In [1]:
import ultralytics
ultralytics.checks()

Ultralytics YOLOv8.1.0 🚀 Python-3.9.12 torch-2.0.0 CPU (Apple M1 Pro)
Setup complete ✅ (10 CPUs, 16.0 GB RAM, 480.9/926.4 GB disk)

In [ ]:
# # Online

# Basepath = '/content/drive/Shareddrives/Wenlan/SVI_Waste/'

# ReadInCSV = Basepath + 'self_uni.csv'
# # ReadInCSV = Basepath + 'GSVI_uni.csv'
# OutputCSV = Basepath + 'self_yolo_0318.csv'
# Typepath = 'GSVI/'
# # Typepath = 'Self/'

In [8]:
# Local

Basepath = '/Users/wenlanzhang/PycharmProjects/SVI_Waste/Data/Output/'
Date = '0315/'
# ReadInCSV = Basepath + 'Self' + 'self_uni.csv'
ReadInCSV = Basepath + 'GSVI/' + 'GSVI_uni.csv'
OutputCSV = Basepath + 'GSVI/' + Date + 'GSVI_yolo_0318.csv'
GSVIpath = '/Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/'
Typepath = 'GSVI/'
# Typepath = 'Self/'

In [14]:
Self1 = pd.read_csv(ReadInCSV)
Self1

,panoid,lat,lon,year,month,img_path,angle,type,img_name
0,---kW5kLNFT2eKu77K0BSg,-1.337135,36.735751,2021,7,-/-/,0,GSVI,---kW5kLNFT2eKu77K0BSg_0
1,---kW5kLNFT2eKu77K0BSg,-1.337135,36.735751,2021,7,-/-/,90,GSVI,---kW5kLNFT2eKu77K0BSg_90
2,---kW5kLNFT2eKu77K0BSg,-1.337135,36.735751,2021,7,-/-/,180,GSVI,---kW5kLNFT2eKu77K0BSg_180
3,---kW5kLNFT2eKu77K0BSg,-1.337135,36.735751,2021,7,-/-/,270,GSVI,---kW5kLNFT2eKu77K0BSg_270
4,--3w2NTa6dWsDSlB7lQqiA,-1.304348,36.742095,2018,1,-/-/,0,GSVI,--3w2NTa6dWsDSlB7lQqiA_0
...,...,...,...,...,...,...,...,...,...
453359,zzz5Wt_DGV8LAzRSfKZWiQ,-1.287985,37.044124,2021,10,Z/Z/,270,GSVI,zzz5Wt_DGV8LAzRSfKZWiQ_270
453360,zzzaSItdTD9Tirtzu6aDnA,-1.274018,37.035957,2021,10,Z/Z/,0,GSVI,zzzaSItdTD9Tirtzu6aDnA_0
453361,zzzaSItdTD9Tirtzu6aDnA,-1.274018,37.035957,2021,10,Z/Z/,90,GSVI,zzzaSItdTD9Tirtzu6aDnA_90
453362,zzzaSItdTD9Tirtzu6aDnA,-1.274018,37.035957,2021,10,Z/Z/,180,GSVI,zzzaSItdTD9Tirtzu6aDnA_180
453363,zzzaSItdTD9Tirtzu6aDnA,-1.274018,37.035957,2021,10,Z/Z/,270,GSVI,zzzaSItdTD9Tirtzu6aDnA_270

In [10]:
import pandas as pd
import numpy as np
import os

# Load the CSV file into a DataFrame
Self = pd.read_csv(ReadInCSV)
Self

/var/folders/2_/nk9j6sb901n_fk5dz_9vtqj80000gn/T/ipykernel_59455/2669019128.py:5: DtypeWarning: Columns (9,10) have mixed types. Specify dtype option on import or set low_memory=False.
  Self = pd.read_csv('/Users/wenlanzhang/Downloads/out.csv')

,panoid,lat,lon,year,month,img_path,angle,type,img_name,conf,bbox
0,---kW5kLNFT2eKu77K0BSg,-1.337135,36.735751,2021,7,-/-/,0,GSVI,---kW5kLNFT2eKu77K0BSg_0,-1,-1
1,---kW5kLNFT2eKu77K0BSg,-1.337135,36.735751,2021,7,-/-/,90,GSVI,---kW5kLNFT2eKu77K0BSg_90,[],[]
2,---kW5kLNFT2eKu77K0BSg,-1.337135,36.735751,2021,7,-/-/,180,GSVI,---kW5kLNFT2eKu77K0BSg_180,[],[]
3,---kW5kLNFT2eKu77K0BSg,-1.337135,36.735751,2021,7,-/-/,270,GSVI,---kW5kLNFT2eKu77K0BSg_270,[],[]
4,--3w2NTa6dWsDSlB7lQqiA,-1.304348,36.742095,2018,1,-/-/,0,GSVI,--3w2NTa6dWsDSlB7lQqiA_0,[],[]
...,...,...,...,...,...,...,...,...,...,...,...
453359,zzz5Wt_DGV8LAzRSfKZWiQ,-1.287985,37.044124,2021,10,Z/Z/,270,GSVI,zzz5Wt_DGV8LAzRSfKZWiQ_270,NaN,NaN
453360,zzzaSItdTD9Tirtzu6aDnA,-1.274018,37.035957,2021,10,Z/Z/,0,GSVI,zzzaSItdTD9Tirtzu6aDnA_0,NaN,NaN
453361,zzzaSItdTD9Tirtzu6aDnA,-1.274018,37.035957,2021,10,Z/Z/,90,GSVI,zzzaSItdTD9Tirtzu6aDnA_90,NaN,NaN
453362,zzzaSItdTD9Tirtzu6aDnA,-1.274018,37.035957,2021,10,Z/Z/,180,GSVI,zzzaSItdTD9Tirtzu6aDnA_180,NaN,NaN
453363,zzzaSItdTD9Tirtzu6aDnA,-1.274018,37.035957,2021,10,Z/Z/,270,GSVI,zzzaSItdTD9Tirtzu6aDnA_270,NaN,NaN

In [11]:
# df_test = Self.iloc[373020:373028]
# df_test = Self
df_test

,panoid,lat,lon,year,month,img_path,angle,type,img_name,conf,bbox
373020,obTl2FZtg9PhKBNGkzJBVQ,-1.284124,37.003164,2018,2,O/B/,0,GSVI,obTl2FZtg9PhKBNGkzJBVQ_0,[],[]
373021,obTl2FZtg9PhKBNGkzJBVQ,-1.284124,37.003164,2018,2,O/B/,90,GSVI,obTl2FZtg9PhKBNGkzJBVQ_90,[],[]
373022,obTl2FZtg9PhKBNGkzJBVQ,-1.284124,37.003164,2018,2,O/B/,180,GSVI,obTl2FZtg9PhKBNGkzJBVQ_180,[],[]
373023,obTl2FZtg9PhKBNGkzJBVQ,-1.284124,37.003164,2018,2,O/B/,270,GSVI,obTl2FZtg9PhKBNGkzJBVQ_270,NaN,NaN
373024,obZ8BRSYaWNPFbbAXas4pg,-1.262416,36.924612,2018,2,O/B/,0,GSVI,obZ8BRSYaWNPFbbAXas4pg_0,NaN,NaN
373025,obZ8BRSYaWNPFbbAXas4pg,-1.262416,36.924612,2018,2,O/B/,90,GSVI,obZ8BRSYaWNPFbbAXas4pg_90,NaN,NaN
373026,obZ8BRSYaWNPFbbAXas4pg,-1.262416,36.924612,2018,2,O/B/,180,GSVI,obZ8BRSYaWNPFbbAXas4pg_180,NaN,NaN
373027,obZ8BRSYaWNPFbbAXas4pg,-1.262416,36.924612,2018,2,O/B/,270,GSVI,obZ8BRSYaWNPFbbAXas4pg_270,NaN,NaN

In [3]:
# Test Model setup

from ultralytics import YOLO
import os

model = YOLO('/Users/wenlanzhang/PycharmProjects/SVI_Waste/Yolo8/Customised_Model/waste_0315.pt')
# load a pretrained model (recommended for training)

In [ ]:
df_test['conf'] = np.nan  # Initialize the 'conf' column if not already present
df_test['bbox'] = np.nan  # Initialize the 'bbox' column to store bounding box information

In [17]:
# Working

import os
import numpy as np

def check_and_correct_path(base_path, type_path, img_folder, modified_img_name):
    # List of possible extensions to try if the default doesn't exist
    possible_extensions = ['.JPG', '.jpg', '.png']
    for ext in possible_extensions:
        # Replace the extension in the modified image name
        name, _ = os.path.splitext(modified_img_name)
#         test_path = os.path.join(base_path, type_path, img_folder, name + ext)
        test_path = os.path.join(GSVIpath, img_folder, name + ext)
        if os.path.exists(test_path):
            return test_path  # Return the corrected path if file exists
    return None  # Return None if no valid path is found

for index, row in df_test.iterrows():

    try:
        img_folder = row['img_path']
        modified_img_name = row['img_name'] + '.JPG'
        source_path = os.path.join(Basepath, Typepath, img_folder, modified_img_name)

        # Check and correct the source path if necessary
        corrected_source_path = check_and_correct_path(Basepath, Typepath, img_folder, modified_img_name)
        if corrected_source_path is None:
            print(f"Error: Image file does not exist for index {index}. Tried multiple extensions.")
            raise FileNotFoundError("Valid image file not found after trying multiple extensions.")

        results = model(corrected_source_path)  # Run the YOLO model with the corrected path
        conf_list = results[0].boxes.cpu().conf.numpy().tolist()  # Get confidence scores as a list
        bbox_list = results[0].boxes.cpu().xyxy.numpy().tolist()  # Get bounding box information as a list

        df_test.at[index, 'conf'] = conf_list  # Store the confidence scores in 'conf' column
        df_test.at[index, 'bbox'] = bbox_list  # Store the bounding box information in 'bbox' column
    except Exception as e:
        print(f"Error processing index {index}: {e}")
        # Optionally, mark rows that failed processing for review
        df_test.at[index, 'conf'] = '-1'
        df_test.at[index, 'bbox'] = '-1'
df_test

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/O/B/obTl2FZtg9PhKBNGkzJBVQ_0.JPG: 480x640 (no detections), 361.4ms
Speed: 2.3ms preprocess, 361.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/O/B/obTl2FZtg9PhKBNGkzJBVQ_90.JPG: 480x640 (no detections), 262.2ms
Speed: 1.3ms preprocess, 262.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/O/B/obTl2FZtg9PhKBNGkzJBVQ_180.JPG: 480x640 (no detections), 263.4ms
Speed: 1.1ms preprocess, 263.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/O/B/obTl2FZtg9PhKBNGkzJBVQ_270.JPG: 480x640 (no detections), 278.9ms
Speed: 1.2ms preprocess, 278.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/O/B/obZ8BRSYaWNPFbbAXas4pg_0.JPG: 480x640 (no detections), 288.6ms
Speed: 1.4ms preprocess, 288.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/O/B/obZ8BRSYaWNPFbbAXas4pg_90.JPG: 480x640 (no detections), 281.7ms
Speed: 1.6ms preprocess, 281.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/O/B/obZ8BRSYaWNPFbbAXas4pg_180.JPG: 480x640 (no detections), 279.1ms
Speed: 1.2ms preprocess, 279.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/O/B/obZ8BRSYaWNPFbbAXas4pg_270.JPG: 480x640 (no detections), 263.5ms
Speed: 1.4ms preprocess, 263.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

,panoid,lat,lon,year,month,img_path,angle,type,img_name,conf,bbox
373020,obTl2FZtg9PhKBNGkzJBVQ,-1.284124,37.003164,2018,2,O/B/,0,GSVI,obTl2FZtg9PhKBNGkzJBVQ_0,[],[]
373021,obTl2FZtg9PhKBNGkzJBVQ,-1.284124,37.003164,2018,2,O/B/,90,GSVI,obTl2FZtg9PhKBNGkzJBVQ_90,[],[]
373022,obTl2FZtg9PhKBNGkzJBVQ,-1.284124,37.003164,2018,2,O/B/,180,GSVI,obTl2FZtg9PhKBNGkzJBVQ_180,[],[]
373023,obTl2FZtg9PhKBNGkzJBVQ,-1.284124,37.003164,2018,2,O/B/,270,GSVI,obTl2FZtg9PhKBNGkzJBVQ_270,[],[]
373024,obZ8BRSYaWNPFbbAXas4pg,-1.262416,36.924612,2018,2,O/B/,0,GSVI,obZ8BRSYaWNPFbbAXas4pg_0,[],[]
373025,obZ8BRSYaWNPFbbAXas4pg,-1.262416,36.924612,2018,2,O/B/,90,GSVI,obZ8BRSYaWNPFbbAXas4pg_90,[],[]
373026,obZ8BRSYaWNPFbbAXas4pg,-1.262416,36.924612,2018,2,O/B/,180,GSVI,obZ8BRSYaWNPFbbAXas4pg_180,[],[]
373027,obZ8BRSYaWNPFbbAXas4pg,-1.262416,36.924612,2018,2,O/B/,270,GSVI,obZ8BRSYaWNPFbbAXas4pg_270,[],[]

In [10]:
df_test.to_csv('/Users/wenlanzhang/Downloads/out.csv', index=False)

# Run Continue

In [5]:
import pandas as pd
import numpy as np
import os

Self = pd.read_csv('/Users/wenlanzhang/PycharmProjects/SVI_Waste/Data/Output/Self/0315/self_yolo_0318.csv')
Self

,Unnamed: 0,panoid,lat,lon,year,month,img_path,angle,type,img_name,conf,bbox
0,0,IMG_7790,-1.314089,36.872331,2023,2,Used/,NaN,Self,IMG_7790,-1,-1
1,1,IMG_0799,-1.366022,36.766883,2023,2,Used/,NaN,Self,IMG_0799,[],[]
2,2,IMG_6303,-1.251897,36.825386,2023,2,Used/,NaN,Self,IMG_6303,[0.4785332679748535],"[[384.7498779296875, 2212.64599609375, 4032.0,..."
3,3,IMG_0772,-1.346758,36.765344,2023,2,Used/,NaN,Self,IMG_0772,[],[]
4,4,IMG_8448,-1.279731,37.049336,2023,2,Used/,NaN,Self,IMG_8448,[],[]
...,...,...,...,...,...,...,...,...,...,...,...,...
2323,2323,IMG_20230212_081016,-1.307547,36.734650,2023,2,Used/,NaN,Self,IMG_20230212_081016,[],[]
2324,2324,IMG_20230212_081003,-1.307619,36.734650,2023,2,Used/,NaN,Self,IMG_20230212_081003,[],[]
2325,2325,IMG_20230212_081017,-1.307547,36.734650,2023,2,Used/,NaN,Self,IMG_20230212_081017,[],[]
2326,2326,IMG_20230212_082052,-1.256017,36.662819,2023,2,Used/,NaN,Self,IMG_20230212_082052,[],[]
2327,2327,IMG_20230212_080902,-1.305370,36.743504,2023,2,Used/,NaN,Self,IMG_20230212_080902,[],[]

In [6]:
rows_done_conf = Self[Self['conf'].notna()]
rows_done_conf

,Unnamed: 0,panoid,lat,lon,year,month,img_path,angle,type,img_name,conf,bbox
0,0,IMG_7790,-1.314089,36.872331,2023,2,Used/,NaN,Self,IMG_7790,-1,-1
1,1,IMG_0799,-1.366022,36.766883,2023,2,Used/,NaN,Self,IMG_0799,[],[]
2,2,IMG_6303,-1.251897,36.825386,2023,2,Used/,NaN,Self,IMG_6303,[0.4785332679748535],"[[384.7498779296875, 2212.64599609375, 4032.0,..."
3,3,IMG_0772,-1.346758,36.765344,2023,2,Used/,NaN,Self,IMG_0772,[],[]
4,4,IMG_8448,-1.279731,37.049336,2023,2,Used/,NaN,Self,IMG_8448,[],[]
...,...,...,...,...,...,...,...,...,...,...,...,...
2323,2323,IMG_20230212_081016,-1.307547,36.734650,2023,2,Used/,NaN,Self,IMG_20230212_081016,[],[]
2324,2324,IMG_20230212_081003,-1.307619,36.734650,2023,2,Used/,NaN,Self,IMG_20230212_081003,[],[]
2325,2325,IMG_20230212_081017,-1.307547,36.734650,2023,2,Used/,NaN,Self,IMG_20230212_081017,[],[]
2326,2326,IMG_20230212_082052,-1.256017,36.662819,2023,2,Used/,NaN,Self,IMG_20230212_082052,[],[]
2327,2327,IMG_20230212_080902,-1.305370,36.743504,2023,2,Used/,NaN,Self,IMG_20230212_080902,[],[]

In [7]:
# Check detected waste piles
rows_done_conf = Self[(Self['conf'] != '-1')]

rows_done_conf

,Unnamed: 0,panoid,lat,lon,year,month,img_path,angle,type,img_name,conf,bbox
1,1,IMG_0799,-1.366022,36.766883,2023,2,Used/,NaN,Self,IMG_0799,[],[]
2,2,IMG_6303,-1.251897,36.825386,2023,2,Used/,NaN,Self,IMG_6303,[0.4785332679748535],"[[384.7498779296875, 2212.64599609375, 4032.0,..."
3,3,IMG_0772,-1.346758,36.765344,2023,2,Used/,NaN,Self,IMG_0772,[],[]
4,4,IMG_8448,-1.279731,37.049336,2023,2,Used/,NaN,Self,IMG_8448,[],[]
5,5,IMG_6465,-1.306939,36.783822,2023,2,Used/,NaN,Self,IMG_6465,[],[]
...,...,...,...,...,...,...,...,...,...,...,...,...
2323,2323,IMG_20230212_081016,-1.307547,36.734650,2023,2,Used/,NaN,Self,IMG_20230212_081016,[],[]
2324,2324,IMG_20230212_081003,-1.307619,36.734650,2023,2,Used/,NaN,Self,IMG_20230212_081003,[],[]
2325,2325,IMG_20230212_081017,-1.307547,36.734650,2023,2,Used/,NaN,Self,IMG_20230212_081017,[],[]
2326,2326,IMG_20230212_082052,-1.256017,36.662819,2023,2,Used/,NaN,Self,IMG_20230212_082052,[],[]
2327,2327,IMG_20230212_080902,-1.305370,36.743504,2023,2,Used/,NaN,Self,IMG_20230212_080902,[],[]

In [8]:
# Check detected waste piles - 1
filtered_df = rows_done_conf[(rows_done_conf['conf'] != '[]')]

filtered_df

,Unnamed: 0,panoid,lat,lon,year,month,img_path,angle,type,img_name,conf,bbox
2,2,IMG_6303,-1.251897,36.825386,2023,2,Used/,NaN,Self,IMG_6303,[0.4785332679748535],"[[384.7498779296875, 2212.64599609375, 4032.0,..."
13,13,IMG_8474,-1.279736,37.048789,2023,2,Used/,NaN,Self,IMG_8474,"[0.6306285262107849, 0.35508689284324646]","[[0.0, 2415.912353515625, 3441.830810546875, 3..."
16,16,IMG_7035,-1.315686,36.788967,2023,2,Used/,NaN,Self,IMG_7035,[0.42672640085220337],"[[0.0, 1964.566650390625, 2074.377197265625, 2..."
36,36,IMG_7814,-1.312628,36.870944,2023,2,Used/,NaN,Self,IMG_7814,[0.7073689699172974],"[[1410.309814453125, 2866.137939453125, 3024.0..."
43,43,IMG_7169,-1.289706,36.797764,2023,2,Used/,NaN,Self,IMG_7169,[0.5590984225273132],"[[1534.6220703125, 2255.146484375, 2174.851074..."
...,...,...,...,...,...,...,...,...,...,...,...,...
2163,2163,IMG_20230212_080702,-1.299250,36.762955,2023,2,Used/,NaN,Self,IMG_20230212_080702,[0.6712612509727478],"[[2035.4974365234375, 1610.3468017578125, 3923..."
2220,2220,IMG_20230212_081057,-1.310380,36.728580,2023,2,Used/,NaN,Self,IMG_20230212_081057,[0.3117744028568268],"[[96.38277435302734, 58.593448638916016, 595.2..."
2270,2270,IMG_20230212_081315,-1.305153,36.715748,2023,2,Used/,NaN,Self,IMG_20230212_081315,[0.5058714747428894],"[[10.408954620361328, 1511.929443359375, 894.9..."
2301,2301,IMG_20230212_081945,-1.260575,36.661160,2023,2,Used/,NaN,Self,IMG_20230212_081945,[0.454032301902771],"[[0.0, 2120.92578125, 1944.1778564453125, 2704..."
2315,2315,IMG_20230212_080929,-1.306133,36.739262,2023,2,Used/,NaN,Self,IMG_20230212_080929,[0.6454396843910217],"[[45.757545471191406, 2217.74853515625, 1195.7..."

In [21]:
# rows_nan_conf = Self[pd.isna(Self['conf'])]
rows_nan_conf = Self[(Self['conf'] == '-1')]
# rows_nan_conf

df_test = rows_nan_conf
df_test

,panoid,lat,lon,year,month,img_path,angle,type,img_name,conf,bbox
0,---kW5kLNFT2eKu77K0BSg,-1.337135,36.735751,2021,7,-/-/,0,GSVI,---kW5kLNFT2eKu77K0BSg_0,-1,-1
427651,wKlN_0tazFZq3y4MyMOlAQ,-1.287796,36.859518,2018,2,w/K/,270,GSVI,wKlN_0tazFZq3y4MyMOlAQ_270,-1,-1
427652,wKmT7fZA7_wzInsXTekmlg,-1.271826,36.972277,2018,2,w/K/,0,GSVI,wKmT7fZA7_wzInsXTekmlg_0,-1,-1
427653,wKmT7fZA7_wzInsXTekmlg,-1.271826,36.972277,2018,2,w/K/,90,GSVI,wKmT7fZA7_wzInsXTekmlg_90,-1,-1
427654,wKmT7fZA7_wzInsXTekmlg,-1.271826,36.972277,2018,2,w/K/,180,GSVI,wKmT7fZA7_wzInsXTekmlg_180,-1,-1
...,...,...,...,...,...,...,...,...,...,...,...
453359,zzz5Wt_DGV8LAzRSfKZWiQ,-1.287985,37.044124,2021,10,Z/Z/,270,GSVI,zzz5Wt_DGV8LAzRSfKZWiQ_270,-1,-1
453360,zzzaSItdTD9Tirtzu6aDnA,-1.274018,37.035957,2021,10,Z/Z/,0,GSVI,zzzaSItdTD9Tirtzu6aDnA_0,-1,-1
453361,zzzaSItdTD9Tirtzu6aDnA,-1.274018,37.035957,2021,10,Z/Z/,90,GSVI,zzzaSItdTD9Tirtzu6aDnA_90,-1,-1
453362,zzzaSItdTD9Tirtzu6aDnA,-1.274018,37.035957,2021,10,Z/Z/,180,GSVI,zzzaSItdTD9Tirtzu6aDnA_180,-1,-1
453363,zzzaSItdTD9Tirtzu6aDnA,-1.274018,37.035957,2021,10,Z/Z/,270,GSVI,zzzaSItdTD9Tirtzu6aDnA_270,-1,-1

In [22]:
# Continue testing

import os
import numpy as np

def check_and_correct_path(base_path, type_path, img_folder, modified_img_name):
    # List of possible extensions to try if the default doesn't exist
    possible_extensions = ['.JPG', '.jpg', '.png']
    for ext in possible_extensions:
        # Replace the extension in the modified image name
        name, _ = os.path.splitext(modified_img_name)
#         test_path = os.path.join(base_path, type_path, img_folder, name + ext)
        test_path = os.path.join(GSVIpath, img_folder, name + ext)
        if os.path.exists(test_path):
            return test_path  # Return the corrected path if file exists
    return None  # Return None if no valid path is found

for index, row in df_test.iterrows():

    try:
        img_folder = row['img_path']
        modified_img_name = row['img_name'] + '.JPG'
        source_path = os.path.join(Basepath, Typepath, img_folder, modified_img_name)

        # Check and correct the source path if necessary
        corrected_source_path = check_and_correct_path(Basepath, Typepath, img_folder, modified_img_name)
        if corrected_source_path is None:
            print(f"Error: Image file does not exist for index {index}. Tried multiple extensions.")
            raise FileNotFoundError("Valid image file not found after trying multiple extensions.")

        results = model(corrected_source_path)  # Run the YOLO model with the corrected path
        conf_list = results[0].boxes.cpu().conf.numpy().tolist()  # Get confidence scores as a list
        bbox_list = results[0].boxes.cpu().xyxy.numpy().tolist()  # Get bounding box information as a list

        df_test.at[index, 'conf'] = conf_list  # Store the confidence scores in 'conf' column
        df_test.at[index, 'bbox'] = bbox_list  # Store the bounding box information in 'bbox' column
    except Exception as e:
        print(f"Error processing index {index}: {e}")
        # Optionally, mark rows that failed processing for review
        df_test.at[index, 'conf'] = '-1'
        df_test.at[index, 'bbox'] = '-1'
df_test

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/-/-/---kW5kLNFT2eKu77K0BSg_0.JPG: 480x640 (no detections), 394.9ms
Speed: 2.1ms preprocess, 394.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wKlN_0tazFZq3y4MyMOlAQ_270.JPG: 480x640 (no detections), 285.3ms
Speed: 1.6ms preprocess, 285.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wKmT7fZA7_wzInsXTekmlg_0.JPG: 480x640 1 Waste, 284.0ms
Speed: 1.2ms preprocess, 284.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wKmT7fZA7_wzInsXTekmlg_90.JPG: 480x640 (no detections), 321.7ms
Speed: 1.2ms preprocess, 321.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wKmT7fZA7_wzInsXTekmlg_180.JPG: 480x640 (no detections), 272.0ms
Speed: 1.2ms preprocess, 272.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wKmT7fZA7_wzInsXTekmlg_270.JPG: 480x640 (no detections), 274.7ms
Speed: 1.1ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wKmYDCuIcDUMAu_g4kO5aw_0.JPG: 480x640 (no detections), 272.9ms
Speed: 1.5ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wKmYDCuIcDUMAu_g4kO5aw_90.JPG: 480x640 1 Waste, 267.3ms
Speed: 1.0ms preprocess, 267.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wKmYDCuIcDUMAu_g4kO5aw_180.JPG: 480x640 1 Waste, 269.5ms
Speed: 1.2ms preprocess, 269.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wKmYDCuIcDUMAu_g4kO5aw_270.JPG: 480x640 (no detections), 264.7ms
Speed: 1.0ms preprocess, 264.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wKnfyGW35TQbGmPT17W7Ew_0.JPG: 480x640 (no detections), 266.5ms
Speed: 1.2ms preprocess, 266.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wKnfyGW35TQbGmPT17W7Ew_90.JPG: 480x640 (no detections), 267.8ms
Speed: 1.0ms preprocess, 267.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wKnfyGW35TQbGmPT17W7Ew_180.JPG: 480x640 (no detections), 266.8ms
Speed: 1.1ms preprocess, 266.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wKnfyGW35TQbGmPT17W7Ew_270.JPG: 480x640 (no detections), 266.7ms
Speed: 1.0ms preprocess, 266.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wKoGvML2WP5hxRN-Os-rWw_0.JPG: 480x640 (no detections), 267.0ms
Speed: 1.0ms preprocess, 267.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wKoGvML2WP5hxRN-Os-rWw_90.JPG: 480x640 (no detections), 266.2ms
Speed: 1.0ms preprocess, 266.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wKoGvML2WP5hxRN-Os-rWw_180.JPG: 480x640 (no detections), 268.2ms
Speed: 1.0ms preprocess, 268.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wKoGvML2WP5hxRN-Os-rWw_270.JPG: 480x640 (no detections), 271.1ms
Speed: 1.0ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wKpD4Go40pK5uy368izqQg_0.JPG: 480x640 (no detections), 271.0ms
Speed: 1.5ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wKpD4Go40pK5uy368izqQg_90.JPG: 480x640 (no detections), 269.1ms
Speed: 1.2ms preprocess, 269.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wKpD4Go40pK5uy368izqQg_180.JPG: 480x640 (no detections), 266.1ms
Speed: 1.1ms preprocess, 266.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wKpD4Go40pK5uy368izqQg_270.JPG: 480x640 (no detections), 267.2ms
Speed: 1.3ms preprocess, 267.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wKpdRb_HC4jKG6gYHEO3gQ_0.JPG: 480x640 (no detections), 271.7ms
Speed: 1.2ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wKpdRb_HC4jKG6gYHEO3gQ_90.JPG: 480x640 (no detections), 268.1ms
Speed: 1.1ms preprocess, 268.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wKpdRb_HC4jKG6gYHEO3gQ_180.JPG: 480x640 (no detections), 269.3ms
Speed: 1.1ms preprocess, 269.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wKpdRb_HC4jKG6gYHEO3gQ_270.JPG: 480x640 (no detections), 267.5ms
Speed: 1.1ms preprocess, 267.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wKqfKjk-bdAE7v53M8wB1g_0.JPG: 480x640 (no detections), 271.0ms
Speed: 1.0ms preprocess, 271.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wKqfKjk-bdAE7v53M8wB1g_90.JPG: 480x640 (no detections), 268.6ms
Speed: 1.1ms preprocess, 268.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wKqfKjk-bdAE7v53M8wB1g_180.JPG: 480x640 (no detections), 269.4ms
Speed: 1.1ms preprocess, 269.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wKqfKjk-bdAE7v53M8wB1g_270.JPG: 480x640 (no detections), 274.0ms
Speed: 1.0ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wKrJjuLshHHGERZ6nmjl3Q_0.JPG: 480x640 (no detections), 268.9ms
Speed: 1.0ms preprocess, 268.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wKrJjuLshHHGERZ6nmjl3Q_90.JPG: 480x640 (no detections), 270.8ms
Speed: 1.2ms preprocess, 270.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wKrJjuLshHHGERZ6nmjl3Q_180.JPG: 480x640 (no detections), 278.9ms
Speed: 1.1ms preprocess, 278.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wKrJjuLshHHGERZ6nmjl3Q_270.JPG: 480x640 (no detections), 280.5ms

Speed: 1.1ms preprocess, 280.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wKssFVUcSP6L-YGZ9UUx3A_0.JPG: 480x640 (no detections), 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wKssFVUcSP6L-YGZ9UUx3A_90.JPG: 480x640 (no detections), 281.4ms
Speed: 1.2ms preprocess, 281.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wKssFVUcSP6L-YGZ9UUx3A_180.JPG: 480x640 (no detections), 271.9ms
Speed: 1.4ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wKssFVUcSP6L-YGZ9UUx3A_270.JPG: 480x640 (no detections), 282.2ms
Speed: 1.3ms preprocess, 282.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wL1LHr3rEmvhleBEQ5sM4w_0.JPG: 480x640 (no detections), 266.5ms
Speed: 1.4ms preprocess, 266.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wL1LHr3rEmvhleBEQ5sM4w_90.JPG: 480x640 (no detections), 274.7ms
Speed: 1.1ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wL1LHr3rEmvhleBEQ5sM4w_180.JPG: 480x640 (no detections), 270.3ms
Speed: 1.7ms preprocess, 270.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wL1LHr3rEmvhleBEQ5sM4w_270.JPG: 480x640 (no detections), 269.7ms
Speed: 1.2ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wL1oZpLUw8aZPJlHjv1klw_0.JPG: 480x640 (no detections), 278.8ms
Speed: 1.1ms preprocess, 278.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wL1oZpLUw8aZPJlHjv1klw_90.JPG: 480x640 (no detections), 264.3ms
Speed: 1.2ms preprocess, 264.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wL1oZpLUw8aZPJlHjv1klw_180.JPG: 480x640 (no detections), 263.6ms
Speed: 1.0ms preprocess, 263.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wL1oZpLUw8aZPJlHjv1klw_270.JPG: 480x640 (no detections), 267.0ms
Speed: 1.0ms preprocess, 267.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wL1s0DSSANkJtpno8WOEGQ_0.JPG: 480x640 (no detections), 269.2ms
Speed: 1.1ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wL1s0DSSANkJtpno8WOEGQ_90.JPG: 480x640 (no detections), 278.2ms
Speed: 1.1ms preprocess, 278.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wL1s0DSSANkJtpno8WOEGQ_180.JPG: 480x640 (no detections), 297.4ms
Speed: 1.7ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wL1s0DSSANkJtpno8WOEGQ_270.JPG: 480x640 (no detections), 286.7ms
Speed: 1.7ms preprocess, 286.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wL3CbbT5j_clBkWSgTIlcA_0.JPG: 480x640 (no detections), 280.0ms
Speed: 2.0ms preprocess, 280.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wL3CbbT5j_clBkWSgTIlcA_90.JPG: 480x640 (no detections), 286.3ms
Speed: 1.4ms preprocess, 286.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wL3CbbT5j_clBkWSgTIlcA_180.JPG: 480x640 (no detections), 297.0ms
Speed: 1.3ms preprocess, 297.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wL3CbbT5j_clBkWSgTIlcA_270.JPG: 480x640 (no detections), 276.6ms
Speed: 1.3ms preprocess, 276.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wL3kmvXXCTLejGVp7MBnCA_0.JPG: 480x640 (no detections), 275.0ms
Speed: 1.1ms preprocess, 275.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wL3kmvXXCTLejGVp7MBnCA_90.JPG: 480x640 (no detections), 299.6ms
Speed: 1.4ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wL3kmvXXCTLejGVp7MBnCA_180.JPG: 480x640 (no detections), 294.8ms
Speed: 1.7ms preprocess, 294.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wL3kmvXXCTLejGVp7MBnCA_270.JPG: 480x640 (no detections), 287.5ms
Speed: 1.3ms preprocess, 287.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wL86QJGrNqlVDLcN6cuD_Q_0.JPG: 480x640 (no detections), 322.5ms
Speed: 1.5ms preprocess, 322.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wL86QJGrNqlVDLcN6cuD_Q_90.JPG: 480x640 (no detections), 266.5ms
Speed: 1.5ms preprocess, 266.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wL86QJGrNqlVDLcN6cuD_Q_180.JPG: 480x640 (no detections), 275.3ms
Speed: 1.1ms preprocess, 275.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wL86QJGrNqlVDLcN6cuD_Q_270.JPG: 480x640 (no detections), 268.2ms
Speed: 1.3ms preprocess, 268.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wL8iEdLuzJcky3I4SiFUMA_0.JPG: 480x640 (no detections), 273.5ms
Speed: 1.4ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wL8iEdLuzJcky3I4SiFUMA_90.JPG: 480x640 (no detections), 268.8ms
Speed: 1.1ms preprocess, 268.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wL8iEdLuzJcky3I4SiFUMA_180.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wL8iEdLuzJcky3I4SiFUMA_270.JPG: 480x640 (no detections), 292.7ms
Speed: 1.4ms preprocess, 292.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLDgF2RoHcW68abaHanC7w_0.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLDgF2RoHcW68abaHanC7w_90.JPG: 480x640 (no detections), 268.6ms
Speed: 1.2ms preprocess, 268.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLDgF2RoHcW68abaHanC7w_180.JPG: 480x640 (no detections), 268.9ms
Speed: 1.1ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLDgF2RoHcW68abaHanC7w_270.JPG: 480x640 (no detections), 268.4ms
Speed: 1.1ms preprocess, 268.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLFd5_KXIFM_EpLYDpFDxg_0.JPG: 480x640 (no detections), 269.4ms
Speed: 1.0ms preprocess, 269.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLFd5_KXIFM_EpLYDpFDxg_90.JPG: 480x640 (no detections), 268.3ms
Speed: 1.1ms preprocess, 268.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLFd5_KXIFM_EpLYDpFDxg_180.JPG: 480x640 (no detections), 266.7ms
Speed: 1.3ms preprocess, 266.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLFd5_KXIFM_EpLYDpFDxg_270.JPG: 480x640 (no detections), 269.2ms
Speed: 1.1ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLG3ceA5qOQRKkrQ9fx9Tw_0.JPG: 480x640 (no detections), 265.2ms
Speed: 1.0ms preprocess, 265.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLG3ceA5qOQRKkrQ9fx9Tw_90.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLG3ceA5qOQRKkrQ9fx9Tw_180.JPG: 480x640 (no detections), 267.0ms
Speed: 1.1ms preprocess, 267.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLG3ceA5qOQRKkrQ9fx9Tw_270.JPG: 480x640 (no detections), 269.6ms
Speed: 1.0ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLH2l5n82iimpG9PtoOJrw_0.JPG: 480x640 (no detections), 268.3ms
Speed: 1.0ms preprocess, 268.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLH2l5n82iimpG9PtoOJrw_90.JPG: 480x640 (no detections), 266.0ms
Speed: 1.1ms preprocess, 266.0ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLH2l5n82iimpG9PtoOJrw_180.JPG: 480x640 (no detections), 271.0ms
Speed: 1.0ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLH2l5n82iimpG9PtoOJrw_270.JPG: 480x640 (no detections), 274.0ms
Speed: 1.1ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLHai0GM0I4NQEMKrYW5SA_0.JPG: 480x640 (no detections), 269.7ms
Speed: 1.2ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLHai0GM0I4NQEMKrYW5SA_90.JPG: 480x640 (no detections), 268.0ms
Speed: 1.1ms preprocess, 268.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLHai0GM0I4NQEMKrYW5SA_180.JPG: 480x640 (no detections), 266.5ms
Speed: 1.0ms preprocess, 266.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLHai0GM0I4NQEMKrYW5SA_270.JPG: 480x640 (no detections), 271.3ms
Speed: 1.0ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLIA6NOAZm2ImhpqD0aeYQ_0.JPG: 480x640 1 Waste, 268.7ms
Speed: 1.1ms preprocess, 268.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLIA6NOAZm2ImhpqD0aeYQ_90.JPG: 480x640 (no detections), 266.0ms
Speed: 1.0ms preprocess, 266.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLIA6NOAZm2ImhpqD0aeYQ_180.JPG: 480x640 (no detections), 267.3ms
Speed: 1.1ms preprocess, 267.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLIA6NOAZm2ImhpqD0aeYQ_270.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLJNGgRLGmJhHP7IcqqvYA_0.JPG: 480x640 (no detections), 267.2ms
Speed: 1.3ms preprocess, 267.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLJNGgRLGmJhHP7IcqqvYA_90.JPG: 480x640 (no detections), 267.9ms
Speed: 1.0ms preprocess, 267.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLJNGgRLGmJhHP7IcqqvYA_180.JPG: 480x640 (no detections), 268.8ms
Speed: 1.0ms preprocess, 268.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLJNGgRLGmJhHP7IcqqvYA_270.JPG: 480x640 (no detections), 265.8ms
Speed: 1.0ms preprocess, 265.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLM4Q3Z-BNV0z0x3CDzBSA_0.JPG: 480x640 (no detections), 269.4ms
Speed: 1.0ms preprocess, 269.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLM4Q3Z-BNV0z0x3CDzBSA_90.JPG: 480x640 (no detections), 266.0ms
Speed: 1.0ms preprocess, 266.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLM4Q3Z-BNV0z0x3CDzBSA_180.JPG: 480x640 (no detections), 269.6ms
Speed: 1.0ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLM4Q3Z-BNV0z0x3CDzBSA_270.JPG: 480x640 (no detections), 266.2ms
Speed: 1.1ms preprocess, 266.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLRFVdMLmVgq36UdLGfALw_0.JPG: 480x640 (no detections), 267.8ms
Speed: 1.1ms preprocess, 267.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLRFVdMLmVgq36UdLGfALw_90.JPG: 480x640 (no detections), 271.3ms
Speed: 1.2ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLRFVdMLmVgq36UdLGfALw_180.JPG: 480x640 (no detections), 269.4ms

Speed: 1.2ms preprocess, 269.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLRFVdMLmVgq36UdLGfALw_270.JPG: 480x640 (no detections), 270.5ms
Speed: 1.1ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLWVYB5_-opqkljvNEw9xw_0.JPG: 480x640 (no detections), 267.6ms
Speed: 1.0ms preprocess, 267.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLWVYB5_-opqkljvNEw9xw_90.JPG: 480x640 (no detections), 265.5ms
Speed: 1.0ms preprocess, 265.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLWVYB5_-opqkljvNEw9xw_180.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLWVYB5_-opqkljvNEw9xw_270.JPG: 480x640 (no detections), 268.1ms
Speed: 1.5ms preprocess, 268.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLYtOxfjrbeZrrohut_Tlg_0.JPG: 480x640 (no detections), 268.9ms
Speed: 1.0ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLYtOxfjrbeZrrohut_Tlg_90.JPG: 480x640 (no detections), 272.6ms
Speed: 1.0ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLYtOxfjrbeZrrohut_Tlg_180.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLYtOxfjrbeZrrohut_Tlg_270.JPG: 480x640 (no detections), 269.2ms
Speed: 1.1ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLZ78sP2GhbiSYntjiXXqw_0.JPG: 480x640 (no detections), 267.2ms
Speed: 1.1ms preprocess, 267.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLZ78sP2GhbiSYntjiXXqw_90.JPG: 480x640 (no detections), 265.9ms
Speed: 1.5ms preprocess, 265.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLZ78sP2GhbiSYntjiXXqw_180.JPG: 480x640 (no detections), 269.7ms
Speed: 1.4ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLZ78sP2GhbiSYntjiXXqw_270.JPG: 480x640 (no detections), 269.2ms
Speed: 1.1ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLZZW-7S5ixvdmw6G5coMA_0.JPG: 480x640 (no detections), 287.9ms
Speed: 1.0ms preprocess, 287.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLZZW-7S5ixvdmw6G5coMA_90.JPG: 480x640 (no detections), 266.1ms
Speed: 1.1ms preprocess, 266.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLZZW-7S5ixvdmw6G5coMA_180.JPG: 480x640 (no detections), 266.8ms
Speed: 1.0ms preprocess, 266.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLZZW-7S5ixvdmw6G5coMA_270.JPG: 480x640 (no detections), 266.2ms
Speed: 1.0ms preprocess, 266.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLinpm7nm8zrYEG1zdeHtA_0.JPG: 480x640 (no detections), 269.3ms
Speed: 1.1ms preprocess, 269.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLinpm7nm8zrYEG1zdeHtA_90.JPG: 480x640 (no detections), 273.4ms
Speed: 1.0ms preprocess, 273.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLinpm7nm8zrYEG1zdeHtA_180.JPG: 480x640 (no detections), 266.5ms
Speed: 1.2ms preprocess, 266.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLinpm7nm8zrYEG1zdeHtA_270.JPG: 480x640 (no detections), 267.2ms
Speed: 1.1ms preprocess, 267.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLji6oq2kwdK9yeJaMR7NA_0.JPG: 480x640 (no detections), 265.3ms
Speed: 1.0ms preprocess, 265.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLji6oq2kwdK9yeJaMR7NA_90.JPG: 480x640 (no detections), 269.7ms
Speed: 1.0ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLji6oq2kwdK9yeJaMR7NA_180.JPG: 480x640 (no detections), 267.5ms
Speed: 1.1ms preprocess, 267.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLji6oq2kwdK9yeJaMR7NA_270.JPG: 480x640 (no detections), 269.0ms
Speed: 1.1ms preprocess, 269.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLjst_EirRPi0_gC2T0A4w_0.JPG: 480x640 (no detections), 267.7ms
Speed: 1.0ms preprocess, 267.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLjst_EirRPi0_gC2T0A4w_90.JPG: 480x640 (no detections), 265.0ms
Speed: 1.0ms preprocess, 265.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLjst_EirRPi0_gC2T0A4w_180.JPG: 480x640 (no detections), 267.2ms
Speed: 1.0ms preprocess, 267.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLjst_EirRPi0_gC2T0A4w_270.JPG: 480x640 (no detections), 269.6ms
Speed: 1.0ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLkgLhX1hg-EGjq3dvbkSw_0.JPG: 480x640 (no detections), 267.7ms
Speed: 1.0ms preprocess, 267.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLkgLhX1hg-EGjq3dvbkSw_90.JPG: 480x640 (no detections), 269.4ms
Speed: 1.0ms preprocess, 269.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLkgLhX1hg-EGjq3dvbkSw_180.JPG: 480x640 (no detections), 265.9ms
Speed: 1.1ms preprocess, 265.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLkgLhX1hg-EGjq3dvbkSw_270.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLkqz_jEGv4otOeN9E2ftQ_0.JPG: 480x640 (no detections), 274.6ms
Speed: 1.2ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLkqz_jEGv4otOeN9E2ftQ_90.JPG: 480x640 (no detections), 268.2ms
Speed: 1.1ms preprocess, 268.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLkqz_jEGv4otOeN9E2ftQ_180.JPG: 480x640 (no detections), 267.1ms
Speed: 1.0ms preprocess, 267.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLkqz_jEGv4otOeN9E2ftQ_270.JPG: 480x640 (no detections), 268.2ms
Speed: 1.0ms preprocess, 268.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLnKZOxZAaEaiDx0mI9J5Q_0.JPG: 480x640 (no detections), 271.4ms
Speed: 1.0ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLnKZOxZAaEaiDx0mI9J5Q_90.JPG: 480x640 (no detections), 268.0ms
Speed: 1.1ms preprocess, 268.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLnKZOxZAaEaiDx0mI9J5Q_180.JPG: 480x640 (no detections), 267.5ms
Speed: 1.0ms preprocess, 267.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLnKZOxZAaEaiDx0mI9J5Q_270.JPG: 480x640 (no detections), 266.7ms
Speed: 1.0ms preprocess, 266.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLolccjCF0jf0lHRr9qBFQ_0.JPG: 480x640 (no detections), 269.4ms
Speed: 1.0ms preprocess, 269.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLolccjCF0jf0lHRr9qBFQ_90.JPG: 480x640 (no detections), 268.3ms
Speed: 1.2ms preprocess, 268.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLolccjCF0jf0lHRr9qBFQ_180.JPG: 480x640 (no detections), 268.1ms
Speed: 1.1ms preprocess, 268.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLolccjCF0jf0lHRr9qBFQ_270.JPG: 480x640 (no detections), 268.9ms
Speed: 1.0ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLrmXFSx5G3rztLtlxLthQ_0.JPG: 480x640 (no detections), 267.9ms
Speed: 1.1ms preprocess, 267.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLrmXFSx5G3rztLtlxLthQ_90.JPG: 480x640 (no detections), 269.0ms
Speed: 1.0ms preprocess, 269.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLrmXFSx5G3rztLtlxLthQ_180.JPG: 480x640 (no detections), 282.1ms
Speed: 1.0ms preprocess, 282.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLrmXFSx5G3rztLtlxLthQ_270.JPG: 480x640 (no detections), 268.3ms
Speed: 1.2ms preprocess, 268.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLxR9d2vi4DYZGtgAvhtyQ_0.JPG: 480x640 (no detections), 266.4ms
Speed: 1.1ms preprocess, 266.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLxR9d2vi4DYZGtgAvhtyQ_90.JPG: 480x640 (no detections), 268.6ms
Speed: 1.1ms preprocess, 268.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLxR9d2vi4DYZGtgAvhtyQ_180.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLxR9d2vi4DYZGtgAvhtyQ_270.JPG: 480x640 (no detections), 267.8ms
Speed: 1.1ms preprocess, 267.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLyVhGtg8_65RrXDPY7Xpw_0.JPG: 480x640 (no detections), 269.9ms
Speed: 1.0ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLyVhGtg8_65RrXDPY7Xpw_90.JPG: 480x640 (no detections), 269.9ms
Speed: 1.2ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLyVhGtg8_65RrXDPY7Xpw_180.JPG: 480x640 (no detections), 266.2ms
Speed: 1.1ms preprocess, 266.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLyVhGtg8_65RrXDPY7Xpw_270.JPG: 480x640 (no detections), 267.4ms
Speed: 1.0ms preprocess, 267.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLyrdEevUbZabGfwqq79zw_0.JPG: 480x640 (no detections), 266.4ms
Speed: 1.0ms preprocess, 266.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLyrdEevUbZabGfwqq79zw_90.JPG: 480x640 (no detections), 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLyrdEevUbZabGfwqq79zw_180.JPG: 480x640 (no detections), 267.6ms
Speed: 1.0ms preprocess, 267.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLyrdEevUbZabGfwqq79zw_270.JPG: 480x640 (no detections), 266.9ms
Speed: 1.0ms preprocess, 266.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLzKDxmzYNdC9A-bj7GUHA_0.JPG: 480x640 (no detections), 269.5ms
Speed: 1.1ms preprocess, 269.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLzKDxmzYNdC9A-bj7GUHA_90.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLzKDxmzYNdC9A-bj7GUHA_180.JPG: 480x640 (no detections), 268.0ms
Speed: 1.1ms preprocess, 268.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLzKDxmzYNdC9A-bj7GUHA_270.JPG: 480x640 (no detections), 267.1ms
Speed: 1.1ms preprocess, 267.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLza5ltfyQPHSTPsQ6dr0A_0.JPG: 480x640 (no detections), 269.5ms
Speed: 1.1ms preprocess, 269.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLza5ltfyQPHSTPsQ6dr0A_90.JPG: 480x640 (no detections), 266.4ms

Speed: 1.0ms preprocess, 266.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLza5ltfyQPHSTPsQ6dr0A_180.JPG: 480x640 1 Waste, 267.3ms
Speed: 1.5ms preprocess, 267.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wLza5ltfyQPHSTPsQ6dr0A_270.JPG: 480x640 (no detections), 273.9ms
Speed: 1.0ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wM3NMejBVddlt6i3gBDaSQ_0.JPG: 480x640 (no detections), 270.5ms
Speed: 1.0ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wM3NMejBVddlt6i3gBDaSQ_90.JPG: 480x640 (no detections), 267.3ms
Speed: 1.1ms preprocess, 267.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wM3NMejBVddlt6i3gBDaSQ_180.JPG: 480x640 (no detections), 267.6ms
Speed: 1.0ms preprocess, 267.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wM3NMejBVddlt6i3gBDaSQ_270.JPG: 480x640 (no detections), 266.7ms
Speed: 1.0ms preprocess, 266.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wM63xEt_Qq-u1GMBj5OoTw_0.JPG: 480x640 (no detections), 271.8ms
Speed: 1.0ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wM63xEt_Qq-u1GMBj5OoTw_90.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wM63xEt_Qq-u1GMBj5OoTw_180.JPG: 480x640 (no detections), 265.5ms
Speed: 1.0ms preprocess, 265.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wM63xEt_Qq-u1GMBj5OoTw_270.JPG: 480x640 (no detections), 267.8ms
Speed: 1.1ms preprocess, 267.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wM6EMBTMp2RwSS4RaIdi-Q_0.JPG: 480x640 (no detections), 281.3ms
Speed: 1.1ms preprocess, 281.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wM6EMBTMp2RwSS4RaIdi-Q_90.JPG: 480x640 (no detections), 267.1ms
Speed: 1.1ms preprocess, 267.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wM6EMBTMp2RwSS4RaIdi-Q_180.JPG: 480x640 (no detections), 268.2ms
Speed: 1.0ms preprocess, 268.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wM6EMBTMp2RwSS4RaIdi-Q_270.JPG: 480x640 (no detections), 266.5ms
Speed: 1.1ms preprocess, 266.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wM8XIQJGqd8MqjKjnndO1A_0.JPG: 480x640 (no detections), 265.2ms
Speed: 1.0ms preprocess, 265.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wM8XIQJGqd8MqjKjnndO1A_90.JPG: 480x640 (no detections), 268.2ms
Speed: 1.0ms preprocess, 268.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wM8XIQJGqd8MqjKjnndO1A_180.JPG: 480x640 (no detections), 269.9ms
Speed: 1.4ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wM8XIQJGqd8MqjKjnndO1A_270.JPG: 480x640 (no detections), 272.1ms
Speed: 1.1ms preprocess, 272.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wM9ztJowBvBlpSYgpAqXSA_0.JPG: 480x640 (no detections), 269.3ms
Speed: 1.2ms preprocess, 269.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wM9ztJowBvBlpSYgpAqXSA_90.JPG: 480x640 1 Waste, 269.6ms
Speed: 1.1ms preprocess, 269.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wM9ztJowBvBlpSYgpAqXSA_180.JPG: 480x640 (no detections), 266.6ms
Speed: 1.1ms preprocess, 266.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wM9ztJowBvBlpSYgpAqXSA_270.JPG: 480x640 (no detections), 267.0ms
Speed: 1.0ms preprocess, 267.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMHg1HdIbVm6t0J6R-PUTQ_0.JPG: 480x640 (no detections), 267.1ms
Speed: 1.0ms preprocess, 267.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMHg1HdIbVm6t0J6R-PUTQ_90.JPG: 480x640 (no detections), 270.2ms
Speed: 1.0ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMHg1HdIbVm6t0J6R-PUTQ_180.JPG: 480x640 (no detections), 275.2ms
Speed: 1.0ms preprocess, 275.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMHg1HdIbVm6t0J6R-PUTQ_270.JPG: 480x640 (no detections), 273.0ms
Speed: 1.3ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMJPb_AMATXX_M_84Zm9zg_0.JPG: 480x640 (no detections), 271.7ms
Speed: 1.2ms preprocess, 271.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMJPb_AMATXX_M_84Zm9zg_90.JPG: 480x640 (no detections), 270.9ms
Speed: 0.9ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMJPb_AMATXX_M_84Zm9zg_180.JPG: 480x640 (no detections), 268.1ms
Speed: 1.0ms preprocess, 268.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMJPb_AMATXX_M_84Zm9zg_270.JPG: 480x640 (no detections), 271.8ms
Speed: 1.0ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMPuGff9jzo6yIdvAWK24w_0.JPG: 480x640 (no detections), 267.0ms
Speed: 1.1ms preprocess, 267.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMPuGff9jzo6yIdvAWK24w_90.JPG: 480x640 (no detections), 268.7ms
Speed: 1.1ms preprocess, 268.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMPuGff9jzo6yIdvAWK24w_180.JPG: 480x640 (no detections), 268.5ms
Speed: 1.1ms preprocess, 268.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMPuGff9jzo6yIdvAWK24w_270.JPG: 480x640 (no detections), 266.2ms
Speed: 1.2ms preprocess, 266.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMV3X_IjcFw6WayrZCYn-Q_0.JPG: 480x640 (no detections), 267.7ms
Speed: 1.1ms preprocess, 267.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMV3X_IjcFw6WayrZCYn-Q_90.JPG: 480x640 1 Waste, 269.3ms
Speed: 1.1ms preprocess, 269.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMV3X_IjcFw6WayrZCYn-Q_180.JPG: 480x640 (no detections), 272.0ms
Speed: 1.0ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMV3X_IjcFw6WayrZCYn-Q_270.JPG: 480x640 (no detections), 276.9ms
Speed: 1.1ms preprocess, 276.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMW1807yBjfpQRRkuWV1yw_0.JPG: 480x640 (no detections), 268.0ms
Speed: 1.1ms preprocess, 268.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMW1807yBjfpQRRkuWV1yw_90.JPG: 480x640 (no detections), 270.1ms
Speed: 1.2ms preprocess, 270.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMW1807yBjfpQRRkuWV1yw_180.JPG: 480x640 (no detections), 267.6ms
Speed: 1.0ms preprocess, 267.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMW1807yBjfpQRRkuWV1yw_270.JPG: 480x640 (no detections), 268.1ms
Speed: 1.2ms preprocess, 268.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMX7YOGWnvSTY7cND77S_Q_0.JPG: 480x640 (no detections), 266.6ms
Speed: 1.1ms preprocess, 266.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMX7YOGWnvSTY7cND77S_Q_90.JPG: 480x640 (no detections), 274.2ms
Speed: 1.2ms preprocess, 274.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMX7YOGWnvSTY7cND77S_Q_180.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMX7YOGWnvSTY7cND77S_Q_270.JPG: 480x640 (no detections), 266.6ms
Speed: 1.1ms preprocess, 266.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMZDY-dN0eTCfJ-3dIkCaw_0.JPG: 480x640 (no detections), 267.5ms
Speed: 1.0ms preprocess, 267.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMZDY-dN0eTCfJ-3dIkCaw_90.JPG: 480x640 (no detections), 268.1ms
Speed: 1.2ms preprocess, 268.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMZDY-dN0eTCfJ-3dIkCaw_180.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMZDY-dN0eTCfJ-3dIkCaw_270.JPG: 480x640 (no detections), 270.5ms
Speed: 1.0ms preprocess, 270.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMaBDGsNtVNLXeObCpl0fQ_0.JPG: 480x640 (no detections), 268.7ms
Speed: 1.0ms preprocess, 268.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMaBDGsNtVNLXeObCpl0fQ_90.JPG: 480x640 (no detections), 266.7ms
Speed: 1.0ms preprocess, 266.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMaBDGsNtVNLXeObCpl0fQ_180.JPG: 480x640 (no detections), 265.6ms
Speed: 1.0ms preprocess, 265.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMaBDGsNtVNLXeObCpl0fQ_270.JPG: 480x640 (no detections), 270.6ms
Speed: 1.2ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMpFMmTwB_mf0QF0XsExhg_0.JPG: 480x640 (no detections), 275.5ms
Speed: 1.2ms preprocess, 275.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMpFMmTwB_mf0QF0XsExhg_90.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMpFMmTwB_mf0QF0XsExhg_180.JPG: 480x640 (no detections), 268.6ms
Speed: 1.2ms preprocess, 268.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMpFMmTwB_mf0QF0XsExhg_270.JPG: 480x640 (no detections), 268.7ms
Speed: 1.1ms preprocess, 268.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMpS3Mh3JOlXc9Kcnip1GA_0.JPG: 480x640 (no detections), 268.7ms
Speed: 1.1ms preprocess, 268.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMpS3Mh3JOlXc9Kcnip1GA_90.JPG: 480x640 (no detections), 265.8ms
Speed: 1.1ms preprocess, 265.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMpS3Mh3JOlXc9Kcnip1GA_180.JPG: 480x640 (no detections), 269.8ms
Speed: 1.0ms preprocess, 269.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMpS3Mh3JOlXc9Kcnip1GA_270.JPG: 480x640 (no detections), 269.2ms
Speed: 1.2ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMraCyzLySn3FcBtDKgNZA_0.JPG: 480x640 (no detections), 265.0ms
Speed: 1.1ms preprocess, 265.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMraCyzLySn3FcBtDKgNZA_90.JPG: 480x640 (no detections), 268.6ms
Speed: 1.1ms preprocess, 268.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMraCyzLySn3FcBtDKgNZA_180.JPG: 480x640 (no detections), 269.4ms
Speed: 1.1ms preprocess, 269.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMraCyzLySn3FcBtDKgNZA_270.JPG: 480x640 (no detections), 279.0ms
Speed: 1.0ms preprocess, 279.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMsKSFExOjWo0TvPI8I_mA_0.JPG: 480x640 (no detections), 270.7ms

Speed: 1.0ms preprocess, 270.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMsKSFExOjWo0TvPI8I_mA_90.JPG: 480x640 (no detections), 299.7ms
Speed: 1.0ms preprocess, 299.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMsKSFExOjWo0TvPI8I_mA_180.JPG: 480x640 (no detections), 272.6ms
Speed: 1.4ms preprocess, 272.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMsKSFExOjWo0TvPI8I_mA_270.JPG: 480x640 (no detections), 270.4ms
Speed: 1.0ms preprocess, 270.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMty3-T5UkGYijislcUeZA_0.JPG: 480x640 (no detections), 263.4ms
Speed: 1.2ms preprocess, 263.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMty3-T5UkGYijislcUeZA_90.JPG: 480x640 (no detections), 269.8ms
Speed: 1.2ms preprocess, 269.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMty3-T5UkGYijislcUeZA_180.JPG: 480x640 (no detections), 265.5ms
Speed: 1.1ms preprocess, 265.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMty3-T5UkGYijislcUeZA_270.JPG: 480x640 (no detections), 268.4ms
Speed: 1.0ms preprocess, 268.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMxRoDsbCsTpYBG3-7o8Hg_0.JPG: 480x640 (no detections), 269.4ms
Speed: 1.0ms preprocess, 269.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMxRoDsbCsTpYBG3-7o8Hg_90.JPG: 480x640 (no detections), 266.2ms
Speed: 1.1ms preprocess, 266.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMxRoDsbCsTpYBG3-7o8Hg_180.JPG: 480x640 (no detections), 265.8ms
Speed: 1.1ms preprocess, 265.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wMxRoDsbCsTpYBG3-7o8Hg_270.JPG: 480x640 (no detections), 267.7ms
Speed: 1.0ms preprocess, 267.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wN-W-hOWcSE5LIOy2FhnKQ_0.JPG: 480x640 (no detections), 267.9ms
Speed: 1.0ms preprocess, 267.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wN-W-hOWcSE5LIOy2FhnKQ_90.JPG: 480x640 (no detections), 265.9ms
Speed: 1.1ms preprocess, 265.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wN-W-hOWcSE5LIOy2FhnKQ_180.JPG: 480x640 (no detections), 266.5ms
Speed: 1.0ms preprocess, 266.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wN-W-hOWcSE5LIOy2FhnKQ_270.JPG: 480x640 (no detections), 267.0ms
Speed: 1.0ms preprocess, 267.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wN68Cb29v5ZocvkNuRjNZg_0.JPG: 480x640 (no detections), 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wN68Cb29v5ZocvkNuRjNZg_90.JPG: 480x640 (no detections), 272.0ms
Speed: 1.0ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wN68Cb29v5ZocvkNuRjNZg_180.JPG: 480x640 (no detections), 265.6ms
Speed: 1.2ms preprocess, 265.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wN68Cb29v5ZocvkNuRjNZg_270.JPG: 480x640 (no detections), 267.4ms
Speed: 1.1ms preprocess, 267.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wN8HYfvlz6UWNm3_21OrWQ_0.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wN8HYfvlz6UWNm3_21OrWQ_90.JPG: 480x640 (no detections), 272.1ms
Speed: 1.2ms preprocess, 272.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wN8HYfvlz6UWNm3_21OrWQ_180.JPG: 480x640 (no detections), 272.5ms
Speed: 1.1ms preprocess, 272.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wN8HYfvlz6UWNm3_21OrWQ_270.JPG: 480x640 1 Waste, 269.2ms
Speed: 1.0ms preprocess, 269.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wNCPpkTlLlufhm0sy3hv_w_0.JPG: 480x640 (no detections), 268.5ms
Speed: 1.1ms preprocess, 268.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wNCPpkTlLlufhm0sy3hv_w_90.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wNCPpkTlLlufhm0sy3hv_w_180.JPG: 480x640 (no detections), 269.5ms
Speed: 1.0ms preprocess, 269.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wNCPpkTlLlufhm0sy3hv_w_270.JPG: 480x640 (no detections), 266.3ms
Speed: 1.0ms preprocess, 266.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wNCxLytzr1A1-y-6kPxIww_0.JPG: 480x640 (no detections), 267.9ms
Speed: 1.0ms preprocess, 267.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wNCxLytzr1A1-y-6kPxIww_90.JPG: 480x640 (no detections), 261.9ms
Speed: 1.1ms preprocess, 261.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wNCxLytzr1A1-y-6kPxIww_180.JPG: 480x640 (no detections), 275.8ms
Speed: 1.1ms preprocess, 275.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wNCxLytzr1A1-y-6kPxIww_270.JPG: 480x640 (no detections), 266.8ms
Speed: 1.0ms preprocess, 266.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wNP-PusefWT8H-qiwNOMGw_0.JPG: 480x640 (no detections), 274.3ms
Speed: 1.0ms preprocess, 274.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wNP-PusefWT8H-qiwNOMGw_90.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wNP-PusefWT8H-qiwNOMGw_180.JPG: 480x640 (no detections), 268.1ms
Speed: 1.1ms preprocess, 268.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wNP-PusefWT8H-qiwNOMGw_270.JPG: 480x640 (no detections), 268.7ms
Speed: 1.1ms preprocess, 268.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wNZmI7vzyEyuE5_ytWTP7w_0.JPG: 480x640 (no detections), 266.9ms
Speed: 1.4ms preprocess, 266.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wNZmI7vzyEyuE5_ytWTP7w_90.JPG: 480x640 (no detections), 269.4ms
Speed: 1.1ms preprocess, 269.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wNZmI7vzyEyuE5_ytWTP7w_180.JPG: 480x640 (no detections), 270.2ms
Speed: 1.0ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wNZmI7vzyEyuE5_ytWTP7w_270.JPG: 480x640 (no detections), 267.8ms
Speed: 1.2ms preprocess, 267.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wN_CPaRnY339n_hfpvyREw_0.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wN_CPaRnY339n_hfpvyREw_90.JPG: 480x640 (no detections), 268.1ms
Speed: 1.2ms preprocess, 268.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wN_CPaRnY339n_hfpvyREw_180.JPG: 480x640 (no detections), 269.2ms
Speed: 1.0ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wN_CPaRnY339n_hfpvyREw_270.JPG: 480x640 (no detections), 266.7ms
Speed: 1.0ms preprocess, 266.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wN_fZ29i_Qrf88NeEJa_Ew_0.JPG: 480x640 (no detections), 270.5ms
Speed: 1.3ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wN_fZ29i_Qrf88NeEJa_Ew_90.JPG: 480x640 (no detections), 273.3ms
Speed: 1.0ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wN_fZ29i_Qrf88NeEJa_Ew_180.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wN_fZ29i_Qrf88NeEJa_Ew_270.JPG: 480x640 (no detections), 273.3ms
Speed: 1.4ms preprocess, 273.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wNd6jsgBhVKZaZ371GP4kg_0.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wNd6jsgBhVKZaZ371GP4kg_90.JPG: 480x640 (no detections), 267.7ms
Speed: 1.2ms preprocess, 267.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wNd6jsgBhVKZaZ371GP4kg_180.JPG: 480x640 (no detections), 269.2ms
Speed: 1.1ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wNd6jsgBhVKZaZ371GP4kg_270.JPG: 480x640 (no detections), 268.6ms
Speed: 1.1ms preprocess, 268.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wNfokU9IAfKaT2amc1gNjA_0.JPG: 480x640 (no detections), 269.5ms
Speed: 1.0ms preprocess, 269.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wNfokU9IAfKaT2amc1gNjA_90.JPG: 480x640 (no detections), 266.2ms
Speed: 1.5ms preprocess, 266.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wNfokU9IAfKaT2amc1gNjA_180.JPG: 480x640 (no detections), 263.9ms
Speed: 1.1ms preprocess, 263.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wNfokU9IAfKaT2amc1gNjA_270.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wNiA5nRZiXhrT_Tb4NZn_Q_0.JPG: 480x640 (no detections), 270.5ms
Speed: 1.1ms preprocess, 270.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wNiA5nRZiXhrT_Tb4NZn_Q_90.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wNiA5nRZiXhrT_Tb4NZn_Q_180.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wNiA5nRZiXhrT_Tb4NZn_Q_270.JPG: 480x640 (no detections), 268.8ms
Speed: 1.2ms preprocess, 268.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wNiV8E4If5eH8bJ3AWL1zg_0.JPG: 480x640 (no detections), 272.0ms
Speed: 1.1ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wNiV8E4If5eH8bJ3AWL1zg_90.JPG: 480x640 (no detections), 276.0ms
Speed: 1.2ms preprocess, 276.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wNiV8E4If5eH8bJ3AWL1zg_180.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wNiV8E4If5eH8bJ3AWL1zg_270.JPG: 480x640 (no detections), 281.6ms
Speed: 1.1ms preprocess, 281.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wNiyHGVniuBvAe3XUfRolw_0.JPG: 480x640 (no detections), 269.7ms
Speed: 1.0ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wNiyHGVniuBvAe3XUfRolw_90.JPG: 480x640 1 Waste, 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wNiyHGVniuBvAe3XUfRolw_180.JPG: 480x640 (no detections), 271.5ms
Speed: 1.4ms preprocess, 271.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wNiyHGVniuBvAe3XUfRolw_270.JPG: 480x640 (no detections), 268.7ms

Speed: 1.0ms preprocess, 268.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wNuuC_vPr2qpUjlP8fmHuQ_0.JPG: 480x640 (no detections), 273.2ms
Speed: 1.0ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wNuuC_vPr2qpUjlP8fmHuQ_90.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wNuuC_vPr2qpUjlP8fmHuQ_180.JPG: 480x640 (no detections), 268.2ms
Speed: 1.1ms preprocess, 268.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wNuuC_vPr2qpUjlP8fmHuQ_270.JPG: 480x640 (no detections), 269.6ms
Speed: 1.0ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wO1dQoY3ewW2qydwLuf-rg_0.JPG: 480x640 (no detections), 268.8ms
Speed: 1.1ms preprocess, 268.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wO1dQoY3ewW2qydwLuf-rg_90.JPG: 480x640 (no detections), 269.8ms
Speed: 1.0ms preprocess, 269.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wO1dQoY3ewW2qydwLuf-rg_180.JPG: 480x640 (no detections), 268.3ms
Speed: 1.1ms preprocess, 268.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wO1dQoY3ewW2qydwLuf-rg_270.JPG: 480x640 (no detections), 269.1ms
Speed: 1.1ms preprocess, 269.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wO4JzCwTbK4xQXDD0VfVMw_0.JPG: 480x640 (no detections), 274.4ms
Speed: 1.1ms preprocess, 274.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wO4JzCwTbK4xQXDD0VfVMw_90.JPG: 480x640 (no detections), 268.1ms
Speed: 1.1ms preprocess, 268.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wO4JzCwTbK4xQXDD0VfVMw_180.JPG: 480x640 (no detections), 266.3ms
Speed: 1.1ms preprocess, 266.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wO4JzCwTbK4xQXDD0VfVMw_270.JPG: 480x640 (no detections), 267.9ms
Speed: 1.0ms preprocess, 267.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOB4rXfUOh3-_q6yHBQnCQ_0.JPG: 480x640 (no detections), 267.2ms
Speed: 1.2ms preprocess, 267.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOB4rXfUOh3-_q6yHBQnCQ_90.JPG: 480x640 (no detections), 266.1ms
Speed: 1.0ms preprocess, 266.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOB4rXfUOh3-_q6yHBQnCQ_180.JPG: 480x640 (no detections), 269.0ms
Speed: 1.1ms preprocess, 269.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOB4rXfUOh3-_q6yHBQnCQ_270.JPG: 480x640 (no detections), 270.6ms
Speed: 1.2ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOBED14CfrkHEuSrpq_5-Q_0.JPG: 480x640 (no detections), 265.5ms
Speed: 1.1ms preprocess, 265.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOBED14CfrkHEuSrpq_5-Q_90.JPG: 480x640 (no detections), 268.9ms
Speed: 1.1ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOBED14CfrkHEuSrpq_5-Q_180.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOBED14CfrkHEuSrpq_5-Q_270.JPG: 480x640 (no detections), 268.3ms
Speed: 1.2ms preprocess, 268.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wODPDPcuKYodv5IxpEKZ3w_0.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wODPDPcuKYodv5IxpEKZ3w_90.JPG: 480x640 (no detections), 268.2ms
Speed: 1.0ms preprocess, 268.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wODPDPcuKYodv5IxpEKZ3w_180.JPG: 480x640 (no detections), 272.4ms
Speed: 1.1ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wODPDPcuKYodv5IxpEKZ3w_270.JPG: 480x640 (no detections), 270.9ms
Speed: 1.1ms preprocess, 270.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOOq8VMylYNuiSMl10J0mQ_0.JPG: 480x640 (no detections), 274.8ms
Speed: 1.0ms preprocess, 274.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOOq8VMylYNuiSMl10J0mQ_90.JPG: 480x640 (no detections), 276.6ms
Speed: 1.0ms preprocess, 276.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOOq8VMylYNuiSMl10J0mQ_180.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOOq8VMylYNuiSMl10J0mQ_270.JPG: 480x640 (no detections), 268.7ms
Speed: 1.1ms preprocess, 268.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOOsNfU37RHaAKSaUDKj4A_0.JPG: 480x640 (no detections), 269.1ms
Speed: 1.1ms preprocess, 269.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOOsNfU37RHaAKSaUDKj4A_90.JPG: 480x640 (no detections), 268.6ms
Speed: 1.1ms preprocess, 268.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOOsNfU37RHaAKSaUDKj4A_180.JPG: 480x640 (no detections), 268.8ms
Speed: 1.1ms preprocess, 268.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOOsNfU37RHaAKSaUDKj4A_270.JPG: 480x640 (no detections), 270.2ms
Speed: 1.2ms preprocess, 270.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wORXI_EPjdawabV2hPRu2A_0.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wORXI_EPjdawabV2hPRu2A_90.JPG: 480x640 (no detections), 272.9ms
Speed: 1.0ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wORXI_EPjdawabV2hPRu2A_180.JPG: 480x640 (no detections), 267.5ms
Speed: 1.1ms preprocess, 267.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wORXI_EPjdawabV2hPRu2A_270.JPG: 480x640 (no detections), 269.4ms
Speed: 1.1ms preprocess, 269.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOTGE5VWV_bKqBMqVij6Aw_0.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOTGE5VWV_bKqBMqVij6Aw_90.JPG: 480x640 (no detections), 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOTGE5VWV_bKqBMqVij6Aw_180.JPG: 480x640 (no detections), 269.4ms
Speed: 1.1ms preprocess, 269.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOTGE5VWV_bKqBMqVij6Aw_270.JPG: 480x640 (no detections), 268.0ms
Speed: 1.1ms preprocess, 268.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOUs-PIdRQB78U3DGpJSzw_0.JPG: 480x640 (no detections), 270.4ms
Speed: 1.1ms preprocess, 270.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOUs-PIdRQB78U3DGpJSzw_90.JPG: 480x640 (no detections), 267.2ms
Speed: 1.0ms preprocess, 267.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOUs-PIdRQB78U3DGpJSzw_180.JPG: 480x640 (no detections), 269.2ms
Speed: 1.2ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOUs-PIdRQB78U3DGpJSzw_270.JPG: 480x640 (no detections), 267.0ms
Speed: 1.1ms preprocess, 267.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOWsh7XSOaSa2vOQpLD8DQ_0.JPG: 480x640 (no detections), 269.8ms
Speed: 1.1ms preprocess, 269.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOWsh7XSOaSa2vOQpLD8DQ_90.JPG: 480x640 (no detections), 269.4ms
Speed: 1.1ms preprocess, 269.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOWsh7XSOaSa2vOQpLD8DQ_180.JPG: 480x640 (no detections), 269.5ms
Speed: 1.1ms preprocess, 269.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOWsh7XSOaSa2vOQpLD8DQ_270.JPG: 480x640 (no detections), 272.4ms
Speed: 1.0ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wObEqldComO2RG2s3yRNJQ_0.JPG: 480x640 (no detections), 270.2ms
Speed: 1.0ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wObEqldComO2RG2s3yRNJQ_90.JPG: 480x640 (no detections), 267.6ms
Speed: 1.0ms preprocess, 267.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wObEqldComO2RG2s3yRNJQ_180.JPG: 480x640 (no detections), 268.1ms
Speed: 1.1ms preprocess, 268.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wObEqldComO2RG2s3yRNJQ_270.JPG: 480x640 (no detections), 267.7ms
Speed: 1.0ms preprocess, 267.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOdCl2hm4hoD5I9NTP5EPg_0.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOdCl2hm4hoD5I9NTP5EPg_90.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOdCl2hm4hoD5I9NTP5EPg_180.JPG: 480x640 (no detections), 268.0ms
Speed: 1.1ms preprocess, 268.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOdCl2hm4hoD5I9NTP5EPg_270.JPG: 480x640 (no detections), 275.7ms
Speed: 1.2ms preprocess, 275.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOer4UPA6aYAefzI2GuLWg_0.JPG: 480x640 (no detections), 276.4ms
Speed: 1.1ms preprocess, 276.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOer4UPA6aYAefzI2GuLWg_90.JPG: 480x640 (no detections), 272.2ms
Speed: 1.0ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOer4UPA6aYAefzI2GuLWg_180.JPG: 480x640 (no detections), 266.9ms
Speed: 1.1ms preprocess, 266.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOer4UPA6aYAefzI2GuLWg_270.JPG: 480x640 (no detections), 270.2ms
Speed: 1.0ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOhmOXZAfNAV9CwZVxHrGQ_0.JPG: 480x640 (no detections), 269.6ms
Speed: 1.1ms preprocess, 269.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOhmOXZAfNAV9CwZVxHrGQ_90.JPG: 480x640 (no detections), 269.0ms
Speed: 1.1ms preprocess, 269.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOhmOXZAfNAV9CwZVxHrGQ_180.JPG: 480x640 (no detections), 268.5ms
Speed: 1.0ms preprocess, 268.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOhmOXZAfNAV9CwZVxHrGQ_270.JPG: 480x640 (no detections), 268.0ms
Speed: 1.1ms preprocess, 268.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOkdpeGFwAayZNP7XdOYRw_0.JPG: 480x640 (no detections), 272.4ms
Speed: 1.0ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOkdpeGFwAayZNP7XdOYRw_90.JPG: 480x640 (no detections), 271.3ms
Speed: 1.0ms preprocess, 271.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOkdpeGFwAayZNP7XdOYRw_180.JPG: 480x640 (no detections), 275.4ms

Speed: 1.0ms preprocess, 275.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOkdpeGFwAayZNP7XdOYRw_270.JPG: 480x640 (no detections), 272.2ms
Speed: 1.0ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOpG7rIiQMr4hkkQGKC8Wg_0.JPG: 480x640 (no detections), 266.2ms
Speed: 1.0ms preprocess, 266.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOpG7rIiQMr4hkkQGKC8Wg_90.JPG: 480x640 1 Waste, 268.7ms
Speed: 1.1ms preprocess, 268.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOpG7rIiQMr4hkkQGKC8Wg_180.JPG: 480x640 1 Waste, 268.1ms
Speed: 1.1ms preprocess, 268.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOpG7rIiQMr4hkkQGKC8Wg_270.JPG: 480x640 1 Waste, 270.5ms
Speed: 1.0ms preprocess, 270.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOpUpTpb6jJvmhTCkn-ypg_0.JPG: 480x640 (no detections), 266.3ms
Speed: 1.0ms preprocess, 266.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOpUpTpb6jJvmhTCkn-ypg_90.JPG: 480x640 (no detections), 265.5ms
Speed: 1.1ms preprocess, 265.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOpUpTpb6jJvmhTCkn-ypg_180.JPG: 480x640 (no detections), 269.0ms
Speed: 1.0ms preprocess, 269.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOpUpTpb6jJvmhTCkn-ypg_270.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOqbCLZhFzuNbbXgZBShxQ_0.JPG: 480x640 (no detections), 270.4ms
Speed: 1.1ms preprocess, 270.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOqbCLZhFzuNbbXgZBShxQ_90.JPG: 480x640 (no detections), 263.1ms
Speed: 1.0ms preprocess, 263.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOqbCLZhFzuNbbXgZBShxQ_180.JPG: 480x640 (no detections), 269.1ms
Speed: 1.0ms preprocess, 269.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOqbCLZhFzuNbbXgZBShxQ_270.JPG: 480x640 (no detections), 268.8ms
Speed: 1.1ms preprocess, 268.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOqdVS6sQYqT4-Mb_wZUxA_0.JPG: 480x640 (no detections), 267.3ms
Speed: 1.1ms preprocess, 267.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOqdVS6sQYqT4-Mb_wZUxA_90.JPG: 480x640 (no detections), 272.4ms
Speed: 1.1ms preprocess, 272.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOqdVS6sQYqT4-Mb_wZUxA_180.JPG: 480x640 (no detections), 268.3ms
Speed: 1.1ms preprocess, 268.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOqdVS6sQYqT4-Mb_wZUxA_270.JPG: 480x640 (no detections), 270.5ms
Speed: 1.0ms preprocess, 270.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOurEM04DxDbC-QgTO0B4A_0.JPG: 480x640 (no detections), 266.2ms
Speed: 1.1ms preprocess, 266.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOurEM04DxDbC-QgTO0B4A_90.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOurEM04DxDbC-QgTO0B4A_180.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOurEM04DxDbC-QgTO0B4A_270.JPG: 480x640 (no detections), 281.4ms
Speed: 1.0ms preprocess, 281.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOwNoKjzjdUkMcS-Qx73wA_0.JPG: 480x640 (no detections), 272.2ms
Speed: 1.0ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOwNoKjzjdUkMcS-Qx73wA_90.JPG: 480x640 1 Waste, 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOwNoKjzjdUkMcS-Qx73wA_180.JPG: 480x640 1 Waste, 269.4ms
Speed: 1.0ms preprocess, 269.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wOwNoKjzjdUkMcS-Qx73wA_270.JPG: 480x640 (no detections), 270.1ms
Speed: 1.0ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wP1J0WOq1PuX2L74nY9Fqw_0.JPG: 480x640 (no detections), 283.7ms
Speed: 1.3ms preprocess, 283.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wP1J0WOq1PuX2L74nY9Fqw_90.JPG: 480x640 (no detections), 276.4ms
Speed: 1.2ms preprocess, 276.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wP1J0WOq1PuX2L74nY9Fqw_180.JPG: 480x640 (no detections), 267.9ms
Speed: 1.6ms preprocess, 267.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wP1J0WOq1PuX2L74nY9Fqw_270.JPG: 480x640 (no detections), 289.9ms
Speed: 1.4ms preprocess, 289.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wP1cVcdl0K8Et2e2IU3XUA_0.JPG: 480x640 (no detections), 288.5ms
Speed: 1.7ms preprocess, 288.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wP1cVcdl0K8Et2e2IU3XUA_90.JPG: 480x640 (no detections), 289.4ms
Speed: 1.5ms preprocess, 289.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wP1cVcdl0K8Et2e2IU3XUA_180.JPG: 480x640 (no detections), 303.4ms
Speed: 1.7ms preprocess, 303.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wP1cVcdl0K8Et2e2IU3XUA_270.JPG: 480x640 (no detections), 323.0ms
Speed: 1.2ms preprocess, 323.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wP2vb1sBlExxeWDYQeLp7w_0.JPG: 480x640 (no detections), 307.7ms
Speed: 1.6ms preprocess, 307.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wP2vb1sBlExxeWDYQeLp7w_90.JPG: 480x640 (no detections), 300.7ms
Speed: 1.8ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wP2vb1sBlExxeWDYQeLp7w_180.JPG: 480x640 (no detections), 289.2ms
Speed: 1.1ms preprocess, 289.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wP2vb1sBlExxeWDYQeLp7w_270.JPG: 480x640 (no detections), 276.8ms
Speed: 1.2ms preprocess, 276.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wP76-PPBZj1KqrXpVPze1A_0.JPG: 480x640 (no detections), 299.0ms
Speed: 1.1ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wP76-PPBZj1KqrXpVPze1A_90.JPG: 480x640 (no detections), 277.0ms
Speed: 1.2ms preprocess, 277.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wP76-PPBZj1KqrXpVPze1A_180.JPG: 480x640 (no detections), 273.4ms
Speed: 1.2ms preprocess, 273.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wP76-PPBZj1KqrXpVPze1A_270.JPG: 480x640 (no detections), 272.0ms
Speed: 1.2ms preprocess, 272.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wP8HosOaSbzb_5AdO1HRBw_0.JPG: 480x640 (no detections), 270.5ms
Speed: 1.2ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wP8HosOaSbzb_5AdO1HRBw_90.JPG: 480x640 (no detections), 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wP8HosOaSbzb_5AdO1HRBw_180.JPG: 480x640 (no detections), 272.3ms
Speed: 1.0ms preprocess, 272.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wP8HosOaSbzb_5AdO1HRBw_270.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wP93XzuX9W0xu7kWFWes_g_0.JPG: 480x640 (no detections), 269.1ms
Speed: 1.1ms preprocess, 269.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wP93XzuX9W0xu7kWFWes_g_90.JPG: 480x640 (no detections), 266.9ms
Speed: 1.1ms preprocess, 266.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wP93XzuX9W0xu7kWFWes_g_180.JPG: 480x640 (no detections), 264.4ms
Speed: 1.1ms preprocess, 264.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wP93XzuX9W0xu7kWFWes_g_270.JPG: 480x640 (no detections), 266.8ms
Speed: 1.1ms preprocess, 266.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPBRlpmydCVa1nFFjJuwLA_0.JPG: 480x640 (no detections), 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPBRlpmydCVa1nFFjJuwLA_90.JPG: 480x640 (no detections), 270.5ms
Speed: 1.1ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPBRlpmydCVa1nFFjJuwLA_180.JPG: 480x640 (no detections), 268.7ms
Speed: 1.1ms preprocess, 268.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPBRlpmydCVa1nFFjJuwLA_270.JPG: 480x640 (no detections), 274.9ms
Speed: 1.2ms preprocess, 274.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPD43XPz522ik79kBKkn_w_0.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPD43XPz522ik79kBKkn_w_90.JPG: 480x640 (no detections), 269.8ms
Speed: 1.1ms preprocess, 269.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPD43XPz522ik79kBKkn_w_180.JPG: 480x640 (no detections), 269.2ms
Speed: 1.0ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPD43XPz522ik79kBKkn_w_270.JPG: 480x640 (no detections), 269.4ms
Speed: 1.0ms preprocess, 269.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPHIBacJUMmxvgRsaO5KiQ_0.JPG: 480x640 (no detections), 292.5ms
Speed: 1.1ms preprocess, 292.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPHIBacJUMmxvgRsaO5KiQ_90.JPG: 480x640 1 Waste, 276.2ms
Speed: 1.2ms preprocess, 276.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPHIBacJUMmxvgRsaO5KiQ_180.JPG: 480x640 (no detections), 270.4ms
Speed: 1.0ms preprocess, 270.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPHIBacJUMmxvgRsaO5KiQ_270.JPG: 480x640 (no detections), 264.2ms
Speed: 1.1ms preprocess, 264.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPKLTCw5bXju9V1Zb3prcA_0.JPG: 480x640 (no detections), 266.0ms
Speed: 1.1ms preprocess, 266.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPKLTCw5bXju9V1Zb3prcA_90.JPG: 480x640 (no detections), 271.4ms
Speed: 1.0ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPKLTCw5bXju9V1Zb3prcA_180.JPG: 480x640 (no detections), 269.8ms
Speed: 1.0ms preprocess, 269.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPKLTCw5bXju9V1Zb3prcA_270.JPG: 480x640 (no detections), 271.9ms
Speed: 1.0ms preprocess, 271.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPKMLBQoNa1u6fgFZNR3Qw_0.JPG: 480x640 (no detections), 269.5ms
Speed: 1.1ms preprocess, 269.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPKMLBQoNa1u6fgFZNR3Qw_90.JPG: 480x640 (no detections), 269.8ms

Speed: 1.1ms preprocess, 269.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPKMLBQoNa1u6fgFZNR3Qw_180.JPG: 480x640 (no detections), 267.7ms
Speed: 1.1ms preprocess, 267.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPKMLBQoNa1u6fgFZNR3Qw_270.JPG: 480x640 (no detections), 272.1ms
Speed: 1.2ms preprocess, 272.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPMnttsdRqT3OFW4oFzzuQ_0.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPMnttsdRqT3OFW4oFzzuQ_90.JPG: 480x640 (no detections), 272.2ms
Speed: 1.0ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPMnttsdRqT3OFW4oFzzuQ_180.JPG: 480x640 (no detections), 285.6ms
Speed: 1.0ms preprocess, 285.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPMnttsdRqT3OFW4oFzzuQ_270.JPG: 480x640 (no detections), 272.3ms
Speed: 1.1ms preprocess, 272.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPN623jYQwb6dJSKzkeWXA_0.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPN623jYQwb6dJSKzkeWXA_90.JPG: 480x640 (no detections), 304.1ms
Speed: 1.1ms preprocess, 304.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPN623jYQwb6dJSKzkeWXA_180.JPG: 480x640 (no detections), 308.8ms
Speed: 1.2ms preprocess, 308.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPN623jYQwb6dJSKzkeWXA_270.JPG: 480x640 (no detections), 285.7ms
Speed: 1.1ms preprocess, 285.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPN8qpN4Rc-OtpTx-trH5w_0.JPG: 480x640 (no detections), 304.2ms
Speed: 1.1ms preprocess, 304.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPN8qpN4Rc-OtpTx-trH5w_90.JPG: 480x640 (no detections), 281.9ms
Speed: 1.1ms preprocess, 281.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPN8qpN4Rc-OtpTx-trH5w_180.JPG: 480x640 (no detections), 270.9ms
Speed: 1.3ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPN8qpN4Rc-OtpTx-trH5w_270.JPG: 480x640 (no detections), 274.7ms
Speed: 1.2ms preprocess, 274.7ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPO6KU3k6IcXfni4t0eAUw_0.JPG: 480x640 (no detections), 271.8ms
Speed: 1.2ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPO6KU3k6IcXfni4t0eAUw_90.JPG: 480x640 (no detections), 270.3ms
Speed: 1.1ms preprocess, 270.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPO6KU3k6IcXfni4t0eAUw_180.JPG: 480x640 (no detections), 270.9ms
Speed: 1.0ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPO6KU3k6IcXfni4t0eAUw_270.JPG: 480x640 (no detections), 299.8ms
Speed: 1.1ms preprocess, 299.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPSKnP1JSZmBbvO4aS1zow_0.JPG: 480x640 (no detections), 274.5ms
Speed: 1.1ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPSKnP1JSZmBbvO4aS1zow_90.JPG: 480x640 (no detections), 269.1ms
Speed: 1.1ms preprocess, 269.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPSKnP1JSZmBbvO4aS1zow_180.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPSKnP1JSZmBbvO4aS1zow_270.JPG: 480x640 (no detections), 273.2ms
Speed: 1.0ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPT6ob2lkTo24gtXrVOVVw_0.JPG: 480x640 (no detections), 272.5ms
Speed: 1.1ms preprocess, 272.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPT6ob2lkTo24gtXrVOVVw_90.JPG: 480x640 (no detections), 268.4ms
Speed: 1.4ms preprocess, 268.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPT6ob2lkTo24gtXrVOVVw_180.JPG: 480x640 (no detections), 275.7ms
Speed: 1.1ms preprocess, 275.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPT6ob2lkTo24gtXrVOVVw_270.JPG: 480x640 (no detections), 268.9ms
Speed: 1.1ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPU1a8bwSwJC9eO-mHtZgQ_0.JPG: 480x640 (no detections), 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPU1a8bwSwJC9eO-mHtZgQ_90.JPG: 480x640 (no detections), 267.7ms
Speed: 1.1ms preprocess, 267.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPU1a8bwSwJC9eO-mHtZgQ_180.JPG: 480x640 (no detections), 272.1ms
Speed: 1.0ms preprocess, 272.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPU1a8bwSwJC9eO-mHtZgQ_270.JPG: 480x640 (no detections), 267.1ms
Speed: 1.1ms preprocess, 267.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPZ2wkNXHh482uWt6Vt-ag_0.JPG: 480x640 (no detections), 268.8ms
Speed: 1.1ms preprocess, 268.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPZ2wkNXHh482uWt6Vt-ag_90.JPG: 480x640 (no detections), 270.5ms
Speed: 1.1ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPZ2wkNXHh482uWt6Vt-ag_180.JPG: 480x640 (no detections), 274.9ms
Speed: 1.1ms preprocess, 274.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPZ2wkNXHh482uWt6Vt-ag_270.JPG: 480x640 (no detections), 280.8ms
Speed: 1.1ms preprocess, 280.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wP_LFUxN9x4rixxuE5pAdg_0.JPG: 480x640 (no detections), 270.5ms
Speed: 1.1ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wP_LFUxN9x4rixxuE5pAdg_90.JPG: 480x640 (no detections), 273.4ms
Speed: 1.1ms preprocess, 273.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wP_LFUxN9x4rixxuE5pAdg_180.JPG: 480x640 (no detections), 268.0ms
Speed: 1.1ms preprocess, 268.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wP_LFUxN9x4rixxuE5pAdg_270.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPd-b5ba6IR19TKa97E43A_0.JPG: 480x640 (no detections), 268.7ms
Speed: 1.0ms preprocess, 268.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPd-b5ba6IR19TKa97E43A_90.JPG: 480x640 (no detections), 288.9ms
Speed: 1.1ms preprocess, 288.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPd-b5ba6IR19TKa97E43A_180.JPG: 480x640 (no detections), 283.6ms
Speed: 1.1ms preprocess, 283.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPd-b5ba6IR19TKa97E43A_270.JPG: 480x640 (no detections), 272.1ms
Speed: 1.0ms preprocess, 272.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPdSKKg2_BqxSJnRj8jKaw_0.JPG: 480x640 (no detections), 271.8ms
Speed: 1.0ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPdSKKg2_BqxSJnRj8jKaw_90.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPdSKKg2_BqxSJnRj8jKaw_180.JPG: 480x640 (no detections), 272.3ms
Speed: 1.1ms preprocess, 272.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPdSKKg2_BqxSJnRj8jKaw_270.JPG: 480x640 (no detections), 269.5ms
Speed: 1.1ms preprocess, 269.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPdqOaSi-XHp0gFCoCb2Zw_0.JPG: 480x640 (no detections), 291.4ms
Speed: 1.1ms preprocess, 291.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPdqOaSi-XHp0gFCoCb2Zw_90.JPG: 480x640 (no detections), 276.3ms
Speed: 1.1ms preprocess, 276.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPdqOaSi-XHp0gFCoCb2Zw_180.JPG: 480x640 (no detections), 270.9ms
Speed: 1.1ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPdqOaSi-XHp0gFCoCb2Zw_270.JPG: 480x640 (no detections), 267.9ms
Speed: 1.1ms preprocess, 267.9ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPfeprMWiEGGNtlL5xYzpw_0.JPG: 480x640 (no detections), 271.0ms
Speed: 1.0ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPfeprMWiEGGNtlL5xYzpw_90.JPG: 480x640 (no detections), 270.4ms
Speed: 1.1ms preprocess, 270.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPfeprMWiEGGNtlL5xYzpw_180.JPG: 480x640 (no detections), 269.9ms
Speed: 1.0ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPfeprMWiEGGNtlL5xYzpw_270.JPG: 480x640 (no detections), 272.4ms
Speed: 1.1ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPmQ5CEehAH0mTH089UTiw_0.JPG: 480x640 (no detections), 275.0ms
Speed: 1.0ms preprocess, 275.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPmQ5CEehAH0mTH089UTiw_90.JPG: 480x640 (no detections), 274.8ms
Speed: 1.1ms preprocess, 274.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPmQ5CEehAH0mTH089UTiw_180.JPG: 480x640 (no detections), 279.0ms
Speed: 1.1ms preprocess, 279.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPmQ5CEehAH0mTH089UTiw_270.JPG: 480x640 (no detections), 269.1ms
Speed: 1.1ms preprocess, 269.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPnj5OSVtceTwnCgvVQWxA_0.JPG: 480x640 (no detections), 272.0ms
Speed: 1.1ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPnj5OSVtceTwnCgvVQWxA_90.JPG: 480x640 (no detections), 274.8ms
Speed: 1.1ms preprocess, 274.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPnj5OSVtceTwnCgvVQWxA_180.JPG: 480x640 1 Waste, 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPnj5OSVtceTwnCgvVQWxA_270.JPG: 480x640 (no detections), 274.7ms
Speed: 1.1ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPqn2vc-AgqpiGWomDzcJg_0.JPG: 480x640 (no detections), 273.2ms
Speed: 1.0ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPqn2vc-AgqpiGWomDzcJg_90.JPG: 480x640 (no detections), 269.6ms
Speed: 1.0ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPqn2vc-AgqpiGWomDzcJg_180.JPG: 480x640 (no detections), 269.2ms
Speed: 1.2ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPqn2vc-AgqpiGWomDzcJg_270.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPtiEWXQvBKjM3CNT4oT9Q_0.JPG: 480x640 (no detections), 275.9ms

Speed: 1.1ms preprocess, 275.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPtiEWXQvBKjM3CNT4oT9Q_90.JPG: 480x640 (no detections), 290.4ms
Speed: 1.0ms preprocess, 290.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPtiEWXQvBKjM3CNT4oT9Q_180.JPG: 480x640 (no detections), 275.6ms
Speed: 1.2ms preprocess, 275.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPtiEWXQvBKjM3CNT4oT9Q_270.JPG: 480x640 (no detections), 277.7ms
Speed: 1.0ms preprocess, 277.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPwuek1iFoColHdxYraYLA_0.JPG: 480x640 (no detections), 277.9ms
Speed: 1.8ms preprocess, 277.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPwuek1iFoColHdxYraYLA_90.JPG: 480x640 (no detections), 272.5ms
Speed: 1.0ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPwuek1iFoColHdxYraYLA_180.JPG: 480x640 (no detections), 289.0ms
Speed: 1.0ms preprocess, 289.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPwuek1iFoColHdxYraYLA_270.JPG: 480x640 (no detections), 274.9ms
Speed: 1.2ms preprocess, 274.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPxCFEC0x2qGhdQMWN0a3A_0.JPG: 480x640 (no detections), 276.7ms
Speed: 1.0ms preprocess, 276.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPxCFEC0x2qGhdQMWN0a3A_90.JPG: 480x640 (no detections), 274.6ms
Speed: 1.0ms preprocess, 274.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPxCFEC0x2qGhdQMWN0a3A_180.JPG: 480x640 (no detections), 286.1ms
Speed: 1.2ms preprocess, 286.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wPxCFEC0x2qGhdQMWN0a3A_270.JPG: 480x640 (no detections), 274.9ms
Speed: 1.2ms preprocess, 274.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQ-IpJ-MOh3r3HPyPHR7_Q_0.JPG: 480x640 (no detections), 268.4ms
Speed: 1.0ms preprocess, 268.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQ-IpJ-MOh3r3HPyPHR7_Q_90.JPG: 480x640 (no detections), 277.0ms
Speed: 1.3ms preprocess, 277.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQ-IpJ-MOh3r3HPyPHR7_Q_180.JPG: 480x640 (no detections), 274.9ms
Speed: 1.1ms preprocess, 274.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQ-IpJ-MOh3r3HPyPHR7_Q_270.JPG: 480x640 (no detections), 274.8ms
Speed: 1.1ms preprocess, 274.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQ0q74RejMr0dFdpBBzbDA_0.JPG: 480x640 (no detections), 274.4ms
Speed: 1.2ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQ0q74RejMr0dFdpBBzbDA_90.JPG: 480x640 (no detections), 268.5ms
Speed: 1.1ms preprocess, 268.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQ0q74RejMr0dFdpBBzbDA_180.JPG: 480x640 (no detections), 272.8ms
Speed: 1.0ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQ0q74RejMr0dFdpBBzbDA_270.JPG: 480x640 (no detections), 292.5ms
Speed: 1.1ms preprocess, 292.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQ2pbZBTK66-YanHdy9coA_0.JPG: 480x640 1 Waste, 279.0ms
Speed: 1.1ms preprocess, 279.0ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQ2pbZBTK66-YanHdy9coA_90.JPG: 480x640 (no detections), 274.7ms
Speed: 1.2ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQ2pbZBTK66-YanHdy9coA_180.JPG: 480x640 1 Waste, 268.4ms
Speed: 1.1ms preprocess, 268.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQ2pbZBTK66-YanHdy9coA_270.JPG: 480x640 (no detections), 275.4ms
Speed: 1.1ms preprocess, 275.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQ31q6M1RyMuitSoB7pzPA_0.JPG: 480x640 (no detections), 277.1ms
Speed: 1.2ms preprocess, 277.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQ31q6M1RyMuitSoB7pzPA_90.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQ31q6M1RyMuitSoB7pzPA_180.JPG: 480x640 (no detections), 276.4ms
Speed: 1.0ms preprocess, 276.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQ31q6M1RyMuitSoB7pzPA_270.JPG: 480x640 (no detections), 273.2ms
Speed: 1.1ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQ4hD-8ahzE5gSMf7x_Ffw_0.JPG: 480x640 (no detections), 268.7ms
Speed: 1.1ms preprocess, 268.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQ4hD-8ahzE5gSMf7x_Ffw_90.JPG: 480x640 (no detections), 272.1ms
Speed: 1.1ms preprocess, 272.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQ4hD-8ahzE5gSMf7x_Ffw_180.JPG: 480x640 (no detections), 262.3ms
Speed: 1.1ms preprocess, 262.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQ4hD-8ahzE5gSMf7x_Ffw_270.JPG: 480x640 (no detections), 269.4ms
Speed: 1.1ms preprocess, 269.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQ4rlQFGz6lXs3JqGSyemw_0.JPG: 480x640 1 Waste, 275.5ms
Speed: 1.2ms preprocess, 275.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQ4rlQFGz6lXs3JqGSyemw_90.JPG: 480x640 (no detections), 269.6ms
Speed: 1.1ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQ4rlQFGz6lXs3JqGSyemw_180.JPG: 480x640 (no detections), 268.1ms
Speed: 1.1ms preprocess, 268.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQ4rlQFGz6lXs3JqGSyemw_270.JPG: 480x640 (no detections), 270.8ms
Speed: 1.0ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQ6eYJ9d-aOeM5SUwqJkkw_0.JPG: 480x640 (no detections), 270.3ms
Speed: 1.0ms preprocess, 270.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQ6eYJ9d-aOeM5SUwqJkkw_90.JPG: 480x640 (no detections), 270.2ms
Speed: 1.2ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQ6eYJ9d-aOeM5SUwqJkkw_180.JPG: 480x640 (no detections), 275.4ms
Speed: 1.1ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQ6eYJ9d-aOeM5SUwqJkkw_270.JPG: 480x640 (no detections), 279.6ms
Speed: 1.0ms preprocess, 279.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQ8pgeuL_9zU5t0klxq5oQ_0.JPG: 480x640 (no detections), 277.3ms
Speed: 1.0ms preprocess, 277.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQ8pgeuL_9zU5t0klxq5oQ_90.JPG: 480x640 (no detections), 274.0ms
Speed: 1.1ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQ8pgeuL_9zU5t0klxq5oQ_180.JPG: 480x640 (no detections), 276.2ms
Speed: 1.1ms preprocess, 276.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQ8pgeuL_9zU5t0klxq5oQ_270.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQ8zwd7nWuKomZyOJKVCDA_0.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQ8zwd7nWuKomZyOJKVCDA_90.JPG: 480x640 (no detections), 274.9ms
Speed: 1.1ms preprocess, 274.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQ8zwd7nWuKomZyOJKVCDA_180.JPG: 480x640 (no detections), 280.0ms
Speed: 1.6ms preprocess, 280.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQ8zwd7nWuKomZyOJKVCDA_270.JPG: 480x640 (no detections), 270.9ms
Speed: 1.1ms preprocess, 270.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQA4CjN7QGDE6WRsDpUteA_0.JPG: 480x640 (no detections), 279.3ms
Speed: 1.2ms preprocess, 279.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQA4CjN7QGDE6WRsDpUteA_90.JPG: 480x640 (no detections), 269.5ms
Speed: 1.1ms preprocess, 269.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQA4CjN7QGDE6WRsDpUteA_180.JPG: 480x640 (no detections), 273.0ms
Speed: 1.0ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQA4CjN7QGDE6WRsDpUteA_270.JPG: 480x640 (no detections), 270.1ms
Speed: 1.0ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQDY9HnEVp7_AFLYfFWEqw_0.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQDY9HnEVp7_AFLYfFWEqw_90.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQDY9HnEVp7_AFLYfFWEqw_180.JPG: 480x640 (no detections), 298.3ms
Speed: 1.0ms preprocess, 298.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQDY9HnEVp7_AFLYfFWEqw_270.JPG: 480x640 (no detections), 333.2ms
Speed: 1.2ms preprocess, 333.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQEr_XSfBU5eigR_q4dIqg_0.JPG: 480x640 (no detections), 309.0ms
Speed: 2.2ms preprocess, 309.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQEr_XSfBU5eigR_q4dIqg_90.JPG: 480x640 (no detections), 282.9ms
Speed: 1.0ms preprocess, 282.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQEr_XSfBU5eigR_q4dIqg_180.JPG: 480x640 (no detections), 318.7ms
Speed: 1.1ms preprocess, 318.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQEr_XSfBU5eigR_q4dIqg_270.JPG: 480x640 (no detections), 408.2ms
Speed: 1.1ms preprocess, 408.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQJkbNgpmrp24ftArkpuAQ_0.JPG: 480x640 (no detections), 324.6ms
Speed: 2.1ms preprocess, 324.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQJkbNgpmrp24ftArkpuAQ_90.JPG: 480x640 (no detections), 283.8ms
Speed: 1.2ms preprocess, 283.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQJkbNgpmrp24ftArkpuAQ_180.JPG: 480x640 (no detections), 282.6ms
Speed: 1.2ms preprocess, 282.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQJkbNgpmrp24ftArkpuAQ_270.JPG: 480x640 (no detections), 289.4ms
Speed: 1.1ms preprocess, 289.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQRSoPAeHyQglT5Lqb5SBg_0.JPG: 480x640 (no detections), 282.0ms
Speed: 1.2ms preprocess, 282.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQRSoPAeHyQglT5Lqb5SBg_90.JPG: 480x640 (no detections), 285.0ms
Speed: 1.2ms preprocess, 285.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQRSoPAeHyQglT5Lqb5SBg_180.JPG: 480x640 (no detections), 281.1ms
Speed: 1.6ms preprocess, 281.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQRSoPAeHyQglT5Lqb5SBg_270.JPG: 480x640 (no detections), 270.8ms

Speed: 1.5ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQWOsHSBTe6IixZkjBQVtg_0.JPG: 480x640 (no detections), 266.3ms
Speed: 1.2ms preprocess, 266.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQWOsHSBTe6IixZkjBQVtg_90.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQWOsHSBTe6IixZkjBQVtg_180.JPG: 480x640 (no detections), 270.9ms
Speed: 1.0ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQWOsHSBTe6IixZkjBQVtg_270.JPG: 480x640 (no detections), 269.6ms
Speed: 1.1ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQZOBrA_CsEokzptPP6wQg_0.JPG: 480x640 (no detections), 271.4ms
Speed: 1.0ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQZOBrA_CsEokzptPP6wQg_90.JPG: 480x640 (no detections), 269.5ms
Speed: 1.2ms preprocess, 269.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQZOBrA_CsEokzptPP6wQg_180.JPG: 480x640 (no detections), 266.8ms
Speed: 1.1ms preprocess, 266.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQZOBrA_CsEokzptPP6wQg_270.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQ_GHWL1ruXCWgR9QdJt8A_0.JPG: 480x640 (no detections), 267.6ms
Speed: 1.1ms preprocess, 267.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQ_GHWL1ruXCWgR9QdJt8A_90.JPG: 480x640 1 Waste, 267.7ms
Speed: 1.2ms preprocess, 267.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQ_GHWL1ruXCWgR9QdJt8A_180.JPG: 480x640 (no detections), 274.2ms
Speed: 1.0ms preprocess, 274.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQ_GHWL1ruXCWgR9QdJt8A_270.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQ_WLfkN8CbCcWuc9siIxg_0.JPG: 480x640 (no detections), 269.5ms
Speed: 1.0ms preprocess, 269.5ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQ_WLfkN8CbCcWuc9siIxg_90.JPG: 480x640 (no detections), 276.0ms
Speed: 1.0ms preprocess, 276.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQ_WLfkN8CbCcWuc9siIxg_180.JPG: 480x640 (no detections), 279.5ms
Speed: 1.1ms preprocess, 279.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQ_WLfkN8CbCcWuc9siIxg_270.JPG: 480x640 (no detections), 293.2ms
Speed: 1.1ms preprocess, 293.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQap-441xuEDycrfUD_hAA_0.JPG: 480x640 (no detections), 278.2ms
Speed: 1.0ms preprocess, 278.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQap-441xuEDycrfUD_hAA_90.JPG: 480x640 (no detections), 277.9ms
Speed: 1.1ms preprocess, 277.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQap-441xuEDycrfUD_hAA_180.JPG: 480x640 (no detections), 274.5ms
Speed: 1.1ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQap-441xuEDycrfUD_hAA_270.JPG: 480x640 (no detections), 279.9ms
Speed: 1.2ms preprocess, 279.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQc38GBoUtBuUujVyLe2Sg_0.JPG: 480x640 (no detections), 313.9ms
Speed: 1.2ms preprocess, 313.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQc38GBoUtBuUujVyLe2Sg_90.JPG: 480x640 (no detections), 271.5ms
Speed: 1.1ms preprocess, 271.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQc38GBoUtBuUujVyLe2Sg_180.JPG: 480x640 (no detections), 269.7ms
Speed: 1.0ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQc38GBoUtBuUujVyLe2Sg_270.JPG: 480x640 (no detections), 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQeV77tRkwfqiYIIQEe85A_0.JPG: 480x640 (no detections), 273.6ms
Speed: 1.3ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQeV77tRkwfqiYIIQEe85A_90.JPG: 480x640 (no detections), 273.0ms
Speed: 1.2ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQeV77tRkwfqiYIIQEe85A_180.JPG: 480x640 (no detections), 272.0ms
Speed: 1.2ms preprocess, 272.0ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQeV77tRkwfqiYIIQEe85A_270.JPG: 480x640 (no detections), 283.9ms
Speed: 1.1ms preprocess, 283.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQhkhsiap9jp0BM3u_5smw_0.JPG: 480x640 (no detections), 283.4ms
Speed: 1.4ms preprocess, 283.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQhkhsiap9jp0BM3u_5smw_90.JPG: 480x640 (no detections), 278.8ms
Speed: 1.2ms preprocess, 278.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQhkhsiap9jp0BM3u_5smw_180.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQhkhsiap9jp0BM3u_5smw_270.JPG: 480x640 (no detections), 287.1ms
Speed: 1.0ms preprocess, 287.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQinOjiB07Hlz5ob4ex7-w_0.JPG: 480x640 (no detections), 271.5ms
Speed: 1.2ms preprocess, 271.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQinOjiB07Hlz5ob4ex7-w_90.JPG: 480x640 (no detections), 275.3ms
Speed: 1.1ms preprocess, 275.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQinOjiB07Hlz5ob4ex7-w_180.JPG: 480x640 (no detections), 283.9ms
Speed: 1.2ms preprocess, 283.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQinOjiB07Hlz5ob4ex7-w_270.JPG: 480x640 (no detections), 277.3ms
Speed: 1.0ms preprocess, 277.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQjX2DESkMahYm1Hi2NhEg_0.JPG: 480x640 (no detections), 275.5ms
Speed: 1.1ms preprocess, 275.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQjX2DESkMahYm1Hi2NhEg_90.JPG: 480x640 (no detections), 275.0ms
Speed: 1.1ms preprocess, 275.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQjX2DESkMahYm1Hi2NhEg_180.JPG: 480x640 (no detections), 281.9ms
Speed: 1.0ms preprocess, 281.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQjX2DESkMahYm1Hi2NhEg_270.JPG: 480x640 (no detections), 278.2ms
Speed: 1.3ms preprocess, 278.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQkG9l-4tStcjQFHhrZiCA_0.JPG: 480x640 (no detections), 275.7ms
Speed: 1.2ms preprocess, 275.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQkG9l-4tStcjQFHhrZiCA_90.JPG: 480x640 (no detections), 272.4ms
Speed: 1.1ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQkG9l-4tStcjQFHhrZiCA_180.JPG: 480x640 1 Waste, 274.0ms
Speed: 1.5ms preprocess, 274.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQkG9l-4tStcjQFHhrZiCA_270.JPG: 480x640 (no detections), 277.7ms
Speed: 1.1ms preprocess, 277.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQpGb1IAO935QfXegRLf7g_0.JPG: 480x640 (no detections), 271.7ms
Speed: 1.2ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQpGb1IAO935QfXegRLf7g_90.JPG: 480x640 (no detections), 266.4ms
Speed: 1.1ms preprocess, 266.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQpGb1IAO935QfXegRLf7g_180.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQpGb1IAO935QfXegRLf7g_270.JPG: 480x640 (no detections), 268.4ms
Speed: 1.2ms preprocess, 268.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQtEl384dGaNxeE7Vq2nBw_0.JPG: 480x640 (no detections), 270.1ms
Speed: 1.0ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQtEl384dGaNxeE7Vq2nBw_90.JPG: 480x640 (no detections), 273.6ms
Speed: 1.1ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQtEl384dGaNxeE7Vq2nBw_180.JPG: 480x640 (no detections), 273.6ms
Speed: 1.1ms preprocess, 273.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQtEl384dGaNxeE7Vq2nBw_270.JPG: 480x640 (no detections), 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQu56KTL14FMHedpKKbdWA_0.JPG: 480x640 (no detections), 272.1ms
Speed: 1.0ms preprocess, 272.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQu56KTL14FMHedpKKbdWA_90.JPG: 480x640 (no detections), 272.5ms
Speed: 1.0ms preprocess, 272.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQu56KTL14FMHedpKKbdWA_180.JPG: 480x640 (no detections), 284.4ms
Speed: 1.1ms preprocess, 284.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQu56KTL14FMHedpKKbdWA_270.JPG: 480x640 (no detections), 283.4ms
Speed: 1.2ms preprocess, 283.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQwKGkNsL3ywpeHjATW25g_0.JPG: 480x640 (no detections), 314.6ms
Speed: 1.4ms preprocess, 314.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQwKGkNsL3ywpeHjATW25g_90.JPG: 480x640 (no detections), 280.9ms
Speed: 1.5ms preprocess, 280.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQwKGkNsL3ywpeHjATW25g_180.JPG: 480x640 (no detections), 284.0ms
Speed: 1.1ms preprocess, 284.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQwKGkNsL3ywpeHjATW25g_270.JPG: 480x640 (no detections), 279.9ms
Speed: 1.1ms preprocess, 279.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQwjmmkWTasY8h_cmzyOfw_0.JPG: 480x640 (no detections), 281.9ms
Speed: 1.3ms preprocess, 281.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQwjmmkWTasY8h_cmzyOfw_90.JPG: 480x640 (no detections), 277.1ms
Speed: 1.1ms preprocess, 277.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQwjmmkWTasY8h_cmzyOfw_180.JPG: 480x640 (no detections), 279.1ms
Speed: 1.0ms preprocess, 279.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQwjmmkWTasY8h_cmzyOfw_270.JPG: 480x640 (no detections), 286.9ms
Speed: 1.1ms preprocess, 286.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQx5o2eaKPHTDlkI6Q8OCQ_0.JPG: 480x640 (no detections), 290.2ms
Speed: 1.1ms preprocess, 290.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQx5o2eaKPHTDlkI6Q8OCQ_90.JPG: 480x640 (no detections), 280.1ms
Speed: 1.1ms preprocess, 280.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQx5o2eaKPHTDlkI6Q8OCQ_180.JPG: 480x640 (no detections), 279.6ms

Speed: 1.0ms preprocess, 279.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQx5o2eaKPHTDlkI6Q8OCQ_270.JPG: 480x640 (no detections), 286.2ms
Speed: 1.2ms preprocess, 286.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQxV5FHiMfOOuUddux_1Yw_0.JPG: 480x640 (no detections), 286.9ms
Speed: 2.1ms preprocess, 286.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQxV5FHiMfOOuUddux_1Yw_90.JPG: 480x640 (no detections), 271.6ms
Speed: 1.2ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQxV5FHiMfOOuUddux_1Yw_180.JPG: 480x640 (no detections), 306.7ms
Speed: 1.0ms preprocess, 306.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQxV5FHiMfOOuUddux_1Yw_270.JPG: 480x640 (no detections), 303.7ms
Speed: 1.4ms preprocess, 303.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQyThHk-S7QjNNzlBVTd0g_0.JPG: 480x640 (no detections), 282.2ms
Speed: 1.2ms preprocess, 282.2ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQyThHk-S7QjNNzlBVTd0g_90.JPG: 480x640 (no detections), 274.6ms
Speed: 1.1ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQyThHk-S7QjNNzlBVTd0g_180.JPG: 480x640 (no detections), 277.6ms
Speed: 1.1ms preprocess, 277.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wQyThHk-S7QjNNzlBVTd0g_270.JPG: 480x640 (no detections), 269.1ms
Speed: 1.0ms preprocess, 269.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wR14ZjA4dXK9mb6ri57eUQ_0.JPG: 480x640 (no detections), 272.6ms
Speed: 1.2ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wR14ZjA4dXK9mb6ri57eUQ_90.JPG: 480x640 (no detections), 267.9ms
Speed: 1.2ms preprocess, 267.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wR14ZjA4dXK9mb6ri57eUQ_180.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wR14ZjA4dXK9mb6ri57eUQ_270.JPG: 480x640 (no detections), 266.2ms
Speed: 1.0ms preprocess, 266.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wR5D7jizmqCkgXnSBx-flA_0.JPG: 480x640 (no detections), 301.8ms
Speed: 1.1ms preprocess, 301.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wR5D7jizmqCkgXnSBx-flA_90.JPG: 480x640 (no detections), 271.8ms
Speed: 1.0ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wR5D7jizmqCkgXnSBx-flA_180.JPG: 480x640 (no detections), 268.2ms
Speed: 1.1ms preprocess, 268.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wR5D7jizmqCkgXnSBx-flA_270.JPG: 480x640 (no detections), 270.5ms
Speed: 1.1ms preprocess, 270.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wR7SkIrFnrorL6wH5hLCfg_0.JPG: 480x640 (no detections), 274.2ms
Speed: 1.0ms preprocess, 274.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wR7SkIrFnrorL6wH5hLCfg_90.JPG: 480x640 (no detections), 268.6ms
Speed: 1.3ms preprocess, 268.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wR7SkIrFnrorL6wH5hLCfg_180.JPG: 480x640 (no detections), 268.1ms
Speed: 1.2ms preprocess, 268.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wR7SkIrFnrorL6wH5hLCfg_270.JPG: 480x640 (no detections), 274.4ms
Speed: 1.1ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wR8r3cH91wRw-1dx70ENrA_0.JPG: 480x640 (no detections), 273.2ms
Speed: 1.2ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wR8r3cH91wRw-1dx70ENrA_90.JPG: 480x640 (no detections), 273.7ms
Speed: 1.2ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wR8r3cH91wRw-1dx70ENrA_180.JPG: 480x640 (no detections), 264.6ms
Speed: 1.1ms preprocess, 264.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wR8r3cH91wRw-1dx70ENrA_270.JPG: 480x640 (no detections), 272.0ms
Speed: 1.1ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wR9EBvSYIP-PLQlkL-y9nA_0.JPG: 480x640 (no detections), 272.5ms
Speed: 1.1ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wR9EBvSYIP-PLQlkL-y9nA_90.JPG: 480x640 (no detections), 268.3ms
Speed: 1.2ms preprocess, 268.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wR9EBvSYIP-PLQlkL-y9nA_180.JPG: 480x640 (no detections), 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wR9EBvSYIP-PLQlkL-y9nA_270.JPG: 480x640 (no detections), 269.8ms
Speed: 1.1ms preprocess, 269.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wR9rHlPvDefV_NYys_LhcQ_0.JPG: 480x640 (no detections), 269.3ms
Speed: 1.1ms preprocess, 269.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wR9rHlPvDefV_NYys_LhcQ_90.JPG: 480x640 (no detections), 268.1ms
Speed: 1.1ms preprocess, 268.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wR9rHlPvDefV_NYys_LhcQ_180.JPG: 480x640 (no detections), 275.4ms
Speed: 1.3ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wR9rHlPvDefV_NYys_LhcQ_270.JPG: 480x640 (no detections), 270.9ms
Speed: 1.2ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRA5DlNgmxPNIz_nf5JDnA_0.JPG: 480x640 (no detections), 276.9ms
Speed: 1.0ms preprocess, 276.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRA5DlNgmxPNIz_nf5JDnA_90.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRA5DlNgmxPNIz_nf5JDnA_180.JPG: 480x640 (no detections), 279.5ms
Speed: 1.1ms preprocess, 279.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRA5DlNgmxPNIz_nf5JDnA_270.JPG: 480x640 (no detections), 273.1ms
Speed: 1.1ms preprocess, 273.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRA9LV_k48E8rleRB_OKIA_0.JPG: 480x640 (no detections), 296.0ms
Speed: 1.3ms preprocess, 296.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRA9LV_k48E8rleRB_OKIA_90.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRA9LV_k48E8rleRB_OKIA_180.JPG: 480x640 (no detections), 269.5ms
Speed: 1.0ms preprocess, 269.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRA9LV_k48E8rleRB_OKIA_270.JPG: 480x640 (no detections), 269.1ms
Speed: 1.1ms preprocess, 269.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRADQs96t-eTgHxY5ng_3A_0.JPG: 480x640 (no detections), 269.1ms
Speed: 1.1ms preprocess, 269.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRADQs96t-eTgHxY5ng_3A_90.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRADQs96t-eTgHxY5ng_3A_180.JPG: 480x640 (no detections), 267.8ms
Speed: 1.0ms preprocess, 267.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRADQs96t-eTgHxY5ng_3A_270.JPG: 480x640 (no detections), 265.0ms
Speed: 1.1ms preprocess, 265.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRBZ2s3CQ7wcL8-BQ37Gcg_0.JPG: 480x640 (no detections), 268.6ms
Speed: 1.3ms preprocess, 268.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRBZ2s3CQ7wcL8-BQ37Gcg_90.JPG: 480x640 (no detections), 275.5ms
Speed: 1.1ms preprocess, 275.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRBZ2s3CQ7wcL8-BQ37Gcg_180.JPG: 480x640 (no detections), 270.0ms
Speed: 1.0ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRBZ2s3CQ7wcL8-BQ37Gcg_270.JPG: 480x640 (no detections), 267.3ms
Speed: 1.0ms preprocess, 267.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRDl6JA0XoBJRx_VRhYsuw_0.JPG: 480x640 (no detections), 269.4ms
Speed: 1.0ms preprocess, 269.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRDl6JA0XoBJRx_VRhYsuw_90.JPG: 480x640 (no detections), 272.0ms
Speed: 1.1ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRDl6JA0XoBJRx_VRhYsuw_180.JPG: 480x640 (no detections), 272.5ms
Speed: 1.1ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRDl6JA0XoBJRx_VRhYsuw_270.JPG: 480x640 (no detections), 272.4ms
Speed: 1.4ms preprocess, 272.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRF5beHZ80AGSoZrl7dFOA_0.JPG: 480x640 (no detections), 275.5ms
Speed: 1.1ms preprocess, 275.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRF5beHZ80AGSoZrl7dFOA_90.JPG: 480x640 (no detections), 271.4ms
Speed: 1.0ms preprocess, 271.4ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRF5beHZ80AGSoZrl7dFOA_180.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRF5beHZ80AGSoZrl7dFOA_270.JPG: 480x640 (no detections), 273.2ms
Speed: 1.0ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRLvuB1J6sPjTJw1vOx-pA_0.JPG: 480x640 (no detections), 267.3ms
Speed: 1.2ms preprocess, 267.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRLvuB1J6sPjTJw1vOx-pA_90.JPG: 480x640 (no detections), 267.0ms
Speed: 1.3ms preprocess, 267.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRLvuB1J6sPjTJw1vOx-pA_180.JPG: 480x640 (no detections), 265.9ms
Speed: 1.0ms preprocess, 265.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRLvuB1J6sPjTJw1vOx-pA_270.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRNfZwPFmijWncdgIg2yTw_0.JPG: 480x640 (no detections), 272.1ms
Speed: 1.1ms preprocess, 272.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRNfZwPFmijWncdgIg2yTw_90.JPG: 480x640 (no detections), 271.3ms
Speed: 1.2ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRNfZwPFmijWncdgIg2yTw_180.JPG: 480x640 (no detections), 274.3ms
Speed: 1.1ms preprocess, 274.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRNfZwPFmijWncdgIg2yTw_270.JPG: 480x640 (no detections), 274.6ms
Speed: 1.1ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wROSqpgPjN6spm24NQHcAQ_0.JPG: 480x640 (no detections), 266.1ms
Speed: 1.1ms preprocess, 266.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wROSqpgPjN6spm24NQHcAQ_90.JPG: 480x640 (no detections), 272.0ms

Speed: 1.2ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wROSqpgPjN6spm24NQHcAQ_180.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wROSqpgPjN6spm24NQHcAQ_270.JPG: 480x640 (no detections), 268.7ms
Speed: 1.4ms preprocess, 268.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRTY3H6cRZvWaY2-FMvN5w_0.JPG: 480x640 (no detections), 273.6ms
Speed: 1.2ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRTY3H6cRZvWaY2-FMvN5w_90.JPG: 480x640 (no detections), 269.5ms
Speed: 1.1ms preprocess, 269.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRTY3H6cRZvWaY2-FMvN5w_180.JPG: 480x640 (no detections), 272.0ms
Speed: 1.0ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRTY3H6cRZvWaY2-FMvN5w_270.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRWtNzfysJbGRZDEcbO7pw_0.JPG: 480x640 1 Waste, 272.4ms
Speed: 1.0ms preprocess, 272.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRWtNzfysJbGRZDEcbO7pw_90.JPG: 480x640 (no detections), 269.1ms
Speed: 1.1ms preprocess, 269.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRWtNzfysJbGRZDEcbO7pw_180.JPG: 480x640 (no detections), 287.9ms
Speed: 1.3ms preprocess, 287.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRWtNzfysJbGRZDEcbO7pw_270.JPG: 480x640 (no detections), 270.5ms
Speed: 1.1ms preprocess, 270.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRY7mUVD4JuKEVtcIUHMUA_0.JPG: 480x640 (no detections), 270.9ms
Speed: 1.0ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRY7mUVD4JuKEVtcIUHMUA_90.JPG: 480x640 (no detections), 275.6ms
Speed: 1.2ms preprocess, 275.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRY7mUVD4JuKEVtcIUHMUA_180.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRY7mUVD4JuKEVtcIUHMUA_270.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRYxoj49PwP25EAodU7THA_0.JPG: 480x640 (no detections), 275.3ms
Speed: 1.1ms preprocess, 275.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRYxoj49PwP25EAodU7THA_90.JPG: 480x640 (no detections), 268.5ms
Speed: 1.1ms preprocess, 268.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRYxoj49PwP25EAodU7THA_180.JPG: 480x640 (no detections), 269.1ms
Speed: 1.0ms preprocess, 269.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRYxoj49PwP25EAodU7THA_270.JPG: 480x640 (no detections), 267.6ms
Speed: 1.5ms preprocess, 267.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wR__i-D-j-teRIwY6UMEYg_0.JPG: 480x640 (no detections), 267.8ms
Speed: 1.2ms preprocess, 267.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wR__i-D-j-teRIwY6UMEYg_90.JPG: 480x640 (no detections), 297.7ms
Speed: 1.0ms preprocess, 297.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wR__i-D-j-teRIwY6UMEYg_180.JPG: 480x640 (no detections), 266.9ms
Speed: 1.1ms preprocess, 266.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wR__i-D-j-teRIwY6UMEYg_270.JPG: 480x640 1 Waste, 265.7ms
Speed: 1.1ms preprocess, 265.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRcD_SxwTOj7n5RpKGMvDw_0.JPG: 480x640 (no detections), 265.6ms
Speed: 1.1ms preprocess, 265.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRcD_SxwTOj7n5RpKGMvDw_90.JPG: 480x640 (no detections), 270.0ms
Speed: 1.2ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRcD_SxwTOj7n5RpKGMvDw_180.JPG: 480x640 (no detections), 268.0ms
Speed: 1.1ms preprocess, 268.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRcD_SxwTOj7n5RpKGMvDw_270.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRflikgvxUenfxrUz0ZUUA_0.JPG: 480x640 (no detections), 267.0ms
Speed: 1.1ms preprocess, 267.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRflikgvxUenfxrUz0ZUUA_90.JPG: 480x640 (no detections), 262.7ms
Speed: 1.1ms preprocess, 262.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRflikgvxUenfxrUz0ZUUA_180.JPG: 480x640 (no detections), 264.7ms
Speed: 1.0ms preprocess, 264.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRflikgvxUenfxrUz0ZUUA_270.JPG: 480x640 (no detections), 267.4ms
Speed: 1.0ms preprocess, 267.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRhS1jXJsyVsz-aFI-dCBw_0.JPG: 480x640 (no detections), 268.9ms
Speed: 1.1ms preprocess, 268.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRhS1jXJsyVsz-aFI-dCBw_90.JPG: 480x640 (no detections), 266.6ms
Speed: 1.2ms preprocess, 266.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRhS1jXJsyVsz-aFI-dCBw_180.JPG: 480x640 (no detections), 268.0ms
Speed: 1.1ms preprocess, 268.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRhS1jXJsyVsz-aFI-dCBw_270.JPG: 480x640 1 Waste, 265.2ms
Speed: 1.4ms preprocess, 265.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRj5l-ZS3-rHstXbKC9_cA_0.JPG: 480x640 (no detections), 267.5ms
Speed: 1.1ms preprocess, 267.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRj5l-ZS3-rHstXbKC9_cA_90.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRj5l-ZS3-rHstXbKC9_cA_180.JPG: 480x640 (no detections), 267.7ms
Speed: 1.1ms preprocess, 267.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRj5l-ZS3-rHstXbKC9_cA_270.JPG: 480x640 (no detections), 272.4ms
Speed: 1.1ms preprocess, 272.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRjP5cEAFswoINZzqKxn4A_0.JPG: 480x640 (no detections), 288.2ms
Speed: 1.0ms preprocess, 288.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRjP5cEAFswoINZzqKxn4A_90.JPG: 480x640 (no detections), 268.4ms
Speed: 1.1ms preprocess, 268.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRjP5cEAFswoINZzqKxn4A_180.JPG: 480x640 (no detections), 287.5ms
Speed: 1.1ms preprocess, 287.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRjP5cEAFswoINZzqKxn4A_270.JPG: 480x640 1 Waste, 267.6ms
Speed: 1.1ms preprocess, 267.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRk6U5mPTW75M7LI6IpyNA_0.JPG: 480x640 (no detections), 268.1ms
Speed: 1.0ms preprocess, 268.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRk6U5mPTW75M7LI6IpyNA_90.JPG: 480x640 (no detections), 268.7ms
Speed: 1.3ms preprocess, 268.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRk6U5mPTW75M7LI6IpyNA_180.JPG: 480x640 (no detections), 266.6ms
Speed: 1.2ms preprocess, 266.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRk6U5mPTW75M7LI6IpyNA_270.JPG: 480x640 (no detections), 263.5ms
Speed: 1.1ms preprocess, 263.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRmQwOnz7a72iSocSKpTEw_0.JPG: 480x640 (no detections), 267.3ms
Speed: 1.0ms preprocess, 267.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRmQwOnz7a72iSocSKpTEw_90.JPG: 480x640 (no detections), 269.1ms
Speed: 1.1ms preprocess, 269.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRmQwOnz7a72iSocSKpTEw_180.JPG: 480x640 (no detections), 267.4ms
Speed: 1.0ms preprocess, 267.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRmQwOnz7a72iSocSKpTEw_270.JPG: 480x640 (no detections), 272.3ms
Speed: 1.2ms preprocess, 272.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRnJKuxav_qPXB5KTOIlUA_0.JPG: 480x640 (no detections), 267.9ms
Speed: 1.1ms preprocess, 267.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRnJKuxav_qPXB5KTOIlUA_90.JPG: 480x640 (no detections), 268.4ms
Speed: 1.1ms preprocess, 268.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRnJKuxav_qPXB5KTOIlUA_180.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRnJKuxav_qPXB5KTOIlUA_270.JPG: 480x640 (no detections), 266.7ms
Speed: 1.0ms preprocess, 266.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRqicRz-h4UUKd0Gnqb5Xw_0.JPG: 480x640 (no detections), 267.3ms
Speed: 1.1ms preprocess, 267.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRqicRz-h4UUKd0Gnqb5Xw_90.JPG: 480x640 (no detections), 265.9ms
Speed: 1.1ms preprocess, 265.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRqicRz-h4UUKd0Gnqb5Xw_180.JPG: 480x640 (no detections), 267.3ms
Speed: 1.1ms preprocess, 267.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRqicRz-h4UUKd0Gnqb5Xw_270.JPG: 480x640 (no detections), 267.3ms
Speed: 1.2ms preprocess, 267.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRzNfl4MMPHP2bhbP3iYYg_0.JPG: 480x640 (no detections), 267.0ms
Speed: 1.2ms preprocess, 267.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRzNfl4MMPHP2bhbP3iYYg_90.JPG: 480x640 (no detections), 269.4ms
Speed: 1.1ms preprocess, 269.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRzNfl4MMPHP2bhbP3iYYg_180.JPG: 480x640 (no detections), 266.9ms
Speed: 1.0ms preprocess, 266.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRzNfl4MMPHP2bhbP3iYYg_270.JPG: 480x640 (no detections), 265.9ms
Speed: 1.0ms preprocess, 265.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRzncHEDakF0ffAvx3slkQ_0.JPG: 480x640 (no detections), 268.5ms
Speed: 1.2ms preprocess, 268.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRzncHEDakF0ffAvx3slkQ_90.JPG: 480x640 (no detections), 268.3ms
Speed: 1.1ms preprocess, 268.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRzncHEDakF0ffAvx3slkQ_180.JPG: 480x640 (no detections), 270.9ms
Speed: 1.1ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wRzncHEDakF0ffAvx3slkQ_270.JPG: 480x640 (no detections), 266.1ms
Speed: 1.1ms preprocess, 266.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wS-w-Of2Xuaz6FwU-89enA_0.JPG: 480x640 (no detections), 270.3ms

Speed: 1.1ms preprocess, 270.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wS-w-Of2Xuaz6FwU-89enA_90.JPG: 480x640 (no detections), 275.9ms
Speed: 1.0ms preprocess, 275.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wS-w-Of2Xuaz6FwU-89enA_180.JPG: 480x640 (no detections), 273.0ms
Speed: 1.2ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wS-w-Of2Xuaz6FwU-89enA_270.JPG: 480x640 (no detections), 266.7ms
Speed: 1.2ms preprocess, 266.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wS3cOa_MyBefLZZ24hG4rQ_0.JPG: 480x640 (no detections), 272.0ms
Speed: 1.2ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wS3cOa_MyBefLZZ24hG4rQ_90.JPG: 480x640 (no detections), 269.0ms
Speed: 1.2ms preprocess, 269.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wS3cOa_MyBefLZZ24hG4rQ_180.JPG: 480x640 (no detections), 268.8ms
Speed: 1.0ms preprocess, 268.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wS3cOa_MyBefLZZ24hG4rQ_270.JPG: 480x640 (no detections), 269.6ms
Speed: 1.1ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wS6M-nHWpaUVyKyeI6yFiA_0.JPG: 480x640 (no detections), 262.2ms
Speed: 1.2ms preprocess, 262.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wS6M-nHWpaUVyKyeI6yFiA_90.JPG: 480x640 (no detections), 267.6ms
Speed: 1.1ms preprocess, 267.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wS6M-nHWpaUVyKyeI6yFiA_180.JPG: 480x640 (no detections), 267.0ms
Speed: 1.1ms preprocess, 267.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wS6M-nHWpaUVyKyeI6yFiA_270.JPG: 480x640 (no detections), 263.8ms
Speed: 1.1ms preprocess, 263.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wS6xywjfjw3p3bRAmXwGGA_0.JPG: 480x640 (no detections), 268.8ms
Speed: 1.1ms preprocess, 268.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wS6xywjfjw3p3bRAmXwGGA_90.JPG: 480x640 (no detections), 267.7ms
Speed: 1.1ms preprocess, 267.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wS6xywjfjw3p3bRAmXwGGA_180.JPG: 480x640 (no detections), 265.8ms
Speed: 1.1ms preprocess, 265.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wS6xywjfjw3p3bRAmXwGGA_270.JPG: 480x640 (no detections), 302.5ms
Speed: 1.1ms preprocess, 302.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSAYDd46XWa8N6gHIQAwJA_0.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSAYDd46XWa8N6gHIQAwJA_90.JPG: 480x640 (no detections), 266.5ms
Speed: 1.0ms preprocess, 266.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSAYDd46XWa8N6gHIQAwJA_180.JPG: 480x640 (no detections), 269.3ms
Speed: 1.1ms preprocess, 269.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSAYDd46XWa8N6gHIQAwJA_270.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSCYTocK5XHIJJgoLyLoAg_0.JPG: 480x640 (no detections), 267.2ms
Speed: 1.1ms preprocess, 267.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSCYTocK5XHIJJgoLyLoAg_90.JPG: 480x640 (no detections), 265.7ms
Speed: 1.0ms preprocess, 265.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSCYTocK5XHIJJgoLyLoAg_180.JPG: 480x640 (no detections), 269.6ms
Speed: 1.1ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSCYTocK5XHIJJgoLyLoAg_270.JPG: 480x640 (no detections), 267.0ms
Speed: 1.1ms preprocess, 267.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSGXosQ5xhV_qMS63CPBLQ_0.JPG: 480x640 (no detections), 266.0ms
Speed: 1.1ms preprocess, 266.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSGXosQ5xhV_qMS63CPBLQ_90.JPG: 480x640 (no detections), 268.3ms
Speed: 1.1ms preprocess, 268.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSGXosQ5xhV_qMS63CPBLQ_180.JPG: 480x640 (no detections), 264.9ms
Speed: 1.1ms preprocess, 264.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSGXosQ5xhV_qMS63CPBLQ_270.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSIOEZ8S1v8cp70VqjdBlQ_0.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSIOEZ8S1v8cp70VqjdBlQ_90.JPG: 480x640 (no detections), 268.0ms
Speed: 1.1ms preprocess, 268.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSIOEZ8S1v8cp70VqjdBlQ_180.JPG: 480x640 (no detections), 271.0ms
Speed: 1.1ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSIOEZ8S1v8cp70VqjdBlQ_270.JPG: 480x640 (no detections), 266.8ms
Speed: 1.2ms preprocess, 266.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSLZtsBrCnXjPFPvHetsoQ_0.JPG: 480x640 (no detections), 265.5ms
Speed: 1.1ms preprocess, 265.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSLZtsBrCnXjPFPvHetsoQ_90.JPG: 480x640 (no detections), 268.9ms
Speed: 1.2ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSLZtsBrCnXjPFPvHetsoQ_180.JPG: 480x640 (no detections), 267.9ms
Speed: 1.0ms preprocess, 267.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSLZtsBrCnXjPFPvHetsoQ_270.JPG: 480x640 (no detections), 267.3ms
Speed: 1.0ms preprocess, 267.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSMk6E1LVNFNiMPei6x0sw_0.JPG: 480x640 (no detections), 264.5ms
Speed: 1.0ms preprocess, 264.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSMk6E1LVNFNiMPei6x0sw_90.JPG: 480x640 (no detections), 267.5ms
Speed: 1.1ms preprocess, 267.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSMk6E1LVNFNiMPei6x0sw_180.JPG: 480x640 (no detections), 266.2ms
Speed: 1.0ms preprocess, 266.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSMk6E1LVNFNiMPei6x0sw_270.JPG: 480x640 (no detections), 267.9ms
Speed: 1.0ms preprocess, 267.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSN2tWQNpkxd2PNBOzWaZw_0.JPG: 480x640 (no detections), 266.9ms
Speed: 1.1ms preprocess, 266.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSN2tWQNpkxd2PNBOzWaZw_90.JPG: 480x640 (no detections), 269.3ms
Speed: 1.1ms preprocess, 269.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSN2tWQNpkxd2PNBOzWaZw_180.JPG: 480x640 (no detections), 266.4ms
Speed: 1.2ms preprocess, 266.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSN2tWQNpkxd2PNBOzWaZw_270.JPG: 480x640 (no detections), 269.4ms
Speed: 1.0ms preprocess, 269.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSSmBDvNpV_V6EQRWdDvIA_0.JPG: 480x640 (no detections), 268.9ms
Speed: 1.1ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSSmBDvNpV_V6EQRWdDvIA_90.JPG: 480x640 (no detections), 271.6ms
Speed: 1.2ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSSmBDvNpV_V6EQRWdDvIA_180.JPG: 480x640 (no detections), 264.4ms
Speed: 1.0ms preprocess, 264.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSSmBDvNpV_V6EQRWdDvIA_270.JPG: 480x640 (no detections), 267.9ms
Speed: 1.1ms preprocess, 267.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSTBo4Aq3Ey8yNg_HrcG-Q_0.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSTBo4Aq3Ey8yNg_HrcG-Q_90.JPG: 480x640 (no detections), 271.4ms
Speed: 1.0ms preprocess, 271.4ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSTBo4Aq3Ey8yNg_HrcG-Q_180.JPG: 480x640 (no detections), 269.6ms
Speed: 1.1ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSTBo4Aq3Ey8yNg_HrcG-Q_270.JPG: 480x640 (no detections), 268.5ms
Speed: 1.1ms preprocess, 268.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSWJGkwQZjnQvmfwYWtNgw_0.JPG: 480x640 (no detections), 269.6ms
Speed: 1.1ms preprocess, 269.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSWJGkwQZjnQvmfwYWtNgw_90.JPG: 480x640 (no detections), 264.6ms
Speed: 1.1ms preprocess, 264.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSWJGkwQZjnQvmfwYWtNgw_180.JPG: 480x640 (no detections), 268.9ms
Speed: 1.2ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSWJGkwQZjnQvmfwYWtNgw_270.JPG: 480x640 (no detections), 270.9ms
Speed: 1.2ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSYTo0rFhcjHhPSS_xx54w_0.JPG: 480x640 (no detections), 270.9ms
Speed: 1.1ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSYTo0rFhcjHhPSS_xx54w_90.JPG: 480x640 (no detections), 265.5ms
Speed: 1.0ms preprocess, 265.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSYTo0rFhcjHhPSS_xx54w_180.JPG: 480x640 (no detections), 262.3ms
Speed: 1.0ms preprocess, 262.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSYTo0rFhcjHhPSS_xx54w_270.JPG: 480x640 (no detections), 265.6ms
Speed: 1.1ms preprocess, 265.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSZhB13u2EMnwUFymmmPMw_0.JPG: 480x640 (no detections), 270.8ms
Speed: 1.0ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSZhB13u2EMnwUFymmmPMw_90.JPG: 480x640 (no detections), 266.1ms
Speed: 1.0ms preprocess, 266.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSZhB13u2EMnwUFymmmPMw_180.JPG: 480x640 (no detections), 267.6ms
Speed: 1.2ms preprocess, 267.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSZhB13u2EMnwUFymmmPMw_270.JPG: 480x640 1 Waste, 267.7ms
Speed: 1.0ms preprocess, 267.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSaCzfa_6OxsjIjcTNtH3A_0.JPG: 480x640 (no detections), 270.6ms
Speed: 1.0ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSaCzfa_6OxsjIjcTNtH3A_90.JPG: 480x640 (no detections), 266.2ms
Speed: 1.1ms preprocess, 266.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSaCzfa_6OxsjIjcTNtH3A_180.JPG: 480x640 (no detections), 265.1ms
Speed: 1.1ms preprocess, 265.1ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSaCzfa_6OxsjIjcTNtH3A_270.JPG: 480x640 (no detections), 269.0ms

Speed: 1.0ms preprocess, 269.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wScucq0iLga_27Huk2rQ3g_0.JPG: 480x640 (no detections), 268.9ms
Speed: 1.0ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wScucq0iLga_27Huk2rQ3g_90.JPG: 480x640 (no detections), 267.4ms
Speed: 1.0ms preprocess, 267.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wScucq0iLga_27Huk2rQ3g_180.JPG: 480x640 (no detections), 267.2ms
Speed: 1.0ms preprocess, 267.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wScucq0iLga_27Huk2rQ3g_270.JPG: 480x640 (no detections), 265.4ms
Speed: 1.2ms preprocess, 265.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wScxlj_dBBOPUd-iVwIMpw_0.JPG: 480x640 (no detections), 266.2ms
Speed: 1.1ms preprocess, 266.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wScxlj_dBBOPUd-iVwIMpw_90.JPG: 480x640 (no detections), 265.1ms
Speed: 1.1ms preprocess, 265.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wScxlj_dBBOPUd-iVwIMpw_180.JPG: 480x640 (no detections), 272.0ms
Speed: 1.1ms preprocess, 272.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wScxlj_dBBOPUd-iVwIMpw_270.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wScyaNwRZylLBl9Uz5x7Aw_0.JPG: 480x640 (no detections), 264.9ms
Speed: 1.1ms preprocess, 264.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wScyaNwRZylLBl9Uz5x7Aw_90.JPG: 480x640 (no detections), 265.6ms
Speed: 1.6ms preprocess, 265.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wScyaNwRZylLBl9Uz5x7Aw_180.JPG: 480x640 (no detections), 269.0ms
Speed: 1.1ms preprocess, 269.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wScyaNwRZylLBl9Uz5x7Aw_270.JPG: 480x640 (no detections), 263.0ms
Speed: 1.4ms preprocess, 263.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSicyiljqJcs8qF9JwoBkg_0.JPG: 480x640 (no detections), 265.5ms
Speed: 1.1ms preprocess, 265.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSicyiljqJcs8qF9JwoBkg_90.JPG: 480x640 (no detections), 267.3ms
Speed: 1.1ms preprocess, 267.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSicyiljqJcs8qF9JwoBkg_180.JPG: 480x640 (no detections), 266.1ms
Speed: 1.0ms preprocess, 266.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSicyiljqJcs8qF9JwoBkg_270.JPG: 480x640 (no detections), 266.5ms
Speed: 1.1ms preprocess, 266.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSmajvLqnNWpcjZqB3TvhQ_0.JPG: 480x640 (no detections), 270.6ms
Speed: 1.3ms preprocess, 270.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSmajvLqnNWpcjZqB3TvhQ_90.JPG: 480x640 (no detections), 269.4ms
Speed: 1.1ms preprocess, 269.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSmajvLqnNWpcjZqB3TvhQ_180.JPG: 480x640 (no detections), 264.3ms
Speed: 1.0ms preprocess, 264.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSmajvLqnNWpcjZqB3TvhQ_270.JPG: 480x640 (no detections), 266.5ms
Speed: 1.0ms preprocess, 266.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSt3fRt0EAYHwCZ4b11plA_0.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSt3fRt0EAYHwCZ4b11plA_90.JPG: 480x640 (no detections), 271.7ms
Speed: 1.0ms preprocess, 271.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSt3fRt0EAYHwCZ4b11plA_180.JPG: 480x640 (no detections), 269.9ms
Speed: 1.2ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wSt3fRt0EAYHwCZ4b11plA_270.JPG: 480x640 (no detections), 272.4ms
Speed: 1.1ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wT8Z6yzp6_MKFOxwUYNgOw_0.JPG: 480x640 (no detections), 265.9ms
Speed: 1.1ms preprocess, 265.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wT8Z6yzp6_MKFOxwUYNgOw_90.JPG: 480x640 (no detections), 268.1ms
Speed: 1.1ms preprocess, 268.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wT8Z6yzp6_MKFOxwUYNgOw_180.JPG: 480x640 (no detections), 268.5ms
Speed: 1.0ms preprocess, 268.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wT8Z6yzp6_MKFOxwUYNgOw_270.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wT9iFS-u71olVc_a4-O_VA_0.JPG: 480x640 (no detections), 268.3ms
Speed: 1.0ms preprocess, 268.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wT9iFS-u71olVc_a4-O_VA_90.JPG: 480x640 (no detections), 264.4ms
Speed: 1.1ms preprocess, 264.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wT9iFS-u71olVc_a4-O_VA_180.JPG: 480x640 (no detections), 266.7ms
Speed: 1.0ms preprocess, 266.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wT9iFS-u71olVc_a4-O_VA_270.JPG: 480x640 (no detections), 279.9ms
Speed: 1.0ms preprocess, 279.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wT9tivpT9w48vG-pgw-HEA_0.JPG: 480x640 (no detections), 301.6ms
Speed: 1.1ms preprocess, 301.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wT9tivpT9w48vG-pgw-HEA_90.JPG: 480x640 (no detections), 277.2ms
Speed: 1.1ms preprocess, 277.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wT9tivpT9w48vG-pgw-HEA_180.JPG: 480x640 (no detections), 277.6ms
Speed: 1.1ms preprocess, 277.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wT9tivpT9w48vG-pgw-HEA_270.JPG: 480x640 (no detections), 278.9ms
Speed: 1.3ms preprocess, 278.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTC_8XUJA_yKpY_tBBRSNg_0.JPG: 480x640 (no detections), 277.4ms
Speed: 1.1ms preprocess, 277.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTC_8XUJA_yKpY_tBBRSNg_90.JPG: 480x640 (no detections), 265.3ms
Speed: 1.1ms preprocess, 265.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTC_8XUJA_yKpY_tBBRSNg_180.JPG: 480x640 (no detections), 322.8ms
Speed: 1.1ms preprocess, 322.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTC_8XUJA_yKpY_tBBRSNg_270.JPG: 480x640 (no detections), 344.5ms
Speed: 1.5ms preprocess, 344.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTGDvbhFBquYXvFyfCEsPg_0.JPG: 480x640 (no detections), 359.1ms
Speed: 1.7ms preprocess, 359.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTGDvbhFBquYXvFyfCEsPg_90.JPG: 480x640 (no detections), 356.0ms
Speed: 1.4ms preprocess, 356.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTGDvbhFBquYXvFyfCEsPg_180.JPG: 480x640 (no detections), 352.0ms
Speed: 1.4ms preprocess, 352.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTGDvbhFBquYXvFyfCEsPg_270.JPG: 480x640 (no detections), 315.0ms
Speed: 1.4ms preprocess, 315.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTJODbc8kzYvtpAaY_zBZQ_0.JPG: 480x640 (no detections), 317.5ms
Speed: 1.4ms preprocess, 317.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTJODbc8kzYvtpAaY_zBZQ_90.JPG: 480x640 (no detections), 274.0ms
Speed: 1.3ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTJODbc8kzYvtpAaY_zBZQ_180.JPG: 480x640 (no detections), 299.0ms
Speed: 1.1ms preprocess, 299.0ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTJODbc8kzYvtpAaY_zBZQ_270.JPG: 480x640 (no detections), 273.9ms
Speed: 1.3ms preprocess, 273.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTJedu2M9ivCaDapdejNxg_0.JPG: 480x640 (no detections), 273.2ms
Speed: 1.0ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTJedu2M9ivCaDapdejNxg_90.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTJedu2M9ivCaDapdejNxg_180.JPG: 480x640 (no detections), 263.0ms
Speed: 1.0ms preprocess, 263.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTJedu2M9ivCaDapdejNxg_270.JPG: 480x640 (no detections), 266.6ms
Speed: 1.1ms preprocess, 266.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTJlWqKLa_0WdER7fHmUcQ_0.JPG: 480x640 (no detections), 267.9ms
Speed: 1.1ms preprocess, 267.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTJlWqKLa_0WdER7fHmUcQ_90.JPG: 480x640 (no detections), 266.4ms
Speed: 1.1ms preprocess, 266.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTJlWqKLa_0WdER7fHmUcQ_180.JPG: 480x640 (no detections), 264.0ms
Speed: 1.0ms preprocess, 264.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTJlWqKLa_0WdER7fHmUcQ_270.JPG: 480x640 (no detections), 265.4ms
Speed: 1.0ms preprocess, 265.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTRA2bwg6_G4X_l9Gd5l8g_0.JPG: 480x640 (no detections), 266.0ms
Speed: 1.2ms preprocess, 266.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTRA2bwg6_G4X_l9Gd5l8g_90.JPG: 480x640 (no detections), 268.5ms
Speed: 1.0ms preprocess, 268.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTRA2bwg6_G4X_l9Gd5l8g_180.JPG: 480x640 (no detections), 267.4ms
Speed: 1.1ms preprocess, 267.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTRA2bwg6_G4X_l9Gd5l8g_270.JPG: 480x640 (no detections), 265.4ms
Speed: 1.1ms preprocess, 265.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTRPiCukOK9lo5vfutBzHA_0.JPG: 480x640 (no detections), 268.2ms
Speed: 1.0ms preprocess, 268.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTRPiCukOK9lo5vfutBzHA_90.JPG: 480x640 (no detections), 268.6ms
Speed: 1.0ms preprocess, 268.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTRPiCukOK9lo5vfutBzHA_180.JPG: 480x640 (no detections), 288.8ms
Speed: 1.1ms preprocess, 288.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTRPiCukOK9lo5vfutBzHA_270.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTSZh7m-REEJVeQCUtGY0w_0.JPG: 480x640 (no detections), 278.6ms
Speed: 1.1ms preprocess, 278.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTSZh7m-REEJVeQCUtGY0w_90.JPG: 480x640 (no detections), 280.2ms
Speed: 1.0ms preprocess, 280.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTSZh7m-REEJVeQCUtGY0w_180.JPG: 480x640 (no detections), 268.5ms

Speed: 1.1ms preprocess, 268.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTSZh7m-REEJVeQCUtGY0w_270.JPG: 480x640 (no detections), 268.1ms
Speed: 1.0ms preprocess, 268.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTTVkFtOBtVuSOsXwsOpiA_0.JPG: 480x640 (no detections), 277.9ms
Speed: 1.1ms preprocess, 277.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTTVkFtOBtVuSOsXwsOpiA_90.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTTVkFtOBtVuSOsXwsOpiA_180.JPG: 480x640 (no detections), 268.5ms
Speed: 1.1ms preprocess, 268.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTTVkFtOBtVuSOsXwsOpiA_270.JPG: 480x640 (no detections), 274.3ms
Speed: 1.1ms preprocess, 274.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTTpWYzF6POritsAra3D3w_0.JPG: 480x640 (no detections), 269.5ms
Speed: 1.0ms preprocess, 269.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTTpWYzF6POritsAra3D3w_90.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTTpWYzF6POritsAra3D3w_180.JPG: 480x640 (no detections), 270.0ms
Speed: 1.0ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTTpWYzF6POritsAra3D3w_270.JPG: 480x640 (no detections), 269.1ms
Speed: 1.1ms preprocess, 269.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTW6yY8R1s6xftw11gCb9Q_0.JPG: 480x640 (no detections), 269.0ms
Speed: 1.2ms preprocess, 269.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTW6yY8R1s6xftw11gCb9Q_90.JPG: 480x640 (no detections), 266.6ms
Speed: 1.2ms preprocess, 266.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTW6yY8R1s6xftw11gCb9Q_180.JPG: 480x640 (no detections), 276.0ms
Speed: 1.0ms preprocess, 276.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTW6yY8R1s6xftw11gCb9Q_270.JPG: 480x640 (no detections), 269.5ms
Speed: 1.1ms preprocess, 269.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTb_2nvoTeRlxHC1OxwRJQ_0.JPG: 480x640 (no detections), 270.6ms
Speed: 1.2ms preprocess, 270.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTb_2nvoTeRlxHC1OxwRJQ_90.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTb_2nvoTeRlxHC1OxwRJQ_180.JPG: 480x640 (no detections), 267.3ms
Speed: 2.0ms preprocess, 267.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTb_2nvoTeRlxHC1OxwRJQ_270.JPG: 480x640 (no detections), 268.8ms
Speed: 1.1ms preprocess, 268.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTeVhOg7xi6Y4w3mxbj3LA_0.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTeVhOg7xi6Y4w3mxbj3LA_90.JPG: 480x640 (no detections), 292.2ms
Speed: 1.2ms preprocess, 292.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTeVhOg7xi6Y4w3mxbj3LA_180.JPG: 480x640 (no detections), 281.5ms
Speed: 1.1ms preprocess, 281.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTeVhOg7xi6Y4w3mxbj3LA_270.JPG: 480x640 (no detections), 269.2ms
Speed: 1.1ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTgt8c0NpWpbpn_E1WdY4Q_0.JPG: 480x640 (no detections), 268.2ms
Speed: 1.1ms preprocess, 268.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTgt8c0NpWpbpn_E1WdY4Q_90.JPG: 480x640 (no detections), 267.4ms
Speed: 1.1ms preprocess, 267.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTgt8c0NpWpbpn_E1WdY4Q_180.JPG: 480x640 (no detections), 266.5ms
Speed: 1.1ms preprocess, 266.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTgt8c0NpWpbpn_E1WdY4Q_270.JPG: 480x640 (no detections), 266.4ms
Speed: 1.1ms preprocess, 266.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTh2Td9BHA1T2mIQf-tWgg_0.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTh2Td9BHA1T2mIQf-tWgg_90.JPG: 480x640 (no detections), 276.4ms
Speed: 1.2ms preprocess, 276.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTh2Td9BHA1T2mIQf-tWgg_180.JPG: 480x640 (no detections), 268.9ms
Speed: 1.0ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTh2Td9BHA1T2mIQf-tWgg_270.JPG: 480x640 (no detections), 267.8ms
Speed: 1.0ms preprocess, 267.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTqjHFCYbWcLzsIjxJJv2Q_0.JPG: 480x640 (no detections), 266.8ms
Speed: 1.1ms preprocess, 266.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTqjHFCYbWcLzsIjxJJv2Q_90.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTqjHFCYbWcLzsIjxJJv2Q_180.JPG: 480x640 (no detections), 270.3ms
Speed: 1.1ms preprocess, 270.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTqjHFCYbWcLzsIjxJJv2Q_270.JPG: 480x640 (no detections), 268.3ms
Speed: 1.0ms preprocess, 268.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTtaFotq1rCtijj0UqsomQ_0.JPG: 480x640 (no detections), 267.4ms
Speed: 1.2ms preprocess, 267.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTtaFotq1rCtijj0UqsomQ_90.JPG: 480x640 (no detections), 266.2ms
Speed: 1.1ms preprocess, 266.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTtaFotq1rCtijj0UqsomQ_180.JPG: 480x640 (no detections), 269.0ms
Speed: 1.2ms preprocess, 269.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTtaFotq1rCtijj0UqsomQ_270.JPG: 480x640 (no detections), 267.3ms
Speed: 1.1ms preprocess, 267.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTuGtldJeyatyoJB-k4sPw_0.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTuGtldJeyatyoJB-k4sPw_90.JPG: 480x640 1 Waste, 269.8ms
Speed: 1.1ms preprocess, 269.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTuGtldJeyatyoJB-k4sPw_180.JPG: 480x640 1 Waste, 269.7ms
Speed: 1.0ms preprocess, 269.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTuGtldJeyatyoJB-k4sPw_270.JPG: 480x640 (no detections), 279.6ms
Speed: 1.1ms preprocess, 279.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTv6RoIopmk3PQSdDKKbbA_0.JPG: 480x640 (no detections), 264.8ms
Speed: 1.0ms preprocess, 264.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTv6RoIopmk3PQSdDKKbbA_90.JPG: 480x640 (no detections), 269.2ms
Speed: 1.0ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTv6RoIopmk3PQSdDKKbbA_180.JPG: 480x640 (no detections), 262.1ms
Speed: 1.0ms preprocess, 262.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTv6RoIopmk3PQSdDKKbbA_270.JPG: 480x640 (no detections), 269.9ms
Speed: 1.0ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTx7dU8dsiYMpgF5RM5Ufg_0.JPG: 480x640 (no detections), 267.0ms
Speed: 1.1ms preprocess, 267.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTx7dU8dsiYMpgF5RM5Ufg_90.JPG: 480x640 (no detections), 266.9ms
Speed: 1.0ms preprocess, 266.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTx7dU8dsiYMpgF5RM5Ufg_180.JPG: 480x640 (no detections), 266.9ms
Speed: 1.0ms preprocess, 266.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTx7dU8dsiYMpgF5RM5Ufg_270.JPG: 480x640 (no detections), 269.6ms
Speed: 1.2ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTzqFeth85hzssPIcVKD-g_0.JPG: 480x640 (no detections), 266.0ms
Speed: 1.1ms preprocess, 266.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTzqFeth85hzssPIcVKD-g_90.JPG: 480x640 1 Waste, 267.0ms
Speed: 1.0ms preprocess, 267.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTzqFeth85hzssPIcVKD-g_180.JPG: 480x640 (no detections), 265.0ms
Speed: 1.1ms preprocess, 265.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wTzqFeth85hzssPIcVKD-g_270.JPG: 480x640 (no detections), 269.3ms
Speed: 1.1ms preprocess, 269.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wU0P4Jf4ZSjC0C338syE-g_0.JPG: 480x640 (no detections), 264.4ms
Speed: 1.1ms preprocess, 264.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wU0P4Jf4ZSjC0C338syE-g_90.JPG: 480x640 (no detections), 265.9ms
Speed: 1.0ms preprocess, 265.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wU0P4Jf4ZSjC0C338syE-g_180.JPG: 480x640 (no detections), 274.2ms
Speed: 1.1ms preprocess, 274.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wU0P4Jf4ZSjC0C338syE-g_270.JPG: 480x640 (no detections), 265.1ms
Speed: 1.1ms preprocess, 265.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wU0os4bF4TeF-iNwP2rcjg_0.JPG: 480x640 (no detections), 262.5ms
Speed: 1.1ms preprocess, 262.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wU0os4bF4TeF-iNwP2rcjg_90.JPG: 480x640 (no detections), 266.4ms
Speed: 1.2ms preprocess, 266.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wU0os4bF4TeF-iNwP2rcjg_180.JPG: 480x640 (no detections), 267.0ms
Speed: 1.1ms preprocess, 267.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wU0os4bF4TeF-iNwP2rcjg_270.JPG: 480x640 (no detections), 299.9ms
Speed: 1.1ms preprocess, 299.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wU29cQD_wdmnA5OtZk4yfA_0.JPG: 480x640 (no detections), 265.0ms
Speed: 1.1ms preprocess, 265.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wU29cQD_wdmnA5OtZk4yfA_90.JPG: 480x640 (no detections), 257.1ms
Speed: 1.1ms preprocess, 257.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wU29cQD_wdmnA5OtZk4yfA_180.JPG: 480x640 (no detections), 261.5ms
Speed: 1.0ms preprocess, 261.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wU29cQD_wdmnA5OtZk4yfA_270.JPG: 480x640 (no detections), 278.2ms
Speed: 1.0ms preprocess, 278.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wU4cB4-g_mKL5zKAenRjdQ_0.JPG: 480x640 (no detections), 299.5ms
Speed: 1.4ms preprocess, 299.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wU4cB4-g_mKL5zKAenRjdQ_90.JPG: 480x640 (no detections), 275.9ms

Speed: 1.2ms preprocess, 275.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wU4cB4-g_mKL5zKAenRjdQ_180.JPG: 480x640 (no detections), 270.5ms
Speed: 1.4ms preprocess, 270.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wU4cB4-g_mKL5zKAenRjdQ_270.JPG: 480x640 (no detections), 267.6ms
Speed: 1.1ms preprocess, 267.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wU4vrkh-BXTMeGkIPgNotQ_0.JPG: 480x640 (no detections), 275.2ms
Speed: 1.1ms preprocess, 275.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wU4vrkh-BXTMeGkIPgNotQ_90.JPG: 480x640 (no detections), 269.9ms
Speed: 1.2ms preprocess, 269.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wU4vrkh-BXTMeGkIPgNotQ_180.JPG: 480x640 (no detections), 275.6ms
Speed: 1.1ms preprocess, 275.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wU4vrkh-BXTMeGkIPgNotQ_270.JPG: 480x640 (no detections), 274.0ms
Speed: 1.1ms preprocess, 274.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wU5h_Sz2vRGm83zjWtf-gA_0.JPG: 480x640 (no detections), 282.2ms
Speed: 1.0ms preprocess, 282.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wU5h_Sz2vRGm83zjWtf-gA_90.JPG: 480x640 (no detections), 281.1ms
Speed: 1.2ms preprocess, 281.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wU5h_Sz2vRGm83zjWtf-gA_180.JPG: 480x640 (no detections), 277.2ms
Speed: 1.3ms preprocess, 277.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wU5h_Sz2vRGm83zjWtf-gA_270.JPG: 480x640 (no detections), 268.8ms
Speed: 1.8ms preprocess, 268.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wU8hxoAbcnkTeovorR144w_0.JPG: 480x640 (no detections), 277.8ms
Speed: 1.2ms preprocess, 277.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wU8hxoAbcnkTeovorR144w_90.JPG: 480x640 (no detections), 279.8ms
Speed: 1.1ms preprocess, 279.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wU8hxoAbcnkTeovorR144w_180.JPG: 480x640 (no detections), 312.4ms
Speed: 1.2ms preprocess, 312.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wU8hxoAbcnkTeovorR144w_270.JPG: 480x640 (no detections), 294.9ms
Speed: 1.8ms preprocess, 294.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wU97InQwqbrbgmHS3ooUAg_0.JPG: 480x640 (no detections), 284.4ms
Speed: 1.9ms preprocess, 284.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wU97InQwqbrbgmHS3ooUAg_90.JPG: 480x640 (no detections), 266.1ms
Speed: 1.1ms preprocess, 266.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wU97InQwqbrbgmHS3ooUAg_180.JPG: 480x640 (no detections), 287.2ms
Speed: 1.0ms preprocess, 287.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wU97InQwqbrbgmHS3ooUAg_270.JPG: 480x640 (no detections), 270.5ms
Speed: 1.1ms preprocess, 270.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wU9OmBKcGns6EclxZk5rHg_0.JPG: 480x640 (no detections), 270.2ms
Speed: 1.0ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wU9OmBKcGns6EclxZk5rHg_90.JPG: 480x640 (no detections), 268.4ms
Speed: 1.0ms preprocess, 268.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wU9OmBKcGns6EclxZk5rHg_180.JPG: 480x640 (no detections), 271.7ms
Speed: 1.2ms preprocess, 271.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wU9OmBKcGns6EclxZk5rHg_270.JPG: 480x640 (no detections), 266.8ms
Speed: 1.2ms preprocess, 266.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUATrGXQNROZ4iTv9BMvHw_0.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUATrGXQNROZ4iTv9BMvHw_90.JPG: 480x640 (no detections), 270.3ms
Speed: 1.1ms preprocess, 270.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUATrGXQNROZ4iTv9BMvHw_180.JPG: 480x640 (no detections), 266.9ms
Speed: 1.2ms preprocess, 266.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUATrGXQNROZ4iTv9BMvHw_270.JPG: 480x640 (no detections), 267.8ms
Speed: 1.1ms preprocess, 267.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUCU47SqmXbEW_5KttVJvw_0.JPG: 480x640 (no detections), 273.6ms
Speed: 1.2ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUCU47SqmXbEW_5KttVJvw_90.JPG: 480x640 (no detections), 267.8ms
Speed: 1.1ms preprocess, 267.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUCU47SqmXbEW_5KttVJvw_180.JPG: 480x640 (no detections), 282.2ms
Speed: 1.0ms preprocess, 282.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUCU47SqmXbEW_5KttVJvw_270.JPG: 480x640 (no detections), 271.5ms
Speed: 1.2ms preprocess, 271.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUJXNwtmTiiKBFm4gUf6qw_0.JPG: 480x640 1 Waste, 281.5ms
Speed: 1.0ms preprocess, 281.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUJXNwtmTiiKBFm4gUf6qw_90.JPG: 480x640 (no detections), 276.9ms
Speed: 1.1ms preprocess, 276.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUJXNwtmTiiKBFm4gUf6qw_180.JPG: 480x640 (no detections), 281.6ms
Speed: 1.2ms preprocess, 281.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUJXNwtmTiiKBFm4gUf6qw_270.JPG: 480x640 (no detections), 277.7ms
Speed: 1.1ms preprocess, 277.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUKEFxnzI5BLrk91LWkb8A_0.JPG: 480x640 (no detections), 272.6ms
Speed: 1.2ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUKEFxnzI5BLrk91LWkb8A_90.JPG: 480x640 (no detections), 271.0ms
Speed: 1.2ms preprocess, 271.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUKEFxnzI5BLrk91LWkb8A_180.JPG: 480x640 (no detections), 272.3ms
Speed: 1.5ms preprocess, 272.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUKEFxnzI5BLrk91LWkb8A_270.JPG: 480x640 (no detections), 270.2ms
Speed: 1.2ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUKUOEo2U0D6yGnH5NoHxw_0.JPG: 480x640 (no detections), 274.9ms
Speed: 1.1ms preprocess, 274.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUKUOEo2U0D6yGnH5NoHxw_90.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUKUOEo2U0D6yGnH5NoHxw_180.JPG: 480x640 (no detections), 273.2ms
Speed: 1.1ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUKUOEo2U0D6yGnH5NoHxw_270.JPG: 480x640 (no detections), 274.6ms
Speed: 1.0ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUKrYBJyOHPZdCHwXXJn4A_0.JPG: 480x640 (no detections), 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUKrYBJyOHPZdCHwXXJn4A_90.JPG: 480x640 (no detections), 367.5ms
Speed: 1.0ms preprocess, 367.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUKrYBJyOHPZdCHwXXJn4A_180.JPG: 480x640 (no detections), 326.5ms
Speed: 1.1ms preprocess, 326.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUKrYBJyOHPZdCHwXXJn4A_270.JPG: 480x640 1 Waste, 322.4ms
Speed: 1.5ms preprocess, 322.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wULqkhL32t924ra20BErQQ_0.JPG: 480x640 1 Waste, 289.9ms
Speed: 1.1ms preprocess, 289.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wULqkhL32t924ra20BErQQ_90.JPG: 480x640 (no detections), 288.6ms
Speed: 1.6ms preprocess, 288.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wULqkhL32t924ra20BErQQ_180.JPG: 480x640 (no detections), 312.7ms
Speed: 1.4ms preprocess, 312.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wULqkhL32t924ra20BErQQ_270.JPG: 480x640 (no detections), 283.0ms
Speed: 1.1ms preprocess, 283.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUN4gfvbljUkE2xwLQR9Rw_0.JPG: 480x640 (no detections), 274.3ms
Speed: 1.4ms preprocess, 274.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUN4gfvbljUkE2xwLQR9Rw_90.JPG: 480x640 (no detections), 274.0ms
Speed: 1.1ms preprocess, 274.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUN4gfvbljUkE2xwLQR9Rw_180.JPG: 480x640 (no detections), 267.7ms
Speed: 1.1ms preprocess, 267.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUN4gfvbljUkE2xwLQR9Rw_270.JPG: 480x640 (no detections), 269.8ms
Speed: 1.1ms preprocess, 269.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wURFskLgA4w6vcTj0UuFSw_0.JPG: 480x640 (no detections), 268.7ms
Speed: 1.1ms preprocess, 268.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wURFskLgA4w6vcTj0UuFSw_90.JPG: 480x640 (no detections), 271.6ms
Speed: 1.0ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wURFskLgA4w6vcTj0UuFSw_180.JPG: 480x640 (no detections), 310.7ms
Speed: 1.0ms preprocess, 310.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wURFskLgA4w6vcTj0UuFSw_270.JPG: 480x640 (no detections), 270.3ms
Speed: 1.1ms preprocess, 270.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wURj42SvdxhJYZ-6BFFaPw_0.JPG: 480x640 (no detections), 268.5ms
Speed: 1.2ms preprocess, 268.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wURj42SvdxhJYZ-6BFFaPw_90.JPG: 480x640 1 Waste, 275.9ms
Speed: 1.1ms preprocess, 275.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wURj42SvdxhJYZ-6BFFaPw_180.JPG: 480x640 (no detections), 268.5ms
Speed: 1.1ms preprocess, 268.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wURj42SvdxhJYZ-6BFFaPw_270.JPG: 480x640 (no detections), 267.1ms
Speed: 1.1ms preprocess, 267.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wURobo_ppKho1Q8cipgtpA_0.JPG: 480x640 (no detections), 270.4ms
Speed: 1.1ms preprocess, 270.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wURobo_ppKho1Q8cipgtpA_90.JPG: 480x640 (no detections), 270.4ms
Speed: 1.3ms preprocess, 270.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wURobo_ppKho1Q8cipgtpA_180.JPG: 480x640 (no detections), 269.2ms
Speed: 1.1ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wURobo_ppKho1Q8cipgtpA_270.JPG: 480x640 (no detections), 287.2ms
Speed: 1.1ms preprocess, 287.2ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUTIvQuZZp63adWjcFH_Vg_0.JPG: 480x640 (no detections), 282.6ms

Speed: 1.3ms preprocess, 282.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUTIvQuZZp63adWjcFH_Vg_90.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUTIvQuZZp63adWjcFH_Vg_180.JPG: 480x640 (no detections), 267.8ms
Speed: 1.1ms preprocess, 267.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUTIvQuZZp63adWjcFH_Vg_270.JPG: 480x640 (no detections), 275.2ms
Speed: 1.0ms preprocess, 275.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUVG4aan_mxNj7wdbhxkvA_0.JPG: 480x640 (no detections), 269.2ms
Speed: 1.2ms preprocess, 269.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUVG4aan_mxNj7wdbhxkvA_90.JPG: 480x640 (no detections), 275.9ms
Speed: 1.1ms preprocess, 275.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUVG4aan_mxNj7wdbhxkvA_180.JPG: 480x640 (no detections), 275.8ms
Speed: 1.1ms preprocess, 275.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUVG4aan_mxNj7wdbhxkvA_270.JPG: 480x640 (no detections), 277.0ms
Speed: 1.1ms preprocess, 277.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUW16S_YUWhd4MgaRrdKcg_0.JPG: 480x640 (no detections), 266.5ms
Speed: 1.0ms preprocess, 266.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUW16S_YUWhd4MgaRrdKcg_90.JPG: 480x640 (no detections), 284.3ms
Speed: 1.1ms preprocess, 284.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUW16S_YUWhd4MgaRrdKcg_180.JPG: 480x640 (no detections), 293.0ms
Speed: 1.4ms preprocess, 293.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUW16S_YUWhd4MgaRrdKcg_270.JPG: 480x640 (no detections), 290.2ms
Speed: 1.1ms preprocess, 290.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUZTtjDb3kvr3dPuJw-iTg_0.JPG: 480x640 (no detections), 318.7ms
Speed: 1.3ms preprocess, 318.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUZTtjDb3kvr3dPuJw-iTg_90.JPG: 480x640 (no detections), 284.9ms
Speed: 1.1ms preprocess, 284.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUZTtjDb3kvr3dPuJw-iTg_180.JPG: 480x640 (no detections), 304.7ms
Speed: 1.2ms preprocess, 304.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUZTtjDb3kvr3dPuJw-iTg_270.JPG: 480x640 (no detections), 321.9ms
Speed: 1.2ms preprocess, 321.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUZeCKE-Sxe9TCSERT42gg_0.JPG: 480x640 (no detections), 316.3ms
Speed: 1.2ms preprocess, 316.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUZeCKE-Sxe9TCSERT42gg_90.JPG: 480x640 (no detections), 286.1ms
Speed: 1.2ms preprocess, 286.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUZeCKE-Sxe9TCSERT42gg_180.JPG: 480x640 (no detections), 280.1ms
Speed: 1.4ms preprocess, 280.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUZeCKE-Sxe9TCSERT42gg_270.JPG: 480x640 (no detections), 279.5ms
Speed: 1.1ms preprocess, 279.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUcgPInSTO6PmtgPIfK7Rw_0.JPG: 480x640 (no detections), 276.9ms
Speed: 1.2ms preprocess, 276.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUcgPInSTO6PmtgPIfK7Rw_90.JPG: 480x640 (no detections), 279.2ms
Speed: 1.1ms preprocess, 279.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUcgPInSTO6PmtgPIfK7Rw_180.JPG: 480x640 (no detections), 271.1ms
Speed: 1.2ms preprocess, 271.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUcgPInSTO6PmtgPIfK7Rw_270.JPG: 480x640 (no detections), 267.4ms
Speed: 1.1ms preprocess, 267.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUeHc5Z2AirwMUX52v4OMg_0.JPG: 480x640 (no detections), 266.4ms
Speed: 1.0ms preprocess, 266.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUeHc5Z2AirwMUX52v4OMg_90.JPG: 480x640 (no detections), 268.4ms
Speed: 1.0ms preprocess, 268.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUeHc5Z2AirwMUX52v4OMg_180.JPG: 480x640 (no detections), 274.3ms
Speed: 1.1ms preprocess, 274.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUeHc5Z2AirwMUX52v4OMg_270.JPG: 480x640 (no detections), 283.4ms
Speed: 1.1ms preprocess, 283.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUgnnaRyWn46E4qxQuD_SA_0.JPG: 480x640 (no detections), 270.1ms
Speed: 1.0ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUgnnaRyWn46E4qxQuD_SA_90.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUgnnaRyWn46E4qxQuD_SA_180.JPG: 480x640 (no detections), 269.2ms
Speed: 1.0ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUgnnaRyWn46E4qxQuD_SA_270.JPG: 480x640 (no detections), 276.7ms
Speed: 1.3ms preprocess, 276.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUmGFqmyJQclhIdw7rH76w_0.JPG: 480x640 (no detections), 278.8ms
Speed: 1.2ms preprocess, 278.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUmGFqmyJQclhIdw7rH76w_90.JPG: 480x640 (no detections), 272.3ms
Speed: 1.2ms preprocess, 272.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUmGFqmyJQclhIdw7rH76w_180.JPG: 480x640 (no detections), 272.9ms
Speed: 1.2ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUmGFqmyJQclhIdw7rH76w_270.JPG: 480x640 (no detections), 278.3ms
Speed: 1.1ms preprocess, 278.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUn6EXvwcdkoeaL1iCMMyw_0.JPG: 480x640 (no detections), 281.8ms
Speed: 1.2ms preprocess, 281.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUn6EXvwcdkoeaL1iCMMyw_90.JPG: 480x640 (no detections), 277.7ms
Speed: 1.1ms preprocess, 277.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUn6EXvwcdkoeaL1iCMMyw_180.JPG: 480x640 (no detections), 328.4ms
Speed: 1.2ms preprocess, 328.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUn6EXvwcdkoeaL1iCMMyw_270.JPG: 480x640 (no detections), 327.1ms
Speed: 1.1ms preprocess, 327.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUnB1dMQZYjpptfKy2Jq_g_0.JPG: 480x640 (no detections), 302.6ms
Speed: 1.5ms preprocess, 302.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUnB1dMQZYjpptfKy2Jq_g_90.JPG: 480x640 (no detections), 286.6ms
Speed: 1.6ms preprocess, 286.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUnB1dMQZYjpptfKy2Jq_g_180.JPG: 480x640 (no detections), 267.1ms
Speed: 1.1ms preprocess, 267.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUnB1dMQZYjpptfKy2Jq_g_270.JPG: 480x640 (no detections), 308.0ms
Speed: 1.2ms preprocess, 308.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUnukyMW8yl_wSKqP9-VEQ_0.JPG: 480x640 (no detections), 275.2ms
Speed: 1.1ms preprocess, 275.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUnukyMW8yl_wSKqP9-VEQ_90.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUnukyMW8yl_wSKqP9-VEQ_180.JPG: 480x640 (no detections), 277.6ms
Speed: 1.0ms preprocess, 277.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUnukyMW8yl_wSKqP9-VEQ_270.JPG: 480x640 (no detections), 324.9ms
Speed: 1.1ms preprocess, 324.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUqEUUZnCiI6CkWvHWFjxA_0.JPG: 480x640 (no detections), 302.1ms
Speed: 1.2ms preprocess, 302.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUqEUUZnCiI6CkWvHWFjxA_90.JPG: 480x640 (no detections), 282.2ms
Speed: 1.3ms preprocess, 282.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUqEUUZnCiI6CkWvHWFjxA_180.JPG: 480x640 (no detections), 288.3ms
Speed: 1.1ms preprocess, 288.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUqEUUZnCiI6CkWvHWFjxA_270.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUqfkMA15NSHYcQ6dRzeew_0.JPG: 480x640 (no detections), 268.4ms
Speed: 1.3ms preprocess, 268.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUqfkMA15NSHYcQ6dRzeew_90.JPG: 480x640 (no detections), 274.5ms
Speed: 1.1ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUqfkMA15NSHYcQ6dRzeew_180.JPG: 480x640 (no detections), 274.5ms
Speed: 1.2ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wUqfkMA15NSHYcQ6dRzeew_270.JPG: 480x640 (no detections), 276.0ms
Speed: 1.4ms preprocess, 276.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wV0Vt9wKdGQLIQy0wH-xmg_0.JPG: 480x640 (no detections), 271.7ms
Speed: 1.2ms preprocess, 271.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wV0Vt9wKdGQLIQy0wH-xmg_90.JPG: 480x640 (no detections), 283.0ms
Speed: 1.1ms preprocess, 283.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wV0Vt9wKdGQLIQy0wH-xmg_180.JPG: 480x640 1 Waste, 308.9ms
Speed: 1.3ms preprocess, 308.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wV0Vt9wKdGQLIQy0wH-xmg_270.JPG: 480x640 (no detections), 283.1ms
Speed: 1.4ms preprocess, 283.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wV30t8Pnh3uelFitigpcIA_0.JPG: 480x640 (no detections), 276.4ms
Speed: 1.0ms preprocess, 276.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wV30t8Pnh3uelFitigpcIA_90.JPG: 480x640 (no detections), 273.9ms
Speed: 1.0ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wV30t8Pnh3uelFitigpcIA_180.JPG: 480x640 (no detections), 278.9ms
Speed: 1.2ms preprocess, 278.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wV30t8Pnh3uelFitigpcIA_270.JPG: 480x640 (no detections), 283.7ms
Speed: 1.1ms preprocess, 283.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wV3TwOLRLst-FOErJcJosw_0.JPG: 480x640 (no detections), 279.1ms
Speed: 1.1ms preprocess, 279.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wV3TwOLRLst-FOErJcJosw_90.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wV3TwOLRLst-FOErJcJosw_180.JPG: 480x640 1 Waste, 272.9ms
Speed: 1.3ms preprocess, 272.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wV3TwOLRLst-FOErJcJosw_270.JPG: 480x640 (no detections), 271.9ms

Speed: 1.2ms preprocess, 271.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wV61ulnf4Md5tDTlWonD7w_0.JPG: 480x640 (no detections), 275.1ms
Speed: 1.2ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wV61ulnf4Md5tDTlWonD7w_90.JPG: 480x640 (no detections), 274.5ms
Speed: 1.1ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wV61ulnf4Md5tDTlWonD7w_180.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wV61ulnf4Md5tDTlWonD7w_270.JPG: 480x640 1 Waste, 272.1ms
Speed: 1.0ms preprocess, 272.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wV6uGcSxffaEVuEQdvBjGA_0.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wV6uGcSxffaEVuEQdvBjGA_90.JPG: 480x640 (no detections), 267.6ms
Speed: 1.0ms preprocess, 267.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wV6uGcSxffaEVuEQdvBjGA_180.JPG: 480x640 (no detections), 271.8ms
Speed: 1.0ms preprocess, 271.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wV6uGcSxffaEVuEQdvBjGA_270.JPG: 480x640 (no detections), 269.5ms
Speed: 1.0ms preprocess, 269.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVBN_jfbmBShhOGgd2iwdg_0.JPG: 480x640 (no detections), 270.6ms
Speed: 1.2ms preprocess, 270.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVBN_jfbmBShhOGgd2iwdg_90.JPG: 480x640 1 Waste, 275.7ms
Speed: 1.5ms preprocess, 275.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVBN_jfbmBShhOGgd2iwdg_180.JPG: 480x640 (no detections), 269.0ms
Speed: 1.4ms preprocess, 269.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVBN_jfbmBShhOGgd2iwdg_270.JPG: 480x640 (no detections), 266.4ms
Speed: 1.1ms preprocess, 266.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVBVrwrJI9bYIU2-3fdfQg_0.JPG: 480x640 (no detections), 306.4ms
Speed: 1.2ms preprocess, 306.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVBVrwrJI9bYIU2-3fdfQg_90.JPG: 480x640 (no detections), 273.4ms
Speed: 1.1ms preprocess, 273.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVBVrwrJI9bYIU2-3fdfQg_180.JPG: 480x640 (no detections), 280.7ms
Speed: 1.1ms preprocess, 280.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVBVrwrJI9bYIU2-3fdfQg_270.JPG: 480x640 (no detections), 275.0ms
Speed: 1.4ms preprocess, 275.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVHeobHhK3ZkGFloEpqyjQ_0.JPG: 480x640 (no detections), 272.3ms
Speed: 1.1ms preprocess, 272.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVHeobHhK3ZkGFloEpqyjQ_90.JPG: 480x640 (no detections), 271.1ms
Speed: 1.2ms preprocess, 271.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVHeobHhK3ZkGFloEpqyjQ_180.JPG: 480x640 (no detections), 277.7ms
Speed: 1.1ms preprocess, 277.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVHeobHhK3ZkGFloEpqyjQ_270.JPG: 480x640 (no detections), 272.6ms
Speed: 1.2ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVHj_VxNxGc4ndJko8FSsQ_0.JPG: 480x640 (no detections), 274.1ms
Speed: 1.0ms preprocess, 274.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVHj_VxNxGc4ndJko8FSsQ_90.JPG: 480x640 (no detections), 274.6ms
Speed: 1.1ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVHj_VxNxGc4ndJko8FSsQ_180.JPG: 480x640 (no detections), 274.6ms
Speed: 1.0ms preprocess, 274.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVHj_VxNxGc4ndJko8FSsQ_270.JPG: 480x640 (no detections), 274.0ms
Speed: 1.0ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVKMWYSmpb9kgEPipCJo6A_0.JPG: 480x640 (no detections), 275.6ms
Speed: 1.1ms preprocess, 275.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVKMWYSmpb9kgEPipCJo6A_90.JPG: 480x640 (no detections), 275.7ms
Speed: 1.1ms preprocess, 275.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVKMWYSmpb9kgEPipCJo6A_180.JPG: 480x640 (no detections), 270.4ms
Speed: 1.1ms preprocess, 270.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVKMWYSmpb9kgEPipCJo6A_270.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVLoqXEI_30RipMUbCoWCg_0.JPG: 480x640 (no detections), 269.0ms
Speed: 1.1ms preprocess, 269.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVLoqXEI_30RipMUbCoWCg_90.JPG: 480x640 (no detections), 271.8ms
Speed: 1.0ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVLoqXEI_30RipMUbCoWCg_180.JPG: 480x640 (no detections), 272.4ms
Speed: 1.0ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVLoqXEI_30RipMUbCoWCg_270.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVMN8fU-l3seJJxg-wL7uA_0.JPG: 480x640 (no detections), 269.7ms
Speed: 1.2ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVMN8fU-l3seJJxg-wL7uA_90.JPG: 480x640 (no detections), 271.5ms
Speed: 1.1ms preprocess, 271.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVMN8fU-l3seJJxg-wL7uA_180.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVMN8fU-l3seJJxg-wL7uA_270.JPG: 480x640 (no detections), 290.8ms
Speed: 1.1ms preprocess, 290.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVOzEWQOXKbF3OMWcVnzIw_0.JPG: 480x640 (no detections), 270.5ms
Speed: 1.2ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVOzEWQOXKbF3OMWcVnzIw_90.JPG: 480x640 1 Waste, 273.1ms
Speed: 1.0ms preprocess, 273.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVOzEWQOXKbF3OMWcVnzIw_180.JPG: 480x640 (no detections), 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVOzEWQOXKbF3OMWcVnzIw_270.JPG: 480x640 (no detections), 274.8ms
Speed: 1.1ms preprocess, 274.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVQDwCUCOvudmqK0o9Sl9Q_0.JPG: 480x640 (no detections), 272.8ms
Speed: 1.0ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVQDwCUCOvudmqK0o9Sl9Q_90.JPG: 480x640 (no detections), 274.4ms
Speed: 1.1ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVQDwCUCOvudmqK0o9Sl9Q_180.JPG: 480x640 (no detections), 269.0ms
Speed: 1.1ms preprocess, 269.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVQDwCUCOvudmqK0o9Sl9Q_270.JPG: 480x640 (no detections), 271.5ms
Speed: 1.3ms preprocess, 271.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVUpZO5_40QY0F7jsm6ADg_0.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVUpZO5_40QY0F7jsm6ADg_90.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVUpZO5_40QY0F7jsm6ADg_180.JPG: 480x640 (no detections), 270.9ms
Speed: 1.6ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVUpZO5_40QY0F7jsm6ADg_270.JPG: 480x640 (no detections), 265.4ms
Speed: 1.1ms preprocess, 265.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVV8xLcJVMTlTVfjdKitfQ_0.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVV8xLcJVMTlTVfjdKitfQ_90.JPG: 480x640 (no detections), 274.4ms
Speed: 1.2ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVV8xLcJVMTlTVfjdKitfQ_180.JPG: 480x640 (no detections), 274.9ms
Speed: 1.2ms preprocess, 274.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVV8xLcJVMTlTVfjdKitfQ_270.JPG: 480x640 (no detections), 274.0ms
Speed: 1.1ms preprocess, 274.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVZST07EtGMEMNnmU9G_Mw_0.JPG: 480x640 (no detections), 272.1ms
Speed: 1.1ms preprocess, 272.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVZST07EtGMEMNnmU9G_Mw_90.JPG: 480x640 (no detections), 285.6ms
Speed: 1.2ms preprocess, 285.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVZST07EtGMEMNnmU9G_Mw_180.JPG: 480x640 (no detections), 271.5ms
Speed: 1.2ms preprocess, 271.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVZST07EtGMEMNnmU9G_Mw_270.JPG: 480x640 (no detections), 272.1ms
Speed: 1.0ms preprocess, 272.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVbiaoZVxAU39Kgyt_jOog_0.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVbiaoZVxAU39Kgyt_jOog_90.JPG: 480x640 (no detections), 272.1ms
Speed: 1.2ms preprocess, 272.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVbiaoZVxAU39Kgyt_jOog_180.JPG: 480x640 (no detections), 264.5ms
Speed: 1.1ms preprocess, 264.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVbiaoZVxAU39Kgyt_jOog_270.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVdG0F6kN1ZFkCXyhTf-1g_0.JPG: 480x640 (no detections), 288.7ms
Speed: 1.0ms preprocess, 288.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVdG0F6kN1ZFkCXyhTf-1g_90.JPG: 480x640 (no detections), 269.4ms
Speed: 1.1ms preprocess, 269.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVdG0F6kN1ZFkCXyhTf-1g_180.JPG: 480x640 (no detections), 269.0ms
Speed: 1.1ms preprocess, 269.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVdG0F6kN1ZFkCXyhTf-1g_270.JPG: 480x640 (no detections), 269.2ms
Speed: 1.0ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVsI8Ra5cr7NVb8htiZS1g_0.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVsI8Ra5cr7NVb8htiZS1g_90.JPG: 480x640 (no detections), 271.8ms
Speed: 1.3ms preprocess, 271.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVsI8Ra5cr7NVb8htiZS1g_180.JPG: 480x640 (no detections), 274.1ms

Speed: 1.1ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVsI8Ra5cr7NVb8htiZS1g_270.JPG: 480x640 (no detections), 280.3ms
Speed: 1.2ms preprocess, 280.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVsIh5FK9Y_EKymjwLzF1A_0.JPG: 480x640 (no detections), 273.5ms
Speed: 1.3ms preprocess, 273.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVsIh5FK9Y_EKymjwLzF1A_90.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVsIh5FK9Y_EKymjwLzF1A_180.JPG: 480x640 (no detections), 273.9ms
Speed: 1.2ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVsIh5FK9Y_EKymjwLzF1A_270.JPG: 480x640 (no detections), 275.3ms
Speed: 1.3ms preprocess, 275.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVsNLtMamoNHlVcJ4pqFVw_0.JPG: 480x640 (no detections), 281.0ms
Speed: 1.3ms preprocess, 281.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVsNLtMamoNHlVcJ4pqFVw_90.JPG: 480x640 1 Waste, 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVsNLtMamoNHlVcJ4pqFVw_180.JPG: 480x640 (no detections), 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVsNLtMamoNHlVcJ4pqFVw_270.JPG: 480x640 (no detections), 270.8ms
Speed: 1.2ms preprocess, 270.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVxdB5p9yEf7JcvpgOoMXg_0.JPG: 480x640 (no detections), 269.9ms
Speed: 1.0ms preprocess, 269.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVxdB5p9yEf7JcvpgOoMXg_90.JPG: 480x640 (no detections), 268.6ms
Speed: 1.1ms preprocess, 268.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVxdB5p9yEf7JcvpgOoMXg_180.JPG: 480x640 (no detections), 275.0ms
Speed: 1.0ms preprocess, 275.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wVxdB5p9yEf7JcvpgOoMXg_270.JPG: 480x640 (no detections), 270.9ms
Speed: 1.2ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wW1ZpxwftwXbVrm4ATZlmA_0.JPG: 480x640 (no detections), 275.3ms
Speed: 1.1ms preprocess, 275.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wW1ZpxwftwXbVrm4ATZlmA_90.JPG: 480x640 (no detections), 270.5ms
Speed: 1.1ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wW1ZpxwftwXbVrm4ATZlmA_180.JPG: 480x640 (no detections), 274.0ms
Speed: 1.3ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wW1ZpxwftwXbVrm4ATZlmA_270.JPG: 480x640 (no detections), 267.6ms
Speed: 1.1ms preprocess, 267.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wW54IulT64EYp6TCDh0Iyw_0.JPG: 480x640 (no detections), 269.8ms
Speed: 1.6ms preprocess, 269.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wW54IulT64EYp6TCDh0Iyw_90.JPG: 480x640 (no detections), 269.0ms
Speed: 1.1ms preprocess, 269.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wW54IulT64EYp6TCDh0Iyw_180.JPG: 480x640 (no detections), 269.6ms
Speed: 1.2ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wW54IulT64EYp6TCDh0Iyw_270.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wW6YkLnRZVrc5dipZ1bHgg_0.JPG: 480x640 (no detections), 276.6ms
Speed: 1.2ms preprocess, 276.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wW6YkLnRZVrc5dipZ1bHgg_90.JPG: 480x640 (no detections), 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wW6YkLnRZVrc5dipZ1bHgg_180.JPG: 480x640 (no detections), 299.7ms
Speed: 1.1ms preprocess, 299.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wW6YkLnRZVrc5dipZ1bHgg_270.JPG: 480x640 (no detections), 272.9ms
Speed: 1.2ms preprocess, 272.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWCTPk5_CdopyGbdHcs8Yg_0.JPG: 480x640 (no detections), 275.5ms
Speed: 1.0ms preprocess, 275.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWCTPk5_CdopyGbdHcs8Yg_90.JPG: 480x640 (no detections), 300.0ms
Speed: 1.1ms preprocess, 300.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWCTPk5_CdopyGbdHcs8Yg_180.JPG: 480x640 (no detections), 279.8ms
Speed: 1.1ms preprocess, 279.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWCTPk5_CdopyGbdHcs8Yg_270.JPG: 480x640 (no detections), 279.6ms
Speed: 1.1ms preprocess, 279.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWF7lKCCJh7_H1N76P0NzQ_0.JPG: 480x640 (no detections), 280.1ms
Speed: 1.1ms preprocess, 280.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWF7lKCCJh7_H1N76P0NzQ_90.JPG: 480x640 (no detections), 275.9ms
Speed: 1.2ms preprocess, 275.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWF7lKCCJh7_H1N76P0NzQ_180.JPG: 480x640 (no detections), 274.2ms
Speed: 1.1ms preprocess, 274.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWF7lKCCJh7_H1N76P0NzQ_270.JPG: 480x640 (no detections), 279.5ms
Speed: 1.1ms preprocess, 279.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWGQlk-IBzlEuYPbgNO5cg_0.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWGQlk-IBzlEuYPbgNO5cg_90.JPG: 480x640 (no detections), 276.0ms
Speed: 1.2ms preprocess, 276.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWGQlk-IBzlEuYPbgNO5cg_180.JPG: 480x640 (no detections), 274.5ms
Speed: 1.0ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWGQlk-IBzlEuYPbgNO5cg_270.JPG: 480x640 (no detections), 272.5ms
Speed: 1.4ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWGUDJZMkDLpZhcQbraTGQ_0.JPG: 480x640 (no detections), 277.3ms
Speed: 1.1ms preprocess, 277.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWGUDJZMkDLpZhcQbraTGQ_90.JPG: 480x640 (no detections), 271.6ms
Speed: 1.0ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWGUDJZMkDLpZhcQbraTGQ_180.JPG: 480x640 (no detections), 269.1ms
Speed: 1.1ms preprocess, 269.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWGUDJZMkDLpZhcQbraTGQ_270.JPG: 480x640 (no detections), 275.1ms
Speed: 1.0ms preprocess, 275.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWHrck--S8u0LGD8efIBQg_0.JPG: 480x640 (no detections), 267.8ms
Speed: 1.3ms preprocess, 267.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWHrck--S8u0LGD8efIBQg_90.JPG: 480x640 (no detections), 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWHrck--S8u0LGD8efIBQg_180.JPG: 480x640 (no detections), 276.1ms
Speed: 1.1ms preprocess, 276.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWHrck--S8u0LGD8efIBQg_270.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWJ13H-xxYskcevqHWxXIA_0.JPG: 480x640 (no detections), 281.6ms
Speed: 1.4ms preprocess, 281.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWJ13H-xxYskcevqHWxXIA_90.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWJ13H-xxYskcevqHWxXIA_180.JPG: 480x640 1 Waste, 276.2ms
Speed: 1.1ms preprocess, 276.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWJ13H-xxYskcevqHWxXIA_270.JPG: 480x640 (no detections), 274.6ms
Speed: 1.6ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWQg0v9Fog8tVYitGnJ29A_0.JPG: 480x640 (no detections), 267.9ms
Speed: 1.8ms preprocess, 267.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWQg0v9Fog8tVYitGnJ29A_90.JPG: 480x640 (no detections), 271.9ms
Speed: 1.0ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWQg0v9Fog8tVYitGnJ29A_180.JPG: 480x640 (no detections), 269.2ms
Speed: 1.1ms preprocess, 269.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWQg0v9Fog8tVYitGnJ29A_270.JPG: 480x640 (no detections), 279.7ms
Speed: 1.1ms preprocess, 279.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWSMS5UTZz3LWvFRRR1Wdg_0.JPG: 480x640 (no detections), 279.5ms
Speed: 1.0ms preprocess, 279.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWSMS5UTZz3LWvFRRR1Wdg_90.JPG: 480x640 (no detections), 275.3ms
Speed: 1.1ms preprocess, 275.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWSMS5UTZz3LWvFRRR1Wdg_180.JPG: 480x640 (no detections), 276.5ms
Speed: 1.1ms preprocess, 276.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWSMS5UTZz3LWvFRRR1Wdg_270.JPG: 480x640 (no detections), 276.3ms
Speed: 1.0ms preprocess, 276.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWU2JnWlOGKTk0SDBCnHmA_0.JPG: 480x640 (no detections), 274.8ms
Speed: 1.1ms preprocess, 274.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWU2JnWlOGKTk0SDBCnHmA_90.JPG: 480x640 (no detections), 272.3ms
Speed: 1.2ms preprocess, 272.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWU2JnWlOGKTk0SDBCnHmA_180.JPG: 480x640 (no detections), 273.4ms
Speed: 1.4ms preprocess, 273.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWU2JnWlOGKTk0SDBCnHmA_270.JPG: 480x640 (no detections), 275.0ms
Speed: 1.1ms preprocess, 275.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWV-3qBfmhprOGdWpTlTnw_0.JPG: 480x640 (no detections), 281.8ms
Speed: 1.3ms preprocess, 281.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWV-3qBfmhprOGdWpTlTnw_90.JPG: 480x640 (no detections), 275.0ms
Speed: 1.3ms preprocess, 275.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWV-3qBfmhprOGdWpTlTnw_180.JPG: 480x640 (no detections), 273.0ms
Speed: 1.0ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWV-3qBfmhprOGdWpTlTnw_270.JPG: 480x640 (no detections), 264.3ms
Speed: 1.1ms preprocess, 264.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWczlt1ImN2nbVO4IB1TSg_0.JPG: 480x640 (no detections), 268.3ms
Speed: 1.1ms preprocess, 268.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWczlt1ImN2nbVO4IB1TSg_90.JPG: 480x640 (no detections), 292.0ms

Speed: 1.1ms preprocess, 292.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWczlt1ImN2nbVO4IB1TSg_180.JPG: 480x640 (no detections), 304.1ms
Speed: 1.1ms preprocess, 304.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWczlt1ImN2nbVO4IB1TSg_270.JPG: 480x640 (no detections), 299.6ms
Speed: 1.4ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWeLALomWMPJ7FM8jV5udg_0.JPG: 480x640 (no detections), 289.1ms
Speed: 1.3ms preprocess, 289.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWeLALomWMPJ7FM8jV5udg_90.JPG: 480x640 (no detections), 283.5ms
Speed: 1.0ms preprocess, 283.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWeLALomWMPJ7FM8jV5udg_180.JPG: 480x640 (no detections), 276.0ms
Speed: 1.1ms preprocess, 276.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWeLALomWMPJ7FM8jV5udg_270.JPG: 480x640 (no detections), 281.4ms
Speed: 1.0ms preprocess, 281.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWfiLUypbBmXOLYryGwhkw_0.JPG: 480x640 (no detections), 272.1ms
Speed: 1.1ms preprocess, 272.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWfiLUypbBmXOLYryGwhkw_90.JPG: 480x640 (no detections), 270.6ms
Speed: 1.0ms preprocess, 270.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWfiLUypbBmXOLYryGwhkw_180.JPG: 480x640 (no detections), 278.8ms
Speed: 1.0ms preprocess, 278.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWfiLUypbBmXOLYryGwhkw_270.JPG: 480x640 (no detections), 276.1ms
Speed: 1.0ms preprocess, 276.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWhlQd5pgKnteu8KR43P0Q_0.JPG: 480x640 (no detections), 279.0ms
Speed: 1.2ms preprocess, 279.0ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWhlQd5pgKnteu8KR43P0Q_90.JPG: 480x640 (no detections), 281.6ms
Speed: 1.1ms preprocess, 281.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWhlQd5pgKnteu8KR43P0Q_180.JPG: 480x640 (no detections), 266.9ms
Speed: 1.3ms preprocess, 266.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWhlQd5pgKnteu8KR43P0Q_270.JPG: 480x640 (no detections), 270.9ms
Speed: 1.0ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWiIICDESgwkmj4UFZPnxg_0.JPG: 480x640 (no detections), 268.1ms
Speed: 1.0ms preprocess, 268.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWiIICDESgwkmj4UFZPnxg_90.JPG: 480x640 (no detections), 277.8ms
Speed: 1.1ms preprocess, 277.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWiIICDESgwkmj4UFZPnxg_180.JPG: 480x640 (no detections), 282.0ms
Speed: 1.3ms preprocess, 282.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWiIICDESgwkmj4UFZPnxg_270.JPG: 480x640 (no detections), 279.9ms
Speed: 1.1ms preprocess, 279.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWjdO6fHsa_eMx5YjFb5BA_0.JPG: 480x640 (no detections), 275.1ms
Speed: 1.2ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWjdO6fHsa_eMx5YjFb5BA_90.JPG: 480x640 (no detections), 279.2ms
Speed: 1.1ms preprocess, 279.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWjdO6fHsa_eMx5YjFb5BA_180.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWjdO6fHsa_eMx5YjFb5BA_270.JPG: 480x640 (no detections), 266.5ms
Speed: 1.0ms preprocess, 266.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWnl0QeJwLBUKX7bh6RfhQ_0.JPG: 480x640 (no detections), 275.3ms
Speed: 1.0ms preprocess, 275.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWnl0QeJwLBUKX7bh6RfhQ_90.JPG: 480x640 (no detections), 282.4ms
Speed: 1.1ms preprocess, 282.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWnl0QeJwLBUKX7bh6RfhQ_180.JPG: 480x640 (no detections), 277.7ms
Speed: 1.1ms preprocess, 277.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWnl0QeJwLBUKX7bh6RfhQ_270.JPG: 480x640 (no detections), 282.5ms
Speed: 1.1ms preprocess, 282.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWnyOd94Zx72RiQYt6_W9g_0.JPG: 480x640 (no detections), 274.8ms
Speed: 1.6ms preprocess, 274.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWnyOd94Zx72RiQYt6_W9g_90.JPG: 480x640 (no detections), 271.2ms
Speed: 1.2ms preprocess, 271.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWnyOd94Zx72RiQYt6_W9g_180.JPG: 480x640 (no detections), 269.4ms
Speed: 1.0ms preprocess, 269.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWnyOd94Zx72RiQYt6_W9g_270.JPG: 480x640 (no detections), 278.1ms
Speed: 1.1ms preprocess, 278.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWpLursSuUZb94-0dWPSAw_0.JPG: 480x640 (no detections), 279.1ms
Speed: 1.2ms preprocess, 279.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWpLursSuUZb94-0dWPSAw_90.JPG: 480x640 1 Waste, 276.1ms
Speed: 1.1ms preprocess, 276.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWpLursSuUZb94-0dWPSAw_180.JPG: 480x640 (no detections), 281.6ms
Speed: 1.1ms preprocess, 281.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWpLursSuUZb94-0dWPSAw_270.JPG: 480x640 (no detections), 270.8ms
Speed: 1.2ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWq5ofdIszR1zYxw0141oQ_0.JPG: 480x640 (no detections), 276.9ms
Speed: 1.1ms preprocess, 276.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWq5ofdIszR1zYxw0141oQ_90.JPG: 480x640 (no detections), 269.2ms
Speed: 1.0ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWq5ofdIszR1zYxw0141oQ_180.JPG: 480x640 (no detections), 270.5ms
Speed: 1.1ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWq5ofdIszR1zYxw0141oQ_270.JPG: 480x640 (no detections), 278.7ms
Speed: 1.1ms preprocess, 278.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWrCR6nRihOpO6Fftcfy8A_0.JPG: 480x640 (no detections), 282.0ms
Speed: 1.3ms preprocess, 282.0ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWrCR6nRihOpO6Fftcfy8A_90.JPG: 480x640 (no detections), 279.2ms
Speed: 1.3ms preprocess, 279.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWrCR6nRihOpO6Fftcfy8A_180.JPG: 480x640 (no detections), 275.7ms
Speed: 1.3ms preprocess, 275.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWrCR6nRihOpO6Fftcfy8A_270.JPG: 480x640 (no detections), 275.0ms
Speed: 1.1ms preprocess, 275.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWv2ABjdT1zBBKz0vnDuSw_0.JPG: 480x640 (no detections), 266.4ms
Speed: 1.1ms preprocess, 266.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWv2ABjdT1zBBKz0vnDuSw_90.JPG: 480x640 (no detections), 273.8ms
Speed: 1.7ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWv2ABjdT1zBBKz0vnDuSw_180.JPG: 480x640 (no detections), 278.6ms
Speed: 1.1ms preprocess, 278.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWv2ABjdT1zBBKz0vnDuSw_270.JPG: 480x640 (no detections), 276.7ms
Speed: 1.0ms preprocess, 276.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWw5AgsGYQrukxOVbRtfTg_0.JPG: 480x640 (no detections), 279.5ms
Speed: 1.0ms preprocess, 279.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWw5AgsGYQrukxOVbRtfTg_90.JPG: 480x640 (no detections), 275.8ms
Speed: 1.1ms preprocess, 275.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWw5AgsGYQrukxOVbRtfTg_180.JPG: 480x640 (no detections), 278.9ms
Speed: 1.7ms preprocess, 278.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWw5AgsGYQrukxOVbRtfTg_270.JPG: 480x640 (no detections), 268.4ms
Speed: 1.1ms preprocess, 268.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWwzKiThU_btI_APEwiR5A_0.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWwzKiThU_btI_APEwiR5A_90.JPG: 480x640 (no detections), 281.1ms
Speed: 1.1ms preprocess, 281.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWwzKiThU_btI_APEwiR5A_180.JPG: 480x640 (no detections), 283.9ms
Speed: 1.0ms preprocess, 283.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wWwzKiThU_btI_APEwiR5A_270.JPG: 480x640 (no detections), 285.2ms
Speed: 1.1ms preprocess, 285.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wX0sXaFblEZF2syyMCzw7A_0.JPG: 480x640 (no detections), 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wX0sXaFblEZF2syyMCzw7A_90.JPG: 480x640 (no detections), 266.9ms
Speed: 1.0ms preprocess, 266.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wX0sXaFblEZF2syyMCzw7A_180.JPG: 480x640 (no detections), 267.0ms
Speed: 1.2ms preprocess, 267.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wX0sXaFblEZF2syyMCzw7A_270.JPG: 480x640 (no detections), 267.7ms
Speed: 1.0ms preprocess, 267.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wX16mE65esxNVHpiwbPa2A_0.JPG: 480x640 (no detections), 277.4ms
Speed: 1.0ms preprocess, 277.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wX16mE65esxNVHpiwbPa2A_90.JPG: 480x640 (no detections), 318.8ms
Speed: 1.4ms preprocess, 318.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wX16mE65esxNVHpiwbPa2A_180.JPG: 480x640 (no detections), 280.6ms
Speed: 1.1ms preprocess, 280.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wX16mE65esxNVHpiwbPa2A_270.JPG: 480x640 1 Waste, 277.5ms
Speed: 1.2ms preprocess, 277.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wX1LeBKfbQvRycs_lAmLkw_0.JPG: 480x640 (no detections), 278.6ms
Speed: 1.2ms preprocess, 278.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wX1LeBKfbQvRycs_lAmLkw_90.JPG: 480x640 1 Waste, 274.4ms
Speed: 1.2ms preprocess, 274.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wX1LeBKfbQvRycs_lAmLkw_180.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wX1LeBKfbQvRycs_lAmLkw_270.JPG: 480x640 (no detections), 276.4ms
Speed: 1.0ms preprocess, 276.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wX1VKS0v7tvOEGrowJH5dg_0.JPG: 480x640 1 Waste, 282.0ms

Speed: 1.2ms preprocess, 282.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wX1VKS0v7tvOEGrowJH5dg_90.JPG: 480x640 (no detections), 277.3ms
Speed: 1.1ms preprocess, 277.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wX1VKS0v7tvOEGrowJH5dg_180.JPG: 480x640 1 Waste, 276.3ms
Speed: 1.4ms preprocess, 276.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wX1VKS0v7tvOEGrowJH5dg_270.JPG: 480x640 (no detections), 266.0ms
Speed: 1.1ms preprocess, 266.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wX3oUAGRuxRP-LFXE5fF6w_0.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wX3oUAGRuxRP-LFXE5fF6w_90.JPG: 480x640 (no detections), 274.5ms
Speed: 1.4ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wX3oUAGRuxRP-LFXE5fF6w_180.JPG: 480x640 (no detections), 280.3ms
Speed: 1.2ms preprocess, 280.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wX3oUAGRuxRP-LFXE5fF6w_270.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wX7P5tt4KviQasF4bF-d7w_0.JPG: 480x640 (no detections), 275.9ms
Speed: 1.1ms preprocess, 275.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wX7P5tt4KviQasF4bF-d7w_90.JPG: 480x640 (no detections), 273.5ms
Speed: 1.2ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wX7P5tt4KviQasF4bF-d7w_180.JPG: 480x640 (no detections), 279.6ms
Speed: 1.1ms preprocess, 279.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wX7P5tt4KviQasF4bF-d7w_270.JPG: 480x640 (no detections), 277.3ms
Speed: 1.2ms preprocess, 277.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXA6i-LHzfXZ7egnOiwpCA_0.JPG: 480x640 (no detections), 272.1ms
Speed: 1.1ms preprocess, 272.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXA6i-LHzfXZ7egnOiwpCA_90.JPG: 480x640 (no detections), 276.0ms
Speed: 1.0ms preprocess, 276.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXA6i-LHzfXZ7egnOiwpCA_180.JPG: 480x640 (no detections), 281.8ms
Speed: 1.1ms preprocess, 281.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXA6i-LHzfXZ7egnOiwpCA_270.JPG: 480x640 1 Waste, 278.7ms
Speed: 1.3ms preprocess, 278.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXBfYsH8qefixSyqxMxx6A_0.JPG: 480x640 (no detections), 278.5ms
Speed: 1.4ms preprocess, 278.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXBfYsH8qefixSyqxMxx6A_90.JPG: 480x640 (no detections), 273.2ms
Speed: 1.1ms preprocess, 273.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXBfYsH8qefixSyqxMxx6A_180.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXBfYsH8qefixSyqxMxx6A_270.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXL-YXMfuMW0EzsMAjgQYg_0.JPG: 480x640 (no detections), 274.1ms
Speed: 1.0ms preprocess, 274.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXL-YXMfuMW0EzsMAjgQYg_90.JPG: 480x640 (no detections), 280.5ms
Speed: 1.0ms preprocess, 280.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXL-YXMfuMW0EzsMAjgQYg_180.JPG: 480x640 (no detections), 280.4ms
Speed: 1.3ms preprocess, 280.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXL-YXMfuMW0EzsMAjgQYg_270.JPG: 480x640 (no detections), 281.6ms
Speed: 1.1ms preprocess, 281.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXMokzcVswhzb1OM-L-oKw_0.JPG: 480x640 (no detections), 271.8ms
Speed: 1.0ms preprocess, 271.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXMokzcVswhzb1OM-L-oKw_90.JPG: 480x640 (no detections), 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXMokzcVswhzb1OM-L-oKw_180.JPG: 480x640 (no detections), 270.7ms
Speed: 1.2ms preprocess, 270.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXMokzcVswhzb1OM-L-oKw_270.JPG: 480x640 (no detections), 274.8ms
Speed: 1.2ms preprocess, 274.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXN-BEIA0VK7r7JvdxaucA_0.JPG: 480x640 (no detections), 278.8ms
Speed: 1.1ms preprocess, 278.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXN-BEIA0VK7r7JvdxaucA_90.JPG: 480x640 (no detections), 283.5ms
Speed: 1.2ms preprocess, 283.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXN-BEIA0VK7r7JvdxaucA_180.JPG: 480x640 (no detections), 277.7ms
Speed: 1.1ms preprocess, 277.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXN-BEIA0VK7r7JvdxaucA_270.JPG: 480x640 (no detections), 275.1ms
Speed: 1.0ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXN1Rjao2QMw9sgAqcPuNA_0.JPG: 480x640 (no detections), 278.6ms
Speed: 1.1ms preprocess, 278.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXN1Rjao2QMw9sgAqcPuNA_90.JPG: 480x640 (no detections), 277.7ms
Speed: 1.1ms preprocess, 277.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXN1Rjao2QMw9sgAqcPuNA_180.JPG: 480x640 (no detections), 279.9ms
Speed: 1.2ms preprocess, 279.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXN1Rjao2QMw9sgAqcPuNA_270.JPG: 480x640 (no detections), 281.3ms
Speed: 1.1ms preprocess, 281.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXO4Lvz7WqhYfQ9vuJWFOA_0.JPG: 480x640 (no detections), 285.3ms
Speed: 1.2ms preprocess, 285.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXO4Lvz7WqhYfQ9vuJWFOA_90.JPG: 480x640 (no detections), 284.9ms
Speed: 1.1ms preprocess, 284.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXO4Lvz7WqhYfQ9vuJWFOA_180.JPG: 480x640 (no detections), 303.4ms
Speed: 1.0ms preprocess, 303.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXO4Lvz7WqhYfQ9vuJWFOA_270.JPG: 480x640 (no detections), 284.5ms
Speed: 1.1ms preprocess, 284.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXOL3Rzwr9WBs-x22mMDzg_0.JPG: 480x640 (no detections), 271.6ms
Speed: 1.2ms preprocess, 271.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXOL3Rzwr9WBs-x22mMDzg_90.JPG: 480x640 (no detections), 273.8ms
Speed: 1.3ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXOL3Rzwr9WBs-x22mMDzg_180.JPG: 480x640 (no detections), 276.2ms
Speed: 1.2ms preprocess, 276.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXOL3Rzwr9WBs-x22mMDzg_270.JPG: 480x640 (no detections), 273.7ms
Speed: 1.2ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXPynjv8zfZ393YZppe5Zg_0.JPG: 480x640 (no detections), 276.3ms
Speed: 1.1ms preprocess, 276.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXPynjv8zfZ393YZppe5Zg_90.JPG: 480x640 (no detections), 266.8ms
Speed: 1.0ms preprocess, 266.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXPynjv8zfZ393YZppe5Zg_180.JPG: 480x640 (no detections), 273.7ms
Speed: 1.2ms preprocess, 273.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXPynjv8zfZ393YZppe5Zg_270.JPG: 480x640 (no detections), 274.3ms
Speed: 1.2ms preprocess, 274.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXR2WtIjjCVB5_XJdZL5rQ_0.JPG: 480x640 (no detections), 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXR2WtIjjCVB5_XJdZL5rQ_90.JPG: 480x640 (no detections), 274.0ms
Speed: 1.1ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXR2WtIjjCVB5_XJdZL5rQ_180.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXR2WtIjjCVB5_XJdZL5rQ_270.JPG: 480x640 (no detections), 277.9ms
Speed: 1.1ms preprocess, 277.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXTHb9aontrlTrpa5kEaBg_0.JPG: 480x640 (no detections), 270.1ms
Speed: 1.2ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXTHb9aontrlTrpa5kEaBg_90.JPG: 480x640 (no detections), 277.1ms
Speed: 1.1ms preprocess, 277.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXTHb9aontrlTrpa5kEaBg_180.JPG: 480x640 (no detections), 270.9ms
Speed: 1.2ms preprocess, 270.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXTHb9aontrlTrpa5kEaBg_270.JPG: 480x640 (no detections), 273.2ms
Speed: 1.2ms preprocess, 273.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXUsncFO6HgyVw6YhhkFcQ_0.JPG: 480x640 (no detections), 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXUsncFO6HgyVw6YhhkFcQ_90.JPG: 480x640 (no detections), 278.9ms
Speed: 1.1ms preprocess, 278.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXUsncFO6HgyVw6YhhkFcQ_180.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXUsncFO6HgyVw6YhhkFcQ_270.JPG: 480x640 (no detections), 268.9ms
Speed: 1.2ms preprocess, 268.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXVGOTDKePWd4IFzosDl2Q_0.JPG: 480x640 (no detections), 268.3ms
Speed: 1.0ms preprocess, 268.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXVGOTDKePWd4IFzosDl2Q_90.JPG: 480x640 (no detections), 271.7ms
Speed: 1.4ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXVGOTDKePWd4IFzosDl2Q_180.JPG: 480x640 (no detections), 267.4ms
Speed: 1.1ms preprocess, 267.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXVGOTDKePWd4IFzosDl2Q_270.JPG: 480x640 (no detections), 274.0ms
Speed: 1.0ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXWUGgrPRTZ8sv6hy36dlA_0.JPG: 480x640 (no detections), 275.4ms
Speed: 1.1ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXWUGgrPRTZ8sv6hy36dlA_90.JPG: 480x640 (no detections), 283.8ms
Speed: 1.1ms preprocess, 283.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXWUGgrPRTZ8sv6hy36dlA_180.JPG: 480x640 (no detections), 277.3ms
Speed: 1.1ms preprocess, 277.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXWUGgrPRTZ8sv6hy36dlA_270.JPG: 480x640 (no detections), 302.1ms

Speed: 1.0ms preprocess, 302.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXXtdom6DbZDjS36xbU8uw_0.JPG: 480x640 (no detections), 272.5ms
Speed: 1.0ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXXtdom6DbZDjS36xbU8uw_90.JPG: 480x640 (no detections), 288.5ms
Speed: 1.3ms preprocess, 288.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXXtdom6DbZDjS36xbU8uw_180.JPG: 480x640 (no detections), 279.2ms
Speed: 1.0ms preprocess, 279.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXXtdom6DbZDjS36xbU8uw_270.JPG: 480x640 (no detections), 279.8ms
Speed: 1.2ms preprocess, 279.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXaOdjFnGxxmNkqy0ZKxVA_0.JPG: 480x640 (no detections), 277.4ms
Speed: 1.3ms preprocess, 277.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXaOdjFnGxxmNkqy0ZKxVA_90.JPG: 480x640 (no detections), 276.9ms
Speed: 1.2ms preprocess, 276.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXaOdjFnGxxmNkqy0ZKxVA_180.JPG: 480x640 (no detections), 268.1ms
Speed: 1.1ms preprocess, 268.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXaOdjFnGxxmNkqy0ZKxVA_270.JPG: 480x640 (no detections), 265.2ms
Speed: 1.6ms preprocess, 265.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXgxKWjCDs-9u_9PLUxY8w_0.JPG: 480x640 (no detections), 267.5ms
Speed: 1.3ms preprocess, 267.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXgxKWjCDs-9u_9PLUxY8w_90.JPG: 480x640 (no detections), 282.5ms
Speed: 1.2ms preprocess, 282.5ms inference, 6.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXgxKWjCDs-9u_9PLUxY8w_180.JPG: 480x640 (no detections), 284.6ms
Speed: 1.3ms preprocess, 284.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXgxKWjCDs-9u_9PLUxY8w_270.JPG: 480x640 (no detections), 280.0ms
Speed: 1.4ms preprocess, 280.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXiBXVnTTk6nShXPB60icg_0.JPG: 480x640 (no detections), 272.3ms
Speed: 1.2ms preprocess, 272.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXiBXVnTTk6nShXPB60icg_90.JPG: 480x640 (no detections), 266.1ms
Speed: 1.1ms preprocess, 266.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXiBXVnTTk6nShXPB60icg_180.JPG: 480x640 1 Waste, 284.6ms
Speed: 1.0ms preprocess, 284.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXiBXVnTTk6nShXPB60icg_270.JPG: 480x640 (no detections), 270.4ms
Speed: 1.0ms preprocess, 270.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXidJS8iL2ce5dyk35UbEw_0.JPG: 480x640 (no detections), 279.1ms
Speed: 1.1ms preprocess, 279.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXidJS8iL2ce5dyk35UbEw_90.JPG: 480x640 (no detections), 278.1ms
Speed: 1.2ms preprocess, 278.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXidJS8iL2ce5dyk35UbEw_180.JPG: 480x640 (no detections), 276.4ms
Speed: 1.1ms preprocess, 276.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXidJS8iL2ce5dyk35UbEw_270.JPG: 480x640 (no detections), 292.8ms
Speed: 1.1ms preprocess, 292.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXjCt69EiktPZoEtNOPb-w_0.JPG: 480x640 (no detections), 267.4ms
Speed: 1.1ms preprocess, 267.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXjCt69EiktPZoEtNOPb-w_90.JPG: 480x640 (no detections), 271.5ms
Speed: 1.0ms preprocess, 271.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXjCt69EiktPZoEtNOPb-w_180.JPG: 480x640 (no detections), 270.3ms
Speed: 1.1ms preprocess, 270.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXjCt69EiktPZoEtNOPb-w_270.JPG: 480x640 1 Waste, 272.7ms
Speed: 1.0ms preprocess, 272.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXlsWAUwdmveV6DaKgOwNQ_0.JPG: 480x640 (no detections), 276.8ms
Speed: 1.1ms preprocess, 276.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXlsWAUwdmveV6DaKgOwNQ_90.JPG: 480x640 (no detections), 275.2ms
Speed: 1.1ms preprocess, 275.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXlsWAUwdmveV6DaKgOwNQ_180.JPG: 480x640 (no detections), 278.2ms
Speed: 1.1ms preprocess, 278.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXlsWAUwdmveV6DaKgOwNQ_270.JPG: 480x640 (no detections), 272.6ms
Speed: 1.2ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXmV1JiuGet8l-huOzuDeA_0.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXmV1JiuGet8l-huOzuDeA_90.JPG: 480x640 (no detections), 268.2ms
Speed: 1.1ms preprocess, 268.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXmV1JiuGet8l-huOzuDeA_180.JPG: 480x640 (no detections), 276.1ms
Speed: 1.1ms preprocess, 276.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXmV1JiuGet8l-huOzuDeA_270.JPG: 480x640 (no detections), 296.1ms
Speed: 1.0ms preprocess, 296.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXnggYy-leHUHt5yUn6jXw_0.JPG: 480x640 (no detections), 278.6ms
Speed: 1.1ms preprocess, 278.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXnggYy-leHUHt5yUn6jXw_90.JPG: 480x640 1 Waste, 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXnggYy-leHUHt5yUn6jXw_180.JPG: 480x640 (no detections), 267.1ms
Speed: 1.1ms preprocess, 267.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXnggYy-leHUHt5yUn6jXw_270.JPG: 480x640 (no detections), 265.9ms
Speed: 1.0ms preprocess, 265.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXtE1xh2B_93uNfGgptN1Q_0.JPG: 480x640 (no detections), 267.5ms
Speed: 1.1ms preprocess, 267.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXtE1xh2B_93uNfGgptN1Q_90.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXtE1xh2B_93uNfGgptN1Q_180.JPG: 480x640 (no detections), 277.4ms
Speed: 1.4ms preprocess, 277.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXtE1xh2B_93uNfGgptN1Q_270.JPG: 480x640 (no detections), 282.7ms
Speed: 1.1ms preprocess, 282.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXx14xlPLvWwaKZ1ZtGu3A_0.JPG: 480x640 (no detections), 296.3ms
Speed: 1.1ms preprocess, 296.3ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXx14xlPLvWwaKZ1ZtGu3A_90.JPG: 480x640 (no detections), 273.2ms
Speed: 1.0ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXx14xlPLvWwaKZ1ZtGu3A_180.JPG: 480x640 (no detections), 277.2ms
Speed: 1.1ms preprocess, 277.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wXx14xlPLvWwaKZ1ZtGu3A_270.JPG: 480x640 (no detections), 270.9ms
Speed: 1.1ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wY28paqFm0-fza3WzRme-g_0.JPG: 480x640 (no detections), 272.3ms
Speed: 1.0ms preprocess, 272.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wY28paqFm0-fza3WzRme-g_90.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wY28paqFm0-fza3WzRme-g_180.JPG: 480x640 (no detections), 275.9ms
Speed: 1.5ms preprocess, 275.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wY28paqFm0-fza3WzRme-g_270.JPG: 480x640 (no detections), 275.9ms
Speed: 1.3ms preprocess, 275.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wY45XsuWb9U-Fffomtx02w_0.JPG: 480x640 (no detections), 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wY45XsuWb9U-Fffomtx02w_90.JPG: 480x640 (no detections), 269.0ms
Speed: 1.1ms preprocess, 269.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wY45XsuWb9U-Fffomtx02w_180.JPG: 480x640 (no detections), 289.2ms
Speed: 1.3ms preprocess, 289.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wY45XsuWb9U-Fffomtx02w_270.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wY6iDwLg0DhX4DPPovydDw_0.JPG: 480x640 (no detections), 278.1ms
Speed: 1.1ms preprocess, 278.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wY6iDwLg0DhX4DPPovydDw_90.JPG: 480x640 (no detections), 277.5ms
Speed: 1.1ms preprocess, 277.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wY6iDwLg0DhX4DPPovydDw_180.JPG: 480x640 (no detections), 276.8ms
Speed: 1.2ms preprocess, 276.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wY6iDwLg0DhX4DPPovydDw_270.JPG: 480x640 (no detections), 272.3ms
Speed: 1.2ms preprocess, 272.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wY79Odwd2pzoimKlyz2LYQ_0.JPG: 480x640 (no detections), 271.0ms
Speed: 1.0ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wY79Odwd2pzoimKlyz2LYQ_90.JPG: 480x640 (no detections), 276.4ms
Speed: 1.1ms preprocess, 276.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wY79Odwd2pzoimKlyz2LYQ_180.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wY79Odwd2pzoimKlyz2LYQ_270.JPG: 480x640 (no detections), 274.5ms
Speed: 1.0ms preprocess, 274.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wY8LFVQ1JLrU3z6OgfKqXw_0.JPG: 480x640 (no detections), 302.6ms
Speed: 1.0ms preprocess, 302.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wY8LFVQ1JLrU3z6OgfKqXw_90.JPG: 480x640 (no detections), 281.2ms
Speed: 1.1ms preprocess, 281.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wY8LFVQ1JLrU3z6OgfKqXw_180.JPG: 480x640 (no detections), 287.6ms
Speed: 1.2ms preprocess, 287.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wY8LFVQ1JLrU3z6OgfKqXw_270.JPG: 480x640 (no detections), 281.3ms
Speed: 1.0ms preprocess, 281.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wY9vA_I1XEALK-Gwm-yLPQ_0.JPG: 480x640 (no detections), 299.0ms
Speed: 1.2ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wY9vA_I1XEALK-Gwm-yLPQ_90.JPG: 480x640 (no detections), 282.5ms
Speed: 1.1ms preprocess, 282.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wY9vA_I1XEALK-Gwm-yLPQ_180.JPG: 480x640 (no detections), 291.4ms

Speed: 1.5ms preprocess, 291.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wY9vA_I1XEALK-Gwm-yLPQ_270.JPG: 480x640 (no detections), 299.5ms
Speed: 1.1ms preprocess, 299.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYAccpt1U_9D19UF1_1YuQ_0.JPG: 480x640 (no detections), 283.6ms
Speed: 1.0ms preprocess, 283.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYAccpt1U_9D19UF1_1YuQ_90.JPG: 480x640 (no detections), 276.0ms
Speed: 1.1ms preprocess, 276.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYAccpt1U_9D19UF1_1YuQ_180.JPG: 480x640 (no detections), 276.3ms
Speed: 1.2ms preprocess, 276.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYAccpt1U_9D19UF1_1YuQ_270.JPG: 480x640 (no detections), 275.5ms
Speed: 1.2ms preprocess, 275.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYB154UQlAWij3yH2UuTuw_0.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYB154UQlAWij3yH2UuTuw_90.JPG: 480x640 (no detections), 268.6ms
Speed: 1.1ms preprocess, 268.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYB154UQlAWij3yH2UuTuw_180.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYB154UQlAWij3yH2UuTuw_270.JPG: 480x640 (no detections), 276.1ms
Speed: 1.4ms preprocess, 276.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYCu2D4Q8nP_f81UJjk8ow_0.JPG: 480x640 (no detections), 274.8ms
Speed: 1.3ms preprocess, 274.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYCu2D4Q8nP_f81UJjk8ow_90.JPG: 480x640 (no detections), 277.5ms
Speed: 1.0ms preprocess, 277.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYCu2D4Q8nP_f81UJjk8ow_180.JPG: 480x640 (no detections), 301.1ms
Speed: 1.2ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYCu2D4Q8nP_f81UJjk8ow_270.JPG: 480x640 (no detections), 313.7ms
Speed: 1.7ms preprocess, 313.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYDUQIQfyqyNlAH4TDhAyA_0.JPG: 480x640 (no detections), 360.0ms
Speed: 1.2ms preprocess, 360.0ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYDUQIQfyqyNlAH4TDhAyA_90.JPG: 480x640 (no detections), 374.9ms
Speed: 1.1ms preprocess, 374.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYDUQIQfyqyNlAH4TDhAyA_180.JPG: 480x640 (no detections), 362.5ms
Speed: 1.3ms preprocess, 362.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYDUQIQfyqyNlAH4TDhAyA_270.JPG: 480x640 (no detections), 379.5ms
Speed: 1.2ms preprocess, 379.5ms inference, 5.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYGkH8rDrzJRCX_CZ5Jj3w_0.JPG: 480x640 (no detections), 311.1ms
Speed: 1.4ms preprocess, 311.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYGkH8rDrzJRCX_CZ5Jj3w_90.JPG: 480x640 (no detections), 309.3ms
Speed: 1.3ms preprocess, 309.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYGkH8rDrzJRCX_CZ5Jj3w_180.JPG: 480x640 (no detections), 320.1ms
Speed: 1.5ms preprocess, 320.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYGkH8rDrzJRCX_CZ5Jj3w_270.JPG: 480x640 (no detections), 312.6ms
Speed: 1.2ms preprocess, 312.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYJ6QwCspmuXWVkCu-crQQ_0.JPG: 480x640 (no detections), 326.1ms
Speed: 1.3ms preprocess, 326.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYJ6QwCspmuXWVkCu-crQQ_90.JPG: 480x640 (no detections), 307.2ms
Speed: 1.2ms preprocess, 307.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYJ6QwCspmuXWVkCu-crQQ_180.JPG: 480x640 4 Wastes, 309.0ms
Speed: 1.2ms preprocess, 309.0ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYJ6QwCspmuXWVkCu-crQQ_270.JPG: 480x640 (no detections), 294.6ms
Speed: 1.2ms preprocess, 294.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYKbO8LNCZqfX1rVsQikhA_0.JPG: 480x640 (no detections), 348.0ms
Speed: 1.4ms preprocess, 348.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYKbO8LNCZqfX1rVsQikhA_90.JPG: 480x640 1 Waste, 333.1ms
Speed: 1.9ms preprocess, 333.1ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYKbO8LNCZqfX1rVsQikhA_180.JPG: 480x640 (no detections), 310.0ms
Speed: 1.3ms preprocess, 310.0ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYKbO8LNCZqfX1rVsQikhA_270.JPG: 480x640 (no detections), 316.5ms
Speed: 1.2ms preprocess, 316.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYNDo6V7IFazRqbETMQdpw_0.JPG: 480x640 (no detections), 314.8ms
Speed: 1.2ms preprocess, 314.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYNDo6V7IFazRqbETMQdpw_90.JPG: 480x640 (no detections), 323.9ms
Speed: 1.3ms preprocess, 323.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYNDo6V7IFazRqbETMQdpw_180.JPG: 480x640 (no detections), 317.3ms
Speed: 1.3ms preprocess, 317.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYNDo6V7IFazRqbETMQdpw_270.JPG: 480x640 (no detections), 316.4ms
Speed: 1.2ms preprocess, 316.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYNfAtvg2GC4QxUeoTN0pQ_0.JPG: 480x640 (no detections), 301.5ms
Speed: 1.3ms preprocess, 301.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYNfAtvg2GC4QxUeoTN0pQ_90.JPG: 480x640 (no detections), 310.8ms
Speed: 1.1ms preprocess, 310.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYNfAtvg2GC4QxUeoTN0pQ_180.JPG: 480x640 (no detections), 306.1ms
Speed: 1.3ms preprocess, 306.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYNfAtvg2GC4QxUeoTN0pQ_270.JPG: 480x640 (no detections), 303.2ms
Speed: 1.1ms preprocess, 303.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYPWFlQfPuCcqKY7Pp0dLw_0.JPG: 480x640 (no detections), 305.2ms
Speed: 1.3ms preprocess, 305.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYPWFlQfPuCcqKY7Pp0dLw_90.JPG: 480x640 (no detections), 302.1ms
Speed: 1.1ms preprocess, 302.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYPWFlQfPuCcqKY7Pp0dLw_180.JPG: 480x640 (no detections), 305.5ms
Speed: 1.1ms preprocess, 305.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYPWFlQfPuCcqKY7Pp0dLw_270.JPG: 480x640 (no detections), 372.8ms
Speed: 1.2ms preprocess, 372.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYVlK3sNKX_tcCdA2LQAuA_0.JPG: 480x640 1 Waste, 338.3ms
Speed: 1.1ms preprocess, 338.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYVlK3sNKX_tcCdA2LQAuA_90.JPG: 480x640 (no detections), 329.1ms
Speed: 1.2ms preprocess, 329.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYVlK3sNKX_tcCdA2LQAuA_180.JPG: 480x640 (no detections), 363.1ms
Speed: 2.0ms preprocess, 363.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYVlK3sNKX_tcCdA2LQAuA_270.JPG: 480x640 (no detections), 350.5ms
Speed: 1.3ms preprocess, 350.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYWZjzlb_H2qj1EZ8qZi6g_0.JPG: 480x640 (no detections), 309.0ms
Speed: 1.2ms preprocess, 309.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYWZjzlb_H2qj1EZ8qZi6g_90.JPG: 480x640 (no detections), 295.3ms
Speed: 1.4ms preprocess, 295.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYWZjzlb_H2qj1EZ8qZi6g_180.JPG: 480x640 (no detections), 278.6ms
Speed: 1.0ms preprocess, 278.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYWZjzlb_H2qj1EZ8qZi6g_270.JPG: 480x640 (no detections), 338.4ms
Speed: 1.2ms preprocess, 338.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYZmPMdwfpNFStoEbPEAiA_0.JPG: 480x640 (no detections), 330.6ms
Speed: 1.3ms preprocess, 330.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYZmPMdwfpNFStoEbPEAiA_90.JPG: 480x640 (no detections), 375.5ms
Speed: 1.1ms preprocess, 375.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYZmPMdwfpNFStoEbPEAiA_180.JPG: 480x640 (no detections), 300.2ms
Speed: 1.2ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYZmPMdwfpNFStoEbPEAiA_270.JPG: 480x640 (no detections), 270.4ms
Speed: 1.2ms preprocess, 270.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYaW2tnwt44s9uAjLRa0xg_0.JPG: 480x640 (no detections), 286.6ms
Speed: 1.2ms preprocess, 286.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYaW2tnwt44s9uAjLRa0xg_90.JPG: 480x640 (no detections), 314.7ms
Speed: 1.0ms preprocess, 314.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYaW2tnwt44s9uAjLRa0xg_180.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYaW2tnwt44s9uAjLRa0xg_270.JPG: 480x640 (no detections), 289.8ms
Speed: 1.1ms preprocess, 289.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYackLFBeR1JSDUL0Zcp0w_0.JPG: 480x640 (no detections), 297.1ms
Speed: 1.2ms preprocess, 297.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYackLFBeR1JSDUL0Zcp0w_90.JPG: 480x640 (no detections), 279.1ms
Speed: 1.1ms preprocess, 279.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYackLFBeR1JSDUL0Zcp0w_180.JPG: 480x640 (no detections), 278.0ms
Speed: 1.1ms preprocess, 278.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYackLFBeR1JSDUL0Zcp0w_270.JPG: 480x640 (no detections), 298.5ms
Speed: 1.3ms preprocess, 298.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYc5kqWiueWTemJbp8s1rQ_0.JPG: 480x640 (no detections), 287.3ms
Speed: 1.1ms preprocess, 287.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYc5kqWiueWTemJbp8s1rQ_90.JPG: 480x640 (no detections), 292.7ms
Speed: 1.0ms preprocess, 292.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYc5kqWiueWTemJbp8s1rQ_180.JPG: 480x640 (no detections), 290.2ms
Speed: 1.1ms preprocess, 290.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYc5kqWiueWTemJbp8s1rQ_270.JPG: 480x640 (no detections), 279.2ms
Speed: 1.1ms preprocess, 279.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYdWzp0eanWkybj6pmqktg_0.JPG: 480x640 (no detections), 278.1ms
Speed: 1.1ms preprocess, 278.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYdWzp0eanWkybj6pmqktg_90.JPG: 480x640 (no detections), 282.8ms

Speed: 1.1ms preprocess, 282.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYdWzp0eanWkybj6pmqktg_180.JPG: 480x640 (no detections), 291.3ms
Speed: 1.3ms preprocess, 291.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYdWzp0eanWkybj6pmqktg_270.JPG: 480x640 (no detections), 308.2ms
Speed: 1.1ms preprocess, 308.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYfpn-DQ8hnQyWLGrqKw_g_0.JPG: 480x640 (no detections), 288.8ms
Speed: 1.1ms preprocess, 288.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYfpn-DQ8hnQyWLGrqKw_g_90.JPG: 480x640 (no detections), 292.5ms
Speed: 1.1ms preprocess, 292.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYfpn-DQ8hnQyWLGrqKw_g_180.JPG: 480x640 (no detections), 294.2ms
Speed: 1.1ms preprocess, 294.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYfpn-DQ8hnQyWLGrqKw_g_270.JPG: 480x640 (no detections), 309.6ms
Speed: 1.1ms preprocess, 309.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYguh2NA5Ah0vBdZ8VWkgg_0.JPG: 480x640 (no detections), 320.0ms
Speed: 1.2ms preprocess, 320.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYguh2NA5Ah0vBdZ8VWkgg_90.JPG: 480x640 (no detections), 323.4ms
Speed: 1.4ms preprocess, 323.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYguh2NA5Ah0vBdZ8VWkgg_180.JPG: 480x640 (no detections), 317.4ms
Speed: 1.3ms preprocess, 317.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYguh2NA5Ah0vBdZ8VWkgg_270.JPG: 480x640 (no detections), 307.6ms
Speed: 1.3ms preprocess, 307.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYkaZpWP_2CwvDk9-KJJ3w_0.JPG: 480x640 (no detections), 308.1ms
Speed: 1.2ms preprocess, 308.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYkaZpWP_2CwvDk9-KJJ3w_90.JPG: 480x640 (no detections), 308.8ms
Speed: 1.5ms preprocess, 308.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYkaZpWP_2CwvDk9-KJJ3w_180.JPG: 480x640 (no detections), 319.2ms
Speed: 1.7ms preprocess, 319.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYkaZpWP_2CwvDk9-KJJ3w_270.JPG: 480x640 (no detections), 291.9ms
Speed: 1.2ms preprocess, 291.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYl2XeWHbj3lm4iufhJU-Q_0.JPG: 480x640 (no detections), 277.7ms
Speed: 1.1ms preprocess, 277.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYl2XeWHbj3lm4iufhJU-Q_90.JPG: 480x640 (no detections), 277.3ms
Speed: 1.0ms preprocess, 277.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYl2XeWHbj3lm4iufhJU-Q_180.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYl2XeWHbj3lm4iufhJU-Q_270.JPG: 480x640 (no detections), 268.4ms
Speed: 1.4ms preprocess, 268.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYnO1zCytfIgxJZ3siSybA_0.JPG: 480x640 (no detections), 266.8ms
Speed: 1.1ms preprocess, 266.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYnO1zCytfIgxJZ3siSybA_90.JPG: 480x640 (no detections), 293.4ms
Speed: 1.0ms preprocess, 293.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYnO1zCytfIgxJZ3siSybA_180.JPG: 480x640 (no detections), 267.0ms
Speed: 1.1ms preprocess, 267.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYnO1zCytfIgxJZ3siSybA_270.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYnpufh3t7FNdwI4UUEnWg_0.JPG: 480x640 (no detections), 278.6ms
Speed: 1.1ms preprocess, 278.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYnpufh3t7FNdwI4UUEnWg_90.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYnpufh3t7FNdwI4UUEnWg_180.JPG: 480x640 (no detections), 268.3ms
Speed: 1.0ms preprocess, 268.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYnpufh3t7FNdwI4UUEnWg_270.JPG: 480x640 (no detections), 268.6ms
Speed: 1.1ms preprocess, 268.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYp55aIKtyO4H7XPsV7BFw_0.JPG: 480x640 (no detections), 268.1ms
Speed: 1.1ms preprocess, 268.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYp55aIKtyO4H7XPsV7BFw_90.JPG: 480x640 (no detections), 269.4ms
Speed: 1.0ms preprocess, 269.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYp55aIKtyO4H7XPsV7BFw_180.JPG: 480x640 (no detections), 272.8ms
Speed: 1.2ms preprocess, 272.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYp55aIKtyO4H7XPsV7BFw_270.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYqO8fXTU5TGaVPoo2xObA_0.JPG: 480x640 (no detections), 267.5ms
Speed: 1.0ms preprocess, 267.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYqO8fXTU5TGaVPoo2xObA_90.JPG: 480x640 (no detections), 267.2ms
Speed: 1.0ms preprocess, 267.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYqO8fXTU5TGaVPoo2xObA_180.JPG: 480x640 (no detections), 265.0ms
Speed: 1.1ms preprocess, 265.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYqO8fXTU5TGaVPoo2xObA_270.JPG: 480x640 (no detections), 267.8ms
Speed: 1.0ms preprocess, 267.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYrxxMjN3i1DuKYqe9MmmA_0.JPG: 480x640 (no detections), 266.8ms
Speed: 1.0ms preprocess, 266.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYrxxMjN3i1DuKYqe9MmmA_90.JPG: 480x640 (no detections), 267.4ms
Speed: 1.0ms preprocess, 267.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYrxxMjN3i1DuKYqe9MmmA_180.JPG: 480x640 (no detections), 265.9ms
Speed: 1.1ms preprocess, 265.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYrxxMjN3i1DuKYqe9MmmA_270.JPG: 480x640 (no detections), 286.8ms
Speed: 1.1ms preprocess, 286.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYsjvZPEGaNKRms81BQAHg_0.JPG: 480x640 (no detections), 310.2ms
Speed: 1.1ms preprocess, 310.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYsjvZPEGaNKRms81BQAHg_90.JPG: 480x640 (no detections), 312.9ms
Speed: 1.3ms preprocess, 312.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYsjvZPEGaNKRms81BQAHg_180.JPG: 480x640 (no detections), 310.9ms
Speed: 1.2ms preprocess, 310.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYsjvZPEGaNKRms81BQAHg_270.JPG: 480x640 (no detections), 309.6ms
Speed: 1.2ms preprocess, 309.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYuZQqsv99NzJsMuViILNA_0.JPG: 480x640 (no detections), 311.0ms
Speed: 1.1ms preprocess, 311.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYuZQqsv99NzJsMuViILNA_90.JPG: 480x640 (no detections), 326.9ms
Speed: 1.2ms preprocess, 326.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYuZQqsv99NzJsMuViILNA_180.JPG: 480x640 (no detections), 306.7ms
Speed: 1.1ms preprocess, 306.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wYuZQqsv99NzJsMuViILNA_270.JPG: 480x640 (no detections), 310.8ms
Speed: 1.2ms preprocess, 310.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZ14x2pnhiKXY-blsnDygQ_0.JPG: 480x640 (no detections), 301.9ms
Speed: 1.1ms preprocess, 301.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZ14x2pnhiKXY-blsnDygQ_90.JPG: 480x640 (no detections), 305.9ms
Speed: 6.2ms preprocess, 305.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZ14x2pnhiKXY-blsnDygQ_180.JPG: 480x640 (no detections), 304.2ms
Speed: 1.7ms preprocess, 304.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZ14x2pnhiKXY-blsnDygQ_270.JPG: 480x640 (no detections), 302.4ms
Speed: 1.2ms preprocess, 302.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZ33wA6VrQ69pFlJxYTFHQ_0.JPG: 480x640 (no detections), 305.4ms
Speed: 1.2ms preprocess, 305.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZ33wA6VrQ69pFlJxYTFHQ_90.JPG: 480x640 (no detections), 305.9ms
Speed: 1.1ms preprocess, 305.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZ33wA6VrQ69pFlJxYTFHQ_180.JPG: 480x640 (no detections), 295.8ms
Speed: 1.1ms preprocess, 295.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZ33wA6VrQ69pFlJxYTFHQ_270.JPG: 480x640 (no detections), 303.2ms
Speed: 1.1ms preprocess, 303.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZ5KsaUv7_Vv2Xtug7TIqA_0.JPG: 480x640 (no detections), 298.4ms
Speed: 1.3ms preprocess, 298.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZ5KsaUv7_Vv2Xtug7TIqA_90.JPG: 480x640 (no detections), 314.2ms
Speed: 1.1ms preprocess, 314.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZ5KsaUv7_Vv2Xtug7TIqA_180.JPG: 480x640 (no detections), 305.2ms
Speed: 1.4ms preprocess, 305.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZ5KsaUv7_Vv2Xtug7TIqA_270.JPG: 480x640 (no detections), 301.0ms
Speed: 1.2ms preprocess, 301.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZ8bzPM4noutejpk7rDPgA_0.JPG: 480x640 (no detections), 299.3ms
Speed: 1.2ms preprocess, 299.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZ8bzPM4noutejpk7rDPgA_90.JPG: 480x640 (no detections), 302.9ms
Speed: 1.1ms preprocess, 302.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZ8bzPM4noutejpk7rDPgA_180.JPG: 480x640 (no detections), 300.4ms
Speed: 1.1ms preprocess, 300.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZ8bzPM4noutejpk7rDPgA_270.JPG: 480x640 (no detections), 300.4ms
Speed: 1.1ms preprocess, 300.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZ9StxagYYi2gmw1nH-50A_0.JPG: 480x640 (no detections), 305.6ms
Speed: 1.0ms preprocess, 305.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZ9StxagYYi2gmw1nH-50A_90.JPG: 480x640 (no detections), 302.8ms
Speed: 1.3ms preprocess, 302.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZ9StxagYYi2gmw1nH-50A_180.JPG: 480x640 (no detections), 301.8ms
Speed: 1.3ms preprocess, 301.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZ9StxagYYi2gmw1nH-50A_270.JPG: 480x640 (no detections), 296.5ms
Speed: 1.1ms preprocess, 296.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZEK_HKqb9uHMc8ZJs1bBg_0.JPG: 480x640 (no detections), 307.5ms

Speed: 1.3ms preprocess, 307.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZEK_HKqb9uHMc8ZJs1bBg_90.JPG: 480x640 (no detections), 299.3ms
Speed: 1.1ms preprocess, 299.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZEK_HKqb9uHMc8ZJs1bBg_180.JPG: 480x640 1 Waste, 311.1ms
Speed: 1.2ms preprocess, 311.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZEK_HKqb9uHMc8ZJs1bBg_270.JPG: 480x640 1 Waste, 304.1ms
Speed: 1.2ms preprocess, 304.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZI6kCZbYtFbl0z1KptBDQ_0.JPG: 480x640 (no detections), 306.3ms
Speed: 1.4ms preprocess, 306.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZI6kCZbYtFbl0z1KptBDQ_90.JPG: 480x640 (no detections), 299.8ms
Speed: 1.1ms preprocess, 299.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZI6kCZbYtFbl0z1KptBDQ_180.JPG: 480x640 (no detections), 304.4ms
Speed: 1.2ms preprocess, 304.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZI6kCZbYtFbl0z1KptBDQ_270.JPG: 480x640 (no detections), 303.7ms
Speed: 1.1ms preprocess, 303.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZK8UZYakKv3Kt2VJuY16Q_0.JPG: 480x640 (no detections), 306.8ms
Speed: 1.3ms preprocess, 306.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZK8UZYakKv3Kt2VJuY16Q_90.JPG: 480x640 (no detections), 314.2ms
Speed: 1.1ms preprocess, 314.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZK8UZYakKv3Kt2VJuY16Q_180.JPG: 480x640 (no detections), 309.6ms
Speed: 1.1ms preprocess, 309.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZK8UZYakKv3Kt2VJuY16Q_270.JPG: 480x640 (no detections), 312.7ms
Speed: 1.5ms preprocess, 312.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZL6WXJC4NarNwKL_sWq5w_0.JPG: 480x640 (no detections), 309.4ms
Speed: 1.2ms preprocess, 309.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZL6WXJC4NarNwKL_sWq5w_90.JPG: 480x640 (no detections), 316.5ms
Speed: 1.5ms preprocess, 316.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZL6WXJC4NarNwKL_sWq5w_180.JPG: 480x640 (no detections), 308.4ms
Speed: 1.1ms preprocess, 308.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZL6WXJC4NarNwKL_sWq5w_270.JPG: 480x640 (no detections), 316.7ms
Speed: 1.0ms preprocess, 316.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZNEUV581eiLJuf8xydXwg_0.JPG: 480x640 (no detections), 299.5ms
Speed: 1.3ms preprocess, 299.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZNEUV581eiLJuf8xydXwg_90.JPG: 480x640 (no detections), 304.7ms
Speed: 1.1ms preprocess, 304.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZNEUV581eiLJuf8xydXwg_180.JPG: 480x640 (no detections), 299.6ms
Speed: 1.0ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZNEUV581eiLJuf8xydXwg_270.JPG: 480x640 (no detections), 301.1ms
Speed: 1.2ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZNi8DSjlQ4noRvsutOeMw_0.JPG: 480x640 (no detections), 301.7ms
Speed: 1.6ms preprocess, 301.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZNi8DSjlQ4noRvsutOeMw_90.JPG: 480x640 (no detections), 302.4ms
Speed: 1.1ms preprocess, 302.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZNi8DSjlQ4noRvsutOeMw_180.JPG: 480x640 (no detections), 299.5ms
Speed: 1.2ms preprocess, 299.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZNi8DSjlQ4noRvsutOeMw_270.JPG: 480x640 (no detections), 301.8ms
Speed: 1.2ms preprocess, 301.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZO8k2CKfas_kP9Kc-zNuA_0.JPG: 480x640 (no detections), 297.9ms
Speed: 1.1ms preprocess, 297.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZO8k2CKfas_kP9Kc-zNuA_90.JPG: 480x640 (no detections), 307.6ms
Speed: 1.8ms preprocess, 307.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZO8k2CKfas_kP9Kc-zNuA_180.JPG: 480x640 (no detections), 303.8ms
Speed: 1.1ms preprocess, 303.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZO8k2CKfas_kP9Kc-zNuA_270.JPG: 480x640 (no detections), 301.9ms
Speed: 1.2ms preprocess, 301.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZPricqyYeXvb08sFbAtrg_0.JPG: 480x640 (no detections), 313.5ms
Speed: 1.2ms preprocess, 313.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZPricqyYeXvb08sFbAtrg_90.JPG: 480x640 (no detections), 298.9ms
Speed: 1.1ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZPricqyYeXvb08sFbAtrg_180.JPG: 480x640 (no detections), 300.3ms
Speed: 1.1ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZPricqyYeXvb08sFbAtrg_270.JPG: 480x640 (no detections), 301.4ms
Speed: 1.0ms preprocess, 301.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZXQCdENdADNJxbKWrzF-w_0.JPG: 480x640 (no detections), 301.5ms
Speed: 1.1ms preprocess, 301.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZXQCdENdADNJxbKWrzF-w_90.JPG: 480x640 (no detections), 306.9ms
Speed: 1.2ms preprocess, 306.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZXQCdENdADNJxbKWrzF-w_180.JPG: 480x640 (no detections), 300.2ms
Speed: 1.1ms preprocess, 300.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZXQCdENdADNJxbKWrzF-w_270.JPG: 480x640 (no detections), 305.0ms
Speed: 1.1ms preprocess, 305.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZY7HUVa2N46UL0XV7IlXw_0.JPG: 480x640 (no detections), 304.7ms
Speed: 1.3ms preprocess, 304.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZY7HUVa2N46UL0XV7IlXw_90.JPG: 480x640 (no detections), 311.7ms
Speed: 1.3ms preprocess, 311.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZY7HUVa2N46UL0XV7IlXw_180.JPG: 480x640 (no detections), 306.8ms
Speed: 1.1ms preprocess, 306.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZY7HUVa2N46UL0XV7IlXw_270.JPG: 480x640 (no detections), 299.3ms
Speed: 1.1ms preprocess, 299.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZZ64RCSNNEjhgEGIZQFqA_0.JPG: 480x640 (no detections), 303.8ms
Speed: 1.1ms preprocess, 303.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZZ64RCSNNEjhgEGIZQFqA_90.JPG: 480x640 (no detections), 307.3ms
Speed: 1.2ms preprocess, 307.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZZ64RCSNNEjhgEGIZQFqA_180.JPG: 480x640 (no detections), 309.4ms
Speed: 1.0ms preprocess, 309.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZZ64RCSNNEjhgEGIZQFqA_270.JPG: 480x640 (no detections), 316.5ms
Speed: 1.2ms preprocess, 316.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZ_wj-9SiXx0yjwe5i_8aw_0.JPG: 480x640 (no detections), 314.7ms
Speed: 1.1ms preprocess, 314.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZ_wj-9SiXx0yjwe5i_8aw_90.JPG: 480x640 (no detections), 325.8ms
Speed: 1.1ms preprocess, 325.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZ_wj-9SiXx0yjwe5i_8aw_180.JPG: 480x640 (no detections), 307.9ms
Speed: 1.2ms preprocess, 307.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZ_wj-9SiXx0yjwe5i_8aw_270.JPG: 480x640 (no detections), 315.8ms
Speed: 1.2ms preprocess, 315.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZb8XdZGqLix_7P5VLtB1g_0.JPG: 480x640 (no detections), 299.1ms
Speed: 1.1ms preprocess, 299.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZb8XdZGqLix_7P5VLtB1g_90.JPG: 480x640 (no detections), 297.5ms
Speed: 1.1ms preprocess, 297.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZb8XdZGqLix_7P5VLtB1g_180.JPG: 480x640 (no detections), 301.9ms
Speed: 1.2ms preprocess, 301.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZb8XdZGqLix_7P5VLtB1g_270.JPG: 480x640 (no detections), 314.7ms
Speed: 1.1ms preprocess, 314.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZcShlKdrFbcqqmkvNa3TQ_0.JPG: 480x640 (no detections), 316.5ms
Speed: 1.3ms preprocess, 316.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZcShlKdrFbcqqmkvNa3TQ_90.JPG: 480x640 (no detections), 317.7ms
Speed: 1.2ms preprocess, 317.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZcShlKdrFbcqqmkvNa3TQ_180.JPG: 480x640 (no detections), 317.0ms
Speed: 1.1ms preprocess, 317.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZcShlKdrFbcqqmkvNa3TQ_270.JPG: 480x640 (no detections), 312.7ms
Speed: 1.2ms preprocess, 312.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZdLv8PMLvEKnuJI8q-ozQ_0.JPG: 480x640 (no detections), 315.0ms
Speed: 1.3ms preprocess, 315.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZdLv8PMLvEKnuJI8q-ozQ_90.JPG: 480x640 (no detections), 306.4ms
Speed: 1.1ms preprocess, 306.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZdLv8PMLvEKnuJI8q-ozQ_180.JPG: 480x640 (no detections), 307.7ms
Speed: 1.3ms preprocess, 307.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZdLv8PMLvEKnuJI8q-ozQ_270.JPG: 480x640 (no detections), 300.1ms
Speed: 1.1ms preprocess, 300.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZdMGwYaitveLXn-KEZDCA_0.JPG: 480x640 (no detections), 304.3ms
Speed: 1.1ms preprocess, 304.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZdMGwYaitveLXn-KEZDCA_90.JPG: 480x640 (no detections), 315.4ms
Speed: 1.0ms preprocess, 315.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZdMGwYaitveLXn-KEZDCA_180.JPG: 480x640 (no detections), 316.5ms
Speed: 1.2ms preprocess, 316.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZdMGwYaitveLXn-KEZDCA_270.JPG: 480x640 (no detections), 302.3ms
Speed: 1.2ms preprocess, 302.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZdZFmR1zabwSUfsxEOHNQ_0.JPG: 480x640 (no detections), 304.2ms
Speed: 1.0ms preprocess, 304.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZdZFmR1zabwSUfsxEOHNQ_90.JPG: 480x640 (no detections), 303.6ms
Speed: 1.2ms preprocess, 303.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZdZFmR1zabwSUfsxEOHNQ_180.JPG: 480x640 (no detections), 300.8ms
Speed: 1.1ms preprocess, 300.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZdZFmR1zabwSUfsxEOHNQ_270.JPG: 480x640 1 Waste, 311.7ms

Speed: 1.1ms preprocess, 311.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZf0U5EkYQJo12_efaUYQQ_0.JPG: 480x640 (no detections), 300.3ms
Speed: 1.2ms preprocess, 300.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZf0U5EkYQJo12_efaUYQQ_90.JPG: 480x640 (no detections), 299.9ms
Speed: 1.2ms preprocess, 299.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZf0U5EkYQJo12_efaUYQQ_180.JPG: 480x640 (no detections), 321.5ms
Speed: 1.2ms preprocess, 321.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZf0U5EkYQJo12_efaUYQQ_270.JPG: 480x640 (no detections), 316.5ms
Speed: 1.1ms preprocess, 316.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZgayT_H_GyjSaR2cit8IA_0.JPG: 480x640 (no detections), 308.1ms
Speed: 1.3ms preprocess, 308.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZgayT_H_GyjSaR2cit8IA_90.JPG: 480x640 (no detections), 332.1ms
Speed: 1.3ms preprocess, 332.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZgayT_H_GyjSaR2cit8IA_180.JPG: 480x640 (no detections), 327.3ms
Speed: 1.2ms preprocess, 327.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZgayT_H_GyjSaR2cit8IA_270.JPG: 480x640 (no detections), 318.3ms
Speed: 1.2ms preprocess, 318.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZieNIkLLzy91QRIWf0tgg_0.JPG: 480x640 (no detections), 304.7ms
Speed: 1.1ms preprocess, 304.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZieNIkLLzy91QRIWf0tgg_90.JPG: 480x640 (no detections), 309.5ms
Speed: 1.3ms preprocess, 309.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZieNIkLLzy91QRIWf0tgg_180.JPG: 480x640 (no detections), 346.8ms
Speed: 1.9ms preprocess, 346.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZieNIkLLzy91QRIWf0tgg_270.JPG: 480x640 (no detections), 335.6ms
Speed: 1.4ms preprocess, 335.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZjMlvhUsnS0VmE4Y2FL_w_0.JPG: 480x640 (no detections), 315.6ms
Speed: 1.5ms preprocess, 315.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZjMlvhUsnS0VmE4Y2FL_w_90.JPG: 480x640 (no detections), 305.1ms
Speed: 1.4ms preprocess, 305.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZjMlvhUsnS0VmE4Y2FL_w_180.JPG: 480x640 (no detections), 317.7ms
Speed: 1.5ms preprocess, 317.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZjMlvhUsnS0VmE4Y2FL_w_270.JPG: 480x640 (no detections), 344.1ms
Speed: 1.4ms preprocess, 344.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZovZKgwgt07C-etlcMy0w_0.JPG: 480x640 (no detections), 417.9ms
Speed: 1.3ms preprocess, 417.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZovZKgwgt07C-etlcMy0w_90.JPG: 480x640 (no detections), 398.9ms
Speed: 1.6ms preprocess, 398.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZovZKgwgt07C-etlcMy0w_180.JPG: 480x640 (no detections), 328.7ms
Speed: 1.4ms preprocess, 328.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZovZKgwgt07C-etlcMy0w_270.JPG: 480x640 (no detections), 308.8ms
Speed: 1.1ms preprocess, 308.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZspVzi9z5FhhE_VQyBcbw_0.JPG: 480x640 (no detections), 298.3ms
Speed: 1.2ms preprocess, 298.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZspVzi9z5FhhE_VQyBcbw_90.JPG: 480x640 (no detections), 302.6ms
Speed: 1.0ms preprocess, 302.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZspVzi9z5FhhE_VQyBcbw_180.JPG: 480x640 (no detections), 300.2ms
Speed: 1.2ms preprocess, 300.2ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wZspVzi9z5FhhE_VQyBcbw_270.JPG: 480x640 (no detections), 311.8ms
Speed: 1.1ms preprocess, 311.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_2wZgNcnrUGSWt0biEj9g_0.JPG: 480x640 (no detections), 310.8ms
Speed: 1.1ms preprocess, 310.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_2wZgNcnrUGSWt0biEj9g_90.JPG: 480x640 (no detections), 302.3ms
Speed: 1.1ms preprocess, 302.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_2wZgNcnrUGSWt0biEj9g_180.JPG: 480x640 (no detections), 304.7ms
Speed: 1.1ms preprocess, 304.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_2wZgNcnrUGSWt0biEj9g_270.JPG: 480x640 (no detections), 302.8ms
Speed: 1.1ms preprocess, 302.8ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_3NdB85M64wDEkD2eLPSw_0.JPG: 480x640 (no detections), 313.4ms
Speed: 1.1ms preprocess, 313.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_3NdB85M64wDEkD2eLPSw_90.JPG: 480x640 (no detections), 306.6ms
Speed: 1.2ms preprocess, 306.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_3NdB85M64wDEkD2eLPSw_180.JPG: 480x640 (no detections), 310.6ms
Speed: 1.1ms preprocess, 310.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_3NdB85M64wDEkD2eLPSw_270.JPG: 480x640 (no detections), 305.4ms
Speed: 1.9ms preprocess, 305.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_4gzB6KFTtJDqcd3tiTcA_0.JPG: 480x640 (no detections), 319.2ms
Speed: 1.7ms preprocess, 319.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_4gzB6KFTtJDqcd3tiTcA_90.JPG: 480x640 1 Waste, 314.3ms
Speed: 1.2ms preprocess, 314.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_4gzB6KFTtJDqcd3tiTcA_180.JPG: 480x640 (no detections), 314.7ms
Speed: 1.3ms preprocess, 314.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_4gzB6KFTtJDqcd3tiTcA_270.JPG: 480x640 (no detections), 308.5ms
Speed: 1.2ms preprocess, 308.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_7V0FKpmfjWZj8BOUsL3Q_0.JPG: 480x640 (no detections), 325.8ms
Speed: 1.2ms preprocess, 325.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_7V0FKpmfjWZj8BOUsL3Q_90.JPG: 480x640 (no detections), 307.5ms
Speed: 1.3ms preprocess, 307.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_7V0FKpmfjWZj8BOUsL3Q_180.JPG: 480x640 (no detections), 307.4ms
Speed: 1.1ms preprocess, 307.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_7V0FKpmfjWZj8BOUsL3Q_270.JPG: 480x640 (no detections), 314.9ms
Speed: 1.3ms preprocess, 314.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_ALpgGIgK2by0UJjKkOCQ_0.JPG: 480x640 (no detections), 336.1ms
Speed: 1.2ms preprocess, 336.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_ALpgGIgK2by0UJjKkOCQ_90.JPG: 480x640 (no detections), 314.8ms
Speed: 1.3ms preprocess, 314.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_ALpgGIgK2by0UJjKkOCQ_180.JPG: 480x640 (no detections), 316.1ms
Speed: 1.4ms preprocess, 316.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_ALpgGIgK2by0UJjKkOCQ_270.JPG: 480x640 (no detections), 312.4ms
Speed: 1.2ms preprocess, 312.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_Afu4NKGAkBYpSZk65YgQ_0.JPG: 480x640 (no detections), 309.2ms
Speed: 1.1ms preprocess, 309.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_Afu4NKGAkBYpSZk65YgQ_90.JPG: 480x640 (no detections), 309.2ms
Speed: 1.3ms preprocess, 309.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_Afu4NKGAkBYpSZk65YgQ_180.JPG: 480x640 (no detections), 314.6ms
Speed: 1.5ms preprocess, 314.6ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_Afu4NKGAkBYpSZk65YgQ_270.JPG: 480x640 (no detections), 314.4ms
Speed: 1.3ms preprocess, 314.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_Cl7lITA73SC98zRjKcPg_0.JPG: 480x640 (no detections), 312.9ms
Speed: 1.3ms preprocess, 312.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_Cl7lITA73SC98zRjKcPg_90.JPG: 480x640 (no detections), 325.9ms
Speed: 1.4ms preprocess, 325.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_Cl7lITA73SC98zRjKcPg_180.JPG: 480x640 (no detections), 283.6ms
Speed: 1.2ms preprocess, 283.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_Cl7lITA73SC98zRjKcPg_270.JPG: 480x640 (no detections), 276.1ms
Speed: 1.3ms preprocess, 276.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_CvD-L86yd_GDsmTcYxjg_0.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_CvD-L86yd_GDsmTcYxjg_90.JPG: 480x640 (no detections), 274.6ms
Speed: 1.0ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_CvD-L86yd_GDsmTcYxjg_180.JPG: 480x640 (no detections), 274.1ms
Speed: 1.2ms preprocess, 274.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_CvD-L86yd_GDsmTcYxjg_270.JPG: 480x640 (no detections), 271.5ms
Speed: 1.1ms preprocess, 271.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_EXZm4CsHRdWKhRGWpTZw_0.JPG: 480x640 (no detections), 268.6ms
Speed: 1.0ms preprocess, 268.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_EXZm4CsHRdWKhRGWpTZw_90.JPG: 480x640 (no detections), 268.3ms
Speed: 1.1ms preprocess, 268.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_EXZm4CsHRdWKhRGWpTZw_180.JPG: 480x640 (no detections), 268.0ms
Speed: 1.0ms preprocess, 268.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_EXZm4CsHRdWKhRGWpTZw_270.JPG: 480x640 (no detections), 268.3ms
Speed: 1.0ms preprocess, 268.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_ErcW8crfBqI1wq1gm4YQ_0.JPG: 480x640 (no detections), 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_ErcW8crfBqI1wq1gm4YQ_90.JPG: 480x640 (no detections), 295.6ms
Speed: 1.1ms preprocess, 295.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_ErcW8crfBqI1wq1gm4YQ_180.JPG: 480x640 (no detections), 278.4ms
Speed: 1.0ms preprocess, 278.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_ErcW8crfBqI1wq1gm4YQ_270.JPG: 480x640 (no detections), 271.6ms
Speed: 1.0ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_IARnw5cEx4xFKj4DH2RQ_0.JPG: 480x640 (no detections), 268.8ms
Speed: 1.0ms preprocess, 268.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_IARnw5cEx4xFKj4DH2RQ_90.JPG: 480x640 (no detections), 276.4ms
Speed: 1.1ms preprocess, 276.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_IARnw5cEx4xFKj4DH2RQ_180.JPG: 480x640 (no detections), 271.5ms

Speed: 1.1ms preprocess, 271.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_IARnw5cEx4xFKj4DH2RQ_270.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_KULZzXHWUGBzgwmW0VRA_0.JPG: 480x640 (no detections), 279.6ms
Speed: 1.1ms preprocess, 279.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_KULZzXHWUGBzgwmW0VRA_90.JPG: 480x640 (no detections), 267.0ms
Speed: 1.0ms preprocess, 267.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_KULZzXHWUGBzgwmW0VRA_180.JPG: 480x640 (no detections), 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_KULZzXHWUGBzgwmW0VRA_270.JPG: 480x640 (no detections), 275.3ms
Speed: 1.1ms preprocess, 275.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_KYAqZZ-32GMGZP9PKO5Q_0.JPG: 480x640 (no detections), 267.8ms
Speed: 1.1ms preprocess, 267.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_KYAqZZ-32GMGZP9PKO5Q_90.JPG: 480x640 (no detections), 265.5ms
Speed: 1.0ms preprocess, 265.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_KYAqZZ-32GMGZP9PKO5Q_180.JPG: 480x640 (no detections), 279.0ms
Speed: 1.1ms preprocess, 279.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_KYAqZZ-32GMGZP9PKO5Q_270.JPG: 480x640 (no detections), 268.7ms
Speed: 1.1ms preprocess, 268.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_NJTnUxb62-qk5Rhbl7wA_0.JPG: 480x640 (no detections), 263.3ms
Speed: 1.0ms preprocess, 263.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_NJTnUxb62-qk5Rhbl7wA_90.JPG: 480x640 (no detections), 274.5ms
Speed: 1.1ms preprocess, 274.5ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_NJTnUxb62-qk5Rhbl7wA_180.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_NJTnUxb62-qk5Rhbl7wA_270.JPG: 480x640 (no detections), 273.2ms
Speed: 1.1ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_OMxqD6TagKH9D-YOq-Vg_0.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_OMxqD6TagKH9D-YOq-Vg_90.JPG: 480x640 (no detections), 270.3ms
Speed: 1.0ms preprocess, 270.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_OMxqD6TagKH9D-YOq-Vg_180.JPG: 480x640 (no detections), 274.0ms
Speed: 1.1ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_OMxqD6TagKH9D-YOq-Vg_270.JPG: 480x640 (no detections), 265.5ms
Speed: 1.2ms preprocess, 265.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_R85FOtwczoJK-3v9PV2w_0.JPG: 480x640 (no detections), 269.6ms
Speed: 1.1ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_R85FOtwczoJK-3v9PV2w_90.JPG: 480x640 (no detections), 273.1ms
Speed: 1.1ms preprocess, 273.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_R85FOtwczoJK-3v9PV2w_180.JPG: 480x640 (no detections), 268.2ms
Speed: 1.0ms preprocess, 268.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_R85FOtwczoJK-3v9PV2w_270.JPG: 480x640 (no detections), 266.1ms
Speed: 1.1ms preprocess, 266.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_WOYW_rAz00Qr6U8B1mhQ_0.JPG: 480x640 (no detections), 270.8ms
Speed: 1.0ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_WOYW_rAz00Qr6U8B1mhQ_90.JPG: 480x640 (no detections), 270.4ms
Speed: 1.1ms preprocess, 270.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_WOYW_rAz00Qr6U8B1mhQ_180.JPG: 480x640 (no detections), 269.4ms
Speed: 1.0ms preprocess, 269.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_WOYW_rAz00Qr6U8B1mhQ_270.JPG: 480x640 (no detections), 267.8ms
Speed: 1.1ms preprocess, 267.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_YQhNYryIffYV7K7EmQlQ_0.JPG: 480x640 (no detections), 274.6ms
Speed: 1.1ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_YQhNYryIffYV7K7EmQlQ_90.JPG: 480x640 (no detections), 276.3ms
Speed: 1.0ms preprocess, 276.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_YQhNYryIffYV7K7EmQlQ_180.JPG: 480x640 (no detections), 266.5ms
Speed: 1.0ms preprocess, 266.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_YQhNYryIffYV7K7EmQlQ_270.JPG: 480x640 (no detections), 269.3ms
Speed: 1.0ms preprocess, 269.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w__IZcnigMlxEn6K9p6KlA_0.JPG: 480x640 (no detections), 267.8ms
Speed: 1.0ms preprocess, 267.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w__IZcnigMlxEn6K9p6KlA_90.JPG: 480x640 (no detections), 273.4ms
Speed: 1.0ms preprocess, 273.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w__IZcnigMlxEn6K9p6KlA_180.JPG: 480x640 (no detections), 285.6ms
Speed: 1.1ms preprocess, 285.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w__IZcnigMlxEn6K9p6KlA_270.JPG: 480x640 (no detections), 266.8ms
Speed: 1.0ms preprocess, 266.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_bN4C7kyNyrbHtQpshz_w_0.JPG: 480x640 (no detections), 271.8ms
Speed: 1.0ms preprocess, 271.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_bN4C7kyNyrbHtQpshz_w_90.JPG: 480x640 (no detections), 277.9ms
Speed: 1.0ms preprocess, 277.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_bN4C7kyNyrbHtQpshz_w_180.JPG: 480x640 (no detections), 264.8ms
Speed: 1.0ms preprocess, 264.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_bN4C7kyNyrbHtQpshz_w_270.JPG: 480x640 (no detections), 273.8ms
Speed: 1.0ms preprocess, 273.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_dNNNNrQApKRGlSHpgnQA_0.JPG: 480x640 (no detections), 269.9ms
Speed: 1.0ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_dNNNNrQApKRGlSHpgnQA_90.JPG: 480x640 (no detections), 268.5ms
Speed: 1.1ms preprocess, 268.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_dNNNNrQApKRGlSHpgnQA_180.JPG: 480x640 (no detections), 274.8ms
Speed: 1.1ms preprocess, 274.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_dNNNNrQApKRGlSHpgnQA_270.JPG: 480x640 (no detections), 270.6ms
Speed: 1.2ms preprocess, 270.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_ekjLypJ0P4PCrwK_bGOw_0.JPG: 480x640 (no detections), 270.5ms
Speed: 1.1ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_ekjLypJ0P4PCrwK_bGOw_90.JPG: 480x640 (no detections), 272.5ms
Speed: 1.0ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_ekjLypJ0P4PCrwK_bGOw_180.JPG: 480x640 (no detections), 322.5ms
Speed: 1.0ms preprocess, 322.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_ekjLypJ0P4PCrwK_bGOw_270.JPG: 480x640 (no detections), 337.5ms
Speed: 1.3ms preprocess, 337.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_f1JkZfLGXfFlW7Ql83pg_0.JPG: 480x640 (no detections), 298.7ms
Speed: 1.3ms preprocess, 298.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_f1JkZfLGXfFlW7Ql83pg_90.JPG: 480x640 (no detections), 292.3ms
Speed: 1.1ms preprocess, 292.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_f1JkZfLGXfFlW7Ql83pg_180.JPG: 480x640 (no detections), 279.3ms
Speed: 1.7ms preprocess, 279.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_f1JkZfLGXfFlW7Ql83pg_270.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_gJG9CV7kDexrQfW4eOQg_0.JPG: 480x640 (no detections), 265.7ms
Speed: 1.0ms preprocess, 265.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_gJG9CV7kDexrQfW4eOQg_90.JPG: 480x640 (no detections), 291.1ms
Speed: 1.1ms preprocess, 291.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_gJG9CV7kDexrQfW4eOQg_180.JPG: 480x640 (no detections), 286.5ms
Speed: 1.3ms preprocess, 286.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_gJG9CV7kDexrQfW4eOQg_270.JPG: 480x640 (no detections), 271.8ms
Speed: 1.2ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_g_ZpT1fcnax-eKnXjjKw_0.JPG: 480x640 (no detections), 276.3ms
Speed: 1.1ms preprocess, 276.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_g_ZpT1fcnax-eKnXjjKw_90.JPG: 480x640 (no detections), 267.0ms
Speed: 1.2ms preprocess, 267.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_g_ZpT1fcnax-eKnXjjKw_180.JPG: 480x640 (no detections), 269.6ms
Speed: 1.1ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_g_ZpT1fcnax-eKnXjjKw_270.JPG: 480x640 (no detections), 266.3ms
Speed: 1.1ms preprocess, 266.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_izeMNDPX6GuGFyZG6tJg_0.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_izeMNDPX6GuGFyZG6tJg_90.JPG: 480x640 (no detections), 267.4ms
Speed: 1.0ms preprocess, 267.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_izeMNDPX6GuGFyZG6tJg_180.JPG: 480x640 (no detections), 268.3ms
Speed: 1.1ms preprocess, 268.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_izeMNDPX6GuGFyZG6tJg_270.JPG: 480x640 (no detections), 267.0ms
Speed: 1.1ms preprocess, 267.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_mFvRt9ZsBElm6YyBClAg_0.JPG: 480x640 (no detections), 266.8ms
Speed: 1.0ms preprocess, 266.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_mFvRt9ZsBElm6YyBClAg_90.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_mFvRt9ZsBElm6YyBClAg_180.JPG: 480x640 (no detections), 269.2ms
Speed: 1.0ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_mFvRt9ZsBElm6YyBClAg_270.JPG: 480x640 (no detections), 269.3ms
Speed: 1.2ms preprocess, 269.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_nfvY3CorHL89AoQrt-Sg_0.JPG: 480x640 (no detections), 268.9ms
Speed: 1.1ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_nfvY3CorHL89AoQrt-Sg_90.JPG: 480x640 (no detections), 269.8ms

Speed: 1.0ms preprocess, 269.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_nfvY3CorHL89AoQrt-Sg_180.JPG: 480x640 (no detections), 270.5ms
Speed: 1.1ms preprocess, 270.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_nfvY3CorHL89AoQrt-Sg_270.JPG: 480x640 (no detections), 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_nkEtTe7PpB_S2M2mwbSA_0.JPG: 480x640 (no detections), 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_nkEtTe7PpB_S2M2mwbSA_90.JPG: 480x640 (no detections), 268.2ms
Speed: 1.0ms preprocess, 268.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_nkEtTe7PpB_S2M2mwbSA_180.JPG: 480x640 (no detections), 268.4ms
Speed: 1.0ms preprocess, 268.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_nkEtTe7PpB_S2M2mwbSA_270.JPG: 480x640 (no detections), 271.7ms
Speed: 1.0ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_noflPCiL5MtotjGXmP6Q_0.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_noflPCiL5MtotjGXmP6Q_90.JPG: 480x640 (no detections), 268.3ms
Speed: 1.2ms preprocess, 268.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_noflPCiL5MtotjGXmP6Q_180.JPG: 480x640 (no detections), 269.6ms
Speed: 1.0ms preprocess, 269.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_noflPCiL5MtotjGXmP6Q_270.JPG: 480x640 (no detections), 268.8ms
Speed: 1.1ms preprocess, 268.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_oRYbMcDpYjwEgVl6r5yQ_0.JPG: 480x640 (no detections), 267.8ms
Speed: 1.0ms preprocess, 267.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_oRYbMcDpYjwEgVl6r5yQ_90.JPG: 480x640 (no detections), 269.7ms
Speed: 1.0ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_oRYbMcDpYjwEgVl6r5yQ_180.JPG: 480x640 (no detections), 267.9ms
Speed: 1.1ms preprocess, 267.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_oRYbMcDpYjwEgVl6r5yQ_270.JPG: 480x640 (no detections), 266.5ms
Speed: 1.0ms preprocess, 266.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_or0HLMX2-7FCQ_3qbjqQ_0.JPG: 480x640 (no detections), 268.4ms
Speed: 1.0ms preprocess, 268.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_or0HLMX2-7FCQ_3qbjqQ_90.JPG: 480x640 (no detections), 269.1ms
Speed: 1.0ms preprocess, 269.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_or0HLMX2-7FCQ_3qbjqQ_180.JPG: 480x640 (no detections), 275.2ms
Speed: 1.1ms preprocess, 275.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_or0HLMX2-7FCQ_3qbjqQ_270.JPG: 480x640 (no detections), 268.0ms
Speed: 1.0ms preprocess, 268.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_tAVlIT2bV8tKZfh-oGWw_0.JPG: 480x640 (no detections), 266.4ms
Speed: 1.1ms preprocess, 266.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_tAVlIT2bV8tKZfh-oGWw_90.JPG: 480x640 (no detections), 268.8ms
Speed: 1.0ms preprocess, 268.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_tAVlIT2bV8tKZfh-oGWw_180.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_tAVlIT2bV8tKZfh-oGWw_270.JPG: 480x640 (no detections), 267.2ms
Speed: 1.0ms preprocess, 267.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_uBFI8J_VFgib15CO7TUQ_0.JPG: 480x640 (no detections), 264.9ms
Speed: 1.0ms preprocess, 264.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_uBFI8J_VFgib15CO7TUQ_90.JPG: 480x640 (no detections), 264.2ms
Speed: 1.1ms preprocess, 264.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_uBFI8J_VFgib15CO7TUQ_180.JPG: 480x640 (no detections), 267.9ms
Speed: 1.0ms preprocess, 267.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_uBFI8J_VFgib15CO7TUQ_270.JPG: 480x640 (no detections), 267.3ms
Speed: 1.1ms preprocess, 267.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_uz1PViwojvU9a-ZEPF2Q_0.JPG: 480x640 (no detections), 266.7ms
Speed: 1.0ms preprocess, 266.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_uz1PViwojvU9a-ZEPF2Q_90.JPG: 480x640 (no detections), 267.5ms
Speed: 1.1ms preprocess, 267.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_uz1PViwojvU9a-ZEPF2Q_180.JPG: 480x640 (no detections), 266.9ms
Speed: 1.0ms preprocess, 266.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/_/w_uz1PViwojvU9a-ZEPF2Q_270.JPG: 480x640 (no detections), 267.2ms
Speed: 1.1ms preprocess, 267.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wa-kMELZGVcOJDzu6duhaQ_0.JPG: 480x640 (no detections), 270.1ms
Speed: 1.0ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wa-kMELZGVcOJDzu6duhaQ_90.JPG: 480x640 1 Waste, 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wa-kMELZGVcOJDzu6duhaQ_180.JPG: 480x640 (no detections), 267.6ms
Speed: 1.2ms preprocess, 267.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wa-kMELZGVcOJDzu6duhaQ_270.JPG: 480x640 (no detections), 267.2ms
Speed: 1.0ms preprocess, 267.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wa0mtK5rWK9x9tKB3x0Hzg_0.JPG: 480x640 (no detections), 266.3ms
Speed: 1.0ms preprocess, 266.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wa0mtK5rWK9x9tKB3x0Hzg_90.JPG: 480x640 (no detections), 266.1ms
Speed: 1.0ms preprocess, 266.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wa0mtK5rWK9x9tKB3x0Hzg_180.JPG: 480x640 (no detections), 268.2ms
Speed: 1.0ms preprocess, 268.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wa0mtK5rWK9x9tKB3x0Hzg_270.JPG: 480x640 (no detections), 267.9ms
Speed: 1.2ms preprocess, 267.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wa0vUmV76qlaXu3SZ6z5mQ_0.JPG: 480x640 (no detections), 268.0ms
Speed: 1.1ms preprocess, 268.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wa0vUmV76qlaXu3SZ6z5mQ_90.JPG: 480x640 (no detections), 268.2ms
Speed: 1.2ms preprocess, 268.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wa0vUmV76qlaXu3SZ6z5mQ_180.JPG: 480x640 (no detections), 267.4ms
Speed: 1.5ms preprocess, 267.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wa0vUmV76qlaXu3SZ6z5mQ_270.JPG: 480x640 (no detections), 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wa12Yujay_3-6Bul9Tgkhg_0.JPG: 480x640 (no detections), 268.3ms
Speed: 1.1ms preprocess, 268.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wa12Yujay_3-6Bul9Tgkhg_90.JPG: 480x640 (no detections), 267.3ms
Speed: 1.1ms preprocess, 267.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wa12Yujay_3-6Bul9Tgkhg_180.JPG: 480x640 (no detections), 266.1ms
Speed: 1.1ms preprocess, 266.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wa12Yujay_3-6Bul9Tgkhg_270.JPG: 480x640 (no detections), 272.5ms
Speed: 1.1ms preprocess, 272.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wa1LFqVRRheE6iI7XXTMwg_0.JPG: 480x640 (no detections), 268.4ms
Speed: 1.0ms preprocess, 268.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wa1LFqVRRheE6iI7XXTMwg_90.JPG: 480x640 (no detections), 268.9ms
Speed: 1.1ms preprocess, 268.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wa1LFqVRRheE6iI7XXTMwg_180.JPG: 480x640 (no detections), 269.2ms
Speed: 1.1ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wa1LFqVRRheE6iI7XXTMwg_270.JPG: 480x640 (no detections), 267.3ms
Speed: 1.1ms preprocess, 267.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wa3sWnMGVeImTY9SddnglQ_0.JPG: 480x640 (no detections), 269.6ms
Speed: 1.0ms preprocess, 269.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wa3sWnMGVeImTY9SddnglQ_90.JPG: 480x640 (no detections), 268.6ms
Speed: 1.1ms preprocess, 268.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wa3sWnMGVeImTY9SddnglQ_180.JPG: 480x640 (no detections), 266.9ms
Speed: 1.1ms preprocess, 266.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wa3sWnMGVeImTY9SddnglQ_270.JPG: 480x640 (no detections), 266.3ms
Speed: 1.0ms preprocess, 266.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waAQqev_Jto3b3Fqq5bujQ_0.JPG: 480x640 (no detections), 271.2ms
Speed: 1.0ms preprocess, 271.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waAQqev_Jto3b3Fqq5bujQ_90.JPG: 480x640 (no detections), 269.5ms
Speed: 1.1ms preprocess, 269.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waAQqev_Jto3b3Fqq5bujQ_180.JPG: 480x640 (no detections), 269.0ms
Speed: 1.1ms preprocess, 269.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waAQqev_Jto3b3Fqq5bujQ_270.JPG: 480x640 (no detections), 267.7ms
Speed: 1.0ms preprocess, 267.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waJZl_nVhSzOmTyx91yQ4A_0.JPG: 480x640 (no detections), 267.1ms
Speed: 1.1ms preprocess, 267.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waJZl_nVhSzOmTyx91yQ4A_90.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waJZl_nVhSzOmTyx91yQ4A_180.JPG: 480x640 1 Waste, 275.3ms
Speed: 1.0ms preprocess, 275.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waJZl_nVhSzOmTyx91yQ4A_270.JPG: 480x640 1 Waste, 268.1ms
Speed: 1.1ms preprocess, 268.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waL8sHKFZrFlAn1L2dqr5g_0.JPG: 480x640 (no detections), 269.2ms
Speed: 1.0ms preprocess, 269.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waL8sHKFZrFlAn1L2dqr5g_90.JPG: 480x640 (no detections), 273.9ms
Speed: 1.0ms preprocess, 273.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waL8sHKFZrFlAn1L2dqr5g_180.JPG: 480x640 (no detections), 268.9ms
Speed: 1.3ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waL8sHKFZrFlAn1L2dqr5g_270.JPG: 480x640 (no detections), 267.4ms
Speed: 1.0ms preprocess, 267.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waLBnC2so3kYyRPwG6X9cg_0.JPG: 480x640 (no detections), 267.1ms

Speed: 1.1ms preprocess, 267.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waLBnC2so3kYyRPwG6X9cg_90.JPG: 480x640 (no detections), 269.7ms
Speed: 1.0ms preprocess, 269.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waLBnC2so3kYyRPwG6X9cg_180.JPG: 480x640 (no detections), 267.8ms
Speed: 1.1ms preprocess, 267.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waLBnC2so3kYyRPwG6X9cg_270.JPG: 480x640 (no detections), 269.8ms
Speed: 1.0ms preprocess, 269.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waM6EDA0JswjU1J70pzdSg_0.JPG: 480x640 (no detections), 268.5ms
Speed: 1.1ms preprocess, 268.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waM6EDA0JswjU1J70pzdSg_90.JPG: 480x640 (no detections), 268.3ms
Speed: 1.0ms preprocess, 268.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waM6EDA0JswjU1J70pzdSg_180.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waM6EDA0JswjU1J70pzdSg_270.JPG: 480x640 (no detections), 269.6ms
Speed: 1.0ms preprocess, 269.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waMsE1jzmaiO6B3fq8VfCQ_0.JPG: 480x640 (no detections), 265.8ms
Speed: 1.1ms preprocess, 265.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waMsE1jzmaiO6B3fq8VfCQ_90.JPG: 480x640 (no detections), 274.9ms
Speed: 1.1ms preprocess, 274.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waMsE1jzmaiO6B3fq8VfCQ_180.JPG: 480x640 (no detections), 268.1ms
Speed: 1.1ms preprocess, 268.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waMsE1jzmaiO6B3fq8VfCQ_270.JPG: 480x640 (no detections), 266.3ms
Speed: 1.1ms preprocess, 266.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waRQptajWELGXH2yiOMGbw_0.JPG: 480x640 (no detections), 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waRQptajWELGXH2yiOMGbw_90.JPG: 480x640 (no detections), 269.8ms
Speed: 1.2ms preprocess, 269.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waRQptajWELGXH2yiOMGbw_180.JPG: 480x640 (no detections), 269.9ms
Speed: 1.0ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waRQptajWELGXH2yiOMGbw_270.JPG: 480x640 (no detections), 267.6ms
Speed: 1.1ms preprocess, 267.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waSDnTLpTsRF5q_jrOny-w_0.JPG: 480x640 (no detections), 268.1ms
Speed: 1.1ms preprocess, 268.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waSDnTLpTsRF5q_jrOny-w_90.JPG: 480x640 (no detections), 265.2ms
Speed: 1.1ms preprocess, 265.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waSDnTLpTsRF5q_jrOny-w_180.JPG: 480x640 (no detections), 266.8ms
Speed: 1.1ms preprocess, 266.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waSDnTLpTsRF5q_jrOny-w_270.JPG: 480x640 (no detections), 268.2ms
Speed: 1.1ms preprocess, 268.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waTpimocPSvLh2tnOJV6Mw_0.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waTpimocPSvLh2tnOJV6Mw_90.JPG: 480x640 (no detections), 265.7ms
Speed: 1.0ms preprocess, 265.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waTpimocPSvLh2tnOJV6Mw_180.JPG: 480x640 (no detections), 265.8ms
Speed: 1.1ms preprocess, 265.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waTpimocPSvLh2tnOJV6Mw_270.JPG: 480x640 (no detections), 268.4ms
Speed: 1.0ms preprocess, 268.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waW_dJvZbB-cupxOGDixWg_0.JPG: 480x640 (no detections), 272.5ms
Speed: 1.1ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waW_dJvZbB-cupxOGDixWg_90.JPG: 480x640 (no detections), 264.6ms
Speed: 1.1ms preprocess, 264.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waW_dJvZbB-cupxOGDixWg_180.JPG: 480x640 (no detections), 269.6ms
Speed: 1.0ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waW_dJvZbB-cupxOGDixWg_270.JPG: 480x640 (no detections), 269.5ms
Speed: 1.1ms preprocess, 269.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waZXt1ghJQq_EWreizvlpA_0.JPG: 480x640 (no detections), 270.2ms
Speed: 1.0ms preprocess, 270.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waZXt1ghJQq_EWreizvlpA_90.JPG: 480x640 (no detections), 270.9ms
Speed: 0.9ms preprocess, 270.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waZXt1ghJQq_EWreizvlpA_180.JPG: 480x640 (no detections), 267.9ms
Speed: 1.0ms preprocess, 267.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waZXt1ghJQq_EWreizvlpA_270.JPG: 480x640 (no detections), 265.1ms
Speed: 1.0ms preprocess, 265.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waZj5iHDgcPxBra8Er_SRQ_0.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waZj5iHDgcPxBra8Er_SRQ_90.JPG: 480x640 (no detections), 267.1ms
Speed: 1.0ms preprocess, 267.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waZj5iHDgcPxBra8Er_SRQ_180.JPG: 480x640 (no detections), 266.3ms
Speed: 1.0ms preprocess, 266.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waZj5iHDgcPxBra8Er_SRQ_270.JPG: 480x640 (no detections), 269.6ms
Speed: 1.0ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wadgzpgwF8vXAhZVy1GElQ_0.JPG: 480x640 1 Waste, 268.1ms
Speed: 1.0ms preprocess, 268.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wadgzpgwF8vXAhZVy1GElQ_90.JPG: 480x640 (no detections), 268.6ms
Speed: 1.1ms preprocess, 268.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wadgzpgwF8vXAhZVy1GElQ_180.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wadgzpgwF8vXAhZVy1GElQ_270.JPG: 480x640 (no detections), 270.2ms
Speed: 1.0ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wahj87ZQGRZQe4UJ467XrQ_0.JPG: 480x640 (no detections), 268.1ms
Speed: 1.0ms preprocess, 268.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wahj87ZQGRZQe4UJ467XrQ_90.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wahj87ZQGRZQe4UJ467XrQ_180.JPG: 480x640 (no detections), 269.2ms
Speed: 1.0ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wahj87ZQGRZQe4UJ467XrQ_270.JPG: 480x640 (no detections), 267.1ms
Speed: 1.1ms preprocess, 267.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waiX5sSx5IUiXa-KJfXEuA_0.JPG: 480x640 (no detections), 267.7ms
Speed: 1.2ms preprocess, 267.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waiX5sSx5IUiXa-KJfXEuA_90.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waiX5sSx5IUiXa-KJfXEuA_180.JPG: 480x640 (no detections), 266.2ms
Speed: 1.1ms preprocess, 266.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waiX5sSx5IUiXa-KJfXEuA_270.JPG: 480x640 (no detections), 268.2ms
Speed: 1.0ms preprocess, 268.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wak1THyai7ViStzOQZkiew_0.JPG: 480x640 (no detections), 269.1ms
Speed: 1.0ms preprocess, 269.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wak1THyai7ViStzOQZkiew_90.JPG: 480x640 (no detections), 269.3ms
Speed: 1.1ms preprocess, 269.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wak1THyai7ViStzOQZkiew_180.JPG: 480x640 (no detections), 273.6ms
Speed: 1.0ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wak1THyai7ViStzOQZkiew_270.JPG: 480x640 (no detections), 269.5ms
Speed: 1.1ms preprocess, 269.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wakrGnGG1ECGHs62RJwakw_0.JPG: 480x640 (no detections), 266.5ms
Speed: 1.1ms preprocess, 266.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wakrGnGG1ECGHs62RJwakw_90.JPG: 480x640 (no detections), 274.2ms
Speed: 1.0ms preprocess, 274.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wakrGnGG1ECGHs62RJwakw_180.JPG: 480x640 (no detections), 269.8ms
Speed: 1.1ms preprocess, 269.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wakrGnGG1ECGHs62RJwakw_270.JPG: 480x640 (no detections), 267.9ms
Speed: 1.2ms preprocess, 267.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waqr3Swjy9u4cVNE5h2Yrg_0.JPG: 480x640 (no detections), 268.7ms
Speed: 1.0ms preprocess, 268.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waqr3Swjy9u4cVNE5h2Yrg_90.JPG: 480x640 (no detections), 265.3ms
Speed: 1.2ms preprocess, 265.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waqr3Swjy9u4cVNE5h2Yrg_180.JPG: 480x640 (no detections), 267.1ms
Speed: 1.0ms preprocess, 267.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waqr3Swjy9u4cVNE5h2Yrg_270.JPG: 480x640 (no detections), 270.7ms
Speed: 1.0ms preprocess, 270.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wask52Oafpj4rmpXgjzG5A_0.JPG: 480x640 (no detections), 267.6ms
Speed: 1.0ms preprocess, 267.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wask52Oafpj4rmpXgjzG5A_90.JPG: 480x640 (no detections), 265.2ms
Speed: 1.0ms preprocess, 265.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wask52Oafpj4rmpXgjzG5A_180.JPG: 480x640 (no detections), 266.7ms
Speed: 1.1ms preprocess, 266.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wask52Oafpj4rmpXgjzG5A_270.JPG: 480x640 (no detections), 268.7ms
Speed: 1.1ms preprocess, 268.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waspIZlXPDcAE1wx6wjwEA_0.JPG: 480x640 1 Waste, 269.5ms
Speed: 1.1ms preprocess, 269.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waspIZlXPDcAE1wx6wjwEA_90.JPG: 480x640 (no detections), 270.4ms
Speed: 1.1ms preprocess, 270.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waspIZlXPDcAE1wx6wjwEA_180.JPG: 480x640 (no detections), 266.9ms
Speed: 1.0ms preprocess, 266.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waspIZlXPDcAE1wx6wjwEA_270.JPG: 480x640 (no detections), 268.1ms

Speed: 1.1ms preprocess, 268.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/watkeCl9hweRy8CrJRQ-2A_0.JPG: 480x640 1 Waste, 275.8ms
Speed: 1.1ms preprocess, 275.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/watkeCl9hweRy8CrJRQ-2A_90.JPG: 480x640 (no detections), 268.0ms
Speed: 1.0ms preprocess, 268.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/watkeCl9hweRy8CrJRQ-2A_180.JPG: 480x640 (no detections), 271.0ms
Speed: 1.2ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/watkeCl9hweRy8CrJRQ-2A_270.JPG: 480x640 (no detections), 266.7ms
Speed: 1.1ms preprocess, 266.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wavBUFcglYeNDVYK-f8nng_0.JPG: 480x640 (no detections), 267.0ms
Speed: 1.1ms preprocess, 267.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wavBUFcglYeNDVYK-f8nng_90.JPG: 480x640 (no detections), 265.0ms
Speed: 1.1ms preprocess, 265.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wavBUFcglYeNDVYK-f8nng_180.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wavBUFcglYeNDVYK-f8nng_270.JPG: 480x640 (no detections), 266.8ms
Speed: 1.0ms preprocess, 266.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waw1PX9zO0SnLqjOj7H_jw_0.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waw1PX9zO0SnLqjOj7H_jw_90.JPG: 480x640 (no detections), 266.4ms
Speed: 1.1ms preprocess, 266.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waw1PX9zO0SnLqjOj7H_jw_180.JPG: 480x640 (no detections), 264.9ms
Speed: 1.1ms preprocess, 264.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/waw1PX9zO0SnLqjOj7H_jw_270.JPG: 480x640 (no detections), 268.9ms
Speed: 1.1ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wawaUvcovCDRtId0C1in6g_0.JPG: 480x640 (no detections), 266.8ms
Speed: 1.1ms preprocess, 266.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wawaUvcovCDRtId0C1in6g_90.JPG: 480x640 (no detections), 266.9ms
Speed: 1.0ms preprocess, 266.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wawaUvcovCDRtId0C1in6g_180.JPG: 480x640 (no detections), 272.5ms
Speed: 1.0ms preprocess, 272.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wawaUvcovCDRtId0C1in6g_270.JPG: 480x640 (no detections), 266.5ms
Speed: 1.0ms preprocess, 266.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wawvcRGXfScKi1_1VQfp5A_0.JPG: 480x640 (no detections), 269.6ms
Speed: 1.0ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wawvcRGXfScKi1_1VQfp5A_90.JPG: 480x640 (no detections), 266.9ms
Speed: 1.1ms preprocess, 266.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wawvcRGXfScKi1_1VQfp5A_180.JPG: 480x640 (no detections), 269.3ms
Speed: 1.2ms preprocess, 269.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wawvcRGXfScKi1_1VQfp5A_270.JPG: 480x640 (no detections), 267.7ms
Speed: 1.0ms preprocess, 267.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wayiM_PvUcOPMYnq-MaAhA_0.JPG: 480x640 (no detections), 264.7ms
Speed: 1.1ms preprocess, 264.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wayiM_PvUcOPMYnq-MaAhA_90.JPG: 480x640 (no detections), 266.0ms
Speed: 1.1ms preprocess, 266.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wayiM_PvUcOPMYnq-MaAhA_180.JPG: 480x640 (no detections), 268.5ms
Speed: 1.0ms preprocess, 268.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/a/wayiM_PvUcOPMYnq-MaAhA_270.JPG: 480x640 (no detections), 269.9ms
Speed: 1.0ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wb-L3Rcq_2ETp5q8j8Hxhw_0.JPG: 480x640 (no detections), 270.8ms
Speed: 1.0ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wb-L3Rcq_2ETp5q8j8Hxhw_90.JPG: 480x640 (no detections), 269.6ms
Speed: 1.2ms preprocess, 269.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wb-L3Rcq_2ETp5q8j8Hxhw_180.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wb-L3Rcq_2ETp5q8j8Hxhw_270.JPG: 480x640 (no detections), 264.9ms
Speed: 1.0ms preprocess, 264.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wb0wQnPcNhKvzJAm4tLf1w_0.JPG: 480x640 (no detections), 267.4ms
Speed: 1.1ms preprocess, 267.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wb0wQnPcNhKvzJAm4tLf1w_90.JPG: 480x640 (no detections), 274.2ms
Speed: 1.1ms preprocess, 274.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wb0wQnPcNhKvzJAm4tLf1w_180.JPG: 480x640 (no detections), 265.6ms
Speed: 1.0ms preprocess, 265.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wb0wQnPcNhKvzJAm4tLf1w_270.JPG: 480x640 (no detections), 266.5ms
Speed: 1.1ms preprocess, 266.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wb16PDKBhH1BdWo-uW0Uxg_0.JPG: 480x640 (no detections), 268.7ms
Speed: 1.1ms preprocess, 268.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wb16PDKBhH1BdWo-uW0Uxg_90.JPG: 480x640 (no detections), 270.4ms
Speed: 1.0ms preprocess, 270.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wb16PDKBhH1BdWo-uW0Uxg_180.JPG: 480x640 (no detections), 271.0ms
Speed: 1.0ms preprocess, 271.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wb16PDKBhH1BdWo-uW0Uxg_270.JPG: 480x640 (no detections), 265.9ms
Speed: 1.2ms preprocess, 265.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wb26uJKrGcmZJSOgeBth4A_0.JPG: 480x640 (no detections), 266.5ms
Speed: 1.1ms preprocess, 266.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wb26uJKrGcmZJSOgeBth4A_90.JPG: 480x640 (no detections), 268.2ms
Speed: 1.1ms preprocess, 268.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wb26uJKrGcmZJSOgeBth4A_180.JPG: 480x640 1 Waste, 268.4ms
Speed: 1.1ms preprocess, 268.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wb26uJKrGcmZJSOgeBth4A_270.JPG: 480x640 (no detections), 268.8ms
Speed: 1.1ms preprocess, 268.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wb2AgoK0i_fA_nbErlLAxw_0.JPG: 480x640 (no detections), 270.6ms
Speed: 1.0ms preprocess, 270.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wb2AgoK0i_fA_nbErlLAxw_90.JPG: 480x640 (no detections), 267.4ms
Speed: 1.0ms preprocess, 267.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wb2AgoK0i_fA_nbErlLAxw_180.JPG: 480x640 (no detections), 265.8ms
Speed: 1.1ms preprocess, 265.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wb2AgoK0i_fA_nbErlLAxw_270.JPG: 480x640 (no detections), 266.6ms
Speed: 1.0ms preprocess, 266.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wb4Cm1zjXEATotoYeyur3A_0.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wb4Cm1zjXEATotoYeyur3A_90.JPG: 480x640 (no detections), 268.5ms
Speed: 1.2ms preprocess, 268.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wb4Cm1zjXEATotoYeyur3A_180.JPG: 480x640 (no detections), 268.4ms
Speed: 1.1ms preprocess, 268.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wb4Cm1zjXEATotoYeyur3A_270.JPG: 480x640 (no detections), 267.7ms
Speed: 1.0ms preprocess, 267.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wb4bO-s40etZ0UaXueB9vg_0.JPG: 480x640 (no detections), 267.6ms
Speed: 1.1ms preprocess, 267.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wb4bO-s40etZ0UaXueB9vg_90.JPG: 480x640 (no detections), 268.3ms
Speed: 1.0ms preprocess, 268.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wb4bO-s40etZ0UaXueB9vg_180.JPG: 480x640 (no detections), 267.0ms
Speed: 1.0ms preprocess, 267.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wb4bO-s40etZ0UaXueB9vg_270.JPG: 480x640 (no detections), 270.0ms
Speed: 1.0ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wb7aRxcSrkC7inqXX_vsmA_0.JPG: 480x640 (no detections), 268.9ms
Speed: 1.0ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wb7aRxcSrkC7inqXX_vsmA_90.JPG: 480x640 (no detections), 264.4ms
Speed: 1.1ms preprocess, 264.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wb7aRxcSrkC7inqXX_vsmA_180.JPG: 480x640 (no detections), 268.7ms
Speed: 1.1ms preprocess, 268.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wb7aRxcSrkC7inqXX_vsmA_270.JPG: 480x640 (no detections), 268.4ms
Speed: 1.1ms preprocess, 268.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbAQLRoTy5FvW2czt2UxAA_0.JPG: 480x640 (no detections), 268.1ms
Speed: 1.0ms preprocess, 268.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbAQLRoTy5FvW2czt2UxAA_90.JPG: 480x640 (no detections), 275.7ms
Speed: 1.0ms preprocess, 275.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbAQLRoTy5FvW2czt2UxAA_180.JPG: 480x640 (no detections), 272.0ms
Speed: 1.1ms preprocess, 272.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbAQLRoTy5FvW2czt2UxAA_270.JPG: 480x640 (no detections), 276.2ms
Speed: 1.1ms preprocess, 276.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbCGbrE8aE-t9kkkdYDU_Q_0.JPG: 480x640 (no detections), 296.3ms
Speed: 1.2ms preprocess, 296.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbCGbrE8aE-t9kkkdYDU_Q_90.JPG: 480x640 (no detections), 275.6ms
Speed: 1.1ms preprocess, 275.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbCGbrE8aE-t9kkkdYDU_Q_180.JPG: 480x640 (no detections), 267.8ms
Speed: 1.1ms preprocess, 267.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbCGbrE8aE-t9kkkdYDU_Q_270.JPG: 480x640 (no detections), 268.7ms
Speed: 1.0ms preprocess, 268.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbG23rz4xyF-14zf2dT9Tg_0.JPG: 480x640 (no detections), 268.2ms
Speed: 1.0ms preprocess, 268.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbG23rz4xyF-14zf2dT9Tg_90.JPG: 480x640 (no detections), 310.8ms
Speed: 1.1ms preprocess, 310.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbG23rz4xyF-14zf2dT9Tg_180.JPG: 480x640 (no detections), 309.0ms

Speed: 1.3ms preprocess, 309.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbG23rz4xyF-14zf2dT9Tg_270.JPG: 480x640 (no detections), 271.6ms
Speed: 1.7ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbKQsNgUxHFyptuor0vpKg_0.JPG: 480x640 (no detections), 291.7ms
Speed: 1.1ms preprocess, 291.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbKQsNgUxHFyptuor0vpKg_90.JPG: 480x640 (no detections), 289.9ms
Speed: 1.1ms preprocess, 289.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbKQsNgUxHFyptuor0vpKg_180.JPG: 480x640 (no detections), 266.9ms
Speed: 1.2ms preprocess, 266.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbKQsNgUxHFyptuor0vpKg_270.JPG: 480x640 (no detections), 266.9ms
Speed: 1.1ms preprocess, 266.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbNXr4OrAJrZRxSKsXCiig_0.JPG: 480x640 (no detections), 267.1ms
Speed: 1.0ms preprocess, 267.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbNXr4OrAJrZRxSKsXCiig_90.JPG: 480x640 (no detections), 272.4ms
Speed: 1.0ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbNXr4OrAJrZRxSKsXCiig_180.JPG: 480x640 (no detections), 264.2ms
Speed: 1.0ms preprocess, 264.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbNXr4OrAJrZRxSKsXCiig_270.JPG: 480x640 (no detections), 273.5ms
Speed: 1.0ms preprocess, 273.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbNiLYR-T5xTSTTpcMzH7w_0.JPG: 480x640 (no detections), 267.8ms
Speed: 1.1ms preprocess, 267.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbNiLYR-T5xTSTTpcMzH7w_90.JPG: 480x640 (no detections), 270.3ms
Speed: 1.1ms preprocess, 270.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbNiLYR-T5xTSTTpcMzH7w_180.JPG: 480x640 (no detections), 264.7ms
Speed: 1.0ms preprocess, 264.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbNiLYR-T5xTSTTpcMzH7w_270.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbPZSuofAdaeSUUNMl2OIQ_0.JPG: 480x640 (no detections), 268.6ms
Speed: 1.1ms preprocess, 268.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbPZSuofAdaeSUUNMl2OIQ_90.JPG: 480x640 (no detections), 270.3ms
Speed: 1.1ms preprocess, 270.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbPZSuofAdaeSUUNMl2OIQ_180.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbPZSuofAdaeSUUNMl2OIQ_270.JPG: 480x640 (no detections), 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbQGD-j2PTKnIw24elSeHw_0.JPG: 480x640 (no detections), 271.9ms
Speed: 1.0ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbQGD-j2PTKnIw24elSeHw_90.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbQGD-j2PTKnIw24elSeHw_180.JPG: 480x640 (no detections), 265.4ms
Speed: 1.1ms preprocess, 265.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbQGD-j2PTKnIw24elSeHw_270.JPG: 480x640 (no detections), 271.8ms
Speed: 1.0ms preprocess, 271.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbSHnAkijpJMj3H6IX655w_0.JPG: 480x640 (no detections), 265.1ms
Speed: 1.2ms preprocess, 265.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbSHnAkijpJMj3H6IX655w_90.JPG: 480x640 (no detections), 272.1ms
Speed: 1.1ms preprocess, 272.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbSHnAkijpJMj3H6IX655w_180.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbSHnAkijpJMj3H6IX655w_270.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbTR95oEflrz4B5GqAt1tw_0.JPG: 480x640 (no detections), 273.4ms
Speed: 1.4ms preprocess, 273.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbTR95oEflrz4B5GqAt1tw_90.JPG: 480x640 (no detections), 267.6ms
Speed: 1.1ms preprocess, 267.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbTR95oEflrz4B5GqAt1tw_180.JPG: 480x640 (no detections), 263.1ms
Speed: 1.0ms preprocess, 263.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbTR95oEflrz4B5GqAt1tw_270.JPG: 480x640 (no detections), 268.6ms
Speed: 1.1ms preprocess, 268.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbVLnv_TsYzyU9gF5p7GvA_0.JPG: 480x640 (no detections), 270.5ms
Speed: 1.1ms preprocess, 270.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbVLnv_TsYzyU9gF5p7GvA_90.JPG: 480x640 (no detections), 265.7ms
Speed: 1.0ms preprocess, 265.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbVLnv_TsYzyU9gF5p7GvA_180.JPG: 480x640 (no detections), 267.0ms
Speed: 1.1ms preprocess, 267.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbVLnv_TsYzyU9gF5p7GvA_270.JPG: 480x640 (no detections), 267.1ms
Speed: 1.1ms preprocess, 267.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbVg2MTjRU36mnao6bXYuw_0.JPG: 480x640 (no detections), 267.4ms
Speed: 1.3ms preprocess, 267.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbVg2MTjRU36mnao6bXYuw_90.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbVg2MTjRU36mnao6bXYuw_180.JPG: 480x640 (no detections), 272.8ms
Speed: 1.0ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbVg2MTjRU36mnao6bXYuw_270.JPG: 480x640 (no detections), 269.4ms
Speed: 1.1ms preprocess, 269.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbWpYOMO-A01AcnSw3kLRQ_0.JPG: 480x640 (no detections), 268.8ms
Speed: 1.1ms preprocess, 268.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbWpYOMO-A01AcnSw3kLRQ_90.JPG: 480x640 (no detections), 274.6ms
Speed: 1.0ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbWpYOMO-A01AcnSw3kLRQ_180.JPG: 480x640 (no detections), 269.1ms
Speed: 1.1ms preprocess, 269.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbWpYOMO-A01AcnSw3kLRQ_270.JPG: 480x640 (no detections), 269.3ms
Speed: 1.0ms preprocess, 269.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wb_3OmEOiKDJLorCJbENvQ_0.JPG: 480x640 (no detections), 267.2ms
Speed: 1.1ms preprocess, 267.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wb_3OmEOiKDJLorCJbENvQ_90.JPG: 480x640 (no detections), 270.9ms
Speed: 1.0ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wb_3OmEOiKDJLorCJbENvQ_180.JPG: 480x640 (no detections), 267.4ms
Speed: 1.0ms preprocess, 267.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wb_3OmEOiKDJLorCJbENvQ_270.JPG: 480x640 (no detections), 266.5ms
Speed: 1.0ms preprocess, 266.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbf9XbSwskpbNnbBWn7rxw_0.JPG: 480x640 (no detections), 275.9ms
Speed: 1.0ms preprocess, 275.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbf9XbSwskpbNnbBWn7rxw_90.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbf9XbSwskpbNnbBWn7rxw_180.JPG: 480x640 (no detections), 266.1ms
Speed: 1.0ms preprocess, 266.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbf9XbSwskpbNnbBWn7rxw_270.JPG: 480x640 (no detections), 268.7ms
Speed: 1.0ms preprocess, 268.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbfSqH24bwE_RvzGIJ8F_A_0.JPG: 480x640 (no detections), 269.1ms
Speed: 1.1ms preprocess, 269.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbfSqH24bwE_RvzGIJ8F_A_90.JPG: 480x640 (no detections), 269.9ms
Speed: 1.2ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbfSqH24bwE_RvzGIJ8F_A_180.JPG: 480x640 (no detections), 269.4ms
Speed: 1.1ms preprocess, 269.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbfSqH24bwE_RvzGIJ8F_A_270.JPG: 480x640 (no detections), 266.4ms
Speed: 1.0ms preprocess, 266.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbh8uh8IXLU-BJGjvMPVFg_0.JPG: 480x640 (no detections), 269.5ms
Speed: 1.1ms preprocess, 269.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbh8uh8IXLU-BJGjvMPVFg_90.JPG: 480x640 (no detections), 265.2ms
Speed: 1.1ms preprocess, 265.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbh8uh8IXLU-BJGjvMPVFg_180.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbh8uh8IXLU-BJGjvMPVFg_270.JPG: 480x640 (no detections), 266.7ms
Speed: 1.1ms preprocess, 266.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbiT7gV_yIWaAzDNUqG_hA_0.JPG: 480x640 (no detections), 267.2ms
Speed: 1.1ms preprocess, 267.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbiT7gV_yIWaAzDNUqG_hA_90.JPG: 480x640 (no detections), 269.9ms
Speed: 1.0ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbiT7gV_yIWaAzDNUqG_hA_180.JPG: 480x640 (no detections), 266.5ms
Speed: 1.1ms preprocess, 266.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbiT7gV_yIWaAzDNUqG_hA_270.JPG: 480x640 (no detections), 272.0ms
Speed: 1.1ms preprocess, 272.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbl3I0PmH7A0u5P8AgR89g_0.JPG: 480x640 (no detections), 270.4ms
Speed: 1.0ms preprocess, 270.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbl3I0PmH7A0u5P8AgR89g_90.JPG: 480x640 (no detections), 267.6ms
Speed: 1.1ms preprocess, 267.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbl3I0PmH7A0u5P8AgR89g_180.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbl3I0PmH7A0u5P8AgR89g_270.JPG: 480x640 (no detections), 267.4ms
Speed: 1.0ms preprocess, 267.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbmg49SnpzE7_F8vDA-i9A_0.JPG: 480x640 (no detections), 271.1ms
Speed: 1.0ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbmg49SnpzE7_F8vDA-i9A_90.JPG: 480x640 (no detections), 266.5ms

Speed: 1.1ms preprocess, 266.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbmg49SnpzE7_F8vDA-i9A_180.JPG: 480x640 (no detections), 271.0ms
Speed: 1.2ms preprocess, 271.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbmg49SnpzE7_F8vDA-i9A_270.JPG: 480x640 (no detections), 266.5ms
Speed: 1.0ms preprocess, 266.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wboowe0mefRLztYM1EH3hA_0.JPG: 480x640 (no detections), 269.8ms
Speed: 1.2ms preprocess, 269.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wboowe0mefRLztYM1EH3hA_90.JPG: 480x640 (no detections), 269.3ms
Speed: 1.1ms preprocess, 269.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wboowe0mefRLztYM1EH3hA_180.JPG: 480x640 (no detections), 267.8ms
Speed: 1.0ms preprocess, 267.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wboowe0mefRLztYM1EH3hA_270.JPG: 480x640 (no detections), 267.7ms
Speed: 1.0ms preprocess, 267.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbpm5e8lxnEr4limxhM7iw_0.JPG: 480x640 (no detections), 292.1ms
Speed: 1.1ms preprocess, 292.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbpm5e8lxnEr4limxhM7iw_90.JPG: 480x640 (no detections), 300.9ms
Speed: 1.3ms preprocess, 300.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbpm5e8lxnEr4limxhM7iw_180.JPG: 480x640 (no detections), 294.3ms
Speed: 1.2ms preprocess, 294.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/B/wbpm5e8lxnEr4limxhM7iw_270.JPG: 480x640 (no detections), 316.9ms
Speed: 1.2ms preprocess, 316.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wc-WpohfSF_ejVRVFXaZrA_0.JPG: 480x640 (no detections), 292.9ms
Speed: 1.3ms preprocess, 292.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wc-WpohfSF_ejVRVFXaZrA_90.JPG: 480x640 (no detections), 284.4ms
Speed: 1.2ms preprocess, 284.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wc-WpohfSF_ejVRVFXaZrA_180.JPG: 480x640 (no detections), 288.3ms
Speed: 1.1ms preprocess, 288.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wc-WpohfSF_ejVRVFXaZrA_270.JPG: 480x640 (no detections), 279.8ms
Speed: 1.3ms preprocess, 279.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wc0ymlxevI_VAMJrUQXw2g_0.JPG: 480x640 (no detections), 272.5ms
Speed: 1.1ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wc0ymlxevI_VAMJrUQXw2g_90.JPG: 480x640 (no detections), 270.0ms
Speed: 1.0ms preprocess, 270.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wc0ymlxevI_VAMJrUQXw2g_180.JPG: 480x640 (no detections), 271.3ms
Speed: 1.2ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wc0ymlxevI_VAMJrUQXw2g_270.JPG: 480x640 (no detections), 267.4ms
Speed: 1.1ms preprocess, 267.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wc4j6wa-jHzr0E74tnm2SA_0.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wc4j6wa-jHzr0E74tnm2SA_90.JPG: 480x640 (no detections), 267.4ms
Speed: 1.0ms preprocess, 267.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wc4j6wa-jHzr0E74tnm2SA_180.JPG: 480x640 (no detections), 267.7ms
Speed: 1.1ms preprocess, 267.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wc4j6wa-jHzr0E74tnm2SA_270.JPG: 480x640 (no detections), 266.9ms
Speed: 1.2ms preprocess, 266.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wc5eJnsGJrL1lWxR6Fukqg_0.JPG: 480x640 (no detections), 267.7ms
Speed: 1.1ms preprocess, 267.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wc5eJnsGJrL1lWxR6Fukqg_90.JPG: 480x640 (no detections), 271.5ms
Speed: 1.0ms preprocess, 271.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wc5eJnsGJrL1lWxR6Fukqg_180.JPG: 480x640 (no detections), 268.1ms
Speed: 1.1ms preprocess, 268.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wc5eJnsGJrL1lWxR6Fukqg_270.JPG: 480x640 (no detections), 269.1ms
Speed: 1.0ms preprocess, 269.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wc69lCs1YmR1EpYsMM-9gw_0.JPG: 480x640 (no detections), 272.8ms
Speed: 1.2ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wc69lCs1YmR1EpYsMM-9gw_90.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wc69lCs1YmR1EpYsMM-9gw_180.JPG: 480x640 (no detections), 268.7ms
Speed: 1.1ms preprocess, 268.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wc69lCs1YmR1EpYsMM-9gw_270.JPG: 480x640 (no detections), 271.2ms
Speed: 1.0ms preprocess, 271.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wc6Gvb_QaZJacPOYSPxV4g_0.JPG: 480x640 (no detections), 268.9ms
Speed: 1.1ms preprocess, 268.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wc6Gvb_QaZJacPOYSPxV4g_90.JPG: 480x640 (no detections), 269.4ms
Speed: 1.0ms preprocess, 269.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wc6Gvb_QaZJacPOYSPxV4g_180.JPG: 480x640 (no detections), 268.9ms
Speed: 1.3ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wc6Gvb_QaZJacPOYSPxV4g_270.JPG: 480x640 (no detections), 272.1ms
Speed: 1.0ms preprocess, 272.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcCAf1PaahKGPzHov_Q52w_0.JPG: 480x640 1 Waste, 267.7ms
Speed: 1.0ms preprocess, 267.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcCAf1PaahKGPzHov_Q52w_90.JPG: 480x640 (no detections), 272.5ms
Speed: 1.1ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcCAf1PaahKGPzHov_Q52w_180.JPG: 480x640 (no detections), 270.5ms
Speed: 1.2ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcCAf1PaahKGPzHov_Q52w_270.JPG: 480x640 (no detections), 266.6ms
Speed: 1.1ms preprocess, 266.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcIbQN93-MWFkmQkWUpgGg_0.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcIbQN93-MWFkmQkWUpgGg_90.JPG: 480x640 (no detections), 273.4ms
Speed: 1.0ms preprocess, 273.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcIbQN93-MWFkmQkWUpgGg_180.JPG: 480x640 (no detections), 266.6ms
Speed: 1.1ms preprocess, 266.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcIbQN93-MWFkmQkWUpgGg_270.JPG: 480x640 (no detections), 271.5ms
Speed: 1.1ms preprocess, 271.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcIlXQ3O72OP33SHnyRGmg_0.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcIlXQ3O72OP33SHnyRGmg_90.JPG: 480x640 (no detections), 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcIlXQ3O72OP33SHnyRGmg_180.JPG: 480x640 (no detections), 267.3ms
Speed: 1.0ms preprocess, 267.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcIlXQ3O72OP33SHnyRGmg_270.JPG: 480x640 (no detections), 270.4ms
Speed: 1.0ms preprocess, 270.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcJ7uoM4ZfpHrI7LouJctw_0.JPG: 480x640 (no detections), 268.1ms
Speed: 1.0ms preprocess, 268.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcJ7uoM4ZfpHrI7LouJctw_90.JPG: 480x640 (no detections), 268.6ms
Speed: 1.0ms preprocess, 268.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcJ7uoM4ZfpHrI7LouJctw_180.JPG: 480x640 (no detections), 266.5ms
Speed: 1.1ms preprocess, 266.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcJ7uoM4ZfpHrI7LouJctw_270.JPG: 480x640 (no detections), 283.5ms
Speed: 1.0ms preprocess, 283.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcOJQkf4ZbPjLOOu3k1Szw_0.JPG: 480x640 (no detections), 268.6ms
Speed: 1.1ms preprocess, 268.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcOJQkf4ZbPjLOOu3k1Szw_90.JPG: 480x640 (no detections), 272.0ms
Speed: 1.1ms preprocess, 272.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcOJQkf4ZbPjLOOu3k1Szw_180.JPG: 480x640 (no detections), 273.2ms
Speed: 1.0ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcOJQkf4ZbPjLOOu3k1Szw_270.JPG: 480x640 (no detections), 268.3ms
Speed: 1.0ms preprocess, 268.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcOrC4RRxIqrmJTIUKARmQ_0.JPG: 480x640 (no detections), 271.2ms
Speed: 1.0ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcOrC4RRxIqrmJTIUKARmQ_90.JPG: 480x640 (no detections), 266.3ms
Speed: 1.1ms preprocess, 266.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcOrC4RRxIqrmJTIUKARmQ_180.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcOrC4RRxIqrmJTIUKARmQ_270.JPG: 480x640 (no detections), 268.8ms
Speed: 1.0ms preprocess, 268.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcRfja--7hDBPL_eq5DLrg_0.JPG: 480x640 (no detections), 267.1ms
Speed: 1.2ms preprocess, 267.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcRfja--7hDBPL_eq5DLrg_90.JPG: 480x640 (no detections), 269.8ms
Speed: 1.0ms preprocess, 269.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcRfja--7hDBPL_eq5DLrg_180.JPG: 480x640 (no detections), 266.3ms
Speed: 1.1ms preprocess, 266.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcRfja--7hDBPL_eq5DLrg_270.JPG: 480x640 (no detections), 267.8ms
Speed: 1.3ms preprocess, 267.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcTncxgVQcveaxwaZE0wPA_0.JPG: 480x640 (no detections), 268.6ms
Speed: 1.0ms preprocess, 268.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcTncxgVQcveaxwaZE0wPA_90.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcTncxgVQcveaxwaZE0wPA_180.JPG: 480x640 (no detections), 268.4ms
Speed: 1.0ms preprocess, 268.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcTncxgVQcveaxwaZE0wPA_270.JPG: 480x640 (no detections), 268.4ms
Speed: 1.0ms preprocess, 268.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcZxwmyyvORn9dV87usg1Q_0.JPG: 480x640 (no detections), 269.2ms

Speed: 1.1ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcZxwmyyvORn9dV87usg1Q_90.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcZxwmyyvORn9dV87usg1Q_180.JPG: 480x640 (no detections), 265.4ms
Speed: 1.1ms preprocess, 265.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcZxwmyyvORn9dV87usg1Q_270.JPG: 480x640 (no detections), 271.3ms
Speed: 1.0ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcbU5T4-h33u7m-Ij3dYjw_0.JPG: 480x640 (no detections), 273.2ms
Speed: 1.1ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcbU5T4-h33u7m-Ij3dYjw_90.JPG: 480x640 (no detections), 267.0ms
Speed: 1.0ms preprocess, 267.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcbU5T4-h33u7m-Ij3dYjw_180.JPG: 480x640 (no detections), 269.8ms
Speed: 1.1ms preprocess, 269.8ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcbU5T4-h33u7m-Ij3dYjw_270.JPG: 480x640 (no detections), 268.1ms
Speed: 1.0ms preprocess, 268.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcfGzqHTA0EUnZ0S98TmYQ_0.JPG: 480x640 (no detections), 268.0ms
Speed: 1.0ms preprocess, 268.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcfGzqHTA0EUnZ0S98TmYQ_90.JPG: 480x640 (no detections), 261.5ms
Speed: 1.0ms preprocess, 261.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcfGzqHTA0EUnZ0S98TmYQ_180.JPG: 480x640 (no detections), 259.0ms
Speed: 1.0ms preprocess, 259.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcfGzqHTA0EUnZ0S98TmYQ_270.JPG: 480x640 1 Waste, 261.6ms
Speed: 1.1ms preprocess, 261.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wchJxSYHfFq_NIHpX890gg_0.JPG: 480x640 (no detections), 263.9ms
Speed: 1.0ms preprocess, 263.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wchJxSYHfFq_NIHpX890gg_90.JPG: 480x640 (no detections), 266.8ms
Speed: 1.0ms preprocess, 266.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wchJxSYHfFq_NIHpX890gg_180.JPG: 480x640 1 Waste, 267.5ms
Speed: 1.0ms preprocess, 267.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wchJxSYHfFq_NIHpX890gg_270.JPG: 480x640 (no detections), 271.8ms
Speed: 1.2ms preprocess, 271.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcn59Sj9amtmDPimAPAqBQ_0.JPG: 480x640 (no detections), 269.5ms
Speed: 1.1ms preprocess, 269.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcn59Sj9amtmDPimAPAqBQ_90.JPG: 480x640 (no detections), 268.2ms
Speed: 1.1ms preprocess, 268.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcn59Sj9amtmDPimAPAqBQ_180.JPG: 480x640 (no detections), 270.9ms
Speed: 1.0ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcn59Sj9amtmDPimAPAqBQ_270.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcnOZheFt1S5v_MbuxvvYQ_0.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcnOZheFt1S5v_MbuxvvYQ_90.JPG: 480x640 (no detections), 269.1ms
Speed: 1.1ms preprocess, 269.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcnOZheFt1S5v_MbuxvvYQ_180.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcnOZheFt1S5v_MbuxvvYQ_270.JPG: 480x640 (no detections), 267.3ms
Speed: 1.0ms preprocess, 267.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcnhkz88yL1GcdFYLU1lWw_0.JPG: 480x640 (no detections), 268.8ms
Speed: 1.1ms preprocess, 268.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcnhkz88yL1GcdFYLU1lWw_90.JPG: 480x640 (no detections), 266.5ms
Speed: 1.1ms preprocess, 266.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcnhkz88yL1GcdFYLU1lWw_180.JPG: 480x640 (no detections), 270.9ms
Speed: 1.0ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcnhkz88yL1GcdFYLU1lWw_270.JPG: 480x640 (no detections), 265.3ms
Speed: 1.1ms preprocess, 265.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcsnuvqFUv0PowBoWJOjkA_0.JPG: 480x640 (no detections), 267.5ms
Speed: 1.0ms preprocess, 267.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcsnuvqFUv0PowBoWJOjkA_90.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcsnuvqFUv0PowBoWJOjkA_180.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcsnuvqFUv0PowBoWJOjkA_270.JPG: 480x640 (no detections), 273.1ms
Speed: 1.1ms preprocess, 273.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcu9lZ_lA_QFZFTiP_7MxA_0.JPG: 480x640 (no detections), 268.3ms
Speed: 1.0ms preprocess, 268.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcu9lZ_lA_QFZFTiP_7MxA_90.JPG: 480x640 1 Waste, 269.4ms
Speed: 1.0ms preprocess, 269.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcu9lZ_lA_QFZFTiP_7MxA_180.JPG: 480x640 (no detections), 268.7ms
Speed: 1.1ms preprocess, 268.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcu9lZ_lA_QFZFTiP_7MxA_270.JPG: 480x640 (no detections), 269.6ms
Speed: 1.2ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcvmpLj-MyBN65NxMbp3Zw_0.JPG: 480x640 (no detections), 266.8ms
Speed: 1.1ms preprocess, 266.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcvmpLj-MyBN65NxMbp3Zw_90.JPG: 480x640 (no detections), 267.5ms
Speed: 1.0ms preprocess, 267.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcvmpLj-MyBN65NxMbp3Zw_180.JPG: 480x640 (no detections), 271.3ms
Speed: 1.2ms preprocess, 271.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcvmpLj-MyBN65NxMbp3Zw_270.JPG: 480x640 (no detections), 266.0ms
Speed: 1.0ms preprocess, 266.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcy6mJr7D1pEOBi4JHh63w_0.JPG: 480x640 (no detections), 268.9ms
Speed: 1.2ms preprocess, 268.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcy6mJr7D1pEOBi4JHh63w_90.JPG: 480x640 (no detections), 265.0ms
Speed: 1.1ms preprocess, 265.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcy6mJr7D1pEOBi4JHh63w_180.JPG: 480x640 (no detections), 269.5ms
Speed: 1.0ms preprocess, 269.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wcy6mJr7D1pEOBi4JHh63w_270.JPG: 480x640 (no detections), 269.2ms
Speed: 1.0ms preprocess, 269.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wczL8uyAcXDaV4oIeJcpXw_0.JPG: 480x640 (no detections), 267.7ms
Speed: 1.0ms preprocess, 267.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wczL8uyAcXDaV4oIeJcpXw_90.JPG: 480x640 (no detections), 274.6ms
Speed: 1.0ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wczL8uyAcXDaV4oIeJcpXw_180.JPG: 480x640 (no detections), 269.0ms
Speed: 1.1ms preprocess, 269.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wczL8uyAcXDaV4oIeJcpXw_270.JPG: 480x640 (no detections), 267.8ms
Speed: 1.5ms preprocess, 267.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wczyeIEqIQN5wbGe-RyMDg_0.JPG: 480x640 (no detections), 271.5ms
Speed: 1.0ms preprocess, 271.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wczyeIEqIQN5wbGe-RyMDg_90.JPG: 480x640 (no detections), 277.5ms
Speed: 1.1ms preprocess, 277.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wczyeIEqIQN5wbGe-RyMDg_180.JPG: 480x640 (no detections), 269.6ms
Speed: 1.0ms preprocess, 269.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/C/wczyeIEqIQN5wbGe-RyMDg_270.JPG: 480x640 (no detections), 278.2ms
Speed: 1.0ms preprocess, 278.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wd3Ov7ZV2vAHRZ9JbVJTaQ_0.JPG: 480x640 (no detections), 270.2ms
Speed: 1.0ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wd3Ov7ZV2vAHRZ9JbVJTaQ_90.JPG: 480x640 (no detections), 265.8ms
Speed: 1.1ms preprocess, 265.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wd3Ov7ZV2vAHRZ9JbVJTaQ_180.JPG: 480x640 (no detections), 277.6ms
Speed: 1.0ms preprocess, 277.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wd3Ov7ZV2vAHRZ9JbVJTaQ_270.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wd48tfpe6ijYnLKud4TZPQ_0.JPG: 480x640 (no detections), 263.9ms
Speed: 1.1ms preprocess, 263.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wd48tfpe6ijYnLKud4TZPQ_90.JPG: 480x640 (no detections), 259.4ms
Speed: 0.9ms preprocess, 259.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wd48tfpe6ijYnLKud4TZPQ_180.JPG: 480x640 (no detections), 281.7ms
Speed: 1.1ms preprocess, 281.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wd48tfpe6ijYnLKud4TZPQ_270.JPG: 480x640 (no detections), 288.4ms
Speed: 3.9ms preprocess, 288.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wd4oByDcuwxcySAzg-cHqw_0.JPG: 480x640 (no detections), 265.0ms
Speed: 1.0ms preprocess, 265.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wd4oByDcuwxcySAzg-cHqw_90.JPG: 480x640 (no detections), 266.7ms
Speed: 1.1ms preprocess, 266.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wd4oByDcuwxcySAzg-cHqw_180.JPG: 480x640 (no detections), 299.5ms
Speed: 1.1ms preprocess, 299.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wd4oByDcuwxcySAzg-cHqw_270.JPG: 480x640 (no detections), 267.3ms
Speed: 1.2ms preprocess, 267.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wd7xg8f866WPXt_V0gudCw_0.JPG: 480x640 (no detections), 259.1ms
Speed: 1.1ms preprocess, 259.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wd7xg8f866WPXt_V0gudCw_90.JPG: 480x640 (no detections), 265.4ms
Speed: 1.0ms preprocess, 265.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wd7xg8f866WPXt_V0gudCw_180.JPG: 480x640 1 Waste, 267.1ms
Speed: 1.1ms preprocess, 267.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wd7xg8f866WPXt_V0gudCw_270.JPG: 480x640 (no detections), 267.8ms

Speed: 1.0ms preprocess, 267.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wd9ZQ8Q_B1vd1wo6XXN9sA_0.JPG: 480x640 (no detections), 264.2ms
Speed: 1.1ms preprocess, 264.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wd9ZQ8Q_B1vd1wo6XXN9sA_90.JPG: 480x640 (no detections), 271.3ms
Speed: 1.0ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wd9ZQ8Q_B1vd1wo6XXN9sA_180.JPG: 480x640 (no detections), 275.5ms
Speed: 1.1ms preprocess, 275.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wd9ZQ8Q_B1vd1wo6XXN9sA_270.JPG: 480x640 (no detections), 269.9ms
Speed: 1.0ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdBk4zgBwUyRZx3eJW1AgQ_0.JPG: 480x640 (no detections), 268.7ms
Speed: 1.0ms preprocess, 268.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdBk4zgBwUyRZx3eJW1AgQ_90.JPG: 480x640 (no detections), 266.9ms
Speed: 1.2ms preprocess, 266.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdBk4zgBwUyRZx3eJW1AgQ_180.JPG: 480x640 (no detections), 267.1ms
Speed: 1.1ms preprocess, 267.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdBk4zgBwUyRZx3eJW1AgQ_270.JPG: 480x640 (no detections), 272.4ms
Speed: 1.0ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdDepo0CTIderBJZpAFdtQ_0.JPG: 480x640 (no detections), 267.1ms
Speed: 1.0ms preprocess, 267.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdDepo0CTIderBJZpAFdtQ_90.JPG: 480x640 (no detections), 265.8ms
Speed: 1.0ms preprocess, 265.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdDepo0CTIderBJZpAFdtQ_180.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdDepo0CTIderBJZpAFdtQ_270.JPG: 480x640 (no detections), 273.6ms
Speed: 1.2ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdIrkacA6y8T7DZXkH7mCQ_0.JPG: 480x640 (no detections), 268.8ms
Speed: 1.1ms preprocess, 268.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdIrkacA6y8T7DZXkH7mCQ_90.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdIrkacA6y8T7DZXkH7mCQ_180.JPG: 480x640 (no detections), 266.5ms
Speed: 1.0ms preprocess, 266.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdIrkacA6y8T7DZXkH7mCQ_270.JPG: 480x640 1 Waste, 268.2ms
Speed: 1.1ms preprocess, 268.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdJT_YJvgWCOkDklfe3RSA_0.JPG: 480x640 (no detections), 267.4ms
Speed: 1.1ms preprocess, 267.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdJT_YJvgWCOkDklfe3RSA_90.JPG: 480x640 (no detections), 267.6ms
Speed: 1.1ms preprocess, 267.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdJT_YJvgWCOkDklfe3RSA_180.JPG: 480x640 (no detections), 270.0ms
Speed: 1.0ms preprocess, 270.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdJT_YJvgWCOkDklfe3RSA_270.JPG: 480x640 (no detections), 266.4ms
Speed: 1.0ms preprocess, 266.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdJcbT8oNUPA76ByjmAdWw_0.JPG: 480x640 (no detections), 268.5ms
Speed: 1.0ms preprocess, 268.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdJcbT8oNUPA76ByjmAdWw_90.JPG: 480x640 (no detections), 265.7ms
Speed: 1.0ms preprocess, 265.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdJcbT8oNUPA76ByjmAdWw_180.JPG: 480x640 (no detections), 269.3ms
Speed: 1.1ms preprocess, 269.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdJcbT8oNUPA76ByjmAdWw_270.JPG: 480x640 (no detections), 266.7ms
Speed: 1.1ms preprocess, 266.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdMSoldXLysu1mTKqx3stQ_0.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdMSoldXLysu1mTKqx3stQ_90.JPG: 480x640 (no detections), 266.8ms
Speed: 1.1ms preprocess, 266.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdMSoldXLysu1mTKqx3stQ_180.JPG: 480x640 (no detections), 269.7ms
Speed: 1.0ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdMSoldXLysu1mTKqx3stQ_270.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdQvquAj174eckobzAKfew_0.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdQvquAj174eckobzAKfew_90.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdQvquAj174eckobzAKfew_180.JPG: 480x640 (no detections), 268.8ms
Speed: 1.2ms preprocess, 268.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdQvquAj174eckobzAKfew_270.JPG: 480x640 (no detections), 272.1ms
Speed: 1.1ms preprocess, 272.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdSHnBiNIWB2Or-nHZCjCg_0.JPG: 480x640 (no detections), 269.9ms
Speed: 1.0ms preprocess, 269.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdSHnBiNIWB2Or-nHZCjCg_90.JPG: 480x640 (no detections), 267.6ms
Speed: 1.2ms preprocess, 267.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdSHnBiNIWB2Or-nHZCjCg_180.JPG: 480x640 (no detections), 268.0ms
Speed: 1.1ms preprocess, 268.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdSHnBiNIWB2Or-nHZCjCg_270.JPG: 480x640 (no detections), 265.9ms
Speed: 1.1ms preprocess, 265.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdZVZ8OZpH-XrTd4ub1hSg_0.JPG: 480x640 (no detections), 266.3ms
Speed: 1.1ms preprocess, 266.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdZVZ8OZpH-XrTd4ub1hSg_90.JPG: 480x640 (no detections), 266.4ms
Speed: 1.0ms preprocess, 266.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdZVZ8OZpH-XrTd4ub1hSg_180.JPG: 480x640 (no detections), 268.0ms
Speed: 1.0ms preprocess, 268.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdZVZ8OZpH-XrTd4ub1hSg_270.JPG: 480x640 (no detections), 272.5ms
Speed: 1.0ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wd_gA4AIku7vTzj2EgALPg_0.JPG: 480x640 (no detections), 268.7ms
Speed: 1.1ms preprocess, 268.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wd_gA4AIku7vTzj2EgALPg_90.JPG: 480x640 (no detections), 268.3ms
Speed: 1.0ms preprocess, 268.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wd_gA4AIku7vTzj2EgALPg_180.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wd_gA4AIku7vTzj2EgALPg_270.JPG: 480x640 (no detections), 269.0ms
Speed: 1.1ms preprocess, 269.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdapzAmZDFd95DMNdakqEA_0.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdapzAmZDFd95DMNdakqEA_90.JPG: 480x640 (no detections), 266.0ms
Speed: 1.0ms preprocess, 266.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdapzAmZDFd95DMNdakqEA_180.JPG: 480x640 (no detections), 268.4ms
Speed: 1.1ms preprocess, 268.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdapzAmZDFd95DMNdakqEA_270.JPG: 480x640 (no detections), 272.3ms
Speed: 1.3ms preprocess, 272.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdjCVuYBeIxCBJIzlIb3DA_0.JPG: 480x640 (no detections), 273.9ms
Speed: 1.1ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdjCVuYBeIxCBJIzlIb3DA_90.JPG: 480x640 (no detections), 269.2ms
Speed: 1.0ms preprocess, 269.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdjCVuYBeIxCBJIzlIb3DA_180.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdjCVuYBeIxCBJIzlIb3DA_270.JPG: 480x640 (no detections), 268.8ms
Speed: 1.0ms preprocess, 268.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdjTylsFjM2eVt6wWdW3ww_0.JPG: 480x640 (no detections), 268.8ms
Speed: 1.2ms preprocess, 268.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdjTylsFjM2eVt6wWdW3ww_90.JPG: 480x640 (no detections), 275.4ms
Speed: 1.0ms preprocess, 275.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdjTylsFjM2eVt6wWdW3ww_180.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdjTylsFjM2eVt6wWdW3ww_270.JPG: 480x640 (no detections), 268.1ms
Speed: 1.1ms preprocess, 268.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdkxzIcKdnqm75kYKzyfvg_0.JPG: 480x640 (no detections), 268.9ms
Speed: 1.1ms preprocess, 268.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdkxzIcKdnqm75kYKzyfvg_90.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdkxzIcKdnqm75kYKzyfvg_180.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdkxzIcKdnqm75kYKzyfvg_270.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdnRDhmQWJ910bPjb7kUQA_0.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdnRDhmQWJ910bPjb7kUQA_90.JPG: 480x640 (no detections), 269.5ms
Speed: 1.1ms preprocess, 269.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdnRDhmQWJ910bPjb7kUQA_180.JPG: 480x640 (no detections), 268.5ms
Speed: 1.2ms preprocess, 268.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdnRDhmQWJ910bPjb7kUQA_270.JPG: 480x640 (no detections), 268.8ms
Speed: 1.0ms preprocess, 268.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdoFDGxYAN-DB4M0onikrA_0.JPG: 480x640 (no detections), 269.3ms
Speed: 1.2ms preprocess, 269.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdoFDGxYAN-DB4M0onikrA_90.JPG: 480x640 (no detections), 267.8ms
Speed: 1.0ms preprocess, 267.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdoFDGxYAN-DB4M0onikrA_180.JPG: 480x640 (no detections), 268.7ms

Speed: 1.0ms preprocess, 268.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdoFDGxYAN-DB4M0onikrA_270.JPG: 480x640 (no detections), 269.1ms
Speed: 1.0ms preprocess, 269.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdpd4epm9SUAkoFD2B0O1A_0.JPG: 480x640 (no detections), 269.2ms
Speed: 1.1ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdpd4epm9SUAkoFD2B0O1A_90.JPG: 480x640 (no detections), 268.3ms
Speed: 1.1ms preprocess, 268.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdpd4epm9SUAkoFD2B0O1A_180.JPG: 480x640 (no detections), 270.3ms
Speed: 1.0ms preprocess, 270.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdpd4epm9SUAkoFD2B0O1A_270.JPG: 480x640 (no detections), 269.6ms
Speed: 1.0ms preprocess, 269.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdqd7EOPxhDF6Vf4gzfwrQ_0.JPG: 480x640 (no detections), 268.2ms
Speed: 1.2ms preprocess, 268.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdqd7EOPxhDF6Vf4gzfwrQ_90.JPG: 480x640 (no detections), 270.9ms
Speed: 1.1ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdqd7EOPxhDF6Vf4gzfwrQ_180.JPG: 480x640 (no detections), 262.2ms
Speed: 1.1ms preprocess, 262.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdqd7EOPxhDF6Vf4gzfwrQ_270.JPG: 480x640 (no detections), 268.8ms
Speed: 1.1ms preprocess, 268.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdzq3kvXt_uwgnSZffAyqw_0.JPG: 480x640 1 Waste, 270.3ms
Speed: 1.2ms preprocess, 270.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdzq3kvXt_uwgnSZffAyqw_90.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdzq3kvXt_uwgnSZffAyqw_180.JPG: 480x640 (no detections), 267.3ms
Speed: 1.1ms preprocess, 267.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/d/wdzq3kvXt_uwgnSZffAyqw_270.JPG: 480x640 (no detections), 267.8ms
Speed: 1.1ms preprocess, 267.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/we0bVp-sP_k1DS5YplDEpA_0.JPG: 480x640 (no detections), 268.9ms
Speed: 1.1ms preprocess, 268.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/we0bVp-sP_k1DS5YplDEpA_90.JPG: 480x640 (no detections), 265.8ms
Speed: 1.0ms preprocess, 265.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/we0bVp-sP_k1DS5YplDEpA_180.JPG: 480x640 (no detections), 267.8ms
Speed: 1.0ms preprocess, 267.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/we0bVp-sP_k1DS5YplDEpA_270.JPG: 480x640 (no detections), 273.3ms
Speed: 1.0ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/we2phNhiF0SILUQVGWENFQ_0.JPG: 480x640 (no detections), 269.1ms
Speed: 1.1ms preprocess, 269.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/we2phNhiF0SILUQVGWENFQ_90.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/we2phNhiF0SILUQVGWENFQ_180.JPG: 480x640 (no detections), 268.9ms
Speed: 1.1ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/we2phNhiF0SILUQVGWENFQ_270.JPG: 480x640 (no detections), 272.4ms
Speed: 1.1ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/we4R_f1XzLsltEmoiMBDXg_0.JPG: 480x640 1 Waste, 267.1ms
Speed: 1.1ms preprocess, 267.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/we4R_f1XzLsltEmoiMBDXg_90.JPG: 480x640 (no detections), 267.2ms
Speed: 1.1ms preprocess, 267.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/we4R_f1XzLsltEmoiMBDXg_180.JPG: 480x640 (no detections), 269.4ms
Speed: 1.1ms preprocess, 269.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/we4R_f1XzLsltEmoiMBDXg_270.JPG: 480x640 1 Waste, 264.2ms
Speed: 1.1ms preprocess, 264.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/we9xWyqqcXIZWyYVGV1ykQ_0.JPG: 480x640 (no detections), 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/we9xWyqqcXIZWyYVGV1ykQ_90.JPG: 480x640 (no detections), 271.1ms
Speed: 1.0ms preprocess, 271.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/we9xWyqqcXIZWyYVGV1ykQ_180.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/we9xWyqqcXIZWyYVGV1ykQ_270.JPG: 480x640 (no detections), 266.2ms
Speed: 1.1ms preprocess, 266.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weDIBYdl4hZKU8Te1ZRF2Q_0.JPG: 480x640 (no detections), 270.6ms
Speed: 1.0ms preprocess, 270.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weDIBYdl4hZKU8Te1ZRF2Q_90.JPG: 480x640 (no detections), 272.3ms
Speed: 1.1ms preprocess, 272.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weDIBYdl4hZKU8Te1ZRF2Q_180.JPG: 480x640 (no detections), 276.5ms
Speed: 1.0ms preprocess, 276.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weDIBYdl4hZKU8Te1ZRF2Q_270.JPG: 480x640 (no detections), 268.8ms
Speed: 1.1ms preprocess, 268.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weE1TuhVYhm6Cyjl5kabRw_0.JPG: 480x640 (no detections), 267.4ms
Speed: 1.0ms preprocess, 267.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weE1TuhVYhm6Cyjl5kabRw_90.JPG: 480x640 (no detections), 269.4ms
Speed: 1.1ms preprocess, 269.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weE1TuhVYhm6Cyjl5kabRw_180.JPG: 480x640 (no detections), 269.6ms
Speed: 1.0ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weE1TuhVYhm6Cyjl5kabRw_270.JPG: 480x640 (no detections), 267.8ms
Speed: 1.0ms preprocess, 267.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weF88toZbtTyhseWV8T67w_0.JPG: 480x640 (no detections), 268.6ms
Speed: 1.0ms preprocess, 268.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weF88toZbtTyhseWV8T67w_90.JPG: 480x640 (no detections), 269.6ms
Speed: 1.1ms preprocess, 269.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weF88toZbtTyhseWV8T67w_180.JPG: 480x640 (no detections), 268.2ms
Speed: 1.1ms preprocess, 268.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weF88toZbtTyhseWV8T67w_270.JPG: 480x640 (no detections), 273.4ms
Speed: 1.0ms preprocess, 273.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weIPDcy9WqApue9DHN9ARQ_0.JPG: 480x640 (no detections), 266.9ms
Speed: 1.0ms preprocess, 266.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weIPDcy9WqApue9DHN9ARQ_90.JPG: 480x640 (no detections), 270.3ms
Speed: 1.1ms preprocess, 270.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weIPDcy9WqApue9DHN9ARQ_180.JPG: 480x640 (no detections), 268.6ms
Speed: 1.1ms preprocess, 268.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weIPDcy9WqApue9DHN9ARQ_270.JPG: 480x640 1 Waste, 274.1ms
Speed: 1.0ms preprocess, 274.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weJNBuSgAweVT_u_ZlKMyA_0.JPG: 480x640 (no detections), 268.6ms
Speed: 1.1ms preprocess, 268.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weJNBuSgAweVT_u_ZlKMyA_90.JPG: 480x640 (no detections), 270.7ms
Speed: 1.0ms preprocess, 270.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weJNBuSgAweVT_u_ZlKMyA_180.JPG: 480x640 (no detections), 268.9ms
Speed: 1.0ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weJNBuSgAweVT_u_ZlKMyA_270.JPG: 480x640 (no detections), 270.6ms
Speed: 1.0ms preprocess, 270.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weLGcdsZJgpoP0w0XA6rlg_0.JPG: 480x640 (no detections), 271.0ms
Speed: 1.1ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weLGcdsZJgpoP0w0XA6rlg_90.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weLGcdsZJgpoP0w0XA6rlg_180.JPG: 480x640 (no detections), 272.1ms
Speed: 1.0ms preprocess, 272.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weLGcdsZJgpoP0w0XA6rlg_270.JPG: 480x640 (no detections), 269.1ms
Speed: 1.1ms preprocess, 269.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weLmJIg1Tgb3Bb0m7t8-cw_0.JPG: 480x640 (no detections), 268.2ms
Speed: 1.1ms preprocess, 268.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weLmJIg1Tgb3Bb0m7t8-cw_90.JPG: 480x640 (no detections), 267.9ms
Speed: 1.1ms preprocess, 267.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weLmJIg1Tgb3Bb0m7t8-cw_180.JPG: 480x640 (no detections), 269.2ms
Speed: 1.1ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weLmJIg1Tgb3Bb0m7t8-cw_270.JPG: 480x640 (no detections), 267.2ms
Speed: 1.1ms preprocess, 267.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weMaB57UAZq8sQBUzX1Mog_0.JPG: 480x640 (no detections), 266.1ms
Speed: 1.0ms preprocess, 266.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weMaB57UAZq8sQBUzX1Mog_90.JPG: 480x640 (no detections), 266.9ms
Speed: 1.1ms preprocess, 266.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weMaB57UAZq8sQBUzX1Mog_180.JPG: 480x640 (no detections), 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weMaB57UAZq8sQBUzX1Mog_270.JPG: 480x640 1 Waste, 269.9ms
Speed: 1.2ms preprocess, 269.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/wePccYLMavxvZmk2L_jFLg_0.JPG: 480x640 (no detections), 267.3ms
Speed: 1.1ms preprocess, 267.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/wePccYLMavxvZmk2L_jFLg_90.JPG: 480x640 (no detections), 267.4ms
Speed: 1.0ms preprocess, 267.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/wePccYLMavxvZmk2L_jFLg_180.JPG: 480x640 (no detections), 271.3ms
Speed: 1.0ms preprocess, 271.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/wePccYLMavxvZmk2L_jFLg_270.JPG: 480x640 (no detections), 267.0ms
Speed: 0.9ms preprocess, 267.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weSTTECz8EQuM498neAnDg_0.JPG: 480x640 (no detections), 265.3ms
Speed: 1.0ms preprocess, 265.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weSTTECz8EQuM498neAnDg_90.JPG: 480x640 (no detections), 262.3ms

Speed: 1.1ms preprocess, 262.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weSTTECz8EQuM498neAnDg_180.JPG: 480x640 (no detections), 267.9ms
Speed: 1.1ms preprocess, 267.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weSTTECz8EQuM498neAnDg_270.JPG: 480x640 (no detections), 270.4ms
Speed: 1.1ms preprocess, 270.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weULQP1Bx1ZEGFhsuDU5cQ_0.JPG: 480x640 (no detections), 271.5ms
Speed: 1.1ms preprocess, 271.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weULQP1Bx1ZEGFhsuDU5cQ_90.JPG: 480x640 (no detections), 269.5ms
Speed: 1.0ms preprocess, 269.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weULQP1Bx1ZEGFhsuDU5cQ_180.JPG: 480x640 (no detections), 267.3ms
Speed: 1.1ms preprocess, 267.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weULQP1Bx1ZEGFhsuDU5cQ_270.JPG: 480x640 (no detections), 265.1ms
Speed: 1.1ms preprocess, 265.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weVmbFNjsg-1cm3sWTrX4A_0.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weVmbFNjsg-1cm3sWTrX4A_90.JPG: 480x640 (no detections), 269.0ms
Speed: 1.1ms preprocess, 269.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weVmbFNjsg-1cm3sWTrX4A_180.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weVmbFNjsg-1cm3sWTrX4A_270.JPG: 480x640 (no detections), 274.2ms
Speed: 1.0ms preprocess, 274.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weWooBbDh59UaENGrP9Vsw_0.JPG: 480x640 (no detections), 266.8ms
Speed: 1.0ms preprocess, 266.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weWooBbDh59UaENGrP9Vsw_90.JPG: 480x640 (no detections), 266.1ms
Speed: 1.1ms preprocess, 266.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weWooBbDh59UaENGrP9Vsw_180.JPG: 480x640 (no detections), 269.6ms
Speed: 1.1ms preprocess, 269.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weWooBbDh59UaENGrP9Vsw_270.JPG: 480x640 (no detections), 267.4ms
Speed: 1.1ms preprocess, 267.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/wei0kitf-fzN-fgxMEbj5Q_0.JPG: 480x640 (no detections), 269.1ms
Speed: 1.1ms preprocess, 269.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/wei0kitf-fzN-fgxMEbj5Q_90.JPG: 480x640 (no detections), 268.5ms
Speed: 1.1ms preprocess, 268.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/wei0kitf-fzN-fgxMEbj5Q_180.JPG: 480x640 (no detections), 274.0ms
Speed: 1.1ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/wei0kitf-fzN-fgxMEbj5Q_270.JPG: 480x640 (no detections), 270.0ms
Speed: 1.0ms preprocess, 270.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/wei2MAaJZuHonfN9Ewn0HA_0.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/wei2MAaJZuHonfN9Ewn0HA_90.JPG: 480x640 (no detections), 269.2ms
Speed: 1.0ms preprocess, 269.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/wei2MAaJZuHonfN9Ewn0HA_180.JPG: 480x640 (no detections), 269.0ms
Speed: 1.0ms preprocess, 269.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/wei2MAaJZuHonfN9Ewn0HA_270.JPG: 480x640 (no detections), 270.9ms
Speed: 1.1ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weoDCDoFM6ZjKlpv0AheHw_0.JPG: 480x640 (no detections), 267.1ms
Speed: 1.0ms preprocess, 267.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weoDCDoFM6ZjKlpv0AheHw_90.JPG: 480x640 (no detections), 273.1ms
Speed: 1.1ms preprocess, 273.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weoDCDoFM6ZjKlpv0AheHw_180.JPG: 480x640 (no detections), 265.1ms
Speed: 1.2ms preprocess, 265.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weoDCDoFM6ZjKlpv0AheHw_270.JPG: 480x640 (no detections), 269.8ms
Speed: 1.0ms preprocess, 269.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weugfC78F8h8BRmAzipTOw_0.JPG: 480x640 1 Waste, 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weugfC78F8h8BRmAzipTOw_90.JPG: 480x640 1 Waste, 267.9ms
Speed: 1.0ms preprocess, 267.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weugfC78F8h8BRmAzipTOw_180.JPG: 480x640 (no detections), 267.0ms
Speed: 1.0ms preprocess, 267.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/weugfC78F8h8BRmAzipTOw_270.JPG: 480x640 (no detections), 265.2ms
Speed: 1.1ms preprocess, 265.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/wewLlFzl8amzAluhBnc5SQ_0.JPG: 480x640 (no detections), 272.0ms
Speed: 1.1ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/wewLlFzl8amzAluhBnc5SQ_90.JPG: 480x640 (no detections), 267.2ms
Speed: 1.1ms preprocess, 267.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/wewLlFzl8amzAluhBnc5SQ_180.JPG: 480x640 (no detections), 266.3ms
Speed: 1.0ms preprocess, 266.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/wewLlFzl8amzAluhBnc5SQ_270.JPG: 480x640 (no detections), 265.2ms
Speed: 1.0ms preprocess, 265.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/wexo761ErEhSsZyUIrt11g_0.JPG: 480x640 (no detections), 271.0ms
Speed: 1.2ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/wexo761ErEhSsZyUIrt11g_90.JPG: 480x640 (no detections), 270.4ms
Speed: 1.2ms preprocess, 270.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/wexo761ErEhSsZyUIrt11g_180.JPG: 480x640 (no detections), 267.6ms
Speed: 1.2ms preprocess, 267.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/wexo761ErEhSsZyUIrt11g_270.JPG: 480x640 (no detections), 278.4ms
Speed: 1.0ms preprocess, 278.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/wezxmiJ3g7kDElve7Q617A_0.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/wezxmiJ3g7kDElve7Q617A_90.JPG: 480x640 (no detections), 266.4ms
Speed: 1.1ms preprocess, 266.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/wezxmiJ3g7kDElve7Q617A_180.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/e/wezxmiJ3g7kDElve7Q617A_270.JPG: 480x640 (no detections), 265.9ms
Speed: 1.1ms preprocess, 265.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wf4yUpGTj_NkScBhSozWPQ_0.JPG: 480x640 (no detections), 270.3ms
Speed: 1.1ms preprocess, 270.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wf4yUpGTj_NkScBhSozWPQ_90.JPG: 480x640 (no detections), 268.8ms
Speed: 1.1ms preprocess, 268.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wf4yUpGTj_NkScBhSozWPQ_180.JPG: 480x640 (no detections), 272.6ms
Speed: 1.0ms preprocess, 272.6ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wf4yUpGTj_NkScBhSozWPQ_270.JPG: 480x640 (no detections), 269.1ms
Speed: 1.1ms preprocess, 269.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wf5ujX-jocNJQFuZ0ZKVZw_0.JPG: 480x640 (no detections), 272.9ms
Speed: 1.0ms preprocess, 272.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wf5ujX-jocNJQFuZ0ZKVZw_90.JPG: 480x640 (no detections), 269.8ms
Speed: 1.1ms preprocess, 269.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wf5ujX-jocNJQFuZ0ZKVZw_180.JPG: 480x640 (no detections), 266.5ms
Speed: 1.1ms preprocess, 266.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wf5ujX-jocNJQFuZ0ZKVZw_270.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfA0_BCBL0VRFC9cqf4_gg_0.JPG: 480x640 (no detections), 268.4ms
Speed: 1.1ms preprocess, 268.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfA0_BCBL0VRFC9cqf4_gg_90.JPG: 480x640 (no detections), 266.0ms
Speed: 1.1ms preprocess, 266.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfA0_BCBL0VRFC9cqf4_gg_180.JPG: 480x640 (no detections), 275.3ms
Speed: 1.1ms preprocess, 275.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfA0_BCBL0VRFC9cqf4_gg_270.JPG: 480x640 (no detections), 268.3ms
Speed: 1.0ms preprocess, 268.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfB4AJKEgGpypyP8xDvlrw_0.JPG: 480x640 (no detections), 267.6ms
Speed: 1.0ms preprocess, 267.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfB4AJKEgGpypyP8xDvlrw_90.JPG: 480x640 (no detections), 271.6ms
Speed: 1.0ms preprocess, 271.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfB4AJKEgGpypyP8xDvlrw_180.JPG: 480x640 (no detections), 269.9ms
Speed: 1.0ms preprocess, 269.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfB4AJKEgGpypyP8xDvlrw_270.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfCY2Rpx1OxCekUtUeTItQ_0.JPG: 480x640 (no detections), 269.9ms
Speed: 1.0ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfCY2Rpx1OxCekUtUeTItQ_90.JPG: 480x640 (no detections), 267.2ms
Speed: 1.1ms preprocess, 267.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfCY2Rpx1OxCekUtUeTItQ_180.JPG: 480x640 (no detections), 264.7ms
Speed: 1.1ms preprocess, 264.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfCY2Rpx1OxCekUtUeTItQ_270.JPG: 480x640 (no detections), 267.5ms
Speed: 1.1ms preprocess, 267.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfEEWKNYh_Rx-MIRTGGV4A_0.JPG: 480x640 (no detections), 268.2ms
Speed: 1.1ms preprocess, 268.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfEEWKNYh_Rx-MIRTGGV4A_90.JPG: 480x640 (no detections), 268.7ms
Speed: 1.0ms preprocess, 268.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfEEWKNYh_Rx-MIRTGGV4A_180.JPG: 480x640 (no detections), 269.1ms
Speed: 1.0ms preprocess, 269.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfEEWKNYh_Rx-MIRTGGV4A_270.JPG: 480x640 (no detections), 272.1ms
Speed: 1.1ms preprocess, 272.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfLHmVz3Q1tM30ar7C_BTQ_0.JPG: 480x640 (no detections), 268.4ms

Speed: 1.0ms preprocess, 268.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfLHmVz3Q1tM30ar7C_BTQ_90.JPG: 480x640 (no detections), 276.5ms
Speed: 1.2ms preprocess, 276.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfLHmVz3Q1tM30ar7C_BTQ_180.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfLHmVz3Q1tM30ar7C_BTQ_270.JPG: 480x640 (no detections), 314.2ms
Speed: 1.1ms preprocess, 314.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfMsnL3DiHjR1K-qbV4KcA_0.JPG: 480x640 (no detections), 345.6ms
Speed: 1.6ms preprocess, 345.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfMsnL3DiHjR1K-qbV4KcA_90.JPG: 480x640 (no detections), 273.1ms
Speed: 1.2ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfMsnL3DiHjR1K-qbV4KcA_180.JPG: 480x640 (no detections), 272.4ms
Speed: 1.1ms preprocess, 272.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfMsnL3DiHjR1K-qbV4KcA_270.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfNBL1-G3uT5fq2DovcfCA_0.JPG: 480x640 (no detections), 267.5ms
Speed: 1.0ms preprocess, 267.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfNBL1-G3uT5fq2DovcfCA_90.JPG: 480x640 (no detections), 268.2ms
Speed: 1.2ms preprocess, 268.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfNBL1-G3uT5fq2DovcfCA_180.JPG: 480x640 (no detections), 269.6ms
Speed: 1.1ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfNBL1-G3uT5fq2DovcfCA_270.JPG: 480x640 (no detections), 266.2ms
Speed: 1.1ms preprocess, 266.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfSOoWjHNAJP3FkCMgZMJA_0.JPG: 480x640 (no detections), 265.4ms
Speed: 1.0ms preprocess, 265.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfSOoWjHNAJP3FkCMgZMJA_90.JPG: 480x640 (no detections), 269.6ms
Speed: 1.1ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfSOoWjHNAJP3FkCMgZMJA_180.JPG: 480x640 (no detections), 267.1ms
Speed: 1.0ms preprocess, 267.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfSOoWjHNAJP3FkCMgZMJA_270.JPG: 480x640 (no detections), 275.4ms
Speed: 1.0ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfSSHiK47s45Z6pO4fU3TQ_0.JPG: 480x640 (no detections), 265.1ms
Speed: 1.1ms preprocess, 265.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfSSHiK47s45Z6pO4fU3TQ_90.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfSSHiK47s45Z6pO4fU3TQ_180.JPG: 480x640 (no detections), 266.7ms
Speed: 1.0ms preprocess, 266.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfSSHiK47s45Z6pO4fU3TQ_270.JPG: 480x640 (no detections), 269.7ms
Speed: 1.0ms preprocess, 269.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfT0gJp7xc3pagn4R5sTyg_0.JPG: 480x640 (no detections), 273.0ms
Speed: 1.2ms preprocess, 273.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfT0gJp7xc3pagn4R5sTyg_90.JPG: 480x640 (no detections), 276.8ms
Speed: 1.2ms preprocess, 276.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfT0gJp7xc3pagn4R5sTyg_180.JPG: 480x640 (no detections), 267.7ms
Speed: 1.1ms preprocess, 267.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfT0gJp7xc3pagn4R5sTyg_270.JPG: 480x640 (no detections), 280.0ms
Speed: 1.1ms preprocess, 280.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfTiWE4VFRZlHGbEqTHq2w_0.JPG: 480x640 (no detections), 342.2ms
Speed: 1.4ms preprocess, 342.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfTiWE4VFRZlHGbEqTHq2w_90.JPG: 480x640 (no detections), 290.9ms
Speed: 1.2ms preprocess, 290.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfTiWE4VFRZlHGbEqTHq2w_180.JPG: 480x640 (no detections), 277.1ms
Speed: 1.1ms preprocess, 277.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfTiWE4VFRZlHGbEqTHq2w_270.JPG: 480x640 (no detections), 267.3ms
Speed: 1.1ms preprocess, 267.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfV1oMkrw5_V00mnZmhdoA_0.JPG: 480x640 (no detections), 266.2ms
Speed: 1.0ms preprocess, 266.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfV1oMkrw5_V00mnZmhdoA_90.JPG: 480x640 (no detections), 267.6ms
Speed: 1.1ms preprocess, 267.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfV1oMkrw5_V00mnZmhdoA_180.JPG: 480x640 (no detections), 265.1ms
Speed: 1.2ms preprocess, 265.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfV1oMkrw5_V00mnZmhdoA_270.JPG: 480x640 (no detections), 271.7ms
Speed: 1.2ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfZBWqUvXMsltrBcAT14PA_0.JPG: 480x640 (no detections), 275.4ms
Speed: 1.3ms preprocess, 275.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfZBWqUvXMsltrBcAT14PA_90.JPG: 480x640 (no detections), 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfZBWqUvXMsltrBcAT14PA_180.JPG: 480x640 (no detections), 271.8ms
Speed: 1.2ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfZBWqUvXMsltrBcAT14PA_270.JPG: 480x640 (no detections), 274.5ms
Speed: 1.2ms preprocess, 274.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wf_ReXgnHb6UAPd9e0VMVA_0.JPG: 480x640 1 Waste, 270.3ms
Speed: 1.3ms preprocess, 270.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wf_ReXgnHb6UAPd9e0VMVA_90.JPG: 480x640 1 Waste, 268.1ms
Speed: 1.1ms preprocess, 268.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wf_ReXgnHb6UAPd9e0VMVA_180.JPG: 480x640 (no detections), 268.2ms
Speed: 1.2ms preprocess, 268.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wf_ReXgnHb6UAPd9e0VMVA_270.JPG: 480x640 (no detections), 269.8ms
Speed: 1.3ms preprocess, 269.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfeN_OLYpgqzv5L9NgwFcw_0.JPG: 480x640 (no detections), 269.4ms
Speed: 1.2ms preprocess, 269.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfeN_OLYpgqzv5L9NgwFcw_90.JPG: 480x640 (no detections), 269.4ms
Speed: 1.3ms preprocess, 269.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfeN_OLYpgqzv5L9NgwFcw_180.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfeN_OLYpgqzv5L9NgwFcw_270.JPG: 480x640 (no detections), 301.2ms
Speed: 1.2ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wffoGCbdH_U_Co43OEFbRw_0.JPG: 480x640 (no detections), 285.0ms
Speed: 1.1ms preprocess, 285.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wffoGCbdH_U_Co43OEFbRw_90.JPG: 480x640 (no detections), 281.2ms
Speed: 1.0ms preprocess, 281.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wffoGCbdH_U_Co43OEFbRw_180.JPG: 480x640 (no detections), 325.7ms
Speed: 1.2ms preprocess, 325.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wffoGCbdH_U_Co43OEFbRw_270.JPG: 480x640 (no detections), 285.6ms
Speed: 1.2ms preprocess, 285.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfhQ8L1rXhHw9QB6AwmeVA_0.JPG: 480x640 (no detections), 304.6ms
Speed: 1.7ms preprocess, 304.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfhQ8L1rXhHw9QB6AwmeVA_90.JPG: 480x640 (no detections), 413.9ms
Speed: 1.2ms preprocess, 413.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfhQ8L1rXhHw9QB6AwmeVA_180.JPG: 480x640 (no detections), 283.1ms
Speed: 1.3ms preprocess, 283.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfhQ8L1rXhHw9QB6AwmeVA_270.JPG: 480x640 (no detections), 274.0ms
Speed: 1.2ms preprocess, 274.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfko-v5gMoct5gxSImSl1A_0.JPG: 480x640 (no detections), 348.8ms
Speed: 1.1ms preprocess, 348.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfko-v5gMoct5gxSImSl1A_90.JPG: 480x640 (no detections), 338.6ms
Speed: 1.1ms preprocess, 338.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfko-v5gMoct5gxSImSl1A_180.JPG: 480x640 (no detections), 303.4ms
Speed: 1.2ms preprocess, 303.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfko-v5gMoct5gxSImSl1A_270.JPG: 480x640 (no detections), 291.5ms
Speed: 1.5ms preprocess, 291.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfltSek3pnKkOejxJoolBw_0.JPG: 480x640 (no detections), 293.9ms
Speed: 1.1ms preprocess, 293.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfltSek3pnKkOejxJoolBw_90.JPG: 480x640 (no detections), 331.6ms
Speed: 1.2ms preprocess, 331.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfltSek3pnKkOejxJoolBw_180.JPG: 480x640 (no detections), 296.6ms
Speed: 1.4ms preprocess, 296.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfltSek3pnKkOejxJoolBw_270.JPG: 480x640 (no detections), 270.0ms
Speed: 1.2ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfmR1RXTaVr1_2mOtZyOkA_0.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfmR1RXTaVr1_2mOtZyOkA_90.JPG: 480x640 (no detections), 271.1ms
Speed: 1.2ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfmR1RXTaVr1_2mOtZyOkA_180.JPG: 480x640 1 Waste, 277.2ms
Speed: 1.2ms preprocess, 277.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfmR1RXTaVr1_2mOtZyOkA_270.JPG: 480x640 (no detections), 273.5ms
Speed: 1.3ms preprocess, 273.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfnkuFykawZnVPcomc-4Ew_0.JPG: 480x640 (no detections), 271.4ms
Speed: 1.3ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfnkuFykawZnVPcomc-4Ew_90.JPG: 480x640 (no detections), 264.4ms
Speed: 1.1ms preprocess, 264.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfnkuFykawZnVPcomc-4Ew_180.JPG: 480x640 1 Waste, 265.7ms
Speed: 1.0ms preprocess, 265.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfnkuFykawZnVPcomc-4Ew_270.JPG: 480x640 (no detections), 271.6ms

Speed: 1.1ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfq41S7bsQEZ3E-wF6QQZw_0.JPG: 480x640 (no detections), 265.8ms
Speed: 1.2ms preprocess, 265.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfq41S7bsQEZ3E-wF6QQZw_90.JPG: 480x640 1 Waste, 266.4ms
Speed: 1.1ms preprocess, 266.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfq41S7bsQEZ3E-wF6QQZw_180.JPG: 480x640 (no detections), 279.9ms
Speed: 1.1ms preprocess, 279.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfq41S7bsQEZ3E-wF6QQZw_270.JPG: 480x640 1 Waste, 268.8ms
Speed: 1.1ms preprocess, 268.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfr1JlgvqX5IQ1zn9u1oTw_0.JPG: 480x640 (no detections), 263.7ms
Speed: 1.0ms preprocess, 263.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfr1JlgvqX5IQ1zn9u1oTw_90.JPG: 480x640 (no detections), 262.1ms
Speed: 1.1ms preprocess, 262.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfr1JlgvqX5IQ1zn9u1oTw_180.JPG: 480x640 (no detections), 269.1ms
Speed: 1.0ms preprocess, 269.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfr1JlgvqX5IQ1zn9u1oTw_270.JPG: 480x640 (no detections), 269.8ms
Speed: 1.0ms preprocess, 269.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfr2cIlTfSUd4r5OnbTpNQ_0.JPG: 480x640 (no detections), 269.3ms
Speed: 1.0ms preprocess, 269.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfr2cIlTfSUd4r5OnbTpNQ_90.JPG: 480x640 (no detections), 266.7ms
Speed: 1.1ms preprocess, 266.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfr2cIlTfSUd4r5OnbTpNQ_180.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfr2cIlTfSUd4r5OnbTpNQ_270.JPG: 480x640 (no detections), 274.9ms
Speed: 1.2ms preprocess, 274.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfw7gpZJAF3bCbWgABdzJQ_0.JPG: 480x640 (no detections), 304.2ms
Speed: 1.1ms preprocess, 304.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfw7gpZJAF3bCbWgABdzJQ_90.JPG: 480x640 (no detections), 275.2ms
Speed: 2.2ms preprocess, 275.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfw7gpZJAF3bCbWgABdzJQ_180.JPG: 480x640 (no detections), 279.9ms
Speed: 1.0ms preprocess, 279.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfw7gpZJAF3bCbWgABdzJQ_270.JPG: 480x640 (no detections), 266.2ms
Speed: 1.3ms preprocess, 266.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfxLUr2AhDKeU5eJKKvlwA_0.JPG: 480x640 (no detections), 267.9ms
Speed: 1.2ms preprocess, 267.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfxLUr2AhDKeU5eJKKvlwA_90.JPG: 480x640 (no detections), 304.7ms
Speed: 1.1ms preprocess, 304.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfxLUr2AhDKeU5eJKKvlwA_180.JPG: 480x640 (no detections), 265.4ms
Speed: 1.3ms preprocess, 265.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfxLUr2AhDKeU5eJKKvlwA_270.JPG: 480x640 (no detections), 275.0ms
Speed: 1.6ms preprocess, 275.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfxOr5IPedIl_hSIc1knLw_0.JPG: 480x640 (no detections), 277.7ms
Speed: 1.0ms preprocess, 277.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfxOr5IPedIl_hSIc1knLw_90.JPG: 480x640 (no detections), 279.5ms
Speed: 1.1ms preprocess, 279.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfxOr5IPedIl_hSIc1knLw_180.JPG: 480x640 (no detections), 310.2ms
Speed: 1.1ms preprocess, 310.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfxOr5IPedIl_hSIc1knLw_270.JPG: 480x640 (no detections), 295.0ms
Speed: 1.6ms preprocess, 295.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfyl4d29EbDy4BAwLDEMgg_0.JPG: 480x640 (no detections), 301.3ms
Speed: 1.2ms preprocess, 301.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfyl4d29EbDy4BAwLDEMgg_90.JPG: 480x640 (no detections), 281.2ms
Speed: 1.4ms preprocess, 281.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfyl4d29EbDy4BAwLDEMgg_180.JPG: 480x640 (no detections), 381.5ms
Speed: 1.2ms preprocess, 381.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfyl4d29EbDy4BAwLDEMgg_270.JPG: 480x640 (no detections), 287.7ms
Speed: 1.3ms preprocess, 287.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfyoFKaLVjIZ_Nap0rppMw_0.JPG: 480x640 (no detections), 267.7ms
Speed: 1.5ms preprocess, 267.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfyoFKaLVjIZ_Nap0rppMw_90.JPG: 480x640 (no detections), 269.6ms
Speed: 1.1ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfyoFKaLVjIZ_Nap0rppMw_180.JPG: 480x640 (no detections), 270.2ms
Speed: 1.0ms preprocess, 270.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/f/wfyoFKaLVjIZ_Nap0rppMw_270.JPG: 480x640 (no detections), 267.9ms
Speed: 1.0ms preprocess, 267.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wg-Nji7g21JrJfmDbHJpcg_0.JPG: 480x640 (no detections), 264.4ms
Speed: 1.0ms preprocess, 264.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wg-Nji7g21JrJfmDbHJpcg_90.JPG: 480x640 (no detections), 279.2ms
Speed: 1.0ms preprocess, 279.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wg-Nji7g21JrJfmDbHJpcg_180.JPG: 480x640 (no detections), 266.1ms
Speed: 1.2ms preprocess, 266.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wg-Nji7g21JrJfmDbHJpcg_270.JPG: 480x640 (no detections), 270.1ms
Speed: 1.2ms preprocess, 270.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wg2bsGghsVhCSCSruGhYgg_0.JPG: 480x640 (no detections), 267.3ms
Speed: 1.1ms preprocess, 267.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wg2bsGghsVhCSCSruGhYgg_90.JPG: 480x640 (no detections), 270.1ms
Speed: 1.0ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wg2bsGghsVhCSCSruGhYgg_180.JPG: 480x640 (no detections), 266.6ms
Speed: 1.1ms preprocess, 266.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wg2bsGghsVhCSCSruGhYgg_270.JPG: 480x640 (no detections), 262.3ms
Speed: 1.0ms preprocess, 262.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wg3IeEKjrlnnlUzKcaCl8A_0.JPG: 480x640 (no detections), 256.4ms
Speed: 1.1ms preprocess, 256.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wg3IeEKjrlnnlUzKcaCl8A_90.JPG: 480x640 (no detections), 265.5ms
Speed: 1.2ms preprocess, 265.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wg3IeEKjrlnnlUzKcaCl8A_180.JPG: 480x640 (no detections), 269.5ms
Speed: 1.1ms preprocess, 269.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wg3IeEKjrlnnlUzKcaCl8A_270.JPG: 480x640 (no detections), 273.3ms
Speed: 1.0ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wg3InVRi7uC8BEP-_z789g_0.JPG: 480x640 (no detections), 272.5ms
Speed: 1.1ms preprocess, 272.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wg3InVRi7uC8BEP-_z789g_90.JPG: 480x640 (no detections), 270.0ms
Speed: 1.0ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wg3InVRi7uC8BEP-_z789g_180.JPG: 480x640 (no detections), 292.2ms
Speed: 1.2ms preprocess, 292.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wg3InVRi7uC8BEP-_z789g_270.JPG: 480x640 (no detections), 270.2ms
Speed: 1.4ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgAmPGHiGkcKyoXAUsMawQ_0.JPG: 480x640 (no detections), 306.2ms
Speed: 1.2ms preprocess, 306.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgAmPGHiGkcKyoXAUsMawQ_90.JPG: 480x640 (no detections), 325.9ms
Speed: 1.4ms preprocess, 325.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgAmPGHiGkcKyoXAUsMawQ_180.JPG: 480x640 (no detections), 352.6ms
Speed: 16.6ms preprocess, 352.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgAmPGHiGkcKyoXAUsMawQ_270.JPG: 480x640 (no detections), 341.0ms
Speed: 1.3ms preprocess, 341.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgF_Py7u81GJbHOUpHMuEA_0.JPG: 480x640 (no detections), 299.2ms
Speed: 1.3ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgF_Py7u81GJbHOUpHMuEA_90.JPG: 480x640 (no detections), 286.9ms
Speed: 1.2ms preprocess, 286.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgF_Py7u81GJbHOUpHMuEA_180.JPG: 480x640 (no detections), 301.6ms
Speed: 1.4ms preprocess, 301.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgF_Py7u81GJbHOUpHMuEA_270.JPG: 480x640 (no detections), 287.4ms
Speed: 1.2ms preprocess, 287.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgHc2sh9lPfa52Y5MkaZ2g_0.JPG: 480x640 (no detections), 265.9ms
Speed: 1.1ms preprocess, 265.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgHc2sh9lPfa52Y5MkaZ2g_90.JPG: 480x640 (no detections), 269.4ms
Speed: 1.1ms preprocess, 269.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgHc2sh9lPfa52Y5MkaZ2g_180.JPG: 480x640 (no detections), 272.7ms
Speed: 1.0ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgHc2sh9lPfa52Y5MkaZ2g_270.JPG: 480x640 (no detections), 295.5ms
Speed: 1.3ms preprocess, 295.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgKEP4_TJfvgKys3zUCAsg_0.JPG: 480x640 (no detections), 292.8ms
Speed: 1.7ms preprocess, 292.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgKEP4_TJfvgKys3zUCAsg_90.JPG: 480x640 (no detections), 290.9ms
Speed: 1.9ms preprocess, 290.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgKEP4_TJfvgKys3zUCAsg_180.JPG: 480x640 (no detections), 280.1ms
Speed: 1.2ms preprocess, 280.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgKEP4_TJfvgKys3zUCAsg_270.JPG: 480x640 (no detections), 275.9ms
Speed: 1.2ms preprocess, 275.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgMYNQRoHVgsBi85FxwUsw_0.JPG: 480x640 (no detections), 292.2ms
Speed: 1.0ms preprocess, 292.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgMYNQRoHVgsBi85FxwUsw_90.JPG: 480x640 (no detections), 290.2ms
Speed: 1.1ms preprocess, 290.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgMYNQRoHVgsBi85FxwUsw_180.JPG: 480x640 (no detections), 276.6ms

Speed: 1.1ms preprocess, 276.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgMYNQRoHVgsBi85FxwUsw_270.JPG: 480x640 (no detections), 265.7ms
Speed: 1.0ms preprocess, 265.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgOztDhvX0tre5wSEdWY_w_0.JPG: 480x640 (no detections), 278.4ms
Speed: 1.0ms preprocess, 278.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgOztDhvX0tre5wSEdWY_w_90.JPG: 480x640 (no detections), 330.1ms
Speed: 1.3ms preprocess, 330.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgOztDhvX0tre5wSEdWY_w_180.JPG: 480x640 (no detections), 313.3ms
Speed: 1.4ms preprocess, 313.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgOztDhvX0tre5wSEdWY_w_270.JPG: 480x640 (no detections), 325.5ms
Speed: 1.2ms preprocess, 325.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgQnPjAwdzob9-VBOp3TZQ_0.JPG: 480x640 (no detections), 292.4ms
Speed: 1.1ms preprocess, 292.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgQnPjAwdzob9-VBOp3TZQ_90.JPG: 480x640 (no detections), 285.5ms
Speed: 1.3ms preprocess, 285.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgQnPjAwdzob9-VBOp3TZQ_180.JPG: 480x640 (no detections), 276.0ms
Speed: 1.1ms preprocess, 276.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgQnPjAwdzob9-VBOp3TZQ_270.JPG: 480x640 (no detections), 278.1ms
Speed: 1.2ms preprocess, 278.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgUr-mKQHg2FB4H5hdnmgg_0.JPG: 480x640 (no detections), 278.1ms
Speed: 1.5ms preprocess, 278.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgUr-mKQHg2FB4H5hdnmgg_90.JPG: 480x640 (no detections), 277.5ms
Speed: 1.1ms preprocess, 277.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgUr-mKQHg2FB4H5hdnmgg_180.JPG: 480x640 (no detections), 288.0ms
Speed: 1.4ms preprocess, 288.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgUr-mKQHg2FB4H5hdnmgg_270.JPG: 480x640 (no detections), 283.9ms
Speed: 1.4ms preprocess, 283.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgVxIAp22W09GhE8Mf1JNg_0.JPG: 480x640 (no detections), 281.0ms
Speed: 1.1ms preprocess, 281.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgVxIAp22W09GhE8Mf1JNg_90.JPG: 480x640 1 Waste, 305.5ms
Speed: 1.4ms preprocess, 305.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgVxIAp22W09GhE8Mf1JNg_180.JPG: 480x640 (no detections), 299.2ms
Speed: 1.2ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgVxIAp22W09GhE8Mf1JNg_270.JPG: 480x640 (no detections), 294.0ms
Speed: 1.2ms preprocess, 294.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgYRJvSasLlVbXUJfzgQjg_0.JPG: 480x640 (no detections), 280.8ms
Speed: 1.1ms preprocess, 280.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgYRJvSasLlVbXUJfzgQjg_90.JPG: 480x640 (no detections), 278.3ms
Speed: 1.3ms preprocess, 278.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgYRJvSasLlVbXUJfzgQjg_180.JPG: 480x640 (no detections), 283.6ms
Speed: 1.2ms preprocess, 283.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgYRJvSasLlVbXUJfzgQjg_270.JPG: 480x640 (no detections), 292.1ms
Speed: 1.1ms preprocess, 292.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wg_NhyYXD0P0R2MkZfrXbg_0.JPG: 480x640 (no detections), 282.8ms
Speed: 1.2ms preprocess, 282.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wg_NhyYXD0P0R2MkZfrXbg_90.JPG: 480x640 (no detections), 285.4ms
Speed: 1.1ms preprocess, 285.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wg_NhyYXD0P0R2MkZfrXbg_180.JPG: 480x640 (no detections), 354.7ms
Speed: 1.2ms preprocess, 354.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wg_NhyYXD0P0R2MkZfrXbg_270.JPG: 480x640 1 Waste, 291.0ms
Speed: 1.0ms preprocess, 291.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgdtrohe6CTSSJllD_m4oA_0.JPG: 480x640 (no detections), 311.5ms
Speed: 1.5ms preprocess, 311.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgdtrohe6CTSSJllD_m4oA_90.JPG: 480x640 (no detections), 395.1ms
Speed: 1.2ms preprocess, 395.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgdtrohe6CTSSJllD_m4oA_180.JPG: 480x640 (no detections), 330.5ms
Speed: 1.2ms preprocess, 330.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgdtrohe6CTSSJllD_m4oA_270.JPG: 480x640 (no detections), 341.4ms
Speed: 1.3ms preprocess, 341.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgfh_c9hdPYtUubFKhZe9A_0.JPG: 480x640 (no detections), 303.6ms
Speed: 1.1ms preprocess, 303.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgfh_c9hdPYtUubFKhZe9A_90.JPG: 480x640 (no detections), 278.3ms
Speed: 1.2ms preprocess, 278.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgfh_c9hdPYtUubFKhZe9A_180.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgfh_c9hdPYtUubFKhZe9A_270.JPG: 480x640 (no detections), 271.0ms
Speed: 1.3ms preprocess, 271.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgfpMCQQAVpXOX3sDLrhRQ_0.JPG: 480x640 (no detections), 275.2ms
Speed: 1.2ms preprocess, 275.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgfpMCQQAVpXOX3sDLrhRQ_90.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgfpMCQQAVpXOX3sDLrhRQ_180.JPG: 480x640 (no detections), 280.7ms
Speed: 1.2ms preprocess, 280.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgfpMCQQAVpXOX3sDLrhRQ_270.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wggfRXJiDGW3QztQxvLQ2g_0.JPG: 480x640 (no detections), 267.4ms
Speed: 1.2ms preprocess, 267.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wggfRXJiDGW3QztQxvLQ2g_90.JPG: 480x640 (no detections), 270.9ms
Speed: 1.3ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wggfRXJiDGW3QztQxvLQ2g_180.JPG: 480x640 (no detections), 271.8ms
Speed: 1.2ms preprocess, 271.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wggfRXJiDGW3QztQxvLQ2g_270.JPG: 480x640 (no detections), 273.2ms
Speed: 1.1ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wggqLp7ItGxTFqsKCzSa_g_0.JPG: 480x640 (no detections), 258.2ms
Speed: 1.1ms preprocess, 258.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wggqLp7ItGxTFqsKCzSa_g_90.JPG: 480x640 (no detections), 261.8ms
Speed: 1.1ms preprocess, 261.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wggqLp7ItGxTFqsKCzSa_g_180.JPG: 480x640 (no detections), 259.1ms
Speed: 1.1ms preprocess, 259.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wggqLp7ItGxTFqsKCzSa_g_270.JPG: 480x640 (no detections), 270.4ms
Speed: 1.1ms preprocess, 270.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wghv9JaxZvKybw5whYNf8g_0.JPG: 480x640 (no detections), 269.4ms
Speed: 1.0ms preprocess, 269.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wghv9JaxZvKybw5whYNf8g_90.JPG: 480x640 (no detections), 278.2ms
Speed: 1.2ms preprocess, 278.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wghv9JaxZvKybw5whYNf8g_180.JPG: 480x640 (no detections), 270.2ms
Speed: 1.0ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wghv9JaxZvKybw5whYNf8g_270.JPG: 480x640 (no detections), 270.5ms
Speed: 1.2ms preprocess, 270.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wghzpZfdPRqHEkbQLylZWQ_0.JPG: 480x640 (no detections), 269.6ms
Speed: 1.1ms preprocess, 269.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wghzpZfdPRqHEkbQLylZWQ_90.JPG: 480x640 (no detections), 267.0ms
Speed: 1.1ms preprocess, 267.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wghzpZfdPRqHEkbQLylZWQ_180.JPG: 480x640 (no detections), 270.9ms
Speed: 1.2ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wghzpZfdPRqHEkbQLylZWQ_270.JPG: 480x640 (no detections), 292.7ms
Speed: 1.1ms preprocess, 292.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgiN1hvcdgAcgxzNb__CgQ_0.JPG: 480x640 1 Waste, 296.9ms
Speed: 1.3ms preprocess, 296.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgiN1hvcdgAcgxzNb__CgQ_90.JPG: 480x640 (no detections), 302.4ms
Speed: 1.3ms preprocess, 302.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgiN1hvcdgAcgxzNb__CgQ_180.JPG: 480x640 (no detections), 287.7ms
Speed: 1.3ms preprocess, 287.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgiN1hvcdgAcgxzNb__CgQ_270.JPG: 480x640 (no detections), 277.6ms
Speed: 1.1ms preprocess, 277.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgk2Y-SMYHI9o-ncTbaMIw_0.JPG: 480x640 (no detections), 288.9ms
Speed: 1.4ms preprocess, 288.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgk2Y-SMYHI9o-ncTbaMIw_90.JPG: 480x640 (no detections), 271.2ms
Speed: 1.2ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgk2Y-SMYHI9o-ncTbaMIw_180.JPG: 480x640 (no detections), 279.5ms
Speed: 1.2ms preprocess, 279.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgk2Y-SMYHI9o-ncTbaMIw_270.JPG: 480x640 (no detections), 282.1ms
Speed: 1.3ms preprocess, 282.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgmq06o_21Gh8pLHnGP6sg_0.JPG: 480x640 (no detections), 289.5ms
Speed: 1.4ms preprocess, 289.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgmq06o_21Gh8pLHnGP6sg_90.JPG: 480x640 (no detections), 285.7ms
Speed: 1.6ms preprocess, 285.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgmq06o_21Gh8pLHnGP6sg_180.JPG: 480x640 (no detections), 285.5ms
Speed: 1.3ms preprocess, 285.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgmq06o_21Gh8pLHnGP6sg_270.JPG: 480x640 (no detections), 296.5ms
Speed: 1.2ms preprocess, 296.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgnq1qLTz2F7PaKK9dZICA_0.JPG: 480x640 (no detections), 307.0ms
Speed: 1.4ms preprocess, 307.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgnq1qLTz2F7PaKK9dZICA_90.JPG: 480x640 (no detections), 276.6ms

Speed: 1.1ms preprocess, 276.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgnq1qLTz2F7PaKK9dZICA_180.JPG: 480x640 (no detections), 297.4ms
Speed: 1.1ms preprocess, 297.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgnq1qLTz2F7PaKK9dZICA_270.JPG: 480x640 (no detections), 272.1ms
Speed: 1.2ms preprocess, 272.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgotxEiYHJ45ynTM6UCmwA_0.JPG: 480x640 (no detections), 276.6ms
Speed: 1.2ms preprocess, 276.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgotxEiYHJ45ynTM6UCmwA_90.JPG: 480x640 (no detections), 268.4ms
Speed: 1.1ms preprocess, 268.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgotxEiYHJ45ynTM6UCmwA_180.JPG: 480x640 (no detections), 274.2ms
Speed: 1.0ms preprocess, 274.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgotxEiYHJ45ynTM6UCmwA_270.JPG: 480x640 (no detections), 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgqJl27YD-nWOqBOdM8QEw_0.JPG: 480x640 (no detections), 267.3ms
Speed: 1.1ms preprocess, 267.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgqJl27YD-nWOqBOdM8QEw_90.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgqJl27YD-nWOqBOdM8QEw_180.JPG: 480x640 (no detections), 266.4ms
Speed: 1.3ms preprocess, 266.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgqJl27YD-nWOqBOdM8QEw_270.JPG: 480x640 (no detections), 266.5ms
Speed: 1.1ms preprocess, 266.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgserxZaHfY7qFwhifwUSQ_0.JPG: 480x640 (no detections), 267.6ms
Speed: 1.0ms preprocess, 267.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgserxZaHfY7qFwhifwUSQ_90.JPG: 480x640 (no detections), 265.5ms
Speed: 1.1ms preprocess, 265.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgserxZaHfY7qFwhifwUSQ_180.JPG: 480x640 (no detections), 266.7ms
Speed: 1.1ms preprocess, 266.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgserxZaHfY7qFwhifwUSQ_270.JPG: 480x640 (no detections), 285.4ms
Speed: 1.1ms preprocess, 285.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgukiV5X4Gu6z76UVC99OQ_0.JPG: 480x640 (no detections), 277.5ms
Speed: 1.5ms preprocess, 277.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgukiV5X4Gu6z76UVC99OQ_90.JPG: 480x640 (no detections), 268.8ms
Speed: 1.1ms preprocess, 268.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgukiV5X4Gu6z76UVC99OQ_180.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgukiV5X4Gu6z76UVC99OQ_270.JPG: 480x640 (no detections), 280.9ms
Speed: 1.1ms preprocess, 280.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgwpTmpgz-vm-fTa5oFO7A_0.JPG: 480x640 (no detections), 285.1ms
Speed: 1.0ms preprocess, 285.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgwpTmpgz-vm-fTa5oFO7A_90.JPG: 480x640 (no detections), 273.8ms
Speed: 1.6ms preprocess, 273.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgwpTmpgz-vm-fTa5oFO7A_180.JPG: 480x640 (no detections), 269.5ms
Speed: 1.1ms preprocess, 269.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgwpTmpgz-vm-fTa5oFO7A_270.JPG: 480x640 (no detections), 285.6ms
Speed: 1.6ms preprocess, 285.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgwvuKPPQ-gZ6bM2S-WOYA_0.JPG: 480x640 (no detections), 411.1ms
Speed: 1.6ms preprocess, 411.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgwvuKPPQ-gZ6bM2S-WOYA_90.JPG: 480x640 1 Waste, 315.6ms
Speed: 1.5ms preprocess, 315.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgwvuKPPQ-gZ6bM2S-WOYA_180.JPG: 480x640 (no detections), 277.2ms
Speed: 1.3ms preprocess, 277.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgwvuKPPQ-gZ6bM2S-WOYA_270.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgyaUk3JFlCKbjUWS3UrFw_0.JPG: 480x640 (no detections), 288.4ms
Speed: 1.1ms preprocess, 288.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgyaUk3JFlCKbjUWS3UrFw_90.JPG: 480x640 (no detections), 274.6ms
Speed: 1.1ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgyaUk3JFlCKbjUWS3UrFw_180.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgyaUk3JFlCKbjUWS3UrFw_270.JPG: 480x640 (no detections), 295.1ms
Speed: 2.1ms preprocess, 295.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgz1rdvAf9bX6tZLGjQU0A_0.JPG: 480x640 (no detections), 297.1ms
Speed: 1.4ms preprocess, 297.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgz1rdvAf9bX6tZLGjQU0A_90.JPG: 480x640 (no detections), 289.4ms
Speed: 1.2ms preprocess, 289.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgz1rdvAf9bX6tZLGjQU0A_180.JPG: 480x640 (no detections), 281.5ms
Speed: 1.4ms preprocess, 281.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/g/wgz1rdvAf9bX6tZLGjQU0A_270.JPG: 480x640 (no detections), 287.2ms
Speed: 1.3ms preprocess, 287.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/wh2njyjCRy-2Jy2b6i-TAw_0.JPG: 480x640 (no detections), 280.1ms
Speed: 1.1ms preprocess, 280.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/wh2njyjCRy-2Jy2b6i-TAw_90.JPG: 480x640 (no detections), 279.6ms
Speed: 1.1ms preprocess, 279.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/wh2njyjCRy-2Jy2b6i-TAw_180.JPG: 480x640 (no detections), 273.2ms
Speed: 1.0ms preprocess, 273.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/wh2njyjCRy-2Jy2b6i-TAw_270.JPG: 480x640 (no detections), 281.3ms
Speed: 1.1ms preprocess, 281.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/wh2s4yYhNgHjcKuBJwZXdA_0.JPG: 480x640 (no detections), 303.5ms
Speed: 1.3ms preprocess, 303.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/wh2s4yYhNgHjcKuBJwZXdA_90.JPG: 480x640 (no detections), 364.5ms
Speed: 1.3ms preprocess, 364.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/wh2s4yYhNgHjcKuBJwZXdA_180.JPG: 480x640 (no detections), 332.3ms
Speed: 1.3ms preprocess, 332.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/wh2s4yYhNgHjcKuBJwZXdA_270.JPG: 480x640 1 Waste, 301.2ms
Speed: 1.4ms preprocess, 301.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/wh3p35OJes5YnFZBspZCag_0.JPG: 480x640 (no detections), 299.1ms
Speed: 1.2ms preprocess, 299.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/wh3p35OJes5YnFZBspZCag_90.JPG: 480x640 (no detections), 293.4ms
Speed: 1.0ms preprocess, 293.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/wh3p35OJes5YnFZBspZCag_180.JPG: 480x640 (no detections), 299.3ms
Speed: 1.8ms preprocess, 299.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/wh3p35OJes5YnFZBspZCag_270.JPG: 480x640 (no detections), 315.1ms
Speed: 1.3ms preprocess, 315.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/wh7RMEV_4PMBaKdOb53xAw_0.JPG: 480x640 (no detections), 296.9ms
Speed: 1.1ms preprocess, 296.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/wh7RMEV_4PMBaKdOb53xAw_90.JPG: 480x640 (no detections), 286.8ms
Speed: 1.1ms preprocess, 286.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/wh7RMEV_4PMBaKdOb53xAw_180.JPG: 480x640 (no detections), 291.8ms
Speed: 1.2ms preprocess, 291.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/wh7RMEV_4PMBaKdOb53xAw_270.JPG: 480x640 (no detections), 294.0ms
Speed: 1.1ms preprocess, 294.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/wh7ymFjiYwwUY1eEwlQpRA_0.JPG: 480x640 (no detections), 284.7ms
Speed: 1.2ms preprocess, 284.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/wh7ymFjiYwwUY1eEwlQpRA_90.JPG: 480x640 (no detections), 293.9ms
Speed: 1.2ms preprocess, 293.9ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/wh7ymFjiYwwUY1eEwlQpRA_180.JPG: 480x640 (no detections), 294.9ms
Speed: 1.3ms preprocess, 294.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/wh7ymFjiYwwUY1eEwlQpRA_270.JPG: 480x640 (no detections), 307.4ms
Speed: 1.2ms preprocess, 307.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/wh7yyNGXABhCFMVPmZBy4Q_0.JPG: 480x640 (no detections), 295.2ms
Speed: 1.1ms preprocess, 295.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/wh7yyNGXABhCFMVPmZBy4Q_90.JPG: 480x640 (no detections), 298.1ms
Speed: 1.3ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/wh7yyNGXABhCFMVPmZBy4Q_180.JPG: 480x640 (no detections), 295.1ms
Speed: 1.1ms preprocess, 295.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/wh7yyNGXABhCFMVPmZBy4Q_270.JPG: 480x640 (no detections), 297.2ms
Speed: 1.1ms preprocess, 297.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/wh84jy4Zzu5x3BoINfGfwQ_0.JPG: 480x640 (no detections), 293.8ms
Speed: 1.1ms preprocess, 293.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/wh84jy4Zzu5x3BoINfGfwQ_90.JPG: 480x640 (no detections), 294.2ms
Speed: 1.0ms preprocess, 294.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/wh84jy4Zzu5x3BoINfGfwQ_180.JPG: 480x640 (no detections), 292.7ms
Speed: 1.2ms preprocess, 292.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/wh84jy4Zzu5x3BoINfGfwQ_270.JPG: 480x640 (no detections), 298.3ms
Speed: 1.2ms preprocess, 298.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/wh8oue4_3HhiF43m9_ub8Q_0.JPG: 480x640 (no detections), 300.8ms
Speed: 1.0ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/wh8oue4_3HhiF43m9_ub8Q_90.JPG: 480x640 (no detections), 298.2ms
Speed: 1.1ms preprocess, 298.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/wh8oue4_3HhiF43m9_ub8Q_180.JPG: 480x640 (no detections), 291.8ms
Speed: 1.2ms preprocess, 291.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/wh8oue4_3HhiF43m9_ub8Q_270.JPG: 480x640 (no detections), 296.4ms
Speed: 1.1ms preprocess, 296.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whARYh2qNC0kWmNFVPIP1A_0.JPG: 480x640 (no detections), 302.2ms

Speed: 1.2ms preprocess, 302.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whARYh2qNC0kWmNFVPIP1A_90.JPG: 480x640 (no detections), 295.5ms
Speed: 1.3ms preprocess, 295.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whARYh2qNC0kWmNFVPIP1A_180.JPG: 480x640 (no detections), 297.0ms
Speed: 1.6ms preprocess, 297.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whARYh2qNC0kWmNFVPIP1A_270.JPG: 480x640 (no detections), 292.9ms
Speed: 1.1ms preprocess, 292.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whG2DFw1j9WNYWNxjv24Wg_0.JPG: 480x640 (no detections), 295.9ms
Speed: 1.3ms preprocess, 295.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whG2DFw1j9WNYWNxjv24Wg_90.JPG: 480x640 (no detections), 295.5ms
Speed: 1.3ms preprocess, 295.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whG2DFw1j9WNYWNxjv24Wg_180.JPG: 480x640 (no detections), 298.1ms
Speed: 1.1ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whG2DFw1j9WNYWNxjv24Wg_270.JPG: 480x640 (no detections), 293.6ms
Speed: 1.4ms preprocess, 293.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whHKdGVjAlpc3EbZSJzY5A_0.JPG: 480x640 (no detections), 294.6ms
Speed: 1.1ms preprocess, 294.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whHKdGVjAlpc3EbZSJzY5A_90.JPG: 480x640 (no detections), 293.1ms
Speed: 1.4ms preprocess, 293.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whHKdGVjAlpc3EbZSJzY5A_180.JPG: 480x640 (no detections), 293.4ms
Speed: 1.4ms preprocess, 293.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whHKdGVjAlpc3EbZSJzY5A_270.JPG: 480x640 (no detections), 293.4ms
Speed: 1.1ms preprocess, 293.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whKoukaQLEY2VspjVXxmkg_0.JPG: 480x640 (no detections), 289.7ms
Speed: 1.1ms preprocess, 289.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whKoukaQLEY2VspjVXxmkg_90.JPG: 480x640 (no detections), 295.6ms
Speed: 1.8ms preprocess, 295.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whKoukaQLEY2VspjVXxmkg_180.JPG: 480x640 (no detections), 295.0ms
Speed: 1.3ms preprocess, 295.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whKoukaQLEY2VspjVXxmkg_270.JPG: 480x640 (no detections), 295.4ms
Speed: 1.2ms preprocess, 295.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whMdS2U46WYxSfJIjsqfzA_0.JPG: 480x640 (no detections), 293.7ms
Speed: 1.1ms preprocess, 293.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whMdS2U46WYxSfJIjsqfzA_90.JPG: 480x640 (no detections), 289.9ms
Speed: 1.1ms preprocess, 289.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whMdS2U46WYxSfJIjsqfzA_180.JPG: 480x640 (no detections), 289.4ms
Speed: 1.2ms preprocess, 289.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whMdS2U46WYxSfJIjsqfzA_270.JPG: 480x640 (no detections), 298.1ms
Speed: 1.1ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whTGasEMqeUtPokTHeuutg_0.JPG: 480x640 (no detections), 291.7ms
Speed: 1.1ms preprocess, 291.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whTGasEMqeUtPokTHeuutg_90.JPG: 480x640 (no detections), 294.1ms
Speed: 1.1ms preprocess, 294.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whTGasEMqeUtPokTHeuutg_180.JPG: 480x640 (no detections), 297.0ms
Speed: 1.1ms preprocess, 297.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whTGasEMqeUtPokTHeuutg_270.JPG: 480x640 (no detections), 302.4ms
Speed: 1.6ms preprocess, 302.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whUPLiFUpHk3nyKRZPbYuA_0.JPG: 480x640 (no detections), 312.2ms
Speed: 1.3ms preprocess, 312.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whUPLiFUpHk3nyKRZPbYuA_90.JPG: 480x640 (no detections), 295.9ms
Speed: 1.2ms preprocess, 295.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whUPLiFUpHk3nyKRZPbYuA_180.JPG: 480x640 (no detections), 378.6ms
Speed: 1.3ms preprocess, 378.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whUPLiFUpHk3nyKRZPbYuA_270.JPG: 480x640 (no detections), 290.8ms
Speed: 1.2ms preprocess, 290.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whYImJwq_-_xig5KGaE7tQ_0.JPG: 480x640 (no detections), 367.7ms
Speed: 1.1ms preprocess, 367.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whYImJwq_-_xig5KGaE7tQ_90.JPG: 480x640 (no detections), 289.1ms
Speed: 1.0ms preprocess, 289.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whYImJwq_-_xig5KGaE7tQ_180.JPG: 480x640 (no detections), 371.5ms
Speed: 1.2ms preprocess, 371.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whYImJwq_-_xig5KGaE7tQ_270.JPG: 480x640 (no detections), 293.7ms
Speed: 1.2ms preprocess, 293.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whe-FoZ5Cuh3TvSuiz9PwQ_0.JPG: 480x640 (no detections), 294.5ms
Speed: 1.1ms preprocess, 294.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whe-FoZ5Cuh3TvSuiz9PwQ_90.JPG: 480x640 (no detections), 292.3ms
Speed: 1.2ms preprocess, 292.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whe-FoZ5Cuh3TvSuiz9PwQ_180.JPG: 480x640 (no detections), 295.0ms
Speed: 1.1ms preprocess, 295.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whe-FoZ5Cuh3TvSuiz9PwQ_270.JPG: 480x640 (no detections), 297.0ms
Speed: 1.3ms preprocess, 297.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whlNrvZaDGg-7w6ZTcCtaA_0.JPG: 480x640 (no detections), 296.6ms
Speed: 1.0ms preprocess, 296.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whlNrvZaDGg-7w6ZTcCtaA_90.JPG: 480x640 (no detections), 294.7ms
Speed: 1.2ms preprocess, 294.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whlNrvZaDGg-7w6ZTcCtaA_180.JPG: 480x640 (no detections), 302.5ms
Speed: 1.2ms preprocess, 302.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whlNrvZaDGg-7w6ZTcCtaA_270.JPG: 480x640 (no detections), 298.7ms
Speed: 1.3ms preprocess, 298.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whmsIvSR8fJmMT4njCDd2w_0.JPG: 480x640 (no detections), 294.6ms
Speed: 1.6ms preprocess, 294.6ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whmsIvSR8fJmMT4njCDd2w_90.JPG: 480x640 (no detections), 292.8ms
Speed: 1.3ms preprocess, 292.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whmsIvSR8fJmMT4njCDd2w_180.JPG: 480x640 (no detections), 292.9ms
Speed: 1.3ms preprocess, 292.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whmsIvSR8fJmMT4njCDd2w_270.JPG: 480x640 (no detections), 295.6ms
Speed: 1.4ms preprocess, 295.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/who8vyuO-5zPJyGDX_sMww_0.JPG: 480x640 (no detections), 293.0ms
Speed: 1.2ms preprocess, 293.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/who8vyuO-5zPJyGDX_sMww_90.JPG: 480x640 (no detections), 291.6ms
Speed: 1.8ms preprocess, 291.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/who8vyuO-5zPJyGDX_sMww_180.JPG: 480x640 (no detections), 299.5ms
Speed: 1.0ms preprocess, 299.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/who8vyuO-5zPJyGDX_sMww_270.JPG: 480x640 (no detections), 294.5ms
Speed: 1.2ms preprocess, 294.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whoKiZB7933fDZhgshpbUA_0.JPG: 480x640 (no detections), 292.6ms
Speed: 1.1ms preprocess, 292.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whoKiZB7933fDZhgshpbUA_90.JPG: 480x640 (no detections), 295.4ms
Speed: 1.4ms preprocess, 295.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whoKiZB7933fDZhgshpbUA_180.JPG: 480x640 (no detections), 292.4ms
Speed: 1.1ms preprocess, 292.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whoKiZB7933fDZhgshpbUA_270.JPG: 480x640 (no detections), 293.3ms
Speed: 1.2ms preprocess, 293.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whpHLSxrSwfn3yWP1-UoCg_0.JPG: 480x640 (no detections), 297.1ms
Speed: 1.0ms preprocess, 297.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whpHLSxrSwfn3yWP1-UoCg_90.JPG: 480x640 (no detections), 295.0ms
Speed: 1.1ms preprocess, 295.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whpHLSxrSwfn3yWP1-UoCg_180.JPG: 480x640 (no detections), 293.8ms
Speed: 1.2ms preprocess, 293.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whpHLSxrSwfn3yWP1-UoCg_270.JPG: 480x640 (no detections), 295.3ms
Speed: 1.3ms preprocess, 295.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whq1aTvzA1V44pJ52Y_Ozw_0.JPG: 480x640 (no detections), 291.9ms
Speed: 1.1ms preprocess, 291.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whq1aTvzA1V44pJ52Y_Ozw_90.JPG: 480x640 (no detections), 296.2ms
Speed: 1.2ms preprocess, 296.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whq1aTvzA1V44pJ52Y_Ozw_180.JPG: 480x640 (no detections), 291.2ms
Speed: 1.1ms preprocess, 291.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whq1aTvzA1V44pJ52Y_Ozw_270.JPG: 480x640 (no detections), 294.9ms
Speed: 1.3ms preprocess, 294.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whrLpgN3ctq2xm3oLVWMIQ_0.JPG: 480x640 (no detections), 291.5ms
Speed: 1.1ms preprocess, 291.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whrLpgN3ctq2xm3oLVWMIQ_90.JPG: 480x640 (no detections), 297.2ms
Speed: 1.0ms preprocess, 297.2ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whrLpgN3ctq2xm3oLVWMIQ_180.JPG: 480x640 2 Wastes, 294.4ms
Speed: 1.1ms preprocess, 294.4ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whrLpgN3ctq2xm3oLVWMIQ_270.JPG: 480x640 1 Waste, 344.3ms
Speed: 1.3ms preprocess, 344.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whtDVM71Wk8OQoeAKF2xBA_0.JPG: 480x640 (no detections), 327.6ms
Speed: 1.9ms preprocess, 327.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whtDVM71Wk8OQoeAKF2xBA_90.JPG: 480x640 (no detections), 318.6ms
Speed: 1.4ms preprocess, 318.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whtDVM71Wk8OQoeAKF2xBA_180.JPG: 480x640 (no detections), 324.8ms
Speed: 1.4ms preprocess, 324.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whtDVM71Wk8OQoeAKF2xBA_270.JPG: 480x640 (no detections), 313.3ms

Speed: 1.4ms preprocess, 313.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whvzSC5HW4NIIh298G4wcw_0.JPG: 480x640 (no detections), 303.4ms
Speed: 1.2ms preprocess, 303.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whvzSC5HW4NIIh298G4wcw_90.JPG: 480x640 (no detections), 295.7ms
Speed: 1.1ms preprocess, 295.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whvzSC5HW4NIIh298G4wcw_180.JPG: 480x640 (no detections), 292.1ms
Speed: 1.2ms preprocess, 292.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whvzSC5HW4NIIh298G4wcw_270.JPG: 480x640 (no detections), 286.1ms
Speed: 1.1ms preprocess, 286.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whzXJtcjylbUwb35LymWyw_0.JPG: 480x640 (no detections), 294.9ms
Speed: 1.6ms preprocess, 294.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whzXJtcjylbUwb35LymWyw_90.JPG: 480x640 (no detections), 288.3ms
Speed: 1.5ms preprocess, 288.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whzXJtcjylbUwb35LymWyw_180.JPG: 480x640 (no detections), 286.9ms
Speed: 1.2ms preprocess, 286.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whzXJtcjylbUwb35LymWyw_270.JPG: 480x640 (no detections), 298.2ms
Speed: 1.1ms preprocess, 298.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whzsTJtlIkE-flA2LI5jwQ_0.JPG: 480x640 (no detections), 296.2ms
Speed: 1.1ms preprocess, 296.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whzsTJtlIkE-flA2LI5jwQ_90.JPG: 480x640 (no detections), 293.7ms
Speed: 1.6ms preprocess, 293.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whzsTJtlIkE-flA2LI5jwQ_180.JPG: 480x640 (no detections), 287.9ms
Speed: 1.1ms preprocess, 287.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/H/whzsTJtlIkE-flA2LI5jwQ_270.JPG: 480x640 (no detections), 291.5ms
Speed: 1.1ms preprocess, 291.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wi2i6pI90uJulcgyBHJqwg_0.JPG: 480x640 (no detections), 293.4ms
Speed: 1.2ms preprocess, 293.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wi2i6pI90uJulcgyBHJqwg_90.JPG: 480x640 (no detections), 291.5ms
Speed: 1.1ms preprocess, 291.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wi2i6pI90uJulcgyBHJqwg_180.JPG: 480x640 (no detections), 293.6ms
Speed: 1.5ms preprocess, 293.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wi2i6pI90uJulcgyBHJqwg_270.JPG: 480x640 (no detections), 291.3ms
Speed: 1.3ms preprocess, 291.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wi2r87bw3ZS7fEm0f9EpCQ_0.JPG: 480x640 (no detections), 295.5ms
Speed: 1.3ms preprocess, 295.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wi2r87bw3ZS7fEm0f9EpCQ_90.JPG: 480x640 (no detections), 293.7ms
Speed: 1.2ms preprocess, 293.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wi2r87bw3ZS7fEm0f9EpCQ_180.JPG: 480x640 (no detections), 293.7ms
Speed: 1.5ms preprocess, 293.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wi2r87bw3ZS7fEm0f9EpCQ_270.JPG: 480x640 (no detections), 295.2ms
Speed: 1.2ms preprocess, 295.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wi33Iw8yaACc0pvHWGbuJQ_0.JPG: 480x640 (no detections), 296.9ms
Speed: 1.8ms preprocess, 296.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wi33Iw8yaACc0pvHWGbuJQ_90.JPG: 480x640 (no detections), 298.0ms
Speed: 1.2ms preprocess, 298.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wi33Iw8yaACc0pvHWGbuJQ_180.JPG: 480x640 (no detections), 294.7ms
Speed: 1.3ms preprocess, 294.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wi33Iw8yaACc0pvHWGbuJQ_270.JPG: 480x640 (no detections), 295.7ms
Speed: 1.8ms preprocess, 295.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wi5H6sSJijmlyl4fu6pfAg_0.JPG: 480x640 (no detections), 299.1ms
Speed: 1.1ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wi5H6sSJijmlyl4fu6pfAg_90.JPG: 480x640 (no detections), 292.7ms
Speed: 1.1ms preprocess, 292.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wi5H6sSJijmlyl4fu6pfAg_180.JPG: 480x640 (no detections), 294.4ms
Speed: 1.1ms preprocess, 294.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wi5H6sSJijmlyl4fu6pfAg_270.JPG: 480x640 (no detections), 293.3ms
Speed: 1.1ms preprocess, 293.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wi8Db6NKeVvrEmqmrM1DrA_0.JPG: 480x640 (no detections), 295.3ms
Speed: 1.1ms preprocess, 295.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wi8Db6NKeVvrEmqmrM1DrA_90.JPG: 480x640 (no detections), 293.5ms
Speed: 1.3ms preprocess, 293.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wi8Db6NKeVvrEmqmrM1DrA_180.JPG: 480x640 (no detections), 292.4ms
Speed: 1.1ms preprocess, 292.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wi8Db6NKeVvrEmqmrM1DrA_270.JPG: 480x640 (no detections), 296.5ms
Speed: 1.1ms preprocess, 296.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wi9nAUqLpNmiEtG5tO8jIQ_0.JPG: 480x640 (no detections), 293.5ms
Speed: 1.1ms preprocess, 293.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wi9nAUqLpNmiEtG5tO8jIQ_90.JPG: 480x640 (no detections), 294.4ms
Speed: 1.1ms preprocess, 294.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wi9nAUqLpNmiEtG5tO8jIQ_180.JPG: 480x640 (no detections), 300.5ms
Speed: 1.2ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wi9nAUqLpNmiEtG5tO8jIQ_270.JPG: 480x640 (no detections), 290.8ms
Speed: 1.2ms preprocess, 290.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wiBGyhUyvFw1cbFJwis5RA_0.JPG: 480x640 (no detections), 299.5ms
Speed: 1.2ms preprocess, 299.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wiBGyhUyvFw1cbFJwis5RA_90.JPG: 480x640 (no detections), 291.6ms
Speed: 1.3ms preprocess, 291.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wiBGyhUyvFw1cbFJwis5RA_180.JPG: 480x640 (no detections), 296.0ms
Speed: 1.1ms preprocess, 296.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wiBGyhUyvFw1cbFJwis5RA_270.JPG: 480x640 (no detections), 292.5ms
Speed: 1.7ms preprocess, 292.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wiCzuue14k3kfm3PTVz4Kg_0.JPG: 480x640 (no detections), 288.7ms
Speed: 1.2ms preprocess, 288.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wiCzuue14k3kfm3PTVz4Kg_90.JPG: 480x640 (no detections), 290.1ms
Speed: 1.3ms preprocess, 290.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wiCzuue14k3kfm3PTVz4Kg_180.JPG: 480x640 (no detections), 294.3ms
Speed: 1.3ms preprocess, 294.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wiCzuue14k3kfm3PTVz4Kg_270.JPG: 480x640 (no detections), 293.3ms
Speed: 1.0ms preprocess, 293.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wiJ1ghvWjSD0u0FNLOn53w_0.JPG: 480x640 (no detections), 299.3ms
Speed: 1.3ms preprocess, 299.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wiJ1ghvWjSD0u0FNLOn53w_90.JPG: 480x640 (no detections), 295.3ms
Speed: 1.2ms preprocess, 295.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wiJ1ghvWjSD0u0FNLOn53w_180.JPG: 480x640 (no detections), 303.3ms
Speed: 1.2ms preprocess, 303.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wiJ1ghvWjSD0u0FNLOn53w_270.JPG: 480x640 (no detections), 298.8ms
Speed: 1.3ms preprocess, 298.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wiQgOJ5oployctr51r6Umg_0.JPG: 480x640 (no detections), 288.2ms
Speed: 1.0ms preprocess, 288.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wiQgOJ5oployctr51r6Umg_90.JPG: 480x640 (no detections), 294.1ms
Speed: 1.1ms preprocess, 294.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wiQgOJ5oployctr51r6Umg_180.JPG: 480x640 (no detections), 298.0ms
Speed: 1.0ms preprocess, 298.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wiQgOJ5oployctr51r6Umg_270.JPG: 480x640 (no detections), 296.3ms
Speed: 1.1ms preprocess, 296.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wiR3q7CQQvogbljBAvb5-g_0.JPG: 480x640 1 Waste, 288.3ms
Speed: 1.5ms preprocess, 288.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wiR3q7CQQvogbljBAvb5-g_90.JPG: 480x640 (no detections), 289.1ms
Speed: 1.3ms preprocess, 289.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wiR3q7CQQvogbljBAvb5-g_180.JPG: 480x640 (no detections), 314.2ms
Speed: 1.2ms preprocess, 314.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wiR3q7CQQvogbljBAvb5-g_270.JPG: 480x640 (no detections), 299.7ms
Speed: 1.2ms preprocess, 299.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wiRjMaswLuf1MmKZ8UntHg_0.JPG: 480x640 (no detections), 298.3ms
Speed: 1.4ms preprocess, 298.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wiRjMaswLuf1MmKZ8UntHg_90.JPG: 480x640 (no detections), 296.9ms
Speed: 1.1ms preprocess, 296.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wiRjMaswLuf1MmKZ8UntHg_180.JPG: 480x640 (no detections), 295.3ms
Speed: 1.2ms preprocess, 295.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wiRjMaswLuf1MmKZ8UntHg_270.JPG: 480x640 (no detections), 294.3ms
Speed: 1.1ms preprocess, 294.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wiSPSMWfriNW7yC1BPbEKg_0.JPG: 480x640 (no detections), 295.6ms
Speed: 1.2ms preprocess, 295.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wiSPSMWfriNW7yC1BPbEKg_90.JPG: 480x640 (no detections), 294.2ms
Speed: 1.2ms preprocess, 294.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wiSPSMWfriNW7yC1BPbEKg_180.JPG: 480x640 (no detections), 295.0ms
Speed: 1.1ms preprocess, 295.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wiSPSMWfriNW7yC1BPbEKg_270.JPG: 480x640 (no detections), 296.2ms
Speed: 1.2ms preprocess, 296.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wiURbARg_vD4MN3vnxKFOA_0.JPG: 480x640 (no detections), 294.5ms
Speed: 1.1ms preprocess, 294.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wiURbARg_vD4MN3vnxKFOA_90.JPG: 480x640 (no detections), 291.5ms
Speed: 1.3ms preprocess, 291.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wiURbARg_vD4MN3vnxKFOA_180.JPG: 480x640 (no detections), 290.9ms

Speed: 1.5ms preprocess, 290.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wiURbARg_vD4MN3vnxKFOA_270.JPG: 480x640 (no detections), 294.0ms
Speed: 1.5ms preprocess, 294.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wiX7gYYp9s8h-VEAPiMGRw_0.JPG: 480x640 (no detections), 293.6ms
Speed: 1.1ms preprocess, 293.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wiX7gYYp9s8h-VEAPiMGRw_90.JPG: 480x640 (no detections), 299.7ms
Speed: 1.2ms preprocess, 299.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wiX7gYYp9s8h-VEAPiMGRw_180.JPG: 480x640 (no detections), 294.6ms
Speed: 1.3ms preprocess, 294.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wiX7gYYp9s8h-VEAPiMGRw_270.JPG: 480x640 (no detections), 329.9ms
Speed: 1.5ms preprocess, 329.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wiYNmyo9PH2TSsiln7vPcg_0.JPG: 480x640 (no detections), 315.7ms
Speed: 2.0ms preprocess, 315.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wiYNmyo9PH2TSsiln7vPcg_90.JPG: 480x640 (no detections), 313.2ms
Speed: 1.4ms preprocess, 313.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wiYNmyo9PH2TSsiln7vPcg_180.JPG: 480x640 1 Waste, 423.8ms
Speed: 1.2ms preprocess, 423.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wiYNmyo9PH2TSsiln7vPcg_270.JPG: 480x640 (no detections), 292.7ms
Speed: 1.2ms preprocess, 292.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wicRLkXXJfYdMggC3USTSw_0.JPG: 480x640 (no detections), 298.8ms
Speed: 1.6ms preprocess, 298.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wicRLkXXJfYdMggC3USTSw_90.JPG: 480x640 (no detections), 294.8ms
Speed: 1.1ms preprocess, 294.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wicRLkXXJfYdMggC3USTSw_180.JPG: 480x640 (no detections), 293.5ms
Speed: 1.7ms preprocess, 293.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wicRLkXXJfYdMggC3USTSw_270.JPG: 480x640 (no detections), 297.9ms
Speed: 1.1ms preprocess, 297.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wigEaFlAhfImJkJ_-sfd1A_0.JPG: 480x640 (no detections), 291.4ms
Speed: 1.1ms preprocess, 291.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wigEaFlAhfImJkJ_-sfd1A_90.JPG: 480x640 (no detections), 292.8ms
Speed: 1.3ms preprocess, 292.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wigEaFlAhfImJkJ_-sfd1A_180.JPG: 480x640 (no detections), 288.7ms
Speed: 1.0ms preprocess, 288.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wigEaFlAhfImJkJ_-sfd1A_270.JPG: 480x640 (no detections), 295.9ms
Speed: 1.1ms preprocess, 295.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wigY3DrA-bCzeIUnr2uFrQ_0.JPG: 480x640 (no detections), 292.9ms
Speed: 1.4ms preprocess, 292.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wigY3DrA-bCzeIUnr2uFrQ_90.JPG: 480x640 (no detections), 303.9ms
Speed: 1.5ms preprocess, 303.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wigY3DrA-bCzeIUnr2uFrQ_180.JPG: 480x640 (no detections), 300.5ms
Speed: 1.3ms preprocess, 300.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wigY3DrA-bCzeIUnr2uFrQ_270.JPG: 480x640 (no detections), 299.0ms
Speed: 1.2ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wikWxYswkimWjxZpgxh_4Q_0.JPG: 480x640 (no detections), 291.7ms
Speed: 1.2ms preprocess, 291.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wikWxYswkimWjxZpgxh_4Q_90.JPG: 480x640 (no detections), 296.1ms
Speed: 1.5ms preprocess, 296.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wikWxYswkimWjxZpgxh_4Q_180.JPG: 480x640 (no detections), 297.9ms
Speed: 1.2ms preprocess, 297.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wikWxYswkimWjxZpgxh_4Q_270.JPG: 480x640 (no detections), 301.5ms
Speed: 1.1ms preprocess, 301.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wikhEBYrnxDub8-yBZL6JA_0.JPG: 480x640 (no detections), 298.2ms
Speed: 1.1ms preprocess, 298.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wikhEBYrnxDub8-yBZL6JA_90.JPG: 480x640 (no detections), 299.4ms
Speed: 1.2ms preprocess, 299.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wikhEBYrnxDub8-yBZL6JA_180.JPG: 480x640 (no detections), 306.4ms
Speed: 1.1ms preprocess, 306.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wikhEBYrnxDub8-yBZL6JA_270.JPG: 480x640 (no detections), 298.9ms
Speed: 1.2ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wimc9IB_hdmNaYMteR_ZTA_0.JPG: 480x640 (no detections), 305.5ms
Speed: 2.4ms preprocess, 305.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wimc9IB_hdmNaYMteR_ZTA_90.JPG: 480x640 (no detections), 293.7ms
Speed: 1.2ms preprocess, 293.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wimc9IB_hdmNaYMteR_ZTA_180.JPG: 480x640 (no detections), 302.8ms
Speed: 1.2ms preprocess, 302.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wimc9IB_hdmNaYMteR_ZTA_270.JPG: 480x640 (no detections), 296.0ms
Speed: 1.3ms preprocess, 296.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wisMXXLwM86HwSoxvomdyA_0.JPG: 480x640 (no detections), 294.4ms
Speed: 1.2ms preprocess, 294.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wisMXXLwM86HwSoxvomdyA_90.JPG: 480x640 (no detections), 293.9ms
Speed: 1.3ms preprocess, 293.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wisMXXLwM86HwSoxvomdyA_180.JPG: 480x640 (no detections), 291.7ms
Speed: 1.1ms preprocess, 291.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wisMXXLwM86HwSoxvomdyA_270.JPG: 480x640 (no detections), 294.8ms
Speed: 1.4ms preprocess, 294.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wiscssedlt33sJ-sAzgFrw_0.JPG: 480x640 (no detections), 287.2ms
Speed: 1.3ms preprocess, 287.2ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wiscssedlt33sJ-sAzgFrw_90.JPG: 480x640 (no detections), 290.8ms
Speed: 1.7ms preprocess, 290.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wiscssedlt33sJ-sAzgFrw_180.JPG: 480x640 (no detections), 310.6ms
Speed: 1.1ms preprocess, 310.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wiscssedlt33sJ-sAzgFrw_270.JPG: 480x640 (no detections), 292.8ms
Speed: 1.8ms preprocess, 292.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wit7D7mFS4If2PwFPbwNMg_0.JPG: 480x640 (no detections), 300.5ms
Speed: 1.4ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wit7D7mFS4If2PwFPbwNMg_90.JPG: 480x640 (no detections), 329.4ms
Speed: 1.3ms preprocess, 329.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wit7D7mFS4If2PwFPbwNMg_180.JPG: 480x640 (no detections), 309.6ms
Speed: 1.1ms preprocess, 309.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wit7D7mFS4If2PwFPbwNMg_270.JPG: 480x640 (no detections), 311.3ms
Speed: 1.2ms preprocess, 311.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wiwW1MwB_RC3wcYrqUBIew_0.JPG: 480x640 (no detections), 298.4ms
Speed: 1.1ms preprocess, 298.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wiwW1MwB_RC3wcYrqUBIew_90.JPG: 480x640 (no detections), 298.2ms
Speed: 1.2ms preprocess, 298.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wiwW1MwB_RC3wcYrqUBIew_180.JPG: 480x640 (no detections), 292.7ms
Speed: 1.1ms preprocess, 292.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wiwW1MwB_RC3wcYrqUBIew_270.JPG: 480x640 (no detections), 290.6ms
Speed: 1.0ms preprocess, 290.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wizCyMRyg10ruuJ3cJHlwQ_0.JPG: 480x640 (no detections), 293.7ms
Speed: 1.6ms preprocess, 293.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wizCyMRyg10ruuJ3cJHlwQ_90.JPG: 480x640 (no detections), 291.1ms
Speed: 1.2ms preprocess, 291.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wizCyMRyg10ruuJ3cJHlwQ_180.JPG: 480x640 3 Wastes, 299.3ms
Speed: 1.2ms preprocess, 299.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/i/wizCyMRyg10ruuJ3cJHlwQ_270.JPG: 480x640 (no detections), 289.4ms
Speed: 1.2ms preprocess, 289.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wj-ifjbDHO5pgIyGbKp7kQ_0.JPG: 480x640 (no detections), 294.7ms
Speed: 1.5ms preprocess, 294.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wj-ifjbDHO5pgIyGbKp7kQ_90.JPG: 480x640 (no detections), 292.2ms
Speed: 1.1ms preprocess, 292.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wj-ifjbDHO5pgIyGbKp7kQ_180.JPG: 480x640 (no detections), 297.7ms
Speed: 1.6ms preprocess, 297.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wj-ifjbDHO5pgIyGbKp7kQ_270.JPG: 480x640 (no detections), 293.0ms
Speed: 1.1ms preprocess, 293.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wj0q9cfAw0vHuWYOerKu8g_0.JPG: 480x640 (no detections), 293.4ms
Speed: 1.1ms preprocess, 293.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wj0q9cfAw0vHuWYOerKu8g_90.JPG: 480x640 (no detections), 293.6ms
Speed: 1.3ms preprocess, 293.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wj0q9cfAw0vHuWYOerKu8g_180.JPG: 480x640 (no detections), 291.8ms
Speed: 1.6ms preprocess, 291.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wj0q9cfAw0vHuWYOerKu8g_270.JPG: 480x640 (no detections), 297.9ms
Speed: 1.1ms preprocess, 297.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wj3K-CcN0RsU5DXdGXGjnQ_0.JPG: 480x640 (no detections), 299.7ms
Speed: 1.3ms preprocess, 299.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wj3K-CcN0RsU5DXdGXGjnQ_90.JPG: 480x640 1 Waste, 289.6ms
Speed: 1.9ms preprocess, 289.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wj3K-CcN0RsU5DXdGXGjnQ_180.JPG: 480x640 (no detections), 299.9ms
Speed: 1.0ms preprocess, 299.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wj3K-CcN0RsU5DXdGXGjnQ_270.JPG: 480x640 (no detections), 290.4ms
Speed: 1.2ms preprocess, 290.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wj3cSliM29-rbD3YbgYnSQ_0.JPG: 480x640 (no detections), 291.5ms
Speed: 1.1ms preprocess, 291.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wj3cSliM29-rbD3YbgYnSQ_90.JPG: 480x640 (no detections), 294.7ms

Speed: 1.2ms preprocess, 294.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wj3cSliM29-rbD3YbgYnSQ_180.JPG: 480x640 (no detections), 291.5ms
Speed: 1.1ms preprocess, 291.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wj3cSliM29-rbD3YbgYnSQ_270.JPG: 480x640 (no detections), 294.8ms
Speed: 1.1ms preprocess, 294.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wj5EbuwqS1DTNsfs5q4vXw_0.JPG: 480x640 (no detections), 294.5ms
Speed: 1.3ms preprocess, 294.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wj5EbuwqS1DTNsfs5q4vXw_90.JPG: 480x640 (no detections), 289.7ms
Speed: 1.3ms preprocess, 289.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wj5EbuwqS1DTNsfs5q4vXw_180.JPG: 480x640 (no detections), 292.0ms
Speed: 1.1ms preprocess, 292.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wj5EbuwqS1DTNsfs5q4vXw_270.JPG: 480x640 (no detections), 292.2ms
Speed: 1.4ms preprocess, 292.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wj83OiNOsA3kx4Pmc1qJRg_0.JPG: 480x640 (no detections), 295.3ms
Speed: 1.1ms preprocess, 295.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wj83OiNOsA3kx4Pmc1qJRg_90.JPG: 480x640 (no detections), 291.1ms
Speed: 1.0ms preprocess, 291.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wj83OiNOsA3kx4Pmc1qJRg_180.JPG: 480x640 (no detections), 291.2ms
Speed: 1.3ms preprocess, 291.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wj83OiNOsA3kx4Pmc1qJRg_270.JPG: 480x640 (no detections), 296.1ms
Speed: 1.1ms preprocess, 296.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wj8QzutU5LlVnwvURonoOw_0.JPG: 480x640 (no detections), 295.9ms
Speed: 1.1ms preprocess, 295.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wj8QzutU5LlVnwvURonoOw_90.JPG: 480x640 (no detections), 292.9ms
Speed: 1.7ms preprocess, 292.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wj8QzutU5LlVnwvURonoOw_180.JPG: 480x640 (no detections), 291.7ms
Speed: 1.2ms preprocess, 291.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wj8QzutU5LlVnwvURonoOw_270.JPG: 480x640 (no detections), 293.8ms
Speed: 1.3ms preprocess, 293.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjC7dOaGT11nnxZB6WxXKA_0.JPG: 480x640 (no detections), 292.6ms
Speed: 1.3ms preprocess, 292.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjC7dOaGT11nnxZB6WxXKA_90.JPG: 480x640 (no detections), 295.3ms
Speed: 1.2ms preprocess, 295.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjC7dOaGT11nnxZB6WxXKA_180.JPG: 480x640 2 Wastes, 294.4ms
Speed: 1.0ms preprocess, 294.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjC7dOaGT11nnxZB6WxXKA_270.JPG: 480x640 1 Waste, 296.1ms
Speed: 1.9ms preprocess, 296.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjEOfhYLaTRTTkCGBMAnyg_0.JPG: 480x640 1 Waste, 294.1ms
Speed: 1.1ms preprocess, 294.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjEOfhYLaTRTTkCGBMAnyg_90.JPG: 480x640 (no detections), 300.1ms
Speed: 1.3ms preprocess, 300.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjEOfhYLaTRTTkCGBMAnyg_180.JPG: 480x640 2 Wastes, 290.0ms
Speed: 1.2ms preprocess, 290.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjEOfhYLaTRTTkCGBMAnyg_270.JPG: 480x640 1 Waste, 290.1ms
Speed: 1.5ms preprocess, 290.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjFpTqoBxqqxXVAEdfJYTw_0.JPG: 480x640 (no detections), 297.4ms
Speed: 1.3ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjFpTqoBxqqxXVAEdfJYTw_90.JPG: 480x640 (no detections), 292.7ms
Speed: 1.3ms preprocess, 292.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjFpTqoBxqqxXVAEdfJYTw_180.JPG: 480x640 (no detections), 297.9ms
Speed: 1.2ms preprocess, 297.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjFpTqoBxqqxXVAEdfJYTw_270.JPG: 480x640 (no detections), 295.2ms
Speed: 1.1ms preprocess, 295.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjJDHmMK3NkRjxdKejaMmg_0.JPG: 480x640 (no detections), 289.1ms
Speed: 1.2ms preprocess, 289.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjJDHmMK3NkRjxdKejaMmg_90.JPG: 480x640 (no detections), 288.5ms
Speed: 1.1ms preprocess, 288.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjJDHmMK3NkRjxdKejaMmg_180.JPG: 480x640 (no detections), 287.5ms
Speed: 1.2ms preprocess, 287.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjJDHmMK3NkRjxdKejaMmg_270.JPG: 480x640 (no detections), 293.4ms
Speed: 1.2ms preprocess, 293.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjJiYCJZkedFCTlu6-dyCQ_0.JPG: 480x640 (no detections), 291.8ms
Speed: 1.2ms preprocess, 291.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjJiYCJZkedFCTlu6-dyCQ_90.JPG: 480x640 (no detections), 292.7ms
Speed: 1.2ms preprocess, 292.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjJiYCJZkedFCTlu6-dyCQ_180.JPG: 480x640 (no detections), 293.7ms
Speed: 1.0ms preprocess, 293.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjJiYCJZkedFCTlu6-dyCQ_270.JPG: 480x640 (no detections), 299.1ms
Speed: 1.1ms preprocess, 299.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjKzST0wmpCueFDCYJBzaQ_0.JPG: 480x640 (no detections), 295.4ms
Speed: 1.1ms preprocess, 295.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjKzST0wmpCueFDCYJBzaQ_90.JPG: 480x640 (no detections), 295.7ms
Speed: 1.1ms preprocess, 295.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjKzST0wmpCueFDCYJBzaQ_180.JPG: 480x640 (no detections), 295.2ms
Speed: 2.0ms preprocess, 295.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjKzST0wmpCueFDCYJBzaQ_270.JPG: 480x640 (no detections), 292.6ms
Speed: 1.3ms preprocess, 292.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjLxHDEM8elCIpLL3UWihA_0.JPG: 480x640 (no detections), 291.3ms
Speed: 1.2ms preprocess, 291.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjLxHDEM8elCIpLL3UWihA_90.JPG: 480x640 (no detections), 294.1ms
Speed: 1.2ms preprocess, 294.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjLxHDEM8elCIpLL3UWihA_180.JPG: 480x640 (no detections), 290.0ms
Speed: 1.3ms preprocess, 290.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjLxHDEM8elCIpLL3UWihA_270.JPG: 480x640 (no detections), 292.9ms
Speed: 1.5ms preprocess, 292.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjMatPsN0jnddlplBSa-OQ_0.JPG: 480x640 (no detections), 297.1ms
Speed: 1.2ms preprocess, 297.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjMatPsN0jnddlplBSa-OQ_90.JPG: 480x640 (no detections), 289.5ms
Speed: 1.2ms preprocess, 289.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjMatPsN0jnddlplBSa-OQ_180.JPG: 480x640 (no detections), 291.7ms
Speed: 1.7ms preprocess, 291.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjMatPsN0jnddlplBSa-OQ_270.JPG: 480x640 (no detections), 294.5ms
Speed: 1.1ms preprocess, 294.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjNRO8qZFt87f4NXYzsxqg_0.JPG: 480x640 (no detections), 292.1ms
Speed: 1.2ms preprocess, 292.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjNRO8qZFt87f4NXYzsxqg_90.JPG: 480x640 (no detections), 286.9ms
Speed: 1.1ms preprocess, 286.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjNRO8qZFt87f4NXYzsxqg_180.JPG: 480x640 (no detections), 290.2ms
Speed: 1.1ms preprocess, 290.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjNRO8qZFt87f4NXYzsxqg_270.JPG: 480x640 (no detections), 291.4ms
Speed: 1.0ms preprocess, 291.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjOeUm155RBYRdf5ZUBpag_0.JPG: 480x640 (no detections), 292.3ms
Speed: 1.4ms preprocess, 292.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjOeUm155RBYRdf5ZUBpag_90.JPG: 480x640 (no detections), 291.6ms
Speed: 1.5ms preprocess, 291.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjOeUm155RBYRdf5ZUBpag_180.JPG: 480x640 (no detections), 291.3ms
Speed: 1.4ms preprocess, 291.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjOeUm155RBYRdf5ZUBpag_270.JPG: 480x640 (no detections), 293.4ms
Speed: 1.2ms preprocess, 293.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjUUs62_m9tnMO_XlImYUQ_0.JPG: 480x640 (no detections), 290.4ms
Speed: 1.2ms preprocess, 290.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjUUs62_m9tnMO_XlImYUQ_90.JPG: 480x640 (no detections), 287.6ms
Speed: 1.0ms preprocess, 287.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjUUs62_m9tnMO_XlImYUQ_180.JPG: 480x640 (no detections), 290.6ms
Speed: 1.1ms preprocess, 290.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjUUs62_m9tnMO_XlImYUQ_270.JPG: 480x640 (no detections), 292.2ms
Speed: 1.2ms preprocess, 292.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wj_GO_dI0MdwrqMcEr7KKg_0.JPG: 480x640 (no detections), 289.5ms
Speed: 1.4ms preprocess, 289.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wj_GO_dI0MdwrqMcEr7KKg_90.JPG: 480x640 (no detections), 291.8ms
Speed: 1.3ms preprocess, 291.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wj_GO_dI0MdwrqMcEr7KKg_180.JPG: 480x640 (no detections), 294.9ms
Speed: 1.6ms preprocess, 294.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wj_GO_dI0MdwrqMcEr7KKg_270.JPG: 480x640 (no detections), 294.6ms
Speed: 1.4ms preprocess, 294.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wj_z1EwYVIUKQTwrH54T5Q_0.JPG: 480x640 (no detections), 297.0ms
Speed: 1.2ms preprocess, 297.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wj_z1EwYVIUKQTwrH54T5Q_90.JPG: 480x640 (no detections), 291.3ms
Speed: 1.1ms preprocess, 291.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wj_z1EwYVIUKQTwrH54T5Q_180.JPG: 480x640 (no detections), 289.4ms
Speed: 1.4ms preprocess, 289.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wj_z1EwYVIUKQTwrH54T5Q_270.JPG: 480x640 (no detections), 292.3ms
Speed: 1.1ms preprocess, 292.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjbrwPleSWtDC7tl6YXC9Q_0.JPG: 480x640 (no detections), 294.7ms

Speed: 1.1ms preprocess, 294.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjbrwPleSWtDC7tl6YXC9Q_90.JPG: 480x640 (no detections), 290.1ms
Speed: 1.2ms preprocess, 290.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjbrwPleSWtDC7tl6YXC9Q_180.JPG: 480x640 (no detections), 292.8ms
Speed: 1.1ms preprocess, 292.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjbrwPleSWtDC7tl6YXC9Q_270.JPG: 480x640 (no detections), 293.8ms
Speed: 1.1ms preprocess, 293.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjfbO6SXO9MMiyUG7xwpYg_0.JPG: 480x640 (no detections), 294.0ms
Speed: 1.2ms preprocess, 294.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjfbO6SXO9MMiyUG7xwpYg_90.JPG: 480x640 (no detections), 291.0ms
Speed: 1.1ms preprocess, 291.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjfbO6SXO9MMiyUG7xwpYg_180.JPG: 480x640 (no detections), 289.6ms
Speed: 1.1ms preprocess, 289.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjfbO6SXO9MMiyUG7xwpYg_270.JPG: 480x640 (no detections), 298.1ms
Speed: 1.1ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjg_qk1CrDY3-Vc4tUPYCw_0.JPG: 480x640 (no detections), 296.3ms
Speed: 1.2ms preprocess, 296.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjg_qk1CrDY3-Vc4tUPYCw_90.JPG: 480x640 (no detections), 292.7ms
Speed: 1.3ms preprocess, 292.7ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjg_qk1CrDY3-Vc4tUPYCw_180.JPG: 480x640 (no detections), 296.0ms
Speed: 1.3ms preprocess, 296.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjg_qk1CrDY3-Vc4tUPYCw_270.JPG: 480x640 (no detections), 292.8ms
Speed: 1.4ms preprocess, 292.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjgyqB65JdDNl7AM36bkSg_0.JPG: 480x640 (no detections), 291.3ms
Speed: 1.2ms preprocess, 291.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjgyqB65JdDNl7AM36bkSg_90.JPG: 480x640 (no detections), 287.5ms
Speed: 1.1ms preprocess, 287.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjgyqB65JdDNl7AM36bkSg_180.JPG: 480x640 (no detections), 299.4ms
Speed: 1.2ms preprocess, 299.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjgyqB65JdDNl7AM36bkSg_270.JPG: 480x640 (no detections), 292.8ms
Speed: 1.2ms preprocess, 292.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjhQ8BcyZbvTLErkle4cnw_0.JPG: 480x640 (no detections), 293.3ms
Speed: 1.1ms preprocess, 293.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjhQ8BcyZbvTLErkle4cnw_90.JPG: 480x640 (no detections), 290.6ms
Speed: 1.1ms preprocess, 290.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjhQ8BcyZbvTLErkle4cnw_180.JPG: 480x640 (no detections), 290.0ms
Speed: 1.2ms preprocess, 290.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjhQ8BcyZbvTLErkle4cnw_270.JPG: 480x640 (no detections), 294.3ms
Speed: 1.3ms preprocess, 294.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjjJIVGjNqQc1ZK3hhX0bw_0.JPG: 480x640 (no detections), 294.4ms
Speed: 1.2ms preprocess, 294.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjjJIVGjNqQc1ZK3hhX0bw_90.JPG: 480x640 (no detections), 288.5ms
Speed: 1.3ms preprocess, 288.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjjJIVGjNqQc1ZK3hhX0bw_180.JPG: 480x640 (no detections), 287.4ms
Speed: 1.1ms preprocess, 287.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjjJIVGjNqQc1ZK3hhX0bw_270.JPG: 480x640 (no detections), 290.2ms
Speed: 1.1ms preprocess, 290.2ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjkqAeFB0Hl1dRQU7BQ2cQ_0.JPG: 480x640 (no detections), 285.3ms
Speed: 1.0ms preprocess, 285.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjkqAeFB0Hl1dRQU7BQ2cQ_90.JPG: 480x640 (no detections), 292.4ms
Speed: 1.1ms preprocess, 292.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjkqAeFB0Hl1dRQU7BQ2cQ_180.JPG: 480x640 (no detections), 293.2ms
Speed: 1.2ms preprocess, 293.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjkqAeFB0Hl1dRQU7BQ2cQ_270.JPG: 480x640 (no detections), 290.2ms
Speed: 1.1ms preprocess, 290.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjmvZgHGrGStGKGJ6dW-Qw_0.JPG: 480x640 (no detections), 290.8ms
Speed: 1.4ms preprocess, 290.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjmvZgHGrGStGKGJ6dW-Qw_90.JPG: 480x640 (no detections), 294.8ms
Speed: 1.2ms preprocess, 294.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjmvZgHGrGStGKGJ6dW-Qw_180.JPG: 480x640 (no detections), 292.7ms
Speed: 1.2ms preprocess, 292.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjmvZgHGrGStGKGJ6dW-Qw_270.JPG: 480x640 (no detections), 291.5ms
Speed: 1.1ms preprocess, 291.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjnX415Aq78FmODg6WWLbg_0.JPG: 480x640 (no detections), 293.2ms
Speed: 1.1ms preprocess, 293.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjnX415Aq78FmODg6WWLbg_90.JPG: 480x640 (no detections), 290.8ms
Speed: 1.3ms preprocess, 290.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjnX415Aq78FmODg6WWLbg_180.JPG: 480x640 (no detections), 299.3ms
Speed: 1.4ms preprocess, 299.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjnX415Aq78FmODg6WWLbg_270.JPG: 480x640 (no detections), 290.1ms
Speed: 1.3ms preprocess, 290.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjotppWVMMo9bBqdD6e3Ug_0.JPG: 480x640 (no detections), 281.6ms
Speed: 1.8ms preprocess, 281.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjotppWVMMo9bBqdD6e3Ug_90.JPG: 480x640 (no detections), 289.8ms
Speed: 1.1ms preprocess, 289.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjotppWVMMo9bBqdD6e3Ug_180.JPG: 480x640 (no detections), 292.5ms
Speed: 1.1ms preprocess, 292.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjotppWVMMo9bBqdD6e3Ug_270.JPG: 480x640 (no detections), 291.0ms
Speed: 1.7ms preprocess, 291.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjpQK_t88dQ-3jcMPkqtog_0.JPG: 480x640 (no detections), 293.0ms
Speed: 1.4ms preprocess, 293.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjpQK_t88dQ-3jcMPkqtog_90.JPG: 480x640 1 Waste, 294.6ms
Speed: 1.3ms preprocess, 294.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjpQK_t88dQ-3jcMPkqtog_180.JPG: 480x640 1 Waste, 292.6ms
Speed: 1.2ms preprocess, 292.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjpQK_t88dQ-3jcMPkqtog_270.JPG: 480x640 (no detections), 297.3ms
Speed: 1.1ms preprocess, 297.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjpYWb9ZajNW-KQicT1psA_0.JPG: 480x640 (no detections), 289.2ms
Speed: 1.1ms preprocess, 289.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjpYWb9ZajNW-KQicT1psA_90.JPG: 480x640 (no detections), 294.0ms
Speed: 1.1ms preprocess, 294.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjpYWb9ZajNW-KQicT1psA_180.JPG: 480x640 (no detections), 292.0ms
Speed: 1.3ms preprocess, 292.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjpYWb9ZajNW-KQicT1psA_270.JPG: 480x640 (no detections), 288.0ms
Speed: 1.1ms preprocess, 288.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjqoZ3MS0V3_ghWs-j1ZPA_0.JPG: 480x640 (no detections), 292.9ms
Speed: 1.3ms preprocess, 292.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjqoZ3MS0V3_ghWs-j1ZPA_90.JPG: 480x640 (no detections), 293.4ms
Speed: 1.2ms preprocess, 293.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjqoZ3MS0V3_ghWs-j1ZPA_180.JPG: 480x640 (no detections), 291.7ms
Speed: 1.1ms preprocess, 291.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjqoZ3MS0V3_ghWs-j1ZPA_270.JPG: 480x640 (no detections), 292.5ms
Speed: 1.0ms preprocess, 292.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjy4UKRDWdF9ocfoIZGNyw_0.JPG: 480x640 (no detections), 291.2ms
Speed: 1.3ms preprocess, 291.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjy4UKRDWdF9ocfoIZGNyw_90.JPG: 480x640 (no detections), 292.9ms
Speed: 1.2ms preprocess, 292.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjy4UKRDWdF9ocfoIZGNyw_180.JPG: 480x640 (no detections), 293.4ms
Speed: 1.2ms preprocess, 293.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjy4UKRDWdF9ocfoIZGNyw_270.JPG: 480x640 (no detections), 295.2ms
Speed: 1.2ms preprocess, 295.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjz8zLjmKm8GjlepNHIvYQ_0.JPG: 480x640 (no detections), 292.5ms
Speed: 1.0ms preprocess, 292.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjz8zLjmKm8GjlepNHIvYQ_90.JPG: 480x640 (no detections), 289.6ms
Speed: 1.2ms preprocess, 289.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjz8zLjmKm8GjlepNHIvYQ_180.JPG: 480x640 (no detections), 292.2ms
Speed: 1.0ms preprocess, 292.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/j/wjz8zLjmKm8GjlepNHIvYQ_270.JPG: 480x640 (no detections), 294.7ms
Speed: 1.1ms preprocess, 294.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wk-P66Um3D83eGpXy5ThtQ_0.JPG: 480x640 (no detections), 289.5ms
Speed: 1.5ms preprocess, 289.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wk-P66Um3D83eGpXy5ThtQ_90.JPG: 480x640 (no detections), 286.3ms
Speed: 1.1ms preprocess, 286.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wk-P66Um3D83eGpXy5ThtQ_180.JPG: 480x640 (no detections), 300.3ms
Speed: 1.0ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wk-P66Um3D83eGpXy5ThtQ_270.JPG: 480x640 (no detections), 293.3ms
Speed: 1.1ms preprocess, 293.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wk1fJz0FPVkCI3WjSaIM9A_0.JPG: 480x640 (no detections), 293.6ms
Speed: 1.1ms preprocess, 293.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wk1fJz0FPVkCI3WjSaIM9A_90.JPG: 480x640 (no detections), 291.5ms
Speed: 1.2ms preprocess, 291.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wk1fJz0FPVkCI3WjSaIM9A_180.JPG: 480x640 (no detections), 293.0ms
Speed: 1.1ms preprocess, 293.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wk1fJz0FPVkCI3WjSaIM9A_270.JPG: 480x640 (no detections), 289.6ms

Speed: 1.2ms preprocess, 289.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wk4io9_g2ZW5HV5KKNH6gQ_0.JPG: 480x640 (no detections), 294.7ms
Speed: 1.2ms preprocess, 294.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wk4io9_g2ZW5HV5KKNH6gQ_90.JPG: 480x640 (no detections), 293.0ms
Speed: 1.1ms preprocess, 293.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wk4io9_g2ZW5HV5KKNH6gQ_180.JPG: 480x640 (no detections), 291.2ms
Speed: 1.2ms preprocess, 291.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wk4io9_g2ZW5HV5KKNH6gQ_270.JPG: 480x640 (no detections), 293.6ms
Speed: 1.8ms preprocess, 293.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wk5KE15lSHQwvLLdFFQpUA_0.JPG: 480x640 1 Waste, 292.9ms
Speed: 1.2ms preprocess, 292.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wk5KE15lSHQwvLLdFFQpUA_90.JPG: 480x640 1 Waste, 289.2ms
Speed: 1.2ms preprocess, 289.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wk5KE15lSHQwvLLdFFQpUA_180.JPG: 480x640 1 Waste, 297.8ms
Speed: 1.1ms preprocess, 297.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wk5KE15lSHQwvLLdFFQpUA_270.JPG: 480x640 (no detections), 297.4ms
Speed: 1.2ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wk74UtlFkBctxS8nMtOw1g_0.JPG: 480x640 (no detections), 295.9ms
Speed: 1.1ms preprocess, 295.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wk74UtlFkBctxS8nMtOw1g_90.JPG: 480x640 (no detections), 296.0ms
Speed: 1.1ms preprocess, 296.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wk74UtlFkBctxS8nMtOw1g_180.JPG: 480x640 (no detections), 296.5ms
Speed: 1.0ms preprocess, 296.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wk74UtlFkBctxS8nMtOw1g_270.JPG: 480x640 1 Waste, 294.2ms
Speed: 1.5ms preprocess, 294.2ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wk8qRLfSJitQ5GLBxGgsDA_0.JPG: 480x640 (no detections), 296.0ms
Speed: 1.4ms preprocess, 296.0ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wk8qRLfSJitQ5GLBxGgsDA_90.JPG: 480x640 (no detections), 290.1ms
Speed: 1.3ms preprocess, 290.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wk8qRLfSJitQ5GLBxGgsDA_180.JPG: 480x640 (no detections), 291.5ms
Speed: 1.4ms preprocess, 291.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wk8qRLfSJitQ5GLBxGgsDA_270.JPG: 480x640 (no detections), 295.3ms
Speed: 1.4ms preprocess, 295.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkE6bEynOQzD2JBh91jKVw_0.JPG: 480x640 (no detections), 292.2ms
Speed: 1.5ms preprocess, 292.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkE6bEynOQzD2JBh91jKVw_90.JPG: 480x640 (no detections), 292.5ms
Speed: 1.2ms preprocess, 292.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkE6bEynOQzD2JBh91jKVw_180.JPG: 480x640 (no detections), 290.5ms
Speed: 1.6ms preprocess, 290.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkE6bEynOQzD2JBh91jKVw_270.JPG: 480x640 (no detections), 299.5ms
Speed: 1.0ms preprocess, 299.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkE8D-n7wnBdfChDftbdBg_0.JPG: 480x640 (no detections), 292.0ms
Speed: 1.8ms preprocess, 292.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkE8D-n7wnBdfChDftbdBg_90.JPG: 480x640 (no detections), 296.4ms
Speed: 1.5ms preprocess, 296.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkE8D-n7wnBdfChDftbdBg_180.JPG: 480x640 (no detections), 290.0ms
Speed: 1.2ms preprocess, 290.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkE8D-n7wnBdfChDftbdBg_270.JPG: 480x640 (no detections), 295.1ms
Speed: 1.1ms preprocess, 295.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkFI2hHyTqMTVaCiX5EGsQ_0.JPG: 480x640 (no detections), 296.8ms
Speed: 1.0ms preprocess, 296.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkFI2hHyTqMTVaCiX5EGsQ_90.JPG: 480x640 (no detections), 290.4ms
Speed: 1.0ms preprocess, 290.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkFI2hHyTqMTVaCiX5EGsQ_180.JPG: 480x640 (no detections), 291.9ms
Speed: 1.1ms preprocess, 291.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkFI2hHyTqMTVaCiX5EGsQ_270.JPG: 480x640 (no detections), 293.8ms
Speed: 1.3ms preprocess, 293.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkGEvM2NyktU5hKRNcBNlA_0.JPG: 480x640 (no detections), 296.3ms
Speed: 1.4ms preprocess, 296.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkGEvM2NyktU5hKRNcBNlA_90.JPG: 480x640 (no detections), 298.4ms
Speed: 1.3ms preprocess, 298.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkGEvM2NyktU5hKRNcBNlA_180.JPG: 480x640 (no detections), 294.5ms
Speed: 1.5ms preprocess, 294.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkGEvM2NyktU5hKRNcBNlA_270.JPG: 480x640 (no detections), 293.6ms
Speed: 1.2ms preprocess, 293.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkJ9WBny_THnqVg79Vwo_g_0.JPG: 480x640 (no detections), 292.4ms
Speed: 1.1ms preprocess, 292.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkJ9WBny_THnqVg79Vwo_g_90.JPG: 480x640 (no detections), 294.3ms
Speed: 1.1ms preprocess, 294.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkJ9WBny_THnqVg79Vwo_g_180.JPG: 480x640 (no detections), 296.3ms
Speed: 1.3ms preprocess, 296.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkJ9WBny_THnqVg79Vwo_g_270.JPG: 480x640 (no detections), 295.5ms
Speed: 1.4ms preprocess, 295.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkJgNW50_fMr0EAirhoktQ_0.JPG: 480x640 (no detections), 295.7ms
Speed: 1.2ms preprocess, 295.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkJgNW50_fMr0EAirhoktQ_90.JPG: 480x640 (no detections), 297.6ms
Speed: 1.2ms preprocess, 297.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkJgNW50_fMr0EAirhoktQ_180.JPG: 480x640 (no detections), 290.8ms
Speed: 1.1ms preprocess, 290.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkJgNW50_fMr0EAirhoktQ_270.JPG: 480x640 (no detections), 295.4ms
Speed: 1.5ms preprocess, 295.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkS0dpPbx8CJNSClMfYU0w_0.JPG: 480x640 (no detections), 293.5ms
Speed: 1.2ms preprocess, 293.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkS0dpPbx8CJNSClMfYU0w_90.JPG: 480x640 (no detections), 291.4ms
Speed: 1.2ms preprocess, 291.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkS0dpPbx8CJNSClMfYU0w_180.JPG: 480x640 (no detections), 285.8ms
Speed: 1.0ms preprocess, 285.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkS0dpPbx8CJNSClMfYU0w_270.JPG: 480x640 (no detections), 288.8ms
Speed: 1.2ms preprocess, 288.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkTRTUtLQFzUulovDNk8Gw_0.JPG: 480x640 (no detections), 291.1ms
Speed: 1.1ms preprocess, 291.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkTRTUtLQFzUulovDNk8Gw_90.JPG: 480x640 (no detections), 291.4ms
Speed: 1.1ms preprocess, 291.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkTRTUtLQFzUulovDNk8Gw_180.JPG: 480x640 (no detections), 289.4ms
Speed: 1.0ms preprocess, 289.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkTRTUtLQFzUulovDNk8Gw_270.JPG: 480x640 (no detections), 289.9ms
Speed: 1.1ms preprocess, 289.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkTXzP-nPA0d1BQYT68S0Q_0.JPG: 480x640 (no detections), 294.9ms
Speed: 1.4ms preprocess, 294.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkTXzP-nPA0d1BQYT68S0Q_90.JPG: 480x640 (no detections), 295.5ms
Speed: 1.3ms preprocess, 295.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkTXzP-nPA0d1BQYT68S0Q_180.JPG: 480x640 (no detections), 296.7ms
Speed: 1.1ms preprocess, 296.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkTXzP-nPA0d1BQYT68S0Q_270.JPG: 480x640 (no detections), 306.5ms
Speed: 1.2ms preprocess, 306.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkTiH-Dp00nplne6_yaJdw_0.JPG: 480x640 (no detections), 296.4ms
Speed: 1.1ms preprocess, 296.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkTiH-Dp00nplne6_yaJdw_90.JPG: 480x640 (no detections), 296.7ms
Speed: 1.2ms preprocess, 296.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkTiH-Dp00nplne6_yaJdw_180.JPG: 480x640 (no detections), 318.3ms
Speed: 1.0ms preprocess, 318.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkTiH-Dp00nplne6_yaJdw_270.JPG: 480x640 (no detections), 298.3ms
Speed: 1.3ms preprocess, 298.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkTnIUqgPSLEgZz4dbRYRQ_0.JPG: 480x640 (no detections), 293.8ms
Speed: 1.1ms preprocess, 293.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkTnIUqgPSLEgZz4dbRYRQ_90.JPG: 480x640 (no detections), 289.8ms
Speed: 1.1ms preprocess, 289.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkTnIUqgPSLEgZz4dbRYRQ_180.JPG: 480x640 (no detections), 292.2ms
Speed: 1.1ms preprocess, 292.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkTnIUqgPSLEgZz4dbRYRQ_270.JPG: 480x640 (no detections), 293.9ms
Speed: 1.2ms preprocess, 293.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkac3kXrrv3O0g7iCRm95g_0.JPG: 480x640 (no detections), 294.5ms
Speed: 1.2ms preprocess, 294.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkac3kXrrv3O0g7iCRm95g_90.JPG: 480x640 (no detections), 296.5ms
Speed: 1.1ms preprocess, 296.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkac3kXrrv3O0g7iCRm95g_180.JPG: 480x640 (no detections), 292.8ms
Speed: 1.4ms preprocess, 292.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkac3kXrrv3O0g7iCRm95g_270.JPG: 480x640 (no detections), 294.7ms
Speed: 1.1ms preprocess, 294.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wket4nPcc4P9TaS4xOh1vg_0.JPG: 480x640 (no detections), 295.6ms
Speed: 1.1ms preprocess, 295.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wket4nPcc4P9TaS4xOh1vg_90.JPG: 480x640 (no detections), 296.2ms
Speed: 1.3ms preprocess, 296.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wket4nPcc4P9TaS4xOh1vg_180.JPG: 480x640 (no detections), 295.0ms

Speed: 1.1ms preprocess, 295.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wket4nPcc4P9TaS4xOh1vg_270.JPG: 480x640 (no detections), 293.4ms
Speed: 1.4ms preprocess, 293.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkfrRoA2TuicTl9b7jyoTA_0.JPG: 480x640 (no detections), 290.7ms
Speed: 1.1ms preprocess, 290.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkfrRoA2TuicTl9b7jyoTA_90.JPG: 480x640 (no detections), 291.9ms
Speed: 1.1ms preprocess, 291.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkfrRoA2TuicTl9b7jyoTA_180.JPG: 480x640 (no detections), 297.4ms
Speed: 1.1ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkfrRoA2TuicTl9b7jyoTA_270.JPG: 480x640 (no detections), 293.4ms
Speed: 1.1ms preprocess, 293.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkiWZVMusdK9jon39ZmCMw_0.JPG: 480x640 1 Waste, 293.7ms
Speed: 1.0ms preprocess, 293.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkiWZVMusdK9jon39ZmCMw_90.JPG: 480x640 1 Waste, 292.9ms
Speed: 1.1ms preprocess, 292.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkiWZVMusdK9jon39ZmCMw_180.JPG: 480x640 (no detections), 296.0ms
Speed: 1.1ms preprocess, 296.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkiWZVMusdK9jon39ZmCMw_270.JPG: 480x640 (no detections), 291.8ms
Speed: 1.2ms preprocess, 291.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkmsVs_9Sj6JbAeOCAW_WA_0.JPG: 480x640 (no detections), 297.9ms
Speed: 1.5ms preprocess, 297.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkmsVs_9Sj6JbAeOCAW_WA_90.JPG: 480x640 (no detections), 299.3ms
Speed: 1.1ms preprocess, 299.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkmsVs_9Sj6JbAeOCAW_WA_180.JPG: 480x640 (no detections), 290.6ms
Speed: 1.1ms preprocess, 290.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkmsVs_9Sj6JbAeOCAW_WA_270.JPG: 480x640 1 Waste, 291.9ms
Speed: 1.2ms preprocess, 291.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkqIW4nTonAlI7Cnf5FlqA_0.JPG: 480x640 (no detections), 299.4ms
Speed: 1.1ms preprocess, 299.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkqIW4nTonAlI7Cnf5FlqA_90.JPG: 480x640 (no detections), 299.7ms
Speed: 1.6ms preprocess, 299.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkqIW4nTonAlI7Cnf5FlqA_180.JPG: 480x640 (no detections), 304.0ms
Speed: 1.4ms preprocess, 304.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkqIW4nTonAlI7Cnf5FlqA_270.JPG: 480x640 (no detections), 445.3ms
Speed: 1.2ms preprocess, 445.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkr2d3xwVWxGwQ4ffUrjqA_0.JPG: 480x640 (no detections), 380.0ms
Speed: 1.6ms preprocess, 380.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkr2d3xwVWxGwQ4ffUrjqA_90.JPG: 480x640 (no detections), 314.2ms
Speed: 1.2ms preprocess, 314.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkr2d3xwVWxGwQ4ffUrjqA_180.JPG: 480x640 (no detections), 326.7ms
Speed: 1.2ms preprocess, 326.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkr2d3xwVWxGwQ4ffUrjqA_270.JPG: 480x640 (no detections), 332.0ms
Speed: 1.3ms preprocess, 332.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkvCBfV2zBO0csmRHnFeYg_0.JPG: 480x640 (no detections), 340.6ms
Speed: 1.4ms preprocess, 340.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkvCBfV2zBO0csmRHnFeYg_90.JPG: 480x640 (no detections), 336.8ms
Speed: 1.3ms preprocess, 336.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkvCBfV2zBO0csmRHnFeYg_180.JPG: 480x640 (no detections), 322.6ms
Speed: 1.3ms preprocess, 322.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkvCBfV2zBO0csmRHnFeYg_270.JPG: 480x640 (no detections), 319.3ms
Speed: 1.2ms preprocess, 319.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkxCxftvQ43Hh30FFvZghA_0.JPG: 480x640 1 Waste, 322.5ms
Speed: 1.9ms preprocess, 322.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkxCxftvQ43Hh30FFvZghA_90.JPG: 480x640 (no detections), 296.3ms
Speed: 1.2ms preprocess, 296.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkxCxftvQ43Hh30FFvZghA_180.JPG: 480x640 (no detections), 293.5ms
Speed: 1.1ms preprocess, 293.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkxCxftvQ43Hh30FFvZghA_270.JPG: 480x640 (no detections), 289.4ms
Speed: 1.1ms preprocess, 289.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkzM8ujnQOB_5DA4AvAfZg_0.JPG: 480x640 (no detections), 308.1ms
Speed: 1.2ms preprocess, 308.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkzM8ujnQOB_5DA4AvAfZg_90.JPG: 480x640 (no detections), 289.9ms
Speed: 1.1ms preprocess, 289.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkzM8ujnQOB_5DA4AvAfZg_180.JPG: 480x640 (no detections), 293.1ms
Speed: 1.1ms preprocess, 293.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/K/wkzM8ujnQOB_5DA4AvAfZg_270.JPG: 480x640 (no detections), 289.1ms
Speed: 1.1ms preprocess, 289.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wl1B5uv9QogV_uhTJvVJkA_0.JPG: 480x640 (no detections), 296.5ms
Speed: 1.3ms preprocess, 296.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wl1B5uv9QogV_uhTJvVJkA_90.JPG: 480x640 (no detections), 292.5ms
Speed: 1.2ms preprocess, 292.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wl1B5uv9QogV_uhTJvVJkA_180.JPG: 480x640 (no detections), 292.5ms
Speed: 1.1ms preprocess, 292.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wl1B5uv9QogV_uhTJvVJkA_270.JPG: 480x640 (no detections), 304.3ms
Speed: 1.2ms preprocess, 304.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wl2s53I-7Xl8Yp0Mm2D3aQ_0.JPG: 480x640 (no detections), 291.9ms
Speed: 1.2ms preprocess, 291.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wl2s53I-7Xl8Yp0Mm2D3aQ_90.JPG: 480x640 (no detections), 296.6ms
Speed: 1.1ms preprocess, 296.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wl2s53I-7Xl8Yp0Mm2D3aQ_180.JPG: 480x640 (no detections), 305.5ms
Speed: 1.4ms preprocess, 305.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wl2s53I-7Xl8Yp0Mm2D3aQ_270.JPG: 480x640 (no detections), 290.8ms
Speed: 1.3ms preprocess, 290.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wl5USHjuMECJ9mYkOhLN3g_0.JPG: 480x640 (no detections), 293.9ms
Speed: 1.2ms preprocess, 293.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wl5USHjuMECJ9mYkOhLN3g_90.JPG: 480x640 (no detections), 287.8ms
Speed: 1.2ms preprocess, 287.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wl5USHjuMECJ9mYkOhLN3g_180.JPG: 480x640 (no detections), 288.9ms
Speed: 1.4ms preprocess, 288.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wl5USHjuMECJ9mYkOhLN3g_270.JPG: 480x640 (no detections), 296.2ms
Speed: 1.1ms preprocess, 296.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wl5m_-uFJXYtBNavSjnM7A_0.JPG: 480x640 (no detections), 294.6ms
Speed: 1.1ms preprocess, 294.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wl5m_-uFJXYtBNavSjnM7A_90.JPG: 480x640 (no detections), 312.3ms
Speed: 1.1ms preprocess, 312.3ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wl5m_-uFJXYtBNavSjnM7A_180.JPG: 480x640 (no detections), 309.8ms
Speed: 1.3ms preprocess, 309.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wl5m_-uFJXYtBNavSjnM7A_270.JPG: 480x640 (no detections), 293.6ms
Speed: 1.3ms preprocess, 293.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wl6H2OvequAyZpRFPrhhWQ_0.JPG: 480x640 (no detections), 311.3ms
Speed: 1.1ms preprocess, 311.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wl6H2OvequAyZpRFPrhhWQ_90.JPG: 480x640 (no detections), 316.1ms
Speed: 1.5ms preprocess, 316.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wl6H2OvequAyZpRFPrhhWQ_180.JPG: 480x640 (no detections), 428.3ms
Speed: 1.4ms preprocess, 428.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wl6H2OvequAyZpRFPrhhWQ_270.JPG: 480x640 (no detections), 307.7ms
Speed: 1.4ms preprocess, 307.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wl6Hw6QBodftHTF1DpafCA_0.JPG: 480x640 (no detections), 293.0ms
Speed: 1.2ms preprocess, 293.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wl6Hw6QBodftHTF1DpafCA_90.JPG: 480x640 (no detections), 296.8ms
Speed: 1.2ms preprocess, 296.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wl6Hw6QBodftHTF1DpafCA_180.JPG: 480x640 (no detections), 304.0ms
Speed: 1.2ms preprocess, 304.0ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wl6Hw6QBodftHTF1DpafCA_270.JPG: 480x640 (no detections), 298.8ms
Speed: 1.2ms preprocess, 298.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlFkyB05VMsFcR_k7XhhQg_0.JPG: 480x640 (no detections), 301.7ms
Speed: 1.2ms preprocess, 301.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlFkyB05VMsFcR_k7XhhQg_90.JPG: 480x640 (no detections), 295.4ms
Speed: 1.2ms preprocess, 295.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlFkyB05VMsFcR_k7XhhQg_180.JPG: 480x640 (no detections), 298.6ms
Speed: 1.2ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlFkyB05VMsFcR_k7XhhQg_270.JPG: 480x640 (no detections), 295.3ms
Speed: 1.4ms preprocess, 295.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlIPj4rmS1MCeS10pOOevQ_0.JPG: 480x640 (no detections), 293.1ms
Speed: 1.5ms preprocess, 293.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlIPj4rmS1MCeS10pOOevQ_90.JPG: 480x640 (no detections), 290.0ms
Speed: 1.3ms preprocess, 290.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlIPj4rmS1MCeS10pOOevQ_180.JPG: 480x640 (no detections), 297.1ms
Speed: 1.2ms preprocess, 297.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlIPj4rmS1MCeS10pOOevQ_270.JPG: 480x640 (no detections), 290.8ms
Speed: 1.1ms preprocess, 290.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlJAwqb_AwrAyD2Kmsxplw_0.JPG: 480x640 (no detections), 292.5ms
Speed: 1.0ms preprocess, 292.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlJAwqb_AwrAyD2Kmsxplw_90.JPG: 480x640 (no detections), 288.7ms

Speed: 1.1ms preprocess, 288.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlJAwqb_AwrAyD2Kmsxplw_180.JPG: 480x640 (no detections), 290.1ms
Speed: 1.1ms preprocess, 290.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlJAwqb_AwrAyD2Kmsxplw_270.JPG: 480x640 (no detections), 290.8ms
Speed: 1.3ms preprocess, 290.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlJFBMC9HMP_WhH-cPDUfQ_0.JPG: 480x640 (no detections), 288.0ms
Speed: 1.6ms preprocess, 288.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlJFBMC9HMP_WhH-cPDUfQ_90.JPG: 480x640 (no detections), 291.8ms
Speed: 1.2ms preprocess, 291.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlJFBMC9HMP_WhH-cPDUfQ_180.JPG: 480x640 (no detections), 287.1ms
Speed: 1.1ms preprocess, 287.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlJFBMC9HMP_WhH-cPDUfQ_270.JPG: 480x640 (no detections), 293.3ms
Speed: 1.1ms preprocess, 293.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlOWZfihRK4ONLTqgg7JWA_0.JPG: 480x640 (no detections), 286.9ms
Speed: 1.1ms preprocess, 286.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlOWZfihRK4ONLTqgg7JWA_90.JPG: 480x640 (no detections), 291.7ms
Speed: 1.1ms preprocess, 291.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlOWZfihRK4ONLTqgg7JWA_180.JPG: 480x640 (no detections), 293.7ms
Speed: 1.1ms preprocess, 293.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlOWZfihRK4ONLTqgg7JWA_270.JPG: 480x640 (no detections), 288.9ms
Speed: 1.2ms preprocess, 288.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlTw9j39eIRZltShVid9ew_0.JPG: 480x640 (no detections), 291.9ms
Speed: 1.0ms preprocess, 291.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlTw9j39eIRZltShVid9ew_90.JPG: 480x640 (no detections), 293.8ms
Speed: 1.3ms preprocess, 293.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlTw9j39eIRZltShVid9ew_180.JPG: 480x640 (no detections), 296.2ms
Speed: 1.2ms preprocess, 296.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlTw9j39eIRZltShVid9ew_270.JPG: 480x640 (no detections), 295.2ms
Speed: 1.4ms preprocess, 295.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlV5Op2a1Ck_AxGo7Kn-pQ_0.JPG: 480x640 1 Waste, 294.6ms
Speed: 1.3ms preprocess, 294.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlV5Op2a1Ck_AxGo7Kn-pQ_90.JPG: 480x640 (no detections), 294.9ms
Speed: 1.2ms preprocess, 294.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlV5Op2a1Ck_AxGo7Kn-pQ_180.JPG: 480x640 (no detections), 293.1ms
Speed: 1.1ms preprocess, 293.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlV5Op2a1Ck_AxGo7Kn-pQ_270.JPG: 480x640 (no detections), 289.7ms
Speed: 1.3ms preprocess, 289.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlXmw3hvaPxsqjyfuC6hZQ_0.JPG: 480x640 (no detections), 294.4ms
Speed: 1.2ms preprocess, 294.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlXmw3hvaPxsqjyfuC6hZQ_90.JPG: 480x640 (no detections), 300.6ms
Speed: 1.1ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlXmw3hvaPxsqjyfuC6hZQ_180.JPG: 480x640 (no detections), 291.7ms
Speed: 1.3ms preprocess, 291.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlXmw3hvaPxsqjyfuC6hZQ_270.JPG: 480x640 (no detections), 296.5ms
Speed: 1.2ms preprocess, 296.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlZxE9CV7FCnwVd11UEZfw_0.JPG: 480x640 (no detections), 294.6ms
Speed: 1.5ms preprocess, 294.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlZxE9CV7FCnwVd11UEZfw_90.JPG: 480x640 (no detections), 295.4ms
Speed: 1.1ms preprocess, 295.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlZxE9CV7FCnwVd11UEZfw_180.JPG: 480x640 (no detections), 290.4ms
Speed: 1.2ms preprocess, 290.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlZxE9CV7FCnwVd11UEZfw_270.JPG: 480x640 (no detections), 291.3ms
Speed: 1.2ms preprocess, 291.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlecafxt1xfvcwNwp5FpVA_0.JPG: 480x640 (no detections), 291.9ms
Speed: 1.2ms preprocess, 291.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlecafxt1xfvcwNwp5FpVA_90.JPG: 480x640 (no detections), 290.0ms
Speed: 1.2ms preprocess, 290.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlecafxt1xfvcwNwp5FpVA_180.JPG: 480x640 (no detections), 299.5ms
Speed: 1.2ms preprocess, 299.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlecafxt1xfvcwNwp5FpVA_270.JPG: 480x640 (no detections), 293.1ms
Speed: 1.0ms preprocess, 293.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlgnYE5YcnRUmyUQGUMgYA_0.JPG: 480x640 (no detections), 292.9ms
Speed: 1.2ms preprocess, 292.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlgnYE5YcnRUmyUQGUMgYA_90.JPG: 480x640 1 Waste, 291.2ms
Speed: 1.3ms preprocess, 291.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlgnYE5YcnRUmyUQGUMgYA_180.JPG: 480x640 (no detections), 293.5ms
Speed: 1.3ms preprocess, 293.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlgnYE5YcnRUmyUQGUMgYA_270.JPG: 480x640 (no detections), 290.6ms
Speed: 1.5ms preprocess, 290.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wljOSq4FRGAWcNLhwpt92w_0.JPG: 480x640 (no detections), 291.6ms
Speed: 1.3ms preprocess, 291.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wljOSq4FRGAWcNLhwpt92w_90.JPG: 480x640 1 Waste, 290.4ms
Speed: 1.2ms preprocess, 290.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wljOSq4FRGAWcNLhwpt92w_180.JPG: 480x640 (no detections), 294.9ms
Speed: 1.2ms preprocess, 294.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wljOSq4FRGAWcNLhwpt92w_270.JPG: 480x640 (no detections), 291.2ms
Speed: 1.2ms preprocess, 291.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wllDakZRBa29dNSbiYddng_0.JPG: 480x640 (no detections), 294.5ms
Speed: 1.2ms preprocess, 294.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wllDakZRBa29dNSbiYddng_90.JPG: 480x640 (no detections), 295.0ms
Speed: 1.1ms preprocess, 295.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wllDakZRBa29dNSbiYddng_180.JPG: 480x640 (no detections), 292.3ms
Speed: 1.1ms preprocess, 292.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wllDakZRBa29dNSbiYddng_270.JPG: 480x640 (no detections), 291.4ms
Speed: 1.1ms preprocess, 291.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlocc4mt3T8MzQrFG_LUtQ_0.JPG: 480x640 (no detections), 294.4ms
Speed: 1.1ms preprocess, 294.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlocc4mt3T8MzQrFG_LUtQ_90.JPG: 480x640 (no detections), 292.8ms
Speed: 1.3ms preprocess, 292.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlocc4mt3T8MzQrFG_LUtQ_180.JPG: 480x640 (no detections), 293.8ms
Speed: 1.2ms preprocess, 293.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlocc4mt3T8MzQrFG_LUtQ_270.JPG: 480x640 (no detections), 293.1ms
Speed: 1.1ms preprocess, 293.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlr9byQqsuRk7xA4i9D2mA_0.JPG: 480x640 (no detections), 298.8ms
Speed: 1.1ms preprocess, 298.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlr9byQqsuRk7xA4i9D2mA_90.JPG: 480x640 (no detections), 292.1ms
Speed: 1.1ms preprocess, 292.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlr9byQqsuRk7xA4i9D2mA_180.JPG: 480x640 (no detections), 294.5ms
Speed: 1.1ms preprocess, 294.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlr9byQqsuRk7xA4i9D2mA_270.JPG: 480x640 (no detections), 293.1ms
Speed: 1.2ms preprocess, 293.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlvTtMgaerD4W32Dd9ZZFg_0.JPG: 480x640 (no detections), 296.7ms
Speed: 1.2ms preprocess, 296.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlvTtMgaerD4W32Dd9ZZFg_90.JPG: 480x640 (no detections), 287.5ms
Speed: 1.2ms preprocess, 287.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlvTtMgaerD4W32Dd9ZZFg_180.JPG: 480x640 (no detections), 289.4ms
Speed: 1.1ms preprocess, 289.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlvTtMgaerD4W32Dd9ZZFg_270.JPG: 480x640 (no detections), 292.5ms
Speed: 1.1ms preprocess, 292.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlwVJOO_asvTaT_zvWCH8g_0.JPG: 480x640 (no detections), 293.2ms
Speed: 1.2ms preprocess, 293.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlwVJOO_asvTaT_zvWCH8g_90.JPG: 480x640 (no detections), 293.1ms
Speed: 1.2ms preprocess, 293.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlwVJOO_asvTaT_zvWCH8g_180.JPG: 480x640 (no detections), 289.5ms
Speed: 1.8ms preprocess, 289.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlwVJOO_asvTaT_zvWCH8g_270.JPG: 480x640 (no detections), 370.9ms
Speed: 1.2ms preprocess, 370.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlyy_51Kg4aODI1ENXr2nw_0.JPG: 480x640 (no detections), 293.4ms
Speed: 1.2ms preprocess, 293.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlyy_51Kg4aODI1ENXr2nw_90.JPG: 480x640 (no detections), 372.9ms
Speed: 1.2ms preprocess, 372.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlyy_51Kg4aODI1ENXr2nw_180.JPG: 480x640 (no detections), 296.0ms
Speed: 1.6ms preprocess, 296.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/L/wlyy_51Kg4aODI1ENXr2nw_270.JPG: 480x640 (no detections), 292.8ms
Speed: 1.3ms preprocess, 292.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wm1RZMvct5mpdykgdpenJQ_0.JPG: 480x640 (no detections), 293.4ms
Speed: 1.3ms preprocess, 293.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wm1RZMvct5mpdykgdpenJQ_90.JPG: 480x640 (no detections), 292.8ms
Speed: 1.1ms preprocess, 292.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wm1RZMvct5mpdykgdpenJQ_180.JPG: 480x640 (no detections), 289.2ms
Speed: 1.5ms preprocess, 289.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wm1RZMvct5mpdykgdpenJQ_270.JPG: 480x640 (no detections), 293.1ms
Speed: 1.1ms preprocess, 293.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wm9g687KnZTR5qsPpfbr0w_0.JPG: 480x640 (no detections), 290.1ms

Speed: 1.1ms preprocess, 290.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wm9g687KnZTR5qsPpfbr0w_90.JPG: 480x640 (no detections), 291.2ms
Speed: 1.0ms preprocess, 291.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wm9g687KnZTR5qsPpfbr0w_180.JPG: 480x640 (no detections), 295.5ms
Speed: 1.1ms preprocess, 295.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wm9g687KnZTR5qsPpfbr0w_270.JPG: 480x640 (no detections), 291.5ms
Speed: 1.1ms preprocess, 291.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmB48n0eZN2_ZYVsfTWaqQ_0.JPG: 480x640 (no detections), 291.4ms
Speed: 1.1ms preprocess, 291.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmB48n0eZN2_ZYVsfTWaqQ_90.JPG: 480x640 (no detections), 288.9ms
Speed: 1.1ms preprocess, 288.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmB48n0eZN2_ZYVsfTWaqQ_180.JPG: 480x640 (no detections), 296.6ms
Speed: 1.3ms preprocess, 296.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmB48n0eZN2_ZYVsfTWaqQ_270.JPG: 480x640 (no detections), 291.4ms
Speed: 1.1ms preprocess, 291.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmDQ5HWP5CDK8bfwbXfm_g_0.JPG: 480x640 (no detections), 291.9ms
Speed: 1.1ms preprocess, 291.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmDQ5HWP5CDK8bfwbXfm_g_90.JPG: 480x640 (no detections), 291.4ms
Speed: 1.2ms preprocess, 291.4ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmDQ5HWP5CDK8bfwbXfm_g_180.JPG: 480x640 (no detections), 290.1ms
Speed: 1.2ms preprocess, 290.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmDQ5HWP5CDK8bfwbXfm_g_270.JPG: 480x640 (no detections), 291.6ms
Speed: 1.2ms preprocess, 291.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmEg3MU5RTyiGuQRTVl97g_0.JPG: 480x640 (no detections), 288.9ms
Speed: 1.0ms preprocess, 288.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmEg3MU5RTyiGuQRTVl97g_90.JPG: 480x640 (no detections), 296.5ms
Speed: 1.2ms preprocess, 296.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmEg3MU5RTyiGuQRTVl97g_180.JPG: 480x640 (no detections), 292.8ms
Speed: 1.2ms preprocess, 292.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmEg3MU5RTyiGuQRTVl97g_270.JPG: 480x640 (no detections), 294.5ms
Speed: 1.1ms preprocess, 294.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmF9YNazR8gf8zQMM9gzow_0.JPG: 480x640 (no detections), 296.0ms
Speed: 1.1ms preprocess, 296.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmF9YNazR8gf8zQMM9gzow_90.JPG: 480x640 (no detections), 294.7ms
Speed: 1.2ms preprocess, 294.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmF9YNazR8gf8zQMM9gzow_180.JPG: 480x640 (no detections), 290.7ms
Speed: 1.2ms preprocess, 290.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmF9YNazR8gf8zQMM9gzow_270.JPG: 480x640 (no detections), 292.0ms
Speed: 1.0ms preprocess, 292.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmMTKdMm28BxT-9-Cf6OBQ_0.JPG: 480x640 (no detections), 298.4ms
Speed: 1.2ms preprocess, 298.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmMTKdMm28BxT-9-Cf6OBQ_90.JPG: 480x640 (no detections), 287.0ms
Speed: 1.2ms preprocess, 287.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmMTKdMm28BxT-9-Cf6OBQ_180.JPG: 480x640 (no detections), 293.2ms
Speed: 1.4ms preprocess, 293.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmMTKdMm28BxT-9-Cf6OBQ_270.JPG: 480x640 (no detections), 295.2ms
Speed: 1.2ms preprocess, 295.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmMsEjEDWvgFT2fmRsTHLQ_0.JPG: 480x640 (no detections), 292.0ms
Speed: 1.1ms preprocess, 292.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmMsEjEDWvgFT2fmRsTHLQ_90.JPG: 480x640 (no detections), 288.7ms
Speed: 1.0ms preprocess, 288.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmMsEjEDWvgFT2fmRsTHLQ_180.JPG: 480x640 (no detections), 294.1ms
Speed: 1.3ms preprocess, 294.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmMsEjEDWvgFT2fmRsTHLQ_270.JPG: 480x640 (no detections), 290.5ms
Speed: 1.2ms preprocess, 290.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmO-XTKIRpnCQEXH49Podw_0.JPG: 480x640 (no detections), 292.4ms
Speed: 1.6ms preprocess, 292.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmO-XTKIRpnCQEXH49Podw_90.JPG: 480x640 (no detections), 298.7ms
Speed: 1.6ms preprocess, 298.7ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmO-XTKIRpnCQEXH49Podw_180.JPG: 480x640 (no detections), 293.0ms
Speed: 1.3ms preprocess, 293.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmO-XTKIRpnCQEXH49Podw_270.JPG: 480x640 (no detections), 289.0ms
Speed: 1.2ms preprocess, 289.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmO6ptO5ixScay-TjQ7X_A_0.JPG: 480x640 (no detections), 293.4ms
Speed: 1.5ms preprocess, 293.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmO6ptO5ixScay-TjQ7X_A_90.JPG: 480x640 (no detections), 299.9ms
Speed: 1.3ms preprocess, 299.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmO6ptO5ixScay-TjQ7X_A_180.JPG: 480x640 (no detections), 293.6ms
Speed: 1.1ms preprocess, 293.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmO6ptO5ixScay-TjQ7X_A_270.JPG: 480x640 (no detections), 307.1ms
Speed: 1.1ms preprocess, 307.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmONsIRO9tVdGoQdxsLKZA_0.JPG: 480x640 (no detections), 305.7ms
Speed: 1.2ms preprocess, 305.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmONsIRO9tVdGoQdxsLKZA_90.JPG: 480x640 (no detections), 302.4ms
Speed: 1.2ms preprocess, 302.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmONsIRO9tVdGoQdxsLKZA_180.JPG: 480x640 (no detections), 317.6ms
Speed: 1.6ms preprocess, 317.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmONsIRO9tVdGoQdxsLKZA_270.JPG: 480x640 (no detections), 333.5ms
Speed: 1.1ms preprocess, 333.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmQS6pQxJB9b7W7Eytctvw_0.JPG: 480x640 2 Wastes, 332.0ms
Speed: 1.7ms preprocess, 332.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmQS6pQxJB9b7W7Eytctvw_90.JPG: 480x640 (no detections), 296.5ms
Speed: 1.1ms preprocess, 296.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmQS6pQxJB9b7W7Eytctvw_180.JPG: 480x640 (no detections), 303.7ms
Speed: 1.4ms preprocess, 303.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmQS6pQxJB9b7W7Eytctvw_270.JPG: 480x640 (no detections), 308.1ms
Speed: 2.2ms preprocess, 308.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmQ_b3DwjXVf_eIwk8X0_w_0.JPG: 480x640 (no detections), 291.5ms
Speed: 1.1ms preprocess, 291.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmQ_b3DwjXVf_eIwk8X0_w_90.JPG: 480x640 (no detections), 312.4ms
Speed: 1.0ms preprocess, 312.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmQ_b3DwjXVf_eIwk8X0_w_180.JPG: 480x640 (no detections), 313.5ms
Speed: 1.5ms preprocess, 313.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmQ_b3DwjXVf_eIwk8X0_w_270.JPG: 480x640 (no detections), 304.2ms
Speed: 1.3ms preprocess, 304.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmRylg55KA2w7-tF0m23tw_0.JPG: 480x640 (no detections), 310.9ms
Speed: 1.2ms preprocess, 310.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmRylg55KA2w7-tF0m23tw_90.JPG: 480x640 (no detections), 296.7ms
Speed: 1.2ms preprocess, 296.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmRylg55KA2w7-tF0m23tw_180.JPG: 480x640 (no detections), 288.8ms
Speed: 1.2ms preprocess, 288.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmRylg55KA2w7-tF0m23tw_270.JPG: 480x640 (no detections), 292.3ms
Speed: 1.3ms preprocess, 292.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmYl8x0xMMYfmvXNNSK2VQ_0.JPG: 480x640 (no detections), 288.9ms
Speed: 1.1ms preprocess, 288.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmYl8x0xMMYfmvXNNSK2VQ_90.JPG: 480x640 (no detections), 292.9ms
Speed: 1.2ms preprocess, 292.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmYl8x0xMMYfmvXNNSK2VQ_180.JPG: 480x640 (no detections), 296.0ms
Speed: 1.4ms preprocess, 296.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmYl8x0xMMYfmvXNNSK2VQ_270.JPG: 480x640 (no detections), 289.0ms
Speed: 1.3ms preprocess, 289.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmZhTPMoUv80d92juwUgFw_0.JPG: 480x640 (no detections), 289.5ms
Speed: 1.7ms preprocess, 289.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmZhTPMoUv80d92juwUgFw_90.JPG: 480x640 (no detections), 291.2ms
Speed: 1.3ms preprocess, 291.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmZhTPMoUv80d92juwUgFw_180.JPG: 480x640 (no detections), 291.6ms
Speed: 1.1ms preprocess, 291.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmZhTPMoUv80d92juwUgFw_270.JPG: 480x640 (no detections), 297.6ms
Speed: 1.6ms preprocess, 297.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wm_jjsK-HElszNPMuPcqqA_0.JPG: 480x640 (no detections), 291.1ms
Speed: 1.2ms preprocess, 291.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wm_jjsK-HElszNPMuPcqqA_90.JPG: 480x640 (no detections), 294.0ms
Speed: 1.1ms preprocess, 294.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wm_jjsK-HElszNPMuPcqqA_180.JPG: 480x640 (no detections), 289.9ms
Speed: 1.3ms preprocess, 289.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wm_jjsK-HElszNPMuPcqqA_270.JPG: 480x640 (no detections), 290.9ms
Speed: 1.0ms preprocess, 290.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wma5sBmitc0WUv84R4wMtA_0.JPG: 480x640 (no detections), 296.1ms
Speed: 1.4ms preprocess, 296.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wma5sBmitc0WUv84R4wMtA_90.JPG: 480x640 (no detections), 290.8ms
Speed: 1.2ms preprocess, 290.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wma5sBmitc0WUv84R4wMtA_180.JPG: 480x640 (no detections), 290.2ms
Speed: 1.4ms preprocess, 290.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wma5sBmitc0WUv84R4wMtA_270.JPG: 480x640 1 Waste, 294.3ms

Speed: 1.2ms preprocess, 294.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmcKSMyjq4mfAX8u_A89FQ_0.JPG: 480x640 (no detections), 294.6ms
Speed: 1.2ms preprocess, 294.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmcKSMyjq4mfAX8u_A89FQ_90.JPG: 480x640 (no detections), 294.1ms
Speed: 1.3ms preprocess, 294.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmcKSMyjq4mfAX8u_A89FQ_180.JPG: 480x640 (no detections), 289.6ms
Speed: 1.2ms preprocess, 289.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmcKSMyjq4mfAX8u_A89FQ_270.JPG: 480x640 (no detections), 294.5ms
Speed: 1.7ms preprocess, 294.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmdybWZ_5aQF14zwIzIXig_0.JPG: 480x640 (no detections), 289.2ms
Speed: 1.1ms preprocess, 289.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmdybWZ_5aQF14zwIzIXig_90.JPG: 480x640 (no detections), 293.0ms
Speed: 1.2ms preprocess, 293.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmdybWZ_5aQF14zwIzIXig_180.JPG: 480x640 (no detections), 295.2ms
Speed: 1.2ms preprocess, 295.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmdybWZ_5aQF14zwIzIXig_270.JPG: 480x640 (no detections), 289.1ms
Speed: 1.7ms preprocess, 289.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmf0quTJYcMXyO4obnZcEw_0.JPG: 480x640 (no detections), 291.2ms
Speed: 1.2ms preprocess, 291.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmf0quTJYcMXyO4obnZcEw_90.JPG: 480x640 (no detections), 290.2ms
Speed: 1.2ms preprocess, 290.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmf0quTJYcMXyO4obnZcEw_180.JPG: 480x640 (no detections), 289.7ms
Speed: 1.4ms preprocess, 289.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmf0quTJYcMXyO4obnZcEw_270.JPG: 480x640 (no detections), 292.5ms
Speed: 1.1ms preprocess, 292.5ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmlLb8WMtttu_8jN07uSaQ_0.JPG: 480x640 (no detections), 294.3ms
Speed: 1.2ms preprocess, 294.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmlLb8WMtttu_8jN07uSaQ_90.JPG: 480x640 (no detections), 290.9ms
Speed: 1.2ms preprocess, 290.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmlLb8WMtttu_8jN07uSaQ_180.JPG: 480x640 (no detections), 288.0ms
Speed: 1.2ms preprocess, 288.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmlLb8WMtttu_8jN07uSaQ_270.JPG: 480x640 (no detections), 293.2ms
Speed: 1.7ms preprocess, 293.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmlX4VcoL0hvKj8guwfaqQ_0.JPG: 480x640 (no detections), 290.7ms
Speed: 1.3ms preprocess, 290.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmlX4VcoL0hvKj8guwfaqQ_90.JPG: 480x640 (no detections), 288.6ms
Speed: 1.2ms preprocess, 288.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmlX4VcoL0hvKj8guwfaqQ_180.JPG: 480x640 (no detections), 287.6ms
Speed: 1.1ms preprocess, 287.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmlX4VcoL0hvKj8guwfaqQ_270.JPG: 480x640 1 Waste, 293.9ms
Speed: 1.6ms preprocess, 293.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmp6AFV6LoR3FSCJXWZ7iQ_0.JPG: 480x640 (no detections), 289.9ms
Speed: 1.1ms preprocess, 289.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmp6AFV6LoR3FSCJXWZ7iQ_90.JPG: 480x640 1 Waste, 297.1ms
Speed: 1.6ms preprocess, 297.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmp6AFV6LoR3FSCJXWZ7iQ_180.JPG: 480x640 (no detections), 291.5ms
Speed: 1.3ms preprocess, 291.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmp6AFV6LoR3FSCJXWZ7iQ_270.JPG: 480x640 (no detections), 291.5ms
Speed: 1.0ms preprocess, 291.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmrgCfyh0TT7RNiISV4pVQ_0.JPG: 480x640 (no detections), 295.3ms
Speed: 1.1ms preprocess, 295.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmrgCfyh0TT7RNiISV4pVQ_90.JPG: 480x640 (no detections), 290.2ms
Speed: 1.3ms preprocess, 290.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmrgCfyh0TT7RNiISV4pVQ_180.JPG: 480x640 (no detections), 293.2ms
Speed: 1.1ms preprocess, 293.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmrgCfyh0TT7RNiISV4pVQ_270.JPG: 480x640 (no detections), 290.2ms
Speed: 1.1ms preprocess, 290.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmvUI_YmnJByopuwLFF2Ig_0.JPG: 480x640 (no detections), 289.1ms
Speed: 1.0ms preprocess, 289.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmvUI_YmnJByopuwLFF2Ig_90.JPG: 480x640 (no detections), 286.7ms
Speed: 1.4ms preprocess, 286.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmvUI_YmnJByopuwLFF2Ig_180.JPG: 480x640 (no detections), 292.1ms
Speed: 1.4ms preprocess, 292.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmvUI_YmnJByopuwLFF2Ig_270.JPG: 480x640 (no detections), 292.8ms
Speed: 1.2ms preprocess, 292.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmvc7fKHTqlNBuND-bCdrw_0.JPG: 480x640 (no detections), 293.5ms
Speed: 1.1ms preprocess, 293.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmvc7fKHTqlNBuND-bCdrw_90.JPG: 480x640 (no detections), 291.5ms
Speed: 1.0ms preprocess, 291.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmvc7fKHTqlNBuND-bCdrw_180.JPG: 480x640 (no detections), 295.4ms
Speed: 1.4ms preprocess, 295.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/m/wmvc7fKHTqlNBuND-bCdrw_270.JPG: 480x640 (no detections), 292.0ms
Speed: 1.1ms preprocess, 292.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wn5TbLepA5BC0KaPLQ9mYw_0.JPG: 480x640 (no detections), 293.8ms
Speed: 1.1ms preprocess, 293.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wn5TbLepA5BC0KaPLQ9mYw_90.JPG: 480x640 (no detections), 294.9ms
Speed: 1.0ms preprocess, 294.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wn5TbLepA5BC0KaPLQ9mYw_180.JPG: 480x640 (no detections), 292.9ms
Speed: 1.2ms preprocess, 292.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wn5TbLepA5BC0KaPLQ9mYw_270.JPG: 480x640 1 Waste, 294.9ms
Speed: 1.2ms preprocess, 294.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wn6x43KX4cpvr9gK_liArg_0.JPG: 480x640 (no detections), 301.1ms
Speed: 1.2ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wn6x43KX4cpvr9gK_liArg_90.JPG: 480x640 (no detections), 289.7ms
Speed: 1.3ms preprocess, 289.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wn6x43KX4cpvr9gK_liArg_180.JPG: 480x640 (no detections), 290.7ms
Speed: 1.9ms preprocess, 290.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wn6x43KX4cpvr9gK_liArg_270.JPG: 480x640 (no detections), 292.8ms
Speed: 1.2ms preprocess, 292.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnB2yZC7qNzwODCmXDxDMg_0.JPG: 480x640 (no detections), 295.3ms
Speed: 1.4ms preprocess, 295.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnB2yZC7qNzwODCmXDxDMg_90.JPG: 480x640 (no detections), 292.1ms
Speed: 1.1ms preprocess, 292.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnB2yZC7qNzwODCmXDxDMg_180.JPG: 480x640 (no detections), 296.8ms
Speed: 1.2ms preprocess, 296.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnB2yZC7qNzwODCmXDxDMg_270.JPG: 480x640 (no detections), 293.6ms
Speed: 1.3ms preprocess, 293.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnBA9MjJrko2SGVLg8bk9w_0.JPG: 480x640 (no detections), 288.5ms
Speed: 1.2ms preprocess, 288.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnBA9MjJrko2SGVLg8bk9w_90.JPG: 480x640 (no detections), 294.4ms
Speed: 1.2ms preprocess, 294.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnBA9MjJrko2SGVLg8bk9w_180.JPG: 480x640 (no detections), 293.4ms
Speed: 1.2ms preprocess, 293.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnBA9MjJrko2SGVLg8bk9w_270.JPG: 480x640 (no detections), 292.6ms
Speed: 1.1ms preprocess, 292.6ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnCtBu4Gp-tp17Awv6oh7A_0.JPG: 480x640 (no detections), 296.1ms
Speed: 1.1ms preprocess, 296.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnCtBu4Gp-tp17Awv6oh7A_90.JPG: 480x640 (no detections), 289.6ms
Speed: 1.1ms preprocess, 289.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnCtBu4Gp-tp17Awv6oh7A_180.JPG: 480x640 (no detections), 290.1ms
Speed: 1.1ms preprocess, 290.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnCtBu4Gp-tp17Awv6oh7A_270.JPG: 480x640 (no detections), 286.9ms
Speed: 1.2ms preprocess, 286.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnIZcuecZSnkpqRwrVGuOA_0.JPG: 480x640 (no detections), 291.8ms
Speed: 1.3ms preprocess, 291.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnIZcuecZSnkpqRwrVGuOA_90.JPG: 480x640 (no detections), 295.6ms
Speed: 1.4ms preprocess, 295.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnIZcuecZSnkpqRwrVGuOA_180.JPG: 480x640 (no detections), 293.7ms
Speed: 1.1ms preprocess, 293.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnIZcuecZSnkpqRwrVGuOA_270.JPG: 480x640 (no detections), 293.1ms
Speed: 1.2ms preprocess, 293.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnM3wHFXtrM5vNBYfbPpkA_0.JPG: 480x640 (no detections), 290.2ms
Speed: 1.1ms preprocess, 290.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnM3wHFXtrM5vNBYfbPpkA_90.JPG: 480x640 (no detections), 289.8ms
Speed: 1.3ms preprocess, 289.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnM3wHFXtrM5vNBYfbPpkA_180.JPG: 480x640 (no detections), 293.1ms
Speed: 1.0ms preprocess, 293.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnM3wHFXtrM5vNBYfbPpkA_270.JPG: 480x640 (no detections), 291.6ms
Speed: 1.1ms preprocess, 291.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnMOAlmoqffKJx9pIM-xxQ_0.JPG: 480x640 (no detections), 296.5ms
Speed: 1.2ms preprocess, 296.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnMOAlmoqffKJx9pIM-xxQ_90.JPG: 480x640 (no detections), 291.5ms
Speed: 1.2ms preprocess, 291.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnMOAlmoqffKJx9pIM-xxQ_180.JPG: 480x640 (no detections), 290.7ms

Speed: 1.2ms preprocess, 290.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnMOAlmoqffKJx9pIM-xxQ_270.JPG: 480x640 (no detections), 290.4ms
Speed: 1.2ms preprocess, 290.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnMljpBhiLo5aulNbMPB9A_0.JPG: 480x640 1 Waste, 294.1ms
Speed: 1.3ms preprocess, 294.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnMljpBhiLo5aulNbMPB9A_90.JPG: 480x640 (no detections), 288.6ms
Speed: 1.2ms preprocess, 288.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnMljpBhiLo5aulNbMPB9A_180.JPG: 480x640 (no detections), 296.5ms
Speed: 1.2ms preprocess, 296.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnMljpBhiLo5aulNbMPB9A_270.JPG: 480x640 (no detections), 294.2ms
Speed: 1.3ms preprocess, 294.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnPiRfeULC7BAY66IF1fsg_0.JPG: 480x640 (no detections), 287.1ms
Speed: 1.4ms preprocess, 287.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnPiRfeULC7BAY66IF1fsg_90.JPG: 480x640 (no detections), 296.4ms
Speed: 1.1ms preprocess, 296.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnPiRfeULC7BAY66IF1fsg_180.JPG: 480x640 (no detections), 289.6ms
Speed: 1.1ms preprocess, 289.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnPiRfeULC7BAY66IF1fsg_270.JPG: 480x640 (no detections), 294.5ms
Speed: 1.3ms preprocess, 294.5ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnQUIt4gDgb_Hkp3dHl0Mw_0.JPG: 480x640 (no detections), 289.0ms
Speed: 1.2ms preprocess, 289.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnQUIt4gDgb_Hkp3dHl0Mw_90.JPG: 480x640 (no detections), 294.2ms
Speed: 1.2ms preprocess, 294.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnQUIt4gDgb_Hkp3dHl0Mw_180.JPG: 480x640 (no detections), 294.1ms
Speed: 1.1ms preprocess, 294.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnQUIt4gDgb_Hkp3dHl0Mw_270.JPG: 480x640 (no detections), 289.9ms
Speed: 1.1ms preprocess, 289.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnRYtuxk2GhtBWJhDgdB9g_0.JPG: 480x640 (no detections), 289.0ms
Speed: 1.2ms preprocess, 289.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnRYtuxk2GhtBWJhDgdB9g_90.JPG: 480x640 (no detections), 291.4ms
Speed: 1.3ms preprocess, 291.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnRYtuxk2GhtBWJhDgdB9g_180.JPG: 480x640 (no detections), 298.9ms
Speed: 1.2ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnRYtuxk2GhtBWJhDgdB9g_270.JPG: 480x640 (no detections), 292.7ms
Speed: 1.1ms preprocess, 292.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnSPit5u4IED1NcV9Ovfzg_0.JPG: 480x640 (no detections), 293.9ms
Speed: 1.2ms preprocess, 293.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnSPit5u4IED1NcV9Ovfzg_90.JPG: 480x640 (no detections), 292.2ms
Speed: 1.1ms preprocess, 292.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnSPit5u4IED1NcV9Ovfzg_180.JPG: 480x640 (no detections), 297.2ms
Speed: 1.2ms preprocess, 297.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnSPit5u4IED1NcV9Ovfzg_270.JPG: 480x640 (no detections), 290.2ms
Speed: 1.2ms preprocess, 290.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnSe4t9Vy78yofI_tWxZUQ_0.JPG: 480x640 1 Waste, 293.2ms
Speed: 1.2ms preprocess, 293.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnSe4t9Vy78yofI_tWxZUQ_90.JPG: 480x640 (no detections), 292.6ms
Speed: 1.1ms preprocess, 292.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnSe4t9Vy78yofI_tWxZUQ_180.JPG: 480x640 (no detections), 300.2ms
Speed: 1.0ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnSe4t9Vy78yofI_tWxZUQ_270.JPG: 480x640 (no detections), 294.2ms
Speed: 1.1ms preprocess, 294.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnTThwMs22RJW_5_qgEVFA_0.JPG: 480x640 (no detections), 291.0ms
Speed: 1.2ms preprocess, 291.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnTThwMs22RJW_5_qgEVFA_90.JPG: 480x640 (no detections), 293.0ms
Speed: 1.3ms preprocess, 293.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnTThwMs22RJW_5_qgEVFA_180.JPG: 480x640 (no detections), 290.7ms
Speed: 1.2ms preprocess, 290.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnTThwMs22RJW_5_qgEVFA_270.JPG: 480x640 (no detections), 296.2ms
Speed: 1.6ms preprocess, 296.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnUeoZ-WvNTBz06PfaAY0A_0.JPG: 480x640 (no detections), 293.1ms
Speed: 1.2ms preprocess, 293.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnUeoZ-WvNTBz06PfaAY0A_90.JPG: 480x640 (no detections), 292.3ms
Speed: 1.5ms preprocess, 292.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnUeoZ-WvNTBz06PfaAY0A_180.JPG: 480x640 (no detections), 286.2ms
Speed: 1.2ms preprocess, 286.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnUeoZ-WvNTBz06PfaAY0A_270.JPG: 480x640 (no detections), 292.7ms
Speed: 1.1ms preprocess, 292.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnWw_zr3wKUSWeIb9c1prw_0.JPG: 480x640 (no detections), 299.9ms
Speed: 1.0ms preprocess, 299.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnWw_zr3wKUSWeIb9c1prw_90.JPG: 480x640 (no detections), 292.0ms
Speed: 1.3ms preprocess, 292.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnWw_zr3wKUSWeIb9c1prw_180.JPG: 480x640 (no detections), 289.3ms
Speed: 1.3ms preprocess, 289.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnWw_zr3wKUSWeIb9c1prw_270.JPG: 480x640 (no detections), 290.1ms
Speed: 1.1ms preprocess, 290.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wn_0DjVG6Bua_ovoSLKwVQ_0.JPG: 480x640 (no detections), 288.4ms
Speed: 1.7ms preprocess, 288.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wn_0DjVG6Bua_ovoSLKwVQ_90.JPG: 480x640 (no detections), 292.9ms
Speed: 1.1ms preprocess, 292.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wn_0DjVG6Bua_ovoSLKwVQ_180.JPG: 480x640 (no detections), 295.4ms
Speed: 1.2ms preprocess, 295.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wn_0DjVG6Bua_ovoSLKwVQ_270.JPG: 480x640 (no detections), 296.0ms
Speed: 1.4ms preprocess, 296.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wneoqtKPgiHfpSq8Te2DWg_0.JPG: 480x640 (no detections), 292.6ms
Speed: 1.0ms preprocess, 292.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wneoqtKPgiHfpSq8Te2DWg_90.JPG: 480x640 (no detections), 295.2ms
Speed: 1.3ms preprocess, 295.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wneoqtKPgiHfpSq8Te2DWg_180.JPG: 480x640 (no detections), 290.8ms
Speed: 1.1ms preprocess, 290.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wneoqtKPgiHfpSq8Te2DWg_270.JPG: 480x640 (no detections), 295.8ms
Speed: 1.5ms preprocess, 295.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnf9lGL0TinCkLZplCBCbA_0.JPG: 480x640 (no detections), 289.7ms
Speed: 1.3ms preprocess, 289.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnf9lGL0TinCkLZplCBCbA_90.JPG: 480x640 (no detections), 300.0ms
Speed: 1.1ms preprocess, 300.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnf9lGL0TinCkLZplCBCbA_180.JPG: 480x640 (no detections), 292.1ms
Speed: 1.8ms preprocess, 292.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnf9lGL0TinCkLZplCBCbA_270.JPG: 480x640 (no detections), 292.1ms
Speed: 1.3ms preprocess, 292.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wng_Hw_vbkwynDy5aXyCmA_0.JPG: 480x640 (no detections), 297.0ms
Speed: 1.0ms preprocess, 297.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wng_Hw_vbkwynDy5aXyCmA_90.JPG: 480x640 (no detections), 291.0ms
Speed: 1.5ms preprocess, 291.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wng_Hw_vbkwynDy5aXyCmA_180.JPG: 480x640 (no detections), 293.5ms
Speed: 1.3ms preprocess, 293.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wng_Hw_vbkwynDy5aXyCmA_270.JPG: 480x640 (no detections), 294.2ms
Speed: 1.1ms preprocess, 294.2ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wngyig0K2pL2yzerYwDPTw_0.JPG: 480x640 (no detections), 289.6ms
Speed: 1.2ms preprocess, 289.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wngyig0K2pL2yzerYwDPTw_90.JPG: 480x640 1 Waste, 289.0ms
Speed: 1.2ms preprocess, 289.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wngyig0K2pL2yzerYwDPTw_180.JPG: 480x640 (no detections), 292.3ms
Speed: 1.2ms preprocess, 292.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wngyig0K2pL2yzerYwDPTw_270.JPG: 480x640 (no detections), 292.3ms
Speed: 1.1ms preprocess, 292.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnhfqLYqEkFlUSyKbBJLOA_0.JPG: 480x640 (no detections), 295.6ms
Speed: 1.2ms preprocess, 295.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnhfqLYqEkFlUSyKbBJLOA_90.JPG: 480x640 (no detections), 291.4ms
Speed: 1.2ms preprocess, 291.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnhfqLYqEkFlUSyKbBJLOA_180.JPG: 480x640 (no detections), 288.4ms
Speed: 1.1ms preprocess, 288.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnhfqLYqEkFlUSyKbBJLOA_270.JPG: 480x640 (no detections), 289.7ms
Speed: 1.2ms preprocess, 289.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnjO3_gqdU9yNsRn2nd1bQ_0.JPG: 480x640 (no detections), 288.0ms
Speed: 1.0ms preprocess, 288.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnjO3_gqdU9yNsRn2nd1bQ_90.JPG: 480x640 (no detections), 290.0ms
Speed: 1.2ms preprocess, 290.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnjO3_gqdU9yNsRn2nd1bQ_180.JPG: 480x640 (no detections), 293.6ms
Speed: 1.2ms preprocess, 293.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnjO3_gqdU9yNsRn2nd1bQ_270.JPG: 480x640 (no detections), 287.1ms
Speed: 1.2ms preprocess, 287.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnkJ0tEj7G4FAbaaNsE3Pg_0.JPG: 480x640 (no detections), 289.5ms
Speed: 1.4ms preprocess, 289.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnkJ0tEj7G4FAbaaNsE3Pg_90.JPG: 480x640 (no detections), 291.5ms

Speed: 1.4ms preprocess, 291.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnkJ0tEj7G4FAbaaNsE3Pg_180.JPG: 480x640 1 Waste, 293.1ms
Speed: 1.2ms preprocess, 293.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnkJ0tEj7G4FAbaaNsE3Pg_270.JPG: 480x640 (no detections), 294.0ms
Speed: 1.9ms preprocess, 294.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnlQPQN7rzfYrcCOuVOChw_0.JPG: 480x640 (no detections), 296.6ms
Speed: 1.2ms preprocess, 296.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnlQPQN7rzfYrcCOuVOChw_90.JPG: 480x640 (no detections), 292.5ms
Speed: 1.5ms preprocess, 292.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnlQPQN7rzfYrcCOuVOChw_180.JPG: 480x640 (no detections), 294.8ms
Speed: 1.2ms preprocess, 294.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnlQPQN7rzfYrcCOuVOChw_270.JPG: 480x640 (no detections), 291.1ms
Speed: 1.5ms preprocess, 291.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnlRWGSQlFUMlIhj17oKNQ_0.JPG: 480x640 (no detections), 291.7ms
Speed: 1.1ms preprocess, 291.7ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnlRWGSQlFUMlIhj17oKNQ_90.JPG: 480x640 (no detections), 291.0ms
Speed: 1.1ms preprocess, 291.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnlRWGSQlFUMlIhj17oKNQ_180.JPG: 480x640 (no detections), 294.8ms
Speed: 1.3ms preprocess, 294.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnlRWGSQlFUMlIhj17oKNQ_270.JPG: 480x640 (no detections), 291.0ms
Speed: 1.2ms preprocess, 291.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnleyl8tkmecZ_dMPxWZbA_0.JPG: 480x640 (no detections), 294.6ms
Speed: 1.2ms preprocess, 294.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnleyl8tkmecZ_dMPxWZbA_90.JPG: 480x640 (no detections), 285.7ms
Speed: 1.1ms preprocess, 285.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnleyl8tkmecZ_dMPxWZbA_180.JPG: 480x640 (no detections), 296.5ms
Speed: 1.2ms preprocess, 296.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnleyl8tkmecZ_dMPxWZbA_270.JPG: 480x640 (no detections), 289.1ms
Speed: 1.7ms preprocess, 289.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnmZFEockvDApA3utZXk9w_0.JPG: 480x640 (no detections), 293.1ms
Speed: 1.4ms preprocess, 293.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnmZFEockvDApA3utZXk9w_90.JPG: 480x640 (no detections), 295.4ms
Speed: 1.0ms preprocess, 295.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnmZFEockvDApA3utZXk9w_180.JPG: 480x640 (no detections), 290.8ms
Speed: 1.1ms preprocess, 290.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnmZFEockvDApA3utZXk9w_270.JPG: 480x640 (no detections), 290.8ms
Speed: 1.2ms preprocess, 290.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnopDinRXXcEX3NrRYrZjA_0.JPG: 480x640 (no detections), 293.8ms
Speed: 1.1ms preprocess, 293.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnopDinRXXcEX3NrRYrZjA_90.JPG: 480x640 (no detections), 297.9ms
Speed: 1.0ms preprocess, 297.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnopDinRXXcEX3NrRYrZjA_180.JPG: 480x640 (no detections), 296.7ms
Speed: 1.1ms preprocess, 296.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnopDinRXXcEX3NrRYrZjA_270.JPG: 480x640 (no detections), 295.8ms
Speed: 1.1ms preprocess, 295.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wntODi5bAyGXJqpIPy4z2w_0.JPG: 480x640 (no detections), 292.9ms
Speed: 1.3ms preprocess, 292.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wntODi5bAyGXJqpIPy4z2w_90.JPG: 480x640 (no detections), 292.3ms
Speed: 1.2ms preprocess, 292.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wntODi5bAyGXJqpIPy4z2w_180.JPG: 480x640 (no detections), 286.0ms
Speed: 1.2ms preprocess, 286.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wntODi5bAyGXJqpIPy4z2w_270.JPG: 480x640 (no detections), 290.2ms
Speed: 1.8ms preprocess, 290.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnvLaOr9UJskCQgk9C2e3g_0.JPG: 480x640 (no detections), 296.8ms
Speed: 1.1ms preprocess, 296.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnvLaOr9UJskCQgk9C2e3g_90.JPG: 480x640 (no detections), 289.1ms
Speed: 1.2ms preprocess, 289.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnvLaOr9UJskCQgk9C2e3g_180.JPG: 480x640 (no detections), 289.9ms
Speed: 1.2ms preprocess, 289.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnvLaOr9UJskCQgk9C2e3g_270.JPG: 480x640 (no detections), 291.6ms
Speed: 1.3ms preprocess, 291.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnvl-bBhXCoAwmImUOB1yg_0.JPG: 480x640 (no detections), 291.8ms
Speed: 1.1ms preprocess, 291.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnvl-bBhXCoAwmImUOB1yg_90.JPG: 480x640 (no detections), 294.2ms
Speed: 1.2ms preprocess, 294.2ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnvl-bBhXCoAwmImUOB1yg_180.JPG: 480x640 (no detections), 290.9ms
Speed: 1.2ms preprocess, 290.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnvl-bBhXCoAwmImUOB1yg_270.JPG: 480x640 (no detections), 294.5ms
Speed: 1.1ms preprocess, 294.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnwk26BolVFkhuLYp2KJjw_0.JPG: 480x640 (no detections), 293.0ms
Speed: 1.1ms preprocess, 293.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnwk26BolVFkhuLYp2KJjw_90.JPG: 480x640 (no detections), 293.6ms
Speed: 2.2ms preprocess, 293.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnwk26BolVFkhuLYp2KJjw_180.JPG: 480x640 (no detections), 291.4ms
Speed: 1.2ms preprocess, 291.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnwk26BolVFkhuLYp2KJjw_270.JPG: 480x640 (no detections), 290.1ms
Speed: 1.0ms preprocess, 290.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnyjxyszpM90e3DqxnzQtw_0.JPG: 480x640 (no detections), 293.0ms
Speed: 1.1ms preprocess, 293.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnyjxyszpM90e3DqxnzQtw_90.JPG: 480x640 (no detections), 289.2ms
Speed: 1.3ms preprocess, 289.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnyjxyszpM90e3DqxnzQtw_180.JPG: 480x640 (no detections), 298.8ms
Speed: 1.3ms preprocess, 298.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/N/wnyjxyszpM90e3DqxnzQtw_270.JPG: 480x640 (no detections), 289.4ms
Speed: 1.5ms preprocess, 289.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wo-i0Kojg3gC8rEztlk5cA_0.JPG: 480x640 (no detections), 290.1ms
Speed: 1.2ms preprocess, 290.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wo-i0Kojg3gC8rEztlk5cA_90.JPG: 480x640 (no detections), 295.9ms
Speed: 1.2ms preprocess, 295.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wo-i0Kojg3gC8rEztlk5cA_180.JPG: 480x640 (no detections), 292.7ms
Speed: 1.2ms preprocess, 292.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wo-i0Kojg3gC8rEztlk5cA_270.JPG: 480x640 (no detections), 294.0ms
Speed: 1.4ms preprocess, 294.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wo4spV-QXuZ3B6vmEE-6Kg_0.JPG: 480x640 (no detections), 292.4ms
Speed: 1.1ms preprocess, 292.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wo4spV-QXuZ3B6vmEE-6Kg_90.JPG: 480x640 (no detections), 292.8ms
Speed: 1.1ms preprocess, 292.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wo4spV-QXuZ3B6vmEE-6Kg_180.JPG: 480x640 (no detections), 287.7ms
Speed: 1.2ms preprocess, 287.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wo4spV-QXuZ3B6vmEE-6Kg_270.JPG: 480x640 (no detections), 289.5ms
Speed: 1.0ms preprocess, 289.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wo87jIhVcdmH7zhzDwdOZg_0.JPG: 480x640 (no detections), 286.3ms
Speed: 1.1ms preprocess, 286.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wo87jIhVcdmH7zhzDwdOZg_90.JPG: 480x640 (no detections), 293.4ms
Speed: 1.2ms preprocess, 293.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wo87jIhVcdmH7zhzDwdOZg_180.JPG: 480x640 (no detections), 289.7ms
Speed: 1.2ms preprocess, 289.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wo87jIhVcdmH7zhzDwdOZg_270.JPG: 480x640 (no detections), 295.0ms
Speed: 1.1ms preprocess, 295.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wo8di4AaFEJ52HDg5h283g_0.JPG: 480x640 (no detections), 291.9ms
Speed: 1.2ms preprocess, 291.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wo8di4AaFEJ52HDg5h283g_90.JPG: 480x640 (no detections), 290.2ms
Speed: 1.1ms preprocess, 290.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wo8di4AaFEJ52HDg5h283g_180.JPG: 480x640 (no detections), 290.1ms
Speed: 1.1ms preprocess, 290.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wo8di4AaFEJ52HDg5h283g_270.JPG: 480x640 (no detections), 289.3ms
Speed: 1.1ms preprocess, 289.3ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wo9Z8l0bA4WG6CFg_x72Tg_0.JPG: 480x640 1 Waste, 293.1ms
Speed: 1.2ms preprocess, 293.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wo9Z8l0bA4WG6CFg_x72Tg_90.JPG: 480x640 (no detections), 289.2ms
Speed: 1.0ms preprocess, 289.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wo9Z8l0bA4WG6CFg_x72Tg_180.JPG: 480x640 (no detections), 301.5ms
Speed: 1.1ms preprocess, 301.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wo9Z8l0bA4WG6CFg_x72Tg_270.JPG: 480x640 (no detections), 291.8ms
Speed: 1.5ms preprocess, 291.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woAbgaX1Lo2jzlGT_inu4A_0.JPG: 480x640 (no detections), 296.5ms
Speed: 1.6ms preprocess, 296.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woAbgaX1Lo2jzlGT_inu4A_90.JPG: 480x640 (no detections), 294.8ms
Speed: 1.3ms preprocess, 294.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woAbgaX1Lo2jzlGT_inu4A_180.JPG: 480x640 (no detections), 293.8ms
Speed: 1.2ms preprocess, 293.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woAbgaX1Lo2jzlGT_inu4A_270.JPG: 480x640 (no detections), 297.4ms
Speed: 1.5ms preprocess, 297.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woB7dkTd25Bj_mlWTaTKnw_0.JPG: 480x640 (no detections), 293.1ms

Speed: 1.1ms preprocess, 293.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woB7dkTd25Bj_mlWTaTKnw_90.JPG: 480x640 (no detections), 293.6ms
Speed: 1.3ms preprocess, 293.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woB7dkTd25Bj_mlWTaTKnw_180.JPG: 480x640 (no detections), 291.1ms
Speed: 1.8ms preprocess, 291.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woB7dkTd25Bj_mlWTaTKnw_270.JPG: 480x640 (no detections), 290.2ms
Speed: 1.4ms preprocess, 290.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woCsbapsS8vCGHySUhZYhQ_0.JPG: 480x640 1 Waste, 288.6ms
Speed: 1.2ms preprocess, 288.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woCsbapsS8vCGHySUhZYhQ_90.JPG: 480x640 (no detections), 295.7ms
Speed: 1.6ms preprocess, 295.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woCsbapsS8vCGHySUhZYhQ_180.JPG: 480x640 (no detections), 293.5ms
Speed: 1.2ms preprocess, 293.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woCsbapsS8vCGHySUhZYhQ_270.JPG: 480x640 (no detections), 292.5ms
Speed: 1.2ms preprocess, 292.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woFW7jibF-H21WCiVBgV8w_0.JPG: 480x640 (no detections), 299.9ms
Speed: 1.6ms preprocess, 299.9ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woFW7jibF-H21WCiVBgV8w_90.JPG: 480x640 (no detections), 290.3ms
Speed: 1.1ms preprocess, 290.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woFW7jibF-H21WCiVBgV8w_180.JPG: 480x640 (no detections), 295.4ms
Speed: 1.3ms preprocess, 295.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woFW7jibF-H21WCiVBgV8w_270.JPG: 480x640 (no detections), 287.8ms
Speed: 1.3ms preprocess, 287.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woGC1tCtDRWG_mOkfyEqcg_0.JPG: 480x640 (no detections), 290.6ms
Speed: 1.2ms preprocess, 290.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woGC1tCtDRWG_mOkfyEqcg_90.JPG: 480x640 (no detections), 292.0ms
Speed: 1.2ms preprocess, 292.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woGC1tCtDRWG_mOkfyEqcg_180.JPG: 480x640 (no detections), 294.9ms
Speed: 1.4ms preprocess, 294.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woGC1tCtDRWG_mOkfyEqcg_270.JPG: 480x640 1 Waste, 296.5ms
Speed: 1.1ms preprocess, 296.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woJl-vfeenDAayIO8OUfRQ_0.JPG: 480x640 (no detections), 293.1ms
Speed: 1.2ms preprocess, 293.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woJl-vfeenDAayIO8OUfRQ_90.JPG: 480x640 (no detections), 292.1ms
Speed: 1.3ms preprocess, 292.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woJl-vfeenDAayIO8OUfRQ_180.JPG: 480x640 (no detections), 295.3ms
Speed: 1.2ms preprocess, 295.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woJl-vfeenDAayIO8OUfRQ_270.JPG: 480x640 (no detections), 294.3ms
Speed: 1.2ms preprocess, 294.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woK_c92O_Bxl9V791NGzLA_0.JPG: 480x640 (no detections), 290.7ms
Speed: 1.1ms preprocess, 290.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woK_c92O_Bxl9V791NGzLA_90.JPG: 480x640 (no detections), 297.8ms
Speed: 1.1ms preprocess, 297.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woK_c92O_Bxl9V791NGzLA_180.JPG: 480x640 (no detections), 292.7ms
Speed: 1.3ms preprocess, 292.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woK_c92O_Bxl9V791NGzLA_270.JPG: 480x640 (no detections), 292.0ms
Speed: 1.3ms preprocess, 292.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woLsbxJRVqbqBrXeoXKnGA_0.JPG: 480x640 (no detections), 294.0ms
Speed: 1.1ms preprocess, 294.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woLsbxJRVqbqBrXeoXKnGA_90.JPG: 480x640 (no detections), 292.4ms
Speed: 1.5ms preprocess, 292.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woLsbxJRVqbqBrXeoXKnGA_180.JPG: 480x640 (no detections), 293.2ms
Speed: 1.3ms preprocess, 293.2ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woLsbxJRVqbqBrXeoXKnGA_270.JPG: 480x640 (no detections), 296.9ms
Speed: 1.3ms preprocess, 296.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woM-qdUAsPK2RSgRpdrZKw_0.JPG: 480x640 (no detections), 292.1ms
Speed: 1.2ms preprocess, 292.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woM-qdUAsPK2RSgRpdrZKw_90.JPG: 480x640 (no detections), 291.7ms
Speed: 1.6ms preprocess, 291.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woM-qdUAsPK2RSgRpdrZKw_180.JPG: 480x640 (no detections), 293.4ms
Speed: 1.3ms preprocess, 293.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woM-qdUAsPK2RSgRpdrZKw_270.JPG: 480x640 (no detections), 292.4ms
Speed: 1.5ms preprocess, 292.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woMKIpX-grs_3Bx82_piGA_0.JPG: 480x640 (no detections), 297.1ms
Speed: 1.0ms preprocess, 297.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woMKIpX-grs_3Bx82_piGA_90.JPG: 480x640 (no detections), 290.8ms
Speed: 1.2ms preprocess, 290.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woMKIpX-grs_3Bx82_piGA_180.JPG: 480x640 (no detections), 296.3ms
Speed: 1.3ms preprocess, 296.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woMKIpX-grs_3Bx82_piGA_270.JPG: 480x640 (no detections), 301.4ms
Speed: 1.2ms preprocess, 301.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woNg6TgkCBdyeh2bz2m2pg_0.JPG: 480x640 (no detections), 293.6ms
Speed: 1.3ms preprocess, 293.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woNg6TgkCBdyeh2bz2m2pg_90.JPG: 480x640 (no detections), 296.8ms
Speed: 1.3ms preprocess, 296.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woNg6TgkCBdyeh2bz2m2pg_180.JPG: 480x640 (no detections), 294.3ms
Speed: 1.0ms preprocess, 294.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woNg6TgkCBdyeh2bz2m2pg_270.JPG: 480x640 (no detections), 288.3ms
Speed: 1.0ms preprocess, 288.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woUXUgWVKMe5mH_LtBpKQA_0.JPG: 480x640 (no detections), 291.7ms
Speed: 1.1ms preprocess, 291.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woUXUgWVKMe5mH_LtBpKQA_90.JPG: 480x640 (no detections), 292.9ms
Speed: 1.1ms preprocess, 292.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woUXUgWVKMe5mH_LtBpKQA_180.JPG: 480x640 (no detections), 290.3ms
Speed: 1.1ms preprocess, 290.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woUXUgWVKMe5mH_LtBpKQA_270.JPG: 480x640 (no detections), 289.9ms
Speed: 1.1ms preprocess, 289.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woV5puR0VFDtliKoBYmVlQ_0.JPG: 480x640 (no detections), 300.2ms
Speed: 1.4ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woV5puR0VFDtliKoBYmVlQ_90.JPG: 480x640 1 Waste, 290.7ms
Speed: 1.1ms preprocess, 290.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woV5puR0VFDtliKoBYmVlQ_180.JPG: 480x640 (no detections), 296.3ms
Speed: 1.3ms preprocess, 296.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woV5puR0VFDtliKoBYmVlQ_270.JPG: 480x640 (no detections), 304.6ms
Speed: 1.2ms preprocess, 304.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woYB8xMYoBoD7V0lTSrKHw_0.JPG: 480x640 (no detections), 382.3ms
Speed: 1.1ms preprocess, 382.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woYB8xMYoBoD7V0lTSrKHw_90.JPG: 480x640 (no detections), 303.0ms
Speed: 1.3ms preprocess, 303.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woYB8xMYoBoD7V0lTSrKHw_180.JPG: 480x640 (no detections), 295.7ms
Speed: 1.3ms preprocess, 295.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woYB8xMYoBoD7V0lTSrKHw_270.JPG: 480x640 (no detections), 290.9ms
Speed: 1.4ms preprocess, 290.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wo_IU9BWO3wuBFsPUM2GxQ_0.JPG: 480x640 (no detections), 296.0ms
Speed: 1.3ms preprocess, 296.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wo_IU9BWO3wuBFsPUM2GxQ_90.JPG: 480x640 (no detections), 290.2ms
Speed: 1.1ms preprocess, 290.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wo_IU9BWO3wuBFsPUM2GxQ_180.JPG: 480x640 (no detections), 291.7ms
Speed: 1.6ms preprocess, 291.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wo_IU9BWO3wuBFsPUM2GxQ_270.JPG: 480x640 (no detections), 292.6ms
Speed: 1.3ms preprocess, 292.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wo_XeL-vyFQ05p3ckr5h-g_0.JPG: 480x640 (no detections), 291.7ms
Speed: 1.2ms preprocess, 291.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wo_XeL-vyFQ05p3ckr5h-g_90.JPG: 480x640 (no detections), 291.7ms
Speed: 1.1ms preprocess, 291.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wo_XeL-vyFQ05p3ckr5h-g_180.JPG: 480x640 (no detections), 296.5ms
Speed: 1.2ms preprocess, 296.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wo_XeL-vyFQ05p3ckr5h-g_270.JPG: 480x640 (no detections), 293.6ms
Speed: 1.1ms preprocess, 293.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wo_mzx_kWoKEMnfm6YzUDQ_0.JPG: 480x640 (no detections), 298.6ms
Speed: 1.3ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wo_mzx_kWoKEMnfm6YzUDQ_90.JPG: 480x640 (no detections), 295.8ms
Speed: 1.0ms preprocess, 295.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wo_mzx_kWoKEMnfm6YzUDQ_180.JPG: 480x640 (no detections), 294.2ms
Speed: 1.2ms preprocess, 294.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wo_mzx_kWoKEMnfm6YzUDQ_270.JPG: 480x640 (no detections), 292.5ms
Speed: 1.2ms preprocess, 292.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wohPnAnRbX3NaTBE6BVcRA_0.JPG: 480x640 (no detections), 295.0ms
Speed: 1.2ms preprocess, 295.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wohPnAnRbX3NaTBE6BVcRA_90.JPG: 480x640 (no detections), 290.9ms
Speed: 1.1ms preprocess, 290.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wohPnAnRbX3NaTBE6BVcRA_180.JPG: 480x640 (no detections), 286.8ms
Speed: 1.1ms preprocess, 286.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wohPnAnRbX3NaTBE6BVcRA_270.JPG: 480x640 (no detections), 291.3ms

Speed: 1.1ms preprocess, 291.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wop2uD6g-STw8-6LUFIrRQ_0.JPG: 480x640 1 Waste, 290.8ms
Speed: 1.1ms preprocess, 290.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wop2uD6g-STw8-6LUFIrRQ_90.JPG: 480x640 (no detections), 298.6ms
Speed: 1.2ms preprocess, 298.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wop2uD6g-STw8-6LUFIrRQ_180.JPG: 480x640 (no detections), 290.8ms
Speed: 1.3ms preprocess, 290.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wop2uD6g-STw8-6LUFIrRQ_270.JPG: 480x640 (no detections), 292.6ms
Speed: 1.1ms preprocess, 292.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wosd0URqLdQQwooPJaoJmw_0.JPG: 480x640 (no detections), 289.7ms
Speed: 1.1ms preprocess, 289.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wosd0URqLdQQwooPJaoJmw_90.JPG: 480x640 (no detections), 286.9ms
Speed: 1.6ms preprocess, 286.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wosd0URqLdQQwooPJaoJmw_180.JPG: 480x640 (no detections), 294.6ms
Speed: 1.4ms preprocess, 294.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wosd0URqLdQQwooPJaoJmw_270.JPG: 480x640 (no detections), 294.4ms
Speed: 1.9ms preprocess, 294.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wot9DQega-gtKBuQoSAENQ_0.JPG: 480x640 (no detections), 290.9ms
Speed: 1.1ms preprocess, 290.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wot9DQega-gtKBuQoSAENQ_90.JPG: 480x640 (no detections), 296.4ms
Speed: 1.1ms preprocess, 296.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wot9DQega-gtKBuQoSAENQ_180.JPG: 480x640 (no detections), 293.4ms
Speed: 1.2ms preprocess, 293.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/wot9DQega-gtKBuQoSAENQ_270.JPG: 480x640 (no detections), 293.4ms
Speed: 1.1ms preprocess, 293.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woyhuvDgWOuwiScOS1kvFg_0.JPG: 480x640 (no detections), 298.6ms
Speed: 1.5ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woyhuvDgWOuwiScOS1kvFg_90.JPG: 480x640 (no detections), 294.7ms
Speed: 1.1ms preprocess, 294.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woyhuvDgWOuwiScOS1kvFg_180.JPG: 480x640 1 Waste, 291.4ms
Speed: 1.0ms preprocess, 291.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woyhuvDgWOuwiScOS1kvFg_270.JPG: 480x640 1 Waste, 290.9ms
Speed: 1.3ms preprocess, 290.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woz07XQDtFiyOlG9TiSXUQ_0.JPG: 480x640 (no detections), 289.3ms
Speed: 1.2ms preprocess, 289.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woz07XQDtFiyOlG9TiSXUQ_90.JPG: 480x640 (no detections), 299.4ms
Speed: 1.7ms preprocess, 299.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woz07XQDtFiyOlG9TiSXUQ_180.JPG: 480x640 (no detections), 291.4ms
Speed: 1.1ms preprocess, 291.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/O/woz07XQDtFiyOlG9TiSXUQ_270.JPG: 480x640 (no detections), 293.3ms
Speed: 1.1ms preprocess, 293.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wp4mCYP0G6BJ6nhDRlYZ8w_0.JPG: 480x640 (no detections), 293.2ms
Speed: 1.4ms preprocess, 293.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wp4mCYP0G6BJ6nhDRlYZ8w_90.JPG: 480x640 (no detections), 297.3ms
Speed: 1.2ms preprocess, 297.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wp4mCYP0G6BJ6nhDRlYZ8w_180.JPG: 480x640 (no detections), 291.8ms
Speed: 1.2ms preprocess, 291.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wp4mCYP0G6BJ6nhDRlYZ8w_270.JPG: 480x640 (no detections), 291.7ms
Speed: 1.3ms preprocess, 291.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wp8SFWt2iGvkEWt4sfzmVg_0.JPG: 480x640 (no detections), 294.4ms
Speed: 1.2ms preprocess, 294.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wp8SFWt2iGvkEWt4sfzmVg_90.JPG: 480x640 1 Waste, 292.3ms
Speed: 1.2ms preprocess, 292.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wp8SFWt2iGvkEWt4sfzmVg_180.JPG: 480x640 (no detections), 292.3ms
Speed: 1.1ms preprocess, 292.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wp8SFWt2iGvkEWt4sfzmVg_270.JPG: 480x640 (no detections), 296.4ms
Speed: 1.2ms preprocess, 296.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wp9hwytMd0Yk_K644bH8CA_0.JPG: 480x640 (no detections), 288.3ms
Speed: 1.7ms preprocess, 288.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wp9hwytMd0Yk_K644bH8CA_90.JPG: 480x640 (no detections), 305.4ms
Speed: 1.8ms preprocess, 305.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wp9hwytMd0Yk_K644bH8CA_180.JPG: 480x640 (no detections), 308.1ms
Speed: 1.4ms preprocess, 308.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wp9hwytMd0Yk_K644bH8CA_270.JPG: 480x640 (no detections), 305.7ms
Speed: 1.4ms preprocess, 305.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpCwaiYT5YmJxiIiF_jCSA_0.JPG: 480x640 (no detections), 314.9ms
Speed: 1.1ms preprocess, 314.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpCwaiYT5YmJxiIiF_jCSA_90.JPG: 480x640 (no detections), 318.5ms
Speed: 1.1ms preprocess, 318.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpCwaiYT5YmJxiIiF_jCSA_180.JPG: 480x640 (no detections), 296.8ms
Speed: 1.4ms preprocess, 296.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpCwaiYT5YmJxiIiF_jCSA_270.JPG: 480x640 (no detections), 297.3ms
Speed: 1.2ms preprocess, 297.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpESjZyAVFLHsdx8Im5Reg_0.JPG: 480x640 (no detections), 291.7ms
Speed: 1.2ms preprocess, 291.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpESjZyAVFLHsdx8Im5Reg_90.JPG: 480x640 (no detections), 291.8ms
Speed: 1.2ms preprocess, 291.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpESjZyAVFLHsdx8Im5Reg_180.JPG: 480x640 (no detections), 297.6ms
Speed: 1.4ms preprocess, 297.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpESjZyAVFLHsdx8Im5Reg_270.JPG: 480x640 (no detections), 297.4ms
Speed: 1.2ms preprocess, 297.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpHdN7m_3Me3IXJyc_G4Tg_0.JPG: 480x640 (no detections), 297.5ms
Speed: 1.3ms preprocess, 297.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpHdN7m_3Me3IXJyc_G4Tg_90.JPG: 480x640 (no detections), 291.1ms
Speed: 1.2ms preprocess, 291.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpHdN7m_3Me3IXJyc_G4Tg_180.JPG: 480x640 (no detections), 297.3ms
Speed: 1.2ms preprocess, 297.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpHdN7m_3Me3IXJyc_G4Tg_270.JPG: 480x640 (no detections), 293.4ms
Speed: 1.2ms preprocess, 293.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpIKy78SehDBmOJIVhKsiA_0.JPG: 480x640 (no detections), 306.7ms
Speed: 1.2ms preprocess, 306.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpIKy78SehDBmOJIVhKsiA_90.JPG: 480x640 (no detections), 295.3ms
Speed: 1.1ms preprocess, 295.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpIKy78SehDBmOJIVhKsiA_180.JPG: 480x640 (no detections), 292.4ms
Speed: 1.1ms preprocess, 292.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpIKy78SehDBmOJIVhKsiA_270.JPG: 480x640 (no detections), 300.5ms
Speed: 1.4ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpNsrI2YGFDsiwaAW5dq5g_0.JPG: 480x640 (no detections), 298.9ms
Speed: 1.2ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpNsrI2YGFDsiwaAW5dq5g_90.JPG: 480x640 (no detections), 293.2ms
Speed: 1.0ms preprocess, 293.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpNsrI2YGFDsiwaAW5dq5g_180.JPG: 480x640 (no detections), 296.4ms
Speed: 1.3ms preprocess, 296.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpNsrI2YGFDsiwaAW5dq5g_270.JPG: 480x640 (no detections), 290.8ms
Speed: 1.1ms preprocess, 290.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpOmqQS1oQPMQ26QQJFq3A_0.JPG: 480x640 (no detections), 293.2ms
Speed: 1.0ms preprocess, 293.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpOmqQS1oQPMQ26QQJFq3A_90.JPG: 480x640 (no detections), 291.4ms
Speed: 1.2ms preprocess, 291.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpOmqQS1oQPMQ26QQJFq3A_180.JPG: 480x640 (no detections), 294.7ms
Speed: 1.1ms preprocess, 294.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpOmqQS1oQPMQ26QQJFq3A_270.JPG: 480x640 (no detections), 292.9ms
Speed: 1.3ms preprocess, 292.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpRaMHZ9fyrP4JQMlh7tiA_0.JPG: 480x640 (no detections), 292.6ms
Speed: 1.0ms preprocess, 292.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpRaMHZ9fyrP4JQMlh7tiA_90.JPG: 480x640 (no detections), 291.6ms
Speed: 1.2ms preprocess, 291.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpRaMHZ9fyrP4JQMlh7tiA_180.JPG: 480x640 (no detections), 315.5ms
Speed: 1.3ms preprocess, 315.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpRaMHZ9fyrP4JQMlh7tiA_270.JPG: 480x640 (no detections), 302.9ms
Speed: 1.5ms preprocess, 302.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpWKCfSRsLvHEQDfZGXbjg_0.JPG: 480x640 (no detections), 326.7ms
Speed: 1.4ms preprocess, 326.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpWKCfSRsLvHEQDfZGXbjg_90.JPG: 480x640 (no detections), 313.2ms
Speed: 1.1ms preprocess, 313.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpWKCfSRsLvHEQDfZGXbjg_180.JPG: 480x640 (no detections), 300.2ms
Speed: 2.0ms preprocess, 300.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpWKCfSRsLvHEQDfZGXbjg_270.JPG: 480x640 (no detections), 299.8ms
Speed: 1.3ms preprocess, 299.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpWOEFTgsBQgMgRuf0TfUA_0.JPG: 480x640 (no detections), 301.3ms
Speed: 1.1ms preprocess, 301.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpWOEFTgsBQgMgRuf0TfUA_90.JPG: 480x640 (no detections), 348.5ms
Speed: 1.8ms preprocess, 348.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpWOEFTgsBQgMgRuf0TfUA_180.JPG: 480x640 (no detections), 343.9ms

Speed: 1.3ms preprocess, 343.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpWOEFTgsBQgMgRuf0TfUA_270.JPG: 480x640 (no detections), 315.4ms
Speed: 1.2ms preprocess, 315.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpWbzSKA5TUV2jBXqoic2A_0.JPG: 480x640 (no detections), 319.9ms
Speed: 1.4ms preprocess, 319.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpWbzSKA5TUV2jBXqoic2A_90.JPG: 480x640 1 Waste, 304.1ms
Speed: 1.3ms preprocess, 304.1ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpWbzSKA5TUV2jBXqoic2A_180.JPG: 480x640 (no detections), 312.0ms
Speed: 1.3ms preprocess, 312.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpWbzSKA5TUV2jBXqoic2A_270.JPG: 480x640 (no detections), 309.4ms
Speed: 1.4ms preprocess, 309.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpXl4m30Z6ED1pIWFY6A9Q_0.JPG: 480x640 (no detections), 303.5ms
Speed: 1.2ms preprocess, 303.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpXl4m30Z6ED1pIWFY6A9Q_90.JPG: 480x640 (no detections), 303.5ms
Speed: 1.7ms preprocess, 303.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpXl4m30Z6ED1pIWFY6A9Q_180.JPG: 480x640 (no detections), 291.4ms
Speed: 1.2ms preprocess, 291.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpXl4m30Z6ED1pIWFY6A9Q_270.JPG: 480x640 (no detections), 292.3ms
Speed: 1.5ms preprocess, 292.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpZQ82q-QgdlkTs5cMdgZw_0.JPG: 480x640 (no detections), 306.4ms
Speed: 1.3ms preprocess, 306.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpZQ82q-QgdlkTs5cMdgZw_90.JPG: 480x640 (no detections), 303.3ms
Speed: 1.1ms preprocess, 303.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpZQ82q-QgdlkTs5cMdgZw_180.JPG: 480x640 (no detections), 309.5ms
Speed: 1.0ms preprocess, 309.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpZQ82q-QgdlkTs5cMdgZw_270.JPG: 480x640 (no detections), 307.3ms
Speed: 1.4ms preprocess, 307.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpb3rWe4M4h91D2sIydnXg_0.JPG: 480x640 (no detections), 299.6ms
Speed: 1.2ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpb3rWe4M4h91D2sIydnXg_90.JPG: 480x640 (no detections), 298.7ms
Speed: 1.0ms preprocess, 298.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpb3rWe4M4h91D2sIydnXg_180.JPG: 480x640 (no detections), 364.4ms
Speed: 2.3ms preprocess, 364.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpb3rWe4M4h91D2sIydnXg_270.JPG: 480x640 (no detections), 321.9ms
Speed: 1.2ms preprocess, 321.9ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpdGFN76LuBgST3mD9G1dA_0.JPG: 480x640 (no detections), 324.0ms
Speed: 1.4ms preprocess, 324.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpdGFN76LuBgST3mD9G1dA_90.JPG: 480x640 (no detections), 350.9ms
Speed: 1.1ms preprocess, 350.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpdGFN76LuBgST3mD9G1dA_180.JPG: 480x640 (no detections), 443.4ms
Speed: 1.6ms preprocess, 443.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpdGFN76LuBgST3mD9G1dA_270.JPG: 480x640 (no detections), 349.7ms
Speed: 1.3ms preprocess, 349.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpkctUpAm4iXwPb3PT-pvw_0.JPG: 480x640 (no detections), 309.7ms
Speed: 1.4ms preprocess, 309.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpkctUpAm4iXwPb3PT-pvw_90.JPG: 480x640 (no detections), 296.8ms
Speed: 1.2ms preprocess, 296.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpkctUpAm4iXwPb3PT-pvw_180.JPG: 480x640 (no detections), 317.3ms
Speed: 1.4ms preprocess, 317.3ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpkctUpAm4iXwPb3PT-pvw_270.JPG: 480x640 (no detections), 311.1ms
Speed: 1.6ms preprocess, 311.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wplyIMlSynG4wcucTDE9EQ_0.JPG: 480x640 (no detections), 306.4ms
Speed: 1.2ms preprocess, 306.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wplyIMlSynG4wcucTDE9EQ_90.JPG: 480x640 (no detections), 293.3ms
Speed: 1.1ms preprocess, 293.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wplyIMlSynG4wcucTDE9EQ_180.JPG: 480x640 (no detections), 290.6ms
Speed: 1.2ms preprocess, 290.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wplyIMlSynG4wcucTDE9EQ_270.JPG: 480x640 (no detections), 296.7ms
Speed: 1.3ms preprocess, 296.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpmUhMt8swkMr4jgmyqnXw_0.JPG: 480x640 (no detections), 303.6ms
Speed: 1.1ms preprocess, 303.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpmUhMt8swkMr4jgmyqnXw_90.JPG: 480x640 (no detections), 311.0ms
Speed: 1.2ms preprocess, 311.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpmUhMt8swkMr4jgmyqnXw_180.JPG: 480x640 (no detections), 303.4ms
Speed: 1.3ms preprocess, 303.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpmUhMt8swkMr4jgmyqnXw_270.JPG: 480x640 (no detections), 304.5ms
Speed: 1.6ms preprocess, 304.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpmeKUpUUEOjipmesV-4KQ_0.JPG: 480x640 (no detections), 303.7ms
Speed: 1.9ms preprocess, 303.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpmeKUpUUEOjipmesV-4KQ_90.JPG: 480x640 (no detections), 310.6ms
Speed: 1.3ms preprocess, 310.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpmeKUpUUEOjipmesV-4KQ_180.JPG: 480x640 (no detections), 315.1ms
Speed: 1.3ms preprocess, 315.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpmeKUpUUEOjipmesV-4KQ_270.JPG: 480x640 (no detections), 322.9ms
Speed: 1.3ms preprocess, 322.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpnskyEqUSdStEOly_tiHA_0.JPG: 480x640 (no detections), 318.6ms
Speed: 1.2ms preprocess, 318.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpnskyEqUSdStEOly_tiHA_90.JPG: 480x640 (no detections), 319.1ms
Speed: 1.2ms preprocess, 319.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpnskyEqUSdStEOly_tiHA_180.JPG: 480x640 (no detections), 319.4ms
Speed: 1.3ms preprocess, 319.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpnskyEqUSdStEOly_tiHA_270.JPG: 480x640 (no detections), 305.0ms
Speed: 1.4ms preprocess, 305.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpqg5amH7Bh-q2M8ia2h2A_0.JPG: 480x640 1 Waste, 302.6ms
Speed: 1.1ms preprocess, 302.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpqg5amH7Bh-q2M8ia2h2A_90.JPG: 480x640 (no detections), 301.5ms
Speed: 1.2ms preprocess, 301.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpqg5amH7Bh-q2M8ia2h2A_180.JPG: 480x640 (no detections), 299.4ms
Speed: 1.2ms preprocess, 299.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpqg5amH7Bh-q2M8ia2h2A_270.JPG: 480x640 3 Wastes, 298.3ms
Speed: 1.2ms preprocess, 298.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpsFKrc4Qt9axWGFZSEulQ_0.JPG: 480x640 (no detections), 312.5ms
Speed: 1.2ms preprocess, 312.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpsFKrc4Qt9axWGFZSEulQ_90.JPG: 480x640 (no detections), 297.2ms
Speed: 1.2ms preprocess, 297.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpsFKrc4Qt9axWGFZSEulQ_180.JPG: 480x640 (no detections), 303.0ms
Speed: 1.2ms preprocess, 303.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpsFKrc4Qt9axWGFZSEulQ_270.JPG: 480x640 (no detections), 301.3ms
Speed: 1.1ms preprocess, 301.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wptG0sNM4XTyptS-CFaYZQ_0.JPG: 480x640 (no detections), 292.6ms
Speed: 1.3ms preprocess, 292.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wptG0sNM4XTyptS-CFaYZQ_90.JPG: 480x640 (no detections), 294.2ms
Speed: 1.3ms preprocess, 294.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wptG0sNM4XTyptS-CFaYZQ_180.JPG: 480x640 (no detections), 305.9ms
Speed: 1.3ms preprocess, 305.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wptG0sNM4XTyptS-CFaYZQ_270.JPG: 480x640 (no detections), 348.8ms
Speed: 1.2ms preprocess, 348.8ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wptRibzQD7CKLn60msbwYQ_0.JPG: 480x640 (no detections), 316.5ms
Speed: 1.3ms preprocess, 316.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wptRibzQD7CKLn60msbwYQ_90.JPG: 480x640 (no detections), 305.3ms
Speed: 1.2ms preprocess, 305.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wptRibzQD7CKLn60msbwYQ_180.JPG: 480x640 (no detections), 301.5ms
Speed: 1.3ms preprocess, 301.5ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wptRibzQD7CKLn60msbwYQ_270.JPG: 480x640 (no detections), 294.2ms
Speed: 1.1ms preprocess, 294.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpvkNr1fa1rfQja03Ios5Q_0.JPG: 480x640 (no detections), 312.2ms
Speed: 1.2ms preprocess, 312.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpvkNr1fa1rfQja03Ios5Q_90.JPG: 480x640 (no detections), 297.3ms
Speed: 1.7ms preprocess, 297.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpvkNr1fa1rfQja03Ios5Q_180.JPG: 480x640 (no detections), 295.3ms
Speed: 1.4ms preprocess, 295.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpvkNr1fa1rfQja03Ios5Q_270.JPG: 480x640 (no detections), 292.9ms
Speed: 1.4ms preprocess, 292.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpw2MAoVJ1NSXRiAHR2BBw_0.JPG: 480x640 (no detections), 285.9ms
Speed: 1.3ms preprocess, 285.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpw2MAoVJ1NSXRiAHR2BBw_90.JPG: 480x640 (no detections), 315.7ms
Speed: 1.3ms preprocess, 315.7ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpw2MAoVJ1NSXRiAHR2BBw_180.JPG: 480x640 (no detections), 306.1ms
Speed: 1.4ms preprocess, 306.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/P/wpw2MAoVJ1NSXRiAHR2BBw_270.JPG: 480x640 (no detections), 289.3ms
Speed: 1.3ms preprocess, 289.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wq2TJ9SeWTPqakxD_4-4TA_0.JPG: 480x640 (no detections), 297.5ms
Speed: 1.2ms preprocess, 297.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wq2TJ9SeWTPqakxD_4-4TA_90.JPG: 480x640 (no detections), 285.0ms

Speed: 1.1ms preprocess, 285.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wq2TJ9SeWTPqakxD_4-4TA_180.JPG: 480x640 (no detections), 289.5ms
Speed: 1.1ms preprocess, 289.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wq2TJ9SeWTPqakxD_4-4TA_270.JPG: 480x640 (no detections), 290.7ms
Speed: 1.5ms preprocess, 290.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wq3I8IczzzD2jnQNAoFYpA_0.JPG: 480x640 (no detections), 288.2ms
Speed: 1.4ms preprocess, 288.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wq3I8IczzzD2jnQNAoFYpA_90.JPG: 480x640 (no detections), 297.1ms
Speed: 1.0ms preprocess, 297.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wq3I8IczzzD2jnQNAoFYpA_180.JPG: 480x640 (no detections), 297.3ms
Speed: 1.2ms preprocess, 297.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wq3I8IczzzD2jnQNAoFYpA_270.JPG: 480x640 (no detections), 310.5ms
Speed: 1.1ms preprocess, 310.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wq4Nm3JMacTVTfo7j0yfDA_0.JPG: 480x640 (no detections), 297.5ms
Speed: 1.5ms preprocess, 297.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wq4Nm3JMacTVTfo7j0yfDA_90.JPG: 480x640 (no detections), 294.5ms
Speed: 1.2ms preprocess, 294.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wq4Nm3JMacTVTfo7j0yfDA_180.JPG: 480x640 (no detections), 290.2ms
Speed: 1.1ms preprocess, 290.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wq4Nm3JMacTVTfo7j0yfDA_270.JPG: 480x640 (no detections), 292.3ms
Speed: 1.0ms preprocess, 292.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wq6W-awSBhGtGbIjrVDugg_0.JPG: 480x640 (no detections), 291.5ms
Speed: 1.4ms preprocess, 291.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wq6W-awSBhGtGbIjrVDugg_90.JPG: 480x640 (no detections), 294.4ms
Speed: 1.1ms preprocess, 294.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wq6W-awSBhGtGbIjrVDugg_180.JPG: 480x640 (no detections), 292.4ms
Speed: 1.2ms preprocess, 292.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wq6W-awSBhGtGbIjrVDugg_270.JPG: 480x640 (no detections), 294.2ms
Speed: 1.9ms preprocess, 294.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wq74xLcz_z6zzCPZ0WPNnQ_0.JPG: 480x640 (no detections), 295.8ms
Speed: 1.7ms preprocess, 295.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wq74xLcz_z6zzCPZ0WPNnQ_90.JPG: 480x640 (no detections), 291.4ms
Speed: 1.1ms preprocess, 291.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wq74xLcz_z6zzCPZ0WPNnQ_180.JPG: 480x640 (no detections), 299.1ms
Speed: 1.1ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wq74xLcz_z6zzCPZ0WPNnQ_270.JPG: 480x640 (no detections), 289.7ms
Speed: 1.1ms preprocess, 289.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wq8qShvJ7B8wsKfJbMYnXA_0.JPG: 480x640 (no detections), 296.9ms
Speed: 1.3ms preprocess, 296.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wq8qShvJ7B8wsKfJbMYnXA_90.JPG: 480x640 (no detections), 317.5ms
Speed: 1.8ms preprocess, 317.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wq8qShvJ7B8wsKfJbMYnXA_180.JPG: 480x640 (no detections), 296.8ms
Speed: 1.6ms preprocess, 296.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wq8qShvJ7B8wsKfJbMYnXA_270.JPG: 480x640 (no detections), 296.2ms
Speed: 1.3ms preprocess, 296.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqAdl_Ok4g_IMagjmfJFiQ_0.JPG: 480x640 (no detections), 300.5ms
Speed: 1.2ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqAdl_Ok4g_IMagjmfJFiQ_90.JPG: 480x640 (no detections), 306.1ms
Speed: 1.3ms preprocess, 306.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqAdl_Ok4g_IMagjmfJFiQ_180.JPG: 480x640 (no detections), 289.4ms
Speed: 1.4ms preprocess, 289.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqAdl_Ok4g_IMagjmfJFiQ_270.JPG: 480x640 (no detections), 301.2ms
Speed: 1.0ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqE9NyPCukMMTmePdUISSQ_0.JPG: 480x640 (no detections), 342.1ms
Speed: 1.6ms preprocess, 342.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqE9NyPCukMMTmePdUISSQ_90.JPG: 480x640 (no detections), 339.9ms
Speed: 1.3ms preprocess, 339.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqE9NyPCukMMTmePdUISSQ_180.JPG: 480x640 (no detections), 329.2ms
Speed: 1.5ms preprocess, 329.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqE9NyPCukMMTmePdUISSQ_270.JPG: 480x640 (no detections), 330.2ms
Speed: 3.1ms preprocess, 330.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqEYfeNs-t6a_LsJlWtUBg_0.JPG: 480x640 (no detections), 308.4ms
Speed: 1.5ms preprocess, 308.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqEYfeNs-t6a_LsJlWtUBg_90.JPG: 480x640 (no detections), 295.2ms
Speed: 1.3ms preprocess, 295.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqEYfeNs-t6a_LsJlWtUBg_180.JPG: 480x640 (no detections), 293.9ms
Speed: 1.1ms preprocess, 293.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqEYfeNs-t6a_LsJlWtUBg_270.JPG: 480x640 (no detections), 294.0ms
Speed: 1.1ms preprocess, 294.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqJGxO0r27xTpkxxoaxaAg_0.JPG: 480x640 (no detections), 290.7ms
Speed: 1.2ms preprocess, 290.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqJGxO0r27xTpkxxoaxaAg_90.JPG: 480x640 (no detections), 290.3ms
Speed: 1.1ms preprocess, 290.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqJGxO0r27xTpkxxoaxaAg_180.JPG: 480x640 (no detections), 289.5ms
Speed: 1.3ms preprocess, 289.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqJGxO0r27xTpkxxoaxaAg_270.JPG: 480x640 (no detections), 292.2ms
Speed: 1.3ms preprocess, 292.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqLteI52_oDffU-hri2Czg_0.JPG: 480x640 (no detections), 290.5ms
Speed: 1.2ms preprocess, 290.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqLteI52_oDffU-hri2Czg_90.JPG: 480x640 (no detections), 307.2ms
Speed: 1.9ms preprocess, 307.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqLteI52_oDffU-hri2Czg_180.JPG: 480x640 (no detections), 293.8ms
Speed: 1.1ms preprocess, 293.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqLteI52_oDffU-hri2Czg_270.JPG: 480x640 (no detections), 293.2ms
Speed: 1.2ms preprocess, 293.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqM7BmSVKIKvD8T90H_Y1A_0.JPG: 480x640 (no detections), 317.8ms
Speed: 1.3ms preprocess, 317.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqM7BmSVKIKvD8T90H_Y1A_90.JPG: 480x640 (no detections), 306.6ms
Speed: 1.6ms preprocess, 306.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqM7BmSVKIKvD8T90H_Y1A_180.JPG: 480x640 (no detections), 295.6ms
Speed: 1.0ms preprocess, 295.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqM7BmSVKIKvD8T90H_Y1A_270.JPG: 480x640 (no detections), 310.1ms
Speed: 1.1ms preprocess, 310.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqOtDg1OEKvTDZvcdEpsmQ_0.JPG: 480x640 (no detections), 299.5ms
Speed: 1.4ms preprocess, 299.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqOtDg1OEKvTDZvcdEpsmQ_90.JPG: 480x640 (no detections), 313.6ms
Speed: 1.2ms preprocess, 313.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqOtDg1OEKvTDZvcdEpsmQ_180.JPG: 480x640 (no detections), 303.2ms
Speed: 1.2ms preprocess, 303.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqOtDg1OEKvTDZvcdEpsmQ_270.JPG: 480x640 (no detections), 291.5ms
Speed: 2.1ms preprocess, 291.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqRe0-XVtDpbckr76M590w_0.JPG: 480x640 (no detections), 303.5ms
Speed: 1.1ms preprocess, 303.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqRe0-XVtDpbckr76M590w_90.JPG: 480x640 (no detections), 309.7ms
Speed: 1.1ms preprocess, 309.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqRe0-XVtDpbckr76M590w_180.JPG: 480x640 (no detections), 295.6ms
Speed: 1.3ms preprocess, 295.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqRe0-XVtDpbckr76M590w_270.JPG: 480x640 (no detections), 291.7ms
Speed: 1.2ms preprocess, 291.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqa-UqEvGIT5_8-SoQ9K7w_0.JPG: 480x640 (no detections), 292.2ms
Speed: 1.2ms preprocess, 292.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqa-UqEvGIT5_8-SoQ9K7w_90.JPG: 480x640 (no detections), 298.6ms
Speed: 1.0ms preprocess, 298.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqa-UqEvGIT5_8-SoQ9K7w_180.JPG: 480x640 (no detections), 293.3ms
Speed: 1.2ms preprocess, 293.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqa-UqEvGIT5_8-SoQ9K7w_270.JPG: 480x640 (no detections), 284.5ms
Speed: 1.4ms preprocess, 284.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqaf3OKNpAm1WCZSILZKqQ_0.JPG: 480x640 (no detections), 288.8ms
Speed: 1.3ms preprocess, 288.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqaf3OKNpAm1WCZSILZKqQ_90.JPG: 480x640 (no detections), 291.2ms
Speed: 1.4ms preprocess, 291.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqaf3OKNpAm1WCZSILZKqQ_180.JPG: 480x640 (no detections), 293.6ms
Speed: 1.2ms preprocess, 293.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqaf3OKNpAm1WCZSILZKqQ_270.JPG: 480x640 (no detections), 289.7ms
Speed: 1.2ms preprocess, 289.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqedM1T6620DK8cSoH7dkA_0.JPG: 480x640 (no detections), 288.0ms
Speed: 1.1ms preprocess, 288.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqedM1T6620DK8cSoH7dkA_90.JPG: 480x640 (no detections), 287.8ms
Speed: 1.2ms preprocess, 287.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqedM1T6620DK8cSoH7dkA_180.JPG: 480x640 (no detections), 310.2ms
Speed: 1.3ms preprocess, 310.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqedM1T6620DK8cSoH7dkA_270.JPG: 480x640 (no detections), 289.3ms
Speed: 1.2ms preprocess, 289.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqfZqt0antlzzuwIm3xeYQ_0.JPG: 480x640 (no detections), 288.9ms

Speed: 1.3ms preprocess, 288.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqfZqt0antlzzuwIm3xeYQ_90.JPG: 480x640 (no detections), 301.6ms
Speed: 2.0ms preprocess, 301.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqfZqt0antlzzuwIm3xeYQ_180.JPG: 480x640 (no detections), 299.7ms
Speed: 1.4ms preprocess, 299.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqfZqt0antlzzuwIm3xeYQ_270.JPG: 480x640 (no detections), 309.9ms
Speed: 1.7ms preprocess, 309.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqiPCCZuzLYGZ6oou9OLNg_0.JPG: 480x640 (no detections), 300.4ms
Speed: 1.3ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqiPCCZuzLYGZ6oou9OLNg_90.JPG: 480x640 (no detections), 303.9ms
Speed: 1.1ms preprocess, 303.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqiPCCZuzLYGZ6oou9OLNg_180.JPG: 480x640 (no detections), 294.7ms
Speed: 1.2ms preprocess, 294.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqiPCCZuzLYGZ6oou9OLNg_270.JPG: 480x640 (no detections), 299.3ms
Speed: 1.5ms preprocess, 299.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqjWX7utK50KHf-ZqrMIxg_0.JPG: 480x640 (no detections), 293.6ms
Speed: 1.2ms preprocess, 293.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqjWX7utK50KHf-ZqrMIxg_90.JPG: 480x640 (no detections), 297.3ms
Speed: 1.4ms preprocess, 297.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqjWX7utK50KHf-ZqrMIxg_180.JPG: 480x640 (no detections), 299.0ms
Speed: 1.1ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqjWX7utK50KHf-ZqrMIxg_270.JPG: 480x640 (no detections), 294.6ms
Speed: 1.2ms preprocess, 294.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqlSzcHEyZKqZEpeRQCWbw_0.JPG: 480x640 (no detections), 292.7ms
Speed: 1.5ms preprocess, 292.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqlSzcHEyZKqZEpeRQCWbw_90.JPG: 480x640 (no detections), 294.9ms
Speed: 1.1ms preprocess, 294.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqlSzcHEyZKqZEpeRQCWbw_180.JPG: 480x640 (no detections), 322.0ms
Speed: 1.3ms preprocess, 322.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqlSzcHEyZKqZEpeRQCWbw_270.JPG: 480x640 (no detections), 297.4ms
Speed: 1.1ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqnBureJ3fxVChm3APFuhw_0.JPG: 480x640 (no detections), 301.6ms
Speed: 1.1ms preprocess, 301.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqnBureJ3fxVChm3APFuhw_90.JPG: 480x640 (no detections), 301.3ms
Speed: 1.3ms preprocess, 301.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqnBureJ3fxVChm3APFuhw_180.JPG: 480x640 (no detections), 297.1ms
Speed: 1.6ms preprocess, 297.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqnBureJ3fxVChm3APFuhw_270.JPG: 480x640 (no detections), 299.6ms
Speed: 1.1ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqptQs01dtnLDW1H_MStxg_0.JPG: 480x640 (no detections), 291.8ms
Speed: 2.0ms preprocess, 291.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqptQs01dtnLDW1H_MStxg_90.JPG: 480x640 (no detections), 295.3ms
Speed: 1.2ms preprocess, 295.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqptQs01dtnLDW1H_MStxg_180.JPG: 480x640 (no detections), 287.5ms
Speed: 1.1ms preprocess, 287.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqptQs01dtnLDW1H_MStxg_270.JPG: 480x640 (no detections), 295.3ms
Speed: 1.1ms preprocess, 295.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqq_IJmoNgfuwX9ZcBHm5g_0.JPG: 480x640 (no detections), 295.7ms
Speed: 1.2ms preprocess, 295.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqq_IJmoNgfuwX9ZcBHm5g_90.JPG: 480x640 (no detections), 313.5ms
Speed: 1.2ms preprocess, 313.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqq_IJmoNgfuwX9ZcBHm5g_180.JPG: 480x640 (no detections), 297.4ms
Speed: 1.2ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqq_IJmoNgfuwX9ZcBHm5g_270.JPG: 480x640 (no detections), 306.0ms
Speed: 1.2ms preprocess, 306.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqrg4gmfwEYUo3PfD-D5aQ_0.JPG: 480x640 (no detections), 299.2ms
Speed: 1.2ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqrg4gmfwEYUo3PfD-D5aQ_90.JPG: 480x640 (no detections), 300.3ms
Speed: 1.2ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqrg4gmfwEYUo3PfD-D5aQ_180.JPG: 480x640 (no detections), 294.0ms
Speed: 1.1ms preprocess, 294.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqrg4gmfwEYUo3PfD-D5aQ_270.JPG: 480x640 (no detections), 297.5ms
Speed: 1.3ms preprocess, 297.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqtN9OHkTaAOkjOvFzeIAw_0.JPG: 480x640 (no detections), 305.5ms
Speed: 1.5ms preprocess, 305.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqtN9OHkTaAOkjOvFzeIAw_90.JPG: 480x640 (no detections), 302.7ms
Speed: 1.2ms preprocess, 302.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqtN9OHkTaAOkjOvFzeIAw_180.JPG: 480x640 (no detections), 290.4ms
Speed: 1.1ms preprocess, 290.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Q/wqtN9OHkTaAOkjOvFzeIAw_270.JPG: 480x640 (no detections), 298.7ms
Speed: 1.1ms preprocess, 298.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wr1VqzS7nSuck9V-OkuGMA_0.JPG: 480x640 (no detections), 293.2ms
Speed: 1.1ms preprocess, 293.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wr1VqzS7nSuck9V-OkuGMA_90.JPG: 480x640 (no detections), 297.0ms
Speed: 1.1ms preprocess, 297.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wr1VqzS7nSuck9V-OkuGMA_180.JPG: 480x640 1 Waste, 298.2ms
Speed: 1.0ms preprocess, 298.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wr1VqzS7nSuck9V-OkuGMA_270.JPG: 480x640 (no detections), 291.2ms
Speed: 1.3ms preprocess, 291.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wr3r60Obp-uI9xBJuiNl2Q_0.JPG: 480x640 (no detections), 296.9ms
Speed: 1.4ms preprocess, 296.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wr3r60Obp-uI9xBJuiNl2Q_90.JPG: 480x640 (no detections), 299.6ms
Speed: 1.2ms preprocess, 299.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wr3r60Obp-uI9xBJuiNl2Q_180.JPG: 480x640 (no detections), 289.6ms
Speed: 1.1ms preprocess, 289.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wr3r60Obp-uI9xBJuiNl2Q_270.JPG: 480x640 (no detections), 302.5ms
Speed: 1.3ms preprocess, 302.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wr5uhQ-m0PXsWYAGWe0IuA_0.JPG: 480x640 (no detections), 293.8ms
Speed: 1.2ms preprocess, 293.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wr5uhQ-m0PXsWYAGWe0IuA_90.JPG: 480x640 (no detections), 299.2ms
Speed: 1.1ms preprocess, 299.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wr5uhQ-m0PXsWYAGWe0IuA_180.JPG: 480x640 (no detections), 299.7ms
Speed: 1.4ms preprocess, 299.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wr5uhQ-m0PXsWYAGWe0IuA_270.JPG: 480x640 (no detections), 298.6ms
Speed: 1.2ms preprocess, 298.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wr6dWMsIta7-V9bR6h1CPA_0.JPG: 480x640 1 Waste, 297.7ms
Speed: 1.2ms preprocess, 297.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wr6dWMsIta7-V9bR6h1CPA_90.JPG: 480x640 (no detections), 295.1ms
Speed: 1.3ms preprocess, 295.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wr6dWMsIta7-V9bR6h1CPA_180.JPG: 480x640 (no detections), 295.4ms
Speed: 1.2ms preprocess, 295.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wr6dWMsIta7-V9bR6h1CPA_270.JPG: 480x640 (no detections), 301.6ms
Speed: 1.2ms preprocess, 301.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wr6ztJZGqdh1DkLnOtFkLg_0.JPG: 480x640 (no detections), 305.0ms
Speed: 1.4ms preprocess, 305.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wr6ztJZGqdh1DkLnOtFkLg_90.JPG: 480x640 (no detections), 294.3ms
Speed: 1.4ms preprocess, 294.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wr6ztJZGqdh1DkLnOtFkLg_180.JPG: 480x640 (no detections), 290.6ms
Speed: 1.3ms preprocess, 290.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wr6ztJZGqdh1DkLnOtFkLg_270.JPG: 480x640 (no detections), 288.7ms
Speed: 1.3ms preprocess, 288.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wr7Xm7EbmLt_Hhws-UKNAw_0.JPG: 480x640 (no detections), 299.2ms
Speed: 1.1ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wr7Xm7EbmLt_Hhws-UKNAw_90.JPG: 480x640 (no detections), 293.1ms
Speed: 1.3ms preprocess, 293.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wr7Xm7EbmLt_Hhws-UKNAw_180.JPG: 480x640 (no detections), 289.1ms
Speed: 1.1ms preprocess, 289.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wr7Xm7EbmLt_Hhws-UKNAw_270.JPG: 480x640 (no detections), 296.6ms
Speed: 1.1ms preprocess, 296.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wr8NqIzkACu6SDdoQ62FOQ_0.JPG: 480x640 (no detections), 309.1ms
Speed: 1.0ms preprocess, 309.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wr8NqIzkACu6SDdoQ62FOQ_90.JPG: 480x640 (no detections), 302.3ms
Speed: 1.2ms preprocess, 302.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wr8NqIzkACu6SDdoQ62FOQ_180.JPG: 480x640 (no detections), 314.7ms
Speed: 1.4ms preprocess, 314.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wr8NqIzkACu6SDdoQ62FOQ_270.JPG: 480x640 (no detections), 298.9ms
Speed: 1.3ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrD0Z8pHzwmEEKDMq1dL4A_0.JPG: 480x640 (no detections), 299.4ms
Speed: 1.1ms preprocess, 299.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrD0Z8pHzwmEEKDMq1dL4A_90.JPG: 480x640 (no detections), 289.5ms
Speed: 1.2ms preprocess, 289.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrD0Z8pHzwmEEKDMq1dL4A_180.JPG: 480x640 (no detections), 295.8ms
Speed: 1.4ms preprocess, 295.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrD0Z8pHzwmEEKDMq1dL4A_270.JPG: 480x640 (no detections), 295.6ms

Speed: 1.5ms preprocess, 295.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrD4DGeXYpYEgk9-l89ANw_0.JPG: 480x640 (no detections), 289.8ms
Speed: 1.1ms preprocess, 289.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrD4DGeXYpYEgk9-l89ANw_90.JPG: 480x640 (no detections), 294.5ms
Speed: 1.2ms preprocess, 294.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrD4DGeXYpYEgk9-l89ANw_180.JPG: 480x640 (no detections), 296.2ms
Speed: 1.4ms preprocess, 296.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrD4DGeXYpYEgk9-l89ANw_270.JPG: 480x640 (no detections), 307.7ms
Speed: 1.1ms preprocess, 307.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrDW3eEucHBV8G7iW35p6Q_0.JPG: 480x640 (no detections), 297.4ms
Speed: 1.3ms preprocess, 297.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrDW3eEucHBV8G7iW35p6Q_90.JPG: 480x640 (no detections), 296.8ms
Speed: 1.3ms preprocess, 296.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrDW3eEucHBV8G7iW35p6Q_180.JPG: 480x640 (no detections), 300.3ms
Speed: 1.3ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrDW3eEucHBV8G7iW35p6Q_270.JPG: 480x640 (no detections), 306.2ms
Speed: 1.3ms preprocess, 306.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrElCNkNYdpT1gwcjLC9GQ_0.JPG: 480x640 (no detections), 298.1ms
Speed: 1.2ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrElCNkNYdpT1gwcjLC9GQ_90.JPG: 480x640 (no detections), 299.7ms
Speed: 1.4ms preprocess, 299.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrElCNkNYdpT1gwcjLC9GQ_180.JPG: 480x640 (no detections), 303.8ms
Speed: 1.1ms preprocess, 303.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrElCNkNYdpT1gwcjLC9GQ_270.JPG: 480x640 (no detections), 304.4ms
Speed: 1.2ms preprocess, 304.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrGSL9i2sphqxDyofzL_kA_0.JPG: 480x640 (no detections), 307.4ms
Speed: 1.5ms preprocess, 307.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrGSL9i2sphqxDyofzL_kA_90.JPG: 480x640 (no detections), 293.2ms
Speed: 1.3ms preprocess, 293.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrGSL9i2sphqxDyofzL_kA_180.JPG: 480x640 (no detections), 313.6ms
Speed: 1.3ms preprocess, 313.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrGSL9i2sphqxDyofzL_kA_270.JPG: 480x640 (no detections), 290.0ms
Speed: 1.2ms preprocess, 290.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrJQUdzkW6nPe7cfw0Meog_0.JPG: 480x640 (no detections), 291.0ms
Speed: 1.2ms preprocess, 291.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrJQUdzkW6nPe7cfw0Meog_90.JPG: 480x640 (no detections), 296.8ms
Speed: 1.3ms preprocess, 296.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrJQUdzkW6nPe7cfw0Meog_180.JPG: 480x640 (no detections), 294.6ms
Speed: 1.3ms preprocess, 294.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrJQUdzkW6nPe7cfw0Meog_270.JPG: 480x640 (no detections), 291.5ms
Speed: 1.1ms preprocess, 291.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrJw7VqbEokJuKK_lVJ6ZQ_0.JPG: 480x640 (no detections), 290.1ms
Speed: 1.2ms preprocess, 290.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrJw7VqbEokJuKK_lVJ6ZQ_90.JPG: 480x640 (no detections), 290.1ms
Speed: 1.2ms preprocess, 290.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrJw7VqbEokJuKK_lVJ6ZQ_180.JPG: 480x640 (no detections), 287.7ms
Speed: 1.2ms preprocess, 287.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrJw7VqbEokJuKK_lVJ6ZQ_270.JPG: 480x640 (no detections), 296.9ms
Speed: 1.2ms preprocess, 296.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrKlK_ZiWZiu_ltUsOei6g_0.JPG: 480x640 (no detections), 295.0ms
Speed: 1.4ms preprocess, 295.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrKlK_ZiWZiu_ltUsOei6g_90.JPG: 480x640 (no detections), 293.0ms
Speed: 1.2ms preprocess, 293.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrKlK_ZiWZiu_ltUsOei6g_180.JPG: 480x640 (no detections), 292.4ms
Speed: 1.1ms preprocess, 292.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrKlK_ZiWZiu_ltUsOei6g_270.JPG: 480x640 (no detections), 307.6ms
Speed: 1.3ms preprocess, 307.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrM1V-RkvImRIGOLpLMc9A_0.JPG: 480x640 (no detections), 309.0ms
Speed: 1.0ms preprocess, 309.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrM1V-RkvImRIGOLpLMc9A_90.JPG: 480x640 (no detections), 288.0ms
Speed: 1.0ms preprocess, 288.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrM1V-RkvImRIGOLpLMc9A_180.JPG: 480x640 (no detections), 295.3ms
Speed: 1.3ms preprocess, 295.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrM1V-RkvImRIGOLpLMc9A_270.JPG: 480x640 (no detections), 297.6ms
Speed: 1.4ms preprocess, 297.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrM3zAslnIBe2-eZhHhpSw_0.JPG: 480x640 (no detections), 291.5ms
Speed: 1.5ms preprocess, 291.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrM3zAslnIBe2-eZhHhpSw_90.JPG: 480x640 (no detections), 289.0ms
Speed: 1.2ms preprocess, 289.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrM3zAslnIBe2-eZhHhpSw_180.JPG: 480x640 (no detections), 288.6ms
Speed: 1.3ms preprocess, 288.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrM3zAslnIBe2-eZhHhpSw_270.JPG: 480x640 (no detections), 291.6ms
Speed: 1.2ms preprocess, 291.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrO-HUVVMXss2KKjssiS4A_0.JPG: 480x640 (no detections), 289.9ms
Speed: 1.3ms preprocess, 289.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrO-HUVVMXss2KKjssiS4A_90.JPG: 480x640 (no detections), 290.2ms
Speed: 1.1ms preprocess, 290.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrO-HUVVMXss2KKjssiS4A_180.JPG: 480x640 (no detections), 297.8ms
Speed: 1.0ms preprocess, 297.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrO-HUVVMXss2KKjssiS4A_270.JPG: 480x640 (no detections), 297.0ms
Speed: 1.1ms preprocess, 297.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrRuGBPXYDYOTqmgYgH48A_0.JPG: 480x640 (no detections), 291.4ms
Speed: 1.1ms preprocess, 291.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrRuGBPXYDYOTqmgYgH48A_90.JPG: 480x640 (no detections), 294.4ms
Speed: 1.0ms preprocess, 294.4ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrRuGBPXYDYOTqmgYgH48A_180.JPG: 480x640 (no detections), 294.2ms
Speed: 1.1ms preprocess, 294.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrRuGBPXYDYOTqmgYgH48A_270.JPG: 480x640 (no detections), 293.3ms
Speed: 1.4ms preprocess, 293.3ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrcVi83oEuNXYl8fuPq9SA_0.JPG: 480x640 (no detections), 294.1ms
Speed: 1.0ms preprocess, 294.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrcVi83oEuNXYl8fuPq9SA_90.JPG: 480x640 (no detections), 294.0ms
Speed: 1.1ms preprocess, 294.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrcVi83oEuNXYl8fuPq9SA_180.JPG: 480x640 (no detections), 297.4ms
Speed: 1.4ms preprocess, 297.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrcVi83oEuNXYl8fuPq9SA_270.JPG: 480x640 (no detections), 296.1ms
Speed: 1.2ms preprocess, 296.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrgIKS1Cl93awkvG8BsNXw_0.JPG: 480x640 (no detections), 302.9ms
Speed: 1.1ms preprocess, 302.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrgIKS1Cl93awkvG8BsNXw_90.JPG: 480x640 (no detections), 284.2ms
Speed: 1.1ms preprocess, 284.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrgIKS1Cl93awkvG8BsNXw_180.JPG: 480x640 (no detections), 290.7ms
Speed: 1.0ms preprocess, 290.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrgIKS1Cl93awkvG8BsNXw_270.JPG: 480x640 (no detections), 296.0ms
Speed: 1.3ms preprocess, 296.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrl6ST4bRMegryiZy6N0hQ_0.JPG: 480x640 (no detections), 290.5ms
Speed: 1.1ms preprocess, 290.5ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrl6ST4bRMegryiZy6N0hQ_90.JPG: 480x640 (no detections), 294.6ms
Speed: 1.1ms preprocess, 294.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrl6ST4bRMegryiZy6N0hQ_180.JPG: 480x640 (no detections), 291.1ms
Speed: 1.1ms preprocess, 291.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrl6ST4bRMegryiZy6N0hQ_270.JPG: 480x640 (no detections), 303.0ms
Speed: 1.1ms preprocess, 303.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrlUUF89z5rvtY6o8O577g_0.JPG: 480x640 (no detections), 293.1ms
Speed: 1.3ms preprocess, 293.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrlUUF89z5rvtY6o8O577g_90.JPG: 480x640 (no detections), 295.2ms
Speed: 1.1ms preprocess, 295.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrlUUF89z5rvtY6o8O577g_180.JPG: 480x640 (no detections), 287.2ms
Speed: 1.1ms preprocess, 287.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrlUUF89z5rvtY6o8O577g_270.JPG: 480x640 (no detections), 319.9ms
Speed: 1.1ms preprocess, 319.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrmkraOoh20nkDX15wSZ2g_0.JPG: 480x640 (no detections), 295.0ms
Speed: 1.1ms preprocess, 295.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrmkraOoh20nkDX15wSZ2g_90.JPG: 480x640 (no detections), 306.1ms
Speed: 1.3ms preprocess, 306.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrmkraOoh20nkDX15wSZ2g_180.JPG: 480x640 (no detections), 303.9ms
Speed: 1.8ms preprocess, 303.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrmkraOoh20nkDX15wSZ2g_270.JPG: 480x640 (no detections), 294.3ms
Speed: 1.0ms preprocess, 294.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrpyqzP6wcfdOy2t8xu0Gw_0.JPG: 480x640 (no detections), 296.5ms
Speed: 1.1ms preprocess, 296.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrpyqzP6wcfdOy2t8xu0Gw_90.JPG: 480x640 (no detections), 295.0ms
Speed: 2.1ms preprocess, 295.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrpyqzP6wcfdOy2t8xu0Gw_180.JPG: 480x640 (no detections), 291.1ms

Speed: 1.2ms preprocess, 291.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrpyqzP6wcfdOy2t8xu0Gw_270.JPG: 480x640 (no detections), 320.0ms
Speed: 1.2ms preprocess, 320.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrsz35HRJqJuvSvO5s1_XA_0.JPG: 480x640 (no detections), 309.9ms
Speed: 1.2ms preprocess, 309.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrsz35HRJqJuvSvO5s1_XA_90.JPG: 480x640 (no detections), 304.7ms
Speed: 1.3ms preprocess, 304.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrsz35HRJqJuvSvO5s1_XA_180.JPG: 480x640 (no detections), 323.9ms
Speed: 1.1ms preprocess, 323.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrsz35HRJqJuvSvO5s1_XA_270.JPG: 480x640 (no detections), 304.4ms
Speed: 1.3ms preprocess, 304.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrtgQsoV1cLykmuo9acMRg_0.JPG: 480x640 (no detections), 313.2ms
Speed: 1.2ms preprocess, 313.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrtgQsoV1cLykmuo9acMRg_90.JPG: 480x640 (no detections), 320.1ms
Speed: 1.1ms preprocess, 320.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrtgQsoV1cLykmuo9acMRg_180.JPG: 480x640 (no detections), 309.0ms
Speed: 1.1ms preprocess, 309.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrtgQsoV1cLykmuo9acMRg_270.JPG: 480x640 (no detections), 315.1ms
Speed: 1.3ms preprocess, 315.1ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wruD7_coYaPMfKkN7JiLJw_0.JPG: 480x640 (no detections), 300.2ms
Speed: 1.4ms preprocess, 300.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wruD7_coYaPMfKkN7JiLJw_90.JPG: 480x640 (no detections), 296.4ms
Speed: 1.1ms preprocess, 296.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wruD7_coYaPMfKkN7JiLJw_180.JPG: 480x640 (no detections), 302.4ms
Speed: 1.2ms preprocess, 302.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wruD7_coYaPMfKkN7JiLJw_270.JPG: 480x640 (no detections), 294.6ms
Speed: 1.5ms preprocess, 294.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrzOSFHEo2evzTcEj09r1Q_0.JPG: 480x640 (no detections), 294.5ms
Speed: 1.4ms preprocess, 294.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrzOSFHEo2evzTcEj09r1Q_90.JPG: 480x640 (no detections), 299.6ms
Speed: 1.1ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrzOSFHEo2evzTcEj09r1Q_180.JPG: 480x640 (no detections), 296.7ms
Speed: 1.6ms preprocess, 296.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/r/wrzOSFHEo2evzTcEj09r1Q_270.JPG: 480x640 (no detections), 301.1ms
Speed: 1.2ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/ws-ndh_2z1Lvm7Co6E5x0Q_0.JPG: 480x640 (no detections), 297.6ms
Speed: 1.2ms preprocess, 297.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/ws-ndh_2z1Lvm7Co6E5x0Q_90.JPG: 480x640 (no detections), 305.2ms
Speed: 1.1ms preprocess, 305.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/ws-ndh_2z1Lvm7Co6E5x0Q_180.JPG: 480x640 (no detections), 299.7ms
Speed: 1.3ms preprocess, 299.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/ws-ndh_2z1Lvm7Co6E5x0Q_270.JPG: 480x640 (no detections), 300.5ms
Speed: 1.3ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/ws-oKYsi1l0tcj2_HB1nIA_0.JPG: 480x640 (no detections), 299.0ms
Speed: 1.3ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/ws-oKYsi1l0tcj2_HB1nIA_90.JPG: 480x640 (no detections), 294.6ms
Speed: 1.2ms preprocess, 294.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/ws-oKYsi1l0tcj2_HB1nIA_180.JPG: 480x640 (no detections), 291.4ms
Speed: 1.3ms preprocess, 291.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/ws-oKYsi1l0tcj2_HB1nIA_270.JPG: 480x640 (no detections), 297.4ms
Speed: 1.1ms preprocess, 297.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/ws4L5WoUEBy0zRMjFzN6OQ_0.JPG: 480x640 (no detections), 307.1ms
Speed: 1.2ms preprocess, 307.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/ws4L5WoUEBy0zRMjFzN6OQ_90.JPG: 480x640 (no detections), 399.9ms
Speed: 1.1ms preprocess, 399.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/ws4L5WoUEBy0zRMjFzN6OQ_180.JPG: 480x640 (no detections), 306.0ms
Speed: 1.3ms preprocess, 306.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/ws4L5WoUEBy0zRMjFzN6OQ_270.JPG: 480x640 (no detections), 304.3ms
Speed: 1.1ms preprocess, 304.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/ws6izHCejmPQ5ihNTHoU-g_0.JPG: 480x640 (no detections), 299.0ms
Speed: 1.2ms preprocess, 299.0ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/ws6izHCejmPQ5ihNTHoU-g_90.JPG: 480x640 (no detections), 300.1ms
Speed: 1.2ms preprocess, 300.1ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/ws6izHCejmPQ5ihNTHoU-g_180.JPG: 480x640 (no detections), 300.7ms
Speed: 1.7ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/ws6izHCejmPQ5ihNTHoU-g_270.JPG: 480x640 (no detections), 294.0ms
Speed: 1.2ms preprocess, 294.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/ws6re8UKrllTxMvMkc9eIg_0.JPG: 480x640 (no detections), 293.4ms
Speed: 1.2ms preprocess, 293.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/ws6re8UKrllTxMvMkc9eIg_90.JPG: 480x640 (no detections), 295.7ms
Speed: 1.2ms preprocess, 295.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/ws6re8UKrllTxMvMkc9eIg_180.JPG: 480x640 (no detections), 290.2ms
Speed: 1.5ms preprocess, 290.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/ws6re8UKrllTxMvMkc9eIg_270.JPG: 480x640 (no detections), 289.5ms
Speed: 1.1ms preprocess, 289.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/ws8riCH0MsC8JX-kvq5NWg_0.JPG: 480x640 (no detections), 290.8ms
Speed: 1.2ms preprocess, 290.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/ws8riCH0MsC8JX-kvq5NWg_90.JPG: 480x640 2 Wastes, 292.9ms
Speed: 1.1ms preprocess, 292.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/ws8riCH0MsC8JX-kvq5NWg_180.JPG: 480x640 (no detections), 292.3ms
Speed: 1.0ms preprocess, 292.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/ws8riCH0MsC8JX-kvq5NWg_270.JPG: 480x640 (no detections), 291.5ms
Speed: 1.2ms preprocess, 291.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wsBFbsMFYdpZyoBdIJA4cQ_0.JPG: 480x640 (no detections), 293.2ms
Speed: 1.2ms preprocess, 293.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wsBFbsMFYdpZyoBdIJA4cQ_90.JPG: 480x640 (no detections), 289.7ms
Speed: 1.3ms preprocess, 289.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wsBFbsMFYdpZyoBdIJA4cQ_180.JPG: 480x640 (no detections), 293.0ms
Speed: 1.3ms preprocess, 293.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wsBFbsMFYdpZyoBdIJA4cQ_270.JPG: 480x640 (no detections), 290.1ms
Speed: 1.1ms preprocess, 290.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wsDR1WmkK0kwmNvXWH77pQ_0.JPG: 480x640 (no detections), 291.5ms
Speed: 1.1ms preprocess, 291.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wsDR1WmkK0kwmNvXWH77pQ_90.JPG: 480x640 (no detections), 292.0ms
Speed: 1.1ms preprocess, 292.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wsDR1WmkK0kwmNvXWH77pQ_180.JPG: 480x640 (no detections), 293.6ms
Speed: 1.1ms preprocess, 293.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wsDR1WmkK0kwmNvXWH77pQ_270.JPG: 480x640 (no detections), 295.4ms
Speed: 1.3ms preprocess, 295.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wsFupvsnb2dBCL8xgT20hw_0.JPG: 480x640 (no detections), 292.7ms
Speed: 1.1ms preprocess, 292.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wsFupvsnb2dBCL8xgT20hw_90.JPG: 480x640 (no detections), 288.1ms
Speed: 1.3ms preprocess, 288.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wsFupvsnb2dBCL8xgT20hw_180.JPG: 480x640 (no detections), 290.2ms
Speed: 1.4ms preprocess, 290.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wsFupvsnb2dBCL8xgT20hw_270.JPG: 480x640 (no detections), 296.3ms
Speed: 1.3ms preprocess, 296.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wsKr-R_3ws1QmdywAf_7XA_0.JPG: 480x640 (no detections), 298.6ms
Speed: 1.3ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wsKr-R_3ws1QmdywAf_7XA_90.JPG: 480x640 (no detections), 302.1ms
Speed: 1.1ms preprocess, 302.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wsKr-R_3ws1QmdywAf_7XA_180.JPG: 480x640 (no detections), 288.9ms
Speed: 1.2ms preprocess, 288.9ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wsKr-R_3ws1QmdywAf_7XA_270.JPG: 480x640 (no detections), 291.5ms
Speed: 1.1ms preprocess, 291.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wsNxHjiOtUhTKNnWbHoUwA_0.JPG: 480x640 (no detections), 288.1ms
Speed: 1.2ms preprocess, 288.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wsNxHjiOtUhTKNnWbHoUwA_90.JPG: 480x640 (no detections), 289.8ms
Speed: 1.3ms preprocess, 289.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wsNxHjiOtUhTKNnWbHoUwA_180.JPG: 480x640 (no detections), 292.2ms
Speed: 1.0ms preprocess, 292.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wsNxHjiOtUhTKNnWbHoUwA_270.JPG: 480x640 (no detections), 293.2ms
Speed: 1.2ms preprocess, 293.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wsSgjxPz7qzFPocRCygymA_0.JPG: 480x640 (no detections), 289.9ms
Speed: 1.3ms preprocess, 289.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wsSgjxPz7qzFPocRCygymA_90.JPG: 480x640 (no detections), 286.9ms
Speed: 1.2ms preprocess, 286.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wsSgjxPz7qzFPocRCygymA_180.JPG: 480x640 (no detections), 285.0ms
Speed: 1.1ms preprocess, 285.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wsSgjxPz7qzFPocRCygymA_270.JPG: 480x640 (no detections), 289.0ms
Speed: 1.1ms preprocess, 289.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wsUHnoTTJQfMImR3UKuslA_0.JPG: 480x640 (no detections), 292.6ms
Speed: 1.2ms preprocess, 292.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wsUHnoTTJQfMImR3UKuslA_90.JPG: 480x640 (no detections), 293.0ms

Speed: 1.2ms preprocess, 293.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wsUHnoTTJQfMImR3UKuslA_180.JPG: 480x640 (no detections), 292.0ms
Speed: 1.0ms preprocess, 292.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wsUHnoTTJQfMImR3UKuslA_270.JPG: 480x640 (no detections), 287.4ms
Speed: 1.0ms preprocess, 287.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wsYg3pS1iwRiLHIEyy5cxw_0.JPG: 480x640 (no detections), 290.7ms
Speed: 1.1ms preprocess, 290.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wsYg3pS1iwRiLHIEyy5cxw_90.JPG: 480x640 (no detections), 291.9ms
Speed: 1.1ms preprocess, 291.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wsYg3pS1iwRiLHIEyy5cxw_180.JPG: 480x640 (no detections), 293.3ms
Speed: 1.5ms preprocess, 293.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wsYg3pS1iwRiLHIEyy5cxw_270.JPG: 480x640 (no detections), 289.7ms
Speed: 1.4ms preprocess, 289.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wsYpQti89Teeu8ED1CcRXQ_0.JPG: 480x640 (no detections), 290.9ms
Speed: 1.2ms preprocess, 290.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wsYpQti89Teeu8ED1CcRXQ_90.JPG: 480x640 (no detections), 290.7ms
Speed: 1.7ms preprocess, 290.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wsYpQti89Teeu8ED1CcRXQ_180.JPG: 480x640 (no detections), 292.1ms
Speed: 1.1ms preprocess, 292.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wsYpQti89Teeu8ED1CcRXQ_270.JPG: 480x640 (no detections), 288.8ms
Speed: 1.1ms preprocess, 288.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wsmnvZtKHIjysebfYxahhA_0.JPG: 480x640 (no detections), 284.6ms
Speed: 1.2ms preprocess, 284.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wsmnvZtKHIjysebfYxahhA_90.JPG: 480x640 (no detections), 295.4ms
Speed: 1.2ms preprocess, 295.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wsmnvZtKHIjysebfYxahhA_180.JPG: 480x640 (no detections), 289.6ms
Speed: 1.3ms preprocess, 289.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wsmnvZtKHIjysebfYxahhA_270.JPG: 480x640 (no detections), 292.8ms
Speed: 1.7ms preprocess, 292.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wsvE0qNH4xOFO1TgztlgBA_0.JPG: 480x640 (no detections), 294.9ms
Speed: 1.5ms preprocess, 294.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wsvE0qNH4xOFO1TgztlgBA_90.JPG: 480x640 (no detections), 293.0ms
Speed: 1.2ms preprocess, 293.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wsvE0qNH4xOFO1TgztlgBA_180.JPG: 480x640 (no detections), 290.1ms
Speed: 1.2ms preprocess, 290.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wsvE0qNH4xOFO1TgztlgBA_270.JPG: 480x640 (no detections), 290.5ms
Speed: 1.0ms preprocess, 290.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wswMHlNQ4tKVzMewzEC-Tw_0.JPG: 480x640 (no detections), 285.4ms
Speed: 2.0ms preprocess, 285.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wswMHlNQ4tKVzMewzEC-Tw_90.JPG: 480x640 (no detections), 292.2ms
Speed: 1.3ms preprocess, 292.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wswMHlNQ4tKVzMewzEC-Tw_180.JPG: 480x640 (no detections), 292.4ms
Speed: 1.2ms preprocess, 292.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wswMHlNQ4tKVzMewzEC-Tw_270.JPG: 480x640 (no detections), 291.6ms
Speed: 1.0ms preprocess, 291.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wsy4yAONjFlTRcm-aOJB3w_0.JPG: 480x640 (no detections), 284.2ms
Speed: 1.0ms preprocess, 284.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wsy4yAONjFlTRcm-aOJB3w_90.JPG: 480x640 (no detections), 289.5ms
Speed: 1.1ms preprocess, 289.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wsy4yAONjFlTRcm-aOJB3w_180.JPG: 480x640 (no detections), 288.0ms
Speed: 1.5ms preprocess, 288.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wsy4yAONjFlTRcm-aOJB3w_270.JPG: 480x640 (no detections), 295.2ms
Speed: 1.4ms preprocess, 295.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wsye0y-vrUukVQhswBTTyA_0.JPG: 480x640 (no detections), 287.8ms
Speed: 1.2ms preprocess, 287.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wsye0y-vrUukVQhswBTTyA_90.JPG: 480x640 (no detections), 299.8ms
Speed: 1.2ms preprocess, 299.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wsye0y-vrUukVQhswBTTyA_180.JPG: 480x640 (no detections), 285.2ms
Speed: 1.1ms preprocess, 285.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/s/wsye0y-vrUukVQhswBTTyA_270.JPG: 480x640 1 Waste, 289.4ms
Speed: 1.2ms preprocess, 289.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wt-2ebnVbYM-pyXuMMGSgg_0.JPG: 480x640 (no detections), 288.6ms
Speed: 1.2ms preprocess, 288.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wt-2ebnVbYM-pyXuMMGSgg_90.JPG: 480x640 (no detections), 285.7ms
Speed: 1.1ms preprocess, 285.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wt-2ebnVbYM-pyXuMMGSgg_180.JPG: 480x640 (no detections), 295.0ms
Speed: 1.4ms preprocess, 295.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wt-2ebnVbYM-pyXuMMGSgg_270.JPG: 480x640 (no detections), 287.7ms
Speed: 1.1ms preprocess, 287.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wt0i9fgKGv3s4nc0qv_fDg_0.JPG: 480x640 (no detections), 289.8ms
Speed: 1.2ms preprocess, 289.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wt0i9fgKGv3s4nc0qv_fDg_90.JPG: 480x640 (no detections), 294.9ms
Speed: 1.3ms preprocess, 294.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wt0i9fgKGv3s4nc0qv_fDg_180.JPG: 480x640 (no detections), 289.0ms
Speed: 1.2ms preprocess, 289.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wt0i9fgKGv3s4nc0qv_fDg_270.JPG: 480x640 (no detections), 288.3ms
Speed: 1.1ms preprocess, 288.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wt2iPZNG5Y0lkNYYrsXdIQ_0.JPG: 480x640 (no detections), 291.0ms
Speed: 1.1ms preprocess, 291.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wt2iPZNG5Y0lkNYYrsXdIQ_90.JPG: 480x640 (no detections), 287.6ms
Speed: 1.2ms preprocess, 287.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wt2iPZNG5Y0lkNYYrsXdIQ_180.JPG: 480x640 (no detections), 290.8ms
Speed: 1.2ms preprocess, 290.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wt2iPZNG5Y0lkNYYrsXdIQ_270.JPG: 480x640 (no detections), 287.8ms
Speed: 1.1ms preprocess, 287.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wt3jSIMODxvK-a6vitcLjw_0.JPG: 480x640 (no detections), 287.5ms
Speed: 1.1ms preprocess, 287.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wt3jSIMODxvK-a6vitcLjw_90.JPG: 480x640 (no detections), 292.4ms
Speed: 1.2ms preprocess, 292.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wt3jSIMODxvK-a6vitcLjw_180.JPG: 480x640 (no detections), 292.5ms
Speed: 1.2ms preprocess, 292.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wt3jSIMODxvK-a6vitcLjw_270.JPG: 480x640 (no detections), 289.4ms
Speed: 1.2ms preprocess, 289.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wt7Rtct0j3MyI-OckiUveA_0.JPG: 480x640 (no detections), 287.1ms
Speed: 1.1ms preprocess, 287.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wt7Rtct0j3MyI-OckiUveA_90.JPG: 480x640 (no detections), 291.0ms
Speed: 1.3ms preprocess, 291.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wt7Rtct0j3MyI-OckiUveA_180.JPG: 480x640 (no detections), 292.7ms
Speed: 1.2ms preprocess, 292.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wt7Rtct0j3MyI-OckiUveA_270.JPG: 480x640 (no detections), 288.0ms
Speed: 1.1ms preprocess, 288.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wt9EBfJ9D85QKpnOGhbV6A_0.JPG: 480x640 (no detections), 289.8ms
Speed: 1.1ms preprocess, 289.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wt9EBfJ9D85QKpnOGhbV6A_90.JPG: 480x640 (no detections), 294.4ms
Speed: 1.3ms preprocess, 294.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wt9EBfJ9D85QKpnOGhbV6A_180.JPG: 480x640 (no detections), 290.4ms
Speed: 1.1ms preprocess, 290.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wt9EBfJ9D85QKpnOGhbV6A_270.JPG: 480x640 (no detections), 292.1ms
Speed: 1.0ms preprocess, 292.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtChSQWtYHsiYlB6b-HyAA_0.JPG: 480x640 (no detections), 291.3ms
Speed: 1.1ms preprocess, 291.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtChSQWtYHsiYlB6b-HyAA_90.JPG: 480x640 (no detections), 299.3ms
Speed: 1.1ms preprocess, 299.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtChSQWtYHsiYlB6b-HyAA_180.JPG: 480x640 (no detections), 289.1ms
Speed: 1.2ms preprocess, 289.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtChSQWtYHsiYlB6b-HyAA_270.JPG: 480x640 (no detections), 303.1ms
Speed: 1.1ms preprocess, 303.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtDivNVFaUvIPmSu3-ui2g_0.JPG: 480x640 (no detections), 310.8ms
Speed: 1.3ms preprocess, 310.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtDivNVFaUvIPmSu3-ui2g_90.JPG: 480x640 (no detections), 303.8ms
Speed: 1.8ms preprocess, 303.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtDivNVFaUvIPmSu3-ui2g_180.JPG: 480x640 (no detections), 295.3ms
Speed: 1.1ms preprocess, 295.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtDivNVFaUvIPmSu3-ui2g_270.JPG: 480x640 (no detections), 304.7ms
Speed: 1.5ms preprocess, 304.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtGitTxbvTLjXJjoKBBRnA_0.JPG: 480x640 (no detections), 302.8ms
Speed: 1.2ms preprocess, 302.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtGitTxbvTLjXJjoKBBRnA_90.JPG: 480x640 (no detections), 300.5ms
Speed: 1.3ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtGitTxbvTLjXJjoKBBRnA_180.JPG: 480x640 (no detections), 301.2ms
Speed: 1.2ms preprocess, 301.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtGitTxbvTLjXJjoKBBRnA_270.JPG: 480x640 (no detections), 304.5ms
Speed: 1.2ms preprocess, 304.5ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtVNAEaWb-qIe3kbq1nfKg_0.JPG: 480x640 (no detections), 296.0ms

Speed: 1.2ms preprocess, 296.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtVNAEaWb-qIe3kbq1nfKg_90.JPG: 480x640 (no detections), 298.7ms
Speed: 1.2ms preprocess, 298.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtVNAEaWb-qIe3kbq1nfKg_180.JPG: 480x640 (no detections), 303.5ms
Speed: 1.2ms preprocess, 303.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtVNAEaWb-qIe3kbq1nfKg_270.JPG: 480x640 (no detections), 294.4ms
Speed: 1.1ms preprocess, 294.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtbqDVtmSQlGEFhocIBwAQ_0.JPG: 480x640 (no detections), 293.6ms
Speed: 1.6ms preprocess, 293.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtbqDVtmSQlGEFhocIBwAQ_90.JPG: 480x640 (no detections), 295.9ms
Speed: 1.2ms preprocess, 295.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtbqDVtmSQlGEFhocIBwAQ_180.JPG: 480x640 (no detections), 301.2ms
Speed: 1.3ms preprocess, 301.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtbqDVtmSQlGEFhocIBwAQ_270.JPG: 480x640 1 Waste, 300.0ms
Speed: 1.3ms preprocess, 300.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtdfIvgCJ-LC_wwTm0zpvw_0.JPG: 480x640 (no detections), 298.6ms
Speed: 1.2ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtdfIvgCJ-LC_wwTm0zpvw_90.JPG: 480x640 (no detections), 293.6ms
Speed: 1.2ms preprocess, 293.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtdfIvgCJ-LC_wwTm0zpvw_180.JPG: 480x640 (no detections), 298.2ms
Speed: 1.3ms preprocess, 298.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtdfIvgCJ-LC_wwTm0zpvw_270.JPG: 480x640 (no detections), 303.1ms
Speed: 1.2ms preprocess, 303.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtehrwf9UdTJfAFteWKxfQ_0.JPG: 480x640 (no detections), 322.0ms
Speed: 1.3ms preprocess, 322.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtehrwf9UdTJfAFteWKxfQ_90.JPG: 480x640 (no detections), 317.5ms
Speed: 1.6ms preprocess, 317.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtehrwf9UdTJfAFteWKxfQ_180.JPG: 480x640 (no detections), 343.5ms
Speed: 1.4ms preprocess, 343.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtehrwf9UdTJfAFteWKxfQ_270.JPG: 480x640 (no detections), 318.7ms
Speed: 1.2ms preprocess, 318.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtfDtZlcG20YkdkkRcLq7w_0.JPG: 480x640 (no detections), 306.3ms
Speed: 1.6ms preprocess, 306.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtfDtZlcG20YkdkkRcLq7w_90.JPG: 480x640 (no detections), 312.2ms
Speed: 1.6ms preprocess, 312.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtfDtZlcG20YkdkkRcLq7w_180.JPG: 480x640 (no detections), 448.7ms
Speed: 1.5ms preprocess, 448.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtfDtZlcG20YkdkkRcLq7w_270.JPG: 480x640 (no detections), 379.4ms
Speed: 1.8ms preprocess, 379.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtjszgkec91w309AGcAZTg_0.JPG: 480x640 (no detections), 321.1ms
Speed: 1.1ms preprocess, 321.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtjszgkec91w309AGcAZTg_90.JPG: 480x640 (no detections), 312.9ms
Speed: 1.2ms preprocess, 312.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtjszgkec91w309AGcAZTg_180.JPG: 480x640 (no detections), 301.1ms
Speed: 2.2ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtjszgkec91w309AGcAZTg_270.JPG: 480x640 1 Waste, 301.6ms
Speed: 1.2ms preprocess, 301.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtjvJyBEi8IvWYgdnCQ2ag_0.JPG: 480x640 (no detections), 295.3ms
Speed: 1.2ms preprocess, 295.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtjvJyBEi8IvWYgdnCQ2ag_90.JPG: 480x640 (no detections), 296.9ms
Speed: 1.5ms preprocess, 296.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtjvJyBEi8IvWYgdnCQ2ag_180.JPG: 480x640 (no detections), 298.4ms
Speed: 1.1ms preprocess, 298.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtjvJyBEi8IvWYgdnCQ2ag_270.JPG: 480x640 (no detections), 301.5ms
Speed: 1.1ms preprocess, 301.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtkhgvFCuzrERXOMtSA60Q_0.JPG: 480x640 (no detections), 296.8ms
Speed: 1.2ms preprocess, 296.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtkhgvFCuzrERXOMtSA60Q_90.JPG: 480x640 (no detections), 360.9ms
Speed: 1.1ms preprocess, 360.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtkhgvFCuzrERXOMtSA60Q_180.JPG: 480x640 1 Waste, 636.2ms
Speed: 1.4ms preprocess, 636.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtkhgvFCuzrERXOMtSA60Q_270.JPG: 480x640 1 Waste, 390.4ms
Speed: 1.4ms preprocess, 390.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtkhhsw4iZ-JeLTGsQrekA_0.JPG: 480x640 (no detections), 369.4ms
Speed: 1.1ms preprocess, 369.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtkhhsw4iZ-JeLTGsQrekA_90.JPG: 480x640 (no detections), 358.5ms
Speed: 1.3ms preprocess, 358.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtkhhsw4iZ-JeLTGsQrekA_180.JPG: 480x640 (no detections), 363.6ms
Speed: 1.8ms preprocess, 363.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtkhhsw4iZ-JeLTGsQrekA_270.JPG: 480x640 (no detections), 351.2ms
Speed: 1.3ms preprocess, 351.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtlM2Txcis-dsaNIn47jiA_0.JPG: 480x640 (no detections), 356.7ms
Speed: 1.6ms preprocess, 356.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtlM2Txcis-dsaNIn47jiA_90.JPG: 480x640 (no detections), 410.4ms
Speed: 3.2ms preprocess, 410.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtlM2Txcis-dsaNIn47jiA_180.JPG: 480x640 (no detections), 568.1ms
Speed: 1.9ms preprocess, 568.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtlM2Txcis-dsaNIn47jiA_270.JPG: 480x640 (no detections), 325.6ms
Speed: 1.2ms preprocess, 325.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtmVz-n6G1jKkmT6z1koOg_0.JPG: 480x640 (no detections), 298.3ms
Speed: 1.2ms preprocess, 298.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtmVz-n6G1jKkmT6z1koOg_90.JPG: 480x640 (no detections), 416.9ms
Speed: 1.2ms preprocess, 416.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtmVz-n6G1jKkmT6z1koOg_180.JPG: 480x640 (no detections), 316.0ms
Speed: 1.2ms preprocess, 316.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtmVz-n6G1jKkmT6z1koOg_270.JPG: 480x640 (no detections), 307.4ms
Speed: 1.2ms preprocess, 307.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtqpwLwA4WADt8QfMYICEQ_0.JPG: 480x640 (no detections), 295.2ms
Speed: 1.3ms preprocess, 295.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtqpwLwA4WADt8QfMYICEQ_90.JPG: 480x640 (no detections), 295.1ms
Speed: 1.2ms preprocess, 295.1ms inference, 1.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtqpwLwA4WADt8QfMYICEQ_180.JPG: 480x640 (no detections), 294.7ms
Speed: 1.0ms preprocess, 294.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtqpwLwA4WADt8QfMYICEQ_270.JPG: 480x640 (no detections), 307.0ms
Speed: 1.3ms preprocess, 307.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtrT2KNy9bLezaWyrwcsWw_0.JPG: 480x640 (no detections), 302.6ms
Speed: 1.3ms preprocess, 302.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtrT2KNy9bLezaWyrwcsWw_90.JPG: 480x640 (no detections), 296.1ms
Speed: 1.3ms preprocess, 296.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtrT2KNy9bLezaWyrwcsWw_180.JPG: 480x640 (no detections), 309.5ms
Speed: 1.2ms preprocess, 309.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtrT2KNy9bLezaWyrwcsWw_270.JPG: 480x640 (no detections), 313.1ms
Speed: 1.2ms preprocess, 313.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wttTAlhCD8EfYHyHFlq46g_0.JPG: 480x640 (no detections), 312.6ms
Speed: 1.2ms preprocess, 312.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wttTAlhCD8EfYHyHFlq46g_90.JPG: 480x640 (no detections), 307.7ms
Speed: 1.2ms preprocess, 307.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wttTAlhCD8EfYHyHFlq46g_180.JPG: 480x640 (no detections), 414.6ms
Speed: 1.7ms preprocess, 414.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wttTAlhCD8EfYHyHFlq46g_270.JPG: 480x640 (no detections), 318.4ms
Speed: 1.3ms preprocess, 318.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtzKBSdWNFckrOLoCCp7ag_0.JPG: 480x640 (no detections), 321.8ms
Speed: 1.2ms preprocess, 321.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtzKBSdWNFckrOLoCCp7ag_90.JPG: 480x640 (no detections), 315.7ms
Speed: 1.3ms preprocess, 315.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtzKBSdWNFckrOLoCCp7ag_180.JPG: 480x640 (no detections), 300.2ms
Speed: 1.4ms preprocess, 300.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/t/wtzKBSdWNFckrOLoCCp7ag_270.JPG: 480x640 (no detections), 294.6ms
Speed: 1.1ms preprocess, 294.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wu1BUdBaFtdlCHFx0Qhw9A_0.JPG: 480x640 (no detections), 302.0ms
Speed: 1.3ms preprocess, 302.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wu1BUdBaFtdlCHFx0Qhw9A_90.JPG: 480x640 (no detections), 290.2ms
Speed: 1.1ms preprocess, 290.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wu1BUdBaFtdlCHFx0Qhw9A_180.JPG: 480x640 (no detections), 297.9ms
Speed: 1.6ms preprocess, 297.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wu1BUdBaFtdlCHFx0Qhw9A_270.JPG: 480x640 (no detections), 290.7ms
Speed: 1.3ms preprocess, 290.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wu6GwSPF9et0b7v4LNp67A_0.JPG: 480x640 (no detections), 292.8ms
Speed: 1.1ms preprocess, 292.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wu6GwSPF9et0b7v4LNp67A_90.JPG: 480x640 (no detections), 290.1ms
Speed: 1.3ms preprocess, 290.1ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wu6GwSPF9et0b7v4LNp67A_180.JPG: 480x640 (no detections), 291.1ms
Speed: 1.0ms preprocess, 291.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wu6GwSPF9et0b7v4LNp67A_270.JPG: 480x640 (no detections), 292.0ms

Speed: 1.3ms preprocess, 292.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wu7awwkXxZYvPVaKiz9B0A_0.JPG: 480x640 (no detections), 295.9ms
Speed: 1.2ms preprocess, 295.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wu7awwkXxZYvPVaKiz9B0A_90.JPG: 480x640 (no detections), 291.0ms
Speed: 1.2ms preprocess, 291.0ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wu7awwkXxZYvPVaKiz9B0A_180.JPG: 480x640 (no detections), 292.9ms
Speed: 1.2ms preprocess, 292.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wu7awwkXxZYvPVaKiz9B0A_270.JPG: 480x640 (no detections), 290.2ms
Speed: 1.0ms preprocess, 290.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wuCo_QXScIW6d5U15mDh3g_0.JPG: 480x640 (no detections), 292.0ms
Speed: 1.1ms preprocess, 292.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wuCo_QXScIW6d5U15mDh3g_90.JPG: 480x640 (no detections), 296.9ms
Speed: 1.2ms preprocess, 296.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wuCo_QXScIW6d5U15mDh3g_180.JPG: 480x640 (no detections), 295.3ms
Speed: 1.1ms preprocess, 295.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wuCo_QXScIW6d5U15mDh3g_270.JPG: 480x640 (no detections), 320.5ms
Speed: 1.1ms preprocess, 320.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wuDyCwZsVOdxEQU4b9NskQ_0.JPG: 480x640 (no detections), 289.7ms
Speed: 1.2ms preprocess, 289.7ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wuDyCwZsVOdxEQU4b9NskQ_90.JPG: 480x640 (no detections), 294.9ms
Speed: 1.2ms preprocess, 294.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wuDyCwZsVOdxEQU4b9NskQ_180.JPG: 480x640 (no detections), 296.3ms
Speed: 1.2ms preprocess, 296.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wuDyCwZsVOdxEQU4b9NskQ_270.JPG: 480x640 (no detections), 298.5ms
Speed: 1.1ms preprocess, 298.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wuGXpOoBjO2uoU6E3vcJcw_0.JPG: 480x640 (no detections), 298.6ms
Speed: 1.2ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wuGXpOoBjO2uoU6E3vcJcw_90.JPG: 480x640 (no detections), 292.8ms
Speed: 1.2ms preprocess, 292.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wuGXpOoBjO2uoU6E3vcJcw_180.JPG: 480x640 (no detections), 294.4ms
Speed: 1.1ms preprocess, 294.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wuGXpOoBjO2uoU6E3vcJcw_270.JPG: 480x640 (no detections), 294.8ms
Speed: 1.7ms preprocess, 294.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wuLGyFXmcwDGQzepHr8Z3A_0.JPG: 480x640 (no detections), 289.1ms
Speed: 1.1ms preprocess, 289.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wuLGyFXmcwDGQzepHr8Z3A_90.JPG: 480x640 (no detections), 297.0ms
Speed: 1.2ms preprocess, 297.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wuLGyFXmcwDGQzepHr8Z3A_180.JPG: 480x640 (no detections), 294.8ms
Speed: 1.2ms preprocess, 294.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wuLGyFXmcwDGQzepHr8Z3A_270.JPG: 480x640 (no detections), 292.8ms
Speed: 1.1ms preprocess, 292.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wuSbmQIHHj25f6d7PnaGHw_0.JPG: 480x640 (no detections), 295.1ms
Speed: 1.4ms preprocess, 295.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wuSbmQIHHj25f6d7PnaGHw_90.JPG: 480x640 (no detections), 294.7ms
Speed: 1.6ms preprocess, 294.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wuSbmQIHHj25f6d7PnaGHw_180.JPG: 480x640 (no detections), 296.0ms
Speed: 1.3ms preprocess, 296.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wuSbmQIHHj25f6d7PnaGHw_270.JPG: 480x640 (no detections), 294.8ms
Speed: 1.3ms preprocess, 294.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wuUJfbpdhDvQW3_7DGkrHw_0.JPG: 480x640 (no detections), 294.7ms
Speed: 1.4ms preprocess, 294.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wuUJfbpdhDvQW3_7DGkrHw_90.JPG: 480x640 (no detections), 292.2ms
Speed: 1.2ms preprocess, 292.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wuUJfbpdhDvQW3_7DGkrHw_180.JPG: 480x640 (no detections), 292.2ms
Speed: 1.1ms preprocess, 292.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wuUJfbpdhDvQW3_7DGkrHw_270.JPG: 480x640 (no detections), 292.5ms
Speed: 1.1ms preprocess, 292.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wuWYxSmPTVTNEG4f8nFdsA_0.JPG: 480x640 (no detections), 292.7ms
Speed: 1.3ms preprocess, 292.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wuWYxSmPTVTNEG4f8nFdsA_90.JPG: 480x640 (no detections), 294.1ms
Speed: 1.0ms preprocess, 294.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wuWYxSmPTVTNEG4f8nFdsA_180.JPG: 480x640 (no detections), 295.3ms
Speed: 1.1ms preprocess, 295.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wuWYxSmPTVTNEG4f8nFdsA_270.JPG: 480x640 (no detections), 294.0ms
Speed: 1.1ms preprocess, 294.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wuXJCn30xr5p1x7dMpkiMQ_0.JPG: 480x640 (no detections), 295.3ms
Speed: 1.1ms preprocess, 295.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wuXJCn30xr5p1x7dMpkiMQ_90.JPG: 480x640 (no detections), 293.4ms
Speed: 1.1ms preprocess, 293.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wuXJCn30xr5p1x7dMpkiMQ_180.JPG: 480x640 (no detections), 302.8ms
Speed: 1.2ms preprocess, 302.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wuXJCn30xr5p1x7dMpkiMQ_270.JPG: 480x640 (no detections), 294.0ms
Speed: 1.3ms preprocess, 294.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wu_coMrrLjCkdj2dwpsMTg_0.JPG: 480x640 (no detections), 294.9ms
Speed: 1.5ms preprocess, 294.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wu_coMrrLjCkdj2dwpsMTg_90.JPG: 480x640 (no detections), 293.4ms
Speed: 1.2ms preprocess, 293.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wu_coMrrLjCkdj2dwpsMTg_180.JPG: 480x640 (no detections), 292.9ms
Speed: 1.2ms preprocess, 292.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wu_coMrrLjCkdj2dwpsMTg_270.JPG: 480x640 (no detections), 297.3ms
Speed: 1.2ms preprocess, 297.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wubzaxh6FFBKp8ON34nHZA_0.JPG: 480x640 (no detections), 293.3ms
Speed: 1.3ms preprocess, 293.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wubzaxh6FFBKp8ON34nHZA_90.JPG: 480x640 (no detections), 294.5ms
Speed: 1.2ms preprocess, 294.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wubzaxh6FFBKp8ON34nHZA_180.JPG: 480x640 (no detections), 296.4ms
Speed: 1.0ms preprocess, 296.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wubzaxh6FFBKp8ON34nHZA_270.JPG: 480x640 (no detections), 293.3ms
Speed: 1.3ms preprocess, 293.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wucGQu4K8TITekUA_DfN6g_0.JPG: 480x640 (no detections), 299.1ms
Speed: 1.2ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wucGQu4K8TITekUA_DfN6g_90.JPG: 480x640 (no detections), 294.8ms
Speed: 1.1ms preprocess, 294.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wucGQu4K8TITekUA_DfN6g_180.JPG: 480x640 (no detections), 301.5ms
Speed: 1.2ms preprocess, 301.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wucGQu4K8TITekUA_DfN6g_270.JPG: 480x640 (no detections), 296.2ms
Speed: 1.5ms preprocess, 296.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wueTn2_eMFkGODe8RAk8rA_0.JPG: 480x640 (no detections), 304.8ms
Speed: 1.1ms preprocess, 304.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wueTn2_eMFkGODe8RAk8rA_90.JPG: 480x640 (no detections), 294.1ms
Speed: 1.1ms preprocess, 294.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wueTn2_eMFkGODe8RAk8rA_180.JPG: 480x640 (no detections), 296.8ms
Speed: 1.3ms preprocess, 296.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wueTn2_eMFkGODe8RAk8rA_270.JPG: 480x640 (no detections), 294.7ms
Speed: 1.3ms preprocess, 294.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wujF5KTDWNjh5UoeKhExOw_0.JPG: 480x640 (no detections), 296.1ms
Speed: 1.8ms preprocess, 296.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wujF5KTDWNjh5UoeKhExOw_90.JPG: 480x640 (no detections), 294.3ms
Speed: 1.1ms preprocess, 294.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wujF5KTDWNjh5UoeKhExOw_180.JPG: 480x640 (no detections), 296.2ms
Speed: 1.1ms preprocess, 296.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wujF5KTDWNjh5UoeKhExOw_270.JPG: 480x640 (no detections), 289.8ms
Speed: 1.3ms preprocess, 289.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wulLR7IzYq_bhUnXVUhRBg_0.JPG: 480x640 (no detections), 289.5ms
Speed: 1.5ms preprocess, 289.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wulLR7IzYq_bhUnXVUhRBg_90.JPG: 480x640 (no detections), 296.4ms
Speed: 1.5ms preprocess, 296.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wulLR7IzYq_bhUnXVUhRBg_180.JPG: 480x640 (no detections), 291.3ms
Speed: 1.2ms preprocess, 291.3ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wulLR7IzYq_bhUnXVUhRBg_270.JPG: 480x640 (no detections), 292.7ms
Speed: 1.3ms preprocess, 292.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wuq-zaYYI9m9GCHJMXBPJA_0.JPG: 480x640 (no detections), 296.9ms
Speed: 1.0ms preprocess, 296.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wuq-zaYYI9m9GCHJMXBPJA_90.JPG: 480x640 (no detections), 300.0ms
Speed: 1.2ms preprocess, 300.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wuq-zaYYI9m9GCHJMXBPJA_180.JPG: 480x640 (no detections), 294.2ms
Speed: 1.1ms preprocess, 294.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wuq-zaYYI9m9GCHJMXBPJA_270.JPG: 480x640 (no detections), 293.6ms
Speed: 1.2ms preprocess, 293.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wuqSBnc4Di5IrS0bcdZaNg_0.JPG: 480x640 (no detections), 289.3ms
Speed: 1.2ms preprocess, 289.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wuqSBnc4Di5IrS0bcdZaNg_90.JPG: 480x640 (no detections), 293.7ms
Speed: 1.1ms preprocess, 293.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wuqSBnc4Di5IrS0bcdZaNg_180.JPG: 480x640 (no detections), 297.4ms

Speed: 1.3ms preprocess, 297.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wuqSBnc4Di5IrS0bcdZaNg_270.JPG: 480x640 (no detections), 299.2ms
Speed: 1.6ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wuugDjHtwgg8CDfyDikVUg_0.JPG: 480x640 (no detections), 294.2ms
Speed: 1.2ms preprocess, 294.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wuugDjHtwgg8CDfyDikVUg_90.JPG: 480x640 (no detections), 292.3ms
Speed: 1.2ms preprocess, 292.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wuugDjHtwgg8CDfyDikVUg_180.JPG: 480x640 (no detections), 295.5ms
Speed: 1.1ms preprocess, 295.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/U/wuugDjHtwgg8CDfyDikVUg_270.JPG: 480x640 (no detections), 292.9ms
Speed: 1.2ms preprocess, 292.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wv0j5GVQJ1m3KHT0Xuv8qQ_0.JPG: 480x640 (no detections), 301.0ms
Speed: 1.4ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wv0j5GVQJ1m3KHT0Xuv8qQ_90.JPG: 480x640 (no detections), 295.4ms
Speed: 1.1ms preprocess, 295.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wv0j5GVQJ1m3KHT0Xuv8qQ_180.JPG: 480x640 1 Waste, 296.5ms
Speed: 1.0ms preprocess, 296.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wv0j5GVQJ1m3KHT0Xuv8qQ_270.JPG: 480x640 (no detections), 290.1ms
Speed: 1.3ms preprocess, 290.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wv2rS_ccpSXl2OknQv-KnA_0.JPG: 480x640 (no detections), 290.6ms
Speed: 1.1ms preprocess, 290.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wv2rS_ccpSXl2OknQv-KnA_90.JPG: 480x640 (no detections), 290.9ms
Speed: 1.2ms preprocess, 290.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wv2rS_ccpSXl2OknQv-KnA_180.JPG: 480x640 1 Waste, 298.0ms
Speed: 1.4ms preprocess, 298.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wv2rS_ccpSXl2OknQv-KnA_270.JPG: 480x640 (no detections), 294.2ms
Speed: 1.2ms preprocess, 294.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wv6LNkddcCdRjhMmN2tHkg_0.JPG: 480x640 (no detections), 288.3ms
Speed: 1.0ms preprocess, 288.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wv6LNkddcCdRjhMmN2tHkg_90.JPG: 480x640 (no detections), 287.6ms
Speed: 1.3ms preprocess, 287.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wv6LNkddcCdRjhMmN2tHkg_180.JPG: 480x640 (no detections), 290.6ms
Speed: 1.1ms preprocess, 290.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wv6LNkddcCdRjhMmN2tHkg_270.JPG: 480x640 (no detections), 289.5ms
Speed: 1.4ms preprocess, 289.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wv6UKlftwAyzLLi3qk5MWw_0.JPG: 480x640 (no detections), 287.3ms
Speed: 1.2ms preprocess, 287.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wv6UKlftwAyzLLi3qk5MWw_90.JPG: 480x640 (no detections), 295.1ms
Speed: 1.3ms preprocess, 295.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wv6UKlftwAyzLLi3qk5MWw_180.JPG: 480x640 (no detections), 296.1ms
Speed: 1.1ms preprocess, 296.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wv6UKlftwAyzLLi3qk5MWw_270.JPG: 480x640 (no detections), 296.6ms
Speed: 1.5ms preprocess, 296.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wv7Dp84fqM3dEeuOCSLTNg_0.JPG: 480x640 (no detections), 298.6ms
Speed: 1.1ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wv7Dp84fqM3dEeuOCSLTNg_90.JPG: 480x640 1 Waste, 294.4ms
Speed: 1.3ms preprocess, 294.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wv7Dp84fqM3dEeuOCSLTNg_180.JPG: 480x640 (no detections), 289.9ms
Speed: 1.6ms preprocess, 289.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wv7Dp84fqM3dEeuOCSLTNg_270.JPG: 480x640 2 Wastes, 291.8ms
Speed: 1.0ms preprocess, 291.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wv8ZFU6vOV35SxhXJ0SEiA_0.JPG: 480x640 (no detections), 295.8ms
Speed: 1.3ms preprocess, 295.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wv8ZFU6vOV35SxhXJ0SEiA_90.JPG: 480x640 (no detections), 299.5ms
Speed: 1.1ms preprocess, 299.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wv8ZFU6vOV35SxhXJ0SEiA_180.JPG: 480x640 (no detections), 292.0ms
Speed: 1.5ms preprocess, 292.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wv8ZFU6vOV35SxhXJ0SEiA_270.JPG: 480x640 (no detections), 291.1ms
Speed: 1.2ms preprocess, 291.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvB-nxqunBvr4sH1yJ6yOQ_0.JPG: 480x640 (no detections), 294.6ms
Speed: 1.5ms preprocess, 294.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvB-nxqunBvr4sH1yJ6yOQ_90.JPG: 480x640 (no detections), 295.9ms
Speed: 1.1ms preprocess, 295.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvB-nxqunBvr4sH1yJ6yOQ_180.JPG: 480x640 (no detections), 293.7ms
Speed: 2.1ms preprocess, 293.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvB-nxqunBvr4sH1yJ6yOQ_270.JPG: 480x640 (no detections), 295.0ms
Speed: 2.1ms preprocess, 295.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvCO9PGxdMGK41j5RmXFlg_0.JPG: 480x640 (no detections), 295.8ms
Speed: 1.2ms preprocess, 295.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvCO9PGxdMGK41j5RmXFlg_90.JPG: 480x640 (no detections), 296.5ms
Speed: 1.1ms preprocess, 296.5ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvCO9PGxdMGK41j5RmXFlg_180.JPG: 480x640 (no detections), 291.8ms
Speed: 1.3ms preprocess, 291.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvCO9PGxdMGK41j5RmXFlg_270.JPG: 480x640 (no detections), 294.1ms
Speed: 1.1ms preprocess, 294.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvEUG85AgEdAYe_n-xvnXw_0.JPG: 480x640 (no detections), 290.9ms
Speed: 1.2ms preprocess, 290.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvEUG85AgEdAYe_n-xvnXw_90.JPG: 480x640 (no detections), 294.5ms
Speed: 1.3ms preprocess, 294.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvEUG85AgEdAYe_n-xvnXw_180.JPG: 480x640 (no detections), 292.1ms
Speed: 1.5ms preprocess, 292.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvEUG85AgEdAYe_n-xvnXw_270.JPG: 480x640 (no detections), 292.9ms
Speed: 1.0ms preprocess, 292.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvLoqyH3LUJUkVBHAEeZ1g_0.JPG: 480x640 (no detections), 294.2ms
Speed: 1.3ms preprocess, 294.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvLoqyH3LUJUkVBHAEeZ1g_90.JPG: 480x640 (no detections), 290.7ms
Speed: 1.2ms preprocess, 290.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvLoqyH3LUJUkVBHAEeZ1g_180.JPG: 480x640 (no detections), 295.7ms
Speed: 1.2ms preprocess, 295.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvLoqyH3LUJUkVBHAEeZ1g_270.JPG: 480x640 (no detections), 294.1ms
Speed: 1.2ms preprocess, 294.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvMClV5NHpYmasJp7Q1BQw_0.JPG: 480x640 (no detections), 294.4ms
Speed: 1.1ms preprocess, 294.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvMClV5NHpYmasJp7Q1BQw_90.JPG: 480x640 (no detections), 296.5ms
Speed: 1.0ms preprocess, 296.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvMClV5NHpYmasJp7Q1BQw_180.JPG: 480x640 (no detections), 294.0ms
Speed: 1.1ms preprocess, 294.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvMClV5NHpYmasJp7Q1BQw_270.JPG: 480x640 (no detections), 297.9ms
Speed: 1.2ms preprocess, 297.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvMa5H6-LFTrvPHGN5JYow_0.JPG: 480x640 (no detections), 292.4ms
Speed: 2.1ms preprocess, 292.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvMa5H6-LFTrvPHGN5JYow_90.JPG: 480x640 (no detections), 294.9ms
Speed: 1.3ms preprocess, 294.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvMa5H6-LFTrvPHGN5JYow_180.JPG: 480x640 (no detections), 290.7ms
Speed: 1.1ms preprocess, 290.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvMa5H6-LFTrvPHGN5JYow_270.JPG: 480x640 (no detections), 294.8ms
Speed: 1.0ms preprocess, 294.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvOAIN2MLHv3qrCQnH4EuA_0.JPG: 480x640 (no detections), 292.2ms
Speed: 1.1ms preprocess, 292.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvOAIN2MLHv3qrCQnH4EuA_90.JPG: 480x640 1 Waste, 291.4ms
Speed: 1.1ms preprocess, 291.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvOAIN2MLHv3qrCQnH4EuA_180.JPG: 480x640 (no detections), 292.1ms
Speed: 1.3ms preprocess, 292.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvOAIN2MLHv3qrCQnH4EuA_270.JPG: 480x640 (no detections), 290.9ms
Speed: 1.8ms preprocess, 290.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvQ3CA9AkJitjfDD8oh20A_0.JPG: 480x640 (no detections), 295.4ms
Speed: 1.0ms preprocess, 295.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvQ3CA9AkJitjfDD8oh20A_90.JPG: 480x640 (no detections), 296.7ms
Speed: 1.3ms preprocess, 296.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvQ3CA9AkJitjfDD8oh20A_180.JPG: 480x640 (no detections), 292.1ms
Speed: 1.2ms preprocess, 292.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvQ3CA9AkJitjfDD8oh20A_270.JPG: 480x640 (no detections), 290.1ms
Speed: 1.4ms preprocess, 290.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvQEKlr7_i-uyIzOyrA_5A_0.JPG: 480x640 (no detections), 295.7ms
Speed: 1.1ms preprocess, 295.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvQEKlr7_i-uyIzOyrA_5A_90.JPG: 480x640 (no detections), 292.0ms
Speed: 1.5ms preprocess, 292.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvQEKlr7_i-uyIzOyrA_5A_180.JPG: 480x640 (no detections), 293.7ms
Speed: 1.3ms preprocess, 293.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvQEKlr7_i-uyIzOyrA_5A_270.JPG: 480x640 (no detections), 293.6ms
Speed: 1.2ms preprocess, 293.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvW2-sp0Zvf0xbkH82QOEQ_0.JPG: 480x640 (no detections), 294.1ms
Speed: 1.2ms preprocess, 294.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvW2-sp0Zvf0xbkH82QOEQ_90.JPG: 480x640 (no detections), 303.1ms

Speed: 1.2ms preprocess, 303.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvW2-sp0Zvf0xbkH82QOEQ_180.JPG: 480x640 (no detections), 295.3ms
Speed: 1.4ms preprocess, 295.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvW2-sp0Zvf0xbkH82QOEQ_270.JPG: 480x640 (no detections), 294.8ms
Speed: 1.2ms preprocess, 294.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvX0oeOTB_Ovb9kV-i9sag_0.JPG: 480x640 (no detections), 325.4ms
Speed: 1.4ms preprocess, 325.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvX0oeOTB_Ovb9kV-i9sag_90.JPG: 480x640 (no detections), 327.7ms
Speed: 1.4ms preprocess, 327.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvX0oeOTB_Ovb9kV-i9sag_180.JPG: 480x640 (no detections), 329.7ms
Speed: 1.1ms preprocess, 329.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvX0oeOTB_Ovb9kV-i9sag_270.JPG: 480x640 (no detections), 316.2ms
Speed: 1.8ms preprocess, 316.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvZqGuSXZjVRMrma9UnIDg_0.JPG: 480x640 (no detections), 315.2ms
Speed: 1.1ms preprocess, 315.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvZqGuSXZjVRMrma9UnIDg_90.JPG: 480x640 (no detections), 319.7ms
Speed: 1.3ms preprocess, 319.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvZqGuSXZjVRMrma9UnIDg_180.JPG: 480x640 (no detections), 315.0ms
Speed: 1.4ms preprocess, 315.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvZqGuSXZjVRMrma9UnIDg_270.JPG: 480x640 (no detections), 305.0ms
Speed: 1.1ms preprocess, 305.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wv_XVcG7NKev7tAkqbOeDA_0.JPG: 480x640 (no detections), 307.9ms
Speed: 1.4ms preprocess, 307.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wv_XVcG7NKev7tAkqbOeDA_90.JPG: 480x640 (no detections), 312.7ms
Speed: 1.3ms preprocess, 312.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wv_XVcG7NKev7tAkqbOeDA_180.JPG: 480x640 (no detections), 296.8ms
Speed: 1.2ms preprocess, 296.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wv_XVcG7NKev7tAkqbOeDA_270.JPG: 480x640 (no detections), 297.0ms
Speed: 1.2ms preprocess, 297.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvgVTbY5z-Wt4jfet4ZsZw_0.JPG: 480x640 (no detections), 327.0ms
Speed: 1.4ms preprocess, 327.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvgVTbY5z-Wt4jfet4ZsZw_90.JPG: 480x640 (no detections), 307.5ms
Speed: 1.2ms preprocess, 307.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvgVTbY5z-Wt4jfet4ZsZw_180.JPG: 480x640 (no detections), 293.8ms
Speed: 1.4ms preprocess, 293.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvgVTbY5z-Wt4jfet4ZsZw_270.JPG: 480x640 1 Waste, 315.8ms
Speed: 1.1ms preprocess, 315.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvhFm1LUfICq_jGu4bNaXQ_0.JPG: 480x640 (no detections), 306.0ms
Speed: 1.2ms preprocess, 306.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvhFm1LUfICq_jGu4bNaXQ_90.JPG: 480x640 (no detections), 324.8ms
Speed: 1.5ms preprocess, 324.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvhFm1LUfICq_jGu4bNaXQ_180.JPG: 480x640 (no detections), 322.7ms
Speed: 1.4ms preprocess, 322.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvhFm1LUfICq_jGu4bNaXQ_270.JPG: 480x640 (no detections), 326.9ms
Speed: 1.5ms preprocess, 326.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvj73944Bo50aKfhYD42qg_0.JPG: 480x640 (no detections), 298.9ms
Speed: 1.8ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvj73944Bo50aKfhYD42qg_90.JPG: 480x640 (no detections), 294.0ms
Speed: 1.9ms preprocess, 294.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvj73944Bo50aKfhYD42qg_180.JPG: 480x640 (no detections), 301.5ms
Speed: 1.3ms preprocess, 301.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvj73944Bo50aKfhYD42qg_270.JPG: 480x640 (no detections), 299.6ms
Speed: 1.2ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvm-kmXfMdVTuLXQvdb9JQ_0.JPG: 480x640 (no detections), 292.9ms
Speed: 1.0ms preprocess, 292.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvm-kmXfMdVTuLXQvdb9JQ_90.JPG: 480x640 (no detections), 295.5ms
Speed: 1.1ms preprocess, 295.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvm-kmXfMdVTuLXQvdb9JQ_180.JPG: 480x640 (no detections), 293.2ms
Speed: 1.2ms preprocess, 293.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvm-kmXfMdVTuLXQvdb9JQ_270.JPG: 480x640 (no detections), 292.3ms
Speed: 1.2ms preprocess, 292.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvn1kRNx6_mfLe2rk4NJsg_0.JPG: 480x640 (no detections), 295.3ms
Speed: 1.3ms preprocess, 295.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvn1kRNx6_mfLe2rk4NJsg_90.JPG: 480x640 1 Waste, 295.5ms
Speed: 1.3ms preprocess, 295.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvn1kRNx6_mfLe2rk4NJsg_180.JPG: 480x640 (no detections), 291.4ms
Speed: 1.2ms preprocess, 291.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvn1kRNx6_mfLe2rk4NJsg_270.JPG: 480x640 (no detections), 305.6ms
Speed: 1.3ms preprocess, 305.6ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvnWqU8eDi03kGQ2vpv13w_0.JPG: 480x640 (no detections), 298.2ms
Speed: 1.5ms preprocess, 298.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvnWqU8eDi03kGQ2vpv13w_90.JPG: 480x640 (no detections), 293.5ms
Speed: 1.3ms preprocess, 293.5ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvnWqU8eDi03kGQ2vpv13w_180.JPG: 480x640 (no detections), 299.6ms
Speed: 1.2ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvnWqU8eDi03kGQ2vpv13w_270.JPG: 480x640 (no detections), 302.9ms
Speed: 1.8ms preprocess, 302.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvod7MYITQOh7q0rwfHB1A_0.JPG: 480x640 (no detections), 300.3ms
Speed: 1.1ms preprocess, 300.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvod7MYITQOh7q0rwfHB1A_90.JPG: 480x640 (no detections), 320.9ms
Speed: 1.1ms preprocess, 320.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvod7MYITQOh7q0rwfHB1A_180.JPG: 480x640 (no detections), 303.7ms
Speed: 1.2ms preprocess, 303.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvod7MYITQOh7q0rwfHB1A_270.JPG: 480x640 (no detections), 299.8ms
Speed: 1.2ms preprocess, 299.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvr7QNkfPQF6RfZxdky6dg_0.JPG: 480x640 (no detections), 390.9ms
Speed: 1.2ms preprocess, 390.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvr7QNkfPQF6RfZxdky6dg_90.JPG: 480x640 (no detections), 300.6ms
Speed: 1.1ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvr7QNkfPQF6RfZxdky6dg_180.JPG: 480x640 (no detections), 303.5ms
Speed: 1.9ms preprocess, 303.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvr7QNkfPQF6RfZxdky6dg_270.JPG: 480x640 (no detections), 302.6ms
Speed: 2.0ms preprocess, 302.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvu1aLcWVJMzm40LNqgMEw_0.JPG: 480x640 (no detections), 304.5ms
Speed: 1.6ms preprocess, 304.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvu1aLcWVJMzm40LNqgMEw_90.JPG: 480x640 (no detections), 296.1ms
Speed: 1.3ms preprocess, 296.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvu1aLcWVJMzm40LNqgMEw_180.JPG: 480x640 (no detections), 299.5ms
Speed: 1.4ms preprocess, 299.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/v/wvu1aLcWVJMzm40LNqgMEw_270.JPG: 480x640 (no detections), 296.5ms
Speed: 1.2ms preprocess, 296.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/ww-XxOSIH4nDwyrvmOXBYg_0.JPG: 480x640 (no detections), 296.0ms
Speed: 1.2ms preprocess, 296.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/ww-XxOSIH4nDwyrvmOXBYg_90.JPG: 480x640 (no detections), 299.1ms
Speed: 1.1ms preprocess, 299.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/ww-XxOSIH4nDwyrvmOXBYg_180.JPG: 480x640 (no detections), 293.3ms
Speed: 1.0ms preprocess, 293.3ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/ww-XxOSIH4nDwyrvmOXBYg_270.JPG: 480x640 (no detections), 299.3ms
Speed: 1.1ms preprocess, 299.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/ww-nzJ5eDjGfGU3oXQC3SA_0.JPG: 480x640 (no detections), 291.1ms
Speed: 1.7ms preprocess, 291.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/ww-nzJ5eDjGfGU3oXQC3SA_90.JPG: 480x640 (no detections), 294.3ms
Speed: 1.1ms preprocess, 294.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/ww-nzJ5eDjGfGU3oXQC3SA_180.JPG: 480x640 (no detections), 295.5ms
Speed: 1.1ms preprocess, 295.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/ww-nzJ5eDjGfGU3oXQC3SA_270.JPG: 480x640 (no detections), 293.2ms
Speed: 1.1ms preprocess, 293.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/ww05M873WeimlCPvYE3jzQ_0.JPG: 480x640 (no detections), 297.3ms
Speed: 1.2ms preprocess, 297.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/ww05M873WeimlCPvYE3jzQ_90.JPG: 480x640 (no detections), 299.7ms
Speed: 1.3ms preprocess, 299.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/ww05M873WeimlCPvYE3jzQ_180.JPG: 480x640 (no detections), 307.7ms
Speed: 1.3ms preprocess, 307.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/ww05M873WeimlCPvYE3jzQ_270.JPG: 480x640 (no detections), 302.3ms
Speed: 1.1ms preprocess, 302.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/ww3lf4UL5NtgAoHBC1qlKw_0.JPG: 480x640 (no detections), 305.9ms
Speed: 1.3ms preprocess, 305.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/ww3lf4UL5NtgAoHBC1qlKw_90.JPG: 480x640 (no detections), 321.7ms
Speed: 1.1ms preprocess, 321.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/ww3lf4UL5NtgAoHBC1qlKw_180.JPG: 480x640 (no detections), 311.0ms
Speed: 1.1ms preprocess, 311.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/ww3lf4UL5NtgAoHBC1qlKw_270.JPG: 480x640 (no detections), 299.5ms
Speed: 1.0ms preprocess, 299.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/ww8CkF9MlidEr0d4tpGX7Q_0.JPG: 480x640 1 Waste, 304.0ms

Speed: 1.7ms preprocess, 304.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/ww8CkF9MlidEr0d4tpGX7Q_90.JPG: 480x640 (no detections), 302.5ms
Speed: 1.1ms preprocess, 302.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/ww8CkF9MlidEr0d4tpGX7Q_180.JPG: 480x640 (no detections), 299.3ms
Speed: 1.2ms preprocess, 299.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/ww8CkF9MlidEr0d4tpGX7Q_270.JPG: 480x640 (no detections), 309.4ms
Speed: 1.2ms preprocess, 309.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/ww9AQxf6sYfRY_kzKCPIEw_0.JPG: 480x640 (no detections), 298.0ms
Speed: 1.2ms preprocess, 298.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/ww9AQxf6sYfRY_kzKCPIEw_90.JPG: 480x640 (no detections), 294.6ms
Speed: 1.1ms preprocess, 294.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/ww9AQxf6sYfRY_kzKCPIEw_180.JPG: 480x640 (no detections), 299.8ms
Speed: 1.1ms preprocess, 299.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/ww9AQxf6sYfRY_kzKCPIEw_270.JPG: 480x640 (no detections), 296.2ms
Speed: 1.1ms preprocess, 296.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/ww9PpV0K55JAVJW9ThGZrw_0.JPG: 480x640 (no detections), 299.6ms
Speed: 1.2ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/ww9PpV0K55JAVJW9ThGZrw_90.JPG: 480x640 (no detections), 312.9ms
Speed: 1.2ms preprocess, 312.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/ww9PpV0K55JAVJW9ThGZrw_180.JPG: 480x640 (no detections), 305.0ms
Speed: 1.5ms preprocess, 305.0ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/ww9PpV0K55JAVJW9ThGZrw_270.JPG: 480x640 (no detections), 300.6ms
Speed: 1.3ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwAzTLWWqgdKx40HcNGc9w_0.JPG: 480x640 (no detections), 300.5ms
Speed: 1.2ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwAzTLWWqgdKx40HcNGc9w_90.JPG: 480x640 (no detections), 318.7ms
Speed: 1.1ms preprocess, 318.7ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwAzTLWWqgdKx40HcNGc9w_180.JPG: 480x640 (no detections), 346.2ms
Speed: 1.4ms preprocess, 346.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwAzTLWWqgdKx40HcNGc9w_270.JPG: 480x640 (no detections), 351.6ms
Speed: 1.9ms preprocess, 351.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwB2plffLYpky9lEY8wTdw_0.JPG: 480x640 (no detections), 353.1ms
Speed: 1.6ms preprocess, 353.1ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwB2plffLYpky9lEY8wTdw_90.JPG: 480x640 1 Waste, 299.7ms
Speed: 1.2ms preprocess, 299.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwB2plffLYpky9lEY8wTdw_180.JPG: 480x640 (no detections), 304.5ms
Speed: 1.3ms preprocess, 304.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwB2plffLYpky9lEY8wTdw_270.JPG: 480x640 (no detections), 332.9ms
Speed: 1.5ms preprocess, 332.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwBF_MPgz1xpdyJ3mU-ilg_0.JPG: 480x640 (no detections), 302.1ms
Speed: 1.5ms preprocess, 302.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwBF_MPgz1xpdyJ3mU-ilg_90.JPG: 480x640 (no detections), 300.6ms
Speed: 1.1ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwBF_MPgz1xpdyJ3mU-ilg_180.JPG: 480x640 (no detections), 304.1ms
Speed: 1.1ms preprocess, 304.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwBF_MPgz1xpdyJ3mU-ilg_270.JPG: 480x640 (no detections), 300.6ms
Speed: 1.4ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwBOPywFv-BMhrflmIB6Yg_0.JPG: 480x640 1 Waste, 361.7ms
Speed: 1.7ms preprocess, 361.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwBOPywFv-BMhrflmIB6Yg_90.JPG: 480x640 1 Waste, 319.5ms
Speed: 1.6ms preprocess, 319.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwBOPywFv-BMhrflmIB6Yg_180.JPG: 480x640 (no detections), 297.7ms
Speed: 1.3ms preprocess, 297.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwBOPywFv-BMhrflmIB6Yg_270.JPG: 480x640 (no detections), 298.6ms
Speed: 1.3ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwBUiXf6h3XTv3PS_8lKpw_0.JPG: 480x640 (no detections), 302.5ms
Speed: 1.2ms preprocess, 302.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwBUiXf6h3XTv3PS_8lKpw_90.JPG: 480x640 (no detections), 295.6ms
Speed: 1.7ms preprocess, 295.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwBUiXf6h3XTv3PS_8lKpw_180.JPG: 480x640 (no detections), 295.0ms
Speed: 1.3ms preprocess, 295.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwBUiXf6h3XTv3PS_8lKpw_270.JPG: 480x640 (no detections), 306.1ms
Speed: 1.1ms preprocess, 306.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwFM4hlwWi037LrFRwJOtg_0.JPG: 480x640 1 Waste, 294.7ms
Speed: 1.1ms preprocess, 294.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwFM4hlwWi037LrFRwJOtg_90.JPG: 480x640 (no detections), 305.1ms
Speed: 1.5ms preprocess, 305.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwFM4hlwWi037LrFRwJOtg_180.JPG: 480x640 (no detections), 295.6ms
Speed: 1.2ms preprocess, 295.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwFM4hlwWi037LrFRwJOtg_270.JPG: 480x640 (no detections), 295.7ms
Speed: 1.3ms preprocess, 295.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwICWc_fqpU4rq3X_VhcUg_0.JPG: 480x640 (no detections), 350.3ms
Speed: 1.0ms preprocess, 350.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwICWc_fqpU4rq3X_VhcUg_90.JPG: 480x640 (no detections), 314.6ms
Speed: 1.5ms preprocess, 314.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwICWc_fqpU4rq3X_VhcUg_180.JPG: 480x640 (no detections), 304.2ms
Speed: 1.2ms preprocess, 304.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwICWc_fqpU4rq3X_VhcUg_270.JPG: 480x640 (no detections), 298.9ms
Speed: 1.1ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwJe6MBIG63PKx3gM9uObw_0.JPG: 480x640 (no detections), 305.5ms
Speed: 1.1ms preprocess, 305.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwJe6MBIG63PKx3gM9uObw_90.JPG: 480x640 (no detections), 318.8ms
Speed: 1.1ms preprocess, 318.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwJe6MBIG63PKx3gM9uObw_180.JPG: 480x640 (no detections), 306.2ms
Speed: 1.6ms preprocess, 306.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwJe6MBIG63PKx3gM9uObw_270.JPG: 480x640 (no detections), 295.2ms
Speed: 1.3ms preprocess, 295.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwKM4InmQJy2yg5enudDdw_0.JPG: 480x640 (no detections), 305.4ms
Speed: 1.1ms preprocess, 305.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwKM4InmQJy2yg5enudDdw_90.JPG: 480x640 (no detections), 301.5ms
Speed: 1.2ms preprocess, 301.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwKM4InmQJy2yg5enudDdw_180.JPG: 480x640 (no detections), 303.4ms
Speed: 1.3ms preprocess, 303.4ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwKM4InmQJy2yg5enudDdw_270.JPG: 480x640 (no detections), 293.5ms
Speed: 1.1ms preprocess, 293.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwLF8aG12eBGbc2B6P4wwQ_0.JPG: 480x640 (no detections), 303.9ms
Speed: 1.2ms preprocess, 303.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwLF8aG12eBGbc2B6P4wwQ_90.JPG: 480x640 (no detections), 307.7ms
Speed: 1.0ms preprocess, 307.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwLF8aG12eBGbc2B6P4wwQ_180.JPG: 480x640 (no detections), 296.6ms
Speed: 1.1ms preprocess, 296.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwLF8aG12eBGbc2B6P4wwQ_270.JPG: 480x640 (no detections), 297.5ms
Speed: 1.2ms preprocess, 297.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwRmqXgyhTrJ4ruPdhh2vg_0.JPG: 480x640 (no detections), 311.0ms
Speed: 1.3ms preprocess, 311.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwRmqXgyhTrJ4ruPdhh2vg_90.JPG: 480x640 (no detections), 306.0ms
Speed: 1.2ms preprocess, 306.0ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwRmqXgyhTrJ4ruPdhh2vg_180.JPG: 480x640 (no detections), 308.6ms
Speed: 1.3ms preprocess, 308.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwRmqXgyhTrJ4ruPdhh2vg_270.JPG: 480x640 (no detections), 298.3ms
Speed: 1.3ms preprocess, 298.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwVGg7exL0m0MacihrBEmg_0.JPG: 480x640 1 Waste, 302.9ms
Speed: 1.2ms preprocess, 302.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwVGg7exL0m0MacihrBEmg_90.JPG: 480x640 (no detections), 303.9ms
Speed: 1.4ms preprocess, 303.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwVGg7exL0m0MacihrBEmg_180.JPG: 480x640 (no detections), 401.8ms
Speed: 1.1ms preprocess, 401.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwVGg7exL0m0MacihrBEmg_270.JPG: 480x640 (no detections), 306.7ms
Speed: 1.3ms preprocess, 306.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwVGlXmsh1nxM_NTjMvafA_0.JPG: 480x640 (no detections), 298.8ms
Speed: 1.1ms preprocess, 298.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwVGlXmsh1nxM_NTjMvafA_90.JPG: 480x640 2 Wastes, 301.4ms
Speed: 1.1ms preprocess, 301.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwVGlXmsh1nxM_NTjMvafA_180.JPG: 480x640 (no detections), 303.3ms
Speed: 1.8ms preprocess, 303.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwVGlXmsh1nxM_NTjMvafA_270.JPG: 480x640 (no detections), 297.9ms
Speed: 1.6ms preprocess, 297.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwVNar4AYSKArdM5jkzVfg_0.JPG: 480x640 (no detections), 297.4ms
Speed: 1.2ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwVNar4AYSKArdM5jkzVfg_90.JPG: 480x640 (no detections), 295.8ms
Speed: 1.1ms preprocess, 295.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwVNar4AYSKArdM5jkzVfg_180.JPG: 480x640 (no detections), 295.0ms
Speed: 1.1ms preprocess, 295.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwVNar4AYSKArdM5jkzVfg_270.JPG: 480x640 (no detections), 301.4ms

Speed: 1.3ms preprocess, 301.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwXWRErnxEsKJ7BvF1elAg_0.JPG: 480x640 (no detections), 297.1ms
Speed: 1.3ms preprocess, 297.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwXWRErnxEsKJ7BvF1elAg_90.JPG: 480x640 (no detections), 297.9ms
Speed: 1.2ms preprocess, 297.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwXWRErnxEsKJ7BvF1elAg_180.JPG: 480x640 (no detections), 300.1ms
Speed: 1.3ms preprocess, 300.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwXWRErnxEsKJ7BvF1elAg_270.JPG: 480x640 (no detections), 293.1ms
Speed: 1.1ms preprocess, 293.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwaXbi6GqO-_aTwQ7vtPyw_0.JPG: 480x640 (no detections), 296.1ms
Speed: 1.1ms preprocess, 296.1ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwaXbi6GqO-_aTwQ7vtPyw_90.JPG: 480x640 (no detections), 299.8ms
Speed: 1.1ms preprocess, 299.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwaXbi6GqO-_aTwQ7vtPyw_180.JPG: 480x640 (no detections), 328.0ms
Speed: 1.2ms preprocess, 328.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwaXbi6GqO-_aTwQ7vtPyw_270.JPG: 480x640 1 Waste, 304.5ms
Speed: 1.1ms preprocess, 304.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwb15Q1DHDi0dkYI6sGY1w_0.JPG: 480x640 1 Waste, 326.1ms
Speed: 1.2ms preprocess, 326.1ms inference, 1.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwb15Q1DHDi0dkYI6sGY1w_90.JPG: 480x640 (no detections), 311.3ms
Speed: 1.4ms preprocess, 311.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwb15Q1DHDi0dkYI6sGY1w_180.JPG: 480x640 (no detections), 296.2ms
Speed: 1.1ms preprocess, 296.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwb15Q1DHDi0dkYI6sGY1w_270.JPG: 480x640 1 Waste, 317.2ms
Speed: 1.1ms preprocess, 317.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwbF3Vboui_7I2AAiju6jA_0.JPG: 480x640 (no detections), 321.3ms
Speed: 1.5ms preprocess, 321.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwbF3Vboui_7I2AAiju6jA_90.JPG: 480x640 (no detections), 314.8ms
Speed: 1.1ms preprocess, 314.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwbF3Vboui_7I2AAiju6jA_180.JPG: 480x640 (no detections), 331.8ms
Speed: 1.8ms preprocess, 331.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwbF3Vboui_7I2AAiju6jA_270.JPG: 480x640 (no detections), 338.5ms
Speed: 1.4ms preprocess, 338.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwbmxvAKjViJskwqfXTkpw_0.JPG: 480x640 (no detections), 299.9ms
Speed: 1.2ms preprocess, 299.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwbmxvAKjViJskwqfXTkpw_90.JPG: 480x640 (no detections), 309.5ms
Speed: 1.2ms preprocess, 309.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwbmxvAKjViJskwqfXTkpw_180.JPG: 480x640 (no detections), 314.4ms
Speed: 1.2ms preprocess, 314.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwbmxvAKjViJskwqfXTkpw_270.JPG: 480x640 (no detections), 298.3ms
Speed: 1.3ms preprocess, 298.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwhxLoBHroAvosoac_M9-g_0.JPG: 480x640 (no detections), 305.9ms
Speed: 1.3ms preprocess, 305.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwhxLoBHroAvosoac_M9-g_90.JPG: 480x640 (no detections), 292.8ms
Speed: 1.2ms preprocess, 292.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwhxLoBHroAvosoac_M9-g_180.JPG: 480x640 (no detections), 297.3ms
Speed: 1.6ms preprocess, 297.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwhxLoBHroAvosoac_M9-g_270.JPG: 480x640 (no detections), 291.4ms
Speed: 1.5ms preprocess, 291.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwj_eeBOjcEZFLz5CLIGXA_0.JPG: 480x640 (no detections), 315.9ms
Speed: 1.1ms preprocess, 315.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwj_eeBOjcEZFLz5CLIGXA_90.JPG: 480x640 (no detections), 312.3ms
Speed: 1.2ms preprocess, 312.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwj_eeBOjcEZFLz5CLIGXA_180.JPG: 480x640 (no detections), 310.5ms
Speed: 1.5ms preprocess, 310.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwj_eeBOjcEZFLz5CLIGXA_270.JPG: 480x640 (no detections), 307.1ms
Speed: 1.1ms preprocess, 307.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwoY2-x8ufYqq8Br_CwY8w_0.JPG: 480x640 (no detections), 313.3ms
Speed: 1.1ms preprocess, 313.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwoY2-x8ufYqq8Br_CwY8w_90.JPG: 480x640 (no detections), 309.7ms
Speed: 1.2ms preprocess, 309.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwoY2-x8ufYqq8Br_CwY8w_180.JPG: 480x640 (no detections), 303.7ms
Speed: 1.4ms preprocess, 303.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwoY2-x8ufYqq8Br_CwY8w_270.JPG: 480x640 (no detections), 298.0ms
Speed: 1.6ms preprocess, 298.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwx81TKFv0G9CCkeL0xz5g_0.JPG: 480x640 (no detections), 312.5ms
Speed: 1.5ms preprocess, 312.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwx81TKFv0G9CCkeL0xz5g_90.JPG: 480x640 (no detections), 321.3ms
Speed: 1.8ms preprocess, 321.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwx81TKFv0G9CCkeL0xz5g_180.JPG: 480x640 (no detections), 310.4ms
Speed: 1.3ms preprocess, 310.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwx81TKFv0G9CCkeL0xz5g_270.JPG: 480x640 (no detections), 308.7ms
Speed: 1.5ms preprocess, 308.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwxYyAbjN_PPAjbAWA5TSg_0.JPG: 480x640 (no detections), 300.3ms
Speed: 1.1ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwxYyAbjN_PPAjbAWA5TSg_90.JPG: 480x640 (no detections), 296.9ms
Speed: 1.4ms preprocess, 296.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwxYyAbjN_PPAjbAWA5TSg_180.JPG: 480x640 (no detections), 319.7ms
Speed: 1.2ms preprocess, 319.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwxYyAbjN_PPAjbAWA5TSg_270.JPG: 480x640 (no detections), 303.9ms
Speed: 1.2ms preprocess, 303.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwyu_pnDk3no6GpfLhzdCw_0.JPG: 480x640 1 Waste, 386.9ms
Speed: 1.1ms preprocess, 386.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwyu_pnDk3no6GpfLhzdCw_90.JPG: 480x640 1 Waste, 301.3ms
Speed: 1.2ms preprocess, 301.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwyu_pnDk3no6GpfLhzdCw_180.JPG: 480x640 (no detections), 297.7ms
Speed: 1.1ms preprocess, 297.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/w/wwyu_pnDk3no6GpfLhzdCw_270.JPG: 480x640 (no detections), 302.0ms
Speed: 1.1ms preprocess, 302.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wx1u0pQRgu47k-syoKngmA_0.JPG: 480x640 (no detections), 306.7ms
Speed: 1.1ms preprocess, 306.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wx1u0pQRgu47k-syoKngmA_90.JPG: 480x640 (no detections), 304.9ms
Speed: 1.1ms preprocess, 304.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wx1u0pQRgu47k-syoKngmA_180.JPG: 480x640 (no detections), 305.7ms
Speed: 1.5ms preprocess, 305.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wx1u0pQRgu47k-syoKngmA_270.JPG: 480x640 (no detections), 301.4ms
Speed: 1.2ms preprocess, 301.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wx3_2eamkAc9NiRDa3bp-A_0.JPG: 480x640 (no detections), 297.8ms
Speed: 1.1ms preprocess, 297.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wx3_2eamkAc9NiRDa3bp-A_90.JPG: 480x640 (no detections), 299.4ms
Speed: 1.1ms preprocess, 299.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wx3_2eamkAc9NiRDa3bp-A_180.JPG: 480x640 (no detections), 306.6ms
Speed: 1.4ms preprocess, 306.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wx3_2eamkAc9NiRDa3bp-A_270.JPG: 480x640 (no detections), 301.6ms
Speed: 1.4ms preprocess, 301.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wx6E4GWJcnC44gaAn5GvpQ_0.JPG: 480x640 (no detections), 303.4ms
Speed: 2.1ms preprocess, 303.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wx6E4GWJcnC44gaAn5GvpQ_90.JPG: 480x640 (no detections), 309.8ms
Speed: 1.2ms preprocess, 309.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wx6E4GWJcnC44gaAn5GvpQ_180.JPG: 480x640 (no detections), 300.6ms
Speed: 1.3ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wx6E4GWJcnC44gaAn5GvpQ_270.JPG: 480x640 (no detections), 312.1ms
Speed: 1.2ms preprocess, 312.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wx7GZ6h4DqqZnXoBUdO-tw_0.JPG: 480x640 (no detections), 301.5ms
Speed: 1.3ms preprocess, 301.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wx7GZ6h4DqqZnXoBUdO-tw_90.JPG: 480x640 1 Waste, 302.7ms
Speed: 1.1ms preprocess, 302.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wx7GZ6h4DqqZnXoBUdO-tw_180.JPG: 480x640 (no detections), 304.0ms
Speed: 1.3ms preprocess, 304.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wx7GZ6h4DqqZnXoBUdO-tw_270.JPG: 480x640 (no detections), 305.4ms
Speed: 1.2ms preprocess, 305.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wx95Jsdfpa4bS9tvnOlGDA_0.JPG: 480x640 (no detections), 305.4ms
Speed: 1.2ms preprocess, 305.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wx95Jsdfpa4bS9tvnOlGDA_90.JPG: 480x640 (no detections), 311.3ms
Speed: 1.0ms preprocess, 311.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wx95Jsdfpa4bS9tvnOlGDA_180.JPG: 480x640 (no detections), 299.9ms
Speed: 1.2ms preprocess, 299.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wx95Jsdfpa4bS9tvnOlGDA_270.JPG: 480x640 (no detections), 304.1ms
Speed: 1.2ms preprocess, 304.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxAQd4PTN5p90yZKhaOFfA_0.JPG: 480x640 (no detections), 299.9ms
Speed: 1.5ms preprocess, 299.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxAQd4PTN5p90yZKhaOFfA_90.JPG: 480x640 (no detections), 297.0ms
Speed: 1.8ms preprocess, 297.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxAQd4PTN5p90yZKhaOFfA_180.JPG: 480x640 (no detections), 298.9ms

Speed: 1.1ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxAQd4PTN5p90yZKhaOFfA_270.JPG: 480x640 (no detections), 296.3ms
Speed: 1.2ms preprocess, 296.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxBW7TKJD-Z3Te4TnWs7Wg_0.JPG: 480x640 (no detections), 300.7ms
Speed: 1.4ms preprocess, 300.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxBW7TKJD-Z3Te4TnWs7Wg_90.JPG: 480x640 (no detections), 309.6ms
Speed: 1.0ms preprocess, 309.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxBW7TKJD-Z3Te4TnWs7Wg_180.JPG: 480x640 (no detections), 305.2ms
Speed: 1.1ms preprocess, 305.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxBW7TKJD-Z3Te4TnWs7Wg_270.JPG: 480x640 (no detections), 302.3ms
Speed: 1.2ms preprocess, 302.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxBar8ldXzb_DLpN78XKMQ_0.JPG: 480x640 (no detections), 308.5ms
Speed: 1.3ms preprocess, 308.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxBar8ldXzb_DLpN78XKMQ_90.JPG: 480x640 (no detections), 304.8ms
Speed: 1.3ms preprocess, 304.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxBar8ldXzb_DLpN78XKMQ_180.JPG: 480x640 (no detections), 300.9ms
Speed: 1.2ms preprocess, 300.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxBar8ldXzb_DLpN78XKMQ_270.JPG: 480x640 (no detections), 298.6ms
Speed: 1.2ms preprocess, 298.6ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxEe5kVgSO48I_8C9PJ0wg_0.JPG: 480x640 (no detections), 309.4ms
Speed: 1.1ms preprocess, 309.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxEe5kVgSO48I_8C9PJ0wg_90.JPG: 480x640 (no detections), 299.7ms
Speed: 1.4ms preprocess, 299.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxEe5kVgSO48I_8C9PJ0wg_180.JPG: 480x640 (no detections), 306.9ms
Speed: 1.2ms preprocess, 306.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxEe5kVgSO48I_8C9PJ0wg_270.JPG: 480x640 (no detections), 321.5ms
Speed: 1.2ms preprocess, 321.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxEqVtcFIVDPF2eEY9GlQw_0.JPG: 480x640 (no detections), 298.0ms
Speed: 1.3ms preprocess, 298.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxEqVtcFIVDPF2eEY9GlQw_90.JPG: 480x640 (no detections), 324.6ms
Speed: 2.6ms preprocess, 324.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxEqVtcFIVDPF2eEY9GlQw_180.JPG: 480x640 (no detections), 300.3ms
Speed: 1.1ms preprocess, 300.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxEqVtcFIVDPF2eEY9GlQw_270.JPG: 480x640 (no detections), 296.2ms
Speed: 1.5ms preprocess, 296.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxExAwcYciOImEG31_ENDA_0.JPG: 480x640 (no detections), 296.3ms
Speed: 1.2ms preprocess, 296.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxExAwcYciOImEG31_ENDA_90.JPG: 480x640 (no detections), 296.0ms
Speed: 1.4ms preprocess, 296.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxExAwcYciOImEG31_ENDA_180.JPG: 480x640 (no detections), 295.3ms
Speed: 1.2ms preprocess, 295.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxExAwcYciOImEG31_ENDA_270.JPG: 480x640 (no detections), 296.5ms
Speed: 1.2ms preprocess, 296.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxFMheF9sX6Lqh-9psPnPg_0.JPG: 480x640 (no detections), 294.6ms
Speed: 1.1ms preprocess, 294.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxFMheF9sX6Lqh-9psPnPg_90.JPG: 480x640 (no detections), 296.6ms
Speed: 1.1ms preprocess, 296.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxFMheF9sX6Lqh-9psPnPg_180.JPG: 480x640 (no detections), 297.9ms
Speed: 1.2ms preprocess, 297.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxFMheF9sX6Lqh-9psPnPg_270.JPG: 480x640 (no detections), 295.5ms
Speed: 1.3ms preprocess, 295.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxK043fqRwjVhQvf2yvxdg_0.JPG: 480x640 (no detections), 304.4ms
Speed: 1.1ms preprocess, 304.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxK043fqRwjVhQvf2yvxdg_90.JPG: 480x640 (no detections), 304.6ms
Speed: 2.3ms preprocess, 304.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxK043fqRwjVhQvf2yvxdg_180.JPG: 480x640 1 Waste, 298.3ms
Speed: 1.1ms preprocess, 298.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxK043fqRwjVhQvf2yvxdg_270.JPG: 480x640 (no detections), 295.3ms
Speed: 1.1ms preprocess, 295.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxOjcx_lLLUEJj_-veiFag_0.JPG: 480x640 (no detections), 299.2ms
Speed: 1.9ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxOjcx_lLLUEJj_-veiFag_90.JPG: 480x640 (no detections), 300.5ms
Speed: 1.1ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxOjcx_lLLUEJj_-veiFag_180.JPG: 480x640 (no detections), 298.6ms
Speed: 1.4ms preprocess, 298.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxOjcx_lLLUEJj_-veiFag_270.JPG: 480x640 (no detections), 301.1ms
Speed: 1.2ms preprocess, 301.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxPqswdIF0dv4SKf7uo3NQ_0.JPG: 480x640 (no detections), 301.0ms
Speed: 1.3ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxPqswdIF0dv4SKf7uo3NQ_90.JPG: 480x640 (no detections), 294.0ms
Speed: 1.2ms preprocess, 294.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxPqswdIF0dv4SKf7uo3NQ_180.JPG: 480x640 (no detections), 298.9ms
Speed: 1.1ms preprocess, 298.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxPqswdIF0dv4SKf7uo3NQ_270.JPG: 480x640 (no detections), 305.6ms
Speed: 1.1ms preprocess, 305.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxRihOAvxG7dv8sLKkijHA_0.JPG: 480x640 (no detections), 311.7ms
Speed: 1.1ms preprocess, 311.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxRihOAvxG7dv8sLKkijHA_90.JPG: 480x640 (no detections), 298.8ms
Speed: 1.2ms preprocess, 298.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxRihOAvxG7dv8sLKkijHA_180.JPG: 480x640 (no detections), 306.8ms
Speed: 1.3ms preprocess, 306.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxRihOAvxG7dv8sLKkijHA_270.JPG: 480x640 (no detections), 301.5ms
Speed: 1.5ms preprocess, 301.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxTUyvyi34iKd--hjQU5BQ_0.JPG: 480x640 (no detections), 307.0ms
Speed: 1.3ms preprocess, 307.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxTUyvyi34iKd--hjQU5BQ_90.JPG: 480x640 (no detections), 301.0ms
Speed: 1.1ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxTUyvyi34iKd--hjQU5BQ_180.JPG: 480x640 (no detections), 294.8ms
Speed: 1.4ms preprocess, 294.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxTUyvyi34iKd--hjQU5BQ_270.JPG: 480x640 (no detections), 296.4ms
Speed: 1.1ms preprocess, 296.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxUedQn9u--jJ0IoU0AF_w_0.JPG: 480x640 (no detections), 296.3ms
Speed: 1.1ms preprocess, 296.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxUedQn9u--jJ0IoU0AF_w_90.JPG: 480x640 (no detections), 298.0ms
Speed: 1.0ms preprocess, 298.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxUedQn9u--jJ0IoU0AF_w_180.JPG: 480x640 (no detections), 292.9ms
Speed: 1.0ms preprocess, 292.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxUedQn9u--jJ0IoU0AF_w_270.JPG: 480x640 (no detections), 293.1ms
Speed: 1.1ms preprocess, 293.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxX5Wdxl-RDQaFxy5vpkCQ_0.JPG: 480x640 (no detections), 295.0ms
Speed: 1.2ms preprocess, 295.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxX5Wdxl-RDQaFxy5vpkCQ_90.JPG: 480x640 (no detections), 295.6ms
Speed: 1.1ms preprocess, 295.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxX5Wdxl-RDQaFxy5vpkCQ_180.JPG: 480x640 (no detections), 293.4ms
Speed: 1.1ms preprocess, 293.4ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxX5Wdxl-RDQaFxy5vpkCQ_270.JPG: 480x640 (no detections), 296.0ms
Speed: 1.1ms preprocess, 296.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxYrxSkvEePwlVp_7ztm8A_0.JPG: 480x640 (no detections), 294.9ms
Speed: 1.2ms preprocess, 294.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxYrxSkvEePwlVp_7ztm8A_90.JPG: 480x640 (no detections), 290.3ms
Speed: 1.0ms preprocess, 290.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxYrxSkvEePwlVp_7ztm8A_180.JPG: 480x640 (no detections), 290.6ms
Speed: 1.1ms preprocess, 290.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxYrxSkvEePwlVp_7ztm8A_270.JPG: 480x640 (no detections), 294.5ms
Speed: 1.2ms preprocess, 294.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wx_QMes1Qr_PIF1teeJ02w_0.JPG: 480x640 (no detections), 291.9ms
Speed: 1.1ms preprocess, 291.9ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wx_QMes1Qr_PIF1teeJ02w_90.JPG: 480x640 (no detections), 293.7ms
Speed: 1.3ms preprocess, 293.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wx_QMes1Qr_PIF1teeJ02w_180.JPG: 480x640 (no detections), 296.2ms
Speed: 1.3ms preprocess, 296.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wx_QMes1Qr_PIF1teeJ02w_270.JPG: 480x640 (no detections), 294.7ms
Speed: 1.2ms preprocess, 294.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxbkyiYyb27RKM_LYCW37A_0.JPG: 480x640 (no detections), 291.4ms
Speed: 1.3ms preprocess, 291.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxbkyiYyb27RKM_LYCW37A_90.JPG: 480x640 (no detections), 382.2ms
Speed: 1.2ms preprocess, 382.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxbkyiYyb27RKM_LYCW37A_180.JPG: 480x640 (no detections), 297.4ms
Speed: 1.2ms preprocess, 297.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxbkyiYyb27RKM_LYCW37A_270.JPG: 480x640 (no detections), 364.3ms
Speed: 1.3ms preprocess, 364.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxcVUhef8WoqgmY-WOLqwA_0.JPG: 480x640 (no detections), 309.2ms
Speed: 1.2ms preprocess, 309.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxcVUhef8WoqgmY-WOLqwA_90.JPG: 480x640 (no detections), 297.9ms

Speed: 1.5ms preprocess, 297.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxcVUhef8WoqgmY-WOLqwA_180.JPG: 480x640 (no detections), 294.0ms
Speed: 1.2ms preprocess, 294.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxcVUhef8WoqgmY-WOLqwA_270.JPG: 480x640 (no detections), 294.5ms
Speed: 1.2ms preprocess, 294.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxeHY16Dy3uWhJCEc_RPgw_0.JPG: 480x640 (no detections), 293.3ms
Speed: 1.1ms preprocess, 293.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxeHY16Dy3uWhJCEc_RPgw_90.JPG: 480x640 (no detections), 293.7ms
Speed: 1.1ms preprocess, 293.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxeHY16Dy3uWhJCEc_RPgw_180.JPG: 480x640 (no detections), 294.5ms
Speed: 1.2ms preprocess, 294.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxeHY16Dy3uWhJCEc_RPgw_270.JPG: 480x640 (no detections), 296.7ms
Speed: 1.2ms preprocess, 296.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxhk2ERQy7VuCQYxcK-zqQ_0.JPG: 480x640 (no detections), 288.3ms
Speed: 1.2ms preprocess, 288.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxhk2ERQy7VuCQYxcK-zqQ_90.JPG: 480x640 (no detections), 295.0ms
Speed: 1.1ms preprocess, 295.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxhk2ERQy7VuCQYxcK-zqQ_180.JPG: 480x640 (no detections), 295.3ms
Speed: 1.2ms preprocess, 295.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxhk2ERQy7VuCQYxcK-zqQ_270.JPG: 480x640 (no detections), 296.6ms
Speed: 1.3ms preprocess, 296.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxoGxAj-7pS0B_Shzu6G8g_0.JPG: 480x640 (no detections), 292.2ms
Speed: 1.3ms preprocess, 292.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxoGxAj-7pS0B_Shzu6G8g_90.JPG: 480x640 (no detections), 294.8ms
Speed: 1.2ms preprocess, 294.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxoGxAj-7pS0B_Shzu6G8g_180.JPG: 480x640 (no detections), 298.0ms
Speed: 1.3ms preprocess, 298.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxoGxAj-7pS0B_Shzu6G8g_270.JPG: 480x640 (no detections), 291.1ms
Speed: 1.3ms preprocess, 291.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxqbvGV9BC0EH2xpGO5STw_0.JPG: 480x640 (no detections), 293.6ms
Speed: 1.2ms preprocess, 293.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxqbvGV9BC0EH2xpGO5STw_90.JPG: 480x640 (no detections), 296.1ms
Speed: 1.1ms preprocess, 296.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxqbvGV9BC0EH2xpGO5STw_180.JPG: 480x640 (no detections), 293.6ms
Speed: 1.6ms preprocess, 293.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxqbvGV9BC0EH2xpGO5STw_270.JPG: 480x640 (no detections), 295.5ms
Speed: 1.1ms preprocess, 295.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxtqanjSiRsBuNKQ0LVRmQ_0.JPG: 480x640 (no detections), 296.4ms
Speed: 1.3ms preprocess, 296.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxtqanjSiRsBuNKQ0LVRmQ_90.JPG: 480x640 1 Waste, 290.1ms
Speed: 1.2ms preprocess, 290.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxtqanjSiRsBuNKQ0LVRmQ_180.JPG: 480x640 (no detections), 296.8ms
Speed: 1.2ms preprocess, 296.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxtqanjSiRsBuNKQ0LVRmQ_270.JPG: 480x640 (no detections), 296.1ms
Speed: 1.3ms preprocess, 296.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxvziJV3KoE6i9fRXrHOIg_0.JPG: 480x640 (no detections), 294.2ms
Speed: 1.1ms preprocess, 294.2ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxvziJV3KoE6i9fRXrHOIg_90.JPG: 480x640 (no detections), 295.4ms
Speed: 1.8ms preprocess, 295.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxvziJV3KoE6i9fRXrHOIg_180.JPG: 480x640 1 Waste, 295.6ms
Speed: 1.3ms preprocess, 295.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxvziJV3KoE6i9fRXrHOIg_270.JPG: 480x640 (no detections), 297.4ms
Speed: 1.1ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxwl4OanN2N2WsF1w83jYw_0.JPG: 480x640 (no detections), 301.9ms
Speed: 1.1ms preprocess, 301.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxwl4OanN2N2WsF1w83jYw_90.JPG: 480x640 (no detections), 295.8ms
Speed: 1.3ms preprocess, 295.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxwl4OanN2N2WsF1w83jYw_180.JPG: 480x640 (no detections), 292.9ms
Speed: 1.2ms preprocess, 292.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxwl4OanN2N2WsF1w83jYw_270.JPG: 480x640 (no detections), 291.7ms
Speed: 1.0ms preprocess, 291.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxwsBN8iC24IDyuN3Sb-SQ_0.JPG: 480x640 (no detections), 292.7ms
Speed: 1.2ms preprocess, 292.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxwsBN8iC24IDyuN3Sb-SQ_90.JPG: 480x640 (no detections), 289.9ms
Speed: 1.2ms preprocess, 289.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxwsBN8iC24IDyuN3Sb-SQ_180.JPG: 480x640 (no detections), 317.3ms
Speed: 1.1ms preprocess, 317.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxwsBN8iC24IDyuN3Sb-SQ_270.JPG: 480x640 (no detections), 314.4ms
Speed: 1.1ms preprocess, 314.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxya3NQ9oz4Cz7e5xmIP5g_0.JPG: 480x640 (no detections), 319.6ms
Speed: 1.4ms preprocess, 319.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxya3NQ9oz4Cz7e5xmIP5g_90.JPG: 480x640 (no detections), 354.2ms
Speed: 1.4ms preprocess, 354.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxya3NQ9oz4Cz7e5xmIP5g_180.JPG: 480x640 (no detections), 326.1ms
Speed: 1.3ms preprocess, 326.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/x/wxya3NQ9oz4Cz7e5xmIP5g_270.JPG: 480x640 (no detections), 313.1ms
Speed: 1.2ms preprocess, 313.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wy11eP6XDtMNEo75pQM6iA_0.JPG: 480x640 (no detections), 316.3ms
Speed: 1.2ms preprocess, 316.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wy11eP6XDtMNEo75pQM6iA_90.JPG: 480x640 (no detections), 306.2ms
Speed: 1.3ms preprocess, 306.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wy11eP6XDtMNEo75pQM6iA_180.JPG: 480x640 (no detections), 300.6ms
Speed: 1.1ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wy11eP6XDtMNEo75pQM6iA_270.JPG: 480x640 (no detections), 338.4ms
Speed: 1.1ms preprocess, 338.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wy3oQD91pdya_Nj4ToMvAQ_0.JPG: 480x640 (no detections), 305.4ms
Speed: 1.3ms preprocess, 305.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wy3oQD91pdya_Nj4ToMvAQ_90.JPG: 480x640 (no detections), 307.5ms
Speed: 1.2ms preprocess, 307.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wy3oQD91pdya_Nj4ToMvAQ_180.JPG: 480x640 (no detections), 313.3ms
Speed: 1.8ms preprocess, 313.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wy3oQD91pdya_Nj4ToMvAQ_270.JPG: 480x640 (no detections), 308.8ms
Speed: 1.3ms preprocess, 308.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wy6XLPV9zjwEDI68DUr5UQ_0.JPG: 480x640 (no detections), 297.6ms
Speed: 1.2ms preprocess, 297.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wy6XLPV9zjwEDI68DUr5UQ_90.JPG: 480x640 (no detections), 300.6ms
Speed: 1.2ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wy6XLPV9zjwEDI68DUr5UQ_180.JPG: 480x640 (no detections), 300.5ms
Speed: 1.4ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wy6XLPV9zjwEDI68DUr5UQ_270.JPG: 480x640 (no detections), 297.4ms
Speed: 1.2ms preprocess, 297.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wy85iP9gQeByQfnhAdOp0g_0.JPG: 480x640 (no detections), 303.1ms
Speed: 1.2ms preprocess, 303.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wy85iP9gQeByQfnhAdOp0g_90.JPG: 480x640 (no detections), 305.3ms
Speed: 1.2ms preprocess, 305.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wy85iP9gQeByQfnhAdOp0g_180.JPG: 480x640 (no detections), 296.8ms
Speed: 1.2ms preprocess, 296.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wy85iP9gQeByQfnhAdOp0g_270.JPG: 480x640 (no detections), 306.0ms
Speed: 1.3ms preprocess, 306.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyAEVOrxcwOBveYjXYGcNw_0.JPG: 480x640 (no detections), 300.4ms
Speed: 1.1ms preprocess, 300.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyAEVOrxcwOBveYjXYGcNw_90.JPG: 480x640 (no detections), 299.2ms
Speed: 1.2ms preprocess, 299.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyAEVOrxcwOBveYjXYGcNw_180.JPG: 480x640 (no detections), 302.8ms
Speed: 1.3ms preprocess, 302.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyAEVOrxcwOBveYjXYGcNw_270.JPG: 480x640 (no detections), 294.7ms
Speed: 1.1ms preprocess, 294.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyAvTWavHseoyOkjAPf1_w_0.JPG: 480x640 (no detections), 307.5ms
Speed: 1.1ms preprocess, 307.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyAvTWavHseoyOkjAPf1_w_90.JPG: 480x640 (no detections), 322.8ms
Speed: 1.4ms preprocess, 322.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyAvTWavHseoyOkjAPf1_w_180.JPG: 480x640 (no detections), 309.5ms
Speed: 1.1ms preprocess, 309.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyAvTWavHseoyOkjAPf1_w_270.JPG: 480x640 (no detections), 299.3ms
Speed: 1.4ms preprocess, 299.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyB_Y1utpxlQekhiXvsVcw_0.JPG: 480x640 (no detections), 305.9ms
Speed: 1.1ms preprocess, 305.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyB_Y1utpxlQekhiXvsVcw_90.JPG: 480x640 (no detections), 299.2ms
Speed: 1.2ms preprocess, 299.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyB_Y1utpxlQekhiXvsVcw_180.JPG: 480x640 (no detections), 384.3ms
Speed: 1.1ms preprocess, 384.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyB_Y1utpxlQekhiXvsVcw_270.JPG: 480x640 (no detections), 310.8ms
Speed: 1.3ms preprocess, 310.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyDe2xG49zvaYMuK1dqqrQ_0.JPG: 480x640 (no detections), 297.8ms

Speed: 1.2ms preprocess, 297.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyDe2xG49zvaYMuK1dqqrQ_90.JPG: 480x640 (no detections), 294.0ms
Speed: 1.2ms preprocess, 294.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyDe2xG49zvaYMuK1dqqrQ_180.JPG: 480x640 (no detections), 299.3ms
Speed: 1.9ms preprocess, 299.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyDe2xG49zvaYMuK1dqqrQ_270.JPG: 480x640 (no detections), 299.9ms
Speed: 1.2ms preprocess, 299.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyFwdXkX2VVtbvDrs3FXgw_0.JPG: 480x640 1 Waste, 299.0ms
Speed: 1.8ms preprocess, 299.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyFwdXkX2VVtbvDrs3FXgw_90.JPG: 480x640 (no detections), 302.2ms
Speed: 1.2ms preprocess, 302.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyFwdXkX2VVtbvDrs3FXgw_180.JPG: 480x640 (no detections), 302.0ms
Speed: 1.1ms preprocess, 302.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyFwdXkX2VVtbvDrs3FXgw_270.JPG: 480x640 (no detections), 302.5ms
Speed: 1.2ms preprocess, 302.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyKaVKOA5eVFbNtqiczKgQ_0.JPG: 480x640 (no detections), 308.7ms
Speed: 1.4ms preprocess, 308.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyKaVKOA5eVFbNtqiczKgQ_90.JPG: 480x640 (no detections), 305.4ms
Speed: 2.1ms preprocess, 305.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyKaVKOA5eVFbNtqiczKgQ_180.JPG: 480x640 (no detections), 298.3ms
Speed: 1.1ms preprocess, 298.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyKaVKOA5eVFbNtqiczKgQ_270.JPG: 480x640 (no detections), 296.2ms
Speed: 1.1ms preprocess, 296.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyNMVfV2tfFwE0O12mwegQ_0.JPG: 480x640 (no detections), 297.5ms
Speed: 1.3ms preprocess, 297.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyNMVfV2tfFwE0O12mwegQ_90.JPG: 480x640 (no detections), 296.7ms
Speed: 1.1ms preprocess, 296.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyNMVfV2tfFwE0O12mwegQ_180.JPG: 480x640 (no detections), 297.8ms
Speed: 1.2ms preprocess, 297.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyNMVfV2tfFwE0O12mwegQ_270.JPG: 480x640 (no detections), 302.3ms
Speed: 1.3ms preprocess, 302.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyQ4cVLoqCwxVHhiNY4bOA_0.JPG: 480x640 (no detections), 305.5ms
Speed: 1.1ms preprocess, 305.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyQ4cVLoqCwxVHhiNY4bOA_90.JPG: 480x640 (no detections), 299.5ms
Speed: 1.2ms preprocess, 299.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyQ4cVLoqCwxVHhiNY4bOA_180.JPG: 480x640 (no detections), 300.0ms
Speed: 1.3ms preprocess, 300.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyQ4cVLoqCwxVHhiNY4bOA_270.JPG: 480x640 (no detections), 294.7ms
Speed: 1.1ms preprocess, 294.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyRuYYDVppDrzmhjRRVWug_0.JPG: 480x640 (no detections), 302.7ms
Speed: 1.5ms preprocess, 302.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyRuYYDVppDrzmhjRRVWug_90.JPG: 480x640 (no detections), 294.6ms
Speed: 1.2ms preprocess, 294.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyRuYYDVppDrzmhjRRVWug_180.JPG: 480x640 (no detections), 297.2ms
Speed: 1.2ms preprocess, 297.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyRuYYDVppDrzmhjRRVWug_270.JPG: 480x640 (no detections), 300.1ms
Speed: 1.1ms preprocess, 300.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wySOQyg2GoFZ-4hZbblNNQ_0.JPG: 480x640 (no detections), 303.9ms
Speed: 1.1ms preprocess, 303.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wySOQyg2GoFZ-4hZbblNNQ_90.JPG: 480x640 (no detections), 320.2ms
Speed: 1.2ms preprocess, 320.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wySOQyg2GoFZ-4hZbblNNQ_180.JPG: 480x640 (no detections), 313.7ms
Speed: 1.4ms preprocess, 313.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wySOQyg2GoFZ-4hZbblNNQ_270.JPG: 480x640 (no detections), 304.8ms
Speed: 1.3ms preprocess, 304.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyU3ZIN-Nq1DDrAllZc3aA_0.JPG: 480x640 (no detections), 312.1ms
Speed: 1.2ms preprocess, 312.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyU3ZIN-Nq1DDrAllZc3aA_90.JPG: 480x640 (no detections), 315.2ms
Speed: 1.3ms preprocess, 315.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyU3ZIN-Nq1DDrAllZc3aA_180.JPG: 480x640 (no detections), 309.6ms
Speed: 1.5ms preprocess, 309.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyU3ZIN-Nq1DDrAllZc3aA_270.JPG: 480x640 (no detections), 294.7ms
Speed: 1.2ms preprocess, 294.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyV7PUaQjzyM2SYnJ4vzIA_0.JPG: 480x640 (no detections), 300.1ms
Speed: 1.1ms preprocess, 300.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyV7PUaQjzyM2SYnJ4vzIA_90.JPG: 480x640 (no detections), 296.8ms
Speed: 1.1ms preprocess, 296.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyV7PUaQjzyM2SYnJ4vzIA_180.JPG: 480x640 (no detections), 295.7ms
Speed: 1.2ms preprocess, 295.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyV7PUaQjzyM2SYnJ4vzIA_270.JPG: 480x640 (no detections), 297.3ms
Speed: 1.1ms preprocess, 297.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyZ-3v-PE3q7vDmk1XQtEg_0.JPG: 480x640 (no detections), 298.6ms
Speed: 1.3ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyZ-3v-PE3q7vDmk1XQtEg_90.JPG: 480x640 (no detections), 302.7ms
Speed: 1.1ms preprocess, 302.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyZ-3v-PE3q7vDmk1XQtEg_180.JPG: 480x640 (no detections), 300.4ms
Speed: 1.1ms preprocess, 300.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyZ-3v-PE3q7vDmk1XQtEg_270.JPG: 480x640 (no detections), 293.4ms
Speed: 1.2ms preprocess, 293.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wybzjjjsgngIHF5c6BrTOg_0.JPG: 480x640 (no detections), 301.4ms
Speed: 1.1ms preprocess, 301.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wybzjjjsgngIHF5c6BrTOg_90.JPG: 480x640 (no detections), 298.0ms
Speed: 1.3ms preprocess, 298.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wybzjjjsgngIHF5c6BrTOg_180.JPG: 480x640 (no detections), 298.0ms
Speed: 1.3ms preprocess, 298.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wybzjjjsgngIHF5c6BrTOg_270.JPG: 480x640 (no detections), 299.6ms
Speed: 1.2ms preprocess, 299.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wygIme_223cEhJTbMNHL3Q_0.JPG: 480x640 (no detections), 295.5ms
Speed: 1.2ms preprocess, 295.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wygIme_223cEhJTbMNHL3Q_90.JPG: 480x640 (no detections), 299.1ms
Speed: 1.2ms preprocess, 299.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wygIme_223cEhJTbMNHL3Q_180.JPG: 480x640 (no detections), 300.5ms
Speed: 1.4ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wygIme_223cEhJTbMNHL3Q_270.JPG: 480x640 (no detections), 297.7ms
Speed: 1.1ms preprocess, 297.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyhehQAwxYAd4qkBDl1-4A_0.JPG: 480x640 (no detections), 299.2ms
Speed: 1.1ms preprocess, 299.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyhehQAwxYAd4qkBDl1-4A_90.JPG: 480x640 (no detections), 294.7ms
Speed: 1.2ms preprocess, 294.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyhehQAwxYAd4qkBDl1-4A_180.JPG: 480x640 (no detections), 303.5ms
Speed: 1.2ms preprocess, 303.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyhehQAwxYAd4qkBDl1-4A_270.JPG: 480x640 (no detections), 293.7ms
Speed: 1.3ms preprocess, 293.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyj2SxzlRTW_nBlE5nkLlA_0.JPG: 480x640 (no detections), 305.2ms
Speed: 1.0ms preprocess, 305.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyj2SxzlRTW_nBlE5nkLlA_90.JPG: 480x640 (no detections), 294.8ms
Speed: 1.1ms preprocess, 294.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyj2SxzlRTW_nBlE5nkLlA_180.JPG: 480x640 (no detections), 297.0ms
Speed: 1.9ms preprocess, 297.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyj2SxzlRTW_nBlE5nkLlA_270.JPG: 480x640 (no detections), 297.9ms
Speed: 1.2ms preprocess, 297.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyj6QOK06iVk_oUIZy5lLg_0.JPG: 480x640 (no detections), 302.5ms
Speed: 1.1ms preprocess, 302.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyj6QOK06iVk_oUIZy5lLg_90.JPG: 480x640 (no detections), 298.0ms
Speed: 1.3ms preprocess, 298.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyj6QOK06iVk_oUIZy5lLg_180.JPG: 480x640 (no detections), 297.3ms
Speed: 1.7ms preprocess, 297.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyj6QOK06iVk_oUIZy5lLg_270.JPG: 480x640 (no detections), 299.5ms
Speed: 1.6ms preprocess, 299.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyjqoOWSpKQ7Ypk0xLoo7Q_0.JPG: 480x640 (no detections), 309.2ms
Speed: 1.1ms preprocess, 309.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyjqoOWSpKQ7Ypk0xLoo7Q_90.JPG: 480x640 (no detections), 315.5ms
Speed: 1.1ms preprocess, 315.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyjqoOWSpKQ7Ypk0xLoo7Q_180.JPG: 480x640 1 Waste, 303.1ms
Speed: 1.3ms preprocess, 303.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyjqoOWSpKQ7Ypk0xLoo7Q_270.JPG: 480x640 (no detections), 303.2ms
Speed: 1.3ms preprocess, 303.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyjzQ3JcZf87zoRgC_41oA_0.JPG: 480x640 (no detections), 300.6ms
Speed: 1.2ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyjzQ3JcZf87zoRgC_41oA_90.JPG: 480x640 (no detections), 300.4ms
Speed: 1.1ms preprocess, 300.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyjzQ3JcZf87zoRgC_41oA_180.JPG: 480x640 (no detections), 298.9ms
Speed: 1.1ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyjzQ3JcZf87zoRgC_41oA_270.JPG: 480x640 (no detections), 296.3ms

Speed: 1.2ms preprocess, 296.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyk8rUekOeoI5uRJek2e-g_0.JPG: 480x640 (no detections), 305.2ms
Speed: 1.2ms preprocess, 305.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyk8rUekOeoI5uRJek2e-g_90.JPG: 480x640 (no detections), 299.2ms
Speed: 1.2ms preprocess, 299.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyk8rUekOeoI5uRJek2e-g_180.JPG: 480x640 (no detections), 305.2ms
Speed: 1.2ms preprocess, 305.2ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyk8rUekOeoI5uRJek2e-g_270.JPG: 480x640 (no detections), 303.5ms
Speed: 1.1ms preprocess, 303.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wymK0ud0YmTN73qIat-6EA_0.JPG: 480x640 (no detections), 302.0ms
Speed: 1.1ms preprocess, 302.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wymK0ud0YmTN73qIat-6EA_90.JPG: 480x640 (no detections), 300.3ms
Speed: 1.2ms preprocess, 300.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wymK0ud0YmTN73qIat-6EA_180.JPG: 480x640 (no detections), 300.7ms
Speed: 1.2ms preprocess, 300.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wymK0ud0YmTN73qIat-6EA_270.JPG: 480x640 (no detections), 302.4ms
Speed: 1.2ms preprocess, 302.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wys-yka79D8BoU4aYOvqkw_0.JPG: 480x640 (no detections), 301.2ms
Speed: 1.4ms preprocess, 301.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wys-yka79D8BoU4aYOvqkw_90.JPG: 480x640 (no detections), 301.9ms
Speed: 1.2ms preprocess, 301.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wys-yka79D8BoU4aYOvqkw_180.JPG: 480x640 (no detections), 296.1ms
Speed: 1.3ms preprocess, 296.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wys-yka79D8BoU4aYOvqkw_270.JPG: 480x640 (no detections), 297.5ms
Speed: 1.2ms preprocess, 297.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wys_H9-5XEMvA9E0VDUB1A_0.JPG: 480x640 (no detections), 297.6ms
Speed: 1.2ms preprocess, 297.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wys_H9-5XEMvA9E0VDUB1A_90.JPG: 480x640 (no detections), 297.5ms
Speed: 1.1ms preprocess, 297.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wys_H9-5XEMvA9E0VDUB1A_180.JPG: 480x640 (no detections), 300.2ms
Speed: 1.2ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wys_H9-5XEMvA9E0VDUB1A_270.JPG: 480x640 (no detections), 300.3ms
Speed: 1.2ms preprocess, 300.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyxW0EjLqo3EZlpVZ8O-3w_0.JPG: 480x640 (no detections), 304.0ms
Speed: 1.2ms preprocess, 304.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyxW0EjLqo3EZlpVZ8O-3w_90.JPG: 480x640 (no detections), 295.4ms
Speed: 1.1ms preprocess, 295.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyxW0EjLqo3EZlpVZ8O-3w_180.JPG: 480x640 (no detections), 297.6ms
Speed: 1.4ms preprocess, 297.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyxW0EjLqo3EZlpVZ8O-3w_270.JPG: 480x640 (no detections), 305.3ms
Speed: 1.5ms preprocess, 305.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyxfPBBw4XJcvVAUZda7Qw_0.JPG: 480x640 (no detections), 299.5ms
Speed: 1.1ms preprocess, 299.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyxfPBBw4XJcvVAUZda7Qw_90.JPG: 480x640 (no detections), 302.6ms
Speed: 1.0ms preprocess, 302.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyxfPBBw4XJcvVAUZda7Qw_180.JPG: 480x640 (no detections), 296.5ms
Speed: 1.2ms preprocess, 296.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyxfPBBw4XJcvVAUZda7Qw_270.JPG: 480x640 (no detections), 300.5ms
Speed: 1.1ms preprocess, 300.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyyR-Tyx7n5dql78sxJuLg_0.JPG: 480x640 (no detections), 302.2ms
Speed: 1.2ms preprocess, 302.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyyR-Tyx7n5dql78sxJuLg_90.JPG: 480x640 (no detections), 294.9ms
Speed: 1.1ms preprocess, 294.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyyR-Tyx7n5dql78sxJuLg_180.JPG: 480x640 (no detections), 303.0ms
Speed: 1.1ms preprocess, 303.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/y/wyyR-Tyx7n5dql78sxJuLg_270.JPG: 480x640 (no detections), 299.9ms
Speed: 1.1ms preprocess, 299.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wz-z1djQ1QjMQXW6AxugqQ_0.JPG: 480x640 (no detections), 302.9ms
Speed: 1.7ms preprocess, 302.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wz-z1djQ1QjMQXW6AxugqQ_90.JPG: 480x640 (no detections), 300.7ms
Speed: 1.3ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wz-z1djQ1QjMQXW6AxugqQ_180.JPG: 480x640 (no detections), 303.1ms
Speed: 1.0ms preprocess, 303.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wz-z1djQ1QjMQXW6AxugqQ_270.JPG: 480x640 (no detections), 296.7ms
Speed: 1.2ms preprocess, 296.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wz6kVXY8h3ZNoIH8RRVv8Q_0.JPG: 480x640 (no detections), 304.9ms
Speed: 1.1ms preprocess, 304.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wz6kVXY8h3ZNoIH8RRVv8Q_90.JPG: 480x640 (no detections), 297.8ms
Speed: 1.3ms preprocess, 297.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wz6kVXY8h3ZNoIH8RRVv8Q_180.JPG: 480x640 (no detections), 300.2ms
Speed: 1.4ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wz6kVXY8h3ZNoIH8RRVv8Q_270.JPG: 480x640 (no detections), 298.6ms
Speed: 1.2ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wz93y01F2LKm6n2ZFTeFpA_0.JPG: 480x640 (no detections), 300.4ms
Speed: 1.3ms preprocess, 300.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wz93y01F2LKm6n2ZFTeFpA_90.JPG: 480x640 (no detections), 296.9ms
Speed: 1.2ms preprocess, 296.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wz93y01F2LKm6n2ZFTeFpA_180.JPG: 480x640 (no detections), 300.1ms
Speed: 1.3ms preprocess, 300.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wz93y01F2LKm6n2ZFTeFpA_270.JPG: 480x640 (no detections), 300.1ms
Speed: 1.1ms preprocess, 300.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzARpDGYVrYF240OmaCceQ_0.JPG: 480x640 (no detections), 301.1ms
Speed: 1.2ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzARpDGYVrYF240OmaCceQ_90.JPG: 480x640 (no detections), 298.9ms
Speed: 1.2ms preprocess, 298.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzARpDGYVrYF240OmaCceQ_180.JPG: 480x640 (no detections), 300.1ms
Speed: 1.2ms preprocess, 300.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzARpDGYVrYF240OmaCceQ_270.JPG: 480x640 (no detections), 298.4ms
Speed: 1.2ms preprocess, 298.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzCoHI1mLr_5Bvt-rImnLw_0.JPG: 480x640 (no detections), 299.0ms
Speed: 1.2ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzCoHI1mLr_5Bvt-rImnLw_90.JPG: 480x640 (no detections), 293.9ms
Speed: 1.1ms preprocess, 293.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzCoHI1mLr_5Bvt-rImnLw_180.JPG: 480x640 (no detections), 303.6ms
Speed: 1.2ms preprocess, 303.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzCoHI1mLr_5Bvt-rImnLw_270.JPG: 480x640 (no detections), 303.2ms
Speed: 1.2ms preprocess, 303.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzD6O3N8QxPoT6L59acqiQ_0.JPG: 480x640 (no detections), 301.7ms
Speed: 1.9ms preprocess, 301.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzD6O3N8QxPoT6L59acqiQ_90.JPG: 480x640 (no detections), 299.3ms
Speed: 1.4ms preprocess, 299.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzD6O3N8QxPoT6L59acqiQ_180.JPG: 480x640 (no detections), 297.7ms
Speed: 1.2ms preprocess, 297.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzD6O3N8QxPoT6L59acqiQ_270.JPG: 480x640 (no detections), 301.5ms
Speed: 1.2ms preprocess, 301.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzDxEhEtBlnLZw_t2ATADA_0.JPG: 480x640 (no detections), 297.4ms
Speed: 1.2ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzDxEhEtBlnLZw_t2ATADA_90.JPG: 480x640 (no detections), 300.9ms
Speed: 1.2ms preprocess, 300.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzDxEhEtBlnLZw_t2ATADA_180.JPG: 480x640 (no detections), 299.8ms
Speed: 1.3ms preprocess, 299.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzDxEhEtBlnLZw_t2ATADA_270.JPG: 480x640 (no detections), 301.8ms
Speed: 1.4ms preprocess, 301.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzKMTgDIt49RHoe61p2Ufw_0.JPG: 480x640 (no detections), 295.8ms
Speed: 1.4ms preprocess, 295.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzKMTgDIt49RHoe61p2Ufw_90.JPG: 480x640 (no detections), 301.8ms
Speed: 1.3ms preprocess, 301.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzKMTgDIt49RHoe61p2Ufw_180.JPG: 480x640 (no detections), 298.4ms
Speed: 1.1ms preprocess, 298.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzKMTgDIt49RHoe61p2Ufw_270.JPG: 480x640 (no detections), 295.5ms
Speed: 1.2ms preprocess, 295.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzNR_4VJlgUmXvP7TYYHTQ_0.JPG: 480x640 (no detections), 308.2ms
Speed: 1.3ms preprocess, 308.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzNR_4VJlgUmXvP7TYYHTQ_90.JPG: 480x640 (no detections), 303.0ms
Speed: 1.6ms preprocess, 303.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzNR_4VJlgUmXvP7TYYHTQ_180.JPG: 480x640 (no detections), 301.2ms
Speed: 1.2ms preprocess, 301.2ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzNR_4VJlgUmXvP7TYYHTQ_270.JPG: 480x640 (no detections), 298.3ms
Speed: 1.3ms preprocess, 298.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzNolmkh912BRBJFbXyfMw_0.JPG: 480x640 (no detections), 298.1ms
Speed: 1.2ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzNolmkh912BRBJFbXyfMw_90.JPG: 480x640 (no detections), 300.7ms
Speed: 1.1ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzNolmkh912BRBJFbXyfMw_180.JPG: 480x640 (no detections), 300.2ms

Speed: 1.4ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzNolmkh912BRBJFbXyfMw_270.JPG: 480x640 (no detections), 298.3ms
Speed: 1.5ms preprocess, 298.3ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzUYtDKPKyjF4hhf6Fslvg_0.JPG: 480x640 (no detections), 300.9ms
Speed: 1.0ms preprocess, 300.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzUYtDKPKyjF4hhf6Fslvg_90.JPG: 480x640 (no detections), 301.9ms
Speed: 1.4ms preprocess, 301.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzUYtDKPKyjF4hhf6Fslvg_180.JPG: 480x640 (no detections), 301.2ms
Speed: 1.1ms preprocess, 301.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzUYtDKPKyjF4hhf6Fslvg_270.JPG: 480x640 (no detections), 297.6ms
Speed: 1.2ms preprocess, 297.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzX_63gwJRPJUwtzhug0jg_0.JPG: 480x640 (no detections), 303.2ms
Speed: 1.7ms preprocess, 303.2ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzX_63gwJRPJUwtzhug0jg_90.JPG: 480x640 (no detections), 296.3ms
Speed: 2.1ms preprocess, 296.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzX_63gwJRPJUwtzhug0jg_180.JPG: 480x640 (no detections), 300.2ms
Speed: 1.1ms preprocess, 300.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzX_63gwJRPJUwtzhug0jg_270.JPG: 480x640 (no detections), 297.2ms
Speed: 1.3ms preprocess, 297.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wz_gq9DXnQPlUlJ7GIZHjA_0.JPG: 480x640 (no detections), 293.7ms
Speed: 1.2ms preprocess, 293.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wz_gq9DXnQPlUlJ7GIZHjA_90.JPG: 480x640 (no detections), 297.8ms
Speed: 1.1ms preprocess, 297.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wz_gq9DXnQPlUlJ7GIZHjA_180.JPG: 480x640 (no detections), 295.3ms
Speed: 1.1ms preprocess, 295.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wz_gq9DXnQPlUlJ7GIZHjA_270.JPG: 480x640 (no detections), 297.5ms
Speed: 1.2ms preprocess, 297.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wz_tKr1py6dvyhSHqlzTvg_0.JPG: 480x640 (no detections), 292.2ms
Speed: 1.1ms preprocess, 292.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wz_tKr1py6dvyhSHqlzTvg_90.JPG: 480x640 (no detections), 297.0ms
Speed: 1.1ms preprocess, 297.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wz_tKr1py6dvyhSHqlzTvg_180.JPG: 480x640 (no detections), 299.6ms
Speed: 1.0ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wz_tKr1py6dvyhSHqlzTvg_270.JPG: 480x640 (no detections), 298.6ms
Speed: 1.1ms preprocess, 298.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzfNm33mIfotA2AmOAcIng_0.JPG: 480x640 (no detections), 296.3ms
Speed: 1.3ms preprocess, 296.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzfNm33mIfotA2AmOAcIng_90.JPG: 480x640 (no detections), 301.1ms
Speed: 1.1ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzfNm33mIfotA2AmOAcIng_180.JPG: 480x640 (no detections), 304.4ms
Speed: 1.1ms preprocess, 304.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzfNm33mIfotA2AmOAcIng_270.JPG: 480x640 (no detections), 304.2ms
Speed: 1.4ms preprocess, 304.2ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wziG3Ih_XuwyyHjNEBCQWw_0.JPG: 480x640 (no detections), 300.2ms
Speed: 1.5ms preprocess, 300.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wziG3Ih_XuwyyHjNEBCQWw_90.JPG: 480x640 (no detections), 297.7ms
Speed: 1.1ms preprocess, 297.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wziG3Ih_XuwyyHjNEBCQWw_180.JPG: 480x640 (no detections), 306.6ms
Speed: 1.8ms preprocess, 306.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wziG3Ih_XuwyyHjNEBCQWw_270.JPG: 480x640 (no detections), 349.0ms
Speed: 1.7ms preprocess, 349.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wziiXvE9sIl9rhg9UhNmoA_0.JPG: 480x640 (no detections), 319.2ms
Speed: 1.7ms preprocess, 319.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wziiXvE9sIl9rhg9UhNmoA_90.JPG: 480x640 (no detections), 355.5ms
Speed: 1.3ms preprocess, 355.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wziiXvE9sIl9rhg9UhNmoA_180.JPG: 480x640 (no detections), 332.2ms
Speed: 1.2ms preprocess, 332.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wziiXvE9sIl9rhg9UhNmoA_270.JPG: 480x640 (no detections), 323.3ms
Speed: 1.5ms preprocess, 323.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzikSWMn8JQnJrIieKFwkA_0.JPG: 480x640 (no detections), 340.4ms
Speed: 1.1ms preprocess, 340.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzikSWMn8JQnJrIieKFwkA_90.JPG: 480x640 (no detections), 299.1ms
Speed: 1.4ms preprocess, 299.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzikSWMn8JQnJrIieKFwkA_180.JPG: 480x640 (no detections), 298.1ms
Speed: 1.1ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzikSWMn8JQnJrIieKFwkA_270.JPG: 480x640 (no detections), 298.8ms
Speed: 1.4ms preprocess, 298.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzlrWNT2W62SlgJ9sHa16w_0.JPG: 480x640 (no detections), 305.1ms
Speed: 1.3ms preprocess, 305.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzlrWNT2W62SlgJ9sHa16w_90.JPG: 480x640 (no detections), 301.4ms
Speed: 1.7ms preprocess, 301.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzlrWNT2W62SlgJ9sHa16w_180.JPG: 480x640 (no detections), 299.8ms
Speed: 1.5ms preprocess, 299.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzlrWNT2W62SlgJ9sHa16w_270.JPG: 480x640 (no detections), 294.4ms
Speed: 1.2ms preprocess, 294.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzmC-4W-ji_Nhh2qjxeWsA_0.JPG: 480x640 (no detections), 303.0ms
Speed: 1.4ms preprocess, 303.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzmC-4W-ji_Nhh2qjxeWsA_90.JPG: 480x640 (no detections), 299.6ms
Speed: 1.2ms preprocess, 299.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzmC-4W-ji_Nhh2qjxeWsA_180.JPG: 480x640 (no detections), 301.6ms
Speed: 1.2ms preprocess, 301.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzmC-4W-ji_Nhh2qjxeWsA_270.JPG: 480x640 (no detections), 307.2ms
Speed: 1.5ms preprocess, 307.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzo_CMxmhRFz3X_iHIcbzA_0.JPG: 480x640 (no detections), 302.1ms
Speed: 1.4ms preprocess, 302.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzo_CMxmhRFz3X_iHIcbzA_90.JPG: 480x640 (no detections), 304.7ms
Speed: 1.4ms preprocess, 304.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzo_CMxmhRFz3X_iHIcbzA_180.JPG: 480x640 (no detections), 296.6ms
Speed: 1.2ms preprocess, 296.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzo_CMxmhRFz3X_iHIcbzA_270.JPG: 480x640 (no detections), 296.9ms
Speed: 1.3ms preprocess, 296.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzqcnaO3C21IuyJmhaUobg_0.JPG: 480x640 (no detections), 294.6ms
Speed: 1.3ms preprocess, 294.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzqcnaO3C21IuyJmhaUobg_90.JPG: 480x640 (no detections), 299.2ms
Speed: 1.8ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzqcnaO3C21IuyJmhaUobg_180.JPG: 480x640 (no detections), 304.2ms
Speed: 1.2ms preprocess, 304.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzqcnaO3C21IuyJmhaUobg_270.JPG: 480x640 (no detections), 301.4ms
Speed: 1.1ms preprocess, 301.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzrikf2GA632jMP_ihB3WA_0.JPG: 480x640 (no detections), 299.0ms
Speed: 1.2ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzrikf2GA632jMP_ihB3WA_90.JPG: 480x640 (no detections), 299.0ms
Speed: 1.2ms preprocess, 299.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzrikf2GA632jMP_ihB3WA_180.JPG: 480x640 (no detections), 301.1ms
Speed: 1.4ms preprocess, 301.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzrikf2GA632jMP_ihB3WA_270.JPG: 480x640 (no detections), 303.3ms
Speed: 1.3ms preprocess, 303.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzv0XfGAOZV4DLhBvg6LXQ_0.JPG: 480x640 (no detections), 301.3ms
Speed: 1.4ms preprocess, 301.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzv0XfGAOZV4DLhBvg6LXQ_90.JPG: 480x640 (no detections), 298.5ms
Speed: 1.3ms preprocess, 298.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzv0XfGAOZV4DLhBvg6LXQ_180.JPG: 480x640 (no detections), 300.8ms
Speed: 1.2ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzv0XfGAOZV4DLhBvg6LXQ_270.JPG: 480x640 (no detections), 301.1ms
Speed: 1.9ms preprocess, 301.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzvksBhttGHEiuVsfyOkOQ_0.JPG: 480x640 (no detections), 299.7ms
Speed: 1.1ms preprocess, 299.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzvksBhttGHEiuVsfyOkOQ_90.JPG: 480x640 (no detections), 300.9ms
Speed: 1.2ms preprocess, 300.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzvksBhttGHEiuVsfyOkOQ_180.JPG: 480x640 (no detections), 298.6ms
Speed: 1.1ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzvksBhttGHEiuVsfyOkOQ_270.JPG: 480x640 (no detections), 308.5ms
Speed: 1.4ms preprocess, 308.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzwtpRV50KwUVgOL0P4XBQ_0.JPG: 480x640 (no detections), 296.2ms
Speed: 1.2ms preprocess, 296.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzwtpRV50KwUVgOL0P4XBQ_90.JPG: 480x640 (no detections), 300.0ms
Speed: 1.3ms preprocess, 300.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzwtpRV50KwUVgOL0P4XBQ_180.JPG: 480x640 (no detections), 296.2ms
Speed: 1.1ms preprocess, 296.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzwtpRV50KwUVgOL0P4XBQ_270.JPG: 480x640 (no detections), 300.1ms
Speed: 1.3ms preprocess, 300.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzx2lUBKfZ_w2wXHEeDD4w_0.JPG: 480x640 (no detections), 298.7ms
Speed: 1.0ms preprocess, 298.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzx2lUBKfZ_w2wXHEeDD4w_90.JPG: 480x640 (no detections), 297.3ms

Speed: 1.3ms preprocess, 297.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzx2lUBKfZ_w2wXHEeDD4w_180.JPG: 480x640 (no detections), 297.9ms
Speed: 2.8ms preprocess, 297.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzx2lUBKfZ_w2wXHEeDD4w_270.JPG: 480x640 (no detections), 296.8ms
Speed: 1.1ms preprocess, 296.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzx4Zbe-VJXF12HNSrwumw_0.JPG: 480x640 (no detections), 301.9ms
Speed: 1.1ms preprocess, 301.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzx4Zbe-VJXF12HNSrwumw_90.JPG: 480x640 (no detections), 299.1ms
Speed: 1.3ms preprocess, 299.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzx4Zbe-VJXF12HNSrwumw_180.JPG: 480x640 (no detections), 301.7ms
Speed: 1.1ms preprocess, 301.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzx4Zbe-VJXF12HNSrwumw_270.JPG: 480x640 (no detections), 307.2ms
Speed: 1.1ms preprocess, 307.2ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzyjXMbwtrna3CeB3_Y1fQ_0.JPG: 480x640 (no detections), 304.3ms
Speed: 1.2ms preprocess, 304.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzyjXMbwtrna3CeB3_Y1fQ_90.JPG: 480x640 (no detections), 301.0ms
Speed: 1.1ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzyjXMbwtrna3CeB3_Y1fQ_180.JPG: 480x640 (no detections), 300.2ms
Speed: 1.1ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzyjXMbwtrna3CeB3_Y1fQ_270.JPG: 480x640 (no detections), 294.1ms
Speed: 1.2ms preprocess, 294.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzzc5FdIR6utHpIDufn78g_0.JPG: 480x640 (no detections), 302.4ms
Speed: 1.2ms preprocess, 302.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzzc5FdIR6utHpIDufn78g_90.JPG: 480x640 (no detections), 304.6ms
Speed: 1.5ms preprocess, 304.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzzc5FdIR6utHpIDufn78g_180.JPG: 480x640 (no detections), 297.2ms
Speed: 1.7ms preprocess, 297.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzzc5FdIR6utHpIDufn78g_270.JPG: 480x640 (no detections), 296.8ms
Speed: 1.1ms preprocess, 296.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzzczEkTqUXp9BHGByg2Kg_0.JPG: 480x640 (no detections), 297.8ms
Speed: 1.4ms preprocess, 297.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzzczEkTqUXp9BHGByg2Kg_90.JPG: 480x640 (no detections), 304.5ms
Speed: 2.0ms preprocess, 304.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzzczEkTqUXp9BHGByg2Kg_180.JPG: 480x640 (no detections), 299.1ms
Speed: 1.1ms preprocess, 299.1ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/w/Z/wzzczEkTqUXp9BHGByg2Kg_270.JPG: 480x640 (no detections), 304.0ms
Speed: 1.3ms preprocess, 304.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-40aQdGzJi6ioif333itg_0.JPG: 480x640 (no detections), 301.9ms
Speed: 1.3ms preprocess, 301.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-40aQdGzJi6ioif333itg_90.JPG: 480x640 (no detections), 304.1ms
Speed: 1.3ms preprocess, 304.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-40aQdGzJi6ioif333itg_180.JPG: 480x640 (no detections), 295.9ms
Speed: 1.2ms preprocess, 295.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-40aQdGzJi6ioif333itg_270.JPG: 480x640 (no detections), 297.2ms
Speed: 1.3ms preprocess, 297.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-5ANPZkvvwjXpC7Y49Tqg_0.JPG: 480x640 (no detections), 299.8ms
Speed: 1.4ms preprocess, 299.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-5ANPZkvvwjXpC7Y49Tqg_90.JPG: 480x640 (no detections), 295.5ms
Speed: 1.2ms preprocess, 295.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-5ANPZkvvwjXpC7Y49Tqg_180.JPG: 480x640 (no detections), 300.2ms
Speed: 1.6ms preprocess, 300.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-5ANPZkvvwjXpC7Y49Tqg_270.JPG: 480x640 (no detections), 301.5ms
Speed: 1.3ms preprocess, 301.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-5Hy4D2NNftijhRXb-55A_0.JPG: 480x640 2 Wastes, 298.9ms
Speed: 1.3ms preprocess, 298.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-5Hy4D2NNftijhRXb-55A_90.JPG: 480x640 1 Waste, 297.6ms
Speed: 1.1ms preprocess, 297.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-5Hy4D2NNftijhRXb-55A_180.JPG: 480x640 2 Wastes, 291.0ms
Speed: 1.2ms preprocess, 291.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-5Hy4D2NNftijhRXb-55A_270.JPG: 480x640 (no detections), 302.0ms
Speed: 1.1ms preprocess, 302.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-5NnFl5AQHMl-MZ1jwLPw_0.JPG: 480x640 (no detections), 297.9ms
Speed: 1.1ms preprocess, 297.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-5NnFl5AQHMl-MZ1jwLPw_90.JPG: 480x640 (no detections), 300.3ms
Speed: 1.1ms preprocess, 300.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-5NnFl5AQHMl-MZ1jwLPw_180.JPG: 480x640 (no detections), 307.2ms
Speed: 1.3ms preprocess, 307.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-5NnFl5AQHMl-MZ1jwLPw_270.JPG: 480x640 (no detections), 296.0ms
Speed: 1.0ms preprocess, 296.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-87GBiJ3nbTpIsYxc6nzg_0.JPG: 480x640 (no detections), 300.6ms
Speed: 1.1ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-87GBiJ3nbTpIsYxc6nzg_90.JPG: 480x640 (no detections), 295.9ms
Speed: 1.2ms preprocess, 295.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-87GBiJ3nbTpIsYxc6nzg_180.JPG: 480x640 (no detections), 303.9ms
Speed: 1.2ms preprocess, 303.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-87GBiJ3nbTpIsYxc6nzg_270.JPG: 480x640 (no detections), 299.1ms
Speed: 1.2ms preprocess, 299.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-AO2TTX8Nad0V2lGXE5og_0.JPG: 480x640 (no detections), 304.0ms
Speed: 1.1ms preprocess, 304.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-AO2TTX8Nad0V2lGXE5og_90.JPG: 480x640 1 Waste, 305.9ms
Speed: 1.4ms preprocess, 305.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-AO2TTX8Nad0V2lGXE5og_180.JPG: 480x640 (no detections), 299.2ms
Speed: 1.2ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-AO2TTX8Nad0V2lGXE5og_270.JPG: 480x640 1 Waste, 299.1ms
Speed: 1.1ms preprocess, 299.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-BjZbnHQ3FGL1zXqSUlSg_0.JPG: 480x640 (no detections), 300.9ms
Speed: 1.3ms preprocess, 300.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-BjZbnHQ3FGL1zXqSUlSg_90.JPG: 480x640 (no detections), 302.8ms
Speed: 1.5ms preprocess, 302.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-BjZbnHQ3FGL1zXqSUlSg_180.JPG: 480x640 (no detections), 297.5ms
Speed: 1.2ms preprocess, 297.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-BjZbnHQ3FGL1zXqSUlSg_270.JPG: 480x640 (no detections), 300.2ms
Speed: 1.2ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-Coh5rfThDCAPjIWZ47UA_0.JPG: 480x640 (no detections), 296.4ms
Speed: 1.1ms preprocess, 296.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-Coh5rfThDCAPjIWZ47UA_90.JPG: 480x640 (no detections), 299.8ms
Speed: 1.1ms preprocess, 299.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-Coh5rfThDCAPjIWZ47UA_180.JPG: 480x640 (no detections), 300.2ms
Speed: 1.4ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-Coh5rfThDCAPjIWZ47UA_270.JPG: 480x640 (no detections), 299.3ms
Speed: 1.1ms preprocess, 299.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-D8mo1X9KccsTfXRXQHig_0.JPG: 480x640 (no detections), 297.8ms
Speed: 1.4ms preprocess, 297.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-D8mo1X9KccsTfXRXQHig_90.JPG: 480x640 (no detections), 299.9ms
Speed: 1.3ms preprocess, 299.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-D8mo1X9KccsTfXRXQHig_180.JPG: 480x640 (no detections), 297.7ms
Speed: 1.3ms preprocess, 297.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-D8mo1X9KccsTfXRXQHig_270.JPG: 480x640 (no detections), 299.2ms
Speed: 1.6ms preprocess, 299.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-EyuaGu41AiMpP2eIY-3g_0.JPG: 480x640 (no detections), 306.2ms
Speed: 1.2ms preprocess, 306.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-EyuaGu41AiMpP2eIY-3g_90.JPG: 480x640 (no detections), 298.8ms
Speed: 1.3ms preprocess, 298.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-EyuaGu41AiMpP2eIY-3g_180.JPG: 480x640 (no detections), 306.3ms
Speed: 1.2ms preprocess, 306.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-EyuaGu41AiMpP2eIY-3g_270.JPG: 480x640 (no detections), 302.8ms
Speed: 1.1ms preprocess, 302.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-GDC25TIoiG--BxpHDuKw_0.JPG: 480x640 (no detections), 298.9ms
Speed: 1.2ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-GDC25TIoiG--BxpHDuKw_90.JPG: 480x640 (no detections), 293.9ms
Speed: 1.2ms preprocess, 293.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-GDC25TIoiG--BxpHDuKw_180.JPG: 480x640 (no detections), 301.6ms
Speed: 1.2ms preprocess, 301.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-GDC25TIoiG--BxpHDuKw_270.JPG: 480x640 (no detections), 308.6ms
Speed: 1.1ms preprocess, 308.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-I9sBniJRov7rL7qQpSPg_0.JPG: 480x640 (no detections), 298.2ms
Speed: 1.8ms preprocess, 298.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-I9sBniJRov7rL7qQpSPg_90.JPG: 480x640 (no detections), 298.6ms
Speed: 1.5ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-I9sBniJRov7rL7qQpSPg_180.JPG: 480x640 (no detections), 300.1ms
Speed: 1.2ms preprocess, 300.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-I9sBniJRov7rL7qQpSPg_270.JPG: 480x640 (no detections), 294.6ms
Speed: 1.1ms preprocess, 294.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-RMYPcaNw_t325DYD6jIg_0.JPG: 480x640 (no detections), 297.4ms

Speed: 1.1ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-RMYPcaNw_t325DYD6jIg_90.JPG: 480x640 (no detections), 295.7ms
Speed: 1.2ms preprocess, 295.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-RMYPcaNw_t325DYD6jIg_180.JPG: 480x640 (no detections), 297.5ms
Speed: 1.1ms preprocess, 297.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-RMYPcaNw_t325DYD6jIg_270.JPG: 480x640 (no detections), 298.5ms
Speed: 1.4ms preprocess, 298.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-RqkWMh5uq-86_mzGD_Jg_0.JPG: 480x640 (no detections), 297.4ms
Speed: 1.3ms preprocess, 297.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-RqkWMh5uq-86_mzGD_Jg_90.JPG: 480x640 (no detections), 303.7ms
Speed: 1.1ms preprocess, 303.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-RqkWMh5uq-86_mzGD_Jg_180.JPG: 480x640 (no detections), 296.4ms
Speed: 1.2ms preprocess, 296.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-RqkWMh5uq-86_mzGD_Jg_270.JPG: 480x640 (no detections), 299.0ms
Speed: 1.4ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-SKq-McK_z9H9r0HmErMQ_0.JPG: 480x640 (no detections), 297.3ms
Speed: 1.1ms preprocess, 297.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-SKq-McK_z9H9r0HmErMQ_90.JPG: 480x640 (no detections), 298.7ms
Speed: 1.2ms preprocess, 298.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-SKq-McK_z9H9r0HmErMQ_180.JPG: 480x640 (no detections), 299.6ms
Speed: 1.2ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-SKq-McK_z9H9r0HmErMQ_270.JPG: 480x640 (no detections), 301.2ms
Speed: 1.1ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-UT1lb7C8DRExyHa8dcEg_0.JPG: 480x640 (no detections), 300.2ms
Speed: 1.1ms preprocess, 300.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-UT1lb7C8DRExyHa8dcEg_90.JPG: 480x640 (no detections), 297.4ms
Speed: 1.2ms preprocess, 297.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-UT1lb7C8DRExyHa8dcEg_180.JPG: 480x640 (no detections), 300.1ms
Speed: 1.4ms preprocess, 300.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-UT1lb7C8DRExyHa8dcEg_270.JPG: 480x640 (no detections), 295.2ms
Speed: 1.3ms preprocess, 295.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-UoYT6eGeCFpvHG1TLHiw_0.JPG: 480x640 (no detections), 301.3ms
Speed: 1.2ms preprocess, 301.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-UoYT6eGeCFpvHG1TLHiw_90.JPG: 480x640 (no detections), 298.1ms
Speed: 1.2ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-UoYT6eGeCFpvHG1TLHiw_180.JPG: 480x640 (no detections), 306.0ms
Speed: 1.1ms preprocess, 306.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-UoYT6eGeCFpvHG1TLHiw_270.JPG: 480x640 (no detections), 299.7ms
Speed: 1.4ms preprocess, 299.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-WuqLf1fCJiankRs5hEtg_0.JPG: 480x640 (no detections), 304.4ms
Speed: 1.6ms preprocess, 304.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-WuqLf1fCJiankRs5hEtg_90.JPG: 480x640 (no detections), 304.1ms
Speed: 1.2ms preprocess, 304.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-WuqLf1fCJiankRs5hEtg_180.JPG: 480x640 (no detections), 302.9ms
Speed: 1.2ms preprocess, 302.9ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-WuqLf1fCJiankRs5hEtg_270.JPG: 480x640 (no detections), 296.4ms
Speed: 1.1ms preprocess, 296.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-XDe3TQt_6An7z7uw6h7w_0.JPG: 480x640 (no detections), 300.8ms
Speed: 1.0ms preprocess, 300.8ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-XDe3TQt_6An7z7uw6h7w_90.JPG: 480x640 (no detections), 302.7ms
Speed: 1.2ms preprocess, 302.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-XDe3TQt_6An7z7uw6h7w_180.JPG: 480x640 (no detections), 303.0ms
Speed: 1.1ms preprocess, 303.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-XDe3TQt_6An7z7uw6h7w_270.JPG: 480x640 (no detections), 303.8ms
Speed: 1.2ms preprocess, 303.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-_e_XleWGnZPoGaSRdatg_0.JPG: 480x640 (no detections), 295.5ms
Speed: 1.3ms preprocess, 295.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-_e_XleWGnZPoGaSRdatg_90.JPG: 480x640 (no detections), 304.1ms
Speed: 1.2ms preprocess, 304.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-_e_XleWGnZPoGaSRdatg_180.JPG: 480x640 (no detections), 307.5ms
Speed: 1.5ms preprocess, 307.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-_e_XleWGnZPoGaSRdatg_270.JPG: 480x640 (no detections), 296.5ms
Speed: 1.3ms preprocess, 296.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-bK_l9gQC6rbB63tn1b7g_0.JPG: 480x640 (no detections), 299.2ms
Speed: 1.1ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-bK_l9gQC6rbB63tn1b7g_90.JPG: 480x640 (no detections), 305.9ms
Speed: 1.3ms preprocess, 305.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-bK_l9gQC6rbB63tn1b7g_180.JPG: 480x640 (no detections), 304.7ms
Speed: 1.2ms preprocess, 304.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-bK_l9gQC6rbB63tn1b7g_270.JPG: 480x640 (no detections), 303.7ms
Speed: 1.2ms preprocess, 303.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-c4-agzl0q9VAzyS0Gy5g_0.JPG: 480x640 (no detections), 306.3ms
Speed: 1.2ms preprocess, 306.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-c4-agzl0q9VAzyS0Gy5g_90.JPG: 480x640 (no detections), 297.0ms
Speed: 1.9ms preprocess, 297.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-c4-agzl0q9VAzyS0Gy5g_180.JPG: 480x640 (no detections), 309.2ms
Speed: 1.2ms preprocess, 309.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-c4-agzl0q9VAzyS0Gy5g_270.JPG: 480x640 (no detections), 296.6ms
Speed: 1.2ms preprocess, 296.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-cWzy6u96pJzjJfIQ5Vvg_0.JPG: 480x640 (no detections), 308.2ms
Speed: 1.1ms preprocess, 308.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-cWzy6u96pJzjJfIQ5Vvg_90.JPG: 480x640 (no detections), 301.0ms
Speed: 1.4ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-cWzy6u96pJzjJfIQ5Vvg_180.JPG: 480x640 (no detections), 294.2ms
Speed: 1.1ms preprocess, 294.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-cWzy6u96pJzjJfIQ5Vvg_270.JPG: 480x640 (no detections), 299.0ms
Speed: 1.3ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-e--F8UbebIpk4jxOQksQ_0.JPG: 480x640 (no detections), 297.1ms
Speed: 1.2ms preprocess, 297.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-e--F8UbebIpk4jxOQksQ_90.JPG: 480x640 (no detections), 299.5ms
Speed: 1.1ms preprocess, 299.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-e--F8UbebIpk4jxOQksQ_180.JPG: 480x640 (no detections), 302.4ms
Speed: 1.1ms preprocess, 302.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-e--F8UbebIpk4jxOQksQ_270.JPG: 480x640 (no detections), 298.5ms
Speed: 1.1ms preprocess, 298.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-iG0mED5K8jgoqRE7Fx0g_0.JPG: 480x640 (no detections), 303.6ms
Speed: 1.4ms preprocess, 303.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-iG0mED5K8jgoqRE7Fx0g_90.JPG: 480x640 (no detections), 300.5ms
Speed: 1.9ms preprocess, 300.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-iG0mED5K8jgoqRE7Fx0g_180.JPG: 480x640 (no detections), 298.6ms
Speed: 1.3ms preprocess, 298.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-iG0mED5K8jgoqRE7Fx0g_270.JPG: 480x640 (no detections), 304.0ms
Speed: 1.2ms preprocess, 304.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-ms60Ir2D-TC_ACsbzHaQ_0.JPG: 480x640 (no detections), 296.9ms
Speed: 1.1ms preprocess, 296.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-ms60Ir2D-TC_ACsbzHaQ_90.JPG: 480x640 (no detections), 299.4ms
Speed: 1.0ms preprocess, 299.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-ms60Ir2D-TC_ACsbzHaQ_180.JPG: 480x640 (no detections), 297.9ms
Speed: 1.1ms preprocess, 297.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-ms60Ir2D-TC_ACsbzHaQ_270.JPG: 480x640 (no detections), 301.7ms
Speed: 1.2ms preprocess, 301.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-nYarLP3_ewa7uWGZJhBw_0.JPG: 480x640 (no detections), 297.6ms
Speed: 1.5ms preprocess, 297.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-nYarLP3_ewa7uWGZJhBw_90.JPG: 480x640 (no detections), 306.5ms
Speed: 1.1ms preprocess, 306.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-nYarLP3_ewa7uWGZJhBw_180.JPG: 480x640 (no detections), 302.1ms
Speed: 1.1ms preprocess, 302.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-nYarLP3_ewa7uWGZJhBw_270.JPG: 480x640 (no detections), 300.2ms
Speed: 1.2ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-rMNuRXZedkmiBe4Uyc4A_0.JPG: 480x640 (no detections), 305.6ms
Speed: 1.3ms preprocess, 305.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-rMNuRXZedkmiBe4Uyc4A_90.JPG: 480x640 (no detections), 301.9ms
Speed: 1.2ms preprocess, 301.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-rMNuRXZedkmiBe4Uyc4A_180.JPG: 480x640 (no detections), 294.6ms
Speed: 1.3ms preprocess, 294.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-rMNuRXZedkmiBe4Uyc4A_270.JPG: 480x640 (no detections), 294.8ms
Speed: 1.4ms preprocess, 294.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-tyckufOuh9Dtq8UmxRSg_0.JPG: 480x640 (no detections), 286.7ms
Speed: 1.1ms preprocess, 286.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-tyckufOuh9Dtq8UmxRSg_90.JPG: 480x640 (no detections), 299.0ms
Speed: 1.6ms preprocess, 299.0ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-tyckufOuh9Dtq8UmxRSg_180.JPG: 480x640 (no detections), 394.3ms
Speed: 2.2ms preprocess, 394.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-tyckufOuh9Dtq8UmxRSg_270.JPG: 480x640 (no detections), 295.3ms

Speed: 1.2ms preprocess, 295.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-uXhGll4fnpvZv3e7SMvw_0.JPG: 480x640 1 Waste, 337.0ms
Speed: 1.5ms preprocess, 337.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-uXhGll4fnpvZv3e7SMvw_90.JPG: 480x640 (no detections), 334.6ms
Speed: 1.2ms preprocess, 334.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-uXhGll4fnpvZv3e7SMvw_180.JPG: 480x640 (no detections), 296.7ms
Speed: 1.4ms preprocess, 296.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-uXhGll4fnpvZv3e7SMvw_270.JPG: 480x640 (no detections), 289.0ms
Speed: 1.2ms preprocess, 289.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-vbiNvKN4AhGWtMqBYWJQ_0.JPG: 480x640 (no detections), 294.3ms
Speed: 1.1ms preprocess, 294.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-vbiNvKN4AhGWtMqBYWJQ_90.JPG: 480x640 (no detections), 300.1ms
Speed: 1.1ms preprocess, 300.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-vbiNvKN4AhGWtMqBYWJQ_180.JPG: 480x640 (no detections), 300.3ms
Speed: 1.6ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/-/x-vbiNvKN4AhGWtMqBYWJQ_270.JPG: 480x640 (no detections), 306.8ms
Speed: 1.2ms preprocess, 306.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x00fjggxXhopQsEECk_Xvw_0.JPG: 480x640 (no detections), 308.1ms
Speed: 1.1ms preprocess, 308.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x00fjggxXhopQsEECk_Xvw_90.JPG: 480x640 (no detections), 299.9ms
Speed: 1.8ms preprocess, 299.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x00fjggxXhopQsEECk_Xvw_180.JPG: 480x640 (no detections), 295.9ms
Speed: 1.3ms preprocess, 295.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x00fjggxXhopQsEECk_Xvw_270.JPG: 480x640 (no detections), 302.0ms
Speed: 1.3ms preprocess, 302.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x03PUk7VD7SdJCn52nPUaw_0.JPG: 480x640 (no detections), 300.7ms
Speed: 1.3ms preprocess, 300.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x03PUk7VD7SdJCn52nPUaw_90.JPG: 480x640 (no detections), 298.3ms
Speed: 1.1ms preprocess, 298.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x03PUk7VD7SdJCn52nPUaw_180.JPG: 480x640 (no detections), 293.7ms
Speed: 1.1ms preprocess, 293.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x03PUk7VD7SdJCn52nPUaw_270.JPG: 480x640 (no detections), 304.3ms
Speed: 1.2ms preprocess, 304.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0A4ujlepyt_aldb6kEluQ_0.JPG: 480x640 (no detections), 300.8ms
Speed: 1.2ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0A4ujlepyt_aldb6kEluQ_90.JPG: 480x640 (no detections), 291.4ms
Speed: 1.1ms preprocess, 291.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0A4ujlepyt_aldb6kEluQ_180.JPG: 480x640 (no detections), 297.1ms
Speed: 1.1ms preprocess, 297.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0A4ujlepyt_aldb6kEluQ_270.JPG: 480x640 (no detections), 299.6ms
Speed: 1.1ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0ACMmQP44PLBjBza4R0zg_0.JPG: 480x640 (no detections), 300.6ms
Speed: 1.3ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0ACMmQP44PLBjBza4R0zg_90.JPG: 480x640 (no detections), 301.4ms
Speed: 1.2ms preprocess, 301.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0ACMmQP44PLBjBza4R0zg_180.JPG: 480x640 (no detections), 300.4ms
Speed: 1.2ms preprocess, 300.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0ACMmQP44PLBjBza4R0zg_270.JPG: 480x640 (no detections), 300.7ms
Speed: 1.4ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0CX_ZWKDSLE__i_wqGXyg_0.JPG: 480x640 1 Waste, 307.6ms
Speed: 1.3ms preprocess, 307.6ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0CX_ZWKDSLE__i_wqGXyg_90.JPG: 480x640 (no detections), 302.2ms
Speed: 1.4ms preprocess, 302.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0CX_ZWKDSLE__i_wqGXyg_180.JPG: 480x640 (no detections), 292.6ms
Speed: 1.2ms preprocess, 292.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0CX_ZWKDSLE__i_wqGXyg_270.JPG: 480x640 1 Waste, 296.8ms
Speed: 1.1ms preprocess, 296.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0GbTud3fA003We3vJOinA_0.JPG: 480x640 (no detections), 301.3ms
Speed: 1.3ms preprocess, 301.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0GbTud3fA003We3vJOinA_90.JPG: 480x640 (no detections), 305.0ms
Speed: 1.1ms preprocess, 305.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0GbTud3fA003We3vJOinA_180.JPG: 480x640 (no detections), 296.6ms
Speed: 1.3ms preprocess, 296.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0GbTud3fA003We3vJOinA_270.JPG: 480x640 (no detections), 294.2ms
Speed: 1.3ms preprocess, 294.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0IGxvnvvNGTA0zKtwfxCA_0.JPG: 480x640 (no detections), 301.0ms
Speed: 1.3ms preprocess, 301.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0IGxvnvvNGTA0zKtwfxCA_90.JPG: 480x640 (no detections), 298.2ms
Speed: 1.4ms preprocess, 298.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0IGxvnvvNGTA0zKtwfxCA_180.JPG: 480x640 (no detections), 296.9ms
Speed: 1.4ms preprocess, 296.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0IGxvnvvNGTA0zKtwfxCA_270.JPG: 480x640 (no detections), 300.5ms
Speed: 1.6ms preprocess, 300.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0IOqb97lCcbFgcpGJ6zrQ_0.JPG: 480x640 (no detections), 299.3ms
Speed: 1.3ms preprocess, 299.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0IOqb97lCcbFgcpGJ6zrQ_90.JPG: 480x640 (no detections), 299.8ms
Speed: 1.3ms preprocess, 299.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0IOqb97lCcbFgcpGJ6zrQ_180.JPG: 480x640 (no detections), 297.8ms
Speed: 1.2ms preprocess, 297.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0IOqb97lCcbFgcpGJ6zrQ_270.JPG: 480x640 (no detections), 300.5ms
Speed: 1.6ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0LJa1jeOf_kc_AsKMF9Jg_0.JPG: 480x640 (no detections), 302.7ms
Speed: 1.2ms preprocess, 302.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0LJa1jeOf_kc_AsKMF9Jg_90.JPG: 480x640 (no detections), 294.3ms
Speed: 1.1ms preprocess, 294.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0LJa1jeOf_kc_AsKMF9Jg_180.JPG: 480x640 (no detections), 305.3ms
Speed: 1.1ms preprocess, 305.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0LJa1jeOf_kc_AsKMF9Jg_270.JPG: 480x640 (no detections), 298.5ms
Speed: 1.1ms preprocess, 298.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0SQu-EMYU8PTJV5E8BMEg_0.JPG: 480x640 1 Waste, 299.1ms
Speed: 1.2ms preprocess, 299.1ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0SQu-EMYU8PTJV5E8BMEg_90.JPG: 480x640 (no detections), 302.8ms
Speed: 1.4ms preprocess, 302.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0SQu-EMYU8PTJV5E8BMEg_180.JPG: 480x640 (no detections), 298.3ms
Speed: 1.3ms preprocess, 298.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0SQu-EMYU8PTJV5E8BMEg_270.JPG: 480x640 (no detections), 297.8ms
Speed: 1.4ms preprocess, 297.8ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0SnvoK5cXozLZOYHkm1qw_0.JPG: 480x640 (no detections), 308.5ms
Speed: 1.2ms preprocess, 308.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0SnvoK5cXozLZOYHkm1qw_90.JPG: 480x640 (no detections), 301.2ms
Speed: 1.1ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0SnvoK5cXozLZOYHkm1qw_180.JPG: 480x640 (no detections), 300.1ms
Speed: 1.8ms preprocess, 300.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0SnvoK5cXozLZOYHkm1qw_270.JPG: 480x640 (no detections), 301.0ms
Speed: 1.3ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0So6k8KXS3vFovksEf-VA_0.JPG: 480x640 (no detections), 296.8ms
Speed: 1.5ms preprocess, 296.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0So6k8KXS3vFovksEf-VA_90.JPG: 480x640 (no detections), 304.8ms
Speed: 1.3ms preprocess, 304.8ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0So6k8KXS3vFovksEf-VA_180.JPG: 480x640 (no detections), 299.8ms
Speed: 1.2ms preprocess, 299.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0So6k8KXS3vFovksEf-VA_270.JPG: 480x640 (no detections), 305.2ms
Speed: 1.5ms preprocess, 305.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0YUxPDyNX6-v2nXwa7ctg_0.JPG: 480x640 (no detections), 305.7ms
Speed: 1.1ms preprocess, 305.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0YUxPDyNX6-v2nXwa7ctg_90.JPG: 480x640 (no detections), 299.3ms
Speed: 1.1ms preprocess, 299.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0YUxPDyNX6-v2nXwa7ctg_180.JPG: 480x640 1 Waste, 296.8ms
Speed: 1.0ms preprocess, 296.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0YUxPDyNX6-v2nXwa7ctg_270.JPG: 480x640 (no detections), 301.0ms
Speed: 1.2ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0Zy4f-pcim-W6CcEvFUZg_0.JPG: 480x640 (no detections), 296.7ms
Speed: 1.1ms preprocess, 296.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0Zy4f-pcim-W6CcEvFUZg_90.JPG: 480x640 (no detections), 300.4ms
Speed: 1.2ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0Zy4f-pcim-W6CcEvFUZg_180.JPG: 480x640 1 Waste, 301.2ms
Speed: 1.0ms preprocess, 301.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0Zy4f-pcim-W6CcEvFUZg_270.JPG: 480x640 1 Waste, 305.0ms
Speed: 1.6ms preprocess, 305.0ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0fSrZdtxIn6WBAmn1nbaA_0.JPG: 480x640 (no detections), 309.6ms
Speed: 1.1ms preprocess, 309.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0fSrZdtxIn6WBAmn1nbaA_90.JPG: 480x640 (no detections), 301.7ms
Speed: 1.2ms preprocess, 301.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0fSrZdtxIn6WBAmn1nbaA_180.JPG: 480x640 (no detections), 293.1ms

Speed: 1.2ms preprocess, 293.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0fSrZdtxIn6WBAmn1nbaA_270.JPG: 480x640 (no detections), 302.4ms
Speed: 1.2ms preprocess, 302.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0gwATQT69AI6s1uC_A6jA_0.JPG: 480x640 (no detections), 305.2ms
Speed: 1.1ms preprocess, 305.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0gwATQT69AI6s1uC_A6jA_90.JPG: 480x640 (no detections), 298.5ms
Speed: 1.2ms preprocess, 298.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0gwATQT69AI6s1uC_A6jA_180.JPG: 480x640 (no detections), 300.4ms
Speed: 1.1ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0gwATQT69AI6s1uC_A6jA_270.JPG: 480x640 (no detections), 294.9ms
Speed: 1.0ms preprocess, 294.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0h1mmP-nVgsCeBvL7Hiig_0.JPG: 480x640 (no detections), 300.4ms
Speed: 1.1ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0h1mmP-nVgsCeBvL7Hiig_90.JPG: 480x640 (no detections), 301.7ms
Speed: 1.3ms preprocess, 301.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0h1mmP-nVgsCeBvL7Hiig_180.JPG: 480x640 (no detections), 299.2ms
Speed: 1.1ms preprocess, 299.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0h1mmP-nVgsCeBvL7Hiig_270.JPG: 480x640 (no detections), 298.6ms
Speed: 1.2ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0i0Djf0OX6d2ErwCJHkZg_0.JPG: 480x640 (no detections), 300.9ms
Speed: 1.4ms preprocess, 300.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0i0Djf0OX6d2ErwCJHkZg_90.JPG: 480x640 (no detections), 300.3ms
Speed: 1.5ms preprocess, 300.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0i0Djf0OX6d2ErwCJHkZg_180.JPG: 480x640 (no detections), 291.1ms
Speed: 1.2ms preprocess, 291.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0i0Djf0OX6d2ErwCJHkZg_270.JPG: 480x640 (no detections), 288.8ms
Speed: 1.0ms preprocess, 288.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0pHed9oxLGNJ6wK3pKRBQ_0.JPG: 480x640 (no detections), 291.4ms
Speed: 1.3ms preprocess, 291.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0pHed9oxLGNJ6wK3pKRBQ_90.JPG: 480x640 (no detections), 302.3ms
Speed: 1.3ms preprocess, 302.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0pHed9oxLGNJ6wK3pKRBQ_180.JPG: 480x640 (no detections), 303.2ms
Speed: 1.4ms preprocess, 303.2ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0pHed9oxLGNJ6wK3pKRBQ_270.JPG: 480x640 (no detections), 295.2ms
Speed: 1.2ms preprocess, 295.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0qAp_JYJuR2lYg2AJVyxw_0.JPG: 480x640 (no detections), 299.1ms
Speed: 1.6ms preprocess, 299.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0qAp_JYJuR2lYg2AJVyxw_90.JPG: 480x640 (no detections), 299.9ms
Speed: 1.1ms preprocess, 299.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0qAp_JYJuR2lYg2AJVyxw_180.JPG: 480x640 (no detections), 300.4ms
Speed: 1.4ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0qAp_JYJuR2lYg2AJVyxw_270.JPG: 480x640 (no detections), 298.8ms
Speed: 1.2ms preprocess, 298.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0yL9Gqf3hGnhI96oe4Zkw_0.JPG: 480x640 (no detections), 298.9ms
Speed: 1.1ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0yL9Gqf3hGnhI96oe4Zkw_90.JPG: 480x640 2 Wastes, 300.0ms
Speed: 1.1ms preprocess, 300.0ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0yL9Gqf3hGnhI96oe4Zkw_180.JPG: 480x640 (no detections), 296.7ms
Speed: 1.1ms preprocess, 296.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0yL9Gqf3hGnhI96oe4Zkw_270.JPG: 480x640 (no detections), 299.3ms
Speed: 1.1ms preprocess, 299.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0ybNWelyOLYBZLjkjrLEw_0.JPG: 480x640 (no detections), 294.6ms
Speed: 1.4ms preprocess, 294.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0ybNWelyOLYBZLjkjrLEw_90.JPG: 480x640 (no detections), 296.1ms
Speed: 1.2ms preprocess, 296.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0ybNWelyOLYBZLjkjrLEw_180.JPG: 480x640 (no detections), 303.5ms
Speed: 1.1ms preprocess, 303.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/0/x0ybNWelyOLYBZLjkjrLEw_270.JPG: 480x640 (no detections), 302.8ms
Speed: 1.4ms preprocess, 302.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x11r2WHITWu82Q4bRe5ZcQ_0.JPG: 480x640 (no detections), 299.1ms
Speed: 1.1ms preprocess, 299.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x11r2WHITWu82Q4bRe5ZcQ_90.JPG: 480x640 (no detections), 305.7ms
Speed: 1.1ms preprocess, 305.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x11r2WHITWu82Q4bRe5ZcQ_180.JPG: 480x640 (no detections), 300.6ms
Speed: 1.2ms preprocess, 300.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x11r2WHITWu82Q4bRe5ZcQ_270.JPG: 480x640 (no detections), 301.6ms
Speed: 1.2ms preprocess, 301.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1AcuIhUHKWdKT8BTZU34g_0.JPG: 480x640 (no detections), 304.0ms
Speed: 1.2ms preprocess, 304.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1AcuIhUHKWdKT8BTZU34g_90.JPG: 480x640 (no detections), 298.8ms
Speed: 1.1ms preprocess, 298.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1AcuIhUHKWdKT8BTZU34g_180.JPG: 480x640 (no detections), 298.6ms
Speed: 1.4ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1AcuIhUHKWdKT8BTZU34g_270.JPG: 480x640 (no detections), 299.4ms
Speed: 1.0ms preprocess, 299.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1C8masnwwKqoF6mvMpLrg_0.JPG: 480x640 (no detections), 305.7ms
Speed: 1.3ms preprocess, 305.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1C8masnwwKqoF6mvMpLrg_90.JPG: 480x640 (no detections), 302.3ms
Speed: 1.3ms preprocess, 302.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1C8masnwwKqoF6mvMpLrg_180.JPG: 480x640 (no detections), 301.1ms
Speed: 1.9ms preprocess, 301.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1C8masnwwKqoF6mvMpLrg_270.JPG: 480x640 (no detections), 299.3ms
Speed: 1.3ms preprocess, 299.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1DATkA1e6aVGUqM4-cg5Q_0.JPG: 480x640 (no detections), 307.6ms
Speed: 1.5ms preprocess, 307.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1DATkA1e6aVGUqM4-cg5Q_90.JPG: 480x640 (no detections), 300.8ms
Speed: 1.8ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1DATkA1e6aVGUqM4-cg5Q_180.JPG: 480x640 (no detections), 301.1ms
Speed: 1.3ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1DATkA1e6aVGUqM4-cg5Q_270.JPG: 480x640 (no detections), 298.8ms
Speed: 1.1ms preprocess, 298.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1G_lFy8EVMJ4f8Th_4F9g_0.JPG: 480x640 (no detections), 299.7ms
Speed: 1.4ms preprocess, 299.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1G_lFy8EVMJ4f8Th_4F9g_90.JPG: 480x640 (no detections), 301.9ms
Speed: 1.3ms preprocess, 301.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1G_lFy8EVMJ4f8Th_4F9g_180.JPG: 480x640 (no detections), 300.6ms
Speed: 1.2ms preprocess, 300.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1G_lFy8EVMJ4f8Th_4F9g_270.JPG: 480x640 (no detections), 297.1ms
Speed: 1.2ms preprocess, 297.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1HQNAfu8OLcS_Dh67be7A_0.JPG: 480x640 (no detections), 297.8ms
Speed: 1.2ms preprocess, 297.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1HQNAfu8OLcS_Dh67be7A_90.JPG: 480x640 (no detections), 300.1ms
Speed: 1.2ms preprocess, 300.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1HQNAfu8OLcS_Dh67be7A_180.JPG: 480x640 (no detections), 298.7ms
Speed: 1.0ms preprocess, 298.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1HQNAfu8OLcS_Dh67be7A_270.JPG: 480x640 (no detections), 383.9ms
Speed: 1.1ms preprocess, 383.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1Mol5qsDpsN8aULQqD6fA_0.JPG: 480x640 (no detections), 302.4ms
Speed: 1.2ms preprocess, 302.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1Mol5qsDpsN8aULQqD6fA_90.JPG: 480x640 (no detections), 307.4ms
Speed: 1.4ms preprocess, 307.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1Mol5qsDpsN8aULQqD6fA_180.JPG: 480x640 (no detections), 305.6ms
Speed: 1.7ms preprocess, 305.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1Mol5qsDpsN8aULQqD6fA_270.JPG: 480x640 (no detections), 302.5ms
Speed: 1.3ms preprocess, 302.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1PhGN_jd5zbPeXiHeg4sw_0.JPG: 480x640 (no detections), 298.0ms
Speed: 1.3ms preprocess, 298.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1PhGN_jd5zbPeXiHeg4sw_90.JPG: 480x640 (no detections), 299.7ms
Speed: 1.2ms preprocess, 299.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1PhGN_jd5zbPeXiHeg4sw_180.JPG: 480x640 (no detections), 311.6ms
Speed: 1.2ms preprocess, 311.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1PhGN_jd5zbPeXiHeg4sw_270.JPG: 480x640 (no detections), 299.7ms
Speed: 1.8ms preprocess, 299.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1Qx_Bxcwq3LIcQPeEvZfw_0.JPG: 480x640 (no detections), 298.9ms
Speed: 1.2ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1Qx_Bxcwq3LIcQPeEvZfw_90.JPG: 480x640 (no detections), 297.1ms
Speed: 1.1ms preprocess, 297.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1Qx_Bxcwq3LIcQPeEvZfw_180.JPG: 480x640 (no detections), 300.5ms
Speed: 1.1ms preprocess, 300.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1Qx_Bxcwq3LIcQPeEvZfw_270.JPG: 480x640 (no detections), 303.9ms
Speed: 1.1ms preprocess, 303.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1Sc9OgBAo6_tLauezfNbw_0.JPG: 480x640 (no detections), 297.3ms
Speed: 1.3ms preprocess, 297.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1Sc9OgBAo6_tLauezfNbw_90.JPG: 480x640 (no detections), 295.6ms

Speed: 1.0ms preprocess, 295.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1Sc9OgBAo6_tLauezfNbw_180.JPG: 480x640 (no detections), 303.3ms
Speed: 1.2ms preprocess, 303.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1Sc9OgBAo6_tLauezfNbw_270.JPG: 480x640 (no detections), 295.7ms
Speed: 1.1ms preprocess, 295.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1TguySh1fcg_LsLKbqUkg_0.JPG: 480x640 (no detections), 303.5ms
Speed: 1.2ms preprocess, 303.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1TguySh1fcg_LsLKbqUkg_90.JPG: 480x640 (no detections), 303.2ms
Speed: 1.0ms preprocess, 303.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1TguySh1fcg_LsLKbqUkg_180.JPG: 480x640 (no detections), 299.7ms
Speed: 1.3ms preprocess, 299.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1TguySh1fcg_LsLKbqUkg_270.JPG: 480x640 (no detections), 302.1ms
Speed: 1.3ms preprocess, 302.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1VGTdzzm2MGx7v8f01weA_0.JPG: 480x640 (no detections), 297.9ms
Speed: 1.2ms preprocess, 297.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1VGTdzzm2MGx7v8f01weA_90.JPG: 480x640 (no detections), 298.0ms
Speed: 1.0ms preprocess, 298.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1VGTdzzm2MGx7v8f01weA_180.JPG: 480x640 (no detections), 298.8ms
Speed: 1.1ms preprocess, 298.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1VGTdzzm2MGx7v8f01weA_270.JPG: 480x640 (no detections), 298.4ms
Speed: 1.1ms preprocess, 298.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1c3YhwtTT2nRb2sTZq_xA_0.JPG: 480x640 (no detections), 301.9ms
Speed: 1.4ms preprocess, 301.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1c3YhwtTT2nRb2sTZq_xA_90.JPG: 480x640 (no detections), 301.0ms
Speed: 1.2ms preprocess, 301.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1c3YhwtTT2nRb2sTZq_xA_180.JPG: 480x640 (no detections), 304.1ms
Speed: 1.2ms preprocess, 304.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1c3YhwtTT2nRb2sTZq_xA_270.JPG: 480x640 (no detections), 298.4ms
Speed: 1.1ms preprocess, 298.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1hTJ917DMNVyCw6RfS6Hg_0.JPG: 480x640 (no detections), 299.9ms
Speed: 1.2ms preprocess, 299.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1hTJ917DMNVyCw6RfS6Hg_90.JPG: 480x640 (no detections), 302.5ms
Speed: 1.1ms preprocess, 302.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1hTJ917DMNVyCw6RfS6Hg_180.JPG: 480x640 (no detections), 303.7ms
Speed: 1.3ms preprocess, 303.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1hTJ917DMNVyCw6RfS6Hg_270.JPG: 480x640 (no detections), 305.4ms
Speed: 1.4ms preprocess, 305.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1j--5tKl3ZKE1GF8Ef6TQ_0.JPG: 480x640 (no detections), 297.6ms
Speed: 1.2ms preprocess, 297.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1j--5tKl3ZKE1GF8Ef6TQ_90.JPG: 480x640 (no detections), 300.8ms
Speed: 1.1ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1j--5tKl3ZKE1GF8Ef6TQ_180.JPG: 480x640 (no detections), 296.9ms
Speed: 1.2ms preprocess, 296.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1j--5tKl3ZKE1GF8Ef6TQ_270.JPG: 480x640 (no detections), 301.1ms
Speed: 1.1ms preprocess, 301.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1lKtXPtueXRvf4M1o8TEg_0.JPG: 480x640 (no detections), 304.0ms
Speed: 1.0ms preprocess, 304.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1lKtXPtueXRvf4M1o8TEg_90.JPG: 480x640 (no detections), 298.5ms
Speed: 1.5ms preprocess, 298.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1lKtXPtueXRvf4M1o8TEg_180.JPG: 480x640 (no detections), 300.5ms
Speed: 2.3ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1lKtXPtueXRvf4M1o8TEg_270.JPG: 480x640 (no detections), 296.8ms
Speed: 1.1ms preprocess, 296.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1lOzLMZigej5YrqMDkIDw_0.JPG: 480x640 (no detections), 307.6ms
Speed: 1.6ms preprocess, 307.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1lOzLMZigej5YrqMDkIDw_90.JPG: 480x640 (no detections), 301.2ms
Speed: 1.2ms preprocess, 301.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1lOzLMZigej5YrqMDkIDw_180.JPG: 480x640 (no detections), 301.9ms
Speed: 1.3ms preprocess, 301.9ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1lOzLMZigej5YrqMDkIDw_270.JPG: 480x640 (no detections), 301.4ms
Speed: 1.3ms preprocess, 301.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1nWJ8bHydlRm4zITL5E2g_0.JPG: 480x640 (no detections), 296.6ms
Speed: 1.2ms preprocess, 296.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1nWJ8bHydlRm4zITL5E2g_90.JPG: 480x640 (no detections), 301.1ms
Speed: 1.4ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1nWJ8bHydlRm4zITL5E2g_180.JPG: 480x640 1 Waste, 293.8ms
Speed: 1.2ms preprocess, 293.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1nWJ8bHydlRm4zITL5E2g_270.JPG: 480x640 (no detections), 300.5ms
Speed: 1.2ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1oYzzdRrL09tfJSMd02wQ_0.JPG: 480x640 (no detections), 302.2ms
Speed: 1.1ms preprocess, 302.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1oYzzdRrL09tfJSMd02wQ_90.JPG: 480x640 (no detections), 305.7ms
Speed: 1.2ms preprocess, 305.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1oYzzdRrL09tfJSMd02wQ_180.JPG: 480x640 (no detections), 301.8ms
Speed: 1.4ms preprocess, 301.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/1/x1oYzzdRrL09tfJSMd02wQ_270.JPG: 480x640 (no detections), 300.6ms
Speed: 1.2ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2-CnV9eQ7Zs7dZ4zPzIXA_0.JPG: 480x640 (no detections), 307.5ms
Speed: 1.1ms preprocess, 307.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2-CnV9eQ7Zs7dZ4zPzIXA_90.JPG: 480x640 (no detections), 301.4ms
Speed: 1.6ms preprocess, 301.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2-CnV9eQ7Zs7dZ4zPzIXA_180.JPG: 480x640 (no detections), 298.6ms
Speed: 1.4ms preprocess, 298.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2-CnV9eQ7Zs7dZ4zPzIXA_270.JPG: 480x640 1 Waste, 299.4ms
Speed: 1.3ms preprocess, 299.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x20IDsQdiL3cwsW9C3MW8g_0.JPG: 480x640 (no detections), 296.8ms
Speed: 1.2ms preprocess, 296.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x20IDsQdiL3cwsW9C3MW8g_90.JPG: 480x640 (no detections), 304.3ms
Speed: 1.2ms preprocess, 304.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x20IDsQdiL3cwsW9C3MW8g_180.JPG: 480x640 (no detections), 300.0ms
Speed: 1.2ms preprocess, 300.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x20IDsQdiL3cwsW9C3MW8g_270.JPG: 480x640 (no detections), 301.9ms
Speed: 1.3ms preprocess, 301.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x23cqD-UdEPxK-AFg1qTEA_0.JPG: 480x640 (no detections), 300.6ms
Speed: 1.1ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x23cqD-UdEPxK-AFg1qTEA_90.JPG: 480x640 (no detections), 304.3ms
Speed: 1.0ms preprocess, 304.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x23cqD-UdEPxK-AFg1qTEA_180.JPG: 480x640 (no detections), 297.1ms
Speed: 1.1ms preprocess, 297.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x23cqD-UdEPxK-AFg1qTEA_270.JPG: 480x640 (no detections), 297.7ms
Speed: 1.2ms preprocess, 297.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x24yjXEUBXBunxsADJLuLg_0.JPG: 480x640 (no detections), 296.2ms
Speed: 1.4ms preprocess, 296.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x24yjXEUBXBunxsADJLuLg_90.JPG: 480x640 (no detections), 297.6ms
Speed: 1.1ms preprocess, 297.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x24yjXEUBXBunxsADJLuLg_180.JPG: 480x640 (no detections), 302.2ms
Speed: 1.1ms preprocess, 302.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x24yjXEUBXBunxsADJLuLg_270.JPG: 480x640 (no detections), 306.1ms
Speed: 1.3ms preprocess, 306.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x27a8SnNhzeDgIGQHgLZpg_0.JPG: 480x640 (no detections), 295.6ms
Speed: 1.1ms preprocess, 295.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x27a8SnNhzeDgIGQHgLZpg_90.JPG: 480x640 (no detections), 306.5ms
Speed: 1.1ms preprocess, 306.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x27a8SnNhzeDgIGQHgLZpg_180.JPG: 480x640 (no detections), 302.2ms
Speed: 1.3ms preprocess, 302.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x27a8SnNhzeDgIGQHgLZpg_270.JPG: 480x640 (no detections), 298.9ms
Speed: 1.3ms preprocess, 298.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x292mhufKPuRRrIZUJWOZQ_0.JPG: 480x640 (no detections), 302.9ms
Speed: 1.3ms preprocess, 302.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x292mhufKPuRRrIZUJWOZQ_90.JPG: 480x640 (no detections), 300.2ms
Speed: 2.1ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x292mhufKPuRRrIZUJWOZQ_180.JPG: 480x640 (no detections), 299.6ms
Speed: 1.3ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x292mhufKPuRRrIZUJWOZQ_270.JPG: 480x640 (no detections), 303.9ms
Speed: 1.2ms preprocess, 303.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x29CK8RFhpgYLlQVnWPUzQ_0.JPG: 480x640 (no detections), 294.4ms
Speed: 1.1ms preprocess, 294.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x29CK8RFhpgYLlQVnWPUzQ_90.JPG: 480x640 (no detections), 299.3ms
Speed: 1.2ms preprocess, 299.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x29CK8RFhpgYLlQVnWPUzQ_180.JPG: 480x640 (no detections), 300.7ms
Speed: 1.8ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x29CK8RFhpgYLlQVnWPUzQ_270.JPG: 480x640 (no detections), 300.6ms
Speed: 1.3ms preprocess, 300.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2MBM2qStpCrTuNwh203VQ_0.JPG: 480x640 (no detections), 312.8ms

Speed: 1.3ms preprocess, 312.8ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2MBM2qStpCrTuNwh203VQ_90.JPG: 480x640 (no detections), 297.1ms
Speed: 1.5ms preprocess, 297.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2MBM2qStpCrTuNwh203VQ_180.JPG: 480x640 (no detections), 298.5ms
Speed: 1.3ms preprocess, 298.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2MBM2qStpCrTuNwh203VQ_270.JPG: 480x640 (no detections), 298.3ms
Speed: 1.3ms preprocess, 298.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2QG_9aQ7rfoGdywM5Djbw_0.JPG: 480x640 (no detections), 299.2ms
Speed: 1.2ms preprocess, 299.2ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2QG_9aQ7rfoGdywM5Djbw_90.JPG: 480x640 (no detections), 299.7ms
Speed: 1.1ms preprocess, 299.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2QG_9aQ7rfoGdywM5Djbw_180.JPG: 480x640 (no detections), 302.1ms
Speed: 1.0ms preprocess, 302.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2QG_9aQ7rfoGdywM5Djbw_270.JPG: 480x640 (no detections), 302.6ms
Speed: 1.2ms preprocess, 302.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2S1nx6douvDY4W_ulR6EQ_0.JPG: 480x640 (no detections), 297.7ms
Speed: 1.3ms preprocess, 297.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2S1nx6douvDY4W_ulR6EQ_90.JPG: 480x640 (no detections), 304.3ms
Speed: 1.3ms preprocess, 304.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2S1nx6douvDY4W_ulR6EQ_180.JPG: 480x640 (no detections), 297.0ms
Speed: 1.2ms preprocess, 297.0ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2S1nx6douvDY4W_ulR6EQ_270.JPG: 480x640 (no detections), 300.7ms
Speed: 1.2ms preprocess, 300.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2T7R09iwamZ3hnaTiux5w_0.JPG: 480x640 (no detections), 295.3ms
Speed: 1.1ms preprocess, 295.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2T7R09iwamZ3hnaTiux5w_90.JPG: 480x640 (no detections), 305.7ms
Speed: 1.2ms preprocess, 305.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2T7R09iwamZ3hnaTiux5w_180.JPG: 480x640 (no detections), 298.5ms
Speed: 1.1ms preprocess, 298.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2T7R09iwamZ3hnaTiux5w_270.JPG: 480x640 (no detections), 300.6ms
Speed: 1.4ms preprocess, 300.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2Wo5oBnjrMlORVZrPn9rg_0.JPG: 480x640 (no detections), 293.9ms
Speed: 1.2ms preprocess, 293.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2Wo5oBnjrMlORVZrPn9rg_90.JPG: 480x640 (no detections), 298.9ms
Speed: 1.0ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2Wo5oBnjrMlORVZrPn9rg_180.JPG: 480x640 (no detections), 298.6ms
Speed: 1.1ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2Wo5oBnjrMlORVZrPn9rg_270.JPG: 480x640 (no detections), 299.0ms
Speed: 1.1ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2YR8ASAwJkQhrGJb5K5ag_0.JPG: 480x640 (no detections), 301.6ms
Speed: 1.1ms preprocess, 301.6ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2YR8ASAwJkQhrGJb5K5ag_90.JPG: 480x640 (no detections), 301.9ms
Speed: 1.9ms preprocess, 301.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2YR8ASAwJkQhrGJb5K5ag_180.JPG: 480x640 (no detections), 299.6ms
Speed: 1.3ms preprocess, 299.6ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2YR8ASAwJkQhrGJb5K5ag_270.JPG: 480x640 (no detections), 300.8ms
Speed: 1.1ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2YSyEvSInpjjQiOqtW7Ag_0.JPG: 480x640 (no detections), 296.6ms
Speed: 1.2ms preprocess, 296.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2YSyEvSInpjjQiOqtW7Ag_90.JPG: 480x640 2 Wastes, 302.3ms
Speed: 1.1ms preprocess, 302.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2YSyEvSInpjjQiOqtW7Ag_180.JPG: 480x640 (no detections), 306.7ms
Speed: 1.2ms preprocess, 306.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2YSyEvSInpjjQiOqtW7Ag_270.JPG: 480x640 (no detections), 291.2ms
Speed: 1.2ms preprocess, 291.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2Z3MS7u3izuDs-BCE7jFw_0.JPG: 480x640 (no detections), 302.4ms
Speed: 1.1ms preprocess, 302.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2Z3MS7u3izuDs-BCE7jFw_90.JPG: 480x640 (no detections), 300.6ms
Speed: 1.2ms preprocess, 300.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2Z3MS7u3izuDs-BCE7jFw_180.JPG: 480x640 (no detections), 298.7ms
Speed: 1.1ms preprocess, 298.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2Z3MS7u3izuDs-BCE7jFw_270.JPG: 480x640 (no detections), 297.4ms
Speed: 1.1ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2_V1zvihJQYQRilNKMcLw_0.JPG: 480x640 (no detections), 298.7ms
Speed: 1.0ms preprocess, 298.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2_V1zvihJQYQRilNKMcLw_90.JPG: 480x640 (no detections), 301.1ms
Speed: 1.3ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2_V1zvihJQYQRilNKMcLw_180.JPG: 480x640 (no detections), 299.1ms
Speed: 1.3ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2_V1zvihJQYQRilNKMcLw_270.JPG: 480x640 (no detections), 304.8ms
Speed: 1.7ms preprocess, 304.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2aR7PiVor-03HSmcI-28g_0.JPG: 480x640 (no detections), 302.4ms
Speed: 1.1ms preprocess, 302.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2aR7PiVor-03HSmcI-28g_90.JPG: 480x640 (no detections), 300.9ms
Speed: 1.2ms preprocess, 300.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2aR7PiVor-03HSmcI-28g_180.JPG: 480x640 (no detections), 299.5ms
Speed: 1.4ms preprocess, 299.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2aR7PiVor-03HSmcI-28g_270.JPG: 480x640 (no detections), 301.5ms
Speed: 1.2ms preprocess, 301.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2bLRzC7Io4t3tSOOpwn6A_0.JPG: 480x640 (no detections), 297.8ms
Speed: 1.1ms preprocess, 297.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2bLRzC7Io4t3tSOOpwn6A_90.JPG: 480x640 (no detections), 302.7ms
Speed: 1.5ms preprocess, 302.7ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2bLRzC7Io4t3tSOOpwn6A_180.JPG: 480x640 (no detections), 298.3ms
Speed: 1.2ms preprocess, 298.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2bLRzC7Io4t3tSOOpwn6A_270.JPG: 480x640 (no detections), 294.4ms
Speed: 1.2ms preprocess, 294.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2bmKn_k3qUBmWsYrOCLlQ_0.JPG: 480x640 (no detections), 296.2ms
Speed: 1.8ms preprocess, 296.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2bmKn_k3qUBmWsYrOCLlQ_90.JPG: 480x640 (no detections), 300.1ms
Speed: 1.3ms preprocess, 300.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2bmKn_k3qUBmWsYrOCLlQ_180.JPG: 480x640 (no detections), 299.9ms
Speed: 1.5ms preprocess, 299.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2bmKn_k3qUBmWsYrOCLlQ_270.JPG: 480x640 (no detections), 300.9ms
Speed: 1.0ms preprocess, 300.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2g6vEDh26JoHSTUoHdMCg_0.JPG: 480x640 (no detections), 297.0ms
Speed: 1.1ms preprocess, 297.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2g6vEDh26JoHSTUoHdMCg_90.JPG: 480x640 (no detections), 296.0ms
Speed: 1.2ms preprocess, 296.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2g6vEDh26JoHSTUoHdMCg_180.JPG: 480x640 (no detections), 300.0ms
Speed: 1.4ms preprocess, 300.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2g6vEDh26JoHSTUoHdMCg_270.JPG: 480x640 (no detections), 300.9ms
Speed: 1.3ms preprocess, 300.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2hbbzi-ujDIxZAkrmo4Ww_0.JPG: 480x640 (no detections), 300.5ms
Speed: 1.2ms preprocess, 300.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2hbbzi-ujDIxZAkrmo4Ww_90.JPG: 480x640 (no detections), 301.8ms
Speed: 1.1ms preprocess, 301.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2hbbzi-ujDIxZAkrmo4Ww_180.JPG: 480x640 1 Waste, 296.5ms
Speed: 1.3ms preprocess, 296.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2hbbzi-ujDIxZAkrmo4Ww_270.JPG: 480x640 (no detections), 301.5ms
Speed: 1.4ms preprocess, 301.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2jM6vLIp31sGyCYo7cw6A_0.JPG: 480x640 (no detections), 297.8ms
Speed: 1.3ms preprocess, 297.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2jM6vLIp31sGyCYo7cw6A_90.JPG: 480x640 (no detections), 299.0ms
Speed: 1.2ms preprocess, 299.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2jM6vLIp31sGyCYo7cw6A_180.JPG: 480x640 (no detections), 293.9ms
Speed: 1.2ms preprocess, 293.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2jM6vLIp31sGyCYo7cw6A_270.JPG: 480x640 (no detections), 299.4ms
Speed: 1.1ms preprocess, 299.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2jZ9EgF8R4sOsA0mD_FkQ_0.JPG: 480x640 1 Waste, 304.5ms
Speed: 1.2ms preprocess, 304.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2jZ9EgF8R4sOsA0mD_FkQ_90.JPG: 480x640 (no detections), 302.7ms
Speed: 1.3ms preprocess, 302.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2jZ9EgF8R4sOsA0mD_FkQ_180.JPG: 480x640 (no detections), 302.2ms
Speed: 1.1ms preprocess, 302.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2jZ9EgF8R4sOsA0mD_FkQ_270.JPG: 480x640 (no detections), 301.3ms
Speed: 1.0ms preprocess, 301.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2kiIqapuFYf5yIKwTa4TQ_0.JPG: 480x640 (no detections), 305.9ms
Speed: 1.1ms preprocess, 305.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2kiIqapuFYf5yIKwTa4TQ_90.JPG: 480x640 (no detections), 297.7ms
Speed: 1.2ms preprocess, 297.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2kiIqapuFYf5yIKwTa4TQ_180.JPG: 480x640 (no detections), 304.4ms
Speed: 1.2ms preprocess, 304.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2kiIqapuFYf5yIKwTa4TQ_270.JPG: 480x640 (no detections), 298.4ms

Speed: 1.2ms preprocess, 298.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2mGAbEW6oZORE-hqNyRTw_0.JPG: 480x640 (no detections), 295.7ms
Speed: 1.2ms preprocess, 295.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2mGAbEW6oZORE-hqNyRTw_90.JPG: 480x640 (no detections), 302.0ms
Speed: 1.1ms preprocess, 302.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2mGAbEW6oZORE-hqNyRTw_180.JPG: 480x640 (no detections), 297.1ms
Speed: 1.4ms preprocess, 297.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2mGAbEW6oZORE-hqNyRTw_270.JPG: 480x640 (no detections), 298.4ms
Speed: 1.1ms preprocess, 298.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2nsmBmNgkkYqEvH1exS8Q_0.JPG: 480x640 (no detections), 297.8ms
Speed: 1.4ms preprocess, 297.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2nsmBmNgkkYqEvH1exS8Q_90.JPG: 480x640 (no detections), 302.0ms
Speed: 1.3ms preprocess, 302.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2nsmBmNgkkYqEvH1exS8Q_180.JPG: 480x640 (no detections), 299.9ms
Speed: 1.5ms preprocess, 299.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2nsmBmNgkkYqEvH1exS8Q_270.JPG: 480x640 (no detections), 298.2ms
Speed: 1.1ms preprocess, 298.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2pE26DidymNvpKM_m1Bkw_0.JPG: 480x640 (no detections), 299.5ms
Speed: 1.1ms preprocess, 299.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2pE26DidymNvpKM_m1Bkw_90.JPG: 480x640 (no detections), 297.3ms
Speed: 1.1ms preprocess, 297.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2pE26DidymNvpKM_m1Bkw_180.JPG: 480x640 (no detections), 297.3ms
Speed: 1.2ms preprocess, 297.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2pE26DidymNvpKM_m1Bkw_270.JPG: 480x640 (no detections), 304.1ms
Speed: 1.3ms preprocess, 304.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2s64pBiBZYYrYvb0Y5lWA_0.JPG: 480x640 (no detections), 301.2ms
Speed: 1.1ms preprocess, 301.2ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2s64pBiBZYYrYvb0Y5lWA_90.JPG: 480x640 (no detections), 304.6ms
Speed: 1.2ms preprocess, 304.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2s64pBiBZYYrYvb0Y5lWA_180.JPG: 480x640 (no detections), 293.9ms
Speed: 1.2ms preprocess, 293.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2s64pBiBZYYrYvb0Y5lWA_270.JPG: 480x640 (no detections), 300.7ms
Speed: 1.4ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2t3AI5Of3sz0NG4yfU_xw_0.JPG: 480x640 (no detections), 298.4ms
Speed: 1.3ms preprocess, 298.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2t3AI5Of3sz0NG4yfU_xw_90.JPG: 480x640 (no detections), 307.6ms
Speed: 1.0ms preprocess, 307.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2t3AI5Of3sz0NG4yfU_xw_180.JPG: 480x640 (no detections), 301.1ms
Speed: 1.2ms preprocess, 301.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2t3AI5Of3sz0NG4yfU_xw_270.JPG: 480x640 (no detections), 299.1ms
Speed: 1.2ms preprocess, 299.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2wwgW09qvsSkFYzLMUiNw_0.JPG: 480x640 (no detections), 295.8ms
Speed: 1.2ms preprocess, 295.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2wwgW09qvsSkFYzLMUiNw_90.JPG: 480x640 (no detections), 300.4ms
Speed: 1.2ms preprocess, 300.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2wwgW09qvsSkFYzLMUiNw_180.JPG: 480x640 (no detections), 297.5ms
Speed: 1.1ms preprocess, 297.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2wwgW09qvsSkFYzLMUiNw_270.JPG: 480x640 (no detections), 301.3ms
Speed: 1.2ms preprocess, 301.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2ywLn8LnDavAt3HUD5-UQ_0.JPG: 480x640 (no detections), 303.8ms
Speed: 1.1ms preprocess, 303.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2ywLn8LnDavAt3HUD5-UQ_90.JPG: 480x640 (no detections), 299.6ms
Speed: 1.2ms preprocess, 299.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2ywLn8LnDavAt3HUD5-UQ_180.JPG: 480x640 (no detections), 301.2ms
Speed: 1.2ms preprocess, 301.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/2/x2ywLn8LnDavAt3HUD5-UQ_270.JPG: 480x640 (no detections), 305.9ms
Speed: 1.2ms preprocess, 305.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x32QJoqPTCm75MrH_SEFBg_0.JPG: 480x640 (no detections), 301.0ms
Speed: 1.1ms preprocess, 301.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x32QJoqPTCm75MrH_SEFBg_90.JPG: 480x640 (no detections), 305.6ms
Speed: 2.0ms preprocess, 305.6ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x32QJoqPTCm75MrH_SEFBg_180.JPG: 480x640 (no detections), 299.2ms
Speed: 1.1ms preprocess, 299.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x32QJoqPTCm75MrH_SEFBg_270.JPG: 480x640 (no detections), 298.6ms
Speed: 1.1ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x355Jkoy3dWV2mipn05kMQ_0.JPG: 480x640 (no detections), 300.3ms
Speed: 1.2ms preprocess, 300.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x355Jkoy3dWV2mipn05kMQ_90.JPG: 480x640 (no detections), 300.1ms
Speed: 1.4ms preprocess, 300.1ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x355Jkoy3dWV2mipn05kMQ_180.JPG: 480x640 (no detections), 304.4ms
Speed: 1.3ms preprocess, 304.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x355Jkoy3dWV2mipn05kMQ_270.JPG: 480x640 (no detections), 297.2ms
Speed: 1.1ms preprocess, 297.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x37TSAY-vGlQx1AL9OTbTQ_0.JPG: 480x640 (no detections), 294.4ms
Speed: 1.2ms preprocess, 294.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x37TSAY-vGlQx1AL9OTbTQ_90.JPG: 480x640 (no detections), 299.2ms
Speed: 1.0ms preprocess, 299.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x37TSAY-vGlQx1AL9OTbTQ_180.JPG: 480x640 (no detections), 301.3ms
Speed: 1.0ms preprocess, 301.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x37TSAY-vGlQx1AL9OTbTQ_270.JPG: 480x640 (no detections), 301.7ms
Speed: 1.2ms preprocess, 301.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3JzJlUko46CNrR9sa2bBA_0.JPG: 480x640 (no detections), 296.5ms
Speed: 1.2ms preprocess, 296.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3JzJlUko46CNrR9sa2bBA_90.JPG: 480x640 (no detections), 301.6ms
Speed: 1.1ms preprocess, 301.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3JzJlUko46CNrR9sa2bBA_180.JPG: 480x640 (no detections), 297.7ms
Speed: 1.2ms preprocess, 297.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3JzJlUko46CNrR9sa2bBA_270.JPG: 480x640 (no detections), 299.8ms
Speed: 1.1ms preprocess, 299.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3NwtX2UkSiQUtQ66o30WA_0.JPG: 480x640 (no detections), 303.7ms
Speed: 1.5ms preprocess, 303.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3NwtX2UkSiQUtQ66o30WA_90.JPG: 480x640 (no detections), 300.4ms
Speed: 1.2ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3NwtX2UkSiQUtQ66o30WA_180.JPG: 480x640 (no detections), 302.2ms
Speed: 1.4ms preprocess, 302.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3NwtX2UkSiQUtQ66o30WA_270.JPG: 480x640 (no detections), 302.0ms
Speed: 1.1ms preprocess, 302.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3SMsX5oo5ESPv4JiIkyTQ_0.JPG: 480x640 (no detections), 301.9ms
Speed: 1.2ms preprocess, 301.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3SMsX5oo5ESPv4JiIkyTQ_90.JPG: 480x640 (no detections), 302.8ms
Speed: 1.2ms preprocess, 302.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3SMsX5oo5ESPv4JiIkyTQ_180.JPG: 480x640 1 Waste, 300.1ms
Speed: 1.2ms preprocess, 300.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3SMsX5oo5ESPv4JiIkyTQ_270.JPG: 480x640 (no detections), 300.1ms
Speed: 1.4ms preprocess, 300.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3UT_OsMbQzmx976GVlacQ_0.JPG: 480x640 (no detections), 301.3ms
Speed: 1.2ms preprocess, 301.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3UT_OsMbQzmx976GVlacQ_90.JPG: 480x640 (no detections), 305.3ms
Speed: 1.2ms preprocess, 305.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3UT_OsMbQzmx976GVlacQ_180.JPG: 480x640 (no detections), 299.9ms
Speed: 1.3ms preprocess, 299.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3UT_OsMbQzmx976GVlacQ_270.JPG: 480x640 (no detections), 303.8ms
Speed: 1.2ms preprocess, 303.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3XDHUX81vffZNSIKZRt4w_0.JPG: 480x640 (no detections), 294.2ms
Speed: 1.4ms preprocess, 294.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3XDHUX81vffZNSIKZRt4w_90.JPG: 480x640 (no detections), 297.4ms
Speed: 1.2ms preprocess, 297.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3XDHUX81vffZNSIKZRt4w_180.JPG: 480x640 1 Waste, 296.7ms
Speed: 1.0ms preprocess, 296.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3XDHUX81vffZNSIKZRt4w_270.JPG: 480x640 (no detections), 302.9ms
Speed: 1.3ms preprocess, 302.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3Y3OSD7PKUniIGOdBKnbA_0.JPG: 480x640 (no detections), 293.0ms
Speed: 1.1ms preprocess, 293.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3Y3OSD7PKUniIGOdBKnbA_90.JPG: 480x640 (no detections), 289.4ms
Speed: 1.2ms preprocess, 289.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3Y3OSD7PKUniIGOdBKnbA_180.JPG: 480x640 (no detections), 298.7ms
Speed: 1.3ms preprocess, 298.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3Y3OSD7PKUniIGOdBKnbA_270.JPG: 480x640 (no detections), 293.7ms
Speed: 1.2ms preprocess, 293.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3ZOqsgdTIQSzyBRCSqJiA_0.JPG: 480x640 (no detections), 304.7ms
Speed: 1.3ms preprocess, 304.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3ZOqsgdTIQSzyBRCSqJiA_90.JPG: 480x640 (no detections), 304.4ms
Speed: 1.3ms preprocess, 304.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3ZOqsgdTIQSzyBRCSqJiA_180.JPG: 480x640 (no detections), 297.9ms

Speed: 1.2ms preprocess, 297.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3ZOqsgdTIQSzyBRCSqJiA_270.JPG: 480x640 (no detections), 304.4ms
Speed: 1.1ms preprocess, 304.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3gaqYySj9VoyzqW0zhdXg_0.JPG: 480x640 (no detections), 300.2ms
Speed: 1.2ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3gaqYySj9VoyzqW0zhdXg_90.JPG: 480x640 (no detections), 299.2ms
Speed: 1.1ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3gaqYySj9VoyzqW0zhdXg_180.JPG: 480x640 (no detections), 299.8ms
Speed: 1.2ms preprocess, 299.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3gaqYySj9VoyzqW0zhdXg_270.JPG: 480x640 (no detections), 296.9ms
Speed: 1.2ms preprocess, 296.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3gg5E0ytEgMt2svA440IQ_0.JPG: 480x640 (no detections), 297.1ms
Speed: 1.3ms preprocess, 297.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3gg5E0ytEgMt2svA440IQ_90.JPG: 480x640 (no detections), 296.8ms
Speed: 1.3ms preprocess, 296.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3gg5E0ytEgMt2svA440IQ_180.JPG: 480x640 (no detections), 295.4ms
Speed: 1.1ms preprocess, 295.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3gg5E0ytEgMt2svA440IQ_270.JPG: 480x640 (no detections), 302.2ms
Speed: 1.2ms preprocess, 302.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3i5jQMWWF8qaHzparMshQ_0.JPG: 480x640 (no detections), 297.2ms
Speed: 1.2ms preprocess, 297.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3i5jQMWWF8qaHzparMshQ_90.JPG: 480x640 (no detections), 305.0ms
Speed: 1.1ms preprocess, 305.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3i5jQMWWF8qaHzparMshQ_180.JPG: 480x640 (no detections), 300.1ms
Speed: 1.7ms preprocess, 300.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3i5jQMWWF8qaHzparMshQ_270.JPG: 480x640 (no detections), 301.5ms
Speed: 1.4ms preprocess, 301.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3o6J7JF3Kxv8oqRcUVljg_0.JPG: 480x640 (no detections), 306.8ms
Speed: 1.1ms preprocess, 306.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3o6J7JF3Kxv8oqRcUVljg_90.JPG: 480x640 (no detections), 299.0ms
Speed: 1.3ms preprocess, 299.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3o6J7JF3Kxv8oqRcUVljg_180.JPG: 480x640 (no detections), 301.1ms
Speed: 1.2ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3o6J7JF3Kxv8oqRcUVljg_270.JPG: 480x640 (no detections), 301.5ms
Speed: 1.3ms preprocess, 301.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3qROu5kCZK333atmHSfFQ_0.JPG: 480x640 (no detections), 298.4ms
Speed: 1.1ms preprocess, 298.4ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3qROu5kCZK333atmHSfFQ_90.JPG: 480x640 (no detections), 296.8ms
Speed: 1.2ms preprocess, 296.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3qROu5kCZK333atmHSfFQ_180.JPG: 480x640 (no detections), 302.8ms
Speed: 1.2ms preprocess, 302.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3qROu5kCZK333atmHSfFQ_270.JPG: 480x640 (no detections), 294.8ms
Speed: 1.2ms preprocess, 294.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3tPHgdhD5JXm6VMmxGNEg_0.JPG: 480x640 (no detections), 293.0ms
Speed: 1.7ms preprocess, 293.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3tPHgdhD5JXm6VMmxGNEg_90.JPG: 480x640 (no detections), 301.5ms
Speed: 1.3ms preprocess, 301.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3tPHgdhD5JXm6VMmxGNEg_180.JPG: 480x640 (no detections), 300.3ms
Speed: 1.2ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3tPHgdhD5JXm6VMmxGNEg_270.JPG: 480x640 1 Waste, 299.7ms
Speed: 1.2ms preprocess, 299.7ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3yRTZjULJNJ9uCcE1wzeA_0.JPG: 480x640 (no detections), 299.2ms
Speed: 1.3ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3yRTZjULJNJ9uCcE1wzeA_90.JPG: 480x640 (no detections), 298.5ms
Speed: 1.3ms preprocess, 298.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3yRTZjULJNJ9uCcE1wzeA_180.JPG: 480x640 (no detections), 300.1ms
Speed: 1.2ms preprocess, 300.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/3/x3yRTZjULJNJ9uCcE1wzeA_270.JPG: 480x640 (no detections), 298.6ms
Speed: 1.3ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x41SHZyuRJat0RZrgkjr-g_0.JPG: 480x640 (no detections), 305.4ms
Speed: 1.3ms preprocess, 305.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x41SHZyuRJat0RZrgkjr-g_90.JPG: 480x640 (no detections), 298.2ms
Speed: 1.1ms preprocess, 298.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x41SHZyuRJat0RZrgkjr-g_180.JPG: 480x640 (no detections), 298.6ms
Speed: 1.1ms preprocess, 298.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x41SHZyuRJat0RZrgkjr-g_270.JPG: 480x640 (no detections), 299.9ms
Speed: 1.2ms preprocess, 299.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x41d_SeMErYSvNc0SvE_jA_0.JPG: 480x640 (no detections), 298.0ms
Speed: 1.1ms preprocess, 298.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x41d_SeMErYSvNc0SvE_jA_90.JPG: 480x640 (no detections), 296.8ms
Speed: 1.1ms preprocess, 296.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x41d_SeMErYSvNc0SvE_jA_180.JPG: 480x640 (no detections), 304.4ms
Speed: 1.4ms preprocess, 304.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x41d_SeMErYSvNc0SvE_jA_270.JPG: 480x640 (no detections), 299.2ms
Speed: 1.1ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x43eEmgfcHE0N-qpe8zjEw_0.JPG: 480x640 (no detections), 301.7ms
Speed: 1.7ms preprocess, 301.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x43eEmgfcHE0N-qpe8zjEw_90.JPG: 480x640 (no detections), 302.2ms
Speed: 1.1ms preprocess, 302.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x43eEmgfcHE0N-qpe8zjEw_180.JPG: 480x640 (no detections), 300.1ms
Speed: 1.3ms preprocess, 300.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x43eEmgfcHE0N-qpe8zjEw_270.JPG: 480x640 (no detections), 293.7ms
Speed: 1.4ms preprocess, 293.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x44vKOXwPqKkUAcZi3tl8A_0.JPG: 480x640 (no detections), 302.4ms
Speed: 1.4ms preprocess, 302.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x44vKOXwPqKkUAcZi3tl8A_90.JPG: 480x640 (no detections), 305.5ms
Speed: 1.4ms preprocess, 305.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x44vKOXwPqKkUAcZi3tl8A_180.JPG: 480x640 (no detections), 301.8ms
Speed: 1.3ms preprocess, 301.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x44vKOXwPqKkUAcZi3tl8A_270.JPG: 480x640 (no detections), 302.7ms
Speed: 1.2ms preprocess, 302.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x45T-RSsMg5s5efwRgy-dA_0.JPG: 480x640 (no detections), 295.6ms
Speed: 2.0ms preprocess, 295.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x45T-RSsMg5s5efwRgy-dA_90.JPG: 480x640 (no detections), 301.0ms
Speed: 1.3ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x45T-RSsMg5s5efwRgy-dA_180.JPG: 480x640 (no detections), 307.6ms
Speed: 1.2ms preprocess, 307.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x45T-RSsMg5s5efwRgy-dA_270.JPG: 480x640 (no detections), 297.8ms
Speed: 1.3ms preprocess, 297.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x46KXuUNitmIQ67f6LSHgg_0.JPG: 480x640 (no detections), 305.9ms
Speed: 1.8ms preprocess, 305.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x46KXuUNitmIQ67f6LSHgg_90.JPG: 480x640 (no detections), 294.7ms
Speed: 1.2ms preprocess, 294.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x46KXuUNitmIQ67f6LSHgg_180.JPG: 480x640 (no detections), 295.2ms
Speed: 1.1ms preprocess, 295.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x46KXuUNitmIQ67f6LSHgg_270.JPG: 480x640 (no detections), 296.4ms
Speed: 1.3ms preprocess, 296.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x47mIsfhZ7oPD03Qob7Ddw_0.JPG: 480x640 (no detections), 297.1ms
Speed: 1.1ms preprocess, 297.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x47mIsfhZ7oPD03Qob7Ddw_90.JPG: 480x640 (no detections), 302.0ms
Speed: 1.2ms preprocess, 302.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x47mIsfhZ7oPD03Qob7Ddw_180.JPG: 480x640 (no detections), 302.6ms
Speed: 1.1ms preprocess, 302.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x47mIsfhZ7oPD03Qob7Ddw_270.JPG: 480x640 (no detections), 303.8ms
Speed: 1.3ms preprocess, 303.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x49Lxxhhx9wpL0Mn3R_4iw_0.JPG: 480x640 (no detections), 299.3ms
Speed: 1.1ms preprocess, 299.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x49Lxxhhx9wpL0Mn3R_4iw_90.JPG: 480x640 (no detections), 297.7ms
Speed: 1.1ms preprocess, 297.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x49Lxxhhx9wpL0Mn3R_4iw_180.JPG: 480x640 (no detections), 299.2ms
Speed: 1.0ms preprocess, 299.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x49Lxxhhx9wpL0Mn3R_4iw_270.JPG: 480x640 (no detections), 300.9ms
Speed: 1.1ms preprocess, 300.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4CZweqtxZHrShA1aLoBkw_0.JPG: 480x640 (no detections), 298.9ms
Speed: 1.0ms preprocess, 298.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4CZweqtxZHrShA1aLoBkw_90.JPG: 480x640 (no detections), 303.9ms
Speed: 1.1ms preprocess, 303.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4CZweqtxZHrShA1aLoBkw_180.JPG: 480x640 (no detections), 306.3ms
Speed: 1.2ms preprocess, 306.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4CZweqtxZHrShA1aLoBkw_270.JPG: 480x640 (no detections), 299.2ms
Speed: 2.0ms preprocess, 299.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4DraOHL2eqHY_FC5OL0Ug_0.JPG: 480x640 (no detections), 302.1ms
Speed: 1.1ms preprocess, 302.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4DraOHL2eqHY_FC5OL0Ug_90.JPG: 480x640 (no detections), 295.8ms

Speed: 1.1ms preprocess, 295.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4DraOHL2eqHY_FC5OL0Ug_180.JPG: 480x640 (no detections), 301.0ms
Speed: 1.1ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4DraOHL2eqHY_FC5OL0Ug_270.JPG: 480x640 (no detections), 303.0ms
Speed: 1.2ms preprocess, 303.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4F8OAUpufLvLo4f-7HMbw_0.JPG: 480x640 (no detections), 303.0ms
Speed: 1.6ms preprocess, 303.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4F8OAUpufLvLo4f-7HMbw_90.JPG: 480x640 (no detections), 296.2ms
Speed: 1.2ms preprocess, 296.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4F8OAUpufLvLo4f-7HMbw_180.JPG: 480x640 (no detections), 302.1ms
Speed: 2.4ms preprocess, 302.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4F8OAUpufLvLo4f-7HMbw_270.JPG: 480x640 (no detections), 301.0ms
Speed: 1.1ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4G7lfHX4hdw-h9u5RYbOg_0.JPG: 480x640 (no detections), 302.8ms
Speed: 1.1ms preprocess, 302.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4G7lfHX4hdw-h9u5RYbOg_90.JPG: 480x640 (no detections), 297.1ms
Speed: 1.2ms preprocess, 297.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4G7lfHX4hdw-h9u5RYbOg_180.JPG: 480x640 (no detections), 297.8ms
Speed: 1.2ms preprocess, 297.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4G7lfHX4hdw-h9u5RYbOg_270.JPG: 480x640 1 Waste, 305.1ms
Speed: 1.4ms preprocess, 305.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4PHWN7-VW52h3QOOox0FA_0.JPG: 480x640 (no detections), 301.7ms
Speed: 1.3ms preprocess, 301.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4PHWN7-VW52h3QOOox0FA_90.JPG: 480x640 (no detections), 301.0ms
Speed: 1.0ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4PHWN7-VW52h3QOOox0FA_180.JPG: 480x640 (no detections), 300.2ms
Speed: 1.5ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4PHWN7-VW52h3QOOox0FA_270.JPG: 480x640 (no detections), 297.6ms
Speed: 1.3ms preprocess, 297.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4SHQmL6zxZ6ms36db0C2g_0.JPG: 480x640 (no detections), 294.0ms
Speed: 1.5ms preprocess, 294.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4SHQmL6zxZ6ms36db0C2g_90.JPG: 480x640 (no detections), 297.9ms
Speed: 1.3ms preprocess, 297.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4SHQmL6zxZ6ms36db0C2g_180.JPG: 480x640 (no detections), 301.2ms
Speed: 1.3ms preprocess, 301.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4SHQmL6zxZ6ms36db0C2g_270.JPG: 480x640 (no detections), 303.5ms
Speed: 1.2ms preprocess, 303.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4WY3oKEcuWO3ovBqTugoQ_0.JPG: 480x640 (no detections), 315.0ms
Speed: 1.4ms preprocess, 315.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4WY3oKEcuWO3ovBqTugoQ_90.JPG: 480x640 (no detections), 301.5ms
Speed: 1.1ms preprocess, 301.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4WY3oKEcuWO3ovBqTugoQ_180.JPG: 480x640 (no detections), 307.0ms
Speed: 1.2ms preprocess, 307.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4WY3oKEcuWO3ovBqTugoQ_270.JPG: 480x640 (no detections), 298.2ms
Speed: 1.1ms preprocess, 298.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4WfWkoh0PxeRNBI-npZhg_0.JPG: 480x640 (no detections), 306.8ms
Speed: 1.2ms preprocess, 306.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4WfWkoh0PxeRNBI-npZhg_90.JPG: 480x640 (no detections), 305.6ms
Speed: 1.2ms preprocess, 305.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4WfWkoh0PxeRNBI-npZhg_180.JPG: 480x640 (no detections), 306.9ms
Speed: 1.1ms preprocess, 306.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4WfWkoh0PxeRNBI-npZhg_270.JPG: 480x640 (no detections), 304.8ms
Speed: 1.3ms preprocess, 304.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4a58b3rq52o045p7Aa36w_0.JPG: 480x640 (no detections), 296.7ms
Speed: 1.2ms preprocess, 296.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4a58b3rq52o045p7Aa36w_90.JPG: 480x640 (no detections), 306.5ms
Speed: 1.2ms preprocess, 306.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4a58b3rq52o045p7Aa36w_180.JPG: 480x640 (no detections), 304.7ms
Speed: 1.2ms preprocess, 304.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4a58b3rq52o045p7Aa36w_270.JPG: 480x640 (no detections), 355.8ms
Speed: 1.2ms preprocess, 355.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4a6kyT7CddBcdpnpeM3BQ_0.JPG: 480x640 (no detections), 466.3ms
Speed: 1.8ms preprocess, 466.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4a6kyT7CddBcdpnpeM3BQ_90.JPG: 480x640 (no detections), 299.3ms
Speed: 1.1ms preprocess, 299.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4a6kyT7CddBcdpnpeM3BQ_180.JPG: 480x640 (no detections), 306.9ms
Speed: 1.3ms preprocess, 306.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4a6kyT7CddBcdpnpeM3BQ_270.JPG: 480x640 (no detections), 296.9ms
Speed: 1.1ms preprocess, 296.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4hCJ-N_vWh5qkDXY4qtxQ_0.JPG: 480x640 (no detections), 299.4ms
Speed: 1.1ms preprocess, 299.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4hCJ-N_vWh5qkDXY4qtxQ_90.JPG: 480x640 (no detections), 303.8ms
Speed: 1.5ms preprocess, 303.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4hCJ-N_vWh5qkDXY4qtxQ_180.JPG: 480x640 (no detections), 302.6ms
Speed: 1.1ms preprocess, 302.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4hCJ-N_vWh5qkDXY4qtxQ_270.JPG: 480x640 (no detections), 296.7ms
Speed: 1.5ms preprocess, 296.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4jAGX9fXfW1OJejkKzCVQ_0.JPG: 480x640 (no detections), 299.9ms
Speed: 1.4ms preprocess, 299.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4jAGX9fXfW1OJejkKzCVQ_90.JPG: 480x640 (no detections), 299.1ms
Speed: 1.2ms preprocess, 299.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4jAGX9fXfW1OJejkKzCVQ_180.JPG: 480x640 (no detections), 299.7ms
Speed: 1.3ms preprocess, 299.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4jAGX9fXfW1OJejkKzCVQ_270.JPG: 480x640 (no detections), 295.6ms
Speed: 1.2ms preprocess, 295.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4nFzrEWZ11VQT3E7KFtjw_0.JPG: 480x640 (no detections), 294.9ms
Speed: 1.2ms preprocess, 294.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4nFzrEWZ11VQT3E7KFtjw_90.JPG: 480x640 (no detections), 295.7ms
Speed: 1.1ms preprocess, 295.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4nFzrEWZ11VQT3E7KFtjw_180.JPG: 480x640 (no detections), 295.5ms
Speed: 1.1ms preprocess, 295.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4nFzrEWZ11VQT3E7KFtjw_270.JPG: 480x640 (no detections), 290.8ms
Speed: 1.1ms preprocess, 290.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4oqaKRVClPMfyPSJWvSvw_0.JPG: 480x640 (no detections), 289.0ms
Speed: 1.2ms preprocess, 289.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4oqaKRVClPMfyPSJWvSvw_90.JPG: 480x640 (no detections), 299.2ms
Speed: 1.4ms preprocess, 299.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4oqaKRVClPMfyPSJWvSvw_180.JPG: 480x640 (no detections), 298.1ms
Speed: 1.2ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4oqaKRVClPMfyPSJWvSvw_270.JPG: 480x640 (no detections), 300.7ms
Speed: 1.1ms preprocess, 300.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4xDHNjfZvP3KxB_9xt1TA_0.JPG: 480x640 (no detections), 296.5ms
Speed: 1.0ms preprocess, 296.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4xDHNjfZvP3KxB_9xt1TA_90.JPG: 480x640 (no detections), 298.9ms
Speed: 1.1ms preprocess, 298.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4xDHNjfZvP3KxB_9xt1TA_180.JPG: 480x640 (no detections), 296.7ms
Speed: 1.3ms preprocess, 296.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/4/x4xDHNjfZvP3KxB_9xt1TA_270.JPG: 480x640 (no detections), 295.9ms
Speed: 1.3ms preprocess, 295.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5-zqIya-UGXC6wawAbFaQ_0.JPG: 480x640 (no detections), 297.3ms
Speed: 1.1ms preprocess, 297.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5-zqIya-UGXC6wawAbFaQ_90.JPG: 480x640 (no detections), 296.7ms
Speed: 1.4ms preprocess, 296.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5-zqIya-UGXC6wawAbFaQ_180.JPG: 480x640 (no detections), 298.0ms
Speed: 1.1ms preprocess, 298.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5-zqIya-UGXC6wawAbFaQ_270.JPG: 480x640 (no detections), 298.9ms
Speed: 1.2ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x51iG-1ZFRgPtiwPxxRDIA_0.JPG: 480x640 (no detections), 300.9ms
Speed: 1.1ms preprocess, 300.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x51iG-1ZFRgPtiwPxxRDIA_90.JPG: 480x640 (no detections), 299.7ms
Speed: 1.1ms preprocess, 299.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x51iG-1ZFRgPtiwPxxRDIA_180.JPG: 480x640 (no detections), 296.3ms
Speed: 1.3ms preprocess, 296.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x51iG-1ZFRgPtiwPxxRDIA_270.JPG: 480x640 (no detections), 301.5ms
Speed: 1.2ms preprocess, 301.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x52G_in9C3lhv3vTFfaOtw_0.JPG: 480x640 (no detections), 296.9ms
Speed: 1.3ms preprocess, 296.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x52G_in9C3lhv3vTFfaOtw_90.JPG: 480x640 (no detections), 301.0ms
Speed: 1.8ms preprocess, 301.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x52G_in9C3lhv3vTFfaOtw_180.JPG: 480x640 (no detections), 296.2ms
Speed: 1.2ms preprocess, 296.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x52G_in9C3lhv3vTFfaOtw_270.JPG: 480x640 (no detections), 295.6ms
Speed: 1.2ms preprocess, 295.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x588diUgxDNKODWP7aCOQg_0.JPG: 480x640 (no detections), 301.4ms

Speed: 1.3ms preprocess, 301.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x588diUgxDNKODWP7aCOQg_90.JPG: 480x640 (no detections), 298.8ms
Speed: 1.2ms preprocess, 298.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x588diUgxDNKODWP7aCOQg_180.JPG: 480x640 (no detections), 297.8ms
Speed: 1.2ms preprocess, 297.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x588diUgxDNKODWP7aCOQg_270.JPG: 480x640 (no detections), 292.9ms
Speed: 1.1ms preprocess, 292.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x59Xy9FaxKUCt-YcbMg6Yw_0.JPG: 480x640 (no detections), 297.3ms
Speed: 1.2ms preprocess, 297.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x59Xy9FaxKUCt-YcbMg6Yw_90.JPG: 480x640 (no detections), 299.6ms
Speed: 1.2ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x59Xy9FaxKUCt-YcbMg6Yw_180.JPG: 480x640 (no detections), 295.7ms
Speed: 1.3ms preprocess, 295.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x59Xy9FaxKUCt-YcbMg6Yw_270.JPG: 480x640 (no detections), 295.1ms
Speed: 1.3ms preprocess, 295.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5D3s-I6C3Q_UnzwtM2zuw_0.JPG: 480x640 (no detections), 303.7ms
Speed: 1.2ms preprocess, 303.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5D3s-I6C3Q_UnzwtM2zuw_90.JPG: 480x640 (no detections), 296.9ms
Speed: 1.3ms preprocess, 296.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5D3s-I6C3Q_UnzwtM2zuw_180.JPG: 480x640 (no detections), 299.7ms
Speed: 1.1ms preprocess, 299.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5D3s-I6C3Q_UnzwtM2zuw_270.JPG: 480x640 (no detections), 297.1ms
Speed: 1.1ms preprocess, 297.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5DrirqjI5Ro7eFZzWuNmw_0.JPG: 480x640 (no detections), 297.0ms
Speed: 1.0ms preprocess, 297.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5DrirqjI5Ro7eFZzWuNmw_90.JPG: 480x640 (no detections), 299.5ms
Speed: 1.1ms preprocess, 299.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5DrirqjI5Ro7eFZzWuNmw_180.JPG: 480x640 (no detections), 295.6ms
Speed: 1.1ms preprocess, 295.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5DrirqjI5Ro7eFZzWuNmw_270.JPG: 480x640 (no detections), 298.3ms
Speed: 1.1ms preprocess, 298.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5G3zqPh69nKUQjvV6i7Ag_0.JPG: 480x640 (no detections), 300.4ms
Speed: 1.0ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5G3zqPh69nKUQjvV6i7Ag_90.JPG: 480x640 (no detections), 292.1ms
Speed: 1.2ms preprocess, 292.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5G3zqPh69nKUQjvV6i7Ag_180.JPG: 480x640 (no detections), 301.8ms
Speed: 1.0ms preprocess, 301.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5G3zqPh69nKUQjvV6i7Ag_270.JPG: 480x640 2 Wastes, 302.7ms
Speed: 1.5ms preprocess, 302.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5HhCjpfvWGdnJgn-Je_bQ_0.JPG: 480x640 (no detections), 298.7ms
Speed: 1.2ms preprocess, 298.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5HhCjpfvWGdnJgn-Je_bQ_90.JPG: 480x640 (no detections), 306.5ms
Speed: 1.2ms preprocess, 306.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5HhCjpfvWGdnJgn-Je_bQ_180.JPG: 480x640 (no detections), 301.3ms
Speed: 1.1ms preprocess, 301.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5HhCjpfvWGdnJgn-Je_bQ_270.JPG: 480x640 (no detections), 295.6ms
Speed: 1.2ms preprocess, 295.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5HiugSHwHLNjr0eaPnvkg_0.JPG: 480x640 (no detections), 298.6ms
Speed: 1.0ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5HiugSHwHLNjr0eaPnvkg_90.JPG: 480x640 (no detections), 300.0ms
Speed: 1.3ms preprocess, 300.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5HiugSHwHLNjr0eaPnvkg_180.JPG: 480x640 (no detections), 302.0ms
Speed: 1.2ms preprocess, 302.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5HiugSHwHLNjr0eaPnvkg_270.JPG: 480x640 (no detections), 297.8ms
Speed: 1.1ms preprocess, 297.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5LG3lIpYwdyCP69Kt_R5w_0.JPG: 480x640 (no detections), 298.2ms
Speed: 1.1ms preprocess, 298.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5LG3lIpYwdyCP69Kt_R5w_90.JPG: 480x640 (no detections), 294.5ms
Speed: 1.1ms preprocess, 294.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5LG3lIpYwdyCP69Kt_R5w_180.JPG: 480x640 1 Waste, 295.9ms
Speed: 1.2ms preprocess, 295.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5LG3lIpYwdyCP69Kt_R5w_270.JPG: 480x640 (no detections), 302.0ms
Speed: 1.4ms preprocess, 302.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5UQGzi8EnrqFEVgiqYtGw_0.JPG: 480x640 (no detections), 297.6ms
Speed: 1.2ms preprocess, 297.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5UQGzi8EnrqFEVgiqYtGw_90.JPG: 480x640 (no detections), 303.5ms
Speed: 1.2ms preprocess, 303.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5UQGzi8EnrqFEVgiqYtGw_180.JPG: 480x640 (no detections), 306.0ms
Speed: 1.2ms preprocess, 306.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5UQGzi8EnrqFEVgiqYtGw_270.JPG: 480x640 (no detections), 301.0ms
Speed: 1.0ms preprocess, 301.0ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5Z2h010qrxtDmpg-PAopw_0.JPG: 480x640 (no detections), 300.2ms
Speed: 1.3ms preprocess, 300.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5Z2h010qrxtDmpg-PAopw_90.JPG: 480x640 (no detections), 298.9ms
Speed: 1.2ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5Z2h010qrxtDmpg-PAopw_180.JPG: 480x640 (no detections), 296.9ms
Speed: 1.9ms preprocess, 296.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5Z2h010qrxtDmpg-PAopw_270.JPG: 480x640 (no detections), 299.1ms
Speed: 1.2ms preprocess, 299.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5_IJJA33goBXGpximsd2Q_0.JPG: 480x640 (no detections), 300.6ms
Speed: 1.1ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5_IJJA33goBXGpximsd2Q_90.JPG: 480x640 (no detections), 297.3ms
Speed: 1.3ms preprocess, 297.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5_IJJA33goBXGpximsd2Q_180.JPG: 480x640 (no detections), 299.1ms
Speed: 1.4ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5_IJJA33goBXGpximsd2Q_270.JPG: 480x640 (no detections), 297.5ms
Speed: 1.6ms preprocess, 297.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5_vbB7OoazD5KJGjxspng_0.JPG: 480x640 1 Waste, 295.2ms
Speed: 1.1ms preprocess, 295.2ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5_vbB7OoazD5KJGjxspng_90.JPG: 480x640 1 Waste, 302.3ms
Speed: 1.4ms preprocess, 302.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5_vbB7OoazD5KJGjxspng_180.JPG: 480x640 (no detections), 300.7ms
Speed: 1.2ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5_vbB7OoazD5KJGjxspng_270.JPG: 480x640 (no detections), 304.5ms
Speed: 1.4ms preprocess, 304.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5bIKysecuTKnPjZ8bRrDw_0.JPG: 480x640 (no detections), 310.6ms
Speed: 1.1ms preprocess, 310.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5bIKysecuTKnPjZ8bRrDw_90.JPG: 480x640 (no detections), 302.1ms
Speed: 1.1ms preprocess, 302.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5bIKysecuTKnPjZ8bRrDw_180.JPG: 480x640 (no detections), 299.7ms
Speed: 1.2ms preprocess, 299.7ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5bIKysecuTKnPjZ8bRrDw_270.JPG: 480x640 (no detections), 299.2ms
Speed: 1.3ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5cU3fhQfQbdSpCv6FsgIA_0.JPG: 480x640 (no detections), 301.5ms
Speed: 1.4ms preprocess, 301.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5cU3fhQfQbdSpCv6FsgIA_90.JPG: 480x640 (no detections), 290.1ms
Speed: 1.1ms preprocess, 290.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5cU3fhQfQbdSpCv6FsgIA_180.JPG: 480x640 (no detections), 299.8ms
Speed: 1.3ms preprocess, 299.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5cU3fhQfQbdSpCv6FsgIA_270.JPG: 480x640 (no detections), 297.5ms
Speed: 1.4ms preprocess, 297.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5dI1BbFlzD4MeI2pUQwEA_0.JPG: 480x640 (no detections), 296.7ms
Speed: 1.1ms preprocess, 296.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5dI1BbFlzD4MeI2pUQwEA_90.JPG: 480x640 (no detections), 295.1ms
Speed: 1.2ms preprocess, 295.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5dI1BbFlzD4MeI2pUQwEA_180.JPG: 480x640 (no detections), 293.3ms
Speed: 1.2ms preprocess, 293.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5dI1BbFlzD4MeI2pUQwEA_270.JPG: 480x640 (no detections), 291.0ms
Speed: 1.1ms preprocess, 291.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5i71tb5pMvsNDO_Dy0y0g_0.JPG: 480x640 (no detections), 295.7ms
Speed: 1.5ms preprocess, 295.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5i71tb5pMvsNDO_Dy0y0g_90.JPG: 480x640 (no detections), 302.9ms
Speed: 1.2ms preprocess, 302.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5i71tb5pMvsNDO_Dy0y0g_180.JPG: 480x640 (no detections), 301.9ms
Speed: 1.2ms preprocess, 301.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5i71tb5pMvsNDO_Dy0y0g_270.JPG: 480x640 (no detections), 297.0ms
Speed: 1.0ms preprocess, 297.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5r0P9_2iLliDzzrLmLN7w_0.JPG: 480x640 (no detections), 298.4ms
Speed: 1.1ms preprocess, 298.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5r0P9_2iLliDzzrLmLN7w_90.JPG: 480x640 (no detections), 303.4ms
Speed: 1.2ms preprocess, 303.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5r0P9_2iLliDzzrLmLN7w_180.JPG: 480x640 (no detections), 300.0ms
Speed: 1.4ms preprocess, 300.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5r0P9_2iLliDzzrLmLN7w_270.JPG: 480x640 (no detections), 298.5ms

Speed: 1.2ms preprocess, 298.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5vXEEyRR0L5DAl6dqXrcA_0.JPG: 480x640 (no detections), 301.0ms
Speed: 1.3ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5vXEEyRR0L5DAl6dqXrcA_90.JPG: 480x640 (no detections), 303.8ms
Speed: 1.0ms preprocess, 303.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5vXEEyRR0L5DAl6dqXrcA_180.JPG: 480x640 (no detections), 298.4ms
Speed: 1.1ms preprocess, 298.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5vXEEyRR0L5DAl6dqXrcA_270.JPG: 480x640 (no detections), 298.4ms
Speed: 1.0ms preprocess, 298.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5vfgM_pwFKZcfWgp7qisQ_0.JPG: 480x640 (no detections), 303.8ms
Speed: 1.0ms preprocess, 303.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5vfgM_pwFKZcfWgp7qisQ_90.JPG: 480x640 1 Waste, 298.0ms
Speed: 1.4ms preprocess, 298.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5vfgM_pwFKZcfWgp7qisQ_180.JPG: 480x640 (no detections), 304.1ms
Speed: 1.1ms preprocess, 304.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/5/x5vfgM_pwFKZcfWgp7qisQ_270.JPG: 480x640 (no detections), 301.7ms
Speed: 1.3ms preprocess, 301.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x60nbE_hSTfBP5BM4VpXdQ_0.JPG: 480x640 1 Waste, 294.8ms
Speed: 1.1ms preprocess, 294.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x60nbE_hSTfBP5BM4VpXdQ_90.JPG: 480x640 (no detections), 300.3ms
Speed: 1.0ms preprocess, 300.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x60nbE_hSTfBP5BM4VpXdQ_180.JPG: 480x640 (no detections), 285.5ms
Speed: 1.2ms preprocess, 285.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x60nbE_hSTfBP5BM4VpXdQ_270.JPG: 480x640 (no detections), 300.6ms
Speed: 1.2ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x61HDNpVfMXw_TpecDACfQ_0.JPG: 480x640 (no detections), 297.2ms
Speed: 1.3ms preprocess, 297.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x61HDNpVfMXw_TpecDACfQ_90.JPG: 480x640 (no detections), 296.4ms
Speed: 1.3ms preprocess, 296.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x61HDNpVfMXw_TpecDACfQ_180.JPG: 480x640 (no detections), 300.2ms
Speed: 1.4ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x61HDNpVfMXw_TpecDACfQ_270.JPG: 480x640 (no detections), 300.4ms
Speed: 1.4ms preprocess, 300.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x63_iBrBrQYiR-9PQogPkQ_0.JPG: 480x640 (no detections), 300.3ms
Speed: 1.1ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x63_iBrBrQYiR-9PQogPkQ_90.JPG: 480x640 (no detections), 299.0ms
Speed: 1.3ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x63_iBrBrQYiR-9PQogPkQ_180.JPG: 480x640 (no detections), 298.0ms
Speed: 1.2ms preprocess, 298.0ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x63_iBrBrQYiR-9PQogPkQ_270.JPG: 480x640 (no detections), 301.5ms
Speed: 1.2ms preprocess, 301.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x65MwJ8z372Fmo1sWln-Tg_0.JPG: 480x640 (no detections), 295.7ms
Speed: 2.3ms preprocess, 295.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x65MwJ8z372Fmo1sWln-Tg_90.JPG: 480x640 (no detections), 299.6ms
Speed: 1.3ms preprocess, 299.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x65MwJ8z372Fmo1sWln-Tg_180.JPG: 480x640 (no detections), 299.0ms
Speed: 1.2ms preprocess, 299.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x65MwJ8z372Fmo1sWln-Tg_270.JPG: 480x640 (no detections), 296.0ms
Speed: 1.3ms preprocess, 296.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6BFyfRawgRgF1QUjh_vxA_0.JPG: 480x640 (no detections), 296.4ms
Speed: 1.1ms preprocess, 296.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6BFyfRawgRgF1QUjh_vxA_90.JPG: 480x640 (no detections), 297.4ms
Speed: 1.2ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6BFyfRawgRgF1QUjh_vxA_180.JPG: 480x640 (no detections), 293.6ms
Speed: 1.1ms preprocess, 293.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6BFyfRawgRgF1QUjh_vxA_270.JPG: 480x640 (no detections), 298.0ms
Speed: 1.2ms preprocess, 298.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6BbUIg0AWLGI3w3tBtlCQ_0.JPG: 480x640 (no detections), 297.8ms
Speed: 1.3ms preprocess, 297.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6BbUIg0AWLGI3w3tBtlCQ_90.JPG: 480x640 (no detections), 300.1ms
Speed: 1.1ms preprocess, 300.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6BbUIg0AWLGI3w3tBtlCQ_180.JPG: 480x640 (no detections), 299.1ms
Speed: 1.2ms preprocess, 299.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6BbUIg0AWLGI3w3tBtlCQ_270.JPG: 480x640 (no detections), 306.2ms
Speed: 1.2ms preprocess, 306.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6C2OK5z2WZAPzwMMEY9Fw_0.JPG: 480x640 (no detections), 300.2ms
Speed: 1.1ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6C2OK5z2WZAPzwMMEY9Fw_90.JPG: 480x640 (no detections), 305.7ms
Speed: 1.2ms preprocess, 305.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6C2OK5z2WZAPzwMMEY9Fw_180.JPG: 480x640 (no detections), 299.3ms
Speed: 1.3ms preprocess, 299.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6C2OK5z2WZAPzwMMEY9Fw_270.JPG: 480x640 (no detections), 297.2ms
Speed: 1.2ms preprocess, 297.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6FraHYJoIlagPh8OI6Uug_0.JPG: 480x640 (no detections), 294.2ms
Speed: 1.7ms preprocess, 294.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6FraHYJoIlagPh8OI6Uug_90.JPG: 480x640 (no detections), 303.0ms
Speed: 1.2ms preprocess, 303.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6FraHYJoIlagPh8OI6Uug_180.JPG: 480x640 (no detections), 301.6ms
Speed: 1.3ms preprocess, 301.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6FraHYJoIlagPh8OI6Uug_270.JPG: 480x640 (no detections), 301.6ms
Speed: 1.1ms preprocess, 301.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6G53qR_vxPN2qIYwWcMfA_0.JPG: 480x640 (no detections), 296.6ms
Speed: 1.2ms preprocess, 296.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6G53qR_vxPN2qIYwWcMfA_90.JPG: 480x640 (no detections), 296.7ms
Speed: 1.2ms preprocess, 296.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6G53qR_vxPN2qIYwWcMfA_180.JPG: 480x640 (no detections), 301.7ms
Speed: 1.3ms preprocess, 301.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6G53qR_vxPN2qIYwWcMfA_270.JPG: 480x640 (no detections), 291.6ms
Speed: 1.1ms preprocess, 291.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6IRjdx59ZrNAODv-4gQyg_0.JPG: 480x640 (no detections), 297.7ms
Speed: 1.0ms preprocess, 297.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6IRjdx59ZrNAODv-4gQyg_90.JPG: 480x640 (no detections), 299.4ms
Speed: 1.9ms preprocess, 299.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6IRjdx59ZrNAODv-4gQyg_180.JPG: 480x640 (no detections), 298.7ms
Speed: 1.2ms preprocess, 298.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6IRjdx59ZrNAODv-4gQyg_270.JPG: 480x640 (no detections), 300.1ms
Speed: 1.3ms preprocess, 300.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6KeQelKRcS2XcIO2PyY3Q_0.JPG: 480x640 (no detections), 298.6ms
Speed: 1.3ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6KeQelKRcS2XcIO2PyY3Q_90.JPG: 480x640 (no detections), 303.3ms
Speed: 1.1ms preprocess, 303.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6KeQelKRcS2XcIO2PyY3Q_180.JPG: 480x640 (no detections), 295.4ms
Speed: 1.7ms preprocess, 295.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6KeQelKRcS2XcIO2PyY3Q_270.JPG: 480x640 (no detections), 297.0ms
Speed: 1.2ms preprocess, 297.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6Pvg6FSSA3cVJOzDmp96g_0.JPG: 480x640 (no detections), 297.5ms
Speed: 1.7ms preprocess, 297.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6Pvg6FSSA3cVJOzDmp96g_90.JPG: 480x640 (no detections), 300.7ms
Speed: 1.2ms preprocess, 300.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6Pvg6FSSA3cVJOzDmp96g_180.JPG: 480x640 (no detections), 296.2ms
Speed: 1.0ms preprocess, 296.2ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6Pvg6FSSA3cVJOzDmp96g_270.JPG: 480x640 (no detections), 298.7ms
Speed: 1.2ms preprocess, 298.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6RJ4ry4ZjF7QHuzKbQQSA_0.JPG: 480x640 (no detections), 298.0ms
Speed: 1.5ms preprocess, 298.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6RJ4ry4ZjF7QHuzKbQQSA_90.JPG: 480x640 (no detections), 298.4ms
Speed: 1.3ms preprocess, 298.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6RJ4ry4ZjF7QHuzKbQQSA_180.JPG: 480x640 1 Waste, 294.2ms
Speed: 1.1ms preprocess, 294.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6RJ4ry4ZjF7QHuzKbQQSA_270.JPG: 480x640 (no detections), 304.5ms
Speed: 1.2ms preprocess, 304.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6UuYPfJNmjUKdqw5M-uOw_0.JPG: 480x640 (no detections), 297.8ms
Speed: 1.1ms preprocess, 297.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6UuYPfJNmjUKdqw5M-uOw_90.JPG: 480x640 (no detections), 296.2ms
Speed: 1.1ms preprocess, 296.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6UuYPfJNmjUKdqw5M-uOw_180.JPG: 480x640 (no detections), 299.7ms
Speed: 1.3ms preprocess, 299.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6UuYPfJNmjUKdqw5M-uOw_270.JPG: 480x640 (no detections), 298.4ms
Speed: 1.1ms preprocess, 298.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6_zH30tzM-LONkNbgVQsw_0.JPG: 480x640 (no detections), 299.0ms
Speed: 1.3ms preprocess, 299.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6_zH30tzM-LONkNbgVQsw_90.JPG: 480x640 (no detections), 296.0ms
Speed: 1.1ms preprocess, 296.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6_zH30tzM-LONkNbgVQsw_180.JPG: 480x640 1 Waste, 295.9ms

Speed: 1.0ms preprocess, 295.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6_zH30tzM-LONkNbgVQsw_270.JPG: 480x640 (no detections), 300.9ms
Speed: 1.1ms preprocess, 300.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6dhKzUbEMsnZ55DwKuMLA_0.JPG: 480x640 (no detections), 298.8ms
Speed: 1.2ms preprocess, 298.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6dhKzUbEMsnZ55DwKuMLA_90.JPG: 480x640 (no detections), 297.3ms
Speed: 1.2ms preprocess, 297.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6dhKzUbEMsnZ55DwKuMLA_180.JPG: 480x640 (no detections), 300.8ms
Speed: 1.1ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6dhKzUbEMsnZ55DwKuMLA_270.JPG: 480x640 (no detections), 302.3ms
Speed: 1.2ms preprocess, 302.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6eQH7w9tX1PZ872CXs9gw_0.JPG: 480x640 (no detections), 297.3ms
Speed: 1.4ms preprocess, 297.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6eQH7w9tX1PZ872CXs9gw_90.JPG: 480x640 (no detections), 301.4ms
Speed: 1.1ms preprocess, 301.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6eQH7w9tX1PZ872CXs9gw_180.JPG: 480x640 (no detections), 299.5ms
Speed: 1.2ms preprocess, 299.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6eQH7w9tX1PZ872CXs9gw_270.JPG: 480x640 (no detections), 306.6ms
Speed: 1.5ms preprocess, 306.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6j31tPaDoZQA2gpWiBDMQ_0.JPG: 480x640 (no detections), 306.2ms
Speed: 1.3ms preprocess, 306.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6j31tPaDoZQA2gpWiBDMQ_90.JPG: 480x640 (no detections), 297.6ms
Speed: 1.6ms preprocess, 297.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6j31tPaDoZQA2gpWiBDMQ_180.JPG: 480x640 (no detections), 303.1ms
Speed: 1.8ms preprocess, 303.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6j31tPaDoZQA2gpWiBDMQ_270.JPG: 480x640 (no detections), 304.4ms
Speed: 1.3ms preprocess, 304.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6j81xJ9L6VSJiqP6swMEA_0.JPG: 480x640 (no detections), 295.9ms
Speed: 1.3ms preprocess, 295.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6j81xJ9L6VSJiqP6swMEA_90.JPG: 480x640 (no detections), 298.1ms
Speed: 1.3ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6j81xJ9L6VSJiqP6swMEA_180.JPG: 480x640 (no detections), 301.0ms
Speed: 1.2ms preprocess, 301.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6j81xJ9L6VSJiqP6swMEA_270.JPG: 480x640 (no detections), 300.0ms
Speed: 1.1ms preprocess, 300.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6jF7WOzJ5zQWde4EbBf_Q_0.JPG: 480x640 (no detections), 295.7ms
Speed: 1.2ms preprocess, 295.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6jF7WOzJ5zQWde4EbBf_Q_90.JPG: 480x640 (no detections), 296.3ms
Speed: 1.1ms preprocess, 296.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6jF7WOzJ5zQWde4EbBf_Q_180.JPG: 480x640 (no detections), 306.4ms
Speed: 1.6ms preprocess, 306.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6jF7WOzJ5zQWde4EbBf_Q_270.JPG: 480x640 (no detections), 307.2ms
Speed: 1.8ms preprocess, 307.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6jfN79DMeRDegbXQ8L-WA_0.JPG: 480x640 (no detections), 305.8ms
Speed: 1.2ms preprocess, 305.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6jfN79DMeRDegbXQ8L-WA_90.JPG: 480x640 (no detections), 304.3ms
Speed: 1.0ms preprocess, 304.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6jfN79DMeRDegbXQ8L-WA_180.JPG: 480x640 (no detections), 298.3ms
Speed: 1.8ms preprocess, 298.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6jfN79DMeRDegbXQ8L-WA_270.JPG: 480x640 (no detections), 298.9ms
Speed: 1.1ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6pAsE2iacQGsPAK3JrBFQ_0.JPG: 480x640 (no detections), 302.0ms
Speed: 1.1ms preprocess, 302.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6pAsE2iacQGsPAK3JrBFQ_90.JPG: 480x640 (no detections), 294.1ms
Speed: 1.1ms preprocess, 294.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6pAsE2iacQGsPAK3JrBFQ_180.JPG: 480x640 (no detections), 301.1ms
Speed: 1.1ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6pAsE2iacQGsPAK3JrBFQ_270.JPG: 480x640 (no detections), 307.5ms
Speed: 1.1ms preprocess, 307.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6q6nEopsZ6lnAdOYeUBag_0.JPG: 480x640 (no detections), 309.9ms
Speed: 1.0ms preprocess, 309.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6q6nEopsZ6lnAdOYeUBag_90.JPG: 480x640 (no detections), 294.9ms
Speed: 1.1ms preprocess, 294.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6q6nEopsZ6lnAdOYeUBag_180.JPG: 480x640 (no detections), 297.4ms
Speed: 1.1ms preprocess, 297.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/6/x6q6nEopsZ6lnAdOYeUBag_270.JPG: 480x640 1 Waste, 300.8ms
Speed: 1.2ms preprocess, 300.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x71CPeaEdYEg3ZS13UGYig_0.JPG: 480x640 (no detections), 332.4ms
Speed: 1.3ms preprocess, 332.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x71CPeaEdYEg3ZS13UGYig_90.JPG: 480x640 (no detections), 301.1ms
Speed: 1.4ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x71CPeaEdYEg3ZS13UGYig_180.JPG: 480x640 (no detections), 316.2ms
Speed: 1.3ms preprocess, 316.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x71CPeaEdYEg3ZS13UGYig_270.JPG: 480x640 (no detections), 427.7ms
Speed: 1.0ms preprocess, 427.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x79XszmeH8RwFjfjzwvccw_0.JPG: 480x640 (no detections), 322.9ms
Speed: 1.4ms preprocess, 322.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x79XszmeH8RwFjfjzwvccw_90.JPG: 480x640 (no detections), 344.8ms
Speed: 1.3ms preprocess, 344.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x79XszmeH8RwFjfjzwvccw_180.JPG: 480x640 (no detections), 320.0ms
Speed: 1.2ms preprocess, 320.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x79XszmeH8RwFjfjzwvccw_270.JPG: 480x640 (no detections), 296.5ms
Speed: 1.2ms preprocess, 296.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7BL8tRF6gESjyLnMGFdeQ_0.JPG: 480x640 (no detections), 293.9ms
Speed: 1.2ms preprocess, 293.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7BL8tRF6gESjyLnMGFdeQ_90.JPG: 480x640 (no detections), 295.7ms
Speed: 1.1ms preprocess, 295.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7BL8tRF6gESjyLnMGFdeQ_180.JPG: 480x640 (no detections), 289.1ms
Speed: 1.0ms preprocess, 289.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7BL8tRF6gESjyLnMGFdeQ_270.JPG: 480x640 (no detections), 295.6ms
Speed: 1.1ms preprocess, 295.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7DAAYnnDArwvywjoTfNaA_0.JPG: 480x640 (no detections), 289.1ms
Speed: 1.0ms preprocess, 289.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7DAAYnnDArwvywjoTfNaA_90.JPG: 480x640 (no detections), 291.6ms
Speed: 1.1ms preprocess, 291.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7DAAYnnDArwvywjoTfNaA_180.JPG: 480x640 (no detections), 293.3ms
Speed: 1.1ms preprocess, 293.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7DAAYnnDArwvywjoTfNaA_270.JPG: 480x640 (no detections), 292.4ms
Speed: 1.3ms preprocess, 292.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7Ex5izVij-n9V5O-1zubw_0.JPG: 480x640 (no detections), 296.0ms
Speed: 1.3ms preprocess, 296.0ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7Ex5izVij-n9V5O-1zubw_90.JPG: 480x640 (no detections), 292.4ms
Speed: 1.1ms preprocess, 292.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7Ex5izVij-n9V5O-1zubw_180.JPG: 480x640 (no detections), 295.4ms
Speed: 1.3ms preprocess, 295.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7Ex5izVij-n9V5O-1zubw_270.JPG: 480x640 (no detections), 292.6ms
Speed: 1.9ms preprocess, 292.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7Gj9E5vdf4KiatHLaBVxA_0.JPG: 480x640 (no detections), 292.6ms
Speed: 1.2ms preprocess, 292.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7Gj9E5vdf4KiatHLaBVxA_90.JPG: 480x640 (no detections), 299.6ms
Speed: 1.1ms preprocess, 299.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7Gj9E5vdf4KiatHLaBVxA_180.JPG: 480x640 (no detections), 313.2ms
Speed: 1.1ms preprocess, 313.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7Gj9E5vdf4KiatHLaBVxA_270.JPG: 480x640 (no detections), 304.6ms
Speed: 1.3ms preprocess, 304.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7H7FvupdfM0JymEiAoI6A_0.JPG: 480x640 (no detections), 302.4ms
Speed: 1.2ms preprocess, 302.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7H7FvupdfM0JymEiAoI6A_90.JPG: 480x640 (no detections), 294.4ms
Speed: 1.2ms preprocess, 294.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7H7FvupdfM0JymEiAoI6A_180.JPG: 480x640 (no detections), 298.7ms
Speed: 1.2ms preprocess, 298.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7H7FvupdfM0JymEiAoI6A_270.JPG: 480x640 (no detections), 294.3ms
Speed: 1.2ms preprocess, 294.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7Hj_pqV6ZM5_uPZSFbIwA_0.JPG: 480x640 (no detections), 292.2ms
Speed: 2.0ms preprocess, 292.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7Hj_pqV6ZM5_uPZSFbIwA_90.JPG: 480x640 (no detections), 294.5ms
Speed: 1.2ms preprocess, 294.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7Hj_pqV6ZM5_uPZSFbIwA_180.JPG: 480x640 (no detections), 299.8ms
Speed: 1.1ms preprocess, 299.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7Hj_pqV6ZM5_uPZSFbIwA_270.JPG: 480x640 (no detections), 298.3ms
Speed: 1.1ms preprocess, 298.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7I3ZtAXRhYLTK7_TYgUUw_0.JPG: 480x640 (no detections), 304.6ms
Speed: 1.2ms preprocess, 304.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7I3ZtAXRhYLTK7_TYgUUw_90.JPG: 480x640 (no detections), 304.0ms

Speed: 1.2ms preprocess, 304.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7I3ZtAXRhYLTK7_TYgUUw_180.JPG: 480x640 (no detections), 308.1ms
Speed: 1.5ms preprocess, 308.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7I3ZtAXRhYLTK7_TYgUUw_270.JPG: 480x640 (no detections), 302.0ms
Speed: 1.2ms preprocess, 302.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7IUvGLjQVKDThMJ-Nxwgw_0.JPG: 480x640 (no detections), 298.5ms
Speed: 1.2ms preprocess, 298.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7IUvGLjQVKDThMJ-Nxwgw_90.JPG: 480x640 (no detections), 299.5ms
Speed: 1.5ms preprocess, 299.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7IUvGLjQVKDThMJ-Nxwgw_180.JPG: 480x640 (no detections), 306.8ms
Speed: 1.9ms preprocess, 306.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7IUvGLjQVKDThMJ-Nxwgw_270.JPG: 480x640 (no detections), 298.3ms
Speed: 1.1ms preprocess, 298.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7cakVZ4tGvuiKf7MlkWnQ_0.JPG: 480x640 (no detections), 306.8ms
Speed: 1.3ms preprocess, 306.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7cakVZ4tGvuiKf7MlkWnQ_90.JPG: 480x640 (no detections), 313.1ms
Speed: 1.4ms preprocess, 313.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7cakVZ4tGvuiKf7MlkWnQ_180.JPG: 480x640 (no detections), 310.5ms
Speed: 1.2ms preprocess, 310.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7cakVZ4tGvuiKf7MlkWnQ_270.JPG: 480x640 (no detections), 314.5ms
Speed: 1.7ms preprocess, 314.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7eS9znfLvEIPcyzv7bt_A_0.JPG: 480x640 (no detections), 304.8ms
Speed: 1.6ms preprocess, 304.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7eS9znfLvEIPcyzv7bt_A_90.JPG: 480x640 (no detections), 301.7ms
Speed: 1.2ms preprocess, 301.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7eS9znfLvEIPcyzv7bt_A_180.JPG: 480x640 (no detections), 299.7ms
Speed: 1.4ms preprocess, 299.7ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7eS9znfLvEIPcyzv7bt_A_270.JPG: 480x640 (no detections), 303.4ms
Speed: 1.2ms preprocess, 303.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7jdwiazxHkcubh9Vj4elw_0.JPG: 480x640 (no detections), 295.9ms
Speed: 1.3ms preprocess, 295.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7jdwiazxHkcubh9Vj4elw_90.JPG: 480x640 (no detections), 299.7ms
Speed: 1.1ms preprocess, 299.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7jdwiazxHkcubh9Vj4elw_180.JPG: 480x640 (no detections), 297.9ms
Speed: 1.1ms preprocess, 297.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7jdwiazxHkcubh9Vj4elw_270.JPG: 480x640 (no detections), 296.9ms
Speed: 1.1ms preprocess, 296.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7l-ZAeDqq4iKRkmYtkfIQ_0.JPG: 480x640 (no detections), 291.6ms
Speed: 1.1ms preprocess, 291.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7l-ZAeDqq4iKRkmYtkfIQ_90.JPG: 480x640 (no detections), 295.6ms
Speed: 1.1ms preprocess, 295.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7l-ZAeDqq4iKRkmYtkfIQ_180.JPG: 480x640 (no detections), 293.7ms
Speed: 1.3ms preprocess, 293.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7l-ZAeDqq4iKRkmYtkfIQ_270.JPG: 480x640 (no detections), 297.2ms
Speed: 1.1ms preprocess, 297.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7me1xCidGVf9YwurEAIoQ_0.JPG: 480x640 (no detections), 301.8ms
Speed: 1.1ms preprocess, 301.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7me1xCidGVf9YwurEAIoQ_90.JPG: 480x640 (no detections), 295.1ms
Speed: 1.0ms preprocess, 295.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7me1xCidGVf9YwurEAIoQ_180.JPG: 480x640 (no detections), 299.0ms
Speed: 1.1ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7me1xCidGVf9YwurEAIoQ_270.JPG: 480x640 (no detections), 300.4ms
Speed: 1.2ms preprocess, 300.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7oXKutC7QoyRn81CxJn1Q_0.JPG: 480x640 (no detections), 295.5ms
Speed: 1.3ms preprocess, 295.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7oXKutC7QoyRn81CxJn1Q_90.JPG: 480x640 (no detections), 295.2ms
Speed: 1.2ms preprocess, 295.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7oXKutC7QoyRn81CxJn1Q_180.JPG: 480x640 (no detections), 298.4ms
Speed: 1.1ms preprocess, 298.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7oXKutC7QoyRn81CxJn1Q_270.JPG: 480x640 (no detections), 295.3ms
Speed: 1.1ms preprocess, 295.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7pDxyYvv6HHJsfzo-sygg_0.JPG: 480x640 (no detections), 303.1ms
Speed: 1.1ms preprocess, 303.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7pDxyYvv6HHJsfzo-sygg_90.JPG: 480x640 (no detections), 297.3ms
Speed: 1.1ms preprocess, 297.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7pDxyYvv6HHJsfzo-sygg_180.JPG: 480x640 (no detections), 299.8ms
Speed: 1.0ms preprocess, 299.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7pDxyYvv6HHJsfzo-sygg_270.JPG: 480x640 (no detections), 295.7ms
Speed: 1.0ms preprocess, 295.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7qpzqEu1JHGrcgSAGiPaQ_0.JPG: 480x640 (no detections), 300.7ms
Speed: 1.1ms preprocess, 300.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7qpzqEu1JHGrcgSAGiPaQ_90.JPG: 480x640 (no detections), 302.4ms
Speed: 1.2ms preprocess, 302.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7qpzqEu1JHGrcgSAGiPaQ_180.JPG: 480x640 (no detections), 296.4ms
Speed: 1.4ms preprocess, 296.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7qpzqEu1JHGrcgSAGiPaQ_270.JPG: 480x640 (no detections), 298.2ms
Speed: 1.5ms preprocess, 298.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7rl2sPeO3o6FSzdAm4e3w_0.JPG: 480x640 (no detections), 299.3ms
Speed: 1.7ms preprocess, 299.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7rl2sPeO3o6FSzdAm4e3w_90.JPG: 480x640 (no detections), 297.8ms
Speed: 1.2ms preprocess, 297.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7rl2sPeO3o6FSzdAm4e3w_180.JPG: 480x640 (no detections), 302.3ms
Speed: 1.3ms preprocess, 302.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7rl2sPeO3o6FSzdAm4e3w_270.JPG: 480x640 (no detections), 298.9ms
Speed: 1.2ms preprocess, 298.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7undV7sCX5z6SxVsnZrSQ_0.JPG: 480x640 (no detections), 299.3ms
Speed: 1.2ms preprocess, 299.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7undV7sCX5z6SxVsnZrSQ_90.JPG: 480x640 (no detections), 305.1ms
Speed: 1.0ms preprocess, 305.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7undV7sCX5z6SxVsnZrSQ_180.JPG: 480x640 (no detections), 297.9ms
Speed: 1.1ms preprocess, 297.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7undV7sCX5z6SxVsnZrSQ_270.JPG: 480x640 (no detections), 300.9ms
Speed: 1.6ms preprocess, 300.9ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7wYjNW0I8KMWcspoITX1w_0.JPG: 480x640 (no detections), 296.0ms
Speed: 1.2ms preprocess, 296.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7wYjNW0I8KMWcspoITX1w_90.JPG: 480x640 (no detections), 296.1ms
Speed: 1.4ms preprocess, 296.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7wYjNW0I8KMWcspoITX1w_180.JPG: 480x640 (no detections), 301.2ms
Speed: 1.1ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7wYjNW0I8KMWcspoITX1w_270.JPG: 480x640 (no detections), 298.9ms
Speed: 1.1ms preprocess, 298.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7zqQnpfwnY7ykguGIYtig_0.JPG: 480x640 (no detections), 293.0ms
Speed: 1.1ms preprocess, 293.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7zqQnpfwnY7ykguGIYtig_90.JPG: 480x640 (no detections), 300.3ms
Speed: 1.1ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7zqQnpfwnY7ykguGIYtig_180.JPG: 480x640 (no detections), 300.8ms
Speed: 1.1ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/7/x7zqQnpfwnY7ykguGIYtig_270.JPG: 480x640 (no detections), 300.0ms
Speed: 1.2ms preprocess, 300.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8111l7YmDqHwvU4e1Mp5w_0.JPG: 480x640 (no detections), 296.3ms
Speed: 1.5ms preprocess, 296.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8111l7YmDqHwvU4e1Mp5w_90.JPG: 480x640 (no detections), 297.1ms
Speed: 1.3ms preprocess, 297.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8111l7YmDqHwvU4e1Mp5w_180.JPG: 480x640 (no detections), 303.8ms
Speed: 1.1ms preprocess, 303.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8111l7YmDqHwvU4e1Mp5w_270.JPG: 480x640 (no detections), 295.5ms
Speed: 1.0ms preprocess, 295.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x81jZukc9OItzbd_mcjAaw_0.JPG: 480x640 (no detections), 297.2ms
Speed: 1.1ms preprocess, 297.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x81jZukc9OItzbd_mcjAaw_90.JPG: 480x640 (no detections), 300.8ms
Speed: 1.2ms preprocess, 300.8ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x81jZukc9OItzbd_mcjAaw_180.JPG: 480x640 (no detections), 300.1ms
Speed: 1.3ms preprocess, 300.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x81jZukc9OItzbd_mcjAaw_270.JPG: 480x640 (no detections), 300.7ms
Speed: 1.2ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x84o3uALHQgYhdbEsZaIyw_0.JPG: 480x640 (no detections), 302.0ms
Speed: 1.1ms preprocess, 302.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x84o3uALHQgYhdbEsZaIyw_90.JPG: 480x640 (no detections), 296.6ms
Speed: 1.2ms preprocess, 296.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x84o3uALHQgYhdbEsZaIyw_180.JPG: 480x640 (no detections), 295.1ms
Speed: 1.1ms preprocess, 295.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x84o3uALHQgYhdbEsZaIyw_270.JPG: 480x640 (no detections), 304.7ms
Speed: 1.2ms preprocess, 304.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x87_Rj73nFuveCKZQq3S1Q_0.JPG: 480x640 (no detections), 299.3ms

Speed: 1.2ms preprocess, 299.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x87_Rj73nFuveCKZQq3S1Q_90.JPG: 480x640 (no detections), 300.4ms
Speed: 1.0ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x87_Rj73nFuveCKZQq3S1Q_180.JPG: 480x640 (no detections), 301.6ms
Speed: 1.2ms preprocess, 301.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x87_Rj73nFuveCKZQq3S1Q_270.JPG: 480x640 (no detections), 301.3ms
Speed: 1.3ms preprocess, 301.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x89EPsJDNtVcouXAmA8bVQ_0.JPG: 480x640 (no detections), 303.2ms
Speed: 1.2ms preprocess, 303.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x89EPsJDNtVcouXAmA8bVQ_90.JPG: 480x640 (no detections), 293.4ms
Speed: 1.2ms preprocess, 293.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x89EPsJDNtVcouXAmA8bVQ_180.JPG: 480x640 (no detections), 298.7ms
Speed: 1.1ms preprocess, 298.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x89EPsJDNtVcouXAmA8bVQ_270.JPG: 480x640 (no detections), 296.2ms
Speed: 1.1ms preprocess, 296.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8CDMUTmgpdB1RKY-lmWKw_0.JPG: 480x640 (no detections), 294.7ms
Speed: 1.2ms preprocess, 294.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8CDMUTmgpdB1RKY-lmWKw_90.JPG: 480x640 (no detections), 300.8ms
Speed: 1.8ms preprocess, 300.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8CDMUTmgpdB1RKY-lmWKw_180.JPG: 480x640 (no detections), 296.8ms
Speed: 1.2ms preprocess, 296.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8CDMUTmgpdB1RKY-lmWKw_270.JPG: 480x640 (no detections), 294.0ms
Speed: 1.3ms preprocess, 294.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8FeZtOD1G0YA_K_OZUrsQ_0.JPG: 480x640 (no detections), 290.1ms
Speed: 1.3ms preprocess, 290.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8FeZtOD1G0YA_K_OZUrsQ_90.JPG: 480x640 (no detections), 301.1ms
Speed: 1.1ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8FeZtOD1G0YA_K_OZUrsQ_180.JPG: 480x640 (no detections), 298.3ms
Speed: 1.1ms preprocess, 298.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8FeZtOD1G0YA_K_OZUrsQ_270.JPG: 480x640 (no detections), 299.9ms
Speed: 1.0ms preprocess, 299.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8H65yTn7clfyyCxCkKcvg_0.JPG: 480x640 (no detections), 294.4ms
Speed: 1.1ms preprocess, 294.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8H65yTn7clfyyCxCkKcvg_90.JPG: 480x640 (no detections), 304.6ms
Speed: 1.2ms preprocess, 304.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8H65yTn7clfyyCxCkKcvg_180.JPG: 480x640 (no detections), 298.6ms
Speed: 1.1ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8H65yTn7clfyyCxCkKcvg_270.JPG: 480x640 (no detections), 297.7ms
Speed: 1.3ms preprocess, 297.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8MUw9MxTUk8ZlQBMdJghw_0.JPG: 480x640 (no detections), 295.3ms
Speed: 1.2ms preprocess, 295.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8MUw9MxTUk8ZlQBMdJghw_90.JPG: 480x640 (no detections), 296.6ms
Speed: 1.2ms preprocess, 296.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8MUw9MxTUk8ZlQBMdJghw_180.JPG: 480x640 (no detections), 300.6ms
Speed: 1.1ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8MUw9MxTUk8ZlQBMdJghw_270.JPG: 480x640 (no detections), 300.3ms
Speed: 1.6ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8TKnKfPa93mU4VAfBojEQ_0.JPG: 480x640 (no detections), 300.3ms
Speed: 1.5ms preprocess, 300.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8TKnKfPa93mU4VAfBojEQ_90.JPG: 480x640 (no detections), 296.7ms
Speed: 1.5ms preprocess, 296.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8TKnKfPa93mU4VAfBojEQ_180.JPG: 480x640 (no detections), 300.0ms
Speed: 1.3ms preprocess, 300.0ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8TKnKfPa93mU4VAfBojEQ_270.JPG: 480x640 (no detections), 295.9ms
Speed: 1.1ms preprocess, 295.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8TQejO7-Y45A_333RyQeQ_0.JPG: 480x640 1 Waste, 295.5ms
Speed: 1.1ms preprocess, 295.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8TQejO7-Y45A_333RyQeQ_90.JPG: 480x640 (no detections), 295.0ms
Speed: 1.1ms preprocess, 295.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8TQejO7-Y45A_333RyQeQ_180.JPG: 480x640 (no detections), 305.5ms
Speed: 1.3ms preprocess, 305.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8TQejO7-Y45A_333RyQeQ_270.JPG: 480x640 (no detections), 298.2ms
Speed: 1.1ms preprocess, 298.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8UpEKJ3lO1175dHTXrHug_0.JPG: 480x640 (no detections), 298.8ms
Speed: 1.5ms preprocess, 298.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8UpEKJ3lO1175dHTXrHug_90.JPG: 480x640 (no detections), 298.2ms
Speed: 1.4ms preprocess, 298.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8UpEKJ3lO1175dHTXrHug_180.JPG: 480x640 (no detections), 301.6ms
Speed: 1.4ms preprocess, 301.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8UpEKJ3lO1175dHTXrHug_270.JPG: 480x640 (no detections), 298.2ms
Speed: 1.2ms preprocess, 298.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8XyaMK0sD-hUYza9ykYCA_0.JPG: 480x640 (no detections), 297.9ms
Speed: 1.2ms preprocess, 297.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8XyaMK0sD-hUYza9ykYCA_90.JPG: 480x640 (no detections), 299.8ms
Speed: 1.1ms preprocess, 299.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8XyaMK0sD-hUYza9ykYCA_180.JPG: 480x640 (no detections), 294.1ms
Speed: 1.2ms preprocess, 294.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8XyaMK0sD-hUYza9ykYCA_270.JPG: 480x640 (no detections), 298.5ms
Speed: 1.1ms preprocess, 298.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8ZY7BaodMwR_QMW-MkvJw_0.JPG: 480x640 (no detections), 299.0ms
Speed: 1.2ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8ZY7BaodMwR_QMW-MkvJw_90.JPG: 480x640 (no detections), 299.8ms
Speed: 1.1ms preprocess, 299.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8ZY7BaodMwR_QMW-MkvJw_180.JPG: 480x640 (no detections), 297.4ms
Speed: 1.1ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8ZY7BaodMwR_QMW-MkvJw_270.JPG: 480x640 (no detections), 308.9ms
Speed: 1.4ms preprocess, 308.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8eKM7yCjAu-O9HU53Pzjg_0.JPG: 480x640 (no detections), 295.0ms
Speed: 1.3ms preprocess, 295.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8eKM7yCjAu-O9HU53Pzjg_90.JPG: 480x640 (no detections), 296.8ms
Speed: 1.1ms preprocess, 296.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8eKM7yCjAu-O9HU53Pzjg_180.JPG: 480x640 (no detections), 298.2ms
Speed: 1.3ms preprocess, 298.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8eKM7yCjAu-O9HU53Pzjg_270.JPG: 480x640 (no detections), 296.6ms
Speed: 1.3ms preprocess, 296.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8eb_IxPr_6RWXHs1EeSHg_0.JPG: 480x640 (no detections), 310.2ms
Speed: 1.2ms preprocess, 310.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8eb_IxPr_6RWXHs1EeSHg_90.JPG: 480x640 (no detections), 305.6ms
Speed: 1.2ms preprocess, 305.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8eb_IxPr_6RWXHs1EeSHg_180.JPG: 480x640 (no detections), 296.5ms
Speed: 1.2ms preprocess, 296.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8eb_IxPr_6RWXHs1EeSHg_270.JPG: 480x640 (no detections), 297.5ms
Speed: 1.1ms preprocess, 297.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8kAvZUs8VRHsfCJR6AQIg_0.JPG: 480x640 (no detections), 297.0ms
Speed: 1.0ms preprocess, 297.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8kAvZUs8VRHsfCJR6AQIg_90.JPG: 480x640 (no detections), 301.6ms
Speed: 1.1ms preprocess, 301.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8kAvZUs8VRHsfCJR6AQIg_180.JPG: 480x640 (no detections), 299.8ms
Speed: 1.1ms preprocess, 299.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8kAvZUs8VRHsfCJR6AQIg_270.JPG: 480x640 (no detections), 300.7ms
Speed: 1.2ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8l0JvsoDaU_1PNdW4AX0A_0.JPG: 480x640 (no detections), 297.7ms
Speed: 1.3ms preprocess, 297.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8l0JvsoDaU_1PNdW4AX0A_90.JPG: 480x640 (no detections), 307.0ms
Speed: 1.4ms preprocess, 307.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8l0JvsoDaU_1PNdW4AX0A_180.JPG: 480x640 (no detections), 298.2ms
Speed: 1.2ms preprocess, 298.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8l0JvsoDaU_1PNdW4AX0A_270.JPG: 480x640 (no detections), 302.0ms
Speed: 1.6ms preprocess, 302.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8uKf2f9952HV6_VyG2f2w_0.JPG: 480x640 (no detections), 305.5ms
Speed: 1.2ms preprocess, 305.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8uKf2f9952HV6_VyG2f2w_90.JPG: 480x640 (no detections), 299.7ms
Speed: 1.1ms preprocess, 299.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8uKf2f9952HV6_VyG2f2w_180.JPG: 480x640 (no detections), 299.9ms
Speed: 1.1ms preprocess, 299.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8uKf2f9952HV6_VyG2f2w_270.JPG: 480x640 (no detections), 298.4ms
Speed: 1.4ms preprocess, 298.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8zWhzQ71PY9mRFJs1J8pg_0.JPG: 480x640 (no detections), 298.6ms
Speed: 1.3ms preprocess, 298.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8zWhzQ71PY9mRFJs1J8pg_90.JPG: 480x640 (no detections), 299.2ms
Speed: 1.1ms preprocess, 299.2ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8zWhzQ71PY9mRFJs1J8pg_180.JPG: 480x640 (no detections), 296.8ms
Speed: 1.6ms preprocess, 296.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/8/x8zWhzQ71PY9mRFJs1J8pg_270.JPG: 480x640 (no detections), 297.5ms

Speed: 1.1ms preprocess, 297.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9-qur--lhL7dyIFQwEDdA_0.JPG: 480x640 (no detections), 302.1ms
Speed: 1.2ms preprocess, 302.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9-qur--lhL7dyIFQwEDdA_90.JPG: 480x640 (no detections), 300.6ms
Speed: 1.1ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9-qur--lhL7dyIFQwEDdA_180.JPG: 480x640 (no detections), 304.7ms
Speed: 1.1ms preprocess, 304.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9-qur--lhL7dyIFQwEDdA_270.JPG: 480x640 (no detections), 297.0ms
Speed: 1.2ms preprocess, 297.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9-zWFH2oLX3O3aagEQ--g_0.JPG: 480x640 (no detections), 297.2ms
Speed: 1.1ms preprocess, 297.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9-zWFH2oLX3O3aagEQ--g_90.JPG: 480x640 (no detections), 303.4ms
Speed: 1.3ms preprocess, 303.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9-zWFH2oLX3O3aagEQ--g_180.JPG: 480x640 (no detections), 298.0ms
Speed: 1.3ms preprocess, 298.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9-zWFH2oLX3O3aagEQ--g_270.JPG: 480x640 (no detections), 298.6ms
Speed: 1.7ms preprocess, 298.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x91GFqEt0MtUJb_hU3rgGQ_0.JPG: 480x640 (no detections), 296.4ms
Speed: 2.3ms preprocess, 296.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x91GFqEt0MtUJb_hU3rgGQ_90.JPG: 480x640 (no detections), 295.4ms
Speed: 1.2ms preprocess, 295.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x91GFqEt0MtUJb_hU3rgGQ_180.JPG: 480x640 (no detections), 300.2ms
Speed: 1.1ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x91GFqEt0MtUJb_hU3rgGQ_270.JPG: 480x640 (no detections), 309.5ms
Speed: 1.2ms preprocess, 309.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x91h1GYQjKR1ebeD4kpvMA_0.JPG: 480x640 (no detections), 293.1ms
Speed: 1.1ms preprocess, 293.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x91h1GYQjKR1ebeD4kpvMA_90.JPG: 480x640 1 Waste, 301.4ms
Speed: 1.1ms preprocess, 301.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x91h1GYQjKR1ebeD4kpvMA_180.JPG: 480x640 (no detections), 304.2ms
Speed: 1.4ms preprocess, 304.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x91h1GYQjKR1ebeD4kpvMA_270.JPG: 480x640 (no detections), 302.7ms
Speed: 1.2ms preprocess, 302.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x91oA16_Jet2fQJYFL1HgQ_0.JPG: 480x640 (no detections), 299.6ms
Speed: 1.2ms preprocess, 299.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x91oA16_Jet2fQJYFL1HgQ_90.JPG: 480x640 (no detections), 302.6ms
Speed: 1.2ms preprocess, 302.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x91oA16_Jet2fQJYFL1HgQ_180.JPG: 480x640 (no detections), 299.8ms
Speed: 1.2ms preprocess, 299.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x91oA16_Jet2fQJYFL1HgQ_270.JPG: 480x640 (no detections), 295.7ms
Speed: 1.2ms preprocess, 295.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9316fLR82moH-CC-vb0Ng_0.JPG: 480x640 (no detections), 297.1ms
Speed: 1.4ms preprocess, 297.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9316fLR82moH-CC-vb0Ng_90.JPG: 480x640 (no detections), 296.1ms
Speed: 1.2ms preprocess, 296.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9316fLR82moH-CC-vb0Ng_180.JPG: 480x640 (no detections), 302.5ms
Speed: 1.3ms preprocess, 302.5ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9316fLR82moH-CC-vb0Ng_270.JPG: 480x640 (no detections), 295.7ms
Speed: 1.3ms preprocess, 295.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x93HZF7UQQWUNU3-WOhDzA_0.JPG: 480x640 (no detections), 296.1ms
Speed: 1.3ms preprocess, 296.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x93HZF7UQQWUNU3-WOhDzA_90.JPG: 480x640 (no detections), 296.8ms
Speed: 1.1ms preprocess, 296.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x93HZF7UQQWUNU3-WOhDzA_180.JPG: 480x640 (no detections), 297.9ms
Speed: 1.1ms preprocess, 297.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x93HZF7UQQWUNU3-WOhDzA_270.JPG: 480x640 (no detections), 294.0ms
Speed: 1.1ms preprocess, 294.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x94gGKseyUYYt_-ux5XOxw_0.JPG: 480x640 (no detections), 303.9ms
Speed: 1.8ms preprocess, 303.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x94gGKseyUYYt_-ux5XOxw_90.JPG: 480x640 (no detections), 301.2ms
Speed: 1.2ms preprocess, 301.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x94gGKseyUYYt_-ux5XOxw_180.JPG: 480x640 (no detections), 298.3ms
Speed: 1.3ms preprocess, 298.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x94gGKseyUYYt_-ux5XOxw_270.JPG: 480x640 (no detections), 302.5ms
Speed: 1.1ms preprocess, 302.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x95eaO9o_A8bN6PZ1ppA8A_0.JPG: 480x640 (no detections), 404.3ms
Speed: 1.1ms preprocess, 404.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x95eaO9o_A8bN6PZ1ppA8A_90.JPG: 480x640 1 Waste, 312.1ms
Speed: 1.3ms preprocess, 312.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x95eaO9o_A8bN6PZ1ppA8A_180.JPG: 480x640 (no detections), 306.8ms
Speed: 1.0ms preprocess, 306.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x95eaO9o_A8bN6PZ1ppA8A_270.JPG: 480x640 (no detections), 330.1ms
Speed: 1.2ms preprocess, 330.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x97X1I24uRiL4y3M485wPQ_0.JPG: 480x640 (no detections), 309.2ms
Speed: 1.3ms preprocess, 309.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x97X1I24uRiL4y3M485wPQ_90.JPG: 480x640 (no detections), 320.5ms
Speed: 1.3ms preprocess, 320.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x97X1I24uRiL4y3M485wPQ_180.JPG: 480x640 (no detections), 323.4ms
Speed: 1.4ms preprocess, 323.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x97X1I24uRiL4y3M485wPQ_270.JPG: 480x640 (no detections), 309.0ms
Speed: 1.1ms preprocess, 309.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x981a7YSKOXrDrVGmwj9JQ_0.JPG: 480x640 (no detections), 315.1ms
Speed: 1.0ms preprocess, 315.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x981a7YSKOXrDrVGmwj9JQ_90.JPG: 480x640 (no detections), 300.4ms
Speed: 1.1ms preprocess, 300.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x981a7YSKOXrDrVGmwj9JQ_180.JPG: 480x640 (no detections), 294.3ms
Speed: 1.3ms preprocess, 294.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x981a7YSKOXrDrVGmwj9JQ_270.JPG: 480x640 (no detections), 301.2ms
Speed: 1.5ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9ArSIwxQ7-tqY7Fs3d-7g_0.JPG: 480x640 (no detections), 288.1ms
Speed: 1.2ms preprocess, 288.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9ArSIwxQ7-tqY7Fs3d-7g_90.JPG: 480x640 (no detections), 299.1ms
Speed: 1.1ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9ArSIwxQ7-tqY7Fs3d-7g_180.JPG: 480x640 (no detections), 290.6ms
Speed: 1.2ms preprocess, 290.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9ArSIwxQ7-tqY7Fs3d-7g_270.JPG: 480x640 (no detections), 298.1ms
Speed: 1.1ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9Iyt0Jj2YIYf1z1GWNthg_0.JPG: 480x640 (no detections), 292.6ms
Speed: 1.6ms preprocess, 292.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9Iyt0Jj2YIYf1z1GWNthg_90.JPG: 480x640 (no detections), 293.8ms
Speed: 1.1ms preprocess, 293.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9Iyt0Jj2YIYf1z1GWNthg_180.JPG: 480x640 (no detections), 310.1ms
Speed: 1.3ms preprocess, 310.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9Iyt0Jj2YIYf1z1GWNthg_270.JPG: 480x640 (no detections), 308.0ms
Speed: 1.5ms preprocess, 308.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9LzHSNuaPMsLhbSOXv3cw_0.JPG: 480x640 (no detections), 299.3ms
Speed: 1.2ms preprocess, 299.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9LzHSNuaPMsLhbSOXv3cw_90.JPG: 480x640 (no detections), 309.8ms
Speed: 1.2ms preprocess, 309.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9LzHSNuaPMsLhbSOXv3cw_180.JPG: 480x640 (no detections), 305.3ms
Speed: 1.3ms preprocess, 305.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9LzHSNuaPMsLhbSOXv3cw_270.JPG: 480x640 (no detections), 301.9ms
Speed: 1.5ms preprocess, 301.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9SLN7H4BCaWKd2de1e8zQ_0.JPG: 480x640 (no detections), 297.8ms
Speed: 1.3ms preprocess, 297.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9SLN7H4BCaWKd2de1e8zQ_90.JPG: 480x640 (no detections), 303.9ms
Speed: 1.5ms preprocess, 303.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9SLN7H4BCaWKd2de1e8zQ_180.JPG: 480x640 (no detections), 302.0ms
Speed: 1.2ms preprocess, 302.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9SLN7H4BCaWKd2de1e8zQ_270.JPG: 480x640 (no detections), 300.5ms
Speed: 1.3ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9U72sHc3d82KG_D83QXqg_0.JPG: 480x640 (no detections), 300.8ms
Speed: 1.2ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9U72sHc3d82KG_D83QXqg_90.JPG: 480x640 (no detections), 295.6ms
Speed: 1.1ms preprocess, 295.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9U72sHc3d82KG_D83QXqg_180.JPG: 480x640 (no detections), 299.5ms
Speed: 1.1ms preprocess, 299.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9U72sHc3d82KG_D83QXqg_270.JPG: 480x640 (no detections), 298.3ms
Speed: 1.2ms preprocess, 298.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9Y4wWEmxjAlo3KdZFMDmA_0.JPG: 480x640 (no detections), 300.3ms
Speed: 1.2ms preprocess, 300.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9Y4wWEmxjAlo3KdZFMDmA_90.JPG: 480x640 (no detections), 299.3ms
Speed: 1.2ms preprocess, 299.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9Y4wWEmxjAlo3KdZFMDmA_180.JPG: 480x640 (no detections), 295.4ms

Speed: 1.2ms preprocess, 295.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9Y4wWEmxjAlo3KdZFMDmA_270.JPG: 480x640 (no detections), 300.4ms
Speed: 1.1ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9YgcMeMT4jFOeZjSs978A_0.JPG: 480x640 (no detections), 298.3ms
Speed: 1.2ms preprocess, 298.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9YgcMeMT4jFOeZjSs978A_90.JPG: 480x640 1 Waste, 301.4ms
Speed: 1.1ms preprocess, 301.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9YgcMeMT4jFOeZjSs978A_180.JPG: 480x640 (no detections), 294.9ms
Speed: 1.3ms preprocess, 294.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9YgcMeMT4jFOeZjSs978A_270.JPG: 480x640 1 Waste, 305.0ms
Speed: 1.4ms preprocess, 305.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9dRPj0V4-Yx_kGGzZJEfg_0.JPG: 480x640 (no detections), 296.5ms
Speed: 1.1ms preprocess, 296.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9dRPj0V4-Yx_kGGzZJEfg_90.JPG: 480x640 (no detections), 299.5ms
Speed: 1.3ms preprocess, 299.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9dRPj0V4-Yx_kGGzZJEfg_180.JPG: 480x640 (no detections), 297.6ms
Speed: 1.2ms preprocess, 297.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9dRPj0V4-Yx_kGGzZJEfg_270.JPG: 480x640 (no detections), 303.7ms
Speed: 1.6ms preprocess, 303.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9fuFnMnDgJ1PTZVMGCIOg_0.JPG: 480x640 (no detections), 301.0ms
Speed: 1.4ms preprocess, 301.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9fuFnMnDgJ1PTZVMGCIOg_90.JPG: 480x640 (no detections), 295.9ms
Speed: 1.8ms preprocess, 295.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9fuFnMnDgJ1PTZVMGCIOg_180.JPG: 480x640 (no detections), 301.0ms
Speed: 1.4ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9fuFnMnDgJ1PTZVMGCIOg_270.JPG: 480x640 (no detections), 304.1ms
Speed: 1.3ms preprocess, 304.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9gmjZE1CD-R8_FGZQrwHA_0.JPG: 480x640 (no detections), 297.8ms
Speed: 1.3ms preprocess, 297.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9gmjZE1CD-R8_FGZQrwHA_90.JPG: 480x640 (no detections), 296.6ms
Speed: 1.1ms preprocess, 296.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9gmjZE1CD-R8_FGZQrwHA_180.JPG: 480x640 (no detections), 298.6ms
Speed: 1.1ms preprocess, 298.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9gmjZE1CD-R8_FGZQrwHA_270.JPG: 480x640 (no detections), 299.1ms
Speed: 1.1ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9iGY866D2n1Z6dSjz-9-g_0.JPG: 480x640 (no detections), 299.5ms
Speed: 1.3ms preprocess, 299.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9iGY866D2n1Z6dSjz-9-g_90.JPG: 480x640 (no detections), 295.6ms
Speed: 1.1ms preprocess, 295.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9iGY866D2n1Z6dSjz-9-g_180.JPG: 480x640 (no detections), 301.0ms
Speed: 1.2ms preprocess, 301.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9iGY866D2n1Z6dSjz-9-g_270.JPG: 480x640 (no detections), 301.7ms
Speed: 1.2ms preprocess, 301.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9isRCG7raZkGxX3ihVOYA_0.JPG: 480x640 (no detections), 300.6ms
Speed: 1.1ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9isRCG7raZkGxX3ihVOYA_90.JPG: 480x640 (no detections), 296.9ms
Speed: 1.1ms preprocess, 296.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9isRCG7raZkGxX3ihVOYA_180.JPG: 480x640 (no detections), 302.2ms
Speed: 1.1ms preprocess, 302.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9isRCG7raZkGxX3ihVOYA_270.JPG: 480x640 (no detections), 298.7ms
Speed: 1.6ms preprocess, 298.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9ogrDurshU7cO-gZYZxMA_0.JPG: 480x640 (no detections), 299.6ms
Speed: 1.2ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9ogrDurshU7cO-gZYZxMA_90.JPG: 480x640 (no detections), 306.2ms
Speed: 1.2ms preprocess, 306.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9ogrDurshU7cO-gZYZxMA_180.JPG: 480x640 (no detections), 299.9ms
Speed: 1.1ms preprocess, 299.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9ogrDurshU7cO-gZYZxMA_270.JPG: 480x640 (no detections), 296.7ms
Speed: 1.2ms preprocess, 296.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9p-mQvkYfgp-UkXat7geg_0.JPG: 480x640 (no detections), 298.1ms
Speed: 1.1ms preprocess, 298.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9p-mQvkYfgp-UkXat7geg_90.JPG: 480x640 (no detections), 296.7ms
Speed: 1.6ms preprocess, 296.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9p-mQvkYfgp-UkXat7geg_180.JPG: 480x640 (no detections), 298.3ms
Speed: 1.2ms preprocess, 298.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9p-mQvkYfgp-UkXat7geg_270.JPG: 480x640 (no detections), 296.4ms
Speed: 1.2ms preprocess, 296.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9pm8-H9EqicrPtxAfZ9BA_0.JPG: 480x640 1 Waste, 295.6ms
Speed: 1.1ms preprocess, 295.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9pm8-H9EqicrPtxAfZ9BA_90.JPG: 480x640 (no detections), 299.4ms
Speed: 1.2ms preprocess, 299.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9pm8-H9EqicrPtxAfZ9BA_180.JPG: 480x640 (no detections), 299.5ms
Speed: 1.4ms preprocess, 299.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9pm8-H9EqicrPtxAfZ9BA_270.JPG: 480x640 (no detections), 299.3ms
Speed: 1.1ms preprocess, 299.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9ujv9_ZkFKQbJyFKG9hfQ_0.JPG: 480x640 (no detections), 291.3ms
Speed: 1.1ms preprocess, 291.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9ujv9_ZkFKQbJyFKG9hfQ_90.JPG: 480x640 (no detections), 298.4ms
Speed: 1.3ms preprocess, 298.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9ujv9_ZkFKQbJyFKG9hfQ_180.JPG: 480x640 (no detections), 298.7ms
Speed: 1.2ms preprocess, 298.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9ujv9_ZkFKQbJyFKG9hfQ_270.JPG: 480x640 (no detections), 321.1ms
Speed: 1.4ms preprocess, 321.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9y-JjuCvLWl9R9TwXNrcA_0.JPG: 480x640 (no detections), 296.9ms
Speed: 1.2ms preprocess, 296.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9y-JjuCvLWl9R9TwXNrcA_90.JPG: 480x640 (no detections), 296.0ms
Speed: 1.2ms preprocess, 296.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9y-JjuCvLWl9R9TwXNrcA_180.JPG: 480x640 (no detections), 293.0ms
Speed: 1.2ms preprocess, 293.0ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9y-JjuCvLWl9R9TwXNrcA_270.JPG: 480x640 (no detections), 293.9ms
Speed: 1.2ms preprocess, 293.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9zDQCOMJV6FQg2CjAfhng_0.JPG: 480x640 (no detections), 296.6ms
Speed: 1.1ms preprocess, 296.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9zDQCOMJV6FQg2CjAfhng_90.JPG: 480x640 (no detections), 296.0ms
Speed: 1.2ms preprocess, 296.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9zDQCOMJV6FQg2CjAfhng_180.JPG: 480x640 (no detections), 298.5ms
Speed: 1.2ms preprocess, 298.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/9/x9zDQCOMJV6FQg2CjAfhng_270.JPG: 480x640 (no detections), 302.3ms
Speed: 1.3ms preprocess, 302.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xA8VCbwPWMmaQDiDrcCQ0Q_0.JPG: 480x640 (no detections), 299.0ms
Speed: 1.2ms preprocess, 299.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xA8VCbwPWMmaQDiDrcCQ0Q_90.JPG: 480x640 (no detections), 300.1ms
Speed: 1.1ms preprocess, 300.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xA8VCbwPWMmaQDiDrcCQ0Q_180.JPG: 480x640 (no detections), 299.5ms
Speed: 1.3ms preprocess, 299.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xA8VCbwPWMmaQDiDrcCQ0Q_270.JPG: 480x640 (no detections), 296.4ms
Speed: 1.2ms preprocess, 296.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xA8mNQtR9MVSs9npzeTjrg_0.JPG: 480x640 (no detections), 301.7ms
Speed: 1.1ms preprocess, 301.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xA8mNQtR9MVSs9npzeTjrg_90.JPG: 480x640 (no detections), 299.6ms
Speed: 1.2ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xA8mNQtR9MVSs9npzeTjrg_180.JPG: 480x640 (no detections), 302.9ms
Speed: 1.2ms preprocess, 302.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xA8mNQtR9MVSs9npzeTjrg_270.JPG: 480x640 (no detections), 296.3ms
Speed: 1.2ms preprocess, 296.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAAYj5mo5aAivxuXh5xvrg_0.JPG: 480x640 (no detections), 300.9ms
Speed: 1.2ms preprocess, 300.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAAYj5mo5aAivxuXh5xvrg_90.JPG: 480x640 (no detections), 299.3ms
Speed: 1.0ms preprocess, 299.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAAYj5mo5aAivxuXh5xvrg_180.JPG: 480x640 (no detections), 297.8ms
Speed: 1.5ms preprocess, 297.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAAYj5mo5aAivxuXh5xvrg_270.JPG: 480x640 (no detections), 376.6ms
Speed: 1.2ms preprocess, 376.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAB8yk2NSrr68-FjBFdSSw_0.JPG: 480x640 (no detections), 296.9ms
Speed: 1.2ms preprocess, 296.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAB8yk2NSrr68-FjBFdSSw_90.JPG: 480x640 (no detections), 296.6ms
Speed: 1.4ms preprocess, 296.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAB8yk2NSrr68-FjBFdSSw_180.JPG: 480x640 (no detections), 302.0ms
Speed: 1.3ms preprocess, 302.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAB8yk2NSrr68-FjBFdSSw_270.JPG: 480x640 (no detections), 295.3ms
Speed: 1.2ms preprocess, 295.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xADNfG4Kuvy532BfxYY_Uw_0.JPG: 480x640 (no detections), 296.9ms
Speed: 1.1ms preprocess, 296.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xADNfG4Kuvy532BfxYY_Uw_90.JPG: 480x640 (no detections), 306.1ms

Speed: 1.2ms preprocess, 306.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xADNfG4Kuvy532BfxYY_Uw_180.JPG: 480x640 (no detections), 302.4ms
Speed: 1.2ms preprocess, 302.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xADNfG4Kuvy532BfxYY_Uw_270.JPG: 480x640 (no detections), 298.8ms
Speed: 1.6ms preprocess, 298.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAENXRnoGYsCwFrGSGN9QQ_0.JPG: 480x640 (no detections), 296.3ms
Speed: 1.2ms preprocess, 296.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAENXRnoGYsCwFrGSGN9QQ_90.JPG: 480x640 1 Waste, 295.9ms
Speed: 1.5ms preprocess, 295.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAENXRnoGYsCwFrGSGN9QQ_180.JPG: 480x640 (no detections), 296.1ms
Speed: 1.6ms preprocess, 296.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAENXRnoGYsCwFrGSGN9QQ_270.JPG: 480x640 (no detections), 301.8ms
Speed: 1.1ms preprocess, 301.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAFgpTMI39BmH4Sc9BYQsw_0.JPG: 480x640 (no detections), 298.5ms
Speed: 2.1ms preprocess, 298.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAFgpTMI39BmH4Sc9BYQsw_90.JPG: 480x640 (no detections), 297.0ms
Speed: 1.1ms preprocess, 297.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAFgpTMI39BmH4Sc9BYQsw_180.JPG: 480x640 (no detections), 293.3ms
Speed: 1.2ms preprocess, 293.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAFgpTMI39BmH4Sc9BYQsw_270.JPG: 480x640 (no detections), 296.8ms
Speed: 1.0ms preprocess, 296.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAHmJY5_yBm7v5nv8nfbFQ_0.JPG: 480x640 (no detections), 297.8ms
Speed: 1.1ms preprocess, 297.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAHmJY5_yBm7v5nv8nfbFQ_90.JPG: 480x640 (no detections), 300.1ms
Speed: 1.4ms preprocess, 300.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAHmJY5_yBm7v5nv8nfbFQ_180.JPG: 480x640 (no detections), 304.9ms
Speed: 1.2ms preprocess, 304.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAHmJY5_yBm7v5nv8nfbFQ_270.JPG: 480x640 (no detections), 287.7ms
Speed: 1.2ms preprocess, 287.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xATLhk003OzDiewWmydG_g_0.JPG: 480x640 (no detections), 299.3ms
Speed: 1.1ms preprocess, 299.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xATLhk003OzDiewWmydG_g_90.JPG: 480x640 (no detections), 294.8ms
Speed: 1.4ms preprocess, 294.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xATLhk003OzDiewWmydG_g_180.JPG: 480x640 (no detections), 296.6ms
Speed: 1.4ms preprocess, 296.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xATLhk003OzDiewWmydG_g_270.JPG: 480x640 (no detections), 294.7ms
Speed: 1.1ms preprocess, 294.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAWwidk2XUUSKWs0Hb5kZQ_0.JPG: 480x640 (no detections), 298.3ms
Speed: 1.2ms preprocess, 298.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAWwidk2XUUSKWs0Hb5kZQ_90.JPG: 480x640 (no detections), 298.0ms
Speed: 1.1ms preprocess, 298.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAWwidk2XUUSKWs0Hb5kZQ_180.JPG: 480x640 (no detections), 296.5ms
Speed: 1.1ms preprocess, 296.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAWwidk2XUUSKWs0Hb5kZQ_270.JPG: 480x640 (no detections), 298.6ms
Speed: 1.3ms preprocess, 298.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAX7F6Ku1sZfgXGwRw9CHg_0.JPG: 480x640 (no detections), 301.7ms
Speed: 1.2ms preprocess, 301.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAX7F6Ku1sZfgXGwRw9CHg_90.JPG: 480x640 (no detections), 294.2ms
Speed: 1.4ms preprocess, 294.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAX7F6Ku1sZfgXGwRw9CHg_180.JPG: 480x640 (no detections), 302.1ms
Speed: 1.4ms preprocess, 302.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAX7F6Ku1sZfgXGwRw9CHg_270.JPG: 480x640 (no detections), 308.2ms
Speed: 1.3ms preprocess, 308.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAYVqGtAqD49hZAiJUp5yA_0.JPG: 480x640 (no detections), 302.7ms
Speed: 1.2ms preprocess, 302.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAYVqGtAqD49hZAiJUp5yA_90.JPG: 480x640 (no detections), 296.4ms
Speed: 1.1ms preprocess, 296.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAYVqGtAqD49hZAiJUp5yA_180.JPG: 480x640 (no detections), 302.9ms
Speed: 1.2ms preprocess, 302.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAYVqGtAqD49hZAiJUp5yA_270.JPG: 480x640 (no detections), 302.4ms
Speed: 1.1ms preprocess, 302.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xA_WdVijt3bDmxrYh-MfgQ_0.JPG: 480x640 (no detections), 295.1ms
Speed: 1.1ms preprocess, 295.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xA_WdVijt3bDmxrYh-MfgQ_90.JPG: 480x640 (no detections), 297.4ms
Speed: 1.0ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xA_WdVijt3bDmxrYh-MfgQ_180.JPG: 480x640 (no detections), 299.6ms
Speed: 1.2ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xA_WdVijt3bDmxrYh-MfgQ_270.JPG: 480x640 (no detections), 295.3ms
Speed: 1.1ms preprocess, 295.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAaELBbc0hfYMMHud-I5aQ_0.JPG: 480x640 (no detections), 294.6ms
Speed: 1.1ms preprocess, 294.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAaELBbc0hfYMMHud-I5aQ_90.JPG: 480x640 (no detections), 297.2ms
Speed: 1.2ms preprocess, 297.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAaELBbc0hfYMMHud-I5aQ_180.JPG: 480x640 (no detections), 298.9ms
Speed: 1.3ms preprocess, 298.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAaELBbc0hfYMMHud-I5aQ_270.JPG: 480x640 1 Waste, 295.8ms
Speed: 1.2ms preprocess, 295.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAbUmMfyWgAki0oGOzcnsA_0.JPG: 480x640 (no detections), 296.1ms
Speed: 1.9ms preprocess, 296.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAbUmMfyWgAki0oGOzcnsA_90.JPG: 480x640 (no detections), 308.0ms
Speed: 1.2ms preprocess, 308.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAbUmMfyWgAki0oGOzcnsA_180.JPG: 480x640 (no detections), 295.2ms
Speed: 1.5ms preprocess, 295.2ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAbUmMfyWgAki0oGOzcnsA_270.JPG: 480x640 (no detections), 299.5ms
Speed: 1.3ms preprocess, 299.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAbhGsBC4MZvzFWaiyOCQQ_0.JPG: 480x640 (no detections), 304.9ms
Speed: 1.4ms preprocess, 304.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAbhGsBC4MZvzFWaiyOCQQ_90.JPG: 480x640 (no detections), 294.8ms
Speed: 1.1ms preprocess, 294.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAbhGsBC4MZvzFWaiyOCQQ_180.JPG: 480x640 (no detections), 297.8ms
Speed: 2.0ms preprocess, 297.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAbhGsBC4MZvzFWaiyOCQQ_270.JPG: 480x640 (no detections), 296.6ms
Speed: 1.1ms preprocess, 296.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAfdMF7np6rEY633fnVHMQ_0.JPG: 480x640 (no detections), 303.8ms
Speed: 1.0ms preprocess, 303.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAfdMF7np6rEY633fnVHMQ_90.JPG: 480x640 (no detections), 303.3ms
Speed: 1.1ms preprocess, 303.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAfdMF7np6rEY633fnVHMQ_180.JPG: 480x640 (no detections), 301.3ms
Speed: 1.1ms preprocess, 301.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAfdMF7np6rEY633fnVHMQ_270.JPG: 480x640 (no detections), 298.5ms
Speed: 1.4ms preprocess, 298.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAhKbbCsDEiGvx5BEY0H2A_0.JPG: 480x640 (no detections), 295.3ms
Speed: 1.4ms preprocess, 295.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAhKbbCsDEiGvx5BEY0H2A_90.JPG: 480x640 (no detections), 296.2ms
Speed: 1.1ms preprocess, 296.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAhKbbCsDEiGvx5BEY0H2A_180.JPG: 480x640 (no detections), 308.8ms
Speed: 1.1ms preprocess, 308.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAhKbbCsDEiGvx5BEY0H2A_270.JPG: 480x640 (no detections), 297.5ms
Speed: 1.2ms preprocess, 297.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAlpPHNfGEnITpvnaXU8vA_0.JPG: 480x640 (no detections), 295.5ms
Speed: 1.2ms preprocess, 295.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAlpPHNfGEnITpvnaXU8vA_90.JPG: 480x640 (no detections), 299.4ms
Speed: 1.2ms preprocess, 299.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAlpPHNfGEnITpvnaXU8vA_180.JPG: 480x640 (no detections), 297.8ms
Speed: 1.2ms preprocess, 297.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAlpPHNfGEnITpvnaXU8vA_270.JPG: 480x640 (no detections), 299.6ms
Speed: 1.4ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAmBjZ5G0_-LAaSqUWIVAA_0.JPG: 480x640 (no detections), 293.8ms
Speed: 1.4ms preprocess, 293.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAmBjZ5G0_-LAaSqUWIVAA_90.JPG: 480x640 (no detections), 301.2ms
Speed: 1.3ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAmBjZ5G0_-LAaSqUWIVAA_180.JPG: 480x640 (no detections), 300.3ms
Speed: 1.1ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAmBjZ5G0_-LAaSqUWIVAA_270.JPG: 480x640 (no detections), 300.2ms
Speed: 1.1ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAn17sGpAj41-d9Vbs5BKw_0.JPG: 480x640 (no detections), 305.9ms
Speed: 1.2ms preprocess, 305.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAn17sGpAj41-d9Vbs5BKw_90.JPG: 480x640 (no detections), 301.5ms
Speed: 1.3ms preprocess, 301.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAn17sGpAj41-d9Vbs5BKw_180.JPG: 480x640 (no detections), 303.2ms
Speed: 1.3ms preprocess, 303.2ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAn17sGpAj41-d9Vbs5BKw_270.JPG: 480x640 (no detections), 302.0ms
Speed: 1.2ms preprocess, 302.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAqBVfBJZ8wf--mDAFhAQw_0.JPG: 480x640 (no detections), 295.4ms

Speed: 1.0ms preprocess, 295.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAqBVfBJZ8wf--mDAFhAQw_90.JPG: 480x640 (no detections), 295.6ms
Speed: 1.4ms preprocess, 295.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAqBVfBJZ8wf--mDAFhAQw_180.JPG: 480x640 (no detections), 294.9ms
Speed: 1.2ms preprocess, 294.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAqBVfBJZ8wf--mDAFhAQw_270.JPG: 480x640 (no detections), 298.3ms
Speed: 1.8ms preprocess, 298.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAxghwnvFbXbShpz4CdCQQ_0.JPG: 480x640 (no detections), 300.0ms
Speed: 1.2ms preprocess, 300.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAxghwnvFbXbShpz4CdCQQ_90.JPG: 480x640 (no detections), 306.0ms
Speed: 1.2ms preprocess, 306.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAxghwnvFbXbShpz4CdCQQ_180.JPG: 480x640 (no detections), 299.4ms
Speed: 1.3ms preprocess, 299.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xAxghwnvFbXbShpz4CdCQQ_270.JPG: 480x640 (no detections), 297.1ms
Speed: 1.2ms preprocess, 297.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xB-VnCidPFMG_tPnYi-f8Q_0.JPG: 480x640 (no detections), 298.0ms
Speed: 1.1ms preprocess, 298.0ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xB-VnCidPFMG_tPnYi-f8Q_90.JPG: 480x640 (no detections), 303.0ms
Speed: 1.3ms preprocess, 303.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xB-VnCidPFMG_tPnYi-f8Q_180.JPG: 480x640 (no detections), 299.4ms
Speed: 1.1ms preprocess, 299.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xB-VnCidPFMG_tPnYi-f8Q_270.JPG: 480x640 (no detections), 301.9ms
Speed: 1.4ms preprocess, 301.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xB20Ww80JAAmzrChouFVwQ_0.JPG: 480x640 (no detections), 300.5ms
Speed: 1.3ms preprocess, 300.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xB20Ww80JAAmzrChouFVwQ_90.JPG: 480x640 (no detections), 298.1ms
Speed: 1.1ms preprocess, 298.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xB20Ww80JAAmzrChouFVwQ_180.JPG: 480x640 (no detections), 298.4ms
Speed: 1.4ms preprocess, 298.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xB20Ww80JAAmzrChouFVwQ_270.JPG: 480x640 (no detections), 293.2ms
Speed: 1.2ms preprocess, 293.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xB7f-tAc80P3e3prHWbVKw_0.JPG: 480x640 (no detections), 298.5ms
Speed: 1.2ms preprocess, 298.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xB7f-tAc80P3e3prHWbVKw_90.JPG: 480x640 (no detections), 294.9ms
Speed: 1.3ms preprocess, 294.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xB7f-tAc80P3e3prHWbVKw_180.JPG: 480x640 (no detections), 298.5ms
Speed: 1.1ms preprocess, 298.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xB7f-tAc80P3e3prHWbVKw_270.JPG: 480x640 (no detections), 302.4ms
Speed: 1.3ms preprocess, 302.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xB8XXt48gfrraOSPQ5BMKA_0.JPG: 480x640 (no detections), 294.9ms
Speed: 1.2ms preprocess, 294.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xB8XXt48gfrraOSPQ5BMKA_90.JPG: 480x640 (no detections), 300.9ms
Speed: 1.5ms preprocess, 300.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xB8XXt48gfrraOSPQ5BMKA_180.JPG: 480x640 (no detections), 305.6ms
Speed: 1.1ms preprocess, 305.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xB8XXt48gfrraOSPQ5BMKA_270.JPG: 480x640 (no detections), 295.9ms
Speed: 1.2ms preprocess, 295.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xB9SNQeduQCG6eqH6rcQKw_0.JPG: 480x640 (no detections), 297.9ms
Speed: 1.1ms preprocess, 297.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xB9SNQeduQCG6eqH6rcQKw_90.JPG: 480x640 (no detections), 307.0ms
Speed: 1.2ms preprocess, 307.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xB9SNQeduQCG6eqH6rcQKw_180.JPG: 480x640 (no detections), 303.5ms
Speed: 1.2ms preprocess, 303.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xB9SNQeduQCG6eqH6rcQKw_270.JPG: 480x640 (no detections), 301.8ms
Speed: 1.1ms preprocess, 301.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBDbQommI8xXaHI_vIjBhg_0.JPG: 480x640 (no detections), 294.2ms
Speed: 1.3ms preprocess, 294.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBDbQommI8xXaHI_vIjBhg_90.JPG: 480x640 (no detections), 300.2ms
Speed: 1.3ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBDbQommI8xXaHI_vIjBhg_180.JPG: 480x640 (no detections), 290.3ms
Speed: 1.1ms preprocess, 290.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBDbQommI8xXaHI_vIjBhg_270.JPG: 480x640 (no detections), 297.7ms
Speed: 1.7ms preprocess, 297.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBFZQLbpSq4-lWFcF08CBg_0.JPG: 480x640 (no detections), 299.3ms
Speed: 1.2ms preprocess, 299.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBFZQLbpSq4-lWFcF08CBg_90.JPG: 480x640 (no detections), 297.2ms
Speed: 1.1ms preprocess, 297.2ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBFZQLbpSq4-lWFcF08CBg_180.JPG: 480x640 (no detections), 304.7ms
Speed: 1.4ms preprocess, 304.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBFZQLbpSq4-lWFcF08CBg_270.JPG: 480x640 (no detections), 295.5ms
Speed: 1.2ms preprocess, 295.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBHWM-w1bnF1oQTAYUpe0g_0.JPG: 480x640 (no detections), 293.1ms
Speed: 1.7ms preprocess, 293.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBHWM-w1bnF1oQTAYUpe0g_90.JPG: 480x640 1 Waste, 296.1ms
Speed: 1.4ms preprocess, 296.1ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBHWM-w1bnF1oQTAYUpe0g_180.JPG: 480x640 1 Waste, 298.0ms
Speed: 1.2ms preprocess, 298.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBHWM-w1bnF1oQTAYUpe0g_270.JPG: 480x640 (no detections), 299.9ms
Speed: 1.1ms preprocess, 299.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBHnwtc5FyAN1VR-SSUi7Q_0.JPG: 480x640 (no detections), 297.9ms
Speed: 1.1ms preprocess, 297.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBHnwtc5FyAN1VR-SSUi7Q_90.JPG: 480x640 (no detections), 302.5ms
Speed: 1.7ms preprocess, 302.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBHnwtc5FyAN1VR-SSUi7Q_180.JPG: 480x640 (no detections), 299.6ms
Speed: 1.1ms preprocess, 299.6ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBHnwtc5FyAN1VR-SSUi7Q_270.JPG: 480x640 (no detections), 297.6ms
Speed: 1.1ms preprocess, 297.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBIJedkCP-9b-P6LyxGH6g_0.JPG: 480x640 (no detections), 302.1ms
Speed: 1.1ms preprocess, 302.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBIJedkCP-9b-P6LyxGH6g_90.JPG: 480x640 (no detections), 296.8ms
Speed: 1.2ms preprocess, 296.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBIJedkCP-9b-P6LyxGH6g_180.JPG: 480x640 (no detections), 296.2ms
Speed: 1.3ms preprocess, 296.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBIJedkCP-9b-P6LyxGH6g_270.JPG: 480x640 (no detections), 296.6ms
Speed: 1.1ms preprocess, 296.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBSlQ8X1u_BlS3JJ4lDxQw_0.JPG: 480x640 (no detections), 303.1ms
Speed: 1.2ms preprocess, 303.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBSlQ8X1u_BlS3JJ4lDxQw_90.JPG: 480x640 (no detections), 300.7ms
Speed: 1.3ms preprocess, 300.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBSlQ8X1u_BlS3JJ4lDxQw_180.JPG: 480x640 (no detections), 299.2ms
Speed: 1.2ms preprocess, 299.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBSlQ8X1u_BlS3JJ4lDxQw_270.JPG: 480x640 (no detections), 292.5ms
Speed: 1.1ms preprocess, 292.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBTYN1u-fsFRzjvu_ER8Mg_0.JPG: 480x640 (no detections), 302.8ms
Speed: 1.3ms preprocess, 302.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBTYN1u-fsFRzjvu_ER8Mg_90.JPG: 480x640 (no detections), 297.9ms
Speed: 1.1ms preprocess, 297.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBTYN1u-fsFRzjvu_ER8Mg_180.JPG: 480x640 (no detections), 299.0ms
Speed: 1.3ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBTYN1u-fsFRzjvu_ER8Mg_270.JPG: 480x640 (no detections), 300.3ms
Speed: 1.2ms preprocess, 300.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBU9HOoaECRK_G42hG1Npg_0.JPG: 480x640 (no detections), 298.5ms
Speed: 1.6ms preprocess, 298.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBU9HOoaECRK_G42hG1Npg_90.JPG: 480x640 (no detections), 294.6ms
Speed: 1.5ms preprocess, 294.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBU9HOoaECRK_G42hG1Npg_180.JPG: 480x640 (no detections), 301.5ms
Speed: 1.8ms preprocess, 301.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBU9HOoaECRK_G42hG1Npg_270.JPG: 480x640 (no detections), 299.8ms
Speed: 1.2ms preprocess, 299.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBaFQbtfA8jjtnkmALakFw_0.JPG: 480x640 (no detections), 305.9ms
Speed: 1.3ms preprocess, 305.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBaFQbtfA8jjtnkmALakFw_90.JPG: 480x640 (no detections), 301.0ms
Speed: 1.2ms preprocess, 301.0ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBaFQbtfA8jjtnkmALakFw_180.JPG: 480x640 (no detections), 297.0ms
Speed: 1.0ms preprocess, 297.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBaFQbtfA8jjtnkmALakFw_270.JPG: 480x640 (no detections), 295.6ms
Speed: 1.1ms preprocess, 295.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBadBTauQ3VFUCgzx3CJog_0.JPG: 480x640 (no detections), 302.7ms
Speed: 1.5ms preprocess, 302.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBadBTauQ3VFUCgzx3CJog_90.JPG: 480x640 (no detections), 306.6ms
Speed: 2.0ms preprocess, 306.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBadBTauQ3VFUCgzx3CJog_180.JPG: 480x640 (no detections), 298.8ms
Speed: 1.2ms preprocess, 298.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBadBTauQ3VFUCgzx3CJog_270.JPG: 480x640 (no detections), 298.4ms

Speed: 1.2ms preprocess, 298.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBbGwLftNAvKzVydRHfDbw_0.JPG: 480x640 (no detections), 297.9ms
Speed: 1.1ms preprocess, 297.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBbGwLftNAvKzVydRHfDbw_90.JPG: 480x640 (no detections), 298.8ms
Speed: 1.3ms preprocess, 298.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBbGwLftNAvKzVydRHfDbw_180.JPG: 480x640 (no detections), 301.0ms
Speed: 1.3ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBbGwLftNAvKzVydRHfDbw_270.JPG: 480x640 (no detections), 301.1ms
Speed: 1.1ms preprocess, 301.1ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBd1eHBea_Gz7CC2E4zSlA_0.JPG: 480x640 (no detections), 299.3ms
Speed: 1.1ms preprocess, 299.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBd1eHBea_Gz7CC2E4zSlA_90.JPG: 480x640 (no detections), 303.4ms
Speed: 1.0ms preprocess, 303.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBd1eHBea_Gz7CC2E4zSlA_180.JPG: 480x640 (no detections), 302.5ms
Speed: 1.2ms preprocess, 302.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBd1eHBea_Gz7CC2E4zSlA_270.JPG: 480x640 (no detections), 300.6ms
Speed: 1.3ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBeEUiGZiRJfocVqQU1kbg_0.JPG: 480x640 (no detections), 297.5ms
Speed: 1.1ms preprocess, 297.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBeEUiGZiRJfocVqQU1kbg_90.JPG: 480x640 (no detections), 296.4ms
Speed: 1.1ms preprocess, 296.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBeEUiGZiRJfocVqQU1kbg_180.JPG: 480x640 (no detections), 303.8ms
Speed: 1.1ms preprocess, 303.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBeEUiGZiRJfocVqQU1kbg_270.JPG: 480x640 (no detections), 301.5ms
Speed: 1.1ms preprocess, 301.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBl3eY7rYoMVEhWDSSZejA_0.JPG: 480x640 (no detections), 304.1ms
Speed: 1.1ms preprocess, 304.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBl3eY7rYoMVEhWDSSZejA_90.JPG: 480x640 (no detections), 300.9ms
Speed: 1.3ms preprocess, 300.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBl3eY7rYoMVEhWDSSZejA_180.JPG: 480x640 (no detections), 300.9ms
Speed: 1.5ms preprocess, 300.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBl3eY7rYoMVEhWDSSZejA_270.JPG: 480x640 (no detections), 299.2ms
Speed: 1.2ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBlJE_0K3IIkrQjEakX9Sw_0.JPG: 480x640 (no detections), 294.4ms
Speed: 1.1ms preprocess, 294.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBlJE_0K3IIkrQjEakX9Sw_90.JPG: 480x640 (no detections), 302.8ms
Speed: 1.2ms preprocess, 302.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBlJE_0K3IIkrQjEakX9Sw_180.JPG: 480x640 (no detections), 304.7ms
Speed: 1.2ms preprocess, 304.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBlJE_0K3IIkrQjEakX9Sw_270.JPG: 480x640 (no detections), 296.6ms
Speed: 1.1ms preprocess, 296.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBlnMo-0leUyWnfAbO3_9g_0.JPG: 480x640 (no detections), 302.7ms
Speed: 1.4ms preprocess, 302.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBlnMo-0leUyWnfAbO3_9g_90.JPG: 480x640 (no detections), 301.8ms
Speed: 1.3ms preprocess, 301.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBlnMo-0leUyWnfAbO3_9g_180.JPG: 480x640 (no detections), 306.0ms
Speed: 1.2ms preprocess, 306.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBlnMo-0leUyWnfAbO3_9g_270.JPG: 480x640 (no detections), 305.3ms
Speed: 1.5ms preprocess, 305.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBpckVA4igKxXFBCe_J6jA_0.JPG: 480x640 (no detections), 295.6ms
Speed: 2.6ms preprocess, 295.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBpckVA4igKxXFBCe_J6jA_90.JPG: 480x640 (no detections), 299.6ms
Speed: 1.1ms preprocess, 299.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBpckVA4igKxXFBCe_J6jA_180.JPG: 480x640 (no detections), 300.4ms
Speed: 1.2ms preprocess, 300.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBpckVA4igKxXFBCe_J6jA_270.JPG: 480x640 (no detections), 303.4ms
Speed: 1.1ms preprocess, 303.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBtYPOYEY8A8mI7VdGeCRQ_0.JPG: 480x640 (no detections), 300.5ms
Speed: 1.6ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBtYPOYEY8A8mI7VdGeCRQ_90.JPG: 480x640 (no detections), 301.6ms
Speed: 1.3ms preprocess, 301.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBtYPOYEY8A8mI7VdGeCRQ_180.JPG: 480x640 (no detections), 297.8ms
Speed: 1.9ms preprocess, 297.8ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBtYPOYEY8A8mI7VdGeCRQ_270.JPG: 480x640 (no detections), 308.7ms
Speed: 1.2ms preprocess, 308.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBvP0y-00tuWOER-egAb0A_0.JPG: 480x640 (no detections), 309.1ms
Speed: 1.1ms preprocess, 309.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBvP0y-00tuWOER-egAb0A_90.JPG: 480x640 (no detections), 298.7ms
Speed: 1.3ms preprocess, 298.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBvP0y-00tuWOER-egAb0A_180.JPG: 480x640 (no detections), 297.5ms
Speed: 1.2ms preprocess, 297.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBvP0y-00tuWOER-egAb0A_270.JPG: 480x640 (no detections), 300.1ms
Speed: 1.1ms preprocess, 300.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBx-1kKuZ8z9LExDTOq95A_0.JPG: 480x640 (no detections), 299.2ms
Speed: 1.2ms preprocess, 299.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBx-1kKuZ8z9LExDTOq95A_90.JPG: 480x640 (no detections), 308.8ms
Speed: 1.1ms preprocess, 308.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBx-1kKuZ8z9LExDTOq95A_180.JPG: 480x640 (no detections), 299.5ms
Speed: 1.2ms preprocess, 299.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xBx-1kKuZ8z9LExDTOq95A_270.JPG: 480x640 (no detections), 298.1ms
Speed: 1.1ms preprocess, 298.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xC1mPs3AtHII_fQzDbnT8A_0.JPG: 480x640 (no detections), 303.1ms
Speed: 1.2ms preprocess, 303.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xC1mPs3AtHII_fQzDbnT8A_90.JPG: 480x640 (no detections), 297.1ms
Speed: 1.2ms preprocess, 297.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xC1mPs3AtHII_fQzDbnT8A_180.JPG: 480x640 (no detections), 296.9ms
Speed: 1.1ms preprocess, 296.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xC1mPs3AtHII_fQzDbnT8A_270.JPG: 480x640 (no detections), 298.7ms
Speed: 1.3ms preprocess, 298.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xC1rItmNaAg8-37vm-HiaQ_0.JPG: 480x640 (no detections), 302.8ms
Speed: 1.2ms preprocess, 302.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xC1rItmNaAg8-37vm-HiaQ_90.JPG: 480x640 (no detections), 299.0ms
Speed: 1.1ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xC1rItmNaAg8-37vm-HiaQ_180.JPG: 480x640 (no detections), 300.9ms
Speed: 1.2ms preprocess, 300.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xC1rItmNaAg8-37vm-HiaQ_270.JPG: 480x640 (no detections), 299.9ms
Speed: 1.3ms preprocess, 299.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xC2Vjn2Lx-lHBp0EG4rvPg_0.JPG: 480x640 (no detections), 301.2ms
Speed: 1.5ms preprocess, 301.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xC2Vjn2Lx-lHBp0EG4rvPg_90.JPG: 480x640 (no detections), 295.0ms
Speed: 1.1ms preprocess, 295.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xC2Vjn2Lx-lHBp0EG4rvPg_180.JPG: 480x640 (no detections), 304.2ms
Speed: 1.2ms preprocess, 304.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xC2Vjn2Lx-lHBp0EG4rvPg_270.JPG: 480x640 (no detections), 298.7ms
Speed: 1.6ms preprocess, 298.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCBPLMvOFPBaJWVEpTJelw_0.JPG: 480x640 (no detections), 299.6ms
Speed: 1.1ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCBPLMvOFPBaJWVEpTJelw_90.JPG: 480x640 (no detections), 297.9ms
Speed: 1.1ms preprocess, 297.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCBPLMvOFPBaJWVEpTJelw_180.JPG: 480x640 (no detections), 297.5ms
Speed: 1.2ms preprocess, 297.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCBPLMvOFPBaJWVEpTJelw_270.JPG: 480x640 (no detections), 300.6ms
Speed: 1.1ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCOPYuw5j3Fz7grI0mphIA_0.JPG: 480x640 (no detections), 299.8ms
Speed: 1.2ms preprocess, 299.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCOPYuw5j3Fz7grI0mphIA_90.JPG: 480x640 (no detections), 298.6ms
Speed: 1.3ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCOPYuw5j3Fz7grI0mphIA_180.JPG: 480x640 (no detections), 299.4ms
Speed: 1.9ms preprocess, 299.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCOPYuw5j3Fz7grI0mphIA_270.JPG: 480x640 (no detections), 308.3ms
Speed: 1.3ms preprocess, 308.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCPgsoyrozu_C8yMaoKnvQ_0.JPG: 480x640 (no detections), 297.5ms
Speed: 1.2ms preprocess, 297.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCPgsoyrozu_C8yMaoKnvQ_90.JPG: 480x640 (no detections), 299.2ms
Speed: 1.2ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCPgsoyrozu_C8yMaoKnvQ_180.JPG: 480x640 (no detections), 299.2ms
Speed: 1.1ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCPgsoyrozu_C8yMaoKnvQ_270.JPG: 480x640 (no detections), 304.8ms
Speed: 1.2ms preprocess, 304.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCQnykOaaz1IHcAtaJqBtw_0.JPG: 480x640 (no detections), 303.5ms
Speed: 1.2ms preprocess, 303.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCQnykOaaz1IHcAtaJqBtw_90.JPG: 480x640 (no detections), 300.6ms
Speed: 1.2ms preprocess, 300.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCQnykOaaz1IHcAtaJqBtw_180.JPG: 480x640 (no detections), 302.3ms

Speed: 1.1ms preprocess, 302.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCQnykOaaz1IHcAtaJqBtw_270.JPG: 480x640 (no detections), 300.6ms
Speed: 1.0ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCSBHVbqUTTdhsayA0NPqA_0.JPG: 480x640 (no detections), 300.1ms
Speed: 1.2ms preprocess, 300.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCSBHVbqUTTdhsayA0NPqA_90.JPG: 480x640 (no detections), 305.4ms
Speed: 1.7ms preprocess, 305.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCSBHVbqUTTdhsayA0NPqA_180.JPG: 480x640 (no detections), 299.1ms
Speed: 1.5ms preprocess, 299.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCSBHVbqUTTdhsayA0NPqA_270.JPG: 480x640 (no detections), 301.0ms
Speed: 1.2ms preprocess, 301.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCcRwmAkIz-v5OTi3fMiKA_0.JPG: 480x640 (no detections), 302.7ms
Speed: 1.2ms preprocess, 302.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCcRwmAkIz-v5OTi3fMiKA_90.JPG: 480x640 (no detections), 294.3ms
Speed: 1.2ms preprocess, 294.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCcRwmAkIz-v5OTi3fMiKA_180.JPG: 480x640 (no detections), 301.5ms
Speed: 1.2ms preprocess, 301.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCcRwmAkIz-v5OTi3fMiKA_270.JPG: 480x640 (no detections), 305.5ms
Speed: 1.3ms preprocess, 305.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCfv860U5TiM5RLSJFhdeg_0.JPG: 480x640 (no detections), 308.1ms
Speed: 1.4ms preprocess, 308.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCfv860U5TiM5RLSJFhdeg_90.JPG: 480x640 (no detections), 303.1ms
Speed: 1.1ms preprocess, 303.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCfv860U5TiM5RLSJFhdeg_180.JPG: 480x640 (no detections), 302.4ms
Speed: 1.2ms preprocess, 302.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCfv860U5TiM5RLSJFhdeg_270.JPG: 480x640 (no detections), 305.8ms
Speed: 1.2ms preprocess, 305.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCjyYI_Ji8cyCEhaATmaQg_0.JPG: 480x640 (no detections), 304.9ms
Speed: 1.3ms preprocess, 304.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCjyYI_Ji8cyCEhaATmaQg_90.JPG: 480x640 (no detections), 298.5ms
Speed: 1.2ms preprocess, 298.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCjyYI_Ji8cyCEhaATmaQg_180.JPG: 480x640 (no detections), 298.4ms
Speed: 1.3ms preprocess, 298.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCjyYI_Ji8cyCEhaATmaQg_270.JPG: 480x640 (no detections), 302.9ms
Speed: 1.2ms preprocess, 302.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCkqRUW_zCO50PKHgeMFng_0.JPG: 480x640 (no detections), 298.1ms
Speed: 1.3ms preprocess, 298.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCkqRUW_zCO50PKHgeMFng_90.JPG: 480x640 (no detections), 297.4ms
Speed: 1.1ms preprocess, 297.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCkqRUW_zCO50PKHgeMFng_180.JPG: 480x640 (no detections), 299.3ms
Speed: 1.1ms preprocess, 299.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCkqRUW_zCO50PKHgeMFng_270.JPG: 480x640 (no detections), 300.1ms
Speed: 1.1ms preprocess, 300.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCpQLygR-91CBHvbElmJoQ_0.JPG: 480x640 2 Wastes, 300.7ms
Speed: 1.2ms preprocess, 300.7ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCpQLygR-91CBHvbElmJoQ_90.JPG: 480x640 (no detections), 303.7ms
Speed: 1.2ms preprocess, 303.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCpQLygR-91CBHvbElmJoQ_180.JPG: 480x640 1 Waste, 304.7ms
Speed: 1.8ms preprocess, 304.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCpQLygR-91CBHvbElmJoQ_270.JPG: 480x640 1 Waste, 299.0ms
Speed: 1.3ms preprocess, 299.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCqFSDfwZ-tIRSdE2l2GvA_0.JPG: 480x640 (no detections), 299.8ms
Speed: 1.3ms preprocess, 299.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCqFSDfwZ-tIRSdE2l2GvA_90.JPG: 480x640 (no detections), 297.0ms
Speed: 1.1ms preprocess, 297.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCqFSDfwZ-tIRSdE2l2GvA_180.JPG: 480x640 (no detections), 297.5ms
Speed: 1.3ms preprocess, 297.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCqFSDfwZ-tIRSdE2l2GvA_270.JPG: 480x640 (no detections), 295.6ms
Speed: 1.2ms preprocess, 295.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCuXhjep3zoAcWfiQU62pA_0.JPG: 480x640 (no detections), 295.5ms
Speed: 1.7ms preprocess, 295.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCuXhjep3zoAcWfiQU62pA_90.JPG: 480x640 (no detections), 301.6ms
Speed: 1.2ms preprocess, 301.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCuXhjep3zoAcWfiQU62pA_180.JPG: 480x640 (no detections), 303.2ms
Speed: 1.5ms preprocess, 303.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCuXhjep3zoAcWfiQU62pA_270.JPG: 480x640 (no detections), 300.8ms
Speed: 1.1ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCxbf55uXk6uBBgJXHE9Yg_0.JPG: 480x640 (no detections), 295.6ms
Speed: 1.4ms preprocess, 295.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCxbf55uXk6uBBgJXHE9Yg_90.JPG: 480x640 (no detections), 302.4ms
Speed: 1.2ms preprocess, 302.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCxbf55uXk6uBBgJXHE9Yg_180.JPG: 480x640 (no detections), 305.8ms
Speed: 1.3ms preprocess, 305.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCxbf55uXk6uBBgJXHE9Yg_270.JPG: 480x640 (no detections), 298.8ms
Speed: 1.2ms preprocess, 298.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCz1ZewLrhxpPKcKLgY2fw_0.JPG: 480x640 (no detections), 304.8ms
Speed: 1.1ms preprocess, 304.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCz1ZewLrhxpPKcKLgY2fw_90.JPG: 480x640 (no detections), 302.5ms
Speed: 1.2ms preprocess, 302.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCz1ZewLrhxpPKcKLgY2fw_180.JPG: 480x640 (no detections), 298.4ms
Speed: 1.2ms preprocess, 298.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xCz1ZewLrhxpPKcKLgY2fw_270.JPG: 480x640 (no detections), 301.9ms
Speed: 1.7ms preprocess, 301.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xD-FIAHzpQJC-4QOoZbjFQ_0.JPG: 480x640 (no detections), 300.0ms
Speed: 1.6ms preprocess, 300.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xD-FIAHzpQJC-4QOoZbjFQ_90.JPG: 480x640 (no detections), 298.7ms
Speed: 1.2ms preprocess, 298.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xD-FIAHzpQJC-4QOoZbjFQ_180.JPG: 480x640 (no detections), 300.2ms
Speed: 1.3ms preprocess, 300.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xD-FIAHzpQJC-4QOoZbjFQ_270.JPG: 480x640 (no detections), 297.2ms
Speed: 1.2ms preprocess, 297.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xD-IF0dArQYDAXuUM_AL5A_0.JPG: 480x640 1 Waste, 301.4ms
Speed: 1.3ms preprocess, 301.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xD-IF0dArQYDAXuUM_AL5A_90.JPG: 480x640 (no detections), 297.5ms
Speed: 1.4ms preprocess, 297.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xD-IF0dArQYDAXuUM_AL5A_180.JPG: 480x640 (no detections), 299.7ms
Speed: 1.2ms preprocess, 299.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xD-IF0dArQYDAXuUM_AL5A_270.JPG: 480x640 (no detections), 295.2ms
Speed: 1.2ms preprocess, 295.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xD0pfjCDmmd_BQZtKE12lg_0.JPG: 480x640 (no detections), 305.4ms
Speed: 1.2ms preprocess, 305.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xD0pfjCDmmd_BQZtKE12lg_90.JPG: 480x640 (no detections), 296.5ms
Speed: 1.1ms preprocess, 296.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xD0pfjCDmmd_BQZtKE12lg_180.JPG: 480x640 (no detections), 300.6ms
Speed: 1.3ms preprocess, 300.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xD0pfjCDmmd_BQZtKE12lg_270.JPG: 480x640 (no detections), 296.8ms
Speed: 1.1ms preprocess, 296.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xD3wyrXHjqrVC-h2lAeUaA_0.JPG: 480x640 (no detections), 301.7ms
Speed: 1.2ms preprocess, 301.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xD3wyrXHjqrVC-h2lAeUaA_90.JPG: 480x640 (no detections), 299.3ms
Speed: 1.2ms preprocess, 299.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xD3wyrXHjqrVC-h2lAeUaA_180.JPG: 480x640 (no detections), 297.3ms
Speed: 1.3ms preprocess, 297.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xD3wyrXHjqrVC-h2lAeUaA_270.JPG: 480x640 (no detections), 300.6ms
Speed: 1.1ms preprocess, 300.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xD568GR0wA2rFzeNcph0kg_0.JPG: 480x640 (no detections), 296.4ms
Speed: 1.4ms preprocess, 296.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xD568GR0wA2rFzeNcph0kg_90.JPG: 480x640 (no detections), 298.6ms
Speed: 1.1ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xD568GR0wA2rFzeNcph0kg_180.JPG: 480x640 (no detections), 296.9ms
Speed: 1.1ms preprocess, 296.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xD568GR0wA2rFzeNcph0kg_270.JPG: 480x640 1 Waste, 300.3ms
Speed: 1.2ms preprocess, 300.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xD5QKdmBOdgUovaS2hV-tg_0.JPG: 480x640 (no detections), 302.5ms
Speed: 1.1ms preprocess, 302.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xD5QKdmBOdgUovaS2hV-tg_90.JPG: 480x640 (no detections), 299.9ms
Speed: 1.0ms preprocess, 299.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xD5QKdmBOdgUovaS2hV-tg_180.JPG: 480x640 (no detections), 298.2ms
Speed: 1.6ms preprocess, 298.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xD5QKdmBOdgUovaS2hV-tg_270.JPG: 480x640 (no detections), 301.5ms
Speed: 1.2ms preprocess, 301.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xD6_w3JFriEG77WW7LwZBg_0.JPG: 480x640 (no detections), 296.4ms
Speed: 1.1ms preprocess, 296.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xD6_w3JFriEG77WW7LwZBg_90.JPG: 480x640 (no detections), 295.9ms

Speed: 1.1ms preprocess, 295.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xD6_w3JFriEG77WW7LwZBg_180.JPG: 480x640 (no detections), 302.1ms
Speed: 1.0ms preprocess, 302.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xD6_w3JFriEG77WW7LwZBg_270.JPG: 480x640 (no detections), 296.6ms
Speed: 1.1ms preprocess, 296.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xD7DVXp9-tu5oAwUKKrhpQ_0.JPG: 480x640 (no detections), 300.0ms
Speed: 1.1ms preprocess, 300.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xD7DVXp9-tu5oAwUKKrhpQ_90.JPG: 480x640 (no detections), 293.3ms
Speed: 1.2ms preprocess, 293.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xD7DVXp9-tu5oAwUKKrhpQ_180.JPG: 480x640 (no detections), 306.0ms
Speed: 1.3ms preprocess, 306.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xD7DVXp9-tu5oAwUKKrhpQ_270.JPG: 480x640 (no detections), 302.2ms
Speed: 1.3ms preprocess, 302.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDHAMmclKO59KggL1TZ8jw_0.JPG: 480x640 (no detections), 299.9ms
Speed: 1.1ms preprocess, 299.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDHAMmclKO59KggL1TZ8jw_90.JPG: 480x640 (no detections), 299.4ms
Speed: 1.3ms preprocess, 299.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDHAMmclKO59KggL1TZ8jw_180.JPG: 480x640 (no detections), 302.9ms
Speed: 1.7ms preprocess, 302.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDHAMmclKO59KggL1TZ8jw_270.JPG: 480x640 (no detections), 301.3ms
Speed: 1.2ms preprocess, 301.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDIRE_81ZwkAxtWq_Sd0hg_0.JPG: 480x640 (no detections), 302.8ms
Speed: 1.4ms preprocess, 302.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDIRE_81ZwkAxtWq_Sd0hg_90.JPG: 480x640 (no detections), 301.8ms
Speed: 1.1ms preprocess, 301.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDIRE_81ZwkAxtWq_Sd0hg_180.JPG: 480x640 (no detections), 297.5ms
Speed: 1.1ms preprocess, 297.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDIRE_81ZwkAxtWq_Sd0hg_270.JPG: 480x640 (no detections), 302.7ms
Speed: 1.4ms preprocess, 302.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDQSGK3XmKJs1UbmAeHeBA_0.JPG: 480x640 (no detections), 296.1ms
Speed: 1.1ms preprocess, 296.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDQSGK3XmKJs1UbmAeHeBA_90.JPG: 480x640 (no detections), 301.9ms
Speed: 1.0ms preprocess, 301.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDQSGK3XmKJs1UbmAeHeBA_180.JPG: 480x640 (no detections), 299.8ms
Speed: 1.2ms preprocess, 299.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDQSGK3XmKJs1UbmAeHeBA_270.JPG: 480x640 (no detections), 298.9ms
Speed: 1.2ms preprocess, 298.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDSDR89d87X01UWf6E102A_0.JPG: 480x640 (no detections), 297.1ms
Speed: 1.2ms preprocess, 297.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDSDR89d87X01UWf6E102A_90.JPG: 480x640 (no detections), 300.2ms
Speed: 1.3ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDSDR89d87X01UWf6E102A_180.JPG: 480x640 (no detections), 300.4ms
Speed: 1.1ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDSDR89d87X01UWf6E102A_270.JPG: 480x640 (no detections), 304.2ms
Speed: 1.4ms preprocess, 304.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDXlI9XqUu3wXZYZPa7Uyw_0.JPG: 480x640 (no detections), 299.3ms
Speed: 1.3ms preprocess, 299.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDXlI9XqUu3wXZYZPa7Uyw_90.JPG: 480x640 1 Waste, 301.4ms
Speed: 1.2ms preprocess, 301.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDXlI9XqUu3wXZYZPa7Uyw_180.JPG: 480x640 (no detections), 301.5ms
Speed: 1.2ms preprocess, 301.5ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDXlI9XqUu3wXZYZPa7Uyw_270.JPG: 480x640 (no detections), 293.8ms
Speed: 1.2ms preprocess, 293.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDZSkoJ1K1vTrriSG0mqgA_0.JPG: 480x640 (no detections), 295.8ms
Speed: 1.1ms preprocess, 295.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDZSkoJ1K1vTrriSG0mqgA_90.JPG: 480x640 (no detections), 297.6ms
Speed: 1.1ms preprocess, 297.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDZSkoJ1K1vTrriSG0mqgA_180.JPG: 480x640 (no detections), 299.9ms
Speed: 1.0ms preprocess, 299.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDZSkoJ1K1vTrriSG0mqgA_270.JPG: 480x640 (no detections), 296.8ms
Speed: 1.2ms preprocess, 296.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDaXJEhlXZ4D1LGSfx1pjQ_0.JPG: 480x640 (no detections), 297.4ms
Speed: 1.1ms preprocess, 297.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDaXJEhlXZ4D1LGSfx1pjQ_90.JPG: 480x640 (no detections), 294.9ms
Speed: 1.2ms preprocess, 294.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDaXJEhlXZ4D1LGSfx1pjQ_180.JPG: 480x640 (no detections), 299.2ms
Speed: 1.2ms preprocess, 299.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDaXJEhlXZ4D1LGSfx1pjQ_270.JPG: 480x640 (no detections), 304.4ms
Speed: 1.3ms preprocess, 304.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDfiXNx5oKnNF97_ID7TcQ_0.JPG: 480x640 (no detections), 306.5ms
Speed: 1.1ms preprocess, 306.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDfiXNx5oKnNF97_ID7TcQ_90.JPG: 480x640 (no detections), 294.7ms
Speed: 1.1ms preprocess, 294.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDfiXNx5oKnNF97_ID7TcQ_180.JPG: 480x640 (no detections), 304.6ms
Speed: 1.1ms preprocess, 304.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDfiXNx5oKnNF97_ID7TcQ_270.JPG: 480x640 (no detections), 297.9ms
Speed: 1.1ms preprocess, 297.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDgBW6m81V0SfifERViOxg_0.JPG: 480x640 (no detections), 300.1ms
Speed: 1.1ms preprocess, 300.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDgBW6m81V0SfifERViOxg_90.JPG: 480x640 (no detections), 299.9ms
Speed: 1.2ms preprocess, 299.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDgBW6m81V0SfifERViOxg_180.JPG: 480x640 1 Waste, 299.9ms
Speed: 1.4ms preprocess, 299.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDgBW6m81V0SfifERViOxg_270.JPG: 480x640 (no detections), 299.1ms
Speed: 1.1ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDjDlrPrYTSpAvFAy4OmSQ_0.JPG: 480x640 (no detections), 304.7ms
Speed: 1.3ms preprocess, 304.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDjDlrPrYTSpAvFAy4OmSQ_90.JPG: 480x640 (no detections), 298.1ms
Speed: 1.1ms preprocess, 298.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDjDlrPrYTSpAvFAy4OmSQ_180.JPG: 480x640 (no detections), 297.8ms
Speed: 1.1ms preprocess, 297.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDjDlrPrYTSpAvFAy4OmSQ_270.JPG: 480x640 (no detections), 299.3ms
Speed: 1.1ms preprocess, 299.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDjqaSRbQiYpHLAtEo3xRQ_0.JPG: 480x640 (no detections), 297.1ms
Speed: 1.0ms preprocess, 297.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDjqaSRbQiYpHLAtEo3xRQ_90.JPG: 480x640 (no detections), 302.6ms
Speed: 1.6ms preprocess, 302.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDjqaSRbQiYpHLAtEo3xRQ_180.JPG: 480x640 2 Wastes, 305.1ms
Speed: 1.1ms preprocess, 305.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDjqaSRbQiYpHLAtEo3xRQ_270.JPG: 480x640 2 Wastes, 303.9ms
Speed: 1.1ms preprocess, 303.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDmGrtZ89OtN4mv04iKbwg_0.JPG: 480x640 (no detections), 301.0ms
Speed: 1.0ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDmGrtZ89OtN4mv04iKbwg_90.JPG: 480x640 (no detections), 294.7ms
Speed: 1.1ms preprocess, 294.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDmGrtZ89OtN4mv04iKbwg_180.JPG: 480x640 (no detections), 301.6ms
Speed: 1.3ms preprocess, 301.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDmGrtZ89OtN4mv04iKbwg_270.JPG: 480x640 (no detections), 298.8ms
Speed: 1.1ms preprocess, 298.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDmeaYbzPrhPD-isFKEC8g_0.JPG: 480x640 (no detections), 296.6ms
Speed: 1.1ms preprocess, 296.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDmeaYbzPrhPD-isFKEC8g_90.JPG: 480x640 (no detections), 301.8ms
Speed: 1.3ms preprocess, 301.8ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDmeaYbzPrhPD-isFKEC8g_180.JPG: 480x640 (no detections), 297.9ms
Speed: 1.1ms preprocess, 297.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDmeaYbzPrhPD-isFKEC8g_270.JPG: 480x640 (no detections), 293.0ms
Speed: 1.2ms preprocess, 293.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDt40RpctoTfgKzzCGHFcw_0.JPG: 480x640 1 Waste, 299.2ms
Speed: 1.1ms preprocess, 299.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDt40RpctoTfgKzzCGHFcw_90.JPG: 480x640 (no detections), 295.2ms
Speed: 1.2ms preprocess, 295.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDt40RpctoTfgKzzCGHFcw_180.JPG: 480x640 (no detections), 296.7ms
Speed: 1.1ms preprocess, 296.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDt40RpctoTfgKzzCGHFcw_270.JPG: 480x640 (no detections), 303.1ms
Speed: 1.2ms preprocess, 303.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDtwGAVQmBmoqdKHUHnfBg_0.JPG: 480x640 (no detections), 300.1ms
Speed: 1.0ms preprocess, 300.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDtwGAVQmBmoqdKHUHnfBg_90.JPG: 480x640 (no detections), 299.4ms
Speed: 1.4ms preprocess, 299.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDtwGAVQmBmoqdKHUHnfBg_180.JPG: 480x640 (no detections), 298.9ms
Speed: 1.2ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDtwGAVQmBmoqdKHUHnfBg_270.JPG: 480x640 (no detections), 298.6ms
Speed: 1.1ms preprocess, 298.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDvRCYRXoh6j0cbIbjtLvA_0.JPG: 480x640 (no detections), 303.0ms

Speed: 1.2ms preprocess, 303.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDvRCYRXoh6j0cbIbjtLvA_90.JPG: 480x640 (no detections), 298.9ms
Speed: 1.2ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDvRCYRXoh6j0cbIbjtLvA_180.JPG: 480x640 (no detections), 293.5ms
Speed: 1.8ms preprocess, 293.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDvRCYRXoh6j0cbIbjtLvA_270.JPG: 480x640 (no detections), 292.6ms
Speed: 1.1ms preprocess, 292.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDxEnLAC8_Nvy1MINDhAGQ_0.JPG: 480x640 (no detections), 297.7ms
Speed: 1.4ms preprocess, 297.7ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDxEnLAC8_Nvy1MINDhAGQ_90.JPG: 480x640 (no detections), 303.4ms
Speed: 1.5ms preprocess, 303.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDxEnLAC8_Nvy1MINDhAGQ_180.JPG: 480x640 (no detections), 300.9ms
Speed: 1.9ms preprocess, 300.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDxEnLAC8_Nvy1MINDhAGQ_270.JPG: 480x640 (no detections), 300.5ms
Speed: 1.7ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDzyAK5xvkqPGEUnnGTnfQ_0.JPG: 480x640 (no detections), 298.2ms
Speed: 1.2ms preprocess, 298.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDzyAK5xvkqPGEUnnGTnfQ_90.JPG: 480x640 (no detections), 294.0ms
Speed: 1.2ms preprocess, 294.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDzyAK5xvkqPGEUnnGTnfQ_180.JPG: 480x640 (no detections), 300.3ms
Speed: 1.1ms preprocess, 300.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xDzyAK5xvkqPGEUnnGTnfQ_270.JPG: 480x640 (no detections), 295.7ms
Speed: 1.2ms preprocess, 295.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xE1MZfXeJ3xqZguDiIgomg_0.JPG: 480x640 (no detections), 295.5ms
Speed: 1.4ms preprocess, 295.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xE1MZfXeJ3xqZguDiIgomg_90.JPG: 480x640 (no detections), 294.2ms
Speed: 1.3ms preprocess, 294.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xE1MZfXeJ3xqZguDiIgomg_180.JPG: 480x640 (no detections), 297.3ms
Speed: 1.8ms preprocess, 297.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xE1MZfXeJ3xqZguDiIgomg_270.JPG: 480x640 (no detections), 298.7ms
Speed: 1.1ms preprocess, 298.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xE69OX-Vb8M2Lad581swyA_0.JPG: 480x640 (no detections), 296.7ms
Speed: 1.3ms preprocess, 296.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xE69OX-Vb8M2Lad581swyA_90.JPG: 480x640 (no detections), 299.4ms
Speed: 1.2ms preprocess, 299.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xE69OX-Vb8M2Lad581swyA_180.JPG: 480x640 (no detections), 305.4ms
Speed: 1.3ms preprocess, 305.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xE69OX-Vb8M2Lad581swyA_270.JPG: 480x640 (no detections), 303.5ms
Speed: 1.3ms preprocess, 303.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEBOweTesBa1zECuD2XdBg_0.JPG: 480x640 (no detections), 298.3ms
Speed: 1.1ms preprocess, 298.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEBOweTesBa1zECuD2XdBg_90.JPG: 480x640 (no detections), 301.2ms
Speed: 1.2ms preprocess, 301.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEBOweTesBa1zECuD2XdBg_180.JPG: 480x640 (no detections), 302.0ms
Speed: 1.2ms preprocess, 302.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEBOweTesBa1zECuD2XdBg_270.JPG: 480x640 (no detections), 307.4ms
Speed: 1.5ms preprocess, 307.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEDUTr86Vj-6_IN-22X9hw_0.JPG: 480x640 (no detections), 297.9ms
Speed: 1.3ms preprocess, 297.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEDUTr86Vj-6_IN-22X9hw_90.JPG: 480x640 (no detections), 295.6ms
Speed: 1.7ms preprocess, 295.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEDUTr86Vj-6_IN-22X9hw_180.JPG: 480x640 (no detections), 297.7ms
Speed: 1.2ms preprocess, 297.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEDUTr86Vj-6_IN-22X9hw_270.JPG: 480x640 (no detections), 296.8ms
Speed: 1.4ms preprocess, 296.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEEzWWlDpnI_dbgiR6I4sg_0.JPG: 480x640 (no detections), 299.4ms
Speed: 1.2ms preprocess, 299.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEEzWWlDpnI_dbgiR6I4sg_90.JPG: 480x640 (no detections), 300.5ms
Speed: 1.2ms preprocess, 300.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEEzWWlDpnI_dbgiR6I4sg_180.JPG: 480x640 (no detections), 297.5ms
Speed: 1.2ms preprocess, 297.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEEzWWlDpnI_dbgiR6I4sg_270.JPG: 480x640 (no detections), 301.5ms
Speed: 1.4ms preprocess, 301.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEKicA3f49iY_iKEJPGw1w_0.JPG: 480x640 (no detections), 299.7ms
Speed: 1.2ms preprocess, 299.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEKicA3f49iY_iKEJPGw1w_90.JPG: 480x640 (no detections), 302.0ms
Speed: 1.2ms preprocess, 302.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEKicA3f49iY_iKEJPGw1w_180.JPG: 480x640 (no detections), 297.2ms
Speed: 1.2ms preprocess, 297.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEKicA3f49iY_iKEJPGw1w_270.JPG: 480x640 (no detections), 299.4ms
Speed: 1.1ms preprocess, 299.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEL19MRUHWN0R97Cs0wi3w_0.JPG: 480x640 (no detections), 289.2ms
Speed: 1.1ms preprocess, 289.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEL19MRUHWN0R97Cs0wi3w_90.JPG: 480x640 (no detections), 291.4ms
Speed: 1.0ms preprocess, 291.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEL19MRUHWN0R97Cs0wi3w_180.JPG: 480x640 (no detections), 297.0ms
Speed: 1.3ms preprocess, 297.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEL19MRUHWN0R97Cs0wi3w_270.JPG: 480x640 (no detections), 306.8ms
Speed: 1.2ms preprocess, 306.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xENBFO81k-jFqn0EJO_QPg_0.JPG: 480x640 (no detections), 298.0ms
Speed: 1.1ms preprocess, 298.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xENBFO81k-jFqn0EJO_QPg_90.JPG: 480x640 (no detections), 298.0ms
Speed: 1.1ms preprocess, 298.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xENBFO81k-jFqn0EJO_QPg_180.JPG: 480x640 (no detections), 300.1ms
Speed: 1.4ms preprocess, 300.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xENBFO81k-jFqn0EJO_QPg_270.JPG: 480x640 (no detections), 297.7ms
Speed: 1.3ms preprocess, 297.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xER0Tiw2LDSnGGSk63dPOw_0.JPG: 480x640 1 Waste, 289.3ms
Speed: 1.2ms preprocess, 289.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xER0Tiw2LDSnGGSk63dPOw_90.JPG: 480x640 (no detections), 299.7ms
Speed: 1.4ms preprocess, 299.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xER0Tiw2LDSnGGSk63dPOw_180.JPG: 480x640 (no detections), 375.0ms
Speed: 1.2ms preprocess, 375.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xER0Tiw2LDSnGGSk63dPOw_270.JPG: 480x640 (no detections), 297.1ms
Speed: 1.9ms preprocess, 297.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEV43jWj_OZQ13miLciUxw_0.JPG: 480x640 (no detections), 305.2ms
Speed: 1.2ms preprocess, 305.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEV43jWj_OZQ13miLciUxw_90.JPG: 480x640 (no detections), 297.9ms
Speed: 1.2ms preprocess, 297.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEV43jWj_OZQ13miLciUxw_180.JPG: 480x640 (no detections), 301.9ms
Speed: 1.3ms preprocess, 301.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEV43jWj_OZQ13miLciUxw_270.JPG: 480x640 (no detections), 301.1ms
Speed: 1.3ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEWbNdafje-rsL4aD-zarQ_0.JPG: 480x640 (no detections), 295.4ms
Speed: 1.7ms preprocess, 295.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEWbNdafje-rsL4aD-zarQ_90.JPG: 480x640 (no detections), 295.8ms
Speed: 1.1ms preprocess, 295.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEWbNdafje-rsL4aD-zarQ_180.JPG: 480x640 (no detections), 298.2ms
Speed: 1.2ms preprocess, 298.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEWbNdafje-rsL4aD-zarQ_270.JPG: 480x640 (no detections), 294.7ms
Speed: 1.0ms preprocess, 294.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEZuEfyPs9Vnv7KYGc-_lQ_0.JPG: 480x640 (no detections), 299.3ms
Speed: 1.7ms preprocess, 299.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEZuEfyPs9Vnv7KYGc-_lQ_90.JPG: 480x640 (no detections), 306.6ms
Speed: 1.3ms preprocess, 306.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEZuEfyPs9Vnv7KYGc-_lQ_180.JPG: 480x640 (no detections), 307.2ms
Speed: 1.2ms preprocess, 307.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEZuEfyPs9Vnv7KYGc-_lQ_270.JPG: 480x640 (no detections), 304.0ms
Speed: 1.4ms preprocess, 304.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xE_X-Ra6y3TnNmhQrv4vNQ_0.JPG: 480x640 (no detections), 304.0ms
Speed: 1.1ms preprocess, 304.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xE_X-Ra6y3TnNmhQrv4vNQ_90.JPG: 480x640 (no detections), 314.2ms
Speed: 1.1ms preprocess, 314.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xE_X-Ra6y3TnNmhQrv4vNQ_180.JPG: 480x640 (no detections), 302.5ms
Speed: 1.2ms preprocess, 302.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xE_X-Ra6y3TnNmhQrv4vNQ_270.JPG: 480x640 (no detections), 302.8ms
Speed: 1.1ms preprocess, 302.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEaW_Ko5wcU4S1hN1xe-Ig_0.JPG: 480x640 (no detections), 303.1ms
Speed: 1.1ms preprocess, 303.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEaW_Ko5wcU4S1hN1xe-Ig_90.JPG: 480x640 (no detections), 302.5ms
Speed: 1.3ms preprocess, 302.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEaW_Ko5wcU4S1hN1xe-Ig_180.JPG: 480x640 (no detections), 304.6ms
Speed: 1.3ms preprocess, 304.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEaW_Ko5wcU4S1hN1xe-Ig_270.JPG: 480x640 (no detections), 302.0ms

Speed: 1.2ms preprocess, 302.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEasRoiLI1L7zF_v2caIAA_0.JPG: 480x640 (no detections), 322.3ms
Speed: 1.3ms preprocess, 322.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEasRoiLI1L7zF_v2caIAA_90.JPG: 480x640 (no detections), 338.9ms
Speed: 1.2ms preprocess, 338.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEasRoiLI1L7zF_v2caIAA_180.JPG: 480x640 (no detections), 303.7ms
Speed: 1.7ms preprocess, 303.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEasRoiLI1L7zF_v2caIAA_270.JPG: 480x640 (no detections), 299.0ms
Speed: 1.3ms preprocess, 299.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEb5wIdGzjDabLDP65evcg_0.JPG: 480x640 (no detections), 307.6ms
Speed: 1.1ms preprocess, 307.6ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEb5wIdGzjDabLDP65evcg_90.JPG: 480x640 (no detections), 308.1ms
Speed: 1.1ms preprocess, 308.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEb5wIdGzjDabLDP65evcg_180.JPG: 480x640 (no detections), 300.9ms
Speed: 1.1ms preprocess, 300.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEb5wIdGzjDabLDP65evcg_270.JPG: 480x640 (no detections), 294.3ms
Speed: 1.1ms preprocess, 294.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEe3zNrWUjrFHxZEHJYmRw_0.JPG: 480x640 (no detections), 304.8ms
Speed: 1.4ms preprocess, 304.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEe3zNrWUjrFHxZEHJYmRw_90.JPG: 480x640 (no detections), 302.9ms
Speed: 1.1ms preprocess, 302.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEe3zNrWUjrFHxZEHJYmRw_180.JPG: 480x640 (no detections), 297.9ms
Speed: 1.1ms preprocess, 297.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEe3zNrWUjrFHxZEHJYmRw_270.JPG: 480x640 (no detections), 306.2ms
Speed: 1.4ms preprocess, 306.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEfFu0IKJYOnG7au6839Zw_0.JPG: 480x640 (no detections), 292.8ms
Speed: 1.7ms preprocess, 292.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEfFu0IKJYOnG7au6839Zw_90.JPG: 480x640 (no detections), 299.4ms
Speed: 1.3ms preprocess, 299.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEfFu0IKJYOnG7au6839Zw_180.JPG: 480x640 (no detections), 297.7ms
Speed: 1.2ms preprocess, 297.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEfFu0IKJYOnG7au6839Zw_270.JPG: 480x640 (no detections), 295.1ms
Speed: 1.2ms preprocess, 295.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEl_h3Aj-qR345X3umvS9g_0.JPG: 480x640 (no detections), 293.9ms
Speed: 1.1ms preprocess, 293.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEl_h3Aj-qR345X3umvS9g_90.JPG: 480x640 (no detections), 305.3ms
Speed: 1.2ms preprocess, 305.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEl_h3Aj-qR345X3umvS9g_180.JPG: 480x640 (no detections), 299.8ms
Speed: 1.1ms preprocess, 299.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEl_h3Aj-qR345X3umvS9g_270.JPG: 480x640 (no detections), 309.5ms
Speed: 1.1ms preprocess, 309.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEnf0bRwBulOPZKFVz4BMg_0.JPG: 480x640 (no detections), 308.3ms
Speed: 1.6ms preprocess, 308.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEnf0bRwBulOPZKFVz4BMg_90.JPG: 480x640 (no detections), 297.0ms
Speed: 1.2ms preprocess, 297.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEnf0bRwBulOPZKFVz4BMg_180.JPG: 480x640 (no detections), 310.9ms
Speed: 1.2ms preprocess, 310.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEnf0bRwBulOPZKFVz4BMg_270.JPG: 480x640 (no detections), 304.8ms
Speed: 1.1ms preprocess, 304.8ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEqt4aev3cubN2Eo7L_Xog_0.JPG: 480x640 (no detections), 301.7ms
Speed: 1.1ms preprocess, 301.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEqt4aev3cubN2Eo7L_Xog_90.JPG: 480x640 (no detections), 299.6ms
Speed: 1.1ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEqt4aev3cubN2Eo7L_Xog_180.JPG: 480x640 1 Waste, 308.2ms
Speed: 1.5ms preprocess, 308.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEqt4aev3cubN2Eo7L_Xog_270.JPG: 480x640 (no detections), 302.9ms
Speed: 1.2ms preprocess, 302.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEtBw2Fr9dq9L0knmtkXDA_0.JPG: 480x640 (no detections), 305.1ms
Speed: 1.9ms preprocess, 305.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEtBw2Fr9dq9L0knmtkXDA_90.JPG: 480x640 (no detections), 299.9ms
Speed: 1.3ms preprocess, 299.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEtBw2Fr9dq9L0knmtkXDA_180.JPG: 480x640 (no detections), 313.4ms
Speed: 1.2ms preprocess, 313.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEtBw2Fr9dq9L0knmtkXDA_270.JPG: 480x640 (no detections), 300.3ms
Speed: 1.1ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEtmW1IgCtlLXvwX_jcPcA_0.JPG: 480x640 (no detections), 304.7ms
Speed: 1.3ms preprocess, 304.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEtmW1IgCtlLXvwX_jcPcA_90.JPG: 480x640 (no detections), 301.2ms
Speed: 1.3ms preprocess, 301.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEtmW1IgCtlLXvwX_jcPcA_180.JPG: 480x640 (no detections), 302.8ms
Speed: 1.1ms preprocess, 302.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEtmW1IgCtlLXvwX_jcPcA_270.JPG: 480x640 (no detections), 303.3ms
Speed: 1.0ms preprocess, 303.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEud0b54FBAiQnq_6dZhOQ_0.JPG: 480x640 (no detections), 305.0ms
Speed: 1.2ms preprocess, 305.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEud0b54FBAiQnq_6dZhOQ_90.JPG: 480x640 (no detections), 300.9ms
Speed: 1.2ms preprocess, 300.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEud0b54FBAiQnq_6dZhOQ_180.JPG: 480x640 (no detections), 304.9ms
Speed: 1.2ms preprocess, 304.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEud0b54FBAiQnq_6dZhOQ_270.JPG: 480x640 (no detections), 302.4ms
Speed: 1.1ms preprocess, 302.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEwA0LWAAebvSEJP7vAevA_0.JPG: 480x640 (no detections), 301.4ms
Speed: 1.1ms preprocess, 301.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEwA0LWAAebvSEJP7vAevA_90.JPG: 480x640 (no detections), 304.7ms
Speed: 1.0ms preprocess, 304.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEwA0LWAAebvSEJP7vAevA_180.JPG: 480x640 (no detections), 311.8ms
Speed: 1.4ms preprocess, 311.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEwA0LWAAebvSEJP7vAevA_270.JPG: 480x640 (no detections), 308.2ms
Speed: 1.2ms preprocess, 308.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xExCt97WuZTI7dGcguWTIA_0.JPG: 480x640 (no detections), 296.8ms
Speed: 1.1ms preprocess, 296.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xExCt97WuZTI7dGcguWTIA_90.JPG: 480x640 (no detections), 305.4ms
Speed: 1.1ms preprocess, 305.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xExCt97WuZTI7dGcguWTIA_180.JPG: 480x640 (no detections), 297.8ms
Speed: 1.3ms preprocess, 297.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xExCt97WuZTI7dGcguWTIA_270.JPG: 480x640 (no detections), 302.2ms
Speed: 1.2ms preprocess, 302.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEyiu5D1VfFMRVpUvKR9gg_0.JPG: 480x640 (no detections), 298.0ms
Speed: 1.3ms preprocess, 298.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEyiu5D1VfFMRVpUvKR9gg_90.JPG: 480x640 (no detections), 295.4ms
Speed: 1.5ms preprocess, 295.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEyiu5D1VfFMRVpUvKR9gg_180.JPG: 480x640 (no detections), 301.1ms
Speed: 1.3ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xEyiu5D1VfFMRVpUvKR9gg_270.JPG: 480x640 (no detections), 300.3ms
Speed: 1.9ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xF-DqqcViKF98MSB3VWtWQ_0.JPG: 480x640 (no detections), 299.2ms
Speed: 1.5ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xF-DqqcViKF98MSB3VWtWQ_90.JPG: 480x640 (no detections), 300.5ms
Speed: 1.1ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xF-DqqcViKF98MSB3VWtWQ_180.JPG: 480x640 (no detections), 296.8ms
Speed: 1.3ms preprocess, 296.8ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xF-DqqcViKF98MSB3VWtWQ_270.JPG: 480x640 2 Wastes, 299.7ms
Speed: 1.2ms preprocess, 299.7ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xF2rer9j3gG_cxuFz0ObiA_0.JPG: 480x640 (no detections), 300.2ms
Speed: 1.1ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xF2rer9j3gG_cxuFz0ObiA_90.JPG: 480x640 (no detections), 304.2ms
Speed: 1.1ms preprocess, 304.2ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xF2rer9j3gG_cxuFz0ObiA_180.JPG: 480x640 (no detections), 297.8ms
Speed: 1.2ms preprocess, 297.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xF2rer9j3gG_cxuFz0ObiA_270.JPG: 480x640 (no detections), 301.4ms
Speed: 1.1ms preprocess, 301.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xF4Kb3wZrOZsdWU6gsrYHg_0.JPG: 480x640 (no detections), 300.0ms
Speed: 1.5ms preprocess, 300.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xF4Kb3wZrOZsdWU6gsrYHg_90.JPG: 480x640 (no detections), 298.7ms
Speed: 1.2ms preprocess, 298.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xF4Kb3wZrOZsdWU6gsrYHg_180.JPG: 480x640 2 Wastes, 298.7ms
Speed: 1.9ms preprocess, 298.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xF4Kb3wZrOZsdWU6gsrYHg_270.JPG: 480x640 (no detections), 298.8ms
Speed: 1.1ms preprocess, 298.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xF7W9-skQze_84zLj4p5nA_0.JPG: 480x640 (no detections), 296.1ms
Speed: 1.1ms preprocess, 296.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xF7W9-skQze_84zLj4p5nA_90.JPG: 480x640 (no detections), 295.1ms
Speed: 1.2ms preprocess, 295.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xF7W9-skQze_84zLj4p5nA_180.JPG: 480x640 (no detections), 299.4ms

Speed: 1.4ms preprocess, 299.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xF7W9-skQze_84zLj4p5nA_270.JPG: 480x640 (no detections), 297.6ms
Speed: 1.2ms preprocess, 297.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xF7WDW1BhZgg6TQffp-1QA_0.JPG: 480x640 (no detections), 297.1ms
Speed: 1.5ms preprocess, 297.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xF7WDW1BhZgg6TQffp-1QA_90.JPG: 480x640 (no detections), 300.7ms
Speed: 1.4ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xF7WDW1BhZgg6TQffp-1QA_180.JPG: 480x640 (no detections), 295.9ms
Speed: 1.2ms preprocess, 295.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xF7WDW1BhZgg6TQffp-1QA_270.JPG: 480x640 (no detections), 296.2ms
Speed: 1.4ms preprocess, 296.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xF8E7zRYDZTkHUeS_MXkFg_0.JPG: 480x640 (no detections), 297.8ms
Speed: 1.1ms preprocess, 297.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xF8E7zRYDZTkHUeS_MXkFg_90.JPG: 480x640 (no detections), 295.8ms
Speed: 1.2ms preprocess, 295.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xF8E7zRYDZTkHUeS_MXkFg_180.JPG: 480x640 (no detections), 290.2ms
Speed: 1.1ms preprocess, 290.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xF8E7zRYDZTkHUeS_MXkFg_270.JPG: 480x640 (no detections), 291.0ms
Speed: 1.3ms preprocess, 291.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xF9DK5CFvdJvV7MOX6Ommg_0.JPG: 480x640 (no detections), 302.4ms
Speed: 1.3ms preprocess, 302.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xF9DK5CFvdJvV7MOX6Ommg_90.JPG: 480x640 (no detections), 295.0ms
Speed: 1.4ms preprocess, 295.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xF9DK5CFvdJvV7MOX6Ommg_180.JPG: 480x640 (no detections), 293.2ms
Speed: 1.1ms preprocess, 293.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xF9DK5CFvdJvV7MOX6Ommg_270.JPG: 480x640 (no detections), 299.1ms
Speed: 1.3ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xF9LISwMHYa8AAdRrkpW4A_0.JPG: 480x640 (no detections), 291.9ms
Speed: 1.1ms preprocess, 291.9ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xF9LISwMHYa8AAdRrkpW4A_90.JPG: 480x640 (no detections), 295.7ms
Speed: 1.2ms preprocess, 295.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xF9LISwMHYa8AAdRrkpW4A_180.JPG: 480x640 (no detections), 292.9ms
Speed: 1.1ms preprocess, 292.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xF9LISwMHYa8AAdRrkpW4A_270.JPG: 480x640 1 Waste, 296.4ms
Speed: 1.2ms preprocess, 296.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xF9XT7UsZTuB_bTMPfp25Q_0.JPG: 480x640 (no detections), 294.3ms
Speed: 1.3ms preprocess, 294.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xF9XT7UsZTuB_bTMPfp25Q_90.JPG: 480x640 (no detections), 300.1ms
Speed: 1.8ms preprocess, 300.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xF9XT7UsZTuB_bTMPfp25Q_180.JPG: 480x640 (no detections), 296.3ms
Speed: 1.5ms preprocess, 296.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xF9XT7UsZTuB_bTMPfp25Q_270.JPG: 480x640 (no detections), 297.8ms
Speed: 1.2ms preprocess, 297.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFG0NQbJZNq9jqwj5nv1BQ_0.JPG: 480x640 (no detections), 290.6ms
Speed: 1.1ms preprocess, 290.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFG0NQbJZNq9jqwj5nv1BQ_90.JPG: 480x640 (no detections), 293.8ms
Speed: 1.2ms preprocess, 293.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFG0NQbJZNq9jqwj5nv1BQ_180.JPG: 480x640 (no detections), 287.9ms
Speed: 1.0ms preprocess, 287.9ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFG0NQbJZNq9jqwj5nv1BQ_270.JPG: 480x640 (no detections), 292.0ms
Speed: 1.2ms preprocess, 292.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFHwojfrR6dHL0HvP7MzeQ_0.JPG: 480x640 (no detections), 294.5ms
Speed: 1.3ms preprocess, 294.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFHwojfrR6dHL0HvP7MzeQ_90.JPG: 480x640 (no detections), 290.3ms
Speed: 1.0ms preprocess, 290.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFHwojfrR6dHL0HvP7MzeQ_180.JPG: 480x640 (no detections), 293.0ms
Speed: 1.1ms preprocess, 293.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFHwojfrR6dHL0HvP7MzeQ_270.JPG: 480x640 (no detections), 293.4ms
Speed: 1.3ms preprocess, 293.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFJ2xMjIvLqBdF3Vhsel2A_0.JPG: 480x640 (no detections), 291.4ms
Speed: 1.2ms preprocess, 291.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFJ2xMjIvLqBdF3Vhsel2A_90.JPG: 480x640 (no detections), 292.0ms
Speed: 1.3ms preprocess, 292.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFJ2xMjIvLqBdF3Vhsel2A_180.JPG: 480x640 (no detections), 301.8ms
Speed: 1.3ms preprocess, 301.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFJ2xMjIvLqBdF3Vhsel2A_270.JPG: 480x640 (no detections), 297.3ms
Speed: 1.1ms preprocess, 297.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFJ5zqqFDHDAEFrKWZe9eg_0.JPG: 480x640 (no detections), 296.6ms
Speed: 1.2ms preprocess, 296.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFJ5zqqFDHDAEFrKWZe9eg_90.JPG: 480x640 (no detections), 293.8ms
Speed: 1.3ms preprocess, 293.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFJ5zqqFDHDAEFrKWZe9eg_180.JPG: 480x640 (no detections), 298.2ms
Speed: 1.9ms preprocess, 298.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFJ5zqqFDHDAEFrKWZe9eg_270.JPG: 480x640 1 Waste, 291.9ms
Speed: 1.2ms preprocess, 291.9ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFJhfMbPfFE_UpBrzduUig_0.JPG: 480x640 (no detections), 295.7ms
Speed: 1.2ms preprocess, 295.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFJhfMbPfFE_UpBrzduUig_90.JPG: 480x640 (no detections), 293.1ms
Speed: 1.2ms preprocess, 293.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFJhfMbPfFE_UpBrzduUig_180.JPG: 480x640 (no detections), 295.2ms
Speed: 1.3ms preprocess, 295.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFJhfMbPfFE_UpBrzduUig_270.JPG: 480x640 (no detections), 296.8ms
Speed: 1.8ms preprocess, 296.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFMaVyGqm11r3xGAmKSJNg_0.JPG: 480x640 (no detections), 293.3ms
Speed: 1.8ms preprocess, 293.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFMaVyGqm11r3xGAmKSJNg_90.JPG: 480x640 (no detections), 293.9ms
Speed: 1.2ms preprocess, 293.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFMaVyGqm11r3xGAmKSJNg_180.JPG: 480x640 (no detections), 295.5ms
Speed: 1.2ms preprocess, 295.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFMaVyGqm11r3xGAmKSJNg_270.JPG: 480x640 (no detections), 291.1ms
Speed: 1.3ms preprocess, 291.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFNAxyLS0dA3VUp5Im-WBQ_0.JPG: 480x640 (no detections), 301.2ms
Speed: 1.2ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFNAxyLS0dA3VUp5Im-WBQ_90.JPG: 480x640 (no detections), 294.0ms
Speed: 1.2ms preprocess, 294.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFNAxyLS0dA3VUp5Im-WBQ_180.JPG: 480x640 (no detections), 294.1ms
Speed: 1.4ms preprocess, 294.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFNAxyLS0dA3VUp5Im-WBQ_270.JPG: 480x640 (no detections), 293.5ms
Speed: 1.6ms preprocess, 293.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFOGfJsBPTiuBvEd6HanGg_0.JPG: 480x640 (no detections), 291.1ms
Speed: 1.3ms preprocess, 291.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFOGfJsBPTiuBvEd6HanGg_90.JPG: 480x640 (no detections), 297.5ms
Speed: 1.2ms preprocess, 297.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFOGfJsBPTiuBvEd6HanGg_180.JPG: 480x640 (no detections), 294.5ms
Speed: 1.2ms preprocess, 294.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFOGfJsBPTiuBvEd6HanGg_270.JPG: 480x640 (no detections), 291.3ms
Speed: 1.2ms preprocess, 291.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFQD-g-AOgnWnnltJQFu4g_0.JPG: 480x640 (no detections), 292.6ms
Speed: 1.3ms preprocess, 292.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFQD-g-AOgnWnnltJQFu4g_90.JPG: 480x640 (no detections), 292.4ms
Speed: 1.1ms preprocess, 292.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFQD-g-AOgnWnnltJQFu4g_180.JPG: 480x640 1 Waste, 294.1ms
Speed: 1.1ms preprocess, 294.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFQD-g-AOgnWnnltJQFu4g_270.JPG: 480x640 (no detections), 293.2ms
Speed: 1.1ms preprocess, 293.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFQLWU1NH1MIPfJaTUIeLw_0.JPG: 480x640 (no detections), 293.5ms
Speed: 1.3ms preprocess, 293.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFQLWU1NH1MIPfJaTUIeLw_90.JPG: 480x640 (no detections), 301.1ms
Speed: 1.7ms preprocess, 301.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFQLWU1NH1MIPfJaTUIeLw_180.JPG: 480x640 (no detections), 298.1ms
Speed: 1.3ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFQLWU1NH1MIPfJaTUIeLw_270.JPG: 480x640 (no detections), 294.6ms
Speed: 1.1ms preprocess, 294.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFZi5Ds4arUD5ZhMAvdZcg_0.JPG: 480x640 (no detections), 298.5ms
Speed: 1.2ms preprocess, 298.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFZi5Ds4arUD5ZhMAvdZcg_90.JPG: 480x640 (no detections), 294.0ms
Speed: 1.1ms preprocess, 294.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFZi5Ds4arUD5ZhMAvdZcg_180.JPG: 480x640 (no detections), 296.9ms
Speed: 1.3ms preprocess, 296.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFZi5Ds4arUD5ZhMAvdZcg_270.JPG: 480x640 (no detections), 290.3ms
Speed: 1.1ms preprocess, 290.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xF_2qvFuOdU17JnwIIvv2g_0.JPG: 480x640 (no detections), 291.5ms
Speed: 1.3ms preprocess, 291.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xF_2qvFuOdU17JnwIIvv2g_90.JPG: 480x640 (no detections), 294.0ms

Speed: 1.1ms preprocess, 294.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xF_2qvFuOdU17JnwIIvv2g_180.JPG: 480x640 (no detections), 294.0ms
Speed: 1.0ms preprocess, 294.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xF_2qvFuOdU17JnwIIvv2g_270.JPG: 480x640 (no detections), 294.2ms
Speed: 1.0ms preprocess, 294.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFaiiFbAFZgKP_4Zu69YFA_0.JPG: 480x640 (no detections), 296.4ms
Speed: 1.3ms preprocess, 296.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFaiiFbAFZgKP_4Zu69YFA_90.JPG: 480x640 (no detections), 299.3ms
Speed: 1.0ms preprocess, 299.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFaiiFbAFZgKP_4Zu69YFA_180.JPG: 480x640 (no detections), 300.9ms
Speed: 1.2ms preprocess, 300.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFaiiFbAFZgKP_4Zu69YFA_270.JPG: 480x640 (no detections), 291.1ms
Speed: 1.5ms preprocess, 291.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFcnqgYjPkEAoCOqiVPcGw_0.JPG: 480x640 (no detections), 297.2ms
Speed: 2.0ms preprocess, 297.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFcnqgYjPkEAoCOqiVPcGw_90.JPG: 480x640 (no detections), 293.7ms
Speed: 1.4ms preprocess, 293.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFcnqgYjPkEAoCOqiVPcGw_180.JPG: 480x640 (no detections), 297.7ms
Speed: 1.1ms preprocess, 297.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFcnqgYjPkEAoCOqiVPcGw_270.JPG: 480x640 (no detections), 293.8ms
Speed: 1.2ms preprocess, 293.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFdZaJR30B9HiYcM64xMyQ_0.JPG: 480x640 (no detections), 293.3ms
Speed: 1.2ms preprocess, 293.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFdZaJR30B9HiYcM64xMyQ_90.JPG: 480x640 (no detections), 294.3ms
Speed: 1.2ms preprocess, 294.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFdZaJR30B9HiYcM64xMyQ_180.JPG: 480x640 (no detections), 294.4ms
Speed: 1.1ms preprocess, 294.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFdZaJR30B9HiYcM64xMyQ_270.JPG: 480x640 (no detections), 295.0ms
Speed: 1.3ms preprocess, 295.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFfhPBa6ZrISzEix3q8egA_0.JPG: 480x640 (no detections), 293.0ms
Speed: 1.4ms preprocess, 293.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFfhPBa6ZrISzEix3q8egA_90.JPG: 480x640 (no detections), 295.8ms
Speed: 1.5ms preprocess, 295.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFfhPBa6ZrISzEix3q8egA_180.JPG: 480x640 (no detections), 292.4ms
Speed: 1.1ms preprocess, 292.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFfhPBa6ZrISzEix3q8egA_270.JPG: 480x640 (no detections), 291.2ms
Speed: 1.3ms preprocess, 291.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFgdBAZUksMHFMLiEUXgyA_0.JPG: 480x640 (no detections), 302.1ms
Speed: 1.2ms preprocess, 302.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFgdBAZUksMHFMLiEUXgyA_90.JPG: 480x640 (no detections), 293.3ms
Speed: 1.2ms preprocess, 293.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFgdBAZUksMHFMLiEUXgyA_180.JPG: 480x640 (no detections), 294.7ms
Speed: 1.3ms preprocess, 294.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFgdBAZUksMHFMLiEUXgyA_270.JPG: 480x640 (no detections), 293.6ms
Speed: 1.2ms preprocess, 293.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFgqRePZ7J4Juwyovg9W6g_0.JPG: 480x640 (no detections), 298.2ms
Speed: 1.0ms preprocess, 298.2ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFgqRePZ7J4Juwyovg9W6g_90.JPG: 480x640 (no detections), 290.4ms
Speed: 1.1ms preprocess, 290.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFgqRePZ7J4Juwyovg9W6g_180.JPG: 480x640 (no detections), 303.8ms
Speed: 1.3ms preprocess, 303.8ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFgqRePZ7J4Juwyovg9W6g_270.JPG: 480x640 (no detections), 293.6ms
Speed: 1.3ms preprocess, 293.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFhkYqEzVrv9qEWCQQg1lw_0.JPG: 480x640 (no detections), 291.3ms
Speed: 1.3ms preprocess, 291.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFhkYqEzVrv9qEWCQQg1lw_90.JPG: 480x640 (no detections), 294.6ms
Speed: 1.2ms preprocess, 294.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFhkYqEzVrv9qEWCQQg1lw_180.JPG: 480x640 (no detections), 298.2ms
Speed: 1.0ms preprocess, 298.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFhkYqEzVrv9qEWCQQg1lw_270.JPG: 480x640 (no detections), 299.6ms
Speed: 1.1ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFibWB2SBcVHz2C7a5-xQg_0.JPG: 480x640 (no detections), 290.0ms
Speed: 1.1ms preprocess, 290.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFibWB2SBcVHz2C7a5-xQg_90.JPG: 480x640 (no detections), 301.4ms
Speed: 1.3ms preprocess, 301.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFibWB2SBcVHz2C7a5-xQg_180.JPG: 480x640 (no detections), 291.1ms
Speed: 1.1ms preprocess, 291.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFibWB2SBcVHz2C7a5-xQg_270.JPG: 480x640 (no detections), 294.8ms
Speed: 1.1ms preprocess, 294.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFlmidJOnT99qWKo4eweSg_0.JPG: 480x640 (no detections), 296.4ms
Speed: 1.1ms preprocess, 296.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFlmidJOnT99qWKo4eweSg_90.JPG: 480x640 (no detections), 293.1ms
Speed: 1.2ms preprocess, 293.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFlmidJOnT99qWKo4eweSg_180.JPG: 480x640 (no detections), 291.8ms
Speed: 1.2ms preprocess, 291.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFlmidJOnT99qWKo4eweSg_270.JPG: 480x640 (no detections), 288.8ms
Speed: 1.1ms preprocess, 288.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFpUXPA17cF4e_RTYBGxyA_0.JPG: 480x640 (no detections), 292.4ms
Speed: 1.1ms preprocess, 292.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFpUXPA17cF4e_RTYBGxyA_90.JPG: 480x640 (no detections), 292.5ms
Speed: 1.3ms preprocess, 292.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFpUXPA17cF4e_RTYBGxyA_180.JPG: 480x640 (no detections), 297.6ms
Speed: 1.4ms preprocess, 297.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFpUXPA17cF4e_RTYBGxyA_270.JPG: 480x640 (no detections), 293.4ms
Speed: 1.2ms preprocess, 293.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFpd8CMExTkqRXKUESrMGg_0.JPG: 480x640 (no detections), 295.2ms
Speed: 1.2ms preprocess, 295.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFpd8CMExTkqRXKUESrMGg_90.JPG: 480x640 (no detections), 299.8ms
Speed: 1.2ms preprocess, 299.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFpd8CMExTkqRXKUESrMGg_180.JPG: 480x640 (no detections), 293.1ms
Speed: 1.2ms preprocess, 293.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFpd8CMExTkqRXKUESrMGg_270.JPG: 480x640 (no detections), 300.6ms
Speed: 1.2ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFqwMZp6tMZkFvo0jE9F5Q_0.JPG: 480x640 (no detections), 293.1ms
Speed: 1.1ms preprocess, 293.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFqwMZp6tMZkFvo0jE9F5Q_90.JPG: 480x640 (no detections), 290.5ms
Speed: 1.2ms preprocess, 290.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFqwMZp6tMZkFvo0jE9F5Q_180.JPG: 480x640 (no detections), 292.0ms
Speed: 1.3ms preprocess, 292.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFqwMZp6tMZkFvo0jE9F5Q_270.JPG: 480x640 (no detections), 289.2ms
Speed: 1.3ms preprocess, 289.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFrdVn25rr2QiIrmBTcsag_0.JPG: 480x640 (no detections), 293.1ms
Speed: 1.2ms preprocess, 293.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFrdVn25rr2QiIrmBTcsag_90.JPG: 480x640 (no detections), 294.8ms
Speed: 1.5ms preprocess, 294.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFrdVn25rr2QiIrmBTcsag_180.JPG: 480x640 (no detections), 293.6ms
Speed: 1.2ms preprocess, 293.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFrdVn25rr2QiIrmBTcsag_270.JPG: 480x640 (no detections), 294.0ms
Speed: 1.2ms preprocess, 294.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFs6UH7g3jl455R7P7w0QQ_0.JPG: 480x640 (no detections), 297.4ms
Speed: 1.1ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFs6UH7g3jl455R7P7w0QQ_90.JPG: 480x640 (no detections), 290.7ms
Speed: 1.1ms preprocess, 290.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFs6UH7g3jl455R7P7w0QQ_180.JPG: 480x640 (no detections), 291.3ms
Speed: 1.3ms preprocess, 291.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFs6UH7g3jl455R7P7w0QQ_270.JPG: 480x640 (no detections), 295.3ms
Speed: 1.1ms preprocess, 295.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFuYOeziSZOJtDKjwuy4oQ_0.JPG: 480x640 (no detections), 292.7ms
Speed: 1.3ms preprocess, 292.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFuYOeziSZOJtDKjwuy4oQ_90.JPG: 480x640 (no detections), 296.9ms
Speed: 1.2ms preprocess, 296.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFuYOeziSZOJtDKjwuy4oQ_180.JPG: 480x640 (no detections), 293.9ms
Speed: 1.3ms preprocess, 293.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFuYOeziSZOJtDKjwuy4oQ_270.JPG: 480x640 (no detections), 294.7ms
Speed: 1.2ms preprocess, 294.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFwhub1PRqJC0C07e7dZdw_0.JPG: 480x640 (no detections), 295.3ms
Speed: 1.1ms preprocess, 295.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFwhub1PRqJC0C07e7dZdw_90.JPG: 480x640 (no detections), 297.0ms
Speed: 1.1ms preprocess, 297.0ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFwhub1PRqJC0C07e7dZdw_180.JPG: 480x640 (no detections), 292.6ms
Speed: 1.3ms preprocess, 292.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFwhub1PRqJC0C07e7dZdw_270.JPG: 480x640 (no detections), 290.7ms
Speed: 1.2ms preprocess, 290.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFxG2NGj6k6U38ix44-AEQ_0.JPG: 480x640 (no detections), 297.3ms

Speed: 1.1ms preprocess, 297.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFxG2NGj6k6U38ix44-AEQ_90.JPG: 480x640 (no detections), 289.1ms
Speed: 1.0ms preprocess, 289.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFxG2NGj6k6U38ix44-AEQ_180.JPG: 480x640 (no detections), 295.1ms
Speed: 1.1ms preprocess, 295.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFxG2NGj6k6U38ix44-AEQ_270.JPG: 480x640 (no detections), 294.4ms
Speed: 1.2ms preprocess, 294.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFyskgyHji7a0okCFecxlQ_0.JPG: 480x640 (no detections), 300.4ms
Speed: 1.0ms preprocess, 300.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFyskgyHji7a0okCFecxlQ_90.JPG: 480x640 (no detections), 293.6ms
Speed: 1.1ms preprocess, 293.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFyskgyHji7a0okCFecxlQ_180.JPG: 480x640 (no detections), 296.9ms
Speed: 1.2ms preprocess, 296.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xFyskgyHji7a0okCFecxlQ_270.JPG: 480x640 (no detections), 295.0ms
Speed: 1.3ms preprocess, 295.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xG0EAj6jQm4Uuils0Y6G3A_0.JPG: 480x640 (no detections), 291.4ms
Speed: 1.1ms preprocess, 291.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xG0EAj6jQm4Uuils0Y6G3A_90.JPG: 480x640 (no detections), 294.2ms
Speed: 1.1ms preprocess, 294.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xG0EAj6jQm4Uuils0Y6G3A_180.JPG: 480x640 (no detections), 299.2ms
Speed: 1.3ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xG0EAj6jQm4Uuils0Y6G3A_270.JPG: 480x640 (no detections), 296.3ms
Speed: 1.1ms preprocess, 296.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xG0R_qZUCzbT6Jq0XEjUug_0.JPG: 480x640 (no detections), 293.4ms
Speed: 1.2ms preprocess, 293.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xG0R_qZUCzbT6Jq0XEjUug_90.JPG: 480x640 (no detections), 299.7ms
Speed: 1.1ms preprocess, 299.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xG0R_qZUCzbT6Jq0XEjUug_180.JPG: 480x640 (no detections), 293.1ms
Speed: 1.0ms preprocess, 293.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xG0R_qZUCzbT6Jq0XEjUug_270.JPG: 480x640 (no detections), 297.9ms
Speed: 1.2ms preprocess, 297.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xG3WNAL-zUIYqZWqWZVMmQ_0.JPG: 480x640 (no detections), 293.1ms
Speed: 1.1ms preprocess, 293.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xG3WNAL-zUIYqZWqWZVMmQ_90.JPG: 480x640 (no detections), 293.5ms
Speed: 1.1ms preprocess, 293.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xG3WNAL-zUIYqZWqWZVMmQ_180.JPG: 480x640 (no detections), 292.0ms
Speed: 1.1ms preprocess, 292.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xG3WNAL-zUIYqZWqWZVMmQ_270.JPG: 480x640 (no detections), 300.1ms
Speed: 1.2ms preprocess, 300.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xG4Z403a1u0WVRT4uV3VJQ_0.JPG: 480x640 (no detections), 298.2ms
Speed: 1.0ms preprocess, 298.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xG4Z403a1u0WVRT4uV3VJQ_90.JPG: 480x640 (no detections), 293.8ms
Speed: 1.2ms preprocess, 293.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xG4Z403a1u0WVRT4uV3VJQ_180.JPG: 480x640 (no detections), 295.7ms
Speed: 1.2ms preprocess, 295.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xG4Z403a1u0WVRT4uV3VJQ_270.JPG: 480x640 (no detections), 296.9ms
Speed: 1.3ms preprocess, 296.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xG9mVbxzUjWMZdUzq4bNdw_0.JPG: 480x640 (no detections), 290.0ms
Speed: 1.3ms preprocess, 290.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xG9mVbxzUjWMZdUzq4bNdw_90.JPG: 480x640 (no detections), 292.5ms
Speed: 1.3ms preprocess, 292.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xG9mVbxzUjWMZdUzq4bNdw_180.JPG: 480x640 (no detections), 292.5ms
Speed: 1.1ms preprocess, 292.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xG9mVbxzUjWMZdUzq4bNdw_270.JPG: 480x640 (no detections), 296.0ms
Speed: 1.1ms preprocess, 296.0ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGB_CLJzestAMAuRtoku3w_0.JPG: 480x640 (no detections), 299.8ms
Speed: 1.2ms preprocess, 299.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGB_CLJzestAMAuRtoku3w_90.JPG: 480x640 (no detections), 293.4ms
Speed: 1.2ms preprocess, 293.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGB_CLJzestAMAuRtoku3w_180.JPG: 480x640 (no detections), 294.7ms
Speed: 1.2ms preprocess, 294.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGB_CLJzestAMAuRtoku3w_270.JPG: 480x640 (no detections), 290.6ms
Speed: 1.1ms preprocess, 290.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGGoFMY6sv-JUBN5Kmca2Q_0.JPG: 480x640 (no detections), 301.7ms
Speed: 1.5ms preprocess, 301.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGGoFMY6sv-JUBN5Kmca2Q_90.JPG: 480x640 (no detections), 291.1ms
Speed: 1.2ms preprocess, 291.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGGoFMY6sv-JUBN5Kmca2Q_180.JPG: 480x640 (no detections), 292.3ms
Speed: 1.0ms preprocess, 292.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGGoFMY6sv-JUBN5Kmca2Q_270.JPG: 480x640 (no detections), 294.4ms
Speed: 1.2ms preprocess, 294.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGK6c_xRlByhCcbeykrQlA_0.JPG: 480x640 (no detections), 295.7ms
Speed: 1.2ms preprocess, 295.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGK6c_xRlByhCcbeykrQlA_90.JPG: 480x640 (no detections), 296.1ms
Speed: 1.5ms preprocess, 296.1ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGK6c_xRlByhCcbeykrQlA_180.JPG: 480x640 (no detections), 289.3ms
Speed: 1.1ms preprocess, 289.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGK6c_xRlByhCcbeykrQlA_270.JPG: 480x640 (no detections), 293.7ms
Speed: 1.2ms preprocess, 293.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGKlwagqH-V6lVL6jszlOQ_0.JPG: 480x640 (no detections), 292.7ms
Speed: 1.2ms preprocess, 292.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGKlwagqH-V6lVL6jszlOQ_90.JPG: 480x640 (no detections), 291.7ms
Speed: 1.1ms preprocess, 291.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGKlwagqH-V6lVL6jszlOQ_180.JPG: 480x640 (no detections), 292.0ms
Speed: 1.2ms preprocess, 292.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGKlwagqH-V6lVL6jszlOQ_270.JPG: 480x640 (no detections), 293.4ms
Speed: 1.1ms preprocess, 293.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGNwNaAJMMzK8DIUbtT4LQ_0.JPG: 480x640 (no detections), 290.8ms
Speed: 1.3ms preprocess, 290.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGNwNaAJMMzK8DIUbtT4LQ_90.JPG: 480x640 (no detections), 296.4ms
Speed: 1.1ms preprocess, 296.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGNwNaAJMMzK8DIUbtT4LQ_180.JPG: 480x640 (no detections), 298.1ms
Speed: 1.2ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGNwNaAJMMzK8DIUbtT4LQ_270.JPG: 480x640 (no detections), 298.4ms
Speed: 1.1ms preprocess, 298.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGQXXxohgZzCXxsrHZZozg_0.JPG: 480x640 (no detections), 295.6ms
Speed: 1.9ms preprocess, 295.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGQXXxohgZzCXxsrHZZozg_90.JPG: 480x640 (no detections), 295.1ms
Speed: 1.2ms preprocess, 295.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGQXXxohgZzCXxsrHZZozg_180.JPG: 480x640 (no detections), 299.9ms
Speed: 1.3ms preprocess, 299.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGQXXxohgZzCXxsrHZZozg_270.JPG: 480x640 (no detections), 290.9ms
Speed: 1.2ms preprocess, 290.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGSHHdDHouw1fAiUCIIJRw_0.JPG: 480x640 (no detections), 293.5ms
Speed: 1.2ms preprocess, 293.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGSHHdDHouw1fAiUCIIJRw_90.JPG: 480x640 (no detections), 294.3ms
Speed: 1.4ms preprocess, 294.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGSHHdDHouw1fAiUCIIJRw_180.JPG: 480x640 (no detections), 294.8ms
Speed: 1.1ms preprocess, 294.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGSHHdDHouw1fAiUCIIJRw_270.JPG: 480x640 (no detections), 296.9ms
Speed: 1.1ms preprocess, 296.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGSvJOts4q-8deGtVIOwjw_0.JPG: 480x640 (no detections), 295.8ms
Speed: 1.1ms preprocess, 295.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGSvJOts4q-8deGtVIOwjw_90.JPG: 480x640 (no detections), 293.5ms
Speed: 1.5ms preprocess, 293.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGSvJOts4q-8deGtVIOwjw_180.JPG: 480x640 2 Wastes, 292.5ms
Speed: 1.3ms preprocess, 292.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGSvJOts4q-8deGtVIOwjw_270.JPG: 480x640 (no detections), 295.2ms
Speed: 1.2ms preprocess, 295.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGUW_fhN-MtV6ADi3-VbEQ_0.JPG: 480x640 (no detections), 297.5ms
Speed: 1.1ms preprocess, 297.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGUW_fhN-MtV6ADi3-VbEQ_90.JPG: 480x640 (no detections), 291.4ms
Speed: 1.3ms preprocess, 291.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGUW_fhN-MtV6ADi3-VbEQ_180.JPG: 480x640 (no detections), 299.0ms
Speed: 1.2ms preprocess, 299.0ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGUW_fhN-MtV6ADi3-VbEQ_270.JPG: 480x640 (no detections), 289.8ms
Speed: 1.2ms preprocess, 289.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGXmfv98c5lK5s44Q-UzKA_0.JPG: 480x640 (no detections), 296.6ms
Speed: 1.0ms preprocess, 296.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGXmfv98c5lK5s44Q-UzKA_90.JPG: 480x640 (no detections), 295.9ms
Speed: 1.3ms preprocess, 295.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGXmfv98c5lK5s44Q-UzKA_180.JPG: 480x640 (no detections), 293.7ms
Speed: 1.3ms preprocess, 293.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGXmfv98c5lK5s44Q-UzKA_270.JPG: 480x640 (no detections), 297.9ms

Speed: 1.1ms preprocess, 297.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xG_hCK5bd7qr5UMfe0KwsA_0.JPG: 480x640 (no detections), 293.5ms
Speed: 1.2ms preprocess, 293.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xG_hCK5bd7qr5UMfe0KwsA_90.JPG: 480x640 (no detections), 294.6ms
Speed: 1.6ms preprocess, 294.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xG_hCK5bd7qr5UMfe0KwsA_180.JPG: 480x640 (no detections), 293.7ms
Speed: 1.2ms preprocess, 293.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xG_hCK5bd7qr5UMfe0KwsA_270.JPG: 480x640 (no detections), 292.4ms
Speed: 1.3ms preprocess, 292.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGb5Nazm7uClDkH1bIRfuw_0.JPG: 480x640 (no detections), 297.8ms
Speed: 1.3ms preprocess, 297.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGb5Nazm7uClDkH1bIRfuw_90.JPG: 480x640 (no detections), 298.7ms
Speed: 1.3ms preprocess, 298.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGb5Nazm7uClDkH1bIRfuw_180.JPG: 480x640 (no detections), 293.0ms
Speed: 1.4ms preprocess, 293.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGb5Nazm7uClDkH1bIRfuw_270.JPG: 480x640 (no detections), 289.4ms
Speed: 1.8ms preprocess, 289.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGdv4N7qRlbWrl3zeYeB-w_0.JPG: 480x640 (no detections), 295.2ms
Speed: 1.4ms preprocess, 295.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGdv4N7qRlbWrl3zeYeB-w_90.JPG: 480x640 (no detections), 295.9ms
Speed: 1.5ms preprocess, 295.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGdv4N7qRlbWrl3zeYeB-w_180.JPG: 480x640 (no detections), 291.6ms
Speed: 1.1ms preprocess, 291.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGdv4N7qRlbWrl3zeYeB-w_270.JPG: 480x640 (no detections), 293.6ms
Speed: 1.1ms preprocess, 293.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGdw8ICn8uGsENivouEeOQ_0.JPG: 480x640 (no detections), 299.5ms
Speed: 1.2ms preprocess, 299.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGdw8ICn8uGsENivouEeOQ_90.JPG: 480x640 (no detections), 291.8ms
Speed: 1.1ms preprocess, 291.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGdw8ICn8uGsENivouEeOQ_180.JPG: 480x640 (no detections), 299.4ms
Speed: 1.4ms preprocess, 299.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGdw8ICn8uGsENivouEeOQ_270.JPG: 480x640 (no detections), 298.0ms
Speed: 1.2ms preprocess, 298.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGjhIV8w2uUz5OlrBjl9Qg_0.JPG: 480x640 (no detections), 296.5ms
Speed: 1.2ms preprocess, 296.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGjhIV8w2uUz5OlrBjl9Qg_90.JPG: 480x640 (no detections), 293.4ms
Speed: 1.1ms preprocess, 293.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGjhIV8w2uUz5OlrBjl9Qg_180.JPG: 480x640 (no detections), 297.8ms
Speed: 1.3ms preprocess, 297.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGjhIV8w2uUz5OlrBjl9Qg_270.JPG: 480x640 (no detections), 293.5ms
Speed: 1.2ms preprocess, 293.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGlau-nz_wvTG9fDhcoYlg_0.JPG: 480x640 (no detections), 297.5ms
Speed: 1.1ms preprocess, 297.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGlau-nz_wvTG9fDhcoYlg_90.JPG: 480x640 (no detections), 298.1ms
Speed: 1.2ms preprocess, 298.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGlau-nz_wvTG9fDhcoYlg_180.JPG: 480x640 (no detections), 294.7ms
Speed: 1.3ms preprocess, 294.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGlau-nz_wvTG9fDhcoYlg_270.JPG: 480x640 (no detections), 295.7ms
Speed: 1.1ms preprocess, 295.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGpIS4u-18hDxfhql9cDIw_0.JPG: 480x640 (no detections), 295.2ms
Speed: 1.2ms preprocess, 295.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGpIS4u-18hDxfhql9cDIw_90.JPG: 480x640 (no detections), 294.4ms
Speed: 1.3ms preprocess, 294.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGpIS4u-18hDxfhql9cDIw_180.JPG: 480x640 (no detections), 291.9ms
Speed: 1.0ms preprocess, 291.9ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGpIS4u-18hDxfhql9cDIw_270.JPG: 480x640 (no detections), 289.7ms
Speed: 1.1ms preprocess, 289.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGpsVx25mXr8cQw6AugLOw_0.JPG: 480x640 (no detections), 296.8ms
Speed: 1.1ms preprocess, 296.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGpsVx25mXr8cQw6AugLOw_90.JPG: 480x640 (no detections), 295.8ms
Speed: 1.1ms preprocess, 295.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGpsVx25mXr8cQw6AugLOw_180.JPG: 480x640 (no detections), 293.1ms
Speed: 1.1ms preprocess, 293.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGpsVx25mXr8cQw6AugLOw_270.JPG: 480x640 (no detections), 297.7ms
Speed: 1.1ms preprocess, 297.7ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGtgxvW1HteBi5NAMhtoWw_0.JPG: 480x640 (no detections), 293.5ms
Speed: 1.2ms preprocess, 293.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGtgxvW1HteBi5NAMhtoWw_90.JPG: 480x640 (no detections), 295.5ms
Speed: 1.0ms preprocess, 295.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGtgxvW1HteBi5NAMhtoWw_180.JPG: 480x640 (no detections), 293.3ms
Speed: 1.4ms preprocess, 293.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGtgxvW1HteBi5NAMhtoWw_270.JPG: 480x640 (no detections), 296.6ms
Speed: 1.5ms preprocess, 296.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGvpkrAluIpP_Jk3hf8fPQ_0.JPG: 480x640 (no detections), 298.0ms
Speed: 1.6ms preprocess, 298.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGvpkrAluIpP_Jk3hf8fPQ_90.JPG: 480x640 (no detections), 298.8ms
Speed: 1.0ms preprocess, 298.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGvpkrAluIpP_Jk3hf8fPQ_180.JPG: 480x640 (no detections), 293.7ms
Speed: 1.3ms preprocess, 293.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGvpkrAluIpP_Jk3hf8fPQ_270.JPG: 480x640 (no detections), 295.8ms
Speed: 1.3ms preprocess, 295.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGwdxjpCXsIpo0h2lTI29Q_0.JPG: 480x640 (no detections), 293.0ms
Speed: 1.1ms preprocess, 293.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGwdxjpCXsIpo0h2lTI29Q_90.JPG: 480x640 1 Waste, 299.4ms
Speed: 1.2ms preprocess, 299.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGwdxjpCXsIpo0h2lTI29Q_180.JPG: 480x640 (no detections), 290.8ms
Speed: 1.0ms preprocess, 290.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGwdxjpCXsIpo0h2lTI29Q_270.JPG: 480x640 (no detections), 299.8ms
Speed: 1.2ms preprocess, 299.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGwf4g6YMqgTnIKaO7Lp4A_0.JPG: 480x640 (no detections), 296.4ms
Speed: 1.1ms preprocess, 296.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGwf4g6YMqgTnIKaO7Lp4A_90.JPG: 480x640 (no detections), 301.4ms
Speed: 1.0ms preprocess, 301.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGwf4g6YMqgTnIKaO7Lp4A_180.JPG: 480x640 (no detections), 292.1ms
Speed: 1.2ms preprocess, 292.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGwf4g6YMqgTnIKaO7Lp4A_270.JPG: 480x640 (no detections), 295.3ms
Speed: 1.1ms preprocess, 295.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGwp1yOCZ5OPErFTipFrNA_0.JPG: 480x640 (no detections), 294.7ms
Speed: 1.0ms preprocess, 294.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGwp1yOCZ5OPErFTipFrNA_90.JPG: 480x640 1 Waste, 294.7ms
Speed: 1.2ms preprocess, 294.7ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGwp1yOCZ5OPErFTipFrNA_180.JPG: 480x640 (no detections), 296.8ms
Speed: 1.3ms preprocess, 296.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGwp1yOCZ5OPErFTipFrNA_270.JPG: 480x640 (no detections), 296.9ms
Speed: 1.3ms preprocess, 296.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGx9n-YGMAJOmAAaHrGi1w_0.JPG: 480x640 (no detections), 294.5ms
Speed: 1.3ms preprocess, 294.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGx9n-YGMAJOmAAaHrGi1w_90.JPG: 480x640 (no detections), 293.8ms
Speed: 1.3ms preprocess, 293.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGx9n-YGMAJOmAAaHrGi1w_180.JPG: 480x640 (no detections), 290.9ms
Speed: 1.2ms preprocess, 290.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xGx9n-YGMAJOmAAaHrGi1w_270.JPG: 480x640 (no detections), 293.6ms
Speed: 1.1ms preprocess, 293.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xH00P9J3hUWIDPD-EV9HKA_0.JPG: 480x640 (no detections), 289.9ms
Speed: 1.1ms preprocess, 289.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xH00P9J3hUWIDPD-EV9HKA_90.JPG: 480x640 (no detections), 297.6ms
Speed: 1.1ms preprocess, 297.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xH00P9J3hUWIDPD-EV9HKA_180.JPG: 480x640 (no detections), 299.3ms
Speed: 1.0ms preprocess, 299.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xH00P9J3hUWIDPD-EV9HKA_270.JPG: 480x640 1 Waste, 295.8ms
Speed: 1.3ms preprocess, 295.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xH0I3GKvMtimub-ZTlq2zQ_0.JPG: 480x640 (no detections), 300.6ms
Speed: 1.4ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xH0I3GKvMtimub-ZTlq2zQ_90.JPG: 480x640 (no detections), 293.6ms
Speed: 1.5ms preprocess, 293.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xH0I3GKvMtimub-ZTlq2zQ_180.JPG: 480x640 (no detections), 296.3ms
Speed: 1.5ms preprocess, 296.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xH0I3GKvMtimub-ZTlq2zQ_270.JPG: 480x640 (no detections), 296.3ms
Speed: 1.2ms preprocess, 296.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xH2tgMV0SN-vGnXVkYATLQ_0.JPG: 480x640 (no detections), 293.7ms
Speed: 1.3ms preprocess, 293.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xH2tgMV0SN-vGnXVkYATLQ_90.JPG: 480x640 (no detections), 293.9ms
Speed: 1.3ms preprocess, 293.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xH2tgMV0SN-vGnXVkYATLQ_180.JPG: 480x640 (no detections), 295.7ms

Speed: 1.4ms preprocess, 295.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xH2tgMV0SN-vGnXVkYATLQ_270.JPG: 480x640 (no detections), 296.3ms
Speed: 1.2ms preprocess, 296.3ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xH7ualao60RlCigTE_PD1A_0.JPG: 480x640 (no detections), 291.4ms
Speed: 1.2ms preprocess, 291.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xH7ualao60RlCigTE_PD1A_90.JPG: 480x640 (no detections), 298.8ms
Speed: 1.2ms preprocess, 298.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xH7ualao60RlCigTE_PD1A_180.JPG: 480x640 (no detections), 297.9ms
Speed: 1.2ms preprocess, 297.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xH7ualao60RlCigTE_PD1A_270.JPG: 480x640 1 Waste, 303.8ms
Speed: 1.4ms preprocess, 303.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xH8wtzTobaNHmN_pwGxtSA_0.JPG: 480x640 (no detections), 295.9ms
Speed: 1.2ms preprocess, 295.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xH8wtzTobaNHmN_pwGxtSA_90.JPG: 480x640 (no detections), 296.1ms
Speed: 1.2ms preprocess, 296.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xH8wtzTobaNHmN_pwGxtSA_180.JPG: 480x640 (no detections), 292.9ms
Speed: 1.1ms preprocess, 292.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xH8wtzTobaNHmN_pwGxtSA_270.JPG: 480x640 (no detections), 292.0ms
Speed: 1.1ms preprocess, 292.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHEp1g_yruMAL1__gvoivg_0.JPG: 480x640 (no detections), 294.0ms
Speed: 1.8ms preprocess, 294.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHEp1g_yruMAL1__gvoivg_90.JPG: 480x640 (no detections), 300.9ms
Speed: 1.1ms preprocess, 300.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHEp1g_yruMAL1__gvoivg_180.JPG: 480x640 (no detections), 294.9ms
Speed: 1.2ms preprocess, 294.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHEp1g_yruMAL1__gvoivg_270.JPG: 480x640 (no detections), 301.3ms
Speed: 1.1ms preprocess, 301.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHH7LAeRllIMT_5VaQCpcQ_0.JPG: 480x640 (no detections), 292.4ms
Speed: 1.1ms preprocess, 292.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHH7LAeRllIMT_5VaQCpcQ_90.JPG: 480x640 (no detections), 293.8ms
Speed: 1.6ms preprocess, 293.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHH7LAeRllIMT_5VaQCpcQ_180.JPG: 480x640 (no detections), 300.3ms
Speed: 1.2ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHH7LAeRllIMT_5VaQCpcQ_270.JPG: 480x640 (no detections), 291.5ms
Speed: 1.6ms preprocess, 291.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHIndDDRAgs3VicYkObCfw_0.JPG: 480x640 (no detections), 290.4ms
Speed: 1.2ms preprocess, 290.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHIndDDRAgs3VicYkObCfw_90.JPG: 480x640 (no detections), 296.0ms
Speed: 1.1ms preprocess, 296.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHIndDDRAgs3VicYkObCfw_180.JPG: 480x640 (no detections), 296.7ms
Speed: 1.1ms preprocess, 296.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHIndDDRAgs3VicYkObCfw_270.JPG: 480x640 (no detections), 293.1ms
Speed: 1.0ms preprocess, 293.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHIty45hx1G1TMwWQZ1Vlg_0.JPG: 480x640 (no detections), 292.0ms
Speed: 1.2ms preprocess, 292.0ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHIty45hx1G1TMwWQZ1Vlg_90.JPG: 480x640 1 Waste, 292.4ms
Speed: 1.2ms preprocess, 292.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHIty45hx1G1TMwWQZ1Vlg_180.JPG: 480x640 (no detections), 296.3ms
Speed: 1.2ms preprocess, 296.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHIty45hx1G1TMwWQZ1Vlg_270.JPG: 480x640 (no detections), 293.5ms
Speed: 1.1ms preprocess, 293.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHK16u-FKKAro7V_jwpuqQ_0.JPG: 480x640 (no detections), 299.4ms
Speed: 1.1ms preprocess, 299.4ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHK16u-FKKAro7V_jwpuqQ_90.JPG: 480x640 (no detections), 298.8ms
Speed: 1.8ms preprocess, 298.8ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHK16u-FKKAro7V_jwpuqQ_180.JPG: 480x640 (no detections), 294.5ms
Speed: 1.2ms preprocess, 294.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHK16u-FKKAro7V_jwpuqQ_270.JPG: 480x640 (no detections), 292.3ms
Speed: 1.1ms preprocess, 292.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHK92ljQhTl4wL85SkYhxg_0.JPG: 480x640 (no detections), 286.3ms
Speed: 1.3ms preprocess, 286.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHK92ljQhTl4wL85SkYhxg_90.JPG: 480x640 (no detections), 294.7ms
Speed: 1.3ms preprocess, 294.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHK92ljQhTl4wL85SkYhxg_180.JPG: 480x640 1 Waste, 296.2ms
Speed: 1.3ms preprocess, 296.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHK92ljQhTl4wL85SkYhxg_270.JPG: 480x640 1 Waste, 293.3ms
Speed: 1.1ms preprocess, 293.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHOhJSzR0hP-nakvDPZMhw_0.JPG: 480x640 (no detections), 294.1ms
Speed: 1.1ms preprocess, 294.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHOhJSzR0hP-nakvDPZMhw_90.JPG: 480x640 (no detections), 300.8ms
Speed: 1.1ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHOhJSzR0hP-nakvDPZMhw_180.JPG: 480x640 (no detections), 290.6ms
Speed: 1.1ms preprocess, 290.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHOhJSzR0hP-nakvDPZMhw_270.JPG: 480x640 1 Waste, 289.3ms
Speed: 1.2ms preprocess, 289.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHQIF_4dUcFVlwCs_D5j6A_0.JPG: 480x640 (no detections), 298.3ms
Speed: 1.4ms preprocess, 298.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHQIF_4dUcFVlwCs_D5j6A_90.JPG: 480x640 (no detections), 299.8ms
Speed: 1.2ms preprocess, 299.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHQIF_4dUcFVlwCs_D5j6A_180.JPG: 480x640 (no detections), 299.7ms
Speed: 1.1ms preprocess, 299.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHQIF_4dUcFVlwCs_D5j6A_270.JPG: 480x640 (no detections), 291.6ms
Speed: 1.2ms preprocess, 291.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHQWT8glIO57WWax85Pwjw_0.JPG: 480x640 (no detections), 297.8ms
Speed: 1.5ms preprocess, 297.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHQWT8glIO57WWax85Pwjw_90.JPG: 480x640 (no detections), 290.1ms
Speed: 1.3ms preprocess, 290.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHQWT8glIO57WWax85Pwjw_180.JPG: 480x640 (no detections), 290.8ms
Speed: 1.2ms preprocess, 290.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHQWT8glIO57WWax85Pwjw_270.JPG: 480x640 (no detections), 294.7ms
Speed: 1.3ms preprocess, 294.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHRHr4Z2-Z5uRM4HjfqRMA_0.JPG: 480x640 (no detections), 303.1ms
Speed: 1.1ms preprocess, 303.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHRHr4Z2-Z5uRM4HjfqRMA_90.JPG: 480x640 (no detections), 290.2ms
Speed: 1.1ms preprocess, 290.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHRHr4Z2-Z5uRM4HjfqRMA_180.JPG: 480x640 (no detections), 299.1ms
Speed: 1.3ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHRHr4Z2-Z5uRM4HjfqRMA_270.JPG: 480x640 (no detections), 300.1ms
Speed: 1.3ms preprocess, 300.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHVYhJ2JqvHd_hvQFudhgQ_0.JPG: 480x640 (no detections), 295.5ms
Speed: 1.1ms preprocess, 295.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHVYhJ2JqvHd_hvQFudhgQ_90.JPG: 480x640 (no detections), 306.0ms
Speed: 1.1ms preprocess, 306.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHVYhJ2JqvHd_hvQFudhgQ_180.JPG: 480x640 (no detections), 313.6ms
Speed: 1.9ms preprocess, 313.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHVYhJ2JqvHd_hvQFudhgQ_270.JPG: 480x640 (no detections), 300.5ms
Speed: 1.2ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHVzfSvtGDloNq5D0flWLQ_0.JPG: 480x640 (no detections), 300.8ms
Speed: 1.3ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHVzfSvtGDloNq5D0flWLQ_90.JPG: 480x640 (no detections), 301.7ms
Speed: 1.4ms preprocess, 301.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHVzfSvtGDloNq5D0flWLQ_180.JPG: 480x640 (no detections), 302.2ms
Speed: 1.8ms preprocess, 302.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHVzfSvtGDloNq5D0flWLQ_270.JPG: 480x640 (no detections), 295.4ms
Speed: 1.5ms preprocess, 295.4ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHXyuob3ZJpNU0N3_Yhb1w_0.JPG: 480x640 (no detections), 301.2ms
Speed: 1.2ms preprocess, 301.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHXyuob3ZJpNU0N3_Yhb1w_90.JPG: 480x640 (no detections), 301.3ms
Speed: 1.1ms preprocess, 301.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHXyuob3ZJpNU0N3_Yhb1w_180.JPG: 480x640 (no detections), 299.8ms
Speed: 1.2ms preprocess, 299.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHXyuob3ZJpNU0N3_Yhb1w_270.JPG: 480x640 (no detections), 300.9ms
Speed: 1.5ms preprocess, 300.9ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHcq0gZ8qUibfjDiHjTkrQ_0.JPG: 480x640 (no detections), 383.4ms
Speed: 1.9ms preprocess, 383.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHcq0gZ8qUibfjDiHjTkrQ_90.JPG: 480x640 (no detections), 317.4ms
Speed: 1.5ms preprocess, 317.4ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHcq0gZ8qUibfjDiHjTkrQ_180.JPG: 480x640 (no detections), 301.2ms
Speed: 1.3ms preprocess, 301.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHcq0gZ8qUibfjDiHjTkrQ_270.JPG: 480x640 (no detections), 299.1ms
Speed: 1.1ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHf3C6JRDW9msoof29EdnQ_0.JPG: 480x640 (no detections), 297.5ms
Speed: 1.2ms preprocess, 297.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHf3C6JRDW9msoof29EdnQ_90.JPG: 480x640 (no detections), 300.6ms

Speed: 1.1ms preprocess, 300.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHf3C6JRDW9msoof29EdnQ_180.JPG: 480x640 (no detections), 301.2ms
Speed: 1.1ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHf3C6JRDW9msoof29EdnQ_270.JPG: 480x640 (no detections), 298.2ms
Speed: 1.2ms preprocess, 298.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHi7yYO18cLmzttdqAYAEw_0.JPG: 480x640 (no detections), 294.4ms
Speed: 1.1ms preprocess, 294.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHi7yYO18cLmzttdqAYAEw_90.JPG: 480x640 (no detections), 298.1ms
Speed: 1.1ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHi7yYO18cLmzttdqAYAEw_180.JPG: 480x640 (no detections), 303.0ms
Speed: 1.2ms preprocess, 303.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHi7yYO18cLmzttdqAYAEw_270.JPG: 480x640 (no detections), 297.9ms
Speed: 1.5ms preprocess, 297.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHlckU5fdFwJHP5qZaOgYA_0.JPG: 480x640 (no detections), 295.7ms
Speed: 1.1ms preprocess, 295.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHlckU5fdFwJHP5qZaOgYA_90.JPG: 480x640 (no detections), 297.4ms
Speed: 1.3ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHlckU5fdFwJHP5qZaOgYA_180.JPG: 480x640 (no detections), 301.7ms
Speed: 1.3ms preprocess, 301.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHlckU5fdFwJHP5qZaOgYA_270.JPG: 480x640 1 Waste, 296.9ms
Speed: 1.3ms preprocess, 296.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHnBr5_P88EjGjTzQ210_Q_0.JPG: 480x640 (no detections), 302.7ms
Speed: 1.3ms preprocess, 302.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHnBr5_P88EjGjTzQ210_Q_90.JPG: 480x640 (no detections), 311.2ms
Speed: 1.3ms preprocess, 311.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHnBr5_P88EjGjTzQ210_Q_180.JPG: 480x640 (no detections), 320.5ms
Speed: 1.2ms preprocess, 320.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHnBr5_P88EjGjTzQ210_Q_270.JPG: 480x640 (no detections), 304.8ms
Speed: 1.3ms preprocess, 304.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHnTplLmuFth4uy2HA65MQ_0.JPG: 480x640 (no detections), 303.0ms
Speed: 1.3ms preprocess, 303.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHnTplLmuFth4uy2HA65MQ_90.JPG: 480x640 (no detections), 312.3ms
Speed: 1.4ms preprocess, 312.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHnTplLmuFth4uy2HA65MQ_180.JPG: 480x640 (no detections), 300.1ms
Speed: 1.1ms preprocess, 300.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHnTplLmuFth4uy2HA65MQ_270.JPG: 480x640 (no detections), 304.8ms
Speed: 1.2ms preprocess, 304.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHqd4KoFcEcE3nI733WE9w_0.JPG: 480x640 (no detections), 306.0ms
Speed: 1.4ms preprocess, 306.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHqd4KoFcEcE3nI733WE9w_90.JPG: 480x640 (no detections), 295.3ms
Speed: 1.1ms preprocess, 295.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHqd4KoFcEcE3nI733WE9w_180.JPG: 480x640 1 Waste, 293.8ms
Speed: 1.1ms preprocess, 293.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHqd4KoFcEcE3nI733WE9w_270.JPG: 480x640 (no detections), 297.1ms
Speed: 1.2ms preprocess, 297.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHqigasfz53xANpMe5W59Q_0.JPG: 480x640 (no detections), 299.1ms
Speed: 1.3ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHqigasfz53xANpMe5W59Q_90.JPG: 480x640 (no detections), 306.6ms
Speed: 1.1ms preprocess, 306.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHqigasfz53xANpMe5W59Q_180.JPG: 480x640 (no detections), 320.7ms
Speed: 1.3ms preprocess, 320.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHqigasfz53xANpMe5W59Q_270.JPG: 480x640 (no detections), 311.3ms
Speed: 1.1ms preprocess, 311.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHxyg10OwPSwkB-FcyFcpQ_0.JPG: 480x640 (no detections), 302.0ms
Speed: 1.3ms preprocess, 302.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHxyg10OwPSwkB-FcyFcpQ_90.JPG: 480x640 (no detections), 301.9ms
Speed: 1.1ms preprocess, 301.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHxyg10OwPSwkB-FcyFcpQ_180.JPG: 480x640 (no detections), 303.4ms
Speed: 1.4ms preprocess, 303.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHxyg10OwPSwkB-FcyFcpQ_270.JPG: 480x640 (no detections), 297.7ms
Speed: 1.3ms preprocess, 297.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHy2dYSCKZzD74HIuMzXHg_0.JPG: 480x640 (no detections), 302.9ms
Speed: 1.2ms preprocess, 302.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHy2dYSCKZzD74HIuMzXHg_90.JPG: 480x640 (no detections), 292.8ms
Speed: 1.1ms preprocess, 292.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHy2dYSCKZzD74HIuMzXHg_180.JPG: 480x640 (no detections), 300.4ms
Speed: 1.1ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHy2dYSCKZzD74HIuMzXHg_270.JPG: 480x640 (no detections), 293.9ms
Speed: 1.1ms preprocess, 293.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHygRt0oMbABDFqrJF2yZQ_0.JPG: 480x640 (no detections), 296.3ms
Speed: 1.1ms preprocess, 296.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHygRt0oMbABDFqrJF2yZQ_90.JPG: 480x640 (no detections), 296.0ms
Speed: 1.1ms preprocess, 296.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHygRt0oMbABDFqrJF2yZQ_180.JPG: 480x640 (no detections), 295.0ms
Speed: 1.1ms preprocess, 295.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xHygRt0oMbABDFqrJF2yZQ_270.JPG: 480x640 (no detections), 301.4ms
Speed: 1.2ms preprocess, 301.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xI1IBTsZ_bow6C-1WMwopw_0.JPG: 480x640 (no detections), 303.4ms
Speed: 1.1ms preprocess, 303.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xI1IBTsZ_bow6C-1WMwopw_90.JPG: 480x640 (no detections), 304.4ms
Speed: 1.2ms preprocess, 304.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xI1IBTsZ_bow6C-1WMwopw_180.JPG: 480x640 (no detections), 305.6ms
Speed: 1.1ms preprocess, 305.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xI1IBTsZ_bow6C-1WMwopw_270.JPG: 480x640 (no detections), 307.9ms
Speed: 1.1ms preprocess, 307.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xI43oVQTWxxBe2j_vti0-A_0.JPG: 480x640 (no detections), 303.7ms
Speed: 1.3ms preprocess, 303.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xI43oVQTWxxBe2j_vti0-A_90.JPG: 480x640 (no detections), 304.5ms
Speed: 1.4ms preprocess, 304.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xI43oVQTWxxBe2j_vti0-A_180.JPG: 480x640 (no detections), 308.7ms
Speed: 1.1ms preprocess, 308.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xI43oVQTWxxBe2j_vti0-A_270.JPG: 480x640 (no detections), 322.9ms
Speed: 1.7ms preprocess, 322.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xI68hCvAfVM0xJ6uMRLo8Q_0.JPG: 480x640 (no detections), 307.2ms
Speed: 1.1ms preprocess, 307.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xI68hCvAfVM0xJ6uMRLo8Q_90.JPG: 480x640 (no detections), 301.4ms
Speed: 1.2ms preprocess, 301.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xI68hCvAfVM0xJ6uMRLo8Q_180.JPG: 480x640 (no detections), 302.7ms
Speed: 1.2ms preprocess, 302.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xI68hCvAfVM0xJ6uMRLo8Q_270.JPG: 480x640 (no detections), 313.7ms
Speed: 1.1ms preprocess, 313.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xI6CASuAqulcnWPJCA9Rwg_0.JPG: 480x640 (no detections), 377.3ms
Speed: 2.3ms preprocess, 377.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xI6CASuAqulcnWPJCA9Rwg_90.JPG: 480x640 (no detections), 322.5ms
Speed: 1.4ms preprocess, 322.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xI6CASuAqulcnWPJCA9Rwg_180.JPG: 480x640 (no detections), 335.3ms
Speed: 1.1ms preprocess, 335.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xI6CASuAqulcnWPJCA9Rwg_270.JPG: 480x640 (no detections), 354.9ms
Speed: 1.6ms preprocess, 354.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xI8wlyPlm_zdB9WpuXfODw_0.JPG: 480x640 (no detections), 328.5ms
Speed: 1.7ms preprocess, 328.5ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xI8wlyPlm_zdB9WpuXfODw_90.JPG: 480x640 (no detections), 329.6ms
Speed: 1.2ms preprocess, 329.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xI8wlyPlm_zdB9WpuXfODw_180.JPG: 480x640 (no detections), 310.3ms
Speed: 1.5ms preprocess, 310.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xI8wlyPlm_zdB9WpuXfODw_270.JPG: 480x640 (no detections), 296.4ms
Speed: 1.3ms preprocess, 296.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIATMxw9txv5SxxKI4I1hA_0.JPG: 480x640 (no detections), 299.2ms
Speed: 1.1ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIATMxw9txv5SxxKI4I1hA_90.JPG: 480x640 (no detections), 291.8ms
Speed: 1.3ms preprocess, 291.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIATMxw9txv5SxxKI4I1hA_180.JPG: 480x640 (no detections), 294.8ms
Speed: 1.2ms preprocess, 294.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIATMxw9txv5SxxKI4I1hA_270.JPG: 480x640 (no detections), 300.7ms
Speed: 1.3ms preprocess, 300.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIBRDf6YxkazV0vNPF4-yw_0.JPG: 480x640 (no detections), 302.2ms
Speed: 1.3ms preprocess, 302.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIBRDf6YxkazV0vNPF4-yw_90.JPG: 480x640 (no detections), 298.0ms
Speed: 1.2ms preprocess, 298.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIBRDf6YxkazV0vNPF4-yw_180.JPG: 480x640 (no detections), 298.6ms
Speed: 1.1ms preprocess, 298.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIBRDf6YxkazV0vNPF4-yw_270.JPG: 480x640 (no detections), 300.1ms
Speed: 1.2ms preprocess, 300.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIC5NkCLTXjMEpdIo6AQMQ_0.JPG: 480x640 (no detections), 299.1ms

Speed: 1.1ms preprocess, 299.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIC5NkCLTXjMEpdIo6AQMQ_90.JPG: 480x640 (no detections), 297.8ms
Speed: 1.1ms preprocess, 297.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIC5NkCLTXjMEpdIo6AQMQ_180.JPG: 480x640 (no detections), 294.8ms
Speed: 1.2ms preprocess, 294.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIC5NkCLTXjMEpdIo6AQMQ_270.JPG: 480x640 (no detections), 306.5ms
Speed: 1.1ms preprocess, 306.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIHzcox9hr3TMg2VH1k1Sw_0.JPG: 480x640 (no detections), 296.2ms
Speed: 1.1ms preprocess, 296.2ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIHzcox9hr3TMg2VH1k1Sw_90.JPG: 480x640 (no detections), 300.0ms
Speed: 1.2ms preprocess, 300.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIHzcox9hr3TMg2VH1k1Sw_180.JPG: 480x640 (no detections), 302.7ms
Speed: 1.2ms preprocess, 302.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIHzcox9hr3TMg2VH1k1Sw_270.JPG: 480x640 (no detections), 305.0ms
Speed: 1.1ms preprocess, 305.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xILGtb30I_h1r6vXwvDfGA_0.JPG: 480x640 (no detections), 296.1ms
Speed: 1.3ms preprocess, 296.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xILGtb30I_h1r6vXwvDfGA_90.JPG: 480x640 (no detections), 298.4ms
Speed: 1.2ms preprocess, 298.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xILGtb30I_h1r6vXwvDfGA_180.JPG: 480x640 (no detections), 300.6ms
Speed: 1.1ms preprocess, 300.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xILGtb30I_h1r6vXwvDfGA_270.JPG: 480x640 (no detections), 301.8ms
Speed: 1.2ms preprocess, 301.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xILWZXVB77L_H8bLRI8xgg_0.JPG: 480x640 (no detections), 303.8ms
Speed: 1.1ms preprocess, 303.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xILWZXVB77L_H8bLRI8xgg_90.JPG: 480x640 (no detections), 302.6ms
Speed: 1.1ms preprocess, 302.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xILWZXVB77L_H8bLRI8xgg_180.JPG: 480x640 (no detections), 298.6ms
Speed: 1.2ms preprocess, 298.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xILWZXVB77L_H8bLRI8xgg_270.JPG: 480x640 (no detections), 295.8ms
Speed: 1.1ms preprocess, 295.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIR3sYlQOwgqTeryPnNJNg_0.JPG: 480x640 (no detections), 306.2ms
Speed: 1.2ms preprocess, 306.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIR3sYlQOwgqTeryPnNJNg_90.JPG: 480x640 (no detections), 297.3ms
Speed: 1.2ms preprocess, 297.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIR3sYlQOwgqTeryPnNJNg_180.JPG: 480x640 (no detections), 298.2ms
Speed: 1.0ms preprocess, 298.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIR3sYlQOwgqTeryPnNJNg_270.JPG: 480x640 (no detections), 303.1ms
Speed: 1.4ms preprocess, 303.1ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xITukdoZfDXhumXZDkaRNg_0.JPG: 480x640 (no detections), 299.8ms
Speed: 1.3ms preprocess, 299.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xITukdoZfDXhumXZDkaRNg_90.JPG: 480x640 (no detections), 292.8ms
Speed: 1.2ms preprocess, 292.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xITukdoZfDXhumXZDkaRNg_180.JPG: 480x640 (no detections), 298.8ms
Speed: 1.4ms preprocess, 298.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xITukdoZfDXhumXZDkaRNg_270.JPG: 480x640 (no detections), 300.9ms
Speed: 1.6ms preprocess, 300.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIVMMweIP4rgM1MtaW8sGg_0.JPG: 480x640 (no detections), 299.6ms
Speed: 1.2ms preprocess, 299.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIVMMweIP4rgM1MtaW8sGg_90.JPG: 480x640 (no detections), 303.7ms
Speed: 1.3ms preprocess, 303.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIVMMweIP4rgM1MtaW8sGg_180.JPG: 480x640 (no detections), 292.6ms
Speed: 1.2ms preprocess, 292.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIVMMweIP4rgM1MtaW8sGg_270.JPG: 480x640 (no detections), 294.0ms
Speed: 1.2ms preprocess, 294.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIYiYjDPAc5EduR7Vtsp2g_0.JPG: 480x640 (no detections), 293.4ms
Speed: 1.4ms preprocess, 293.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIYiYjDPAc5EduR7Vtsp2g_90.JPG: 480x640 (no detections), 303.3ms
Speed: 1.5ms preprocess, 303.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIYiYjDPAc5EduR7Vtsp2g_180.JPG: 480x640 (no detections), 299.0ms
Speed: 1.3ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIYiYjDPAc5EduR7Vtsp2g_270.JPG: 480x640 (no detections), 298.7ms
Speed: 1.3ms preprocess, 298.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIZ_XYQXbLQOuxWSZqhRhw_0.JPG: 480x640 (no detections), 298.5ms
Speed: 1.2ms preprocess, 298.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIZ_XYQXbLQOuxWSZqhRhw_90.JPG: 480x640 (no detections), 300.5ms
Speed: 1.0ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIZ_XYQXbLQOuxWSZqhRhw_180.JPG: 480x640 (no detections), 300.7ms
Speed: 1.5ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIZ_XYQXbLQOuxWSZqhRhw_270.JPG: 480x640 (no detections), 297.1ms
Speed: 1.1ms preprocess, 297.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIf7BytOHJnfXx9jCpp6oA_0.JPG: 480x640 (no detections), 304.1ms
Speed: 1.3ms preprocess, 304.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIf7BytOHJnfXx9jCpp6oA_90.JPG: 480x640 (no detections), 304.3ms
Speed: 1.2ms preprocess, 304.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIf7BytOHJnfXx9jCpp6oA_180.JPG: 480x640 (no detections), 295.8ms
Speed: 1.2ms preprocess, 295.8ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIf7BytOHJnfXx9jCpp6oA_270.JPG: 480x640 (no detections), 300.4ms
Speed: 1.2ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIfQOtnyAFYskWgF32PCYg_0.JPG: 480x640 (no detections), 289.7ms
Speed: 1.0ms preprocess, 289.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIfQOtnyAFYskWgF32PCYg_90.JPG: 480x640 (no detections), 291.5ms
Speed: 1.7ms preprocess, 291.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIfQOtnyAFYskWgF32PCYg_180.JPG: 480x640 (no detections), 296.9ms
Speed: 1.1ms preprocess, 296.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIfQOtnyAFYskWgF32PCYg_270.JPG: 480x640 (no detections), 297.6ms
Speed: 1.2ms preprocess, 297.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIj5O7VTdq3Xl9F8vtshNA_0.JPG: 480x640 (no detections), 291.4ms
Speed: 1.2ms preprocess, 291.4ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIj5O7VTdq3Xl9F8vtshNA_90.JPG: 480x640 (no detections), 294.4ms
Speed: 1.3ms preprocess, 294.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIj5O7VTdq3Xl9F8vtshNA_180.JPG: 480x640 (no detections), 304.8ms
Speed: 1.3ms preprocess, 304.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIj5O7VTdq3Xl9F8vtshNA_270.JPG: 480x640 (no detections), 300.8ms
Speed: 1.2ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIlU7IEosPRjfz6_BqB_qg_0.JPG: 480x640 (no detections), 298.4ms
Speed: 1.2ms preprocess, 298.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIlU7IEosPRjfz6_BqB_qg_90.JPG: 480x640 (no detections), 313.7ms
Speed: 1.3ms preprocess, 313.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIlU7IEosPRjfz6_BqB_qg_180.JPG: 480x640 (no detections), 300.4ms
Speed: 1.8ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIlU7IEosPRjfz6_BqB_qg_270.JPG: 480x640 (no detections), 306.5ms
Speed: 1.0ms preprocess, 306.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xImJWw-vUHI_PX3B_zURDw_0.JPG: 480x640 (no detections), 290.4ms
Speed: 1.2ms preprocess, 290.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xImJWw-vUHI_PX3B_zURDw_90.JPG: 480x640 (no detections), 290.5ms
Speed: 1.3ms preprocess, 290.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xImJWw-vUHI_PX3B_zURDw_180.JPG: 480x640 (no detections), 287.8ms
Speed: 1.2ms preprocess, 287.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xImJWw-vUHI_PX3B_zURDw_270.JPG: 480x640 (no detections), 289.1ms
Speed: 1.2ms preprocess, 289.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIp8uZ2_p0Vl5v1eNafrwA_0.JPG: 480x640 (no detections), 295.5ms
Speed: 1.5ms preprocess, 295.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIp8uZ2_p0Vl5v1eNafrwA_90.JPG: 480x640 (no detections), 297.6ms
Speed: 1.1ms preprocess, 297.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIp8uZ2_p0Vl5v1eNafrwA_180.JPG: 480x640 (no detections), 296.2ms
Speed: 1.5ms preprocess, 296.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIp8uZ2_p0Vl5v1eNafrwA_270.JPG: 480x640 (no detections), 297.4ms
Speed: 1.1ms preprocess, 297.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIqPhq2mBjrnzkzqXfskgQ_0.JPG: 480x640 (no detections), 295.2ms
Speed: 1.2ms preprocess, 295.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIqPhq2mBjrnzkzqXfskgQ_90.JPG: 480x640 (no detections), 293.3ms
Speed: 1.2ms preprocess, 293.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIqPhq2mBjrnzkzqXfskgQ_180.JPG: 480x640 (no detections), 296.9ms
Speed: 1.3ms preprocess, 296.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIqPhq2mBjrnzkzqXfskgQ_270.JPG: 480x640 (no detections), 295.2ms
Speed: 1.2ms preprocess, 295.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIr7gQzSgs5bzaY3gQ3r3w_0.JPG: 480x640 (no detections), 296.2ms
Speed: 1.0ms preprocess, 296.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIr7gQzSgs5bzaY3gQ3r3w_90.JPG: 480x640 (no detections), 298.3ms
Speed: 1.0ms preprocess, 298.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIr7gQzSgs5bzaY3gQ3r3w_180.JPG: 480x640 (no detections), 296.8ms
Speed: 1.2ms preprocess, 296.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIr7gQzSgs5bzaY3gQ3r3w_270.JPG: 480x640 (no detections), 297.3ms

Speed: 1.4ms preprocess, 297.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIrDLZkKlgLJWKsTUIWYAA_0.JPG: 480x640 (no detections), 297.9ms
Speed: 1.3ms preprocess, 297.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIrDLZkKlgLJWKsTUIWYAA_90.JPG: 480x640 (no detections), 297.1ms
Speed: 1.9ms preprocess, 297.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIrDLZkKlgLJWKsTUIWYAA_180.JPG: 480x640 (no detections), 297.6ms
Speed: 1.3ms preprocess, 297.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIrDLZkKlgLJWKsTUIWYAA_270.JPG: 480x640 (no detections), 295.3ms
Speed: 1.6ms preprocess, 295.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIwN4NmbQYgPYRiNQXN3Nw_0.JPG: 480x640 (no detections), 297.0ms
Speed: 1.4ms preprocess, 297.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIwN4NmbQYgPYRiNQXN3Nw_90.JPG: 480x640 (no detections), 294.2ms
Speed: 1.3ms preprocess, 294.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIwN4NmbQYgPYRiNQXN3Nw_180.JPG: 480x640 (no detections), 294.1ms
Speed: 1.1ms preprocess, 294.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIwN4NmbQYgPYRiNQXN3Nw_270.JPG: 480x640 (no detections), 297.0ms
Speed: 1.1ms preprocess, 297.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIwvgHbxl4vlUN1YNcU2tQ_0.JPG: 480x640 (no detections), 296.9ms
Speed: 1.3ms preprocess, 296.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIwvgHbxl4vlUN1YNcU2tQ_90.JPG: 480x640 (no detections), 304.1ms
Speed: 1.3ms preprocess, 304.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIwvgHbxl4vlUN1YNcU2tQ_180.JPG: 480x640 (no detections), 298.0ms
Speed: 1.1ms preprocess, 298.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIwvgHbxl4vlUN1YNcU2tQ_270.JPG: 480x640 (no detections), 303.5ms
Speed: 1.0ms preprocess, 303.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIzodHkj3T0ahwS5iGkPoQ_0.JPG: 480x640 (no detections), 298.2ms
Speed: 1.3ms preprocess, 298.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIzodHkj3T0ahwS5iGkPoQ_90.JPG: 480x640 (no detections), 296.7ms
Speed: 1.1ms preprocess, 296.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIzodHkj3T0ahwS5iGkPoQ_180.JPG: 480x640 (no detections), 316.0ms
Speed: 1.5ms preprocess, 316.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xIzodHkj3T0ahwS5iGkPoQ_270.JPG: 480x640 (no detections), 295.7ms
Speed: 1.2ms preprocess, 295.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJ1rg-msfnhptCw6ednpEg_0.JPG: 480x640 (no detections), 307.2ms
Speed: 1.2ms preprocess, 307.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJ1rg-msfnhptCw6ednpEg_90.JPG: 480x640 (no detections), 296.6ms
Speed: 1.3ms preprocess, 296.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJ1rg-msfnhptCw6ednpEg_180.JPG: 480x640 (no detections), 307.9ms
Speed: 1.3ms preprocess, 307.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJ1rg-msfnhptCw6ednpEg_270.JPG: 480x640 (no detections), 298.7ms
Speed: 1.2ms preprocess, 298.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJ3pT7jrWucB_Gu2aWUjwQ_0.JPG: 480x640 (no detections), 301.2ms
Speed: 1.4ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJ3pT7jrWucB_Gu2aWUjwQ_90.JPG: 480x640 (no detections), 302.7ms
Speed: 1.5ms preprocess, 302.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJ3pT7jrWucB_Gu2aWUjwQ_180.JPG: 480x640 (no detections), 301.9ms
Speed: 1.2ms preprocess, 301.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJ3pT7jrWucB_Gu2aWUjwQ_270.JPG: 480x640 (no detections), 294.7ms
Speed: 1.6ms preprocess, 294.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJ52H98h65uUu5tze1FHzA_0.JPG: 480x640 (no detections), 291.2ms
Speed: 1.2ms preprocess, 291.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJ52H98h65uUu5tze1FHzA_90.JPG: 480x640 (no detections), 298.1ms
Speed: 1.1ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJ52H98h65uUu5tze1FHzA_180.JPG: 480x640 (no detections), 298.5ms
Speed: 1.0ms preprocess, 298.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJ52H98h65uUu5tze1FHzA_270.JPG: 480x640 (no detections), 299.5ms
Speed: 1.2ms preprocess, 299.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJ5JgewxTQKUohB2k3fQlw_0.JPG: 480x640 (no detections), 303.5ms
Speed: 1.2ms preprocess, 303.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJ5JgewxTQKUohB2k3fQlw_90.JPG: 480x640 (no detections), 299.2ms
Speed: 1.1ms preprocess, 299.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJ5JgewxTQKUohB2k3fQlw_180.JPG: 480x640 (no detections), 293.4ms
Speed: 1.2ms preprocess, 293.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJ5JgewxTQKUohB2k3fQlw_270.JPG: 480x640 (no detections), 298.0ms
Speed: 1.2ms preprocess, 298.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJ5L28yCNWalvK4Pz2xNDg_0.JPG: 480x640 (no detections), 296.6ms
Speed: 1.1ms preprocess, 296.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJ5L28yCNWalvK4Pz2xNDg_90.JPG: 480x640 (no detections), 293.9ms
Speed: 1.0ms preprocess, 293.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJ5L28yCNWalvK4Pz2xNDg_180.JPG: 480x640 (no detections), 296.8ms
Speed: 1.1ms preprocess, 296.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJ5L28yCNWalvK4Pz2xNDg_270.JPG: 480x640 (no detections), 299.9ms
Speed: 1.2ms preprocess, 299.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJ8KZH7TPtmM9M3hC7MwgA_0.JPG: 480x640 (no detections), 300.8ms
Speed: 1.2ms preprocess, 300.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJ8KZH7TPtmM9M3hC7MwgA_90.JPG: 480x640 (no detections), 309.9ms
Speed: 1.0ms preprocess, 309.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJ8KZH7TPtmM9M3hC7MwgA_180.JPG: 480x640 (no detections), 305.9ms
Speed: 1.4ms preprocess, 305.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJ8KZH7TPtmM9M3hC7MwgA_270.JPG: 480x640 (no detections), 304.4ms
Speed: 1.6ms preprocess, 304.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJ9JG_KA3kExPX7FEliZ7g_0.JPG: 480x640 (no detections), 314.1ms
Speed: 1.2ms preprocess, 314.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJ9JG_KA3kExPX7FEliZ7g_90.JPG: 480x640 (no detections), 340.3ms
Speed: 1.2ms preprocess, 340.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJ9JG_KA3kExPX7FEliZ7g_180.JPG: 480x640 (no detections), 305.3ms
Speed: 1.3ms preprocess, 305.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJ9JG_KA3kExPX7FEliZ7g_270.JPG: 480x640 (no detections), 290.9ms
Speed: 1.3ms preprocess, 290.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJ9L8E6za4l_1oCISn-3lQ_0.JPG: 480x640 (no detections), 294.3ms
Speed: 1.2ms preprocess, 294.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJ9L8E6za4l_1oCISn-3lQ_90.JPG: 480x640 (no detections), 298.6ms
Speed: 1.1ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJ9L8E6za4l_1oCISn-3lQ_180.JPG: 480x640 (no detections), 292.0ms
Speed: 1.2ms preprocess, 292.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJ9L8E6za4l_1oCISn-3lQ_270.JPG: 480x640 (no detections), 293.0ms
Speed: 1.2ms preprocess, 293.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJ9t57HOrDex9p65VwfIog_0.JPG: 480x640 (no detections), 293.6ms
Speed: 1.4ms preprocess, 293.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJ9t57HOrDex9p65VwfIog_90.JPG: 480x640 (no detections), 306.2ms
Speed: 1.4ms preprocess, 306.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJ9t57HOrDex9p65VwfIog_180.JPG: 480x640 (no detections), 317.5ms
Speed: 1.5ms preprocess, 317.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJ9t57HOrDex9p65VwfIog_270.JPG: 480x640 (no detections), 305.4ms
Speed: 1.2ms preprocess, 305.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJDjKCtYuRoLTtqm0Gc90g_0.JPG: 480x640 1 Waste, 295.1ms
Speed: 1.2ms preprocess, 295.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJDjKCtYuRoLTtqm0Gc90g_90.JPG: 480x640 (no detections), 302.7ms
Speed: 1.1ms preprocess, 302.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJDjKCtYuRoLTtqm0Gc90g_180.JPG: 480x640 (no detections), 305.5ms
Speed: 1.3ms preprocess, 305.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJDjKCtYuRoLTtqm0Gc90g_270.JPG: 480x640 (no detections), 295.3ms
Speed: 1.2ms preprocess, 295.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJF_IVNova0K2EmE5yiVew_0.JPG: 480x640 (no detections), 295.2ms
Speed: 1.8ms preprocess, 295.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJF_IVNova0K2EmE5yiVew_90.JPG: 480x640 (no detections), 298.9ms
Speed: 1.2ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJF_IVNova0K2EmE5yiVew_180.JPG: 480x640 (no detections), 295.2ms
Speed: 1.1ms preprocess, 295.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJF_IVNova0K2EmE5yiVew_270.JPG: 480x640 (no detections), 294.7ms
Speed: 1.2ms preprocess, 294.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJFtS2Cx6MO8h1RMLfX0WQ_0.JPG: 480x640 (no detections), 301.9ms
Speed: 1.4ms preprocess, 301.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJFtS2Cx6MO8h1RMLfX0WQ_90.JPG: 480x640 (no detections), 299.9ms
Speed: 1.2ms preprocess, 299.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJFtS2Cx6MO8h1RMLfX0WQ_180.JPG: 480x640 (no detections), 302.1ms
Speed: 1.2ms preprocess, 302.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJFtS2Cx6MO8h1RMLfX0WQ_270.JPG: 480x640 (no detections), 306.7ms
Speed: 1.0ms preprocess, 306.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJGAsqATPkxnnv6Bx58ptA_0.JPG: 480x640 (no detections), 296.7ms
Speed: 1.1ms preprocess, 296.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJGAsqATPkxnnv6Bx58ptA_90.JPG: 480x640 (no detections), 302.5ms
Speed: 1.2ms preprocess, 302.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJGAsqATPkxnnv6Bx58ptA_180.JPG: 480x640 (no detections), 301.7ms

Speed: 1.2ms preprocess, 301.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJGAsqATPkxnnv6Bx58ptA_270.JPG: 480x640 (no detections), 303.5ms
Speed: 1.1ms preprocess, 303.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJJMiVEm694-oQhHponq2A_0.JPG: 480x640 (no detections), 298.1ms
Speed: 1.1ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJJMiVEm694-oQhHponq2A_90.JPG: 480x640 (no detections), 300.0ms
Speed: 1.1ms preprocess, 300.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJJMiVEm694-oQhHponq2A_180.JPG: 480x640 (no detections), 299.3ms
Speed: 1.3ms preprocess, 299.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJJMiVEm694-oQhHponq2A_270.JPG: 480x640 (no detections), 301.2ms
Speed: 1.2ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJQXoQ8C8WSyRGA5lwjw5Q_0.JPG: 480x640 (no detections), 297.8ms
Speed: 1.3ms preprocess, 297.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJQXoQ8C8WSyRGA5lwjw5Q_90.JPG: 480x640 (no detections), 302.2ms
Speed: 1.3ms preprocess, 302.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJQXoQ8C8WSyRGA5lwjw5Q_180.JPG: 480x640 (no detections), 301.4ms
Speed: 1.2ms preprocess, 301.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJQXoQ8C8WSyRGA5lwjw5Q_270.JPG: 480x640 (no detections), 298.4ms
Speed: 1.2ms preprocess, 298.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJUKLgdK8D4qpgq4FWxw4Q_0.JPG: 480x640 (no detections), 298.7ms
Speed: 1.2ms preprocess, 298.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJUKLgdK8D4qpgq4FWxw4Q_90.JPG: 480x640 (no detections), 300.8ms
Speed: 1.2ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJUKLgdK8D4qpgq4FWxw4Q_180.JPG: 480x640 (no detections), 298.6ms
Speed: 1.2ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJUKLgdK8D4qpgq4FWxw4Q_270.JPG: 480x640 (no detections), 298.9ms
Speed: 1.1ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJhq7eLybwZCj_X5H3Btfg_0.JPG: 480x640 (no detections), 304.8ms
Speed: 1.6ms preprocess, 304.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJhq7eLybwZCj_X5H3Btfg_90.JPG: 480x640 (no detections), 299.3ms
Speed: 1.7ms preprocess, 299.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJhq7eLybwZCj_X5H3Btfg_180.JPG: 480x640 (no detections), 295.3ms
Speed: 1.4ms preprocess, 295.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJhq7eLybwZCj_X5H3Btfg_270.JPG: 480x640 (no detections), 298.2ms
Speed: 1.1ms preprocess, 298.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJjMU7lxzeCVaYdwLB8w7Q_0.JPG: 480x640 (no detections), 295.8ms
Speed: 1.1ms preprocess, 295.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJjMU7lxzeCVaYdwLB8w7Q_90.JPG: 480x640 (no detections), 296.8ms
Speed: 1.1ms preprocess, 296.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJjMU7lxzeCVaYdwLB8w7Q_180.JPG: 480x640 (no detections), 298.1ms
Speed: 1.1ms preprocess, 298.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJjMU7lxzeCVaYdwLB8w7Q_270.JPG: 480x640 (no detections), 301.2ms
Speed: 1.3ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJoCh2-cwCcIlwW5aSyGJA_0.JPG: 480x640 1 Waste, 300.2ms
Speed: 1.1ms preprocess, 300.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJoCh2-cwCcIlwW5aSyGJA_90.JPG: 480x640 1 Waste, 298.2ms
Speed: 1.1ms preprocess, 298.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJoCh2-cwCcIlwW5aSyGJA_180.JPG: 480x640 (no detections), 297.5ms
Speed: 1.2ms preprocess, 297.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJoCh2-cwCcIlwW5aSyGJA_270.JPG: 480x640 (no detections), 296.6ms
Speed: 1.1ms preprocess, 296.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJpoQH9DhK7cBvg8RrETFA_0.JPG: 480x640 (no detections), 297.2ms
Speed: 1.3ms preprocess, 297.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJpoQH9DhK7cBvg8RrETFA_90.JPG: 480x640 (no detections), 297.4ms
Speed: 1.1ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJpoQH9DhK7cBvg8RrETFA_180.JPG: 480x640 (no detections), 297.7ms
Speed: 1.2ms preprocess, 297.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJpoQH9DhK7cBvg8RrETFA_270.JPG: 480x640 (no detections), 305.8ms
Speed: 1.2ms preprocess, 305.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJq-4trfPpgAm_EduuQ_Ig_0.JPG: 480x640 (no detections), 305.1ms
Speed: 1.1ms preprocess, 305.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJq-4trfPpgAm_EduuQ_Ig_90.JPG: 480x640 (no detections), 298.8ms
Speed: 1.4ms preprocess, 298.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJq-4trfPpgAm_EduuQ_Ig_180.JPG: 480x640 (no detections), 294.0ms
Speed: 1.1ms preprocess, 294.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJq-4trfPpgAm_EduuQ_Ig_270.JPG: 480x640 (no detections), 293.3ms
Speed: 1.2ms preprocess, 293.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJrbBCYieT0dZiCni95t6A_0.JPG: 480x640 (no detections), 302.6ms
Speed: 1.3ms preprocess, 302.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJrbBCYieT0dZiCni95t6A_90.JPG: 480x640 (no detections), 299.3ms
Speed: 1.2ms preprocess, 299.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJrbBCYieT0dZiCni95t6A_180.JPG: 480x640 (no detections), 296.1ms
Speed: 1.0ms preprocess, 296.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJrbBCYieT0dZiCni95t6A_270.JPG: 480x640 (no detections), 299.8ms
Speed: 1.2ms preprocess, 299.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJtgcTmcWTXJTqCULIlI7A_0.JPG: 480x640 (no detections), 297.4ms
Speed: 1.7ms preprocess, 297.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJtgcTmcWTXJTqCULIlI7A_90.JPG: 480x640 (no detections), 297.6ms
Speed: 1.3ms preprocess, 297.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJtgcTmcWTXJTqCULIlI7A_180.JPG: 480x640 (no detections), 300.4ms
Speed: 1.2ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJtgcTmcWTXJTqCULIlI7A_270.JPG: 480x640 (no detections), 300.9ms
Speed: 1.4ms preprocess, 300.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJy4NwKaGqzdcbNfBlGJ0g_0.JPG: 480x640 (no detections), 299.9ms
Speed: 1.1ms preprocess, 299.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJy4NwKaGqzdcbNfBlGJ0g_90.JPG: 480x640 (no detections), 301.5ms
Speed: 1.3ms preprocess, 301.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJy4NwKaGqzdcbNfBlGJ0g_180.JPG: 480x640 (no detections), 300.0ms
Speed: 1.2ms preprocess, 300.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJy4NwKaGqzdcbNfBlGJ0g_270.JPG: 480x640 (no detections), 300.4ms
Speed: 1.2ms preprocess, 300.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJyMlncZ9v8tlwjENPiCYA_0.JPG: 480x640 (no detections), 298.8ms
Speed: 1.3ms preprocess, 298.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJyMlncZ9v8tlwjENPiCYA_90.JPG: 480x640 (no detections), 298.7ms
Speed: 1.1ms preprocess, 298.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJyMlncZ9v8tlwjENPiCYA_180.JPG: 480x640 (no detections), 295.3ms
Speed: 1.2ms preprocess, 295.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJyMlncZ9v8tlwjENPiCYA_270.JPG: 480x640 (no detections), 299.3ms
Speed: 1.1ms preprocess, 299.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJydTyt9WEulFkn_3as21A_0.JPG: 480x640 (no detections), 301.2ms
Speed: 1.3ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJydTyt9WEulFkn_3as21A_90.JPG: 480x640 (no detections), 299.6ms
Speed: 1.1ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJydTyt9WEulFkn_3as21A_180.JPG: 480x640 (no detections), 296.1ms
Speed: 1.2ms preprocess, 296.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xJydTyt9WEulFkn_3as21A_270.JPG: 480x640 (no detections), 296.8ms
Speed: 1.2ms preprocess, 296.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xK-iKbx0QMGM_x2CHcm5rA_0.JPG: 480x640 (no detections), 304.0ms
Speed: 1.3ms preprocess, 304.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xK-iKbx0QMGM_x2CHcm5rA_90.JPG: 480x640 (no detections), 301.1ms
Speed: 1.1ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xK-iKbx0QMGM_x2CHcm5rA_180.JPG: 480x640 (no detections), 295.2ms
Speed: 1.4ms preprocess, 295.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xK-iKbx0QMGM_x2CHcm5rA_270.JPG: 480x640 (no detections), 296.3ms
Speed: 1.2ms preprocess, 296.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xK0vthRDyawN4vd4iIsAng_0.JPG: 480x640 (no detections), 298.1ms
Speed: 1.2ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xK0vthRDyawN4vd4iIsAng_90.JPG: 480x640 (no detections), 301.4ms
Speed: 1.1ms preprocess, 301.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xK0vthRDyawN4vd4iIsAng_180.JPG: 480x640 (no detections), 303.7ms
Speed: 1.2ms preprocess, 303.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xK0vthRDyawN4vd4iIsAng_270.JPG: 480x640 (no detections), 299.8ms
Speed: 1.4ms preprocess, 299.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xK31rBbggNw2ET_Qzo08MQ_0.JPG: 480x640 (no detections), 299.2ms
Speed: 1.2ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xK31rBbggNw2ET_Qzo08MQ_90.JPG: 480x640 (no detections), 297.4ms
Speed: 1.2ms preprocess, 297.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xK31rBbggNw2ET_Qzo08MQ_180.JPG: 480x640 (no detections), 299.5ms
Speed: 1.2ms preprocess, 299.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xK31rBbggNw2ET_Qzo08MQ_270.JPG: 480x640 (no detections), 303.4ms
Speed: 1.1ms preprocess, 303.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKBjqbS4TaiZYdzgmvH8NA_0.JPG: 480x640 (no detections), 299.0ms
Speed: 1.1ms preprocess, 299.0ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKBjqbS4TaiZYdzgmvH8NA_90.JPG: 480x640 (no detections), 304.2ms

Speed: 1.5ms preprocess, 304.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKBjqbS4TaiZYdzgmvH8NA_180.JPG: 480x640 (no detections), 292.6ms
Speed: 1.3ms preprocess, 292.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKBjqbS4TaiZYdzgmvH8NA_270.JPG: 480x640 (no detections), 299.4ms
Speed: 1.1ms preprocess, 299.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKEqANbdf429Gc0Y7bSBXQ_0.JPG: 480x640 (no detections), 381.1ms
Speed: 1.2ms preprocess, 381.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKEqANbdf429Gc0Y7bSBXQ_90.JPG: 480x640 (no detections), 298.4ms
Speed: 1.1ms preprocess, 298.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKEqANbdf429Gc0Y7bSBXQ_180.JPG: 480x640 (no detections), 299.0ms
Speed: 1.0ms preprocess, 299.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKEqANbdf429Gc0Y7bSBXQ_270.JPG: 480x640 (no detections), 297.9ms
Speed: 1.0ms preprocess, 297.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKFWzjjRIoNKCjcegbCZ7w_0.JPG: 480x640 (no detections), 297.5ms
Speed: 1.2ms preprocess, 297.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKFWzjjRIoNKCjcegbCZ7w_90.JPG: 480x640 (no detections), 298.5ms
Speed: 1.6ms preprocess, 298.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKFWzjjRIoNKCjcegbCZ7w_180.JPG: 480x640 (no detections), 298.3ms
Speed: 1.1ms preprocess, 298.3ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKFWzjjRIoNKCjcegbCZ7w_270.JPG: 480x640 (no detections), 299.6ms
Speed: 1.3ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKPkVLy7nzqDUOTlN6fPkg_0.JPG: 480x640 (no detections), 299.4ms
Speed: 1.2ms preprocess, 299.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKPkVLy7nzqDUOTlN6fPkg_90.JPG: 480x640 (no detections), 299.1ms
Speed: 1.0ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKPkVLy7nzqDUOTlN6fPkg_180.JPG: 480x640 (no detections), 303.0ms
Speed: 1.2ms preprocess, 303.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKPkVLy7nzqDUOTlN6fPkg_270.JPG: 480x640 (no detections), 297.0ms
Speed: 1.4ms preprocess, 297.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKRTJ6gKBr2LLko2x2PIiw_0.JPG: 480x640 (no detections), 295.9ms
Speed: 1.1ms preprocess, 295.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKRTJ6gKBr2LLko2x2PIiw_90.JPG: 480x640 (no detections), 299.3ms
Speed: 1.4ms preprocess, 299.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKRTJ6gKBr2LLko2x2PIiw_180.JPG: 480x640 (no detections), 302.1ms
Speed: 1.1ms preprocess, 302.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKRTJ6gKBr2LLko2x2PIiw_270.JPG: 480x640 (no detections), 292.7ms
Speed: 1.0ms preprocess, 292.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKSyUdKXdvG97WvlsRTGuw_0.JPG: 480x640 (no detections), 295.1ms
Speed: 1.1ms preprocess, 295.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKSyUdKXdvG97WvlsRTGuw_90.JPG: 480x640 (no detections), 300.7ms
Speed: 1.3ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKSyUdKXdvG97WvlsRTGuw_180.JPG: 480x640 (no detections), 299.7ms
Speed: 1.2ms preprocess, 299.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKSyUdKXdvG97WvlsRTGuw_270.JPG: 480x640 (no detections), 298.1ms
Speed: 1.3ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKY2MeFOamJCjhMGctdnhg_0.JPG: 480x640 (no detections), 297.1ms
Speed: 1.2ms preprocess, 297.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKY2MeFOamJCjhMGctdnhg_90.JPG: 480x640 (no detections), 300.4ms
Speed: 1.4ms preprocess, 300.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKY2MeFOamJCjhMGctdnhg_180.JPG: 480x640 1 Waste, 305.0ms
Speed: 1.2ms preprocess, 305.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKY2MeFOamJCjhMGctdnhg_270.JPG: 480x640 (no detections), 301.8ms
Speed: 1.2ms preprocess, 301.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKYopPM_yE5pszai9ZdHsA_0.JPG: 480x640 (no detections), 297.1ms
Speed: 1.1ms preprocess, 297.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKYopPM_yE5pszai9ZdHsA_90.JPG: 480x640 (no detections), 299.1ms
Speed: 1.0ms preprocess, 299.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKYopPM_yE5pszai9ZdHsA_180.JPG: 480x640 (no detections), 299.9ms
Speed: 1.5ms preprocess, 299.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKYopPM_yE5pszai9ZdHsA_270.JPG: 480x640 (no detections), 300.3ms
Speed: 1.4ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKbNc_-sYGj3Q2eYJqktAA_0.JPG: 480x640 (no detections), 300.6ms
Speed: 1.2ms preprocess, 300.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKbNc_-sYGj3Q2eYJqktAA_90.JPG: 480x640 (no detections), 298.4ms
Speed: 1.2ms preprocess, 298.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKbNc_-sYGj3Q2eYJqktAA_180.JPG: 480x640 1 Waste, 296.1ms
Speed: 1.2ms preprocess, 296.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKbNc_-sYGj3Q2eYJqktAA_270.JPG: 480x640 (no detections), 298.5ms
Speed: 1.2ms preprocess, 298.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKeOJOBZg8rhMYvpmXZ4DA_0.JPG: 480x640 (no detections), 300.7ms
Speed: 1.1ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKeOJOBZg8rhMYvpmXZ4DA_90.JPG: 480x640 (no detections), 301.0ms
Speed: 1.4ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKeOJOBZg8rhMYvpmXZ4DA_180.JPG: 480x640 (no detections), 307.3ms
Speed: 1.4ms preprocess, 307.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKeOJOBZg8rhMYvpmXZ4DA_270.JPG: 480x640 (no detections), 299.6ms
Speed: 1.2ms preprocess, 299.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKjFHuRK9kR-pkhbAhCIeQ_0.JPG: 480x640 (no detections), 305.0ms
Speed: 1.2ms preprocess, 305.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKjFHuRK9kR-pkhbAhCIeQ_90.JPG: 480x640 (no detections), 298.1ms
Speed: 1.4ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKjFHuRK9kR-pkhbAhCIeQ_180.JPG: 480x640 (no detections), 300.3ms
Speed: 1.3ms preprocess, 300.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKjFHuRK9kR-pkhbAhCIeQ_270.JPG: 480x640 (no detections), 296.7ms
Speed: 1.9ms preprocess, 296.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKkU-RmPblsU7JXQPTpxjw_0.JPG: 480x640 (no detections), 295.6ms
Speed: 1.2ms preprocess, 295.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKkU-RmPblsU7JXQPTpxjw_90.JPG: 480x640 (no detections), 299.9ms
Speed: 1.4ms preprocess, 299.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKkU-RmPblsU7JXQPTpxjw_180.JPG: 480x640 (no detections), 306.6ms
Speed: 1.5ms preprocess, 306.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKkU-RmPblsU7JXQPTpxjw_270.JPG: 480x640 (no detections), 298.6ms
Speed: 1.3ms preprocess, 298.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKn-vxJMx8ACKXW9TmtV4Q_0.JPG: 480x640 (no detections), 296.9ms
Speed: 1.3ms preprocess, 296.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKn-vxJMx8ACKXW9TmtV4Q_90.JPG: 480x640 (no detections), 298.0ms
Speed: 1.4ms preprocess, 298.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKn-vxJMx8ACKXW9TmtV4Q_180.JPG: 480x640 (no detections), 298.8ms
Speed: 1.3ms preprocess, 298.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKn-vxJMx8ACKXW9TmtV4Q_270.JPG: 480x640 (no detections), 303.5ms
Speed: 1.3ms preprocess, 303.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKr4S4kMpGSFqALbyDhJFw_0.JPG: 480x640 (no detections), 292.5ms
Speed: 1.1ms preprocess, 292.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKr4S4kMpGSFqALbyDhJFw_90.JPG: 480x640 (no detections), 299.1ms
Speed: 1.1ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKr4S4kMpGSFqALbyDhJFw_180.JPG: 480x640 (no detections), 300.8ms
Speed: 1.8ms preprocess, 300.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKr4S4kMpGSFqALbyDhJFw_270.JPG: 480x640 (no detections), 299.9ms
Speed: 1.0ms preprocess, 299.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKuq5ROGV5xEui3JCwQ7Dw_0.JPG: 480x640 (no detections), 298.6ms
Speed: 1.2ms preprocess, 298.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKuq5ROGV5xEui3JCwQ7Dw_90.JPG: 480x640 (no detections), 299.2ms
Speed: 1.3ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKuq5ROGV5xEui3JCwQ7Dw_180.JPG: 480x640 (no detections), 295.8ms
Speed: 1.8ms preprocess, 295.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKuq5ROGV5xEui3JCwQ7Dw_270.JPG: 480x640 (no detections), 299.6ms
Speed: 1.2ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKvVvt5CAk38p4Qp1f-W-g_0.JPG: 480x640 (no detections), 297.0ms
Speed: 1.2ms preprocess, 297.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKvVvt5CAk38p4Qp1f-W-g_90.JPG: 480x640 (no detections), 300.7ms
Speed: 2.0ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKvVvt5CAk38p4Qp1f-W-g_180.JPG: 480x640 (no detections), 299.9ms
Speed: 1.2ms preprocess, 299.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKvVvt5CAk38p4Qp1f-W-g_270.JPG: 480x640 (no detections), 296.9ms
Speed: 1.1ms preprocess, 296.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKwrvx63vafVenNNNTJjXg_0.JPG: 480x640 (no detections), 297.6ms
Speed: 1.1ms preprocess, 297.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKwrvx63vafVenNNNTJjXg_90.JPG: 480x640 (no detections), 309.1ms
Speed: 1.5ms preprocess, 309.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKwrvx63vafVenNNNTJjXg_180.JPG: 480x640 (no detections), 300.6ms
Speed: 1.3ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKwrvx63vafVenNNNTJjXg_270.JPG: 480x640 1 Waste, 298.8ms
Speed: 1.2ms preprocess, 298.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKxjg3hpMeiJYp-TCwwqEQ_0.JPG: 480x640 (no detections), 302.3ms

Speed: 1.1ms preprocess, 302.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKxjg3hpMeiJYp-TCwwqEQ_90.JPG: 480x640 (no detections), 300.3ms
Speed: 1.1ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKxjg3hpMeiJYp-TCwwqEQ_180.JPG: 480x640 (no detections), 299.0ms
Speed: 2.1ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKxjg3hpMeiJYp-TCwwqEQ_270.JPG: 480x640 (no detections), 297.8ms
Speed: 1.8ms preprocess, 297.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKyELicXqUVb5IuKzVj-1Q_0.JPG: 480x640 (no detections), 298.6ms
Speed: 1.8ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKyELicXqUVb5IuKzVj-1Q_90.JPG: 480x640 (no detections), 298.6ms
Speed: 1.2ms preprocess, 298.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKyELicXqUVb5IuKzVj-1Q_180.JPG: 480x640 (no detections), 300.5ms
Speed: 1.2ms preprocess, 300.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xKyELicXqUVb5IuKzVj-1Q_270.JPG: 480x640 (no detections), 300.7ms
Speed: 1.2ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xL-QOhqbIvE67biEdZn0ig_0.JPG: 480x640 (no detections), 303.2ms
Speed: 1.1ms preprocess, 303.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xL-QOhqbIvE67biEdZn0ig_90.JPG: 480x640 (no detections), 303.8ms
Speed: 1.6ms preprocess, 303.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xL-QOhqbIvE67biEdZn0ig_180.JPG: 480x640 (no detections), 300.5ms
Speed: 1.4ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xL-QOhqbIvE67biEdZn0ig_270.JPG: 480x640 (no detections), 299.0ms
Speed: 1.7ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xL10EHznxg9PBe1DHERJzA_0.JPG: 480x640 (no detections), 306.1ms
Speed: 1.3ms preprocess, 306.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xL10EHznxg9PBe1DHERJzA_90.JPG: 480x640 (no detections), 299.2ms
Speed: 1.5ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xL10EHznxg9PBe1DHERJzA_180.JPG: 480x640 (no detections), 298.2ms
Speed: 1.3ms preprocess, 298.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xL10EHznxg9PBe1DHERJzA_270.JPG: 480x640 1 Waste, 296.6ms
Speed: 1.4ms preprocess, 296.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xL78U3LO60h86i5Kp8g9Aw_0.JPG: 480x640 1 Waste, 300.2ms
Speed: 1.3ms preprocess, 300.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xL78U3LO60h86i5Kp8g9Aw_90.JPG: 480x640 (no detections), 314.3ms
Speed: 1.0ms preprocess, 314.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xL78U3LO60h86i5Kp8g9Aw_180.JPG: 480x640 (no detections), 305.8ms
Speed: 1.4ms preprocess, 305.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xL78U3LO60h86i5Kp8g9Aw_270.JPG: 480x640 (no detections), 300.3ms
Speed: 1.1ms preprocess, 300.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xL8NrjCT6g05-iVAQEEKqA_0.JPG: 480x640 1 Waste, 297.0ms
Speed: 1.6ms preprocess, 297.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xL8NrjCT6g05-iVAQEEKqA_90.JPG: 480x640 (no detections), 305.6ms
Speed: 1.3ms preprocess, 305.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xL8NrjCT6g05-iVAQEEKqA_180.JPG: 480x640 (no detections), 300.4ms
Speed: 1.3ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xL8NrjCT6g05-iVAQEEKqA_270.JPG: 480x640 (no detections), 298.7ms
Speed: 1.1ms preprocess, 298.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xL9hWoT6GjxOMK39T_6xew_0.JPG: 480x640 (no detections), 302.6ms
Speed: 1.1ms preprocess, 302.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xL9hWoT6GjxOMK39T_6xew_90.JPG: 480x640 (no detections), 300.7ms
Speed: 1.2ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xL9hWoT6GjxOMK39T_6xew_180.JPG: 480x640 (no detections), 298.7ms
Speed: 1.0ms preprocess, 298.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xL9hWoT6GjxOMK39T_6xew_270.JPG: 480x640 (no detections), 301.7ms
Speed: 1.3ms preprocess, 301.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLAbPBeSjeXOJAqWHIKqUw_0.JPG: 480x640 (no detections), 297.0ms
Speed: 1.4ms preprocess, 297.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLAbPBeSjeXOJAqWHIKqUw_90.JPG: 480x640 (no detections), 302.5ms
Speed: 1.0ms preprocess, 302.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLAbPBeSjeXOJAqWHIKqUw_180.JPG: 480x640 (no detections), 298.9ms
Speed: 1.3ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLAbPBeSjeXOJAqWHIKqUw_270.JPG: 480x640 (no detections), 297.5ms
Speed: 1.1ms preprocess, 297.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLD_Um6mhcZ9TrKFVIQzWQ_0.JPG: 480x640 (no detections), 297.0ms
Speed: 1.1ms preprocess, 297.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLD_Um6mhcZ9TrKFVIQzWQ_90.JPG: 480x640 (no detections), 298.7ms
Speed: 1.2ms preprocess, 298.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLD_Um6mhcZ9TrKFVIQzWQ_180.JPG: 480x640 (no detections), 303.1ms
Speed: 1.1ms preprocess, 303.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLD_Um6mhcZ9TrKFVIQzWQ_270.JPG: 480x640 (no detections), 297.6ms
Speed: 1.2ms preprocess, 297.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLE994PQNkg6xdDr7OiA-Q_0.JPG: 480x640 (no detections), 303.3ms
Speed: 1.2ms preprocess, 303.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLE994PQNkg6xdDr7OiA-Q_90.JPG: 480x640 (no detections), 298.4ms
Speed: 1.3ms preprocess, 298.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLE994PQNkg6xdDr7OiA-Q_180.JPG: 480x640 (no detections), 302.9ms
Speed: 1.2ms preprocess, 302.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLE994PQNkg6xdDr7OiA-Q_270.JPG: 480x640 (no detections), 301.9ms
Speed: 1.0ms preprocess, 301.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLFfHprr-4zLwHLab1eXKw_0.JPG: 480x640 (no detections), 293.6ms
Speed: 1.1ms preprocess, 293.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLFfHprr-4zLwHLab1eXKw_90.JPG: 480x640 (no detections), 295.3ms
Speed: 1.2ms preprocess, 295.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLFfHprr-4zLwHLab1eXKw_180.JPG: 480x640 (no detections), 298.9ms
Speed: 1.3ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLFfHprr-4zLwHLab1eXKw_270.JPG: 480x640 (no detections), 300.2ms
Speed: 1.5ms preprocess, 300.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLHgj-gr85KQHhrYvjcYdA_0.JPG: 480x640 (no detections), 300.8ms
Speed: 1.3ms preprocess, 300.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLHgj-gr85KQHhrYvjcYdA_90.JPG: 480x640 (no detections), 296.7ms
Speed: 1.1ms preprocess, 296.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLHgj-gr85KQHhrYvjcYdA_180.JPG: 480x640 (no detections), 304.4ms
Speed: 1.1ms preprocess, 304.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLHgj-gr85KQHhrYvjcYdA_270.JPG: 480x640 1 Waste, 299.7ms
Speed: 1.2ms preprocess, 299.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLIRsRKLsL7TNntcrjJxeA_0.JPG: 480x640 (no detections), 300.0ms
Speed: 1.2ms preprocess, 300.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLIRsRKLsL7TNntcrjJxeA_90.JPG: 480x640 (no detections), 298.7ms
Speed: 1.1ms preprocess, 298.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLIRsRKLsL7TNntcrjJxeA_180.JPG: 480x640 (no detections), 303.8ms
Speed: 1.2ms preprocess, 303.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLIRsRKLsL7TNntcrjJxeA_270.JPG: 480x640 (no detections), 302.6ms
Speed: 1.2ms preprocess, 302.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLJAz4Vwe6WKFXVzvIlZIQ_0.JPG: 480x640 (no detections), 298.1ms
Speed: 1.3ms preprocess, 298.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLJAz4Vwe6WKFXVzvIlZIQ_90.JPG: 480x640 (no detections), 295.4ms
Speed: 1.3ms preprocess, 295.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLJAz4Vwe6WKFXVzvIlZIQ_180.JPG: 480x640 (no detections), 299.4ms
Speed: 1.4ms preprocess, 299.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLJAz4Vwe6WKFXVzvIlZIQ_270.JPG: 480x640 (no detections), 304.1ms
Speed: 1.2ms preprocess, 304.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLJbpCgajQmE-qKxjZbOLw_0.JPG: 480x640 (no detections), 300.0ms
Speed: 1.2ms preprocess, 300.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLJbpCgajQmE-qKxjZbOLw_90.JPG: 480x640 (no detections), 303.3ms
Speed: 1.2ms preprocess, 303.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLJbpCgajQmE-qKxjZbOLw_180.JPG: 480x640 (no detections), 295.4ms
Speed: 1.1ms preprocess, 295.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLJbpCgajQmE-qKxjZbOLw_270.JPG: 480x640 (no detections), 302.6ms
Speed: 1.3ms preprocess, 302.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLJhg1LDxAJrTA8OfmlQoA_0.JPG: 480x640 (no detections), 302.7ms
Speed: 1.1ms preprocess, 302.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLJhg1LDxAJrTA8OfmlQoA_90.JPG: 480x640 (no detections), 300.1ms
Speed: 1.2ms preprocess, 300.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLJhg1LDxAJrTA8OfmlQoA_180.JPG: 480x640 (no detections), 298.6ms
Speed: 1.1ms preprocess, 298.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLJhg1LDxAJrTA8OfmlQoA_270.JPG: 480x640 (no detections), 299.2ms
Speed: 1.2ms preprocess, 299.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLMADOENLDlUmjoVldVdvw_0.JPG: 480x640 (no detections), 299.2ms
Speed: 1.1ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLMADOENLDlUmjoVldVdvw_90.JPG: 480x640 (no detections), 303.2ms
Speed: 1.3ms preprocess, 303.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLMADOENLDlUmjoVldVdvw_180.JPG: 480x640 (no detections), 299.2ms
Speed: 1.1ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLMADOENLDlUmjoVldVdvw_270.JPG: 480x640 (no detections), 299.4ms

Speed: 1.2ms preprocess, 299.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLMO2aA7-GcH1IIQ-x877g_0.JPG: 480x640 (no detections), 303.1ms
Speed: 1.1ms preprocess, 303.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLMO2aA7-GcH1IIQ-x877g_90.JPG: 480x640 (no detections), 298.3ms
Speed: 1.1ms preprocess, 298.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLMO2aA7-GcH1IIQ-x877g_180.JPG: 480x640 (no detections), 297.4ms
Speed: 1.3ms preprocess, 297.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLMO2aA7-GcH1IIQ-x877g_270.JPG: 480x640 (no detections), 299.3ms
Speed: 1.2ms preprocess, 299.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLPbDYjfphH-82kf-Dvbcw_0.JPG: 480x640 (no detections), 297.6ms
Speed: 1.1ms preprocess, 297.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLPbDYjfphH-82kf-Dvbcw_90.JPG: 480x640 (no detections), 301.4ms
Speed: 1.3ms preprocess, 301.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLPbDYjfphH-82kf-Dvbcw_180.JPG: 480x640 (no detections), 303.1ms
Speed: 1.1ms preprocess, 303.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLPbDYjfphH-82kf-Dvbcw_270.JPG: 480x640 (no detections), 305.2ms
Speed: 1.2ms preprocess, 305.2ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLR7amdEF5FpI_7CUD4FVg_0.JPG: 480x640 (no detections), 302.3ms
Speed: 1.3ms preprocess, 302.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLR7amdEF5FpI_7CUD4FVg_90.JPG: 480x640 (no detections), 300.0ms
Speed: 1.4ms preprocess, 300.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLR7amdEF5FpI_7CUD4FVg_180.JPG: 480x640 (no detections), 309.4ms
Speed: 1.2ms preprocess, 309.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLR7amdEF5FpI_7CUD4FVg_270.JPG: 480x640 (no detections), 301.2ms
Speed: 1.7ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLUbO8J8iHxSGTC8MdUSVw_0.JPG: 480x640 (no detections), 296.7ms
Speed: 1.7ms preprocess, 296.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLUbO8J8iHxSGTC8MdUSVw_90.JPG: 480x640 (no detections), 296.3ms
Speed: 1.3ms preprocess, 296.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLUbO8J8iHxSGTC8MdUSVw_180.JPG: 480x640 (no detections), 302.8ms
Speed: 1.2ms preprocess, 302.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLUbO8J8iHxSGTC8MdUSVw_270.JPG: 480x640 (no detections), 301.7ms
Speed: 1.2ms preprocess, 301.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLVVc31FOGHtcT_4F5A7LA_0.JPG: 480x640 (no detections), 299.1ms
Speed: 1.6ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLVVc31FOGHtcT_4F5A7LA_90.JPG: 480x640 (no detections), 302.1ms
Speed: 1.2ms preprocess, 302.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLVVc31FOGHtcT_4F5A7LA_180.JPG: 480x640 (no detections), 303.4ms
Speed: 1.7ms preprocess, 303.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLVVc31FOGHtcT_4F5A7LA_270.JPG: 480x640 (no detections), 299.9ms
Speed: 1.3ms preprocess, 299.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLXc_PaGKgZKJ8HmlOXlSg_0.JPG: 480x640 (no detections), 299.5ms
Speed: 1.1ms preprocess, 299.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLXc_PaGKgZKJ8HmlOXlSg_90.JPG: 480x640 (no detections), 299.5ms
Speed: 1.2ms preprocess, 299.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLXc_PaGKgZKJ8HmlOXlSg_180.JPG: 480x640 (no detections), 303.0ms
Speed: 1.7ms preprocess, 303.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLXc_PaGKgZKJ8HmlOXlSg_270.JPG: 480x640 (no detections), 302.9ms
Speed: 1.1ms preprocess, 302.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLXg4gejCwuJBveQ-K7VhQ_0.JPG: 480x640 (no detections), 301.3ms
Speed: 2.0ms preprocess, 301.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLXg4gejCwuJBveQ-K7VhQ_90.JPG: 480x640 (no detections), 301.9ms
Speed: 1.1ms preprocess, 301.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLXg4gejCwuJBveQ-K7VhQ_180.JPG: 480x640 (no detections), 295.4ms
Speed: 1.1ms preprocess, 295.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLXg4gejCwuJBveQ-K7VhQ_270.JPG: 480x640 (no detections), 299.0ms
Speed: 1.0ms preprocess, 299.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLY1iJcz-dNCIZ5-jfRVAQ_0.JPG: 480x640 (no detections), 298.7ms
Speed: 1.3ms preprocess, 298.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLY1iJcz-dNCIZ5-jfRVAQ_90.JPG: 480x640 (no detections), 302.7ms
Speed: 1.1ms preprocess, 302.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLY1iJcz-dNCIZ5-jfRVAQ_180.JPG: 480x640 (no detections), 299.2ms
Speed: 1.2ms preprocess, 299.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLY1iJcz-dNCIZ5-jfRVAQ_270.JPG: 480x640 (no detections), 297.8ms
Speed: 1.1ms preprocess, 297.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLhzC1kuhlp-yfQ6XWhPgQ_0.JPG: 480x640 (no detections), 301.2ms
Speed: 1.4ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLhzC1kuhlp-yfQ6XWhPgQ_90.JPG: 480x640 (no detections), 299.1ms
Speed: 1.1ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLhzC1kuhlp-yfQ6XWhPgQ_180.JPG: 480x640 (no detections), 300.7ms
Speed: 1.0ms preprocess, 300.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLhzC1kuhlp-yfQ6XWhPgQ_270.JPG: 480x640 (no detections), 304.0ms
Speed: 1.3ms preprocess, 304.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLkV02t3v--2gko4AJJGVA_0.JPG: 480x640 (no detections), 305.4ms
Speed: 1.8ms preprocess, 305.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLkV02t3v--2gko4AJJGVA_90.JPG: 480x640 (no detections), 295.6ms
Speed: 1.2ms preprocess, 295.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLkV02t3v--2gko4AJJGVA_180.JPG: 480x640 (no detections), 298.6ms
Speed: 1.2ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLkV02t3v--2gko4AJJGVA_270.JPG: 480x640 (no detections), 301.7ms
Speed: 1.1ms preprocess, 301.7ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLoqe3w4r5bLzRLucjn9Uw_0.JPG: 480x640 (no detections), 298.1ms
Speed: 1.1ms preprocess, 298.1ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLoqe3w4r5bLzRLucjn9Uw_90.JPG: 480x640 (no detections), 299.8ms
Speed: 1.2ms preprocess, 299.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLoqe3w4r5bLzRLucjn9Uw_180.JPG: 480x640 (no detections), 307.5ms
Speed: 1.3ms preprocess, 307.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLoqe3w4r5bLzRLucjn9Uw_270.JPG: 480x640 (no detections), 300.3ms
Speed: 1.1ms preprocess, 300.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLqOx3h6eF8fh3cN7WsDfg_0.JPG: 480x640 (no detections), 303.1ms
Speed: 1.1ms preprocess, 303.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLqOx3h6eF8fh3cN7WsDfg_90.JPG: 480x640 (no detections), 301.1ms
Speed: 1.1ms preprocess, 301.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLqOx3h6eF8fh3cN7WsDfg_180.JPG: 480x640 (no detections), 295.5ms
Speed: 1.3ms preprocess, 295.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLqOx3h6eF8fh3cN7WsDfg_270.JPG: 480x640 (no detections), 295.7ms
Speed: 1.1ms preprocess, 295.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLryJNONkflnucPo1JGVmw_0.JPG: 480x640 (no detections), 305.3ms
Speed: 1.2ms preprocess, 305.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLryJNONkflnucPo1JGVmw_90.JPG: 480x640 (no detections), 308.7ms
Speed: 1.2ms preprocess, 308.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLryJNONkflnucPo1JGVmw_180.JPG: 480x640 (no detections), 296.0ms
Speed: 1.0ms preprocess, 296.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLryJNONkflnucPo1JGVmw_270.JPG: 480x640 (no detections), 299.2ms
Speed: 1.3ms preprocess, 299.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLt4jDZDeGfQUdiijPWAkw_0.JPG: 480x640 (no detections), 300.7ms
Speed: 1.4ms preprocess, 300.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLt4jDZDeGfQUdiijPWAkw_90.JPG: 480x640 (no detections), 303.6ms
Speed: 1.3ms preprocess, 303.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLt4jDZDeGfQUdiijPWAkw_180.JPG: 480x640 (no detections), 300.6ms
Speed: 1.1ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLt4jDZDeGfQUdiijPWAkw_270.JPG: 480x640 1 Waste, 301.9ms
Speed: 1.2ms preprocess, 301.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLxQo7BQnTTOKOJ5PinNQA_0.JPG: 480x640 (no detections), 299.3ms
Speed: 1.3ms preprocess, 299.3ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLxQo7BQnTTOKOJ5PinNQA_90.JPG: 480x640 (no detections), 308.0ms
Speed: 1.1ms preprocess, 308.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLxQo7BQnTTOKOJ5PinNQA_180.JPG: 480x640 (no detections), 296.4ms
Speed: 1.3ms preprocess, 296.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLxQo7BQnTTOKOJ5PinNQA_270.JPG: 480x640 (no detections), 302.9ms
Speed: 1.2ms preprocess, 302.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLyQyzfQtkghVmHs3Uhc2w_0.JPG: 480x640 (no detections), 298.5ms
Speed: 1.2ms preprocess, 298.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLyQyzfQtkghVmHs3Uhc2w_90.JPG: 480x640 (no detections), 301.9ms
Speed: 1.2ms preprocess, 301.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLyQyzfQtkghVmHs3Uhc2w_180.JPG: 480x640 (no detections), 299.8ms
Speed: 1.3ms preprocess, 299.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLyQyzfQtkghVmHs3Uhc2w_270.JPG: 480x640 (no detections), 301.7ms
Speed: 1.3ms preprocess, 301.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLzGyBi3tBvtcSPbNet09g_0.JPG: 480x640 (no detections), 300.2ms
Speed: 1.3ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLzGyBi3tBvtcSPbNet09g_90.JPG: 480x640 (no detections), 300.3ms
Speed: 1.3ms preprocess, 300.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLzGyBi3tBvtcSPbNet09g_180.JPG: 480x640 (no detections), 291.6ms

Speed: 1.2ms preprocess, 291.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLzGyBi3tBvtcSPbNet09g_270.JPG: 480x640 (no detections), 301.0ms
Speed: 1.1ms preprocess, 301.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLze78cJkcx6bKPduLzQVA_0.JPG: 480x640 (no detections), 299.3ms
Speed: 1.3ms preprocess, 299.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLze78cJkcx6bKPduLzQVA_90.JPG: 480x640 (no detections), 303.0ms
Speed: 1.1ms preprocess, 303.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLze78cJkcx6bKPduLzQVA_180.JPG: 480x640 (no detections), 296.6ms
Speed: 1.2ms preprocess, 296.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xLze78cJkcx6bKPduLzQVA_270.JPG: 480x640 (no detections), 300.7ms
Speed: 1.6ms preprocess, 300.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xM6jXa6cphSI9BAAuypItQ_0.JPG: 480x640 (no detections), 304.7ms
Speed: 1.4ms preprocess, 304.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xM6jXa6cphSI9BAAuypItQ_90.JPG: 480x640 (no detections), 308.1ms
Speed: 1.1ms preprocess, 308.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xM6jXa6cphSI9BAAuypItQ_180.JPG: 480x640 (no detections), 306.4ms
Speed: 1.3ms preprocess, 306.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xM6jXa6cphSI9BAAuypItQ_270.JPG: 480x640 (no detections), 305.6ms
Speed: 1.1ms preprocess, 305.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xM7d4unZWQLEUj8jbws9Pg_0.JPG: 480x640 (no detections), 300.0ms
Speed: 1.2ms preprocess, 300.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xM7d4unZWQLEUj8jbws9Pg_90.JPG: 480x640 (no detections), 296.3ms
Speed: 1.6ms preprocess, 296.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xM7d4unZWQLEUj8jbws9Pg_180.JPG: 480x640 (no detections), 297.3ms
Speed: 1.2ms preprocess, 297.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xM7d4unZWQLEUj8jbws9Pg_270.JPG: 480x640 (no detections), 301.8ms
Speed: 1.0ms preprocess, 301.8ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xM9nyQYdTyRoqLAhmfHGOQ_0.JPG: 480x640 (no detections), 298.4ms
Speed: 1.7ms preprocess, 298.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xM9nyQYdTyRoqLAhmfHGOQ_90.JPG: 480x640 (no detections), 300.4ms
Speed: 1.3ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xM9nyQYdTyRoqLAhmfHGOQ_180.JPG: 480x640 (no detections), 297.2ms
Speed: 1.1ms preprocess, 297.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xM9nyQYdTyRoqLAhmfHGOQ_270.JPG: 480x640 (no detections), 304.5ms
Speed: 1.2ms preprocess, 304.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMCkAoxChD-BK54YvnAqjg_0.JPG: 480x640 (no detections), 303.5ms
Speed: 1.2ms preprocess, 303.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMCkAoxChD-BK54YvnAqjg_90.JPG: 480x640 (no detections), 298.3ms
Speed: 1.2ms preprocess, 298.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMCkAoxChD-BK54YvnAqjg_180.JPG: 480x640 (no detections), 304.8ms
Speed: 1.3ms preprocess, 304.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMCkAoxChD-BK54YvnAqjg_270.JPG: 480x640 (no detections), 301.8ms
Speed: 1.2ms preprocess, 301.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMDelPzkKnMlLpBLppo4kg_0.JPG: 480x640 (no detections), 303.7ms
Speed: 1.2ms preprocess, 303.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMDelPzkKnMlLpBLppo4kg_90.JPG: 480x640 (no detections), 299.6ms
Speed: 1.1ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMDelPzkKnMlLpBLppo4kg_180.JPG: 480x640 (no detections), 300.0ms
Speed: 1.3ms preprocess, 300.0ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMDelPzkKnMlLpBLppo4kg_270.JPG: 480x640 (no detections), 298.2ms
Speed: 1.2ms preprocess, 298.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMDzWGgEAELuVRNnJliAMA_0.JPG: 480x640 (no detections), 296.5ms
Speed: 1.2ms preprocess, 296.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMDzWGgEAELuVRNnJliAMA_90.JPG: 480x640 (no detections), 301.2ms
Speed: 1.2ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMDzWGgEAELuVRNnJliAMA_180.JPG: 480x640 (no detections), 297.3ms
Speed: 1.1ms preprocess, 297.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMDzWGgEAELuVRNnJliAMA_270.JPG: 480x640 (no detections), 296.4ms
Speed: 1.2ms preprocess, 296.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMEHI3KjadOoCHfwQn96iQ_0.JPG: 480x640 (no detections), 302.0ms
Speed: 1.1ms preprocess, 302.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMEHI3KjadOoCHfwQn96iQ_90.JPG: 480x640 (no detections), 305.7ms
Speed: 1.1ms preprocess, 305.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMEHI3KjadOoCHfwQn96iQ_180.JPG: 480x640 (no detections), 300.1ms
Speed: 1.3ms preprocess, 300.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMEHI3KjadOoCHfwQn96iQ_270.JPG: 480x640 (no detections), 301.5ms
Speed: 1.3ms preprocess, 301.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMF1hjv6qQY6g7vHZa0c6A_0.JPG: 480x640 (no detections), 299.3ms
Speed: 1.2ms preprocess, 299.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMF1hjv6qQY6g7vHZa0c6A_90.JPG: 480x640 (no detections), 299.7ms
Speed: 1.1ms preprocess, 299.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMF1hjv6qQY6g7vHZa0c6A_180.JPG: 480x640 (no detections), 299.9ms
Speed: 1.2ms preprocess, 299.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMF1hjv6qQY6g7vHZa0c6A_270.JPG: 480x640 (no detections), 301.1ms
Speed: 1.0ms preprocess, 301.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMIXb81AnO8UV69oWaWbgw_0.JPG: 480x640 (no detections), 302.8ms
Speed: 1.3ms preprocess, 302.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMIXb81AnO8UV69oWaWbgw_90.JPG: 480x640 (no detections), 303.7ms
Speed: 1.1ms preprocess, 303.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMIXb81AnO8UV69oWaWbgw_180.JPG: 480x640 (no detections), 302.2ms
Speed: 1.3ms preprocess, 302.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMIXb81AnO8UV69oWaWbgw_270.JPG: 480x640 (no detections), 309.2ms
Speed: 1.3ms preprocess, 309.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMJMqD3be-_39xyA-qjoNA_0.JPG: 480x640 (no detections), 293.6ms
Speed: 1.1ms preprocess, 293.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMJMqD3be-_39xyA-qjoNA_90.JPG: 480x640 (no detections), 300.2ms
Speed: 1.3ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMJMqD3be-_39xyA-qjoNA_180.JPG: 480x640 (no detections), 291.3ms
Speed: 1.0ms preprocess, 291.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMJMqD3be-_39xyA-qjoNA_270.JPG: 480x640 (no detections), 292.2ms
Speed: 1.2ms preprocess, 292.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMMZnqtpsNV0Fk8wgv9h6Q_0.JPG: 480x640 (no detections), 293.8ms
Speed: 1.2ms preprocess, 293.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMMZnqtpsNV0Fk8wgv9h6Q_90.JPG: 480x640 (no detections), 292.4ms
Speed: 1.8ms preprocess, 292.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMMZnqtpsNV0Fk8wgv9h6Q_180.JPG: 480x640 (no detections), 291.5ms
Speed: 1.3ms preprocess, 291.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMMZnqtpsNV0Fk8wgv9h6Q_270.JPG: 480x640 (no detections), 293.0ms
Speed: 1.2ms preprocess, 293.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMOGXyfhvRCNEFo17_34OA_0.JPG: 480x640 (no detections), 291.7ms
Speed: 1.4ms preprocess, 291.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMOGXyfhvRCNEFo17_34OA_90.JPG: 480x640 (no detections), 302.8ms
Speed: 1.2ms preprocess, 302.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMOGXyfhvRCNEFo17_34OA_180.JPG: 480x640 (no detections), 299.9ms
Speed: 1.1ms preprocess, 299.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMOGXyfhvRCNEFo17_34OA_270.JPG: 480x640 (no detections), 306.8ms
Speed: 1.7ms preprocess, 306.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMPplnk45EQjSeQaHnP3vg_0.JPG: 480x640 (no detections), 301.2ms
Speed: 1.8ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMPplnk45EQjSeQaHnP3vg_90.JPG: 480x640 (no detections), 298.1ms
Speed: 1.4ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMPplnk45EQjSeQaHnP3vg_180.JPG: 480x640 (no detections), 307.5ms
Speed: 1.3ms preprocess, 307.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMPplnk45EQjSeQaHnP3vg_270.JPG: 480x640 (no detections), 296.1ms
Speed: 1.1ms preprocess, 296.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMQfCm04ezSVWdxrT1KR-g_0.JPG: 480x640 (no detections), 298.9ms
Speed: 1.1ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMQfCm04ezSVWdxrT1KR-g_90.JPG: 480x640 (no detections), 297.9ms
Speed: 1.1ms preprocess, 297.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMQfCm04ezSVWdxrT1KR-g_180.JPG: 480x640 (no detections), 306.0ms
Speed: 1.3ms preprocess, 306.0ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMQfCm04ezSVWdxrT1KR-g_270.JPG: 480x640 (no detections), 294.9ms
Speed: 1.1ms preprocess, 294.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMVUPt5AYnz1C-7LB34LLw_0.JPG: 480x640 (no detections), 304.3ms
Speed: 1.2ms preprocess, 304.3ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMVUPt5AYnz1C-7LB34LLw_90.JPG: 480x640 (no detections), 304.4ms
Speed: 1.3ms preprocess, 304.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMVUPt5AYnz1C-7LB34LLw_180.JPG: 480x640 (no detections), 302.6ms
Speed: 1.1ms preprocess, 302.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMVUPt5AYnz1C-7LB34LLw_270.JPG: 480x640 (no detections), 299.3ms
Speed: 1.0ms preprocess, 299.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMVk_HAXyakdrJOgcVSBdA_0.JPG: 480x640 (no detections), 300.5ms
Speed: 1.5ms preprocess, 300.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMVk_HAXyakdrJOgcVSBdA_90.JPG: 480x640 (no detections), 301.1ms

Speed: 1.4ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMVk_HAXyakdrJOgcVSBdA_180.JPG: 480x640 (no detections), 297.0ms
Speed: 1.1ms preprocess, 297.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMVk_HAXyakdrJOgcVSBdA_270.JPG: 480x640 (no detections), 302.8ms
Speed: 1.2ms preprocess, 302.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMYD2ADgDJAyM1FVd4iUAQ_0.JPG: 480x640 (no detections), 299.8ms
Speed: 1.1ms preprocess, 299.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMYD2ADgDJAyM1FVd4iUAQ_90.JPG: 480x640 (no detections), 297.2ms
Speed: 1.2ms preprocess, 297.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMYD2ADgDJAyM1FVd4iUAQ_180.JPG: 480x640 (no detections), 298.2ms
Speed: 1.2ms preprocess, 298.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMYD2ADgDJAyM1FVd4iUAQ_270.JPG: 480x640 (no detections), 299.2ms
Speed: 1.2ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMYwa3vJEmO4dWL2EQiqDw_0.JPG: 480x640 (no detections), 300.1ms
Speed: 1.1ms preprocess, 300.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMYwa3vJEmO4dWL2EQiqDw_90.JPG: 480x640 (no detections), 299.3ms
Speed: 1.1ms preprocess, 299.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMYwa3vJEmO4dWL2EQiqDw_180.JPG: 480x640 (no detections), 298.5ms
Speed: 1.2ms preprocess, 298.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMYwa3vJEmO4dWL2EQiqDw_270.JPG: 480x640 (no detections), 295.6ms
Speed: 1.2ms preprocess, 295.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMfsTNw8VuijjTarO3p9IQ_0.JPG: 480x640 (no detections), 297.3ms
Speed: 1.2ms preprocess, 297.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMfsTNw8VuijjTarO3p9IQ_90.JPG: 480x640 (no detections), 304.9ms
Speed: 1.0ms preprocess, 304.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMfsTNw8VuijjTarO3p9IQ_180.JPG: 480x640 (no detections), 297.2ms
Speed: 1.2ms preprocess, 297.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMfsTNw8VuijjTarO3p9IQ_270.JPG: 480x640 (no detections), 297.2ms
Speed: 1.3ms preprocess, 297.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMjeHuKhOyRxo2_12B0UGQ_0.JPG: 480x640 (no detections), 304.9ms
Speed: 1.2ms preprocess, 304.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMjeHuKhOyRxo2_12B0UGQ_90.JPG: 480x640 (no detections), 300.2ms
Speed: 1.3ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMjeHuKhOyRxo2_12B0UGQ_180.JPG: 480x640 (no detections), 293.4ms
Speed: 1.2ms preprocess, 293.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMjeHuKhOyRxo2_12B0UGQ_270.JPG: 480x640 (no detections), 289.4ms
Speed: 1.5ms preprocess, 289.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMl4N6rqhD8OC3OHt0zvUA_0.JPG: 480x640 (no detections), 304.8ms
Speed: 1.7ms preprocess, 304.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMl4N6rqhD8OC3OHt0zvUA_90.JPG: 480x640 (no detections), 298.1ms
Speed: 1.2ms preprocess, 298.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMl4N6rqhD8OC3OHt0zvUA_180.JPG: 480x640 (no detections), 299.9ms
Speed: 1.2ms preprocess, 299.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMl4N6rqhD8OC3OHt0zvUA_270.JPG: 480x640 (no detections), 302.7ms
Speed: 1.2ms preprocess, 302.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMn-YwZJFrG0Qby9i3rauA_0.JPG: 480x640 (no detections), 304.2ms
Speed: 1.6ms preprocess, 304.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMn-YwZJFrG0Qby9i3rauA_90.JPG: 480x640 (no detections), 300.1ms
Speed: 1.2ms preprocess, 300.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMn-YwZJFrG0Qby9i3rauA_180.JPG: 480x640 (no detections), 304.7ms
Speed: 1.1ms preprocess, 304.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMn-YwZJFrG0Qby9i3rauA_270.JPG: 480x640 (no detections), 302.1ms
Speed: 1.1ms preprocess, 302.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMnPYdItb2xHBNhPQi2e6g_0.JPG: 480x640 (no detections), 298.3ms
Speed: 1.0ms preprocess, 298.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMnPYdItb2xHBNhPQi2e6g_90.JPG: 480x640 (no detections), 298.0ms
Speed: 1.2ms preprocess, 298.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMnPYdItb2xHBNhPQi2e6g_180.JPG: 480x640 (no detections), 302.1ms
Speed: 1.4ms preprocess, 302.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMnPYdItb2xHBNhPQi2e6g_270.JPG: 480x640 (no detections), 302.9ms
Speed: 1.2ms preprocess, 302.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMpBc7y_6aONeK0-adgucQ_0.JPG: 480x640 (no detections), 299.2ms
Speed: 1.3ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMpBc7y_6aONeK0-adgucQ_90.JPG: 480x640 (no detections), 295.7ms
Speed: 1.1ms preprocess, 295.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMpBc7y_6aONeK0-adgucQ_180.JPG: 480x640 (no detections), 302.2ms
Speed: 1.2ms preprocess, 302.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMpBc7y_6aONeK0-adgucQ_270.JPG: 480x640 (no detections), 296.5ms
Speed: 1.1ms preprocess, 296.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMpmT8ZsM7BIvx7eeruwnQ_0.JPG: 480x640 (no detections), 305.5ms
Speed: 1.1ms preprocess, 305.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMpmT8ZsM7BIvx7eeruwnQ_90.JPG: 480x640 (no detections), 302.8ms
Speed: 1.1ms preprocess, 302.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMpmT8ZsM7BIvx7eeruwnQ_180.JPG: 480x640 (no detections), 302.6ms
Speed: 1.3ms preprocess, 302.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMpmT8ZsM7BIvx7eeruwnQ_270.JPG: 480x640 (no detections), 298.0ms
Speed: 1.2ms preprocess, 298.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMptMKjitv7RJ172R5kirw_0.JPG: 480x640 (no detections), 299.7ms
Speed: 1.0ms preprocess, 299.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMptMKjitv7RJ172R5kirw_90.JPG: 480x640 (no detections), 295.8ms
Speed: 1.1ms preprocess, 295.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMptMKjitv7RJ172R5kirw_180.JPG: 480x640 (no detections), 304.4ms
Speed: 1.8ms preprocess, 304.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMptMKjitv7RJ172R5kirw_270.JPG: 480x640 (no detections), 298.0ms
Speed: 1.2ms preprocess, 298.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMrLiZJxgK3fUJ75TBGF_g_0.JPG: 480x640 (no detections), 297.8ms
Speed: 1.0ms preprocess, 297.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMrLiZJxgK3fUJ75TBGF_g_90.JPG: 480x640 (no detections), 299.3ms
Speed: 1.1ms preprocess, 299.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMrLiZJxgK3fUJ75TBGF_g_180.JPG: 480x640 (no detections), 298.1ms
Speed: 1.1ms preprocess, 298.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMrLiZJxgK3fUJ75TBGF_g_270.JPG: 480x640 (no detections), 298.0ms
Speed: 1.1ms preprocess, 298.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMyMSZ7Bg2UCY1AXvxWx0A_0.JPG: 480x640 (no detections), 299.8ms
Speed: 1.1ms preprocess, 299.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMyMSZ7Bg2UCY1AXvxWx0A_90.JPG: 480x640 (no detections), 305.2ms
Speed: 1.2ms preprocess, 305.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMyMSZ7Bg2UCY1AXvxWx0A_180.JPG: 480x640 (no detections), 298.4ms
Speed: 1.1ms preprocess, 298.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMyMSZ7Bg2UCY1AXvxWx0A_270.JPG: 480x640 (no detections), 304.1ms
Speed: 1.5ms preprocess, 304.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMzeCARrf7ftg4dkLm02fQ_0.JPG: 480x640 (no detections), 303.5ms
Speed: 1.6ms preprocess, 303.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMzeCARrf7ftg4dkLm02fQ_90.JPG: 480x640 (no detections), 300.9ms
Speed: 1.1ms preprocess, 300.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMzeCARrf7ftg4dkLm02fQ_180.JPG: 480x640 (no detections), 297.0ms
Speed: 1.1ms preprocess, 297.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMzeCARrf7ftg4dkLm02fQ_270.JPG: 480x640 (no detections), 303.9ms
Speed: 1.2ms preprocess, 303.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMzeU6UDqYIPtZqdQRp2VQ_0.JPG: 480x640 (no detections), 297.0ms
Speed: 1.1ms preprocess, 297.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMzeU6UDqYIPtZqdQRp2VQ_90.JPG: 480x640 (no detections), 298.5ms
Speed: 1.2ms preprocess, 298.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMzeU6UDqYIPtZqdQRp2VQ_180.JPG: 480x640 (no detections), 299.3ms
Speed: 1.2ms preprocess, 299.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xMzeU6UDqYIPtZqdQRp2VQ_270.JPG: 480x640 (no detections), 297.6ms
Speed: 1.2ms preprocess, 297.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xN503HT8rAeHVQohOghMsg_0.JPG: 480x640 (no detections), 299.2ms
Speed: 1.4ms preprocess, 299.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xN503HT8rAeHVQohOghMsg_90.JPG: 480x640 1 Waste, 298.2ms
Speed: 1.2ms preprocess, 298.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xN503HT8rAeHVQohOghMsg_180.JPG: 480x640 (no detections), 302.3ms
Speed: 1.2ms preprocess, 302.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xN503HT8rAeHVQohOghMsg_270.JPG: 480x640 (no detections), 305.0ms
Speed: 1.4ms preprocess, 305.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xN6q5MBW_7U2A9-Whw94bA_0.JPG: 480x640 1 Waste, 300.4ms
Speed: 1.3ms preprocess, 300.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xN6q5MBW_7U2A9-Whw94bA_90.JPG: 480x640 (no detections), 304.4ms
Speed: 1.0ms preprocess, 304.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xN6q5MBW_7U2A9-Whw94bA_180.JPG: 480x640 (no detections), 300.4ms
Speed: 1.1ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xN6q5MBW_7U2A9-Whw94bA_270.JPG: 480x640 1 Waste, 297.7ms
Speed: 1.4ms preprocess, 297.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xN9wxsnI7t7FqHBpucqUYQ_0.JPG: 480x640 (no detections), 300.4ms

Speed: 1.3ms preprocess, 300.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xN9wxsnI7t7FqHBpucqUYQ_90.JPG: 480x640 (no detections), 297.6ms
Speed: 1.8ms preprocess, 297.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xN9wxsnI7t7FqHBpucqUYQ_180.JPG: 480x640 (no detections), 302.7ms
Speed: 1.5ms preprocess, 302.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xN9wxsnI7t7FqHBpucqUYQ_270.JPG: 480x640 (no detections), 304.1ms
Speed: 1.1ms preprocess, 304.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNHdf_q5cEsYl-VlU7E6NA_0.JPG: 480x640 (no detections), 299.3ms
Speed: 1.5ms preprocess, 299.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNHdf_q5cEsYl-VlU7E6NA_90.JPG: 480x640 (no detections), 297.0ms
Speed: 1.2ms preprocess, 297.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNHdf_q5cEsYl-VlU7E6NA_180.JPG: 480x640 (no detections), 299.1ms
Speed: 1.1ms preprocess, 299.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNHdf_q5cEsYl-VlU7E6NA_270.JPG: 480x640 (no detections), 301.8ms
Speed: 1.2ms preprocess, 301.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNJg4sg0kf1Mz-fOMwjdrA_0.JPG: 480x640 (no detections), 303.0ms
Speed: 1.3ms preprocess, 303.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNJg4sg0kf1Mz-fOMwjdrA_90.JPG: 480x640 (no detections), 298.2ms
Speed: 1.1ms preprocess, 298.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNJg4sg0kf1Mz-fOMwjdrA_180.JPG: 480x640 (no detections), 300.7ms
Speed: 1.8ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNJg4sg0kf1Mz-fOMwjdrA_270.JPG: 480x640 (no detections), 295.1ms
Speed: 1.4ms preprocess, 295.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNJl801n4OznbAeI4oxQbg_0.JPG: 480x640 (no detections), 299.0ms
Speed: 1.5ms preprocess, 299.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNJl801n4OznbAeI4oxQbg_90.JPG: 480x640 (no detections), 307.8ms
Speed: 1.1ms preprocess, 307.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNJl801n4OznbAeI4oxQbg_180.JPG: 480x640 (no detections), 303.7ms
Speed: 1.2ms preprocess, 303.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNJl801n4OznbAeI4oxQbg_270.JPG: 480x640 (no detections), 297.4ms
Speed: 1.1ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNR3lgX-FghjJaQQDqBVRA_0.JPG: 480x640 (no detections), 295.8ms
Speed: 1.1ms preprocess, 295.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNR3lgX-FghjJaQQDqBVRA_90.JPG: 480x640 (no detections), 306.0ms
Speed: 1.2ms preprocess, 306.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNR3lgX-FghjJaQQDqBVRA_180.JPG: 480x640 (no detections), 302.6ms
Speed: 1.2ms preprocess, 302.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNR3lgX-FghjJaQQDqBVRA_270.JPG: 480x640 (no detections), 299.8ms
Speed: 1.1ms preprocess, 299.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNXJkHKoY9mm-6VdX7SF7A_0.JPG: 480x640 (no detections), 302.8ms
Speed: 1.1ms preprocess, 302.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNXJkHKoY9mm-6VdX7SF7A_90.JPG: 480x640 (no detections), 302.3ms
Speed: 1.3ms preprocess, 302.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNXJkHKoY9mm-6VdX7SF7A_180.JPG: 480x640 (no detections), 302.9ms
Speed: 1.1ms preprocess, 302.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNXJkHKoY9mm-6VdX7SF7A_270.JPG: 480x640 (no detections), 296.3ms
Speed: 1.1ms preprocess, 296.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNXo38Pf_cwvwHoJZpzWMA_0.JPG: 480x640 (no detections), 301.6ms
Speed: 1.2ms preprocess, 301.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNXo38Pf_cwvwHoJZpzWMA_90.JPG: 480x640 (no detections), 298.7ms
Speed: 1.1ms preprocess, 298.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNXo38Pf_cwvwHoJZpzWMA_180.JPG: 480x640 (no detections), 306.6ms
Speed: 1.1ms preprocess, 306.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNXo38Pf_cwvwHoJZpzWMA_270.JPG: 480x640 (no detections), 299.6ms
Speed: 1.5ms preprocess, 299.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNckbXXVSFL9DL0kfakCiQ_0.JPG: 480x640 (no detections), 298.8ms
Speed: 1.7ms preprocess, 298.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNckbXXVSFL9DL0kfakCiQ_90.JPG: 480x640 (no detections), 301.6ms
Speed: 2.0ms preprocess, 301.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNckbXXVSFL9DL0kfakCiQ_180.JPG: 480x640 (no detections), 303.3ms
Speed: 1.0ms preprocess, 303.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNckbXXVSFL9DL0kfakCiQ_270.JPG: 480x640 (no detections), 297.5ms
Speed: 1.2ms preprocess, 297.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNdkpSQ3SnKQdzte96YZjg_0.JPG: 480x640 (no detections), 300.9ms
Speed: 1.3ms preprocess, 300.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNdkpSQ3SnKQdzte96YZjg_90.JPG: 480x640 (no detections), 301.8ms
Speed: 1.3ms preprocess, 301.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNdkpSQ3SnKQdzte96YZjg_180.JPG: 480x640 (no detections), 302.9ms
Speed: 1.3ms preprocess, 302.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNdkpSQ3SnKQdzte96YZjg_270.JPG: 480x640 1 Waste, 297.7ms
Speed: 1.2ms preprocess, 297.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNiYC-JGgr-tAAl5SI8ThA_0.JPG: 480x640 (no detections), 300.2ms
Speed: 1.6ms preprocess, 300.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNiYC-JGgr-tAAl5SI8ThA_90.JPG: 480x640 (no detections), 303.4ms
Speed: 1.0ms preprocess, 303.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNiYC-JGgr-tAAl5SI8ThA_180.JPG: 480x640 (no detections), 301.0ms
Speed: 1.4ms preprocess, 301.0ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNiYC-JGgr-tAAl5SI8ThA_270.JPG: 480x640 (no detections), 299.0ms
Speed: 1.3ms preprocess, 299.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNjGrhsiDR7ZAhS-YZVoUg_0.JPG: 480x640 (no detections), 297.7ms
Speed: 1.2ms preprocess, 297.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNjGrhsiDR7ZAhS-YZVoUg_90.JPG: 480x640 (no detections), 297.6ms
Speed: 1.2ms preprocess, 297.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNjGrhsiDR7ZAhS-YZVoUg_180.JPG: 480x640 (no detections), 294.1ms
Speed: 1.1ms preprocess, 294.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNjGrhsiDR7ZAhS-YZVoUg_270.JPG: 480x640 (no detections), 299.8ms
Speed: 1.1ms preprocess, 299.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNjqx9x4GZk4c7sx4NZxMw_0.JPG: 480x640 (no detections), 307.2ms
Speed: 1.3ms preprocess, 307.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNjqx9x4GZk4c7sx4NZxMw_90.JPG: 480x640 1 Waste, 304.1ms
Speed: 1.3ms preprocess, 304.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNjqx9x4GZk4c7sx4NZxMw_180.JPG: 480x640 (no detections), 299.6ms
Speed: 1.3ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNjqx9x4GZk4c7sx4NZxMw_270.JPG: 480x640 (no detections), 301.2ms
Speed: 1.1ms preprocess, 301.2ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNkodyIAKvnA2UT2RTK-zQ_0.JPG: 480x640 (no detections), 301.0ms
Speed: 1.2ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNkodyIAKvnA2UT2RTK-zQ_90.JPG: 480x640 (no detections), 300.5ms
Speed: 1.3ms preprocess, 300.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNkodyIAKvnA2UT2RTK-zQ_180.JPG: 480x640 (no detections), 296.8ms
Speed: 1.6ms preprocess, 296.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNkodyIAKvnA2UT2RTK-zQ_270.JPG: 480x640 (no detections), 299.4ms
Speed: 1.1ms preprocess, 299.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNl36Vdy0AkwaDGB514oKQ_0.JPG: 480x640 (no detections), 297.7ms
Speed: 1.3ms preprocess, 297.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNl36Vdy0AkwaDGB514oKQ_90.JPG: 480x640 (no detections), 303.8ms
Speed: 1.1ms preprocess, 303.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNl36Vdy0AkwaDGB514oKQ_180.JPG: 480x640 (no detections), 306.3ms
Speed: 1.2ms preprocess, 306.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNl36Vdy0AkwaDGB514oKQ_270.JPG: 480x640 (no detections), 304.9ms
Speed: 1.2ms preprocess, 304.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNlL82NBf-bGf-CLxlV30Q_0.JPG: 480x640 (no detections), 306.1ms
Speed: 1.2ms preprocess, 306.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNlL82NBf-bGf-CLxlV30Q_90.JPG: 480x640 (no detections), 298.8ms
Speed: 1.1ms preprocess, 298.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNlL82NBf-bGf-CLxlV30Q_180.JPG: 480x640 (no detections), 301.1ms
Speed: 1.1ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNlL82NBf-bGf-CLxlV30Q_270.JPG: 480x640 (no detections), 300.3ms
Speed: 1.6ms preprocess, 300.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNlmZ85tMf8_wtzjSYDerQ_0.JPG: 480x640 (no detections), 312.0ms
Speed: 1.2ms preprocess, 312.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNlmZ85tMf8_wtzjSYDerQ_90.JPG: 480x640 (no detections), 300.6ms
Speed: 1.2ms preprocess, 300.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNlmZ85tMf8_wtzjSYDerQ_180.JPG: 480x640 (no detections), 301.1ms
Speed: 1.2ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNlmZ85tMf8_wtzjSYDerQ_270.JPG: 480x640 (no detections), 302.0ms
Speed: 1.3ms preprocess, 302.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNmxaUyTSGXI5dSzJ4YdWw_0.JPG: 480x640 (no detections), 307.1ms
Speed: 1.3ms preprocess, 307.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNmxaUyTSGXI5dSzJ4YdWw_90.JPG: 480x640 (no detections), 300.3ms
Speed: 1.2ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNmxaUyTSGXI5dSzJ4YdWw_180.JPG: 480x640 (no detections), 305.9ms
Speed: 1.3ms preprocess, 305.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNmxaUyTSGXI5dSzJ4YdWw_270.JPG: 480x640 (no detections), 302.0ms

Speed: 1.2ms preprocess, 302.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNoaB67OjxXUXJ_iUXyjqQ_0.JPG: 480x640 1 Waste, 296.1ms
Speed: 1.3ms preprocess, 296.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNoaB67OjxXUXJ_iUXyjqQ_90.JPG: 480x640 (no detections), 303.3ms
Speed: 1.2ms preprocess, 303.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNoaB67OjxXUXJ_iUXyjqQ_180.JPG: 480x640 (no detections), 299.2ms
Speed: 1.1ms preprocess, 299.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNoaB67OjxXUXJ_iUXyjqQ_270.JPG: 480x640 (no detections), 295.0ms
Speed: 1.0ms preprocess, 295.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNqUhezIuzKHtOM1DQUN6A_0.JPG: 480x640 (no detections), 301.6ms
Speed: 1.2ms preprocess, 301.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNqUhezIuzKHtOM1DQUN6A_90.JPG: 480x640 (no detections), 303.6ms
Speed: 1.8ms preprocess, 303.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNqUhezIuzKHtOM1DQUN6A_180.JPG: 480x640 (no detections), 298.7ms
Speed: 1.1ms preprocess, 298.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNqUhezIuzKHtOM1DQUN6A_270.JPG: 480x640 1 Waste, 297.8ms
Speed: 1.1ms preprocess, 297.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNqiJdtM-y__zHZP9NGSrQ_0.JPG: 480x640 (no detections), 299.4ms
Speed: 1.2ms preprocess, 299.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNqiJdtM-y__zHZP9NGSrQ_90.JPG: 480x640 (no detections), 304.1ms
Speed: 1.0ms preprocess, 304.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNqiJdtM-y__zHZP9NGSrQ_180.JPG: 480x640 (no detections), 298.8ms
Speed: 1.2ms preprocess, 298.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNqiJdtM-y__zHZP9NGSrQ_270.JPG: 480x640 (no detections), 298.4ms
Speed: 1.2ms preprocess, 298.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNr8vpU1cMFn5SKZsmAc4g_0.JPG: 480x640 (no detections), 304.2ms
Speed: 1.2ms preprocess, 304.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNr8vpU1cMFn5SKZsmAc4g_90.JPG: 480x640 (no detections), 296.5ms
Speed: 1.0ms preprocess, 296.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNr8vpU1cMFn5SKZsmAc4g_180.JPG: 480x640 (no detections), 300.5ms
Speed: 1.2ms preprocess, 300.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNr8vpU1cMFn5SKZsmAc4g_270.JPG: 480x640 (no detections), 300.0ms
Speed: 1.1ms preprocess, 300.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNrVh8YmWPA_q-kT9yR1OQ_0.JPG: 480x640 (no detections), 302.5ms
Speed: 1.0ms preprocess, 302.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNrVh8YmWPA_q-kT9yR1OQ_90.JPG: 480x640 (no detections), 300.4ms
Speed: 1.5ms preprocess, 300.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNrVh8YmWPA_q-kT9yR1OQ_180.JPG: 480x640 (no detections), 301.0ms
Speed: 1.1ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNrVh8YmWPA_q-kT9yR1OQ_270.JPG: 480x640 (no detections), 299.5ms
Speed: 1.2ms preprocess, 299.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNwUfhgQva-6Tf6gBrGQgA_0.JPG: 480x640 (no detections), 384.0ms
Speed: 1.1ms preprocess, 384.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNwUfhgQva-6Tf6gBrGQgA_90.JPG: 480x640 (no detections), 302.2ms
Speed: 1.3ms preprocess, 302.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNwUfhgQva-6Tf6gBrGQgA_180.JPG: 480x640 (no detections), 300.6ms
Speed: 1.3ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNwUfhgQva-6Tf6gBrGQgA_270.JPG: 480x640 (no detections), 304.4ms
Speed: 1.5ms preprocess, 304.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNxe-zw7ZoheUA2YzRYQHg_0.JPG: 480x640 (no detections), 302.8ms
Speed: 1.2ms preprocess, 302.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNxe-zw7ZoheUA2YzRYQHg_90.JPG: 480x640 (no detections), 298.9ms
Speed: 1.2ms preprocess, 298.9ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNxe-zw7ZoheUA2YzRYQHg_180.JPG: 480x640 (no detections), 296.7ms
Speed: 1.3ms preprocess, 296.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNxe-zw7ZoheUA2YzRYQHg_270.JPG: 480x640 (no detections), 301.9ms
Speed: 1.1ms preprocess, 301.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNzeiv7K2NyVf1NyD_etiw_0.JPG: 480x640 (no detections), 301.5ms
Speed: 1.8ms preprocess, 301.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNzeiv7K2NyVf1NyD_etiw_90.JPG: 480x640 1 Waste, 302.4ms
Speed: 1.1ms preprocess, 302.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNzeiv7K2NyVf1NyD_etiw_180.JPG: 480x640 (no detections), 301.0ms
Speed: 1.2ms preprocess, 301.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xNzeiv7K2NyVf1NyD_etiw_270.JPG: 480x640 (no detections), 307.6ms
Speed: 1.4ms preprocess, 307.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xO0xnT_SiPxmb6ySG-aD1Q_0.JPG: 480x640 (no detections), 306.3ms
Speed: 1.2ms preprocess, 306.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xO0xnT_SiPxmb6ySG-aD1Q_90.JPG: 480x640 (no detections), 298.0ms
Speed: 1.3ms preprocess, 298.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xO0xnT_SiPxmb6ySG-aD1Q_180.JPG: 480x640 (no detections), 298.5ms
Speed: 1.3ms preprocess, 298.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xO0xnT_SiPxmb6ySG-aD1Q_270.JPG: 480x640 (no detections), 299.2ms
Speed: 1.3ms preprocess, 299.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xO2WmF7fz9nN8iq3-qNmEQ_0.JPG: 480x640 (no detections), 302.9ms
Speed: 1.2ms preprocess, 302.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xO2WmF7fz9nN8iq3-qNmEQ_90.JPG: 480x640 (no detections), 304.9ms
Speed: 1.2ms preprocess, 304.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xO2WmF7fz9nN8iq3-qNmEQ_180.JPG: 480x640 (no detections), 303.0ms
Speed: 1.9ms preprocess, 303.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xO2WmF7fz9nN8iq3-qNmEQ_270.JPG: 480x640 (no detections), 297.5ms
Speed: 1.9ms preprocess, 297.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xO2sqUKnCyChHDpS8TOGxQ_0.JPG: 480x640 (no detections), 302.8ms
Speed: 1.3ms preprocess, 302.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xO2sqUKnCyChHDpS8TOGxQ_90.JPG: 480x640 (no detections), 299.7ms
Speed: 1.2ms preprocess, 299.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xO2sqUKnCyChHDpS8TOGxQ_180.JPG: 480x640 (no detections), 296.7ms
Speed: 1.2ms preprocess, 296.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xO2sqUKnCyChHDpS8TOGxQ_270.JPG: 480x640 (no detections), 295.5ms
Speed: 1.1ms preprocess, 295.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xO4EerZeNWgiQ4KrlTaw8w_0.JPG: 480x640 (no detections), 303.6ms
Speed: 1.3ms preprocess, 303.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xO4EerZeNWgiQ4KrlTaw8w_90.JPG: 480x640 (no detections), 297.5ms
Speed: 1.2ms preprocess, 297.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xO4EerZeNWgiQ4KrlTaw8w_180.JPG: 480x640 (no detections), 361.6ms
Speed: 1.3ms preprocess, 361.6ms inference, 7.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xO4EerZeNWgiQ4KrlTaw8w_270.JPG: 480x640 (no detections), 318.0ms
Speed: 1.1ms preprocess, 318.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xO5dmcUrsZglqRXtIDzkwg_0.JPG: 480x640 (no detections), 303.7ms
Speed: 1.2ms preprocess, 303.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xO5dmcUrsZglqRXtIDzkwg_90.JPG: 480x640 (no detections), 367.9ms
Speed: 5.0ms preprocess, 367.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xO5dmcUrsZglqRXtIDzkwg_180.JPG: 480x640 (no detections), 301.7ms
Speed: 1.4ms preprocess, 301.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xO5dmcUrsZglqRXtIDzkwg_270.JPG: 480x640 (no detections), 376.4ms
Speed: 1.2ms preprocess, 376.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xO8OnwU7IHDX_z1Y2ZxoOA_0.JPG: 480x640 (no detections), 296.8ms
Speed: 1.2ms preprocess, 296.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xO8OnwU7IHDX_z1Y2ZxoOA_90.JPG: 480x640 (no detections), 300.0ms
Speed: 1.1ms preprocess, 300.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xO8OnwU7IHDX_z1Y2ZxoOA_180.JPG: 480x640 (no detections), 303.9ms
Speed: 1.2ms preprocess, 303.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xO8OnwU7IHDX_z1Y2ZxoOA_270.JPG: 480x640 (no detections), 297.5ms
Speed: 1.2ms preprocess, 297.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xO9KmDEZli2ZFaHM8SVQng_0.JPG: 480x640 (no detections), 303.3ms
Speed: 1.1ms preprocess, 303.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xO9KmDEZli2ZFaHM8SVQng_90.JPG: 480x640 (no detections), 297.0ms
Speed: 1.2ms preprocess, 297.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xO9KmDEZli2ZFaHM8SVQng_180.JPG: 480x640 (no detections), 297.5ms
Speed: 1.1ms preprocess, 297.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xO9KmDEZli2ZFaHM8SVQng_270.JPG: 480x640 1 Waste, 300.1ms
Speed: 1.0ms preprocess, 300.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOFf407UJnNmolhkiTCFcw_0.JPG: 480x640 (no detections), 299.2ms
Speed: 1.3ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOFf407UJnNmolhkiTCFcw_90.JPG: 480x640 (no detections), 302.3ms
Speed: 1.3ms preprocess, 302.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOFf407UJnNmolhkiTCFcw_180.JPG: 480x640 (no detections), 304.1ms
Speed: 1.4ms preprocess, 304.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOFf407UJnNmolhkiTCFcw_270.JPG: 480x640 (no detections), 294.7ms
Speed: 1.1ms preprocess, 294.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOFw_8h9wWEW1dLqPtiuVA_0.JPG: 480x640 (no detections), 300.4ms
Speed: 1.3ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOFw_8h9wWEW1dLqPtiuVA_90.JPG: 480x640 (no detections), 298.6ms
Speed: 1.1ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOFw_8h9wWEW1dLqPtiuVA_180.JPG: 480x640 (no detections), 298.1ms

Speed: 1.1ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOFw_8h9wWEW1dLqPtiuVA_270.JPG: 480x640 (no detections), 301.2ms
Speed: 1.8ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOGs5vGyNjTN524tY-Ouxw_0.JPG: 480x640 (no detections), 302.6ms
Speed: 1.3ms preprocess, 302.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOGs5vGyNjTN524tY-Ouxw_90.JPG: 480x640 (no detections), 302.9ms
Speed: 1.2ms preprocess, 302.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOGs5vGyNjTN524tY-Ouxw_180.JPG: 480x640 (no detections), 307.9ms
Speed: 1.2ms preprocess, 307.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOGs5vGyNjTN524tY-Ouxw_270.JPG: 480x640 (no detections), 298.6ms
Speed: 1.2ms preprocess, 298.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOIROUa8F1YRChds18-nag_0.JPG: 480x640 (no detections), 305.3ms
Speed: 1.2ms preprocess, 305.3ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOIROUa8F1YRChds18-nag_90.JPG: 480x640 (no detections), 305.5ms
Speed: 1.2ms preprocess, 305.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOIROUa8F1YRChds18-nag_180.JPG: 480x640 (no detections), 303.0ms
Speed: 1.1ms preprocess, 303.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOIROUa8F1YRChds18-nag_270.JPG: 480x640 (no detections), 298.0ms
Speed: 1.1ms preprocess, 298.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xORoFSn8s-gKc7R_50USgQ_0.JPG: 480x640 (no detections), 293.8ms
Speed: 1.2ms preprocess, 293.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xORoFSn8s-gKc7R_50USgQ_90.JPG: 480x640 (no detections), 297.3ms
Speed: 1.3ms preprocess, 297.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xORoFSn8s-gKc7R_50USgQ_180.JPG: 480x640 (no detections), 300.5ms
Speed: 1.5ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xORoFSn8s-gKc7R_50USgQ_270.JPG: 480x640 (no detections), 301.7ms
Speed: 1.2ms preprocess, 301.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOTGy2MX2EAm0JU5xukZOg_0.JPG: 480x640 (no detections), 300.5ms
Speed: 1.9ms preprocess, 300.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOTGy2MX2EAm0JU5xukZOg_90.JPG: 480x640 (no detections), 307.8ms
Speed: 1.1ms preprocess, 307.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOTGy2MX2EAm0JU5xukZOg_180.JPG: 480x640 (no detections), 302.3ms
Speed: 1.4ms preprocess, 302.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOTGy2MX2EAm0JU5xukZOg_270.JPG: 480x640 (no detections), 302.0ms
Speed: 1.9ms preprocess, 302.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOWtL83Hr1UzrG4NWoa6wg_0.JPG: 480x640 (no detections), 297.7ms
Speed: 1.1ms preprocess, 297.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOWtL83Hr1UzrG4NWoa6wg_90.JPG: 480x640 (no detections), 297.1ms
Speed: 1.3ms preprocess, 297.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOWtL83Hr1UzrG4NWoa6wg_180.JPG: 480x640 (no detections), 303.9ms
Speed: 1.7ms preprocess, 303.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOWtL83Hr1UzrG4NWoa6wg_270.JPG: 480x640 (no detections), 299.5ms
Speed: 1.5ms preprocess, 299.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOYd0CDIYdnBCCLwqLV7TQ_0.JPG: 480x640 (no detections), 306.8ms
Speed: 1.1ms preprocess, 306.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOYd0CDIYdnBCCLwqLV7TQ_90.JPG: 480x640 (no detections), 300.7ms
Speed: 1.2ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOYd0CDIYdnBCCLwqLV7TQ_180.JPG: 480x640 (no detections), 302.6ms
Speed: 1.1ms preprocess, 302.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOYd0CDIYdnBCCLwqLV7TQ_270.JPG: 480x640 (no detections), 302.8ms
Speed: 1.3ms preprocess, 302.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xObF1bZoOQKffn-i_xCeLg_0.JPG: 480x640 (no detections), 301.4ms
Speed: 1.1ms preprocess, 301.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xObF1bZoOQKffn-i_xCeLg_90.JPG: 480x640 (no detections), 302.4ms
Speed: 1.1ms preprocess, 302.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xObF1bZoOQKffn-i_xCeLg_180.JPG: 480x640 (no detections), 298.2ms
Speed: 1.1ms preprocess, 298.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xObF1bZoOQKffn-i_xCeLg_270.JPG: 480x640 (no detections), 302.7ms
Speed: 1.2ms preprocess, 302.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xObbaedSqn7mwsWzkM00tQ_0.JPG: 480x640 (no detections), 303.7ms
Speed: 1.1ms preprocess, 303.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xObbaedSqn7mwsWzkM00tQ_90.JPG: 480x640 (no detections), 298.8ms
Speed: 1.2ms preprocess, 298.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xObbaedSqn7mwsWzkM00tQ_180.JPG: 480x640 (no detections), 303.4ms
Speed: 1.2ms preprocess, 303.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xObbaedSqn7mwsWzkM00tQ_270.JPG: 480x640 (no detections), 300.8ms
Speed: 1.1ms preprocess, 300.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOcHEOZk2Fr5vwKQrM41_g_0.JPG: 480x640 (no detections), 296.8ms
Speed: 1.2ms preprocess, 296.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOcHEOZk2Fr5vwKQrM41_g_90.JPG: 480x640 (no detections), 303.1ms
Speed: 1.2ms preprocess, 303.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOcHEOZk2Fr5vwKQrM41_g_180.JPG: 480x640 (no detections), 297.9ms
Speed: 1.1ms preprocess, 297.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOcHEOZk2Fr5vwKQrM41_g_270.JPG: 480x640 (no detections), 306.8ms
Speed: 1.0ms preprocess, 306.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOg6p5_VW9-q2bFLj04uIw_0.JPG: 480x640 (no detections), 301.3ms
Speed: 1.3ms preprocess, 301.3ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOg6p5_VW9-q2bFLj04uIw_90.JPG: 480x640 (no detections), 295.5ms
Speed: 1.1ms preprocess, 295.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOg6p5_VW9-q2bFLj04uIw_180.JPG: 480x640 (no detections), 305.8ms
Speed: 1.2ms preprocess, 305.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOg6p5_VW9-q2bFLj04uIw_270.JPG: 480x640 (no detections), 300.0ms
Speed: 1.2ms preprocess, 300.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOgMx9oMX7rYN20zjqNy2Q_0.JPG: 480x640 (no detections), 299.6ms
Speed: 1.1ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOgMx9oMX7rYN20zjqNy2Q_90.JPG: 480x640 (no detections), 307.5ms
Speed: 1.2ms preprocess, 307.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOgMx9oMX7rYN20zjqNy2Q_180.JPG: 480x640 (no detections), 299.8ms
Speed: 1.1ms preprocess, 299.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOgMx9oMX7rYN20zjqNy2Q_270.JPG: 480x640 (no detections), 298.0ms
Speed: 1.1ms preprocess, 298.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOgO8IYS57XbLseju_PWtw_0.JPG: 480x640 (no detections), 297.8ms
Speed: 1.2ms preprocess, 297.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOgO8IYS57XbLseju_PWtw_90.JPG: 480x640 (no detections), 298.1ms
Speed: 1.3ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOgO8IYS57XbLseju_PWtw_180.JPG: 480x640 (no detections), 298.6ms
Speed: 1.2ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOgO8IYS57XbLseju_PWtw_270.JPG: 480x640 1 Waste, 304.6ms
Speed: 1.1ms preprocess, 304.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOhsSvjU4v9AglzKFv-SBQ_0.JPG: 480x640 (no detections), 305.4ms
Speed: 1.5ms preprocess, 305.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOhsSvjU4v9AglzKFv-SBQ_90.JPG: 480x640 (no detections), 300.5ms
Speed: 1.4ms preprocess, 300.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOhsSvjU4v9AglzKFv-SBQ_180.JPG: 480x640 (no detections), 298.7ms
Speed: 1.3ms preprocess, 298.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOhsSvjU4v9AglzKFv-SBQ_270.JPG: 480x640 (no detections), 299.7ms
Speed: 1.2ms preprocess, 299.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOmq7wNkaU_w6c1FHUjDNA_0.JPG: 480x640 (no detections), 303.3ms
Speed: 1.1ms preprocess, 303.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOmq7wNkaU_w6c1FHUjDNA_90.JPG: 480x640 (no detections), 303.1ms
Speed: 1.3ms preprocess, 303.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOmq7wNkaU_w6c1FHUjDNA_180.JPG: 480x640 (no detections), 304.1ms
Speed: 1.4ms preprocess, 304.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOmq7wNkaU_w6c1FHUjDNA_270.JPG: 480x640 (no detections), 297.3ms
Speed: 1.1ms preprocess, 297.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOnMXNb3y7H4cGMSpwuGtQ_0.JPG: 480x640 (no detections), 299.0ms
Speed: 1.2ms preprocess, 299.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOnMXNb3y7H4cGMSpwuGtQ_90.JPG: 480x640 (no detections), 302.1ms
Speed: 1.1ms preprocess, 302.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOnMXNb3y7H4cGMSpwuGtQ_180.JPG: 480x640 (no detections), 301.5ms
Speed: 1.3ms preprocess, 301.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOnMXNb3y7H4cGMSpwuGtQ_270.JPG: 480x640 (no detections), 306.7ms
Speed: 1.4ms preprocess, 306.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOnwBW5GLCvgCRWx31NrCg_0.JPG: 480x640 (no detections), 301.7ms
Speed: 1.2ms preprocess, 301.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOnwBW5GLCvgCRWx31NrCg_90.JPG: 480x640 (no detections), 301.0ms
Speed: 1.1ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOnwBW5GLCvgCRWx31NrCg_180.JPG: 480x640 (no detections), 297.0ms
Speed: 1.5ms preprocess, 297.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOnwBW5GLCvgCRWx31NrCg_270.JPG: 480x640 (no detections), 305.3ms
Speed: 1.1ms preprocess, 305.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOnwTD6jFSQIDflXNjPg0Q_0.JPG: 480x640 (no detections), 298.5ms
Speed: 1.3ms preprocess, 298.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOnwTD6jFSQIDflXNjPg0Q_90.JPG: 480x640 (no detections), 297.5ms

Speed: 1.5ms preprocess, 297.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOnwTD6jFSQIDflXNjPg0Q_180.JPG: 480x640 (no detections), 298.6ms
Speed: 1.2ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOnwTD6jFSQIDflXNjPg0Q_270.JPG: 480x640 (no detections), 304.0ms
Speed: 1.0ms preprocess, 304.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOq6B99R3FMfAHkVjgFsVw_0.JPG: 480x640 (no detections), 302.0ms
Speed: 1.2ms preprocess, 302.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOq6B99R3FMfAHkVjgFsVw_90.JPG: 480x640 (no detections), 302.6ms
Speed: 1.2ms preprocess, 302.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOq6B99R3FMfAHkVjgFsVw_180.JPG: 480x640 (no detections), 303.2ms
Speed: 1.1ms preprocess, 303.2ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOq6B99R3FMfAHkVjgFsVw_270.JPG: 480x640 (no detections), 299.5ms
Speed: 1.1ms preprocess, 299.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOqcuXzrU5KznvX0uy6ZGA_0.JPG: 480x640 (no detections), 300.5ms
Speed: 1.3ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOqcuXzrU5KznvX0uy6ZGA_90.JPG: 480x640 (no detections), 300.2ms
Speed: 1.1ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOqcuXzrU5KznvX0uy6ZGA_180.JPG: 480x640 (no detections), 301.9ms
Speed: 1.2ms preprocess, 301.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOqcuXzrU5KznvX0uy6ZGA_270.JPG: 480x640 (no detections), 296.2ms
Speed: 1.2ms preprocess, 296.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOxYshkkJHsA6LdLoZB0-g_0.JPG: 480x640 (no detections), 302.2ms
Speed: 1.2ms preprocess, 302.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOxYshkkJHsA6LdLoZB0-g_90.JPG: 480x640 (no detections), 300.6ms
Speed: 1.2ms preprocess, 300.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOxYshkkJHsA6LdLoZB0-g_180.JPG: 480x640 (no detections), 296.2ms
Speed: 1.4ms preprocess, 296.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOxYshkkJHsA6LdLoZB0-g_270.JPG: 480x640 (no detections), 298.1ms
Speed: 1.2ms preprocess, 298.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOy-fAhs_HoN9ELgK-HyPg_0.JPG: 480x640 (no detections), 299.7ms
Speed: 1.2ms preprocess, 299.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOy-fAhs_HoN9ELgK-HyPg_90.JPG: 480x640 (no detections), 304.6ms
Speed: 1.1ms preprocess, 304.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOy-fAhs_HoN9ELgK-HyPg_180.JPG: 480x640 (no detections), 298.7ms
Speed: 1.2ms preprocess, 298.7ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOy-fAhs_HoN9ELgK-HyPg_270.JPG: 480x640 (no detections), 303.3ms
Speed: 1.1ms preprocess, 303.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOzIyU4CeR8TJd1GFpgZqw_0.JPG: 480x640 (no detections), 300.5ms
Speed: 1.2ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOzIyU4CeR8TJd1GFpgZqw_90.JPG: 480x640 (no detections), 302.0ms
Speed: 1.9ms preprocess, 302.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOzIyU4CeR8TJd1GFpgZqw_180.JPG: 480x640 (no detections), 296.2ms
Speed: 1.3ms preprocess, 296.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xOzIyU4CeR8TJd1GFpgZqw_270.JPG: 480x640 (no detections), 298.9ms
Speed: 1.8ms preprocess, 298.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xP06eXg4PFljDD7sm7os4g_0.JPG: 480x640 (no detections), 298.7ms
Speed: 1.2ms preprocess, 298.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xP06eXg4PFljDD7sm7os4g_90.JPG: 480x640 (no detections), 306.2ms
Speed: 1.0ms preprocess, 306.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xP06eXg4PFljDD7sm7os4g_180.JPG: 480x640 (no detections), 300.9ms
Speed: 1.1ms preprocess, 300.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xP06eXg4PFljDD7sm7os4g_270.JPG: 480x640 (no detections), 304.6ms
Speed: 1.3ms preprocess, 304.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xP29BDyz-uWaAqgbAucwew_0.JPG: 480x640 (no detections), 297.0ms
Speed: 1.2ms preprocess, 297.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xP29BDyz-uWaAqgbAucwew_90.JPG: 480x640 (no detections), 296.3ms
Speed: 1.1ms preprocess, 296.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xP29BDyz-uWaAqgbAucwew_180.JPG: 480x640 (no detections), 300.2ms
Speed: 1.2ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xP29BDyz-uWaAqgbAucwew_270.JPG: 480x640 (no detections), 297.4ms
Speed: 1.1ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xP2ZXP-aXni0OG4apBP2Ag_0.JPG: 480x640 (no detections), 306.4ms
Speed: 1.2ms preprocess, 306.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xP2ZXP-aXni0OG4apBP2Ag_90.JPG: 480x640 (no detections), 297.1ms
Speed: 1.3ms preprocess, 297.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xP2ZXP-aXni0OG4apBP2Ag_180.JPG: 480x640 (no detections), 299.5ms
Speed: 1.2ms preprocess, 299.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xP2ZXP-aXni0OG4apBP2Ag_270.JPG: 480x640 (no detections), 298.7ms
Speed: 1.1ms preprocess, 298.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xP6xajIjrypbvsVeWOa2bQ_0.JPG: 480x640 (no detections), 297.0ms
Speed: 1.1ms preprocess, 297.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xP6xajIjrypbvsVeWOa2bQ_90.JPG: 480x640 (no detections), 303.9ms
Speed: 1.0ms preprocess, 303.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xP6xajIjrypbvsVeWOa2bQ_180.JPG: 480x640 (no detections), 302.8ms
Speed: 1.2ms preprocess, 302.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xP6xajIjrypbvsVeWOa2bQ_270.JPG: 480x640 (no detections), 301.2ms
Speed: 1.4ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xP9FwI3akEIXSDFgy5qe3g_0.JPG: 480x640 1 Waste, 320.9ms
Speed: 1.8ms preprocess, 320.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xP9FwI3akEIXSDFgy5qe3g_90.JPG: 480x640 (no detections), 291.9ms
Speed: 1.2ms preprocess, 291.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xP9FwI3akEIXSDFgy5qe3g_180.JPG: 480x640 (no detections), 296.0ms
Speed: 1.2ms preprocess, 296.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xP9FwI3akEIXSDFgy5qe3g_270.JPG: 480x640 (no detections), 304.1ms
Speed: 1.2ms preprocess, 304.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xP9GTaNBv-MObkoOlZGMYQ_0.JPG: 480x640 (no detections), 305.8ms
Speed: 1.2ms preprocess, 305.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xP9GTaNBv-MObkoOlZGMYQ_90.JPG: 480x640 (no detections), 300.1ms
Speed: 1.2ms preprocess, 300.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xP9GTaNBv-MObkoOlZGMYQ_180.JPG: 480x640 (no detections), 301.2ms
Speed: 1.1ms preprocess, 301.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xP9GTaNBv-MObkoOlZGMYQ_270.JPG: 480x640 (no detections), 300.7ms
Speed: 1.1ms preprocess, 300.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xP9aPanlxycIy5ofbUnKrg_0.JPG: 480x640 (no detections), 300.4ms
Speed: 1.7ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xP9aPanlxycIy5ofbUnKrg_90.JPG: 480x640 (no detections), 301.3ms
Speed: 1.5ms preprocess, 301.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xP9aPanlxycIy5ofbUnKrg_180.JPG: 480x640 (no detections), 298.1ms
Speed: 1.2ms preprocess, 298.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xP9aPanlxycIy5ofbUnKrg_270.JPG: 480x640 (no detections), 298.1ms
Speed: 1.4ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPAZvJ7A9IKxN0uLeDKodA_0.JPG: 480x640 (no detections), 298.4ms
Speed: 1.2ms preprocess, 298.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPAZvJ7A9IKxN0uLeDKodA_90.JPG: 480x640 (no detections), 300.4ms
Speed: 1.7ms preprocess, 300.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPAZvJ7A9IKxN0uLeDKodA_180.JPG: 480x640 (no detections), 296.9ms
Speed: 1.1ms preprocess, 296.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPAZvJ7A9IKxN0uLeDKodA_270.JPG: 480x640 (no detections), 307.4ms
Speed: 1.3ms preprocess, 307.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPCBRe-Xt8OcXiZGw_pMVg_0.JPG: 480x640 (no detections), 304.7ms
Speed: 1.2ms preprocess, 304.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPCBRe-Xt8OcXiZGw_pMVg_90.JPG: 480x640 (no detections), 299.5ms
Speed: 1.2ms preprocess, 299.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPCBRe-Xt8OcXiZGw_pMVg_180.JPG: 480x640 (no detections), 301.5ms
Speed: 1.1ms preprocess, 301.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPCBRe-Xt8OcXiZGw_pMVg_270.JPG: 480x640 (no detections), 300.1ms
Speed: 1.2ms preprocess, 300.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPHWmA1gmVgjggH5RYdeDg_0.JPG: 480x640 (no detections), 303.5ms
Speed: 1.2ms preprocess, 303.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPHWmA1gmVgjggH5RYdeDg_90.JPG: 480x640 (no detections), 301.5ms
Speed: 1.2ms preprocess, 301.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPHWmA1gmVgjggH5RYdeDg_180.JPG: 480x640 (no detections), 297.1ms
Speed: 1.3ms preprocess, 297.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPHWmA1gmVgjggH5RYdeDg_270.JPG: 480x640 (no detections), 300.1ms
Speed: 1.4ms preprocess, 300.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPJKFADQ5XG7Iak5XiF-9g_0.JPG: 480x640 (no detections), 299.7ms
Speed: 1.1ms preprocess, 299.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPJKFADQ5XG7Iak5XiF-9g_90.JPG: 480x640 (no detections), 301.7ms
Speed: 1.4ms preprocess, 301.7ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPJKFADQ5XG7Iak5XiF-9g_180.JPG: 480x640 (no detections), 293.3ms
Speed: 1.3ms preprocess, 293.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPJKFADQ5XG7Iak5XiF-9g_270.JPG: 480x640 (no detections), 295.5ms
Speed: 1.2ms preprocess, 295.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPMSx6CcH20eknnYTTjN6w_0.JPG: 480x640 (no detections), 300.1ms

Speed: 1.9ms preprocess, 300.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPMSx6CcH20eknnYTTjN6w_90.JPG: 480x640 (no detections), 301.3ms
Speed: 1.2ms preprocess, 301.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPMSx6CcH20eknnYTTjN6w_180.JPG: 480x640 (no detections), 303.8ms
Speed: 1.1ms preprocess, 303.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPMSx6CcH20eknnYTTjN6w_270.JPG: 480x640 (no detections), 298.6ms
Speed: 1.4ms preprocess, 298.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPQAUJ_B1LgMuorCBDUofQ_0.JPG: 480x640 (no detections), 295.4ms
Speed: 1.2ms preprocess, 295.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPQAUJ_B1LgMuorCBDUofQ_90.JPG: 480x640 (no detections), 295.7ms
Speed: 1.1ms preprocess, 295.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPQAUJ_B1LgMuorCBDUofQ_180.JPG: 480x640 (no detections), 303.9ms
Speed: 1.2ms preprocess, 303.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPQAUJ_B1LgMuorCBDUofQ_270.JPG: 480x640 (no detections), 302.9ms
Speed: 1.4ms preprocess, 302.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPRLtBf5XSIFVBTQg5Sv4w_0.JPG: 480x640 (no detections), 300.9ms
Speed: 1.2ms preprocess, 300.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPRLtBf5XSIFVBTQg5Sv4w_90.JPG: 480x640 (no detections), 301.0ms
Speed: 1.1ms preprocess, 301.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPRLtBf5XSIFVBTQg5Sv4w_180.JPG: 480x640 (no detections), 304.1ms
Speed: 1.2ms preprocess, 304.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPRLtBf5XSIFVBTQg5Sv4w_270.JPG: 480x640 (no detections), 302.1ms
Speed: 1.2ms preprocess, 302.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPS1Sj1XXM9_9gzkfabj8A_0.JPG: 480x640 (no detections), 304.9ms
Speed: 1.3ms preprocess, 304.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPS1Sj1XXM9_9gzkfabj8A_90.JPG: 480x640 (no detections), 301.8ms
Speed: 1.1ms preprocess, 301.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPS1Sj1XXM9_9gzkfabj8A_180.JPG: 480x640 (no detections), 303.4ms
Speed: 1.3ms preprocess, 303.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPS1Sj1XXM9_9gzkfabj8A_270.JPG: 480x640 (no detections), 307.2ms
Speed: 1.2ms preprocess, 307.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPTCETlCZ9lZ5X0YUBFBdw_0.JPG: 480x640 (no detections), 305.1ms
Speed: 1.1ms preprocess, 305.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPTCETlCZ9lZ5X0YUBFBdw_90.JPG: 480x640 (no detections), 305.1ms
Speed: 1.2ms preprocess, 305.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPTCETlCZ9lZ5X0YUBFBdw_180.JPG: 480x640 (no detections), 294.9ms
Speed: 1.1ms preprocess, 294.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPTCETlCZ9lZ5X0YUBFBdw_270.JPG: 480x640 (no detections), 311.0ms
Speed: 1.1ms preprocess, 311.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPWDpKXsy-AbvK7uxhQZLQ_0.JPG: 480x640 (no detections), 304.7ms
Speed: 1.1ms preprocess, 304.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPWDpKXsy-AbvK7uxhQZLQ_90.JPG: 480x640 (no detections), 312.6ms
Speed: 1.1ms preprocess, 312.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPWDpKXsy-AbvK7uxhQZLQ_180.JPG: 480x640 (no detections), 299.3ms
Speed: 1.2ms preprocess, 299.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPWDpKXsy-AbvK7uxhQZLQ_270.JPG: 480x640 1 Waste, 300.1ms
Speed: 1.3ms preprocess, 300.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPYQ1TxixeK6bJ9QUriWuw_0.JPG: 480x640 (no detections), 299.1ms
Speed: 1.3ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPYQ1TxixeK6bJ9QUriWuw_90.JPG: 480x640 (no detections), 297.8ms
Speed: 1.3ms preprocess, 297.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPYQ1TxixeK6bJ9QUriWuw_180.JPG: 480x640 (no detections), 300.0ms
Speed: 1.2ms preprocess, 300.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPYQ1TxixeK6bJ9QUriWuw_270.JPG: 480x640 (no detections), 302.6ms
Speed: 1.2ms preprocess, 302.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xP_WYXTbp4ayK1hegBE3xQ_0.JPG: 480x640 (no detections), 300.0ms
Speed: 1.2ms preprocess, 300.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xP_WYXTbp4ayK1hegBE3xQ_90.JPG: 480x640 (no detections), 306.4ms
Speed: 1.2ms preprocess, 306.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xP_WYXTbp4ayK1hegBE3xQ_180.JPG: 480x640 (no detections), 309.4ms
Speed: 1.0ms preprocess, 309.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xP_WYXTbp4ayK1hegBE3xQ_270.JPG: 480x640 (no detections), 305.5ms
Speed: 1.5ms preprocess, 305.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPeBM6Tt-FmzNT8UTorDqw_0.JPG: 480x640 (no detections), 303.1ms
Speed: 1.2ms preprocess, 303.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPeBM6Tt-FmzNT8UTorDqw_90.JPG: 480x640 (no detections), 296.0ms
Speed: 1.2ms preprocess, 296.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPeBM6Tt-FmzNT8UTorDqw_180.JPG: 480x640 (no detections), 299.5ms
Speed: 1.1ms preprocess, 299.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPeBM6Tt-FmzNT8UTorDqw_270.JPG: 480x640 (no detections), 306.2ms
Speed: 1.7ms preprocess, 306.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPiTMuV7JrJ3PS86CWQ6ow_0.JPG: 480x640 (no detections), 299.5ms
Speed: 1.1ms preprocess, 299.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPiTMuV7JrJ3PS86CWQ6ow_90.JPG: 480x640 (no detections), 302.6ms
Speed: 1.1ms preprocess, 302.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPiTMuV7JrJ3PS86CWQ6ow_180.JPG: 480x640 (no detections), 300.1ms
Speed: 1.2ms preprocess, 300.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPiTMuV7JrJ3PS86CWQ6ow_270.JPG: 480x640 (no detections), 305.6ms
Speed: 1.1ms preprocess, 305.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPjBg5ZT6bm6Bbqxrpdv5w_0.JPG: 480x640 (no detections), 300.8ms
Speed: 1.8ms preprocess, 300.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPjBg5ZT6bm6Bbqxrpdv5w_90.JPG: 480x640 (no detections), 304.1ms
Speed: 1.2ms preprocess, 304.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPjBg5ZT6bm6Bbqxrpdv5w_180.JPG: 480x640 (no detections), 300.2ms
Speed: 1.1ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPjBg5ZT6bm6Bbqxrpdv5w_270.JPG: 480x640 (no detections), 297.7ms
Speed: 1.2ms preprocess, 297.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPkI--SfEQpPXU6RsNnNSA_0.JPG: 480x640 (no detections), 307.3ms
Speed: 1.3ms preprocess, 307.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPkI--SfEQpPXU6RsNnNSA_90.JPG: 480x640 (no detections), 299.4ms
Speed: 1.2ms preprocess, 299.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPkI--SfEQpPXU6RsNnNSA_180.JPG: 480x640 (no detections), 299.6ms
Speed: 1.1ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPkI--SfEQpPXU6RsNnNSA_270.JPG: 480x640 (no detections), 300.5ms
Speed: 1.1ms preprocess, 300.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPkRayZ_c4hTspC45IqtjA_0.JPG: 480x640 (no detections), 301.6ms
Speed: 1.2ms preprocess, 301.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPkRayZ_c4hTspC45IqtjA_90.JPG: 480x640 (no detections), 302.1ms
Speed: 1.2ms preprocess, 302.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPkRayZ_c4hTspC45IqtjA_180.JPG: 480x640 (no detections), 298.6ms
Speed: 1.4ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPkRayZ_c4hTspC45IqtjA_270.JPG: 480x640 (no detections), 300.0ms
Speed: 1.2ms preprocess, 300.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPl0kqy6p9F6u1KZ6DbDHg_0.JPG: 480x640 1 Waste, 300.3ms
Speed: 1.2ms preprocess, 300.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPl0kqy6p9F6u1KZ6DbDHg_90.JPG: 480x640 1 Waste, 303.6ms
Speed: 1.2ms preprocess, 303.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPl0kqy6p9F6u1KZ6DbDHg_180.JPG: 480x640 (no detections), 293.5ms
Speed: 1.1ms preprocess, 293.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPl0kqy6p9F6u1KZ6DbDHg_270.JPG: 480x640 1 Waste, 304.0ms
Speed: 1.0ms preprocess, 304.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPmPLHEIQeMKGiLYS3HWtQ_0.JPG: 480x640 (no detections), 301.2ms
Speed: 1.1ms preprocess, 301.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPmPLHEIQeMKGiLYS3HWtQ_90.JPG: 480x640 (no detections), 295.7ms
Speed: 1.7ms preprocess, 295.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPmPLHEIQeMKGiLYS3HWtQ_180.JPG: 480x640 (no detections), 299.4ms
Speed: 1.5ms preprocess, 299.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPmPLHEIQeMKGiLYS3HWtQ_270.JPG: 480x640 (no detections), 300.6ms
Speed: 1.3ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPmoSgSq6uDz9w9ihIdtXw_0.JPG: 480x640 (no detections), 303.8ms
Speed: 1.3ms preprocess, 303.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPmoSgSq6uDz9w9ihIdtXw_90.JPG: 480x640 (no detections), 300.6ms
Speed: 1.4ms preprocess, 300.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPmoSgSq6uDz9w9ihIdtXw_180.JPG: 480x640 (no detections), 299.7ms
Speed: 1.2ms preprocess, 299.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPmoSgSq6uDz9w9ihIdtXw_270.JPG: 480x640 (no detections), 297.9ms
Speed: 1.1ms preprocess, 297.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPnRs69ht61v4YwaMoRaig_0.JPG: 480x640 (no detections), 299.6ms
Speed: 1.1ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPnRs69ht61v4YwaMoRaig_90.JPG: 480x640 (no detections), 300.8ms
Speed: 1.3ms preprocess, 300.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPnRs69ht61v4YwaMoRaig_180.JPG: 480x640 (no detections), 300.6ms
Speed: 1.1ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPnRs69ht61v4YwaMoRaig_270.JPG: 480x640 (no detections), 302.8ms

Speed: 1.1ms preprocess, 302.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPnrNUvlpci269Ofrsc79g_0.JPG: 480x640 (no detections), 298.9ms
Speed: 1.3ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPnrNUvlpci269Ofrsc79g_90.JPG: 480x640 (no detections), 300.7ms
Speed: 1.3ms preprocess, 300.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPnrNUvlpci269Ofrsc79g_180.JPG: 480x640 (no detections), 298.9ms
Speed: 1.3ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPnrNUvlpci269Ofrsc79g_270.JPG: 480x640 (no detections), 298.1ms
Speed: 1.1ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPnvhyuZ8XYQXUWi9l_B0w_0.JPG: 480x640 (no detections), 297.3ms
Speed: 1.0ms preprocess, 297.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPnvhyuZ8XYQXUWi9l_B0w_90.JPG: 480x640 (no detections), 297.4ms
Speed: 1.2ms preprocess, 297.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPnvhyuZ8XYQXUWi9l_B0w_180.JPG: 480x640 (no detections), 297.7ms
Speed: 1.2ms preprocess, 297.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPnvhyuZ8XYQXUWi9l_B0w_270.JPG: 480x640 (no detections), 302.1ms
Speed: 1.3ms preprocess, 302.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPvbJM28qbvo8H-qESLSRg_0.JPG: 480x640 (no detections), 297.8ms
Speed: 1.2ms preprocess, 297.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPvbJM28qbvo8H-qESLSRg_90.JPG: 480x640 (no detections), 297.3ms
Speed: 1.5ms preprocess, 297.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPvbJM28qbvo8H-qESLSRg_180.JPG: 480x640 (no detections), 297.3ms
Speed: 1.2ms preprocess, 297.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPvbJM28qbvo8H-qESLSRg_270.JPG: 480x640 (no detections), 305.7ms
Speed: 1.2ms preprocess, 305.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPvoMdHQd5c_VBdF8x_IpA_0.JPG: 480x640 (no detections), 299.8ms
Speed: 1.1ms preprocess, 299.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPvoMdHQd5c_VBdF8x_IpA_90.JPG: 480x640 (no detections), 297.4ms
Speed: 1.3ms preprocess, 297.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPvoMdHQd5c_VBdF8x_IpA_180.JPG: 480x640 (no detections), 301.7ms
Speed: 1.2ms preprocess, 301.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPvoMdHQd5c_VBdF8x_IpA_270.JPG: 480x640 (no detections), 300.4ms
Speed: 1.3ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPvyeNaVV5BPitNbEy-4zQ_0.JPG: 480x640 (no detections), 297.3ms
Speed: 1.3ms preprocess, 297.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPvyeNaVV5BPitNbEy-4zQ_90.JPG: 480x640 (no detections), 299.7ms
Speed: 1.1ms preprocess, 299.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPvyeNaVV5BPitNbEy-4zQ_180.JPG: 480x640 (no detections), 302.7ms
Speed: 1.8ms preprocess, 302.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPvyeNaVV5BPitNbEy-4zQ_270.JPG: 480x640 (no detections), 322.3ms
Speed: 1.6ms preprocess, 322.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPxkoquO6WZcSt9kAZ2uJA_0.JPG: 480x640 (no detections), 321.2ms
Speed: 1.1ms preprocess, 321.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPxkoquO6WZcSt9kAZ2uJA_90.JPG: 480x640 (no detections), 316.9ms
Speed: 1.3ms preprocess, 316.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPxkoquO6WZcSt9kAZ2uJA_180.JPG: 480x640 (no detections), 309.2ms
Speed: 1.8ms preprocess, 309.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPxkoquO6WZcSt9kAZ2uJA_270.JPG: 480x640 (no detections), 300.2ms
Speed: 1.2ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPy-jm2hvCFQyI7CQsF7nQ_0.JPG: 480x640 (no detections), 303.3ms
Speed: 1.3ms preprocess, 303.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPy-jm2hvCFQyI7CQsF7nQ_90.JPG: 480x640 (no detections), 306.1ms
Speed: 1.2ms preprocess, 306.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPy-jm2hvCFQyI7CQsF7nQ_180.JPG: 480x640 (no detections), 311.6ms
Speed: 1.6ms preprocess, 311.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPy-jm2hvCFQyI7CQsF7nQ_270.JPG: 480x640 (no detections), 297.5ms
Speed: 1.1ms preprocess, 297.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPz1ym4rKsSRI_X0KlNA4A_0.JPG: 480x640 (no detections), 297.9ms
Speed: 1.2ms preprocess, 297.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPz1ym4rKsSRI_X0KlNA4A_90.JPG: 480x640 (no detections), 299.6ms
Speed: 1.2ms preprocess, 299.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPz1ym4rKsSRI_X0KlNA4A_180.JPG: 480x640 (no detections), 299.4ms
Speed: 1.1ms preprocess, 299.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xPz1ym4rKsSRI_X0KlNA4A_270.JPG: 480x640 (no detections), 296.2ms
Speed: 1.2ms preprocess, 296.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQ1aAhmf3uSfqMHsXLfnYA_0.JPG: 480x640 (no detections), 298.9ms
Speed: 1.4ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQ1aAhmf3uSfqMHsXLfnYA_90.JPG: 480x640 (no detections), 299.5ms
Speed: 1.3ms preprocess, 299.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQ1aAhmf3uSfqMHsXLfnYA_180.JPG: 480x640 (no detections), 302.9ms
Speed: 1.2ms preprocess, 302.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQ1aAhmf3uSfqMHsXLfnYA_270.JPG: 480x640 (no detections), 302.2ms
Speed: 1.1ms preprocess, 302.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQ5_XP-vLNv6NmcjF9zNnA_0.JPG: 480x640 1 Waste, 295.6ms
Speed: 1.3ms preprocess, 295.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQ5_XP-vLNv6NmcjF9zNnA_90.JPG: 480x640 (no detections), 300.4ms
Speed: 1.3ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQ5_XP-vLNv6NmcjF9zNnA_180.JPG: 480x640 (no detections), 304.1ms
Speed: 1.2ms preprocess, 304.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQ5_XP-vLNv6NmcjF9zNnA_270.JPG: 480x640 2 Wastes, 301.0ms
Speed: 1.6ms preprocess, 301.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQ6ehkD61aC0xwoEJRGxGw_0.JPG: 480x640 (no detections), 300.7ms
Speed: 1.4ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQ6ehkD61aC0xwoEJRGxGw_90.JPG: 480x640 (no detections), 299.4ms
Speed: 1.1ms preprocess, 299.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQ6ehkD61aC0xwoEJRGxGw_180.JPG: 480x640 (no detections), 296.5ms
Speed: 1.2ms preprocess, 296.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQ6ehkD61aC0xwoEJRGxGw_270.JPG: 480x640 (no detections), 298.0ms
Speed: 1.2ms preprocess, 298.0ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQ729LzXSzO8TxM-y559Ng_0.JPG: 480x640 (no detections), 296.7ms
Speed: 1.1ms preprocess, 296.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQ729LzXSzO8TxM-y559Ng_90.JPG: 480x640 (no detections), 299.1ms
Speed: 1.4ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQ729LzXSzO8TxM-y559Ng_180.JPG: 480x640 (no detections), 295.6ms
Speed: 1.3ms preprocess, 295.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQ729LzXSzO8TxM-y559Ng_270.JPG: 480x640 (no detections), 298.3ms
Speed: 1.2ms preprocess, 298.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQBOnbvlUh0tftBHiE3NEA_0.JPG: 480x640 (no detections), 377.9ms
Speed: 1.2ms preprocess, 377.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQBOnbvlUh0tftBHiE3NEA_90.JPG: 480x640 (no detections), 307.2ms
Speed: 1.4ms preprocess, 307.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQBOnbvlUh0tftBHiE3NEA_180.JPG: 480x640 (no detections), 302.4ms
Speed: 1.1ms preprocess, 302.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQBOnbvlUh0tftBHiE3NEA_270.JPG: 480x640 (no detections), 307.8ms
Speed: 1.2ms preprocess, 307.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQBjlYEh1P_XnOnVoIYf5Q_0.JPG: 480x640 (no detections), 300.5ms
Speed: 1.2ms preprocess, 300.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQBjlYEh1P_XnOnVoIYf5Q_90.JPG: 480x640 (no detections), 296.8ms
Speed: 1.1ms preprocess, 296.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQBjlYEh1P_XnOnVoIYf5Q_180.JPG: 480x640 (no detections), 297.6ms
Speed: 1.3ms preprocess, 297.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQBjlYEh1P_XnOnVoIYf5Q_270.JPG: 480x640 (no detections), 296.6ms
Speed: 1.1ms preprocess, 296.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQFLExau_7lNsKfMRSm0Ig_0.JPG: 480x640 (no detections), 300.0ms
Speed: 1.2ms preprocess, 300.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQFLExau_7lNsKfMRSm0Ig_90.JPG: 480x640 (no detections), 298.9ms
Speed: 1.2ms preprocess, 298.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQFLExau_7lNsKfMRSm0Ig_180.JPG: 480x640 (no detections), 299.0ms
Speed: 1.2ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQFLExau_7lNsKfMRSm0Ig_270.JPG: 480x640 (no detections), 302.3ms
Speed: 1.4ms preprocess, 302.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQG_kbZ2m64F6arYwC-Alg_0.JPG: 480x640 (no detections), 296.8ms
Speed: 1.2ms preprocess, 296.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQG_kbZ2m64F6arYwC-Alg_90.JPG: 480x640 (no detections), 298.6ms
Speed: 1.1ms preprocess, 298.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQG_kbZ2m64F6arYwC-Alg_180.JPG: 480x640 (no detections), 296.6ms
Speed: 1.1ms preprocess, 296.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQG_kbZ2m64F6arYwC-Alg_270.JPG: 480x640 (no detections), 303.4ms
Speed: 1.2ms preprocess, 303.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQH7FIOxQowuwFTnrTvPZA_0.JPG: 480x640 (no detections), 300.3ms
Speed: 1.2ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQH7FIOxQowuwFTnrTvPZA_90.JPG: 480x640 (no detections), 300.5ms
Speed: 1.3ms preprocess, 300.5ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQH7FIOxQowuwFTnrTvPZA_180.JPG: 480x640 (no detections), 300.9ms

Speed: 1.1ms preprocess, 300.9ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQH7FIOxQowuwFTnrTvPZA_270.JPG: 480x640 (no detections), 308.5ms
Speed: 1.3ms preprocess, 308.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQNXPDXOuYw0drjKkSPjoA_0.JPG: 480x640 (no detections), 305.4ms
Speed: 1.1ms preprocess, 305.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQNXPDXOuYw0drjKkSPjoA_90.JPG: 480x640 (no detections), 308.1ms
Speed: 1.2ms preprocess, 308.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQNXPDXOuYw0drjKkSPjoA_180.JPG: 480x640 3 Wastes, 303.5ms
Speed: 1.6ms preprocess, 303.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQNXPDXOuYw0drjKkSPjoA_270.JPG: 480x640 (no detections), 298.6ms
Speed: 1.1ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQP9xUBDyxqgh7jYz0Z_PQ_0.JPG: 480x640 (no detections), 299.7ms
Speed: 1.1ms preprocess, 299.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQP9xUBDyxqgh7jYz0Z_PQ_90.JPG: 480x640 (no detections), 307.6ms
Speed: 1.2ms preprocess, 307.6ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQP9xUBDyxqgh7jYz0Z_PQ_180.JPG: 480x640 (no detections), 302.8ms
Speed: 1.2ms preprocess, 302.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQP9xUBDyxqgh7jYz0Z_PQ_270.JPG: 480x640 (no detections), 300.1ms
Speed: 1.2ms preprocess, 300.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQUM_bjNlIxvLBjSDHpv3g_0.JPG: 480x640 1 Waste, 302.1ms
Speed: 1.5ms preprocess, 302.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQUM_bjNlIxvLBjSDHpv3g_90.JPG: 480x640 (no detections), 305.3ms
Speed: 1.2ms preprocess, 305.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQUM_bjNlIxvLBjSDHpv3g_180.JPG: 480x640 (no detections), 301.5ms
Speed: 1.3ms preprocess, 301.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQUM_bjNlIxvLBjSDHpv3g_270.JPG: 480x640 (no detections), 294.5ms
Speed: 1.2ms preprocess, 294.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQUxw7eoH9x88gViLiiLGQ_0.JPG: 480x640 (no detections), 296.7ms
Speed: 1.2ms preprocess, 296.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQUxw7eoH9x88gViLiiLGQ_90.JPG: 480x640 (no detections), 296.8ms
Speed: 1.1ms preprocess, 296.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQUxw7eoH9x88gViLiiLGQ_180.JPG: 480x640 (no detections), 301.4ms
Speed: 1.3ms preprocess, 301.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQUxw7eoH9x88gViLiiLGQ_270.JPG: 480x640 (no detections), 298.4ms
Speed: 1.1ms preprocess, 298.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQ_1u1amcWyYvmkh7O20gw_0.JPG: 480x640 (no detections), 299.0ms
Speed: 1.3ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQ_1u1amcWyYvmkh7O20gw_90.JPG: 480x640 (no detections), 304.4ms
Speed: 1.3ms preprocess, 304.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQ_1u1amcWyYvmkh7O20gw_180.JPG: 480x640 (no detections), 300.6ms
Speed: 1.2ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQ_1u1amcWyYvmkh7O20gw_270.JPG: 480x640 (no detections), 300.6ms
Speed: 1.2ms preprocess, 300.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQg2YPoWnT1YKYWDBQnkxw_0.JPG: 480x640 1 Waste, 302.1ms
Speed: 1.2ms preprocess, 302.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQg2YPoWnT1YKYWDBQnkxw_90.JPG: 480x640 1 Waste, 304.9ms
Speed: 1.2ms preprocess, 304.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQg2YPoWnT1YKYWDBQnkxw_180.JPG: 480x640 (no detections), 300.4ms
Speed: 1.2ms preprocess, 300.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQg2YPoWnT1YKYWDBQnkxw_270.JPG: 480x640 (no detections), 305.5ms
Speed: 1.1ms preprocess, 305.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQhB5JThS8x9cb__x-beFA_0.JPG: 480x640 (no detections), 296.3ms
Speed: 1.1ms preprocess, 296.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQhB5JThS8x9cb__x-beFA_90.JPG: 480x640 (no detections), 306.2ms
Speed: 1.3ms preprocess, 306.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQhB5JThS8x9cb__x-beFA_180.JPG: 480x640 (no detections), 300.7ms
Speed: 1.2ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQhB5JThS8x9cb__x-beFA_270.JPG: 480x640 (no detections), 311.7ms
Speed: 1.1ms preprocess, 311.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQhgK-OJ7yQ4JlpXXVbdog_0.JPG: 480x640 (no detections), 304.9ms
Speed: 1.2ms preprocess, 304.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQhgK-OJ7yQ4JlpXXVbdog_90.JPG: 480x640 (no detections), 300.8ms
Speed: 1.3ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQhgK-OJ7yQ4JlpXXVbdog_180.JPG: 480x640 (no detections), 300.9ms
Speed: 1.1ms preprocess, 300.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQhgK-OJ7yQ4JlpXXVbdog_270.JPG: 480x640 (no detections), 304.2ms
Speed: 1.3ms preprocess, 304.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQnn8MInmcrVcZuZYFXf2w_0.JPG: 480x640 (no detections), 305.0ms
Speed: 1.2ms preprocess, 305.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQnn8MInmcrVcZuZYFXf2w_90.JPG: 480x640 (no detections), 295.5ms
Speed: 1.4ms preprocess, 295.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQnn8MInmcrVcZuZYFXf2w_180.JPG: 480x640 (no detections), 299.0ms
Speed: 1.1ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQnn8MInmcrVcZuZYFXf2w_270.JPG: 480x640 1 Waste, 301.9ms
Speed: 1.2ms preprocess, 301.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQvXI1XLquUY8Q5edG6duQ_0.JPG: 480x640 (no detections), 300.4ms
Speed: 1.8ms preprocess, 300.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQvXI1XLquUY8Q5edG6duQ_90.JPG: 480x640 (no detections), 302.6ms
Speed: 1.3ms preprocess, 302.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQvXI1XLquUY8Q5edG6duQ_180.JPG: 480x640 (no detections), 301.1ms
Speed: 1.1ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQvXI1XLquUY8Q5edG6duQ_270.JPG: 480x640 (no detections), 302.2ms
Speed: 1.0ms preprocess, 302.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQwNBF2rz9gYnpm8HLwLkg_0.JPG: 480x640 (no detections), 309.5ms
Speed: 1.3ms preprocess, 309.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQwNBF2rz9gYnpm8HLwLkg_90.JPG: 480x640 (no detections), 297.9ms
Speed: 1.3ms preprocess, 297.9ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQwNBF2rz9gYnpm8HLwLkg_180.JPG: 480x640 (no detections), 298.6ms
Speed: 1.5ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQwNBF2rz9gYnpm8HLwLkg_270.JPG: 480x640 (no detections), 302.8ms
Speed: 1.2ms preprocess, 302.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQwy_HJS3t-bWO4NapSJrg_0.JPG: 480x640 (no detections), 301.1ms
Speed: 1.2ms preprocess, 301.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQwy_HJS3t-bWO4NapSJrg_90.JPG: 480x640 (no detections), 300.5ms
Speed: 1.3ms preprocess, 300.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQwy_HJS3t-bWO4NapSJrg_180.JPG: 480x640 1 Waste, 298.6ms
Speed: 1.2ms preprocess, 298.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQwy_HJS3t-bWO4NapSJrg_270.JPG: 480x640 (no detections), 298.2ms
Speed: 1.0ms preprocess, 298.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQze6y7og1Iw9HqJUNk8BQ_0.JPG: 480x640 (no detections), 302.7ms
Speed: 1.0ms preprocess, 302.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQze6y7og1Iw9HqJUNk8BQ_90.JPG: 480x640 (no detections), 299.4ms
Speed: 1.3ms preprocess, 299.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQze6y7og1Iw9HqJUNk8BQ_180.JPG: 480x640 (no detections), 301.5ms
Speed: 1.3ms preprocess, 301.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xQze6y7og1Iw9HqJUNk8BQ_270.JPG: 480x640 (no detections), 300.9ms
Speed: 1.3ms preprocess, 300.9ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xR2p37bhuvtJgyqyB0y4Kg_0.JPG: 480x640 (no detections), 301.0ms
Speed: 1.2ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xR2p37bhuvtJgyqyB0y4Kg_90.JPG: 480x640 (no detections), 301.3ms
Speed: 1.2ms preprocess, 301.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xR2p37bhuvtJgyqyB0y4Kg_180.JPG: 480x640 (no detections), 307.7ms
Speed: 1.1ms preprocess, 307.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xR2p37bhuvtJgyqyB0y4Kg_270.JPG: 480x640 (no detections), 296.2ms
Speed: 1.3ms preprocess, 296.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xR4ttBPUacGwFDfyBfsIxw_0.JPG: 480x640 (no detections), 302.3ms
Speed: 1.1ms preprocess, 302.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xR4ttBPUacGwFDfyBfsIxw_90.JPG: 480x640 (no detections), 297.5ms
Speed: 1.1ms preprocess, 297.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xR4ttBPUacGwFDfyBfsIxw_180.JPG: 480x640 (no detections), 300.7ms
Speed: 1.7ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xR4ttBPUacGwFDfyBfsIxw_270.JPG: 480x640 (no detections), 294.2ms
Speed: 1.1ms preprocess, 294.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xR5-Cbqr8XjeTmivGAA62Q_0.JPG: 480x640 (no detections), 296.7ms
Speed: 1.1ms preprocess, 296.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xR5-Cbqr8XjeTmivGAA62Q_90.JPG: 480x640 (no detections), 301.4ms
Speed: 1.2ms preprocess, 301.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xR5-Cbqr8XjeTmivGAA62Q_180.JPG: 480x640 (no detections), 307.3ms
Speed: 1.4ms preprocess, 307.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xR5-Cbqr8XjeTmivGAA62Q_270.JPG: 480x640 (no detections), 297.7ms
Speed: 1.4ms preprocess, 297.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xR71pDbd_7kJbIJnc_mPlA_0.JPG: 480x640 (no detections), 296.7ms
Speed: 1.2ms preprocess, 296.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xR71pDbd_7kJbIJnc_mPlA_90.JPG: 480x640 (no detections), 303.3ms

Speed: 1.0ms preprocess, 303.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xR71pDbd_7kJbIJnc_mPlA_180.JPG: 480x640 (no detections), 298.0ms
Speed: 1.1ms preprocess, 298.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xR71pDbd_7kJbIJnc_mPlA_270.JPG: 480x640 (no detections), 300.5ms
Speed: 1.3ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xR8YzgmSDT4cNct4T6m9SQ_0.JPG: 480x640 (no detections), 300.4ms
Speed: 1.2ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xR8YzgmSDT4cNct4T6m9SQ_90.JPG: 480x640 (no detections), 295.5ms
Speed: 1.4ms preprocess, 295.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xR8YzgmSDT4cNct4T6m9SQ_180.JPG: 480x640 (no detections), 298.2ms
Speed: 1.6ms preprocess, 298.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xR8YzgmSDT4cNct4T6m9SQ_270.JPG: 480x640 (no detections), 300.7ms
Speed: 1.2ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRB9JNnxPDbSy7vyuAEEYw_0.JPG: 480x640 (no detections), 302.1ms
Speed: 1.1ms preprocess, 302.1ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRB9JNnxPDbSy7vyuAEEYw_90.JPG: 480x640 (no detections), 298.5ms
Speed: 1.1ms preprocess, 298.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRB9JNnxPDbSy7vyuAEEYw_180.JPG: 480x640 (no detections), 298.0ms
Speed: 1.2ms preprocess, 298.0ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRB9JNnxPDbSy7vyuAEEYw_270.JPG: 480x640 (no detections), 305.9ms
Speed: 1.7ms preprocess, 305.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRBfMeniw1S8Ag3zH4M_bw_0.JPG: 480x640 (no detections), 300.8ms
Speed: 1.4ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRBfMeniw1S8Ag3zH4M_bw_90.JPG: 480x640 (no detections), 297.2ms
Speed: 1.1ms preprocess, 297.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRBfMeniw1S8Ag3zH4M_bw_180.JPG: 480x640 (no detections), 295.1ms
Speed: 1.2ms preprocess, 295.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRBfMeniw1S8Ag3zH4M_bw_270.JPG: 480x640 (no detections), 304.4ms
Speed: 1.1ms preprocess, 304.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRD2_5bdEGabSe27Cuyi-w_0.JPG: 480x640 (no detections), 295.5ms
Speed: 1.1ms preprocess, 295.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRD2_5bdEGabSe27Cuyi-w_90.JPG: 480x640 (no detections), 306.8ms
Speed: 1.2ms preprocess, 306.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRD2_5bdEGabSe27Cuyi-w_180.JPG: 480x640 (no detections), 302.3ms
Speed: 1.2ms preprocess, 302.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRD2_5bdEGabSe27Cuyi-w_270.JPG: 480x640 (no detections), 299.2ms
Speed: 1.4ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRDDH1SkL-GfzBcJnVswsg_0.JPG: 480x640 (no detections), 304.0ms
Speed: 1.3ms preprocess, 304.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRDDH1SkL-GfzBcJnVswsg_90.JPG: 480x640 (no detections), 306.6ms
Speed: 1.8ms preprocess, 306.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRDDH1SkL-GfzBcJnVswsg_180.JPG: 480x640 (no detections), 303.9ms
Speed: 1.2ms preprocess, 303.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRDDH1SkL-GfzBcJnVswsg_270.JPG: 480x640 (no detections), 298.9ms
Speed: 1.2ms preprocess, 298.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRDMP4j04iVaTK6cCf1fFQ_0.JPG: 480x640 (no detections), 303.4ms
Speed: 1.1ms preprocess, 303.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRDMP4j04iVaTK6cCf1fFQ_90.JPG: 480x640 (no detections), 293.4ms
Speed: 1.1ms preprocess, 293.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRDMP4j04iVaTK6cCf1fFQ_180.JPG: 480x640 (no detections), 297.2ms
Speed: 1.5ms preprocess, 297.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRDMP4j04iVaTK6cCf1fFQ_270.JPG: 480x640 (no detections), 300.5ms
Speed: 1.2ms preprocess, 300.5ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRE45qrWDYWoJ-th69gPew_0.JPG: 480x640 (no detections), 305.5ms
Speed: 1.3ms preprocess, 305.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRE45qrWDYWoJ-th69gPew_90.JPG: 480x640 (no detections), 297.4ms
Speed: 1.3ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRE45qrWDYWoJ-th69gPew_180.JPG: 480x640 (no detections), 295.1ms
Speed: 1.1ms preprocess, 295.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRE45qrWDYWoJ-th69gPew_270.JPG: 480x640 (no detections), 302.9ms
Speed: 1.3ms preprocess, 302.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRFV43eAlfdgzVUdUVQJkg_0.JPG: 480x640 (no detections), 304.6ms
Speed: 1.1ms preprocess, 304.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRFV43eAlfdgzVUdUVQJkg_90.JPG: 480x640 (no detections), 296.9ms
Speed: 1.6ms preprocess, 296.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRFV43eAlfdgzVUdUVQJkg_180.JPG: 480x640 (no detections), 303.2ms
Speed: 1.1ms preprocess, 303.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRFV43eAlfdgzVUdUVQJkg_270.JPG: 480x640 (no detections), 300.0ms
Speed: 1.1ms preprocess, 300.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRInRw5aXTwwXzOrvYVYVQ_0.JPG: 480x640 (no detections), 299.1ms
Speed: 1.2ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRInRw5aXTwwXzOrvYVYVQ_90.JPG: 480x640 (no detections), 303.5ms
Speed: 1.1ms preprocess, 303.5ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRInRw5aXTwwXzOrvYVYVQ_180.JPG: 480x640 (no detections), 300.5ms
Speed: 1.5ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRInRw5aXTwwXzOrvYVYVQ_270.JPG: 480x640 (no detections), 304.5ms
Speed: 1.4ms preprocess, 304.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRIxRNZwRGcsy03xZ1pU1g_0.JPG: 480x640 (no detections), 299.0ms
Speed: 1.2ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRIxRNZwRGcsy03xZ1pU1g_90.JPG: 480x640 (no detections), 298.3ms
Speed: 1.2ms preprocess, 298.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRIxRNZwRGcsy03xZ1pU1g_180.JPG: 480x640 (no detections), 297.6ms
Speed: 1.1ms preprocess, 297.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRIxRNZwRGcsy03xZ1pU1g_270.JPG: 480x640 (no detections), 298.3ms
Speed: 1.1ms preprocess, 298.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xROzT-ErH9o-lEU_u7wBqA_0.JPG: 480x640 (no detections), 299.6ms
Speed: 1.2ms preprocess, 299.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xROzT-ErH9o-lEU_u7wBqA_90.JPG: 480x640 (no detections), 299.1ms
Speed: 1.0ms preprocess, 299.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xROzT-ErH9o-lEU_u7wBqA_180.JPG: 480x640 (no detections), 302.6ms
Speed: 1.3ms preprocess, 302.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xROzT-ErH9o-lEU_u7wBqA_270.JPG: 480x640 (no detections), 300.6ms
Speed: 1.6ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRRUTfx-tfvk5Mbeb4ELTg_0.JPG: 480x640 (no detections), 300.3ms
Speed: 1.7ms preprocess, 300.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRRUTfx-tfvk5Mbeb4ELTg_90.JPG: 480x640 (no detections), 303.6ms
Speed: 1.4ms preprocess, 303.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRRUTfx-tfvk5Mbeb4ELTg_180.JPG: 480x640 (no detections), 301.3ms
Speed: 1.2ms preprocess, 301.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRRUTfx-tfvk5Mbeb4ELTg_270.JPG: 480x640 (no detections), 306.4ms
Speed: 1.5ms preprocess, 306.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xReF9iCpc1e5-6Pcu1pUPA_0.JPG: 480x640 (no detections), 299.5ms
Speed: 1.4ms preprocess, 299.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xReF9iCpc1e5-6Pcu1pUPA_90.JPG: 480x640 (no detections), 298.0ms
Speed: 1.2ms preprocess, 298.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xReF9iCpc1e5-6Pcu1pUPA_180.JPG: 480x640 (no detections), 298.5ms
Speed: 1.3ms preprocess, 298.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xReF9iCpc1e5-6Pcu1pUPA_270.JPG: 480x640 (no detections), 303.7ms
Speed: 1.2ms preprocess, 303.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRg8vjCF4No6VfdpOLPqHw_0.JPG: 480x640 (no detections), 297.3ms
Speed: 1.2ms preprocess, 297.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRg8vjCF4No6VfdpOLPqHw_90.JPG: 480x640 (no detections), 298.5ms
Speed: 1.1ms preprocess, 298.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRg8vjCF4No6VfdpOLPqHw_180.JPG: 480x640 (no detections), 300.4ms
Speed: 1.1ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRg8vjCF4No6VfdpOLPqHw_270.JPG: 480x640 (no detections), 298.8ms
Speed: 1.0ms preprocess, 298.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRgN-mGOwNyEKTiDWFK1WQ_0.JPG: 480x640 (no detections), 297.4ms
Speed: 1.1ms preprocess, 297.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRgN-mGOwNyEKTiDWFK1WQ_90.JPG: 480x640 (no detections), 299.3ms
Speed: 1.1ms preprocess, 299.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRgN-mGOwNyEKTiDWFK1WQ_180.JPG: 480x640 (no detections), 296.2ms
Speed: 1.1ms preprocess, 296.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRgN-mGOwNyEKTiDWFK1WQ_270.JPG: 480x640 (no detections), 309.2ms
Speed: 1.0ms preprocess, 309.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRjQKKUZMkkrUiVhBPFinQ_0.JPG: 480x640 (no detections), 303.0ms
Speed: 1.5ms preprocess, 303.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRjQKKUZMkkrUiVhBPFinQ_90.JPG: 480x640 (no detections), 300.1ms
Speed: 1.2ms preprocess, 300.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRjQKKUZMkkrUiVhBPFinQ_180.JPG: 480x640 (no detections), 302.0ms
Speed: 1.1ms preprocess, 302.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRjQKKUZMkkrUiVhBPFinQ_270.JPG: 480x640 (no detections), 292.0ms
Speed: 1.2ms preprocess, 292.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRjW8glJFbcqKr8erOsd7A_0.JPG: 480x640 (no detections), 301.7ms

Speed: 1.3ms preprocess, 301.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRjW8glJFbcqKr8erOsd7A_90.JPG: 480x640 (no detections), 299.9ms
Speed: 1.1ms preprocess, 299.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRjW8glJFbcqKr8erOsd7A_180.JPG: 480x640 (no detections), 302.0ms
Speed: 1.2ms preprocess, 302.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRjW8glJFbcqKr8erOsd7A_270.JPG: 480x640 (no detections), 299.0ms
Speed: 1.2ms preprocess, 299.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRjfVFFwxJufjK-gFp5v5w_0.JPG: 480x640 (no detections), 298.9ms
Speed: 1.0ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRjfVFFwxJufjK-gFp5v5w_90.JPG: 480x640 (no detections), 299.7ms
Speed: 1.0ms preprocess, 299.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRjfVFFwxJufjK-gFp5v5w_180.JPG: 480x640 (no detections), 300.8ms
Speed: 1.2ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRjfVFFwxJufjK-gFp5v5w_270.JPG: 480x640 (no detections), 300.5ms
Speed: 1.2ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRk6dTLEoWGeyC750VskNA_0.JPG: 480x640 (no detections), 300.9ms
Speed: 1.1ms preprocess, 300.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRk6dTLEoWGeyC750VskNA_90.JPG: 480x640 (no detections), 310.2ms
Speed: 1.1ms preprocess, 310.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRk6dTLEoWGeyC750VskNA_180.JPG: 480x640 (no detections), 300.0ms
Speed: 1.1ms preprocess, 300.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRk6dTLEoWGeyC750VskNA_270.JPG: 480x640 (no detections), 297.9ms
Speed: 1.3ms preprocess, 297.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRsKiYOcgcO38wwZ5FXSbg_0.JPG: 480x640 (no detections), 299.2ms
Speed: 1.1ms preprocess, 299.2ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRsKiYOcgcO38wwZ5FXSbg_90.JPG: 480x640 (no detections), 303.4ms
Speed: 1.4ms preprocess, 303.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRsKiYOcgcO38wwZ5FXSbg_180.JPG: 480x640 (no detections), 297.0ms
Speed: 1.1ms preprocess, 297.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRsKiYOcgcO38wwZ5FXSbg_270.JPG: 480x640 (no detections), 298.2ms
Speed: 1.2ms preprocess, 298.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRsZt3fQZy_-h4kJVUc6-w_0.JPG: 480x640 (no detections), 299.3ms
Speed: 1.2ms preprocess, 299.3ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRsZt3fQZy_-h4kJVUc6-w_90.JPG: 480x640 (no detections), 299.1ms
Speed: 1.6ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRsZt3fQZy_-h4kJVUc6-w_180.JPG: 480x640 (no detections), 291.8ms
Speed: 1.2ms preprocess, 291.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRsZt3fQZy_-h4kJVUc6-w_270.JPG: 480x640 (no detections), 299.2ms
Speed: 1.4ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRsggMF7uHTuNHBMv-iTyw_0.JPG: 480x640 1 Waste, 296.2ms
Speed: 1.1ms preprocess, 296.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRsggMF7uHTuNHBMv-iTyw_90.JPG: 480x640 (no detections), 294.0ms
Speed: 1.0ms preprocess, 294.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRsggMF7uHTuNHBMv-iTyw_180.JPG: 480x640 (no detections), 300.0ms
Speed: 1.1ms preprocess, 300.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRsggMF7uHTuNHBMv-iTyw_270.JPG: 480x640 (no detections), 306.4ms
Speed: 1.0ms preprocess, 306.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRsxznbpSxWms2XyhUedvA_0.JPG: 480x640 (no detections), 295.1ms
Speed: 2.1ms preprocess, 295.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRsxznbpSxWms2XyhUedvA_90.JPG: 480x640 (no detections), 296.3ms
Speed: 1.3ms preprocess, 296.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRsxznbpSxWms2XyhUedvA_180.JPG: 480x640 (no detections), 301.9ms
Speed: 1.1ms preprocess, 301.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRsxznbpSxWms2XyhUedvA_270.JPG: 480x640 (no detections), 301.8ms
Speed: 1.1ms preprocess, 301.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRvFrWheF7H1TjYeqXXFqw_0.JPG: 480x640 (no detections), 298.6ms
Speed: 1.3ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRvFrWheF7H1TjYeqXXFqw_90.JPG: 480x640 (no detections), 300.1ms
Speed: 1.2ms preprocess, 300.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRvFrWheF7H1TjYeqXXFqw_180.JPG: 480x640 (no detections), 304.2ms
Speed: 1.2ms preprocess, 304.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xRvFrWheF7H1TjYeqXXFqw_270.JPG: 480x640 (no detections), 309.1ms
Speed: 1.1ms preprocess, 309.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xS0w374X4mIqrztatxDkBQ_0.JPG: 480x640 (no detections), 298.6ms
Speed: 1.1ms preprocess, 298.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xS0w374X4mIqrztatxDkBQ_90.JPG: 480x640 (no detections), 299.7ms
Speed: 1.4ms preprocess, 299.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xS0w374X4mIqrztatxDkBQ_180.JPG: 480x640 (no detections), 293.9ms
Speed: 1.1ms preprocess, 293.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xS0w374X4mIqrztatxDkBQ_270.JPG: 480x640 (no detections), 300.1ms
Speed: 1.5ms preprocess, 300.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xS14yRkRK65Aq-RslnpNaw_0.JPG: 480x640 (no detections), 303.0ms
Speed: 1.3ms preprocess, 303.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xS14yRkRK65Aq-RslnpNaw_90.JPG: 480x640 (no detections), 295.5ms
Speed: 1.4ms preprocess, 295.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xS14yRkRK65Aq-RslnpNaw_180.JPG: 480x640 (no detections), 303.8ms
Speed: 1.2ms preprocess, 303.8ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xS14yRkRK65Aq-RslnpNaw_270.JPG: 480x640 (no detections), 305.4ms
Speed: 1.3ms preprocess, 305.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xS1xheBXSTp1md2aYDxBXw_0.JPG: 480x640 (no detections), 298.7ms
Speed: 1.2ms preprocess, 298.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xS1xheBXSTp1md2aYDxBXw_90.JPG: 480x640 (no detections), 305.3ms
Speed: 1.4ms preprocess, 305.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xS1xheBXSTp1md2aYDxBXw_180.JPG: 480x640 (no detections), 297.6ms
Speed: 1.2ms preprocess, 297.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xS1xheBXSTp1md2aYDxBXw_270.JPG: 480x640 (no detections), 301.2ms
Speed: 1.1ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xS2UirFE4xPx6NDBCzYTjw_0.JPG: 480x640 (no detections), 303.4ms
Speed: 1.4ms preprocess, 303.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xS2UirFE4xPx6NDBCzYTjw_90.JPG: 480x640 (no detections), 300.3ms
Speed: 1.1ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xS2UirFE4xPx6NDBCzYTjw_180.JPG: 480x640 (no detections), 299.0ms
Speed: 1.3ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xS2UirFE4xPx6NDBCzYTjw_270.JPG: 480x640 (no detections), 301.9ms
Speed: 1.3ms preprocess, 301.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xS3aLjkHZCzfIYl6LMx2Qg_0.JPG: 480x640 (no detections), 308.2ms
Speed: 1.1ms preprocess, 308.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xS3aLjkHZCzfIYl6LMx2Qg_90.JPG: 480x640 (no detections), 300.9ms
Speed: 1.4ms preprocess, 300.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xS3aLjkHZCzfIYl6LMx2Qg_180.JPG: 480x640 (no detections), 300.7ms
Speed: 1.1ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xS3aLjkHZCzfIYl6LMx2Qg_270.JPG: 480x640 (no detections), 304.2ms
Speed: 1.1ms preprocess, 304.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSAA06xX78r4MPPvah8tBg_0.JPG: 480x640 (no detections), 297.7ms
Speed: 1.0ms preprocess, 297.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSAA06xX78r4MPPvah8tBg_90.JPG: 480x640 (no detections), 302.1ms
Speed: 1.3ms preprocess, 302.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSAA06xX78r4MPPvah8tBg_180.JPG: 480x640 (no detections), 307.6ms
Speed: 1.2ms preprocess, 307.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSAA06xX78r4MPPvah8tBg_270.JPG: 480x640 (no detections), 303.4ms
Speed: 1.5ms preprocess, 303.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSAikVsnmlLIBb9MWMs8RQ_0.JPG: 480x640 (no detections), 298.2ms
Speed: 1.2ms preprocess, 298.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSAikVsnmlLIBb9MWMs8RQ_90.JPG: 480x640 (no detections), 303.8ms
Speed: 1.0ms preprocess, 303.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSAikVsnmlLIBb9MWMs8RQ_180.JPG: 480x640 (no detections), 302.4ms
Speed: 1.4ms preprocess, 302.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSAikVsnmlLIBb9MWMs8RQ_270.JPG: 480x640 (no detections), 296.5ms
Speed: 1.1ms preprocess, 296.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSBtWVLcCeqj5AtdePzV6A_0.JPG: 480x640 (no detections), 299.3ms
Speed: 1.2ms preprocess, 299.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSBtWVLcCeqj5AtdePzV6A_90.JPG: 480x640 (no detections), 298.9ms
Speed: 1.1ms preprocess, 298.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSBtWVLcCeqj5AtdePzV6A_180.JPG: 480x640 (no detections), 298.5ms
Speed: 1.1ms preprocess, 298.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSBtWVLcCeqj5AtdePzV6A_270.JPG: 480x640 (no detections), 300.1ms
Speed: 1.1ms preprocess, 300.1ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSEe_g390MT0dwywIyyMmQ_0.JPG: 480x640 (no detections), 298.4ms
Speed: 1.6ms preprocess, 298.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSEe_g390MT0dwywIyyMmQ_90.JPG: 480x640 (no detections), 304.3ms
Speed: 1.8ms preprocess, 304.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSEe_g390MT0dwywIyyMmQ_180.JPG: 480x640 (no detections), 302.5ms
Speed: 1.3ms preprocess, 302.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSEe_g390MT0dwywIyyMmQ_270.JPG: 480x640 (no detections), 294.8ms

Speed: 1.2ms preprocess, 294.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSJ9OR0Z8p6Bzs2j_aZGSw_0.JPG: 480x640 (no detections), 300.5ms
Speed: 1.4ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSJ9OR0Z8p6Bzs2j_aZGSw_90.JPG: 480x640 (no detections), 302.6ms
Speed: 1.1ms preprocess, 302.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSJ9OR0Z8p6Bzs2j_aZGSw_180.JPG: 480x640 (no detections), 300.5ms
Speed: 1.1ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSJ9OR0Z8p6Bzs2j_aZGSw_270.JPG: 480x640 (no detections), 296.7ms
Speed: 1.2ms preprocess, 296.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSPdST7b26ya8SRMZE4kDA_0.JPG: 480x640 (no detections), 301.7ms
Speed: 1.3ms preprocess, 301.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSPdST7b26ya8SRMZE4kDA_90.JPG: 480x640 (no detections), 296.7ms
Speed: 1.4ms preprocess, 296.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSPdST7b26ya8SRMZE4kDA_180.JPG: 480x640 (no detections), 298.8ms
Speed: 1.1ms preprocess, 298.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSPdST7b26ya8SRMZE4kDA_270.JPG: 480x640 (no detections), 303.3ms
Speed: 1.4ms preprocess, 303.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSR9bztQmj4RKf3OVIC3LA_0.JPG: 480x640 (no detections), 295.0ms
Speed: 1.1ms preprocess, 295.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSR9bztQmj4RKf3OVIC3LA_90.JPG: 480x640 (no detections), 299.4ms
Speed: 1.0ms preprocess, 299.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSR9bztQmj4RKf3OVIC3LA_180.JPG: 480x640 (no detections), 299.6ms
Speed: 1.2ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSR9bztQmj4RKf3OVIC3LA_270.JPG: 480x640 (no detections), 303.4ms
Speed: 1.3ms preprocess, 303.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSYZAXkJ0BgwSUr2FNxQNg_0.JPG: 480x640 (no detections), 296.5ms
Speed: 1.1ms preprocess, 296.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSYZAXkJ0BgwSUr2FNxQNg_90.JPG: 480x640 (no detections), 301.4ms
Speed: 1.2ms preprocess, 301.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSYZAXkJ0BgwSUr2FNxQNg_180.JPG: 480x640 (no detections), 304.5ms
Speed: 1.2ms preprocess, 304.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSYZAXkJ0BgwSUr2FNxQNg_270.JPG: 480x640 (no detections), 298.0ms
Speed: 1.2ms preprocess, 298.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSZwZ3dJGAAMgx7I9ZswEg_0.JPG: 480x640 (no detections), 303.9ms
Speed: 1.5ms preprocess, 303.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSZwZ3dJGAAMgx7I9ZswEg_90.JPG: 480x640 (no detections), 299.7ms
Speed: 2.0ms preprocess, 299.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSZwZ3dJGAAMgx7I9ZswEg_180.JPG: 480x640 (no detections), 300.2ms
Speed: 1.7ms preprocess, 300.2ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSZwZ3dJGAAMgx7I9ZswEg_270.JPG: 480x640 (no detections), 296.7ms
Speed: 1.3ms preprocess, 296.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xS_BZMAsaXeuyXKoVHrGDg_0.JPG: 480x640 (no detections), 303.8ms
Speed: 1.3ms preprocess, 303.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xS_BZMAsaXeuyXKoVHrGDg_90.JPG: 480x640 (no detections), 298.4ms
Speed: 1.1ms preprocess, 298.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xS_BZMAsaXeuyXKoVHrGDg_180.JPG: 480x640 (no detections), 297.7ms
Speed: 1.7ms preprocess, 297.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xS_BZMAsaXeuyXKoVHrGDg_270.JPG: 480x640 (no detections), 302.7ms
Speed: 1.1ms preprocess, 302.7ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSa7IMcGrljSx9lxLZXJMg_0.JPG: 480x640 (no detections), 299.0ms
Speed: 1.2ms preprocess, 299.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSa7IMcGrljSx9lxLZXJMg_90.JPG: 480x640 (no detections), 296.3ms
Speed: 1.1ms preprocess, 296.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSa7IMcGrljSx9lxLZXJMg_180.JPG: 480x640 (no detections), 294.8ms
Speed: 1.3ms preprocess, 294.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSa7IMcGrljSx9lxLZXJMg_270.JPG: 480x640 (no detections), 299.3ms
Speed: 1.2ms preprocess, 299.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSfGvT1CxO4uZ4ON7woHSg_0.JPG: 480x640 (no detections), 300.0ms
Speed: 1.3ms preprocess, 300.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSfGvT1CxO4uZ4ON7woHSg_90.JPG: 480x640 (no detections), 292.5ms
Speed: 1.3ms preprocess, 292.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSfGvT1CxO4uZ4ON7woHSg_180.JPG: 480x640 (no detections), 300.2ms
Speed: 1.1ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSfGvT1CxO4uZ4ON7woHSg_270.JPG: 480x640 (no detections), 298.1ms
Speed: 1.2ms preprocess, 298.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSfJ3fEDfn61jOcvl4Lx5A_0.JPG: 480x640 (no detections), 298.9ms
Speed: 1.1ms preprocess, 298.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSfJ3fEDfn61jOcvl4Lx5A_90.JPG: 480x640 (no detections), 305.2ms
Speed: 1.4ms preprocess, 305.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSfJ3fEDfn61jOcvl4Lx5A_180.JPG: 480x640 (no detections), 303.9ms
Speed: 1.3ms preprocess, 303.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSfJ3fEDfn61jOcvl4Lx5A_270.JPG: 480x640 (no detections), 298.6ms
Speed: 1.2ms preprocess, 298.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSh-A1bbYVWot8I_CHQUeg_0.JPG: 480x640 (no detections), 294.4ms
Speed: 1.2ms preprocess, 294.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSh-A1bbYVWot8I_CHQUeg_90.JPG: 480x640 (no detections), 296.7ms
Speed: 1.2ms preprocess, 296.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSh-A1bbYVWot8I_CHQUeg_180.JPG: 480x640 (no detections), 296.3ms
Speed: 1.1ms preprocess, 296.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSh-A1bbYVWot8I_CHQUeg_270.JPG: 480x640 (no detections), 297.9ms
Speed: 1.3ms preprocess, 297.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xShMm52n1Zsc0YYrvcV50Q_0.JPG: 480x640 (no detections), 304.3ms
Speed: 1.1ms preprocess, 304.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xShMm52n1Zsc0YYrvcV50Q_90.JPG: 480x640 (no detections), 301.4ms
Speed: 1.2ms preprocess, 301.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xShMm52n1Zsc0YYrvcV50Q_180.JPG: 480x640 (no detections), 302.6ms
Speed: 1.1ms preprocess, 302.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xShMm52n1Zsc0YYrvcV50Q_270.JPG: 480x640 (no detections), 301.3ms
Speed: 1.4ms preprocess, 301.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSiIPk92boyYdBEX03jF0g_0.JPG: 480x640 (no detections), 295.6ms
Speed: 1.2ms preprocess, 295.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSiIPk92boyYdBEX03jF0g_90.JPG: 480x640 (no detections), 301.9ms
Speed: 1.7ms preprocess, 301.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSiIPk92boyYdBEX03jF0g_180.JPG: 480x640 (no detections), 301.6ms
Speed: 1.1ms preprocess, 301.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSiIPk92boyYdBEX03jF0g_270.JPG: 480x640 (no detections), 296.1ms
Speed: 1.2ms preprocess, 296.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSlBQkxlI-2Vl5KSqmqATw_0.JPG: 480x640 (no detections), 296.4ms
Speed: 1.3ms preprocess, 296.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSlBQkxlI-2Vl5KSqmqATw_90.JPG: 480x640 (no detections), 297.8ms
Speed: 1.8ms preprocess, 297.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSlBQkxlI-2Vl5KSqmqATw_180.JPG: 480x640 (no detections), 307.4ms
Speed: 1.1ms preprocess, 307.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSlBQkxlI-2Vl5KSqmqATw_270.JPG: 480x640 (no detections), 289.8ms
Speed: 1.1ms preprocess, 289.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSnr8vWS-yUrfF0ZZv9AzA_0.JPG: 480x640 (no detections), 300.5ms
Speed: 1.1ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSnr8vWS-yUrfF0ZZv9AzA_90.JPG: 480x640 (no detections), 298.5ms
Speed: 1.2ms preprocess, 298.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSnr8vWS-yUrfF0ZZv9AzA_180.JPG: 480x640 (no detections), 299.4ms
Speed: 1.4ms preprocess, 299.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSnr8vWS-yUrfF0ZZv9AzA_270.JPG: 480x640 (no detections), 303.9ms
Speed: 1.2ms preprocess, 303.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSqi2Pn4KXHJQU8CX4BtUQ_0.JPG: 480x640 2 Wastes, 297.1ms
Speed: 1.3ms preprocess, 297.1ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSqi2Pn4KXHJQU8CX4BtUQ_90.JPG: 480x640 (no detections), 299.9ms
Speed: 1.3ms preprocess, 299.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSqi2Pn4KXHJQU8CX4BtUQ_180.JPG: 480x640 (no detections), 297.7ms
Speed: 1.1ms preprocess, 297.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSqi2Pn4KXHJQU8CX4BtUQ_270.JPG: 480x640 (no detections), 299.7ms
Speed: 1.3ms preprocess, 299.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSrynPDUscudz1VioZ-x9Q_0.JPG: 480x640 (no detections), 297.9ms
Speed: 1.2ms preprocess, 297.9ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSrynPDUscudz1VioZ-x9Q_90.JPG: 480x640 (no detections), 300.5ms
Speed: 1.2ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSrynPDUscudz1VioZ-x9Q_180.JPG: 480x640 (no detections), 299.8ms
Speed: 1.2ms preprocess, 299.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSrynPDUscudz1VioZ-x9Q_270.JPG: 480x640 (no detections), 304.0ms
Speed: 2.0ms preprocess, 304.0ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSu5viBeCQbnjqRXzVOT5A_0.JPG: 480x640 (no detections), 296.1ms
Speed: 1.3ms preprocess, 296.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSu5viBeCQbnjqRXzVOT5A_90.JPG: 480x640 (no detections), 304.1ms
Speed: 1.7ms preprocess, 304.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSu5viBeCQbnjqRXzVOT5A_180.JPG: 480x640 (no detections), 299.1ms

Speed: 1.2ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xSu5viBeCQbnjqRXzVOT5A_270.JPG: 480x640 (no detections), 301.2ms
Speed: 1.3ms preprocess, 301.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xT-ofSK4JjU0VO1iBf4Elw_0.JPG: 480x640 (no detections), 298.1ms
Speed: 1.3ms preprocess, 298.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xT-ofSK4JjU0VO1iBf4Elw_90.JPG: 480x640 (no detections), 302.8ms
Speed: 1.2ms preprocess, 302.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xT-ofSK4JjU0VO1iBf4Elw_180.JPG: 480x640 1 Waste, 298.5ms
Speed: 1.1ms preprocess, 298.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xT-ofSK4JjU0VO1iBf4Elw_270.JPG: 480x640 1 Waste, 295.2ms
Speed: 1.2ms preprocess, 295.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xT23XMwPaqLyJXhRCAiKtA_0.JPG: 480x640 (no detections), 296.5ms
Speed: 1.3ms preprocess, 296.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xT23XMwPaqLyJXhRCAiKtA_90.JPG: 480x640 (no detections), 301.3ms
Speed: 1.2ms preprocess, 301.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xT23XMwPaqLyJXhRCAiKtA_180.JPG: 480x640 (no detections), 301.3ms
Speed: 1.3ms preprocess, 301.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xT23XMwPaqLyJXhRCAiKtA_270.JPG: 480x640 (no detections), 301.3ms
Speed: 1.2ms preprocess, 301.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xT2g3mkDo_ThDuZAd0FDKQ_0.JPG: 480x640 (no detections), 300.5ms
Speed: 1.1ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xT2g3mkDo_ThDuZAd0FDKQ_90.JPG: 480x640 (no detections), 300.4ms
Speed: 1.4ms preprocess, 300.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xT2g3mkDo_ThDuZAd0FDKQ_180.JPG: 480x640 (no detections), 299.5ms
Speed: 1.4ms preprocess, 299.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xT2g3mkDo_ThDuZAd0FDKQ_270.JPG: 480x640 (no detections), 299.6ms
Speed: 1.7ms preprocess, 299.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xT2gzuKZNMh9KkzS_ampew_0.JPG: 480x640 (no detections), 304.1ms
Speed: 1.3ms preprocess, 304.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xT2gzuKZNMh9KkzS_ampew_90.JPG: 480x640 (no detections), 298.5ms
Speed: 1.5ms preprocess, 298.5ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xT2gzuKZNMh9KkzS_ampew_180.JPG: 480x640 (no detections), 298.0ms
Speed: 1.2ms preprocess, 298.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xT2gzuKZNMh9KkzS_ampew_270.JPG: 480x640 (no detections), 305.0ms
Speed: 1.4ms preprocess, 305.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xT3XS8KWcoCQd5eU08Fp4A_0.JPG: 480x640 (no detections), 296.1ms
Speed: 1.1ms preprocess, 296.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xT3XS8KWcoCQd5eU08Fp4A_90.JPG: 480x640 (no detections), 302.0ms
Speed: 1.1ms preprocess, 302.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xT3XS8KWcoCQd5eU08Fp4A_180.JPG: 480x640 (no detections), 302.4ms
Speed: 1.4ms preprocess, 302.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xT3XS8KWcoCQd5eU08Fp4A_270.JPG: 480x640 (no detections), 303.2ms
Speed: 1.2ms preprocess, 303.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTARW9Y0wXjTHtOQvq1PsQ_0.JPG: 480x640 (no detections), 299.9ms
Speed: 1.3ms preprocess, 299.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTARW9Y0wXjTHtOQvq1PsQ_90.JPG: 480x640 (no detections), 298.9ms
Speed: 1.1ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTARW9Y0wXjTHtOQvq1PsQ_180.JPG: 480x640 (no detections), 301.7ms
Speed: 1.2ms preprocess, 301.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTARW9Y0wXjTHtOQvq1PsQ_270.JPG: 480x640 (no detections), 300.6ms
Speed: 1.2ms preprocess, 300.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTDmvuhunim3qiZDgOtldw_0.JPG: 480x640 (no detections), 299.0ms
Speed: 1.2ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTDmvuhunim3qiZDgOtldw_90.JPG: 480x640 (no detections), 307.0ms
Speed: 1.2ms preprocess, 307.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTDmvuhunim3qiZDgOtldw_180.JPG: 480x640 (no detections), 296.5ms
Speed: 1.1ms preprocess, 296.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTDmvuhunim3qiZDgOtldw_270.JPG: 480x640 1 Waste, 299.9ms
Speed: 1.1ms preprocess, 299.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTEaTKAmqB5DUvwhRu8_eg_0.JPG: 480x640 (no detections), 292.7ms
Speed: 1.1ms preprocess, 292.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTEaTKAmqB5DUvwhRu8_eg_90.JPG: 480x640 (no detections), 294.9ms
Speed: 1.2ms preprocess, 294.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTEaTKAmqB5DUvwhRu8_eg_180.JPG: 480x640 (no detections), 294.5ms
Speed: 1.1ms preprocess, 294.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTEaTKAmqB5DUvwhRu8_eg_270.JPG: 480x640 (no detections), 298.0ms
Speed: 1.1ms preprocess, 298.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTG7WUShNYdXceVQpHNFUQ_0.JPG: 480x640 (no detections), 295.0ms
Speed: 1.3ms preprocess, 295.0ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTG7WUShNYdXceVQpHNFUQ_90.JPG: 480x640 1 Waste, 292.9ms
Speed: 1.2ms preprocess, 292.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTG7WUShNYdXceVQpHNFUQ_180.JPG: 480x640 (no detections), 297.8ms
Speed: 1.1ms preprocess, 297.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTG7WUShNYdXceVQpHNFUQ_270.JPG: 480x640 (no detections), 293.8ms
Speed: 1.2ms preprocess, 293.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTI9FntFOP1NBBa8dRRk3A_0.JPG: 480x640 (no detections), 292.5ms
Speed: 1.2ms preprocess, 292.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTI9FntFOP1NBBa8dRRk3A_90.JPG: 480x640 (no detections), 295.1ms
Speed: 1.2ms preprocess, 295.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTI9FntFOP1NBBa8dRRk3A_180.JPG: 480x640 (no detections), 293.4ms
Speed: 1.2ms preprocess, 293.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTI9FntFOP1NBBa8dRRk3A_270.JPG: 480x640 (no detections), 293.6ms
Speed: 1.2ms preprocess, 293.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTKZOTM_iFxlf6pgLVJV2w_0.JPG: 480x640 (no detections), 293.9ms
Speed: 1.1ms preprocess, 293.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTKZOTM_iFxlf6pgLVJV2w_90.JPG: 480x640 (no detections), 300.4ms
Speed: 1.1ms preprocess, 300.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTKZOTM_iFxlf6pgLVJV2w_180.JPG: 480x640 (no detections), 295.2ms
Speed: 1.3ms preprocess, 295.2ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTKZOTM_iFxlf6pgLVJV2w_270.JPG: 480x640 (no detections), 294.4ms
Speed: 1.2ms preprocess, 294.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTNXJ1qpHr_rM5CyyreGKQ_0.JPG: 480x640 (no detections), 303.8ms
Speed: 1.0ms preprocess, 303.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTNXJ1qpHr_rM5CyyreGKQ_90.JPG: 480x640 (no detections), 293.0ms
Speed: 1.1ms preprocess, 293.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTNXJ1qpHr_rM5CyyreGKQ_180.JPG: 480x640 (no detections), 298.3ms
Speed: 1.2ms preprocess, 298.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTNXJ1qpHr_rM5CyyreGKQ_270.JPG: 480x640 (no detections), 298.2ms
Speed: 1.2ms preprocess, 298.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTZ1oPz6oSm8HtKy2F_J8A_0.JPG: 480x640 (no detections), 293.5ms
Speed: 1.5ms preprocess, 293.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTZ1oPz6oSm8HtKy2F_J8A_90.JPG: 480x640 (no detections), 299.6ms
Speed: 1.7ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTZ1oPz6oSm8HtKy2F_J8A_180.JPG: 480x640 (no detections), 298.5ms
Speed: 1.2ms preprocess, 298.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTZ1oPz6oSm8HtKy2F_J8A_270.JPG: 480x640 (no detections), 292.4ms
Speed: 1.0ms preprocess, 292.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTZ5p5kQ-QM73qytOZu5dA_0.JPG: 480x640 (no detections), 293.4ms
Speed: 1.4ms preprocess, 293.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTZ5p5kQ-QM73qytOZu5dA_90.JPG: 480x640 (no detections), 298.3ms
Speed: 1.0ms preprocess, 298.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTZ5p5kQ-QM73qytOZu5dA_180.JPG: 480x640 (no detections), 298.1ms
Speed: 1.4ms preprocess, 298.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTZ5p5kQ-QM73qytOZu5dA_270.JPG: 480x640 (no detections), 296.1ms
Speed: 1.3ms preprocess, 296.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTb4LGpNrzWiH3ylZtTDwQ_0.JPG: 480x640 (no detections), 296.5ms
Speed: 1.1ms preprocess, 296.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTb4LGpNrzWiH3ylZtTDwQ_90.JPG: 480x640 (no detections), 296.0ms
Speed: 1.1ms preprocess, 296.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTb4LGpNrzWiH3ylZtTDwQ_180.JPG: 480x640 (no detections), 305.9ms
Speed: 1.2ms preprocess, 305.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTb4LGpNrzWiH3ylZtTDwQ_270.JPG: 480x640 (no detections), 297.7ms
Speed: 1.2ms preprocess, 297.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTbCGG4E6bngrEDdVFSC1Q_0.JPG: 480x640 (no detections), 293.3ms
Speed: 1.2ms preprocess, 293.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTbCGG4E6bngrEDdVFSC1Q_90.JPG: 480x640 (no detections), 296.3ms
Speed: 1.6ms preprocess, 296.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTbCGG4E6bngrEDdVFSC1Q_180.JPG: 480x640 (no detections), 297.2ms
Speed: 1.1ms preprocess, 297.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTbCGG4E6bngrEDdVFSC1Q_270.JPG: 480x640 (no detections), 296.8ms
Speed: 1.1ms preprocess, 296.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTbs5EWf5o7ImrvEM7HNwg_0.JPG: 480x640 (no detections), 293.7ms
Speed: 1.4ms preprocess, 293.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTbs5EWf5o7ImrvEM7HNwg_90.JPG: 480x640 (no detections), 293.0ms

Speed: 1.2ms preprocess, 293.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTbs5EWf5o7ImrvEM7HNwg_180.JPG: 480x640 (no detections), 297.7ms
Speed: 1.2ms preprocess, 297.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTbs5EWf5o7ImrvEM7HNwg_270.JPG: 480x640 (no detections), 301.2ms
Speed: 1.4ms preprocess, 301.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTgUeXS3-zbrxcrD_f39GA_0.JPG: 480x640 (no detections), 292.5ms
Speed: 1.1ms preprocess, 292.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTgUeXS3-zbrxcrD_f39GA_90.JPG: 480x640 (no detections), 298.0ms
Speed: 1.1ms preprocess, 298.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTgUeXS3-zbrxcrD_f39GA_180.JPG: 480x640 (no detections), 295.7ms
Speed: 1.1ms preprocess, 295.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTgUeXS3-zbrxcrD_f39GA_270.JPG: 480x640 (no detections), 299.6ms
Speed: 1.3ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTiBBIX5cTwesr8oTubvcA_0.JPG: 480x640 (no detections), 293.3ms
Speed: 1.1ms preprocess, 293.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTiBBIX5cTwesr8oTubvcA_90.JPG: 480x640 (no detections), 295.6ms
Speed: 1.0ms preprocess, 295.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTiBBIX5cTwesr8oTubvcA_180.JPG: 480x640 (no detections), 291.7ms
Speed: 1.3ms preprocess, 291.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTiBBIX5cTwesr8oTubvcA_270.JPG: 480x640 (no detections), 293.9ms
Speed: 1.3ms preprocess, 293.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTj09AvWoIH7r-UAHYo1eA_0.JPG: 480x640 (no detections), 296.1ms
Speed: 1.4ms preprocess, 296.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTj09AvWoIH7r-UAHYo1eA_90.JPG: 480x640 (no detections), 296.9ms
Speed: 1.2ms preprocess, 296.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTj09AvWoIH7r-UAHYo1eA_180.JPG: 480x640 (no detections), 297.7ms
Speed: 1.3ms preprocess, 297.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTj09AvWoIH7r-UAHYo1eA_270.JPG: 480x640 (no detections), 294.6ms
Speed: 1.2ms preprocess, 294.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTny2Y_-35v8puFs9voYbQ_0.JPG: 480x640 1 Waste, 298.6ms
Speed: 1.1ms preprocess, 298.6ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTny2Y_-35v8puFs9voYbQ_90.JPG: 480x640 (no detections), 296.9ms
Speed: 1.0ms preprocess, 296.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTny2Y_-35v8puFs9voYbQ_180.JPG: 480x640 (no detections), 301.2ms
Speed: 1.3ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTny2Y_-35v8puFs9voYbQ_270.JPG: 480x640 (no detections), 298.0ms
Speed: 1.2ms preprocess, 298.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTrTf2RpOq7isJ8-BFzB8g_0.JPG: 480x640 (no detections), 297.7ms
Speed: 1.1ms preprocess, 297.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTrTf2RpOq7isJ8-BFzB8g_90.JPG: 480x640 (no detections), 300.2ms
Speed: 1.1ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTrTf2RpOq7isJ8-BFzB8g_180.JPG: 480x640 (no detections), 297.2ms
Speed: 1.1ms preprocess, 297.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTrTf2RpOq7isJ8-BFzB8g_270.JPG: 480x640 (no detections), 300.5ms
Speed: 1.2ms preprocess, 300.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTtxo2T38kSSjEIhJKQ3IQ_0.JPG: 480x640 1 Waste, 300.3ms
Speed: 1.6ms preprocess, 300.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTtxo2T38kSSjEIhJKQ3IQ_90.JPG: 480x640 (no detections), 293.0ms
Speed: 1.1ms preprocess, 293.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTtxo2T38kSSjEIhJKQ3IQ_180.JPG: 480x640 (no detections), 298.0ms
Speed: 1.0ms preprocess, 298.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTtxo2T38kSSjEIhJKQ3IQ_270.JPG: 480x640 (no detections), 293.9ms
Speed: 1.8ms preprocess, 293.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTwp4zDLxOjaqFCwwMZ64Q_0.JPG: 480x640 (no detections), 297.6ms
Speed: 1.8ms preprocess, 297.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTwp4zDLxOjaqFCwwMZ64Q_90.JPG: 480x640 1 Waste, 292.8ms
Speed: 1.1ms preprocess, 292.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTwp4zDLxOjaqFCwwMZ64Q_180.JPG: 480x640 (no detections), 299.3ms
Speed: 1.1ms preprocess, 299.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTwp4zDLxOjaqFCwwMZ64Q_270.JPG: 480x640 (no detections), 294.6ms
Speed: 1.1ms preprocess, 294.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTxd45UqVwemaqATb2yr7g_0.JPG: 480x640 (no detections), 292.7ms
Speed: 1.2ms preprocess, 292.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTxd45UqVwemaqATb2yr7g_90.JPG: 480x640 (no detections), 294.3ms
Speed: 1.1ms preprocess, 294.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTxd45UqVwemaqATb2yr7g_180.JPG: 480x640 (no detections), 300.9ms
Speed: 1.1ms preprocess, 300.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xTxd45UqVwemaqATb2yr7g_270.JPG: 480x640 (no detections), 298.1ms
Speed: 1.1ms preprocess, 298.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xU-f30vSW1Rb3rUsGLsCRg_0.JPG: 480x640 (no detections), 298.9ms
Speed: 1.4ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xU-f30vSW1Rb3rUsGLsCRg_90.JPG: 480x640 (no detections), 294.3ms
Speed: 1.2ms preprocess, 294.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xU-f30vSW1Rb3rUsGLsCRg_180.JPG: 480x640 (no detections), 295.3ms
Speed: 1.3ms preprocess, 295.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xU-f30vSW1Rb3rUsGLsCRg_270.JPG: 480x640 (no detections), 293.1ms
Speed: 1.2ms preprocess, 293.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xU0vr0cQkbWDMrL1B-dZIg_0.JPG: 480x640 (no detections), 296.1ms
Speed: 1.2ms preprocess, 296.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xU0vr0cQkbWDMrL1B-dZIg_90.JPG: 480x640 (no detections), 293.4ms
Speed: 1.2ms preprocess, 293.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xU0vr0cQkbWDMrL1B-dZIg_180.JPG: 480x640 (no detections), 297.5ms
Speed: 1.3ms preprocess, 297.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xU0vr0cQkbWDMrL1B-dZIg_270.JPG: 480x640 (no detections), 299.7ms
Speed: 1.3ms preprocess, 299.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xU2HSflwgZlB0cYl5x1Nww_0.JPG: 480x640 (no detections), 291.4ms
Speed: 1.1ms preprocess, 291.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xU2HSflwgZlB0cYl5x1Nww_90.JPG: 480x640 (no detections), 294.1ms
Speed: 1.2ms preprocess, 294.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xU2HSflwgZlB0cYl5x1Nww_180.JPG: 480x640 (no detections), 293.2ms
Speed: 1.1ms preprocess, 293.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xU2HSflwgZlB0cYl5x1Nww_270.JPG: 480x640 (no detections), 297.2ms
Speed: 1.1ms preprocess, 297.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xU89XyKBtJDLOHFzFiO2EA_0.JPG: 480x640 (no detections), 298.3ms
Speed: 1.2ms preprocess, 298.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xU89XyKBtJDLOHFzFiO2EA_90.JPG: 480x640 (no detections), 296.1ms
Speed: 1.0ms preprocess, 296.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xU89XyKBtJDLOHFzFiO2EA_180.JPG: 480x640 (no detections), 299.3ms
Speed: 1.3ms preprocess, 299.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xU89XyKBtJDLOHFzFiO2EA_270.JPG: 480x640 (no detections), 304.8ms
Speed: 1.1ms preprocess, 304.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xU8yJd84tFUNZpFs5XcA0g_0.JPG: 480x640 (no detections), 293.9ms
Speed: 1.1ms preprocess, 293.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xU8yJd84tFUNZpFs5XcA0g_90.JPG: 480x640 (no detections), 297.3ms
Speed: 1.1ms preprocess, 297.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xU8yJd84tFUNZpFs5XcA0g_180.JPG: 480x640 (no detections), 296.5ms
Speed: 1.2ms preprocess, 296.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xU8yJd84tFUNZpFs5XcA0g_270.JPG: 480x640 (no detections), 294.3ms
Speed: 1.3ms preprocess, 294.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUAYTQb6w5A2r_Y8L29R9w_0.JPG: 480x640 (no detections), 291.1ms
Speed: 1.3ms preprocess, 291.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUAYTQb6w5A2r_Y8L29R9w_90.JPG: 480x640 (no detections), 297.6ms
Speed: 1.2ms preprocess, 297.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUAYTQb6w5A2r_Y8L29R9w_180.JPG: 480x640 (no detections), 298.1ms
Speed: 1.1ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUAYTQb6w5A2r_Y8L29R9w_270.JPG: 480x640 (no detections), 292.6ms
Speed: 1.2ms preprocess, 292.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUAqS7RQvyJh0wTFLFrKxg_0.JPG: 480x640 (no detections), 300.4ms
Speed: 1.1ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUAqS7RQvyJh0wTFLFrKxg_90.JPG: 480x640 (no detections), 295.9ms
Speed: 1.3ms preprocess, 295.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUAqS7RQvyJh0wTFLFrKxg_180.JPG: 480x640 (no detections), 292.7ms
Speed: 1.1ms preprocess, 292.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUAqS7RQvyJh0wTFLFrKxg_270.JPG: 480x640 (no detections), 301.4ms
Speed: 1.0ms preprocess, 301.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUFqttoKO6ZNHAHZ1kQLlA_0.JPG: 480x640 (no detections), 297.7ms
Speed: 1.1ms preprocess, 297.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUFqttoKO6ZNHAHZ1kQLlA_90.JPG: 480x640 (no detections), 293.7ms
Speed: 1.6ms preprocess, 293.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUFqttoKO6ZNHAHZ1kQLlA_180.JPG: 480x640 (no detections), 295.7ms
Speed: 1.1ms preprocess, 295.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUFqttoKO6ZNHAHZ1kQLlA_270.JPG: 480x640 (no detections), 293.8ms
Speed: 1.6ms preprocess, 293.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUJuOygb-ngZVJ-XaZnCPg_0.JPG: 480x640 (no detections), 299.8ms

Speed: 1.2ms preprocess, 299.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUJuOygb-ngZVJ-XaZnCPg_90.JPG: 480x640 (no detections), 294.2ms
Speed: 1.1ms preprocess, 294.2ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUJuOygb-ngZVJ-XaZnCPg_180.JPG: 480x640 (no detections), 296.3ms
Speed: 1.2ms preprocess, 296.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUJuOygb-ngZVJ-XaZnCPg_270.JPG: 480x640 (no detections), 299.2ms
Speed: 1.4ms preprocess, 299.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xULGGX2S07SPWgr3hx1vfQ_0.JPG: 480x640 (no detections), 293.3ms
Speed: 1.1ms preprocess, 293.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xULGGX2S07SPWgr3hx1vfQ_90.JPG: 480x640 (no detections), 297.0ms
Speed: 1.2ms preprocess, 297.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xULGGX2S07SPWgr3hx1vfQ_180.JPG: 480x640 (no detections), 299.9ms
Speed: 1.3ms preprocess, 299.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xULGGX2S07SPWgr3hx1vfQ_270.JPG: 480x640 (no detections), 294.2ms
Speed: 1.3ms preprocess, 294.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUSmWWycnaZF92a8chYwxw_0.JPG: 480x640 (no detections), 295.1ms
Speed: 1.6ms preprocess, 295.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUSmWWycnaZF92a8chYwxw_90.JPG: 480x640 (no detections), 298.3ms
Speed: 1.4ms preprocess, 298.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUSmWWycnaZF92a8chYwxw_180.JPG: 480x640 (no detections), 381.9ms
Speed: 1.3ms preprocess, 381.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUSmWWycnaZF92a8chYwxw_270.JPG: 480x640 (no detections), 298.8ms
Speed: 1.1ms preprocess, 298.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUU5WyxXGTPJmtOBtAvq1g_0.JPG: 480x640 (no detections), 291.6ms
Speed: 1.2ms preprocess, 291.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUU5WyxXGTPJmtOBtAvq1g_90.JPG: 480x640 (no detections), 291.4ms
Speed: 1.2ms preprocess, 291.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUU5WyxXGTPJmtOBtAvq1g_180.JPG: 480x640 (no detections), 289.6ms
Speed: 1.2ms preprocess, 289.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUU5WyxXGTPJmtOBtAvq1g_270.JPG: 480x640 (no detections), 298.4ms
Speed: 1.3ms preprocess, 298.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUVKgERtOHW4jlIfw56AfQ_0.JPG: 480x640 (no detections), 294.4ms
Speed: 1.0ms preprocess, 294.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUVKgERtOHW4jlIfw56AfQ_90.JPG: 480x640 (no detections), 295.8ms
Speed: 1.2ms preprocess, 295.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUVKgERtOHW4jlIfw56AfQ_180.JPG: 480x640 (no detections), 299.6ms
Speed: 1.4ms preprocess, 299.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUVKgERtOHW4jlIfw56AfQ_270.JPG: 480x640 (no detections), 306.4ms
Speed: 1.2ms preprocess, 306.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUaXsj2FIz8mRNo9tMsbAA_0.JPG: 480x640 (no detections), 297.8ms
Speed: 1.2ms preprocess, 297.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUaXsj2FIz8mRNo9tMsbAA_90.JPG: 480x640 (no detections), 293.0ms
Speed: 1.2ms preprocess, 293.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUaXsj2FIz8mRNo9tMsbAA_180.JPG: 480x640 (no detections), 296.4ms
Speed: 1.1ms preprocess, 296.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUaXsj2FIz8mRNo9tMsbAA_270.JPG: 480x640 (no detections), 292.1ms
Speed: 1.2ms preprocess, 292.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUfcX9wjPfbtd-4Zj_-u0Q_0.JPG: 480x640 (no detections), 296.5ms
Speed: 1.4ms preprocess, 296.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUfcX9wjPfbtd-4Zj_-u0Q_90.JPG: 480x640 (no detections), 297.9ms
Speed: 1.1ms preprocess, 297.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUfcX9wjPfbtd-4Zj_-u0Q_180.JPG: 480x640 (no detections), 291.7ms
Speed: 1.0ms preprocess, 291.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUfcX9wjPfbtd-4Zj_-u0Q_270.JPG: 480x640 (no detections), 286.2ms
Speed: 1.2ms preprocess, 286.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUl9AqdQpkbIm9BEMe96EQ_0.JPG: 480x640 (no detections), 298.2ms
Speed: 1.3ms preprocess, 298.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUl9AqdQpkbIm9BEMe96EQ_90.JPG: 480x640 (no detections), 298.4ms
Speed: 1.1ms preprocess, 298.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUl9AqdQpkbIm9BEMe96EQ_180.JPG: 480x640 (no detections), 295.8ms
Speed: 1.1ms preprocess, 295.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUl9AqdQpkbIm9BEMe96EQ_270.JPG: 480x640 (no detections), 298.3ms
Speed: 1.4ms preprocess, 298.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUp3yipUSk6kHwli7R1C6w_0.JPG: 480x640 (no detections), 298.5ms
Speed: 1.3ms preprocess, 298.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUp3yipUSk6kHwli7R1C6w_90.JPG: 480x640 (no detections), 295.2ms
Speed: 1.3ms preprocess, 295.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUp3yipUSk6kHwli7R1C6w_180.JPG: 480x640 (no detections), 292.7ms
Speed: 1.2ms preprocess, 292.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUp3yipUSk6kHwli7R1C6w_270.JPG: 480x640 (no detections), 295.4ms
Speed: 1.1ms preprocess, 295.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUr1b--gzsVv3U0htcrBRg_0.JPG: 480x640 (no detections), 297.8ms
Speed: 1.3ms preprocess, 297.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUr1b--gzsVv3U0htcrBRg_90.JPG: 480x640 (no detections), 288.1ms
Speed: 1.2ms preprocess, 288.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUr1b--gzsVv3U0htcrBRg_180.JPG: 480x640 (no detections), 294.1ms
Speed: 1.2ms preprocess, 294.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUr1b--gzsVv3U0htcrBRg_270.JPG: 480x640 (no detections), 299.3ms
Speed: 1.5ms preprocess, 299.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUt3tH7-YxAVPlk_Qu4CJA_0.JPG: 480x640 (no detections), 295.7ms
Speed: 1.1ms preprocess, 295.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUt3tH7-YxAVPlk_Qu4CJA_90.JPG: 480x640 (no detections), 299.5ms
Speed: 1.0ms preprocess, 299.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUt3tH7-YxAVPlk_Qu4CJA_180.JPG: 480x640 (no detections), 295.3ms
Speed: 1.1ms preprocess, 295.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUt3tH7-YxAVPlk_Qu4CJA_270.JPG: 480x640 (no detections), 296.5ms
Speed: 1.2ms preprocess, 296.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUuULjlT492a_RjulfXBWw_0.JPG: 480x640 (no detections), 298.7ms
Speed: 1.1ms preprocess, 298.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUuULjlT492a_RjulfXBWw_90.JPG: 480x640 (no detections), 294.1ms
Speed: 1.1ms preprocess, 294.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUuULjlT492a_RjulfXBWw_180.JPG: 480x640 (no detections), 297.9ms
Speed: 1.4ms preprocess, 297.9ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUuULjlT492a_RjulfXBWw_270.JPG: 480x640 (no detections), 298.7ms
Speed: 1.3ms preprocess, 298.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUyS8HgcdnneQ6VJDiglTw_0.JPG: 480x640 (no detections), 296.6ms
Speed: 1.3ms preprocess, 296.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUyS8HgcdnneQ6VJDiglTw_90.JPG: 480x640 (no detections), 294.1ms
Speed: 1.1ms preprocess, 294.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUyS8HgcdnneQ6VJDiglTw_180.JPG: 480x640 (no detections), 298.4ms
Speed: 1.3ms preprocess, 298.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUyS8HgcdnneQ6VJDiglTw_270.JPG: 480x640 (no detections), 302.4ms
Speed: 1.3ms preprocess, 302.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUzZiVB3r3Z25xE80UXpJw_0.JPG: 480x640 (no detections), 297.2ms
Speed: 1.2ms preprocess, 297.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUzZiVB3r3Z25xE80UXpJw_90.JPG: 480x640 (no detections), 296.6ms
Speed: 1.1ms preprocess, 296.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUzZiVB3r3Z25xE80UXpJw_180.JPG: 480x640 (no detections), 293.3ms
Speed: 1.9ms preprocess, 293.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xUzZiVB3r3Z25xE80UXpJw_270.JPG: 480x640 (no detections), 296.1ms
Speed: 1.3ms preprocess, 296.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xV7COE2D-dF4MLYFJ5DU4A_0.JPG: 480x640 (no detections), 296.7ms
Speed: 1.3ms preprocess, 296.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xV7COE2D-dF4MLYFJ5DU4A_90.JPG: 480x640 (no detections), 300.4ms
Speed: 1.1ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xV7COE2D-dF4MLYFJ5DU4A_180.JPG: 480x640 (no detections), 297.4ms
Speed: 1.3ms preprocess, 297.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xV7COE2D-dF4MLYFJ5DU4A_270.JPG: 480x640 (no detections), 300.3ms
Speed: 1.3ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xV81LQQyPai79F5joPJlFQ_0.JPG: 480x640 (no detections), 292.6ms
Speed: 1.3ms preprocess, 292.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xV81LQQyPai79F5joPJlFQ_90.JPG: 480x640 (no detections), 298.5ms
Speed: 1.5ms preprocess, 298.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xV81LQQyPai79F5joPJlFQ_180.JPG: 480x640 (no detections), 297.7ms
Speed: 1.4ms preprocess, 297.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xV81LQQyPai79F5joPJlFQ_270.JPG: 480x640 (no detections), 297.0ms
Speed: 1.2ms preprocess, 297.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xV9oyh8wRrg6QbfdaaHlRA_0.JPG: 480x640 (no detections), 295.4ms
Speed: 1.2ms preprocess, 295.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xV9oyh8wRrg6QbfdaaHlRA_90.JPG: 480x640 (no detections), 294.7ms
Speed: 1.3ms preprocess, 294.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xV9oyh8wRrg6QbfdaaHlRA_180.JPG: 480x640 (no detections), 297.7ms
Speed: 1.2ms preprocess, 297.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xV9oyh8wRrg6QbfdaaHlRA_270.JPG: 480x640 (no detections), 296.8ms

Speed: 1.4ms preprocess, 296.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVAd-lHSZJUTZnNX5O3Ftw_0.JPG: 480x640 (no detections), 298.7ms
Speed: 1.6ms preprocess, 298.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVAd-lHSZJUTZnNX5O3Ftw_90.JPG: 480x640 1 Waste, 303.6ms
Speed: 1.2ms preprocess, 303.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVAd-lHSZJUTZnNX5O3Ftw_180.JPG: 480x640 (no detections), 292.7ms
Speed: 1.4ms preprocess, 292.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVAd-lHSZJUTZnNX5O3Ftw_270.JPG: 480x640 (no detections), 297.0ms
Speed: 1.1ms preprocess, 297.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVBjGy_82qi1I-mbuT3gWA_0.JPG: 480x640 (no detections), 301.2ms
Speed: 1.3ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVBjGy_82qi1I-mbuT3gWA_90.JPG: 480x640 (no detections), 298.6ms
Speed: 1.2ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVBjGy_82qi1I-mbuT3gWA_180.JPG: 480x640 (no detections), 303.2ms
Speed: 1.9ms preprocess, 303.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVBjGy_82qi1I-mbuT3gWA_270.JPG: 480x640 (no detections), 295.2ms
Speed: 1.3ms preprocess, 295.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVHmrUhiAL8-jjILP4KyRA_0.JPG: 480x640 (no detections), 293.3ms
Speed: 1.2ms preprocess, 293.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVHmrUhiAL8-jjILP4KyRA_90.JPG: 480x640 (no detections), 294.2ms
Speed: 1.2ms preprocess, 294.2ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVHmrUhiAL8-jjILP4KyRA_180.JPG: 480x640 (no detections), 296.6ms
Speed: 1.1ms preprocess, 296.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVHmrUhiAL8-jjILP4KyRA_270.JPG: 480x640 (no detections), 300.9ms
Speed: 1.2ms preprocess, 300.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVIf6UaIKJDiUa-JhzHQow_0.JPG: 480x640 (no detections), 298.1ms
Speed: 1.1ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVIf6UaIKJDiUa-JhzHQow_90.JPG: 480x640 (no detections), 298.0ms
Speed: 1.2ms preprocess, 298.0ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVIf6UaIKJDiUa-JhzHQow_180.JPG: 480x640 (no detections), 294.5ms
Speed: 1.3ms preprocess, 294.5ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVIf6UaIKJDiUa-JhzHQow_270.JPG: 480x640 (no detections), 310.1ms
Speed: 1.7ms preprocess, 310.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVKCPaAzInbV4S-f10SirA_0.JPG: 480x640 (no detections), 294.4ms
Speed: 1.2ms preprocess, 294.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVKCPaAzInbV4S-f10SirA_90.JPG: 480x640 (no detections), 299.6ms
Speed: 1.1ms preprocess, 299.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVKCPaAzInbV4S-f10SirA_180.JPG: 480x640 (no detections), 291.8ms
Speed: 1.0ms preprocess, 291.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVKCPaAzInbV4S-f10SirA_270.JPG: 480x640 (no detections), 293.8ms
Speed: 1.2ms preprocess, 293.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVLEisaAPDbLsUeOLSLXsw_0.JPG: 480x640 (no detections), 295.1ms
Speed: 1.3ms preprocess, 295.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVLEisaAPDbLsUeOLSLXsw_90.JPG: 480x640 (no detections), 292.8ms
Speed: 1.2ms preprocess, 292.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVLEisaAPDbLsUeOLSLXsw_180.JPG: 480x640 (no detections), 298.1ms
Speed: 1.0ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVLEisaAPDbLsUeOLSLXsw_270.JPG: 480x640 (no detections), 296.0ms
Speed: 1.1ms preprocess, 296.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVN6d6pQUjKmyly6qMGq2w_0.JPG: 480x640 (no detections), 292.3ms
Speed: 1.1ms preprocess, 292.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVN6d6pQUjKmyly6qMGq2w_90.JPG: 480x640 (no detections), 296.2ms
Speed: 1.2ms preprocess, 296.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVN6d6pQUjKmyly6qMGq2w_180.JPG: 480x640 (no detections), 294.8ms
Speed: 1.2ms preprocess, 294.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVN6d6pQUjKmyly6qMGq2w_270.JPG: 480x640 (no detections), 291.2ms
Speed: 1.4ms preprocess, 291.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVOtlAik-NXSrZPdDVVfzQ_0.JPG: 480x640 (no detections), 296.5ms
Speed: 1.2ms preprocess, 296.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVOtlAik-NXSrZPdDVVfzQ_90.JPG: 480x640 (no detections), 296.0ms
Speed: 1.1ms preprocess, 296.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVOtlAik-NXSrZPdDVVfzQ_180.JPG: 480x640 (no detections), 296.3ms
Speed: 1.3ms preprocess, 296.3ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVOtlAik-NXSrZPdDVVfzQ_270.JPG: 480x640 (no detections), 298.7ms
Speed: 1.1ms preprocess, 298.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVOyCM-xQUNoG0cnkkUEaA_0.JPG: 480x640 (no detections), 292.0ms
Speed: 1.2ms preprocess, 292.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVOyCM-xQUNoG0cnkkUEaA_90.JPG: 480x640 (no detections), 299.2ms
Speed: 1.5ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVOyCM-xQUNoG0cnkkUEaA_180.JPG: 480x640 (no detections), 298.6ms
Speed: 1.9ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVOyCM-xQUNoG0cnkkUEaA_270.JPG: 480x640 (no detections), 293.1ms
Speed: 1.1ms preprocess, 293.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVPM8dGCLa8AVPeUi6FMmQ_0.JPG: 480x640 (no detections), 297.7ms
Speed: 1.0ms preprocess, 297.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVPM8dGCLa8AVPeUi6FMmQ_90.JPG: 480x640 (no detections), 294.0ms
Speed: 1.1ms preprocess, 294.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVPM8dGCLa8AVPeUi6FMmQ_180.JPG: 480x640 (no detections), 291.6ms
Speed: 1.1ms preprocess, 291.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVPM8dGCLa8AVPeUi6FMmQ_270.JPG: 480x640 (no detections), 294.5ms
Speed: 1.2ms preprocess, 294.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVRuL2Ay_up08wf2bLQDPA_0.JPG: 480x640 (no detections), 290.6ms
Speed: 1.0ms preprocess, 290.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVRuL2Ay_up08wf2bLQDPA_90.JPG: 480x640 (no detections), 427.5ms
Speed: 1.1ms preprocess, 427.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVRuL2Ay_up08wf2bLQDPA_180.JPG: 480x640 (no detections), 306.8ms
Speed: 1.4ms preprocess, 306.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVRuL2Ay_up08wf2bLQDPA_270.JPG: 480x640 (no detections), 312.8ms
Speed: 1.1ms preprocess, 312.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVZwbtB5HYV8-H30lOJTLA_0.JPG: 480x640 (no detections), 397.5ms
Speed: 1.1ms preprocess, 397.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVZwbtB5HYV8-H30lOJTLA_90.JPG: 480x640 (no detections), 293.4ms
Speed: 1.5ms preprocess, 293.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVZwbtB5HYV8-H30lOJTLA_180.JPG: 480x640 (no detections), 290.4ms
Speed: 1.2ms preprocess, 290.4ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVZwbtB5HYV8-H30lOJTLA_270.JPG: 480x640 (no detections), 295.3ms
Speed: 1.1ms preprocess, 295.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xV_ZdCds0HLFC3GzHHrTaQ_0.JPG: 480x640 (no detections), 296.2ms
Speed: 1.3ms preprocess, 296.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xV_ZdCds0HLFC3GzHHrTaQ_90.JPG: 480x640 (no detections), 300.8ms
Speed: 1.4ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xV_ZdCds0HLFC3GzHHrTaQ_180.JPG: 480x640 (no detections), 305.2ms
Speed: 1.8ms preprocess, 305.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xV_ZdCds0HLFC3GzHHrTaQ_270.JPG: 480x640 (no detections), 309.8ms
Speed: 1.1ms preprocess, 309.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVaJ1wggSKhh_-az6qnr4w_0.JPG: 480x640 (no detections), 300.2ms
Speed: 1.1ms preprocess, 300.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVaJ1wggSKhh_-az6qnr4w_90.JPG: 480x640 (no detections), 296.5ms
Speed: 1.2ms preprocess, 296.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVaJ1wggSKhh_-az6qnr4w_180.JPG: 480x640 (no detections), 300.8ms
Speed: 1.2ms preprocess, 300.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVaJ1wggSKhh_-az6qnr4w_270.JPG: 480x640 (no detections), 306.4ms
Speed: 1.0ms preprocess, 306.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVaQ6Mcmq9YEMC29aczCJQ_0.JPG: 480x640 (no detections), 301.5ms
Speed: 1.6ms preprocess, 301.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVaQ6Mcmq9YEMC29aczCJQ_90.JPG: 480x640 (no detections), 301.3ms
Speed: 1.2ms preprocess, 301.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVaQ6Mcmq9YEMC29aczCJQ_180.JPG: 480x640 (no detections), 295.4ms
Speed: 1.1ms preprocess, 295.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVaQ6Mcmq9YEMC29aczCJQ_270.JPG: 480x640 (no detections), 289.0ms
Speed: 1.2ms preprocess, 289.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVdbeAOTtWEQockFncZSNg_0.JPG: 480x640 1 Waste, 289.3ms
Speed: 1.1ms preprocess, 289.3ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVdbeAOTtWEQockFncZSNg_90.JPG: 480x640 (no detections), 297.7ms
Speed: 1.7ms preprocess, 297.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVdbeAOTtWEQockFncZSNg_180.JPG: 480x640 (no detections), 300.8ms
Speed: 1.3ms preprocess, 300.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVdbeAOTtWEQockFncZSNg_270.JPG: 480x640 (no detections), 300.0ms
Speed: 1.3ms preprocess, 300.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVfXy3WP4MHV337HF45ShQ_0.JPG: 480x640 (no detections), 299.2ms
Speed: 1.2ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVfXy3WP4MHV337HF45ShQ_90.JPG: 480x640 (no detections), 303.2ms
Speed: 1.0ms preprocess, 303.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVfXy3WP4MHV337HF45ShQ_180.JPG: 480x640 (no detections), 300.3ms

Speed: 1.4ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVfXy3WP4MHV337HF45ShQ_270.JPG: 480x640 (no detections), 301.9ms
Speed: 1.0ms preprocess, 301.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVgtaj5s2hYqkdIcaYoMqw_0.JPG: 480x640 (no detections), 300.7ms
Speed: 1.3ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVgtaj5s2hYqkdIcaYoMqw_90.JPG: 480x640 (no detections), 302.3ms
Speed: 2.1ms preprocess, 302.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVgtaj5s2hYqkdIcaYoMqw_180.JPG: 480x640 (no detections), 305.3ms
Speed: 1.2ms preprocess, 305.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVgtaj5s2hYqkdIcaYoMqw_270.JPG: 480x640 (no detections), 302.4ms
Speed: 1.2ms preprocess, 302.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVhGGxNjuLSw4kGamQgdUQ_0.JPG: 480x640 (no detections), 302.8ms
Speed: 1.1ms preprocess, 302.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVhGGxNjuLSw4kGamQgdUQ_90.JPG: 480x640 (no detections), 307.7ms
Speed: 1.2ms preprocess, 307.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVhGGxNjuLSw4kGamQgdUQ_180.JPG: 480x640 (no detections), 300.7ms
Speed: 1.5ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVhGGxNjuLSw4kGamQgdUQ_270.JPG: 480x640 (no detections), 299.9ms
Speed: 1.6ms preprocess, 299.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVm3IVQfgyHtCvIIuyvQCQ_0.JPG: 480x640 (no detections), 297.9ms
Speed: 1.1ms preprocess, 297.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVm3IVQfgyHtCvIIuyvQCQ_90.JPG: 480x640 (no detections), 304.3ms
Speed: 1.3ms preprocess, 304.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVm3IVQfgyHtCvIIuyvQCQ_180.JPG: 480x640 (no detections), 301.8ms
Speed: 1.1ms preprocess, 301.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVm3IVQfgyHtCvIIuyvQCQ_270.JPG: 480x640 (no detections), 300.0ms
Speed: 1.2ms preprocess, 300.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVniUvfre8UABcPDZmw7pQ_0.JPG: 480x640 (no detections), 305.2ms
Speed: 1.7ms preprocess, 305.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVniUvfre8UABcPDZmw7pQ_90.JPG: 480x640 (no detections), 297.8ms
Speed: 1.1ms preprocess, 297.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVniUvfre8UABcPDZmw7pQ_180.JPG: 480x640 (no detections), 302.2ms
Speed: 1.0ms preprocess, 302.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVniUvfre8UABcPDZmw7pQ_270.JPG: 480x640 (no detections), 302.7ms
Speed: 1.3ms preprocess, 302.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVs2OlECkGKrJ3TzM_dqKw_0.JPG: 480x640 (no detections), 305.9ms
Speed: 1.1ms preprocess, 305.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVs2OlECkGKrJ3TzM_dqKw_90.JPG: 480x640 (no detections), 298.1ms
Speed: 1.2ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVs2OlECkGKrJ3TzM_dqKw_180.JPG: 480x640 (no detections), 305.8ms
Speed: 1.1ms preprocess, 305.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVs2OlECkGKrJ3TzM_dqKw_270.JPG: 480x640 (no detections), 303.1ms
Speed: 1.3ms preprocess, 303.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVtXQ95FQvD4hNEEEKdHBA_0.JPG: 480x640 (no detections), 304.5ms
Speed: 1.2ms preprocess, 304.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVtXQ95FQvD4hNEEEKdHBA_90.JPG: 480x640 (no detections), 302.0ms
Speed: 1.1ms preprocess, 302.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVtXQ95FQvD4hNEEEKdHBA_180.JPG: 480x640 (no detections), 297.0ms
Speed: 1.1ms preprocess, 297.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVtXQ95FQvD4hNEEEKdHBA_270.JPG: 480x640 (no detections), 304.4ms
Speed: 1.1ms preprocess, 304.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVxNIUeMhzJj6_7Q7MTqMA_0.JPG: 480x640 (no detections), 303.1ms
Speed: 1.3ms preprocess, 303.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVxNIUeMhzJj6_7Q7MTqMA_90.JPG: 480x640 (no detections), 298.6ms
Speed: 1.1ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVxNIUeMhzJj6_7Q7MTqMA_180.JPG: 480x640 (no detections), 300.9ms
Speed: 1.1ms preprocess, 300.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVxNIUeMhzJj6_7Q7MTqMA_270.JPG: 480x640 (no detections), 300.0ms
Speed: 1.1ms preprocess, 300.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVxdxSHJFQx_otlMBxbCCw_0.JPG: 480x640 (no detections), 300.3ms
Speed: 1.2ms preprocess, 300.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVxdxSHJFQx_otlMBxbCCw_90.JPG: 480x640 1 Waste, 304.4ms
Speed: 1.2ms preprocess, 304.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVxdxSHJFQx_otlMBxbCCw_180.JPG: 480x640 1 Waste, 298.4ms
Speed: 1.3ms preprocess, 298.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVxdxSHJFQx_otlMBxbCCw_270.JPG: 480x640 (no detections), 297.1ms
Speed: 1.4ms preprocess, 297.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVyB3lBZl9bhQWqmA2ftTQ_0.JPG: 480x640 (no detections), 300.1ms
Speed: 1.3ms preprocess, 300.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVyB3lBZl9bhQWqmA2ftTQ_90.JPG: 480x640 (no detections), 301.6ms
Speed: 1.1ms preprocess, 301.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVyB3lBZl9bhQWqmA2ftTQ_180.JPG: 480x640 (no detections), 304.9ms
Speed: 1.4ms preprocess, 304.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xVyB3lBZl9bhQWqmA2ftTQ_270.JPG: 480x640 (no detections), 301.7ms
Speed: 1.3ms preprocess, 301.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xW3adxhrfwuRTYWn1rwCHA_0.JPG: 480x640 (no detections), 306.3ms
Speed: 1.3ms preprocess, 306.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xW3adxhrfwuRTYWn1rwCHA_90.JPG: 480x640 (no detections), 305.4ms
Speed: 1.5ms preprocess, 305.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xW3adxhrfwuRTYWn1rwCHA_180.JPG: 480x640 (no detections), 299.5ms
Speed: 1.1ms preprocess, 299.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xW3adxhrfwuRTYWn1rwCHA_270.JPG: 480x640 (no detections), 304.1ms
Speed: 1.0ms preprocess, 304.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xW7hHdS3ef0uoy4wXjlp_w_0.JPG: 480x640 (no detections), 301.7ms
Speed: 1.6ms preprocess, 301.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xW7hHdS3ef0uoy4wXjlp_w_90.JPG: 480x640 (no detections), 302.7ms
Speed: 1.3ms preprocess, 302.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xW7hHdS3ef0uoy4wXjlp_w_180.JPG: 480x640 (no detections), 299.3ms
Speed: 1.7ms preprocess, 299.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xW7hHdS3ef0uoy4wXjlp_w_270.JPG: 480x640 (no detections), 304.2ms
Speed: 1.1ms preprocess, 304.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xW8m0cXcTZpthXxjCaWfVw_0.JPG: 480x640 (no detections), 299.2ms
Speed: 1.4ms preprocess, 299.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xW8m0cXcTZpthXxjCaWfVw_90.JPG: 480x640 (no detections), 300.2ms
Speed: 1.1ms preprocess, 300.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xW8m0cXcTZpthXxjCaWfVw_180.JPG: 480x640 (no detections), 307.6ms
Speed: 1.1ms preprocess, 307.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xW8m0cXcTZpthXxjCaWfVw_270.JPG: 480x640 (no detections), 301.9ms
Speed: 1.1ms preprocess, 301.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWAedXp8qnHWMV4MBuNsAQ_0.JPG: 480x640 (no detections), 305.5ms
Speed: 1.1ms preprocess, 305.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWAedXp8qnHWMV4MBuNsAQ_90.JPG: 480x640 (no detections), 299.0ms
Speed: 1.5ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWAedXp8qnHWMV4MBuNsAQ_180.JPG: 480x640 (no detections), 301.2ms
Speed: 1.3ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWAedXp8qnHWMV4MBuNsAQ_270.JPG: 480x640 (no detections), 299.3ms
Speed: 1.2ms preprocess, 299.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWCd_ErlkfM2y4ZS1i-zkA_0.JPG: 480x640 (no detections), 294.5ms
Speed: 1.3ms preprocess, 294.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWCd_ErlkfM2y4ZS1i-zkA_90.JPG: 480x640 (no detections), 296.4ms
Speed: 1.1ms preprocess, 296.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWCd_ErlkfM2y4ZS1i-zkA_180.JPG: 480x640 (no detections), 302.0ms
Speed: 1.1ms preprocess, 302.0ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWCd_ErlkfM2y4ZS1i-zkA_270.JPG: 480x640 (no detections), 300.4ms
Speed: 1.4ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWDHlMSGEQhids2kEh5NCA_0.JPG: 480x640 (no detections), 304.4ms
Speed: 1.5ms preprocess, 304.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWDHlMSGEQhids2kEh5NCA_90.JPG: 480x640 (no detections), 301.2ms
Speed: 1.2ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWDHlMSGEQhids2kEh5NCA_180.JPG: 480x640 (no detections), 297.6ms
Speed: 1.1ms preprocess, 297.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWDHlMSGEQhids2kEh5NCA_270.JPG: 480x640 (no detections), 298.1ms
Speed: 1.1ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWDpVwg4g-QoseQTSOK3ZQ_0.JPG: 480x640 (no detections), 297.3ms
Speed: 1.0ms preprocess, 297.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWDpVwg4g-QoseQTSOK3ZQ_90.JPG: 480x640 (no detections), 304.9ms
Speed: 1.1ms preprocess, 304.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWDpVwg4g-QoseQTSOK3ZQ_180.JPG: 480x640 (no detections), 303.3ms
Speed: 1.2ms preprocess, 303.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWDpVwg4g-QoseQTSOK3ZQ_270.JPG: 480x640 (no detections), 303.1ms
Speed: 1.2ms preprocess, 303.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWI0TkzC3LccXGTgkOW12A_0.JPG: 480x640 (no detections), 296.5ms
Speed: 1.2ms preprocess, 296.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWI0TkzC3LccXGTgkOW12A_90.JPG: 480x640 (no detections), 299.0ms

Speed: 1.1ms preprocess, 299.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWI0TkzC3LccXGTgkOW12A_180.JPG: 480x640 (no detections), 300.4ms
Speed: 1.2ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWI0TkzC3LccXGTgkOW12A_270.JPG: 480x640 (no detections), 305.7ms
Speed: 1.2ms preprocess, 305.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWO2C_ADpmHD-H8m7Ezd-A_0.JPG: 480x640 (no detections), 297.2ms
Speed: 1.1ms preprocess, 297.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWO2C_ADpmHD-H8m7Ezd-A_90.JPG: 480x640 (no detections), 303.6ms
Speed: 1.3ms preprocess, 303.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWO2C_ADpmHD-H8m7Ezd-A_180.JPG: 480x640 (no detections), 300.5ms
Speed: 1.2ms preprocess, 300.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWO2C_ADpmHD-H8m7Ezd-A_270.JPG: 480x640 (no detections), 298.1ms
Speed: 1.1ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWOhuShCsjLjrYfzyUB11A_0.JPG: 480x640 (no detections), 303.4ms
Speed: 1.1ms preprocess, 303.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWOhuShCsjLjrYfzyUB11A_90.JPG: 480x640 (no detections), 299.2ms
Speed: 1.2ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWOhuShCsjLjrYfzyUB11A_180.JPG: 480x640 (no detections), 302.3ms
Speed: 1.2ms preprocess, 302.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWOhuShCsjLjrYfzyUB11A_270.JPG: 480x640 (no detections), 293.4ms
Speed: 1.1ms preprocess, 293.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWUWnNXLu_lch7Fna7MlDw_0.JPG: 480x640 (no detections), 293.9ms
Speed: 1.0ms preprocess, 293.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWUWnNXLu_lch7Fna7MlDw_90.JPG: 480x640 (no detections), 302.5ms
Speed: 1.1ms preprocess, 302.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWUWnNXLu_lch7Fna7MlDw_180.JPG: 480x640 (no detections), 299.9ms
Speed: 1.2ms preprocess, 299.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWUWnNXLu_lch7Fna7MlDw_270.JPG: 480x640 (no detections), 300.9ms
Speed: 1.2ms preprocess, 300.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWWunPtF-PGLV3KXtris_A_0.JPG: 480x640 (no detections), 302.7ms
Speed: 1.1ms preprocess, 302.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWWunPtF-PGLV3KXtris_A_90.JPG: 480x640 (no detections), 304.0ms
Speed: 1.4ms preprocess, 304.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWWunPtF-PGLV3KXtris_A_180.JPG: 480x640 (no detections), 302.2ms
Speed: 1.1ms preprocess, 302.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWWunPtF-PGLV3KXtris_A_270.JPG: 480x640 (no detections), 297.5ms
Speed: 1.2ms preprocess, 297.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWYW9zh1KyBpwq_adyPdyw_0.JPG: 480x640 (no detections), 300.8ms
Speed: 1.3ms preprocess, 300.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWYW9zh1KyBpwq_adyPdyw_90.JPG: 480x640 (no detections), 304.7ms
Speed: 1.2ms preprocess, 304.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWYW9zh1KyBpwq_adyPdyw_180.JPG: 480x640 (no detections), 302.2ms
Speed: 1.2ms preprocess, 302.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWYW9zh1KyBpwq_adyPdyw_270.JPG: 480x640 (no detections), 302.6ms
Speed: 1.2ms preprocess, 302.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWa5-nfqlT4tf-i6bFnNLA_0.JPG: 480x640 (no detections), 298.2ms
Speed: 1.2ms preprocess, 298.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWa5-nfqlT4tf-i6bFnNLA_90.JPG: 480x640 (no detections), 303.5ms
Speed: 1.2ms preprocess, 303.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWa5-nfqlT4tf-i6bFnNLA_180.JPG: 480x640 (no detections), 292.9ms
Speed: 1.1ms preprocess, 292.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWa5-nfqlT4tf-i6bFnNLA_270.JPG: 480x640 (no detections), 304.3ms
Speed: 1.8ms preprocess, 304.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWa_D4r_D14rHIB3SdaBSg_0.JPG: 480x640 (no detections), 296.7ms
Speed: 1.1ms preprocess, 296.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWa_D4r_D14rHIB3SdaBSg_90.JPG: 480x640 (no detections), 300.5ms
Speed: 1.1ms preprocess, 300.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWa_D4r_D14rHIB3SdaBSg_180.JPG: 480x640 (no detections), 305.7ms
Speed: 1.1ms preprocess, 305.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWa_D4r_D14rHIB3SdaBSg_270.JPG: 480x640 (no detections), 304.3ms
Speed: 1.1ms preprocess, 304.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWctSLh_Jk9kWotNkeRTwQ_0.JPG: 480x640 (no detections), 300.7ms
Speed: 1.1ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWctSLh_Jk9kWotNkeRTwQ_90.JPG: 480x640 (no detections), 302.6ms
Speed: 1.4ms preprocess, 302.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWctSLh_Jk9kWotNkeRTwQ_180.JPG: 480x640 (no detections), 299.5ms
Speed: 1.2ms preprocess, 299.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWctSLh_Jk9kWotNkeRTwQ_270.JPG: 480x640 (no detections), 304.4ms
Speed: 1.1ms preprocess, 304.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWdFKSIuDy2KVhE96AwNkw_0.JPG: 480x640 (no detections), 301.2ms
Speed: 1.2ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWdFKSIuDy2KVhE96AwNkw_90.JPG: 480x640 (no detections), 304.0ms
Speed: 1.3ms preprocess, 304.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWdFKSIuDy2KVhE96AwNkw_180.JPG: 480x640 (no detections), 299.4ms
Speed: 1.2ms preprocess, 299.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWdFKSIuDy2KVhE96AwNkw_270.JPG: 480x640 (no detections), 295.6ms
Speed: 1.1ms preprocess, 295.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWgNr5EQ4iefNDjEUNCLeQ_0.JPG: 480x640 (no detections), 298.0ms
Speed: 1.1ms preprocess, 298.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWgNr5EQ4iefNDjEUNCLeQ_90.JPG: 480x640 (no detections), 302.9ms
Speed: 1.1ms preprocess, 302.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWgNr5EQ4iefNDjEUNCLeQ_180.JPG: 480x640 (no detections), 300.1ms
Speed: 1.1ms preprocess, 300.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWgNr5EQ4iefNDjEUNCLeQ_270.JPG: 480x640 (no detections), 302.8ms
Speed: 1.2ms preprocess, 302.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWh0JCj71sZRIir1r7n2uw_0.JPG: 480x640 1 Waste, 299.3ms
Speed: 1.2ms preprocess, 299.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWh0JCj71sZRIir1r7n2uw_90.JPG: 480x640 (no detections), 297.6ms
Speed: 1.2ms preprocess, 297.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWh0JCj71sZRIir1r7n2uw_180.JPG: 480x640 (no detections), 303.1ms
Speed: 1.3ms preprocess, 303.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWh0JCj71sZRIir1r7n2uw_270.JPG: 480x640 (no detections), 303.1ms
Speed: 1.4ms preprocess, 303.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWh4uau1yjmA4bL6BKnEAw_0.JPG: 480x640 (no detections), 299.0ms
Speed: 1.2ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWh4uau1yjmA4bL6BKnEAw_90.JPG: 480x640 (no detections), 302.5ms
Speed: 1.2ms preprocess, 302.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWh4uau1yjmA4bL6BKnEAw_180.JPG: 480x640 (no detections), 297.4ms
Speed: 1.2ms preprocess, 297.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWh4uau1yjmA4bL6BKnEAw_270.JPG: 480x640 (no detections), 305.2ms
Speed: 1.2ms preprocess, 305.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWi_W9oGxulPENVkhZLFdw_0.JPG: 480x640 (no detections), 294.5ms
Speed: 1.9ms preprocess, 294.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWi_W9oGxulPENVkhZLFdw_90.JPG: 480x640 (no detections), 304.0ms
Speed: 1.2ms preprocess, 304.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWi_W9oGxulPENVkhZLFdw_180.JPG: 480x640 (no detections), 300.6ms
Speed: 1.2ms preprocess, 300.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWi_W9oGxulPENVkhZLFdw_270.JPG: 480x640 (no detections), 299.2ms
Speed: 1.1ms preprocess, 299.2ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWnt9fVGscCdKAdBcKUDdA_0.JPG: 480x640 (no detections), 301.7ms
Speed: 1.4ms preprocess, 301.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWnt9fVGscCdKAdBcKUDdA_90.JPG: 480x640 (no detections), 306.3ms
Speed: 1.2ms preprocess, 306.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWnt9fVGscCdKAdBcKUDdA_180.JPG: 480x640 (no detections), 298.8ms
Speed: 1.2ms preprocess, 298.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWnt9fVGscCdKAdBcKUDdA_270.JPG: 480x640 (no detections), 303.7ms
Speed: 1.1ms preprocess, 303.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWo2Vkbpoh3YR690n1HOMg_0.JPG: 480x640 (no detections), 300.4ms
Speed: 1.2ms preprocess, 300.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWo2Vkbpoh3YR690n1HOMg_90.JPG: 480x640 (no detections), 297.6ms
Speed: 1.3ms preprocess, 297.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWo2Vkbpoh3YR690n1HOMg_180.JPG: 480x640 (no detections), 298.4ms
Speed: 1.3ms preprocess, 298.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWo2Vkbpoh3YR690n1HOMg_270.JPG: 480x640 (no detections), 301.3ms
Speed: 1.3ms preprocess, 301.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWog2jZ6KklNowxLBdsUUQ_0.JPG: 480x640 (no detections), 305.6ms
Speed: 1.2ms preprocess, 305.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWog2jZ6KklNowxLBdsUUQ_90.JPG: 480x640 (no detections), 296.6ms
Speed: 1.3ms preprocess, 296.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWog2jZ6KklNowxLBdsUUQ_180.JPG: 480x640 (no detections), 298.7ms
Speed: 1.2ms preprocess, 298.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWog2jZ6KklNowxLBdsUUQ_270.JPG: 480x640 (no detections), 297.6ms
Speed: 1.2ms preprocess, 297.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWr1l8ShFAt5C6WJqFsEug_0.JPG: 480x640 (no detections), 303.2ms

Speed: 1.4ms preprocess, 303.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWr1l8ShFAt5C6WJqFsEug_90.JPG: 480x640 (no detections), 301.7ms
Speed: 1.2ms preprocess, 301.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWr1l8ShFAt5C6WJqFsEug_180.JPG: 480x640 (no detections), 307.7ms
Speed: 1.1ms preprocess, 307.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWr1l8ShFAt5C6WJqFsEug_270.JPG: 480x640 (no detections), 304.5ms
Speed: 1.3ms preprocess, 304.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWttY2RNEWXRxwWoD61SXg_0.JPG: 480x640 (no detections), 303.5ms
Speed: 2.1ms preprocess, 303.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWttY2RNEWXRxwWoD61SXg_90.JPG: 480x640 (no detections), 304.7ms
Speed: 1.3ms preprocess, 304.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWttY2RNEWXRxwWoD61SXg_180.JPG: 480x640 (no detections), 300.3ms
Speed: 1.4ms preprocess, 300.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xWttY2RNEWXRxwWoD61SXg_270.JPG: 480x640 (no detections), 298.0ms
Speed: 1.4ms preprocess, 298.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xX1OeU02m4CkHoiO1yFaXg_0.JPG: 480x640 (no detections), 301.3ms
Speed: 1.3ms preprocess, 301.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xX1OeU02m4CkHoiO1yFaXg_90.JPG: 480x640 (no detections), 301.6ms
Speed: 1.1ms preprocess, 301.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xX1OeU02m4CkHoiO1yFaXg_180.JPG: 480x640 (no detections), 300.3ms
Speed: 1.2ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xX1OeU02m4CkHoiO1yFaXg_270.JPG: 480x640 1 Waste, 308.0ms
Speed: 1.3ms preprocess, 308.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xX1vPVVg4NJSIcY2UM1wqg_0.JPG: 480x640 (no detections), 301.0ms
Speed: 1.6ms preprocess, 301.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xX1vPVVg4NJSIcY2UM1wqg_90.JPG: 480x640 (no detections), 298.5ms
Speed: 1.1ms preprocess, 298.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xX1vPVVg4NJSIcY2UM1wqg_180.JPG: 480x640 (no detections), 302.2ms
Speed: 1.5ms preprocess, 302.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xX1vPVVg4NJSIcY2UM1wqg_270.JPG: 480x640 (no detections), 301.4ms
Speed: 1.2ms preprocess, 301.4ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xX3MFX_ge_OMfjOgMAyd5A_0.JPG: 480x640 (no detections), 300.9ms
Speed: 1.1ms preprocess, 300.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xX3MFX_ge_OMfjOgMAyd5A_90.JPG: 480x640 (no detections), 297.2ms
Speed: 1.4ms preprocess, 297.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xX3MFX_ge_OMfjOgMAyd5A_180.JPG: 480x640 (no detections), 300.3ms
Speed: 1.7ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xX3MFX_ge_OMfjOgMAyd5A_270.JPG: 480x640 (no detections), 302.9ms
Speed: 1.1ms preprocess, 302.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xX63UOO9w1K6nTFiKsFvwg_0.JPG: 480x640 (no detections), 299.2ms
Speed: 1.0ms preprocess, 299.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xX63UOO9w1K6nTFiKsFvwg_90.JPG: 480x640 (no detections), 307.3ms
Speed: 1.0ms preprocess, 307.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xX63UOO9w1K6nTFiKsFvwg_180.JPG: 480x640 (no detections), 303.4ms
Speed: 1.3ms preprocess, 303.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xX63UOO9w1K6nTFiKsFvwg_270.JPG: 480x640 (no detections), 300.3ms
Speed: 1.1ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xX7_uPcPDZcNP-mQlvzq8Q_0.JPG: 480x640 (no detections), 302.3ms
Speed: 1.1ms preprocess, 302.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xX7_uPcPDZcNP-mQlvzq8Q_90.JPG: 480x640 (no detections), 303.0ms
Speed: 1.2ms preprocess, 303.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xX7_uPcPDZcNP-mQlvzq8Q_180.JPG: 480x640 (no detections), 300.5ms
Speed: 1.2ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xX7_uPcPDZcNP-mQlvzq8Q_270.JPG: 480x640 (no detections), 311.6ms
Speed: 1.2ms preprocess, 311.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xX9IW5rwokNGuMyyDKGvtA_0.JPG: 480x640 (no detections), 298.3ms
Speed: 1.2ms preprocess, 298.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xX9IW5rwokNGuMyyDKGvtA_90.JPG: 480x640 (no detections), 301.7ms
Speed: 1.1ms preprocess, 301.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xX9IW5rwokNGuMyyDKGvtA_180.JPG: 480x640 1 Waste, 303.0ms
Speed: 1.3ms preprocess, 303.0ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xX9IW5rwokNGuMyyDKGvtA_270.JPG: 480x640 (no detections), 302.3ms
Speed: 1.6ms preprocess, 302.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xX9tDNWlY1Z79AqwsTHLmw_0.JPG: 480x640 (no detections), 302.0ms
Speed: 1.3ms preprocess, 302.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xX9tDNWlY1Z79AqwsTHLmw_90.JPG: 480x640 (no detections), 301.5ms
Speed: 1.3ms preprocess, 301.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xX9tDNWlY1Z79AqwsTHLmw_180.JPG: 480x640 (no detections), 302.8ms
Speed: 1.2ms preprocess, 302.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xX9tDNWlY1Z79AqwsTHLmw_270.JPG: 480x640 (no detections), 299.4ms
Speed: 1.1ms preprocess, 299.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXA82iPc4KzTR6rBF0Lipw_0.JPG: 480x640 (no detections), 300.5ms
Speed: 1.8ms preprocess, 300.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXA82iPc4KzTR6rBF0Lipw_90.JPG: 480x640 (no detections), 296.9ms
Speed: 1.4ms preprocess, 296.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXA82iPc4KzTR6rBF0Lipw_180.JPG: 480x640 (no detections), 301.3ms
Speed: 1.1ms preprocess, 301.3ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXA82iPc4KzTR6rBF0Lipw_270.JPG: 480x640 (no detections), 295.3ms
Speed: 1.0ms preprocess, 295.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXACzWsLGQ_JtOZVw5Aq_Q_0.JPG: 480x640 (no detections), 309.2ms
Speed: 1.2ms preprocess, 309.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXACzWsLGQ_JtOZVw5Aq_Q_90.JPG: 480x640 (no detections), 300.6ms
Speed: 1.2ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXACzWsLGQ_JtOZVw5Aq_Q_180.JPG: 480x640 (no detections), 301.3ms
Speed: 1.1ms preprocess, 301.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXACzWsLGQ_JtOZVw5Aq_Q_270.JPG: 480x640 (no detections), 300.1ms
Speed: 1.2ms preprocess, 300.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXCAw1FxZh9YSYPhO6joQg_0.JPG: 480x640 (no detections), 300.9ms
Speed: 1.2ms preprocess, 300.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXCAw1FxZh9YSYPhO6joQg_90.JPG: 480x640 (no detections), 297.5ms
Speed: 1.2ms preprocess, 297.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXCAw1FxZh9YSYPhO6joQg_180.JPG: 480x640 (no detections), 306.8ms
Speed: 1.4ms preprocess, 306.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXCAw1FxZh9YSYPhO6joQg_270.JPG: 480x640 (no detections), 297.4ms
Speed: 1.2ms preprocess, 297.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXDZdEMrJ1dvwT_ZcktJBQ_0.JPG: 480x640 (no detections), 297.6ms
Speed: 1.1ms preprocess, 297.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXDZdEMrJ1dvwT_ZcktJBQ_90.JPG: 480x640 (no detections), 301.3ms
Speed: 1.6ms preprocess, 301.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXDZdEMrJ1dvwT_ZcktJBQ_180.JPG: 480x640 (no detections), 302.0ms
Speed: 1.1ms preprocess, 302.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXDZdEMrJ1dvwT_ZcktJBQ_270.JPG: 480x640 1 Waste, 304.2ms
Speed: 1.2ms preprocess, 304.2ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXKEKnO9ZAPIQjykuM43-A_0.JPG: 480x640 (no detections), 303.7ms
Speed: 1.3ms preprocess, 303.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXKEKnO9ZAPIQjykuM43-A_90.JPG: 480x640 1 Waste, 301.7ms
Speed: 1.4ms preprocess, 301.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXKEKnO9ZAPIQjykuM43-A_180.JPG: 480x640 (no detections), 306.5ms
Speed: 1.4ms preprocess, 306.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXKEKnO9ZAPIQjykuM43-A_270.JPG: 480x640 (no detections), 302.2ms
Speed: 1.1ms preprocess, 302.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXLW93VDdOkaEWigk_FQGw_0.JPG: 480x640 (no detections), 301.0ms
Speed: 1.5ms preprocess, 301.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXLW93VDdOkaEWigk_FQGw_90.JPG: 480x640 1 Waste, 294.8ms
Speed: 1.1ms preprocess, 294.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXLW93VDdOkaEWigk_FQGw_180.JPG: 480x640 (no detections), 300.7ms
Speed: 1.2ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXLW93VDdOkaEWigk_FQGw_270.JPG: 480x640 (no detections), 295.8ms
Speed: 1.2ms preprocess, 295.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXMEZ6jhu3x5-wKPz1_jUQ_0.JPG: 480x640 (no detections), 298.8ms
Speed: 1.0ms preprocess, 298.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXMEZ6jhu3x5-wKPz1_jUQ_90.JPG: 480x640 (no detections), 297.7ms
Speed: 1.1ms preprocess, 297.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXMEZ6jhu3x5-wKPz1_jUQ_180.JPG: 480x640 (no detections), 307.7ms
Speed: 1.2ms preprocess, 307.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXMEZ6jhu3x5-wKPz1_jUQ_270.JPG: 480x640 (no detections), 303.6ms
Speed: 1.4ms preprocess, 303.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXMYwwKylPrWdzgmgAVuhA_0.JPG: 480x640 (no detections), 301.3ms
Speed: 1.3ms preprocess, 301.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXMYwwKylPrWdzgmgAVuhA_90.JPG: 480x640 (no detections), 300.5ms
Speed: 1.3ms preprocess, 300.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXMYwwKylPrWdzgmgAVuhA_180.JPG: 480x640 (no detections), 296.6ms
Speed: 1.2ms preprocess, 296.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXMYwwKylPrWdzgmgAVuhA_270.JPG: 480x640 (no detections), 305.9ms

Speed: 1.3ms preprocess, 305.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXQOaMyKYlCiBDQ2MmlZJQ_0.JPG: 480x640 (no detections), 301.2ms
Speed: 1.3ms preprocess, 301.2ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXQOaMyKYlCiBDQ2MmlZJQ_90.JPG: 480x640 (no detections), 297.5ms
Speed: 1.6ms preprocess, 297.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXQOaMyKYlCiBDQ2MmlZJQ_180.JPG: 480x640 (no detections), 298.3ms
Speed: 1.2ms preprocess, 298.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXQOaMyKYlCiBDQ2MmlZJQ_270.JPG: 480x640 (no detections), 296.3ms
Speed: 1.3ms preprocess, 296.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXWUwWPJwtL7Ay71cSIRTA_0.JPG: 480x640 (no detections), 298.2ms
Speed: 1.1ms preprocess, 298.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXWUwWPJwtL7Ay71cSIRTA_90.JPG: 480x640 (no detections), 300.8ms
Speed: 1.3ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXWUwWPJwtL7Ay71cSIRTA_180.JPG: 480x640 (no detections), 305.3ms
Speed: 1.1ms preprocess, 305.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXWUwWPJwtL7Ay71cSIRTA_270.JPG: 480x640 (no detections), 290.6ms
Speed: 1.3ms preprocess, 290.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXXHB_UmzhHFOpeLTml9bw_0.JPG: 480x640 (no detections), 305.7ms
Speed: 1.9ms preprocess, 305.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXXHB_UmzhHFOpeLTml9bw_90.JPG: 480x640 (no detections), 303.9ms
Speed: 1.6ms preprocess, 303.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXXHB_UmzhHFOpeLTml9bw_180.JPG: 480x640 (no detections), 302.0ms
Speed: 1.5ms preprocess, 302.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXXHB_UmzhHFOpeLTml9bw_270.JPG: 480x640 (no detections), 300.9ms
Speed: 1.9ms preprocess, 300.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xX_7MuRKfwPYSQkbYzz1lQ_0.JPG: 480x640 (no detections), 298.6ms
Speed: 1.2ms preprocess, 298.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xX_7MuRKfwPYSQkbYzz1lQ_90.JPG: 480x640 (no detections), 300.8ms
Speed: 1.4ms preprocess, 300.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xX_7MuRKfwPYSQkbYzz1lQ_180.JPG: 480x640 1 Waste, 299.3ms
Speed: 1.1ms preprocess, 299.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xX_7MuRKfwPYSQkbYzz1lQ_270.JPG: 480x640 (no detections), 297.8ms
Speed: 1.4ms preprocess, 297.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXaZRIsU-ZXLIJ6sURjWYQ_0.JPG: 480x640 (no detections), 297.3ms
Speed: 1.3ms preprocess, 297.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXaZRIsU-ZXLIJ6sURjWYQ_90.JPG: 480x640 (no detections), 300.0ms
Speed: 1.6ms preprocess, 300.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXaZRIsU-ZXLIJ6sURjWYQ_180.JPG: 480x640 (no detections), 303.3ms
Speed: 1.2ms preprocess, 303.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXaZRIsU-ZXLIJ6sURjWYQ_270.JPG: 480x640 (no detections), 298.7ms
Speed: 1.2ms preprocess, 298.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXb9pqvI3mRb2F2nxlF4nA_0.JPG: 480x640 (no detections), 295.3ms
Speed: 1.1ms preprocess, 295.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXb9pqvI3mRb2F2nxlF4nA_90.JPG: 480x640 (no detections), 303.2ms
Speed: 1.4ms preprocess, 303.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXb9pqvI3mRb2F2nxlF4nA_180.JPG: 480x640 (no detections), 299.0ms
Speed: 1.8ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXb9pqvI3mRb2F2nxlF4nA_270.JPG: 480x640 (no detections), 301.8ms
Speed: 1.3ms preprocess, 301.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXckvw4OGvezdTcJb-F1XQ_0.JPG: 480x640 1 Waste, 300.7ms
Speed: 1.1ms preprocess, 300.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXckvw4OGvezdTcJb-F1XQ_90.JPG: 480x640 (no detections), 298.7ms
Speed: 1.3ms preprocess, 298.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXckvw4OGvezdTcJb-F1XQ_180.JPG: 480x640 (no detections), 295.3ms
Speed: 1.4ms preprocess, 295.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXckvw4OGvezdTcJb-F1XQ_270.JPG: 480x640 1 Waste, 298.3ms
Speed: 1.1ms preprocess, 298.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXdi7UG7judhMU-JjmzJjw_0.JPG: 480x640 (no detections), 303.5ms
Speed: 1.1ms preprocess, 303.5ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXdi7UG7judhMU-JjmzJjw_90.JPG: 480x640 (no detections), 301.9ms
Speed: 1.6ms preprocess, 301.9ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXdi7UG7judhMU-JjmzJjw_180.JPG: 480x640 (no detections), 298.7ms
Speed: 1.2ms preprocess, 298.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXdi7UG7judhMU-JjmzJjw_270.JPG: 480x640 (no detections), 301.6ms
Speed: 1.7ms preprocess, 301.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXdoDCfiEYJHCgRfas1i1A_0.JPG: 480x640 (no detections), 295.8ms
Speed: 1.1ms preprocess, 295.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXdoDCfiEYJHCgRfas1i1A_90.JPG: 480x640 (no detections), 299.7ms
Speed: 1.0ms preprocess, 299.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXdoDCfiEYJHCgRfas1i1A_180.JPG: 480x640 (no detections), 296.6ms
Speed: 1.2ms preprocess, 296.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXdoDCfiEYJHCgRfas1i1A_270.JPG: 480x640 (no detections), 297.3ms
Speed: 1.1ms preprocess, 297.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXeb00vjjwtZSBziNNaUmA_0.JPG: 480x640 (no detections), 301.1ms
Speed: 1.3ms preprocess, 301.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXeb00vjjwtZSBziNNaUmA_90.JPG: 480x640 (no detections), 297.2ms
Speed: 1.3ms preprocess, 297.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXeb00vjjwtZSBziNNaUmA_180.JPG: 480x640 (no detections), 299.0ms
Speed: 1.3ms preprocess, 299.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXeb00vjjwtZSBziNNaUmA_270.JPG: 480x640 (no detections), 301.5ms
Speed: 1.2ms preprocess, 301.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXfjDlaM26ssOShEqc16tg_0.JPG: 480x640 (no detections), 298.4ms
Speed: 1.1ms preprocess, 298.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXfjDlaM26ssOShEqc16tg_90.JPG: 480x640 (no detections), 303.6ms
Speed: 1.2ms preprocess, 303.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXfjDlaM26ssOShEqc16tg_180.JPG: 480x640 (no detections), 298.2ms
Speed: 1.2ms preprocess, 298.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXfjDlaM26ssOShEqc16tg_270.JPG: 480x640 (no detections), 301.7ms
Speed: 1.4ms preprocess, 301.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXh980c5gH6jWPKwsVSGBQ_0.JPG: 480x640 (no detections), 299.1ms
Speed: 1.1ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXh980c5gH6jWPKwsVSGBQ_90.JPG: 480x640 (no detections), 299.7ms
Speed: 1.3ms preprocess, 299.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXh980c5gH6jWPKwsVSGBQ_180.JPG: 480x640 (no detections), 303.9ms
Speed: 1.2ms preprocess, 303.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXh980c5gH6jWPKwsVSGBQ_270.JPG: 480x640 (no detections), 303.4ms
Speed: 1.2ms preprocess, 303.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXlaqIzEvykRlDPwy-Rt2w_0.JPG: 480x640 (no detections), 301.2ms
Speed: 1.0ms preprocess, 301.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXlaqIzEvykRlDPwy-Rt2w_90.JPG: 480x640 (no detections), 300.8ms
Speed: 1.3ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXlaqIzEvykRlDPwy-Rt2w_180.JPG: 480x640 (no detections), 301.5ms
Speed: 1.3ms preprocess, 301.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXlaqIzEvykRlDPwy-Rt2w_270.JPG: 480x640 (no detections), 304.2ms
Speed: 1.2ms preprocess, 304.2ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXpLs8peGpTe6w_LiI999g_0.JPG: 480x640 (no detections), 304.3ms
Speed: 1.6ms preprocess, 304.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXpLs8peGpTe6w_LiI999g_90.JPG: 480x640 (no detections), 293.8ms
Speed: 1.1ms preprocess, 293.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXpLs8peGpTe6w_LiI999g_180.JPG: 480x640 (no detections), 301.8ms
Speed: 1.1ms preprocess, 301.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXpLs8peGpTe6w_LiI999g_270.JPG: 480x640 (no detections), 301.1ms
Speed: 1.1ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXpU4nefj1lGAht4gPF59A_0.JPG: 480x640 (no detections), 296.8ms
Speed: 1.1ms preprocess, 296.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXpU4nefj1lGAht4gPF59A_90.JPG: 480x640 1 Waste, 297.3ms
Speed: 1.1ms preprocess, 297.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXpU4nefj1lGAht4gPF59A_180.JPG: 480x640 (no detections), 291.1ms
Speed: 1.1ms preprocess, 291.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXpU4nefj1lGAht4gPF59A_270.JPG: 480x640 (no detections), 295.7ms
Speed: 1.3ms preprocess, 295.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXpW3dd_rmXoIWb7E7kIOw_0.JPG: 480x640 (no detections), 303.7ms
Speed: 1.4ms preprocess, 303.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXpW3dd_rmXoIWb7E7kIOw_90.JPG: 480x640 (no detections), 300.0ms
Speed: 1.6ms preprocess, 300.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXpW3dd_rmXoIWb7E7kIOw_180.JPG: 480x640 (no detections), 300.8ms
Speed: 1.5ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXpW3dd_rmXoIWb7E7kIOw_270.JPG: 480x640 (no detections), 294.3ms
Speed: 1.1ms preprocess, 294.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXzEtVjKodTMhZFD5mBo0w_0.JPG: 480x640 (no detections), 299.0ms
Speed: 1.2ms preprocess, 299.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXzEtVjKodTMhZFD5mBo0w_90.JPG: 480x640 (no detections), 306.9ms
Speed: 1.2ms preprocess, 306.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXzEtVjKodTMhZFD5mBo0w_180.JPG: 480x640 (no detections), 303.7ms

Speed: 1.2ms preprocess, 303.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xXzEtVjKodTMhZFD5mBo0w_270.JPG: 480x640 (no detections), 298.6ms
Speed: 1.3ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xY0GJVSOqV_3n3KczonFPg_0.JPG: 480x640 (no detections), 302.3ms
Speed: 1.2ms preprocess, 302.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xY0GJVSOqV_3n3KczonFPg_90.JPG: 480x640 (no detections), 295.5ms
Speed: 1.2ms preprocess, 295.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xY0GJVSOqV_3n3KczonFPg_180.JPG: 480x640 (no detections), 297.1ms
Speed: 1.1ms preprocess, 297.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xY0GJVSOqV_3n3KczonFPg_270.JPG: 480x640 (no detections), 298.6ms
Speed: 1.2ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xY0cY1LkMnaG-4pJrFD5ZQ_0.JPG: 480x640 (no detections), 300.9ms
Speed: 1.1ms preprocess, 300.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xY0cY1LkMnaG-4pJrFD5ZQ_90.JPG: 480x640 (no detections), 300.4ms
Speed: 1.1ms preprocess, 300.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xY0cY1LkMnaG-4pJrFD5ZQ_180.JPG: 480x640 (no detections), 297.4ms
Speed: 1.1ms preprocess, 297.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xY0cY1LkMnaG-4pJrFD5ZQ_270.JPG: 480x640 (no detections), 293.9ms
Speed: 1.2ms preprocess, 293.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xY77PDH01rntd34fclL5Dw_0.JPG: 480x640 (no detections), 307.0ms
Speed: 1.0ms preprocess, 307.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xY77PDH01rntd34fclL5Dw_90.JPG: 480x640 (no detections), 298.5ms
Speed: 1.2ms preprocess, 298.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xY77PDH01rntd34fclL5Dw_180.JPG: 480x640 (no detections), 302.1ms
Speed: 1.5ms preprocess, 302.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xY77PDH01rntd34fclL5Dw_270.JPG: 480x640 (no detections), 298.1ms
Speed: 1.3ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xY89SuY1jWkEkyJGjwR4Tg_0.JPG: 480x640 (no detections), 301.4ms
Speed: 1.2ms preprocess, 301.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xY89SuY1jWkEkyJGjwR4Tg_90.JPG: 480x640 (no detections), 296.3ms
Speed: 1.5ms preprocess, 296.3ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xY89SuY1jWkEkyJGjwR4Tg_180.JPG: 480x640 (no detections), 312.4ms
Speed: 1.2ms preprocess, 312.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xY89SuY1jWkEkyJGjwR4Tg_270.JPG: 480x640 (no detections), 298.5ms
Speed: 1.2ms preprocess, 298.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xY8khKcl84fZuKoDLTJa_Q_0.JPG: 480x640 (no detections), 298.0ms
Speed: 1.2ms preprocess, 298.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xY8khKcl84fZuKoDLTJa_Q_90.JPG: 480x640 (no detections), 303.9ms
Speed: 1.3ms preprocess, 303.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xY8khKcl84fZuKoDLTJa_Q_180.JPG: 480x640 (no detections), 301.4ms
Speed: 1.2ms preprocess, 301.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xY8khKcl84fZuKoDLTJa_Q_270.JPG: 480x640 (no detections), 298.1ms
Speed: 1.2ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYIC31gRTqC8gNhoFtVhJg_0.JPG: 480x640 (no detections), 300.3ms
Speed: 1.3ms preprocess, 300.3ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYIC31gRTqC8gNhoFtVhJg_90.JPG: 480x640 (no detections), 298.1ms
Speed: 1.1ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYIC31gRTqC8gNhoFtVhJg_180.JPG: 480x640 (no detections), 303.6ms
Speed: 1.0ms preprocess, 303.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYIC31gRTqC8gNhoFtVhJg_270.JPG: 480x640 (no detections), 303.4ms
Speed: 1.3ms preprocess, 303.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYManEd4ahuHXazoJeYIDA_0.JPG: 480x640 (no detections), 299.7ms
Speed: 1.7ms preprocess, 299.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYManEd4ahuHXazoJeYIDA_90.JPG: 480x640 (no detections), 300.4ms
Speed: 1.3ms preprocess, 300.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYManEd4ahuHXazoJeYIDA_180.JPG: 480x640 (no detections), 297.7ms
Speed: 1.2ms preprocess, 297.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYManEd4ahuHXazoJeYIDA_270.JPG: 480x640 (no detections), 296.9ms
Speed: 1.0ms preprocess, 296.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYO11pIRVvuRWKYAe6WIQQ_0.JPG: 480x640 (no detections), 379.8ms
Speed: 1.1ms preprocess, 379.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYO11pIRVvuRWKYAe6WIQQ_90.JPG: 480x640 (no detections), 298.3ms
Speed: 1.2ms preprocess, 298.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYO11pIRVvuRWKYAe6WIQQ_180.JPG: 480x640 (no detections), 302.9ms
Speed: 1.2ms preprocess, 302.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYO11pIRVvuRWKYAe6WIQQ_270.JPG: 480x640 (no detections), 297.8ms
Speed: 1.2ms preprocess, 297.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYPrH3ODaBQ5vDei7a-N8Q_0.JPG: 480x640 (no detections), 300.5ms
Speed: 1.2ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYPrH3ODaBQ5vDei7a-N8Q_90.JPG: 480x640 (no detections), 297.7ms
Speed: 1.2ms preprocess, 297.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYPrH3ODaBQ5vDei7a-N8Q_180.JPG: 480x640 1 Waste, 298.6ms
Speed: 1.4ms preprocess, 298.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYPrH3ODaBQ5vDei7a-N8Q_270.JPG: 480x640 (no detections), 296.3ms
Speed: 1.2ms preprocess, 296.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYUL-vA7Jpob2zQllKNHUQ_0.JPG: 480x640 (no detections), 301.3ms
Speed: 1.2ms preprocess, 301.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYUL-vA7Jpob2zQllKNHUQ_90.JPG: 480x640 (no detections), 301.3ms
Speed: 1.3ms preprocess, 301.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYUL-vA7Jpob2zQllKNHUQ_180.JPG: 480x640 (no detections), 306.0ms
Speed: 1.3ms preprocess, 306.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYUL-vA7Jpob2zQllKNHUQ_270.JPG: 480x640 (no detections), 309.3ms
Speed: 1.2ms preprocess, 309.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYUv6zXm8Mc0gZZ9U7AUGw_0.JPG: 480x640 (no detections), 291.9ms
Speed: 1.2ms preprocess, 291.9ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYUv6zXm8Mc0gZZ9U7AUGw_90.JPG: 480x640 (no detections), 291.5ms
Speed: 1.1ms preprocess, 291.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYUv6zXm8Mc0gZZ9U7AUGw_180.JPG: 480x640 (no detections), 297.7ms
Speed: 1.1ms preprocess, 297.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYUv6zXm8Mc0gZZ9U7AUGw_270.JPG: 480x640 (no detections), 294.9ms
Speed: 1.4ms preprocess, 294.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYXeZYUq2uNfvXSyN8Cr1Q_0.JPG: 480x640 (no detections), 299.2ms
Speed: 1.3ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYXeZYUq2uNfvXSyN8Cr1Q_90.JPG: 480x640 (no detections), 297.6ms
Speed: 1.8ms preprocess, 297.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYXeZYUq2uNfvXSyN8Cr1Q_180.JPG: 480x640 (no detections), 295.8ms
Speed: 1.2ms preprocess, 295.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYXeZYUq2uNfvXSyN8Cr1Q_270.JPG: 480x640 (no detections), 299.2ms
Speed: 1.1ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYXmtpo9hN8Fo74bwGOUmA_0.JPG: 480x640 (no detections), 290.7ms
Speed: 1.8ms preprocess, 290.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYXmtpo9hN8Fo74bwGOUmA_90.JPG: 480x640 (no detections), 294.5ms
Speed: 1.2ms preprocess, 294.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYXmtpo9hN8Fo74bwGOUmA_180.JPG: 480x640 (no detections), 296.6ms
Speed: 1.3ms preprocess, 296.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYXmtpo9hN8Fo74bwGOUmA_270.JPG: 480x640 (no detections), 291.6ms
Speed: 1.4ms preprocess, 291.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYZlzfexxhbSsdUfUfd0RQ_0.JPG: 480x640 (no detections), 296.0ms
Speed: 1.2ms preprocess, 296.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYZlzfexxhbSsdUfUfd0RQ_90.JPG: 480x640 (no detections), 294.9ms
Speed: 1.2ms preprocess, 294.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYZlzfexxhbSsdUfUfd0RQ_180.JPG: 480x640 (no detections), 296.8ms
Speed: 1.1ms preprocess, 296.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYZlzfexxhbSsdUfUfd0RQ_270.JPG: 480x640 (no detections), 297.6ms
Speed: 1.5ms preprocess, 297.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYZsToXShQ-kYot8GXxYiA_0.JPG: 480x640 1 Waste, 293.4ms
Speed: 1.1ms preprocess, 293.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYZsToXShQ-kYot8GXxYiA_90.JPG: 480x640 (no detections), 294.8ms
Speed: 1.1ms preprocess, 294.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYZsToXShQ-kYot8GXxYiA_180.JPG: 480x640 (no detections), 294.5ms
Speed: 1.1ms preprocess, 294.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYZsToXShQ-kYot8GXxYiA_270.JPG: 480x640 (no detections), 295.6ms
Speed: 1.0ms preprocess, 295.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYcRW3BXWUbW4V3PsKWocA_0.JPG: 480x640 (no detections), 294.8ms
Speed: 1.0ms preprocess, 294.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYcRW3BXWUbW4V3PsKWocA_90.JPG: 480x640 (no detections), 295.0ms
Speed: 1.1ms preprocess, 295.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYcRW3BXWUbW4V3PsKWocA_180.JPG: 480x640 (no detections), 297.0ms
Speed: 1.0ms preprocess, 297.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYcRW3BXWUbW4V3PsKWocA_270.JPG: 480x640 (no detections), 296.4ms
Speed: 1.1ms preprocess, 296.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYcxqUSLr82lZavwbboZLg_0.JPG: 480x640 (no detections), 296.5ms
Speed: 1.1ms preprocess, 296.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYcxqUSLr82lZavwbboZLg_90.JPG: 480x640 (no detections), 300.2ms

Speed: 1.6ms preprocess, 300.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYcxqUSLr82lZavwbboZLg_180.JPG: 480x640 (no detections), 295.1ms
Speed: 1.3ms preprocess, 295.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYcxqUSLr82lZavwbboZLg_270.JPG: 480x640 (no detections), 290.9ms
Speed: 1.0ms preprocess, 290.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYdEqScG2PSys28bW2RpSw_0.JPG: 480x640 (no detections), 292.1ms
Speed: 1.2ms preprocess, 292.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYdEqScG2PSys28bW2RpSw_90.JPG: 480x640 (no detections), 299.2ms
Speed: 1.2ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYdEqScG2PSys28bW2RpSw_180.JPG: 480x640 (no detections), 297.0ms
Speed: 1.2ms preprocess, 297.0ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYdEqScG2PSys28bW2RpSw_270.JPG: 480x640 (no detections), 301.7ms
Speed: 1.2ms preprocess, 301.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYe4zeE6VHIS5XlC99vRIA_0.JPG: 480x640 (no detections), 294.4ms
Speed: 1.5ms preprocess, 294.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYe4zeE6VHIS5XlC99vRIA_90.JPG: 480x640 (no detections), 297.6ms
Speed: 1.1ms preprocess, 297.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYe4zeE6VHIS5XlC99vRIA_180.JPG: 480x640 (no detections), 296.5ms
Speed: 1.1ms preprocess, 296.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYe4zeE6VHIS5XlC99vRIA_270.JPG: 480x640 (no detections), 294.5ms
Speed: 1.2ms preprocess, 294.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYjF_ApTD-G7j3DtuBsfhw_0.JPG: 480x640 (no detections), 301.8ms
Speed: 1.1ms preprocess, 301.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYjF_ApTD-G7j3DtuBsfhw_90.JPG: 480x640 (no detections), 294.5ms
Speed: 1.1ms preprocess, 294.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYjF_ApTD-G7j3DtuBsfhw_180.JPG: 480x640 (no detections), 296.7ms
Speed: 1.1ms preprocess, 296.7ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYjF_ApTD-G7j3DtuBsfhw_270.JPG: 480x640 (no detections), 297.2ms
Speed: 1.3ms preprocess, 297.2ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYkx3Y8B7vk8JN7kpjP02w_0.JPG: 480x640 (no detections), 299.2ms
Speed: 1.2ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYkx3Y8B7vk8JN7kpjP02w_90.JPG: 480x640 (no detections), 302.2ms
Speed: 1.2ms preprocess, 302.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYkx3Y8B7vk8JN7kpjP02w_180.JPG: 480x640 (no detections), 295.9ms
Speed: 1.8ms preprocess, 295.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYkx3Y8B7vk8JN7kpjP02w_270.JPG: 480x640 (no detections), 294.0ms
Speed: 1.2ms preprocess, 294.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYl6cnFvXiXWoaiOni74iw_0.JPG: 480x640 (no detections), 296.0ms
Speed: 1.2ms preprocess, 296.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYl6cnFvXiXWoaiOni74iw_90.JPG: 480x640 (no detections), 299.0ms
Speed: 1.6ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYl6cnFvXiXWoaiOni74iw_180.JPG: 480x640 (no detections), 293.6ms
Speed: 1.2ms preprocess, 293.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYl6cnFvXiXWoaiOni74iw_270.JPG: 480x640 (no detections), 292.1ms
Speed: 1.1ms preprocess, 292.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYmgV8dq3Ra6msZj8XWvpg_0.JPG: 480x640 (no detections), 293.4ms
Speed: 1.0ms preprocess, 293.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYmgV8dq3Ra6msZj8XWvpg_90.JPG: 480x640 (no detections), 301.8ms
Speed: 1.1ms preprocess, 301.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYmgV8dq3Ra6msZj8XWvpg_180.JPG: 480x640 (no detections), 302.2ms
Speed: 1.2ms preprocess, 302.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYmgV8dq3Ra6msZj8XWvpg_270.JPG: 480x640 (no detections), 296.8ms
Speed: 1.4ms preprocess, 296.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYnJ-LDlNhaP04ljfw5jlg_0.JPG: 480x640 (no detections), 295.6ms
Speed: 1.1ms preprocess, 295.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYnJ-LDlNhaP04ljfw5jlg_90.JPG: 480x640 (no detections), 299.6ms
Speed: 1.6ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYnJ-LDlNhaP04ljfw5jlg_180.JPG: 480x640 (no detections), 294.2ms
Speed: 1.3ms preprocess, 294.2ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYnJ-LDlNhaP04ljfw5jlg_270.JPG: 480x640 (no detections), 299.4ms
Speed: 1.1ms preprocess, 299.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYoDP4nvLyLDke2wYwuluA_0.JPG: 480x640 (no detections), 298.5ms
Speed: 1.1ms preprocess, 298.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYoDP4nvLyLDke2wYwuluA_90.JPG: 480x640 (no detections), 296.1ms
Speed: 1.0ms preprocess, 296.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYoDP4nvLyLDke2wYwuluA_180.JPG: 480x640 (no detections), 293.1ms
Speed: 1.2ms preprocess, 293.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYoDP4nvLyLDke2wYwuluA_270.JPG: 480x640 (no detections), 292.8ms
Speed: 1.1ms preprocess, 292.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYq-vIPnH6Y5YZQLGnibBQ_0.JPG: 480x640 (no detections), 298.9ms
Speed: 1.2ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYq-vIPnH6Y5YZQLGnibBQ_90.JPG: 480x640 (no detections), 291.7ms
Speed: 1.2ms preprocess, 291.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYq-vIPnH6Y5YZQLGnibBQ_180.JPG: 480x640 (no detections), 292.7ms
Speed: 1.4ms preprocess, 292.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYq-vIPnH6Y5YZQLGnibBQ_270.JPG: 480x640 (no detections), 297.8ms
Speed: 1.1ms preprocess, 297.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYr-QdDjY68NWPrrfDwTFw_0.JPG: 480x640 (no detections), 294.2ms
Speed: 1.1ms preprocess, 294.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYr-QdDjY68NWPrrfDwTFw_90.JPG: 480x640 (no detections), 296.4ms
Speed: 1.0ms preprocess, 296.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYr-QdDjY68NWPrrfDwTFw_180.JPG: 480x640 (no detections), 294.2ms
Speed: 1.3ms preprocess, 294.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYr-QdDjY68NWPrrfDwTFw_270.JPG: 480x640 (no detections), 297.6ms
Speed: 1.3ms preprocess, 297.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYrBBYTBGuMGUCxNk1yqfw_0.JPG: 480x640 (no detections), 297.0ms
Speed: 1.3ms preprocess, 297.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYrBBYTBGuMGUCxNk1yqfw_90.JPG: 480x640 (no detections), 290.1ms
Speed: 1.1ms preprocess, 290.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYrBBYTBGuMGUCxNk1yqfw_180.JPG: 480x640 (no detections), 297.9ms
Speed: 1.5ms preprocess, 297.9ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xYrBBYTBGuMGUCxNk1yqfw_270.JPG: 480x640 (no detections), 296.7ms
Speed: 1.3ms preprocess, 296.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZ0_cRH71jicxFQAWJnFpQ_0.JPG: 480x640 (no detections), 300.1ms
Speed: 1.2ms preprocess, 300.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZ0_cRH71jicxFQAWJnFpQ_90.JPG: 480x640 (no detections), 300.5ms
Speed: 1.2ms preprocess, 300.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZ0_cRH71jicxFQAWJnFpQ_180.JPG: 480x640 (no detections), 291.5ms
Speed: 1.4ms preprocess, 291.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZ0_cRH71jicxFQAWJnFpQ_270.JPG: 480x640 (no detections), 293.3ms
Speed: 1.0ms preprocess, 293.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZ3_mIFQ09GVignyIiiPog_0.JPG: 480x640 (no detections), 305.3ms
Speed: 1.2ms preprocess, 305.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZ3_mIFQ09GVignyIiiPog_90.JPG: 480x640 (no detections), 291.4ms
Speed: 1.6ms preprocess, 291.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZ3_mIFQ09GVignyIiiPog_180.JPG: 480x640 (no detections), 294.0ms
Speed: 1.3ms preprocess, 294.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZ3_mIFQ09GVignyIiiPog_270.JPG: 480x640 (no detections), 295.7ms
Speed: 1.2ms preprocess, 295.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZ3ht5doYEU1J__vCRjVtQ_0.JPG: 480x640 (no detections), 294.3ms
Speed: 1.4ms preprocess, 294.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZ3ht5doYEU1J__vCRjVtQ_90.JPG: 480x640 (no detections), 296.5ms
Speed: 1.3ms preprocess, 296.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZ3ht5doYEU1J__vCRjVtQ_180.JPG: 480x640 (no detections), 293.8ms
Speed: 1.2ms preprocess, 293.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZ3ht5doYEU1J__vCRjVtQ_270.JPG: 480x640 (no detections), 290.4ms
Speed: 1.2ms preprocess, 290.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZ9b4wexBPzXLObTjAp1Fg_0.JPG: 480x640 (no detections), 295.9ms
Speed: 1.4ms preprocess, 295.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZ9b4wexBPzXLObTjAp1Fg_90.JPG: 480x640 (no detections), 301.6ms
Speed: 1.2ms preprocess, 301.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZ9b4wexBPzXLObTjAp1Fg_180.JPG: 480x640 1 Waste, 294.3ms
Speed: 1.1ms preprocess, 294.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZ9b4wexBPzXLObTjAp1Fg_270.JPG: 480x640 (no detections), 289.9ms
Speed: 1.4ms preprocess, 289.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZFPRHPrSGToTpYgbun_IA_0.JPG: 480x640 (no detections), 298.4ms
Speed: 1.2ms preprocess, 298.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZFPRHPrSGToTpYgbun_IA_90.JPG: 480x640 (no detections), 296.1ms
Speed: 1.0ms preprocess, 296.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZFPRHPrSGToTpYgbun_IA_180.JPG: 480x640 (no detections), 295.9ms
Speed: 1.3ms preprocess, 295.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZFPRHPrSGToTpYgbun_IA_270.JPG: 480x640 (no detections), 298.5ms
Speed: 1.1ms preprocess, 298.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZG8mATYUl4dK1KMoFwMPg_0.JPG: 480x640 (no detections), 298.4ms

Speed: 1.1ms preprocess, 298.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZG8mATYUl4dK1KMoFwMPg_90.JPG: 480x640 (no detections), 296.0ms
Speed: 1.2ms preprocess, 296.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZG8mATYUl4dK1KMoFwMPg_180.JPG: 480x640 (no detections), 296.0ms
Speed: 1.1ms preprocess, 296.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZG8mATYUl4dK1KMoFwMPg_270.JPG: 480x640 (no detections), 297.6ms
Speed: 1.1ms preprocess, 297.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZITpLOLvBCxKFz52JGJeA_0.JPG: 480x640 (no detections), 291.5ms
Speed: 1.1ms preprocess, 291.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZITpLOLvBCxKFz52JGJeA_90.JPG: 480x640 (no detections), 290.7ms
Speed: 1.2ms preprocess, 290.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZITpLOLvBCxKFz52JGJeA_180.JPG: 480x640 (no detections), 299.4ms
Speed: 1.1ms preprocess, 299.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZITpLOLvBCxKFz52JGJeA_270.JPG: 480x640 (no detections), 300.1ms
Speed: 1.0ms preprocess, 300.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZJockdRy5FTQPpcuDB2hw_0.JPG: 480x640 (no detections), 299.9ms
Speed: 1.4ms preprocess, 299.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZJockdRy5FTQPpcuDB2hw_90.JPG: 480x640 (no detections), 294.9ms
Speed: 1.4ms preprocess, 294.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZJockdRy5FTQPpcuDB2hw_180.JPG: 480x640 (no detections), 299.7ms
Speed: 1.2ms preprocess, 299.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZJockdRy5FTQPpcuDB2hw_270.JPG: 480x640 (no detections), 298.4ms
Speed: 1.0ms preprocess, 298.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZMFTBNSLz17gG3HUPKNkw_0.JPG: 480x640 2 Wastes, 292.2ms
Speed: 1.2ms preprocess, 292.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZMFTBNSLz17gG3HUPKNkw_90.JPG: 480x640 2 Wastes, 297.1ms
Speed: 1.1ms preprocess, 297.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZMFTBNSLz17gG3HUPKNkw_180.JPG: 480x640 (no detections), 293.3ms
Speed: 1.4ms preprocess, 293.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZMFTBNSLz17gG3HUPKNkw_270.JPG: 480x640 (no detections), 297.5ms
Speed: 1.3ms preprocess, 297.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZO6ChM1D-g7j1Lg5tycyg_0.JPG: 480x640 (no detections), 297.2ms
Speed: 1.1ms preprocess, 297.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZO6ChM1D-g7j1Lg5tycyg_90.JPG: 480x640 (no detections), 299.0ms
Speed: 1.1ms preprocess, 299.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZO6ChM1D-g7j1Lg5tycyg_180.JPG: 480x640 (no detections), 301.0ms
Speed: 1.2ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZO6ChM1D-g7j1Lg5tycyg_270.JPG: 480x640 (no detections), 292.6ms
Speed: 1.2ms preprocess, 292.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZOzKJxLX9b5UzbKbvbZlA_0.JPG: 480x640 (no detections), 295.0ms
Speed: 1.1ms preprocess, 295.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZOzKJxLX9b5UzbKbvbZlA_90.JPG: 480x640 (no detections), 293.8ms
Speed: 1.2ms preprocess, 293.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZOzKJxLX9b5UzbKbvbZlA_180.JPG: 480x640 (no detections), 291.2ms
Speed: 1.3ms preprocess, 291.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZOzKJxLX9b5UzbKbvbZlA_270.JPG: 480x640 (no detections), 300.0ms
Speed: 1.1ms preprocess, 300.0ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZREy7YBExQ1yxkaXRcqqQ_0.JPG: 480x640 (no detections), 295.3ms
Speed: 1.1ms preprocess, 295.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZREy7YBExQ1yxkaXRcqqQ_90.JPG: 480x640 (no detections), 291.2ms
Speed: 1.2ms preprocess, 291.2ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZREy7YBExQ1yxkaXRcqqQ_180.JPG: 480x640 (no detections), 295.8ms
Speed: 1.0ms preprocess, 295.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZREy7YBExQ1yxkaXRcqqQ_270.JPG: 480x640 (no detections), 290.9ms
Speed: 1.3ms preprocess, 290.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZS8BKRRzp1vr4C9nnpS3Q_0.JPG: 480x640 2 Wastes, 298.6ms
Speed: 1.1ms preprocess, 298.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZS8BKRRzp1vr4C9nnpS3Q_90.JPG: 480x640 (no detections), 290.7ms
Speed: 1.1ms preprocess, 290.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZS8BKRRzp1vr4C9nnpS3Q_180.JPG: 480x640 1 Waste, 297.8ms
Speed: 1.3ms preprocess, 297.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZS8BKRRzp1vr4C9nnpS3Q_270.JPG: 480x640 (no detections), 298.9ms
Speed: 1.2ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZU2Fb1OT_uXV80HxSx5TQ_0.JPG: 480x640 (no detections), 296.4ms
Speed: 1.0ms preprocess, 296.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZU2Fb1OT_uXV80HxSx5TQ_90.JPG: 480x640 (no detections), 293.0ms
Speed: 1.0ms preprocess, 293.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZU2Fb1OT_uXV80HxSx5TQ_180.JPG: 480x640 (no detections), 297.1ms
Speed: 1.2ms preprocess, 297.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZU2Fb1OT_uXV80HxSx5TQ_270.JPG: 480x640 (no detections), 294.7ms
Speed: 1.2ms preprocess, 294.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZUpuY2ETtt6waL3YO6Qmg_0.JPG: 480x640 (no detections), 299.4ms
Speed: 1.3ms preprocess, 299.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZUpuY2ETtt6waL3YO6Qmg_90.JPG: 480x640 (no detections), 297.1ms
Speed: 1.2ms preprocess, 297.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZUpuY2ETtt6waL3YO6Qmg_180.JPG: 480x640 (no detections), 297.7ms
Speed: 1.1ms preprocess, 297.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZUpuY2ETtt6waL3YO6Qmg_270.JPG: 480x640 (no detections), 300.3ms
Speed: 1.3ms preprocess, 300.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZe-lagylom-zSKYzMKQug_0.JPG: 480x640 (no detections), 294.2ms
Speed: 1.2ms preprocess, 294.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZe-lagylom-zSKYzMKQug_90.JPG: 480x640 1 Waste, 294.7ms
Speed: 1.1ms preprocess, 294.7ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZe-lagylom-zSKYzMKQug_180.JPG: 480x640 (no detections), 293.6ms
Speed: 1.1ms preprocess, 293.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZe-lagylom-zSKYzMKQug_270.JPG: 480x640 (no detections), 296.4ms
Speed: 1.0ms preprocess, 296.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZgK2ifc4QWn9_MTpdPcxQ_0.JPG: 480x640 (no detections), 298.0ms
Speed: 1.1ms preprocess, 298.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZgK2ifc4QWn9_MTpdPcxQ_90.JPG: 480x640 (no detections), 292.3ms
Speed: 1.1ms preprocess, 292.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZgK2ifc4QWn9_MTpdPcxQ_180.JPG: 480x640 (no detections), 296.1ms
Speed: 1.2ms preprocess, 296.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZgK2ifc4QWn9_MTpdPcxQ_270.JPG: 480x640 (no detections), 301.2ms
Speed: 1.1ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZjMyFaWmkIHPzCN3atNOA_0.JPG: 480x640 (no detections), 301.3ms
Speed: 1.6ms preprocess, 301.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZjMyFaWmkIHPzCN3atNOA_90.JPG: 480x640 (no detections), 293.1ms
Speed: 1.1ms preprocess, 293.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZjMyFaWmkIHPzCN3atNOA_180.JPG: 480x640 (no detections), 295.3ms
Speed: 1.1ms preprocess, 295.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZjMyFaWmkIHPzCN3atNOA_270.JPG: 480x640 (no detections), 300.0ms
Speed: 1.0ms preprocess, 300.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZmjYur1QYrO2T9ChcW-Sg_0.JPG: 480x640 1 Waste, 292.6ms
Speed: 1.1ms preprocess, 292.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZmjYur1QYrO2T9ChcW-Sg_90.JPG: 480x640 (no detections), 297.8ms
Speed: 1.2ms preprocess, 297.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZmjYur1QYrO2T9ChcW-Sg_180.JPG: 480x640 (no detections), 304.5ms
Speed: 1.2ms preprocess, 304.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZmjYur1QYrO2T9ChcW-Sg_270.JPG: 480x640 (no detections), 293.4ms
Speed: 1.1ms preprocess, 293.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZpT1NvsE1261xp1oVZWEQ_0.JPG: 480x640 (no detections), 293.4ms
Speed: 1.1ms preprocess, 293.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZpT1NvsE1261xp1oVZWEQ_90.JPG: 480x640 (no detections), 295.7ms
Speed: 1.2ms preprocess, 295.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZpT1NvsE1261xp1oVZWEQ_180.JPG: 480x640 2 Wastes, 298.4ms
Speed: 1.1ms preprocess, 298.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZpT1NvsE1261xp1oVZWEQ_270.JPG: 480x640 3 Wastes, 291.4ms
Speed: 1.2ms preprocess, 291.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZs6NnqyYjAhDxjCpNYKGg_0.JPG: 480x640 (no detections), 295.6ms
Speed: 1.1ms preprocess, 295.6ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZs6NnqyYjAhDxjCpNYKGg_90.JPG: 480x640 (no detections), 299.5ms
Speed: 1.1ms preprocess, 299.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZs6NnqyYjAhDxjCpNYKGg_180.JPG: 480x640 (no detections), 301.2ms
Speed: 1.3ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZs6NnqyYjAhDxjCpNYKGg_270.JPG: 480x640 (no detections), 291.4ms
Speed: 1.2ms preprocess, 291.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZxKpWLoYKZpURLog73eTQ_0.JPG: 480x640 (no detections), 304.3ms
Speed: 1.5ms preprocess, 304.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZxKpWLoYKZpURLog73eTQ_90.JPG: 480x640 (no detections), 299.7ms
Speed: 1.3ms preprocess, 299.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZxKpWLoYKZpURLog73eTQ_180.JPG: 480x640 (no detections), 297.5ms
Speed: 1.3ms preprocess, 297.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZxKpWLoYKZpURLog73eTQ_270.JPG: 480x640 (no detections), 297.2ms

Speed: 1.2ms preprocess, 297.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZxYxos4ZxWathnOKDYWQg_0.JPG: 480x640 (no detections), 291.2ms
Speed: 1.2ms preprocess, 291.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZxYxos4ZxWathnOKDYWQg_90.JPG: 480x640 (no detections), 295.6ms
Speed: 1.4ms preprocess, 295.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZxYxos4ZxWathnOKDYWQg_180.JPG: 480x640 (no detections), 296.1ms
Speed: 1.1ms preprocess, 296.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xZxYxos4ZxWathnOKDYWQg_270.JPG: 480x640 (no detections), 299.0ms
Speed: 1.3ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_-1HxPlzZOxBCT-QsJ6rg_0.JPG: 480x640 (no detections), 298.7ms
Speed: 1.4ms preprocess, 298.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_-1HxPlzZOxBCT-QsJ6rg_90.JPG: 480x640 (no detections), 294.3ms
Speed: 1.1ms preprocess, 294.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_-1HxPlzZOxBCT-QsJ6rg_180.JPG: 480x640 (no detections), 294.4ms
Speed: 1.3ms preprocess, 294.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_-1HxPlzZOxBCT-QsJ6rg_270.JPG: 480x640 (no detections), 319.7ms
Speed: 1.4ms preprocess, 319.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_-SJK63aksjhAaZvYaenA_0.JPG: 480x640 (no detections), 332.2ms
Speed: 1.3ms preprocess, 332.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_-SJK63aksjhAaZvYaenA_90.JPG: 480x640 (no detections), 328.8ms
Speed: 1.5ms preprocess, 328.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_-SJK63aksjhAaZvYaenA_180.JPG: 480x640 (no detections), 326.7ms
Speed: 1.6ms preprocess, 326.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_-SJK63aksjhAaZvYaenA_270.JPG: 480x640 (no detections), 329.3ms
Speed: 1.2ms preprocess, 329.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_1eCVnP4FB6mM8ZoQ1OIg_0.JPG: 480x640 (no detections), 326.1ms
Speed: 1.5ms preprocess, 326.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_1eCVnP4FB6mM8ZoQ1OIg_90.JPG: 480x640 (no detections), 321.5ms
Speed: 1.3ms preprocess, 321.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_1eCVnP4FB6mM8ZoQ1OIg_180.JPG: 480x640 (no detections), 304.5ms
Speed: 1.3ms preprocess, 304.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_1eCVnP4FB6mM8ZoQ1OIg_270.JPG: 480x640 (no detections), 293.7ms
Speed: 1.2ms preprocess, 293.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_4REKD-0pu2PRvUjjbSmQ_0.JPG: 480x640 (no detections), 297.7ms
Speed: 1.1ms preprocess, 297.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_4REKD-0pu2PRvUjjbSmQ_90.JPG: 480x640 (no detections), 290.4ms
Speed: 1.1ms preprocess, 290.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_4REKD-0pu2PRvUjjbSmQ_180.JPG: 480x640 (no detections), 296.1ms
Speed: 1.1ms preprocess, 296.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_4REKD-0pu2PRvUjjbSmQ_270.JPG: 480x640 (no detections), 288.9ms
Speed: 1.2ms preprocess, 288.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_4xtrhyo8A68zskLUho0w_0.JPG: 480x640 (no detections), 295.9ms
Speed: 1.0ms preprocess, 295.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_4xtrhyo8A68zskLUho0w_90.JPG: 480x640 (no detections), 299.4ms
Speed: 1.2ms preprocess, 299.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_4xtrhyo8A68zskLUho0w_180.JPG: 480x640 (no detections), 307.5ms
Speed: 1.4ms preprocess, 307.5ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_4xtrhyo8A68zskLUho0w_270.JPG: 480x640 (no detections), 299.7ms
Speed: 1.1ms preprocess, 299.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_7JDVT7wj0jv2vSYtjOWg_0.JPG: 480x640 (no detections), 296.1ms
Speed: 1.2ms preprocess, 296.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_7JDVT7wj0jv2vSYtjOWg_90.JPG: 480x640 (no detections), 294.5ms
Speed: 1.2ms preprocess, 294.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_7JDVT7wj0jv2vSYtjOWg_180.JPG: 480x640 (no detections), 293.1ms
Speed: 1.1ms preprocess, 293.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_7JDVT7wj0jv2vSYtjOWg_270.JPG: 480x640 (no detections), 300.9ms
Speed: 1.0ms preprocess, 300.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_EXh719Mdu_ClpJ2iX-EA_0.JPG: 480x640 (no detections), 291.8ms
Speed: 1.2ms preprocess, 291.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_EXh719Mdu_ClpJ2iX-EA_90.JPG: 480x640 (no detections), 299.0ms
Speed: 1.0ms preprocess, 299.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_EXh719Mdu_ClpJ2iX-EA_180.JPG: 480x640 (no detections), 291.1ms
Speed: 1.3ms preprocess, 291.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_EXh719Mdu_ClpJ2iX-EA_270.JPG: 480x640 (no detections), 297.0ms
Speed: 1.0ms preprocess, 297.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_Gg3KpbDjhqw9EHaHvxFg_0.JPG: 480x640 (no detections), 296.0ms
Speed: 1.1ms preprocess, 296.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_Gg3KpbDjhqw9EHaHvxFg_90.JPG: 480x640 (no detections), 293.9ms
Speed: 1.2ms preprocess, 293.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_Gg3KpbDjhqw9EHaHvxFg_180.JPG: 480x640 (no detections), 299.5ms
Speed: 1.1ms preprocess, 299.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_Gg3KpbDjhqw9EHaHvxFg_270.JPG: 480x640 (no detections), 296.1ms
Speed: 1.1ms preprocess, 296.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_GljZecIHC4VcoPXo8z9A_0.JPG: 480x640 (no detections), 293.8ms
Speed: 1.5ms preprocess, 293.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_GljZecIHC4VcoPXo8z9A_90.JPG: 480x640 (no detections), 294.9ms
Speed: 1.2ms preprocess, 294.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_GljZecIHC4VcoPXo8z9A_180.JPG: 480x640 (no detections), 294.7ms
Speed: 1.2ms preprocess, 294.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_GljZecIHC4VcoPXo8z9A_270.JPG: 480x640 (no detections), 295.8ms
Speed: 1.1ms preprocess, 295.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_K8KzBTbFhDA0vk1lFTdQ_0.JPG: 480x640 (no detections), 298.5ms
Speed: 1.2ms preprocess, 298.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_K8KzBTbFhDA0vk1lFTdQ_90.JPG: 480x640 (no detections), 292.0ms
Speed: 1.2ms preprocess, 292.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_K8KzBTbFhDA0vk1lFTdQ_180.JPG: 480x640 (no detections), 297.4ms
Speed: 1.3ms preprocess, 297.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_K8KzBTbFhDA0vk1lFTdQ_270.JPG: 480x640 (no detections), 294.4ms
Speed: 1.2ms preprocess, 294.4ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_OqSxg5zUW8Uj1QGOV7EQ_0.JPG: 480x640 (no detections), 295.5ms
Speed: 1.2ms preprocess, 295.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_OqSxg5zUW8Uj1QGOV7EQ_90.JPG: 480x640 (no detections), 297.3ms
Speed: 1.1ms preprocess, 297.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_OqSxg5zUW8Uj1QGOV7EQ_180.JPG: 480x640 (no detections), 295.8ms
Speed: 1.0ms preprocess, 295.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_OqSxg5zUW8Uj1QGOV7EQ_270.JPG: 480x640 (no detections), 293.5ms
Speed: 1.1ms preprocess, 293.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_RTzTi0CZTl_D7zfLNusg_0.JPG: 480x640 (no detections), 296.8ms
Speed: 1.1ms preprocess, 296.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_RTzTi0CZTl_D7zfLNusg_90.JPG: 480x640 (no detections), 300.9ms
Speed: 1.1ms preprocess, 300.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_RTzTi0CZTl_D7zfLNusg_180.JPG: 480x640 (no detections), 293.4ms
Speed: 1.2ms preprocess, 293.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_RTzTi0CZTl_D7zfLNusg_270.JPG: 480x640 (no detections), 293.7ms
Speed: 1.2ms preprocess, 293.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_T2YIAX0mq_dg9LfABm2Q_0.JPG: 480x640 (no detections), 292.7ms
Speed: 1.2ms preprocess, 292.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_T2YIAX0mq_dg9LfABm2Q_90.JPG: 480x640 (no detections), 292.8ms
Speed: 1.2ms preprocess, 292.8ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_T2YIAX0mq_dg9LfABm2Q_180.JPG: 480x640 (no detections), 293.1ms
Speed: 1.1ms preprocess, 293.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_T2YIAX0mq_dg9LfABm2Q_270.JPG: 480x640 (no detections), 291.9ms
Speed: 1.3ms preprocess, 291.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_UktOvEBJSBAzZK6anctQ_0.JPG: 480x640 (no detections), 294.2ms
Speed: 1.2ms preprocess, 294.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_UktOvEBJSBAzZK6anctQ_90.JPG: 480x640 (no detections), 293.3ms
Speed: 1.1ms preprocess, 293.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_UktOvEBJSBAzZK6anctQ_180.JPG: 480x640 (no detections), 293.3ms
Speed: 1.1ms preprocess, 293.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_UktOvEBJSBAzZK6anctQ_270.JPG: 480x640 (no detections), 296.6ms
Speed: 1.1ms preprocess, 296.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_UqVfnada3mJXBLFReKcQ_0.JPG: 480x640 (no detections), 298.9ms
Speed: 1.2ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_UqVfnada3mJXBLFReKcQ_90.JPG: 480x640 (no detections), 299.4ms
Speed: 1.7ms preprocess, 299.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_UqVfnada3mJXBLFReKcQ_180.JPG: 480x640 (no detections), 308.0ms
Speed: 1.2ms preprocess, 308.0ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_UqVfnada3mJXBLFReKcQ_270.JPG: 480x640 (no detections), 302.7ms
Speed: 1.6ms preprocess, 302.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_Uun1HLd1Kfm0mUR6eKog_0.JPG: 480x640 (no detections), 305.3ms
Speed: 1.4ms preprocess, 305.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_Uun1HLd1Kfm0mUR6eKog_90.JPG: 480x640 (no detections), 296.0ms
Speed: 1.1ms preprocess, 296.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_Uun1HLd1Kfm0mUR6eKog_180.JPG: 480x640 (no detections), 297.7ms

Speed: 1.5ms preprocess, 297.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_Uun1HLd1Kfm0mUR6eKog_270.JPG: 480x640 (no detections), 298.4ms
Speed: 1.2ms preprocess, 298.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_X4J8ddhTgLBnU0gT6Axg_0.JPG: 480x640 (no detections), 296.4ms
Speed: 1.3ms preprocess, 296.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_X4J8ddhTgLBnU0gT6Axg_90.JPG: 480x640 (no detections), 301.7ms
Speed: 1.1ms preprocess, 301.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_X4J8ddhTgLBnU0gT6Axg_180.JPG: 480x640 (no detections), 300.5ms
Speed: 1.1ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_X4J8ddhTgLBnU0gT6Axg_270.JPG: 480x640 (no detections), 302.5ms
Speed: 1.1ms preprocess, 302.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_XZXDvv_qEPtMGDB7LYgA_0.JPG: 480x640 (no detections), 298.8ms
Speed: 1.7ms preprocess, 298.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_XZXDvv_qEPtMGDB7LYgA_90.JPG: 480x640 (no detections), 294.5ms
Speed: 1.3ms preprocess, 294.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_XZXDvv_qEPtMGDB7LYgA_180.JPG: 480x640 (no detections), 297.7ms
Speed: 1.2ms preprocess, 297.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_XZXDvv_qEPtMGDB7LYgA_270.JPG: 480x640 (no detections), 300.9ms
Speed: 1.2ms preprocess, 300.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_Y0Qx8GAaRhgAG9JAHjgw_0.JPG: 480x640 (no detections), 296.4ms
Speed: 1.3ms preprocess, 296.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_Y0Qx8GAaRhgAG9JAHjgw_90.JPG: 480x640 (no detections), 300.8ms
Speed: 1.1ms preprocess, 300.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_Y0Qx8GAaRhgAG9JAHjgw_180.JPG: 480x640 (no detections), 301.4ms
Speed: 1.3ms preprocess, 301.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_Y0Qx8GAaRhgAG9JAHjgw_270.JPG: 480x640 (no detections), 302.9ms
Speed: 1.3ms preprocess, 302.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_Ze8wLjSsHjZP2wQ3q-ng_0.JPG: 480x640 (no detections), 299.3ms
Speed: 1.1ms preprocess, 299.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_Ze8wLjSsHjZP2wQ3q-ng_90.JPG: 480x640 (no detections), 301.9ms
Speed: 1.2ms preprocess, 301.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_Ze8wLjSsHjZP2wQ3q-ng_180.JPG: 480x640 (no detections), 300.5ms
Speed: 1.4ms preprocess, 300.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_Ze8wLjSsHjZP2wQ3q-ng_270.JPG: 480x640 (no detections), 299.6ms
Speed: 1.1ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_ajze50GwL9I03qteD8zg_0.JPG: 480x640 (no detections), 302.5ms
Speed: 1.2ms preprocess, 302.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_ajze50GwL9I03qteD8zg_90.JPG: 480x640 (no detections), 304.6ms
Speed: 1.0ms preprocess, 304.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_ajze50GwL9I03qteD8zg_180.JPG: 480x640 (no detections), 301.4ms
Speed: 1.1ms preprocess, 301.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_ajze50GwL9I03qteD8zg_270.JPG: 480x640 (no detections), 298.3ms
Speed: 1.7ms preprocess, 298.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_axEooLuuSWZFDmVIWVrg_0.JPG: 480x640 (no detections), 300.2ms
Speed: 1.0ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_axEooLuuSWZFDmVIWVrg_90.JPG: 480x640 (no detections), 305.4ms
Speed: 1.3ms preprocess, 305.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_axEooLuuSWZFDmVIWVrg_180.JPG: 480x640 (no detections), 296.9ms
Speed: 1.3ms preprocess, 296.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_axEooLuuSWZFDmVIWVrg_270.JPG: 480x640 (no detections), 295.0ms
Speed: 1.2ms preprocess, 295.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_d2Q14s88Ml9B6Q8_SGfg_0.JPG: 480x640 1 Waste, 296.3ms
Speed: 1.3ms preprocess, 296.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_d2Q14s88Ml9B6Q8_SGfg_90.JPG: 480x640 (no detections), 299.4ms
Speed: 1.1ms preprocess, 299.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_d2Q14s88Ml9B6Q8_SGfg_180.JPG: 480x640 (no detections), 299.8ms
Speed: 1.4ms preprocess, 299.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_d2Q14s88Ml9B6Q8_SGfg_270.JPG: 480x640 (no detections), 297.7ms
Speed: 1.2ms preprocess, 297.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_f8YSHM_lYC99W7HmZ3tw_0.JPG: 480x640 (no detections), 302.5ms
Speed: 1.3ms preprocess, 302.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_f8YSHM_lYC99W7HmZ3tw_90.JPG: 480x640 (no detections), 303.5ms
Speed: 1.1ms preprocess, 303.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_f8YSHM_lYC99W7HmZ3tw_180.JPG: 480x640 (no detections), 297.6ms
Speed: 1.2ms preprocess, 297.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_f8YSHM_lYC99W7HmZ3tw_270.JPG: 480x640 (no detections), 296.6ms
Speed: 1.2ms preprocess, 296.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_gAXkMYgjIqmx7KsJxWug_0.JPG: 480x640 (no detections), 298.4ms
Speed: 1.1ms preprocess, 298.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_gAXkMYgjIqmx7KsJxWug_90.JPG: 480x640 (no detections), 304.2ms
Speed: 1.1ms preprocess, 304.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_gAXkMYgjIqmx7KsJxWug_180.JPG: 480x640 (no detections), 305.4ms
Speed: 1.2ms preprocess, 305.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_gAXkMYgjIqmx7KsJxWug_270.JPG: 480x640 (no detections), 300.4ms
Speed: 1.1ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_h3iikEjkR70p2_eLuCsA_0.JPG: 480x640 (no detections), 297.8ms
Speed: 1.2ms preprocess, 297.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_h3iikEjkR70p2_eLuCsA_90.JPG: 480x640 2 Wastes, 300.7ms
Speed: 1.3ms preprocess, 300.7ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_h3iikEjkR70p2_eLuCsA_180.JPG: 480x640 (no detections), 310.3ms
Speed: 1.5ms preprocess, 310.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_h3iikEjkR70p2_eLuCsA_270.JPG: 480x640 (no detections), 291.3ms
Speed: 1.1ms preprocess, 291.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_hhE7lVa0C_hiAlGiONOQ_0.JPG: 480x640 (no detections), 299.8ms
Speed: 1.3ms preprocess, 299.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_hhE7lVa0C_hiAlGiONOQ_90.JPG: 480x640 (no detections), 308.5ms
Speed: 1.7ms preprocess, 308.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_hhE7lVa0C_hiAlGiONOQ_180.JPG: 480x640 (no detections), 298.5ms
Speed: 1.4ms preprocess, 298.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_hhE7lVa0C_hiAlGiONOQ_270.JPG: 480x640 (no detections), 301.7ms
Speed: 1.3ms preprocess, 301.7ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_ju1R0UYrRIpUsU3rePPQ_0.JPG: 480x640 (no detections), 297.0ms
Speed: 1.1ms preprocess, 297.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_ju1R0UYrRIpUsU3rePPQ_90.JPG: 480x640 (no detections), 298.7ms
Speed: 1.3ms preprocess, 298.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_ju1R0UYrRIpUsU3rePPQ_180.JPG: 480x640 (no detections), 301.6ms
Speed: 1.1ms preprocess, 301.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_ju1R0UYrRIpUsU3rePPQ_270.JPG: 480x640 (no detections), 300.9ms
Speed: 1.2ms preprocess, 300.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_k79j9wONPDatUORe-4WQ_0.JPG: 480x640 1 Waste, 300.5ms
Speed: 1.1ms preprocess, 300.5ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_k79j9wONPDatUORe-4WQ_90.JPG: 480x640 (no detections), 301.5ms
Speed: 1.5ms preprocess, 301.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_k79j9wONPDatUORe-4WQ_180.JPG: 480x640 (no detections), 296.6ms
Speed: 1.4ms preprocess, 296.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_k79j9wONPDatUORe-4WQ_270.JPG: 480x640 1 Waste, 299.1ms
Speed: 1.1ms preprocess, 299.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_kwkuMI4fkTKGDTdmofIw_0.JPG: 480x640 (no detections), 303.7ms
Speed: 1.1ms preprocess, 303.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_kwkuMI4fkTKGDTdmofIw_90.JPG: 480x640 (no detections), 298.4ms
Speed: 1.2ms preprocess, 298.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_kwkuMI4fkTKGDTdmofIw_180.JPG: 480x640 (no detections), 302.7ms
Speed: 1.0ms preprocess, 302.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_kwkuMI4fkTKGDTdmofIw_270.JPG: 480x640 (no detections), 306.2ms
Speed: 1.2ms preprocess, 306.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_sa7MHte98YAulE7KrPyw_0.JPG: 480x640 (no detections), 296.4ms
Speed: 1.2ms preprocess, 296.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_sa7MHte98YAulE7KrPyw_90.JPG: 480x640 (no detections), 301.4ms
Speed: 1.1ms preprocess, 301.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_sa7MHte98YAulE7KrPyw_180.JPG: 480x640 (no detections), 304.3ms
Speed: 1.2ms preprocess, 304.3ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_sa7MHte98YAulE7KrPyw_270.JPG: 480x640 (no detections), 298.8ms
Speed: 1.3ms preprocess, 298.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_tidUKvRDlCX-3fwqY0yg_0.JPG: 480x640 (no detections), 302.7ms
Speed: 1.3ms preprocess, 302.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_tidUKvRDlCX-3fwqY0yg_90.JPG: 480x640 (no detections), 296.4ms
Speed: 2.2ms preprocess, 296.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_tidUKvRDlCX-3fwqY0yg_180.JPG: 480x640 (no detections), 297.1ms
Speed: 1.1ms preprocess, 297.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/_/x_tidUKvRDlCX-3fwqY0yg_270.JPG: 480x640 (no detections), 298.3ms
Speed: 1.3ms preprocess, 298.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xa-OX3Tqy9zfChtzYaTJ0A_0.JPG: 480x640 (no detections), 300.3ms
Speed: 1.2ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xa-OX3Tqy9zfChtzYaTJ0A_90.JPG: 480x640 (no detections), 306.2ms

Speed: 1.3ms preprocess, 306.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xa-OX3Tqy9zfChtzYaTJ0A_180.JPG: 480x640 (no detections), 292.1ms
Speed: 1.1ms preprocess, 292.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xa-OX3Tqy9zfChtzYaTJ0A_270.JPG: 480x640 (no detections), 301.7ms
Speed: 1.2ms preprocess, 301.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xa-yalsWj_6sE4OH2i0dKQ_0.JPG: 480x640 (no detections), 304.5ms
Speed: 1.9ms preprocess, 304.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xa-yalsWj_6sE4OH2i0dKQ_90.JPG: 480x640 (no detections), 300.6ms
Speed: 1.6ms preprocess, 300.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xa-yalsWj_6sE4OH2i0dKQ_180.JPG: 480x640 (no detections), 301.9ms
Speed: 1.2ms preprocess, 301.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xa-yalsWj_6sE4OH2i0dKQ_270.JPG: 480x640 (no detections), 295.7ms
Speed: 1.3ms preprocess, 295.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xa1Sp-MDdJrMAcdP8M02CA_0.JPG: 480x640 (no detections), 300.1ms
Speed: 1.0ms preprocess, 300.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xa1Sp-MDdJrMAcdP8M02CA_90.JPG: 480x640 (no detections), 302.3ms
Speed: 1.1ms preprocess, 302.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xa1Sp-MDdJrMAcdP8M02CA_180.JPG: 480x640 (no detections), 294.6ms
Speed: 1.2ms preprocess, 294.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xa1Sp-MDdJrMAcdP8M02CA_270.JPG: 480x640 (no detections), 296.1ms
Speed: 1.3ms preprocess, 296.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xa5grF27XS_jKdd2VHlN4g_0.JPG: 480x640 (no detections), 302.7ms
Speed: 1.4ms preprocess, 302.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xa5grF27XS_jKdd2VHlN4g_90.JPG: 480x640 (no detections), 299.0ms
Speed: 1.1ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xa5grF27XS_jKdd2VHlN4g_180.JPG: 480x640 (no detections), 301.4ms
Speed: 1.2ms preprocess, 301.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xa5grF27XS_jKdd2VHlN4g_270.JPG: 480x640 (no detections), 310.2ms
Speed: 1.7ms preprocess, 310.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xa8aT8toEA01W9fq8s3AhA_0.JPG: 480x640 (no detections), 318.6ms
Speed: 1.5ms preprocess, 318.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xa8aT8toEA01W9fq8s3AhA_90.JPG: 480x640 (no detections), 304.2ms
Speed: 1.3ms preprocess, 304.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xa8aT8toEA01W9fq8s3AhA_180.JPG: 480x640 1 Waste, 297.6ms
Speed: 1.2ms preprocess, 297.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xa8aT8toEA01W9fq8s3AhA_270.JPG: 480x640 (no detections), 300.7ms
Speed: 1.3ms preprocess, 300.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xa9_oDL6MMHzGuNPrywBMw_0.JPG: 480x640 (no detections), 302.6ms
Speed: 1.6ms preprocess, 302.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xa9_oDL6MMHzGuNPrywBMw_90.JPG: 480x640 (no detections), 301.2ms
Speed: 1.2ms preprocess, 301.2ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xa9_oDL6MMHzGuNPrywBMw_180.JPG: 480x640 (no detections), 307.7ms
Speed: 1.1ms preprocess, 307.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xa9_oDL6MMHzGuNPrywBMw_270.JPG: 480x640 (no detections), 298.0ms
Speed: 1.2ms preprocess, 298.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xaB4Ni5sogt_TfcM9JUehg_0.JPG: 480x640 (no detections), 295.6ms
Speed: 1.2ms preprocess, 295.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xaB4Ni5sogt_TfcM9JUehg_90.JPG: 480x640 (no detections), 300.3ms
Speed: 1.1ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xaB4Ni5sogt_TfcM9JUehg_180.JPG: 480x640 (no detections), 306.5ms
Speed: 1.1ms preprocess, 306.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xaB4Ni5sogt_TfcM9JUehg_270.JPG: 480x640 (no detections), 303.4ms
Speed: 1.0ms preprocess, 303.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xaGgRa9rCE1eNex76YHBqQ_0.JPG: 480x640 (no detections), 296.1ms
Speed: 1.1ms preprocess, 296.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xaGgRa9rCE1eNex76YHBqQ_90.JPG: 480x640 (no detections), 303.3ms
Speed: 1.2ms preprocess, 303.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xaGgRa9rCE1eNex76YHBqQ_180.JPG: 480x640 (no detections), 301.6ms
Speed: 1.2ms preprocess, 301.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xaGgRa9rCE1eNex76YHBqQ_270.JPG: 480x640 (no detections), 306.5ms
Speed: 1.2ms preprocess, 306.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xaK_yoqFJzEDcnD8yHPx0Q_0.JPG: 480x640 (no detections), 301.5ms
Speed: 1.3ms preprocess, 301.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xaK_yoqFJzEDcnD8yHPx0Q_90.JPG: 480x640 (no detections), 303.5ms
Speed: 1.4ms preprocess, 303.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xaK_yoqFJzEDcnD8yHPx0Q_180.JPG: 480x640 (no detections), 303.6ms
Speed: 1.3ms preprocess, 303.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xaK_yoqFJzEDcnD8yHPx0Q_270.JPG: 480x640 (no detections), 299.8ms
Speed: 1.2ms preprocess, 299.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xaLfkrrnbAz00_D6wSONKg_0.JPG: 480x640 (no detections), 305.6ms
Speed: 1.0ms preprocess, 305.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xaLfkrrnbAz00_D6wSONKg_90.JPG: 480x640 (no detections), 299.2ms
Speed: 1.2ms preprocess, 299.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xaLfkrrnbAz00_D6wSONKg_180.JPG: 480x640 (no detections), 300.0ms
Speed: 1.2ms preprocess, 300.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xaLfkrrnbAz00_D6wSONKg_270.JPG: 480x640 (no detections), 298.0ms
Speed: 1.2ms preprocess, 298.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xaMnGzDb5RSw5n0CoZvusA_0.JPG: 480x640 1 Waste, 297.1ms
Speed: 1.2ms preprocess, 297.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xaMnGzDb5RSw5n0CoZvusA_90.JPG: 480x640 (no detections), 296.1ms
Speed: 1.2ms preprocess, 296.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xaMnGzDb5RSw5n0CoZvusA_180.JPG: 480x640 (no detections), 299.4ms
Speed: 1.1ms preprocess, 299.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xaMnGzDb5RSw5n0CoZvusA_270.JPG: 480x640 (no detections), 302.7ms
Speed: 1.2ms preprocess, 302.7ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xaOZyl_dLWafynTyfeulXA_0.JPG: 480x640 (no detections), 309.0ms
Speed: 1.2ms preprocess, 309.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xaOZyl_dLWafynTyfeulXA_90.JPG: 480x640 (no detections), 317.2ms
Speed: 1.3ms preprocess, 317.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xaOZyl_dLWafynTyfeulXA_180.JPG: 480x640 (no detections), 303.5ms
Speed: 1.2ms preprocess, 303.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xaOZyl_dLWafynTyfeulXA_270.JPG: 480x640 (no detections), 303.5ms
Speed: 1.2ms preprocess, 303.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xaQirqzj7TmxYyZi5I_W9w_0.JPG: 480x640 (no detections), 304.4ms
Speed: 1.2ms preprocess, 304.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xaQirqzj7TmxYyZi5I_W9w_90.JPG: 480x640 (no detections), 317.9ms
Speed: 1.2ms preprocess, 317.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xaQirqzj7TmxYyZi5I_W9w_180.JPG: 480x640 (no detections), 308.6ms
Speed: 1.3ms preprocess, 308.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xaQirqzj7TmxYyZi5I_W9w_270.JPG: 480x640 (no detections), 300.3ms
Speed: 1.1ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xaQsfYzRXtQ-r48WgtlnWg_0.JPG: 480x640 (no detections), 300.8ms
Speed: 1.1ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xaQsfYzRXtQ-r48WgtlnWg_90.JPG: 480x640 (no detections), 297.0ms
Speed: 1.2ms preprocess, 297.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xaQsfYzRXtQ-r48WgtlnWg_180.JPG: 480x640 (no detections), 299.4ms
Speed: 1.1ms preprocess, 299.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xaQsfYzRXtQ-r48WgtlnWg_270.JPG: 480x640 (no detections), 392.4ms
Speed: 1.1ms preprocess, 392.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xaZP7HYSQyM_vcfn6f488Q_0.JPG: 480x640 (no detections), 305.0ms
Speed: 1.1ms preprocess, 305.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xaZP7HYSQyM_vcfn6f488Q_90.JPG: 480x640 (no detections), 302.2ms
Speed: 1.4ms preprocess, 302.2ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xaZP7HYSQyM_vcfn6f488Q_180.JPG: 480x640 (no detections), 303.5ms
Speed: 1.4ms preprocess, 303.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xaZP7HYSQyM_vcfn6f488Q_270.JPG: 480x640 (no detections), 304.1ms
Speed: 1.3ms preprocess, 304.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xa_7XFzKVFQxSFt-igu-SA_0.JPG: 480x640 (no detections), 295.7ms
Speed: 1.5ms preprocess, 295.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xa_7XFzKVFQxSFt-igu-SA_90.JPG: 480x640 (no detections), 305.8ms
Speed: 1.1ms preprocess, 305.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xa_7XFzKVFQxSFt-igu-SA_180.JPG: 480x640 (no detections), 296.0ms
Speed: 1.2ms preprocess, 296.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xa_7XFzKVFQxSFt-igu-SA_270.JPG: 480x640 (no detections), 303.4ms
Speed: 1.1ms preprocess, 303.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xaao8EeVPnNw9teCZ_r-3A_0.JPG: 480x640 (no detections), 298.4ms
Speed: 1.4ms preprocess, 298.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xaao8EeVPnNw9teCZ_r-3A_90.JPG: 480x640 (no detections), 305.2ms
Speed: 1.3ms preprocess, 305.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xaao8EeVPnNw9teCZ_r-3A_180.JPG: 480x640 (no detections), 295.9ms
Speed: 1.1ms preprocess, 295.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xaao8EeVPnNw9teCZ_r-3A_270.JPG: 480x640 (no detections), 301.2ms
Speed: 1.2ms preprocess, 301.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xagcL4eX4OIv1B6t6hC8nA_0.JPG: 480x640 (no detections), 301.9ms

Speed: 1.4ms preprocess, 301.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xagcL4eX4OIv1B6t6hC8nA_90.JPG: 480x640 1 Waste, 300.0ms
Speed: 1.1ms preprocess, 300.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xagcL4eX4OIv1B6t6hC8nA_180.JPG: 480x640 (no detections), 301.4ms
Speed: 1.2ms preprocess, 301.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xagcL4eX4OIv1B6t6hC8nA_270.JPG: 480x640 (no detections), 295.9ms
Speed: 1.1ms preprocess, 295.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xageZpSM3v4DlEFgml32yA_0.JPG: 480x640 (no detections), 308.4ms
Speed: 1.1ms preprocess, 308.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xageZpSM3v4DlEFgml32yA_90.JPG: 480x640 (no detections), 295.7ms
Speed: 1.0ms preprocess, 295.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xageZpSM3v4DlEFgml32yA_180.JPG: 480x640 (no detections), 305.7ms
Speed: 1.3ms preprocess, 305.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xageZpSM3v4DlEFgml32yA_270.JPG: 480x640 (no detections), 300.9ms
Speed: 1.7ms preprocess, 300.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xais7ALo4ze_daVF_4WXuQ_0.JPG: 480x640 (no detections), 298.8ms
Speed: 1.3ms preprocess, 298.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xais7ALo4ze_daVF_4WXuQ_90.JPG: 480x640 (no detections), 296.9ms
Speed: 1.5ms preprocess, 296.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xais7ALo4ze_daVF_4WXuQ_180.JPG: 480x640 (no detections), 291.4ms
Speed: 1.2ms preprocess, 291.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xais7ALo4ze_daVF_4WXuQ_270.JPG: 480x640 (no detections), 296.6ms
Speed: 1.3ms preprocess, 296.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xanuEaoP8l3lwhXGt9FwNA_0.JPG: 480x640 (no detections), 294.0ms
Speed: 1.3ms preprocess, 294.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xanuEaoP8l3lwhXGt9FwNA_90.JPG: 480x640 (no detections), 294.3ms
Speed: 1.8ms preprocess, 294.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xanuEaoP8l3lwhXGt9FwNA_180.JPG: 480x640 (no detections), 296.0ms
Speed: 1.2ms preprocess, 296.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xanuEaoP8l3lwhXGt9FwNA_270.JPG: 480x640 (no detections), 297.6ms
Speed: 1.2ms preprocess, 297.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xavboJRumv7rF-n_DKz8bQ_0.JPG: 480x640 (no detections), 294.6ms
Speed: 1.2ms preprocess, 294.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xavboJRumv7rF-n_DKz8bQ_90.JPG: 480x640 (no detections), 292.8ms
Speed: 1.2ms preprocess, 292.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xavboJRumv7rF-n_DKz8bQ_180.JPG: 480x640 (no detections), 295.7ms
Speed: 1.2ms preprocess, 295.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/a/xavboJRumv7rF-n_DKz8bQ_270.JPG: 480x640 (no detections), 293.2ms
Speed: 1.3ms preprocess, 293.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xb-a7esoZaEVNpdc5YDlpw_0.JPG: 480x640 (no detections), 308.1ms
Speed: 1.2ms preprocess, 308.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xb-a7esoZaEVNpdc5YDlpw_90.JPG: 480x640 (no detections), 293.4ms
Speed: 1.2ms preprocess, 293.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xb-a7esoZaEVNpdc5YDlpw_180.JPG: 480x640 (no detections), 290.8ms
Speed: 1.3ms preprocess, 290.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xb-a7esoZaEVNpdc5YDlpw_270.JPG: 480x640 (no detections), 297.6ms
Speed: 1.1ms preprocess, 297.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xb2awAtgn19GXdsJiKVyiQ_0.JPG: 480x640 (no detections), 291.2ms
Speed: 1.5ms preprocess, 291.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xb2awAtgn19GXdsJiKVyiQ_90.JPG: 480x640 (no detections), 295.2ms
Speed: 1.0ms preprocess, 295.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xb2awAtgn19GXdsJiKVyiQ_180.JPG: 480x640 (no detections), 294.5ms
Speed: 1.2ms preprocess, 294.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xb2awAtgn19GXdsJiKVyiQ_270.JPG: 480x640 (no detections), 295.1ms
Speed: 1.1ms preprocess, 295.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbB_dwb3e4MpMpPZ70LNsQ_0.JPG: 480x640 (no detections), 298.5ms
Speed: 1.2ms preprocess, 298.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbB_dwb3e4MpMpPZ70LNsQ_90.JPG: 480x640 (no detections), 297.1ms
Speed: 1.0ms preprocess, 297.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbB_dwb3e4MpMpPZ70LNsQ_180.JPG: 480x640 (no detections), 299.0ms
Speed: 1.1ms preprocess, 299.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbB_dwb3e4MpMpPZ70LNsQ_270.JPG: 480x640 (no detections), 293.5ms
Speed: 1.1ms preprocess, 293.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbIcZzIi6e-Qliw-CD7Vrw_0.JPG: 480x640 (no detections), 299.6ms
Speed: 1.2ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbIcZzIi6e-Qliw-CD7Vrw_90.JPG: 480x640 (no detections), 296.5ms
Speed: 1.3ms preprocess, 296.5ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbIcZzIi6e-Qliw-CD7Vrw_180.JPG: 480x640 (no detections), 294.4ms
Speed: 1.4ms preprocess, 294.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbIcZzIi6e-Qliw-CD7Vrw_270.JPG: 480x640 (no detections), 295.9ms
Speed: 1.1ms preprocess, 295.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbMnLYXmBUMu5mFuZ9RWbg_0.JPG: 480x640 (no detections), 294.9ms
Speed: 1.2ms preprocess, 294.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbMnLYXmBUMu5mFuZ9RWbg_90.JPG: 480x640 (no detections), 298.6ms
Speed: 1.1ms preprocess, 298.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbMnLYXmBUMu5mFuZ9RWbg_180.JPG: 480x640 (no detections), 296.1ms
Speed: 1.2ms preprocess, 296.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbMnLYXmBUMu5mFuZ9RWbg_270.JPG: 480x640 (no detections), 294.4ms
Speed: 1.1ms preprocess, 294.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbMrFg-rS8A_I29xwYPL6g_0.JPG: 480x640 (no detections), 293.6ms
Speed: 1.1ms preprocess, 293.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbMrFg-rS8A_I29xwYPL6g_90.JPG: 480x640 (no detections), 292.2ms
Speed: 1.2ms preprocess, 292.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbMrFg-rS8A_I29xwYPL6g_180.JPG: 480x640 (no detections), 298.8ms
Speed: 1.2ms preprocess, 298.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbMrFg-rS8A_I29xwYPL6g_270.JPG: 480x640 (no detections), 297.3ms
Speed: 1.3ms preprocess, 297.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbNyT1uD16pQWQFVzTnqJg_0.JPG: 480x640 (no detections), 296.8ms
Speed: 1.1ms preprocess, 296.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbNyT1uD16pQWQFVzTnqJg_90.JPG: 480x640 (no detections), 293.2ms
Speed: 1.1ms preprocess, 293.2ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbNyT1uD16pQWQFVzTnqJg_180.JPG: 480x640 (no detections), 290.3ms
Speed: 1.1ms preprocess, 290.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbNyT1uD16pQWQFVzTnqJg_270.JPG: 480x640 (no detections), 297.5ms
Speed: 1.2ms preprocess, 297.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbRZA8LUkhlmtA-P4SENvQ_0.JPG: 480x640 (no detections), 290.9ms
Speed: 1.1ms preprocess, 290.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbRZA8LUkhlmtA-P4SENvQ_90.JPG: 480x640 (no detections), 292.7ms
Speed: 1.3ms preprocess, 292.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbRZA8LUkhlmtA-P4SENvQ_180.JPG: 480x640 (no detections), 300.6ms
Speed: 1.3ms preprocess, 300.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbRZA8LUkhlmtA-P4SENvQ_270.JPG: 480x640 (no detections), 295.6ms
Speed: 1.1ms preprocess, 295.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbTvcbTUiy46FQG_f9vtyg_0.JPG: 480x640 (no detections), 293.8ms
Speed: 1.5ms preprocess, 293.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbTvcbTUiy46FQG_f9vtyg_90.JPG: 480x640 (no detections), 293.8ms
Speed: 1.2ms preprocess, 293.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbTvcbTUiy46FQG_f9vtyg_180.JPG: 480x640 (no detections), 292.9ms
Speed: 1.4ms preprocess, 292.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbTvcbTUiy46FQG_f9vtyg_270.JPG: 480x640 (no detections), 293.8ms
Speed: 1.3ms preprocess, 293.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbUHgo1ls3yhijGKhN-nWQ_0.JPG: 480x640 (no detections), 294.8ms
Speed: 1.3ms preprocess, 294.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbUHgo1ls3yhijGKhN-nWQ_90.JPG: 480x640 (no detections), 295.9ms
Speed: 1.3ms preprocess, 295.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbUHgo1ls3yhijGKhN-nWQ_180.JPG: 480x640 (no detections), 300.1ms
Speed: 1.2ms preprocess, 300.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbUHgo1ls3yhijGKhN-nWQ_270.JPG: 480x640 (no detections), 290.0ms
Speed: 1.2ms preprocess, 290.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbZDVIAXoPGUlT9WdSfTSg_0.JPG: 480x640 (no detections), 294.2ms
Speed: 1.2ms preprocess, 294.2ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbZDVIAXoPGUlT9WdSfTSg_90.JPG: 480x640 1 Waste, 294.8ms
Speed: 1.3ms preprocess, 294.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbZDVIAXoPGUlT9WdSfTSg_180.JPG: 480x640 (no detections), 296.4ms
Speed: 1.3ms preprocess, 296.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbZDVIAXoPGUlT9WdSfTSg_270.JPG: 480x640 1 Waste, 295.8ms
Speed: 1.2ms preprocess, 295.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbcjLcAnU5OlhClo7zM8nA_0.JPG: 480x640 (no detections), 302.3ms
Speed: 1.5ms preprocess, 302.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbcjLcAnU5OlhClo7zM8nA_90.JPG: 480x640 (no detections), 294.9ms
Speed: 1.3ms preprocess, 294.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbcjLcAnU5OlhClo7zM8nA_180.JPG: 480x640 (no detections), 298.0ms
Speed: 1.3ms preprocess, 298.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbcjLcAnU5OlhClo7zM8nA_270.JPG: 480x640 (no detections), 294.4ms

Speed: 1.1ms preprocess, 294.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbeqwkk6gFAkawhV8Nel4Q_0.JPG: 480x640 (no detections), 292.5ms
Speed: 1.1ms preprocess, 292.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbeqwkk6gFAkawhV8Nel4Q_90.JPG: 480x640 (no detections), 295.4ms
Speed: 1.3ms preprocess, 295.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbeqwkk6gFAkawhV8Nel4Q_180.JPG: 480x640 (no detections), 296.6ms
Speed: 1.4ms preprocess, 296.6ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbeqwkk6gFAkawhV8Nel4Q_270.JPG: 480x640 (no detections), 294.8ms
Speed: 1.1ms preprocess, 294.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbphMc_w87N5xNsdAvcoig_0.JPG: 480x640 (no detections), 297.6ms
Speed: 1.1ms preprocess, 297.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbphMc_w87N5xNsdAvcoig_90.JPG: 480x640 (no detections), 299.6ms
Speed: 1.3ms preprocess, 299.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbphMc_w87N5xNsdAvcoig_180.JPG: 480x640 (no detections), 298.5ms
Speed: 1.2ms preprocess, 298.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbphMc_w87N5xNsdAvcoig_270.JPG: 480x640 (no detections), 294.8ms
Speed: 1.3ms preprocess, 294.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbpnkZWoRtZEpgL33oAh6g_0.JPG: 480x640 (no detections), 294.3ms
Speed: 1.1ms preprocess, 294.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbpnkZWoRtZEpgL33oAh6g_90.JPG: 480x640 (no detections), 296.3ms
Speed: 1.2ms preprocess, 296.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbpnkZWoRtZEpgL33oAh6g_180.JPG: 480x640 (no detections), 296.7ms
Speed: 1.3ms preprocess, 296.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbpnkZWoRtZEpgL33oAh6g_270.JPG: 480x640 (no detections), 295.8ms
Speed: 1.0ms preprocess, 295.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbpybdRJq97R-gtUesTUfg_0.JPG: 480x640 (no detections), 300.9ms
Speed: 1.3ms preprocess, 300.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbpybdRJq97R-gtUesTUfg_90.JPG: 480x640 (no detections), 293.2ms
Speed: 1.1ms preprocess, 293.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbpybdRJq97R-gtUesTUfg_180.JPG: 480x640 (no detections), 298.9ms
Speed: 1.1ms preprocess, 298.9ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbpybdRJq97R-gtUesTUfg_270.JPG: 480x640 (no detections), 300.0ms
Speed: 1.2ms preprocess, 300.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbwj6Pr9L_8alXhR065nXg_0.JPG: 480x640 (no detections), 298.0ms
Speed: 1.1ms preprocess, 298.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbwj6Pr9L_8alXhR065nXg_90.JPG: 480x640 (no detections), 295.4ms
Speed: 1.2ms preprocess, 295.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbwj6Pr9L_8alXhR065nXg_180.JPG: 480x640 (no detections), 295.0ms
Speed: 1.2ms preprocess, 295.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbwj6Pr9L_8alXhR065nXg_270.JPG: 480x640 (no detections), 297.2ms
Speed: 1.2ms preprocess, 297.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbwp6yJvAjpcvbLqBrsxfA_0.JPG: 480x640 (no detections), 297.6ms
Speed: 1.1ms preprocess, 297.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbwp6yJvAjpcvbLqBrsxfA_90.JPG: 480x640 (no detections), 295.6ms
Speed: 1.3ms preprocess, 295.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbwp6yJvAjpcvbLqBrsxfA_180.JPG: 480x640 (no detections), 293.6ms
Speed: 1.1ms preprocess, 293.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbwp6yJvAjpcvbLqBrsxfA_270.JPG: 480x640 (no detections), 291.2ms
Speed: 1.1ms preprocess, 291.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbz7KcekK3XwVmjZ3Xs-Gg_0.JPG: 480x640 (no detections), 292.4ms
Speed: 1.2ms preprocess, 292.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbz7KcekK3XwVmjZ3Xs-Gg_90.JPG: 480x640 2 Wastes, 291.9ms
Speed: 1.1ms preprocess, 291.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbz7KcekK3XwVmjZ3Xs-Gg_180.JPG: 480x640 2 Wastes, 295.4ms
Speed: 1.2ms preprocess, 295.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/B/xbz7KcekK3XwVmjZ3Xs-Gg_270.JPG: 480x640 (no detections), 293.8ms
Speed: 1.4ms preprocess, 293.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xc6RJYYS6U8tW-VYxPX3GA_0.JPG: 480x640 (no detections), 294.3ms
Speed: 1.5ms preprocess, 294.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xc6RJYYS6U8tW-VYxPX3GA_90.JPG: 480x640 (no detections), 292.8ms
Speed: 1.5ms preprocess, 292.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xc6RJYYS6U8tW-VYxPX3GA_180.JPG: 480x640 (no detections), 293.1ms
Speed: 1.1ms preprocess, 293.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xc6RJYYS6U8tW-VYxPX3GA_270.JPG: 480x640 (no detections), 295.8ms
Speed: 1.2ms preprocess, 295.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xc6WNFUCWAy6p2M3Uxu0kQ_0.JPG: 480x640 (no detections), 301.6ms
Speed: 1.4ms preprocess, 301.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xc6WNFUCWAy6p2M3Uxu0kQ_90.JPG: 480x640 (no detections), 293.5ms
Speed: 1.3ms preprocess, 293.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xc6WNFUCWAy6p2M3Uxu0kQ_180.JPG: 480x640 (no detections), 295.5ms
Speed: 1.1ms preprocess, 295.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xc6WNFUCWAy6p2M3Uxu0kQ_270.JPG: 480x640 (no detections), 293.8ms
Speed: 1.3ms preprocess, 293.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xc7-fi_spGrAvu__fAdW6g_0.JPG: 480x640 (no detections), 296.0ms
Speed: 1.5ms preprocess, 296.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xc7-fi_spGrAvu__fAdW6g_90.JPG: 480x640 (no detections), 296.6ms
Speed: 1.1ms preprocess, 296.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xc7-fi_spGrAvu__fAdW6g_180.JPG: 480x640 (no detections), 292.7ms
Speed: 1.4ms preprocess, 292.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xc7-fi_spGrAvu__fAdW6g_270.JPG: 480x640 (no detections), 290.2ms
Speed: 1.3ms preprocess, 290.2ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcC55c8LYIR3mnx0CWcKQw_0.JPG: 480x640 (no detections), 293.7ms
Speed: 1.2ms preprocess, 293.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcC55c8LYIR3mnx0CWcKQw_90.JPG: 480x640 (no detections), 292.5ms
Speed: 1.2ms preprocess, 292.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcC55c8LYIR3mnx0CWcKQw_180.JPG: 480x640 (no detections), 298.8ms
Speed: 1.2ms preprocess, 298.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcC55c8LYIR3mnx0CWcKQw_270.JPG: 480x640 (no detections), 293.1ms
Speed: 1.1ms preprocess, 293.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcFSv3zc7-OIRcVlXe3sgg_0.JPG: 480x640 (no detections), 293.0ms
Speed: 1.2ms preprocess, 293.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcFSv3zc7-OIRcVlXe3sgg_90.JPG: 480x640 (no detections), 295.1ms
Speed: 1.3ms preprocess, 295.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcFSv3zc7-OIRcVlXe3sgg_180.JPG: 480x640 (no detections), 294.2ms
Speed: 1.2ms preprocess, 294.2ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcFSv3zc7-OIRcVlXe3sgg_270.JPG: 480x640 (no detections), 294.6ms
Speed: 1.2ms preprocess, 294.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcGllb-VnuwZQ8LsPloetQ_0.JPG: 480x640 (no detections), 288.6ms
Speed: 1.2ms preprocess, 288.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcGllb-VnuwZQ8LsPloetQ_90.JPG: 480x640 (no detections), 295.4ms
Speed: 1.2ms preprocess, 295.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcGllb-VnuwZQ8LsPloetQ_180.JPG: 480x640 (no detections), 297.7ms
Speed: 1.2ms preprocess, 297.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcGllb-VnuwZQ8LsPloetQ_270.JPG: 480x640 (no detections), 293.2ms
Speed: 1.2ms preprocess, 293.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcJ1JRgu1jQcej_vj5BVHw_0.JPG: 480x640 (no detections), 295.0ms
Speed: 1.1ms preprocess, 295.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcJ1JRgu1jQcej_vj5BVHw_90.JPG: 480x640 (no detections), 298.0ms
Speed: 1.1ms preprocess, 298.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcJ1JRgu1jQcej_vj5BVHw_180.JPG: 480x640 (no detections), 294.5ms
Speed: 1.3ms preprocess, 294.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcJ1JRgu1jQcej_vj5BVHw_270.JPG: 480x640 (no detections), 294.1ms
Speed: 1.2ms preprocess, 294.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcJiV9Qhvfg--saZ5teWYg_0.JPG: 480x640 (no detections), 294.9ms
Speed: 1.2ms preprocess, 294.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcJiV9Qhvfg--saZ5teWYg_90.JPG: 480x640 (no detections), 296.9ms
Speed: 1.2ms preprocess, 296.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcJiV9Qhvfg--saZ5teWYg_180.JPG: 480x640 (no detections), 296.0ms
Speed: 1.7ms preprocess, 296.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcJiV9Qhvfg--saZ5teWYg_270.JPG: 480x640 (no detections), 298.1ms
Speed: 1.2ms preprocess, 298.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcKCiAs3-fWIT3NNF7XCtA_0.JPG: 480x640 (no detections), 295.4ms
Speed: 1.2ms preprocess, 295.4ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcKCiAs3-fWIT3NNF7XCtA_90.JPG: 480x640 (no detections), 295.3ms
Speed: 1.1ms preprocess, 295.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcKCiAs3-fWIT3NNF7XCtA_180.JPG: 480x640 (no detections), 295.9ms
Speed: 1.3ms preprocess, 295.9ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcKCiAs3-fWIT3NNF7XCtA_270.JPG: 480x640 (no detections), 298.8ms
Speed: 2.0ms preprocess, 298.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcME0FdeT8NVcc4BKWtjNw_0.JPG: 480x640 (no detections), 298.0ms
Speed: 1.2ms preprocess, 298.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcME0FdeT8NVcc4BKWtjNw_90.JPG: 480x640 (no detections), 288.0ms
Speed: 1.2ms preprocess, 288.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcME0FdeT8NVcc4BKWtjNw_180.JPG: 480x640 (no detections), 294.0ms

Speed: 1.2ms preprocess, 294.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcME0FdeT8NVcc4BKWtjNw_270.JPG: 480x640 (no detections), 294.6ms
Speed: 1.2ms preprocess, 294.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcNAKvuLEQGuVJVQo4dAuw_0.JPG: 480x640 (no detections), 292.8ms
Speed: 1.3ms preprocess, 292.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcNAKvuLEQGuVJVQo4dAuw_90.JPG: 480x640 1 Waste, 295.8ms
Speed: 1.2ms preprocess, 295.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcNAKvuLEQGuVJVQo4dAuw_180.JPG: 480x640 (no detections), 298.4ms
Speed: 1.8ms preprocess, 298.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcNAKvuLEQGuVJVQo4dAuw_270.JPG: 480x640 (no detections), 291.9ms
Speed: 1.3ms preprocess, 291.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcOE7Yc8c0vPUTSj9wDgWQ_0.JPG: 480x640 (no detections), 297.8ms
Speed: 1.3ms preprocess, 297.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcOE7Yc8c0vPUTSj9wDgWQ_90.JPG: 480x640 (no detections), 296.3ms
Speed: 1.2ms preprocess, 296.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcOE7Yc8c0vPUTSj9wDgWQ_180.JPG: 480x640 (no detections), 293.3ms
Speed: 1.1ms preprocess, 293.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcOE7Yc8c0vPUTSj9wDgWQ_270.JPG: 480x640 (no detections), 290.5ms
Speed: 1.2ms preprocess, 290.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcRuzMY2d-b7goCFcD8pPw_0.JPG: 480x640 (no detections), 298.0ms
Speed: 1.7ms preprocess, 298.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcRuzMY2d-b7goCFcD8pPw_90.JPG: 480x640 (no detections), 291.0ms
Speed: 1.2ms preprocess, 291.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcRuzMY2d-b7goCFcD8pPw_180.JPG: 480x640 (no detections), 297.5ms
Speed: 1.3ms preprocess, 297.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcRuzMY2d-b7goCFcD8pPw_270.JPG: 480x640 1 Waste, 296.2ms
Speed: 1.2ms preprocess, 296.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcS9ViX1qkWzoK6nW7VDYg_0.JPG: 480x640 (no detections), 293.4ms
Speed: 1.2ms preprocess, 293.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcS9ViX1qkWzoK6nW7VDYg_90.JPG: 480x640 (no detections), 289.8ms
Speed: 1.2ms preprocess, 289.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcS9ViX1qkWzoK6nW7VDYg_180.JPG: 480x640 (no detections), 297.8ms
Speed: 1.3ms preprocess, 297.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcS9ViX1qkWzoK6nW7VDYg_270.JPG: 480x640 (no detections), 290.2ms
Speed: 1.0ms preprocess, 290.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcWg2y5gW7Yx_ox8MKeLBw_0.JPG: 480x640 (no detections), 290.8ms
Speed: 1.1ms preprocess, 290.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcWg2y5gW7Yx_ox8MKeLBw_90.JPG: 480x640 (no detections), 294.2ms
Speed: 1.0ms preprocess, 294.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcWg2y5gW7Yx_ox8MKeLBw_180.JPG: 480x640 (no detections), 294.7ms
Speed: 1.1ms preprocess, 294.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcWg2y5gW7Yx_ox8MKeLBw_270.JPG: 480x640 (no detections), 303.1ms
Speed: 1.3ms preprocess, 303.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcXI1zYBPGL1I2BqEeJhJQ_0.JPG: 480x640 (no detections), 294.7ms
Speed: 1.3ms preprocess, 294.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcXI1zYBPGL1I2BqEeJhJQ_90.JPG: 480x640 (no detections), 296.5ms
Speed: 1.1ms preprocess, 296.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcXI1zYBPGL1I2BqEeJhJQ_180.JPG: 480x640 (no detections), 292.1ms
Speed: 1.1ms preprocess, 292.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcXI1zYBPGL1I2BqEeJhJQ_270.JPG: 480x640 (no detections), 291.3ms
Speed: 1.1ms preprocess, 291.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcXcN186utxbKb9KYGYqAg_0.JPG: 480x640 (no detections), 300.1ms
Speed: 1.4ms preprocess, 300.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcXcN186utxbKb9KYGYqAg_90.JPG: 480x640 (no detections), 293.7ms
Speed: 1.2ms preprocess, 293.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcXcN186utxbKb9KYGYqAg_180.JPG: 480x640 (no detections), 292.6ms
Speed: 1.1ms preprocess, 292.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcXcN186utxbKb9KYGYqAg_270.JPG: 480x640 (no detections), 294.1ms
Speed: 1.4ms preprocess, 294.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcbNKqJSp4YiMS_R72cgcg_0.JPG: 480x640 (no detections), 298.7ms
Speed: 1.5ms preprocess, 298.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcbNKqJSp4YiMS_R72cgcg_90.JPG: 480x640 (no detections), 296.2ms
Speed: 1.2ms preprocess, 296.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcbNKqJSp4YiMS_R72cgcg_180.JPG: 480x640 3 Wastes, 294.5ms
Speed: 1.3ms preprocess, 294.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcbNKqJSp4YiMS_R72cgcg_270.JPG: 480x640 1 Waste, 301.1ms
Speed: 1.1ms preprocess, 301.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcd2MuRHhmvDwl0rBwImhg_0.JPG: 480x640 (no detections), 299.4ms
Speed: 1.2ms preprocess, 299.4ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcd2MuRHhmvDwl0rBwImhg_90.JPG: 480x640 (no detections), 291.4ms
Speed: 1.2ms preprocess, 291.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcd2MuRHhmvDwl0rBwImhg_180.JPG: 480x640 (no detections), 294.3ms
Speed: 1.1ms preprocess, 294.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcd2MuRHhmvDwl0rBwImhg_270.JPG: 480x640 (no detections), 294.5ms
Speed: 1.1ms preprocess, 294.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xce7kgSwUxhG-wkEMGY6wg_0.JPG: 480x640 (no detections), 294.9ms
Speed: 1.1ms preprocess, 294.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xce7kgSwUxhG-wkEMGY6wg_90.JPG: 480x640 (no detections), 292.3ms
Speed: 1.4ms preprocess, 292.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xce7kgSwUxhG-wkEMGY6wg_180.JPG: 480x640 (no detections), 292.6ms
Speed: 1.3ms preprocess, 292.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xce7kgSwUxhG-wkEMGY6wg_270.JPG: 480x640 (no detections), 292.8ms
Speed: 1.0ms preprocess, 292.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcedeGVaj8HJVklQAqYaWg_0.JPG: 480x640 (no detections), 293.2ms
Speed: 1.1ms preprocess, 293.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcedeGVaj8HJVklQAqYaWg_90.JPG: 480x640 (no detections), 298.8ms
Speed: 1.4ms preprocess, 298.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcedeGVaj8HJVklQAqYaWg_180.JPG: 480x640 (no detections), 291.7ms
Speed: 1.3ms preprocess, 291.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcedeGVaj8HJVklQAqYaWg_270.JPG: 480x640 (no detections), 292.7ms
Speed: 1.1ms preprocess, 292.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcgA1MVoSlTT1DLmt0MfcA_0.JPG: 480x640 (no detections), 298.9ms
Speed: 1.6ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcgA1MVoSlTT1DLmt0MfcA_90.JPG: 480x640 (no detections), 314.8ms
Speed: 1.5ms preprocess, 314.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcgA1MVoSlTT1DLmt0MfcA_180.JPG: 480x640 (no detections), 326.4ms
Speed: 1.3ms preprocess, 326.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcgA1MVoSlTT1DLmt0MfcA_270.JPG: 480x640 (no detections), 313.4ms
Speed: 1.1ms preprocess, 313.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcgOb906UpuC1eQK9IMaZw_0.JPG: 480x640 (no detections), 319.2ms
Speed: 1.2ms preprocess, 319.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcgOb906UpuC1eQK9IMaZw_90.JPG: 480x640 (no detections), 309.5ms
Speed: 1.3ms preprocess, 309.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcgOb906UpuC1eQK9IMaZw_180.JPG: 480x640 (no detections), 297.6ms
Speed: 1.2ms preprocess, 297.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcgOb906UpuC1eQK9IMaZw_270.JPG: 480x640 (no detections), 300.4ms
Speed: 1.0ms preprocess, 300.4ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcgRPMrh514PD4Vs4vwmgQ_0.JPG: 480x640 (no detections), 303.8ms
Speed: 1.2ms preprocess, 303.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcgRPMrh514PD4Vs4vwmgQ_90.JPG: 480x640 (no detections), 303.0ms
Speed: 1.0ms preprocess, 303.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcgRPMrh514PD4Vs4vwmgQ_180.JPG: 480x640 (no detections), 298.2ms
Speed: 1.3ms preprocess, 298.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcgRPMrh514PD4Vs4vwmgQ_270.JPG: 480x640 (no detections), 300.7ms
Speed: 2.4ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xciyQVxCr4Qeho6kCMpoVQ_0.JPG: 480x640 (no detections), 296.5ms
Speed: 1.3ms preprocess, 296.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xciyQVxCr4Qeho6kCMpoVQ_90.JPG: 480x640 (no detections), 301.1ms
Speed: 1.1ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xciyQVxCr4Qeho6kCMpoVQ_180.JPG: 480x640 (no detections), 299.0ms
Speed: 1.4ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xciyQVxCr4Qeho6kCMpoVQ_270.JPG: 480x640 (no detections), 303.3ms
Speed: 1.4ms preprocess, 303.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcjWTljdm0B2cbrN3T-FVQ_0.JPG: 480x640 (no detections), 301.0ms
Speed: 1.2ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcjWTljdm0B2cbrN3T-FVQ_90.JPG: 480x640 (no detections), 302.1ms
Speed: 1.1ms preprocess, 302.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcjWTljdm0B2cbrN3T-FVQ_180.JPG: 480x640 (no detections), 300.0ms
Speed: 1.2ms preprocess, 300.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcjWTljdm0B2cbrN3T-FVQ_270.JPG: 480x640 (no detections), 298.3ms
Speed: 1.2ms preprocess, 298.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcpF4bYMnwDxpawi7Cm4Ng_0.JPG: 480x640 (no detections), 303.6ms
Speed: 1.4ms preprocess, 303.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcpF4bYMnwDxpawi7Cm4Ng_90.JPG: 480x640 (no detections), 301.0ms

Speed: 1.2ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcpF4bYMnwDxpawi7Cm4Ng_180.JPG: 480x640 (no detections), 295.8ms
Speed: 1.1ms preprocess, 295.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcpF4bYMnwDxpawi7Cm4Ng_270.JPG: 480x640 (no detections), 296.9ms
Speed: 1.2ms preprocess, 296.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcr1ZK2UJPgmAVskmjWcjg_0.JPG: 480x640 (no detections), 295.0ms
Speed: 1.1ms preprocess, 295.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcr1ZK2UJPgmAVskmjWcjg_90.JPG: 480x640 (no detections), 297.4ms
Speed: 1.1ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcr1ZK2UJPgmAVskmjWcjg_180.JPG: 480x640 (no detections), 302.6ms
Speed: 1.1ms preprocess, 302.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcr1ZK2UJPgmAVskmjWcjg_270.JPG: 480x640 (no detections), 303.9ms
Speed: 1.1ms preprocess, 303.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcxrhIidMiw-O-RQnfqKiA_0.JPG: 480x640 (no detections), 294.4ms
Speed: 1.2ms preprocess, 294.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcxrhIidMiw-O-RQnfqKiA_90.JPG: 480x640 (no detections), 294.1ms
Speed: 1.1ms preprocess, 294.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcxrhIidMiw-O-RQnfqKiA_180.JPG: 480x640 (no detections), 302.0ms
Speed: 1.0ms preprocess, 302.0ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcxrhIidMiw-O-RQnfqKiA_270.JPG: 480x640 (no detections), 301.3ms
Speed: 1.3ms preprocess, 301.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcyhDLicmqDi8jZdCFmhmQ_0.JPG: 480x640 (no detections), 297.1ms
Speed: 1.2ms preprocess, 297.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcyhDLicmqDi8jZdCFmhmQ_90.JPG: 480x640 (no detections), 296.5ms
Speed: 1.2ms preprocess, 296.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcyhDLicmqDi8jZdCFmhmQ_180.JPG: 480x640 (no detections), 299.5ms
Speed: 1.1ms preprocess, 299.5ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/C/xcyhDLicmqDi8jZdCFmhmQ_270.JPG: 480x640 (no detections), 305.8ms
Speed: 1.3ms preprocess, 305.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xd2aeqOucem-vSO1GTJKMA_0.JPG: 480x640 (no detections), 297.0ms
Speed: 1.1ms preprocess, 297.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xd2aeqOucem-vSO1GTJKMA_90.JPG: 480x640 (no detections), 298.5ms
Speed: 1.2ms preprocess, 298.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xd2aeqOucem-vSO1GTJKMA_180.JPG: 480x640 (no detections), 302.2ms
Speed: 1.5ms preprocess, 302.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xd2aeqOucem-vSO1GTJKMA_270.JPG: 480x640 (no detections), 297.4ms
Speed: 1.3ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xd3SHOFg5mJwNwtI6f3mzQ_0.JPG: 480x640 (no detections), 304.6ms
Speed: 1.2ms preprocess, 304.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xd3SHOFg5mJwNwtI6f3mzQ_90.JPG: 480x640 (no detections), 301.3ms
Speed: 1.3ms preprocess, 301.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xd3SHOFg5mJwNwtI6f3mzQ_180.JPG: 480x640 (no detections), 303.8ms
Speed: 1.2ms preprocess, 303.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xd3SHOFg5mJwNwtI6f3mzQ_270.JPG: 480x640 (no detections), 305.7ms
Speed: 2.3ms preprocess, 305.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xd4KA8qZ74QFrHG95la50g_0.JPG: 480x640 (no detections), 301.8ms
Speed: 1.1ms preprocess, 301.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xd4KA8qZ74QFrHG95la50g_90.JPG: 480x640 (no detections), 299.0ms
Speed: 1.0ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xd4KA8qZ74QFrHG95la50g_180.JPG: 480x640 (no detections), 299.5ms
Speed: 1.2ms preprocess, 299.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xd4KA8qZ74QFrHG95la50g_270.JPG: 480x640 (no detections), 304.6ms
Speed: 1.3ms preprocess, 304.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xd7DJ6SX-e4wDxHBbg1b2Q_0.JPG: 480x640 1 Waste, 300.5ms
Speed: 1.3ms preprocess, 300.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xd7DJ6SX-e4wDxHBbg1b2Q_90.JPG: 480x640 (no detections), 299.2ms
Speed: 1.1ms preprocess, 299.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xd7DJ6SX-e4wDxHBbg1b2Q_180.JPG: 480x640 (no detections), 304.8ms
Speed: 1.1ms preprocess, 304.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xd7DJ6SX-e4wDxHBbg1b2Q_270.JPG: 480x640 (no detections), 299.9ms
Speed: 1.1ms preprocess, 299.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xd7IK_Q-0eG8HvfTPDNkiA_0.JPG: 480x640 (no detections), 299.7ms
Speed: 1.1ms preprocess, 299.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xd7IK_Q-0eG8HvfTPDNkiA_90.JPG: 480x640 (no detections), 301.6ms
Speed: 1.3ms preprocess, 301.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xd7IK_Q-0eG8HvfTPDNkiA_180.JPG: 480x640 (no detections), 295.0ms
Speed: 1.2ms preprocess, 295.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xd7IK_Q-0eG8HvfTPDNkiA_270.JPG: 480x640 (no detections), 295.2ms
Speed: 1.1ms preprocess, 295.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xd7TE2DttTfL1LOQtXIzng_0.JPG: 480x640 (no detections), 292.7ms
Speed: 1.2ms preprocess, 292.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xd7TE2DttTfL1LOQtXIzng_90.JPG: 480x640 (no detections), 299.3ms
Speed: 1.3ms preprocess, 299.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xd7TE2DttTfL1LOQtXIzng_180.JPG: 480x640 (no detections), 301.9ms
Speed: 1.1ms preprocess, 301.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xd7TE2DttTfL1LOQtXIzng_270.JPG: 480x640 (no detections), 300.1ms
Speed: 1.1ms preprocess, 300.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdAfuc7YAWG6_h8cW1i-1w_0.JPG: 480x640 (no detections), 301.0ms
Speed: 1.2ms preprocess, 301.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdAfuc7YAWG6_h8cW1i-1w_90.JPG: 480x640 (no detections), 302.6ms
Speed: 1.3ms preprocess, 302.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdAfuc7YAWG6_h8cW1i-1w_180.JPG: 480x640 (no detections), 306.9ms
Speed: 1.5ms preprocess, 306.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdAfuc7YAWG6_h8cW1i-1w_270.JPG: 480x640 (no detections), 300.8ms
Speed: 1.1ms preprocess, 300.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdAgnRYtRD9GNvKM_QQ4Kw_0.JPG: 480x640 1 Waste, 302.5ms
Speed: 1.2ms preprocess, 302.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdAgnRYtRD9GNvKM_QQ4Kw_90.JPG: 480x640 1 Waste, 302.7ms
Speed: 1.4ms preprocess, 302.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdAgnRYtRD9GNvKM_QQ4Kw_180.JPG: 480x640 2 Wastes, 304.3ms
Speed: 1.2ms preprocess, 304.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdAgnRYtRD9GNvKM_QQ4Kw_270.JPG: 480x640 1 Waste, 301.3ms
Speed: 1.4ms preprocess, 301.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdF0AthZrni2dl_1b4DENw_0.JPG: 480x640 (no detections), 295.8ms
Speed: 1.2ms preprocess, 295.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdF0AthZrni2dl_1b4DENw_90.JPG: 480x640 (no detections), 303.4ms
Speed: 1.3ms preprocess, 303.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdF0AthZrni2dl_1b4DENw_180.JPG: 480x640 (no detections), 296.3ms
Speed: 1.6ms preprocess, 296.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdF0AthZrni2dl_1b4DENw_270.JPG: 480x640 (no detections), 301.5ms
Speed: 1.2ms preprocess, 301.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdKleq9XT2ZcJYg_9UMv6A_0.JPG: 480x640 (no detections), 303.1ms
Speed: 1.1ms preprocess, 303.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdKleq9XT2ZcJYg_9UMv6A_90.JPG: 480x640 (no detections), 304.4ms
Speed: 1.1ms preprocess, 304.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdKleq9XT2ZcJYg_9UMv6A_180.JPG: 480x640 (no detections), 304.4ms
Speed: 1.2ms preprocess, 304.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdKleq9XT2ZcJYg_9UMv6A_270.JPG: 480x640 (no detections), 299.8ms
Speed: 1.4ms preprocess, 299.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdPZlwPkATSQNL2jrCrZyQ_0.JPG: 480x640 (no detections), 299.8ms
Speed: 1.3ms preprocess, 299.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdPZlwPkATSQNL2jrCrZyQ_90.JPG: 480x640 (no detections), 300.7ms
Speed: 1.4ms preprocess, 300.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdPZlwPkATSQNL2jrCrZyQ_180.JPG: 480x640 (no detections), 296.7ms
Speed: 1.1ms preprocess, 296.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdPZlwPkATSQNL2jrCrZyQ_270.JPG: 480x640 (no detections), 303.2ms
Speed: 1.1ms preprocess, 303.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdR0zb1nazwhAqPFf943DQ_0.JPG: 480x640 (no detections), 299.0ms
Speed: 1.4ms preprocess, 299.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdR0zb1nazwhAqPFf943DQ_90.JPG: 480x640 1 Waste, 299.6ms
Speed: 1.2ms preprocess, 299.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdR0zb1nazwhAqPFf943DQ_180.JPG: 480x640 (no detections), 301.0ms
Speed: 1.2ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdR0zb1nazwhAqPFf943DQ_270.JPG: 480x640 (no detections), 300.6ms
Speed: 1.1ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdRF8gDw2vSNZjzetUrlcw_0.JPG: 480x640 (no detections), 289.9ms
Speed: 1.2ms preprocess, 289.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdRF8gDw2vSNZjzetUrlcw_90.JPG: 480x640 (no detections), 294.7ms
Speed: 1.2ms preprocess, 294.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdRF8gDw2vSNZjzetUrlcw_180.JPG: 480x640 (no detections), 300.6ms
Speed: 1.1ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdRF8gDw2vSNZjzetUrlcw_270.JPG: 480x640 (no detections), 298.3ms
Speed: 1.2ms preprocess, 298.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdSh4dFB6ezAxikVL1Te0A_0.JPG: 480x640 (no detections), 296.7ms

Speed: 1.3ms preprocess, 296.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdSh4dFB6ezAxikVL1Te0A_90.JPG: 480x640 (no detections), 307.3ms
Speed: 1.1ms preprocess, 307.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdSh4dFB6ezAxikVL1Te0A_180.JPG: 480x640 (no detections), 307.3ms
Speed: 1.3ms preprocess, 307.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdSh4dFB6ezAxikVL1Te0A_270.JPG: 480x640 (no detections), 296.6ms
Speed: 1.1ms preprocess, 296.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdXpKXNSXx035PZwvbju8Q_0.JPG: 480x640 (no detections), 300.5ms
Speed: 1.1ms preprocess, 300.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdXpKXNSXx035PZwvbju8Q_90.JPG: 480x640 (no detections), 302.2ms
Speed: 1.4ms preprocess, 302.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdXpKXNSXx035PZwvbju8Q_180.JPG: 480x640 (no detections), 298.2ms
Speed: 1.1ms preprocess, 298.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdXpKXNSXx035PZwvbju8Q_270.JPG: 480x640 (no detections), 305.3ms
Speed: 1.1ms preprocess, 305.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdZm52myhmsoUobKt55S4g_0.JPG: 480x640 (no detections), 297.6ms
Speed: 1.2ms preprocess, 297.6ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdZm52myhmsoUobKt55S4g_90.JPG: 480x640 (no detections), 299.8ms
Speed: 1.1ms preprocess, 299.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdZm52myhmsoUobKt55S4g_180.JPG: 480x640 (no detections), 300.0ms
Speed: 1.1ms preprocess, 300.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdZm52myhmsoUobKt55S4g_270.JPG: 480x640 (no detections), 301.8ms
Speed: 1.2ms preprocess, 301.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdZzCE0kZMLCLPulwxs-LQ_0.JPG: 480x640 (no detections), 299.0ms
Speed: 1.3ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdZzCE0kZMLCLPulwxs-LQ_90.JPG: 480x640 (no detections), 294.2ms
Speed: 1.0ms preprocess, 294.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdZzCE0kZMLCLPulwxs-LQ_180.JPG: 480x640 (no detections), 308.8ms
Speed: 1.4ms preprocess, 308.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdZzCE0kZMLCLPulwxs-LQ_270.JPG: 480x640 (no detections), 298.9ms
Speed: 1.1ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdak_7920qujY4KYnstrAQ_0.JPG: 480x640 (no detections), 286.3ms
Speed: 1.0ms preprocess, 286.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdak_7920qujY4KYnstrAQ_90.JPG: 480x640 1 Waste, 295.0ms
Speed: 1.2ms preprocess, 295.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdak_7920qujY4KYnstrAQ_180.JPG: 480x640 (no detections), 306.7ms
Speed: 1.2ms preprocess, 306.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdak_7920qujY4KYnstrAQ_270.JPG: 480x640 (no detections), 299.2ms
Speed: 1.8ms preprocess, 299.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdbHvgfpwRO_sh8joZXkSg_0.JPG: 480x640 (no detections), 301.3ms
Speed: 1.5ms preprocess, 301.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdbHvgfpwRO_sh8joZXkSg_90.JPG: 480x640 (no detections), 298.2ms
Speed: 1.2ms preprocess, 298.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdbHvgfpwRO_sh8joZXkSg_180.JPG: 480x640 (no detections), 296.3ms
Speed: 1.2ms preprocess, 296.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdbHvgfpwRO_sh8joZXkSg_270.JPG: 480x640 (no detections), 303.5ms
Speed: 1.9ms preprocess, 303.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdgIoXVkXnKWXZhUIyIdaQ_0.JPG: 480x640 (no detections), 294.9ms
Speed: 1.1ms preprocess, 294.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdgIoXVkXnKWXZhUIyIdaQ_90.JPG: 480x640 (no detections), 297.2ms
Speed: 1.3ms preprocess, 297.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdgIoXVkXnKWXZhUIyIdaQ_180.JPG: 480x640 (no detections), 301.3ms
Speed: 1.2ms preprocess, 301.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdgIoXVkXnKWXZhUIyIdaQ_270.JPG: 480x640 (no detections), 297.2ms
Speed: 1.9ms preprocess, 297.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdkQk9Yq8606esgkfe8v2A_0.JPG: 480x640 (no detections), 302.9ms
Speed: 1.1ms preprocess, 302.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdkQk9Yq8606esgkfe8v2A_90.JPG: 480x640 (no detections), 301.5ms
Speed: 1.0ms preprocess, 301.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdkQk9Yq8606esgkfe8v2A_180.JPG: 480x640 2 Wastes, 301.9ms
Speed: 1.2ms preprocess, 301.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdkQk9Yq8606esgkfe8v2A_270.JPG: 480x640 1 Waste, 298.3ms
Speed: 1.2ms preprocess, 298.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdoHpT-xOuUFt-roN-pgjA_0.JPG: 480x640 (no detections), 294.4ms
Speed: 1.0ms preprocess, 294.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdoHpT-xOuUFt-roN-pgjA_90.JPG: 480x640 (no detections), 301.0ms
Speed: 1.1ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdoHpT-xOuUFt-roN-pgjA_180.JPG: 480x640 (no detections), 304.7ms
Speed: 1.4ms preprocess, 304.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdoHpT-xOuUFt-roN-pgjA_270.JPG: 480x640 (no detections), 304.0ms
Speed: 1.2ms preprocess, 304.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdqpujAQZqZFljltA2Mxhg_0.JPG: 480x640 (no detections), 313.4ms
Speed: 1.4ms preprocess, 313.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdqpujAQZqZFljltA2Mxhg_90.JPG: 480x640 (no detections), 302.0ms
Speed: 1.2ms preprocess, 302.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdqpujAQZqZFljltA2Mxhg_180.JPG: 480x640 (no detections), 298.0ms
Speed: 1.2ms preprocess, 298.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xdqpujAQZqZFljltA2Mxhg_270.JPG: 480x640 (no detections), 297.2ms
Speed: 2.2ms preprocess, 297.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xduU6NtgcKInnSbNxdcJ0Q_0.JPG: 480x640 (no detections), 299.9ms
Speed: 9.4ms preprocess, 299.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xduU6NtgcKInnSbNxdcJ0Q_90.JPG: 480x640 (no detections), 295.3ms
Speed: 1.3ms preprocess, 295.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xduU6NtgcKInnSbNxdcJ0Q_180.JPG: 480x640 (no detections), 298.4ms
Speed: 1.3ms preprocess, 298.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/d/xduU6NtgcKInnSbNxdcJ0Q_270.JPG: 480x640 1 Waste, 301.0ms
Speed: 1.2ms preprocess, 301.0ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xe0PY1h1-HwN4AOljUBQlg_0.JPG: 480x640 (no detections), 308.9ms
Speed: 1.6ms preprocess, 308.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xe0PY1h1-HwN4AOljUBQlg_90.JPG: 480x640 (no detections), 295.1ms
Speed: 1.2ms preprocess, 295.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xe0PY1h1-HwN4AOljUBQlg_180.JPG: 480x640 (no detections), 300.2ms
Speed: 1.1ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xe0PY1h1-HwN4AOljUBQlg_270.JPG: 480x640 (no detections), 293.4ms
Speed: 1.1ms preprocess, 293.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xe2XsT5-OC35PJcumi6VCw_0.JPG: 480x640 (no detections), 300.7ms
Speed: 1.0ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xe2XsT5-OC35PJcumi6VCw_90.JPG: 480x640 (no detections), 301.9ms
Speed: 1.6ms preprocess, 301.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xe2XsT5-OC35PJcumi6VCw_180.JPG: 480x640 (no detections), 296.5ms
Speed: 1.7ms preprocess, 296.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xe2XsT5-OC35PJcumi6VCw_270.JPG: 480x640 (no detections), 290.0ms
Speed: 1.2ms preprocess, 290.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xe5_f-XRfvABYVjSsDUZ9w_0.JPG: 480x640 (no detections), 288.8ms
Speed: 1.4ms preprocess, 288.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xe5_f-XRfvABYVjSsDUZ9w_90.JPG: 480x640 (no detections), 290.3ms
Speed: 1.6ms preprocess, 290.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xe5_f-XRfvABYVjSsDUZ9w_180.JPG: 480x640 (no detections), 293.0ms
Speed: 1.2ms preprocess, 293.0ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xe5_f-XRfvABYVjSsDUZ9w_270.JPG: 480x640 (no detections), 295.5ms
Speed: 1.2ms preprocess, 295.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xe8CAHm_kjXLB13tKUMzTQ_0.JPG: 480x640 (no detections), 301.3ms
Speed: 1.0ms preprocess, 301.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xe8CAHm_kjXLB13tKUMzTQ_90.JPG: 480x640 (no detections), 300.1ms
Speed: 1.1ms preprocess, 300.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xe8CAHm_kjXLB13tKUMzTQ_180.JPG: 480x640 (no detections), 300.6ms
Speed: 1.2ms preprocess, 300.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xe8CAHm_kjXLB13tKUMzTQ_270.JPG: 480x640 (no detections), 303.2ms
Speed: 1.3ms preprocess, 303.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeHlzcPEra_HJFai3FgqSg_0.JPG: 480x640 (no detections), 299.7ms
Speed: 1.2ms preprocess, 299.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeHlzcPEra_HJFai3FgqSg_90.JPG: 480x640 (no detections), 298.4ms
Speed: 1.2ms preprocess, 298.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeHlzcPEra_HJFai3FgqSg_180.JPG: 480x640 (no detections), 298.7ms
Speed: 1.0ms preprocess, 298.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeHlzcPEra_HJFai3FgqSg_270.JPG: 480x640 (no detections), 302.6ms
Speed: 1.3ms preprocess, 302.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeLBUN6l466NWXYT_T83Uw_0.JPG: 480x640 (no detections), 297.5ms
Speed: 1.1ms preprocess, 297.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeLBUN6l466NWXYT_T83Uw_90.JPG: 480x640 (no detections), 300.9ms
Speed: 1.7ms preprocess, 300.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeLBUN6l466NWXYT_T83Uw_180.JPG: 480x640 (no detections), 301.3ms
Speed: 1.1ms preprocess, 301.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeLBUN6l466NWXYT_T83Uw_270.JPG: 480x640 (no detections), 299.9ms

Speed: 1.1ms preprocess, 299.9ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeNfy9muRedK4THo0pzWzA_0.JPG: 480x640 (no detections), 297.2ms
Speed: 1.4ms preprocess, 297.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeNfy9muRedK4THo0pzWzA_90.JPG: 480x640 (no detections), 299.6ms
Speed: 1.1ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeNfy9muRedK4THo0pzWzA_180.JPG: 480x640 (no detections), 305.6ms
Speed: 1.3ms preprocess, 305.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeNfy9muRedK4THo0pzWzA_270.JPG: 480x640 (no detections), 299.2ms
Speed: 1.0ms preprocess, 299.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeRrEj0QG_i9M1FVDYGdcA_0.JPG: 480x640 (no detections), 302.5ms
Speed: 1.2ms preprocess, 302.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeRrEj0QG_i9M1FVDYGdcA_90.JPG: 480x640 1 Waste, 296.6ms
Speed: 1.1ms preprocess, 296.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeRrEj0QG_i9M1FVDYGdcA_180.JPG: 480x640 (no detections), 299.1ms
Speed: 1.1ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeRrEj0QG_i9M1FVDYGdcA_270.JPG: 480x640 (no detections), 296.7ms
Speed: 1.1ms preprocess, 296.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeTR0lUo9trKgRbxC5dRkA_0.JPG: 480x640 (no detections), 301.5ms
Speed: 1.3ms preprocess, 301.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeTR0lUo9trKgRbxC5dRkA_90.JPG: 480x640 (no detections), 302.0ms
Speed: 1.6ms preprocess, 302.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeTR0lUo9trKgRbxC5dRkA_180.JPG: 480x640 (no detections), 305.9ms
Speed: 1.2ms preprocess, 305.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeTR0lUo9trKgRbxC5dRkA_270.JPG: 480x640 (no detections), 296.6ms
Speed: 1.1ms preprocess, 296.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeU8e5b331iL3frzhZhYFA_0.JPG: 480x640 (no detections), 294.5ms
Speed: 1.1ms preprocess, 294.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeU8e5b331iL3frzhZhYFA_90.JPG: 480x640 (no detections), 298.4ms
Speed: 1.1ms preprocess, 298.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeU8e5b331iL3frzhZhYFA_180.JPG: 480x640 (no detections), 303.1ms
Speed: 1.2ms preprocess, 303.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeU8e5b331iL3frzhZhYFA_270.JPG: 480x640 (no detections), 294.5ms
Speed: 2.1ms preprocess, 294.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeU9beVdXYPzPxN_XQi7SQ_0.JPG: 480x640 (no detections), 303.3ms
Speed: 1.3ms preprocess, 303.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeU9beVdXYPzPxN_XQi7SQ_90.JPG: 480x640 (no detections), 295.5ms
Speed: 1.2ms preprocess, 295.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeU9beVdXYPzPxN_XQi7SQ_180.JPG: 480x640 (no detections), 300.0ms
Speed: 1.1ms preprocess, 300.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeU9beVdXYPzPxN_XQi7SQ_270.JPG: 480x640 (no detections), 308.6ms
Speed: 2.2ms preprocess, 308.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeZkZfZvgWimw5fGuvIfMQ_0.JPG: 480x640 (no detections), 301.6ms
Speed: 1.2ms preprocess, 301.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeZkZfZvgWimw5fGuvIfMQ_90.JPG: 480x640 (no detections), 297.6ms
Speed: 1.1ms preprocess, 297.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeZkZfZvgWimw5fGuvIfMQ_180.JPG: 480x640 (no detections), 299.4ms
Speed: 1.1ms preprocess, 299.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeZkZfZvgWimw5fGuvIfMQ_270.JPG: 480x640 (no detections), 299.8ms
Speed: 1.1ms preprocess, 299.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xe_NYL911yQBoATGfMwiMg_0.JPG: 480x640 (no detections), 298.8ms
Speed: 1.4ms preprocess, 298.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xe_NYL911yQBoATGfMwiMg_90.JPG: 480x640 (no detections), 300.0ms
Speed: 1.1ms preprocess, 300.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xe_NYL911yQBoATGfMwiMg_180.JPG: 480x640 (no detections), 295.9ms
Speed: 1.1ms preprocess, 295.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xe_NYL911yQBoATGfMwiMg_270.JPG: 480x640 (no detections), 303.5ms
Speed: 1.3ms preprocess, 303.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeb92WfG2rwx9jzGtnSLLA_0.JPG: 480x640 (no detections), 302.2ms
Speed: 1.1ms preprocess, 302.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeb92WfG2rwx9jzGtnSLLA_90.JPG: 480x640 (no detections), 305.8ms
Speed: 1.1ms preprocess, 305.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeb92WfG2rwx9jzGtnSLLA_180.JPG: 480x640 (no detections), 298.0ms
Speed: 1.3ms preprocess, 298.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeb92WfG2rwx9jzGtnSLLA_270.JPG: 480x640 1 Waste, 298.7ms
Speed: 1.1ms preprocess, 298.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xecZpeAq9hzabT8-xQvhFg_0.JPG: 480x640 (no detections), 297.5ms
Speed: 1.1ms preprocess, 297.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xecZpeAq9hzabT8-xQvhFg_90.JPG: 480x640 (no detections), 306.4ms
Speed: 1.5ms preprocess, 306.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xecZpeAq9hzabT8-xQvhFg_180.JPG: 480x640 (no detections), 405.4ms
Speed: 1.2ms preprocess, 405.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xecZpeAq9hzabT8-xQvhFg_270.JPG: 480x640 (no detections), 319.2ms
Speed: 1.8ms preprocess, 319.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xedBs0k1Cu8SHUHmSsT7AA_0.JPG: 480x640 (no detections), 292.4ms
Speed: 1.2ms preprocess, 292.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xedBs0k1Cu8SHUHmSsT7AA_90.JPG: 480x640 (no detections), 291.4ms
Speed: 1.2ms preprocess, 291.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xedBs0k1Cu8SHUHmSsT7AA_180.JPG: 480x640 (no detections), 304.4ms
Speed: 1.7ms preprocess, 304.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xedBs0k1Cu8SHUHmSsT7AA_270.JPG: 480x640 (no detections), 301.3ms
Speed: 1.5ms preprocess, 301.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeiDE6K5GXc0NZSzUDvD5g_0.JPG: 480x640 (no detections), 304.2ms
Speed: 1.2ms preprocess, 304.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeiDE6K5GXc0NZSzUDvD5g_90.JPG: 480x640 (no detections), 294.1ms
Speed: 1.3ms preprocess, 294.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeiDE6K5GXc0NZSzUDvD5g_180.JPG: 480x640 (no detections), 300.6ms
Speed: 1.2ms preprocess, 300.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeiDE6K5GXc0NZSzUDvD5g_270.JPG: 480x640 (no detections), 297.4ms
Speed: 1.1ms preprocess, 297.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeieg75BE_kpssSlnqg6Qw_0.JPG: 480x640 (no detections), 303.3ms
Speed: 1.1ms preprocess, 303.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeieg75BE_kpssSlnqg6Qw_90.JPG: 480x640 (no detections), 297.5ms
Speed: 1.3ms preprocess, 297.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeieg75BE_kpssSlnqg6Qw_180.JPG: 480x640 (no detections), 302.3ms
Speed: 1.9ms preprocess, 302.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeieg75BE_kpssSlnqg6Qw_270.JPG: 480x640 (no detections), 300.4ms
Speed: 1.3ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeijBuVozcx0s3XRqYsx6A_0.JPG: 480x640 (no detections), 302.0ms
Speed: 1.7ms preprocess, 302.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeijBuVozcx0s3XRqYsx6A_90.JPG: 480x640 (no detections), 301.2ms
Speed: 1.3ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeijBuVozcx0s3XRqYsx6A_180.JPG: 480x640 (no detections), 302.4ms
Speed: 1.1ms preprocess, 302.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeijBuVozcx0s3XRqYsx6A_270.JPG: 480x640 (no detections), 303.1ms
Speed: 1.3ms preprocess, 303.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeoj0ajE-tjJccKhkAbYTA_0.JPG: 480x640 1 Waste, 298.9ms
Speed: 1.5ms preprocess, 298.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeoj0ajE-tjJccKhkAbYTA_90.JPG: 480x640 (no detections), 303.8ms
Speed: 1.2ms preprocess, 303.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeoj0ajE-tjJccKhkAbYTA_180.JPG: 480x640 (no detections), 303.2ms
Speed: 1.3ms preprocess, 303.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeoj0ajE-tjJccKhkAbYTA_270.JPG: 480x640 (no detections), 304.5ms
Speed: 1.2ms preprocess, 304.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeunxbfptwQCHE4XDXoRwg_0.JPG: 480x640 (no detections), 298.4ms
Speed: 1.1ms preprocess, 298.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeunxbfptwQCHE4XDXoRwg_90.JPG: 480x640 (no detections), 300.7ms
Speed: 1.4ms preprocess, 300.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeunxbfptwQCHE4XDXoRwg_180.JPG: 480x640 (no detections), 299.9ms
Speed: 1.2ms preprocess, 299.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xeunxbfptwQCHE4XDXoRwg_270.JPG: 480x640 (no detections), 300.9ms
Speed: 1.7ms preprocess, 300.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xexJ7lU46MKiuOFgoKt3qw_0.JPG: 480x640 (no detections), 298.5ms
Speed: 1.3ms preprocess, 298.5ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xexJ7lU46MKiuOFgoKt3qw_90.JPG: 480x640 (no detections), 296.1ms
Speed: 1.3ms preprocess, 296.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xexJ7lU46MKiuOFgoKt3qw_180.JPG: 480x640 (no detections), 304.5ms
Speed: 1.3ms preprocess, 304.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xexJ7lU46MKiuOFgoKt3qw_270.JPG: 480x640 (no detections), 300.6ms
Speed: 1.3ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xey_lAlBUQ3epcg8neLHKA_0.JPG: 480x640 (no detections), 300.7ms
Speed: 1.2ms preprocess, 300.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xey_lAlBUQ3epcg8neLHKA_90.JPG: 480x640 (no detections), 296.0ms
Speed: 1.2ms preprocess, 296.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xey_lAlBUQ3epcg8neLHKA_180.JPG: 480x640 (no detections), 307.1ms

Speed: 1.2ms preprocess, 307.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/e/xey_lAlBUQ3epcg8neLHKA_270.JPG: 480x640 (no detections), 294.5ms
Speed: 1.6ms preprocess, 294.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xf-LLL5dsMwm3Sa_X-gGwg_0.JPG: 480x640 (no detections), 308.1ms
Speed: 1.5ms preprocess, 308.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xf-LLL5dsMwm3Sa_X-gGwg_90.JPG: 480x640 (no detections), 299.1ms
Speed: 1.2ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xf-LLL5dsMwm3Sa_X-gGwg_180.JPG: 480x640 (no detections), 297.0ms
Speed: 1.1ms preprocess, 297.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xf-LLL5dsMwm3Sa_X-gGwg_270.JPG: 480x640 (no detections), 298.2ms
Speed: 1.2ms preprocess, 298.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xf084gHnOGCY11U9SED09w_0.JPG: 480x640 (no detections), 300.7ms
Speed: 1.3ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xf084gHnOGCY11U9SED09w_90.JPG: 480x640 (no detections), 304.9ms
Speed: 1.1ms preprocess, 304.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xf084gHnOGCY11U9SED09w_180.JPG: 480x640 (no detections), 297.8ms
Speed: 1.3ms preprocess, 297.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xf084gHnOGCY11U9SED09w_270.JPG: 480x640 (no detections), 304.8ms
Speed: 1.2ms preprocess, 304.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xf42SfAwUEFNMWb-PlyS7A_0.JPG: 480x640 (no detections), 303.5ms
Speed: 1.6ms preprocess, 303.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xf42SfAwUEFNMWb-PlyS7A_90.JPG: 480x640 (no detections), 296.7ms
Speed: 1.3ms preprocess, 296.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xf42SfAwUEFNMWb-PlyS7A_180.JPG: 480x640 (no detections), 300.9ms
Speed: 1.8ms preprocess, 300.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xf42SfAwUEFNMWb-PlyS7A_270.JPG: 480x640 (no detections), 296.0ms
Speed: 1.1ms preprocess, 296.0ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xf5dYTvT9bapzHU1ZRz5Nw_0.JPG: 480x640 (no detections), 300.1ms
Speed: 1.5ms preprocess, 300.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xf5dYTvT9bapzHU1ZRz5Nw_90.JPG: 480x640 (no detections), 300.9ms
Speed: 1.0ms preprocess, 300.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xf5dYTvT9bapzHU1ZRz5Nw_180.JPG: 480x640 (no detections), 380.8ms
Speed: 1.3ms preprocess, 380.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xf5dYTvT9bapzHU1ZRz5Nw_270.JPG: 480x640 (no detections), 299.6ms
Speed: 1.2ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xf7TTd2Xs7_nzbfwf6xTmg_0.JPG: 480x640 (no detections), 298.5ms
Speed: 1.2ms preprocess, 298.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xf7TTd2Xs7_nzbfwf6xTmg_90.JPG: 480x640 (no detections), 300.9ms
Speed: 1.3ms preprocess, 300.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xf7TTd2Xs7_nzbfwf6xTmg_180.JPG: 480x640 (no detections), 299.1ms
Speed: 1.2ms preprocess, 299.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xf7TTd2Xs7_nzbfwf6xTmg_270.JPG: 480x640 (no detections), 301.3ms
Speed: 1.1ms preprocess, 301.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xf7Vm_yOxGz91ORjATO8bQ_0.JPG: 480x640 (no detections), 301.3ms
Speed: 1.2ms preprocess, 301.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xf7Vm_yOxGz91ORjATO8bQ_90.JPG: 480x640 (no detections), 296.7ms
Speed: 1.4ms preprocess, 296.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xf7Vm_yOxGz91ORjATO8bQ_180.JPG: 480x640 (no detections), 298.3ms
Speed: 1.1ms preprocess, 298.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xf7Vm_yOxGz91ORjATO8bQ_270.JPG: 480x640 (no detections), 306.3ms
Speed: 1.2ms preprocess, 306.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xf7YncoNaMxNuliHAvQjCw_0.JPG: 480x640 (no detections), 300.9ms
Speed: 1.1ms preprocess, 300.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xf7YncoNaMxNuliHAvQjCw_90.JPG: 480x640 (no detections), 299.1ms
Speed: 1.1ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xf7YncoNaMxNuliHAvQjCw_180.JPG: 480x640 (no detections), 306.3ms
Speed: 1.4ms preprocess, 306.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xf7YncoNaMxNuliHAvQjCw_270.JPG: 480x640 (no detections), 291.9ms
Speed: 1.2ms preprocess, 291.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xf8EaZ9cJRCIUjmOibt8dQ_0.JPG: 480x640 (no detections), 295.4ms
Speed: 1.3ms preprocess, 295.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xf8EaZ9cJRCIUjmOibt8dQ_90.JPG: 480x640 (no detections), 302.5ms
Speed: 1.2ms preprocess, 302.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xf8EaZ9cJRCIUjmOibt8dQ_180.JPG: 480x640 (no detections), 300.7ms
Speed: 1.3ms preprocess, 300.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xf8EaZ9cJRCIUjmOibt8dQ_270.JPG: 480x640 (no detections), 302.0ms
Speed: 1.1ms preprocess, 302.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xf8z7R4BX-QurDC38Ut9Nw_0.JPG: 480x640 (no detections), 304.9ms
Speed: 1.1ms preprocess, 304.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xf8z7R4BX-QurDC38Ut9Nw_90.JPG: 480x640 (no detections), 296.4ms
Speed: 1.2ms preprocess, 296.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xf8z7R4BX-QurDC38Ut9Nw_180.JPG: 480x640 (no detections), 302.6ms
Speed: 1.3ms preprocess, 302.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xf8z7R4BX-QurDC38Ut9Nw_270.JPG: 480x640 (no detections), 295.0ms
Speed: 1.2ms preprocess, 295.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xf9Gif_G4PLWTgUllBERsg_0.JPG: 480x640 (no detections), 299.4ms
Speed: 1.0ms preprocess, 299.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xf9Gif_G4PLWTgUllBERsg_90.JPG: 480x640 (no detections), 298.5ms
Speed: 1.4ms preprocess, 298.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xf9Gif_G4PLWTgUllBERsg_180.JPG: 480x640 (no detections), 310.1ms
Speed: 1.3ms preprocess, 310.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xf9Gif_G4PLWTgUllBERsg_270.JPG: 480x640 (no detections), 303.8ms
Speed: 1.2ms preprocess, 303.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfI0vXE2o9_RzU6f7UKsjQ_0.JPG: 480x640 (no detections), 302.8ms
Speed: 1.1ms preprocess, 302.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfI0vXE2o9_RzU6f7UKsjQ_90.JPG: 480x640 (no detections), 297.7ms
Speed: 1.1ms preprocess, 297.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfI0vXE2o9_RzU6f7UKsjQ_180.JPG: 480x640 (no detections), 298.8ms
Speed: 1.1ms preprocess, 298.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfI0vXE2o9_RzU6f7UKsjQ_270.JPG: 480x640 (no detections), 297.9ms
Speed: 1.4ms preprocess, 297.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfIZCK9ahhcGv2A5qm30hg_0.JPG: 480x640 (no detections), 298.3ms
Speed: 1.2ms preprocess, 298.3ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfIZCK9ahhcGv2A5qm30hg_90.JPG: 480x640 (no detections), 294.6ms
Speed: 1.1ms preprocess, 294.6ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfIZCK9ahhcGv2A5qm30hg_180.JPG: 480x640 (no detections), 301.2ms
Speed: 1.2ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfIZCK9ahhcGv2A5qm30hg_270.JPG: 480x640 (no detections), 298.3ms
Speed: 1.2ms preprocess, 298.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfJRsuLKVVFJm1UCHfTnyQ_0.JPG: 480x640 (no detections), 299.2ms
Speed: 1.2ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfJRsuLKVVFJm1UCHfTnyQ_90.JPG: 480x640 (no detections), 299.4ms
Speed: 1.2ms preprocess, 299.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfJRsuLKVVFJm1UCHfTnyQ_180.JPG: 480x640 (no detections), 298.8ms
Speed: 1.3ms preprocess, 298.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfJRsuLKVVFJm1UCHfTnyQ_270.JPG: 480x640 (no detections), 297.9ms
Speed: 1.2ms preprocess, 297.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfKasNoiMAxCKFg9R_8e5w_0.JPG: 480x640 (no detections), 299.9ms
Speed: 1.4ms preprocess, 299.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfKasNoiMAxCKFg9R_8e5w_90.JPG: 480x640 (no detections), 295.2ms
Speed: 1.1ms preprocess, 295.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfKasNoiMAxCKFg9R_8e5w_180.JPG: 480x640 (no detections), 293.5ms
Speed: 1.2ms preprocess, 293.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfKasNoiMAxCKFg9R_8e5w_270.JPG: 480x640 (no detections), 295.6ms
Speed: 1.4ms preprocess, 295.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfL_tOupMaBcPXgEZR2cUQ_0.JPG: 480x640 (no detections), 295.6ms
Speed: 1.3ms preprocess, 295.6ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfL_tOupMaBcPXgEZR2cUQ_90.JPG: 480x640 (no detections), 298.8ms
Speed: 1.2ms preprocess, 298.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfL_tOupMaBcPXgEZR2cUQ_180.JPG: 480x640 (no detections), 290.0ms
Speed: 1.1ms preprocess, 290.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfL_tOupMaBcPXgEZR2cUQ_270.JPG: 480x640 (no detections), 299.2ms
Speed: 1.0ms preprocess, 299.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfM7xUrM-uMVlOL4hv7UnA_0.JPG: 480x640 (no detections), 301.2ms
Speed: 1.2ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfM7xUrM-uMVlOL4hv7UnA_90.JPG: 480x640 (no detections), 293.6ms
Speed: 1.3ms preprocess, 293.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfM7xUrM-uMVlOL4hv7UnA_180.JPG: 480x640 (no detections), 295.8ms
Speed: 1.2ms preprocess, 295.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfM7xUrM-uMVlOL4hv7UnA_270.JPG: 480x640 (no detections), 294.5ms
Speed: 1.2ms preprocess, 294.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfbHrmx8brqMUNLfTg7-FA_0.JPG: 480x640 (no detections), 296.2ms
Speed: 1.1ms preprocess, 296.2ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfbHrmx8brqMUNLfTg7-FA_90.JPG: 480x640 1 Waste, 297.3ms

Speed: 1.1ms preprocess, 297.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfbHrmx8brqMUNLfTg7-FA_180.JPG: 480x640 (no detections), 298.6ms
Speed: 1.1ms preprocess, 298.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfbHrmx8brqMUNLfTg7-FA_270.JPG: 480x640 (no detections), 293.4ms
Speed: 1.0ms preprocess, 293.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xffPW6P1S6uz0m06y7j0cQ_0.JPG: 480x640 (no detections), 299.0ms
Speed: 1.2ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xffPW6P1S6uz0m06y7j0cQ_90.JPG: 480x640 (no detections), 295.7ms
Speed: 1.3ms preprocess, 295.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xffPW6P1S6uz0m06y7j0cQ_180.JPG: 480x640 (no detections), 300.5ms
Speed: 1.1ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xffPW6P1S6uz0m06y7j0cQ_270.JPG: 480x640 (no detections), 302.2ms
Speed: 1.2ms preprocess, 302.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xffZOOcwWFwaSizihF8N3A_0.JPG: 480x640 (no detections), 297.1ms
Speed: 1.2ms preprocess, 297.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xffZOOcwWFwaSizihF8N3A_90.JPG: 480x640 (no detections), 297.5ms
Speed: 1.6ms preprocess, 297.5ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xffZOOcwWFwaSizihF8N3A_180.JPG: 480x640 (no detections), 296.5ms
Speed: 1.8ms preprocess, 296.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xffZOOcwWFwaSizihF8N3A_270.JPG: 480x640 (no detections), 296.3ms
Speed: 1.3ms preprocess, 296.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfhiTp3xqm0uJMF4bcyRyg_0.JPG: 480x640 (no detections), 295.1ms
Speed: 1.5ms preprocess, 295.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfhiTp3xqm0uJMF4bcyRyg_90.JPG: 480x640 (no detections), 298.6ms
Speed: 1.0ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfhiTp3xqm0uJMF4bcyRyg_180.JPG: 480x640 (no detections), 302.3ms
Speed: 1.1ms preprocess, 302.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfhiTp3xqm0uJMF4bcyRyg_270.JPG: 480x640 (no detections), 296.0ms
Speed: 1.1ms preprocess, 296.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfjNI7vdnlR5Kq5MDwCHuQ_0.JPG: 480x640 (no detections), 294.6ms
Speed: 1.1ms preprocess, 294.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfjNI7vdnlR5Kq5MDwCHuQ_90.JPG: 480x640 (no detections), 296.3ms
Speed: 1.2ms preprocess, 296.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfjNI7vdnlR5Kq5MDwCHuQ_180.JPG: 480x640 (no detections), 298.9ms
Speed: 1.2ms preprocess, 298.9ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfjNI7vdnlR5Kq5MDwCHuQ_270.JPG: 480x640 (no detections), 294.9ms
Speed: 1.2ms preprocess, 294.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfnsCybyORaHy8uRWEcjXg_0.JPG: 480x640 (no detections), 295.1ms
Speed: 1.2ms preprocess, 295.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfnsCybyORaHy8uRWEcjXg_90.JPG: 480x640 1 Waste, 298.8ms
Speed: 1.3ms preprocess, 298.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfnsCybyORaHy8uRWEcjXg_180.JPG: 480x640 (no detections), 293.7ms
Speed: 1.1ms preprocess, 293.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfnsCybyORaHy8uRWEcjXg_270.JPG: 480x640 (no detections), 297.3ms
Speed: 1.5ms preprocess, 297.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfrpy59TqtRJ1gr_NPv8vw_0.JPG: 480x640 (no detections), 295.8ms
Speed: 1.2ms preprocess, 295.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfrpy59TqtRJ1gr_NPv8vw_90.JPG: 480x640 (no detections), 293.4ms
Speed: 1.2ms preprocess, 293.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfrpy59TqtRJ1gr_NPv8vw_180.JPG: 480x640 (no detections), 296.3ms
Speed: 1.1ms preprocess, 296.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfrpy59TqtRJ1gr_NPv8vw_270.JPG: 480x640 (no detections), 298.2ms
Speed: 1.3ms preprocess, 298.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfvlTRCTa1AW_eFTcvrtWw_0.JPG: 480x640 (no detections), 299.7ms
Speed: 1.3ms preprocess, 299.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfvlTRCTa1AW_eFTcvrtWw_90.JPG: 480x640 (no detections), 294.7ms
Speed: 1.2ms preprocess, 294.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfvlTRCTa1AW_eFTcvrtWw_180.JPG: 480x640 (no detections), 294.5ms
Speed: 1.3ms preprocess, 294.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfvlTRCTa1AW_eFTcvrtWw_270.JPG: 480x640 (no detections), 293.5ms
Speed: 1.1ms preprocess, 293.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfvwObUW_7vzL-KZzraf5A_0.JPG: 480x640 (no detections), 296.7ms
Speed: 1.2ms preprocess, 296.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfvwObUW_7vzL-KZzraf5A_90.JPG: 480x640 (no detections), 294.5ms
Speed: 1.3ms preprocess, 294.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfvwObUW_7vzL-KZzraf5A_180.JPG: 480x640 (no detections), 297.0ms
Speed: 1.1ms preprocess, 297.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfvwObUW_7vzL-KZzraf5A_270.JPG: 480x640 (no detections), 291.3ms
Speed: 1.2ms preprocess, 291.3ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfzJdFcYQiikkff0JHXbAg_0.JPG: 480x640 (no detections), 300.8ms
Speed: 1.2ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfzJdFcYQiikkff0JHXbAg_90.JPG: 480x640 (no detections), 295.1ms
Speed: 1.1ms preprocess, 295.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfzJdFcYQiikkff0JHXbAg_180.JPG: 480x640 (no detections), 302.9ms
Speed: 1.2ms preprocess, 302.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/f/xfzJdFcYQiikkff0JHXbAg_270.JPG: 480x640 (no detections), 291.9ms
Speed: 1.3ms preprocess, 291.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xg3Kp88NQpniCWb6aOMkYQ_0.JPG: 480x640 (no detections), 293.5ms
Speed: 1.2ms preprocess, 293.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xg3Kp88NQpniCWb6aOMkYQ_90.JPG: 480x640 (no detections), 292.2ms
Speed: 1.1ms preprocess, 292.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xg3Kp88NQpniCWb6aOMkYQ_180.JPG: 480x640 (no detections), 304.7ms
Speed: 1.2ms preprocess, 304.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xg3Kp88NQpniCWb6aOMkYQ_270.JPG: 480x640 (no detections), 295.1ms
Speed: 1.3ms preprocess, 295.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xg42oKelccUzW8DVkIz--w_0.JPG: 480x640 1 Waste, 293.4ms
Speed: 1.1ms preprocess, 293.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xg42oKelccUzW8DVkIz--w_90.JPG: 480x640 (no detections), 293.0ms
Speed: 1.5ms preprocess, 293.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xg42oKelccUzW8DVkIz--w_180.JPG: 480x640 (no detections), 293.5ms
Speed: 1.2ms preprocess, 293.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xg42oKelccUzW8DVkIz--w_270.JPG: 480x640 (no detections), 298.0ms
Speed: 1.2ms preprocess, 298.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xg8OhuP6DzcK9BNOjHIOLA_0.JPG: 480x640 (no detections), 295.1ms
Speed: 1.2ms preprocess, 295.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xg8OhuP6DzcK9BNOjHIOLA_90.JPG: 480x640 (no detections), 293.5ms
Speed: 1.1ms preprocess, 293.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xg8OhuP6DzcK9BNOjHIOLA_180.JPG: 480x640 (no detections), 292.5ms
Speed: 1.1ms preprocess, 292.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xg8OhuP6DzcK9BNOjHIOLA_270.JPG: 480x640 (no detections), 298.8ms
Speed: 1.0ms preprocess, 298.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgDXKjfFOlJNbtcr-P-XGw_0.JPG: 480x640 (no detections), 294.7ms
Speed: 1.2ms preprocess, 294.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgDXKjfFOlJNbtcr-P-XGw_90.JPG: 480x640 (no detections), 298.7ms
Speed: 1.1ms preprocess, 298.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgDXKjfFOlJNbtcr-P-XGw_180.JPG: 480x640 (no detections), 299.3ms
Speed: 1.1ms preprocess, 299.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgDXKjfFOlJNbtcr-P-XGw_270.JPG: 480x640 (no detections), 297.8ms
Speed: 1.7ms preprocess, 297.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgEwtkEzMQATZ2p-NJDjWg_0.JPG: 480x640 (no detections), 291.4ms
Speed: 1.3ms preprocess, 291.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgEwtkEzMQATZ2p-NJDjWg_90.JPG: 480x640 (no detections), 297.4ms
Speed: 1.2ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgEwtkEzMQATZ2p-NJDjWg_180.JPG: 480x640 (no detections), 291.7ms
Speed: 1.3ms preprocess, 291.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgEwtkEzMQATZ2p-NJDjWg_270.JPG: 480x640 (no detections), 293.1ms
Speed: 1.3ms preprocess, 293.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgL7Eok7WUS4wPsnzMa07Q_0.JPG: 480x640 (no detections), 302.7ms
Speed: 1.4ms preprocess, 302.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgL7Eok7WUS4wPsnzMa07Q_90.JPG: 480x640 1 Waste, 294.3ms
Speed: 1.2ms preprocess, 294.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgL7Eok7WUS4wPsnzMa07Q_180.JPG: 480x640 (no detections), 293.3ms
Speed: 1.2ms preprocess, 293.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgL7Eok7WUS4wPsnzMa07Q_270.JPG: 480x640 (no detections), 293.6ms
Speed: 1.1ms preprocess, 293.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgOlrqCH4-MGe-edbPkg6g_0.JPG: 480x640 (no detections), 298.6ms
Speed: 1.1ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgOlrqCH4-MGe-edbPkg6g_90.JPG: 480x640 (no detections), 294.5ms
Speed: 1.5ms preprocess, 294.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgOlrqCH4-MGe-edbPkg6g_180.JPG: 480x640 (no detections), 298.3ms
Speed: 1.2ms preprocess, 298.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgOlrqCH4-MGe-edbPkg6g_270.JPG: 480x640 (no detections), 294.8ms
Speed: 1.1ms preprocess, 294.8ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgOr7fWWbzkk5-ApeS2dHQ_0.JPG: 480x640 (no detections), 299.7ms

Speed: 1.1ms preprocess, 299.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgOr7fWWbzkk5-ApeS2dHQ_90.JPG: 480x640 (no detections), 295.6ms
Speed: 1.1ms preprocess, 295.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgOr7fWWbzkk5-ApeS2dHQ_180.JPG: 480x640 (no detections), 293.0ms
Speed: 1.1ms preprocess, 293.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgOr7fWWbzkk5-ApeS2dHQ_270.JPG: 480x640 (no detections), 292.4ms
Speed: 1.1ms preprocess, 292.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgQ-bXBrfy_HPuPukajYFg_0.JPG: 480x640 (no detections), 292.4ms
Speed: 1.1ms preprocess, 292.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgQ-bXBrfy_HPuPukajYFg_90.JPG: 480x640 2 Wastes, 296.1ms
Speed: 1.1ms preprocess, 296.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgQ-bXBrfy_HPuPukajYFg_180.JPG: 480x640 1 Waste, 296.4ms
Speed: 1.3ms preprocess, 296.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgQ-bXBrfy_HPuPukajYFg_270.JPG: 480x640 (no detections), 291.1ms
Speed: 1.3ms preprocess, 291.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgRePVxizMF3qWI15hafXg_0.JPG: 480x640 (no detections), 296.9ms
Speed: 1.1ms preprocess, 296.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgRePVxizMF3qWI15hafXg_90.JPG: 480x640 2 Wastes, 295.8ms
Speed: 1.1ms preprocess, 295.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgRePVxizMF3qWI15hafXg_180.JPG: 480x640 (no detections), 291.7ms
Speed: 1.1ms preprocess, 291.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgRePVxizMF3qWI15hafXg_270.JPG: 480x640 (no detections), 296.3ms
Speed: 1.0ms preprocess, 296.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgRha3aA_MxkBTSWQK3uSA_0.JPG: 480x640 (no detections), 296.9ms
Speed: 1.2ms preprocess, 296.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgRha3aA_MxkBTSWQK3uSA_90.JPG: 480x640 (no detections), 292.3ms
Speed: 1.0ms preprocess, 292.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgRha3aA_MxkBTSWQK3uSA_180.JPG: 480x640 (no detections), 293.7ms
Speed: 1.0ms preprocess, 293.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgRha3aA_MxkBTSWQK3uSA_270.JPG: 480x640 (no detections), 295.7ms
Speed: 1.4ms preprocess, 295.7ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgSC8m8VgwbHyvKKTPYsug_0.JPG: 480x640 (no detections), 285.4ms
Speed: 1.2ms preprocess, 285.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgSC8m8VgwbHyvKKTPYsug_90.JPG: 480x640 (no detections), 294.8ms
Speed: 1.2ms preprocess, 294.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgSC8m8VgwbHyvKKTPYsug_180.JPG: 480x640 (no detections), 294.0ms
Speed: 1.6ms preprocess, 294.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgSC8m8VgwbHyvKKTPYsug_270.JPG: 480x640 (no detections), 294.4ms
Speed: 1.2ms preprocess, 294.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgUUmRRxZKzHohvCM-NN9w_0.JPG: 480x640 (no detections), 296.6ms
Speed: 1.3ms preprocess, 296.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgUUmRRxZKzHohvCM-NN9w_90.JPG: 480x640 (no detections), 299.0ms
Speed: 1.5ms preprocess, 299.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgUUmRRxZKzHohvCM-NN9w_180.JPG: 480x640 (no detections), 297.4ms
Speed: 1.3ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgUUmRRxZKzHohvCM-NN9w_270.JPG: 480x640 (no detections), 293.3ms
Speed: 1.2ms preprocess, 293.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgVhVoOxnguLXGVjPDhJ4A_0.JPG: 480x640 (no detections), 299.2ms
Speed: 1.4ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgVhVoOxnguLXGVjPDhJ4A_90.JPG: 480x640 (no detections), 295.1ms
Speed: 1.2ms preprocess, 295.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgVhVoOxnguLXGVjPDhJ4A_180.JPG: 480x640 (no detections), 298.0ms
Speed: 1.1ms preprocess, 298.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgVhVoOxnguLXGVjPDhJ4A_270.JPG: 480x640 (no detections), 296.7ms
Speed: 1.2ms preprocess, 296.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgW2MWADlElmwljQcRBvAg_0.JPG: 480x640 (no detections), 298.9ms
Speed: 1.2ms preprocess, 298.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgW2MWADlElmwljQcRBvAg_90.JPG: 480x640 (no detections), 300.7ms
Speed: 1.1ms preprocess, 300.7ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgW2MWADlElmwljQcRBvAg_180.JPG: 480x640 (no detections), 291.6ms
Speed: 1.0ms preprocess, 291.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgW2MWADlElmwljQcRBvAg_270.JPG: 480x640 (no detections), 295.0ms
Speed: 1.2ms preprocess, 295.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgYjKxCFInD_ddAZ5h3TRA_0.JPG: 480x640 (no detections), 304.8ms
Speed: 1.2ms preprocess, 304.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgYjKxCFInD_ddAZ5h3TRA_90.JPG: 480x640 (no detections), 303.1ms
Speed: 1.2ms preprocess, 303.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgYjKxCFInD_ddAZ5h3TRA_180.JPG: 480x640 (no detections), 297.2ms
Speed: 1.0ms preprocess, 297.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgYjKxCFInD_ddAZ5h3TRA_270.JPG: 480x640 (no detections), 296.6ms
Speed: 1.1ms preprocess, 296.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgZm0Rml5eFzK8sKSgdvdA_0.JPG: 480x640 (no detections), 298.4ms
Speed: 1.3ms preprocess, 298.4ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgZm0Rml5eFzK8sKSgdvdA_90.JPG: 480x640 (no detections), 297.7ms
Speed: 1.2ms preprocess, 297.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgZm0Rml5eFzK8sKSgdvdA_180.JPG: 480x640 (no detections), 297.5ms
Speed: 1.6ms preprocess, 297.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgZm0Rml5eFzK8sKSgdvdA_270.JPG: 480x640 (no detections), 295.4ms
Speed: 1.3ms preprocess, 295.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgaIXyA2arHPAFGm0JqjEQ_0.JPG: 480x640 (no detections), 294.0ms
Speed: 1.6ms preprocess, 294.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgaIXyA2arHPAFGm0JqjEQ_90.JPG: 480x640 (no detections), 298.5ms
Speed: 1.2ms preprocess, 298.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgaIXyA2arHPAFGm0JqjEQ_180.JPG: 480x640 (no detections), 293.6ms
Speed: 1.0ms preprocess, 293.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgaIXyA2arHPAFGm0JqjEQ_270.JPG: 480x640 (no detections), 295.4ms
Speed: 1.2ms preprocess, 295.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgdVb9hhfusUi2xWn0HNUA_0.JPG: 480x640 (no detections), 297.7ms
Speed: 1.2ms preprocess, 297.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgdVb9hhfusUi2xWn0HNUA_90.JPG: 480x640 (no detections), 299.6ms
Speed: 1.0ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgdVb9hhfusUi2xWn0HNUA_180.JPG: 480x640 (no detections), 300.5ms
Speed: 1.2ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgdVb9hhfusUi2xWn0HNUA_270.JPG: 480x640 (no detections), 298.2ms
Speed: 1.1ms preprocess, 298.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgfRgbLSVnyWoNnPVBv75w_0.JPG: 480x640 (no detections), 294.9ms
Speed: 1.1ms preprocess, 294.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgfRgbLSVnyWoNnPVBv75w_90.JPG: 480x640 (no detections), 298.3ms
Speed: 1.5ms preprocess, 298.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgfRgbLSVnyWoNnPVBv75w_180.JPG: 480x640 (no detections), 293.6ms
Speed: 1.1ms preprocess, 293.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgfRgbLSVnyWoNnPVBv75w_270.JPG: 480x640 (no detections), 293.8ms
Speed: 1.3ms preprocess, 293.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xggkOufQcMlRe4Ly7sZxIA_0.JPG: 480x640 (no detections), 297.2ms
Speed: 1.1ms preprocess, 297.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xggkOufQcMlRe4Ly7sZxIA_90.JPG: 480x640 (no detections), 301.5ms
Speed: 1.2ms preprocess, 301.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xggkOufQcMlRe4Ly7sZxIA_180.JPG: 480x640 (no detections), 299.0ms
Speed: 1.2ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xggkOufQcMlRe4Ly7sZxIA_270.JPG: 480x640 (no detections), 293.5ms
Speed: 1.1ms preprocess, 293.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xghCNocKrgiilvsBJO0xHQ_0.JPG: 480x640 (no detections), 299.2ms
Speed: 1.0ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xghCNocKrgiilvsBJO0xHQ_90.JPG: 480x640 (no detections), 298.4ms
Speed: 1.2ms preprocess, 298.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xghCNocKrgiilvsBJO0xHQ_180.JPG: 480x640 (no detections), 294.6ms
Speed: 1.1ms preprocess, 294.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xghCNocKrgiilvsBJO0xHQ_270.JPG: 480x640 (no detections), 293.9ms
Speed: 1.0ms preprocess, 293.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xghoscK14-N3ozIwaNo_cA_0.JPG: 480x640 (no detections), 295.2ms
Speed: 1.1ms preprocess, 295.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xghoscK14-N3ozIwaNo_cA_90.JPG: 480x640 (no detections), 292.9ms
Speed: 1.1ms preprocess, 292.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xghoscK14-N3ozIwaNo_cA_180.JPG: 480x640 (no detections), 301.0ms
Speed: 1.2ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xghoscK14-N3ozIwaNo_cA_270.JPG: 480x640 (no detections), 297.1ms
Speed: 1.7ms preprocess, 297.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgjAXOFeat33vvR8_lxEsQ_0.JPG: 480x640 (no detections), 297.2ms
Speed: 1.2ms preprocess, 297.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgjAXOFeat33vvR8_lxEsQ_90.JPG: 480x640 (no detections), 305.1ms
Speed: 1.2ms preprocess, 305.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgjAXOFeat33vvR8_lxEsQ_180.JPG: 480x640 (no detections), 290.9ms
Speed: 1.1ms preprocess, 290.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgjAXOFeat33vvR8_lxEsQ_270.JPG: 480x640 (no detections), 292.3ms

Speed: 1.1ms preprocess, 292.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgnbhPA8eLmK5RD6w4eQQA_0.JPG: 480x640 (no detections), 295.3ms
Speed: 1.2ms preprocess, 295.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgnbhPA8eLmK5RD6w4eQQA_90.JPG: 480x640 (no detections), 303.2ms
Speed: 1.4ms preprocess, 303.2ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgnbhPA8eLmK5RD6w4eQQA_180.JPG: 480x640 (no detections), 294.4ms
Speed: 1.2ms preprocess, 294.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgnbhPA8eLmK5RD6w4eQQA_270.JPG: 480x640 (no detections), 298.6ms
Speed: 2.2ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgoLNawV39-YCQdlanNNkg_0.JPG: 480x640 (no detections), 292.4ms
Speed: 1.5ms preprocess, 292.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgoLNawV39-YCQdlanNNkg_90.JPG: 480x640 (no detections), 296.8ms
Speed: 1.2ms preprocess, 296.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgoLNawV39-YCQdlanNNkg_180.JPG: 480x640 1 Waste, 299.8ms
Speed: 1.2ms preprocess, 299.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgoLNawV39-YCQdlanNNkg_270.JPG: 480x640 (no detections), 294.3ms
Speed: 1.2ms preprocess, 294.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgsCvJ90Xb4PVRbCY8VMQw_0.JPG: 480x640 (no detections), 294.0ms
Speed: 1.7ms preprocess, 294.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgsCvJ90Xb4PVRbCY8VMQw_90.JPG: 480x640 (no detections), 297.3ms
Speed: 1.8ms preprocess, 297.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgsCvJ90Xb4PVRbCY8VMQw_180.JPG: 480x640 (no detections), 291.2ms
Speed: 1.0ms preprocess, 291.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgsCvJ90Xb4PVRbCY8VMQw_270.JPG: 480x640 (no detections), 296.3ms
Speed: 1.2ms preprocess, 296.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgsvxWGEzMUDB_GkA29GVg_0.JPG: 480x640 (no detections), 292.6ms
Speed: 1.1ms preprocess, 292.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgsvxWGEzMUDB_GkA29GVg_90.JPG: 480x640 (no detections), 299.3ms
Speed: 1.3ms preprocess, 299.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgsvxWGEzMUDB_GkA29GVg_180.JPG: 480x640 (no detections), 295.5ms
Speed: 1.1ms preprocess, 295.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgsvxWGEzMUDB_GkA29GVg_270.JPG: 480x640 (no detections), 294.0ms
Speed: 1.1ms preprocess, 294.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgwLlZwpRYmT3yb5DACywQ_0.JPG: 480x640 (no detections), 300.2ms
Speed: 1.2ms preprocess, 300.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgwLlZwpRYmT3yb5DACywQ_90.JPG: 480x640 (no detections), 299.1ms
Speed: 1.1ms preprocess, 299.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgwLlZwpRYmT3yb5DACywQ_180.JPG: 480x640 (no detections), 296.3ms
Speed: 1.0ms preprocess, 296.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgwLlZwpRYmT3yb5DACywQ_270.JPG: 480x640 (no detections), 296.3ms
Speed: 1.2ms preprocess, 296.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgwQZ9DGoL3XViuUt-CMmg_0.JPG: 480x640 (no detections), 294.9ms
Speed: 1.3ms preprocess, 294.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgwQZ9DGoL3XViuUt-CMmg_90.JPG: 480x640 (no detections), 298.4ms
Speed: 1.3ms preprocess, 298.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgwQZ9DGoL3XViuUt-CMmg_180.JPG: 480x640 (no detections), 294.8ms
Speed: 1.1ms preprocess, 294.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgwQZ9DGoL3XViuUt-CMmg_270.JPG: 480x640 (no detections), 294.6ms
Speed: 1.1ms preprocess, 294.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgwt2Xw8p_1gzXilJj2xPw_0.JPG: 480x640 (no detections), 289.0ms
Speed: 1.0ms preprocess, 289.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgwt2Xw8p_1gzXilJj2xPw_90.JPG: 480x640 (no detections), 291.5ms
Speed: 1.1ms preprocess, 291.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgwt2Xw8p_1gzXilJj2xPw_180.JPG: 480x640 (no detections), 302.6ms
Speed: 1.2ms preprocess, 302.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/g/xgwt2Xw8p_1gzXilJj2xPw_270.JPG: 480x640 (no detections), 294.8ms
Speed: 1.3ms preprocess, 294.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xh-hnAbHqz6H4Vr-ZFnkFA_0.JPG: 480x640 (no detections), 296.0ms
Speed: 1.1ms preprocess, 296.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xh-hnAbHqz6H4Vr-ZFnkFA_90.JPG: 480x640 (no detections), 298.0ms
Speed: 1.3ms preprocess, 298.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xh-hnAbHqz6H4Vr-ZFnkFA_180.JPG: 480x640 (no detections), 293.7ms
Speed: 1.3ms preprocess, 293.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xh-hnAbHqz6H4Vr-ZFnkFA_270.JPG: 480x640 (no detections), 302.6ms
Speed: 1.1ms preprocess, 302.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xh1-RBjWZ2n6A78a2TMIqw_0.JPG: 480x640 (no detections), 296.1ms
Speed: 1.2ms preprocess, 296.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xh1-RBjWZ2n6A78a2TMIqw_90.JPG: 480x640 (no detections), 297.0ms
Speed: 2.0ms preprocess, 297.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xh1-RBjWZ2n6A78a2TMIqw_180.JPG: 480x640 (no detections), 294.8ms
Speed: 1.2ms preprocess, 294.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xh1-RBjWZ2n6A78a2TMIqw_270.JPG: 480x640 (no detections), 290.7ms
Speed: 1.2ms preprocess, 290.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xh17uFOzyq7rSWi9T8c3GQ_0.JPG: 480x640 (no detections), 295.5ms
Speed: 1.2ms preprocess, 295.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xh17uFOzyq7rSWi9T8c3GQ_90.JPG: 480x640 (no detections), 296.7ms
Speed: 1.2ms preprocess, 296.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xh17uFOzyq7rSWi9T8c3GQ_180.JPG: 480x640 (no detections), 294.6ms
Speed: 1.1ms preprocess, 294.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xh17uFOzyq7rSWi9T8c3GQ_270.JPG: 480x640 (no detections), 292.9ms
Speed: 1.2ms preprocess, 292.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xh325QYJSTcfEPJLeL1Lrw_0.JPG: 480x640 (no detections), 295.1ms
Speed: 1.6ms preprocess, 295.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xh325QYJSTcfEPJLeL1Lrw_90.JPG: 480x640 (no detections), 297.8ms
Speed: 1.2ms preprocess, 297.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xh325QYJSTcfEPJLeL1Lrw_180.JPG: 480x640 (no detections), 299.5ms
Speed: 1.1ms preprocess, 299.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xh325QYJSTcfEPJLeL1Lrw_270.JPG: 480x640 (no detections), 287.5ms
Speed: 1.2ms preprocess, 287.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xh44KTZux2DhMmSqMezUBw_0.JPG: 480x640 (no detections), 296.8ms
Speed: 1.2ms preprocess, 296.8ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xh44KTZux2DhMmSqMezUBw_90.JPG: 480x640 (no detections), 294.8ms
Speed: 1.1ms preprocess, 294.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xh44KTZux2DhMmSqMezUBw_180.JPG: 480x640 (no detections), 296.3ms
Speed: 1.2ms preprocess, 296.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xh44KTZux2DhMmSqMezUBw_270.JPG: 480x640 (no detections), 290.4ms
Speed: 1.3ms preprocess, 290.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xh4dAoOxy0AHfPn28iaVQw_0.JPG: 480x640 (no detections), 296.2ms
Speed: 1.1ms preprocess, 296.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xh4dAoOxy0AHfPn28iaVQw_90.JPG: 480x640 (no detections), 296.8ms
Speed: 1.6ms preprocess, 296.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xh4dAoOxy0AHfPn28iaVQw_180.JPG: 480x640 (no detections), 295.6ms
Speed: 1.2ms preprocess, 295.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xh4dAoOxy0AHfPn28iaVQw_270.JPG: 480x640 (no detections), 292.9ms
Speed: 1.2ms preprocess, 292.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xh66DiB9a8qWgyeMaFsSSg_0.JPG: 480x640 (no detections), 294.5ms
Speed: 1.2ms preprocess, 294.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xh66DiB9a8qWgyeMaFsSSg_90.JPG: 480x640 (no detections), 296.9ms
Speed: 1.5ms preprocess, 296.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xh66DiB9a8qWgyeMaFsSSg_180.JPG: 480x640 (no detections), 299.3ms
Speed: 1.2ms preprocess, 299.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xh66DiB9a8qWgyeMaFsSSg_270.JPG: 480x640 (no detections), 298.2ms
Speed: 1.1ms preprocess, 298.2ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xh6KEJGu46skE7ytZlmsyA_0.JPG: 480x640 (no detections), 292.5ms
Speed: 1.1ms preprocess, 292.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xh6KEJGu46skE7ytZlmsyA_90.JPG: 480x640 (no detections), 291.1ms
Speed: 1.1ms preprocess, 291.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xh6KEJGu46skE7ytZlmsyA_180.JPG: 480x640 (no detections), 296.0ms
Speed: 1.2ms preprocess, 296.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xh6KEJGu46skE7ytZlmsyA_270.JPG: 480x640 (no detections), 291.5ms
Speed: 1.2ms preprocess, 291.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xh6y36YKEPzffrrwuPEp6A_0.JPG: 480x640 (no detections), 297.2ms
Speed: 1.1ms preprocess, 297.2ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xh6y36YKEPzffrrwuPEp6A_90.JPG: 480x640 (no detections), 299.1ms
Speed: 1.1ms preprocess, 299.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xh6y36YKEPzffrrwuPEp6A_180.JPG: 480x640 (no detections), 295.7ms
Speed: 1.3ms preprocess, 295.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xh6y36YKEPzffrrwuPEp6A_270.JPG: 480x640 (no detections), 296.2ms
Speed: 1.1ms preprocess, 296.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhBJ0sh-IoZCw7EwJtwlhw_0.JPG: 480x640 (no detections), 295.0ms
Speed: 1.1ms preprocess, 295.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhBJ0sh-IoZCw7EwJtwlhw_90.JPG: 480x640 (no detections), 295.9ms
Speed: 1.2ms preprocess, 295.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhBJ0sh-IoZCw7EwJtwlhw_180.JPG: 480x640 (no detections), 293.9ms

Speed: 1.1ms preprocess, 293.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhBJ0sh-IoZCw7EwJtwlhw_270.JPG: 480x640 (no detections), 297.4ms
Speed: 1.2ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhCcgVLlolohveyGgxGIqg_0.JPG: 480x640 (no detections), 301.1ms
Speed: 1.4ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhCcgVLlolohveyGgxGIqg_90.JPG: 480x640 (no detections), 293.4ms
Speed: 1.4ms preprocess, 293.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhCcgVLlolohveyGgxGIqg_180.JPG: 480x640 (no detections), 301.8ms
Speed: 1.7ms preprocess, 301.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhCcgVLlolohveyGgxGIqg_270.JPG: 480x640 1 Waste, 305.0ms
Speed: 1.2ms preprocess, 305.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhEH7S2T52sVGaBPLNmnew_0.JPG: 480x640 (no detections), 295.3ms
Speed: 1.0ms preprocess, 295.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhEH7S2T52sVGaBPLNmnew_90.JPG: 480x640 (no detections), 294.7ms
Speed: 2.1ms preprocess, 294.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhEH7S2T52sVGaBPLNmnew_180.JPG: 480x640 (no detections), 295.3ms
Speed: 1.3ms preprocess, 295.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhEH7S2T52sVGaBPLNmnew_270.JPG: 480x640 (no detections), 295.1ms
Speed: 1.0ms preprocess, 295.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhHUzUReb-GIxCVjGdvvSw_0.JPG: 480x640 (no detections), 293.9ms
Speed: 1.1ms preprocess, 293.9ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhHUzUReb-GIxCVjGdvvSw_90.JPG: 480x640 (no detections), 295.3ms
Speed: 1.4ms preprocess, 295.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhHUzUReb-GIxCVjGdvvSw_180.JPG: 480x640 (no detections), 299.0ms
Speed: 1.2ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhHUzUReb-GIxCVjGdvvSw_270.JPG: 480x640 (no detections), 292.9ms
Speed: 1.1ms preprocess, 292.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhJ26uLslUY0ELmhmOAWxw_0.JPG: 480x640 (no detections), 295.7ms
Speed: 1.1ms preprocess, 295.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhJ26uLslUY0ELmhmOAWxw_90.JPG: 480x640 (no detections), 290.6ms
Speed: 1.2ms preprocess, 290.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhJ26uLslUY0ELmhmOAWxw_180.JPG: 480x640 (no detections), 300.4ms
Speed: 1.1ms preprocess, 300.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhJ26uLslUY0ELmhmOAWxw_270.JPG: 480x640 (no detections), 291.1ms
Speed: 1.2ms preprocess, 291.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhM3K31yD5LPoTErTUcsYQ_0.JPG: 480x640 (no detections), 296.6ms
Speed: 1.4ms preprocess, 296.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhM3K31yD5LPoTErTUcsYQ_90.JPG: 480x640 (no detections), 298.4ms
Speed: 1.2ms preprocess, 298.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhM3K31yD5LPoTErTUcsYQ_180.JPG: 480x640 (no detections), 300.2ms
Speed: 1.7ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhM3K31yD5LPoTErTUcsYQ_270.JPG: 480x640 (no detections), 295.6ms
Speed: 1.3ms preprocess, 295.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhMJWuoatlJw2UwTYM7U5w_0.JPG: 480x640 (no detections), 301.5ms
Speed: 1.1ms preprocess, 301.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhMJWuoatlJw2UwTYM7U5w_90.JPG: 480x640 (no detections), 298.3ms
Speed: 1.1ms preprocess, 298.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhMJWuoatlJw2UwTYM7U5w_180.JPG: 480x640 (no detections), 295.6ms
Speed: 1.3ms preprocess, 295.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhMJWuoatlJw2UwTYM7U5w_270.JPG: 480x640 (no detections), 296.9ms
Speed: 1.3ms preprocess, 296.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhT_K02weAkXiHgbtaNmdQ_0.JPG: 480x640 (no detections), 297.6ms
Speed: 1.2ms preprocess, 297.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhT_K02weAkXiHgbtaNmdQ_90.JPG: 480x640 (no detections), 299.6ms
Speed: 1.4ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhT_K02weAkXiHgbtaNmdQ_180.JPG: 480x640 (no detections), 296.4ms
Speed: 1.1ms preprocess, 296.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhT_K02weAkXiHgbtaNmdQ_270.JPG: 480x640 (no detections), 300.2ms
Speed: 1.1ms preprocess, 300.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhTi7GWveP-H26TTSdDQjg_0.JPG: 480x640 (no detections), 294.9ms
Speed: 1.2ms preprocess, 294.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhTi7GWveP-H26TTSdDQjg_90.JPG: 480x640 (no detections), 290.0ms
Speed: 1.0ms preprocess, 290.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhTi7GWveP-H26TTSdDQjg_180.JPG: 480x640 (no detections), 291.9ms
Speed: 1.2ms preprocess, 291.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhTi7GWveP-H26TTSdDQjg_270.JPG: 480x640 (no detections), 297.7ms
Speed: 1.1ms preprocess, 297.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhUhDDtIxhoKA7ILc4_YLg_0.JPG: 480x640 (no detections), 295.4ms
Speed: 1.2ms preprocess, 295.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhUhDDtIxhoKA7ILc4_YLg_90.JPG: 480x640 (no detections), 291.7ms
Speed: 1.1ms preprocess, 291.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhUhDDtIxhoKA7ILc4_YLg_180.JPG: 480x640 (no detections), 297.7ms
Speed: 1.1ms preprocess, 297.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhUhDDtIxhoKA7ILc4_YLg_270.JPG: 480x640 (no detections), 295.4ms
Speed: 1.2ms preprocess, 295.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhW_JtNsWQRIappqxC3QUg_0.JPG: 480x640 (no detections), 302.7ms
Speed: 1.3ms preprocess, 302.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhW_JtNsWQRIappqxC3QUg_90.JPG: 480x640 (no detections), 293.9ms
Speed: 1.1ms preprocess, 293.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhW_JtNsWQRIappqxC3QUg_180.JPG: 480x640 (no detections), 300.8ms
Speed: 1.0ms preprocess, 300.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhW_JtNsWQRIappqxC3QUg_270.JPG: 480x640 (no detections), 296.3ms
Speed: 1.1ms preprocess, 296.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhYO19m6co2fIobsO9Q9oQ_0.JPG: 480x640 1 Waste, 293.8ms
Speed: 1.2ms preprocess, 293.8ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhYO19m6co2fIobsO9Q9oQ_90.JPG: 480x640 1 Waste, 299.7ms
Speed: 1.3ms preprocess, 299.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhYO19m6co2fIobsO9Q9oQ_180.JPG: 480x640 (no detections), 297.0ms
Speed: 1.2ms preprocess, 297.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhYO19m6co2fIobsO9Q9oQ_270.JPG: 480x640 (no detections), 298.1ms
Speed: 1.2ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhYsIYDMvTz-dcaNWtAO2Q_0.JPG: 480x640 (no detections), 300.8ms
Speed: 1.2ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhYsIYDMvTz-dcaNWtAO2Q_90.JPG: 480x640 (no detections), 295.9ms
Speed: 1.1ms preprocess, 295.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhYsIYDMvTz-dcaNWtAO2Q_180.JPG: 480x640 (no detections), 297.2ms
Speed: 1.3ms preprocess, 297.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhYsIYDMvTz-dcaNWtAO2Q_270.JPG: 480x640 (no detections), 295.4ms
Speed: 1.1ms preprocess, 295.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xh_qcf7Ip7hDR_bPrIJ0WQ_0.JPG: 480x640 1 Waste, 294.7ms
Speed: 1.1ms preprocess, 294.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xh_qcf7Ip7hDR_bPrIJ0WQ_90.JPG: 480x640 (no detections), 294.9ms
Speed: 1.3ms preprocess, 294.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xh_qcf7Ip7hDR_bPrIJ0WQ_180.JPG: 480x640 (no detections), 292.3ms
Speed: 1.2ms preprocess, 292.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xh_qcf7Ip7hDR_bPrIJ0WQ_270.JPG: 480x640 (no detections), 297.9ms
Speed: 1.2ms preprocess, 297.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhdHRN8BeixpFoCubIzSzw_0.JPG: 480x640 (no detections), 294.8ms
Speed: 1.3ms preprocess, 294.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhdHRN8BeixpFoCubIzSzw_90.JPG: 480x640 (no detections), 293.1ms
Speed: 1.4ms preprocess, 293.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhdHRN8BeixpFoCubIzSzw_180.JPG: 480x640 (no detections), 293.0ms
Speed: 1.1ms preprocess, 293.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhdHRN8BeixpFoCubIzSzw_270.JPG: 480x640 (no detections), 296.6ms
Speed: 1.3ms preprocess, 296.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhe2U36PQNH2WiJY2Uvolw_0.JPG: 480x640 (no detections), 295.7ms
Speed: 1.1ms preprocess, 295.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhe2U36PQNH2WiJY2Uvolw_90.JPG: 480x640 (no detections), 292.6ms
Speed: 1.1ms preprocess, 292.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhe2U36PQNH2WiJY2Uvolw_180.JPG: 480x640 (no detections), 295.2ms
Speed: 1.2ms preprocess, 295.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhe2U36PQNH2WiJY2Uvolw_270.JPG: 480x640 (no detections), 296.3ms
Speed: 1.1ms preprocess, 296.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhf-AWCln79X5Ra23c0Ygg_0.JPG: 480x640 (no detections), 291.9ms
Speed: 1.2ms preprocess, 291.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhf-AWCln79X5Ra23c0Ygg_90.JPG: 480x640 (no detections), 295.4ms
Speed: 1.2ms preprocess, 295.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhf-AWCln79X5Ra23c0Ygg_180.JPG: 480x640 (no detections), 299.4ms
Speed: 1.1ms preprocess, 299.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhf-AWCln79X5Ra23c0Ygg_270.JPG: 480x640 (no detections), 298.1ms
Speed: 1.1ms preprocess, 298.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhfG03zLyhPAY46ZBEzjXQ_0.JPG: 480x640 (no detections), 292.6ms
Speed: 1.2ms preprocess, 292.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhfG03zLyhPAY46ZBEzjXQ_90.JPG: 480x640 (no detections), 298.7ms

Speed: 1.2ms preprocess, 298.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhfG03zLyhPAY46ZBEzjXQ_180.JPG: 480x640 (no detections), 293.0ms
Speed: 1.2ms preprocess, 293.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhfG03zLyhPAY46ZBEzjXQ_270.JPG: 480x640 (no detections), 295.4ms
Speed: 1.2ms preprocess, 295.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhfsxLUYnsFTyWkex0DAjw_0.JPG: 480x640 (no detections), 290.1ms
Speed: 1.6ms preprocess, 290.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhfsxLUYnsFTyWkex0DAjw_90.JPG: 480x640 (no detections), 293.6ms
Speed: 1.2ms preprocess, 293.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhfsxLUYnsFTyWkex0DAjw_180.JPG: 480x640 (no detections), 297.4ms
Speed: 1.2ms preprocess, 297.4ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhfsxLUYnsFTyWkex0DAjw_270.JPG: 480x640 1 Waste, 297.4ms
Speed: 1.3ms preprocess, 297.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhg2XTvrNnLLa64PswhJUA_0.JPG: 480x640 (no detections), 293.7ms
Speed: 1.3ms preprocess, 293.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhg2XTvrNnLLa64PswhJUA_90.JPG: 480x640 (no detections), 293.0ms
Speed: 1.2ms preprocess, 293.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhg2XTvrNnLLa64PswhJUA_180.JPG: 480x640 (no detections), 297.4ms
Speed: 1.1ms preprocess, 297.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhg2XTvrNnLLa64PswhJUA_270.JPG: 480x640 (no detections), 294.7ms
Speed: 1.1ms preprocess, 294.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhgwZxH0Q44NGU-9cuf5bA_0.JPG: 480x640 (no detections), 298.1ms
Speed: 1.3ms preprocess, 298.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhgwZxH0Q44NGU-9cuf5bA_90.JPG: 480x640 (no detections), 292.4ms
Speed: 1.2ms preprocess, 292.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhgwZxH0Q44NGU-9cuf5bA_180.JPG: 480x640 (no detections), 301.5ms
Speed: 1.4ms preprocess, 301.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhgwZxH0Q44NGU-9cuf5bA_270.JPG: 480x640 (no detections), 308.8ms
Speed: 1.1ms preprocess, 308.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhjpBKDjUprV4MHDVlQ9BQ_0.JPG: 480x640 (no detections), 303.0ms
Speed: 1.3ms preprocess, 303.0ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhjpBKDjUprV4MHDVlQ9BQ_90.JPG: 480x640 (no detections), 306.0ms
Speed: 1.6ms preprocess, 306.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhjpBKDjUprV4MHDVlQ9BQ_180.JPG: 480x640 (no detections), 321.3ms
Speed: 1.4ms preprocess, 321.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhjpBKDjUprV4MHDVlQ9BQ_270.JPG: 480x640 (no detections), 305.2ms
Speed: 1.1ms preprocess, 305.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhk3sThfGhsIdulgRsCvEw_0.JPG: 480x640 (no detections), 307.2ms
Speed: 1.2ms preprocess, 307.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhk3sThfGhsIdulgRsCvEw_90.JPG: 480x640 (no detections), 308.6ms
Speed: 1.6ms preprocess, 308.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhk3sThfGhsIdulgRsCvEw_180.JPG: 480x640 (no detections), 306.3ms
Speed: 1.3ms preprocess, 306.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhk3sThfGhsIdulgRsCvEw_270.JPG: 480x640 (no detections), 305.5ms
Speed: 1.2ms preprocess, 305.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhltiGn1DuXLLki4UvT3Sw_0.JPG: 480x640 (no detections), 305.1ms
Speed: 1.1ms preprocess, 305.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhltiGn1DuXLLki4UvT3Sw_90.JPG: 480x640 (no detections), 304.0ms
Speed: 1.3ms preprocess, 304.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhltiGn1DuXLLki4UvT3Sw_180.JPG: 480x640 (no detections), 307.1ms
Speed: 1.7ms preprocess, 307.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhltiGn1DuXLLki4UvT3Sw_270.JPG: 480x640 (no detections), 308.4ms
Speed: 1.3ms preprocess, 308.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhmEugiuVIUmMN-SpzD9Mg_0.JPG: 480x640 (no detections), 305.5ms
Speed: 1.2ms preprocess, 305.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhmEugiuVIUmMN-SpzD9Mg_90.JPG: 480x640 (no detections), 300.8ms
Speed: 1.5ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhmEugiuVIUmMN-SpzD9Mg_180.JPG: 480x640 (no detections), 307.6ms
Speed: 1.3ms preprocess, 307.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhmEugiuVIUmMN-SpzD9Mg_270.JPG: 480x640 (no detections), 300.4ms
Speed: 1.4ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhn0FVyygl_3XIhuC18WuQ_0.JPG: 480x640 (no detections), 302.0ms
Speed: 1.2ms preprocess, 302.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhn0FVyygl_3XIhuC18WuQ_90.JPG: 480x640 (no detections), 300.2ms
Speed: 1.6ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhn0FVyygl_3XIhuC18WuQ_180.JPG: 480x640 (no detections), 301.9ms
Speed: 1.0ms preprocess, 301.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhn0FVyygl_3XIhuC18WuQ_270.JPG: 480x640 (no detections), 306.8ms
Speed: 1.1ms preprocess, 306.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhrYOBKHA_34Q8Rp_riybQ_0.JPG: 480x640 (no detections), 308.8ms
Speed: 1.7ms preprocess, 308.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhrYOBKHA_34Q8Rp_riybQ_90.JPG: 480x640 (no detections), 299.3ms
Speed: 1.1ms preprocess, 299.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhrYOBKHA_34Q8Rp_riybQ_180.JPG: 480x640 (no detections), 299.1ms
Speed: 1.2ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhrYOBKHA_34Q8Rp_riybQ_270.JPG: 480x640 (no detections), 297.7ms
Speed: 1.5ms preprocess, 297.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhunUlGLLHiXgG_yOrx-OA_0.JPG: 480x640 (no detections), 301.9ms
Speed: 1.2ms preprocess, 301.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhunUlGLLHiXgG_yOrx-OA_90.JPG: 480x640 (no detections), 298.1ms
Speed: 1.6ms preprocess, 298.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhunUlGLLHiXgG_yOrx-OA_180.JPG: 480x640 (no detections), 306.3ms
Speed: 1.2ms preprocess, 306.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhunUlGLLHiXgG_yOrx-OA_270.JPG: 480x640 (no detections), 302.2ms
Speed: 1.3ms preprocess, 302.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhw-kU2Xa9Aw8axsVqsfxA_0.JPG: 480x640 (no detections), 302.4ms
Speed: 1.2ms preprocess, 302.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhw-kU2Xa9Aw8axsVqsfxA_90.JPG: 480x640 (no detections), 315.4ms
Speed: 1.7ms preprocess, 315.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhw-kU2Xa9Aw8axsVqsfxA_180.JPG: 480x640 (no detections), 306.7ms
Speed: 1.2ms preprocess, 306.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/H/xhw-kU2Xa9Aw8axsVqsfxA_270.JPG: 480x640 (no detections), 302.9ms
Speed: 1.7ms preprocess, 302.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xi1GIZ4Hh2gLrkd4Ro7ZvQ_0.JPG: 480x640 (no detections), 300.3ms
Speed: 1.3ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xi1GIZ4Hh2gLrkd4Ro7ZvQ_90.JPG: 480x640 (no detections), 301.8ms
Speed: 1.3ms preprocess, 301.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xi1GIZ4Hh2gLrkd4Ro7ZvQ_180.JPG: 480x640 (no detections), 300.1ms
Speed: 1.5ms preprocess, 300.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xi1GIZ4Hh2gLrkd4Ro7ZvQ_270.JPG: 480x640 (no detections), 292.1ms
Speed: 1.4ms preprocess, 292.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xi3jc03kWvBG-DnNP3ccZw_0.JPG: 480x640 (no detections), 313.9ms
Speed: 1.2ms preprocess, 313.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xi3jc03kWvBG-DnNP3ccZw_90.JPG: 480x640 (no detections), 307.8ms
Speed: 1.4ms preprocess, 307.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xi3jc03kWvBG-DnNP3ccZw_180.JPG: 480x640 (no detections), 304.8ms
Speed: 1.3ms preprocess, 304.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xi3jc03kWvBG-DnNP3ccZw_270.JPG: 480x640 (no detections), 308.9ms
Speed: 2.4ms preprocess, 308.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xi53AKnoNLPWPVWDCb49kg_0.JPG: 480x640 (no detections), 301.9ms
Speed: 1.3ms preprocess, 301.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xi53AKnoNLPWPVWDCb49kg_90.JPG: 480x640 (no detections), 299.2ms
Speed: 1.2ms preprocess, 299.2ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xi53AKnoNLPWPVWDCb49kg_180.JPG: 480x640 (no detections), 300.8ms
Speed: 1.2ms preprocess, 300.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xi53AKnoNLPWPVWDCb49kg_270.JPG: 480x640 5 Wastes, 301.5ms
Speed: 1.3ms preprocess, 301.5ms inference, 1.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xi5qTK0IhX4pwyqnYUWxNA_0.JPG: 480x640 (no detections), 297.0ms
Speed: 1.2ms preprocess, 297.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xi5qTK0IhX4pwyqnYUWxNA_90.JPG: 480x640 (no detections), 296.4ms
Speed: 1.4ms preprocess, 296.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xi5qTK0IhX4pwyqnYUWxNA_180.JPG: 480x640 (no detections), 297.1ms
Speed: 1.5ms preprocess, 297.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xi5qTK0IhX4pwyqnYUWxNA_270.JPG: 480x640 (no detections), 297.2ms
Speed: 1.2ms preprocess, 297.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xi8R5r0NSS0W6tLNuVaBow_0.JPG: 480x640 (no detections), 294.8ms
Speed: 1.3ms preprocess, 294.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xi8R5r0NSS0W6tLNuVaBow_90.JPG: 480x640 (no detections), 295.2ms
Speed: 1.1ms preprocess, 295.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xi8R5r0NSS0W6tLNuVaBow_180.JPG: 480x640 (no detections), 300.5ms
Speed: 1.2ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xi8R5r0NSS0W6tLNuVaBow_270.JPG: 480x640 (no detections), 300.6ms
Speed: 1.6ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xi9QrYiVQMjgZtIuPUdyJA_0.JPG: 480x640 (no detections), 304.0ms

Speed: 1.8ms preprocess, 304.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xi9QrYiVQMjgZtIuPUdyJA_90.JPG: 480x640 (no detections), 298.9ms
Speed: 1.2ms preprocess, 298.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xi9QrYiVQMjgZtIuPUdyJA_180.JPG: 480x640 (no detections), 294.8ms
Speed: 1.1ms preprocess, 294.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xi9QrYiVQMjgZtIuPUdyJA_270.JPG: 480x640 (no detections), 294.9ms
Speed: 1.2ms preprocess, 294.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiA8fGc6hmy72SBHx_oomA_0.JPG: 480x640 (no detections), 298.8ms
Speed: 1.2ms preprocess, 298.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiA8fGc6hmy72SBHx_oomA_90.JPG: 480x640 (no detections), 303.9ms
Speed: 1.4ms preprocess, 303.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiA8fGc6hmy72SBHx_oomA_180.JPG: 480x640 (no detections), 303.8ms
Speed: 1.2ms preprocess, 303.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiA8fGc6hmy72SBHx_oomA_270.JPG: 480x640 1 Waste, 296.0ms
Speed: 1.1ms preprocess, 296.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiAoi64XPL8IZ1QD_0MtMw_0.JPG: 480x640 (no detections), 298.6ms
Speed: 1.1ms preprocess, 298.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiAoi64XPL8IZ1QD_0MtMw_90.JPG: 480x640 (no detections), 296.8ms
Speed: 1.2ms preprocess, 296.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiAoi64XPL8IZ1QD_0MtMw_180.JPG: 480x640 (no detections), 300.1ms
Speed: 1.4ms preprocess, 300.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiAoi64XPL8IZ1QD_0MtMw_270.JPG: 480x640 (no detections), 303.9ms
Speed: 1.4ms preprocess, 303.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiDXmU1TvzWpFwOjrPEmUg_0.JPG: 480x640 (no detections), 302.0ms
Speed: 1.2ms preprocess, 302.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiDXmU1TvzWpFwOjrPEmUg_90.JPG: 480x640 (no detections), 301.5ms
Speed: 1.5ms preprocess, 301.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiDXmU1TvzWpFwOjrPEmUg_180.JPG: 480x640 (no detections), 302.8ms
Speed: 1.1ms preprocess, 302.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiDXmU1TvzWpFwOjrPEmUg_270.JPG: 480x640 (no detections), 301.3ms
Speed: 1.2ms preprocess, 301.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiEeCjpWj9-OFdgrQMN76g_0.JPG: 480x640 (no detections), 302.3ms
Speed: 1.3ms preprocess, 302.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiEeCjpWj9-OFdgrQMN76g_90.JPG: 480x640 (no detections), 297.4ms
Speed: 1.2ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiEeCjpWj9-OFdgrQMN76g_180.JPG: 480x640 (no detections), 299.7ms
Speed: 1.2ms preprocess, 299.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiEeCjpWj9-OFdgrQMN76g_270.JPG: 480x640 (no detections), 302.9ms
Speed: 1.8ms preprocess, 302.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiEsW7-JdUAxNka3uBQ9rg_0.JPG: 480x640 (no detections), 298.3ms
Speed: 1.0ms preprocess, 298.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiEsW7-JdUAxNka3uBQ9rg_90.JPG: 480x640 (no detections), 304.5ms
Speed: 1.5ms preprocess, 304.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiEsW7-JdUAxNka3uBQ9rg_180.JPG: 480x640 (no detections), 295.3ms
Speed: 1.2ms preprocess, 295.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiEsW7-JdUAxNka3uBQ9rg_270.JPG: 480x640 (no detections), 295.3ms
Speed: 1.1ms preprocess, 295.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiFCKdn3aJw1uDTZ8wx3FQ_0.JPG: 480x640 (no detections), 296.9ms
Speed: 1.0ms preprocess, 296.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiFCKdn3aJw1uDTZ8wx3FQ_90.JPG: 480x640 (no detections), 304.3ms
Speed: 1.1ms preprocess, 304.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiFCKdn3aJw1uDTZ8wx3FQ_180.JPG: 480x640 (no detections), 301.4ms
Speed: 1.3ms preprocess, 301.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiFCKdn3aJw1uDTZ8wx3FQ_270.JPG: 480x640 (no detections), 296.5ms
Speed: 1.2ms preprocess, 296.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiHM_qr8VNBppBWzjmJC7A_0.JPG: 480x640 (no detections), 300.4ms
Speed: 1.3ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiHM_qr8VNBppBWzjmJC7A_90.JPG: 480x640 (no detections), 298.7ms
Speed: 1.1ms preprocess, 298.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiHM_qr8VNBppBWzjmJC7A_180.JPG: 480x640 (no detections), 298.3ms
Speed: 1.1ms preprocess, 298.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiHM_qr8VNBppBWzjmJC7A_270.JPG: 480x640 (no detections), 301.4ms
Speed: 1.4ms preprocess, 301.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiHkwEQpap7LCMtxo2qHGg_0.JPG: 480x640 (no detections), 301.4ms
Speed: 1.6ms preprocess, 301.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiHkwEQpap7LCMtxo2qHGg_90.JPG: 480x640 (no detections), 303.0ms
Speed: 1.0ms preprocess, 303.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiHkwEQpap7LCMtxo2qHGg_180.JPG: 480x640 (no detections), 298.0ms
Speed: 1.3ms preprocess, 298.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiHkwEQpap7LCMtxo2qHGg_270.JPG: 480x640 (no detections), 300.9ms
Speed: 1.1ms preprocess, 300.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiJqm2fLnGcG-93lN4jBPQ_0.JPG: 480x640 (no detections), 308.4ms
Speed: 1.5ms preprocess, 308.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiJqm2fLnGcG-93lN4jBPQ_90.JPG: 480x640 (no detections), 298.4ms
Speed: 1.1ms preprocess, 298.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiJqm2fLnGcG-93lN4jBPQ_180.JPG: 480x640 (no detections), 301.2ms
Speed: 1.3ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiJqm2fLnGcG-93lN4jBPQ_270.JPG: 480x640 (no detections), 302.9ms
Speed: 1.1ms preprocess, 302.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiL4PFYW0j4qYeJIOtOJuQ_0.JPG: 480x640 (no detections), 298.0ms
Speed: 1.1ms preprocess, 298.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiL4PFYW0j4qYeJIOtOJuQ_90.JPG: 480x640 (no detections), 294.6ms
Speed: 1.3ms preprocess, 294.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiL4PFYW0j4qYeJIOtOJuQ_180.JPG: 480x640 (no detections), 298.6ms
Speed: 1.1ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiL4PFYW0j4qYeJIOtOJuQ_270.JPG: 480x640 (no detections), 303.1ms
Speed: 1.3ms preprocess, 303.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiO48AqtW6nNfrx2809VZQ_0.JPG: 480x640 (no detections), 301.5ms
Speed: 1.3ms preprocess, 301.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiO48AqtW6nNfrx2809VZQ_90.JPG: 480x640 (no detections), 297.3ms
Speed: 1.2ms preprocess, 297.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiO48AqtW6nNfrx2809VZQ_180.JPG: 480x640 (no detections), 307.9ms
Speed: 1.8ms preprocess, 307.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiO48AqtW6nNfrx2809VZQ_270.JPG: 480x640 (no detections), 301.4ms
Speed: 1.2ms preprocess, 301.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiOzRM6uWiRDwb82KgqQcw_0.JPG: 480x640 (no detections), 378.0ms
Speed: 1.1ms preprocess, 378.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiOzRM6uWiRDwb82KgqQcw_90.JPG: 480x640 (no detections), 299.8ms
Speed: 1.2ms preprocess, 299.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiOzRM6uWiRDwb82KgqQcw_180.JPG: 480x640 (no detections), 297.5ms
Speed: 1.0ms preprocess, 297.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiOzRM6uWiRDwb82KgqQcw_270.JPG: 480x640 (no detections), 306.4ms
Speed: 1.2ms preprocess, 306.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiRnXO0BKQu7YbUGAre0VQ_0.JPG: 480x640 (no detections), 299.8ms
Speed: 1.2ms preprocess, 299.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiRnXO0BKQu7YbUGAre0VQ_90.JPG: 480x640 (no detections), 299.1ms
Speed: 1.4ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiRnXO0BKQu7YbUGAre0VQ_180.JPG: 480x640 (no detections), 302.6ms
Speed: 1.3ms preprocess, 302.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiRnXO0BKQu7YbUGAre0VQ_270.JPG: 480x640 (no detections), 299.4ms
Speed: 1.0ms preprocess, 299.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiSQ1TCzQPbOvFgZbLr3Eg_0.JPG: 480x640 (no detections), 300.9ms
Speed: 1.2ms preprocess, 300.9ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiSQ1TCzQPbOvFgZbLr3Eg_90.JPG: 480x640 (no detections), 298.6ms
Speed: 1.3ms preprocess, 298.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiSQ1TCzQPbOvFgZbLr3Eg_180.JPG: 480x640 (no detections), 300.4ms
Speed: 1.5ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiSQ1TCzQPbOvFgZbLr3Eg_270.JPG: 480x640 (no detections), 304.1ms
Speed: 1.2ms preprocess, 304.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xictc6aO4HfF0zvpe_stSw_0.JPG: 480x640 (no detections), 297.2ms
Speed: 1.1ms preprocess, 297.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xictc6aO4HfF0zvpe_stSw_90.JPG: 480x640 (no detections), 296.9ms
Speed: 1.2ms preprocess, 296.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xictc6aO4HfF0zvpe_stSw_180.JPG: 480x640 (no detections), 301.2ms
Speed: 1.1ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xictc6aO4HfF0zvpe_stSw_270.JPG: 480x640 (no detections), 297.0ms
Speed: 1.1ms preprocess, 297.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xieyN0SkFQY1RdiQmNk9Mw_0.JPG: 480x640 (no detections), 301.4ms
Speed: 1.6ms preprocess, 301.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xieyN0SkFQY1RdiQmNk9Mw_90.JPG: 480x640 (no detections), 302.9ms
Speed: 1.3ms preprocess, 302.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xieyN0SkFQY1RdiQmNk9Mw_180.JPG: 480x640 (no detections), 297.3ms
Speed: 1.4ms preprocess, 297.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xieyN0SkFQY1RdiQmNk9Mw_270.JPG: 480x640 (no detections), 301.6ms

Speed: 1.2ms preprocess, 301.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xifjEDHQ8dE6KRdMKB7nzw_0.JPG: 480x640 (no detections), 293.3ms
Speed: 1.1ms preprocess, 293.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xifjEDHQ8dE6KRdMKB7nzw_90.JPG: 480x640 (no detections), 298.0ms
Speed: 1.3ms preprocess, 298.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xifjEDHQ8dE6KRdMKB7nzw_180.JPG: 480x640 (no detections), 299.6ms
Speed: 1.2ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xifjEDHQ8dE6KRdMKB7nzw_270.JPG: 480x640 (no detections), 296.0ms
Speed: 1.2ms preprocess, 296.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xig8pzvjwBNT4VJVfazU9g_0.JPG: 480x640 (no detections), 300.1ms
Speed: 1.3ms preprocess, 300.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xig8pzvjwBNT4VJVfazU9g_90.JPG: 480x640 (no detections), 303.0ms
Speed: 1.3ms preprocess, 303.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xig8pzvjwBNT4VJVfazU9g_180.JPG: 480x640 (no detections), 298.5ms
Speed: 1.3ms preprocess, 298.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xig8pzvjwBNT4VJVfazU9g_270.JPG: 480x640 (no detections), 303.0ms
Speed: 1.3ms preprocess, 303.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xii7JAskpwktbQ_qQpGfaw_0.JPG: 480x640 (no detections), 303.0ms
Speed: 1.2ms preprocess, 303.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xii7JAskpwktbQ_qQpGfaw_90.JPG: 480x640 (no detections), 302.6ms
Speed: 1.3ms preprocess, 302.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xii7JAskpwktbQ_qQpGfaw_180.JPG: 480x640 (no detections), 297.4ms
Speed: 1.4ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xii7JAskpwktbQ_qQpGfaw_270.JPG: 480x640 (no detections), 304.1ms
Speed: 1.4ms preprocess, 304.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xis5eosVFKWmBioAADLHwQ_0.JPG: 480x640 (no detections), 299.9ms
Speed: 1.2ms preprocess, 299.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xis5eosVFKWmBioAADLHwQ_90.JPG: 480x640 (no detections), 299.4ms
Speed: 1.3ms preprocess, 299.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xis5eosVFKWmBioAADLHwQ_180.JPG: 480x640 (no detections), 297.0ms
Speed: 1.1ms preprocess, 297.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xis5eosVFKWmBioAADLHwQ_270.JPG: 480x640 (no detections), 299.9ms
Speed: 1.1ms preprocess, 299.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xitbYBCEvtea3o5SvbtXuQ_0.JPG: 480x640 (no detections), 296.9ms
Speed: 1.1ms preprocess, 296.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xitbYBCEvtea3o5SvbtXuQ_90.JPG: 480x640 (no detections), 298.5ms
Speed: 1.2ms preprocess, 298.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xitbYBCEvtea3o5SvbtXuQ_180.JPG: 480x640 (no detections), 299.6ms
Speed: 1.0ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xitbYBCEvtea3o5SvbtXuQ_270.JPG: 480x640 (no detections), 298.9ms
Speed: 1.2ms preprocess, 298.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xivfIGhHXf5opfpS6Wv87A_0.JPG: 480x640 (no detections), 297.8ms
Speed: 1.5ms preprocess, 297.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xivfIGhHXf5opfpS6Wv87A_90.JPG: 480x640 (no detections), 300.0ms
Speed: 1.3ms preprocess, 300.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xivfIGhHXf5opfpS6Wv87A_180.JPG: 480x640 (no detections), 301.2ms
Speed: 1.8ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xivfIGhHXf5opfpS6Wv87A_270.JPG: 480x640 (no detections), 301.1ms
Speed: 1.3ms preprocess, 301.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiw3rVPS_4DxDIrd8CIOLQ_0.JPG: 480x640 (no detections), 300.4ms
Speed: 1.2ms preprocess, 300.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiw3rVPS_4DxDIrd8CIOLQ_90.JPG: 480x640 (no detections), 311.5ms
Speed: 1.1ms preprocess, 311.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiw3rVPS_4DxDIrd8CIOLQ_180.JPG: 480x640 (no detections), 305.7ms
Speed: 1.2ms preprocess, 305.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xiw3rVPS_4DxDIrd8CIOLQ_270.JPG: 480x640 (no detections), 293.1ms
Speed: 1.1ms preprocess, 293.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xixhJHtAwEch3li55VtCHQ_0.JPG: 480x640 (no detections), 291.7ms
Speed: 1.1ms preprocess, 291.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xixhJHtAwEch3li55VtCHQ_90.JPG: 480x640 (no detections), 293.6ms
Speed: 1.2ms preprocess, 293.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xixhJHtAwEch3li55VtCHQ_180.JPG: 480x640 (no detections), 290.7ms
Speed: 1.1ms preprocess, 290.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/i/xixhJHtAwEch3li55VtCHQ_270.JPG: 480x640 (no detections), 296.0ms
Speed: 1.2ms preprocess, 296.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xj-pS5UUWRW_4OAxWr-cjQ_0.JPG: 480x640 (no detections), 297.1ms
Speed: 1.2ms preprocess, 297.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xj-pS5UUWRW_4OAxWr-cjQ_90.JPG: 480x640 (no detections), 291.5ms
Speed: 1.0ms preprocess, 291.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xj-pS5UUWRW_4OAxWr-cjQ_180.JPG: 480x640 (no detections), 298.2ms
Speed: 1.1ms preprocess, 298.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xj-pS5UUWRW_4OAxWr-cjQ_270.JPG: 480x640 (no detections), 288.8ms
Speed: 1.1ms preprocess, 288.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xj-wOkCbX98zx5B8I7Yitw_0.JPG: 480x640 (no detections), 296.4ms
Speed: 1.1ms preprocess, 296.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xj-wOkCbX98zx5B8I7Yitw_90.JPG: 480x640 (no detections), 291.8ms
Speed: 1.1ms preprocess, 291.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xj-wOkCbX98zx5B8I7Yitw_180.JPG: 480x640 (no detections), 289.9ms
Speed: 1.2ms preprocess, 289.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xj-wOkCbX98zx5B8I7Yitw_270.JPG: 480x640 (no detections), 293.4ms
Speed: 1.7ms preprocess, 293.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xj13plAqfwn9uJqnXKZhMw_0.JPG: 480x640 (no detections), 291.9ms
Speed: 1.0ms preprocess, 291.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xj13plAqfwn9uJqnXKZhMw_90.JPG: 480x640 (no detections), 294.6ms
Speed: 1.2ms preprocess, 294.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xj13plAqfwn9uJqnXKZhMw_180.JPG: 480x640 (no detections), 295.3ms
Speed: 1.1ms preprocess, 295.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xj13plAqfwn9uJqnXKZhMw_270.JPG: 480x640 (no detections), 296.7ms
Speed: 1.1ms preprocess, 296.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xj8EIp2Q1hAvjHz_lAG_UA_0.JPG: 480x640 1 Waste, 288.4ms
Speed: 1.1ms preprocess, 288.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xj8EIp2Q1hAvjHz_lAG_UA_90.JPG: 480x640 (no detections), 291.7ms
Speed: 1.2ms preprocess, 291.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xj8EIp2Q1hAvjHz_lAG_UA_180.JPG: 480x640 (no detections), 298.9ms
Speed: 1.1ms preprocess, 298.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xj8EIp2Q1hAvjHz_lAG_UA_270.JPG: 480x640 (no detections), 293.7ms
Speed: 1.2ms preprocess, 293.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjGCOFUjmqwaRYmew7qfBw_0.JPG: 480x640 (no detections), 288.8ms
Speed: 1.1ms preprocess, 288.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjGCOFUjmqwaRYmew7qfBw_90.JPG: 480x640 (no detections), 300.1ms
Speed: 1.2ms preprocess, 300.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjGCOFUjmqwaRYmew7qfBw_180.JPG: 480x640 (no detections), 288.7ms
Speed: 1.2ms preprocess, 288.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjGCOFUjmqwaRYmew7qfBw_270.JPG: 480x640 (no detections), 289.2ms
Speed: 1.3ms preprocess, 289.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjJ5uB3uEjC9HW6c9A215w_0.JPG: 480x640 (no detections), 295.0ms
Speed: 1.1ms preprocess, 295.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjJ5uB3uEjC9HW6c9A215w_90.JPG: 480x640 (no detections), 291.6ms
Speed: 1.6ms preprocess, 291.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjJ5uB3uEjC9HW6c9A215w_180.JPG: 480x640 (no detections), 292.9ms
Speed: 1.4ms preprocess, 292.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjJ5uB3uEjC9HW6c9A215w_270.JPG: 480x640 (no detections), 294.2ms
Speed: 1.1ms preprocess, 294.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjJKQAhJMdJmyYbZFpIUQw_0.JPG: 480x640 1 Waste, 294.7ms
Speed: 1.2ms preprocess, 294.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjJKQAhJMdJmyYbZFpIUQw_90.JPG: 480x640 (no detections), 295.3ms
Speed: 1.1ms preprocess, 295.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjJKQAhJMdJmyYbZFpIUQw_180.JPG: 480x640 (no detections), 293.5ms
Speed: 1.1ms preprocess, 293.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjJKQAhJMdJmyYbZFpIUQw_270.JPG: 480x640 (no detections), 290.7ms
Speed: 1.1ms preprocess, 290.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjJmVumSBQskhuJROJy1Kw_0.JPG: 480x640 (no detections), 292.2ms
Speed: 1.4ms preprocess, 292.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjJmVumSBQskhuJROJy1Kw_90.JPG: 480x640 (no detections), 295.1ms
Speed: 1.3ms preprocess, 295.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjJmVumSBQskhuJROJy1Kw_180.JPG: 480x640 (no detections), 293.7ms
Speed: 1.3ms preprocess, 293.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjJmVumSBQskhuJROJy1Kw_270.JPG: 480x640 (no detections), 297.5ms
Speed: 1.5ms preprocess, 297.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjK49VNCeVvEMvmDFfbqpA_0.JPG: 480x640 (no detections), 292.9ms
Speed: 1.2ms preprocess, 292.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjK49VNCeVvEMvmDFfbqpA_90.JPG: 480x640 (no detections), 291.1ms
Speed: 1.4ms preprocess, 291.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjK49VNCeVvEMvmDFfbqpA_180.JPG: 480x640 (no detections), 298.4ms

Speed: 1.4ms preprocess, 298.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjK49VNCeVvEMvmDFfbqpA_270.JPG: 480x640 (no detections), 293.0ms
Speed: 1.3ms preprocess, 293.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjLZ__H9AQrRjE01c4NP_g_0.JPG: 480x640 (no detections), 288.1ms
Speed: 1.2ms preprocess, 288.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjLZ__H9AQrRjE01c4NP_g_90.JPG: 480x640 (no detections), 292.8ms
Speed: 1.1ms preprocess, 292.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjLZ__H9AQrRjE01c4NP_g_180.JPG: 480x640 (no detections), 294.8ms
Speed: 1.2ms preprocess, 294.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjLZ__H9AQrRjE01c4NP_g_270.JPG: 480x640 (no detections), 299.2ms
Speed: 1.3ms preprocess, 299.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjN-awFYwNvTW-6NNHKNhw_0.JPG: 480x640 (no detections), 293.9ms
Speed: 1.2ms preprocess, 293.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjN-awFYwNvTW-6NNHKNhw_90.JPG: 480x640 (no detections), 297.2ms
Speed: 1.2ms preprocess, 297.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjN-awFYwNvTW-6NNHKNhw_180.JPG: 480x640 (no detections), 298.3ms
Speed: 1.4ms preprocess, 298.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjN-awFYwNvTW-6NNHKNhw_270.JPG: 480x640 (no detections), 290.9ms
Speed: 1.1ms preprocess, 290.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjOrt_6TiWKO31yyPrRi9Q_0.JPG: 480x640 (no detections), 297.4ms
Speed: 1.2ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjOrt_6TiWKO31yyPrRi9Q_90.JPG: 480x640 (no detections), 292.4ms
Speed: 1.4ms preprocess, 292.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjOrt_6TiWKO31yyPrRi9Q_180.JPG: 480x640 (no detections), 291.8ms
Speed: 1.2ms preprocess, 291.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjOrt_6TiWKO31yyPrRi9Q_270.JPG: 480x640 (no detections), 298.6ms
Speed: 1.3ms preprocess, 298.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjQ7iezqFe8-10XSqMujrQ_0.JPG: 480x640 (no detections), 294.7ms
Speed: 1.3ms preprocess, 294.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjQ7iezqFe8-10XSqMujrQ_90.JPG: 480x640 (no detections), 291.0ms
Speed: 1.5ms preprocess, 291.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjQ7iezqFe8-10XSqMujrQ_180.JPG: 480x640 (no detections), 292.0ms
Speed: 1.3ms preprocess, 292.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjQ7iezqFe8-10XSqMujrQ_270.JPG: 480x640 (no detections), 296.7ms
Speed: 1.2ms preprocess, 296.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjQzu4mBpmrhP8rdZt_fyA_0.JPG: 480x640 (no detections), 293.7ms
Speed: 1.2ms preprocess, 293.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjQzu4mBpmrhP8rdZt_fyA_90.JPG: 480x640 (no detections), 290.4ms
Speed: 1.2ms preprocess, 290.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjQzu4mBpmrhP8rdZt_fyA_180.JPG: 480x640 (no detections), 291.2ms
Speed: 1.1ms preprocess, 291.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjQzu4mBpmrhP8rdZt_fyA_270.JPG: 480x640 (no detections), 294.4ms
Speed: 1.4ms preprocess, 294.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjTLmjGEz2CJFd0kP6leow_0.JPG: 480x640 (no detections), 294.5ms
Speed: 1.1ms preprocess, 294.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjTLmjGEz2CJFd0kP6leow_90.JPG: 480x640 (no detections), 293.1ms
Speed: 1.1ms preprocess, 293.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjTLmjGEz2CJFd0kP6leow_180.JPG: 480x640 (no detections), 296.5ms
Speed: 1.2ms preprocess, 296.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjTLmjGEz2CJFd0kP6leow_270.JPG: 480x640 (no detections), 297.8ms
Speed: 1.5ms preprocess, 297.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjUEd0eHTUaP8gYgTwTK8w_0.JPG: 480x640 (no detections), 298.2ms
Speed: 1.2ms preprocess, 298.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjUEd0eHTUaP8gYgTwTK8w_90.JPG: 480x640 (no detections), 295.7ms
Speed: 1.1ms preprocess, 295.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjUEd0eHTUaP8gYgTwTK8w_180.JPG: 480x640 (no detections), 301.5ms
Speed: 1.3ms preprocess, 301.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjUEd0eHTUaP8gYgTwTK8w_270.JPG: 480x640 (no detections), 295.3ms
Speed: 1.2ms preprocess, 295.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjVr00dnL9cr-cb6hBru0Q_0.JPG: 480x640 (no detections), 299.3ms
Speed: 1.1ms preprocess, 299.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjVr00dnL9cr-cb6hBru0Q_90.JPG: 480x640 (no detections), 301.0ms
Speed: 1.3ms preprocess, 301.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjVr00dnL9cr-cb6hBru0Q_180.JPG: 480x640 (no detections), 297.0ms
Speed: 1.1ms preprocess, 297.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjVr00dnL9cr-cb6hBru0Q_270.JPG: 480x640 (no detections), 297.5ms
Speed: 1.3ms preprocess, 297.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjXvyIL9aoK0fIUMZpsurg_0.JPG: 480x640 (no detections), 290.9ms
Speed: 1.1ms preprocess, 290.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjXvyIL9aoK0fIUMZpsurg_90.JPG: 480x640 (no detections), 294.4ms
Speed: 1.0ms preprocess, 294.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjXvyIL9aoK0fIUMZpsurg_180.JPG: 480x640 (no detections), 297.5ms
Speed: 1.3ms preprocess, 297.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjXvyIL9aoK0fIUMZpsurg_270.JPG: 480x640 (no detections), 303.0ms
Speed: 1.3ms preprocess, 303.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjYNvY8qVg21z8drN9T7SQ_0.JPG: 480x640 (no detections), 296.4ms
Speed: 1.2ms preprocess, 296.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjYNvY8qVg21z8drN9T7SQ_90.JPG: 480x640 (no detections), 294.8ms
Speed: 1.1ms preprocess, 294.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjYNvY8qVg21z8drN9T7SQ_180.JPG: 480x640 (no detections), 299.7ms
Speed: 1.2ms preprocess, 299.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjYNvY8qVg21z8drN9T7SQ_270.JPG: 480x640 (no detections), 302.1ms
Speed: 1.1ms preprocess, 302.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjZvel3Gn3bvJX-6Zx3aWw_0.JPG: 480x640 (no detections), 297.4ms
Speed: 1.1ms preprocess, 297.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjZvel3Gn3bvJX-6Zx3aWw_90.JPG: 480x640 (no detections), 302.3ms
Speed: 1.1ms preprocess, 302.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjZvel3Gn3bvJX-6Zx3aWw_180.JPG: 480x640 (no detections), 298.8ms
Speed: 1.2ms preprocess, 298.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjZvel3Gn3bvJX-6Zx3aWw_270.JPG: 480x640 (no detections), 304.4ms
Speed: 1.3ms preprocess, 304.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xja5ndOBeEfE0uAQPQrLrw_0.JPG: 480x640 (no detections), 301.0ms
Speed: 1.2ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xja5ndOBeEfE0uAQPQrLrw_90.JPG: 480x640 (no detections), 300.1ms
Speed: 1.0ms preprocess, 300.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xja5ndOBeEfE0uAQPQrLrw_180.JPG: 480x640 (no detections), 296.8ms
Speed: 1.2ms preprocess, 296.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xja5ndOBeEfE0uAQPQrLrw_270.JPG: 480x640 (no detections), 295.6ms
Speed: 1.2ms preprocess, 295.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjaHdbCV1L2Fkf2mW0nPKg_0.JPG: 480x640 (no detections), 301.1ms
Speed: 1.6ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjaHdbCV1L2Fkf2mW0nPKg_90.JPG: 480x640 (no detections), 298.2ms
Speed: 1.3ms preprocess, 298.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjaHdbCV1L2Fkf2mW0nPKg_180.JPG: 480x640 (no detections), 295.1ms
Speed: 1.2ms preprocess, 295.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjaHdbCV1L2Fkf2mW0nPKg_270.JPG: 480x640 (no detections), 295.9ms
Speed: 1.1ms preprocess, 295.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjafzO5b2n7ym0AL4mR7Kw_0.JPG: 480x640 (no detections), 299.4ms
Speed: 1.5ms preprocess, 299.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjafzO5b2n7ym0AL4mR7Kw_90.JPG: 480x640 (no detections), 297.6ms
Speed: 1.2ms preprocess, 297.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjafzO5b2n7ym0AL4mR7Kw_180.JPG: 480x640 (no detections), 298.3ms
Speed: 1.2ms preprocess, 298.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjafzO5b2n7ym0AL4mR7Kw_270.JPG: 480x640 (no detections), 292.5ms
Speed: 1.1ms preprocess, 292.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjdNa8Kd49Om8EqlZOS1OQ_0.JPG: 480x640 (no detections), 303.7ms
Speed: 1.2ms preprocess, 303.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjdNa8Kd49Om8EqlZOS1OQ_90.JPG: 480x640 (no detections), 298.0ms
Speed: 1.2ms preprocess, 298.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjdNa8Kd49Om8EqlZOS1OQ_180.JPG: 480x640 (no detections), 297.8ms
Speed: 1.3ms preprocess, 297.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjdNa8Kd49Om8EqlZOS1OQ_270.JPG: 480x640 (no detections), 301.1ms
Speed: 1.1ms preprocess, 301.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjdpaL9zh5_XgDTPrzkXdQ_0.JPG: 480x640 (no detections), 300.9ms
Speed: 1.1ms preprocess, 300.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjdpaL9zh5_XgDTPrzkXdQ_90.JPG: 480x640 (no detections), 301.2ms
Speed: 1.6ms preprocess, 301.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjdpaL9zh5_XgDTPrzkXdQ_180.JPG: 480x640 (no detections), 295.9ms
Speed: 1.2ms preprocess, 295.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjdpaL9zh5_XgDTPrzkXdQ_270.JPG: 480x640 (no detections), 295.9ms
Speed: 1.2ms preprocess, 295.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjeEN-xxcsmmv3tB2iWPTQ_0.JPG: 480x640 (no detections), 296.7ms
Speed: 1.2ms preprocess, 296.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjeEN-xxcsmmv3tB2iWPTQ_90.JPG: 480x640 (no detections), 296.1ms

Speed: 1.0ms preprocess, 296.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjeEN-xxcsmmv3tB2iWPTQ_180.JPG: 480x640 (no detections), 293.8ms
Speed: 1.4ms preprocess, 293.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjeEN-xxcsmmv3tB2iWPTQ_270.JPG: 480x640 (no detections), 298.9ms
Speed: 1.2ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjfYaBNJ1kkP_Iw0MYaCGA_0.JPG: 480x640 (no detections), 303.0ms
Speed: 1.0ms preprocess, 303.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjfYaBNJ1kkP_Iw0MYaCGA_90.JPG: 480x640 (no detections), 301.3ms
Speed: 1.1ms preprocess, 301.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjfYaBNJ1kkP_Iw0MYaCGA_180.JPG: 480x640 (no detections), 297.0ms
Speed: 1.1ms preprocess, 297.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjfYaBNJ1kkP_Iw0MYaCGA_270.JPG: 480x640 (no detections), 295.6ms
Speed: 1.1ms preprocess, 295.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjhPjEJ89tX5hrDhor-zcA_0.JPG: 480x640 (no detections), 293.6ms
Speed: 1.9ms preprocess, 293.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjhPjEJ89tX5hrDhor-zcA_90.JPG: 480x640 (no detections), 294.6ms
Speed: 1.2ms preprocess, 294.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjhPjEJ89tX5hrDhor-zcA_180.JPG: 480x640 (no detections), 297.4ms
Speed: 1.2ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjhPjEJ89tX5hrDhor-zcA_270.JPG: 480x640 (no detections), 300.1ms
Speed: 1.3ms preprocess, 300.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjholGq_XbbwWvwKiZRd4A_0.JPG: 480x640 (no detections), 292.3ms
Speed: 1.2ms preprocess, 292.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjholGq_XbbwWvwKiZRd4A_90.JPG: 480x640 (no detections), 296.1ms
Speed: 1.1ms preprocess, 296.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjholGq_XbbwWvwKiZRd4A_180.JPG: 480x640 (no detections), 299.0ms
Speed: 1.1ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjholGq_XbbwWvwKiZRd4A_270.JPG: 480x640 (no detections), 299.0ms
Speed: 1.0ms preprocess, 299.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xji0rK0zWhb7RDeBeI1_zA_0.JPG: 480x640 (no detections), 293.8ms
Speed: 1.0ms preprocess, 293.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xji0rK0zWhb7RDeBeI1_zA_90.JPG: 480x640 (no detections), 293.2ms
Speed: 1.1ms preprocess, 293.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xji0rK0zWhb7RDeBeI1_zA_180.JPG: 480x640 (no detections), 296.5ms
Speed: 1.2ms preprocess, 296.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xji0rK0zWhb7RDeBeI1_zA_270.JPG: 480x640 (no detections), 296.1ms
Speed: 1.5ms preprocess, 296.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjjmBWYTbFrTGElF41hCvw_0.JPG: 480x640 (no detections), 293.5ms
Speed: 1.2ms preprocess, 293.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjjmBWYTbFrTGElF41hCvw_90.JPG: 480x640 (no detections), 292.7ms
Speed: 2.1ms preprocess, 292.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjjmBWYTbFrTGElF41hCvw_180.JPG: 480x640 (no detections), 299.1ms
Speed: 1.2ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjjmBWYTbFrTGElF41hCvw_270.JPG: 480x640 (no detections), 297.3ms
Speed: 1.2ms preprocess, 297.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjlRE5ZPIlwkxel_SLhW8Q_0.JPG: 480x640 (no detections), 304.1ms
Speed: 1.2ms preprocess, 304.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjlRE5ZPIlwkxel_SLhW8Q_90.JPG: 480x640 (no detections), 298.8ms
Speed: 1.4ms preprocess, 298.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjlRE5ZPIlwkxel_SLhW8Q_180.JPG: 480x640 (no detections), 295.4ms
Speed: 1.3ms preprocess, 295.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjlRE5ZPIlwkxel_SLhW8Q_270.JPG: 480x640 (no detections), 297.6ms
Speed: 1.3ms preprocess, 297.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjoIrOqA-pGWF5n4k0V0pA_0.JPG: 480x640 (no detections), 302.3ms
Speed: 1.1ms preprocess, 302.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjoIrOqA-pGWF5n4k0V0pA_90.JPG: 480x640 (no detections), 300.6ms
Speed: 1.3ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjoIrOqA-pGWF5n4k0V0pA_180.JPG: 480x640 (no detections), 299.1ms
Speed: 1.3ms preprocess, 299.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjoIrOqA-pGWF5n4k0V0pA_270.JPG: 480x640 (no detections), 300.5ms
Speed: 1.2ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjsoo-9_wJFwWF1SeGNivQ_0.JPG: 480x640 (no detections), 297.5ms
Speed: 1.2ms preprocess, 297.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjsoo-9_wJFwWF1SeGNivQ_90.JPG: 480x640 (no detections), 300.9ms
Speed: 1.2ms preprocess, 300.9ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjsoo-9_wJFwWF1SeGNivQ_180.JPG: 480x640 (no detections), 299.0ms
Speed: 1.3ms preprocess, 299.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjsoo-9_wJFwWF1SeGNivQ_270.JPG: 480x640 (no detections), 295.7ms
Speed: 1.2ms preprocess, 295.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjuNOA9OK_--6V-o3TZ8QA_0.JPG: 480x640 (no detections), 301.6ms
Speed: 1.2ms preprocess, 301.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjuNOA9OK_--6V-o3TZ8QA_90.JPG: 480x640 (no detections), 301.2ms
Speed: 1.2ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjuNOA9OK_--6V-o3TZ8QA_180.JPG: 480x640 (no detections), 292.3ms
Speed: 1.1ms preprocess, 292.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjuNOA9OK_--6V-o3TZ8QA_270.JPG: 480x640 (no detections), 297.5ms
Speed: 1.2ms preprocess, 297.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjwENl4-kOSM09VhpW-teg_0.JPG: 480x640 (no detections), 295.7ms
Speed: 1.3ms preprocess, 295.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjwENl4-kOSM09VhpW-teg_90.JPG: 480x640 (no detections), 298.6ms
Speed: 1.6ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjwENl4-kOSM09VhpW-teg_180.JPG: 480x640 (no detections), 294.5ms
Speed: 1.5ms preprocess, 294.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjwENl4-kOSM09VhpW-teg_270.JPG: 480x640 (no detections), 299.8ms
Speed: 1.4ms preprocess, 299.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjx5EtKhFcuKccf7swtEZg_0.JPG: 480x640 (no detections), 304.5ms
Speed: 1.9ms preprocess, 304.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjx5EtKhFcuKccf7swtEZg_90.JPG: 480x640 (no detections), 297.0ms
Speed: 1.1ms preprocess, 297.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjx5EtKhFcuKccf7swtEZg_180.JPG: 480x640 (no detections), 300.6ms
Speed: 1.2ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjx5EtKhFcuKccf7swtEZg_270.JPG: 480x640 (no detections), 296.6ms
Speed: 1.1ms preprocess, 296.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjzG7kAVK5_Lo4FVKz8efg_0.JPG: 480x640 (no detections), 301.0ms
Speed: 1.1ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjzG7kAVK5_Lo4FVKz8efg_90.JPG: 480x640 (no detections), 295.4ms
Speed: 1.2ms preprocess, 295.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjzG7kAVK5_Lo4FVKz8efg_180.JPG: 480x640 (no detections), 304.3ms
Speed: 1.2ms preprocess, 304.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjzG7kAVK5_Lo4FVKz8efg_270.JPG: 480x640 1 Waste, 299.4ms
Speed: 1.3ms preprocess, 299.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjzekwJXb-JKdy1CmSs_-g_0.JPG: 480x640 1 Waste, 297.0ms
Speed: 1.5ms preprocess, 297.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjzekwJXb-JKdy1CmSs_-g_90.JPG: 480x640 (no detections), 304.9ms
Speed: 1.2ms preprocess, 304.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjzekwJXb-JKdy1CmSs_-g_180.JPG: 480x640 (no detections), 298.1ms
Speed: 1.3ms preprocess, 298.1ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjzekwJXb-JKdy1CmSs_-g_270.JPG: 480x640 (no detections), 297.6ms
Speed: 1.7ms preprocess, 297.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjzs3bPHk8_UIWGG9QmQ4A_0.JPG: 480x640 (no detections), 298.1ms
Speed: 1.3ms preprocess, 298.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjzs3bPHk8_UIWGG9QmQ4A_90.JPG: 480x640 (no detections), 300.0ms
Speed: 1.0ms preprocess, 300.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjzs3bPHk8_UIWGG9QmQ4A_180.JPG: 480x640 (no detections), 299.8ms
Speed: 1.1ms preprocess, 299.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/j/xjzs3bPHk8_UIWGG9QmQ4A_270.JPG: 480x640 (no detections), 297.2ms
Speed: 1.3ms preprocess, 297.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xk61AByCtB6ccNWBOttviw_0.JPG: 480x640 (no detections), 294.5ms
Speed: 1.6ms preprocess, 294.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xk61AByCtB6ccNWBOttviw_90.JPG: 480x640 (no detections), 298.8ms
Speed: 1.1ms preprocess, 298.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xk61AByCtB6ccNWBOttviw_180.JPG: 480x640 (no detections), 301.5ms
Speed: 1.2ms preprocess, 301.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xk61AByCtB6ccNWBOttviw_270.JPG: 480x640 (no detections), 295.0ms
Speed: 1.2ms preprocess, 295.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkC2Gs2wt114xya3SkTS1w_0.JPG: 480x640 (no detections), 303.9ms
Speed: 1.3ms preprocess, 303.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkC2Gs2wt114xya3SkTS1w_90.JPG: 480x640 (no detections), 297.9ms
Speed: 1.2ms preprocess, 297.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkC2Gs2wt114xya3SkTS1w_180.JPG: 480x640 (no detections), 300.6ms
Speed: 1.3ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkC2Gs2wt114xya3SkTS1w_270.JPG: 480x640 (no detections), 299.8ms
Speed: 1.1ms preprocess, 299.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkGjEGgendRHeHBBWApDPA_0.JPG: 480x640 (no detections), 299.9ms

Speed: 1.1ms preprocess, 299.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkGjEGgendRHeHBBWApDPA_90.JPG: 480x640 (no detections), 295.6ms
Speed: 1.1ms preprocess, 295.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkGjEGgendRHeHBBWApDPA_180.JPG: 480x640 (no detections), 293.4ms
Speed: 1.4ms preprocess, 293.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkGjEGgendRHeHBBWApDPA_270.JPG: 480x640 (no detections), 295.4ms
Speed: 1.3ms preprocess, 295.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkJiw_eQFf3N_TlpJ9stNQ_0.JPG: 480x640 (no detections), 298.7ms
Speed: 1.2ms preprocess, 298.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkJiw_eQFf3N_TlpJ9stNQ_90.JPG: 480x640 (no detections), 296.5ms
Speed: 1.0ms preprocess, 296.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkJiw_eQFf3N_TlpJ9stNQ_180.JPG: 480x640 (no detections), 292.5ms
Speed: 1.1ms preprocess, 292.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkJiw_eQFf3N_TlpJ9stNQ_270.JPG: 480x640 (no detections), 297.3ms
Speed: 1.2ms preprocess, 297.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkL-IvviLQmnu2c6ngAcTQ_0.JPG: 480x640 (no detections), 298.1ms
Speed: 1.3ms preprocess, 298.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkL-IvviLQmnu2c6ngAcTQ_90.JPG: 480x640 (no detections), 300.8ms
Speed: 1.4ms preprocess, 300.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkL-IvviLQmnu2c6ngAcTQ_180.JPG: 480x640 (no detections), 301.0ms
Speed: 1.2ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkL-IvviLQmnu2c6ngAcTQ_270.JPG: 480x640 1 Waste, 296.1ms
Speed: 1.1ms preprocess, 296.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkLMeupNWL3tmeqBqWRI4A_0.JPG: 480x640 (no detections), 298.8ms
Speed: 1.2ms preprocess, 298.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkLMeupNWL3tmeqBqWRI4A_90.JPG: 480x640 (no detections), 301.4ms
Speed: 1.2ms preprocess, 301.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkLMeupNWL3tmeqBqWRI4A_180.JPG: 480x640 (no detections), 297.4ms
Speed: 1.2ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkLMeupNWL3tmeqBqWRI4A_270.JPG: 480x640 (no detections), 294.6ms
Speed: 1.3ms preprocess, 294.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkM2p9LbyGIOTdnr5njiCA_0.JPG: 480x640 (no detections), 300.1ms
Speed: 1.4ms preprocess, 300.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkM2p9LbyGIOTdnr5njiCA_90.JPG: 480x640 (no detections), 300.5ms
Speed: 1.2ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkM2p9LbyGIOTdnr5njiCA_180.JPG: 480x640 (no detections), 297.4ms
Speed: 1.4ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkM2p9LbyGIOTdnr5njiCA_270.JPG: 480x640 1 Waste, 300.5ms
Speed: 1.2ms preprocess, 300.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkO5dRKN5J8n4UEEYiyKKw_0.JPG: 480x640 (no detections), 295.4ms
Speed: 1.7ms preprocess, 295.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkO5dRKN5J8n4UEEYiyKKw_90.JPG: 480x640 (no detections), 296.8ms
Speed: 1.1ms preprocess, 296.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkO5dRKN5J8n4UEEYiyKKw_180.JPG: 480x640 (no detections), 305.6ms
Speed: 1.4ms preprocess, 305.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkO5dRKN5J8n4UEEYiyKKw_270.JPG: 480x640 (no detections), 302.8ms
Speed: 1.2ms preprocess, 302.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xk_Qm1NBYti4hyCtikG19Q_0.JPG: 480x640 (no detections), 295.7ms
Speed: 1.2ms preprocess, 295.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xk_Qm1NBYti4hyCtikG19Q_90.JPG: 480x640 (no detections), 300.7ms
Speed: 1.1ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xk_Qm1NBYti4hyCtikG19Q_180.JPG: 480x640 (no detections), 302.0ms
Speed: 1.3ms preprocess, 302.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xk_Qm1NBYti4hyCtikG19Q_270.JPG: 480x640 (no detections), 297.2ms
Speed: 1.1ms preprocess, 297.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xk_r2yCDRYwG8-JsGY1DAQ_0.JPG: 480x640 (no detections), 295.2ms
Speed: 1.4ms preprocess, 295.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xk_r2yCDRYwG8-JsGY1DAQ_90.JPG: 480x640 (no detections), 298.6ms
Speed: 2.1ms preprocess, 298.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xk_r2yCDRYwG8-JsGY1DAQ_180.JPG: 480x640 (no detections), 297.6ms
Speed: 1.1ms preprocess, 297.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xk_r2yCDRYwG8-JsGY1DAQ_270.JPG: 480x640 (no detections), 297.4ms
Speed: 1.2ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkb6rVWAePAJ00rPqeDu7g_0.JPG: 480x640 (no detections), 295.9ms
Speed: 1.2ms preprocess, 295.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkb6rVWAePAJ00rPqeDu7g_90.JPG: 480x640 (no detections), 296.9ms
Speed: 1.3ms preprocess, 296.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkb6rVWAePAJ00rPqeDu7g_180.JPG: 480x640 (no detections), 291.8ms
Speed: 1.1ms preprocess, 291.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkb6rVWAePAJ00rPqeDu7g_270.JPG: 480x640 (no detections), 299.8ms
Speed: 1.2ms preprocess, 299.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkc9lpvo0a7sBZY6OZnMzA_0.JPG: 480x640 (no detections), 296.2ms
Speed: 1.1ms preprocess, 296.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkc9lpvo0a7sBZY6OZnMzA_90.JPG: 480x640 (no detections), 297.9ms
Speed: 1.1ms preprocess, 297.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkc9lpvo0a7sBZY6OZnMzA_180.JPG: 480x640 (no detections), 290.4ms
Speed: 1.8ms preprocess, 290.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkc9lpvo0a7sBZY6OZnMzA_270.JPG: 480x640 (no detections), 299.4ms
Speed: 1.4ms preprocess, 299.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkd6fvHwXSbAxCb6Q-ezSQ_0.JPG: 480x640 (no detections), 301.3ms
Speed: 1.3ms preprocess, 301.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkd6fvHwXSbAxCb6Q-ezSQ_90.JPG: 480x640 (no detections), 297.7ms
Speed: 1.6ms preprocess, 297.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkd6fvHwXSbAxCb6Q-ezSQ_180.JPG: 480x640 (no detections), 298.8ms
Speed: 1.4ms preprocess, 298.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkd6fvHwXSbAxCb6Q-ezSQ_270.JPG: 480x640 (no detections), 297.1ms
Speed: 1.1ms preprocess, 297.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkhH5O8dM7p74KuS9nilKg_0.JPG: 480x640 (no detections), 296.6ms
Speed: 1.2ms preprocess, 296.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkhH5O8dM7p74KuS9nilKg_90.JPG: 480x640 (no detections), 296.8ms
Speed: 1.1ms preprocess, 296.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkhH5O8dM7p74KuS9nilKg_180.JPG: 480x640 (no detections), 302.4ms
Speed: 1.0ms preprocess, 302.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkhH5O8dM7p74KuS9nilKg_270.JPG: 480x640 (no detections), 297.4ms
Speed: 1.3ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xko2MiV8yiNNwi53lF6_NA_0.JPG: 480x640 (no detections), 300.2ms
Speed: 1.3ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xko2MiV8yiNNwi53lF6_NA_90.JPG: 480x640 (no detections), 301.9ms
Speed: 1.2ms preprocess, 301.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xko2MiV8yiNNwi53lF6_NA_180.JPG: 480x640 (no detections), 299.3ms
Speed: 1.1ms preprocess, 299.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xko2MiV8yiNNwi53lF6_NA_270.JPG: 480x640 (no detections), 304.0ms
Speed: 1.3ms preprocess, 304.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xks3n848g5EizKoSa-8ayg_0.JPG: 480x640 (no detections), 294.1ms
Speed: 1.2ms preprocess, 294.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xks3n848g5EizKoSa-8ayg_90.JPG: 480x640 (no detections), 301.7ms
Speed: 1.1ms preprocess, 301.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xks3n848g5EizKoSa-8ayg_180.JPG: 480x640 (no detections), 297.8ms
Speed: 1.7ms preprocess, 297.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xks3n848g5EizKoSa-8ayg_270.JPG: 480x640 (no detections), 304.1ms
Speed: 1.2ms preprocess, 304.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xksoUOV_piv7JOabnrziCw_0.JPG: 480x640 (no detections), 304.5ms
Speed: 1.7ms preprocess, 304.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xksoUOV_piv7JOabnrziCw_90.JPG: 480x640 (no detections), 295.0ms
Speed: 1.7ms preprocess, 295.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xksoUOV_piv7JOabnrziCw_180.JPG: 480x640 (no detections), 298.4ms
Speed: 1.2ms preprocess, 298.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xksoUOV_piv7JOabnrziCw_270.JPG: 480x640 (no detections), 301.8ms
Speed: 1.2ms preprocess, 301.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xktm66177oMdGOOYMJAxpA_0.JPG: 480x640 (no detections), 299.1ms
Speed: 1.5ms preprocess, 299.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xktm66177oMdGOOYMJAxpA_90.JPG: 480x640 (no detections), 298.9ms
Speed: 1.2ms preprocess, 298.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xktm66177oMdGOOYMJAxpA_180.JPG: 480x640 (no detections), 305.4ms
Speed: 1.3ms preprocess, 305.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xktm66177oMdGOOYMJAxpA_270.JPG: 480x640 (no detections), 295.2ms
Speed: 1.3ms preprocess, 295.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xktquzzcjG2TmmO59ad_9w_0.JPG: 480x640 (no detections), 296.8ms
Speed: 1.1ms preprocess, 296.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xktquzzcjG2TmmO59ad_9w_90.JPG: 480x640 (no detections), 294.3ms
Speed: 1.2ms preprocess, 294.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xktquzzcjG2TmmO59ad_9w_180.JPG: 480x640 (no detections), 296.2ms
Speed: 1.3ms preprocess, 296.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xktquzzcjG2TmmO59ad_9w_270.JPG: 480x640 (no detections), 300.2ms

Speed: 1.1ms preprocess, 300.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkutQcCQqI_NcIYKoCTBaQ_0.JPG: 480x640 (no detections), 296.0ms
Speed: 1.2ms preprocess, 296.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkutQcCQqI_NcIYKoCTBaQ_90.JPG: 480x640 (no detections), 297.0ms
Speed: 1.0ms preprocess, 297.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkutQcCQqI_NcIYKoCTBaQ_180.JPG: 480x640 (no detections), 299.1ms
Speed: 1.1ms preprocess, 299.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkutQcCQqI_NcIYKoCTBaQ_270.JPG: 480x640 (no detections), 297.6ms
Speed: 1.2ms preprocess, 297.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkwxJYAvGfYoKQ2XVKQAog_0.JPG: 480x640 (no detections), 297.4ms
Speed: 1.1ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkwxJYAvGfYoKQ2XVKQAog_90.JPG: 480x640 (no detections), 300.2ms
Speed: 1.1ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkwxJYAvGfYoKQ2XVKQAog_180.JPG: 480x640 (no detections), 298.1ms
Speed: 1.2ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkwxJYAvGfYoKQ2XVKQAog_270.JPG: 480x640 (no detections), 302.5ms
Speed: 1.3ms preprocess, 302.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkwyeXMjg8k_ZTqURmRsjQ_0.JPG: 480x640 (no detections), 295.6ms
Speed: 1.1ms preprocess, 295.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkwyeXMjg8k_ZTqURmRsjQ_90.JPG: 480x640 (no detections), 297.5ms
Speed: 1.1ms preprocess, 297.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkwyeXMjg8k_ZTqURmRsjQ_180.JPG: 480x640 (no detections), 296.1ms
Speed: 1.4ms preprocess, 296.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkwyeXMjg8k_ZTqURmRsjQ_270.JPG: 480x640 (no detections), 296.8ms
Speed: 1.3ms preprocess, 296.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkxSogcEymC5B6JInu5ohA_0.JPG: 480x640 (no detections), 302.2ms
Speed: 2.0ms preprocess, 302.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkxSogcEymC5B6JInu5ohA_90.JPG: 480x640 (no detections), 298.0ms
Speed: 1.2ms preprocess, 298.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkxSogcEymC5B6JInu5ohA_180.JPG: 480x640 (no detections), 295.0ms
Speed: 1.1ms preprocess, 295.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkxSogcEymC5B6JInu5ohA_270.JPG: 480x640 (no detections), 297.2ms
Speed: 1.0ms preprocess, 297.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkyv30HnqXa_jh6BiVLm-g_0.JPG: 480x640 (no detections), 302.1ms
Speed: 1.4ms preprocess, 302.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkyv30HnqXa_jh6BiVLm-g_90.JPG: 480x640 (no detections), 301.3ms
Speed: 1.3ms preprocess, 301.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkyv30HnqXa_jh6BiVLm-g_180.JPG: 480x640 (no detections), 296.6ms
Speed: 1.2ms preprocess, 296.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkyv30HnqXa_jh6BiVLm-g_270.JPG: 480x640 (no detections), 297.7ms
Speed: 1.2ms preprocess, 297.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkzmRMzc1uhzPrfHqWr-DA_0.JPG: 480x640 (no detections), 301.5ms
Speed: 1.3ms preprocess, 301.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkzmRMzc1uhzPrfHqWr-DA_90.JPG: 480x640 (no detections), 296.4ms
Speed: 1.0ms preprocess, 296.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkzmRMzc1uhzPrfHqWr-DA_180.JPG: 480x640 (no detections), 300.6ms
Speed: 1.2ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/K/xkzmRMzc1uhzPrfHqWr-DA_270.JPG: 480x640 (no detections), 298.4ms
Speed: 1.0ms preprocess, 298.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xl-bKGliVcSlloa4Z07EMg_0.JPG: 480x640 (no detections), 303.1ms
Speed: 1.2ms preprocess, 303.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xl-bKGliVcSlloa4Z07EMg_90.JPG: 480x640 (no detections), 296.2ms
Speed: 1.2ms preprocess, 296.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xl-bKGliVcSlloa4Z07EMg_180.JPG: 480x640 (no detections), 302.9ms
Speed: 1.4ms preprocess, 302.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xl-bKGliVcSlloa4Z07EMg_270.JPG: 480x640 (no detections), 294.2ms
Speed: 1.2ms preprocess, 294.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xl4xuykHE0v_nVLUgYLm_w_0.JPG: 480x640 (no detections), 299.7ms
Speed: 1.1ms preprocess, 299.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xl4xuykHE0v_nVLUgYLm_w_90.JPG: 480x640 (no detections), 303.1ms
Speed: 1.2ms preprocess, 303.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xl4xuykHE0v_nVLUgYLm_w_180.JPG: 480x640 (no detections), 299.4ms
Speed: 1.3ms preprocess, 299.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xl4xuykHE0v_nVLUgYLm_w_270.JPG: 480x640 (no detections), 306.6ms
Speed: 1.2ms preprocess, 306.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xl6nXxUW3M_eecz3ErtirA_0.JPG: 480x640 (no detections), 296.3ms
Speed: 1.2ms preprocess, 296.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xl6nXxUW3M_eecz3ErtirA_90.JPG: 480x640 (no detections), 297.9ms
Speed: 1.1ms preprocess, 297.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xl6nXxUW3M_eecz3ErtirA_180.JPG: 480x640 (no detections), 299.0ms
Speed: 1.3ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xl6nXxUW3M_eecz3ErtirA_270.JPG: 480x640 (no detections), 295.2ms
Speed: 1.2ms preprocess, 295.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xl71fw5BR4cXaODDppdTBA_0.JPG: 480x640 (no detections), 297.2ms
Speed: 1.1ms preprocess, 297.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xl71fw5BR4cXaODDppdTBA_90.JPG: 480x640 (no detections), 300.1ms
Speed: 1.1ms preprocess, 300.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xl71fw5BR4cXaODDppdTBA_180.JPG: 480x640 (no detections), 294.2ms
Speed: 1.6ms preprocess, 294.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xl71fw5BR4cXaODDppdTBA_270.JPG: 480x640 (no detections), 297.1ms
Speed: 1.6ms preprocess, 297.1ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xl7CJVeUos2zgn2K7O9CpA_0.JPG: 480x640 (no detections), 302.9ms
Speed: 1.2ms preprocess, 302.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xl7CJVeUos2zgn2K7O9CpA_90.JPG: 480x640 (no detections), 296.8ms
Speed: 1.4ms preprocess, 296.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xl7CJVeUos2zgn2K7O9CpA_180.JPG: 480x640 (no detections), 296.1ms
Speed: 1.2ms preprocess, 296.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xl7CJVeUos2zgn2K7O9CpA_270.JPG: 480x640 (no detections), 297.9ms
Speed: 1.2ms preprocess, 297.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlB6eNyy0Xbba7KWr9FCyw_0.JPG: 480x640 (no detections), 295.7ms
Speed: 1.1ms preprocess, 295.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlB6eNyy0Xbba7KWr9FCyw_90.JPG: 480x640 (no detections), 296.8ms
Speed: 1.1ms preprocess, 296.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlB6eNyy0Xbba7KWr9FCyw_180.JPG: 480x640 (no detections), 297.5ms
Speed: 1.1ms preprocess, 297.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlB6eNyy0Xbba7KWr9FCyw_270.JPG: 480x640 (no detections), 303.6ms
Speed: 1.1ms preprocess, 303.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlENx12n9x-D8kl0pEo4sQ_0.JPG: 480x640 (no detections), 295.0ms
Speed: 1.0ms preprocess, 295.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlENx12n9x-D8kl0pEo4sQ_90.JPG: 480x640 (no detections), 299.7ms
Speed: 1.0ms preprocess, 299.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlENx12n9x-D8kl0pEo4sQ_180.JPG: 480x640 (no detections), 298.4ms
Speed: 1.5ms preprocess, 298.4ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlENx12n9x-D8kl0pEo4sQ_270.JPG: 480x640 (no detections), 296.6ms
Speed: 1.2ms preprocess, 296.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlEm_aSpLaFPb_KbXS7HMw_0.JPG: 480x640 (no detections), 299.4ms
Speed: 1.1ms preprocess, 299.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlEm_aSpLaFPb_KbXS7HMw_90.JPG: 480x640 (no detections), 297.9ms
Speed: 1.7ms preprocess, 297.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlEm_aSpLaFPb_KbXS7HMw_180.JPG: 480x640 (no detections), 296.6ms
Speed: 1.2ms preprocess, 296.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlEm_aSpLaFPb_KbXS7HMw_270.JPG: 480x640 (no detections), 300.3ms
Speed: 1.0ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlFzwcseXOhY-EYMgmtqkA_0.JPG: 480x640 (no detections), 291.4ms
Speed: 1.1ms preprocess, 291.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlFzwcseXOhY-EYMgmtqkA_90.JPG: 480x640 (no detections), 300.3ms
Speed: 1.2ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlFzwcseXOhY-EYMgmtqkA_180.JPG: 480x640 (no detections), 295.2ms
Speed: 1.1ms preprocess, 295.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlFzwcseXOhY-EYMgmtqkA_270.JPG: 480x640 (no detections), 300.0ms
Speed: 1.1ms preprocess, 300.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlHSk2KedNK4KtYjrMkEpg_0.JPG: 480x640 (no detections), 304.5ms
Speed: 1.2ms preprocess, 304.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlHSk2KedNK4KtYjrMkEpg_90.JPG: 480x640 (no detections), 297.8ms
Speed: 1.1ms preprocess, 297.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlHSk2KedNK4KtYjrMkEpg_180.JPG: 480x640 (no detections), 296.2ms
Speed: 1.3ms preprocess, 296.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlHSk2KedNK4KtYjrMkEpg_270.JPG: 480x640 (no detections), 299.2ms
Speed: 1.1ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlNA3Nvh65KoCgBImjPyFw_0.JPG: 480x640 (no detections), 298.0ms
Speed: 1.2ms preprocess, 298.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlNA3Nvh65KoCgBImjPyFw_90.JPG: 480x640 (no detections), 300.1ms
Speed: 1.2ms preprocess, 300.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlNA3Nvh65KoCgBImjPyFw_180.JPG: 480x640 1 Waste, 300.6ms

Speed: 1.8ms preprocess, 300.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlNA3Nvh65KoCgBImjPyFw_270.JPG: 480x640 (no detections), 299.2ms
Speed: 1.2ms preprocess, 299.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlOtA42IeyF1oOHQoOOzjw_0.JPG: 480x640 (no detections), 299.1ms
Speed: 1.3ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlOtA42IeyF1oOHQoOOzjw_90.JPG: 480x640 (no detections), 295.6ms
Speed: 1.4ms preprocess, 295.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlOtA42IeyF1oOHQoOOzjw_180.JPG: 480x640 (no detections), 298.7ms
Speed: 1.3ms preprocess, 298.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlOtA42IeyF1oOHQoOOzjw_270.JPG: 480x640 (no detections), 300.6ms
Speed: 1.1ms preprocess, 300.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlPN8viHw8yHOeCfxBMFAA_0.JPG: 480x640 (no detections), 300.1ms
Speed: 1.3ms preprocess, 300.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlPN8viHw8yHOeCfxBMFAA_90.JPG: 480x640 (no detections), 301.4ms
Speed: 1.1ms preprocess, 301.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlPN8viHw8yHOeCfxBMFAA_180.JPG: 480x640 (no detections), 296.7ms
Speed: 1.1ms preprocess, 296.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlPN8viHw8yHOeCfxBMFAA_270.JPG: 480x640 (no detections), 296.3ms
Speed: 1.1ms preprocess, 296.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlPv3ZZeKucrNl6-hXFVPg_0.JPG: 480x640 (no detections), 298.6ms
Speed: 1.9ms preprocess, 298.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlPv3ZZeKucrNl6-hXFVPg_90.JPG: 480x640 (no detections), 300.8ms
Speed: 1.1ms preprocess, 300.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlPv3ZZeKucrNl6-hXFVPg_180.JPG: 480x640 (no detections), 299.2ms
Speed: 1.1ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlPv3ZZeKucrNl6-hXFVPg_270.JPG: 480x640 (no detections), 295.8ms
Speed: 1.9ms preprocess, 295.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlSQ2yyBYkVW0ykApHMNHQ_0.JPG: 480x640 (no detections), 300.3ms
Speed: 1.2ms preprocess, 300.3ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlSQ2yyBYkVW0ykApHMNHQ_90.JPG: 480x640 (no detections), 301.7ms
Speed: 1.0ms preprocess, 301.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlSQ2yyBYkVW0ykApHMNHQ_180.JPG: 480x640 (no detections), 296.9ms
Speed: 1.1ms preprocess, 296.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlSQ2yyBYkVW0ykApHMNHQ_270.JPG: 480x640 (no detections), 300.3ms
Speed: 1.9ms preprocess, 300.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlV0y357irHFwbcVgWVAiA_0.JPG: 480x640 (no detections), 303.6ms
Speed: 1.3ms preprocess, 303.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlV0y357irHFwbcVgWVAiA_90.JPG: 480x640 1 Waste, 296.7ms
Speed: 1.0ms preprocess, 296.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlV0y357irHFwbcVgWVAiA_180.JPG: 480x640 (no detections), 300.5ms
Speed: 1.3ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlV0y357irHFwbcVgWVAiA_270.JPG: 480x640 (no detections), 303.8ms
Speed: 1.2ms preprocess, 303.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlW5gW31CUL4Lst8ocCf2A_0.JPG: 480x640 (no detections), 303.3ms
Speed: 1.2ms preprocess, 303.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlW5gW31CUL4Lst8ocCf2A_90.JPG: 480x640 (no detections), 297.0ms
Speed: 1.2ms preprocess, 297.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlW5gW31CUL4Lst8ocCf2A_180.JPG: 480x640 (no detections), 297.5ms
Speed: 1.3ms preprocess, 297.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlW5gW31CUL4Lst8ocCf2A_270.JPG: 480x640 (no detections), 300.5ms
Speed: 1.1ms preprocess, 300.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlX1Vlb-SMRxxhICRY_VZw_0.JPG: 480x640 (no detections), 304.1ms
Speed: 1.1ms preprocess, 304.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlX1Vlb-SMRxxhICRY_VZw_90.JPG: 480x640 (no detections), 298.3ms
Speed: 1.2ms preprocess, 298.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlX1Vlb-SMRxxhICRY_VZw_180.JPG: 480x640 (no detections), 297.9ms
Speed: 1.2ms preprocess, 297.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlX1Vlb-SMRxxhICRY_VZw_270.JPG: 480x640 (no detections), 296.2ms
Speed: 1.1ms preprocess, 296.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlXFQ_MqL8z7cwcm_xr7kw_0.JPG: 480x640 (no detections), 298.4ms
Speed: 1.5ms preprocess, 298.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlXFQ_MqL8z7cwcm_xr7kw_90.JPG: 480x640 (no detections), 296.4ms
Speed: 1.3ms preprocess, 296.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlXFQ_MqL8z7cwcm_xr7kw_180.JPG: 480x640 (no detections), 304.9ms
Speed: 1.2ms preprocess, 304.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlXFQ_MqL8z7cwcm_xr7kw_270.JPG: 480x640 (no detections), 299.1ms
Speed: 1.8ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlXSIpWRGFcXk774WwJxog_0.JPG: 480x640 (no detections), 304.3ms
Speed: 1.9ms preprocess, 304.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlXSIpWRGFcXk774WwJxog_90.JPG: 480x640 (no detections), 290.1ms
Speed: 1.1ms preprocess, 290.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlXSIpWRGFcXk774WwJxog_180.JPG: 480x640 (no detections), 306.6ms
Speed: 1.1ms preprocess, 306.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlXSIpWRGFcXk774WwJxog_270.JPG: 480x640 (no detections), 317.8ms
Speed: 1.3ms preprocess, 317.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlesgQap0-B76w4yTusuZQ_0.JPG: 480x640 (no detections), 321.7ms
Speed: 1.2ms preprocess, 321.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlesgQap0-B76w4yTusuZQ_90.JPG: 480x640 (no detections), 299.1ms
Speed: 1.1ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlesgQap0-B76w4yTusuZQ_180.JPG: 480x640 (no detections), 301.3ms
Speed: 1.1ms preprocess, 301.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlesgQap0-B76w4yTusuZQ_270.JPG: 480x640 (no detections), 304.2ms
Speed: 2.0ms preprocess, 304.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlgmi0aIbd_u6VHRu6eWGA_0.JPG: 480x640 (no detections), 299.8ms
Speed: 1.5ms preprocess, 299.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlgmi0aIbd_u6VHRu6eWGA_90.JPG: 480x640 (no detections), 301.6ms
Speed: 1.5ms preprocess, 301.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlgmi0aIbd_u6VHRu6eWGA_180.JPG: 480x640 (no detections), 295.8ms
Speed: 1.2ms preprocess, 295.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlgmi0aIbd_u6VHRu6eWGA_270.JPG: 480x640 (no detections), 304.0ms
Speed: 1.0ms preprocess, 304.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlkZpw8RPT6Q5mYKA2SQDQ_0.JPG: 480x640 (no detections), 315.4ms
Speed: 1.3ms preprocess, 315.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlkZpw8RPT6Q5mYKA2SQDQ_90.JPG: 480x640 (no detections), 308.4ms
Speed: 1.2ms preprocess, 308.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlkZpw8RPT6Q5mYKA2SQDQ_180.JPG: 480x640 (no detections), 302.5ms
Speed: 1.2ms preprocess, 302.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlkZpw8RPT6Q5mYKA2SQDQ_270.JPG: 480x640 (no detections), 302.3ms
Speed: 1.4ms preprocess, 302.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlk_QH5djrzXb48B1m7fBA_0.JPG: 480x640 (no detections), 299.8ms
Speed: 1.5ms preprocess, 299.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlk_QH5djrzXb48B1m7fBA_90.JPG: 480x640 (no detections), 302.2ms
Speed: 1.5ms preprocess, 302.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlk_QH5djrzXb48B1m7fBA_180.JPG: 480x640 (no detections), 300.6ms
Speed: 1.1ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlk_QH5djrzXb48B1m7fBA_270.JPG: 480x640 (no detections), 301.8ms
Speed: 1.2ms preprocess, 301.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlkmNMns9RsGIkpgu0-40g_0.JPG: 480x640 (no detections), 300.0ms
Speed: 1.5ms preprocess, 300.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlkmNMns9RsGIkpgu0-40g_90.JPG: 480x640 (no detections), 298.3ms
Speed: 1.2ms preprocess, 298.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlkmNMns9RsGIkpgu0-40g_180.JPG: 480x640 (no detections), 301.6ms
Speed: 1.3ms preprocess, 301.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlkmNMns9RsGIkpgu0-40g_270.JPG: 480x640 (no detections), 302.4ms
Speed: 1.2ms preprocess, 302.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xllftz19o6UUuSURrtbeFA_0.JPG: 480x640 (no detections), 300.2ms
Speed: 1.3ms preprocess, 300.2ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xllftz19o6UUuSURrtbeFA_90.JPG: 480x640 (no detections), 300.0ms
Speed: 1.5ms preprocess, 300.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xllftz19o6UUuSURrtbeFA_180.JPG: 480x640 (no detections), 305.8ms
Speed: 1.9ms preprocess, 305.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xllftz19o6UUuSURrtbeFA_270.JPG: 480x640 (no detections), 298.9ms
Speed: 1.2ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlm_WqzFxU3PUtXSdLlClA_0.JPG: 480x640 (no detections), 296.9ms
Speed: 1.1ms preprocess, 296.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlm_WqzFxU3PUtXSdLlClA_90.JPG: 480x640 (no detections), 303.9ms
Speed: 1.2ms preprocess, 303.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlm_WqzFxU3PUtXSdLlClA_180.JPG: 480x640 (no detections), 300.7ms
Speed: 1.1ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlm_WqzFxU3PUtXSdLlClA_270.JPG: 480x640 (no detections), 305.4ms
Speed: 1.5ms preprocess, 305.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlqnEyrzc96ylL0yF0VcXw_0.JPG: 480x640 (no detections), 314.5ms
Speed: 1.1ms preprocess, 314.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlqnEyrzc96ylL0yF0VcXw_90.JPG: 480x640 (no detections), 306.4ms

Speed: 1.2ms preprocess, 306.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlqnEyrzc96ylL0yF0VcXw_180.JPG: 480x640 (no detections), 302.1ms
Speed: 1.5ms preprocess, 302.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlqnEyrzc96ylL0yF0VcXw_270.JPG: 480x640 (no detections), 299.1ms
Speed: 1.2ms preprocess, 299.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlqwKf7Bt6D1le7iZRhkEw_0.JPG: 480x640 (no detections), 301.6ms
Speed: 1.3ms preprocess, 301.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlqwKf7Bt6D1le7iZRhkEw_90.JPG: 480x640 (no detections), 300.6ms
Speed: 1.1ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlqwKf7Bt6D1le7iZRhkEw_180.JPG: 480x640 (no detections), 302.6ms
Speed: 1.4ms preprocess, 302.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlqwKf7Bt6D1le7iZRhkEw_270.JPG: 480x640 (no detections), 300.8ms
Speed: 1.1ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xltL56tT9-PQe_cNLlX-Qw_0.JPG: 480x640 (no detections), 294.9ms
Speed: 1.3ms preprocess, 294.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xltL56tT9-PQe_cNLlX-Qw_90.JPG: 480x640 (no detections), 300.9ms
Speed: 1.4ms preprocess, 300.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xltL56tT9-PQe_cNLlX-Qw_180.JPG: 480x640 (no detections), 297.0ms
Speed: 1.1ms preprocess, 297.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xltL56tT9-PQe_cNLlX-Qw_270.JPG: 480x640 (no detections), 366.4ms
Speed: 10.4ms preprocess, 366.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlwArRgj21VQTaLiEXsX_A_0.JPG: 480x640 (no detections), 297.4ms
Speed: 1.3ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlwArRgj21VQTaLiEXsX_A_90.JPG: 480x640 (no detections), 294.6ms
Speed: 1.4ms preprocess, 294.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlwArRgj21VQTaLiEXsX_A_180.JPG: 480x640 (no detections), 300.1ms
Speed: 1.9ms preprocess, 300.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlwArRgj21VQTaLiEXsX_A_270.JPG: 480x640 (no detections), 294.0ms
Speed: 1.2ms preprocess, 294.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlx1bi4mOLjXSWWilZklpQ_0.JPG: 480x640 (no detections), 296.9ms
Speed: 1.2ms preprocess, 296.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlx1bi4mOLjXSWWilZklpQ_90.JPG: 480x640 (no detections), 299.8ms
Speed: 1.2ms preprocess, 299.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlx1bi4mOLjXSWWilZklpQ_180.JPG: 480x640 (no detections), 300.2ms
Speed: 1.1ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlx1bi4mOLjXSWWilZklpQ_270.JPG: 480x640 (no detections), 305.2ms
Speed: 1.0ms preprocess, 305.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlxTL5hvA19UH3paGwzyCQ_0.JPG: 480x640 (no detections), 300.3ms
Speed: 1.6ms preprocess, 300.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlxTL5hvA19UH3paGwzyCQ_90.JPG: 480x640 (no detections), 297.5ms
Speed: 1.1ms preprocess, 297.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlxTL5hvA19UH3paGwzyCQ_180.JPG: 480x640 (no detections), 292.6ms
Speed: 1.2ms preprocess, 292.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlxTL5hvA19UH3paGwzyCQ_270.JPG: 480x640 (no detections), 296.8ms
Speed: 1.4ms preprocess, 296.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlzKF8Su6N6EhKz_npkE0w_0.JPG: 480x640 1 Waste, 289.1ms
Speed: 1.2ms preprocess, 289.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlzKF8Su6N6EhKz_npkE0w_90.JPG: 480x640 (no detections), 287.9ms
Speed: 1.2ms preprocess, 287.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlzKF8Su6N6EhKz_npkE0w_180.JPG: 480x640 (no detections), 296.6ms
Speed: 1.3ms preprocess, 296.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/L/xlzKF8Su6N6EhKz_npkE0w_270.JPG: 480x640 (no detections), 299.3ms
Speed: 1.1ms preprocess, 299.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xm-o73YVVjf6NWnDa9ps9A_0.JPG: 480x640 (no detections), 292.6ms
Speed: 1.6ms preprocess, 292.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xm-o73YVVjf6NWnDa9ps9A_90.JPG: 480x640 (no detections), 301.9ms
Speed: 1.1ms preprocess, 301.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xm-o73YVVjf6NWnDa9ps9A_180.JPG: 480x640 (no detections), 296.7ms
Speed: 1.3ms preprocess, 296.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xm-o73YVVjf6NWnDa9ps9A_270.JPG: 480x640 (no detections), 301.4ms
Speed: 1.2ms preprocess, 301.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xm30-QWHhPhTlRb8pjXcsg_0.JPG: 480x640 (no detections), 302.5ms
Speed: 1.2ms preprocess, 302.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xm30-QWHhPhTlRb8pjXcsg_90.JPG: 480x640 (no detections), 300.3ms
Speed: 1.2ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xm30-QWHhPhTlRb8pjXcsg_180.JPG: 480x640 (no detections), 303.3ms
Speed: 1.7ms preprocess, 303.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xm30-QWHhPhTlRb8pjXcsg_270.JPG: 480x640 (no detections), 294.2ms
Speed: 1.1ms preprocess, 294.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xm3rXUw_QXWBIqvg8qcO_A_0.JPG: 480x640 (no detections), 294.1ms
Speed: 1.1ms preprocess, 294.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xm3rXUw_QXWBIqvg8qcO_A_90.JPG: 480x640 (no detections), 297.7ms
Speed: 1.3ms preprocess, 297.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xm3rXUw_QXWBIqvg8qcO_A_180.JPG: 480x640 (no detections), 303.1ms
Speed: 1.3ms preprocess, 303.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xm3rXUw_QXWBIqvg8qcO_A_270.JPG: 480x640 (no detections), 298.3ms
Speed: 1.2ms preprocess, 298.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xm43DKWW2fRWO5A8i_-5Ew_0.JPG: 480x640 (no detections), 304.2ms
Speed: 1.2ms preprocess, 304.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xm43DKWW2fRWO5A8i_-5Ew_90.JPG: 480x640 (no detections), 299.6ms
Speed: 1.4ms preprocess, 299.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xm43DKWW2fRWO5A8i_-5Ew_180.JPG: 480x640 (no detections), 298.4ms
Speed: 1.1ms preprocess, 298.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xm43DKWW2fRWO5A8i_-5Ew_270.JPG: 480x640 (no detections), 292.9ms
Speed: 1.1ms preprocess, 292.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xm5UxgogZNaKwmZYOtRIoQ_0.JPG: 480x640 (no detections), 298.5ms
Speed: 1.1ms preprocess, 298.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xm5UxgogZNaKwmZYOtRIoQ_90.JPG: 480x640 (no detections), 302.7ms
Speed: 1.3ms preprocess, 302.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xm5UxgogZNaKwmZYOtRIoQ_180.JPG: 480x640 (no detections), 299.8ms
Speed: 1.1ms preprocess, 299.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xm5UxgogZNaKwmZYOtRIoQ_270.JPG: 480x640 (no detections), 295.5ms
Speed: 1.1ms preprocess, 295.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xm5w04a0uTIy5BPPaEV7Cg_0.JPG: 480x640 (no detections), 294.0ms
Speed: 1.1ms preprocess, 294.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xm5w04a0uTIy5BPPaEV7Cg_90.JPG: 480x640 (no detections), 303.9ms
Speed: 1.0ms preprocess, 303.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xm5w04a0uTIy5BPPaEV7Cg_180.JPG: 480x640 (no detections), 299.4ms
Speed: 1.3ms preprocess, 299.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xm5w04a0uTIy5BPPaEV7Cg_270.JPG: 480x640 (no detections), 295.9ms
Speed: 1.2ms preprocess, 295.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmCAbTaq-Y1-4CA-zNa31Q_0.JPG: 480x640 (no detections), 297.8ms
Speed: 1.7ms preprocess, 297.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmCAbTaq-Y1-4CA-zNa31Q_90.JPG: 480x640 (no detections), 297.3ms
Speed: 1.3ms preprocess, 297.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmCAbTaq-Y1-4CA-zNa31Q_180.JPG: 480x640 (no detections), 298.2ms
Speed: 1.2ms preprocess, 298.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmCAbTaq-Y1-4CA-zNa31Q_270.JPG: 480x640 (no detections), 295.6ms
Speed: 1.1ms preprocess, 295.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmGADnKBz3ZvQEIf2SRoZg_0.JPG: 480x640 (no detections), 297.1ms
Speed: 1.1ms preprocess, 297.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmGADnKBz3ZvQEIf2SRoZg_90.JPG: 480x640 (no detections), 292.8ms
Speed: 1.1ms preprocess, 292.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmGADnKBz3ZvQEIf2SRoZg_180.JPG: 480x640 (no detections), 299.7ms
Speed: 1.2ms preprocess, 299.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmGADnKBz3ZvQEIf2SRoZg_270.JPG: 480x640 (no detections), 298.5ms
Speed: 1.1ms preprocess, 298.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmHkiDFC-ChaoRcOHEknvA_0.JPG: 480x640 1 Waste, 299.1ms
Speed: 1.2ms preprocess, 299.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmHkiDFC-ChaoRcOHEknvA_90.JPG: 480x640 (no detections), 304.6ms
Speed: 1.1ms preprocess, 304.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmHkiDFC-ChaoRcOHEknvA_180.JPG: 480x640 (no detections), 311.2ms
Speed: 1.2ms preprocess, 311.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmHkiDFC-ChaoRcOHEknvA_270.JPG: 480x640 1 Waste, 306.2ms
Speed: 1.5ms preprocess, 306.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmIxwl4wlrd2CcTb3Fo2hA_0.JPG: 480x640 (no detections), 309.2ms
Speed: 1.2ms preprocess, 309.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmIxwl4wlrd2CcTb3Fo2hA_90.JPG: 480x640 (no detections), 303.0ms
Speed: 1.2ms preprocess, 303.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmIxwl4wlrd2CcTb3Fo2hA_180.JPG: 480x640 (no detections), 302.3ms
Speed: 1.2ms preprocess, 302.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmIxwl4wlrd2CcTb3Fo2hA_270.JPG: 480x640 (no detections), 310.0ms
Speed: 1.3ms preprocess, 310.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmMEU3VI0yyEh_QMJ-7AHg_0.JPG: 480x640 (no detections), 310.6ms

Speed: 1.1ms preprocess, 310.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmMEU3VI0yyEh_QMJ-7AHg_90.JPG: 480x640 (no detections), 319.7ms
Speed: 1.2ms preprocess, 319.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmMEU3VI0yyEh_QMJ-7AHg_180.JPG: 480x640 (no detections), 315.2ms
Speed: 1.2ms preprocess, 315.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmMEU3VI0yyEh_QMJ-7AHg_270.JPG: 480x640 (no detections), 322.7ms
Speed: 1.9ms preprocess, 322.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmPR2JhJv5kFmm0ZsrNpSA_0.JPG: 480x640 (no detections), 305.3ms
Speed: 1.4ms preprocess, 305.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmPR2JhJv5kFmm0ZsrNpSA_90.JPG: 480x640 (no detections), 316.6ms
Speed: 1.6ms preprocess, 316.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmPR2JhJv5kFmm0ZsrNpSA_180.JPG: 480x640 (no detections), 334.0ms
Speed: 1.0ms preprocess, 334.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmPR2JhJv5kFmm0ZsrNpSA_270.JPG: 480x640 (no detections), 328.4ms
Speed: 1.9ms preprocess, 328.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmQgFgpf8CqAbcJ9s1WXag_0.JPG: 480x640 (no detections), 319.4ms
Speed: 1.4ms preprocess, 319.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmQgFgpf8CqAbcJ9s1WXag_90.JPG: 480x640 (no detections), 307.6ms
Speed: 1.4ms preprocess, 307.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmQgFgpf8CqAbcJ9s1WXag_180.JPG: 480x640 (no detections), 306.3ms
Speed: 1.1ms preprocess, 306.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmQgFgpf8CqAbcJ9s1WXag_270.JPG: 480x640 (no detections), 304.4ms
Speed: 1.2ms preprocess, 304.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmU_ztq9kmHT-vp1O5vrfg_0.JPG: 480x640 (no detections), 305.4ms
Speed: 1.5ms preprocess, 305.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmU_ztq9kmHT-vp1O5vrfg_90.JPG: 480x640 (no detections), 302.9ms
Speed: 1.2ms preprocess, 302.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmU_ztq9kmHT-vp1O5vrfg_180.JPG: 480x640 (no detections), 303.2ms
Speed: 1.2ms preprocess, 303.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmU_ztq9kmHT-vp1O5vrfg_270.JPG: 480x640 (no detections), 298.6ms
Speed: 1.1ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmXBXdqjE0CBSpEGvJEayw_0.JPG: 480x640 (no detections), 291.2ms
Speed: 1.3ms preprocess, 291.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmXBXdqjE0CBSpEGvJEayw_90.JPG: 480x640 (no detections), 309.7ms
Speed: 1.3ms preprocess, 309.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmXBXdqjE0CBSpEGvJEayw_180.JPG: 480x640 (no detections), 302.3ms
Speed: 1.4ms preprocess, 302.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmXBXdqjE0CBSpEGvJEayw_270.JPG: 480x640 (no detections), 297.8ms
Speed: 1.2ms preprocess, 297.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmZQUHT2DqirDP9jKgJo3g_0.JPG: 480x640 (no detections), 297.7ms
Speed: 1.2ms preprocess, 297.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmZQUHT2DqirDP9jKgJo3g_90.JPG: 480x640 (no detections), 299.0ms
Speed: 1.2ms preprocess, 299.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmZQUHT2DqirDP9jKgJo3g_180.JPG: 480x640 (no detections), 301.7ms
Speed: 1.1ms preprocess, 301.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmZQUHT2DqirDP9jKgJo3g_270.JPG: 480x640 (no detections), 301.9ms
Speed: 1.7ms preprocess, 301.9ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xm_xqYV6mxN236pmEnb8sg_0.JPG: 480x640 (no detections), 303.7ms
Speed: 1.9ms preprocess, 303.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xm_xqYV6mxN236pmEnb8sg_90.JPG: 480x640 (no detections), 302.8ms
Speed: 1.2ms preprocess, 302.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xm_xqYV6mxN236pmEnb8sg_180.JPG: 480x640 (no detections), 298.9ms
Speed: 1.3ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xm_xqYV6mxN236pmEnb8sg_270.JPG: 480x640 (no detections), 305.1ms
Speed: 1.1ms preprocess, 305.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmaabIK1TZRqOIxMpo63uQ_0.JPG: 480x640 (no detections), 298.2ms
Speed: 1.1ms preprocess, 298.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmaabIK1TZRqOIxMpo63uQ_90.JPG: 480x640 (no detections), 300.8ms
Speed: 1.3ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmaabIK1TZRqOIxMpo63uQ_180.JPG: 480x640 (no detections), 301.2ms
Speed: 1.3ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmaabIK1TZRqOIxMpo63uQ_270.JPG: 480x640 (no detections), 298.0ms
Speed: 1.2ms preprocess, 298.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmdtiRYXTIed4lvNCDEWOQ_0.JPG: 480x640 (no detections), 298.9ms
Speed: 1.2ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmdtiRYXTIed4lvNCDEWOQ_90.JPG: 480x640 (no detections), 305.3ms
Speed: 1.2ms preprocess, 305.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmdtiRYXTIed4lvNCDEWOQ_180.JPG: 480x640 (no detections), 296.3ms
Speed: 1.3ms preprocess, 296.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmdtiRYXTIed4lvNCDEWOQ_270.JPG: 480x640 (no detections), 299.7ms
Speed: 1.2ms preprocess, 299.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmhL7UcQoPIDZEZabq-JuQ_0.JPG: 480x640 (no detections), 300.7ms
Speed: 1.2ms preprocess, 300.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmhL7UcQoPIDZEZabq-JuQ_90.JPG: 480x640 (no detections), 302.0ms
Speed: 1.1ms preprocess, 302.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmhL7UcQoPIDZEZabq-JuQ_180.JPG: 480x640 (no detections), 303.4ms
Speed: 1.2ms preprocess, 303.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmhL7UcQoPIDZEZabq-JuQ_270.JPG: 480x640 (no detections), 309.3ms
Speed: 1.3ms preprocess, 309.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmhVz0NQwpGftX07ZOLpQQ_0.JPG: 480x640 (no detections), 300.6ms
Speed: 1.2ms preprocess, 300.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmhVz0NQwpGftX07ZOLpQQ_90.JPG: 480x640 (no detections), 305.3ms
Speed: 1.4ms preprocess, 305.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmhVz0NQwpGftX07ZOLpQQ_180.JPG: 480x640 (no detections), 316.8ms
Speed: 1.3ms preprocess, 316.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmhVz0NQwpGftX07ZOLpQQ_270.JPG: 480x640 (no detections), 303.3ms
Speed: 1.2ms preprocess, 303.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmjOg96hBz6C9OXC1AvCEg_0.JPG: 480x640 (no detections), 301.5ms
Speed: 1.2ms preprocess, 301.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmjOg96hBz6C9OXC1AvCEg_90.JPG: 480x640 (no detections), 303.8ms
Speed: 1.2ms preprocess, 303.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmjOg96hBz6C9OXC1AvCEg_180.JPG: 480x640 (no detections), 306.7ms
Speed: 1.3ms preprocess, 306.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmjOg96hBz6C9OXC1AvCEg_270.JPG: 480x640 (no detections), 298.7ms
Speed: 1.2ms preprocess, 298.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmjmKTDocmBpnJ_V6TZ1ig_0.JPG: 480x640 (no detections), 300.7ms
Speed: 1.3ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmjmKTDocmBpnJ_V6TZ1ig_90.JPG: 480x640 (no detections), 299.6ms
Speed: 1.2ms preprocess, 299.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmjmKTDocmBpnJ_V6TZ1ig_180.JPG: 480x640 (no detections), 301.3ms
Speed: 1.4ms preprocess, 301.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmjmKTDocmBpnJ_V6TZ1ig_270.JPG: 480x640 (no detections), 299.5ms
Speed: 1.6ms preprocess, 299.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xml3SQ8TZe13i_BEM593wQ_0.JPG: 480x640 (no detections), 298.7ms
Speed: 1.2ms preprocess, 298.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xml3SQ8TZe13i_BEM593wQ_90.JPG: 480x640 (no detections), 299.2ms
Speed: 1.1ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xml3SQ8TZe13i_BEM593wQ_180.JPG: 480x640 (no detections), 297.7ms
Speed: 1.1ms preprocess, 297.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xml3SQ8TZe13i_BEM593wQ_270.JPG: 480x640 (no detections), 306.3ms
Speed: 1.3ms preprocess, 306.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmo4EuOKJwiUdGIrfpiocg_0.JPG: 480x640 (no detections), 301.6ms
Speed: 1.2ms preprocess, 301.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmo4EuOKJwiUdGIrfpiocg_90.JPG: 480x640 (no detections), 303.6ms
Speed: 1.1ms preprocess, 303.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmo4EuOKJwiUdGIrfpiocg_180.JPG: 480x640 (no detections), 300.7ms
Speed: 1.1ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmo4EuOKJwiUdGIrfpiocg_270.JPG: 480x640 (no detections), 300.6ms
Speed: 1.4ms preprocess, 300.6ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmoRorFK-WMD3Zs1VQ6Xbw_0.JPG: 480x640 (no detections), 300.9ms
Speed: 1.2ms preprocess, 300.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmoRorFK-WMD3Zs1VQ6Xbw_90.JPG: 480x640 (no detections), 298.4ms
Speed: 1.2ms preprocess, 298.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmoRorFK-WMD3Zs1VQ6Xbw_180.JPG: 480x640 (no detections), 299.2ms
Speed: 1.4ms preprocess, 299.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmoRorFK-WMD3Zs1VQ6Xbw_270.JPG: 480x640 (no detections), 293.6ms
Speed: 1.3ms preprocess, 293.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmqk92Oqaro0z05-7POLUg_0.JPG: 480x640 (no detections), 292.0ms
Speed: 1.3ms preprocess, 292.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmqk92Oqaro0z05-7POLUg_90.JPG: 480x640 (no detections), 302.6ms
Speed: 1.2ms preprocess, 302.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmqk92Oqaro0z05-7POLUg_180.JPG: 480x640 (no detections), 298.9ms
Speed: 1.1ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmqk92Oqaro0z05-7POLUg_270.JPG: 480x640 (no detections), 297.9ms

Speed: 1.1ms preprocess, 297.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmr7ss6micWVixnlpPF4Qg_0.JPG: 480x640 (no detections), 297.0ms
Speed: 1.1ms preprocess, 297.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmr7ss6micWVixnlpPF4Qg_90.JPG: 480x640 (no detections), 304.7ms
Speed: 1.2ms preprocess, 304.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmr7ss6micWVixnlpPF4Qg_180.JPG: 480x640 (no detections), 302.7ms
Speed: 1.2ms preprocess, 302.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmr7ss6micWVixnlpPF4Qg_270.JPG: 480x640 (no detections), 300.3ms
Speed: 1.7ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmrslShEOG4q7D4dUxvlxw_0.JPG: 480x640 (no detections), 297.9ms
Speed: 1.2ms preprocess, 297.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmrslShEOG4q7D4dUxvlxw_90.JPG: 480x640 (no detections), 302.5ms
Speed: 1.1ms preprocess, 302.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmrslShEOG4q7D4dUxvlxw_180.JPG: 480x640 (no detections), 307.3ms
Speed: 1.2ms preprocess, 307.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmrslShEOG4q7D4dUxvlxw_270.JPG: 480x640 (no detections), 300.9ms
Speed: 1.3ms preprocess, 300.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmsFv76BilzL9ZDnzgjJuQ_0.JPG: 480x640 1 Waste, 316.7ms
Speed: 1.2ms preprocess, 316.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmsFv76BilzL9ZDnzgjJuQ_90.JPG: 480x640 (no detections), 320.2ms
Speed: 1.3ms preprocess, 320.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmsFv76BilzL9ZDnzgjJuQ_180.JPG: 480x640 (no detections), 319.6ms
Speed: 1.6ms preprocess, 319.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmsFv76BilzL9ZDnzgjJuQ_270.JPG: 480x640 (no detections), 298.5ms
Speed: 1.2ms preprocess, 298.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmvQCjndbnmT2Q4tDSp0xw_0.JPG: 480x640 (no detections), 302.5ms
Speed: 1.2ms preprocess, 302.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmvQCjndbnmT2Q4tDSp0xw_90.JPG: 480x640 (no detections), 298.2ms
Speed: 1.1ms preprocess, 298.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmvQCjndbnmT2Q4tDSp0xw_180.JPG: 480x640 (no detections), 301.2ms
Speed: 1.2ms preprocess, 301.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmvQCjndbnmT2Q4tDSp0xw_270.JPG: 480x640 (no detections), 305.7ms
Speed: 1.1ms preprocess, 305.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmygE8_DTDV23nqdMcCjkA_0.JPG: 480x640 (no detections), 299.3ms
Speed: 1.1ms preprocess, 299.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmygE8_DTDV23nqdMcCjkA_90.JPG: 480x640 (no detections), 302.1ms
Speed: 1.1ms preprocess, 302.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmygE8_DTDV23nqdMcCjkA_180.JPG: 480x640 (no detections), 304.1ms
Speed: 1.3ms preprocess, 304.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmygE8_DTDV23nqdMcCjkA_270.JPG: 480x640 1 Waste, 295.8ms
Speed: 1.5ms preprocess, 295.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmzL3aUGMMPzj17pNT7VCw_0.JPG: 480x640 (no detections), 302.2ms
Speed: 1.0ms preprocess, 302.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmzL3aUGMMPzj17pNT7VCw_90.JPG: 480x640 (no detections), 300.3ms
Speed: 1.1ms preprocess, 300.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmzL3aUGMMPzj17pNT7VCw_180.JPG: 480x640 (no detections), 298.6ms
Speed: 1.2ms preprocess, 298.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmzL3aUGMMPzj17pNT7VCw_270.JPG: 480x640 (no detections), 296.2ms
Speed: 1.2ms preprocess, 296.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmzphtyDfJHwiieRZ_s6pA_0.JPG: 480x640 (no detections), 295.4ms
Speed: 1.1ms preprocess, 295.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmzphtyDfJHwiieRZ_s6pA_90.JPG: 480x640 1 Waste, 300.0ms
Speed: 1.1ms preprocess, 300.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmzphtyDfJHwiieRZ_s6pA_180.JPG: 480x640 (no detections), 296.4ms
Speed: 1.1ms preprocess, 296.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/m/xmzphtyDfJHwiieRZ_s6pA_270.JPG: 480x640 (no detections), 298.9ms
Speed: 1.1ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xn9iaT-Lyrwb0F9u0MdYxw_0.JPG: 480x640 (no detections), 303.9ms
Speed: 1.3ms preprocess, 303.9ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xn9iaT-Lyrwb0F9u0MdYxw_90.JPG: 480x640 (no detections), 299.2ms
Speed: 1.1ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xn9iaT-Lyrwb0F9u0MdYxw_180.JPG: 480x640 (no detections), 296.2ms
Speed: 1.1ms preprocess, 296.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xn9iaT-Lyrwb0F9u0MdYxw_270.JPG: 480x640 (no detections), 296.8ms
Speed: 1.7ms preprocess, 296.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnEkGnVFyBT_npgp4Gn2lA_0.JPG: 480x640 (no detections), 300.0ms
Speed: 1.1ms preprocess, 300.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnEkGnVFyBT_npgp4Gn2lA_90.JPG: 480x640 (no detections), 300.1ms
Speed: 1.3ms preprocess, 300.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnEkGnVFyBT_npgp4Gn2lA_180.JPG: 480x640 (no detections), 298.9ms
Speed: 1.4ms preprocess, 298.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnEkGnVFyBT_npgp4Gn2lA_270.JPG: 480x640 (no detections), 299.3ms
Speed: 1.6ms preprocess, 299.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnF7MNnf7ab_htIy2ZqFtA_0.JPG: 480x640 (no detections), 302.1ms
Speed: 1.1ms preprocess, 302.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnF7MNnf7ab_htIy2ZqFtA_90.JPG: 480x640 (no detections), 301.0ms
Speed: 1.3ms preprocess, 301.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnF7MNnf7ab_htIy2ZqFtA_180.JPG: 480x640 (no detections), 301.6ms
Speed: 1.2ms preprocess, 301.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnF7MNnf7ab_htIy2ZqFtA_270.JPG: 480x640 (no detections), 297.3ms
Speed: 1.2ms preprocess, 297.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnGG7Tm5DOEDlrgQG-3oFQ_0.JPG: 480x640 (no detections), 297.1ms
Speed: 1.1ms preprocess, 297.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnGG7Tm5DOEDlrgQG-3oFQ_90.JPG: 480x640 (no detections), 302.6ms
Speed: 1.4ms preprocess, 302.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnGG7Tm5DOEDlrgQG-3oFQ_180.JPG: 480x640 (no detections), 295.9ms
Speed: 1.4ms preprocess, 295.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnGG7Tm5DOEDlrgQG-3oFQ_270.JPG: 480x640 (no detections), 307.6ms
Speed: 1.3ms preprocess, 307.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnGklY4LHchrOAyNchxvfw_0.JPG: 480x640 (no detections), 298.3ms
Speed: 1.2ms preprocess, 298.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnGklY4LHchrOAyNchxvfw_90.JPG: 480x640 (no detections), 301.7ms
Speed: 1.2ms preprocess, 301.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnGklY4LHchrOAyNchxvfw_180.JPG: 480x640 (no detections), 305.4ms
Speed: 1.1ms preprocess, 305.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnGklY4LHchrOAyNchxvfw_270.JPG: 480x640 (no detections), 294.2ms
Speed: 1.4ms preprocess, 294.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnIHHRvvBXTOQCDAfzYnHg_0.JPG: 480x640 (no detections), 292.4ms
Speed: 1.3ms preprocess, 292.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnIHHRvvBXTOQCDAfzYnHg_90.JPG: 480x640 (no detections), 294.5ms
Speed: 1.2ms preprocess, 294.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnIHHRvvBXTOQCDAfzYnHg_180.JPG: 480x640 (no detections), 292.6ms
Speed: 1.2ms preprocess, 292.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnIHHRvvBXTOQCDAfzYnHg_270.JPG: 480x640 (no detections), 301.2ms
Speed: 1.2ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnIbCElWl-rbLccepbZIwQ_0.JPG: 480x640 (no detections), 298.4ms
Speed: 1.3ms preprocess, 298.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnIbCElWl-rbLccepbZIwQ_90.JPG: 480x640 (no detections), 297.7ms
Speed: 1.1ms preprocess, 297.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnIbCElWl-rbLccepbZIwQ_180.JPG: 480x640 (no detections), 300.5ms
Speed: 1.0ms preprocess, 300.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnIbCElWl-rbLccepbZIwQ_270.JPG: 480x640 (no detections), 297.2ms
Speed: 1.1ms preprocess, 297.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnIpG7v6x23lIhJWnOW7Rw_0.JPG: 480x640 (no detections), 296.7ms
Speed: 1.1ms preprocess, 296.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnIpG7v6x23lIhJWnOW7Rw_90.JPG: 480x640 (no detections), 300.1ms
Speed: 1.2ms preprocess, 300.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnIpG7v6x23lIhJWnOW7Rw_180.JPG: 480x640 (no detections), 296.9ms
Speed: 1.1ms preprocess, 296.9ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnIpG7v6x23lIhJWnOW7Rw_270.JPG: 480x640 (no detections), 301.2ms
Speed: 1.0ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnKQmHLjssYmBRWiMCjkUQ_0.JPG: 480x640 (no detections), 300.8ms
Speed: 1.5ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnKQmHLjssYmBRWiMCjkUQ_90.JPG: 480x640 (no detections), 297.9ms
Speed: 1.1ms preprocess, 297.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnKQmHLjssYmBRWiMCjkUQ_180.JPG: 480x640 (no detections), 305.7ms
Speed: 1.3ms preprocess, 305.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnKQmHLjssYmBRWiMCjkUQ_270.JPG: 480x640 (no detections), 301.9ms
Speed: 1.2ms preprocess, 301.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnN-uZvAuB0qbwXPmPExgw_0.JPG: 480x640 (no detections), 297.9ms
Speed: 1.1ms preprocess, 297.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnN-uZvAuB0qbwXPmPExgw_90.JPG: 480x640 (no detections), 300.6ms
Speed: 1.3ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnN-uZvAuB0qbwXPmPExgw_180.JPG: 480x640 (no detections), 300.3ms

Speed: 1.1ms preprocess, 300.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnN-uZvAuB0qbwXPmPExgw_270.JPG: 480x640 (no detections), 298.1ms
Speed: 1.2ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnOxeV_bGxKafbwqyylgbA_0.JPG: 480x640 (no detections), 308.0ms
Speed: 1.1ms preprocess, 308.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnOxeV_bGxKafbwqyylgbA_90.JPG: 480x640 (no detections), 305.4ms
Speed: 1.3ms preprocess, 305.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnOxeV_bGxKafbwqyylgbA_180.JPG: 480x640 (no detections), 298.6ms
Speed: 1.2ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnOxeV_bGxKafbwqyylgbA_270.JPG: 480x640 (no detections), 296.4ms
Speed: 1.2ms preprocess, 296.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnUwo6x9LLuiV2usogjvMA_0.JPG: 480x640 (no detections), 302.1ms
Speed: 1.1ms preprocess, 302.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnUwo6x9LLuiV2usogjvMA_90.JPG: 480x640 (no detections), 302.3ms
Speed: 1.2ms preprocess, 302.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnUwo6x9LLuiV2usogjvMA_180.JPG: 480x640 (no detections), 301.3ms
Speed: 1.1ms preprocess, 301.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnUwo6x9LLuiV2usogjvMA_270.JPG: 480x640 (no detections), 301.6ms
Speed: 1.3ms preprocess, 301.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnZ1aPwT5nPtSHgfj4_kwg_0.JPG: 480x640 (no detections), 298.6ms
Speed: 1.2ms preprocess, 298.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnZ1aPwT5nPtSHgfj4_kwg_90.JPG: 480x640 (no detections), 294.8ms
Speed: 1.3ms preprocess, 294.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnZ1aPwT5nPtSHgfj4_kwg_180.JPG: 480x640 (no detections), 304.8ms
Speed: 1.1ms preprocess, 304.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnZ1aPwT5nPtSHgfj4_kwg_270.JPG: 480x640 (no detections), 300.5ms
Speed: 1.3ms preprocess, 300.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xn_ckkvQVcKEh0VVSfeXoA_0.JPG: 480x640 (no detections), 302.5ms
Speed: 1.2ms preprocess, 302.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xn_ckkvQVcKEh0VVSfeXoA_90.JPG: 480x640 (no detections), 302.2ms
Speed: 1.3ms preprocess, 302.2ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xn_ckkvQVcKEh0VVSfeXoA_180.JPG: 480x640 (no detections), 302.6ms
Speed: 1.3ms preprocess, 302.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xn_ckkvQVcKEh0VVSfeXoA_270.JPG: 480x640 (no detections), 302.0ms
Speed: 1.5ms preprocess, 302.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xn_wfVSimF0-Ma2pB-akuA_0.JPG: 480x640 (no detections), 305.9ms
Speed: 1.5ms preprocess, 305.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xn_wfVSimF0-Ma2pB-akuA_90.JPG: 480x640 (no detections), 316.7ms
Speed: 1.2ms preprocess, 316.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xn_wfVSimF0-Ma2pB-akuA_180.JPG: 480x640 (no detections), 299.7ms
Speed: 1.2ms preprocess, 299.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xn_wfVSimF0-Ma2pB-akuA_270.JPG: 480x640 (no detections), 298.7ms
Speed: 1.4ms preprocess, 298.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnaIs7Y5GvmRq2qTqAPGKQ_0.JPG: 480x640 (no detections), 300.9ms
Speed: 1.3ms preprocess, 300.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnaIs7Y5GvmRq2qTqAPGKQ_90.JPG: 480x640 (no detections), 298.4ms
Speed: 1.2ms preprocess, 298.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnaIs7Y5GvmRq2qTqAPGKQ_180.JPG: 480x640 (no detections), 296.7ms
Speed: 1.1ms preprocess, 296.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnaIs7Y5GvmRq2qTqAPGKQ_270.JPG: 480x640 (no detections), 295.5ms
Speed: 1.6ms preprocess, 295.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnaao_lDSVqk-K3BrkH15A_0.JPG: 480x640 (no detections), 301.2ms
Speed: 1.1ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnaao_lDSVqk-K3BrkH15A_90.JPG: 480x640 (no detections), 297.3ms
Speed: 1.3ms preprocess, 297.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnaao_lDSVqk-K3BrkH15A_180.JPG: 480x640 (no detections), 307.6ms
Speed: 1.0ms preprocess, 307.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnaao_lDSVqk-K3BrkH15A_270.JPG: 480x640 (no detections), 299.1ms
Speed: 1.0ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xndeqAD0knnqN1WseI-yng_0.JPG: 480x640 (no detections), 298.3ms
Speed: 1.1ms preprocess, 298.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xndeqAD0knnqN1WseI-yng_90.JPG: 480x640 (no detections), 292.2ms
Speed: 1.3ms preprocess, 292.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xndeqAD0knnqN1WseI-yng_180.JPG: 480x640 (no detections), 300.8ms
Speed: 1.5ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xndeqAD0knnqN1WseI-yng_270.JPG: 480x640 (no detections), 300.3ms
Speed: 1.3ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnf8VX74Rr9RlM-PundSEQ_0.JPG: 480x640 (no detections), 303.7ms
Speed: 1.3ms preprocess, 303.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnf8VX74Rr9RlM-PundSEQ_90.JPG: 480x640 (no detections), 301.9ms
Speed: 1.3ms preprocess, 301.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnf8VX74Rr9RlM-PundSEQ_180.JPG: 480x640 1 Waste, 296.2ms
Speed: 1.6ms preprocess, 296.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnf8VX74Rr9RlM-PundSEQ_270.JPG: 480x640 1 Waste, 302.9ms
Speed: 1.3ms preprocess, 302.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnfBk29a0j8d32NP0x7zsQ_0.JPG: 480x640 (no detections), 297.7ms
Speed: 1.2ms preprocess, 297.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnfBk29a0j8d32NP0x7zsQ_90.JPG: 480x640 (no detections), 303.8ms
Speed: 1.3ms preprocess, 303.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnfBk29a0j8d32NP0x7zsQ_180.JPG: 480x640 (no detections), 294.3ms
Speed: 1.2ms preprocess, 294.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnfBk29a0j8d32NP0x7zsQ_270.JPG: 480x640 (no detections), 294.2ms
Speed: 1.2ms preprocess, 294.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xngfrFyMZzQt5QGRzyP9dA_0.JPG: 480x640 (no detections), 298.0ms
Speed: 1.1ms preprocess, 298.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xngfrFyMZzQt5QGRzyP9dA_90.JPG: 480x640 (no detections), 295.7ms
Speed: 1.2ms preprocess, 295.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xngfrFyMZzQt5QGRzyP9dA_180.JPG: 480x640 (no detections), 300.0ms
Speed: 1.3ms preprocess, 300.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xngfrFyMZzQt5QGRzyP9dA_270.JPG: 480x640 (no detections), 297.5ms
Speed: 1.3ms preprocess, 297.5ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnm8hvEiehf9Y-5TTs-zEw_0.JPG: 480x640 (no detections), 302.4ms
Speed: 1.2ms preprocess, 302.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnm8hvEiehf9Y-5TTs-zEw_90.JPG: 480x640 (no detections), 297.6ms
Speed: 1.2ms preprocess, 297.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnm8hvEiehf9Y-5TTs-zEw_180.JPG: 480x640 (no detections), 299.3ms
Speed: 1.1ms preprocess, 299.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnm8hvEiehf9Y-5TTs-zEw_270.JPG: 480x640 (no detections), 297.6ms
Speed: 1.4ms preprocess, 297.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnrQw5L5FZ_WLYvofZWSww_0.JPG: 480x640 (no detections), 295.3ms
Speed: 1.2ms preprocess, 295.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnrQw5L5FZ_WLYvofZWSww_90.JPG: 480x640 (no detections), 303.6ms
Speed: 1.3ms preprocess, 303.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnrQw5L5FZ_WLYvofZWSww_180.JPG: 480x640 (no detections), 299.6ms
Speed: 1.1ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnrQw5L5FZ_WLYvofZWSww_270.JPG: 480x640 (no detections), 294.5ms
Speed: 1.1ms preprocess, 294.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnuS23G7_jas2aIPGwdHbA_0.JPG: 480x640 (no detections), 301.5ms
Speed: 1.3ms preprocess, 301.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnuS23G7_jas2aIPGwdHbA_90.JPG: 480x640 (no detections), 296.3ms
Speed: 1.3ms preprocess, 296.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnuS23G7_jas2aIPGwdHbA_180.JPG: 480x640 (no detections), 297.0ms
Speed: 1.2ms preprocess, 297.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnuS23G7_jas2aIPGwdHbA_270.JPG: 480x640 (no detections), 298.9ms
Speed: 1.1ms preprocess, 298.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnxAIaCnrcWzrFjhTCHwzA_0.JPG: 480x640 (no detections), 295.9ms
Speed: 1.0ms preprocess, 295.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnxAIaCnrcWzrFjhTCHwzA_90.JPG: 480x640 (no detections), 292.0ms
Speed: 1.1ms preprocess, 292.0ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnxAIaCnrcWzrFjhTCHwzA_180.JPG: 480x640 (no detections), 298.5ms
Speed: 1.1ms preprocess, 298.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnxAIaCnrcWzrFjhTCHwzA_270.JPG: 480x640 (no detections), 304.9ms
Speed: 1.2ms preprocess, 304.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnxUuZQOMe7KopQv11impQ_0.JPG: 480x640 (no detections), 296.8ms
Speed: 1.1ms preprocess, 296.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnxUuZQOMe7KopQv11impQ_90.JPG: 480x640 (no detections), 297.7ms
Speed: 1.0ms preprocess, 297.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnxUuZQOMe7KopQv11impQ_180.JPG: 480x640 (no detections), 296.7ms
Speed: 1.1ms preprocess, 296.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnxUuZQOMe7KopQv11impQ_270.JPG: 480x640 (no detections), 301.2ms
Speed: 1.1ms preprocess, 301.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnyVuLGhvb6OFl-p_RuC8A_0.JPG: 480x640 (no detections), 300.2ms
Speed: 1.2ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnyVuLGhvb6OFl-p_RuC8A_90.JPG: 480x640 (no detections), 302.5ms

Speed: 1.6ms preprocess, 302.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnyVuLGhvb6OFl-p_RuC8A_180.JPG: 480x640 1 Waste, 299.6ms
Speed: 1.3ms preprocess, 299.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/N/xnyVuLGhvb6OFl-p_RuC8A_270.JPG: 480x640 1 Waste, 302.4ms
Speed: 1.1ms preprocess, 302.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xo0F7jbn5OGAxSDpdSa9cA_0.JPG: 480x640 (no detections), 299.0ms
Speed: 1.1ms preprocess, 299.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xo0F7jbn5OGAxSDpdSa9cA_90.JPG: 480x640 (no detections), 298.9ms
Speed: 1.6ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xo0F7jbn5OGAxSDpdSa9cA_180.JPG: 480x640 (no detections), 297.5ms
Speed: 1.7ms preprocess, 297.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xo0F7jbn5OGAxSDpdSa9cA_270.JPG: 480x640 (no detections), 297.9ms
Speed: 1.5ms preprocess, 297.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xo15FMhoQ8q0DddneztWng_0.JPG: 480x640 1 Waste, 294.6ms
Speed: 1.4ms preprocess, 294.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xo15FMhoQ8q0DddneztWng_90.JPG: 480x640 (no detections), 298.6ms
Speed: 1.3ms preprocess, 298.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xo15FMhoQ8q0DddneztWng_180.JPG: 480x640 (no detections), 298.6ms
Speed: 1.3ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xo15FMhoQ8q0DddneztWng_270.JPG: 480x640 (no detections), 295.4ms
Speed: 1.2ms preprocess, 295.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xo1jiZq6lR-upm6XWlTMfA_0.JPG: 480x640 (no detections), 297.8ms
Speed: 1.3ms preprocess, 297.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xo1jiZq6lR-upm6XWlTMfA_90.JPG: 480x640 (no detections), 296.5ms
Speed: 1.2ms preprocess, 296.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xo1jiZq6lR-upm6XWlTMfA_180.JPG: 480x640 (no detections), 297.5ms
Speed: 1.0ms preprocess, 297.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xo1jiZq6lR-upm6XWlTMfA_270.JPG: 480x640 (no detections), 301.2ms
Speed: 1.1ms preprocess, 301.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xo66474C0t13WS8yhupm1A_0.JPG: 480x640 (no detections), 296.3ms
Speed: 1.3ms preprocess, 296.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xo66474C0t13WS8yhupm1A_90.JPG: 480x640 (no detections), 301.3ms
Speed: 1.1ms preprocess, 301.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xo66474C0t13WS8yhupm1A_180.JPG: 480x640 (no detections), 300.7ms
Speed: 1.1ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xo66474C0t13WS8yhupm1A_270.JPG: 480x640 1 Waste, 301.0ms
Speed: 1.3ms preprocess, 301.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xo9HFlZguGKgQEh0JZ8U_w_0.JPG: 480x640 (no detections), 296.4ms
Speed: 1.1ms preprocess, 296.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xo9HFlZguGKgQEh0JZ8U_w_90.JPG: 480x640 (no detections), 300.4ms
Speed: 1.1ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xo9HFlZguGKgQEh0JZ8U_w_180.JPG: 480x640 (no detections), 296.1ms
Speed: 1.0ms preprocess, 296.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xo9HFlZguGKgQEh0JZ8U_w_270.JPG: 480x640 (no detections), 303.5ms
Speed: 1.2ms preprocess, 303.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoCuYgU5c4ehkOjJOvhtmA_0.JPG: 480x640 (no detections), 301.1ms
Speed: 1.2ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoCuYgU5c4ehkOjJOvhtmA_90.JPG: 480x640 (no detections), 297.5ms
Speed: 1.2ms preprocess, 297.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoCuYgU5c4ehkOjJOvhtmA_180.JPG: 480x640 (no detections), 297.7ms
Speed: 1.1ms preprocess, 297.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoCuYgU5c4ehkOjJOvhtmA_270.JPG: 480x640 (no detections), 303.2ms
Speed: 1.1ms preprocess, 303.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoFtiS2lc3O2oSXlTlIJ8g_0.JPG: 480x640 (no detections), 308.3ms
Speed: 1.2ms preprocess, 308.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoFtiS2lc3O2oSXlTlIJ8g_90.JPG: 480x640 (no detections), 296.7ms
Speed: 1.3ms preprocess, 296.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoFtiS2lc3O2oSXlTlIJ8g_180.JPG: 480x640 (no detections), 292.8ms
Speed: 1.1ms preprocess, 292.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoFtiS2lc3O2oSXlTlIJ8g_270.JPG: 480x640 (no detections), 302.1ms
Speed: 1.6ms preprocess, 302.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoG0M-laU9x7p36_6UBbsQ_0.JPG: 480x640 (no detections), 300.3ms
Speed: 1.2ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoG0M-laU9x7p36_6UBbsQ_90.JPG: 480x640 (no detections), 301.9ms
Speed: 1.1ms preprocess, 301.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoG0M-laU9x7p36_6UBbsQ_180.JPG: 480x640 (no detections), 304.0ms
Speed: 1.8ms preprocess, 304.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoG0M-laU9x7p36_6UBbsQ_270.JPG: 480x640 (no detections), 302.8ms
Speed: 1.4ms preprocess, 302.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoGa-wMk9BtY3xCQcKUBRg_0.JPG: 480x640 (no detections), 299.1ms
Speed: 1.3ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoGa-wMk9BtY3xCQcKUBRg_90.JPG: 480x640 (no detections), 300.5ms
Speed: 1.2ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoGa-wMk9BtY3xCQcKUBRg_180.JPG: 480x640 (no detections), 296.3ms
Speed: 1.2ms preprocess, 296.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoGa-wMk9BtY3xCQcKUBRg_270.JPG: 480x640 (no detections), 303.2ms
Speed: 1.1ms preprocess, 303.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoIi1Z7yHpuRLjQZahjrGQ_0.JPG: 480x640 (no detections), 296.5ms
Speed: 1.1ms preprocess, 296.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoIi1Z7yHpuRLjQZahjrGQ_90.JPG: 480x640 (no detections), 303.6ms
Speed: 1.3ms preprocess, 303.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoIi1Z7yHpuRLjQZahjrGQ_180.JPG: 480x640 (no detections), 298.2ms
Speed: 1.3ms preprocess, 298.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoIi1Z7yHpuRLjQZahjrGQ_270.JPG: 480x640 (no detections), 301.1ms
Speed: 1.2ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoKtfGfGSRi7Mj0Zny1N-w_0.JPG: 480x640 (no detections), 299.1ms
Speed: 1.2ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoKtfGfGSRi7Mj0Zny1N-w_90.JPG: 480x640 (no detections), 294.8ms
Speed: 1.2ms preprocess, 294.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoKtfGfGSRi7Mj0Zny1N-w_180.JPG: 480x640 (no detections), 299.2ms
Speed: 1.2ms preprocess, 299.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoKtfGfGSRi7Mj0Zny1N-w_270.JPG: 480x640 (no detections), 301.0ms
Speed: 1.2ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoQ5ck2TP74YHx9U08ikhA_0.JPG: 480x640 (no detections), 296.9ms
Speed: 1.2ms preprocess, 296.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoQ5ck2TP74YHx9U08ikhA_90.JPG: 480x640 (no detections), 296.6ms
Speed: 1.4ms preprocess, 296.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoQ5ck2TP74YHx9U08ikhA_180.JPG: 480x640 (no detections), 297.1ms
Speed: 1.5ms preprocess, 297.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoQ5ck2TP74YHx9U08ikhA_270.JPG: 480x640 1 Waste, 305.6ms
Speed: 1.6ms preprocess, 305.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoRllmoT3KN2TMIStiOC4Q_0.JPG: 480x640 (no detections), 298.5ms
Speed: 1.2ms preprocess, 298.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoRllmoT3KN2TMIStiOC4Q_90.JPG: 480x640 (no detections), 303.9ms
Speed: 1.2ms preprocess, 303.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoRllmoT3KN2TMIStiOC4Q_180.JPG: 480x640 1 Waste, 302.9ms
Speed: 1.2ms preprocess, 302.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoRllmoT3KN2TMIStiOC4Q_270.JPG: 480x640 1 Waste, 299.4ms
Speed: 1.4ms preprocess, 299.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoSoVqYJM4rJHVZ1jmCXZA_0.JPG: 480x640 (no detections), 302.0ms
Speed: 1.3ms preprocess, 302.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoSoVqYJM4rJHVZ1jmCXZA_90.JPG: 480x640 (no detections), 297.5ms
Speed: 1.2ms preprocess, 297.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoSoVqYJM4rJHVZ1jmCXZA_180.JPG: 480x640 (no detections), 299.5ms
Speed: 1.2ms preprocess, 299.5ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoSoVqYJM4rJHVZ1jmCXZA_270.JPG: 480x640 (no detections), 293.4ms
Speed: 1.2ms preprocess, 293.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoTyQ-L8laXHJmr-o2d2Pg_0.JPG: 480x640 (no detections), 297.0ms
Speed: 1.1ms preprocess, 297.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoTyQ-L8laXHJmr-o2d2Pg_90.JPG: 480x640 (no detections), 298.6ms
Speed: 1.1ms preprocess, 298.6ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoTyQ-L8laXHJmr-o2d2Pg_180.JPG: 480x640 (no detections), 299.9ms
Speed: 1.2ms preprocess, 299.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoTyQ-L8laXHJmr-o2d2Pg_270.JPG: 480x640 (no detections), 298.9ms
Speed: 1.1ms preprocess, 298.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoZh5EF8xvU7y4I3h_h2-A_0.JPG: 480x640 (no detections), 301.3ms
Speed: 1.5ms preprocess, 301.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoZh5EF8xvU7y4I3h_h2-A_90.JPG: 480x640 (no detections), 301.0ms
Speed: 1.3ms preprocess, 301.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoZh5EF8xvU7y4I3h_h2-A_180.JPG: 480x640 (no detections), 304.0ms
Speed: 1.2ms preprocess, 304.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoZh5EF8xvU7y4I3h_h2-A_270.JPG: 480x640 (no detections), 305.3ms
Speed: 1.1ms preprocess, 305.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoaG8wObXrAGcnsSVvuKtQ_0.JPG: 480x640 (no detections), 298.3ms

Speed: 1.4ms preprocess, 298.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoaG8wObXrAGcnsSVvuKtQ_90.JPG: 480x640 (no detections), 297.0ms
Speed: 1.1ms preprocess, 297.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoaG8wObXrAGcnsSVvuKtQ_180.JPG: 480x640 (no detections), 295.4ms
Speed: 1.3ms preprocess, 295.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoaG8wObXrAGcnsSVvuKtQ_270.JPG: 480x640 (no detections), 303.7ms
Speed: 1.3ms preprocess, 303.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xodFMuVxB2a4tW0VZ9-Zxg_0.JPG: 480x640 (no detections), 294.7ms
Speed: 1.3ms preprocess, 294.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xodFMuVxB2a4tW0VZ9-Zxg_90.JPG: 480x640 (no detections), 302.9ms
Speed: 1.2ms preprocess, 302.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xodFMuVxB2a4tW0VZ9-Zxg_180.JPG: 480x640 (no detections), 303.0ms
Speed: 1.2ms preprocess, 303.0ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xodFMuVxB2a4tW0VZ9-Zxg_270.JPG: 480x640 (no detections), 301.6ms
Speed: 1.4ms preprocess, 301.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoilW_ErBwsnMn8PSz2_Mw_0.JPG: 480x640 (no detections), 295.6ms
Speed: 1.5ms preprocess, 295.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoilW_ErBwsnMn8PSz2_Mw_90.JPG: 480x640 (no detections), 297.2ms
Speed: 1.3ms preprocess, 297.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoilW_ErBwsnMn8PSz2_Mw_180.JPG: 480x640 (no detections), 300.1ms
Speed: 1.1ms preprocess, 300.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoilW_ErBwsnMn8PSz2_Mw_270.JPG: 480x640 (no detections), 297.9ms
Speed: 1.2ms preprocess, 297.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xon_ToC_cV-yIaM7-jQlDw_0.JPG: 480x640 (no detections), 387.7ms
Speed: 1.1ms preprocess, 387.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xon_ToC_cV-yIaM7-jQlDw_90.JPG: 480x640 (no detections), 302.2ms
Speed: 1.7ms preprocess, 302.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xon_ToC_cV-yIaM7-jQlDw_180.JPG: 480x640 1 Waste, 297.9ms
Speed: 1.4ms preprocess, 297.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xon_ToC_cV-yIaM7-jQlDw_270.JPG: 480x640 (no detections), 301.7ms
Speed: 1.3ms preprocess, 301.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xooEnwCZfPx7sIgk9hMkkQ_0.JPG: 480x640 (no detections), 292.8ms
Speed: 1.1ms preprocess, 292.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xooEnwCZfPx7sIgk9hMkkQ_90.JPG: 480x640 (no detections), 296.1ms
Speed: 1.2ms preprocess, 296.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xooEnwCZfPx7sIgk9hMkkQ_180.JPG: 480x640 (no detections), 300.7ms
Speed: 1.4ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xooEnwCZfPx7sIgk9hMkkQ_270.JPG: 480x640 (no detections), 301.5ms
Speed: 1.0ms preprocess, 301.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoqEeL2gexA4ZEgziB9VuA_0.JPG: 480x640 (no detections), 298.0ms
Speed: 1.6ms preprocess, 298.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoqEeL2gexA4ZEgziB9VuA_90.JPG: 480x640 (no detections), 294.0ms
Speed: 1.2ms preprocess, 294.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoqEeL2gexA4ZEgziB9VuA_180.JPG: 480x640 (no detections), 296.7ms
Speed: 1.9ms preprocess, 296.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoqEeL2gexA4ZEgziB9VuA_270.JPG: 480x640 (no detections), 292.9ms
Speed: 1.1ms preprocess, 292.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoqwpMIM5SoJqWGUbqzLRw_0.JPG: 480x640 (no detections), 298.1ms
Speed: 1.2ms preprocess, 298.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoqwpMIM5SoJqWGUbqzLRw_90.JPG: 480x640 (no detections), 305.1ms
Speed: 1.1ms preprocess, 305.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoqwpMIM5SoJqWGUbqzLRw_180.JPG: 480x640 (no detections), 303.9ms
Speed: 1.1ms preprocess, 303.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xoqwpMIM5SoJqWGUbqzLRw_270.JPG: 480x640 (no detections), 297.5ms
Speed: 1.2ms preprocess, 297.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xor-26qwuEgeeaMfYFU_Kg_0.JPG: 480x640 (no detections), 300.9ms
Speed: 1.2ms preprocess, 300.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xor-26qwuEgeeaMfYFU_Kg_90.JPG: 480x640 (no detections), 302.5ms
Speed: 1.3ms preprocess, 302.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xor-26qwuEgeeaMfYFU_Kg_180.JPG: 480x640 (no detections), 297.9ms
Speed: 1.2ms preprocess, 297.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xor-26qwuEgeeaMfYFU_Kg_270.JPG: 480x640 (no detections), 300.4ms
Speed: 1.1ms preprocess, 300.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xosGKX4QUE7JtdkrflQ08w_0.JPG: 480x640 (no detections), 300.8ms
Speed: 1.2ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xosGKX4QUE7JtdkrflQ08w_90.JPG: 480x640 (no detections), 301.5ms
Speed: 1.1ms preprocess, 301.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xosGKX4QUE7JtdkrflQ08w_180.JPG: 480x640 (no detections), 304.0ms
Speed: 1.6ms preprocess, 304.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/O/xosGKX4QUE7JtdkrflQ08w_270.JPG: 480x640 (no detections), 298.6ms
Speed: 1.2ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xp0VQmx6Q5odf0hPYkdUPg_0.JPG: 480x640 1 Waste, 301.3ms
Speed: 1.1ms preprocess, 301.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xp0VQmx6Q5odf0hPYkdUPg_90.JPG: 480x640 1 Waste, 303.3ms
Speed: 1.4ms preprocess, 303.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xp0VQmx6Q5odf0hPYkdUPg_180.JPG: 480x640 (no detections), 301.5ms
Speed: 1.3ms preprocess, 301.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xp0VQmx6Q5odf0hPYkdUPg_270.JPG: 480x640 (no detections), 303.3ms
Speed: 1.2ms preprocess, 303.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xp27xMWSmA3BFDo-BXcPIA_0.JPG: 480x640 (no detections), 301.6ms
Speed: 1.1ms preprocess, 301.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xp27xMWSmA3BFDo-BXcPIA_90.JPG: 480x640 (no detections), 303.5ms
Speed: 1.2ms preprocess, 303.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xp27xMWSmA3BFDo-BXcPIA_180.JPG: 480x640 (no detections), 299.9ms
Speed: 1.2ms preprocess, 299.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xp27xMWSmA3BFDo-BXcPIA_270.JPG: 480x640 1 Waste, 299.8ms
Speed: 1.1ms preprocess, 299.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xp5qrTMf7126rfTsaS8rjQ_0.JPG: 480x640 1 Waste, 304.8ms
Speed: 1.3ms preprocess, 304.8ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xp5qrTMf7126rfTsaS8rjQ_90.JPG: 480x640 (no detections), 299.4ms
Speed: 1.5ms preprocess, 299.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xp5qrTMf7126rfTsaS8rjQ_180.JPG: 480x640 1 Waste, 302.7ms
Speed: 1.4ms preprocess, 302.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xp5qrTMf7126rfTsaS8rjQ_270.JPG: 480x640 (no detections), 299.4ms
Speed: 1.1ms preprocess, 299.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xp8pHleWNHF00L6Mq271mA_0.JPG: 480x640 (no detections), 300.3ms
Speed: 1.1ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xp8pHleWNHF00L6Mq271mA_90.JPG: 480x640 (no detections), 300.4ms
Speed: 1.2ms preprocess, 300.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xp8pHleWNHF00L6Mq271mA_180.JPG: 480x640 (no detections), 299.6ms
Speed: 1.2ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xp8pHleWNHF00L6Mq271mA_270.JPG: 480x640 (no detections), 307.7ms
Speed: 1.2ms preprocess, 307.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpA3ZD7KtfNGUXel7TspiA_0.JPG: 480x640 (no detections), 308.3ms
Speed: 1.7ms preprocess, 308.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpA3ZD7KtfNGUXel7TspiA_90.JPG: 480x640 (no detections), 296.8ms
Speed: 1.2ms preprocess, 296.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpA3ZD7KtfNGUXel7TspiA_180.JPG: 480x640 (no detections), 297.9ms
Speed: 1.2ms preprocess, 297.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpA3ZD7KtfNGUXel7TspiA_270.JPG: 480x640 (no detections), 299.5ms
Speed: 1.1ms preprocess, 299.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpD3m6CtocpA5akrcnjrBQ_0.JPG: 480x640 (no detections), 310.9ms
Speed: 1.2ms preprocess, 310.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpD3m6CtocpA5akrcnjrBQ_90.JPG: 480x640 (no detections), 307.5ms
Speed: 1.1ms preprocess, 307.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpD3m6CtocpA5akrcnjrBQ_180.JPG: 480x640 (no detections), 307.4ms
Speed: 1.2ms preprocess, 307.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpD3m6CtocpA5akrcnjrBQ_270.JPG: 480x640 (no detections), 330.8ms
Speed: 1.5ms preprocess, 330.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpHnpJJeAlHBilO0ei3eVw_0.JPG: 480x640 (no detections), 298.3ms
Speed: 1.5ms preprocess, 298.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpHnpJJeAlHBilO0ei3eVw_90.JPG: 480x640 (no detections), 338.4ms
Speed: 1.3ms preprocess, 338.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpHnpJJeAlHBilO0ei3eVw_180.JPG: 480x640 (no detections), 298.5ms
Speed: 1.6ms preprocess, 298.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpHnpJJeAlHBilO0ei3eVw_270.JPG: 480x640 (no detections), 308.4ms
Speed: 1.1ms preprocess, 308.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpJxeEYE5zyl3w4kfdJ8gw_0.JPG: 480x640 (no detections), 316.6ms
Speed: 1.3ms preprocess, 316.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpJxeEYE5zyl3w4kfdJ8gw_90.JPG: 480x640 (no detections), 338.1ms
Speed: 1.2ms preprocess, 338.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpJxeEYE5zyl3w4kfdJ8gw_180.JPG: 480x640 (no detections), 388.6ms
Speed: 1.3ms preprocess, 388.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpJxeEYE5zyl3w4kfdJ8gw_270.JPG: 480x640 (no detections), 312.4ms

Speed: 1.3ms preprocess, 312.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpK0pVrb4DOr6xvAyKzPQA_0.JPG: 480x640 (no detections), 294.8ms
Speed: 1.5ms preprocess, 294.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpK0pVrb4DOr6xvAyKzPQA_90.JPG: 480x640 (no detections), 297.2ms
Speed: 1.3ms preprocess, 297.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpK0pVrb4DOr6xvAyKzPQA_180.JPG: 480x640 (no detections), 298.4ms
Speed: 1.3ms preprocess, 298.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpK0pVrb4DOr6xvAyKzPQA_270.JPG: 480x640 (no detections), 304.8ms
Speed: 1.3ms preprocess, 304.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpMYI4MJfaOMBWze3HpSUw_0.JPG: 480x640 (no detections), 302.3ms
Speed: 1.3ms preprocess, 302.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpMYI4MJfaOMBWze3HpSUw_90.JPG: 480x640 (no detections), 315.6ms
Speed: 2.3ms preprocess, 315.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpMYI4MJfaOMBWze3HpSUw_180.JPG: 480x640 (no detections), 310.4ms
Speed: 1.2ms preprocess, 310.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpMYI4MJfaOMBWze3HpSUw_270.JPG: 480x640 (no detections), 307.6ms
Speed: 1.2ms preprocess, 307.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpN_XjmVvQbX3T05X9HLDw_0.JPG: 480x640 (no detections), 303.6ms
Speed: 1.3ms preprocess, 303.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpN_XjmVvQbX3T05X9HLDw_90.JPG: 480x640 (no detections), 303.8ms
Speed: 1.2ms preprocess, 303.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpN_XjmVvQbX3T05X9HLDw_180.JPG: 480x640 (no detections), 324.1ms
Speed: 1.3ms preprocess, 324.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpN_XjmVvQbX3T05X9HLDw_270.JPG: 480x640 (no detections), 305.3ms
Speed: 1.2ms preprocess, 305.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpNdDB7WRoRg01hk-51yaw_0.JPG: 480x640 (no detections), 304.5ms
Speed: 1.3ms preprocess, 304.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpNdDB7WRoRg01hk-51yaw_90.JPG: 480x640 (no detections), 301.0ms
Speed: 1.6ms preprocess, 301.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpNdDB7WRoRg01hk-51yaw_180.JPG: 480x640 (no detections), 307.9ms
Speed: 1.2ms preprocess, 307.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpNdDB7WRoRg01hk-51yaw_270.JPG: 480x640 (no detections), 300.1ms
Speed: 1.1ms preprocess, 300.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpOQCJ3amf_H13t27EzoeA_0.JPG: 480x640 (no detections), 298.9ms
Speed: 1.1ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpOQCJ3amf_H13t27EzoeA_90.JPG: 480x640 (no detections), 300.0ms
Speed: 1.5ms preprocess, 300.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpOQCJ3amf_H13t27EzoeA_180.JPG: 480x640 (no detections), 305.4ms
Speed: 1.2ms preprocess, 305.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpOQCJ3amf_H13t27EzoeA_270.JPG: 480x640 (no detections), 298.1ms
Speed: 1.4ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpTPOzKFnmpHa0NiluUmPw_0.JPG: 480x640 (no detections), 308.0ms
Speed: 1.2ms preprocess, 308.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpTPOzKFnmpHa0NiluUmPw_90.JPG: 480x640 (no detections), 301.2ms
Speed: 1.2ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpTPOzKFnmpHa0NiluUmPw_180.JPG: 480x640 (no detections), 299.6ms
Speed: 1.1ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpTPOzKFnmpHa0NiluUmPw_270.JPG: 480x640 (no detections), 306.5ms
Speed: 1.5ms preprocess, 306.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpUUmSndcSHmRXCsnEo1eg_0.JPG: 480x640 (no detections), 300.2ms
Speed: 1.2ms preprocess, 300.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpUUmSndcSHmRXCsnEo1eg_90.JPG: 480x640 (no detections), 305.3ms
Speed: 1.1ms preprocess, 305.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpUUmSndcSHmRXCsnEo1eg_180.JPG: 480x640 (no detections), 301.8ms
Speed: 1.2ms preprocess, 301.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpUUmSndcSHmRXCsnEo1eg_270.JPG: 480x640 (no detections), 301.1ms
Speed: 1.2ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpVH44HEZaCkGFfIo3XGKg_0.JPG: 480x640 (no detections), 305.0ms
Speed: 1.4ms preprocess, 305.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpVH44HEZaCkGFfIo3XGKg_90.JPG: 480x640 (no detections), 302.9ms
Speed: 1.1ms preprocess, 302.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpVH44HEZaCkGFfIo3XGKg_180.JPG: 480x640 (no detections), 298.9ms
Speed: 1.2ms preprocess, 298.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpVH44HEZaCkGFfIo3XGKg_270.JPG: 480x640 (no detections), 299.0ms
Speed: 1.1ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpZXSpYw_unU-hWhEZeiWQ_0.JPG: 480x640 (no detections), 302.1ms
Speed: 1.3ms preprocess, 302.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpZXSpYw_unU-hWhEZeiWQ_90.JPG: 480x640 (no detections), 303.7ms
Speed: 1.3ms preprocess, 303.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpZXSpYw_unU-hWhEZeiWQ_180.JPG: 480x640 (no detections), 294.4ms
Speed: 1.1ms preprocess, 294.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpZXSpYw_unU-hWhEZeiWQ_270.JPG: 480x640 (no detections), 303.7ms
Speed: 1.1ms preprocess, 303.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpaC2qVkH-htr4Dz-wZVHA_0.JPG: 480x640 (no detections), 299.2ms
Speed: 1.1ms preprocess, 299.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpaC2qVkH-htr4Dz-wZVHA_90.JPG: 480x640 (no detections), 304.2ms
Speed: 1.3ms preprocess, 304.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpaC2qVkH-htr4Dz-wZVHA_180.JPG: 480x640 (no detections), 301.5ms
Speed: 1.2ms preprocess, 301.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpaC2qVkH-htr4Dz-wZVHA_270.JPG: 480x640 (no detections), 298.4ms
Speed: 1.2ms preprocess, 298.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpkeTUOvyp-CzRFlleiiRQ_0.JPG: 480x640 (no detections), 303.4ms
Speed: 1.2ms preprocess, 303.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpkeTUOvyp-CzRFlleiiRQ_90.JPG: 480x640 (no detections), 296.8ms
Speed: 1.3ms preprocess, 296.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpkeTUOvyp-CzRFlleiiRQ_180.JPG: 480x640 (no detections), 306.4ms
Speed: 1.1ms preprocess, 306.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpkeTUOvyp-CzRFlleiiRQ_270.JPG: 480x640 (no detections), 296.9ms
Speed: 1.4ms preprocess, 296.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpoByDtmn--ArniHX2ho6Q_0.JPG: 480x640 (no detections), 302.7ms
Speed: 1.1ms preprocess, 302.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpoByDtmn--ArniHX2ho6Q_90.JPG: 480x640 (no detections), 301.8ms
Speed: 1.3ms preprocess, 301.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpoByDtmn--ArniHX2ho6Q_180.JPG: 480x640 1 Waste, 294.7ms
Speed: 1.2ms preprocess, 294.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpoByDtmn--ArniHX2ho6Q_270.JPG: 480x640 (no detections), 303.1ms
Speed: 1.2ms preprocess, 303.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpqZUd2fzW2E_Jpz_6sRAA_0.JPG: 480x640 (no detections), 297.7ms
Speed: 1.2ms preprocess, 297.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpqZUd2fzW2E_Jpz_6sRAA_90.JPG: 480x640 (no detections), 305.1ms
Speed: 1.1ms preprocess, 305.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpqZUd2fzW2E_Jpz_6sRAA_180.JPG: 480x640 (no detections), 299.3ms
Speed: 1.4ms preprocess, 299.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpqZUd2fzW2E_Jpz_6sRAA_270.JPG: 480x640 (no detections), 303.0ms
Speed: 1.2ms preprocess, 303.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpqjeqLm2HkmV19EFOjvLQ_0.JPG: 480x640 (no detections), 296.9ms
Speed: 1.5ms preprocess, 296.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpqjeqLm2HkmV19EFOjvLQ_90.JPG: 480x640 (no detections), 296.1ms
Speed: 1.1ms preprocess, 296.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpqjeqLm2HkmV19EFOjvLQ_180.JPG: 480x640 1 Waste, 299.6ms
Speed: 1.1ms preprocess, 299.6ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpqjeqLm2HkmV19EFOjvLQ_270.JPG: 480x640 (no detections), 299.7ms
Speed: 1.4ms preprocess, 299.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xprkKSgkthd2kcgJOGsCHQ_0.JPG: 480x640 (no detections), 301.0ms
Speed: 1.2ms preprocess, 301.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xprkKSgkthd2kcgJOGsCHQ_90.JPG: 480x640 (no detections), 303.9ms
Speed: 1.2ms preprocess, 303.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xprkKSgkthd2kcgJOGsCHQ_180.JPG: 480x640 (no detections), 301.7ms
Speed: 1.2ms preprocess, 301.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xprkKSgkthd2kcgJOGsCHQ_270.JPG: 480x640 (no detections), 301.6ms
Speed: 1.1ms preprocess, 301.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpsBbfkHb0zqZJCORfOV2g_0.JPG: 480x640 (no detections), 301.6ms
Speed: 1.7ms preprocess, 301.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpsBbfkHb0zqZJCORfOV2g_90.JPG: 480x640 (no detections), 302.7ms
Speed: 1.1ms preprocess, 302.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpsBbfkHb0zqZJCORfOV2g_180.JPG: 480x640 (no detections), 305.4ms
Speed: 1.2ms preprocess, 305.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpsBbfkHb0zqZJCORfOV2g_270.JPG: 480x640 (no detections), 299.6ms
Speed: 1.1ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpusiflIEbsnt83fAh9TkA_0.JPG: 480x640 (no detections), 299.0ms
Speed: 1.2ms preprocess, 299.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpusiflIEbsnt83fAh9TkA_90.JPG: 480x640 (no detections), 306.1ms
Speed: 1.2ms preprocess, 306.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpusiflIEbsnt83fAh9TkA_180.JPG: 480x640 (no detections), 296.8ms

Speed: 1.7ms preprocess, 296.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpusiflIEbsnt83fAh9TkA_270.JPG: 480x640 (no detections), 305.2ms
Speed: 1.0ms preprocess, 305.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpvAdYZOcmPVqB-vyIbc9A_0.JPG: 480x640 (no detections), 299.4ms
Speed: 1.5ms preprocess, 299.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpvAdYZOcmPVqB-vyIbc9A_90.JPG: 480x640 (no detections), 297.0ms
Speed: 1.9ms preprocess, 297.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpvAdYZOcmPVqB-vyIbc9A_180.JPG: 480x640 (no detections), 301.9ms
Speed: 1.2ms preprocess, 301.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpvAdYZOcmPVqB-vyIbc9A_270.JPG: 480x640 (no detections), 299.0ms
Speed: 1.0ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpvt1fbF1CqLkm1iCOuQzg_0.JPG: 480x640 (no detections), 299.0ms
Speed: 1.0ms preprocess, 299.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpvt1fbF1CqLkm1iCOuQzg_90.JPG: 480x640 (no detections), 303.3ms
Speed: 1.1ms preprocess, 303.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpvt1fbF1CqLkm1iCOuQzg_180.JPG: 480x640 (no detections), 301.6ms
Speed: 1.2ms preprocess, 301.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpvt1fbF1CqLkm1iCOuQzg_270.JPG: 480x640 1 Waste, 302.9ms
Speed: 1.1ms preprocess, 302.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpy844JQFcB8d-6oE9jeGQ_0.JPG: 480x640 (no detections), 304.1ms
Speed: 1.2ms preprocess, 304.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpy844JQFcB8d-6oE9jeGQ_90.JPG: 480x640 (no detections), 300.6ms
Speed: 1.1ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpy844JQFcB8d-6oE9jeGQ_180.JPG: 480x640 (no detections), 301.0ms
Speed: 1.2ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpy844JQFcB8d-6oE9jeGQ_270.JPG: 480x640 (no detections), 298.8ms
Speed: 1.2ms preprocess, 298.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpyIM3OR1iqDg0Zibs0r0A_0.JPG: 480x640 (no detections), 299.4ms
Speed: 1.1ms preprocess, 299.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpyIM3OR1iqDg0Zibs0r0A_90.JPG: 480x640 (no detections), 295.9ms
Speed: 1.2ms preprocess, 295.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpyIM3OR1iqDg0Zibs0r0A_180.JPG: 480x640 (no detections), 298.3ms
Speed: 1.1ms preprocess, 298.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpyIM3OR1iqDg0Zibs0r0A_270.JPG: 480x640 (no detections), 298.9ms
Speed: 1.1ms preprocess, 298.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpz__csHmSMquyTpUIRs1g_0.JPG: 480x640 1 Waste, 297.5ms
Speed: 1.1ms preprocess, 297.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpz__csHmSMquyTpUIRs1g_90.JPG: 480x640 (no detections), 298.9ms
Speed: 1.5ms preprocess, 298.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpz__csHmSMquyTpUIRs1g_180.JPG: 480x640 (no detections), 300.0ms
Speed: 1.2ms preprocess, 300.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpz__csHmSMquyTpUIRs1g_270.JPG: 480x640 (no detections), 297.1ms
Speed: 1.4ms preprocess, 297.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpzn-OPzjUYmJ5ys0BAXJw_0.JPG: 480x640 (no detections), 304.2ms
Speed: 1.1ms preprocess, 304.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpzn-OPzjUYmJ5ys0BAXJw_90.JPG: 480x640 (no detections), 296.1ms
Speed: 1.1ms preprocess, 296.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpzn-OPzjUYmJ5ys0BAXJw_180.JPG: 480x640 (no detections), 297.1ms
Speed: 1.2ms preprocess, 297.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpzn-OPzjUYmJ5ys0BAXJw_270.JPG: 480x640 (no detections), 295.8ms
Speed: 1.2ms preprocess, 295.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpzuSBT2B2qz2PniDID1qQ_0.JPG: 480x640 (no detections), 301.9ms
Speed: 1.2ms preprocess, 301.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpzuSBT2B2qz2PniDID1qQ_90.JPG: 480x640 (no detections), 299.7ms
Speed: 1.4ms preprocess, 299.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpzuSBT2B2qz2PniDID1qQ_180.JPG: 480x640 (no detections), 299.2ms
Speed: 1.2ms preprocess, 299.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/P/xpzuSBT2B2qz2PniDID1qQ_270.JPG: 480x640 (no detections), 299.6ms
Speed: 1.6ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xq2bEsQDVZwCSvUIlJ22oQ_0.JPG: 480x640 (no detections), 317.0ms
Speed: 1.2ms preprocess, 317.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xq2bEsQDVZwCSvUIlJ22oQ_90.JPG: 480x640 (no detections), 300.8ms
Speed: 1.2ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xq2bEsQDVZwCSvUIlJ22oQ_180.JPG: 480x640 (no detections), 301.9ms
Speed: 1.2ms preprocess, 301.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xq2bEsQDVZwCSvUIlJ22oQ_270.JPG: 480x640 (no detections), 303.2ms
Speed: 1.2ms preprocess, 303.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xq2hvp3yVvaLFQkspkugrw_0.JPG: 480x640 (no detections), 302.1ms
Speed: 1.3ms preprocess, 302.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xq2hvp3yVvaLFQkspkugrw_90.JPG: 480x640 (no detections), 299.1ms
Speed: 1.5ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xq2hvp3yVvaLFQkspkugrw_180.JPG: 480x640 (no detections), 302.8ms
Speed: 1.9ms preprocess, 302.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xq2hvp3yVvaLFQkspkugrw_270.JPG: 480x640 (no detections), 301.5ms
Speed: 1.2ms preprocess, 301.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xq7kHhQ3UyJcgKH9wsfEyg_0.JPG: 480x640 (no detections), 293.8ms
Speed: 1.2ms preprocess, 293.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xq7kHhQ3UyJcgKH9wsfEyg_90.JPG: 480x640 (no detections), 303.0ms
Speed: 1.2ms preprocess, 303.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xq7kHhQ3UyJcgKH9wsfEyg_180.JPG: 480x640 (no detections), 297.9ms
Speed: 1.2ms preprocess, 297.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xq7kHhQ3UyJcgKH9wsfEyg_270.JPG: 480x640 (no detections), 294.6ms
Speed: 1.3ms preprocess, 294.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xq8LaeE-2lSHBS21uMeybA_0.JPG: 480x640 (no detections), 300.3ms
Speed: 1.4ms preprocess, 300.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xq8LaeE-2lSHBS21uMeybA_90.JPG: 480x640 (no detections), 301.8ms
Speed: 1.1ms preprocess, 301.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xq8LaeE-2lSHBS21uMeybA_180.JPG: 480x640 (no detections), 301.2ms
Speed: 1.4ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xq8LaeE-2lSHBS21uMeybA_270.JPG: 480x640 (no detections), 296.6ms
Speed: 1.2ms preprocess, 296.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqD2kZu7_gk17xxL6zYk3w_0.JPG: 480x640 (no detections), 299.8ms
Speed: 1.2ms preprocess, 299.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqD2kZu7_gk17xxL6zYk3w_90.JPG: 480x640 (no detections), 299.8ms
Speed: 1.1ms preprocess, 299.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqD2kZu7_gk17xxL6zYk3w_180.JPG: 480x640 (no detections), 307.0ms
Speed: 1.1ms preprocess, 307.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqD2kZu7_gk17xxL6zYk3w_270.JPG: 480x640 (no detections), 296.5ms
Speed: 1.1ms preprocess, 296.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqDLMSUZS1qkKs3x_V-5ig_0.JPG: 480x640 (no detections), 302.9ms
Speed: 1.2ms preprocess, 302.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqDLMSUZS1qkKs3x_V-5ig_90.JPG: 480x640 (no detections), 295.3ms
Speed: 1.2ms preprocess, 295.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqDLMSUZS1qkKs3x_V-5ig_180.JPG: 480x640 (no detections), 301.8ms
Speed: 1.1ms preprocess, 301.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqDLMSUZS1qkKs3x_V-5ig_270.JPG: 480x640 (no detections), 299.3ms
Speed: 1.3ms preprocess, 299.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqKegt-GKqas5yfTtk0F7A_0.JPG: 480x640 (no detections), 302.1ms
Speed: 1.2ms preprocess, 302.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqKegt-GKqas5yfTtk0F7A_90.JPG: 480x640 (no detections), 301.8ms
Speed: 1.3ms preprocess, 301.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqKegt-GKqas5yfTtk0F7A_180.JPG: 480x640 1 Waste, 296.9ms
Speed: 1.2ms preprocess, 296.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqKegt-GKqas5yfTtk0F7A_270.JPG: 480x640 (no detections), 294.2ms
Speed: 1.1ms preprocess, 294.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqQIiy7t33TjJ-O5Ptujbw_0.JPG: 480x640 (no detections), 296.3ms
Speed: 1.1ms preprocess, 296.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqQIiy7t33TjJ-O5Ptujbw_90.JPG: 480x640 (no detections), 297.8ms
Speed: 1.2ms preprocess, 297.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqQIiy7t33TjJ-O5Ptujbw_180.JPG: 480x640 (no detections), 304.8ms
Speed: 1.4ms preprocess, 304.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqQIiy7t33TjJ-O5Ptujbw_270.JPG: 480x640 (no detections), 302.1ms
Speed: 1.1ms preprocess, 302.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqWG-o85HcY1s7SqduaD9g_0.JPG: 480x640 (no detections), 302.2ms
Speed: 1.0ms preprocess, 302.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqWG-o85HcY1s7SqduaD9g_90.JPG: 480x640 (no detections), 303.0ms
Speed: 1.4ms preprocess, 303.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqWG-o85HcY1s7SqduaD9g_180.JPG: 480x640 (no detections), 302.8ms
Speed: 1.4ms preprocess, 302.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqWG-o85HcY1s7SqduaD9g_270.JPG: 480x640 (no detections), 289.4ms
Speed: 1.3ms preprocess, 289.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqWTBVJwHSmr-IMz6oKrRA_0.JPG: 480x640 (no detections), 288.7ms
Speed: 1.3ms preprocess, 288.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqWTBVJwHSmr-IMz6oKrRA_90.JPG: 480x640 (no detections), 295.0ms

Speed: 1.2ms preprocess, 295.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqWTBVJwHSmr-IMz6oKrRA_180.JPG: 480x640 (no detections), 296.3ms
Speed: 1.1ms preprocess, 296.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqWTBVJwHSmr-IMz6oKrRA_270.JPG: 480x640 (no detections), 300.5ms
Speed: 1.7ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqXAUIQEUOobVkNYT2CKJg_0.JPG: 480x640 (no detections), 304.2ms
Speed: 1.2ms preprocess, 304.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqXAUIQEUOobVkNYT2CKJg_90.JPG: 480x640 (no detections), 303.3ms
Speed: 1.5ms preprocess, 303.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqXAUIQEUOobVkNYT2CKJg_180.JPG: 480x640 (no detections), 300.3ms
Speed: 1.2ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqXAUIQEUOobVkNYT2CKJg_270.JPG: 480x640 (no detections), 296.2ms
Speed: 1.2ms preprocess, 296.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqZLXFlBy_wMdzYHIgX71w_0.JPG: 480x640 (no detections), 301.5ms
Speed: 1.1ms preprocess, 301.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqZLXFlBy_wMdzYHIgX71w_90.JPG: 480x640 (no detections), 303.6ms
Speed: 1.6ms preprocess, 303.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqZLXFlBy_wMdzYHIgX71w_180.JPG: 480x640 (no detections), 298.8ms
Speed: 1.0ms preprocess, 298.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqZLXFlBy_wMdzYHIgX71w_270.JPG: 480x640 (no detections), 302.7ms
Speed: 1.2ms preprocess, 302.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqdMBifJwbkZnD4vtYSocg_0.JPG: 480x640 (no detections), 300.5ms
Speed: 1.1ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqdMBifJwbkZnD4vtYSocg_90.JPG: 480x640 (no detections), 300.2ms
Speed: 1.1ms preprocess, 300.2ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqdMBifJwbkZnD4vtYSocg_180.JPG: 480x640 (no detections), 296.6ms
Speed: 1.3ms preprocess, 296.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqdMBifJwbkZnD4vtYSocg_270.JPG: 480x640 (no detections), 302.0ms
Speed: 1.2ms preprocess, 302.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqeTNfax5QfeNYElAqnZQA_0.JPG: 480x640 (no detections), 295.8ms
Speed: 1.6ms preprocess, 295.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqeTNfax5QfeNYElAqnZQA_90.JPG: 480x640 (no detections), 295.0ms
Speed: 1.2ms preprocess, 295.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqeTNfax5QfeNYElAqnZQA_180.JPG: 480x640 (no detections), 300.1ms
Speed: 1.4ms preprocess, 300.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqeTNfax5QfeNYElAqnZQA_270.JPG: 480x640 (no detections), 302.7ms
Speed: 1.3ms preprocess, 302.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqfp8GCOrPf4seYI29cXUA_0.JPG: 480x640 (no detections), 299.1ms
Speed: 1.3ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqfp8GCOrPf4seYI29cXUA_90.JPG: 480x640 (no detections), 297.4ms
Speed: 1.3ms preprocess, 297.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqfp8GCOrPf4seYI29cXUA_180.JPG: 480x640 (no detections), 306.8ms
Speed: 1.2ms preprocess, 306.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqfp8GCOrPf4seYI29cXUA_270.JPG: 480x640 (no detections), 304.8ms
Speed: 1.3ms preprocess, 304.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqfyIdRKLzygW-I70fFajA_0.JPG: 480x640 (no detections), 299.2ms
Speed: 1.2ms preprocess, 299.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqfyIdRKLzygW-I70fFajA_90.JPG: 480x640 (no detections), 298.5ms
Speed: 1.4ms preprocess, 298.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqfyIdRKLzygW-I70fFajA_180.JPG: 480x640 (no detections), 297.9ms
Speed: 1.1ms preprocess, 297.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqfyIdRKLzygW-I70fFajA_270.JPG: 480x640 (no detections), 301.4ms
Speed: 1.3ms preprocess, 301.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqjjwN5-Gc-dssdQlnocYw_0.JPG: 480x640 (no detections), 307.6ms
Speed: 1.9ms preprocess, 307.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqjjwN5-Gc-dssdQlnocYw_90.JPG: 480x640 (no detections), 303.2ms
Speed: 1.1ms preprocess, 303.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqjjwN5-Gc-dssdQlnocYw_180.JPG: 480x640 (no detections), 301.6ms
Speed: 1.2ms preprocess, 301.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqjjwN5-Gc-dssdQlnocYw_270.JPG: 480x640 1 Waste, 297.8ms
Speed: 1.5ms preprocess, 297.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqm51hvxWqt9WMSzCdIOeQ_0.JPG: 480x640 (no detections), 302.0ms
Speed: 1.2ms preprocess, 302.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqm51hvxWqt9WMSzCdIOeQ_90.JPG: 480x640 (no detections), 297.8ms
Speed: 1.1ms preprocess, 297.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqm51hvxWqt9WMSzCdIOeQ_180.JPG: 480x640 (no detections), 301.3ms
Speed: 1.1ms preprocess, 301.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqm51hvxWqt9WMSzCdIOeQ_270.JPG: 480x640 (no detections), 302.6ms
Speed: 1.1ms preprocess, 302.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqsUKAjYcBkPI6QIeXQowQ_0.JPG: 480x640 (no detections), 304.4ms
Speed: 1.2ms preprocess, 304.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqsUKAjYcBkPI6QIeXQowQ_90.JPG: 480x640 (no detections), 386.1ms
Speed: 1.4ms preprocess, 386.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqsUKAjYcBkPI6QIeXQowQ_180.JPG: 480x640 (no detections), 301.6ms
Speed: 1.3ms preprocess, 301.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqsUKAjYcBkPI6QIeXQowQ_270.JPG: 480x640 (no detections), 299.7ms
Speed: 1.3ms preprocess, 299.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqvacGwvQ8atDOGpWpFSnw_0.JPG: 480x640 (no detections), 301.2ms
Speed: 1.1ms preprocess, 301.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqvacGwvQ8atDOGpWpFSnw_90.JPG: 480x640 (no detections), 290.6ms
Speed: 1.1ms preprocess, 290.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqvacGwvQ8atDOGpWpFSnw_180.JPG: 480x640 (no detections), 302.2ms
Speed: 1.1ms preprocess, 302.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqvacGwvQ8atDOGpWpFSnw_270.JPG: 480x640 (no detections), 302.5ms
Speed: 1.3ms preprocess, 302.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqxFKVUCOM4apSiatyiywg_0.JPG: 480x640 (no detections), 301.1ms
Speed: 1.3ms preprocess, 301.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqxFKVUCOM4apSiatyiywg_90.JPG: 480x640 (no detections), 296.2ms
Speed: 1.3ms preprocess, 296.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqxFKVUCOM4apSiatyiywg_180.JPG: 480x640 (no detections), 302.5ms
Speed: 1.3ms preprocess, 302.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Q/xqxFKVUCOM4apSiatyiywg_270.JPG: 480x640 (no detections), 300.1ms
Speed: 1.4ms preprocess, 300.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xr0sg7VrqYN-uVrK0uzmsA_0.JPG: 480x640 (no detections), 301.3ms
Speed: 1.3ms preprocess, 301.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xr0sg7VrqYN-uVrK0uzmsA_90.JPG: 480x640 (no detections), 297.0ms
Speed: 1.2ms preprocess, 297.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xr0sg7VrqYN-uVrK0uzmsA_180.JPG: 480x640 (no detections), 299.2ms
Speed: 1.4ms preprocess, 299.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xr0sg7VrqYN-uVrK0uzmsA_270.JPG: 480x640 (no detections), 298.3ms
Speed: 1.1ms preprocess, 298.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xr2la3ps_Mp-7S5iR2LZCw_0.JPG: 480x640 (no detections), 300.4ms
Speed: 1.0ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xr2la3ps_Mp-7S5iR2LZCw_90.JPG: 480x640 (no detections), 302.8ms
Speed: 1.2ms preprocess, 302.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xr2la3ps_Mp-7S5iR2LZCw_180.JPG: 480x640 (no detections), 295.3ms
Speed: 1.7ms preprocess, 295.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xr2la3ps_Mp-7S5iR2LZCw_270.JPG: 480x640 (no detections), 300.0ms
Speed: 1.2ms preprocess, 300.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xr2qP-Yep9sOuj7Jiu9TLQ_0.JPG: 480x640 (no detections), 301.1ms
Speed: 1.2ms preprocess, 301.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xr2qP-Yep9sOuj7Jiu9TLQ_90.JPG: 480x640 (no detections), 298.5ms
Speed: 1.2ms preprocess, 298.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xr2qP-Yep9sOuj7Jiu9TLQ_180.JPG: 480x640 1 Waste, 305.8ms
Speed: 1.5ms preprocess, 305.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xr2qP-Yep9sOuj7Jiu9TLQ_270.JPG: 480x640 (no detections), 304.0ms
Speed: 1.1ms preprocess, 304.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xr5IicTYrHEKWJI51Jv7OA_0.JPG: 480x640 (no detections), 298.0ms
Speed: 1.1ms preprocess, 298.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xr5IicTYrHEKWJI51Jv7OA_90.JPG: 480x640 1 Waste, 302.1ms
Speed: 1.0ms preprocess, 302.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xr5IicTYrHEKWJI51Jv7OA_180.JPG: 480x640 (no detections), 342.8ms
Speed: 1.2ms preprocess, 342.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xr5IicTYrHEKWJI51Jv7OA_270.JPG: 480x640 (no detections), 332.0ms
Speed: 1.4ms preprocess, 332.0ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrBT4an3MnQc81picDYk9w_0.JPG: 480x640 (no detections), 333.8ms
Speed: 1.5ms preprocess, 333.8ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrBT4an3MnQc81picDYk9w_90.JPG: 480x640 (no detections), 363.3ms
Speed: 1.2ms preprocess, 363.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrBT4an3MnQc81picDYk9w_180.JPG: 480x640 (no detections), 354.2ms
Speed: 1.7ms preprocess, 354.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrBT4an3MnQc81picDYk9w_270.JPG: 480x640 (no detections), 329.2ms
Speed: 1.7ms preprocess, 329.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrCUFVNZBaf0YaRte6T_PQ_0.JPG: 480x640 (no detections), 328.8ms

Speed: 1.9ms preprocess, 328.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrCUFVNZBaf0YaRte6T_PQ_90.JPG: 480x640 (no detections), 306.6ms
Speed: 1.1ms preprocess, 306.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrCUFVNZBaf0YaRte6T_PQ_180.JPG: 480x640 (no detections), 303.1ms
Speed: 1.4ms preprocess, 303.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrCUFVNZBaf0YaRte6T_PQ_270.JPG: 480x640 1 Waste, 299.2ms
Speed: 1.2ms preprocess, 299.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrDlplu_MPLGfKlJ5CTouQ_0.JPG: 480x640 (no detections), 303.7ms
Speed: 1.1ms preprocess, 303.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrDlplu_MPLGfKlJ5CTouQ_90.JPG: 480x640 (no detections), 309.8ms
Speed: 1.3ms preprocess, 309.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrDlplu_MPLGfKlJ5CTouQ_180.JPG: 480x640 (no detections), 304.3ms
Speed: 1.4ms preprocess, 304.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrDlplu_MPLGfKlJ5CTouQ_270.JPG: 480x640 (no detections), 318.8ms
Speed: 1.1ms preprocess, 318.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrFdUIb7DH-QFxsVr7KcPw_0.JPG: 480x640 (no detections), 307.4ms
Speed: 1.1ms preprocess, 307.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrFdUIb7DH-QFxsVr7KcPw_90.JPG: 480x640 (no detections), 302.3ms
Speed: 1.2ms preprocess, 302.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrFdUIb7DH-QFxsVr7KcPw_180.JPG: 480x640 (no detections), 304.8ms
Speed: 1.1ms preprocess, 304.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrFdUIb7DH-QFxsVr7KcPw_270.JPG: 480x640 1 Waste, 302.7ms
Speed: 1.3ms preprocess, 302.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrIOTHG6RwdrSCi4mze-4A_0.JPG: 480x640 (no detections), 303.4ms
Speed: 1.2ms preprocess, 303.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrIOTHG6RwdrSCi4mze-4A_90.JPG: 480x640 (no detections), 300.7ms
Speed: 1.2ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrIOTHG6RwdrSCi4mze-4A_180.JPG: 480x640 (no detections), 299.3ms
Speed: 1.1ms preprocess, 299.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrIOTHG6RwdrSCi4mze-4A_270.JPG: 480x640 (no detections), 298.3ms
Speed: 1.2ms preprocess, 298.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrJlczBGdbdgI1yFGFSy8w_0.JPG: 480x640 (no detections), 300.8ms
Speed: 1.1ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrJlczBGdbdgI1yFGFSy8w_90.JPG: 480x640 1 Waste, 299.5ms
Speed: 1.2ms preprocess, 299.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrJlczBGdbdgI1yFGFSy8w_180.JPG: 480x640 1 Waste, 302.1ms
Speed: 1.4ms preprocess, 302.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrJlczBGdbdgI1yFGFSy8w_270.JPG: 480x640 (no detections), 299.3ms
Speed: 2.0ms preprocess, 299.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrM3cZUuwcw_rGr-PLf_Qg_0.JPG: 480x640 (no detections), 299.2ms
Speed: 1.4ms preprocess, 299.2ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrM3cZUuwcw_rGr-PLf_Qg_90.JPG: 480x640 (no detections), 304.2ms
Speed: 1.7ms preprocess, 304.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrM3cZUuwcw_rGr-PLf_Qg_180.JPG: 480x640 (no detections), 302.4ms
Speed: 1.2ms preprocess, 302.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrM3cZUuwcw_rGr-PLf_Qg_270.JPG: 480x640 (no detections), 301.8ms
Speed: 1.1ms preprocess, 301.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrNvGOhLVVetHSLMvBA0_w_0.JPG: 480x640 (no detections), 302.4ms
Speed: 1.7ms preprocess, 302.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrNvGOhLVVetHSLMvBA0_w_90.JPG: 480x640 (no detections), 299.5ms
Speed: 1.3ms preprocess, 299.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrNvGOhLVVetHSLMvBA0_w_180.JPG: 480x640 1 Waste, 300.3ms
Speed: 1.5ms preprocess, 300.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrNvGOhLVVetHSLMvBA0_w_270.JPG: 480x640 (no detections), 297.4ms
Speed: 1.1ms preprocess, 297.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrS8Ay52CdX_LKyaGbu8dw_0.JPG: 480x640 (no detections), 296.8ms
Speed: 1.3ms preprocess, 296.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrS8Ay52CdX_LKyaGbu8dw_90.JPG: 480x640 (no detections), 303.9ms
Speed: 1.2ms preprocess, 303.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrS8Ay52CdX_LKyaGbu8dw_180.JPG: 480x640 (no detections), 297.6ms
Speed: 1.7ms preprocess, 297.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrS8Ay52CdX_LKyaGbu8dw_270.JPG: 480x640 (no detections), 303.0ms
Speed: 1.2ms preprocess, 303.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrSmEncuLcVIRmVD11HXRQ_0.JPG: 480x640 (no detections), 307.6ms
Speed: 1.2ms preprocess, 307.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrSmEncuLcVIRmVD11HXRQ_90.JPG: 480x640 (no detections), 297.8ms
Speed: 1.2ms preprocess, 297.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrSmEncuLcVIRmVD11HXRQ_180.JPG: 480x640 (no detections), 298.2ms
Speed: 1.0ms preprocess, 298.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrSmEncuLcVIRmVD11HXRQ_270.JPG: 480x640 (no detections), 298.9ms
Speed: 1.4ms preprocess, 298.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrUo_kJrzLmy1wTszItWMQ_0.JPG: 480x640 (no detections), 298.5ms
Speed: 1.5ms preprocess, 298.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrUo_kJrzLmy1wTszItWMQ_90.JPG: 480x640 (no detections), 299.0ms
Speed: 1.1ms preprocess, 299.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrUo_kJrzLmy1wTszItWMQ_180.JPG: 480x640 (no detections), 298.1ms
Speed: 1.1ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrUo_kJrzLmy1wTszItWMQ_270.JPG: 480x640 (no detections), 299.6ms
Speed: 1.3ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrXhG-QgVqekXywyJw2ACg_0.JPG: 480x640 (no detections), 298.5ms
Speed: 1.4ms preprocess, 298.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrXhG-QgVqekXywyJw2ACg_90.JPG: 480x640 (no detections), 297.2ms
Speed: 1.1ms preprocess, 297.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrXhG-QgVqekXywyJw2ACg_180.JPG: 480x640 (no detections), 300.3ms
Speed: 1.1ms preprocess, 300.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrXhG-QgVqekXywyJw2ACg_270.JPG: 480x640 (no detections), 299.2ms
Speed: 1.2ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrZ0TnXnEq67g0pivlZCDA_0.JPG: 480x640 (no detections), 303.2ms
Speed: 1.1ms preprocess, 303.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrZ0TnXnEq67g0pivlZCDA_90.JPG: 480x640 (no detections), 308.7ms
Speed: 1.2ms preprocess, 308.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrZ0TnXnEq67g0pivlZCDA_180.JPG: 480x640 (no detections), 299.6ms
Speed: 1.3ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrZ0TnXnEq67g0pivlZCDA_270.JPG: 480x640 (no detections), 299.4ms
Speed: 1.3ms preprocess, 299.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrhGHmZiqBhrY29QIn2ucQ_0.JPG: 480x640 (no detections), 299.5ms
Speed: 1.1ms preprocess, 299.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrhGHmZiqBhrY29QIn2ucQ_90.JPG: 480x640 (no detections), 297.3ms
Speed: 1.2ms preprocess, 297.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrhGHmZiqBhrY29QIn2ucQ_180.JPG: 480x640 (no detections), 298.8ms
Speed: 1.2ms preprocess, 298.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrhGHmZiqBhrY29QIn2ucQ_270.JPG: 480x640 (no detections), 300.7ms
Speed: 1.3ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrjM5CLw6haNF5qusv7_6Q_0.JPG: 480x640 (no detections), 299.7ms
Speed: 1.2ms preprocess, 299.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrjM5CLw6haNF5qusv7_6Q_90.JPG: 480x640 (no detections), 298.8ms
Speed: 1.3ms preprocess, 298.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrjM5CLw6haNF5qusv7_6Q_180.JPG: 480x640 (no detections), 298.8ms
Speed: 1.4ms preprocess, 298.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrjM5CLw6haNF5qusv7_6Q_270.JPG: 480x640 (no detections), 303.4ms
Speed: 1.2ms preprocess, 303.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrkBWv7Gsn6kXOILzxFaqg_0.JPG: 480x640 (no detections), 297.9ms
Speed: 1.3ms preprocess, 297.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrkBWv7Gsn6kXOILzxFaqg_90.JPG: 480x640 (no detections), 301.3ms
Speed: 1.1ms preprocess, 301.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrkBWv7Gsn6kXOILzxFaqg_180.JPG: 480x640 (no detections), 302.8ms
Speed: 1.9ms preprocess, 302.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrkBWv7Gsn6kXOILzxFaqg_270.JPG: 480x640 (no detections), 297.0ms
Speed: 1.2ms preprocess, 297.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrl_IJC9vgDE8QqCKZn2_A_0.JPG: 480x640 (no detections), 301.7ms
Speed: 1.2ms preprocess, 301.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrl_IJC9vgDE8QqCKZn2_A_90.JPG: 480x640 (no detections), 305.2ms
Speed: 1.1ms preprocess, 305.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrl_IJC9vgDE8QqCKZn2_A_180.JPG: 480x640 (no detections), 297.1ms
Speed: 1.1ms preprocess, 297.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrl_IJC9vgDE8QqCKZn2_A_270.JPG: 480x640 (no detections), 296.9ms
Speed: 1.4ms preprocess, 296.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrmxZfcxQLhoXJVr5br4WQ_0.JPG: 480x640 (no detections), 302.9ms
Speed: 1.1ms preprocess, 302.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrmxZfcxQLhoXJVr5br4WQ_90.JPG: 480x640 (no detections), 309.5ms
Speed: 1.7ms preprocess, 309.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrmxZfcxQLhoXJVr5br4WQ_180.JPG: 480x640 (no detections), 297.5ms
Speed: 1.2ms preprocess, 297.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrmxZfcxQLhoXJVr5br4WQ_270.JPG: 480x640 (no detections), 301.0ms

Speed: 1.2ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrxj8-UoPFwfcWuoiNjwCQ_0.JPG: 480x640 1 Waste, 299.3ms
Speed: 1.8ms preprocess, 299.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrxj8-UoPFwfcWuoiNjwCQ_90.JPG: 480x640 (no detections), 296.5ms
Speed: 1.2ms preprocess, 296.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrxj8-UoPFwfcWuoiNjwCQ_180.JPG: 480x640 (no detections), 296.3ms
Speed: 1.1ms preprocess, 296.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrxj8-UoPFwfcWuoiNjwCQ_270.JPG: 480x640 (no detections), 302.0ms
Speed: 1.2ms preprocess, 302.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrzftTA4r3VGOSuGBMesTg_0.JPG: 480x640 (no detections), 300.0ms
Speed: 1.6ms preprocess, 300.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrzftTA4r3VGOSuGBMesTg_90.JPG: 480x640 (no detections), 299.7ms
Speed: 1.4ms preprocess, 299.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrzftTA4r3VGOSuGBMesTg_180.JPG: 480x640 (no detections), 297.8ms
Speed: 1.7ms preprocess, 297.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/r/xrzftTA4r3VGOSuGBMesTg_270.JPG: 480x640 (no detections), 296.4ms
Speed: 1.2ms preprocess, 296.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xs13f1Z6dZk6G0WJ1H4TKw_0.JPG: 480x640 1 Waste, 300.6ms
Speed: 1.1ms preprocess, 300.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xs13f1Z6dZk6G0WJ1H4TKw_90.JPG: 480x640 (no detections), 303.6ms
Speed: 1.0ms preprocess, 303.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xs13f1Z6dZk6G0WJ1H4TKw_180.JPG: 480x640 (no detections), 303.2ms
Speed: 1.2ms preprocess, 303.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xs13f1Z6dZk6G0WJ1H4TKw_270.JPG: 480x640 (no detections), 301.6ms
Speed: 1.3ms preprocess, 301.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xs3TASmsr5wAFXANw0O7BA_0.JPG: 480x640 (no detections), 303.2ms
Speed: 1.2ms preprocess, 303.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xs3TASmsr5wAFXANw0O7BA_90.JPG: 480x640 (no detections), 297.8ms
Speed: 1.2ms preprocess, 297.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xs3TASmsr5wAFXANw0O7BA_180.JPG: 480x640 (no detections), 299.0ms
Speed: 1.1ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xs3TASmsr5wAFXANw0O7BA_270.JPG: 480x640 (no detections), 298.4ms
Speed: 1.2ms preprocess, 298.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xs4AUKyf1NWvCL_HPzKHiA_0.JPG: 480x640 (no detections), 305.9ms
Speed: 1.3ms preprocess, 305.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xs4AUKyf1NWvCL_HPzKHiA_90.JPG: 480x640 (no detections), 302.3ms
Speed: 1.2ms preprocess, 302.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xs4AUKyf1NWvCL_HPzKHiA_180.JPG: 480x640 (no detections), 300.8ms
Speed: 1.1ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xs4AUKyf1NWvCL_HPzKHiA_270.JPG: 480x640 (no detections), 300.5ms
Speed: 1.6ms preprocess, 300.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xs6DfGp6LFMcAyU7GTELKA_0.JPG: 480x640 (no detections), 295.3ms
Speed: 1.3ms preprocess, 295.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xs6DfGp6LFMcAyU7GTELKA_90.JPG: 480x640 (no detections), 300.7ms
Speed: 1.3ms preprocess, 300.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xs6DfGp6LFMcAyU7GTELKA_180.JPG: 480x640 (no detections), 303.7ms
Speed: 1.2ms preprocess, 303.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xs6DfGp6LFMcAyU7GTELKA_270.JPG: 480x640 (no detections), 312.7ms
Speed: 1.2ms preprocess, 312.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xs6FRcaLBU0FbrhJBiWIbQ_0.JPG: 480x640 (no detections), 303.8ms
Speed: 1.2ms preprocess, 303.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xs6FRcaLBU0FbrhJBiWIbQ_90.JPG: 480x640 (no detections), 318.0ms
Speed: 1.2ms preprocess, 318.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xs6FRcaLBU0FbrhJBiWIbQ_180.JPG: 480x640 (no detections), 302.7ms
Speed: 1.6ms preprocess, 302.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xs6FRcaLBU0FbrhJBiWIbQ_270.JPG: 480x640 (no detections), 303.0ms
Speed: 1.3ms preprocess, 303.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xs6fgkjMqAb-uTuTWJ-3Qg_0.JPG: 480x640 (no detections), 301.2ms
Speed: 1.3ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xs6fgkjMqAb-uTuTWJ-3Qg_90.JPG: 480x640 (no detections), 307.8ms
Speed: 1.0ms preprocess, 307.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xs6fgkjMqAb-uTuTWJ-3Qg_180.JPG: 480x640 (no detections), 302.7ms
Speed: 1.3ms preprocess, 302.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xs6fgkjMqAb-uTuTWJ-3Qg_270.JPG: 480x640 (no detections), 307.5ms
Speed: 1.2ms preprocess, 307.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsBt945Xh6wxPZ8cOyOGgw_0.JPG: 480x640 (no detections), 298.5ms
Speed: 1.1ms preprocess, 298.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsBt945Xh6wxPZ8cOyOGgw_90.JPG: 480x640 (no detections), 293.1ms
Speed: 1.2ms preprocess, 293.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsBt945Xh6wxPZ8cOyOGgw_180.JPG: 480x640 (no detections), 302.1ms
Speed: 1.3ms preprocess, 302.1ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsBt945Xh6wxPZ8cOyOGgw_270.JPG: 480x640 (no detections), 300.6ms
Speed: 1.7ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsC63YTRXHPyMVIFiwC8Pw_0.JPG: 480x640 (no detections), 299.3ms
Speed: 1.1ms preprocess, 299.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsC63YTRXHPyMVIFiwC8Pw_90.JPG: 480x640 (no detections), 305.0ms
Speed: 1.3ms preprocess, 305.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsC63YTRXHPyMVIFiwC8Pw_180.JPG: 480x640 (no detections), 303.1ms
Speed: 1.2ms preprocess, 303.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsC63YTRXHPyMVIFiwC8Pw_270.JPG: 480x640 (no detections), 305.0ms
Speed: 1.1ms preprocess, 305.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsFnhbpMXlYnu-XCijJvGQ_0.JPG: 480x640 (no detections), 302.3ms
Speed: 1.1ms preprocess, 302.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsFnhbpMXlYnu-XCijJvGQ_90.JPG: 480x640 (no detections), 295.1ms
Speed: 1.5ms preprocess, 295.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsFnhbpMXlYnu-XCijJvGQ_180.JPG: 480x640 (no detections), 301.5ms
Speed: 2.0ms preprocess, 301.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsFnhbpMXlYnu-XCijJvGQ_270.JPG: 480x640 (no detections), 302.1ms
Speed: 1.2ms preprocess, 302.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsJNSgkO9mDtqncZxQ3nZQ_0.JPG: 480x640 (no detections), 302.0ms
Speed: 1.5ms preprocess, 302.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsJNSgkO9mDtqncZxQ3nZQ_90.JPG: 480x640 (no detections), 303.5ms
Speed: 1.5ms preprocess, 303.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsJNSgkO9mDtqncZxQ3nZQ_180.JPG: 480x640 (no detections), 302.2ms
Speed: 1.3ms preprocess, 302.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsJNSgkO9mDtqncZxQ3nZQ_270.JPG: 480x640 (no detections), 299.8ms
Speed: 1.0ms preprocess, 299.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsMtb5fO5VA-UF5nGbxNYA_0.JPG: 480x640 (no detections), 298.1ms
Speed: 1.0ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsMtb5fO5VA-UF5nGbxNYA_90.JPG: 480x640 (no detections), 298.3ms
Speed: 1.3ms preprocess, 298.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsMtb5fO5VA-UF5nGbxNYA_180.JPG: 480x640 (no detections), 298.2ms
Speed: 1.0ms preprocess, 298.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsMtb5fO5VA-UF5nGbxNYA_270.JPG: 480x640 (no detections), 301.3ms
Speed: 1.1ms preprocess, 301.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsP7q8BDxXvlZqnFqfFN_A_0.JPG: 480x640 (no detections), 300.3ms
Speed: 1.1ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsP7q8BDxXvlZqnFqfFN_A_90.JPG: 480x640 (no detections), 297.6ms
Speed: 1.3ms preprocess, 297.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsP7q8BDxXvlZqnFqfFN_A_180.JPG: 480x640 (no detections), 294.6ms
Speed: 1.0ms preprocess, 294.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsP7q8BDxXvlZqnFqfFN_A_270.JPG: 480x640 (no detections), 302.2ms
Speed: 1.1ms preprocess, 302.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsRdxQuFSQpzVvGpZG22_g_0.JPG: 480x640 (no detections), 306.3ms
Speed: 1.1ms preprocess, 306.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsRdxQuFSQpzVvGpZG22_g_90.JPG: 480x640 (no detections), 300.0ms
Speed: 1.0ms preprocess, 300.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsRdxQuFSQpzVvGpZG22_g_180.JPG: 480x640 (no detections), 299.1ms
Speed: 1.2ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsRdxQuFSQpzVvGpZG22_g_270.JPG: 480x640 (no detections), 302.6ms
Speed: 1.4ms preprocess, 302.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsSyIU3qIcpb6GhVTrfVaA_0.JPG: 480x640 (no detections), 298.0ms
Speed: 1.1ms preprocess, 298.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsSyIU3qIcpb6GhVTrfVaA_90.JPG: 480x640 (no detections), 299.3ms
Speed: 1.1ms preprocess, 299.3ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsSyIU3qIcpb6GhVTrfVaA_180.JPG: 480x640 (no detections), 300.5ms
Speed: 1.0ms preprocess, 300.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsSyIU3qIcpb6GhVTrfVaA_270.JPG: 480x640 (no detections), 297.8ms
Speed: 1.2ms preprocess, 297.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsWGd45vwQU6A9PtYMoljw_0.JPG: 480x640 (no detections), 299.3ms
Speed: 1.2ms preprocess, 299.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsWGd45vwQU6A9PtYMoljw_90.JPG: 480x640 (no detections), 299.8ms
Speed: 1.3ms preprocess, 299.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsWGd45vwQU6A9PtYMoljw_180.JPG: 480x640 (no detections), 300.8ms

Speed: 1.1ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsWGd45vwQU6A9PtYMoljw_270.JPG: 480x640 (no detections), 299.0ms
Speed: 1.1ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsXnUr7cwuoYFd19DH3wtg_0.JPG: 480x640 (no detections), 304.4ms
Speed: 1.1ms preprocess, 304.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsXnUr7cwuoYFd19DH3wtg_90.JPG: 480x640 (no detections), 306.4ms
Speed: 1.1ms preprocess, 306.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsXnUr7cwuoYFd19DH3wtg_180.JPG: 480x640 (no detections), 299.9ms
Speed: 1.3ms preprocess, 299.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsXnUr7cwuoYFd19DH3wtg_270.JPG: 480x640 (no detections), 296.2ms
Speed: 1.1ms preprocess, 296.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsYVEGCkGRz8ynco67DS7g_0.JPG: 480x640 1 Waste, 293.3ms
Speed: 1.1ms preprocess, 293.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsYVEGCkGRz8ynco67DS7g_90.JPG: 480x640 (no detections), 299.4ms
Speed: 1.2ms preprocess, 299.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsYVEGCkGRz8ynco67DS7g_180.JPG: 480x640 (no detections), 292.4ms
Speed: 1.2ms preprocess, 292.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsYVEGCkGRz8ynco67DS7g_270.JPG: 480x640 (no detections), 298.2ms
Speed: 1.1ms preprocess, 298.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsYwxOILgTJR4PjQsWqNDA_0.JPG: 480x640 (no detections), 297.4ms
Speed: 1.1ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsYwxOILgTJR4PjQsWqNDA_90.JPG: 480x640 (no detections), 293.6ms
Speed: 1.2ms preprocess, 293.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsYwxOILgTJR4PjQsWqNDA_180.JPG: 480x640 (no detections), 296.9ms
Speed: 1.2ms preprocess, 296.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsYwxOILgTJR4PjQsWqNDA_270.JPG: 480x640 (no detections), 294.2ms
Speed: 1.1ms preprocess, 294.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsZ3ryRGYYA5blSMHmFexg_0.JPG: 480x640 1 Waste, 294.4ms
Speed: 1.2ms preprocess, 294.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsZ3ryRGYYA5blSMHmFexg_90.JPG: 480x640 (no detections), 295.3ms
Speed: 1.1ms preprocess, 295.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsZ3ryRGYYA5blSMHmFexg_180.JPG: 480x640 (no detections), 297.9ms
Speed: 1.1ms preprocess, 297.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsZ3ryRGYYA5blSMHmFexg_270.JPG: 480x640 1 Waste, 298.8ms
Speed: 1.1ms preprocess, 298.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsasbfgI4tde2tz2hY3DDw_0.JPG: 480x640 (no detections), 300.6ms
Speed: 1.3ms preprocess, 300.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsasbfgI4tde2tz2hY3DDw_90.JPG: 480x640 (no detections), 299.2ms
Speed: 1.2ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsasbfgI4tde2tz2hY3DDw_180.JPG: 480x640 (no detections), 294.4ms
Speed: 1.1ms preprocess, 294.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsasbfgI4tde2tz2hY3DDw_270.JPG: 480x640 (no detections), 296.0ms
Speed: 1.5ms preprocess, 296.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xseQME_xFou9aLZOztXCOA_0.JPG: 480x640 (no detections), 303.9ms
Speed: 1.8ms preprocess, 303.9ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xseQME_xFou9aLZOztXCOA_90.JPG: 480x640 (no detections), 293.1ms
Speed: 1.3ms preprocess, 293.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xseQME_xFou9aLZOztXCOA_180.JPG: 480x640 (no detections), 295.9ms
Speed: 1.1ms preprocess, 295.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xseQME_xFou9aLZOztXCOA_270.JPG: 480x640 (no detections), 293.5ms
Speed: 1.2ms preprocess, 293.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsi0QLqrwJK9f2nu2nc5nQ_0.JPG: 480x640 (no detections), 298.3ms
Speed: 1.1ms preprocess, 298.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsi0QLqrwJK9f2nu2nc5nQ_90.JPG: 480x640 (no detections), 297.6ms
Speed: 1.2ms preprocess, 297.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsi0QLqrwJK9f2nu2nc5nQ_180.JPG: 480x640 (no detections), 296.1ms
Speed: 1.1ms preprocess, 296.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsi0QLqrwJK9f2nu2nc5nQ_270.JPG: 480x640 (no detections), 293.3ms
Speed: 1.0ms preprocess, 293.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xskn4TZHMX6QwFSWuDli8w_0.JPG: 480x640 (no detections), 298.8ms
Speed: 1.1ms preprocess, 298.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xskn4TZHMX6QwFSWuDli8w_90.JPG: 480x640 (no detections), 293.9ms
Speed: 1.3ms preprocess, 293.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xskn4TZHMX6QwFSWuDli8w_180.JPG: 480x640 (no detections), 298.4ms
Speed: 1.1ms preprocess, 298.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xskn4TZHMX6QwFSWuDli8w_270.JPG: 480x640 (no detections), 292.3ms
Speed: 1.2ms preprocess, 292.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsmAGvP_dUV-NOhnSNRYYg_0.JPG: 480x640 (no detections), 300.1ms
Speed: 1.3ms preprocess, 300.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsmAGvP_dUV-NOhnSNRYYg_90.JPG: 480x640 (no detections), 299.0ms
Speed: 1.4ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsmAGvP_dUV-NOhnSNRYYg_180.JPG: 480x640 (no detections), 294.7ms
Speed: 1.2ms preprocess, 294.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsmAGvP_dUV-NOhnSNRYYg_270.JPG: 480x640 (no detections), 300.5ms
Speed: 1.5ms preprocess, 300.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsn_WFErfKKNh5Ge9-MJZA_0.JPG: 480x640 (no detections), 298.4ms
Speed: 1.3ms preprocess, 298.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsn_WFErfKKNh5Ge9-MJZA_90.JPG: 480x640 (no detections), 299.1ms
Speed: 1.2ms preprocess, 299.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsn_WFErfKKNh5Ge9-MJZA_180.JPG: 480x640 (no detections), 292.0ms
Speed: 1.1ms preprocess, 292.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsn_WFErfKKNh5Ge9-MJZA_270.JPG: 480x640 (no detections), 295.6ms
Speed: 1.8ms preprocess, 295.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsqPhD9zFT6_HFO7i8XWNw_0.JPG: 480x640 (no detections), 303.5ms
Speed: 1.3ms preprocess, 303.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsqPhD9zFT6_HFO7i8XWNw_90.JPG: 480x640 (no detections), 297.1ms
Speed: 1.3ms preprocess, 297.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsqPhD9zFT6_HFO7i8XWNw_180.JPG: 480x640 (no detections), 294.9ms
Speed: 1.3ms preprocess, 294.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsqPhD9zFT6_HFO7i8XWNw_270.JPG: 480x640 1 Waste, 297.1ms
Speed: 1.2ms preprocess, 297.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xst1a7VELUBxi-A0yfGvaA_0.JPG: 480x640 (no detections), 299.6ms
Speed: 1.1ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xst1a7VELUBxi-A0yfGvaA_90.JPG: 480x640 (no detections), 297.9ms
Speed: 1.1ms preprocess, 297.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xst1a7VELUBxi-A0yfGvaA_180.JPG: 480x640 (no detections), 295.8ms
Speed: 1.4ms preprocess, 295.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xst1a7VELUBxi-A0yfGvaA_270.JPG: 480x640 (no detections), 294.7ms
Speed: 1.4ms preprocess, 294.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsuCVU9MvCqbj4nJ8oNTpA_0.JPG: 480x640 (no detections), 292.5ms
Speed: 1.3ms preprocess, 292.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsuCVU9MvCqbj4nJ8oNTpA_90.JPG: 480x640 (no detections), 292.9ms
Speed: 1.1ms preprocess, 292.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsuCVU9MvCqbj4nJ8oNTpA_180.JPG: 480x640 (no detections), 300.7ms
Speed: 1.1ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsuCVU9MvCqbj4nJ8oNTpA_270.JPG: 480x640 (no detections), 296.2ms
Speed: 1.3ms preprocess, 296.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsvw_Cgnoh7uidS9hIq1jw_0.JPG: 480x640 (no detections), 295.7ms
Speed: 1.1ms preprocess, 295.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsvw_Cgnoh7uidS9hIq1jw_90.JPG: 480x640 (no detections), 292.4ms
Speed: 1.2ms preprocess, 292.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsvw_Cgnoh7uidS9hIq1jw_180.JPG: 480x640 (no detections), 295.9ms
Speed: 1.1ms preprocess, 295.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsvw_Cgnoh7uidS9hIq1jw_270.JPG: 480x640 (no detections), 302.1ms
Speed: 1.4ms preprocess, 302.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsxg09wNSFzSeueZR5VOTg_0.JPG: 480x640 (no detections), 293.6ms
Speed: 1.2ms preprocess, 293.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsxg09wNSFzSeueZR5VOTg_90.JPG: 480x640 (no detections), 295.4ms
Speed: 1.0ms preprocess, 295.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsxg09wNSFzSeueZR5VOTg_180.JPG: 480x640 (no detections), 300.2ms
Speed: 1.3ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsxg09wNSFzSeueZR5VOTg_270.JPG: 480x640 (no detections), 293.0ms
Speed: 1.1ms preprocess, 293.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsz7J-6C907DkVWx2lQiTw_0.JPG: 480x640 (no detections), 301.6ms
Speed: 1.0ms preprocess, 301.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsz7J-6C907DkVWx2lQiTw_90.JPG: 480x640 (no detections), 309.8ms
Speed: 1.1ms preprocess, 309.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsz7J-6C907DkVWx2lQiTw_180.JPG: 480x640 (no detections), 300.6ms
Speed: 1.2ms preprocess, 300.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xsz7J-6C907DkVWx2lQiTw_270.JPG: 480x640 (no detections), 290.9ms
Speed: 1.2ms preprocess, 290.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xszGWT78lK0-e4wc47ehng_0.JPG: 480x640 (no detections), 293.0ms
Speed: 1.9ms preprocess, 293.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xszGWT78lK0-e4wc47ehng_90.JPG: 480x640 (no detections), 297.4ms

Speed: 1.2ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xszGWT78lK0-e4wc47ehng_180.JPG: 480x640 (no detections), 293.6ms
Speed: 1.2ms preprocess, 293.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/s/xszGWT78lK0-e4wc47ehng_270.JPG: 480x640 (no detections), 295.6ms
Speed: 1.3ms preprocess, 295.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xt-iXfUyvBpkVlvWZGj4RQ_0.JPG: 480x640 (no detections), 303.1ms
Speed: 1.1ms preprocess, 303.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xt-iXfUyvBpkVlvWZGj4RQ_90.JPG: 480x640 (no detections), 292.3ms
Speed: 1.1ms preprocess, 292.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xt-iXfUyvBpkVlvWZGj4RQ_180.JPG: 480x640 1 Waste, 296.0ms
Speed: 1.2ms preprocess, 296.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xt-iXfUyvBpkVlvWZGj4RQ_270.JPG: 480x640 (no detections), 298.4ms
Speed: 1.0ms preprocess, 298.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xt0xQ2zkbt-sm1GZK0YZxg_0.JPG: 480x640 (no detections), 293.9ms
Speed: 1.1ms preprocess, 293.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xt0xQ2zkbt-sm1GZK0YZxg_90.JPG: 480x640 (no detections), 297.4ms
Speed: 1.2ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xt0xQ2zkbt-sm1GZK0YZxg_180.JPG: 480x640 (no detections), 292.6ms
Speed: 1.1ms preprocess, 292.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xt0xQ2zkbt-sm1GZK0YZxg_270.JPG: 480x640 (no detections), 297.1ms
Speed: 1.2ms preprocess, 297.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xt1727ed2u__SPe9dUBVdQ_0.JPG: 480x640 (no detections), 298.0ms
Speed: 1.1ms preprocess, 298.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xt1727ed2u__SPe9dUBVdQ_90.JPG: 480x640 (no detections), 296.1ms
Speed: 1.2ms preprocess, 296.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xt1727ed2u__SPe9dUBVdQ_180.JPG: 480x640 (no detections), 295.6ms
Speed: 1.2ms preprocess, 295.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xt1727ed2u__SPe9dUBVdQ_270.JPG: 480x640 (no detections), 294.8ms
Speed: 1.2ms preprocess, 294.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xt29fbHXIP3pn8U_0wECfg_0.JPG: 480x640 1 Waste, 298.6ms
Speed: 1.1ms preprocess, 298.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xt29fbHXIP3pn8U_0wECfg_90.JPG: 480x640 1 Waste, 298.2ms
Speed: 1.2ms preprocess, 298.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xt29fbHXIP3pn8U_0wECfg_180.JPG: 480x640 1 Waste, 293.9ms
Speed: 1.1ms preprocess, 293.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xt29fbHXIP3pn8U_0wECfg_270.JPG: 480x640 (no detections), 299.0ms
Speed: 1.1ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xt8THb5mGmoW8JtHhosYww_0.JPG: 480x640 (no detections), 298.6ms
Speed: 1.4ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xt8THb5mGmoW8JtHhosYww_90.JPG: 480x640 (no detections), 296.5ms
Speed: 1.6ms preprocess, 296.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xt8THb5mGmoW8JtHhosYww_180.JPG: 480x640 (no detections), 294.6ms
Speed: 1.2ms preprocess, 294.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xt8THb5mGmoW8JtHhosYww_270.JPG: 480x640 (no detections), 290.9ms
Speed: 1.2ms preprocess, 290.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtD-BbDIPhkUbIeompHj0g_0.JPG: 480x640 (no detections), 300.8ms
Speed: 1.5ms preprocess, 300.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtD-BbDIPhkUbIeompHj0g_90.JPG: 480x640 (no detections), 294.8ms
Speed: 1.4ms preprocess, 294.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtD-BbDIPhkUbIeompHj0g_180.JPG: 480x640 (no detections), 296.2ms
Speed: 1.3ms preprocess, 296.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtD-BbDIPhkUbIeompHj0g_270.JPG: 480x640 (no detections), 295.9ms
Speed: 1.3ms preprocess, 295.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtE0E79e3v5EcR9VaUUNrg_0.JPG: 480x640 (no detections), 295.7ms
Speed: 1.1ms preprocess, 295.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtE0E79e3v5EcR9VaUUNrg_90.JPG: 480x640 (no detections), 299.7ms
Speed: 1.2ms preprocess, 299.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtE0E79e3v5EcR9VaUUNrg_180.JPG: 480x640 (no detections), 300.9ms
Speed: 1.2ms preprocess, 300.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtE0E79e3v5EcR9VaUUNrg_270.JPG: 480x640 (no detections), 295.9ms
Speed: 1.2ms preprocess, 295.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtIM_zYjYDoPfIFOhioSIg_0.JPG: 480x640 (no detections), 295.4ms
Speed: 1.7ms preprocess, 295.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtIM_zYjYDoPfIFOhioSIg_90.JPG: 480x640 (no detections), 299.7ms
Speed: 1.2ms preprocess, 299.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtIM_zYjYDoPfIFOhioSIg_180.JPG: 480x640 (no detections), 295.7ms
Speed: 1.2ms preprocess, 295.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtIM_zYjYDoPfIFOhioSIg_270.JPG: 480x640 (no detections), 295.2ms
Speed: 1.1ms preprocess, 295.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtMrySuOeFxL4ANOtNx4Bw_0.JPG: 480x640 (no detections), 296.3ms
Speed: 1.2ms preprocess, 296.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtMrySuOeFxL4ANOtNx4Bw_90.JPG: 480x640 (no detections), 294.3ms
Speed: 1.1ms preprocess, 294.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtMrySuOeFxL4ANOtNx4Bw_180.JPG: 480x640 (no detections), 297.9ms
Speed: 1.1ms preprocess, 297.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtMrySuOeFxL4ANOtNx4Bw_270.JPG: 480x640 (no detections), 295.0ms
Speed: 1.3ms preprocess, 295.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtPGPwsis1W5RCxRHtSsWA_0.JPG: 480x640 (no detections), 293.0ms
Speed: 1.1ms preprocess, 293.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtPGPwsis1W5RCxRHtSsWA_90.JPG: 480x640 (no detections), 296.2ms
Speed: 1.1ms preprocess, 296.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtPGPwsis1W5RCxRHtSsWA_180.JPG: 480x640 (no detections), 295.2ms
Speed: 1.1ms preprocess, 295.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtPGPwsis1W5RCxRHtSsWA_270.JPG: 480x640 (no detections), 299.4ms
Speed: 1.3ms preprocess, 299.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtS4A8tsPnBlexTDPiKzaA_0.JPG: 480x640 (no detections), 297.8ms
Speed: 1.3ms preprocess, 297.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtS4A8tsPnBlexTDPiKzaA_90.JPG: 480x640 (no detections), 298.4ms
Speed: 1.4ms preprocess, 298.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtS4A8tsPnBlexTDPiKzaA_180.JPG: 480x640 (no detections), 295.6ms
Speed: 1.3ms preprocess, 295.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtS4A8tsPnBlexTDPiKzaA_270.JPG: 480x640 (no detections), 293.3ms
Speed: 1.1ms preprocess, 293.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtZBZbDsU1wqj8Fneq06pA_0.JPG: 480x640 (no detections), 297.8ms
Speed: 1.2ms preprocess, 297.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtZBZbDsU1wqj8Fneq06pA_90.JPG: 480x640 (no detections), 296.5ms
Speed: 1.3ms preprocess, 296.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtZBZbDsU1wqj8Fneq06pA_180.JPG: 480x640 (no detections), 298.7ms
Speed: 1.5ms preprocess, 298.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtZBZbDsU1wqj8Fneq06pA_270.JPG: 480x640 (no detections), 298.4ms
Speed: 1.2ms preprocess, 298.4ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtbW0diAGJs2b1T1efTEbQ_0.JPG: 480x640 (no detections), 294.1ms
Speed: 1.4ms preprocess, 294.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtbW0diAGJs2b1T1efTEbQ_90.JPG: 480x640 (no detections), 295.9ms
Speed: 1.3ms preprocess, 295.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtbW0diAGJs2b1T1efTEbQ_180.JPG: 480x640 (no detections), 300.6ms
Speed: 1.1ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtbW0diAGJs2b1T1efTEbQ_270.JPG: 480x640 (no detections), 291.6ms
Speed: 1.1ms preprocess, 291.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtff7mvGJ1uEdXL7MrnuXA_0.JPG: 480x640 (no detections), 296.5ms
Speed: 1.2ms preprocess, 296.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtff7mvGJ1uEdXL7MrnuXA_90.JPG: 480x640 (no detections), 297.3ms
Speed: 1.1ms preprocess, 297.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtff7mvGJ1uEdXL7MrnuXA_180.JPG: 480x640 (no detections), 299.4ms
Speed: 1.1ms preprocess, 299.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtff7mvGJ1uEdXL7MrnuXA_270.JPG: 480x640 1 Waste, 294.1ms
Speed: 1.1ms preprocess, 294.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xthZD90pYXY5NivhnwtADg_0.JPG: 480x640 (no detections), 298.5ms
Speed: 1.2ms preprocess, 298.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xthZD90pYXY5NivhnwtADg_90.JPG: 480x640 (no detections), 294.2ms
Speed: 1.2ms preprocess, 294.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xthZD90pYXY5NivhnwtADg_180.JPG: 480x640 (no detections), 295.7ms
Speed: 1.0ms preprocess, 295.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xthZD90pYXY5NivhnwtADg_270.JPG: 480x640 (no detections), 295.8ms
Speed: 1.4ms preprocess, 295.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtj8nLUtEB7bgTEr4RrIYw_0.JPG: 480x640 2 Wastes, 294.3ms
Speed: 1.2ms preprocess, 294.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtj8nLUtEB7bgTEr4RrIYw_90.JPG: 480x640 (no detections), 291.7ms
Speed: 1.0ms preprocess, 291.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtj8nLUtEB7bgTEr4RrIYw_180.JPG: 480x640 (no detections), 297.7ms
Speed: 1.2ms preprocess, 297.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtj8nLUtEB7bgTEr4RrIYw_270.JPG: 480x640 1 Waste, 293.1ms
Speed: 1.2ms preprocess, 293.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtjPrNZpFDR0e9mNHnOwzw_0.JPG: 480x640 (no detections), 296.9ms

Speed: 1.2ms preprocess, 296.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtjPrNZpFDR0e9mNHnOwzw_90.JPG: 480x640 (no detections), 298.5ms
Speed: 1.2ms preprocess, 298.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtjPrNZpFDR0e9mNHnOwzw_180.JPG: 480x640 (no detections), 305.2ms
Speed: 1.2ms preprocess, 305.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtjPrNZpFDR0e9mNHnOwzw_270.JPG: 480x640 (no detections), 298.8ms
Speed: 1.8ms preprocess, 298.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtkS9y8rNhLIv0WykAE5qA_0.JPG: 480x640 (no detections), 296.8ms
Speed: 1.1ms preprocess, 296.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtkS9y8rNhLIv0WykAE5qA_90.JPG: 480x640 (no detections), 293.3ms
Speed: 1.1ms preprocess, 293.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtkS9y8rNhLIv0WykAE5qA_180.JPG: 480x640 (no detections), 298.3ms
Speed: 1.2ms preprocess, 298.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtkS9y8rNhLIv0WykAE5qA_270.JPG: 480x640 (no detections), 298.3ms
Speed: 1.2ms preprocess, 298.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtkhOb3vdpU5_iNSxI7oqw_0.JPG: 480x640 (no detections), 293.1ms
Speed: 1.3ms preprocess, 293.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtkhOb3vdpU5_iNSxI7oqw_90.JPG: 480x640 (no detections), 295.1ms
Speed: 1.3ms preprocess, 295.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtkhOb3vdpU5_iNSxI7oqw_180.JPG: 480x640 (no detections), 294.6ms
Speed: 1.2ms preprocess, 294.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtkhOb3vdpU5_iNSxI7oqw_270.JPG: 480x640 (no detections), 294.9ms
Speed: 1.0ms preprocess, 294.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtltC5k9uC6nfiC5to6_-A_0.JPG: 480x640 (no detections), 293.6ms
Speed: 1.2ms preprocess, 293.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtltC5k9uC6nfiC5to6_-A_90.JPG: 480x640 (no detections), 292.7ms
Speed: 1.2ms preprocess, 292.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtltC5k9uC6nfiC5to6_-A_180.JPG: 480x640 (no detections), 295.1ms
Speed: 1.1ms preprocess, 295.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtltC5k9uC6nfiC5to6_-A_270.JPG: 480x640 (no detections), 297.8ms
Speed: 1.1ms preprocess, 297.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtmPTFE9C5Uv-_IofJkS-Q_0.JPG: 480x640 1 Waste, 294.0ms
Speed: 1.2ms preprocess, 294.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtmPTFE9C5Uv-_IofJkS-Q_90.JPG: 480x640 (no detections), 297.4ms
Speed: 1.1ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtmPTFE9C5Uv-_IofJkS-Q_180.JPG: 480x640 (no detections), 295.1ms
Speed: 1.1ms preprocess, 295.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtmPTFE9C5Uv-_IofJkS-Q_270.JPG: 480x640 (no detections), 297.4ms
Speed: 1.0ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtme3NT_ndLJ9QJz3y328Q_0.JPG: 480x640 1 Waste, 296.6ms
Speed: 1.1ms preprocess, 296.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtme3NT_ndLJ9QJz3y328Q_90.JPG: 480x640 (no detections), 292.6ms
Speed: 1.2ms preprocess, 292.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtme3NT_ndLJ9QJz3y328Q_180.JPG: 480x640 (no detections), 295.1ms
Speed: 1.1ms preprocess, 295.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtme3NT_ndLJ9QJz3y328Q_270.JPG: 480x640 1 Waste, 292.9ms
Speed: 1.2ms preprocess, 292.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtqa6MkOo0J5Urg6SexgCA_0.JPG: 480x640 (no detections), 296.2ms
Speed: 1.0ms preprocess, 296.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtqa6MkOo0J5Urg6SexgCA_90.JPG: 480x640 (no detections), 298.0ms
Speed: 1.2ms preprocess, 298.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtqa6MkOo0J5Urg6SexgCA_180.JPG: 480x640 (no detections), 296.3ms
Speed: 1.1ms preprocess, 296.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtqa6MkOo0J5Urg6SexgCA_270.JPG: 480x640 (no detections), 294.7ms
Speed: 1.6ms preprocess, 294.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xttgSYsW998xzVgAPCuGFw_0.JPG: 480x640 (no detections), 294.8ms
Speed: 1.0ms preprocess, 294.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xttgSYsW998xzVgAPCuGFw_90.JPG: 480x640 (no detections), 296.7ms
Speed: 1.1ms preprocess, 296.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xttgSYsW998xzVgAPCuGFw_180.JPG: 480x640 (no detections), 295.0ms
Speed: 1.2ms preprocess, 295.0ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xttgSYsW998xzVgAPCuGFw_270.JPG: 480x640 (no detections), 296.4ms
Speed: 1.0ms preprocess, 296.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xttyYp7NRFru6Aos9pN1pA_0.JPG: 480x640 (no detections), 295.7ms
Speed: 1.3ms preprocess, 295.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xttyYp7NRFru6Aos9pN1pA_90.JPG: 480x640 (no detections), 293.8ms
Speed: 1.2ms preprocess, 293.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xttyYp7NRFru6Aos9pN1pA_180.JPG: 480x640 (no detections), 297.9ms
Speed: 1.2ms preprocess, 297.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xttyYp7NRFru6Aos9pN1pA_270.JPG: 480x640 (no detections), 292.5ms
Speed: 1.1ms preprocess, 292.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtuv08QG270UuzqmheYo4g_0.JPG: 480x640 (no detections), 302.7ms
Speed: 1.0ms preprocess, 302.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtuv08QG270UuzqmheYo4g_90.JPG: 480x640 (no detections), 299.2ms
Speed: 1.4ms preprocess, 299.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtuv08QG270UuzqmheYo4g_180.JPG: 480x640 (no detections), 293.4ms
Speed: 1.3ms preprocess, 293.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/t/xtuv08QG270UuzqmheYo4g_270.JPG: 480x640 (no detections), 298.9ms
Speed: 1.2ms preprocess, 298.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xu6peJ-eTAUWmnlf64nJAw_0.JPG: 480x640 (no detections), 296.9ms
Speed: 1.0ms preprocess, 296.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xu6peJ-eTAUWmnlf64nJAw_90.JPG: 480x640 (no detections), 297.8ms
Speed: 1.2ms preprocess, 297.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xu6peJ-eTAUWmnlf64nJAw_180.JPG: 480x640 (no detections), 298.6ms
Speed: 1.2ms preprocess, 298.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xu6peJ-eTAUWmnlf64nJAw_270.JPG: 480x640 (no detections), 297.6ms
Speed: 1.1ms preprocess, 297.6ms inference, 1.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xu7wjQI8us6riaEQUSMVlg_0.JPG: 480x640 (no detections), 298.7ms
Speed: 1.3ms preprocess, 298.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xu7wjQI8us6riaEQUSMVlg_90.JPG: 480x640 (no detections), 296.0ms
Speed: 1.1ms preprocess, 296.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xu7wjQI8us6riaEQUSMVlg_180.JPG: 480x640 (no detections), 295.8ms
Speed: 1.2ms preprocess, 295.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xu7wjQI8us6riaEQUSMVlg_270.JPG: 480x640 (no detections), 299.7ms
Speed: 1.0ms preprocess, 299.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xu9WhpmIUHwaaGN1PQpfdg_0.JPG: 480x640 (no detections), 296.6ms
Speed: 1.3ms preprocess, 296.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xu9WhpmIUHwaaGN1PQpfdg_90.JPG: 480x640 (no detections), 293.8ms
Speed: 1.3ms preprocess, 293.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xu9WhpmIUHwaaGN1PQpfdg_180.JPG: 480x640 (no detections), 296.0ms
Speed: 1.1ms preprocess, 296.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xu9WhpmIUHwaaGN1PQpfdg_270.JPG: 480x640 (no detections), 300.0ms
Speed: 1.2ms preprocess, 300.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuDAQUMgar9_WPADzCe9yw_0.JPG: 480x640 (no detections), 294.4ms
Speed: 1.2ms preprocess, 294.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuDAQUMgar9_WPADzCe9yw_90.JPG: 480x640 (no detections), 300.2ms
Speed: 1.3ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuDAQUMgar9_WPADzCe9yw_180.JPG: 480x640 (no detections), 294.9ms
Speed: 1.5ms preprocess, 294.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuDAQUMgar9_WPADzCe9yw_270.JPG: 480x640 (no detections), 291.3ms
Speed: 1.3ms preprocess, 291.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuFkIbJvHUyqVwGVAptn0g_0.JPG: 480x640 (no detections), 298.9ms
Speed: 1.2ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuFkIbJvHUyqVwGVAptn0g_90.JPG: 480x640 (no detections), 295.1ms
Speed: 1.1ms preprocess, 295.1ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuFkIbJvHUyqVwGVAptn0g_180.JPG: 480x640 (no detections), 292.3ms
Speed: 1.2ms preprocess, 292.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuFkIbJvHUyqVwGVAptn0g_270.JPG: 480x640 (no detections), 292.7ms
Speed: 1.1ms preprocess, 292.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuGR9FmWU30XC1cyuxY8-w_0.JPG: 480x640 (no detections), 296.8ms
Speed: 1.3ms preprocess, 296.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuGR9FmWU30XC1cyuxY8-w_90.JPG: 480x640 (no detections), 292.9ms
Speed: 1.3ms preprocess, 292.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuGR9FmWU30XC1cyuxY8-w_180.JPG: 480x640 (no detections), 296.2ms
Speed: 1.3ms preprocess, 296.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuGR9FmWU30XC1cyuxY8-w_270.JPG: 480x640 (no detections), 299.2ms
Speed: 1.1ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuH3eugpultcsRHgcT20bA_0.JPG: 480x640 (no detections), 289.9ms
Speed: 1.1ms preprocess, 289.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuH3eugpultcsRHgcT20bA_90.JPG: 480x640 (no detections), 295.5ms
Speed: 1.0ms preprocess, 295.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuH3eugpultcsRHgcT20bA_180.JPG: 480x640 (no detections), 296.0ms
Speed: 1.5ms preprocess, 296.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuH3eugpultcsRHgcT20bA_270.JPG: 480x640 1 Waste, 293.6ms

Speed: 1.3ms preprocess, 293.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuKwfKiNxUp8_SQY04fChw_0.JPG: 480x640 2 Wastes, 295.0ms
Speed: 1.0ms preprocess, 295.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuKwfKiNxUp8_SQY04fChw_90.JPG: 480x640 (no detections), 300.6ms
Speed: 1.2ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuKwfKiNxUp8_SQY04fChw_180.JPG: 480x640 (no detections), 297.2ms
Speed: 1.1ms preprocess, 297.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuKwfKiNxUp8_SQY04fChw_270.JPG: 480x640 (no detections), 296.1ms
Speed: 1.3ms preprocess, 296.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuQKr8NoUjCSSj652P2vqg_0.JPG: 480x640 (no detections), 296.3ms
Speed: 1.1ms preprocess, 296.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuQKr8NoUjCSSj652P2vqg_90.JPG: 480x640 (no detections), 295.3ms
Speed: 1.2ms preprocess, 295.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuQKr8NoUjCSSj652P2vqg_180.JPG: 480x640 (no detections), 291.5ms
Speed: 1.1ms preprocess, 291.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuQKr8NoUjCSSj652P2vqg_270.JPG: 480x640 (no detections), 297.0ms
Speed: 1.2ms preprocess, 297.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuQa0YW-ZjKLca_eaMmJKg_0.JPG: 480x640 1 Waste, 289.0ms
Speed: 1.2ms preprocess, 289.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuQa0YW-ZjKLca_eaMmJKg_90.JPG: 480x640 (no detections), 299.4ms
Speed: 1.1ms preprocess, 299.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuQa0YW-ZjKLca_eaMmJKg_180.JPG: 480x640 (no detections), 291.4ms
Speed: 1.5ms preprocess, 291.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuQa0YW-ZjKLca_eaMmJKg_270.JPG: 480x640 (no detections), 296.1ms
Speed: 1.3ms preprocess, 296.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuRQfQ0FQCWTjUEGqK6MUw_0.JPG: 480x640 (no detections), 294.0ms
Speed: 1.6ms preprocess, 294.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuRQfQ0FQCWTjUEGqK6MUw_90.JPG: 480x640 (no detections), 300.5ms
Speed: 1.8ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuRQfQ0FQCWTjUEGqK6MUw_180.JPG: 480x640 (no detections), 299.2ms
Speed: 1.1ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuRQfQ0FQCWTjUEGqK6MUw_270.JPG: 480x640 (no detections), 293.7ms
Speed: 1.1ms preprocess, 293.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuUUdJCioSVeteCIxFYtXw_0.JPG: 480x640 (no detections), 300.2ms
Speed: 1.0ms preprocess, 300.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuUUdJCioSVeteCIxFYtXw_90.JPG: 480x640 (no detections), 293.9ms
Speed: 1.1ms preprocess, 293.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuUUdJCioSVeteCIxFYtXw_180.JPG: 480x640 (no detections), 294.2ms
Speed: 1.1ms preprocess, 294.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuUUdJCioSVeteCIxFYtXw_270.JPG: 480x640 (no detections), 297.5ms
Speed: 1.2ms preprocess, 297.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuYQXrVOnC6K6V2ZNVV9cQ_0.JPG: 480x640 (no detections), 291.8ms
Speed: 1.2ms preprocess, 291.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuYQXrVOnC6K6V2ZNVV9cQ_90.JPG: 480x640 (no detections), 298.3ms
Speed: 1.1ms preprocess, 298.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuYQXrVOnC6K6V2ZNVV9cQ_180.JPG: 480x640 (no detections), 294.1ms
Speed: 1.1ms preprocess, 294.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuYQXrVOnC6K6V2ZNVV9cQ_270.JPG: 480x640 (no detections), 294.6ms
Speed: 1.1ms preprocess, 294.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuZWxpc3Za0XQasZEtJ9bg_0.JPG: 480x640 1 Waste, 292.8ms
Speed: 1.3ms preprocess, 292.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuZWxpc3Za0XQasZEtJ9bg_90.JPG: 480x640 1 Waste, 297.3ms
Speed: 1.2ms preprocess, 297.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuZWxpc3Za0XQasZEtJ9bg_180.JPG: 480x640 (no detections), 288.3ms
Speed: 1.3ms preprocess, 288.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuZWxpc3Za0XQasZEtJ9bg_270.JPG: 480x640 (no detections), 292.4ms
Speed: 1.3ms preprocess, 292.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xubvouUwjYdydLfRrfo0sQ_0.JPG: 480x640 (no detections), 297.0ms
Speed: 1.1ms preprocess, 297.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xubvouUwjYdydLfRrfo0sQ_90.JPG: 480x640 (no detections), 297.8ms
Speed: 1.5ms preprocess, 297.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xubvouUwjYdydLfRrfo0sQ_180.JPG: 480x640 (no detections), 296.2ms
Speed: 1.2ms preprocess, 296.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xubvouUwjYdydLfRrfo0sQ_270.JPG: 480x640 (no detections), 380.3ms
Speed: 1.2ms preprocess, 380.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xudAVKhOJBbkV_a3L7-tdg_0.JPG: 480x640 (no detections), 298.4ms
Speed: 1.2ms preprocess, 298.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xudAVKhOJBbkV_a3L7-tdg_90.JPG: 480x640 (no detections), 294.1ms
Speed: 1.2ms preprocess, 294.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xudAVKhOJBbkV_a3L7-tdg_180.JPG: 480x640 (no detections), 295.4ms
Speed: 1.4ms preprocess, 295.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xudAVKhOJBbkV_a3L7-tdg_270.JPG: 480x640 (no detections), 291.8ms
Speed: 1.1ms preprocess, 291.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xudhkEGwjVAwhAPxXoOZ6w_0.JPG: 480x640 (no detections), 295.7ms
Speed: 1.1ms preprocess, 295.7ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xudhkEGwjVAwhAPxXoOZ6w_90.JPG: 480x640 (no detections), 294.4ms
Speed: 1.3ms preprocess, 294.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xudhkEGwjVAwhAPxXoOZ6w_180.JPG: 480x640 (no detections), 297.5ms
Speed: 1.2ms preprocess, 297.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xudhkEGwjVAwhAPxXoOZ6w_270.JPG: 480x640 (no detections), 300.1ms
Speed: 1.4ms preprocess, 300.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuhhXyx_nHbXKsXvXlaS9w_0.JPG: 480x640 (no detections), 294.0ms
Speed: 1.1ms preprocess, 294.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuhhXyx_nHbXKsXvXlaS9w_90.JPG: 480x640 (no detections), 296.3ms
Speed: 1.3ms preprocess, 296.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuhhXyx_nHbXKsXvXlaS9w_180.JPG: 480x640 (no detections), 300.3ms
Speed: 1.0ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuhhXyx_nHbXKsXvXlaS9w_270.JPG: 480x640 (no detections), 297.1ms
Speed: 1.2ms preprocess, 297.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xujnlhnESAla3j0wwrhUsw_0.JPG: 480x640 (no detections), 297.2ms
Speed: 1.3ms preprocess, 297.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xujnlhnESAla3j0wwrhUsw_90.JPG: 480x640 (no detections), 292.0ms
Speed: 1.2ms preprocess, 292.0ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xujnlhnESAla3j0wwrhUsw_180.JPG: 480x640 (no detections), 297.0ms
Speed: 1.6ms preprocess, 297.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xujnlhnESAla3j0wwrhUsw_270.JPG: 480x640 (no detections), 297.6ms
Speed: 1.1ms preprocess, 297.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xumT5nhQJysEXKXLTu7Q8g_0.JPG: 480x640 (no detections), 300.1ms
Speed: 1.2ms preprocess, 300.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xumT5nhQJysEXKXLTu7Q8g_90.JPG: 480x640 (no detections), 294.9ms
Speed: 1.1ms preprocess, 294.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xumT5nhQJysEXKXLTu7Q8g_180.JPG: 480x640 (no detections), 296.0ms
Speed: 1.3ms preprocess, 296.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xumT5nhQJysEXKXLTu7Q8g_270.JPG: 480x640 (no detections), 295.2ms
Speed: 1.3ms preprocess, 295.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xumVvngj35G9jZIfowESZg_0.JPG: 480x640 (no detections), 294.9ms
Speed: 1.1ms preprocess, 294.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xumVvngj35G9jZIfowESZg_90.JPG: 480x640 1 Waste, 291.5ms
Speed: 1.1ms preprocess, 291.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xumVvngj35G9jZIfowESZg_180.JPG: 480x640 (no detections), 299.1ms
Speed: 1.2ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xumVvngj35G9jZIfowESZg_270.JPG: 480x640 (no detections), 296.4ms
Speed: 1.2ms preprocess, 296.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuopRhIrAl-27cBgQ4-Dgw_0.JPG: 480x640 (no detections), 297.3ms
Speed: 1.6ms preprocess, 297.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuopRhIrAl-27cBgQ4-Dgw_90.JPG: 480x640 (no detections), 292.6ms
Speed: 1.1ms preprocess, 292.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuopRhIrAl-27cBgQ4-Dgw_180.JPG: 480x640 (no detections), 389.8ms
Speed: 1.4ms preprocess, 389.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuopRhIrAl-27cBgQ4-Dgw_270.JPG: 480x640 (no detections), 306.0ms
Speed: 1.3ms preprocess, 306.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xurEbfMhIJj2crXnOQ0g_Q_0.JPG: 480x640 (no detections), 408.4ms
Speed: 1.3ms preprocess, 408.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xurEbfMhIJj2crXnOQ0g_Q_90.JPG: 480x640 (no detections), 299.2ms
Speed: 1.2ms preprocess, 299.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xurEbfMhIJj2crXnOQ0g_Q_180.JPG: 480x640 (no detections), 372.9ms
Speed: 1.3ms preprocess, 372.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xurEbfMhIJj2crXnOQ0g_Q_270.JPG: 480x640 (no detections), 297.6ms
Speed: 1.2ms preprocess, 297.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuuEHCLDkMU9lYw5kZVxnA_0.JPG: 480x640 (no detections), 293.2ms
Speed: 1.0ms preprocess, 293.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuuEHCLDkMU9lYw5kZVxnA_90.JPG: 480x640 (no detections), 288.8ms
Speed: 1.6ms preprocess, 288.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuuEHCLDkMU9lYw5kZVxnA_180.JPG: 480x640 (no detections), 297.4ms

Speed: 1.3ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuuEHCLDkMU9lYw5kZVxnA_270.JPG: 480x640 (no detections), 305.7ms
Speed: 1.1ms preprocess, 305.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuw2lbEJa6klevYGFkPeaw_0.JPG: 480x640 (no detections), 298.4ms
Speed: 1.3ms preprocess, 298.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuw2lbEJa6klevYGFkPeaw_90.JPG: 480x640 (no detections), 295.2ms
Speed: 1.3ms preprocess, 295.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuw2lbEJa6klevYGFkPeaw_180.JPG: 480x640 (no detections), 293.5ms
Speed: 1.1ms preprocess, 293.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuw2lbEJa6klevYGFkPeaw_270.JPG: 480x640 1 Waste, 299.8ms
Speed: 1.2ms preprocess, 299.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuxMVWaDbxRzU0zrwvFuGA_0.JPG: 480x640 (no detections), 297.9ms
Speed: 1.3ms preprocess, 297.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuxMVWaDbxRzU0zrwvFuGA_90.JPG: 480x640 1 Waste, 291.6ms
Speed: 1.2ms preprocess, 291.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuxMVWaDbxRzU0zrwvFuGA_180.JPG: 480x640 (no detections), 296.9ms
Speed: 1.0ms preprocess, 296.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/U/xuxMVWaDbxRzU0zrwvFuGA_270.JPG: 480x640 (no detections), 291.6ms
Speed: 1.1ms preprocess, 291.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xv-0g-rrk_mEEzOrMh3Azg_0.JPG: 480x640 (no detections), 303.4ms
Speed: 1.1ms preprocess, 303.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xv-0g-rrk_mEEzOrMh3Azg_90.JPG: 480x640 (no detections), 298.5ms
Speed: 1.2ms preprocess, 298.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xv-0g-rrk_mEEzOrMh3Azg_180.JPG: 480x640 (no detections), 299.8ms
Speed: 1.2ms preprocess, 299.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xv-0g-rrk_mEEzOrMh3Azg_270.JPG: 480x640 (no detections), 297.1ms
Speed: 1.3ms preprocess, 297.1ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xv3k60MySTGn3mASzZGnww_0.JPG: 480x640 (no detections), 299.5ms
Speed: 1.0ms preprocess, 299.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xv3k60MySTGn3mASzZGnww_90.JPG: 480x640 (no detections), 297.2ms
Speed: 2.0ms preprocess, 297.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xv3k60MySTGn3mASzZGnww_180.JPG: 480x640 (no detections), 295.8ms
Speed: 1.1ms preprocess, 295.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xv3k60MySTGn3mASzZGnww_270.JPG: 480x640 (no detections), 293.9ms
Speed: 1.1ms preprocess, 293.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xv4H2RWW15aJR3xVwKVqvQ_0.JPG: 480x640 (no detections), 292.0ms
Speed: 1.1ms preprocess, 292.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xv4H2RWW15aJR3xVwKVqvQ_90.JPG: 480x640 (no detections), 293.8ms
Speed: 1.1ms preprocess, 293.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xv4H2RWW15aJR3xVwKVqvQ_180.JPG: 480x640 (no detections), 295.1ms
Speed: 1.0ms preprocess, 295.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xv4H2RWW15aJR3xVwKVqvQ_270.JPG: 480x640 (no detections), 297.6ms
Speed: 1.1ms preprocess, 297.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xv5p7DJtuEM0Ok8Tf3RNOw_0.JPG: 480x640 (no detections), 292.0ms
Speed: 1.1ms preprocess, 292.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xv5p7DJtuEM0Ok8Tf3RNOw_90.JPG: 480x640 (no detections), 299.1ms
Speed: 2.0ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xv5p7DJtuEM0Ok8Tf3RNOw_180.JPG: 480x640 (no detections), 293.6ms
Speed: 1.2ms preprocess, 293.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xv5p7DJtuEM0Ok8Tf3RNOw_270.JPG: 480x640 (no detections), 299.2ms
Speed: 1.1ms preprocess, 299.2ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvFIPYCWbnTBMS6C4PtOmA_0.JPG: 480x640 (no detections), 294.7ms
Speed: 1.1ms preprocess, 294.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvFIPYCWbnTBMS6C4PtOmA_90.JPG: 480x640 (no detections), 299.1ms
Speed: 1.6ms preprocess, 299.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvFIPYCWbnTBMS6C4PtOmA_180.JPG: 480x640 (no detections), 297.3ms
Speed: 1.4ms preprocess, 297.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvFIPYCWbnTBMS6C4PtOmA_270.JPG: 480x640 (no detections), 295.5ms
Speed: 1.2ms preprocess, 295.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvIkVLkznuFHOTfAzW6E4A_0.JPG: 480x640 (no detections), 300.6ms
Speed: 1.1ms preprocess, 300.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvIkVLkznuFHOTfAzW6E4A_90.JPG: 480x640 (no detections), 295.6ms
Speed: 1.3ms preprocess, 295.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvIkVLkznuFHOTfAzW6E4A_180.JPG: 480x640 (no detections), 299.4ms
Speed: 1.6ms preprocess, 299.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvIkVLkznuFHOTfAzW6E4A_270.JPG: 480x640 (no detections), 298.8ms
Speed: 1.4ms preprocess, 298.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvKysQXHBzk3YfNBe7ljWQ_0.JPG: 480x640 (no detections), 289.9ms
Speed: 1.1ms preprocess, 289.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvKysQXHBzk3YfNBe7ljWQ_90.JPG: 480x640 (no detections), 298.5ms
Speed: 1.1ms preprocess, 298.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvKysQXHBzk3YfNBe7ljWQ_180.JPG: 480x640 (no detections), 298.9ms
Speed: 1.7ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvKysQXHBzk3YfNBe7ljWQ_270.JPG: 480x640 (no detections), 292.8ms
Speed: 1.1ms preprocess, 292.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvMV6NZRnXj3GQ_dFN7NOA_0.JPG: 480x640 (no detections), 294.4ms
Speed: 1.4ms preprocess, 294.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvMV6NZRnXj3GQ_dFN7NOA_90.JPG: 480x640 (no detections), 295.2ms
Speed: 1.2ms preprocess, 295.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvMV6NZRnXj3GQ_dFN7NOA_180.JPG: 480x640 (no detections), 294.9ms
Speed: 1.2ms preprocess, 294.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvMV6NZRnXj3GQ_dFN7NOA_270.JPG: 480x640 (no detections), 297.8ms
Speed: 1.5ms preprocess, 297.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvMjx6eK1TWVr9bWx0sqPg_0.JPG: 480x640 (no detections), 297.5ms
Speed: 1.2ms preprocess, 297.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvMjx6eK1TWVr9bWx0sqPg_90.JPG: 480x640 (no detections), 294.2ms
Speed: 1.0ms preprocess, 294.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvMjx6eK1TWVr9bWx0sqPg_180.JPG: 480x640 (no detections), 301.0ms
Speed: 1.1ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvMjx6eK1TWVr9bWx0sqPg_270.JPG: 480x640 (no detections), 296.9ms
Speed: 1.3ms preprocess, 296.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvO6ksqpsI42mx9OUTA3YA_0.JPG: 480x640 (no detections), 295.8ms
Speed: 1.3ms preprocess, 295.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvO6ksqpsI42mx9OUTA3YA_90.JPG: 480x640 (no detections), 295.4ms
Speed: 1.1ms preprocess, 295.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvO6ksqpsI42mx9OUTA3YA_180.JPG: 480x640 (no detections), 294.0ms
Speed: 1.0ms preprocess, 294.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvO6ksqpsI42mx9OUTA3YA_270.JPG: 480x640 (no detections), 297.9ms
Speed: 1.2ms preprocess, 297.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvRhJHY3Oru9yZcS7AjU9Q_0.JPG: 480x640 (no detections), 297.6ms
Speed: 1.4ms preprocess, 297.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvRhJHY3Oru9yZcS7AjU9Q_90.JPG: 480x640 (no detections), 296.5ms
Speed: 1.2ms preprocess, 296.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvRhJHY3Oru9yZcS7AjU9Q_180.JPG: 480x640 (no detections), 296.1ms
Speed: 1.3ms preprocess, 296.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvRhJHY3Oru9yZcS7AjU9Q_270.JPG: 480x640 (no detections), 299.1ms
Speed: 1.5ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvSV7WwsRErj0kvxNfojTQ_0.JPG: 480x640 (no detections), 297.2ms
Speed: 1.2ms preprocess, 297.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvSV7WwsRErj0kvxNfojTQ_90.JPG: 480x640 (no detections), 294.3ms
Speed: 1.0ms preprocess, 294.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvSV7WwsRErj0kvxNfojTQ_180.JPG: 480x640 (no detections), 299.4ms
Speed: 1.1ms preprocess, 299.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvSV7WwsRErj0kvxNfojTQ_270.JPG: 480x640 (no detections), 294.0ms
Speed: 1.7ms preprocess, 294.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvVt1UlenWv-vzV7tgsnkQ_0.JPG: 480x640 (no detections), 297.8ms
Speed: 1.1ms preprocess, 297.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvVt1UlenWv-vzV7tgsnkQ_90.JPG: 480x640 (no detections), 292.3ms
Speed: 1.4ms preprocess, 292.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvVt1UlenWv-vzV7tgsnkQ_180.JPG: 480x640 (no detections), 292.1ms
Speed: 1.2ms preprocess, 292.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvVt1UlenWv-vzV7tgsnkQ_270.JPG: 480x640 (no detections), 294.3ms
Speed: 1.1ms preprocess, 294.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvYVN-yMTc6K82wVowNxzA_0.JPG: 480x640 (no detections), 297.8ms
Speed: 1.2ms preprocess, 297.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvYVN-yMTc6K82wVowNxzA_90.JPG: 480x640 (no detections), 305.0ms
Speed: 1.1ms preprocess, 305.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvYVN-yMTc6K82wVowNxzA_180.JPG: 480x640 (no detections), 292.6ms
Speed: 1.0ms preprocess, 292.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvYVN-yMTc6K82wVowNxzA_270.JPG: 480x640 (no detections), 294.9ms
Speed: 1.1ms preprocess, 294.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvcs1EGoML6s39xrWnLEzA_0.JPG: 480x640 (no detections), 298.0ms
Speed: 1.2ms preprocess, 298.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvcs1EGoML6s39xrWnLEzA_90.JPG: 480x640 (no detections), 301.3ms

Speed: 1.4ms preprocess, 301.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvcs1EGoML6s39xrWnLEzA_180.JPG: 480x640 (no detections), 302.5ms
Speed: 1.3ms preprocess, 302.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvcs1EGoML6s39xrWnLEzA_270.JPG: 480x640 (no detections), 293.9ms
Speed: 1.2ms preprocess, 293.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvdv93s_r1u7fmIitJ_6dQ_0.JPG: 480x640 (no detections), 295.1ms
Speed: 1.1ms preprocess, 295.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvdv93s_r1u7fmIitJ_6dQ_90.JPG: 480x640 (no detections), 297.9ms
Speed: 1.0ms preprocess, 297.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvdv93s_r1u7fmIitJ_6dQ_180.JPG: 480x640 (no detections), 292.8ms
Speed: 1.0ms preprocess, 292.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvdv93s_r1u7fmIitJ_6dQ_270.JPG: 480x640 (no detections), 295.3ms
Speed: 1.3ms preprocess, 295.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xve7L0FGkuPWRiP26Meqlw_0.JPG: 480x640 (no detections), 296.6ms
Speed: 1.2ms preprocess, 296.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xve7L0FGkuPWRiP26Meqlw_90.JPG: 480x640 (no detections), 297.7ms
Speed: 1.3ms preprocess, 297.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xve7L0FGkuPWRiP26Meqlw_180.JPG: 480x640 (no detections), 294.4ms
Speed: 1.3ms preprocess, 294.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xve7L0FGkuPWRiP26Meqlw_270.JPG: 480x640 (no detections), 297.2ms
Speed: 1.2ms preprocess, 297.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvgfetvexGe8df5zkkhN_A_0.JPG: 480x640 (no detections), 300.7ms
Speed: 1.2ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvgfetvexGe8df5zkkhN_A_90.JPG: 480x640 (no detections), 298.4ms
Speed: 1.2ms preprocess, 298.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvgfetvexGe8df5zkkhN_A_180.JPG: 480x640 (no detections), 301.7ms
Speed: 1.3ms preprocess, 301.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvgfetvexGe8df5zkkhN_A_270.JPG: 480x640 (no detections), 300.4ms
Speed: 1.1ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvi4Ip-PgBqBw88A50-iCA_0.JPG: 480x640 (no detections), 295.6ms
Speed: 1.2ms preprocess, 295.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvi4Ip-PgBqBw88A50-iCA_90.JPG: 480x640 (no detections), 298.8ms
Speed: 1.6ms preprocess, 298.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvi4Ip-PgBqBw88A50-iCA_180.JPG: 480x640 (no detections), 295.7ms
Speed: 1.9ms preprocess, 295.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvi4Ip-PgBqBw88A50-iCA_270.JPG: 480x640 (no detections), 295.3ms
Speed: 1.4ms preprocess, 295.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvj49A9jIZdaqqioiWxaHQ_0.JPG: 480x640 (no detections), 301.4ms
Speed: 1.2ms preprocess, 301.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvj49A9jIZdaqqioiWxaHQ_90.JPG: 480x640 (no detections), 294.7ms
Speed: 1.1ms preprocess, 294.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvj49A9jIZdaqqioiWxaHQ_180.JPG: 480x640 (no detections), 292.5ms
Speed: 1.0ms preprocess, 292.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvj49A9jIZdaqqioiWxaHQ_270.JPG: 480x640 (no detections), 296.0ms
Speed: 1.2ms preprocess, 296.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvk67j4_Au82QzyJCZAkvQ_0.JPG: 480x640 (no detections), 295.8ms
Speed: 1.5ms preprocess, 295.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvk67j4_Au82QzyJCZAkvQ_90.JPG: 480x640 (no detections), 300.2ms
Speed: 1.2ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvk67j4_Au82QzyJCZAkvQ_180.JPG: 480x640 (no detections), 292.4ms
Speed: 1.2ms preprocess, 292.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvk67j4_Au82QzyJCZAkvQ_270.JPG: 480x640 (no detections), 299.1ms
Speed: 1.1ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvn0E0g4eKn8nkiRuwtXaw_0.JPG: 480x640 (no detections), 298.0ms
Speed: 1.1ms preprocess, 298.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvn0E0g4eKn8nkiRuwtXaw_90.JPG: 480x640 (no detections), 293.2ms
Speed: 1.0ms preprocess, 293.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvn0E0g4eKn8nkiRuwtXaw_180.JPG: 480x640 1 Waste, 301.9ms
Speed: 1.2ms preprocess, 301.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvn0E0g4eKn8nkiRuwtXaw_270.JPG: 480x640 (no detections), 296.9ms
Speed: 1.1ms preprocess, 296.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvn8YpTsMCjdsr3uefbcBA_0.JPG: 480x640 (no detections), 296.3ms
Speed: 1.2ms preprocess, 296.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvn8YpTsMCjdsr3uefbcBA_90.JPG: 480x640 (no detections), 298.4ms
Speed: 1.0ms preprocess, 298.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvn8YpTsMCjdsr3uefbcBA_180.JPG: 480x640 (no detections), 298.8ms
Speed: 1.1ms preprocess, 298.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvn8YpTsMCjdsr3uefbcBA_270.JPG: 480x640 (no detections), 292.7ms
Speed: 1.1ms preprocess, 292.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvrC_wzOuimyuJKHcrVk5A_0.JPG: 480x640 (no detections), 297.0ms
Speed: 1.0ms preprocess, 297.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvrC_wzOuimyuJKHcrVk5A_90.JPG: 480x640 (no detections), 300.6ms
Speed: 1.7ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvrC_wzOuimyuJKHcrVk5A_180.JPG: 480x640 (no detections), 295.5ms
Speed: 1.3ms preprocess, 295.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvrC_wzOuimyuJKHcrVk5A_270.JPG: 480x640 (no detections), 291.4ms
Speed: 1.1ms preprocess, 291.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvrUe8y_1HrT_TUT4AWwqw_0.JPG: 480x640 (no detections), 296.6ms
Speed: 1.3ms preprocess, 296.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvrUe8y_1HrT_TUT4AWwqw_90.JPG: 480x640 (no detections), 298.9ms
Speed: 1.3ms preprocess, 298.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvrUe8y_1HrT_TUT4AWwqw_180.JPG: 480x640 (no detections), 297.4ms
Speed: 1.4ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvrUe8y_1HrT_TUT4AWwqw_270.JPG: 480x640 (no detections), 289.1ms
Speed: 1.1ms preprocess, 289.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvrjhuMwZIhdxmglutQFjA_0.JPG: 480x640 (no detections), 294.9ms
Speed: 1.1ms preprocess, 294.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvrjhuMwZIhdxmglutQFjA_90.JPG: 480x640 (no detections), 297.4ms
Speed: 1.3ms preprocess, 297.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvrjhuMwZIhdxmglutQFjA_180.JPG: 480x640 (no detections), 295.6ms
Speed: 1.2ms preprocess, 295.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvrjhuMwZIhdxmglutQFjA_270.JPG: 480x640 (no detections), 295.7ms
Speed: 1.4ms preprocess, 295.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvv4fuAGZamMmCRkHLlhog_0.JPG: 480x640 1 Waste, 294.4ms
Speed: 1.2ms preprocess, 294.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvv4fuAGZamMmCRkHLlhog_90.JPG: 480x640 (no detections), 299.1ms
Speed: 1.1ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvv4fuAGZamMmCRkHLlhog_180.JPG: 480x640 (no detections), 295.0ms
Speed: 1.2ms preprocess, 295.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvv4fuAGZamMmCRkHLlhog_270.JPG: 480x640 (no detections), 295.0ms
Speed: 1.3ms preprocess, 295.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvvbb88-UeGVL9_YVkXBdg_0.JPG: 480x640 (no detections), 296.4ms
Speed: 1.1ms preprocess, 296.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvvbb88-UeGVL9_YVkXBdg_90.JPG: 480x640 (no detections), 295.0ms
Speed: 1.1ms preprocess, 295.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvvbb88-UeGVL9_YVkXBdg_180.JPG: 480x640 (no detections), 290.7ms
Speed: 1.1ms preprocess, 290.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/v/xvvbb88-UeGVL9_YVkXBdg_270.JPG: 480x640 (no detections), 300.2ms
Speed: 1.4ms preprocess, 300.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xw-fOaIiJ0E49gWfSvrEuQ_0.JPG: 480x640 (no detections), 291.3ms
Speed: 1.1ms preprocess, 291.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xw-fOaIiJ0E49gWfSvrEuQ_90.JPG: 480x640 (no detections), 294.6ms
Speed: 1.1ms preprocess, 294.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xw-fOaIiJ0E49gWfSvrEuQ_180.JPG: 480x640 (no detections), 295.6ms
Speed: 1.3ms preprocess, 295.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xw-fOaIiJ0E49gWfSvrEuQ_270.JPG: 480x640 (no detections), 295.4ms
Speed: 1.3ms preprocess, 295.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xw1jmRayQDXKMSNxVWriPw_0.JPG: 480x640 (no detections), 292.5ms
Speed: 1.0ms preprocess, 292.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xw1jmRayQDXKMSNxVWriPw_90.JPG: 480x640 (no detections), 293.6ms
Speed: 1.3ms preprocess, 293.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xw1jmRayQDXKMSNxVWriPw_180.JPG: 480x640 (no detections), 295.9ms
Speed: 1.2ms preprocess, 295.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xw1jmRayQDXKMSNxVWriPw_270.JPG: 480x640 (no detections), 296.3ms
Speed: 1.8ms preprocess, 296.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xw2E0GUiZPGrAbBuc9x5WA_0.JPG: 480x640 (no detections), 292.9ms
Speed: 1.1ms preprocess, 292.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xw2E0GUiZPGrAbBuc9x5WA_90.JPG: 480x640 (no detections), 294.3ms
Speed: 1.1ms preprocess, 294.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xw2E0GUiZPGrAbBuc9x5WA_180.JPG: 480x640 (no detections), 300.1ms
Speed: 1.1ms preprocess, 300.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xw2E0GUiZPGrAbBuc9x5WA_270.JPG: 480x640 (no detections), 299.7ms
Speed: 1.3ms preprocess, 299.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xw4ETkSaTWzzpxSNqzAhmw_0.JPG: 480x640 (no detections), 298.5ms

Speed: 1.1ms preprocess, 298.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xw4ETkSaTWzzpxSNqzAhmw_90.JPG: 480x640 1 Waste, 289.8ms
Speed: 1.1ms preprocess, 289.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xw4ETkSaTWzzpxSNqzAhmw_180.JPG: 480x640 1 Waste, 293.8ms
Speed: 1.0ms preprocess, 293.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xw4ETkSaTWzzpxSNqzAhmw_270.JPG: 480x640 (no detections), 298.6ms
Speed: 1.0ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xw4XCUAbzvA-0ZivRKZhKg_0.JPG: 480x640 (no detections), 295.0ms
Speed: 1.3ms preprocess, 295.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xw4XCUAbzvA-0ZivRKZhKg_90.JPG: 480x640 (no detections), 296.3ms
Speed: 1.2ms preprocess, 296.3ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xw4XCUAbzvA-0ZivRKZhKg_180.JPG: 480x640 (no detections), 292.2ms
Speed: 1.1ms preprocess, 292.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xw4XCUAbzvA-0ZivRKZhKg_270.JPG: 480x640 (no detections), 292.8ms
Speed: 1.1ms preprocess, 292.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xw5WwhZbuAkCqO16ik8_dQ_0.JPG: 480x640 (no detections), 295.3ms
Speed: 1.1ms preprocess, 295.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xw5WwhZbuAkCqO16ik8_dQ_90.JPG: 480x640 (no detections), 298.7ms
Speed: 1.2ms preprocess, 298.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xw5WwhZbuAkCqO16ik8_dQ_180.JPG: 480x640 (no detections), 298.2ms
Speed: 1.2ms preprocess, 298.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xw5WwhZbuAkCqO16ik8_dQ_270.JPG: 480x640 (no detections), 292.9ms
Speed: 1.1ms preprocess, 292.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwBpmQyx-xOy1BUl2-V9Bw_0.JPG: 480x640 (no detections), 294.5ms
Speed: 1.1ms preprocess, 294.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwBpmQyx-xOy1BUl2-V9Bw_90.JPG: 480x640 (no detections), 306.8ms
Speed: 1.1ms preprocess, 306.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwBpmQyx-xOy1BUl2-V9Bw_180.JPG: 480x640 (no detections), 304.1ms
Speed: 1.1ms preprocess, 304.1ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwBpmQyx-xOy1BUl2-V9Bw_270.JPG: 480x640 (no detections), 303.1ms
Speed: 1.4ms preprocess, 303.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwEG8ziXwRJ4WJSCiwdceg_0.JPG: 480x640 (no detections), 305.6ms
Speed: 1.1ms preprocess, 305.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwEG8ziXwRJ4WJSCiwdceg_90.JPG: 480x640 (no detections), 302.1ms
Speed: 1.2ms preprocess, 302.1ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwEG8ziXwRJ4WJSCiwdceg_180.JPG: 480x640 (no detections), 299.7ms
Speed: 1.3ms preprocess, 299.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwEG8ziXwRJ4WJSCiwdceg_270.JPG: 480x640 (no detections), 300.1ms
Speed: 1.2ms preprocess, 300.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwEPB3pUDsLDOcBj2SCY_w_0.JPG: 480x640 (no detections), 297.3ms
Speed: 1.2ms preprocess, 297.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwEPB3pUDsLDOcBj2SCY_w_90.JPG: 480x640 (no detections), 300.8ms
Speed: 1.3ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwEPB3pUDsLDOcBj2SCY_w_180.JPG: 480x640 (no detections), 304.3ms
Speed: 1.6ms preprocess, 304.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwEPB3pUDsLDOcBj2SCY_w_270.JPG: 480x640 (no detections), 302.7ms
Speed: 1.1ms preprocess, 302.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwG101jgWOGBOHavz6YPTQ_0.JPG: 480x640 (no detections), 299.8ms
Speed: 1.3ms preprocess, 299.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwG101jgWOGBOHavz6YPTQ_90.JPG: 480x640 (no detections), 297.4ms
Speed: 1.2ms preprocess, 297.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwG101jgWOGBOHavz6YPTQ_180.JPG: 480x640 (no detections), 299.7ms
Speed: 1.1ms preprocess, 299.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwG101jgWOGBOHavz6YPTQ_270.JPG: 480x640 (no detections), 297.2ms
Speed: 1.1ms preprocess, 297.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwHLmqhy7HDu4KwZJhi-vw_0.JPG: 480x640 (no detections), 303.6ms
Speed: 1.3ms preprocess, 303.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwHLmqhy7HDu4KwZJhi-vw_90.JPG: 480x640 (no detections), 298.2ms
Speed: 1.7ms preprocess, 298.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwHLmqhy7HDu4KwZJhi-vw_180.JPG: 480x640 (no detections), 300.8ms
Speed: 1.8ms preprocess, 300.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwHLmqhy7HDu4KwZJhi-vw_270.JPG: 480x640 (no detections), 301.2ms
Speed: 1.1ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwHWceOLxDV2B5BWLn3_3Q_0.JPG: 480x640 (no detections), 297.1ms
Speed: 1.3ms preprocess, 297.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwHWceOLxDV2B5BWLn3_3Q_90.JPG: 480x640 (no detections), 297.6ms
Speed: 1.2ms preprocess, 297.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwHWceOLxDV2B5BWLn3_3Q_180.JPG: 480x640 (no detections), 298.4ms
Speed: 1.3ms preprocess, 298.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwHWceOLxDV2B5BWLn3_3Q_270.JPG: 480x640 (no detections), 298.1ms
Speed: 1.3ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwHjxHr6PNwZSJysEe6xNw_0.JPG: 480x640 (no detections), 297.5ms
Speed: 1.2ms preprocess, 297.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwHjxHr6PNwZSJysEe6xNw_90.JPG: 480x640 (no detections), 306.5ms
Speed: 1.3ms preprocess, 306.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwHjxHr6PNwZSJysEe6xNw_180.JPG: 480x640 (no detections), 296.4ms
Speed: 1.3ms preprocess, 296.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwHjxHr6PNwZSJysEe6xNw_270.JPG: 480x640 (no detections), 299.8ms
Speed: 1.1ms preprocess, 299.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwJlEKVK_ee_t3Fpdc-ziw_0.JPG: 480x640 (no detections), 302.6ms
Speed: 1.1ms preprocess, 302.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwJlEKVK_ee_t3Fpdc-ziw_90.JPG: 480x640 (no detections), 301.1ms
Speed: 1.2ms preprocess, 301.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwJlEKVK_ee_t3Fpdc-ziw_180.JPG: 480x640 (no detections), 302.3ms
Speed: 1.1ms preprocess, 302.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwJlEKVK_ee_t3Fpdc-ziw_270.JPG: 480x640 (no detections), 299.3ms
Speed: 1.1ms preprocess, 299.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwLbugPQMKwvCZpbALNKkg_0.JPG: 480x640 (no detections), 298.3ms
Speed: 1.1ms preprocess, 298.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwLbugPQMKwvCZpbALNKkg_90.JPG: 480x640 (no detections), 297.4ms
Speed: 1.1ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwLbugPQMKwvCZpbALNKkg_180.JPG: 480x640 (no detections), 300.7ms
Speed: 1.2ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwLbugPQMKwvCZpbALNKkg_270.JPG: 480x640 (no detections), 299.6ms
Speed: 1.2ms preprocess, 299.6ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwMnxyO53smc7t_H5RWvJw_0.JPG: 480x640 (no detections), 302.3ms
Speed: 1.4ms preprocess, 302.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwMnxyO53smc7t_H5RWvJw_90.JPG: 480x640 (no detections), 299.4ms
Speed: 1.1ms preprocess, 299.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwMnxyO53smc7t_H5RWvJw_180.JPG: 480x640 (no detections), 299.6ms
Speed: 1.7ms preprocess, 299.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwMnxyO53smc7t_H5RWvJw_270.JPG: 480x640 (no detections), 299.8ms
Speed: 1.2ms preprocess, 299.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwPV9bBM1k2PBzMyubaW9Q_0.JPG: 480x640 (no detections), 304.8ms
Speed: 1.2ms preprocess, 304.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwPV9bBM1k2PBzMyubaW9Q_90.JPG: 480x640 (no detections), 303.2ms
Speed: 1.2ms preprocess, 303.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwPV9bBM1k2PBzMyubaW9Q_180.JPG: 480x640 (no detections), 304.8ms
Speed: 1.1ms preprocess, 304.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwPV9bBM1k2PBzMyubaW9Q_270.JPG: 480x640 (no detections), 300.3ms
Speed: 1.2ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwPWoNiYzaZby9xW1SeFHA_0.JPG: 480x640 (no detections), 301.5ms
Speed: 1.2ms preprocess, 301.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwPWoNiYzaZby9xW1SeFHA_90.JPG: 480x640 (no detections), 295.6ms
Speed: 1.1ms preprocess, 295.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwPWoNiYzaZby9xW1SeFHA_180.JPG: 480x640 (no detections), 297.0ms
Speed: 1.4ms preprocess, 297.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwPWoNiYzaZby9xW1SeFHA_270.JPG: 480x640 (no detections), 299.1ms
Speed: 1.1ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwQq1gjSZ1kPsED0R3FYrw_0.JPG: 480x640 (no detections), 296.3ms
Speed: 1.1ms preprocess, 296.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwQq1gjSZ1kPsED0R3FYrw_90.JPG: 480x640 (no detections), 296.9ms
Speed: 1.3ms preprocess, 296.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwQq1gjSZ1kPsED0R3FYrw_180.JPG: 480x640 (no detections), 307.6ms
Speed: 1.1ms preprocess, 307.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwQq1gjSZ1kPsED0R3FYrw_270.JPG: 480x640 (no detections), 298.7ms
Speed: 1.2ms preprocess, 298.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwR7_a8zgzBJARSKJx2yyA_0.JPG: 480x640 (no detections), 294.8ms
Speed: 1.1ms preprocess, 294.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwR7_a8zgzBJARSKJx2yyA_90.JPG: 480x640 (no detections), 287.4ms
Speed: 1.2ms preprocess, 287.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwR7_a8zgzBJARSKJx2yyA_180.JPG: 480x640 (no detections), 298.4ms
Speed: 1.0ms preprocess, 298.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwR7_a8zgzBJARSKJx2yyA_270.JPG: 480x640 (no detections), 299.3ms

Speed: 1.1ms preprocess, 299.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwRoAHX4kamNK-yrx6N4nQ_0.JPG: 480x640 (no detections), 298.4ms
Speed: 1.2ms preprocess, 298.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwRoAHX4kamNK-yrx6N4nQ_90.JPG: 480x640 (no detections), 301.8ms
Speed: 1.2ms preprocess, 301.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwRoAHX4kamNK-yrx6N4nQ_180.JPG: 480x640 (no detections), 301.5ms
Speed: 1.1ms preprocess, 301.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwRoAHX4kamNK-yrx6N4nQ_270.JPG: 480x640 1 Waste, 300.5ms
Speed: 1.2ms preprocess, 300.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwSrDQGQyS4ZYmjqoOBZ8A_0.JPG: 480x640 (no detections), 301.3ms
Speed: 1.1ms preprocess, 301.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwSrDQGQyS4ZYmjqoOBZ8A_90.JPG: 480x640 (no detections), 299.8ms
Speed: 1.3ms preprocess, 299.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwSrDQGQyS4ZYmjqoOBZ8A_180.JPG: 480x640 (no detections), 301.7ms
Speed: 1.2ms preprocess, 301.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwSrDQGQyS4ZYmjqoOBZ8A_270.JPG: 480x640 (no detections), 301.3ms
Speed: 1.3ms preprocess, 301.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwVhnBq1ngB2Gm5NJNqDrw_0.JPG: 480x640 (no detections), 295.7ms
Speed: 1.4ms preprocess, 295.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwVhnBq1ngB2Gm5NJNqDrw_90.JPG: 480x640 (no detections), 302.1ms
Speed: 1.2ms preprocess, 302.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwVhnBq1ngB2Gm5NJNqDrw_180.JPG: 480x640 (no detections), 302.3ms
Speed: 1.3ms preprocess, 302.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwVhnBq1ngB2Gm5NJNqDrw_270.JPG: 480x640 (no detections), 302.2ms
Speed: 1.3ms preprocess, 302.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwVmVUttPP5e1_qe65FfQA_0.JPG: 480x640 (no detections), 292.5ms
Speed: 1.1ms preprocess, 292.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwVmVUttPP5e1_qe65FfQA_90.JPG: 480x640 (no detections), 296.2ms
Speed: 1.1ms preprocess, 296.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwVmVUttPP5e1_qe65FfQA_180.JPG: 480x640 (no detections), 295.8ms
Speed: 1.1ms preprocess, 295.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwVmVUttPP5e1_qe65FfQA_270.JPG: 480x640 (no detections), 298.0ms
Speed: 1.2ms preprocess, 298.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwXLoZO9UnpP5wEF3pv5Pg_0.JPG: 480x640 (no detections), 297.2ms
Speed: 1.1ms preprocess, 297.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwXLoZO9UnpP5wEF3pv5Pg_90.JPG: 480x640 (no detections), 296.2ms
Speed: 1.2ms preprocess, 296.2ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwXLoZO9UnpP5wEF3pv5Pg_180.JPG: 480x640 (no detections), 301.8ms
Speed: 1.3ms preprocess, 301.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwXLoZO9UnpP5wEF3pv5Pg_270.JPG: 480x640 (no detections), 298.5ms
Speed: 1.5ms preprocess, 298.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwXszVSeis8LwaaKmM28LA_0.JPG: 480x640 (no detections), 301.4ms
Speed: 1.2ms preprocess, 301.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwXszVSeis8LwaaKmM28LA_90.JPG: 480x640 (no detections), 301.0ms
Speed: 1.8ms preprocess, 301.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwXszVSeis8LwaaKmM28LA_180.JPG: 480x640 (no detections), 298.4ms
Speed: 1.9ms preprocess, 298.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwXszVSeis8LwaaKmM28LA_270.JPG: 480x640 (no detections), 298.0ms
Speed: 1.1ms preprocess, 298.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwaIAk1duSwsWS6XIXAskg_0.JPG: 480x640 (no detections), 302.8ms
Speed: 1.3ms preprocess, 302.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwaIAk1duSwsWS6XIXAskg_90.JPG: 480x640 (no detections), 296.2ms
Speed: 1.8ms preprocess, 296.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwaIAk1duSwsWS6XIXAskg_180.JPG: 480x640 (no detections), 299.3ms
Speed: 1.2ms preprocess, 299.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwaIAk1duSwsWS6XIXAskg_270.JPG: 480x640 (no detections), 297.9ms
Speed: 1.7ms preprocess, 297.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwbMm8nwtfhpp-WVB4wxaw_0.JPG: 480x640 (no detections), 299.8ms
Speed: 2.0ms preprocess, 299.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwbMm8nwtfhpp-WVB4wxaw_90.JPG: 480x640 (no detections), 304.1ms
Speed: 1.1ms preprocess, 304.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwbMm8nwtfhpp-WVB4wxaw_180.JPG: 480x640 (no detections), 295.6ms
Speed: 1.4ms preprocess, 295.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwbMm8nwtfhpp-WVB4wxaw_270.JPG: 480x640 (no detections), 298.9ms
Speed: 1.2ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwc7nDV1kwW0QXjl782yXg_0.JPG: 480x640 (no detections), 303.4ms
Speed: 1.0ms preprocess, 303.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwc7nDV1kwW0QXjl782yXg_90.JPG: 480x640 (no detections), 302.1ms
Speed: 1.2ms preprocess, 302.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwc7nDV1kwW0QXjl782yXg_180.JPG: 480x640 (no detections), 298.6ms
Speed: 1.4ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwc7nDV1kwW0QXjl782yXg_270.JPG: 480x640 (no detections), 297.6ms
Speed: 1.3ms preprocess, 297.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwcM2HcoVMt1lYuBEUF7IQ_0.JPG: 480x640 (no detections), 299.2ms
Speed: 1.3ms preprocess, 299.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwcM2HcoVMt1lYuBEUF7IQ_90.JPG: 480x640 (no detections), 297.0ms
Speed: 1.4ms preprocess, 297.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwcM2HcoVMt1lYuBEUF7IQ_180.JPG: 480x640 (no detections), 301.9ms
Speed: 1.1ms preprocess, 301.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwcM2HcoVMt1lYuBEUF7IQ_270.JPG: 480x640 (no detections), 302.0ms
Speed: 1.2ms preprocess, 302.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwcrRVFQHgwVzOAJOQgbEw_0.JPG: 480x640 (no detections), 298.1ms
Speed: 1.2ms preprocess, 298.1ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwcrRVFQHgwVzOAJOQgbEw_90.JPG: 480x640 (no detections), 301.7ms
Speed: 1.1ms preprocess, 301.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwcrRVFQHgwVzOAJOQgbEw_180.JPG: 480x640 (no detections), 299.1ms
Speed: 1.2ms preprocess, 299.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwcrRVFQHgwVzOAJOQgbEw_270.JPG: 480x640 (no detections), 297.9ms
Speed: 1.3ms preprocess, 297.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwdPa7V5qzIehP8DlusheQ_0.JPG: 480x640 (no detections), 304.3ms
Speed: 1.1ms preprocess, 304.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwdPa7V5qzIehP8DlusheQ_90.JPG: 480x640 (no detections), 306.8ms
Speed: 1.6ms preprocess, 306.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwdPa7V5qzIehP8DlusheQ_180.JPG: 480x640 (no detections), 300.9ms
Speed: 1.2ms preprocess, 300.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwdPa7V5qzIehP8DlusheQ_270.JPG: 480x640 (no detections), 298.9ms
Speed: 1.2ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwhxgYVj34DPgUn_9TUZaQ_0.JPG: 480x640 (no detections), 297.9ms
Speed: 1.2ms preprocess, 297.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwhxgYVj34DPgUn_9TUZaQ_90.JPG: 480x640 (no detections), 298.3ms
Speed: 1.1ms preprocess, 298.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwhxgYVj34DPgUn_9TUZaQ_180.JPG: 480x640 (no detections), 296.7ms
Speed: 1.1ms preprocess, 296.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwhxgYVj34DPgUn_9TUZaQ_270.JPG: 480x640 (no detections), 302.3ms
Speed: 1.2ms preprocess, 302.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwj9oZeREFTxkaurLwpNHw_0.JPG: 480x640 (no detections), 301.0ms
Speed: 1.1ms preprocess, 301.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwj9oZeREFTxkaurLwpNHw_90.JPG: 480x640 (no detections), 295.4ms
Speed: 1.2ms preprocess, 295.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwj9oZeREFTxkaurLwpNHw_180.JPG: 480x640 (no detections), 300.3ms
Speed: 1.1ms preprocess, 300.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwj9oZeREFTxkaurLwpNHw_270.JPG: 480x640 (no detections), 299.4ms
Speed: 1.1ms preprocess, 299.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwjvKBfMiE5ySgfiWAYXzA_0.JPG: 480x640 (no detections), 298.2ms
Speed: 1.3ms preprocess, 298.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwjvKBfMiE5ySgfiWAYXzA_90.JPG: 480x640 (no detections), 300.9ms
Speed: 1.2ms preprocess, 300.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwjvKBfMiE5ySgfiWAYXzA_180.JPG: 480x640 (no detections), 299.1ms
Speed: 1.2ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwjvKBfMiE5ySgfiWAYXzA_270.JPG: 480x640 (no detections), 297.8ms
Speed: 1.5ms preprocess, 297.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwjyOyV7DmXbQRRAl5CjMg_0.JPG: 480x640 (no detections), 298.1ms
Speed: 1.2ms preprocess, 298.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwjyOyV7DmXbQRRAl5CjMg_90.JPG: 480x640 (no detections), 301.6ms
Speed: 1.1ms preprocess, 301.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwjyOyV7DmXbQRRAl5CjMg_180.JPG: 480x640 (no detections), 302.6ms
Speed: 1.0ms preprocess, 302.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwjyOyV7DmXbQRRAl5CjMg_270.JPG: 480x640 (no detections), 299.8ms
Speed: 1.5ms preprocess, 299.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwm9eJOkukiriGLlWffCOw_0.JPG: 480x640 (no detections), 301.9ms
Speed: 1.1ms preprocess, 301.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwm9eJOkukiriGLlWffCOw_90.JPG: 480x640 (no detections), 301.3ms
Speed: 1.2ms preprocess, 301.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwm9eJOkukiriGLlWffCOw_180.JPG: 480x640 (no detections), 303.2ms

Speed: 1.4ms preprocess, 303.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwm9eJOkukiriGLlWffCOw_270.JPG: 480x640 (no detections), 293.8ms
Speed: 1.3ms preprocess, 293.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwnXT_ewlAyWpv1oEfN5tw_0.JPG: 480x640 (no detections), 303.9ms
Speed: 1.3ms preprocess, 303.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwnXT_ewlAyWpv1oEfN5tw_90.JPG: 480x640 (no detections), 298.4ms
Speed: 1.5ms preprocess, 298.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwnXT_ewlAyWpv1oEfN5tw_180.JPG: 480x640 (no detections), 302.5ms
Speed: 1.2ms preprocess, 302.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwnXT_ewlAyWpv1oEfN5tw_270.JPG: 480x640 (no detections), 303.2ms
Speed: 1.1ms preprocess, 303.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwoZv7qx21gt2RKODJrc2g_0.JPG: 480x640 (no detections), 302.0ms
Speed: 1.2ms preprocess, 302.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwoZv7qx21gt2RKODJrc2g_90.JPG: 480x640 (no detections), 295.9ms
Speed: 1.0ms preprocess, 295.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwoZv7qx21gt2RKODJrc2g_180.JPG: 480x640 1 Waste, 297.7ms
Speed: 1.2ms preprocess, 297.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwoZv7qx21gt2RKODJrc2g_270.JPG: 480x640 (no detections), 300.0ms
Speed: 1.3ms preprocess, 300.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwuDWpcid-W5HZfuJWKGqA_0.JPG: 480x640 (no detections), 297.1ms
Speed: 1.2ms preprocess, 297.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwuDWpcid-W5HZfuJWKGqA_90.JPG: 480x640 (no detections), 307.7ms
Speed: 1.3ms preprocess, 307.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwuDWpcid-W5HZfuJWKGqA_180.JPG: 480x640 (no detections), 299.8ms
Speed: 1.2ms preprocess, 299.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwuDWpcid-W5HZfuJWKGqA_270.JPG: 480x640 (no detections), 302.6ms
Speed: 1.3ms preprocess, 302.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwuvcPuj4rwaR_27kB5Ciw_0.JPG: 480x640 (no detections), 300.8ms
Speed: 1.1ms preprocess, 300.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwuvcPuj4rwaR_27kB5Ciw_90.JPG: 480x640 (no detections), 301.8ms
Speed: 1.2ms preprocess, 301.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwuvcPuj4rwaR_27kB5Ciw_180.JPG: 480x640 (no detections), 301.9ms
Speed: 1.1ms preprocess, 301.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/w/xwuvcPuj4rwaR_27kB5Ciw_270.JPG: 480x640 (no detections), 298.5ms
Speed: 1.1ms preprocess, 298.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xx-06qpvYaQ7aPtaJseJZA_0.JPG: 480x640 (no detections), 301.1ms
Speed: 1.7ms preprocess, 301.1ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xx-06qpvYaQ7aPtaJseJZA_90.JPG: 480x640 (no detections), 301.4ms
Speed: 1.1ms preprocess, 301.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xx-06qpvYaQ7aPtaJseJZA_180.JPG: 480x640 (no detections), 300.8ms
Speed: 1.2ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xx-06qpvYaQ7aPtaJseJZA_270.JPG: 480x640 (no detections), 297.6ms
Speed: 1.3ms preprocess, 297.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xx0GQBL1dA06fi4EUAZWWg_0.JPG: 480x640 (no detections), 306.7ms
Speed: 1.2ms preprocess, 306.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xx0GQBL1dA06fi4EUAZWWg_90.JPG: 480x640 (no detections), 316.3ms
Speed: 1.3ms preprocess, 316.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xx0GQBL1dA06fi4EUAZWWg_180.JPG: 480x640 (no detections), 320.7ms
Speed: 1.1ms preprocess, 320.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xx0GQBL1dA06fi4EUAZWWg_270.JPG: 480x640 (no detections), 297.3ms
Speed: 1.3ms preprocess, 297.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xx6jT9U-hrBwueBhgScdDg_0.JPG: 480x640 (no detections), 302.2ms
Speed: 1.2ms preprocess, 302.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xx6jT9U-hrBwueBhgScdDg_90.JPG: 480x640 (no detections), 302.0ms
Speed: 1.2ms preprocess, 302.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xx6jT9U-hrBwueBhgScdDg_180.JPG: 480x640 (no detections), 304.2ms
Speed: 1.8ms preprocess, 304.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xx6jT9U-hrBwueBhgScdDg_270.JPG: 480x640 (no detections), 300.5ms
Speed: 1.3ms preprocess, 300.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xx7JNkv0sPRwm2Lmf6RKzA_0.JPG: 480x640 (no detections), 301.4ms
Speed: 1.3ms preprocess, 301.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xx7JNkv0sPRwm2Lmf6RKzA_90.JPG: 480x640 (no detections), 299.9ms
Speed: 1.2ms preprocess, 299.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xx7JNkv0sPRwm2Lmf6RKzA_180.JPG: 480x640 (no detections), 306.7ms
Speed: 1.3ms preprocess, 306.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xx7JNkv0sPRwm2Lmf6RKzA_270.JPG: 480x640 (no detections), 317.0ms
Speed: 1.1ms preprocess, 317.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xx8k6_ecVoqTQsz5nHMwJg_0.JPG: 480x640 (no detections), 305.5ms
Speed: 1.9ms preprocess, 305.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xx8k6_ecVoqTQsz5nHMwJg_90.JPG: 480x640 (no detections), 326.8ms
Speed: 1.1ms preprocess, 326.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xx8k6_ecVoqTQsz5nHMwJg_180.JPG: 480x640 (no detections), 304.1ms
Speed: 1.3ms preprocess, 304.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xx8k6_ecVoqTQsz5nHMwJg_270.JPG: 480x640 (no detections), 306.7ms
Speed: 1.1ms preprocess, 306.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xx9iciqP0L0PSSnSAlo7Ng_0.JPG: 480x640 (no detections), 304.1ms
Speed: 1.2ms preprocess, 304.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xx9iciqP0L0PSSnSAlo7Ng_90.JPG: 480x640 (no detections), 297.4ms
Speed: 1.1ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xx9iciqP0L0PSSnSAlo7Ng_180.JPG: 480x640 (no detections), 297.7ms
Speed: 1.2ms preprocess, 297.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xx9iciqP0L0PSSnSAlo7Ng_270.JPG: 480x640 (no detections), 303.7ms
Speed: 1.2ms preprocess, 303.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxCpUY2Zzovd2W7UZjamwg_0.JPG: 480x640 (no detections), 307.2ms
Speed: 1.2ms preprocess, 307.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxCpUY2Zzovd2W7UZjamwg_90.JPG: 480x640 (no detections), 307.4ms
Speed: 1.1ms preprocess, 307.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxCpUY2Zzovd2W7UZjamwg_180.JPG: 480x640 (no detections), 299.5ms
Speed: 1.1ms preprocess, 299.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxCpUY2Zzovd2W7UZjamwg_270.JPG: 480x640 (no detections), 305.6ms
Speed: 1.2ms preprocess, 305.6ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxFoX1xQRBePOG3gWiQZ1Q_0.JPG: 480x640 (no detections), 304.7ms
Speed: 1.1ms preprocess, 304.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxFoX1xQRBePOG3gWiQZ1Q_90.JPG: 480x640 (no detections), 314.1ms
Speed: 1.3ms preprocess, 314.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxFoX1xQRBePOG3gWiQZ1Q_180.JPG: 480x640 (no detections), 302.1ms
Speed: 1.2ms preprocess, 302.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxFoX1xQRBePOG3gWiQZ1Q_270.JPG: 480x640 (no detections), 299.8ms
Speed: 1.2ms preprocess, 299.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxHu_TU4907kr5bAsLZw0g_0.JPG: 480x640 (no detections), 302.7ms
Speed: 1.1ms preprocess, 302.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxHu_TU4907kr5bAsLZw0g_90.JPG: 480x640 (no detections), 307.0ms
Speed: 1.3ms preprocess, 307.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxHu_TU4907kr5bAsLZw0g_180.JPG: 480x640 (no detections), 300.8ms
Speed: 1.4ms preprocess, 300.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxHu_TU4907kr5bAsLZw0g_270.JPG: 480x640 (no detections), 300.9ms
Speed: 1.4ms preprocess, 300.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxJYi5_35jsO1Hep3OqMAw_0.JPG: 480x640 (no detections), 300.8ms
Speed: 1.1ms preprocess, 300.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxJYi5_35jsO1Hep3OqMAw_90.JPG: 480x640 (no detections), 309.5ms
Speed: 1.2ms preprocess, 309.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxJYi5_35jsO1Hep3OqMAw_180.JPG: 480x640 (no detections), 319.9ms
Speed: 1.1ms preprocess, 319.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxJYi5_35jsO1Hep3OqMAw_270.JPG: 480x640 (no detections), 310.7ms
Speed: 1.1ms preprocess, 310.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxLG2V5dumkaL5of4e6qxQ_0.JPG: 480x640 (no detections), 306.3ms
Speed: 1.2ms preprocess, 306.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxLG2V5dumkaL5of4e6qxQ_90.JPG: 480x640 (no detections), 383.8ms
Speed: 1.1ms preprocess, 383.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxLG2V5dumkaL5of4e6qxQ_180.JPG: 480x640 (no detections), 305.2ms
Speed: 1.7ms preprocess, 305.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxLG2V5dumkaL5of4e6qxQ_270.JPG: 480x640 (no detections), 299.9ms
Speed: 1.1ms preprocess, 299.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxZArKOdgvPFIfopEWXfVA_0.JPG: 480x640 (no detections), 300.6ms
Speed: 1.0ms preprocess, 300.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxZArKOdgvPFIfopEWXfVA_90.JPG: 480x640 (no detections), 308.7ms
Speed: 1.2ms preprocess, 308.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxZArKOdgvPFIfopEWXfVA_180.JPG: 480x640 (no detections), 311.4ms
Speed: 1.2ms preprocess, 311.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxZArKOdgvPFIfopEWXfVA_270.JPG: 480x640 (no detections), 303.0ms
Speed: 1.8ms preprocess, 303.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxZd-utHXRWAOaVGmtrlBg_0.JPG: 480x640 (no detections), 303.5ms
Speed: 1.4ms preprocess, 303.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxZd-utHXRWAOaVGmtrlBg_90.JPG: 480x640 (no detections), 298.8ms

Speed: 1.2ms preprocess, 298.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxZd-utHXRWAOaVGmtrlBg_180.JPG: 480x640 (no detections), 302.0ms
Speed: 1.2ms preprocess, 302.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxZd-utHXRWAOaVGmtrlBg_270.JPG: 480x640 (no detections), 300.8ms
Speed: 1.3ms preprocess, 300.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxcylnj0Lo4hFTOFnVWEbg_0.JPG: 480x640 (no detections), 307.1ms
Speed: 1.3ms preprocess, 307.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxcylnj0Lo4hFTOFnVWEbg_90.JPG: 480x640 (no detections), 299.3ms
Speed: 1.1ms preprocess, 299.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxcylnj0Lo4hFTOFnVWEbg_180.JPG: 480x640 (no detections), 315.4ms
Speed: 1.1ms preprocess, 315.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxcylnj0Lo4hFTOFnVWEbg_270.JPG: 480x640 (no detections), 298.2ms
Speed: 1.1ms preprocess, 298.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxdgH-2r_LNiQQv7pTKwIg_0.JPG: 480x640 (no detections), 298.3ms
Speed: 1.1ms preprocess, 298.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxdgH-2r_LNiQQv7pTKwIg_90.JPG: 480x640 (no detections), 300.4ms
Speed: 1.4ms preprocess, 300.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxdgH-2r_LNiQQv7pTKwIg_180.JPG: 480x640 (no detections), 305.7ms
Speed: 1.1ms preprocess, 305.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxdgH-2r_LNiQQv7pTKwIg_270.JPG: 480x640 (no detections), 300.2ms
Speed: 1.2ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxfDzMmO__DBRl9my1XA1g_0.JPG: 480x640 (no detections), 304.8ms
Speed: 1.1ms preprocess, 304.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxfDzMmO__DBRl9my1XA1g_90.JPG: 480x640 (no detections), 303.3ms
Speed: 1.3ms preprocess, 303.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxfDzMmO__DBRl9my1XA1g_180.JPG: 480x640 (no detections), 304.0ms
Speed: 1.3ms preprocess, 304.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxfDzMmO__DBRl9my1XA1g_270.JPG: 480x640 (no detections), 310.7ms
Speed: 1.1ms preprocess, 310.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxfFAzBWipkloGUMkPwagA_0.JPG: 480x640 (no detections), 301.0ms
Speed: 1.2ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxfFAzBWipkloGUMkPwagA_90.JPG: 480x640 (no detections), 298.0ms
Speed: 1.2ms preprocess, 298.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxfFAzBWipkloGUMkPwagA_180.JPG: 480x640 (no detections), 300.7ms
Speed: 1.1ms preprocess, 300.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxfFAzBWipkloGUMkPwagA_270.JPG: 480x640 (no detections), 298.9ms
Speed: 1.2ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxgsqD3I4_qDaR_ncqEi1Q_0.JPG: 480x640 1 Waste, 301.4ms
Speed: 1.1ms preprocess, 301.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxgsqD3I4_qDaR_ncqEi1Q_90.JPG: 480x640 (no detections), 308.8ms
Speed: 1.5ms preprocess, 308.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxgsqD3I4_qDaR_ncqEi1Q_180.JPG: 480x640 (no detections), 302.4ms
Speed: 1.3ms preprocess, 302.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxgsqD3I4_qDaR_ncqEi1Q_270.JPG: 480x640 (no detections), 301.6ms
Speed: 1.3ms preprocess, 301.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxhQGJLfhpTqE1U9S0J2Eg_0.JPG: 480x640 (no detections), 301.1ms
Speed: 1.3ms preprocess, 301.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxhQGJLfhpTqE1U9S0J2Eg_90.JPG: 480x640 (no detections), 308.2ms
Speed: 1.2ms preprocess, 308.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxhQGJLfhpTqE1U9S0J2Eg_180.JPG: 480x640 (no detections), 300.3ms
Speed: 1.2ms preprocess, 300.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxhQGJLfhpTqE1U9S0J2Eg_270.JPG: 480x640 (no detections), 300.7ms
Speed: 1.2ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxhSvxYkP4-X16SnQ4n2dw_0.JPG: 480x640 (no detections), 299.5ms
Speed: 1.2ms preprocess, 299.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxhSvxYkP4-X16SnQ4n2dw_90.JPG: 480x640 (no detections), 303.6ms
Speed: 1.2ms preprocess, 303.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxhSvxYkP4-X16SnQ4n2dw_180.JPG: 480x640 (no detections), 304.8ms
Speed: 1.1ms preprocess, 304.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxhSvxYkP4-X16SnQ4n2dw_270.JPG: 480x640 (no detections), 298.9ms
Speed: 1.2ms preprocess, 298.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxl4FpcceDsYOXlv8-jhiQ_0.JPG: 480x640 (no detections), 302.4ms
Speed: 1.2ms preprocess, 302.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxl4FpcceDsYOXlv8-jhiQ_90.JPG: 480x640 (no detections), 299.7ms
Speed: 1.1ms preprocess, 299.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxl4FpcceDsYOXlv8-jhiQ_180.JPG: 480x640 (no detections), 303.1ms
Speed: 1.1ms preprocess, 303.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxl4FpcceDsYOXlv8-jhiQ_270.JPG: 480x640 (no detections), 300.4ms
Speed: 1.3ms preprocess, 300.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxlvd8D3tdL-vxdMz_sRYg_0.JPG: 480x640 (no detections), 304.2ms
Speed: 1.1ms preprocess, 304.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxlvd8D3tdL-vxdMz_sRYg_90.JPG: 480x640 (no detections), 298.3ms
Speed: 1.2ms preprocess, 298.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxlvd8D3tdL-vxdMz_sRYg_180.JPG: 480x640 (no detections), 302.4ms
Speed: 1.3ms preprocess, 302.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxlvd8D3tdL-vxdMz_sRYg_270.JPG: 480x640 (no detections), 295.5ms
Speed: 1.1ms preprocess, 295.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxn37IScKgAUhUdonFvi_Q_0.JPG: 480x640 (no detections), 299.9ms
Speed: 1.3ms preprocess, 299.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxn37IScKgAUhUdonFvi_Q_90.JPG: 480x640 (no detections), 300.3ms
Speed: 1.3ms preprocess, 300.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxn37IScKgAUhUdonFvi_Q_180.JPG: 480x640 (no detections), 300.8ms
Speed: 1.2ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxn37IScKgAUhUdonFvi_Q_270.JPG: 480x640 (no detections), 297.9ms
Speed: 2.0ms preprocess, 297.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxnM1aEmg9SxxSGJzBIydQ_0.JPG: 480x640 (no detections), 299.8ms
Speed: 1.3ms preprocess, 299.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxnM1aEmg9SxxSGJzBIydQ_90.JPG: 480x640 (no detections), 298.1ms
Speed: 1.3ms preprocess, 298.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxnM1aEmg9SxxSGJzBIydQ_180.JPG: 480x640 1 Waste, 301.1ms
Speed: 1.1ms preprocess, 301.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxnM1aEmg9SxxSGJzBIydQ_270.JPG: 480x640 (no detections), 298.6ms
Speed: 1.2ms preprocess, 298.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxoSDYv2VgZaDBpLx2Cnzw_0.JPG: 480x640 (no detections), 301.0ms
Speed: 1.1ms preprocess, 301.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxoSDYv2VgZaDBpLx2Cnzw_90.JPG: 480x640 (no detections), 304.9ms
Speed: 1.3ms preprocess, 304.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxoSDYv2VgZaDBpLx2Cnzw_180.JPG: 480x640 1 Waste, 296.2ms
Speed: 1.2ms preprocess, 296.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxoSDYv2VgZaDBpLx2Cnzw_270.JPG: 480x640 (no detections), 298.0ms
Speed: 1.2ms preprocess, 298.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxqiIME5oNwKd1T4iiMIdA_0.JPG: 480x640 (no detections), 298.8ms
Speed: 1.1ms preprocess, 298.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxqiIME5oNwKd1T4iiMIdA_90.JPG: 480x640 (no detections), 301.4ms
Speed: 1.1ms preprocess, 301.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxqiIME5oNwKd1T4iiMIdA_180.JPG: 480x640 (no detections), 305.5ms
Speed: 1.3ms preprocess, 305.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxqiIME5oNwKd1T4iiMIdA_270.JPG: 480x640 (no detections), 301.2ms
Speed: 1.2ms preprocess, 301.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxvGfqH6lax8oBTF0WgwRw_0.JPG: 480x640 (no detections), 305.1ms
Speed: 1.2ms preprocess, 305.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxvGfqH6lax8oBTF0WgwRw_90.JPG: 480x640 1 Waste, 305.1ms
Speed: 1.4ms preprocess, 305.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxvGfqH6lax8oBTF0WgwRw_180.JPG: 480x640 (no detections), 303.5ms
Speed: 1.3ms preprocess, 303.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxvGfqH6lax8oBTF0WgwRw_270.JPG: 480x640 (no detections), 310.1ms
Speed: 1.2ms preprocess, 310.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxvHTKSj5gKJEFk-isWhMw_0.JPG: 480x640 (no detections), 302.0ms
Speed: 1.1ms preprocess, 302.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxvHTKSj5gKJEFk-isWhMw_90.JPG: 480x640 (no detections), 303.4ms
Speed: 1.3ms preprocess, 303.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxvHTKSj5gKJEFk-isWhMw_180.JPG: 480x640 (no detections), 306.3ms
Speed: 1.3ms preprocess, 306.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/x/xxvHTKSj5gKJEFk-isWhMw_270.JPG: 480x640 1 Waste, 295.5ms
Speed: 1.1ms preprocess, 295.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xy1-e1NvFo3eHRCnij-51w_0.JPG: 480x640 (no detections), 298.2ms
Speed: 1.3ms preprocess, 298.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xy1-e1NvFo3eHRCnij-51w_90.JPG: 480x640 (no detections), 300.8ms
Speed: 1.3ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xy1-e1NvFo3eHRCnij-51w_180.JPG: 480x640 (no detections), 302.1ms
Speed: 1.1ms preprocess, 302.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xy1-e1NvFo3eHRCnij-51w_270.JPG: 480x640 (no detections), 299.3ms
Speed: 1.2ms preprocess, 299.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xy2bM0EVOgpj2FxKVslyeQ_0.JPG: 480x640 (no detections), 289.9ms

Speed: 1.2ms preprocess, 289.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xy2bM0EVOgpj2FxKVslyeQ_90.JPG: 480x640 (no detections), 291.8ms
Speed: 1.4ms preprocess, 291.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xy2bM0EVOgpj2FxKVslyeQ_180.JPG: 480x640 (no detections), 293.2ms
Speed: 1.2ms preprocess, 293.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xy2bM0EVOgpj2FxKVslyeQ_270.JPG: 480x640 (no detections), 297.2ms
Speed: 1.5ms preprocess, 297.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xy6W25Bdi0mFlWdCTPJN5Q_0.JPG: 480x640 (no detections), 302.8ms
Speed: 1.3ms preprocess, 302.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xy6W25Bdi0mFlWdCTPJN5Q_90.JPG: 480x640 (no detections), 301.7ms
Speed: 1.2ms preprocess, 301.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xy6W25Bdi0mFlWdCTPJN5Q_180.JPG: 480x640 (no detections), 300.5ms
Speed: 1.1ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xy6W25Bdi0mFlWdCTPJN5Q_270.JPG: 480x640 (no detections), 301.7ms
Speed: 1.1ms preprocess, 301.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xy9aDHi9iKyIcWQK1hsF2g_0.JPG: 480x640 (no detections), 304.9ms
Speed: 1.2ms preprocess, 304.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xy9aDHi9iKyIcWQK1hsF2g_90.JPG: 480x640 (no detections), 295.9ms
Speed: 1.2ms preprocess, 295.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xy9aDHi9iKyIcWQK1hsF2g_180.JPG: 480x640 (no detections), 305.0ms
Speed: 1.3ms preprocess, 305.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xy9aDHi9iKyIcWQK1hsF2g_270.JPG: 480x640 (no detections), 306.0ms
Speed: 1.0ms preprocess, 306.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyGYXduojQCD4kXCn140dA_0.JPG: 480x640 (no detections), 296.9ms
Speed: 1.2ms preprocess, 296.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyGYXduojQCD4kXCn140dA_90.JPG: 480x640 (no detections), 302.9ms
Speed: 1.1ms preprocess, 302.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyGYXduojQCD4kXCn140dA_180.JPG: 480x640 (no detections), 298.7ms
Speed: 1.2ms preprocess, 298.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyGYXduojQCD4kXCn140dA_270.JPG: 480x640 (no detections), 302.1ms
Speed: 1.1ms preprocess, 302.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyIym5k3PnV1XTLv-Uetiw_0.JPG: 480x640 (no detections), 299.9ms
Speed: 1.0ms preprocess, 299.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyIym5k3PnV1XTLv-Uetiw_90.JPG: 480x640 (no detections), 301.3ms
Speed: 1.1ms preprocess, 301.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyIym5k3PnV1XTLv-Uetiw_180.JPG: 480x640 (no detections), 296.6ms
Speed: 1.1ms preprocess, 296.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyIym5k3PnV1XTLv-Uetiw_270.JPG: 480x640 (no detections), 307.5ms
Speed: 1.8ms preprocess, 307.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyJ4aLDqq5ECjvKReopKfw_0.JPG: 480x640 (no detections), 296.7ms
Speed: 1.1ms preprocess, 296.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyJ4aLDqq5ECjvKReopKfw_90.JPG: 480x640 (no detections), 305.5ms
Speed: 1.3ms preprocess, 305.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyJ4aLDqq5ECjvKReopKfw_180.JPG: 480x640 (no detections), 300.4ms
Speed: 1.1ms preprocess, 300.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyJ4aLDqq5ECjvKReopKfw_270.JPG: 480x640 (no detections), 298.8ms
Speed: 1.3ms preprocess, 298.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyMHKAssN9IcDrRl7sc1mw_0.JPG: 480x640 (no detections), 304.1ms
Speed: 1.1ms preprocess, 304.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyMHKAssN9IcDrRl7sc1mw_90.JPG: 480x640 (no detections), 301.2ms
Speed: 1.2ms preprocess, 301.2ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyMHKAssN9IcDrRl7sc1mw_180.JPG: 480x640 (no detections), 300.8ms
Speed: 1.3ms preprocess, 300.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyMHKAssN9IcDrRl7sc1mw_270.JPG: 480x640 (no detections), 299.2ms
Speed: 1.1ms preprocess, 299.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyTOVxdMvJTZtXealL9r8Q_0.JPG: 480x640 (no detections), 303.8ms
Speed: 1.1ms preprocess, 303.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyTOVxdMvJTZtXealL9r8Q_90.JPG: 480x640 (no detections), 304.4ms
Speed: 1.2ms preprocess, 304.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyTOVxdMvJTZtXealL9r8Q_180.JPG: 480x640 (no detections), 298.2ms
Speed: 1.1ms preprocess, 298.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyTOVxdMvJTZtXealL9r8Q_270.JPG: 480x640 (no detections), 296.0ms
Speed: 1.3ms preprocess, 296.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyUK2c3co-7gwBs_1kDSbA_0.JPG: 480x640 (no detections), 298.4ms
Speed: 1.1ms preprocess, 298.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyUK2c3co-7gwBs_1kDSbA_90.JPG: 480x640 (no detections), 297.4ms
Speed: 1.1ms preprocess, 297.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyUK2c3co-7gwBs_1kDSbA_180.JPG: 480x640 (no detections), 306.4ms
Speed: 1.2ms preprocess, 306.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyUK2c3co-7gwBs_1kDSbA_270.JPG: 480x640 (no detections), 303.0ms
Speed: 1.4ms preprocess, 303.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyVT4S-CjpH_nhxT-lDDIQ_0.JPG: 480x640 (no detections), 300.8ms
Speed: 1.5ms preprocess, 300.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyVT4S-CjpH_nhxT-lDDIQ_90.JPG: 480x640 2 Wastes, 300.7ms
Speed: 1.3ms preprocess, 300.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyVT4S-CjpH_nhxT-lDDIQ_180.JPG: 480x640 (no detections), 304.0ms
Speed: 1.1ms preprocess, 304.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyVT4S-CjpH_nhxT-lDDIQ_270.JPG: 480x640 (no detections), 303.4ms
Speed: 1.1ms preprocess, 303.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyX8sGxdBNf3MHA3Z4rzxg_0.JPG: 480x640 (no detections), 302.7ms
Speed: 1.4ms preprocess, 302.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyX8sGxdBNf3MHA3Z4rzxg_90.JPG: 480x640 (no detections), 301.9ms
Speed: 1.3ms preprocess, 301.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyX8sGxdBNf3MHA3Z4rzxg_180.JPG: 480x640 (no detections), 302.4ms
Speed: 1.1ms preprocess, 302.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyX8sGxdBNf3MHA3Z4rzxg_270.JPG: 480x640 (no detections), 303.5ms
Speed: 1.2ms preprocess, 303.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyXIJQxXxuAqnLcesfkL-g_0.JPG: 480x640 (no detections), 299.1ms
Speed: 1.8ms preprocess, 299.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyXIJQxXxuAqnLcesfkL-g_90.JPG: 480x640 (no detections), 297.0ms
Speed: 1.7ms preprocess, 297.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyXIJQxXxuAqnLcesfkL-g_180.JPG: 480x640 (no detections), 298.9ms
Speed: 1.2ms preprocess, 298.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyXIJQxXxuAqnLcesfkL-g_270.JPG: 480x640 (no detections), 304.8ms
Speed: 1.4ms preprocess, 304.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyXyhIi1G1JY6ai0Li46hg_0.JPG: 480x640 (no detections), 299.5ms
Speed: 1.2ms preprocess, 299.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyXyhIi1G1JY6ai0Li46hg_90.JPG: 480x640 (no detections), 300.0ms
Speed: 1.4ms preprocess, 300.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyXyhIi1G1JY6ai0Li46hg_180.JPG: 480x640 (no detections), 302.5ms
Speed: 1.2ms preprocess, 302.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyXyhIi1G1JY6ai0Li46hg_270.JPG: 480x640 (no detections), 298.5ms
Speed: 1.1ms preprocess, 298.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyYJjQUzdNAlH0i-fhOg5g_0.JPG: 480x640 (no detections), 294.8ms
Speed: 1.1ms preprocess, 294.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyYJjQUzdNAlH0i-fhOg5g_90.JPG: 480x640 (no detections), 302.5ms
Speed: 1.5ms preprocess, 302.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyYJjQUzdNAlH0i-fhOg5g_180.JPG: 480x640 (no detections), 297.2ms
Speed: 1.3ms preprocess, 297.2ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyYJjQUzdNAlH0i-fhOg5g_270.JPG: 480x640 (no detections), 296.6ms
Speed: 1.1ms preprocess, 296.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyYu7fUQUSRkTWIsoc_x7w_0.JPG: 480x640 (no detections), 303.3ms
Speed: 1.3ms preprocess, 303.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyYu7fUQUSRkTWIsoc_x7w_90.JPG: 480x640 (no detections), 301.4ms
Speed: 1.2ms preprocess, 301.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyYu7fUQUSRkTWIsoc_x7w_180.JPG: 480x640 (no detections), 301.5ms
Speed: 1.4ms preprocess, 301.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyYu7fUQUSRkTWIsoc_x7w_270.JPG: 480x640 (no detections), 306.0ms
Speed: 1.2ms preprocess, 306.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyZ8BLL86jcSpIULiKvppg_0.JPG: 480x640 (no detections), 302.9ms
Speed: 1.2ms preprocess, 302.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyZ8BLL86jcSpIULiKvppg_90.JPG: 480x640 (no detections), 314.3ms
Speed: 1.7ms preprocess, 314.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyZ8BLL86jcSpIULiKvppg_180.JPG: 480x640 (no detections), 326.9ms
Speed: 1.3ms preprocess, 326.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyZ8BLL86jcSpIULiKvppg_270.JPG: 480x640 (no detections), 304.2ms
Speed: 1.3ms preprocess, 304.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyZS1gdtGiGlrEQrtM8OUA_0.JPG: 480x640 (no detections), 311.7ms
Speed: 1.1ms preprocess, 311.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyZS1gdtGiGlrEQrtM8OUA_90.JPG: 480x640 (no detections), 311.6ms
Speed: 1.0ms preprocess, 311.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyZS1gdtGiGlrEQrtM8OUA_180.JPG: 480x640 (no detections), 317.4ms
Speed: 1.2ms preprocess, 317.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyZS1gdtGiGlrEQrtM8OUA_270.JPG: 480x640 (no detections), 311.5ms

Speed: 1.5ms preprocess, 311.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xybs5NEMcnN0j20p-RBccw_0.JPG: 480x640 (no detections), 308.7ms
Speed: 1.3ms preprocess, 308.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xybs5NEMcnN0j20p-RBccw_90.JPG: 480x640 (no detections), 307.6ms
Speed: 1.1ms preprocess, 307.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xybs5NEMcnN0j20p-RBccw_180.JPG: 480x640 (no detections), 323.1ms
Speed: 1.3ms preprocess, 323.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xybs5NEMcnN0j20p-RBccw_270.JPG: 480x640 (no detections), 309.9ms
Speed: 1.6ms preprocess, 309.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xypSMUkD6U6ebFC7DMbHFg_0.JPG: 480x640 (no detections), 303.4ms
Speed: 1.4ms preprocess, 303.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xypSMUkD6U6ebFC7DMbHFg_90.JPG: 480x640 (no detections), 300.8ms
Speed: 1.2ms preprocess, 300.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xypSMUkD6U6ebFC7DMbHFg_180.JPG: 480x640 (no detections), 300.7ms
Speed: 1.3ms preprocess, 300.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xypSMUkD6U6ebFC7DMbHFg_270.JPG: 480x640 (no detections), 297.8ms
Speed: 1.2ms preprocess, 297.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xypkBraaRguI3IFLa-m6Yw_0.JPG: 480x640 (no detections), 301.8ms
Speed: 1.1ms preprocess, 301.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xypkBraaRguI3IFLa-m6Yw_90.JPG: 480x640 (no detections), 310.3ms
Speed: 1.9ms preprocess, 310.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xypkBraaRguI3IFLa-m6Yw_180.JPG: 480x640 (no detections), 301.5ms
Speed: 1.3ms preprocess, 301.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xypkBraaRguI3IFLa-m6Yw_270.JPG: 480x640 (no detections), 301.1ms
Speed: 1.1ms preprocess, 301.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xypxOPvsT1z4Mgb1cqYNag_0.JPG: 480x640 (no detections), 303.8ms
Speed: 1.3ms preprocess, 303.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xypxOPvsT1z4Mgb1cqYNag_90.JPG: 480x640 (no detections), 306.8ms
Speed: 1.1ms preprocess, 306.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xypxOPvsT1z4Mgb1cqYNag_180.JPG: 480x640 (no detections), 298.5ms
Speed: 1.9ms preprocess, 298.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xypxOPvsT1z4Mgb1cqYNag_270.JPG: 480x640 (no detections), 300.8ms
Speed: 1.2ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyruaxw4ujaYPnWqxtCc4Q_0.JPG: 480x640 (no detections), 305.0ms
Speed: 1.2ms preprocess, 305.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyruaxw4ujaYPnWqxtCc4Q_90.JPG: 480x640 (no detections), 292.3ms
Speed: 1.1ms preprocess, 292.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyruaxw4ujaYPnWqxtCc4Q_180.JPG: 480x640 1 Waste, 310.4ms
Speed: 1.5ms preprocess, 310.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xyruaxw4ujaYPnWqxtCc4Q_270.JPG: 480x640 (no detections), 298.1ms
Speed: 1.2ms preprocess, 298.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xysEfNimmc2s9-JVy1mglw_0.JPG: 480x640 (no detections), 295.3ms
Speed: 1.0ms preprocess, 295.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xysEfNimmc2s9-JVy1mglw_90.JPG: 480x640 (no detections), 298.5ms
Speed: 1.1ms preprocess, 298.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xysEfNimmc2s9-JVy1mglw_180.JPG: 480x640 (no detections), 296.8ms
Speed: 1.1ms preprocess, 296.8ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xysEfNimmc2s9-JVy1mglw_270.JPG: 480x640 (no detections), 299.3ms
Speed: 1.6ms preprocess, 299.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xysmzOOSV27lKXC4EwzbLA_0.JPG: 480x640 (no detections), 299.7ms
Speed: 1.2ms preprocess, 299.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xysmzOOSV27lKXC4EwzbLA_90.JPG: 480x640 (no detections), 299.4ms
Speed: 1.1ms preprocess, 299.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xysmzOOSV27lKXC4EwzbLA_180.JPG: 480x640 (no detections), 305.1ms
Speed: 1.1ms preprocess, 305.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/y/xysmzOOSV27lKXC4EwzbLA_270.JPG: 480x640 (no detections), 302.6ms
Speed: 1.1ms preprocess, 302.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xz3TE01kkDqXobkXUJ-e6g_0.JPG: 480x640 (no detections), 296.2ms
Speed: 1.3ms preprocess, 296.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xz3TE01kkDqXobkXUJ-e6g_90.JPG: 480x640 (no detections), 298.8ms
Speed: 2.1ms preprocess, 298.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xz3TE01kkDqXobkXUJ-e6g_180.JPG: 480x640 (no detections), 301.0ms
Speed: 1.4ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xz3TE01kkDqXobkXUJ-e6g_270.JPG: 480x640 (no detections), 300.6ms
Speed: 1.2ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xz3VM6SVH1DK03w8IDma0g_0.JPG: 480x640 (no detections), 300.0ms
Speed: 1.4ms preprocess, 300.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xz3VM6SVH1DK03w8IDma0g_90.JPG: 480x640 (no detections), 302.4ms
Speed: 1.3ms preprocess, 302.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xz3VM6SVH1DK03w8IDma0g_180.JPG: 480x640 (no detections), 299.3ms
Speed: 2.1ms preprocess, 299.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xz3VM6SVH1DK03w8IDma0g_270.JPG: 480x640 (no detections), 291.7ms
Speed: 1.0ms preprocess, 291.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xz7XkhdXITB61SuwHzwswQ_0.JPG: 480x640 (no detections), 290.2ms
Speed: 1.1ms preprocess, 290.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xz7XkhdXITB61SuwHzwswQ_90.JPG: 480x640 (no detections), 296.1ms
Speed: 1.1ms preprocess, 296.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xz7XkhdXITB61SuwHzwswQ_180.JPG: 480x640 (no detections), 304.6ms
Speed: 1.3ms preprocess, 304.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xz7XkhdXITB61SuwHzwswQ_270.JPG: 480x640 (no detections), 299.1ms
Speed: 1.3ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzC28Lu188H-iOLyiHiGcw_0.JPG: 480x640 (no detections), 305.6ms
Speed: 1.3ms preprocess, 305.6ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzC28Lu188H-iOLyiHiGcw_90.JPG: 480x640 (no detections), 300.8ms
Speed: 1.2ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzC28Lu188H-iOLyiHiGcw_180.JPG: 480x640 (no detections), 298.8ms
Speed: 1.2ms preprocess, 298.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzC28Lu188H-iOLyiHiGcw_270.JPG: 480x640 (no detections), 295.6ms
Speed: 1.1ms preprocess, 295.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzCx-oYwnEuOspXOwH8vQQ_0.JPG: 480x640 (no detections), 301.4ms
Speed: 1.2ms preprocess, 301.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzCx-oYwnEuOspXOwH8vQQ_90.JPG: 480x640 (no detections), 301.4ms
Speed: 1.5ms preprocess, 301.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzCx-oYwnEuOspXOwH8vQQ_180.JPG: 480x640 (no detections), 298.4ms
Speed: 1.1ms preprocess, 298.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzCx-oYwnEuOspXOwH8vQQ_270.JPG: 480x640 (no detections), 297.3ms
Speed: 1.0ms preprocess, 297.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzDiD_-XdCcj-DfLrT-4_Q_0.JPG: 480x640 (no detections), 301.7ms
Speed: 1.2ms preprocess, 301.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzDiD_-XdCcj-DfLrT-4_Q_90.JPG: 480x640 (no detections), 297.5ms
Speed: 1.6ms preprocess, 297.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzDiD_-XdCcj-DfLrT-4_Q_180.JPG: 480x640 (no detections), 294.4ms
Speed: 1.1ms preprocess, 294.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzDiD_-XdCcj-DfLrT-4_Q_270.JPG: 480x640 (no detections), 301.8ms
Speed: 1.4ms preprocess, 301.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzHNagai5v0VATxW5UyTQg_0.JPG: 480x640 (no detections), 296.6ms
Speed: 1.1ms preprocess, 296.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzHNagai5v0VATxW5UyTQg_90.JPG: 480x640 (no detections), 299.8ms
Speed: 1.3ms preprocess, 299.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzHNagai5v0VATxW5UyTQg_180.JPG: 480x640 (no detections), 299.2ms
Speed: 1.1ms preprocess, 299.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzHNagai5v0VATxW5UyTQg_270.JPG: 480x640 (no detections), 303.9ms
Speed: 1.2ms preprocess, 303.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzMdOiEi_DttODO_H48i6A_0.JPG: 480x640 (no detections), 300.3ms
Speed: 1.1ms preprocess, 300.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzMdOiEi_DttODO_H48i6A_90.JPG: 480x640 (no detections), 302.2ms
Speed: 1.1ms preprocess, 302.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzMdOiEi_DttODO_H48i6A_180.JPG: 480x640 (no detections), 298.9ms
Speed: 1.1ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzMdOiEi_DttODO_H48i6A_270.JPG: 480x640 (no detections), 301.1ms
Speed: 1.1ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzP639qYLhwnWa3hTc8gOQ_0.JPG: 480x640 (no detections), 300.1ms
Speed: 1.8ms preprocess, 300.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzP639qYLhwnWa3hTc8gOQ_90.JPG: 480x640 (no detections), 302.1ms
Speed: 1.2ms preprocess, 302.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzP639qYLhwnWa3hTc8gOQ_180.JPG: 480x640 (no detections), 300.5ms
Speed: 1.2ms preprocess, 300.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzP639qYLhwnWa3hTc8gOQ_270.JPG: 480x640 1 Waste, 299.6ms
Speed: 1.2ms preprocess, 299.6ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzP8rh5HmQz2hGRIqsu-vQ_0.JPG: 480x640 (no detections), 300.5ms
Speed: 1.2ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzP8rh5HmQz2hGRIqsu-vQ_90.JPG: 480x640 (no detections), 303.9ms
Speed: 1.2ms preprocess, 303.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzP8rh5HmQz2hGRIqsu-vQ_180.JPG: 480x640 2 Wastes, 299.1ms

Speed: 1.2ms preprocess, 299.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzP8rh5HmQz2hGRIqsu-vQ_270.JPG: 480x640 1 Waste, 303.3ms
Speed: 1.2ms preprocess, 303.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzPrWJDh4PmsJrfPMtXVBw_0.JPG: 480x640 (no detections), 299.9ms
Speed: 1.6ms preprocess, 299.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzPrWJDh4PmsJrfPMtXVBw_90.JPG: 480x640 (no detections), 301.5ms
Speed: 1.2ms preprocess, 301.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzPrWJDh4PmsJrfPMtXVBw_180.JPG: 480x640 (no detections), 300.2ms
Speed: 1.1ms preprocess, 300.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzPrWJDh4PmsJrfPMtXVBw_270.JPG: 480x640 (no detections), 308.4ms
Speed: 1.1ms preprocess, 308.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzXmNFxUU9PCxCoaDoQRfA_0.JPG: 480x640 (no detections), 299.8ms
Speed: 1.1ms preprocess, 299.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzXmNFxUU9PCxCoaDoQRfA_90.JPG: 480x640 (no detections), 301.0ms
Speed: 1.0ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzXmNFxUU9PCxCoaDoQRfA_180.JPG: 480x640 (no detections), 306.1ms
Speed: 1.1ms preprocess, 306.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzXmNFxUU9PCxCoaDoQRfA_270.JPG: 480x640 (no detections), 303.7ms
Speed: 1.2ms preprocess, 303.7ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzfRrlUum-T1PJAWT4y-WA_0.JPG: 480x640 (no detections), 297.1ms
Speed: 1.1ms preprocess, 297.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzfRrlUum-T1PJAWT4y-WA_90.JPG: 480x640 (no detections), 300.6ms
Speed: 1.2ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzfRrlUum-T1PJAWT4y-WA_180.JPG: 480x640 (no detections), 298.8ms
Speed: 1.0ms preprocess, 298.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzfRrlUum-T1PJAWT4y-WA_270.JPG: 480x640 (no detections), 297.7ms
Speed: 1.1ms preprocess, 297.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzfcPB7rR1Y34OSxyogPlw_0.JPG: 480x640 (no detections), 296.8ms
Speed: 1.1ms preprocess, 296.8ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzfcPB7rR1Y34OSxyogPlw_90.JPG: 480x640 (no detections), 305.6ms
Speed: 1.2ms preprocess, 305.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzfcPB7rR1Y34OSxyogPlw_180.JPG: 480x640 1 Waste, 303.3ms
Speed: 1.2ms preprocess, 303.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzfcPB7rR1Y34OSxyogPlw_270.JPG: 480x640 (no detections), 302.9ms
Speed: 1.2ms preprocess, 302.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzmM28ycD3EkIJ2chhqR2g_0.JPG: 480x640 (no detections), 307.3ms
Speed: 1.1ms preprocess, 307.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzmM28ycD3EkIJ2chhqR2g_90.JPG: 480x640 (no detections), 299.1ms
Speed: 1.0ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzmM28ycD3EkIJ2chhqR2g_180.JPG: 480x640 (no detections), 298.4ms
Speed: 1.2ms preprocess, 298.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzmM28ycD3EkIJ2chhqR2g_270.JPG: 480x640 (no detections), 301.5ms
Speed: 1.1ms preprocess, 301.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzqwEsrUcI0AfARFGs4LYA_0.JPG: 480x640 (no detections), 301.1ms
Speed: 1.4ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzqwEsrUcI0AfARFGs4LYA_90.JPG: 480x640 (no detections), 299.5ms
Speed: 1.1ms preprocess, 299.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzqwEsrUcI0AfARFGs4LYA_180.JPG: 480x640 (no detections), 301.9ms
Speed: 1.3ms preprocess, 301.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzqwEsrUcI0AfARFGs4LYA_270.JPG: 480x640 (no detections), 302.1ms
Speed: 1.6ms preprocess, 302.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzr0318YvtY3n7rz7dmo0A_0.JPG: 480x640 (no detections), 301.8ms
Speed: 1.4ms preprocess, 301.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzr0318YvtY3n7rz7dmo0A_90.JPG: 480x640 (no detections), 302.6ms
Speed: 1.2ms preprocess, 302.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzr0318YvtY3n7rz7dmo0A_180.JPG: 480x640 (no detections), 297.5ms
Speed: 1.2ms preprocess, 297.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzr0318YvtY3n7rz7dmo0A_270.JPG: 480x640 (no detections), 298.8ms
Speed: 1.6ms preprocess, 298.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzsp6LnhK4rr-NYSLn7qAQ_0.JPG: 480x640 (no detections), 301.4ms
Speed: 1.6ms preprocess, 301.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzsp6LnhK4rr-NYSLn7qAQ_90.JPG: 480x640 (no detections), 302.7ms
Speed: 1.2ms preprocess, 302.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzsp6LnhK4rr-NYSLn7qAQ_180.JPG: 480x640 (no detections), 298.8ms
Speed: 1.1ms preprocess, 298.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzsp6LnhK4rr-NYSLn7qAQ_270.JPG: 480x640 (no detections), 300.8ms
Speed: 1.2ms preprocess, 300.8ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzty50HEL9putLgLuDlfzg_0.JPG: 480x640 (no detections), 302.0ms
Speed: 1.2ms preprocess, 302.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzty50HEL9putLgLuDlfzg_90.JPG: 480x640 (no detections), 304.9ms
Speed: 1.3ms preprocess, 304.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzty50HEL9putLgLuDlfzg_180.JPG: 480x640 (no detections), 303.2ms
Speed: 1.7ms preprocess, 303.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzty50HEL9putLgLuDlfzg_270.JPG: 480x640 (no detections), 303.9ms
Speed: 1.2ms preprocess, 303.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzuJvQlA8HkCin3nRwE_SQ_0.JPG: 480x640 (no detections), 299.7ms
Speed: 1.1ms preprocess, 299.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzuJvQlA8HkCin3nRwE_SQ_90.JPG: 480x640 (no detections), 299.9ms
Speed: 1.3ms preprocess, 299.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzuJvQlA8HkCin3nRwE_SQ_180.JPG: 480x640 (no detections), 300.5ms
Speed: 1.1ms preprocess, 300.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzuJvQlA8HkCin3nRwE_SQ_270.JPG: 480x640 (no detections), 301.1ms
Speed: 1.1ms preprocess, 301.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzxHFc3Pdj7Q_MCBXHzs0A_0.JPG: 480x640 (no detections), 305.4ms
Speed: 1.2ms preprocess, 305.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzxHFc3Pdj7Q_MCBXHzs0A_90.JPG: 480x640 (no detections), 302.2ms
Speed: 1.3ms preprocess, 302.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzxHFc3Pdj7Q_MCBXHzs0A_180.JPG: 480x640 (no detections), 305.3ms
Speed: 1.2ms preprocess, 305.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzxHFc3Pdj7Q_MCBXHzs0A_270.JPG: 480x640 (no detections), 298.9ms
Speed: 1.2ms preprocess, 298.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzzPV3lEpsCXJISzNOrONg_0.JPG: 480x640 (no detections), 300.5ms
Speed: 1.4ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzzPV3lEpsCXJISzNOrONg_90.JPG: 480x640 (no detections), 295.4ms
Speed: 1.1ms preprocess, 295.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzzPV3lEpsCXJISzNOrONg_180.JPG: 480x640 (no detections), 298.6ms
Speed: 1.1ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/x/Z/xzzPV3lEpsCXJISzNOrONg_270.JPG: 480x640 (no detections), 291.2ms
Speed: 1.1ms preprocess, 291.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-0X0MqaJfkBBfztW-l_jg_0.JPG: 480x640 (no detections), 298.3ms
Speed: 1.3ms preprocess, 298.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-0X0MqaJfkBBfztW-l_jg_90.JPG: 480x640 (no detections), 303.0ms
Speed: 1.1ms preprocess, 303.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-0X0MqaJfkBBfztW-l_jg_180.JPG: 480x640 (no detections), 299.2ms
Speed: 1.3ms preprocess, 299.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-0X0MqaJfkBBfztW-l_jg_270.JPG: 480x640 (no detections), 300.7ms
Speed: 1.2ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-AjzYizypNxHGvQNYDJXg_0.JPG: 480x640 (no detections), 300.3ms
Speed: 1.7ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-AjzYizypNxHGvQNYDJXg_90.JPG: 480x640 (no detections), 299.8ms
Speed: 1.2ms preprocess, 299.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-AjzYizypNxHGvQNYDJXg_180.JPG: 480x640 (no detections), 297.9ms
Speed: 1.2ms preprocess, 297.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-AjzYizypNxHGvQNYDJXg_270.JPG: 480x640 (no detections), 304.8ms
Speed: 1.2ms preprocess, 304.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-EQBhv5uGJO4mZ94qSrgg_0.JPG: 480x640 (no detections), 304.9ms
Speed: 1.2ms preprocess, 304.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-EQBhv5uGJO4mZ94qSrgg_90.JPG: 480x640 (no detections), 304.1ms
Speed: 1.3ms preprocess, 304.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-EQBhv5uGJO4mZ94qSrgg_180.JPG: 480x640 (no detections), 302.7ms
Speed: 1.3ms preprocess, 302.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-EQBhv5uGJO4mZ94qSrgg_270.JPG: 480x640 (no detections), 299.0ms
Speed: 2.1ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-HjFE7u6l7FNFsiw8_GGQ_0.JPG: 480x640 (no detections), 302.4ms
Speed: 2.0ms preprocess, 302.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-HjFE7u6l7FNFsiw8_GGQ_90.JPG: 480x640 (no detections), 300.8ms
Speed: 1.1ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-HjFE7u6l7FNFsiw8_GGQ_180.JPG: 480x640 (no detections), 303.0ms
Speed: 1.2ms preprocess, 303.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-HjFE7u6l7FNFsiw8_GGQ_270.JPG: 480x640 (no detections), 301.5ms
Speed: 1.0ms preprocess, 301.5ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-IQX5At-rTP6xN1A3cW4A_0.JPG: 480x640 (no detections), 300.6ms
Speed: 1.4ms preprocess, 300.6ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-IQX5At-rTP6xN1A3cW4A_90.JPG: 480x640 (no detections), 300.5ms

Speed: 1.2ms preprocess, 300.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-IQX5At-rTP6xN1A3cW4A_180.JPG: 480x640 (no detections), 302.1ms
Speed: 1.4ms preprocess, 302.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-IQX5At-rTP6xN1A3cW4A_270.JPG: 480x640 1 Waste, 294.9ms
Speed: 1.4ms preprocess, 294.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-JiVeSLDXMQux2zBymrYg_0.JPG: 480x640 (no detections), 305.9ms
Speed: 1.0ms preprocess, 305.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-JiVeSLDXMQux2zBymrYg_90.JPG: 480x640 (no detections), 298.2ms
Speed: 1.8ms preprocess, 298.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-JiVeSLDXMQux2zBymrYg_180.JPG: 480x640 (no detections), 302.7ms
Speed: 1.3ms preprocess, 302.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-JiVeSLDXMQux2zBymrYg_270.JPG: 480x640 (no detections), 299.9ms
Speed: 1.4ms preprocess, 299.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-VhVbLX3MRn3DYv9qwY-w_0.JPG: 480x640 (no detections), 298.8ms
Speed: 1.1ms preprocess, 298.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-VhVbLX3MRn3DYv9qwY-w_90.JPG: 480x640 (no detections), 303.8ms
Speed: 1.2ms preprocess, 303.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-VhVbLX3MRn3DYv9qwY-w_180.JPG: 480x640 (no detections), 299.4ms
Speed: 1.2ms preprocess, 299.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-VhVbLX3MRn3DYv9qwY-w_270.JPG: 480x640 (no detections), 299.3ms
Speed: 1.1ms preprocess, 299.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-W0oAFJzqIBPKRfO9Tj3g_0.JPG: 480x640 (no detections), 298.5ms
Speed: 1.2ms preprocess, 298.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-W0oAFJzqIBPKRfO9Tj3g_90.JPG: 480x640 (no detections), 302.2ms
Speed: 1.2ms preprocess, 302.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-W0oAFJzqIBPKRfO9Tj3g_180.JPG: 480x640 (no detections), 300.5ms
Speed: 1.1ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-W0oAFJzqIBPKRfO9Tj3g_270.JPG: 480x640 (no detections), 298.2ms
Speed: 1.4ms preprocess, 298.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-g4Fgpe8yPcPOJugQsPQg_0.JPG: 480x640 (no detections), 297.1ms
Speed: 1.0ms preprocess, 297.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-g4Fgpe8yPcPOJugQsPQg_90.JPG: 480x640 (no detections), 301.0ms
Speed: 1.0ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-g4Fgpe8yPcPOJugQsPQg_180.JPG: 480x640 (no detections), 302.5ms
Speed: 1.3ms preprocess, 302.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-g4Fgpe8yPcPOJugQsPQg_270.JPG: 480x640 (no detections), 294.5ms
Speed: 1.0ms preprocess, 294.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-kNaibLAfRtbCdXLIF-pA_0.JPG: 480x640 (no detections), 299.5ms
Speed: 1.6ms preprocess, 299.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-kNaibLAfRtbCdXLIF-pA_90.JPG: 480x640 (no detections), 299.3ms
Speed: 1.2ms preprocess, 299.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-kNaibLAfRtbCdXLIF-pA_180.JPG: 480x640 (no detections), 301.4ms
Speed: 1.2ms preprocess, 301.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-kNaibLAfRtbCdXLIF-pA_270.JPG: 480x640 (no detections), 300.1ms
Speed: 1.2ms preprocess, 300.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-l57JAoP4aNjj4C6P9j2w_0.JPG: 480x640 (no detections), 302.3ms
Speed: 1.2ms preprocess, 302.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-l57JAoP4aNjj4C6P9j2w_90.JPG: 480x640 (no detections), 298.7ms
Speed: 1.5ms preprocess, 298.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-l57JAoP4aNjj4C6P9j2w_180.JPG: 480x640 (no detections), 299.8ms
Speed: 1.2ms preprocess, 299.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-l57JAoP4aNjj4C6P9j2w_270.JPG: 480x640 (no detections), 299.2ms
Speed: 1.3ms preprocess, 299.2ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-nqQ60F-kXuIR9s1S3uKw_0.JPG: 480x640 1 Waste, 306.1ms
Speed: 1.2ms preprocess, 306.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-nqQ60F-kXuIR9s1S3uKw_90.JPG: 480x640 (no detections), 302.5ms
Speed: 1.2ms preprocess, 302.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-nqQ60F-kXuIR9s1S3uKw_180.JPG: 480x640 (no detections), 297.6ms
Speed: 1.1ms preprocess, 297.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-nqQ60F-kXuIR9s1S3uKw_270.JPG: 480x640 1 Waste, 306.2ms
Speed: 1.2ms preprocess, 306.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-s2RVKUc-OlN3-X43y7Cg_0.JPG: 480x640 (no detections), 306.7ms
Speed: 1.3ms preprocess, 306.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-s2RVKUc-OlN3-X43y7Cg_90.JPG: 480x640 (no detections), 305.7ms
Speed: 1.4ms preprocess, 305.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-s2RVKUc-OlN3-X43y7Cg_180.JPG: 480x640 (no detections), 298.3ms
Speed: 1.3ms preprocess, 298.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-s2RVKUc-OlN3-X43y7Cg_270.JPG: 480x640 (no detections), 300.9ms
Speed: 1.3ms preprocess, 300.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-u-ik3myOYTJJI8rF0lrw_0.JPG: 480x640 (no detections), 299.9ms
Speed: 1.2ms preprocess, 299.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-u-ik3myOYTJJI8rF0lrw_90.JPG: 480x640 (no detections), 297.7ms
Speed: 1.8ms preprocess, 297.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-u-ik3myOYTJJI8rF0lrw_180.JPG: 480x640 (no detections), 299.9ms
Speed: 1.3ms preprocess, 299.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-u-ik3myOYTJJI8rF0lrw_270.JPG: 480x640 (no detections), 304.6ms
Speed: 1.0ms preprocess, 304.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-w7of7MdNFOznv7JvCyqQ_0.JPG: 480x640 (no detections), 301.0ms
Speed: 1.5ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-w7of7MdNFOznv7JvCyqQ_90.JPG: 480x640 (no detections), 298.2ms
Speed: 1.2ms preprocess, 298.2ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-w7of7MdNFOznv7JvCyqQ_180.JPG: 480x640 (no detections), 299.4ms
Speed: 1.1ms preprocess, 299.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-w7of7MdNFOznv7JvCyqQ_270.JPG: 480x640 (no detections), 301.8ms
Speed: 1.1ms preprocess, 301.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-yWTyRUyc-ZRO1-C4wefQ_0.JPG: 480x640 (no detections), 303.9ms
Speed: 1.1ms preprocess, 303.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-yWTyRUyc-ZRO1-C4wefQ_90.JPG: 480x640 (no detections), 300.2ms
Speed: 1.1ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-yWTyRUyc-ZRO1-C4wefQ_180.JPG: 480x640 (no detections), 300.0ms
Speed: 1.3ms preprocess, 300.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/-/y-yWTyRUyc-ZRO1-C4wefQ_270.JPG: 480x640 (no detections), 298.9ms
Speed: 1.2ms preprocess, 298.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y03LxkbdCNA1gJVzBEDgCg_0.JPG: 480x640 (no detections), 300.1ms
Speed: 1.1ms preprocess, 300.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y03LxkbdCNA1gJVzBEDgCg_90.JPG: 480x640 (no detections), 303.1ms
Speed: 1.1ms preprocess, 303.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y03LxkbdCNA1gJVzBEDgCg_180.JPG: 480x640 (no detections), 305.8ms
Speed: 1.3ms preprocess, 305.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y03LxkbdCNA1gJVzBEDgCg_270.JPG: 480x640 (no detections), 302.3ms
Speed: 1.9ms preprocess, 302.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y04O4m5QfjccM1zhg1p9Pg_0.JPG: 480x640 (no detections), 305.0ms
Speed: 1.4ms preprocess, 305.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y04O4m5QfjccM1zhg1p9Pg_90.JPG: 480x640 (no detections), 301.3ms
Speed: 1.4ms preprocess, 301.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y04O4m5QfjccM1zhg1p9Pg_180.JPG: 480x640 (no detections), 302.2ms
Speed: 1.1ms preprocess, 302.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y04O4m5QfjccM1zhg1p9Pg_270.JPG: 480x640 (no detections), 300.2ms
Speed: 1.2ms preprocess, 300.2ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y04smL_i4xcMTqlb7XHxbA_0.JPG: 480x640 (no detections), 303.0ms
Speed: 1.1ms preprocess, 303.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y04smL_i4xcMTqlb7XHxbA_90.JPG: 480x640 (no detections), 303.9ms
Speed: 1.3ms preprocess, 303.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y04smL_i4xcMTqlb7XHxbA_180.JPG: 480x640 (no detections), 293.2ms
Speed: 1.2ms preprocess, 293.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y04smL_i4xcMTqlb7XHxbA_270.JPG: 480x640 (no detections), 294.7ms
Speed: 1.0ms preprocess, 294.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y06EIV-XXpORYRosZp8doQ_0.JPG: 480x640 (no detections), 296.8ms
Speed: 1.1ms preprocess, 296.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y06EIV-XXpORYRosZp8doQ_90.JPG: 480x640 (no detections), 297.8ms
Speed: 1.6ms preprocess, 297.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y06EIV-XXpORYRosZp8doQ_180.JPG: 480x640 (no detections), 300.6ms
Speed: 1.2ms preprocess, 300.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y06EIV-XXpORYRosZp8doQ_270.JPG: 480x640 (no detections), 298.6ms
Speed: 1.2ms preprocess, 298.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0ERGg3coDt89vHqwgXWmg_0.JPG: 480x640 (no detections), 298.2ms
Speed: 1.1ms preprocess, 298.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0ERGg3coDt89vHqwgXWmg_90.JPG: 480x640 (no detections), 301.6ms
Speed: 1.2ms preprocess, 301.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0ERGg3coDt89vHqwgXWmg_180.JPG: 480x640 (no detections), 295.9ms
Speed: 1.3ms preprocess, 295.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0ERGg3coDt89vHqwgXWmg_270.JPG: 480x640 (no detections), 300.8ms
Speed: 1.2ms preprocess, 300.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0FnvmWcR5tbRTT3PXd6Dg_0.JPG: 480x640 (no detections), 306.1ms

Speed: 1.2ms preprocess, 306.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0FnvmWcR5tbRTT3PXd6Dg_90.JPG: 480x640 (no detections), 302.5ms
Speed: 1.0ms preprocess, 302.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0FnvmWcR5tbRTT3PXd6Dg_180.JPG: 480x640 (no detections), 298.6ms
Speed: 1.0ms preprocess, 298.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0FnvmWcR5tbRTT3PXd6Dg_270.JPG: 480x640 (no detections), 296.2ms
Speed: 1.1ms preprocess, 296.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0N5znczW5W9XAkb2BtkRw_0.JPG: 480x640 (no detections), 308.0ms
Speed: 1.3ms preprocess, 308.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0N5znczW5W9XAkb2BtkRw_90.JPG: 480x640 1 Waste, 301.2ms
Speed: 1.2ms preprocess, 301.2ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0N5znczW5W9XAkb2BtkRw_180.JPG: 480x640 2 Wastes, 299.9ms
Speed: 1.2ms preprocess, 299.9ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0N5znczW5W9XAkb2BtkRw_270.JPG: 480x640 1 Waste, 296.7ms
Speed: 1.4ms preprocess, 296.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0PGCyW6ceboiKNFOk9RZg_0.JPG: 480x640 (no detections), 301.2ms
Speed: 1.1ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0PGCyW6ceboiKNFOk9RZg_90.JPG: 480x640 (no detections), 305.2ms
Speed: 1.2ms preprocess, 305.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0PGCyW6ceboiKNFOk9RZg_180.JPG: 480x640 (no detections), 301.1ms
Speed: 1.1ms preprocess, 301.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0PGCyW6ceboiKNFOk9RZg_270.JPG: 480x640 (no detections), 296.1ms
Speed: 1.2ms preprocess, 296.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0TlgMCjEpjcQNp2j6j65A_0.JPG: 480x640 (no detections), 301.2ms
Speed: 1.1ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0TlgMCjEpjcQNp2j6j65A_90.JPG: 480x640 (no detections), 292.7ms
Speed: 1.2ms preprocess, 292.7ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0TlgMCjEpjcQNp2j6j65A_180.JPG: 480x640 (no detections), 301.5ms
Speed: 1.2ms preprocess, 301.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0TlgMCjEpjcQNp2j6j65A_270.JPG: 480x640 (no detections), 302.6ms
Speed: 1.4ms preprocess, 302.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0WkvH91JvO95lXQuj6dxQ_0.JPG: 480x640 (no detections), 300.8ms
Speed: 1.4ms preprocess, 300.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0WkvH91JvO95lXQuj6dxQ_90.JPG: 480x640 (no detections), 300.8ms
Speed: 1.2ms preprocess, 300.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0WkvH91JvO95lXQuj6dxQ_180.JPG: 480x640 (no detections), 299.2ms
Speed: 1.2ms preprocess, 299.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0WkvH91JvO95lXQuj6dxQ_270.JPG: 480x640 (no detections), 306.0ms
Speed: 1.2ms preprocess, 306.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0Wpi-ch20qWLucZ3b4YwQ_0.JPG: 480x640 (no detections), 297.4ms
Speed: 1.1ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0Wpi-ch20qWLucZ3b4YwQ_90.JPG: 480x640 (no detections), 301.8ms
Speed: 1.6ms preprocess, 301.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0Wpi-ch20qWLucZ3b4YwQ_180.JPG: 480x640 (no detections), 300.9ms
Speed: 1.2ms preprocess, 300.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0Wpi-ch20qWLucZ3b4YwQ_270.JPG: 480x640 (no detections), 302.7ms
Speed: 1.3ms preprocess, 302.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0X1si97bcZGFS4_K6q52A_0.JPG: 480x640 (no detections), 296.8ms
Speed: 1.1ms preprocess, 296.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0X1si97bcZGFS4_K6q52A_90.JPG: 480x640 (no detections), 302.5ms
Speed: 1.7ms preprocess, 302.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0X1si97bcZGFS4_K6q52A_180.JPG: 480x640 (no detections), 305.5ms
Speed: 1.4ms preprocess, 305.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0X1si97bcZGFS4_K6q52A_270.JPG: 480x640 (no detections), 302.5ms
Speed: 1.4ms preprocess, 302.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0_iRii7v4R7J7rlpHG20w_0.JPG: 480x640 (no detections), 304.7ms
Speed: 1.1ms preprocess, 304.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0_iRii7v4R7J7rlpHG20w_90.JPG: 480x640 (no detections), 386.5ms
Speed: 1.0ms preprocess, 386.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0_iRii7v4R7J7rlpHG20w_180.JPG: 480x640 (no detections), 298.5ms
Speed: 1.1ms preprocess, 298.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0_iRii7v4R7J7rlpHG20w_270.JPG: 480x640 (no detections), 302.6ms
Speed: 1.2ms preprocess, 302.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0bBDz_y770Q_DfhB_XMMw_0.JPG: 480x640 (no detections), 297.5ms
Speed: 1.2ms preprocess, 297.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0bBDz_y770Q_DfhB_XMMw_90.JPG: 480x640 (no detections), 299.9ms
Speed: 1.2ms preprocess, 299.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0bBDz_y770Q_DfhB_XMMw_180.JPG: 480x640 (no detections), 298.3ms
Speed: 1.1ms preprocess, 298.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0bBDz_y770Q_DfhB_XMMw_270.JPG: 480x640 (no detections), 291.7ms
Speed: 1.9ms preprocess, 291.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0bMregDZxvnHpunekJMrg_0.JPG: 480x640 (no detections), 303.7ms
Speed: 1.1ms preprocess, 303.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0bMregDZxvnHpunekJMrg_90.JPG: 480x640 (no detections), 294.9ms
Speed: 1.4ms preprocess, 294.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0bMregDZxvnHpunekJMrg_180.JPG: 480x640 (no detections), 286.0ms
Speed: 1.2ms preprocess, 286.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0bMregDZxvnHpunekJMrg_270.JPG: 480x640 (no detections), 301.1ms
Speed: 1.3ms preprocess, 301.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0dld1q28xuqhdQ0DoSyLA_0.JPG: 480x640 (no detections), 297.6ms
Speed: 1.2ms preprocess, 297.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0dld1q28xuqhdQ0DoSyLA_90.JPG: 480x640 (no detections), 301.2ms
Speed: 1.1ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0dld1q28xuqhdQ0DoSyLA_180.JPG: 480x640 (no detections), 300.4ms
Speed: 1.5ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0dld1q28xuqhdQ0DoSyLA_270.JPG: 480x640 (no detections), 300.3ms
Speed: 1.2ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0h0zoQbrjldtXWkKPG1AA_0.JPG: 480x640 (no detections), 303.5ms
Speed: 1.4ms preprocess, 303.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0h0zoQbrjldtXWkKPG1AA_90.JPG: 480x640 (no detections), 300.2ms
Speed: 1.1ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0h0zoQbrjldtXWkKPG1AA_180.JPG: 480x640 (no detections), 300.9ms
Speed: 1.1ms preprocess, 300.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0h0zoQbrjldtXWkKPG1AA_270.JPG: 480x640 (no detections), 295.3ms
Speed: 1.0ms preprocess, 295.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0hu3LffTwx__7ig9ig5KQ_0.JPG: 480x640 1 Waste, 301.7ms
Speed: 1.6ms preprocess, 301.7ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0hu3LffTwx__7ig9ig5KQ_90.JPG: 480x640 (no detections), 300.0ms
Speed: 1.1ms preprocess, 300.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0hu3LffTwx__7ig9ig5KQ_180.JPG: 480x640 1 Waste, 299.3ms
Speed: 1.2ms preprocess, 299.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0hu3LffTwx__7ig9ig5KQ_270.JPG: 480x640 (no detections), 300.8ms
Speed: 1.2ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0makunaSuVND-jX6j9ekA_0.JPG: 480x640 (no detections), 303.5ms
Speed: 1.2ms preprocess, 303.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0makunaSuVND-jX6j9ekA_90.JPG: 480x640 (no detections), 300.8ms
Speed: 1.9ms preprocess, 300.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0makunaSuVND-jX6j9ekA_180.JPG: 480x640 (no detections), 298.0ms
Speed: 1.1ms preprocess, 298.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0makunaSuVND-jX6j9ekA_270.JPG: 480x640 (no detections), 303.6ms
Speed: 1.1ms preprocess, 303.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0pEAEhO_K-bXj8_rJjkQA_0.JPG: 480x640 (no detections), 298.6ms
Speed: 1.1ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0pEAEhO_K-bXj8_rJjkQA_90.JPG: 480x640 (no detections), 301.2ms
Speed: 1.4ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0pEAEhO_K-bXj8_rJjkQA_180.JPG: 480x640 (no detections), 306.6ms
Speed: 1.3ms preprocess, 306.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0pEAEhO_K-bXj8_rJjkQA_270.JPG: 480x640 (no detections), 305.7ms
Speed: 1.2ms preprocess, 305.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0pkCF0ppF5rKpScWeWudw_0.JPG: 480x640 (no detections), 301.7ms
Speed: 1.1ms preprocess, 301.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0pkCF0ppF5rKpScWeWudw_90.JPG: 480x640 1 Waste, 300.6ms
Speed: 1.1ms preprocess, 300.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0pkCF0ppF5rKpScWeWudw_180.JPG: 480x640 (no detections), 299.2ms
Speed: 1.1ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0pkCF0ppF5rKpScWeWudw_270.JPG: 480x640 (no detections), 301.3ms
Speed: 1.2ms preprocess, 301.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0quSaMlWS_UK5-jDh8Ujg_0.JPG: 480x640 (no detections), 301.0ms
Speed: 1.4ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0quSaMlWS_UK5-jDh8Ujg_90.JPG: 480x640 2 Wastes, 301.0ms
Speed: 1.3ms preprocess, 301.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0quSaMlWS_UK5-jDh8Ujg_180.JPG: 480x640 (no detections), 298.9ms
Speed: 1.1ms preprocess, 298.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0quSaMlWS_UK5-jDh8Ujg_270.JPG: 480x640 (no detections), 300.4ms

Speed: 1.2ms preprocess, 300.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0rJHN6pQPMv8UH9bxH9vQ_0.JPG: 480x640 (no detections), 302.1ms
Speed: 1.4ms preprocess, 302.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0rJHN6pQPMv8UH9bxH9vQ_90.JPG: 480x640 (no detections), 304.7ms
Speed: 1.3ms preprocess, 304.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0rJHN6pQPMv8UH9bxH9vQ_180.JPG: 480x640 (no detections), 300.0ms
Speed: 1.1ms preprocess, 300.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0rJHN6pQPMv8UH9bxH9vQ_270.JPG: 480x640 (no detections), 299.9ms
Speed: 1.1ms preprocess, 299.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0v3OmZKq4qGk4yzPGIt7w_0.JPG: 480x640 (no detections), 300.0ms
Speed: 1.0ms preprocess, 300.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0v3OmZKq4qGk4yzPGIt7w_90.JPG: 480x640 (no detections), 298.8ms
Speed: 1.1ms preprocess, 298.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0v3OmZKq4qGk4yzPGIt7w_180.JPG: 480x640 (no detections), 301.9ms
Speed: 1.0ms preprocess, 301.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0v3OmZKq4qGk4yzPGIt7w_270.JPG: 480x640 (no detections), 298.5ms
Speed: 1.2ms preprocess, 298.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0vJ-cRboYnMAtYcX5-7kw_0.JPG: 480x640 (no detections), 302.4ms
Speed: 1.2ms preprocess, 302.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0vJ-cRboYnMAtYcX5-7kw_90.JPG: 480x640 (no detections), 297.4ms
Speed: 1.2ms preprocess, 297.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0vJ-cRboYnMAtYcX5-7kw_180.JPG: 480x640 (no detections), 298.9ms
Speed: 1.9ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0vJ-cRboYnMAtYcX5-7kw_270.JPG: 480x640 (no detections), 300.1ms
Speed: 1.2ms preprocess, 300.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0zXJ-gYG_ojSS-oCEPNqQ_0.JPG: 480x640 (no detections), 300.1ms
Speed: 1.1ms preprocess, 300.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0zXJ-gYG_ojSS-oCEPNqQ_90.JPG: 480x640 (no detections), 306.7ms
Speed: 1.1ms preprocess, 306.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0zXJ-gYG_ojSS-oCEPNqQ_180.JPG: 480x640 (no detections), 299.3ms
Speed: 1.2ms preprocess, 299.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/0/y0zXJ-gYG_ojSS-oCEPNqQ_270.JPG: 480x640 (no detections), 302.1ms
Speed: 1.1ms preprocess, 302.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y111AvRiqf0RcAHQ87zoNw_0.JPG: 480x640 (no detections), 301.2ms
Speed: 1.2ms preprocess, 301.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y111AvRiqf0RcAHQ87zoNw_90.JPG: 480x640 (no detections), 301.4ms
Speed: 1.2ms preprocess, 301.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y111AvRiqf0RcAHQ87zoNw_180.JPG: 480x640 (no detections), 303.3ms
Speed: 1.4ms preprocess, 303.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y111AvRiqf0RcAHQ87zoNw_270.JPG: 480x640 (no detections), 303.5ms
Speed: 1.1ms preprocess, 303.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y11vMj-SQI5cWdElB3DjGw_0.JPG: 480x640 1 Waste, 301.0ms
Speed: 1.3ms preprocess, 301.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y11vMj-SQI5cWdElB3DjGw_90.JPG: 480x640 2 Wastes, 299.6ms
Speed: 1.3ms preprocess, 299.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y11vMj-SQI5cWdElB3DjGw_180.JPG: 480x640 (no detections), 293.9ms
Speed: 1.3ms preprocess, 293.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y11vMj-SQI5cWdElB3DjGw_270.JPG: 480x640 (no detections), 298.5ms
Speed: 1.7ms preprocess, 298.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y13QrGsZ-UAj7rvUIx54DQ_0.JPG: 480x640 (no detections), 302.2ms
Speed: 1.2ms preprocess, 302.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y13QrGsZ-UAj7rvUIx54DQ_90.JPG: 480x640 (no detections), 298.5ms
Speed: 1.3ms preprocess, 298.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y13QrGsZ-UAj7rvUIx54DQ_180.JPG: 480x640 (no detections), 307.2ms
Speed: 1.5ms preprocess, 307.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y13QrGsZ-UAj7rvUIx54DQ_270.JPG: 480x640 (no detections), 300.7ms
Speed: 1.2ms preprocess, 300.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y14QVFi4gHT5ND-5nIi87Q_0.JPG: 480x640 (no detections), 300.3ms
Speed: 1.4ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y14QVFi4gHT5ND-5nIi87Q_90.JPG: 480x640 (no detections), 301.4ms
Speed: 1.3ms preprocess, 301.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y14QVFi4gHT5ND-5nIi87Q_180.JPG: 480x640 (no detections), 304.3ms
Speed: 1.3ms preprocess, 304.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y14QVFi4gHT5ND-5nIi87Q_270.JPG: 480x640 (no detections), 305.1ms
Speed: 1.3ms preprocess, 305.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y18XXPCLwKDhTQWgHsLf_w_0.JPG: 480x640 (no detections), 299.2ms
Speed: 1.1ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y18XXPCLwKDhTQWgHsLf_w_90.JPG: 480x640 (no detections), 306.0ms
Speed: 1.2ms preprocess, 306.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y18XXPCLwKDhTQWgHsLf_w_180.JPG: 480x640 (no detections), 307.7ms
Speed: 1.2ms preprocess, 307.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y18XXPCLwKDhTQWgHsLf_w_270.JPG: 480x640 (no detections), 301.9ms
Speed: 1.1ms preprocess, 301.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1AHSI5kmKot1y_IoUfAaQ_0.JPG: 480x640 (no detections), 301.4ms
Speed: 1.5ms preprocess, 301.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1AHSI5kmKot1y_IoUfAaQ_90.JPG: 480x640 (no detections), 299.8ms
Speed: 1.2ms preprocess, 299.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1AHSI5kmKot1y_IoUfAaQ_180.JPG: 480x640 (no detections), 304.6ms
Speed: 1.0ms preprocess, 304.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1AHSI5kmKot1y_IoUfAaQ_270.JPG: 480x640 (no detections), 305.0ms
Speed: 1.3ms preprocess, 305.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1ApX3TdZ41siGcjKK4BIQ_0.JPG: 480x640 (no detections), 306.4ms
Speed: 1.4ms preprocess, 306.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1ApX3TdZ41siGcjKK4BIQ_90.JPG: 480x640 (no detections), 304.0ms
Speed: 1.2ms preprocess, 304.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1ApX3TdZ41siGcjKK4BIQ_180.JPG: 480x640 (no detections), 301.5ms
Speed: 1.3ms preprocess, 301.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1ApX3TdZ41siGcjKK4BIQ_270.JPG: 480x640 (no detections), 293.6ms
Speed: 1.2ms preprocess, 293.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1DmIuoUotYIofRAaWC-Wg_0.JPG: 480x640 (no detections), 300.9ms
Speed: 1.3ms preprocess, 300.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1DmIuoUotYIofRAaWC-Wg_90.JPG: 480x640 (no detections), 303.4ms
Speed: 1.1ms preprocess, 303.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1DmIuoUotYIofRAaWC-Wg_180.JPG: 480x640 (no detections), 299.1ms
Speed: 1.5ms preprocess, 299.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1DmIuoUotYIofRAaWC-Wg_270.JPG: 480x640 (no detections), 303.6ms
Speed: 1.2ms preprocess, 303.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1E6zJGJDM7jSW0yYK4YLg_0.JPG: 480x640 (no detections), 302.9ms
Speed: 1.3ms preprocess, 302.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1E6zJGJDM7jSW0yYK4YLg_90.JPG: 480x640 (no detections), 297.2ms
Speed: 1.2ms preprocess, 297.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1E6zJGJDM7jSW0yYK4YLg_180.JPG: 480x640 (no detections), 299.1ms
Speed: 1.6ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1E6zJGJDM7jSW0yYK4YLg_270.JPG: 480x640 (no detections), 304.5ms
Speed: 1.2ms preprocess, 304.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1EE03qdfn1ZlUkZDxsZWw_0.JPG: 480x640 (no detections), 302.2ms
Speed: 1.4ms preprocess, 302.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1EE03qdfn1ZlUkZDxsZWw_90.JPG: 480x640 (no detections), 297.4ms
Speed: 1.2ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1EE03qdfn1ZlUkZDxsZWw_180.JPG: 480x640 (no detections), 299.3ms
Speed: 1.1ms preprocess, 299.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1EE03qdfn1ZlUkZDxsZWw_270.JPG: 480x640 (no detections), 302.1ms
Speed: 1.1ms preprocess, 302.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1Fe5HgkpGHWEn0OUsxhYQ_0.JPG: 480x640 (no detections), 300.3ms
Speed: 1.2ms preprocess, 300.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1Fe5HgkpGHWEn0OUsxhYQ_90.JPG: 480x640 (no detections), 306.5ms
Speed: 1.1ms preprocess, 306.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1Fe5HgkpGHWEn0OUsxhYQ_180.JPG: 480x640 1 Waste, 298.8ms
Speed: 1.2ms preprocess, 298.8ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1Fe5HgkpGHWEn0OUsxhYQ_270.JPG: 480x640 (no detections), 297.2ms
Speed: 1.6ms preprocess, 297.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1H1c82jZZGJMGPOGL_3xQ_0.JPG: 480x640 (no detections), 300.1ms
Speed: 1.1ms preprocess, 300.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1H1c82jZZGJMGPOGL_3xQ_90.JPG: 480x640 (no detections), 297.9ms
Speed: 1.2ms preprocess, 297.9ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1H1c82jZZGJMGPOGL_3xQ_180.JPG: 480x640 (no detections), 301.9ms
Speed: 1.2ms preprocess, 301.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1H1c82jZZGJMGPOGL_3xQ_270.JPG: 480x640 (no detections), 302.5ms
Speed: 1.2ms preprocess, 302.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1JTxjzLatZ8ZHM7scXxFA_0.JPG: 480x640 (no detections), 292.4ms
Speed: 1.3ms preprocess, 292.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1JTxjzLatZ8ZHM7scXxFA_90.JPG: 480x640 (no detections), 306.0ms
Speed: 1.3ms preprocess, 306.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1JTxjzLatZ8ZHM7scXxFA_180.JPG: 480x640 (no detections), 295.8ms

Speed: 1.4ms preprocess, 295.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1JTxjzLatZ8ZHM7scXxFA_270.JPG: 480x640 (no detections), 299.7ms
Speed: 1.1ms preprocess, 299.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1JXO-EJlT_KEnMp93EZIw_0.JPG: 480x640 (no detections), 297.8ms
Speed: 1.1ms preprocess, 297.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1JXO-EJlT_KEnMp93EZIw_90.JPG: 480x640 (no detections), 297.7ms
Speed: 1.2ms preprocess, 297.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1JXO-EJlT_KEnMp93EZIw_180.JPG: 480x640 (no detections), 301.1ms
Speed: 1.1ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1JXO-EJlT_KEnMp93EZIw_270.JPG: 480x640 (no detections), 303.9ms
Speed: 1.2ms preprocess, 303.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1LNTn6K2tGDqXS2d3yWNQ_0.JPG: 480x640 (no detections), 304.4ms
Speed: 1.0ms preprocess, 304.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1LNTn6K2tGDqXS2d3yWNQ_90.JPG: 480x640 (no detections), 298.0ms
Speed: 1.1ms preprocess, 298.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1LNTn6K2tGDqXS2d3yWNQ_180.JPG: 480x640 (no detections), 300.6ms
Speed: 1.1ms preprocess, 300.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1LNTn6K2tGDqXS2d3yWNQ_270.JPG: 480x640 (no detections), 297.2ms
Speed: 1.0ms preprocess, 297.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1LqhYxEtuQzeyWP_GGRUg_0.JPG: 480x640 1 Waste, 299.6ms
Speed: 1.2ms preprocess, 299.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1LqhYxEtuQzeyWP_GGRUg_90.JPG: 480x640 (no detections), 302.0ms
Speed: 1.3ms preprocess, 302.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1LqhYxEtuQzeyWP_GGRUg_180.JPG: 480x640 (no detections), 309.1ms
Speed: 1.2ms preprocess, 309.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1LqhYxEtuQzeyWP_GGRUg_270.JPG: 480x640 (no detections), 300.5ms
Speed: 1.4ms preprocess, 300.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1PNuBWlNk6kM0vcifEYoQ_0.JPG: 480x640 (no detections), 301.7ms
Speed: 1.1ms preprocess, 301.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1PNuBWlNk6kM0vcifEYoQ_90.JPG: 480x640 (no detections), 306.9ms
Speed: 1.5ms preprocess, 306.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1PNuBWlNk6kM0vcifEYoQ_180.JPG: 480x640 (no detections), 304.5ms
Speed: 1.3ms preprocess, 304.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1PNuBWlNk6kM0vcifEYoQ_270.JPG: 480x640 (no detections), 302.2ms
Speed: 1.0ms preprocess, 302.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1ZFOOhcOzwC12xefPNM_w_0.JPG: 480x640 (no detections), 297.3ms
Speed: 1.2ms preprocess, 297.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1ZFOOhcOzwC12xefPNM_w_90.JPG: 480x640 (no detections), 300.1ms
Speed: 1.8ms preprocess, 300.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1ZFOOhcOzwC12xefPNM_w_180.JPG: 480x640 (no detections), 299.4ms
Speed: 1.2ms preprocess, 299.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1ZFOOhcOzwC12xefPNM_w_270.JPG: 480x640 (no detections), 299.2ms
Speed: 1.2ms preprocess, 299.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1ZUyyCp42m7DELSfW1Oqw_0.JPG: 480x640 (no detections), 301.7ms
Speed: 1.3ms preprocess, 301.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1ZUyyCp42m7DELSfW1Oqw_90.JPG: 480x640 (no detections), 298.5ms
Speed: 1.1ms preprocess, 298.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1ZUyyCp42m7DELSfW1Oqw_180.JPG: 480x640 (no detections), 302.6ms
Speed: 1.2ms preprocess, 302.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1ZUyyCp42m7DELSfW1Oqw_270.JPG: 480x640 (no detections), 302.3ms
Speed: 1.6ms preprocess, 302.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1ZVElVdQpLjMZLiQ_B4eA_0.JPG: 480x640 (no detections), 306.3ms
Speed: 1.4ms preprocess, 306.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1ZVElVdQpLjMZLiQ_B4eA_90.JPG: 480x640 (no detections), 302.7ms
Speed: 1.2ms preprocess, 302.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1ZVElVdQpLjMZLiQ_B4eA_180.JPG: 480x640 (no detections), 300.1ms
Speed: 1.2ms preprocess, 300.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1ZVElVdQpLjMZLiQ_B4eA_270.JPG: 480x640 (no detections), 304.3ms
Speed: 1.1ms preprocess, 304.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1_1tzeDWsJ6j4ScXc2AnQ_0.JPG: 480x640 (no detections), 303.8ms
Speed: 1.2ms preprocess, 303.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1_1tzeDWsJ6j4ScXc2AnQ_90.JPG: 480x640 (no detections), 304.3ms
Speed: 1.8ms preprocess, 304.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1_1tzeDWsJ6j4ScXc2AnQ_180.JPG: 480x640 (no detections), 301.6ms
Speed: 1.1ms preprocess, 301.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1_1tzeDWsJ6j4ScXc2AnQ_270.JPG: 480x640 (no detections), 303.5ms
Speed: 1.4ms preprocess, 303.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1eUI3J-qZZr_ZV2dzLf-A_0.JPG: 480x640 (no detections), 299.6ms
Speed: 1.3ms preprocess, 299.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1eUI3J-qZZr_ZV2dzLf-A_90.JPG: 480x640 (no detections), 298.7ms
Speed: 1.2ms preprocess, 298.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1eUI3J-qZZr_ZV2dzLf-A_180.JPG: 480x640 (no detections), 303.9ms
Speed: 1.5ms preprocess, 303.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1eUI3J-qZZr_ZV2dzLf-A_270.JPG: 480x640 (no detections), 295.2ms
Speed: 1.2ms preprocess, 295.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1gdAQXLWbI6HtxonAHqyw_0.JPG: 480x640 (no detections), 301.1ms
Speed: 1.0ms preprocess, 301.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1gdAQXLWbI6HtxonAHqyw_90.JPG: 480x640 (no detections), 305.5ms
Speed: 1.1ms preprocess, 305.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1gdAQXLWbI6HtxonAHqyw_180.JPG: 480x640 (no detections), 301.5ms
Speed: 1.4ms preprocess, 301.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1gdAQXLWbI6HtxonAHqyw_270.JPG: 480x640 (no detections), 292.3ms
Speed: 1.3ms preprocess, 292.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1huqPXLfmaIb96HVkPicQ_0.JPG: 480x640 (no detections), 307.1ms
Speed: 1.3ms preprocess, 307.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1huqPXLfmaIb96HVkPicQ_90.JPG: 480x640 (no detections), 340.2ms
Speed: 1.3ms preprocess, 340.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1huqPXLfmaIb96HVkPicQ_180.JPG: 480x640 (no detections), 305.1ms
Speed: 1.4ms preprocess, 305.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1huqPXLfmaIb96HVkPicQ_270.JPG: 480x640 (no detections), 301.7ms
Speed: 1.4ms preprocess, 301.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1k4Zz2NJwZ4MGvgCwA8ow_0.JPG: 480x640 (no detections), 305.7ms
Speed: 1.0ms preprocess, 305.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1k4Zz2NJwZ4MGvgCwA8ow_90.JPG: 480x640 (no detections), 309.9ms
Speed: 1.1ms preprocess, 309.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1k4Zz2NJwZ4MGvgCwA8ow_180.JPG: 480x640 (no detections), 304.6ms
Speed: 1.1ms preprocess, 304.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1k4Zz2NJwZ4MGvgCwA8ow_270.JPG: 480x640 (no detections), 303.6ms
Speed: 1.2ms preprocess, 303.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1l8ygqOd389XfwoupGCPg_0.JPG: 480x640 (no detections), 301.3ms
Speed: 1.3ms preprocess, 301.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1l8ygqOd389XfwoupGCPg_90.JPG: 480x640 (no detections), 300.5ms
Speed: 1.2ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1l8ygqOd389XfwoupGCPg_180.JPG: 480x640 (no detections), 305.3ms
Speed: 1.3ms preprocess, 305.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1l8ygqOd389XfwoupGCPg_270.JPG: 480x640 (no detections), 303.2ms
Speed: 1.2ms preprocess, 303.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1yV1QpyHr_POGr6-nxM3Q_0.JPG: 480x640 (no detections), 296.4ms
Speed: 1.0ms preprocess, 296.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1yV1QpyHr_POGr6-nxM3Q_90.JPG: 480x640 (no detections), 303.9ms
Speed: 1.0ms preprocess, 303.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1yV1QpyHr_POGr6-nxM3Q_180.JPG: 480x640 (no detections), 300.2ms
Speed: 1.1ms preprocess, 300.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/1/y1yV1QpyHr_POGr6-nxM3Q_270.JPG: 480x640 (no detections), 300.4ms
Speed: 1.4ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2-FG6n2-eP1nZfaY5lTvQ_0.JPG: 480x640 (no detections), 300.7ms
Speed: 1.1ms preprocess, 300.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2-FG6n2-eP1nZfaY5lTvQ_90.JPG: 480x640 (no detections), 298.4ms
Speed: 1.1ms preprocess, 298.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2-FG6n2-eP1nZfaY5lTvQ_180.JPG: 480x640 (no detections), 296.5ms
Speed: 1.1ms preprocess, 296.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2-FG6n2-eP1nZfaY5lTvQ_270.JPG: 480x640 (no detections), 301.6ms
Speed: 1.6ms preprocess, 301.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y25mMMALTSbyeGTOpyb51w_0.JPG: 480x640 (no detections), 305.6ms
Speed: 1.3ms preprocess, 305.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y25mMMALTSbyeGTOpyb51w_90.JPG: 480x640 (no detections), 295.4ms
Speed: 1.1ms preprocess, 295.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y25mMMALTSbyeGTOpyb51w_180.JPG: 480x640 (no detections), 297.4ms
Speed: 1.1ms preprocess, 297.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y25mMMALTSbyeGTOpyb51w_270.JPG: 480x640 (no detections), 303.7ms
Speed: 1.0ms preprocess, 303.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y29Y9U-eMoWPc8Lu64SW0w_0.JPG: 480x640 (no detections), 296.8ms
Speed: 1.1ms preprocess, 296.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y29Y9U-eMoWPc8Lu64SW0w_90.JPG: 480x640 (no detections), 301.3ms

Speed: 1.6ms preprocess, 301.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y29Y9U-eMoWPc8Lu64SW0w_180.JPG: 480x640 (no detections), 306.1ms
Speed: 1.2ms preprocess, 306.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y29Y9U-eMoWPc8Lu64SW0w_270.JPG: 480x640 (no detections), 301.1ms
Speed: 1.4ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2AhmNP8OHC82eoVaMDD8Q_0.JPG: 480x640 (no detections), 300.3ms
Speed: 1.1ms preprocess, 300.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2AhmNP8OHC82eoVaMDD8Q_90.JPG: 480x640 (no detections), 300.3ms
Speed: 1.6ms preprocess, 300.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2AhmNP8OHC82eoVaMDD8Q_180.JPG: 480x640 (no detections), 303.9ms
Speed: 1.3ms preprocess, 303.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2AhmNP8OHC82eoVaMDD8Q_270.JPG: 480x640 (no detections), 297.8ms
Speed: 1.1ms preprocess, 297.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2BiqynVIzPQVPRd-Heybg_0.JPG: 480x640 1 Waste, 300.5ms
Speed: 1.2ms preprocess, 300.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2BiqynVIzPQVPRd-Heybg_90.JPG: 480x640 (no detections), 300.6ms
Speed: 1.6ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2BiqynVIzPQVPRd-Heybg_180.JPG: 480x640 (no detections), 297.5ms
Speed: 1.5ms preprocess, 297.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2BiqynVIzPQVPRd-Heybg_270.JPG: 480x640 (no detections), 303.6ms
Speed: 1.0ms preprocess, 303.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2CiDezxVCe2htqD2bdnsQ_0.JPG: 480x640 (no detections), 303.0ms
Speed: 1.2ms preprocess, 303.0ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2CiDezxVCe2htqD2bdnsQ_90.JPG: 480x640 (no detections), 303.7ms
Speed: 1.1ms preprocess, 303.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2CiDezxVCe2htqD2bdnsQ_180.JPG: 480x640 1 Waste, 301.7ms
Speed: 1.1ms preprocess, 301.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2CiDezxVCe2htqD2bdnsQ_270.JPG: 480x640 1 Waste, 296.9ms
Speed: 1.2ms preprocess, 296.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2DR_51jwcYJ5jl9kfVgTA_0.JPG: 480x640 (no detections), 298.4ms
Speed: 1.3ms preprocess, 298.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2DR_51jwcYJ5jl9kfVgTA_90.JPG: 480x640 (no detections), 299.6ms
Speed: 1.2ms preprocess, 299.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2DR_51jwcYJ5jl9kfVgTA_180.JPG: 480x640 (no detections), 301.1ms
Speed: 1.2ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2DR_51jwcYJ5jl9kfVgTA_270.JPG: 480x640 (no detections), 306.9ms
Speed: 1.3ms preprocess, 306.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2FjbzgH6EEwF9U4qDT8xA_0.JPG: 480x640 (no detections), 298.3ms
Speed: 1.2ms preprocess, 298.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2FjbzgH6EEwF9U4qDT8xA_90.JPG: 480x640 (no detections), 302.2ms
Speed: 1.2ms preprocess, 302.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2FjbzgH6EEwF9U4qDT8xA_180.JPG: 480x640 (no detections), 299.9ms
Speed: 1.2ms preprocess, 299.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2FjbzgH6EEwF9U4qDT8xA_270.JPG: 480x640 (no detections), 297.0ms
Speed: 1.4ms preprocess, 297.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2HIxr5uRa6jemDsXRknhw_0.JPG: 480x640 (no detections), 297.3ms
Speed: 1.3ms preprocess, 297.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2HIxr5uRa6jemDsXRknhw_90.JPG: 480x640 (no detections), 303.8ms
Speed: 1.3ms preprocess, 303.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2HIxr5uRa6jemDsXRknhw_180.JPG: 480x640 (no detections), 298.1ms
Speed: 1.3ms preprocess, 298.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2HIxr5uRa6jemDsXRknhw_270.JPG: 480x640 (no detections), 299.7ms
Speed: 1.2ms preprocess, 299.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2Ji2pRtQpikV82tSe5dOQ_0.JPG: 480x640 (no detections), 297.8ms
Speed: 1.3ms preprocess, 297.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2Ji2pRtQpikV82tSe5dOQ_90.JPG: 480x640 (no detections), 302.3ms
Speed: 1.2ms preprocess, 302.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2Ji2pRtQpikV82tSe5dOQ_180.JPG: 480x640 (no detections), 301.8ms
Speed: 1.2ms preprocess, 301.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2Ji2pRtQpikV82tSe5dOQ_270.JPG: 480x640 (no detections), 300.1ms
Speed: 1.2ms preprocess, 300.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2PXpHvKRgib1p0LMcSL-w_0.JPG: 480x640 1 Waste, 307.1ms
Speed: 1.3ms preprocess, 307.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2PXpHvKRgib1p0LMcSL-w_90.JPG: 480x640 (no detections), 299.4ms
Speed: 1.3ms preprocess, 299.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2PXpHvKRgib1p0LMcSL-w_180.JPG: 480x640 (no detections), 301.1ms
Speed: 1.1ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2PXpHvKRgib1p0LMcSL-w_270.JPG: 480x640 (no detections), 303.9ms
Speed: 1.2ms preprocess, 303.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2PdXdZ6deLb0ibLoqOr4w_0.JPG: 480x640 (no detections), 302.0ms
Speed: 1.2ms preprocess, 302.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2PdXdZ6deLb0ibLoqOr4w_90.JPG: 480x640 (no detections), 297.2ms
Speed: 1.2ms preprocess, 297.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2PdXdZ6deLb0ibLoqOr4w_180.JPG: 480x640 (no detections), 301.4ms
Speed: 1.5ms preprocess, 301.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2PdXdZ6deLb0ibLoqOr4w_270.JPG: 480x640 (no detections), 296.9ms
Speed: 1.2ms preprocess, 296.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2Rkjn3mRHz3Hcd3qumoDA_0.JPG: 480x640 (no detections), 297.5ms
Speed: 1.1ms preprocess, 297.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2Rkjn3mRHz3Hcd3qumoDA_90.JPG: 480x640 (no detections), 302.1ms
Speed: 1.1ms preprocess, 302.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2Rkjn3mRHz3Hcd3qumoDA_180.JPG: 480x640 (no detections), 311.8ms
Speed: 1.3ms preprocess, 311.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2Rkjn3mRHz3Hcd3qumoDA_270.JPG: 480x640 1 Waste, 300.1ms
Speed: 1.5ms preprocess, 300.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2SoumJ1_kJBRSFkh5r5TA_0.JPG: 480x640 (no detections), 302.1ms
Speed: 1.2ms preprocess, 302.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2SoumJ1_kJBRSFkh5r5TA_90.JPG: 480x640 1 Waste, 303.8ms
Speed: 1.3ms preprocess, 303.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2SoumJ1_kJBRSFkh5r5TA_180.JPG: 480x640 (no detections), 302.5ms
Speed: 1.2ms preprocess, 302.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2SoumJ1_kJBRSFkh5r5TA_270.JPG: 480x640 (no detections), 303.3ms
Speed: 1.7ms preprocess, 303.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2XCPcCA2zUmPoiIVuzb6A_0.JPG: 480x640 (no detections), 300.1ms
Speed: 1.9ms preprocess, 300.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2XCPcCA2zUmPoiIVuzb6A_90.JPG: 480x640 (no detections), 300.7ms
Speed: 1.1ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2XCPcCA2zUmPoiIVuzb6A_180.JPG: 480x640 (no detections), 305.0ms
Speed: 1.2ms preprocess, 305.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2XCPcCA2zUmPoiIVuzb6A_270.JPG: 480x640 (no detections), 306.2ms
Speed: 1.1ms preprocess, 306.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2YWHp86MvJUQv9ndjD1_w_0.JPG: 480x640 (no detections), 298.1ms
Speed: 1.2ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2YWHp86MvJUQv9ndjD1_w_90.JPG: 480x640 (no detections), 297.8ms
Speed: 1.2ms preprocess, 297.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2YWHp86MvJUQv9ndjD1_w_180.JPG: 480x640 (no detections), 299.6ms
Speed: 1.1ms preprocess, 299.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2YWHp86MvJUQv9ndjD1_w_270.JPG: 480x640 (no detections), 299.8ms
Speed: 1.3ms preprocess, 299.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2YaaF92jdomlBbTmy_QVg_0.JPG: 480x640 (no detections), 304.0ms
Speed: 1.1ms preprocess, 304.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2YaaF92jdomlBbTmy_QVg_90.JPG: 480x640 (no detections), 297.7ms
Speed: 2.0ms preprocess, 297.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2YaaF92jdomlBbTmy_QVg_180.JPG: 480x640 (no detections), 304.2ms
Speed: 1.1ms preprocess, 304.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2YaaF92jdomlBbTmy_QVg_270.JPG: 480x640 (no detections), 301.2ms
Speed: 1.2ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2aJx-27qdpGjkUXEisuIw_0.JPG: 480x640 (no detections), 302.3ms
Speed: 1.4ms preprocess, 302.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2aJx-27qdpGjkUXEisuIw_90.JPG: 480x640 (no detections), 306.7ms
Speed: 1.3ms preprocess, 306.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2aJx-27qdpGjkUXEisuIw_180.JPG: 480x640 (no detections), 302.5ms
Speed: 1.1ms preprocess, 302.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2aJx-27qdpGjkUXEisuIw_270.JPG: 480x640 (no detections), 296.8ms
Speed: 1.1ms preprocess, 296.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2eHpk9e00bRTYm9TR5Wig_0.JPG: 480x640 (no detections), 303.0ms
Speed: 1.1ms preprocess, 303.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2eHpk9e00bRTYm9TR5Wig_90.JPG: 480x640 (no detections), 301.0ms
Speed: 1.1ms preprocess, 301.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2eHpk9e00bRTYm9TR5Wig_180.JPG: 480x640 (no detections), 308.4ms
Speed: 1.2ms preprocess, 308.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2eHpk9e00bRTYm9TR5Wig_270.JPG: 480x640 (no detections), 300.2ms
Speed: 1.1ms preprocess, 300.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2eUTkC0Ymtcx46dcjVvrQ_0.JPG: 480x640 (no detections), 302.3ms

Speed: 1.0ms preprocess, 302.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2eUTkC0Ymtcx46dcjVvrQ_90.JPG: 480x640 (no detections), 299.4ms
Speed: 1.4ms preprocess, 299.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2eUTkC0Ymtcx46dcjVvrQ_180.JPG: 480x640 (no detections), 307.4ms
Speed: 1.1ms preprocess, 307.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2eUTkC0Ymtcx46dcjVvrQ_270.JPG: 480x640 (no detections), 302.2ms
Speed: 1.1ms preprocess, 302.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2em-7KyCMKBa4iKCN7Z8g_0.JPG: 480x640 (no detections), 298.9ms
Speed: 1.0ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2em-7KyCMKBa4iKCN7Z8g_90.JPG: 480x640 (no detections), 299.6ms
Speed: 1.3ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2em-7KyCMKBa4iKCN7Z8g_180.JPG: 480x640 (no detections), 301.8ms
Speed: 1.2ms preprocess, 301.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2em-7KyCMKBa4iKCN7Z8g_270.JPG: 480x640 (no detections), 302.0ms
Speed: 1.5ms preprocess, 302.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2eon67QybDmVRIDlwjMDg_0.JPG: 480x640 (no detections), 300.9ms
Speed: 1.2ms preprocess, 300.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2eon67QybDmVRIDlwjMDg_90.JPG: 480x640 (no detections), 303.3ms
Speed: 1.1ms preprocess, 303.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2eon67QybDmVRIDlwjMDg_180.JPG: 480x640 (no detections), 298.0ms
Speed: 1.2ms preprocess, 298.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2eon67QybDmVRIDlwjMDg_270.JPG: 480x640 (no detections), 301.6ms
Speed: 1.2ms preprocess, 301.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2gnAxHwNJeZxCqVAjdixg_0.JPG: 480x640 (no detections), 302.6ms
Speed: 1.1ms preprocess, 302.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2gnAxHwNJeZxCqVAjdixg_90.JPG: 480x640 1 Waste, 301.1ms
Speed: 1.9ms preprocess, 301.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2gnAxHwNJeZxCqVAjdixg_180.JPG: 480x640 (no detections), 298.8ms
Speed: 1.2ms preprocess, 298.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2gnAxHwNJeZxCqVAjdixg_270.JPG: 480x640 1 Waste, 299.7ms
Speed: 1.2ms preprocess, 299.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2iOp1VNhUeqltX-_Vag8Q_0.JPG: 480x640 (no detections), 298.8ms
Speed: 1.2ms preprocess, 298.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2iOp1VNhUeqltX-_Vag8Q_90.JPG: 480x640 1 Waste, 303.0ms
Speed: 1.3ms preprocess, 303.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2iOp1VNhUeqltX-_Vag8Q_180.JPG: 480x640 (no detections), 306.5ms
Speed: 1.3ms preprocess, 306.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2iOp1VNhUeqltX-_Vag8Q_270.JPG: 480x640 (no detections), 301.0ms
Speed: 1.1ms preprocess, 301.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2pYYH3Je2q4DHY-hCAMIQ_0.JPG: 480x640 (no detections), 299.2ms
Speed: 1.2ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2pYYH3Je2q4DHY-hCAMIQ_90.JPG: 480x640 (no detections), 302.1ms
Speed: 1.1ms preprocess, 302.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2pYYH3Je2q4DHY-hCAMIQ_180.JPG: 480x640 (no detections), 304.9ms
Speed: 1.3ms preprocess, 304.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2pYYH3Je2q4DHY-hCAMIQ_270.JPG: 480x640 (no detections), 306.1ms
Speed: 1.0ms preprocess, 306.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2ukGok0xUW_W4sjmVEa2w_0.JPG: 480x640 (no detections), 297.8ms
Speed: 1.3ms preprocess, 297.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2ukGok0xUW_W4sjmVEa2w_90.JPG: 480x640 (no detections), 298.6ms
Speed: 1.2ms preprocess, 298.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2ukGok0xUW_W4sjmVEa2w_180.JPG: 480x640 (no detections), 306.2ms
Speed: 1.2ms preprocess, 306.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2ukGok0xUW_W4sjmVEa2w_270.JPG: 480x640 (no detections), 302.4ms
Speed: 1.8ms preprocess, 302.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2xy7aRTOdzUZuFHtqBW1A_0.JPG: 480x640 (no detections), 300.9ms
Speed: 1.2ms preprocess, 300.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2xy7aRTOdzUZuFHtqBW1A_90.JPG: 480x640 (no detections), 303.4ms
Speed: 1.1ms preprocess, 303.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2xy7aRTOdzUZuFHtqBW1A_180.JPG: 480x640 (no detections), 297.4ms
Speed: 1.2ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2xy7aRTOdzUZuFHtqBW1A_270.JPG: 480x640 (no detections), 305.9ms
Speed: 1.3ms preprocess, 305.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2zOA-Y81jgUVKnsxTuCTw_0.JPG: 480x640 (no detections), 299.6ms
Speed: 1.2ms preprocess, 299.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2zOA-Y81jgUVKnsxTuCTw_90.JPG: 480x640 (no detections), 299.0ms
Speed: 1.1ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2zOA-Y81jgUVKnsxTuCTw_180.JPG: 480x640 (no detections), 299.6ms
Speed: 1.1ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/2/y2zOA-Y81jgUVKnsxTuCTw_270.JPG: 480x640 (no detections), 310.0ms
Speed: 1.3ms preprocess, 310.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3-XG4w9xQoNBMqFaJVtcA_0.JPG: 480x640 (no detections), 310.0ms
Speed: 1.3ms preprocess, 310.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3-XG4w9xQoNBMqFaJVtcA_90.JPG: 480x640 1 Waste, 298.0ms
Speed: 1.4ms preprocess, 298.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3-XG4w9xQoNBMqFaJVtcA_180.JPG: 480x640 (no detections), 301.3ms
Speed: 1.2ms preprocess, 301.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3-XG4w9xQoNBMqFaJVtcA_270.JPG: 480x640 (no detections), 317.1ms
Speed: 1.1ms preprocess, 317.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y32_UYW6OzSUsHw8wcicKw_0.JPG: 480x640 (no detections), 296.5ms
Speed: 1.5ms preprocess, 296.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y32_UYW6OzSUsHw8wcicKw_90.JPG: 480x640 (no detections), 296.8ms
Speed: 1.2ms preprocess, 296.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y32_UYW6OzSUsHw8wcicKw_180.JPG: 480x640 (no detections), 298.8ms
Speed: 1.3ms preprocess, 298.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y32_UYW6OzSUsHw8wcicKw_270.JPG: 480x640 (no detections), 294.8ms
Speed: 1.1ms preprocess, 294.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y38i4WF-IMOLbY6XSh1K9A_0.JPG: 480x640 (no detections), 302.5ms
Speed: 1.2ms preprocess, 302.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y38i4WF-IMOLbY6XSh1K9A_90.JPG: 480x640 (no detections), 306.8ms
Speed: 1.3ms preprocess, 306.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y38i4WF-IMOLbY6XSh1K9A_180.JPG: 480x640 (no detections), 300.3ms
Speed: 1.2ms preprocess, 300.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y38i4WF-IMOLbY6XSh1K9A_270.JPG: 480x640 (no detections), 304.6ms
Speed: 1.1ms preprocess, 304.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3BYPq8TpaqqQG0qDHDHFQ_0.JPG: 480x640 (no detections), 297.1ms
Speed: 1.3ms preprocess, 297.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3BYPq8TpaqqQG0qDHDHFQ_90.JPG: 480x640 (no detections), 302.2ms
Speed: 1.2ms preprocess, 302.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3BYPq8TpaqqQG0qDHDHFQ_180.JPG: 480x640 (no detections), 305.6ms
Speed: 1.2ms preprocess, 305.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3BYPq8TpaqqQG0qDHDHFQ_270.JPG: 480x640 (no detections), 301.1ms
Speed: 1.6ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3HrZDrE1iqeDH_wkLdBOg_0.JPG: 480x640 (no detections), 297.5ms
Speed: 1.1ms preprocess, 297.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3HrZDrE1iqeDH_wkLdBOg_90.JPG: 480x640 (no detections), 294.4ms
Speed: 1.2ms preprocess, 294.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3HrZDrE1iqeDH_wkLdBOg_180.JPG: 480x640 (no detections), 295.9ms
Speed: 1.2ms preprocess, 295.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3HrZDrE1iqeDH_wkLdBOg_270.JPG: 480x640 (no detections), 296.3ms
Speed: 1.1ms preprocess, 296.3ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3Mj0x2ZLev7y348k_tDBw_0.JPG: 480x640 (no detections), 294.1ms
Speed: 1.1ms preprocess, 294.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3Mj0x2ZLev7y348k_tDBw_90.JPG: 480x640 (no detections), 296.9ms
Speed: 1.9ms preprocess, 296.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3Mj0x2ZLev7y348k_tDBw_180.JPG: 480x640 (no detections), 302.1ms
Speed: 1.1ms preprocess, 302.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3Mj0x2ZLev7y348k_tDBw_270.JPG: 480x640 (no detections), 297.4ms
Speed: 1.1ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3Pm60zdEPLrorCICL5YxA_0.JPG: 480x640 (no detections), 294.8ms
Speed: 1.1ms preprocess, 294.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3Pm60zdEPLrorCICL5YxA_90.JPG: 480x640 (no detections), 297.9ms
Speed: 1.2ms preprocess, 297.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3Pm60zdEPLrorCICL5YxA_180.JPG: 480x640 (no detections), 305.9ms
Speed: 1.3ms preprocess, 305.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3Pm60zdEPLrorCICL5YxA_270.JPG: 480x640 (no detections), 293.9ms
Speed: 1.2ms preprocess, 293.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3PyEwvAcLTS60wW--6U6g_0.JPG: 480x640 (no detections), 296.1ms
Speed: 1.4ms preprocess, 296.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3PyEwvAcLTS60wW--6U6g_90.JPG: 480x640 (no detections), 300.6ms
Speed: 1.4ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3PyEwvAcLTS60wW--6U6g_180.JPG: 480x640 (no detections), 293.8ms
Speed: 1.3ms preprocess, 293.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3PyEwvAcLTS60wW--6U6g_270.JPG: 480x640 (no detections), 298.4ms

Speed: 1.3ms preprocess, 298.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3PzbYvlCZjMWxMQhjqf7g_0.JPG: 480x640 (no detections), 293.7ms
Speed: 1.6ms preprocess, 293.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3PzbYvlCZjMWxMQhjqf7g_90.JPG: 480x640 (no detections), 293.2ms
Speed: 1.3ms preprocess, 293.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3PzbYvlCZjMWxMQhjqf7g_180.JPG: 480x640 (no detections), 299.8ms
Speed: 1.3ms preprocess, 299.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3PzbYvlCZjMWxMQhjqf7g_270.JPG: 480x640 (no detections), 294.8ms
Speed: 1.9ms preprocess, 294.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3S6DLXMe3aDhHmAxOyT0A_0.JPG: 480x640 (no detections), 293.6ms
Speed: 1.2ms preprocess, 293.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3S6DLXMe3aDhHmAxOyT0A_90.JPG: 480x640 (no detections), 293.8ms
Speed: 1.0ms preprocess, 293.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3S6DLXMe3aDhHmAxOyT0A_180.JPG: 480x640 1 Waste, 290.2ms
Speed: 1.2ms preprocess, 290.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3S6DLXMe3aDhHmAxOyT0A_270.JPG: 480x640 (no detections), 303.8ms
Speed: 1.1ms preprocess, 303.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3XSSY0samzZRoMNBdxjyg_0.JPG: 480x640 (no detections), 298.2ms
Speed: 1.1ms preprocess, 298.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3XSSY0samzZRoMNBdxjyg_90.JPG: 480x640 (no detections), 296.3ms
Speed: 1.1ms preprocess, 296.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3XSSY0samzZRoMNBdxjyg_180.JPG: 480x640 (no detections), 298.1ms
Speed: 1.3ms preprocess, 298.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3XSSY0samzZRoMNBdxjyg_270.JPG: 480x640 (no detections), 298.5ms
Speed: 1.1ms preprocess, 298.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3XmGJrvMqncNWt6lBMBwQ_0.JPG: 480x640 (no detections), 300.0ms
Speed: 1.2ms preprocess, 300.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3XmGJrvMqncNWt6lBMBwQ_90.JPG: 480x640 (no detections), 295.8ms
Speed: 1.2ms preprocess, 295.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3XmGJrvMqncNWt6lBMBwQ_180.JPG: 480x640 (no detections), 298.8ms
Speed: 1.7ms preprocess, 298.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3XmGJrvMqncNWt6lBMBwQ_270.JPG: 480x640 (no detections), 294.5ms
Speed: 1.1ms preprocess, 294.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3bNvX8hWxSavvRH9rQTMQ_0.JPG: 480x640 (no detections), 294.4ms
Speed: 1.0ms preprocess, 294.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3bNvX8hWxSavvRH9rQTMQ_90.JPG: 480x640 (no detections), 300.3ms
Speed: 1.3ms preprocess, 300.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3bNvX8hWxSavvRH9rQTMQ_180.JPG: 480x640 (no detections), 295.8ms
Speed: 1.3ms preprocess, 295.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3bNvX8hWxSavvRH9rQTMQ_270.JPG: 480x640 (no detections), 300.6ms
Speed: 1.3ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3c0pD9ToG9lUnW7ww8EhQ_0.JPG: 480x640 (no detections), 298.1ms
Speed: 1.1ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3c0pD9ToG9lUnW7ww8EhQ_90.JPG: 480x640 (no detections), 297.1ms
Speed: 1.2ms preprocess, 297.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3c0pD9ToG9lUnW7ww8EhQ_180.JPG: 480x640 (no detections), 293.8ms
Speed: 1.1ms preprocess, 293.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3c0pD9ToG9lUnW7ww8EhQ_270.JPG: 480x640 (no detections), 295.3ms
Speed: 1.1ms preprocess, 295.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3el0ku8LkAvQVOJWEQfKw_0.JPG: 480x640 (no detections), 298.6ms
Speed: 1.1ms preprocess, 298.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3el0ku8LkAvQVOJWEQfKw_90.JPG: 480x640 (no detections), 298.3ms
Speed: 1.0ms preprocess, 298.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3el0ku8LkAvQVOJWEQfKw_180.JPG: 480x640 (no detections), 297.8ms
Speed: 1.0ms preprocess, 297.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3el0ku8LkAvQVOJWEQfKw_270.JPG: 480x640 (no detections), 297.5ms
Speed: 1.2ms preprocess, 297.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3kNVWAH-d45sRBjoSe4FQ_0.JPG: 480x640 (no detections), 296.5ms
Speed: 1.3ms preprocess, 296.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3kNVWAH-d45sRBjoSe4FQ_90.JPG: 480x640 (no detections), 298.3ms
Speed: 1.4ms preprocess, 298.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3kNVWAH-d45sRBjoSe4FQ_180.JPG: 480x640 (no detections), 296.0ms
Speed: 1.3ms preprocess, 296.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3kNVWAH-d45sRBjoSe4FQ_270.JPG: 480x640 (no detections), 293.1ms
Speed: 1.1ms preprocess, 293.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3wFKYGpR3p6BkZwZMeBVw_0.JPG: 480x640 (no detections), 301.3ms
Speed: 1.3ms preprocess, 301.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3wFKYGpR3p6BkZwZMeBVw_90.JPG: 480x640 (no detections), 293.3ms
Speed: 1.2ms preprocess, 293.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3wFKYGpR3p6BkZwZMeBVw_180.JPG: 480x640 (no detections), 299.4ms
Speed: 1.3ms preprocess, 299.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3wFKYGpR3p6BkZwZMeBVw_270.JPG: 480x640 (no detections), 413.6ms
Speed: 1.1ms preprocess, 413.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3wJc7DzZuNiWgtSW_z9eA_0.JPG: 480x640 (no detections), 302.2ms
Speed: 1.6ms preprocess, 302.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3wJc7DzZuNiWgtSW_z9eA_90.JPG: 480x640 (no detections), 290.4ms
Speed: 1.1ms preprocess, 290.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3wJc7DzZuNiWgtSW_z9eA_180.JPG: 480x640 (no detections), 302.6ms
Speed: 1.0ms preprocess, 302.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3wJc7DzZuNiWgtSW_z9eA_270.JPG: 480x640 (no detections), 306.8ms
Speed: 1.1ms preprocess, 306.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3yl2NfbLA52tM_ixiPSBQ_0.JPG: 480x640 (no detections), 299.1ms
Speed: 1.2ms preprocess, 299.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3yl2NfbLA52tM_ixiPSBQ_90.JPG: 480x640 1 Waste, 299.9ms
Speed: 1.3ms preprocess, 299.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3yl2NfbLA52tM_ixiPSBQ_180.JPG: 480x640 (no detections), 302.6ms
Speed: 1.3ms preprocess, 302.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/3/y3yl2NfbLA52tM_ixiPSBQ_270.JPG: 480x640 (no detections), 301.7ms
Speed: 1.5ms preprocess, 301.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4-svfo0fNJGKr2V9gn6_g_0.JPG: 480x640 (no detections), 303.6ms
Speed: 1.3ms preprocess, 303.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4-svfo0fNJGKr2V9gn6_g_90.JPG: 480x640 (no detections), 300.1ms
Speed: 1.3ms preprocess, 300.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4-svfo0fNJGKr2V9gn6_g_180.JPG: 480x640 (no detections), 301.0ms
Speed: 1.3ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4-svfo0fNJGKr2V9gn6_g_270.JPG: 480x640 (no detections), 303.9ms
Speed: 1.3ms preprocess, 303.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y42F6zqok2qxBkkkTslKag_0.JPG: 480x640 (no detections), 304.0ms
Speed: 1.3ms preprocess, 304.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y42F6zqok2qxBkkkTslKag_90.JPG: 480x640 (no detections), 303.5ms
Speed: 1.4ms preprocess, 303.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y42F6zqok2qxBkkkTslKag_180.JPG: 480x640 (no detections), 300.0ms
Speed: 1.1ms preprocess, 300.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y42F6zqok2qxBkkkTslKag_270.JPG: 480x640 (no detections), 299.5ms
Speed: 1.2ms preprocess, 299.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y49mXkLqFEtnE-r6SOFzIw_0.JPG: 480x640 (no detections), 299.0ms
Speed: 1.5ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y49mXkLqFEtnE-r6SOFzIw_90.JPG: 480x640 (no detections), 300.2ms
Speed: 1.4ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y49mXkLqFEtnE-r6SOFzIw_180.JPG: 480x640 (no detections), 299.2ms
Speed: 1.2ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y49mXkLqFEtnE-r6SOFzIw_270.JPG: 480x640 (no detections), 298.1ms
Speed: 1.1ms preprocess, 298.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4AZ61nIZSmIU3MLwCCMyA_0.JPG: 480x640 (no detections), 303.8ms
Speed: 1.1ms preprocess, 303.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4AZ61nIZSmIU3MLwCCMyA_90.JPG: 480x640 (no detections), 301.4ms
Speed: 1.2ms preprocess, 301.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4AZ61nIZSmIU3MLwCCMyA_180.JPG: 480x640 (no detections), 307.7ms
Speed: 1.2ms preprocess, 307.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4AZ61nIZSmIU3MLwCCMyA_270.JPG: 480x640 (no detections), 306.5ms
Speed: 1.2ms preprocess, 306.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4CfZ9euF-kkueld1PSJUg_0.JPG: 480x640 (no detections), 309.7ms
Speed: 1.9ms preprocess, 309.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4CfZ9euF-kkueld1PSJUg_90.JPG: 480x640 (no detections), 307.8ms
Speed: 1.2ms preprocess, 307.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4CfZ9euF-kkueld1PSJUg_180.JPG: 480x640 (no detections), 307.1ms
Speed: 1.2ms preprocess, 307.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4CfZ9euF-kkueld1PSJUg_270.JPG: 480x640 1 Waste, 312.3ms
Speed: 1.1ms preprocess, 312.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4HvCzpCFp17z8Z_O-kuKg_0.JPG: 480x640 (no detections), 313.7ms
Speed: 1.1ms preprocess, 313.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4HvCzpCFp17z8Z_O-kuKg_90.JPG: 480x640 (no detections), 328.7ms
Speed: 1.4ms preprocess, 328.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4HvCzpCFp17z8Z_O-kuKg_180.JPG: 480x640 (no detections), 303.4ms

Speed: 1.4ms preprocess, 303.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4HvCzpCFp17z8Z_O-kuKg_270.JPG: 480x640 (no detections), 299.6ms
Speed: 1.3ms preprocess, 299.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4Hzea3aQhH3tCnzK7boWQ_0.JPG: 480x640 (no detections), 297.3ms
Speed: 1.3ms preprocess, 297.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4Hzea3aQhH3tCnzK7boWQ_90.JPG: 480x640 (no detections), 311.7ms
Speed: 1.2ms preprocess, 311.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4Hzea3aQhH3tCnzK7boWQ_180.JPG: 480x640 (no detections), 306.6ms
Speed: 1.4ms preprocess, 306.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4Hzea3aQhH3tCnzK7boWQ_270.JPG: 480x640 (no detections), 299.8ms
Speed: 1.3ms preprocess, 299.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4JCIktDqpKeAC7BAXz6ww_0.JPG: 480x640 (no detections), 307.4ms
Speed: 1.1ms preprocess, 307.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4JCIktDqpKeAC7BAXz6ww_90.JPG: 480x640 (no detections), 306.2ms
Speed: 1.1ms preprocess, 306.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4JCIktDqpKeAC7BAXz6ww_180.JPG: 480x640 1 Waste, 308.6ms
Speed: 1.1ms preprocess, 308.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4JCIktDqpKeAC7BAXz6ww_270.JPG: 480x640 (no detections), 309.5ms
Speed: 1.2ms preprocess, 309.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4MCtiItnSrOUVOD7OdOcg_0.JPG: 480x640 (no detections), 313.8ms
Speed: 1.6ms preprocess, 313.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4MCtiItnSrOUVOD7OdOcg_90.JPG: 480x640 (no detections), 392.9ms
Speed: 1.1ms preprocess, 392.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4MCtiItnSrOUVOD7OdOcg_180.JPG: 480x640 (no detections), 301.1ms
Speed: 1.5ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4MCtiItnSrOUVOD7OdOcg_270.JPG: 480x640 (no detections), 306.1ms
Speed: 1.1ms preprocess, 306.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4NeCC3bupCVSuFHXJrRGQ_0.JPG: 480x640 (no detections), 303.6ms
Speed: 1.4ms preprocess, 303.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4NeCC3bupCVSuFHXJrRGQ_90.JPG: 480x640 (no detections), 309.0ms
Speed: 1.3ms preprocess, 309.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4NeCC3bupCVSuFHXJrRGQ_180.JPG: 480x640 (no detections), 299.9ms
Speed: 1.1ms preprocess, 299.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4NeCC3bupCVSuFHXJrRGQ_270.JPG: 480x640 (no detections), 304.3ms
Speed: 1.0ms preprocess, 304.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4PQjNgVHMjyCELinlajDg_0.JPG: 480x640 (no detections), 295.0ms
Speed: 1.1ms preprocess, 295.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4PQjNgVHMjyCELinlajDg_90.JPG: 480x640 (no detections), 291.5ms
Speed: 1.4ms preprocess, 291.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4PQjNgVHMjyCELinlajDg_180.JPG: 480x640 (no detections), 291.8ms
Speed: 1.4ms preprocess, 291.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4PQjNgVHMjyCELinlajDg_270.JPG: 480x640 (no detections), 292.2ms
Speed: 1.4ms preprocess, 292.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4WBRWpnsIY8ZjM2NMj5AA_0.JPG: 480x640 (no detections), 298.0ms
Speed: 1.4ms preprocess, 298.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4WBRWpnsIY8ZjM2NMj5AA_90.JPG: 480x640 (no detections), 294.1ms
Speed: 1.0ms preprocess, 294.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4WBRWpnsIY8ZjM2NMj5AA_180.JPG: 480x640 (no detections), 293.5ms
Speed: 1.3ms preprocess, 293.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4WBRWpnsIY8ZjM2NMj5AA_270.JPG: 480x640 (no detections), 301.6ms
Speed: 1.4ms preprocess, 301.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4YRV9Z7YoF1k3QCRlZc5A_0.JPG: 480x640 (no detections), 304.6ms
Speed: 1.3ms preprocess, 304.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4YRV9Z7YoF1k3QCRlZc5A_90.JPG: 480x640 (no detections), 302.4ms
Speed: 1.1ms preprocess, 302.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4YRV9Z7YoF1k3QCRlZc5A_180.JPG: 480x640 (no detections), 296.8ms
Speed: 1.1ms preprocess, 296.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4YRV9Z7YoF1k3QCRlZc5A_270.JPG: 480x640 (no detections), 300.2ms
Speed: 1.4ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4a_fCyY0ctxAW_FRc6Ohg_0.JPG: 480x640 (no detections), 302.8ms
Speed: 1.4ms preprocess, 302.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4a_fCyY0ctxAW_FRc6Ohg_90.JPG: 480x640 (no detections), 302.2ms
Speed: 1.1ms preprocess, 302.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4a_fCyY0ctxAW_FRc6Ohg_180.JPG: 480x640 (no detections), 299.2ms
Speed: 1.2ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4a_fCyY0ctxAW_FRc6Ohg_270.JPG: 480x640 (no detections), 306.0ms
Speed: 1.2ms preprocess, 306.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4i_Zc0cJJEWFKu-poZhYg_0.JPG: 480x640 (no detections), 304.2ms
Speed: 1.4ms preprocess, 304.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4i_Zc0cJJEWFKu-poZhYg_90.JPG: 480x640 (no detections), 298.0ms
Speed: 1.1ms preprocess, 298.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4i_Zc0cJJEWFKu-poZhYg_180.JPG: 480x640 (no detections), 303.2ms
Speed: 1.3ms preprocess, 303.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4i_Zc0cJJEWFKu-poZhYg_270.JPG: 480x640 (no detections), 300.2ms
Speed: 1.6ms preprocess, 300.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4mimABalMzJvAX9_4BDqA_0.JPG: 480x640 (no detections), 298.8ms
Speed: 1.1ms preprocess, 298.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4mimABalMzJvAX9_4BDqA_90.JPG: 480x640 (no detections), 300.1ms
Speed: 1.2ms preprocess, 300.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4mimABalMzJvAX9_4BDqA_180.JPG: 480x640 (no detections), 301.9ms
Speed: 1.2ms preprocess, 301.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4mimABalMzJvAX9_4BDqA_270.JPG: 480x640 (no detections), 301.5ms
Speed: 1.4ms preprocess, 301.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4sf3EvDmo5qNd6cUEhuYA_0.JPG: 480x640 (no detections), 299.0ms
Speed: 1.4ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4sf3EvDmo5qNd6cUEhuYA_90.JPG: 480x640 (no detections), 304.1ms
Speed: 1.3ms preprocess, 304.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4sf3EvDmo5qNd6cUEhuYA_180.JPG: 480x640 (no detections), 299.7ms
Speed: 1.0ms preprocess, 299.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4sf3EvDmo5qNd6cUEhuYA_270.JPG: 480x640 (no detections), 296.7ms
Speed: 1.6ms preprocess, 296.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4w9OXJTt8uf9qUjluuXDw_0.JPG: 480x640 (no detections), 301.4ms
Speed: 1.2ms preprocess, 301.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4w9OXJTt8uf9qUjluuXDw_90.JPG: 480x640 (no detections), 296.8ms
Speed: 1.2ms preprocess, 296.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4w9OXJTt8uf9qUjluuXDw_180.JPG: 480x640 (no detections), 301.8ms
Speed: 1.4ms preprocess, 301.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4w9OXJTt8uf9qUjluuXDw_270.JPG: 480x640 (no detections), 300.9ms
Speed: 1.2ms preprocess, 300.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4x301Eg2DcNQqjSzpAcGQ_0.JPG: 480x640 (no detections), 303.4ms
Speed: 1.2ms preprocess, 303.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4x301Eg2DcNQqjSzpAcGQ_90.JPG: 480x640 (no detections), 300.8ms
Speed: 1.2ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4x301Eg2DcNQqjSzpAcGQ_180.JPG: 480x640 (no detections), 301.9ms
Speed: 1.8ms preprocess, 301.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4x301Eg2DcNQqjSzpAcGQ_270.JPG: 480x640 (no detections), 300.3ms
Speed: 1.1ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4x42HDhGxYLb3ortj_kdg_0.JPG: 480x640 (no detections), 297.4ms
Speed: 1.2ms preprocess, 297.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4x42HDhGxYLb3ortj_kdg_90.JPG: 480x640 (no detections), 301.2ms
Speed: 1.6ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4x42HDhGxYLb3ortj_kdg_180.JPG: 480x640 (no detections), 301.1ms
Speed: 1.1ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4x42HDhGxYLb3ortj_kdg_270.JPG: 480x640 (no detections), 304.2ms
Speed: 1.2ms preprocess, 304.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4ziavq7p7Xees5HUWWTYw_0.JPG: 480x640 (no detections), 302.0ms
Speed: 1.3ms preprocess, 302.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4ziavq7p7Xees5HUWWTYw_90.JPG: 480x640 (no detections), 304.5ms
Speed: 1.2ms preprocess, 304.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4ziavq7p7Xees5HUWWTYw_180.JPG: 480x640 (no detections), 301.6ms
Speed: 1.1ms preprocess, 301.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/4/y4ziavq7p7Xees5HUWWTYw_270.JPG: 480x640 (no detections), 301.0ms
Speed: 1.1ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y51uCKhIeD5KmXd6Vfq-BQ_0.JPG: 480x640 (no detections), 303.6ms
Speed: 1.1ms preprocess, 303.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y51uCKhIeD5KmXd6Vfq-BQ_90.JPG: 480x640 (no detections), 304.7ms
Speed: 1.9ms preprocess, 304.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y51uCKhIeD5KmXd6Vfq-BQ_180.JPG: 480x640 (no detections), 298.3ms
Speed: 1.6ms preprocess, 298.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y51uCKhIeD5KmXd6Vfq-BQ_270.JPG: 480x640 (no detections), 301.0ms
Speed: 1.4ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y545JWUU44PZkeuTZFPH-A_0.JPG: 480x640 (no detections), 300.9ms
Speed: 1.2ms preprocess, 300.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y545JWUU44PZkeuTZFPH-A_90.JPG: 480x640 (no detections), 300.4ms

Speed: 1.5ms preprocess, 300.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y545JWUU44PZkeuTZFPH-A_180.JPG: 480x640 (no detections), 306.8ms
Speed: 1.2ms preprocess, 306.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y545JWUU44PZkeuTZFPH-A_270.JPG: 480x640 (no detections), 300.6ms
Speed: 1.2ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y54y6Zt3PyfIVKiw2__6NQ_0.JPG: 480x640 (no detections), 307.9ms
Speed: 1.3ms preprocess, 307.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y54y6Zt3PyfIVKiw2__6NQ_90.JPG: 480x640 (no detections), 301.2ms
Speed: 1.1ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y54y6Zt3PyfIVKiw2__6NQ_180.JPG: 480x640 (no detections), 305.0ms
Speed: 1.1ms preprocess, 305.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y54y6Zt3PyfIVKiw2__6NQ_270.JPG: 480x640 (no detections), 304.2ms
Speed: 1.1ms preprocess, 304.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5B8CNW69Z3Xq-aBzV8PgA_0.JPG: 480x640 (no detections), 302.0ms
Speed: 1.4ms preprocess, 302.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5B8CNW69Z3Xq-aBzV8PgA_90.JPG: 480x640 (no detections), 298.6ms
Speed: 1.2ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5B8CNW69Z3Xq-aBzV8PgA_180.JPG: 480x640 (no detections), 298.9ms
Speed: 1.7ms preprocess, 298.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5B8CNW69Z3Xq-aBzV8PgA_270.JPG: 480x640 (no detections), 297.1ms
Speed: 1.1ms preprocess, 297.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5EkR6Q9l6o8DZsdtSAWPQ_0.JPG: 480x640 (no detections), 299.1ms
Speed: 1.1ms preprocess, 299.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5EkR6Q9l6o8DZsdtSAWPQ_90.JPG: 480x640 (no detections), 300.6ms
Speed: 1.2ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5EkR6Q9l6o8DZsdtSAWPQ_180.JPG: 480x640 (no detections), 300.9ms
Speed: 1.1ms preprocess, 300.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5EkR6Q9l6o8DZsdtSAWPQ_270.JPG: 480x640 (no detections), 304.1ms
Speed: 1.2ms preprocess, 304.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5MlB9WKy2NxLF5Iq1Vfgg_0.JPG: 480x640 (no detections), 294.9ms
Speed: 1.1ms preprocess, 294.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5MlB9WKy2NxLF5Iq1Vfgg_90.JPG: 480x640 (no detections), 301.3ms
Speed: 1.3ms preprocess, 301.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5MlB9WKy2NxLF5Iq1Vfgg_180.JPG: 480x640 (no detections), 299.5ms
Speed: 1.1ms preprocess, 299.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5MlB9WKy2NxLF5Iq1Vfgg_270.JPG: 480x640 (no detections), 300.8ms
Speed: 1.1ms preprocess, 300.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5MrSeB_xAueqhCHhTGYdg_0.JPG: 480x640 (no detections), 302.4ms
Speed: 1.1ms preprocess, 302.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5MrSeB_xAueqhCHhTGYdg_90.JPG: 480x640 (no detections), 302.3ms
Speed: 1.1ms preprocess, 302.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5MrSeB_xAueqhCHhTGYdg_180.JPG: 480x640 (no detections), 299.6ms
Speed: 1.1ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5MrSeB_xAueqhCHhTGYdg_270.JPG: 480x640 (no detections), 298.2ms
Speed: 1.2ms preprocess, 298.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5NlRA-86iDoSDOoUoT4ag_0.JPG: 480x640 (no detections), 297.1ms
Speed: 1.2ms preprocess, 297.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5NlRA-86iDoSDOoUoT4ag_90.JPG: 480x640 (no detections), 298.3ms
Speed: 1.2ms preprocess, 298.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5NlRA-86iDoSDOoUoT4ag_180.JPG: 480x640 (no detections), 294.8ms
Speed: 1.1ms preprocess, 294.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5NlRA-86iDoSDOoUoT4ag_270.JPG: 480x640 (no detections), 300.6ms
Speed: 1.1ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5XebRRL4kW5i_3Ej67RQg_0.JPG: 480x640 (no detections), 299.5ms
Speed: 1.1ms preprocess, 299.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5XebRRL4kW5i_3Ej67RQg_90.JPG: 480x640 (no detections), 295.9ms
Speed: 1.2ms preprocess, 295.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5XebRRL4kW5i_3Ej67RQg_180.JPG: 480x640 (no detections), 299.0ms
Speed: 1.2ms preprocess, 299.0ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5XebRRL4kW5i_3Ej67RQg_270.JPG: 480x640 (no detections), 303.2ms
Speed: 1.2ms preprocess, 303.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5aFLjwqDs1EQ0WjSLkIig_0.JPG: 480x640 (no detections), 296.7ms
Speed: 1.8ms preprocess, 296.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5aFLjwqDs1EQ0WjSLkIig_90.JPG: 480x640 2 Wastes, 297.3ms
Speed: 1.3ms preprocess, 297.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5aFLjwqDs1EQ0WjSLkIig_180.JPG: 480x640 (no detections), 292.8ms
Speed: 1.2ms preprocess, 292.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5aFLjwqDs1EQ0WjSLkIig_270.JPG: 480x640 (no detections), 299.1ms
Speed: 1.1ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5aYWy0IHcyPuNp6i7DIHg_0.JPG: 480x640 (no detections), 298.1ms
Speed: 1.3ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5aYWy0IHcyPuNp6i7DIHg_90.JPG: 480x640 (no detections), 304.3ms
Speed: 1.2ms preprocess, 304.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5aYWy0IHcyPuNp6i7DIHg_180.JPG: 480x640 (no detections), 309.0ms
Speed: 1.6ms preprocess, 309.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5aYWy0IHcyPuNp6i7DIHg_270.JPG: 480x640 (no detections), 301.0ms
Speed: 1.1ms preprocess, 301.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5au5r3UDh03lm4cA0VGEQ_0.JPG: 480x640 (no detections), 301.7ms
Speed: 1.6ms preprocess, 301.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5au5r3UDh03lm4cA0VGEQ_90.JPG: 480x640 (no detections), 302.4ms
Speed: 1.1ms preprocess, 302.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5au5r3UDh03lm4cA0VGEQ_180.JPG: 480x640 (no detections), 297.1ms
Speed: 1.1ms preprocess, 297.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5au5r3UDh03lm4cA0VGEQ_270.JPG: 480x640 (no detections), 300.0ms
Speed: 1.1ms preprocess, 300.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5fzw1ObE7GnH74RZioZWw_0.JPG: 480x640 (no detections), 299.9ms
Speed: 1.2ms preprocess, 299.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5fzw1ObE7GnH74RZioZWw_90.JPG: 480x640 (no detections), 305.2ms
Speed: 1.3ms preprocess, 305.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5fzw1ObE7GnH74RZioZWw_180.JPG: 480x640 (no detections), 305.5ms
Speed: 1.2ms preprocess, 305.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5fzw1ObE7GnH74RZioZWw_270.JPG: 480x640 (no detections), 296.3ms
Speed: 1.1ms preprocess, 296.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5hs-1y-Hbt-EcSHRewcig_0.JPG: 480x640 (no detections), 296.2ms
Speed: 1.2ms preprocess, 296.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5hs-1y-Hbt-EcSHRewcig_90.JPG: 480x640 (no detections), 303.0ms
Speed: 1.6ms preprocess, 303.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5hs-1y-Hbt-EcSHRewcig_180.JPG: 480x640 (no detections), 300.1ms
Speed: 1.2ms preprocess, 300.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5hs-1y-Hbt-EcSHRewcig_270.JPG: 480x640 (no detections), 301.8ms
Speed: 1.3ms preprocess, 301.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5rOw_7aFW734sRSwEzXkw_0.JPG: 480x640 (no detections), 297.0ms
Speed: 1.1ms preprocess, 297.0ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5rOw_7aFW734sRSwEzXkw_90.JPG: 480x640 (no detections), 300.8ms
Speed: 1.0ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5rOw_7aFW734sRSwEzXkw_180.JPG: 480x640 (no detections), 294.6ms
Speed: 1.1ms preprocess, 294.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5rOw_7aFW734sRSwEzXkw_270.JPG: 480x640 (no detections), 296.4ms
Speed: 1.2ms preprocess, 296.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5syrdtD9OFoMIBz2B84Ag_0.JPG: 480x640 (no detections), 304.8ms
Speed: 1.2ms preprocess, 304.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5syrdtD9OFoMIBz2B84Ag_90.JPG: 480x640 (no detections), 302.8ms
Speed: 1.2ms preprocess, 302.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5syrdtD9OFoMIBz2B84Ag_180.JPG: 480x640 (no detections), 300.3ms
Speed: 1.3ms preprocess, 300.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5syrdtD9OFoMIBz2B84Ag_270.JPG: 480x640 (no detections), 299.8ms
Speed: 1.1ms preprocess, 299.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5wu_eL3yH8xDnyGk5WkAw_0.JPG: 480x640 (no detections), 303.8ms
Speed: 1.1ms preprocess, 303.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5wu_eL3yH8xDnyGk5WkAw_90.JPG: 480x640 (no detections), 307.3ms
Speed: 1.3ms preprocess, 307.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5wu_eL3yH8xDnyGk5WkAw_180.JPG: 480x640 (no detections), 300.0ms
Speed: 1.1ms preprocess, 300.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/5/y5wu_eL3yH8xDnyGk5WkAw_270.JPG: 480x640 (no detections), 302.1ms
Speed: 1.1ms preprocess, 302.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y60VbiqRwWCrO3BcNg9dWQ_0.JPG: 480x640 (no detections), 301.6ms
Speed: 1.2ms preprocess, 301.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y60VbiqRwWCrO3BcNg9dWQ_90.JPG: 480x640 1 Waste, 301.2ms
Speed: 1.2ms preprocess, 301.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y60VbiqRwWCrO3BcNg9dWQ_180.JPG: 480x640 1 Waste, 303.2ms
Speed: 1.3ms preprocess, 303.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y60VbiqRwWCrO3BcNg9dWQ_270.JPG: 480x640 (no detections), 300.6ms
Speed: 1.1ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y60_PmvFR1NH4CZy3VhuNQ_0.JPG: 480x640 (no detections), 299.6ms

Speed: 1.2ms preprocess, 299.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y60_PmvFR1NH4CZy3VhuNQ_90.JPG: 480x640 (no detections), 303.8ms
Speed: 1.1ms preprocess, 303.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y60_PmvFR1NH4CZy3VhuNQ_180.JPG: 480x640 (no detections), 301.2ms
Speed: 1.4ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y60_PmvFR1NH4CZy3VhuNQ_270.JPG: 480x640 (no detections), 303.0ms
Speed: 1.2ms preprocess, 303.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y649S6pc9CCAwv5_BwG2PQ_0.JPG: 480x640 (no detections), 309.6ms
Speed: 1.2ms preprocess, 309.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y649S6pc9CCAwv5_BwG2PQ_90.JPG: 480x640 (no detections), 298.8ms
Speed: 1.1ms preprocess, 298.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y649S6pc9CCAwv5_BwG2PQ_180.JPG: 480x640 (no detections), 302.3ms
Speed: 1.3ms preprocess, 302.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y649S6pc9CCAwv5_BwG2PQ_270.JPG: 480x640 (no detections), 301.6ms
Speed: 1.2ms preprocess, 301.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y664cjM9Bup08tH9Vnuwpg_0.JPG: 480x640 (no detections), 302.2ms
Speed: 1.2ms preprocess, 302.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y664cjM9Bup08tH9Vnuwpg_90.JPG: 480x640 (no detections), 303.7ms
Speed: 1.2ms preprocess, 303.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y664cjM9Bup08tH9Vnuwpg_180.JPG: 480x640 (no detections), 300.3ms
Speed: 1.2ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y664cjM9Bup08tH9Vnuwpg_270.JPG: 480x640 (no detections), 300.0ms
Speed: 1.4ms preprocess, 300.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y66vthegv4zdJ_laIuedPQ_0.JPG: 480x640 (no detections), 306.3ms
Speed: 1.2ms preprocess, 306.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y66vthegv4zdJ_laIuedPQ_90.JPG: 480x640 (no detections), 303.2ms
Speed: 1.2ms preprocess, 303.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y66vthegv4zdJ_laIuedPQ_180.JPG: 480x640 1 Waste, 304.1ms
Speed: 1.2ms preprocess, 304.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y66vthegv4zdJ_laIuedPQ_270.JPG: 480x640 (no detections), 301.2ms
Speed: 1.2ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6BTqVtU9tTk-hPycVP5mg_0.JPG: 480x640 (no detections), 305.1ms
Speed: 1.2ms preprocess, 305.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6BTqVtU9tTk-hPycVP5mg_90.JPG: 480x640 (no detections), 305.2ms
Speed: 1.3ms preprocess, 305.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6BTqVtU9tTk-hPycVP5mg_180.JPG: 480x640 (no detections), 305.5ms
Speed: 1.1ms preprocess, 305.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6BTqVtU9tTk-hPycVP5mg_270.JPG: 480x640 (no detections), 303.2ms
Speed: 1.3ms preprocess, 303.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6Gk1nTygS-XkWxE8goRAA_0.JPG: 480x640 (no detections), 299.3ms
Speed: 1.2ms preprocess, 299.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6Gk1nTygS-XkWxE8goRAA_90.JPG: 480x640 1 Waste, 302.4ms
Speed: 1.1ms preprocess, 302.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6Gk1nTygS-XkWxE8goRAA_180.JPG: 480x640 (no detections), 308.0ms
Speed: 1.1ms preprocess, 308.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6Gk1nTygS-XkWxE8goRAA_270.JPG: 480x640 (no detections), 300.7ms
Speed: 1.2ms preprocess, 300.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6HTwaNQrcvQsKvcaa5qhw_0.JPG: 480x640 (no detections), 298.3ms
Speed: 1.3ms preprocess, 298.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6HTwaNQrcvQsKvcaa5qhw_90.JPG: 480x640 (no detections), 301.8ms
Speed: 1.3ms preprocess, 301.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6HTwaNQrcvQsKvcaa5qhw_180.JPG: 480x640 (no detections), 299.5ms
Speed: 1.5ms preprocess, 299.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6HTwaNQrcvQsKvcaa5qhw_270.JPG: 480x640 (no detections), 303.1ms
Speed: 1.2ms preprocess, 303.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6M-BVJdRf7ReeJYAHjLkw_0.JPG: 480x640 (no detections), 300.3ms
Speed: 1.2ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6M-BVJdRf7ReeJYAHjLkw_90.JPG: 480x640 (no detections), 302.2ms
Speed: 1.4ms preprocess, 302.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6M-BVJdRf7ReeJYAHjLkw_180.JPG: 480x640 (no detections), 297.2ms
Speed: 1.3ms preprocess, 297.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6M-BVJdRf7ReeJYAHjLkw_270.JPG: 480x640 (no detections), 305.7ms
Speed: 1.1ms preprocess, 305.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6PA1UpaKfFQI-uPWTbwMw_0.JPG: 480x640 (no detections), 305.4ms
Speed: 1.3ms preprocess, 305.4ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6PA1UpaKfFQI-uPWTbwMw_90.JPG: 480x640 (no detections), 304.9ms
Speed: 1.1ms preprocess, 304.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6PA1UpaKfFQI-uPWTbwMw_180.JPG: 480x640 (no detections), 296.5ms
Speed: 1.2ms preprocess, 296.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6PA1UpaKfFQI-uPWTbwMw_270.JPG: 480x640 (no detections), 300.6ms
Speed: 1.1ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6PQoDeGbGTJasaCvra7hQ_0.JPG: 480x640 1 Waste, 298.5ms
Speed: 1.1ms preprocess, 298.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6PQoDeGbGTJasaCvra7hQ_90.JPG: 480x640 (no detections), 303.3ms
Speed: 1.5ms preprocess, 303.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6PQoDeGbGTJasaCvra7hQ_180.JPG: 480x640 (no detections), 303.8ms
Speed: 1.6ms preprocess, 303.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6PQoDeGbGTJasaCvra7hQ_270.JPG: 480x640 (no detections), 300.8ms
Speed: 1.2ms preprocess, 300.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6QO_1SROv-OkC1l7Lyzyg_0.JPG: 480x640 (no detections), 301.4ms
Speed: 1.4ms preprocess, 301.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6QO_1SROv-OkC1l7Lyzyg_90.JPG: 480x640 (no detections), 301.2ms
Speed: 1.3ms preprocess, 301.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6QO_1SROv-OkC1l7Lyzyg_180.JPG: 480x640 (no detections), 298.1ms
Speed: 1.2ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6QO_1SROv-OkC1l7Lyzyg_270.JPG: 480x640 (no detections), 305.2ms
Speed: 1.2ms preprocess, 305.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6UlN_I0wOtUjRXWaJONzw_0.JPG: 480x640 (no detections), 302.0ms
Speed: 1.1ms preprocess, 302.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6UlN_I0wOtUjRXWaJONzw_90.JPG: 480x640 (no detections), 300.6ms
Speed: 1.2ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6UlN_I0wOtUjRXWaJONzw_180.JPG: 480x640 (no detections), 299.0ms
Speed: 1.1ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6UlN_I0wOtUjRXWaJONzw_270.JPG: 480x640 (no detections), 299.9ms
Speed: 1.1ms preprocess, 299.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6UrbQb5fPRl5xOePJxyLg_0.JPG: 480x640 (no detections), 299.8ms
Speed: 1.3ms preprocess, 299.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6UrbQb5fPRl5xOePJxyLg_90.JPG: 480x640 (no detections), 295.4ms
Speed: 1.1ms preprocess, 295.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6UrbQb5fPRl5xOePJxyLg_180.JPG: 480x640 1 Waste, 304.1ms
Speed: 1.1ms preprocess, 304.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6UrbQb5fPRl5xOePJxyLg_270.JPG: 480x640 (no detections), 300.6ms
Speed: 1.2ms preprocess, 300.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6XylIQ8M_wl7ctAgfRS0A_0.JPG: 480x640 (no detections), 305.5ms
Speed: 1.1ms preprocess, 305.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6XylIQ8M_wl7ctAgfRS0A_90.JPG: 480x640 (no detections), 297.8ms
Speed: 1.0ms preprocess, 297.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6XylIQ8M_wl7ctAgfRS0A_180.JPG: 480x640 (no detections), 299.2ms
Speed: 1.1ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6XylIQ8M_wl7ctAgfRS0A_270.JPG: 480x640 (no detections), 299.9ms
Speed: 1.1ms preprocess, 299.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6d55kCy6TfxnzvOPomIGg_0.JPG: 480x640 (no detections), 303.8ms
Speed: 1.5ms preprocess, 303.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6d55kCy6TfxnzvOPomIGg_90.JPG: 480x640 (no detections), 298.0ms
Speed: 1.2ms preprocess, 298.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6d55kCy6TfxnzvOPomIGg_180.JPG: 480x640 (no detections), 297.5ms
Speed: 1.4ms preprocess, 297.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6d55kCy6TfxnzvOPomIGg_270.JPG: 480x640 (no detections), 300.1ms
Speed: 1.5ms preprocess, 300.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6eTBwBudYphY_ZmwX4prw_0.JPG: 480x640 (no detections), 298.6ms
Speed: 1.2ms preprocess, 298.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6eTBwBudYphY_ZmwX4prw_90.JPG: 480x640 (no detections), 292.4ms
Speed: 1.2ms preprocess, 292.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6eTBwBudYphY_ZmwX4prw_180.JPG: 480x640 (no detections), 312.4ms
Speed: 1.1ms preprocess, 312.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6eTBwBudYphY_ZmwX4prw_270.JPG: 480x640 (no detections), 295.0ms
Speed: 1.3ms preprocess, 295.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6fY_98Ted9bHkaC7FXmpQ_0.JPG: 480x640 1 Waste, 297.1ms
Speed: 1.5ms preprocess, 297.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6fY_98Ted9bHkaC7FXmpQ_90.JPG: 480x640 (no detections), 300.7ms
Speed: 1.3ms preprocess, 300.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6fY_98Ted9bHkaC7FXmpQ_180.JPG: 480x640 (no detections), 298.6ms
Speed: 1.3ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6fY_98Ted9bHkaC7FXmpQ_270.JPG: 480x640 (no detections), 302.2ms

Speed: 1.0ms preprocess, 302.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6pLo_WNaEZFiRS3jA4ESw_0.JPG: 480x640 (no detections), 299.9ms
Speed: 1.5ms preprocess, 299.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6pLo_WNaEZFiRS3jA4ESw_90.JPG: 480x640 (no detections), 300.8ms
Speed: 1.7ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6pLo_WNaEZFiRS3jA4ESw_180.JPG: 480x640 (no detections), 307.6ms
Speed: 1.3ms preprocess, 307.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6pLo_WNaEZFiRS3jA4ESw_270.JPG: 480x640 (no detections), 305.2ms
Speed: 1.4ms preprocess, 305.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6r1uZz5gyiByRQKJnfMvg_0.JPG: 480x640 (no detections), 298.8ms
Speed: 1.1ms preprocess, 298.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6r1uZz5gyiByRQKJnfMvg_90.JPG: 480x640 (no detections), 303.8ms
Speed: 1.4ms preprocess, 303.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6r1uZz5gyiByRQKJnfMvg_180.JPG: 480x640 (no detections), 306.1ms
Speed: 1.2ms preprocess, 306.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6r1uZz5gyiByRQKJnfMvg_270.JPG: 480x640 (no detections), 304.2ms
Speed: 1.2ms preprocess, 304.2ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6rqtgd-ZV7Tg-XKgQ7VBQ_0.JPG: 480x640 (no detections), 304.1ms
Speed: 1.1ms preprocess, 304.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6rqtgd-ZV7Tg-XKgQ7VBQ_90.JPG: 480x640 (no detections), 299.2ms
Speed: 1.2ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6rqtgd-ZV7Tg-XKgQ7VBQ_180.JPG: 480x640 (no detections), 298.8ms
Speed: 1.1ms preprocess, 298.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6rqtgd-ZV7Tg-XKgQ7VBQ_270.JPG: 480x640 (no detections), 298.7ms
Speed: 1.3ms preprocess, 298.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6tKisGKaNV__1stoF0SEg_0.JPG: 480x640 (no detections), 299.4ms
Speed: 1.2ms preprocess, 299.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6tKisGKaNV__1stoF0SEg_90.JPG: 480x640 (no detections), 301.7ms
Speed: 1.2ms preprocess, 301.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6tKisGKaNV__1stoF0SEg_180.JPG: 480x640 (no detections), 302.4ms
Speed: 1.4ms preprocess, 302.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6tKisGKaNV__1stoF0SEg_270.JPG: 480x640 (no detections), 306.8ms
Speed: 1.4ms preprocess, 306.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6tKmx1UVUopUb6kS-XBcA_0.JPG: 480x640 (no detections), 309.0ms
Speed: 1.0ms preprocess, 309.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6tKmx1UVUopUb6kS-XBcA_90.JPG: 480x640 (no detections), 298.6ms
Speed: 1.3ms preprocess, 298.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6tKmx1UVUopUb6kS-XBcA_180.JPG: 480x640 (no detections), 299.7ms
Speed: 1.2ms preprocess, 299.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6tKmx1UVUopUb6kS-XBcA_270.JPG: 480x640 (no detections), 300.7ms
Speed: 1.3ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6uD1Rkxx2O3LNz4FdHIAg_0.JPG: 480x640 (no detections), 300.6ms
Speed: 1.6ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6uD1Rkxx2O3LNz4FdHIAg_90.JPG: 480x640 (no detections), 300.5ms
Speed: 1.4ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6uD1Rkxx2O3LNz4FdHIAg_180.JPG: 480x640 (no detections), 299.0ms
Speed: 1.1ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6uD1Rkxx2O3LNz4FdHIAg_270.JPG: 480x640 (no detections), 303.1ms
Speed: 1.1ms preprocess, 303.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6v2oLZQQH94Gwc2N5nwlg_0.JPG: 480x640 (no detections), 301.4ms
Speed: 1.2ms preprocess, 301.4ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6v2oLZQQH94Gwc2N5nwlg_90.JPG: 480x640 (no detections), 305.0ms
Speed: 1.2ms preprocess, 305.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6v2oLZQQH94Gwc2N5nwlg_180.JPG: 480x640 (no detections), 302.3ms
Speed: 1.1ms preprocess, 302.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6v2oLZQQH94Gwc2N5nwlg_270.JPG: 480x640 (no detections), 299.2ms
Speed: 1.1ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6w2LQeGvVFD6BerBTzaHQ_0.JPG: 480x640 (no detections), 306.7ms
Speed: 1.2ms preprocess, 306.7ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6w2LQeGvVFD6BerBTzaHQ_90.JPG: 480x640 (no detections), 308.3ms
Speed: 1.4ms preprocess, 308.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6w2LQeGvVFD6BerBTzaHQ_180.JPG: 480x640 (no detections), 300.2ms
Speed: 1.1ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/6/y6w2LQeGvVFD6BerBTzaHQ_270.JPG: 480x640 (no detections), 302.6ms
Speed: 1.2ms preprocess, 302.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7-F8UZqlKzcy1VkpbG88w_0.JPG: 480x640 (no detections), 297.3ms
Speed: 1.6ms preprocess, 297.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7-F8UZqlKzcy1VkpbG88w_90.JPG: 480x640 (no detections), 300.8ms
Speed: 1.3ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7-F8UZqlKzcy1VkpbG88w_180.JPG: 480x640 (no detections), 296.2ms
Speed: 1.2ms preprocess, 296.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7-F8UZqlKzcy1VkpbG88w_270.JPG: 480x640 (no detections), 300.5ms
Speed: 1.3ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y74DyR1Slnv7oiMw2ePuCg_0.JPG: 480x640 (no detections), 293.3ms
Speed: 1.1ms preprocess, 293.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y74DyR1Slnv7oiMw2ePuCg_90.JPG: 480x640 (no detections), 295.2ms
Speed: 1.1ms preprocess, 295.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y74DyR1Slnv7oiMw2ePuCg_180.JPG: 480x640 (no detections), 299.3ms
Speed: 1.1ms preprocess, 299.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y74DyR1Slnv7oiMw2ePuCg_270.JPG: 480x640 (no detections), 304.2ms
Speed: 1.3ms preprocess, 304.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y75h7kC_cNLUIkQ0Gow7SQ_0.JPG: 480x640 (no detections), 301.0ms
Speed: 1.2ms preprocess, 301.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y75h7kC_cNLUIkQ0Gow7SQ_90.JPG: 480x640 (no detections), 302.8ms
Speed: 1.3ms preprocess, 302.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y75h7kC_cNLUIkQ0Gow7SQ_180.JPG: 480x640 (no detections), 301.0ms
Speed: 1.1ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y75h7kC_cNLUIkQ0Gow7SQ_270.JPG: 480x640 (no detections), 298.3ms
Speed: 1.2ms preprocess, 298.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y77SO0u6_BByf-WMedK-Tg_0.JPG: 480x640 (no detections), 303.4ms
Speed: 1.2ms preprocess, 303.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y77SO0u6_BByf-WMedK-Tg_90.JPG: 480x640 (no detections), 301.3ms
Speed: 1.5ms preprocess, 301.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y77SO0u6_BByf-WMedK-Tg_180.JPG: 480x640 (no detections), 300.1ms
Speed: 1.3ms preprocess, 300.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y77SO0u6_BByf-WMedK-Tg_270.JPG: 480x640 (no detections), 305.8ms
Speed: 1.1ms preprocess, 305.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7E0w2e_TNePuTaV-jb_yA_0.JPG: 480x640 (no detections), 301.0ms
Speed: 1.1ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7E0w2e_TNePuTaV-jb_yA_90.JPG: 480x640 (no detections), 302.3ms
Speed: 1.0ms preprocess, 302.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7E0w2e_TNePuTaV-jb_yA_180.JPG: 480x640 (no detections), 303.7ms
Speed: 1.3ms preprocess, 303.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7E0w2e_TNePuTaV-jb_yA_270.JPG: 480x640 (no detections), 302.9ms
Speed: 1.5ms preprocess, 302.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7F2yqwx5syPcvNA6n902A_0.JPG: 480x640 (no detections), 299.7ms
Speed: 1.2ms preprocess, 299.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7F2yqwx5syPcvNA6n902A_90.JPG: 480x640 (no detections), 302.8ms
Speed: 1.2ms preprocess, 302.8ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7F2yqwx5syPcvNA6n902A_180.JPG: 480x640 1 Waste, 308.3ms
Speed: 1.7ms preprocess, 308.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7F2yqwx5syPcvNA6n902A_270.JPG: 480x640 (no detections), 301.8ms
Speed: 1.1ms preprocess, 301.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7JjGdmyTXpbNNJ6j6Tq5Q_0.JPG: 480x640 (no detections), 296.9ms
Speed: 1.3ms preprocess, 296.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7JjGdmyTXpbNNJ6j6Tq5Q_90.JPG: 480x640 (no detections), 302.2ms
Speed: 1.3ms preprocess, 302.2ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7JjGdmyTXpbNNJ6j6Tq5Q_180.JPG: 480x640 (no detections), 302.4ms
Speed: 1.3ms preprocess, 302.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7JjGdmyTXpbNNJ6j6Tq5Q_270.JPG: 480x640 (no detections), 302.8ms
Speed: 1.4ms preprocess, 302.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7Kdqe2_KWD5KTgWzfDDZQ_0.JPG: 480x640 (no detections), 298.1ms
Speed: 1.2ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7Kdqe2_KWD5KTgWzfDDZQ_90.JPG: 480x640 (no detections), 298.2ms
Speed: 1.5ms preprocess, 298.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7Kdqe2_KWD5KTgWzfDDZQ_180.JPG: 480x640 (no detections), 301.1ms
Speed: 1.1ms preprocess, 301.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7Kdqe2_KWD5KTgWzfDDZQ_270.JPG: 480x640 (no detections), 304.0ms
Speed: 1.3ms preprocess, 304.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7OiXmMpTPU9Awr8EruzIQ_0.JPG: 480x640 (no detections), 301.4ms
Speed: 1.1ms preprocess, 301.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7OiXmMpTPU9Awr8EruzIQ_90.JPG: 480x640 (no detections), 304.6ms
Speed: 1.2ms preprocess, 304.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7OiXmMpTPU9Awr8EruzIQ_180.JPG: 480x640 (no detections), 296.8ms

Speed: 1.7ms preprocess, 296.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7OiXmMpTPU9Awr8EruzIQ_270.JPG: 480x640 (no detections), 300.1ms
Speed: 1.1ms preprocess, 300.1ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7U865fyjYuAzyCOMQ2PAA_0.JPG: 480x640 (no detections), 298.1ms
Speed: 1.1ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7U865fyjYuAzyCOMQ2PAA_90.JPG: 480x640 (no detections), 300.1ms
Speed: 1.1ms preprocess, 300.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7U865fyjYuAzyCOMQ2PAA_180.JPG: 480x640 (no detections), 303.4ms
Speed: 1.1ms preprocess, 303.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7U865fyjYuAzyCOMQ2PAA_270.JPG: 480x640 (no detections), 299.4ms
Speed: 1.2ms preprocess, 299.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7ZJbQG5EVTetMtWDj1Rpg_0.JPG: 480x640 (no detections), 298.6ms
Speed: 1.2ms preprocess, 298.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7ZJbQG5EVTetMtWDj1Rpg_90.JPG: 480x640 (no detections), 299.9ms
Speed: 1.2ms preprocess, 299.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7ZJbQG5EVTetMtWDj1Rpg_180.JPG: 480x640 (no detections), 297.8ms
Speed: 1.4ms preprocess, 297.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7ZJbQG5EVTetMtWDj1Rpg_270.JPG: 480x640 (no detections), 301.3ms
Speed: 1.1ms preprocess, 301.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7ZqSrSvYMfM2MI_FuScAg_0.JPG: 480x640 1 Waste, 305.5ms
Speed: 1.4ms preprocess, 305.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7ZqSrSvYMfM2MI_FuScAg_90.JPG: 480x640 (no detections), 299.7ms
Speed: 1.3ms preprocess, 299.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7ZqSrSvYMfM2MI_FuScAg_180.JPG: 480x640 (no detections), 304.9ms
Speed: 1.2ms preprocess, 304.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7ZqSrSvYMfM2MI_FuScAg_270.JPG: 480x640 (no detections), 301.6ms
Speed: 1.2ms preprocess, 301.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7_Dggv5D93G2rMwfB6EZg_0.JPG: 480x640 (no detections), 303.5ms
Speed: 1.2ms preprocess, 303.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7_Dggv5D93G2rMwfB6EZg_90.JPG: 480x640 (no detections), 303.3ms
Speed: 1.1ms preprocess, 303.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7_Dggv5D93G2rMwfB6EZg_180.JPG: 480x640 (no detections), 301.7ms
Speed: 1.1ms preprocess, 301.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7_Dggv5D93G2rMwfB6EZg_270.JPG: 480x640 (no detections), 299.5ms
Speed: 1.1ms preprocess, 299.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7_Fdo9NnQD2AIsMjr8j8A_0.JPG: 480x640 (no detections), 301.9ms
Speed: 1.4ms preprocess, 301.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7_Fdo9NnQD2AIsMjr8j8A_90.JPG: 480x640 (no detections), 302.7ms
Speed: 1.5ms preprocess, 302.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7_Fdo9NnQD2AIsMjr8j8A_180.JPG: 480x640 (no detections), 299.0ms
Speed: 1.3ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7_Fdo9NnQD2AIsMjr8j8A_270.JPG: 480x640 (no detections), 302.8ms
Speed: 1.2ms preprocess, 302.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7_GbOfWhTZKW-WD_Scoqw_0.JPG: 480x640 (no detections), 300.7ms
Speed: 1.3ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7_GbOfWhTZKW-WD_Scoqw_90.JPG: 480x640 (no detections), 305.5ms
Speed: 1.2ms preprocess, 305.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7_GbOfWhTZKW-WD_Scoqw_180.JPG: 480x640 1 Waste, 301.1ms
Speed: 1.3ms preprocess, 301.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7_GbOfWhTZKW-WD_Scoqw_270.JPG: 480x640 (no detections), 299.2ms
Speed: 1.1ms preprocess, 299.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7b7HRQPeYlAZ338daC6Lg_0.JPG: 480x640 (no detections), 300.1ms
Speed: 1.2ms preprocess, 300.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7b7HRQPeYlAZ338daC6Lg_90.JPG: 480x640 (no detections), 305.3ms
Speed: 1.1ms preprocess, 305.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7b7HRQPeYlAZ338daC6Lg_180.JPG: 480x640 (no detections), 300.3ms
Speed: 1.3ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7b7HRQPeYlAZ338daC6Lg_270.JPG: 480x640 (no detections), 301.0ms
Speed: 1.1ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7bhKWCUkULzXe2UW1WsKg_0.JPG: 480x640 (no detections), 300.3ms
Speed: 1.2ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7bhKWCUkULzXe2UW1WsKg_90.JPG: 480x640 1 Waste, 301.4ms
Speed: 1.2ms preprocess, 301.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7bhKWCUkULzXe2UW1WsKg_180.JPG: 480x640 (no detections), 303.4ms
Speed: 1.1ms preprocess, 303.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7bhKWCUkULzXe2UW1WsKg_270.JPG: 480x640 (no detections), 304.0ms
Speed: 1.5ms preprocess, 304.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7fZYQscKTQNjAwj-zB5UA_0.JPG: 480x640 (no detections), 299.9ms
Speed: 1.5ms preprocess, 299.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7fZYQscKTQNjAwj-zB5UA_90.JPG: 480x640 (no detections), 298.9ms
Speed: 1.3ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7fZYQscKTQNjAwj-zB5UA_180.JPG: 480x640 (no detections), 301.0ms
Speed: 2.1ms preprocess, 301.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7fZYQscKTQNjAwj-zB5UA_270.JPG: 480x640 (no detections), 300.4ms
Speed: 1.1ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7jtPJ7OfO3TmeVh5iwm3A_0.JPG: 480x640 (no detections), 295.2ms
Speed: 1.1ms preprocess, 295.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7jtPJ7OfO3TmeVh5iwm3A_90.JPG: 480x640 (no detections), 298.9ms
Speed: 1.4ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7jtPJ7OfO3TmeVh5iwm3A_180.JPG: 480x640 (no detections), 305.0ms
Speed: 1.2ms preprocess, 305.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7jtPJ7OfO3TmeVh5iwm3A_270.JPG: 480x640 (no detections), 299.8ms
Speed: 1.2ms preprocess, 299.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7okZ0SyGsDEJGFlncUh9A_0.JPG: 480x640 (no detections), 301.2ms
Speed: 1.2ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7okZ0SyGsDEJGFlncUh9A_90.JPG: 480x640 (no detections), 301.9ms
Speed: 1.0ms preprocess, 301.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7okZ0SyGsDEJGFlncUh9A_180.JPG: 480x640 (no detections), 302.6ms
Speed: 1.2ms preprocess, 302.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7okZ0SyGsDEJGFlncUh9A_270.JPG: 480x640 (no detections), 302.3ms
Speed: 1.0ms preprocess, 302.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7oxyT8L6I5Ek5H6vIapiA_0.JPG: 480x640 (no detections), 300.5ms
Speed: 1.3ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7oxyT8L6I5Ek5H6vIapiA_90.JPG: 480x640 (no detections), 298.0ms
Speed: 1.2ms preprocess, 298.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7oxyT8L6I5Ek5H6vIapiA_180.JPG: 480x640 (no detections), 300.2ms
Speed: 1.1ms preprocess, 300.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7oxyT8L6I5Ek5H6vIapiA_270.JPG: 480x640 (no detections), 302.6ms
Speed: 1.1ms preprocess, 302.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7rI3Uqfw6pN08cR-_7G6w_0.JPG: 480x640 (no detections), 303.6ms
Speed: 1.2ms preprocess, 303.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7rI3Uqfw6pN08cR-_7G6w_90.JPG: 480x640 (no detections), 298.8ms
Speed: 1.5ms preprocess, 298.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7rI3Uqfw6pN08cR-_7G6w_180.JPG: 480x640 (no detections), 299.6ms
Speed: 1.1ms preprocess, 299.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7rI3Uqfw6pN08cR-_7G6w_270.JPG: 480x640 (no detections), 299.9ms
Speed: 1.3ms preprocess, 299.9ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7vhrvVzWWte0ASTCpZ45Q_0.JPG: 480x640 (no detections), 302.6ms
Speed: 1.4ms preprocess, 302.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7vhrvVzWWte0ASTCpZ45Q_90.JPG: 480x640 (no detections), 303.1ms
Speed: 1.5ms preprocess, 303.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7vhrvVzWWte0ASTCpZ45Q_180.JPG: 480x640 (no detections), 299.8ms
Speed: 1.4ms preprocess, 299.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7vhrvVzWWte0ASTCpZ45Q_270.JPG: 480x640 (no detections), 300.6ms
Speed: 1.3ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7w3dJE55BF8mgfQq-UhkQ_0.JPG: 480x640 (no detections), 299.2ms
Speed: 1.2ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7w3dJE55BF8mgfQq-UhkQ_90.JPG: 480x640 (no detections), 299.0ms
Speed: 1.3ms preprocess, 299.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7w3dJE55BF8mgfQq-UhkQ_180.JPG: 480x640 (no detections), 305.1ms
Speed: 1.2ms preprocess, 305.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/7/y7w3dJE55BF8mgfQq-UhkQ_270.JPG: 480x640 (no detections), 298.8ms
Speed: 1.2ms preprocess, 298.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y81G7hmRjl294ODbLQa2rg_0.JPG: 480x640 (no detections), 301.2ms
Speed: 1.3ms preprocess, 301.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y81G7hmRjl294ODbLQa2rg_90.JPG: 480x640 (no detections), 300.1ms
Speed: 1.2ms preprocess, 300.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y81G7hmRjl294ODbLQa2rg_180.JPG: 480x640 (no detections), 300.8ms
Speed: 1.4ms preprocess, 300.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y81G7hmRjl294ODbLQa2rg_270.JPG: 480x640 (no detections), 299.2ms
Speed: 1.3ms preprocess, 299.2ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y81q5OizlNQ0Cx2iYAU0ag_0.JPG: 480x640 (no detections), 300.1ms
Speed: 1.3ms preprocess, 300.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y81q5OizlNQ0Cx2iYAU0ag_90.JPG: 480x640 (no detections), 305.4ms

Speed: 1.3ms preprocess, 305.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y81q5OizlNQ0Cx2iYAU0ag_180.JPG: 480x640 (no detections), 305.7ms
Speed: 1.2ms preprocess, 305.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y81q5OizlNQ0Cx2iYAU0ag_270.JPG: 480x640 (no detections), 300.0ms
Speed: 1.4ms preprocess, 300.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y82GWSdWE4UKPMkUhQTQDw_0.JPG: 480x640 (no detections), 298.2ms
Speed: 1.2ms preprocess, 298.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y82GWSdWE4UKPMkUhQTQDw_90.JPG: 480x640 (no detections), 302.8ms
Speed: 1.8ms preprocess, 302.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y82GWSdWE4UKPMkUhQTQDw_180.JPG: 480x640 (no detections), 299.5ms
Speed: 1.1ms preprocess, 299.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y82GWSdWE4UKPMkUhQTQDw_270.JPG: 480x640 (no detections), 302.0ms
Speed: 1.1ms preprocess, 302.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y83BNIIbQhHLvaV0BPh1Sg_0.JPG: 480x640 (no detections), 300.8ms
Speed: 1.1ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y83BNIIbQhHLvaV0BPh1Sg_90.JPG: 480x640 (no detections), 297.0ms
Speed: 1.4ms preprocess, 297.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y83BNIIbQhHLvaV0BPh1Sg_180.JPG: 480x640 (no detections), 301.1ms
Speed: 1.2ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y83BNIIbQhHLvaV0BPh1Sg_270.JPG: 480x640 (no detections), 302.9ms
Speed: 1.2ms preprocess, 302.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y83Y4b858VWhnp-RcewpvA_0.JPG: 480x640 (no detections), 299.0ms
Speed: 1.1ms preprocess, 299.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y83Y4b858VWhnp-RcewpvA_90.JPG: 480x640 (no detections), 303.8ms
Speed: 1.1ms preprocess, 303.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y83Y4b858VWhnp-RcewpvA_180.JPG: 480x640 (no detections), 304.5ms
Speed: 1.2ms preprocess, 304.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y83Y4b858VWhnp-RcewpvA_270.JPG: 480x640 (no detections), 304.7ms
Speed: 1.0ms preprocess, 304.7ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y84NUPneXvZ9AQexxG1R7A_0.JPG: 480x640 1 Waste, 297.6ms
Speed: 1.2ms preprocess, 297.6ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y84NUPneXvZ9AQexxG1R7A_90.JPG: 480x640 (no detections), 301.1ms
Speed: 1.1ms preprocess, 301.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y84NUPneXvZ9AQexxG1R7A_180.JPG: 480x640 (no detections), 304.7ms
Speed: 1.2ms preprocess, 304.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y84NUPneXvZ9AQexxG1R7A_270.JPG: 480x640 (no detections), 305.5ms
Speed: 1.2ms preprocess, 305.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y87KP2qB7so21SOR8aUy2w_0.JPG: 480x640 (no detections), 298.3ms
Speed: 1.1ms preprocess, 298.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y87KP2qB7so21SOR8aUy2w_90.JPG: 480x640 (no detections), 301.2ms
Speed: 1.1ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y87KP2qB7so21SOR8aUy2w_180.JPG: 480x640 (no detections), 300.8ms
Speed: 1.0ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y87KP2qB7so21SOR8aUy2w_270.JPG: 480x640 (no detections), 300.4ms
Speed: 1.2ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y88hcMoxJve3M7ycLU2pRg_0.JPG: 480x640 (no detections), 299.9ms
Speed: 1.4ms preprocess, 299.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y88hcMoxJve3M7ycLU2pRg_90.JPG: 480x640 (no detections), 297.5ms
Speed: 1.3ms preprocess, 297.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y88hcMoxJve3M7ycLU2pRg_180.JPG: 480x640 (no detections), 305.2ms
Speed: 1.2ms preprocess, 305.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y88hcMoxJve3M7ycLU2pRg_270.JPG: 480x640 (no detections), 302.9ms
Speed: 1.1ms preprocess, 302.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y88nFRvBW7fSPQHYqKRMTQ_0.JPG: 480x640 (no detections), 300.9ms
Speed: 1.2ms preprocess, 300.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y88nFRvBW7fSPQHYqKRMTQ_90.JPG: 480x640 (no detections), 300.2ms
Speed: 1.2ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y88nFRvBW7fSPQHYqKRMTQ_180.JPG: 480x640 (no detections), 302.8ms
Speed: 1.2ms preprocess, 302.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y88nFRvBW7fSPQHYqKRMTQ_270.JPG: 480x640 (no detections), 300.5ms
Speed: 1.3ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8AQuFHaWWUbJSXFTu62OQ_0.JPG: 480x640 (no detections), 298.4ms
Speed: 1.2ms preprocess, 298.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8AQuFHaWWUbJSXFTu62OQ_90.JPG: 480x640 (no detections), 299.8ms
Speed: 1.8ms preprocess, 299.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8AQuFHaWWUbJSXFTu62OQ_180.JPG: 480x640 (no detections), 301.4ms
Speed: 1.3ms preprocess, 301.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8AQuFHaWWUbJSXFTu62OQ_270.JPG: 480x640 (no detections), 301.7ms
Speed: 1.7ms preprocess, 301.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8Adlw-Zz3dFV7XA6RbcPA_0.JPG: 480x640 (no detections), 298.5ms
Speed: 1.4ms preprocess, 298.5ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8Adlw-Zz3dFV7XA6RbcPA_90.JPG: 480x640 (no detections), 296.7ms
Speed: 1.2ms preprocess, 296.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8Adlw-Zz3dFV7XA6RbcPA_180.JPG: 480x640 (no detections), 298.9ms
Speed: 1.1ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8Adlw-Zz3dFV7XA6RbcPA_270.JPG: 480x640 (no detections), 303.1ms
Speed: 1.3ms preprocess, 303.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8B4tlMUdR8cmiGax_1WTw_0.JPG: 480x640 (no detections), 308.0ms
Speed: 1.2ms preprocess, 308.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8B4tlMUdR8cmiGax_1WTw_90.JPG: 480x640 (no detections), 301.1ms
Speed: 1.4ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8B4tlMUdR8cmiGax_1WTw_180.JPG: 480x640 (no detections), 302.4ms
Speed: 1.2ms preprocess, 302.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8B4tlMUdR8cmiGax_1WTw_270.JPG: 480x640 (no detections), 305.2ms
Speed: 1.1ms preprocess, 305.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8DNQanYpwsH9EMlNGkjeA_0.JPG: 480x640 (no detections), 311.6ms
Speed: 1.0ms preprocess, 311.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8DNQanYpwsH9EMlNGkjeA_90.JPG: 480x640 (no detections), 322.7ms
Speed: 1.3ms preprocess, 322.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8DNQanYpwsH9EMlNGkjeA_180.JPG: 480x640 (no detections), 314.2ms
Speed: 1.2ms preprocess, 314.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8DNQanYpwsH9EMlNGkjeA_270.JPG: 480x640 (no detections), 406.3ms
Speed: 1.1ms preprocess, 406.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8G7nkTrzpHLGeHjPrhF7g_0.JPG: 480x640 (no detections), 304.1ms
Speed: 1.2ms preprocess, 304.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8G7nkTrzpHLGeHjPrhF7g_90.JPG: 480x640 (no detections), 296.9ms
Speed: 1.2ms preprocess, 296.9ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8G7nkTrzpHLGeHjPrhF7g_180.JPG: 480x640 (no detections), 309.8ms
Speed: 1.0ms preprocess, 309.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8G7nkTrzpHLGeHjPrhF7g_270.JPG: 480x640 (no detections), 304.9ms
Speed: 1.4ms preprocess, 304.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8Gmastvgccz1UyXnvLxZQ_0.JPG: 480x640 (no detections), 306.1ms
Speed: 1.0ms preprocess, 306.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8Gmastvgccz1UyXnvLxZQ_90.JPG: 480x640 (no detections), 308.0ms
Speed: 1.1ms preprocess, 308.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8Gmastvgccz1UyXnvLxZQ_180.JPG: 480x640 (no detections), 300.8ms
Speed: 1.3ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8Gmastvgccz1UyXnvLxZQ_270.JPG: 480x640 (no detections), 302.9ms
Speed: 1.2ms preprocess, 302.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8HO6kikVDzgnnA3Z24slw_0.JPG: 480x640 (no detections), 301.2ms
Speed: 1.3ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8HO6kikVDzgnnA3Z24slw_90.JPG: 480x640 (no detections), 300.8ms
Speed: 1.4ms preprocess, 300.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8HO6kikVDzgnnA3Z24slw_180.JPG: 480x640 (no detections), 294.2ms
Speed: 1.1ms preprocess, 294.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8HO6kikVDzgnnA3Z24slw_270.JPG: 480x640 (no detections), 297.3ms
Speed: 1.2ms preprocess, 297.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8HT2LzjeSe6aA5DsKKbyw_0.JPG: 480x640 (no detections), 300.5ms
Speed: 1.3ms preprocess, 300.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8HT2LzjeSe6aA5DsKKbyw_90.JPG: 480x640 (no detections), 300.6ms
Speed: 1.2ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8HT2LzjeSe6aA5DsKKbyw_180.JPG: 480x640 (no detections), 301.4ms
Speed: 1.1ms preprocess, 301.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8HT2LzjeSe6aA5DsKKbyw_270.JPG: 480x640 (no detections), 303.9ms
Speed: 1.1ms preprocess, 303.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8JI7PKyx6P8Yw3uwlkgbw_0.JPG: 480x640 (no detections), 302.5ms
Speed: 1.1ms preprocess, 302.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8JI7PKyx6P8Yw3uwlkgbw_90.JPG: 480x640 (no detections), 300.1ms
Speed: 1.7ms preprocess, 300.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8JI7PKyx6P8Yw3uwlkgbw_180.JPG: 480x640 (no detections), 309.0ms
Speed: 1.1ms preprocess, 309.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8JI7PKyx6P8Yw3uwlkgbw_270.JPG: 480x640 (no detections), 301.5ms
Speed: 1.0ms preprocess, 301.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8KReRjvINfsulJ-JawFcA_0.JPG: 480x640 (no detections), 302.4ms

Speed: 1.7ms preprocess, 302.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8KReRjvINfsulJ-JawFcA_90.JPG: 480x640 (no detections), 300.5ms
Speed: 1.3ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8KReRjvINfsulJ-JawFcA_180.JPG: 480x640 (no detections), 300.8ms
Speed: 1.1ms preprocess, 300.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8KReRjvINfsulJ-JawFcA_270.JPG: 480x640 (no detections), 295.6ms
Speed: 1.4ms preprocess, 295.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8Ka-o9B5753hWl-Wbc_dg_0.JPG: 480x640 (no detections), 297.8ms
Speed: 1.1ms preprocess, 297.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8Ka-o9B5753hWl-Wbc_dg_90.JPG: 480x640 (no detections), 298.6ms
Speed: 1.2ms preprocess, 298.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8Ka-o9B5753hWl-Wbc_dg_180.JPG: 480x640 (no detections), 302.7ms
Speed: 1.1ms preprocess, 302.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8Ka-o9B5753hWl-Wbc_dg_270.JPG: 480x640 (no detections), 301.9ms
Speed: 1.1ms preprocess, 301.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8NgxXam5wcWlRGrNg_rDQ_0.JPG: 480x640 (no detections), 305.2ms
Speed: 1.3ms preprocess, 305.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8NgxXam5wcWlRGrNg_rDQ_90.JPG: 480x640 (no detections), 301.1ms
Speed: 1.1ms preprocess, 301.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8NgxXam5wcWlRGrNg_rDQ_180.JPG: 480x640 (no detections), 298.3ms
Speed: 1.3ms preprocess, 298.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8NgxXam5wcWlRGrNg_rDQ_270.JPG: 480x640 (no detections), 301.2ms
Speed: 1.2ms preprocess, 301.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8PdpdHzKsYq21AVd96V-g_0.JPG: 480x640 (no detections), 302.4ms
Speed: 1.1ms preprocess, 302.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8PdpdHzKsYq21AVd96V-g_90.JPG: 480x640 (no detections), 301.6ms
Speed: 1.1ms preprocess, 301.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8PdpdHzKsYq21AVd96V-g_180.JPG: 480x640 (no detections), 302.3ms
Speed: 1.2ms preprocess, 302.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8PdpdHzKsYq21AVd96V-g_270.JPG: 480x640 (no detections), 305.6ms
Speed: 1.2ms preprocess, 305.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8RHHQkDsKiuWkQrYgj-Uw_0.JPG: 480x640 (no detections), 304.1ms
Speed: 1.3ms preprocess, 304.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8RHHQkDsKiuWkQrYgj-Uw_90.JPG: 480x640 (no detections), 297.7ms
Speed: 1.4ms preprocess, 297.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8RHHQkDsKiuWkQrYgj-Uw_180.JPG: 480x640 (no detections), 301.5ms
Speed: 1.3ms preprocess, 301.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8RHHQkDsKiuWkQrYgj-Uw_270.JPG: 480x640 (no detections), 302.6ms
Speed: 1.6ms preprocess, 302.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8RckhUVgRBWQ-6fr-4h9w_0.JPG: 480x640 (no detections), 299.7ms
Speed: 1.1ms preprocess, 299.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8RckhUVgRBWQ-6fr-4h9w_90.JPG: 480x640 (no detections), 303.1ms
Speed: 1.3ms preprocess, 303.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8RckhUVgRBWQ-6fr-4h9w_180.JPG: 480x640 1 Waste, 299.6ms
Speed: 1.6ms preprocess, 299.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8RckhUVgRBWQ-6fr-4h9w_270.JPG: 480x640 (no detections), 296.7ms
Speed: 1.3ms preprocess, 296.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8W-hmq8NL00wXUI4lOg6g_0.JPG: 480x640 (no detections), 303.9ms
Speed: 1.2ms preprocess, 303.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8W-hmq8NL00wXUI4lOg6g_90.JPG: 480x640 1 Waste, 298.5ms
Speed: 1.1ms preprocess, 298.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8W-hmq8NL00wXUI4lOg6g_180.JPG: 480x640 (no detections), 298.5ms
Speed: 1.1ms preprocess, 298.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8W-hmq8NL00wXUI4lOg6g_270.JPG: 480x640 (no detections), 297.5ms
Speed: 1.1ms preprocess, 297.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8W428g2OQgW64vc6GoPOA_0.JPG: 480x640 (no detections), 307.6ms
Speed: 1.4ms preprocess, 307.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8W428g2OQgW64vc6GoPOA_90.JPG: 480x640 (no detections), 299.6ms
Speed: 1.9ms preprocess, 299.6ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8W428g2OQgW64vc6GoPOA_180.JPG: 480x640 1 Waste, 300.5ms
Speed: 1.3ms preprocess, 300.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8W428g2OQgW64vc6GoPOA_270.JPG: 480x640 (no detections), 295.7ms
Speed: 1.1ms preprocess, 295.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8WJSnSxEJDADijZWx3BYA_0.JPG: 480x640 (no detections), 306.8ms
Speed: 1.7ms preprocess, 306.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8WJSnSxEJDADijZWx3BYA_90.JPG: 480x640 (no detections), 307.4ms
Speed: 1.2ms preprocess, 307.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8WJSnSxEJDADijZWx3BYA_180.JPG: 480x640 1 Waste, 301.8ms
Speed: 1.1ms preprocess, 301.8ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8WJSnSxEJDADijZWx3BYA_270.JPG: 480x640 1 Waste, 302.4ms
Speed: 1.5ms preprocess, 302.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8ZBSKhHKB5vhgCgsp6axg_0.JPG: 480x640 (no detections), 305.1ms
Speed: 1.3ms preprocess, 305.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8ZBSKhHKB5vhgCgsp6axg_90.JPG: 480x640 (no detections), 321.4ms
Speed: 1.4ms preprocess, 321.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8ZBSKhHKB5vhgCgsp6axg_180.JPG: 480x640 (no detections), 295.0ms
Speed: 1.3ms preprocess, 295.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8ZBSKhHKB5vhgCgsp6axg_270.JPG: 480x640 (no detections), 307.6ms
Speed: 1.0ms preprocess, 307.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8bDliOUxR_Kwk6DJoubMQ_0.JPG: 480x640 (no detections), 303.6ms
Speed: 1.1ms preprocess, 303.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8bDliOUxR_Kwk6DJoubMQ_90.JPG: 480x640 (no detections), 302.6ms
Speed: 1.3ms preprocess, 302.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8bDliOUxR_Kwk6DJoubMQ_180.JPG: 480x640 (no detections), 308.2ms
Speed: 1.1ms preprocess, 308.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8bDliOUxR_Kwk6DJoubMQ_270.JPG: 480x640 (no detections), 309.1ms
Speed: 1.4ms preprocess, 309.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8gB2_Klui2ET4gCZsZVug_0.JPG: 480x640 (no detections), 303.0ms
Speed: 1.3ms preprocess, 303.0ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8gB2_Klui2ET4gCZsZVug_90.JPG: 480x640 (no detections), 309.2ms
Speed: 1.2ms preprocess, 309.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8gB2_Klui2ET4gCZsZVug_180.JPG: 480x640 (no detections), 376.5ms
Speed: 1.3ms preprocess, 376.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8gB2_Klui2ET4gCZsZVug_270.JPG: 480x640 (no detections), 374.7ms
Speed: 1.6ms preprocess, 374.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8hbNzd4amIrmZkpbpWZIA_0.JPG: 480x640 (no detections), 312.6ms
Speed: 2.1ms preprocess, 312.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8hbNzd4amIrmZkpbpWZIA_90.JPG: 480x640 (no detections), 312.0ms
Speed: 1.3ms preprocess, 312.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8hbNzd4amIrmZkpbpWZIA_180.JPG: 480x640 (no detections), 304.8ms
Speed: 1.3ms preprocess, 304.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8hbNzd4amIrmZkpbpWZIA_270.JPG: 480x640 (no detections), 295.5ms
Speed: 1.2ms preprocess, 295.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8k5qZ7HmVWhTv55LsnrKQ_0.JPG: 480x640 (no detections), 303.1ms
Speed: 1.2ms preprocess, 303.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8k5qZ7HmVWhTv55LsnrKQ_90.JPG: 480x640 (no detections), 307.8ms
Speed: 1.3ms preprocess, 307.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8k5qZ7HmVWhTv55LsnrKQ_180.JPG: 480x640 (no detections), 303.1ms
Speed: 1.3ms preprocess, 303.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8k5qZ7HmVWhTv55LsnrKQ_270.JPG: 480x640 (no detections), 296.7ms
Speed: 1.4ms preprocess, 296.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8l7Cj4IsXZAubXZ4Rb15Q_0.JPG: 480x640 (no detections), 298.6ms
Speed: 1.2ms preprocess, 298.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8l7Cj4IsXZAubXZ4Rb15Q_90.JPG: 480x640 (no detections), 301.2ms
Speed: 1.2ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8l7Cj4IsXZAubXZ4Rb15Q_180.JPG: 480x640 (no detections), 305.3ms
Speed: 1.9ms preprocess, 305.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8l7Cj4IsXZAubXZ4Rb15Q_270.JPG: 480x640 (no detections), 298.9ms
Speed: 1.2ms preprocess, 298.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8oErAQM-aNoFqmxXXEIZQ_0.JPG: 480x640 (no detections), 305.9ms
Speed: 1.3ms preprocess, 305.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8oErAQM-aNoFqmxXXEIZQ_90.JPG: 480x640 (no detections), 304.0ms
Speed: 1.1ms preprocess, 304.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8oErAQM-aNoFqmxXXEIZQ_180.JPG: 480x640 (no detections), 303.9ms
Speed: 1.2ms preprocess, 303.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8oErAQM-aNoFqmxXXEIZQ_270.JPG: 480x640 (no detections), 313.5ms
Speed: 1.3ms preprocess, 313.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8pDLP66C9bTWvp-SG3Atw_0.JPG: 480x640 (no detections), 302.4ms
Speed: 1.0ms preprocess, 302.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8pDLP66C9bTWvp-SG3Atw_90.JPG: 480x640 (no detections), 301.6ms
Speed: 1.2ms preprocess, 301.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8pDLP66C9bTWvp-SG3Atw_180.JPG: 480x640 (no detections), 309.7ms
Speed: 1.5ms preprocess, 309.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8pDLP66C9bTWvp-SG3Atw_270.JPG: 480x640 (no detections), 312.7ms

Speed: 1.1ms preprocess, 312.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8q9qIW3eVKfK2rpq5nIKA_0.JPG: 480x640 (no detections), 309.1ms
Speed: 1.3ms preprocess, 309.1ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8q9qIW3eVKfK2rpq5nIKA_90.JPG: 480x640 (no detections), 300.9ms
Speed: 1.3ms preprocess, 300.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8q9qIW3eVKfK2rpq5nIKA_180.JPG: 480x640 (no detections), 302.5ms
Speed: 1.3ms preprocess, 302.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8q9qIW3eVKfK2rpq5nIKA_270.JPG: 480x640 (no detections), 301.5ms
Speed: 1.4ms preprocess, 301.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8qJGn-ZgwQM8Dq_aue2uw_0.JPG: 480x640 (no detections), 300.8ms
Speed: 1.2ms preprocess, 300.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8qJGn-ZgwQM8Dq_aue2uw_90.JPG: 480x640 (no detections), 303.1ms
Speed: 1.1ms preprocess, 303.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8qJGn-ZgwQM8Dq_aue2uw_180.JPG: 480x640 (no detections), 300.4ms
Speed: 1.1ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8qJGn-ZgwQM8Dq_aue2uw_270.JPG: 480x640 (no detections), 298.5ms
Speed: 1.3ms preprocess, 298.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8qLjJxaL3aQClPDGRgdeg_0.JPG: 480x640 (no detections), 304.7ms
Speed: 1.1ms preprocess, 304.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8qLjJxaL3aQClPDGRgdeg_90.JPG: 480x640 (no detections), 302.6ms
Speed: 1.1ms preprocess, 302.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8qLjJxaL3aQClPDGRgdeg_180.JPG: 480x640 (no detections), 303.0ms
Speed: 1.5ms preprocess, 303.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8qLjJxaL3aQClPDGRgdeg_270.JPG: 480x640 (no detections), 304.7ms
Speed: 1.5ms preprocess, 304.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8uK412X7BiW5ZsZDMmgIg_0.JPG: 480x640 (no detections), 320.9ms
Speed: 1.1ms preprocess, 320.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8uK412X7BiW5ZsZDMmgIg_90.JPG: 480x640 (no detections), 352.1ms
Speed: 1.4ms preprocess, 352.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8uK412X7BiW5ZsZDMmgIg_180.JPG: 480x640 (no detections), 328.0ms
Speed: 1.1ms preprocess, 328.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8uK412X7BiW5ZsZDMmgIg_270.JPG: 480x640 (no detections), 352.0ms
Speed: 1.2ms preprocess, 352.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8y-GCMNV_ltcavpN-Ee7A_0.JPG: 480x640 (no detections), 334.1ms
Speed: 1.2ms preprocess, 334.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8y-GCMNV_ltcavpN-Ee7A_90.JPG: 480x640 (no detections), 315.3ms
Speed: 1.2ms preprocess, 315.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8y-GCMNV_ltcavpN-Ee7A_180.JPG: 480x640 (no detections), 329.1ms
Speed: 1.1ms preprocess, 329.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8y-GCMNV_ltcavpN-Ee7A_270.JPG: 480x640 (no detections), 295.5ms
Speed: 1.5ms preprocess, 295.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8zYeprs9UuYDbaqoqkcTg_0.JPG: 480x640 (no detections), 306.7ms
Speed: 1.1ms preprocess, 306.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8zYeprs9UuYDbaqoqkcTg_90.JPG: 480x640 (no detections), 297.5ms
Speed: 1.8ms preprocess, 297.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8zYeprs9UuYDbaqoqkcTg_180.JPG: 480x640 (no detections), 302.4ms
Speed: 1.2ms preprocess, 302.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/8/y8zYeprs9UuYDbaqoqkcTg_270.JPG: 480x640 (no detections), 302.3ms
Speed: 1.1ms preprocess, 302.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9-XNJwNlBUXZ3Zo6qiLPw_0.JPG: 480x640 (no detections), 295.9ms
Speed: 1.2ms preprocess, 295.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9-XNJwNlBUXZ3Zo6qiLPw_90.JPG: 480x640 (no detections), 299.5ms
Speed: 1.2ms preprocess, 299.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9-XNJwNlBUXZ3Zo6qiLPw_180.JPG: 480x640 (no detections), 298.5ms
Speed: 1.2ms preprocess, 298.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9-XNJwNlBUXZ3Zo6qiLPw_270.JPG: 480x640 (no detections), 301.1ms
Speed: 1.2ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y90-Ia_M--CsA3cxOL67Mg_0.JPG: 480x640 (no detections), 301.6ms
Speed: 1.1ms preprocess, 301.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y90-Ia_M--CsA3cxOL67Mg_90.JPG: 480x640 (no detections), 296.3ms
Speed: 1.1ms preprocess, 296.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y90-Ia_M--CsA3cxOL67Mg_180.JPG: 480x640 (no detections), 297.5ms
Speed: 1.3ms preprocess, 297.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y90-Ia_M--CsA3cxOL67Mg_270.JPG: 480x640 (no detections), 302.9ms
Speed: 1.1ms preprocess, 302.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y93yE_dG012qvTMHcTtung_0.JPG: 480x640 (no detections), 299.5ms
Speed: 1.2ms preprocess, 299.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y93yE_dG012qvTMHcTtung_90.JPG: 480x640 (no detections), 308.1ms
Speed: 1.5ms preprocess, 308.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y93yE_dG012qvTMHcTtung_180.JPG: 480x640 (no detections), 297.9ms
Speed: 1.2ms preprocess, 297.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y93yE_dG012qvTMHcTtung_270.JPG: 480x640 (no detections), 298.8ms
Speed: 1.1ms preprocess, 298.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9A-jTL9_qDDPJh7c1xNfw_0.JPG: 480x640 (no detections), 301.3ms
Speed: 1.1ms preprocess, 301.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9A-jTL9_qDDPJh7c1xNfw_90.JPG: 480x640 (no detections), 298.3ms
Speed: 1.2ms preprocess, 298.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9A-jTL9_qDDPJh7c1xNfw_180.JPG: 480x640 (no detections), 304.5ms
Speed: 1.1ms preprocess, 304.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9A-jTL9_qDDPJh7c1xNfw_270.JPG: 480x640 (no detections), 298.3ms
Speed: 1.3ms preprocess, 298.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9Gx1AY5ZAv40Tstn1Q-tQ_0.JPG: 480x640 (no detections), 303.5ms
Speed: 1.1ms preprocess, 303.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9Gx1AY5ZAv40Tstn1Q-tQ_90.JPG: 480x640 (no detections), 308.2ms
Speed: 1.1ms preprocess, 308.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9Gx1AY5ZAv40Tstn1Q-tQ_180.JPG: 480x640 (no detections), 304.9ms
Speed: 1.1ms preprocess, 304.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9Gx1AY5ZAv40Tstn1Q-tQ_270.JPG: 480x640 (no detections), 298.4ms
Speed: 1.3ms preprocess, 298.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9HLFHZC8P07uo5ioXp9ag_0.JPG: 480x640 (no detections), 300.1ms
Speed: 1.2ms preprocess, 300.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9HLFHZC8P07uo5ioXp9ag_90.JPG: 480x640 (no detections), 303.5ms
Speed: 1.1ms preprocess, 303.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9HLFHZC8P07uo5ioXp9ag_180.JPG: 480x640 (no detections), 303.4ms
Speed: 1.0ms preprocess, 303.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9HLFHZC8P07uo5ioXp9ag_270.JPG: 480x640 (no detections), 303.9ms
Speed: 1.1ms preprocess, 303.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9J_KP6Z5ZsCGz27i4Enaw_0.JPG: 480x640 (no detections), 302.9ms
Speed: 1.2ms preprocess, 302.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9J_KP6Z5ZsCGz27i4Enaw_90.JPG: 480x640 (no detections), 302.7ms
Speed: 1.2ms preprocess, 302.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9J_KP6Z5ZsCGz27i4Enaw_180.JPG: 480x640 (no detections), 304.5ms
Speed: 1.3ms preprocess, 304.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9J_KP6Z5ZsCGz27i4Enaw_270.JPG: 480x640 (no detections), 307.0ms
Speed: 1.3ms preprocess, 307.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9N5W6tiaI66Z2litmZPlA_0.JPG: 480x640 (no detections), 302.8ms
Speed: 1.1ms preprocess, 302.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9N5W6tiaI66Z2litmZPlA_90.JPG: 480x640 1 Waste, 306.3ms
Speed: 1.1ms preprocess, 306.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9N5W6tiaI66Z2litmZPlA_180.JPG: 480x640 3 Wastes, 301.4ms
Speed: 1.2ms preprocess, 301.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9N5W6tiaI66Z2litmZPlA_270.JPG: 480x640 1 Waste, 304.0ms
Speed: 1.1ms preprocess, 304.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9QoCrVid3WBKPaMiXRogg_0.JPG: 480x640 (no detections), 306.0ms
Speed: 1.3ms preprocess, 306.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9QoCrVid3WBKPaMiXRogg_90.JPG: 480x640 (no detections), 300.8ms
Speed: 1.2ms preprocess, 300.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9QoCrVid3WBKPaMiXRogg_180.JPG: 480x640 (no detections), 297.0ms
Speed: 1.2ms preprocess, 297.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9QoCrVid3WBKPaMiXRogg_270.JPG: 480x640 (no detections), 309.3ms
Speed: 1.3ms preprocess, 309.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9T-YPwhOyckmmhTPYHYOg_0.JPG: 480x640 (no detections), 300.4ms
Speed: 1.2ms preprocess, 300.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9T-YPwhOyckmmhTPYHYOg_90.JPG: 480x640 (no detections), 305.8ms
Speed: 1.4ms preprocess, 305.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9T-YPwhOyckmmhTPYHYOg_180.JPG: 480x640 (no detections), 300.4ms
Speed: 1.1ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9T-YPwhOyckmmhTPYHYOg_270.JPG: 480x640 (no detections), 301.7ms
Speed: 1.1ms preprocess, 301.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9TaU0m4Il_pPOhrhY0yFw_0.JPG: 480x640 (no detections), 298.3ms
Speed: 1.1ms preprocess, 298.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9TaU0m4Il_pPOhrhY0yFw_90.JPG: 480x640 (no detections), 305.2ms
Speed: 1.0ms preprocess, 305.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9TaU0m4Il_pPOhrhY0yFw_180.JPG: 480x640 (no detections), 302.3ms

Speed: 1.2ms preprocess, 302.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9TaU0m4Il_pPOhrhY0yFw_270.JPG: 480x640 (no detections), 302.6ms
Speed: 1.1ms preprocess, 302.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9dUVGpsL0XNOrRR8oedDA_0.JPG: 480x640 (no detections), 302.3ms
Speed: 1.2ms preprocess, 302.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9dUVGpsL0XNOrRR8oedDA_90.JPG: 480x640 (no detections), 298.6ms
Speed: 1.6ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9dUVGpsL0XNOrRR8oedDA_180.JPG: 480x640 (no detections), 300.5ms
Speed: 1.9ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9dUVGpsL0XNOrRR8oedDA_270.JPG: 480x640 (no detections), 302.2ms
Speed: 1.2ms preprocess, 302.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9g5MOpD1UwiiVFrHSgm2w_0.JPG: 480x640 (no detections), 307.7ms
Speed: 1.2ms preprocess, 307.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9g5MOpD1UwiiVFrHSgm2w_90.JPG: 480x640 (no detections), 305.4ms
Speed: 1.2ms preprocess, 305.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9g5MOpD1UwiiVFrHSgm2w_180.JPG: 480x640 (no detections), 302.3ms
Speed: 1.3ms preprocess, 302.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9g5MOpD1UwiiVFrHSgm2w_270.JPG: 480x640 (no detections), 302.2ms
Speed: 1.3ms preprocess, 302.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9hBxkW_BOh5_WcCLoPq1w_0.JPG: 480x640 (no detections), 304.1ms
Speed: 1.2ms preprocess, 304.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9hBxkW_BOh5_WcCLoPq1w_90.JPG: 480x640 (no detections), 302.6ms
Speed: 1.3ms preprocess, 302.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9hBxkW_BOh5_WcCLoPq1w_180.JPG: 480x640 (no detections), 299.7ms
Speed: 1.3ms preprocess, 299.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9hBxkW_BOh5_WcCLoPq1w_270.JPG: 480x640 (no detections), 306.8ms
Speed: 1.7ms preprocess, 306.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9hoaQqOMek6K-mLS6SkNg_0.JPG: 480x640 (no detections), 306.7ms
Speed: 1.2ms preprocess, 306.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9hoaQqOMek6K-mLS6SkNg_90.JPG: 480x640 (no detections), 307.4ms
Speed: 1.9ms preprocess, 307.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9hoaQqOMek6K-mLS6SkNg_180.JPG: 480x640 (no detections), 301.0ms
Speed: 1.1ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9hoaQqOMek6K-mLS6SkNg_270.JPG: 480x640 (no detections), 300.6ms
Speed: 1.8ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9iP0s8iVk1R5N7F5VwrwQ_0.JPG: 480x640 (no detections), 304.6ms
Speed: 1.2ms preprocess, 304.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9iP0s8iVk1R5N7F5VwrwQ_90.JPG: 480x640 (no detections), 309.9ms
Speed: 1.5ms preprocess, 309.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9iP0s8iVk1R5N7F5VwrwQ_180.JPG: 480x640 (no detections), 304.7ms
Speed: 1.8ms preprocess, 304.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9iP0s8iVk1R5N7F5VwrwQ_270.JPG: 480x640 (no detections), 299.2ms
Speed: 1.1ms preprocess, 299.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9tsTB3qs2ymBIiUJtavPQ_0.JPG: 480x640 (no detections), 300.9ms
Speed: 1.3ms preprocess, 300.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9tsTB3qs2ymBIiUJtavPQ_90.JPG: 480x640 (no detections), 310.5ms
Speed: 1.3ms preprocess, 310.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9tsTB3qs2ymBIiUJtavPQ_180.JPG: 480x640 (no detections), 303.2ms
Speed: 1.1ms preprocess, 303.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9tsTB3qs2ymBIiUJtavPQ_270.JPG: 480x640 1 Waste, 300.5ms
Speed: 1.1ms preprocess, 300.5ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9uQT8QebfxjDZ5mXbWALg_0.JPG: 480x640 (no detections), 303.7ms
Speed: 1.4ms preprocess, 303.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9uQT8QebfxjDZ5mXbWALg_90.JPG: 480x640 (no detections), 305.4ms
Speed: 1.1ms preprocess, 305.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9uQT8QebfxjDZ5mXbWALg_180.JPG: 480x640 (no detections), 302.6ms
Speed: 1.3ms preprocess, 302.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9uQT8QebfxjDZ5mXbWALg_270.JPG: 480x640 (no detections), 302.1ms
Speed: 1.1ms preprocess, 302.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9vwcXd2ALOVkFMAhTsJMg_0.JPG: 480x640 (no detections), 302.3ms
Speed: 1.3ms preprocess, 302.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9vwcXd2ALOVkFMAhTsJMg_90.JPG: 480x640 (no detections), 301.5ms
Speed: 1.3ms preprocess, 301.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9vwcXd2ALOVkFMAhTsJMg_180.JPG: 480x640 (no detections), 300.7ms
Speed: 1.1ms preprocess, 300.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9vwcXd2ALOVkFMAhTsJMg_270.JPG: 480x640 (no detections), 305.5ms
Speed: 1.3ms preprocess, 305.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9wgstxYePCLQ90x_2tP-w_0.JPG: 480x640 (no detections), 299.9ms
Speed: 1.3ms preprocess, 299.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9wgstxYePCLQ90x_2tP-w_90.JPG: 480x640 (no detections), 299.9ms
Speed: 1.2ms preprocess, 299.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9wgstxYePCLQ90x_2tP-w_180.JPG: 480x640 (no detections), 305.2ms
Speed: 1.4ms preprocess, 305.2ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9wgstxYePCLQ90x_2tP-w_270.JPG: 480x640 1 Waste, 297.9ms
Speed: 1.3ms preprocess, 297.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9xRdnE2jqf2Hl8fSFyAWw_0.JPG: 480x640 (no detections), 304.3ms
Speed: 1.3ms preprocess, 304.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9xRdnE2jqf2Hl8fSFyAWw_90.JPG: 480x640 (no detections), 303.0ms
Speed: 1.1ms preprocess, 303.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9xRdnE2jqf2Hl8fSFyAWw_180.JPG: 480x640 (no detections), 305.3ms
Speed: 1.1ms preprocess, 305.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9xRdnE2jqf2Hl8fSFyAWw_270.JPG: 480x640 (no detections), 302.4ms
Speed: 1.2ms preprocess, 302.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9yTRXgGEq9UMnph7Xs2ag_0.JPG: 480x640 (no detections), 299.3ms
Speed: 1.3ms preprocess, 299.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9yTRXgGEq9UMnph7Xs2ag_90.JPG: 480x640 (no detections), 315.8ms
Speed: 1.1ms preprocess, 315.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9yTRXgGEq9UMnph7Xs2ag_180.JPG: 480x640 (no detections), 299.1ms
Speed: 1.1ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9yTRXgGEq9UMnph7Xs2ag_270.JPG: 480x640 (no detections), 309.8ms
Speed: 1.2ms preprocess, 309.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9z6mUP3ENRXIf2wLxYxVg_0.JPG: 480x640 (no detections), 306.3ms
Speed: 1.5ms preprocess, 306.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9z6mUP3ENRXIf2wLxYxVg_90.JPG: 480x640 (no detections), 312.3ms
Speed: 1.8ms preprocess, 312.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9z6mUP3ENRXIf2wLxYxVg_180.JPG: 480x640 (no detections), 310.3ms
Speed: 1.2ms preprocess, 310.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9z6mUP3ENRXIf2wLxYxVg_270.JPG: 480x640 (no detections), 300.4ms
Speed: 1.1ms preprocess, 300.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9zkZKc4RrEcxLkHx6wPqw_0.JPG: 480x640 (no detections), 299.4ms
Speed: 1.3ms preprocess, 299.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9zkZKc4RrEcxLkHx6wPqw_90.JPG: 480x640 (no detections), 300.8ms
Speed: 1.2ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9zkZKc4RrEcxLkHx6wPqw_180.JPG: 480x640 (no detections), 302.8ms
Speed: 1.1ms preprocess, 302.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/9/y9zkZKc4RrEcxLkHx6wPqw_270.JPG: 480x640 (no detections), 302.8ms
Speed: 1.0ms preprocess, 302.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yA-Vt_Y30GER9Exk6H-_Iw_0.JPG: 480x640 (no detections), 298.9ms
Speed: 1.2ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yA-Vt_Y30GER9Exk6H-_Iw_90.JPG: 480x640 (no detections), 307.7ms
Speed: 1.3ms preprocess, 307.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yA-Vt_Y30GER9Exk6H-_Iw_180.JPG: 480x640 (no detections), 305.5ms
Speed: 1.2ms preprocess, 305.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yA-Vt_Y30GER9Exk6H-_Iw_270.JPG: 480x640 (no detections), 301.7ms
Speed: 1.9ms preprocess, 301.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yA0SuA0YkE98iDslsceRLA_0.JPG: 480x640 (no detections), 300.5ms
Speed: 1.2ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yA0SuA0YkE98iDslsceRLA_90.JPG: 480x640 (no detections), 303.9ms
Speed: 1.2ms preprocess, 303.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yA0SuA0YkE98iDslsceRLA_180.JPG: 480x640 (no detections), 300.7ms
Speed: 1.2ms preprocess, 300.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yA0SuA0YkE98iDslsceRLA_270.JPG: 480x640 (no detections), 298.8ms
Speed: 1.1ms preprocess, 298.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yA3OYAvTcMCOGtr8jSxXNw_0.JPG: 480x640 (no detections), 307.8ms
Speed: 1.4ms preprocess, 307.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yA3OYAvTcMCOGtr8jSxXNw_90.JPG: 480x640 (no detections), 300.1ms
Speed: 1.2ms preprocess, 300.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yA3OYAvTcMCOGtr8jSxXNw_180.JPG: 480x640 (no detections), 297.2ms
Speed: 1.2ms preprocess, 297.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yA3OYAvTcMCOGtr8jSxXNw_270.JPG: 480x640 (no detections), 302.0ms
Speed: 1.0ms preprocess, 302.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yA4QF5lb0ZQrRZJNb0v91w_0.JPG: 480x640 (no detections), 303.4ms
Speed: 1.2ms preprocess, 303.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yA4QF5lb0ZQrRZJNb0v91w_90.JPG: 480x640 (no detections), 300.9ms

Speed: 1.2ms preprocess, 300.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yA4QF5lb0ZQrRZJNb0v91w_180.JPG: 480x640 (no detections), 302.3ms
Speed: 1.0ms preprocess, 302.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yA4QF5lb0ZQrRZJNb0v91w_270.JPG: 480x640 1 Waste, 302.1ms
Speed: 1.2ms preprocess, 302.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yA6qBGVeWHVsEf2mlr0s6A_0.JPG: 480x640 (no detections), 306.9ms
Speed: 1.2ms preprocess, 306.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yA6qBGVeWHVsEf2mlr0s6A_90.JPG: 480x640 (no detections), 307.1ms
Speed: 1.1ms preprocess, 307.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yA6qBGVeWHVsEf2mlr0s6A_180.JPG: 480x640 (no detections), 309.7ms
Speed: 1.4ms preprocess, 309.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yA6qBGVeWHVsEf2mlr0s6A_270.JPG: 480x640 (no detections), 300.7ms
Speed: 1.2ms preprocess, 300.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yA8lKzHZTse-sAdigSQcww_0.JPG: 480x640 (no detections), 301.5ms
Speed: 1.2ms preprocess, 301.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yA8lKzHZTse-sAdigSQcww_90.JPG: 480x640 (no detections), 301.7ms
Speed: 1.1ms preprocess, 301.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yA8lKzHZTse-sAdigSQcww_180.JPG: 480x640 (no detections), 300.1ms
Speed: 1.2ms preprocess, 300.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yA8lKzHZTse-sAdigSQcww_270.JPG: 480x640 (no detections), 295.3ms
Speed: 1.5ms preprocess, 295.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yA9muQWiD_Kgbn6qRu0M3A_0.JPG: 480x640 (no detections), 294.3ms
Speed: 1.3ms preprocess, 294.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yA9muQWiD_Kgbn6qRu0M3A_90.JPG: 480x640 (no detections), 297.4ms
Speed: 1.1ms preprocess, 297.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yA9muQWiD_Kgbn6qRu0M3A_180.JPG: 480x640 (no detections), 303.1ms
Speed: 1.3ms preprocess, 303.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yA9muQWiD_Kgbn6qRu0M3A_270.JPG: 480x640 (no detections), 298.4ms
Speed: 1.1ms preprocess, 298.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yA9z2rrRZ3ZSWxJS_pSJKQ_0.JPG: 480x640 (no detections), 299.8ms
Speed: 1.1ms preprocess, 299.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yA9z2rrRZ3ZSWxJS_pSJKQ_90.JPG: 480x640 (no detections), 296.9ms
Speed: 1.0ms preprocess, 296.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yA9z2rrRZ3ZSWxJS_pSJKQ_180.JPG: 480x640 (no detections), 302.5ms
Speed: 1.4ms preprocess, 302.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yA9z2rrRZ3ZSWxJS_pSJKQ_270.JPG: 480x640 (no detections), 307.7ms
Speed: 1.8ms preprocess, 307.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAAHdmXcT4HF_-SC4UWteA_0.JPG: 480x640 (no detections), 303.7ms
Speed: 1.2ms preprocess, 303.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAAHdmXcT4HF_-SC4UWteA_90.JPG: 480x640 (no detections), 299.8ms
Speed: 1.2ms preprocess, 299.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAAHdmXcT4HF_-SC4UWteA_180.JPG: 480x640 (no detections), 296.9ms
Speed: 1.0ms preprocess, 296.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAAHdmXcT4HF_-SC4UWteA_270.JPG: 480x640 (no detections), 300.7ms
Speed: 1.1ms preprocess, 300.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yACtw4ED8iawXkix2qXkcw_0.JPG: 480x640 (no detections), 316.8ms
Speed: 1.4ms preprocess, 316.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yACtw4ED8iawXkix2qXkcw_90.JPG: 480x640 (no detections), 299.4ms
Speed: 1.5ms preprocess, 299.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yACtw4ED8iawXkix2qXkcw_180.JPG: 480x640 (no detections), 300.6ms
Speed: 1.3ms preprocess, 300.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yACtw4ED8iawXkix2qXkcw_270.JPG: 480x640 (no detections), 302.9ms
Speed: 1.3ms preprocess, 302.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yADlpBvLpBHJQzk9CEtAaA_0.JPG: 480x640 (no detections), 292.8ms
Speed: 1.0ms preprocess, 292.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yADlpBvLpBHJQzk9CEtAaA_90.JPG: 480x640 (no detections), 296.7ms
Speed: 1.2ms preprocess, 296.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yADlpBvLpBHJQzk9CEtAaA_180.JPG: 480x640 (no detections), 295.9ms
Speed: 1.2ms preprocess, 295.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yADlpBvLpBHJQzk9CEtAaA_270.JPG: 480x640 (no detections), 287.8ms
Speed: 1.2ms preprocess, 287.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAFhNQ263hE-vuZgixUzLA_0.JPG: 480x640 (no detections), 298.7ms
Speed: 1.2ms preprocess, 298.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAFhNQ263hE-vuZgixUzLA_90.JPG: 480x640 (no detections), 301.2ms
Speed: 1.3ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAFhNQ263hE-vuZgixUzLA_180.JPG: 480x640 (no detections), 300.5ms
Speed: 1.3ms preprocess, 300.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAFhNQ263hE-vuZgixUzLA_270.JPG: 480x640 (no detections), 300.1ms
Speed: 1.1ms preprocess, 300.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAGniT5geS_5ehcfzQgRtg_0.JPG: 480x640 (no detections), 297.7ms
Speed: 1.1ms preprocess, 297.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAGniT5geS_5ehcfzQgRtg_90.JPG: 480x640 (no detections), 293.6ms
Speed: 1.4ms preprocess, 293.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAGniT5geS_5ehcfzQgRtg_180.JPG: 480x640 (no detections), 304.5ms
Speed: 1.2ms preprocess, 304.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAGniT5geS_5ehcfzQgRtg_270.JPG: 480x640 (no detections), 299.9ms
Speed: 1.2ms preprocess, 299.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAHvKnIahiG7GC2pPi3zGQ_0.JPG: 480x640 (no detections), 297.7ms
Speed: 1.3ms preprocess, 297.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAHvKnIahiG7GC2pPi3zGQ_90.JPG: 480x640 (no detections), 297.1ms
Speed: 1.1ms preprocess, 297.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAHvKnIahiG7GC2pPi3zGQ_180.JPG: 480x640 (no detections), 299.1ms
Speed: 1.0ms preprocess, 299.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAHvKnIahiG7GC2pPi3zGQ_270.JPG: 480x640 (no detections), 294.4ms
Speed: 1.2ms preprocess, 294.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yANW04LJRDh5NJqO-9WEew_0.JPG: 480x640 (no detections), 297.5ms
Speed: 1.3ms preprocess, 297.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yANW04LJRDh5NJqO-9WEew_90.JPG: 480x640 (no detections), 303.2ms
Speed: 1.2ms preprocess, 303.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yANW04LJRDh5NJqO-9WEew_180.JPG: 480x640 (no detections), 299.7ms
Speed: 1.1ms preprocess, 299.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yANW04LJRDh5NJqO-9WEew_270.JPG: 480x640 (no detections), 295.0ms
Speed: 1.1ms preprocess, 295.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yANsYsRuhALy7QER-O_bjg_0.JPG: 480x640 (no detections), 297.2ms
Speed: 1.1ms preprocess, 297.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yANsYsRuhALy7QER-O_bjg_90.JPG: 480x640 1 Waste, 314.2ms
Speed: 1.1ms preprocess, 314.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yANsYsRuhALy7QER-O_bjg_180.JPG: 480x640 (no detections), 294.4ms
Speed: 1.4ms preprocess, 294.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yANsYsRuhALy7QER-O_bjg_270.JPG: 480x640 (no detections), 293.7ms
Speed: 1.5ms preprocess, 293.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAWJ42TkUIWpzleZZJtTRQ_0.JPG: 480x640 (no detections), 295.7ms
Speed: 1.1ms preprocess, 295.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAWJ42TkUIWpzleZZJtTRQ_90.JPG: 480x640 (no detections), 297.4ms
Speed: 1.1ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAWJ42TkUIWpzleZZJtTRQ_180.JPG: 480x640 (no detections), 296.5ms
Speed: 1.2ms preprocess, 296.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAWJ42TkUIWpzleZZJtTRQ_270.JPG: 480x640 (no detections), 303.8ms
Speed: 1.4ms preprocess, 303.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAYiqYQU45SXowADsJ39fA_0.JPG: 480x640 (no detections), 296.0ms
Speed: 1.2ms preprocess, 296.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAYiqYQU45SXowADsJ39fA_90.JPG: 480x640 1 Waste, 299.0ms
Speed: 1.3ms preprocess, 299.0ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAYiqYQU45SXowADsJ39fA_180.JPG: 480x640 (no detections), 307.7ms
Speed: 1.0ms preprocess, 307.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAYiqYQU45SXowADsJ39fA_270.JPG: 480x640 (no detections), 311.4ms
Speed: 1.4ms preprocess, 311.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yA_IMhmdtwigdwDPmutqaA_0.JPG: 480x640 (no detections), 317.6ms
Speed: 1.1ms preprocess, 317.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yA_IMhmdtwigdwDPmutqaA_90.JPG: 480x640 (no detections), 319.5ms
Speed: 1.7ms preprocess, 319.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yA_IMhmdtwigdwDPmutqaA_180.JPG: 480x640 (no detections), 298.0ms
Speed: 1.5ms preprocess, 298.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yA_IMhmdtwigdwDPmutqaA_270.JPG: 480x640 (no detections), 305.6ms
Speed: 1.4ms preprocess, 305.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yA_fgPPOMts_kGZS8nFerQ_0.JPG: 480x640 (no detections), 315.5ms
Speed: 1.2ms preprocess, 315.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yA_fgPPOMts_kGZS8nFerQ_90.JPG: 480x640 (no detections), 300.3ms
Speed: 1.0ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yA_fgPPOMts_kGZS8nFerQ_180.JPG: 480x640 (no detections), 302.7ms
Speed: 1.3ms preprocess, 302.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yA_fgPPOMts_kGZS8nFerQ_270.JPG: 480x640 (no detections), 298.8ms
Speed: 1.4ms preprocess, 298.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAbWk2Xw-VSg_WqM5cT6lw_0.JPG: 480x640 (no detections), 301.4ms

Speed: 1.2ms preprocess, 301.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAbWk2Xw-VSg_WqM5cT6lw_90.JPG: 480x640 (no detections), 299.3ms
Speed: 1.3ms preprocess, 299.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAbWk2Xw-VSg_WqM5cT6lw_180.JPG: 480x640 (no detections), 298.2ms
Speed: 1.3ms preprocess, 298.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAbWk2Xw-VSg_WqM5cT6lw_270.JPG: 480x640 (no detections), 308.8ms
Speed: 1.4ms preprocess, 308.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAc0Ky7fy5HbNHLVvMPLiQ_0.JPG: 480x640 (no detections), 295.6ms
Speed: 1.2ms preprocess, 295.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAc0Ky7fy5HbNHLVvMPLiQ_90.JPG: 480x640 (no detections), 297.6ms
Speed: 1.2ms preprocess, 297.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAc0Ky7fy5HbNHLVvMPLiQ_180.JPG: 480x640 (no detections), 294.0ms
Speed: 1.1ms preprocess, 294.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAc0Ky7fy5HbNHLVvMPLiQ_270.JPG: 480x640 (no detections), 294.0ms
Speed: 1.1ms preprocess, 294.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAcdCSnzpW8i6H1uFFfGXQ_0.JPG: 480x640 (no detections), 303.9ms
Speed: 1.2ms preprocess, 303.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAcdCSnzpW8i6H1uFFfGXQ_90.JPG: 480x640 (no detections), 301.4ms
Speed: 1.3ms preprocess, 301.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAcdCSnzpW8i6H1uFFfGXQ_180.JPG: 480x640 (no detections), 300.4ms
Speed: 1.2ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAcdCSnzpW8i6H1uFFfGXQ_270.JPG: 480x640 1 Waste, 314.2ms
Speed: 1.2ms preprocess, 314.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAg18hWyMPMAlYEaJ5zzCg_0.JPG: 480x640 (no detections), 303.6ms
Speed: 8.2ms preprocess, 303.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAg18hWyMPMAlYEaJ5zzCg_90.JPG: 480x640 (no detections), 301.8ms
Speed: 1.1ms preprocess, 301.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAg18hWyMPMAlYEaJ5zzCg_180.JPG: 480x640 (no detections), 301.3ms
Speed: 1.4ms preprocess, 301.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAg18hWyMPMAlYEaJ5zzCg_270.JPG: 480x640 (no detections), 306.6ms
Speed: 1.1ms preprocess, 306.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAg28eEZ8IHLPqY23z2fIg_0.JPG: 480x640 (no detections), 306.8ms
Speed: 1.2ms preprocess, 306.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAg28eEZ8IHLPqY23z2fIg_90.JPG: 480x640 (no detections), 304.9ms
Speed: 1.4ms preprocess, 304.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAg28eEZ8IHLPqY23z2fIg_180.JPG: 480x640 (no detections), 297.9ms
Speed: 1.5ms preprocess, 297.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAg28eEZ8IHLPqY23z2fIg_270.JPG: 480x640 (no detections), 300.8ms
Speed: 1.1ms preprocess, 300.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAiG1vf9sHaVwesu-iuM6A_0.JPG: 480x640 (no detections), 300.1ms
Speed: 1.1ms preprocess, 300.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAiG1vf9sHaVwesu-iuM6A_90.JPG: 480x640 (no detections), 302.0ms
Speed: 1.4ms preprocess, 302.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAiG1vf9sHaVwesu-iuM6A_180.JPG: 480x640 (no detections), 299.1ms
Speed: 1.2ms preprocess, 299.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAiG1vf9sHaVwesu-iuM6A_270.JPG: 480x640 (no detections), 302.8ms
Speed: 1.3ms preprocess, 302.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAjWB4GtV_BsSHpIOBMe_w_0.JPG: 480x640 (no detections), 297.2ms
Speed: 1.2ms preprocess, 297.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAjWB4GtV_BsSHpIOBMe_w_90.JPG: 480x640 (no detections), 304.5ms
Speed: 1.4ms preprocess, 304.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAjWB4GtV_BsSHpIOBMe_w_180.JPG: 480x640 (no detections), 300.7ms
Speed: 1.1ms preprocess, 300.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAjWB4GtV_BsSHpIOBMe_w_270.JPG: 480x640 (no detections), 300.8ms
Speed: 1.2ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAjjBMXXRPku3SwnSWrf2Q_0.JPG: 480x640 (no detections), 305.3ms
Speed: 1.5ms preprocess, 305.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAjjBMXXRPku3SwnSWrf2Q_90.JPG: 480x640 (no detections), 300.9ms
Speed: 1.4ms preprocess, 300.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAjjBMXXRPku3SwnSWrf2Q_180.JPG: 480x640 (no detections), 307.3ms
Speed: 1.2ms preprocess, 307.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAjjBMXXRPku3SwnSWrf2Q_270.JPG: 480x640 (no detections), 301.3ms
Speed: 1.2ms preprocess, 301.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAoRKBHBx_rEPMqZkqGisg_0.JPG: 480x640 (no detections), 298.9ms
Speed: 1.0ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAoRKBHBx_rEPMqZkqGisg_90.JPG: 480x640 (no detections), 298.8ms
Speed: 1.2ms preprocess, 298.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAoRKBHBx_rEPMqZkqGisg_180.JPG: 480x640 (no detections), 301.9ms
Speed: 1.2ms preprocess, 301.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAoRKBHBx_rEPMqZkqGisg_270.JPG: 480x640 (no detections), 302.5ms
Speed: 1.2ms preprocess, 302.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAsaXdCTI_snUEPuAcQNvg_0.JPG: 480x640 (no detections), 302.7ms
Speed: 1.1ms preprocess, 302.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAsaXdCTI_snUEPuAcQNvg_90.JPG: 480x640 (no detections), 303.9ms
Speed: 1.2ms preprocess, 303.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAsaXdCTI_snUEPuAcQNvg_180.JPG: 480x640 (no detections), 301.6ms
Speed: 1.2ms preprocess, 301.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAsaXdCTI_snUEPuAcQNvg_270.JPG: 480x640 (no detections), 303.3ms
Speed: 1.4ms preprocess, 303.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAuJBKJiTI86ZkIRVybbBg_0.JPG: 480x640 (no detections), 298.1ms
Speed: 1.0ms preprocess, 298.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAuJBKJiTI86ZkIRVybbBg_90.JPG: 480x640 (no detections), 302.8ms
Speed: 1.4ms preprocess, 302.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAuJBKJiTI86ZkIRVybbBg_180.JPG: 480x640 (no detections), 303.2ms
Speed: 1.1ms preprocess, 303.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAuJBKJiTI86ZkIRVybbBg_270.JPG: 480x640 (no detections), 306.6ms
Speed: 1.6ms preprocess, 306.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAuPXlZq1lYHCCJd7K4r7Q_0.JPG: 480x640 (no detections), 306.7ms
Speed: 1.1ms preprocess, 306.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAuPXlZq1lYHCCJd7K4r7Q_90.JPG: 480x640 (no detections), 303.7ms
Speed: 1.2ms preprocess, 303.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAuPXlZq1lYHCCJd7K4r7Q_180.JPG: 480x640 (no detections), 300.7ms
Speed: 1.1ms preprocess, 300.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAuPXlZq1lYHCCJd7K4r7Q_270.JPG: 480x640 (no detections), 305.7ms
Speed: 1.2ms preprocess, 305.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAvOqF1S6ATvPwe0K34QoA_0.JPG: 480x640 (no detections), 300.1ms
Speed: 1.1ms preprocess, 300.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAvOqF1S6ATvPwe0K34QoA_90.JPG: 480x640 (no detections), 311.7ms
Speed: 1.1ms preprocess, 311.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAvOqF1S6ATvPwe0K34QoA_180.JPG: 480x640 (no detections), 300.0ms
Speed: 1.3ms preprocess, 300.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAvOqF1S6ATvPwe0K34QoA_270.JPG: 480x640 (no detections), 305.2ms
Speed: 1.6ms preprocess, 305.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAwDUutfVm3QeOSiAEMXOw_0.JPG: 480x640 (no detections), 304.2ms
Speed: 1.1ms preprocess, 304.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAwDUutfVm3QeOSiAEMXOw_90.JPG: 480x640 (no detections), 299.7ms
Speed: 1.2ms preprocess, 299.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAwDUutfVm3QeOSiAEMXOw_180.JPG: 480x640 (no detections), 303.3ms
Speed: 1.5ms preprocess, 303.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAwDUutfVm3QeOSiAEMXOw_270.JPG: 480x640 2 Wastes, 310.6ms
Speed: 1.1ms preprocess, 310.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAwqi8b7O3bBaWLAk0raiA_0.JPG: 480x640 (no detections), 303.2ms
Speed: 1.3ms preprocess, 303.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAwqi8b7O3bBaWLAk0raiA_90.JPG: 480x640 (no detections), 309.5ms
Speed: 1.2ms preprocess, 309.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAwqi8b7O3bBaWLAk0raiA_180.JPG: 480x640 (no detections), 304.0ms
Speed: 1.2ms preprocess, 304.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAwqi8b7O3bBaWLAk0raiA_270.JPG: 480x640 (no detections), 302.2ms
Speed: 1.7ms preprocess, 302.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAxMDXkmoijZtr8LPcfqWg_0.JPG: 480x640 (no detections), 299.5ms
Speed: 1.4ms preprocess, 299.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAxMDXkmoijZtr8LPcfqWg_90.JPG: 480x640 (no detections), 299.7ms
Speed: 1.4ms preprocess, 299.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAxMDXkmoijZtr8LPcfqWg_180.JPG: 480x640 (no detections), 299.7ms
Speed: 1.8ms preprocess, 299.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAxMDXkmoijZtr8LPcfqWg_270.JPG: 480x640 (no detections), 298.6ms
Speed: 1.4ms preprocess, 298.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAyfODDIFxdmDERViYZ4EQ_0.JPG: 480x640 (no detections), 300.4ms
Speed: 1.1ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAyfODDIFxdmDERViYZ4EQ_90.JPG: 480x640 (no detections), 304.9ms
Speed: 1.8ms preprocess, 304.9ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAyfODDIFxdmDERViYZ4EQ_180.JPG: 480x640 1 Waste, 301.4ms
Speed: 1.5ms preprocess, 301.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yAyfODDIFxdmDERViYZ4EQ_270.JPG: 480x640 (no detections), 301.9ms

Speed: 1.7ms preprocess, 301.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yB-c7KMLUdbzo2qVYmCOow_0.JPG: 480x640 (no detections), 299.0ms
Speed: 1.3ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yB-c7KMLUdbzo2qVYmCOow_90.JPG: 480x640 (no detections), 305.5ms
Speed: 1.3ms preprocess, 305.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yB-c7KMLUdbzo2qVYmCOow_180.JPG: 480x640 1 Waste, 299.8ms
Speed: 1.2ms preprocess, 299.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yB-c7KMLUdbzo2qVYmCOow_270.JPG: 480x640 (no detections), 306.7ms
Speed: 1.3ms preprocess, 306.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yB42a0_zA1m-UTCGzjrZMg_0.JPG: 480x640 (no detections), 300.7ms
Speed: 1.0ms preprocess, 300.7ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yB42a0_zA1m-UTCGzjrZMg_90.JPG: 480x640 (no detections), 301.7ms
Speed: 1.3ms preprocess, 301.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yB42a0_zA1m-UTCGzjrZMg_180.JPG: 480x640 (no detections), 303.8ms
Speed: 1.2ms preprocess, 303.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yB42a0_zA1m-UTCGzjrZMg_270.JPG: 480x640 (no detections), 300.9ms
Speed: 1.3ms preprocess, 300.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yB4Jp56qp_KFjnvSwVNIFw_0.JPG: 480x640 (no detections), 380.8ms
Speed: 1.3ms preprocess, 380.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yB4Jp56qp_KFjnvSwVNIFw_90.JPG: 480x640 (no detections), 302.6ms
Speed: 1.3ms preprocess, 302.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yB4Jp56qp_KFjnvSwVNIFw_180.JPG: 480x640 (no detections), 300.9ms
Speed: 1.2ms preprocess, 300.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yB4Jp56qp_KFjnvSwVNIFw_270.JPG: 480x640 (no detections), 303.8ms
Speed: 1.1ms preprocess, 303.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yB5YzzSZcqv7n1qUQSgpmw_0.JPG: 480x640 (no detections), 309.5ms
Speed: 1.2ms preprocess, 309.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yB5YzzSZcqv7n1qUQSgpmw_90.JPG: 480x640 (no detections), 302.9ms
Speed: 1.3ms preprocess, 302.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yB5YzzSZcqv7n1qUQSgpmw_180.JPG: 480x640 (no detections), 299.6ms
Speed: 1.3ms preprocess, 299.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yB5YzzSZcqv7n1qUQSgpmw_270.JPG: 480x640 (no detections), 303.4ms
Speed: 1.2ms preprocess, 303.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yB6UtqA8mfyQAi4IeQMoxQ_0.JPG: 480x640 (no detections), 305.5ms
Speed: 1.1ms preprocess, 305.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yB6UtqA8mfyQAi4IeQMoxQ_90.JPG: 480x640 (no detections), 300.3ms
Speed: 1.3ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yB6UtqA8mfyQAi4IeQMoxQ_180.JPG: 480x640 1 Waste, 308.8ms
Speed: 1.3ms preprocess, 308.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yB6UtqA8mfyQAi4IeQMoxQ_270.JPG: 480x640 (no detections), 300.9ms
Speed: 1.2ms preprocess, 300.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBFZZ4cMEtFIK3PsvM5dtQ_0.JPG: 480x640 (no detections), 299.5ms
Speed: 1.2ms preprocess, 299.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBFZZ4cMEtFIK3PsvM5dtQ_90.JPG: 480x640 (no detections), 304.6ms
Speed: 1.1ms preprocess, 304.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBFZZ4cMEtFIK3PsvM5dtQ_180.JPG: 480x640 (no detections), 301.8ms
Speed: 1.2ms preprocess, 301.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBFZZ4cMEtFIK3PsvM5dtQ_270.JPG: 480x640 (no detections), 303.1ms
Speed: 1.3ms preprocess, 303.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBI10P5sZ6KpRMCIGgltaA_0.JPG: 480x640 (no detections), 299.4ms
Speed: 1.1ms preprocess, 299.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBI10P5sZ6KpRMCIGgltaA_90.JPG: 480x640 (no detections), 299.1ms
Speed: 1.4ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBI10P5sZ6KpRMCIGgltaA_180.JPG: 480x640 (no detections), 300.8ms
Speed: 1.2ms preprocess, 300.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBI10P5sZ6KpRMCIGgltaA_270.JPG: 480x640 (no detections), 305.5ms
Speed: 1.4ms preprocess, 305.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBIgL0LWJiyXEw83yRZr9Q_0.JPG: 480x640 (no detections), 297.9ms
Speed: 1.4ms preprocess, 297.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBIgL0LWJiyXEw83yRZr9Q_90.JPG: 480x640 1 Waste, 302.9ms
Speed: 1.4ms preprocess, 302.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBIgL0LWJiyXEw83yRZr9Q_180.JPG: 480x640 (no detections), 298.5ms
Speed: 1.1ms preprocess, 298.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBIgL0LWJiyXEw83yRZr9Q_270.JPG: 480x640 (no detections), 298.2ms
Speed: 1.1ms preprocess, 298.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBJOcK2_wxNRWIA_li5rTQ_0.JPG: 480x640 (no detections), 304.0ms
Speed: 1.1ms preprocess, 304.0ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBJOcK2_wxNRWIA_li5rTQ_90.JPG: 480x640 (no detections), 298.1ms
Speed: 1.4ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBJOcK2_wxNRWIA_li5rTQ_180.JPG: 480x640 (no detections), 301.1ms
Speed: 1.0ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBJOcK2_wxNRWIA_li5rTQ_270.JPG: 480x640 (no detections), 301.8ms
Speed: 1.3ms preprocess, 301.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBRxiJ0EkHVn7PU906CK5A_0.JPG: 480x640 (no detections), 300.6ms
Speed: 1.6ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBRxiJ0EkHVn7PU906CK5A_90.JPG: 480x640 (no detections), 296.5ms
Speed: 1.1ms preprocess, 296.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBRxiJ0EkHVn7PU906CK5A_180.JPG: 480x640 1 Waste, 300.0ms
Speed: 1.0ms preprocess, 300.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBRxiJ0EkHVn7PU906CK5A_270.JPG: 480x640 (no detections), 301.0ms
Speed: 1.8ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBUY5cBOmMaOgVqypQo05Q_0.JPG: 480x640 (no detections), 305.7ms
Speed: 1.2ms preprocess, 305.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBUY5cBOmMaOgVqypQo05Q_90.JPG: 480x640 (no detections), 301.3ms
Speed: 1.1ms preprocess, 301.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBUY5cBOmMaOgVqypQo05Q_180.JPG: 480x640 (no detections), 300.8ms
Speed: 1.1ms preprocess, 300.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBUY5cBOmMaOgVqypQo05Q_270.JPG: 480x640 (no detections), 294.6ms
Speed: 1.4ms preprocess, 294.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBVP225xfZ3w1hGxUZL8QQ_0.JPG: 480x640 (no detections), 300.6ms
Speed: 1.1ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBVP225xfZ3w1hGxUZL8QQ_90.JPG: 480x640 (no detections), 299.3ms
Speed: 1.2ms preprocess, 299.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBVP225xfZ3w1hGxUZL8QQ_180.JPG: 480x640 (no detections), 298.4ms
Speed: 1.1ms preprocess, 298.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBVP225xfZ3w1hGxUZL8QQ_270.JPG: 480x640 (no detections), 298.1ms
Speed: 1.2ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBWwDS_B4OvzJp64Kkt1OQ_0.JPG: 480x640 (no detections), 297.8ms
Speed: 1.1ms preprocess, 297.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBWwDS_B4OvzJp64Kkt1OQ_90.JPG: 480x640 (no detections), 305.1ms
Speed: 1.2ms preprocess, 305.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBWwDS_B4OvzJp64Kkt1OQ_180.JPG: 480x640 (no detections), 300.4ms
Speed: 1.1ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBWwDS_B4OvzJp64Kkt1OQ_270.JPG: 480x640 (no detections), 303.3ms
Speed: 1.7ms preprocess, 303.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBbI9p3mju3hEDDMFMgxiA_0.JPG: 480x640 (no detections), 301.9ms
Speed: 1.1ms preprocess, 301.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBbI9p3mju3hEDDMFMgxiA_90.JPG: 480x640 (no detections), 320.7ms
Speed: 1.4ms preprocess, 320.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBbI9p3mju3hEDDMFMgxiA_180.JPG: 480x640 (no detections), 311.3ms
Speed: 1.3ms preprocess, 311.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBbI9p3mju3hEDDMFMgxiA_270.JPG: 480x640 (no detections), 312.1ms
Speed: 1.2ms preprocess, 312.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBpxeXEYxa7LlENXcR3_2w_0.JPG: 480x640 (no detections), 303.2ms
Speed: 1.2ms preprocess, 303.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBpxeXEYxa7LlENXcR3_2w_90.JPG: 480x640 (no detections), 303.1ms
Speed: 1.2ms preprocess, 303.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBpxeXEYxa7LlENXcR3_2w_180.JPG: 480x640 (no detections), 302.2ms
Speed: 1.5ms preprocess, 302.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBpxeXEYxa7LlENXcR3_2w_270.JPG: 480x640 (no detections), 298.9ms
Speed: 1.4ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBuFB0NhY7txwgyO3HjukQ_0.JPG: 480x640 (no detections), 306.0ms
Speed: 1.3ms preprocess, 306.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBuFB0NhY7txwgyO3HjukQ_90.JPG: 480x640 (no detections), 299.1ms
Speed: 1.1ms preprocess, 299.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBuFB0NhY7txwgyO3HjukQ_180.JPG: 480x640 (no detections), 301.4ms
Speed: 1.1ms preprocess, 301.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBuFB0NhY7txwgyO3HjukQ_270.JPG: 480x640 (no detections), 296.3ms
Speed: 1.1ms preprocess, 296.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBuHI1bjUId4IIm-n3pvSg_0.JPG: 480x640 (no detections), 294.5ms
Speed: 1.1ms preprocess, 294.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBuHI1bjUId4IIm-n3pvSg_90.JPG: 480x640 (no detections), 299.7ms
Speed: 1.1ms preprocess, 299.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBuHI1bjUId4IIm-n3pvSg_180.JPG: 480x640 (no detections), 309.1ms

Speed: 1.2ms preprocess, 309.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBuHI1bjUId4IIm-n3pvSg_270.JPG: 480x640 (no detections), 297.0ms
Speed: 1.2ms preprocess, 297.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBunzCKTV8Jl2c5jEas4Fw_0.JPG: 480x640 (no detections), 292.0ms
Speed: 1.4ms preprocess, 292.0ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBunzCKTV8Jl2c5jEas4Fw_90.JPG: 480x640 (no detections), 298.5ms
Speed: 1.2ms preprocess, 298.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBunzCKTV8Jl2c5jEas4Fw_180.JPG: 480x640 (no detections), 300.0ms
Speed: 1.1ms preprocess, 300.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBunzCKTV8Jl2c5jEas4Fw_270.JPG: 480x640 (no detections), 301.7ms
Speed: 1.3ms preprocess, 301.7ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBvSAqZ1wUk9yToqnTLJfA_0.JPG: 480x640 (no detections), 302.8ms
Speed: 1.3ms preprocess, 302.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBvSAqZ1wUk9yToqnTLJfA_90.JPG: 480x640 (no detections), 300.2ms
Speed: 1.3ms preprocess, 300.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBvSAqZ1wUk9yToqnTLJfA_180.JPG: 480x640 (no detections), 308.8ms
Speed: 1.0ms preprocess, 308.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBvSAqZ1wUk9yToqnTLJfA_270.JPG: 480x640 (no detections), 303.4ms
Speed: 1.2ms preprocess, 303.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBx4zFu7oJTJ1SbPDSJc_Q_0.JPG: 480x640 (no detections), 297.5ms
Speed: 1.1ms preprocess, 297.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBx4zFu7oJTJ1SbPDSJc_Q_90.JPG: 480x640 (no detections), 305.5ms
Speed: 1.3ms preprocess, 305.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBx4zFu7oJTJ1SbPDSJc_Q_180.JPG: 480x640 (no detections), 300.0ms
Speed: 1.6ms preprocess, 300.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yBx4zFu7oJTJ1SbPDSJc_Q_270.JPG: 480x640 1 Waste, 304.7ms
Speed: 1.2ms preprocess, 304.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yC2NeZXjlclJrlbDo9wgRQ_0.JPG: 480x640 (no detections), 301.9ms
Speed: 1.1ms preprocess, 301.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yC2NeZXjlclJrlbDo9wgRQ_90.JPG: 480x640 (no detections), 305.7ms
Speed: 1.3ms preprocess, 305.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yC2NeZXjlclJrlbDo9wgRQ_180.JPG: 480x640 (no detections), 305.0ms
Speed: 1.3ms preprocess, 305.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yC2NeZXjlclJrlbDo9wgRQ_270.JPG: 480x640 (no detections), 296.0ms
Speed: 1.3ms preprocess, 296.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yC9PjsjBXHb1zuzIayB3sA_0.JPG: 480x640 (no detections), 296.0ms
Speed: 1.1ms preprocess, 296.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yC9PjsjBXHb1zuzIayB3sA_90.JPG: 480x640 (no detections), 298.7ms
Speed: 2.0ms preprocess, 298.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yC9PjsjBXHb1zuzIayB3sA_180.JPG: 480x640 (no detections), 299.3ms
Speed: 1.3ms preprocess, 299.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yC9PjsjBXHb1zuzIayB3sA_270.JPG: 480x640 (no detections), 297.1ms
Speed: 1.3ms preprocess, 297.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCABZQ9O8UwduczS4Mjl8A_0.JPG: 480x640 (no detections), 303.3ms
Speed: 1.2ms preprocess, 303.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCABZQ9O8UwduczS4Mjl8A_90.JPG: 480x640 (no detections), 303.2ms
Speed: 1.6ms preprocess, 303.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCABZQ9O8UwduczS4Mjl8A_180.JPG: 480x640 (no detections), 299.3ms
Speed: 1.0ms preprocess, 299.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCABZQ9O8UwduczS4Mjl8A_270.JPG: 480x640 (no detections), 302.7ms
Speed: 1.2ms preprocess, 302.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCC4KM3lv5VccG0o8AW_TQ_0.JPG: 480x640 (no detections), 299.6ms
Speed: 1.1ms preprocess, 299.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCC4KM3lv5VccG0o8AW_TQ_90.JPG: 480x640 (no detections), 297.2ms
Speed: 1.0ms preprocess, 297.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCC4KM3lv5VccG0o8AW_TQ_180.JPG: 480x640 (no detections), 305.3ms
Speed: 1.7ms preprocess, 305.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCC4KM3lv5VccG0o8AW_TQ_270.JPG: 480x640 (no detections), 298.7ms
Speed: 1.3ms preprocess, 298.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCEm9P5LpsLkvH2NNMpMbg_0.JPG: 480x640 (no detections), 295.1ms
Speed: 1.2ms preprocess, 295.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCEm9P5LpsLkvH2NNMpMbg_90.JPG: 480x640 (no detections), 303.2ms
Speed: 1.2ms preprocess, 303.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCEm9P5LpsLkvH2NNMpMbg_180.JPG: 480x640 (no detections), 304.2ms
Speed: 1.1ms preprocess, 304.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCEm9P5LpsLkvH2NNMpMbg_270.JPG: 480x640 (no detections), 300.5ms
Speed: 1.1ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCGpLAsAo3j3CdLBLJQa5Q_0.JPG: 480x640 (no detections), 299.4ms
Speed: 1.0ms preprocess, 299.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCGpLAsAo3j3CdLBLJQa5Q_90.JPG: 480x640 (no detections), 301.1ms
Speed: 1.2ms preprocess, 301.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCGpLAsAo3j3CdLBLJQa5Q_180.JPG: 480x640 (no detections), 305.9ms
Speed: 1.7ms preprocess, 305.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCGpLAsAo3j3CdLBLJQa5Q_270.JPG: 480x640 (no detections), 302.6ms
Speed: 1.1ms preprocess, 302.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCHat0Ahwv890oDRI5plhA_0.JPG: 480x640 (no detections), 307.7ms
Speed: 1.2ms preprocess, 307.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCHat0Ahwv890oDRI5plhA_90.JPG: 480x640 (no detections), 301.3ms
Speed: 1.1ms preprocess, 301.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCHat0Ahwv890oDRI5plhA_180.JPG: 480x640 (no detections), 293.3ms
Speed: 1.1ms preprocess, 293.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCHat0Ahwv890oDRI5plhA_270.JPG: 480x640 (no detections), 299.0ms
Speed: 1.0ms preprocess, 299.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCLqHBT3O0DcHe71VfwiHQ_0.JPG: 480x640 (no detections), 303.4ms
Speed: 1.3ms preprocess, 303.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCLqHBT3O0DcHe71VfwiHQ_90.JPG: 480x640 (no detections), 309.4ms
Speed: 1.2ms preprocess, 309.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCLqHBT3O0DcHe71VfwiHQ_180.JPG: 480x640 (no detections), 304.4ms
Speed: 1.5ms preprocess, 304.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCLqHBT3O0DcHe71VfwiHQ_270.JPG: 480x640 (no detections), 319.3ms
Speed: 1.1ms preprocess, 319.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCN4g8sA8y1vZkP__-x5vw_0.JPG: 480x640 (no detections), 311.6ms
Speed: 1.2ms preprocess, 311.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCN4g8sA8y1vZkP__-x5vw_90.JPG: 480x640 (no detections), 313.2ms
Speed: 1.1ms preprocess, 313.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCN4g8sA8y1vZkP__-x5vw_180.JPG: 480x640 1 Waste, 314.7ms
Speed: 1.6ms preprocess, 314.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCN4g8sA8y1vZkP__-x5vw_270.JPG: 480x640 (no detections), 304.0ms
Speed: 1.2ms preprocess, 304.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCS4OEMO9bL7y5Kp0mswRw_0.JPG: 480x640 (no detections), 312.9ms
Speed: 1.4ms preprocess, 312.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCS4OEMO9bL7y5Kp0mswRw_90.JPG: 480x640 (no detections), 309.9ms
Speed: 1.2ms preprocess, 309.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCS4OEMO9bL7y5Kp0mswRw_180.JPG: 480x640 (no detections), 302.5ms
Speed: 1.2ms preprocess, 302.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCS4OEMO9bL7y5Kp0mswRw_270.JPG: 480x640 (no detections), 305.8ms
Speed: 1.2ms preprocess, 305.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCSxI7xwi09m_mX-9aOyEA_0.JPG: 480x640 (no detections), 304.6ms
Speed: 1.3ms preprocess, 304.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCSxI7xwi09m_mX-9aOyEA_90.JPG: 480x640 (no detections), 305.0ms
Speed: 1.2ms preprocess, 305.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCSxI7xwi09m_mX-9aOyEA_180.JPG: 480x640 (no detections), 318.4ms
Speed: 1.5ms preprocess, 318.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCSxI7xwi09m_mX-9aOyEA_270.JPG: 480x640 (no detections), 311.5ms
Speed: 1.5ms preprocess, 311.5ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCVlpqlZ2pb1jpebXqMvLQ_0.JPG: 480x640 (no detections), 298.5ms
Speed: 1.2ms preprocess, 298.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCVlpqlZ2pb1jpebXqMvLQ_90.JPG: 480x640 (no detections), 301.3ms
Speed: 1.1ms preprocess, 301.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCVlpqlZ2pb1jpebXqMvLQ_180.JPG: 480x640 (no detections), 313.3ms
Speed: 1.0ms preprocess, 313.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCVlpqlZ2pb1jpebXqMvLQ_270.JPG: 480x640 (no detections), 312.8ms
Speed: 1.3ms preprocess, 312.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCVqqx32lpzlaJsatF1vJw_0.JPG: 480x640 (no detections), 311.1ms
Speed: 1.7ms preprocess, 311.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCVqqx32lpzlaJsatF1vJw_90.JPG: 480x640 (no detections), 314.9ms
Speed: 1.3ms preprocess, 314.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCVqqx32lpzlaJsatF1vJw_180.JPG: 480x640 (no detections), 305.3ms
Speed: 1.2ms preprocess, 305.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCVqqx32lpzlaJsatF1vJw_270.JPG: 480x640 (no detections), 328.2ms
Speed: 1.3ms preprocess, 328.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCbHoHGiHJBT_aCKSvQ3-g_0.JPG: 480x640 (no detections), 309.0ms
Speed: 1.2ms preprocess, 309.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCbHoHGiHJBT_aCKSvQ3-g_90.JPG: 480x640 (no detections), 308.2ms

Speed: 1.1ms preprocess, 308.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCbHoHGiHJBT_aCKSvQ3-g_180.JPG: 480x640 (no detections), 317.5ms
Speed: 1.5ms preprocess, 317.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCbHoHGiHJBT_aCKSvQ3-g_270.JPG: 480x640 (no detections), 308.7ms
Speed: 1.2ms preprocess, 308.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCc5waBemSm4baJQzjX-pw_0.JPG: 480x640 (no detections), 317.9ms
Speed: 1.3ms preprocess, 317.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCc5waBemSm4baJQzjX-pw_90.JPG: 480x640 (no detections), 322.0ms
Speed: 1.4ms preprocess, 322.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCc5waBemSm4baJQzjX-pw_180.JPG: 480x640 (no detections), 307.1ms
Speed: 1.2ms preprocess, 307.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCc5waBemSm4baJQzjX-pw_270.JPG: 480x640 (no detections), 300.7ms
Speed: 1.4ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCeFLiCReGN-B4Nu4Uo9Xg_0.JPG: 480x640 (no detections), 301.4ms
Speed: 1.2ms preprocess, 301.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCeFLiCReGN-B4Nu4Uo9Xg_90.JPG: 480x640 (no detections), 295.7ms
Speed: 1.1ms preprocess, 295.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCeFLiCReGN-B4Nu4Uo9Xg_180.JPG: 480x640 (no detections), 293.4ms
Speed: 1.1ms preprocess, 293.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCeFLiCReGN-B4Nu4Uo9Xg_270.JPG: 480x640 (no detections), 293.4ms
Speed: 1.0ms preprocess, 293.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCedDBKA4RAVlD0UeD0BfQ_0.JPG: 480x640 (no detections), 307.0ms
Speed: 1.2ms preprocess, 307.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCedDBKA4RAVlD0UeD0BfQ_90.JPG: 480x640 (no detections), 318.6ms
Speed: 1.2ms preprocess, 318.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCedDBKA4RAVlD0UeD0BfQ_180.JPG: 480x640 (no detections), 311.0ms
Speed: 2.1ms preprocess, 311.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCedDBKA4RAVlD0UeD0BfQ_270.JPG: 480x640 (no detections), 301.4ms
Speed: 1.1ms preprocess, 301.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yClP3m5G0doCww39Pj3mwg_0.JPG: 480x640 (no detections), 301.8ms
Speed: 1.2ms preprocess, 301.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yClP3m5G0doCww39Pj3mwg_90.JPG: 480x640 (no detections), 302.9ms
Speed: 1.3ms preprocess, 302.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yClP3m5G0doCww39Pj3mwg_180.JPG: 480x640 1 Waste, 304.8ms
Speed: 1.1ms preprocess, 304.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yClP3m5G0doCww39Pj3mwg_270.JPG: 480x640 (no detections), 302.2ms
Speed: 1.1ms preprocess, 302.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCl_3vsF0Albi3xJixNzdg_0.JPG: 480x640 (no detections), 299.9ms
Speed: 1.8ms preprocess, 299.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCl_3vsF0Albi3xJixNzdg_90.JPG: 480x640 (no detections), 297.8ms
Speed: 1.2ms preprocess, 297.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCl_3vsF0Albi3xJixNzdg_180.JPG: 480x640 (no detections), 301.1ms
Speed: 1.1ms preprocess, 301.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCl_3vsF0Albi3xJixNzdg_270.JPG: 480x640 (no detections), 303.1ms
Speed: 1.2ms preprocess, 303.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCn75Ll8ls2qGiQhQmhauw_0.JPG: 480x640 (no detections), 306.3ms
Speed: 1.3ms preprocess, 306.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCn75Ll8ls2qGiQhQmhauw_90.JPG: 480x640 (no detections), 301.4ms
Speed: 1.2ms preprocess, 301.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCn75Ll8ls2qGiQhQmhauw_180.JPG: 480x640 (no detections), 300.8ms
Speed: 1.3ms preprocess, 300.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCn75Ll8ls2qGiQhQmhauw_270.JPG: 480x640 (no detections), 299.9ms
Speed: 1.5ms preprocess, 299.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCpo4iIltJ1wzFvakurViQ_0.JPG: 480x640 (no detections), 304.1ms
Speed: 1.2ms preprocess, 304.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCpo4iIltJ1wzFvakurViQ_90.JPG: 480x640 (no detections), 303.0ms
Speed: 1.1ms preprocess, 303.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCpo4iIltJ1wzFvakurViQ_180.JPG: 480x640 (no detections), 299.1ms
Speed: 1.2ms preprocess, 299.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCpo4iIltJ1wzFvakurViQ_270.JPG: 480x640 (no detections), 302.7ms
Speed: 1.3ms preprocess, 302.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCpqjWidFHvdOLuZO4tVlw_0.JPG: 480x640 (no detections), 301.9ms
Speed: 1.1ms preprocess, 301.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCpqjWidFHvdOLuZO4tVlw_90.JPG: 480x640 (no detections), 304.5ms
Speed: 1.3ms preprocess, 304.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCpqjWidFHvdOLuZO4tVlw_180.JPG: 480x640 (no detections), 310.2ms
Speed: 1.3ms preprocess, 310.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCpqjWidFHvdOLuZO4tVlw_270.JPG: 480x640 1 Waste, 326.6ms
Speed: 1.4ms preprocess, 326.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCr4ajfKjCDpkpTHoQ_zig_0.JPG: 480x640 (no detections), 318.1ms
Speed: 1.1ms preprocess, 318.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCr4ajfKjCDpkpTHoQ_zig_90.JPG: 480x640 (no detections), 307.0ms
Speed: 1.1ms preprocess, 307.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCr4ajfKjCDpkpTHoQ_zig_180.JPG: 480x640 (no detections), 314.6ms
Speed: 1.1ms preprocess, 314.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yCr4ajfKjCDpkpTHoQ_zig_270.JPG: 480x640 (no detections), 310.3ms
Speed: 1.7ms preprocess, 310.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yD-mMkFoTKmg_tDrxhx5PA_0.JPG: 480x640 (no detections), 309.7ms
Speed: 1.3ms preprocess, 309.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yD-mMkFoTKmg_tDrxhx5PA_90.JPG: 480x640 (no detections), 304.9ms
Speed: 1.3ms preprocess, 304.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yD-mMkFoTKmg_tDrxhx5PA_180.JPG: 480x640 (no detections), 302.2ms
Speed: 1.2ms preprocess, 302.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yD-mMkFoTKmg_tDrxhx5PA_270.JPG: 480x640 (no detections), 309.4ms
Speed: 1.3ms preprocess, 309.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yD2QGP9JLO1MS0QwcpmabA_0.JPG: 480x640 (no detections), 301.5ms
Speed: 1.1ms preprocess, 301.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yD2QGP9JLO1MS0QwcpmabA_90.JPG: 480x640 (no detections), 303.3ms
Speed: 1.0ms preprocess, 303.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yD2QGP9JLO1MS0QwcpmabA_180.JPG: 480x640 1 Waste, 309.0ms
Speed: 1.1ms preprocess, 309.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yD2QGP9JLO1MS0QwcpmabA_270.JPG: 480x640 (no detections), 302.0ms
Speed: 1.2ms preprocess, 302.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yD4z2L6OgzZGJhz7VjZ-WQ_0.JPG: 480x640 (no detections), 297.7ms
Speed: 1.2ms preprocess, 297.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yD4z2L6OgzZGJhz7VjZ-WQ_90.JPG: 480x640 (no detections), 301.6ms
Speed: 1.2ms preprocess, 301.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yD4z2L6OgzZGJhz7VjZ-WQ_180.JPG: 480x640 (no detections), 306.1ms
Speed: 1.2ms preprocess, 306.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yD4z2L6OgzZGJhz7VjZ-WQ_270.JPG: 480x640 (no detections), 308.1ms
Speed: 1.3ms preprocess, 308.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yD5SAnK1kdUXLJd4sWmpFw_0.JPG: 480x640 (no detections), 293.8ms
Speed: 1.2ms preprocess, 293.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yD5SAnK1kdUXLJd4sWmpFw_90.JPG: 480x640 (no detections), 298.5ms
Speed: 1.2ms preprocess, 298.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yD5SAnK1kdUXLJd4sWmpFw_180.JPG: 480x640 (no detections), 305.0ms
Speed: 1.1ms preprocess, 305.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yD5SAnK1kdUXLJd4sWmpFw_270.JPG: 480x640 (no detections), 303.1ms
Speed: 1.4ms preprocess, 303.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yD6opXrRCBza8eQJRPcy7A_0.JPG: 480x640 (no detections), 303.3ms
Speed: 1.4ms preprocess, 303.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yD6opXrRCBza8eQJRPcy7A_90.JPG: 480x640 (no detections), 304.0ms
Speed: 1.2ms preprocess, 304.0ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yD6opXrRCBza8eQJRPcy7A_180.JPG: 480x640 (no detections), 298.6ms
Speed: 1.1ms preprocess, 298.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yD6opXrRCBza8eQJRPcy7A_270.JPG: 480x640 (no detections), 309.0ms
Speed: 1.2ms preprocess, 309.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yD7f1HC8Q8hpUDfgMCa3lw_0.JPG: 480x640 (no detections), 303.2ms
Speed: 1.8ms preprocess, 303.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yD7f1HC8Q8hpUDfgMCa3lw_90.JPG: 480x640 (no detections), 303.1ms
Speed: 1.2ms preprocess, 303.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yD7f1HC8Q8hpUDfgMCa3lw_180.JPG: 480x640 (no detections), 301.2ms
Speed: 1.4ms preprocess, 301.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yD7f1HC8Q8hpUDfgMCa3lw_270.JPG: 480x640 (no detections), 301.9ms
Speed: 1.3ms preprocess, 301.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDCoRYM_PGsPV1JILb8ajQ_0.JPG: 480x640 (no detections), 308.2ms
Speed: 1.2ms preprocess, 308.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDCoRYM_PGsPV1JILb8ajQ_90.JPG: 480x640 (no detections), 303.6ms
Speed: 1.7ms preprocess, 303.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDCoRYM_PGsPV1JILb8ajQ_180.JPG: 480x640 (no detections), 297.3ms
Speed: 1.1ms preprocess, 297.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDCoRYM_PGsPV1JILb8ajQ_270.JPG: 480x640 (no detections), 301.1ms
Speed: 1.2ms preprocess, 301.1ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDE0AIMWrXdmjoX_r4cycA_0.JPG: 480x640 (no detections), 301.5ms

Speed: 1.5ms preprocess, 301.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDE0AIMWrXdmjoX_r4cycA_90.JPG: 480x640 (no detections), 300.3ms
Speed: 1.9ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDE0AIMWrXdmjoX_r4cycA_180.JPG: 480x640 (no detections), 301.5ms
Speed: 1.2ms preprocess, 301.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDE0AIMWrXdmjoX_r4cycA_270.JPG: 480x640 (no detections), 299.8ms
Speed: 1.1ms preprocess, 299.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDGtrbkxMG1EC0ENbnJ_UA_0.JPG: 480x640 (no detections), 304.2ms
Speed: 1.3ms preprocess, 304.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDGtrbkxMG1EC0ENbnJ_UA_90.JPG: 480x640 (no detections), 305.3ms
Speed: 1.3ms preprocess, 305.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDGtrbkxMG1EC0ENbnJ_UA_180.JPG: 480x640 (no detections), 299.5ms
Speed: 1.2ms preprocess, 299.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDGtrbkxMG1EC0ENbnJ_UA_270.JPG: 480x640 (no detections), 302.2ms
Speed: 1.3ms preprocess, 302.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDJGV6fSyzMFJ-9cXmHGBg_0.JPG: 480x640 (no detections), 305.1ms
Speed: 1.1ms preprocess, 305.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDJGV6fSyzMFJ-9cXmHGBg_90.JPG: 480x640 (no detections), 303.0ms
Speed: 1.1ms preprocess, 303.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDJGV6fSyzMFJ-9cXmHGBg_180.JPG: 480x640 (no detections), 298.7ms
Speed: 1.3ms preprocess, 298.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDJGV6fSyzMFJ-9cXmHGBg_270.JPG: 480x640 (no detections), 304.0ms
Speed: 1.2ms preprocess, 304.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDNW-6Do49yGJLFLCMKcgw_0.JPG: 480x640 (no detections), 303.3ms
Speed: 1.1ms preprocess, 303.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDNW-6Do49yGJLFLCMKcgw_90.JPG: 480x640 (no detections), 299.3ms
Speed: 1.1ms preprocess, 299.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDNW-6Do49yGJLFLCMKcgw_180.JPG: 480x640 (no detections), 304.2ms
Speed: 1.1ms preprocess, 304.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDNW-6Do49yGJLFLCMKcgw_270.JPG: 480x640 (no detections), 309.1ms
Speed: 1.3ms preprocess, 309.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDOyFII2L99xYB0aht97yw_0.JPG: 480x640 (no detections), 304.3ms
Speed: 1.1ms preprocess, 304.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDOyFII2L99xYB0aht97yw_90.JPG: 480x640 (no detections), 302.2ms
Speed: 1.5ms preprocess, 302.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDOyFII2L99xYB0aht97yw_180.JPG: 480x640 (no detections), 296.0ms
Speed: 1.2ms preprocess, 296.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDOyFII2L99xYB0aht97yw_270.JPG: 480x640 (no detections), 297.8ms
Speed: 1.3ms preprocess, 297.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDRvSc5y1Er-CZ3DzDX_ZA_0.JPG: 480x640 (no detections), 297.9ms
Speed: 1.1ms preprocess, 297.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDRvSc5y1Er-CZ3DzDX_ZA_90.JPG: 480x640 (no detections), 298.8ms
Speed: 1.0ms preprocess, 298.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDRvSc5y1Er-CZ3DzDX_ZA_180.JPG: 480x640 (no detections), 302.4ms
Speed: 1.1ms preprocess, 302.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDRvSc5y1Er-CZ3DzDX_ZA_270.JPG: 480x640 (no detections), 301.5ms
Speed: 1.3ms preprocess, 301.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDTn80yUZC3Yz67ljPoPzQ_0.JPG: 480x640 (no detections), 298.1ms
Speed: 1.2ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDTn80yUZC3Yz67ljPoPzQ_90.JPG: 480x640 (no detections), 301.1ms
Speed: 1.3ms preprocess, 301.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDTn80yUZC3Yz67ljPoPzQ_180.JPG: 480x640 (no detections), 303.0ms
Speed: 1.2ms preprocess, 303.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDTn80yUZC3Yz67ljPoPzQ_270.JPG: 480x640 (no detections), 297.4ms
Speed: 1.0ms preprocess, 297.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDUELatGH3mvgYnDFRmYiA_0.JPG: 480x640 (no detections), 304.8ms
Speed: 1.3ms preprocess, 304.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDUELatGH3mvgYnDFRmYiA_90.JPG: 480x640 (no detections), 297.8ms
Speed: 1.5ms preprocess, 297.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDUELatGH3mvgYnDFRmYiA_180.JPG: 480x640 (no detections), 302.3ms
Speed: 1.3ms preprocess, 302.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDUELatGH3mvgYnDFRmYiA_270.JPG: 480x640 (no detections), 299.5ms
Speed: 1.2ms preprocess, 299.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDY8J51HaFgfkm_STj9Ebw_0.JPG: 480x640 (no detections), 301.3ms
Speed: 1.4ms preprocess, 301.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDY8J51HaFgfkm_STj9Ebw_90.JPG: 480x640 (no detections), 297.2ms
Speed: 1.2ms preprocess, 297.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDY8J51HaFgfkm_STj9Ebw_180.JPG: 480x640 (no detections), 301.9ms
Speed: 1.0ms preprocess, 301.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDY8J51HaFgfkm_STj9Ebw_270.JPG: 480x640 (no detections), 305.7ms
Speed: 1.1ms preprocess, 305.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDafDVbclwvWKnKN4aWZFw_0.JPG: 480x640 (no detections), 300.3ms
Speed: 1.3ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDafDVbclwvWKnKN4aWZFw_90.JPG: 480x640 (no detections), 296.7ms
Speed: 1.0ms preprocess, 296.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDafDVbclwvWKnKN4aWZFw_180.JPG: 480x640 (no detections), 298.6ms
Speed: 1.6ms preprocess, 298.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDafDVbclwvWKnKN4aWZFw_270.JPG: 480x640 (no detections), 301.6ms
Speed: 1.2ms preprocess, 301.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDbKUcSanp5tEPek6M0-yg_0.JPG: 480x640 (no detections), 297.4ms
Speed: 1.1ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDbKUcSanp5tEPek6M0-yg_90.JPG: 480x640 (no detections), 304.8ms
Speed: 1.1ms preprocess, 304.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDbKUcSanp5tEPek6M0-yg_180.JPG: 480x640 (no detections), 298.7ms
Speed: 1.2ms preprocess, 298.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDbKUcSanp5tEPek6M0-yg_270.JPG: 480x640 1 Waste, 301.8ms
Speed: 1.1ms preprocess, 301.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDbgzKhig5YiE-r4m118xw_0.JPG: 480x640 (no detections), 295.9ms
Speed: 1.1ms preprocess, 295.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDbgzKhig5YiE-r4m118xw_90.JPG: 480x640 (no detections), 297.7ms
Speed: 1.1ms preprocess, 297.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDbgzKhig5YiE-r4m118xw_180.JPG: 480x640 (no detections), 301.2ms
Speed: 1.1ms preprocess, 301.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDbgzKhig5YiE-r4m118xw_270.JPG: 480x640 (no detections), 303.4ms
Speed: 1.1ms preprocess, 303.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDd8c-tXa-ZMRAYjSI_OVQ_0.JPG: 480x640 (no detections), 310.6ms
Speed: 1.1ms preprocess, 310.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDd8c-tXa-ZMRAYjSI_OVQ_90.JPG: 480x640 (no detections), 298.1ms
Speed: 1.4ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDd8c-tXa-ZMRAYjSI_OVQ_180.JPG: 480x640 (no detections), 298.9ms
Speed: 1.2ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDd8c-tXa-ZMRAYjSI_OVQ_270.JPG: 480x640 (no detections), 296.5ms
Speed: 1.1ms preprocess, 296.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDds-qcZBXeK8bnq2Fznyg_0.JPG: 480x640 (no detections), 297.5ms
Speed: 1.5ms preprocess, 297.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDds-qcZBXeK8bnq2Fznyg_90.JPG: 480x640 (no detections), 293.5ms
Speed: 1.4ms preprocess, 293.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDds-qcZBXeK8bnq2Fznyg_180.JPG: 480x640 (no detections), 301.5ms
Speed: 1.1ms preprocess, 301.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDds-qcZBXeK8bnq2Fznyg_270.JPG: 480x640 (no detections), 293.3ms
Speed: 2.2ms preprocess, 293.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDhSkQsLCgG1VtqxpMbImg_0.JPG: 480x640 (no detections), 301.9ms
Speed: 1.3ms preprocess, 301.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDhSkQsLCgG1VtqxpMbImg_90.JPG: 480x640 (no detections), 296.2ms
Speed: 1.3ms preprocess, 296.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDhSkQsLCgG1VtqxpMbImg_180.JPG: 480x640 (no detections), 298.3ms
Speed: 1.2ms preprocess, 298.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDhSkQsLCgG1VtqxpMbImg_270.JPG: 480x640 (no detections), 299.5ms
Speed: 1.0ms preprocess, 299.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDpCb6_D8_djSmWbMExjdQ_0.JPG: 480x640 (no detections), 301.7ms
Speed: 1.3ms preprocess, 301.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDpCb6_D8_djSmWbMExjdQ_90.JPG: 480x640 (no detections), 297.1ms
Speed: 1.3ms preprocess, 297.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDpCb6_D8_djSmWbMExjdQ_180.JPG: 480x640 (no detections), 300.6ms
Speed: 1.1ms preprocess, 300.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDpCb6_D8_djSmWbMExjdQ_270.JPG: 480x640 (no detections), 299.0ms
Speed: 1.3ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDpKI52wQVun2rx5xopXtw_0.JPG: 480x640 (no detections), 303.4ms
Speed: 1.1ms preprocess, 303.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDpKI52wQVun2rx5xopXtw_90.JPG: 480x640 (no detections), 294.0ms
Speed: 1.3ms preprocess, 294.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDpKI52wQVun2rx5xopXtw_180.JPG: 480x640 (no detections), 300.7ms
Speed: 1.1ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDpKI52wQVun2rx5xopXtw_270.JPG: 480x640 (no detections), 296.9ms

Speed: 1.3ms preprocess, 296.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDr2Y4sE-ryAOFaqbdJwww_0.JPG: 480x640 (no detections), 295.5ms
Speed: 1.2ms preprocess, 295.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDr2Y4sE-ryAOFaqbdJwww_90.JPG: 480x640 (no detections), 292.6ms
Speed: 1.1ms preprocess, 292.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDr2Y4sE-ryAOFaqbdJwww_180.JPG: 480x640 (no detections), 293.7ms
Speed: 1.1ms preprocess, 293.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDr2Y4sE-ryAOFaqbdJwww_270.JPG: 480x640 (no detections), 295.1ms
Speed: 1.3ms preprocess, 295.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDs5PRID8udcnjNNrCxAeg_0.JPG: 480x640 (no detections), 300.1ms
Speed: 1.2ms preprocess, 300.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDs5PRID8udcnjNNrCxAeg_90.JPG: 480x640 (no detections), 298.0ms
Speed: 1.1ms preprocess, 298.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDs5PRID8udcnjNNrCxAeg_180.JPG: 480x640 (no detections), 294.7ms
Speed: 1.9ms preprocess, 294.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDs5PRID8udcnjNNrCxAeg_270.JPG: 480x640 (no detections), 296.8ms
Speed: 1.2ms preprocess, 296.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDsM18E01M3OiCXEJo5YDg_0.JPG: 480x640 (no detections), 296.7ms
Speed: 1.2ms preprocess, 296.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDsM18E01M3OiCXEJo5YDg_90.JPG: 480x640 (no detections), 295.4ms
Speed: 1.1ms preprocess, 295.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDsM18E01M3OiCXEJo5YDg_180.JPG: 480x640 (no detections), 301.7ms
Speed: 1.2ms preprocess, 301.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDsM18E01M3OiCXEJo5YDg_270.JPG: 480x640 (no detections), 304.3ms
Speed: 1.2ms preprocess, 304.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDthW-YRcokL6FdNtuH98w_0.JPG: 480x640 (no detections), 302.7ms
Speed: 1.5ms preprocess, 302.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDthW-YRcokL6FdNtuH98w_90.JPG: 480x640 (no detections), 298.6ms
Speed: 1.3ms preprocess, 298.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDthW-YRcokL6FdNtuH98w_180.JPG: 480x640 (no detections), 293.0ms
Speed: 1.2ms preprocess, 293.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDthW-YRcokL6FdNtuH98w_270.JPG: 480x640 (no detections), 301.1ms
Speed: 1.1ms preprocess, 301.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDv3LtaxfOS5piCv_t7kzw_0.JPG: 480x640 (no detections), 308.8ms
Speed: 1.4ms preprocess, 308.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDv3LtaxfOS5piCv_t7kzw_90.JPG: 480x640 (no detections), 304.9ms
Speed: 1.6ms preprocess, 304.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDv3LtaxfOS5piCv_t7kzw_180.JPG: 480x640 (no detections), 345.2ms
Speed: 1.2ms preprocess, 345.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDv3LtaxfOS5piCv_t7kzw_270.JPG: 480x640 (no detections), 309.2ms
Speed: 1.3ms preprocess, 309.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDxjlcxKB56GyZStUv8jqg_0.JPG: 480x640 (no detections), 318.3ms
Speed: 1.2ms preprocess, 318.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDxjlcxKB56GyZStUv8jqg_90.JPG: 480x640 (no detections), 317.1ms
Speed: 1.3ms preprocess, 317.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDxjlcxKB56GyZStUv8jqg_180.JPG: 480x640 (no detections), 307.4ms
Speed: 1.1ms preprocess, 307.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDxjlcxKB56GyZStUv8jqg_270.JPG: 480x640 (no detections), 302.8ms
Speed: 1.2ms preprocess, 302.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDxmRC7VO9kTEkSS5dBKYA_0.JPG: 480x640 (no detections), 300.9ms
Speed: 1.1ms preprocess, 300.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDxmRC7VO9kTEkSS5dBKYA_90.JPG: 480x640 1 Waste, 301.5ms
Speed: 1.2ms preprocess, 301.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDxmRC7VO9kTEkSS5dBKYA_180.JPG: 480x640 1 Waste, 305.3ms
Speed: 1.3ms preprocess, 305.3ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yDxmRC7VO9kTEkSS5dBKYA_270.JPG: 480x640 (no detections), 306.2ms
Speed: 1.2ms preprocess, 306.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yE0GMjcJX5MmDeSTahaIYQ_0.JPG: 480x640 (no detections), 311.2ms
Speed: 1.2ms preprocess, 311.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yE0GMjcJX5MmDeSTahaIYQ_90.JPG: 480x640 (no detections), 311.7ms
Speed: 1.2ms preprocess, 311.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yE0GMjcJX5MmDeSTahaIYQ_180.JPG: 480x640 (no detections), 307.6ms
Speed: 1.1ms preprocess, 307.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yE0GMjcJX5MmDeSTahaIYQ_270.JPG: 480x640 (no detections), 299.8ms
Speed: 1.3ms preprocess, 299.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yE1e16WmPk_jqPO0C7DMcg_0.JPG: 480x640 (no detections), 309.4ms
Speed: 1.0ms preprocess, 309.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yE1e16WmPk_jqPO0C7DMcg_90.JPG: 480x640 (no detections), 306.9ms
Speed: 1.2ms preprocess, 306.9ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yE1e16WmPk_jqPO0C7DMcg_180.JPG: 480x640 (no detections), 305.1ms
Speed: 1.1ms preprocess, 305.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yE1e16WmPk_jqPO0C7DMcg_270.JPG: 480x640 (no detections), 305.3ms
Speed: 1.1ms preprocess, 305.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yE34p36OK1Evv8AZG_Afrg_0.JPG: 480x640 (no detections), 304.6ms
Speed: 1.1ms preprocess, 304.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yE34p36OK1Evv8AZG_Afrg_90.JPG: 480x640 (no detections), 307.2ms
Speed: 1.1ms preprocess, 307.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yE34p36OK1Evv8AZG_Afrg_180.JPG: 480x640 (no detections), 299.4ms
Speed: 1.3ms preprocess, 299.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yE34p36OK1Evv8AZG_Afrg_270.JPG: 480x640 (no detections), 301.2ms
Speed: 1.3ms preprocess, 301.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yE45yCGGqmhzJs1ecEUkLg_0.JPG: 480x640 (no detections), 298.9ms
Speed: 1.2ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yE45yCGGqmhzJs1ecEUkLg_90.JPG: 480x640 (no detections), 295.1ms
Speed: 1.5ms preprocess, 295.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yE45yCGGqmhzJs1ecEUkLg_180.JPG: 480x640 (no detections), 300.6ms
Speed: 1.6ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yE45yCGGqmhzJs1ecEUkLg_270.JPG: 480x640 (no detections), 304.1ms
Speed: 1.2ms preprocess, 304.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yE8R6o41RcoG6La_YvjCVA_0.JPG: 480x640 (no detections), 300.3ms
Speed: 1.4ms preprocess, 300.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yE8R6o41RcoG6La_YvjCVA_90.JPG: 480x640 1 Waste, 303.4ms
Speed: 1.2ms preprocess, 303.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yE8R6o41RcoG6La_YvjCVA_180.JPG: 480x640 (no detections), 308.1ms
Speed: 1.1ms preprocess, 308.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yE8R6o41RcoG6La_YvjCVA_270.JPG: 480x640 1 Waste, 300.9ms
Speed: 1.3ms preprocess, 300.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yE8VD_6jyQcoULMkxK4u8w_0.JPG: 480x640 (no detections), 306.2ms
Speed: 1.2ms preprocess, 306.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yE8VD_6jyQcoULMkxK4u8w_90.JPG: 480x640 (no detections), 301.3ms
Speed: 1.3ms preprocess, 301.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yE8VD_6jyQcoULMkxK4u8w_180.JPG: 480x640 (no detections), 301.5ms
Speed: 1.3ms preprocess, 301.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yE8VD_6jyQcoULMkxK4u8w_270.JPG: 480x640 (no detections), 300.2ms
Speed: 1.8ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yE8hHlfWsoYx6qRunM3ZRw_0.JPG: 480x640 (no detections), 299.7ms
Speed: 1.2ms preprocess, 299.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yE8hHlfWsoYx6qRunM3ZRw_90.JPG: 480x640 (no detections), 303.3ms
Speed: 1.2ms preprocess, 303.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yE8hHlfWsoYx6qRunM3ZRw_180.JPG: 480x640 (no detections), 302.0ms
Speed: 1.2ms preprocess, 302.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yE8hHlfWsoYx6qRunM3ZRw_270.JPG: 480x640 (no detections), 306.5ms
Speed: 1.1ms preprocess, 306.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yE9aoZYtfTTxrt2WorCZyA_0.JPG: 480x640 (no detections), 300.4ms
Speed: 2.1ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yE9aoZYtfTTxrt2WorCZyA_90.JPG: 480x640 (no detections), 301.1ms
Speed: 1.2ms preprocess, 301.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yE9aoZYtfTTxrt2WorCZyA_180.JPG: 480x640 (no detections), 304.4ms
Speed: 1.2ms preprocess, 304.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yE9aoZYtfTTxrt2WorCZyA_270.JPG: 480x640 (no detections), 374.7ms
Speed: 1.3ms preprocess, 374.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEDSiHnF2uId8YUl4b5iow_0.JPG: 480x640 (no detections), 311.9ms
Speed: 1.1ms preprocess, 311.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEDSiHnF2uId8YUl4b5iow_90.JPG: 480x640 1 Waste, 302.0ms
Speed: 1.2ms preprocess, 302.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEDSiHnF2uId8YUl4b5iow_180.JPG: 480x640 1 Waste, 299.9ms
Speed: 1.1ms preprocess, 299.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEDSiHnF2uId8YUl4b5iow_270.JPG: 480x640 (no detections), 298.4ms
Speed: 1.0ms preprocess, 298.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEEVlZfy09ZTBPRLUX3vFw_0.JPG: 480x640 (no detections), 300.5ms
Speed: 1.4ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEEVlZfy09ZTBPRLUX3vFw_90.JPG: 480x640 (no detections), 303.0ms
Speed: 1.2ms preprocess, 303.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEEVlZfy09ZTBPRLUX3vFw_180.JPG: 480x640 (no detections), 298.6ms

Speed: 1.1ms preprocess, 298.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEEVlZfy09ZTBPRLUX3vFw_270.JPG: 480x640 (no detections), 299.2ms
Speed: 1.1ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEHukhiMwHNC-ZrCVYrCnQ_0.JPG: 480x640 (no detections), 302.7ms
Speed: 1.1ms preprocess, 302.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEHukhiMwHNC-ZrCVYrCnQ_90.JPG: 480x640 (no detections), 306.0ms
Speed: 1.1ms preprocess, 306.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEHukhiMwHNC-ZrCVYrCnQ_180.JPG: 480x640 (no detections), 299.5ms
Speed: 1.2ms preprocess, 299.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEHukhiMwHNC-ZrCVYrCnQ_270.JPG: 480x640 (no detections), 300.9ms
Speed: 1.1ms preprocess, 300.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEKvuePWXSeVZmsDRD640A_0.JPG: 480x640 (no detections), 300.2ms
Speed: 1.2ms preprocess, 300.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEKvuePWXSeVZmsDRD640A_90.JPG: 480x640 (no detections), 300.0ms
Speed: 1.7ms preprocess, 300.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEKvuePWXSeVZmsDRD640A_180.JPG: 480x640 (no detections), 302.6ms
Speed: 1.2ms preprocess, 302.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEKvuePWXSeVZmsDRD640A_270.JPG: 480x640 (no detections), 300.3ms
Speed: 1.2ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yELz5HFY_8toE2z62Yi_Sg_0.JPG: 480x640 (no detections), 298.8ms
Speed: 1.3ms preprocess, 298.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yELz5HFY_8toE2z62Yi_Sg_90.JPG: 480x640 (no detections), 301.6ms
Speed: 1.2ms preprocess, 301.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yELz5HFY_8toE2z62Yi_Sg_180.JPG: 480x640 (no detections), 298.6ms
Speed: 1.4ms preprocess, 298.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yELz5HFY_8toE2z62Yi_Sg_270.JPG: 480x640 (no detections), 302.4ms
Speed: 1.5ms preprocess, 302.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEMJ6_YjM22gmckoC1ZLpA_0.JPG: 480x640 (no detections), 296.1ms
Speed: 1.2ms preprocess, 296.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEMJ6_YjM22gmckoC1ZLpA_90.JPG: 480x640 (no detections), 307.6ms
Speed: 1.4ms preprocess, 307.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEMJ6_YjM22gmckoC1ZLpA_180.JPG: 480x640 (no detections), 309.0ms
Speed: 1.3ms preprocess, 309.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEMJ6_YjM22gmckoC1ZLpA_270.JPG: 480x640 (no detections), 302.6ms
Speed: 1.2ms preprocess, 302.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEM_HT2LdkfNHabItlvd8Q_0.JPG: 480x640 (no detections), 299.4ms
Speed: 1.3ms preprocess, 299.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEM_HT2LdkfNHabItlvd8Q_90.JPG: 480x640 (no detections), 309.7ms
Speed: 1.4ms preprocess, 309.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEM_HT2LdkfNHabItlvd8Q_180.JPG: 480x640 (no detections), 305.4ms
Speed: 1.1ms preprocess, 305.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEM_HT2LdkfNHabItlvd8Q_270.JPG: 480x640 (no detections), 301.2ms
Speed: 1.4ms preprocess, 301.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yENlNWjhfTr8fBo686wcGA_0.JPG: 480x640 (no detections), 298.1ms
Speed: 1.3ms preprocess, 298.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yENlNWjhfTr8fBo686wcGA_90.JPG: 480x640 (no detections), 306.2ms
Speed: 1.3ms preprocess, 306.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yENlNWjhfTr8fBo686wcGA_180.JPG: 480x640 (no detections), 305.7ms
Speed: 1.3ms preprocess, 305.7ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yENlNWjhfTr8fBo686wcGA_270.JPG: 480x640 (no detections), 306.4ms
Speed: 1.6ms preprocess, 306.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEXBV0b_lGq3JqN0TWqtJw_0.JPG: 480x640 (no detections), 302.1ms
Speed: 1.1ms preprocess, 302.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEXBV0b_lGq3JqN0TWqtJw_90.JPG: 480x640 (no detections), 303.1ms
Speed: 1.2ms preprocess, 303.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEXBV0b_lGq3JqN0TWqtJw_180.JPG: 480x640 (no detections), 301.1ms
Speed: 1.2ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEXBV0b_lGq3JqN0TWqtJw_270.JPG: 480x640 (no detections), 297.7ms
Speed: 1.1ms preprocess, 297.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEXaUt5VCMfsSyJwqacAyw_0.JPG: 480x640 (no detections), 306.6ms
Speed: 1.1ms preprocess, 306.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEXaUt5VCMfsSyJwqacAyw_90.JPG: 480x640 2 Wastes, 300.3ms
Speed: 1.2ms preprocess, 300.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEXaUt5VCMfsSyJwqacAyw_180.JPG: 480x640 (no detections), 304.5ms
Speed: 1.4ms preprocess, 304.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEXaUt5VCMfsSyJwqacAyw_270.JPG: 480x640 (no detections), 305.0ms
Speed: 1.3ms preprocess, 305.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEgd9fQINMUez5qd-QdorA_0.JPG: 480x640 (no detections), 305.3ms
Speed: 1.3ms preprocess, 305.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEgd9fQINMUez5qd-QdorA_90.JPG: 480x640 (no detections), 301.6ms
Speed: 1.1ms preprocess, 301.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEgd9fQINMUez5qd-QdorA_180.JPG: 480x640 (no detections), 302.2ms
Speed: 1.5ms preprocess, 302.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEgd9fQINMUez5qd-QdorA_270.JPG: 480x640 (no detections), 307.4ms
Speed: 1.3ms preprocess, 307.4ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEiO9OdvRwALb7qRkvaPCg_0.JPG: 480x640 (no detections), 304.3ms
Speed: 1.3ms preprocess, 304.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEiO9OdvRwALb7qRkvaPCg_90.JPG: 480x640 (no detections), 303.1ms
Speed: 1.3ms preprocess, 303.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEiO9OdvRwALb7qRkvaPCg_180.JPG: 480x640 (no detections), 306.3ms
Speed: 1.4ms preprocess, 306.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEiO9OdvRwALb7qRkvaPCg_270.JPG: 480x640 (no detections), 304.1ms
Speed: 1.1ms preprocess, 304.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEjFdX75i8Rdzn90eZCC5g_0.JPG: 480x640 (no detections), 297.7ms
Speed: 1.2ms preprocess, 297.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEjFdX75i8Rdzn90eZCC5g_90.JPG: 480x640 (no detections), 302.8ms
Speed: 1.1ms preprocess, 302.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEjFdX75i8Rdzn90eZCC5g_180.JPG: 480x640 (no detections), 303.6ms
Speed: 1.3ms preprocess, 303.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEjFdX75i8Rdzn90eZCC5g_270.JPG: 480x640 (no detections), 300.7ms
Speed: 1.2ms preprocess, 300.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEj_AMhGMVypHxyxpcmcCw_0.JPG: 480x640 (no detections), 302.0ms
Speed: 1.1ms preprocess, 302.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEj_AMhGMVypHxyxpcmcCw_90.JPG: 480x640 (no detections), 300.4ms
Speed: 1.5ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEj_AMhGMVypHxyxpcmcCw_180.JPG: 480x640 (no detections), 303.0ms
Speed: 1.6ms preprocess, 303.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEj_AMhGMVypHxyxpcmcCw_270.JPG: 480x640 (no detections), 301.7ms
Speed: 1.9ms preprocess, 301.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEnijPxnaMxvvlQ9Tw86vQ_0.JPG: 480x640 (no detections), 304.6ms
Speed: 1.1ms preprocess, 304.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEnijPxnaMxvvlQ9Tw86vQ_90.JPG: 480x640 (no detections), 307.6ms
Speed: 1.5ms preprocess, 307.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEnijPxnaMxvvlQ9Tw86vQ_180.JPG: 480x640 (no detections), 302.1ms
Speed: 1.2ms preprocess, 302.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEnijPxnaMxvvlQ9Tw86vQ_270.JPG: 480x640 (no detections), 302.6ms
Speed: 1.1ms preprocess, 302.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEo7gza4D1o9ZMEcPNRe0A_0.JPG: 480x640 (no detections), 299.6ms
Speed: 1.6ms preprocess, 299.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEo7gza4D1o9ZMEcPNRe0A_90.JPG: 480x640 (no detections), 300.2ms
Speed: 1.1ms preprocess, 300.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEo7gza4D1o9ZMEcPNRe0A_180.JPG: 480x640 (no detections), 298.1ms
Speed: 1.3ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEo7gza4D1o9ZMEcPNRe0A_270.JPG: 480x640 (no detections), 303.6ms
Speed: 1.1ms preprocess, 303.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEuqssPGvazusRm7S2QttA_0.JPG: 480x640 (no detections), 300.0ms
Speed: 1.3ms preprocess, 300.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEuqssPGvazusRm7S2QttA_90.JPG: 480x640 (no detections), 303.0ms
Speed: 1.5ms preprocess, 303.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEuqssPGvazusRm7S2QttA_180.JPG: 480x640 (no detections), 302.1ms
Speed: 1.8ms preprocess, 302.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEuqssPGvazusRm7S2QttA_270.JPG: 480x640 (no detections), 304.0ms
Speed: 1.4ms preprocess, 304.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEwWzicrbgnyZqlYScOZiQ_0.JPG: 480x640 (no detections), 308.7ms
Speed: 1.6ms preprocess, 308.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEwWzicrbgnyZqlYScOZiQ_90.JPG: 480x640 (no detections), 303.0ms
Speed: 1.2ms preprocess, 303.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEwWzicrbgnyZqlYScOZiQ_180.JPG: 480x640 (no detections), 303.5ms
Speed: 1.4ms preprocess, 303.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEwWzicrbgnyZqlYScOZiQ_270.JPG: 480x640 (no detections), 305.4ms
Speed: 1.3ms preprocess, 305.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEwdQNO-0EqcHANzPje6xw_0.JPG: 480x640 (no detections), 301.4ms
Speed: 1.4ms preprocess, 301.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEwdQNO-0EqcHANzPje6xw_90.JPG: 480x640 (no detections), 299.8ms

Speed: 1.1ms preprocess, 299.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEwdQNO-0EqcHANzPje6xw_180.JPG: 480x640 (no detections), 305.1ms
Speed: 1.1ms preprocess, 305.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEwdQNO-0EqcHANzPje6xw_270.JPG: 480x640 (no detections), 303.3ms
Speed: 1.2ms preprocess, 303.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEylLu_28lT8SkmCcr_msA_0.JPG: 480x640 (no detections), 313.2ms
Speed: 1.2ms preprocess, 313.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEylLu_28lT8SkmCcr_msA_90.JPG: 480x640 (no detections), 308.7ms
Speed: 1.2ms preprocess, 308.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEylLu_28lT8SkmCcr_msA_180.JPG: 480x640 (no detections), 303.0ms
Speed: 1.3ms preprocess, 303.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yEylLu_28lT8SkmCcr_msA_270.JPG: 480x640 (no detections), 301.5ms
Speed: 1.3ms preprocess, 301.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yF6SflG4SW8vNeEPNgKqCg_0.JPG: 480x640 1 Waste, 303.2ms
Speed: 1.2ms preprocess, 303.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yF6SflG4SW8vNeEPNgKqCg_90.JPG: 480x640 (no detections), 302.5ms
Speed: 1.3ms preprocess, 302.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yF6SflG4SW8vNeEPNgKqCg_180.JPG: 480x640 (no detections), 301.7ms
Speed: 1.3ms preprocess, 301.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yF6SflG4SW8vNeEPNgKqCg_270.JPG: 480x640 (no detections), 301.8ms
Speed: 1.1ms preprocess, 301.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFCMYDQM54GrsZT_tMjL9g_0.JPG: 480x640 (no detections), 306.9ms
Speed: 1.1ms preprocess, 306.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFCMYDQM54GrsZT_tMjL9g_90.JPG: 480x640 (no detections), 299.6ms
Speed: 1.3ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFCMYDQM54GrsZT_tMjL9g_180.JPG: 480x640 (no detections), 299.1ms
Speed: 1.1ms preprocess, 299.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFCMYDQM54GrsZT_tMjL9g_270.JPG: 480x640 (no detections), 304.7ms
Speed: 1.2ms preprocess, 304.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFE3KKodf27RpZZmYtCoZQ_0.JPG: 480x640 1 Waste, 297.8ms
Speed: 1.8ms preprocess, 297.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFE3KKodf27RpZZmYtCoZQ_90.JPG: 480x640 (no detections), 297.4ms
Speed: 1.2ms preprocess, 297.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFE3KKodf27RpZZmYtCoZQ_180.JPG: 480x640 (no detections), 308.9ms
Speed: 1.4ms preprocess, 308.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFE3KKodf27RpZZmYtCoZQ_270.JPG: 480x640 (no detections), 305.3ms
Speed: 1.1ms preprocess, 305.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFFNOCgpXub1A0JxbJk-RQ_0.JPG: 480x640 (no detections), 300.1ms
Speed: 1.1ms preprocess, 300.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFFNOCgpXub1A0JxbJk-RQ_90.JPG: 480x640 (no detections), 306.5ms
Speed: 1.0ms preprocess, 306.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFFNOCgpXub1A0JxbJk-RQ_180.JPG: 480x640 (no detections), 303.7ms
Speed: 1.4ms preprocess, 303.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFFNOCgpXub1A0JxbJk-RQ_270.JPG: 480x640 (no detections), 298.5ms
Speed: 1.2ms preprocess, 298.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFJDmrTFxZbrJfZ91u1ChA_0.JPG: 480x640 (no detections), 302.8ms
Speed: 1.1ms preprocess, 302.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFJDmrTFxZbrJfZ91u1ChA_90.JPG: 480x640 (no detections), 301.5ms
Speed: 1.2ms preprocess, 301.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFJDmrTFxZbrJfZ91u1ChA_180.JPG: 480x640 (no detections), 302.5ms
Speed: 1.0ms preprocess, 302.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFJDmrTFxZbrJfZ91u1ChA_270.JPG: 480x640 (no detections), 304.5ms
Speed: 1.3ms preprocess, 304.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFKVboBD1NK5UNi8jbYj6g_0.JPG: 480x640 (no detections), 301.6ms
Speed: 1.2ms preprocess, 301.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFKVboBD1NK5UNi8jbYj6g_90.JPG: 480x640 (no detections), 305.0ms
Speed: 1.2ms preprocess, 305.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFKVboBD1NK5UNi8jbYj6g_180.JPG: 480x640 (no detections), 299.8ms
Speed: 1.5ms preprocess, 299.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFKVboBD1NK5UNi8jbYj6g_270.JPG: 480x640 (no detections), 311.1ms
Speed: 1.4ms preprocess, 311.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFLB1VB1WHODu9-sSf-lXA_0.JPG: 480x640 (no detections), 301.6ms
Speed: 1.2ms preprocess, 301.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFLB1VB1WHODu9-sSf-lXA_90.JPG: 480x640 (no detections), 302.2ms
Speed: 1.2ms preprocess, 302.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFLB1VB1WHODu9-sSf-lXA_180.JPG: 480x640 (no detections), 302.1ms
Speed: 1.2ms preprocess, 302.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFLB1VB1WHODu9-sSf-lXA_270.JPG: 480x640 (no detections), 296.6ms
Speed: 1.1ms preprocess, 296.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFMltgNGNmlKv35NBHZUxg_0.JPG: 480x640 (no detections), 305.4ms
Speed: 1.3ms preprocess, 305.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFMltgNGNmlKv35NBHZUxg_90.JPG: 480x640 (no detections), 304.4ms
Speed: 1.4ms preprocess, 304.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFMltgNGNmlKv35NBHZUxg_180.JPG: 480x640 (no detections), 302.5ms
Speed: 1.1ms preprocess, 302.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFMltgNGNmlKv35NBHZUxg_270.JPG: 480x640 (no detections), 301.1ms
Speed: 1.2ms preprocess, 301.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFOyzvrv28yv7YmO_ik7qw_0.JPG: 480x640 (no detections), 301.3ms
Speed: 1.3ms preprocess, 301.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFOyzvrv28yv7YmO_ik7qw_90.JPG: 480x640 (no detections), 301.5ms
Speed: 1.1ms preprocess, 301.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFOyzvrv28yv7YmO_ik7qw_180.JPG: 480x640 (no detections), 302.6ms
Speed: 1.2ms preprocess, 302.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFOyzvrv28yv7YmO_ik7qw_270.JPG: 480x640 (no detections), 297.2ms
Speed: 1.1ms preprocess, 297.2ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFTQX-9RnQduGf4Ua9KsWQ_0.JPG: 480x640 (no detections), 304.3ms
Speed: 1.3ms preprocess, 304.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFTQX-9RnQduGf4Ua9KsWQ_90.JPG: 480x640 (no detections), 304.0ms
Speed: 1.0ms preprocess, 304.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFTQX-9RnQduGf4Ua9KsWQ_180.JPG: 480x640 (no detections), 302.1ms
Speed: 1.3ms preprocess, 302.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFTQX-9RnQduGf4Ua9KsWQ_270.JPG: 480x640 (no detections), 300.3ms
Speed: 1.7ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFXPKQ4nLQM0aQLlTkOeiw_0.JPG: 480x640 (no detections), 298.1ms
Speed: 1.2ms preprocess, 298.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFXPKQ4nLQM0aQLlTkOeiw_90.JPG: 480x640 (no detections), 298.4ms
Speed: 1.0ms preprocess, 298.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFXPKQ4nLQM0aQLlTkOeiw_180.JPG: 480x640 (no detections), 299.8ms
Speed: 1.1ms preprocess, 299.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFXPKQ4nLQM0aQLlTkOeiw_270.JPG: 480x640 (no detections), 303.2ms
Speed: 1.1ms preprocess, 303.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFaW5SlTz0Jidmv1i9g0Nw_0.JPG: 480x640 (no detections), 299.0ms
Speed: 1.1ms preprocess, 299.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFaW5SlTz0Jidmv1i9g0Nw_90.JPG: 480x640 (no detections), 300.3ms
Speed: 1.0ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFaW5SlTz0Jidmv1i9g0Nw_180.JPG: 480x640 (no detections), 300.5ms
Speed: 1.2ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFaW5SlTz0Jidmv1i9g0Nw_270.JPG: 480x640 (no detections), 302.5ms
Speed: 1.2ms preprocess, 302.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFbWPqD2vrYAAAQrDCEKag_0.JPG: 480x640 (no detections), 300.4ms
Speed: 1.0ms preprocess, 300.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFbWPqD2vrYAAAQrDCEKag_90.JPG: 480x640 (no detections), 307.8ms
Speed: 1.4ms preprocess, 307.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFbWPqD2vrYAAAQrDCEKag_180.JPG: 480x640 (no detections), 301.2ms
Speed: 1.0ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFbWPqD2vrYAAAQrDCEKag_270.JPG: 480x640 (no detections), 297.4ms
Speed: 1.0ms preprocess, 297.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFfcOPeGTkQOtm9zxjpMUw_0.JPG: 480x640 2 Wastes, 299.7ms
Speed: 1.3ms preprocess, 299.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFfcOPeGTkQOtm9zxjpMUw_90.JPG: 480x640 (no detections), 300.1ms
Speed: 1.1ms preprocess, 300.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFfcOPeGTkQOtm9zxjpMUw_180.JPG: 480x640 (no detections), 301.6ms
Speed: 1.1ms preprocess, 301.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFfcOPeGTkQOtm9zxjpMUw_270.JPG: 480x640 (no detections), 302.4ms
Speed: 1.1ms preprocess, 302.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFg-oHNnJghCXSwGEvjQcw_0.JPG: 480x640 (no detections), 300.2ms
Speed: 1.9ms preprocess, 300.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFg-oHNnJghCXSwGEvjQcw_90.JPG: 480x640 (no detections), 297.9ms
Speed: 1.1ms preprocess, 297.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFg-oHNnJghCXSwGEvjQcw_180.JPG: 480x640 (no detections), 306.3ms
Speed: 1.3ms preprocess, 306.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFg-oHNnJghCXSwGEvjQcw_270.JPG: 480x640 (no detections), 300.7ms
Speed: 1.2ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFhT2S30R7cDjCx1ojkb2A_0.JPG: 480x640 (no detections), 301.5ms

Speed: 1.1ms preprocess, 301.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFhT2S30R7cDjCx1ojkb2A_90.JPG: 480x640 (no detections), 301.6ms
Speed: 1.4ms preprocess, 301.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFhT2S30R7cDjCx1ojkb2A_180.JPG: 480x640 (no detections), 303.6ms
Speed: 1.4ms preprocess, 303.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFhT2S30R7cDjCx1ojkb2A_270.JPG: 480x640 (no detections), 299.4ms
Speed: 1.4ms preprocess, 299.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFjBI3oMGFt7OX27nN39dA_0.JPG: 480x640 (no detections), 297.8ms
Speed: 1.1ms preprocess, 297.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFjBI3oMGFt7OX27nN39dA_90.JPG: 480x640 (no detections), 299.9ms
Speed: 1.0ms preprocess, 299.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFjBI3oMGFt7OX27nN39dA_180.JPG: 480x640 (no detections), 301.0ms
Speed: 1.7ms preprocess, 301.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFjBI3oMGFt7OX27nN39dA_270.JPG: 480x640 (no detections), 300.0ms
Speed: 1.3ms preprocess, 300.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFkWOOL5_cqb9BYfX3ZPcg_0.JPG: 480x640 (no detections), 299.0ms
Speed: 1.1ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFkWOOL5_cqb9BYfX3ZPcg_90.JPG: 480x640 (no detections), 298.0ms
Speed: 1.2ms preprocess, 298.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFkWOOL5_cqb9BYfX3ZPcg_180.JPG: 480x640 (no detections), 302.2ms
Speed: 1.3ms preprocess, 302.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFkWOOL5_cqb9BYfX3ZPcg_270.JPG: 480x640 (no detections), 300.0ms
Speed: 1.1ms preprocess, 300.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFp4Hmve1nb90Fw1Cs5tTA_0.JPG: 480x640 (no detections), 299.7ms
Speed: 1.2ms preprocess, 299.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFp4Hmve1nb90Fw1Cs5tTA_90.JPG: 480x640 1 Waste, 301.5ms
Speed: 1.2ms preprocess, 301.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFp4Hmve1nb90Fw1Cs5tTA_180.JPG: 480x640 (no detections), 303.3ms
Speed: 1.1ms preprocess, 303.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFp4Hmve1nb90Fw1Cs5tTA_270.JPG: 480x640 (no detections), 302.4ms
Speed: 1.2ms preprocess, 302.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFrZUCvwQhw8QhRHuGcpBQ_0.JPG: 480x640 (no detections), 306.6ms
Speed: 1.7ms preprocess, 306.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFrZUCvwQhw8QhRHuGcpBQ_90.JPG: 480x640 (no detections), 298.9ms
Speed: 1.5ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFrZUCvwQhw8QhRHuGcpBQ_180.JPG: 480x640 (no detections), 298.5ms
Speed: 1.2ms preprocess, 298.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFrZUCvwQhw8QhRHuGcpBQ_270.JPG: 480x640 1 Waste, 301.6ms
Speed: 1.3ms preprocess, 301.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFrc9jwOwkxQ2lTPsL9Yxg_0.JPG: 480x640 (no detections), 300.1ms
Speed: 1.1ms preprocess, 300.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFrc9jwOwkxQ2lTPsL9Yxg_90.JPG: 480x640 (no detections), 297.5ms
Speed: 1.2ms preprocess, 297.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFrc9jwOwkxQ2lTPsL9Yxg_180.JPG: 480x640 (no detections), 307.2ms
Speed: 1.1ms preprocess, 307.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFrc9jwOwkxQ2lTPsL9Yxg_270.JPG: 480x640 (no detections), 303.9ms
Speed: 1.3ms preprocess, 303.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFscVnU5EiraaGv3rlst1g_0.JPG: 480x640 (no detections), 294.4ms
Speed: 1.2ms preprocess, 294.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFscVnU5EiraaGv3rlst1g_90.JPG: 480x640 (no detections), 306.4ms
Speed: 1.3ms preprocess, 306.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFscVnU5EiraaGv3rlst1g_180.JPG: 480x640 (no detections), 301.8ms
Speed: 1.1ms preprocess, 301.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFscVnU5EiraaGv3rlst1g_270.JPG: 480x640 (no detections), 306.5ms
Speed: 2.0ms preprocess, 306.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFu4STgL2tj23L2pd0KbDA_0.JPG: 480x640 (no detections), 300.9ms
Speed: 1.1ms preprocess, 300.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFu4STgL2tj23L2pd0KbDA_90.JPG: 480x640 (no detections), 306.6ms
Speed: 1.2ms preprocess, 306.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFu4STgL2tj23L2pd0KbDA_180.JPG: 480x640 (no detections), 304.3ms
Speed: 1.1ms preprocess, 304.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yFu4STgL2tj23L2pd0KbDA_270.JPG: 480x640 (no detections), 300.2ms
Speed: 1.2ms preprocess, 300.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yG00hLfvotlvoZF5R-ytnw_0.JPG: 480x640 (no detections), 302.0ms
Speed: 1.2ms preprocess, 302.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yG00hLfvotlvoZF5R-ytnw_90.JPG: 480x640 (no detections), 300.3ms
Speed: 1.1ms preprocess, 300.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yG00hLfvotlvoZF5R-ytnw_180.JPG: 480x640 (no detections), 301.0ms
Speed: 1.0ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yG00hLfvotlvoZF5R-ytnw_270.JPG: 480x640 (no detections), 303.0ms
Speed: 1.4ms preprocess, 303.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yG1xW-vOYi_-pxQ2EQ6IPg_0.JPG: 480x640 (no detections), 302.0ms
Speed: 1.3ms preprocess, 302.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yG1xW-vOYi_-pxQ2EQ6IPg_90.JPG: 480x640 (no detections), 297.8ms
Speed: 1.4ms preprocess, 297.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yG1xW-vOYi_-pxQ2EQ6IPg_180.JPG: 480x640 (no detections), 297.1ms
Speed: 1.2ms preprocess, 297.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yG1xW-vOYi_-pxQ2EQ6IPg_270.JPG: 480x640 (no detections), 298.9ms
Speed: 1.1ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yG2jkT1YX63lr72q9AhgVQ_0.JPG: 480x640 (no detections), 298.6ms
Speed: 1.1ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yG2jkT1YX63lr72q9AhgVQ_90.JPG: 480x640 (no detections), 300.8ms
Speed: 1.2ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yG2jkT1YX63lr72q9AhgVQ_180.JPG: 480x640 (no detections), 303.6ms
Speed: 1.4ms preprocess, 303.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yG2jkT1YX63lr72q9AhgVQ_270.JPG: 480x640 (no detections), 302.1ms
Speed: 1.1ms preprocess, 302.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yG3QnSf07FJWXSJV5_8ppg_0.JPG: 480x640 (no detections), 299.7ms
Speed: 1.2ms preprocess, 299.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yG3QnSf07FJWXSJV5_8ppg_90.JPG: 480x640 1 Waste, 311.5ms
Speed: 1.0ms preprocess, 311.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yG3QnSf07FJWXSJV5_8ppg_180.JPG: 480x640 (no detections), 298.8ms
Speed: 1.0ms preprocess, 298.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yG3QnSf07FJWXSJV5_8ppg_270.JPG: 480x640 (no detections), 298.9ms
Speed: 1.2ms preprocess, 298.9ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yG58Xf2ns9jfHKnDewq8uQ_0.JPG: 480x640 (no detections), 298.5ms
Speed: 1.4ms preprocess, 298.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yG58Xf2ns9jfHKnDewq8uQ_90.JPG: 480x640 (no detections), 300.9ms
Speed: 1.2ms preprocess, 300.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yG58Xf2ns9jfHKnDewq8uQ_180.JPG: 480x640 (no detections), 300.4ms
Speed: 1.1ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yG58Xf2ns9jfHKnDewq8uQ_270.JPG: 480x640 (no detections), 304.5ms
Speed: 1.2ms preprocess, 304.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yG5tCt0pM3YbjWSjxRzw_w_0.JPG: 480x640 (no detections), 298.3ms
Speed: 1.2ms preprocess, 298.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yG5tCt0pM3YbjWSjxRzw_w_90.JPG: 480x640 (no detections), 301.7ms
Speed: 1.5ms preprocess, 301.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yG5tCt0pM3YbjWSjxRzw_w_180.JPG: 480x640 (no detections), 302.4ms
Speed: 1.1ms preprocess, 302.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yG5tCt0pM3YbjWSjxRzw_w_270.JPG: 480x640 (no detections), 306.7ms
Speed: 1.2ms preprocess, 306.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yG7XlNqd0k2hV2eF4RNkiw_0.JPG: 480x640 (no detections), 302.6ms
Speed: 1.4ms preprocess, 302.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yG7XlNqd0k2hV2eF4RNkiw_90.JPG: 480x640 (no detections), 300.6ms
Speed: 1.2ms preprocess, 300.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yG7XlNqd0k2hV2eF4RNkiw_180.JPG: 480x640 (no detections), 293.9ms
Speed: 1.1ms preprocess, 293.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yG7XlNqd0k2hV2eF4RNkiw_270.JPG: 480x640 (no detections), 304.1ms
Speed: 1.2ms preprocess, 304.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yG8MAv5OsyAu7PDaigFrZw_0.JPG: 480x640 (no detections), 301.2ms
Speed: 1.1ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yG8MAv5OsyAu7PDaigFrZw_90.JPG: 480x640 (no detections), 302.1ms
Speed: 1.3ms preprocess, 302.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yG8MAv5OsyAu7PDaigFrZw_180.JPG: 480x640 (no detections), 295.0ms
Speed: 1.1ms preprocess, 295.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yG8MAv5OsyAu7PDaigFrZw_270.JPG: 480x640 (no detections), 300.5ms
Speed: 1.5ms preprocess, 300.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yG8j1ig3hZqzdez27-IxzQ_0.JPG: 480x640 (no detections), 301.2ms
Speed: 1.3ms preprocess, 301.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yG8j1ig3hZqzdez27-IxzQ_90.JPG: 480x640 (no detections), 297.7ms
Speed: 1.3ms preprocess, 297.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yG8j1ig3hZqzdez27-IxzQ_180.JPG: 480x640 (no detections), 301.4ms
Speed: 1.1ms preprocess, 301.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yG8j1ig3hZqzdez27-IxzQ_270.JPG: 480x640 (no detections), 292.7ms

Speed: 1.4ms preprocess, 292.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGC0_pvZY32zkz-zV5yr4g_0.JPG: 480x640 (no detections), 304.4ms
Speed: 1.6ms preprocess, 304.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGC0_pvZY32zkz-zV5yr4g_90.JPG: 480x640 (no detections), 298.3ms
Speed: 1.3ms preprocess, 298.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGC0_pvZY32zkz-zV5yr4g_180.JPG: 480x640 (no detections), 302.3ms
Speed: 1.2ms preprocess, 302.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGC0_pvZY32zkz-zV5yr4g_270.JPG: 480x640 (no detections), 303.1ms
Speed: 1.1ms preprocess, 303.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGCDCoUpF5MH1rGYkoYl0A_0.JPG: 480x640 2 Wastes, 300.0ms
Speed: 1.1ms preprocess, 300.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGCDCoUpF5MH1rGYkoYl0A_90.JPG: 480x640 (no detections), 302.8ms
Speed: 1.1ms preprocess, 302.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGCDCoUpF5MH1rGYkoYl0A_180.JPG: 480x640 (no detections), 295.5ms
Speed: 1.1ms preprocess, 295.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGCDCoUpF5MH1rGYkoYl0A_270.JPG: 480x640 (no detections), 303.3ms
Speed: 1.1ms preprocess, 303.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGEFQqGoLGmGtKqwwyu8_Q_0.JPG: 480x640 (no detections), 302.2ms
Speed: 1.3ms preprocess, 302.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGEFQqGoLGmGtKqwwyu8_Q_90.JPG: 480x640 (no detections), 298.1ms
Speed: 1.2ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGEFQqGoLGmGtKqwwyu8_Q_180.JPG: 480x640 1 Waste, 302.3ms
Speed: 1.3ms preprocess, 302.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGEFQqGoLGmGtKqwwyu8_Q_270.JPG: 480x640 (no detections), 301.7ms
Speed: 1.3ms preprocess, 301.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGFJ4P_xwkkbVDYSNtyQbQ_0.JPG: 480x640 (no detections), 298.8ms
Speed: 1.3ms preprocess, 298.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGFJ4P_xwkkbVDYSNtyQbQ_90.JPG: 480x640 1 Waste, 305.0ms
Speed: 1.3ms preprocess, 305.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGFJ4P_xwkkbVDYSNtyQbQ_180.JPG: 480x640 (no detections), 301.4ms
Speed: 1.2ms preprocess, 301.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGFJ4P_xwkkbVDYSNtyQbQ_270.JPG: 480x640 1 Waste, 298.2ms
Speed: 1.0ms preprocess, 298.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGH7kUOEG0CXgpv13EI3mA_0.JPG: 480x640 (no detections), 300.4ms
Speed: 1.1ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGH7kUOEG0CXgpv13EI3mA_90.JPG: 480x640 (no detections), 301.6ms
Speed: 1.2ms preprocess, 301.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGH7kUOEG0CXgpv13EI3mA_180.JPG: 480x640 (no detections), 301.6ms
Speed: 1.3ms preprocess, 301.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGH7kUOEG0CXgpv13EI3mA_270.JPG: 480x640 (no detections), 302.2ms
Speed: 1.2ms preprocess, 302.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGIgtvfN6_5J15FXmiXxJA_0.JPG: 480x640 (no detections), 302.4ms
Speed: 1.2ms preprocess, 302.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGIgtvfN6_5J15FXmiXxJA_90.JPG: 480x640 (no detections), 304.3ms
Speed: 1.4ms preprocess, 304.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGIgtvfN6_5J15FXmiXxJA_180.JPG: 480x640 (no detections), 301.3ms
Speed: 1.2ms preprocess, 301.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGIgtvfN6_5J15FXmiXxJA_270.JPG: 480x640 (no detections), 297.4ms
Speed: 1.2ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGJoCTTeh455IJj2fmjP9A_0.JPG: 480x640 (no detections), 299.7ms
Speed: 1.0ms preprocess, 299.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGJoCTTeh455IJj2fmjP9A_90.JPG: 480x640 (no detections), 303.9ms
Speed: 1.1ms preprocess, 303.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGJoCTTeh455IJj2fmjP9A_180.JPG: 480x640 (no detections), 307.9ms
Speed: 1.5ms preprocess, 307.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGJoCTTeh455IJj2fmjP9A_270.JPG: 480x640 (no detections), 300.0ms
Speed: 1.1ms preprocess, 300.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGKLyWHD3ot9qQUQt8DPtA_0.JPG: 480x640 (no detections), 301.4ms
Speed: 1.2ms preprocess, 301.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGKLyWHD3ot9qQUQt8DPtA_90.JPG: 480x640 (no detections), 305.8ms
Speed: 1.1ms preprocess, 305.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGKLyWHD3ot9qQUQt8DPtA_180.JPG: 480x640 (no detections), 303.3ms
Speed: 1.2ms preprocess, 303.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGKLyWHD3ot9qQUQt8DPtA_270.JPG: 480x640 (no detections), 298.3ms
Speed: 1.2ms preprocess, 298.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGMcl3PpYhfVmGDPFmRDHA_0.JPG: 480x640 (no detections), 299.2ms
Speed: 1.2ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGMcl3PpYhfVmGDPFmRDHA_90.JPG: 480x640 (no detections), 299.9ms
Speed: 1.7ms preprocess, 299.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGMcl3PpYhfVmGDPFmRDHA_180.JPG: 480x640 (no detections), 302.8ms
Speed: 1.1ms preprocess, 302.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGMcl3PpYhfVmGDPFmRDHA_270.JPG: 480x640 (no detections), 302.2ms
Speed: 1.2ms preprocess, 302.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGNRLVjDd7CFQ0P_s5-SQg_0.JPG: 480x640 (no detections), 299.6ms
Speed: 1.3ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGNRLVjDd7CFQ0P_s5-SQg_90.JPG: 480x640 (no detections), 300.9ms
Speed: 1.2ms preprocess, 300.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGNRLVjDd7CFQ0P_s5-SQg_180.JPG: 480x640 (no detections), 302.8ms
Speed: 1.2ms preprocess, 302.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGNRLVjDd7CFQ0P_s5-SQg_270.JPG: 480x640 (no detections), 305.8ms
Speed: 1.1ms preprocess, 305.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGRl7m5E4Lu-c73wC-ijWA_0.JPG: 480x640 (no detections), 300.0ms
Speed: 1.3ms preprocess, 300.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGRl7m5E4Lu-c73wC-ijWA_90.JPG: 480x640 (no detections), 299.3ms
Speed: 1.3ms preprocess, 299.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGRl7m5E4Lu-c73wC-ijWA_180.JPG: 480x640 (no detections), 297.9ms
Speed: 1.4ms preprocess, 297.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGRl7m5E4Lu-c73wC-ijWA_270.JPG: 480x640 (no detections), 303.9ms
Speed: 1.1ms preprocess, 303.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGS-JMh5OcxctCfGUE8HwA_0.JPG: 480x640 (no detections), 300.5ms
Speed: 1.2ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGS-JMh5OcxctCfGUE8HwA_90.JPG: 480x640 (no detections), 301.4ms
Speed: 1.3ms preprocess, 301.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGS-JMh5OcxctCfGUE8HwA_180.JPG: 480x640 (no detections), 303.0ms
Speed: 1.2ms preprocess, 303.0ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGS-JMh5OcxctCfGUE8HwA_270.JPG: 480x640 (no detections), 306.1ms
Speed: 1.2ms preprocess, 306.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGTEo3qyQ559_3WSsru-RQ_0.JPG: 480x640 (no detections), 304.9ms
Speed: 1.2ms preprocess, 304.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGTEo3qyQ559_3WSsru-RQ_90.JPG: 480x640 (no detections), 302.2ms
Speed: 1.2ms preprocess, 302.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGTEo3qyQ559_3WSsru-RQ_180.JPG: 480x640 (no detections), 301.7ms
Speed: 1.4ms preprocess, 301.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGTEo3qyQ559_3WSsru-RQ_270.JPG: 480x640 (no detections), 299.2ms
Speed: 1.2ms preprocess, 299.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGYIQLO05m-sWSi5KXs9Uw_0.JPG: 480x640 (no detections), 298.8ms
Speed: 1.0ms preprocess, 298.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGYIQLO05m-sWSi5KXs9Uw_90.JPG: 480x640 (no detections), 307.0ms
Speed: 1.2ms preprocess, 307.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGYIQLO05m-sWSi5KXs9Uw_180.JPG: 480x640 (no detections), 301.4ms
Speed: 1.2ms preprocess, 301.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGYIQLO05m-sWSi5KXs9Uw_270.JPG: 480x640 (no detections), 299.8ms
Speed: 1.3ms preprocess, 299.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGYdqq9DKynOo56YUSztfg_0.JPG: 480x640 (no detections), 300.9ms
Speed: 1.2ms preprocess, 300.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGYdqq9DKynOo56YUSztfg_90.JPG: 480x640 (no detections), 302.3ms
Speed: 1.2ms preprocess, 302.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGYdqq9DKynOo56YUSztfg_180.JPG: 480x640 (no detections), 302.3ms
Speed: 1.3ms preprocess, 302.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGYdqq9DKynOo56YUSztfg_270.JPG: 480x640 (no detections), 302.2ms
Speed: 1.3ms preprocess, 302.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGZK2Twz_CF8l6a7IWclkQ_0.JPG: 480x640 (no detections), 303.7ms
Speed: 1.0ms preprocess, 303.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGZK2Twz_CF8l6a7IWclkQ_90.JPG: 480x640 (no detections), 302.9ms
Speed: 1.3ms preprocess, 302.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGZK2Twz_CF8l6a7IWclkQ_180.JPG: 480x640 (no detections), 301.1ms
Speed: 1.1ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGZK2Twz_CF8l6a7IWclkQ_270.JPG: 480x640 (no detections), 299.4ms
Speed: 1.8ms preprocess, 299.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGcJ-REwQPfIh_M6p6JDlw_0.JPG: 480x640 (no detections), 302.0ms
Speed: 1.5ms preprocess, 302.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGcJ-REwQPfIh_M6p6JDlw_90.JPG: 480x640 (no detections), 309.6ms
Speed: 1.2ms preprocess, 309.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGcJ-REwQPfIh_M6p6JDlw_180.JPG: 480x640 (no detections), 304.6ms

Speed: 1.1ms preprocess, 304.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGcJ-REwQPfIh_M6p6JDlw_270.JPG: 480x640 (no detections), 300.0ms
Speed: 1.2ms preprocess, 300.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGdWNvT-fGw0P_gYgTMuTg_0.JPG: 480x640 (no detections), 300.3ms
Speed: 1.3ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGdWNvT-fGw0P_gYgTMuTg_90.JPG: 480x640 (no detections), 301.0ms
Speed: 1.3ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGdWNvT-fGw0P_gYgTMuTg_180.JPG: 480x640 (no detections), 295.1ms
Speed: 1.3ms preprocess, 295.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGdWNvT-fGw0P_gYgTMuTg_270.JPG: 480x640 (no detections), 308.0ms
Speed: 1.1ms preprocess, 308.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGg3GSdsNU9jEudjDZB0mQ_0.JPG: 480x640 (no detections), 306.4ms
Speed: 1.4ms preprocess, 306.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGg3GSdsNU9jEudjDZB0mQ_90.JPG: 480x640 (no detections), 296.3ms
Speed: 1.4ms preprocess, 296.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGg3GSdsNU9jEudjDZB0mQ_180.JPG: 480x640 (no detections), 300.4ms
Speed: 1.3ms preprocess, 300.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGg3GSdsNU9jEudjDZB0mQ_270.JPG: 480x640 (no detections), 303.0ms
Speed: 1.0ms preprocess, 303.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGg5JOiEOpfFyPrqKMJQug_0.JPG: 480x640 (no detections), 303.8ms
Speed: 1.2ms preprocess, 303.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGg5JOiEOpfFyPrqKMJQug_90.JPG: 480x640 (no detections), 301.0ms
Speed: 1.2ms preprocess, 301.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGg5JOiEOpfFyPrqKMJQug_180.JPG: 480x640 (no detections), 306.4ms
Speed: 1.3ms preprocess, 306.4ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGg5JOiEOpfFyPrqKMJQug_270.JPG: 480x640 (no detections), 304.3ms
Speed: 1.2ms preprocess, 304.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGglPOCQ8uykHVaE6GmteQ_0.JPG: 480x640 1 Waste, 306.5ms
Speed: 1.2ms preprocess, 306.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGglPOCQ8uykHVaE6GmteQ_90.JPG: 480x640 (no detections), 304.5ms
Speed: 1.5ms preprocess, 304.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGglPOCQ8uykHVaE6GmteQ_180.JPG: 480x640 (no detections), 303.7ms
Speed: 1.2ms preprocess, 303.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGglPOCQ8uykHVaE6GmteQ_270.JPG: 480x640 (no detections), 305.5ms
Speed: 1.7ms preprocess, 305.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGgo4jwYezALnh0rFNlVqg_0.JPG: 480x640 (no detections), 300.9ms
Speed: 1.4ms preprocess, 300.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGgo4jwYezALnh0rFNlVqg_90.JPG: 480x640 (no detections), 313.8ms
Speed: 1.3ms preprocess, 313.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGgo4jwYezALnh0rFNlVqg_180.JPG: 480x640 (no detections), 311.6ms
Speed: 1.3ms preprocess, 311.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGgo4jwYezALnh0rFNlVqg_270.JPG: 480x640 (no detections), 380.4ms
Speed: 2.0ms preprocess, 380.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGmFh6m8BuOK-aGU20Jkwg_0.JPG: 480x640 (no detections), 301.8ms
Speed: 1.4ms preprocess, 301.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGmFh6m8BuOK-aGU20Jkwg_90.JPG: 480x640 (no detections), 303.9ms
Speed: 1.2ms preprocess, 303.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGmFh6m8BuOK-aGU20Jkwg_180.JPG: 480x640 (no detections), 299.1ms
Speed: 1.1ms preprocess, 299.1ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGmFh6m8BuOK-aGU20Jkwg_270.JPG: 480x640 (no detections), 302.2ms
Speed: 1.2ms preprocess, 302.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGoZSEnvK56gPRHvececpw_0.JPG: 480x640 (no detections), 301.0ms
Speed: 1.9ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGoZSEnvK56gPRHvececpw_90.JPG: 480x640 (no detections), 301.1ms
Speed: 1.2ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGoZSEnvK56gPRHvececpw_180.JPG: 480x640 (no detections), 305.8ms
Speed: 1.2ms preprocess, 305.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGoZSEnvK56gPRHvececpw_270.JPG: 480x640 (no detections), 301.2ms
Speed: 1.1ms preprocess, 301.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGpECmLQoaoiL7TgLYF2ag_0.JPG: 480x640 (no detections), 298.1ms
Speed: 1.0ms preprocess, 298.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGpECmLQoaoiL7TgLYF2ag_90.JPG: 480x640 (no detections), 301.1ms
Speed: 1.2ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGpECmLQoaoiL7TgLYF2ag_180.JPG: 480x640 (no detections), 302.9ms
Speed: 1.2ms preprocess, 302.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGpECmLQoaoiL7TgLYF2ag_270.JPG: 480x640 (no detections), 298.0ms
Speed: 1.1ms preprocess, 298.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGrzAab_PN6KZ-Hr9VGwYQ_0.JPG: 480x640 (no detections), 302.2ms
Speed: 1.2ms preprocess, 302.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGrzAab_PN6KZ-Hr9VGwYQ_90.JPG: 480x640 (no detections), 305.8ms
Speed: 1.0ms preprocess, 305.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGrzAab_PN6KZ-Hr9VGwYQ_180.JPG: 480x640 (no detections), 304.7ms
Speed: 1.5ms preprocess, 304.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGrzAab_PN6KZ-Hr9VGwYQ_270.JPG: 480x640 (no detections), 300.7ms
Speed: 1.2ms preprocess, 300.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGuJCVF12xNfzPuZygbiDA_0.JPG: 480x640 1 Waste, 303.6ms
Speed: 1.3ms preprocess, 303.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGuJCVF12xNfzPuZygbiDA_90.JPG: 480x640 (no detections), 306.1ms
Speed: 1.3ms preprocess, 306.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGuJCVF12xNfzPuZygbiDA_180.JPG: 480x640 (no detections), 304.5ms
Speed: 1.1ms preprocess, 304.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGuJCVF12xNfzPuZygbiDA_270.JPG: 480x640 (no detections), 296.9ms
Speed: 1.2ms preprocess, 296.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGv19mRiUsMnvhf7xtLqMQ_0.JPG: 480x640 (no detections), 302.9ms
Speed: 1.8ms preprocess, 302.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGv19mRiUsMnvhf7xtLqMQ_90.JPG: 480x640 (no detections), 302.7ms
Speed: 1.2ms preprocess, 302.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGv19mRiUsMnvhf7xtLqMQ_180.JPG: 480x640 (no detections), 311.8ms
Speed: 2.2ms preprocess, 311.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGv19mRiUsMnvhf7xtLqMQ_270.JPG: 480x640 (no detections), 305.5ms
Speed: 1.2ms preprocess, 305.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGvRmNzZdd9Z9A0HPuV8JQ_0.JPG: 480x640 (no detections), 301.5ms
Speed: 1.1ms preprocess, 301.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGvRmNzZdd9Z9A0HPuV8JQ_90.JPG: 480x640 (no detections), 303.5ms
Speed: 1.3ms preprocess, 303.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGvRmNzZdd9Z9A0HPuV8JQ_180.JPG: 480x640 (no detections), 301.6ms
Speed: 1.2ms preprocess, 301.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGvRmNzZdd9Z9A0HPuV8JQ_270.JPG: 480x640 (no detections), 300.5ms
Speed: 1.4ms preprocess, 300.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGwO2z0koYN6seGSQpzsVg_0.JPG: 480x640 (no detections), 302.7ms
Speed: 1.2ms preprocess, 302.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGwO2z0koYN6seGSQpzsVg_90.JPG: 480x640 1 Waste, 304.8ms
Speed: 1.2ms preprocess, 304.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGwO2z0koYN6seGSQpzsVg_180.JPG: 480x640 (no detections), 308.0ms
Speed: 1.3ms preprocess, 308.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGwO2z0koYN6seGSQpzsVg_270.JPG: 480x640 (no detections), 303.2ms
Speed: 1.2ms preprocess, 303.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGxO95gw9HbbTyc4eTTEzA_0.JPG: 480x640 (no detections), 307.2ms
Speed: 1.5ms preprocess, 307.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGxO95gw9HbbTyc4eTTEzA_90.JPG: 480x640 (no detections), 298.9ms
Speed: 1.1ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGxO95gw9HbbTyc4eTTEzA_180.JPG: 480x640 (no detections), 301.1ms
Speed: 1.1ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGxO95gw9HbbTyc4eTTEzA_270.JPG: 480x640 (no detections), 301.4ms
Speed: 1.1ms preprocess, 301.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGxn5LGIUDpuBELGisT9Rg_0.JPG: 480x640 (no detections), 299.8ms
Speed: 1.1ms preprocess, 299.8ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGxn5LGIUDpuBELGisT9Rg_90.JPG: 480x640 (no detections), 302.7ms
Speed: 1.1ms preprocess, 302.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGxn5LGIUDpuBELGisT9Rg_180.JPG: 480x640 (no detections), 302.5ms
Speed: 1.2ms preprocess, 302.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGxn5LGIUDpuBELGisT9Rg_270.JPG: 480x640 (no detections), 305.6ms
Speed: 1.1ms preprocess, 305.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGz_iaR53GvltVvc7PL6cg_0.JPG: 480x640 (no detections), 298.8ms
Speed: 1.1ms preprocess, 298.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGz_iaR53GvltVvc7PL6cg_90.JPG: 480x640 (no detections), 305.8ms
Speed: 1.1ms preprocess, 305.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGz_iaR53GvltVvc7PL6cg_180.JPG: 480x640 (no detections), 307.5ms
Speed: 1.5ms preprocess, 307.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGz_iaR53GvltVvc7PL6cg_270.JPG: 480x640 (no detections), 306.6ms
Speed: 1.1ms preprocess, 306.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGzaDjhz9WYoA2oEu3X5Jg_0.JPG: 480x640 (no detections), 299.9ms
Speed: 1.4ms preprocess, 299.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGzaDjhz9WYoA2oEu3X5Jg_90.JPG: 480x640 (no detections), 303.5ms

Speed: 1.3ms preprocess, 303.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGzaDjhz9WYoA2oEu3X5Jg_180.JPG: 480x640 (no detections), 302.9ms
Speed: 1.0ms preprocess, 302.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yGzaDjhz9WYoA2oEu3X5Jg_270.JPG: 480x640 (no detections), 306.8ms
Speed: 1.1ms preprocess, 306.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yH-Kx0VHwTiA5LOsYzSaZQ_0.JPG: 480x640 (no detections), 310.1ms
Speed: 1.3ms preprocess, 310.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yH-Kx0VHwTiA5LOsYzSaZQ_90.JPG: 480x640 (no detections), 302.5ms
Speed: 1.1ms preprocess, 302.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yH-Kx0VHwTiA5LOsYzSaZQ_180.JPG: 480x640 (no detections), 300.6ms
Speed: 1.2ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yH-Kx0VHwTiA5LOsYzSaZQ_270.JPG: 480x640 (no detections), 303.7ms
Speed: 1.1ms preprocess, 303.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yH-RtEuyqKuNtqi5ua0ZwA_0.JPG: 480x640 (no detections), 306.5ms
Speed: 1.1ms preprocess, 306.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yH-RtEuyqKuNtqi5ua0ZwA_90.JPG: 480x640 (no detections), 299.9ms
Speed: 1.4ms preprocess, 299.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yH-RtEuyqKuNtqi5ua0ZwA_180.JPG: 480x640 (no detections), 304.7ms
Speed: 1.1ms preprocess, 304.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yH-RtEuyqKuNtqi5ua0ZwA_270.JPG: 480x640 (no detections), 298.4ms
Speed: 1.1ms preprocess, 298.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yH4Osa_Bb4ND7OLsC08jUA_0.JPG: 480x640 (no detections), 307.7ms
Speed: 1.4ms preprocess, 307.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yH4Osa_Bb4ND7OLsC08jUA_90.JPG: 480x640 (no detections), 313.0ms
Speed: 1.4ms preprocess, 313.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yH4Osa_Bb4ND7OLsC08jUA_180.JPG: 480x640 (no detections), 312.1ms
Speed: 1.2ms preprocess, 312.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yH4Osa_Bb4ND7OLsC08jUA_270.JPG: 480x640 (no detections), 307.4ms
Speed: 1.3ms preprocess, 307.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yH6EffZ3dritiSnVyW0cUQ_0.JPG: 480x640 (no detections), 304.7ms
Speed: 1.5ms preprocess, 304.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yH6EffZ3dritiSnVyW0cUQ_90.JPG: 480x640 (no detections), 303.5ms
Speed: 1.3ms preprocess, 303.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yH6EffZ3dritiSnVyW0cUQ_180.JPG: 480x640 (no detections), 302.4ms
Speed: 1.3ms preprocess, 302.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yH6EffZ3dritiSnVyW0cUQ_270.JPG: 480x640 (no detections), 303.0ms
Speed: 1.3ms preprocess, 303.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yH7PZFSqJjetB1EfUN3v8Q_0.JPG: 480x640 (no detections), 321.3ms
Speed: 1.6ms preprocess, 321.3ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yH7PZFSqJjetB1EfUN3v8Q_90.JPG: 480x640 (no detections), 309.0ms
Speed: 2.0ms preprocess, 309.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yH7PZFSqJjetB1EfUN3v8Q_180.JPG: 480x640 (no detections), 309.5ms
Speed: 1.2ms preprocess, 309.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yH7PZFSqJjetB1EfUN3v8Q_270.JPG: 480x640 (no detections), 303.0ms
Speed: 1.1ms preprocess, 303.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yH9EXCGqPSNXWTR6ovQpsA_0.JPG: 480x640 (no detections), 307.6ms
Speed: 1.1ms preprocess, 307.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yH9EXCGqPSNXWTR6ovQpsA_90.JPG: 480x640 (no detections), 301.4ms
Speed: 1.5ms preprocess, 301.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yH9EXCGqPSNXWTR6ovQpsA_180.JPG: 480x640 (no detections), 301.1ms
Speed: 1.1ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yH9EXCGqPSNXWTR6ovQpsA_270.JPG: 480x640 (no detections), 304.0ms
Speed: 1.1ms preprocess, 304.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yH9hUlG_tpXNsnsUNyK-iQ_0.JPG: 480x640 (no detections), 313.4ms
Speed: 1.1ms preprocess, 313.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yH9hUlG_tpXNsnsUNyK-iQ_90.JPG: 480x640 (no detections), 302.6ms
Speed: 1.2ms preprocess, 302.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yH9hUlG_tpXNsnsUNyK-iQ_180.JPG: 480x640 (no detections), 304.5ms
Speed: 1.1ms preprocess, 304.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yH9hUlG_tpXNsnsUNyK-iQ_270.JPG: 480x640 (no detections), 302.4ms
Speed: 1.5ms preprocess, 302.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHF_1MEwNonlXjDewuB1MA_0.JPG: 480x640 (no detections), 304.2ms
Speed: 1.1ms preprocess, 304.2ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHF_1MEwNonlXjDewuB1MA_90.JPG: 480x640 (no detections), 302.2ms
Speed: 1.4ms preprocess, 302.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHF_1MEwNonlXjDewuB1MA_180.JPG: 480x640 (no detections), 305.5ms
Speed: 1.1ms preprocess, 305.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHF_1MEwNonlXjDewuB1MA_270.JPG: 480x640 (no detections), 302.5ms
Speed: 1.2ms preprocess, 302.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHFx5FJaR8zhOEkiDSvOZA_0.JPG: 480x640 (no detections), 303.9ms
Speed: 1.1ms preprocess, 303.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHFx5FJaR8zhOEkiDSvOZA_90.JPG: 480x640 (no detections), 309.0ms
Speed: 1.6ms preprocess, 309.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHFx5FJaR8zhOEkiDSvOZA_180.JPG: 480x640 (no detections), 307.8ms
Speed: 1.4ms preprocess, 307.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHFx5FJaR8zhOEkiDSvOZA_270.JPG: 480x640 (no detections), 307.3ms
Speed: 1.1ms preprocess, 307.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHK3wZNrxxrC5ptbhVd0dw_0.JPG: 480x640 (no detections), 306.1ms
Speed: 1.3ms preprocess, 306.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHK3wZNrxxrC5ptbhVd0dw_90.JPG: 480x640 (no detections), 300.0ms
Speed: 1.5ms preprocess, 300.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHK3wZNrxxrC5ptbhVd0dw_180.JPG: 480x640 (no detections), 300.4ms
Speed: 1.1ms preprocess, 300.4ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHK3wZNrxxrC5ptbhVd0dw_270.JPG: 480x640 1 Waste, 302.3ms
Speed: 1.2ms preprocess, 302.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHKZSB_k6qkcbQjV7d06tA_0.JPG: 480x640 (no detections), 302.0ms
Speed: 1.2ms preprocess, 302.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHKZSB_k6qkcbQjV7d06tA_90.JPG: 480x640 (no detections), 301.2ms
Speed: 1.6ms preprocess, 301.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHKZSB_k6qkcbQjV7d06tA_180.JPG: 480x640 (no detections), 299.2ms
Speed: 1.2ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHKZSB_k6qkcbQjV7d06tA_270.JPG: 480x640 (no detections), 298.6ms
Speed: 1.2ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHLEsJmA5dmuKi8H7-MqUQ_0.JPG: 480x640 (no detections), 298.8ms
Speed: 1.0ms preprocess, 298.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHLEsJmA5dmuKi8H7-MqUQ_90.JPG: 480x640 (no detections), 301.1ms
Speed: 1.1ms preprocess, 301.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHLEsJmA5dmuKi8H7-MqUQ_180.JPG: 480x640 (no detections), 302.7ms
Speed: 1.3ms preprocess, 302.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHLEsJmA5dmuKi8H7-MqUQ_270.JPG: 480x640 (no detections), 309.6ms
Speed: 1.3ms preprocess, 309.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHPwt1tQEZ8s5EPlyDS0Lg_0.JPG: 480x640 (no detections), 302.9ms
Speed: 1.2ms preprocess, 302.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHPwt1tQEZ8s5EPlyDS0Lg_90.JPG: 480x640 (no detections), 318.2ms
Speed: 1.1ms preprocess, 318.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHPwt1tQEZ8s5EPlyDS0Lg_180.JPG: 480x640 (no detections), 295.3ms
Speed: 1.1ms preprocess, 295.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHPwt1tQEZ8s5EPlyDS0Lg_270.JPG: 480x640 (no detections), 307.6ms
Speed: 1.2ms preprocess, 307.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHRvJDF8n6U2A0ljzp7pQg_0.JPG: 480x640 (no detections), 305.9ms
Speed: 1.5ms preprocess, 305.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHRvJDF8n6U2A0ljzp7pQg_90.JPG: 480x640 (no detections), 309.8ms
Speed: 1.4ms preprocess, 309.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHRvJDF8n6U2A0ljzp7pQg_180.JPG: 480x640 (no detections), 304.3ms
Speed: 1.2ms preprocess, 304.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHRvJDF8n6U2A0ljzp7pQg_270.JPG: 480x640 (no detections), 304.6ms
Speed: 1.3ms preprocess, 304.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHVJVsThKQaF_Hzj4CbtIQ_0.JPG: 480x640 (no detections), 307.5ms
Speed: 1.2ms preprocess, 307.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHVJVsThKQaF_Hzj4CbtIQ_90.JPG: 480x640 (no detections), 307.2ms
Speed: 1.1ms preprocess, 307.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHVJVsThKQaF_Hzj4CbtIQ_180.JPG: 480x640 (no detections), 304.9ms
Speed: 1.4ms preprocess, 304.9ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHVJVsThKQaF_Hzj4CbtIQ_270.JPG: 480x640 (no detections), 317.0ms
Speed: 1.3ms preprocess, 317.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHYoav-Vhjn7n-efpvNxzA_0.JPG: 480x640 (no detections), 315.1ms
Speed: 1.2ms preprocess, 315.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHYoav-Vhjn7n-efpvNxzA_90.JPG: 480x640 (no detections), 344.8ms
Speed: 1.6ms preprocess, 344.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHYoav-Vhjn7n-efpvNxzA_180.JPG: 480x640 (no detections), 320.9ms
Speed: 1.5ms preprocess, 320.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHYoav-Vhjn7n-efpvNxzA_270.JPG: 480x640 (no detections), 335.9ms
Speed: 1.2ms preprocess, 335.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHYzawFmwGl9ZUATahGY-w_0.JPG: 480x640 (no detections), 324.3ms

Speed: 1.3ms preprocess, 324.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHYzawFmwGl9ZUATahGY-w_90.JPG: 480x640 (no detections), 332.3ms
Speed: 1.1ms preprocess, 332.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHYzawFmwGl9ZUATahGY-w_180.JPG: 480x640 (no detections), 316.8ms
Speed: 1.6ms preprocess, 316.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHYzawFmwGl9ZUATahGY-w_270.JPG: 480x640 (no detections), 310.1ms
Speed: 1.1ms preprocess, 310.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHfARTXV2mnGCeV03_tPhg_0.JPG: 480x640 (no detections), 309.3ms
Speed: 1.3ms preprocess, 309.3ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHfARTXV2mnGCeV03_tPhg_90.JPG: 480x640 (no detections), 307.3ms
Speed: 1.3ms preprocess, 307.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHfARTXV2mnGCeV03_tPhg_180.JPG: 480x640 (no detections), 295.9ms
Speed: 1.3ms preprocess, 295.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHfARTXV2mnGCeV03_tPhg_270.JPG: 480x640 (no detections), 299.2ms
Speed: 1.4ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHfSJxd-pwCR44atbNj-wg_0.JPG: 480x640 (no detections), 302.5ms
Speed: 1.3ms preprocess, 302.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHfSJxd-pwCR44atbNj-wg_90.JPG: 480x640 (no detections), 296.7ms
Speed: 1.1ms preprocess, 296.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHfSJxd-pwCR44atbNj-wg_180.JPG: 480x640 (no detections), 301.5ms
Speed: 1.1ms preprocess, 301.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHfSJxd-pwCR44atbNj-wg_270.JPG: 480x640 (no detections), 302.3ms
Speed: 1.1ms preprocess, 302.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHffz9_xWstFiZtMCq7Sbg_0.JPG: 480x640 (no detections), 299.1ms
Speed: 1.3ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHffz9_xWstFiZtMCq7Sbg_90.JPG: 480x640 (no detections), 302.8ms
Speed: 1.6ms preprocess, 302.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHffz9_xWstFiZtMCq7Sbg_180.JPG: 480x640 1 Waste, 300.0ms
Speed: 1.4ms preprocess, 300.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHffz9_xWstFiZtMCq7Sbg_270.JPG: 480x640 (no detections), 296.9ms
Speed: 1.1ms preprocess, 296.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHhp1WB3mfvtFkgB6MIdvg_0.JPG: 480x640 (no detections), 299.6ms
Speed: 1.4ms preprocess, 299.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHhp1WB3mfvtFkgB6MIdvg_90.JPG: 480x640 (no detections), 296.0ms
Speed: 1.1ms preprocess, 296.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHhp1WB3mfvtFkgB6MIdvg_180.JPG: 480x640 (no detections), 298.9ms
Speed: 1.3ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHhp1WB3mfvtFkgB6MIdvg_270.JPG: 480x640 (no detections), 297.9ms
Speed: 1.2ms preprocess, 297.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHhwNuiY-658bDMBukM0Zw_0.JPG: 480x640 (no detections), 301.4ms
Speed: 1.1ms preprocess, 301.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHhwNuiY-658bDMBukM0Zw_90.JPG: 480x640 (no detections), 301.9ms
Speed: 1.2ms preprocess, 301.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHhwNuiY-658bDMBukM0Zw_180.JPG: 480x640 (no detections), 297.0ms
Speed: 1.2ms preprocess, 297.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHhwNuiY-658bDMBukM0Zw_270.JPG: 480x640 (no detections), 305.7ms
Speed: 1.4ms preprocess, 305.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHiPXRYW9b0CKiz3zazdqQ_0.JPG: 480x640 (no detections), 305.8ms
Speed: 1.1ms preprocess, 305.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHiPXRYW9b0CKiz3zazdqQ_90.JPG: 480x640 (no detections), 303.4ms
Speed: 1.6ms preprocess, 303.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHiPXRYW9b0CKiz3zazdqQ_180.JPG: 480x640 (no detections), 300.9ms
Speed: 1.2ms preprocess, 300.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHiPXRYW9b0CKiz3zazdqQ_270.JPG: 480x640 (no detections), 301.3ms
Speed: 1.1ms preprocess, 301.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHjvEkzsg_xJuoeNbh2wVw_0.JPG: 480x640 (no detections), 305.1ms
Speed: 1.1ms preprocess, 305.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHjvEkzsg_xJuoeNbh2wVw_90.JPG: 480x640 (no detections), 303.5ms
Speed: 1.3ms preprocess, 303.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHjvEkzsg_xJuoeNbh2wVw_180.JPG: 480x640 (no detections), 306.1ms
Speed: 1.3ms preprocess, 306.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHjvEkzsg_xJuoeNbh2wVw_270.JPG: 480x640 (no detections), 301.8ms
Speed: 1.2ms preprocess, 301.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHpNwHLB1OYE6GoPJTw70g_0.JPG: 480x640 (no detections), 302.3ms
Speed: 1.4ms preprocess, 302.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHpNwHLB1OYE6GoPJTw70g_90.JPG: 480x640 (no detections), 305.7ms
Speed: 1.3ms preprocess, 305.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHpNwHLB1OYE6GoPJTw70g_180.JPG: 480x640 (no detections), 302.4ms
Speed: 1.3ms preprocess, 302.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHpNwHLB1OYE6GoPJTw70g_270.JPG: 480x640 (no detections), 295.9ms
Speed: 1.1ms preprocess, 295.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHpaGX2KuO2Lhi5Cw_lq-w_0.JPG: 480x640 (no detections), 299.7ms
Speed: 1.1ms preprocess, 299.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHpaGX2KuO2Lhi5Cw_lq-w_90.JPG: 480x640 (no detections), 303.3ms
Speed: 1.1ms preprocess, 303.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHpaGX2KuO2Lhi5Cw_lq-w_180.JPG: 480x640 (no detections), 299.8ms
Speed: 1.1ms preprocess, 299.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHpaGX2KuO2Lhi5Cw_lq-w_270.JPG: 480x640 (no detections), 304.3ms
Speed: 1.3ms preprocess, 304.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHs0E8xDp7XT2oHrMPeFPQ_0.JPG: 480x640 (no detections), 301.8ms
Speed: 1.3ms preprocess, 301.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHs0E8xDp7XT2oHrMPeFPQ_90.JPG: 480x640 (no detections), 299.1ms
Speed: 1.1ms preprocess, 299.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHs0E8xDp7XT2oHrMPeFPQ_180.JPG: 480x640 (no detections), 303.4ms
Speed: 1.1ms preprocess, 303.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHs0E8xDp7XT2oHrMPeFPQ_270.JPG: 480x640 (no detections), 306.5ms
Speed: 1.1ms preprocess, 306.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHs6uavIpnmOA99jyI59ZQ_0.JPG: 480x640 (no detections), 309.3ms
Speed: 1.2ms preprocess, 309.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHs6uavIpnmOA99jyI59ZQ_90.JPG: 480x640 (no detections), 304.2ms
Speed: 1.0ms preprocess, 304.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHs6uavIpnmOA99jyI59ZQ_180.JPG: 480x640 (no detections), 308.1ms
Speed: 1.3ms preprocess, 308.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHs6uavIpnmOA99jyI59ZQ_270.JPG: 480x640 (no detections), 302.2ms
Speed: 1.2ms preprocess, 302.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHtdoUmofeGbU8-tB4Yk6g_0.JPG: 480x640 1 Waste, 306.2ms
Speed: 1.4ms preprocess, 306.2ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHtdoUmofeGbU8-tB4Yk6g_90.JPG: 480x640 (no detections), 304.2ms
Speed: 1.4ms preprocess, 304.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHtdoUmofeGbU8-tB4Yk6g_180.JPG: 480x640 (no detections), 303.7ms
Speed: 1.4ms preprocess, 303.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHtdoUmofeGbU8-tB4Yk6g_270.JPG: 480x640 (no detections), 302.7ms
Speed: 1.4ms preprocess, 302.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHvvQxW7cEWewHNO4tM8kA_0.JPG: 480x640 (no detections), 304.8ms
Speed: 1.1ms preprocess, 304.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHvvQxW7cEWewHNO4tM8kA_90.JPG: 480x640 (no detections), 306.7ms
Speed: 1.2ms preprocess, 306.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHvvQxW7cEWewHNO4tM8kA_180.JPG: 480x640 (no detections), 296.9ms
Speed: 1.1ms preprocess, 296.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHvvQxW7cEWewHNO4tM8kA_270.JPG: 480x640 (no detections), 300.7ms
Speed: 1.1ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHwMBf4PM11rC2EuzkZvOg_0.JPG: 480x640 (no detections), 301.8ms
Speed: 1.1ms preprocess, 301.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHwMBf4PM11rC2EuzkZvOg_90.JPG: 480x640 (no detections), 298.5ms
Speed: 1.1ms preprocess, 298.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHwMBf4PM11rC2EuzkZvOg_180.JPG: 480x640 (no detections), 301.1ms
Speed: 1.1ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHwMBf4PM11rC2EuzkZvOg_270.JPG: 480x640 (no detections), 302.0ms
Speed: 1.3ms preprocess, 302.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHxxPy3YFjOApbLhFy9new_0.JPG: 480x640 (no detections), 305.2ms
Speed: 1.2ms preprocess, 305.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHxxPy3YFjOApbLhFy9new_90.JPG: 480x640 (no detections), 300.9ms
Speed: 1.2ms preprocess, 300.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHxxPy3YFjOApbLhFy9new_180.JPG: 480x640 (no detections), 308.3ms
Speed: 1.3ms preprocess, 308.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yHxxPy3YFjOApbLhFy9new_270.JPG: 480x640 (no detections), 307.6ms
Speed: 1.4ms preprocess, 307.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yI1r6o8CjtPaxfnF3sAZUg_0.JPG: 480x640 (no detections), 302.3ms
Speed: 1.2ms preprocess, 302.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yI1r6o8CjtPaxfnF3sAZUg_90.JPG: 480x640 (no detections), 301.7ms
Speed: 1.1ms preprocess, 301.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yI1r6o8CjtPaxfnF3sAZUg_180.JPG: 480x640 (no detections), 301.9ms
Speed: 1.1ms preprocess, 301.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yI1r6o8CjtPaxfnF3sAZUg_270.JPG: 480x640 (no detections), 304.9ms

Speed: 1.2ms preprocess, 304.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yI5QXL8D0UOIi2D1bNQ8vA_0.JPG: 480x640 (no detections), 300.8ms
Speed: 1.1ms preprocess, 300.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yI5QXL8D0UOIi2D1bNQ8vA_90.JPG: 480x640 (no detections), 303.8ms
Speed: 1.0ms preprocess, 303.8ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yI5QXL8D0UOIi2D1bNQ8vA_180.JPG: 480x640 (no detections), 299.7ms
Speed: 1.1ms preprocess, 299.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yI5QXL8D0UOIi2D1bNQ8vA_270.JPG: 480x640 (no detections), 297.2ms
Speed: 1.1ms preprocess, 297.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yI5Tp4wIg_zH0VcEBo1QYA_0.JPG: 480x640 (no detections), 302.7ms
Speed: 1.2ms preprocess, 302.7ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yI5Tp4wIg_zH0VcEBo1QYA_90.JPG: 480x640 (no detections), 301.7ms
Speed: 1.2ms preprocess, 301.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yI5Tp4wIg_zH0VcEBo1QYA_180.JPG: 480x640 (no detections), 303.4ms
Speed: 1.1ms preprocess, 303.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yI5Tp4wIg_zH0VcEBo1QYA_270.JPG: 480x640 (no detections), 309.9ms
Speed: 2.0ms preprocess, 309.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yI6btVLbUydGjO3r3FpTCA_0.JPG: 480x640 (no detections), 300.4ms
Speed: 1.3ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yI6btVLbUydGjO3r3FpTCA_90.JPG: 480x640 (no detections), 298.0ms
Speed: 1.1ms preprocess, 298.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yI6btVLbUydGjO3r3FpTCA_180.JPG: 480x640 (no detections), 303.8ms
Speed: 1.3ms preprocess, 303.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yI6btVLbUydGjO3r3FpTCA_270.JPG: 480x640 (no detections), 305.2ms
Speed: 1.5ms preprocess, 305.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yI6x08USIRjtNSJ5ohHZLQ_0.JPG: 480x640 (no detections), 303.6ms
Speed: 1.2ms preprocess, 303.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yI6x08USIRjtNSJ5ohHZLQ_90.JPG: 480x640 (no detections), 311.1ms
Speed: 1.7ms preprocess, 311.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yI6x08USIRjtNSJ5ohHZLQ_180.JPG: 480x640 (no detections), 307.0ms
Speed: 1.1ms preprocess, 307.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yI6x08USIRjtNSJ5ohHZLQ_270.JPG: 480x640 1 Waste, 318.3ms
Speed: 1.4ms preprocess, 318.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIAWcAOOVZUyGMURs7EO8w_0.JPG: 480x640 (no detections), 307.2ms
Speed: 1.4ms preprocess, 307.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIAWcAOOVZUyGMURs7EO8w_90.JPG: 480x640 (no detections), 329.1ms
Speed: 1.2ms preprocess, 329.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIAWcAOOVZUyGMURs7EO8w_180.JPG: 480x640 (no detections), 333.1ms
Speed: 1.5ms preprocess, 333.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIAWcAOOVZUyGMURs7EO8w_270.JPG: 480x640 (no detections), 344.5ms
Speed: 1.2ms preprocess, 344.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIIz4aQeTN8CaiBISrf1ww_0.JPG: 480x640 2 Wastes, 356.5ms
Speed: 1.5ms preprocess, 356.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIIz4aQeTN8CaiBISrf1ww_90.JPG: 480x640 (no detections), 338.5ms
Speed: 1.1ms preprocess, 338.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIIz4aQeTN8CaiBISrf1ww_180.JPG: 480x640 (no detections), 443.2ms
Speed: 1.5ms preprocess, 443.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIIz4aQeTN8CaiBISrf1ww_270.JPG: 480x640 (no detections), 330.1ms
Speed: 1.9ms preprocess, 330.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIJDOuiYYLrCrMhOnVC_iw_0.JPG: 480x640 (no detections), 321.6ms
Speed: 1.2ms preprocess, 321.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIJDOuiYYLrCrMhOnVC_iw_90.JPG: 480x640 (no detections), 305.5ms
Speed: 1.7ms preprocess, 305.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIJDOuiYYLrCrMhOnVC_iw_180.JPG: 480x640 (no detections), 300.1ms
Speed: 1.4ms preprocess, 300.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIJDOuiYYLrCrMhOnVC_iw_270.JPG: 480x640 (no detections), 303.3ms
Speed: 1.2ms preprocess, 303.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yILDZq2Q1BZ4_kUA0Kqsqg_0.JPG: 480x640 (no detections), 301.6ms
Speed: 1.1ms preprocess, 301.6ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yILDZq2Q1BZ4_kUA0Kqsqg_90.JPG: 480x640 (no detections), 305.9ms
Speed: 1.4ms preprocess, 305.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yILDZq2Q1BZ4_kUA0Kqsqg_180.JPG: 480x640 (no detections), 324.8ms
Speed: 1.2ms preprocess, 324.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yILDZq2Q1BZ4_kUA0Kqsqg_270.JPG: 480x640 (no detections), 340.1ms
Speed: 1.3ms preprocess, 340.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIMDzTTy39j7qhSVh9a3wA_0.JPG: 480x640 (no detections), 311.4ms
Speed: 1.3ms preprocess, 311.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIMDzTTy39j7qhSVh9a3wA_90.JPG: 480x640 (no detections), 315.0ms
Speed: 1.1ms preprocess, 315.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIMDzTTy39j7qhSVh9a3wA_180.JPG: 480x640 (no detections), 313.3ms
Speed: 1.2ms preprocess, 313.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIMDzTTy39j7qhSVh9a3wA_270.JPG: 480x640 (no detections), 299.0ms
Speed: 1.6ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIWtQ6vfWjPeVxadLW0-eg_0.JPG: 480x640 (no detections), 302.0ms
Speed: 1.3ms preprocess, 302.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIWtQ6vfWjPeVxadLW0-eg_90.JPG: 480x640 (no detections), 293.0ms
Speed: 1.2ms preprocess, 293.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIWtQ6vfWjPeVxadLW0-eg_180.JPG: 480x640 (no detections), 302.3ms
Speed: 1.3ms preprocess, 302.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIWtQ6vfWjPeVxadLW0-eg_270.JPG: 480x640 (no detections), 311.1ms
Speed: 2.2ms preprocess, 311.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIX8tMN122OpRUCh2h83xw_0.JPG: 480x640 (no detections), 304.7ms
Speed: 1.5ms preprocess, 304.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIX8tMN122OpRUCh2h83xw_90.JPG: 480x640 (no detections), 301.0ms
Speed: 1.1ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIX8tMN122OpRUCh2h83xw_180.JPG: 480x640 (no detections), 303.0ms
Speed: 1.4ms preprocess, 303.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIX8tMN122OpRUCh2h83xw_270.JPG: 480x640 (no detections), 301.5ms
Speed: 1.0ms preprocess, 301.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIcK2q5kuZrF_Yb0gwFK0g_0.JPG: 480x640 (no detections), 304.2ms
Speed: 1.1ms preprocess, 304.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIcK2q5kuZrF_Yb0gwFK0g_90.JPG: 480x640 (no detections), 304.3ms
Speed: 1.2ms preprocess, 304.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIcK2q5kuZrF_Yb0gwFK0g_180.JPG: 480x640 (no detections), 297.6ms
Speed: 1.1ms preprocess, 297.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIcK2q5kuZrF_Yb0gwFK0g_270.JPG: 480x640 (no detections), 300.8ms
Speed: 1.5ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIfICOOPbZ16BkKmmmVWqA_0.JPG: 480x640 (no detections), 298.1ms
Speed: 1.0ms preprocess, 298.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIfICOOPbZ16BkKmmmVWqA_90.JPG: 480x640 (no detections), 304.2ms
Speed: 1.4ms preprocess, 304.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIfICOOPbZ16BkKmmmVWqA_180.JPG: 480x640 (no detections), 302.7ms
Speed: 1.3ms preprocess, 302.7ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIfICOOPbZ16BkKmmmVWqA_270.JPG: 480x640 (no detections), 299.9ms
Speed: 1.2ms preprocess, 299.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIgykO_TEF9IzJZ61G4Ljg_0.JPG: 480x640 (no detections), 305.5ms
Speed: 1.1ms preprocess, 305.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIgykO_TEF9IzJZ61G4Ljg_90.JPG: 480x640 (no detections), 303.1ms
Speed: 1.1ms preprocess, 303.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIgykO_TEF9IzJZ61G4Ljg_180.JPG: 480x640 (no detections), 298.9ms
Speed: 1.4ms preprocess, 298.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIgykO_TEF9IzJZ61G4Ljg_270.JPG: 480x640 (no detections), 304.1ms
Speed: 1.4ms preprocess, 304.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIhYVq1Ih4F6wWJuhU7hSQ_0.JPG: 480x640 (no detections), 301.2ms
Speed: 1.3ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIhYVq1Ih4F6wWJuhU7hSQ_90.JPG: 480x640 (no detections), 298.2ms
Speed: 2.0ms preprocess, 298.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIhYVq1Ih4F6wWJuhU7hSQ_180.JPG: 480x640 (no detections), 306.5ms
Speed: 1.2ms preprocess, 306.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIhYVq1Ih4F6wWJuhU7hSQ_270.JPG: 480x640 (no detections), 299.0ms
Speed: 1.4ms preprocess, 299.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yImmxxv_0x4M2R8vzbw97g_0.JPG: 480x640 (no detections), 296.8ms
Speed: 1.1ms preprocess, 296.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yImmxxv_0x4M2R8vzbw97g_90.JPG: 480x640 (no detections), 298.2ms
Speed: 1.1ms preprocess, 298.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yImmxxv_0x4M2R8vzbw97g_180.JPG: 480x640 (no detections), 299.9ms
Speed: 1.3ms preprocess, 299.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yImmxxv_0x4M2R8vzbw97g_270.JPG: 480x640 (no detections), 301.8ms
Speed: 1.2ms preprocess, 301.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yInPLDvYFLj9MRtJXmopZA_0.JPG: 480x640 (no detections), 301.5ms
Speed: 1.1ms preprocess, 301.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yInPLDvYFLj9MRtJXmopZA_90.JPG: 480x640 (no detections), 297.3ms
Speed: 1.2ms preprocess, 297.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yInPLDvYFLj9MRtJXmopZA_180.JPG: 480x640 (no detections), 298.4ms

Speed: 1.1ms preprocess, 298.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yInPLDvYFLj9MRtJXmopZA_270.JPG: 480x640 (no detections), 297.0ms
Speed: 1.3ms preprocess, 297.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIneaY2QS6W2sQNKT5yw9A_0.JPG: 480x640 (no detections), 303.8ms
Speed: 1.3ms preprocess, 303.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIneaY2QS6W2sQNKT5yw9A_90.JPG: 480x640 (no detections), 302.9ms
Speed: 1.2ms preprocess, 302.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIneaY2QS6W2sQNKT5yw9A_180.JPG: 480x640 (no detections), 299.1ms
Speed: 1.3ms preprocess, 299.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIneaY2QS6W2sQNKT5yw9A_270.JPG: 480x640 (no detections), 303.4ms
Speed: 1.3ms preprocess, 303.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIqYBH8X1AVzDGbML0jAOg_0.JPG: 480x640 (no detections), 305.0ms
Speed: 1.3ms preprocess, 305.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIqYBH8X1AVzDGbML0jAOg_90.JPG: 480x640 (no detections), 296.8ms
Speed: 1.1ms preprocess, 296.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIqYBH8X1AVzDGbML0jAOg_180.JPG: 480x640 (no detections), 302.1ms
Speed: 1.1ms preprocess, 302.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIqYBH8X1AVzDGbML0jAOg_270.JPG: 480x640 (no detections), 302.7ms
Speed: 1.0ms preprocess, 302.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIqjLWml6tUG05l_9hqvlQ_0.JPG: 480x640 (no detections), 308.0ms
Speed: 1.3ms preprocess, 308.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIqjLWml6tUG05l_9hqvlQ_90.JPG: 480x640 (no detections), 305.3ms
Speed: 1.5ms preprocess, 305.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIqjLWml6tUG05l_9hqvlQ_180.JPG: 480x640 (no detections), 301.4ms
Speed: 1.8ms preprocess, 301.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIqjLWml6tUG05l_9hqvlQ_270.JPG: 480x640 (no detections), 301.6ms
Speed: 1.2ms preprocess, 301.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIr6kWLhoXcLCE6MNQ7ppQ_0.JPG: 480x640 1 Waste, 300.3ms
Speed: 1.5ms preprocess, 300.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIr6kWLhoXcLCE6MNQ7ppQ_90.JPG: 480x640 (no detections), 299.9ms
Speed: 1.2ms preprocess, 299.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIr6kWLhoXcLCE6MNQ7ppQ_180.JPG: 480x640 (no detections), 300.4ms
Speed: 1.1ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIr6kWLhoXcLCE6MNQ7ppQ_270.JPG: 480x640 1 Waste, 299.7ms
Speed: 1.4ms preprocess, 299.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIrzbMlr9fITglmQyyGEzA_0.JPG: 480x640 (no detections), 303.3ms
Speed: 1.3ms preprocess, 303.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIrzbMlr9fITglmQyyGEzA_90.JPG: 480x640 (no detections), 300.0ms
Speed: 1.2ms preprocess, 300.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIrzbMlr9fITglmQyyGEzA_180.JPG: 480x640 (no detections), 301.2ms
Speed: 1.2ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIrzbMlr9fITglmQyyGEzA_270.JPG: 480x640 (no detections), 305.4ms
Speed: 1.1ms preprocess, 305.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIs2hOFLv4hGJYge-MPVSA_0.JPG: 480x640 (no detections), 310.1ms
Speed: 1.3ms preprocess, 310.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIs2hOFLv4hGJYge-MPVSA_90.JPG: 480x640 (no detections), 300.8ms
Speed: 1.2ms preprocess, 300.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIs2hOFLv4hGJYge-MPVSA_180.JPG: 480x640 (no detections), 299.9ms
Speed: 1.0ms preprocess, 299.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIs2hOFLv4hGJYge-MPVSA_270.JPG: 480x640 (no detections), 300.1ms
Speed: 1.0ms preprocess, 300.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIsnKfKxS92kGaAElgming_0.JPG: 480x640 (no detections), 309.2ms
Speed: 1.2ms preprocess, 309.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIsnKfKxS92kGaAElgming_90.JPG: 480x640 (no detections), 309.9ms
Speed: 1.1ms preprocess, 309.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIsnKfKxS92kGaAElgming_180.JPG: 480x640 (no detections), 323.7ms
Speed: 1.2ms preprocess, 323.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIsnKfKxS92kGaAElgming_270.JPG: 480x640 (no detections), 325.3ms
Speed: 1.2ms preprocess, 325.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIuqvqyWipzm8HufjXFKiQ_0.JPG: 480x640 (no detections), 307.6ms
Speed: 1.9ms preprocess, 307.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIuqvqyWipzm8HufjXFKiQ_90.JPG: 480x640 (no detections), 336.2ms
Speed: 1.0ms preprocess, 336.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIuqvqyWipzm8HufjXFKiQ_180.JPG: 480x640 (no detections), 309.4ms
Speed: 1.3ms preprocess, 309.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIuqvqyWipzm8HufjXFKiQ_270.JPG: 480x640 (no detections), 337.5ms
Speed: 1.4ms preprocess, 337.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIw3S_2hYejMhWPs3mHJVw_0.JPG: 480x640 (no detections), 353.7ms
Speed: 1.4ms preprocess, 353.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIw3S_2hYejMhWPs3mHJVw_90.JPG: 480x640 (no detections), 332.1ms
Speed: 1.6ms preprocess, 332.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIw3S_2hYejMhWPs3mHJVw_180.JPG: 480x640 (no detections), 327.9ms
Speed: 1.2ms preprocess, 327.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIw3S_2hYejMhWPs3mHJVw_270.JPG: 480x640 (no detections), 330.3ms
Speed: 1.5ms preprocess, 330.3ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIyJDhhEdwSnVqQd43QelA_0.JPG: 480x640 (no detections), 317.5ms
Speed: 1.4ms preprocess, 317.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIyJDhhEdwSnVqQd43QelA_90.JPG: 480x640 (no detections), 305.9ms
Speed: 1.3ms preprocess, 305.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIyJDhhEdwSnVqQd43QelA_180.JPG: 480x640 (no detections), 304.2ms
Speed: 1.3ms preprocess, 304.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIyJDhhEdwSnVqQd43QelA_270.JPG: 480x640 (no detections), 301.5ms
Speed: 1.5ms preprocess, 301.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIzMjEg2eIiEHIzek0A1-Q_0.JPG: 480x640 (no detections), 307.5ms
Speed: 1.1ms preprocess, 307.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIzMjEg2eIiEHIzek0A1-Q_90.JPG: 480x640 (no detections), 313.7ms
Speed: 1.3ms preprocess, 313.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIzMjEg2eIiEHIzek0A1-Q_180.JPG: 480x640 (no detections), 305.2ms
Speed: 1.1ms preprocess, 305.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yIzMjEg2eIiEHIzek0A1-Q_270.JPG: 480x640 (no detections), 301.9ms
Speed: 1.4ms preprocess, 301.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJERRChRDDQcFgjVJOGOFg_0.JPG: 480x640 (no detections), 394.2ms
Speed: 1.5ms preprocess, 394.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJERRChRDDQcFgjVJOGOFg_90.JPG: 480x640 (no detections), 302.3ms
Speed: 1.7ms preprocess, 302.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJERRChRDDQcFgjVJOGOFg_180.JPG: 480x640 (no detections), 301.5ms
Speed: 1.1ms preprocess, 301.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJERRChRDDQcFgjVJOGOFg_270.JPG: 480x640 (no detections), 298.4ms
Speed: 1.3ms preprocess, 298.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJFfjCe4s5sUWTudKo_JWA_0.JPG: 480x640 (no detections), 299.7ms
Speed: 1.4ms preprocess, 299.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJFfjCe4s5sUWTudKo_JWA_90.JPG: 480x640 (no detections), 300.3ms
Speed: 1.2ms preprocess, 300.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJFfjCe4s5sUWTudKo_JWA_180.JPG: 480x640 (no detections), 300.4ms
Speed: 1.1ms preprocess, 300.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJFfjCe4s5sUWTudKo_JWA_270.JPG: 480x640 (no detections), 299.7ms
Speed: 1.2ms preprocess, 299.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJGTGksgBSO2FLfztO4t2Q_0.JPG: 480x640 (no detections), 302.3ms
Speed: 1.5ms preprocess, 302.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJGTGksgBSO2FLfztO4t2Q_90.JPG: 480x640 (no detections), 301.1ms
Speed: 1.3ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJGTGksgBSO2FLfztO4t2Q_180.JPG: 480x640 (no detections), 299.5ms
Speed: 1.2ms preprocess, 299.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJGTGksgBSO2FLfztO4t2Q_270.JPG: 480x640 (no detections), 304.1ms
Speed: 1.1ms preprocess, 304.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJI2bJv3aINkIDTwuM3wqg_0.JPG: 480x640 (no detections), 299.7ms
Speed: 1.5ms preprocess, 299.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJI2bJv3aINkIDTwuM3wqg_90.JPG: 480x640 (no detections), 295.6ms
Speed: 1.2ms preprocess, 295.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJI2bJv3aINkIDTwuM3wqg_180.JPG: 480x640 (no detections), 297.9ms
Speed: 1.3ms preprocess, 297.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJI2bJv3aINkIDTwuM3wqg_270.JPG: 480x640 (no detections), 294.6ms
Speed: 1.2ms preprocess, 294.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJPH6Lnsgd6z2yx6P9DWTQ_0.JPG: 480x640 (no detections), 298.6ms
Speed: 1.1ms preprocess, 298.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJPH6Lnsgd6z2yx6P9DWTQ_90.JPG: 480x640 (no detections), 296.4ms
Speed: 1.7ms preprocess, 296.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJPH6Lnsgd6z2yx6P9DWTQ_180.JPG: 480x640 (no detections), 299.8ms
Speed: 1.2ms preprocess, 299.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJPH6Lnsgd6z2yx6P9DWTQ_270.JPG: 480x640 (no detections), 300.5ms
Speed: 2.1ms preprocess, 300.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJQvqkwdPRp3qIC8m6MenA_0.JPG: 480x640 (no detections), 302.8ms
Speed: 1.3ms preprocess, 302.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJQvqkwdPRp3qIC8m6MenA_90.JPG: 480x640 (no detections), 303.0ms

Speed: 1.3ms preprocess, 303.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJQvqkwdPRp3qIC8m6MenA_180.JPG: 480x640 (no detections), 298.0ms
Speed: 1.1ms preprocess, 298.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJQvqkwdPRp3qIC8m6MenA_270.JPG: 480x640 (no detections), 304.4ms
Speed: 1.2ms preprocess, 304.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJROL23Guz8I3xAgrvV_wQ_0.JPG: 480x640 (no detections), 302.3ms
Speed: 1.1ms preprocess, 302.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJROL23Guz8I3xAgrvV_wQ_90.JPG: 480x640 (no detections), 299.1ms
Speed: 1.0ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJROL23Guz8I3xAgrvV_wQ_180.JPG: 480x640 (no detections), 298.7ms
Speed: 1.4ms preprocess, 298.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJROL23Guz8I3xAgrvV_wQ_270.JPG: 480x640 (no detections), 306.2ms
Speed: 1.2ms preprocess, 306.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJRf0DPH4wpMXuGAqRnHrA_0.JPG: 480x640 (no detections), 299.2ms
Speed: 1.2ms preprocess, 299.2ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJRf0DPH4wpMXuGAqRnHrA_90.JPG: 480x640 (no detections), 307.8ms
Speed: 1.3ms preprocess, 307.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJRf0DPH4wpMXuGAqRnHrA_180.JPG: 480x640 (no detections), 305.5ms
Speed: 1.6ms preprocess, 305.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJRf0DPH4wpMXuGAqRnHrA_270.JPG: 480x640 (no detections), 303.9ms
Speed: 1.4ms preprocess, 303.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJTL4udMc8vkwrBeVkvHHg_0.JPG: 480x640 (no detections), 303.9ms
Speed: 1.1ms preprocess, 303.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJTL4udMc8vkwrBeVkvHHg_90.JPG: 480x640 (no detections), 302.8ms
Speed: 1.1ms preprocess, 302.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJTL4udMc8vkwrBeVkvHHg_180.JPG: 480x640 (no detections), 303.3ms
Speed: 1.6ms preprocess, 303.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJTL4udMc8vkwrBeVkvHHg_270.JPG: 480x640 (no detections), 302.0ms
Speed: 1.4ms preprocess, 302.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJUuBfGWO-cAf_ZJ96F5qQ_0.JPG: 480x640 (no detections), 303.7ms
Speed: 1.1ms preprocess, 303.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJUuBfGWO-cAf_ZJ96F5qQ_90.JPG: 480x640 (no detections), 303.9ms
Speed: 1.2ms preprocess, 303.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJUuBfGWO-cAf_ZJ96F5qQ_180.JPG: 480x640 (no detections), 300.9ms
Speed: 1.2ms preprocess, 300.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJUuBfGWO-cAf_ZJ96F5qQ_270.JPG: 480x640 (no detections), 302.7ms
Speed: 1.2ms preprocess, 302.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJawrk51WF3k0iYYnrm6sg_0.JPG: 480x640 (no detections), 301.5ms
Speed: 1.3ms preprocess, 301.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJawrk51WF3k0iYYnrm6sg_90.JPG: 480x640 (no detections), 299.4ms
Speed: 1.1ms preprocess, 299.4ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJawrk51WF3k0iYYnrm6sg_180.JPG: 480x640 (no detections), 301.3ms
Speed: 1.0ms preprocess, 301.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJawrk51WF3k0iYYnrm6sg_270.JPG: 480x640 (no detections), 299.1ms
Speed: 1.5ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJdMWsfDRnDf69tjZ2R4xA_0.JPG: 480x640 (no detections), 300.4ms
Speed: 1.4ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJdMWsfDRnDf69tjZ2R4xA_90.JPG: 480x640 (no detections), 300.7ms
Speed: 1.8ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJdMWsfDRnDf69tjZ2R4xA_180.JPG: 480x640 (no detections), 302.9ms
Speed: 1.2ms preprocess, 302.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJdMWsfDRnDf69tjZ2R4xA_270.JPG: 480x640 (no detections), 306.5ms
Speed: 1.2ms preprocess, 306.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJg6Vm-CeaMMtsRZ3cFZgQ_0.JPG: 480x640 (no detections), 299.5ms
Speed: 1.2ms preprocess, 299.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJg6Vm-CeaMMtsRZ3cFZgQ_90.JPG: 480x640 (no detections), 299.5ms
Speed: 1.0ms preprocess, 299.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJg6Vm-CeaMMtsRZ3cFZgQ_180.JPG: 480x640 (no detections), 304.1ms
Speed: 1.1ms preprocess, 304.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJg6Vm-CeaMMtsRZ3cFZgQ_270.JPG: 480x640 (no detections), 299.5ms
Speed: 1.1ms preprocess, 299.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJhU-wW0l2mBGGPu_Oc5vw_0.JPG: 480x640 (no detections), 301.8ms
Speed: 1.1ms preprocess, 301.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJhU-wW0l2mBGGPu_Oc5vw_90.JPG: 480x640 (no detections), 305.4ms
Speed: 1.0ms preprocess, 305.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJhU-wW0l2mBGGPu_Oc5vw_180.JPG: 480x640 (no detections), 303.0ms
Speed: 1.1ms preprocess, 303.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJhU-wW0l2mBGGPu_Oc5vw_270.JPG: 480x640 (no detections), 300.8ms
Speed: 1.1ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJj-x7pYIMY_VgG5K4extw_0.JPG: 480x640 1 Waste, 301.8ms
Speed: 1.2ms preprocess, 301.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJj-x7pYIMY_VgG5K4extw_90.JPG: 480x640 (no detections), 298.1ms
Speed: 1.1ms preprocess, 298.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJj-x7pYIMY_VgG5K4extw_180.JPG: 480x640 (no detections), 300.2ms
Speed: 1.3ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJj-x7pYIMY_VgG5K4extw_270.JPG: 480x640 (no detections), 299.1ms
Speed: 1.1ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJm9fs2ygHlwp3x8b5MCSg_0.JPG: 480x640 (no detections), 302.3ms
Speed: 1.4ms preprocess, 302.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJm9fs2ygHlwp3x8b5MCSg_90.JPG: 480x640 (no detections), 298.9ms
Speed: 1.1ms preprocess, 298.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJm9fs2ygHlwp3x8b5MCSg_180.JPG: 480x640 (no detections), 303.7ms
Speed: 1.0ms preprocess, 303.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJm9fs2ygHlwp3x8b5MCSg_270.JPG: 480x640 (no detections), 309.2ms
Speed: 1.2ms preprocess, 309.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJpDvZhTqJYefOKO2lMWkA_0.JPG: 480x640 (no detections), 302.6ms
Speed: 1.3ms preprocess, 302.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJpDvZhTqJYefOKO2lMWkA_90.JPG: 480x640 (no detections), 302.6ms
Speed: 1.3ms preprocess, 302.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJpDvZhTqJYefOKO2lMWkA_180.JPG: 480x640 (no detections), 303.0ms
Speed: 1.0ms preprocess, 303.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJpDvZhTqJYefOKO2lMWkA_270.JPG: 480x640 (no detections), 304.1ms
Speed: 1.5ms preprocess, 304.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJrBvotJNdNrlXbSA9V6QA_0.JPG: 480x640 (no detections), 299.4ms
Speed: 1.3ms preprocess, 299.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJrBvotJNdNrlXbSA9V6QA_90.JPG: 480x640 (no detections), 301.1ms
Speed: 1.1ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJrBvotJNdNrlXbSA9V6QA_180.JPG: 480x640 (no detections), 303.5ms
Speed: 1.4ms preprocess, 303.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJrBvotJNdNrlXbSA9V6QA_270.JPG: 480x640 (no detections), 303.3ms
Speed: 1.1ms preprocess, 303.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJriD2ZHSe4NMNQoDrgFxw_0.JPG: 480x640 (no detections), 304.1ms
Speed: 1.0ms preprocess, 304.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJriD2ZHSe4NMNQoDrgFxw_90.JPG: 480x640 (no detections), 299.0ms
Speed: 1.2ms preprocess, 299.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJriD2ZHSe4NMNQoDrgFxw_180.JPG: 480x640 (no detections), 299.7ms
Speed: 1.1ms preprocess, 299.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJriD2ZHSe4NMNQoDrgFxw_270.JPG: 480x640 (no detections), 297.5ms
Speed: 1.2ms preprocess, 297.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJth2_OtP45zF4Vcu4g0Uw_0.JPG: 480x640 (no detections), 303.2ms
Speed: 1.1ms preprocess, 303.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJth2_OtP45zF4Vcu4g0Uw_90.JPG: 480x640 (no detections), 301.1ms
Speed: 1.3ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJth2_OtP45zF4Vcu4g0Uw_180.JPG: 480x640 (no detections), 302.3ms
Speed: 1.2ms preprocess, 302.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJth2_OtP45zF4Vcu4g0Uw_270.JPG: 480x640 (no detections), 299.9ms
Speed: 1.3ms preprocess, 299.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJui0dgLB4hhzpblP1nJig_0.JPG: 480x640 (no detections), 298.7ms
Speed: 1.2ms preprocess, 298.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJui0dgLB4hhzpblP1nJig_90.JPG: 480x640 (no detections), 304.7ms
Speed: 1.1ms preprocess, 304.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJui0dgLB4hhzpblP1nJig_180.JPG: 480x640 (no detections), 299.0ms
Speed: 1.2ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJui0dgLB4hhzpblP1nJig_270.JPG: 480x640 (no detections), 304.0ms
Speed: 1.4ms preprocess, 304.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJvDzDcjtdgihM-ICx-5EQ_0.JPG: 480x640 (no detections), 299.4ms
Speed: 1.2ms preprocess, 299.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJvDzDcjtdgihM-ICx-5EQ_90.JPG: 480x640 (no detections), 301.5ms
Speed: 1.3ms preprocess, 301.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJvDzDcjtdgihM-ICx-5EQ_180.JPG: 480x640 (no detections), 305.9ms
Speed: 1.2ms preprocess, 305.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yJvDzDcjtdgihM-ICx-5EQ_270.JPG: 480x640 (no detections), 301.6ms
Speed: 1.1ms preprocess, 301.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yK-N2dnUgMhRchOm_Gd8ag_0.JPG: 480x640 (no detections), 303.0ms

Speed: 1.5ms preprocess, 303.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yK-N2dnUgMhRchOm_Gd8ag_90.JPG: 480x640 (no detections), 304.7ms
Speed: 1.1ms preprocess, 304.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yK-N2dnUgMhRchOm_Gd8ag_180.JPG: 480x640 (no detections), 300.1ms
Speed: 1.1ms preprocess, 300.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yK-N2dnUgMhRchOm_Gd8ag_270.JPG: 480x640 (no detections), 305.0ms
Speed: 1.1ms preprocess, 305.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yK-t7n6pznjphsp41GCelA_0.JPG: 480x640 (no detections), 298.7ms
Speed: 1.3ms preprocess, 298.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yK-t7n6pznjphsp41GCelA_90.JPG: 480x640 (no detections), 307.0ms
Speed: 1.1ms preprocess, 307.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yK-t7n6pznjphsp41GCelA_180.JPG: 480x640 (no detections), 303.5ms
Speed: 1.1ms preprocess, 303.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yK-t7n6pznjphsp41GCelA_270.JPG: 480x640 (no detections), 300.4ms
Speed: 1.6ms preprocess, 300.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yK42Uu6-7Mlw68X9Oe0B8w_0.JPG: 480x640 (no detections), 318.9ms
Speed: 1.2ms preprocess, 318.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yK42Uu6-7Mlw68X9Oe0B8w_90.JPG: 480x640 (no detections), 300.1ms
Speed: 1.2ms preprocess, 300.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yK42Uu6-7Mlw68X9Oe0B8w_180.JPG: 480x640 (no detections), 303.5ms
Speed: 1.1ms preprocess, 303.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yK42Uu6-7Mlw68X9Oe0B8w_270.JPG: 480x640 (no detections), 299.7ms
Speed: 1.2ms preprocess, 299.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yK4_jyWqOJD2dNuoQXEOYw_0.JPG: 480x640 (no detections), 301.2ms
Speed: 1.3ms preprocess, 301.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yK4_jyWqOJD2dNuoQXEOYw_90.JPG: 480x640 (no detections), 305.5ms
Speed: 1.2ms preprocess, 305.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yK4_jyWqOJD2dNuoQXEOYw_180.JPG: 480x640 (no detections), 307.3ms
Speed: 1.3ms preprocess, 307.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yK4_jyWqOJD2dNuoQXEOYw_270.JPG: 480x640 (no detections), 301.4ms
Speed: 1.1ms preprocess, 301.4ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yK8e4CNQXEyJjcata-9b0w_0.JPG: 480x640 (no detections), 311.1ms
Speed: 1.1ms preprocess, 311.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yK8e4CNQXEyJjcata-9b0w_90.JPG: 480x640 (no detections), 302.1ms
Speed: 1.4ms preprocess, 302.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yK8e4CNQXEyJjcata-9b0w_180.JPG: 480x640 (no detections), 297.9ms
Speed: 1.1ms preprocess, 297.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yK8e4CNQXEyJjcata-9b0w_270.JPG: 480x640 (no detections), 305.1ms
Speed: 1.1ms preprocess, 305.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKAw6R-e6f48fp7PjHcYdw_0.JPG: 480x640 (no detections), 300.7ms
Speed: 1.1ms preprocess, 300.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKAw6R-e6f48fp7PjHcYdw_90.JPG: 480x640 (no detections), 301.1ms
Speed: 1.2ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKAw6R-e6f48fp7PjHcYdw_180.JPG: 480x640 (no detections), 298.3ms
Speed: 1.2ms preprocess, 298.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKAw6R-e6f48fp7PjHcYdw_270.JPG: 480x640 (no detections), 302.1ms
Speed: 1.6ms preprocess, 302.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKBUwoI-Esz3PPnH8HFQbg_0.JPG: 480x640 (no detections), 301.5ms
Speed: 1.3ms preprocess, 301.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKBUwoI-Esz3PPnH8HFQbg_90.JPG: 480x640 (no detections), 302.2ms
Speed: 1.1ms preprocess, 302.2ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKBUwoI-Esz3PPnH8HFQbg_180.JPG: 480x640 (no detections), 301.3ms
Speed: 1.7ms preprocess, 301.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKBUwoI-Esz3PPnH8HFQbg_270.JPG: 480x640 (no detections), 302.4ms
Speed: 1.2ms preprocess, 302.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKBi5Qne-12Sm_nJbNgDPQ_0.JPG: 480x640 (no detections), 302.6ms
Speed: 1.1ms preprocess, 302.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKBi5Qne-12Sm_nJbNgDPQ_90.JPG: 480x640 (no detections), 300.4ms
Speed: 1.2ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKBi5Qne-12Sm_nJbNgDPQ_180.JPG: 480x640 (no detections), 300.4ms
Speed: 1.1ms preprocess, 300.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKBi5Qne-12Sm_nJbNgDPQ_270.JPG: 480x640 (no detections), 304.4ms
Speed: 1.5ms preprocess, 304.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKG6KDVny3sMMpmPu6lUHA_0.JPG: 480x640 (no detections), 300.0ms
Speed: 1.5ms preprocess, 300.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKG6KDVny3sMMpmPu6lUHA_90.JPG: 480x640 1 Waste, 302.3ms
Speed: 1.1ms preprocess, 302.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKG6KDVny3sMMpmPu6lUHA_180.JPG: 480x640 (no detections), 298.9ms
Speed: 1.1ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKG6KDVny3sMMpmPu6lUHA_270.JPG: 480x640 (no detections), 295.6ms
Speed: 1.2ms preprocess, 295.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKKWKa2obcBava-JNhCL6w_0.JPG: 480x640 (no detections), 299.9ms
Speed: 1.1ms preprocess, 299.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKKWKa2obcBava-JNhCL6w_90.JPG: 480x640 (no detections), 298.3ms
Speed: 1.1ms preprocess, 298.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKKWKa2obcBava-JNhCL6w_180.JPG: 480x640 (no detections), 302.2ms
Speed: 1.5ms preprocess, 302.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKKWKa2obcBava-JNhCL6w_270.JPG: 480x640 (no detections), 303.7ms
Speed: 1.4ms preprocess, 303.7ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKLY8uAbgCBBWRhBLuDKQg_0.JPG: 480x640 (no detections), 303.3ms
Speed: 1.1ms preprocess, 303.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKLY8uAbgCBBWRhBLuDKQg_90.JPG: 480x640 (no detections), 300.3ms
Speed: 1.1ms preprocess, 300.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKLY8uAbgCBBWRhBLuDKQg_180.JPG: 480x640 (no detections), 305.0ms
Speed: 1.1ms preprocess, 305.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKLY8uAbgCBBWRhBLuDKQg_270.JPG: 480x640 (no detections), 305.3ms
Speed: 1.3ms preprocess, 305.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKM4HYPUP2wSbQNnmzw-NQ_0.JPG: 480x640 (no detections), 301.0ms
Speed: 1.1ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKM4HYPUP2wSbQNnmzw-NQ_90.JPG: 480x640 (no detections), 306.0ms
Speed: 1.3ms preprocess, 306.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKM4HYPUP2wSbQNnmzw-NQ_180.JPG: 480x640 (no detections), 306.0ms
Speed: 1.2ms preprocess, 306.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKM4HYPUP2wSbQNnmzw-NQ_270.JPG: 480x640 (no detections), 299.2ms
Speed: 1.1ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKP5mL-11l4wKoySwzCL3Q_0.JPG: 480x640 (no detections), 300.5ms
Speed: 1.3ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKP5mL-11l4wKoySwzCL3Q_90.JPG: 480x640 (no detections), 301.0ms
Speed: 1.1ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKP5mL-11l4wKoySwzCL3Q_180.JPG: 480x640 1 Waste, 302.2ms
Speed: 1.2ms preprocess, 302.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKP5mL-11l4wKoySwzCL3Q_270.JPG: 480x640 (no detections), 304.6ms
Speed: 1.2ms preprocess, 304.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKTNTnPb4RHk6vGGJy2uzA_0.JPG: 480x640 (no detections), 309.7ms
Speed: 1.1ms preprocess, 309.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKTNTnPb4RHk6vGGJy2uzA_90.JPG: 480x640 (no detections), 304.9ms
Speed: 1.1ms preprocess, 304.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKTNTnPb4RHk6vGGJy2uzA_180.JPG: 480x640 (no detections), 298.6ms
Speed: 1.4ms preprocess, 298.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKTNTnPb4RHk6vGGJy2uzA_270.JPG: 480x640 (no detections), 303.2ms
Speed: 1.2ms preprocess, 303.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKVvBSvm3sJSv3b_zfrJBg_0.JPG: 480x640 (no detections), 300.1ms
Speed: 1.1ms preprocess, 300.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKVvBSvm3sJSv3b_zfrJBg_90.JPG: 480x640 (no detections), 304.0ms
Speed: 1.1ms preprocess, 304.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKVvBSvm3sJSv3b_zfrJBg_180.JPG: 480x640 (no detections), 297.8ms
Speed: 1.2ms preprocess, 297.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKVvBSvm3sJSv3b_zfrJBg_270.JPG: 480x640 (no detections), 300.8ms
Speed: 1.1ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKX1-Ln3FijEaslQpalYYw_0.JPG: 480x640 (no detections), 303.4ms
Speed: 1.2ms preprocess, 303.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKX1-Ln3FijEaslQpalYYw_90.JPG: 480x640 (no detections), 295.8ms
Speed: 1.1ms preprocess, 295.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKX1-Ln3FijEaslQpalYYw_180.JPG: 480x640 (no detections), 300.2ms
Speed: 1.2ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKX1-Ln3FijEaslQpalYYw_270.JPG: 480x640 (no detections), 300.8ms
Speed: 1.1ms preprocess, 300.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKZl7ML_KkEcUcwLj2_XQg_0.JPG: 480x640 (no detections), 298.1ms
Speed: 1.4ms preprocess, 298.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKZl7ML_KkEcUcwLj2_XQg_90.JPG: 480x640 (no detections), 306.4ms
Speed: 1.1ms preprocess, 306.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKZl7ML_KkEcUcwLj2_XQg_180.JPG: 480x640 (no detections), 306.2ms
Speed: 1.2ms preprocess, 306.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKZl7ML_KkEcUcwLj2_XQg_270.JPG: 480x640 (no detections), 301.1ms

Speed: 1.1ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yK_Px_u-guoUeE0Ul_ZXow_0.JPG: 480x640 (no detections), 302.7ms
Speed: 1.1ms preprocess, 302.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yK_Px_u-guoUeE0Ul_ZXow_90.JPG: 480x640 (no detections), 296.7ms
Speed: 1.2ms preprocess, 296.7ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yK_Px_u-guoUeE0Ul_ZXow_180.JPG: 480x640 (no detections), 307.7ms
Speed: 1.4ms preprocess, 307.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yK_Px_u-guoUeE0Ul_ZXow_270.JPG: 480x640 (no detections), 294.8ms
Speed: 1.1ms preprocess, 294.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yK_l5WEp_HBwYedxo4S-lg_0.JPG: 480x640 (no detections), 301.3ms
Speed: 1.1ms preprocess, 301.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yK_l5WEp_HBwYedxo4S-lg_90.JPG: 480x640 (no detections), 300.5ms
Speed: 1.1ms preprocess, 300.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yK_l5WEp_HBwYedxo4S-lg_180.JPG: 480x640 (no detections), 298.3ms
Speed: 1.4ms preprocess, 298.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yK_l5WEp_HBwYedxo4S-lg_270.JPG: 480x640 (no detections), 305.3ms
Speed: 1.0ms preprocess, 305.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKc3bH-22R6Cb0btKGUDPQ_0.JPG: 480x640 (no detections), 299.9ms
Speed: 1.1ms preprocess, 299.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKc3bH-22R6Cb0btKGUDPQ_90.JPG: 480x640 (no detections), 301.6ms
Speed: 1.1ms preprocess, 301.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKc3bH-22R6Cb0btKGUDPQ_180.JPG: 480x640 (no detections), 302.1ms
Speed: 1.4ms preprocess, 302.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKc3bH-22R6Cb0btKGUDPQ_270.JPG: 480x640 (no detections), 307.6ms
Speed: 1.2ms preprocess, 307.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKca2I7TK8hRz2IsLFU41w_0.JPG: 480x640 (no detections), 301.0ms
Speed: 1.3ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKca2I7TK8hRz2IsLFU41w_90.JPG: 480x640 (no detections), 308.9ms
Speed: 1.1ms preprocess, 308.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKca2I7TK8hRz2IsLFU41w_180.JPG: 480x640 (no detections), 300.2ms
Speed: 1.3ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKca2I7TK8hRz2IsLFU41w_270.JPG: 480x640 (no detections), 308.6ms
Speed: 1.5ms preprocess, 308.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKeReTo2nmGQ7OP0a-tDqA_0.JPG: 480x640 (no detections), 302.9ms
Speed: 1.3ms preprocess, 302.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKeReTo2nmGQ7OP0a-tDqA_90.JPG: 480x640 (no detections), 300.5ms
Speed: 1.1ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKeReTo2nmGQ7OP0a-tDqA_180.JPG: 480x640 (no detections), 298.9ms
Speed: 1.0ms preprocess, 298.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKeReTo2nmGQ7OP0a-tDqA_270.JPG: 480x640 (no detections), 302.5ms
Speed: 1.2ms preprocess, 302.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKiCd4aqZnQVKymWI2nA7w_0.JPG: 480x640 (no detections), 302.5ms
Speed: 1.4ms preprocess, 302.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKiCd4aqZnQVKymWI2nA7w_90.JPG: 480x640 (no detections), 305.8ms
Speed: 1.3ms preprocess, 305.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKiCd4aqZnQVKymWI2nA7w_180.JPG: 480x640 (no detections), 297.0ms
Speed: 1.2ms preprocess, 297.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKiCd4aqZnQVKymWI2nA7w_270.JPG: 480x640 (no detections), 301.4ms
Speed: 1.4ms preprocess, 301.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKmibqOrAOJJu7BFJMP9jg_0.JPG: 480x640 (no detections), 307.4ms
Speed: 1.2ms preprocess, 307.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKmibqOrAOJJu7BFJMP9jg_90.JPG: 480x640 (no detections), 299.8ms
Speed: 1.1ms preprocess, 299.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKmibqOrAOJJu7BFJMP9jg_180.JPG: 480x640 (no detections), 297.3ms
Speed: 1.2ms preprocess, 297.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKmibqOrAOJJu7BFJMP9jg_270.JPG: 480x640 (no detections), 298.0ms
Speed: 1.2ms preprocess, 298.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKrib4rAm5FUh5EPTpNIsg_0.JPG: 480x640 (no detections), 302.9ms
Speed: 1.1ms preprocess, 302.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKrib4rAm5FUh5EPTpNIsg_90.JPG: 480x640 (no detections), 300.0ms
Speed: 1.2ms preprocess, 300.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKrib4rAm5FUh5EPTpNIsg_180.JPG: 480x640 (no detections), 298.5ms
Speed: 1.4ms preprocess, 298.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKrib4rAm5FUh5EPTpNIsg_270.JPG: 480x640 (no detections), 300.6ms
Speed: 1.1ms preprocess, 300.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKruLxvWPeq-GGygX9SVDA_0.JPG: 480x640 (no detections), 302.0ms
Speed: 1.1ms preprocess, 302.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKruLxvWPeq-GGygX9SVDA_90.JPG: 480x640 (no detections), 299.1ms
Speed: 1.7ms preprocess, 299.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKruLxvWPeq-GGygX9SVDA_180.JPG: 480x640 (no detections), 296.0ms
Speed: 1.4ms preprocess, 296.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKruLxvWPeq-GGygX9SVDA_270.JPG: 480x640 (no detections), 297.5ms
Speed: 1.2ms preprocess, 297.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKuExJIS1t53yfG9EKY1mg_0.JPG: 480x640 (no detections), 306.5ms
Speed: 1.0ms preprocess, 306.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKuExJIS1t53yfG9EKY1mg_90.JPG: 480x640 (no detections), 304.0ms
Speed: 1.4ms preprocess, 304.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKuExJIS1t53yfG9EKY1mg_180.JPG: 480x640 (no detections), 306.4ms
Speed: 1.3ms preprocess, 306.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKuExJIS1t53yfG9EKY1mg_270.JPG: 480x640 (no detections), 296.3ms
Speed: 1.2ms preprocess, 296.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKvWY5t-STSyja2CmoLvcQ_0.JPG: 480x640 (no detections), 301.2ms
Speed: 1.3ms preprocess, 301.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKvWY5t-STSyja2CmoLvcQ_90.JPG: 480x640 1 Waste, 294.6ms
Speed: 1.2ms preprocess, 294.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKvWY5t-STSyja2CmoLvcQ_180.JPG: 480x640 (no detections), 294.9ms
Speed: 1.1ms preprocess, 294.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKvWY5t-STSyja2CmoLvcQ_270.JPG: 480x640 (no detections), 298.8ms
Speed: 1.1ms preprocess, 298.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKyJhwf2uhTef-cBR2sElw_0.JPG: 480x640 (no detections), 302.5ms
Speed: 1.2ms preprocess, 302.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKyJhwf2uhTef-cBR2sElw_90.JPG: 480x640 (no detections), 308.3ms
Speed: 1.2ms preprocess, 308.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKyJhwf2uhTef-cBR2sElw_180.JPG: 480x640 (no detections), 296.3ms
Speed: 1.1ms preprocess, 296.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yKyJhwf2uhTef-cBR2sElw_270.JPG: 480x640 (no detections), 298.1ms
Speed: 1.5ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yL42MB2ht33agTfXuw7lAw_0.JPG: 480x640 (no detections), 297.8ms
Speed: 1.9ms preprocess, 297.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yL42MB2ht33agTfXuw7lAw_90.JPG: 480x640 (no detections), 297.2ms
Speed: 1.4ms preprocess, 297.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yL42MB2ht33agTfXuw7lAw_180.JPG: 480x640 (no detections), 300.1ms
Speed: 1.6ms preprocess, 300.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yL42MB2ht33agTfXuw7lAw_270.JPG: 480x640 (no detections), 305.5ms
Speed: 1.6ms preprocess, 305.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yL4525dhfpO6JBJZLFjLUQ_0.JPG: 480x640 (no detections), 302.2ms
Speed: 1.3ms preprocess, 302.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yL4525dhfpO6JBJZLFjLUQ_90.JPG: 480x640 (no detections), 307.3ms
Speed: 1.4ms preprocess, 307.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yL4525dhfpO6JBJZLFjLUQ_180.JPG: 480x640 (no detections), 295.4ms
Speed: 1.2ms preprocess, 295.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yL4525dhfpO6JBJZLFjLUQ_270.JPG: 480x640 (no detections), 297.2ms
Speed: 1.1ms preprocess, 297.2ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yL64Gr0hM-wI2zXkPq7FcQ_0.JPG: 480x640 (no detections), 303.5ms
Speed: 1.1ms preprocess, 303.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yL64Gr0hM-wI2zXkPq7FcQ_90.JPG: 480x640 (no detections), 301.8ms
Speed: 1.1ms preprocess, 301.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yL64Gr0hM-wI2zXkPq7FcQ_180.JPG: 480x640 (no detections), 303.4ms
Speed: 1.8ms preprocess, 303.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yL64Gr0hM-wI2zXkPq7FcQ_270.JPG: 480x640 (no detections), 299.8ms
Speed: 1.1ms preprocess, 299.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yL9s6NSjAw0dEtWBN5CPHw_0.JPG: 480x640 (no detections), 303.1ms
Speed: 1.5ms preprocess, 303.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yL9s6NSjAw0dEtWBN5CPHw_90.JPG: 480x640 (no detections), 299.6ms
Speed: 1.3ms preprocess, 299.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yL9s6NSjAw0dEtWBN5CPHw_180.JPG: 480x640 (no detections), 307.0ms
Speed: 1.3ms preprocess, 307.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yL9s6NSjAw0dEtWBN5CPHw_270.JPG: 480x640 (no detections), 306.3ms
Speed: 1.3ms preprocess, 306.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLA-6mffy5IoN1Wz2vWXPw_0.JPG: 480x640 (no detections), 306.1ms
Speed: 1.1ms preprocess, 306.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLA-6mffy5IoN1Wz2vWXPw_90.JPG: 480x640 (no detections), 299.9ms
Speed: 1.1ms preprocess, 299.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLA-6mffy5IoN1Wz2vWXPw_180.JPG: 480x640 (no detections), 298.1ms

Speed: 1.2ms preprocess, 298.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLA-6mffy5IoN1Wz2vWXPw_270.JPG: 480x640 (no detections), 300.9ms
Speed: 1.3ms preprocess, 300.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLAi3SYByf2ptgxSniUH_g_0.JPG: 480x640 (no detections), 302.5ms
Speed: 1.2ms preprocess, 302.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLAi3SYByf2ptgxSniUH_g_90.JPG: 480x640 (no detections), 302.3ms
Speed: 1.3ms preprocess, 302.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLAi3SYByf2ptgxSniUH_g_180.JPG: 480x640 (no detections), 299.1ms
Speed: 1.2ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLAi3SYByf2ptgxSniUH_g_270.JPG: 480x640 (no detections), 299.3ms
Speed: 1.0ms preprocess, 299.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLF_F_e-geEXHD1SlSeiTg_0.JPG: 480x640 (no detections), 301.0ms
Speed: 1.3ms preprocess, 301.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLF_F_e-geEXHD1SlSeiTg_90.JPG: 480x640 (no detections), 303.6ms
Speed: 1.1ms preprocess, 303.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLF_F_e-geEXHD1SlSeiTg_180.JPG: 480x640 (no detections), 299.0ms
Speed: 1.1ms preprocess, 299.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLF_F_e-geEXHD1SlSeiTg_270.JPG: 480x640 (no detections), 305.9ms
Speed: 1.3ms preprocess, 305.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLIqTj_8XY5fWaXMINHUlQ_0.JPG: 480x640 (no detections), 304.5ms
Speed: 1.1ms preprocess, 304.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLIqTj_8XY5fWaXMINHUlQ_90.JPG: 480x640 2 Wastes, 304.0ms
Speed: 1.5ms preprocess, 304.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLIqTj_8XY5fWaXMINHUlQ_180.JPG: 480x640 (no detections), 299.4ms
Speed: 1.1ms preprocess, 299.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLIqTj_8XY5fWaXMINHUlQ_270.JPG: 480x640 (no detections), 300.5ms
Speed: 1.3ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLJx6uc0D2dpIux4-FHacQ_0.JPG: 480x640 (no detections), 302.2ms
Speed: 1.1ms preprocess, 302.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLJx6uc0D2dpIux4-FHacQ_90.JPG: 480x640 (no detections), 303.6ms
Speed: 1.3ms preprocess, 303.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLJx6uc0D2dpIux4-FHacQ_180.JPG: 480x640 (no detections), 303.1ms
Speed: 1.5ms preprocess, 303.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLJx6uc0D2dpIux4-FHacQ_270.JPG: 480x640 (no detections), 301.2ms
Speed: 1.1ms preprocess, 301.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLKG3Uj05KdG7U_s-dbAWw_0.JPG: 480x640 (no detections), 307.0ms
Speed: 1.0ms preprocess, 307.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLKG3Uj05KdG7U_s-dbAWw_90.JPG: 480x640 (no detections), 298.4ms
Speed: 1.1ms preprocess, 298.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLKG3Uj05KdG7U_s-dbAWw_180.JPG: 480x640 (no detections), 300.3ms
Speed: 1.0ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLKG3Uj05KdG7U_s-dbAWw_270.JPG: 480x640 (no detections), 295.9ms
Speed: 2.0ms preprocess, 295.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLM_xVL2Z_zjSwd3veRJmA_0.JPG: 480x640 (no detections), 299.9ms
Speed: 1.2ms preprocess, 299.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLM_xVL2Z_zjSwd3veRJmA_90.JPG: 480x640 (no detections), 300.8ms
Speed: 1.1ms preprocess, 300.8ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLM_xVL2Z_zjSwd3veRJmA_180.JPG: 480x640 (no detections), 303.6ms
Speed: 1.8ms preprocess, 303.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLM_xVL2Z_zjSwd3veRJmA_270.JPG: 480x640 (no detections), 297.2ms
Speed: 1.2ms preprocess, 297.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLNfzIXj7Q8cNfI0uhP-WA_0.JPG: 480x640 (no detections), 302.4ms
Speed: 1.8ms preprocess, 302.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLNfzIXj7Q8cNfI0uhP-WA_90.JPG: 480x640 1 Waste, 299.7ms
Speed: 1.1ms preprocess, 299.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLNfzIXj7Q8cNfI0uhP-WA_180.JPG: 480x640 (no detections), 296.7ms
Speed: 1.1ms preprocess, 296.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLNfzIXj7Q8cNfI0uhP-WA_270.JPG: 480x640 (no detections), 313.6ms
Speed: 1.1ms preprocess, 313.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLO55WFrSE4uJLzknFD5zQ_0.JPG: 480x640 (no detections), 302.4ms
Speed: 1.1ms preprocess, 302.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLO55WFrSE4uJLzknFD5zQ_90.JPG: 480x640 (no detections), 302.4ms
Speed: 1.1ms preprocess, 302.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLO55WFrSE4uJLzknFD5zQ_180.JPG: 480x640 (no detections), 305.7ms
Speed: 1.1ms preprocess, 305.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLO55WFrSE4uJLzknFD5zQ_270.JPG: 480x640 (no detections), 298.9ms
Speed: 1.1ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLQZc_DWju_QxEbRBJg0qw_0.JPG: 480x640 (no detections), 299.6ms
Speed: 1.4ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLQZc_DWju_QxEbRBJg0qw_90.JPG: 480x640 (no detections), 295.2ms
Speed: 1.5ms preprocess, 295.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLQZc_DWju_QxEbRBJg0qw_180.JPG: 480x640 (no detections), 306.9ms
Speed: 1.2ms preprocess, 306.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLQZc_DWju_QxEbRBJg0qw_270.JPG: 480x640 (no detections), 315.0ms
Speed: 1.3ms preprocess, 315.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLQoYMeciEn-1FVXdaSoAA_0.JPG: 480x640 (no detections), 295.0ms
Speed: 1.0ms preprocess, 295.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLQoYMeciEn-1FVXdaSoAA_90.JPG: 480x640 (no detections), 293.1ms
Speed: 1.1ms preprocess, 293.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLQoYMeciEn-1FVXdaSoAA_180.JPG: 480x640 (no detections), 295.5ms
Speed: 1.3ms preprocess, 295.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLQoYMeciEn-1FVXdaSoAA_270.JPG: 480x640 (no detections), 311.0ms
Speed: 1.1ms preprocess, 311.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLV8vZI5eW-61yKN03odQQ_0.JPG: 480x640 (no detections), 311.7ms
Speed: 1.3ms preprocess, 311.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLV8vZI5eW-61yKN03odQQ_90.JPG: 480x640 (no detections), 322.7ms
Speed: 1.2ms preprocess, 322.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLV8vZI5eW-61yKN03odQQ_180.JPG: 480x640 (no detections), 309.7ms
Speed: 1.1ms preprocess, 309.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLV8vZI5eW-61yKN03odQQ_270.JPG: 480x640 (no detections), 297.4ms
Speed: 1.7ms preprocess, 297.4ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLYZrtzPaIwvk7tFfrDAjg_0.JPG: 480x640 (no detections), 303.0ms
Speed: 1.1ms preprocess, 303.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLYZrtzPaIwvk7tFfrDAjg_90.JPG: 480x640 (no detections), 318.4ms
Speed: 1.4ms preprocess, 318.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLYZrtzPaIwvk7tFfrDAjg_180.JPG: 480x640 (no detections), 320.6ms
Speed: 2.0ms preprocess, 320.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLYZrtzPaIwvk7tFfrDAjg_270.JPG: 480x640 (no detections), 292.2ms
Speed: 1.2ms preprocess, 292.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLYc116c3nyKdjTfU3Y0Aw_0.JPG: 480x640 (no detections), 311.4ms
Speed: 1.0ms preprocess, 311.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLYc116c3nyKdjTfU3Y0Aw_90.JPG: 480x640 (no detections), 309.5ms
Speed: 1.3ms preprocess, 309.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLYc116c3nyKdjTfU3Y0Aw_180.JPG: 480x640 (no detections), 308.6ms
Speed: 1.3ms preprocess, 308.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLYc116c3nyKdjTfU3Y0Aw_270.JPG: 480x640 (no detections), 302.7ms
Speed: 1.2ms preprocess, 302.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLZLP7JKgPGHjmbktU9W-g_0.JPG: 480x640 (no detections), 304.8ms
Speed: 1.2ms preprocess, 304.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLZLP7JKgPGHjmbktU9W-g_90.JPG: 480x640 (no detections), 306.2ms
Speed: 1.0ms preprocess, 306.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLZLP7JKgPGHjmbktU9W-g_180.JPG: 480x640 (no detections), 308.9ms
Speed: 1.1ms preprocess, 308.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLZLP7JKgPGHjmbktU9W-g_270.JPG: 480x640 (no detections), 310.5ms
Speed: 1.4ms preprocess, 310.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLZsQUjCR7m7kJ7xCwHaeA_0.JPG: 480x640 (no detections), 354.5ms
Speed: 1.5ms preprocess, 354.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLZsQUjCR7m7kJ7xCwHaeA_90.JPG: 480x640 (no detections), 388.9ms
Speed: 1.4ms preprocess, 388.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLZsQUjCR7m7kJ7xCwHaeA_180.JPG: 480x640 (no detections), 365.4ms
Speed: 1.5ms preprocess, 365.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLZsQUjCR7m7kJ7xCwHaeA_270.JPG: 480x640 (no detections), 335.9ms
Speed: 1.2ms preprocess, 335.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLcERfbq2jL-surPDWx2rw_0.JPG: 480x640 (no detections), 328.0ms
Speed: 1.1ms preprocess, 328.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLcERfbq2jL-surPDWx2rw_90.JPG: 480x640 (no detections), 313.6ms
Speed: 1.1ms preprocess, 313.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLcERfbq2jL-surPDWx2rw_180.JPG: 480x640 (no detections), 326.2ms
Speed: 1.1ms preprocess, 326.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLcERfbq2jL-surPDWx2rw_270.JPG: 480x640 (no detections), 387.6ms
Speed: 1.3ms preprocess, 387.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLibzvWwmn7WrEUxm9i0tQ_0.JPG: 480x640 (no detections), 275.9ms
Speed: 1.3ms preprocess, 275.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLibzvWwmn7WrEUxm9i0tQ_90.JPG: 480x640 (no detections), 265.6ms

Speed: 1.0ms preprocess, 265.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLibzvWwmn7WrEUxm9i0tQ_180.JPG: 480x640 (no detections), 265.3ms
Speed: 1.0ms preprocess, 265.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLibzvWwmn7WrEUxm9i0tQ_270.JPG: 480x640 (no detections), 275.4ms
Speed: 1.1ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLjahs_n1q5jHW6dyBS6Ew_0.JPG: 480x640 (no detections), 289.3ms
Speed: 1.2ms preprocess, 289.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLjahs_n1q5jHW6dyBS6Ew_90.JPG: 480x640 (no detections), 298.4ms
Speed: 1.1ms preprocess, 298.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLjahs_n1q5jHW6dyBS6Ew_180.JPG: 480x640 (no detections), 278.5ms
Speed: 1.1ms preprocess, 278.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLjahs_n1q5jHW6dyBS6Ew_270.JPG: 480x640 (no detections), 285.8ms
Speed: 1.1ms preprocess, 285.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLmGPBhFJxbqpIzGxRb8Zg_0.JPG: 480x640 (no detections), 278.3ms
Speed: 1.3ms preprocess, 278.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLmGPBhFJxbqpIzGxRb8Zg_90.JPG: 480x640 (no detections), 276.0ms
Speed: 1.1ms preprocess, 276.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLmGPBhFJxbqpIzGxRb8Zg_180.JPG: 480x640 (no detections), 284.2ms
Speed: 1.2ms preprocess, 284.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLmGPBhFJxbqpIzGxRb8Zg_270.JPG: 480x640 (no detections), 284.0ms
Speed: 1.2ms preprocess, 284.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLoUdNdnFk_ujmSeEH4XCQ_0.JPG: 480x640 (no detections), 290.1ms
Speed: 1.1ms preprocess, 290.1ms inference, 2.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLoUdNdnFk_ujmSeEH4XCQ_90.JPG: 480x640 (no detections), 311.2ms
Speed: 1.4ms preprocess, 311.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLoUdNdnFk_ujmSeEH4XCQ_180.JPG: 480x640 (no detections), 311.3ms
Speed: 1.1ms preprocess, 311.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLoUdNdnFk_ujmSeEH4XCQ_270.JPG: 480x640 (no detections), 368.8ms
Speed: 1.3ms preprocess, 368.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLqloy8AaBGlzhobSk3Q-Q_0.JPG: 480x640 (no detections), 286.1ms
Speed: 1.2ms preprocess, 286.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLqloy8AaBGlzhobSk3Q-Q_90.JPG: 480x640 (no detections), 280.7ms
Speed: 1.1ms preprocess, 280.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLqloy8AaBGlzhobSk3Q-Q_180.JPG: 480x640 (no detections), 268.9ms
Speed: 1.1ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLqloy8AaBGlzhobSk3Q-Q_270.JPG: 480x640 (no detections), 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLsprLan30KkECqkKsK3IQ_0.JPG: 480x640 (no detections), 265.2ms
Speed: 1.1ms preprocess, 265.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLsprLan30KkECqkKsK3IQ_90.JPG: 480x640 (no detections), 265.5ms
Speed: 1.1ms preprocess, 265.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLsprLan30KkECqkKsK3IQ_180.JPG: 480x640 (no detections), 267.0ms
Speed: 1.1ms preprocess, 267.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLsprLan30KkECqkKsK3IQ_270.JPG: 480x640 (no detections), 276.8ms
Speed: 1.0ms preprocess, 276.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLuEELAinYCXsv7HxAM5QA_0.JPG: 480x640 (no detections), 279.4ms
Speed: 1.2ms preprocess, 279.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLuEELAinYCXsv7HxAM5QA_90.JPG: 480x640 (no detections), 287.1ms
Speed: 1.4ms preprocess, 287.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLuEELAinYCXsv7HxAM5QA_180.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLuEELAinYCXsv7HxAM5QA_270.JPG: 480x640 1 Waste, 279.0ms
Speed: 1.0ms preprocess, 279.0ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLvXsD7CC6O67WjA9hp6iw_0.JPG: 480x640 (no detections), 311.8ms
Speed: 1.2ms preprocess, 311.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLvXsD7CC6O67WjA9hp6iw_90.JPG: 480x640 (no detections), 313.5ms
Speed: 1.2ms preprocess, 313.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLvXsD7CC6O67WjA9hp6iw_180.JPG: 480x640 (no detections), 293.9ms
Speed: 1.1ms preprocess, 293.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLvXsD7CC6O67WjA9hp6iw_270.JPG: 480x640 (no detections), 284.4ms
Speed: 1.0ms preprocess, 284.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLwolukxCT0UcumyvPKYNw_0.JPG: 480x640 (no detections), 290.7ms
Speed: 1.1ms preprocess, 290.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLwolukxCT0UcumyvPKYNw_90.JPG: 480x640 (no detections), 288.5ms
Speed: 1.2ms preprocess, 288.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLwolukxCT0UcumyvPKYNw_180.JPG: 480x640 (no detections), 304.9ms
Speed: 1.5ms preprocess, 304.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLwolukxCT0UcumyvPKYNw_270.JPG: 480x640 (no detections), 309.8ms
Speed: 1.1ms preprocess, 309.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLyOCnRLU3zuJckIuIip1A_0.JPG: 480x640 (no detections), 295.3ms
Speed: 1.1ms preprocess, 295.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLyOCnRLU3zuJckIuIip1A_90.JPG: 480x640 (no detections), 290.7ms
Speed: 1.7ms preprocess, 290.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLyOCnRLU3zuJckIuIip1A_180.JPG: 480x640 (no detections), 285.5ms
Speed: 1.1ms preprocess, 285.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLyOCnRLU3zuJckIuIip1A_270.JPG: 480x640 (no detections), 277.9ms
Speed: 1.0ms preprocess, 277.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLyi2BN41gaMxwRrFRajxQ_0.JPG: 480x640 1 Waste, 275.8ms
Speed: 1.0ms preprocess, 275.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLyi2BN41gaMxwRrFRajxQ_90.JPG: 480x640 (no detections), 288.7ms
Speed: 1.1ms preprocess, 288.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLyi2BN41gaMxwRrFRajxQ_180.JPG: 480x640 (no detections), 323.8ms
Speed: 1.7ms preprocess, 323.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yLyi2BN41gaMxwRrFRajxQ_270.JPG: 480x640 (no detections), 328.9ms
Speed: 1.3ms preprocess, 328.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yM23Aal9HhEJZpQQMl-kCg_0.JPG: 480x640 (no detections), 302.2ms
Speed: 1.3ms preprocess, 302.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yM23Aal9HhEJZpQQMl-kCg_90.JPG: 480x640 (no detections), 282.3ms
Speed: 1.1ms preprocess, 282.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yM23Aal9HhEJZpQQMl-kCg_180.JPG: 480x640 (no detections), 269.1ms
Speed: 1.1ms preprocess, 269.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yM23Aal9HhEJZpQQMl-kCg_270.JPG: 480x640 (no detections), 273.5ms
Speed: 1.0ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yM67fSDSULqFuaNReaLcjw_0.JPG: 480x640 (no detections), 268.9ms
Speed: 1.1ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yM67fSDSULqFuaNReaLcjw_90.JPG: 480x640 (no detections), 272.1ms
Speed: 1.2ms preprocess, 272.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yM67fSDSULqFuaNReaLcjw_180.JPG: 480x640 (no detections), 272.5ms
Speed: 1.1ms preprocess, 272.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yM67fSDSULqFuaNReaLcjw_270.JPG: 480x640 (no detections), 281.4ms
Speed: 1.1ms preprocess, 281.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yM7BPx8LPtzWFrjuQqXInQ_0.JPG: 480x640 (no detections), 300.7ms
Speed: 1.2ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yM7BPx8LPtzWFrjuQqXInQ_90.JPG: 480x640 (no detections), 272.0ms
Speed: 1.0ms preprocess, 272.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yM7BPx8LPtzWFrjuQqXInQ_180.JPG: 480x640 (no detections), 269.2ms
Speed: 1.0ms preprocess, 269.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yM7BPx8LPtzWFrjuQqXInQ_270.JPG: 480x640 (no detections), 269.9ms
Speed: 1.0ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yM7YCtv5vXLXgg0fDIRJ9A_0.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yM7YCtv5vXLXgg0fDIRJ9A_90.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yM7YCtv5vXLXgg0fDIRJ9A_180.JPG: 480x640 (no detections), 270.7ms
Speed: 1.0ms preprocess, 270.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yM7YCtv5vXLXgg0fDIRJ9A_270.JPG: 480x640 (no detections), 269.6ms
Speed: 1.1ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yM9I00pUOPmmrwc41dFIhQ_0.JPG: 480x640 (no detections), 273.6ms
Speed: 1.1ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yM9I00pUOPmmrwc41dFIhQ_90.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yM9I00pUOPmmrwc41dFIhQ_180.JPG: 480x640 (no detections), 278.4ms
Speed: 1.0ms preprocess, 278.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yM9I00pUOPmmrwc41dFIhQ_270.JPG: 480x640 (no detections), 278.7ms
Speed: 1.2ms preprocess, 278.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMCODIEdJwnS7GwAEgjZgg_0.JPG: 480x640 (no detections), 290.3ms
Speed: 1.2ms preprocess, 290.3ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMCODIEdJwnS7GwAEgjZgg_90.JPG: 480x640 (no detections), 280.7ms
Speed: 1.2ms preprocess, 280.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMCODIEdJwnS7GwAEgjZgg_180.JPG: 480x640 (no detections), 275.0ms
Speed: 1.0ms preprocess, 275.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMCODIEdJwnS7GwAEgjZgg_270.JPG: 480x640 (no detections), 273.4ms
Speed: 1.2ms preprocess, 273.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMDoRIpo2DxhRxrxI0xYcA_0.JPG: 480x640 (no detections), 287.3ms

Speed: 1.2ms preprocess, 287.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMDoRIpo2DxhRxrxI0xYcA_90.JPG: 480x640 (no detections), 289.1ms
Speed: 1.2ms preprocess, 289.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMDoRIpo2DxhRxrxI0xYcA_180.JPG: 480x640 (no detections), 272.4ms
Speed: 1.1ms preprocess, 272.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMDoRIpo2DxhRxrxI0xYcA_270.JPG: 480x640 (no detections), 279.5ms
Speed: 1.1ms preprocess, 279.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMFxVsJzM7JmJHnQWDyaGw_0.JPG: 480x640 1 Waste, 289.7ms
Speed: 1.1ms preprocess, 289.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMFxVsJzM7JmJHnQWDyaGw_90.JPG: 480x640 (no detections), 285.3ms
Speed: 1.2ms preprocess, 285.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMFxVsJzM7JmJHnQWDyaGw_180.JPG: 480x640 (no detections), 300.4ms
Speed: 1.2ms preprocess, 300.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMFxVsJzM7JmJHnQWDyaGw_270.JPG: 480x640 (no detections), 286.2ms
Speed: 1.2ms preprocess, 286.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMGvYFUjfzIZAC-Mnc7YdQ_0.JPG: 480x640 (no detections), 285.5ms
Speed: 1.1ms preprocess, 285.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMGvYFUjfzIZAC-Mnc7YdQ_90.JPG: 480x640 (no detections), 293.8ms
Speed: 1.1ms preprocess, 293.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMGvYFUjfzIZAC-Mnc7YdQ_180.JPG: 480x640 (no detections), 282.9ms
Speed: 1.0ms preprocess, 282.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMGvYFUjfzIZAC-Mnc7YdQ_270.JPG: 480x640 (no detections), 283.7ms
Speed: 1.1ms preprocess, 283.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMI9Y9BguSh5gpajVdDngg_0.JPG: 480x640 (no detections), 270.3ms
Speed: 1.1ms preprocess, 270.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMI9Y9BguSh5gpajVdDngg_90.JPG: 480x640 (no detections), 272.7ms
Speed: 1.0ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMI9Y9BguSh5gpajVdDngg_180.JPG: 480x640 (no detections), 329.2ms
Speed: 1.1ms preprocess, 329.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMI9Y9BguSh5gpajVdDngg_270.JPG: 480x640 (no detections), 305.3ms
Speed: 9.3ms preprocess, 305.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMKQPPeFYwggPNNcdU453Q_0.JPG: 480x640 (no detections), 297.6ms
Speed: 1.1ms preprocess, 297.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMKQPPeFYwggPNNcdU453Q_90.JPG: 480x640 (no detections), 345.0ms
Speed: 1.0ms preprocess, 345.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMKQPPeFYwggPNNcdU453Q_180.JPG: 480x640 (no detections), 288.0ms
Speed: 1.1ms preprocess, 288.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMKQPPeFYwggPNNcdU453Q_270.JPG: 480x640 (no detections), 349.6ms
Speed: 1.1ms preprocess, 349.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMK_v_xPOcUIKoLFKww8EQ_0.JPG: 480x640 (no detections), 287.6ms
Speed: 1.1ms preprocess, 287.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMK_v_xPOcUIKoLFKww8EQ_90.JPG: 480x640 (no detections), 288.5ms
Speed: 1.4ms preprocess, 288.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMK_v_xPOcUIKoLFKww8EQ_180.JPG: 480x640 (no detections), 282.1ms
Speed: 1.2ms preprocess, 282.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMK_v_xPOcUIKoLFKww8EQ_270.JPG: 480x640 (no detections), 289.6ms
Speed: 1.1ms preprocess, 289.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yML2wn3oxGB7ytnqoLgYKg_0.JPG: 480x640 (no detections), 298.1ms
Speed: 1.0ms preprocess, 298.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yML2wn3oxGB7ytnqoLgYKg_90.JPG: 480x640 (no detections), 292.6ms
Speed: 2.5ms preprocess, 292.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yML2wn3oxGB7ytnqoLgYKg_180.JPG: 480x640 (no detections), 276.1ms
Speed: 1.0ms preprocess, 276.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yML2wn3oxGB7ytnqoLgYKg_270.JPG: 480x640 (no detections), 274.2ms
Speed: 1.1ms preprocess, 274.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMQAKGmDbl7LXN1FSpGrPA_0.JPG: 480x640 (no detections), 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMQAKGmDbl7LXN1FSpGrPA_90.JPG: 480x640 (no detections), 275.8ms
Speed: 1.0ms preprocess, 275.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMQAKGmDbl7LXN1FSpGrPA_180.JPG: 480x640 (no detections), 276.7ms
Speed: 1.2ms preprocess, 276.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMQAKGmDbl7LXN1FSpGrPA_270.JPG: 480x640 (no detections), 271.0ms
Speed: 1.2ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMQOJlkOsAYKOp4CySRW4Q_0.JPG: 480x640 (no detections), 283.0ms
Speed: 1.0ms preprocess, 283.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMQOJlkOsAYKOp4CySRW4Q_90.JPG: 480x640 (no detections), 283.5ms
Speed: 1.2ms preprocess, 283.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMQOJlkOsAYKOp4CySRW4Q_180.JPG: 480x640 (no detections), 288.9ms
Speed: 1.1ms preprocess, 288.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMQOJlkOsAYKOp4CySRW4Q_270.JPG: 480x640 (no detections), 281.9ms
Speed: 1.0ms preprocess, 281.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMR3utdQQVIgCFCl0upf5A_0.JPG: 480x640 (no detections), 284.3ms
Speed: 1.1ms preprocess, 284.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMR3utdQQVIgCFCl0upf5A_90.JPG: 480x640 (no detections), 273.3ms
Speed: 1.0ms preprocess, 273.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMR3utdQQVIgCFCl0upf5A_180.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMR3utdQQVIgCFCl0upf5A_270.JPG: 480x640 (no detections), 279.1ms
Speed: 1.3ms preprocess, 279.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMSd9180HnbZRUzvzTD32Q_0.JPG: 480x640 (no detections), 276.4ms
Speed: 1.3ms preprocess, 276.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMSd9180HnbZRUzvzTD32Q_90.JPG: 480x640 1 Waste, 303.5ms
Speed: 1.5ms preprocess, 303.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMSd9180HnbZRUzvzTD32Q_180.JPG: 480x640 (no detections), 282.7ms
Speed: 1.1ms preprocess, 282.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMSd9180HnbZRUzvzTD32Q_270.JPG: 480x640 (no detections), 278.8ms
Speed: 1.5ms preprocess, 278.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMUa5f4Ptsxgf5lR4OEC3A_0.JPG: 480x640 (no detections), 272.3ms
Speed: 1.1ms preprocess, 272.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMUa5f4Ptsxgf5lR4OEC3A_90.JPG: 480x640 (no detections), 277.0ms
Speed: 1.2ms preprocess, 277.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMUa5f4Ptsxgf5lR4OEC3A_180.JPG: 480x640 (no detections), 276.9ms
Speed: 1.0ms preprocess, 276.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMUa5f4Ptsxgf5lR4OEC3A_270.JPG: 480x640 (no detections), 277.3ms
Speed: 1.0ms preprocess, 277.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMUcTc2C79n84cVQpzenvQ_0.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMUcTc2C79n84cVQpzenvQ_90.JPG: 480x640 (no detections), 274.7ms
Speed: 1.0ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMUcTc2C79n84cVQpzenvQ_180.JPG: 480x640 (no detections), 406.2ms
Speed: 1.1ms preprocess, 406.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMUcTc2C79n84cVQpzenvQ_270.JPG: 480x640 (no detections), 316.8ms
Speed: 1.2ms preprocess, 316.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMW_jHFNmJRtCNretDnklQ_0.JPG: 480x640 (no detections), 339.0ms
Speed: 1.3ms preprocess, 339.0ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMW_jHFNmJRtCNretDnklQ_90.JPG: 480x640 (no detections), 295.8ms
Speed: 1.3ms preprocess, 295.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMW_jHFNmJRtCNretDnklQ_180.JPG: 480x640 (no detections), 316.0ms
Speed: 1.2ms preprocess, 316.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMW_jHFNmJRtCNretDnklQ_270.JPG: 480x640 1 Waste, 293.0ms
Speed: 1.3ms preprocess, 293.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMbIFzkKPcP34S1H46DD_g_0.JPG: 480x640 (no detections), 294.2ms
Speed: 1.1ms preprocess, 294.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMbIFzkKPcP34S1H46DD_g_90.JPG: 480x640 (no detections), 280.9ms
Speed: 1.1ms preprocess, 280.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMbIFzkKPcP34S1H46DD_g_180.JPG: 480x640 (no detections), 268.1ms
Speed: 1.1ms preprocess, 268.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMbIFzkKPcP34S1H46DD_g_270.JPG: 480x640 (no detections), 292.7ms
Speed: 1.1ms preprocess, 292.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMcHpXZHqfZ0COIxE9Vy5w_0.JPG: 480x640 (no detections), 308.1ms
Speed: 1.5ms preprocess, 308.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMcHpXZHqfZ0COIxE9Vy5w_90.JPG: 480x640 (no detections), 275.1ms
Speed: 1.2ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMcHpXZHqfZ0COIxE9Vy5w_180.JPG: 480x640 (no detections), 285.5ms
Speed: 1.4ms preprocess, 285.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMcHpXZHqfZ0COIxE9Vy5w_270.JPG: 480x640 (no detections), 268.6ms
Speed: 1.2ms preprocess, 268.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMdcm6HaUBqLEptpk5I7OQ_0.JPG: 480x640 (no detections), 277.5ms
Speed: 1.0ms preprocess, 277.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMdcm6HaUBqLEptpk5I7OQ_90.JPG: 480x640 (no detections), 295.6ms
Speed: 1.1ms preprocess, 295.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMdcm6HaUBqLEptpk5I7OQ_180.JPG: 480x640 (no detections), 280.5ms
Speed: 1.2ms preprocess, 280.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMdcm6HaUBqLEptpk5I7OQ_270.JPG: 480x640 (no detections), 293.6ms

Speed: 1.1ms preprocess, 293.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMdj1ankbhqDzHSQlFIEPA_0.JPG: 480x640 (no detections), 285.1ms
Speed: 1.2ms preprocess, 285.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMdj1ankbhqDzHSQlFIEPA_90.JPG: 480x640 (no detections), 292.1ms
Speed: 1.2ms preprocess, 292.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMdj1ankbhqDzHSQlFIEPA_180.JPG: 480x640 (no detections), 268.7ms
Speed: 1.2ms preprocess, 268.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMdj1ankbhqDzHSQlFIEPA_270.JPG: 480x640 (no detections), 303.3ms
Speed: 1.1ms preprocess, 303.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMg3FfRT2Lxbaei9R1_7xA_0.JPG: 480x640 (no detections), 288.3ms
Speed: 2.1ms preprocess, 288.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMg3FfRT2Lxbaei9R1_7xA_90.JPG: 480x640 (no detections), 266.9ms
Speed: 1.1ms preprocess, 266.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMg3FfRT2Lxbaei9R1_7xA_180.JPG: 480x640 (no detections), 266.6ms
Speed: 1.0ms preprocess, 266.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMg3FfRT2Lxbaei9R1_7xA_270.JPG: 480x640 (no detections), 284.1ms
Speed: 1.4ms preprocess, 284.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMjKPcwu76g-bZ-StCBoAw_0.JPG: 480x640 (no detections), 274.9ms
Speed: 1.8ms preprocess, 274.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMjKPcwu76g-bZ-StCBoAw_90.JPG: 480x640 (no detections), 272.5ms
Speed: 1.2ms preprocess, 272.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMjKPcwu76g-bZ-StCBoAw_180.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMjKPcwu76g-bZ-StCBoAw_270.JPG: 480x640 (no detections), 277.8ms
Speed: 1.0ms preprocess, 277.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMmQFOvX9zCwMseKZh9Rtw_0.JPG: 480x640 (no detections), 279.4ms
Speed: 1.4ms preprocess, 279.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMmQFOvX9zCwMseKZh9Rtw_90.JPG: 480x640 (no detections), 278.7ms
Speed: 1.1ms preprocess, 278.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMmQFOvX9zCwMseKZh9Rtw_180.JPG: 480x640 (no detections), 270.5ms
Speed: 1.0ms preprocess, 270.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMmQFOvX9zCwMseKZh9Rtw_270.JPG: 480x640 (no detections), 275.1ms
Speed: 1.0ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMmQjjOOvy_63JrBhA-JhA_0.JPG: 480x640 (no detections), 267.3ms
Speed: 1.1ms preprocess, 267.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMmQjjOOvy_63JrBhA-JhA_90.JPG: 480x640 (no detections), 271.8ms
Speed: 1.0ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMmQjjOOvy_63JrBhA-JhA_180.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMmQjjOOvy_63JrBhA-JhA_270.JPG: 480x640 (no detections), 268.2ms
Speed: 1.1ms preprocess, 268.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMqCP5KtnsriHp-tfIuaJg_0.JPG: 480x640 (no detections), 268.9ms
Speed: 1.0ms preprocess, 268.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMqCP5KtnsriHp-tfIuaJg_90.JPG: 480x640 (no detections), 267.8ms
Speed: 1.0ms preprocess, 267.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMqCP5KtnsriHp-tfIuaJg_180.JPG: 480x640 (no detections), 270.2ms
Speed: 1.0ms preprocess, 270.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMqCP5KtnsriHp-tfIuaJg_270.JPG: 480x640 (no detections), 277.8ms
Speed: 1.0ms preprocess, 277.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMw9iZXSk3K7RJ7Ex2hjQQ_0.JPG: 480x640 (no detections), 281.8ms
Speed: 1.1ms preprocess, 281.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMw9iZXSk3K7RJ7Ex2hjQQ_90.JPG: 480x640 (no detections), 272.4ms
Speed: 1.1ms preprocess, 272.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMw9iZXSk3K7RJ7Ex2hjQQ_180.JPG: 480x640 (no detections), 280.8ms
Speed: 1.0ms preprocess, 280.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMw9iZXSk3K7RJ7Ex2hjQQ_270.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMwaG4ajgjOfGLEDeZxUZA_0.JPG: 480x640 (no detections), 274.0ms
Speed: 1.1ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMwaG4ajgjOfGLEDeZxUZA_90.JPG: 480x640 (no detections), 275.2ms
Speed: 1.0ms preprocess, 275.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMwaG4ajgjOfGLEDeZxUZA_180.JPG: 480x640 (no detections), 275.1ms
Speed: 1.0ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMwaG4ajgjOfGLEDeZxUZA_270.JPG: 480x640 (no detections), 284.6ms
Speed: 1.0ms preprocess, 284.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMxaJ0kQDZ9osOdqkt3D7Q_0.JPG: 480x640 (no detections), 281.7ms
Speed: 1.0ms preprocess, 281.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMxaJ0kQDZ9osOdqkt3D7Q_90.JPG: 480x640 (no detections), 275.1ms
Speed: 1.2ms preprocess, 275.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMxaJ0kQDZ9osOdqkt3D7Q_180.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yMxaJ0kQDZ9osOdqkt3D7Q_270.JPG: 480x640 (no detections), 287.2ms
Speed: 1.1ms preprocess, 287.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yN1OVHATv3w5e_42b_KwvQ_0.JPG: 480x640 (no detections), 272.6ms
Speed: 1.0ms preprocess, 272.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yN1OVHATv3w5e_42b_KwvQ_90.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yN1OVHATv3w5e_42b_KwvQ_180.JPG: 480x640 (no detections), 276.6ms
Speed: 1.1ms preprocess, 276.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yN1OVHATv3w5e_42b_KwvQ_270.JPG: 480x640 (no detections), 268.3ms
Speed: 1.1ms preprocess, 268.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yN1evoE3D0-BJVd6Ty9qtA_0.JPG: 480x640 (no detections), 276.6ms
Speed: 1.2ms preprocess, 276.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yN1evoE3D0-BJVd6Ty9qtA_90.JPG: 480x640 (no detections), 273.6ms
Speed: 1.2ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yN1evoE3D0-BJVd6Ty9qtA_180.JPG: 480x640 (no detections), 266.7ms
Speed: 1.1ms preprocess, 266.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yN1evoE3D0-BJVd6Ty9qtA_270.JPG: 480x640 (no detections), 266.4ms
Speed: 1.1ms preprocess, 266.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yN1gKFIYKis8yDZdy_lJlA_0.JPG: 480x640 1 Waste, 270.7ms
Speed: 1.0ms preprocess, 270.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yN1gKFIYKis8yDZdy_lJlA_90.JPG: 480x640 (no detections), 269.7ms
Speed: 1.0ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yN1gKFIYKis8yDZdy_lJlA_180.JPG: 480x640 (no detections), 277.4ms
Speed: 1.1ms preprocess, 277.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yN1gKFIYKis8yDZdy_lJlA_270.JPG: 480x640 1 Waste, 275.5ms
Speed: 1.1ms preprocess, 275.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yN4RPtPgGEI_im6i75uHlw_0.JPG: 480x640 (no detections), 275.8ms
Speed: 1.0ms preprocess, 275.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yN4RPtPgGEI_im6i75uHlw_90.JPG: 480x640 (no detections), 274.9ms
Speed: 1.1ms preprocess, 274.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yN4RPtPgGEI_im6i75uHlw_180.JPG: 480x640 (no detections), 269.9ms
Speed: 1.0ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yN4RPtPgGEI_im6i75uHlw_270.JPG: 480x640 (no detections), 280.9ms
Speed: 0.9ms preprocess, 280.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yN9hYYmTKKIzfBprbA0cLA_0.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yN9hYYmTKKIzfBprbA0cLA_90.JPG: 480x640 (no detections), 276.7ms
Speed: 1.1ms preprocess, 276.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yN9hYYmTKKIzfBprbA0cLA_180.JPG: 480x640 (no detections), 276.4ms
Speed: 1.3ms preprocess, 276.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yN9hYYmTKKIzfBprbA0cLA_270.JPG: 480x640 (no detections), 275.2ms
Speed: 1.1ms preprocess, 275.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNF689RRI1wgmZh3eg2eHw_0.JPG: 480x640 (no detections), 273.3ms
Speed: 1.2ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNF689RRI1wgmZh3eg2eHw_90.JPG: 480x640 1 Waste, 272.0ms
Speed: 1.1ms preprocess, 272.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNF689RRI1wgmZh3eg2eHw_180.JPG: 480x640 (no detections), 268.9ms
Speed: 1.6ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNF689RRI1wgmZh3eg2eHw_270.JPG: 480x640 (no detections), 274.0ms
Speed: 1.5ms preprocess, 274.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNJAlM3Eq7v9C6nXhbArUw_0.JPG: 480x640 (no detections), 272.4ms
Speed: 1.1ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNJAlM3Eq7v9C6nXhbArUw_90.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNJAlM3Eq7v9C6nXhbArUw_180.JPG: 480x640 (no detections), 270.4ms
Speed: 1.1ms preprocess, 270.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNJAlM3Eq7v9C6nXhbArUw_270.JPG: 480x640 (no detections), 277.4ms
Speed: 1.0ms preprocess, 277.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNMkF97m-Ojr9QWs80_XzA_0.JPG: 480x640 (no detections), 281.9ms
Speed: 1.3ms preprocess, 281.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNMkF97m-Ojr9QWs80_XzA_90.JPG: 480x640 (no detections), 273.9ms
Speed: 1.2ms preprocess, 273.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNMkF97m-Ojr9QWs80_XzA_180.JPG: 480x640 (no detections), 273.2ms

Speed: 1.0ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNMkF97m-Ojr9QWs80_XzA_270.JPG: 480x640 (no detections), 268.6ms
Speed: 1.0ms preprocess, 268.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNN7tnxCEP_eHiGZFa9IMw_0.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNN7tnxCEP_eHiGZFa9IMw_90.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNN7tnxCEP_eHiGZFa9IMw_180.JPG: 480x640 (no detections), 269.7ms
Speed: 1.3ms preprocess, 269.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNN7tnxCEP_eHiGZFa9IMw_270.JPG: 480x640 (no detections), 281.2ms
Speed: 1.5ms preprocess, 281.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNNeLaxlku95lW4J6dSZPg_0.JPG: 480x640 (no detections), 273.4ms
Speed: 1.1ms preprocess, 273.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNNeLaxlku95lW4J6dSZPg_90.JPG: 480x640 (no detections), 273.1ms
Speed: 1.1ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNNeLaxlku95lW4J6dSZPg_180.JPG: 480x640 (no detections), 287.3ms
Speed: 1.0ms preprocess, 287.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNNeLaxlku95lW4J6dSZPg_270.JPG: 480x640 (no detections), 280.7ms
Speed: 1.1ms preprocess, 280.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNRgJ-HdN0dWQZInwMBl-w_0.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNRgJ-HdN0dWQZInwMBl-w_90.JPG: 480x640 (no detections), 273.6ms
Speed: 1.2ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNRgJ-HdN0dWQZInwMBl-w_180.JPG: 480x640 (no detections), 287.5ms
Speed: 1.1ms preprocess, 287.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNRgJ-HdN0dWQZInwMBl-w_270.JPG: 480x640 (no detections), 281.0ms
Speed: 1.0ms preprocess, 281.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNS96aTS5qGLxoFknrRxbg_0.JPG: 480x640 (no detections), 268.9ms
Speed: 1.0ms preprocess, 268.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNS96aTS5qGLxoFknrRxbg_90.JPG: 480x640 (no detections), 275.5ms
Speed: 1.1ms preprocess, 275.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNS96aTS5qGLxoFknrRxbg_180.JPG: 480x640 (no detections), 272.4ms
Speed: 1.1ms preprocess, 272.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNS96aTS5qGLxoFknrRxbg_270.JPG: 480x640 (no detections), 278.6ms
Speed: 1.2ms preprocess, 278.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNSOdbbke4z8TnBOnYQ1hA_0.JPG: 480x640 (no detections), 278.0ms
Speed: 1.2ms preprocess, 278.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNSOdbbke4z8TnBOnYQ1hA_90.JPG: 480x640 (no detections), 277.6ms
Speed: 1.2ms preprocess, 277.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNSOdbbke4z8TnBOnYQ1hA_180.JPG: 480x640 2 Wastes, 273.4ms
Speed: 1.1ms preprocess, 273.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNSOdbbke4z8TnBOnYQ1hA_270.JPG: 480x640 (no detections), 275.4ms
Speed: 1.0ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNUbPylew2zM2IjgpGJf2g_0.JPG: 480x640 (no detections), 274.6ms
Speed: 1.1ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNUbPylew2zM2IjgpGJf2g_90.JPG: 480x640 (no detections), 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNUbPylew2zM2IjgpGJf2g_180.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNUbPylew2zM2IjgpGJf2g_270.JPG: 480x640 (no detections), 281.5ms
Speed: 1.7ms preprocess, 281.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNY6CbXJLVLksz4ePiQQ8Q_0.JPG: 480x640 (no detections), 277.7ms
Speed: 1.4ms preprocess, 277.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNY6CbXJLVLksz4ePiQQ8Q_90.JPG: 480x640 (no detections), 275.2ms
Speed: 1.0ms preprocess, 275.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNY6CbXJLVLksz4ePiQQ8Q_180.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNY6CbXJLVLksz4ePiQQ8Q_270.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNaEsg1pPFr6gguGREssrg_0.JPG: 480x640 (no detections), 272.7ms
Speed: 1.0ms preprocess, 272.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNaEsg1pPFr6gguGREssrg_90.JPG: 480x640 (no detections), 267.3ms
Speed: 1.0ms preprocess, 267.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNaEsg1pPFr6gguGREssrg_180.JPG: 480x640 (no detections), 285.0ms
Speed: 1.4ms preprocess, 285.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNaEsg1pPFr6gguGREssrg_270.JPG: 480x640 (no detections), 272.1ms
Speed: 1.1ms preprocess, 272.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNeAtJkX35IT9ATWKcGpXA_0.JPG: 480x640 (no detections), 267.1ms
Speed: 1.0ms preprocess, 267.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNeAtJkX35IT9ATWKcGpXA_90.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNeAtJkX35IT9ATWKcGpXA_180.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNeAtJkX35IT9ATWKcGpXA_270.JPG: 480x640 (no detections), 270.9ms
Speed: 1.1ms preprocess, 270.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNf0N2LX6bQpMEn7CzQE4g_0.JPG: 480x640 (no detections), 267.8ms
Speed: 1.0ms preprocess, 267.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNf0N2LX6bQpMEn7CzQE4g_90.JPG: 480x640 1 Waste, 272.4ms
Speed: 1.1ms preprocess, 272.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNf0N2LX6bQpMEn7CzQE4g_180.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNf0N2LX6bQpMEn7CzQE4g_270.JPG: 480x640 1 Waste, 276.0ms
Speed: 1.0ms preprocess, 276.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNheujxMtD-WEgv5vIJEAA_0.JPG: 480x640 (no detections), 277.9ms
Speed: 1.1ms preprocess, 277.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNheujxMtD-WEgv5vIJEAA_90.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNheujxMtD-WEgv5vIJEAA_180.JPG: 480x640 (no detections), 271.2ms
Speed: 1.0ms preprocess, 271.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNheujxMtD-WEgv5vIJEAA_270.JPG: 480x640 (no detections), 269.2ms
Speed: 1.1ms preprocess, 269.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNlUaQ4d6TDozxUT7RF_dA_0.JPG: 480x640 (no detections), 275.0ms
Speed: 1.3ms preprocess, 275.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNlUaQ4d6TDozxUT7RF_dA_90.JPG: 480x640 (no detections), 290.2ms
Speed: 1.1ms preprocess, 290.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNlUaQ4d6TDozxUT7RF_dA_180.JPG: 480x640 (no detections), 274.5ms
Speed: 1.0ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNlUaQ4d6TDozxUT7RF_dA_270.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNlzV1oCzOicG8zd-var3w_0.JPG: 480x640 (no detections), 274.6ms
Speed: 1.2ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNlzV1oCzOicG8zd-var3w_90.JPG: 480x640 (no detections), 274.7ms
Speed: 1.1ms preprocess, 274.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNlzV1oCzOicG8zd-var3w_180.JPG: 480x640 (no detections), 272.3ms
Speed: 1.0ms preprocess, 272.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNlzV1oCzOicG8zd-var3w_270.JPG: 480x640 (no detections), 272.5ms
Speed: 1.2ms preprocess, 272.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNmma8a2h6-i-w9yXinEiQ_0.JPG: 480x640 (no detections), 267.4ms
Speed: 1.1ms preprocess, 267.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNmma8a2h6-i-w9yXinEiQ_90.JPG: 480x640 (no detections), 272.7ms
Speed: 1.0ms preprocess, 272.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNmma8a2h6-i-w9yXinEiQ_180.JPG: 480x640 (no detections), 280.2ms
Speed: 1.0ms preprocess, 280.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNmma8a2h6-i-w9yXinEiQ_270.JPG: 480x640 (no detections), 272.5ms
Speed: 1.2ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNn1hrC0vWDpvxs73vRxCQ_0.JPG: 480x640 (no detections), 275.5ms
Speed: 1.1ms preprocess, 275.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNn1hrC0vWDpvxs73vRxCQ_90.JPG: 480x640 (no detections), 272.8ms
Speed: 1.0ms preprocess, 272.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNn1hrC0vWDpvxs73vRxCQ_180.JPG: 480x640 (no detections), 268.1ms
Speed: 1.1ms preprocess, 268.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNn1hrC0vWDpvxs73vRxCQ_270.JPG: 480x640 (no detections), 277.4ms
Speed: 1.0ms preprocess, 277.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNoEZlTMvVANlPd38Vhmkg_0.JPG: 480x640 (no detections), 270.5ms
Speed: 1.2ms preprocess, 270.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNoEZlTMvVANlPd38Vhmkg_90.JPG: 480x640 (no detections), 279.1ms
Speed: 1.0ms preprocess, 279.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNoEZlTMvVANlPd38Vhmkg_180.JPG: 480x640 (no detections), 276.5ms
Speed: 1.1ms preprocess, 276.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNoEZlTMvVANlPd38Vhmkg_270.JPG: 480x640 (no detections), 271.5ms
Speed: 1.0ms preprocess, 271.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNo_vXZZ8Di3Z5abFVaThw_0.JPG: 480x640 (no detections), 275.8ms
Speed: 1.4ms preprocess, 275.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNo_vXZZ8Di3Z5abFVaThw_90.JPG: 480x640 (no detections), 268.5ms

Speed: 1.1ms preprocess, 268.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNo_vXZZ8Di3Z5abFVaThw_180.JPG: 480x640 (no detections), 273.5ms
Speed: 1.0ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNo_vXZZ8Di3Z5abFVaThw_270.JPG: 480x640 (no detections), 267.7ms
Speed: 1.1ms preprocess, 267.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNoezzFLIIrQe9HRbKUaQg_0.JPG: 480x640 (no detections), 273.9ms
Speed: 1.0ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNoezzFLIIrQe9HRbKUaQg_90.JPG: 480x640 (no detections), 279.4ms
Speed: 1.4ms preprocess, 279.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNoezzFLIIrQe9HRbKUaQg_180.JPG: 480x640 (no detections), 278.7ms
Speed: 1.2ms preprocess, 278.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNoezzFLIIrQe9HRbKUaQg_270.JPG: 480x640 1 Waste, 275.3ms
Speed: 1.0ms preprocess, 275.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNrRHT9YmEotYNYlArzC5g_0.JPG: 480x640 (no detections), 271.5ms
Speed: 1.0ms preprocess, 271.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNrRHT9YmEotYNYlArzC5g_90.JPG: 480x640 (no detections), 278.5ms
Speed: 1.0ms preprocess, 278.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNrRHT9YmEotYNYlArzC5g_180.JPG: 480x640 1 Waste, 275.8ms
Speed: 1.0ms preprocess, 275.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNrRHT9YmEotYNYlArzC5g_270.JPG: 480x640 (no detections), 273.7ms
Speed: 1.0ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNtWgQvGzpRu_a8bVDfKzg_0.JPG: 480x640 (no detections), 277.4ms
Speed: 1.2ms preprocess, 277.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNtWgQvGzpRu_a8bVDfKzg_90.JPG: 480x640 (no detections), 265.8ms
Speed: 1.1ms preprocess, 265.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNtWgQvGzpRu_a8bVDfKzg_180.JPG: 480x640 (no detections), 273.6ms
Speed: 1.1ms preprocess, 273.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNtWgQvGzpRu_a8bVDfKzg_270.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNwgJdvLupeytr9f8vG5Iw_0.JPG: 480x640 (no detections), 274.8ms
Speed: 1.2ms preprocess, 274.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNwgJdvLupeytr9f8vG5Iw_90.JPG: 480x640 (no detections), 266.3ms
Speed: 1.1ms preprocess, 266.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNwgJdvLupeytr9f8vG5Iw_180.JPG: 480x640 (no detections), 269.4ms
Speed: 1.1ms preprocess, 269.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNwgJdvLupeytr9f8vG5Iw_270.JPG: 480x640 (no detections), 268.1ms
Speed: 1.0ms preprocess, 268.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNyjPETZNwOvcmc1YmkxNw_0.JPG: 480x640 (no detections), 268.7ms
Speed: 1.1ms preprocess, 268.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNyjPETZNwOvcmc1YmkxNw_90.JPG: 480x640 (no detections), 269.4ms
Speed: 1.1ms preprocess, 269.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNyjPETZNwOvcmc1YmkxNw_180.JPG: 480x640 (no detections), 271.0ms
Speed: 1.0ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yNyjPETZNwOvcmc1YmkxNw_270.JPG: 480x640 (no detections), 272.2ms
Speed: 0.9ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yO5mIDOvVO-A5b4uXDUVrw_0.JPG: 480x640 (no detections), 275.9ms
Speed: 1.1ms preprocess, 275.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yO5mIDOvVO-A5b4uXDUVrw_90.JPG: 480x640 (no detections), 275.8ms
Speed: 1.0ms preprocess, 275.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yO5mIDOvVO-A5b4uXDUVrw_180.JPG: 480x640 (no detections), 274.5ms
Speed: 1.0ms preprocess, 274.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yO5mIDOvVO-A5b4uXDUVrw_270.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yO7S7P3DK1L3Uv2d4hX_DQ_0.JPG: 480x640 (no detections), 269.1ms
Speed: 1.1ms preprocess, 269.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yO7S7P3DK1L3Uv2d4hX_DQ_90.JPG: 480x640 (no detections), 269.4ms
Speed: 1.0ms preprocess, 269.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yO7S7P3DK1L3Uv2d4hX_DQ_180.JPG: 480x640 (no detections), 275.9ms
Speed: 1.0ms preprocess, 275.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yO7S7P3DK1L3Uv2d4hX_DQ_270.JPG: 480x640 (no detections), 278.2ms
Speed: 1.0ms preprocess, 278.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yO84i-N1BeouHooolBxgbw_0.JPG: 480x640 1 Waste, 272.4ms
Speed: 1.1ms preprocess, 272.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yO84i-N1BeouHooolBxgbw_90.JPG: 480x640 (no detections), 266.4ms
Speed: 0.9ms preprocess, 266.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yO84i-N1BeouHooolBxgbw_180.JPG: 480x640 (no detections), 268.1ms
Speed: 1.0ms preprocess, 268.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yO84i-N1BeouHooolBxgbw_270.JPG: 480x640 (no detections), 266.4ms
Speed: 1.1ms preprocess, 266.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yODNjbtpDSqxM6KId59C1Q_0.JPG: 480x640 (no detections), 271.0ms
Speed: 1.0ms preprocess, 271.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yODNjbtpDSqxM6KId59C1Q_90.JPG: 480x640 (no detections), 266.7ms
Speed: 1.0ms preprocess, 266.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yODNjbtpDSqxM6KId59C1Q_180.JPG: 480x640 (no detections), 279.2ms
Speed: 1.1ms preprocess, 279.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yODNjbtpDSqxM6KId59C1Q_270.JPG: 480x640 (no detections), 278.8ms
Speed: 1.1ms preprocess, 278.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yODS-RTM0ujnVOFW5mpvBA_0.JPG: 480x640 (no detections), 268.7ms
Speed: 1.1ms preprocess, 268.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yODS-RTM0ujnVOFW5mpvBA_90.JPG: 480x640 (no detections), 280.4ms
Speed: 1.1ms preprocess, 280.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yODS-RTM0ujnVOFW5mpvBA_180.JPG: 480x640 (no detections), 278.9ms
Speed: 1.1ms preprocess, 278.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yODS-RTM0ujnVOFW5mpvBA_270.JPG: 480x640 (no detections), 264.3ms
Speed: 1.0ms preprocess, 264.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOEsymzlZjO-7n5LrMi1fA_0.JPG: 480x640 (no detections), 270.5ms
Speed: 1.1ms preprocess, 270.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOEsymzlZjO-7n5LrMi1fA_90.JPG: 480x640 (no detections), 266.6ms
Speed: 1.1ms preprocess, 266.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOEsymzlZjO-7n5LrMi1fA_180.JPG: 480x640 (no detections), 267.8ms
Speed: 1.0ms preprocess, 267.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOEsymzlZjO-7n5LrMi1fA_270.JPG: 480x640 (no detections), 269.2ms
Speed: 1.1ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOEvqdrMY5NE7uPeoW2PaA_0.JPG: 480x640 (no detections), 272.5ms
Speed: 1.0ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOEvqdrMY5NE7uPeoW2PaA_90.JPG: 480x640 (no detections), 267.2ms
Speed: 1.1ms preprocess, 267.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOEvqdrMY5NE7uPeoW2PaA_180.JPG: 480x640 (no detections), 269.5ms
Speed: 1.0ms preprocess, 269.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOEvqdrMY5NE7uPeoW2PaA_270.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOF1U8-c5wRuDbNzGXii6A_0.JPG: 480x640 (no detections), 270.9ms
Speed: 1.0ms preprocess, 270.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOF1U8-c5wRuDbNzGXii6A_90.JPG: 480x640 (no detections), 283.2ms
Speed: 1.0ms preprocess, 283.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOF1U8-c5wRuDbNzGXii6A_180.JPG: 480x640 (no detections), 273.6ms
Speed: 1.1ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOF1U8-c5wRuDbNzGXii6A_270.JPG: 480x640 (no detections), 272.3ms
Speed: 1.1ms preprocess, 272.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOHXUSeO8k_1L-1cN8TxNw_0.JPG: 480x640 (no detections), 273.6ms
Speed: 1.0ms preprocess, 273.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOHXUSeO8k_1L-1cN8TxNw_90.JPG: 480x640 (no detections), 270.9ms
Speed: 1.0ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOHXUSeO8k_1L-1cN8TxNw_180.JPG: 480x640 (no detections), 274.4ms
Speed: 1.2ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOHXUSeO8k_1L-1cN8TxNw_270.JPG: 480x640 1 Waste, 277.2ms
Speed: 1.1ms preprocess, 277.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOIlHiRE8BhevIOATF12tA_0.JPG: 480x640 (no detections), 276.1ms
Speed: 1.2ms preprocess, 276.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOIlHiRE8BhevIOATF12tA_90.JPG: 480x640 (no detections), 275.0ms
Speed: 1.2ms preprocess, 275.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOIlHiRE8BhevIOATF12tA_180.JPG: 480x640 (no detections), 269.1ms
Speed: 1.1ms preprocess, 269.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOIlHiRE8BhevIOATF12tA_270.JPG: 480x640 (no detections), 284.5ms
Speed: 1.1ms preprocess, 284.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOJGm5qr6TnETETf9r3mgQ_0.JPG: 480x640 (no detections), 283.2ms
Speed: 1.2ms preprocess, 283.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOJGm5qr6TnETETf9r3mgQ_90.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOJGm5qr6TnETETf9r3mgQ_180.JPG: 480x640 1 Waste, 274.5ms
Speed: 1.1ms preprocess, 274.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOJGm5qr6TnETETf9r3mgQ_270.JPG: 480x640 (no detections), 278.3ms
Speed: 1.1ms preprocess, 278.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOLPw6E0aEidlUnMwaBg2g_0.JPG: 480x640 (no detections), 276.9ms

Speed: 1.0ms preprocess, 276.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOLPw6E0aEidlUnMwaBg2g_90.JPG: 480x640 (no detections), 278.3ms
Speed: 1.1ms preprocess, 278.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOLPw6E0aEidlUnMwaBg2g_180.JPG: 480x640 (no detections), 272.6ms
Speed: 1.0ms preprocess, 272.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOLPw6E0aEidlUnMwaBg2g_270.JPG: 480x640 (no detections), 273.9ms
Speed: 1.1ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOM96-7Go6knDDqfauTStg_0.JPG: 480x640 (no detections), 278.6ms
Speed: 1.0ms preprocess, 278.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOM96-7Go6knDDqfauTStg_90.JPG: 480x640 (no detections), 269.6ms
Speed: 1.1ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOM96-7Go6knDDqfauTStg_180.JPG: 480x640 (no detections), 266.6ms
Speed: 1.0ms preprocess, 266.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOM96-7Go6knDDqfauTStg_270.JPG: 480x640 (no detections), 269.2ms
Speed: 1.0ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOPg5oMkM1WCf-k7K0zOlg_0.JPG: 480x640 (no detections), 267.9ms
Speed: 1.1ms preprocess, 267.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOPg5oMkM1WCf-k7K0zOlg_90.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOPg5oMkM1WCf-k7K0zOlg_180.JPG: 480x640 (no detections), 265.9ms
Speed: 1.1ms preprocess, 265.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOPg5oMkM1WCf-k7K0zOlg_270.JPG: 480x640 (no detections), 268.7ms
Speed: 1.0ms preprocess, 268.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOSLPz_cYMyIu4J-4Ysolw_0.JPG: 480x640 (no detections), 277.2ms
Speed: 1.2ms preprocess, 277.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOSLPz_cYMyIu4J-4Ysolw_90.JPG: 480x640 (no detections), 279.7ms
Speed: 1.3ms preprocess, 279.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOSLPz_cYMyIu4J-4Ysolw_180.JPG: 480x640 (no detections), 278.7ms
Speed: 1.1ms preprocess, 278.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOSLPz_cYMyIu4J-4Ysolw_270.JPG: 480x640 (no detections), 267.6ms
Speed: 1.1ms preprocess, 267.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOTYK14TPmFHAkga781kBQ_0.JPG: 480x640 (no detections), 272.3ms
Speed: 1.1ms preprocess, 272.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOTYK14TPmFHAkga781kBQ_90.JPG: 480x640 (no detections), 266.0ms
Speed: 1.1ms preprocess, 266.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOTYK14TPmFHAkga781kBQ_180.JPG: 480x640 (no detections), 267.6ms
Speed: 1.1ms preprocess, 267.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOTYK14TPmFHAkga781kBQ_270.JPG: 480x640 (no detections), 269.1ms
Speed: 1.1ms preprocess, 269.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOU0nLIoTEqHvfujhSZc5g_0.JPG: 480x640 (no detections), 270.1ms
Speed: 1.0ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOU0nLIoTEqHvfujhSZc5g_90.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOU0nLIoTEqHvfujhSZc5g_180.JPG: 480x640 (no detections), 268.1ms
Speed: 1.1ms preprocess, 268.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOU0nLIoTEqHvfujhSZc5g_270.JPG: 480x640 1 Waste, 265.0ms
Speed: 1.1ms preprocess, 265.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOaFswm7JWzr_Pbs23QttQ_0.JPG: 480x640 (no detections), 273.2ms
Speed: 1.0ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOaFswm7JWzr_Pbs23QttQ_90.JPG: 480x640 (no detections), 268.7ms
Speed: 1.0ms preprocess, 268.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOaFswm7JWzr_Pbs23QttQ_180.JPG: 480x640 (no detections), 270.4ms
Speed: 1.0ms preprocess, 270.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOaFswm7JWzr_Pbs23QttQ_270.JPG: 480x640 (no detections), 273.9ms
Speed: 1.3ms preprocess, 273.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOdmKI7ZQDExQvyVK9bybw_0.JPG: 480x640 (no detections), 274.7ms
Speed: 1.1ms preprocess, 274.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOdmKI7ZQDExQvyVK9bybw_90.JPG: 480x640 (no detections), 270.0ms
Speed: 1.0ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOdmKI7ZQDExQvyVK9bybw_180.JPG: 480x640 (no detections), 265.7ms
Speed: 1.0ms preprocess, 265.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOdmKI7ZQDExQvyVK9bybw_270.JPG: 480x640 (no detections), 266.8ms
Speed: 1.1ms preprocess, 266.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOg2jjFwmp1EhnHnPVjY1g_0.JPG: 480x640 (no detections), 275.0ms
Speed: 1.0ms preprocess, 275.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOg2jjFwmp1EhnHnPVjY1g_90.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOg2jjFwmp1EhnHnPVjY1g_180.JPG: 480x640 (no detections), 275.0ms
Speed: 1.1ms preprocess, 275.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOg2jjFwmp1EhnHnPVjY1g_270.JPG: 480x640 (no detections), 278.9ms
Speed: 1.2ms preprocess, 278.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOg826nQLTK8EorYfl6qwg_0.JPG: 480x640 (no detections), 280.9ms
Speed: 1.2ms preprocess, 280.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOg826nQLTK8EorYfl6qwg_90.JPG: 480x640 (no detections), 277.6ms
Speed: 1.1ms preprocess, 277.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOg826nQLTK8EorYfl6qwg_180.JPG: 480x640 (no detections), 278.7ms
Speed: 1.1ms preprocess, 278.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOg826nQLTK8EorYfl6qwg_270.JPG: 480x640 (no detections), 282.8ms
Speed: 1.0ms preprocess, 282.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOgz7jvNSJEB4iFt1TF71g_0.JPG: 480x640 (no detections), 274.1ms
Speed: 1.0ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOgz7jvNSJEB4iFt1TF71g_90.JPG: 480x640 (no detections), 278.0ms
Speed: 1.1ms preprocess, 278.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOgz7jvNSJEB4iFt1TF71g_180.JPG: 480x640 (no detections), 272.4ms
Speed: 1.0ms preprocess, 272.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOgz7jvNSJEB4iFt1TF71g_270.JPG: 480x640 (no detections), 286.0ms
Speed: 1.1ms preprocess, 286.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOlEVKinqkMisrJ942ggUg_0.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOlEVKinqkMisrJ942ggUg_90.JPG: 480x640 (no detections), 268.5ms
Speed: 1.1ms preprocess, 268.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOlEVKinqkMisrJ942ggUg_180.JPG: 480x640 (no detections), 266.7ms
Speed: 1.1ms preprocess, 266.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOlEVKinqkMisrJ942ggUg_270.JPG: 480x640 (no detections), 268.9ms
Speed: 1.0ms preprocess, 268.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOnNt_NkgM__AC_lLUzRgA_0.JPG: 480x640 (no detections), 267.0ms
Speed: 1.1ms preprocess, 267.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOnNt_NkgM__AC_lLUzRgA_90.JPG: 480x640 (no detections), 268.6ms
Speed: 1.2ms preprocess, 268.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOnNt_NkgM__AC_lLUzRgA_180.JPG: 480x640 (no detections), 269.3ms
Speed: 1.0ms preprocess, 269.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOnNt_NkgM__AC_lLUzRgA_270.JPG: 480x640 (no detections), 261.8ms
Speed: 1.1ms preprocess, 261.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOpIRI2YOt0SI9S8SuDlJg_0.JPG: 480x640 2 Wastes, 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOpIRI2YOt0SI9S8SuDlJg_90.JPG: 480x640 (no detections), 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOpIRI2YOt0SI9S8SuDlJg_180.JPG: 480x640 (no detections), 272.6ms
Speed: 1.2ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOpIRI2YOt0SI9S8SuDlJg_270.JPG: 480x640 (no detections), 264.1ms
Speed: 1.1ms preprocess, 264.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOrNAgb52yKa57Kvax0auQ_0.JPG: 480x640 (no detections), 264.4ms
Speed: 1.0ms preprocess, 264.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOrNAgb52yKa57Kvax0auQ_90.JPG: 480x640 (no detections), 265.8ms
Speed: 1.1ms preprocess, 265.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOrNAgb52yKa57Kvax0auQ_180.JPG: 480x640 (no detections), 278.6ms
Speed: 1.2ms preprocess, 278.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOrNAgb52yKa57Kvax0auQ_270.JPG: 480x640 (no detections), 274.3ms
Speed: 1.0ms preprocess, 274.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOuiKSARKqOCScV5Ob7lMA_0.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOuiKSARKqOCScV5Ob7lMA_90.JPG: 480x640 (no detections), 265.0ms
Speed: 1.1ms preprocess, 265.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOuiKSARKqOCScV5Ob7lMA_180.JPG: 480x640 (no detections), 276.8ms
Speed: 1.0ms preprocess, 276.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOuiKSARKqOCScV5Ob7lMA_270.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOurB4MfWjSZtJ-OE9wkPw_0.JPG: 480x640 (no detections), 266.2ms
Speed: 1.0ms preprocess, 266.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOurB4MfWjSZtJ-OE9wkPw_90.JPG: 480x640 (no detections), 281.3ms
Speed: 1.1ms preprocess, 281.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOurB4MfWjSZtJ-OE9wkPw_180.JPG: 480x640 (no detections), 273.1ms
Speed: 1.0ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOurB4MfWjSZtJ-OE9wkPw_270.JPG: 480x640 (no detections), 267.2ms

Speed: 1.0ms preprocess, 267.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOxeCG2egF1yZUb1NBh4dA_0.JPG: 480x640 (no detections), 272.4ms
Speed: 1.2ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOxeCG2egF1yZUb1NBh4dA_90.JPG: 480x640 (no detections), 275.7ms
Speed: 1.1ms preprocess, 275.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOxeCG2egF1yZUb1NBh4dA_180.JPG: 480x640 (no detections), 268.5ms
Speed: 1.0ms preprocess, 268.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOxeCG2egF1yZUb1NBh4dA_270.JPG: 480x640 (no detections), 266.8ms
Speed: 1.1ms preprocess, 266.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOyvQ-oAojFmJ9tkqEqLZA_0.JPG: 480x640 (no detections), 277.1ms
Speed: 1.0ms preprocess, 277.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOyvQ-oAojFmJ9tkqEqLZA_90.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOyvQ-oAojFmJ9tkqEqLZA_180.JPG: 480x640 (no detections), 267.8ms
Speed: 1.0ms preprocess, 267.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yOyvQ-oAojFmJ9tkqEqLZA_270.JPG: 480x640 (no detections), 265.0ms
Speed: 1.0ms preprocess, 265.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yP0EvcaZG3PSrYUyUe1ygQ_0.JPG: 480x640 (no detections), 267.7ms
Speed: 1.1ms preprocess, 267.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yP0EvcaZG3PSrYUyUe1ygQ_90.JPG: 480x640 (no detections), 266.3ms
Speed: 1.1ms preprocess, 266.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yP0EvcaZG3PSrYUyUe1ygQ_180.JPG: 480x640 (no detections), 270.9ms
Speed: 1.1ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yP0EvcaZG3PSrYUyUe1ygQ_270.JPG: 480x640 (no detections), 268.8ms
Speed: 1.1ms preprocess, 268.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yP70AKb3aCtUOuQf2Cjb9g_0.JPG: 480x640 (no detections), 266.2ms
Speed: 1.0ms preprocess, 266.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yP70AKb3aCtUOuQf2Cjb9g_90.JPG: 480x640 (no detections), 266.2ms
Speed: 1.1ms preprocess, 266.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yP70AKb3aCtUOuQf2Cjb9g_180.JPG: 480x640 (no detections), 273.6ms
Speed: 1.0ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yP70AKb3aCtUOuQf2Cjb9g_270.JPG: 480x640 (no detections), 272.2ms
Speed: 1.2ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yP72dEfTnmZbwCf59alolA_0.JPG: 480x640 (no detections), 267.7ms
Speed: 1.1ms preprocess, 267.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yP72dEfTnmZbwCf59alolA_90.JPG: 480x640 (no detections), 267.7ms
Speed: 1.1ms preprocess, 267.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yP72dEfTnmZbwCf59alolA_180.JPG: 480x640 (no detections), 269.1ms
Speed: 1.0ms preprocess, 269.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yP72dEfTnmZbwCf59alolA_270.JPG: 480x640 (no detections), 279.5ms
Speed: 1.0ms preprocess, 279.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yP7NsYg4uImp7305LjcjdA_0.JPG: 480x640 (no detections), 265.3ms
Speed: 1.0ms preprocess, 265.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yP7NsYg4uImp7305LjcjdA_90.JPG: 480x640 (no detections), 271.1ms
Speed: 1.0ms preprocess, 271.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yP7NsYg4uImp7305LjcjdA_180.JPG: 480x640 1 Waste, 267.5ms
Speed: 1.1ms preprocess, 267.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yP7NsYg4uImp7305LjcjdA_270.JPG: 480x640 (no detections), 264.6ms
Speed: 1.1ms preprocess, 264.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yP9GWFYl0vOsTEC9B6gceg_0.JPG: 480x640 1 Waste, 266.2ms
Speed: 1.1ms preprocess, 266.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yP9GWFYl0vOsTEC9B6gceg_90.JPG: 480x640 (no detections), 267.0ms
Speed: 1.1ms preprocess, 267.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yP9GWFYl0vOsTEC9B6gceg_180.JPG: 480x640 (no detections), 264.2ms
Speed: 1.1ms preprocess, 264.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yP9GWFYl0vOsTEC9B6gceg_270.JPG: 480x640 (no detections), 269.0ms
Speed: 1.0ms preprocess, 269.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPA45ztmXLsv5ZthozbKhg_0.JPG: 480x640 (no detections), 268.4ms
Speed: 1.0ms preprocess, 268.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPA45ztmXLsv5ZthozbKhg_90.JPG: 480x640 (no detections), 268.3ms
Speed: 1.1ms preprocess, 268.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPA45ztmXLsv5ZthozbKhg_180.JPG: 480x640 (no detections), 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPA45ztmXLsv5ZthozbKhg_270.JPG: 480x640 (no detections), 267.3ms
Speed: 1.0ms preprocess, 267.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPBUtX_UdCUbKuxUOO_AAw_0.JPG: 480x640 (no detections), 270.0ms
Speed: 1.2ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPBUtX_UdCUbKuxUOO_AAw_90.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPBUtX_UdCUbKuxUOO_AAw_180.JPG: 480x640 (no detections), 269.0ms
Speed: 1.0ms preprocess, 269.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPBUtX_UdCUbKuxUOO_AAw_270.JPG: 480x640 (no detections), 267.7ms
Speed: 1.0ms preprocess, 267.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPDLlPjwI2X527HbBzEGLQ_0.JPG: 480x640 (no detections), 267.6ms
Speed: 1.1ms preprocess, 267.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPDLlPjwI2X527HbBzEGLQ_90.JPG: 480x640 (no detections), 267.9ms
Speed: 1.1ms preprocess, 267.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPDLlPjwI2X527HbBzEGLQ_180.JPG: 480x640 (no detections), 264.9ms
Speed: 1.1ms preprocess, 264.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPDLlPjwI2X527HbBzEGLQ_270.JPG: 480x640 (no detections), 272.3ms
Speed: 1.1ms preprocess, 272.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPGfrzUNMfDxkFyVaoEmwg_0.JPG: 480x640 (no detections), 268.9ms
Speed: 1.0ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPGfrzUNMfDxkFyVaoEmwg_90.JPG: 480x640 (no detections), 266.6ms
Speed: 1.0ms preprocess, 266.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPGfrzUNMfDxkFyVaoEmwg_180.JPG: 480x640 (no detections), 265.6ms
Speed: 1.0ms preprocess, 265.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPGfrzUNMfDxkFyVaoEmwg_270.JPG: 480x640 (no detections), 267.8ms
Speed: 1.1ms preprocess, 267.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPGn4dGSg7QJt7XBLycH6w_0.JPG: 480x640 (no detections), 269.1ms
Speed: 1.1ms preprocess, 269.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPGn4dGSg7QJt7XBLycH6w_90.JPG: 480x640 (no detections), 267.6ms
Speed: 1.1ms preprocess, 267.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPGn4dGSg7QJt7XBLycH6w_180.JPG: 480x640 (no detections), 268.8ms
Speed: 1.0ms preprocess, 268.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPGn4dGSg7QJt7XBLycH6w_270.JPG: 480x640 (no detections), 267.8ms
Speed: 0.9ms preprocess, 267.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPJv7CA0rLdhSFiwp-eT2g_0.JPG: 480x640 (no detections), 270.5ms
Speed: 1.0ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPJv7CA0rLdhSFiwp-eT2g_90.JPG: 480x640 (no detections), 264.4ms
Speed: 1.1ms preprocess, 264.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPJv7CA0rLdhSFiwp-eT2g_180.JPG: 480x640 (no detections), 266.7ms
Speed: 1.1ms preprocess, 266.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPJv7CA0rLdhSFiwp-eT2g_270.JPG: 480x640 (no detections), 269.2ms
Speed: 1.1ms preprocess, 269.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPM2w4m2qn8wam5Z3suthA_0.JPG: 480x640 (no detections), 264.9ms
Speed: 1.0ms preprocess, 264.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPM2w4m2qn8wam5Z3suthA_90.JPG: 480x640 (no detections), 267.2ms
Speed: 1.1ms preprocess, 267.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPM2w4m2qn8wam5Z3suthA_180.JPG: 480x640 (no detections), 268.7ms
Speed: 1.0ms preprocess, 268.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPM2w4m2qn8wam5Z3suthA_270.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPORvIG6TF_9VyJdpbt1xQ_0.JPG: 480x640 (no detections), 268.0ms
Speed: 1.1ms preprocess, 268.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPORvIG6TF_9VyJdpbt1xQ_90.JPG: 480x640 (no detections), 274.7ms
Speed: 1.0ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPORvIG6TF_9VyJdpbt1xQ_180.JPG: 480x640 (no detections), 265.8ms
Speed: 1.0ms preprocess, 265.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPORvIG6TF_9VyJdpbt1xQ_270.JPG: 480x640 (no detections), 268.7ms
Speed: 1.1ms preprocess, 268.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPSm6Qj7XVH-z-Xf6FzcgQ_0.JPG: 480x640 (no detections), 265.8ms
Speed: 1.1ms preprocess, 265.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPSm6Qj7XVH-z-Xf6FzcgQ_90.JPG: 480x640 (no detections), 266.7ms
Speed: 1.1ms preprocess, 266.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPSm6Qj7XVH-z-Xf6FzcgQ_180.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPSm6Qj7XVH-z-Xf6FzcgQ_270.JPG: 480x640 (no detections), 278.8ms
Speed: 1.1ms preprocess, 278.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yP_nds1hKGoatjzCmX7wYw_0.JPG: 480x640 (no detections), 265.3ms
Speed: 1.1ms preprocess, 265.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yP_nds1hKGoatjzCmX7wYw_90.JPG: 480x640 (no detections), 266.6ms
Speed: 1.0ms preprocess, 266.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yP_nds1hKGoatjzCmX7wYw_180.JPG: 480x640 (no detections), 271.0ms

Speed: 1.0ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yP_nds1hKGoatjzCmX7wYw_270.JPG: 480x640 (no detections), 268.1ms
Speed: 1.2ms preprocess, 268.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPb5cugnjz0UzTVUOluYGQ_0.JPG: 480x640 (no detections), 267.8ms
Speed: 1.0ms preprocess, 267.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPb5cugnjz0UzTVUOluYGQ_90.JPG: 480x640 (no detections), 266.5ms
Speed: 1.1ms preprocess, 266.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPb5cugnjz0UzTVUOluYGQ_180.JPG: 480x640 (no detections), 268.4ms
Speed: 1.1ms preprocess, 268.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPb5cugnjz0UzTVUOluYGQ_270.JPG: 480x640 1 Waste, 268.6ms
Speed: 1.1ms preprocess, 268.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPf-igt6dKrEpPGJIrGXPw_0.JPG: 480x640 (no detections), 268.9ms
Speed: 1.1ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPf-igt6dKrEpPGJIrGXPw_90.JPG: 480x640 (no detections), 267.9ms
Speed: 1.0ms preprocess, 267.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPf-igt6dKrEpPGJIrGXPw_180.JPG: 480x640 (no detections), 273.9ms
Speed: 1.0ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPf-igt6dKrEpPGJIrGXPw_270.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPfIVB0tu_FosOF-zzgPGg_0.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPfIVB0tu_FosOF-zzgPGg_90.JPG: 480x640 (no detections), 267.7ms
Speed: 1.1ms preprocess, 267.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPfIVB0tu_FosOF-zzgPGg_180.JPG: 480x640 (no detections), 284.6ms
Speed: 1.1ms preprocess, 284.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPfIVB0tu_FosOF-zzgPGg_270.JPG: 480x640 (no detections), 276.0ms
Speed: 1.1ms preprocess, 276.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPfQZoTtnK0MSlK-UMjQlw_0.JPG: 480x640 (no detections), 269.6ms
Speed: 1.1ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPfQZoTtnK0MSlK-UMjQlw_90.JPG: 480x640 (no detections), 278.1ms
Speed: 1.1ms preprocess, 278.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPfQZoTtnK0MSlK-UMjQlw_180.JPG: 480x640 (no detections), 267.4ms
Speed: 1.0ms preprocess, 267.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPfQZoTtnK0MSlK-UMjQlw_270.JPG: 480x640 (no detections), 273.9ms
Speed: 1.1ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPi-RDUjsMH5TJGJnVtDew_0.JPG: 480x640 (no detections), 269.0ms
Speed: 1.1ms preprocess, 269.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPi-RDUjsMH5TJGJnVtDew_90.JPG: 480x640 (no detections), 268.0ms
Speed: 1.1ms preprocess, 268.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPi-RDUjsMH5TJGJnVtDew_180.JPG: 480x640 (no detections), 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPi-RDUjsMH5TJGJnVtDew_270.JPG: 480x640 (no detections), 278.8ms
Speed: 1.1ms preprocess, 278.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPilCOHMEy2LDc4kQoULhg_0.JPG: 480x640 (no detections), 279.4ms
Speed: 1.1ms preprocess, 279.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPilCOHMEy2LDc4kQoULhg_90.JPG: 480x640 (no detections), 272.5ms
Speed: 1.1ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPilCOHMEy2LDc4kQoULhg_180.JPG: 480x640 (no detections), 271.9ms
Speed: 1.2ms preprocess, 271.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPilCOHMEy2LDc4kQoULhg_270.JPG: 480x640 (no detections), 272.0ms
Speed: 1.0ms preprocess, 272.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPmx1UsnyZBGvWokq2svGg_0.JPG: 480x640 (no detections), 277.6ms
Speed: 1.0ms preprocess, 277.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPmx1UsnyZBGvWokq2svGg_90.JPG: 480x640 (no detections), 268.1ms
Speed: 1.0ms preprocess, 268.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPmx1UsnyZBGvWokq2svGg_180.JPG: 480x640 (no detections), 271.6ms
Speed: 1.3ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPmx1UsnyZBGvWokq2svGg_270.JPG: 480x640 (no detections), 274.6ms
Speed: 1.0ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPnQlpsa5YPpFdQuraOXNQ_0.JPG: 480x640 (no detections), 273.4ms
Speed: 1.1ms preprocess, 273.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPnQlpsa5YPpFdQuraOXNQ_90.JPG: 480x640 (no detections), 271.2ms
Speed: 1.0ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPnQlpsa5YPpFdQuraOXNQ_180.JPG: 480x640 (no detections), 268.6ms
Speed: 1.1ms preprocess, 268.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPnQlpsa5YPpFdQuraOXNQ_270.JPG: 480x640 (no detections), 268.8ms
Speed: 1.1ms preprocess, 268.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPo28qzfQb4dg5f9NIM5Ug_0.JPG: 480x640 (no detections), 269.2ms
Speed: 1.0ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPo28qzfQb4dg5f9NIM5Ug_90.JPG: 480x640 (no detections), 272.6ms
Speed: 1.0ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPo28qzfQb4dg5f9NIM5Ug_180.JPG: 480x640 (no detections), 278.1ms
Speed: 1.1ms preprocess, 278.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPo28qzfQb4dg5f9NIM5Ug_270.JPG: 480x640 (no detections), 273.5ms
Speed: 1.0ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPq8HlKTpeBEGpDVyIflgw_0.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPq8HlKTpeBEGpDVyIflgw_90.JPG: 480x640 (no detections), 268.3ms
Speed: 1.1ms preprocess, 268.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPq8HlKTpeBEGpDVyIflgw_180.JPG: 480x640 (no detections), 274.6ms
Speed: 1.0ms preprocess, 274.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPq8HlKTpeBEGpDVyIflgw_270.JPG: 480x640 (no detections), 277.5ms
Speed: 1.1ms preprocess, 277.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPu930ctVl54gDPvdcUPZA_0.JPG: 480x640 (no detections), 263.8ms
Speed: 1.1ms preprocess, 263.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPu930ctVl54gDPvdcUPZA_90.JPG: 480x640 (no detections), 270.8ms
Speed: 1.0ms preprocess, 270.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPu930ctVl54gDPvdcUPZA_180.JPG: 480x640 (no detections), 268.4ms
Speed: 1.0ms preprocess, 268.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPu930ctVl54gDPvdcUPZA_270.JPG: 480x640 (no detections), 266.7ms
Speed: 1.1ms preprocess, 266.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPwTUK-PBK7tJPHrDBwKXg_0.JPG: 480x640 (no detections), 276.4ms
Speed: 1.0ms preprocess, 276.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPwTUK-PBK7tJPHrDBwKXg_90.JPG: 480x640 (no detections), 280.7ms
Speed: 1.0ms preprocess, 280.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPwTUK-PBK7tJPHrDBwKXg_180.JPG: 480x640 (no detections), 273.9ms
Speed: 1.2ms preprocess, 273.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yPwTUK-PBK7tJPHrDBwKXg_270.JPG: 480x640 (no detections), 272.4ms
Speed: 1.0ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQ-6smXafbTsI3VyshFgYw_0.JPG: 480x640 (no detections), 271.7ms
Speed: 1.0ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQ-6smXafbTsI3VyshFgYw_90.JPG: 480x640 (no detections), 274.8ms
Speed: 1.0ms preprocess, 274.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQ-6smXafbTsI3VyshFgYw_180.JPG: 480x640 (no detections), 268.6ms
Speed: 1.2ms preprocess, 268.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQ-6smXafbTsI3VyshFgYw_270.JPG: 480x640 (no detections), 268.3ms
Speed: 1.0ms preprocess, 268.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQ2y6Zr08W1FloHz-iYSXA_0.JPG: 480x640 (no detections), 267.8ms
Speed: 1.1ms preprocess, 267.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQ2y6Zr08W1FloHz-iYSXA_90.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQ2y6Zr08W1FloHz-iYSXA_180.JPG: 480x640 (no detections), 278.6ms
Speed: 1.3ms preprocess, 278.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQ2y6Zr08W1FloHz-iYSXA_270.JPG: 480x640 1 Waste, 270.9ms
Speed: 1.3ms preprocess, 270.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQ4EnYDHCFoJh_vRbfXJzg_0.JPG: 480x640 (no detections), 278.7ms
Speed: 1.1ms preprocess, 278.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQ4EnYDHCFoJh_vRbfXJzg_90.JPG: 480x640 (no detections), 273.2ms
Speed: 1.2ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQ4EnYDHCFoJh_vRbfXJzg_180.JPG: 480x640 (no detections), 270.5ms
Speed: 1.0ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQ4EnYDHCFoJh_vRbfXJzg_270.JPG: 480x640 (no detections), 273.6ms
Speed: 1.1ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQ5yvs_qwRONJpAAjUCmvw_0.JPG: 480x640 (no detections), 283.6ms
Speed: 1.1ms preprocess, 283.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQ5yvs_qwRONJpAAjUCmvw_90.JPG: 480x640 (no detections), 319.3ms
Speed: 1.5ms preprocess, 319.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQ5yvs_qwRONJpAAjUCmvw_180.JPG: 480x640 (no detections), 304.6ms
Speed: 1.2ms preprocess, 304.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQ5yvs_qwRONJpAAjUCmvw_270.JPG: 480x640 (no detections), 306.3ms
Speed: 1.4ms preprocess, 306.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQ7ukpqJqN-3xbojBuYeNg_0.JPG: 480x640 (no detections), 296.6ms
Speed: 1.1ms preprocess, 296.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQ7ukpqJqN-3xbojBuYeNg_90.JPG: 480x640 (no detections), 323.6ms

Speed: 1.4ms preprocess, 323.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQ7ukpqJqN-3xbojBuYeNg_180.JPG: 480x640 (no detections), 307.9ms
Speed: 1.6ms preprocess, 307.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQ7ukpqJqN-3xbojBuYeNg_270.JPG: 480x640 (no detections), 290.1ms
Speed: 1.3ms preprocess, 290.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQ9zQJS-IwMFR9bLZ_ABQg_0.JPG: 480x640 (no detections), 269.8ms
Speed: 1.8ms preprocess, 269.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQ9zQJS-IwMFR9bLZ_ABQg_90.JPG: 480x640 (no detections), 269.7ms
Speed: 1.0ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQ9zQJS-IwMFR9bLZ_ABQg_180.JPG: 480x640 (no detections), 291.2ms
Speed: 1.3ms preprocess, 291.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQ9zQJS-IwMFR9bLZ_ABQg_270.JPG: 480x640 (no detections), 270.4ms
Speed: 1.1ms preprocess, 270.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQHWkyCj4Grpl_AO0rMaOA_0.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQHWkyCj4Grpl_AO0rMaOA_90.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQHWkyCj4Grpl_AO0rMaOA_180.JPG: 480x640 (no detections), 289.9ms
Speed: 1.0ms preprocess, 289.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQHWkyCj4Grpl_AO0rMaOA_270.JPG: 480x640 (no detections), 289.0ms
Speed: 1.1ms preprocess, 289.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQIWpq889Y1HeSHELnnxiw_0.JPG: 480x640 (no detections), 279.2ms
Speed: 1.2ms preprocess, 279.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQIWpq889Y1HeSHELnnxiw_90.JPG: 480x640 (no detections), 288.2ms
Speed: 1.2ms preprocess, 288.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQIWpq889Y1HeSHELnnxiw_180.JPG: 480x640 (no detections), 286.0ms
Speed: 1.1ms preprocess, 286.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQIWpq889Y1HeSHELnnxiw_270.JPG: 480x640 (no detections), 288.3ms
Speed: 1.1ms preprocess, 288.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQJRdWZIQN_TQ94CFIQdaQ_0.JPG: 480x640 (no detections), 305.6ms
Speed: 1.1ms preprocess, 305.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQJRdWZIQN_TQ94CFIQdaQ_90.JPG: 480x640 (no detections), 303.1ms
Speed: 1.1ms preprocess, 303.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQJRdWZIQN_TQ94CFIQdaQ_180.JPG: 480x640 (no detections), 293.1ms
Speed: 1.1ms preprocess, 293.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQJRdWZIQN_TQ94CFIQdaQ_270.JPG: 480x640 (no detections), 283.0ms
Speed: 1.1ms preprocess, 283.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQKiYk-MGL_8nGcotyrmog_0.JPG: 480x640 (no detections), 278.0ms
Speed: 1.2ms preprocess, 278.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQKiYk-MGL_8nGcotyrmog_90.JPG: 480x640 (no detections), 274.5ms
Speed: 1.1ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQKiYk-MGL_8nGcotyrmog_180.JPG: 480x640 (no detections), 270.6ms
Speed: 1.0ms preprocess, 270.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQKiYk-MGL_8nGcotyrmog_270.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQLCBQmM8ZPwnfLNHg-JAA_0.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQLCBQmM8ZPwnfLNHg-JAA_90.JPG: 480x640 (no detections), 269.9ms
Speed: 1.0ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQLCBQmM8ZPwnfLNHg-JAA_180.JPG: 480x640 (no detections), 271.1ms
Speed: 1.0ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQLCBQmM8ZPwnfLNHg-JAA_270.JPG: 480x640 (no detections), 275.9ms
Speed: 1.1ms preprocess, 275.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQLaF8owaYD1yvBJ8yv_wg_0.JPG: 480x640 (no detections), 276.6ms
Speed: 1.0ms preprocess, 276.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQLaF8owaYD1yvBJ8yv_wg_90.JPG: 480x640 (no detections), 267.6ms
Speed: 1.3ms preprocess, 267.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQLaF8owaYD1yvBJ8yv_wg_180.JPG: 480x640 (no detections), 274.0ms
Speed: 1.0ms preprocess, 274.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQLaF8owaYD1yvBJ8yv_wg_270.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQMVBlDzO_swVxV970Lizg_0.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQMVBlDzO_swVxV970Lizg_90.JPG: 480x640 (no detections), 269.0ms
Speed: 1.0ms preprocess, 269.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQMVBlDzO_swVxV970Lizg_180.JPG: 480x640 (no detections), 273.5ms
Speed: 1.2ms preprocess, 273.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQMVBlDzO_swVxV970Lizg_270.JPG: 480x640 (no detections), 275.9ms
Speed: 1.0ms preprocess, 275.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQMeL4d3i8oxYmJSpYSt2A_0.JPG: 480x640 (no detections), 277.8ms
Speed: 1.2ms preprocess, 277.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQMeL4d3i8oxYmJSpYSt2A_90.JPG: 480x640 (no detections), 274.6ms
Speed: 1.0ms preprocess, 274.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQMeL4d3i8oxYmJSpYSt2A_180.JPG: 480x640 (no detections), 273.2ms
Speed: 1.2ms preprocess, 273.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQMeL4d3i8oxYmJSpYSt2A_270.JPG: 480x640 (no detections), 278.8ms
Speed: 1.0ms preprocess, 278.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQMf5UxE_dgK25l2vzAm1g_0.JPG: 480x640 (no detections), 281.2ms
Speed: 1.2ms preprocess, 281.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQMf5UxE_dgK25l2vzAm1g_90.JPG: 480x640 (no detections), 267.9ms
Speed: 1.1ms preprocess, 267.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQMf5UxE_dgK25l2vzAm1g_180.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQMf5UxE_dgK25l2vzAm1g_270.JPG: 480x640 (no detections), 284.4ms
Speed: 1.1ms preprocess, 284.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQNleQ4S778OZg4H88bxVg_0.JPG: 480x640 (no detections), 274.9ms
Speed: 1.0ms preprocess, 274.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQNleQ4S778OZg4H88bxVg_90.JPG: 480x640 (no detections), 275.9ms
Speed: 1.1ms preprocess, 275.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQNleQ4S778OZg4H88bxVg_180.JPG: 480x640 (no detections), 278.3ms
Speed: 1.2ms preprocess, 278.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQNleQ4S778OZg4H88bxVg_270.JPG: 480x640 (no detections), 272.8ms
Speed: 1.2ms preprocess, 272.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQPZVq8eUKkszQdykgKL1A_0.JPG: 480x640 (no detections), 271.0ms
Speed: 1.1ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQPZVq8eUKkszQdykgKL1A_90.JPG: 480x640 (no detections), 273.5ms
Speed: 1.7ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQPZVq8eUKkszQdykgKL1A_180.JPG: 480x640 (no detections), 270.4ms
Speed: 1.2ms preprocess, 270.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQPZVq8eUKkszQdykgKL1A_270.JPG: 480x640 (no detections), 267.4ms
Speed: 1.2ms preprocess, 267.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQQRcUXQZzGLtbGZVHAeOg_0.JPG: 480x640 (no detections), 273.4ms
Speed: 1.1ms preprocess, 273.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQQRcUXQZzGLtbGZVHAeOg_90.JPG: 480x640 (no detections), 277.2ms
Speed: 1.1ms preprocess, 277.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQQRcUXQZzGLtbGZVHAeOg_180.JPG: 480x640 (no detections), 271.2ms
Speed: 1.0ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQQRcUXQZzGLtbGZVHAeOg_270.JPG: 480x640 (no detections), 268.2ms
Speed: 1.1ms preprocess, 268.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQS59h2VdOul5349h4EZ4g_0.JPG: 480x640 (no detections), 274.9ms
Speed: 1.1ms preprocess, 274.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQS59h2VdOul5349h4EZ4g_90.JPG: 480x640 (no detections), 294.9ms
Speed: 1.1ms preprocess, 294.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQS59h2VdOul5349h4EZ4g_180.JPG: 480x640 (no detections), 290.9ms
Speed: 1.2ms preprocess, 290.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQS59h2VdOul5349h4EZ4g_270.JPG: 480x640 (no detections), 276.8ms
Speed: 1.1ms preprocess, 276.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQT-Te-v8nNgeDYk6XoN7A_0.JPG: 480x640 (no detections), 295.4ms
Speed: 1.2ms preprocess, 295.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQT-Te-v8nNgeDYk6XoN7A_90.JPG: 480x640 (no detections), 285.1ms
Speed: 2.0ms preprocess, 285.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQT-Te-v8nNgeDYk6XoN7A_180.JPG: 480x640 (no detections), 277.7ms
Speed: 1.2ms preprocess, 277.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQT-Te-v8nNgeDYk6XoN7A_270.JPG: 480x640 (no detections), 281.7ms
Speed: 1.2ms preprocess, 281.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQTw-uyGywd41YW2DcL9sg_0.JPG: 480x640 (no detections), 272.4ms
Speed: 1.2ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQTw-uyGywd41YW2DcL9sg_90.JPG: 480x640 (no detections), 265.0ms
Speed: 1.1ms preprocess, 265.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQTw-uyGywd41YW2DcL9sg_180.JPG: 480x640 (no detections), 273.1ms
Speed: 1.0ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQTw-uyGywd41YW2DcL9sg_270.JPG: 480x640 (no detections), 274.2ms
Speed: 1.0ms preprocess, 274.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQUtyLFVSUS2YFPeCkxcpg_0.JPG: 480x640 (no detections), 270.7ms

Speed: 1.0ms preprocess, 270.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQUtyLFVSUS2YFPeCkxcpg_90.JPG: 480x640 (no detections), 269.5ms
Speed: 1.1ms preprocess, 269.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQUtyLFVSUS2YFPeCkxcpg_180.JPG: 480x640 (no detections), 291.6ms
Speed: 1.1ms preprocess, 291.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQUtyLFVSUS2YFPeCkxcpg_270.JPG: 480x640 (no detections), 285.0ms
Speed: 1.2ms preprocess, 285.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQXiGEoXgYbHq1kA1tPm9Q_0.JPG: 480x640 (no detections), 284.8ms
Speed: 1.3ms preprocess, 284.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQXiGEoXgYbHq1kA1tPm9Q_90.JPG: 480x640 (no detections), 281.0ms
Speed: 1.1ms preprocess, 281.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQXiGEoXgYbHq1kA1tPm9Q_180.JPG: 480x640 (no detections), 281.4ms
Speed: 1.1ms preprocess, 281.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQXiGEoXgYbHq1kA1tPm9Q_270.JPG: 480x640 (no detections), 280.5ms
Speed: 1.0ms preprocess, 280.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQ_PdURQtNWx-gatLlFzwQ_0.JPG: 480x640 (no detections), 284.4ms
Speed: 1.1ms preprocess, 284.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQ_PdURQtNWx-gatLlFzwQ_90.JPG: 480x640 (no detections), 284.7ms
Speed: 1.2ms preprocess, 284.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQ_PdURQtNWx-gatLlFzwQ_180.JPG: 480x640 (no detections), 280.2ms
Speed: 1.1ms preprocess, 280.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQ_PdURQtNWx-gatLlFzwQ_270.JPG: 480x640 (no detections), 280.5ms
Speed: 1.0ms preprocess, 280.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQgQOxvv7C19pOwIm_3fJg_0.JPG: 480x640 (no detections), 292.4ms
Speed: 1.1ms preprocess, 292.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQgQOxvv7C19pOwIm_3fJg_90.JPG: 480x640 (no detections), 287.1ms
Speed: 1.0ms preprocess, 287.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQgQOxvv7C19pOwIm_3fJg_180.JPG: 480x640 (no detections), 286.0ms
Speed: 1.0ms preprocess, 286.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQgQOxvv7C19pOwIm_3fJg_270.JPG: 480x640 (no detections), 276.9ms
Speed: 1.2ms preprocess, 276.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQlVgCxouqdeD7fpSNxmSQ_0.JPG: 480x640 (no detections), 273.6ms
Speed: 1.1ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQlVgCxouqdeD7fpSNxmSQ_90.JPG: 480x640 (no detections), 277.1ms
Speed: 1.2ms preprocess, 277.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQlVgCxouqdeD7fpSNxmSQ_180.JPG: 480x640 (no detections), 278.8ms
Speed: 1.2ms preprocess, 278.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQlVgCxouqdeD7fpSNxmSQ_270.JPG: 480x640 (no detections), 282.2ms
Speed: 1.1ms preprocess, 282.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQmcsxAOnX5AvxpGxPpsmw_0.JPG: 480x640 (no detections), 284.9ms
Speed: 1.2ms preprocess, 284.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQmcsxAOnX5AvxpGxPpsmw_90.JPG: 480x640 (no detections), 278.1ms
Speed: 1.2ms preprocess, 278.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQmcsxAOnX5AvxpGxPpsmw_180.JPG: 480x640 (no detections), 278.9ms
Speed: 1.2ms preprocess, 278.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQmcsxAOnX5AvxpGxPpsmw_270.JPG: 480x640 (no detections), 278.7ms
Speed: 1.2ms preprocess, 278.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQoW89Nf5v-JE2JMHJo27g_0.JPG: 480x640 (no detections), 278.2ms
Speed: 1.8ms preprocess, 278.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQoW89Nf5v-JE2JMHJo27g_90.JPG: 480x640 (no detections), 281.3ms
Speed: 1.1ms preprocess, 281.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQoW89Nf5v-JE2JMHJo27g_180.JPG: 480x640 (no detections), 280.3ms
Speed: 1.2ms preprocess, 280.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQoW89Nf5v-JE2JMHJo27g_270.JPG: 480x640 (no detections), 278.7ms
Speed: 1.1ms preprocess, 278.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQpKPxb_AQCt7TtD5w1S-Q_0.JPG: 480x640 (no detections), 279.6ms
Speed: 1.1ms preprocess, 279.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQpKPxb_AQCt7TtD5w1S-Q_90.JPG: 480x640 (no detections), 277.0ms
Speed: 1.1ms preprocess, 277.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQpKPxb_AQCt7TtD5w1S-Q_180.JPG: 480x640 (no detections), 288.1ms
Speed: 1.1ms preprocess, 288.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQpKPxb_AQCt7TtD5w1S-Q_270.JPG: 480x640 (no detections), 296.3ms
Speed: 1.0ms preprocess, 296.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQqJNxZ0dIwPROE0vBoZGA_0.JPG: 480x640 (no detections), 287.6ms
Speed: 1.1ms preprocess, 287.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQqJNxZ0dIwPROE0vBoZGA_90.JPG: 480x640 (no detections), 283.0ms
Speed: 1.1ms preprocess, 283.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQqJNxZ0dIwPROE0vBoZGA_180.JPG: 480x640 (no detections), 318.2ms
Speed: 1.1ms preprocess, 318.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQqJNxZ0dIwPROE0vBoZGA_270.JPG: 480x640 (no detections), 296.8ms
Speed: 1.4ms preprocess, 296.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQsYbqOd9eWrS82fvt_Nag_0.JPG: 480x640 (no detections), 303.3ms
Speed: 1.1ms preprocess, 303.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQsYbqOd9eWrS82fvt_Nag_90.JPG: 480x640 (no detections), 285.9ms
Speed: 1.8ms preprocess, 285.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQsYbqOd9eWrS82fvt_Nag_180.JPG: 480x640 (no detections), 302.8ms
Speed: 1.2ms preprocess, 302.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQsYbqOd9eWrS82fvt_Nag_270.JPG: 480x640 (no detections), 331.1ms
Speed: 1.5ms preprocess, 331.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQxdX4lTDT6h23d57_qiYw_0.JPG: 480x640 (no detections), 300.0ms
Speed: 1.2ms preprocess, 300.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQxdX4lTDT6h23d57_qiYw_90.JPG: 480x640 (no detections), 287.4ms
Speed: 1.3ms preprocess, 287.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQxdX4lTDT6h23d57_qiYw_180.JPG: 480x640 (no detections), 294.3ms
Speed: 1.1ms preprocess, 294.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQxdX4lTDT6h23d57_qiYw_270.JPG: 480x640 (no detections), 290.3ms
Speed: 1.2ms preprocess, 290.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQylM_-lxZOgpegKwVLdZg_0.JPG: 480x640 (no detections), 285.7ms
Speed: 1.0ms preprocess, 285.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQylM_-lxZOgpegKwVLdZg_90.JPG: 480x640 (no detections), 292.8ms
Speed: 1.1ms preprocess, 292.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQylM_-lxZOgpegKwVLdZg_180.JPG: 480x640 (no detections), 287.5ms
Speed: 1.2ms preprocess, 287.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yQylM_-lxZOgpegKwVLdZg_270.JPG: 480x640 (no detections), 292.4ms
Speed: 1.0ms preprocess, 292.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yR-HnYgavRLSN0clx7zNTA_0.JPG: 480x640 1 Waste, 289.0ms
Speed: 1.1ms preprocess, 289.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yR-HnYgavRLSN0clx7zNTA_90.JPG: 480x640 (no detections), 279.7ms
Speed: 1.1ms preprocess, 279.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yR-HnYgavRLSN0clx7zNTA_180.JPG: 480x640 (no detections), 287.3ms
Speed: 1.0ms preprocess, 287.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yR-HnYgavRLSN0clx7zNTA_270.JPG: 480x640 (no detections), 281.0ms
Speed: 1.1ms preprocess, 281.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yR3W0AURm2T-4XS5l0kAwQ_0.JPG: 480x640 (no detections), 285.2ms
Speed: 1.0ms preprocess, 285.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yR3W0AURm2T-4XS5l0kAwQ_90.JPG: 480x640 (no detections), 286.0ms
Speed: 1.1ms preprocess, 286.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yR3W0AURm2T-4XS5l0kAwQ_180.JPG: 480x640 (no detections), 291.5ms
Speed: 1.1ms preprocess, 291.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yR3W0AURm2T-4XS5l0kAwQ_270.JPG: 480x640 (no detections), 307.8ms
Speed: 1.1ms preprocess, 307.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yR5cbncxyhBN2tIdWSVJZA_0.JPG: 480x640 (no detections), 293.6ms
Speed: 1.3ms preprocess, 293.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yR5cbncxyhBN2tIdWSVJZA_90.JPG: 480x640 (no detections), 295.0ms
Speed: 1.3ms preprocess, 295.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yR5cbncxyhBN2tIdWSVJZA_180.JPG: 480x640 (no detections), 285.1ms
Speed: 1.1ms preprocess, 285.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yR5cbncxyhBN2tIdWSVJZA_270.JPG: 480x640 (no detections), 287.2ms
Speed: 1.1ms preprocess, 287.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yR5zQSz8vdoVEqfRTv4zLw_0.JPG: 480x640 (no detections), 288.6ms
Speed: 1.2ms preprocess, 288.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yR5zQSz8vdoVEqfRTv4zLw_90.JPG: 480x640 (no detections), 289.7ms
Speed: 1.1ms preprocess, 289.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yR5zQSz8vdoVEqfRTv4zLw_180.JPG: 480x640 (no detections), 278.4ms
Speed: 1.1ms preprocess, 278.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yR5zQSz8vdoVEqfRTv4zLw_270.JPG: 480x640 (no detections), 281.0ms
Speed: 1.1ms preprocess, 281.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yR6ktn-tcI-EMTCMW8TzJA_0.JPG: 480x640 (no detections), 283.5ms
Speed: 1.2ms preprocess, 283.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yR6ktn-tcI-EMTCMW8TzJA_90.JPG: 480x640 (no detections), 281.7ms
Speed: 1.1ms preprocess, 281.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yR6ktn-tcI-EMTCMW8TzJA_180.JPG: 480x640 (no detections), 276.9ms
Speed: 1.1ms preprocess, 276.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yR6ktn-tcI-EMTCMW8TzJA_270.JPG: 480x640 (no detections), 279.6ms

Speed: 1.2ms preprocess, 279.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yR85qX4Od_pUFjVGPxcwMw_0.JPG: 480x640 (no detections), 282.3ms
Speed: 1.2ms preprocess, 282.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yR85qX4Od_pUFjVGPxcwMw_90.JPG: 480x640 (no detections), 282.9ms
Speed: 1.1ms preprocess, 282.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yR85qX4Od_pUFjVGPxcwMw_180.JPG: 480x640 (no detections), 291.6ms
Speed: 1.0ms preprocess, 291.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yR85qX4Od_pUFjVGPxcwMw_270.JPG: 480x640 (no detections), 291.3ms
Speed: 1.3ms preprocess, 291.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yR8v-VEwbFXrXyqefiA__w_0.JPG: 480x640 (no detections), 284.5ms
Speed: 1.3ms preprocess, 284.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yR8v-VEwbFXrXyqefiA__w_90.JPG: 480x640 (no detections), 285.5ms
Speed: 1.1ms preprocess, 285.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yR8v-VEwbFXrXyqefiA__w_180.JPG: 480x640 (no detections), 280.6ms
Speed: 1.1ms preprocess, 280.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yR8v-VEwbFXrXyqefiA__w_270.JPG: 480x640 (no detections), 291.8ms
Speed: 1.2ms preprocess, 291.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yR95qGakE4SN6JhylYellQ_0.JPG: 480x640 (no detections), 285.7ms
Speed: 1.2ms preprocess, 285.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yR95qGakE4SN6JhylYellQ_90.JPG: 480x640 (no detections), 310.1ms
Speed: 1.8ms preprocess, 310.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yR95qGakE4SN6JhylYellQ_180.JPG: 480x640 (no detections), 289.2ms
Speed: 1.1ms preprocess, 289.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yR95qGakE4SN6JhylYellQ_270.JPG: 480x640 (no detections), 281.4ms
Speed: 1.1ms preprocess, 281.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yR9K9l7YQf2A40gG-bNWlA_0.JPG: 480x640 (no detections), 293.1ms
Speed: 1.1ms preprocess, 293.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yR9K9l7YQf2A40gG-bNWlA_90.JPG: 480x640 (no detections), 280.6ms
Speed: 1.1ms preprocess, 280.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yR9K9l7YQf2A40gG-bNWlA_180.JPG: 480x640 (no detections), 286.5ms
Speed: 1.0ms preprocess, 286.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yR9K9l7YQf2A40gG-bNWlA_270.JPG: 480x640 (no detections), 281.6ms
Speed: 1.1ms preprocess, 281.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRHdz4-FhTzxLoc7j7U-dg_0.JPG: 480x640 (no detections), 288.0ms
Speed: 1.1ms preprocess, 288.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRHdz4-FhTzxLoc7j7U-dg_90.JPG: 480x640 (no detections), 295.4ms
Speed: 1.1ms preprocess, 295.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRHdz4-FhTzxLoc7j7U-dg_180.JPG: 480x640 (no detections), 304.0ms
Speed: 1.1ms preprocess, 304.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRHdz4-FhTzxLoc7j7U-dg_270.JPG: 480x640 (no detections), 295.3ms
Speed: 1.2ms preprocess, 295.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRJ6p0Yb7cAhPDaGk2FpQA_0.JPG: 480x640 (no detections), 290.9ms
Speed: 1.1ms preprocess, 290.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRJ6p0Yb7cAhPDaGk2FpQA_90.JPG: 480x640 (no detections), 294.2ms
Speed: 1.1ms preprocess, 294.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRJ6p0Yb7cAhPDaGk2FpQA_180.JPG: 480x640 (no detections), 284.6ms
Speed: 1.1ms preprocess, 284.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRJ6p0Yb7cAhPDaGk2FpQA_270.JPG: 480x640 (no detections), 281.6ms
Speed: 1.1ms preprocess, 281.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRKG1-YbuLfOmte4jnWW_g_0.JPG: 480x640 (no detections), 280.0ms
Speed: 1.1ms preprocess, 280.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRKG1-YbuLfOmte4jnWW_g_90.JPG: 480x640 (no detections), 280.1ms
Speed: 1.2ms preprocess, 280.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRKG1-YbuLfOmte4jnWW_g_180.JPG: 480x640 (no detections), 285.6ms
Speed: 1.3ms preprocess, 285.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRKG1-YbuLfOmte4jnWW_g_270.JPG: 480x640 (no detections), 281.7ms
Speed: 1.1ms preprocess, 281.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRMXMOtsQxNiiatFBUEyqQ_0.JPG: 480x640 (no detections), 279.1ms
Speed: 1.6ms preprocess, 279.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRMXMOtsQxNiiatFBUEyqQ_90.JPG: 480x640 (no detections), 281.8ms
Speed: 1.1ms preprocess, 281.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRMXMOtsQxNiiatFBUEyqQ_180.JPG: 480x640 (no detections), 282.2ms
Speed: 1.1ms preprocess, 282.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRMXMOtsQxNiiatFBUEyqQ_270.JPG: 480x640 (no detections), 276.3ms
Speed: 1.7ms preprocess, 276.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRN3e1pfPz5E6qW3XxHIHQ_0.JPG: 480x640 (no detections), 279.2ms
Speed: 1.0ms preprocess, 279.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRN3e1pfPz5E6qW3XxHIHQ_90.JPG: 480x640 (no detections), 279.7ms
Speed: 1.3ms preprocess, 279.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRN3e1pfPz5E6qW3XxHIHQ_180.JPG: 480x640 (no detections), 281.5ms
Speed: 1.1ms preprocess, 281.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRN3e1pfPz5E6qW3XxHIHQ_270.JPG: 480x640 (no detections), 279.9ms
Speed: 1.1ms preprocess, 279.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRPViIZiTyogJmzWgQDlfg_0.JPG: 480x640 (no detections), 284.1ms
Speed: 1.1ms preprocess, 284.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRPViIZiTyogJmzWgQDlfg_90.JPG: 480x640 (no detections), 296.1ms
Speed: 1.0ms preprocess, 296.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRPViIZiTyogJmzWgQDlfg_180.JPG: 480x640 (no detections), 282.7ms
Speed: 1.1ms preprocess, 282.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRPViIZiTyogJmzWgQDlfg_270.JPG: 480x640 (no detections), 281.6ms
Speed: 1.1ms preprocess, 281.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRPflcg1hnBL4Vpb9M40-Q_0.JPG: 480x640 (no detections), 287.2ms
Speed: 1.2ms preprocess, 287.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRPflcg1hnBL4Vpb9M40-Q_90.JPG: 480x640 (no detections), 294.2ms
Speed: 1.8ms preprocess, 294.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRPflcg1hnBL4Vpb9M40-Q_180.JPG: 480x640 (no detections), 291.9ms
Speed: 1.4ms preprocess, 291.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRPflcg1hnBL4Vpb9M40-Q_270.JPG: 480x640 (no detections), 280.7ms
Speed: 1.2ms preprocess, 280.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRWr95R1us83hvEpvDTISA_0.JPG: 480x640 (no detections), 280.1ms
Speed: 1.0ms preprocess, 280.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRWr95R1us83hvEpvDTISA_90.JPG: 480x640 (no detections), 296.4ms
Speed: 1.2ms preprocess, 296.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRWr95R1us83hvEpvDTISA_180.JPG: 480x640 (no detections), 284.1ms
Speed: 1.3ms preprocess, 284.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRWr95R1us83hvEpvDTISA_270.JPG: 480x640 (no detections), 282.1ms
Speed: 1.1ms preprocess, 282.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRXVs5QUY63lU-RxsSEVQA_0.JPG: 480x640 (no detections), 296.0ms
Speed: 1.9ms preprocess, 296.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRXVs5QUY63lU-RxsSEVQA_90.JPG: 480x640 (no detections), 300.9ms
Speed: 1.1ms preprocess, 300.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRXVs5QUY63lU-RxsSEVQA_180.JPG: 480x640 (no detections), 292.8ms
Speed: 1.3ms preprocess, 292.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRXVs5QUY63lU-RxsSEVQA_270.JPG: 480x640 (no detections), 295.5ms
Speed: 1.3ms preprocess, 295.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRZd790wBrimt2a9SqAjsg_0.JPG: 480x640 (no detections), 296.7ms
Speed: 1.7ms preprocess, 296.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRZd790wBrimt2a9SqAjsg_90.JPG: 480x640 (no detections), 288.1ms
Speed: 1.3ms preprocess, 288.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRZd790wBrimt2a9SqAjsg_180.JPG: 480x640 (no detections), 303.5ms
Speed: 1.7ms preprocess, 303.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRZd790wBrimt2a9SqAjsg_270.JPG: 480x640 (no detections), 293.1ms
Speed: 1.2ms preprocess, 293.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRboosl_tkbvahi0arG8DQ_0.JPG: 480x640 (no detections), 284.5ms
Speed: 1.2ms preprocess, 284.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRboosl_tkbvahi0arG8DQ_90.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRboosl_tkbvahi0arG8DQ_180.JPG: 480x640 (no detections), 270.0ms
Speed: 1.0ms preprocess, 270.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRboosl_tkbvahi0arG8DQ_270.JPG: 480x640 (no detections), 268.4ms
Speed: 1.0ms preprocess, 268.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yReOnXAiep77rvpgsi5hjA_0.JPG: 480x640 (no detections), 267.8ms
Speed: 1.1ms preprocess, 267.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yReOnXAiep77rvpgsi5hjA_90.JPG: 480x640 (no detections), 271.9ms
Speed: 1.0ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yReOnXAiep77rvpgsi5hjA_180.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yReOnXAiep77rvpgsi5hjA_270.JPG: 480x640 (no detections), 272.6ms
Speed: 1.0ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRfiLbfE2yE6d3UTf1NOBA_0.JPG: 480x640 (no detections), 267.8ms
Speed: 1.1ms preprocess, 267.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRfiLbfE2yE6d3UTf1NOBA_90.JPG: 480x640 (no detections), 275.1ms
Speed: 1.2ms preprocess, 275.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRfiLbfE2yE6d3UTf1NOBA_180.JPG: 480x640 (no detections), 272.5ms

Speed: 1.1ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRfiLbfE2yE6d3UTf1NOBA_270.JPG: 480x640 (no detections), 274.9ms
Speed: 1.1ms preprocess, 274.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRjWCY3hxPKnkggz8-VQ2A_0.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRjWCY3hxPKnkggz8-VQ2A_90.JPG: 480x640 (no detections), 271.3ms
Speed: 1.0ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRjWCY3hxPKnkggz8-VQ2A_180.JPG: 480x640 (no detections), 279.4ms
Speed: 1.2ms preprocess, 279.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRjWCY3hxPKnkggz8-VQ2A_270.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRlCvNgOVeKjK4zFZWyQWg_0.JPG: 480x640 (no detections), 268.6ms
Speed: 1.0ms preprocess, 268.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRlCvNgOVeKjK4zFZWyQWg_90.JPG: 480x640 (no detections), 280.0ms
Speed: 1.2ms preprocess, 280.0ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRlCvNgOVeKjK4zFZWyQWg_180.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRlCvNgOVeKjK4zFZWyQWg_270.JPG: 480x640 (no detections), 271.2ms
Speed: 1.0ms preprocess, 271.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRpnkdXtr96zrjrUTEbUcg_0.JPG: 480x640 (no detections), 272.1ms
Speed: 1.0ms preprocess, 272.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRpnkdXtr96zrjrUTEbUcg_90.JPG: 480x640 (no detections), 280.4ms
Speed: 1.2ms preprocess, 280.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRpnkdXtr96zrjrUTEbUcg_180.JPG: 480x640 (no detections), 267.1ms
Speed: 1.1ms preprocess, 267.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRpnkdXtr96zrjrUTEbUcg_270.JPG: 480x640 (no detections), 268.4ms
Speed: 1.0ms preprocess, 268.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRqxZr2-VfKOxi_zPr51ww_0.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRqxZr2-VfKOxi_zPr51ww_90.JPG: 480x640 (no detections), 270.4ms
Speed: 1.0ms preprocess, 270.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRqxZr2-VfKOxi_zPr51ww_180.JPG: 480x640 (no detections), 271.2ms
Speed: 1.0ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRqxZr2-VfKOxi_zPr51ww_270.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRrgGrcK-9hggMPjRKXoLQ_0.JPG: 480x640 (no detections), 269.8ms
Speed: 1.2ms preprocess, 269.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRrgGrcK-9hggMPjRKXoLQ_90.JPG: 480x640 (no detections), 269.3ms
Speed: 1.0ms preprocess, 269.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRrgGrcK-9hggMPjRKXoLQ_180.JPG: 480x640 (no detections), 268.0ms
Speed: 1.1ms preprocess, 268.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRrgGrcK-9hggMPjRKXoLQ_270.JPG: 480x640 (no detections), 274.1ms
Speed: 0.9ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRsnm6IrTSwR7VmD2WTdCg_0.JPG: 480x640 (no detections), 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRsnm6IrTSwR7VmD2WTdCg_90.JPG: 480x640 (no detections), 268.4ms
Speed: 1.0ms preprocess, 268.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRsnm6IrTSwR7VmD2WTdCg_180.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRsnm6IrTSwR7VmD2WTdCg_270.JPG: 480x640 (no detections), 274.4ms
Speed: 1.0ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRxoVgN7x-OyuMNwnx0Wew_0.JPG: 480x640 (no detections), 272.9ms
Speed: 1.2ms preprocess, 272.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRxoVgN7x-OyuMNwnx0Wew_90.JPG: 480x640 (no detections), 276.3ms
Speed: 1.2ms preprocess, 276.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRxoVgN7x-OyuMNwnx0Wew_180.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRxoVgN7x-OyuMNwnx0Wew_270.JPG: 480x640 (no detections), 270.3ms
Speed: 1.1ms preprocess, 270.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRzbZlTbhAk3ROjd0acHZw_0.JPG: 480x640 (no detections), 278.7ms
Speed: 1.1ms preprocess, 278.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRzbZlTbhAk3ROjd0acHZw_90.JPG: 480x640 (no detections), 270.5ms
Speed: 1.1ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRzbZlTbhAk3ROjd0acHZw_180.JPG: 480x640 (no detections), 266.7ms
Speed: 1.0ms preprocess, 266.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yRzbZlTbhAk3ROjd0acHZw_270.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/yS1Ae3L2MmQj1avObY47sg_0.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/yS1Ae3L2MmQj1avObY47sg_90.JPG: 480x640 (no detections), 266.6ms
Speed: 1.0ms preprocess, 266.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/yS1Ae3L2MmQj1avObY47sg_180.JPG: 480x640 (no detections), 271.2ms
Speed: 1.0ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/yS1Ae3L2MmQj1avObY47sg_270.JPG: 480x640 (no detections), 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/yS3FIOjVX1emXHqwHlOCHw_0.JPG: 480x640 1 Waste, 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/yS3FIOjVX1emXHqwHlOCHw_90.JPG: 480x640 (no detections), 270.5ms
Speed: 1.0ms preprocess, 270.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/yS3FIOjVX1emXHqwHlOCHw_180.JPG: 480x640 (no detections), 276.0ms
Speed: 1.0ms preprocess, 276.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/yS3FIOjVX1emXHqwHlOCHw_270.JPG: 480x640 (no detections), 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/yS6ldtmXjmtszaRDNo4_MA_0.JPG: 480x640 (no detections), 273.8ms
Speed: 1.0ms preprocess, 273.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/yS6ldtmXjmtszaRDNo4_MA_90.JPG: 480x640 (no detections), 273.5ms
Speed: 1.0ms preprocess, 273.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/yS6ldtmXjmtszaRDNo4_MA_180.JPG: 480x640 (no detections), 273.7ms
Speed: 1.0ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/yS6ldtmXjmtszaRDNo4_MA_270.JPG: 480x640 (no detections), 266.4ms
Speed: 1.0ms preprocess, 266.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySBSwFOZUUQlDWatZ-fStg_0.JPG: 480x640 (no detections), 269.5ms
Speed: 1.1ms preprocess, 269.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySBSwFOZUUQlDWatZ-fStg_90.JPG: 480x640 (no detections), 270.4ms
Speed: 1.1ms preprocess, 270.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySBSwFOZUUQlDWatZ-fStg_180.JPG: 480x640 (no detections), 266.4ms
Speed: 1.0ms preprocess, 266.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySBSwFOZUUQlDWatZ-fStg_270.JPG: 480x640 1 Waste, 268.4ms
Speed: 1.0ms preprocess, 268.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySBpuGTueZB1gCpX45lDxA_0.JPG: 480x640 (no detections), 267.9ms
Speed: 1.1ms preprocess, 267.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySBpuGTueZB1gCpX45lDxA_90.JPG: 480x640 (no detections), 273.2ms
Speed: 1.1ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySBpuGTueZB1gCpX45lDxA_180.JPG: 480x640 (no detections), 269.7ms
Speed: 1.0ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySBpuGTueZB1gCpX45lDxA_270.JPG: 480x640 (no detections), 272.7ms
Speed: 1.2ms preprocess, 272.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySFEzFqTtXr2RtR82XY0kg_0.JPG: 480x640 (no detections), 275.3ms
Speed: 1.0ms preprocess, 275.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySFEzFqTtXr2RtR82XY0kg_90.JPG: 480x640 (no detections), 275.2ms
Speed: 1.2ms preprocess, 275.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySFEzFqTtXr2RtR82XY0kg_180.JPG: 480x640 (no detections), 269.4ms
Speed: 1.0ms preprocess, 269.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySFEzFqTtXr2RtR82XY0kg_270.JPG: 480x640 (no detections), 279.9ms
Speed: 1.1ms preprocess, 279.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySHacHnLvba2xvRVjysypw_0.JPG: 480x640 (no detections), 274.6ms
Speed: 1.1ms preprocess, 274.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySHacHnLvba2xvRVjysypw_90.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySHacHnLvba2xvRVjysypw_180.JPG: 480x640 (no detections), 269.9ms
Speed: 1.0ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySHacHnLvba2xvRVjysypw_270.JPG: 480x640 (no detections), 270.7ms
Speed: 1.0ms preprocess, 270.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySJGqw826VtQE7C8RE2m7A_0.JPG: 480x640 (no detections), 269.6ms
Speed: 1.1ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySJGqw826VtQE7C8RE2m7A_90.JPG: 480x640 (no detections), 273.8ms
Speed: 1.0ms preprocess, 273.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySJGqw826VtQE7C8RE2m7A_180.JPG: 480x640 (no detections), 267.0ms
Speed: 1.0ms preprocess, 267.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySJGqw826VtQE7C8RE2m7A_270.JPG: 480x640 (no detections), 270.5ms
Speed: 1.0ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySK1uVrd121GkjHXJ_2RPw_0.JPG: 480x640 (no detections), 269.0ms
Speed: 1.0ms preprocess, 269.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySK1uVrd121GkjHXJ_2RPw_90.JPG: 480x640 (no detections), 269.4ms

Speed: 1.0ms preprocess, 269.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySK1uVrd121GkjHXJ_2RPw_180.JPG: 480x640 (no detections), 271.4ms
Speed: 1.0ms preprocess, 271.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySK1uVrd121GkjHXJ_2RPw_270.JPG: 480x640 (no detections), 276.1ms
Speed: 1.0ms preprocess, 276.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySKC7lnruDN_tQGJzMMImw_0.JPG: 480x640 (no detections), 268.6ms
Speed: 1.1ms preprocess, 268.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySKC7lnruDN_tQGJzMMImw_90.JPG: 480x640 (no detections), 269.2ms
Speed: 1.0ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySKC7lnruDN_tQGJzMMImw_180.JPG: 480x640 (no detections), 269.6ms
Speed: 1.1ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySKC7lnruDN_tQGJzMMImw_270.JPG: 480x640 (no detections), 266.3ms
Speed: 1.0ms preprocess, 266.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySLrGMNgL3hLWTUCrSNt4w_0.JPG: 480x640 (no detections), 278.8ms
Speed: 1.0ms preprocess, 278.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySLrGMNgL3hLWTUCrSNt4w_90.JPG: 480x640 (no detections), 269.3ms
Speed: 1.1ms preprocess, 269.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySLrGMNgL3hLWTUCrSNt4w_180.JPG: 480x640 (no detections), 276.7ms
Speed: 1.1ms preprocess, 276.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySLrGMNgL3hLWTUCrSNt4w_270.JPG: 480x640 (no detections), 272.6ms
Speed: 1.2ms preprocess, 272.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/yST7OiuZvnUItmDRtBtBPA_0.JPG: 480x640 (no detections), 268.5ms
Speed: 1.0ms preprocess, 268.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/yST7OiuZvnUItmDRtBtBPA_90.JPG: 480x640 (no detections), 270.3ms
Speed: 1.0ms preprocess, 270.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/yST7OiuZvnUItmDRtBtBPA_180.JPG: 480x640 (no detections), 272.4ms
Speed: 1.0ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/yST7OiuZvnUItmDRtBtBPA_270.JPG: 480x640 (no detections), 267.0ms
Speed: 1.0ms preprocess, 267.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySWtRcmnxQBCsm_-XgIQIA_0.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySWtRcmnxQBCsm_-XgIQIA_90.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySWtRcmnxQBCsm_-XgIQIA_180.JPG: 480x640 (no detections), 275.5ms
Speed: 1.0ms preprocess, 275.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySWtRcmnxQBCsm_-XgIQIA_270.JPG: 480x640 (no detections), 267.4ms
Speed: 1.0ms preprocess, 267.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySaiPs8YUIr__iBnnEwqTw_0.JPG: 480x640 (no detections), 273.6ms
Speed: 1.0ms preprocess, 273.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySaiPs8YUIr__iBnnEwqTw_90.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySaiPs8YUIr__iBnnEwqTw_180.JPG: 480x640 (no detections), 270.8ms
Speed: 1.0ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySaiPs8YUIr__iBnnEwqTw_270.JPG: 480x640 (no detections), 274.0ms
Speed: 1.1ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySevyQbJl4_WoJlJ-0v0Jw_0.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySevyQbJl4_WoJlJ-0v0Jw_90.JPG: 480x640 (no detections), 272.0ms
Speed: 1.0ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySevyQbJl4_WoJlJ-0v0Jw_180.JPG: 480x640 (no detections), 277.5ms
Speed: 1.2ms preprocess, 277.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySevyQbJl4_WoJlJ-0v0Jw_270.JPG: 480x640 (no detections), 283.0ms
Speed: 1.1ms preprocess, 283.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySfeK1NWdg6qhKA0DX9jvA_0.JPG: 480x640 (no detections), 277.2ms
Speed: 1.3ms preprocess, 277.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySfeK1NWdg6qhKA0DX9jvA_90.JPG: 480x640 (no detections), 273.7ms
Speed: 1.0ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySfeK1NWdg6qhKA0DX9jvA_180.JPG: 480x640 (no detections), 267.3ms
Speed: 1.1ms preprocess, 267.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySfeK1NWdg6qhKA0DX9jvA_270.JPG: 480x640 (no detections), 275.7ms
Speed: 1.1ms preprocess, 275.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySgiQ1xv8vpUW8EdomcbLA_0.JPG: 480x640 (no detections), 286.1ms
Speed: 1.0ms preprocess, 286.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySgiQ1xv8vpUW8EdomcbLA_90.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySgiQ1xv8vpUW8EdomcbLA_180.JPG: 480x640 (no detections), 271.0ms
Speed: 1.0ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySgiQ1xv8vpUW8EdomcbLA_270.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySrDLmpKOyCLAj11Gh3syQ_0.JPG: 480x640 (no detections), 281.5ms
Speed: 1.0ms preprocess, 281.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySrDLmpKOyCLAj11Gh3syQ_90.JPG: 480x640 (no detections), 272.0ms
Speed: 1.0ms preprocess, 272.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySrDLmpKOyCLAj11Gh3syQ_180.JPG: 480x640 (no detections), 275.6ms
Speed: 1.0ms preprocess, 275.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySrDLmpKOyCLAj11Gh3syQ_270.JPG: 480x640 (no detections), 272.0ms
Speed: 1.0ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySsSPJlWefLkk82txbM_kQ_0.JPG: 480x640 (no detections), 270.4ms
Speed: 1.0ms preprocess, 270.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySsSPJlWefLkk82txbM_kQ_90.JPG: 480x640 (no detections), 274.9ms
Speed: 1.1ms preprocess, 274.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySsSPJlWefLkk82txbM_kQ_180.JPG: 480x640 (no detections), 282.1ms
Speed: 1.1ms preprocess, 282.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySsSPJlWefLkk82txbM_kQ_270.JPG: 480x640 (no detections), 270.7ms
Speed: 1.3ms preprocess, 270.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySsaZD-mxKUK1LzwM57wAA_0.JPG: 480x640 (no detections), 271.8ms
Speed: 1.0ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySsaZD-mxKUK1LzwM57wAA_90.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySsaZD-mxKUK1LzwM57wAA_180.JPG: 480x640 (no detections), 268.4ms
Speed: 1.0ms preprocess, 268.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySsaZD-mxKUK1LzwM57wAA_270.JPG: 480x640 (no detections), 275.2ms
Speed: 1.1ms preprocess, 275.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySvHEFLTOWQKBkW8TSjrWA_0.JPG: 480x640 (no detections), 266.7ms
Speed: 1.1ms preprocess, 266.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySvHEFLTOWQKBkW8TSjrWA_90.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySvHEFLTOWQKBkW8TSjrWA_180.JPG: 480x640 (no detections), 266.3ms
Speed: 1.1ms preprocess, 266.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySvHEFLTOWQKBkW8TSjrWA_270.JPG: 480x640 (no detections), 270.9ms
Speed: 1.1ms preprocess, 270.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySwgNUqo0vZZ5j6ge1Pbeg_0.JPG: 480x640 (no detections), 272.8ms
Speed: 1.2ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySwgNUqo0vZZ5j6ge1Pbeg_90.JPG: 480x640 1 Waste, 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySwgNUqo0vZZ5j6ge1Pbeg_180.JPG: 480x640 (no detections), 273.2ms
Speed: 1.1ms preprocess, 273.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySwgNUqo0vZZ5j6ge1Pbeg_270.JPG: 480x640 (no detections), 270.3ms
Speed: 1.0ms preprocess, 270.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySzGPG_8v78o3gD4gpg1Bg_0.JPG: 480x640 (no detections), 266.5ms
Speed: 1.0ms preprocess, 266.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySzGPG_8v78o3gD4gpg1Bg_90.JPG: 480x640 (no detections), 267.8ms
Speed: 1.0ms preprocess, 267.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySzGPG_8v78o3gD4gpg1Bg_180.JPG: 480x640 1 Waste, 276.5ms
Speed: 1.1ms preprocess, 276.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ySzGPG_8v78o3gD4gpg1Bg_270.JPG: 480x640 (no detections), 281.4ms
Speed: 1.1ms preprocess, 281.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yT18xxGkjEnz1wyblcaNkg_0.JPG: 480x640 (no detections), 270.8ms
Speed: 1.0ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yT18xxGkjEnz1wyblcaNkg_90.JPG: 480x640 (no detections), 275.3ms
Speed: 1.0ms preprocess, 275.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yT18xxGkjEnz1wyblcaNkg_180.JPG: 480x640 (no detections), 281.5ms
Speed: 1.0ms preprocess, 281.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yT18xxGkjEnz1wyblcaNkg_270.JPG: 480x640 (no detections), 280.9ms
Speed: 1.1ms preprocess, 280.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yT1OiMa6EEcb9-ujBdlumA_0.JPG: 480x640 (no detections), 277.4ms
Speed: 1.1ms preprocess, 277.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yT1OiMa6EEcb9-ujBdlumA_90.JPG: 480x640 (no detections), 269.3ms
Speed: 1.0ms preprocess, 269.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yT1OiMa6EEcb9-ujBdlumA_180.JPG: 480x640 (no detections), 270.6ms
Speed: 1.0ms preprocess, 270.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yT1OiMa6EEcb9-ujBdlumA_270.JPG: 480x640 (no detections), 285.6ms
Speed: 1.1ms preprocess, 285.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yT3D5yY_HnNMbm6o1qBZWQ_0.JPG: 480x640 (no detections), 275.0ms

Speed: 1.0ms preprocess, 275.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yT3D5yY_HnNMbm6o1qBZWQ_90.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yT3D5yY_HnNMbm6o1qBZWQ_180.JPG: 480x640 (no detections), 274.2ms
Speed: 1.2ms preprocess, 274.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yT3D5yY_HnNMbm6o1qBZWQ_270.JPG: 480x640 (no detections), 280.0ms
Speed: 1.0ms preprocess, 280.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTB-sy7hCwE2C21OT6VL7A_0.JPG: 480x640 (no detections), 280.6ms
Speed: 1.8ms preprocess, 280.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTB-sy7hCwE2C21OT6VL7A_90.JPG: 480x640 1 Waste, 282.4ms
Speed: 1.1ms preprocess, 282.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTB-sy7hCwE2C21OT6VL7A_180.JPG: 480x640 1 Waste, 293.3ms
Speed: 1.0ms preprocess, 293.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTB-sy7hCwE2C21OT6VL7A_270.JPG: 480x640 (no detections), 280.9ms
Speed: 1.1ms preprocess, 280.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTC41XnsQYlpyvHknBz-Rg_0.JPG: 480x640 (no detections), 275.3ms
Speed: 1.2ms preprocess, 275.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTC41XnsQYlpyvHknBz-Rg_90.JPG: 480x640 (no detections), 306.4ms
Speed: 1.1ms preprocess, 306.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTC41XnsQYlpyvHknBz-Rg_180.JPG: 480x640 (no detections), 277.3ms
Speed: 1.1ms preprocess, 277.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTC41XnsQYlpyvHknBz-Rg_270.JPG: 480x640 (no detections), 275.4ms
Speed: 1.1ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTFODBPdjP6f10Pe4QLTdw_0.JPG: 480x640 (no detections), 276.3ms
Speed: 1.1ms preprocess, 276.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTFODBPdjP6f10Pe4QLTdw_90.JPG: 480x640 (no detections), 270.3ms
Speed: 1.2ms preprocess, 270.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTFODBPdjP6f10Pe4QLTdw_180.JPG: 480x640 (no detections), 269.5ms
Speed: 1.1ms preprocess, 269.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTFODBPdjP6f10Pe4QLTdw_270.JPG: 480x640 (no detections), 271.0ms
Speed: 1.0ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTFZ_vf6Rzcj7IWbxKKX2Q_0.JPG: 480x640 (no detections), 267.9ms
Speed: 1.0ms preprocess, 267.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTFZ_vf6Rzcj7IWbxKKX2Q_90.JPG: 480x640 (no detections), 270.9ms
Speed: 1.0ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTFZ_vf6Rzcj7IWbxKKX2Q_180.JPG: 480x640 (no detections), 269.2ms
Speed: 1.2ms preprocess, 269.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTFZ_vf6Rzcj7IWbxKKX2Q_270.JPG: 480x640 (no detections), 270.3ms
Speed: 1.1ms preprocess, 270.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTHh1Mc5GucqitXs0Ko0zg_0.JPG: 480x640 (no detections), 266.6ms
Speed: 1.1ms preprocess, 266.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTHh1Mc5GucqitXs0Ko0zg_90.JPG: 480x640 (no detections), 272.0ms
Speed: 1.0ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTHh1Mc5GucqitXs0Ko0zg_180.JPG: 480x640 (no detections), 274.3ms
Speed: 1.0ms preprocess, 274.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTHh1Mc5GucqitXs0Ko0zg_270.JPG: 480x640 1 Waste, 267.8ms
Speed: 1.0ms preprocess, 267.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTJuhiwszYnWMgUyjnfpGw_0.JPG: 480x640 (no detections), 268.5ms
Speed: 1.1ms preprocess, 268.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTJuhiwszYnWMgUyjnfpGw_90.JPG: 480x640 (no detections), 270.5ms
Speed: 1.0ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTJuhiwszYnWMgUyjnfpGw_180.JPG: 480x640 (no detections), 268.3ms
Speed: 1.0ms preprocess, 268.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTJuhiwszYnWMgUyjnfpGw_270.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTO-bSNnR6FBn2JFTjZ1Og_0.JPG: 480x640 (no detections), 275.8ms
Speed: 1.0ms preprocess, 275.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTO-bSNnR6FBn2JFTjZ1Og_90.JPG: 480x640 (no detections), 266.6ms
Speed: 1.0ms preprocess, 266.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTO-bSNnR6FBn2JFTjZ1Og_180.JPG: 480x640 (no detections), 268.8ms
Speed: 1.1ms preprocess, 268.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTO-bSNnR6FBn2JFTjZ1Og_270.JPG: 480x640 (no detections), 269.0ms
Speed: 1.1ms preprocess, 269.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTYHLC4xnMoKI0XUfrCmYQ_0.JPG: 480x640 (no detections), 271.0ms
Speed: 1.1ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTYHLC4xnMoKI0XUfrCmYQ_90.JPG: 480x640 (no detections), 267.7ms
Speed: 1.0ms preprocess, 267.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTYHLC4xnMoKI0XUfrCmYQ_180.JPG: 480x640 (no detections), 271.3ms
Speed: 1.2ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTYHLC4xnMoKI0XUfrCmYQ_270.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTYgWixHeshsfYMperDKMA_0.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTYgWixHeshsfYMperDKMA_90.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTYgWixHeshsfYMperDKMA_180.JPG: 480x640 (no detections), 269.3ms
Speed: 1.1ms preprocess, 269.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTYgWixHeshsfYMperDKMA_270.JPG: 480x640 (no detections), 268.2ms
Speed: 1.1ms preprocess, 268.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTc5QrSojRjCC7H9g3OB2g_0.JPG: 480x640 (no detections), 270.5ms
Speed: 1.0ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTc5QrSojRjCC7H9g3OB2g_90.JPG: 480x640 (no detections), 268.4ms
Speed: 1.1ms preprocess, 268.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTc5QrSojRjCC7H9g3OB2g_180.JPG: 480x640 (no detections), 268.8ms
Speed: 1.2ms preprocess, 268.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTc5QrSojRjCC7H9g3OB2g_270.JPG: 480x640 (no detections), 271.5ms
Speed: 1.1ms preprocess, 271.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTcj1tZe6v3MpmHcF0U5LA_0.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTcj1tZe6v3MpmHcF0U5LA_90.JPG: 480x640 (no detections), 267.0ms
Speed: 1.1ms preprocess, 267.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTcj1tZe6v3MpmHcF0U5LA_180.JPG: 480x640 (no detections), 268.2ms
Speed: 1.0ms preprocess, 268.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTcj1tZe6v3MpmHcF0U5LA_270.JPG: 480x640 (no detections), 270.9ms
Speed: 1.1ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTckE5zwpU6xj5nLkk38kg_0.JPG: 480x640 (no detections), 266.9ms
Speed: 1.0ms preprocess, 266.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTckE5zwpU6xj5nLkk38kg_90.JPG: 480x640 1 Waste, 268.4ms
Speed: 1.1ms preprocess, 268.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTckE5zwpU6xj5nLkk38kg_180.JPG: 480x640 (no detections), 273.4ms
Speed: 1.0ms preprocess, 273.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTckE5zwpU6xj5nLkk38kg_270.JPG: 480x640 (no detections), 275.8ms
Speed: 1.0ms preprocess, 275.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTeiN1mlrr0dplzJ1A4qng_0.JPG: 480x640 (no detections), 274.9ms
Speed: 1.1ms preprocess, 274.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTeiN1mlrr0dplzJ1A4qng_90.JPG: 480x640 (no detections), 270.6ms
Speed: 1.0ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTeiN1mlrr0dplzJ1A4qng_180.JPG: 480x640 (no detections), 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTeiN1mlrr0dplzJ1A4qng_270.JPG: 480x640 (no detections), 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTjLiLa754umyw4-qW-Z5g_0.JPG: 480x640 (no detections), 269.1ms
Speed: 1.0ms preprocess, 269.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTjLiLa754umyw4-qW-Z5g_90.JPG: 480x640 (no detections), 273.0ms
Speed: 1.0ms preprocess, 273.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTjLiLa754umyw4-qW-Z5g_180.JPG: 480x640 (no detections), 269.5ms
Speed: 1.1ms preprocess, 269.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTjLiLa754umyw4-qW-Z5g_270.JPG: 480x640 (no detections), 267.3ms
Speed: 0.9ms preprocess, 267.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTnuwllVdkCqCJVlHjNErg_0.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTnuwllVdkCqCJVlHjNErg_90.JPG: 480x640 (no detections), 268.3ms
Speed: 1.0ms preprocess, 268.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTnuwllVdkCqCJVlHjNErg_180.JPG: 480x640 (no detections), 269.3ms
Speed: 1.0ms preprocess, 269.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yTnuwllVdkCqCJVlHjNErg_270.JPG: 480x640 (no detections), 265.5ms
Speed: 1.1ms preprocess, 265.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yU24ORgVHxSmBuatmJVTiA_0.JPG: 480x640 (no detections), 267.2ms
Speed: 1.0ms preprocess, 267.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yU24ORgVHxSmBuatmJVTiA_90.JPG: 480x640 (no detections), 267.8ms
Speed: 1.0ms preprocess, 267.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yU24ORgVHxSmBuatmJVTiA_180.JPG: 480x640 (no detections), 276.7ms
Speed: 1.0ms preprocess, 276.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yU24ORgVHxSmBuatmJVTiA_270.JPG: 480x640 (no detections), 271.1ms

Speed: 1.0ms preprocess, 271.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yU26b8NBs3R0xkq-wFRpyQ_0.JPG: 480x640 (no detections), 270.2ms
Speed: 1.0ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yU26b8NBs3R0xkq-wFRpyQ_90.JPG: 480x640 (no detections), 269.1ms
Speed: 1.0ms preprocess, 269.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yU26b8NBs3R0xkq-wFRpyQ_180.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yU26b8NBs3R0xkq-wFRpyQ_270.JPG: 480x640 (no detections), 269.5ms
Speed: 1.1ms preprocess, 269.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yU5gGeW80No7KAn4NsYxnQ_0.JPG: 480x640 (no detections), 272.5ms
Speed: 1.1ms preprocess, 272.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yU5gGeW80No7KAn4NsYxnQ_90.JPG: 480x640 (no detections), 268.3ms
Speed: 1.1ms preprocess, 268.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yU5gGeW80No7KAn4NsYxnQ_180.JPG: 480x640 (no detections), 269.1ms
Speed: 1.1ms preprocess, 269.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yU5gGeW80No7KAn4NsYxnQ_270.JPG: 480x640 (no detections), 272.8ms
Speed: 1.0ms preprocess, 272.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yU75tyBuvuh9oOu5pUHgMw_0.JPG: 480x640 (no detections), 269.4ms
Speed: 1.0ms preprocess, 269.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yU75tyBuvuh9oOu5pUHgMw_90.JPG: 480x640 (no detections), 268.8ms
Speed: 1.1ms preprocess, 268.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yU75tyBuvuh9oOu5pUHgMw_180.JPG: 480x640 (no detections), 270.4ms
Speed: 1.1ms preprocess, 270.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yU75tyBuvuh9oOu5pUHgMw_270.JPG: 480x640 (no detections), 268.4ms
Speed: 1.0ms preprocess, 268.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUAQioN2s3UabgIvLXvijA_0.JPG: 480x640 1 Waste, 270.0ms
Speed: 1.0ms preprocess, 270.0ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUAQioN2s3UabgIvLXvijA_90.JPG: 480x640 1 Waste, 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUAQioN2s3UabgIvLXvijA_180.JPG: 480x640 (no detections), 269.2ms
Speed: 1.1ms preprocess, 269.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUAQioN2s3UabgIvLXvijA_270.JPG: 480x640 (no detections), 270.1ms
Speed: 1.0ms preprocess, 270.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUAlrzLELATCCOImXiVvEQ_0.JPG: 480x640 (no detections), 270.4ms
Speed: 1.1ms preprocess, 270.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUAlrzLELATCCOImXiVvEQ_90.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUAlrzLELATCCOImXiVvEQ_180.JPG: 480x640 (no detections), 270.3ms
Speed: 1.1ms preprocess, 270.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUAlrzLELATCCOImXiVvEQ_270.JPG: 480x640 (no detections), 267.6ms
Speed: 1.0ms preprocess, 267.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUD9TAASNEVZdFvXhSU_5A_0.JPG: 480x640 (no detections), 265.3ms
Speed: 1.1ms preprocess, 265.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUD9TAASNEVZdFvXhSU_5A_90.JPG: 480x640 (no detections), 268.2ms
Speed: 1.0ms preprocess, 268.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUD9TAASNEVZdFvXhSU_5A_180.JPG: 480x640 (no detections), 270.1ms
Speed: 1.2ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUD9TAASNEVZdFvXhSU_5A_270.JPG: 480x640 (no detections), 266.2ms
Speed: 1.0ms preprocess, 266.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUELolo6VRcp3fVuGJUbZA_0.JPG: 480x640 (no detections), 262.5ms
Speed: 1.1ms preprocess, 262.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUELolo6VRcp3fVuGJUbZA_90.JPG: 480x640 (no detections), 269.1ms
Speed: 1.0ms preprocess, 269.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUELolo6VRcp3fVuGJUbZA_180.JPG: 480x640 (no detections), 271.2ms
Speed: 1.0ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUELolo6VRcp3fVuGJUbZA_270.JPG: 480x640 (no detections), 277.6ms
Speed: 1.1ms preprocess, 277.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUEXrnhkW_DatdwICgwlew_0.JPG: 480x640 (no detections), 269.1ms
Speed: 1.1ms preprocess, 269.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUEXrnhkW_DatdwICgwlew_90.JPG: 480x640 (no detections), 276.0ms
Speed: 1.0ms preprocess, 276.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUEXrnhkW_DatdwICgwlew_180.JPG: 480x640 (no detections), 270.3ms
Speed: 1.2ms preprocess, 270.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUEXrnhkW_DatdwICgwlew_270.JPG: 480x640 (no detections), 268.9ms
Speed: 1.0ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUEkB76sHy76hmN9pTs20w_0.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUEkB76sHy76hmN9pTs20w_90.JPG: 480x640 (no detections), 273.5ms
Speed: 1.0ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUEkB76sHy76hmN9pTs20w_180.JPG: 480x640 (no detections), 265.9ms
Speed: 1.1ms preprocess, 265.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUEkB76sHy76hmN9pTs20w_270.JPG: 480x640 1 Waste, 271.0ms
Speed: 1.1ms preprocess, 271.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUGgGw__6u5V_BK6Ox6Ofw_0.JPG: 480x640 (no detections), 266.8ms
Speed: 1.1ms preprocess, 266.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUGgGw__6u5V_BK6Ox6Ofw_90.JPG: 480x640 (no detections), 267.2ms
Speed: 1.0ms preprocess, 267.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUGgGw__6u5V_BK6Ox6Ofw_180.JPG: 480x640 (no detections), 266.7ms
Speed: 1.0ms preprocess, 266.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUGgGw__6u5V_BK6Ox6Ofw_270.JPG: 480x640 (no detections), 265.1ms
Speed: 1.0ms preprocess, 265.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUGhNy62JRdx_al8CxqwIg_0.JPG: 480x640 (no detections), 268.3ms
Speed: 1.1ms preprocess, 268.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUGhNy62JRdx_al8CxqwIg_90.JPG: 480x640 (no detections), 267.9ms
Speed: 1.0ms preprocess, 267.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUGhNy62JRdx_al8CxqwIg_180.JPG: 480x640 (no detections), 272.8ms
Speed: 1.0ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUGhNy62JRdx_al8CxqwIg_270.JPG: 480x640 (no detections), 266.6ms
Speed: 1.1ms preprocess, 266.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUQkt-2jMzJMB5TvqbwMfg_0.JPG: 480x640 (no detections), 270.2ms
Speed: 1.0ms preprocess, 270.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUQkt-2jMzJMB5TvqbwMfg_90.JPG: 480x640 (no detections), 268.9ms
Speed: 1.0ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUQkt-2jMzJMB5TvqbwMfg_180.JPG: 480x640 (no detections), 271.5ms
Speed: 1.0ms preprocess, 271.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUQkt-2jMzJMB5TvqbwMfg_270.JPG: 480x640 (no detections), 267.7ms
Speed: 1.1ms preprocess, 267.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUSH3e-nih7NpbDyJJv0Pg_0.JPG: 480x640 (no detections), 268.5ms
Speed: 1.1ms preprocess, 268.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUSH3e-nih7NpbDyJJv0Pg_90.JPG: 480x640 (no detections), 268.5ms
Speed: 1.0ms preprocess, 268.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUSH3e-nih7NpbDyJJv0Pg_180.JPG: 480x640 (no detections), 271.6ms
Speed: 1.0ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUSH3e-nih7NpbDyJJv0Pg_270.JPG: 480x640 (no detections), 268.9ms
Speed: 1.1ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUUsEfPVASuZ6H3Ah575tA_0.JPG: 480x640 (no detections), 270.2ms
Speed: 1.0ms preprocess, 270.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUUsEfPVASuZ6H3Ah575tA_90.JPG: 480x640 (no detections), 267.3ms
Speed: 1.1ms preprocess, 267.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUUsEfPVASuZ6H3Ah575tA_180.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUUsEfPVASuZ6H3Ah575tA_270.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUUzi4u53QiwknxhBqYw7w_0.JPG: 480x640 (no detections), 267.2ms
Speed: 1.0ms preprocess, 267.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUUzi4u53QiwknxhBqYw7w_90.JPG: 480x640 (no detections), 278.3ms
Speed: 1.2ms preprocess, 278.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUUzi4u53QiwknxhBqYw7w_180.JPG: 480x640 (no detections), 269.4ms
Speed: 1.1ms preprocess, 269.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUUzi4u53QiwknxhBqYw7w_270.JPG: 480x640 (no detections), 267.9ms
Speed: 1.3ms preprocess, 267.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUVhtIZxzVUxXe3yqQe-lw_0.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUVhtIZxzVUxXe3yqQe-lw_90.JPG: 480x640 (no detections), 276.1ms
Speed: 1.1ms preprocess, 276.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUVhtIZxzVUxXe3yqQe-lw_180.JPG: 480x640 (no detections), 269.4ms
Speed: 1.0ms preprocess, 269.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUVhtIZxzVUxXe3yqQe-lw_270.JPG: 480x640 (no detections), 269.6ms
Speed: 1.0ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUVlxHai8wsUMLWQp_vIGQ_0.JPG: 480x640 (no detections), 271.0ms
Speed: 1.0ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUVlxHai8wsUMLWQp_vIGQ_90.JPG: 480x640 (no detections), 272.0ms
Speed: 1.0ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUVlxHai8wsUMLWQp_vIGQ_180.JPG: 480x640 (no detections), 270.7ms

Speed: 1.0ms preprocess, 270.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUVlxHai8wsUMLWQp_vIGQ_270.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUWNr5o9aAno2dSRSDOgow_0.JPG: 480x640 (no detections), 269.4ms
Speed: 1.1ms preprocess, 269.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUWNr5o9aAno2dSRSDOgow_90.JPG: 480x640 (no detections), 272.5ms
Speed: 1.0ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUWNr5o9aAno2dSRSDOgow_180.JPG: 480x640 2 Wastes, 266.7ms
Speed: 1.1ms preprocess, 266.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUWNr5o9aAno2dSRSDOgow_270.JPG: 480x640 (no detections), 275.5ms
Speed: 1.0ms preprocess, 275.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUb3hEdqMnA_TCAetMX_9g_0.JPG: 480x640 (no detections), 267.5ms
Speed: 1.1ms preprocess, 267.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUb3hEdqMnA_TCAetMX_9g_90.JPG: 480x640 (no detections), 269.6ms
Speed: 1.1ms preprocess, 269.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUb3hEdqMnA_TCAetMX_9g_180.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUb3hEdqMnA_TCAetMX_9g_270.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUdOCJBIK77jKjdXuZmYsw_0.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUdOCJBIK77jKjdXuZmYsw_90.JPG: 480x640 (no detections), 267.5ms
Speed: 1.1ms preprocess, 267.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUdOCJBIK77jKjdXuZmYsw_180.JPG: 480x640 (no detections), 264.7ms
Speed: 1.0ms preprocess, 264.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUdOCJBIK77jKjdXuZmYsw_270.JPG: 480x640 (no detections), 265.9ms
Speed: 1.1ms preprocess, 265.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUg8hWf74Px1W0Yo1IQ28w_0.JPG: 480x640 (no detections), 271.0ms
Speed: 1.1ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUg8hWf74Px1W0Yo1IQ28w_90.JPG: 480x640 (no detections), 268.0ms
Speed: 1.2ms preprocess, 268.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUg8hWf74Px1W0Yo1IQ28w_180.JPG: 480x640 (no detections), 268.8ms
Speed: 1.0ms preprocess, 268.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUg8hWf74Px1W0Yo1IQ28w_270.JPG: 480x640 (no detections), 267.6ms
Speed: 1.1ms preprocess, 267.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUhzWR3aGhO_ZZYLbBqXRg_0.JPG: 480x640 (no detections), 268.2ms
Speed: 1.0ms preprocess, 268.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUhzWR3aGhO_ZZYLbBqXRg_90.JPG: 480x640 (no detections), 271.4ms
Speed: 1.0ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUhzWR3aGhO_ZZYLbBqXRg_180.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUhzWR3aGhO_ZZYLbBqXRg_270.JPG: 480x640 (no detections), 268.1ms
Speed: 1.0ms preprocess, 268.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUkQu7F3_34ZdBvh_UzWTg_0.JPG: 480x640 (no detections), 267.6ms
Speed: 1.1ms preprocess, 267.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUkQu7F3_34ZdBvh_UzWTg_90.JPG: 480x640 (no detections), 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUkQu7F3_34ZdBvh_UzWTg_180.JPG: 480x640 (no detections), 268.8ms
Speed: 1.1ms preprocess, 268.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUkQu7F3_34ZdBvh_UzWTg_270.JPG: 480x640 (no detections), 268.0ms
Speed: 1.1ms preprocess, 268.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUl5IaK-Hac9cdc2zJiVEA_0.JPG: 480x640 (no detections), 269.9ms
Speed: 1.0ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUl5IaK-Hac9cdc2zJiVEA_90.JPG: 480x640 (no detections), 268.0ms
Speed: 1.1ms preprocess, 268.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUl5IaK-Hac9cdc2zJiVEA_180.JPG: 480x640 (no detections), 270.3ms
Speed: 1.1ms preprocess, 270.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUl5IaK-Hac9cdc2zJiVEA_270.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUnvkAITVqN5x0lRhF5-mw_0.JPG: 480x640 2 Wastes, 269.6ms
Speed: 1.0ms preprocess, 269.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUnvkAITVqN5x0lRhF5-mw_90.JPG: 480x640 1 Waste, 269.0ms
Speed: 1.1ms preprocess, 269.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUnvkAITVqN5x0lRhF5-mw_180.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUnvkAITVqN5x0lRhF5-mw_270.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUppRmgiiA1aHYl3Jg6jDA_0.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUppRmgiiA1aHYl3Jg6jDA_90.JPG: 480x640 (no detections), 269.3ms
Speed: 1.1ms preprocess, 269.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUppRmgiiA1aHYl3Jg6jDA_180.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUppRmgiiA1aHYl3Jg6jDA_270.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUsjU42m_s-0CviWNoUMZQ_0.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUsjU42m_s-0CviWNoUMZQ_90.JPG: 480x640 (no detections), 272.9ms
Speed: 1.2ms preprocess, 272.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUsjU42m_s-0CviWNoUMZQ_180.JPG: 480x640 (no detections), 267.6ms
Speed: 1.0ms preprocess, 267.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUsjU42m_s-0CviWNoUMZQ_270.JPG: 480x640 (no detections), 269.2ms
Speed: 1.0ms preprocess, 269.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUsuLyX-e2gkRgiaDEFiUw_0.JPG: 480x640 (no detections), 269.0ms
Speed: 1.0ms preprocess, 269.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUsuLyX-e2gkRgiaDEFiUw_90.JPG: 480x640 (no detections), 267.6ms
Speed: 1.0ms preprocess, 267.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUsuLyX-e2gkRgiaDEFiUw_180.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yUsuLyX-e2gkRgiaDEFiUw_270.JPG: 480x640 (no detections), 271.2ms
Speed: 1.0ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yV-TDQzGHX1LzAH1mxZWYA_0.JPG: 480x640 (no detections), 269.1ms
Speed: 1.0ms preprocess, 269.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yV-TDQzGHX1LzAH1mxZWYA_90.JPG: 480x640 (no detections), 273.8ms
Speed: 1.0ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yV-TDQzGHX1LzAH1mxZWYA_180.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yV-TDQzGHX1LzAH1mxZWYA_270.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yV-cE9KUa7Hvz--0pSRFiw_0.JPG: 480x640 (no detections), 267.3ms
Speed: 1.7ms preprocess, 267.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yV-cE9KUa7Hvz--0pSRFiw_90.JPG: 480x640 (no detections), 269.9ms
Speed: 1.2ms preprocess, 269.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yV-cE9KUa7Hvz--0pSRFiw_180.JPG: 480x640 (no detections), 269.7ms
Speed: 1.2ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yV-cE9KUa7Hvz--0pSRFiw_270.JPG: 480x640 (no detections), 272.2ms
Speed: 1.2ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yV7T8SGAZ-QHC3KYXomgKw_0.JPG: 480x640 (no detections), 267.0ms
Speed: 1.1ms preprocess, 267.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yV7T8SGAZ-QHC3KYXomgKw_90.JPG: 480x640 (no detections), 269.3ms
Speed: 1.1ms preprocess, 269.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yV7T8SGAZ-QHC3KYXomgKw_180.JPG: 480x640 (no detections), 269.4ms
Speed: 1.0ms preprocess, 269.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yV7T8SGAZ-QHC3KYXomgKw_270.JPG: 480x640 (no detections), 269.4ms
Speed: 1.1ms preprocess, 269.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVBEiD8cNS8U3rjBP2Uo7Q_0.JPG: 480x640 (no detections), 267.8ms
Speed: 1.0ms preprocess, 267.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVBEiD8cNS8U3rjBP2Uo7Q_90.JPG: 480x640 (no detections), 269.3ms
Speed: 1.2ms preprocess, 269.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVBEiD8cNS8U3rjBP2Uo7Q_180.JPG: 480x640 (no detections), 270.2ms
Speed: 1.0ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVBEiD8cNS8U3rjBP2Uo7Q_270.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVFuj6XHq-mVw8jPouQkvw_0.JPG: 480x640 (no detections), 270.9ms
Speed: 1.0ms preprocess, 270.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVFuj6XHq-mVw8jPouQkvw_90.JPG: 480x640 (no detections), 266.0ms
Speed: 1.0ms preprocess, 266.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVFuj6XHq-mVw8jPouQkvw_180.JPG: 480x640 (no detections), 274.9ms
Speed: 1.1ms preprocess, 274.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVFuj6XHq-mVw8jPouQkvw_270.JPG: 480x640 (no detections), 270.1ms
Speed: 1.2ms preprocess, 270.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVK_ZXMtgP86ih6y0r-XMA_0.JPG: 480x640 1 Waste, 268.9ms
Speed: 1.0ms preprocess, 268.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVK_ZXMtgP86ih6y0r-XMA_90.JPG: 480x640 (no detections), 271.6ms

Speed: 1.1ms preprocess, 271.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVK_ZXMtgP86ih6y0r-XMA_180.JPG: 480x640 (no detections), 269.8ms
Speed: 1.1ms preprocess, 269.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVK_ZXMtgP86ih6y0r-XMA_270.JPG: 480x640 (no detections), 268.1ms
Speed: 1.1ms preprocess, 268.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVLIY-rygRWGwK1ncpM1Hw_0.JPG: 480x640 (no detections), 266.0ms
Speed: 1.0ms preprocess, 266.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVLIY-rygRWGwK1ncpM1Hw_90.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVLIY-rygRWGwK1ncpM1Hw_180.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVLIY-rygRWGwK1ncpM1Hw_270.JPG: 480x640 1 Waste, 264.5ms
Speed: 1.0ms preprocess, 264.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVMuEOVtFhFm8x0DM27kJA_0.JPG: 480x640 (no detections), 268.6ms
Speed: 1.0ms preprocess, 268.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVMuEOVtFhFm8x0DM27kJA_90.JPG: 480x640 (no detections), 269.8ms
Speed: 1.1ms preprocess, 269.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVMuEOVtFhFm8x0DM27kJA_180.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVMuEOVtFhFm8x0DM27kJA_270.JPG: 480x640 (no detections), 269.7ms
Speed: 1.2ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVNpO66mK43VdX0OWHx8cA_0.JPG: 480x640 (no detections), 270.7ms
Speed: 1.0ms preprocess, 270.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVNpO66mK43VdX0OWHx8cA_90.JPG: 480x640 (no detections), 273.9ms
Speed: 1.1ms preprocess, 273.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVNpO66mK43VdX0OWHx8cA_180.JPG: 480x640 (no detections), 269.2ms
Speed: 1.0ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVNpO66mK43VdX0OWHx8cA_270.JPG: 480x640 (no detections), 266.7ms
Speed: 1.0ms preprocess, 266.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVPj-yzz6IHY4M2hPlojFw_0.JPG: 480x640 (no detections), 272.1ms
Speed: 1.1ms preprocess, 272.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVPj-yzz6IHY4M2hPlojFw_90.JPG: 480x640 (no detections), 270.4ms
Speed: 1.1ms preprocess, 270.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVPj-yzz6IHY4M2hPlojFw_180.JPG: 480x640 (no detections), 266.2ms
Speed: 1.1ms preprocess, 266.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVPj-yzz6IHY4M2hPlojFw_270.JPG: 480x640 (no detections), 268.0ms
Speed: 1.1ms preprocess, 268.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVSsE3OJjkv-IGBs8j2HXg_0.JPG: 480x640 (no detections), 270.1ms
Speed: 1.0ms preprocess, 270.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVSsE3OJjkv-IGBs8j2HXg_90.JPG: 480x640 (no detections), 269.3ms
Speed: 1.1ms preprocess, 269.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVSsE3OJjkv-IGBs8j2HXg_180.JPG: 480x640 (no detections), 267.9ms
Speed: 1.0ms preprocess, 267.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVSsE3OJjkv-IGBs8j2HXg_270.JPG: 480x640 (no detections), 268.5ms
Speed: 1.1ms preprocess, 268.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVTdwGR-3GyO5SvbzkQxnw_0.JPG: 480x640 (no detections), 268.1ms
Speed: 1.1ms preprocess, 268.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVTdwGR-3GyO5SvbzkQxnw_90.JPG: 480x640 (no detections), 273.1ms
Speed: 1.1ms preprocess, 273.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVTdwGR-3GyO5SvbzkQxnw_180.JPG: 480x640 (no detections), 268.6ms
Speed: 1.1ms preprocess, 268.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVTdwGR-3GyO5SvbzkQxnw_270.JPG: 480x640 (no detections), 276.4ms
Speed: 1.1ms preprocess, 276.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVUZ1T9EPk43Lrt20V1eMA_0.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVUZ1T9EPk43Lrt20V1eMA_90.JPG: 480x640 1 Waste, 269.6ms
Speed: 1.0ms preprocess, 269.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVUZ1T9EPk43Lrt20V1eMA_180.JPG: 480x640 (no detections), 269.6ms
Speed: 1.1ms preprocess, 269.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVUZ1T9EPk43Lrt20V1eMA_270.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yV_tfs_UnEVauf2QPOwpow_0.JPG: 480x640 1 Waste, 286.3ms
Speed: 1.1ms preprocess, 286.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yV_tfs_UnEVauf2QPOwpow_90.JPG: 480x640 (no detections), 270.5ms
Speed: 1.1ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yV_tfs_UnEVauf2QPOwpow_180.JPG: 480x640 (no detections), 269.2ms
Speed: 1.0ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yV_tfs_UnEVauf2QPOwpow_270.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVaU7cBsnpIxdZHo51OLpg_0.JPG: 480x640 (no detections), 272.6ms
Speed: 1.0ms preprocess, 272.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVaU7cBsnpIxdZHo51OLpg_90.JPG: 480x640 (no detections), 269.1ms
Speed: 1.0ms preprocess, 269.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVaU7cBsnpIxdZHo51OLpg_180.JPG: 480x640 (no detections), 266.3ms
Speed: 1.0ms preprocess, 266.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVaU7cBsnpIxdZHo51OLpg_270.JPG: 480x640 (no detections), 269.5ms
Speed: 1.1ms preprocess, 269.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVjkDa7pchzkZ3nC6ZumwQ_0.JPG: 480x640 (no detections), 274.2ms
Speed: 1.0ms preprocess, 274.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVjkDa7pchzkZ3nC6ZumwQ_90.JPG: 480x640 (no detections), 267.2ms
Speed: 1.2ms preprocess, 267.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVjkDa7pchzkZ3nC6ZumwQ_180.JPG: 480x640 (no detections), 273.2ms
Speed: 1.0ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVjkDa7pchzkZ3nC6ZumwQ_270.JPG: 480x640 (no detections), 267.1ms
Speed: 1.0ms preprocess, 267.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVomEoJj5M8zavmH3Lq5ig_0.JPG: 480x640 (no detections), 271.9ms
Speed: 1.2ms preprocess, 271.9ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVomEoJj5M8zavmH3Lq5ig_90.JPG: 480x640 (no detections), 363.6ms
Speed: 1.1ms preprocess, 363.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVomEoJj5M8zavmH3Lq5ig_180.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVomEoJj5M8zavmH3Lq5ig_270.JPG: 480x640 (no detections), 264.9ms
Speed: 1.1ms preprocess, 264.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVuRriZPXObhI5GQdEes5Q_0.JPG: 480x640 (no detections), 266.2ms
Speed: 1.2ms preprocess, 266.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVuRriZPXObhI5GQdEes5Q_90.JPG: 480x640 1 Waste, 273.3ms
Speed: 1.2ms preprocess, 273.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVuRriZPXObhI5GQdEes5Q_180.JPG: 480x640 (no detections), 270.4ms
Speed: 1.1ms preprocess, 270.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVuRriZPXObhI5GQdEes5Q_270.JPG: 480x640 (no detections), 270.3ms
Speed: 1.0ms preprocess, 270.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVv08ZZlU0EPyPa0EJ6_GA_0.JPG: 480x640 (no detections), 266.0ms
Speed: 1.0ms preprocess, 266.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVv08ZZlU0EPyPa0EJ6_GA_90.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVv08ZZlU0EPyPa0EJ6_GA_180.JPG: 480x640 (no detections), 268.9ms
Speed: 1.2ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVv08ZZlU0EPyPa0EJ6_GA_270.JPG: 480x640 (no detections), 269.4ms
Speed: 1.1ms preprocess, 269.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVv_J9tuYZu34ZmKhLckXA_0.JPG: 480x640 (no detections), 272.9ms
Speed: 1.0ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVv_J9tuYZu34ZmKhLckXA_90.JPG: 480x640 (no detections), 270.8ms
Speed: 1.0ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVv_J9tuYZu34ZmKhLckXA_180.JPG: 480x640 (no detections), 268.7ms
Speed: 1.0ms preprocess, 268.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVv_J9tuYZu34ZmKhLckXA_270.JPG: 480x640 (no detections), 270.5ms
Speed: 1.0ms preprocess, 270.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVx46i1M7CTPJ0IdpiIuEA_0.JPG: 480x640 (no detections), 271.0ms
Speed: 1.2ms preprocess, 271.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVx46i1M7CTPJ0IdpiIuEA_90.JPG: 480x640 (no detections), 271.9ms
Speed: 1.0ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVx46i1M7CTPJ0IdpiIuEA_180.JPG: 480x640 (no detections), 273.2ms
Speed: 1.0ms preprocess, 273.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVx46i1M7CTPJ0IdpiIuEA_270.JPG: 480x640 (no detections), 267.5ms
Speed: 1.0ms preprocess, 267.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVyu4AlZEw9uEMLmEt6DRQ_0.JPG: 480x640 (no detections), 268.7ms
Speed: 1.1ms preprocess, 268.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVyu4AlZEw9uEMLmEt6DRQ_90.JPG: 480x640 (no detections), 266.1ms
Speed: 1.1ms preprocess, 266.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVyu4AlZEw9uEMLmEt6DRQ_180.JPG: 480x640 (no detections), 267.9ms
Speed: 1.0ms preprocess, 267.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yVyu4AlZEw9uEMLmEt6DRQ_270.JPG: 480x640 (no detections), 270.4ms
Speed: 1.1ms preprocess, 270.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yW08GP3kg0PljTEQf3-N3A_0.JPG: 480x640 (no detections), 275.0ms

Speed: 1.1ms preprocess, 275.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yW08GP3kg0PljTEQf3-N3A_90.JPG: 480x640 (no detections), 269.9ms
Speed: 1.0ms preprocess, 269.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yW08GP3kg0PljTEQf3-N3A_180.JPG: 480x640 (no detections), 269.8ms
Speed: 1.0ms preprocess, 269.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yW08GP3kg0PljTEQf3-N3A_270.JPG: 480x640 (no detections), 273.1ms
Speed: 1.0ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yW65cxV06qGsQS1FOW3N6A_0.JPG: 480x640 (no detections), 268.8ms
Speed: 1.0ms preprocess, 268.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yW65cxV06qGsQS1FOW3N6A_90.JPG: 480x640 1 Waste, 269.6ms
Speed: 1.0ms preprocess, 269.6ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yW65cxV06qGsQS1FOW3N6A_180.JPG: 480x640 (no detections), 270.2ms
Speed: 1.0ms preprocess, 270.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yW65cxV06qGsQS1FOW3N6A_270.JPG: 480x640 (no detections), 265.1ms
Speed: 1.1ms preprocess, 265.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yW7t6X1fgDYL48o5nwj9ow_0.JPG: 480x640 1 Waste, 270.4ms
Speed: 1.1ms preprocess, 270.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yW7t6X1fgDYL48o5nwj9ow_90.JPG: 480x640 (no detections), 269.8ms
Speed: 1.1ms preprocess, 269.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yW7t6X1fgDYL48o5nwj9ow_180.JPG: 480x640 (no detections), 267.8ms
Speed: 1.1ms preprocess, 267.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yW7t6X1fgDYL48o5nwj9ow_270.JPG: 480x640 1 Waste, 266.9ms
Speed: 1.1ms preprocess, 266.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yW8vQujvryqPLdW8Y2cYEQ_0.JPG: 480x640 1 Waste, 270.4ms
Speed: 1.0ms preprocess, 270.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yW8vQujvryqPLdW8Y2cYEQ_90.JPG: 480x640 (no detections), 269.1ms
Speed: 1.0ms preprocess, 269.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yW8vQujvryqPLdW8Y2cYEQ_180.JPG: 480x640 (no detections), 264.2ms
Speed: 1.1ms preprocess, 264.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yW8vQujvryqPLdW8Y2cYEQ_270.JPG: 480x640 (no detections), 266.6ms
Speed: 1.0ms preprocess, 266.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yW9Zjy4uE32vPxkERviOtg_0.JPG: 480x640 (no detections), 265.7ms
Speed: 1.0ms preprocess, 265.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yW9Zjy4uE32vPxkERviOtg_90.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yW9Zjy4uE32vPxkERviOtg_180.JPG: 480x640 (no detections), 267.2ms
Speed: 1.1ms preprocess, 267.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yW9Zjy4uE32vPxkERviOtg_270.JPG: 480x640 (no detections), 269.7ms
Speed: 1.0ms preprocess, 269.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWAPwfEr9yxE1r-czxXXcw_0.JPG: 480x640 (no detections), 267.6ms
Speed: 1.1ms preprocess, 267.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWAPwfEr9yxE1r-czxXXcw_90.JPG: 480x640 (no detections), 268.4ms
Speed: 1.1ms preprocess, 268.4ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWAPwfEr9yxE1r-czxXXcw_180.JPG: 480x640 (no detections), 267.8ms
Speed: 1.0ms preprocess, 267.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWAPwfEr9yxE1r-czxXXcw_270.JPG: 480x640 (no detections), 271.0ms
Speed: 1.0ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWAaVfR3b97XFCxx6WYKrQ_0.JPG: 480x640 (no detections), 268.5ms
Speed: 1.2ms preprocess, 268.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWAaVfR3b97XFCxx6WYKrQ_90.JPG: 480x640 (no detections), 271.6ms
Speed: 1.0ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWAaVfR3b97XFCxx6WYKrQ_180.JPG: 480x640 (no detections), 268.2ms
Speed: 1.1ms preprocess, 268.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWAaVfR3b97XFCxx6WYKrQ_270.JPG: 480x640 (no detections), 274.4ms
Speed: 1.0ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWCK4OXbfdIILGrEG-gOHA_0.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWCK4OXbfdIILGrEG-gOHA_90.JPG: 480x640 (no detections), 271.6ms
Speed: 1.0ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWCK4OXbfdIILGrEG-gOHA_180.JPG: 480x640 (no detections), 269.2ms
Speed: 1.0ms preprocess, 269.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWCK4OXbfdIILGrEG-gOHA_270.JPG: 480x640 (no detections), 261.5ms
Speed: 1.0ms preprocess, 261.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWILI8b5LLVKZDXrejfREA_0.JPG: 480x640 (no detections), 272.1ms
Speed: 1.0ms preprocess, 272.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWILI8b5LLVKZDXrejfREA_90.JPG: 480x640 (no detections), 269.9ms
Speed: 1.2ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWILI8b5LLVKZDXrejfREA_180.JPG: 480x640 (no detections), 267.5ms
Speed: 1.1ms preprocess, 267.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWILI8b5LLVKZDXrejfREA_270.JPG: 480x640 (no detections), 267.6ms
Speed: 1.0ms preprocess, 267.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWIlQzwaEOmpmRcRaVhwnQ_0.JPG: 480x640 (no detections), 269.0ms
Speed: 1.0ms preprocess, 269.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWIlQzwaEOmpmRcRaVhwnQ_90.JPG: 480x640 (no detections), 269.8ms
Speed: 1.0ms preprocess, 269.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWIlQzwaEOmpmRcRaVhwnQ_180.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWIlQzwaEOmpmRcRaVhwnQ_270.JPG: 480x640 (no detections), 263.3ms
Speed: 1.1ms preprocess, 263.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWJUhDlymzCIrIrFTZ2tUw_0.JPG: 480x640 (no detections), 269.3ms
Speed: 1.0ms preprocess, 269.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWJUhDlymzCIrIrFTZ2tUw_90.JPG: 480x640 (no detections), 270.1ms
Speed: 1.0ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWJUhDlymzCIrIrFTZ2tUw_180.JPG: 480x640 (no detections), 268.1ms
Speed: 1.0ms preprocess, 268.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWJUhDlymzCIrIrFTZ2tUw_270.JPG: 480x640 (no detections), 274.7ms
Speed: 1.1ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWKvKj2SVpyO50jCMRDuhg_0.JPG: 480x640 (no detections), 270.1ms
Speed: 1.0ms preprocess, 270.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWKvKj2SVpyO50jCMRDuhg_90.JPG: 480x640 (no detections), 269.0ms
Speed: 1.2ms preprocess, 269.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWKvKj2SVpyO50jCMRDuhg_180.JPG: 480x640 (no detections), 264.2ms
Speed: 1.0ms preprocess, 264.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWKvKj2SVpyO50jCMRDuhg_270.JPG: 480x640 (no detections), 276.6ms
Speed: 1.0ms preprocess, 276.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWMV3vaWrjPN-2XqMiQFRA_0.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWMV3vaWrjPN-2XqMiQFRA_90.JPG: 480x640 (no detections), 268.7ms
Speed: 1.1ms preprocess, 268.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWMV3vaWrjPN-2XqMiQFRA_180.JPG: 480x640 (no detections), 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWMV3vaWrjPN-2XqMiQFRA_270.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWOJPpdJCKJ9XDaEyS6isg_0.JPG: 480x640 (no detections), 267.3ms
Speed: 1.1ms preprocess, 267.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWOJPpdJCKJ9XDaEyS6isg_90.JPG: 480x640 (no detections), 268.7ms
Speed: 1.1ms preprocess, 268.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWOJPpdJCKJ9XDaEyS6isg_180.JPG: 480x640 (no detections), 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWOJPpdJCKJ9XDaEyS6isg_270.JPG: 480x640 (no detections), 268.9ms
Speed: 1.0ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWPmx7GK7sm8SYJx65gyMg_0.JPG: 480x640 (no detections), 269.8ms
Speed: 1.1ms preprocess, 269.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWPmx7GK7sm8SYJx65gyMg_90.JPG: 480x640 (no detections), 272.0ms
Speed: 1.2ms preprocess, 272.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWPmx7GK7sm8SYJx65gyMg_180.JPG: 480x640 (no detections), 267.6ms
Speed: 1.0ms preprocess, 267.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWPmx7GK7sm8SYJx65gyMg_270.JPG: 480x640 (no detections), 265.3ms
Speed: 1.1ms preprocess, 265.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWWrr5Za2UUUHzoI3yTgzQ_0.JPG: 480x640 (no detections), 270.1ms
Speed: 1.0ms preprocess, 270.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWWrr5Za2UUUHzoI3yTgzQ_90.JPG: 480x640 (no detections), 271.2ms
Speed: 1.0ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWWrr5Za2UUUHzoI3yTgzQ_180.JPG: 480x640 (no detections), 270.5ms
Speed: 1.2ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWWrr5Za2UUUHzoI3yTgzQ_270.JPG: 480x640 (no detections), 268.6ms
Speed: 1.1ms preprocess, 268.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWc4aPRb8G6Ter-M1M0QXw_0.JPG: 480x640 (no detections), 266.5ms
Speed: 1.0ms preprocess, 266.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWc4aPRb8G6Ter-M1M0QXw_90.JPG: 480x640 (no detections), 274.5ms
Speed: 1.2ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWc4aPRb8G6Ter-M1M0QXw_180.JPG: 480x640 (no detections), 268.7ms
Speed: 1.1ms preprocess, 268.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWc4aPRb8G6Ter-M1M0QXw_270.JPG: 480x640 (no detections), 268.9ms

Speed: 1.0ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWcQRo9lKPCTRkMVUmTT9Q_0.JPG: 480x640 (no detections), 266.8ms
Speed: 1.0ms preprocess, 266.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWcQRo9lKPCTRkMVUmTT9Q_90.JPG: 480x640 (no detections), 270.4ms
Speed: 1.1ms preprocess, 270.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWcQRo9lKPCTRkMVUmTT9Q_180.JPG: 480x640 (no detections), 267.5ms
Speed: 1.0ms preprocess, 267.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWcQRo9lKPCTRkMVUmTT9Q_270.JPG: 480x640 (no detections), 268.1ms
Speed: 1.1ms preprocess, 268.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWjTRbRLmj9oHo7p78paag_0.JPG: 480x640 (no detections), 268.7ms
Speed: 1.1ms preprocess, 268.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWjTRbRLmj9oHo7p78paag_90.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWjTRbRLmj9oHo7p78paag_180.JPG: 480x640 (no detections), 269.4ms
Speed: 1.0ms preprocess, 269.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWjTRbRLmj9oHo7p78paag_270.JPG: 480x640 (no detections), 270.4ms
Speed: 1.1ms preprocess, 270.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWnjwpMJvcULr2Fl70-vjg_0.JPG: 480x640 (no detections), 273.8ms
Speed: 1.0ms preprocess, 273.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWnjwpMJvcULr2Fl70-vjg_90.JPG: 480x640 (no detections), 271.0ms
Speed: 1.0ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWnjwpMJvcULr2Fl70-vjg_180.JPG: 480x640 (no detections), 267.7ms
Speed: 1.1ms preprocess, 267.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWnjwpMJvcULr2Fl70-vjg_270.JPG: 480x640 (no detections), 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWqTXuJS_A2kk2MZlnejpg_0.JPG: 480x640 (no detections), 268.0ms
Speed: 1.0ms preprocess, 268.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWqTXuJS_A2kk2MZlnejpg_90.JPG: 480x640 (no detections), 267.6ms
Speed: 1.1ms preprocess, 267.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWqTXuJS_A2kk2MZlnejpg_180.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWqTXuJS_A2kk2MZlnejpg_270.JPG: 480x640 (no detections), 268.4ms
Speed: 1.0ms preprocess, 268.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWsLz2JF53TTRFFlb8tiXA_0.JPG: 480x640 (no detections), 269.3ms
Speed: 1.1ms preprocess, 269.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWsLz2JF53TTRFFlb8tiXA_90.JPG: 480x640 (no detections), 269.7ms
Speed: 1.0ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWsLz2JF53TTRFFlb8tiXA_180.JPG: 480x640 (no detections), 267.2ms
Speed: 1.0ms preprocess, 267.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWsLz2JF53TTRFFlb8tiXA_270.JPG: 480x640 (no detections), 269.7ms
Speed: 1.2ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWtQrGhMSNYY1Nx50PEZQQ_0.JPG: 480x640 (no detections), 267.1ms
Speed: 1.0ms preprocess, 267.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWtQrGhMSNYY1Nx50PEZQQ_90.JPG: 480x640 (no detections), 270.5ms
Speed: 1.0ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWtQrGhMSNYY1Nx50PEZQQ_180.JPG: 480x640 (no detections), 271.1ms
Speed: 1.0ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWtQrGhMSNYY1Nx50PEZQQ_270.JPG: 480x640 (no detections), 275.4ms
Speed: 1.0ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWtV7YSBuC7Z7XEEUun9qw_0.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWtV7YSBuC7Z7XEEUun9qw_90.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWtV7YSBuC7Z7XEEUun9qw_180.JPG: 480x640 (no detections), 269.9ms
Speed: 1.0ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWtV7YSBuC7Z7XEEUun9qw_270.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWtVAoGxlzucNHtKwWg2Ag_0.JPG: 480x640 (no detections), 269.7ms
Speed: 1.0ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWtVAoGxlzucNHtKwWg2Ag_90.JPG: 480x640 (no detections), 270.2ms
Speed: 1.0ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWtVAoGxlzucNHtKwWg2Ag_180.JPG: 480x640 (no detections), 270.9ms
Speed: 1.1ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWtVAoGxlzucNHtKwWg2Ag_270.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWy_GryJK6z-ML47n6yv9Q_0.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWy_GryJK6z-ML47n6yv9Q_90.JPG: 480x640 (no detections), 269.4ms
Speed: 1.0ms preprocess, 269.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWy_GryJK6z-ML47n6yv9Q_180.JPG: 480x640 (no detections), 267.4ms
Speed: 1.1ms preprocess, 267.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWy_GryJK6z-ML47n6yv9Q_270.JPG: 480x640 (no detections), 269.0ms
Speed: 1.1ms preprocess, 269.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWzw4hfz85IECL2TDLLzXg_0.JPG: 480x640 (no detections), 270.2ms
Speed: 1.0ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWzw4hfz85IECL2TDLLzXg_90.JPG: 480x640 (no detections), 275.4ms
Speed: 1.1ms preprocess, 275.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWzw4hfz85IECL2TDLLzXg_180.JPG: 480x640 (no detections), 270.5ms
Speed: 1.1ms preprocess, 270.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yWzw4hfz85IECL2TDLLzXg_270.JPG: 480x640 1 Waste, 267.8ms
Speed: 1.0ms preprocess, 267.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yX-xy6IesPA7UPIbVJhjNQ_0.JPG: 480x640 (no detections), 272.0ms
Speed: 1.0ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yX-xy6IesPA7UPIbVJhjNQ_90.JPG: 480x640 (no detections), 282.6ms
Speed: 1.3ms preprocess, 282.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yX-xy6IesPA7UPIbVJhjNQ_180.JPG: 480x640 (no detections), 286.5ms
Speed: 1.1ms preprocess, 286.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yX-xy6IesPA7UPIbVJhjNQ_270.JPG: 480x640 (no detections), 279.1ms
Speed: 1.3ms preprocess, 279.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yX2b5f_9W38z27m9sFirGg_0.JPG: 480x640 (no detections), 273.6ms
Speed: 1.1ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yX2b5f_9W38z27m9sFirGg_90.JPG: 480x640 (no detections), 274.2ms
Speed: 1.1ms preprocess, 274.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yX2b5f_9W38z27m9sFirGg_180.JPG: 480x640 (no detections), 293.7ms
Speed: 1.0ms preprocess, 293.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yX2b5f_9W38z27m9sFirGg_270.JPG: 480x640 (no detections), 302.1ms
Speed: 1.4ms preprocess, 302.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yX50SEMXrIg3_YM2cmWkdw_0.JPG: 480x640 (no detections), 280.3ms
Speed: 1.1ms preprocess, 280.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yX50SEMXrIg3_YM2cmWkdw_90.JPG: 480x640 (no detections), 263.8ms
Speed: 1.2ms preprocess, 263.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yX50SEMXrIg3_YM2cmWkdw_180.JPG: 480x640 (no detections), 268.8ms
Speed: 1.0ms preprocess, 268.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yX50SEMXrIg3_YM2cmWkdw_270.JPG: 480x640 (no detections), 266.0ms
Speed: 1.0ms preprocess, 266.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yX7gRumQuV0yvDTNuTFdwA_0.JPG: 480x640 (no detections), 278.2ms
Speed: 1.1ms preprocess, 278.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yX7gRumQuV0yvDTNuTFdwA_90.JPG: 480x640 (no detections), 282.3ms
Speed: 1.0ms preprocess, 282.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yX7gRumQuV0yvDTNuTFdwA_180.JPG: 480x640 (no detections), 274.1ms
Speed: 1.3ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yX7gRumQuV0yvDTNuTFdwA_270.JPG: 480x640 (no detections), 265.4ms
Speed: 1.1ms preprocess, 265.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXAp0B7BXr3kJhZwocTMWQ_0.JPG: 480x640 (no detections), 281.7ms
Speed: 1.0ms preprocess, 281.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXAp0B7BXr3kJhZwocTMWQ_90.JPG: 480x640 (no detections), 276.7ms
Speed: 1.2ms preprocess, 276.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXAp0B7BXr3kJhZwocTMWQ_180.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXAp0B7BXr3kJhZwocTMWQ_270.JPG: 480x640 (no detections), 267.8ms
Speed: 1.1ms preprocess, 267.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXBSz7mTgAJitF66HA7Cgw_0.JPG: 480x640 (no detections), 269.3ms
Speed: 1.1ms preprocess, 269.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXBSz7mTgAJitF66HA7Cgw_90.JPG: 480x640 (no detections), 261.4ms
Speed: 1.1ms preprocess, 261.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXBSz7mTgAJitF66HA7Cgw_180.JPG: 480x640 (no detections), 265.7ms
Speed: 1.0ms preprocess, 265.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXBSz7mTgAJitF66HA7Cgw_270.JPG: 480x640 (no detections), 275.2ms
Speed: 1.1ms preprocess, 275.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXD-_fQV2_QMq0a7H06tlg_0.JPG: 480x640 (no detections), 274.2ms
Speed: 1.3ms preprocess, 274.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXD-_fQV2_QMq0a7H06tlg_90.JPG: 480x640 (no detections), 279.7ms
Speed: 1.3ms preprocess, 279.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXD-_fQV2_QMq0a7H06tlg_180.JPG: 480x640 (no detections), 275.7ms

Speed: 1.0ms preprocess, 275.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXD-_fQV2_QMq0a7H06tlg_270.JPG: 480x640 1 Waste, 267.6ms
Speed: 1.1ms preprocess, 267.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXDrQclUx7eBtYsWKqxj3Q_0.JPG: 480x640 (no detections), 271.5ms
Speed: 1.0ms preprocess, 271.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXDrQclUx7eBtYsWKqxj3Q_90.JPG: 480x640 (no detections), 268.5ms
Speed: 1.1ms preprocess, 268.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXDrQclUx7eBtYsWKqxj3Q_180.JPG: 480x640 1 Waste, 269.1ms
Speed: 1.0ms preprocess, 269.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXDrQclUx7eBtYsWKqxj3Q_270.JPG: 480x640 (no detections), 269.3ms
Speed: 1.1ms preprocess, 269.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXHOQgn-OTP4siwY1FHXKw_0.JPG: 480x640 (no detections), 268.7ms
Speed: 1.0ms preprocess, 268.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXHOQgn-OTP4siwY1FHXKw_90.JPG: 480x640 (no detections), 272.3ms
Speed: 1.1ms preprocess, 272.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXHOQgn-OTP4siwY1FHXKw_180.JPG: 480x640 (no detections), 272.7ms
Speed: 1.0ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXHOQgn-OTP4siwY1FHXKw_270.JPG: 480x640 (no detections), 268.4ms
Speed: 1.0ms preprocess, 268.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXItM6Q6JN5aF5BB0Q7p7g_0.JPG: 480x640 (no detections), 274.8ms
Speed: 1.1ms preprocess, 274.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXItM6Q6JN5aF5BB0Q7p7g_90.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXItM6Q6JN5aF5BB0Q7p7g_180.JPG: 480x640 (no detections), 272.1ms
Speed: 1.1ms preprocess, 272.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXItM6Q6JN5aF5BB0Q7p7g_270.JPG: 480x640 (no detections), 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXLVSMv0oVsW0-qBCm3ckQ_0.JPG: 480x640 (no detections), 278.2ms
Speed: 1.1ms preprocess, 278.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXLVSMv0oVsW0-qBCm3ckQ_90.JPG: 480x640 (no detections), 278.3ms
Speed: 1.1ms preprocess, 278.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXLVSMv0oVsW0-qBCm3ckQ_180.JPG: 480x640 (no detections), 271.7ms
Speed: 1.2ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXLVSMv0oVsW0-qBCm3ckQ_270.JPG: 480x640 (no detections), 279.3ms
Speed: 1.0ms preprocess, 279.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXRenusTg1-9uZdPluXztQ_0.JPG: 480x640 (no detections), 270.5ms
Speed: 1.0ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXRenusTg1-9uZdPluXztQ_90.JPG: 480x640 (no detections), 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXRenusTg1-9uZdPluXztQ_180.JPG: 480x640 (no detections), 271.4ms
Speed: 1.0ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXRenusTg1-9uZdPluXztQ_270.JPG: 480x640 (no detections), 269.5ms
Speed: 1.0ms preprocess, 269.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXVtTBk3ZRE3fMIY-BKXXg_0.JPG: 480x640 (no detections), 270.6ms
Speed: 1.0ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXVtTBk3ZRE3fMIY-BKXXg_90.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXVtTBk3ZRE3fMIY-BKXXg_180.JPG: 480x640 (no detections), 270.0ms
Speed: 1.0ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXVtTBk3ZRE3fMIY-BKXXg_270.JPG: 480x640 (no detections), 271.5ms
Speed: 1.1ms preprocess, 271.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXaznrJYrOv3QlfEIpn3OQ_0.JPG: 480x640 (no detections), 267.6ms
Speed: 1.0ms preprocess, 267.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXaznrJYrOv3QlfEIpn3OQ_90.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXaznrJYrOv3QlfEIpn3OQ_180.JPG: 480x640 (no detections), 274.2ms
Speed: 1.1ms preprocess, 274.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXaznrJYrOv3QlfEIpn3OQ_270.JPG: 480x640 1 Waste, 275.4ms
Speed: 1.1ms preprocess, 275.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXbQdDQNFkP3mfP0mOlDDw_0.JPG: 480x640 (no detections), 268.6ms
Speed: 1.1ms preprocess, 268.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXbQdDQNFkP3mfP0mOlDDw_90.JPG: 480x640 (no detections), 265.7ms
Speed: 1.1ms preprocess, 265.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXbQdDQNFkP3mfP0mOlDDw_180.JPG: 480x640 (no detections), 272.7ms
Speed: 1.2ms preprocess, 272.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXbQdDQNFkP3mfP0mOlDDw_270.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXdE5yxjzWIyqCTQJOr5Qg_0.JPG: 480x640 (no detections), 270.1ms
Speed: 1.0ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXdE5yxjzWIyqCTQJOr5Qg_90.JPG: 480x640 (no detections), 268.7ms
Speed: 1.0ms preprocess, 268.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXdE5yxjzWIyqCTQJOr5Qg_180.JPG: 480x640 (no detections), 270.5ms
Speed: 1.0ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXdE5yxjzWIyqCTQJOr5Qg_270.JPG: 480x640 (no detections), 266.8ms
Speed: 1.1ms preprocess, 266.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXeKvGYxYS6JcF7nioc5GQ_0.JPG: 480x640 (no detections), 268.1ms
Speed: 1.1ms preprocess, 268.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXeKvGYxYS6JcF7nioc5GQ_90.JPG: 480x640 (no detections), 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXeKvGYxYS6JcF7nioc5GQ_180.JPG: 480x640 (no detections), 269.2ms
Speed: 1.1ms preprocess, 269.2ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXeKvGYxYS6JcF7nioc5GQ_270.JPG: 480x640 (no detections), 270.6ms
Speed: 1.0ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXehphv6EeEIoQTE40XZFA_0.JPG: 480x640 (no detections), 265.0ms
Speed: 1.0ms preprocess, 265.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXehphv6EeEIoQTE40XZFA_90.JPG: 480x640 (no detections), 266.3ms
Speed: 1.0ms preprocess, 266.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXehphv6EeEIoQTE40XZFA_180.JPG: 480x640 (no detections), 275.2ms
Speed: 1.0ms preprocess, 275.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXehphv6EeEIoQTE40XZFA_270.JPG: 480x640 (no detections), 268.6ms
Speed: 1.0ms preprocess, 268.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXiI6ZJzoF7R1BSw5gwTKg_0.JPG: 480x640 (no detections), 275.2ms
Speed: 1.1ms preprocess, 275.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXiI6ZJzoF7R1BSw5gwTKg_90.JPG: 480x640 (no detections), 298.8ms
Speed: 1.1ms preprocess, 298.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXiI6ZJzoF7R1BSw5gwTKg_180.JPG: 480x640 (no detections), 274.6ms
Speed: 1.3ms preprocess, 274.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXiI6ZJzoF7R1BSw5gwTKg_270.JPG: 480x640 (no detections), 275.0ms
Speed: 1.1ms preprocess, 275.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXiYjs6rI0buHk7e803y2A_0.JPG: 480x640 (no detections), 268.4ms
Speed: 1.1ms preprocess, 268.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXiYjs6rI0buHk7e803y2A_90.JPG: 480x640 (no detections), 277.2ms
Speed: 1.2ms preprocess, 277.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXiYjs6rI0buHk7e803y2A_180.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXiYjs6rI0buHk7e803y2A_270.JPG: 480x640 (no detections), 268.6ms
Speed: 1.0ms preprocess, 268.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXjzSP2H-1nklunviNcpmQ_0.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXjzSP2H-1nklunviNcpmQ_90.JPG: 480x640 (no detections), 268.5ms
Speed: 1.1ms preprocess, 268.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXjzSP2H-1nklunviNcpmQ_180.JPG: 480x640 (no detections), 269.0ms
Speed: 1.0ms preprocess, 269.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXjzSP2H-1nklunviNcpmQ_270.JPG: 480x640 (no detections), 273.8ms
Speed: 1.0ms preprocess, 273.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXkuORvDnRd9i-awudFqUQ_0.JPG: 480x640 (no detections), 277.7ms
Speed: 1.1ms preprocess, 277.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXkuORvDnRd9i-awudFqUQ_90.JPG: 480x640 (no detections), 274.2ms
Speed: 1.1ms preprocess, 274.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXkuORvDnRd9i-awudFqUQ_180.JPG: 480x640 (no detections), 267.4ms
Speed: 1.0ms preprocess, 267.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXkuORvDnRd9i-awudFqUQ_270.JPG: 480x640 (no detections), 278.6ms
Speed: 1.2ms preprocess, 278.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXlMbxGXQHAlZ1uGHBTQcg_0.JPG: 480x640 (no detections), 273.7ms
Speed: 1.0ms preprocess, 273.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXlMbxGXQHAlZ1uGHBTQcg_90.JPG: 480x640 (no detections), 273.7ms
Speed: 1.0ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXlMbxGXQHAlZ1uGHBTQcg_180.JPG: 480x640 (no detections), 269.4ms
Speed: 1.2ms preprocess, 269.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXlMbxGXQHAlZ1uGHBTQcg_270.JPG: 480x640 (no detections), 268.6ms
Speed: 1.1ms preprocess, 268.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXmJVeYZshmHKONf9Y7jgw_0.JPG: 480x640 (no detections), 287.8ms
Speed: 1.2ms preprocess, 287.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXmJVeYZshmHKONf9Y7jgw_90.JPG: 480x640 (no detections), 280.6ms

Speed: 1.1ms preprocess, 280.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXmJVeYZshmHKONf9Y7jgw_180.JPG: 480x640 (no detections), 273.5ms
Speed: 1.0ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXmJVeYZshmHKONf9Y7jgw_270.JPG: 480x640 (no detections), 269.0ms
Speed: 1.0ms preprocess, 269.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXn6EBAHmwu0eRbX0opeEQ_0.JPG: 480x640 (no detections), 270.4ms
Speed: 1.0ms preprocess, 270.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXn6EBAHmwu0eRbX0opeEQ_90.JPG: 480x640 (no detections), 269.3ms
Speed: 1.1ms preprocess, 269.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXn6EBAHmwu0eRbX0opeEQ_180.JPG: 480x640 (no detections), 269.0ms
Speed: 1.1ms preprocess, 269.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXn6EBAHmwu0eRbX0opeEQ_270.JPG: 480x640 (no detections), 276.8ms
Speed: 1.1ms preprocess, 276.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXr3zQLTQ9IHipO3Jvx_dQ_0.JPG: 480x640 (no detections), 277.6ms
Speed: 1.1ms preprocess, 277.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXr3zQLTQ9IHipO3Jvx_dQ_90.JPG: 480x640 (no detections), 270.0ms
Speed: 1.7ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXr3zQLTQ9IHipO3Jvx_dQ_180.JPG: 480x640 (no detections), 276.0ms
Speed: 1.0ms preprocess, 276.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXr3zQLTQ9IHipO3Jvx_dQ_270.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXxDAGuxqHesLnUQ1vJpJQ_0.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXxDAGuxqHesLnUQ1vJpJQ_90.JPG: 480x640 (no detections), 274.6ms
Speed: 1.0ms preprocess, 274.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXxDAGuxqHesLnUQ1vJpJQ_180.JPG: 480x640 (no detections), 267.4ms
Speed: 1.1ms preprocess, 267.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXxDAGuxqHesLnUQ1vJpJQ_270.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXycF072fTG22dsl_GGd2Q_0.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXycF072fTG22dsl_GGd2Q_90.JPG: 480x640 (no detections), 270.4ms
Speed: 1.1ms preprocess, 270.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXycF072fTG22dsl_GGd2Q_180.JPG: 480x640 (no detections), 268.3ms
Speed: 1.0ms preprocess, 268.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXycF072fTG22dsl_GGd2Q_270.JPG: 480x640 (no detections), 269.2ms
Speed: 1.1ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXzuNeNZxZNxO-2IVi0rkA_0.JPG: 480x640 (no detections), 267.2ms
Speed: 1.1ms preprocess, 267.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXzuNeNZxZNxO-2IVi0rkA_90.JPG: 480x640 (no detections), 275.0ms
Speed: 1.1ms preprocess, 275.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXzuNeNZxZNxO-2IVi0rkA_180.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXzuNeNZxZNxO-2IVi0rkA_270.JPG: 480x640 (no detections), 268.3ms
Speed: 1.1ms preprocess, 268.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXzz9Yc0pG21RCt-ubVs2Q_0.JPG: 480x640 (no detections), 267.8ms
Speed: 1.1ms preprocess, 267.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXzz9Yc0pG21RCt-ubVs2Q_90.JPG: 480x640 (no detections), 265.6ms
Speed: 1.0ms preprocess, 265.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXzz9Yc0pG21RCt-ubVs2Q_180.JPG: 480x640 (no detections), 267.9ms
Speed: 1.1ms preprocess, 267.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yXzz9Yc0pG21RCt-ubVs2Q_270.JPG: 480x640 (no detections), 270.8ms
Speed: 1.0ms preprocess, 270.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yY-J8r4btqRS8uOxefxr_w_0.JPG: 480x640 (no detections), 269.3ms
Speed: 1.0ms preprocess, 269.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yY-J8r4btqRS8uOxefxr_w_90.JPG: 480x640 (no detections), 267.5ms
Speed: 1.1ms preprocess, 267.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yY-J8r4btqRS8uOxefxr_w_180.JPG: 480x640 (no detections), 267.0ms
Speed: 1.1ms preprocess, 267.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yY-J8r4btqRS8uOxefxr_w_270.JPG: 480x640 (no detections), 267.9ms
Speed: 1.0ms preprocess, 267.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yY325cycyXMB64-V8H1U2w_0.JPG: 480x640 (no detections), 269.1ms
Speed: 1.1ms preprocess, 269.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yY325cycyXMB64-V8H1U2w_90.JPG: 480x640 (no detections), 269.2ms
Speed: 1.2ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yY325cycyXMB64-V8H1U2w_180.JPG: 480x640 (no detections), 268.4ms
Speed: 1.2ms preprocess, 268.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yY325cycyXMB64-V8H1U2w_270.JPG: 480x640 (no detections), 273.6ms
Speed: 1.1ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yY9g16YZVpRVzp_h61tJYg_0.JPG: 480x640 (no detections), 276.5ms
Speed: 1.1ms preprocess, 276.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yY9g16YZVpRVzp_h61tJYg_90.JPG: 480x640 (no detections), 272.7ms
Speed: 1.2ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yY9g16YZVpRVzp_h61tJYg_180.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yY9g16YZVpRVzp_h61tJYg_270.JPG: 480x640 (no detections), 268.1ms
Speed: 1.1ms preprocess, 268.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYBzkVAd46A1awbh936U9w_0.JPG: 480x640 (no detections), 267.5ms
Speed: 1.1ms preprocess, 267.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYBzkVAd46A1awbh936U9w_90.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYBzkVAd46A1awbh936U9w_180.JPG: 480x640 (no detections), 269.0ms
Speed: 1.0ms preprocess, 269.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYBzkVAd46A1awbh936U9w_270.JPG: 480x640 (no detections), 272.0ms
Speed: 1.1ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYDAFXtrMrFmrHQVP7KZvQ_0.JPG: 480x640 (no detections), 266.0ms
Speed: 1.0ms preprocess, 266.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYDAFXtrMrFmrHQVP7KZvQ_90.JPG: 480x640 (no detections), 269.7ms
Speed: 1.7ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYDAFXtrMrFmrHQVP7KZvQ_180.JPG: 480x640 (no detections), 274.6ms
Speed: 1.1ms preprocess, 274.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYDAFXtrMrFmrHQVP7KZvQ_270.JPG: 480x640 (no detections), 277.0ms
Speed: 1.0ms preprocess, 277.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYEnBNAmvfIlYQ5Clt_m1g_0.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYEnBNAmvfIlYQ5Clt_m1g_90.JPG: 480x640 (no detections), 268.9ms
Speed: 1.1ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYEnBNAmvfIlYQ5Clt_m1g_180.JPG: 480x640 (no detections), 272.4ms
Speed: 1.2ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYEnBNAmvfIlYQ5Clt_m1g_270.JPG: 480x640 (no detections), 275.0ms
Speed: 1.1ms preprocess, 275.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYIhrmQdJutorAtVme66HA_0.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYIhrmQdJutorAtVme66HA_90.JPG: 480x640 (no detections), 274.2ms
Speed: 1.0ms preprocess, 274.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYIhrmQdJutorAtVme66HA_180.JPG: 480x640 (no detections), 275.5ms
Speed: 1.0ms preprocess, 275.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYIhrmQdJutorAtVme66HA_270.JPG: 480x640 (no detections), 273.3ms
Speed: 1.0ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYJSeRDlfOm3t775NGZAPA_0.JPG: 480x640 (no detections), 273.6ms
Speed: 1.1ms preprocess, 273.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYJSeRDlfOm3t775NGZAPA_90.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYJSeRDlfOm3t775NGZAPA_180.JPG: 480x640 (no detections), 274.4ms
Speed: 1.1ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYJSeRDlfOm3t775NGZAPA_270.JPG: 480x640 (no detections), 274.6ms
Speed: 1.2ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYMl8hZlKFIB_bs5uDOaxw_0.JPG: 480x640 (no detections), 281.4ms
Speed: 1.2ms preprocess, 281.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYMl8hZlKFIB_bs5uDOaxw_90.JPG: 480x640 (no detections), 275.8ms
Speed: 1.2ms preprocess, 275.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYMl8hZlKFIB_bs5uDOaxw_180.JPG: 480x640 (no detections), 273.1ms
Speed: 1.0ms preprocess, 273.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYMl8hZlKFIB_bs5uDOaxw_270.JPG: 480x640 (no detections), 275.9ms
Speed: 1.1ms preprocess, 275.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYOZR43yeF-BWqKWpcPatg_0.JPG: 480x640 (no detections), 276.9ms
Speed: 1.1ms preprocess, 276.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYOZR43yeF-BWqKWpcPatg_90.JPG: 480x640 (no detections), 278.8ms
Speed: 1.2ms preprocess, 278.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYOZR43yeF-BWqKWpcPatg_180.JPG: 480x640 (no detections), 275.2ms
Speed: 1.1ms preprocess, 275.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYOZR43yeF-BWqKWpcPatg_270.JPG: 480x640 (no detections), 279.6ms
Speed: 1.1ms preprocess, 279.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYOghALd-aBdclqxSpvn7w_0.JPG: 480x640 (no detections), 271.5ms

Speed: 1.1ms preprocess, 271.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYOghALd-aBdclqxSpvn7w_90.JPG: 480x640 (no detections), 276.6ms
Speed: 1.0ms preprocess, 276.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYOghALd-aBdclqxSpvn7w_180.JPG: 480x640 (no detections), 278.1ms
Speed: 1.1ms preprocess, 278.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYOghALd-aBdclqxSpvn7w_270.JPG: 480x640 (no detections), 271.3ms
Speed: 1.0ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYPiFoW-jz5J4kdF52lJ1Q_0.JPG: 480x640 (no detections), 268.2ms
Speed: 1.0ms preprocess, 268.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYPiFoW-jz5J4kdF52lJ1Q_90.JPG: 480x640 (no detections), 278.2ms
Speed: 1.4ms preprocess, 278.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYPiFoW-jz5J4kdF52lJ1Q_180.JPG: 480x640 (no detections), 270.0ms
Speed: 1.2ms preprocess, 270.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYPiFoW-jz5J4kdF52lJ1Q_270.JPG: 480x640 (no detections), 276.4ms
Speed: 1.0ms preprocess, 276.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYW-yGqi4sjKGg0u_uPo9A_0.JPG: 480x640 (no detections), 282.2ms
Speed: 1.1ms preprocess, 282.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYW-yGqi4sjKGg0u_uPo9A_90.JPG: 480x640 (no detections), 286.2ms
Speed: 1.3ms preprocess, 286.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYW-yGqi4sjKGg0u_uPo9A_180.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYW-yGqi4sjKGg0u_uPo9A_270.JPG: 480x640 (no detections), 273.9ms
Speed: 1.1ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYY4uHPN2VzOFRTCEPMv3A_0.JPG: 480x640 (no detections), 279.8ms
Speed: 1.1ms preprocess, 279.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYY4uHPN2VzOFRTCEPMv3A_90.JPG: 480x640 (no detections), 277.2ms
Speed: 1.4ms preprocess, 277.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYY4uHPN2VzOFRTCEPMv3A_180.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYY4uHPN2VzOFRTCEPMv3A_270.JPG: 480x640 (no detections), 279.2ms
Speed: 1.1ms preprocess, 279.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYZ2hEJ0RuYiY6Djw-WOfg_0.JPG: 480x640 (no detections), 271.5ms
Speed: 1.2ms preprocess, 271.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYZ2hEJ0RuYiY6Djw-WOfg_90.JPG: 480x640 (no detections), 268.5ms
Speed: 1.1ms preprocess, 268.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYZ2hEJ0RuYiY6Djw-WOfg_180.JPG: 480x640 (no detections), 267.5ms
Speed: 1.1ms preprocess, 267.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYZ2hEJ0RuYiY6Djw-WOfg_270.JPG: 480x640 (no detections), 278.0ms
Speed: 1.0ms preprocess, 278.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYbHiR2846QM8CKpVHvaGw_0.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYbHiR2846QM8CKpVHvaGw_90.JPG: 480x640 (no detections), 271.9ms
Speed: 1.0ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYbHiR2846QM8CKpVHvaGw_180.JPG: 480x640 (no detections), 272.0ms
Speed: 1.1ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYbHiR2846QM8CKpVHvaGw_270.JPG: 480x640 (no detections), 276.4ms
Speed: 1.0ms preprocess, 276.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYiV-8So3PSvLt9UuRx7AA_0.JPG: 480x640 (no detections), 289.7ms
Speed: 1.0ms preprocess, 289.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYiV-8So3PSvLt9UuRx7AA_90.JPG: 480x640 (no detections), 274.8ms
Speed: 1.2ms preprocess, 274.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYiV-8So3PSvLt9UuRx7AA_180.JPG: 480x640 (no detections), 284.2ms
Speed: 1.0ms preprocess, 284.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYiV-8So3PSvLt9UuRx7AA_270.JPG: 480x640 (no detections), 275.7ms
Speed: 1.1ms preprocess, 275.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYoP_fdbw50cVgO-A42uzA_0.JPG: 480x640 (no detections), 274.9ms
Speed: 1.1ms preprocess, 274.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYoP_fdbw50cVgO-A42uzA_90.JPG: 480x640 (no detections), 273.9ms
Speed: 1.2ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYoP_fdbw50cVgO-A42uzA_180.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYoP_fdbw50cVgO-A42uzA_270.JPG: 480x640 (no detections), 269.6ms
Speed: 1.1ms preprocess, 269.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYuj972GpM4HVMIhjxuwAA_0.JPG: 480x640 (no detections), 276.5ms
Speed: 1.1ms preprocess, 276.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYuj972GpM4HVMIhjxuwAA_90.JPG: 480x640 (no detections), 275.4ms
Speed: 1.0ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYuj972GpM4HVMIhjxuwAA_180.JPG: 480x640 (no detections), 275.8ms
Speed: 1.0ms preprocess, 275.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYuj972GpM4HVMIhjxuwAA_270.JPG: 480x640 (no detections), 270.3ms
Speed: 1.1ms preprocess, 270.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYzqNoqWussQ0b19nn-omw_0.JPG: 480x640 1 Waste, 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYzqNoqWussQ0b19nn-omw_90.JPG: 480x640 (no detections), 270.9ms
Speed: 1.0ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYzqNoqWussQ0b19nn-omw_180.JPG: 480x640 (no detections), 273.9ms
Speed: 1.1ms preprocess, 273.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yYzqNoqWussQ0b19nn-omw_270.JPG: 480x640 (no detections), 273.0ms
Speed: 1.2ms preprocess, 273.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZ082DA2PE5Zh2Lcy7Y34Q_0.JPG: 480x640 (no detections), 277.1ms
Speed: 1.1ms preprocess, 277.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZ082DA2PE5Zh2Lcy7Y34Q_90.JPG: 480x640 (no detections), 276.5ms
Speed: 1.0ms preprocess, 276.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZ082DA2PE5Zh2Lcy7Y34Q_180.JPG: 480x640 (no detections), 272.2ms
Speed: 1.3ms preprocess, 272.2ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZ082DA2PE5Zh2Lcy7Y34Q_270.JPG: 480x640 (no detections), 270.1ms
Speed: 1.2ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZ0Weto2Khu6lbAi-LrCVA_0.JPG: 480x640 (no detections), 292.5ms
Speed: 1.1ms preprocess, 292.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZ0Weto2Khu6lbAi-LrCVA_90.JPG: 480x640 (no detections), 276.8ms
Speed: 1.2ms preprocess, 276.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZ0Weto2Khu6lbAi-LrCVA_180.JPG: 480x640 (no detections), 274.2ms
Speed: 1.4ms preprocess, 274.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZ0Weto2Khu6lbAi-LrCVA_270.JPG: 480x640 (no detections), 282.9ms
Speed: 1.1ms preprocess, 282.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZ9S8rafSK_f8Cc9aXn3FQ_0.JPG: 480x640 (no detections), 272.9ms
Speed: 1.0ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZ9S8rafSK_f8Cc9aXn3FQ_90.JPG: 480x640 (no detections), 277.6ms
Speed: 1.0ms preprocess, 277.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZ9S8rafSK_f8Cc9aXn3FQ_180.JPG: 480x640 (no detections), 279.6ms
Speed: 1.0ms preprocess, 279.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZ9S8rafSK_f8Cc9aXn3FQ_270.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZB2STcNbiF3FrYpEMoT1A_0.JPG: 480x640 (no detections), 270.2ms
Speed: 1.3ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZB2STcNbiF3FrYpEMoT1A_90.JPG: 480x640 (no detections), 273.3ms
Speed: 1.2ms preprocess, 273.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZB2STcNbiF3FrYpEMoT1A_180.JPG: 480x640 (no detections), 279.5ms
Speed: 1.1ms preprocess, 279.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZB2STcNbiF3FrYpEMoT1A_270.JPG: 480x640 (no detections), 284.5ms
Speed: 1.1ms preprocess, 284.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZFT9Nc5z3omI6j3JwlT_w_0.JPG: 480x640 (no detections), 272.9ms
Speed: 1.0ms preprocess, 272.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZFT9Nc5z3omI6j3JwlT_w_90.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZFT9Nc5z3omI6j3JwlT_w_180.JPG: 480x640 (no detections), 268.6ms
Speed: 1.0ms preprocess, 268.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZFT9Nc5z3omI6j3JwlT_w_270.JPG: 480x640 (no detections), 271.4ms
Speed: 1.0ms preprocess, 271.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZGrTiEP9clWp1PMx_WIng_0.JPG: 480x640 (no detections), 274.7ms
Speed: 1.1ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZGrTiEP9clWp1PMx_WIng_90.JPG: 480x640 (no detections), 270.9ms
Speed: 1.0ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZGrTiEP9clWp1PMx_WIng_180.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZGrTiEP9clWp1PMx_WIng_270.JPG: 480x640 (no detections), 277.0ms
Speed: 1.2ms preprocess, 277.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZHZL-hgVsGtIIaJd00-6w_0.JPG: 480x640 (no detections), 280.7ms
Speed: 1.1ms preprocess, 280.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZHZL-hgVsGtIIaJd00-6w_90.JPG: 480x640 (no detections), 274.1ms
Speed: 1.0ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZHZL-hgVsGtIIaJd00-6w_180.JPG: 480x640 (no detections), 275.9ms
Speed: 1.7ms preprocess, 275.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZHZL-hgVsGtIIaJd00-6w_270.JPG: 480x640 (no detections), 272.7ms

Speed: 1.1ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZHcwVKlJ_665bztSDVGAQ_0.JPG: 480x640 (no detections), 274.7ms
Speed: 1.0ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZHcwVKlJ_665bztSDVGAQ_90.JPG: 480x640 (no detections), 275.7ms
Speed: 1.1ms preprocess, 275.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZHcwVKlJ_665bztSDVGAQ_180.JPG: 480x640 (no detections), 273.8ms
Speed: 1.3ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZHcwVKlJ_665bztSDVGAQ_270.JPG: 480x640 (no detections), 280.0ms
Speed: 1.2ms preprocess, 280.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZJUAV_b4MWP8kCSWNW3_Q_0.JPG: 480x640 1 Waste, 274.3ms
Speed: 1.2ms preprocess, 274.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZJUAV_b4MWP8kCSWNW3_Q_90.JPG: 480x640 (no detections), 274.8ms
Speed: 1.1ms preprocess, 274.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZJUAV_b4MWP8kCSWNW3_Q_180.JPG: 480x640 (no detections), 272.4ms
Speed: 1.0ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZJUAV_b4MWP8kCSWNW3_Q_270.JPG: 480x640 (no detections), 275.3ms
Speed: 1.0ms preprocess, 275.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZJmwKO_OnmOb-zZRtblUw_0.JPG: 480x640 (no detections), 271.1ms
Speed: 1.0ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZJmwKO_OnmOb-zZRtblUw_90.JPG: 480x640 (no detections), 268.0ms
Speed: 1.0ms preprocess, 268.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZJmwKO_OnmOb-zZRtblUw_180.JPG: 480x640 (no detections), 280.6ms
Speed: 1.0ms preprocess, 280.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZJmwKO_OnmOb-zZRtblUw_270.JPG: 480x640 (no detections), 272.1ms
Speed: 1.1ms preprocess, 272.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZKEVcbDmJlSN1Yu2RNAhw_0.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZKEVcbDmJlSN1Yu2RNAhw_90.JPG: 480x640 (no detections), 274.0ms
Speed: 1.1ms preprocess, 274.0ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZKEVcbDmJlSN1Yu2RNAhw_180.JPG: 480x640 (no detections), 272.5ms
Speed: 1.0ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZKEVcbDmJlSN1Yu2RNAhw_270.JPG: 480x640 (no detections), 276.1ms
Speed: 1.1ms preprocess, 276.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZL3Cg_-RboV_09LK9EnGw_0.JPG: 480x640 1 Waste, 301.9ms
Speed: 1.2ms preprocess, 301.9ms inference, 9.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZL3Cg_-RboV_09LK9EnGw_90.JPG: 480x640 (no detections), 345.5ms
Speed: 12.5ms preprocess, 345.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZL3Cg_-RboV_09LK9EnGw_180.JPG: 480x640 (no detections), 313.5ms
Speed: 1.3ms preprocess, 313.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZL3Cg_-RboV_09LK9EnGw_270.JPG: 480x640 1 Waste, 310.0ms
Speed: 1.5ms preprocess, 310.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZQ99Cs26OatWKvY3hv1iw_0.JPG: 480x640 (no detections), 368.4ms
Speed: 1.4ms preprocess, 368.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZQ99Cs26OatWKvY3hv1iw_90.JPG: 480x640 (no detections), 290.0ms
Speed: 1.2ms preprocess, 290.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZQ99Cs26OatWKvY3hv1iw_180.JPG: 480x640 (no detections), 277.4ms
Speed: 1.1ms preprocess, 277.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZQ99Cs26OatWKvY3hv1iw_270.JPG: 480x640 (no detections), 288.4ms
Speed: 1.2ms preprocess, 288.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZSx9CoEzrAuu0RBAeMKTg_0.JPG: 480x640 (no detections), 292.0ms
Speed: 1.7ms preprocess, 292.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZSx9CoEzrAuu0RBAeMKTg_90.JPG: 480x640 (no detections), 286.7ms
Speed: 2.1ms preprocess, 286.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZSx9CoEzrAuu0RBAeMKTg_180.JPG: 480x640 (no detections), 287.5ms
Speed: 1.1ms preprocess, 287.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZSx9CoEzrAuu0RBAeMKTg_270.JPG: 480x640 (no detections), 332.4ms
Speed: 1.1ms preprocess, 332.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZUcJqCE0K4fFFEOyA_4Fw_0.JPG: 480x640 (no detections), 295.0ms
Speed: 1.3ms preprocess, 295.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZUcJqCE0K4fFFEOyA_4Fw_90.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZUcJqCE0K4fFFEOyA_4Fw_180.JPG: 480x640 (no detections), 276.6ms
Speed: 1.0ms preprocess, 276.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZUcJqCE0K4fFFEOyA_4Fw_270.JPG: 480x640 (no detections), 277.7ms
Speed: 1.4ms preprocess, 277.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZc76FW2_6n-T3XPkpZQtw_0.JPG: 480x640 (no detections), 297.3ms
Speed: 1.1ms preprocess, 297.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZc76FW2_6n-T3XPkpZQtw_90.JPG: 480x640 (no detections), 275.2ms
Speed: 1.0ms preprocess, 275.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZc76FW2_6n-T3XPkpZQtw_180.JPG: 480x640 (no detections), 270.5ms
Speed: 1.1ms preprocess, 270.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZc76FW2_6n-T3XPkpZQtw_270.JPG: 480x640 (no detections), 280.0ms
Speed: 1.1ms preprocess, 280.0ms inference, 1.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZdVnCVa_qX2VK9P4iMMmA_0.JPG: 480x640 (no detections), 264.0ms
Speed: 1.3ms preprocess, 264.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZdVnCVa_qX2VK9P4iMMmA_90.JPG: 480x640 (no detections), 267.4ms
Speed: 1.1ms preprocess, 267.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZdVnCVa_qX2VK9P4iMMmA_180.JPG: 480x640 (no detections), 275.7ms
Speed: 1.2ms preprocess, 275.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZdVnCVa_qX2VK9P4iMMmA_270.JPG: 480x640 (no detections), 273.5ms
Speed: 1.3ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZfsSe56pQChRy2JXXJepQ_0.JPG: 480x640 (no detections), 277.5ms
Speed: 1.3ms preprocess, 277.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZfsSe56pQChRy2JXXJepQ_90.JPG: 480x640 (no detections), 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZfsSe56pQChRy2JXXJepQ_180.JPG: 480x640 (no detections), 276.6ms
Speed: 1.0ms preprocess, 276.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZfsSe56pQChRy2JXXJepQ_270.JPG: 480x640 (no detections), 287.6ms
Speed: 1.0ms preprocess, 287.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZg3nYaqwo1nqyce60HfJg_0.JPG: 480x640 (no detections), 278.1ms
Speed: 1.2ms preprocess, 278.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZg3nYaqwo1nqyce60HfJg_90.JPG: 480x640 2 Wastes, 288.5ms
Speed: 1.1ms preprocess, 288.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZg3nYaqwo1nqyce60HfJg_180.JPG: 480x640 (no detections), 271.5ms
Speed: 1.1ms preprocess, 271.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZg3nYaqwo1nqyce60HfJg_270.JPG: 480x640 (no detections), 271.6ms
Speed: 1.5ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZhKIE8iYH8yok6oYLkjtg_0.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZhKIE8iYH8yok6oYLkjtg_90.JPG: 480x640 (no detections), 272.1ms
Speed: 1.1ms preprocess, 272.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZhKIE8iYH8yok6oYLkjtg_180.JPG: 480x640 (no detections), 276.4ms
Speed: 1.1ms preprocess, 276.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZhKIE8iYH8yok6oYLkjtg_270.JPG: 480x640 (no detections), 285.4ms
Speed: 1.0ms preprocess, 285.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZif6RUbm0cAO-Wv_yh8KA_0.JPG: 480x640 (no detections), 283.2ms
Speed: 1.2ms preprocess, 283.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZif6RUbm0cAO-Wv_yh8KA_90.JPG: 480x640 (no detections), 280.0ms
Speed: 1.1ms preprocess, 280.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZif6RUbm0cAO-Wv_yh8KA_180.JPG: 480x640 (no detections), 278.7ms
Speed: 1.2ms preprocess, 278.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZif6RUbm0cAO-Wv_yh8KA_270.JPG: 480x640 (no detections), 280.7ms
Speed: 1.1ms preprocess, 280.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZjIzoF5khjLufHqM7i1gg_0.JPG: 480x640 (no detections), 308.9ms
Speed: 1.2ms preprocess, 308.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZjIzoF5khjLufHqM7i1gg_90.JPG: 480x640 (no detections), 286.8ms
Speed: 1.1ms preprocess, 286.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZjIzoF5khjLufHqM7i1gg_180.JPG: 480x640 (no detections), 300.2ms
Speed: 1.1ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZjIzoF5khjLufHqM7i1gg_270.JPG: 480x640 (no detections), 304.8ms
Speed: 1.1ms preprocess, 304.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZjtctnNgWyn82VlnKZdjw_0.JPG: 480x640 (no detections), 301.6ms
Speed: 1.0ms preprocess, 301.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZjtctnNgWyn82VlnKZdjw_90.JPG: 480x640 (no detections), 324.1ms
Speed: 1.4ms preprocess, 324.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZjtctnNgWyn82VlnKZdjw_180.JPG: 480x640 (no detections), 313.2ms
Speed: 1.1ms preprocess, 313.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZjtctnNgWyn82VlnKZdjw_270.JPG: 480x640 2 Wastes, 309.7ms
Speed: 1.3ms preprocess, 309.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZpo-8moPZDiGnZQ76s4Xg_0.JPG: 480x640 (no detections), 312.0ms
Speed: 1.3ms preprocess, 312.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZpo-8moPZDiGnZQ76s4Xg_90.JPG: 480x640 (no detections), 312.5ms
Speed: 1.5ms preprocess, 312.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZpo-8moPZDiGnZQ76s4Xg_180.JPG: 480x640 (no detections), 299.7ms

Speed: 1.1ms preprocess, 299.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZpo-8moPZDiGnZQ76s4Xg_270.JPG: 480x640 (no detections), 299.4ms
Speed: 1.1ms preprocess, 299.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZqLE7rnztlSwcPLjTZekw_0.JPG: 480x640 1 Waste, 295.7ms
Speed: 1.2ms preprocess, 295.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZqLE7rnztlSwcPLjTZekw_90.JPG: 480x640 (no detections), 343.2ms
Speed: 1.1ms preprocess, 343.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZqLE7rnztlSwcPLjTZekw_180.JPG: 480x640 (no detections), 302.7ms
Speed: 1.3ms preprocess, 302.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZqLE7rnztlSwcPLjTZekw_270.JPG: 480x640 (no detections), 307.8ms
Speed: 1.1ms preprocess, 307.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZqrO2o0gXKdau6SH7aHww_0.JPG: 480x640 (no detections), 315.0ms
Speed: 1.3ms preprocess, 315.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZqrO2o0gXKdau6SH7aHww_90.JPG: 480x640 (no detections), 317.4ms
Speed: 1.6ms preprocess, 317.4ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZqrO2o0gXKdau6SH7aHww_180.JPG: 480x640 (no detections), 324.7ms
Speed: 1.5ms preprocess, 324.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZqrO2o0gXKdau6SH7aHww_270.JPG: 480x640 (no detections), 313.4ms
Speed: 1.1ms preprocess, 313.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZuoCFQAXkxx3PToo4q-cQ_0.JPG: 480x640 (no detections), 308.5ms
Speed: 1.7ms preprocess, 308.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZuoCFQAXkxx3PToo4q-cQ_90.JPG: 480x640 (no detections), 315.7ms
Speed: 1.3ms preprocess, 315.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZuoCFQAXkxx3PToo4q-cQ_180.JPG: 480x640 (no detections), 312.2ms
Speed: 1.2ms preprocess, 312.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZuoCFQAXkxx3PToo4q-cQ_270.JPG: 480x640 (no detections), 308.9ms
Speed: 1.1ms preprocess, 308.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZyZdmLXdEDq00g5fksl1g_0.JPG: 480x640 (no detections), 300.1ms
Speed: 1.1ms preprocess, 300.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZyZdmLXdEDq00g5fksl1g_90.JPG: 480x640 (no detections), 298.5ms
Speed: 1.6ms preprocess, 298.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZyZdmLXdEDq00g5fksl1g_180.JPG: 480x640 (no detections), 314.1ms
Speed: 1.6ms preprocess, 314.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yZyZdmLXdEDq00g5fksl1g_270.JPG: 480x640 (no detections), 311.4ms
Speed: 1.1ms preprocess, 311.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_-_BCz3RPfZPFkLoqlA7Q_0.JPG: 480x640 1 Waste, 306.9ms
Speed: 1.0ms preprocess, 306.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_-_BCz3RPfZPFkLoqlA7Q_90.JPG: 480x640 1 Waste, 297.0ms
Speed: 1.2ms preprocess, 297.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_-_BCz3RPfZPFkLoqlA7Q_180.JPG: 480x640 (no detections), 266.8ms
Speed: 1.1ms preprocess, 266.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_-_BCz3RPfZPFkLoqlA7Q_270.JPG: 480x640 (no detections), 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_2hjRZsgt_0Xsx4zuE0rQ_0.JPG: 480x640 (no detections), 268.4ms
Speed: 1.0ms preprocess, 268.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_2hjRZsgt_0Xsx4zuE0rQ_90.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_2hjRZsgt_0Xsx4zuE0rQ_180.JPG: 480x640 (no detections), 270.9ms
Speed: 1.0ms preprocess, 270.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_2hjRZsgt_0Xsx4zuE0rQ_270.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_4lagVV6WayW_tt63CFsw_0.JPG: 480x640 (no detections), 272.1ms
Speed: 1.2ms preprocess, 272.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_4lagVV6WayW_tt63CFsw_90.JPG: 480x640 (no detections), 281.2ms
Speed: 1.1ms preprocess, 281.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_4lagVV6WayW_tt63CFsw_180.JPG: 480x640 (no detections), 275.8ms
Speed: 1.1ms preprocess, 275.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_4lagVV6WayW_tt63CFsw_270.JPG: 480x640 (no detections), 269.1ms
Speed: 1.1ms preprocess, 269.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_4wOebg0eseF7WWmDsfsw_0.JPG: 480x640 (no detections), 282.2ms
Speed: 1.6ms preprocess, 282.2ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_4wOebg0eseF7WWmDsfsw_90.JPG: 480x640 (no detections), 277.3ms
Speed: 1.1ms preprocess, 277.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_4wOebg0eseF7WWmDsfsw_180.JPG: 480x640 (no detections), 345.3ms
Speed: 1.0ms preprocess, 345.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_4wOebg0eseF7WWmDsfsw_270.JPG: 480x640 (no detections), 275.0ms
Speed: 1.1ms preprocess, 275.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_5JOZ4JhI73kZnO-1Tbhw_0.JPG: 480x640 (no detections), 347.5ms
Speed: 1.0ms preprocess, 347.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_5JOZ4JhI73kZnO-1Tbhw_90.JPG: 480x640 (no detections), 280.2ms
Speed: 1.1ms preprocess, 280.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_5JOZ4JhI73kZnO-1Tbhw_180.JPG: 480x640 (no detections), 276.0ms
Speed: 1.3ms preprocess, 276.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_5JOZ4JhI73kZnO-1Tbhw_270.JPG: 480x640 (no detections), 352.5ms
Speed: 1.0ms preprocess, 352.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_8JZMnG9AoCC4QJdVuYxw_0.JPG: 480x640 (no detections), 280.0ms
Speed: 1.1ms preprocess, 280.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_8JZMnG9AoCC4QJdVuYxw_90.JPG: 480x640 (no detections), 278.8ms
Speed: 1.0ms preprocess, 278.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_8JZMnG9AoCC4QJdVuYxw_180.JPG: 480x640 (no detections), 273.2ms
Speed: 1.2ms preprocess, 273.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_8JZMnG9AoCC4QJdVuYxw_270.JPG: 480x640 (no detections), 278.6ms
Speed: 1.1ms preprocess, 278.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_9F4zmJyraudZydgUicaw_0.JPG: 480x640 (no detections), 279.8ms
Speed: 1.1ms preprocess, 279.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_9F4zmJyraudZydgUicaw_90.JPG: 480x640 (no detections), 272.6ms
Speed: 1.0ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_9F4zmJyraudZydgUicaw_180.JPG: 480x640 (no detections), 279.9ms
Speed: 1.0ms preprocess, 279.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_9F4zmJyraudZydgUicaw_270.JPG: 480x640 (no detections), 269.2ms
Speed: 1.0ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_A9EX7j-qkZntrTeiK81A_0.JPG: 480x640 (no detections), 266.7ms
Speed: 1.0ms preprocess, 266.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_A9EX7j-qkZntrTeiK81A_90.JPG: 480x640 (no detections), 273.6ms
Speed: 1.1ms preprocess, 273.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_A9EX7j-qkZntrTeiK81A_180.JPG: 480x640 (no detections), 268.6ms
Speed: 1.1ms preprocess, 268.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_A9EX7j-qkZntrTeiK81A_270.JPG: 480x640 (no detections), 269.4ms
Speed: 1.0ms preprocess, 269.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_AJ2vORrUGGW1phJvg5dQ_0.JPG: 480x640 (no detections), 266.8ms
Speed: 1.0ms preprocess, 266.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_AJ2vORrUGGW1phJvg5dQ_90.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_AJ2vORrUGGW1phJvg5dQ_180.JPG: 480x640 (no detections), 268.1ms
Speed: 1.1ms preprocess, 268.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_AJ2vORrUGGW1phJvg5dQ_270.JPG: 480x640 (no detections), 269.7ms
Speed: 1.0ms preprocess, 269.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_C1EOO11X2wnSCg6BYFIg_0.JPG: 480x640 (no detections), 270.1ms
Speed: 1.0ms preprocess, 270.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_C1EOO11X2wnSCg6BYFIg_90.JPG: 480x640 (no detections), 266.6ms
Speed: 1.1ms preprocess, 266.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_C1EOO11X2wnSCg6BYFIg_180.JPG: 480x640 (no detections), 270.4ms
Speed: 1.0ms preprocess, 270.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_C1EOO11X2wnSCg6BYFIg_270.JPG: 480x640 (no detections), 264.5ms
Speed: 1.0ms preprocess, 264.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_D5mfK09n1hZgEhng2j5g_0.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_D5mfK09n1hZgEhng2j5g_90.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_D5mfK09n1hZgEhng2j5g_180.JPG: 480x640 (no detections), 274.4ms
Speed: 1.1ms preprocess, 274.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_D5mfK09n1hZgEhng2j5g_270.JPG: 480x640 (no detections), 267.9ms
Speed: 1.0ms preprocess, 267.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_Ee2xxyuIKzkrWT5Mni3A_0.JPG: 480x640 (no detections), 270.2ms
Speed: 1.0ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_Ee2xxyuIKzkrWT5Mni3A_90.JPG: 480x640 (no detections), 269.2ms
Speed: 1.1ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_Ee2xxyuIKzkrWT5Mni3A_180.JPG: 480x640 (no detections), 268.3ms
Speed: 1.1ms preprocess, 268.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_Ee2xxyuIKzkrWT5Mni3A_270.JPG: 480x640 (no detections), 271.0ms
Speed: 1.1ms preprocess, 271.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_GIfhs7jWGF7sM_dujNOg_0.JPG: 480x640 (no detections), 268.6ms
Speed: 1.1ms preprocess, 268.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_GIfhs7jWGF7sM_dujNOg_90.JPG: 480x640 (no detections), 271.2ms

Speed: 1.1ms preprocess, 271.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_GIfhs7jWGF7sM_dujNOg_180.JPG: 480x640 (no detections), 268.1ms
Speed: 1.0ms preprocess, 268.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_GIfhs7jWGF7sM_dujNOg_270.JPG: 480x640 (no detections), 268.2ms
Speed: 1.1ms preprocess, 268.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_I5119nGEL0sMHgvqsf-g_0.JPG: 480x640 (no detections), 266.2ms
Speed: 1.0ms preprocess, 266.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_I5119nGEL0sMHgvqsf-g_90.JPG: 480x640 (no detections), 269.9ms
Speed: 1.0ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_I5119nGEL0sMHgvqsf-g_180.JPG: 480x640 (no detections), 271.2ms
Speed: 1.0ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_I5119nGEL0sMHgvqsf-g_270.JPG: 480x640 (no detections), 278.9ms
Speed: 1.4ms preprocess, 278.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_I7FEpM5PC6BMXAcdOQ9g_0.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_I7FEpM5PC6BMXAcdOQ9g_90.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_I7FEpM5PC6BMXAcdOQ9g_180.JPG: 480x640 (no detections), 266.4ms
Speed: 1.1ms preprocess, 266.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_I7FEpM5PC6BMXAcdOQ9g_270.JPG: 480x640 (no detections), 269.5ms
Speed: 1.1ms preprocess, 269.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_JCWiEXURdoGpXcDDpriw_0.JPG: 480x640 (no detections), 268.2ms
Speed: 1.0ms preprocess, 268.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_JCWiEXURdoGpXcDDpriw_90.JPG: 480x640 (no detections), 270.4ms
Speed: 1.0ms preprocess, 270.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_JCWiEXURdoGpXcDDpriw_180.JPG: 480x640 (no detections), 267.3ms
Speed: 1.0ms preprocess, 267.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_JCWiEXURdoGpXcDDpriw_270.JPG: 480x640 (no detections), 270.0ms
Speed: 1.0ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_JzI8r1rdc1qNaDRWL0mw_0.JPG: 480x640 (no detections), 277.2ms
Speed: 1.0ms preprocess, 277.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_JzI8r1rdc1qNaDRWL0mw_90.JPG: 480x640 (no detections), 268.1ms
Speed: 1.0ms preprocess, 268.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_JzI8r1rdc1qNaDRWL0mw_180.JPG: 480x640 (no detections), 268.9ms
Speed: 1.0ms preprocess, 268.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_JzI8r1rdc1qNaDRWL0mw_270.JPG: 480x640 (no detections), 270.9ms
Speed: 1.0ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_N3nUqqH2un1LUErtdalw_0.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_N3nUqqH2un1LUErtdalw_90.JPG: 480x640 1 Waste, 270.0ms
Speed: 1.2ms preprocess, 270.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_N3nUqqH2un1LUErtdalw_180.JPG: 480x640 (no detections), 283.1ms
Speed: 1.1ms preprocess, 283.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_N3nUqqH2un1LUErtdalw_270.JPG: 480x640 (no detections), 278.8ms
Speed: 1.2ms preprocess, 278.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_Nw6fwI0sgV5PcMUyzqqw_0.JPG: 480x640 (no detections), 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_Nw6fwI0sgV5PcMUyzqqw_90.JPG: 480x640 (no detections), 272.0ms
Speed: 1.1ms preprocess, 272.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_Nw6fwI0sgV5PcMUyzqqw_180.JPG: 480x640 (no detections), 270.5ms
Speed: 1.6ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_Nw6fwI0sgV5PcMUyzqqw_270.JPG: 480x640 (no detections), 270.2ms
Speed: 1.0ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_Nwr8XCcrxm2frJ3G-7Ww_0.JPG: 480x640 (no detections), 267.5ms
Speed: 1.1ms preprocess, 267.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_Nwr8XCcrxm2frJ3G-7Ww_90.JPG: 480x640 (no detections), 267.5ms
Speed: 1.0ms preprocess, 267.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_Nwr8XCcrxm2frJ3G-7Ww_180.JPG: 480x640 (no detections), 268.7ms
Speed: 1.1ms preprocess, 268.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_Nwr8XCcrxm2frJ3G-7Ww_270.JPG: 480x640 (no detections), 267.2ms
Speed: 1.1ms preprocess, 267.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_PXn1xADueI6-nTJfOqoQ_0.JPG: 480x640 (no detections), 270.0ms
Speed: 1.0ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_PXn1xADueI6-nTJfOqoQ_90.JPG: 480x640 (no detections), 270.8ms
Speed: 1.0ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_PXn1xADueI6-nTJfOqoQ_180.JPG: 480x640 (no detections), 271.2ms
Speed: 1.0ms preprocess, 271.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_PXn1xADueI6-nTJfOqoQ_270.JPG: 480x640 (no detections), 268.8ms
Speed: 1.1ms preprocess, 268.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_Pb3gpawZYHviOaa7Al4w_0.JPG: 480x640 (no detections), 277.6ms
Speed: 1.1ms preprocess, 277.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_Pb3gpawZYHviOaa7Al4w_90.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_Pb3gpawZYHviOaa7Al4w_180.JPG: 480x640 (no detections), 283.3ms
Speed: 1.1ms preprocess, 283.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_Pb3gpawZYHviOaa7Al4w_270.JPG: 480x640 (no detections), 271.5ms
Speed: 1.2ms preprocess, 271.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_cIsclT_NgV03wOnl4yzA_0.JPG: 480x640 (no detections), 273.7ms
Speed: 1.0ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_cIsclT_NgV03wOnl4yzA_90.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_cIsclT_NgV03wOnl4yzA_180.JPG: 480x640 (no detections), 268.9ms
Speed: 1.0ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_cIsclT_NgV03wOnl4yzA_270.JPG: 480x640 (no detections), 284.1ms
Speed: 1.0ms preprocess, 284.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_gFJh2VnFASqQXC0PF2Vg_0.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_gFJh2VnFASqQXC0PF2Vg_90.JPG: 480x640 (no detections), 279.9ms
Speed: 1.0ms preprocess, 279.9ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_gFJh2VnFASqQXC0PF2Vg_180.JPG: 480x640 (no detections), 276.8ms
Speed: 1.2ms preprocess, 276.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_gFJh2VnFASqQXC0PF2Vg_270.JPG: 480x640 (no detections), 268.4ms
Speed: 1.1ms preprocess, 268.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_lbFLGJTVgy1P47gN505A_0.JPG: 480x640 (no detections), 271.1ms
Speed: 1.0ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_lbFLGJTVgy1P47gN505A_90.JPG: 480x640 (no detections), 268.2ms
Speed: 1.0ms preprocess, 268.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_lbFLGJTVgy1P47gN505A_180.JPG: 480x640 (no detections), 269.5ms
Speed: 1.0ms preprocess, 269.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_lbFLGJTVgy1P47gN505A_270.JPG: 480x640 (no detections), 278.7ms
Speed: 1.0ms preprocess, 278.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_li2dTu0fIWLTHXVBvyvA_0.JPG: 480x640 (no detections), 266.7ms
Speed: 1.0ms preprocess, 266.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_li2dTu0fIWLTHXVBvyvA_90.JPG: 480x640 (no detections), 266.2ms
Speed: 1.1ms preprocess, 266.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_li2dTu0fIWLTHXVBvyvA_180.JPG: 480x640 (no detections), 266.9ms
Speed: 1.0ms preprocess, 266.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_li2dTu0fIWLTHXVBvyvA_270.JPG: 480x640 (no detections), 263.8ms
Speed: 1.0ms preprocess, 263.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_m06ibn9cn2zwLAJQs8cA_0.JPG: 480x640 (no detections), 268.8ms
Speed: 1.4ms preprocess, 268.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_m06ibn9cn2zwLAJQs8cA_90.JPG: 480x640 (no detections), 268.2ms
Speed: 1.1ms preprocess, 268.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_m06ibn9cn2zwLAJQs8cA_180.JPG: 480x640 (no detections), 269.8ms
Speed: 1.0ms preprocess, 269.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_m06ibn9cn2zwLAJQs8cA_270.JPG: 480x640 (no detections), 268.0ms
Speed: 1.2ms preprocess, 268.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_m7oiBGu-gqsnyVtCQ1Ng_0.JPG: 480x640 (no detections), 269.2ms
Speed: 1.2ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_m7oiBGu-gqsnyVtCQ1Ng_90.JPG: 480x640 (no detections), 275.8ms
Speed: 1.1ms preprocess, 275.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_m7oiBGu-gqsnyVtCQ1Ng_180.JPG: 480x640 (no detections), 275.5ms
Speed: 1.0ms preprocess, 275.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_m7oiBGu-gqsnyVtCQ1Ng_270.JPG: 480x640 (no detections), 273.8ms
Speed: 1.0ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_pS9n3Woh6dMpvTjxGQrw_0.JPG: 480x640 (no detections), 269.5ms
Speed: 1.1ms preprocess, 269.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_pS9n3Woh6dMpvTjxGQrw_90.JPG: 480x640 (no detections), 273.7ms
Speed: 1.0ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_pS9n3Woh6dMpvTjxGQrw_180.JPG: 480x640 (no detections), 272.4ms
Speed: 1.2ms preprocess, 272.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_pS9n3Woh6dMpvTjxGQrw_270.JPG: 480x640 (no detections), 268.9ms
Speed: 1.0ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_qKqbrttDcm_6qyYhQlsQ_0.JPG: 480x640 (no detections), 269.9ms

Speed: 1.1ms preprocess, 269.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_qKqbrttDcm_6qyYhQlsQ_90.JPG: 480x640 (no detections), 268.0ms
Speed: 1.1ms preprocess, 268.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_qKqbrttDcm_6qyYhQlsQ_180.JPG: 480x640 (no detections), 274.7ms
Speed: 1.0ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_qKqbrttDcm_6qyYhQlsQ_270.JPG: 480x640 (no detections), 273.2ms
Speed: 1.1ms preprocess, 273.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_sCnS9E38zD33ZvHIbT_Q_0.JPG: 480x640 (no detections), 274.9ms
Speed: 1.1ms preprocess, 274.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_sCnS9E38zD33ZvHIbT_Q_90.JPG: 480x640 (no detections), 269.2ms
Speed: 1.1ms preprocess, 269.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_sCnS9E38zD33ZvHIbT_Q_180.JPG: 480x640 (no detections), 276.3ms
Speed: 1.0ms preprocess, 276.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_sCnS9E38zD33ZvHIbT_Q_270.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_srLrscs3ZWP2mtfuPI_A_0.JPG: 480x640 (no detections), 265.8ms
Speed: 1.1ms preprocess, 265.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_srLrscs3ZWP2mtfuPI_A_90.JPG: 480x640 (no detections), 268.2ms
Speed: 1.0ms preprocess, 268.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_srLrscs3ZWP2mtfuPI_A_180.JPG: 480x640 (no detections), 266.8ms
Speed: 1.2ms preprocess, 266.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_srLrscs3ZWP2mtfuPI_A_270.JPG: 480x640 (no detections), 266.5ms
Speed: 1.1ms preprocess, 266.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_t0HGCXyx3u0PUhvzcMfA_0.JPG: 480x640 (no detections), 271.7ms
Speed: 1.0ms preprocess, 271.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_t0HGCXyx3u0PUhvzcMfA_90.JPG: 480x640 (no detections), 268.4ms
Speed: 1.0ms preprocess, 268.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_t0HGCXyx3u0PUhvzcMfA_180.JPG: 480x640 (no detections), 269.8ms
Speed: 1.0ms preprocess, 269.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_t0HGCXyx3u0PUhvzcMfA_270.JPG: 480x640 (no detections), 279.6ms
Speed: 1.0ms preprocess, 279.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_tecltCCtF_b7AFWtmdXw_0.JPG: 480x640 (no detections), 270.9ms
Speed: 1.1ms preprocess, 270.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_tecltCCtF_b7AFWtmdXw_90.JPG: 480x640 (no detections), 271.0ms
Speed: 1.0ms preprocess, 271.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_tecltCCtF_b7AFWtmdXw_180.JPG: 480x640 2 Wastes, 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_tecltCCtF_b7AFWtmdXw_270.JPG: 480x640 1 Waste, 270.6ms
Speed: 1.0ms preprocess, 270.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_ztC0Mk56sSAoriRGm1XA_0.JPG: 480x640 (no detections), 269.1ms
Speed: 1.1ms preprocess, 269.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_ztC0Mk56sSAoriRGm1XA_90.JPG: 480x640 (no detections), 268.3ms
Speed: 1.0ms preprocess, 268.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_ztC0Mk56sSAoriRGm1XA_180.JPG: 480x640 (no detections), 271.4ms
Speed: 1.0ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/_/y_ztC0Mk56sSAoriRGm1XA_270.JPG: 480x640 (no detections), 268.6ms
Speed: 1.1ms preprocess, 268.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/ya1-rH6MbSm04RjYvppWmA_0.JPG: 480x640 (no detections), 268.2ms
Speed: 1.0ms preprocess, 268.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/ya1-rH6MbSm04RjYvppWmA_90.JPG: 480x640 (no detections), 267.7ms
Speed: 1.0ms preprocess, 267.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/ya1-rH6MbSm04RjYvppWmA_180.JPG: 480x640 (no detections), 269.9ms
Speed: 1.2ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/ya1-rH6MbSm04RjYvppWmA_270.JPG: 480x640 (no detections), 281.1ms
Speed: 1.1ms preprocess, 281.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/ya5LZuM-rj4I9If9xUqMjA_0.JPG: 480x640 (no detections), 272.3ms
Speed: 1.7ms preprocess, 272.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/ya5LZuM-rj4I9If9xUqMjA_90.JPG: 480x640 (no detections), 278.9ms
Speed: 1.2ms preprocess, 278.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/ya5LZuM-rj4I9If9xUqMjA_180.JPG: 480x640 (no detections), 270.9ms
Speed: 1.1ms preprocess, 270.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/ya5LZuM-rj4I9If9xUqMjA_270.JPG: 480x640 (no detections), 271.5ms
Speed: 1.1ms preprocess, 271.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/ya7colSb299Ma2rEQamCPg_0.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/ya7colSb299Ma2rEQamCPg_90.JPG: 480x640 (no detections), 278.7ms
Speed: 1.4ms preprocess, 278.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/ya7colSb299Ma2rEQamCPg_180.JPG: 480x640 (no detections), 272.4ms
Speed: 1.0ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/ya7colSb299Ma2rEQamCPg_270.JPG: 480x640 (no detections), 271.5ms
Speed: 1.1ms preprocess, 271.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/ya8908Pii_HAp2seFSeAAQ_0.JPG: 480x640 (no detections), 269.3ms
Speed: 1.1ms preprocess, 269.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/ya8908Pii_HAp2seFSeAAQ_90.JPG: 480x640 (no detections), 268.7ms
Speed: 1.0ms preprocess, 268.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/ya8908Pii_HAp2seFSeAAQ_180.JPG: 480x640 1 Waste, 270.5ms
Speed: 1.0ms preprocess, 270.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/ya8908Pii_HAp2seFSeAAQ_270.JPG: 480x640 (no detections), 272.9ms
Speed: 1.0ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yaBVrDzaSe35rTA-_tLooA_0.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yaBVrDzaSe35rTA-_tLooA_90.JPG: 480x640 (no detections), 280.2ms
Speed: 1.1ms preprocess, 280.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yaBVrDzaSe35rTA-_tLooA_180.JPG: 480x640 (no detections), 268.1ms
Speed: 1.1ms preprocess, 268.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yaBVrDzaSe35rTA-_tLooA_270.JPG: 480x640 (no detections), 270.3ms
Speed: 1.1ms preprocess, 270.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yaDnxQjfMiBJLoUoTzpNNA_0.JPG: 480x640 (no detections), 270.9ms
Speed: 1.1ms preprocess, 270.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yaDnxQjfMiBJLoUoTzpNNA_90.JPG: 480x640 (no detections), 270.6ms
Speed: 1.0ms preprocess, 270.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yaDnxQjfMiBJLoUoTzpNNA_180.JPG: 480x640 (no detections), 267.0ms
Speed: 1.1ms preprocess, 267.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yaDnxQjfMiBJLoUoTzpNNA_270.JPG: 480x640 (no detections), 269.6ms
Speed: 1.0ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yaEKlyrZiMwuxkmxjucrqg_0.JPG: 480x640 (no detections), 267.9ms
Speed: 1.0ms preprocess, 267.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yaEKlyrZiMwuxkmxjucrqg_90.JPG: 480x640 (no detections), 269.8ms
Speed: 1.2ms preprocess, 269.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yaEKlyrZiMwuxkmxjucrqg_180.JPG: 480x640 (no detections), 270.8ms
Speed: 1.0ms preprocess, 270.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yaEKlyrZiMwuxkmxjucrqg_270.JPG: 480x640 (no detections), 269.0ms
Speed: 1.1ms preprocess, 269.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yaIjONO0nvcxN47Mc9OSFQ_0.JPG: 480x640 (no detections), 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yaIjONO0nvcxN47Mc9OSFQ_90.JPG: 480x640 1 Waste, 269.8ms
Speed: 1.1ms preprocess, 269.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yaIjONO0nvcxN47Mc9OSFQ_180.JPG: 480x640 (no detections), 268.3ms
Speed: 1.0ms preprocess, 268.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yaIjONO0nvcxN47Mc9OSFQ_270.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yaKBdb45RqPl2Xsp8WKlSQ_0.JPG: 480x640 (no detections), 278.1ms
Speed: 1.1ms preprocess, 278.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yaKBdb45RqPl2Xsp8WKlSQ_90.JPG: 480x640 (no detections), 268.1ms
Speed: 1.0ms preprocess, 268.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yaKBdb45RqPl2Xsp8WKlSQ_180.JPG: 480x640 1 Waste, 272.0ms
Speed: 1.0ms preprocess, 272.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yaKBdb45RqPl2Xsp8WKlSQ_270.JPG: 480x640 (no detections), 275.3ms
Speed: 1.0ms preprocess, 275.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yaLMojwte1k79W_R6zW31A_0.JPG: 480x640 (no detections), 269.8ms
Speed: 1.2ms preprocess, 269.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yaLMojwte1k79W_R6zW31A_90.JPG: 480x640 (no detections), 272.6ms
Speed: 1.0ms preprocess, 272.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yaLMojwte1k79W_R6zW31A_180.JPG: 480x640 (no detections), 264.8ms
Speed: 1.0ms preprocess, 264.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yaLMojwte1k79W_R6zW31A_270.JPG: 480x640 1 Waste, 274.1ms
Speed: 1.0ms preprocess, 274.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yaN-JbTBeykJfsYKLfU3RQ_0.JPG: 480x640 (no detections), 272.1ms
Speed: 1.1ms preprocess, 272.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yaN-JbTBeykJfsYKLfU3RQ_90.JPG: 480x640 1 Waste, 269.3ms
Speed: 1.0ms preprocess, 269.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yaN-JbTBeykJfsYKLfU3RQ_180.JPG: 480x640 (no detections), 270.9ms
Speed: 1.2ms preprocess, 270.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yaN-JbTBeykJfsYKLfU3RQ_270.JPG: 480x640 (no detections), 271.3ms

Speed: 1.1ms preprocess, 271.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yaQt6oWY6n6A665Q0M-LuA_0.JPG: 480x640 (no detections), 303.9ms
Speed: 1.3ms preprocess, 303.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yaQt6oWY6n6A665Q0M-LuA_90.JPG: 480x640 (no detections), 285.8ms
Speed: 1.1ms preprocess, 285.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yaQt6oWY6n6A665Q0M-LuA_180.JPG: 480x640 (no detections), 279.6ms
Speed: 1.1ms preprocess, 279.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yaQt6oWY6n6A665Q0M-LuA_270.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yaSw5XPQL27o1aCY4IAvtw_0.JPG: 480x640 (no detections), 264.5ms
Speed: 1.0ms preprocess, 264.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yaSw5XPQL27o1aCY4IAvtw_90.JPG: 480x640 (no detections), 269.9ms
Speed: 1.0ms preprocess, 269.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yaSw5XPQL27o1aCY4IAvtw_180.JPG: 480x640 (no detections), 276.9ms
Speed: 1.1ms preprocess, 276.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yaSw5XPQL27o1aCY4IAvtw_270.JPG: 480x640 (no detections), 279.9ms
Speed: 1.2ms preprocess, 279.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yaW_X7YMEii9j3Arw4Xp3g_0.JPG: 480x640 (no detections), 270.8ms
Speed: 1.7ms preprocess, 270.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yaW_X7YMEii9j3Arw4Xp3g_90.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yaW_X7YMEii9j3Arw4Xp3g_180.JPG: 480x640 (no detections), 283.3ms
Speed: 1.1ms preprocess, 283.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yaW_X7YMEii9j3Arw4Xp3g_270.JPG: 480x640 (no detections), 281.4ms
Speed: 1.1ms preprocess, 281.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/ya_wRe3Jz5fSwrEV3kAqWQ_0.JPG: 480x640 (no detections), 295.9ms
Speed: 1.6ms preprocess, 295.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/ya_wRe3Jz5fSwrEV3kAqWQ_90.JPG: 480x640 (no detections), 280.2ms
Speed: 1.2ms preprocess, 280.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/ya_wRe3Jz5fSwrEV3kAqWQ_180.JPG: 480x640 (no detections), 285.6ms
Speed: 1.4ms preprocess, 285.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/ya_wRe3Jz5fSwrEV3kAqWQ_270.JPG: 480x640 (no detections), 300.7ms
Speed: 1.2ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yab_sq5pseIxxy-xOML1CQ_0.JPG: 480x640 (no detections), 297.4ms
Speed: 1.5ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yab_sq5pseIxxy-xOML1CQ_90.JPG: 480x640 (no detections), 284.2ms
Speed: 1.0ms preprocess, 284.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yab_sq5pseIxxy-xOML1CQ_180.JPG: 480x640 (no detections), 273.4ms
Speed: 1.2ms preprocess, 273.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yab_sq5pseIxxy-xOML1CQ_270.JPG: 480x640 (no detections), 278.0ms
Speed: 1.2ms preprocess, 278.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yacS6m7j22q3QpG2HT5soA_0.JPG: 480x640 (no detections), 287.8ms
Speed: 1.1ms preprocess, 287.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yacS6m7j22q3QpG2HT5soA_90.JPG: 480x640 (no detections), 289.7ms
Speed: 1.7ms preprocess, 289.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yacS6m7j22q3QpG2HT5soA_180.JPG: 480x640 (no detections), 276.8ms
Speed: 1.1ms preprocess, 276.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yacS6m7j22q3QpG2HT5soA_270.JPG: 480x640 (no detections), 295.0ms
Speed: 1.0ms preprocess, 295.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yacX5a8-A_Y3MJ8zOuqfdA_0.JPG: 480x640 (no detections), 283.1ms
Speed: 1.3ms preprocess, 283.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yacX5a8-A_Y3MJ8zOuqfdA_90.JPG: 480x640 (no detections), 270.2ms
Speed: 1.2ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yacX5a8-A_Y3MJ8zOuqfdA_180.JPG: 480x640 (no detections), 276.9ms
Speed: 1.2ms preprocess, 276.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yacX5a8-A_Y3MJ8zOuqfdA_270.JPG: 480x640 (no detections), 273.6ms
Speed: 1.3ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yacgjJ2xl4GkVTWj4Ejcng_0.JPG: 480x640 (no detections), 276.3ms
Speed: 1.1ms preprocess, 276.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yacgjJ2xl4GkVTWj4Ejcng_90.JPG: 480x640 (no detections), 275.2ms
Speed: 1.4ms preprocess, 275.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yacgjJ2xl4GkVTWj4Ejcng_180.JPG: 480x640 (no detections), 285.0ms
Speed: 1.2ms preprocess, 285.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yacgjJ2xl4GkVTWj4Ejcng_270.JPG: 480x640 (no detections), 277.1ms
Speed: 1.3ms preprocess, 277.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yada44YGYOq3qu-U1kuRgw_0.JPG: 480x640 (no detections), 269.2ms
Speed: 1.2ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yada44YGYOq3qu-U1kuRgw_90.JPG: 480x640 (no detections), 270.4ms
Speed: 1.0ms preprocess, 270.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yada44YGYOq3qu-U1kuRgw_180.JPG: 480x640 (no detections), 268.1ms
Speed: 1.1ms preprocess, 268.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yada44YGYOq3qu-U1kuRgw_270.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yaeGfAQAnUIYY2IMVU5kIQ_0.JPG: 480x640 (no detections), 277.2ms
Speed: 1.2ms preprocess, 277.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yaeGfAQAnUIYY2IMVU5kIQ_90.JPG: 480x640 (no detections), 274.6ms
Speed: 1.3ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yaeGfAQAnUIYY2IMVU5kIQ_180.JPG: 480x640 (no detections), 270.9ms
Speed: 1.1ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yaeGfAQAnUIYY2IMVU5kIQ_270.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yahBNRjgt7szGZ2rMNhDhQ_0.JPG: 480x640 (no detections), 271.9ms
Speed: 1.3ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yahBNRjgt7szGZ2rMNhDhQ_90.JPG: 480x640 (no detections), 267.8ms
Speed: 1.3ms preprocess, 267.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yahBNRjgt7szGZ2rMNhDhQ_180.JPG: 480x640 (no detections), 269.5ms
Speed: 1.1ms preprocess, 269.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yahBNRjgt7szGZ2rMNhDhQ_270.JPG: 480x640 (no detections), 265.8ms
Speed: 1.1ms preprocess, 265.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yatwir8LKvh0ommbHALA5w_0.JPG: 480x640 (no detections), 270.9ms
Speed: 1.1ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yatwir8LKvh0ommbHALA5w_90.JPG: 480x640 (no detections), 276.1ms
Speed: 1.1ms preprocess, 276.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yatwir8LKvh0ommbHALA5w_180.JPG: 480x640 (no detections), 269.4ms
Speed: 1.0ms preprocess, 269.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yatwir8LKvh0ommbHALA5w_270.JPG: 480x640 (no detections), 266.1ms
Speed: 1.0ms preprocess, 266.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yau36IV_MyJd4DT0fN-DDw_0.JPG: 480x640 (no detections), 268.4ms
Speed: 1.1ms preprocess, 268.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yau36IV_MyJd4DT0fN-DDw_90.JPG: 480x640 (no detections), 284.1ms
Speed: 1.0ms preprocess, 284.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yau36IV_MyJd4DT0fN-DDw_180.JPG: 480x640 (no detections), 273.4ms
Speed: 1.1ms preprocess, 273.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yau36IV_MyJd4DT0fN-DDw_270.JPG: 480x640 (no detections), 266.6ms
Speed: 1.1ms preprocess, 266.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yaxaMdVqM-s47tmVe1pU-A_0.JPG: 480x640 (no detections), 281.2ms
Speed: 1.1ms preprocess, 281.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yaxaMdVqM-s47tmVe1pU-A_90.JPG: 480x640 (no detections), 277.9ms
Speed: 1.0ms preprocess, 277.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yaxaMdVqM-s47tmVe1pU-A_180.JPG: 480x640 (no detections), 270.3ms
Speed: 1.1ms preprocess, 270.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yaxaMdVqM-s47tmVe1pU-A_270.JPG: 480x640 (no detections), 271.0ms
Speed: 1.0ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yayVTtF2I7LZATy0xhh3Tg_0.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yayVTtF2I7LZATy0xhh3Tg_90.JPG: 480x640 (no detections), 271.8ms
Speed: 1.2ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yayVTtF2I7LZATy0xhh3Tg_180.JPG: 480x640 (no detections), 270.7ms
Speed: 1.0ms preprocess, 270.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/a/yayVTtF2I7LZATy0xhh3Tg_270.JPG: 480x640 (no detections), 281.7ms
Speed: 1.1ms preprocess, 281.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yb3QOyB9sPTU06g4w4-mbg_0.JPG: 480x640 (no detections), 276.8ms
Speed: 1.1ms preprocess, 276.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yb3QOyB9sPTU06g4w4-mbg_90.JPG: 480x640 (no detections), 270.7ms
Speed: 1.0ms preprocess, 270.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yb3QOyB9sPTU06g4w4-mbg_180.JPG: 480x640 (no detections), 270.2ms
Speed: 1.0ms preprocess, 270.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yb3QOyB9sPTU06g4w4-mbg_270.JPG: 480x640 (no detections), 273.3ms
Speed: 1.0ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yb4qHKPXLHJVyR06xfawwA_0.JPG: 480x640 (no detections), 270.3ms
Speed: 1.1ms preprocess, 270.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yb4qHKPXLHJVyR06xfawwA_90.JPG: 480x640 (no detections), 282.0ms
Speed: 1.0ms preprocess, 282.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yb4qHKPXLHJVyR06xfawwA_180.JPG: 480x640 (no detections), 273.0ms

Speed: 1.5ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yb4qHKPXLHJVyR06xfawwA_270.JPG: 480x640 (no detections), 267.5ms
Speed: 1.2ms preprocess, 267.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybAPQCqbCIrYJiG8A-WKWA_0.JPG: 480x640 (no detections), 280.5ms
Speed: 1.0ms preprocess, 280.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybAPQCqbCIrYJiG8A-WKWA_90.JPG: 480x640 (no detections), 273.2ms
Speed: 1.4ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybAPQCqbCIrYJiG8A-WKWA_180.JPG: 480x640 (no detections), 275.6ms
Speed: 1.1ms preprocess, 275.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybAPQCqbCIrYJiG8A-WKWA_270.JPG: 480x640 (no detections), 271.4ms
Speed: 1.0ms preprocess, 271.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybFFcYM4RRGkwNODBnd9tw_0.JPG: 480x640 (no detections), 277.5ms
Speed: 1.2ms preprocess, 277.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybFFcYM4RRGkwNODBnd9tw_90.JPG: 480x640 (no detections), 274.5ms
Speed: 1.0ms preprocess, 274.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybFFcYM4RRGkwNODBnd9tw_180.JPG: 480x640 (no detections), 276.1ms
Speed: 1.1ms preprocess, 276.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybFFcYM4RRGkwNODBnd9tw_270.JPG: 480x640 (no detections), 268.5ms
Speed: 1.0ms preprocess, 268.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybHLIq2oraqcSNuVVCaaLQ_0.JPG: 480x640 (no detections), 272.1ms
Speed: 1.0ms preprocess, 272.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybHLIq2oraqcSNuVVCaaLQ_90.JPG: 480x640 (no detections), 269.5ms
Speed: 1.1ms preprocess, 269.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybHLIq2oraqcSNuVVCaaLQ_180.JPG: 480x640 (no detections), 272.0ms
Speed: 1.1ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybHLIq2oraqcSNuVVCaaLQ_270.JPG: 480x640 (no detections), 274.4ms
Speed: 1.1ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybJ2rBahEvQmNYOBzpziQg_0.JPG: 480x640 (no detections), 281.0ms
Speed: 1.3ms preprocess, 281.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybJ2rBahEvQmNYOBzpziQg_90.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybJ2rBahEvQmNYOBzpziQg_180.JPG: 480x640 (no detections), 272.9ms
Speed: 1.0ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybJ2rBahEvQmNYOBzpziQg_270.JPG: 480x640 (no detections), 269.4ms
Speed: 1.0ms preprocess, 269.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybNsXgE2QP977MFSsPE1PA_0.JPG: 480x640 (no detections), 269.4ms
Speed: 1.0ms preprocess, 269.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybNsXgE2QP977MFSsPE1PA_90.JPG: 480x640 (no detections), 284.5ms
Speed: 1.0ms preprocess, 284.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybNsXgE2QP977MFSsPE1PA_180.JPG: 480x640 (no detections), 274.5ms
Speed: 1.0ms preprocess, 274.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybNsXgE2QP977MFSsPE1PA_270.JPG: 480x640 (no detections), 271.4ms
Speed: 1.6ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybRQ__6WFg-k7Pc0J5w1VA_0.JPG: 480x640 (no detections), 275.4ms
Speed: 1.0ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybRQ__6WFg-k7Pc0J5w1VA_90.JPG: 480x640 (no detections), 280.6ms
Speed: 1.2ms preprocess, 280.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybRQ__6WFg-k7Pc0J5w1VA_180.JPG: 480x640 (no detections), 295.7ms
Speed: 1.2ms preprocess, 295.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybRQ__6WFg-k7Pc0J5w1VA_270.JPG: 480x640 (no detections), 280.2ms
Speed: 1.3ms preprocess, 280.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybRWoee9H7ZV97Xvm9oGug_0.JPG: 480x640 (no detections), 275.2ms
Speed: 1.3ms preprocess, 275.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybRWoee9H7ZV97Xvm9oGug_90.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybRWoee9H7ZV97Xvm9oGug_180.JPG: 480x640 1 Waste, 268.5ms
Speed: 1.0ms preprocess, 268.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybRWoee9H7ZV97Xvm9oGug_270.JPG: 480x640 (no detections), 271.4ms
Speed: 1.0ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybS_RL1LK54QIDu0OaOVMg_0.JPG: 480x640 1 Waste, 268.2ms
Speed: 1.1ms preprocess, 268.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybS_RL1LK54QIDu0OaOVMg_90.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybS_RL1LK54QIDu0OaOVMg_180.JPG: 480x640 (no detections), 278.8ms
Speed: 1.1ms preprocess, 278.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybS_RL1LK54QIDu0OaOVMg_270.JPG: 480x640 (no detections), 269.1ms
Speed: 1.0ms preprocess, 269.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybYmW02QxbHeeowEepBPZA_0.JPG: 480x640 (no detections), 268.6ms
Speed: 1.1ms preprocess, 268.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybYmW02QxbHeeowEepBPZA_90.JPG: 480x640 (no detections), 276.8ms
Speed: 1.2ms preprocess, 276.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybYmW02QxbHeeowEepBPZA_180.JPG: 480x640 (no detections), 275.5ms
Speed: 1.0ms preprocess, 275.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybYmW02QxbHeeowEepBPZA_270.JPG: 480x640 (no detections), 282.2ms
Speed: 1.1ms preprocess, 282.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybZPkmv7IKNL_yGvoaPfxw_0.JPG: 480x640 (no detections), 285.7ms
Speed: 1.2ms preprocess, 285.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybZPkmv7IKNL_yGvoaPfxw_90.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybZPkmv7IKNL_yGvoaPfxw_180.JPG: 480x640 (no detections), 272.8ms
Speed: 1.0ms preprocess, 272.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybZPkmv7IKNL_yGvoaPfxw_270.JPG: 480x640 (no detections), 273.8ms
Speed: 1.2ms preprocess, 273.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybdz1396j_JvFLyni_-c1w_0.JPG: 480x640 (no detections), 268.8ms
Speed: 1.1ms preprocess, 268.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybdz1396j_JvFLyni_-c1w_90.JPG: 480x640 1 Waste, 279.2ms
Speed: 1.0ms preprocess, 279.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybdz1396j_JvFLyni_-c1w_180.JPG: 480x640 (no detections), 270.0ms
Speed: 1.0ms preprocess, 270.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybdz1396j_JvFLyni_-c1w_270.JPG: 480x640 (no detections), 271.9ms
Speed: 1.0ms preprocess, 271.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybiQjb9hvkLsSGJuknghwA_0.JPG: 480x640 (no detections), 268.2ms
Speed: 1.0ms preprocess, 268.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybiQjb9hvkLsSGJuknghwA_90.JPG: 480x640 (no detections), 270.6ms
Speed: 1.0ms preprocess, 270.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybiQjb9hvkLsSGJuknghwA_180.JPG: 480x640 (no detections), 276.2ms
Speed: 1.0ms preprocess, 276.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybiQjb9hvkLsSGJuknghwA_270.JPG: 480x640 (no detections), 276.7ms
Speed: 1.0ms preprocess, 276.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybl2GQapUObV9118WEOrnA_0.JPG: 480x640 (no detections), 275.1ms
Speed: 1.0ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybl2GQapUObV9118WEOrnA_90.JPG: 480x640 (no detections), 282.6ms
Speed: 1.2ms preprocess, 282.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybl2GQapUObV9118WEOrnA_180.JPG: 480x640 (no detections), 299.4ms
Speed: 1.1ms preprocess, 299.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybl2GQapUObV9118WEOrnA_270.JPG: 480x640 (no detections), 353.9ms
Speed: 1.1ms preprocess, 353.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybloI0N9HAJ-wtNJc3_8gg_0.JPG: 480x640 (no detections), 282.8ms
Speed: 1.1ms preprocess, 282.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybloI0N9HAJ-wtNJc3_8gg_90.JPG: 480x640 (no detections), 286.7ms
Speed: 1.1ms preprocess, 286.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybloI0N9HAJ-wtNJc3_8gg_180.JPG: 480x640 (no detections), 274.2ms
Speed: 1.0ms preprocess, 274.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybloI0N9HAJ-wtNJc3_8gg_270.JPG: 480x640 (no detections), 276.9ms
Speed: 1.0ms preprocess, 276.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybmonlseIM_Mx7lXuOb2jw_0.JPG: 480x640 (no detections), 296.0ms
Speed: 1.2ms preprocess, 296.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybmonlseIM_Mx7lXuOb2jw_90.JPG: 480x640 (no detections), 313.3ms
Speed: 1.4ms preprocess, 313.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybmonlseIM_Mx7lXuOb2jw_180.JPG: 480x640 (no detections), 283.2ms
Speed: 1.2ms preprocess, 283.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybmonlseIM_Mx7lXuOb2jw_270.JPG: 480x640 1 Waste, 276.4ms
Speed: 1.3ms preprocess, 276.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybnF6Z_zdGbgbBhp5ase5g_0.JPG: 480x640 (no detections), 296.1ms
Speed: 1.1ms preprocess, 296.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybnF6Z_zdGbgbBhp5ase5g_90.JPG: 480x640 (no detections), 280.2ms
Speed: 1.7ms preprocess, 280.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybnF6Z_zdGbgbBhp5ase5g_180.JPG: 480x640 (no detections), 275.8ms
Speed: 1.1ms preprocess, 275.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybnF6Z_zdGbgbBhp5ase5g_270.JPG: 480x640 (no detections), 282.2ms
Speed: 1.0ms preprocess, 282.2ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybnR2ndRZWyyh34s_0ZrCw_0.JPG: 480x640 (no detections), 272.3ms
Speed: 1.0ms preprocess, 272.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybnR2ndRZWyyh34s_0ZrCw_90.JPG: 480x640 (no detections), 280.1ms

Speed: 1.1ms preprocess, 280.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybnR2ndRZWyyh34s_0ZrCw_180.JPG: 480x640 (no detections), 341.8ms
Speed: 1.0ms preprocess, 341.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybnR2ndRZWyyh34s_0ZrCw_270.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybp_-chDDfrpTOpTEjinKA_0.JPG: 480x640 1 Waste, 282.5ms
Speed: 1.2ms preprocess, 282.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybp_-chDDfrpTOpTEjinKA_90.JPG: 480x640 (no detections), 297.2ms
Speed: 1.0ms preprocess, 297.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybp_-chDDfrpTOpTEjinKA_180.JPG: 480x640 (no detections), 272.0ms
Speed: 1.2ms preprocess, 272.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybp_-chDDfrpTOpTEjinKA_270.JPG: 480x640 1 Waste, 271.5ms
Speed: 1.1ms preprocess, 271.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybqoHjXp1ZMcC0tkqhio_w_0.JPG: 480x640 (no detections), 272.4ms
Speed: 1.0ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybqoHjXp1ZMcC0tkqhio_w_90.JPG: 480x640 (no detections), 271.7ms
Speed: 1.0ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybqoHjXp1ZMcC0tkqhio_w_180.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybqoHjXp1ZMcC0tkqhio_w_270.JPG: 480x640 1 Waste, 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybsF-pFWTlr0M5S-3afiOg_0.JPG: 480x640 (no detections), 270.2ms
Speed: 1.0ms preprocess, 270.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybsF-pFWTlr0M5S-3afiOg_90.JPG: 480x640 (no detections), 275.3ms
Speed: 1.0ms preprocess, 275.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybsF-pFWTlr0M5S-3afiOg_180.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybsF-pFWTlr0M5S-3afiOg_270.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybsw96VqLpVCwkvBQ-3p4Q_0.JPG: 480x640 (no detections), 273.0ms
Speed: 1.0ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybsw96VqLpVCwkvBQ-3p4Q_90.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybsw96VqLpVCwkvBQ-3p4Q_180.JPG: 480x640 (no detections), 285.0ms
Speed: 1.1ms preprocess, 285.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybsw96VqLpVCwkvBQ-3p4Q_270.JPG: 480x640 (no detections), 282.0ms
Speed: 1.1ms preprocess, 282.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybuCO_0m90oiQLN_rFS88w_0.JPG: 480x640 (no detections), 288.8ms
Speed: 1.1ms preprocess, 288.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybuCO_0m90oiQLN_rFS88w_90.JPG: 480x640 (no detections), 305.0ms
Speed: 1.0ms preprocess, 305.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybuCO_0m90oiQLN_rFS88w_180.JPG: 480x640 (no detections), 309.5ms
Speed: 1.2ms preprocess, 309.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/ybuCO_0m90oiQLN_rFS88w_270.JPG: 480x640 (no detections), 307.0ms
Speed: 1.2ms preprocess, 307.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yby2L7xEffSTVuom9cMzCQ_0.JPG: 480x640 (no detections), 304.5ms
Speed: 1.6ms preprocess, 304.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yby2L7xEffSTVuom9cMzCQ_90.JPG: 480x640 (no detections), 283.6ms
Speed: 1.1ms preprocess, 283.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yby2L7xEffSTVuom9cMzCQ_180.JPG: 480x640 (no detections), 382.7ms
Speed: 1.3ms preprocess, 382.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yby2L7xEffSTVuom9cMzCQ_270.JPG: 480x640 (no detections), 280.2ms
Speed: 1.1ms preprocess, 280.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yby9y6uHRKFRBJeG6ncMuw_0.JPG: 480x640 (no detections), 277.7ms
Speed: 1.1ms preprocess, 277.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yby9y6uHRKFRBJeG6ncMuw_90.JPG: 480x640 (no detections), 289.8ms
Speed: 1.0ms preprocess, 289.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yby9y6uHRKFRBJeG6ncMuw_180.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/B/yby9y6uHRKFRBJeG6ncMuw_270.JPG: 480x640 (no detections), 270.4ms
Speed: 1.0ms preprocess, 270.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yc-mIr00dE1x0fqEgKwrVA_0.JPG: 480x640 (no detections), 287.5ms
Speed: 1.0ms preprocess, 287.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yc-mIr00dE1x0fqEgKwrVA_90.JPG: 480x640 (no detections), 286.6ms
Speed: 1.1ms preprocess, 286.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yc-mIr00dE1x0fqEgKwrVA_180.JPG: 480x640 (no detections), 318.0ms
Speed: 1.0ms preprocess, 318.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yc-mIr00dE1x0fqEgKwrVA_270.JPG: 480x640 (no detections), 299.6ms
Speed: 1.6ms preprocess, 299.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yc0V9SwUbwxPnUMbYv34Iw_0.JPG: 480x640 (no detections), 292.2ms
Speed: 1.4ms preprocess, 292.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yc0V9SwUbwxPnUMbYv34Iw_90.JPG: 480x640 (no detections), 280.5ms
Speed: 1.1ms preprocess, 280.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yc0V9SwUbwxPnUMbYv34Iw_180.JPG: 480x640 (no detections), 277.0ms
Speed: 1.0ms preprocess, 277.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yc0V9SwUbwxPnUMbYv34Iw_270.JPG: 480x640 (no detections), 315.4ms
Speed: 1.1ms preprocess, 315.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycA8WrpuoahcSZ7SfYXMjw_0.JPG: 480x640 (no detections), 302.5ms
Speed: 1.1ms preprocess, 302.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycA8WrpuoahcSZ7SfYXMjw_90.JPG: 480x640 (no detections), 276.6ms
Speed: 1.2ms preprocess, 276.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycA8WrpuoahcSZ7SfYXMjw_180.JPG: 480x640 (no detections), 271.4ms
Speed: 1.0ms preprocess, 271.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycA8WrpuoahcSZ7SfYXMjw_270.JPG: 480x640 (no detections), 273.6ms
Speed: 1.1ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycBUzkZHzdZJqjfXad5TQA_0.JPG: 480x640 (no detections), 289.2ms
Speed: 1.0ms preprocess, 289.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycBUzkZHzdZJqjfXad5TQA_90.JPG: 480x640 (no detections), 283.7ms
Speed: 1.0ms preprocess, 283.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycBUzkZHzdZJqjfXad5TQA_180.JPG: 480x640 (no detections), 275.3ms
Speed: 1.1ms preprocess, 275.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycBUzkZHzdZJqjfXad5TQA_270.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycBkVmsUC1Dz4PAdGIIgdQ_0.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycBkVmsUC1Dz4PAdGIIgdQ_90.JPG: 480x640 (no detections), 304.2ms
Speed: 1.1ms preprocess, 304.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycBkVmsUC1Dz4PAdGIIgdQ_180.JPG: 480x640 (no detections), 297.8ms
Speed: 1.4ms preprocess, 297.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycBkVmsUC1Dz4PAdGIIgdQ_270.JPG: 480x640 (no detections), 275.5ms
Speed: 1.2ms preprocess, 275.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycC31DskMrmT2KHdtV-8RQ_0.JPG: 480x640 (no detections), 296.0ms
Speed: 1.1ms preprocess, 296.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycC31DskMrmT2KHdtV-8RQ_90.JPG: 480x640 (no detections), 291.3ms
Speed: 1.1ms preprocess, 291.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycC31DskMrmT2KHdtV-8RQ_180.JPG: 480x640 (no detections), 289.9ms
Speed: 1.1ms preprocess, 289.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycC31DskMrmT2KHdtV-8RQ_270.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycCnDVHdgcytc3v3rclRxQ_0.JPG: 480x640 (no detections), 377.9ms
Speed: 1.0ms preprocess, 377.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycCnDVHdgcytc3v3rclRxQ_90.JPG: 480x640 (no detections), 342.5ms
Speed: 1.7ms preprocess, 342.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycCnDVHdgcytc3v3rclRxQ_180.JPG: 480x640 (no detections), 313.1ms
Speed: 1.2ms preprocess, 313.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycCnDVHdgcytc3v3rclRxQ_270.JPG: 480x640 (no detections), 297.4ms
Speed: 1.5ms preprocess, 297.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycEycwR65FE2gYwH2zTD4w_0.JPG: 480x640 1 Waste, 283.3ms
Speed: 1.0ms preprocess, 283.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycEycwR65FE2gYwH2zTD4w_90.JPG: 480x640 (no detections), 284.9ms
Speed: 1.2ms preprocess, 284.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycEycwR65FE2gYwH2zTD4w_180.JPG: 480x640 (no detections), 274.7ms
Speed: 1.5ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycEycwR65FE2gYwH2zTD4w_270.JPG: 480x640 (no detections), 276.5ms
Speed: 1.1ms preprocess, 276.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycF0Kl0mZ1o9qZvUZH6VHA_0.JPG: 480x640 (no detections), 273.6ms
Speed: 1.0ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycF0Kl0mZ1o9qZvUZH6VHA_90.JPG: 480x640 (no detections), 276.0ms
Speed: 1.0ms preprocess, 276.0ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycF0Kl0mZ1o9qZvUZH6VHA_180.JPG: 480x640 1 Waste, 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycF0Kl0mZ1o9qZvUZH6VHA_270.JPG: 480x640 (no detections), 281.8ms
Speed: 1.1ms preprocess, 281.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycHwxSV1NW2VRQUAki2r_Q_0.JPG: 480x640 (no detections), 273.7ms

Speed: 1.0ms preprocess, 273.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycHwxSV1NW2VRQUAki2r_Q_90.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycHwxSV1NW2VRQUAki2r_Q_180.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycHwxSV1NW2VRQUAki2r_Q_270.JPG: 480x640 (no detections), 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycIKRwstWuqvtGL2Y5zFHw_0.JPG: 480x640 (no detections), 272.3ms
Speed: 1.0ms preprocess, 272.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycIKRwstWuqvtGL2Y5zFHw_90.JPG: 480x640 1 Waste, 275.8ms
Speed: 1.0ms preprocess, 275.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycIKRwstWuqvtGL2Y5zFHw_180.JPG: 480x640 (no detections), 279.4ms
Speed: 1.0ms preprocess, 279.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycIKRwstWuqvtGL2Y5zFHw_270.JPG: 480x640 (no detections), 273.3ms
Speed: 1.0ms preprocess, 273.3ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycIWf8wnIXySNw6FHlmaXg_0.JPG: 480x640 (no detections), 276.5ms
Speed: 1.0ms preprocess, 276.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycIWf8wnIXySNw6FHlmaXg_90.JPG: 480x640 (no detections), 275.2ms
Speed: 1.1ms preprocess, 275.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycIWf8wnIXySNw6FHlmaXg_180.JPG: 480x640 (no detections), 282.2ms
Speed: 1.0ms preprocess, 282.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycIWf8wnIXySNw6FHlmaXg_270.JPG: 480x640 (no detections), 277.2ms
Speed: 1.1ms preprocess, 277.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycRy_V4-t5vSz3iEAcTgGg_0.JPG: 480x640 (no detections), 270.4ms
Speed: 1.1ms preprocess, 270.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycRy_V4-t5vSz3iEAcTgGg_90.JPG: 480x640 (no detections), 279.5ms
Speed: 1.0ms preprocess, 279.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycRy_V4-t5vSz3iEAcTgGg_180.JPG: 480x640 (no detections), 298.0ms
Speed: 1.1ms preprocess, 298.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycRy_V4-t5vSz3iEAcTgGg_270.JPG: 480x640 (no detections), 374.4ms
Speed: 2.0ms preprocess, 374.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycTYe8pZegxn-qG21aEJyQ_0.JPG: 480x640 2 Wastes, 318.5ms
Speed: 1.1ms preprocess, 318.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycTYe8pZegxn-qG21aEJyQ_90.JPG: 480x640 (no detections), 276.4ms
Speed: 1.2ms preprocess, 276.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycTYe8pZegxn-qG21aEJyQ_180.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycTYe8pZegxn-qG21aEJyQ_270.JPG: 480x640 4 Wastes, 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yccM78DA1TjHFiKhLGFkZQ_0.JPG: 480x640 (no detections), 270.2ms
Speed: 1.0ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yccM78DA1TjHFiKhLGFkZQ_90.JPG: 480x640 1 Waste, 274.9ms
Speed: 1.1ms preprocess, 274.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yccM78DA1TjHFiKhLGFkZQ_180.JPG: 480x640 1 Waste, 269.5ms
Speed: 1.0ms preprocess, 269.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/yccM78DA1TjHFiKhLGFkZQ_270.JPG: 480x640 (no detections), 272.2ms
Speed: 1.3ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycjCPaDVVz7j69xVk6J5yg_0.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycjCPaDVVz7j69xVk6J5yg_90.JPG: 480x640 (no detections), 270.8ms
Speed: 1.0ms preprocess, 270.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycjCPaDVVz7j69xVk6J5yg_180.JPG: 480x640 (no detections), 272.7ms
Speed: 1.0ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycjCPaDVVz7j69xVk6J5yg_270.JPG: 480x640 (no detections), 273.0ms
Speed: 1.2ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycjG8d9ZKlWUju4-Y4yv4g_0.JPG: 480x640 (no detections), 277.7ms
Speed: 1.1ms preprocess, 277.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycjG8d9ZKlWUju4-Y4yv4g_90.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycjG8d9ZKlWUju4-Y4yv4g_180.JPG: 480x640 (no detections), 273.1ms
Speed: 1.1ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycjG8d9ZKlWUju4-Y4yv4g_270.JPG: 480x640 (no detections), 272.9ms
Speed: 1.0ms preprocess, 272.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycja1IEe_ktyR2flHVHFXg_0.JPG: 480x640 (no detections), 276.6ms
Speed: 1.0ms preprocess, 276.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycja1IEe_ktyR2flHVHFXg_90.JPG: 480x640 (no detections), 273.7ms
Speed: 1.0ms preprocess, 273.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycja1IEe_ktyR2flHVHFXg_180.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycja1IEe_ktyR2flHVHFXg_270.JPG: 480x640 (no detections), 271.2ms
Speed: 1.0ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycpP0uuljaoRqL7wrEgkng_0.JPG: 480x640 (no detections), 271.3ms
Speed: 1.2ms preprocess, 271.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycpP0uuljaoRqL7wrEgkng_90.JPG: 480x640 (no detections), 272.7ms
Speed: 1.0ms preprocess, 272.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycpP0uuljaoRqL7wrEgkng_180.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycpP0uuljaoRqL7wrEgkng_270.JPG: 480x640 1 Waste, 272.1ms
Speed: 1.1ms preprocess, 272.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycpls78E_NRwwp3_q3P13g_0.JPG: 480x640 1 Waste, 273.2ms
Speed: 1.0ms preprocess, 273.2ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycpls78E_NRwwp3_q3P13g_90.JPG: 480x640 (no detections), 271.0ms
Speed: 1.0ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycpls78E_NRwwp3_q3P13g_180.JPG: 480x640 (no detections), 277.0ms
Speed: 1.1ms preprocess, 277.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycpls78E_NRwwp3_q3P13g_270.JPG: 480x640 (no detections), 292.0ms
Speed: 1.1ms preprocess, 292.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycuRIJEfneUkfwDOuVozow_0.JPG: 480x640 (no detections), 272.5ms
Speed: 1.0ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycuRIJEfneUkfwDOuVozow_90.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycuRIJEfneUkfwDOuVozow_180.JPG: 480x640 (no detections), 287.7ms
Speed: 1.1ms preprocess, 287.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycuRIJEfneUkfwDOuVozow_270.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycvLx07Ulk4_1e7XeWEIpA_0.JPG: 480x640 (no detections), 291.0ms
Speed: 1.1ms preprocess, 291.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycvLx07Ulk4_1e7XeWEIpA_90.JPG: 480x640 (no detections), 275.7ms
Speed: 1.1ms preprocess, 275.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycvLx07Ulk4_1e7XeWEIpA_180.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycvLx07Ulk4_1e7XeWEIpA_270.JPG: 480x640 (no detections), 270.8ms
Speed: 1.0ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycyB3nHCFsvFXmSr27ZzqA_0.JPG: 480x640 (no detections), 271.8ms
Speed: 1.0ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycyB3nHCFsvFXmSr27ZzqA_90.JPG: 480x640 (no detections), 265.6ms
Speed: 1.0ms preprocess, 265.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycyB3nHCFsvFXmSr27ZzqA_180.JPG: 480x640 (no detections), 271.3ms
Speed: 1.0ms preprocess, 271.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/C/ycyB3nHCFsvFXmSr27ZzqA_270.JPG: 480x640 (no detections), 275.4ms
Speed: 1.0ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yd2BSVtsIx_t8iIlyRgrlw_0.JPG: 480x640 (no detections), 269.4ms
Speed: 1.0ms preprocess, 269.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yd2BSVtsIx_t8iIlyRgrlw_90.JPG: 480x640 (no detections), 275.0ms
Speed: 1.1ms preprocess, 275.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yd2BSVtsIx_t8iIlyRgrlw_180.JPG: 480x640 (no detections), 273.2ms
Speed: 1.0ms preprocess, 273.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yd2BSVtsIx_t8iIlyRgrlw_270.JPG: 480x640 (no detections), 273.6ms
Speed: 1.0ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yd2F0jsjej8hGiO-lyE9sA_0.JPG: 480x640 (no detections), 274.1ms
Speed: 1.0ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yd2F0jsjej8hGiO-lyE9sA_90.JPG: 480x640 (no detections), 272.8ms
Speed: 1.0ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yd2F0jsjej8hGiO-lyE9sA_180.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yd2F0jsjej8hGiO-lyE9sA_270.JPG: 480x640 (no detections), 274.7ms
Speed: 1.1ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yd56vXl3jXQjjEF0VSkhxw_0.JPG: 480x640 (no detections), 271.9ms
Speed: 1.0ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yd56vXl3jXQjjEF0VSkhxw_90.JPG: 480x640 (no detections), 270.5ms
Speed: 1.0ms preprocess, 270.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yd56vXl3jXQjjEF0VSkhxw_180.JPG: 480x640 (no detections), 272.8ms
Speed: 1.0ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yd56vXl3jXQjjEF0VSkhxw_270.JPG: 480x640 (no detections), 277.6ms

Speed: 1.1ms preprocess, 277.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydAQqjrFkIvG6X1yfHRCww_0.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydAQqjrFkIvG6X1yfHRCww_90.JPG: 480x640 (no detections), 270.5ms
Speed: 1.1ms preprocess, 270.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydAQqjrFkIvG6X1yfHRCww_180.JPG: 480x640 (no detections), 274.1ms
Speed: 1.0ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydAQqjrFkIvG6X1yfHRCww_270.JPG: 480x640 (no detections), 280.9ms
Speed: 1.0ms preprocess, 280.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydBs7N1GiNP7q9zJv4tuXg_0.JPG: 480x640 (no detections), 272.5ms
Speed: 1.1ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydBs7N1GiNP7q9zJv4tuXg_90.JPG: 480x640 (no detections), 272.5ms
Speed: 1.0ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydBs7N1GiNP7q9zJv4tuXg_180.JPG: 480x640 (no detections), 271.0ms
Speed: 1.1ms preprocess, 271.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydBs7N1GiNP7q9zJv4tuXg_270.JPG: 480x640 (no detections), 276.0ms
Speed: 1.0ms preprocess, 276.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydC44d6TArdm6AibDlslXA_0.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydC44d6TArdm6AibDlslXA_90.JPG: 480x640 (no detections), 276.2ms
Speed: 1.1ms preprocess, 276.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydC44d6TArdm6AibDlslXA_180.JPG: 480x640 1 Waste, 271.9ms
Speed: 1.0ms preprocess, 271.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydC44d6TArdm6AibDlslXA_270.JPG: 480x640 (no detections), 269.3ms
Speed: 1.0ms preprocess, 269.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydDizOTmuPl83Zwqnu_qUA_0.JPG: 480x640 (no detections), 273.7ms
Speed: 1.0ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydDizOTmuPl83Zwqnu_qUA_90.JPG: 480x640 (no detections), 273.2ms
Speed: 1.1ms preprocess, 273.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydDizOTmuPl83Zwqnu_qUA_180.JPG: 480x640 (no detections), 269.8ms
Speed: 1.0ms preprocess, 269.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydDizOTmuPl83Zwqnu_qUA_270.JPG: 480x640 (no detections), 269.6ms
Speed: 1.0ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydJzA6kSi4prAqrqBXPC3A_0.JPG: 480x640 (no detections), 275.8ms
Speed: 1.3ms preprocess, 275.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydJzA6kSi4prAqrqBXPC3A_90.JPG: 480x640 (no detections), 278.5ms
Speed: 1.1ms preprocess, 278.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydJzA6kSi4prAqrqBXPC3A_180.JPG: 480x640 (no detections), 269.1ms
Speed: 1.0ms preprocess, 269.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydJzA6kSi4prAqrqBXPC3A_270.JPG: 480x640 (no detections), 268.0ms
Speed: 1.1ms preprocess, 268.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydKLqEIfqeZiU0LxV4Gj1g_0.JPG: 480x640 (no detections), 278.0ms
Speed: 1.0ms preprocess, 278.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydKLqEIfqeZiU0LxV4Gj1g_90.JPG: 480x640 (no detections), 262.5ms
Speed: 1.0ms preprocess, 262.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydKLqEIfqeZiU0LxV4Gj1g_180.JPG: 480x640 (no detections), 265.0ms
Speed: 1.0ms preprocess, 265.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydKLqEIfqeZiU0LxV4Gj1g_270.JPG: 480x640 (no detections), 263.2ms
Speed: 1.0ms preprocess, 263.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydMDF67Avf6s9kcAOmi-Eg_0.JPG: 480x640 (no detections), 274.7ms
Speed: 1.0ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydMDF67Avf6s9kcAOmi-Eg_90.JPG: 480x640 (no detections), 270.0ms
Speed: 1.0ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydMDF67Avf6s9kcAOmi-Eg_180.JPG: 480x640 (no detections), 273.9ms
Speed: 1.0ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydMDF67Avf6s9kcAOmi-Eg_270.JPG: 480x640 (no detections), 280.5ms
Speed: 1.0ms preprocess, 280.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydMoLQCCZh5A3wr70whFow_0.JPG: 480x640 (no detections), 271.0ms
Speed: 1.1ms preprocess, 271.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydMoLQCCZh5A3wr70whFow_90.JPG: 480x640 (no detections), 280.9ms
Speed: 1.0ms preprocess, 280.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydMoLQCCZh5A3wr70whFow_180.JPG: 480x640 (no detections), 274.1ms
Speed: 1.0ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydMoLQCCZh5A3wr70whFow_270.JPG: 480x640 (no detections), 276.0ms
Speed: 1.0ms preprocess, 276.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydNVbI-NMrKgIiTkWi726w_0.JPG: 480x640 (no detections), 274.7ms
Speed: 1.1ms preprocess, 274.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydNVbI-NMrKgIiTkWi726w_90.JPG: 480x640 (no detections), 268.5ms
Speed: 1.0ms preprocess, 268.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydNVbI-NMrKgIiTkWi726w_180.JPG: 480x640 (no detections), 276.2ms
Speed: 1.1ms preprocess, 276.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydNVbI-NMrKgIiTkWi726w_270.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydNhoixeJT4McrVUBtDRlA_0.JPG: 480x640 (no detections), 268.4ms
Speed: 1.1ms preprocess, 268.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydNhoixeJT4McrVUBtDRlA_90.JPG: 480x640 (no detections), 274.3ms
Speed: 1.1ms preprocess, 274.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydNhoixeJT4McrVUBtDRlA_180.JPG: 480x640 (no detections), 275.2ms
Speed: 1.0ms preprocess, 275.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydNhoixeJT4McrVUBtDRlA_270.JPG: 480x640 (no detections), 271.0ms
Speed: 1.1ms preprocess, 271.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydOG2CxA16-RgT-m9TZpuw_0.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydOG2CxA16-RgT-m9TZpuw_90.JPG: 480x640 (no detections), 273.9ms
Speed: 1.0ms preprocess, 273.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydOG2CxA16-RgT-m9TZpuw_180.JPG: 480x640 (no detections), 272.5ms
Speed: 1.0ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydOG2CxA16-RgT-m9TZpuw_270.JPG: 480x640 (no detections), 273.9ms
Speed: 1.0ms preprocess, 273.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydPqpRp4Cu5Dhk2jPg31Ug_0.JPG: 480x640 (no detections), 274.0ms
Speed: 1.2ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydPqpRp4Cu5Dhk2jPg31Ug_90.JPG: 480x640 (no detections), 273.3ms
Speed: 1.2ms preprocess, 273.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydPqpRp4Cu5Dhk2jPg31Ug_180.JPG: 480x640 (no detections), 273.9ms
Speed: 1.0ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydPqpRp4Cu5Dhk2jPg31Ug_270.JPG: 480x640 (no detections), 270.9ms
Speed: 1.1ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydUQEPaWeCweVKcRoX87Sg_0.JPG: 480x640 (no detections), 273.4ms
Speed: 1.1ms preprocess, 273.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydUQEPaWeCweVKcRoX87Sg_90.JPG: 480x640 (no detections), 267.1ms
Speed: 1.0ms preprocess, 267.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydUQEPaWeCweVKcRoX87Sg_180.JPG: 480x640 (no detections), 275.0ms
Speed: 1.1ms preprocess, 275.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydUQEPaWeCweVKcRoX87Sg_270.JPG: 480x640 (no detections), 271.4ms
Speed: 1.0ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydXjMNTtoLvMYqcchh0-cw_0.JPG: 480x640 (no detections), 277.6ms
Speed: 1.0ms preprocess, 277.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydXjMNTtoLvMYqcchh0-cw_90.JPG: 480x640 (no detections), 270.4ms
Speed: 1.1ms preprocess, 270.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydXjMNTtoLvMYqcchh0-cw_180.JPG: 480x640 (no detections), 275.8ms
Speed: 1.1ms preprocess, 275.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydXjMNTtoLvMYqcchh0-cw_270.JPG: 480x640 (no detections), 273.6ms
Speed: 1.0ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydZKHWKzsvvsCZdbvDkiIg_0.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydZKHWKzsvvsCZdbvDkiIg_90.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydZKHWKzsvvsCZdbvDkiIg_180.JPG: 480x640 (no detections), 275.2ms
Speed: 1.0ms preprocess, 275.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydZKHWKzsvvsCZdbvDkiIg_270.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yd_67HahUj9F72g4EUpgmw_0.JPG: 480x640 (no detections), 274.5ms
Speed: 1.1ms preprocess, 274.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yd_67HahUj9F72g4EUpgmw_90.JPG: 480x640 (no detections), 276.9ms
Speed: 1.2ms preprocess, 276.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yd_67HahUj9F72g4EUpgmw_180.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yd_67HahUj9F72g4EUpgmw_270.JPG: 480x640 (no detections), 272.0ms
Speed: 1.1ms preprocess, 272.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydaKhKE2GvxPAQ3w-ArN1w_0.JPG: 480x640 (no detections), 271.5ms
Speed: 1.1ms preprocess, 271.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydaKhKE2GvxPAQ3w-ArN1w_90.JPG: 480x640 (no detections), 267.8ms
Speed: 1.0ms preprocess, 267.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydaKhKE2GvxPAQ3w-ArN1w_180.JPG: 480x640 (no detections), 272.3ms

Speed: 1.1ms preprocess, 272.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydaKhKE2GvxPAQ3w-ArN1w_270.JPG: 480x640 (no detections), 271.1ms
Speed: 1.0ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydc747INlzWvSWpZBx_Rrg_0.JPG: 480x640 (no detections), 273.8ms
Speed: 1.0ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydc747INlzWvSWpZBx_Rrg_90.JPG: 480x640 (no detections), 274.5ms
Speed: 1.0ms preprocess, 274.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydc747INlzWvSWpZBx_Rrg_180.JPG: 480x640 (no detections), 275.7ms
Speed: 1.0ms preprocess, 275.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydc747INlzWvSWpZBx_Rrg_270.JPG: 480x640 (no detections), 273.1ms
Speed: 1.0ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yddQ7rT7lm0YjpWNvFTMyw_0.JPG: 480x640 (no detections), 267.8ms
Speed: 1.1ms preprocess, 267.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yddQ7rT7lm0YjpWNvFTMyw_90.JPG: 480x640 (no detections), 270.8ms
Speed: 1.0ms preprocess, 270.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yddQ7rT7lm0YjpWNvFTMyw_180.JPG: 480x640 (no detections), 270.3ms
Speed: 1.0ms preprocess, 270.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/yddQ7rT7lm0YjpWNvFTMyw_270.JPG: 480x640 (no detections), 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydhi3zgrbkOGD7icHQw_1A_0.JPG: 480x640 (no detections), 271.8ms
Speed: 1.0ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydhi3zgrbkOGD7icHQw_1A_90.JPG: 480x640 (no detections), 271.6ms
Speed: 1.0ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydhi3zgrbkOGD7icHQw_1A_180.JPG: 480x640 (no detections), 274.8ms
Speed: 1.1ms preprocess, 274.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydhi3zgrbkOGD7icHQw_1A_270.JPG: 480x640 (no detections), 274.4ms
Speed: 1.1ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydiqfHjzukPe645HwWrxgg_0.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydiqfHjzukPe645HwWrxgg_90.JPG: 480x640 (no detections), 270.7ms
Speed: 1.0ms preprocess, 270.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydiqfHjzukPe645HwWrxgg_180.JPG: 480x640 (no detections), 275.6ms
Speed: 1.0ms preprocess, 275.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydiqfHjzukPe645HwWrxgg_270.JPG: 480x640 (no detections), 271.4ms
Speed: 1.0ms preprocess, 271.4ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydixfUA7yIcKvj1Bbxjb4w_0.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydixfUA7yIcKvj1Bbxjb4w_90.JPG: 480x640 (no detections), 270.7ms
Speed: 1.0ms preprocess, 270.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydixfUA7yIcKvj1Bbxjb4w_180.JPG: 480x640 (no detections), 271.5ms
Speed: 1.0ms preprocess, 271.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydixfUA7yIcKvj1Bbxjb4w_270.JPG: 480x640 (no detections), 271.9ms
Speed: 1.0ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydjcyUuzf1auKNf5MVFJ1A_0.JPG: 480x640 (no detections), 271.5ms
Speed: 1.1ms preprocess, 271.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydjcyUuzf1auKNf5MVFJ1A_90.JPG: 480x640 (no detections), 273.2ms
Speed: 1.1ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydjcyUuzf1auKNf5MVFJ1A_180.JPG: 480x640 (no detections), 276.7ms
Speed: 1.1ms preprocess, 276.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydjcyUuzf1auKNf5MVFJ1A_270.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydlBm9b8NDe5UkUUVLAH-Q_0.JPG: 480x640 (no detections), 276.4ms
Speed: 1.1ms preprocess, 276.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydlBm9b8NDe5UkUUVLAH-Q_90.JPG: 480x640 (no detections), 272.4ms
Speed: 1.0ms preprocess, 272.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydlBm9b8NDe5UkUUVLAH-Q_180.JPG: 480x640 (no detections), 267.8ms
Speed: 1.1ms preprocess, 267.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydlBm9b8NDe5UkUUVLAH-Q_270.JPG: 480x640 (no detections), 269.7ms
Speed: 1.0ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydmrmQVUM-HgVjONnBChqw_0.JPG: 480x640 (no detections), 270.7ms
Speed: 1.0ms preprocess, 270.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydmrmQVUM-HgVjONnBChqw_90.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydmrmQVUM-HgVjONnBChqw_180.JPG: 480x640 (no detections), 268.9ms
Speed: 1.1ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydmrmQVUM-HgVjONnBChqw_270.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydmsUxtVwgNOlehmgMny9A_0.JPG: 480x640 (no detections), 276.0ms
Speed: 1.0ms preprocess, 276.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydmsUxtVwgNOlehmgMny9A_90.JPG: 480x640 (no detections), 274.4ms
Speed: 1.0ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydmsUxtVwgNOlehmgMny9A_180.JPG: 480x640 (no detections), 279.0ms
Speed: 1.0ms preprocess, 279.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydmsUxtVwgNOlehmgMny9A_270.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydsHKy9iYXImHOT9VXhVmQ_0.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydsHKy9iYXImHOT9VXhVmQ_90.JPG: 480x640 (no detections), 276.9ms
Speed: 1.0ms preprocess, 276.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydsHKy9iYXImHOT9VXhVmQ_180.JPG: 480x640 (no detections), 270.7ms
Speed: 1.0ms preprocess, 270.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydsHKy9iYXImHOT9VXhVmQ_270.JPG: 480x640 (no detections), 276.8ms
Speed: 1.0ms preprocess, 276.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydvMoLL9255LDSyMzqyePg_0.JPG: 480x640 (no detections), 272.5ms
Speed: 1.1ms preprocess, 272.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydvMoLL9255LDSyMzqyePg_90.JPG: 480x640 (no detections), 273.2ms
Speed: 1.2ms preprocess, 273.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydvMoLL9255LDSyMzqyePg_180.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydvMoLL9255LDSyMzqyePg_270.JPG: 480x640 (no detections), 275.0ms
Speed: 1.0ms preprocess, 275.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydw7M_FtSmovGX6dOBkC7A_0.JPG: 480x640 (no detections), 269.2ms
Speed: 1.0ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydw7M_FtSmovGX6dOBkC7A_90.JPG: 480x640 (no detections), 275.2ms
Speed: 1.1ms preprocess, 275.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydw7M_FtSmovGX6dOBkC7A_180.JPG: 480x640 (no detections), 273.0ms
Speed: 1.0ms preprocess, 273.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/d/ydw7M_FtSmovGX6dOBkC7A_270.JPG: 480x640 (no detections), 272.3ms
Speed: 1.1ms preprocess, 272.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/ye-VrqVoVBgqCq3es5yIWQ_0.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/ye-VrqVoVBgqCq3es5yIWQ_90.JPG: 480x640 (no detections), 273.1ms
Speed: 1.0ms preprocess, 273.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/ye-VrqVoVBgqCq3es5yIWQ_180.JPG: 480x640 (no detections), 270.7ms
Speed: 1.0ms preprocess, 270.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/ye-VrqVoVBgqCq3es5yIWQ_270.JPG: 480x640 (no detections), 276.4ms
Speed: 1.1ms preprocess, 276.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/ye2e1UDQmC9K6xmQE7G-9g_0.JPG: 480x640 (no detections), 272.3ms
Speed: 1.1ms preprocess, 272.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/ye2e1UDQmC9K6xmQE7G-9g_90.JPG: 480x640 (no detections), 276.0ms
Speed: 1.0ms preprocess, 276.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/ye2e1UDQmC9K6xmQE7G-9g_180.JPG: 480x640 (no detections), 274.8ms
Speed: 1.0ms preprocess, 274.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/ye2e1UDQmC9K6xmQE7G-9g_270.JPG: 480x640 (no detections), 272.3ms
Speed: 1.1ms preprocess, 272.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/ye6oEcuYLLJDLlq6sqKdnw_0.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/ye6oEcuYLLJDLlq6sqKdnw_90.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/ye6oEcuYLLJDLlq6sqKdnw_180.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/ye6oEcuYLLJDLlq6sqKdnw_270.JPG: 480x640 (no detections), 267.2ms
Speed: 1.0ms preprocess, 267.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yeBd2op062vvBXbxKu3l1A_0.JPG: 480x640 (no detections), 268.8ms
Speed: 1.1ms preprocess, 268.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yeBd2op062vvBXbxKu3l1A_90.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yeBd2op062vvBXbxKu3l1A_180.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yeBd2op062vvBXbxKu3l1A_270.JPG: 480x640 (no detections), 273.7ms
Speed: 1.0ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yeDa2FSP_wy2UYVf7KKwDw_0.JPG: 480x640 (no detections), 276.0ms
Speed: 1.0ms preprocess, 276.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yeDa2FSP_wy2UYVf7KKwDw_90.JPG: 480x640 (no detections), 273.7ms

Speed: 1.0ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yeDa2FSP_wy2UYVf7KKwDw_180.JPG: 480x640 (no detections), 281.3ms
Speed: 1.1ms preprocess, 281.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yeDa2FSP_wy2UYVf7KKwDw_270.JPG: 480x640 (no detections), 269.1ms
Speed: 1.0ms preprocess, 269.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yeGD2aZj2giRM5XZG_7N3w_0.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yeGD2aZj2giRM5XZG_7N3w_90.JPG: 480x640 (no detections), 270.7ms
Speed: 1.0ms preprocess, 270.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yeGD2aZj2giRM5XZG_7N3w_180.JPG: 480x640 (no detections), 274.6ms
Speed: 1.0ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yeGD2aZj2giRM5XZG_7N3w_270.JPG: 480x640 (no detections), 270.7ms
Speed: 1.0ms preprocess, 270.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yeIX9D0QNnx-z_nnwnxXDw_0.JPG: 480x640 (no detections), 271.0ms
Speed: 1.0ms preprocess, 271.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yeIX9D0QNnx-z_nnwnxXDw_90.JPG: 480x640 (no detections), 272.3ms
Speed: 1.1ms preprocess, 272.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yeIX9D0QNnx-z_nnwnxXDw_180.JPG: 480x640 (no detections), 271.8ms
Speed: 1.0ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yeIX9D0QNnx-z_nnwnxXDw_270.JPG: 480x640 (no detections), 272.5ms
Speed: 1.0ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yeNA_sM5NsiPrafqDEOsCA_0.JPG: 480x640 (no detections), 281.9ms
Speed: 1.1ms preprocess, 281.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yeNA_sM5NsiPrafqDEOsCA_90.JPG: 480x640 (no detections), 272.4ms
Speed: 1.1ms preprocess, 272.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yeNA_sM5NsiPrafqDEOsCA_180.JPG: 480x640 (no detections), 279.8ms
Speed: 1.0ms preprocess, 279.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yeNA_sM5NsiPrafqDEOsCA_270.JPG: 480x640 (no detections), 276.8ms
Speed: 1.1ms preprocess, 276.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yeNz5HrhqMpCItuA8idlMA_0.JPG: 480x640 (no detections), 276.9ms
Speed: 1.1ms preprocess, 276.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yeNz5HrhqMpCItuA8idlMA_90.JPG: 480x640 (no detections), 274.8ms
Speed: 1.0ms preprocess, 274.8ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yeNz5HrhqMpCItuA8idlMA_180.JPG: 480x640 (no detections), 272.7ms
Speed: 1.2ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yeNz5HrhqMpCItuA8idlMA_270.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yeOAHkoBK1khW7xLFwsUAA_0.JPG: 480x640 (no detections), 273.5ms
Speed: 1.0ms preprocess, 273.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yeOAHkoBK1khW7xLFwsUAA_90.JPG: 480x640 (no detections), 272.8ms
Speed: 1.0ms preprocess, 272.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yeOAHkoBK1khW7xLFwsUAA_180.JPG: 480x640 (no detections), 274.6ms
Speed: 1.1ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yeOAHkoBK1khW7xLFwsUAA_270.JPG: 480x640 (no detections), 272.5ms
Speed: 1.0ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yePCWdMmTdwE9_uo83hmYw_0.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yePCWdMmTdwE9_uo83hmYw_90.JPG: 480x640 (no detections), 268.6ms
Speed: 1.1ms preprocess, 268.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yePCWdMmTdwE9_uo83hmYw_180.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yePCWdMmTdwE9_uo83hmYw_270.JPG: 480x640 (no detections), 268.3ms
Speed: 1.0ms preprocess, 268.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yeTGc0fsgaOQW2AoGyKp4Q_0.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yeTGc0fsgaOQW2AoGyKp4Q_90.JPG: 480x640 (no detections), 275.4ms
Speed: 1.0ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yeTGc0fsgaOQW2AoGyKp4Q_180.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yeTGc0fsgaOQW2AoGyKp4Q_270.JPG: 480x640 (no detections), 274.9ms
Speed: 1.0ms preprocess, 274.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yeTe310GU9TFxtds54ZHeQ_0.JPG: 480x640 (no detections), 271.5ms
Speed: 1.1ms preprocess, 271.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yeTe310GU9TFxtds54ZHeQ_90.JPG: 480x640 (no detections), 272.6ms
Speed: 1.2ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yeTe310GU9TFxtds54ZHeQ_180.JPG: 480x640 (no detections), 274.7ms
Speed: 1.2ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yeTe310GU9TFxtds54ZHeQ_270.JPG: 480x640 (no detections), 272.4ms
Speed: 1.1ms preprocess, 272.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yeVTjSmPp6UAhPZbXQD-ug_0.JPG: 480x640 (no detections), 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yeVTjSmPp6UAhPZbXQD-ug_90.JPG: 480x640 (no detections), 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yeVTjSmPp6UAhPZbXQD-ug_180.JPG: 480x640 (no detections), 270.1ms
Speed: 1.2ms preprocess, 270.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yeVTjSmPp6UAhPZbXQD-ug_270.JPG: 480x640 (no detections), 275.9ms
Speed: 1.1ms preprocess, 275.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/ye_LZCZ0-gPniTwMXmggDQ_0.JPG: 480x640 (no detections), 275.1ms
Speed: 1.5ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/ye_LZCZ0-gPniTwMXmggDQ_90.JPG: 480x640 (no detections), 278.0ms
Speed: 1.0ms preprocess, 278.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/ye_LZCZ0-gPniTwMXmggDQ_180.JPG: 480x640 (no detections), 272.2ms
Speed: 1.0ms preprocess, 272.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/ye_LZCZ0-gPniTwMXmggDQ_270.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yecGtwcmV0mpyQEaY9ZcBA_0.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yecGtwcmV0mpyQEaY9ZcBA_90.JPG: 480x640 (no detections), 276.0ms
Speed: 1.0ms preprocess, 276.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yecGtwcmV0mpyQEaY9ZcBA_180.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yecGtwcmV0mpyQEaY9ZcBA_270.JPG: 480x640 (no detections), 276.5ms
Speed: 1.0ms preprocess, 276.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yedxEH6U9KIbjwgIyGXYOw_0.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yedxEH6U9KIbjwgIyGXYOw_90.JPG: 480x640 (no detections), 275.2ms
Speed: 1.3ms preprocess, 275.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yedxEH6U9KIbjwgIyGXYOw_180.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yedxEH6U9KIbjwgIyGXYOw_270.JPG: 480x640 (no detections), 275.9ms
Speed: 1.2ms preprocess, 275.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yehKb1vwe2BrJZZtnJWdHQ_0.JPG: 480x640 (no detections), 272.8ms
Speed: 1.5ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yehKb1vwe2BrJZZtnJWdHQ_90.JPG: 480x640 (no detections), 274.3ms
Speed: 1.1ms preprocess, 274.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yehKb1vwe2BrJZZtnJWdHQ_180.JPG: 480x640 (no detections), 272.2ms
Speed: 1.0ms preprocess, 272.2ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yehKb1vwe2BrJZZtnJWdHQ_270.JPG: 480x640 (no detections), 274.5ms
Speed: 1.0ms preprocess, 274.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yeoUxxdisQZPujl86Te63Q_0.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yeoUxxdisQZPujl86Te63Q_90.JPG: 480x640 (no detections), 272.5ms
Speed: 1.0ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yeoUxxdisQZPujl86Te63Q_180.JPG: 480x640 (no detections), 269.8ms
Speed: 1.0ms preprocess, 269.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yeoUxxdisQZPujl86Te63Q_270.JPG: 480x640 (no detections), 270.0ms
Speed: 1.0ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yeoVX8j69AZRGSNYvd2PMw_0.JPG: 480x640 (no detections), 274.5ms
Speed: 1.0ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yeoVX8j69AZRGSNYvd2PMw_90.JPG: 480x640 (no detections), 273.9ms
Speed: 1.1ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yeoVX8j69AZRGSNYvd2PMw_180.JPG: 480x640 (no detections), 263.8ms
Speed: 1.1ms preprocess, 263.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yeoVX8j69AZRGSNYvd2PMw_270.JPG: 480x640 (no detections), 273.2ms
Speed: 1.0ms preprocess, 273.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yepzvsNlqfKX2D6rU7bnrQ_0.JPG: 480x640 (no detections), 274.4ms
Speed: 1.0ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yepzvsNlqfKX2D6rU7bnrQ_90.JPG: 480x640 (no detections), 273.1ms
Speed: 1.1ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yepzvsNlqfKX2D6rU7bnrQ_180.JPG: 480x640 (no detections), 270.9ms
Speed: 1.1ms preprocess, 270.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yepzvsNlqfKX2D6rU7bnrQ_270.JPG: 480x640 (no detections), 270.2ms
Speed: 1.0ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yeqRa7ckAdSzLoRc1IOwRw_0.JPG: 480x640 (no detections), 270.8ms

Speed: 1.1ms preprocess, 270.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yeqRa7ckAdSzLoRc1IOwRw_90.JPG: 480x640 (no detections), 280.6ms
Speed: 1.2ms preprocess, 280.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yeqRa7ckAdSzLoRc1IOwRw_180.JPG: 480x640 (no detections), 290.6ms
Speed: 1.2ms preprocess, 290.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yeqRa7ckAdSzLoRc1IOwRw_270.JPG: 480x640 (no detections), 289.5ms
Speed: 1.2ms preprocess, 289.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yewTyQ_gtSbGZc1QQQReOQ_0.JPG: 480x640 (no detections), 277.7ms
Speed: 1.2ms preprocess, 277.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yewTyQ_gtSbGZc1QQQReOQ_90.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yewTyQ_gtSbGZc1QQQReOQ_180.JPG: 480x640 (no detections), 276.4ms
Speed: 1.1ms preprocess, 276.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yewTyQ_gtSbGZc1QQQReOQ_270.JPG: 480x640 (no detections), 272.2ms
Speed: 1.0ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yezbx1n1xNg_7nC_RHWfvg_0.JPG: 480x640 (no detections), 273.6ms
Speed: 1.1ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yezbx1n1xNg_7nC_RHWfvg_90.JPG: 480x640 (no detections), 269.8ms
Speed: 1.2ms preprocess, 269.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yezbx1n1xNg_7nC_RHWfvg_180.JPG: 480x640 (no detections), 278.0ms
Speed: 1.1ms preprocess, 278.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yezbx1n1xNg_7nC_RHWfvg_270.JPG: 480x640 (no detections), 269.5ms
Speed: 1.1ms preprocess, 269.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yezxAMdAStJZP-3lMhYwew_0.JPG: 480x640 (no detections), 267.8ms
Speed: 1.1ms preprocess, 267.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yezxAMdAStJZP-3lMhYwew_90.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yezxAMdAStJZP-3lMhYwew_180.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/e/yezxAMdAStJZP-3lMhYwew_270.JPG: 480x640 (no detections), 273.8ms
Speed: 1.0ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yf-wsId1OIpG4TPERi1pnQ_0.JPG: 480x640 (no detections), 275.2ms
Speed: 1.1ms preprocess, 275.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yf-wsId1OIpG4TPERi1pnQ_90.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yf-wsId1OIpG4TPERi1pnQ_180.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yf-wsId1OIpG4TPERi1pnQ_270.JPG: 480x640 (no detections), 271.8ms
Speed: 1.0ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yf58OU0EYPEW6nzfsK5vgw_0.JPG: 480x640 (no detections), 272.2ms
Speed: 1.0ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yf58OU0EYPEW6nzfsK5vgw_90.JPG: 480x640 (no detections), 267.9ms
Speed: 1.1ms preprocess, 267.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yf58OU0EYPEW6nzfsK5vgw_180.JPG: 480x640 (no detections), 277.5ms
Speed: 1.0ms preprocess, 277.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yf58OU0EYPEW6nzfsK5vgw_270.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yf9YB9htEiRUaJUmVF3T6Q_0.JPG: 480x640 (no detections), 273.2ms
Speed: 1.1ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yf9YB9htEiRUaJUmVF3T6Q_90.JPG: 480x640 (no detections), 268.7ms
Speed: 1.2ms preprocess, 268.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yf9YB9htEiRUaJUmVF3T6Q_180.JPG: 480x640 (no detections), 267.9ms
Speed: 1.0ms preprocess, 267.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yf9YB9htEiRUaJUmVF3T6Q_270.JPG: 480x640 (no detections), 270.0ms
Speed: 1.0ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfO5Uw3vv5DyLFEz6iXD-Q_0.JPG: 480x640 1 Waste, 270.3ms
Speed: 1.1ms preprocess, 270.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfO5Uw3vv5DyLFEz6iXD-Q_90.JPG: 480x640 (no detections), 273.1ms
Speed: 1.2ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfO5Uw3vv5DyLFEz6iXD-Q_180.JPG: 480x640 (no detections), 265.0ms
Speed: 1.0ms preprocess, 265.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfO5Uw3vv5DyLFEz6iXD-Q_270.JPG: 480x640 (no detections), 269.8ms
Speed: 1.0ms preprocess, 269.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfO6FulsUxttRrvprge6_A_0.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfO6FulsUxttRrvprge6_A_90.JPG: 480x640 (no detections), 276.7ms
Speed: 1.0ms preprocess, 276.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfO6FulsUxttRrvprge6_A_180.JPG: 480x640 (no detections), 273.6ms
Speed: 1.0ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfO6FulsUxttRrvprge6_A_270.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfRghmBqUgEBuOPYW8VPBg_0.JPG: 480x640 (no detections), 277.3ms
Speed: 1.1ms preprocess, 277.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfRghmBqUgEBuOPYW8VPBg_90.JPG: 480x640 (no detections), 274.9ms
Speed: 1.2ms preprocess, 274.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfRghmBqUgEBuOPYW8VPBg_180.JPG: 480x640 (no detections), 271.1ms
Speed: 1.2ms preprocess, 271.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfRghmBqUgEBuOPYW8VPBg_270.JPG: 480x640 (no detections), 272.4ms
Speed: 1.1ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfX9ornYl2ERTdHX1xaMpQ_0.JPG: 480x640 (no detections), 268.9ms
Speed: 1.0ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfX9ornYl2ERTdHX1xaMpQ_90.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfX9ornYl2ERTdHX1xaMpQ_180.JPG: 480x640 (no detections), 268.9ms
Speed: 1.0ms preprocess, 268.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfX9ornYl2ERTdHX1xaMpQ_270.JPG: 480x640 (no detections), 272.9ms
Speed: 1.3ms preprocess, 272.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfb1Fdra3fqL3_ej4Fkq8w_0.JPG: 480x640 (no detections), 272.5ms
Speed: 1.1ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfb1Fdra3fqL3_ej4Fkq8w_90.JPG: 480x640 (no detections), 268.7ms
Speed: 1.1ms preprocess, 268.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfb1Fdra3fqL3_ej4Fkq8w_180.JPG: 480x640 (no detections), 271.9ms
Speed: 1.0ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfb1Fdra3fqL3_ej4Fkq8w_270.JPG: 480x640 (no detections), 270.4ms
Speed: 1.0ms preprocess, 270.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfdzrDl_ynPu9Pd6fYi48Q_0.JPG: 480x640 (no detections), 268.3ms
Speed: 1.0ms preprocess, 268.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfdzrDl_ynPu9Pd6fYi48Q_90.JPG: 480x640 (no detections), 272.4ms
Speed: 1.1ms preprocess, 272.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfdzrDl_ynPu9Pd6fYi48Q_180.JPG: 480x640 (no detections), 273.6ms
Speed: 1.1ms preprocess, 273.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfdzrDl_ynPu9Pd6fYi48Q_270.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfg2KMUW5IKH-a1J78ctLQ_0.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfg2KMUW5IKH-a1J78ctLQ_90.JPG: 480x640 (no detections), 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfg2KMUW5IKH-a1J78ctLQ_180.JPG: 480x640 (no detections), 277.8ms
Speed: 1.0ms preprocess, 277.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfg2KMUW5IKH-a1J78ctLQ_270.JPG: 480x640 (no detections), 274.0ms
Speed: 1.2ms preprocess, 274.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfn3qB09jpSBdu-Fe2WXPw_0.JPG: 480x640 (no detections), 269.1ms
Speed: 1.1ms preprocess, 269.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfn3qB09jpSBdu-Fe2WXPw_90.JPG: 480x640 (no detections), 271.2ms
Speed: 1.0ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfn3qB09jpSBdu-Fe2WXPw_180.JPG: 480x640 (no detections), 271.7ms
Speed: 1.2ms preprocess, 271.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfn3qB09jpSBdu-Fe2WXPw_270.JPG: 480x640 1 Waste, 267.4ms
Speed: 1.0ms preprocess, 267.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfpqgwOFX03Q4gDWzG0CwA_0.JPG: 480x640 (no detections), 271.7ms
Speed: 1.0ms preprocess, 271.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfpqgwOFX03Q4gDWzG0CwA_90.JPG: 480x640 (no detections), 268.8ms
Speed: 1.0ms preprocess, 268.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfpqgwOFX03Q4gDWzG0CwA_180.JPG: 480x640 (no detections), 269.5ms
Speed: 1.1ms preprocess, 269.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfpqgwOFX03Q4gDWzG0CwA_270.JPG: 480x640 (no detections), 271.7ms
Speed: 1.0ms preprocess, 271.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfsOsboO1S8KTkYkvJm_-A_0.JPG: 480x640 1 Waste, 276.7ms
Speed: 1.0ms preprocess, 276.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfsOsboO1S8KTkYkvJm_-A_90.JPG: 480x640 1 Waste, 272.4ms
Speed: 1.0ms preprocess, 272.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfsOsboO1S8KTkYkvJm_-A_180.JPG: 480x640 (no detections), 271.9ms
Speed: 1.0ms preprocess, 271.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfsOsboO1S8KTkYkvJm_-A_270.JPG: 480x640 1 Waste, 267.4ms

Speed: 1.0ms preprocess, 267.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfs_batyeh5JJubGN-Mtqw_0.JPG: 480x640 (no detections), 272.4ms
Speed: 1.2ms preprocess, 272.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfs_batyeh5JJubGN-Mtqw_90.JPG: 480x640 (no detections), 269.8ms
Speed: 1.1ms preprocess, 269.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfs_batyeh5JJubGN-Mtqw_180.JPG: 480x640 (no detections), 268.3ms
Speed: 1.1ms preprocess, 268.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfs_batyeh5JJubGN-Mtqw_270.JPG: 480x640 (no detections), 274.6ms
Speed: 1.1ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfvlLNAG1nSLvAwbLkGTWA_0.JPG: 480x640 (no detections), 275.7ms
Speed: 1.0ms preprocess, 275.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfvlLNAG1nSLvAwbLkGTWA_90.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfvlLNAG1nSLvAwbLkGTWA_180.JPG: 480x640 2 Wastes, 272.5ms
Speed: 1.0ms preprocess, 272.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfvlLNAG1nSLvAwbLkGTWA_270.JPG: 480x640 1 Waste, 275.0ms
Speed: 1.0ms preprocess, 275.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfwV4HgO15YEAdeWk24owQ_0.JPG: 480x640 (no detections), 272.3ms
Speed: 1.0ms preprocess, 272.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfwV4HgO15YEAdeWk24owQ_90.JPG: 480x640 (no detections), 270.9ms
Speed: 1.0ms preprocess, 270.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfwV4HgO15YEAdeWk24owQ_180.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfwV4HgO15YEAdeWk24owQ_270.JPG: 480x640 (no detections), 275.4ms
Speed: 1.1ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfyH38Ot8VVH1JoEQcooRA_0.JPG: 480x640 (no detections), 270.9ms
Speed: 1.1ms preprocess, 270.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfyH38Ot8VVH1JoEQcooRA_90.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfyH38Ot8VVH1JoEQcooRA_180.JPG: 480x640 (no detections), 269.0ms
Speed: 1.0ms preprocess, 269.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfyH38Ot8VVH1JoEQcooRA_270.JPG: 480x640 (no detections), 272.4ms
Speed: 1.0ms preprocess, 272.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfyLrPs65ffOcWXKMt4hdw_0.JPG: 480x640 (no detections), 272.2ms
Speed: 1.0ms preprocess, 272.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfyLrPs65ffOcWXKMt4hdw_90.JPG: 480x640 (no detections), 268.2ms
Speed: 1.0ms preprocess, 268.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfyLrPs65ffOcWXKMt4hdw_180.JPG: 480x640 (no detections), 268.5ms
Speed: 1.0ms preprocess, 268.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfyLrPs65ffOcWXKMt4hdw_270.JPG: 480x640 (no detections), 272.8ms
Speed: 1.0ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfzEu0qwmnAIvhHxLwlpZg_0.JPG: 480x640 (no detections), 269.2ms
Speed: 1.1ms preprocess, 269.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfzEu0qwmnAIvhHxLwlpZg_90.JPG: 480x640 (no detections), 270.5ms
Speed: 1.0ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfzEu0qwmnAIvhHxLwlpZg_180.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfzEu0qwmnAIvhHxLwlpZg_270.JPG: 480x640 (no detections), 271.0ms
Speed: 1.0ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfzKMGMkOukC92PGjeglrw_0.JPG: 480x640 (no detections), 272.8ms
Speed: 1.0ms preprocess, 272.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfzKMGMkOukC92PGjeglrw_90.JPG: 480x640 (no detections), 273.4ms
Speed: 1.1ms preprocess, 273.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfzKMGMkOukC92PGjeglrw_180.JPG: 480x640 (no detections), 272.3ms
Speed: 1.0ms preprocess, 272.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/f/yfzKMGMkOukC92PGjeglrw_270.JPG: 480x640 (no detections), 273.8ms
Speed: 1.3ms preprocess, 273.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yg-IawSBTFpvMvQv-vml3A_0.JPG: 480x640 (no detections), 271.6ms
Speed: 1.2ms preprocess, 271.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yg-IawSBTFpvMvQv-vml3A_90.JPG: 480x640 (no detections), 269.6ms
Speed: 1.1ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yg-IawSBTFpvMvQv-vml3A_180.JPG: 480x640 (no detections), 269.4ms
Speed: 1.1ms preprocess, 269.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yg-IawSBTFpvMvQv-vml3A_270.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yg0C7dOfAuPUBKizM6szwA_0.JPG: 480x640 (no detections), 273.6ms
Speed: 1.1ms preprocess, 273.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yg0C7dOfAuPUBKizM6szwA_90.JPG: 480x640 (no detections), 269.7ms
Speed: 1.0ms preprocess, 269.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yg0C7dOfAuPUBKizM6szwA_180.JPG: 480x640 (no detections), 273.9ms
Speed: 1.0ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yg0C7dOfAuPUBKizM6szwA_270.JPG: 480x640 (no detections), 267.5ms
Speed: 1.1ms preprocess, 267.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yg1-vS8xp6LhhRg9XvUxPQ_0.JPG: 480x640 (no detections), 273.9ms
Speed: 1.1ms preprocess, 273.9ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yg1-vS8xp6LhhRg9XvUxPQ_90.JPG: 480x640 (no detections), 269.0ms
Speed: 1.0ms preprocess, 269.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yg1-vS8xp6LhhRg9XvUxPQ_180.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yg1-vS8xp6LhhRg9XvUxPQ_270.JPG: 480x640 (no detections), 276.9ms
Speed: 1.0ms preprocess, 276.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yg6YbIHo2QgS2Cc4C3m2nA_0.JPG: 480x640 (no detections), 277.6ms
Speed: 1.0ms preprocess, 277.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yg6YbIHo2QgS2Cc4C3m2nA_90.JPG: 480x640 (no detections), 275.9ms
Speed: 1.1ms preprocess, 275.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yg6YbIHo2QgS2Cc4C3m2nA_180.JPG: 480x640 (no detections), 270.8ms
Speed: 1.0ms preprocess, 270.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yg6YbIHo2QgS2Cc4C3m2nA_270.JPG: 480x640 (no detections), 268.1ms
Speed: 1.0ms preprocess, 268.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yg7bPLQDMDvvVYS8T2PAbw_0.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yg7bPLQDMDvvVYS8T2PAbw_90.JPG: 480x640 (no detections), 270.5ms
Speed: 0.9ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yg7bPLQDMDvvVYS8T2PAbw_180.JPG: 480x640 (no detections), 272.3ms
Speed: 1.0ms preprocess, 272.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yg7bPLQDMDvvVYS8T2PAbw_270.JPG: 480x640 1 Waste, 270.9ms
Speed: 1.1ms preprocess, 270.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygEsV92gsCb-6IuMh1Os-A_0.JPG: 480x640 (no detections), 275.3ms
Speed: 1.1ms preprocess, 275.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygEsV92gsCb-6IuMh1Os-A_90.JPG: 480x640 (no detections), 275.4ms
Speed: 1.1ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygEsV92gsCb-6IuMh1Os-A_180.JPG: 480x640 (no detections), 271.0ms
Speed: 1.1ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygEsV92gsCb-6IuMh1Os-A_270.JPG: 480x640 (no detections), 272.9ms
Speed: 1.0ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygJLRnuo9U_i3inyzhSNdA_0.JPG: 480x640 (no detections), 273.5ms
Speed: 1.0ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygJLRnuo9U_i3inyzhSNdA_90.JPG: 480x640 (no detections), 267.9ms
Speed: 1.1ms preprocess, 267.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygJLRnuo9U_i3inyzhSNdA_180.JPG: 480x640 (no detections), 271.5ms
Speed: 1.1ms preprocess, 271.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygJLRnuo9U_i3inyzhSNdA_270.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygPg6AZAv1DIwafuhaR--A_0.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygPg6AZAv1DIwafuhaR--A_90.JPG: 480x640 (no detections), 271.5ms
Speed: 1.0ms preprocess, 271.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygPg6AZAv1DIwafuhaR--A_180.JPG: 480x640 (no detections), 269.2ms
Speed: 1.0ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygPg6AZAv1DIwafuhaR--A_270.JPG: 480x640 (no detections), 271.0ms
Speed: 1.1ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygQUxgF5bfYiwEqFFyzkCw_0.JPG: 480x640 (no detections), 269.2ms
Speed: 1.1ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygQUxgF5bfYiwEqFFyzkCw_90.JPG: 480x640 1 Waste, 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygQUxgF5bfYiwEqFFyzkCw_180.JPG: 480x640 (no detections), 269.6ms
Speed: 1.1ms preprocess, 269.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygQUxgF5bfYiwEqFFyzkCw_270.JPG: 480x640 (no detections), 273.7ms
Speed: 1.0ms preprocess, 273.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygRGlgar5vj0jlQrFEeMCw_0.JPG: 480x640 (no detections), 269.8ms
Speed: 1.0ms preprocess, 269.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygRGlgar5vj0jlQrFEeMCw_90.JPG: 480x640 (no detections), 273.6ms
Speed: 1.1ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygRGlgar5vj0jlQrFEeMCw_180.JPG: 480x640 (no detections), 270.7ms

Speed: 1.1ms preprocess, 270.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygRGlgar5vj0jlQrFEeMCw_270.JPG: 480x640 (no detections), 274.2ms
Speed: 1.0ms preprocess, 274.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygRrS3MXYWhKKWONvKBtxw_0.JPG: 480x640 (no detections), 271.1ms
Speed: 1.0ms preprocess, 271.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygRrS3MXYWhKKWONvKBtxw_90.JPG: 480x640 (no detections), 279.1ms
Speed: 1.1ms preprocess, 279.1ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygRrS3MXYWhKKWONvKBtxw_180.JPG: 480x640 (no detections), 271.0ms
Speed: 1.0ms preprocess, 271.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygRrS3MXYWhKKWONvKBtxw_270.JPG: 480x640 (no detections), 269.3ms
Speed: 1.0ms preprocess, 269.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygRzYiYrG82btUiZh_3Rlg_0.JPG: 480x640 (no detections), 270.6ms
Speed: 1.0ms preprocess, 270.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygRzYiYrG82btUiZh_3Rlg_90.JPG: 480x640 (no detections), 271.0ms
Speed: 1.1ms preprocess, 271.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygRzYiYrG82btUiZh_3Rlg_180.JPG: 480x640 (no detections), 278.1ms
Speed: 1.1ms preprocess, 278.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygRzYiYrG82btUiZh_3Rlg_270.JPG: 480x640 (no detections), 272.0ms
Speed: 1.1ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygTa7bJpHoJB0OHwqot-oA_0.JPG: 480x640 (no detections), 268.9ms
Speed: 1.1ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygTa7bJpHoJB0OHwqot-oA_90.JPG: 480x640 (no detections), 270.0ms
Speed: 1.0ms preprocess, 270.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygTa7bJpHoJB0OHwqot-oA_180.JPG: 480x640 (no detections), 268.0ms
Speed: 1.1ms preprocess, 268.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygTa7bJpHoJB0OHwqot-oA_270.JPG: 480x640 (no detections), 273.0ms
Speed: 1.2ms preprocess, 273.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygVKXDl16i8PZgHTr4Gz8w_0.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygVKXDl16i8PZgHTr4Gz8w_90.JPG: 480x640 (no detections), 270.9ms
Speed: 1.0ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygVKXDl16i8PZgHTr4Gz8w_180.JPG: 480x640 (no detections), 271.5ms
Speed: 1.1ms preprocess, 271.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygVKXDl16i8PZgHTr4Gz8w_270.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygVeA4OA1_hT57rNnQrt2w_0.JPG: 480x640 (no detections), 278.2ms
Speed: 1.0ms preprocess, 278.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygVeA4OA1_hT57rNnQrt2w_90.JPG: 480x640 (no detections), 273.8ms
Speed: 1.0ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygVeA4OA1_hT57rNnQrt2w_180.JPG: 480x640 (no detections), 269.4ms
Speed: 1.1ms preprocess, 269.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygVeA4OA1_hT57rNnQrt2w_270.JPG: 480x640 (no detections), 272.9ms
Speed: 1.0ms preprocess, 272.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygWspgrSI0elpZrn29DvVg_0.JPG: 480x640 (no detections), 269.9ms
Speed: 1.0ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygWspgrSI0elpZrn29DvVg_90.JPG: 480x640 (no detections), 271.9ms
Speed: 1.0ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygWspgrSI0elpZrn29DvVg_180.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygWspgrSI0elpZrn29DvVg_270.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygZpmdubW3uX2ruk8ivolw_0.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygZpmdubW3uX2ruk8ivolw_90.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygZpmdubW3uX2ruk8ivolw_180.JPG: 480x640 (no detections), 270.2ms
Speed: 1.0ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygZpmdubW3uX2ruk8ivolw_270.JPG: 480x640 (no detections), 270.5ms
Speed: 1.0ms preprocess, 270.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygd8RNf_1-fXzHBWdoPTOA_0.JPG: 480x640 (no detections), 273.2ms
Speed: 1.0ms preprocess, 273.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygd8RNf_1-fXzHBWdoPTOA_90.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygd8RNf_1-fXzHBWdoPTOA_180.JPG: 480x640 (no detections), 272.8ms
Speed: 1.0ms preprocess, 272.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygd8RNf_1-fXzHBWdoPTOA_270.JPG: 480x640 (no detections), 275.6ms
Speed: 1.0ms preprocess, 275.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygeftB-tYMCaplO9IRiqeg_0.JPG: 480x640 (no detections), 268.3ms
Speed: 1.0ms preprocess, 268.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygeftB-tYMCaplO9IRiqeg_90.JPG: 480x640 (no detections), 269.6ms
Speed: 1.1ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygeftB-tYMCaplO9IRiqeg_180.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygeftB-tYMCaplO9IRiqeg_270.JPG: 480x640 (no detections), 272.0ms
Speed: 1.1ms preprocess, 272.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yghSWYDCp5GkA0kqwCqi6g_0.JPG: 480x640 (no detections), 270.8ms
Speed: 1.2ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yghSWYDCp5GkA0kqwCqi6g_90.JPG: 480x640 (no detections), 268.4ms
Speed: 1.1ms preprocess, 268.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yghSWYDCp5GkA0kqwCqi6g_180.JPG: 480x640 (no detections), 271.7ms
Speed: 1.0ms preprocess, 271.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yghSWYDCp5GkA0kqwCqi6g_270.JPG: 480x640 (no detections), 272.0ms
Speed: 1.1ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygh_PiBAzifxxmWlx5xAFg_0.JPG: 480x640 (no detections), 266.3ms
Speed: 1.0ms preprocess, 266.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygh_PiBAzifxxmWlx5xAFg_90.JPG: 480x640 (no detections), 271.7ms
Speed: 1.0ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygh_PiBAzifxxmWlx5xAFg_180.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygh_PiBAzifxxmWlx5xAFg_270.JPG: 480x640 1 Waste, 272.0ms
Speed: 1.2ms preprocess, 272.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yghoont4Btd75_06t9tqIw_0.JPG: 480x640 (no detections), 273.1ms
Speed: 1.0ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yghoont4Btd75_06t9tqIw_90.JPG: 480x640 (no detections), 281.0ms
Speed: 1.3ms preprocess, 281.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yghoont4Btd75_06t9tqIw_180.JPG: 480x640 (no detections), 273.2ms
Speed: 1.1ms preprocess, 273.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/yghoont4Btd75_06t9tqIw_270.JPG: 480x640 (no detections), 275.9ms
Speed: 1.0ms preprocess, 275.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygi-0JC5FCc-InXtc76OOw_0.JPG: 480x640 (no detections), 271.7ms
Speed: 1.0ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygi-0JC5FCc-InXtc76OOw_90.JPG: 480x640 (no detections), 275.4ms
Speed: 1.0ms preprocess, 275.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygi-0JC5FCc-InXtc76OOw_180.JPG: 480x640 (no detections), 273.4ms
Speed: 1.1ms preprocess, 273.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygi-0JC5FCc-InXtc76OOw_270.JPG: 480x640 (no detections), 266.5ms
Speed: 1.1ms preprocess, 266.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygihliXmR0goIM6Y1FzM4g_0.JPG: 480x640 (no detections), 271.6ms
Speed: 1.0ms preprocess, 271.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygihliXmR0goIM6Y1FzM4g_90.JPG: 480x640 (no detections), 269.8ms
Speed: 1.0ms preprocess, 269.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygihliXmR0goIM6Y1FzM4g_180.JPG: 480x640 (no detections), 274.0ms
Speed: 1.1ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygihliXmR0goIM6Y1FzM4g_270.JPG: 480x640 (no detections), 271.8ms
Speed: 1.0ms preprocess, 271.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygl3GVYP4bLAM-PBZp-GFg_0.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygl3GVYP4bLAM-PBZp-GFg_90.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygl3GVYP4bLAM-PBZp-GFg_180.JPG: 480x640 (no detections), 271.4ms
Speed: 1.5ms preprocess, 271.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygl3GVYP4bLAM-PBZp-GFg_270.JPG: 480x640 (no detections), 277.8ms
Speed: 1.0ms preprocess, 277.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygnJMBoX93NOo5Ax6d-WtA_0.JPG: 480x640 (no detections), 271.5ms
Speed: 1.0ms preprocess, 271.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygnJMBoX93NOo5Ax6d-WtA_90.JPG: 480x640 (no detections), 272.7ms
Speed: 1.2ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygnJMBoX93NOo5Ax6d-WtA_180.JPG: 480x640 (no detections), 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygnJMBoX93NOo5Ax6d-WtA_270.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygoB2xFO739tQNpTb06MUg_0.JPG: 480x640 (no detections), 273.1ms
Speed: 1.0ms preprocess, 273.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygoB2xFO739tQNpTb06MUg_90.JPG: 480x640 (no detections), 271.8ms

Speed: 1.0ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygoB2xFO739tQNpTb06MUg_180.JPG: 480x640 (no detections), 276.0ms
Speed: 1.1ms preprocess, 276.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygoB2xFO739tQNpTb06MUg_270.JPG: 480x640 1 Waste, 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygrQgXXb1BXqYhzrPE9_Nw_0.JPG: 480x640 (no detections), 272.4ms
Speed: 1.0ms preprocess, 272.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygrQgXXb1BXqYhzrPE9_Nw_90.JPG: 480x640 (no detections), 269.1ms
Speed: 1.1ms preprocess, 269.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygrQgXXb1BXqYhzrPE9_Nw_180.JPG: 480x640 (no detections), 270.0ms
Speed: 1.0ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygrQgXXb1BXqYhzrPE9_Nw_270.JPG: 480x640 (no detections), 270.7ms
Speed: 1.0ms preprocess, 270.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygsKLaF-65x5TINOfHAE2A_0.JPG: 480x640 (no detections), 270.9ms
Speed: 1.0ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygsKLaF-65x5TINOfHAE2A_90.JPG: 480x640 (no detections), 273.6ms
Speed: 1.1ms preprocess, 273.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygsKLaF-65x5TINOfHAE2A_180.JPG: 480x640 (no detections), 270.4ms
Speed: 1.0ms preprocess, 270.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygsKLaF-65x5TINOfHAE2A_270.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygtyyjJq4Or086GxMejoww_0.JPG: 480x640 (no detections), 270.6ms
Speed: 1.0ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygtyyjJq4Or086GxMejoww_90.JPG: 480x640 (no detections), 270.9ms
Speed: 1.0ms preprocess, 270.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygtyyjJq4Or086GxMejoww_180.JPG: 480x640 (no detections), 275.9ms
Speed: 1.0ms preprocess, 275.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygtyyjJq4Or086GxMejoww_270.JPG: 480x640 (no detections), 266.7ms
Speed: 1.0ms preprocess, 266.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygxpX-OV47dTSFwAI-GTwA_0.JPG: 480x640 (no detections), 270.6ms
Speed: 1.0ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygxpX-OV47dTSFwAI-GTwA_90.JPG: 480x640 (no detections), 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygxpX-OV47dTSFwAI-GTwA_180.JPG: 480x640 (no detections), 272.4ms
Speed: 1.0ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygxpX-OV47dTSFwAI-GTwA_270.JPG: 480x640 (no detections), 270.5ms
Speed: 1.1ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygybPozl884AAAQrDCEKaQ_0.JPG: 480x640 (no detections), 269.6ms
Speed: 1.1ms preprocess, 269.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygybPozl884AAAQrDCEKaQ_90.JPG: 480x640 (no detections), 271.0ms
Speed: 1.0ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygybPozl884AAAQrDCEKaQ_180.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygybPozl884AAAQrDCEKaQ_270.JPG: 480x640 (no detections), 276.2ms
Speed: 1.0ms preprocess, 276.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygypCfBP_luVk4Xd0XVVUQ_0.JPG: 480x640 (no detections), 274.0ms
Speed: 1.0ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygypCfBP_luVk4Xd0XVVUQ_90.JPG: 480x640 (no detections), 270.4ms
Speed: 1.0ms preprocess, 270.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygypCfBP_luVk4Xd0XVVUQ_180.JPG: 480x640 (no detections), 272.8ms
Speed: 1.0ms preprocess, 272.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygypCfBP_luVk4Xd0XVVUQ_270.JPG: 480x640 (no detections), 276.4ms
Speed: 1.1ms preprocess, 276.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygz2SrQakGhwiHeuDZ1aCw_0.JPG: 480x640 (no detections), 271.7ms
Speed: 1.0ms preprocess, 271.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygz2SrQakGhwiHeuDZ1aCw_90.JPG: 480x640 (no detections), 270.3ms
Speed: 1.1ms preprocess, 270.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygz2SrQakGhwiHeuDZ1aCw_180.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/g/ygz2SrQakGhwiHeuDZ1aCw_270.JPG: 480x640 (no detections), 271.3ms
Speed: 1.0ms preprocess, 271.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhBi6rkMxc7Oa3eI6wdvaw_0.JPG: 480x640 (no detections), 272.4ms
Speed: 1.0ms preprocess, 272.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhBi6rkMxc7Oa3eI6wdvaw_90.JPG: 480x640 (no detections), 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhBi6rkMxc7Oa3eI6wdvaw_180.JPG: 480x640 (no detections), 271.9ms
Speed: 1.0ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhBi6rkMxc7Oa3eI6wdvaw_270.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhESWCEUhHZJN3mIBli-Ig_0.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhESWCEUhHZJN3mIBli-Ig_90.JPG: 480x640 (no detections), 269.3ms
Speed: 1.1ms preprocess, 269.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhESWCEUhHZJN3mIBli-Ig_180.JPG: 480x640 (no detections), 274.3ms
Speed: 1.0ms preprocess, 274.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhESWCEUhHZJN3mIBli-Ig_270.JPG: 480x640 (no detections), 275.9ms
Speed: 1.1ms preprocess, 275.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhFOIBBrQablM4oFc5cOKA_0.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhFOIBBrQablM4oFc5cOKA_90.JPG: 480x640 (no detections), 269.0ms
Speed: 1.0ms preprocess, 269.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhFOIBBrQablM4oFc5cOKA_180.JPG: 480x640 (no detections), 272.7ms
Speed: 0.9ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhFOIBBrQablM4oFc5cOKA_270.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhFcfSu7j9OvGAsN1Zix8Q_0.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhFcfSu7j9OvGAsN1Zix8Q_90.JPG: 480x640 (no detections), 270.5ms
Speed: 1.0ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhFcfSu7j9OvGAsN1Zix8Q_180.JPG: 480x640 (no detections), 270.8ms
Speed: 1.0ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhFcfSu7j9OvGAsN1Zix8Q_270.JPG: 480x640 (no detections), 269.8ms
Speed: 1.0ms preprocess, 269.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhKqo_Sv1oivCrGfYqfcOg_0.JPG: 480x640 (no detections), 272.5ms
Speed: 1.1ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhKqo_Sv1oivCrGfYqfcOg_90.JPG: 480x640 (no detections), 274.2ms
Speed: 1.1ms preprocess, 274.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhKqo_Sv1oivCrGfYqfcOg_180.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhKqo_Sv1oivCrGfYqfcOg_270.JPG: 480x640 (no detections), 271.3ms
Speed: 1.0ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhLrH7xU8ou51VF2O77WWQ_0.JPG: 480x640 (no detections), 268.2ms
Speed: 1.0ms preprocess, 268.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhLrH7xU8ou51VF2O77WWQ_90.JPG: 480x640 (no detections), 279.5ms
Speed: 1.1ms preprocess, 279.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhLrH7xU8ou51VF2O77WWQ_180.JPG: 480x640 (no detections), 273.7ms
Speed: 1.0ms preprocess, 273.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhLrH7xU8ou51VF2O77WWQ_270.JPG: 480x640 (no detections), 268.2ms
Speed: 1.1ms preprocess, 268.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhNuEBbYxWfXs7ipVN7gtA_0.JPG: 480x640 (no detections), 275.2ms
Speed: 1.1ms preprocess, 275.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhNuEBbYxWfXs7ipVN7gtA_90.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhNuEBbYxWfXs7ipVN7gtA_180.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhNuEBbYxWfXs7ipVN7gtA_270.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhShcz5ezNlOFoUhK7lsnQ_0.JPG: 480x640 (no detections), 267.7ms
Speed: 1.0ms preprocess, 267.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhShcz5ezNlOFoUhK7lsnQ_90.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhShcz5ezNlOFoUhK7lsnQ_180.JPG: 480x640 (no detections), 271.2ms
Speed: 1.2ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhShcz5ezNlOFoUhK7lsnQ_270.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yh_Dqte0TkP7OrPzSUtmoQ_0.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yh_Dqte0TkP7OrPzSUtmoQ_90.JPG: 480x640 (no detections), 271.3ms
Speed: 1.0ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yh_Dqte0TkP7OrPzSUtmoQ_180.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yh_Dqte0TkP7OrPzSUtmoQ_270.JPG: 480x640 (no detections), 269.1ms
Speed: 1.0ms preprocess, 269.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhe-ovaxQRRs8-V5OKXhXw_0.JPG: 480x640 (no detections), 275.2ms

Speed: 1.1ms preprocess, 275.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhe-ovaxQRRs8-V5OKXhXw_90.JPG: 480x640 (no detections), 268.3ms
Speed: 1.1ms preprocess, 268.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhe-ovaxQRRs8-V5OKXhXw_180.JPG: 480x640 (no detections), 273.1ms
Speed: 1.0ms preprocess, 273.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhe-ovaxQRRs8-V5OKXhXw_270.JPG: 480x640 (no detections), 270.5ms
Speed: 1.1ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhg5RUzwwPpAoyEEV485qw_0.JPG: 480x640 (no detections), 277.4ms
Speed: 1.2ms preprocess, 277.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhg5RUzwwPpAoyEEV485qw_90.JPG: 480x640 (no detections), 280.3ms
Speed: 1.0ms preprocess, 280.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhg5RUzwwPpAoyEEV485qw_180.JPG: 480x640 (no detections), 271.7ms
Speed: 1.2ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhg5RUzwwPpAoyEEV485qw_270.JPG: 480x640 (no detections), 271.3ms
Speed: 1.0ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhhLcO14F6rlTCXnVL9YiA_0.JPG: 480x640 (no detections), 273.0ms
Speed: 1.0ms preprocess, 273.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhhLcO14F6rlTCXnVL9YiA_90.JPG: 480x640 (no detections), 268.7ms
Speed: 1.1ms preprocess, 268.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhhLcO14F6rlTCXnVL9YiA_180.JPG: 480x640 (no detections), 269.2ms
Speed: 1.0ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhhLcO14F6rlTCXnVL9YiA_270.JPG: 480x640 (no detections), 275.8ms
Speed: 1.0ms preprocess, 275.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhpJNQjdmoC7eF5jIP52Vg_0.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhpJNQjdmoC7eF5jIP52Vg_90.JPG: 480x640 (no detections), 274.5ms
Speed: 1.1ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhpJNQjdmoC7eF5jIP52Vg_180.JPG: 480x640 (no detections), 272.4ms
Speed: 1.0ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhpJNQjdmoC7eF5jIP52Vg_270.JPG: 480x640 (no detections), 279.0ms
Speed: 1.1ms preprocess, 279.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhpMuvHQTLVw2wwAlH-NzQ_0.JPG: 480x640 (no detections), 271.7ms
Speed: 1.0ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhpMuvHQTLVw2wwAlH-NzQ_90.JPG: 480x640 (no detections), 274.2ms
Speed: 1.1ms preprocess, 274.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhpMuvHQTLVw2wwAlH-NzQ_180.JPG: 480x640 (no detections), 272.9ms
Speed: 1.0ms preprocess, 272.9ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhpMuvHQTLVw2wwAlH-NzQ_270.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhqWovbiQv1tSZoh6eGBuA_0.JPG: 480x640 (no detections), 268.7ms
Speed: 1.0ms preprocess, 268.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhqWovbiQv1tSZoh6eGBuA_90.JPG: 480x640 (no detections), 269.1ms
Speed: 1.1ms preprocess, 269.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhqWovbiQv1tSZoh6eGBuA_180.JPG: 480x640 (no detections), 276.3ms
Speed: 1.0ms preprocess, 276.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhqWovbiQv1tSZoh6eGBuA_270.JPG: 480x640 (no detections), 274.8ms
Speed: 1.0ms preprocess, 274.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhrsLywSpGx1_v1kHHwgaw_0.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhrsLywSpGx1_v1kHHwgaw_90.JPG: 480x640 (no detections), 269.2ms
Speed: 1.0ms preprocess, 269.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhrsLywSpGx1_v1kHHwgaw_180.JPG: 480x640 (no detections), 275.1ms
Speed: 1.0ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhrsLywSpGx1_v1kHHwgaw_270.JPG: 480x640 (no detections), 270.7ms
Speed: 1.0ms preprocess, 270.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhrwaRmhnN56AMSc34UJWQ_0.JPG: 480x640 (no detections), 271.4ms
Speed: 1.0ms preprocess, 271.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhrwaRmhnN56AMSc34UJWQ_90.JPG: 480x640 (no detections), 275.9ms
Speed: 1.0ms preprocess, 275.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhrwaRmhnN56AMSc34UJWQ_180.JPG: 480x640 (no detections), 270.2ms
Speed: 1.0ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhrwaRmhnN56AMSc34UJWQ_270.JPG: 480x640 (no detections), 271.6ms
Speed: 1.2ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhuY_WHAEkN2d8i7Jo_8og_0.JPG: 480x640 (no detections), 270.4ms
Speed: 1.0ms preprocess, 270.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhuY_WHAEkN2d8i7Jo_8og_90.JPG: 480x640 (no detections), 275.0ms
Speed: 1.0ms preprocess, 275.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhuY_WHAEkN2d8i7Jo_8og_180.JPG: 480x640 (no detections), 269.0ms
Speed: 1.1ms preprocess, 269.0ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhuY_WHAEkN2d8i7Jo_8og_270.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhxF6itmQvYlpoG44NBh_g_0.JPG: 480x640 1 Waste, 270.4ms
Speed: 1.0ms preprocess, 270.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhxF6itmQvYlpoG44NBh_g_90.JPG: 480x640 (no detections), 274.2ms
Speed: 1.1ms preprocess, 274.2ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhxF6itmQvYlpoG44NBh_g_180.JPG: 480x640 (no detections), 276.1ms
Speed: 1.0ms preprocess, 276.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhxF6itmQvYlpoG44NBh_g_270.JPG: 480x640 (no detections), 270.8ms
Speed: 1.0ms preprocess, 270.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhxqZ_y0RB00aXtcb9u2HQ_0.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhxqZ_y0RB00aXtcb9u2HQ_90.JPG: 480x640 (no detections), 271.6ms
Speed: 1.0ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhxqZ_y0RB00aXtcb9u2HQ_180.JPG: 480x640 (no detections), 272.8ms
Speed: 1.0ms preprocess, 272.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhxqZ_y0RB00aXtcb9u2HQ_270.JPG: 480x640 (no detections), 272.3ms
Speed: 1.0ms preprocess, 272.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhxz0KahvVqfiovDu76prw_0.JPG: 480x640 (no detections), 277.4ms
Speed: 1.1ms preprocess, 277.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhxz0KahvVqfiovDu76prw_90.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhxz0KahvVqfiovDu76prw_180.JPG: 480x640 (no detections), 272.1ms
Speed: 1.0ms preprocess, 272.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhxz0KahvVqfiovDu76prw_270.JPG: 480x640 (no detections), 272.5ms
Speed: 1.0ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhzyEJfAuZIfz9TvbNLlEQ_0.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhzyEJfAuZIfz9TvbNLlEQ_90.JPG: 480x640 (no detections), 271.1ms
Speed: 1.0ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhzyEJfAuZIfz9TvbNLlEQ_180.JPG: 480x640 (no detections), 272.5ms
Speed: 1.0ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhzyEJfAuZIfz9TvbNLlEQ_270.JPG: 480x640 (no detections), 276.4ms
Speed: 1.2ms preprocess, 276.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhzzsS2Nba6PnRnFleowNw_0.JPG: 480x640 (no detections), 270.6ms
Speed: 1.8ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhzzsS2Nba6PnRnFleowNw_90.JPG: 480x640 (no detections), 272.1ms
Speed: 1.1ms preprocess, 272.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhzzsS2Nba6PnRnFleowNw_180.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/H/yhzzsS2Nba6PnRnFleowNw_270.JPG: 480x640 (no detections), 272.2ms
Speed: 1.0ms preprocess, 272.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yi-0cpWu79Sdm7IexuWaew_0.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yi-0cpWu79Sdm7IexuWaew_90.JPG: 480x640 (no detections), 272.3ms
Speed: 1.0ms preprocess, 272.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yi-0cpWu79Sdm7IexuWaew_180.JPG: 480x640 (no detections), 274.7ms
Speed: 1.0ms preprocess, 274.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yi-0cpWu79Sdm7IexuWaew_270.JPG: 480x640 (no detections), 276.3ms
Speed: 1.1ms preprocess, 276.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yi32YkIGfVvT2i-BWNCKYA_0.JPG: 480x640 (no detections), 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yi32YkIGfVvT2i-BWNCKYA_90.JPG: 480x640 (no detections), 271.5ms
Speed: 1.0ms preprocess, 271.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yi32YkIGfVvT2i-BWNCKYA_180.JPG: 480x640 (no detections), 270.4ms
Speed: 1.0ms preprocess, 270.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yi32YkIGfVvT2i-BWNCKYA_270.JPG: 480x640 (no detections), 270.1ms
Speed: 1.0ms preprocess, 270.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yi6GavoRZ2CedXTHQTCVzg_0.JPG: 480x640 (no detections), 271.8ms
Speed: 1.0ms preprocess, 271.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yi6GavoRZ2CedXTHQTCVzg_90.JPG: 480x640 (no detections), 271.7ms
Speed: 1.2ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yi6GavoRZ2CedXTHQTCVzg_180.JPG: 480x640 (no detections), 271.5ms
Speed: 1.1ms preprocess, 271.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yi6GavoRZ2CedXTHQTCVzg_270.JPG: 480x640 (no detections), 271.1ms

Speed: 1.0ms preprocess, 271.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yi7sYagFmuR-7h0ptMHGqg_0.JPG: 480x640 (no detections), 270.5ms
Speed: 1.0ms preprocess, 270.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yi7sYagFmuR-7h0ptMHGqg_90.JPG: 480x640 (no detections), 268.6ms
Speed: 1.0ms preprocess, 268.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yi7sYagFmuR-7h0ptMHGqg_180.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yi7sYagFmuR-7h0ptMHGqg_270.JPG: 480x640 1 Waste, 272.7ms
Speed: 1.0ms preprocess, 272.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yi9O64QZ-FMwRKfkOGCvOA_0.JPG: 480x640 (no detections), 269.3ms
Speed: 1.1ms preprocess, 269.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yi9O64QZ-FMwRKfkOGCvOA_90.JPG: 480x640 (no detections), 278.3ms
Speed: 1.0ms preprocess, 278.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yi9O64QZ-FMwRKfkOGCvOA_180.JPG: 480x640 (no detections), 269.8ms
Speed: 1.1ms preprocess, 269.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yi9O64QZ-FMwRKfkOGCvOA_270.JPG: 480x640 (no detections), 268.4ms
Speed: 1.0ms preprocess, 268.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yiBFSkT8Uwz70aquQhwDrA_0.JPG: 480x640 (no detections), 274.3ms
Speed: 1.1ms preprocess, 274.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yiBFSkT8Uwz70aquQhwDrA_90.JPG: 480x640 (no detections), 276.3ms
Speed: 1.2ms preprocess, 276.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yiBFSkT8Uwz70aquQhwDrA_180.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yiBFSkT8Uwz70aquQhwDrA_270.JPG: 480x640 (no detections), 273.9ms
Speed: 1.1ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yiEyRdd8jS1GkRbKFnGArQ_0.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yiEyRdd8jS1GkRbKFnGArQ_90.JPG: 480x640 (no detections), 268.4ms
Speed: 1.1ms preprocess, 268.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yiEyRdd8jS1GkRbKFnGArQ_180.JPG: 480x640 (no detections), 270.4ms
Speed: 1.2ms preprocess, 270.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yiEyRdd8jS1GkRbKFnGArQ_270.JPG: 480x640 (no detections), 273.9ms
Speed: 1.2ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yiJvFnU0WO8xswrNqo7HMw_0.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yiJvFnU0WO8xswrNqo7HMw_90.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yiJvFnU0WO8xswrNqo7HMw_180.JPG: 480x640 (no detections), 274.0ms
Speed: 1.0ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yiJvFnU0WO8xswrNqo7HMw_270.JPG: 480x640 (no detections), 271.8ms
Speed: 1.0ms preprocess, 271.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yiKg9wCHiReAqVXc2EpM3w_0.JPG: 480x640 (no detections), 269.1ms
Speed: 1.1ms preprocess, 269.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yiKg9wCHiReAqVXc2EpM3w_90.JPG: 480x640 (no detections), 272.1ms
Speed: 1.1ms preprocess, 272.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yiKg9wCHiReAqVXc2EpM3w_180.JPG: 480x640 (no detections), 270.7ms
Speed: 1.0ms preprocess, 270.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yiKg9wCHiReAqVXc2EpM3w_270.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yiMqlt_vnpgFWyhNuj6gOw_0.JPG: 480x640 2 Wastes, 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yiMqlt_vnpgFWyhNuj6gOw_90.JPG: 480x640 1 Waste, 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yiMqlt_vnpgFWyhNuj6gOw_180.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yiMqlt_vnpgFWyhNuj6gOw_270.JPG: 480x640 (no detections), 272.4ms
Speed: 1.0ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yiMs6uHQyv0Js_O9_S0OLQ_0.JPG: 480x640 (no detections), 268.2ms
Speed: 1.1ms preprocess, 268.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yiMs6uHQyv0Js_O9_S0OLQ_90.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yiMs6uHQyv0Js_O9_S0OLQ_180.JPG: 480x640 (no detections), 271.3ms
Speed: 1.0ms preprocess, 271.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yiMs6uHQyv0Js_O9_S0OLQ_270.JPG: 480x640 (no detections), 269.0ms
Speed: 1.1ms preprocess, 269.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yiOx_u7snhrZxMc9R6-Q7w_0.JPG: 480x640 (no detections), 272.4ms
Speed: 1.0ms preprocess, 272.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yiOx_u7snhrZxMc9R6-Q7w_90.JPG: 480x640 (no detections), 269.5ms
Speed: 1.0ms preprocess, 269.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yiOx_u7snhrZxMc9R6-Q7w_180.JPG: 480x640 (no detections), 278.1ms
Speed: 1.1ms preprocess, 278.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yiOx_u7snhrZxMc9R6-Q7w_270.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yiQdTszS6FjHmGF3b_M-iw_0.JPG: 480x640 1 Waste, 267.4ms
Speed: 1.0ms preprocess, 267.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yiQdTszS6FjHmGF3b_M-iw_90.JPG: 480x640 (no detections), 268.5ms
Speed: 1.1ms preprocess, 268.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yiQdTszS6FjHmGF3b_M-iw_180.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yiQdTszS6FjHmGF3b_M-iw_270.JPG: 480x640 (no detections), 268.4ms
Speed: 1.1ms preprocess, 268.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yiSQEjWIILQcLAMUMxchGQ_0.JPG: 480x640 (no detections), 271.7ms
Speed: 1.0ms preprocess, 271.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yiSQEjWIILQcLAMUMxchGQ_90.JPG: 480x640 (no detections), 268.9ms
Speed: 1.1ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yiSQEjWIILQcLAMUMxchGQ_180.JPG: 480x640 (no detections), 269.3ms
Speed: 1.1ms preprocess, 269.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yiSQEjWIILQcLAMUMxchGQ_270.JPG: 480x640 (no detections), 276.6ms
Speed: 1.1ms preprocess, 276.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yiUlWvQIX5XojLyxQolEaQ_0.JPG: 480x640 1 Waste, 270.5ms
Speed: 1.0ms preprocess, 270.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yiUlWvQIX5XojLyxQolEaQ_90.JPG: 480x640 (no detections), 271.7ms
Speed: 1.0ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yiUlWvQIX5XojLyxQolEaQ_180.JPG: 480x640 (no detections), 270.8ms
Speed: 1.0ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yiUlWvQIX5XojLyxQolEaQ_270.JPG: 480x640 (no detections), 272.3ms
Speed: 1.2ms preprocess, 272.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yiY5ZZbhTv_eXYn1PYN7sQ_0.JPG: 480x640 (no detections), 271.1ms
Speed: 1.0ms preprocess, 271.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yiY5ZZbhTv_eXYn1PYN7sQ_90.JPG: 480x640 (no detections), 275.7ms
Speed: 1.1ms preprocess, 275.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yiY5ZZbhTv_eXYn1PYN7sQ_180.JPG: 480x640 (no detections), 268.9ms
Speed: 1.1ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yiY5ZZbhTv_eXYn1PYN7sQ_270.JPG: 480x640 (no detections), 272.4ms
Speed: 1.1ms preprocess, 272.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yi_CxMM-WB_8dMe_l5aX_g_0.JPG: 480x640 (no detections), 260.8ms
Speed: 1.1ms preprocess, 260.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yi_CxMM-WB_8dMe_l5aX_g_90.JPG: 480x640 (no detections), 266.7ms
Speed: 1.0ms preprocess, 266.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yi_CxMM-WB_8dMe_l5aX_g_180.JPG: 480x640 (no detections), 269.8ms
Speed: 1.1ms preprocess, 269.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yi_CxMM-WB_8dMe_l5aX_g_270.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yia7-iaxQSGYEhvl_BLC2A_0.JPG: 480x640 (no detections), 273.4ms
Speed: 1.0ms preprocess, 273.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yia7-iaxQSGYEhvl_BLC2A_90.JPG: 480x640 (no detections), 269.5ms
Speed: 1.0ms preprocess, 269.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yia7-iaxQSGYEhvl_BLC2A_180.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yia7-iaxQSGYEhvl_BLC2A_270.JPG: 480x640 (no detections), 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yib5ye3SmBQ3TQkFae-c-g_0.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yib5ye3SmBQ3TQkFae-c-g_90.JPG: 480x640 (no detections), 274.9ms
Speed: 1.1ms preprocess, 274.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yib5ye3SmBQ3TQkFae-c-g_180.JPG: 480x640 (no detections), 275.4ms
Speed: 1.0ms preprocess, 275.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yib5ye3SmBQ3TQkFae-c-g_270.JPG: 480x640 (no detections), 268.3ms
Speed: 1.1ms preprocess, 268.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yietRGlMqciIwh_isskEhg_0.JPG: 480x640 (no detections), 270.4ms
Speed: 1.1ms preprocess, 270.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yietRGlMqciIwh_isskEhg_90.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yietRGlMqciIwh_isskEhg_180.JPG: 480x640 (no detections), 272.9ms

Speed: 1.1ms preprocess, 272.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yietRGlMqciIwh_isskEhg_270.JPG: 480x640 (no detections), 268.8ms
Speed: 1.0ms preprocess, 268.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yieyhSbQK0pnS6Ph9iZwYw_0.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yieyhSbQK0pnS6Ph9iZwYw_90.JPG: 480x640 (no detections), 273.9ms
Speed: 1.1ms preprocess, 273.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yieyhSbQK0pnS6Ph9iZwYw_180.JPG: 480x640 (no detections), 269.9ms
Speed: 1.0ms preprocess, 269.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yieyhSbQK0pnS6Ph9iZwYw_270.JPG: 480x640 (no detections), 269.0ms
Speed: 1.1ms preprocess, 269.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yigIISzk20OPiJxfhykETA_0.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yigIISzk20OPiJxfhykETA_90.JPG: 480x640 (no detections), 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yigIISzk20OPiJxfhykETA_180.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yigIISzk20OPiJxfhykETA_270.JPG: 480x640 (no detections), 270.9ms
Speed: 1.1ms preprocess, 270.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yihRDw4Ytnb6rSUJKYFawA_0.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yihRDw4Ytnb6rSUJKYFawA_90.JPG: 480x640 (no detections), 278.0ms
Speed: 1.3ms preprocess, 278.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yihRDw4Ytnb6rSUJKYFawA_180.JPG: 480x640 (no detections), 279.6ms
Speed: 1.0ms preprocess, 279.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yihRDw4Ytnb6rSUJKYFawA_270.JPG: 480x640 (no detections), 275.9ms
Speed: 1.1ms preprocess, 275.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yijI2zPVAZ3PNJzHuh6sig_0.JPG: 480x640 (no detections), 268.9ms
Speed: 1.0ms preprocess, 268.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yijI2zPVAZ3PNJzHuh6sig_90.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yijI2zPVAZ3PNJzHuh6sig_180.JPG: 480x640 (no detections), 269.0ms
Speed: 1.1ms preprocess, 269.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yijI2zPVAZ3PNJzHuh6sig_270.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yijv3CbA9rG_QkARgh5aFg_0.JPG: 480x640 (no detections), 270.2ms
Speed: 1.2ms preprocess, 270.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yijv3CbA9rG_QkARgh5aFg_90.JPG: 480x640 (no detections), 273.0ms
Speed: 1.0ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yijv3CbA9rG_QkARgh5aFg_180.JPG: 480x640 (no detections), 273.9ms
Speed: 1.0ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yijv3CbA9rG_QkARgh5aFg_270.JPG: 480x640 (no detections), 274.0ms
Speed: 1.1ms preprocess, 274.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yil9qjEBBV6lYXQ2i2E06g_0.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yil9qjEBBV6lYXQ2i2E06g_90.JPG: 480x640 (no detections), 274.1ms
Speed: 1.0ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yil9qjEBBV6lYXQ2i2E06g_180.JPG: 480x640 2 Wastes, 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yil9qjEBBV6lYXQ2i2E06g_270.JPG: 480x640 (no detections), 271.7ms
Speed: 1.0ms preprocess, 271.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yilnkxipacZ-DyUGHuZStQ_0.JPG: 480x640 (no detections), 275.2ms
Speed: 1.0ms preprocess, 275.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yilnkxipacZ-DyUGHuZStQ_90.JPG: 480x640 (no detections), 267.6ms
Speed: 1.0ms preprocess, 267.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yilnkxipacZ-DyUGHuZStQ_180.JPG: 480x640 (no detections), 272.5ms
Speed: 1.0ms preprocess, 272.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yilnkxipacZ-DyUGHuZStQ_270.JPG: 480x640 (no detections), 269.2ms
Speed: 1.1ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yinOPZzRlhOo4L6atsUU_Q_0.JPG: 480x640 (no detections), 273.2ms
Speed: 1.0ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yinOPZzRlhOo4L6atsUU_Q_90.JPG: 480x640 (no detections), 273.4ms
Speed: 1.1ms preprocess, 273.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yinOPZzRlhOo4L6atsUU_Q_180.JPG: 480x640 (no detections), 271.5ms
Speed: 1.0ms preprocess, 271.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yinOPZzRlhOo4L6atsUU_Q_270.JPG: 480x640 (no detections), 274.0ms
Speed: 1.0ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yituFLb32-mOfCesnlxvtA_0.JPG: 480x640 (no detections), 271.1ms
Speed: 1.0ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yituFLb32-mOfCesnlxvtA_90.JPG: 480x640 (no detections), 269.5ms
Speed: 1.1ms preprocess, 269.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yituFLb32-mOfCesnlxvtA_180.JPG: 480x640 (no detections), 275.4ms
Speed: 1.0ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yituFLb32-mOfCesnlxvtA_270.JPG: 480x640 (no detections), 272.1ms
Speed: 1.0ms preprocess, 272.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yiv4cs8zd_ercQX4ocoQDA_0.JPG: 480x640 (no detections), 271.7ms
Speed: 1.0ms preprocess, 271.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yiv4cs8zd_ercQX4ocoQDA_90.JPG: 480x640 (no detections), 275.0ms
Speed: 1.0ms preprocess, 275.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yiv4cs8zd_ercQX4ocoQDA_180.JPG: 480x640 (no detections), 273.1ms
Speed: 1.0ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/i/yiv4cs8zd_ercQX4ocoQDA_270.JPG: 480x640 (no detections), 272.1ms
Speed: 1.0ms preprocess, 272.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yj1lUNnz59Ze_sdF2c7O2Q_0.JPG: 480x640 (no detections), 278.1ms
Speed: 1.1ms preprocess, 278.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yj1lUNnz59Ze_sdF2c7O2Q_90.JPG: 480x640 (no detections), 267.8ms
Speed: 1.1ms preprocess, 267.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yj1lUNnz59Ze_sdF2c7O2Q_180.JPG: 480x640 (no detections), 274.5ms
Speed: 1.1ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yj1lUNnz59Ze_sdF2c7O2Q_270.JPG: 480x640 (no detections), 272.0ms
Speed: 1.2ms preprocess, 272.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yj4kfSnq9P0cKvlm80Q4VQ_0.JPG: 480x640 (no detections), 270.5ms
Speed: 1.0ms preprocess, 270.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yj4kfSnq9P0cKvlm80Q4VQ_90.JPG: 480x640 (no detections), 271.2ms
Speed: 1.0ms preprocess, 271.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yj4kfSnq9P0cKvlm80Q4VQ_180.JPG: 480x640 (no detections), 272.3ms
Speed: 1.1ms preprocess, 272.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yj4kfSnq9P0cKvlm80Q4VQ_270.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yj97EuHsB0_JzdLbX2NT-g_0.JPG: 480x640 (no detections), 271.4ms
Speed: 1.0ms preprocess, 271.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yj97EuHsB0_JzdLbX2NT-g_90.JPG: 480x640 (no detections), 272.0ms
Speed: 1.0ms preprocess, 272.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yj97EuHsB0_JzdLbX2NT-g_180.JPG: 480x640 (no detections), 269.9ms
Speed: 1.0ms preprocess, 269.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yj97EuHsB0_JzdLbX2NT-g_270.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yj9Vg-ehuWyY8EXL16QfAQ_0.JPG: 480x640 1 Waste, 273.1ms
Speed: 1.1ms preprocess, 273.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yj9Vg-ehuWyY8EXL16QfAQ_90.JPG: 480x640 (no detections), 276.0ms
Speed: 1.0ms preprocess, 276.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yj9Vg-ehuWyY8EXL16QfAQ_180.JPG: 480x640 (no detections), 269.3ms
Speed: 1.2ms preprocess, 269.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yj9Vg-ehuWyY8EXL16QfAQ_270.JPG: 480x640 (no detections), 271.0ms
Speed: 1.1ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjBmvEIq5h0tzL88CJEC6w_0.JPG: 480x640 (no detections), 269.9ms
Speed: 1.0ms preprocess, 269.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjBmvEIq5h0tzL88CJEC6w_90.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjBmvEIq5h0tzL88CJEC6w_180.JPG: 480x640 (no detections), 271.1ms
Speed: 1.0ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjBmvEIq5h0tzL88CJEC6w_270.JPG: 480x640 (no detections), 275.5ms
Speed: 1.0ms preprocess, 275.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjDs3jHRlw1rC60P2OKovA_0.JPG: 480x640 (no detections), 273.1ms
Speed: 1.1ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjDs3jHRlw1rC60P2OKovA_90.JPG: 480x640 1 Waste, 271.5ms
Speed: 1.1ms preprocess, 271.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjDs3jHRlw1rC60P2OKovA_180.JPG: 480x640 (no detections), 298.8ms
Speed: 1.2ms preprocess, 298.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjDs3jHRlw1rC60P2OKovA_270.JPG: 480x640 (no detections), 304.5ms
Speed: 1.3ms preprocess, 304.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjEVyR9XJoxzZHsUVoZN5A_0.JPG: 480x640 (no detections), 296.3ms
Speed: 1.1ms preprocess, 296.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjEVyR9XJoxzZHsUVoZN5A_90.JPG: 480x640 (no detections), 289.5ms

Speed: 1.1ms preprocess, 289.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjEVyR9XJoxzZHsUVoZN5A_180.JPG: 480x640 (no detections), 297.3ms
Speed: 1.2ms preprocess, 297.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjEVyR9XJoxzZHsUVoZN5A_270.JPG: 480x640 (no detections), 297.1ms
Speed: 1.3ms preprocess, 297.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjGJBNx9_-urT44E02FNtg_0.JPG: 480x640 (no detections), 295.9ms
Speed: 1.5ms preprocess, 295.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjGJBNx9_-urT44E02FNtg_90.JPG: 480x640 (no detections), 274.9ms
Speed: 1.0ms preprocess, 274.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjGJBNx9_-urT44E02FNtg_180.JPG: 480x640 (no detections), 272.9ms
Speed: 1.2ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjGJBNx9_-urT44E02FNtg_270.JPG: 480x640 (no detections), 273.4ms
Speed: 1.1ms preprocess, 273.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjJOfPrlgE676pvNEp6xfw_0.JPG: 480x640 (no detections), 268.8ms
Speed: 1.0ms preprocess, 268.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjJOfPrlgE676pvNEp6xfw_90.JPG: 480x640 (no detections), 271.5ms
Speed: 1.0ms preprocess, 271.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjJOfPrlgE676pvNEp6xfw_180.JPG: 480x640 (no detections), 270.4ms
Speed: 1.0ms preprocess, 270.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjJOfPrlgE676pvNEp6xfw_270.JPG: 480x640 (no detections), 270.9ms
Speed: 1.0ms preprocess, 270.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjM0632H3SVVSKZadl3vwg_0.JPG: 480x640 (no detections), 272.5ms
Speed: 1.0ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjM0632H3SVVSKZadl3vwg_90.JPG: 480x640 (no detections), 273.8ms
Speed: 1.0ms preprocess, 273.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjM0632H3SVVSKZadl3vwg_180.JPG: 480x640 (no detections), 273.8ms
Speed: 1.0ms preprocess, 273.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjM0632H3SVVSKZadl3vwg_270.JPG: 480x640 (no detections), 268.4ms
Speed: 1.0ms preprocess, 268.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjMQT1wvaeyw-3E-xa1Ebw_0.JPG: 480x640 (no detections), 270.4ms
Speed: 1.0ms preprocess, 270.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjMQT1wvaeyw-3E-xa1Ebw_90.JPG: 480x640 (no detections), 273.1ms
Speed: 1.1ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjMQT1wvaeyw-3E-xa1Ebw_180.JPG: 480x640 (no detections), 275.3ms
Speed: 1.1ms preprocess, 275.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjMQT1wvaeyw-3E-xa1Ebw_270.JPG: 480x640 (no detections), 275.6ms
Speed: 1.1ms preprocess, 275.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjNDZKyoh5HcQFbKmds8aQ_0.JPG: 480x640 1 Waste, 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjNDZKyoh5HcQFbKmds8aQ_90.JPG: 480x640 (no detections), 273.0ms
Speed: 1.0ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjNDZKyoh5HcQFbKmds8aQ_180.JPG: 480x640 (no detections), 272.2ms
Speed: 1.0ms preprocess, 272.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjNDZKyoh5HcQFbKmds8aQ_270.JPG: 480x640 (no detections), 273.4ms
Speed: 1.0ms preprocess, 273.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjP_pVRqhQjgsPF-GByhhg_0.JPG: 480x640 (no detections), 272.9ms
Speed: 1.0ms preprocess, 272.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjP_pVRqhQjgsPF-GByhhg_90.JPG: 480x640 (no detections), 277.0ms
Speed: 1.1ms preprocess, 277.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjP_pVRqhQjgsPF-GByhhg_180.JPG: 480x640 (no detections), 270.5ms
Speed: 1.1ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjP_pVRqhQjgsPF-GByhhg_270.JPG: 480x640 (no detections), 273.7ms
Speed: 1.0ms preprocess, 273.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjSev_ztsW5-AhChYk3b1w_0.JPG: 480x640 (no detections), 272.2ms
Speed: 1.2ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjSev_ztsW5-AhChYk3b1w_90.JPG: 480x640 (no detections), 270.5ms
Speed: 1.1ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjSev_ztsW5-AhChYk3b1w_180.JPG: 480x640 (no detections), 273.9ms
Speed: 1.1ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjSev_ztsW5-AhChYk3b1w_270.JPG: 480x640 (no detections), 268.3ms
Speed: 1.1ms preprocess, 268.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjV4R-VniDPOuIAXsc902Q_0.JPG: 480x640 (no detections), 274.4ms
Speed: 1.0ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjV4R-VniDPOuIAXsc902Q_90.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjV4R-VniDPOuIAXsc902Q_180.JPG: 480x640 (no detections), 272.0ms
Speed: 1.1ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjV4R-VniDPOuIAXsc902Q_270.JPG: 480x640 (no detections), 270.4ms
Speed: 1.0ms preprocess, 270.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjXBwdV2LsjT3MH5mC6LGw_0.JPG: 480x640 (no detections), 272.7ms
Speed: 1.0ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjXBwdV2LsjT3MH5mC6LGw_90.JPG: 480x640 (no detections), 270.1ms
Speed: 1.3ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjXBwdV2LsjT3MH5mC6LGw_180.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjXBwdV2LsjT3MH5mC6LGw_270.JPG: 480x640 (no detections), 275.2ms
Speed: 1.0ms preprocess, 275.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjYGhGleL6UGGx_RWvhnbw_0.JPG: 480x640 (no detections), 270.3ms
Speed: 1.0ms preprocess, 270.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjYGhGleL6UGGx_RWvhnbw_90.JPG: 480x640 (no detections), 274.4ms
Speed: 1.0ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjYGhGleL6UGGx_RWvhnbw_180.JPG: 480x640 (no detections), 276.7ms
Speed: 1.1ms preprocess, 276.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjYGhGleL6UGGx_RWvhnbw_270.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjYi0FPZgkH4lz8ITKVQZA_0.JPG: 480x640 (no detections), 268.9ms
Speed: 1.1ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjYi0FPZgkH4lz8ITKVQZA_90.JPG: 480x640 (no detections), 270.0ms
Speed: 1.2ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjYi0FPZgkH4lz8ITKVQZA_180.JPG: 480x640 (no detections), 269.6ms
Speed: 1.1ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjYi0FPZgkH4lz8ITKVQZA_270.JPG: 480x640 (no detections), 275.8ms
Speed: 1.1ms preprocess, 275.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yj_QjgQazgzcVXw4idjspw_0.JPG: 480x640 (no detections), 270.0ms
Speed: 1.2ms preprocess, 270.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yj_QjgQazgzcVXw4idjspw_90.JPG: 480x640 (no detections), 274.0ms
Speed: 1.0ms preprocess, 274.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yj_QjgQazgzcVXw4idjspw_180.JPG: 480x640 (no detections), 274.6ms
Speed: 1.0ms preprocess, 274.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yj_QjgQazgzcVXw4idjspw_270.JPG: 480x640 (no detections), 271.0ms
Speed: 1.1ms preprocess, 271.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yj_aVjblr9Y4OrcXkZEi8w_0.JPG: 480x640 (no detections), 269.9ms
Speed: 1.0ms preprocess, 269.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yj_aVjblr9Y4OrcXkZEi8w_90.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yj_aVjblr9Y4OrcXkZEi8w_180.JPG: 480x640 (no detections), 269.3ms
Speed: 1.1ms preprocess, 269.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yj_aVjblr9Y4OrcXkZEi8w_270.JPG: 480x640 (no detections), 276.0ms
Speed: 1.0ms preprocess, 276.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjfStb6nNi9RDpuFGBiVmQ_0.JPG: 480x640 (no detections), 268.7ms
Speed: 1.1ms preprocess, 268.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjfStb6nNi9RDpuFGBiVmQ_90.JPG: 480x640 (no detections), 270.9ms
Speed: 1.1ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjfStb6nNi9RDpuFGBiVmQ_180.JPG: 480x640 (no detections), 272.3ms
Speed: 1.0ms preprocess, 272.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjfStb6nNi9RDpuFGBiVmQ_270.JPG: 480x640 (no detections), 274.1ms
Speed: 1.0ms preprocess, 274.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjfX1zxIhKZZGnNzjJewEg_0.JPG: 480x640 (no detections), 270.8ms
Speed: 1.0ms preprocess, 270.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjfX1zxIhKZZGnNzjJewEg_90.JPG: 480x640 (no detections), 277.4ms
Speed: 1.0ms preprocess, 277.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjfX1zxIhKZZGnNzjJewEg_180.JPG: 480x640 (no detections), 274.4ms
Speed: 1.1ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjfX1zxIhKZZGnNzjJewEg_270.JPG: 480x640 (no detections), 272.1ms
Speed: 1.1ms preprocess, 272.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjgcEX3XJ_GAbak5y0G2ZQ_0.JPG: 480x640 (no detections), 274.7ms
Speed: 1.0ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjgcEX3XJ_GAbak5y0G2ZQ_90.JPG: 480x640 (no detections), 268.9ms
Speed: 1.0ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjgcEX3XJ_GAbak5y0G2ZQ_180.JPG: 480x640 (no detections), 270.5ms
Speed: 1.1ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjgcEX3XJ_GAbak5y0G2ZQ_270.JPG: 480x640 (no detections), 272.7ms
Speed: 1.0ms preprocess, 272.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjhk2YZ7mJPUBjdI134hIQ_0.JPG: 480x640 (no detections), 274.8ms

Speed: 1.1ms preprocess, 274.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjhk2YZ7mJPUBjdI134hIQ_90.JPG: 480x640 (no detections), 265.0ms
Speed: 1.1ms preprocess, 265.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjhk2YZ7mJPUBjdI134hIQ_180.JPG: 480x640 (no detections), 267.8ms
Speed: 1.0ms preprocess, 267.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjhk2YZ7mJPUBjdI134hIQ_270.JPG: 480x640 (no detections), 270.9ms
Speed: 1.0ms preprocess, 270.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjjIacPOp3BkMxOYIXLj2w_0.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjjIacPOp3BkMxOYIXLj2w_90.JPG: 480x640 (no detections), 274.5ms
Speed: 1.3ms preprocess, 274.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjjIacPOp3BkMxOYIXLj2w_180.JPG: 480x640 (no detections), 278.1ms
Speed: 1.0ms preprocess, 278.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjjIacPOp3BkMxOYIXLj2w_270.JPG: 480x640 1 Waste, 275.6ms
Speed: 1.0ms preprocess, 275.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjjv4or3vDP3BH-nMjnu1Q_0.JPG: 480x640 (no detections), 278.3ms
Speed: 1.1ms preprocess, 278.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjjv4or3vDP3BH-nMjnu1Q_90.JPG: 480x640 (no detections), 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjjv4or3vDP3BH-nMjnu1Q_180.JPG: 480x640 (no detections), 271.0ms
Speed: 1.1ms preprocess, 271.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjjv4or3vDP3BH-nMjnu1Q_270.JPG: 480x640 (no detections), 271.9ms
Speed: 1.0ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjlmnGMqnyG9BcZBi6hLMg_0.JPG: 480x640 (no detections), 275.8ms
Speed: 1.1ms preprocess, 275.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjlmnGMqnyG9BcZBi6hLMg_90.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjlmnGMqnyG9BcZBi6hLMg_180.JPG: 480x640 (no detections), 273.1ms
Speed: 1.1ms preprocess, 273.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjlmnGMqnyG9BcZBi6hLMg_270.JPG: 480x640 (no detections), 271.6ms
Speed: 1.0ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjoJQ_iRlKs_6uo6_G9Bcw_0.JPG: 480x640 (no detections), 275.0ms
Speed: 1.0ms preprocess, 275.0ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjoJQ_iRlKs_6uo6_G9Bcw_90.JPG: 480x640 (no detections), 274.5ms
Speed: 1.0ms preprocess, 274.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjoJQ_iRlKs_6uo6_G9Bcw_180.JPG: 480x640 (no detections), 273.4ms
Speed: 1.0ms preprocess, 273.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjoJQ_iRlKs_6uo6_G9Bcw_270.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjr1eMHzF_0V1uHmnn1iUQ_0.JPG: 480x640 (no detections), 274.5ms
Speed: 1.0ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjr1eMHzF_0V1uHmnn1iUQ_90.JPG: 480x640 (no detections), 273.9ms
Speed: 1.1ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjr1eMHzF_0V1uHmnn1iUQ_180.JPG: 480x640 (no detections), 278.4ms
Speed: 1.1ms preprocess, 278.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjr1eMHzF_0V1uHmnn1iUQ_270.JPG: 480x640 1 Waste, 277.9ms
Speed: 1.1ms preprocess, 277.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjs3-D1Nm90TrsRv5e-TuA_0.JPG: 480x640 (no detections), 271.1ms
Speed: 1.0ms preprocess, 271.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjs3-D1Nm90TrsRv5e-TuA_90.JPG: 480x640 (no detections), 270.4ms
Speed: 1.0ms preprocess, 270.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjs3-D1Nm90TrsRv5e-TuA_180.JPG: 480x640 (no detections), 270.1ms
Speed: 1.0ms preprocess, 270.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjs3-D1Nm90TrsRv5e-TuA_270.JPG: 480x640 1 Waste, 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjyN33lbZgK436POKyONkw_0.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjyN33lbZgK436POKyONkw_90.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjyN33lbZgK436POKyONkw_180.JPG: 480x640 (no detections), 273.8ms
Speed: 1.0ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjyN33lbZgK436POKyONkw_270.JPG: 480x640 (no detections), 272.9ms
Speed: 1.2ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjzqlIvtHVa53sLfzZS12w_0.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjzqlIvtHVa53sLfzZS12w_90.JPG: 480x640 (no detections), 272.6ms
Speed: 1.0ms preprocess, 272.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjzqlIvtHVa53sLfzZS12w_180.JPG: 480x640 (no detections), 271.7ms
Speed: 1.3ms preprocess, 271.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/j/yjzqlIvtHVa53sLfzZS12w_270.JPG: 480x640 (no detections), 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yk1pM2PH_hbiwcj8Kf1yWw_0.JPG: 480x640 (no detections), 268.7ms
Speed: 1.1ms preprocess, 268.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yk1pM2PH_hbiwcj8Kf1yWw_90.JPG: 480x640 (no detections), 276.0ms
Speed: 1.1ms preprocess, 276.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yk1pM2PH_hbiwcj8Kf1yWw_180.JPG: 480x640 (no detections), 280.5ms
Speed: 1.1ms preprocess, 280.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yk1pM2PH_hbiwcj8Kf1yWw_270.JPG: 480x640 2 Wastes, 273.2ms
Speed: 1.0ms preprocess, 273.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yk4hTEAMS70gwVnCKLJh3g_0.JPG: 480x640 (no detections), 274.6ms
Speed: 1.1ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yk4hTEAMS70gwVnCKLJh3g_90.JPG: 480x640 (no detections), 268.0ms
Speed: 1.0ms preprocess, 268.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yk4hTEAMS70gwVnCKLJh3g_180.JPG: 480x640 (no detections), 276.2ms
Speed: 1.1ms preprocess, 276.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yk4hTEAMS70gwVnCKLJh3g_270.JPG: 480x640 (no detections), 274.2ms
Speed: 1.1ms preprocess, 274.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yk4x4bOvc8g4JazZPKLGlw_0.JPG: 480x640 (no detections), 268.9ms
Speed: 1.1ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yk4x4bOvc8g4JazZPKLGlw_90.JPG: 480x640 (no detections), 275.2ms
Speed: 1.0ms preprocess, 275.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yk4x4bOvc8g4JazZPKLGlw_180.JPG: 480x640 (no detections), 276.8ms
Speed: 1.1ms preprocess, 276.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yk4x4bOvc8g4JazZPKLGlw_270.JPG: 480x640 (no detections), 271.6ms
Speed: 1.0ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yk6TN8i7BODENOm1usTlzA_0.JPG: 480x640 (no detections), 273.3ms
Speed: 1.0ms preprocess, 273.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yk6TN8i7BODENOm1usTlzA_90.JPG: 480x640 (no detections), 274.4ms
Speed: 1.0ms preprocess, 274.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yk6TN8i7BODENOm1usTlzA_180.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/yk6TN8i7BODENOm1usTlzA_270.JPG: 480x640 (no detections), 269.5ms
Speed: 1.0ms preprocess, 269.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykCv6ZloTxDIlHbqfix0kA_0.JPG: 480x640 (no detections), 273.6ms
Speed: 1.0ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykCv6ZloTxDIlHbqfix0kA_90.JPG: 480x640 (no detections), 268.7ms
Speed: 1.0ms preprocess, 268.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykCv6ZloTxDIlHbqfix0kA_180.JPG: 480x640 (no detections), 272.3ms
Speed: 1.1ms preprocess, 272.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykCv6ZloTxDIlHbqfix0kA_270.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykDLbQm6ZVQLO8LvEztAYg_0.JPG: 480x640 (no detections), 273.2ms
Speed: 1.1ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykDLbQm6ZVQLO8LvEztAYg_90.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykDLbQm6ZVQLO8LvEztAYg_180.JPG: 480x640 (no detections), 267.9ms
Speed: 1.1ms preprocess, 267.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykDLbQm6ZVQLO8LvEztAYg_270.JPG: 480x640 (no detections), 274.6ms
Speed: 1.0ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykGGojTI6jhcuVsL6d7tgA_0.JPG: 480x640 (no detections), 270.9ms
Speed: 1.1ms preprocess, 270.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykGGojTI6jhcuVsL6d7tgA_90.JPG: 480x640 (no detections), 273.4ms
Speed: 1.0ms preprocess, 273.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykGGojTI6jhcuVsL6d7tgA_180.JPG: 480x640 (no detections), 274.2ms
Speed: 1.2ms preprocess, 274.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykGGojTI6jhcuVsL6d7tgA_270.JPG: 480x640 (no detections), 276.7ms
Speed: 1.1ms preprocess, 276.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykGJ75miMDvXYrZyCut06Q_0.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykGJ75miMDvXYrZyCut06Q_90.JPG: 480x640 (no detections), 276.9ms
Speed: 1.0ms preprocess, 276.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykGJ75miMDvXYrZyCut06Q_180.JPG: 480x640 (no detections), 284.9ms
Speed: 1.2ms preprocess, 284.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykGJ75miMDvXYrZyCut06Q_270.JPG: 480x640 (no detections), 287.1ms

Speed: 1.1ms preprocess, 287.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykI6na7eMhfXH6usEK7Ekg_0.JPG: 480x640 (no detections), 276.6ms
Speed: 1.0ms preprocess, 276.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykI6na7eMhfXH6usEK7Ekg_90.JPG: 480x640 (no detections), 317.1ms
Speed: 1.3ms preprocess, 317.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykI6na7eMhfXH6usEK7Ekg_180.JPG: 480x640 (no detections), 283.8ms
Speed: 1.4ms preprocess, 283.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykI6na7eMhfXH6usEK7Ekg_270.JPG: 480x640 (no detections), 273.1ms
Speed: 1.2ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykIztV29nkiLkKLjMq7gWw_0.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykIztV29nkiLkKLjMq7gWw_90.JPG: 480x640 (no detections), 271.5ms
Speed: 1.1ms preprocess, 271.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykIztV29nkiLkKLjMq7gWw_180.JPG: 480x640 (no detections), 271.1ms
Speed: 1.0ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykIztV29nkiLkKLjMq7gWw_270.JPG: 480x640 (no detections), 271.2ms
Speed: 1.2ms preprocess, 271.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykJMdyncJefz2AEeJLfHwg_0.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykJMdyncJefz2AEeJLfHwg_90.JPG: 480x640 (no detections), 270.6ms
Speed: 1.0ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykJMdyncJefz2AEeJLfHwg_180.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykJMdyncJefz2AEeJLfHwg_270.JPG: 480x640 (no detections), 274.9ms
Speed: 1.2ms preprocess, 274.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykLr1VMc2gwp68C4X7gNEA_0.JPG: 480x640 (no detections), 274.4ms
Speed: 1.1ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykLr1VMc2gwp68C4X7gNEA_90.JPG: 480x640 (no detections), 274.5ms
Speed: 1.1ms preprocess, 274.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykLr1VMc2gwp68C4X7gNEA_180.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykLr1VMc2gwp68C4X7gNEA_270.JPG: 480x640 (no detections), 275.0ms
Speed: 1.1ms preprocess, 275.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykOaQQt3wIYT4bNbZZZY6A_0.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykOaQQt3wIYT4bNbZZZY6A_90.JPG: 480x640 (no detections), 273.8ms
Speed: 1.2ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykOaQQt3wIYT4bNbZZZY6A_180.JPG: 480x640 (no detections), 275.1ms
Speed: 1.0ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykOaQQt3wIYT4bNbZZZY6A_270.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykP9HvBptyCXHwVrNTw0zA_0.JPG: 480x640 (no detections), 272.6ms
Speed: 1.0ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykP9HvBptyCXHwVrNTw0zA_90.JPG: 480x640 (no detections), 278.6ms
Speed: 1.2ms preprocess, 278.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykP9HvBptyCXHwVrNTw0zA_180.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykP9HvBptyCXHwVrNTw0zA_270.JPG: 480x640 (no detections), 269.3ms
Speed: 1.0ms preprocess, 269.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykQi6bBp30Sk_3c2Ebkezw_0.JPG: 480x640 (no detections), 268.7ms
Speed: 1.0ms preprocess, 268.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykQi6bBp30Sk_3c2Ebkezw_90.JPG: 480x640 (no detections), 269.4ms
Speed: 1.1ms preprocess, 269.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykQi6bBp30Sk_3c2Ebkezw_180.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykQi6bBp30Sk_3c2Ebkezw_270.JPG: 480x640 (no detections), 278.5ms
Speed: 1.2ms preprocess, 278.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykQyw8EFN2RPVS9DRdZxnw_0.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykQyw8EFN2RPVS9DRdZxnw_90.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykQyw8EFN2RPVS9DRdZxnw_180.JPG: 480x640 (no detections), 270.3ms
Speed: 1.1ms preprocess, 270.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykQyw8EFN2RPVS9DRdZxnw_270.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykWnwBz6nfebekRmNbkuEQ_0.JPG: 480x640 (no detections), 271.0ms
Speed: 1.1ms preprocess, 271.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykWnwBz6nfebekRmNbkuEQ_90.JPG: 480x640 (no detections), 269.8ms
Speed: 1.0ms preprocess, 269.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykWnwBz6nfebekRmNbkuEQ_180.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykWnwBz6nfebekRmNbkuEQ_270.JPG: 480x640 1 Waste, 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykaT7nLu7lZAgp9-z-cNxQ_0.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykaT7nLu7lZAgp9-z-cNxQ_90.JPG: 480x640 (no detections), 269.0ms
Speed: 1.0ms preprocess, 269.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykaT7nLu7lZAgp9-z-cNxQ_180.JPG: 480x640 1 Waste, 270.3ms
Speed: 1.1ms preprocess, 270.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykaT7nLu7lZAgp9-z-cNxQ_270.JPG: 480x640 (no detections), 275.0ms
Speed: 1.0ms preprocess, 275.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykb4NG25w3ccPvW-z-EsZw_0.JPG: 480x640 1 Waste, 269.8ms
Speed: 1.2ms preprocess, 269.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykb4NG25w3ccPvW-z-EsZw_90.JPG: 480x640 (no detections), 274.7ms
Speed: 1.0ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykb4NG25w3ccPvW-z-EsZw_180.JPG: 480x640 (no detections), 274.3ms
Speed: 1.1ms preprocess, 274.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykb4NG25w3ccPvW-z-EsZw_270.JPG: 480x640 (no detections), 271.6ms
Speed: 1.0ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykimbnHPIybtNmv82YWfhw_0.JPG: 480x640 (no detections), 274.4ms
Speed: 1.0ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykimbnHPIybtNmv82YWfhw_90.JPG: 480x640 (no detections), 269.8ms
Speed: 1.1ms preprocess, 269.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykimbnHPIybtNmv82YWfhw_180.JPG: 480x640 (no detections), 270.3ms
Speed: 1.0ms preprocess, 270.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykimbnHPIybtNmv82YWfhw_270.JPG: 480x640 (no detections), 269.0ms
Speed: 1.2ms preprocess, 269.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykk3rTPscxiaomFJ370UMQ_0.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykk3rTPscxiaomFJ370UMQ_90.JPG: 480x640 (no detections), 266.9ms
Speed: 1.1ms preprocess, 266.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykk3rTPscxiaomFJ370UMQ_180.JPG: 480x640 (no detections), 272.3ms
Speed: 1.1ms preprocess, 272.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykk3rTPscxiaomFJ370UMQ_270.JPG: 480x640 (no detections), 270.9ms
Speed: 1.2ms preprocess, 270.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykkWWC4-H2YvNhgldOcKNg_0.JPG: 480x640 (no detections), 275.7ms
Speed: 1.1ms preprocess, 275.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykkWWC4-H2YvNhgldOcKNg_90.JPG: 480x640 1 Waste, 272.5ms
Speed: 1.1ms preprocess, 272.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykkWWC4-H2YvNhgldOcKNg_180.JPG: 480x640 (no detections), 270.2ms
Speed: 1.0ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykkWWC4-H2YvNhgldOcKNg_270.JPG: 480x640 (no detections), 276.5ms
Speed: 1.1ms preprocess, 276.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykmJL4Cq1xUSuwObtE0XdA_0.JPG: 480x640 (no detections), 277.3ms
Speed: 1.2ms preprocess, 277.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykmJL4Cq1xUSuwObtE0XdA_90.JPG: 480x640 (no detections), 277.5ms
Speed: 1.2ms preprocess, 277.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykmJL4Cq1xUSuwObtE0XdA_180.JPG: 480x640 (no detections), 278.7ms
Speed: 1.1ms preprocess, 278.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykmJL4Cq1xUSuwObtE0XdA_270.JPG: 480x640 (no detections), 270.5ms
Speed: 1.2ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykni24-3NgQPl-MG1pPAQg_0.JPG: 480x640 (no detections), 269.6ms
Speed: 1.1ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykni24-3NgQPl-MG1pPAQg_90.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykni24-3NgQPl-MG1pPAQg_180.JPG: 480x640 (no detections), 272.4ms
Speed: 1.1ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykni24-3NgQPl-MG1pPAQg_270.JPG: 480x640 (no detections), 270.5ms
Speed: 1.0ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykvMwuqOvTMYJjrShhU4Qw_0.JPG: 480x640 (no detections), 273.4ms
Speed: 1.1ms preprocess, 273.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykvMwuqOvTMYJjrShhU4Qw_90.JPG: 480x640 (no detections), 271.0ms
Speed: 1.1ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykvMwuqOvTMYJjrShhU4Qw_180.JPG: 480x640 (no detections), 273.3ms

Speed: 1.1ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/K/ykvMwuqOvTMYJjrShhU4Qw_270.JPG: 480x640 (no detections), 274.0ms
Speed: 1.0ms preprocess, 274.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yl0NrvZz50lj2Qnl9Ve7mA_0.JPG: 480x640 (no detections), 272.8ms
Speed: 1.0ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yl0NrvZz50lj2Qnl9Ve7mA_90.JPG: 480x640 (no detections), 274.1ms
Speed: 1.2ms preprocess, 274.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yl0NrvZz50lj2Qnl9Ve7mA_180.JPG: 480x640 (no detections), 274.8ms
Speed: 1.0ms preprocess, 274.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yl0NrvZz50lj2Qnl9Ve7mA_270.JPG: 480x640 (no detections), 274.4ms
Speed: 1.0ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yl164toT5-BUL9CqpIJKXw_0.JPG: 480x640 (no detections), 272.7ms
Speed: 1.0ms preprocess, 272.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yl164toT5-BUL9CqpIJKXw_90.JPG: 480x640 (no detections), 269.6ms
Speed: 1.0ms preprocess, 269.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yl164toT5-BUL9CqpIJKXw_180.JPG: 480x640 (no detections), 272.4ms
Speed: 1.0ms preprocess, 272.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yl164toT5-BUL9CqpIJKXw_270.JPG: 480x640 (no detections), 271.1ms
Speed: 1.0ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yl1W2N4N7QAW_J2_pfB7fw_0.JPG: 480x640 1 Waste, 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yl1W2N4N7QAW_J2_pfB7fw_90.JPG: 480x640 1 Waste, 270.5ms
Speed: 1.1ms preprocess, 270.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yl1W2N4N7QAW_J2_pfB7fw_180.JPG: 480x640 (no detections), 268.9ms
Speed: 1.1ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yl1W2N4N7QAW_J2_pfB7fw_270.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yl2t7l7smuj98ns96Nif9w_0.JPG: 480x640 (no detections), 270.9ms
Speed: 1.0ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yl2t7l7smuj98ns96Nif9w_90.JPG: 480x640 (no detections), 269.0ms
Speed: 1.1ms preprocess, 269.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yl2t7l7smuj98ns96Nif9w_180.JPG: 480x640 (no detections), 274.8ms
Speed: 1.0ms preprocess, 274.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yl2t7l7smuj98ns96Nif9w_270.JPG: 480x640 (no detections), 272.0ms
Speed: 1.0ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yl3apETUXZmijUfKzJnBLA_0.JPG: 480x640 (no detections), 271.6ms
Speed: 1.0ms preprocess, 271.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yl3apETUXZmijUfKzJnBLA_90.JPG: 480x640 (no detections), 272.5ms
Speed: 1.1ms preprocess, 272.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yl3apETUXZmijUfKzJnBLA_180.JPG: 480x640 (no detections), 271.4ms
Speed: 1.0ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yl3apETUXZmijUfKzJnBLA_270.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yl5yFKvzKQJsNQUxLMg9bg_0.JPG: 480x640 (no detections), 272.9ms
Speed: 1.0ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yl5yFKvzKQJsNQUxLMg9bg_90.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yl5yFKvzKQJsNQUxLMg9bg_180.JPG: 480x640 (no detections), 271.8ms
Speed: 1.0ms preprocess, 271.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yl5yFKvzKQJsNQUxLMg9bg_270.JPG: 480x640 (no detections), 266.8ms
Speed: 1.1ms preprocess, 266.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yl7E7-9rch4QprdBPByVOw_0.JPG: 480x640 (no detections), 282.2ms
Speed: 1.1ms preprocess, 282.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yl7E7-9rch4QprdBPByVOw_90.JPG: 480x640 (no detections), 273.2ms
Speed: 1.1ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yl7E7-9rch4QprdBPByVOw_180.JPG: 480x640 (no detections), 268.7ms
Speed: 1.0ms preprocess, 268.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yl7E7-9rch4QprdBPByVOw_270.JPG: 480x640 (no detections), 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yl7EEwafkRkNfZLOcdHWyg_0.JPG: 480x640 (no detections), 273.4ms
Speed: 1.1ms preprocess, 273.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yl7EEwafkRkNfZLOcdHWyg_90.JPG: 480x640 (no detections), 275.5ms
Speed: 1.0ms preprocess, 275.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yl7EEwafkRkNfZLOcdHWyg_180.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yl7EEwafkRkNfZLOcdHWyg_270.JPG: 480x640 (no detections), 276.2ms
Speed: 1.1ms preprocess, 276.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylGQc-hrbxRZTIbHHenzGg_0.JPG: 480x640 (no detections), 271.5ms
Speed: 1.1ms preprocess, 271.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylGQc-hrbxRZTIbHHenzGg_90.JPG: 480x640 (no detections), 270.3ms
Speed: 1.1ms preprocess, 270.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylGQc-hrbxRZTIbHHenzGg_180.JPG: 480x640 (no detections), 270.2ms
Speed: 1.0ms preprocess, 270.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylGQc-hrbxRZTIbHHenzGg_270.JPG: 480x640 (no detections), 270.9ms
Speed: 1.0ms preprocess, 270.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylHvXRx180F5qAY1_UqQSA_0.JPG: 480x640 (no detections), 277.4ms
Speed: 1.1ms preprocess, 277.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylHvXRx180F5qAY1_UqQSA_90.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylHvXRx180F5qAY1_UqQSA_180.JPG: 480x640 (no detections), 268.1ms
Speed: 1.0ms preprocess, 268.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylHvXRx180F5qAY1_UqQSA_270.JPG: 480x640 (no detections), 268.7ms
Speed: 1.0ms preprocess, 268.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylMSRjtGHNlsMofc5OznHw_0.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylMSRjtGHNlsMofc5OznHw_90.JPG: 480x640 (no detections), 269.2ms
Speed: 1.0ms preprocess, 269.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylMSRjtGHNlsMofc5OznHw_180.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylMSRjtGHNlsMofc5OznHw_270.JPG: 480x640 (no detections), 275.6ms
Speed: 1.0ms preprocess, 275.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylO3nWEhwtv_cnL9yPeDcw_0.JPG: 480x640 (no detections), 269.1ms
Speed: 1.1ms preprocess, 269.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylO3nWEhwtv_cnL9yPeDcw_90.JPG: 480x640 (no detections), 271.0ms
Speed: 1.0ms preprocess, 271.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylO3nWEhwtv_cnL9yPeDcw_180.JPG: 480x640 (no detections), 275.6ms
Speed: 1.0ms preprocess, 275.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylO3nWEhwtv_cnL9yPeDcw_270.JPG: 480x640 (no detections), 275.2ms
Speed: 1.0ms preprocess, 275.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylOqbkf8jjoZaIX8oEjO0g_0.JPG: 480x640 (no detections), 272.1ms
Speed: 1.0ms preprocess, 272.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylOqbkf8jjoZaIX8oEjO0g_90.JPG: 480x640 (no detections), 271.2ms
Speed: 1.0ms preprocess, 271.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylOqbkf8jjoZaIX8oEjO0g_180.JPG: 480x640 1 Waste, 269.2ms
Speed: 1.0ms preprocess, 269.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylOqbkf8jjoZaIX8oEjO0g_270.JPG: 480x640 (no detections), 275.2ms
Speed: 1.1ms preprocess, 275.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylUc5OSnQgzFYlGdRM-T5g_0.JPG: 480x640 (no detections), 273.9ms
Speed: 1.1ms preprocess, 273.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylUc5OSnQgzFYlGdRM-T5g_90.JPG: 480x640 (no detections), 270.4ms
Speed: 1.0ms preprocess, 270.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylUc5OSnQgzFYlGdRM-T5g_180.JPG: 480x640 (no detections), 269.0ms
Speed: 1.1ms preprocess, 269.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylUc5OSnQgzFYlGdRM-T5g_270.JPG: 480x640 (no detections), 269.9ms
Speed: 1.0ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylUvozvrNwryd_3KFb4Bkg_0.JPG: 480x640 (no detections), 272.4ms
Speed: 1.1ms preprocess, 272.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylUvozvrNwryd_3KFb4Bkg_90.JPG: 480x640 (no detections), 271.8ms
Speed: 1.0ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylUvozvrNwryd_3KFb4Bkg_180.JPG: 480x640 (no detections), 272.8ms
Speed: 1.0ms preprocess, 272.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylUvozvrNwryd_3KFb4Bkg_270.JPG: 480x640 (no detections), 272.0ms
Speed: 1.0ms preprocess, 272.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylV44_A8YyrBDqhuxOkfLA_0.JPG: 480x640 (no detections), 275.4ms
Speed: 1.0ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylV44_A8YyrBDqhuxOkfLA_90.JPG: 480x640 (no detections), 273.6ms
Speed: 1.0ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylV44_A8YyrBDqhuxOkfLA_180.JPG: 480x640 (no detections), 271.5ms
Speed: 1.1ms preprocess, 271.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylV44_A8YyrBDqhuxOkfLA_270.JPG: 480x640 (no detections), 274.1ms
Speed: 1.0ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylXd3W7T6X1SIzpdtG2ueQ_0.JPG: 480x640 (no detections), 272.3ms
Speed: 1.0ms preprocess, 272.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylXd3W7T6X1SIzpdtG2ueQ_90.JPG: 480x640 (no detections), 272.2ms

Speed: 1.0ms preprocess, 272.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylXd3W7T6X1SIzpdtG2ueQ_180.JPG: 480x640 (no detections), 271.8ms
Speed: 1.0ms preprocess, 271.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylXd3W7T6X1SIzpdtG2ueQ_270.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yl_QOwIbZI48jxesnLIfhQ_0.JPG: 480x640 (no detections), 275.7ms
Speed: 1.1ms preprocess, 275.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yl_QOwIbZI48jxesnLIfhQ_90.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yl_QOwIbZI48jxesnLIfhQ_180.JPG: 480x640 (no detections), 279.0ms
Speed: 1.1ms preprocess, 279.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yl_QOwIbZI48jxesnLIfhQ_270.JPG: 480x640 (no detections), 272.7ms
Speed: 1.0ms preprocess, 272.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yld9-qMehf7sCIjRCn5zMg_0.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yld9-qMehf7sCIjRCn5zMg_90.JPG: 480x640 (no detections), 271.2ms
Speed: 1.0ms preprocess, 271.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yld9-qMehf7sCIjRCn5zMg_180.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yld9-qMehf7sCIjRCn5zMg_270.JPG: 480x640 (no detections), 277.9ms
Speed: 1.0ms preprocess, 277.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yldWx2gazytabywCXG02tw_0.JPG: 480x640 (no detections), 273.9ms
Speed: 1.3ms preprocess, 273.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yldWx2gazytabywCXG02tw_90.JPG: 480x640 (no detections), 269.1ms
Speed: 1.0ms preprocess, 269.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yldWx2gazytabywCXG02tw_180.JPG: 480x640 (no detections), 269.5ms
Speed: 1.1ms preprocess, 269.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yldWx2gazytabywCXG02tw_270.JPG: 480x640 (no detections), 270.4ms
Speed: 1.0ms preprocess, 270.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yle9LxD0AdmVkWCIDcjy7A_0.JPG: 480x640 (no detections), 275.3ms
Speed: 1.1ms preprocess, 275.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yle9LxD0AdmVkWCIDcjy7A_90.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yle9LxD0AdmVkWCIDcjy7A_180.JPG: 480x640 (no detections), 274.5ms
Speed: 1.2ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yle9LxD0AdmVkWCIDcjy7A_270.JPG: 480x640 (no detections), 274.0ms
Speed: 1.0ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yleQWbTqEW8KheYI2ovGSA_0.JPG: 480x640 (no detections), 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yleQWbTqEW8KheYI2ovGSA_90.JPG: 480x640 (no detections), 276.3ms
Speed: 1.1ms preprocess, 276.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yleQWbTqEW8KheYI2ovGSA_180.JPG: 480x640 (no detections), 272.5ms
Speed: 1.1ms preprocess, 272.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yleQWbTqEW8KheYI2ovGSA_270.JPG: 480x640 (no detections), 275.2ms
Speed: 1.0ms preprocess, 275.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylhi9b-w0VVJJ0AjPZu6ew_0.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylhi9b-w0VVJJ0AjPZu6ew_90.JPG: 480x640 (no detections), 280.1ms
Speed: 1.1ms preprocess, 280.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylhi9b-w0VVJJ0AjPZu6ew_180.JPG: 480x640 (no detections), 273.1ms
Speed: 1.0ms preprocess, 273.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylhi9b-w0VVJJ0AjPZu6ew_270.JPG: 480x640 (no detections), 269.4ms
Speed: 1.0ms preprocess, 269.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yljgWLwChtEXt53jQA0J6g_0.JPG: 480x640 (no detections), 272.2ms
Speed: 1.0ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yljgWLwChtEXt53jQA0J6g_90.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yljgWLwChtEXt53jQA0J6g_180.JPG: 480x640 (no detections), 269.8ms
Speed: 1.0ms preprocess, 269.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yljgWLwChtEXt53jQA0J6g_270.JPG: 480x640 (no detections), 272.0ms
Speed: 1.1ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylkoCLErhrbLflO4Ah0SlQ_0.JPG: 480x640 (no detections), 276.7ms
Speed: 1.0ms preprocess, 276.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylkoCLErhrbLflO4Ah0SlQ_90.JPG: 480x640 (no detections), 270.6ms
Speed: 1.0ms preprocess, 270.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylkoCLErhrbLflO4Ah0SlQ_180.JPG: 480x640 (no detections), 274.3ms
Speed: 1.1ms preprocess, 274.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylkoCLErhrbLflO4Ah0SlQ_270.JPG: 480x640 (no detections), 265.0ms
Speed: 1.0ms preprocess, 265.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylmz_-ZaHW-LDBuObp10Lw_0.JPG: 480x640 (no detections), 272.4ms
Speed: 1.1ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylmz_-ZaHW-LDBuObp10Lw_90.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylmz_-ZaHW-LDBuObp10Lw_180.JPG: 480x640 (no detections), 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylmz_-ZaHW-LDBuObp10Lw_270.JPG: 480x640 (no detections), 274.0ms
Speed: 1.1ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylnWa5m8nBuB2nmZtKTdsw_0.JPG: 480x640 (no detections), 275.3ms
Speed: 1.0ms preprocess, 275.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylnWa5m8nBuB2nmZtKTdsw_90.JPG: 480x640 (no detections), 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylnWa5m8nBuB2nmZtKTdsw_180.JPG: 480x640 (no detections), 271.4ms
Speed: 1.0ms preprocess, 271.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylnWa5m8nBuB2nmZtKTdsw_270.JPG: 480x640 (no detections), 268.8ms
Speed: 1.0ms preprocess, 268.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylrw4IKI1qQP-adMuObyhg_0.JPG: 480x640 (no detections), 270.3ms
Speed: 1.0ms preprocess, 270.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylrw4IKI1qQP-adMuObyhg_90.JPG: 480x640 (no detections), 272.3ms
Speed: 1.0ms preprocess, 272.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylrw4IKI1qQP-adMuObyhg_180.JPG: 480x640 (no detections), 271.0ms
Speed: 1.0ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylrw4IKI1qQP-adMuObyhg_270.JPG: 480x640 (no detections), 270.3ms
Speed: 1.0ms preprocess, 270.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylsJKXdb8zzLPtOPn-hArg_0.JPG: 480x640 (no detections), 270.5ms
Speed: 1.0ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylsJKXdb8zzLPtOPn-hArg_90.JPG: 480x640 (no detections), 273.2ms
Speed: 1.1ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylsJKXdb8zzLPtOPn-hArg_180.JPG: 480x640 (no detections), 273.2ms
Speed: 1.1ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylsJKXdb8zzLPtOPn-hArg_270.JPG: 480x640 (no detections), 273.0ms
Speed: 1.0ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylsOknXuVOVcmHai0S-fBg_0.JPG: 480x640 (no detections), 271.1ms
Speed: 1.0ms preprocess, 271.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylsOknXuVOVcmHai0S-fBg_90.JPG: 480x640 (no detections), 277.2ms
Speed: 1.1ms preprocess, 277.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylsOknXuVOVcmHai0S-fBg_180.JPG: 480x640 (no detections), 275.5ms
Speed: 1.0ms preprocess, 275.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylsOknXuVOVcmHai0S-fBg_270.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylskhtzhRTKOW7rtSBacNw_0.JPG: 480x640 (no detections), 270.0ms
Speed: 1.0ms preprocess, 270.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylskhtzhRTKOW7rtSBacNw_90.JPG: 480x640 (no detections), 267.8ms
Speed: 1.1ms preprocess, 267.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylskhtzhRTKOW7rtSBacNw_180.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylskhtzhRTKOW7rtSBacNw_270.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yluoGjnud0Ozu0A4uVC_PQ_0.JPG: 480x640 (no detections), 275.1ms
Speed: 1.0ms preprocess, 275.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yluoGjnud0Ozu0A4uVC_PQ_90.JPG: 480x640 (no detections), 275.3ms
Speed: 1.0ms preprocess, 275.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yluoGjnud0Ozu0A4uVC_PQ_180.JPG: 480x640 (no detections), 272.6ms
Speed: 1.0ms preprocess, 272.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/yluoGjnud0Ozu0A4uVC_PQ_270.JPG: 480x640 (no detections), 272.5ms
Speed: 1.1ms preprocess, 272.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylwJkYtW3neaCsulCA2qpQ_0.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylwJkYtW3neaCsulCA2qpQ_90.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylwJkYtW3neaCsulCA2qpQ_180.JPG: 480x640 (no detections), 276.5ms
Speed: 1.0ms preprocess, 276.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylwJkYtW3neaCsulCA2qpQ_270.JPG: 480x640 (no detections), 273.1ms
Speed: 1.1ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylx1Kulmttq-EAdYbR4LXA_0.JPG: 480x640 (no detections), 272.4ms

Speed: 1.0ms preprocess, 272.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylx1Kulmttq-EAdYbR4LXA_90.JPG: 480x640 (no detections), 271.7ms
Speed: 1.0ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylx1Kulmttq-EAdYbR4LXA_180.JPG: 480x640 (no detections), 277.4ms
Speed: 1.2ms preprocess, 277.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylx1Kulmttq-EAdYbR4LXA_270.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylx1xK25tpXwrYm4vRI5Cw_0.JPG: 480x640 (no detections), 272.0ms
Speed: 1.1ms preprocess, 272.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylx1xK25tpXwrYm4vRI5Cw_90.JPG: 480x640 (no detections), 270.0ms
Speed: 1.0ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylx1xK25tpXwrYm4vRI5Cw_180.JPG: 480x640 (no detections), 275.3ms
Speed: 1.0ms preprocess, 275.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylx1xK25tpXwrYm4vRI5Cw_270.JPG: 480x640 (no detections), 270.3ms
Speed: 1.0ms preprocess, 270.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylyUVLV696iiWOF3I6xztQ_0.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylyUVLV696iiWOF3I6xztQ_90.JPG: 480x640 (no detections), 275.1ms
Speed: 1.0ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylyUVLV696iiWOF3I6xztQ_180.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylyUVLV696iiWOF3I6xztQ_270.JPG: 480x640 (no detections), 271.2ms
Speed: 1.0ms preprocess, 271.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylzeUwsXft4rtOTtaQiePA_0.JPG: 480x640 (no detections), 275.2ms
Speed: 1.1ms preprocess, 275.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylzeUwsXft4rtOTtaQiePA_90.JPG: 480x640 (no detections), 279.3ms
Speed: 1.2ms preprocess, 279.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylzeUwsXft4rtOTtaQiePA_180.JPG: 480x640 (no detections), 274.4ms
Speed: 1.1ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/L/ylzeUwsXft4rtOTtaQiePA_270.JPG: 480x640 (no detections), 280.0ms
Speed: 1.1ms preprocess, 280.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ym-TRMeEm0moloiVLXdMmQ_0.JPG: 480x640 (no detections), 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ym-TRMeEm0moloiVLXdMmQ_90.JPG: 480x640 (no detections), 270.0ms
Speed: 1.0ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ym-TRMeEm0moloiVLXdMmQ_180.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ym-TRMeEm0moloiVLXdMmQ_270.JPG: 480x640 (no detections), 271.5ms
Speed: 1.0ms preprocess, 271.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ym1BlgfAfIPfgINeL0SQqA_0.JPG: 480x640 (no detections), 270.4ms
Speed: 1.0ms preprocess, 270.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ym1BlgfAfIPfgINeL0SQqA_90.JPG: 480x640 (no detections), 270.4ms
Speed: 1.1ms preprocess, 270.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ym1BlgfAfIPfgINeL0SQqA_180.JPG: 480x640 (no detections), 272.0ms
Speed: 1.0ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ym1BlgfAfIPfgINeL0SQqA_270.JPG: 480x640 (no detections), 271.6ms
Speed: 1.0ms preprocess, 271.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ym1b6S1sUpgbUJ-nsM71fA_0.JPG: 480x640 (no detections), 272.5ms
Speed: 1.1ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ym1b6S1sUpgbUJ-nsM71fA_90.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ym1b6S1sUpgbUJ-nsM71fA_180.JPG: 480x640 (no detections), 275.5ms
Speed: 1.0ms preprocess, 275.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ym1b6S1sUpgbUJ-nsM71fA_270.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ym2QpLTG1xUh-qw9cBiBUg_0.JPG: 480x640 (no detections), 270.9ms
Speed: 1.0ms preprocess, 270.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ym2QpLTG1xUh-qw9cBiBUg_90.JPG: 480x640 (no detections), 273.9ms
Speed: 1.0ms preprocess, 273.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ym2QpLTG1xUh-qw9cBiBUg_180.JPG: 480x640 (no detections), 282.7ms
Speed: 1.2ms preprocess, 282.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ym2QpLTG1xUh-qw9cBiBUg_270.JPG: 480x640 (no detections), 270.3ms
Speed: 1.1ms preprocess, 270.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ym2kWA9pWB4NTe7J1UcCqg_0.JPG: 480x640 (no detections), 273.4ms
Speed: 1.0ms preprocess, 273.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ym2kWA9pWB4NTe7J1UcCqg_90.JPG: 480x640 (no detections), 272.0ms
Speed: 1.1ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ym2kWA9pWB4NTe7J1UcCqg_180.JPG: 480x640 (no detections), 270.4ms
Speed: 1.1ms preprocess, 270.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ym2kWA9pWB4NTe7J1UcCqg_270.JPG: 480x640 (no detections), 272.7ms
Speed: 1.0ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ym8yxuGes9lLWZZOn3DCGA_0.JPG: 480x640 (no detections), 276.7ms
Speed: 1.1ms preprocess, 276.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ym8yxuGes9lLWZZOn3DCGA_90.JPG: 480x640 (no detections), 273.4ms
Speed: 1.2ms preprocess, 273.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ym8yxuGes9lLWZZOn3DCGA_180.JPG: 480x640 (no detections), 272.5ms
Speed: 1.0ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ym8yxuGes9lLWZZOn3DCGA_270.JPG: 480x640 (no detections), 271.3ms
Speed: 1.0ms preprocess, 271.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ym9n8hzvsan0Fgr-YdSN_A_0.JPG: 480x640 (no detections), 274.9ms
Speed: 1.1ms preprocess, 274.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ym9n8hzvsan0Fgr-YdSN_A_90.JPG: 480x640 (no detections), 270.5ms
Speed: 1.2ms preprocess, 270.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ym9n8hzvsan0Fgr-YdSN_A_180.JPG: 480x640 (no detections), 274.7ms
Speed: 1.2ms preprocess, 274.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ym9n8hzvsan0Fgr-YdSN_A_270.JPG: 480x640 (no detections), 271.2ms
Speed: 1.0ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymA9IJ8ayCJ0V3-Lj94EMw_0.JPG: 480x640 (no detections), 275.6ms
Speed: 1.1ms preprocess, 275.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymA9IJ8ayCJ0V3-Lj94EMw_90.JPG: 480x640 (no detections), 272.8ms
Speed: 1.0ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymA9IJ8ayCJ0V3-Lj94EMw_180.JPG: 480x640 (no detections), 273.8ms
Speed: 1.0ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymA9IJ8ayCJ0V3-Lj94EMw_270.JPG: 480x640 1 Waste, 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymDgbHHpcSgmQIj5jTt3Ng_0.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymDgbHHpcSgmQIj5jTt3Ng_90.JPG: 480x640 (no detections), 271.1ms
Speed: 1.2ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymDgbHHpcSgmQIj5jTt3Ng_180.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymDgbHHpcSgmQIj5jTt3Ng_270.JPG: 480x640 (no detections), 271.2ms
Speed: 1.0ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymGpT7XvOB4-TFCuxJC38g_0.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymGpT7XvOB4-TFCuxJC38g_90.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymGpT7XvOB4-TFCuxJC38g_180.JPG: 480x640 (no detections), 269.4ms
Speed: 1.0ms preprocess, 269.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymGpT7XvOB4-TFCuxJC38g_270.JPG: 480x640 (no detections), 271.2ms
Speed: 1.0ms preprocess, 271.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymHb0WahHJEOJ3t2u9aZcA_0.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymHb0WahHJEOJ3t2u9aZcA_90.JPG: 480x640 (no detections), 269.2ms
Speed: 1.0ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymHb0WahHJEOJ3t2u9aZcA_180.JPG: 480x640 (no detections), 269.1ms
Speed: 1.0ms preprocess, 269.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymHb0WahHJEOJ3t2u9aZcA_270.JPG: 480x640 (no detections), 279.9ms
Speed: 1.1ms preprocess, 279.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymJYf04YsA_eV_MkJC81WQ_0.JPG: 480x640 (no detections), 273.0ms
Speed: 1.0ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymJYf04YsA_eV_MkJC81WQ_90.JPG: 480x640 (no detections), 271.2ms
Speed: 1.2ms preprocess, 271.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymJYf04YsA_eV_MkJC81WQ_180.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymJYf04YsA_eV_MkJC81WQ_270.JPG: 480x640 (no detections), 273.0ms
Speed: 1.0ms preprocess, 273.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymMep3_j7Q6kfZ430dilhw_0.JPG: 480x640 (no detections), 275.4ms
Speed: 1.0ms preprocess, 275.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymMep3_j7Q6kfZ430dilhw_90.JPG: 480x640 (no detections), 274.4ms
Speed: 1.0ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymMep3_j7Q6kfZ430dilhw_180.JPG: 480x640 1 Waste, 275.4ms
Speed: 1.0ms preprocess, 275.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymMep3_j7Q6kfZ430dilhw_270.JPG: 480x640 (no detections), 273.2ms

Speed: 1.0ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymMiSUOJRRaXdOsyu9Ae-A_0.JPG: 480x640 (no detections), 270.9ms
Speed: 1.0ms preprocess, 270.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymMiSUOJRRaXdOsyu9Ae-A_90.JPG: 480x640 (no detections), 269.6ms
Speed: 1.2ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymMiSUOJRRaXdOsyu9Ae-A_180.JPG: 480x640 (no detections), 274.3ms
Speed: 1.1ms preprocess, 274.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymMiSUOJRRaXdOsyu9Ae-A_270.JPG: 480x640 (no detections), 271.5ms
Speed: 1.1ms preprocess, 271.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymOE1tOO3E9VQH9Hzqc33Q_0.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymOE1tOO3E9VQH9Hzqc33Q_90.JPG: 480x640 (no detections), 277.0ms
Speed: 1.0ms preprocess, 277.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymOE1tOO3E9VQH9Hzqc33Q_180.JPG: 480x640 (no detections), 274.4ms
Speed: 1.1ms preprocess, 274.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymOE1tOO3E9VQH9Hzqc33Q_270.JPG: 480x640 (no detections), 269.3ms
Speed: 1.0ms preprocess, 269.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymQDo8ikq2rfqFbJInDLHw_0.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymQDo8ikq2rfqFbJInDLHw_90.JPG: 480x640 (no detections), 271.5ms
Speed: 1.1ms preprocess, 271.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymQDo8ikq2rfqFbJInDLHw_180.JPG: 480x640 (no detections), 271.8ms
Speed: 1.0ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymQDo8ikq2rfqFbJInDLHw_270.JPG: 480x640 (no detections), 271.9ms
Speed: 1.0ms preprocess, 271.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymTz4A6rPZfqBo5dQ0ymEQ_0.JPG: 480x640 (no detections), 271.4ms
Speed: 1.0ms preprocess, 271.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymTz4A6rPZfqBo5dQ0ymEQ_90.JPG: 480x640 (no detections), 274.5ms
Speed: 1.1ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymTz4A6rPZfqBo5dQ0ymEQ_180.JPG: 480x640 (no detections), 275.3ms
Speed: 1.1ms preprocess, 275.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymTz4A6rPZfqBo5dQ0ymEQ_270.JPG: 480x640 (no detections), 275.8ms
Speed: 1.1ms preprocess, 275.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymUU_jYoz-i-F0K2iYGKdw_0.JPG: 480x640 (no detections), 274.0ms
Speed: 1.1ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymUU_jYoz-i-F0K2iYGKdw_90.JPG: 480x640 (no detections), 268.2ms
Speed: 1.0ms preprocess, 268.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymUU_jYoz-i-F0K2iYGKdw_180.JPG: 480x640 (no detections), 272.0ms
Speed: 1.2ms preprocess, 272.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymUU_jYoz-i-F0K2iYGKdw_270.JPG: 480x640 (no detections), 269.6ms
Speed: 1.0ms preprocess, 269.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymVm4-kljg0D1E5aAK6u-A_0.JPG: 480x640 (no detections), 274.9ms
Speed: 1.0ms preprocess, 274.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymVm4-kljg0D1E5aAK6u-A_90.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymVm4-kljg0D1E5aAK6u-A_180.JPG: 480x640 1 Waste, 271.5ms
Speed: 1.0ms preprocess, 271.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymVm4-kljg0D1E5aAK6u-A_270.JPG: 480x640 1 Waste, 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymWPc8mqjSYrAslsKU_atA_0.JPG: 480x640 (no detections), 269.0ms
Speed: 1.0ms preprocess, 269.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymWPc8mqjSYrAslsKU_atA_90.JPG: 480x640 (no detections), 270.3ms
Speed: 1.1ms preprocess, 270.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymWPc8mqjSYrAslsKU_atA_180.JPG: 480x640 (no detections), 275.4ms
Speed: 1.2ms preprocess, 275.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymWPc8mqjSYrAslsKU_atA_270.JPG: 480x640 (no detections), 265.3ms
Speed: 1.1ms preprocess, 265.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymWdodiLviVxxAWwPodPzg_0.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymWdodiLviVxxAWwPodPzg_90.JPG: 480x640 (no detections), 264.3ms
Speed: 1.1ms preprocess, 264.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymWdodiLviVxxAWwPodPzg_180.JPG: 480x640 (no detections), 275.2ms
Speed: 1.1ms preprocess, 275.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymWdodiLviVxxAWwPodPzg_270.JPG: 480x640 (no detections), 263.6ms
Speed: 1.0ms preprocess, 263.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymYCj8MQ8zSx6bMpY9U_LQ_0.JPG: 480x640 (no detections), 262.4ms
Speed: 1.1ms preprocess, 262.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymYCj8MQ8zSx6bMpY9U_LQ_90.JPG: 480x640 (no detections), 264.6ms
Speed: 1.0ms preprocess, 264.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymYCj8MQ8zSx6bMpY9U_LQ_180.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymYCj8MQ8zSx6bMpY9U_LQ_270.JPG: 480x640 (no detections), 274.5ms
Speed: 1.0ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymb41knMFkyW4MDCEdXzDA_0.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymb41knMFkyW4MDCEdXzDA_90.JPG: 480x640 (no detections), 273.5ms
Speed: 1.0ms preprocess, 273.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymb41knMFkyW4MDCEdXzDA_180.JPG: 480x640 (no detections), 274.3ms
Speed: 1.0ms preprocess, 274.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymb41knMFkyW4MDCEdXzDA_270.JPG: 480x640 (no detections), 270.3ms
Speed: 1.1ms preprocess, 270.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymciScZmbjjjsbH1KTyVJQ_0.JPG: 480x640 (no detections), 276.0ms
Speed: 1.0ms preprocess, 276.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymciScZmbjjjsbH1KTyVJQ_90.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymciScZmbjjjsbH1KTyVJQ_180.JPG: 480x640 (no detections), 272.9ms
Speed: 1.0ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymciScZmbjjjsbH1KTyVJQ_270.JPG: 480x640 (no detections), 271.1ms
Speed: 1.0ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymdGt4eFw3VYyasMCYZLsA_0.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymdGt4eFw3VYyasMCYZLsA_90.JPG: 480x640 (no detections), 272.9ms
Speed: 1.0ms preprocess, 272.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymdGt4eFw3VYyasMCYZLsA_180.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymdGt4eFw3VYyasMCYZLsA_270.JPG: 480x640 (no detections), 272.5ms
Speed: 1.0ms preprocess, 272.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymek1QHVCgmM8lErjajf7g_0.JPG: 480x640 (no detections), 270.2ms
Speed: 1.0ms preprocess, 270.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymek1QHVCgmM8lErjajf7g_90.JPG: 480x640 (no detections), 275.9ms
Speed: 1.1ms preprocess, 275.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymek1QHVCgmM8lErjajf7g_180.JPG: 480x640 (no detections), 270.9ms
Speed: 1.0ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymek1QHVCgmM8lErjajf7g_270.JPG: 480x640 (no detections), 276.4ms
Speed: 1.2ms preprocess, 276.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymfyHOx3t8Q5psrirobvZw_0.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymfyHOx3t8Q5psrirobvZw_90.JPG: 480x640 (no detections), 274.2ms
Speed: 1.0ms preprocess, 274.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymfyHOx3t8Q5psrirobvZw_180.JPG: 480x640 (no detections), 272.0ms
Speed: 1.1ms preprocess, 272.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymfyHOx3t8Q5psrirobvZw_270.JPG: 480x640 (no detections), 277.2ms
Speed: 1.1ms preprocess, 277.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymky9qPI_dRAnU34o-_z8g_0.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymky9qPI_dRAnU34o-_z8g_90.JPG: 480x640 (no detections), 272.2ms
Speed: 1.2ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymky9qPI_dRAnU34o-_z8g_180.JPG: 480x640 (no detections), 274.2ms
Speed: 1.1ms preprocess, 274.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymky9qPI_dRAnU34o-_z8g_270.JPG: 480x640 (no detections), 271.3ms
Speed: 1.2ms preprocess, 271.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yml76vNpzpIjUGSOGqCxgQ_0.JPG: 480x640 (no detections), 274.7ms
Speed: 1.0ms preprocess, 274.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yml76vNpzpIjUGSOGqCxgQ_90.JPG: 480x640 (no detections), 273.8ms
Speed: 1.0ms preprocess, 273.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yml76vNpzpIjUGSOGqCxgQ_180.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yml76vNpzpIjUGSOGqCxgQ_270.JPG: 480x640 (no detections), 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymlWZz9a5o0xgQ29em63JA_0.JPG: 480x640 (no detections), 281.6ms
Speed: 1.1ms preprocess, 281.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymlWZz9a5o0xgQ29em63JA_90.JPG: 480x640 (no detections), 269.8ms
Speed: 1.1ms preprocess, 269.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymlWZz9a5o0xgQ29em63JA_180.JPG: 480x640 (no detections), 269.8ms

Speed: 1.0ms preprocess, 269.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymlWZz9a5o0xgQ29em63JA_270.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymo4MMCkt1JmsvYtC0WdRw_0.JPG: 480x640 (no detections), 269.6ms
Speed: 1.0ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymo4MMCkt1JmsvYtC0WdRw_90.JPG: 480x640 (no detections), 271.3ms
Speed: 1.0ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymo4MMCkt1JmsvYtC0WdRw_180.JPG: 480x640 (no detections), 275.1ms
Speed: 1.0ms preprocess, 275.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymo4MMCkt1JmsvYtC0WdRw_270.JPG: 480x640 (no detections), 272.1ms
Speed: 1.1ms preprocess, 272.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymoGiPhpKWFcrSzlfn4tbA_0.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymoGiPhpKWFcrSzlfn4tbA_90.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymoGiPhpKWFcrSzlfn4tbA_180.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymoGiPhpKWFcrSzlfn4tbA_270.JPG: 480x640 (no detections), 273.9ms
Speed: 1.1ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymohqIKeKRbQdMJAq7CSng_0.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymohqIKeKRbQdMJAq7CSng_90.JPG: 480x640 (no detections), 271.9ms
Speed: 1.0ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymohqIKeKRbQdMJAq7CSng_180.JPG: 480x640 (no detections), 274.0ms
Speed: 1.2ms preprocess, 274.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymohqIKeKRbQdMJAq7CSng_270.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ympg8OD-jsRuSR6LkwojZA_0.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ympg8OD-jsRuSR6LkwojZA_90.JPG: 480x640 (no detections), 274.4ms
Speed: 1.0ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ympg8OD-jsRuSR6LkwojZA_180.JPG: 480x640 (no detections), 269.9ms
Speed: 1.0ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ympg8OD-jsRuSR6LkwojZA_270.JPG: 480x640 (no detections), 270.3ms
Speed: 1.0ms preprocess, 270.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymq6gALFtc0bvrglro_vAA_0.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymq6gALFtc0bvrglro_vAA_90.JPG: 480x640 (no detections), 272.9ms
Speed: 1.0ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymq6gALFtc0bvrglro_vAA_180.JPG: 480x640 (no detections), 269.0ms
Speed: 1.1ms preprocess, 269.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymq6gALFtc0bvrglro_vAA_270.JPG: 480x640 (no detections), 269.5ms
Speed: 1.0ms preprocess, 269.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yms37c3rDLjEgIq2g2_lTQ_0.JPG: 480x640 (no detections), 269.6ms
Speed: 1.1ms preprocess, 269.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yms37c3rDLjEgIq2g2_lTQ_90.JPG: 480x640 (no detections), 269.7ms
Speed: 1.0ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yms37c3rDLjEgIq2g2_lTQ_180.JPG: 480x640 (no detections), 271.5ms
Speed: 1.2ms preprocess, 271.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/yms37c3rDLjEgIq2g2_lTQ_270.JPG: 480x640 (no detections), 272.7ms
Speed: 1.0ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymszQIB6TzYNVwFzNjm6tg_0.JPG: 480x640 (no detections), 275.8ms
Speed: 1.1ms preprocess, 275.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymszQIB6TzYNVwFzNjm6tg_90.JPG: 480x640 (no detections), 276.6ms
Speed: 1.1ms preprocess, 276.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymszQIB6TzYNVwFzNjm6tg_180.JPG: 480x640 (no detections), 273.5ms
Speed: 1.0ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymszQIB6TzYNVwFzNjm6tg_270.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymwl6tZi5BnAb6OmpgiMlg_0.JPG: 480x640 (no detections), 272.3ms
Speed: 1.1ms preprocess, 272.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymwl6tZi5BnAb6OmpgiMlg_90.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymwl6tZi5BnAb6OmpgiMlg_180.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymwl6tZi5BnAb6OmpgiMlg_270.JPG: 480x640 (no detections), 273.5ms
Speed: 1.0ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymyM72yQL-OdEcYUokCkfw_0.JPG: 480x640 (no detections), 269.6ms
Speed: 1.1ms preprocess, 269.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymyM72yQL-OdEcYUokCkfw_90.JPG: 480x640 (no detections), 270.9ms
Speed: 1.0ms preprocess, 270.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymyM72yQL-OdEcYUokCkfw_180.JPG: 480x640 (no detections), 276.3ms
Speed: 1.0ms preprocess, 276.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/m/ymyM72yQL-OdEcYUokCkfw_270.JPG: 480x640 (no detections), 274.9ms
Speed: 1.1ms preprocess, 274.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yn5LJl002Mq3hiac_Im5Lw_0.JPG: 480x640 (no detections), 272.6ms
Speed: 1.0ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yn5LJl002Mq3hiac_Im5Lw_90.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yn5LJl002Mq3hiac_Im5Lw_180.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yn5LJl002Mq3hiac_Im5Lw_270.JPG: 480x640 (no detections), 272.9ms
Speed: 1.0ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yn5mi8yfmo9p9Y8q2gOrtw_0.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yn5mi8yfmo9p9Y8q2gOrtw_90.JPG: 480x640 (no detections), 272.1ms
Speed: 1.1ms preprocess, 272.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yn5mi8yfmo9p9Y8q2gOrtw_180.JPG: 480x640 (no detections), 273.1ms
Speed: 1.0ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yn5mi8yfmo9p9Y8q2gOrtw_270.JPG: 480x640 (no detections), 273.4ms
Speed: 1.0ms preprocess, 273.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yn97030_R1w9EgXLJ1MbfA_0.JPG: 480x640 (no detections), 277.3ms
Speed: 1.2ms preprocess, 277.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yn97030_R1w9EgXLJ1MbfA_90.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yn97030_R1w9EgXLJ1MbfA_180.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yn97030_R1w9EgXLJ1MbfA_270.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yn9fL4f1WzyrIqYIT5PARg_0.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yn9fL4f1WzyrIqYIT5PARg_90.JPG: 480x640 (no detections), 272.2ms
Speed: 0.9ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yn9fL4f1WzyrIqYIT5PARg_180.JPG: 480x640 (no detections), 270.5ms
Speed: 1.1ms preprocess, 270.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yn9fL4f1WzyrIqYIT5PARg_270.JPG: 480x640 (no detections), 270.5ms
Speed: 1.0ms preprocess, 270.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynAU5rU4U5awCqaSviIU-w_0.JPG: 480x640 (no detections), 274.1ms
Speed: 1.0ms preprocess, 274.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynAU5rU4U5awCqaSviIU-w_90.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynAU5rU4U5awCqaSviIU-w_180.JPG: 480x640 (no detections), 274.8ms
Speed: 1.0ms preprocess, 274.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynAU5rU4U5awCqaSviIU-w_270.JPG: 480x640 (no detections), 276.9ms
Speed: 1.1ms preprocess, 276.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynByfs94QZMaMWLa8Bbrvw_0.JPG: 480x640 (no detections), 269.6ms
Speed: 1.1ms preprocess, 269.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynByfs94QZMaMWLa8Bbrvw_90.JPG: 480x640 (no detections), 271.8ms
Speed: 1.0ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynByfs94QZMaMWLa8Bbrvw_180.JPG: 480x640 (no detections), 270.3ms
Speed: 1.0ms preprocess, 270.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynByfs94QZMaMWLa8Bbrvw_270.JPG: 480x640 (no detections), 268.8ms
Speed: 1.1ms preprocess, 268.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynCZn6AijQU5t882AEQpWQ_0.JPG: 480x640 (no detections), 272.1ms
Speed: 1.0ms preprocess, 272.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynCZn6AijQU5t882AEQpWQ_90.JPG: 480x640 (no detections), 278.1ms
Speed: 1.0ms preprocess, 278.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynCZn6AijQU5t882AEQpWQ_180.JPG: 480x640 (no detections), 272.4ms
Speed: 1.1ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynCZn6AijQU5t882AEQpWQ_270.JPG: 480x640 (no detections), 270.5ms
Speed: 1.2ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynDYgT2Enq520g-R8P6RWw_0.JPG: 480x640 (no detections), 275.3ms
Speed: 1.0ms preprocess, 275.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynDYgT2Enq520g-R8P6RWw_90.JPG: 480x640 1 Waste, 273.5ms

Speed: 1.0ms preprocess, 273.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynDYgT2Enq520g-R8P6RWw_180.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynDYgT2Enq520g-R8P6RWw_270.JPG: 480x640 (no detections), 270.5ms
Speed: 1.1ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynFViWDpkPjP0FhdyXu3uw_0.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynFViWDpkPjP0FhdyXu3uw_90.JPG: 480x640 (no detections), 265.2ms
Speed: 1.1ms preprocess, 265.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynFViWDpkPjP0FhdyXu3uw_180.JPG: 480x640 (no detections), 274.5ms
Speed: 1.0ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynFViWDpkPjP0FhdyXu3uw_270.JPG: 480x640 (no detections), 272.8ms
Speed: 1.2ms preprocess, 272.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynHVobasWu0Vmu6QpbGZnA_0.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynHVobasWu0Vmu6QpbGZnA_90.JPG: 480x640 (no detections), 278.5ms
Speed: 1.0ms preprocess, 278.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynHVobasWu0Vmu6QpbGZnA_180.JPG: 480x640 (no detections), 268.9ms
Speed: 1.0ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynHVobasWu0Vmu6QpbGZnA_270.JPG: 480x640 (no detections), 274.0ms
Speed: 1.0ms preprocess, 274.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynHloiL4C6XoL41WJOmG8w_0.JPG: 480x640 (no detections), 277.8ms
Speed: 1.0ms preprocess, 277.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynHloiL4C6XoL41WJOmG8w_90.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynHloiL4C6XoL41WJOmG8w_180.JPG: 480x640 (no detections), 277.1ms
Speed: 1.1ms preprocess, 277.1ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynHloiL4C6XoL41WJOmG8w_270.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynP_HVPV_1n5L4aJypUaZA_0.JPG: 480x640 (no detections), 274.0ms
Speed: 1.1ms preprocess, 274.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynP_HVPV_1n5L4aJypUaZA_90.JPG: 480x640 (no detections), 268.4ms
Speed: 1.1ms preprocess, 268.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynP_HVPV_1n5L4aJypUaZA_180.JPG: 480x640 (no detections), 270.4ms
Speed: 1.1ms preprocess, 270.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynP_HVPV_1n5L4aJypUaZA_270.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynQwe9cntG9lsRRN1vKZeQ_0.JPG: 480x640 (no detections), 274.7ms
Speed: 1.1ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynQwe9cntG9lsRRN1vKZeQ_90.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynQwe9cntG9lsRRN1vKZeQ_180.JPG: 480x640 (no detections), 271.0ms
Speed: 1.1ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynQwe9cntG9lsRRN1vKZeQ_270.JPG: 480x640 (no detections), 270.4ms
Speed: 1.1ms preprocess, 270.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynRJbL0L-juLHTGoY4g58g_0.JPG: 480x640 (no detections), 268.5ms
Speed: 1.1ms preprocess, 268.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynRJbL0L-juLHTGoY4g58g_90.JPG: 480x640 (no detections), 277.0ms
Speed: 1.0ms preprocess, 277.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynRJbL0L-juLHTGoY4g58g_180.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynRJbL0L-juLHTGoY4g58g_270.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynVhRjx3LS7vu9me3jkVFw_0.JPG: 480x640 (no detections), 271.2ms
Speed: 1.0ms preprocess, 271.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynVhRjx3LS7vu9me3jkVFw_90.JPG: 480x640 (no detections), 272.9ms
Speed: 1.0ms preprocess, 272.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynVhRjx3LS7vu9me3jkVFw_180.JPG: 480x640 (no detections), 272.1ms
Speed: 1.0ms preprocess, 272.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynVhRjx3LS7vu9me3jkVFw_270.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynWYLUOOwiufgQCVzneGGA_0.JPG: 480x640 (no detections), 268.8ms
Speed: 1.1ms preprocess, 268.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynWYLUOOwiufgQCVzneGGA_90.JPG: 480x640 (no detections), 274.9ms
Speed: 1.0ms preprocess, 274.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynWYLUOOwiufgQCVzneGGA_180.JPG: 480x640 (no detections), 271.3ms
Speed: 1.0ms preprocess, 271.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynWYLUOOwiufgQCVzneGGA_270.JPG: 480x640 (no detections), 273.9ms
Speed: 1.0ms preprocess, 273.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynbSD7eUqAmw2I-vVlUeVQ_0.JPG: 480x640 (no detections), 273.9ms
Speed: 1.0ms preprocess, 273.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynbSD7eUqAmw2I-vVlUeVQ_90.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynbSD7eUqAmw2I-vVlUeVQ_180.JPG: 480x640 (no detections), 271.0ms
Speed: 1.0ms preprocess, 271.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynbSD7eUqAmw2I-vVlUeVQ_270.JPG: 480x640 (no detections), 267.5ms
Speed: 1.0ms preprocess, 267.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yngOcdkX-RQABux3KuT-bg_0.JPG: 480x640 (no detections), 271.0ms
Speed: 1.1ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yngOcdkX-RQABux3KuT-bg_90.JPG: 480x640 (no detections), 271.2ms
Speed: 1.0ms preprocess, 271.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yngOcdkX-RQABux3KuT-bg_180.JPG: 480x640 (no detections), 276.9ms
Speed: 1.0ms preprocess, 276.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yngOcdkX-RQABux3KuT-bg_270.JPG: 480x640 (no detections), 274.4ms
Speed: 1.0ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yngSq55lEiRlq0evAiLVyw_0.JPG: 480x640 (no detections), 270.8ms
Speed: 1.2ms preprocess, 270.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yngSq55lEiRlq0evAiLVyw_90.JPG: 480x640 (no detections), 270.9ms
Speed: 1.0ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yngSq55lEiRlq0evAiLVyw_180.JPG: 480x640 (no detections), 269.2ms
Speed: 1.1ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yngSq55lEiRlq0evAiLVyw_270.JPG: 480x640 (no detections), 272.3ms
Speed: 1.2ms preprocess, 272.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yngYql5rs-pudMdB6NBkQA_0.JPG: 480x640 (no detections), 266.0ms
Speed: 1.1ms preprocess, 266.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yngYql5rs-pudMdB6NBkQA_90.JPG: 480x640 (no detections), 277.2ms
Speed: 1.1ms preprocess, 277.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yngYql5rs-pudMdB6NBkQA_180.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yngYql5rs-pudMdB6NBkQA_270.JPG: 480x640 (no detections), 270.1ms
Speed: 1.0ms preprocess, 270.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynh61d_a38uNV35Y1fPMDA_0.JPG: 480x640 (no detections), 276.3ms
Speed: 1.1ms preprocess, 276.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynh61d_a38uNV35Y1fPMDA_90.JPG: 480x640 (no detections), 272.2ms
Speed: 1.0ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynh61d_a38uNV35Y1fPMDA_180.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynh61d_a38uNV35Y1fPMDA_270.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynhkT2J4QZwQgRhB5dMREg_0.JPG: 480x640 (no detections), 269.1ms
Speed: 1.1ms preprocess, 269.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynhkT2J4QZwQgRhB5dMREg_90.JPG: 480x640 (no detections), 267.8ms
Speed: 1.1ms preprocess, 267.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynhkT2J4QZwQgRhB5dMREg_180.JPG: 480x640 (no detections), 272.4ms
Speed: 1.1ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynhkT2J4QZwQgRhB5dMREg_270.JPG: 480x640 (no detections), 271.0ms
Speed: 1.1ms preprocess, 271.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynihkjyj8NXOF2YWVaRi-A_0.JPG: 480x640 (no detections), 270.5ms
Speed: 1.1ms preprocess, 270.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynihkjyj8NXOF2YWVaRi-A_90.JPG: 480x640 (no detections), 271.6ms
Speed: 1.0ms preprocess, 271.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynihkjyj8NXOF2YWVaRi-A_180.JPG: 480x640 (no detections), 275.0ms
Speed: 1.1ms preprocess, 275.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynihkjyj8NXOF2YWVaRi-A_270.JPG: 480x640 (no detections), 272.0ms
Speed: 1.0ms preprocess, 272.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynk4EM1ApnkJ8r--cowQzQ_0.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynk4EM1ApnkJ8r--cowQzQ_90.JPG: 480x640 (no detections), 269.8ms
Speed: 1.0ms preprocess, 269.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynk4EM1ApnkJ8r--cowQzQ_180.JPG: 480x640 (no detections), 268.5ms
Speed: 1.1ms preprocess, 268.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynk4EM1ApnkJ8r--cowQzQ_270.JPG: 480x640 (no detections), 271.6ms
Speed: 1.0ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynl8NKvkNYkv3wfkIvdiqg_0.JPG: 480x640 (no detections), 273.5ms

Speed: 1.1ms preprocess, 273.5ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynl8NKvkNYkv3wfkIvdiqg_90.JPG: 480x640 (no detections), 272.5ms
Speed: 1.0ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynl8NKvkNYkv3wfkIvdiqg_180.JPG: 480x640 (no detections), 271.8ms
Speed: 1.0ms preprocess, 271.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynl8NKvkNYkv3wfkIvdiqg_270.JPG: 480x640 (no detections), 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynlIv8QVK2sSsWobjbVsQw_0.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynlIv8QVK2sSsWobjbVsQw_90.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynlIv8QVK2sSsWobjbVsQw_180.JPG: 480x640 (no detections), 274.3ms
Speed: 1.1ms preprocess, 274.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynlIv8QVK2sSsWobjbVsQw_270.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynlX3dMDIyOBiPZG1qQtaw_0.JPG: 480x640 (no detections), 271.0ms
Speed: 1.1ms preprocess, 271.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynlX3dMDIyOBiPZG1qQtaw_90.JPG: 480x640 (no detections), 272.9ms
Speed: 1.0ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynlX3dMDIyOBiPZG1qQtaw_180.JPG: 480x640 (no detections), 271.9ms
Speed: 1.0ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynlX3dMDIyOBiPZG1qQtaw_270.JPG: 480x640 (no detections), 273.5ms
Speed: 1.0ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynoW4SuYnOItHvoQ3nL7ZQ_0.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynoW4SuYnOItHvoQ3nL7ZQ_90.JPG: 480x640 (no detections), 273.4ms
Speed: 1.0ms preprocess, 273.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynoW4SuYnOItHvoQ3nL7ZQ_180.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynoW4SuYnOItHvoQ3nL7ZQ_270.JPG: 480x640 (no detections), 277.5ms
Speed: 1.0ms preprocess, 277.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynpoEDBVUE0fzD7wHHuexA_0.JPG: 480x640 (no detections), 273.1ms
Speed: 1.1ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynpoEDBVUE0fzD7wHHuexA_90.JPG: 480x640 (no detections), 273.5ms
Speed: 1.0ms preprocess, 273.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynpoEDBVUE0fzD7wHHuexA_180.JPG: 480x640 (no detections), 274.1ms
Speed: 1.0ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynpoEDBVUE0fzD7wHHuexA_270.JPG: 480x640 (no detections), 269.9ms
Speed: 1.0ms preprocess, 269.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynrcZQ7oVjUxgCZjwfe_ZA_0.JPG: 480x640 2 Wastes, 275.4ms
Speed: 1.1ms preprocess, 275.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynrcZQ7oVjUxgCZjwfe_ZA_90.JPG: 480x640 1 Waste, 272.1ms
Speed: 1.0ms preprocess, 272.1ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynrcZQ7oVjUxgCZjwfe_ZA_180.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynrcZQ7oVjUxgCZjwfe_ZA_270.JPG: 480x640 1 Waste, 267.9ms
Speed: 1.0ms preprocess, 267.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yns3gOLPA4hR73Nj05nxOQ_0.JPG: 480x640 (no detections), 279.5ms
Speed: 1.2ms preprocess, 279.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yns3gOLPA4hR73Nj05nxOQ_90.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yns3gOLPA4hR73Nj05nxOQ_180.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/yns3gOLPA4hR73Nj05nxOQ_270.JPG: 480x640 (no detections), 274.0ms
Speed: 1.0ms preprocess, 274.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynwD61v789--1nfXZv3pwg_0.JPG: 480x640 (no detections), 271.8ms
Speed: 1.0ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynwD61v789--1nfXZv3pwg_90.JPG: 480x640 (no detections), 276.3ms
Speed: 1.2ms preprocess, 276.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynwD61v789--1nfXZv3pwg_180.JPG: 480x640 (no detections), 274.9ms
Speed: 1.2ms preprocess, 274.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynwD61v789--1nfXZv3pwg_270.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynxox-nh3QRo_KCVUsEX9A_0.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynxox-nh3QRo_KCVUsEX9A_90.JPG: 480x640 (no detections), 273.4ms
Speed: 1.0ms preprocess, 273.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynxox-nh3QRo_KCVUsEX9A_180.JPG: 480x640 (no detections), 271.0ms
Speed: 1.1ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/N/ynxox-nh3QRo_KCVUsEX9A_270.JPG: 480x640 (no detections), 269.4ms
Speed: 1.1ms preprocess, 269.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yo0Tncjuq8UHENIONKGHWg_0.JPG: 480x640 (no detections), 271.9ms
Speed: 1.0ms preprocess, 271.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yo0Tncjuq8UHENIONKGHWg_90.JPG: 480x640 (no detections), 272.9ms
Speed: 1.0ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yo0Tncjuq8UHENIONKGHWg_180.JPG: 480x640 (no detections), 276.5ms
Speed: 1.1ms preprocess, 276.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yo0Tncjuq8UHENIONKGHWg_270.JPG: 480x640 (no detections), 275.6ms
Speed: 1.1ms preprocess, 275.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yo1OYjI7BS0PgReUFQcy-w_0.JPG: 480x640 (no detections), 271.5ms
Speed: 1.1ms preprocess, 271.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yo1OYjI7BS0PgReUFQcy-w_90.JPG: 480x640 (no detections), 274.3ms
Speed: 1.0ms preprocess, 274.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yo1OYjI7BS0PgReUFQcy-w_180.JPG: 480x640 (no detections), 275.5ms
Speed: 1.1ms preprocess, 275.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yo1OYjI7BS0PgReUFQcy-w_270.JPG: 480x640 (no detections), 271.3ms
Speed: 1.0ms preprocess, 271.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yo3JNqWkKteT01RxCNn6mQ_0.JPG: 480x640 (no detections), 270.3ms
Speed: 1.0ms preprocess, 270.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yo3JNqWkKteT01RxCNn6mQ_90.JPG: 480x640 (no detections), 272.7ms
Speed: 1.0ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yo3JNqWkKteT01RxCNn6mQ_180.JPG: 480x640 (no detections), 273.9ms
Speed: 1.2ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yo3JNqWkKteT01RxCNn6mQ_270.JPG: 480x640 (no detections), 272.8ms
Speed: 1.2ms preprocess, 272.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yo42tYDzwEtRPvHRGqilBA_0.JPG: 480x640 1 Waste, 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yo42tYDzwEtRPvHRGqilBA_90.JPG: 480x640 (no detections), 275.7ms
Speed: 1.1ms preprocess, 275.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yo42tYDzwEtRPvHRGqilBA_180.JPG: 480x640 (no detections), 272.5ms
Speed: 1.1ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yo42tYDzwEtRPvHRGqilBA_270.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yo4SbrLlrFcUs3jSQhNjNA_0.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yo4SbrLlrFcUs3jSQhNjNA_90.JPG: 480x640 (no detections), 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yo4SbrLlrFcUs3jSQhNjNA_180.JPG: 480x640 (no detections), 270.6ms
Speed: 1.0ms preprocess, 270.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yo4SbrLlrFcUs3jSQhNjNA_270.JPG: 480x640 (no detections), 273.2ms
Speed: 1.1ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yo4_Tu5ckSPAYsKWWT4rMw_0.JPG: 480x640 (no detections), 274.8ms
Speed: 1.1ms preprocess, 274.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yo4_Tu5ckSPAYsKWWT4rMw_90.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yo4_Tu5ckSPAYsKWWT4rMw_180.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yo4_Tu5ckSPAYsKWWT4rMw_270.JPG: 480x640 (no detections), 268.7ms
Speed: 1.0ms preprocess, 268.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yo547vTwmPOiqjooiHsi4Q_0.JPG: 480x640 (no detections), 268.8ms
Speed: 1.1ms preprocess, 268.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yo547vTwmPOiqjooiHsi4Q_90.JPG: 480x640 (no detections), 270.0ms
Speed: 1.0ms preprocess, 270.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yo547vTwmPOiqjooiHsi4Q_180.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yo547vTwmPOiqjooiHsi4Q_270.JPG: 480x640 (no detections), 273.3ms
Speed: 1.2ms preprocess, 273.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yo59wVrlNI-zar46GauHQQ_0.JPG: 480x640 (no detections), 274.5ms
Speed: 1.5ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yo59wVrlNI-zar46GauHQQ_90.JPG: 480x640 (no detections), 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yo59wVrlNI-zar46GauHQQ_180.JPG: 480x640 (no detections), 269.5ms
Speed: 1.1ms preprocess, 269.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yo59wVrlNI-zar46GauHQQ_270.JPG: 480x640 (no detections), 274.4ms

Speed: 1.1ms preprocess, 274.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yo6krCsSkKr80g-CCYoJ0A_0.JPG: 480x640 (no detections), 273.0ms
Speed: 1.0ms preprocess, 273.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yo6krCsSkKr80g-CCYoJ0A_90.JPG: 480x640 (no detections), 274.6ms
Speed: 1.0ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yo6krCsSkKr80g-CCYoJ0A_180.JPG: 480x640 (no detections), 271.8ms
Speed: 1.0ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yo6krCsSkKr80g-CCYoJ0A_270.JPG: 480x640 (no detections), 273.2ms
Speed: 1.0ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yo8DZT-NOpq8kOMiPRywzQ_0.JPG: 480x640 (no detections), 274.8ms
Speed: 1.0ms preprocess, 274.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yo8DZT-NOpq8kOMiPRywzQ_90.JPG: 480x640 (no detections), 282.3ms
Speed: 1.0ms preprocess, 282.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yo8DZT-NOpq8kOMiPRywzQ_180.JPG: 480x640 (no detections), 273.6ms
Speed: 1.2ms preprocess, 273.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yo8DZT-NOpq8kOMiPRywzQ_270.JPG: 480x640 (no detections), 273.7ms
Speed: 1.0ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yo8xqlTNBERsoiOcITG3Qg_0.JPG: 480x640 (no detections), 270.9ms
Speed: 1.1ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yo8xqlTNBERsoiOcITG3Qg_90.JPG: 480x640 (no detections), 272.1ms
Speed: 1.0ms preprocess, 272.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yo8xqlTNBERsoiOcITG3Qg_180.JPG: 480x640 (no detections), 275.0ms
Speed: 1.1ms preprocess, 275.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yo8xqlTNBERsoiOcITG3Qg_270.JPG: 480x640 (no detections), 269.4ms
Speed: 1.0ms preprocess, 269.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yo9Ae71IELoac93MA2SUSQ_0.JPG: 480x640 (no detections), 274.5ms
Speed: 1.0ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yo9Ae71IELoac93MA2SUSQ_90.JPG: 480x640 (no detections), 279.1ms
Speed: 1.1ms preprocess, 279.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yo9Ae71IELoac93MA2SUSQ_180.JPG: 480x640 (no detections), 274.0ms
Speed: 1.1ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yo9Ae71IELoac93MA2SUSQ_270.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yo9iRNwI2Sfk-REqCUzGTg_0.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yo9iRNwI2Sfk-REqCUzGTg_90.JPG: 480x640 (no detections), 275.4ms
Speed: 1.0ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yo9iRNwI2Sfk-REqCUzGTg_180.JPG: 480x640 (no detections), 274.1ms
Speed: 1.0ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yo9iRNwI2Sfk-REqCUzGTg_270.JPG: 480x640 (no detections), 273.6ms
Speed: 1.0ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yoCUxvkFB-k12qKE8lBdBQ_0.JPG: 480x640 (no detections), 275.4ms
Speed: 1.0ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yoCUxvkFB-k12qKE8lBdBQ_90.JPG: 480x640 (no detections), 273.4ms
Speed: 1.0ms preprocess, 273.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yoCUxvkFB-k12qKE8lBdBQ_180.JPG: 480x640 (no detections), 272.8ms
Speed: 1.0ms preprocess, 272.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yoCUxvkFB-k12qKE8lBdBQ_270.JPG: 480x640 (no detections), 272.0ms
Speed: 1.0ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yoE5U3BjNpGzVqtJLxnVLA_0.JPG: 480x640 (no detections), 273.0ms
Speed: 1.0ms preprocess, 273.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yoE5U3BjNpGzVqtJLxnVLA_90.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yoE5U3BjNpGzVqtJLxnVLA_180.JPG: 480x640 (no detections), 273.1ms
Speed: 1.0ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yoE5U3BjNpGzVqtJLxnVLA_270.JPG: 480x640 (no detections), 270.9ms
Speed: 1.1ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yoFpAI9BLBWhhApiAGKEkw_0.JPG: 480x640 (no detections), 276.5ms
Speed: 1.1ms preprocess, 276.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yoFpAI9BLBWhhApiAGKEkw_90.JPG: 480x640 (no detections), 274.0ms
Speed: 1.0ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yoFpAI9BLBWhhApiAGKEkw_180.JPG: 480x640 (no detections), 269.0ms
Speed: 1.1ms preprocess, 269.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yoFpAI9BLBWhhApiAGKEkw_270.JPG: 480x640 (no detections), 271.9ms
Speed: 1.0ms preprocess, 271.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yoJGksvon_qSyPztHrPdIg_0.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yoJGksvon_qSyPztHrPdIg_90.JPG: 480x640 (no detections), 272.3ms
Speed: 1.0ms preprocess, 272.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yoJGksvon_qSyPztHrPdIg_180.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yoJGksvon_qSyPztHrPdIg_270.JPG: 480x640 (no detections), 272.6ms
Speed: 1.0ms preprocess, 272.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yoJQmhw1Up8GHBPiRg_ixQ_0.JPG: 480x640 (no detections), 269.6ms
Speed: 1.1ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yoJQmhw1Up8GHBPiRg_ixQ_90.JPG: 480x640 (no detections), 268.1ms
Speed: 1.1ms preprocess, 268.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yoJQmhw1Up8GHBPiRg_ixQ_180.JPG: 480x640 (no detections), 271.5ms
Speed: 1.1ms preprocess, 271.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yoJQmhw1Up8GHBPiRg_ixQ_270.JPG: 480x640 (no detections), 273.0ms
Speed: 1.0ms preprocess, 273.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yoKY9fn8TV4rJ6toqnAg1Q_0.JPG: 480x640 (no detections), 273.4ms
Speed: 1.1ms preprocess, 273.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yoKY9fn8TV4rJ6toqnAg1Q_90.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yoKY9fn8TV4rJ6toqnAg1Q_180.JPG: 480x640 (no detections), 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yoKY9fn8TV4rJ6toqnAg1Q_270.JPG: 480x640 (no detections), 273.0ms
Speed: 1.0ms preprocess, 273.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yoL5zmiQqvDHu1EvkNVf9w_0.JPG: 480x640 (no detections), 271.9ms
Speed: 1.2ms preprocess, 271.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yoL5zmiQqvDHu1EvkNVf9w_90.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yoL5zmiQqvDHu1EvkNVf9w_180.JPG: 480x640 (no detections), 272.1ms
Speed: 1.0ms preprocess, 272.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yoL5zmiQqvDHu1EvkNVf9w_270.JPG: 480x640 (no detections), 270.1ms
Speed: 1.0ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yoM4Sf27dGoO2dM5ggeCtQ_0.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yoM4Sf27dGoO2dM5ggeCtQ_90.JPG: 480x640 (no detections), 272.0ms
Speed: 1.1ms preprocess, 272.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yoM4Sf27dGoO2dM5ggeCtQ_180.JPG: 480x640 (no detections), 278.1ms
Speed: 1.0ms preprocess, 278.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yoM4Sf27dGoO2dM5ggeCtQ_270.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yoRPu9EIIAkA2Z6tM_DaNQ_0.JPG: 480x640 (no detections), 269.8ms
Speed: 1.1ms preprocess, 269.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yoRPu9EIIAkA2Z6tM_DaNQ_90.JPG: 480x640 (no detections), 276.6ms
Speed: 1.0ms preprocess, 276.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yoRPu9EIIAkA2Z6tM_DaNQ_180.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yoRPu9EIIAkA2Z6tM_DaNQ_270.JPG: 480x640 (no detections), 273.6ms
Speed: 1.1ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yoTRcW656J92MDnvaiCh2Q_0.JPG: 480x640 (no detections), 272.4ms
Speed: 1.1ms preprocess, 272.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yoTRcW656J92MDnvaiCh2Q_90.JPG: 480x640 (no detections), 271.0ms
Speed: 1.0ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yoTRcW656J92MDnvaiCh2Q_180.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yoTRcW656J92MDnvaiCh2Q_270.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yoaFiZbxfqMqtRO-waoTdA_0.JPG: 480x640 (no detections), 273.6ms
Speed: 1.1ms preprocess, 273.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yoaFiZbxfqMqtRO-waoTdA_90.JPG: 480x640 (no detections), 271.6ms
Speed: 1.0ms preprocess, 271.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yoaFiZbxfqMqtRO-waoTdA_180.JPG: 480x640 (no detections), 270.4ms
Speed: 1.0ms preprocess, 270.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yoaFiZbxfqMqtRO-waoTdA_270.JPG: 480x640 (no detections), 272.9ms
Speed: 1.2ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yogWoc0GwMmBbUvCY8Z4mA_0.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yogWoc0GwMmBbUvCY8Z4mA_90.JPG: 480x640 (no detections), 274.8ms
Speed: 1.1ms preprocess, 274.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yogWoc0GwMmBbUvCY8Z4mA_180.JPG: 480x640 (no detections), 269.0ms

Speed: 1.0ms preprocess, 269.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yogWoc0GwMmBbUvCY8Z4mA_270.JPG: 480x640 (no detections), 272.7ms
Speed: 1.0ms preprocess, 272.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yogxg-1BuzrE73Yanomx8Q_0.JPG: 480x640 (no detections), 272.6ms
Speed: 1.0ms preprocess, 272.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yogxg-1BuzrE73Yanomx8Q_90.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yogxg-1BuzrE73Yanomx8Q_180.JPG: 480x640 (no detections), 268.9ms
Speed: 1.0ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yogxg-1BuzrE73Yanomx8Q_270.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yoh3UXU-AUb-DpNb4tBR2w_0.JPG: 480x640 (no detections), 275.5ms
Speed: 1.3ms preprocess, 275.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yoh3UXU-AUb-DpNb4tBR2w_90.JPG: 480x640 (no detections), 274.6ms
Speed: 1.1ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yoh3UXU-AUb-DpNb4tBR2w_180.JPG: 480x640 (no detections), 272.4ms
Speed: 1.0ms preprocess, 272.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yoh3UXU-AUb-DpNb4tBR2w_270.JPG: 480x640 (no detections), 270.4ms
Speed: 1.1ms preprocess, 270.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/you_ZUMEwCl95DjyM9ca3A_0.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/you_ZUMEwCl95DjyM9ca3A_90.JPG: 480x640 (no detections), 274.7ms
Speed: 1.1ms preprocess, 274.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/you_ZUMEwCl95DjyM9ca3A_180.JPG: 480x640 (no detections), 272.0ms
Speed: 1.0ms preprocess, 272.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/you_ZUMEwCl95DjyM9ca3A_270.JPG: 480x640 (no detections), 275.4ms
Speed: 1.1ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yoy5uDDx3Fz32yh5f2doSw_0.JPG: 480x640 (no detections), 277.1ms
Speed: 1.0ms preprocess, 277.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yoy5uDDx3Fz32yh5f2doSw_90.JPG: 480x640 (no detections), 268.0ms
Speed: 1.1ms preprocess, 268.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yoy5uDDx3Fz32yh5f2doSw_180.JPG: 480x640 (no detections), 274.0ms
Speed: 1.1ms preprocess, 274.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/O/yoy5uDDx3Fz32yh5f2doSw_270.JPG: 480x640 (no detections), 273.9ms
Speed: 1.0ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yp-GzDxM_EHs9kiM8Q4Niw_0.JPG: 480x640 (no detections), 284.9ms
Speed: 1.0ms preprocess, 284.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yp-GzDxM_EHs9kiM8Q4Niw_90.JPG: 480x640 (no detections), 268.5ms
Speed: 1.1ms preprocess, 268.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yp-GzDxM_EHs9kiM8Q4Niw_180.JPG: 480x640 (no detections), 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yp-GzDxM_EHs9kiM8Q4Niw_270.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yp-rloM1aiVmHQGnKAcl_w_0.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yp-rloM1aiVmHQGnKAcl_w_90.JPG: 480x640 (no detections), 270.7ms
Speed: 1.0ms preprocess, 270.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yp-rloM1aiVmHQGnKAcl_w_180.JPG: 480x640 (no detections), 272.3ms
Speed: 1.0ms preprocess, 272.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yp-rloM1aiVmHQGnKAcl_w_270.JPG: 480x640 (no detections), 270.8ms
Speed: 1.0ms preprocess, 270.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yp3QDTBIO4NrJrYXLY5q4w_0.JPG: 480x640 (no detections), 271.3ms
Speed: 1.0ms preprocess, 271.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yp3QDTBIO4NrJrYXLY5q4w_90.JPG: 480x640 (no detections), 273.4ms
Speed: 1.0ms preprocess, 273.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yp3QDTBIO4NrJrYXLY5q4w_180.JPG: 480x640 (no detections), 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yp3QDTBIO4NrJrYXLY5q4w_270.JPG: 480x640 (no detections), 273.0ms
Speed: 1.0ms preprocess, 273.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yp5CtgA-1NDOByKY64yaiA_0.JPG: 480x640 (no detections), 272.3ms
Speed: 1.0ms preprocess, 272.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yp5CtgA-1NDOByKY64yaiA_90.JPG: 480x640 (no detections), 271.8ms
Speed: 1.0ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yp5CtgA-1NDOByKY64yaiA_180.JPG: 480x640 (no detections), 269.6ms
Speed: 1.1ms preprocess, 269.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yp5CtgA-1NDOByKY64yaiA_270.JPG: 480x640 (no detections), 270.6ms
Speed: 1.0ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yp5cv-2Dk2wFiL8IA9RObA_0.JPG: 480x640 (no detections), 275.7ms
Speed: 1.0ms preprocess, 275.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yp5cv-2Dk2wFiL8IA9RObA_90.JPG: 480x640 (no detections), 276.4ms
Speed: 1.0ms preprocess, 276.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yp5cv-2Dk2wFiL8IA9RObA_180.JPG: 480x640 (no detections), 270.9ms
Speed: 1.1ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yp5cv-2Dk2wFiL8IA9RObA_270.JPG: 480x640 (no detections), 272.6ms
Speed: 1.2ms preprocess, 272.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yp6KunRxvAONP6Y8kmbhJw_0.JPG: 480x640 1 Waste, 268.9ms
Speed: 1.1ms preprocess, 268.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yp6KunRxvAONP6Y8kmbhJw_90.JPG: 480x640 1 Waste, 274.7ms
Speed: 1.0ms preprocess, 274.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yp6KunRxvAONP6Y8kmbhJw_180.JPG: 480x640 (no detections), 271.7ms
Speed: 1.2ms preprocess, 271.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yp6KunRxvAONP6Y8kmbhJw_270.JPG: 480x640 1 Waste, 274.6ms
Speed: 1.1ms preprocess, 274.6ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yp84F3B9lnRgb1yR6G6Ptg_0.JPG: 480x640 (no detections), 270.9ms
Speed: 1.1ms preprocess, 270.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yp84F3B9lnRgb1yR6G6Ptg_90.JPG: 480x640 (no detections), 274.4ms
Speed: 1.1ms preprocess, 274.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yp84F3B9lnRgb1yR6G6Ptg_180.JPG: 480x640 (no detections), 275.9ms
Speed: 1.1ms preprocess, 275.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yp84F3B9lnRgb1yR6G6Ptg_270.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypAdnwB-XM-GgiLXFtLPTw_0.JPG: 480x640 (no detections), 269.2ms
Speed: 1.0ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypAdnwB-XM-GgiLXFtLPTw_90.JPG: 480x640 (no detections), 273.1ms
Speed: 1.1ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypAdnwB-XM-GgiLXFtLPTw_180.JPG: 480x640 (no detections), 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypAdnwB-XM-GgiLXFtLPTw_270.JPG: 480x640 (no detections), 277.4ms
Speed: 1.1ms preprocess, 277.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypBPIBdUP-RAPGYiTFXBsA_0.JPG: 480x640 (no detections), 274.5ms
Speed: 1.1ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypBPIBdUP-RAPGYiTFXBsA_90.JPG: 480x640 (no detections), 267.5ms
Speed: 1.0ms preprocess, 267.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypBPIBdUP-RAPGYiTFXBsA_180.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypBPIBdUP-RAPGYiTFXBsA_270.JPG: 480x640 (no detections), 274.2ms
Speed: 1.0ms preprocess, 274.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypBegQZM36MqvF3ilUyN_A_0.JPG: 480x640 (no detections), 271.3ms
Speed: 1.0ms preprocess, 271.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypBegQZM36MqvF3ilUyN_A_90.JPG: 480x640 (no detections), 274.7ms
Speed: 1.1ms preprocess, 274.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypBegQZM36MqvF3ilUyN_A_180.JPG: 480x640 (no detections), 272.1ms
Speed: 1.1ms preprocess, 272.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypBegQZM36MqvF3ilUyN_A_270.JPG: 480x640 (no detections), 275.2ms
Speed: 1.1ms preprocess, 275.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypBgt7jvKx6KgxNh0x1GRA_0.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypBgt7jvKx6KgxNh0x1GRA_90.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypBgt7jvKx6KgxNh0x1GRA_180.JPG: 480x640 (no detections), 271.9ms
Speed: 1.0ms preprocess, 271.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypBgt7jvKx6KgxNh0x1GRA_270.JPG: 480x640 (no detections), 274.5ms
Speed: 1.3ms preprocess, 274.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypEGSF85nWAbDA0wAhnoyg_0.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypEGSF85nWAbDA0wAhnoyg_90.JPG: 480x640 (no detections), 273.9ms
Speed: 1.0ms preprocess, 273.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypEGSF85nWAbDA0wAhnoyg_180.JPG: 480x640 (no detections), 278.1ms
Speed: 1.0ms preprocess, 278.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypEGSF85nWAbDA0wAhnoyg_270.JPG: 480x640 1 Waste, 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypHhBWveGOPa_4n7IJ35MQ_0.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypHhBWveGOPa_4n7IJ35MQ_90.JPG: 480x640 (no detections), 269.9ms

Speed: 1.0ms preprocess, 269.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypHhBWveGOPa_4n7IJ35MQ_180.JPG: 480x640 (no detections), 276.2ms
Speed: 1.1ms preprocess, 276.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypHhBWveGOPa_4n7IJ35MQ_270.JPG: 480x640 (no detections), 268.9ms
Speed: 1.1ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypIdC5bf4zm4Fe7i_StVmQ_0.JPG: 480x640 (no detections), 275.5ms
Speed: 1.0ms preprocess, 275.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypIdC5bf4zm4Fe7i_StVmQ_90.JPG: 480x640 (no detections), 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypIdC5bf4zm4Fe7i_StVmQ_180.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypIdC5bf4zm4Fe7i_StVmQ_270.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypKAYqXuyrGNEd-KQn_KUw_0.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypKAYqXuyrGNEd-KQn_KUw_90.JPG: 480x640 (no detections), 268.0ms
Speed: 1.0ms preprocess, 268.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypKAYqXuyrGNEd-KQn_KUw_180.JPG: 480x640 (no detections), 269.1ms
Speed: 1.1ms preprocess, 269.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypKAYqXuyrGNEd-KQn_KUw_270.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypMZPxurqRomfzmu4u5aUQ_0.JPG: 480x640 (no detections), 276.7ms
Speed: 1.0ms preprocess, 276.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypMZPxurqRomfzmu4u5aUQ_90.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypMZPxurqRomfzmu4u5aUQ_180.JPG: 480x640 (no detections), 263.7ms
Speed: 1.1ms preprocess, 263.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypMZPxurqRomfzmu4u5aUQ_270.JPG: 480x640 (no detections), 272.4ms
Speed: 1.0ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypSVvHDf3M8xRqo6hPVrIg_0.JPG: 480x640 (no detections), 273.9ms
Speed: 1.0ms preprocess, 273.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypSVvHDf3M8xRqo6hPVrIg_90.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypSVvHDf3M8xRqo6hPVrIg_180.JPG: 480x640 (no detections), 274.4ms
Speed: 1.0ms preprocess, 274.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypSVvHDf3M8xRqo6hPVrIg_270.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypUDMxHBeys7xmdE_p-VYA_0.JPG: 480x640 (no detections), 273.9ms
Speed: 1.1ms preprocess, 273.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypUDMxHBeys7xmdE_p-VYA_90.JPG: 480x640 (no detections), 270.9ms
Speed: 1.1ms preprocess, 270.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypUDMxHBeys7xmdE_p-VYA_180.JPG: 480x640 (no detections), 269.6ms
Speed: 1.0ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypUDMxHBeys7xmdE_p-VYA_270.JPG: 480x640 (no detections), 267.9ms
Speed: 1.1ms preprocess, 267.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypViEFlHm6RBuodhMwSw_w_0.JPG: 480x640 (no detections), 272.5ms
Speed: 1.0ms preprocess, 272.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypViEFlHm6RBuodhMwSw_w_90.JPG: 480x640 (no detections), 274.7ms
Speed: 1.1ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypViEFlHm6RBuodhMwSw_w_180.JPG: 480x640 (no detections), 275.6ms
Speed: 1.2ms preprocess, 275.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypViEFlHm6RBuodhMwSw_w_270.JPG: 480x640 (no detections), 276.2ms
Speed: 1.0ms preprocess, 276.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yp_LXXtZKkUYEOf54mCSbw_0.JPG: 480x640 (no detections), 272.0ms
Speed: 1.1ms preprocess, 272.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yp_LXXtZKkUYEOf54mCSbw_90.JPG: 480x640 (no detections), 270.7ms
Speed: 1.0ms preprocess, 270.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yp_LXXtZKkUYEOf54mCSbw_180.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yp_LXXtZKkUYEOf54mCSbw_270.JPG: 480x640 (no detections), 272.1ms
Speed: 1.2ms preprocess, 272.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yp_xkBF9PZlMoTeNNMCVqw_0.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yp_xkBF9PZlMoTeNNMCVqw_90.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yp_xkBF9PZlMoTeNNMCVqw_180.JPG: 480x640 (no detections), 270.9ms
Speed: 1.0ms preprocess, 270.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yp_xkBF9PZlMoTeNNMCVqw_270.JPG: 480x640 (no detections), 276.8ms
Speed: 1.0ms preprocess, 276.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypc6GRMIb3hlGC-0Z9uMug_0.JPG: 480x640 (no detections), 273.9ms
Speed: 1.1ms preprocess, 273.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypc6GRMIb3hlGC-0Z9uMug_90.JPG: 480x640 (no detections), 271.5ms
Speed: 1.3ms preprocess, 271.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypc6GRMIb3hlGC-0Z9uMug_180.JPG: 480x640 (no detections), 271.7ms
Speed: 1.0ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypc6GRMIb3hlGC-0Z9uMug_270.JPG: 480x640 (no detections), 269.6ms
Speed: 1.4ms preprocess, 269.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yphBLmnR3YkdQmxyFUXL_A_0.JPG: 480x640 (no detections), 272.4ms
Speed: 1.2ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yphBLmnR3YkdQmxyFUXL_A_90.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yphBLmnR3YkdQmxyFUXL_A_180.JPG: 480x640 (no detections), 269.8ms
Speed: 1.0ms preprocess, 269.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yphBLmnR3YkdQmxyFUXL_A_270.JPG: 480x640 (no detections), 272.0ms
Speed: 1.1ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypiajEsJk_Eqs8-6AI5QPQ_0.JPG: 480x640 (no detections), 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypiajEsJk_Eqs8-6AI5QPQ_90.JPG: 480x640 (no detections), 273.4ms
Speed: 1.1ms preprocess, 273.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypiajEsJk_Eqs8-6AI5QPQ_180.JPG: 480x640 (no detections), 269.5ms
Speed: 1.0ms preprocess, 269.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypiajEsJk_Eqs8-6AI5QPQ_270.JPG: 480x640 (no detections), 271.3ms
Speed: 1.0ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypj9-VJzP_ZvHh0jJxJofQ_0.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypj9-VJzP_ZvHh0jJxJofQ_90.JPG: 480x640 (no detections), 269.9ms
Speed: 1.2ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypj9-VJzP_ZvHh0jJxJofQ_180.JPG: 480x640 (no detections), 267.7ms
Speed: 1.1ms preprocess, 267.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypj9-VJzP_ZvHh0jJxJofQ_270.JPG: 480x640 (no detections), 273.6ms
Speed: 1.1ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypkcrI7ntZBiOqp4ectTNw_0.JPG: 480x640 (no detections), 272.5ms
Speed: 1.0ms preprocess, 272.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypkcrI7ntZBiOqp4ectTNw_90.JPG: 480x640 (no detections), 274.9ms
Speed: 1.0ms preprocess, 274.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypkcrI7ntZBiOqp4ectTNw_180.JPG: 480x640 (no detections), 269.8ms
Speed: 1.0ms preprocess, 269.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypkcrI7ntZBiOqp4ectTNw_270.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yplLMonWpOqkWA6M9PkGEQ_0.JPG: 480x640 (no detections), 273.5ms
Speed: 1.0ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yplLMonWpOqkWA6M9PkGEQ_90.JPG: 480x640 (no detections), 270.4ms
Speed: 1.1ms preprocess, 270.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yplLMonWpOqkWA6M9PkGEQ_180.JPG: 480x640 (no detections), 274.1ms
Speed: 1.0ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yplLMonWpOqkWA6M9PkGEQ_270.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypqwGyUZBCf4TgRyCuHxcg_0.JPG: 480x640 1 Waste, 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypqwGyUZBCf4TgRyCuHxcg_90.JPG: 480x640 (no detections), 274.6ms
Speed: 1.5ms preprocess, 274.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypqwGyUZBCf4TgRyCuHxcg_180.JPG: 480x640 (no detections), 275.3ms
Speed: 1.2ms preprocess, 275.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypqwGyUZBCf4TgRyCuHxcg_270.JPG: 480x640 (no detections), 269.8ms
Speed: 1.1ms preprocess, 269.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yprgh6POYObhiUzzY7guTA_0.JPG: 480x640 (no detections), 275.3ms
Speed: 1.1ms preprocess, 275.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yprgh6POYObhiUzzY7guTA_90.JPG: 480x640 (no detections), 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yprgh6POYObhiUzzY7guTA_180.JPG: 480x640 (no detections), 270.7ms
Speed: 1.0ms preprocess, 270.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/yprgh6POYObhiUzzY7guTA_270.JPG: 480x640 (no detections), 270.6ms
Speed: 1.0ms preprocess, 270.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypsHhw-AikOEiby-RNRLRQ_0.JPG: 480x640 (no detections), 271.3ms

Speed: 1.0ms preprocess, 271.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypsHhw-AikOEiby-RNRLRQ_90.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypsHhw-AikOEiby-RNRLRQ_180.JPG: 480x640 (no detections), 272.5ms
Speed: 1.0ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypsHhw-AikOEiby-RNRLRQ_270.JPG: 480x640 (no detections), 271.6ms
Speed: 1.0ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypsgqrelsCXwm1MluO-bNg_0.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypsgqrelsCXwm1MluO-bNg_90.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypsgqrelsCXwm1MluO-bNg_180.JPG: 480x640 (no detections), 269.8ms
Speed: 1.1ms preprocess, 269.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypsgqrelsCXwm1MluO-bNg_270.JPG: 480x640 (no detections), 270.3ms
Speed: 1.0ms preprocess, 270.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypv8fyM5MtumsU2MtxI1qg_0.JPG: 480x640 (no detections), 274.3ms
Speed: 1.0ms preprocess, 274.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypv8fyM5MtumsU2MtxI1qg_90.JPG: 480x640 (no detections), 273.1ms
Speed: 1.1ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypv8fyM5MtumsU2MtxI1qg_180.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypv8fyM5MtumsU2MtxI1qg_270.JPG: 480x640 (no detections), 271.7ms
Speed: 1.0ms preprocess, 271.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypwpk-r4hQorJGZfoAhGRg_0.JPG: 480x640 (no detections), 276.4ms
Speed: 1.1ms preprocess, 276.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypwpk-r4hQorJGZfoAhGRg_90.JPG: 480x640 (no detections), 269.3ms
Speed: 1.0ms preprocess, 269.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypwpk-r4hQorJGZfoAhGRg_180.JPG: 480x640 (no detections), 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypwpk-r4hQorJGZfoAhGRg_270.JPG: 480x640 (no detections), 269.1ms
Speed: 1.1ms preprocess, 269.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypywTEficZc5UbxohxehUQ_0.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypywTEficZc5UbxohxehUQ_90.JPG: 480x640 (no detections), 274.6ms
Speed: 1.0ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypywTEficZc5UbxohxehUQ_180.JPG: 480x640 (no detections), 269.4ms
Speed: 1.3ms preprocess, 269.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypywTEficZc5UbxohxehUQ_270.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypzZ973xXNMclclr0n3myQ_0.JPG: 480x640 (no detections), 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypzZ973xXNMclclr0n3myQ_90.JPG: 480x640 1 Waste, 274.2ms
Speed: 1.1ms preprocess, 274.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypzZ973xXNMclclr0n3myQ_180.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/P/ypzZ973xXNMclclr0n3myQ_270.JPG: 480x640 (no detections), 270.9ms
Speed: 1.0ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yq-I9MSiMxTpFsxoP9PN6g_0.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yq-I9MSiMxTpFsxoP9PN6g_90.JPG: 480x640 (no detections), 270.9ms
Speed: 1.1ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yq-I9MSiMxTpFsxoP9PN6g_180.JPG: 480x640 1 Waste, 274.8ms
Speed: 1.1ms preprocess, 274.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yq-I9MSiMxTpFsxoP9PN6g_270.JPG: 480x640 (no detections), 272.4ms
Speed: 1.2ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yq198lXd2YHwf1Y2MgwAAA_0.JPG: 480x640 (no detections), 294.3ms
Speed: 1.1ms preprocess, 294.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yq198lXd2YHwf1Y2MgwAAA_90.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yq198lXd2YHwf1Y2MgwAAA_180.JPG: 480x640 (no detections), 289.0ms
Speed: 1.1ms preprocess, 289.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yq198lXd2YHwf1Y2MgwAAA_270.JPG: 480x640 (no detections), 283.4ms
Speed: 1.2ms preprocess, 283.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yq1RUTFnw29R8AAcwEtsWg_0.JPG: 480x640 (no detections), 275.2ms
Speed: 1.1ms preprocess, 275.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yq1RUTFnw29R8AAcwEtsWg_90.JPG: 480x640 (no detections), 291.8ms
Speed: 1.0ms preprocess, 291.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yq1RUTFnw29R8AAcwEtsWg_180.JPG: 480x640 (no detections), 284.1ms
Speed: 1.2ms preprocess, 284.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yq1RUTFnw29R8AAcwEtsWg_270.JPG: 480x640 (no detections), 272.7ms
Speed: 1.2ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yq1w7aGguff4XAN1tsSzNA_0.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yq1w7aGguff4XAN1tsSzNA_90.JPG: 480x640 (no detections), 274.1ms
Speed: 1.0ms preprocess, 274.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yq1w7aGguff4XAN1tsSzNA_180.JPG: 480x640 (no detections), 277.8ms
Speed: 1.5ms preprocess, 277.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yq1w7aGguff4XAN1tsSzNA_270.JPG: 480x640 (no detections), 292.9ms
Speed: 1.4ms preprocess, 292.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yq3LWPllQ3HYlPMkTnlMyA_0.JPG: 480x640 (no detections), 269.5ms
Speed: 1.1ms preprocess, 269.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yq3LWPllQ3HYlPMkTnlMyA_90.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yq3LWPllQ3HYlPMkTnlMyA_180.JPG: 480x640 (no detections), 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yq3LWPllQ3HYlPMkTnlMyA_270.JPG: 480x640 (no detections), 294.2ms
Speed: 1.1ms preprocess, 294.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yq3ywdRGL770c8r_TuepoA_0.JPG: 480x640 (no detections), 294.8ms
Speed: 1.1ms preprocess, 294.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yq3ywdRGL770c8r_TuepoA_90.JPG: 480x640 (no detections), 284.3ms
Speed: 1.3ms preprocess, 284.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yq3ywdRGL770c8r_TuepoA_180.JPG: 480x640 1 Waste, 286.9ms
Speed: 1.2ms preprocess, 286.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yq3ywdRGL770c8r_TuepoA_270.JPG: 480x640 (no detections), 280.3ms
Speed: 1.4ms preprocess, 280.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yq6uTWzEd1ZEUbwlVukuIg_0.JPG: 480x640 (no detections), 275.5ms
Speed: 1.1ms preprocess, 275.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yq6uTWzEd1ZEUbwlVukuIg_90.JPG: 480x640 (no detections), 326.2ms
Speed: 1.2ms preprocess, 326.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yq6uTWzEd1ZEUbwlVukuIg_180.JPG: 480x640 (no detections), 361.8ms
Speed: 1.2ms preprocess, 361.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yq6uTWzEd1ZEUbwlVukuIg_270.JPG: 480x640 (no detections), 310.7ms
Speed: 1.4ms preprocess, 310.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yq8ZyiuHowTrsYyzZ3ZukQ_0.JPG: 480x640 (no detections), 301.7ms
Speed: 1.2ms preprocess, 301.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yq8ZyiuHowTrsYyzZ3ZukQ_90.JPG: 480x640 (no detections), 290.3ms
Speed: 1.3ms preprocess, 290.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yq8ZyiuHowTrsYyzZ3ZukQ_180.JPG: 480x640 (no detections), 286.0ms
Speed: 1.2ms preprocess, 286.0ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yq8ZyiuHowTrsYyzZ3ZukQ_270.JPG: 480x640 (no detections), 276.1ms
Speed: 1.1ms preprocess, 276.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yq8vWfOkO1uf-U-YAHRKgA_0.JPG: 480x640 (no detections), 302.9ms
Speed: 1.1ms preprocess, 302.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yq8vWfOkO1uf-U-YAHRKgA_90.JPG: 480x640 (no detections), 288.4ms
Speed: 1.3ms preprocess, 288.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yq8vWfOkO1uf-U-YAHRKgA_180.JPG: 480x640 (no detections), 279.2ms
Speed: 1.1ms preprocess, 279.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yq8vWfOkO1uf-U-YAHRKgA_270.JPG: 480x640 (no detections), 303.3ms
Speed: 1.3ms preprocess, 303.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqD-3BacIdbQSTh9wKXoGg_0.JPG: 480x640 (no detections), 285.0ms
Speed: 1.1ms preprocess, 285.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqD-3BacIdbQSTh9wKXoGg_90.JPG: 480x640 (no detections), 274.2ms
Speed: 1.1ms preprocess, 274.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqD-3BacIdbQSTh9wKXoGg_180.JPG: 480x640 (no detections), 280.1ms
Speed: 1.0ms preprocess, 280.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqD-3BacIdbQSTh9wKXoGg_270.JPG: 480x640 (no detections), 282.9ms
Speed: 1.0ms preprocess, 282.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqGF7a8xGXWRaYQpbCSNvw_0.JPG: 480x640 (no detections), 276.4ms
Speed: 1.1ms preprocess, 276.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqGF7a8xGXWRaYQpbCSNvw_90.JPG: 480x640 (no detections), 279.8ms
Speed: 1.1ms preprocess, 279.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqGF7a8xGXWRaYQpbCSNvw_180.JPG: 480x640 (no detections), 274.8ms
Speed: 1.1ms preprocess, 274.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqGF7a8xGXWRaYQpbCSNvw_270.JPG: 480x640 (no detections), 275.4ms

Speed: 1.0ms preprocess, 275.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqHYxn6n3XxJisPrgskAzQ_0.JPG: 480x640 (no detections), 279.1ms
Speed: 1.0ms preprocess, 279.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqHYxn6n3XxJisPrgskAzQ_90.JPG: 480x640 (no detections), 357.0ms
Speed: 1.0ms preprocess, 357.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqHYxn6n3XxJisPrgskAzQ_180.JPG: 480x640 (no detections), 336.2ms
Speed: 1.2ms preprocess, 336.2ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqHYxn6n3XxJisPrgskAzQ_270.JPG: 480x640 (no detections), 298.0ms
Speed: 1.1ms preprocess, 298.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqJHhSFJT_44tqbs0lSnUw_0.JPG: 480x640 (no detections), 276.9ms
Speed: 1.1ms preprocess, 276.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqJHhSFJT_44tqbs0lSnUw_90.JPG: 480x640 (no detections), 271.0ms
Speed: 1.1ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqJHhSFJT_44tqbs0lSnUw_180.JPG: 480x640 (no detections), 277.3ms
Speed: 1.1ms preprocess, 277.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqJHhSFJT_44tqbs0lSnUw_270.JPG: 480x640 (no detections), 273.9ms
Speed: 1.1ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqP1_Hetk_1tPx07mhfUFg_0.JPG: 480x640 (no detections), 273.6ms
Speed: 1.1ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqP1_Hetk_1tPx07mhfUFg_90.JPG: 480x640 (no detections), 268.5ms
Speed: 1.0ms preprocess, 268.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqP1_Hetk_1tPx07mhfUFg_180.JPG: 480x640 (no detections), 276.9ms
Speed: 1.1ms preprocess, 276.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqP1_Hetk_1tPx07mhfUFg_270.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqPPF_aJ1-nMk03MDnwyUw_0.JPG: 480x640 (no detections), 270.9ms
Speed: 1.1ms preprocess, 270.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqPPF_aJ1-nMk03MDnwyUw_90.JPG: 480x640 (no detections), 272.7ms
Speed: 1.0ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqPPF_aJ1-nMk03MDnwyUw_180.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqPPF_aJ1-nMk03MDnwyUw_270.JPG: 480x640 (no detections), 271.7ms
Speed: 1.2ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqPPas8K1mrtdOIC-r-33Q_0.JPG: 480x640 1 Waste, 271.3ms
Speed: 1.0ms preprocess, 271.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqPPas8K1mrtdOIC-r-33Q_90.JPG: 480x640 (no detections), 269.9ms
Speed: 1.0ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqPPas8K1mrtdOIC-r-33Q_180.JPG: 480x640 (no detections), 274.6ms
Speed: 1.0ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqPPas8K1mrtdOIC-r-33Q_270.JPG: 480x640 (no detections), 275.4ms
Speed: 1.1ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqQiTS4LnWarYpyQicoQoQ_0.JPG: 480x640 (no detections), 268.1ms
Speed: 1.1ms preprocess, 268.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqQiTS4LnWarYpyQicoQoQ_90.JPG: 480x640 (no detections), 270.2ms
Speed: 1.0ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqQiTS4LnWarYpyQicoQoQ_180.JPG: 480x640 (no detections), 271.8ms
Speed: 1.0ms preprocess, 271.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqQiTS4LnWarYpyQicoQoQ_270.JPG: 480x640 (no detections), 280.0ms
Speed: 1.0ms preprocess, 280.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqRs9FMkqGh97ozNf9ILOQ_0.JPG: 480x640 (no detections), 294.8ms
Speed: 1.2ms preprocess, 294.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqRs9FMkqGh97ozNf9ILOQ_90.JPG: 480x640 (no detections), 273.3ms
Speed: 1.2ms preprocess, 273.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqRs9FMkqGh97ozNf9ILOQ_180.JPG: 480x640 (no detections), 301.8ms
Speed: 1.1ms preprocess, 301.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqRs9FMkqGh97ozNf9ILOQ_270.JPG: 480x640 (no detections), 289.2ms
Speed: 1.2ms preprocess, 289.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqTrqFYfqbywqIM6P0WLDw_0.JPG: 480x640 1 Waste, 278.3ms
Speed: 1.1ms preprocess, 278.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqTrqFYfqbywqIM6P0WLDw_90.JPG: 480x640 (no detections), 268.7ms
Speed: 1.0ms preprocess, 268.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqTrqFYfqbywqIM6P0WLDw_180.JPG: 480x640 (no detections), 278.9ms
Speed: 1.1ms preprocess, 278.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqTrqFYfqbywqIM6P0WLDw_270.JPG: 480x640 (no detections), 276.4ms
Speed: 1.1ms preprocess, 276.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqURbkuW0YC_-n6JNLJFJQ_0.JPG: 480x640 (no detections), 292.9ms
Speed: 1.1ms preprocess, 292.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqURbkuW0YC_-n6JNLJFJQ_90.JPG: 480x640 (no detections), 283.4ms
Speed: 1.0ms preprocess, 283.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqURbkuW0YC_-n6JNLJFJQ_180.JPG: 480x640 (no detections), 289.3ms
Speed: 1.2ms preprocess, 289.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqURbkuW0YC_-n6JNLJFJQ_270.JPG: 480x640 (no detections), 274.0ms
Speed: 1.1ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqX-0Q_Le4utJmChFUjrHA_0.JPG: 480x640 (no detections), 282.9ms
Speed: 1.1ms preprocess, 282.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqX-0Q_Le4utJmChFUjrHA_90.JPG: 480x640 (no detections), 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqX-0Q_Le4utJmChFUjrHA_180.JPG: 480x640 (no detections), 271.6ms
Speed: 1.0ms preprocess, 271.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqX-0Q_Le4utJmChFUjrHA_270.JPG: 480x640 (no detections), 273.4ms
Speed: 1.0ms preprocess, 273.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqYTY5LiNp6IO0qCLXfw6A_0.JPG: 480x640 (no detections), 274.8ms
Speed: 1.1ms preprocess, 274.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqYTY5LiNp6IO0qCLXfw6A_90.JPG: 480x640 (no detections), 275.2ms
Speed: 1.1ms preprocess, 275.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqYTY5LiNp6IO0qCLXfw6A_180.JPG: 480x640 1 Waste, 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqYTY5LiNp6IO0qCLXfw6A_270.JPG: 480x640 (no detections), 272.4ms
Speed: 1.1ms preprocess, 272.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqbl97CztYP-OA0ABHVFxQ_0.JPG: 480x640 (no detections), 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqbl97CztYP-OA0ABHVFxQ_90.JPG: 480x640 (no detections), 276.4ms
Speed: 1.3ms preprocess, 276.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqbl97CztYP-OA0ABHVFxQ_180.JPG: 480x640 (no detections), 276.2ms
Speed: 1.2ms preprocess, 276.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqbl97CztYP-OA0ABHVFxQ_270.JPG: 480x640 1 Waste, 277.5ms
Speed: 1.0ms preprocess, 277.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqoE-K3FtaF56hAg9TQ1Ww_0.JPG: 480x640 (no detections), 278.1ms
Speed: 1.0ms preprocess, 278.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqoE-K3FtaF56hAg9TQ1Ww_90.JPG: 480x640 (no detections), 282.9ms
Speed: 1.1ms preprocess, 282.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqoE-K3FtaF56hAg9TQ1Ww_180.JPG: 480x640 (no detections), 279.2ms
Speed: 1.2ms preprocess, 279.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqoE-K3FtaF56hAg9TQ1Ww_270.JPG: 480x640 (no detections), 270.9ms
Speed: 1.1ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqp4XJB_qdqRJQigwo037A_0.JPG: 480x640 (no detections), 283.5ms
Speed: 1.1ms preprocess, 283.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqp4XJB_qdqRJQigwo037A_90.JPG: 480x640 (no detections), 273.4ms
Speed: 1.0ms preprocess, 273.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqp4XJB_qdqRJQigwo037A_180.JPG: 480x640 (no detections), 290.0ms
Speed: 1.0ms preprocess, 290.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqp4XJB_qdqRJQigwo037A_270.JPG: 480x640 (no detections), 287.1ms
Speed: 1.2ms preprocess, 287.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqtyP1KBerKIEu1uUG-99Q_0.JPG: 480x640 (no detections), 277.5ms
Speed: 1.0ms preprocess, 277.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqtyP1KBerKIEu1uUG-99Q_90.JPG: 480x640 (no detections), 284.0ms
Speed: 1.4ms preprocess, 284.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqtyP1KBerKIEu1uUG-99Q_180.JPG: 480x640 (no detections), 287.6ms
Speed: 1.1ms preprocess, 287.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqtyP1KBerKIEu1uUG-99Q_270.JPG: 480x640 (no detections), 277.2ms
Speed: 1.1ms preprocess, 277.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqwFsjYfSmymo1UJh-sJqw_0.JPG: 480x640 (no detections), 276.6ms
Speed: 1.0ms preprocess, 276.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqwFsjYfSmymo1UJh-sJqw_90.JPG: 480x640 (no detections), 282.6ms
Speed: 1.1ms preprocess, 282.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqwFsjYfSmymo1UJh-sJqw_180.JPG: 480x640 (no detections), 274.5ms
Speed: 1.2ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Q/yqwFsjYfSmymo1UJh-sJqw_270.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yr4zYL1CIjHMmUBPzGL0GA_0.JPG: 480x640 (no detections), 275.3ms
Speed: 1.0ms preprocess, 275.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yr4zYL1CIjHMmUBPzGL0GA_90.JPG: 480x640 (no detections), 272.4ms
Speed: 1.1ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yr4zYL1CIjHMmUBPzGL0GA_180.JPG: 480x640 (no detections), 273.7ms

Speed: 1.1ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yr4zYL1CIjHMmUBPzGL0GA_270.JPG: 480x640 (no detections), 274.9ms
Speed: 1.0ms preprocess, 274.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yr7-Gfw2PY6_-qjffD73CA_0.JPG: 480x640 (no detections), 264.1ms
Speed: 1.1ms preprocess, 264.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yr7-Gfw2PY6_-qjffD73CA_90.JPG: 480x640 (no detections), 280.8ms
Speed: 1.2ms preprocess, 280.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yr7-Gfw2PY6_-qjffD73CA_180.JPG: 480x640 (no detections), 275.2ms
Speed: 1.1ms preprocess, 275.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yr7-Gfw2PY6_-qjffD73CA_270.JPG: 480x640 (no detections), 272.8ms
Speed: 1.0ms preprocess, 272.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yr8FE-jM620eMQra2iz64A_0.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yr8FE-jM620eMQra2iz64A_90.JPG: 480x640 (no detections), 271.9ms
Speed: 1.0ms preprocess, 271.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yr8FE-jM620eMQra2iz64A_180.JPG: 480x640 (no detections), 285.0ms
Speed: 1.2ms preprocess, 285.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yr8FE-jM620eMQra2iz64A_270.JPG: 480x640 (no detections), 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrAo0hh7ZKpSkXgwL1FmUQ_0.JPG: 480x640 (no detections), 316.5ms
Speed: 1.2ms preprocess, 316.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrAo0hh7ZKpSkXgwL1FmUQ_90.JPG: 480x640 (no detections), 288.6ms
Speed: 1.2ms preprocess, 288.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrAo0hh7ZKpSkXgwL1FmUQ_180.JPG: 480x640 (no detections), 275.3ms
Speed: 1.2ms preprocess, 275.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrAo0hh7ZKpSkXgwL1FmUQ_270.JPG: 480x640 (no detections), 277.2ms
Speed: 1.1ms preprocess, 277.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrBenCkRFJJDmSZ_od652g_0.JPG: 480x640 (no detections), 268.9ms
Speed: 1.1ms preprocess, 268.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrBenCkRFJJDmSZ_od652g_90.JPG: 480x640 (no detections), 275.0ms
Speed: 1.0ms preprocess, 275.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrBenCkRFJJDmSZ_od652g_180.JPG: 480x640 (no detections), 277.0ms
Speed: 1.1ms preprocess, 277.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrBenCkRFJJDmSZ_od652g_270.JPG: 480x640 (no detections), 268.8ms
Speed: 1.1ms preprocess, 268.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrBjXKycDz1VsslbpSL4Uw_0.JPG: 480x640 (no detections), 303.6ms
Speed: 1.1ms preprocess, 303.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrBjXKycDz1VsslbpSL4Uw_90.JPG: 480x640 (no detections), 287.7ms
Speed: 1.2ms preprocess, 287.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrBjXKycDz1VsslbpSL4Uw_180.JPG: 480x640 (no detections), 387.6ms
Speed: 1.0ms preprocess, 387.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrBjXKycDz1VsslbpSL4Uw_270.JPG: 480x640 (no detections), 288.5ms
Speed: 1.2ms preprocess, 288.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrBvqBrpGfzp5iDxjeFJbA_0.JPG: 480x640 (no detections), 295.9ms
Speed: 1.1ms preprocess, 295.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrBvqBrpGfzp5iDxjeFJbA_90.JPG: 480x640 (no detections), 276.3ms
Speed: 1.1ms preprocess, 276.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrBvqBrpGfzp5iDxjeFJbA_180.JPG: 480x640 (no detections), 277.5ms
Speed: 1.1ms preprocess, 277.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrBvqBrpGfzp5iDxjeFJbA_270.JPG: 480x640 (no detections), 275.7ms
Speed: 1.0ms preprocess, 275.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrCWCEH_KNytgAhiI8uoJg_0.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrCWCEH_KNytgAhiI8uoJg_90.JPG: 480x640 (no detections), 292.9ms
Speed: 1.1ms preprocess, 292.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrCWCEH_KNytgAhiI8uoJg_180.JPG: 480x640 (no detections), 287.7ms
Speed: 1.1ms preprocess, 287.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrCWCEH_KNytgAhiI8uoJg_270.JPG: 480x640 (no detections), 286.2ms
Speed: 1.0ms preprocess, 286.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrFtqa7n1eh7xR8xshKcvg_0.JPG: 480x640 (no detections), 316.6ms
Speed: 1.2ms preprocess, 316.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrFtqa7n1eh7xR8xshKcvg_90.JPG: 480x640 (no detections), 275.4ms
Speed: 1.2ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrFtqa7n1eh7xR8xshKcvg_180.JPG: 480x640 (no detections), 321.3ms
Speed: 1.1ms preprocess, 321.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrFtqa7n1eh7xR8xshKcvg_270.JPG: 480x640 (no detections), 315.4ms
Speed: 1.5ms preprocess, 315.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrGezuifjMF0Tu_XuyLbhA_0.JPG: 480x640 (no detections), 302.7ms
Speed: 1.4ms preprocess, 302.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrGezuifjMF0Tu_XuyLbhA_90.JPG: 480x640 (no detections), 278.4ms
Speed: 1.2ms preprocess, 278.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrGezuifjMF0Tu_XuyLbhA_180.JPG: 480x640 (no detections), 277.8ms
Speed: 1.3ms preprocess, 277.8ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrGezuifjMF0Tu_XuyLbhA_270.JPG: 480x640 (no detections), 276.1ms
Speed: 1.1ms preprocess, 276.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrGgboJy8S3Dr4Cfltp2xw_0.JPG: 480x640 (no detections), 279.3ms
Speed: 1.1ms preprocess, 279.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrGgboJy8S3Dr4Cfltp2xw_90.JPG: 480x640 (no detections), 275.2ms
Speed: 1.1ms preprocess, 275.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrGgboJy8S3Dr4Cfltp2xw_180.JPG: 480x640 (no detections), 285.9ms
Speed: 1.2ms preprocess, 285.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrGgboJy8S3Dr4Cfltp2xw_270.JPG: 480x640 (no detections), 290.5ms
Speed: 1.2ms preprocess, 290.5ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrI9D6raZZ2mAXrb5AUzUA_0.JPG: 480x640 (no detections), 279.2ms
Speed: 1.1ms preprocess, 279.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrI9D6raZZ2mAXrb5AUzUA_90.JPG: 480x640 (no detections), 271.1ms
Speed: 1.0ms preprocess, 271.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrI9D6raZZ2mAXrb5AUzUA_180.JPG: 480x640 (no detections), 267.9ms
Speed: 1.1ms preprocess, 267.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrI9D6raZZ2mAXrb5AUzUA_270.JPG: 480x640 (no detections), 272.9ms
Speed: 1.0ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrJ3nss24vrYtZ_REC7P7Q_0.JPG: 480x640 (no detections), 270.3ms
Speed: 1.1ms preprocess, 270.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrJ3nss24vrYtZ_REC7P7Q_90.JPG: 480x640 1 Waste, 273.1ms
Speed: 1.1ms preprocess, 273.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrJ3nss24vrYtZ_REC7P7Q_180.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrJ3nss24vrYtZ_REC7P7Q_270.JPG: 480x640 (no detections), 275.8ms
Speed: 1.1ms preprocess, 275.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrKW6R938loCxoizucjKwg_0.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrKW6R938loCxoizucjKwg_90.JPG: 480x640 (no detections), 268.9ms
Speed: 1.0ms preprocess, 268.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrKW6R938loCxoizucjKwg_180.JPG: 480x640 (no detections), 269.4ms
Speed: 1.0ms preprocess, 269.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrKW6R938loCxoizucjKwg_270.JPG: 480x640 (no detections), 272.3ms
Speed: 1.1ms preprocess, 272.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrSfz5l6pZzCejH2-nQt4w_0.JPG: 480x640 (no detections), 272.1ms
Speed: 1.2ms preprocess, 272.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrSfz5l6pZzCejH2-nQt4w_90.JPG: 480x640 (no detections), 269.4ms
Speed: 1.0ms preprocess, 269.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrSfz5l6pZzCejH2-nQt4w_180.JPG: 480x640 (no detections), 270.1ms
Speed: 1.0ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrSfz5l6pZzCejH2-nQt4w_270.JPG: 480x640 (no detections), 272.8ms
Speed: 1.0ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrW_-Ofsaz1-JZDpt3tWgg_0.JPG: 480x640 (no detections), 271.3ms
Speed: 1.2ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrW_-Ofsaz1-JZDpt3tWgg_90.JPG: 480x640 (no detections), 275.8ms
Speed: 1.1ms preprocess, 275.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrW_-Ofsaz1-JZDpt3tWgg_180.JPG: 480x640 (no detections), 272.4ms
Speed: 1.1ms preprocess, 272.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrW_-Ofsaz1-JZDpt3tWgg_270.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrXTLRS-Hvl5SY2gcxKnbA_0.JPG: 480x640 (no detections), 273.1ms
Speed: 1.1ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrXTLRS-Hvl5SY2gcxKnbA_90.JPG: 480x640 (no detections), 274.5ms
Speed: 1.0ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrXTLRS-Hvl5SY2gcxKnbA_180.JPG: 480x640 (no detections), 268.2ms
Speed: 1.1ms preprocess, 268.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrXTLRS-Hvl5SY2gcxKnbA_270.JPG: 480x640 (no detections), 271.4ms
Speed: 1.0ms preprocess, 271.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrYcQTEFwHjbwt5m4lvGBw_0.JPG: 480x640 (no detections), 276.7ms
Speed: 1.0ms preprocess, 276.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrYcQTEFwHjbwt5m4lvGBw_90.JPG: 480x640 (no detections), 267.7ms

Speed: 1.0ms preprocess, 267.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrYcQTEFwHjbwt5m4lvGBw_180.JPG: 480x640 (no detections), 273.7ms
Speed: 1.0ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrYcQTEFwHjbwt5m4lvGBw_270.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrZXRpOTVfItzMZ6bD_fHw_0.JPG: 480x640 (no detections), 273.9ms
Speed: 1.0ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrZXRpOTVfItzMZ6bD_fHw_90.JPG: 480x640 (no detections), 275.1ms
Speed: 1.0ms preprocess, 275.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrZXRpOTVfItzMZ6bD_fHw_180.JPG: 480x640 (no detections), 283.0ms
Speed: 1.1ms preprocess, 283.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrZXRpOTVfItzMZ6bD_fHw_270.JPG: 480x640 (no detections), 283.2ms
Speed: 1.1ms preprocess, 283.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrae79oyYnjsW5KeyU5B0Q_0.JPG: 480x640 (no detections), 293.8ms
Speed: 1.0ms preprocess, 293.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrae79oyYnjsW5KeyU5B0Q_90.JPG: 480x640 (no detections), 311.0ms
Speed: 1.5ms preprocess, 311.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrae79oyYnjsW5KeyU5B0Q_180.JPG: 480x640 (no detections), 281.4ms
Speed: 1.7ms preprocess, 281.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrae79oyYnjsW5KeyU5B0Q_270.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yre38zMKS459eGGViAfeWA_0.JPG: 480x640 (no detections), 273.2ms
Speed: 1.0ms preprocess, 273.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yre38zMKS459eGGViAfeWA_90.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yre38zMKS459eGGViAfeWA_180.JPG: 480x640 (no detections), 275.5ms
Speed: 1.1ms preprocess, 275.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yre38zMKS459eGGViAfeWA_270.JPG: 480x640 (no detections), 272.0ms
Speed: 1.0ms preprocess, 272.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrh5pRs1ZuK1sVlBRAc8UA_0.JPG: 480x640 (no detections), 269.3ms
Speed: 1.0ms preprocess, 269.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrh5pRs1ZuK1sVlBRAc8UA_90.JPG: 480x640 (no detections), 272.9ms
Speed: 1.2ms preprocess, 272.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrh5pRs1ZuK1sVlBRAc8UA_180.JPG: 480x640 (no detections), 288.0ms
Speed: 1.1ms preprocess, 288.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrh5pRs1ZuK1sVlBRAc8UA_270.JPG: 480x640 (no detections), 278.9ms
Speed: 1.3ms preprocess, 278.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrhYvGZVB_HV9sPqelajOw_0.JPG: 480x640 (no detections), 284.6ms
Speed: 1.2ms preprocess, 284.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrhYvGZVB_HV9sPqelajOw_90.JPG: 480x640 (no detections), 297.0ms
Speed: 1.4ms preprocess, 297.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrhYvGZVB_HV9sPqelajOw_180.JPG: 480x640 (no detections), 282.1ms
Speed: 1.2ms preprocess, 282.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrhYvGZVB_HV9sPqelajOw_270.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrj1sHT05BT1KhY64KZRGQ_0.JPG: 480x640 (no detections), 276.3ms
Speed: 1.1ms preprocess, 276.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrj1sHT05BT1KhY64KZRGQ_90.JPG: 480x640 (no detections), 280.2ms
Speed: 1.2ms preprocess, 280.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrj1sHT05BT1KhY64KZRGQ_180.JPG: 480x640 (no detections), 292.5ms
Speed: 1.1ms preprocess, 292.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrj1sHT05BT1KhY64KZRGQ_270.JPG: 480x640 (no detections), 313.7ms
Speed: 1.1ms preprocess, 313.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrlQoZo1QG-lRODxsUEe7g_0.JPG: 480x640 (no detections), 303.9ms
Speed: 1.3ms preprocess, 303.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrlQoZo1QG-lRODxsUEe7g_90.JPG: 480x640 (no detections), 325.0ms
Speed: 1.3ms preprocess, 325.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrlQoZo1QG-lRODxsUEe7g_180.JPG: 480x640 1 Waste, 310.6ms
Speed: 1.1ms preprocess, 310.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrlQoZo1QG-lRODxsUEe7g_270.JPG: 480x640 (no detections), 286.3ms
Speed: 1.3ms preprocess, 286.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yro7zSjdvd4BSFbwtaY--A_0.JPG: 480x640 (no detections), 290.7ms
Speed: 1.2ms preprocess, 290.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yro7zSjdvd4BSFbwtaY--A_90.JPG: 480x640 (no detections), 286.9ms
Speed: 1.0ms preprocess, 286.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yro7zSjdvd4BSFbwtaY--A_180.JPG: 480x640 (no detections), 287.0ms
Speed: 1.0ms preprocess, 287.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yro7zSjdvd4BSFbwtaY--A_270.JPG: 480x640 (no detections), 292.1ms
Speed: 1.0ms preprocess, 292.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrpAEFw7VobDpwxH3Y6QLA_0.JPG: 480x640 (no detections), 281.9ms
Speed: 1.3ms preprocess, 281.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrpAEFw7VobDpwxH3Y6QLA_90.JPG: 480x640 (no detections), 291.1ms
Speed: 1.5ms preprocess, 291.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrpAEFw7VobDpwxH3Y6QLA_180.JPG: 480x640 (no detections), 292.5ms
Speed: 1.3ms preprocess, 292.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrpAEFw7VobDpwxH3Y6QLA_270.JPG: 480x640 (no detections), 283.2ms
Speed: 1.1ms preprocess, 283.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrq3b61y_6BCYJnTwE-2pg_0.JPG: 480x640 (no detections), 284.7ms
Speed: 1.2ms preprocess, 284.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrq3b61y_6BCYJnTwE-2pg_90.JPG: 480x640 (no detections), 272.5ms
Speed: 1.2ms preprocess, 272.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrq3b61y_6BCYJnTwE-2pg_180.JPG: 480x640 (no detections), 292.2ms
Speed: 1.1ms preprocess, 292.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrq3b61y_6BCYJnTwE-2pg_270.JPG: 480x640 (no detections), 335.2ms
Speed: 1.3ms preprocess, 335.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrsRBbX6bMh-h_k02XYe5w_0.JPG: 480x640 (no detections), 311.8ms
Speed: 1.3ms preprocess, 311.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrsRBbX6bMh-h_k02XYe5w_90.JPG: 480x640 (no detections), 320.4ms
Speed: 1.4ms preprocess, 320.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrsRBbX6bMh-h_k02XYe5w_180.JPG: 480x640 (no detections), 293.8ms
Speed: 1.2ms preprocess, 293.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrsRBbX6bMh-h_k02XYe5w_270.JPG: 480x640 (no detections), 301.5ms
Speed: 1.1ms preprocess, 301.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrtiy0MSWM0y8kOg9HqjqQ_0.JPG: 480x640 (no detections), 345.3ms
Speed: 1.2ms preprocess, 345.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrtiy0MSWM0y8kOg9HqjqQ_90.JPG: 480x640 (no detections), 294.2ms
Speed: 1.9ms preprocess, 294.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrtiy0MSWM0y8kOg9HqjqQ_180.JPG: 480x640 (no detections), 287.1ms
Speed: 1.2ms preprocess, 287.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrtiy0MSWM0y8kOg9HqjqQ_270.JPG: 480x640 (no detections), 296.0ms
Speed: 1.3ms preprocess, 296.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrtr_HYC0ZAZuEyfF5Hciw_0.JPG: 480x640 (no detections), 276.9ms
Speed: 1.3ms preprocess, 276.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrtr_HYC0ZAZuEyfF5Hciw_90.JPG: 480x640 (no detections), 272.5ms
Speed: 1.0ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrtr_HYC0ZAZuEyfF5Hciw_180.JPG: 480x640 (no detections), 273.1ms
Speed: 0.9ms preprocess, 273.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrtr_HYC0ZAZuEyfF5Hciw_270.JPG: 480x640 (no detections), 288.2ms
Speed: 1.0ms preprocess, 288.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yru-LQm3Cmm433_zA0MSkg_0.JPG: 480x640 (no detections), 274.5ms
Speed: 1.3ms preprocess, 274.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yru-LQm3Cmm433_zA0MSkg_90.JPG: 480x640 (no detections), 284.5ms
Speed: 1.1ms preprocess, 284.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yru-LQm3Cmm433_zA0MSkg_180.JPG: 480x640 (no detections), 276.3ms
Speed: 1.3ms preprocess, 276.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yru-LQm3Cmm433_zA0MSkg_270.JPG: 480x640 (no detections), 275.0ms
Speed: 1.0ms preprocess, 275.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yru-SnTHtN81wHJRbG8h8g_0.JPG: 480x640 (no detections), 270.9ms
Speed: 1.3ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yru-SnTHtN81wHJRbG8h8g_90.JPG: 480x640 (no detections), 277.3ms
Speed: 1.1ms preprocess, 277.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yru-SnTHtN81wHJRbG8h8g_180.JPG: 480x640 (no detections), 274.6ms
Speed: 1.2ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yru-SnTHtN81wHJRbG8h8g_270.JPG: 480x640 (no detections), 278.8ms
Speed: 1.1ms preprocess, 278.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrvBSRklye4Zr6QOqhxRgQ_0.JPG: 480x640 (no detections), 273.9ms
Speed: 1.0ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrvBSRklye4Zr6QOqhxRgQ_90.JPG: 480x640 1 Waste, 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrvBSRklye4Zr6QOqhxRgQ_180.JPG: 480x640 2 Wastes, 273.4ms
Speed: 1.0ms preprocess, 273.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrvBSRklye4Zr6QOqhxRgQ_270.JPG: 480x640 (no detections), 277.7ms
Speed: 1.0ms preprocess, 277.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrw4azLMvIsKsSinmVWI_w_0.JPG: 480x640 (no detections), 275.3ms

Speed: 1.0ms preprocess, 275.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrw4azLMvIsKsSinmVWI_w_90.JPG: 480x640 (no detections), 275.4ms
Speed: 1.0ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrw4azLMvIsKsSinmVWI_w_180.JPG: 480x640 (no detections), 287.2ms
Speed: 1.0ms preprocess, 287.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrw4azLMvIsKsSinmVWI_w_270.JPG: 480x640 (no detections), 279.9ms
Speed: 1.0ms preprocess, 279.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrx1tEoIuYbe6zadmdWTyw_0.JPG: 480x640 (no detections), 293.4ms
Speed: 1.2ms preprocess, 293.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrx1tEoIuYbe6zadmdWTyw_90.JPG: 480x640 (no detections), 271.7ms
Speed: 1.2ms preprocess, 271.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrx1tEoIuYbe6zadmdWTyw_180.JPG: 480x640 (no detections), 279.4ms
Speed: 1.0ms preprocess, 279.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrx1tEoIuYbe6zadmdWTyw_270.JPG: 480x640 (no detections), 274.3ms
Speed: 1.0ms preprocess, 274.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrxjFStIWTRmwYI3UFUoNQ_0.JPG: 480x640 (no detections), 279.7ms
Speed: 1.1ms preprocess, 279.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrxjFStIWTRmwYI3UFUoNQ_90.JPG: 480x640 (no detections), 280.0ms
Speed: 1.3ms preprocess, 280.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrxjFStIWTRmwYI3UFUoNQ_180.JPG: 480x640 (no detections), 275.6ms
Speed: 1.4ms preprocess, 275.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrxjFStIWTRmwYI3UFUoNQ_270.JPG: 480x640 (no detections), 305.8ms
Speed: 1.1ms preprocess, 305.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yryAQoTqJPTNfspk9DbcvQ_0.JPG: 480x640 (no detections), 280.0ms
Speed: 1.1ms preprocess, 280.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yryAQoTqJPTNfspk9DbcvQ_90.JPG: 480x640 (no detections), 275.6ms
Speed: 1.0ms preprocess, 275.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yryAQoTqJPTNfspk9DbcvQ_180.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yryAQoTqJPTNfspk9DbcvQ_270.JPG: 480x640 (no detections), 285.4ms
Speed: 1.5ms preprocess, 285.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yryfKFuy80bMweADu7-DxQ_0.JPG: 480x640 (no detections), 274.7ms
Speed: 1.3ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yryfKFuy80bMweADu7-DxQ_90.JPG: 480x640 (no detections), 275.4ms
Speed: 1.1ms preprocess, 275.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yryfKFuy80bMweADu7-DxQ_180.JPG: 480x640 (no detections), 273.4ms
Speed: 1.0ms preprocess, 273.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yryfKFuy80bMweADu7-DxQ_270.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrzid-DX0oG0smHYUwfHgQ_0.JPG: 480x640 (no detections), 274.5ms
Speed: 1.1ms preprocess, 274.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrzid-DX0oG0smHYUwfHgQ_90.JPG: 480x640 (no detections), 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrzid-DX0oG0smHYUwfHgQ_180.JPG: 480x640 (no detections), 285.7ms
Speed: 1.1ms preprocess, 285.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/r/yrzid-DX0oG0smHYUwfHgQ_270.JPG: 480x640 (no detections), 291.0ms
Speed: 1.4ms preprocess, 291.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ys142ZYfL_rDVOQbXwIxaQ_0.JPG: 480x640 (no detections), 292.0ms
Speed: 1.1ms preprocess, 292.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ys142ZYfL_rDVOQbXwIxaQ_90.JPG: 480x640 (no detections), 278.7ms
Speed: 1.2ms preprocess, 278.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ys142ZYfL_rDVOQbXwIxaQ_180.JPG: 480x640 (no detections), 281.7ms
Speed: 1.3ms preprocess, 281.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ys142ZYfL_rDVOQbXwIxaQ_270.JPG: 480x640 (no detections), 284.4ms
Speed: 1.3ms preprocess, 284.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ys2DL9qhZgi3EhCxDZUR7A_0.JPG: 480x640 (no detections), 277.4ms
Speed: 1.0ms preprocess, 277.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ys2DL9qhZgi3EhCxDZUR7A_90.JPG: 480x640 (no detections), 281.6ms
Speed: 1.1ms preprocess, 281.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ys2DL9qhZgi3EhCxDZUR7A_180.JPG: 480x640 (no detections), 278.8ms
Speed: 1.2ms preprocess, 278.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ys2DL9qhZgi3EhCxDZUR7A_270.JPG: 480x640 (no detections), 268.9ms
Speed: 1.1ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ys5SjAVsZvTu44zhvlXY-A_0.JPG: 480x640 (no detections), 274.4ms
Speed: 1.1ms preprocess, 274.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ys5SjAVsZvTu44zhvlXY-A_90.JPG: 480x640 (no detections), 274.7ms
Speed: 1.1ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ys5SjAVsZvTu44zhvlXY-A_180.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ys5SjAVsZvTu44zhvlXY-A_270.JPG: 480x640 (no detections), 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ys9bYVaUesOzl8R6S8-qlw_0.JPG: 480x640 (no detections), 291.7ms
Speed: 1.1ms preprocess, 291.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ys9bYVaUesOzl8R6S8-qlw_90.JPG: 480x640 (no detections), 278.9ms
Speed: 1.1ms preprocess, 278.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ys9bYVaUesOzl8R6S8-qlw_180.JPG: 480x640 (no detections), 275.3ms
Speed: 1.1ms preprocess, 275.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ys9bYVaUesOzl8R6S8-qlw_270.JPG: 480x640 (no detections), 293.8ms
Speed: 1.1ms preprocess, 293.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysB7wkb_Pgm61DJ0BMnh_A_0.JPG: 480x640 (no detections), 286.6ms
Speed: 1.1ms preprocess, 286.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysB7wkb_Pgm61DJ0BMnh_A_90.JPG: 480x640 (no detections), 272.2ms
Speed: 1.3ms preprocess, 272.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysB7wkb_Pgm61DJ0BMnh_A_180.JPG: 480x640 (no detections), 277.2ms
Speed: 1.4ms preprocess, 277.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysB7wkb_Pgm61DJ0BMnh_A_270.JPG: 480x640 (no detections), 270.4ms
Speed: 1.1ms preprocess, 270.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysCw4_8w7k52HFNuOoOcFA_0.JPG: 480x640 (no detections), 278.3ms
Speed: 1.0ms preprocess, 278.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysCw4_8w7k52HFNuOoOcFA_90.JPG: 480x640 (no detections), 272.5ms
Speed: 1.0ms preprocess, 272.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysCw4_8w7k52HFNuOoOcFA_180.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysCw4_8w7k52HFNuOoOcFA_270.JPG: 480x640 (no detections), 274.9ms
Speed: 1.2ms preprocess, 274.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysEzFwn4aBVezE6d2OWzHg_0.JPG: 480x640 (no detections), 275.0ms
Speed: 1.0ms preprocess, 275.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysEzFwn4aBVezE6d2OWzHg_90.JPG: 480x640 (no detections), 275.4ms
Speed: 1.4ms preprocess, 275.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysEzFwn4aBVezE6d2OWzHg_180.JPG: 480x640 1 Waste, 277.0ms
Speed: 1.0ms preprocess, 277.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysEzFwn4aBVezE6d2OWzHg_270.JPG: 480x640 (no detections), 275.7ms
Speed: 1.0ms preprocess, 275.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysHUoXOUKWHe3MbRhzg-oA_0.JPG: 480x640 (no detections), 271.9ms
Speed: 1.2ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysHUoXOUKWHe3MbRhzg-oA_90.JPG: 480x640 (no detections), 275.0ms
Speed: 1.0ms preprocess, 275.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysHUoXOUKWHe3MbRhzg-oA_180.JPG: 480x640 (no detections), 274.7ms
Speed: 1.1ms preprocess, 274.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysHUoXOUKWHe3MbRhzg-oA_270.JPG: 480x640 (no detections), 271.0ms
Speed: 1.0ms preprocess, 271.0ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysMzdYVbYC9n7b1H15IQ9A_0.JPG: 480x640 (no detections), 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysMzdYVbYC9n7b1H15IQ9A_90.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysMzdYVbYC9n7b1H15IQ9A_180.JPG: 480x640 (no detections), 273.9ms
Speed: 1.1ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysMzdYVbYC9n7b1H15IQ9A_270.JPG: 480x640 (no detections), 272.4ms
Speed: 1.0ms preprocess, 272.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysNvgSIZ7kfOW_Ixuea2lA_0.JPG: 480x640 (no detections), 273.4ms
Speed: 1.2ms preprocess, 273.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysNvgSIZ7kfOW_Ixuea2lA_90.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysNvgSIZ7kfOW_Ixuea2lA_180.JPG: 480x640 (no detections), 272.1ms
Speed: 1.1ms preprocess, 272.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysNvgSIZ7kfOW_Ixuea2lA_270.JPG: 480x640 (no detections), 274.0ms
Speed: 1.1ms preprocess, 274.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysOqJFaf6iRrGBWTY9z_Gg_0.JPG: 480x640 (no detections), 270.8ms
Speed: 1.0ms preprocess, 270.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysOqJFaf6iRrGBWTY9z_Gg_90.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysOqJFaf6iRrGBWTY9z_Gg_180.JPG: 480x640 (no detections), 282.9ms
Speed: 1.0ms preprocess, 282.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysOqJFaf6iRrGBWTY9z_Gg_270.JPG: 480x640 (no detections), 264.0ms

Speed: 1.1ms preprocess, 264.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysQtWQ1wJQd6lVURzgcvRg_0.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysQtWQ1wJQd6lVURzgcvRg_90.JPG: 480x640 (no detections), 265.4ms
Speed: 1.2ms preprocess, 265.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysQtWQ1wJQd6lVURzgcvRg_180.JPG: 480x640 (no detections), 264.1ms
Speed: 1.1ms preprocess, 264.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysQtWQ1wJQd6lVURzgcvRg_270.JPG: 480x640 (no detections), 267.8ms
Speed: 1.0ms preprocess, 267.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysUiQkyI91NW5ACsgoa3PA_0.JPG: 480x640 (no detections), 275.8ms
Speed: 1.4ms preprocess, 275.8ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysUiQkyI91NW5ACsgoa3PA_90.JPG: 480x640 (no detections), 277.7ms
Speed: 1.1ms preprocess, 277.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysUiQkyI91NW5ACsgoa3PA_180.JPG: 480x640 (no detections), 276.3ms
Speed: 1.0ms preprocess, 276.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysUiQkyI91NW5ACsgoa3PA_270.JPG: 480x640 (no detections), 268.1ms
Speed: 1.0ms preprocess, 268.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysVh9xc0KUcf47Vf3yS6gA_0.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysVh9xc0KUcf47Vf3yS6gA_90.JPG: 480x640 1 Waste, 273.6ms
Speed: 1.1ms preprocess, 273.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysVh9xc0KUcf47Vf3yS6gA_180.JPG: 480x640 (no detections), 281.3ms
Speed: 1.0ms preprocess, 281.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysVh9xc0KUcf47Vf3yS6gA_270.JPG: 480x640 (no detections), 275.0ms
Speed: 1.0ms preprocess, 275.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysZOKoOyStx0ew_ZiymxIQ_0.JPG: 480x640 (no detections), 277.9ms
Speed: 1.1ms preprocess, 277.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysZOKoOyStx0ew_ZiymxIQ_90.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysZOKoOyStx0ew_ZiymxIQ_180.JPG: 480x640 (no detections), 269.6ms
Speed: 1.0ms preprocess, 269.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysZOKoOyStx0ew_ZiymxIQ_270.JPG: 480x640 (no detections), 273.4ms
Speed: 1.1ms preprocess, 273.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysZvko3nO0qJ1La3fuO9OQ_0.JPG: 480x640 1 Waste, 277.7ms
Speed: 1.2ms preprocess, 277.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysZvko3nO0qJ1La3fuO9OQ_90.JPG: 480x640 (no detections), 274.2ms
Speed: 1.2ms preprocess, 274.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysZvko3nO0qJ1La3fuO9OQ_180.JPG: 480x640 (no detections), 277.7ms
Speed: 1.0ms preprocess, 277.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysZvko3nO0qJ1La3fuO9OQ_270.JPG: 480x640 (no detections), 272.6ms
Speed: 1.2ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/yscVbyYPos9pH3CptO-_DA_0.JPG: 480x640 (no detections), 275.3ms
Speed: 1.1ms preprocess, 275.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/yscVbyYPos9pH3CptO-_DA_90.JPG: 480x640 (no detections), 274.9ms
Speed: 1.1ms preprocess, 274.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/yscVbyYPos9pH3CptO-_DA_180.JPG: 480x640 1 Waste, 274.2ms
Speed: 1.3ms preprocess, 274.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/yscVbyYPos9pH3CptO-_DA_270.JPG: 480x640 (no detections), 274.0ms
Speed: 1.1ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/yscsXU5fiQW90aqHAx6TYg_0.JPG: 480x640 (no detections), 274.5ms
Speed: 1.0ms preprocess, 274.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/yscsXU5fiQW90aqHAx6TYg_90.JPG: 480x640 (no detections), 283.1ms
Speed: 1.7ms preprocess, 283.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/yscsXU5fiQW90aqHAx6TYg_180.JPG: 480x640 (no detections), 270.9ms
Speed: 1.1ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/yscsXU5fiQW90aqHAx6TYg_270.JPG: 480x640 (no detections), 273.7ms
Speed: 1.0ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysixdW_9vPXwgqVenT46CQ_0.JPG: 480x640 (no detections), 275.5ms
Speed: 1.0ms preprocess, 275.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysixdW_9vPXwgqVenT46CQ_90.JPG: 480x640 (no detections), 272.9ms
Speed: 1.0ms preprocess, 272.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysixdW_9vPXwgqVenT46CQ_180.JPG: 480x640 (no detections), 275.6ms
Speed: 1.2ms preprocess, 275.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysixdW_9vPXwgqVenT46CQ_270.JPG: 480x640 (no detections), 273.3ms
Speed: 1.2ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysjJXbAuxhROwD_8hePIAA_0.JPG: 480x640 (no detections), 273.4ms
Speed: 1.1ms preprocess, 273.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysjJXbAuxhROwD_8hePIAA_90.JPG: 480x640 (no detections), 272.3ms
Speed: 1.1ms preprocess, 272.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysjJXbAuxhROwD_8hePIAA_180.JPG: 480x640 (no detections), 278.0ms
Speed: 1.3ms preprocess, 278.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysjJXbAuxhROwD_8hePIAA_270.JPG: 480x640 (no detections), 272.7ms
Speed: 1.3ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysjm7uBRV2TtUGWlMNIEZQ_0.JPG: 480x640 (no detections), 269.1ms
Speed: 1.0ms preprocess, 269.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysjm7uBRV2TtUGWlMNIEZQ_90.JPG: 480x640 (no detections), 269.2ms
Speed: 1.0ms preprocess, 269.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysjm7uBRV2TtUGWlMNIEZQ_180.JPG: 480x640 (no detections), 270.6ms
Speed: 1.0ms preprocess, 270.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysjm7uBRV2TtUGWlMNIEZQ_270.JPG: 480x640 (no detections), 270.4ms
Speed: 1.0ms preprocess, 270.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysv95CZPcigVGs5-FGPpvw_0.JPG: 480x640 (no detections), 275.7ms
Speed: 1.0ms preprocess, 275.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysv95CZPcigVGs5-FGPpvw_90.JPG: 480x640 (no detections), 289.2ms
Speed: 1.1ms preprocess, 289.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysv95CZPcigVGs5-FGPpvw_180.JPG: 480x640 (no detections), 276.5ms
Speed: 1.2ms preprocess, 276.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysv95CZPcigVGs5-FGPpvw_270.JPG: 480x640 (no detections), 276.1ms
Speed: 1.3ms preprocess, 276.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysxEoqS2p4DnAo2hKfTrXA_0.JPG: 480x640 (no detections), 269.3ms
Speed: 1.1ms preprocess, 269.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysxEoqS2p4DnAo2hKfTrXA_90.JPG: 480x640 (no detections), 274.3ms
Speed: 1.1ms preprocess, 274.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysxEoqS2p4DnAo2hKfTrXA_180.JPG: 480x640 (no detections), 269.2ms
Speed: 1.1ms preprocess, 269.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/s/ysxEoqS2p4DnAo2hKfTrXA_270.JPG: 480x640 (no detections), 274.3ms
Speed: 1.0ms preprocess, 274.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yt3ETzQCI0djKfKKt2kDfg_0.JPG: 480x640 (no detections), 272.6ms
Speed: 1.0ms preprocess, 272.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yt3ETzQCI0djKfKKt2kDfg_90.JPG: 480x640 (no detections), 272.3ms
Speed: 1.0ms preprocess, 272.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yt3ETzQCI0djKfKKt2kDfg_180.JPG: 480x640 (no detections), 277.0ms
Speed: 1.2ms preprocess, 277.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yt3ETzQCI0djKfKKt2kDfg_270.JPG: 480x640 (no detections), 277.7ms
Speed: 1.1ms preprocess, 277.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yt3jTXZ08bzbMgYFMyxHFA_0.JPG: 480x640 (no detections), 277.4ms
Speed: 1.1ms preprocess, 277.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yt3jTXZ08bzbMgYFMyxHFA_90.JPG: 480x640 (no detections), 273.6ms
Speed: 1.2ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yt3jTXZ08bzbMgYFMyxHFA_180.JPG: 480x640 (no detections), 273.8ms
Speed: 1.0ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yt3jTXZ08bzbMgYFMyxHFA_270.JPG: 480x640 (no detections), 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yt8840-VuD0glKDseqgnNw_0.JPG: 480x640 (no detections), 270.8ms
Speed: 1.2ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yt8840-VuD0glKDseqgnNw_90.JPG: 480x640 (no detections), 270.5ms
Speed: 1.0ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yt8840-VuD0glKDseqgnNw_180.JPG: 480x640 (no detections), 273.7ms
Speed: 1.0ms preprocess, 273.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yt8840-VuD0glKDseqgnNw_270.JPG: 480x640 (no detections), 268.1ms
Speed: 1.0ms preprocess, 268.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yt8GEzrE3Fbe5XX3xGCZSw_0.JPG: 480x640 (no detections), 271.2ms
Speed: 1.0ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yt8GEzrE3Fbe5XX3xGCZSw_90.JPG: 480x640 (no detections), 272.6ms
Speed: 1.0ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yt8GEzrE3Fbe5XX3xGCZSw_180.JPG: 480x640 (no detections), 274.6ms
Speed: 1.2ms preprocess, 274.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yt8GEzrE3Fbe5XX3xGCZSw_270.JPG: 480x640 (no detections), 281.3ms
Speed: 1.2ms preprocess, 281.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yt8MGEk37-KdSO3zf27gWg_0.JPG: 480x640 (no detections), 279.2ms
Speed: 1.2ms preprocess, 279.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yt8MGEk37-KdSO3zf27gWg_90.JPG: 480x640 (no detections), 272.9ms
Speed: 1.0ms preprocess, 272.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yt8MGEk37-KdSO3zf27gWg_180.JPG: 480x640 (no detections), 275.9ms

Speed: 1.1ms preprocess, 275.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yt8MGEk37-KdSO3zf27gWg_270.JPG: 480x640 (no detections), 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytAK2X-6TEa-voKQsbHHjg_0.JPG: 480x640 (no detections), 274.8ms
Speed: 1.3ms preprocess, 274.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytAK2X-6TEa-voKQsbHHjg_90.JPG: 480x640 (no detections), 274.7ms
Speed: 1.1ms preprocess, 274.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytAK2X-6TEa-voKQsbHHjg_180.JPG: 480x640 (no detections), 275.6ms
Speed: 1.3ms preprocess, 275.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytAK2X-6TEa-voKQsbHHjg_270.JPG: 480x640 (no detections), 271.5ms
Speed: 1.1ms preprocess, 271.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytCkCX2C54zIbwHQaoNkfA_0.JPG: 480x640 (no detections), 273.9ms
Speed: 1.1ms preprocess, 273.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytCkCX2C54zIbwHQaoNkfA_90.JPG: 480x640 (no detections), 272.8ms
Speed: 1.0ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytCkCX2C54zIbwHQaoNkfA_180.JPG: 480x640 (no detections), 268.8ms
Speed: 1.1ms preprocess, 268.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytCkCX2C54zIbwHQaoNkfA_270.JPG: 480x640 (no detections), 272.1ms
Speed: 1.0ms preprocess, 272.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytK2qvvN8dTTQYpLbTJ3Dw_0.JPG: 480x640 (no detections), 274.6ms
Speed: 1.1ms preprocess, 274.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytK2qvvN8dTTQYpLbTJ3Dw_90.JPG: 480x640 (no detections), 277.5ms
Speed: 1.0ms preprocess, 277.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytK2qvvN8dTTQYpLbTJ3Dw_180.JPG: 480x640 1 Waste, 274.2ms
Speed: 1.1ms preprocess, 274.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytK2qvvN8dTTQYpLbTJ3Dw_270.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytMMQRVhIrnaYy2pQpPFHA_0.JPG: 480x640 (no detections), 267.3ms
Speed: 1.0ms preprocess, 267.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytMMQRVhIrnaYy2pQpPFHA_90.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytMMQRVhIrnaYy2pQpPFHA_180.JPG: 480x640 (no detections), 272.3ms
Speed: 1.1ms preprocess, 272.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytMMQRVhIrnaYy2pQpPFHA_270.JPG: 480x640 (no detections), 278.1ms
Speed: 1.0ms preprocess, 278.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytQ4-Zl4I2EVevDjwln5UA_0.JPG: 480x640 (no detections), 274.6ms
Speed: 1.1ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytQ4-Zl4I2EVevDjwln5UA_90.JPG: 480x640 (no detections), 271.8ms
Speed: 1.0ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytQ4-Zl4I2EVevDjwln5UA_180.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytQ4-Zl4I2EVevDjwln5UA_270.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytRDyDRpgYWrztnmZYnZKA_0.JPG: 480x640 (no detections), 273.2ms
Speed: 1.0ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytRDyDRpgYWrztnmZYnZKA_90.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytRDyDRpgYWrztnmZYnZKA_180.JPG: 480x640 (no detections), 272.5ms
Speed: 1.1ms preprocess, 272.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytRDyDRpgYWrztnmZYnZKA_270.JPG: 480x640 (no detections), 276.0ms
Speed: 1.2ms preprocess, 276.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytT-ss4YY_7wLHoJx0YgvA_0.JPG: 480x640 (no detections), 278.3ms
Speed: 1.0ms preprocess, 278.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytT-ss4YY_7wLHoJx0YgvA_90.JPG: 480x640 (no detections), 273.6ms
Speed: 1.0ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytT-ss4YY_7wLHoJx0YgvA_180.JPG: 480x640 (no detections), 289.2ms
Speed: 1.1ms preprocess, 289.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytT-ss4YY_7wLHoJx0YgvA_270.JPG: 480x640 (no detections), 278.2ms
Speed: 1.0ms preprocess, 278.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytTKgrIEB1z0hPuiPpOd-A_0.JPG: 480x640 (no detections), 274.6ms
Speed: 1.0ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytTKgrIEB1z0hPuiPpOd-A_90.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytTKgrIEB1z0hPuiPpOd-A_180.JPG: 480x640 (no detections), 273.1ms
Speed: 1.1ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytTKgrIEB1z0hPuiPpOd-A_270.JPG: 480x640 (no detections), 271.1ms
Speed: 1.0ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytVFvWDVS8om-hhBdfVCiw_0.JPG: 480x640 (no detections), 274.4ms
Speed: 1.1ms preprocess, 274.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytVFvWDVS8om-hhBdfVCiw_90.JPG: 480x640 (no detections), 272.0ms
Speed: 1.0ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytVFvWDVS8om-hhBdfVCiw_180.JPG: 480x640 2 Wastes, 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytVFvWDVS8om-hhBdfVCiw_270.JPG: 480x640 (no detections), 273.5ms
Speed: 1.0ms preprocess, 273.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytWV-P8XmYcEKg9ZejEGbQ_0.JPG: 480x640 (no detections), 282.7ms
Speed: 1.0ms preprocess, 282.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytWV-P8XmYcEKg9ZejEGbQ_90.JPG: 480x640 (no detections), 280.9ms
Speed: 1.0ms preprocess, 280.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytWV-P8XmYcEKg9ZejEGbQ_180.JPG: 480x640 (no detections), 280.8ms
Speed: 2.2ms preprocess, 280.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytWV-P8XmYcEKg9ZejEGbQ_270.JPG: 480x640 (no detections), 273.7ms
Speed: 1.2ms preprocess, 273.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytX523JKQ_xv407zsBp3hw_0.JPG: 480x640 (no detections), 271.9ms
Speed: 1.0ms preprocess, 271.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytX523JKQ_xv407zsBp3hw_90.JPG: 480x640 (no detections), 268.9ms
Speed: 0.9ms preprocess, 268.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytX523JKQ_xv407zsBp3hw_180.JPG: 480x640 (no detections), 281.5ms
Speed: 1.4ms preprocess, 281.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytX523JKQ_xv407zsBp3hw_270.JPG: 480x640 (no detections), 274.0ms
Speed: 1.1ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytXQym02oMlBmAUElcLMRw_0.JPG: 480x640 1 Waste, 273.7ms
Speed: 1.0ms preprocess, 273.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytXQym02oMlBmAUElcLMRw_90.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytXQym02oMlBmAUElcLMRw_180.JPG: 480x640 (no detections), 277.4ms
Speed: 1.1ms preprocess, 277.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytXQym02oMlBmAUElcLMRw_270.JPG: 480x640 (no detections), 272.2ms
Speed: 1.2ms preprocess, 272.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytZxCSMY51QGy-wL8OFgZg_0.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytZxCSMY51QGy-wL8OFgZg_90.JPG: 480x640 (no detections), 275.8ms
Speed: 1.0ms preprocess, 275.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytZxCSMY51QGy-wL8OFgZg_180.JPG: 480x640 (no detections), 270.7ms
Speed: 1.0ms preprocess, 270.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytZxCSMY51QGy-wL8OFgZg_270.JPG: 480x640 (no detections), 269.8ms
Speed: 1.1ms preprocess, 269.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yt_YP_vzfsb-L0AzHcyeTQ_0.JPG: 480x640 (no detections), 274.3ms
Speed: 1.0ms preprocess, 274.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yt_YP_vzfsb-L0AzHcyeTQ_90.JPG: 480x640 (no detections), 277.0ms
Speed: 1.1ms preprocess, 277.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yt_YP_vzfsb-L0AzHcyeTQ_180.JPG: 480x640 (no detections), 272.5ms
Speed: 1.1ms preprocess, 272.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yt_YP_vzfsb-L0AzHcyeTQ_270.JPG: 480x640 (no detections), 277.8ms
Speed: 1.1ms preprocess, 277.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yta3OV3qPqnlcO2oefnS2Q_0.JPG: 480x640 (no detections), 270.3ms
Speed: 1.0ms preprocess, 270.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yta3OV3qPqnlcO2oefnS2Q_90.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yta3OV3qPqnlcO2oefnS2Q_180.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/yta3OV3qPqnlcO2oefnS2Q_270.JPG: 480x640 (no detections), 272.0ms
Speed: 1.0ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytcS79rS72Ubb_V9Ime0xw_0.JPG: 480x640 (no detections), 274.9ms
Speed: 1.0ms preprocess, 274.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytcS79rS72Ubb_V9Ime0xw_90.JPG: 480x640 (no detections), 269.0ms
Speed: 1.1ms preprocess, 269.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytcS79rS72Ubb_V9Ime0xw_180.JPG: 480x640 (no detections), 276.9ms
Speed: 1.1ms preprocess, 276.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytcS79rS72Ubb_V9Ime0xw_270.JPG: 480x640 (no detections), 277.4ms
Speed: 1.0ms preprocess, 277.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytd4hEbwyhAdOMR2Z3xG6g_0.JPG: 480x640 (no detections), 272.9ms
Speed: 1.0ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytd4hEbwyhAdOMR2Z3xG6g_90.JPG: 480x640 (no detections), 269.1ms

Speed: 1.2ms preprocess, 269.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytd4hEbwyhAdOMR2Z3xG6g_180.JPG: 480x640 2 Wastes, 274.3ms
Speed: 1.0ms preprocess, 274.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytd4hEbwyhAdOMR2Z3xG6g_270.JPG: 480x640 1 Waste, 271.6ms
Speed: 1.0ms preprocess, 271.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytdBok2BpNGgwnL6Szdj3A_0.JPG: 480x640 (no detections), 282.0ms
Speed: 1.4ms preprocess, 282.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytdBok2BpNGgwnL6Szdj3A_90.JPG: 480x640 (no detections), 272.1ms
Speed: 1.1ms preprocess, 272.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytdBok2BpNGgwnL6Szdj3A_180.JPG: 480x640 (no detections), 277.0ms
Speed: 1.2ms preprocess, 277.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytdBok2BpNGgwnL6Szdj3A_270.JPG: 480x640 (no detections), 271.0ms
Speed: 1.1ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytl-05t8Nax4xXVKV3cMRQ_0.JPG: 480x640 (no detections), 274.7ms
Speed: 1.2ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytl-05t8Nax4xXVKV3cMRQ_90.JPG: 480x640 (no detections), 274.4ms
Speed: 1.1ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytl-05t8Nax4xXVKV3cMRQ_180.JPG: 480x640 (no detections), 272.5ms
Speed: 1.1ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytl-05t8Nax4xXVKV3cMRQ_270.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytlgG6PspSknzD9lV69r4g_0.JPG: 480x640 (no detections), 271.9ms
Speed: 1.0ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytlgG6PspSknzD9lV69r4g_90.JPG: 480x640 (no detections), 275.4ms
Speed: 1.0ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytlgG6PspSknzD9lV69r4g_180.JPG: 480x640 (no detections), 276.8ms
Speed: 1.0ms preprocess, 276.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytlgG6PspSknzD9lV69r4g_270.JPG: 480x640 (no detections), 272.5ms
Speed: 1.1ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytrHGD80L9-QpMiQRk5IDA_0.JPG: 480x640 (no detections), 276.8ms
Speed: 1.4ms preprocess, 276.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytrHGD80L9-QpMiQRk5IDA_90.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytrHGD80L9-QpMiQRk5IDA_180.JPG: 480x640 (no detections), 272.2ms
Speed: 1.0ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytrHGD80L9-QpMiQRk5IDA_270.JPG: 480x640 (no detections), 278.4ms
Speed: 1.1ms preprocess, 278.4ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytsLNptXB-uD_DfbEIy8FQ_0.JPG: 480x640 (no detections), 292.7ms
Speed: 1.0ms preprocess, 292.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytsLNptXB-uD_DfbEIy8FQ_90.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytsLNptXB-uD_DfbEIy8FQ_180.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytsLNptXB-uD_DfbEIy8FQ_270.JPG: 480x640 (no detections), 271.3ms
Speed: 1.0ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytv6jEAhSZoJBh4IjhonNQ_0.JPG: 480x640 (no detections), 271.9ms
Speed: 1.0ms preprocess, 271.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytv6jEAhSZoJBh4IjhonNQ_90.JPG: 480x640 (no detections), 274.5ms
Speed: 1.1ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytv6jEAhSZoJBh4IjhonNQ_180.JPG: 480x640 (no detections), 272.7ms
Speed: 1.0ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/t/ytv6jEAhSZoJBh4IjhonNQ_270.JPG: 480x640 (no detections), 270.0ms
Speed: 1.0ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yu-l7X61yfqxpaz-zzdHDg_0.JPG: 480x640 (no detections), 275.1ms
Speed: 1.2ms preprocess, 275.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yu-l7X61yfqxpaz-zzdHDg_90.JPG: 480x640 (no detections), 271.5ms
Speed: 1.1ms preprocess, 271.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yu-l7X61yfqxpaz-zzdHDg_180.JPG: 480x640 1 Waste, 270.8ms
Speed: 1.0ms preprocess, 270.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yu-l7X61yfqxpaz-zzdHDg_270.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yu2jjk7B3NHGiA2JHqm4og_0.JPG: 480x640 (no detections), 272.5ms
Speed: 1.1ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yu2jjk7B3NHGiA2JHqm4og_90.JPG: 480x640 (no detections), 275.8ms
Speed: 1.2ms preprocess, 275.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yu2jjk7B3NHGiA2JHqm4og_180.JPG: 480x640 (no detections), 270.8ms
Speed: 1.0ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yu2jjk7B3NHGiA2JHqm4og_270.JPG: 480x640 (no detections), 269.7ms
Speed: 1.2ms preprocess, 269.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yu3llNmNbSs0gaSWrmdn_A_0.JPG: 480x640 (no detections), 279.1ms
Speed: 1.5ms preprocess, 279.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yu3llNmNbSs0gaSWrmdn_A_90.JPG: 480x640 (no detections), 275.4ms
Speed: 1.1ms preprocess, 275.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yu3llNmNbSs0gaSWrmdn_A_180.JPG: 480x640 (no detections), 272.0ms
Speed: 1.1ms preprocess, 272.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yu3llNmNbSs0gaSWrmdn_A_270.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yu4Sl7NdLoFOB2kzIuiq7g_0.JPG: 480x640 (no detections), 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yu4Sl7NdLoFOB2kzIuiq7g_90.JPG: 480x640 (no detections), 270.8ms
Speed: 1.0ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yu4Sl7NdLoFOB2kzIuiq7g_180.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yu4Sl7NdLoFOB2kzIuiq7g_270.JPG: 480x640 (no detections), 272.9ms
Speed: 1.0ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yu8T2wcylozQkljtaIDtcQ_0.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yu8T2wcylozQkljtaIDtcQ_90.JPG: 480x640 (no detections), 275.0ms
Speed: 1.0ms preprocess, 275.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yu8T2wcylozQkljtaIDtcQ_180.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yu8T2wcylozQkljtaIDtcQ_270.JPG: 480x640 (no detections), 269.1ms
Speed: 1.1ms preprocess, 269.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuAS4uLj2V5BYyr3bxdwnQ_0.JPG: 480x640 (no detections), 268.1ms
Speed: 1.0ms preprocess, 268.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuAS4uLj2V5BYyr3bxdwnQ_90.JPG: 480x640 (no detections), 272.1ms
Speed: 1.1ms preprocess, 272.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuAS4uLj2V5BYyr3bxdwnQ_180.JPG: 480x640 (no detections), 274.6ms
Speed: 1.2ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuAS4uLj2V5BYyr3bxdwnQ_270.JPG: 480x640 (no detections), 272.5ms
Speed: 1.1ms preprocess, 272.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuCextB0oPbnmcnyz3cUEg_0.JPG: 480x640 (no detections), 274.0ms
Speed: 1.1ms preprocess, 274.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuCextB0oPbnmcnyz3cUEg_90.JPG: 480x640 (no detections), 268.3ms
Speed: 1.0ms preprocess, 268.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuCextB0oPbnmcnyz3cUEg_180.JPG: 480x640 (no detections), 272.5ms
Speed: 1.1ms preprocess, 272.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuCextB0oPbnmcnyz3cUEg_270.JPG: 480x640 (no detections), 272.5ms
Speed: 1.0ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuELW4zIgRTTCfTlSKGoww_0.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuELW4zIgRTTCfTlSKGoww_90.JPG: 480x640 1 Waste, 274.0ms
Speed: 1.0ms preprocess, 274.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuELW4zIgRTTCfTlSKGoww_180.JPG: 480x640 (no detections), 269.6ms
Speed: 1.1ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuELW4zIgRTTCfTlSKGoww_270.JPG: 480x640 (no detections), 275.6ms
Speed: 1.1ms preprocess, 275.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuGDB1fIWVtDttvSQX-V_g_0.JPG: 480x640 (no detections), 277.3ms
Speed: 1.0ms preprocess, 277.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuGDB1fIWVtDttvSQX-V_g_90.JPG: 480x640 1 Waste, 270.7ms
Speed: 1.0ms preprocess, 270.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuGDB1fIWVtDttvSQX-V_g_180.JPG: 480x640 (no detections), 277.7ms
Speed: 1.1ms preprocess, 277.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuGDB1fIWVtDttvSQX-V_g_270.JPG: 480x640 (no detections), 271.5ms
Speed: 1.0ms preprocess, 271.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuJkCkVSkEgb_Y-9w4llBQ_0.JPG: 480x640 (no detections), 273.3ms
Speed: 1.0ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuJkCkVSkEgb_Y-9w4llBQ_90.JPG: 480x640 (no detections), 268.8ms
Speed: 1.0ms preprocess, 268.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuJkCkVSkEgb_Y-9w4llBQ_180.JPG: 480x640 (no detections), 273.9ms
Speed: 1.1ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuJkCkVSkEgb_Y-9w4llBQ_270.JPG: 480x640 (no detections), 271.9ms
Speed: 1.0ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuLyqNt31xIq6G_2MbwAIA_0.JPG: 480x640 (no detections), 274.0ms

Speed: 1.1ms preprocess, 274.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuLyqNt31xIq6G_2MbwAIA_90.JPG: 480x640 (no detections), 272.6ms
Speed: 1.0ms preprocess, 272.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuLyqNt31xIq6G_2MbwAIA_180.JPG: 480x640 (no detections), 272.0ms
Speed: 1.0ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuLyqNt31xIq6G_2MbwAIA_270.JPG: 480x640 (no detections), 275.8ms
Speed: 1.1ms preprocess, 275.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuOzG7b6JvVfkdF_4Fd84g_0.JPG: 480x640 (no detections), 271.9ms
Speed: 1.0ms preprocess, 271.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuOzG7b6JvVfkdF_4Fd84g_90.JPG: 480x640 (no detections), 291.2ms
Speed: 1.0ms preprocess, 291.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuOzG7b6JvVfkdF_4Fd84g_180.JPG: 480x640 (no detections), 276.4ms
Speed: 1.2ms preprocess, 276.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuOzG7b6JvVfkdF_4Fd84g_270.JPG: 480x640 (no detections), 274.6ms
Speed: 1.3ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuP7aYDXnSzRh-6RSMe2qg_0.JPG: 480x640 (no detections), 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuP7aYDXnSzRh-6RSMe2qg_90.JPG: 480x640 (no detections), 290.3ms
Speed: 1.1ms preprocess, 290.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuP7aYDXnSzRh-6RSMe2qg_180.JPG: 480x640 (no detections), 288.4ms
Speed: 1.0ms preprocess, 288.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuP7aYDXnSzRh-6RSMe2qg_270.JPG: 480x640 (no detections), 277.3ms
Speed: 1.1ms preprocess, 277.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuQXi2znLx6lrBQhV2L19w_0.JPG: 480x640 (no detections), 276.0ms
Speed: 1.2ms preprocess, 276.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuQXi2znLx6lrBQhV2L19w_90.JPG: 480x640 (no detections), 273.6ms
Speed: 1.1ms preprocess, 273.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuQXi2znLx6lrBQhV2L19w_180.JPG: 480x640 (no detections), 291.1ms
Speed: 1.0ms preprocess, 291.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuQXi2znLx6lrBQhV2L19w_270.JPG: 480x640 (no detections), 279.4ms
Speed: 1.1ms preprocess, 279.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuQdpQOeqncYkmZ07hcAkg_0.JPG: 480x640 (no detections), 271.2ms
Speed: 1.3ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuQdpQOeqncYkmZ07hcAkg_90.JPG: 480x640 (no detections), 284.0ms
Speed: 1.2ms preprocess, 284.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuQdpQOeqncYkmZ07hcAkg_180.JPG: 480x640 (no detections), 274.4ms
Speed: 1.1ms preprocess, 274.4ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuQdpQOeqncYkmZ07hcAkg_270.JPG: 480x640 (no detections), 263.3ms
Speed: 1.2ms preprocess, 263.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuZ45WUPKNEaV3B4BHruGg_0.JPG: 480x640 (no detections), 269.0ms
Speed: 1.2ms preprocess, 269.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuZ45WUPKNEaV3B4BHruGg_90.JPG: 480x640 (no detections), 267.3ms
Speed: 1.1ms preprocess, 267.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuZ45WUPKNEaV3B4BHruGg_180.JPG: 480x640 (no detections), 276.7ms
Speed: 1.1ms preprocess, 276.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuZ45WUPKNEaV3B4BHruGg_270.JPG: 480x640 (no detections), 279.6ms
Speed: 1.2ms preprocess, 279.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuaRroDBJ5U-1Tbrei04Ag_0.JPG: 480x640 (no detections), 277.0ms
Speed: 1.1ms preprocess, 277.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuaRroDBJ5U-1Tbrei04Ag_90.JPG: 480x640 (no detections), 276.0ms
Speed: 1.1ms preprocess, 276.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuaRroDBJ5U-1Tbrei04Ag_180.JPG: 480x640 (no detections), 284.1ms
Speed: 1.0ms preprocess, 284.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuaRroDBJ5U-1Tbrei04Ag_270.JPG: 480x640 (no detections), 286.5ms
Speed: 1.1ms preprocess, 286.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yucVsvv8UmXc46EY5X9ayQ_0.JPG: 480x640 (no detections), 282.4ms
Speed: 1.3ms preprocess, 282.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yucVsvv8UmXc46EY5X9ayQ_90.JPG: 480x640 (no detections), 277.7ms
Speed: 1.0ms preprocess, 277.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yucVsvv8UmXc46EY5X9ayQ_180.JPG: 480x640 (no detections), 276.4ms
Speed: 1.1ms preprocess, 276.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yucVsvv8UmXc46EY5X9ayQ_270.JPG: 480x640 (no detections), 276.1ms
Speed: 1.1ms preprocess, 276.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuclm-2xx0OGIAj7Z_u66g_0.JPG: 480x640 (no detections), 272.4ms
Speed: 1.1ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuclm-2xx0OGIAj7Z_u66g_90.JPG: 480x640 (no detections), 273.4ms
Speed: 1.1ms preprocess, 273.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuclm-2xx0OGIAj7Z_u66g_180.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuclm-2xx0OGIAj7Z_u66g_270.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yudjcrfFJ_XqWm_msEOGXQ_0.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yudjcrfFJ_XqWm_msEOGXQ_90.JPG: 480x640 (no detections), 277.1ms
Speed: 1.0ms preprocess, 277.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yudjcrfFJ_XqWm_msEOGXQ_180.JPG: 480x640 (no detections), 278.0ms
Speed: 1.2ms preprocess, 278.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yudjcrfFJ_XqWm_msEOGXQ_270.JPG: 480x640 1 Waste, 276.5ms
Speed: 1.2ms preprocess, 276.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yudxb9J1qA0ZLgoKY95Zzw_0.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yudxb9J1qA0ZLgoKY95Zzw_90.JPG: 480x640 (no detections), 282.5ms
Speed: 1.2ms preprocess, 282.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yudxb9J1qA0ZLgoKY95Zzw_180.JPG: 480x640 (no detections), 285.2ms
Speed: 1.2ms preprocess, 285.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yudxb9J1qA0ZLgoKY95Zzw_270.JPG: 480x640 (no detections), 278.2ms
Speed: 1.2ms preprocess, 278.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yugrLsQGPOdltDitLTQ8BQ_0.JPG: 480x640 (no detections), 278.1ms
Speed: 1.0ms preprocess, 278.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yugrLsQGPOdltDitLTQ8BQ_90.JPG: 480x640 (no detections), 275.3ms
Speed: 1.1ms preprocess, 275.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yugrLsQGPOdltDitLTQ8BQ_180.JPG: 480x640 (no detections), 268.0ms
Speed: 1.1ms preprocess, 268.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yugrLsQGPOdltDitLTQ8BQ_270.JPG: 480x640 (no detections), 276.6ms
Speed: 1.1ms preprocess, 276.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuhzKrFbWij7g-kxomfmmA_0.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuhzKrFbWij7g-kxomfmmA_90.JPG: 480x640 (no detections), 276.8ms
Speed: 1.1ms preprocess, 276.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuhzKrFbWij7g-kxomfmmA_180.JPG: 480x640 (no detections), 279.2ms
Speed: 1.1ms preprocess, 279.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuhzKrFbWij7g-kxomfmmA_270.JPG: 480x640 (no detections), 274.8ms
Speed: 1.0ms preprocess, 274.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yulhXn7FX2YGtqBwfL5bqA_0.JPG: 480x640 (no detections), 275.3ms
Speed: 1.1ms preprocess, 275.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yulhXn7FX2YGtqBwfL5bqA_90.JPG: 480x640 (no detections), 274.0ms
Speed: 1.1ms preprocess, 274.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yulhXn7FX2YGtqBwfL5bqA_180.JPG: 480x640 (no detections), 274.7ms
Speed: 1.0ms preprocess, 274.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yulhXn7FX2YGtqBwfL5bqA_270.JPG: 480x640 (no detections), 271.9ms
Speed: 1.2ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yumW5AhgEM86eAC4h9_PyA_0.JPG: 480x640 (no detections), 273.6ms
Speed: 1.1ms preprocess, 273.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yumW5AhgEM86eAC4h9_PyA_90.JPG: 480x640 (no detections), 276.6ms
Speed: 1.1ms preprocess, 276.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yumW5AhgEM86eAC4h9_PyA_180.JPG: 480x640 (no detections), 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yumW5AhgEM86eAC4h9_PyA_270.JPG: 480x640 (no detections), 276.7ms
Speed: 1.0ms preprocess, 276.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuoAyNVU3vaR-MX5Q4-lWw_0.JPG: 480x640 (no detections), 273.6ms
Speed: 1.2ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuoAyNVU3vaR-MX5Q4-lWw_90.JPG: 480x640 (no detections), 277.2ms
Speed: 1.1ms preprocess, 277.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuoAyNVU3vaR-MX5Q4-lWw_180.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuoAyNVU3vaR-MX5Q4-lWw_270.JPG: 480x640 (no detections), 277.8ms
Speed: 1.1ms preprocess, 277.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuouVL-PW6yfQ9YC5RHJ6w_0.JPG: 480x640 (no detections), 277.1ms
Speed: 1.2ms preprocess, 277.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuouVL-PW6yfQ9YC5RHJ6w_90.JPG: 480x640 (no detections), 277.0ms
Speed: 1.2ms preprocess, 277.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuouVL-PW6yfQ9YC5RHJ6w_180.JPG: 480x640 (no detections), 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuouVL-PW6yfQ9YC5RHJ6w_270.JPG: 480x640 (no detections), 277.4ms

Speed: 1.1ms preprocess, 277.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yurQuGfGfqlvPTDCZ9pCwQ_0.JPG: 480x640 (no detections), 275.9ms
Speed: 1.1ms preprocess, 275.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yurQuGfGfqlvPTDCZ9pCwQ_90.JPG: 480x640 (no detections), 282.6ms
Speed: 1.1ms preprocess, 282.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yurQuGfGfqlvPTDCZ9pCwQ_180.JPG: 480x640 (no detections), 273.8ms
Speed: 1.0ms preprocess, 273.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yurQuGfGfqlvPTDCZ9pCwQ_270.JPG: 480x640 (no detections), 271.4ms
Speed: 1.0ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuze5Tc947-FBC4QNrehtg_0.JPG: 480x640 (no detections), 278.1ms
Speed: 1.1ms preprocess, 278.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuze5Tc947-FBC4QNrehtg_90.JPG: 480x640 (no detections), 277.3ms
Speed: 1.0ms preprocess, 277.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuze5Tc947-FBC4QNrehtg_180.JPG: 480x640 (no detections), 277.1ms
Speed: 1.0ms preprocess, 277.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/U/yuze5Tc947-FBC4QNrehtg_270.JPG: 480x640 (no detections), 270.8ms
Speed: 1.0ms preprocess, 270.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yv6-33wTsGCgSkVucHlQ4g_0.JPG: 480x640 (no detections), 270.5ms
Speed: 1.0ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yv6-33wTsGCgSkVucHlQ4g_90.JPG: 480x640 (no detections), 275.8ms
Speed: 1.4ms preprocess, 275.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yv6-33wTsGCgSkVucHlQ4g_180.JPG: 480x640 (no detections), 279.9ms
Speed: 1.0ms preprocess, 279.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yv6-33wTsGCgSkVucHlQ4g_270.JPG: 480x640 (no detections), 277.1ms
Speed: 1.5ms preprocess, 277.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yv6Yxu6IFSGwFnYjDsvnXg_0.JPG: 480x640 1 Waste, 275.9ms
Speed: 1.1ms preprocess, 275.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yv6Yxu6IFSGwFnYjDsvnXg_90.JPG: 480x640 (no detections), 276.1ms
Speed: 1.0ms preprocess, 276.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yv6Yxu6IFSGwFnYjDsvnXg_180.JPG: 480x640 (no detections), 274.5ms
Speed: 1.0ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yv6Yxu6IFSGwFnYjDsvnXg_270.JPG: 480x640 (no detections), 272.0ms
Speed: 1.3ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yv78vvdK8r7NBMMZwIYIug_0.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yv78vvdK8r7NBMMZwIYIug_90.JPG: 480x640 (no detections), 272.1ms
Speed: 1.0ms preprocess, 272.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yv78vvdK8r7NBMMZwIYIug_180.JPG: 480x640 (no detections), 271.9ms
Speed: 1.0ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yv78vvdK8r7NBMMZwIYIug_270.JPG: 480x640 (no detections), 274.3ms
Speed: 1.1ms preprocess, 274.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvB7VwOJOP-WYtUddxlnZg_0.JPG: 480x640 (no detections), 278.4ms
Speed: 1.0ms preprocess, 278.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvB7VwOJOP-WYtUddxlnZg_90.JPG: 480x640 (no detections), 275.7ms
Speed: 1.1ms preprocess, 275.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvB7VwOJOP-WYtUddxlnZg_180.JPG: 480x640 (no detections), 275.0ms
Speed: 1.0ms preprocess, 275.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvB7VwOJOP-WYtUddxlnZg_270.JPG: 480x640 (no detections), 272.1ms
Speed: 1.1ms preprocess, 272.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvC1g1sjswQ08z3eQWd2Rw_0.JPG: 480x640 (no detections), 272.5ms
Speed: 1.1ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvC1g1sjswQ08z3eQWd2Rw_90.JPG: 480x640 (no detections), 290.4ms
Speed: 1.2ms preprocess, 290.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvC1g1sjswQ08z3eQWd2Rw_180.JPG: 480x640 (no detections), 275.3ms
Speed: 1.1ms preprocess, 275.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvC1g1sjswQ08z3eQWd2Rw_270.JPG: 480x640 (no detections), 275.6ms
Speed: 1.6ms preprocess, 275.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvCEyZQ3YzkiEWZ45HiezA_0.JPG: 480x640 (no detections), 271.8ms
Speed: 1.0ms preprocess, 271.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvCEyZQ3YzkiEWZ45HiezA_90.JPG: 480x640 (no detections), 275.9ms
Speed: 1.1ms preprocess, 275.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvCEyZQ3YzkiEWZ45HiezA_180.JPG: 480x640 (no detections), 271.2ms
Speed: 1.0ms preprocess, 271.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvCEyZQ3YzkiEWZ45HiezA_270.JPG: 480x640 (no detections), 275.4ms
Speed: 1.2ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvExI6qVqVDxgipscFGTXw_0.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvExI6qVqVDxgipscFGTXw_90.JPG: 480x640 (no detections), 274.6ms
Speed: 1.0ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvExI6qVqVDxgipscFGTXw_180.JPG: 480x640 (no detections), 278.0ms
Speed: 1.1ms preprocess, 278.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvExI6qVqVDxgipscFGTXw_270.JPG: 480x640 (no detections), 278.4ms
Speed: 1.1ms preprocess, 278.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvFgCvnFdB-X75XRsoVMRg_0.JPG: 480x640 (no detections), 277.2ms
Speed: 1.0ms preprocess, 277.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvFgCvnFdB-X75XRsoVMRg_90.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvFgCvnFdB-X75XRsoVMRg_180.JPG: 480x640 (no detections), 275.6ms
Speed: 1.0ms preprocess, 275.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvFgCvnFdB-X75XRsoVMRg_270.JPG: 480x640 (no detections), 275.4ms
Speed: 1.1ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvHaFdWYNSII7qSXBNFkiA_0.JPG: 480x640 (no detections), 275.3ms
Speed: 1.0ms preprocess, 275.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvHaFdWYNSII7qSXBNFkiA_90.JPG: 480x640 (no detections), 271.7ms
Speed: 1.2ms preprocess, 271.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvHaFdWYNSII7qSXBNFkiA_180.JPG: 480x640 1 Waste, 274.6ms
Speed: 1.0ms preprocess, 274.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvHaFdWYNSII7qSXBNFkiA_270.JPG: 480x640 (no detections), 275.9ms
Speed: 1.1ms preprocess, 275.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvLMZgf9eBjriUz6_UaoHA_0.JPG: 480x640 (no detections), 276.7ms
Speed: 1.3ms preprocess, 276.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvLMZgf9eBjriUz6_UaoHA_90.JPG: 480x640 (no detections), 273.6ms
Speed: 1.1ms preprocess, 273.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvLMZgf9eBjriUz6_UaoHA_180.JPG: 480x640 (no detections), 281.5ms
Speed: 1.1ms preprocess, 281.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvLMZgf9eBjriUz6_UaoHA_270.JPG: 480x640 (no detections), 284.5ms
Speed: 1.0ms preprocess, 284.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvLgHceHIoeq8eWT7rqAZg_0.JPG: 480x640 1 Waste, 279.2ms
Speed: 1.2ms preprocess, 279.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvLgHceHIoeq8eWT7rqAZg_90.JPG: 480x640 (no detections), 283.0ms
Speed: 1.2ms preprocess, 283.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvLgHceHIoeq8eWT7rqAZg_180.JPG: 480x640 (no detections), 274.2ms
Speed: 1.1ms preprocess, 274.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvLgHceHIoeq8eWT7rqAZg_270.JPG: 480x640 (no detections), 275.0ms
Speed: 1.1ms preprocess, 275.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvNRdBl3udWG3x3vQqJw8Q_0.JPG: 480x640 (no detections), 275.6ms
Speed: 1.1ms preprocess, 275.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvNRdBl3udWG3x3vQqJw8Q_90.JPG: 480x640 1 Waste, 277.0ms
Speed: 1.3ms preprocess, 277.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvNRdBl3udWG3x3vQqJw8Q_180.JPG: 480x640 (no detections), 274.7ms
Speed: 1.1ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvNRdBl3udWG3x3vQqJw8Q_270.JPG: 480x640 (no detections), 276.3ms
Speed: 1.1ms preprocess, 276.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvRXbMc7oQLJellQ7E8KzQ_0.JPG: 480x640 (no detections), 270.5ms
Speed: 1.1ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvRXbMc7oQLJellQ7E8KzQ_90.JPG: 480x640 (no detections), 274.8ms
Speed: 1.0ms preprocess, 274.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvRXbMc7oQLJellQ7E8KzQ_180.JPG: 480x640 (no detections), 275.2ms
Speed: 1.0ms preprocess, 275.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvRXbMc7oQLJellQ7E8KzQ_270.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yv_W9ljNA683vFcHrWTUwg_0.JPG: 480x640 (no detections), 277.3ms
Speed: 1.0ms preprocess, 277.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yv_W9ljNA683vFcHrWTUwg_90.JPG: 480x640 (no detections), 269.3ms
Speed: 1.1ms preprocess, 269.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yv_W9ljNA683vFcHrWTUwg_180.JPG: 480x640 (no detections), 284.1ms
Speed: 1.0ms preprocess, 284.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yv_W9ljNA683vFcHrWTUwg_270.JPG: 480x640 (no detections), 279.5ms
Speed: 1.1ms preprocess, 279.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvaO_QdzqmFAVWfr1MHBlw_0.JPG: 480x640 (no detections), 276.5ms
Speed: 1.2ms preprocess, 276.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvaO_QdzqmFAVWfr1MHBlw_90.JPG: 480x640 (no detections), 275.7ms
Speed: 1.1ms preprocess, 275.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvaO_QdzqmFAVWfr1MHBlw_180.JPG: 480x640 (no detections), 272.9ms

Speed: 1.1ms preprocess, 272.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvaO_QdzqmFAVWfr1MHBlw_270.JPG: 480x640 (no detections), 277.7ms
Speed: 1.2ms preprocess, 277.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvbq0KjqC83Lb309QO9t9w_0.JPG: 480x640 (no detections), 269.8ms
Speed: 1.2ms preprocess, 269.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvbq0KjqC83Lb309QO9t9w_90.JPG: 480x640 (no detections), 273.1ms
Speed: 1.0ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvbq0KjqC83Lb309QO9t9w_180.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvbq0KjqC83Lb309QO9t9w_270.JPG: 480x640 (no detections), 283.4ms
Speed: 1.1ms preprocess, 283.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvcmcLS7LYt4CcZtsydOFQ_0.JPG: 480x640 (no detections), 279.8ms
Speed: 1.1ms preprocess, 279.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvcmcLS7LYt4CcZtsydOFQ_90.JPG: 480x640 (no detections), 297.9ms
Speed: 1.1ms preprocess, 297.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvcmcLS7LYt4CcZtsydOFQ_180.JPG: 480x640 (no detections), 303.3ms
Speed: 1.4ms preprocess, 303.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvcmcLS7LYt4CcZtsydOFQ_270.JPG: 480x640 (no detections), 301.8ms
Speed: 1.2ms preprocess, 301.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvcxXnkTOaBY9e4J9nPTWg_0.JPG: 480x640 (no detections), 287.1ms
Speed: 1.9ms preprocess, 287.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvcxXnkTOaBY9e4J9nPTWg_90.JPG: 480x640 1 Waste, 360.9ms
Speed: 1.1ms preprocess, 360.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvcxXnkTOaBY9e4J9nPTWg_180.JPG: 480x640 (no detections), 273.5ms
Speed: 1.2ms preprocess, 273.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvcxXnkTOaBY9e4J9nPTWg_270.JPG: 480x640 (no detections), 279.4ms
Speed: 1.0ms preprocess, 279.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yveGQS3LPxTqi0CDH4w0KA_0.JPG: 480x640 (no detections), 272.2ms
Speed: 1.0ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yveGQS3LPxTqi0CDH4w0KA_90.JPG: 480x640 (no detections), 298.3ms
Speed: 1.1ms preprocess, 298.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yveGQS3LPxTqi0CDH4w0KA_180.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yveGQS3LPxTqi0CDH4w0KA_270.JPG: 480x640 (no detections), 271.5ms
Speed: 1.0ms preprocess, 271.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yveZg_NVW-AMVWP8wTmymg_0.JPG: 480x640 (no detections), 274.5ms
Speed: 1.0ms preprocess, 274.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yveZg_NVW-AMVWP8wTmymg_90.JPG: 480x640 (no detections), 271.6ms
Speed: 1.0ms preprocess, 271.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yveZg_NVW-AMVWP8wTmymg_180.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yveZg_NVW-AMVWP8wTmymg_270.JPG: 480x640 (no detections), 276.5ms
Speed: 1.1ms preprocess, 276.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvgJqIPh4YJvnw6xfZDr3A_0.JPG: 480x640 (no detections), 275.2ms
Speed: 1.1ms preprocess, 275.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvgJqIPh4YJvnw6xfZDr3A_90.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvgJqIPh4YJvnw6xfZDr3A_180.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvgJqIPh4YJvnw6xfZDr3A_270.JPG: 480x640 (no detections), 275.1ms
Speed: 1.0ms preprocess, 275.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvj3zp_pzFAXIiBV20d0Yg_0.JPG: 480x640 (no detections), 274.5ms
Speed: 1.0ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvj3zp_pzFAXIiBV20d0Yg_90.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvj3zp_pzFAXIiBV20d0Yg_180.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvj3zp_pzFAXIiBV20d0Yg_270.JPG: 480x640 (no detections), 271.5ms
Speed: 1.1ms preprocess, 271.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvkTUKcRNOWyc66hi2w9qA_0.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvkTUKcRNOWyc66hi2w9qA_90.JPG: 480x640 (no detections), 272.8ms
Speed: 1.0ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvkTUKcRNOWyc66hi2w9qA_180.JPG: 480x640 (no detections), 279.5ms
Speed: 1.2ms preprocess, 279.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvkTUKcRNOWyc66hi2w9qA_270.JPG: 480x640 (no detections), 275.7ms
Speed: 1.1ms preprocess, 275.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvmMdIkqpx157VCSBQeJCg_0.JPG: 480x640 (no detections), 272.5ms
Speed: 1.0ms preprocess, 272.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvmMdIkqpx157VCSBQeJCg_90.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvmMdIkqpx157VCSBQeJCg_180.JPG: 480x640 (no detections), 284.8ms
Speed: 1.1ms preprocess, 284.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvmMdIkqpx157VCSBQeJCg_270.JPG: 480x640 (no detections), 275.0ms
Speed: 1.1ms preprocess, 275.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvo9znBio47LQp_5xJRRTw_0.JPG: 480x640 (no detections), 274.6ms
Speed: 1.0ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvo9znBio47LQp_5xJRRTw_90.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvo9znBio47LQp_5xJRRTw_180.JPG: 480x640 (no detections), 273.3ms
Speed: 1.0ms preprocess, 273.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvo9znBio47LQp_5xJRRTw_270.JPG: 480x640 (no detections), 272.1ms
Speed: 1.0ms preprocess, 272.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvpnbUm_6WuSPrq9RIqwAg_0.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvpnbUm_6WuSPrq9RIqwAg_90.JPG: 480x640 (no detections), 277.5ms
Speed: 1.0ms preprocess, 277.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvpnbUm_6WuSPrq9RIqwAg_180.JPG: 480x640 (no detections), 275.8ms
Speed: 1.2ms preprocess, 275.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvpnbUm_6WuSPrq9RIqwAg_270.JPG: 480x640 (no detections), 276.1ms
Speed: 1.0ms preprocess, 276.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvvEZno-bnkvjuXO9n5W3w_0.JPG: 480x640 (no detections), 275.5ms
Speed: 1.1ms preprocess, 275.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvvEZno-bnkvjuXO9n5W3w_90.JPG: 480x640 (no detections), 275.2ms
Speed: 1.1ms preprocess, 275.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvvEZno-bnkvjuXO9n5W3w_180.JPG: 480x640 (no detections), 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvvEZno-bnkvjuXO9n5W3w_270.JPG: 480x640 (no detections), 276.4ms
Speed: 1.3ms preprocess, 276.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvwyIQO2_jI1VSZjXjOQ7w_0.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvwyIQO2_jI1VSZjXjOQ7w_90.JPG: 480x640 (no detections), 275.4ms
Speed: 1.1ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvwyIQO2_jI1VSZjXjOQ7w_180.JPG: 480x640 (no detections), 279.6ms
Speed: 1.0ms preprocess, 279.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/v/yvwyIQO2_jI1VSZjXjOQ7w_270.JPG: 480x640 (no detections), 277.3ms
Speed: 1.1ms preprocess, 277.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yw-Vg_Ro2w1E9TU--8n5dw_0.JPG: 480x640 (no detections), 273.9ms
Speed: 1.1ms preprocess, 273.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yw-Vg_Ro2w1E9TU--8n5dw_90.JPG: 480x640 (no detections), 276.5ms
Speed: 1.1ms preprocess, 276.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yw-Vg_Ro2w1E9TU--8n5dw_180.JPG: 480x640 (no detections), 279.0ms
Speed: 1.0ms preprocess, 279.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yw-Vg_Ro2w1E9TU--8n5dw_270.JPG: 480x640 (no detections), 291.2ms
Speed: 1.1ms preprocess, 291.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yw20DJ1bv-jZl8P4SjFivQ_0.JPG: 480x640 (no detections), 294.7ms
Speed: 1.1ms preprocess, 294.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yw20DJ1bv-jZl8P4SjFivQ_90.JPG: 480x640 (no detections), 285.7ms
Speed: 1.2ms preprocess, 285.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yw20DJ1bv-jZl8P4SjFivQ_180.JPG: 480x640 (no detections), 398.1ms
Speed: 1.2ms preprocess, 398.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yw20DJ1bv-jZl8P4SjFivQ_270.JPG: 480x640 (no detections), 328.3ms
Speed: 3.6ms preprocess, 328.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yw2pP248BG0uZaSTNu-pCA_0.JPG: 480x640 (no detections), 312.2ms
Speed: 1.3ms preprocess, 312.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yw2pP248BG0uZaSTNu-pCA_90.JPG: 480x640 (no detections), 369.0ms
Speed: 1.2ms preprocess, 369.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yw2pP248BG0uZaSTNu-pCA_180.JPG: 480x640 (no detections), 375.2ms
Speed: 1.4ms preprocess, 375.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yw2pP248BG0uZaSTNu-pCA_270.JPG: 480x640 (no detections), 278.5ms
Speed: 1.2ms preprocess, 278.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yw6Iud54dAAeSb4wcNOlLQ_0.JPG: 480x640 (no detections), 281.1ms
Speed: 1.2ms preprocess, 281.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yw6Iud54dAAeSb4wcNOlLQ_90.JPG: 480x640 (no detections), 420.0ms

Speed: 1.7ms preprocess, 420.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yw6Iud54dAAeSb4wcNOlLQ_180.JPG: 480x640 (no detections), 336.3ms
Speed: 1.3ms preprocess, 336.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yw6Iud54dAAeSb4wcNOlLQ_270.JPG: 480x640 (no detections), 497.5ms
Speed: 1.2ms preprocess, 497.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yw8jSPaP7p3StF2OcCCw6A_0.JPG: 480x640 (no detections), 308.7ms
Speed: 1.1ms preprocess, 308.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yw8jSPaP7p3StF2OcCCw6A_90.JPG: 480x640 (no detections), 271.0ms
Speed: 1.3ms preprocess, 271.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yw8jSPaP7p3StF2OcCCw6A_180.JPG: 480x640 (no detections), 272.4ms
Speed: 1.0ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yw8jSPaP7p3StF2OcCCw6A_270.JPG: 480x640 (no detections), 283.7ms
Speed: 1.1ms preprocess, 283.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywB1odJge78uGjBPxkTX-Q_0.JPG: 480x640 (no detections), 269.6ms
Speed: 1.0ms preprocess, 269.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywB1odJge78uGjBPxkTX-Q_90.JPG: 480x640 (no detections), 267.1ms
Speed: 1.1ms preprocess, 267.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywB1odJge78uGjBPxkTX-Q_180.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywB1odJge78uGjBPxkTX-Q_270.JPG: 480x640 (no detections), 269.1ms
Speed: 1.0ms preprocess, 269.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywDqL42XYV4fQWJyxFDROQ_0.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywDqL42XYV4fQWJyxFDROQ_90.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywDqL42XYV4fQWJyxFDROQ_180.JPG: 480x640 (no detections), 305.6ms
Speed: 1.0ms preprocess, 305.6ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywDqL42XYV4fQWJyxFDROQ_270.JPG: 480x640 (no detections), 365.2ms
Speed: 1.8ms preprocess, 365.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywF_sxaIEJDFdRmAJzdiAg_0.JPG: 480x640 (no detections), 276.1ms
Speed: 5.2ms preprocess, 276.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywF_sxaIEJDFdRmAJzdiAg_90.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywF_sxaIEJDFdRmAJzdiAg_180.JPG: 480x640 (no detections), 317.3ms
Speed: 1.0ms preprocess, 317.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywF_sxaIEJDFdRmAJzdiAg_270.JPG: 480x640 (no detections), 339.3ms
Speed: 1.1ms preprocess, 339.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywKWWvBD6plqL_YfkJRCfQ_0.JPG: 480x640 (no detections), 369.3ms
Speed: 1.4ms preprocess, 369.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywKWWvBD6plqL_YfkJRCfQ_90.JPG: 480x640 (no detections), 343.3ms
Speed: 2.4ms preprocess, 343.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywKWWvBD6plqL_YfkJRCfQ_180.JPG: 480x640 (no detections), 384.9ms
Speed: 1.3ms preprocess, 384.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywKWWvBD6plqL_YfkJRCfQ_270.JPG: 480x640 (no detections), 333.8ms
Speed: 1.6ms preprocess, 333.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywNOAIcTRuL6ja7EV_pv5w_0.JPG: 480x640 (no detections), 316.0ms
Speed: 1.1ms preprocess, 316.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywNOAIcTRuL6ja7EV_pv5w_90.JPG: 480x640 (no detections), 324.2ms
Speed: 1.1ms preprocess, 324.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywNOAIcTRuL6ja7EV_pv5w_180.JPG: 480x640 (no detections), 342.7ms
Speed: 1.4ms preprocess, 342.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywNOAIcTRuL6ja7EV_pv5w_270.JPG: 480x640 (no detections), 314.7ms
Speed: 1.1ms preprocess, 314.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywP5puPAQd7tjOMp_bUdeA_0.JPG: 480x640 (no detections), 296.9ms
Speed: 1.4ms preprocess, 296.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywP5puPAQd7tjOMp_bUdeA_90.JPG: 480x640 (no detections), 286.4ms
Speed: 1.1ms preprocess, 286.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywP5puPAQd7tjOMp_bUdeA_180.JPG: 480x640 (no detections), 293.3ms
Speed: 1.1ms preprocess, 293.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywP5puPAQd7tjOMp_bUdeA_270.JPG: 480x640 (no detections), 285.1ms
Speed: 1.1ms preprocess, 285.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywTQdL1kcDAMRIY_ur_PEA_0.JPG: 480x640 (no detections), 276.0ms
Speed: 1.0ms preprocess, 276.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywTQdL1kcDAMRIY_ur_PEA_90.JPG: 480x640 (no detections), 279.8ms
Speed: 1.2ms preprocess, 279.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywTQdL1kcDAMRIY_ur_PEA_180.JPG: 480x640 (no detections), 290.0ms
Speed: 1.2ms preprocess, 290.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywTQdL1kcDAMRIY_ur_PEA_270.JPG: 480x640 (no detections), 279.4ms
Speed: 1.0ms preprocess, 279.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywTWI1-vL7W-QJFI5JKJAQ_0.JPG: 480x640 (no detections), 289.1ms
Speed: 1.1ms preprocess, 289.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywTWI1-vL7W-QJFI5JKJAQ_90.JPG: 480x640 (no detections), 278.7ms
Speed: 1.1ms preprocess, 278.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywTWI1-vL7W-QJFI5JKJAQ_180.JPG: 480x640 (no detections), 279.3ms
Speed: 1.0ms preprocess, 279.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywTWI1-vL7W-QJFI5JKJAQ_270.JPG: 480x640 (no detections), 283.2ms
Speed: 1.1ms preprocess, 283.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywURkI-6MF4NyXnL5lG2cQ_0.JPG: 480x640 (no detections), 275.5ms
Speed: 1.2ms preprocess, 275.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywURkI-6MF4NyXnL5lG2cQ_90.JPG: 480x640 1 Waste, 275.6ms
Speed: 1.1ms preprocess, 275.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywURkI-6MF4NyXnL5lG2cQ_180.JPG: 480x640 (no detections), 276.7ms
Speed: 1.0ms preprocess, 276.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywURkI-6MF4NyXnL5lG2cQ_270.JPG: 480x640 (no detections), 283.5ms
Speed: 1.1ms preprocess, 283.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywUXOREVv7o5-nHS-HCqzA_0.JPG: 480x640 (no detections), 277.5ms
Speed: 1.1ms preprocess, 277.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywUXOREVv7o5-nHS-HCqzA_90.JPG: 480x640 (no detections), 273.9ms
Speed: 1.4ms preprocess, 273.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywUXOREVv7o5-nHS-HCqzA_180.JPG: 480x640 (no detections), 278.7ms
Speed: 1.2ms preprocess, 278.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywUXOREVv7o5-nHS-HCqzA_270.JPG: 480x640 (no detections), 344.1ms
Speed: 1.1ms preprocess, 344.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywW4KMn7HTHJpWjW68x6EA_0.JPG: 480x640 (no detections), 286.3ms
Speed: 1.2ms preprocess, 286.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywW4KMn7HTHJpWjW68x6EA_90.JPG: 480x640 (no detections), 285.4ms
Speed: 1.1ms preprocess, 285.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywW4KMn7HTHJpWjW68x6EA_180.JPG: 480x640 (no detections), 284.8ms
Speed: 1.2ms preprocess, 284.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywW4KMn7HTHJpWjW68x6EA_270.JPG: 480x640 (no detections), 284.2ms
Speed: 1.1ms preprocess, 284.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywXMZtwPlBxE98LvW6Onlw_0.JPG: 480x640 (no detections), 278.4ms
Speed: 1.3ms preprocess, 278.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywXMZtwPlBxE98LvW6Onlw_90.JPG: 480x640 1 Waste, 276.4ms
Speed: 1.2ms preprocess, 276.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywXMZtwPlBxE98LvW6Onlw_180.JPG: 480x640 (no detections), 279.5ms
Speed: 1.1ms preprocess, 279.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywXMZtwPlBxE98LvW6Onlw_270.JPG: 480x640 (no detections), 319.1ms
Speed: 1.5ms preprocess, 319.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywYG1EjtJz1DYDG7Z2QGBQ_0.JPG: 480x640 (no detections), 296.5ms
Speed: 1.1ms preprocess, 296.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywYG1EjtJz1DYDG7Z2QGBQ_90.JPG: 480x640 (no detections), 291.0ms
Speed: 1.1ms preprocess, 291.0ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywYG1EjtJz1DYDG7Z2QGBQ_180.JPG: 480x640 2 Wastes, 283.8ms
Speed: 1.1ms preprocess, 283.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywYG1EjtJz1DYDG7Z2QGBQ_270.JPG: 480x640 (no detections), 278.7ms
Speed: 1.0ms preprocess, 278.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yw_sjB09afx8YOCvCmUDvg_0.JPG: 480x640 (no detections), 276.5ms
Speed: 1.1ms preprocess, 276.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yw_sjB09afx8YOCvCmUDvg_90.JPG: 480x640 (no detections), 272.1ms
Speed: 1.2ms preprocess, 272.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yw_sjB09afx8YOCvCmUDvg_180.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yw_sjB09afx8YOCvCmUDvg_270.JPG: 480x640 (no detections), 272.8ms
Speed: 1.0ms preprocess, 272.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywcbX6HTdRRSWg4In06cnw_0.JPG: 480x640 (no detections), 273.4ms
Speed: 1.6ms preprocess, 273.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywcbX6HTdRRSWg4In06cnw_90.JPG: 480x640 (no detections), 280.1ms
Speed: 1.1ms preprocess, 280.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywcbX6HTdRRSWg4In06cnw_180.JPG: 480x640 (no detections), 272.4ms
Speed: 1.1ms preprocess, 272.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywcbX6HTdRRSWg4In06cnw_270.JPG: 480x640 (no detections), 287.2ms
Speed: 1.0ms preprocess, 287.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yweVzkAgEd9cyOIyvyMh3g_0.JPG: 480x640 (no detections), 277.2ms

Speed: 1.0ms preprocess, 277.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yweVzkAgEd9cyOIyvyMh3g_90.JPG: 480x640 (no detections), 290.4ms
Speed: 1.1ms preprocess, 290.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yweVzkAgEd9cyOIyvyMh3g_180.JPG: 480x640 (no detections), 275.1ms
Speed: 1.0ms preprocess, 275.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/yweVzkAgEd9cyOIyvyMh3g_270.JPG: 480x640 (no detections), 291.0ms
Speed: 1.1ms preprocess, 291.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywgVlVIA1LrYgC9gIsifnQ_0.JPG: 480x640 (no detections), 274.4ms
Speed: 1.1ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywgVlVIA1LrYgC9gIsifnQ_90.JPG: 480x640 (no detections), 283.3ms
Speed: 1.6ms preprocess, 283.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywgVlVIA1LrYgC9gIsifnQ_180.JPG: 480x640 (no detections), 275.0ms
Speed: 1.1ms preprocess, 275.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywgVlVIA1LrYgC9gIsifnQ_270.JPG: 480x640 (no detections), 274.3ms
Speed: 1.1ms preprocess, 274.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywhpO-0LfRqmwb5Izr5qFw_0.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywhpO-0LfRqmwb5Izr5qFw_90.JPG: 480x640 (no detections), 275.8ms
Speed: 1.1ms preprocess, 275.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywhpO-0LfRqmwb5Izr5qFw_180.JPG: 480x640 (no detections), 273.9ms
Speed: 1.8ms preprocess, 273.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywhpO-0LfRqmwb5Izr5qFw_270.JPG: 480x640 (no detections), 276.4ms
Speed: 1.4ms preprocess, 276.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywkHA6yCXARxxjUxNw2LmQ_0.JPG: 480x640 (no detections), 276.7ms
Speed: 1.1ms preprocess, 276.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywkHA6yCXARxxjUxNw2LmQ_90.JPG: 480x640 (no detections), 275.8ms
Speed: 1.0ms preprocess, 275.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywkHA6yCXARxxjUxNw2LmQ_180.JPG: 480x640 (no detections), 278.7ms
Speed: 1.1ms preprocess, 278.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywkHA6yCXARxxjUxNw2LmQ_270.JPG: 480x640 (no detections), 296.1ms
Speed: 1.2ms preprocess, 296.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywkz1ITpcRkpkI28ZZYfrw_0.JPG: 480x640 (no detections), 321.8ms
Speed: 1.2ms preprocess, 321.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywkz1ITpcRkpkI28ZZYfrw_90.JPG: 480x640 (no detections), 302.2ms
Speed: 1.0ms preprocess, 302.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywkz1ITpcRkpkI28ZZYfrw_180.JPG: 480x640 (no detections), 296.0ms
Speed: 1.1ms preprocess, 296.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywkz1ITpcRkpkI28ZZYfrw_270.JPG: 480x640 (no detections), 283.4ms
Speed: 1.1ms preprocess, 283.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywmcSux2jClEULkuC_jISg_0.JPG: 480x640 1 Waste, 275.8ms
Speed: 1.0ms preprocess, 275.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywmcSux2jClEULkuC_jISg_90.JPG: 480x640 (no detections), 278.3ms
Speed: 1.2ms preprocess, 278.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywmcSux2jClEULkuC_jISg_180.JPG: 480x640 (no detections), 293.2ms
Speed: 1.3ms preprocess, 293.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywmcSux2jClEULkuC_jISg_270.JPG: 480x640 (no detections), 318.5ms
Speed: 1.3ms preprocess, 318.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywsStKkfz7ErgC14nKTcFA_0.JPG: 480x640 (no detections), 291.2ms
Speed: 1.7ms preprocess, 291.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywsStKkfz7ErgC14nKTcFA_90.JPG: 480x640 1 Waste, 299.2ms
Speed: 1.1ms preprocess, 299.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywsStKkfz7ErgC14nKTcFA_180.JPG: 480x640 (no detections), 286.6ms
Speed: 1.1ms preprocess, 286.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywsStKkfz7ErgC14nKTcFA_270.JPG: 480x640 (no detections), 291.4ms
Speed: 1.1ms preprocess, 291.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywuXLB2Zr6iccVl8SdknmA_0.JPG: 480x640 (no detections), 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywuXLB2Zr6iccVl8SdknmA_90.JPG: 480x640 (no detections), 332.4ms
Speed: 1.6ms preprocess, 332.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywuXLB2Zr6iccVl8SdknmA_180.JPG: 480x640 (no detections), 288.9ms
Speed: 1.2ms preprocess, 288.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywuXLB2Zr6iccVl8SdknmA_270.JPG: 480x640 (no detections), 317.6ms
Speed: 1.1ms preprocess, 317.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywulN1YGPZ5SQCU4hzh00Q_0.JPG: 480x640 (no detections), 290.5ms
Speed: 1.5ms preprocess, 290.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywulN1YGPZ5SQCU4hzh00Q_90.JPG: 480x640 (no detections), 332.4ms
Speed: 1.2ms preprocess, 332.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywulN1YGPZ5SQCU4hzh00Q_180.JPG: 480x640 (no detections), 291.2ms
Speed: 1.5ms preprocess, 291.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywulN1YGPZ5SQCU4hzh00Q_270.JPG: 480x640 (no detections), 275.2ms
Speed: 1.4ms preprocess, 275.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywy1oJ2ffitxUB4Q6ktDFQ_0.JPG: 480x640 (no detections), 282.1ms
Speed: 1.1ms preprocess, 282.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywy1oJ2ffitxUB4Q6ktDFQ_90.JPG: 480x640 (no detections), 301.6ms
Speed: 1.0ms preprocess, 301.6ms inference, 16.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywy1oJ2ffitxUB4Q6ktDFQ_180.JPG: 480x640 (no detections), 296.1ms
Speed: 1.7ms preprocess, 296.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywy1oJ2ffitxUB4Q6ktDFQ_270.JPG: 480x640 (no detections), 282.0ms
Speed: 1.3ms preprocess, 282.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywy82gbRf5YMVqYxmroEMw_0.JPG: 480x640 (no detections), 288.0ms
Speed: 1.4ms preprocess, 288.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywy82gbRf5YMVqYxmroEMw_90.JPG: 480x640 (no detections), 280.9ms
Speed: 1.1ms preprocess, 280.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywy82gbRf5YMVqYxmroEMw_180.JPG: 480x640 (no detections), 278.6ms
Speed: 1.0ms preprocess, 278.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywy82gbRf5YMVqYxmroEMw_270.JPG: 480x640 (no detections), 283.2ms
Speed: 1.0ms preprocess, 283.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywz-uvpK46eTzMmplBcAdA_0.JPG: 480x640 (no detections), 287.8ms
Speed: 1.2ms preprocess, 287.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywz-uvpK46eTzMmplBcAdA_90.JPG: 480x640 (no detections), 301.1ms
Speed: 1.2ms preprocess, 301.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywz-uvpK46eTzMmplBcAdA_180.JPG: 480x640 (no detections), 290.8ms
Speed: 1.1ms preprocess, 290.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/w/ywz-uvpK46eTzMmplBcAdA_270.JPG: 480x640 (no detections), 276.2ms
Speed: 1.1ms preprocess, 276.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yx0YxFajbZqlnlikvrraXw_0.JPG: 480x640 (no detections), 297.4ms
Speed: 1.1ms preprocess, 297.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yx0YxFajbZqlnlikvrraXw_90.JPG: 480x640 (no detections), 294.3ms
Speed: 1.1ms preprocess, 294.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yx0YxFajbZqlnlikvrraXw_180.JPG: 480x640 (no detections), 302.1ms
Speed: 1.7ms preprocess, 302.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yx0YxFajbZqlnlikvrraXw_270.JPG: 480x640 (no detections), 303.3ms
Speed: 1.1ms preprocess, 303.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yx3MrIp1tkKbYozR4F5mmw_0.JPG: 480x640 (no detections), 289.2ms
Speed: 1.0ms preprocess, 289.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yx3MrIp1tkKbYozR4F5mmw_90.JPG: 480x640 (no detections), 300.5ms
Speed: 1.1ms preprocess, 300.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yx3MrIp1tkKbYozR4F5mmw_180.JPG: 480x640 (no detections), 276.6ms
Speed: 1.1ms preprocess, 276.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yx3MrIp1tkKbYozR4F5mmw_270.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxDskKcTyBWuDgeGO65xQw_0.JPG: 480x640 (no detections), 297.2ms
Speed: 1.1ms preprocess, 297.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxDskKcTyBWuDgeGO65xQw_90.JPG: 480x640 (no detections), 279.2ms
Speed: 1.0ms preprocess, 279.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxDskKcTyBWuDgeGO65xQw_180.JPG: 480x640 (no detections), 271.0ms
Speed: 1.1ms preprocess, 271.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxDskKcTyBWuDgeGO65xQw_270.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxENOJ1H7IimwhVW0bVURw_0.JPG: 480x640 (no detections), 330.4ms
Speed: 1.2ms preprocess, 330.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxENOJ1H7IimwhVW0bVURw_90.JPG: 480x640 (no detections), 283.1ms
Speed: 1.2ms preprocess, 283.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxENOJ1H7IimwhVW0bVURw_180.JPG: 480x640 (no detections), 277.7ms
Speed: 1.4ms preprocess, 277.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxENOJ1H7IimwhVW0bVURw_270.JPG: 480x640 (no detections), 276.0ms
Speed: 1.2ms preprocess, 276.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxFB9EkMGmtSuRgneEfQSg_0.JPG: 480x640 (no detections), 272.0ms
Speed: 1.2ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxFB9EkMGmtSuRgneEfQSg_90.JPG: 480x640 (no detections), 273.0ms
Speed: 1.0ms preprocess, 273.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxFB9EkMGmtSuRgneEfQSg_180.JPG: 480x640 (no detections), 277.3ms
Speed: 1.1ms preprocess, 277.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxFB9EkMGmtSuRgneEfQSg_270.JPG: 480x640 (no detections), 271.6ms

Speed: 1.0ms preprocess, 271.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxGKyZ3TIEvSSfV6uVdOrA_0.JPG: 480x640 (no detections), 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxGKyZ3TIEvSSfV6uVdOrA_90.JPG: 480x640 (no detections), 304.5ms
Speed: 1.1ms preprocess, 304.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxGKyZ3TIEvSSfV6uVdOrA_180.JPG: 480x640 (no detections), 282.6ms
Speed: 1.2ms preprocess, 282.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxGKyZ3TIEvSSfV6uVdOrA_270.JPG: 480x640 (no detections), 283.4ms
Speed: 1.1ms preprocess, 283.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxGQ5hm2gO8xkV-efACTUg_0.JPG: 480x640 1 Waste, 274.4ms
Speed: 1.2ms preprocess, 274.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxGQ5hm2gO8xkV-efACTUg_90.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxGQ5hm2gO8xkV-efACTUg_180.JPG: 480x640 (no detections), 274.7ms
Speed: 1.1ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxGQ5hm2gO8xkV-efACTUg_270.JPG: 480x640 (no detections), 273.3ms
Speed: 1.2ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxH5jbtezFBHa237MU7wRw_0.JPG: 480x640 (no detections), 272.0ms
Speed: 1.1ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxH5jbtezFBHa237MU7wRw_90.JPG: 480x640 (no detections), 275.0ms
Speed: 1.1ms preprocess, 275.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxH5jbtezFBHa237MU7wRw_180.JPG: 480x640 (no detections), 272.3ms
Speed: 1.1ms preprocess, 272.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxH5jbtezFBHa237MU7wRw_270.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxH8ppA-KTOsn9vWakEpqw_0.JPG: 480x640 (no detections), 283.2ms
Speed: 1.2ms preprocess, 283.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxH8ppA-KTOsn9vWakEpqw_90.JPG: 480x640 (no detections), 273.5ms
Speed: 1.2ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxH8ppA-KTOsn9vWakEpqw_180.JPG: 480x640 (no detections), 273.2ms
Speed: 1.1ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxH8ppA-KTOsn9vWakEpqw_270.JPG: 480x640 (no detections), 275.4ms
Speed: 1.1ms preprocess, 275.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxTUIDkkCGLR8r5meDJmdg_0.JPG: 480x640 (no detections), 278.6ms
Speed: 1.2ms preprocess, 278.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxTUIDkkCGLR8r5meDJmdg_90.JPG: 480x640 (no detections), 278.5ms
Speed: 1.1ms preprocess, 278.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxTUIDkkCGLR8r5meDJmdg_180.JPG: 480x640 (no detections), 274.9ms
Speed: 1.2ms preprocess, 274.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxTUIDkkCGLR8r5meDJmdg_270.JPG: 480x640 (no detections), 274.8ms
Speed: 1.1ms preprocess, 274.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxTonfOGbGe4O8V8ElDe4w_0.JPG: 480x640 (no detections), 277.4ms
Speed: 1.0ms preprocess, 277.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxTonfOGbGe4O8V8ElDe4w_90.JPG: 480x640 (no detections), 274.7ms
Speed: 1.3ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxTonfOGbGe4O8V8ElDe4w_180.JPG: 480x640 (no detections), 271.1ms
Speed: 1.0ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxTonfOGbGe4O8V8ElDe4w_270.JPG: 480x640 (no detections), 278.8ms
Speed: 1.2ms preprocess, 278.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxUfwVBuEk1cxtqseqSmCA_0.JPG: 480x640 (no detections), 272.8ms
Speed: 1.2ms preprocess, 272.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxUfwVBuEk1cxtqseqSmCA_90.JPG: 480x640 (no detections), 273.6ms
Speed: 1.1ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxUfwVBuEk1cxtqseqSmCA_180.JPG: 480x640 (no detections), 273.6ms
Speed: 1.2ms preprocess, 273.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxUfwVBuEk1cxtqseqSmCA_270.JPG: 480x640 (no detections), 275.9ms
Speed: 1.0ms preprocess, 275.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxjnuB61QzbSXhJOvnw8vA_0.JPG: 480x640 (no detections), 277.0ms
Speed: 1.1ms preprocess, 277.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxjnuB61QzbSXhJOvnw8vA_90.JPG: 480x640 (no detections), 271.8ms
Speed: 1.0ms preprocess, 271.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxjnuB61QzbSXhJOvnw8vA_180.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxjnuB61QzbSXhJOvnw8vA_270.JPG: 480x640 (no detections), 274.4ms
Speed: 1.2ms preprocess, 274.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxn53whvHvhZsTT7qk1jbQ_0.JPG: 480x640 (no detections), 278.5ms
Speed: 1.0ms preprocess, 278.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxn53whvHvhZsTT7qk1jbQ_90.JPG: 480x640 (no detections), 276.9ms
Speed: 1.2ms preprocess, 276.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxn53whvHvhZsTT7qk1jbQ_180.JPG: 480x640 (no detections), 336.4ms
Speed: 1.1ms preprocess, 336.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxn53whvHvhZsTT7qk1jbQ_270.JPG: 480x640 (no detections), 320.9ms
Speed: 1.0ms preprocess, 320.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxrOCEGKQfwYWTjiSlB3Aw_0.JPG: 480x640 (no detections), 281.8ms
Speed: 1.4ms preprocess, 281.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxrOCEGKQfwYWTjiSlB3Aw_90.JPG: 480x640 (no detections), 272.8ms
Speed: 1.0ms preprocess, 272.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxrOCEGKQfwYWTjiSlB3Aw_180.JPG: 480x640 (no detections), 274.3ms
Speed: 1.0ms preprocess, 274.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxrOCEGKQfwYWTjiSlB3Aw_270.JPG: 480x640 (no detections), 275.3ms
Speed: 1.1ms preprocess, 275.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxrRsm4FpJsmPc_xebg4Fw_0.JPG: 480x640 (no detections), 273.4ms
Speed: 1.1ms preprocess, 273.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxrRsm4FpJsmPc_xebg4Fw_90.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxrRsm4FpJsmPc_xebg4Fw_180.JPG: 480x640 (no detections), 266.3ms
Speed: 1.1ms preprocess, 266.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxrRsm4FpJsmPc_xebg4Fw_270.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxsS7JK89tMH8IMQOF-ajA_0.JPG: 480x640 (no detections), 272.5ms
Speed: 1.1ms preprocess, 272.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxsS7JK89tMH8IMQOF-ajA_90.JPG: 480x640 (no detections), 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxsS7JK89tMH8IMQOF-ajA_180.JPG: 480x640 (no detections), 275.6ms
Speed: 1.0ms preprocess, 275.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxsS7JK89tMH8IMQOF-ajA_270.JPG: 480x640 (no detections), 273.3ms
Speed: 1.0ms preprocess, 273.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxtJJUD3Fu4k2vkmXNB0ng_0.JPG: 480x640 (no detections), 276.2ms
Speed: 1.2ms preprocess, 276.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxtJJUD3Fu4k2vkmXNB0ng_90.JPG: 480x640 (no detections), 274.1ms
Speed: 1.2ms preprocess, 274.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxtJJUD3Fu4k2vkmXNB0ng_180.JPG: 480x640 (no detections), 272.4ms
Speed: 1.1ms preprocess, 272.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxtJJUD3Fu4k2vkmXNB0ng_270.JPG: 480x640 (no detections), 274.7ms
Speed: 1.1ms preprocess, 274.7ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxuQF8qLC18IcI76KJRLEg_0.JPG: 480x640 (no detections), 272.0ms
Speed: 1.1ms preprocess, 272.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxuQF8qLC18IcI76KJRLEg_90.JPG: 480x640 (no detections), 268.8ms
Speed: 1.1ms preprocess, 268.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxuQF8qLC18IcI76KJRLEg_180.JPG: 480x640 (no detections), 272.8ms
Speed: 1.2ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxuQF8qLC18IcI76KJRLEg_270.JPG: 480x640 (no detections), 273.1ms
Speed: 1.0ms preprocess, 273.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxzYnEHBy5BQs07vi_FX3g_0.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxzYnEHBy5BQs07vi_FX3g_90.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxzYnEHBy5BQs07vi_FX3g_180.JPG: 480x640 (no detections), 271.0ms
Speed: 1.1ms preprocess, 271.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/x/yxzYnEHBy5BQs07vi_FX3g_270.JPG: 480x640 (no detections), 272.8ms
Speed: 1.0ms preprocess, 272.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yy0SQt6um7naYsKcj8VTlQ_0.JPG: 480x640 (no detections), 277.7ms
Speed: 1.0ms preprocess, 277.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yy0SQt6um7naYsKcj8VTlQ_90.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yy0SQt6um7naYsKcj8VTlQ_180.JPG: 480x640 (no detections), 268.4ms
Speed: 1.1ms preprocess, 268.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yy0SQt6um7naYsKcj8VTlQ_270.JPG: 480x640 (no detections), 271.0ms
Speed: 1.1ms preprocess, 271.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yy0tk6OToM6jt_YgSg9bXA_0.JPG: 480x640 (no detections), 328.9ms
Speed: 1.1ms preprocess, 328.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yy0tk6OToM6jt_YgSg9bXA_90.JPG: 480x640 (no detections), 284.6ms
Speed: 1.1ms preprocess, 284.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yy0tk6OToM6jt_YgSg9bXA_180.JPG: 480x640 (no detections), 325.6ms

Speed: 1.6ms preprocess, 325.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yy0tk6OToM6jt_YgSg9bXA_270.JPG: 480x640 (no detections), 278.8ms
Speed: 1.1ms preprocess, 278.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yy8a3lltAB3QA4zRO194mw_0.JPG: 480x640 (no detections), 280.8ms
Speed: 1.4ms preprocess, 280.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yy8a3lltAB3QA4zRO194mw_90.JPG: 480x640 1 Waste, 280.5ms
Speed: 1.9ms preprocess, 280.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yy8a3lltAB3QA4zRO194mw_180.JPG: 480x640 (no detections), 276.2ms
Speed: 1.4ms preprocess, 276.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yy8a3lltAB3QA4zRO194mw_270.JPG: 480x640 (no detections), 272.6ms
Speed: 1.2ms preprocess, 272.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yyAvlxHJ-GxR6SrNnP6HQQ_0.JPG: 480x640 (no detections), 279.1ms
Speed: 1.6ms preprocess, 279.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yyAvlxHJ-GxR6SrNnP6HQQ_90.JPG: 480x640 (no detections), 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yyAvlxHJ-GxR6SrNnP6HQQ_180.JPG: 480x640 (no detections), 277.2ms
Speed: 1.1ms preprocess, 277.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yyAvlxHJ-GxR6SrNnP6HQQ_270.JPG: 480x640 (no detections), 284.7ms
Speed: 1.1ms preprocess, 284.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yyB836-vXggYh4gJUfPoeQ_0.JPG: 480x640 (no detections), 274.3ms
Speed: 1.3ms preprocess, 274.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yyB836-vXggYh4gJUfPoeQ_90.JPG: 480x640 (no detections), 277.6ms
Speed: 1.1ms preprocess, 277.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yyB836-vXggYh4gJUfPoeQ_180.JPG: 480x640 (no detections), 275.2ms
Speed: 1.1ms preprocess, 275.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yyB836-vXggYh4gJUfPoeQ_270.JPG: 480x640 (no detections), 272.5ms
Speed: 1.2ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yyCBa3NClSAaYkckg-smhA_0.JPG: 480x640 (no detections), 268.7ms
Speed: 1.1ms preprocess, 268.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yyCBa3NClSAaYkckg-smhA_90.JPG: 480x640 (no detections), 272.3ms
Speed: 1.0ms preprocess, 272.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yyCBa3NClSAaYkckg-smhA_180.JPG: 480x640 (no detections), 277.1ms
Speed: 1.1ms preprocess, 277.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yyCBa3NClSAaYkckg-smhA_270.JPG: 480x640 (no detections), 278.7ms
Speed: 1.0ms preprocess, 278.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yyCbZP4M75ibjW_NGUHrpQ_0.JPG: 480x640 (no detections), 276.4ms
Speed: 1.1ms preprocess, 276.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yyCbZP4M75ibjW_NGUHrpQ_90.JPG: 480x640 (no detections), 290.2ms
Speed: 1.3ms preprocess, 290.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yyCbZP4M75ibjW_NGUHrpQ_180.JPG: 480x640 (no detections), 276.9ms
Speed: 1.1ms preprocess, 276.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yyCbZP4M75ibjW_NGUHrpQ_270.JPG: 480x640 (no detections), 277.3ms
Speed: 1.1ms preprocess, 277.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yyD0vt5snHc3DH2-ro8cnA_0.JPG: 480x640 (no detections), 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yyD0vt5snHc3DH2-ro8cnA_90.JPG: 480x640 (no detections), 280.7ms
Speed: 1.2ms preprocess, 280.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yyD0vt5snHc3DH2-ro8cnA_180.JPG: 480x640 (no detections), 297.3ms
Speed: 1.1ms preprocess, 297.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yyD0vt5snHc3DH2-ro8cnA_270.JPG: 480x640 (no detections), 352.7ms
Speed: 1.1ms preprocess, 352.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yyJhPE-M1kkys007Xqt1BA_0.JPG: 480x640 (no detections), 310.8ms
Speed: 1.2ms preprocess, 310.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yyJhPE-M1kkys007Xqt1BA_90.JPG: 480x640 (no detections), 309.6ms
Speed: 1.3ms preprocess, 309.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yyJhPE-M1kkys007Xqt1BA_180.JPG: 480x640 (no detections), 306.6ms
Speed: 1.2ms preprocess, 306.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yyJhPE-M1kkys007Xqt1BA_270.JPG: 480x640 (no detections), 307.1ms
Speed: 1.0ms preprocess, 307.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yyLUnKoyWpTwG9Op0oZuZw_0.JPG: 480x640 (no detections), 306.4ms
Speed: 1.1ms preprocess, 306.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yyLUnKoyWpTwG9Op0oZuZw_90.JPG: 480x640 (no detections), 294.3ms
Speed: 1.2ms preprocess, 294.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yyLUnKoyWpTwG9Op0oZuZw_180.JPG: 480x640 (no detections), 290.0ms
Speed: 1.3ms preprocess, 290.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yyLUnKoyWpTwG9Op0oZuZw_270.JPG: 480x640 (no detections), 340.4ms
Speed: 1.1ms preprocess, 340.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yyOFd_zFtQTptqaHPDc1dA_0.JPG: 480x640 (no detections), 302.1ms
Speed: 1.4ms preprocess, 302.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yyOFd_zFtQTptqaHPDc1dA_90.JPG: 480x640 (no detections), 285.3ms
Speed: 1.1ms preprocess, 285.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yyOFd_zFtQTptqaHPDc1dA_180.JPG: 480x640 (no detections), 298.6ms
Speed: 1.6ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yyOFd_zFtQTptqaHPDc1dA_270.JPG: 480x640 (no detections), 324.8ms
Speed: 1.3ms preprocess, 324.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yyQxxzX38NrO4daObDcVOw_0.JPG: 480x640 (no detections), 293.3ms
Speed: 1.1ms preprocess, 293.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yyQxxzX38NrO4daObDcVOw_90.JPG: 480x640 (no detections), 292.6ms
Speed: 1.6ms preprocess, 292.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yyQxxzX38NrO4daObDcVOw_180.JPG: 480x640 (no detections), 275.2ms
Speed: 1.2ms preprocess, 275.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yyQxxzX38NrO4daObDcVOw_270.JPG: 480x640 (no detections), 313.9ms
Speed: 1.1ms preprocess, 313.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yyffgQA9sAGe6_Kodvbs-w_0.JPG: 480x640 (no detections), 285.7ms
Speed: 1.3ms preprocess, 285.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yyffgQA9sAGe6_Kodvbs-w_90.JPG: 480x640 (no detections), 295.4ms
Speed: 1.1ms preprocess, 295.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yyffgQA9sAGe6_Kodvbs-w_180.JPG: 480x640 (no detections), 322.4ms
Speed: 1.2ms preprocess, 322.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yyffgQA9sAGe6_Kodvbs-w_270.JPG: 480x640 (no detections), 308.6ms
Speed: 1.4ms preprocess, 308.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yyjwKfxuicM8T825GNIyTA_0.JPG: 480x640 (no detections), 279.8ms
Speed: 1.1ms preprocess, 279.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yyjwKfxuicM8T825GNIyTA_90.JPG: 480x640 (no detections), 282.3ms
Speed: 1.0ms preprocess, 282.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yyjwKfxuicM8T825GNIyTA_180.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yyjwKfxuicM8T825GNIyTA_270.JPG: 480x640 (no detections), 279.9ms
Speed: 1.3ms preprocess, 279.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yyvUfH74eHqDbTNGGvh34g_0.JPG: 480x640 (no detections), 275.2ms
Speed: 1.1ms preprocess, 275.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yyvUfH74eHqDbTNGGvh34g_90.JPG: 480x640 (no detections), 288.5ms
Speed: 1.0ms preprocess, 288.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yyvUfH74eHqDbTNGGvh34g_180.JPG: 480x640 (no detections), 291.3ms
Speed: 1.1ms preprocess, 291.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/y/yyvUfH74eHqDbTNGGvh34g_270.JPG: 480x640 (no detections), 308.0ms
Speed: 1.0ms preprocess, 308.0ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yz-s3jqFfdaw6Z3GfZZPUw_0.JPG: 480x640 (no detections), 373.9ms
Speed: 1.2ms preprocess, 373.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yz-s3jqFfdaw6Z3GfZZPUw_90.JPG: 480x640 (no detections), 291.0ms
Speed: 1.2ms preprocess, 291.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yz-s3jqFfdaw6Z3GfZZPUw_180.JPG: 480x640 (no detections), 281.9ms
Speed: 1.1ms preprocess, 281.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yz-s3jqFfdaw6Z3GfZZPUw_270.JPG: 480x640 (no detections), 283.6ms
Speed: 1.1ms preprocess, 283.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yz-u1H3pD-MMMltusRpLNg_0.JPG: 480x640 (no detections), 289.5ms
Speed: 1.2ms preprocess, 289.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yz-u1H3pD-MMMltusRpLNg_90.JPG: 480x640 (no detections), 318.4ms
Speed: 1.6ms preprocess, 318.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yz-u1H3pD-MMMltusRpLNg_180.JPG: 480x640 (no detections), 311.7ms
Speed: 1.2ms preprocess, 311.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yz-u1H3pD-MMMltusRpLNg_270.JPG: 480x640 (no detections), 292.1ms
Speed: 1.2ms preprocess, 292.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yz2-2XiO5tls3mXYvSGzng_0.JPG: 480x640 (no detections), 298.0ms
Speed: 1.2ms preprocess, 298.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yz2-2XiO5tls3mXYvSGzng_90.JPG: 480x640 (no detections), 290.8ms
Speed: 1.2ms preprocess, 290.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yz2-2XiO5tls3mXYvSGzng_180.JPG: 480x640 (no detections), 279.2ms
Speed: 1.3ms preprocess, 279.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yz2-2XiO5tls3mXYvSGzng_270.JPG: 480x640 (no detections), 308.9ms
Speed: 1.2ms preprocess, 308.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yz6EdSehLge9VBKMhmfayQ_0.JPG: 480x640 (no detections), 277.3ms
Speed: 1.2ms preprocess, 277.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yz6EdSehLge9VBKMhmfayQ_90.JPG: 480x640 (no detections), 289.1ms

Speed: 1.0ms preprocess, 289.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yz6EdSehLge9VBKMhmfayQ_180.JPG: 480x640 (no detections), 314.1ms
Speed: 1.3ms preprocess, 314.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yz6EdSehLge9VBKMhmfayQ_270.JPG: 480x640 (no detections), 284.4ms
Speed: 1.1ms preprocess, 284.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzA6c3CiQb8eVifAGJnmGQ_0.JPG: 480x640 1 Waste, 281.9ms
Speed: 1.1ms preprocess, 281.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzA6c3CiQb8eVifAGJnmGQ_90.JPG: 480x640 (no detections), 286.1ms
Speed: 1.1ms preprocess, 286.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzA6c3CiQb8eVifAGJnmGQ_180.JPG: 480x640 (no detections), 274.5ms
Speed: 1.0ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzA6c3CiQb8eVifAGJnmGQ_270.JPG: 480x640 (no detections), 274.8ms
Speed: 1.1ms preprocess, 274.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzAiUV-6C24qETDvUKmQVw_0.JPG: 480x640 (no detections), 283.6ms
Speed: 1.1ms preprocess, 283.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzAiUV-6C24qETDvUKmQVw_90.JPG: 480x640 (no detections), 281.3ms
Speed: 1.2ms preprocess, 281.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzAiUV-6C24qETDvUKmQVw_180.JPG: 480x640 (no detections), 280.1ms
Speed: 1.2ms preprocess, 280.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzAiUV-6C24qETDvUKmQVw_270.JPG: 480x640 (no detections), 301.0ms
Speed: 1.0ms preprocess, 301.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzBbNSgTcN-vZ_vrTGKNgA_0.JPG: 480x640 (no detections), 288.3ms
Speed: 1.3ms preprocess, 288.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzBbNSgTcN-vZ_vrTGKNgA_90.JPG: 480x640 (no detections), 297.4ms
Speed: 1.1ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzBbNSgTcN-vZ_vrTGKNgA_180.JPG: 480x640 (no detections), 292.8ms
Speed: 1.3ms preprocess, 292.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzBbNSgTcN-vZ_vrTGKNgA_270.JPG: 480x640 (no detections), 283.1ms
Speed: 2.2ms preprocess, 283.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzMXvQ9spkdi5A3Fp3wm6w_0.JPG: 480x640 (no detections), 335.6ms
Speed: 1.1ms preprocess, 335.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzMXvQ9spkdi5A3Fp3wm6w_90.JPG: 480x640 1 Waste, 283.0ms
Speed: 1.1ms preprocess, 283.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzMXvQ9spkdi5A3Fp3wm6w_180.JPG: 480x640 (no detections), 275.7ms
Speed: 1.0ms preprocess, 275.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzMXvQ9spkdi5A3Fp3wm6w_270.JPG: 480x640 (no detections), 279.7ms
Speed: 1.1ms preprocess, 279.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzWy2IHBYnST-WICjcpECg_0.JPG: 480x640 (no detections), 275.7ms
Speed: 1.0ms preprocess, 275.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzWy2IHBYnST-WICjcpECg_90.JPG: 480x640 (no detections), 277.1ms
Speed: 1.2ms preprocess, 277.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzWy2IHBYnST-WICjcpECg_180.JPG: 480x640 (no detections), 275.9ms
Speed: 1.2ms preprocess, 275.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzWy2IHBYnST-WICjcpECg_270.JPG: 480x640 (no detections), 279.2ms
Speed: 1.1ms preprocess, 279.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzX-hXoe8AhoSEuyqNzk3w_0.JPG: 480x640 (no detections), 278.2ms
Speed: 1.2ms preprocess, 278.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzX-hXoe8AhoSEuyqNzk3w_90.JPG: 480x640 (no detections), 283.2ms
Speed: 1.2ms preprocess, 283.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzX-hXoe8AhoSEuyqNzk3w_180.JPG: 480x640 (no detections), 275.3ms
Speed: 1.2ms preprocess, 275.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzX-hXoe8AhoSEuyqNzk3w_270.JPG: 480x640 (no detections), 276.0ms
Speed: 1.1ms preprocess, 276.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzYpOQttwvSdX8dJkyy9Hw_0.JPG: 480x640 (no detections), 277.5ms
Speed: 1.0ms preprocess, 277.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzYpOQttwvSdX8dJkyy9Hw_90.JPG: 480x640 (no detections), 278.3ms
Speed: 1.0ms preprocess, 278.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzYpOQttwvSdX8dJkyy9Hw_180.JPG: 480x640 (no detections), 279.3ms
Speed: 1.1ms preprocess, 279.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzYpOQttwvSdX8dJkyy9Hw_270.JPG: 480x640 (no detections), 279.2ms
Speed: 1.1ms preprocess, 279.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzYplgUoMUtzBei523u5kQ_0.JPG: 480x640 (no detections), 280.5ms
Speed: 1.0ms preprocess, 280.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzYplgUoMUtzBei523u5kQ_90.JPG: 480x640 (no detections), 292.6ms
Speed: 1.1ms preprocess, 292.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzYplgUoMUtzBei523u5kQ_180.JPG: 480x640 (no detections), 290.8ms
Speed: 1.2ms preprocess, 290.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzYplgUoMUtzBei523u5kQ_270.JPG: 480x640 (no detections), 289.6ms
Speed: 1.2ms preprocess, 289.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yz_cCHSzsJGLkS3qCW4sqQ_0.JPG: 480x640 (no detections), 282.4ms
Speed: 1.5ms preprocess, 282.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yz_cCHSzsJGLkS3qCW4sqQ_90.JPG: 480x640 (no detections), 278.6ms
Speed: 1.1ms preprocess, 278.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yz_cCHSzsJGLkS3qCW4sqQ_180.JPG: 480x640 (no detections), 316.1ms
Speed: 1.2ms preprocess, 316.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yz_cCHSzsJGLkS3qCW4sqQ_270.JPG: 480x640 (no detections), 285.2ms
Speed: 1.2ms preprocess, 285.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzb4VhYHjdz6sNY8fuswSw_0.JPG: 480x640 (no detections), 278.3ms
Speed: 1.0ms preprocess, 278.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzb4VhYHjdz6sNY8fuswSw_90.JPG: 480x640 (no detections), 277.9ms
Speed: 1.1ms preprocess, 277.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzb4VhYHjdz6sNY8fuswSw_180.JPG: 480x640 (no detections), 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzb4VhYHjdz6sNY8fuswSw_270.JPG: 480x640 (no detections), 271.5ms
Speed: 1.0ms preprocess, 271.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzbtWi99JPJWghVur74PwA_0.JPG: 480x640 (no detections), 275.6ms
Speed: 1.2ms preprocess, 275.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzbtWi99JPJWghVur74PwA_90.JPG: 480x640 (no detections), 281.0ms
Speed: 1.1ms preprocess, 281.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzbtWi99JPJWghVur74PwA_180.JPG: 480x640 (no detections), 359.6ms
Speed: 1.2ms preprocess, 359.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzbtWi99JPJWghVur74PwA_270.JPG: 480x640 (no detections), 304.7ms
Speed: 1.3ms preprocess, 304.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzdM8YW2cy_cb8cANxxNSw_0.JPG: 480x640 (no detections), 293.9ms
Speed: 1.2ms preprocess, 293.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzdM8YW2cy_cb8cANxxNSw_90.JPG: 480x640 (no detections), 285.9ms
Speed: 1.4ms preprocess, 285.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzdM8YW2cy_cb8cANxxNSw_180.JPG: 480x640 (no detections), 305.1ms
Speed: 1.3ms preprocess, 305.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzdM8YW2cy_cb8cANxxNSw_270.JPG: 480x640 (no detections), 301.2ms
Speed: 1.1ms preprocess, 301.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzg_7qctsfJgK5n4RDzY_w_0.JPG: 480x640 (no detections), 285.5ms
Speed: 1.1ms preprocess, 285.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzg_7qctsfJgK5n4RDzY_w_90.JPG: 480x640 (no detections), 293.3ms
Speed: 1.1ms preprocess, 293.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzg_7qctsfJgK5n4RDzY_w_180.JPG: 480x640 (no detections), 298.8ms
Speed: 1.3ms preprocess, 298.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzg_7qctsfJgK5n4RDzY_w_270.JPG: 480x640 (no detections), 276.5ms
Speed: 1.1ms preprocess, 276.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yziEtBATbQm71ZVEeIxMKw_0.JPG: 480x640 (no detections), 308.0ms
Speed: 1.1ms preprocess, 308.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yziEtBATbQm71ZVEeIxMKw_90.JPG: 480x640 (no detections), 312.8ms
Speed: 1.0ms preprocess, 312.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yziEtBATbQm71ZVEeIxMKw_180.JPG: 480x640 (no detections), 299.6ms
Speed: 1.3ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yziEtBATbQm71ZVEeIxMKw_270.JPG: 480x640 (no detections), 295.4ms
Speed: 1.2ms preprocess, 295.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yziOdvF35pfUSiqZ0metKw_0.JPG: 480x640 (no detections), 315.5ms
Speed: 1.0ms preprocess, 315.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yziOdvF35pfUSiqZ0metKw_90.JPG: 480x640 (no detections), 314.0ms
Speed: 1.1ms preprocess, 314.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yziOdvF35pfUSiqZ0metKw_180.JPG: 480x640 (no detections), 284.1ms
Speed: 1.1ms preprocess, 284.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yziOdvF35pfUSiqZ0metKw_270.JPG: 480x640 (no detections), 287.6ms
Speed: 1.1ms preprocess, 287.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzmJujxxXfjzVWU_iiV7Vw_0.JPG: 480x640 (no detections), 387.7ms
Speed: 1.1ms preprocess, 387.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzmJujxxXfjzVWU_iiV7Vw_90.JPG: 480x640 (no detections), 297.3ms
Speed: 1.2ms preprocess, 297.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzmJujxxXfjzVWU_iiV7Vw_180.JPG: 480x640 (no detections), 289.4ms
Speed: 1.2ms preprocess, 289.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzmJujxxXfjzVWU_iiV7Vw_270.JPG: 480x640 (no detections), 301.5ms
Speed: 1.1ms preprocess, 301.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzrWo2TlEIKL1viinTDP8w_0.JPG: 480x640 (no detections), 283.9ms

Speed: 1.0ms preprocess, 283.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzrWo2TlEIKL1viinTDP8w_90.JPG: 480x640 (no detections), 273.4ms
Speed: 1.1ms preprocess, 273.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzrWo2TlEIKL1viinTDP8w_180.JPG: 480x640 (no detections), 275.9ms
Speed: 1.0ms preprocess, 275.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzrWo2TlEIKL1viinTDP8w_270.JPG: 480x640 1 Waste, 276.3ms
Speed: 1.1ms preprocess, 276.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yztGgRDDYmMN9CeFUY0Iyw_0.JPG: 480x640 (no detections), 274.3ms
Speed: 1.1ms preprocess, 274.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yztGgRDDYmMN9CeFUY0Iyw_90.JPG: 480x640 (no detections), 273.1ms
Speed: 1.0ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yztGgRDDYmMN9CeFUY0Iyw_180.JPG: 480x640 (no detections), 272.6ms
Speed: 1.0ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yztGgRDDYmMN9CeFUY0Iyw_270.JPG: 480x640 (no detections), 274.4ms
Speed: 1.0ms preprocess, 274.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzzTLYDZOU5FdfY60fNhYA_0.JPG: 480x640 (no detections), 273.2ms
Speed: 1.1ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzzTLYDZOU5FdfY60fNhYA_90.JPG: 480x640 (no detections), 325.1ms
Speed: 1.0ms preprocess, 325.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzzTLYDZOU5FdfY60fNhYA_180.JPG: 480x640 (no detections), 304.2ms
Speed: 1.3ms preprocess, 304.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/y/Z/yzzTLYDZOU5FdfY60fNhYA_270.JPG: 480x640 (no detections), 304.9ms
Speed: 1.1ms preprocess, 304.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-3_rj7dAsRyl2e1JknnZw_0.JPG: 480x640 (no detections), 297.3ms
Speed: 1.3ms preprocess, 297.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-3_rj7dAsRyl2e1JknnZw_90.JPG: 480x640 (no detections), 277.7ms
Speed: 1.3ms preprocess, 277.7ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-3_rj7dAsRyl2e1JknnZw_180.JPG: 480x640 (no detections), 415.9ms
Speed: 1.1ms preprocess, 415.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-3_rj7dAsRyl2e1JknnZw_270.JPG: 480x640 (no detections), 612.4ms
Speed: 1.6ms preprocess, 612.4ms inference, 2.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-4KsXzbOK-D1hLOXQbd3g_0.JPG: 480x640 (no detections), 557.9ms
Speed: 4.3ms preprocess, 557.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-4KsXzbOK-D1hLOXQbd3g_90.JPG: 480x640 (no detections), 403.1ms
Speed: 1.4ms preprocess, 403.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-4KsXzbOK-D1hLOXQbd3g_180.JPG: 480x640 (no detections), 286.4ms
Speed: 1.1ms preprocess, 286.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-4KsXzbOK-D1hLOXQbd3g_270.JPG: 480x640 (no detections), 291.8ms
Speed: 1.2ms preprocess, 291.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-4yVW-HZAyO9f6yEvO-GQ_0.JPG: 480x640 (no detections), 296.5ms
Speed: 1.3ms preprocess, 296.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-4yVW-HZAyO9f6yEvO-GQ_90.JPG: 480x640 (no detections), 283.0ms
Speed: 1.2ms preprocess, 283.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-4yVW-HZAyO9f6yEvO-GQ_180.JPG: 480x640 (no detections), 292.1ms
Speed: 1.1ms preprocess, 292.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-4yVW-HZAyO9f6yEvO-GQ_270.JPG: 480x640 (no detections), 290.5ms
Speed: 1.2ms preprocess, 290.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-ABpCEOBMlQZWlzqiLaeQ_0.JPG: 480x640 (no detections), 318.3ms
Speed: 1.3ms preprocess, 318.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-ABpCEOBMlQZWlzqiLaeQ_90.JPG: 480x640 (no detections), 295.8ms
Speed: 1.3ms preprocess, 295.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-ABpCEOBMlQZWlzqiLaeQ_180.JPG: 480x640 (no detections), 291.7ms
Speed: 1.3ms preprocess, 291.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-ABpCEOBMlQZWlzqiLaeQ_270.JPG: 480x640 (no detections), 299.5ms
Speed: 1.1ms preprocess, 299.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-H3GrZ1eWIQa27BfXtJaA_0.JPG: 480x640 (no detections), 292.5ms
Speed: 1.1ms preprocess, 292.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-H3GrZ1eWIQa27BfXtJaA_90.JPG: 480x640 (no detections), 291.8ms
Speed: 1.0ms preprocess, 291.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-H3GrZ1eWIQa27BfXtJaA_180.JPG: 480x640 (no detections), 290.2ms
Speed: 1.3ms preprocess, 290.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-H3GrZ1eWIQa27BfXtJaA_270.JPG: 480x640 (no detections), 284.9ms
Speed: 1.2ms preprocess, 284.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-XVcqSLCMB05ckvIrr_wA_0.JPG: 480x640 (no detections), 286.3ms
Speed: 1.2ms preprocess, 286.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-XVcqSLCMB05ckvIrr_wA_90.JPG: 480x640 (no detections), 303.1ms
Speed: 1.1ms preprocess, 303.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-XVcqSLCMB05ckvIrr_wA_180.JPG: 480x640 (no detections), 299.3ms
Speed: 1.3ms preprocess, 299.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-XVcqSLCMB05ckvIrr_wA_270.JPG: 480x640 1 Waste, 329.6ms
Speed: 1.1ms preprocess, 329.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-YBKM8RCgZNEyr6t2VsUg_0.JPG: 480x640 (no detections), 298.0ms
Speed: 1.2ms preprocess, 298.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-YBKM8RCgZNEyr6t2VsUg_90.JPG: 480x640 (no detections), 286.4ms
Speed: 1.0ms preprocess, 286.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-YBKM8RCgZNEyr6t2VsUg_180.JPG: 480x640 (no detections), 301.4ms
Speed: 1.1ms preprocess, 301.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-YBKM8RCgZNEyr6t2VsUg_270.JPG: 480x640 (no detections), 288.9ms
Speed: 1.0ms preprocess, 288.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-aWH8TEpK-RbdMNVAMvzA_0.JPG: 480x640 (no detections), 291.0ms
Speed: 1.2ms preprocess, 291.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-aWH8TEpK-RbdMNVAMvzA_90.JPG: 480x640 (no detections), 299.1ms
Speed: 1.2ms preprocess, 299.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-aWH8TEpK-RbdMNVAMvzA_180.JPG: 480x640 (no detections), 312.5ms
Speed: 1.1ms preprocess, 312.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-aWH8TEpK-RbdMNVAMvzA_270.JPG: 480x640 (no detections), 301.2ms
Speed: 1.0ms preprocess, 301.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-d-dLLRR4gP6szcIZY5Qg_0.JPG: 480x640 (no detections), 302.6ms
Speed: 1.3ms preprocess, 302.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-d-dLLRR4gP6szcIZY5Qg_90.JPG: 480x640 (no detections), 317.0ms
Speed: 1.4ms preprocess, 317.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-d-dLLRR4gP6szcIZY5Qg_180.JPG: 480x640 (no detections), 309.6ms
Speed: 1.1ms preprocess, 309.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-d-dLLRR4gP6szcIZY5Qg_270.JPG: 480x640 1 Waste, 316.5ms
Speed: 1.1ms preprocess, 316.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-hXGrbulin8TYsXvXXK4g_0.JPG: 480x640 (no detections), 300.2ms
Speed: 1.1ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-hXGrbulin8TYsXvXXK4g_90.JPG: 480x640 (no detections), 319.2ms
Speed: 1.2ms preprocess, 319.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-hXGrbulin8TYsXvXXK4g_180.JPG: 480x640 (no detections), 293.8ms
Speed: 1.0ms preprocess, 293.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-hXGrbulin8TYsXvXXK4g_270.JPG: 480x640 (no detections), 314.5ms
Speed: 1.2ms preprocess, 314.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-jnBP8Tl2yHnSi0tf2aFw_0.JPG: 480x640 (no detections), 307.0ms
Speed: 1.4ms preprocess, 307.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-jnBP8Tl2yHnSi0tf2aFw_90.JPG: 480x640 (no detections), 296.3ms
Speed: 1.4ms preprocess, 296.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-jnBP8Tl2yHnSi0tf2aFw_180.JPG: 480x640 (no detections), 310.6ms
Speed: 1.5ms preprocess, 310.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-jnBP8Tl2yHnSi0tf2aFw_270.JPG: 480x640 (no detections), 322.6ms
Speed: 1.1ms preprocess, 322.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-t8xe7bIzKzy7Df71unvg_0.JPG: 480x640 (no detections), 289.5ms
Speed: 1.3ms preprocess, 289.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-t8xe7bIzKzy7Df71unvg_90.JPG: 480x640 (no detections), 274.7ms
Speed: 1.1ms preprocess, 274.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-t8xe7bIzKzy7Df71unvg_180.JPG: 480x640 (no detections), 280.2ms
Speed: 1.0ms preprocess, 280.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-t8xe7bIzKzy7Df71unvg_270.JPG: 480x640 (no detections), 278.4ms
Speed: 1.1ms preprocess, 278.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-vGhcdUb5eziUm9TYNPTw_0.JPG: 480x640 (no detections), 280.5ms
Speed: 1.1ms preprocess, 280.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-vGhcdUb5eziUm9TYNPTw_90.JPG: 480x640 (no detections), 275.7ms
Speed: 1.2ms preprocess, 275.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-vGhcdUb5eziUm9TYNPTw_180.JPG: 480x640 (no detections), 295.2ms
Speed: 1.2ms preprocess, 295.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-vGhcdUb5eziUm9TYNPTw_270.JPG: 480x640 (no detections), 273.2ms
Speed: 1.1ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-w1oCL5kBbhGO7PBgiCEw_0.JPG: 480x640 (no detections), 279.0ms
Speed: 1.1ms preprocess, 279.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-w1oCL5kBbhGO7PBgiCEw_90.JPG: 480x640 (no detections), 275.0ms
Speed: 1.1ms preprocess, 275.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-w1oCL5kBbhGO7PBgiCEw_180.JPG: 480x640 (no detections), 287.5ms
Speed: 1.1ms preprocess, 287.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-w1oCL5kBbhGO7PBgiCEw_270.JPG: 480x640 (no detections), 295.6ms

Speed: 1.1ms preprocess, 295.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-wd0KTa-NuZqPmJN37V7w_0.JPG: 480x640 (no detections), 285.4ms
Speed: 1.1ms preprocess, 285.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-wd0KTa-NuZqPmJN37V7w_90.JPG: 480x640 (no detections), 286.5ms
Speed: 1.0ms preprocess, 286.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-wd0KTa-NuZqPmJN37V7w_180.JPG: 480x640 (no detections), 297.7ms
Speed: 1.5ms preprocess, 297.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-wd0KTa-NuZqPmJN37V7w_270.JPG: 480x640 (no detections), 293.7ms
Speed: 1.4ms preprocess, 293.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-ycVgMTI4_5I0fJ16VwZA_0.JPG: 480x640 (no detections), 306.8ms
Speed: 1.1ms preprocess, 306.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-ycVgMTI4_5I0fJ16VwZA_90.JPG: 480x640 (no detections), 294.9ms
Speed: 1.1ms preprocess, 294.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-ycVgMTI4_5I0fJ16VwZA_180.JPG: 480x640 (no detections), 294.2ms
Speed: 1.2ms preprocess, 294.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-ycVgMTI4_5I0fJ16VwZA_270.JPG: 480x640 (no detections), 277.1ms
Speed: 1.0ms preprocess, 277.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-zF-nFj_8XQmZJXvyjoyg_0.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-zF-nFj_8XQmZJXvyjoyg_90.JPG: 480x640 (no detections), 303.1ms
Speed: 1.0ms preprocess, 303.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-zF-nFj_8XQmZJXvyjoyg_180.JPG: 480x640 (no detections), 376.7ms
Speed: 2.2ms preprocess, 376.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/-/z-zF-nFj_8XQmZJXvyjoyg_270.JPG: 480x640 (no detections), 381.8ms
Speed: 1.3ms preprocess, 381.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z02eG53kwNLFnrDT1hGFHA_0.JPG: 480x640 (no detections), 353.0ms
Speed: 1.7ms preprocess, 353.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z02eG53kwNLFnrDT1hGFHA_90.JPG: 480x640 (no detections), 353.4ms
Speed: 1.2ms preprocess, 353.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z02eG53kwNLFnrDT1hGFHA_180.JPG: 480x640 (no detections), 285.0ms
Speed: 1.2ms preprocess, 285.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z02eG53kwNLFnrDT1hGFHA_270.JPG: 480x640 (no detections), 272.1ms
Speed: 1.2ms preprocess, 272.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z04dOtZrjkf9jKPdYvxpsw_0.JPG: 480x640 (no detections), 281.9ms
Speed: 1.0ms preprocess, 281.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z04dOtZrjkf9jKPdYvxpsw_90.JPG: 480x640 (no detections), 281.1ms
Speed: 1.5ms preprocess, 281.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z04dOtZrjkf9jKPdYvxpsw_180.JPG: 480x640 (no detections), 275.8ms
Speed: 1.1ms preprocess, 275.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z04dOtZrjkf9jKPdYvxpsw_270.JPG: 480x640 (no detections), 290.0ms
Speed: 1.1ms preprocess, 290.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z04olRDfWEj3kC0WcaIu2A_0.JPG: 480x640 (no detections), 276.5ms
Speed: 1.1ms preprocess, 276.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z04olRDfWEj3kC0WcaIu2A_90.JPG: 480x640 (no detections), 274.6ms
Speed: 1.0ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z04olRDfWEj3kC0WcaIu2A_180.JPG: 480x640 (no detections), 277.3ms
Speed: 1.1ms preprocess, 277.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z04olRDfWEj3kC0WcaIu2A_270.JPG: 480x640 (no detections), 273.4ms
Speed: 1.2ms preprocess, 273.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z08V8afP6i7GjWYRxjKyWQ_0.JPG: 480x640 (no detections), 313.7ms
Speed: 1.1ms preprocess, 313.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z08V8afP6i7GjWYRxjKyWQ_90.JPG: 480x640 (no detections), 276.4ms
Speed: 1.0ms preprocess, 276.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z08V8afP6i7GjWYRxjKyWQ_180.JPG: 480x640 (no detections), 288.2ms
Speed: 1.0ms preprocess, 288.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z08V8afP6i7GjWYRxjKyWQ_270.JPG: 480x640 (no detections), 283.7ms
Speed: 1.3ms preprocess, 283.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0BKh2ljAlLJYsr-EBjB4A_0.JPG: 480x640 (no detections), 272.3ms
Speed: 1.1ms preprocess, 272.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0BKh2ljAlLJYsr-EBjB4A_90.JPG: 480x640 (no detections), 274.5ms
Speed: 1.2ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0BKh2ljAlLJYsr-EBjB4A_180.JPG: 480x640 (no detections), 296.5ms
Speed: 1.1ms preprocess, 296.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0BKh2ljAlLJYsr-EBjB4A_270.JPG: 480x640 1 Waste, 276.0ms
Speed: 1.1ms preprocess, 276.0ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0C2yeNPBLWkBHMRaM-WXA_0.JPG: 480x640 (no detections), 273.3ms
Speed: 1.2ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0C2yeNPBLWkBHMRaM-WXA_90.JPG: 480x640 (no detections), 303.5ms
Speed: 1.2ms preprocess, 303.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0C2yeNPBLWkBHMRaM-WXA_180.JPG: 480x640 (no detections), 283.8ms
Speed: 1.2ms preprocess, 283.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0C2yeNPBLWkBHMRaM-WXA_270.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0E1mV7ROq5yOKbPOAb6qQ_0.JPG: 480x640 (no detections), 276.0ms
Speed: 1.1ms preprocess, 276.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0E1mV7ROq5yOKbPOAb6qQ_90.JPG: 480x640 (no detections), 273.1ms
Speed: 1.1ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0E1mV7ROq5yOKbPOAb6qQ_180.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0E1mV7ROq5yOKbPOAb6qQ_270.JPG: 480x640 (no detections), 292.9ms
Speed: 1.2ms preprocess, 292.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0IxPqbjTYo-1MeNRetYsQ_0.JPG: 480x640 (no detections), 274.6ms
Speed: 1.1ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0IxPqbjTYo-1MeNRetYsQ_90.JPG: 480x640 (no detections), 282.8ms
Speed: 1.1ms preprocess, 282.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0IxPqbjTYo-1MeNRetYsQ_180.JPG: 480x640 (no detections), 280.8ms
Speed: 1.1ms preprocess, 280.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0IxPqbjTYo-1MeNRetYsQ_270.JPG: 480x640 (no detections), 305.3ms
Speed: 1.3ms preprocess, 305.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0J1roL3hj6l19LWHxFHvQ_0.JPG: 480x640 (no detections), 286.0ms
Speed: 1.2ms preprocess, 286.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0J1roL3hj6l19LWHxFHvQ_90.JPG: 480x640 (no detections), 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0J1roL3hj6l19LWHxFHvQ_180.JPG: 480x640 (no detections), 283.7ms
Speed: 1.0ms preprocess, 283.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0J1roL3hj6l19LWHxFHvQ_270.JPG: 480x640 (no detections), 401.3ms
Speed: 1.0ms preprocess, 401.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0KyISWE7Mo2L0qr8WPPrg_0.JPG: 480x640 (no detections), 295.5ms
Speed: 1.2ms preprocess, 295.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0KyISWE7Mo2L0qr8WPPrg_90.JPG: 480x640 (no detections), 280.3ms
Speed: 1.4ms preprocess, 280.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0KyISWE7Mo2L0qr8WPPrg_180.JPG: 480x640 (no detections), 267.7ms
Speed: 1.1ms preprocess, 267.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0KyISWE7Mo2L0qr8WPPrg_270.JPG: 480x640 (no detections), 269.2ms
Speed: 1.1ms preprocess, 269.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0M2mAjlwl6NnNzijLxUPA_0.JPG: 480x640 (no detections), 270.6ms
Speed: 1.0ms preprocess, 270.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0M2mAjlwl6NnNzijLxUPA_90.JPG: 480x640 (no detections), 270.3ms
Speed: 1.1ms preprocess, 270.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0M2mAjlwl6NnNzijLxUPA_180.JPG: 480x640 (no detections), 270.9ms
Speed: 1.0ms preprocess, 270.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0M2mAjlwl6NnNzijLxUPA_270.JPG: 480x640 (no detections), 277.8ms
Speed: 1.1ms preprocess, 277.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0MK877Zve2j9jg0OKZVmg_0.JPG: 480x640 (no detections), 323.5ms
Speed: 1.3ms preprocess, 323.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0MK877Zve2j9jg0OKZVmg_90.JPG: 480x640 (no detections), 299.3ms
Speed: 1.1ms preprocess, 299.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0MK877Zve2j9jg0OKZVmg_180.JPG: 480x640 (no detections), 306.1ms
Speed: 1.1ms preprocess, 306.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0MK877Zve2j9jg0OKZVmg_270.JPG: 480x640 (no detections), 390.6ms
Speed: 1.4ms preprocess, 390.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0MLmgoFLGM5pny4vEXiLw_0.JPG: 480x640 (no detections), 334.5ms
Speed: 2.2ms preprocess, 334.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0MLmgoFLGM5pny4vEXiLw_90.JPG: 480x640 (no detections), 347.4ms
Speed: 1.0ms preprocess, 347.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0MLmgoFLGM5pny4vEXiLw_180.JPG: 480x640 (no detections), 344.1ms
Speed: 1.4ms preprocess, 344.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0MLmgoFLGM5pny4vEXiLw_270.JPG: 480x640 (no detections), 603.7ms
Speed: 1.3ms preprocess, 603.7ms inference, 1.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0OII-352wzijj0a9cTeHg_0.JPG: 480x640 (no detections), 449.6ms
Speed: 1.4ms preprocess, 449.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0OII-352wzijj0a9cTeHg_90.JPG: 480x640 (no detections), 401.5ms
Speed: 2.0ms preprocess, 401.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0OII-352wzijj0a9cTeHg_180.JPG: 480x640 (no detections), 505.2ms

Speed: 2.0ms preprocess, 505.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0OII-352wzijj0a9cTeHg_270.JPG: 480x640 (no detections), 318.8ms
Speed: 1.2ms preprocess, 318.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0ZjnBDHBGTciXCPDq5Ywg_0.JPG: 480x640 (no detections), 292.6ms
Speed: 1.1ms preprocess, 292.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0ZjnBDHBGTciXCPDq5Ywg_90.JPG: 480x640 (no detections), 304.6ms
Speed: 1.4ms preprocess, 304.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0ZjnBDHBGTciXCPDq5Ywg_180.JPG: 480x640 (no detections), 287.4ms
Speed: 1.1ms preprocess, 287.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0ZjnBDHBGTciXCPDq5Ywg_270.JPG: 480x640 (no detections), 282.0ms
Speed: 1.2ms preprocess, 282.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0cW5sOMMp_UDr6D8_zxQQ_0.JPG: 480x640 (no detections), 274.0ms
Speed: 1.2ms preprocess, 274.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0cW5sOMMp_UDr6D8_zxQQ_90.JPG: 480x640 (no detections), 393.1ms
Speed: 1.1ms preprocess, 393.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0cW5sOMMp_UDr6D8_zxQQ_180.JPG: 480x640 (no detections), 276.4ms
Speed: 1.1ms preprocess, 276.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0cW5sOMMp_UDr6D8_zxQQ_270.JPG: 480x640 (no detections), 284.8ms
Speed: 1.0ms preprocess, 284.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0eTEFwR2zCKvFl_7HmB3w_0.JPG: 480x640 (no detections), 306.3ms
Speed: 1.2ms preprocess, 306.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0eTEFwR2zCKvFl_7HmB3w_90.JPG: 480x640 (no detections), 326.7ms
Speed: 1.3ms preprocess, 326.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0eTEFwR2zCKvFl_7HmB3w_180.JPG: 480x640 (no detections), 346.1ms
Speed: 1.8ms preprocess, 346.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0eTEFwR2zCKvFl_7HmB3w_270.JPG: 480x640 (no detections), 293.5ms
Speed: 1.4ms preprocess, 293.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0fdGUNBVZi45BO2Mo3Vqw_0.JPG: 480x640 (no detections), 274.4ms
Speed: 1.3ms preprocess, 274.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0fdGUNBVZi45BO2Mo3Vqw_90.JPG: 480x640 (no detections), 274.4ms
Speed: 1.0ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0fdGUNBVZi45BO2Mo3Vqw_180.JPG: 480x640 (no detections), 283.6ms
Speed: 1.1ms preprocess, 283.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0fdGUNBVZi45BO2Mo3Vqw_270.JPG: 480x640 (no detections), 280.7ms
Speed: 1.3ms preprocess, 280.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0jO08sx8Qu458An7fcX5g_0.JPG: 480x640 (no detections), 306.4ms
Speed: 1.1ms preprocess, 306.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0jO08sx8Qu458An7fcX5g_90.JPG: 480x640 (no detections), 282.0ms
Speed: 1.0ms preprocess, 282.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0jO08sx8Qu458An7fcX5g_180.JPG: 480x640 (no detections), 293.5ms
Speed: 1.3ms preprocess, 293.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0jO08sx8Qu458An7fcX5g_270.JPG: 480x640 (no detections), 269.9ms
Speed: 1.2ms preprocess, 269.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0jyJc8pX4RCIGEBb8kyRA_0.JPG: 480x640 (no detections), 269.2ms
Speed: 1.1ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0jyJc8pX4RCIGEBb8kyRA_90.JPG: 480x640 (no detections), 274.5ms
Speed: 1.1ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0jyJc8pX4RCIGEBb8kyRA_180.JPG: 480x640 (no detections), 272.8ms
Speed: 1.0ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0jyJc8pX4RCIGEBb8kyRA_270.JPG: 480x640 (no detections), 270.3ms
Speed: 1.1ms preprocess, 270.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0uuWCS6930A6dV3WxYPEA_0.JPG: 480x640 (no detections), 267.1ms
Speed: 1.2ms preprocess, 267.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0uuWCS6930A6dV3WxYPEA_90.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0uuWCS6930A6dV3WxYPEA_180.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0uuWCS6930A6dV3WxYPEA_270.JPG: 480x640 (no detections), 286.8ms
Speed: 1.0ms preprocess, 286.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0v_56JrhIRmY18xBpY53Q_0.JPG: 480x640 (no detections), 297.4ms
Speed: 1.3ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0v_56JrhIRmY18xBpY53Q_90.JPG: 480x640 (no detections), 308.1ms
Speed: 1.2ms preprocess, 308.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0v_56JrhIRmY18xBpY53Q_180.JPG: 480x640 (no detections), 292.7ms
Speed: 2.4ms preprocess, 292.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0v_56JrhIRmY18xBpY53Q_270.JPG: 480x640 1 Waste, 298.9ms
Speed: 1.5ms preprocess, 298.9ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0viz7-I7SHIU80IFoNAmA_0.JPG: 480x640 1 Waste, 277.2ms
Speed: 1.0ms preprocess, 277.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0viz7-I7SHIU80IFoNAmA_90.JPG: 480x640 2 Wastes, 278.1ms
Speed: 1.2ms preprocess, 278.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0viz7-I7SHIU80IFoNAmA_180.JPG: 480x640 (no detections), 278.5ms
Speed: 1.0ms preprocess, 278.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0viz7-I7SHIU80IFoNAmA_270.JPG: 480x640 (no detections), 268.6ms
Speed: 1.1ms preprocess, 268.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0yQyCK_PjojKFqP0-mtRA_0.JPG: 480x640 (no detections), 276.6ms
Speed: 1.0ms preprocess, 276.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0yQyCK_PjojKFqP0-mtRA_90.JPG: 480x640 (no detections), 273.1ms
Speed: 1.1ms preprocess, 273.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0yQyCK_PjojKFqP0-mtRA_180.JPG: 480x640 (no detections), 270.9ms
Speed: 1.0ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/0/z0yQyCK_PjojKFqP0-mtRA_270.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z13jSZe8wure03Ubx9MD6A_0.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z13jSZe8wure03Ubx9MD6A_90.JPG: 480x640 (no detections), 277.3ms
Speed: 1.0ms preprocess, 277.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z13jSZe8wure03Ubx9MD6A_180.JPG: 480x640 (no detections), 271.0ms
Speed: 1.0ms preprocess, 271.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z13jSZe8wure03Ubx9MD6A_270.JPG: 480x640 (no detections), 293.4ms
Speed: 1.1ms preprocess, 293.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z14j_W5IWc526KPljQRZZQ_0.JPG: 480x640 (no detections), 293.2ms
Speed: 1.1ms preprocess, 293.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z14j_W5IWc526KPljQRZZQ_90.JPG: 480x640 1 Waste, 290.7ms
Speed: 1.1ms preprocess, 290.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z14j_W5IWc526KPljQRZZQ_180.JPG: 480x640 (no detections), 278.5ms
Speed: 1.2ms preprocess, 278.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z14j_W5IWc526KPljQRZZQ_270.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z15iq8WfsrndocUMe0bh9A_0.JPG: 480x640 (no detections), 276.1ms
Speed: 1.0ms preprocess, 276.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z15iq8WfsrndocUMe0bh9A_90.JPG: 480x640 (no detections), 279.3ms
Speed: 1.2ms preprocess, 279.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z15iq8WfsrndocUMe0bh9A_180.JPG: 480x640 (no detections), 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z15iq8WfsrndocUMe0bh9A_270.JPG: 480x640 (no detections), 280.9ms
Speed: 1.1ms preprocess, 280.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1BrRe-gbaf8ypGwGX8jsQ_0.JPG: 480x640 (no detections), 274.4ms
Speed: 1.1ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1BrRe-gbaf8ypGwGX8jsQ_90.JPG: 480x640 (no detections), 272.1ms
Speed: 1.2ms preprocess, 272.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1BrRe-gbaf8ypGwGX8jsQ_180.JPG: 480x640 (no detections), 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1BrRe-gbaf8ypGwGX8jsQ_270.JPG: 480x640 (no detections), 273.1ms
Speed: 1.0ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1DDsS2tg4S-hcPeaqA2cA_0.JPG: 480x640 (no detections), 283.5ms
Speed: 1.1ms preprocess, 283.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1DDsS2tg4S-hcPeaqA2cA_90.JPG: 480x640 (no detections), 471.9ms
Speed: 3.5ms preprocess, 471.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1DDsS2tg4S-hcPeaqA2cA_180.JPG: 480x640 (no detections), 340.9ms
Speed: 1.3ms preprocess, 340.9ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1DDsS2tg4S-hcPeaqA2cA_270.JPG: 480x640 (no detections), 746.7ms
Speed: 1.0ms preprocess, 746.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1DIkq3nLyVD2dGL0LFnNA_0.JPG: 480x640 (no detections), 370.5ms
Speed: 1.4ms preprocess, 370.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1DIkq3nLyVD2dGL0LFnNA_90.JPG: 480x640 (no detections), 374.2ms
Speed: 1.1ms preprocess, 374.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1DIkq3nLyVD2dGL0LFnNA_180.JPG: 480x640 (no detections), 380.8ms
Speed: 1.3ms preprocess, 380.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1DIkq3nLyVD2dGL0LFnNA_270.JPG: 480x640 (no detections), 416.3ms
Speed: 1.4ms preprocess, 416.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1GqmNc7yqyYjgmKyDT7pw_0.JPG: 480x640 (no detections), 280.9ms
Speed: 1.4ms preprocess, 280.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1GqmNc7yqyYjgmKyDT7pw_90.JPG: 480x640 (no detections), 272.0ms

Speed: 1.2ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1GqmNc7yqyYjgmKyDT7pw_180.JPG: 480x640 (no detections), 270.5ms
Speed: 1.1ms preprocess, 270.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1GqmNc7yqyYjgmKyDT7pw_270.JPG: 480x640 (no detections), 275.6ms
Speed: 1.0ms preprocess, 275.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1HJJWk2ZLPDFEUF6m_v6A_0.JPG: 480x640 (no detections), 275.4ms
Speed: 1.1ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1HJJWk2ZLPDFEUF6m_v6A_90.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1HJJWk2ZLPDFEUF6m_v6A_180.JPG: 480x640 (no detections), 273.2ms
Speed: 1.0ms preprocess, 273.2ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1HJJWk2ZLPDFEUF6m_v6A_270.JPG: 480x640 (no detections), 290.8ms
Speed: 1.3ms preprocess, 290.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1Hqmuq8VYMzd5DeRQ4B8A_0.JPG: 480x640 (no detections), 266.7ms
Speed: 1.2ms preprocess, 266.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1Hqmuq8VYMzd5DeRQ4B8A_90.JPG: 480x640 (no detections), 264.8ms
Speed: 1.0ms preprocess, 264.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1Hqmuq8VYMzd5DeRQ4B8A_180.JPG: 480x640 (no detections), 268.3ms
Speed: 1.0ms preprocess, 268.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1Hqmuq8VYMzd5DeRQ4B8A_270.JPG: 480x640 1 Waste, 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1J76n2wata678Od1fOD5A_0.JPG: 480x640 (no detections), 272.5ms
Speed: 1.1ms preprocess, 272.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1J76n2wata678Od1fOD5A_90.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1J76n2wata678Od1fOD5A_180.JPG: 480x640 (no detections), 271.4ms
Speed: 1.0ms preprocess, 271.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1J76n2wata678Od1fOD5A_270.JPG: 480x640 (no detections), 290.8ms
Speed: 1.1ms preprocess, 290.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1PmM1jwVe7rpsQdP-tp2g_0.JPG: 480x640 (no detections), 275.5ms
Speed: 1.0ms preprocess, 275.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1PmM1jwVe7rpsQdP-tp2g_90.JPG: 480x640 (no detections), 282.9ms
Speed: 1.2ms preprocess, 282.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1PmM1jwVe7rpsQdP-tp2g_180.JPG: 480x640 (no detections), 279.5ms
Speed: 1.2ms preprocess, 279.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1PmM1jwVe7rpsQdP-tp2g_270.JPG: 480x640 (no detections), 286.4ms
Speed: 1.1ms preprocess, 286.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1R29ifRYHfsatE3suHkCw_0.JPG: 480x640 (no detections), 283.5ms
Speed: 1.1ms preprocess, 283.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1R29ifRYHfsatE3suHkCw_90.JPG: 480x640 (no detections), 271.8ms
Speed: 1.2ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1R29ifRYHfsatE3suHkCw_180.JPG: 480x640 (no detections), 286.2ms
Speed: 1.1ms preprocess, 286.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1R29ifRYHfsatE3suHkCw_270.JPG: 480x640 (no detections), 275.4ms
Speed: 1.1ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1Tt2JNZGwDTSjmv8i7n-g_0.JPG: 480x640 (no detections), 270.6ms
Speed: 1.2ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1Tt2JNZGwDTSjmv8i7n-g_90.JPG: 480x640 (no detections), 274.5ms
Speed: 1.0ms preprocess, 274.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1Tt2JNZGwDTSjmv8i7n-g_180.JPG: 480x640 (no detections), 269.3ms
Speed: 1.1ms preprocess, 269.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1Tt2JNZGwDTSjmv8i7n-g_270.JPG: 480x640 (no detections), 282.9ms
Speed: 1.0ms preprocess, 282.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1UVAo5pXCZbMEUF8TRYYQ_0.JPG: 480x640 (no detections), 302.8ms
Speed: 1.5ms preprocess, 302.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1UVAo5pXCZbMEUF8TRYYQ_90.JPG: 480x640 (no detections), 275.7ms
Speed: 1.0ms preprocess, 275.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1UVAo5pXCZbMEUF8TRYYQ_180.JPG: 480x640 (no detections), 280.1ms
Speed: 1.0ms preprocess, 280.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1UVAo5pXCZbMEUF8TRYYQ_270.JPG: 480x640 (no detections), 277.1ms
Speed: 1.2ms preprocess, 277.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1V45k1bifBqQtEop1jwFw_0.JPG: 480x640 (no detections), 276.0ms
Speed: 1.1ms preprocess, 276.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1V45k1bifBqQtEop1jwFw_90.JPG: 480x640 (no detections), 271.9ms
Speed: 1.0ms preprocess, 271.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1V45k1bifBqQtEop1jwFw_180.JPG: 480x640 (no detections), 271.8ms
Speed: 1.0ms preprocess, 271.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1V45k1bifBqQtEop1jwFw_270.JPG: 480x640 (no detections), 356.3ms
Speed: 1.0ms preprocess, 356.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1XdXVCmcWX0WjBxwhAh6Q_0.JPG: 480x640 (no detections), 298.8ms
Speed: 1.1ms preprocess, 298.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1XdXVCmcWX0WjBxwhAh6Q_90.JPG: 480x640 (no detections), 317.5ms
Speed: 1.5ms preprocess, 317.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1XdXVCmcWX0WjBxwhAh6Q_180.JPG: 480x640 (no detections), 336.1ms
Speed: 1.8ms preprocess, 336.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1XdXVCmcWX0WjBxwhAh6Q_270.JPG: 480x640 (no detections), 309.4ms
Speed: 1.7ms preprocess, 309.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1ddYKuFR5A8t5jmWx1FPQ_0.JPG: 480x640 (no detections), 299.4ms
Speed: 1.1ms preprocess, 299.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1ddYKuFR5A8t5jmWx1FPQ_90.JPG: 480x640 (no detections), 394.2ms
Speed: 1.2ms preprocess, 394.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1ddYKuFR5A8t5jmWx1FPQ_180.JPG: 480x640 (no detections), 316.3ms
Speed: 1.3ms preprocess, 316.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1ddYKuFR5A8t5jmWx1FPQ_270.JPG: 480x640 (no detections), 334.5ms
Speed: 1.2ms preprocess, 334.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1fPxxedHvcz7PFdVC2WeQ_0.JPG: 480x640 (no detections), 299.6ms
Speed: 1.2ms preprocess, 299.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1fPxxedHvcz7PFdVC2WeQ_90.JPG: 480x640 (no detections), 286.1ms
Speed: 1.1ms preprocess, 286.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1fPxxedHvcz7PFdVC2WeQ_180.JPG: 480x640 (no detections), 278.7ms
Speed: 1.1ms preprocess, 278.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1fPxxedHvcz7PFdVC2WeQ_270.JPG: 480x640 (no detections), 277.2ms
Speed: 1.0ms preprocess, 277.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1fVsa29K_xxjF97BB4RIA_0.JPG: 480x640 (no detections), 282.0ms
Speed: 1.0ms preprocess, 282.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1fVsa29K_xxjF97BB4RIA_90.JPG: 480x640 (no detections), 344.1ms
Speed: 1.4ms preprocess, 344.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1fVsa29K_xxjF97BB4RIA_180.JPG: 480x640 1 Waste, 282.4ms
Speed: 1.0ms preprocess, 282.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1fVsa29K_xxjF97BB4RIA_270.JPG: 480x640 (no detections), 283.4ms
Speed: 1.1ms preprocess, 283.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1jOeWcgWDNFsIMIMFTPzw_0.JPG: 480x640 (no detections), 276.6ms
Speed: 1.1ms preprocess, 276.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1jOeWcgWDNFsIMIMFTPzw_90.JPG: 480x640 (no detections), 279.4ms
Speed: 1.2ms preprocess, 279.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1jOeWcgWDNFsIMIMFTPzw_180.JPG: 480x640 (no detections), 293.2ms
Speed: 1.0ms preprocess, 293.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1jOeWcgWDNFsIMIMFTPzw_270.JPG: 480x640 (no detections), 289.6ms
Speed: 1.0ms preprocess, 289.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1l2LfoDFtioMxMIQYDI0A_0.JPG: 480x640 (no detections), 281.4ms
Speed: 1.0ms preprocess, 281.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1l2LfoDFtioMxMIQYDI0A_90.JPG: 480x640 (no detections), 297.5ms
Speed: 1.1ms preprocess, 297.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1l2LfoDFtioMxMIQYDI0A_180.JPG: 480x640 (no detections), 289.6ms
Speed: 1.5ms preprocess, 289.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1l2LfoDFtioMxMIQYDI0A_270.JPG: 480x640 (no detections), 277.8ms
Speed: 1.1ms preprocess, 277.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1lUm4gmgx-C7QfZ28CXSg_0.JPG: 480x640 (no detections), 275.9ms
Speed: 1.2ms preprocess, 275.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1lUm4gmgx-C7QfZ28CXSg_90.JPG: 480x640 (no detections), 277.7ms
Speed: 1.1ms preprocess, 277.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1lUm4gmgx-C7QfZ28CXSg_180.JPG: 480x640 (no detections), 342.9ms
Speed: 1.0ms preprocess, 342.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1lUm4gmgx-C7QfZ28CXSg_270.JPG: 480x640 (no detections), 285.9ms
Speed: 1.0ms preprocess, 285.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1lzo8TDH8S-KF-GPsFFBw_0.JPG: 480x640 (no detections), 276.4ms
Speed: 1.2ms preprocess, 276.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1lzo8TDH8S-KF-GPsFFBw_90.JPG: 480x640 (no detections), 279.6ms
Speed: 1.2ms preprocess, 279.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1lzo8TDH8S-KF-GPsFFBw_180.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1lzo8TDH8S-KF-GPsFFBw_270.JPG: 480x640 (no detections), 275.2ms
Speed: 1.0ms preprocess, 275.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1pIrPOcnN_xde2CZf0FGw_0.JPG: 480x640 (no detections), 275.5ms

Speed: 1.1ms preprocess, 275.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1pIrPOcnN_xde2CZf0FGw_90.JPG: 480x640 (no detections), 272.4ms
Speed: 1.1ms preprocess, 272.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1pIrPOcnN_xde2CZf0FGw_180.JPG: 480x640 (no detections), 276.8ms
Speed: 1.1ms preprocess, 276.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1pIrPOcnN_xde2CZf0FGw_270.JPG: 480x640 (no detections), 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1pmSbxZ3BxANKJrOIVHtA_0.JPG: 480x640 (no detections), 285.3ms
Speed: 1.2ms preprocess, 285.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1pmSbxZ3BxANKJrOIVHtA_90.JPG: 480x640 (no detections), 287.7ms
Speed: 1.5ms preprocess, 287.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1pmSbxZ3BxANKJrOIVHtA_180.JPG: 480x640 (no detections), 287.1ms
Speed: 1.4ms preprocess, 287.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1pmSbxZ3BxANKJrOIVHtA_270.JPG: 480x640 (no detections), 339.5ms
Speed: 1.2ms preprocess, 339.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1q8WrHnwVm6wJWRf8Aibg_0.JPG: 480x640 (no detections), 287.5ms
Speed: 1.1ms preprocess, 287.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1q8WrHnwVm6wJWRf8Aibg_90.JPG: 480x640 (no detections), 277.5ms
Speed: 1.1ms preprocess, 277.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1q8WrHnwVm6wJWRf8Aibg_180.JPG: 480x640 (no detections), 277.2ms
Speed: 1.0ms preprocess, 277.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1q8WrHnwVm6wJWRf8Aibg_270.JPG: 480x640 (no detections), 277.6ms
Speed: 1.2ms preprocess, 277.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1rgKZdgMioDmdOv5886_g_0.JPG: 480x640 2 Wastes, 274.7ms
Speed: 1.1ms preprocess, 274.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1rgKZdgMioDmdOv5886_g_90.JPG: 480x640 (no detections), 277.1ms
Speed: 1.2ms preprocess, 277.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1rgKZdgMioDmdOv5886_g_180.JPG: 480x640 (no detections), 268.6ms
Speed: 1.3ms preprocess, 268.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1rgKZdgMioDmdOv5886_g_270.JPG: 480x640 (no detections), 346.7ms
Speed: 1.3ms preprocess, 346.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1sds_Vh8Q__ULmXSWrt0Q_0.JPG: 480x640 (no detections), 284.9ms
Speed: 1.1ms preprocess, 284.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1sds_Vh8Q__ULmXSWrt0Q_90.JPG: 480x640 (no detections), 277.8ms
Speed: 1.2ms preprocess, 277.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1sds_Vh8Q__ULmXSWrt0Q_180.JPG: 480x640 (no detections), 311.6ms
Speed: 1.0ms preprocess, 311.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1sds_Vh8Q__ULmXSWrt0Q_270.JPG: 480x640 (no detections), 286.1ms
Speed: 1.2ms preprocess, 286.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1ul727hHohflaZt-HSFNA_0.JPG: 480x640 (no detections), 290.2ms
Speed: 1.0ms preprocess, 290.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1ul727hHohflaZt-HSFNA_90.JPG: 480x640 (no detections), 301.2ms
Speed: 1.5ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1ul727hHohflaZt-HSFNA_180.JPG: 480x640 (no detections), 309.7ms
Speed: 1.3ms preprocess, 309.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1ul727hHohflaZt-HSFNA_270.JPG: 480x640 (no detections), 308.3ms
Speed: 1.2ms preprocess, 308.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1vqaEu172_lG7-F73lrbg_0.JPG: 480x640 (no detections), 301.1ms
Speed: 1.1ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1vqaEu172_lG7-F73lrbg_90.JPG: 480x640 (no detections), 293.1ms
Speed: 1.0ms preprocess, 293.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1vqaEu172_lG7-F73lrbg_180.JPG: 480x640 (no detections), 281.3ms
Speed: 1.4ms preprocess, 281.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1vqaEu172_lG7-F73lrbg_270.JPG: 480x640 (no detections), 311.4ms
Speed: 1.1ms preprocess, 311.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1xpFpNv6V0QsZFzcnlRpA_0.JPG: 480x640 (no detections), 406.7ms
Speed: 1.2ms preprocess, 406.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1xpFpNv6V0QsZFzcnlRpA_90.JPG: 480x640 (no detections), 334.6ms
Speed: 1.1ms preprocess, 334.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1xpFpNv6V0QsZFzcnlRpA_180.JPG: 480x640 (no detections), 335.6ms
Speed: 1.2ms preprocess, 335.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/1/z1xpFpNv6V0QsZFzcnlRpA_270.JPG: 480x640 (no detections), 322.8ms
Speed: 1.1ms preprocess, 322.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z21wSKIkPGkvLms2W0vu0Q_0.JPG: 480x640 (no detections), 316.4ms
Speed: 1.2ms preprocess, 316.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z21wSKIkPGkvLms2W0vu0Q_90.JPG: 480x640 (no detections), 295.2ms
Speed: 1.3ms preprocess, 295.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z21wSKIkPGkvLms2W0vu0Q_180.JPG: 480x640 (no detections), 289.4ms
Speed: 1.5ms preprocess, 289.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z21wSKIkPGkvLms2W0vu0Q_270.JPG: 480x640 (no detections), 288.0ms
Speed: 1.4ms preprocess, 288.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z28Amk8AoXECnTHjqI63fg_0.JPG: 480x640 (no detections), 277.4ms
Speed: 1.1ms preprocess, 277.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z28Amk8AoXECnTHjqI63fg_90.JPG: 480x640 (no detections), 276.1ms
Speed: 1.0ms preprocess, 276.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z28Amk8AoXECnTHjqI63fg_180.JPG: 480x640 (no detections), 277.5ms
Speed: 1.2ms preprocess, 277.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z28Amk8AoXECnTHjqI63fg_270.JPG: 480x640 (no detections), 279.1ms
Speed: 1.1ms preprocess, 279.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2AXNDYoDuWInBNMmeX3Sw_0.JPG: 480x640 (no detections), 283.9ms
Speed: 1.2ms preprocess, 283.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2AXNDYoDuWInBNMmeX3Sw_90.JPG: 480x640 (no detections), 272.1ms
Speed: 1.1ms preprocess, 272.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2AXNDYoDuWInBNMmeX3Sw_180.JPG: 480x640 (no detections), 279.3ms
Speed: 1.2ms preprocess, 279.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2AXNDYoDuWInBNMmeX3Sw_270.JPG: 480x640 (no detections), 276.8ms
Speed: 1.1ms preprocess, 276.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2AzLk228p7h7PNxrPKl1w_0.JPG: 480x640 (no detections), 278.0ms
Speed: 1.0ms preprocess, 278.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2AzLk228p7h7PNxrPKl1w_90.JPG: 480x640 (no detections), 279.3ms
Speed: 1.1ms preprocess, 279.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2AzLk228p7h7PNxrPKl1w_180.JPG: 480x640 (no detections), 281.2ms
Speed: 1.0ms preprocess, 281.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2AzLk228p7h7PNxrPKl1w_270.JPG: 480x640 (no detections), 277.4ms
Speed: 1.2ms preprocess, 277.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2BCCSXLBKBbQDD88_4eaA_0.JPG: 480x640 (no detections), 281.6ms
Speed: 1.2ms preprocess, 281.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2BCCSXLBKBbQDD88_4eaA_90.JPG: 480x640 (no detections), 276.7ms
Speed: 1.1ms preprocess, 276.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2BCCSXLBKBbQDD88_4eaA_180.JPG: 480x640 (no detections), 275.7ms
Speed: 1.1ms preprocess, 275.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2BCCSXLBKBbQDD88_4eaA_270.JPG: 480x640 (no detections), 277.2ms
Speed: 1.1ms preprocess, 277.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2DXYAgk8kwIbRaP8ZGW7g_0.JPG: 480x640 (no detections), 277.5ms
Speed: 1.3ms preprocess, 277.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2DXYAgk8kwIbRaP8ZGW7g_90.JPG: 480x640 (no detections), 273.6ms
Speed: 1.1ms preprocess, 273.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2DXYAgk8kwIbRaP8ZGW7g_180.JPG: 480x640 (no detections), 274.5ms
Speed: 1.1ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2DXYAgk8kwIbRaP8ZGW7g_270.JPG: 480x640 (no detections), 275.4ms
Speed: 1.0ms preprocess, 275.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2E2AefS8on85RL--LbCYw_0.JPG: 480x640 (no detections), 336.0ms
Speed: 1.1ms preprocess, 336.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2E2AefS8on85RL--LbCYw_90.JPG: 480x640 (no detections), 277.8ms
Speed: 1.1ms preprocess, 277.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2E2AefS8on85RL--LbCYw_180.JPG: 480x640 (no detections), 327.2ms
Speed: 1.1ms preprocess, 327.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2E2AefS8on85RL--LbCYw_270.JPG: 480x640 (no detections), 328.3ms
Speed: 1.1ms preprocess, 328.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2FBWC0wlrgEVvtmicZcfQ_0.JPG: 480x640 (no detections), 340.2ms
Speed: 1.0ms preprocess, 340.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2FBWC0wlrgEVvtmicZcfQ_90.JPG: 480x640 (no detections), 289.5ms
Speed: 1.1ms preprocess, 289.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2FBWC0wlrgEVvtmicZcfQ_180.JPG: 480x640 (no detections), 281.5ms
Speed: 1.1ms preprocess, 281.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2FBWC0wlrgEVvtmicZcfQ_270.JPG: 480x640 (no detections), 280.6ms
Speed: 1.2ms preprocess, 280.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2FC1yW4Gab2v4ww3VflnA_0.JPG: 480x640 (no detections), 275.8ms
Speed: 1.1ms preprocess, 275.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2FC1yW4Gab2v4ww3VflnA_90.JPG: 480x640 (no detections), 276.0ms
Speed: 1.0ms preprocess, 276.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2FC1yW4Gab2v4ww3VflnA_180.JPG: 480x640 (no detections), 278.2ms
Speed: 1.1ms preprocess, 278.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2FC1yW4Gab2v4ww3VflnA_270.JPG: 480x640 (no detections), 275.0ms

Speed: 1.2ms preprocess, 275.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2GCwJLFCYoDNpz4nNef-w_0.JPG: 480x640 (no detections), 276.7ms
Speed: 1.1ms preprocess, 276.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2GCwJLFCYoDNpz4nNef-w_90.JPG: 480x640 (no detections), 279.0ms
Speed: 1.2ms preprocess, 279.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2GCwJLFCYoDNpz4nNef-w_180.JPG: 480x640 (no detections), 276.1ms
Speed: 1.1ms preprocess, 276.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2GCwJLFCYoDNpz4nNef-w_270.JPG: 480x640 (no detections), 278.0ms
Speed: 1.0ms preprocess, 278.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2Gzn_Iu3AmEP2UQ7_EohQ_0.JPG: 480x640 (no detections), 277.4ms
Speed: 1.1ms preprocess, 277.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2Gzn_Iu3AmEP2UQ7_EohQ_90.JPG: 480x640 (no detections), 275.9ms
Speed: 1.0ms preprocess, 275.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2Gzn_Iu3AmEP2UQ7_EohQ_180.JPG: 480x640 (no detections), 275.5ms
Speed: 1.1ms preprocess, 275.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2Gzn_Iu3AmEP2UQ7_EohQ_270.JPG: 480x640 (no detections), 306.1ms
Speed: 1.1ms preprocess, 306.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2K8u6JVeXwuo9W3eQXqEA_0.JPG: 480x640 (no detections), 292.1ms
Speed: 1.1ms preprocess, 292.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2K8u6JVeXwuo9W3eQXqEA_90.JPG: 480x640 (no detections), 274.2ms
Speed: 1.2ms preprocess, 274.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2K8u6JVeXwuo9W3eQXqEA_180.JPG: 480x640 (no detections), 277.4ms
Speed: 1.1ms preprocess, 277.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2K8u6JVeXwuo9W3eQXqEA_270.JPG: 480x640 (no detections), 281.6ms
Speed: 1.0ms preprocess, 281.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2LBI15cGgLHRufD8WIHOQ_0.JPG: 480x640 (no detections), 276.3ms
Speed: 1.1ms preprocess, 276.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2LBI15cGgLHRufD8WIHOQ_90.JPG: 480x640 (no detections), 270.3ms
Speed: 1.0ms preprocess, 270.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2LBI15cGgLHRufD8WIHOQ_180.JPG: 480x640 (no detections), 276.6ms
Speed: 1.2ms preprocess, 276.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2LBI15cGgLHRufD8WIHOQ_270.JPG: 480x640 (no detections), 300.3ms
Speed: 1.1ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2MxJsOJATAg2fd0E3xxtg_0.JPG: 480x640 (no detections), 282.7ms
Speed: 1.1ms preprocess, 282.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2MxJsOJATAg2fd0E3xxtg_90.JPG: 480x640 (no detections), 300.4ms
Speed: 1.1ms preprocess, 300.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2MxJsOJATAg2fd0E3xxtg_180.JPG: 480x640 (no detections), 287.1ms
Speed: 1.2ms preprocess, 287.1ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2MxJsOJATAg2fd0E3xxtg_270.JPG: 480x640 (no detections), 279.6ms
Speed: 1.1ms preprocess, 279.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2NM2Vv9eVa7OHe637AL4A_0.JPG: 480x640 (no detections), 278.2ms
Speed: 1.1ms preprocess, 278.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2NM2Vv9eVa7OHe637AL4A_90.JPG: 480x640 1 Waste, 280.0ms
Speed: 1.2ms preprocess, 280.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2NM2Vv9eVa7OHe637AL4A_180.JPG: 480x640 (no detections), 276.0ms
Speed: 1.0ms preprocess, 276.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2NM2Vv9eVa7OHe637AL4A_270.JPG: 480x640 (no detections), 277.2ms
Speed: 1.1ms preprocess, 277.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2NkI_8AOQ7aTwaehzBDlA_0.JPG: 480x640 (no detections), 287.5ms
Speed: 1.1ms preprocess, 287.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2NkI_8AOQ7aTwaehzBDlA_90.JPG: 480x640 (no detections), 299.6ms
Speed: 1.1ms preprocess, 299.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2NkI_8AOQ7aTwaehzBDlA_180.JPG: 480x640 (no detections), 288.4ms
Speed: 1.1ms preprocess, 288.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2NkI_8AOQ7aTwaehzBDlA_270.JPG: 480x640 (no detections), 278.7ms
Speed: 1.1ms preprocess, 278.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2OaAYwSWcQt7MTjjHqBDg_0.JPG: 480x640 (no detections), 277.0ms
Speed: 1.0ms preprocess, 277.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2OaAYwSWcQt7MTjjHqBDg_90.JPG: 480x640 (no detections), 278.5ms
Speed: 1.2ms preprocess, 278.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2OaAYwSWcQt7MTjjHqBDg_180.JPG: 480x640 (no detections), 270.5ms
Speed: 1.1ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2OaAYwSWcQt7MTjjHqBDg_270.JPG: 480x640 1 Waste, 300.9ms
Speed: 1.1ms preprocess, 300.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2RJ5IhYB5iEY2BZldFHdQ_0.JPG: 480x640 (no detections), 286.9ms
Speed: 1.3ms preprocess, 286.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2RJ5IhYB5iEY2BZldFHdQ_90.JPG: 480x640 (no detections), 288.7ms
Speed: 1.1ms preprocess, 288.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2RJ5IhYB5iEY2BZldFHdQ_180.JPG: 480x640 (no detections), 288.4ms
Speed: 1.1ms preprocess, 288.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2RJ5IhYB5iEY2BZldFHdQ_270.JPG: 480x640 (no detections), 278.5ms
Speed: 1.2ms preprocess, 278.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2YGom8O07RrSl_KDnhKOA_0.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2YGom8O07RrSl_KDnhKOA_90.JPG: 480x640 (no detections), 290.1ms
Speed: 1.1ms preprocess, 290.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2YGom8O07RrSl_KDnhKOA_180.JPG: 480x640 (no detections), 281.6ms
Speed: 1.2ms preprocess, 281.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2YGom8O07RrSl_KDnhKOA_270.JPG: 480x640 (no detections), 279.7ms
Speed: 1.1ms preprocess, 279.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2YIAuQc1XqviMiCYv-0Gw_0.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2YIAuQc1XqviMiCYv-0Gw_90.JPG: 480x640 (no detections), 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2YIAuQc1XqviMiCYv-0Gw_180.JPG: 480x640 (no detections), 278.0ms
Speed: 1.1ms preprocess, 278.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2YIAuQc1XqviMiCYv-0Gw_270.JPG: 480x640 (no detections), 277.7ms
Speed: 1.1ms preprocess, 277.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2Ya4AhVsCMO4yQHEGh17A_0.JPG: 480x640 (no detections), 277.8ms
Speed: 1.0ms preprocess, 277.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2Ya4AhVsCMO4yQHEGh17A_90.JPG: 480x640 (no detections), 275.9ms
Speed: 1.1ms preprocess, 275.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2Ya4AhVsCMO4yQHEGh17A_180.JPG: 480x640 (no detections), 278.1ms
Speed: 1.0ms preprocess, 278.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2Ya4AhVsCMO4yQHEGh17A_270.JPG: 480x640 (no detections), 275.0ms
Speed: 1.2ms preprocess, 275.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2aGGIyQY_BhJTIjSVtWaQ_0.JPG: 480x640 (no detections), 274.9ms
Speed: 1.1ms preprocess, 274.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2aGGIyQY_BhJTIjSVtWaQ_90.JPG: 480x640 (no detections), 277.0ms
Speed: 1.0ms preprocess, 277.0ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2aGGIyQY_BhJTIjSVtWaQ_180.JPG: 480x640 (no detections), 272.8ms
Speed: 0.9ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2aGGIyQY_BhJTIjSVtWaQ_270.JPG: 480x640 (no detections), 274.0ms
Speed: 1.0ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2aI2sXNG_QrLRf5DAf4Hw_0.JPG: 480x640 (no detections), 278.5ms
Speed: 1.1ms preprocess, 278.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2aI2sXNG_QrLRf5DAf4Hw_90.JPG: 480x640 (no detections), 279.6ms
Speed: 1.2ms preprocess, 279.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2aI2sXNG_QrLRf5DAf4Hw_180.JPG: 480x640 (no detections), 275.7ms
Speed: 1.0ms preprocess, 275.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2aI2sXNG_QrLRf5DAf4Hw_270.JPG: 480x640 (no detections), 275.8ms
Speed: 1.1ms preprocess, 275.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2aaYM-lHYyMC58Dd7nzdA_0.JPG: 480x640 (no detections), 274.3ms
Speed: 1.0ms preprocess, 274.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2aaYM-lHYyMC58Dd7nzdA_90.JPG: 480x640 (no detections), 277.5ms
Speed: 1.0ms preprocess, 277.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2aaYM-lHYyMC58Dd7nzdA_180.JPG: 480x640 1 Waste, 275.4ms
Speed: 1.1ms preprocess, 275.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2aaYM-lHYyMC58Dd7nzdA_270.JPG: 480x640 (no detections), 274.4ms
Speed: 1.1ms preprocess, 274.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2euKnk329WfYmcZ41RWUw_0.JPG: 480x640 (no detections), 279.5ms
Speed: 1.1ms preprocess, 279.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2euKnk329WfYmcZ41RWUw_90.JPG: 480x640 (no detections), 278.1ms
Speed: 1.1ms preprocess, 278.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2euKnk329WfYmcZ41RWUw_180.JPG: 480x640 (no detections), 298.2ms
Speed: 1.1ms preprocess, 298.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2euKnk329WfYmcZ41RWUw_270.JPG: 480x640 (no detections), 279.1ms
Speed: 1.0ms preprocess, 279.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2gKB70zpDj2JIzV2Ev4ww_0.JPG: 480x640 (no detections), 276.8ms
Speed: 1.2ms preprocess, 276.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2gKB70zpDj2JIzV2Ev4ww_90.JPG: 480x640 (no detections), 278.3ms
Speed: 1.1ms preprocess, 278.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2gKB70zpDj2JIzV2Ev4ww_180.JPG: 480x640 (no detections), 278.0ms

Speed: 1.1ms preprocess, 278.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2gKB70zpDj2JIzV2Ev4ww_270.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2guhpHpqke7ggjwLuOulw_0.JPG: 480x640 (no detections), 274.7ms
Speed: 1.3ms preprocess, 274.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2guhpHpqke7ggjwLuOulw_90.JPG: 480x640 (no detections), 275.4ms
Speed: 1.1ms preprocess, 275.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2guhpHpqke7ggjwLuOulw_180.JPG: 480x640 (no detections), 278.3ms
Speed: 1.2ms preprocess, 278.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2guhpHpqke7ggjwLuOulw_270.JPG: 480x640 (no detections), 275.6ms
Speed: 1.3ms preprocess, 275.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2hwGAkQPz_-D3ml42BEOw_0.JPG: 480x640 (no detections), 278.5ms
Speed: 1.2ms preprocess, 278.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2hwGAkQPz_-D3ml42BEOw_90.JPG: 480x640 (no detections), 275.7ms
Speed: 1.2ms preprocess, 275.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2hwGAkQPz_-D3ml42BEOw_180.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2hwGAkQPz_-D3ml42BEOw_270.JPG: 480x640 (no detections), 287.9ms
Speed: 1.1ms preprocess, 287.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2q779bPC112PiEHbYndyg_0.JPG: 480x640 (no detections), 349.3ms
Speed: 1.2ms preprocess, 349.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2q779bPC112PiEHbYndyg_90.JPG: 480x640 (no detections), 297.1ms
Speed: 1.1ms preprocess, 297.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2q779bPC112PiEHbYndyg_180.JPG: 480x640 (no detections), 294.5ms
Speed: 1.1ms preprocess, 294.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2q779bPC112PiEHbYndyg_270.JPG: 480x640 (no detections), 283.4ms
Speed: 1.1ms preprocess, 283.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2rniUAZhrOt1ttahG0Czw_0.JPG: 480x640 (no detections), 283.9ms
Speed: 1.0ms preprocess, 283.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2rniUAZhrOt1ttahG0Czw_90.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2rniUAZhrOt1ttahG0Czw_180.JPG: 480x640 (no detections), 275.2ms
Speed: 1.0ms preprocess, 275.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/2/z2rniUAZhrOt1ttahG0Czw_270.JPG: 480x640 (no detections), 278.0ms
Speed: 1.1ms preprocess, 278.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3-WMDKsbhWMSHWyu-wJLA_0.JPG: 480x640 (no detections), 277.1ms
Speed: 1.1ms preprocess, 277.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3-WMDKsbhWMSHWyu-wJLA_90.JPG: 480x640 (no detections), 306.5ms
Speed: 1.2ms preprocess, 306.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3-WMDKsbhWMSHWyu-wJLA_180.JPG: 480x640 (no detections), 301.1ms
Speed: 1.3ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3-WMDKsbhWMSHWyu-wJLA_270.JPG: 480x640 (no detections), 280.0ms
Speed: 1.1ms preprocess, 280.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z30L8rwTcvnpGnU3WwcMyg_0.JPG: 480x640 (no detections), 286.9ms
Speed: 1.0ms preprocess, 286.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z30L8rwTcvnpGnU3WwcMyg_90.JPG: 480x640 (no detections), 298.6ms
Speed: 1.1ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z30L8rwTcvnpGnU3WwcMyg_180.JPG: 480x640 (no detections), 290.4ms
Speed: 1.8ms preprocess, 290.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z30L8rwTcvnpGnU3WwcMyg_270.JPG: 480x640 (no detections), 291.6ms
Speed: 1.1ms preprocess, 291.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z32xBKpGZ8GirLrTlvytsg_0.JPG: 480x640 (no detections), 283.8ms
Speed: 1.0ms preprocess, 283.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z32xBKpGZ8GirLrTlvytsg_90.JPG: 480x640 (no detections), 304.1ms
Speed: 1.3ms preprocess, 304.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z32xBKpGZ8GirLrTlvytsg_180.JPG: 480x640 (no detections), 316.7ms
Speed: 1.3ms preprocess, 316.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z32xBKpGZ8GirLrTlvytsg_270.JPG: 480x640 (no detections), 289.3ms
Speed: 1.1ms preprocess, 289.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z330wqyXweDfI37DPdmrPg_0.JPG: 480x640 (no detections), 288.6ms
Speed: 1.1ms preprocess, 288.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z330wqyXweDfI37DPdmrPg_90.JPG: 480x640 (no detections), 282.9ms
Speed: 1.2ms preprocess, 282.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z330wqyXweDfI37DPdmrPg_180.JPG: 480x640 (no detections), 285.4ms
Speed: 1.0ms preprocess, 285.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z330wqyXweDfI37DPdmrPg_270.JPG: 480x640 1 Waste, 279.7ms
Speed: 1.0ms preprocess, 279.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z39VrUuxBW05Z1dqvoJAvQ_0.JPG: 480x640 (no detections), 277.1ms
Speed: 1.1ms preprocess, 277.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z39VrUuxBW05Z1dqvoJAvQ_90.JPG: 480x640 (no detections), 281.2ms
Speed: 1.1ms preprocess, 281.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z39VrUuxBW05Z1dqvoJAvQ_180.JPG: 480x640 (no detections), 293.9ms
Speed: 1.0ms preprocess, 293.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z39VrUuxBW05Z1dqvoJAvQ_270.JPG: 480x640 (no detections), 292.9ms
Speed: 1.1ms preprocess, 292.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3MfkibrYNmc3cun-fRfsQ_0.JPG: 480x640 (no detections), 371.7ms
Speed: 1.4ms preprocess, 371.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3MfkibrYNmc3cun-fRfsQ_90.JPG: 480x640 (no detections), 323.8ms
Speed: 1.4ms preprocess, 323.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3MfkibrYNmc3cun-fRfsQ_180.JPG: 480x640 (no detections), 305.3ms
Speed: 1.7ms preprocess, 305.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3MfkibrYNmc3cun-fRfsQ_270.JPG: 480x640 (no detections), 278.1ms
Speed: 1.2ms preprocess, 278.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3NFvDXUmQbrCF6pMGqy7Q_0.JPG: 480x640 (no detections), 275.3ms
Speed: 1.0ms preprocess, 275.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3NFvDXUmQbrCF6pMGqy7Q_90.JPG: 480x640 (no detections), 274.9ms
Speed: 1.1ms preprocess, 274.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3NFvDXUmQbrCF6pMGqy7Q_180.JPG: 480x640 (no detections), 273.4ms
Speed: 1.1ms preprocess, 273.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3NFvDXUmQbrCF6pMGqy7Q_270.JPG: 480x640 (no detections), 269.1ms
Speed: 1.0ms preprocess, 269.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3QlAt0tnDSUCCnKNEMEbw_0.JPG: 480x640 (no detections), 358.5ms
Speed: 1.1ms preprocess, 358.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3QlAt0tnDSUCCnKNEMEbw_90.JPG: 480x640 (no detections), 296.7ms
Speed: 1.1ms preprocess, 296.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3QlAt0tnDSUCCnKNEMEbw_180.JPG: 480x640 (no detections), 283.8ms
Speed: 1.0ms preprocess, 283.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3QlAt0tnDSUCCnKNEMEbw_270.JPG: 480x640 (no detections), 291.2ms
Speed: 1.1ms preprocess, 291.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3SuidP3ZS6PTEu8RYRWyg_0.JPG: 480x640 (no detections), 294.4ms
Speed: 1.1ms preprocess, 294.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3SuidP3ZS6PTEu8RYRWyg_90.JPG: 480x640 (no detections), 296.4ms
Speed: 1.3ms preprocess, 296.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3SuidP3ZS6PTEu8RYRWyg_180.JPG: 480x640 (no detections), 281.2ms
Speed: 1.1ms preprocess, 281.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3SuidP3ZS6PTEu8RYRWyg_270.JPG: 480x640 (no detections), 273.5ms
Speed: 1.2ms preprocess, 273.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3UlFOYJ5vnbvzA2jgt4LA_0.JPG: 480x640 (no detections), 272.2ms
Speed: 1.0ms preprocess, 272.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3UlFOYJ5vnbvzA2jgt4LA_90.JPG: 480x640 1 Waste, 274.6ms
Speed: 1.2ms preprocess, 274.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3UlFOYJ5vnbvzA2jgt4LA_180.JPG: 480x640 (no detections), 275.3ms
Speed: 1.1ms preprocess, 275.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3UlFOYJ5vnbvzA2jgt4LA_270.JPG: 480x640 (no detections), 292.2ms
Speed: 1.0ms preprocess, 292.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3VTVJYXZ1mjHsJrodFdKQ_0.JPG: 480x640 (no detections), 282.0ms
Speed: 1.2ms preprocess, 282.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3VTVJYXZ1mjHsJrodFdKQ_90.JPG: 480x640 (no detections), 280.6ms
Speed: 1.1ms preprocess, 280.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3VTVJYXZ1mjHsJrodFdKQ_180.JPG: 480x640 (no detections), 280.7ms
Speed: 1.1ms preprocess, 280.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3VTVJYXZ1mjHsJrodFdKQ_270.JPG: 480x640 (no detections), 278.7ms
Speed: 1.1ms preprocess, 278.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3YzT4i-CX-yYU9sHQ-kww_0.JPG: 480x640 (no detections), 280.6ms
Speed: 1.0ms preprocess, 280.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3YzT4i-CX-yYU9sHQ-kww_90.JPG: 480x640 (no detections), 282.5ms
Speed: 1.1ms preprocess, 282.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3YzT4i-CX-yYU9sHQ-kww_180.JPG: 480x640 (no detections), 277.8ms
Speed: 1.1ms preprocess, 277.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3YzT4i-CX-yYU9sHQ-kww_270.JPG: 480x640 (no detections), 269.6ms
Speed: 1.1ms preprocess, 269.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3ZeIllog-uRQfEMtwBx_g_0.JPG: 480x640 (no detections), 274.8ms
Speed: 1.0ms preprocess, 274.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3ZeIllog-uRQfEMtwBx_g_90.JPG: 480x640 (no detections), 279.2ms

Speed: 1.1ms preprocess, 279.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3ZeIllog-uRQfEMtwBx_g_180.JPG: 480x640 (no detections), 277.2ms
Speed: 1.3ms preprocess, 277.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3ZeIllog-uRQfEMtwBx_g_270.JPG: 480x640 (no detections), 276.3ms
Speed: 1.0ms preprocess, 276.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3_9j1CQXIKIT8JZ9yQGTQ_0.JPG: 480x640 (no detections), 283.2ms
Speed: 1.1ms preprocess, 283.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3_9j1CQXIKIT8JZ9yQGTQ_90.JPG: 480x640 (no detections), 275.7ms
Speed: 1.0ms preprocess, 275.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3_9j1CQXIKIT8JZ9yQGTQ_180.JPG: 480x640 (no detections), 332.7ms
Speed: 1.1ms preprocess, 332.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3_9j1CQXIKIT8JZ9yQGTQ_270.JPG: 480x640 (no detections), 307.8ms
Speed: 1.2ms preprocess, 307.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3_D5JTTiweN-P1rV9DZtQ_0.JPG: 480x640 (no detections), 295.1ms
Speed: 1.1ms preprocess, 295.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3_D5JTTiweN-P1rV9DZtQ_90.JPG: 480x640 (no detections), 286.9ms
Speed: 1.3ms preprocess, 286.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3_D5JTTiweN-P1rV9DZtQ_180.JPG: 480x640 (no detections), 285.3ms
Speed: 1.3ms preprocess, 285.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3_D5JTTiweN-P1rV9DZtQ_270.JPG: 480x640 (no detections), 291.3ms
Speed: 1.1ms preprocess, 291.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3etUv4n2hvDDsWSMPZCog_0.JPG: 480x640 (no detections), 284.2ms
Speed: 1.4ms preprocess, 284.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3etUv4n2hvDDsWSMPZCog_90.JPG: 480x640 (no detections), 301.2ms
Speed: 1.1ms preprocess, 301.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3etUv4n2hvDDsWSMPZCog_180.JPG: 480x640 (no detections), 276.5ms
Speed: 1.1ms preprocess, 276.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3etUv4n2hvDDsWSMPZCog_270.JPG: 480x640 (no detections), 283.7ms
Speed: 1.0ms preprocess, 283.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3lbWZBGscMGKo48N2R1JA_0.JPG: 480x640 (no detections), 277.8ms
Speed: 1.3ms preprocess, 277.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3lbWZBGscMGKo48N2R1JA_90.JPG: 480x640 (no detections), 290.5ms
Speed: 1.2ms preprocess, 290.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3lbWZBGscMGKo48N2R1JA_180.JPG: 480x640 (no detections), 282.0ms
Speed: 1.1ms preprocess, 282.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3lbWZBGscMGKo48N2R1JA_270.JPG: 480x640 (no detections), 280.9ms
Speed: 1.1ms preprocess, 280.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3pqXbPZIjcEVtWeqix9QA_0.JPG: 480x640 (no detections), 336.5ms
Speed: 1.1ms preprocess, 336.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3pqXbPZIjcEVtWeqix9QA_90.JPG: 480x640 (no detections), 292.6ms
Speed: 1.1ms preprocess, 292.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3pqXbPZIjcEVtWeqix9QA_180.JPG: 480x640 (no detections), 289.9ms
Speed: 1.3ms preprocess, 289.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3pqXbPZIjcEVtWeqix9QA_270.JPG: 480x640 (no detections), 279.6ms
Speed: 1.0ms preprocess, 279.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3uhlL_5aBGObRW26jtpew_0.JPG: 480x640 (no detections), 290.6ms
Speed: 1.1ms preprocess, 290.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3uhlL_5aBGObRW26jtpew_90.JPG: 480x640 (no detections), 279.6ms
Speed: 1.0ms preprocess, 279.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3uhlL_5aBGObRW26jtpew_180.JPG: 480x640 (no detections), 300.4ms
Speed: 1.1ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3uhlL_5aBGObRW26jtpew_270.JPG: 480x640 (no detections), 281.9ms
Speed: 1.3ms preprocess, 281.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3w_ZGsKw36wxCI6dA1fbQ_0.JPG: 480x640 1 Waste, 269.6ms
Speed: 1.1ms preprocess, 269.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3w_ZGsKw36wxCI6dA1fbQ_90.JPG: 480x640 1 Waste, 297.1ms
Speed: 1.2ms preprocess, 297.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3w_ZGsKw36wxCI6dA1fbQ_180.JPG: 480x640 (no detections), 299.5ms
Speed: 1.1ms preprocess, 299.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3w_ZGsKw36wxCI6dA1fbQ_270.JPG: 480x640 (no detections), 297.2ms
Speed: 1.1ms preprocess, 297.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3yPoI_0CVGulXxvlGXbew_0.JPG: 480x640 (no detections), 297.1ms
Speed: 1.1ms preprocess, 297.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3yPoI_0CVGulXxvlGXbew_90.JPG: 480x640 (no detections), 279.5ms
Speed: 1.2ms preprocess, 279.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3yPoI_0CVGulXxvlGXbew_180.JPG: 480x640 (no detections), 281.9ms
Speed: 1.3ms preprocess, 281.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/3/z3yPoI_0CVGulXxvlGXbew_270.JPG: 480x640 (no detections), 282.7ms
Speed: 1.2ms preprocess, 282.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z40KbN5gMDQWP15lScv5uA_0.JPG: 480x640 (no detections), 295.3ms
Speed: 1.1ms preprocess, 295.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z40KbN5gMDQWP15lScv5uA_90.JPG: 480x640 (no detections), 278.5ms
Speed: 1.1ms preprocess, 278.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z40KbN5gMDQWP15lScv5uA_180.JPG: 480x640 (no detections), 277.7ms
Speed: 1.0ms preprocess, 277.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z40KbN5gMDQWP15lScv5uA_270.JPG: 480x640 (no detections), 280.7ms
Speed: 1.1ms preprocess, 280.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z48BAkBgoR6tkavYo8GUqw_0.JPG: 480x640 (no detections), 284.4ms
Speed: 1.1ms preprocess, 284.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z48BAkBgoR6tkavYo8GUqw_90.JPG: 480x640 (no detections), 343.5ms
Speed: 1.3ms preprocess, 343.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z48BAkBgoR6tkavYo8GUqw_180.JPG: 480x640 (no detections), 275.6ms
Speed: 1.1ms preprocess, 275.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z48BAkBgoR6tkavYo8GUqw_270.JPG: 480x640 (no detections), 289.8ms
Speed: 1.1ms preprocess, 289.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4E1z83Sdq7j1gqfG1lPfg_0.JPG: 480x640 (no detections), 278.1ms
Speed: 1.1ms preprocess, 278.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4E1z83Sdq7j1gqfG1lPfg_90.JPG: 480x640 (no detections), 271.5ms
Speed: 1.1ms preprocess, 271.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4E1z83Sdq7j1gqfG1lPfg_180.JPG: 480x640 (no detections), 269.3ms
Speed: 1.0ms preprocess, 269.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4E1z83Sdq7j1gqfG1lPfg_270.JPG: 480x640 (no detections), 308.5ms
Speed: 1.1ms preprocess, 308.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4HnfOTmx1-zWa1NQsCz-g_0.JPG: 480x640 (no detections), 269.5ms
Speed: 1.0ms preprocess, 269.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4HnfOTmx1-zWa1NQsCz-g_90.JPG: 480x640 (no detections), 272.5ms
Speed: 1.0ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4HnfOTmx1-zWa1NQsCz-g_180.JPG: 480x640 (no detections), 267.1ms
Speed: 1.7ms preprocess, 267.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4HnfOTmx1-zWa1NQsCz-g_270.JPG: 480x640 (no detections), 268.4ms
Speed: 1.0ms preprocess, 268.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4N4ovSMVNL2DGFsgb-Dow_0.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4N4ovSMVNL2DGFsgb-Dow_90.JPG: 480x640 (no detections), 281.4ms
Speed: 1.1ms preprocess, 281.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4N4ovSMVNL2DGFsgb-Dow_180.JPG: 480x640 (no detections), 295.2ms
Speed: 1.8ms preprocess, 295.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4N4ovSMVNL2DGFsgb-Dow_270.JPG: 480x640 (no detections), 294.9ms
Speed: 1.8ms preprocess, 294.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4PGxBKT61Bkjvh4SEAsCw_0.JPG: 480x640 (no detections), 283.8ms
Speed: 1.1ms preprocess, 283.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4PGxBKT61Bkjvh4SEAsCw_90.JPG: 480x640 (no detections), 287.1ms
Speed: 1.1ms preprocess, 287.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4PGxBKT61Bkjvh4SEAsCw_180.JPG: 480x640 (no detections), 277.2ms
Speed: 1.2ms preprocess, 277.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4PGxBKT61Bkjvh4SEAsCw_270.JPG: 480x640 (no detections), 275.3ms
Speed: 1.1ms preprocess, 275.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4QgYUVnYFZKmEmPFrSzgw_0.JPG: 480x640 (no detections), 298.4ms
Speed: 1.0ms preprocess, 298.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4QgYUVnYFZKmEmPFrSzgw_90.JPG: 480x640 (no detections), 292.5ms
Speed: 1.3ms preprocess, 292.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4QgYUVnYFZKmEmPFrSzgw_180.JPG: 480x640 (no detections), 337.4ms
Speed: 1.1ms preprocess, 337.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4QgYUVnYFZKmEmPFrSzgw_270.JPG: 480x640 (no detections), 289.4ms
Speed: 1.0ms preprocess, 289.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4SJbs_ep8L_cbgNJdfj4Q_0.JPG: 480x640 (no detections), 304.4ms
Speed: 1.0ms preprocess, 304.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4SJbs_ep8L_cbgNJdfj4Q_90.JPG: 480x640 (no detections), 311.0ms
Speed: 1.2ms preprocess, 311.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4SJbs_ep8L_cbgNJdfj4Q_180.JPG: 480x640 (no detections), 335.8ms
Speed: 1.2ms preprocess, 335.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4SJbs_ep8L_cbgNJdfj4Q_270.JPG: 480x640 (no detections), 312.6ms
Speed: 1.1ms preprocess, 312.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4V7bh36OY8T54XaTGG0ww_0.JPG: 480x640 (no detections), 308.5ms

Speed: 1.4ms preprocess, 308.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4V7bh36OY8T54XaTGG0ww_90.JPG: 480x640 (no detections), 325.8ms
Speed: 1.0ms preprocess, 325.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4V7bh36OY8T54XaTGG0ww_180.JPG: 480x640 (no detections), 287.7ms
Speed: 1.2ms preprocess, 287.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4V7bh36OY8T54XaTGG0ww_270.JPG: 480x640 (no detections), 271.6ms
Speed: 1.0ms preprocess, 271.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4VfxRFkP2saiZ2srszu7g_0.JPG: 480x640 (no detections), 276.8ms
Speed: 1.0ms preprocess, 276.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4VfxRFkP2saiZ2srszu7g_90.JPG: 480x640 (no detections), 277.6ms
Speed: 1.1ms preprocess, 277.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4VfxRFkP2saiZ2srszu7g_180.JPG: 480x640 (no detections), 278.0ms
Speed: 1.0ms preprocess, 278.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4VfxRFkP2saiZ2srszu7g_270.JPG: 480x640 (no detections), 288.9ms
Speed: 1.0ms preprocess, 288.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4W_FHPXzbDNsRdi1-0hAQ_0.JPG: 480x640 (no detections), 284.9ms
Speed: 1.1ms preprocess, 284.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4W_FHPXzbDNsRdi1-0hAQ_90.JPG: 480x640 (no detections), 289.8ms
Speed: 1.1ms preprocess, 289.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4W_FHPXzbDNsRdi1-0hAQ_180.JPG: 480x640 (no detections), 294.3ms
Speed: 1.2ms preprocess, 294.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4W_FHPXzbDNsRdi1-0hAQ_270.JPG: 480x640 (no detections), 280.4ms
Speed: 1.6ms preprocess, 280.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4WgS_CS1fVFTiZaX6FCcA_0.JPG: 480x640 (no detections), 275.7ms
Speed: 1.2ms preprocess, 275.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4WgS_CS1fVFTiZaX6FCcA_90.JPG: 480x640 (no detections), 279.0ms
Speed: 1.1ms preprocess, 279.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4WgS_CS1fVFTiZaX6FCcA_180.JPG: 480x640 (no detections), 288.4ms
Speed: 1.3ms preprocess, 288.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4WgS_CS1fVFTiZaX6FCcA_270.JPG: 480x640 (no detections), 281.2ms
Speed: 1.1ms preprocess, 281.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4ZKyCuCzLv_3sFLSwDhQg_0.JPG: 480x640 (no detections), 282.9ms
Speed: 1.0ms preprocess, 282.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4ZKyCuCzLv_3sFLSwDhQg_90.JPG: 480x640 (no detections), 283.5ms
Speed: 1.2ms preprocess, 283.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4ZKyCuCzLv_3sFLSwDhQg_180.JPG: 480x640 (no detections), 291.0ms
Speed: 1.2ms preprocess, 291.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4ZKyCuCzLv_3sFLSwDhQg_270.JPG: 480x640 (no detections), 329.0ms
Speed: 1.0ms preprocess, 329.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4_w32msUQdL7nOWppQ4qw_0.JPG: 480x640 (no detections), 286.2ms
Speed: 1.5ms preprocess, 286.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4_w32msUQdL7nOWppQ4qw_90.JPG: 480x640 (no detections), 275.3ms
Speed: 1.3ms preprocess, 275.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4_w32msUQdL7nOWppQ4qw_180.JPG: 480x640 (no detections), 276.9ms
Speed: 1.0ms preprocess, 276.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4_w32msUQdL7nOWppQ4qw_270.JPG: 480x640 (no detections), 274.4ms
Speed: 1.1ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4cQXMK3ApYC0dSAUAJQUg_0.JPG: 480x640 (no detections), 274.4ms
Speed: 1.1ms preprocess, 274.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4cQXMK3ApYC0dSAUAJQUg_90.JPG: 480x640 (no detections), 276.1ms
Speed: 1.2ms preprocess, 276.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4cQXMK3ApYC0dSAUAJQUg_180.JPG: 480x640 (no detections), 285.7ms
Speed: 1.1ms preprocess, 285.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4cQXMK3ApYC0dSAUAJQUg_270.JPG: 480x640 (no detections), 278.1ms
Speed: 1.2ms preprocess, 278.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4jThl1BsK1k6RZO0qshFQ_0.JPG: 480x640 (no detections), 277.3ms
Speed: 1.1ms preprocess, 277.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4jThl1BsK1k6RZO0qshFQ_90.JPG: 480x640 (no detections), 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4jThl1BsK1k6RZO0qshFQ_180.JPG: 480x640 (no detections), 276.1ms
Speed: 1.0ms preprocess, 276.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4jThl1BsK1k6RZO0qshFQ_270.JPG: 480x640 (no detections), 276.9ms
Speed: 1.0ms preprocess, 276.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4jYzPq1gtDYVyTgCE0pdQ_0.JPG: 480x640 (no detections), 273.5ms
Speed: 1.0ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4jYzPq1gtDYVyTgCE0pdQ_90.JPG: 480x640 (no detections), 280.7ms
Speed: 1.1ms preprocess, 280.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4jYzPq1gtDYVyTgCE0pdQ_180.JPG: 480x640 (no detections), 324.6ms
Speed: 1.2ms preprocess, 324.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4jYzPq1gtDYVyTgCE0pdQ_270.JPG: 480x640 (no detections), 292.2ms
Speed: 2.3ms preprocess, 292.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4jj9vuhcL0NlUrocPGDRA_0.JPG: 480x640 2 Wastes, 277.9ms
Speed: 1.2ms preprocess, 277.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4jj9vuhcL0NlUrocPGDRA_90.JPG: 480x640 (no detections), 308.7ms
Speed: 1.0ms preprocess, 308.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4jj9vuhcL0NlUrocPGDRA_180.JPG: 480x640 (no detections), 305.7ms
Speed: 1.1ms preprocess, 305.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4jj9vuhcL0NlUrocPGDRA_270.JPG: 480x640 (no detections), 277.4ms
Speed: 1.3ms preprocess, 277.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4lJw-AYJxM6luSqysmlpQ_0.JPG: 480x640 (no detections), 292.8ms
Speed: 1.1ms preprocess, 292.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4lJw-AYJxM6luSqysmlpQ_90.JPG: 480x640 (no detections), 289.9ms
Speed: 1.2ms preprocess, 289.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4lJw-AYJxM6luSqysmlpQ_180.JPG: 480x640 (no detections), 297.2ms
Speed: 1.6ms preprocess, 297.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4lJw-AYJxM6luSqysmlpQ_270.JPG: 480x640 (no detections), 296.2ms
Speed: 1.3ms preprocess, 296.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4mMpRgrQU8M27elLCWfWQ_0.JPG: 480x640 (no detections), 279.8ms
Speed: 1.1ms preprocess, 279.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4mMpRgrQU8M27elLCWfWQ_90.JPG: 480x640 (no detections), 285.8ms
Speed: 1.1ms preprocess, 285.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4mMpRgrQU8M27elLCWfWQ_180.JPG: 480x640 (no detections), 297.1ms
Speed: 1.1ms preprocess, 297.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4mMpRgrQU8M27elLCWfWQ_270.JPG: 480x640 (no detections), 285.8ms
Speed: 1.5ms preprocess, 285.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4pL9vJ3IZsnSfx3fYxHdA_0.JPG: 480x640 (no detections), 317.8ms
Speed: 1.1ms preprocess, 317.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4pL9vJ3IZsnSfx3fYxHdA_90.JPG: 480x640 (no detections), 288.7ms
Speed: 1.1ms preprocess, 288.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4pL9vJ3IZsnSfx3fYxHdA_180.JPG: 480x640 (no detections), 282.6ms
Speed: 1.1ms preprocess, 282.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4pL9vJ3IZsnSfx3fYxHdA_270.JPG: 480x640 (no detections), 297.4ms
Speed: 1.1ms preprocess, 297.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4qRRSFDmtQ7cRJDPZOWew_0.JPG: 480x640 (no detections), 288.0ms
Speed: 1.0ms preprocess, 288.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4qRRSFDmtQ7cRJDPZOWew_90.JPG: 480x640 (no detections), 318.2ms
Speed: 1.2ms preprocess, 318.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4qRRSFDmtQ7cRJDPZOWew_180.JPG: 480x640 (no detections), 301.5ms
Speed: 1.6ms preprocess, 301.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4qRRSFDmtQ7cRJDPZOWew_270.JPG: 480x640 (no detections), 285.7ms
Speed: 1.3ms preprocess, 285.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4qW9AFYcwioUFpIiO0vgg_0.JPG: 480x640 (no detections), 280.2ms
Speed: 1.1ms preprocess, 280.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4qW9AFYcwioUFpIiO0vgg_90.JPG: 480x640 (no detections), 335.3ms
Speed: 1.0ms preprocess, 335.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4qW9AFYcwioUFpIiO0vgg_180.JPG: 480x640 1 Waste, 357.1ms
Speed: 1.2ms preprocess, 357.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4qW9AFYcwioUFpIiO0vgg_270.JPG: 480x640 (no detections), 394.4ms
Speed: 1.5ms preprocess, 394.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4sr7mt9TpTc1xb2A809-w_0.JPG: 480x640 (no detections), 404.8ms
Speed: 1.2ms preprocess, 404.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4sr7mt9TpTc1xb2A809-w_90.JPG: 480x640 (no detections), 349.7ms
Speed: 1.3ms preprocess, 349.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4sr7mt9TpTc1xb2A809-w_180.JPG: 480x640 (no detections), 322.5ms
Speed: 1.1ms preprocess, 322.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4sr7mt9TpTc1xb2A809-w_270.JPG: 480x640 (no detections), 286.7ms
Speed: 1.0ms preprocess, 286.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4vYhSNnou7a3NmhYfur6A_0.JPG: 480x640 (no detections), 284.8ms
Speed: 1.0ms preprocess, 284.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4vYhSNnou7a3NmhYfur6A_90.JPG: 480x640 (no detections), 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4vYhSNnou7a3NmhYfur6A_180.JPG: 480x640 (no detections), 281.1ms
Speed: 1.1ms preprocess, 281.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4vYhSNnou7a3NmhYfur6A_270.JPG: 480x640 (no detections), 277.3ms

Speed: 1.0ms preprocess, 277.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4yABU1nZpwMl1IzSRp6Sg_0.JPG: 480x640 (no detections), 279.6ms
Speed: 1.2ms preprocess, 279.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4yABU1nZpwMl1IzSRp6Sg_90.JPG: 480x640 (no detections), 282.3ms
Speed: 1.8ms preprocess, 282.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4yABU1nZpwMl1IzSRp6Sg_180.JPG: 480x640 (no detections), 325.0ms
Speed: 1.5ms preprocess, 325.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/4/z4yABU1nZpwMl1IzSRp6Sg_270.JPG: 480x640 (no detections), 346.0ms
Speed: 1.2ms preprocess, 346.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5-eFh-fI1WT-ntoR18xIA_0.JPG: 480x640 1 Waste, 306.0ms
Speed: 1.1ms preprocess, 306.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5-eFh-fI1WT-ntoR18xIA_90.JPG: 480x640 (no detections), 337.2ms
Speed: 1.1ms preprocess, 337.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5-eFh-fI1WT-ntoR18xIA_180.JPG: 480x640 (no detections), 304.4ms
Speed: 1.3ms preprocess, 304.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5-eFh-fI1WT-ntoR18xIA_270.JPG: 480x640 (no detections), 289.6ms
Speed: 1.3ms preprocess, 289.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5-fO-C49aBKxoO7RpisYA_0.JPG: 480x640 (no detections), 273.1ms
Speed: 1.2ms preprocess, 273.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5-fO-C49aBKxoO7RpisYA_90.JPG: 480x640 (no detections), 279.9ms
Speed: 1.1ms preprocess, 279.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5-fO-C49aBKxoO7RpisYA_180.JPG: 480x640 (no detections), 278.6ms
Speed: 1.1ms preprocess, 278.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5-fO-C49aBKxoO7RpisYA_270.JPG: 480x640 (no detections), 283.5ms
Speed: 1.1ms preprocess, 283.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z50t6MusOx-f0U0BodossQ_0.JPG: 480x640 (no detections), 286.6ms
Speed: 1.3ms preprocess, 286.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z50t6MusOx-f0U0BodossQ_90.JPG: 480x640 (no detections), 274.9ms
Speed: 1.2ms preprocess, 274.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z50t6MusOx-f0U0BodossQ_180.JPG: 480x640 (no detections), 274.0ms
Speed: 1.0ms preprocess, 274.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z50t6MusOx-f0U0BodossQ_270.JPG: 480x640 (no detections), 273.8ms
Speed: 1.0ms preprocess, 273.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z55Uiqw8SkTIvE_Yh_aGnA_0.JPG: 480x640 (no detections), 317.6ms
Speed: 1.3ms preprocess, 317.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z55Uiqw8SkTIvE_Yh_aGnA_90.JPG: 480x640 (no detections), 341.1ms
Speed: 1.6ms preprocess, 341.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z55Uiqw8SkTIvE_Yh_aGnA_180.JPG: 480x640 (no detections), 317.1ms
Speed: 1.1ms preprocess, 317.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z55Uiqw8SkTIvE_Yh_aGnA_270.JPG: 480x640 (no detections), 305.6ms
Speed: 1.3ms preprocess, 305.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z57r53ErdNg8fs4PHJdvzQ_0.JPG: 480x640 (no detections), 303.7ms
Speed: 1.2ms preprocess, 303.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z57r53ErdNg8fs4PHJdvzQ_90.JPG: 480x640 (no detections), 490.5ms
Speed: 1.6ms preprocess, 490.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z57r53ErdNg8fs4PHJdvzQ_180.JPG: 480x640 (no detections), 291.5ms
Speed: 1.2ms preprocess, 291.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z57r53ErdNg8fs4PHJdvzQ_270.JPG: 480x640 (no detections), 308.9ms
Speed: 1.3ms preprocess, 308.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5B9jPsVoKigS61Svjt7mQ_0.JPG: 480x640 (no detections), 275.5ms
Speed: 1.1ms preprocess, 275.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5B9jPsVoKigS61Svjt7mQ_90.JPG: 480x640 (no detections), 278.8ms
Speed: 1.1ms preprocess, 278.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5B9jPsVoKigS61Svjt7mQ_180.JPG: 480x640 (no detections), 274.7ms
Speed: 1.1ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5B9jPsVoKigS61Svjt7mQ_270.JPG: 480x640 (no detections), 279.1ms
Speed: 1.2ms preprocess, 279.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5Cebdi37UDE3SEWgdwhjQ_0.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5Cebdi37UDE3SEWgdwhjQ_90.JPG: 480x640 (no detections), 275.5ms
Speed: 1.0ms preprocess, 275.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5Cebdi37UDE3SEWgdwhjQ_180.JPG: 480x640 (no detections), 270.7ms
Speed: 1.0ms preprocess, 270.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5Cebdi37UDE3SEWgdwhjQ_270.JPG: 480x640 (no detections), 269.6ms
Speed: 1.2ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5CeiorYgO4ANgT9AMzUsg_0.JPG: 480x640 (no detections), 274.1ms
Speed: 1.2ms preprocess, 274.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5CeiorYgO4ANgT9AMzUsg_90.JPG: 480x640 (no detections), 270.5ms
Speed: 1.1ms preprocess, 270.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5CeiorYgO4ANgT9AMzUsg_180.JPG: 480x640 (no detections), 275.0ms
Speed: 1.2ms preprocess, 275.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5CeiorYgO4ANgT9AMzUsg_270.JPG: 480x640 (no detections), 274.5ms
Speed: 1.1ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5IAVBw4ta5nmrLOT1P0rQ_0.JPG: 480x640 (no detections), 273.8ms
Speed: 1.0ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5IAVBw4ta5nmrLOT1P0rQ_90.JPG: 480x640 (no detections), 276.1ms
Speed: 1.1ms preprocess, 276.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5IAVBw4ta5nmrLOT1P0rQ_180.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5IAVBw4ta5nmrLOT1P0rQ_270.JPG: 480x640 (no detections), 275.4ms
Speed: 1.4ms preprocess, 275.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5LBlKO7-xYX-Mm6m2fQ1w_0.JPG: 480x640 (no detections), 273.0ms
Speed: 1.0ms preprocess, 273.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5LBlKO7-xYX-Mm6m2fQ1w_90.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5LBlKO7-xYX-Mm6m2fQ1w_180.JPG: 480x640 (no detections), 279.4ms
Speed: 1.1ms preprocess, 279.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5LBlKO7-xYX-Mm6m2fQ1w_270.JPG: 480x640 (no detections), 274.7ms
Speed: 1.2ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5Nd2tU5f_fzS1PzsxA06g_0.JPG: 480x640 1 Waste, 272.7ms
Speed: 1.0ms preprocess, 272.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5Nd2tU5f_fzS1PzsxA06g_90.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5Nd2tU5f_fzS1PzsxA06g_180.JPG: 480x640 (no detections), 271.5ms
Speed: 1.1ms preprocess, 271.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5Nd2tU5f_fzS1PzsxA06g_270.JPG: 480x640 (no detections), 273.0ms
Speed: 1.0ms preprocess, 273.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5QZfaz2lZCEGKwPOfh-IA_0.JPG: 480x640 (no detections), 270.8ms
Speed: 1.0ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5QZfaz2lZCEGKwPOfh-IA_90.JPG: 480x640 (no detections), 281.8ms
Speed: 1.0ms preprocess, 281.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5QZfaz2lZCEGKwPOfh-IA_180.JPG: 480x640 (no detections), 279.8ms
Speed: 1.0ms preprocess, 279.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5QZfaz2lZCEGKwPOfh-IA_270.JPG: 480x640 (no detections), 275.6ms
Speed: 1.0ms preprocess, 275.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5_m45JcLqLjJ-J84UG2aQ_0.JPG: 480x640 (no detections), 273.5ms
Speed: 1.0ms preprocess, 273.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5_m45JcLqLjJ-J84UG2aQ_90.JPG: 480x640 (no detections), 271.6ms
Speed: 1.2ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5_m45JcLqLjJ-J84UG2aQ_180.JPG: 480x640 (no detections), 277.2ms
Speed: 1.1ms preprocess, 277.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5_m45JcLqLjJ-J84UG2aQ_270.JPG: 480x640 (no detections), 277.7ms
Speed: 1.1ms preprocess, 277.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5baW4rh_aqw7ZiBzhFS5A_0.JPG: 480x640 1 Waste, 274.4ms
Speed: 1.0ms preprocess, 274.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5baW4rh_aqw7ZiBzhFS5A_90.JPG: 480x640 (no detections), 280.0ms
Speed: 1.2ms preprocess, 280.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5baW4rh_aqw7ZiBzhFS5A_180.JPG: 480x640 (no detections), 277.4ms
Speed: 1.0ms preprocess, 277.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5baW4rh_aqw7ZiBzhFS5A_270.JPG: 480x640 (no detections), 274.9ms
Speed: 1.1ms preprocess, 274.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5ggnKecYeRlTMbgZnGfUg_0.JPG: 480x640 (no detections), 272.7ms
Speed: 1.0ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5ggnKecYeRlTMbgZnGfUg_90.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5ggnKecYeRlTMbgZnGfUg_180.JPG: 480x640 (no detections), 275.9ms
Speed: 1.0ms preprocess, 275.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5ggnKecYeRlTMbgZnGfUg_270.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5ht_TejJB14vGzxLry4MQ_0.JPG: 480x640 (no detections), 273.1ms
Speed: 1.1ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5ht_TejJB14vGzxLry4MQ_90.JPG: 480x640 (no detections), 275.9ms
Speed: 1.1ms preprocess, 275.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5ht_TejJB14vGzxLry4MQ_180.JPG: 480x640 (no detections), 276.7ms

Speed: 1.2ms preprocess, 276.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5ht_TejJB14vGzxLry4MQ_270.JPG: 480x640 (no detections), 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5jAJvG8lkkNH16NyKCkKw_0.JPG: 480x640 (no detections), 273.2ms
Speed: 1.1ms preprocess, 273.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5jAJvG8lkkNH16NyKCkKw_90.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5jAJvG8lkkNH16NyKCkKw_180.JPG: 480x640 (no detections), 271.5ms
Speed: 1.6ms preprocess, 271.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5jAJvG8lkkNH16NyKCkKw_270.JPG: 480x640 (no detections), 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5mjRzIJFQg0iokmBNdYJg_0.JPG: 480x640 (no detections), 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5mjRzIJFQg0iokmBNdYJg_90.JPG: 480x640 (no detections), 276.9ms
Speed: 1.2ms preprocess, 276.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5mjRzIJFQg0iokmBNdYJg_180.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5mjRzIJFQg0iokmBNdYJg_270.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5nQWsehXUwKJiJIjheeFA_0.JPG: 480x640 (no detections), 266.3ms
Speed: 1.0ms preprocess, 266.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5nQWsehXUwKJiJIjheeFA_90.JPG: 480x640 (no detections), 268.9ms
Speed: 1.1ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5nQWsehXUwKJiJIjheeFA_180.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5nQWsehXUwKJiJIjheeFA_270.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5npQN7WRPZWP5n8M3Htnw_0.JPG: 480x640 (no detections), 263.0ms
Speed: 1.1ms preprocess, 263.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5npQN7WRPZWP5n8M3Htnw_90.JPG: 480x640 (no detections), 272.6ms
Speed: 1.0ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5npQN7WRPZWP5n8M3Htnw_180.JPG: 480x640 (no detections), 269.0ms
Speed: 1.1ms preprocess, 269.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5npQN7WRPZWP5n8M3Htnw_270.JPG: 480x640 (no detections), 284.5ms
Speed: 1.1ms preprocess, 284.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5s6Fa7jy6Kor3j1wXfCIA_0.JPG: 480x640 (no detections), 287.4ms
Speed: 1.1ms preprocess, 287.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5s6Fa7jy6Kor3j1wXfCIA_90.JPG: 480x640 (no detections), 275.0ms
Speed: 1.2ms preprocess, 275.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5s6Fa7jy6Kor3j1wXfCIA_180.JPG: 480x640 (no detections), 277.8ms
Speed: 1.2ms preprocess, 277.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5s6Fa7jy6Kor3j1wXfCIA_270.JPG: 480x640 (no detections), 272.9ms
Speed: 1.0ms preprocess, 272.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5x9CrwUcVune8KxaPsmaQ_0.JPG: 480x640 (no detections), 275.0ms
Speed: 1.1ms preprocess, 275.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5x9CrwUcVune8KxaPsmaQ_90.JPG: 480x640 (no detections), 273.2ms
Speed: 1.0ms preprocess, 273.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5x9CrwUcVune8KxaPsmaQ_180.JPG: 480x640 (no detections), 272.3ms
Speed: 1.0ms preprocess, 272.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5x9CrwUcVune8KxaPsmaQ_270.JPG: 480x640 (no detections), 276.3ms
Speed: 1.1ms preprocess, 276.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5xN2pd3YQh-hUJCjhaa-w_0.JPG: 480x640 (no detections), 277.4ms
Speed: 1.2ms preprocess, 277.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5xN2pd3YQh-hUJCjhaa-w_90.JPG: 480x640 (no detections), 281.8ms
Speed: 1.2ms preprocess, 281.8ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5xN2pd3YQh-hUJCjhaa-w_180.JPG: 480x640 (no detections), 281.6ms
Speed: 1.1ms preprocess, 281.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5xN2pd3YQh-hUJCjhaa-w_270.JPG: 480x640 (no detections), 280.0ms
Speed: 1.0ms preprocess, 280.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5yF8l8d6XsKUbyOhXUjqg_0.JPG: 480x640 (no detections), 273.2ms
Speed: 1.0ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5yF8l8d6XsKUbyOhXUjqg_90.JPG: 480x640 (no detections), 277.5ms
Speed: 1.0ms preprocess, 277.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5yF8l8d6XsKUbyOhXUjqg_180.JPG: 480x640 (no detections), 284.3ms
Speed: 1.4ms preprocess, 284.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5yF8l8d6XsKUbyOhXUjqg_270.JPG: 480x640 (no detections), 277.2ms
Speed: 1.0ms preprocess, 277.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5znRjUJ6v2opAI1yRN1eQ_0.JPG: 480x640 (no detections), 273.6ms
Speed: 1.0ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5znRjUJ6v2opAI1yRN1eQ_90.JPG: 480x640 (no detections), 273.1ms
Speed: 1.0ms preprocess, 273.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5znRjUJ6v2opAI1yRN1eQ_180.JPG: 480x640 (no detections), 280.1ms
Speed: 1.1ms preprocess, 280.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/5/z5znRjUJ6v2opAI1yRN1eQ_270.JPG: 480x640 (no detections), 280.7ms
Speed: 1.1ms preprocess, 280.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z62dQDokmvAY9SVdIHB5Jg_0.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z62dQDokmvAY9SVdIHB5Jg_90.JPG: 480x640 (no detections), 278.7ms
Speed: 1.0ms preprocess, 278.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z62dQDokmvAY9SVdIHB5Jg_180.JPG: 480x640 (no detections), 279.1ms
Speed: 1.1ms preprocess, 279.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z62dQDokmvAY9SVdIHB5Jg_270.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z64v4mjNGxNei83XFzekuw_0.JPG: 480x640 2 Wastes, 273.6ms
Speed: 1.1ms preprocess, 273.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z64v4mjNGxNei83XFzekuw_90.JPG: 480x640 (no detections), 274.7ms
Speed: 1.1ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z64v4mjNGxNei83XFzekuw_180.JPG: 480x640 (no detections), 276.0ms
Speed: 1.1ms preprocess, 276.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z64v4mjNGxNei83XFzekuw_270.JPG: 480x640 1 Waste, 273.9ms
Speed: 1.1ms preprocess, 273.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z665JcQD4qbIxyaBWNXa8w_0.JPG: 480x640 (no detections), 273.1ms
Speed: 1.2ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z665JcQD4qbIxyaBWNXa8w_90.JPG: 480x640 (no detections), 274.4ms
Speed: 1.0ms preprocess, 274.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z665JcQD4qbIxyaBWNXa8w_180.JPG: 480x640 (no detections), 270.4ms
Speed: 1.1ms preprocess, 270.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z665JcQD4qbIxyaBWNXa8w_270.JPG: 480x640 (no detections), 269.6ms
Speed: 1.1ms preprocess, 269.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z67rEz5gRIEuoTbW6ouh7g_0.JPG: 480x640 (no detections), 274.7ms
Speed: 1.2ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z67rEz5gRIEuoTbW6ouh7g_90.JPG: 480x640 (no detections), 275.4ms
Speed: 1.2ms preprocess, 275.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z67rEz5gRIEuoTbW6ouh7g_180.JPG: 480x640 (no detections), 278.3ms
Speed: 1.1ms preprocess, 278.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z67rEz5gRIEuoTbW6ouh7g_270.JPG: 480x640 (no detections), 276.0ms
Speed: 1.2ms preprocess, 276.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6DUtsrDrzChED0zPrpkZQ_0.JPG: 480x640 (no detections), 277.9ms
Speed: 1.1ms preprocess, 277.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6DUtsrDrzChED0zPrpkZQ_90.JPG: 480x640 (no detections), 275.0ms
Speed: 1.1ms preprocess, 275.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6DUtsrDrzChED0zPrpkZQ_180.JPG: 480x640 (no detections), 273.4ms
Speed: 1.1ms preprocess, 273.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6DUtsrDrzChED0zPrpkZQ_270.JPG: 480x640 (no detections), 271.3ms
Speed: 1.0ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6HPttQNvUYnX6Rc0ZH3OQ_0.JPG: 480x640 (no detections), 273.9ms
Speed: 1.1ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6HPttQNvUYnX6Rc0ZH3OQ_90.JPG: 480x640 (no detections), 276.2ms
Speed: 1.0ms preprocess, 276.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6HPttQNvUYnX6Rc0ZH3OQ_180.JPG: 480x640 (no detections), 276.0ms
Speed: 1.1ms preprocess, 276.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6HPttQNvUYnX6Rc0ZH3OQ_270.JPG: 480x640 (no detections), 271.3ms
Speed: 1.0ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6Ix217gOgUOhUId6U2skA_0.JPG: 480x640 (no detections), 275.8ms
Speed: 1.1ms preprocess, 275.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6Ix217gOgUOhUId6U2skA_90.JPG: 480x640 (no detections), 268.9ms
Speed: 1.1ms preprocess, 268.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6Ix217gOgUOhUId6U2skA_180.JPG: 480x640 (no detections), 271.5ms
Speed: 1.0ms preprocess, 271.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6Ix217gOgUOhUId6U2skA_270.JPG: 480x640 (no detections), 276.1ms
Speed: 1.3ms preprocess, 276.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6Lig4s3vgnrsu5lm2ihdg_0.JPG: 480x640 (no detections), 277.9ms
Speed: 1.2ms preprocess, 277.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6Lig4s3vgnrsu5lm2ihdg_90.JPG: 480x640 (no detections), 272.2ms

Speed: 1.1ms preprocess, 272.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6Lig4s3vgnrsu5lm2ihdg_180.JPG: 480x640 (no detections), 273.4ms
Speed: 1.0ms preprocess, 273.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6Lig4s3vgnrsu5lm2ihdg_270.JPG: 480x640 (no detections), 267.9ms
Speed: 1.1ms preprocess, 267.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6RExNaPM0S8IgaLQSuokA_0.JPG: 480x640 (no detections), 274.5ms
Speed: 1.1ms preprocess, 274.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6RExNaPM0S8IgaLQSuokA_90.JPG: 480x640 (no detections), 279.5ms
Speed: 1.2ms preprocess, 279.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6RExNaPM0S8IgaLQSuokA_180.JPG: 480x640 (no detections), 277.5ms
Speed: 1.1ms preprocess, 277.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6RExNaPM0S8IgaLQSuokA_270.JPG: 480x640 2 Wastes, 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6RjbH2rtoVAbKcosN5fgg_0.JPG: 480x640 (no detections), 273.4ms
Speed: 1.1ms preprocess, 273.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6RjbH2rtoVAbKcosN5fgg_90.JPG: 480x640 (no detections), 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6RjbH2rtoVAbKcosN5fgg_180.JPG: 480x640 (no detections), 272.1ms
Speed: 1.0ms preprocess, 272.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6RjbH2rtoVAbKcosN5fgg_270.JPG: 480x640 (no detections), 277.0ms
Speed: 1.1ms preprocess, 277.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6Rov5Thynx1jTH63UB77Q_0.JPG: 480x640 (no detections), 274.4ms
Speed: 1.0ms preprocess, 274.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6Rov5Thynx1jTH63UB77Q_90.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6Rov5Thynx1jTH63UB77Q_180.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6Rov5Thynx1jTH63UB77Q_270.JPG: 480x640 (no detections), 276.8ms
Speed: 1.0ms preprocess, 276.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6SjwNOOEU11y_yx2nAMgw_0.JPG: 480x640 (no detections), 276.5ms
Speed: 1.0ms preprocess, 276.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6SjwNOOEU11y_yx2nAMgw_90.JPG: 480x640 (no detections), 272.7ms
Speed: 1.0ms preprocess, 272.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6SjwNOOEU11y_yx2nAMgw_180.JPG: 480x640 (no detections), 274.6ms
Speed: 1.0ms preprocess, 274.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6SjwNOOEU11y_yx2nAMgw_270.JPG: 480x640 (no detections), 276.1ms
Speed: 1.1ms preprocess, 276.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6WgI5zYBW99d6K6ffylDA_0.JPG: 480x640 (no detections), 272.4ms
Speed: 1.2ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6WgI5zYBW99d6K6ffylDA_90.JPG: 480x640 (no detections), 274.0ms
Speed: 1.1ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6WgI5zYBW99d6K6ffylDA_180.JPG: 480x640 (no detections), 274.6ms
Speed: 1.0ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6WgI5zYBW99d6K6ffylDA_270.JPG: 480x640 (no detections), 270.8ms
Speed: 1.0ms preprocess, 270.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6YaDtJqgcT7SCO7PUxxuQ_0.JPG: 480x640 (no detections), 274.7ms
Speed: 1.3ms preprocess, 274.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6YaDtJqgcT7SCO7PUxxuQ_90.JPG: 480x640 (no detections), 274.0ms
Speed: 1.0ms preprocess, 274.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6YaDtJqgcT7SCO7PUxxuQ_180.JPG: 480x640 (no detections), 273.3ms
Speed: 1.0ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6YaDtJqgcT7SCO7PUxxuQ_270.JPG: 480x640 (no detections), 271.9ms
Speed: 1.0ms preprocess, 271.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6YhOSTlgCd7_vR8CL6m3g_0.JPG: 480x640 (no detections), 279.5ms
Speed: 1.2ms preprocess, 279.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6YhOSTlgCd7_vR8CL6m3g_90.JPG: 480x640 (no detections), 269.2ms
Speed: 1.1ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6YhOSTlgCd7_vR8CL6m3g_180.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6YhOSTlgCd7_vR8CL6m3g_270.JPG: 480x640 (no detections), 270.3ms
Speed: 1.1ms preprocess, 270.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6ZMJlIKbU9fhUorEeLZzA_0.JPG: 480x640 (no detections), 270.9ms
Speed: 1.1ms preprocess, 270.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6ZMJlIKbU9fhUorEeLZzA_90.JPG: 480x640 (no detections), 271.8ms
Speed: 1.0ms preprocess, 271.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6ZMJlIKbU9fhUorEeLZzA_180.JPG: 480x640 (no detections), 280.6ms
Speed: 1.0ms preprocess, 280.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6ZMJlIKbU9fhUorEeLZzA_270.JPG: 480x640 (no detections), 275.1ms
Speed: 1.0ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6gaNIYdQ4I6B9f3T1x_OQ_0.JPG: 480x640 (no detections), 270.5ms
Speed: 1.1ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6gaNIYdQ4I6B9f3T1x_OQ_90.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6gaNIYdQ4I6B9f3T1x_OQ_180.JPG: 480x640 (no detections), 276.2ms
Speed: 1.2ms preprocess, 276.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6gaNIYdQ4I6B9f3T1x_OQ_270.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6h1nn4uzdwIgrHyVLWTuA_0.JPG: 480x640 (no detections), 278.2ms
Speed: 1.0ms preprocess, 278.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6h1nn4uzdwIgrHyVLWTuA_90.JPG: 480x640 (no detections), 287.1ms
Speed: 1.1ms preprocess, 287.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6h1nn4uzdwIgrHyVLWTuA_180.JPG: 480x640 (no detections), 275.5ms
Speed: 1.1ms preprocess, 275.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6h1nn4uzdwIgrHyVLWTuA_270.JPG: 480x640 (no detections), 274.8ms
Speed: 1.0ms preprocess, 274.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6iZs-CCrqZVHS-qkJmVMg_0.JPG: 480x640 (no detections), 278.4ms
Speed: 1.1ms preprocess, 278.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6iZs-CCrqZVHS-qkJmVMg_90.JPG: 480x640 (no detections), 276.9ms
Speed: 1.1ms preprocess, 276.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6iZs-CCrqZVHS-qkJmVMg_180.JPG: 480x640 (no detections), 280.0ms
Speed: 1.0ms preprocess, 280.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6iZs-CCrqZVHS-qkJmVMg_270.JPG: 480x640 (no detections), 274.8ms
Speed: 1.2ms preprocess, 274.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6j5-0IvBkvnmHoWZ3Yt4g_0.JPG: 480x640 (no detections), 278.0ms
Speed: 1.0ms preprocess, 278.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6j5-0IvBkvnmHoWZ3Yt4g_90.JPG: 480x640 (no detections), 277.5ms
Speed: 1.2ms preprocess, 277.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6j5-0IvBkvnmHoWZ3Yt4g_180.JPG: 480x640 (no detections), 272.9ms
Speed: 1.3ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6j5-0IvBkvnmHoWZ3Yt4g_270.JPG: 480x640 (no detections), 273.6ms
Speed: 1.2ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6jVs1cp8HgL9nicXB1u-A_0.JPG: 480x640 (no detections), 278.0ms
Speed: 1.4ms preprocess, 278.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6jVs1cp8HgL9nicXB1u-A_90.JPG: 480x640 (no detections), 275.5ms
Speed: 1.1ms preprocess, 275.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6jVs1cp8HgL9nicXB1u-A_180.JPG: 480x640 (no detections), 275.3ms
Speed: 1.1ms preprocess, 275.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6jVs1cp8HgL9nicXB1u-A_270.JPG: 480x640 (no detections), 280.2ms
Speed: 1.1ms preprocess, 280.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6kBQY-vbk-ohYrwOfzhpQ_0.JPG: 480x640 (no detections), 276.9ms
Speed: 1.2ms preprocess, 276.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6kBQY-vbk-ohYrwOfzhpQ_90.JPG: 480x640 (no detections), 269.8ms
Speed: 1.1ms preprocess, 269.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6kBQY-vbk-ohYrwOfzhpQ_180.JPG: 480x640 (no detections), 277.8ms
Speed: 1.1ms preprocess, 277.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6kBQY-vbk-ohYrwOfzhpQ_270.JPG: 480x640 (no detections), 279.0ms
Speed: 1.1ms preprocess, 279.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6nTx58DVNDeHZVterc2DA_0.JPG: 480x640 (no detections), 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6nTx58DVNDeHZVterc2DA_90.JPG: 480x640 (no detections), 275.0ms
Speed: 1.0ms preprocess, 275.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6nTx58DVNDeHZVterc2DA_180.JPG: 480x640 (no detections), 276.3ms
Speed: 1.0ms preprocess, 276.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6nTx58DVNDeHZVterc2DA_270.JPG: 480x640 (no detections), 273.2ms
Speed: 1.1ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6nuLzMqEmVhPzA40AGXSw_0.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6nuLzMqEmVhPzA40AGXSw_90.JPG: 480x640 (no detections), 277.4ms
Speed: 1.0ms preprocess, 277.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6nuLzMqEmVhPzA40AGXSw_180.JPG: 480x640 (no detections), 274.7ms
Speed: 1.0ms preprocess, 274.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6nuLzMqEmVhPzA40AGXSw_270.JPG: 480x640 (no detections), 274.3ms
Speed: 1.1ms preprocess, 274.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6oaltI0FadGoI0V2ymdHw_0.JPG: 480x640 (no detections), 272.5ms

Speed: 1.1ms preprocess, 272.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6oaltI0FadGoI0V2ymdHw_90.JPG: 480x640 (no detections), 278.8ms
Speed: 1.2ms preprocess, 278.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6oaltI0FadGoI0V2ymdHw_180.JPG: 480x640 (no detections), 276.8ms
Speed: 1.0ms preprocess, 276.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6oaltI0FadGoI0V2ymdHw_270.JPG: 480x640 (no detections), 275.0ms
Speed: 1.1ms preprocess, 275.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6tF84566CaVg62JPsubAA_0.JPG: 480x640 (no detections), 277.8ms
Speed: 0.9ms preprocess, 277.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6tF84566CaVg62JPsubAA_90.JPG: 480x640 (no detections), 276.9ms
Speed: 1.1ms preprocess, 276.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6tF84566CaVg62JPsubAA_180.JPG: 480x640 (no detections), 274.9ms
Speed: 1.0ms preprocess, 274.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6tF84566CaVg62JPsubAA_270.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6v8Jw2aK4HPjivCh73-vA_0.JPG: 480x640 (no detections), 275.7ms
Speed: 1.1ms preprocess, 275.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6v8Jw2aK4HPjivCh73-vA_90.JPG: 480x640 (no detections), 276.3ms
Speed: 1.1ms preprocess, 276.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6v8Jw2aK4HPjivCh73-vA_180.JPG: 480x640 (no detections), 277.4ms
Speed: 1.2ms preprocess, 277.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6v8Jw2aK4HPjivCh73-vA_270.JPG: 480x640 1 Waste, 276.0ms
Speed: 1.1ms preprocess, 276.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6wcCvzIb9tmuLr5wycTow_0.JPG: 480x640 (no detections), 273.3ms
Speed: 1.2ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6wcCvzIb9tmuLr5wycTow_90.JPG: 480x640 1 Waste, 279.5ms
Speed: 1.1ms preprocess, 279.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6wcCvzIb9tmuLr5wycTow_180.JPG: 480x640 (no detections), 275.2ms
Speed: 1.0ms preprocess, 275.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6wcCvzIb9tmuLr5wycTow_270.JPG: 480x640 (no detections), 272.4ms
Speed: 1.1ms preprocess, 272.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6xVbhkYPMXv7Pjdf3JoMA_0.JPG: 480x640 (no detections), 276.3ms
Speed: 1.0ms preprocess, 276.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6xVbhkYPMXv7Pjdf3JoMA_90.JPG: 480x640 (no detections), 274.0ms
Speed: 1.0ms preprocess, 274.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6xVbhkYPMXv7Pjdf3JoMA_180.JPG: 480x640 (no detections), 273.2ms
Speed: 1.0ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/6/z6xVbhkYPMXv7Pjdf3JoMA_270.JPG: 480x640 (no detections), 270.8ms
Speed: 1.0ms preprocess, 270.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z71ru83oY2B4QkKjnZQRbw_0.JPG: 480x640 (no detections), 277.8ms
Speed: 1.1ms preprocess, 277.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z71ru83oY2B4QkKjnZQRbw_90.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z71ru83oY2B4QkKjnZQRbw_180.JPG: 480x640 (no detections), 281.5ms
Speed: 1.1ms preprocess, 281.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z71ru83oY2B4QkKjnZQRbw_270.JPG: 480x640 (no detections), 278.7ms
Speed: 1.1ms preprocess, 278.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z731IfZdW_u0bDNSZSN7UQ_0.JPG: 480x640 (no detections), 274.2ms
Speed: 1.2ms preprocess, 274.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z731IfZdW_u0bDNSZSN7UQ_90.JPG: 480x640 (no detections), 275.3ms
Speed: 1.0ms preprocess, 275.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z731IfZdW_u0bDNSZSN7UQ_180.JPG: 480x640 (no detections), 277.0ms
Speed: 1.1ms preprocess, 277.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z731IfZdW_u0bDNSZSN7UQ_270.JPG: 480x640 (no detections), 280.3ms
Speed: 1.0ms preprocess, 280.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z75voXxo7qC3WhOSWjQ3hQ_0.JPG: 480x640 (no detections), 275.6ms
Speed: 1.1ms preprocess, 275.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z75voXxo7qC3WhOSWjQ3hQ_90.JPG: 480x640 (no detections), 281.6ms
Speed: 1.2ms preprocess, 281.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z75voXxo7qC3WhOSWjQ3hQ_180.JPG: 480x640 (no detections), 275.0ms
Speed: 1.1ms preprocess, 275.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z75voXxo7qC3WhOSWjQ3hQ_270.JPG: 480x640 (no detections), 275.4ms
Speed: 1.3ms preprocess, 275.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z79FxWQPqTu2Sy-erYowbA_0.JPG: 480x640 1 Waste, 278.2ms
Speed: 1.1ms preprocess, 278.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z79FxWQPqTu2Sy-erYowbA_90.JPG: 480x640 (no detections), 274.5ms
Speed: 1.1ms preprocess, 274.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z79FxWQPqTu2Sy-erYowbA_180.JPG: 480x640 (no detections), 272.4ms
Speed: 1.1ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z79FxWQPqTu2Sy-erYowbA_270.JPG: 480x640 (no detections), 272.7ms
Speed: 1.0ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7AY5ZtmQdgcnSkKdNX_gQ_0.JPG: 480x640 (no detections), 271.2ms
Speed: 1.0ms preprocess, 271.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7AY5ZtmQdgcnSkKdNX_gQ_90.JPG: 480x640 (no detections), 274.4ms
Speed: 1.1ms preprocess, 274.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7AY5ZtmQdgcnSkKdNX_gQ_180.JPG: 480x640 (no detections), 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7AY5ZtmQdgcnSkKdNX_gQ_270.JPG: 480x640 (no detections), 304.3ms
Speed: 1.1ms preprocess, 304.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7EfIc_FLPH7PfGKE7s1Ww_0.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7EfIc_FLPH7PfGKE7s1Ww_90.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7EfIc_FLPH7PfGKE7s1Ww_180.JPG: 480x640 (no detections), 273.3ms
Speed: 1.0ms preprocess, 273.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7EfIc_FLPH7PfGKE7s1Ww_270.JPG: 480x640 (no detections), 278.0ms
Speed: 1.1ms preprocess, 278.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7H6P2NkY60zG2W3V6j_1g_0.JPG: 480x640 (no detections), 274.2ms
Speed: 1.1ms preprocess, 274.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7H6P2NkY60zG2W3V6j_1g_90.JPG: 480x640 (no detections), 273.8ms
Speed: 1.3ms preprocess, 273.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7H6P2NkY60zG2W3V6j_1g_180.JPG: 480x640 (no detections), 271.5ms
Speed: 1.0ms preprocess, 271.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7H6P2NkY60zG2W3V6j_1g_270.JPG: 480x640 (no detections), 274.0ms
Speed: 1.9ms preprocess, 274.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7IK-MXrULkwH_EvLiyEkQ_0.JPG: 480x640 (no detections), 274.5ms
Speed: 1.0ms preprocess, 274.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7IK-MXrULkwH_EvLiyEkQ_90.JPG: 480x640 (no detections), 280.6ms
Speed: 1.0ms preprocess, 280.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7IK-MXrULkwH_EvLiyEkQ_180.JPG: 480x640 (no detections), 276.2ms
Speed: 1.0ms preprocess, 276.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7IK-MXrULkwH_EvLiyEkQ_270.JPG: 480x640 (no detections), 280.2ms
Speed: 1.1ms preprocess, 280.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7Ng2XMIcDmvr-Ph3iblYQ_0.JPG: 480x640 (no detections), 272.3ms
Speed: 1.2ms preprocess, 272.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7Ng2XMIcDmvr-Ph3iblYQ_90.JPG: 480x640 (no detections), 273.7ms
Speed: 1.3ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7Ng2XMIcDmvr-Ph3iblYQ_180.JPG: 480x640 (no detections), 273.3ms
Speed: 1.0ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7Ng2XMIcDmvr-Ph3iblYQ_270.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7OT9J84mtpEWxlReiayWA_0.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7OT9J84mtpEWxlReiayWA_90.JPG: 480x640 (no detections), 273.1ms
Speed: 1.0ms preprocess, 273.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7OT9J84mtpEWxlReiayWA_180.JPG: 480x640 (no detections), 272.9ms
Speed: 1.0ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7OT9J84mtpEWxlReiayWA_270.JPG: 480x640 (no detections), 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7Qp3mq2Q_u1oYaz8v2Jog_0.JPG: 480x640 (no detections), 275.2ms
Speed: 1.1ms preprocess, 275.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7Qp3mq2Q_u1oYaz8v2Jog_90.JPG: 480x640 (no detections), 273.0ms
Speed: 1.0ms preprocess, 273.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7Qp3mq2Q_u1oYaz8v2Jog_180.JPG: 480x640 (no detections), 276.6ms
Speed: 1.0ms preprocess, 276.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7Qp3mq2Q_u1oYaz8v2Jog_270.JPG: 480x640 (no detections), 281.0ms
Speed: 1.0ms preprocess, 281.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7QuGCpfn3Z2L_3wqm-S4g_0.JPG: 480x640 (no detections), 273.7ms
Speed: 1.0ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7QuGCpfn3Z2L_3wqm-S4g_90.JPG: 480x640 (no detections), 280.7ms
Speed: 1.1ms preprocess, 280.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7QuGCpfn3Z2L_3wqm-S4g_180.JPG: 480x640 (no detections), 276.1ms
Speed: 1.2ms preprocess, 276.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7QuGCpfn3Z2L_3wqm-S4g_270.JPG: 480x640 (no detections), 270.8ms

Speed: 1.1ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7RlfiteL--z4rv8fs6XXA_0.JPG: 480x640 (no detections), 268.5ms
Speed: 1.1ms preprocess, 268.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7RlfiteL--z4rv8fs6XXA_90.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7RlfiteL--z4rv8fs6XXA_180.JPG: 480x640 (no detections), 275.3ms
Speed: 1.1ms preprocess, 275.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7RlfiteL--z4rv8fs6XXA_270.JPG: 480x640 (no detections), 272.7ms
Speed: 1.0ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7VelnCfBJrxzxFCkiDCsQ_0.JPG: 480x640 (no detections), 277.0ms
Speed: 1.1ms preprocess, 277.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7VelnCfBJrxzxFCkiDCsQ_90.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7VelnCfBJrxzxFCkiDCsQ_180.JPG: 480x640 (no detections), 278.1ms
Speed: 1.0ms preprocess, 278.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7VelnCfBJrxzxFCkiDCsQ_270.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7WF1F5Pd4V4XUT523UevQ_0.JPG: 480x640 (no detections), 279.4ms
Speed: 1.1ms preprocess, 279.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7WF1F5Pd4V4XUT523UevQ_90.JPG: 480x640 (no detections), 272.4ms
Speed: 1.0ms preprocess, 272.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7WF1F5Pd4V4XUT523UevQ_180.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7WF1F5Pd4V4XUT523UevQ_270.JPG: 480x640 (no detections), 277.1ms
Speed: 1.1ms preprocess, 277.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7ZMq-tNiRqIga_euvkSRw_0.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7ZMq-tNiRqIga_euvkSRw_90.JPG: 480x640 (no detections), 271.4ms
Speed: 1.0ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7ZMq-tNiRqIga_euvkSRw_180.JPG: 480x640 (no detections), 288.9ms
Speed: 1.1ms preprocess, 288.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7ZMq-tNiRqIga_euvkSRw_270.JPG: 480x640 (no detections), 276.1ms
Speed: 1.1ms preprocess, 276.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7cPZI9fj28087yZQ46-Rw_0.JPG: 480x640 (no detections), 275.0ms
Speed: 1.2ms preprocess, 275.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7cPZI9fj28087yZQ46-Rw_90.JPG: 480x640 (no detections), 274.8ms
Speed: 1.1ms preprocess, 274.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7cPZI9fj28087yZQ46-Rw_180.JPG: 480x640 (no detections), 277.8ms
Speed: 1.0ms preprocess, 277.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7cPZI9fj28087yZQ46-Rw_270.JPG: 480x640 (no detections), 273.6ms
Speed: 1.1ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7c__a3VxHBjTM7Loz6z8w_0.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7c__a3VxHBjTM7Loz6z8w_90.JPG: 480x640 (no detections), 278.4ms
Speed: 1.0ms preprocess, 278.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7c__a3VxHBjTM7Loz6z8w_180.JPG: 480x640 (no detections), 273.7ms
Speed: 1.0ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7c__a3VxHBjTM7Loz6z8w_270.JPG: 480x640 (no detections), 275.6ms
Speed: 1.2ms preprocess, 275.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7e2_zUnj4eM9cFhk3cVFw_0.JPG: 480x640 (no detections), 271.6ms
Speed: 1.2ms preprocess, 271.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7e2_zUnj4eM9cFhk3cVFw_90.JPG: 480x640 (no detections), 275.4ms
Speed: 1.1ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7e2_zUnj4eM9cFhk3cVFw_180.JPG: 480x640 (no detections), 277.2ms
Speed: 1.1ms preprocess, 277.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7e2_zUnj4eM9cFhk3cVFw_270.JPG: 480x640 1 Waste, 272.4ms
Speed: 1.2ms preprocess, 272.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7jdSk4g3TKRbrF0dWXGRA_0.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7jdSk4g3TKRbrF0dWXGRA_90.JPG: 480x640 (no detections), 274.4ms
Speed: 1.0ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7jdSk4g3TKRbrF0dWXGRA_180.JPG: 480x640 (no detections), 272.1ms
Speed: 1.1ms preprocess, 272.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7jdSk4g3TKRbrF0dWXGRA_270.JPG: 480x640 (no detections), 272.7ms
Speed: 1.0ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7k56v_OgflTW6NTmtGWEA_0.JPG: 480x640 (no detections), 273.3ms
Speed: 1.0ms preprocess, 273.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7k56v_OgflTW6NTmtGWEA_90.JPG: 480x640 (no detections), 277.5ms
Speed: 1.1ms preprocess, 277.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7k56v_OgflTW6NTmtGWEA_180.JPG: 480x640 (no detections), 273.2ms
Speed: 1.1ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7k56v_OgflTW6NTmtGWEA_270.JPG: 480x640 (no detections), 272.1ms
Speed: 1.1ms preprocess, 272.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7kSNDw80T6ohQyaE7ZWNw_0.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7kSNDw80T6ohQyaE7ZWNw_90.JPG: 480x640 (no detections), 278.2ms
Speed: 1.1ms preprocess, 278.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7kSNDw80T6ohQyaE7ZWNw_180.JPG: 480x640 (no detections), 276.1ms
Speed: 1.2ms preprocess, 276.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7kSNDw80T6ohQyaE7ZWNw_270.JPG: 480x640 (no detections), 275.6ms
Speed: 1.0ms preprocess, 275.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7n1P-aGf18wBiUiEkGdxg_0.JPG: 480x640 (no detections), 272.8ms
Speed: 1.0ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7n1P-aGf18wBiUiEkGdxg_90.JPG: 480x640 (no detections), 273.1ms
Speed: 1.1ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7n1P-aGf18wBiUiEkGdxg_180.JPG: 480x640 (no detections), 273.6ms
Speed: 1.1ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7n1P-aGf18wBiUiEkGdxg_270.JPG: 480x640 (no detections), 278.7ms
Speed: 1.1ms preprocess, 278.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7uck7tTlYafi4uYaXY2Zg_0.JPG: 480x640 (no detections), 294.1ms
Speed: 1.1ms preprocess, 294.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7uck7tTlYafi4uYaXY2Zg_90.JPG: 480x640 (no detections), 278.5ms
Speed: 1.3ms preprocess, 278.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7uck7tTlYafi4uYaXY2Zg_180.JPG: 480x640 (no detections), 268.7ms
Speed: 1.2ms preprocess, 268.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7uck7tTlYafi4uYaXY2Zg_270.JPG: 480x640 (no detections), 274.6ms
Speed: 1.0ms preprocess, 274.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7vpEIPJYqGuUe5OX3aOuA_0.JPG: 480x640 (no detections), 270.5ms
Speed: 1.0ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7vpEIPJYqGuUe5OX3aOuA_90.JPG: 480x640 (no detections), 275.2ms
Speed: 1.1ms preprocess, 275.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7vpEIPJYqGuUe5OX3aOuA_180.JPG: 480x640 (no detections), 270.3ms
Speed: 1.1ms preprocess, 270.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7vpEIPJYqGuUe5OX3aOuA_270.JPG: 480x640 (no detections), 272.5ms
Speed: 1.0ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7wZirC-SqN6pKsdzvCB6A_0.JPG: 480x640 (no detections), 275.9ms
Speed: 1.0ms preprocess, 275.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7wZirC-SqN6pKsdzvCB6A_90.JPG: 480x640 (no detections), 278.9ms
Speed: 1.2ms preprocess, 278.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7wZirC-SqN6pKsdzvCB6A_180.JPG: 480x640 (no detections), 292.0ms
Speed: 1.6ms preprocess, 292.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/7/z7wZirC-SqN6pKsdzvCB6A_270.JPG: 480x640 (no detections), 285.4ms
Speed: 1.1ms preprocess, 285.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z805OX_qyPq-pK9KoAnh2g_0.JPG: 480x640 (no detections), 280.0ms
Speed: 1.1ms preprocess, 280.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z805OX_qyPq-pK9KoAnh2g_90.JPG: 480x640 (no detections), 277.3ms
Speed: 1.2ms preprocess, 277.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z805OX_qyPq-pK9KoAnh2g_180.JPG: 480x640 (no detections), 274.5ms
Speed: 1.1ms preprocess, 274.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z805OX_qyPq-pK9KoAnh2g_270.JPG: 480x640 (no detections), 277.9ms
Speed: 1.0ms preprocess, 277.9ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z82HXM5b5Mg56O5p2Xtrsg_0.JPG: 480x640 (no detections), 280.7ms
Speed: 1.1ms preprocess, 280.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z82HXM5b5Mg56O5p2Xtrsg_90.JPG: 480x640 (no detections), 376.2ms
Speed: 1.1ms preprocess, 376.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z82HXM5b5Mg56O5p2Xtrsg_180.JPG: 480x640 (no detections), 329.7ms
Speed: 1.3ms preprocess, 329.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z82HXM5b5Mg56O5p2Xtrsg_270.JPG: 480x640 (no detections), 329.2ms
Speed: 1.2ms preprocess, 329.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z83xuRB727YcE4YOZh10eg_0.JPG: 480x640 (no detections), 294.4ms
Speed: 1.5ms preprocess, 294.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z83xuRB727YcE4YOZh10eg_90.JPG: 480x640 (no detections), 306.9ms
Speed: 1.2ms preprocess, 306.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z83xuRB727YcE4YOZh10eg_180.JPG: 480x640 (no detections), 281.4ms

Speed: 1.1ms preprocess, 281.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z83xuRB727YcE4YOZh10eg_270.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z85-AKh8LYf7dGvPnWruig_0.JPG: 480x640 (no detections), 276.1ms
Speed: 1.2ms preprocess, 276.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z85-AKh8LYf7dGvPnWruig_90.JPG: 480x640 (no detections), 274.4ms
Speed: 1.0ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z85-AKh8LYf7dGvPnWruig_180.JPG: 480x640 (no detections), 279.7ms
Speed: 1.0ms preprocess, 279.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z85-AKh8LYf7dGvPnWruig_270.JPG: 480x640 (no detections), 281.3ms
Speed: 1.2ms preprocess, 281.3ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z86RRcBXFZfqFkZzVuzxVg_0.JPG: 480x640 (no detections), 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z86RRcBXFZfqFkZzVuzxVg_90.JPG: 480x640 (no detections), 275.2ms
Speed: 1.0ms preprocess, 275.2ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z86RRcBXFZfqFkZzVuzxVg_180.JPG: 480x640 (no detections), 282.6ms
Speed: 1.0ms preprocess, 282.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z86RRcBXFZfqFkZzVuzxVg_270.JPG: 480x640 (no detections), 276.4ms
Speed: 1.1ms preprocess, 276.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z86XskHnI7R2N6_dEH6CHA_0.JPG: 480x640 (no detections), 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z86XskHnI7R2N6_dEH6CHA_90.JPG: 480x640 (no detections), 273.4ms
Speed: 1.0ms preprocess, 273.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z86XskHnI7R2N6_dEH6CHA_180.JPG: 480x640 (no detections), 277.7ms
Speed: 1.1ms preprocess, 277.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z86XskHnI7R2N6_dEH6CHA_270.JPG: 480x640 (no detections), 277.3ms
Speed: 1.0ms preprocess, 277.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8A1NVNkydpASNBA2AtQJQ_0.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8A1NVNkydpASNBA2AtQJQ_90.JPG: 480x640 (no detections), 275.5ms
Speed: 1.1ms preprocess, 275.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8A1NVNkydpASNBA2AtQJQ_180.JPG: 480x640 (no detections), 273.1ms
Speed: 1.1ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8A1NVNkydpASNBA2AtQJQ_270.JPG: 480x640 (no detections), 277.3ms
Speed: 1.0ms preprocess, 277.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8A_Lnm94n152QJXq4fUTw_0.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8A_Lnm94n152QJXq4fUTw_90.JPG: 480x640 (no detections), 271.3ms
Speed: 1.6ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8A_Lnm94n152QJXq4fUTw_180.JPG: 480x640 (no detections), 273.4ms
Speed: 1.1ms preprocess, 273.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8A_Lnm94n152QJXq4fUTw_270.JPG: 480x640 (no detections), 274.8ms
Speed: 1.1ms preprocess, 274.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8C6V_ylBVxs1u1xYy5ziA_0.JPG: 480x640 (no detections), 277.0ms
Speed: 1.3ms preprocess, 277.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8C6V_ylBVxs1u1xYy5ziA_90.JPG: 480x640 (no detections), 274.2ms
Speed: 1.1ms preprocess, 274.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8C6V_ylBVxs1u1xYy5ziA_180.JPG: 480x640 (no detections), 275.7ms
Speed: 1.1ms preprocess, 275.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8C6V_ylBVxs1u1xYy5ziA_270.JPG: 480x640 (no detections), 277.5ms
Speed: 1.1ms preprocess, 277.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8CEhB8i2W3EKWZVVZjKMQ_0.JPG: 480x640 (no detections), 274.6ms
Speed: 1.0ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8CEhB8i2W3EKWZVVZjKMQ_90.JPG: 480x640 (no detections), 273.1ms
Speed: 1.1ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8CEhB8i2W3EKWZVVZjKMQ_180.JPG: 480x640 (no detections), 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8CEhB8i2W3EKWZVVZjKMQ_270.JPG: 480x640 (no detections), 274.4ms
Speed: 1.0ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8MvuiaHVH1NnpjgK7qI3Q_0.JPG: 480x640 (no detections), 277.8ms
Speed: 1.1ms preprocess, 277.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8MvuiaHVH1NnpjgK7qI3Q_90.JPG: 480x640 (no detections), 275.3ms
Speed: 1.4ms preprocess, 275.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8MvuiaHVH1NnpjgK7qI3Q_180.JPG: 480x640 (no detections), 273.4ms
Speed: 1.1ms preprocess, 273.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8MvuiaHVH1NnpjgK7qI3Q_270.JPG: 480x640 (no detections), 276.4ms
Speed: 1.0ms preprocess, 276.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8PJgh1ip7hCB-pPW-BGIg_0.JPG: 480x640 (no detections), 276.9ms
Speed: 1.1ms preprocess, 276.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8PJgh1ip7hCB-pPW-BGIg_90.JPG: 480x640 (no detections), 274.1ms
Speed: 1.2ms preprocess, 274.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8PJgh1ip7hCB-pPW-BGIg_180.JPG: 480x640 (no detections), 283.2ms
Speed: 1.0ms preprocess, 283.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8PJgh1ip7hCB-pPW-BGIg_270.JPG: 480x640 (no detections), 281.3ms
Speed: 1.4ms preprocess, 281.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8QNPDedxNB4s1haKUyp7A_0.JPG: 480x640 (no detections), 275.3ms
Speed: 1.2ms preprocess, 275.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8QNPDedxNB4s1haKUyp7A_90.JPG: 480x640 (no detections), 272.2ms
Speed: 1.0ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8QNPDedxNB4s1haKUyp7A_180.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8QNPDedxNB4s1haKUyp7A_270.JPG: 480x640 (no detections), 274.9ms
Speed: 1.1ms preprocess, 274.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8Qy-xRoub07k92PqOAIOA_0.JPG: 480x640 (no detections), 271.4ms
Speed: 1.0ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8Qy-xRoub07k92PqOAIOA_90.JPG: 480x640 (no detections), 275.2ms
Speed: 1.1ms preprocess, 275.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8Qy-xRoub07k92PqOAIOA_180.JPG: 480x640 (no detections), 269.3ms
Speed: 1.1ms preprocess, 269.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8Qy-xRoub07k92PqOAIOA_270.JPG: 480x640 (no detections), 274.7ms
Speed: 1.1ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8SCWQl2Ec26ZLjMhg8IOw_0.JPG: 480x640 (no detections), 274.2ms
Speed: 1.1ms preprocess, 274.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8SCWQl2Ec26ZLjMhg8IOw_90.JPG: 480x640 (no detections), 304.8ms
Speed: 1.0ms preprocess, 304.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8SCWQl2Ec26ZLjMhg8IOw_180.JPG: 480x640 (no detections), 279.5ms
Speed: 1.3ms preprocess, 279.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8SCWQl2Ec26ZLjMhg8IOw_270.JPG: 480x640 (no detections), 277.7ms
Speed: 1.1ms preprocess, 277.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8TTykD1C4_Qs4sc868zSg_0.JPG: 480x640 (no detections), 276.0ms
Speed: 1.1ms preprocess, 276.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8TTykD1C4_Qs4sc868zSg_90.JPG: 480x640 (no detections), 275.3ms
Speed: 1.1ms preprocess, 275.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8TTykD1C4_Qs4sc868zSg_180.JPG: 480x640 (no detections), 276.8ms
Speed: 1.1ms preprocess, 276.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8TTykD1C4_Qs4sc868zSg_270.JPG: 480x640 1 Waste, 273.7ms
Speed: 1.3ms preprocess, 273.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8TzeajlhpsL_MxWgKuN1g_0.JPG: 480x640 (no detections), 270.4ms
Speed: 1.1ms preprocess, 270.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8TzeajlhpsL_MxWgKuN1g_90.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8TzeajlhpsL_MxWgKuN1g_180.JPG: 480x640 (no detections), 279.9ms
Speed: 1.1ms preprocess, 279.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8TzeajlhpsL_MxWgKuN1g_270.JPG: 480x640 (no detections), 278.3ms
Speed: 1.1ms preprocess, 278.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8Y2OFATFIPJxmpgczgfaQ_0.JPG: 480x640 (no detections), 276.0ms
Speed: 1.0ms preprocess, 276.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8Y2OFATFIPJxmpgczgfaQ_90.JPG: 480x640 (no detections), 283.9ms
Speed: 1.5ms preprocess, 283.9ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8Y2OFATFIPJxmpgczgfaQ_180.JPG: 480x640 (no detections), 280.3ms
Speed: 1.1ms preprocess, 280.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8Y2OFATFIPJxmpgczgfaQ_270.JPG: 480x640 (no detections), 282.2ms
Speed: 1.1ms preprocess, 282.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8ZzE5KPWeUdrMDhs607PQ_0.JPG: 480x640 (no detections), 276.6ms
Speed: 1.2ms preprocess, 276.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8ZzE5KPWeUdrMDhs607PQ_90.JPG: 480x640 (no detections), 275.9ms
Speed: 1.1ms preprocess, 275.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8ZzE5KPWeUdrMDhs607PQ_180.JPG: 480x640 (no detections), 275.2ms
Speed: 1.0ms preprocess, 275.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8ZzE5KPWeUdrMDhs607PQ_270.JPG: 480x640 (no detections), 278.1ms
Speed: 1.0ms preprocess, 278.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8dCGgZ_pfu4drqii6skqw_0.JPG: 480x640 (no detections), 361.4ms
Speed: 1.0ms preprocess, 361.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8dCGgZ_pfu4drqii6skqw_90.JPG: 480x640 (no detections), 336.5ms

Speed: 1.0ms preprocess, 336.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8dCGgZ_pfu4drqii6skqw_180.JPG: 480x640 (no detections), 306.7ms
Speed: 1.9ms preprocess, 306.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8dCGgZ_pfu4drqii6skqw_270.JPG: 480x640 (no detections), 303.9ms
Speed: 1.1ms preprocess, 303.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8eUmtWODrSM-bQxLsom0A_0.JPG: 480x640 (no detections), 288.7ms
Speed: 1.6ms preprocess, 288.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8eUmtWODrSM-bQxLsom0A_90.JPG: 480x640 (no detections), 280.9ms
Speed: 1.2ms preprocess, 280.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8eUmtWODrSM-bQxLsom0A_180.JPG: 480x640 (no detections), 276.2ms
Speed: 1.0ms preprocess, 276.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8eUmtWODrSM-bQxLsom0A_270.JPG: 480x640 (no detections), 288.0ms
Speed: 1.1ms preprocess, 288.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8gcFrN20JiiRu-Yx9A4aA_0.JPG: 480x640 (no detections), 297.5ms
Speed: 1.3ms preprocess, 297.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8gcFrN20JiiRu-Yx9A4aA_90.JPG: 480x640 (no detections), 269.4ms
Speed: 1.1ms preprocess, 269.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8gcFrN20JiiRu-Yx9A4aA_180.JPG: 480x640 (no detections), 273.8ms
Speed: 1.2ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8gcFrN20JiiRu-Yx9A4aA_270.JPG: 480x640 (no detections), 276.1ms
Speed: 1.1ms preprocess, 276.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8ihb2rg04n04T61yUtztw_0.JPG: 480x640 (no detections), 272.6ms
Speed: 1.0ms preprocess, 272.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8ihb2rg04n04T61yUtztw_90.JPG: 480x640 (no detections), 281.4ms
Speed: 1.0ms preprocess, 281.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8ihb2rg04n04T61yUtztw_180.JPG: 480x640 (no detections), 278.2ms
Speed: 1.4ms preprocess, 278.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8ihb2rg04n04T61yUtztw_270.JPG: 480x640 (no detections), 273.2ms
Speed: 1.1ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8ksyDUET0qM1aGGy1kmFA_0.JPG: 480x640 (no detections), 273.6ms
Speed: 1.1ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8ksyDUET0qM1aGGy1kmFA_90.JPG: 480x640 (no detections), 274.6ms
Speed: 1.1ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8ksyDUET0qM1aGGy1kmFA_180.JPG: 480x640 (no detections), 274.6ms
Speed: 1.1ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8ksyDUET0qM1aGGy1kmFA_270.JPG: 480x640 (no detections), 274.8ms
Speed: 1.0ms preprocess, 274.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8obtjx3tj3tuLbIAwWrqg_0.JPG: 480x640 (no detections), 276.5ms
Speed: 1.2ms preprocess, 276.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8obtjx3tj3tuLbIAwWrqg_90.JPG: 480x640 (no detections), 281.0ms
Speed: 1.0ms preprocess, 281.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8obtjx3tj3tuLbIAwWrqg_180.JPG: 480x640 (no detections), 274.2ms
Speed: 1.1ms preprocess, 274.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8obtjx3tj3tuLbIAwWrqg_270.JPG: 480x640 (no detections), 277.7ms
Speed: 1.0ms preprocess, 277.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8qM54dmrVFqyyu95XdzcA_0.JPG: 480x640 (no detections), 281.7ms
Speed: 1.2ms preprocess, 281.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8qM54dmrVFqyyu95XdzcA_90.JPG: 480x640 (no detections), 275.7ms
Speed: 1.1ms preprocess, 275.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8qM54dmrVFqyyu95XdzcA_180.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8qM54dmrVFqyyu95XdzcA_270.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8w3gq2vGmLkwo1mRuc2Kg_0.JPG: 480x640 (no detections), 273.9ms
Speed: 1.1ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8w3gq2vGmLkwo1mRuc2Kg_90.JPG: 480x640 (no detections), 276.5ms
Speed: 1.0ms preprocess, 276.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8w3gq2vGmLkwo1mRuc2Kg_180.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8w3gq2vGmLkwo1mRuc2Kg_270.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8xiqrBYShc3VQ7MgKVcEQ_0.JPG: 480x640 (no detections), 274.3ms
Speed: 1.0ms preprocess, 274.3ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8xiqrBYShc3VQ7MgKVcEQ_90.JPG: 480x640 (no detections), 274.8ms
Speed: 1.1ms preprocess, 274.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8xiqrBYShc3VQ7MgKVcEQ_180.JPG: 480x640 (no detections), 281.6ms
Speed: 1.1ms preprocess, 281.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8xiqrBYShc3VQ7MgKVcEQ_270.JPG: 480x640 (no detections), 281.3ms
Speed: 1.2ms preprocess, 281.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8yqTfjfGWGdQeiwRidipw_0.JPG: 480x640 (no detections), 276.8ms
Speed: 1.1ms preprocess, 276.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8yqTfjfGWGdQeiwRidipw_90.JPG: 480x640 (no detections), 278.5ms
Speed: 1.1ms preprocess, 278.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8yqTfjfGWGdQeiwRidipw_180.JPG: 480x640 (no detections), 277.9ms
Speed: 1.1ms preprocess, 277.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8yqTfjfGWGdQeiwRidipw_270.JPG: 480x640 (no detections), 278.5ms
Speed: 1.1ms preprocess, 278.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8zth8nHEljSHKklckf9Cw_0.JPG: 480x640 (no detections), 270.6ms
Speed: 1.0ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8zth8nHEljSHKklckf9Cw_90.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8zth8nHEljSHKklckf9Cw_180.JPG: 480x640 (no detections), 276.9ms
Speed: 1.6ms preprocess, 276.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/8/z8zth8nHEljSHKklckf9Cw_270.JPG: 480x640 (no detections), 270.9ms
Speed: 1.1ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9-DVYjhT24WGxucOwg0Ag_0.JPG: 480x640 (no detections), 276.7ms
Speed: 1.2ms preprocess, 276.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9-DVYjhT24WGxucOwg0Ag_90.JPG: 480x640 (no detections), 275.0ms
Speed: 1.1ms preprocess, 275.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9-DVYjhT24WGxucOwg0Ag_180.JPG: 480x640 (no detections), 277.1ms
Speed: 1.1ms preprocess, 277.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9-DVYjhT24WGxucOwg0Ag_270.JPG: 480x640 1 Waste, 276.5ms
Speed: 1.0ms preprocess, 276.5ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9-ZnFJfwCuo1fiC4L1Edw_0.JPG: 480x640 (no detections), 275.4ms
Speed: 1.0ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9-ZnFJfwCuo1fiC4L1Edw_90.JPG: 480x640 (no detections), 274.0ms
Speed: 1.1ms preprocess, 274.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9-ZnFJfwCuo1fiC4L1Edw_180.JPG: 480x640 (no detections), 280.3ms
Speed: 1.1ms preprocess, 280.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9-ZnFJfwCuo1fiC4L1Edw_270.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z90Fvw8QyfN5TcDlT9KOwQ_0.JPG: 480x640 (no detections), 275.2ms
Speed: 1.0ms preprocess, 275.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z90Fvw8QyfN5TcDlT9KOwQ_90.JPG: 480x640 (no detections), 285.8ms
Speed: 1.2ms preprocess, 285.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z90Fvw8QyfN5TcDlT9KOwQ_180.JPG: 480x640 (no detections), 281.6ms
Speed: 1.1ms preprocess, 281.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z90Fvw8QyfN5TcDlT9KOwQ_270.JPG: 480x640 (no detections), 271.8ms
Speed: 1.0ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z90XpPBhr78SDizGKVZ8xA_0.JPG: 480x640 (no detections), 276.7ms
Speed: 1.0ms preprocess, 276.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z90XpPBhr78SDizGKVZ8xA_90.JPG: 480x640 (no detections), 276.6ms
Speed: 1.1ms preprocess, 276.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z90XpPBhr78SDizGKVZ8xA_180.JPG: 480x640 (no detections), 272.2ms
Speed: 1.0ms preprocess, 272.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z90XpPBhr78SDizGKVZ8xA_270.JPG: 480x640 (no detections), 270.1ms
Speed: 1.0ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z91QdpkCPYEQjtmM62xQCw_0.JPG: 480x640 (no detections), 270.6ms
Speed: 1.0ms preprocess, 270.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z91QdpkCPYEQjtmM62xQCw_90.JPG: 480x640 (no detections), 281.3ms
Speed: 1.2ms preprocess, 281.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z91QdpkCPYEQjtmM62xQCw_180.JPG: 480x640 (no detections), 275.2ms
Speed: 1.1ms preprocess, 275.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z91QdpkCPYEQjtmM62xQCw_270.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z92M5K_5cXIa5PmLorLH4w_0.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z92M5K_5cXIa5PmLorLH4w_90.JPG: 480x640 (no detections), 278.2ms
Speed: 1.1ms preprocess, 278.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z92M5K_5cXIa5PmLorLH4w_180.JPG: 480x640 (no detections), 276.1ms
Speed: 1.1ms preprocess, 276.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z92M5K_5cXIa5PmLorLH4w_270.JPG: 480x640 (no detections), 283.7ms
Speed: 1.6ms preprocess, 283.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z92Wpu9pbkOr-CloVuZ3iA_0.JPG: 480x640 (no detections), 278.7ms

Speed: 1.2ms preprocess, 278.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z92Wpu9pbkOr-CloVuZ3iA_90.JPG: 480x640 (no detections), 283.5ms
Speed: 1.0ms preprocess, 283.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z92Wpu9pbkOr-CloVuZ3iA_180.JPG: 480x640 (no detections), 274.8ms
Speed: 1.1ms preprocess, 274.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z92Wpu9pbkOr-CloVuZ3iA_270.JPG: 480x640 (no detections), 271.5ms
Speed: 1.1ms preprocess, 271.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z92a0HkSP3cdI1habVPBwg_0.JPG: 480x640 (no detections), 274.5ms
Speed: 1.0ms preprocess, 274.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z92a0HkSP3cdI1habVPBwg_90.JPG: 480x640 (no detections), 279.4ms
Speed: 1.0ms preprocess, 279.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z92a0HkSP3cdI1habVPBwg_180.JPG: 480x640 (no detections), 278.1ms
Speed: 1.2ms preprocess, 278.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z92a0HkSP3cdI1habVPBwg_270.JPG: 480x640 (no detections), 275.0ms
Speed: 1.1ms preprocess, 275.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z94AKXyDiseMk6NIRJBpcw_0.JPG: 480x640 (no detections), 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z94AKXyDiseMk6NIRJBpcw_90.JPG: 480x640 (no detections), 272.5ms
Speed: 1.1ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z94AKXyDiseMk6NIRJBpcw_180.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z94AKXyDiseMk6NIRJBpcw_270.JPG: 480x640 3 Wastes, 274.9ms
Speed: 1.1ms preprocess, 274.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z96rikkrv4OWBAzfjoH3Zg_0.JPG: 480x640 (no detections), 276.9ms
Speed: 1.1ms preprocess, 276.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z96rikkrv4OWBAzfjoH3Zg_90.JPG: 480x640 (no detections), 275.0ms
Speed: 1.0ms preprocess, 275.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z96rikkrv4OWBAzfjoH3Zg_180.JPG: 480x640 (no detections), 277.9ms
Speed: 1.0ms preprocess, 277.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z96rikkrv4OWBAzfjoH3Zg_270.JPG: 480x640 (no detections), 275.8ms
Speed: 1.0ms preprocess, 275.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z96u8WHJDwJQ1c7aYj5vqA_0.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z96u8WHJDwJQ1c7aYj5vqA_90.JPG: 480x640 (no detections), 277.6ms
Speed: 1.1ms preprocess, 277.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z96u8WHJDwJQ1c7aYj5vqA_180.JPG: 480x640 (no detections), 273.9ms
Speed: 1.2ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z96u8WHJDwJQ1c7aYj5vqA_270.JPG: 480x640 (no detections), 273.3ms
Speed: 1.0ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z98id0crwk30Mu-3CWmF5A_0.JPG: 480x640 (no detections), 278.6ms
Speed: 1.1ms preprocess, 278.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z98id0crwk30Mu-3CWmF5A_90.JPG: 480x640 (no detections), 272.0ms
Speed: 1.2ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z98id0crwk30Mu-3CWmF5A_180.JPG: 480x640 (no detections), 272.0ms
Speed: 1.0ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z98id0crwk30Mu-3CWmF5A_270.JPG: 480x640 (no detections), 274.3ms
Speed: 1.2ms preprocess, 274.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9A4K7Bp0VcZoU9E7wQ_Ww_0.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9A4K7Bp0VcZoU9E7wQ_Ww_90.JPG: 480x640 (no detections), 274.8ms
Speed: 1.2ms preprocess, 274.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9A4K7Bp0VcZoU9E7wQ_Ww_180.JPG: 480x640 (no detections), 273.4ms
Speed: 1.1ms preprocess, 273.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9A4K7Bp0VcZoU9E7wQ_Ww_270.JPG: 480x640 (no detections), 273.1ms
Speed: 1.0ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9InMbZFwueDdsBFLdULxw_0.JPG: 480x640 (no detections), 275.8ms
Speed: 1.1ms preprocess, 275.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9InMbZFwueDdsBFLdULxw_90.JPG: 480x640 (no detections), 274.9ms
Speed: 1.1ms preprocess, 274.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9InMbZFwueDdsBFLdULxw_180.JPG: 480x640 (no detections), 274.0ms
Speed: 1.0ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9InMbZFwueDdsBFLdULxw_270.JPG: 480x640 (no detections), 277.5ms
Speed: 1.4ms preprocess, 277.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9MUR4YZ8zJG03h9lH1kJA_0.JPG: 480x640 (no detections), 278.0ms
Speed: 1.1ms preprocess, 278.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9MUR4YZ8zJG03h9lH1kJA_90.JPG: 480x640 (no detections), 281.0ms
Speed: 1.0ms preprocess, 281.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9MUR4YZ8zJG03h9lH1kJA_180.JPG: 480x640 (no detections), 276.9ms
Speed: 1.2ms preprocess, 276.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9MUR4YZ8zJG03h9lH1kJA_270.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9N3r6MwBty0hdw-41CJPA_0.JPG: 480x640 (no detections), 278.4ms
Speed: 1.1ms preprocess, 278.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9N3r6MwBty0hdw-41CJPA_90.JPG: 480x640 (no detections), 279.2ms
Speed: 1.0ms preprocess, 279.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9N3r6MwBty0hdw-41CJPA_180.JPG: 480x640 (no detections), 278.6ms
Speed: 1.1ms preprocess, 278.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9N3r6MwBty0hdw-41CJPA_270.JPG: 480x640 (no detections), 281.2ms
Speed: 1.2ms preprocess, 281.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9OXZK6BllaeOjUUYvAzrg_0.JPG: 480x640 (no detections), 281.1ms
Speed: 1.1ms preprocess, 281.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9OXZK6BllaeOjUUYvAzrg_90.JPG: 480x640 (no detections), 275.0ms
Speed: 1.1ms preprocess, 275.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9OXZK6BllaeOjUUYvAzrg_180.JPG: 480x640 (no detections), 273.2ms
Speed: 1.0ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9OXZK6BllaeOjUUYvAzrg_270.JPG: 480x640 (no detections), 275.5ms
Speed: 1.1ms preprocess, 275.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9RE2Emv7j2IQBC6EdPv0A_0.JPG: 480x640 (no detections), 280.3ms
Speed: 1.1ms preprocess, 280.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9RE2Emv7j2IQBC6EdPv0A_90.JPG: 480x640 (no detections), 274.9ms
Speed: 1.1ms preprocess, 274.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9RE2Emv7j2IQBC6EdPv0A_180.JPG: 480x640 (no detections), 272.4ms
Speed: 1.3ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9RE2Emv7j2IQBC6EdPv0A_270.JPG: 480x640 (no detections), 276.2ms
Speed: 1.1ms preprocess, 276.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9Sv9NMCKSp9cxOxDD1dKQ_0.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9Sv9NMCKSp9cxOxDD1dKQ_90.JPG: 480x640 (no detections), 274.1ms
Speed: 1.0ms preprocess, 274.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9Sv9NMCKSp9cxOxDD1dKQ_180.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9Sv9NMCKSp9cxOxDD1dKQ_270.JPG: 480x640 (no detections), 270.3ms
Speed: 1.1ms preprocess, 270.3ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9WBfw3HNpNsQBsY55oLBg_0.JPG: 480x640 (no detections), 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9WBfw3HNpNsQBsY55oLBg_90.JPG: 480x640 (no detections), 278.1ms
Speed: 1.1ms preprocess, 278.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9WBfw3HNpNsQBsY55oLBg_180.JPG: 480x640 (no detections), 275.6ms
Speed: 1.0ms preprocess, 275.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9WBfw3HNpNsQBsY55oLBg_270.JPG: 480x640 (no detections), 274.2ms
Speed: 1.4ms preprocess, 274.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9XVJ4H1X5z0TXe3Y-Jd8A_0.JPG: 480x640 (no detections), 289.9ms
Speed: 1.3ms preprocess, 289.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9XVJ4H1X5z0TXe3Y-Jd8A_90.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9XVJ4H1X5z0TXe3Y-Jd8A_180.JPG: 480x640 (no detections), 273.2ms
Speed: 1.2ms preprocess, 273.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9XVJ4H1X5z0TXe3Y-Jd8A_270.JPG: 480x640 (no detections), 274.1ms
Speed: 1.2ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9XkYvwQ_2yeAgVAzFtjpA_0.JPG: 480x640 (no detections), 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9XkYvwQ_2yeAgVAzFtjpA_90.JPG: 480x640 (no detections), 277.5ms
Speed: 1.1ms preprocess, 277.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9XkYvwQ_2yeAgVAzFtjpA_180.JPG: 480x640 (no detections), 279.6ms
Speed: 1.1ms preprocess, 279.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9XkYvwQ_2yeAgVAzFtjpA_270.JPG: 480x640 (no detections), 272.0ms
Speed: 1.0ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9XxbAIDlNRrt1LO_GwQ9Q_0.JPG: 480x640 3 Wastes, 274.4ms
Speed: 1.2ms preprocess, 274.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9XxbAIDlNRrt1LO_GwQ9Q_90.JPG: 480x640 (no detections), 276.6ms
Speed: 1.1ms preprocess, 276.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9XxbAIDlNRrt1LO_GwQ9Q_180.JPG: 480x640 (no detections), 277.4ms
Speed: 1.6ms preprocess, 277.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9XxbAIDlNRrt1LO_GwQ9Q_270.JPG: 480x640 (no detections), 275.1ms

Speed: 1.0ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9YSOCpvFcX3MBZdtANEUg_0.JPG: 480x640 1 Waste, 277.3ms
Speed: 1.0ms preprocess, 277.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9YSOCpvFcX3MBZdtANEUg_90.JPG: 480x640 1 Waste, 274.4ms
Speed: 1.1ms preprocess, 274.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9YSOCpvFcX3MBZdtANEUg_180.JPG: 480x640 (no detections), 278.3ms
Speed: 1.0ms preprocess, 278.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9YSOCpvFcX3MBZdtANEUg_270.JPG: 480x640 (no detections), 279.8ms
Speed: 1.5ms preprocess, 279.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9ZF1ilm7dn2rUdZ6Hu22Q_0.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9ZF1ilm7dn2rUdZ6Hu22Q_90.JPG: 480x640 (no detections), 272.6ms
Speed: 1.0ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9ZF1ilm7dn2rUdZ6Hu22Q_180.JPG: 480x640 (no detections), 276.2ms
Speed: 1.1ms preprocess, 276.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9ZF1ilm7dn2rUdZ6Hu22Q_270.JPG: 480x640 (no detections), 277.0ms
Speed: 1.0ms preprocess, 277.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9aVjXpJoZPq7ob05mQFtg_0.JPG: 480x640 (no detections), 276.1ms
Speed: 1.1ms preprocess, 276.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9aVjXpJoZPq7ob05mQFtg_90.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9aVjXpJoZPq7ob05mQFtg_180.JPG: 480x640 (no detections), 276.2ms
Speed: 1.0ms preprocess, 276.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9aVjXpJoZPq7ob05mQFtg_270.JPG: 480x640 (no detections), 273.2ms
Speed: 1.2ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9aWl9v_gPnNbUsKKP3dig_0.JPG: 480x640 (no detections), 274.6ms
Speed: 1.0ms preprocess, 274.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9aWl9v_gPnNbUsKKP3dig_90.JPG: 480x640 (no detections), 275.3ms
Speed: 1.1ms preprocess, 275.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9aWl9v_gPnNbUsKKP3dig_180.JPG: 480x640 (no detections), 274.3ms
Speed: 1.2ms preprocess, 274.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9aWl9v_gPnNbUsKKP3dig_270.JPG: 480x640 (no detections), 276.4ms
Speed: 1.2ms preprocess, 276.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9cBWyirwobLhjTh449Rfg_0.JPG: 480x640 (no detections), 277.9ms
Speed: 1.5ms preprocess, 277.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9cBWyirwobLhjTh449Rfg_90.JPG: 480x640 (no detections), 276.1ms
Speed: 1.2ms preprocess, 276.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9cBWyirwobLhjTh449Rfg_180.JPG: 480x640 (no detections), 274.8ms
Speed: 1.0ms preprocess, 274.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9cBWyirwobLhjTh449Rfg_270.JPG: 480x640 (no detections), 272.4ms
Speed: 1.2ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9h4E_IgEjA2dCVlxm0KWQ_0.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9h4E_IgEjA2dCVlxm0KWQ_90.JPG: 480x640 (no detections), 280.5ms
Speed: 1.2ms preprocess, 280.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9h4E_IgEjA2dCVlxm0KWQ_180.JPG: 480x640 (no detections), 275.5ms
Speed: 1.2ms preprocess, 275.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9h4E_IgEjA2dCVlxm0KWQ_270.JPG: 480x640 (no detections), 272.7ms
Speed: 1.0ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9lB-UrIAeZyJPYg3HaqRg_0.JPG: 480x640 (no detections), 306.1ms
Speed: 1.0ms preprocess, 306.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9lB-UrIAeZyJPYg3HaqRg_90.JPG: 480x640 (no detections), 275.4ms
Speed: 1.2ms preprocess, 275.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9lB-UrIAeZyJPYg3HaqRg_180.JPG: 480x640 (no detections), 271.4ms
Speed: 1.0ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9lB-UrIAeZyJPYg3HaqRg_270.JPG: 480x640 (no detections), 276.6ms
Speed: 1.1ms preprocess, 276.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9oawhkV1StCdx2JjBM4kw_0.JPG: 480x640 (no detections), 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9oawhkV1StCdx2JjBM4kw_90.JPG: 480x640 (no detections), 274.3ms
Speed: 1.0ms preprocess, 274.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9oawhkV1StCdx2JjBM4kw_180.JPG: 480x640 (no detections), 271.1ms
Speed: 1.2ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9oawhkV1StCdx2JjBM4kw_270.JPG: 480x640 (no detections), 277.8ms
Speed: 1.1ms preprocess, 277.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9rTttQHjBBBi0kWPijWzQ_0.JPG: 480x640 (no detections), 278.6ms
Speed: 1.0ms preprocess, 278.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9rTttQHjBBBi0kWPijWzQ_90.JPG: 480x640 (no detections), 278.2ms
Speed: 1.1ms preprocess, 278.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9rTttQHjBBBi0kWPijWzQ_180.JPG: 480x640 (no detections), 272.8ms
Speed: 1.0ms preprocess, 272.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9rTttQHjBBBi0kWPijWzQ_270.JPG: 480x640 (no detections), 280.7ms
Speed: 1.0ms preprocess, 280.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9vVhWsM0fI9MUrODhrrbQ_0.JPG: 480x640 (no detections), 277.2ms
Speed: 1.2ms preprocess, 277.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9vVhWsM0fI9MUrODhrrbQ_90.JPG: 480x640 (no detections), 273.9ms
Speed: 1.1ms preprocess, 273.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9vVhWsM0fI9MUrODhrrbQ_180.JPG: 480x640 (no detections), 275.5ms
Speed: 1.1ms preprocess, 275.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9vVhWsM0fI9MUrODhrrbQ_270.JPG: 480x640 (no detections), 274.4ms
Speed: 1.0ms preprocess, 274.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9yaH609x1XThwQU5y1LkQ_0.JPG: 480x640 (no detections), 270.7ms
Speed: 1.0ms preprocess, 270.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9yaH609x1XThwQU5y1LkQ_90.JPG: 480x640 (no detections), 272.4ms
Speed: 1.1ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9yaH609x1XThwQU5y1LkQ_180.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/9/z9yaH609x1XThwQU5y1LkQ_270.JPG: 480x640 1 Waste, 279.5ms
Speed: 1.2ms preprocess, 279.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zA1HbfWcomQuWR5DuiGrsg_0.JPG: 480x640 (no detections), 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zA1HbfWcomQuWR5DuiGrsg_90.JPG: 480x640 (no detections), 276.9ms
Speed: 1.0ms preprocess, 276.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zA1HbfWcomQuWR5DuiGrsg_180.JPG: 480x640 (no detections), 275.2ms
Speed: 1.0ms preprocess, 275.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zA1HbfWcomQuWR5DuiGrsg_270.JPG: 480x640 (no detections), 277.9ms
Speed: 1.0ms preprocess, 277.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zA1Igda2zdc6CDOq6xWe_g_0.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zA1Igda2zdc6CDOq6xWe_g_90.JPG: 480x640 (no detections), 274.9ms
Speed: 1.0ms preprocess, 274.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zA1Igda2zdc6CDOq6xWe_g_180.JPG: 480x640 (no detections), 277.6ms
Speed: 1.1ms preprocess, 277.6ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zA1Igda2zdc6CDOq6xWe_g_270.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zA1d79f25s8I84wiMml0jA_0.JPG: 480x640 (no detections), 277.3ms
Speed: 1.1ms preprocess, 277.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zA1d79f25s8I84wiMml0jA_90.JPG: 480x640 (no detections), 277.5ms
Speed: 1.0ms preprocess, 277.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zA1d79f25s8I84wiMml0jA_180.JPG: 480x640 (no detections), 274.2ms
Speed: 1.1ms preprocess, 274.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zA1d79f25s8I84wiMml0jA_270.JPG: 480x640 (no detections), 278.8ms
Speed: 1.0ms preprocess, 278.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zA1eVjL0mT_EnsPZdvuPVw_0.JPG: 480x640 (no detections), 273.0ms
Speed: 1.0ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zA1eVjL0mT_EnsPZdvuPVw_90.JPG: 480x640 (no detections), 273.2ms
Speed: 1.1ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zA1eVjL0mT_EnsPZdvuPVw_180.JPG: 480x640 (no detections), 274.5ms
Speed: 1.1ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zA1eVjL0mT_EnsPZdvuPVw_270.JPG: 480x640 (no detections), 274.3ms
Speed: 1.0ms preprocess, 274.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zA3iALGU7MUrLw66jYsebg_0.JPG: 480x640 (no detections), 276.2ms
Speed: 1.1ms preprocess, 276.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zA3iALGU7MUrLw66jYsebg_90.JPG: 480x640 (no detections), 271.8ms
Speed: 1.0ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zA3iALGU7MUrLw66jYsebg_180.JPG: 480x640 (no detections), 277.8ms
Speed: 1.0ms preprocess, 277.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zA3iALGU7MUrLw66jYsebg_270.JPG: 480x640 (no detections), 274.8ms
Speed: 1.0ms preprocess, 274.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zA4X-VoRSkn5Uh5vXF8WXg_0.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zA4X-VoRSkn5Uh5vXF8WXg_90.JPG: 480x640 (no detections), 269.6ms
Speed: 1.0ms preprocess, 269.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zA4X-VoRSkn5Uh5vXF8WXg_180.JPG: 480x640 (no detections), 274.0ms

Speed: 1.0ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zA4X-VoRSkn5Uh5vXF8WXg_270.JPG: 480x640 (no detections), 276.4ms
Speed: 1.2ms preprocess, 276.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zA4YOWAVcfdClR1WTGK92w_0.JPG: 480x640 1 Waste, 278.0ms
Speed: 1.1ms preprocess, 278.0ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zA4YOWAVcfdClR1WTGK92w_90.JPG: 480x640 (no detections), 274.8ms
Speed: 1.1ms preprocess, 274.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zA4YOWAVcfdClR1WTGK92w_180.JPG: 480x640 (no detections), 274.8ms
Speed: 1.1ms preprocess, 274.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zA4YOWAVcfdClR1WTGK92w_270.JPG: 480x640 (no detections), 279.4ms
Speed: 1.1ms preprocess, 279.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zA534SufRNZFLbS6ehAsoQ_0.JPG: 480x640 (no detections), 272.5ms
Speed: 1.4ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zA534SufRNZFLbS6ehAsoQ_90.JPG: 480x640 (no detections), 275.8ms
Speed: 1.2ms preprocess, 275.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zA534SufRNZFLbS6ehAsoQ_180.JPG: 480x640 (no detections), 271.5ms
Speed: 1.1ms preprocess, 271.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zA534SufRNZFLbS6ehAsoQ_270.JPG: 480x640 (no detections), 273.6ms
Speed: 1.2ms preprocess, 273.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zA7BJUnq52Re6uA9x06hGQ_0.JPG: 480x640 (no detections), 282.6ms
Speed: 1.1ms preprocess, 282.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zA7BJUnq52Re6uA9x06hGQ_90.JPG: 480x640 (no detections), 273.0ms
Speed: 1.2ms preprocess, 273.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zA7BJUnq52Re6uA9x06hGQ_180.JPG: 480x640 (no detections), 274.0ms
Speed: 1.1ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zA7BJUnq52Re6uA9x06hGQ_270.JPG: 480x640 (no detections), 274.7ms
Speed: 1.0ms preprocess, 274.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zA8sH1PHY0bsmjXkKJka7A_0.JPG: 480x640 (no detections), 278.1ms
Speed: 1.1ms preprocess, 278.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zA8sH1PHY0bsmjXkKJka7A_90.JPG: 480x640 (no detections), 275.3ms
Speed: 1.1ms preprocess, 275.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zA8sH1PHY0bsmjXkKJka7A_180.JPG: 480x640 (no detections), 273.9ms
Speed: 1.2ms preprocess, 273.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zA8sH1PHY0bsmjXkKJka7A_270.JPG: 480x640 (no detections), 273.9ms
Speed: 1.0ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAHr2_5DHlgn5hUwA5IJZA_0.JPG: 480x640 (no detections), 276.7ms
Speed: 1.1ms preprocess, 276.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAHr2_5DHlgn5hUwA5IJZA_90.JPG: 480x640 (no detections), 274.8ms
Speed: 1.1ms preprocess, 274.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAHr2_5DHlgn5hUwA5IJZA_180.JPG: 480x640 (no detections), 286.0ms
Speed: 1.1ms preprocess, 286.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAHr2_5DHlgn5hUwA5IJZA_270.JPG: 480x640 (no detections), 277.1ms
Speed: 1.1ms preprocess, 277.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zANDzFC6KaaLKv0ekmY-Xw_0.JPG: 480x640 (no detections), 273.9ms
Speed: 1.1ms preprocess, 273.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zANDzFC6KaaLKv0ekmY-Xw_90.JPG: 480x640 (no detections), 277.6ms
Speed: 1.1ms preprocess, 277.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zANDzFC6KaaLKv0ekmY-Xw_180.JPG: 480x640 (no detections), 278.1ms
Speed: 1.1ms preprocess, 278.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zANDzFC6KaaLKv0ekmY-Xw_270.JPG: 480x640 1 Waste, 269.3ms
Speed: 1.1ms preprocess, 269.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zANnW8u6sHm4p74Y-EAm4g_0.JPG: 480x640 (no detections), 276.3ms
Speed: 1.1ms preprocess, 276.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zANnW8u6sHm4p74Y-EAm4g_90.JPG: 480x640 (no detections), 278.4ms
Speed: 1.0ms preprocess, 278.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zANnW8u6sHm4p74Y-EAm4g_180.JPG: 480x640 (no detections), 275.4ms
Speed: 1.1ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zANnW8u6sHm4p74Y-EAm4g_270.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAQD0rCFQcqTr_Rh5DNhCw_0.JPG: 480x640 (no detections), 272.0ms
Speed: 1.1ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAQD0rCFQcqTr_Rh5DNhCw_90.JPG: 480x640 (no detections), 278.3ms
Speed: 1.2ms preprocess, 278.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAQD0rCFQcqTr_Rh5DNhCw_180.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAQD0rCFQcqTr_Rh5DNhCw_270.JPG: 480x640 (no detections), 282.5ms
Speed: 1.2ms preprocess, 282.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAT0u8KTBWvwEVslZtFKzw_0.JPG: 480x640 (no detections), 274.5ms
Speed: 1.2ms preprocess, 274.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAT0u8KTBWvwEVslZtFKzw_90.JPG: 480x640 (no detections), 273.3ms
Speed: 1.0ms preprocess, 273.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAT0u8KTBWvwEVslZtFKzw_180.JPG: 480x640 (no detections), 274.6ms
Speed: 1.0ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAT0u8KTBWvwEVslZtFKzw_270.JPG: 480x640 (no detections), 272.5ms
Speed: 1.0ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAVfb_uuQL_a4u55rdOItA_0.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAVfb_uuQL_a4u55rdOItA_90.JPG: 480x640 1 Waste, 272.5ms
Speed: 1.0ms preprocess, 272.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAVfb_uuQL_a4u55rdOItA_180.JPG: 480x640 (no detections), 274.7ms
Speed: 1.1ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAVfb_uuQL_a4u55rdOItA_270.JPG: 480x640 (no detections), 284.1ms
Speed: 1.1ms preprocess, 284.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAW3leY9q5x6MPjx0SUCUA_0.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAW3leY9q5x6MPjx0SUCUA_90.JPG: 480x640 (no detections), 276.0ms
Speed: 1.1ms preprocess, 276.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAW3leY9q5x6MPjx0SUCUA_180.JPG: 480x640 (no detections), 273.7ms
Speed: 1.2ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAW3leY9q5x6MPjx0SUCUA_270.JPG: 480x640 (no detections), 279.0ms
Speed: 1.2ms preprocess, 279.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAYjYDYn3c6W0kmdOciEIg_0.JPG: 480x640 (no detections), 272.1ms
Speed: 1.0ms preprocess, 272.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAYjYDYn3c6W0kmdOciEIg_90.JPG: 480x640 (no detections), 279.4ms
Speed: 1.1ms preprocess, 279.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAYjYDYn3c6W0kmdOciEIg_180.JPG: 480x640 (no detections), 276.3ms
Speed: 1.2ms preprocess, 276.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAYjYDYn3c6W0kmdOciEIg_270.JPG: 480x640 (no detections), 279.7ms
Speed: 1.1ms preprocess, 279.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAa_45t2X9EvSG7TW81SzA_0.JPG: 480x640 (no detections), 272.4ms
Speed: 1.0ms preprocess, 272.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAa_45t2X9EvSG7TW81SzA_90.JPG: 480x640 (no detections), 270.4ms
Speed: 1.1ms preprocess, 270.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAa_45t2X9EvSG7TW81SzA_180.JPG: 480x640 (no detections), 273.5ms
Speed: 1.0ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAa_45t2X9EvSG7TW81SzA_270.JPG: 480x640 (no detections), 274.7ms
Speed: 1.0ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAcw2z57hHxntwHzvZyeiA_0.JPG: 480x640 (no detections), 271.6ms
Speed: 1.0ms preprocess, 271.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAcw2z57hHxntwHzvZyeiA_90.JPG: 480x640 (no detections), 277.7ms
Speed: 1.1ms preprocess, 277.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAcw2z57hHxntwHzvZyeiA_180.JPG: 480x640 (no detections), 276.7ms
Speed: 1.2ms preprocess, 276.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAcw2z57hHxntwHzvZyeiA_270.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAhY0D_bEoIUwwAZZicf5w_0.JPG: 480x640 (no detections), 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAhY0D_bEoIUwwAZZicf5w_90.JPG: 480x640 (no detections), 277.5ms
Speed: 1.2ms preprocess, 277.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAhY0D_bEoIUwwAZZicf5w_180.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAhY0D_bEoIUwwAZZicf5w_270.JPG: 480x640 (no detections), 279.2ms
Speed: 1.0ms preprocess, 279.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAiCMmcGFAebGZFnNhsc3w_0.JPG: 480x640 (no detections), 273.9ms
Speed: 1.1ms preprocess, 273.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAiCMmcGFAebGZFnNhsc3w_90.JPG: 480x640 (no detections), 277.5ms
Speed: 1.0ms preprocess, 277.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAiCMmcGFAebGZFnNhsc3w_180.JPG: 480x640 (no detections), 274.4ms
Speed: 1.0ms preprocess, 274.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAiCMmcGFAebGZFnNhsc3w_270.JPG: 480x640 (no detections), 271.1ms
Speed: 1.0ms preprocess, 271.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAiKXeVGR2GlaljEM2CNOg_0.JPG: 480x640 (no detections), 277.1ms
Speed: 1.0ms preprocess, 277.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAiKXeVGR2GlaljEM2CNOg_90.JPG: 480x640 (no detections), 276.8ms

Speed: 1.2ms preprocess, 276.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAiKXeVGR2GlaljEM2CNOg_180.JPG: 480x640 1 Waste, 274.4ms
Speed: 1.1ms preprocess, 274.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAiKXeVGR2GlaljEM2CNOg_270.JPG: 480x640 (no detections), 278.3ms
Speed: 1.2ms preprocess, 278.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAidTwmPqq7mvl2-fkbQDA_0.JPG: 480x640 (no detections), 275.1ms
Speed: 1.0ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAidTwmPqq7mvl2-fkbQDA_90.JPG: 480x640 (no detections), 275.4ms
Speed: 1.1ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAidTwmPqq7mvl2-fkbQDA_180.JPG: 480x640 (no detections), 278.9ms
Speed: 1.0ms preprocess, 278.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAidTwmPqq7mvl2-fkbQDA_270.JPG: 480x640 (no detections), 279.3ms
Speed: 1.1ms preprocess, 279.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAk3N76PZuB7mCYoc8c2Vw_0.JPG: 480x640 (no detections), 275.3ms
Speed: 1.1ms preprocess, 275.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAk3N76PZuB7mCYoc8c2Vw_90.JPG: 480x640 (no detections), 278.6ms
Speed: 1.0ms preprocess, 278.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAk3N76PZuB7mCYoc8c2Vw_180.JPG: 480x640 (no detections), 276.6ms
Speed: 1.0ms preprocess, 276.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAk3N76PZuB7mCYoc8c2Vw_270.JPG: 480x640 (no detections), 275.0ms
Speed: 1.2ms preprocess, 275.0ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAkKTOBy9mf95zI8M6j8cw_0.JPG: 480x640 (no detections), 278.6ms
Speed: 1.2ms preprocess, 278.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAkKTOBy9mf95zI8M6j8cw_90.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAkKTOBy9mf95zI8M6j8cw_180.JPG: 480x640 (no detections), 274.9ms
Speed: 1.2ms preprocess, 274.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAkKTOBy9mf95zI8M6j8cw_270.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAmqgSRtzvJQb2r2KCjTLw_0.JPG: 480x640 (no detections), 276.5ms
Speed: 1.1ms preprocess, 276.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAmqgSRtzvJQb2r2KCjTLw_90.JPG: 480x640 (no detections), 280.8ms
Speed: 1.1ms preprocess, 280.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAmqgSRtzvJQb2r2KCjTLw_180.JPG: 480x640 (no detections), 278.2ms
Speed: 1.1ms preprocess, 278.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAmqgSRtzvJQb2r2KCjTLw_270.JPG: 480x640 (no detections), 273.9ms
Speed: 1.1ms preprocess, 273.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAo7tk25LHmZmouL9dyngg_0.JPG: 480x640 (no detections), 272.5ms
Speed: 1.1ms preprocess, 272.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAo7tk25LHmZmouL9dyngg_90.JPG: 480x640 (no detections), 277.2ms
Speed: 1.2ms preprocess, 277.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAo7tk25LHmZmouL9dyngg_180.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAo7tk25LHmZmouL9dyngg_270.JPG: 480x640 (no detections), 275.2ms
Speed: 1.1ms preprocess, 275.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAomwB9fjW2IfmubpoqPPA_0.JPG: 480x640 (no detections), 273.6ms
Speed: 1.1ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAomwB9fjW2IfmubpoqPPA_90.JPG: 480x640 (no detections), 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAomwB9fjW2IfmubpoqPPA_180.JPG: 480x640 (no detections), 273.2ms
Speed: 1.0ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAomwB9fjW2IfmubpoqPPA_270.JPG: 480x640 (no detections), 274.4ms
Speed: 1.0ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAp3lPa6hUZnB35J609vfQ_0.JPG: 480x640 (no detections), 278.2ms
Speed: 1.1ms preprocess, 278.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAp3lPa6hUZnB35J609vfQ_90.JPG: 480x640 (no detections), 276.7ms
Speed: 1.0ms preprocess, 276.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAp3lPa6hUZnB35J609vfQ_180.JPG: 480x640 (no detections), 277.7ms
Speed: 1.1ms preprocess, 277.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAp3lPa6hUZnB35J609vfQ_270.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAqtbbNmwkk3bWHDeYxGNg_0.JPG: 480x640 (no detections), 274.5ms
Speed: 1.1ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAqtbbNmwkk3bWHDeYxGNg_90.JPG: 480x640 (no detections), 275.3ms
Speed: 1.0ms preprocess, 275.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAqtbbNmwkk3bWHDeYxGNg_180.JPG: 480x640 (no detections), 278.1ms
Speed: 1.1ms preprocess, 278.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAqtbbNmwkk3bWHDeYxGNg_270.JPG: 480x640 (no detections), 273.7ms
Speed: 1.2ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAzXNm53cQ9T47Bo0mkb5Q_0.JPG: 480x640 (no detections), 274.0ms
Speed: 1.1ms preprocess, 274.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAzXNm53cQ9T47Bo0mkb5Q_90.JPG: 480x640 (no detections), 273.1ms
Speed: 1.1ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAzXNm53cQ9T47Bo0mkb5Q_180.JPG: 480x640 (no detections), 281.7ms
Speed: 1.2ms preprocess, 281.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zAzXNm53cQ9T47Bo0mkb5Q_270.JPG: 480x640 (no detections), 276.6ms
Speed: 1.1ms preprocess, 276.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zB0SyLj3C44X-7_peWzWsw_0.JPG: 480x640 (no detections), 276.7ms
Speed: 1.0ms preprocess, 276.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zB0SyLj3C44X-7_peWzWsw_90.JPG: 480x640 1 Waste, 273.8ms
Speed: 1.0ms preprocess, 273.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zB0SyLj3C44X-7_peWzWsw_180.JPG: 480x640 (no detections), 272.5ms
Speed: 1.1ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zB0SyLj3C44X-7_peWzWsw_270.JPG: 480x640 (no detections), 271.7ms
Speed: 1.0ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zB37v5vY7wrjvCU50nuOag_0.JPG: 480x640 (no detections), 274.9ms
Speed: 1.0ms preprocess, 274.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zB37v5vY7wrjvCU50nuOag_90.JPG: 480x640 (no detections), 274.4ms
Speed: 1.1ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zB37v5vY7wrjvCU50nuOag_180.JPG: 480x640 (no detections), 274.3ms
Speed: 1.0ms preprocess, 274.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zB37v5vY7wrjvCU50nuOag_270.JPG: 480x640 (no detections), 277.9ms
Speed: 1.3ms preprocess, 277.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zB3cbbGIJ32AtOFrybvrvw_0.JPG: 480x640 (no detections), 276.3ms
Speed: 1.1ms preprocess, 276.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zB3cbbGIJ32AtOFrybvrvw_90.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zB3cbbGIJ32AtOFrybvrvw_180.JPG: 480x640 (no detections), 278.3ms
Speed: 1.1ms preprocess, 278.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zB3cbbGIJ32AtOFrybvrvw_270.JPG: 480x640 (no detections), 274.8ms
Speed: 1.1ms preprocess, 274.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBBAGOZRw73fqnEwihIwRw_0.JPG: 480x640 (no detections), 277.5ms
Speed: 1.1ms preprocess, 277.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBBAGOZRw73fqnEwihIwRw_90.JPG: 480x640 (no detections), 276.2ms
Speed: 1.1ms preprocess, 276.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBBAGOZRw73fqnEwihIwRw_180.JPG: 480x640 (no detections), 279.3ms
Speed: 1.2ms preprocess, 279.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBBAGOZRw73fqnEwihIwRw_270.JPG: 480x640 (no detections), 268.4ms
Speed: 1.0ms preprocess, 268.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBBQT7erS9Un1nG4GPcsZw_0.JPG: 480x640 (no detections), 270.8ms
Speed: 1.0ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBBQT7erS9Un1nG4GPcsZw_90.JPG: 480x640 (no detections), 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBBQT7erS9Un1nG4GPcsZw_180.JPG: 480x640 (no detections), 273.1ms
Speed: 1.1ms preprocess, 273.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBBQT7erS9Un1nG4GPcsZw_270.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBEAfL0-vl5g6a5Lqb82dw_0.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBEAfL0-vl5g6a5Lqb82dw_90.JPG: 480x640 (no detections), 272.4ms
Speed: 1.0ms preprocess, 272.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBEAfL0-vl5g6a5Lqb82dw_180.JPG: 480x640 (no detections), 283.9ms
Speed: 1.2ms preprocess, 283.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBEAfL0-vl5g6a5Lqb82dw_270.JPG: 480x640 (no detections), 272.1ms
Speed: 1.0ms preprocess, 272.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBGb1_LI3dovBQLEuMtfpw_0.JPG: 480x640 (no detections), 273.5ms
Speed: 1.0ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBGb1_LI3dovBQLEuMtfpw_90.JPG: 480x640 (no detections), 274.2ms
Speed: 1.0ms preprocess, 274.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBGb1_LI3dovBQLEuMtfpw_180.JPG: 480x640 (no detections), 271.9ms
Speed: 1.0ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBGb1_LI3dovBQLEuMtfpw_270.JPG: 480x640 (no detections), 275.2ms
Speed: 1.1ms preprocess, 275.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBOFsPwMG-VbCtofn9asIQ_0.JPG: 480x640 (no detections), 276.8ms

Speed: 1.1ms preprocess, 276.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBOFsPwMG-VbCtofn9asIQ_90.JPG: 480x640 (no detections), 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBOFsPwMG-VbCtofn9asIQ_180.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBOFsPwMG-VbCtofn9asIQ_270.JPG: 480x640 (no detections), 273.2ms
Speed: 1.0ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBOlXCSIvuRLTBumfbysjA_0.JPG: 480x640 (no detections), 273.0ms
Speed: 1.0ms preprocess, 273.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBOlXCSIvuRLTBumfbysjA_90.JPG: 480x640 (no detections), 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBOlXCSIvuRLTBumfbysjA_180.JPG: 480x640 (no detections), 272.8ms
Speed: 1.0ms preprocess, 272.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBOlXCSIvuRLTBumfbysjA_270.JPG: 480x640 (no detections), 275.1ms
Speed: 1.2ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBR8_1ZBdGzBhV1W_CbB2Q_0.JPG: 480x640 (no detections), 272.0ms
Speed: 1.2ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBR8_1ZBdGzBhV1W_CbB2Q_90.JPG: 480x640 (no detections), 283.5ms
Speed: 1.1ms preprocess, 283.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBR8_1ZBdGzBhV1W_CbB2Q_180.JPG: 480x640 (no detections), 276.6ms
Speed: 1.0ms preprocess, 276.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBR8_1ZBdGzBhV1W_CbB2Q_270.JPG: 480x640 (no detections), 279.8ms
Speed: 1.2ms preprocess, 279.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBRzOwNaqQWtEV_9mwDhsA_0.JPG: 480x640 (no detections), 271.4ms
Speed: 1.0ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBRzOwNaqQWtEV_9mwDhsA_90.JPG: 480x640 (no detections), 269.6ms
Speed: 1.0ms preprocess, 269.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBRzOwNaqQWtEV_9mwDhsA_180.JPG: 480x640 (no detections), 273.2ms
Speed: 1.0ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBRzOwNaqQWtEV_9mwDhsA_270.JPG: 480x640 (no detections), 281.9ms
Speed: 1.1ms preprocess, 281.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBWow2TKdk7Ee-BQy6a-uQ_0.JPG: 480x640 (no detections), 276.9ms
Speed: 1.1ms preprocess, 276.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBWow2TKdk7Ee-BQy6a-uQ_90.JPG: 480x640 (no detections), 354.6ms
Speed: 1.0ms preprocess, 354.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBWow2TKdk7Ee-BQy6a-uQ_180.JPG: 480x640 (no detections), 386.3ms
Speed: 1.6ms preprocess, 386.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBWow2TKdk7Ee-BQy6a-uQ_270.JPG: 480x640 (no detections), 325.0ms
Speed: 1.2ms preprocess, 325.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBX_VSyHTENh64mMq9Ucvw_0.JPG: 480x640 (no detections), 340.0ms
Speed: 2.1ms preprocess, 340.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBX_VSyHTENh64mMq9Ucvw_90.JPG: 480x640 (no detections), 354.6ms
Speed: 1.1ms preprocess, 354.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBX_VSyHTENh64mMq9Ucvw_180.JPG: 480x640 1 Waste, 428.6ms
Speed: 1.2ms preprocess, 428.6ms inference, 1.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBX_VSyHTENh64mMq9Ucvw_270.JPG: 480x640 (no detections), 423.3ms
Speed: 1.3ms preprocess, 423.3ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBXpBRsBCnuucDJ9QPV_zQ_0.JPG: 480x640 (no detections), 299.3ms
Speed: 1.1ms preprocess, 299.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBXpBRsBCnuucDJ9QPV_zQ_90.JPG: 480x640 (no detections), 289.6ms
Speed: 1.1ms preprocess, 289.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBXpBRsBCnuucDJ9QPV_zQ_180.JPG: 480x640 (no detections), 312.1ms
Speed: 1.9ms preprocess, 312.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBXpBRsBCnuucDJ9QPV_zQ_270.JPG: 480x640 (no detections), 307.4ms
Speed: 1.2ms preprocess, 307.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBaf4ojrF80O-7U0Zm6z7g_0.JPG: 480x640 (no detections), 389.3ms
Speed: 1.1ms preprocess, 389.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBaf4ojrF80O-7U0Zm6z7g_90.JPG: 480x640 (no detections), 299.1ms
Speed: 1.2ms preprocess, 299.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBaf4ojrF80O-7U0Zm6z7g_180.JPG: 480x640 (no detections), 296.4ms
Speed: 1.4ms preprocess, 296.4ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBaf4ojrF80O-7U0Zm6z7g_270.JPG: 480x640 (no detections), 479.2ms
Speed: 1.2ms preprocess, 479.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBbTSwNsguHhq9AmVxCYHg_0.JPG: 480x640 (no detections), 280.0ms
Speed: 1.5ms preprocess, 280.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBbTSwNsguHhq9AmVxCYHg_90.JPG: 480x640 (no detections), 275.9ms
Speed: 1.2ms preprocess, 275.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBbTSwNsguHhq9AmVxCYHg_180.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBbTSwNsguHhq9AmVxCYHg_270.JPG: 480x640 (no detections), 318.7ms
Speed: 1.5ms preprocess, 318.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBcpYA6bGx6DroNYhzJ4ww_0.JPG: 480x640 (no detections), 401.6ms
Speed: 2.0ms preprocess, 401.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBcpYA6bGx6DroNYhzJ4ww_90.JPG: 480x640 (no detections), 325.1ms
Speed: 2.1ms preprocess, 325.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBcpYA6bGx6DroNYhzJ4ww_180.JPG: 480x640 (no detections), 337.7ms
Speed: 1.6ms preprocess, 337.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBcpYA6bGx6DroNYhzJ4ww_270.JPG: 480x640 (no detections), 313.2ms
Speed: 1.6ms preprocess, 313.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBecUDsxmcrVVi7eCmxxMw_0.JPG: 480x640 (no detections), 337.1ms
Speed: 3.7ms preprocess, 337.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBecUDsxmcrVVi7eCmxxMw_90.JPG: 480x640 (no detections), 317.4ms
Speed: 1.7ms preprocess, 317.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBecUDsxmcrVVi7eCmxxMw_180.JPG: 480x640 (no detections), 337.8ms
Speed: 1.2ms preprocess, 337.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBecUDsxmcrVVi7eCmxxMw_270.JPG: 480x640 (no detections), 308.3ms
Speed: 1.1ms preprocess, 308.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBgn6x1AeA749CwJFnxQQA_0.JPG: 480x640 (no detections), 318.6ms
Speed: 1.1ms preprocess, 318.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBgn6x1AeA749CwJFnxQQA_90.JPG: 480x640 (no detections), 310.9ms
Speed: 1.4ms preprocess, 310.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBgn6x1AeA749CwJFnxQQA_180.JPG: 480x640 (no detections), 278.2ms
Speed: 1.0ms preprocess, 278.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBgn6x1AeA749CwJFnxQQA_270.JPG: 480x640 (no detections), 282.5ms
Speed: 1.3ms preprocess, 282.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBjKBxoBwg6nLtskPqjQ9A_0.JPG: 480x640 (no detections), 276.6ms
Speed: 1.2ms preprocess, 276.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBjKBxoBwg6nLtskPqjQ9A_90.JPG: 480x640 (no detections), 309.6ms
Speed: 1.1ms preprocess, 309.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBjKBxoBwg6nLtskPqjQ9A_180.JPG: 480x640 (no detections), 279.7ms
Speed: 1.1ms preprocess, 279.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBjKBxoBwg6nLtskPqjQ9A_270.JPG: 480x640 (no detections), 289.5ms
Speed: 1.1ms preprocess, 289.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBjxrzfYKpbZ-djlfK8iQw_0.JPG: 480x640 (no detections), 295.5ms
Speed: 1.1ms preprocess, 295.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBjxrzfYKpbZ-djlfK8iQw_90.JPG: 480x640 (no detections), 321.8ms
Speed: 2.9ms preprocess, 321.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBjxrzfYKpbZ-djlfK8iQw_180.JPG: 480x640 (no detections), 313.8ms
Speed: 1.6ms preprocess, 313.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBjxrzfYKpbZ-djlfK8iQw_270.JPG: 480x640 (no detections), 293.9ms
Speed: 1.2ms preprocess, 293.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBkoZs1qsng6H0BpMB-BEg_0.JPG: 480x640 2 Wastes, 299.9ms
Speed: 1.1ms preprocess, 299.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBkoZs1qsng6H0BpMB-BEg_90.JPG: 480x640 2 Wastes, 291.6ms
Speed: 1.4ms preprocess, 291.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBkoZs1qsng6H0BpMB-BEg_180.JPG: 480x640 (no detections), 297.4ms
Speed: 1.2ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBkoZs1qsng6H0BpMB-BEg_270.JPG: 480x640 (no detections), 284.5ms
Speed: 1.2ms preprocess, 284.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBtJ4WnWe1HsTJKKGr5DEQ_0.JPG: 480x640 (no detections), 274.7ms
Speed: 1.2ms preprocess, 274.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBtJ4WnWe1HsTJKKGr5DEQ_90.JPG: 480x640 (no detections), 281.9ms
Speed: 1.2ms preprocess, 281.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBtJ4WnWe1HsTJKKGr5DEQ_180.JPG: 480x640 (no detections), 291.9ms
Speed: 1.2ms preprocess, 291.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBtJ4WnWe1HsTJKKGr5DEQ_270.JPG: 480x640 (no detections), 276.9ms
Speed: 1.1ms preprocess, 276.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBuC1w8ep_y8PDe-kyj5vA_0.JPG: 480x640 (no detections), 273.3ms
Speed: 1.0ms preprocess, 273.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBuC1w8ep_y8PDe-kyj5vA_90.JPG: 480x640 (no detections), 293.5ms
Speed: 1.0ms preprocess, 293.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBuC1w8ep_y8PDe-kyj5vA_180.JPG: 480x640 (no detections), 272.9ms
Speed: 1.2ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBuC1w8ep_y8PDe-kyj5vA_270.JPG: 480x640 (no detections), 275.2ms

Speed: 1.1ms preprocess, 275.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBumB5P8EyCk2ZifeMtD-A_0.JPG: 480x640 1 Waste, 303.5ms
Speed: 1.0ms preprocess, 303.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBumB5P8EyCk2ZifeMtD-A_90.JPG: 480x640 (no detections), 290.0ms
Speed: 1.2ms preprocess, 290.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBumB5P8EyCk2ZifeMtD-A_180.JPG: 480x640 (no detections), 289.2ms
Speed: 1.1ms preprocess, 289.2ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBumB5P8EyCk2ZifeMtD-A_270.JPG: 480x640 (no detections), 295.7ms
Speed: 1.4ms preprocess, 295.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBzDOXxqXQsBCFe3rBC88w_0.JPG: 480x640 (no detections), 281.6ms
Speed: 1.1ms preprocess, 281.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBzDOXxqXQsBCFe3rBC88w_90.JPG: 480x640 (no detections), 281.9ms
Speed: 1.0ms preprocess, 281.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBzDOXxqXQsBCFe3rBC88w_180.JPG: 480x640 (no detections), 288.7ms
Speed: 1.1ms preprocess, 288.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zBzDOXxqXQsBCFe3rBC88w_270.JPG: 480x640 (no detections), 280.8ms
Speed: 1.1ms preprocess, 280.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zC4PBmrJV2MYIsi1NhGQcw_0.JPG: 480x640 (no detections), 284.0ms
Speed: 1.0ms preprocess, 284.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zC4PBmrJV2MYIsi1NhGQcw_90.JPG: 480x640 (no detections), 286.1ms
Speed: 1.2ms preprocess, 286.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zC4PBmrJV2MYIsi1NhGQcw_180.JPG: 480x640 (no detections), 285.9ms
Speed: 1.0ms preprocess, 285.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zC4PBmrJV2MYIsi1NhGQcw_270.JPG: 480x640 (no detections), 283.7ms
Speed: 1.2ms preprocess, 283.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zC6MOsJDeI1Ip5S6_zrhqw_0.JPG: 480x640 (no detections), 278.1ms
Speed: 1.1ms preprocess, 278.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zC6MOsJDeI1Ip5S6_zrhqw_90.JPG: 480x640 (no detections), 281.8ms
Speed: 1.1ms preprocess, 281.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zC6MOsJDeI1Ip5S6_zrhqw_180.JPG: 480x640 (no detections), 281.6ms
Speed: 1.1ms preprocess, 281.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zC6MOsJDeI1Ip5S6_zrhqw_270.JPG: 480x640 (no detections), 275.4ms
Speed: 1.1ms preprocess, 275.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCACiswu_6Oh-kRKgZb4fw_0.JPG: 480x640 (no detections), 277.6ms
Speed: 1.1ms preprocess, 277.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCACiswu_6Oh-kRKgZb4fw_90.JPG: 480x640 (no detections), 273.5ms
Speed: 1.2ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCACiswu_6Oh-kRKgZb4fw_180.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCACiswu_6Oh-kRKgZb4fw_270.JPG: 480x640 (no detections), 272.1ms
Speed: 1.1ms preprocess, 272.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCK-tFVOx-5JF1MwKT88FA_0.JPG: 480x640 (no detections), 269.3ms
Speed: 1.0ms preprocess, 269.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCK-tFVOx-5JF1MwKT88FA_90.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCK-tFVOx-5JF1MwKT88FA_180.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCK-tFVOx-5JF1MwKT88FA_270.JPG: 480x640 (no detections), 274.3ms
Speed: 1.1ms preprocess, 274.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCM6zGq500aLSbXqMbHjhA_0.JPG: 480x640 (no detections), 271.8ms
Speed: 1.0ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCM6zGq500aLSbXqMbHjhA_90.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCM6zGq500aLSbXqMbHjhA_180.JPG: 480x640 (no detections), 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCM6zGq500aLSbXqMbHjhA_270.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCMbuRTyHWmBXgX-IEsAQA_0.JPG: 480x640 (no detections), 269.8ms
Speed: 1.0ms preprocess, 269.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCMbuRTyHWmBXgX-IEsAQA_90.JPG: 480x640 (no detections), 272.3ms
Speed: 1.0ms preprocess, 272.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCMbuRTyHWmBXgX-IEsAQA_180.JPG: 480x640 (no detections), 272.3ms
Speed: 1.0ms preprocess, 272.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCMbuRTyHWmBXgX-IEsAQA_270.JPG: 480x640 (no detections), 274.0ms
Speed: 1.1ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCMfaEXXFKqsq-DIQpMwOg_0.JPG: 480x640 (no detections), 271.5ms
Speed: 1.0ms preprocess, 271.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCMfaEXXFKqsq-DIQpMwOg_90.JPG: 480x640 (no detections), 274.2ms
Speed: 1.1ms preprocess, 274.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCMfaEXXFKqsq-DIQpMwOg_180.JPG: 480x640 (no detections), 266.6ms
Speed: 1.2ms preprocess, 266.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCMfaEXXFKqsq-DIQpMwOg_270.JPG: 480x640 (no detections), 304.9ms
Speed: 1.1ms preprocess, 304.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCOGkIYs-6bVspXWXoVHZQ_0.JPG: 480x640 (no detections), 274.3ms
Speed: 1.1ms preprocess, 274.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCOGkIYs-6bVspXWXoVHZQ_90.JPG: 480x640 (no detections), 272.1ms
Speed: 1.2ms preprocess, 272.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCOGkIYs-6bVspXWXoVHZQ_180.JPG: 480x640 (no detections), 271.8ms
Speed: 1.0ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCOGkIYs-6bVspXWXoVHZQ_270.JPG: 480x640 (no detections), 272.6ms
Speed: 1.0ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCP8uoCjaUkWAFBf9Y544w_0.JPG: 480x640 (no detections), 276.0ms
Speed: 1.2ms preprocess, 276.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCP8uoCjaUkWAFBf9Y544w_90.JPG: 480x640 (no detections), 267.2ms
Speed: 1.0ms preprocess, 267.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCP8uoCjaUkWAFBf9Y544w_180.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCP8uoCjaUkWAFBf9Y544w_270.JPG: 480x640 (no detections), 271.5ms
Speed: 1.0ms preprocess, 271.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCRTAvrdlDOvbvd43ObnFw_0.JPG: 480x640 (no detections), 270.5ms
Speed: 1.0ms preprocess, 270.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCRTAvrdlDOvbvd43ObnFw_90.JPG: 480x640 (no detections), 278.5ms
Speed: 1.1ms preprocess, 278.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCRTAvrdlDOvbvd43ObnFw_180.JPG: 480x640 (no detections), 277.0ms
Speed: 1.0ms preprocess, 277.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCRTAvrdlDOvbvd43ObnFw_270.JPG: 480x640 (no detections), 279.8ms
Speed: 1.1ms preprocess, 279.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCS2WBk646b1B9U0McIHWQ_0.JPG: 480x640 (no detections), 274.2ms
Speed: 1.1ms preprocess, 274.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCS2WBk646b1B9U0McIHWQ_90.JPG: 480x640 (no detections), 282.3ms
Speed: 1.0ms preprocess, 282.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCS2WBk646b1B9U0McIHWQ_180.JPG: 480x640 (no detections), 280.3ms
Speed: 1.3ms preprocess, 280.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCS2WBk646b1B9U0McIHWQ_270.JPG: 480x640 (no detections), 278.9ms
Speed: 1.1ms preprocess, 278.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCSt_yqCCsWRzC6EVIVgqA_0.JPG: 480x640 (no detections), 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCSt_yqCCsWRzC6EVIVgqA_90.JPG: 480x640 (no detections), 272.5ms
Speed: 1.0ms preprocess, 272.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCSt_yqCCsWRzC6EVIVgqA_180.JPG: 480x640 (no detections), 314.5ms
Speed: 1.0ms preprocess, 314.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCSt_yqCCsWRzC6EVIVgqA_270.JPG: 480x640 (no detections), 285.3ms
Speed: 1.2ms preprocess, 285.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCSzfjRxXdiFK22rRHcIug_0.JPG: 480x640 (no detections), 310.4ms
Speed: 1.2ms preprocess, 310.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCSzfjRxXdiFK22rRHcIug_90.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCSzfjRxXdiFK22rRHcIug_180.JPG: 480x640 (no detections), 306.6ms
Speed: 1.1ms preprocess, 306.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCSzfjRxXdiFK22rRHcIug_270.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCTkEwaOUNVi3fuCx0VeWg_0.JPG: 480x640 1 Waste, 285.4ms
Speed: 1.2ms preprocess, 285.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCTkEwaOUNVi3fuCx0VeWg_90.JPG: 480x640 (no detections), 275.9ms
Speed: 1.1ms preprocess, 275.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCTkEwaOUNVi3fuCx0VeWg_180.JPG: 480x640 (no detections), 273.4ms
Speed: 1.2ms preprocess, 273.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCTkEwaOUNVi3fuCx0VeWg_270.JPG: 480x640 (no detections), 277.8ms
Speed: 1.1ms preprocess, 277.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCTz56xd6nJH2paJH9ur5g_0.JPG: 480x640 (no detections), 283.1ms
Speed: 1.0ms preprocess, 283.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCTz56xd6nJH2paJH9ur5g_90.JPG: 480x640 (no detections), 275.7ms
Speed: 1.0ms preprocess, 275.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCTz56xd6nJH2paJH9ur5g_180.JPG: 480x640 (no detections), 272.3ms

Speed: 1.1ms preprocess, 272.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCTz56xd6nJH2paJH9ur5g_270.JPG: 480x640 (no detections), 273.5ms
Speed: 1.0ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCWnI5WM1uDbLs0wv-iJ-w_0.JPG: 480x640 (no detections), 271.3ms
Speed: 1.0ms preprocess, 271.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCWnI5WM1uDbLs0wv-iJ-w_90.JPG: 480x640 (no detections), 281.4ms
Speed: 1.0ms preprocess, 281.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCWnI5WM1uDbLs0wv-iJ-w_180.JPG: 480x640 (no detections), 399.1ms
Speed: 1.7ms preprocess, 399.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCWnI5WM1uDbLs0wv-iJ-w_270.JPG: 480x640 (no detections), 279.0ms
Speed: 1.4ms preprocess, 279.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCaVFJLXRxk4yQKHPft3cQ_0.JPG: 480x640 (no detections), 274.5ms
Speed: 1.6ms preprocess, 274.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCaVFJLXRxk4yQKHPft3cQ_90.JPG: 480x640 (no detections), 289.2ms
Speed: 1.1ms preprocess, 289.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCaVFJLXRxk4yQKHPft3cQ_180.JPG: 480x640 (no detections), 275.3ms
Speed: 1.0ms preprocess, 275.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCaVFJLXRxk4yQKHPft3cQ_270.JPG: 480x640 (no detections), 277.9ms
Speed: 1.1ms preprocess, 277.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCcybBsxbsdJa-DdY1LBwg_0.JPG: 480x640 (no detections), 327.9ms
Speed: 1.1ms preprocess, 327.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCcybBsxbsdJa-DdY1LBwg_90.JPG: 480x640 (no detections), 292.9ms
Speed: 2.0ms preprocess, 292.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCcybBsxbsdJa-DdY1LBwg_180.JPG: 480x640 (no detections), 353.9ms
Speed: 1.2ms preprocess, 353.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCcybBsxbsdJa-DdY1LBwg_270.JPG: 480x640 (no detections), 351.1ms
Speed: 1.4ms preprocess, 351.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCnPUYCC_PtZgaI2J0DPlw_0.JPG: 480x640 (no detections), 309.3ms
Speed: 2.0ms preprocess, 309.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCnPUYCC_PtZgaI2J0DPlw_90.JPG: 480x640 (no detections), 324.2ms
Speed: 1.0ms preprocess, 324.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCnPUYCC_PtZgaI2J0DPlw_180.JPG: 480x640 (no detections), 295.1ms
Speed: 1.5ms preprocess, 295.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCnPUYCC_PtZgaI2J0DPlw_270.JPG: 480x640 (no detections), 356.7ms
Speed: 1.3ms preprocess, 356.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCpmn1dtxsCqHp96p860fQ_0.JPG: 480x640 (no detections), 295.5ms
Speed: 1.4ms preprocess, 295.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCpmn1dtxsCqHp96p860fQ_90.JPG: 480x640 (no detections), 341.5ms
Speed: 1.4ms preprocess, 341.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCpmn1dtxsCqHp96p860fQ_180.JPG: 480x640 (no detections), 410.7ms
Speed: 1.3ms preprocess, 410.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCpmn1dtxsCqHp96p860fQ_270.JPG: 480x640 (no detections), 285.7ms
Speed: 1.2ms preprocess, 285.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCq_AMHlFCju4XlRk513fA_0.JPG: 480x640 (no detections), 269.8ms
Speed: 1.1ms preprocess, 269.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCq_AMHlFCju4XlRk513fA_90.JPG: 480x640 (no detections), 277.0ms
Speed: 1.0ms preprocess, 277.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCq_AMHlFCju4XlRk513fA_180.JPG: 480x640 (no detections), 296.1ms
Speed: 1.1ms preprocess, 296.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCq_AMHlFCju4XlRk513fA_270.JPG: 480x640 (no detections), 347.4ms
Speed: 1.3ms preprocess, 347.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCqgbKxPVowHOI-TtOFKzQ_0.JPG: 480x640 (no detections), 299.5ms
Speed: 1.3ms preprocess, 299.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCqgbKxPVowHOI-TtOFKzQ_90.JPG: 480x640 (no detections), 297.7ms
Speed: 1.4ms preprocess, 297.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCqgbKxPVowHOI-TtOFKzQ_180.JPG: 480x640 (no detections), 278.2ms
Speed: 1.1ms preprocess, 278.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCqgbKxPVowHOI-TtOFKzQ_270.JPG: 480x640 1 Waste, 290.7ms
Speed: 1.1ms preprocess, 290.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCr_UP1uQCd5N033XDYreA_0.JPG: 480x640 (no detections), 278.4ms
Speed: 1.1ms preprocess, 278.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCr_UP1uQCd5N033XDYreA_90.JPG: 480x640 (no detections), 274.9ms
Speed: 1.1ms preprocess, 274.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCr_UP1uQCd5N033XDYreA_180.JPG: 480x640 (no detections), 275.4ms
Speed: 1.0ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCr_UP1uQCd5N033XDYreA_270.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCsnPVJjWTdrJvUznxwNQA_0.JPG: 480x640 (no detections), 298.6ms
Speed: 1.1ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCsnPVJjWTdrJvUznxwNQA_90.JPG: 480x640 (no detections), 370.5ms
Speed: 1.3ms preprocess, 370.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCsnPVJjWTdrJvUznxwNQA_180.JPG: 480x640 (no detections), 417.3ms
Speed: 1.2ms preprocess, 417.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCsnPVJjWTdrJvUznxwNQA_270.JPG: 480x640 (no detections), 432.5ms
Speed: 1.4ms preprocess, 432.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCtNCDvl8AWi4XZKXU_ZnA_0.JPG: 480x640 (no detections), 342.6ms
Speed: 1.3ms preprocess, 342.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCtNCDvl8AWi4XZKXU_ZnA_90.JPG: 480x640 (no detections), 311.8ms
Speed: 1.0ms preprocess, 311.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCtNCDvl8AWi4XZKXU_ZnA_180.JPG: 480x640 (no detections), 308.8ms
Speed: 2.0ms preprocess, 308.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCtNCDvl8AWi4XZKXU_ZnA_270.JPG: 480x640 (no detections), 298.7ms
Speed: 1.6ms preprocess, 298.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCtj8zagGIQIBwwiCo6Uhw_0.JPG: 480x640 (no detections), 319.8ms
Speed: 1.2ms preprocess, 319.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCtj8zagGIQIBwwiCo6Uhw_90.JPG: 480x640 (no detections), 305.6ms
Speed: 1.3ms preprocess, 305.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCtj8zagGIQIBwwiCo6Uhw_180.JPG: 480x640 (no detections), 291.7ms
Speed: 1.0ms preprocess, 291.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCtj8zagGIQIBwwiCo6Uhw_270.JPG: 480x640 1 Waste, 296.7ms
Speed: 2.0ms preprocess, 296.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCuG9DvrrT3AEYTsns-iOg_0.JPG: 480x640 (no detections), 297.9ms
Speed: 1.1ms preprocess, 297.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCuG9DvrrT3AEYTsns-iOg_90.JPG: 480x640 (no detections), 298.0ms
Speed: 1.2ms preprocess, 298.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCuG9DvrrT3AEYTsns-iOg_180.JPG: 480x640 (no detections), 285.0ms
Speed: 1.5ms preprocess, 285.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCuG9DvrrT3AEYTsns-iOg_270.JPG: 480x640 (no detections), 292.1ms
Speed: 2.5ms preprocess, 292.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCyUwghhfN3--S_6aQeQkw_0.JPG: 480x640 (no detections), 278.5ms
Speed: 1.3ms preprocess, 278.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCyUwghhfN3--S_6aQeQkw_90.JPG: 480x640 (no detections), 291.8ms
Speed: 1.2ms preprocess, 291.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCyUwghhfN3--S_6aQeQkw_180.JPG: 480x640 (no detections), 277.0ms
Speed: 1.1ms preprocess, 277.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCyUwghhfN3--S_6aQeQkw_270.JPG: 480x640 (no detections), 299.9ms
Speed: 2.7ms preprocess, 299.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCycgayNcCXpXLL0v4argA_0.JPG: 480x640 (no detections), 272.9ms
Speed: 1.2ms preprocess, 272.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCycgayNcCXpXLL0v4argA_90.JPG: 480x640 (no detections), 268.1ms
Speed: 1.1ms preprocess, 268.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCycgayNcCXpXLL0v4argA_180.JPG: 480x640 (no detections), 284.9ms
Speed: 1.2ms preprocess, 284.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zCycgayNcCXpXLL0v4argA_270.JPG: 480x640 (no detections), 306.6ms
Speed: 1.2ms preprocess, 306.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zD0Y0KDDVgfgNLAdDr1_Iw_0.JPG: 480x640 (no detections), 274.5ms
Speed: 1.2ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zD0Y0KDDVgfgNLAdDr1_Iw_90.JPG: 480x640 (no detections), 279.0ms
Speed: 1.1ms preprocess, 279.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zD0Y0KDDVgfgNLAdDr1_Iw_180.JPG: 480x640 (no detections), 272.7ms
Speed: 1.0ms preprocess, 272.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zD0Y0KDDVgfgNLAdDr1_Iw_270.JPG: 480x640 (no detections), 281.9ms
Speed: 1.1ms preprocess, 281.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zD10OfCp2oYlTZocyjZ4FQ_0.JPG: 480x640 (no detections), 276.0ms
Speed: 1.1ms preprocess, 276.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zD10OfCp2oYlTZocyjZ4FQ_90.JPG: 480x640 (no detections), 286.1ms
Speed: 1.1ms preprocess, 286.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zD10OfCp2oYlTZocyjZ4FQ_180.JPG: 480x640 (no detections), 289.8ms
Speed: 1.2ms preprocess, 289.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zD10OfCp2oYlTZocyjZ4FQ_270.JPG: 480x640 (no detections), 276.6ms
Speed: 1.2ms preprocess, 276.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zD3Vcfuj2QdzF6-yT5VcnQ_0.JPG: 480x640 (no detections), 280.8ms
Speed: 1.1ms preprocess, 280.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zD3Vcfuj2QdzF6-yT5VcnQ_90.JPG: 480x640 (no detections), 301.9ms

Speed: 1.3ms preprocess, 301.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zD3Vcfuj2QdzF6-yT5VcnQ_180.JPG: 480x640 (no detections), 283.7ms
Speed: 1.5ms preprocess, 283.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zD3Vcfuj2QdzF6-yT5VcnQ_270.JPG: 480x640 (no detections), 289.7ms
Speed: 1.8ms preprocess, 289.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zD3sJWPnigRZE0k5Ahk_Pw_0.JPG: 480x640 (no detections), 285.5ms
Speed: 1.0ms preprocess, 285.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zD3sJWPnigRZE0k5Ahk_Pw_90.JPG: 480x640 (no detections), 272.8ms
Speed: 1.2ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zD3sJWPnigRZE0k5Ahk_Pw_180.JPG: 480x640 (no detections), 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zD3sJWPnigRZE0k5Ahk_Pw_270.JPG: 480x640 (no detections), 364.2ms
Speed: 1.0ms preprocess, 364.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zD4gGap1msaL2i6zNViSdg_0.JPG: 480x640 (no detections), 276.7ms
Speed: 1.1ms preprocess, 276.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zD4gGap1msaL2i6zNViSdg_90.JPG: 480x640 (no detections), 307.5ms
Speed: 1.1ms preprocess, 307.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zD4gGap1msaL2i6zNViSdg_180.JPG: 480x640 (no detections), 305.9ms
Speed: 1.1ms preprocess, 305.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zD4gGap1msaL2i6zNViSdg_270.JPG: 480x640 (no detections), 274.6ms
Speed: 1.5ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zD56wEtt-s3xfUZ4gwKDpQ_0.JPG: 480x640 (no detections), 284.5ms
Speed: 1.1ms preprocess, 284.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zD56wEtt-s3xfUZ4gwKDpQ_90.JPG: 480x640 (no detections), 302.9ms
Speed: 1.2ms preprocess, 302.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zD56wEtt-s3xfUZ4gwKDpQ_180.JPG: 480x640 1 Waste, 282.6ms
Speed: 1.1ms preprocess, 282.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zD56wEtt-s3xfUZ4gwKDpQ_270.JPG: 480x640 (no detections), 275.0ms
Speed: 1.1ms preprocess, 275.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zD5hfYaCq_rcadcr5L1U8A_0.JPG: 480x640 (no detections), 280.0ms
Speed: 1.1ms preprocess, 280.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zD5hfYaCq_rcadcr5L1U8A_90.JPG: 480x640 (no detections), 313.8ms
Speed: 1.0ms preprocess, 313.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zD5hfYaCq_rcadcr5L1U8A_180.JPG: 480x640 (no detections), 277.2ms
Speed: 1.2ms preprocess, 277.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zD5hfYaCq_rcadcr5L1U8A_270.JPG: 480x640 (no detections), 274.7ms
Speed: 1.2ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zD7KGPLUYQN335jCPQYqSw_0.JPG: 480x640 (no detections), 270.8ms
Speed: 1.0ms preprocess, 270.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zD7KGPLUYQN335jCPQYqSw_90.JPG: 480x640 (no detections), 284.9ms
Speed: 1.0ms preprocess, 284.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zD7KGPLUYQN335jCPQYqSw_180.JPG: 480x640 (no detections), 284.6ms
Speed: 1.1ms preprocess, 284.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zD7KGPLUYQN335jCPQYqSw_270.JPG: 480x640 (no detections), 280.8ms
Speed: 1.1ms preprocess, 280.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zD84bc-SfFyt1pb1MyVILw_0.JPG: 480x640 (no detections), 281.0ms
Speed: 1.1ms preprocess, 281.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zD84bc-SfFyt1pb1MyVILw_90.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zD84bc-SfFyt1pb1MyVILw_180.JPG: 480x640 (no detections), 269.3ms
Speed: 1.1ms preprocess, 269.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zD84bc-SfFyt1pb1MyVILw_270.JPG: 480x640 (no detections), 276.3ms
Speed: 1.0ms preprocess, 276.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zD8Zo5PbMXrRjgu91CMc_A_0.JPG: 480x640 (no detections), 267.1ms
Speed: 1.0ms preprocess, 267.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zD8Zo5PbMXrRjgu91CMc_A_90.JPG: 480x640 (no detections), 292.3ms
Speed: 1.6ms preprocess, 292.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zD8Zo5PbMXrRjgu91CMc_A_180.JPG: 480x640 (no detections), 355.1ms
Speed: 1.1ms preprocess, 355.1ms inference, 1.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zD8Zo5PbMXrRjgu91CMc_A_270.JPG: 480x640 (no detections), 295.3ms
Speed: 1.2ms preprocess, 295.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDAoSpR4Ts8Or6g4_wbhaQ_0.JPG: 480x640 (no detections), 270.6ms
Speed: 1.3ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDAoSpR4Ts8Or6g4_wbhaQ_90.JPG: 480x640 (no detections), 324.3ms
Speed: 1.1ms preprocess, 324.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDAoSpR4Ts8Or6g4_wbhaQ_180.JPG: 480x640 (no detections), 301.3ms
Speed: 1.3ms preprocess, 301.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDAoSpR4Ts8Or6g4_wbhaQ_270.JPG: 480x640 (no detections), 286.7ms
Speed: 1.1ms preprocess, 286.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDAp2lErIYsbjgvxb--4qA_0.JPG: 480x640 (no detections), 276.0ms
Speed: 1.1ms preprocess, 276.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDAp2lErIYsbjgvxb--4qA_90.JPG: 480x640 (no detections), 277.1ms
Speed: 1.1ms preprocess, 277.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDAp2lErIYsbjgvxb--4qA_180.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDAp2lErIYsbjgvxb--4qA_270.JPG: 480x640 (no detections), 276.9ms
Speed: 1.1ms preprocess, 276.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDIAG0np3CGctkbsAEnQMQ_0.JPG: 480x640 1 Waste, 268.9ms
Speed: 1.0ms preprocess, 268.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDIAG0np3CGctkbsAEnQMQ_90.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDIAG0np3CGctkbsAEnQMQ_180.JPG: 480x640 (no detections), 296.6ms
Speed: 1.1ms preprocess, 296.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDIAG0np3CGctkbsAEnQMQ_270.JPG: 480x640 (no detections), 275.3ms
Speed: 1.2ms preprocess, 275.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDJ7qZHb8I8kMrczN4eq2A_0.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDJ7qZHb8I8kMrczN4eq2A_90.JPG: 480x640 (no detections), 329.2ms
Speed: 1.0ms preprocess, 329.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDJ7qZHb8I8kMrczN4eq2A_180.JPG: 480x640 (no detections), 295.9ms
Speed: 1.0ms preprocess, 295.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDJ7qZHb8I8kMrczN4eq2A_270.JPG: 480x640 (no detections), 275.6ms
Speed: 1.0ms preprocess, 275.6ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDJFshI6r-8YxTq71MMXhg_0.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDJFshI6r-8YxTq71MMXhg_90.JPG: 480x640 (no detections), 281.7ms
Speed: 1.0ms preprocess, 281.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDJFshI6r-8YxTq71MMXhg_180.JPG: 480x640 (no detections), 291.5ms
Speed: 1.5ms preprocess, 291.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDJFshI6r-8YxTq71MMXhg_270.JPG: 480x640 (no detections), 287.6ms
Speed: 1.0ms preprocess, 287.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDLDcXkvA66xSQXH3vGgug_0.JPG: 480x640 (no detections), 274.8ms
Speed: 1.2ms preprocess, 274.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDLDcXkvA66xSQXH3vGgug_90.JPG: 480x640 (no detections), 273.5ms
Speed: 1.5ms preprocess, 273.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDLDcXkvA66xSQXH3vGgug_180.JPG: 480x640 (no detections), 273.2ms
Speed: 1.1ms preprocess, 273.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDLDcXkvA66xSQXH3vGgug_270.JPG: 480x640 (no detections), 272.3ms
Speed: 1.0ms preprocess, 272.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDTj_ne6D7QYxpb6KNue2w_0.JPG: 480x640 (no detections), 276.2ms
Speed: 1.1ms preprocess, 276.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDTj_ne6D7QYxpb6KNue2w_90.JPG: 480x640 (no detections), 271.3ms
Speed: 1.3ms preprocess, 271.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDTj_ne6D7QYxpb6KNue2w_180.JPG: 480x640 (no detections), 272.5ms
Speed: 1.1ms preprocess, 272.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDTj_ne6D7QYxpb6KNue2w_270.JPG: 480x640 (no detections), 276.7ms
Speed: 1.0ms preprocess, 276.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDaB68pBy-b2V_u-4VEOng_0.JPG: 480x640 (no detections), 269.3ms
Speed: 1.0ms preprocess, 269.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDaB68pBy-b2V_u-4VEOng_90.JPG: 480x640 1 Waste, 271.3ms
Speed: 1.2ms preprocess, 271.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDaB68pBy-b2V_u-4VEOng_180.JPG: 480x640 1 Waste, 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDaB68pBy-b2V_u-4VEOng_270.JPG: 480x640 (no detections), 278.4ms
Speed: 1.1ms preprocess, 278.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDaJSc498fThFHiI8Bq2qw_0.JPG: 480x640 (no detections), 271.0ms
Speed: 1.1ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDaJSc498fThFHiI8Bq2qw_90.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDaJSc498fThFHiI8Bq2qw_180.JPG: 480x640 (no detections), 272.7ms
Speed: 1.0ms preprocess, 272.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDaJSc498fThFHiI8Bq2qw_270.JPG: 480x640 (no detections), 270.0ms
Speed: 1.0ms preprocess, 270.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDc8Itx8IpOHEUYwADtINQ_0.JPG: 480x640 (no detections), 271.1ms

Speed: 1.1ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDc8Itx8IpOHEUYwADtINQ_90.JPG: 480x640 (no detections), 271.8ms
Speed: 1.0ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDc8Itx8IpOHEUYwADtINQ_180.JPG: 480x640 (no detections), 274.3ms
Speed: 1.3ms preprocess, 274.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDc8Itx8IpOHEUYwADtINQ_270.JPG: 480x640 (no detections), 275.4ms
Speed: 1.1ms preprocess, 275.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDcjnNO_ZsqnS4ZClfYhRQ_0.JPG: 480x640 (no detections), 276.5ms
Speed: 1.1ms preprocess, 276.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDcjnNO_ZsqnS4ZClfYhRQ_90.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDcjnNO_ZsqnS4ZClfYhRQ_180.JPG: 480x640 1 Waste, 287.4ms
Speed: 1.1ms preprocess, 287.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDcjnNO_ZsqnS4ZClfYhRQ_270.JPG: 480x640 (no detections), 269.6ms
Speed: 1.4ms preprocess, 269.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDdAxLMxZ5CNYAIUEWfTng_0.JPG: 480x640 (no detections), 276.5ms
Speed: 1.1ms preprocess, 276.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDdAxLMxZ5CNYAIUEWfTng_90.JPG: 480x640 (no detections), 273.9ms
Speed: 1.0ms preprocess, 273.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDdAxLMxZ5CNYAIUEWfTng_180.JPG: 480x640 (no detections), 316.4ms
Speed: 1.1ms preprocess, 316.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDdAxLMxZ5CNYAIUEWfTng_270.JPG: 480x640 (no detections), 273.8ms
Speed: 1.3ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDh3nJwax7tN3CVv0VADAw_0.JPG: 480x640 (no detections), 307.1ms
Speed: 1.1ms preprocess, 307.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDh3nJwax7tN3CVv0VADAw_90.JPG: 480x640 (no detections), 295.3ms
Speed: 1.2ms preprocess, 295.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDh3nJwax7tN3CVv0VADAw_180.JPG: 480x640 (no detections), 281.2ms
Speed: 1.6ms preprocess, 281.2ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDh3nJwax7tN3CVv0VADAw_270.JPG: 480x640 (no detections), 309.2ms
Speed: 1.2ms preprocess, 309.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDkLqf_7bSCmngN_ON81tw_0.JPG: 480x640 (no detections), 293.4ms
Speed: 1.2ms preprocess, 293.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDkLqf_7bSCmngN_ON81tw_90.JPG: 480x640 (no detections), 291.9ms
Speed: 1.2ms preprocess, 291.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDkLqf_7bSCmngN_ON81tw_180.JPG: 480x640 1 Waste, 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDkLqf_7bSCmngN_ON81tw_270.JPG: 480x640 1 Waste, 282.2ms
Speed: 1.1ms preprocess, 282.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDqGC2qwpWE1MVaj-hs3nw_0.JPG: 480x640 (no detections), 279.7ms
Speed: 1.4ms preprocess, 279.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDqGC2qwpWE1MVaj-hs3nw_90.JPG: 480x640 (no detections), 284.5ms
Speed: 1.2ms preprocess, 284.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDqGC2qwpWE1MVaj-hs3nw_180.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDqGC2qwpWE1MVaj-hs3nw_270.JPG: 480x640 (no detections), 284.0ms
Speed: 1.3ms preprocess, 284.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDxdzT42ZeVLFPWNPW9iQg_0.JPG: 480x640 (no detections), 273.1ms
Speed: 1.1ms preprocess, 273.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDxdzT42ZeVLFPWNPW9iQg_90.JPG: 480x640 (no detections), 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDxdzT42ZeVLFPWNPW9iQg_180.JPG: 480x640 (no detections), 297.5ms
Speed: 1.3ms preprocess, 297.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDxdzT42ZeVLFPWNPW9iQg_270.JPG: 480x640 (no detections), 280.6ms
Speed: 1.1ms preprocess, 280.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDzIHgVT-_l3KE4BvXOBlQ_0.JPG: 480x640 (no detections), 277.3ms
Speed: 1.2ms preprocess, 277.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDzIHgVT-_l3KE4BvXOBlQ_90.JPG: 480x640 (no detections), 353.6ms
Speed: 1.4ms preprocess, 353.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDzIHgVT-_l3KE4BvXOBlQ_180.JPG: 480x640 (no detections), 284.7ms
Speed: 3.3ms preprocess, 284.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDzIHgVT-_l3KE4BvXOBlQ_270.JPG: 480x640 (no detections), 274.6ms
Speed: 1.2ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDzsP4eT6nnIMqays3xWQA_0.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDzsP4eT6nnIMqays3xWQA_90.JPG: 480x640 (no detections), 273.5ms
Speed: 1.0ms preprocess, 273.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDzsP4eT6nnIMqays3xWQA_180.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zDzsP4eT6nnIMqays3xWQA_270.JPG: 480x640 (no detections), 275.2ms
Speed: 1.1ms preprocess, 275.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zE-5AhusG6e7JxbuzS_oHw_0.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zE-5AhusG6e7JxbuzS_oHw_90.JPG: 480x640 (no detections), 271.8ms
Speed: 1.0ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zE-5AhusG6e7JxbuzS_oHw_180.JPG: 480x640 1 Waste, 274.2ms
Speed: 1.1ms preprocess, 274.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zE-5AhusG6e7JxbuzS_oHw_270.JPG: 480x640 (no detections), 275.5ms
Speed: 1.0ms preprocess, 275.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zE2I_QnY6T8NCmUSbe8A_w_0.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zE2I_QnY6T8NCmUSbe8A_w_90.JPG: 480x640 (no detections), 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zE2I_QnY6T8NCmUSbe8A_w_180.JPG: 480x640 1 Waste, 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zE2I_QnY6T8NCmUSbe8A_w_270.JPG: 480x640 (no detections), 276.5ms
Speed: 1.1ms preprocess, 276.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zE4NQzx1Ti7NNmVqgthAwA_0.JPG: 480x640 (no detections), 274.0ms
Speed: 1.0ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zE4NQzx1Ti7NNmVqgthAwA_90.JPG: 480x640 (no detections), 273.1ms
Speed: 1.0ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zE4NQzx1Ti7NNmVqgthAwA_180.JPG: 480x640 (no detections), 273.8ms
Speed: 1.2ms preprocess, 273.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zE4NQzx1Ti7NNmVqgthAwA_270.JPG: 480x640 (no detections), 275.1ms
Speed: 1.0ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zE4iCzmQqdGzdKTZgKc0UQ_0.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zE4iCzmQqdGzdKTZgKc0UQ_90.JPG: 480x640 (no detections), 269.0ms
Speed: 1.0ms preprocess, 269.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zE4iCzmQqdGzdKTZgKc0UQ_180.JPG: 480x640 (no detections), 269.1ms
Speed: 1.0ms preprocess, 269.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zE4iCzmQqdGzdKTZgKc0UQ_270.JPG: 480x640 (no detections), 273.2ms
Speed: 1.0ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zE6M0tUoWuA3SrQsndCgZQ_0.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zE6M0tUoWuA3SrQsndCgZQ_90.JPG: 480x640 (no detections), 272.3ms
Speed: 1.0ms preprocess, 272.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zE6M0tUoWuA3SrQsndCgZQ_180.JPG: 480x640 (no detections), 271.8ms
Speed: 1.2ms preprocess, 271.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zE6M0tUoWuA3SrQsndCgZQ_270.JPG: 480x640 (no detections), 310.8ms
Speed: 1.1ms preprocess, 310.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zE7GNHRLAajJZS_B4CjsvA_0.JPG: 480x640 (no detections), 278.6ms
Speed: 1.1ms preprocess, 278.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zE7GNHRLAajJZS_B4CjsvA_90.JPG: 480x640 (no detections), 307.9ms
Speed: 1.0ms preprocess, 307.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zE7GNHRLAajJZS_B4CjsvA_180.JPG: 480x640 (no detections), 325.7ms
Speed: 1.6ms preprocess, 325.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zE7GNHRLAajJZS_B4CjsvA_270.JPG: 480x640 (no detections), 276.1ms
Speed: 1.2ms preprocess, 276.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zE8EHcslSEepcqwdl9alnw_0.JPG: 480x640 (no detections), 281.7ms
Speed: 1.1ms preprocess, 281.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zE8EHcslSEepcqwdl9alnw_90.JPG: 480x640 (no detections), 276.5ms
Speed: 1.1ms preprocess, 276.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zE8EHcslSEepcqwdl9alnw_180.JPG: 480x640 (no detections), 277.7ms
Speed: 1.3ms preprocess, 277.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zE8EHcslSEepcqwdl9alnw_270.JPG: 480x640 (no detections), 275.4ms
Speed: 1.1ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zE9Cdky2IIVJjP6aaJvWZg_0.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zE9Cdky2IIVJjP6aaJvWZg_90.JPG: 480x640 (no detections), 307.1ms
Speed: 1.1ms preprocess, 307.1ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zE9Cdky2IIVJjP6aaJvWZg_180.JPG: 480x640 (no detections), 291.5ms
Speed: 2.1ms preprocess, 291.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zE9Cdky2IIVJjP6aaJvWZg_270.JPG: 480x640 (no detections), 277.1ms

Speed: 1.1ms preprocess, 277.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zE9MgC8UPKeH-o7f4s4ZSA_0.JPG: 480x640 (no detections), 285.6ms
Speed: 1.1ms preprocess, 285.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zE9MgC8UPKeH-o7f4s4ZSA_90.JPG: 480x640 (no detections), 281.2ms
Speed: 1.1ms preprocess, 281.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zE9MgC8UPKeH-o7f4s4ZSA_180.JPG: 480x640 (no detections), 280.6ms
Speed: 1.1ms preprocess, 280.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zE9MgC8UPKeH-o7f4s4ZSA_270.JPG: 480x640 (no detections), 287.1ms
Speed: 1.7ms preprocess, 287.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zE9ij2EKxaz_X-teMilvKw_0.JPG: 480x640 1 Waste, 278.2ms
Speed: 1.0ms preprocess, 278.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zE9ij2EKxaz_X-teMilvKw_90.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zE9ij2EKxaz_X-teMilvKw_180.JPG: 480x640 (no detections), 268.9ms
Speed: 1.0ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zE9ij2EKxaz_X-teMilvKw_270.JPG: 480x640 (no detections), 303.4ms
Speed: 1.1ms preprocess, 303.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEIice7LvI81EAjeIJ8gNw_0.JPG: 480x640 (no detections), 352.2ms
Speed: 1.3ms preprocess, 352.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEIice7LvI81EAjeIJ8gNw_90.JPG: 480x640 (no detections), 281.8ms
Speed: 1.4ms preprocess, 281.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEIice7LvI81EAjeIJ8gNw_180.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEIice7LvI81EAjeIJ8gNw_270.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEKvLnLmLrEc2XhqkWwCmw_0.JPG: 480x640 (no detections), 302.6ms
Speed: 1.2ms preprocess, 302.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEKvLnLmLrEc2XhqkWwCmw_90.JPG: 480x640 (no detections), 285.3ms
Speed: 1.2ms preprocess, 285.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEKvLnLmLrEc2XhqkWwCmw_180.JPG: 480x640 (no detections), 287.0ms
Speed: 1.2ms preprocess, 287.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEKvLnLmLrEc2XhqkWwCmw_270.JPG: 480x640 (no detections), 279.2ms
Speed: 1.2ms preprocess, 279.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEOq1l18jErbc3Vrfc18Ag_0.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEOq1l18jErbc3Vrfc18Ag_90.JPG: 480x640 (no detections), 354.6ms
Speed: 1.1ms preprocess, 354.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEOq1l18jErbc3Vrfc18Ag_180.JPG: 480x640 (no detections), 308.5ms
Speed: 1.1ms preprocess, 308.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEOq1l18jErbc3Vrfc18Ag_270.JPG: 480x640 (no detections), 293.9ms
Speed: 1.1ms preprocess, 293.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEQxjXNciA9qbbNEkN7dAw_0.JPG: 480x640 (no detections), 268.7ms
Speed: 1.1ms preprocess, 268.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEQxjXNciA9qbbNEkN7dAw_90.JPG: 480x640 (no detections), 287.6ms
Speed: 1.1ms preprocess, 287.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEQxjXNciA9qbbNEkN7dAw_180.JPG: 480x640 (no detections), 278.7ms
Speed: 1.1ms preprocess, 278.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEQxjXNciA9qbbNEkN7dAw_270.JPG: 480x640 (no detections), 275.1ms
Speed: 1.3ms preprocess, 275.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zETQPYshUTVVcv1LVqy9lA_0.JPG: 480x640 (no detections), 277.9ms
Speed: 1.2ms preprocess, 277.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zETQPYshUTVVcv1LVqy9lA_90.JPG: 480x640 (no detections), 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zETQPYshUTVVcv1LVqy9lA_180.JPG: 480x640 (no detections), 274.0ms
Speed: 1.1ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zETQPYshUTVVcv1LVqy9lA_270.JPG: 480x640 (no detections), 276.2ms
Speed: 1.1ms preprocess, 276.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEV50cX2I1NkLqPmgyxgag_0.JPG: 480x640 (no detections), 268.4ms
Speed: 1.1ms preprocess, 268.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEV50cX2I1NkLqPmgyxgag_90.JPG: 480x640 (no detections), 281.1ms
Speed: 1.0ms preprocess, 281.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEV50cX2I1NkLqPmgyxgag_180.JPG: 480x640 (no detections), 272.3ms
Speed: 1.1ms preprocess, 272.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEV50cX2I1NkLqPmgyxgag_270.JPG: 480x640 (no detections), 273.9ms
Speed: 1.1ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEX9vuM0OEdEu8JXC088PQ_0.JPG: 480x640 (no detections), 316.9ms
Speed: 1.1ms preprocess, 316.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEX9vuM0OEdEu8JXC088PQ_90.JPG: 480x640 (no detections), 278.0ms
Speed: 1.0ms preprocess, 278.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEX9vuM0OEdEu8JXC088PQ_180.JPG: 480x640 (no detections), 269.2ms
Speed: 1.0ms preprocess, 269.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEX9vuM0OEdEu8JXC088PQ_270.JPG: 480x640 (no detections), 275.0ms
Speed: 1.0ms preprocess, 275.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEZFQGFbisMohcbdKyHUmg_0.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEZFQGFbisMohcbdKyHUmg_90.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEZFQGFbisMohcbdKyHUmg_180.JPG: 480x640 1 Waste, 272.0ms
Speed: 1.0ms preprocess, 272.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEZFQGFbisMohcbdKyHUmg_270.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEdjCYYlPPQ-q1TLXfuG4Q_0.JPG: 480x640 (no detections), 270.0ms
Speed: 1.0ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEdjCYYlPPQ-q1TLXfuG4Q_90.JPG: 480x640 (no detections), 273.1ms
Speed: 1.1ms preprocess, 273.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEdjCYYlPPQ-q1TLXfuG4Q_180.JPG: 480x640 (no detections), 274.8ms
Speed: 1.3ms preprocess, 274.8ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEdjCYYlPPQ-q1TLXfuG4Q_270.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEdxqRJTukZL8X566-F_hg_0.JPG: 480x640 1 Waste, 269.8ms
Speed: 1.2ms preprocess, 269.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEdxqRJTukZL8X566-F_hg_90.JPG: 480x640 (no detections), 273.1ms
Speed: 1.0ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEdxqRJTukZL8X566-F_hg_180.JPG: 480x640 (no detections), 265.9ms
Speed: 1.0ms preprocess, 265.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEdxqRJTukZL8X566-F_hg_270.JPG: 480x640 (no detections), 274.7ms
Speed: 1.2ms preprocess, 274.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEgSXtZ6P33tgVzod-GMfw_0.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEgSXtZ6P33tgVzod-GMfw_90.JPG: 480x640 (no detections), 268.9ms
Speed: 1.1ms preprocess, 268.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEgSXtZ6P33tgVzod-GMfw_180.JPG: 480x640 (no detections), 277.7ms
Speed: 1.0ms preprocess, 277.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEgSXtZ6P33tgVzod-GMfw_270.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEi8ClfX1rQbuBVzMiuINQ_0.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEi8ClfX1rQbuBVzMiuINQ_90.JPG: 480x640 (no detections), 278.9ms
Speed: 1.0ms preprocess, 278.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEi8ClfX1rQbuBVzMiuINQ_180.JPG: 480x640 (no detections), 275.4ms
Speed: 1.3ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEi8ClfX1rQbuBVzMiuINQ_270.JPG: 480x640 (no detections), 275.7ms
Speed: 1.0ms preprocess, 275.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEuQo0urDQvWDmWizuiqLA_0.JPG: 480x640 (no detections), 271.0ms
Speed: 1.2ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEuQo0urDQvWDmWizuiqLA_90.JPG: 480x640 (no detections), 277.3ms
Speed: 1.3ms preprocess, 277.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEuQo0urDQvWDmWizuiqLA_180.JPG: 480x640 (no detections), 288.4ms
Speed: 1.2ms preprocess, 288.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEuQo0urDQvWDmWizuiqLA_270.JPG: 480x640 (no detections), 286.9ms
Speed: 1.7ms preprocess, 286.9ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEv1GW_WofMtRR01kqEHFQ_0.JPG: 480x640 2 Wastes, 318.4ms
Speed: 1.1ms preprocess, 318.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEv1GW_WofMtRR01kqEHFQ_90.JPG: 480x640 (no detections), 285.9ms
Speed: 1.2ms preprocess, 285.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEv1GW_WofMtRR01kqEHFQ_180.JPG: 480x640 (no detections), 277.1ms
Speed: 1.2ms preprocess, 277.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEv1GW_WofMtRR01kqEHFQ_270.JPG: 480x640 (no detections), 308.8ms
Speed: 1.1ms preprocess, 308.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEy66-vrR66k9NQx0qFLSw_0.JPG: 480x640 (no detections), 283.0ms
Speed: 1.1ms preprocess, 283.0ms inference, 2.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEy66-vrR66k9NQx0qFLSw_90.JPG: 480x640 (no detections), 280.9ms
Speed: 1.1ms preprocess, 280.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEy66-vrR66k9NQx0qFLSw_180.JPG: 480x640 (no detections), 274.9ms

Speed: 1.1ms preprocess, 274.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEy66-vrR66k9NQx0qFLSw_270.JPG: 480x640 (no detections), 272.7ms
Speed: 1.0ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEyAVLZHddtkiMUxx-lhQg_0.JPG: 480x640 (no detections), 275.7ms
Speed: 1.2ms preprocess, 275.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEyAVLZHddtkiMUxx-lhQg_90.JPG: 480x640 (no detections), 273.1ms
Speed: 1.2ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEyAVLZHddtkiMUxx-lhQg_180.JPG: 480x640 (no detections), 277.5ms
Speed: 1.1ms preprocess, 277.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEyAVLZHddtkiMUxx-lhQg_270.JPG: 480x640 (no detections), 272.2ms
Speed: 1.0ms preprocess, 272.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEzqshZ7RF8nQ0Jp7U1OeA_0.JPG: 480x640 (no detections), 280.4ms
Speed: 1.1ms preprocess, 280.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEzqshZ7RF8nQ0Jp7U1OeA_90.JPG: 480x640 (no detections), 278.4ms
Speed: 1.1ms preprocess, 278.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEzqshZ7RF8nQ0Jp7U1OeA_180.JPG: 480x640 (no detections), 276.3ms
Speed: 1.2ms preprocess, 276.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zEzqshZ7RF8nQ0Jp7U1OeA_270.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zF1NH8ErLg01YYpTO7KoZA_0.JPG: 480x640 (no detections), 274.5ms
Speed: 1.0ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zF1NH8ErLg01YYpTO7KoZA_90.JPG: 480x640 (no detections), 270.9ms
Speed: 1.2ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zF1NH8ErLg01YYpTO7KoZA_180.JPG: 480x640 (no detections), 266.5ms
Speed: 1.1ms preprocess, 266.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zF1NH8ErLg01YYpTO7KoZA_270.JPG: 480x640 (no detections), 271.7ms
Speed: 1.2ms preprocess, 271.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zF1rcH6Xl34TWCjolwkmwg_0.JPG: 480x640 (no detections), 276.5ms
Speed: 1.1ms preprocess, 276.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zF1rcH6Xl34TWCjolwkmwg_90.JPG: 480x640 (no detections), 282.7ms
Speed: 1.3ms preprocess, 282.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zF1rcH6Xl34TWCjolwkmwg_180.JPG: 480x640 (no detections), 327.7ms
Speed: 1.2ms preprocess, 327.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zF1rcH6Xl34TWCjolwkmwg_270.JPG: 480x640 (no detections), 286.2ms
Speed: 1.1ms preprocess, 286.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zF3gnZMt_iUq8QxfdnY8-g_0.JPG: 480x640 (no detections), 270.5ms
Speed: 1.0ms preprocess, 270.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zF3gnZMt_iUq8QxfdnY8-g_90.JPG: 480x640 (no detections), 275.5ms
Speed: 1.1ms preprocess, 275.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zF3gnZMt_iUq8QxfdnY8-g_180.JPG: 480x640 (no detections), 278.0ms
Speed: 1.1ms preprocess, 278.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zF3gnZMt_iUq8QxfdnY8-g_270.JPG: 480x640 (no detections), 275.4ms
Speed: 1.2ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zF3sjo7FUAZEfeoHaOfDMg_0.JPG: 480x640 (no detections), 281.9ms
Speed: 1.3ms preprocess, 281.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zF3sjo7FUAZEfeoHaOfDMg_90.JPG: 480x640 (no detections), 290.3ms
Speed: 1.2ms preprocess, 290.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zF3sjo7FUAZEfeoHaOfDMg_180.JPG: 480x640 (no detections), 286.3ms
Speed: 1.1ms preprocess, 286.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zF3sjo7FUAZEfeoHaOfDMg_270.JPG: 480x640 2 Wastes, 311.3ms
Speed: 1.0ms preprocess, 311.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zF78mEJzwU5D7xzmailHdA_0.JPG: 480x640 (no detections), 271.2ms
Speed: 1.2ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zF78mEJzwU5D7xzmailHdA_90.JPG: 480x640 (no detections), 272.5ms
Speed: 1.0ms preprocess, 272.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zF78mEJzwU5D7xzmailHdA_180.JPG: 480x640 (no detections), 271.5ms
Speed: 1.2ms preprocess, 271.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zF78mEJzwU5D7xzmailHdA_270.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFAnp9dIqcHS9oHa2qknwg_0.JPG: 480x640 (no detections), 278.9ms
Speed: 1.0ms preprocess, 278.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFAnp9dIqcHS9oHa2qknwg_90.JPG: 480x640 (no detections), 277.2ms
Speed: 1.4ms preprocess, 277.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFAnp9dIqcHS9oHa2qknwg_180.JPG: 480x640 (no detections), 273.9ms
Speed: 1.3ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFAnp9dIqcHS9oHa2qknwg_270.JPG: 480x640 (no detections), 272.3ms
Speed: 1.2ms preprocess, 272.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFCoTg6IlLE6nPFEG11_Jg_0.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFCoTg6IlLE6nPFEG11_Jg_90.JPG: 480x640 (no detections), 269.4ms
Speed: 1.1ms preprocess, 269.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFCoTg6IlLE6nPFEG11_Jg_180.JPG: 480x640 (no detections), 326.4ms
Speed: 1.0ms preprocess, 326.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFCoTg6IlLE6nPFEG11_Jg_270.JPG: 480x640 (no detections), 347.2ms
Speed: 1.2ms preprocess, 347.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFCqzqebrjE3L7eQQvICDA_0.JPG: 480x640 (no detections), 312.5ms
Speed: 1.3ms preprocess, 312.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFCqzqebrjE3L7eQQvICDA_90.JPG: 480x640 (no detections), 276.0ms
Speed: 1.1ms preprocess, 276.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFCqzqebrjE3L7eQQvICDA_180.JPG: 480x640 (no detections), 268.3ms
Speed: 1.0ms preprocess, 268.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFCqzqebrjE3L7eQQvICDA_270.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFE0byh7PaJpDkzZDGKEUg_0.JPG: 480x640 (no detections), 279.1ms
Speed: 1.0ms preprocess, 279.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFE0byh7PaJpDkzZDGKEUg_90.JPG: 480x640 (no detections), 270.4ms
Speed: 1.1ms preprocess, 270.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFE0byh7PaJpDkzZDGKEUg_180.JPG: 480x640 (no detections), 276.9ms
Speed: 1.0ms preprocess, 276.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFE0byh7PaJpDkzZDGKEUg_270.JPG: 480x640 (no detections), 270.3ms
Speed: 1.0ms preprocess, 270.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFGmnUsa8HdCHiBrJRCTSQ_0.JPG: 480x640 (no detections), 271.0ms
Speed: 1.1ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFGmnUsa8HdCHiBrJRCTSQ_90.JPG: 480x640 (no detections), 274.4ms
Speed: 1.5ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFGmnUsa8HdCHiBrJRCTSQ_180.JPG: 480x640 (no detections), 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFGmnUsa8HdCHiBrJRCTSQ_270.JPG: 480x640 (no detections), 270.5ms
Speed: 1.1ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFOQezS4VtgNWfG1aLKo2Q_0.JPG: 480x640 (no detections), 270.5ms
Speed: 1.0ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFOQezS4VtgNWfG1aLKo2Q_90.JPG: 480x640 (no detections), 271.0ms
Speed: 1.1ms preprocess, 271.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFOQezS4VtgNWfG1aLKo2Q_180.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFOQezS4VtgNWfG1aLKo2Q_270.JPG: 480x640 (no detections), 273.1ms
Speed: 1.0ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFTy-8Ede4IlTtEFYpN6bQ_0.JPG: 480x640 (no detections), 278.6ms
Speed: 1.3ms preprocess, 278.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFTy-8Ede4IlTtEFYpN6bQ_90.JPG: 480x640 (no detections), 265.7ms
Speed: 1.1ms preprocess, 265.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFTy-8Ede4IlTtEFYpN6bQ_180.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFTy-8Ede4IlTtEFYpN6bQ_270.JPG: 480x640 (no detections), 274.6ms
Speed: 1.1ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFUdxWZ5Icy9_HiDwgLlXA_0.JPG: 480x640 (no detections), 292.4ms
Speed: 1.1ms preprocess, 292.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFUdxWZ5Icy9_HiDwgLlXA_90.JPG: 480x640 (no detections), 276.7ms
Speed: 1.1ms preprocess, 276.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFUdxWZ5Icy9_HiDwgLlXA_180.JPG: 480x640 (no detections), 271.8ms
Speed: 1.0ms preprocess, 271.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFUdxWZ5Icy9_HiDwgLlXA_270.JPG: 480x640 (no detections), 270.8ms
Speed: 1.0ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFUzcGPBoLELMtQ5HHN4eA_0.JPG: 480x640 (no detections), 269.2ms
Speed: 1.1ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFUzcGPBoLELMtQ5HHN4eA_90.JPG: 480x640 (no detections), 272.4ms
Speed: 1.1ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFUzcGPBoLELMtQ5HHN4eA_180.JPG: 480x640 (no detections), 274.6ms
Speed: 1.1ms preprocess, 274.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFUzcGPBoLELMtQ5HHN4eA_270.JPG: 480x640 (no detections), 274.0ms
Speed: 1.0ms preprocess, 274.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFY9XvkRBzRx-MRlhals8Q_0.JPG: 480x640 (no detections), 276.4ms
Speed: 1.2ms preprocess, 276.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFY9XvkRBzRx-MRlhals8Q_90.JPG: 480x640 (no detections), 279.3ms

Speed: 1.0ms preprocess, 279.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFY9XvkRBzRx-MRlhals8Q_180.JPG: 480x640 (no detections), 272.7ms
Speed: 1.8ms preprocess, 272.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFY9XvkRBzRx-MRlhals8Q_270.JPG: 480x640 (no detections), 305.3ms
Speed: 1.0ms preprocess, 305.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFYo1RH16oVPP7cndesfMQ_0.JPG: 480x640 (no detections), 275.5ms
Speed: 1.2ms preprocess, 275.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFYo1RH16oVPP7cndesfMQ_90.JPG: 480x640 (no detections), 273.6ms
Speed: 1.1ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFYo1RH16oVPP7cndesfMQ_180.JPG: 480x640 (no detections), 269.5ms
Speed: 1.0ms preprocess, 269.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFYo1RH16oVPP7cndesfMQ_270.JPG: 480x640 (no detections), 273.9ms
Speed: 1.1ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFZtmcqjFTb0zBtX7cuAgw_0.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFZtmcqjFTb0zBtX7cuAgw_90.JPG: 480x640 (no detections), 270.6ms
Speed: 1.0ms preprocess, 270.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFZtmcqjFTb0zBtX7cuAgw_180.JPG: 480x640 (no detections), 276.7ms
Speed: 1.2ms preprocess, 276.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFZtmcqjFTb0zBtX7cuAgw_270.JPG: 480x640 (no detections), 270.3ms
Speed: 1.1ms preprocess, 270.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zF_fJL-CoiTSXqrVPE2zzA_0.JPG: 480x640 (no detections), 272.1ms
Speed: 1.1ms preprocess, 272.1ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zF_fJL-CoiTSXqrVPE2zzA_90.JPG: 480x640 (no detections), 277.6ms
Speed: 1.0ms preprocess, 277.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zF_fJL-CoiTSXqrVPE2zzA_180.JPG: 480x640 (no detections), 276.8ms
Speed: 1.1ms preprocess, 276.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zF_fJL-CoiTSXqrVPE2zzA_270.JPG: 480x640 (no detections), 273.4ms
Speed: 1.0ms preprocess, 273.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zF_v7yBdZajQil5ftVkdtg_0.JPG: 480x640 (no detections), 272.3ms
Speed: 1.0ms preprocess, 272.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zF_v7yBdZajQil5ftVkdtg_90.JPG: 480x640 (no detections), 268.6ms
Speed: 1.1ms preprocess, 268.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zF_v7yBdZajQil5ftVkdtg_180.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zF_v7yBdZajQil5ftVkdtg_270.JPG: 480x640 (no detections), 274.8ms
Speed: 1.1ms preprocess, 274.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFbZLB83NiDE_Rpuhh7Fzg_0.JPG: 480x640 (no detections), 266.3ms
Speed: 1.1ms preprocess, 266.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFbZLB83NiDE_Rpuhh7Fzg_90.JPG: 480x640 (no detections), 267.5ms
Speed: 1.0ms preprocess, 267.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFbZLB83NiDE_Rpuhh7Fzg_180.JPG: 480x640 (no detections), 274.5ms
Speed: 1.1ms preprocess, 274.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFbZLB83NiDE_Rpuhh7Fzg_270.JPG: 480x640 (no detections), 268.4ms
Speed: 1.0ms preprocess, 268.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFcZ79s-EIDhMFYGLBqXLQ_0.JPG: 480x640 (no detections), 270.8ms
Speed: 1.0ms preprocess, 270.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFcZ79s-EIDhMFYGLBqXLQ_90.JPG: 480x640 (no detections), 271.2ms
Speed: 1.0ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFcZ79s-EIDhMFYGLBqXLQ_180.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFcZ79s-EIDhMFYGLBqXLQ_270.JPG: 480x640 (no detections), 276.3ms
Speed: 1.1ms preprocess, 276.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFgkKBzCsVA1zgUQDMdxIA_0.JPG: 480x640 (no detections), 276.8ms
Speed: 1.1ms preprocess, 276.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFgkKBzCsVA1zgUQDMdxIA_90.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFgkKBzCsVA1zgUQDMdxIA_180.JPG: 480x640 (no detections), 270.7ms
Speed: 1.0ms preprocess, 270.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFgkKBzCsVA1zgUQDMdxIA_270.JPG: 480x640 (no detections), 275.5ms
Speed: 1.0ms preprocess, 275.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFiLjG4hVm1cMtbj3oVogA_0.JPG: 480x640 (no detections), 275.0ms
Speed: 1.1ms preprocess, 275.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFiLjG4hVm1cMtbj3oVogA_90.JPG: 480x640 (no detections), 269.2ms
Speed: 1.1ms preprocess, 269.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFiLjG4hVm1cMtbj3oVogA_180.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFiLjG4hVm1cMtbj3oVogA_270.JPG: 480x640 (no detections), 278.5ms
Speed: 1.1ms preprocess, 278.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFmRoVhih91rH1iNDM6tRg_0.JPG: 480x640 (no detections), 273.9ms
Speed: 1.0ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFmRoVhih91rH1iNDM6tRg_90.JPG: 480x640 (no detections), 289.3ms
Speed: 1.0ms preprocess, 289.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFmRoVhih91rH1iNDM6tRg_180.JPG: 480x640 (no detections), 283.6ms
Speed: 1.0ms preprocess, 283.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFmRoVhih91rH1iNDM6tRg_270.JPG: 480x640 (no detections), 277.8ms
Speed: 1.1ms preprocess, 277.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFmsRIM4A_zsCc7hRsKLMQ_0.JPG: 480x640 (no detections), 273.4ms
Speed: 1.1ms preprocess, 273.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFmsRIM4A_zsCc7hRsKLMQ_90.JPG: 480x640 (no detections), 272.3ms
Speed: 1.0ms preprocess, 272.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFmsRIM4A_zsCc7hRsKLMQ_180.JPG: 480x640 (no detections), 276.5ms
Speed: 1.2ms preprocess, 276.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFmsRIM4A_zsCc7hRsKLMQ_270.JPG: 480x640 (no detections), 277.5ms
Speed: 1.2ms preprocess, 277.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFtXXVUvm9mgsyfn-yh3qg_0.JPG: 480x640 (no detections), 273.2ms
Speed: 1.0ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFtXXVUvm9mgsyfn-yh3qg_90.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFtXXVUvm9mgsyfn-yh3qg_180.JPG: 480x640 (no detections), 269.9ms
Speed: 1.7ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFtXXVUvm9mgsyfn-yh3qg_270.JPG: 480x640 (no detections), 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFttfxF_tKVdJOB7M007vQ_0.JPG: 480x640 (no detections), 271.0ms
Speed: 1.0ms preprocess, 271.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFttfxF_tKVdJOB7M007vQ_90.JPG: 480x640 (no detections), 268.1ms
Speed: 1.1ms preprocess, 268.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFttfxF_tKVdJOB7M007vQ_180.JPG: 480x640 (no detections), 270.5ms
Speed: 1.0ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFttfxF_tKVdJOB7M007vQ_270.JPG: 480x640 (no detections), 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFtyqoADkp5-TIPISnSoCw_0.JPG: 480x640 (no detections), 271.0ms
Speed: 1.1ms preprocess, 271.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFtyqoADkp5-TIPISnSoCw_90.JPG: 480x640 (no detections), 270.4ms
Speed: 1.0ms preprocess, 270.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFtyqoADkp5-TIPISnSoCw_180.JPG: 480x640 (no detections), 273.9ms
Speed: 1.1ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zFtyqoADkp5-TIPISnSoCw_270.JPG: 480x640 (no detections), 273.6ms
Speed: 1.0ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zG4htFsIMa4zmeoJGPO67w_0.JPG: 480x640 (no detections), 274.0ms
Speed: 1.0ms preprocess, 274.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zG4htFsIMa4zmeoJGPO67w_90.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zG4htFsIMa4zmeoJGPO67w_180.JPG: 480x640 (no detections), 276.3ms
Speed: 1.1ms preprocess, 276.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zG4htFsIMa4zmeoJGPO67w_270.JPG: 480x640 (no detections), 270.4ms
Speed: 1.1ms preprocess, 270.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zG5CG2E7KGv-AOJ2izboNA_0.JPG: 480x640 (no detections), 269.3ms
Speed: 1.1ms preprocess, 269.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zG5CG2E7KGv-AOJ2izboNA_90.JPG: 480x640 (no detections), 270.3ms
Speed: 1.0ms preprocess, 270.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zG5CG2E7KGv-AOJ2izboNA_180.JPG: 480x640 (no detections), 271.5ms
Speed: 1.1ms preprocess, 271.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zG5CG2E7KGv-AOJ2izboNA_270.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zG7CbBOnIMkOLzc34EjBIw_0.JPG: 480x640 (no detections), 269.4ms
Speed: 1.1ms preprocess, 269.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zG7CbBOnIMkOLzc34EjBIw_90.JPG: 480x640 1 Waste, 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zG7CbBOnIMkOLzc34EjBIw_180.JPG: 480x640 (no detections), 276.0ms
Speed: 1.1ms preprocess, 276.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zG7CbBOnIMkOLzc34EjBIw_270.JPG: 480x640 (no detections), 271.8ms
Speed: 1.0ms preprocess, 271.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zG9ofiZYw4knXTfj0FWaXQ_0.JPG: 480x640 (no detections), 273.8ms

Speed: 1.1ms preprocess, 273.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zG9ofiZYw4knXTfj0FWaXQ_90.JPG: 480x640 (no detections), 269.1ms
Speed: 1.2ms preprocess, 269.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zG9ofiZYw4knXTfj0FWaXQ_180.JPG: 480x640 (no detections), 334.4ms
Speed: 1.5ms preprocess, 334.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zG9ofiZYw4knXTfj0FWaXQ_270.JPG: 480x640 (no detections), 367.5ms
Speed: 1.4ms preprocess, 367.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGCHVQS9hNM0hZmFB1lLjw_0.JPG: 480x640 (no detections), 305.9ms
Speed: 1.3ms preprocess, 305.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGCHVQS9hNM0hZmFB1lLjw_90.JPG: 480x640 (no detections), 285.1ms
Speed: 1.2ms preprocess, 285.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGCHVQS9hNM0hZmFB1lLjw_180.JPG: 480x640 (no detections), 290.6ms
Speed: 1.1ms preprocess, 290.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGCHVQS9hNM0hZmFB1lLjw_270.JPG: 480x640 (no detections), 303.1ms
Speed: 1.1ms preprocess, 303.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGCLwRhRv_rLQvmDaaOkBg_0.JPG: 480x640 (no detections), 277.8ms
Speed: 1.4ms preprocess, 277.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGCLwRhRv_rLQvmDaaOkBg_90.JPG: 480x640 (no detections), 360.0ms
Speed: 1.1ms preprocess, 360.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGCLwRhRv_rLQvmDaaOkBg_180.JPG: 480x640 (no detections), 350.4ms
Speed: 1.3ms preprocess, 350.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGCLwRhRv_rLQvmDaaOkBg_270.JPG: 480x640 (no detections), 372.8ms
Speed: 1.3ms preprocess, 372.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGFjinvsONVntHNfNCUHeg_0.JPG: 480x640 (no detections), 289.4ms
Speed: 1.1ms preprocess, 289.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGFjinvsONVntHNfNCUHeg_90.JPG: 480x640 (no detections), 289.5ms
Speed: 1.1ms preprocess, 289.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGFjinvsONVntHNfNCUHeg_180.JPG: 480x640 (no detections), 299.3ms
Speed: 1.0ms preprocess, 299.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGFjinvsONVntHNfNCUHeg_270.JPG: 480x640 (no detections), 350.0ms
Speed: 1.4ms preprocess, 350.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGJ15pcIukte-_efAZYZAQ_0.JPG: 480x640 (no detections), 283.3ms
Speed: 1.3ms preprocess, 283.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGJ15pcIukte-_efAZYZAQ_90.JPG: 480x640 (no detections), 293.4ms
Speed: 1.2ms preprocess, 293.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGJ15pcIukte-_efAZYZAQ_180.JPG: 480x640 (no detections), 297.7ms
Speed: 1.0ms preprocess, 297.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGJ15pcIukte-_efAZYZAQ_270.JPG: 480x640 (no detections), 287.7ms
Speed: 1.6ms preprocess, 287.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGKb_2NCBUznefZpuGi-xA_0.JPG: 480x640 (no detections), 321.9ms
Speed: 1.7ms preprocess, 321.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGKb_2NCBUznefZpuGi-xA_90.JPG: 480x640 (no detections), 320.6ms
Speed: 1.1ms preprocess, 320.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGKb_2NCBUznefZpuGi-xA_180.JPG: 480x640 (no detections), 322.8ms
Speed: 1.1ms preprocess, 322.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGKb_2NCBUznefZpuGi-xA_270.JPG: 480x640 (no detections), 303.2ms
Speed: 1.4ms preprocess, 303.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGLxy7oazjStawPPy652OQ_0.JPG: 480x640 (no detections), 284.6ms
Speed: 1.1ms preprocess, 284.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGLxy7oazjStawPPy652OQ_90.JPG: 480x640 (no detections), 297.0ms
Speed: 1.4ms preprocess, 297.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGLxy7oazjStawPPy652OQ_180.JPG: 480x640 (no detections), 299.5ms
Speed: 1.9ms preprocess, 299.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGLxy7oazjStawPPy652OQ_270.JPG: 480x640 (no detections), 284.9ms
Speed: 1.3ms preprocess, 284.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGOQKo78aLy6rq2bkjVWdw_0.JPG: 480x640 (no detections), 306.6ms
Speed: 1.5ms preprocess, 306.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGOQKo78aLy6rq2bkjVWdw_90.JPG: 480x640 (no detections), 282.7ms
Speed: 1.4ms preprocess, 282.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGOQKo78aLy6rq2bkjVWdw_180.JPG: 480x640 (no detections), 310.8ms
Speed: 1.1ms preprocess, 310.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGOQKo78aLy6rq2bkjVWdw_270.JPG: 480x640 (no detections), 303.4ms
Speed: 1.1ms preprocess, 303.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGOoaOwun8XGzFWnxBCLXA_0.JPG: 480x640 (no detections), 309.5ms
Speed: 1.3ms preprocess, 309.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGOoaOwun8XGzFWnxBCLXA_90.JPG: 480x640 (no detections), 289.4ms
Speed: 1.1ms preprocess, 289.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGOoaOwun8XGzFWnxBCLXA_180.JPG: 480x640 (no detections), 294.7ms
Speed: 1.2ms preprocess, 294.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGOoaOwun8XGzFWnxBCLXA_270.JPG: 480x640 (no detections), 342.3ms
Speed: 1.0ms preprocess, 342.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGOtx64WGbzbgIAlAR0BWQ_0.JPG: 480x640 (no detections), 289.0ms
Speed: 1.2ms preprocess, 289.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGOtx64WGbzbgIAlAR0BWQ_90.JPG: 480x640 (no detections), 287.3ms
Speed: 1.2ms preprocess, 287.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGOtx64WGbzbgIAlAR0BWQ_180.JPG: 480x640 (no detections), 275.9ms
Speed: 1.0ms preprocess, 275.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGOtx64WGbzbgIAlAR0BWQ_270.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGPd4ahFdQ1enXVrK0o5gQ_0.JPG: 480x640 (no detections), 275.5ms
Speed: 1.0ms preprocess, 275.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGPd4ahFdQ1enXVrK0o5gQ_90.JPG: 480x640 (no detections), 270.4ms
Speed: 1.1ms preprocess, 270.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGPd4ahFdQ1enXVrK0o5gQ_180.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGPd4ahFdQ1enXVrK0o5gQ_270.JPG: 480x640 (no detections), 271.6ms
Speed: 1.0ms preprocess, 271.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGRLiddZqp7nFn2vITspaA_0.JPG: 480x640 (no detections), 271.5ms
Speed: 1.1ms preprocess, 271.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGRLiddZqp7nFn2vITspaA_90.JPG: 480x640 (no detections), 288.0ms
Speed: 1.1ms preprocess, 288.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGRLiddZqp7nFn2vITspaA_180.JPG: 480x640 (no detections), 296.8ms
Speed: 1.1ms preprocess, 296.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGRLiddZqp7nFn2vITspaA_270.JPG: 480x640 (no detections), 298.2ms
Speed: 1.2ms preprocess, 298.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGSqOJbM9TqWQj1hpvltlQ_0.JPG: 480x640 (no detections), 329.1ms
Speed: 1.3ms preprocess, 329.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGSqOJbM9TqWQj1hpvltlQ_90.JPG: 480x640 (no detections), 298.3ms
Speed: 2.0ms preprocess, 298.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGSqOJbM9TqWQj1hpvltlQ_180.JPG: 480x640 (no detections), 291.8ms
Speed: 1.1ms preprocess, 291.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGSqOJbM9TqWQj1hpvltlQ_270.JPG: 480x640 (no detections), 272.5ms
Speed: 1.0ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGXvQoZgWZWF7HOynd4dmA_0.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGXvQoZgWZWF7HOynd4dmA_90.JPG: 480x640 (no detections), 300.4ms
Speed: 1.0ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGXvQoZgWZWF7HOynd4dmA_180.JPG: 480x640 (no detections), 276.3ms
Speed: 1.2ms preprocess, 276.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGXvQoZgWZWF7HOynd4dmA_270.JPG: 480x640 (no detections), 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGZEIXyOeHXtgcKJydZNfA_0.JPG: 480x640 (no detections), 287.1ms
Speed: 1.1ms preprocess, 287.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGZEIXyOeHXtgcKJydZNfA_90.JPG: 480x640 (no detections), 269.8ms
Speed: 1.1ms preprocess, 269.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGZEIXyOeHXtgcKJydZNfA_180.JPG: 480x640 (no detections), 273.6ms
Speed: 1.0ms preprocess, 273.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGZEIXyOeHXtgcKJydZNfA_270.JPG: 480x640 (no detections), 302.4ms
Speed: 1.1ms preprocess, 302.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zG_7XbyLqOeZckLkfp5-Dw_0.JPG: 480x640 (no detections), 278.0ms
Speed: 1.1ms preprocess, 278.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zG_7XbyLqOeZckLkfp5-Dw_90.JPG: 480x640 (no detections), 274.0ms
Speed: 1.1ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zG_7XbyLqOeZckLkfp5-Dw_180.JPG: 480x640 (no detections), 296.8ms
Speed: 1.1ms preprocess, 296.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zG_7XbyLqOeZckLkfp5-Dw_270.JPG: 480x640 (no detections), 274.5ms
Speed: 1.1ms preprocess, 274.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGcowvL5wxGhRzm5eUsrjQ_0.JPG: 480x640 (no detections), 272.3ms
Speed: 1.0ms preprocess, 272.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGcowvL5wxGhRzm5eUsrjQ_90.JPG: 480x640 (no detections), 273.7ms
Speed: 1.2ms preprocess, 273.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGcowvL5wxGhRzm5eUsrjQ_180.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGcowvL5wxGhRzm5eUsrjQ_270.JPG: 480x640 (no detections), 280.2ms

Speed: 1.0ms preprocess, 280.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGdEIBSRiOasuV8UkzFStw_0.JPG: 480x640 1 Waste, 272.3ms
Speed: 1.2ms preprocess, 272.3ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGdEIBSRiOasuV8UkzFStw_90.JPG: 480x640 (no detections), 295.1ms
Speed: 1.0ms preprocess, 295.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGdEIBSRiOasuV8UkzFStw_180.JPG: 480x640 (no detections), 287.7ms
Speed: 1.0ms preprocess, 287.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGdEIBSRiOasuV8UkzFStw_270.JPG: 480x640 (no detections), 288.9ms
Speed: 1.1ms preprocess, 288.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGigEQ3UQPYiaVXJc0K8JQ_0.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGigEQ3UQPYiaVXJc0K8JQ_90.JPG: 480x640 (no detections), 274.0ms
Speed: 1.1ms preprocess, 274.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGigEQ3UQPYiaVXJc0K8JQ_180.JPG: 480x640 (no detections), 273.9ms
Speed: 1.2ms preprocess, 273.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGigEQ3UQPYiaVXJc0K8JQ_270.JPG: 480x640 (no detections), 277.2ms
Speed: 1.0ms preprocess, 277.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGq0QWEQ8Hoia7-ETmpBLg_0.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGq0QWEQ8Hoia7-ETmpBLg_90.JPG: 480x640 1 Waste, 272.4ms
Speed: 1.2ms preprocess, 272.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGq0QWEQ8Hoia7-ETmpBLg_180.JPG: 480x640 (no detections), 282.8ms
Speed: 1.2ms preprocess, 282.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGq0QWEQ8Hoia7-ETmpBLg_270.JPG: 480x640 (no detections), 356.4ms
Speed: 1.0ms preprocess, 356.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGqGhe1CgGlaFhIITfE30w_0.JPG: 480x640 (no detections), 323.9ms
Speed: 1.1ms preprocess, 323.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGqGhe1CgGlaFhIITfE30w_90.JPG: 480x640 (no detections), 285.6ms
Speed: 1.2ms preprocess, 285.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGqGhe1CgGlaFhIITfE30w_180.JPG: 480x640 (no detections), 293.6ms
Speed: 1.2ms preprocess, 293.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGqGhe1CgGlaFhIITfE30w_270.JPG: 480x640 (no detections), 294.4ms
Speed: 1.1ms preprocess, 294.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGqgjkljEsWa7VJkN2w5lA_0.JPG: 480x640 (no detections), 320.6ms
Speed: 1.4ms preprocess, 320.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGqgjkljEsWa7VJkN2w5lA_90.JPG: 480x640 (no detections), 278.8ms
Speed: 1.1ms preprocess, 278.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGqgjkljEsWa7VJkN2w5lA_180.JPG: 480x640 (no detections), 274.7ms
Speed: 1.0ms preprocess, 274.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGqgjkljEsWa7VJkN2w5lA_270.JPG: 480x640 (no detections), 273.6ms
Speed: 1.0ms preprocess, 273.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGsLrfz6TJf7gTjMC3GDLg_0.JPG: 480x640 (no detections), 280.6ms
Speed: 1.0ms preprocess, 280.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGsLrfz6TJf7gTjMC3GDLg_90.JPG: 480x640 (no detections), 277.5ms
Speed: 1.0ms preprocess, 277.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGsLrfz6TJf7gTjMC3GDLg_180.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGsLrfz6TJf7gTjMC3GDLg_270.JPG: 480x640 (no detections), 272.5ms
Speed: 1.1ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGtIz48dckU6d1bduns4Bw_0.JPG: 480x640 (no detections), 269.4ms
Speed: 1.1ms preprocess, 269.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGtIz48dckU6d1bduns4Bw_90.JPG: 480x640 (no detections), 274.8ms
Speed: 1.0ms preprocess, 274.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGtIz48dckU6d1bduns4Bw_180.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGtIz48dckU6d1bduns4Bw_270.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGxMTlyk4yk9RGOz1IU1vQ_0.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGxMTlyk4yk9RGOz1IU1vQ_90.JPG: 480x640 (no detections), 273.8ms
Speed: 1.0ms preprocess, 273.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGxMTlyk4yk9RGOz1IU1vQ_180.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zGxMTlyk4yk9RGOz1IU1vQ_270.JPG: 480x640 (no detections), 269.0ms
Speed: 1.0ms preprocess, 269.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zH1IV449LU0vp5hSJHwyDQ_0.JPG: 480x640 (no detections), 274.8ms
Speed: 1.2ms preprocess, 274.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zH1IV449LU0vp5hSJHwyDQ_90.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zH1IV449LU0vp5hSJHwyDQ_180.JPG: 480x640 (no detections), 278.2ms
Speed: 1.0ms preprocess, 278.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zH1IV449LU0vp5hSJHwyDQ_270.JPG: 480x640 (no detections), 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zH2ODSYVPoJ1DaLSxrpfcQ_0.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zH2ODSYVPoJ1DaLSxrpfcQ_90.JPG: 480x640 (no detections), 289.9ms
Speed: 1.8ms preprocess, 289.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zH2ODSYVPoJ1DaLSxrpfcQ_180.JPG: 480x640 (no detections), 310.7ms
Speed: 1.1ms preprocess, 310.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zH2ODSYVPoJ1DaLSxrpfcQ_270.JPG: 480x640 (no detections), 288.1ms
Speed: 1.2ms preprocess, 288.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zH2e2s6QnVh_gI1sp3CE7g_0.JPG: 480x640 (no detections), 291.8ms
Speed: 1.1ms preprocess, 291.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zH2e2s6QnVh_gI1sp3CE7g_90.JPG: 480x640 (no detections), 296.1ms
Speed: 1.1ms preprocess, 296.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zH2e2s6QnVh_gI1sp3CE7g_180.JPG: 480x640 (no detections), 275.6ms
Speed: 1.1ms preprocess, 275.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zH2e2s6QnVh_gI1sp3CE7g_270.JPG: 480x640 1 Waste, 272.5ms
Speed: 1.1ms preprocess, 272.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zH4iYG1fgwg6n2Rskn9nkg_0.JPG: 480x640 (no detections), 296.2ms
Speed: 1.2ms preprocess, 296.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zH4iYG1fgwg6n2Rskn9nkg_90.JPG: 480x640 (no detections), 289.3ms
Speed: 1.1ms preprocess, 289.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zH4iYG1fgwg6n2Rskn9nkg_180.JPG: 480x640 (no detections), 278.0ms
Speed: 1.3ms preprocess, 278.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zH4iYG1fgwg6n2Rskn9nkg_270.JPG: 480x640 (no detections), 291.3ms
Speed: 1.1ms preprocess, 291.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zH5_y4Y4OQTzloGZm-W1zQ_0.JPG: 480x640 (no detections), 272.9ms
Speed: 1.0ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zH5_y4Y4OQTzloGZm-W1zQ_90.JPG: 480x640 (no detections), 292.5ms
Speed: 1.1ms preprocess, 292.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zH5_y4Y4OQTzloGZm-W1zQ_180.JPG: 480x640 (no detections), 271.9ms
Speed: 1.0ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zH5_y4Y4OQTzloGZm-W1zQ_270.JPG: 480x640 (no detections), 269.7ms
Speed: 1.0ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zH71ntSSQT1J0SuiNUkE8w_0.JPG: 480x640 (no detections), 270.9ms
Speed: 1.1ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zH71ntSSQT1J0SuiNUkE8w_90.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zH71ntSSQT1J0SuiNUkE8w_180.JPG: 480x640 (no detections), 270.5ms
Speed: 1.1ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zH71ntSSQT1J0SuiNUkE8w_270.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zH8nw1bxhR6QR21bUFMU5w_0.JPG: 480x640 (no detections), 274.5ms
Speed: 1.1ms preprocess, 274.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zH8nw1bxhR6QR21bUFMU5w_90.JPG: 480x640 (no detections), 270.9ms
Speed: 1.2ms preprocess, 270.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zH8nw1bxhR6QR21bUFMU5w_180.JPG: 480x640 (no detections), 280.9ms
Speed: 1.1ms preprocess, 280.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zH8nw1bxhR6QR21bUFMU5w_270.JPG: 480x640 (no detections), 269.2ms
Speed: 1.1ms preprocess, 269.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zH9Tc1BP6gfwUoSLSoXecQ_0.JPG: 480x640 (no detections), 270.5ms
Speed: 1.1ms preprocess, 270.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zH9Tc1BP6gfwUoSLSoXecQ_90.JPG: 480x640 (no detections), 274.7ms
Speed: 1.1ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zH9Tc1BP6gfwUoSLSoXecQ_180.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zH9Tc1BP6gfwUoSLSoXecQ_270.JPG: 480x640 (no detections), 268.9ms
Speed: 1.2ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHEFEUfi_Ci9hkT9McTTuQ_0.JPG: 480x640 (no detections), 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHEFEUfi_Ci9hkT9McTTuQ_90.JPG: 480x640 (no detections), 270.5ms
Speed: 1.0ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHEFEUfi_Ci9hkT9McTTuQ_180.JPG: 480x640 (no detections), 271.2ms

Speed: 1.2ms preprocess, 271.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHEFEUfi_Ci9hkT9McTTuQ_270.JPG: 480x640 (no detections), 272.7ms
Speed: 1.0ms preprocess, 272.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHHRRpiJJZlsjgCdkOyrPQ_0.JPG: 480x640 (no detections), 272.4ms
Speed: 1.0ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHHRRpiJJZlsjgCdkOyrPQ_90.JPG: 480x640 (no detections), 274.9ms
Speed: 1.1ms preprocess, 274.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHHRRpiJJZlsjgCdkOyrPQ_180.JPG: 480x640 (no detections), 273.9ms
Speed: 1.1ms preprocess, 273.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHHRRpiJJZlsjgCdkOyrPQ_270.JPG: 480x640 (no detections), 274.4ms
Speed: 1.6ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHIjDFcwo52OrYk8XghUiQ_0.JPG: 480x640 (no detections), 282.8ms
Speed: 1.1ms preprocess, 282.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHIjDFcwo52OrYk8XghUiQ_90.JPG: 480x640 (no detections), 275.5ms
Speed: 1.1ms preprocess, 275.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHIjDFcwo52OrYk8XghUiQ_180.JPG: 480x640 (no detections), 278.6ms
Speed: 1.2ms preprocess, 278.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHIjDFcwo52OrYk8XghUiQ_270.JPG: 480x640 (no detections), 271.5ms
Speed: 1.0ms preprocess, 271.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHJ2Gy8A3VVMCAPxy4I4aA_0.JPG: 480x640 (no detections), 278.2ms
Speed: 1.1ms preprocess, 278.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHJ2Gy8A3VVMCAPxy4I4aA_90.JPG: 480x640 (no detections), 274.2ms
Speed: 1.1ms preprocess, 274.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHJ2Gy8A3VVMCAPxy4I4aA_180.JPG: 480x640 (no detections), 268.6ms
Speed: 1.1ms preprocess, 268.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHJ2Gy8A3VVMCAPxy4I4aA_270.JPG: 480x640 (no detections), 273.4ms
Speed: 1.0ms preprocess, 273.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHNrqT7RaqmO6V3X6lkDDw_0.JPG: 480x640 (no detections), 275.9ms
Speed: 1.2ms preprocess, 275.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHNrqT7RaqmO6V3X6lkDDw_90.JPG: 480x640 (no detections), 278.3ms
Speed: 1.1ms preprocess, 278.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHNrqT7RaqmO6V3X6lkDDw_180.JPG: 480x640 (no detections), 274.7ms
Speed: 1.2ms preprocess, 274.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHNrqT7RaqmO6V3X6lkDDw_270.JPG: 480x640 (no detections), 271.9ms
Speed: 1.0ms preprocess, 271.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHOoRJptxRwPlBeaLiAuYA_0.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHOoRJptxRwPlBeaLiAuYA_90.JPG: 480x640 (no detections), 274.8ms
Speed: 1.0ms preprocess, 274.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHOoRJptxRwPlBeaLiAuYA_180.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHOoRJptxRwPlBeaLiAuYA_270.JPG: 480x640 (no detections), 274.2ms
Speed: 1.1ms preprocess, 274.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHQCCR46lrjIMeFSj9QqaQ_0.JPG: 480x640 (no detections), 276.6ms
Speed: 1.1ms preprocess, 276.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHQCCR46lrjIMeFSj9QqaQ_90.JPG: 480x640 (no detections), 275.3ms
Speed: 1.0ms preprocess, 275.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHQCCR46lrjIMeFSj9QqaQ_180.JPG: 480x640 (no detections), 268.4ms
Speed: 1.1ms preprocess, 268.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHQCCR46lrjIMeFSj9QqaQ_270.JPG: 480x640 (no detections), 414.6ms
Speed: 1.1ms preprocess, 414.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHWpV2Kkb8fH9or-vyhieQ_0.JPG: 480x640 (no detections), 269.5ms
Speed: 1.1ms preprocess, 269.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHWpV2Kkb8fH9or-vyhieQ_90.JPG: 480x640 (no detections), 278.5ms
Speed: 1.1ms preprocess, 278.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHWpV2Kkb8fH9or-vyhieQ_180.JPG: 480x640 (no detections), 273.4ms
Speed: 1.0ms preprocess, 273.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHWpV2Kkb8fH9or-vyhieQ_270.JPG: 480x640 (no detections), 275.6ms
Speed: 1.1ms preprocess, 275.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHYrElWqgpVnOPJpAmBB9w_0.JPG: 480x640 (no detections), 273.2ms
Speed: 1.1ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHYrElWqgpVnOPJpAmBB9w_90.JPG: 480x640 (no detections), 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHYrElWqgpVnOPJpAmBB9w_180.JPG: 480x640 (no detections), 269.4ms
Speed: 1.0ms preprocess, 269.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHYrElWqgpVnOPJpAmBB9w_270.JPG: 480x640 (no detections), 268.1ms
Speed: 1.0ms preprocess, 268.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHYrHXXuEu53aEYz7GrLCg_0.JPG: 480x640 1 Waste, 270.3ms
Speed: 1.1ms preprocess, 270.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHYrHXXuEu53aEYz7GrLCg_90.JPG: 480x640 (no detections), 272.9ms
Speed: 1.0ms preprocess, 272.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHYrHXXuEu53aEYz7GrLCg_180.JPG: 480x640 (no detections), 274.2ms
Speed: 1.0ms preprocess, 274.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHYrHXXuEu53aEYz7GrLCg_270.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zH_clGdCf_0MPz6QRwcLyA_0.JPG: 480x640 (no detections), 272.2ms
Speed: 1.3ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zH_clGdCf_0MPz6QRwcLyA_90.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zH_clGdCf_0MPz6QRwcLyA_180.JPG: 480x640 (no detections), 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zH_clGdCf_0MPz6QRwcLyA_270.JPG: 480x640 (no detections), 284.6ms
Speed: 1.1ms preprocess, 284.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zH_jiUpZm72Ft3fqfGSXwg_0.JPG: 480x640 (no detections), 271.0ms
Speed: 1.0ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zH_jiUpZm72Ft3fqfGSXwg_90.JPG: 480x640 (no detections), 272.9ms
Speed: 1.2ms preprocess, 272.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zH_jiUpZm72Ft3fqfGSXwg_180.JPG: 480x640 1 Waste, 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zH_jiUpZm72Ft3fqfGSXwg_270.JPG: 480x640 (no detections), 279.2ms
Speed: 1.0ms preprocess, 279.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHb1WcdmqMStqIHJPjSzlg_0.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHb1WcdmqMStqIHJPjSzlg_90.JPG: 480x640 (no detections), 274.8ms
Speed: 1.0ms preprocess, 274.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHb1WcdmqMStqIHJPjSzlg_180.JPG: 480x640 (no detections), 270.6ms
Speed: 1.0ms preprocess, 270.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHb1WcdmqMStqIHJPjSzlg_270.JPG: 480x640 (no detections), 278.6ms
Speed: 1.3ms preprocess, 278.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHc6gDiev86uyGuLJNMvbw_0.JPG: 480x640 (no detections), 269.1ms
Speed: 1.1ms preprocess, 269.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHc6gDiev86uyGuLJNMvbw_90.JPG: 480x640 3 Wastes, 272.5ms
Speed: 1.1ms preprocess, 272.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHc6gDiev86uyGuLJNMvbw_180.JPG: 480x640 1 Waste, 275.3ms
Speed: 0.9ms preprocess, 275.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHc6gDiev86uyGuLJNMvbw_270.JPG: 480x640 (no detections), 277.0ms
Speed: 1.2ms preprocess, 277.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHgVVxC3YE53xRbhTd1teg_0.JPG: 480x640 (no detections), 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHgVVxC3YE53xRbhTd1teg_90.JPG: 480x640 (no detections), 269.8ms
Speed: 1.1ms preprocess, 269.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHgVVxC3YE53xRbhTd1teg_180.JPG: 480x640 (no detections), 272.2ms
Speed: 1.0ms preprocess, 272.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHgVVxC3YE53xRbhTd1teg_270.JPG: 480x640 (no detections), 275.7ms
Speed: 1.0ms preprocess, 275.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHjAPf0L23-DQhjp3X2N4g_0.JPG: 480x640 (no detections), 270.3ms
Speed: 1.1ms preprocess, 270.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHjAPf0L23-DQhjp3X2N4g_90.JPG: 480x640 (no detections), 274.7ms
Speed: 1.1ms preprocess, 274.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHjAPf0L23-DQhjp3X2N4g_180.JPG: 480x640 (no detections), 274.5ms
Speed: 1.2ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHjAPf0L23-DQhjp3X2N4g_270.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHk5pmrg_equtPX4j3lESg_0.JPG: 480x640 (no detections), 276.7ms
Speed: 1.0ms preprocess, 276.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHk5pmrg_equtPX4j3lESg_90.JPG: 480x640 (no detections), 294.3ms
Speed: 1.2ms preprocess, 294.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHk5pmrg_equtPX4j3lESg_180.JPG: 480x640 (no detections), 270.2ms
Speed: 1.0ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHk5pmrg_equtPX4j3lESg_270.JPG: 480x640 (no detections), 275.2ms
Speed: 1.1ms preprocess, 275.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHnHQ2utMM5SC_rO-XfMRQ_0.JPG: 480x640 (no detections), 267.9ms
Speed: 1.0ms preprocess, 267.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHnHQ2utMM5SC_rO-XfMRQ_90.JPG: 480x640 (no detections), 267.1ms

Speed: 1.1ms preprocess, 267.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHnHQ2utMM5SC_rO-XfMRQ_180.JPG: 480x640 (no detections), 271.4ms
Speed: 1.0ms preprocess, 271.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHnHQ2utMM5SC_rO-XfMRQ_270.JPG: 480x640 1 Waste, 276.4ms
Speed: 1.1ms preprocess, 276.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHnwN8KPAoHD1ObmXbtZbA_0.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHnwN8KPAoHD1ObmXbtZbA_90.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHnwN8KPAoHD1ObmXbtZbA_180.JPG: 480x640 (no detections), 265.8ms
Speed: 1.0ms preprocess, 265.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHnwN8KPAoHD1ObmXbtZbA_270.JPG: 480x640 1 Waste, 272.9ms
Speed: 1.0ms preprocess, 272.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHpx89yAbp9rkRBK6Hg7VA_0.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHpx89yAbp9rkRBK6Hg7VA_90.JPG: 480x640 (no detections), 275.1ms
Speed: 1.0ms preprocess, 275.1ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHpx89yAbp9rkRBK6Hg7VA_180.JPG: 480x640 (no detections), 277.4ms
Speed: 1.0ms preprocess, 277.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHpx89yAbp9rkRBK6Hg7VA_270.JPG: 480x640 (no detections), 275.4ms
Speed: 1.1ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHqmoQrTmbzfO3XrUZ9Gag_0.JPG: 480x640 (no detections), 279.0ms
Speed: 1.1ms preprocess, 279.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHqmoQrTmbzfO3XrUZ9Gag_90.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHqmoQrTmbzfO3XrUZ9Gag_180.JPG: 480x640 (no detections), 271.0ms
Speed: 1.3ms preprocess, 271.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHqmoQrTmbzfO3XrUZ9Gag_270.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHrGMCuK9C-VGQVycmwf9w_0.JPG: 480x640 (no detections), 269.1ms
Speed: 1.1ms preprocess, 269.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHrGMCuK9C-VGQVycmwf9w_90.JPG: 480x640 (no detections), 274.2ms
Speed: 1.1ms preprocess, 274.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHrGMCuK9C-VGQVycmwf9w_180.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHrGMCuK9C-VGQVycmwf9w_270.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHsusAOayUbqI1fpjzcx2g_0.JPG: 480x640 (no detections), 273.6ms
Speed: 1.0ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHsusAOayUbqI1fpjzcx2g_90.JPG: 480x640 (no detections), 270.8ms
Speed: 1.0ms preprocess, 270.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHsusAOayUbqI1fpjzcx2g_180.JPG: 480x640 (no detections), 277.7ms
Speed: 1.2ms preprocess, 277.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHsusAOayUbqI1fpjzcx2g_270.JPG: 480x640 (no detections), 278.8ms
Speed: 1.0ms preprocess, 278.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHsvg74-rpOlj3WIWvRTZg_0.JPG: 480x640 (no detections), 273.9ms
Speed: 1.2ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHsvg74-rpOlj3WIWvRTZg_90.JPG: 480x640 2 Wastes, 267.9ms
Speed: 1.0ms preprocess, 267.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHsvg74-rpOlj3WIWvRTZg_180.JPG: 480x640 (no detections), 272.5ms
Speed: 1.2ms preprocess, 272.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHsvg74-rpOlj3WIWvRTZg_270.JPG: 480x640 (no detections), 275.4ms
Speed: 1.0ms preprocess, 275.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHt4X4GNlekJo34rtjbjog_0.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHt4X4GNlekJo34rtjbjog_90.JPG: 480x640 (no detections), 274.4ms
Speed: 1.9ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHt4X4GNlekJo34rtjbjog_180.JPG: 480x640 (no detections), 271.1ms
Speed: 1.0ms preprocess, 271.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHt4X4GNlekJo34rtjbjog_270.JPG: 480x640 (no detections), 278.1ms
Speed: 1.0ms preprocess, 278.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHtqccDx2YudT8W76zswbA_0.JPG: 480x640 (no detections), 268.3ms
Speed: 1.1ms preprocess, 268.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHtqccDx2YudT8W76zswbA_90.JPG: 480x640 (no detections), 275.3ms
Speed: 1.1ms preprocess, 275.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHtqccDx2YudT8W76zswbA_180.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHtqccDx2YudT8W76zswbA_270.JPG: 480x640 (no detections), 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHuxR9xvQ--3Mcw9UlLcHg_0.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHuxR9xvQ--3Mcw9UlLcHg_90.JPG: 480x640 (no detections), 276.0ms
Speed: 1.1ms preprocess, 276.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHuxR9xvQ--3Mcw9UlLcHg_180.JPG: 480x640 (no detections), 273.9ms
Speed: 1.0ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHuxR9xvQ--3Mcw9UlLcHg_270.JPG: 480x640 (no detections), 274.0ms
Speed: 1.3ms preprocess, 274.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHv6sBK8b2Wvvb6DdStgJw_0.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHv6sBK8b2Wvvb6DdStgJw_90.JPG: 480x640 (no detections), 275.2ms
Speed: 1.1ms preprocess, 275.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHv6sBK8b2Wvvb6DdStgJw_180.JPG: 480x640 (no detections), 274.7ms
Speed: 1.1ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHv6sBK8b2Wvvb6DdStgJw_270.JPG: 480x640 1 Waste, 274.3ms
Speed: 1.1ms preprocess, 274.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHvSwkopgNCpbUW_3ynZfQ_0.JPG: 480x640 (no detections), 282.7ms
Speed: 1.2ms preprocess, 282.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHvSwkopgNCpbUW_3ynZfQ_90.JPG: 480x640 (no detections), 273.6ms
Speed: 1.1ms preprocess, 273.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHvSwkopgNCpbUW_3ynZfQ_180.JPG: 480x640 (no detections), 268.7ms
Speed: 1.1ms preprocess, 268.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHvSwkopgNCpbUW_3ynZfQ_270.JPG: 480x640 (no detections), 274.0ms
Speed: 1.1ms preprocess, 274.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHv_UabVIjX0diGRCa2few_0.JPG: 480x640 (no detections), 270.3ms
Speed: 1.1ms preprocess, 270.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHv_UabVIjX0diGRCa2few_90.JPG: 480x640 (no detections), 272.4ms
Speed: 1.2ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHv_UabVIjX0diGRCa2few_180.JPG: 480x640 (no detections), 270.3ms
Speed: 1.1ms preprocess, 270.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHv_UabVIjX0diGRCa2few_270.JPG: 480x640 (no detections), 277.4ms
Speed: 1.2ms preprocess, 277.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHwC3p--z6XMQZhujmAu3w_0.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHwC3p--z6XMQZhujmAu3w_90.JPG: 480x640 (no detections), 273.1ms
Speed: 1.1ms preprocess, 273.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHwC3p--z6XMQZhujmAu3w_180.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zHwC3p--z6XMQZhujmAu3w_270.JPG: 480x640 (no detections), 276.2ms
Speed: 1.0ms preprocess, 276.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zI1pRzOHhoUdRRc6_i9_RA_0.JPG: 480x640 1 Waste, 282.0ms
Speed: 1.1ms preprocess, 282.0ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zI1pRzOHhoUdRRc6_i9_RA_90.JPG: 480x640 (no detections), 279.6ms
Speed: 1.2ms preprocess, 279.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zI1pRzOHhoUdRRc6_i9_RA_180.JPG: 480x640 (no detections), 275.6ms
Speed: 1.1ms preprocess, 275.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zI1pRzOHhoUdRRc6_i9_RA_270.JPG: 480x640 (no detections), 274.6ms
Speed: 1.3ms preprocess, 274.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zI2xbiXi4SZGv7TTOjJknw_0.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zI2xbiXi4SZGv7TTOjJknw_90.JPG: 480x640 (no detections), 278.6ms
Speed: 1.4ms preprocess, 278.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zI2xbiXi4SZGv7TTOjJknw_180.JPG: 480x640 (no detections), 277.9ms
Speed: 1.2ms preprocess, 277.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zI2xbiXi4SZGv7TTOjJknw_270.JPG: 480x640 (no detections), 272.4ms
Speed: 1.1ms preprocess, 272.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zI43HnMGlsKDOtKWEGA3lg_0.JPG: 480x640 (no detections), 270.3ms
Speed: 1.1ms preprocess, 270.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zI43HnMGlsKDOtKWEGA3lg_90.JPG: 480x640 (no detections), 272.3ms
Speed: 1.0ms preprocess, 272.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zI43HnMGlsKDOtKWEGA3lg_180.JPG: 480x640 (no detections), 273.8ms
Speed: 1.6ms preprocess, 273.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zI43HnMGlsKDOtKWEGA3lg_270.JPG: 480x640 (no detections), 271.5ms
Speed: 1.1ms preprocess, 271.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zI4XecE7xSw0nRHStYVh3w_0.JPG: 480x640 (no detections), 274.1ms

Speed: 1.4ms preprocess, 274.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zI4XecE7xSw0nRHStYVh3w_90.JPG: 480x640 (no detections), 274.3ms
Speed: 1.1ms preprocess, 274.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zI4XecE7xSw0nRHStYVh3w_180.JPG: 480x640 (no detections), 274.4ms
Speed: 1.1ms preprocess, 274.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zI4XecE7xSw0nRHStYVh3w_270.JPG: 480x640 (no detections), 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIDDAaNnbqgB4DZ6iDMFKw_0.JPG: 480x640 (no detections), 273.1ms
Speed: 1.1ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIDDAaNnbqgB4DZ6iDMFKw_90.JPG: 480x640 (no detections), 270.4ms
Speed: 1.1ms preprocess, 270.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIDDAaNnbqgB4DZ6iDMFKw_180.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIDDAaNnbqgB4DZ6iDMFKw_270.JPG: 480x640 (no detections), 273.4ms
Speed: 1.1ms preprocess, 273.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIEkK23-Wt_apbrAZCPQ5Q_0.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIEkK23-Wt_apbrAZCPQ5Q_90.JPG: 480x640 (no detections), 273.3ms
Speed: 1.0ms preprocess, 273.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIEkK23-Wt_apbrAZCPQ5Q_180.JPG: 480x640 (no detections), 268.3ms
Speed: 1.0ms preprocess, 268.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIEkK23-Wt_apbrAZCPQ5Q_270.JPG: 480x640 (no detections), 272.0ms
Speed: 1.0ms preprocess, 272.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIG8OeQGVvsUsZeD9gd9rQ_0.JPG: 480x640 (no detections), 274.9ms
Speed: 1.3ms preprocess, 274.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIG8OeQGVvsUsZeD9gd9rQ_90.JPG: 480x640 (no detections), 274.0ms
Speed: 1.0ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIG8OeQGVvsUsZeD9gd9rQ_180.JPG: 480x640 (no detections), 271.4ms
Speed: 1.2ms preprocess, 271.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIG8OeQGVvsUsZeD9gd9rQ_270.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIGPoY_Jj3wekwYNhPVPWA_0.JPG: 480x640 (no detections), 278.1ms
Speed: 1.1ms preprocess, 278.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIGPoY_Jj3wekwYNhPVPWA_90.JPG: 480x640 (no detections), 272.3ms
Speed: 1.0ms preprocess, 272.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIGPoY_Jj3wekwYNhPVPWA_180.JPG: 480x640 (no detections), 274.1ms
Speed: 1.2ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIGPoY_Jj3wekwYNhPVPWA_270.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIIitmM36RVxClVzyjFtMg_0.JPG: 480x640 (no detections), 274.4ms
Speed: 1.0ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIIitmM36RVxClVzyjFtMg_90.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIIitmM36RVxClVzyjFtMg_180.JPG: 480x640 (no detections), 289.0ms
Speed: 1.0ms preprocess, 289.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIIitmM36RVxClVzyjFtMg_270.JPG: 480x640 (no detections), 270.9ms
Speed: 1.2ms preprocess, 270.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zILf-d4wFUI5rJrLA0nvyg_0.JPG: 480x640 (no detections), 271.5ms
Speed: 1.2ms preprocess, 271.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zILf-d4wFUI5rJrLA0nvyg_90.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zILf-d4wFUI5rJrLA0nvyg_180.JPG: 480x640 (no detections), 275.4ms
Speed: 1.1ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zILf-d4wFUI5rJrLA0nvyg_270.JPG: 480x640 (no detections), 270.7ms
Speed: 1.2ms preprocess, 270.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIOz296hrDaPbw6ClqX4zQ_0.JPG: 480x640 (no detections), 280.6ms
Speed: 1.2ms preprocess, 280.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIOz296hrDaPbw6ClqX4zQ_90.JPG: 480x640 (no detections), 274.4ms
Speed: 1.2ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIOz296hrDaPbw6ClqX4zQ_180.JPG: 480x640 (no detections), 271.1ms
Speed: 1.0ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIOz296hrDaPbw6ClqX4zQ_270.JPG: 480x640 (no detections), 272.4ms
Speed: 1.1ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIWFU2vyMafXn0u9ZqQewg_0.JPG: 480x640 (no detections), 281.8ms
Speed: 1.1ms preprocess, 281.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIWFU2vyMafXn0u9ZqQewg_90.JPG: 480x640 (no detections), 273.4ms
Speed: 1.0ms preprocess, 273.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIWFU2vyMafXn0u9ZqQewg_180.JPG: 480x640 (no detections), 278.6ms
Speed: 1.0ms preprocess, 278.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIWFU2vyMafXn0u9ZqQewg_270.JPG: 480x640 (no detections), 273.6ms
Speed: 1.2ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIeDpiOkyYVTHThT_T5tJg_0.JPG: 480x640 (no detections), 306.5ms
Speed: 1.1ms preprocess, 306.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIeDpiOkyYVTHThT_T5tJg_90.JPG: 480x640 (no detections), 268.9ms
Speed: 1.0ms preprocess, 268.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIeDpiOkyYVTHThT_T5tJg_180.JPG: 480x640 (no detections), 274.3ms
Speed: 1.0ms preprocess, 274.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIeDpiOkyYVTHThT_T5tJg_270.JPG: 480x640 (no detections), 271.9ms
Speed: 1.2ms preprocess, 271.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIh407RXQSEgSYrg_L_4CA_0.JPG: 480x640 (no detections), 276.6ms
Speed: 1.0ms preprocess, 276.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIh407RXQSEgSYrg_L_4CA_90.JPG: 480x640 (no detections), 274.3ms
Speed: 1.1ms preprocess, 274.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIh407RXQSEgSYrg_L_4CA_180.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIh407RXQSEgSYrg_L_4CA_270.JPG: 480x640 (no detections), 275.0ms
Speed: 1.0ms preprocess, 275.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIhB1r3srIDjUb6dMfmeww_0.JPG: 480x640 (no detections), 275.1ms
Speed: 1.2ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIhB1r3srIDjUb6dMfmeww_90.JPG: 480x640 (no detections), 278.0ms
Speed: 1.1ms preprocess, 278.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIhB1r3srIDjUb6dMfmeww_180.JPG: 480x640 (no detections), 269.7ms
Speed: 1.2ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIhB1r3srIDjUb6dMfmeww_270.JPG: 480x640 (no detections), 273.1ms
Speed: 1.0ms preprocess, 273.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIhH0YlHSyl7e3z5J4YEmQ_0.JPG: 480x640 (no detections), 272.5ms
Speed: 1.0ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIhH0YlHSyl7e3z5J4YEmQ_90.JPG: 480x640 (no detections), 270.4ms
Speed: 1.1ms preprocess, 270.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIhH0YlHSyl7e3z5J4YEmQ_180.JPG: 480x640 (no detections), 267.7ms
Speed: 1.0ms preprocess, 267.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIhH0YlHSyl7e3z5J4YEmQ_270.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIjIqmLLvFVPt_02pHBlKA_0.JPG: 480x640 (no detections), 273.9ms
Speed: 1.1ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIjIqmLLvFVPt_02pHBlKA_90.JPG: 480x640 (no detections), 271.5ms
Speed: 1.2ms preprocess, 271.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIjIqmLLvFVPt_02pHBlKA_180.JPG: 480x640 (no detections), 275.7ms
Speed: 1.1ms preprocess, 275.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIjIqmLLvFVPt_02pHBlKA_270.JPG: 480x640 (no detections), 273.9ms
Speed: 1.1ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIkFv6vZbzYnRV1KI0lD-w_0.JPG: 480x640 (no detections), 273.3ms
Speed: 1.0ms preprocess, 273.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIkFv6vZbzYnRV1KI0lD-w_90.JPG: 480x640 (no detections), 276.9ms
Speed: 1.2ms preprocess, 276.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIkFv6vZbzYnRV1KI0lD-w_180.JPG: 480x640 1 Waste, 268.0ms
Speed: 1.0ms preprocess, 268.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIkFv6vZbzYnRV1KI0lD-w_270.JPG: 480x640 (no detections), 272.9ms
Speed: 1.2ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIn5mIYfCIS_wqiR8jgW6Q_0.JPG: 480x640 (no detections), 271.9ms
Speed: 1.2ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIn5mIYfCIS_wqiR8jgW6Q_90.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIn5mIYfCIS_wqiR8jgW6Q_180.JPG: 480x640 (no detections), 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIn5mIYfCIS_wqiR8jgW6Q_270.JPG: 480x640 (no detections), 272.0ms
Speed: 1.1ms preprocess, 272.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zInUNUieSx3CWe9l9QoLNw_0.JPG: 480x640 (no detections), 270.9ms
Speed: 1.2ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zInUNUieSx3CWe9l9QoLNw_90.JPG: 480x640 (no detections), 268.7ms
Speed: 1.1ms preprocess, 268.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zInUNUieSx3CWe9l9QoLNw_180.JPG: 480x640 (no detections), 274.5ms
Speed: 1.0ms preprocess, 274.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zInUNUieSx3CWe9l9QoLNw_270.JPG: 480x640 (no detections), 262.8ms

Speed: 1.0ms preprocess, 262.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIosDqeTa-5z2ZzAVTwK3Q_0.JPG: 480x640 (no detections), 267.5ms
Speed: 1.0ms preprocess, 267.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIosDqeTa-5z2ZzAVTwK3Q_90.JPG: 480x640 (no detections), 266.6ms
Speed: 1.1ms preprocess, 266.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIosDqeTa-5z2ZzAVTwK3Q_180.JPG: 480x640 (no detections), 272.1ms
Speed: 1.1ms preprocess, 272.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIosDqeTa-5z2ZzAVTwK3Q_270.JPG: 480x640 (no detections), 268.0ms
Speed: 1.1ms preprocess, 268.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIt1tFanYoDW11eVV1HCtw_0.JPG: 480x640 (no detections), 264.7ms
Speed: 1.0ms preprocess, 264.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIt1tFanYoDW11eVV1HCtw_90.JPG: 480x640 (no detections), 270.6ms
Speed: 1.0ms preprocess, 270.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIt1tFanYoDW11eVV1HCtw_180.JPG: 480x640 (no detections), 273.9ms
Speed: 1.0ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIt1tFanYoDW11eVV1HCtw_270.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIuHRbXOolmofTsI8s7IoA_0.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIuHRbXOolmofTsI8s7IoA_90.JPG: 480x640 (no detections), 285.3ms
Speed: 1.2ms preprocess, 285.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIuHRbXOolmofTsI8s7IoA_180.JPG: 480x640 (no detections), 281.3ms
Speed: 1.1ms preprocess, 281.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIuHRbXOolmofTsI8s7IoA_270.JPG: 480x640 (no detections), 274.3ms
Speed: 1.1ms preprocess, 274.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIvSccyBAkQfpPRQoLGl6A_0.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIvSccyBAkQfpPRQoLGl6A_90.JPG: 480x640 (no detections), 267.6ms
Speed: 1.0ms preprocess, 267.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIvSccyBAkQfpPRQoLGl6A_180.JPG: 480x640 (no detections), 273.3ms
Speed: 1.2ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIvSccyBAkQfpPRQoLGl6A_270.JPG: 480x640 (no detections), 274.7ms
Speed: 1.2ms preprocess, 274.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIyJCbRey3oA2jFs6xU3jw_0.JPG: 480x640 (no detections), 272.5ms
Speed: 1.2ms preprocess, 272.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIyJCbRey3oA2jFs6xU3jw_90.JPG: 480x640 (no detections), 268.7ms
Speed: 1.0ms preprocess, 268.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIyJCbRey3oA2jFs6xU3jw_180.JPG: 480x640 (no detections), 273.9ms
Speed: 1.0ms preprocess, 273.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zIyJCbRey3oA2jFs6xU3jw_270.JPG: 480x640 (no detections), 271.9ms
Speed: 1.0ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJ2yKU3zNFHwgPwGkPWR9Q_0.JPG: 480x640 (no detections), 274.4ms
Speed: 1.1ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJ2yKU3zNFHwgPwGkPWR9Q_90.JPG: 480x640 (no detections), 273.7ms
Speed: 1.0ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJ2yKU3zNFHwgPwGkPWR9Q_180.JPG: 480x640 (no detections), 278.6ms
Speed: 1.1ms preprocess, 278.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJ2yKU3zNFHwgPwGkPWR9Q_270.JPG: 480x640 (no detections), 301.1ms
Speed: 1.1ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJ3Bq0tELO46LhawFOUOcw_0.JPG: 480x640 (no detections), 278.5ms
Speed: 1.2ms preprocess, 278.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJ3Bq0tELO46LhawFOUOcw_90.JPG: 480x640 (no detections), 274.9ms
Speed: 1.0ms preprocess, 274.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJ3Bq0tELO46LhawFOUOcw_180.JPG: 480x640 (no detections), 273.2ms
Speed: 1.1ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJ3Bq0tELO46LhawFOUOcw_270.JPG: 480x640 (no detections), 269.9ms
Speed: 1.8ms preprocess, 269.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJ3m1RcGYOkHkfxtMblPlw_0.JPG: 480x640 1 Waste, 273.1ms
Speed: 1.1ms preprocess, 273.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJ3m1RcGYOkHkfxtMblPlw_90.JPG: 480x640 (no detections), 278.4ms
Speed: 1.4ms preprocess, 278.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJ3m1RcGYOkHkfxtMblPlw_180.JPG: 480x640 (no detections), 276.1ms
Speed: 1.3ms preprocess, 276.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJ3m1RcGYOkHkfxtMblPlw_270.JPG: 480x640 (no detections), 284.7ms
Speed: 1.1ms preprocess, 284.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJ3zw5DimLtKz7ml_1X1OQ_0.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJ3zw5DimLtKz7ml_1X1OQ_90.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJ3zw5DimLtKz7ml_1X1OQ_180.JPG: 480x640 (no detections), 279.9ms
Speed: 1.1ms preprocess, 279.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJ3zw5DimLtKz7ml_1X1OQ_270.JPG: 480x640 1 Waste, 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJ4Ft9q_sxv2cyWMuJt_EA_0.JPG: 480x640 (no detections), 292.2ms
Speed: 1.4ms preprocess, 292.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJ4Ft9q_sxv2cyWMuJt_EA_90.JPG: 480x640 (no detections), 274.2ms
Speed: 1.2ms preprocess, 274.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJ4Ft9q_sxv2cyWMuJt_EA_180.JPG: 480x640 (no detections), 269.3ms
Speed: 1.1ms preprocess, 269.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJ4Ft9q_sxv2cyWMuJt_EA_270.JPG: 480x640 (no detections), 301.2ms
Speed: 1.0ms preprocess, 301.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJ622LJgpM9vdC5OjDA46g_0.JPG: 480x640 (no detections), 297.3ms
Speed: 1.3ms preprocess, 297.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJ622LJgpM9vdC5OjDA46g_90.JPG: 480x640 (no detections), 295.4ms
Speed: 1.2ms preprocess, 295.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJ622LJgpM9vdC5OjDA46g_180.JPG: 480x640 (no detections), 300.7ms
Speed: 1.2ms preprocess, 300.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJ622LJgpM9vdC5OjDA46g_270.JPG: 480x640 (no detections), 303.8ms
Speed: 1.2ms preprocess, 303.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJ7lZroeRHmk-PSgZ44Iuw_0.JPG: 480x640 (no detections), 293.7ms
Speed: 1.3ms preprocess, 293.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJ7lZroeRHmk-PSgZ44Iuw_90.JPG: 480x640 (no detections), 287.2ms
Speed: 1.1ms preprocess, 287.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJ7lZroeRHmk-PSgZ44Iuw_180.JPG: 480x640 (no detections), 270.4ms
Speed: 1.0ms preprocess, 270.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJ7lZroeRHmk-PSgZ44Iuw_270.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJIpFvI_iaE3Hjd82wu1_g_0.JPG: 480x640 (no detections), 273.0ms
Speed: 1.2ms preprocess, 273.0ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJIpFvI_iaE3Hjd82wu1_g_90.JPG: 480x640 (no detections), 276.9ms
Speed: 1.0ms preprocess, 276.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJIpFvI_iaE3Hjd82wu1_g_180.JPG: 480x640 (no detections), 271.9ms
Speed: 1.0ms preprocess, 271.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJIpFvI_iaE3Hjd82wu1_g_270.JPG: 480x640 (no detections), 277.0ms
Speed: 1.0ms preprocess, 277.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJJWT9PcH89jIfY_tkxu2A_0.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJJWT9PcH89jIfY_tkxu2A_90.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJJWT9PcH89jIfY_tkxu2A_180.JPG: 480x640 (no detections), 290.3ms
Speed: 1.1ms preprocess, 290.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJJWT9PcH89jIfY_tkxu2A_270.JPG: 480x640 (no detections), 275.8ms
Speed: 1.2ms preprocess, 275.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJMbTCKRhoBNEnEEOJhcCA_0.JPG: 480x640 (no detections), 282.1ms
Speed: 1.2ms preprocess, 282.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJMbTCKRhoBNEnEEOJhcCA_90.JPG: 480x640 (no detections), 277.6ms
Speed: 1.1ms preprocess, 277.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJMbTCKRhoBNEnEEOJhcCA_180.JPG: 480x640 (no detections), 277.6ms
Speed: 1.0ms preprocess, 277.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJMbTCKRhoBNEnEEOJhcCA_270.JPG: 480x640 (no detections), 282.7ms
Speed: 1.3ms preprocess, 282.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJR_5ISPGBgsTdljPY2x4A_0.JPG: 480x640 (no detections), 276.5ms
Speed: 1.1ms preprocess, 276.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJR_5ISPGBgsTdljPY2x4A_90.JPG: 480x640 (no detections), 271.1ms
Speed: 1.2ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJR_5ISPGBgsTdljPY2x4A_180.JPG: 480x640 (no detections), 281.1ms
Speed: 1.1ms preprocess, 281.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJR_5ISPGBgsTdljPY2x4A_270.JPG: 480x640 (no detections), 277.4ms
Speed: 1.0ms preprocess, 277.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJSEWizJ2uQR_pdXheqkjQ_0.JPG: 480x640 (no detections), 277.2ms
Speed: 1.0ms preprocess, 277.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJSEWizJ2uQR_pdXheqkjQ_90.JPG: 480x640 1 Waste, 272.9ms
Speed: 1.0ms preprocess, 272.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJSEWizJ2uQR_pdXheqkjQ_180.JPG: 480x640 (no detections), 274.1ms

Speed: 1.0ms preprocess, 274.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJSEWizJ2uQR_pdXheqkjQ_270.JPG: 480x640 (no detections), 276.2ms
Speed: 1.1ms preprocess, 276.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJU1bHuezl2f9fnJoY-uag_0.JPG: 480x640 (no detections), 275.2ms
Speed: 1.1ms preprocess, 275.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJU1bHuezl2f9fnJoY-uag_90.JPG: 480x640 (no detections), 278.5ms
Speed: 1.1ms preprocess, 278.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJU1bHuezl2f9fnJoY-uag_180.JPG: 480x640 (no detections), 275.3ms
Speed: 1.1ms preprocess, 275.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJU1bHuezl2f9fnJoY-uag_270.JPG: 480x640 (no detections), 278.1ms
Speed: 1.1ms preprocess, 278.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJWdXxg3I_lFjdOiumF0mA_0.JPG: 480x640 (no detections), 271.9ms
Speed: 1.2ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJWdXxg3I_lFjdOiumF0mA_90.JPG: 480x640 (no detections), 274.8ms
Speed: 1.1ms preprocess, 274.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJWdXxg3I_lFjdOiumF0mA_180.JPG: 480x640 (no detections), 277.7ms
Speed: 1.0ms preprocess, 277.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJWdXxg3I_lFjdOiumF0mA_270.JPG: 480x640 (no detections), 299.3ms
Speed: 1.1ms preprocess, 299.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJYdUF_lNZqzr3x8o1jbiA_0.JPG: 480x640 (no detections), 287.6ms
Speed: 1.0ms preprocess, 287.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJYdUF_lNZqzr3x8o1jbiA_90.JPG: 480x640 (no detections), 273.8ms
Speed: 1.2ms preprocess, 273.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJYdUF_lNZqzr3x8o1jbiA_180.JPG: 480x640 (no detections), 273.4ms
Speed: 1.0ms preprocess, 273.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJYdUF_lNZqzr3x8o1jbiA_270.JPG: 480x640 (no detections), 274.0ms
Speed: 1.1ms preprocess, 274.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJbQVO5kjR6mje1SMMQ4cg_0.JPG: 480x640 (no detections), 274.3ms
Speed: 1.0ms preprocess, 274.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJbQVO5kjR6mje1SMMQ4cg_90.JPG: 480x640 (no detections), 276.5ms
Speed: 1.1ms preprocess, 276.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJbQVO5kjR6mje1SMMQ4cg_180.JPG: 480x640 (no detections), 273.4ms
Speed: 1.1ms preprocess, 273.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJbQVO5kjR6mje1SMMQ4cg_270.JPG: 480x640 (no detections), 276.7ms
Speed: 1.0ms preprocess, 276.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJc-NeSRIbBiMCyIw7d64g_0.JPG: 480x640 (no detections), 273.0ms
Speed: 1.0ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJc-NeSRIbBiMCyIw7d64g_90.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJc-NeSRIbBiMCyIw7d64g_180.JPG: 480x640 (no detections), 275.8ms
Speed: 1.1ms preprocess, 275.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJc-NeSRIbBiMCyIw7d64g_270.JPG: 480x640 (no detections), 273.2ms
Speed: 1.1ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJdVEM6n_LB1przUMfg4YA_0.JPG: 480x640 (no detections), 278.6ms
Speed: 1.0ms preprocess, 278.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJdVEM6n_LB1przUMfg4YA_90.JPG: 480x640 (no detections), 285.2ms
Speed: 1.1ms preprocess, 285.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJdVEM6n_LB1przUMfg4YA_180.JPG: 480x640 (no detections), 327.1ms
Speed: 1.2ms preprocess, 327.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJdVEM6n_LB1przUMfg4YA_270.JPG: 480x640 (no detections), 287.0ms
Speed: 1.2ms preprocess, 287.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJdsFCvq5uaXodOJKFdJkg_0.JPG: 480x640 (no detections), 298.0ms
Speed: 1.1ms preprocess, 298.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJdsFCvq5uaXodOJKFdJkg_90.JPG: 480x640 (no detections), 461.0ms
Speed: 1.1ms preprocess, 461.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJdsFCvq5uaXodOJKFdJkg_180.JPG: 480x640 (no detections), 356.7ms
Speed: 4.6ms preprocess, 356.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJdsFCvq5uaXodOJKFdJkg_270.JPG: 480x640 (no detections), 293.3ms
Speed: 1.2ms preprocess, 293.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJf80pXLTok0fEdMWjOPew_0.JPG: 480x640 (no detections), 281.7ms
Speed: 1.3ms preprocess, 281.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJf80pXLTok0fEdMWjOPew_90.JPG: 480x640 (no detections), 273.4ms
Speed: 1.1ms preprocess, 273.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJf80pXLTok0fEdMWjOPew_180.JPG: 480x640 (no detections), 274.0ms
Speed: 1.0ms preprocess, 274.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJf80pXLTok0fEdMWjOPew_270.JPG: 480x640 (no detections), 275.6ms
Speed: 1.3ms preprocess, 275.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJg_xTQpX_rdgNDPClTirQ_0.JPG: 480x640 (no detections), 269.5ms
Speed: 1.1ms preprocess, 269.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJg_xTQpX_rdgNDPClTirQ_90.JPG: 480x640 (no detections), 275.3ms
Speed: 1.1ms preprocess, 275.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJg_xTQpX_rdgNDPClTirQ_180.JPG: 480x640 (no detections), 268.4ms
Speed: 1.1ms preprocess, 268.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJg_xTQpX_rdgNDPClTirQ_270.JPG: 480x640 (no detections), 272.5ms
Speed: 1.1ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJoA2qWBLSzDRFMlov4hPQ_0.JPG: 480x640 (no detections), 298.6ms
Speed: 1.1ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJoA2qWBLSzDRFMlov4hPQ_90.JPG: 480x640 (no detections), 271.7ms
Speed: 1.2ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJoA2qWBLSzDRFMlov4hPQ_180.JPG: 480x640 (no detections), 306.4ms
Speed: 1.1ms preprocess, 306.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJoA2qWBLSzDRFMlov4hPQ_270.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJuBgwcMrOSQjdUzAmPXQA_0.JPG: 480x640 (no detections), 275.8ms
Speed: 1.1ms preprocess, 275.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJuBgwcMrOSQjdUzAmPXQA_90.JPG: 480x640 (no detections), 272.6ms
Speed: 1.2ms preprocess, 272.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJuBgwcMrOSQjdUzAmPXQA_180.JPG: 480x640 (no detections), 267.7ms
Speed: 1.1ms preprocess, 267.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJuBgwcMrOSQjdUzAmPXQA_270.JPG: 480x640 (no detections), 268.2ms
Speed: 1.1ms preprocess, 268.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJx6XwJVH4YTMzmdGdtKiQ_0.JPG: 480x640 (no detections), 274.4ms
Speed: 1.2ms preprocess, 274.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJx6XwJVH4YTMzmdGdtKiQ_90.JPG: 480x640 (no detections), 278.4ms
Speed: 1.0ms preprocess, 278.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJx6XwJVH4YTMzmdGdtKiQ_180.JPG: 480x640 (no detections), 277.4ms
Speed: 1.1ms preprocess, 277.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJx6XwJVH4YTMzmdGdtKiQ_270.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJzo3D8dmmqiXEv3wAZuGQ_0.JPG: 480x640 (no detections), 271.0ms
Speed: 1.1ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJzo3D8dmmqiXEv3wAZuGQ_90.JPG: 480x640 (no detections), 270.9ms
Speed: 1.1ms preprocess, 270.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJzo3D8dmmqiXEv3wAZuGQ_180.JPG: 480x640 (no detections), 276.0ms
Speed: 1.0ms preprocess, 276.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zJzo3D8dmmqiXEv3wAZuGQ_270.JPG: 480x640 (no detections), 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zK1k_VoVotcXryFLsjJWzA_0.JPG: 480x640 (no detections), 275.0ms
Speed: 1.0ms preprocess, 275.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zK1k_VoVotcXryFLsjJWzA_90.JPG: 480x640 (no detections), 269.0ms
Speed: 1.1ms preprocess, 269.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zK1k_VoVotcXryFLsjJWzA_180.JPG: 480x640 (no detections), 272.5ms
Speed: 1.0ms preprocess, 272.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zK1k_VoVotcXryFLsjJWzA_270.JPG: 480x640 (no detections), 288.3ms
Speed: 1.1ms preprocess, 288.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zK3ApyJhm_F3Lg3Qv7QwmA_0.JPG: 480x640 (no detections), 271.7ms
Speed: 1.0ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zK3ApyJhm_F3Lg3Qv7QwmA_90.JPG: 480x640 (no detections), 271.0ms
Speed: 1.0ms preprocess, 271.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zK3ApyJhm_F3Lg3Qv7QwmA_180.JPG: 480x640 (no detections), 296.3ms
Speed: 1.0ms preprocess, 296.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zK3ApyJhm_F3Lg3Qv7QwmA_270.JPG: 480x640 (no detections), 270.2ms
Speed: 1.5ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zK3JE9iXLX3x1_vvJ2J6Fg_0.JPG: 480x640 (no detections), 275.3ms
Speed: 1.2ms preprocess, 275.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zK3JE9iXLX3x1_vvJ2J6Fg_90.JPG: 480x640 (no detections), 272.2ms
Speed: 1.0ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zK3JE9iXLX3x1_vvJ2J6Fg_180.JPG: 480x640 (no detections), 270.1ms
Speed: 1.0ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zK3JE9iXLX3x1_vvJ2J6Fg_270.JPG: 480x640 (no detections), 268.5ms
Speed: 1.0ms preprocess, 268.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zK47Gfe1Z5WUsxL9zcp2WA_0.JPG: 480x640 (no detections), 271.7ms
Speed: 1.0ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zK47Gfe1Z5WUsxL9zcp2WA_90.JPG: 480x640 (no detections), 274.4ms

Speed: 1.0ms preprocess, 274.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zK47Gfe1Z5WUsxL9zcp2WA_180.JPG: 480x640 (no detections), 272.5ms
Speed: 1.0ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zK47Gfe1Z5WUsxL9zcp2WA_270.JPG: 480x640 (no detections), 276.2ms
Speed: 1.1ms preprocess, 276.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zK8Vy-5W391pzqR4h6qV8w_0.JPG: 480x640 (no detections), 277.5ms
Speed: 1.0ms preprocess, 277.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zK8Vy-5W391pzqR4h6qV8w_90.JPG: 480x640 (no detections), 272.1ms
Speed: 1.1ms preprocess, 272.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zK8Vy-5W391pzqR4h6qV8w_180.JPG: 480x640 (no detections), 273.2ms
Speed: 1.1ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zK8Vy-5W391pzqR4h6qV8w_270.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zK9VqKdeLsETU7Rwnyh4rA_0.JPG: 480x640 (no detections), 271.9ms
Speed: 1.0ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zK9VqKdeLsETU7Rwnyh4rA_90.JPG: 480x640 (no detections), 273.7ms
Speed: 1.0ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zK9VqKdeLsETU7Rwnyh4rA_180.JPG: 480x640 (no detections), 270.5ms
Speed: 1.1ms preprocess, 270.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zK9VqKdeLsETU7Rwnyh4rA_270.JPG: 480x640 (no detections), 276.8ms
Speed: 1.3ms preprocess, 276.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKA7nCPmPzMooxAZccHJIQ_0.JPG: 480x640 (no detections), 275.3ms
Speed: 1.2ms preprocess, 275.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKA7nCPmPzMooxAZccHJIQ_90.JPG: 480x640 (no detections), 274.0ms
Speed: 1.1ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKA7nCPmPzMooxAZccHJIQ_180.JPG: 480x640 (no detections), 283.5ms
Speed: 1.1ms preprocess, 283.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKA7nCPmPzMooxAZccHJIQ_270.JPG: 480x640 (no detections), 274.4ms
Speed: 1.1ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKApmvhS86lsQkN4zwOKUw_0.JPG: 480x640 (no detections), 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKApmvhS86lsQkN4zwOKUw_90.JPG: 480x640 (no detections), 269.5ms
Speed: 1.0ms preprocess, 269.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKApmvhS86lsQkN4zwOKUw_180.JPG: 480x640 (no detections), 274.6ms
Speed: 1.1ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKApmvhS86lsQkN4zwOKUw_270.JPG: 480x640 (no detections), 271.3ms
Speed: 1.0ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKC9xywqMaqok9cySB4iRQ_0.JPG: 480x640 1 Waste, 275.6ms
Speed: 1.2ms preprocess, 275.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKC9xywqMaqok9cySB4iRQ_90.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKC9xywqMaqok9cySB4iRQ_180.JPG: 480x640 (no detections), 276.0ms
Speed: 1.1ms preprocess, 276.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKC9xywqMaqok9cySB4iRQ_270.JPG: 480x640 (no detections), 270.3ms
Speed: 1.0ms preprocess, 270.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKLEQ4vAYtgbDjuLv5OeRw_0.JPG: 480x640 1 Waste, 272.9ms
Speed: 1.0ms preprocess, 272.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKLEQ4vAYtgbDjuLv5OeRw_90.JPG: 480x640 (no detections), 268.6ms
Speed: 1.0ms preprocess, 268.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKLEQ4vAYtgbDjuLv5OeRw_180.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKLEQ4vAYtgbDjuLv5OeRw_270.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKReIB-4UYLroj3SHmwiuA_0.JPG: 480x640 (no detections), 273.9ms
Speed: 1.0ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKReIB-4UYLroj3SHmwiuA_90.JPG: 480x640 (no detections), 274.8ms
Speed: 1.0ms preprocess, 274.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKReIB-4UYLroj3SHmwiuA_180.JPG: 480x640 (no detections), 276.8ms
Speed: 1.0ms preprocess, 276.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKReIB-4UYLroj3SHmwiuA_270.JPG: 480x640 (no detections), 273.9ms
Speed: 1.1ms preprocess, 273.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKZb0UVntt8fyTcwp0wCLg_0.JPG: 480x640 (no detections), 274.9ms
Speed: 1.1ms preprocess, 274.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKZb0UVntt8fyTcwp0wCLg_90.JPG: 480x640 (no detections), 280.3ms
Speed: 1.1ms preprocess, 280.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKZb0UVntt8fyTcwp0wCLg_180.JPG: 480x640 (no detections), 277.5ms
Speed: 1.0ms preprocess, 277.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKZb0UVntt8fyTcwp0wCLg_270.JPG: 480x640 (no detections), 276.2ms
Speed: 1.0ms preprocess, 276.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKhgfkm4PMHxIIVxOXsxuA_0.JPG: 480x640 (no detections), 280.4ms
Speed: 1.2ms preprocess, 280.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKhgfkm4PMHxIIVxOXsxuA_90.JPG: 480x640 (no detections), 277.2ms
Speed: 1.2ms preprocess, 277.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKhgfkm4PMHxIIVxOXsxuA_180.JPG: 480x640 (no detections), 273.2ms
Speed: 1.2ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKhgfkm4PMHxIIVxOXsxuA_270.JPG: 480x640 (no detections), 270.2ms
Speed: 1.0ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKhtORP46fYMwHIKGcVQYg_0.JPG: 480x640 (no detections), 270.9ms
Speed: 1.0ms preprocess, 270.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKhtORP46fYMwHIKGcVQYg_90.JPG: 480x640 (no detections), 272.5ms
Speed: 1.0ms preprocess, 272.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKhtORP46fYMwHIKGcVQYg_180.JPG: 480x640 (no detections), 286.4ms
Speed: 1.1ms preprocess, 286.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKhtORP46fYMwHIKGcVQYg_270.JPG: 480x640 (no detections), 272.0ms
Speed: 1.1ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKi8hWgoM5U1-7HNuEH-9w_0.JPG: 480x640 (no detections), 274.3ms
Speed: 1.2ms preprocess, 274.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKi8hWgoM5U1-7HNuEH-9w_90.JPG: 480x640 (no detections), 277.4ms
Speed: 1.1ms preprocess, 277.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKi8hWgoM5U1-7HNuEH-9w_180.JPG: 480x640 (no detections), 285.1ms
Speed: 1.1ms preprocess, 285.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKi8hWgoM5U1-7HNuEH-9w_270.JPG: 480x640 (no detections), 286.6ms
Speed: 1.4ms preprocess, 286.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKj_lkfCu6nggF9RJUJDjA_0.JPG: 480x640 (no detections), 274.1ms
Speed: 1.2ms preprocess, 274.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKj_lkfCu6nggF9RJUJDjA_90.JPG: 480x640 (no detections), 277.3ms
Speed: 1.2ms preprocess, 277.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKj_lkfCu6nggF9RJUJDjA_180.JPG: 480x640 (no detections), 281.1ms
Speed: 1.0ms preprocess, 281.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKj_lkfCu6nggF9RJUJDjA_270.JPG: 480x640 (no detections), 276.2ms
Speed: 1.0ms preprocess, 276.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKrPZYpQtuCrWhDZiSBgew_0.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKrPZYpQtuCrWhDZiSBgew_90.JPG: 480x640 (no detections), 277.3ms
Speed: 1.2ms preprocess, 277.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKrPZYpQtuCrWhDZiSBgew_180.JPG: 480x640 (no detections), 298.3ms
Speed: 1.2ms preprocess, 298.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKrPZYpQtuCrWhDZiSBgew_270.JPG: 480x640 (no detections), 309.9ms
Speed: 1.3ms preprocess, 309.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKrmnMmIcOKfVqnwmF39Vw_0.JPG: 480x640 (no detections), 339.5ms
Speed: 1.1ms preprocess, 339.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKrmnMmIcOKfVqnwmF39Vw_90.JPG: 480x640 (no detections), 327.9ms
Speed: 1.3ms preprocess, 327.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKrmnMmIcOKfVqnwmF39Vw_180.JPG: 480x640 (no detections), 316.3ms
Speed: 1.0ms preprocess, 316.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKrmnMmIcOKfVqnwmF39Vw_270.JPG: 480x640 (no detections), 281.1ms
Speed: 1.4ms preprocess, 281.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKvn0dPdajEwshuBBcpKvw_0.JPG: 480x640 (no detections), 284.8ms
Speed: 1.5ms preprocess, 284.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKvn0dPdajEwshuBBcpKvw_90.JPG: 480x640 (no detections), 275.9ms
Speed: 1.1ms preprocess, 275.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKvn0dPdajEwshuBBcpKvw_180.JPG: 480x640 (no detections), 269.8ms
Speed: 1.3ms preprocess, 269.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKvn0dPdajEwshuBBcpKvw_270.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKxqmT5W__SOjFagtu7erA_0.JPG: 480x640 (no detections), 269.8ms
Speed: 1.0ms preprocess, 269.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKxqmT5W__SOjFagtu7erA_90.JPG: 480x640 (no detections), 275.4ms
Speed: 1.0ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKxqmT5W__SOjFagtu7erA_180.JPG: 480x640 3 Wastes, 268.8ms
Speed: 1.1ms preprocess, 268.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKxqmT5W__SOjFagtu7erA_270.JPG: 480x640 2 Wastes, 271.5ms
Speed: 1.0ms preprocess, 271.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKyAtcTTUApJ1gY2d15CwA_0.JPG: 480x640 (no detections), 305.9ms

Speed: 1.1ms preprocess, 305.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKyAtcTTUApJ1gY2d15CwA_90.JPG: 480x640 (no detections), 271.7ms
Speed: 1.0ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKyAtcTTUApJ1gY2d15CwA_180.JPG: 480x640 (no detections), 272.7ms
Speed: 1.0ms preprocess, 272.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKyAtcTTUApJ1gY2d15CwA_270.JPG: 480x640 (no detections), 277.7ms
Speed: 1.2ms preprocess, 277.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKzgTOt3ys2YnYz7wFfPAQ_0.JPG: 480x640 (no detections), 275.6ms
Speed: 1.2ms preprocess, 275.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKzgTOt3ys2YnYz7wFfPAQ_90.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKzgTOt3ys2YnYz7wFfPAQ_180.JPG: 480x640 (no detections), 275.4ms
Speed: 1.1ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKzgTOt3ys2YnYz7wFfPAQ_270.JPG: 480x640 (no detections), 269.2ms
Speed: 1.0ms preprocess, 269.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKznYsI6fF_hFpHZoZVbLQ_0.JPG: 480x640 (no detections), 272.5ms
Speed: 1.0ms preprocess, 272.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKznYsI6fF_hFpHZoZVbLQ_90.JPG: 480x640 (no detections), 272.2ms
Speed: 1.2ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKznYsI6fF_hFpHZoZVbLQ_180.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zKznYsI6fF_hFpHZoZVbLQ_270.JPG: 480x640 (no detections), 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zL0bz4caHddv5-N3G_lW8w_0.JPG: 480x640 (no detections), 278.1ms
Speed: 1.3ms preprocess, 278.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zL0bz4caHddv5-N3G_lW8w_90.JPG: 480x640 (no detections), 271.5ms
Speed: 1.1ms preprocess, 271.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zL0bz4caHddv5-N3G_lW8w_180.JPG: 480x640 (no detections), 273.3ms
Speed: 1.0ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zL0bz4caHddv5-N3G_lW8w_270.JPG: 480x640 (no detections), 276.5ms
Speed: 1.1ms preprocess, 276.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zL4wexoi8tV7mOGWVYHIdQ_0.JPG: 480x640 (no detections), 272.0ms
Speed: 1.1ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zL4wexoi8tV7mOGWVYHIdQ_90.JPG: 480x640 (no detections), 278.1ms
Speed: 1.1ms preprocess, 278.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zL4wexoi8tV7mOGWVYHIdQ_180.JPG: 480x640 (no detections), 283.9ms
Speed: 1.2ms preprocess, 283.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zL4wexoi8tV7mOGWVYHIdQ_270.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zL5TIOWRIZnITL2HsIWHow_0.JPG: 480x640 (no detections), 276.5ms
Speed: 1.1ms preprocess, 276.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zL5TIOWRIZnITL2HsIWHow_90.JPG: 480x640 (no detections), 271.9ms
Speed: 1.0ms preprocess, 271.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zL5TIOWRIZnITL2HsIWHow_180.JPG: 480x640 (no detections), 281.0ms
Speed: 1.2ms preprocess, 281.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zL5TIOWRIZnITL2HsIWHow_270.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zL5nDqCeSe8KQ5PoQD8avA_0.JPG: 480x640 (no detections), 281.6ms
Speed: 1.2ms preprocess, 281.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zL5nDqCeSe8KQ5PoQD8avA_90.JPG: 480x640 (no detections), 274.5ms
Speed: 1.1ms preprocess, 274.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zL5nDqCeSe8KQ5PoQD8avA_180.JPG: 480x640 (no detections), 277.0ms
Speed: 1.0ms preprocess, 277.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zL5nDqCeSe8KQ5PoQD8avA_270.JPG: 480x640 (no detections), 269.8ms
Speed: 1.0ms preprocess, 269.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zL7dyXQHVJ8lPoCSSGBfAw_0.JPG: 480x640 (no detections), 274.7ms
Speed: 1.2ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zL7dyXQHVJ8lPoCSSGBfAw_90.JPG: 480x640 (no detections), 273.5ms
Speed: 1.4ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zL7dyXQHVJ8lPoCSSGBfAw_180.JPG: 480x640 (no detections), 274.4ms
Speed: 1.1ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zL7dyXQHVJ8lPoCSSGBfAw_270.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zL8ZXhSRJh78kTcloGfVhg_0.JPG: 480x640 (no detections), 273.8ms
Speed: 1.0ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zL8ZXhSRJh78kTcloGfVhg_90.JPG: 480x640 (no detections), 268.2ms
Speed: 1.1ms preprocess, 268.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zL8ZXhSRJh78kTcloGfVhg_180.JPG: 480x640 (no detections), 269.9ms
Speed: 1.0ms preprocess, 269.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zL8ZXhSRJh78kTcloGfVhg_270.JPG: 480x640 (no detections), 268.9ms
Speed: 1.0ms preprocess, 268.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLALGkI4JJ__KeZ2S3DA_Q_0.JPG: 480x640 (no detections), 271.6ms
Speed: 1.7ms preprocess, 271.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLALGkI4JJ__KeZ2S3DA_Q_90.JPG: 480x640 (no detections), 273.5ms
Speed: 1.2ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLALGkI4JJ__KeZ2S3DA_Q_180.JPG: 480x640 (no detections), 268.5ms
Speed: 1.1ms preprocess, 268.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLALGkI4JJ__KeZ2S3DA_Q_270.JPG: 480x640 (no detections), 269.5ms
Speed: 1.1ms preprocess, 269.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLC3w74dE56ERYxaGm0_Jg_0.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLC3w74dE56ERYxaGm0_Jg_90.JPG: 480x640 (no detections), 275.8ms
Speed: 1.0ms preprocess, 275.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLC3w74dE56ERYxaGm0_Jg_180.JPG: 480x640 (no detections), 268.6ms
Speed: 1.0ms preprocess, 268.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLC3w74dE56ERYxaGm0_Jg_270.JPG: 480x640 (no detections), 285.5ms
Speed: 1.1ms preprocess, 285.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLGDip93sHCHSU357hdtig_0.JPG: 480x640 (no detections), 283.6ms
Speed: 1.1ms preprocess, 283.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLGDip93sHCHSU357hdtig_90.JPG: 480x640 (no detections), 277.9ms
Speed: 1.1ms preprocess, 277.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLGDip93sHCHSU357hdtig_180.JPG: 480x640 (no detections), 305.4ms
Speed: 1.0ms preprocess, 305.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLGDip93sHCHSU357hdtig_270.JPG: 480x640 (no detections), 286.9ms
Speed: 1.3ms preprocess, 286.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLIbgd1O2LT49o6QFdhQSw_0.JPG: 480x640 (no detections), 288.9ms
Speed: 1.2ms preprocess, 288.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLIbgd1O2LT49o6QFdhQSw_90.JPG: 480x640 (no detections), 289.4ms
Speed: 1.1ms preprocess, 289.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLIbgd1O2LT49o6QFdhQSw_180.JPG: 480x640 (no detections), 369.7ms
Speed: 1.3ms preprocess, 369.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLIbgd1O2LT49o6QFdhQSw_270.JPG: 480x640 (no detections), 283.0ms
Speed: 1.2ms preprocess, 283.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLPkiiHD4PKMzaADFC_szA_0.JPG: 480x640 (no detections), 291.5ms
Speed: 1.2ms preprocess, 291.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLPkiiHD4PKMzaADFC_szA_90.JPG: 480x640 (no detections), 300.3ms
Speed: 1.1ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLPkiiHD4PKMzaADFC_szA_180.JPG: 480x640 1 Waste, 294.4ms
Speed: 1.2ms preprocess, 294.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLPkiiHD4PKMzaADFC_szA_270.JPG: 480x640 (no detections), 286.2ms
Speed: 1.3ms preprocess, 286.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLPvhaz-9ZuIo9sJt6RkXA_0.JPG: 480x640 (no detections), 316.2ms
Speed: 1.2ms preprocess, 316.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLPvhaz-9ZuIo9sJt6RkXA_90.JPG: 480x640 (no detections), 311.8ms
Speed: 2.2ms preprocess, 311.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLPvhaz-9ZuIo9sJt6RkXA_180.JPG: 480x640 (no detections), 317.0ms
Speed: 1.4ms preprocess, 317.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLPvhaz-9ZuIo9sJt6RkXA_270.JPG: 480x640 (no detections), 316.3ms
Speed: 1.1ms preprocess, 316.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLQTIUNamkz7CdhkIUflmg_0.JPG: 480x640 (no detections), 415.9ms
Speed: 1.3ms preprocess, 415.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLQTIUNamkz7CdhkIUflmg_90.JPG: 480x640 (no detections), 294.0ms
Speed: 1.8ms preprocess, 294.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLQTIUNamkz7CdhkIUflmg_180.JPG: 480x640 (no detections), 312.8ms
Speed: 1.1ms preprocess, 312.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLQTIUNamkz7CdhkIUflmg_270.JPG: 480x640 (no detections), 296.2ms
Speed: 1.1ms preprocess, 296.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLSqVKoHRqvgeXzIR_xiDQ_0.JPG: 480x640 (no detections), 288.2ms
Speed: 1.2ms preprocess, 288.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLSqVKoHRqvgeXzIR_xiDQ_90.JPG: 480x640 (no detections), 269.7ms
Speed: 1.0ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLSqVKoHRqvgeXzIR_xiDQ_180.JPG: 480x640 (no detections), 302.8ms
Speed: 1.1ms preprocess, 302.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLSqVKoHRqvgeXzIR_xiDQ_270.JPG: 480x640 (no detections), 272.8ms

Speed: 1.2ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLTNpqx6m6T8pqcM9po0Jg_0.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLTNpqx6m6T8pqcM9po0Jg_90.JPG: 480x640 1 Waste, 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLTNpqx6m6T8pqcM9po0Jg_180.JPG: 480x640 1 Waste, 277.5ms
Speed: 1.1ms preprocess, 277.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLTNpqx6m6T8pqcM9po0Jg_270.JPG: 480x640 (no detections), 275.4ms
Speed: 1.0ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLTRR59loxmizd_1QwkdLQ_0.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLTRR59loxmizd_1QwkdLQ_90.JPG: 480x640 (no detections), 280.5ms
Speed: 1.0ms preprocess, 280.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLTRR59loxmizd_1QwkdLQ_180.JPG: 480x640 (no detections), 270.5ms
Speed: 1.1ms preprocess, 270.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLTRR59loxmizd_1QwkdLQ_270.JPG: 480x640 (no detections), 271.3ms
Speed: 1.2ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLVT8_cWWXUXlSPfiyVYkA_0.JPG: 480x640 (no detections), 272.4ms
Speed: 1.1ms preprocess, 272.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLVT8_cWWXUXlSPfiyVYkA_90.JPG: 480x640 (no detections), 282.9ms
Speed: 1.0ms preprocess, 282.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLVT8_cWWXUXlSPfiyVYkA_180.JPG: 480x640 (no detections), 297.3ms
Speed: 1.5ms preprocess, 297.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLVT8_cWWXUXlSPfiyVYkA_270.JPG: 480x640 (no detections), 276.1ms
Speed: 1.1ms preprocess, 276.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLXDc-CU6_c-ZZsx0WNKyQ_0.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLXDc-CU6_c-ZZsx0WNKyQ_90.JPG: 480x640 (no detections), 274.7ms
Speed: 1.1ms preprocess, 274.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLXDc-CU6_c-ZZsx0WNKyQ_180.JPG: 480x640 (no detections), 303.5ms
Speed: 1.0ms preprocess, 303.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLXDc-CU6_c-ZZsx0WNKyQ_270.JPG: 480x640 (no detections), 304.2ms
Speed: 1.2ms preprocess, 304.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLXrEvhK70vDxDhuaC_-5Q_0.JPG: 480x640 (no detections), 329.1ms
Speed: 1.4ms preprocess, 329.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLXrEvhK70vDxDhuaC_-5Q_90.JPG: 480x640 (no detections), 320.9ms
Speed: 1.5ms preprocess, 320.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLXrEvhK70vDxDhuaC_-5Q_180.JPG: 480x640 (no detections), 277.5ms
Speed: 1.4ms preprocess, 277.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLXrEvhK70vDxDhuaC_-5Q_270.JPG: 480x640 (no detections), 274.9ms
Speed: 1.1ms preprocess, 274.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLYTZAttuiAd_SfxSsfBAA_0.JPG: 480x640 (no detections), 272.3ms
Speed: 1.2ms preprocess, 272.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLYTZAttuiAd_SfxSsfBAA_90.JPG: 480x640 (no detections), 275.6ms
Speed: 1.1ms preprocess, 275.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLYTZAttuiAd_SfxSsfBAA_180.JPG: 480x640 (no detections), 272.0ms
Speed: 1.0ms preprocess, 272.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLYTZAttuiAd_SfxSsfBAA_270.JPG: 480x640 (no detections), 279.4ms
Speed: 1.1ms preprocess, 279.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLYULbIR9hgTT0z0masQ8Q_0.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLYULbIR9hgTT0z0masQ8Q_90.JPG: 480x640 (no detections), 274.3ms
Speed: 1.0ms preprocess, 274.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLYULbIR9hgTT0z0masQ8Q_180.JPG: 480x640 (no detections), 269.7ms
Speed: 1.0ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLYULbIR9hgTT0z0masQ8Q_270.JPG: 480x640 (no detections), 273.5ms
Speed: 1.2ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLYm1b7LMQtbCVKHYoi2QQ_0.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLYm1b7LMQtbCVKHYoi2QQ_90.JPG: 480x640 (no detections), 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLYm1b7LMQtbCVKHYoi2QQ_180.JPG: 480x640 (no detections), 280.9ms
Speed: 1.1ms preprocess, 280.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLYm1b7LMQtbCVKHYoi2QQ_270.JPG: 480x640 (no detections), 300.9ms
Speed: 1.1ms preprocess, 300.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLZ77_8dzGScnIKW03GTaQ_0.JPG: 480x640 (no detections), 334.8ms
Speed: 1.5ms preprocess, 334.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLZ77_8dzGScnIKW03GTaQ_90.JPG: 480x640 (no detections), 318.8ms
Speed: 1.3ms preprocess, 318.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLZ77_8dzGScnIKW03GTaQ_180.JPG: 480x640 (no detections), 278.4ms
Speed: 1.4ms preprocess, 278.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLZ77_8dzGScnIKW03GTaQ_270.JPG: 480x640 (no detections), 273.9ms
Speed: 1.3ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLZok9KwKADGljpAiJa9Ow_0.JPG: 480x640 (no detections), 269.4ms
Speed: 1.1ms preprocess, 269.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLZok9KwKADGljpAiJa9Ow_90.JPG: 480x640 (no detections), 284.9ms
Speed: 1.0ms preprocess, 284.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLZok9KwKADGljpAiJa9Ow_180.JPG: 480x640 (no detections), 307.9ms
Speed: 1.2ms preprocess, 307.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLZok9KwKADGljpAiJa9Ow_270.JPG: 480x640 (no detections), 273.3ms
Speed: 1.2ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLa1PwvwdbJDugvEMbJcSA_0.JPG: 480x640 (no detections), 292.1ms
Speed: 1.0ms preprocess, 292.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLa1PwvwdbJDugvEMbJcSA_90.JPG: 480x640 (no detections), 297.7ms
Speed: 1.0ms preprocess, 297.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLa1PwvwdbJDugvEMbJcSA_180.JPG: 480x640 (no detections), 314.0ms
Speed: 1.3ms preprocess, 314.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLa1PwvwdbJDugvEMbJcSA_270.JPG: 480x640 (no detections), 301.4ms
Speed: 1.3ms preprocess, 301.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLdA2zLi6-GaSe0VmMG-7Q_0.JPG: 480x640 (no detections), 272.8ms
Speed: 1.0ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLdA2zLi6-GaSe0VmMG-7Q_90.JPG: 480x640 (no detections), 303.3ms
Speed: 1.2ms preprocess, 303.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLdA2zLi6-GaSe0VmMG-7Q_180.JPG: 480x640 (no detections), 300.1ms
Speed: 1.1ms preprocess, 300.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLdA2zLi6-GaSe0VmMG-7Q_270.JPG: 480x640 (no detections), 307.7ms
Speed: 1.2ms preprocess, 307.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLdqnbL_eHL99xH7n1DWtA_0.JPG: 480x640 (no detections), 371.4ms
Speed: 1.2ms preprocess, 371.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLdqnbL_eHL99xH7n1DWtA_90.JPG: 480x640 (no detections), 272.5ms
Speed: 1.2ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLdqnbL_eHL99xH7n1DWtA_180.JPG: 480x640 1 Waste, 354.2ms
Speed: 1.0ms preprocess, 354.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLdqnbL_eHL99xH7n1DWtA_270.JPG: 480x640 (no detections), 295.1ms
Speed: 1.4ms preprocess, 295.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLigS-DMwruR0dwAZ8oD2Q_0.JPG: 480x640 (no detections), 289.4ms
Speed: 1.3ms preprocess, 289.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLigS-DMwruR0dwAZ8oD2Q_90.JPG: 480x640 (no detections), 321.9ms
Speed: 1.0ms preprocess, 321.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLigS-DMwruR0dwAZ8oD2Q_180.JPG: 480x640 (no detections), 290.0ms
Speed: 1.6ms preprocess, 290.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLigS-DMwruR0dwAZ8oD2Q_270.JPG: 480x640 (no detections), 287.2ms
Speed: 1.1ms preprocess, 287.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLk-gcfV0Mhhtqggz7pdmg_0.JPG: 480x640 (no detections), 288.8ms
Speed: 1.0ms preprocess, 288.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLk-gcfV0Mhhtqggz7pdmg_90.JPG: 480x640 (no detections), 309.3ms
Speed: 1.2ms preprocess, 309.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLk-gcfV0Mhhtqggz7pdmg_180.JPG: 480x640 (no detections), 298.6ms
Speed: 1.1ms preprocess, 298.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLk-gcfV0Mhhtqggz7pdmg_270.JPG: 480x640 (no detections), 406.3ms
Speed: 1.3ms preprocess, 406.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLkNfqrtFRzKAjZjyAbWNA_0.JPG: 480x640 (no detections), 297.4ms
Speed: 1.2ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLkNfqrtFRzKAjZjyAbWNA_90.JPG: 480x640 (no detections), 307.2ms
Speed: 1.0ms preprocess, 307.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLkNfqrtFRzKAjZjyAbWNA_180.JPG: 480x640 (no detections), 314.5ms
Speed: 1.4ms preprocess, 314.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLkNfqrtFRzKAjZjyAbWNA_270.JPG: 480x640 (no detections), 297.4ms
Speed: 1.4ms preprocess, 297.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLme7fEMEgR9_k3NAzJnvw_0.JPG: 480x640 (no detections), 274.6ms
Speed: 1.1ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLme7fEMEgR9_k3NAzJnvw_90.JPG: 480x640 (no detections), 302.3ms
Speed: 1.1ms preprocess, 302.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLme7fEMEgR9_k3NAzJnvw_180.JPG: 480x640 (no detections), 276.7ms

Speed: 1.1ms preprocess, 276.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLme7fEMEgR9_k3NAzJnvw_270.JPG: 480x640 (no detections), 309.9ms
Speed: 1.0ms preprocess, 309.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLmiwvsTISI8D-Ac1W3yew_0.JPG: 480x640 (no detections), 283.1ms
Speed: 1.7ms preprocess, 283.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLmiwvsTISI8D-Ac1W3yew_90.JPG: 480x640 (no detections), 370.7ms
Speed: 1.0ms preprocess, 370.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLmiwvsTISI8D-Ac1W3yew_180.JPG: 480x640 (no detections), 278.5ms
Speed: 1.7ms preprocess, 278.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLmiwvsTISI8D-Ac1W3yew_270.JPG: 480x640 (no detections), 297.7ms
Speed: 1.1ms preprocess, 297.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLoshyVXgHKuTfWOfYhAaw_0.JPG: 480x640 (no detections), 300.2ms
Speed: 1.1ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLoshyVXgHKuTfWOfYhAaw_90.JPG: 480x640 (no detections), 276.5ms
Speed: 1.3ms preprocess, 276.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLoshyVXgHKuTfWOfYhAaw_180.JPG: 480x640 (no detections), 291.1ms
Speed: 1.2ms preprocess, 291.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLoshyVXgHKuTfWOfYhAaw_270.JPG: 480x640 (no detections), 276.3ms
Speed: 1.2ms preprocess, 276.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLp6rtDFXU0OrodUiWdWXw_0.JPG: 480x640 (no detections), 274.2ms
Speed: 1.0ms preprocess, 274.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLp6rtDFXU0OrodUiWdWXw_90.JPG: 480x640 (no detections), 287.2ms
Speed: 1.0ms preprocess, 287.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLp6rtDFXU0OrodUiWdWXw_180.JPG: 480x640 (no detections), 286.0ms
Speed: 1.3ms preprocess, 286.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLp6rtDFXU0OrodUiWdWXw_270.JPG: 480x640 (no detections), 306.4ms
Speed: 1.1ms preprocess, 306.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLtzLE_aE9szEE-31Vzpew_0.JPG: 480x640 (no detections), 285.0ms
Speed: 1.2ms preprocess, 285.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLtzLE_aE9szEE-31Vzpew_90.JPG: 480x640 (no detections), 272.9ms
Speed: 1.0ms preprocess, 272.9ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLtzLE_aE9szEE-31Vzpew_180.JPG: 480x640 (no detections), 265.2ms
Speed: 1.1ms preprocess, 265.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLtzLE_aE9szEE-31Vzpew_270.JPG: 480x640 (no detections), 277.3ms
Speed: 1.1ms preprocess, 277.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLuSn_YuB4OApHw6zXBDag_0.JPG: 480x640 (no detections), 295.9ms
Speed: 1.4ms preprocess, 295.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLuSn_YuB4OApHw6zXBDag_90.JPG: 480x640 (no detections), 295.0ms
Speed: 1.2ms preprocess, 295.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLuSn_YuB4OApHw6zXBDag_180.JPG: 480x640 (no detections), 280.9ms
Speed: 1.2ms preprocess, 280.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLuSn_YuB4OApHw6zXBDag_270.JPG: 480x640 (no detections), 275.3ms
Speed: 1.5ms preprocess, 275.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLzBaIYHdNRk1gNMJ20LJA_0.JPG: 480x640 (no detections), 275.0ms
Speed: 1.1ms preprocess, 275.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLzBaIYHdNRk1gNMJ20LJA_90.JPG: 480x640 (no detections), 282.4ms
Speed: 1.2ms preprocess, 282.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLzBaIYHdNRk1gNMJ20LJA_180.JPG: 480x640 (no detections), 281.7ms
Speed: 1.1ms preprocess, 281.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zLzBaIYHdNRk1gNMJ20LJA_270.JPG: 480x640 (no detections), 291.3ms
Speed: 1.3ms preprocess, 291.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zM0-8KVbCWFI_J9dm1N4_Q_0.JPG: 480x640 (no detections), 281.0ms
Speed: 1.1ms preprocess, 281.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zM0-8KVbCWFI_J9dm1N4_Q_90.JPG: 480x640 (no detections), 286.7ms
Speed: 1.1ms preprocess, 286.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zM0-8KVbCWFI_J9dm1N4_Q_180.JPG: 480x640 (no detections), 286.5ms
Speed: 1.0ms preprocess, 286.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zM0-8KVbCWFI_J9dm1N4_Q_270.JPG: 480x640 (no detections), 304.8ms
Speed: 1.2ms preprocess, 304.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zM7efoZIS2Nu2hTMpCV3jw_0.JPG: 480x640 (no detections), 294.0ms
Speed: 1.2ms preprocess, 294.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zM7efoZIS2Nu2hTMpCV3jw_90.JPG: 480x640 (no detections), 278.2ms
Speed: 1.0ms preprocess, 278.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zM7efoZIS2Nu2hTMpCV3jw_180.JPG: 480x640 (no detections), 273.2ms
Speed: 1.1ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zM7efoZIS2Nu2hTMpCV3jw_270.JPG: 480x640 (no detections), 281.1ms
Speed: 1.1ms preprocess, 281.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zM9fm2IiWYd5e-jbs9FRhA_0.JPG: 480x640 (no detections), 284.3ms
Speed: 1.2ms preprocess, 284.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zM9fm2IiWYd5e-jbs9FRhA_90.JPG: 480x640 (no detections), 273.0ms
Speed: 1.2ms preprocess, 273.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zM9fm2IiWYd5e-jbs9FRhA_180.JPG: 480x640 (no detections), 274.3ms
Speed: 1.0ms preprocess, 274.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zM9fm2IiWYd5e-jbs9FRhA_270.JPG: 480x640 (no detections), 272.3ms
Speed: 1.2ms preprocess, 272.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMAkq6LY9SCYJdpJWWPgVg_0.JPG: 480x640 (no detections), 271.6ms
Speed: 1.2ms preprocess, 271.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMAkq6LY9SCYJdpJWWPgVg_90.JPG: 480x640 (no detections), 267.0ms
Speed: 1.1ms preprocess, 267.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMAkq6LY9SCYJdpJWWPgVg_180.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMAkq6LY9SCYJdpJWWPgVg_270.JPG: 480x640 (no detections), 283.2ms
Speed: 1.1ms preprocess, 283.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMExzUUrQbdyhdUO7CNb3g_0.JPG: 480x640 (no detections), 300.1ms
Speed: 1.3ms preprocess, 300.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMExzUUrQbdyhdUO7CNb3g_90.JPG: 480x640 (no detections), 286.5ms
Speed: 1.5ms preprocess, 286.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMExzUUrQbdyhdUO7CNb3g_180.JPG: 480x640 1 Waste, 284.8ms
Speed: 1.1ms preprocess, 284.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMExzUUrQbdyhdUO7CNb3g_270.JPG: 480x640 (no detections), 286.8ms
Speed: 1.1ms preprocess, 286.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMF_wBvFtseruirHxHCqZw_0.JPG: 480x640 (no detections), 295.1ms
Speed: 1.4ms preprocess, 295.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMF_wBvFtseruirHxHCqZw_90.JPG: 480x640 (no detections), 283.8ms
Speed: 1.3ms preprocess, 283.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMF_wBvFtseruirHxHCqZw_180.JPG: 480x640 (no detections), 287.1ms
Speed: 1.3ms preprocess, 287.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMF_wBvFtseruirHxHCqZw_270.JPG: 480x640 (no detections), 289.0ms
Speed: 1.5ms preprocess, 289.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMGOEXkZsRlM16i-76qS0w_0.JPG: 480x640 (no detections), 296.4ms
Speed: 1.1ms preprocess, 296.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMGOEXkZsRlM16i-76qS0w_90.JPG: 480x640 (no detections), 341.7ms
Speed: 1.7ms preprocess, 341.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMGOEXkZsRlM16i-76qS0w_180.JPG: 480x640 (no detections), 327.6ms
Speed: 1.2ms preprocess, 327.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMGOEXkZsRlM16i-76qS0w_270.JPG: 480x640 (no detections), 314.0ms
Speed: 1.2ms preprocess, 314.0ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMGT2BfaG28wjelvxooc3Q_0.JPG: 480x640 (no detections), 312.0ms
Speed: 1.2ms preprocess, 312.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMGT2BfaG28wjelvxooc3Q_90.JPG: 480x640 (no detections), 334.8ms
Speed: 1.1ms preprocess, 334.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMGT2BfaG28wjelvxooc3Q_180.JPG: 480x640 (no detections), 321.6ms
Speed: 1.4ms preprocess, 321.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMGT2BfaG28wjelvxooc3Q_270.JPG: 480x640 (no detections), 341.0ms
Speed: 1.6ms preprocess, 341.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMJhOLnErl6Jt3CaH5vwug_0.JPG: 480x640 (no detections), 430.4ms
Speed: 1.6ms preprocess, 430.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMJhOLnErl6Jt3CaH5vwug_90.JPG: 480x640 (no detections), 339.7ms
Speed: 1.4ms preprocess, 339.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMJhOLnErl6Jt3CaH5vwug_180.JPG: 480x640 (no detections), 407.8ms
Speed: 2.4ms preprocess, 407.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMJhOLnErl6Jt3CaH5vwug_270.JPG: 480x640 (no detections), 331.0ms
Speed: 1.1ms preprocess, 331.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMKBdhUv63hxAwrVFx321A_0.JPG: 480x640 (no detections), 406.3ms
Speed: 1.3ms preprocess, 406.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMKBdhUv63hxAwrVFx321A_90.JPG: 480x640 (no detections), 320.4ms
Speed: 1.3ms preprocess, 320.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMKBdhUv63hxAwrVFx321A_180.JPG: 480x640 (no detections), 301.7ms
Speed: 1.2ms preprocess, 301.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMKBdhUv63hxAwrVFx321A_270.JPG: 480x640 (no detections), 274.7ms
Speed: 1.4ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMSkLmJ0IHAvfJj_9TYitQ_0.JPG: 480x640 (no detections), 279.8ms
Speed: 1.2ms preprocess, 279.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMSkLmJ0IHAvfJj_9TYitQ_90.JPG: 480x640 (no detections), 270.2ms

Speed: 1.2ms preprocess, 270.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMSkLmJ0IHAvfJj_9TYitQ_180.JPG: 480x640 (no detections), 271.1ms
Speed: 1.0ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMSkLmJ0IHAvfJj_9TYitQ_270.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMVVLnzO3Gfj9XJIQLvhBQ_0.JPG: 480x640 (no detections), 301.6ms
Speed: 1.1ms preprocess, 301.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMVVLnzO3Gfj9XJIQLvhBQ_90.JPG: 480x640 (no detections), 280.4ms
Speed: 1.1ms preprocess, 280.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMVVLnzO3Gfj9XJIQLvhBQ_180.JPG: 480x640 (no detections), 290.3ms
Speed: 1.1ms preprocess, 290.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMVVLnzO3Gfj9XJIQLvhBQ_270.JPG: 480x640 (no detections), 285.7ms
Speed: 1.2ms preprocess, 285.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMX1C91-kCB2u9yMrB7VrA_0.JPG: 480x640 (no detections), 302.6ms
Speed: 1.2ms preprocess, 302.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMX1C91-kCB2u9yMrB7VrA_90.JPG: 480x640 (no detections), 279.6ms
Speed: 1.2ms preprocess, 279.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMX1C91-kCB2u9yMrB7VrA_180.JPG: 480x640 (no detections), 268.0ms
Speed: 1.1ms preprocess, 268.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMX1C91-kCB2u9yMrB7VrA_270.JPG: 480x640 (no detections), 268.9ms
Speed: 1.1ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMX5o-A_ixxH585rRUgK9A_0.JPG: 480x640 (no detections), 286.6ms
Speed: 1.0ms preprocess, 286.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMX5o-A_ixxH585rRUgK9A_90.JPG: 480x640 (no detections), 291.4ms
Speed: 1.1ms preprocess, 291.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMX5o-A_ixxH585rRUgK9A_180.JPG: 480x640 (no detections), 298.8ms
Speed: 1.8ms preprocess, 298.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMX5o-A_ixxH585rRUgK9A_270.JPG: 480x640 (no detections), 279.2ms
Speed: 1.2ms preprocess, 279.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMXyNhRKptEMxDXVvT5Vwg_0.JPG: 480x640 (no detections), 296.4ms
Speed: 1.1ms preprocess, 296.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMXyNhRKptEMxDXVvT5Vwg_90.JPG: 480x640 (no detections), 280.6ms
Speed: 1.0ms preprocess, 280.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMXyNhRKptEMxDXVvT5Vwg_180.JPG: 480x640 (no detections), 282.5ms
Speed: 1.0ms preprocess, 282.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMXyNhRKptEMxDXVvT5Vwg_270.JPG: 480x640 (no detections), 275.8ms
Speed: 1.2ms preprocess, 275.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMblXO4mqFJCol__t51k7A_0.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMblXO4mqFJCol__t51k7A_90.JPG: 480x640 (no detections), 284.1ms
Speed: 1.0ms preprocess, 284.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMblXO4mqFJCol__t51k7A_180.JPG: 480x640 (no detections), 275.6ms
Speed: 1.1ms preprocess, 275.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMblXO4mqFJCol__t51k7A_270.JPG: 480x640 (no detections), 331.7ms
Speed: 1.5ms preprocess, 331.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMmeo4TQznxsE40yO3QO7Q_0.JPG: 480x640 (no detections), 266.1ms
Speed: 1.2ms preprocess, 266.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMmeo4TQznxsE40yO3QO7Q_90.JPG: 480x640 (no detections), 336.7ms
Speed: 1.1ms preprocess, 336.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMmeo4TQznxsE40yO3QO7Q_180.JPG: 480x640 (no detections), 294.6ms
Speed: 1.4ms preprocess, 294.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMmeo4TQznxsE40yO3QO7Q_270.JPG: 480x640 (no detections), 271.5ms
Speed: 1.1ms preprocess, 271.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMne73qxQTBOuoRgvbVu4Q_0.JPG: 480x640 (no detections), 291.0ms
Speed: 1.0ms preprocess, 291.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMne73qxQTBOuoRgvbVu4Q_90.JPG: 480x640 (no detections), 291.8ms
Speed: 1.1ms preprocess, 291.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMne73qxQTBOuoRgvbVu4Q_180.JPG: 480x640 (no detections), 308.3ms
Speed: 1.1ms preprocess, 308.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMne73qxQTBOuoRgvbVu4Q_270.JPG: 480x640 (no detections), 320.5ms
Speed: 1.9ms preprocess, 320.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMogg5fBj5j_GID6ZLFaKg_0.JPG: 480x640 (no detections), 336.6ms
Speed: 1.2ms preprocess, 336.6ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMogg5fBj5j_GID6ZLFaKg_90.JPG: 480x640 (no detections), 302.6ms
Speed: 1.3ms preprocess, 302.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMogg5fBj5j_GID6ZLFaKg_180.JPG: 480x640 (no detections), 281.1ms
Speed: 1.3ms preprocess, 281.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMogg5fBj5j_GID6ZLFaKg_270.JPG: 480x640 (no detections), 299.2ms
Speed: 1.2ms preprocess, 299.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMrUN4zv1kPto1DM0UhaOQ_0.JPG: 480x640 (no detections), 275.2ms
Speed: 1.0ms preprocess, 275.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMrUN4zv1kPto1DM0UhaOQ_90.JPG: 480x640 (no detections), 294.0ms
Speed: 1.1ms preprocess, 294.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMrUN4zv1kPto1DM0UhaOQ_180.JPG: 480x640 (no detections), 289.8ms
Speed: 1.3ms preprocess, 289.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMrUN4zv1kPto1DM0UhaOQ_270.JPG: 480x640 (no detections), 290.1ms
Speed: 1.4ms preprocess, 290.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMsDISwU45YYTY8CmLduPA_0.JPG: 480x640 (no detections), 287.3ms
Speed: 1.1ms preprocess, 287.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMsDISwU45YYTY8CmLduPA_90.JPG: 480x640 (no detections), 284.9ms
Speed: 1.4ms preprocess, 284.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMsDISwU45YYTY8CmLduPA_180.JPG: 480x640 (no detections), 290.3ms
Speed: 1.1ms preprocess, 290.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMsDISwU45YYTY8CmLduPA_270.JPG: 480x640 (no detections), 305.0ms
Speed: 1.2ms preprocess, 305.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMsX3ec-50exfcC-0hc3cw_0.JPG: 480x640 (no detections), 287.0ms
Speed: 1.5ms preprocess, 287.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMsX3ec-50exfcC-0hc3cw_90.JPG: 480x640 (no detections), 311.4ms
Speed: 1.5ms preprocess, 311.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMsX3ec-50exfcC-0hc3cw_180.JPG: 480x640 (no detections), 288.5ms
Speed: 1.3ms preprocess, 288.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMsX3ec-50exfcC-0hc3cw_270.JPG: 480x640 (no detections), 313.6ms
Speed: 1.3ms preprocess, 313.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMvKoiezEkFONjyYJ6jziA_0.JPG: 480x640 (no detections), 289.3ms
Speed: 1.0ms preprocess, 289.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMvKoiezEkFONjyYJ6jziA_90.JPG: 480x640 (no detections), 312.9ms
Speed: 1.2ms preprocess, 312.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMvKoiezEkFONjyYJ6jziA_180.JPG: 480x640 (no detections), 270.3ms
Speed: 1.2ms preprocess, 270.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMvKoiezEkFONjyYJ6jziA_270.JPG: 480x640 (no detections), 283.5ms
Speed: 1.1ms preprocess, 283.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMxjC1FQEyIk7DaTlzzlpA_0.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMxjC1FQEyIk7DaTlzzlpA_90.JPG: 480x640 (no detections), 279.9ms
Speed: 1.2ms preprocess, 279.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMxjC1FQEyIk7DaTlzzlpA_180.JPG: 480x640 (no detections), 283.8ms
Speed: 2.1ms preprocess, 283.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMxjC1FQEyIk7DaTlzzlpA_270.JPG: 480x640 (no detections), 264.7ms
Speed: 1.1ms preprocess, 264.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMzYO8cLzGr5_MXvjjchEw_0.JPG: 480x640 (no detections), 272.8ms
Speed: 1.2ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMzYO8cLzGr5_MXvjjchEw_90.JPG: 480x640 (no detections), 272.9ms
Speed: 1.0ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMzYO8cLzGr5_MXvjjchEw_180.JPG: 480x640 (no detections), 270.7ms
Speed: 1.0ms preprocess, 270.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMzYO8cLzGr5_MXvjjchEw_270.JPG: 480x640 (no detections), 267.3ms
Speed: 1.0ms preprocess, 267.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMzsFi9wm75l_MzJ-DLD0g_0.JPG: 480x640 (no detections), 268.7ms
Speed: 1.2ms preprocess, 268.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMzsFi9wm75l_MzJ-DLD0g_90.JPG: 480x640 (no detections), 271.9ms
Speed: 1.0ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMzsFi9wm75l_MzJ-DLD0g_180.JPG: 480x640 (no detections), 268.5ms
Speed: 1.0ms preprocess, 268.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zMzsFi9wm75l_MzJ-DLD0g_270.JPG: 480x640 (no detections), 272.4ms
Speed: 1.0ms preprocess, 272.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zN6KtjtSp1ohpZ9G9nwF3A_0.JPG: 480x640 (no detections), 272.6ms
Speed: 1.2ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zN6KtjtSp1ohpZ9G9nwF3A_90.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zN6KtjtSp1ohpZ9G9nwF3A_180.JPG: 480x640 (no detections), 272.5ms
Speed: 1.0ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zN6KtjtSp1ohpZ9G9nwF3A_270.JPG: 480x640 (no detections), 272.7ms
Speed: 1.0ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zN7cDpp4ikT_c6OIF1sCaw_0.JPG: 480x640 (no detections), 268.0ms

Speed: 1.1ms preprocess, 268.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zN7cDpp4ikT_c6OIF1sCaw_90.JPG: 480x640 (no detections), 269.2ms
Speed: 1.0ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zN7cDpp4ikT_c6OIF1sCaw_180.JPG: 480x640 (no detections), 275.4ms
Speed: 1.0ms preprocess, 275.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zN7cDpp4ikT_c6OIF1sCaw_270.JPG: 480x640 (no detections), 272.5ms
Speed: 1.2ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zN8p4mGIBnlG1ZG4iaUlwQ_0.JPG: 480x640 (no detections), 272.2ms
Speed: 1.5ms preprocess, 272.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zN8p4mGIBnlG1ZG4iaUlwQ_90.JPG: 480x640 (no detections), 268.4ms
Speed: 1.1ms preprocess, 268.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zN8p4mGIBnlG1ZG4iaUlwQ_180.JPG: 480x640 (no detections), 274.8ms
Speed: 1.1ms preprocess, 274.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zN8p4mGIBnlG1ZG4iaUlwQ_270.JPG: 480x640 (no detections), 269.9ms
Speed: 1.0ms preprocess, 269.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zN95BNC6k7CFEJq_fJjreA_0.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zN95BNC6k7CFEJq_fJjreA_90.JPG: 480x640 (no detections), 275.1ms
Speed: 1.0ms preprocess, 275.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zN95BNC6k7CFEJq_fJjreA_180.JPG: 480x640 (no detections), 274.7ms
Speed: 1.0ms preprocess, 274.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zN95BNC6k7CFEJq_fJjreA_270.JPG: 480x640 (no detections), 270.3ms
Speed: 1.1ms preprocess, 270.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNAFfAxRH8Q7B6MylsysgQ_0.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNAFfAxRH8Q7B6MylsysgQ_90.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNAFfAxRH8Q7B6MylsysgQ_180.JPG: 480x640 (no detections), 274.4ms
Speed: 1.0ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNAFfAxRH8Q7B6MylsysgQ_270.JPG: 480x640 (no detections), 270.8ms
Speed: 1.0ms preprocess, 270.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNFHqIYBiIFJ7NIRwofE6A_0.JPG: 480x640 (no detections), 278.7ms
Speed: 1.1ms preprocess, 278.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNFHqIYBiIFJ7NIRwofE6A_90.JPG: 480x640 (no detections), 270.9ms
Speed: 1.0ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNFHqIYBiIFJ7NIRwofE6A_180.JPG: 480x640 (no detections), 270.9ms
Speed: 1.0ms preprocess, 270.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNFHqIYBiIFJ7NIRwofE6A_270.JPG: 480x640 (no detections), 275.1ms
Speed: 1.0ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNNDA_8ILT9zMyCjVFmwtQ_0.JPG: 480x640 2 Wastes, 268.6ms
Speed: 1.0ms preprocess, 268.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNNDA_8ILT9zMyCjVFmwtQ_90.JPG: 480x640 (no detections), 275.0ms
Speed: 1.1ms preprocess, 275.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNNDA_8ILT9zMyCjVFmwtQ_180.JPG: 480x640 (no detections), 274.5ms
Speed: 1.0ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNNDA_8ILT9zMyCjVFmwtQ_270.JPG: 480x640 (no detections), 277.2ms
Speed: 1.1ms preprocess, 277.2ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNNmHWwje0XLgPgJhPDfSA_0.JPG: 480x640 (no detections), 274.1ms
Speed: 1.2ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNNmHWwje0XLgPgJhPDfSA_90.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNNmHWwje0XLgPgJhPDfSA_180.JPG: 480x640 (no detections), 274.7ms
Speed: 1.0ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNNmHWwje0XLgPgJhPDfSA_270.JPG: 480x640 (no detections), 274.3ms
Speed: 1.1ms preprocess, 274.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNUkkzDk80DRXivUWOmufQ_0.JPG: 480x640 1 Waste, 270.3ms
Speed: 1.2ms preprocess, 270.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNUkkzDk80DRXivUWOmufQ_90.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNUkkzDk80DRXivUWOmufQ_180.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNUkkzDk80DRXivUWOmufQ_270.JPG: 480x640 (no detections), 273.1ms
Speed: 1.1ms preprocess, 273.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNWTQatzKGwDQRRFAsLpWA_0.JPG: 480x640 (no detections), 269.8ms
Speed: 1.1ms preprocess, 269.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNWTQatzKGwDQRRFAsLpWA_90.JPG: 480x640 (no detections), 274.0ms
Speed: 1.0ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNWTQatzKGwDQRRFAsLpWA_180.JPG: 480x640 (no detections), 273.9ms
Speed: 1.1ms preprocess, 273.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNWTQatzKGwDQRRFAsLpWA_270.JPG: 480x640 (no detections), 272.4ms
Speed: 1.1ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNXEfgVBt1x8cqbVjvOYHA_0.JPG: 480x640 (no detections), 272.1ms
Speed: 1.1ms preprocess, 272.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNXEfgVBt1x8cqbVjvOYHA_90.JPG: 480x640 (no detections), 274.9ms
Speed: 1.1ms preprocess, 274.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNXEfgVBt1x8cqbVjvOYHA_180.JPG: 480x640 (no detections), 268.6ms
Speed: 1.0ms preprocess, 268.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNXEfgVBt1x8cqbVjvOYHA_270.JPG: 480x640 (no detections), 272.4ms
Speed: 1.1ms preprocess, 272.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNXRNkvhXMaTpH6M-2DbdQ_0.JPG: 480x640 (no detections), 269.8ms
Speed: 1.0ms preprocess, 269.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNXRNkvhXMaTpH6M-2DbdQ_90.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNXRNkvhXMaTpH6M-2DbdQ_180.JPG: 480x640 (no detections), 297.2ms
Speed: 1.1ms preprocess, 297.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNXRNkvhXMaTpH6M-2DbdQ_270.JPG: 480x640 (no detections), 268.0ms
Speed: 1.0ms preprocess, 268.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNYe86KvURfTcsdHjPcFYA_0.JPG: 480x640 (no detections), 269.7ms
Speed: 1.0ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNYe86KvURfTcsdHjPcFYA_90.JPG: 480x640 1 Waste, 274.5ms
Speed: 1.0ms preprocess, 274.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNYe86KvURfTcsdHjPcFYA_180.JPG: 480x640 1 Waste, 274.9ms
Speed: 1.1ms preprocess, 274.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNYe86KvURfTcsdHjPcFYA_270.JPG: 480x640 (no detections), 272.0ms
Speed: 1.1ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNZbhqVEvmvvYoCwgCbmAg_0.JPG: 480x640 (no detections), 269.2ms
Speed: 1.1ms preprocess, 269.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNZbhqVEvmvvYoCwgCbmAg_90.JPG: 480x640 (no detections), 275.3ms
Speed: 1.1ms preprocess, 275.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNZbhqVEvmvvYoCwgCbmAg_180.JPG: 480x640 (no detections), 278.6ms
Speed: 1.2ms preprocess, 278.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNZbhqVEvmvvYoCwgCbmAg_270.JPG: 480x640 (no detections), 279.5ms
Speed: 1.2ms preprocess, 279.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zN_DwvapdMd2ce2jJtdzfA_0.JPG: 480x640 (no detections), 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zN_DwvapdMd2ce2jJtdzfA_90.JPG: 480x640 (no detections), 275.3ms
Speed: 1.0ms preprocess, 275.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zN_DwvapdMd2ce2jJtdzfA_180.JPG: 480x640 (no detections), 276.4ms
Speed: 1.1ms preprocess, 276.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zN_DwvapdMd2ce2jJtdzfA_270.JPG: 480x640 (no detections), 272.2ms
Speed: 1.0ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNb2z9kOiHhcKjnqWtcUiA_0.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNb2z9kOiHhcKjnqWtcUiA_90.JPG: 480x640 1 Waste, 273.1ms
Speed: 1.3ms preprocess, 273.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNb2z9kOiHhcKjnqWtcUiA_180.JPG: 480x640 (no detections), 270.9ms
Speed: 1.2ms preprocess, 270.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNb2z9kOiHhcKjnqWtcUiA_270.JPG: 480x640 (no detections), 271.3ms
Speed: 1.0ms preprocess, 271.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNc7x9n2JKbCOd-0XpvnxQ_0.JPG: 480x640 (no detections), 273.2ms
Speed: 1.3ms preprocess, 273.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNc7x9n2JKbCOd-0XpvnxQ_90.JPG: 480x640 1 Waste, 275.9ms
Speed: 1.2ms preprocess, 275.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNc7x9n2JKbCOd-0XpvnxQ_180.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNc7x9n2JKbCOd-0XpvnxQ_270.JPG: 480x640 (no detections), 273.6ms
Speed: 1.1ms preprocess, 273.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNcHIHmY8oknGsJS6lbtcA_0.JPG: 480x640 (no detections), 272.3ms
Speed: 1.2ms preprocess, 272.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNcHIHmY8oknGsJS6lbtcA_90.JPG: 480x640 (no detections), 266.8ms
Speed: 1.1ms preprocess, 266.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNcHIHmY8oknGsJS6lbtcA_180.JPG: 480x640 (no detections), 277.5ms
Speed: 1.1ms preprocess, 277.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNcHIHmY8oknGsJS6lbtcA_270.JPG: 480x640 (no detections), 271.8ms

Speed: 1.0ms preprocess, 271.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNdPGBdJVv2ErYUICdUhVg_0.JPG: 480x640 1 Waste, 271.3ms
Speed: 1.0ms preprocess, 271.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNdPGBdJVv2ErYUICdUhVg_90.JPG: 480x640 (no detections), 272.6ms
Speed: 1.0ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNdPGBdJVv2ErYUICdUhVg_180.JPG: 480x640 (no detections), 270.5ms
Speed: 1.0ms preprocess, 270.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNdPGBdJVv2ErYUICdUhVg_270.JPG: 480x640 3 Wastes, 274.4ms
Speed: 1.1ms preprocess, 274.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNk2OroxSkVWS9g-XFcofw_0.JPG: 480x640 (no detections), 270.4ms
Speed: 1.0ms preprocess, 270.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNk2OroxSkVWS9g-XFcofw_90.JPG: 480x640 (no detections), 275.3ms
Speed: 1.2ms preprocess, 275.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNk2OroxSkVWS9g-XFcofw_180.JPG: 480x640 (no detections), 274.3ms
Speed: 1.1ms preprocess, 274.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNk2OroxSkVWS9g-XFcofw_270.JPG: 480x640 (no detections), 278.7ms
Speed: 1.0ms preprocess, 278.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNm7GT3hJkT-QvyYCDZfCA_0.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNm7GT3hJkT-QvyYCDZfCA_90.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNm7GT3hJkT-QvyYCDZfCA_180.JPG: 480x640 (no detections), 271.0ms
Speed: 1.0ms preprocess, 271.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNm7GT3hJkT-QvyYCDZfCA_270.JPG: 480x640 (no detections), 267.4ms
Speed: 1.0ms preprocess, 267.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNnT9ADQhar3freu9JAa-g_0.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNnT9ADQhar3freu9JAa-g_90.JPG: 480x640 (no detections), 274.3ms
Speed: 1.1ms preprocess, 274.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNnT9ADQhar3freu9JAa-g_180.JPG: 480x640 (no detections), 272.0ms
Speed: 1.0ms preprocess, 272.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNnT9ADQhar3freu9JAa-g_270.JPG: 480x640 (no detections), 270.4ms
Speed: 1.1ms preprocess, 270.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNpBopsz2_tvfGkdX7kyqA_0.JPG: 480x640 (no detections), 269.4ms
Speed: 1.1ms preprocess, 269.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNpBopsz2_tvfGkdX7kyqA_90.JPG: 480x640 (no detections), 271.9ms
Speed: 1.0ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNpBopsz2_tvfGkdX7kyqA_180.JPG: 480x640 1 Waste, 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNpBopsz2_tvfGkdX7kyqA_270.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNrLQh-crQ08a3fKWw4Opg_0.JPG: 480x640 (no detections), 270.8ms
Speed: 1.0ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNrLQh-crQ08a3fKWw4Opg_90.JPG: 480x640 (no detections), 273.4ms
Speed: 1.0ms preprocess, 273.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNrLQh-crQ08a3fKWw4Opg_180.JPG: 480x640 (no detections), 274.8ms
Speed: 1.0ms preprocess, 274.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNrLQh-crQ08a3fKWw4Opg_270.JPG: 480x640 (no detections), 275.4ms
Speed: 1.2ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNsTkzpdMpVP2hPeaBilQA_0.JPG: 480x640 (no detections), 273.6ms
Speed: 1.1ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNsTkzpdMpVP2hPeaBilQA_90.JPG: 480x640 (no detections), 268.9ms
Speed: 1.1ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNsTkzpdMpVP2hPeaBilQA_180.JPG: 480x640 (no detections), 266.8ms
Speed: 1.1ms preprocess, 266.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNsTkzpdMpVP2hPeaBilQA_270.JPG: 480x640 (no detections), 277.8ms
Speed: 1.1ms preprocess, 277.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNtmFqO3UGs5I5jQVsecYA_0.JPG: 480x640 (no detections), 269.3ms
Speed: 1.1ms preprocess, 269.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNtmFqO3UGs5I5jQVsecYA_90.JPG: 480x640 (no detections), 273.9ms
Speed: 1.0ms preprocess, 273.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNtmFqO3UGs5I5jQVsecYA_180.JPG: 480x640 (no detections), 270.9ms
Speed: 1.0ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNtmFqO3UGs5I5jQVsecYA_270.JPG: 480x640 (no detections), 272.9ms
Speed: 1.0ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNx0UQ2-y-MzMmuJsi9plA_0.JPG: 480x640 (no detections), 268.7ms
Speed: 1.1ms preprocess, 268.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNx0UQ2-y-MzMmuJsi9plA_90.JPG: 480x640 (no detections), 273.0ms
Speed: 1.2ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNx0UQ2-y-MzMmuJsi9plA_180.JPG: 480x640 (no detections), 271.7ms
Speed: 1.0ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNx0UQ2-y-MzMmuJsi9plA_270.JPG: 480x640 (no detections), 273.3ms
Speed: 1.4ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNyynaY1a6rsSNYMN2P3wg_0.JPG: 480x640 (no detections), 276.0ms
Speed: 1.2ms preprocess, 276.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNyynaY1a6rsSNYMN2P3wg_90.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNyynaY1a6rsSNYMN2P3wg_180.JPG: 480x640 (no detections), 272.1ms
Speed: 1.1ms preprocess, 272.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zNyynaY1a6rsSNYMN2P3wg_270.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zO0cgbZuNWPSjbu9VfLg6g_0.JPG: 480x640 (no detections), 275.2ms
Speed: 1.2ms preprocess, 275.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zO0cgbZuNWPSjbu9VfLg6g_90.JPG: 480x640 (no detections), 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zO0cgbZuNWPSjbu9VfLg6g_180.JPG: 480x640 (no detections), 270.8ms
Speed: 1.0ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zO0cgbZuNWPSjbu9VfLg6g_270.JPG: 480x640 (no detections), 273.9ms
Speed: 1.1ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zO32U7BaZHDlDUWCi4gOJw_0.JPG: 480x640 (no detections), 266.6ms
Speed: 1.1ms preprocess, 266.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zO32U7BaZHDlDUWCi4gOJw_90.JPG: 480x640 (no detections), 273.1ms
Speed: 1.2ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zO32U7BaZHDlDUWCi4gOJw_180.JPG: 480x640 (no detections), 272.8ms
Speed: 1.0ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zO32U7BaZHDlDUWCi4gOJw_270.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zO33Da72r-rswbX7pKmd9g_0.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zO33Da72r-rswbX7pKmd9g_90.JPG: 480x640 (no detections), 264.3ms
Speed: 1.0ms preprocess, 264.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zO33Da72r-rswbX7pKmd9g_180.JPG: 480x640 (no detections), 266.8ms
Speed: 1.0ms preprocess, 266.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zO33Da72r-rswbX7pKmd9g_270.JPG: 480x640 (no detections), 269.2ms
Speed: 1.2ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zO4thaJkmxSVQ0VN69Wuqw_0.JPG: 480x640 (no detections), 274.2ms
Speed: 1.2ms preprocess, 274.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zO4thaJkmxSVQ0VN69Wuqw_90.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zO4thaJkmxSVQ0VN69Wuqw_180.JPG: 480x640 (no detections), 283.7ms
Speed: 1.2ms preprocess, 283.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zO4thaJkmxSVQ0VN69Wuqw_270.JPG: 480x640 (no detections), 272.4ms
Speed: 1.1ms preprocess, 272.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zO6Tqre_WdwqA9_w9kAGOA_0.JPG: 480x640 (no detections), 279.5ms
Speed: 1.1ms preprocess, 279.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zO6Tqre_WdwqA9_w9kAGOA_90.JPG: 480x640 (no detections), 270.8ms
Speed: 1.2ms preprocess, 270.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zO6Tqre_WdwqA9_w9kAGOA_180.JPG: 480x640 (no detections), 271.8ms
Speed: 1.0ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zO6Tqre_WdwqA9_w9kAGOA_270.JPG: 480x640 (no detections), 283.1ms
Speed: 1.6ms preprocess, 283.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zO6_xueZPR1uIVne_Fs9hw_0.JPG: 480x640 (no detections), 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zO6_xueZPR1uIVne_Fs9hw_90.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zO6_xueZPR1uIVne_Fs9hw_180.JPG: 480x640 (no detections), 276.3ms
Speed: 1.0ms preprocess, 276.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zO6_xueZPR1uIVne_Fs9hw_270.JPG: 480x640 (no detections), 281.8ms
Speed: 1.1ms preprocess, 281.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zO75vZfCoyJa5pRRvqG6sw_0.JPG: 480x640 (no detections), 274.4ms
Speed: 1.1ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zO75vZfCoyJa5pRRvqG6sw_90.JPG: 480x640 (no detections), 333.4ms
Speed: 1.1ms preprocess, 333.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zO75vZfCoyJa5pRRvqG6sw_180.JPG: 480x640 (no detections), 345.8ms

Speed: 1.3ms preprocess, 345.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zO75vZfCoyJa5pRRvqG6sw_270.JPG: 480x640 (no detections), 270.6ms
Speed: 1.3ms preprocess, 270.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zO84B3mlPp4fj09uTq0LFA_0.JPG: 480x640 (no detections), 271.4ms
Speed: 1.3ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zO84B3mlPp4fj09uTq0LFA_90.JPG: 480x640 (no detections), 276.9ms
Speed: 1.1ms preprocess, 276.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zO84B3mlPp4fj09uTq0LFA_180.JPG: 480x640 (no detections), 271.9ms
Speed: 1.4ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zO84B3mlPp4fj09uTq0LFA_270.JPG: 480x640 (no detections), 272.3ms
Speed: 1.1ms preprocess, 272.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zO90rdZb9pqbOIx7-mgVmQ_0.JPG: 480x640 (no detections), 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zO90rdZb9pqbOIx7-mgVmQ_90.JPG: 480x640 (no detections), 268.7ms
Speed: 1.3ms preprocess, 268.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zO90rdZb9pqbOIx7-mgVmQ_180.JPG: 480x640 (no detections), 270.8ms
Speed: 1.2ms preprocess, 270.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zO90rdZb9pqbOIx7-mgVmQ_270.JPG: 480x640 (no detections), 275.7ms
Speed: 1.1ms preprocess, 275.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOAJdjKtHeMU9okX3LdOVQ_0.JPG: 480x640 (no detections), 275.0ms
Speed: 1.2ms preprocess, 275.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOAJdjKtHeMU9okX3LdOVQ_90.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOAJdjKtHeMU9okX3LdOVQ_180.JPG: 480x640 (no detections), 275.9ms
Speed: 1.2ms preprocess, 275.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOAJdjKtHeMU9okX3LdOVQ_270.JPG: 480x640 (no detections), 272.9ms
Speed: 1.2ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOBXoKzJgPCn3x3K0X9F0Q_0.JPG: 480x640 (no detections), 271.0ms
Speed: 1.2ms preprocess, 271.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOBXoKzJgPCn3x3K0X9F0Q_90.JPG: 480x640 (no detections), 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOBXoKzJgPCn3x3K0X9F0Q_180.JPG: 480x640 (no detections), 271.6ms
Speed: 1.2ms preprocess, 271.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOBXoKzJgPCn3x3K0X9F0Q_270.JPG: 480x640 (no detections), 268.0ms
Speed: 1.1ms preprocess, 268.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOEwUu3QF737Iyge1XQSdA_0.JPG: 480x640 (no detections), 274.6ms
Speed: 1.0ms preprocess, 274.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOEwUu3QF737Iyge1XQSdA_90.JPG: 480x640 (no detections), 272.2ms
Speed: 1.0ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOEwUu3QF737Iyge1XQSdA_180.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOEwUu3QF737Iyge1XQSdA_270.JPG: 480x640 (no detections), 273.1ms
Speed: 1.1ms preprocess, 273.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOFgMK1wG-9HUQpIvUJtOw_0.JPG: 480x640 (no detections), 278.8ms
Speed: 1.2ms preprocess, 278.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOFgMK1wG-9HUQpIvUJtOw_90.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOFgMK1wG-9HUQpIvUJtOw_180.JPG: 480x640 (no detections), 274.8ms
Speed: 1.1ms preprocess, 274.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOFgMK1wG-9HUQpIvUJtOw_270.JPG: 480x640 (no detections), 274.6ms
Speed: 1.0ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOFziINxfLUNS75ER0CagQ_0.JPG: 480x640 (no detections), 277.8ms
Speed: 1.1ms preprocess, 277.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOFziINxfLUNS75ER0CagQ_90.JPG: 480x640 (no detections), 277.1ms
Speed: 1.2ms preprocess, 277.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOFziINxfLUNS75ER0CagQ_180.JPG: 480x640 (no detections), 276.4ms
Speed: 1.7ms preprocess, 276.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOFziINxfLUNS75ER0CagQ_270.JPG: 480x640 (no detections), 273.9ms
Speed: 1.1ms preprocess, 273.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOJ801HwiLHJz4r5jnJuIg_0.JPG: 480x640 (no detections), 277.6ms
Speed: 1.0ms preprocess, 277.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOJ801HwiLHJz4r5jnJuIg_90.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOJ801HwiLHJz4r5jnJuIg_180.JPG: 480x640 (no detections), 275.9ms
Speed: 1.0ms preprocess, 275.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOJ801HwiLHJz4r5jnJuIg_270.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zONwi9y5BI1VLSmDknnllw_0.JPG: 480x640 (no detections), 275.6ms
Speed: 1.1ms preprocess, 275.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zONwi9y5BI1VLSmDknnllw_90.JPG: 480x640 (no detections), 277.7ms
Speed: 1.1ms preprocess, 277.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zONwi9y5BI1VLSmDknnllw_180.JPG: 480x640 (no detections), 275.7ms
Speed: 1.1ms preprocess, 275.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zONwi9y5BI1VLSmDknnllw_270.JPG: 480x640 (no detections), 278.1ms
Speed: 1.1ms preprocess, 278.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOOAwI_3WoMoFYD7yBrCQg_0.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOOAwI_3WoMoFYD7yBrCQg_90.JPG: 480x640 (no detections), 272.6ms
Speed: 1.0ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOOAwI_3WoMoFYD7yBrCQg_180.JPG: 480x640 (no detections), 278.1ms
Speed: 1.1ms preprocess, 278.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOOAwI_3WoMoFYD7yBrCQg_270.JPG: 480x640 (no detections), 271.1ms
Speed: 1.0ms preprocess, 271.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOPCLIfGsUWuAsiAqQKmpg_0.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOPCLIfGsUWuAsiAqQKmpg_90.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOPCLIfGsUWuAsiAqQKmpg_180.JPG: 480x640 (no detections), 276.4ms
Speed: 1.1ms preprocess, 276.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOPCLIfGsUWuAsiAqQKmpg_270.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOSe0XlzgD4R85GfydPzlA_0.JPG: 480x640 (no detections), 271.2ms
Speed: 1.0ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOSe0XlzgD4R85GfydPzlA_90.JPG: 480x640 (no detections), 272.4ms
Speed: 1.0ms preprocess, 272.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOSe0XlzgD4R85GfydPzlA_180.JPG: 480x640 (no detections), 274.2ms
Speed: 1.0ms preprocess, 274.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOSe0XlzgD4R85GfydPzlA_270.JPG: 480x640 (no detections), 277.7ms
Speed: 1.1ms preprocess, 277.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOVxCDl3Pcu7fPNII4vBLQ_0.JPG: 480x640 (no detections), 277.8ms
Speed: 1.0ms preprocess, 277.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOVxCDl3Pcu7fPNII4vBLQ_90.JPG: 480x640 (no detections), 276.8ms
Speed: 1.0ms preprocess, 276.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOVxCDl3Pcu7fPNII4vBLQ_180.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOVxCDl3Pcu7fPNII4vBLQ_270.JPG: 480x640 (no detections), 272.0ms
Speed: 1.0ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOVxmLGHO9NUcGZL3Yf8NA_0.JPG: 480x640 (no detections), 269.5ms
Speed: 1.1ms preprocess, 269.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOVxmLGHO9NUcGZL3Yf8NA_90.JPG: 480x640 (no detections), 271.4ms
Speed: 1.0ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOVxmLGHO9NUcGZL3Yf8NA_180.JPG: 480x640 (no detections), 275.9ms
Speed: 1.0ms preprocess, 275.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOVxmLGHO9NUcGZL3Yf8NA_270.JPG: 480x640 (no detections), 274.5ms
Speed: 1.0ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOWr8XFYgMbUlUs3lgRjTw_0.JPG: 480x640 (no detections), 270.1ms
Speed: 1.0ms preprocess, 270.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOWr8XFYgMbUlUs3lgRjTw_90.JPG: 480x640 (no detections), 274.9ms
Speed: 1.0ms preprocess, 274.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOWr8XFYgMbUlUs3lgRjTw_180.JPG: 480x640 (no detections), 277.8ms
Speed: 1.5ms preprocess, 277.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOWr8XFYgMbUlUs3lgRjTw_270.JPG: 480x640 (no detections), 274.8ms
Speed: 1.1ms preprocess, 274.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOXwCLz6OAnkfDvnXu0NyQ_0.JPG: 480x640 (no detections), 269.7ms
Speed: 1.2ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOXwCLz6OAnkfDvnXu0NyQ_90.JPG: 480x640 (no detections), 274.6ms
Speed: 1.2ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOXwCLz6OAnkfDvnXu0NyQ_180.JPG: 480x640 (no detections), 273.4ms
Speed: 1.1ms preprocess, 273.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOXwCLz6OAnkfDvnXu0NyQ_270.JPG: 480x640 (no detections), 270.1ms
Speed: 1.0ms preprocess, 270.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zO_pj63FciBinTOsj010eQ_0.JPG: 480x640 (no detections), 272.5ms
Speed: 1.2ms preprocess, 272.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zO_pj63FciBinTOsj010eQ_90.JPG: 480x640 (no detections), 282.7ms

Speed: 1.0ms preprocess, 282.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zO_pj63FciBinTOsj010eQ_180.JPG: 480x640 2 Wastes, 275.9ms
Speed: 1.1ms preprocess, 275.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zO_pj63FciBinTOsj010eQ_270.JPG: 480x640 (no detections), 277.7ms
Speed: 1.3ms preprocess, 277.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zObUYT6QqaC2FL771E0liQ_0.JPG: 480x640 (no detections), 287.3ms
Speed: 1.0ms preprocess, 287.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zObUYT6QqaC2FL771E0liQ_90.JPG: 480x640 (no detections), 273.1ms
Speed: 1.1ms preprocess, 273.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zObUYT6QqaC2FL771E0liQ_180.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zObUYT6QqaC2FL771E0liQ_270.JPG: 480x640 (no detections), 277.0ms
Speed: 1.1ms preprocess, 277.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zObt9sLsUfH7kegbF1X74A_0.JPG: 480x640 (no detections), 284.0ms
Speed: 1.1ms preprocess, 284.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zObt9sLsUfH7kegbF1X74A_90.JPG: 480x640 1 Waste, 291.0ms
Speed: 1.3ms preprocess, 291.0ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zObt9sLsUfH7kegbF1X74A_180.JPG: 480x640 (no detections), 298.5ms
Speed: 1.2ms preprocess, 298.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zObt9sLsUfH7kegbF1X74A_270.JPG: 480x640 (no detections), 307.6ms
Speed: 1.1ms preprocess, 307.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOgrrQS7xJKXJexQOOmKKQ_0.JPG: 480x640 (no detections), 303.8ms
Speed: 1.4ms preprocess, 303.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOgrrQS7xJKXJexQOOmKKQ_90.JPG: 480x640 (no detections), 280.3ms
Speed: 1.1ms preprocess, 280.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOgrrQS7xJKXJexQOOmKKQ_180.JPG: 480x640 (no detections), 286.9ms
Speed: 1.1ms preprocess, 286.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOgrrQS7xJKXJexQOOmKKQ_270.JPG: 480x640 (no detections), 292.4ms
Speed: 1.2ms preprocess, 292.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOi1ytB1H4uZgoyaOV7_Lg_0.JPG: 480x640 (no detections), 418.9ms
Speed: 1.4ms preprocess, 418.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOi1ytB1H4uZgoyaOV7_Lg_90.JPG: 480x640 (no detections), 314.8ms
Speed: 1.2ms preprocess, 314.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOi1ytB1H4uZgoyaOV7_Lg_180.JPG: 480x640 (no detections), 323.6ms
Speed: 1.4ms preprocess, 323.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOi1ytB1H4uZgoyaOV7_Lg_270.JPG: 480x640 (no detections), 298.2ms
Speed: 1.1ms preprocess, 298.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOlLdjDc69J9prrzNGLQfQ_0.JPG: 480x640 (no detections), 277.4ms
Speed: 1.2ms preprocess, 277.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOlLdjDc69J9prrzNGLQfQ_90.JPG: 480x640 (no detections), 320.1ms
Speed: 1.1ms preprocess, 320.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOlLdjDc69J9prrzNGLQfQ_180.JPG: 480x640 (no detections), 283.6ms
Speed: 1.1ms preprocess, 283.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOlLdjDc69J9prrzNGLQfQ_270.JPG: 480x640 (no detections), 294.2ms
Speed: 1.1ms preprocess, 294.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOlu461dzFmGknLSKseSJQ_0.JPG: 480x640 (no detections), 285.2ms
Speed: 1.2ms preprocess, 285.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOlu461dzFmGknLSKseSJQ_90.JPG: 480x640 (no detections), 274.9ms
Speed: 1.2ms preprocess, 274.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOlu461dzFmGknLSKseSJQ_180.JPG: 480x640 (no detections), 268.1ms
Speed: 1.0ms preprocess, 268.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOlu461dzFmGknLSKseSJQ_270.JPG: 480x640 (no detections), 275.9ms
Speed: 1.0ms preprocess, 275.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOm3HGxCHdSQeyMxzdlcGA_0.JPG: 480x640 (no detections), 284.0ms
Speed: 1.2ms preprocess, 284.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOm3HGxCHdSQeyMxzdlcGA_90.JPG: 480x640 (no detections), 273.6ms
Speed: 1.3ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOm3HGxCHdSQeyMxzdlcGA_180.JPG: 480x640 (no detections), 273.1ms
Speed: 1.1ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOm3HGxCHdSQeyMxzdlcGA_270.JPG: 480x640 (no detections), 270.8ms
Speed: 1.0ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOmfnkwMU4IY_Rx8QeMBQQ_0.JPG: 480x640 (no detections), 273.7ms
Speed: 1.2ms preprocess, 273.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOmfnkwMU4IY_Rx8QeMBQQ_90.JPG: 480x640 (no detections), 291.5ms
Speed: 1.1ms preprocess, 291.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOmfnkwMU4IY_Rx8QeMBQQ_180.JPG: 480x640 (no detections), 290.3ms
Speed: 1.2ms preprocess, 290.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOmfnkwMU4IY_Rx8QeMBQQ_270.JPG: 480x640 (no detections), 316.6ms
Speed: 1.6ms preprocess, 316.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOnIMajQPujc8qkcECMP_Q_0.JPG: 480x640 (no detections), 325.2ms
Speed: 1.1ms preprocess, 325.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOnIMajQPujc8qkcECMP_Q_90.JPG: 480x640 (no detections), 324.0ms
Speed: 1.8ms preprocess, 324.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOnIMajQPujc8qkcECMP_Q_180.JPG: 480x640 (no detections), 317.2ms
Speed: 1.6ms preprocess, 317.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOnIMajQPujc8qkcECMP_Q_270.JPG: 480x640 (no detections), 295.7ms
Speed: 1.2ms preprocess, 295.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOqtM9rQzd1jRCuYyi8bSg_0.JPG: 480x640 (no detections), 324.7ms
Speed: 2.0ms preprocess, 324.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOqtM9rQzd1jRCuYyi8bSg_90.JPG: 480x640 (no detections), 316.4ms
Speed: 1.3ms preprocess, 316.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOqtM9rQzd1jRCuYyi8bSg_180.JPG: 480x640 (no detections), 357.6ms
Speed: 1.1ms preprocess, 357.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOqtM9rQzd1jRCuYyi8bSg_270.JPG: 480x640 (no detections), 281.3ms
Speed: 1.5ms preprocess, 281.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOrX3wtTF0fYvCg7krSk0A_0.JPG: 480x640 (no detections), 290.6ms
Speed: 1.2ms preprocess, 290.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOrX3wtTF0fYvCg7krSk0A_90.JPG: 480x640 (no detections), 281.5ms
Speed: 1.2ms preprocess, 281.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOrX3wtTF0fYvCg7krSk0A_180.JPG: 480x640 (no detections), 309.4ms
Speed: 1.0ms preprocess, 309.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zOrX3wtTF0fYvCg7krSk0A_270.JPG: 480x640 (no detections), 428.3ms
Speed: 1.3ms preprocess, 428.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zP--MyMU5IHyZGD7AVa-kw_0.JPG: 480x640 (no detections), 343.1ms
Speed: 1.8ms preprocess, 343.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zP--MyMU5IHyZGD7AVa-kw_90.JPG: 480x640 (no detections), 392.1ms
Speed: 1.3ms preprocess, 392.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zP--MyMU5IHyZGD7AVa-kw_180.JPG: 480x640 (no detections), 383.3ms
Speed: 1.2ms preprocess, 383.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zP--MyMU5IHyZGD7AVa-kw_270.JPG: 480x640 1 Waste, 334.0ms
Speed: 1.3ms preprocess, 334.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zP1a130imKq9IfLQJoZIyA_0.JPG: 480x640 (no detections), 318.6ms
Speed: 1.1ms preprocess, 318.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zP1a130imKq9IfLQJoZIyA_90.JPG: 480x640 (no detections), 405.1ms
Speed: 1.1ms preprocess, 405.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zP1a130imKq9IfLQJoZIyA_180.JPG: 480x640 (no detections), 310.3ms
Speed: 1.2ms preprocess, 310.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zP1a130imKq9IfLQJoZIyA_270.JPG: 480x640 (no detections), 277.5ms
Speed: 1.2ms preprocess, 277.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zP4McW7Av1-VcQRrvV5X3g_0.JPG: 480x640 1 Waste, 302.7ms
Speed: 1.0ms preprocess, 302.7ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zP4McW7Av1-VcQRrvV5X3g_90.JPG: 480x640 (no detections), 331.2ms
Speed: 1.4ms preprocess, 331.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zP4McW7Av1-VcQRrvV5X3g_180.JPG: 480x640 (no detections), 381.0ms
Speed: 1.3ms preprocess, 381.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zP4McW7Av1-VcQRrvV5X3g_270.JPG: 480x640 (no detections), 302.6ms
Speed: 1.2ms preprocess, 302.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zP6W7rrXbI1afcn4OgyyCA_0.JPG: 480x640 (no detections), 276.2ms
Speed: 1.3ms preprocess, 276.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zP6W7rrXbI1afcn4OgyyCA_90.JPG: 480x640 (no detections), 280.4ms
Speed: 1.3ms preprocess, 280.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zP6W7rrXbI1afcn4OgyyCA_180.JPG: 480x640 (no detections), 346.6ms
Speed: 1.0ms preprocess, 346.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zP6W7rrXbI1afcn4OgyyCA_270.JPG: 480x640 (no detections), 311.7ms
Speed: 1.9ms preprocess, 311.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPDOqYtC7VwzmPK6icVHkg_0.JPG: 480x640 (no detections), 287.8ms
Speed: 1.5ms preprocess, 287.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPDOqYtC7VwzmPK6icVHkg_90.JPG: 480x640 (no detections), 293.1ms
Speed: 1.2ms preprocess, 293.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPDOqYtC7VwzmPK6icVHkg_180.JPG: 480x640 (no detections), 272.0ms
Speed: 1.0ms preprocess, 272.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPDOqYtC7VwzmPK6icVHkg_270.JPG: 480x640 (no detections), 283.8ms
Speed: 1.2ms preprocess, 283.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPFx4PrPH9-7rd6viSvW-Q_0.JPG: 480x640 (no detections), 280.9ms

Speed: 1.2ms preprocess, 280.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPFx4PrPH9-7rd6viSvW-Q_90.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPFx4PrPH9-7rd6viSvW-Q_180.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPFx4PrPH9-7rd6viSvW-Q_270.JPG: 480x640 (no detections), 274.0ms
Speed: 1.1ms preprocess, 274.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPGRkLDXbjpyna5lp6wSxQ_0.JPG: 480x640 (no detections), 320.4ms
Speed: 1.3ms preprocess, 320.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPGRkLDXbjpyna5lp6wSxQ_90.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPGRkLDXbjpyna5lp6wSxQ_180.JPG: 480x640 (no detections), 269.0ms
Speed: 1.1ms preprocess, 269.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPGRkLDXbjpyna5lp6wSxQ_270.JPG: 480x640 1 Waste, 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPHPJOgEI-n3Ny1x1sQLFg_0.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPHPJOgEI-n3Ny1x1sQLFg_90.JPG: 480x640 (no detections), 281.8ms
Speed: 1.1ms preprocess, 281.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPHPJOgEI-n3Ny1x1sQLFg_180.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPHPJOgEI-n3Ny1x1sQLFg_270.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPHTn590kb9o2A7M9F5GRg_0.JPG: 480x640 (no detections), 282.7ms
Speed: 1.0ms preprocess, 282.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPHTn590kb9o2A7M9F5GRg_90.JPG: 480x640 (no detections), 271.9ms
Speed: 1.0ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPHTn590kb9o2A7M9F5GRg_180.JPG: 480x640 (no detections), 267.6ms
Speed: 1.0ms preprocess, 267.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPHTn590kb9o2A7M9F5GRg_270.JPG: 480x640 (no detections), 265.6ms
Speed: 1.0ms preprocess, 265.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPITFZFVWzL8be8j8G5S4A_0.JPG: 480x640 (no detections), 268.7ms
Speed: 1.1ms preprocess, 268.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPITFZFVWzL8be8j8G5S4A_90.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPITFZFVWzL8be8j8G5S4A_180.JPG: 480x640 (no detections), 275.8ms
Speed: 1.0ms preprocess, 275.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPITFZFVWzL8be8j8G5S4A_270.JPG: 480x640 (no detections), 272.0ms
Speed: 1.5ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPJ1VQLJ9JTsR5JH_xWBPw_0.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPJ1VQLJ9JTsR5JH_xWBPw_90.JPG: 480x640 (no detections), 271.2ms
Speed: 1.0ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPJ1VQLJ9JTsR5JH_xWBPw_180.JPG: 480x640 (no detections), 260.2ms
Speed: 1.1ms preprocess, 260.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPJ1VQLJ9JTsR5JH_xWBPw_270.JPG: 480x640 (no detections), 274.3ms
Speed: 1.0ms preprocess, 274.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPMDHkDIAy2_Nmw4WMuLjw_0.JPG: 480x640 (no detections), 268.6ms
Speed: 1.0ms preprocess, 268.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPMDHkDIAy2_Nmw4WMuLjw_90.JPG: 480x640 (no detections), 270.2ms
Speed: 1.0ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPMDHkDIAy2_Nmw4WMuLjw_180.JPG: 480x640 (no detections), 270.7ms
Speed: 1.0ms preprocess, 270.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPMDHkDIAy2_Nmw4WMuLjw_270.JPG: 480x640 (no detections), 283.3ms
Speed: 1.2ms preprocess, 283.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPMSRxT39ZmbsYt3QfEXQQ_0.JPG: 480x640 (no detections), 274.9ms
Speed: 1.0ms preprocess, 274.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPMSRxT39ZmbsYt3QfEXQQ_90.JPG: 480x640 (no detections), 274.6ms
Speed: 1.1ms preprocess, 274.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPMSRxT39ZmbsYt3QfEXQQ_180.JPG: 480x640 (no detections), 269.6ms
Speed: 1.0ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPMSRxT39ZmbsYt3QfEXQQ_270.JPG: 480x640 (no detections), 272.1ms
Speed: 1.2ms preprocess, 272.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPNI4BfDvbkYGGGzamypQg_0.JPG: 480x640 (no detections), 272.2ms
Speed: 1.5ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPNI4BfDvbkYGGGzamypQg_90.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPNI4BfDvbkYGGGzamypQg_180.JPG: 480x640 (no detections), 270.0ms
Speed: 1.0ms preprocess, 270.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPNI4BfDvbkYGGGzamypQg_270.JPG: 480x640 1 Waste, 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPQlsRRVYDDKZQ7ZbscAnQ_0.JPG: 480x640 (no detections), 272.6ms
Speed: 1.0ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPQlsRRVYDDKZQ7ZbscAnQ_90.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPQlsRRVYDDKZQ7ZbscAnQ_180.JPG: 480x640 (no detections), 262.1ms
Speed: 1.0ms preprocess, 262.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPQlsRRVYDDKZQ7ZbscAnQ_270.JPG: 480x640 (no detections), 273.6ms
Speed: 1.1ms preprocess, 273.6ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPSy4WR3M61qC04jLJ5pqw_0.JPG: 480x640 (no detections), 270.5ms
Speed: 1.1ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPSy4WR3M61qC04jLJ5pqw_90.JPG: 480x640 1 Waste, 271.0ms
Speed: 1.2ms preprocess, 271.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPSy4WR3M61qC04jLJ5pqw_180.JPG: 480x640 (no detections), 269.5ms
Speed: 1.1ms preprocess, 269.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPSy4WR3M61qC04jLJ5pqw_270.JPG: 480x640 (no detections), 271.5ms
Speed: 1.1ms preprocess, 271.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPTG-slzjxi6pOfi18i0DQ_0.JPG: 480x640 (no detections), 268.4ms
Speed: 1.1ms preprocess, 268.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPTG-slzjxi6pOfi18i0DQ_90.JPG: 480x640 (no detections), 265.5ms
Speed: 1.0ms preprocess, 265.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPTG-slzjxi6pOfi18i0DQ_180.JPG: 480x640 (no detections), 268.7ms
Speed: 1.0ms preprocess, 268.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPTG-slzjxi6pOfi18i0DQ_270.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zP_sqcIFgI39qxQLg9l3WA_0.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zP_sqcIFgI39qxQLg9l3WA_90.JPG: 480x640 (no detections), 279.0ms
Speed: 1.0ms preprocess, 279.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zP_sqcIFgI39qxQLg9l3WA_180.JPG: 480x640 (no detections), 274.2ms
Speed: 1.0ms preprocess, 274.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zP_sqcIFgI39qxQLg9l3WA_270.JPG: 480x640 (no detections), 274.6ms
Speed: 1.1ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPalhEcZIOXSWIkpkRVrBg_0.JPG: 480x640 (no detections), 268.9ms
Speed: 1.1ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPalhEcZIOXSWIkpkRVrBg_90.JPG: 480x640 (no detections), 274.5ms
Speed: 1.1ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPalhEcZIOXSWIkpkRVrBg_180.JPG: 480x640 (no detections), 266.6ms
Speed: 1.1ms preprocess, 266.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPalhEcZIOXSWIkpkRVrBg_270.JPG: 480x640 (no detections), 268.9ms
Speed: 1.1ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPeR3gyZdjzKkY6PyzULbQ_0.JPG: 480x640 (no detections), 272.6ms
Speed: 1.0ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPeR3gyZdjzKkY6PyzULbQ_90.JPG: 480x640 (no detections), 267.0ms
Speed: 1.0ms preprocess, 267.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPeR3gyZdjzKkY6PyzULbQ_180.JPG: 480x640 (no detections), 268.9ms
Speed: 1.0ms preprocess, 268.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPeR3gyZdjzKkY6PyzULbQ_270.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPfadndVyB9Ls4tnyu_AIg_0.JPG: 480x640 (no detections), 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPfadndVyB9Ls4tnyu_AIg_90.JPG: 480x640 (no detections), 268.4ms
Speed: 1.0ms preprocess, 268.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPfadndVyB9Ls4tnyu_AIg_180.JPG: 480x640 (no detections), 273.8ms
Speed: 1.0ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPfadndVyB9Ls4tnyu_AIg_270.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPgz1w6FHbXPly-NcAEWaw_0.JPG: 480x640 (no detections), 273.9ms
Speed: 1.1ms preprocess, 273.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPgz1w6FHbXPly-NcAEWaw_90.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPgz1w6FHbXPly-NcAEWaw_180.JPG: 480x640 (no detections), 271.3ms
Speed: 1.0ms preprocess, 271.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPgz1w6FHbXPly-NcAEWaw_270.JPG: 480x640 (no detections), 272.0ms

Speed: 1.1ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPh0i3eqvS0y5zbyhP_Low_0.JPG: 480x640 (no detections), 267.8ms
Speed: 1.1ms preprocess, 267.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPh0i3eqvS0y5zbyhP_Low_90.JPG: 480x640 (no detections), 276.8ms
Speed: 1.0ms preprocess, 276.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPh0i3eqvS0y5zbyhP_Low_180.JPG: 480x640 (no detections), 267.6ms
Speed: 1.0ms preprocess, 267.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPh0i3eqvS0y5zbyhP_Low_270.JPG: 480x640 (no detections), 268.6ms
Speed: 1.0ms preprocess, 268.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPig30_IDc_32vuwasPbCg_0.JPG: 480x640 (no detections), 272.6ms
Speed: 1.2ms preprocess, 272.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPig30_IDc_32vuwasPbCg_90.JPG: 480x640 1 Waste, 269.3ms
Speed: 1.0ms preprocess, 269.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPig30_IDc_32vuwasPbCg_180.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPig30_IDc_32vuwasPbCg_270.JPG: 480x640 (no detections), 272.5ms
Speed: 1.1ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPnaYwqkzqc1AKctTLlwVQ_0.JPG: 480x640 (no detections), 267.1ms
Speed: 1.1ms preprocess, 267.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPnaYwqkzqc1AKctTLlwVQ_90.JPG: 480x640 (no detections), 306.2ms
Speed: 1.0ms preprocess, 306.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPnaYwqkzqc1AKctTLlwVQ_180.JPG: 480x640 (no detections), 274.6ms
Speed: 1.0ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPnaYwqkzqc1AKctTLlwVQ_270.JPG: 480x640 (no detections), 295.8ms
Speed: 1.1ms preprocess, 295.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPo9c8ZfdFu91ybP5BUIBg_0.JPG: 480x640 (no detections), 267.4ms
Speed: 1.1ms preprocess, 267.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPo9c8ZfdFu91ybP5BUIBg_90.JPG: 480x640 (no detections), 269.5ms
Speed: 1.1ms preprocess, 269.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPo9c8ZfdFu91ybP5BUIBg_180.JPG: 480x640 (no detections), 291.6ms
Speed: 1.1ms preprocess, 291.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPo9c8ZfdFu91ybP5BUIBg_270.JPG: 480x640 (no detections), 268.5ms
Speed: 1.1ms preprocess, 268.5ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPrDu5j2VmTHzEnnpRrLIg_0.JPG: 480x640 (no detections), 273.8ms
Speed: 1.2ms preprocess, 273.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPrDu5j2VmTHzEnnpRrLIg_90.JPG: 480x640 (no detections), 269.3ms
Speed: 1.0ms preprocess, 269.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPrDu5j2VmTHzEnnpRrLIg_180.JPG: 480x640 (no detections), 271.9ms
Speed: 1.2ms preprocess, 271.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPrDu5j2VmTHzEnnpRrLIg_270.JPG: 480x640 (no detections), 268.2ms
Speed: 1.1ms preprocess, 268.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPwzdrepCXH3sAHUYVjE0g_0.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPwzdrepCXH3sAHUYVjE0g_90.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPwzdrepCXH3sAHUYVjE0g_180.JPG: 480x640 (no detections), 270.7ms
Speed: 1.0ms preprocess, 270.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPwzdrepCXH3sAHUYVjE0g_270.JPG: 480x640 (no detections), 268.1ms
Speed: 1.0ms preprocess, 268.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPyAiKPpyhQTunS5a-K7Fg_0.JPG: 480x640 1 Waste, 275.9ms
Speed: 1.2ms preprocess, 275.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPyAiKPpyhQTunS5a-K7Fg_90.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPyAiKPpyhQTunS5a-K7Fg_180.JPG: 480x640 (no detections), 267.2ms
Speed: 1.1ms preprocess, 267.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPyAiKPpyhQTunS5a-K7Fg_270.JPG: 480x640 (no detections), 269.4ms
Speed: 1.0ms preprocess, 269.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPyxq02eVZ1pnbz1VahtHA_0.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPyxq02eVZ1pnbz1VahtHA_90.JPG: 480x640 (no detections), 268.9ms
Speed: 1.0ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPyxq02eVZ1pnbz1VahtHA_180.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zPyxq02eVZ1pnbz1VahtHA_270.JPG: 480x640 (no detections), 265.3ms
Speed: 1.0ms preprocess, 265.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQ-e50rgQrjXAIKxmBoDlQ_0.JPG: 480x640 (no detections), 270.1ms
Speed: 1.0ms preprocess, 270.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQ-e50rgQrjXAIKxmBoDlQ_90.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQ-e50rgQrjXAIKxmBoDlQ_180.JPG: 480x640 (no detections), 269.3ms
Speed: 1.0ms preprocess, 269.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQ-e50rgQrjXAIKxmBoDlQ_270.JPG: 480x640 (no detections), 266.5ms
Speed: 1.0ms preprocess, 266.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQ1sW9J3DtS0dNK9Hef4Ag_0.JPG: 480x640 (no detections), 273.2ms
Speed: 1.0ms preprocess, 273.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQ1sW9J3DtS0dNK9Hef4Ag_90.JPG: 480x640 (no detections), 269.3ms
Speed: 1.2ms preprocess, 269.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQ1sW9J3DtS0dNK9Hef4Ag_180.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQ1sW9J3DtS0dNK9Hef4Ag_270.JPG: 480x640 (no detections), 268.1ms
Speed: 1.0ms preprocess, 268.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQ21n_VkesqBNWKT7Z9_cg_0.JPG: 480x640 (no detections), 270.3ms
Speed: 1.0ms preprocess, 270.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQ21n_VkesqBNWKT7Z9_cg_90.JPG: 480x640 (no detections), 271.5ms
Speed: 1.2ms preprocess, 271.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQ21n_VkesqBNWKT7Z9_cg_180.JPG: 480x640 (no detections), 270.2ms
Speed: 1.0ms preprocess, 270.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQ21n_VkesqBNWKT7Z9_cg_270.JPG: 480x640 (no detections), 268.3ms
Speed: 1.0ms preprocess, 268.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQ3D5cHBxg8dOWOrYqNpRg_0.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQ3D5cHBxg8dOWOrYqNpRg_90.JPG: 480x640 (no detections), 271.0ms
Speed: 1.1ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQ3D5cHBxg8dOWOrYqNpRg_180.JPG: 480x640 (no detections), 266.8ms
Speed: 1.1ms preprocess, 266.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQ3D5cHBxg8dOWOrYqNpRg_270.JPG: 480x640 (no detections), 269.4ms
Speed: 1.2ms preprocess, 269.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQ5FF4RHlxSKGN4UWn68GQ_0.JPG: 480x640 (no detections), 271.6ms
Speed: 1.2ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQ5FF4RHlxSKGN4UWn68GQ_90.JPG: 480x640 (no detections), 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQ5FF4RHlxSKGN4UWn68GQ_180.JPG: 480x640 (no detections), 269.2ms
Speed: 1.1ms preprocess, 269.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQ5FF4RHlxSKGN4UWn68GQ_270.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQDzUOGxtS0LV2bTuXO7kg_0.JPG: 480x640 (no detections), 272.2ms
Speed: 1.0ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQDzUOGxtS0LV2bTuXO7kg_90.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQDzUOGxtS0LV2bTuXO7kg_180.JPG: 480x640 (no detections), 267.5ms
Speed: 1.1ms preprocess, 267.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQDzUOGxtS0LV2bTuXO7kg_270.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQF-XO_SiQ5UKlu-Jwkabw_0.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQF-XO_SiQ5UKlu-Jwkabw_90.JPG: 480x640 (no detections), 269.5ms
Speed: 1.1ms preprocess, 269.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQF-XO_SiQ5UKlu-Jwkabw_180.JPG: 480x640 (no detections), 270.7ms
Speed: 1.0ms preprocess, 270.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQF-XO_SiQ5UKlu-Jwkabw_270.JPG: 480x640 (no detections), 270.4ms
Speed: 1.1ms preprocess, 270.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQKgAJzDipGopVs5kASCxA_0.JPG: 480x640 (no detections), 270.0ms
Speed: 1.0ms preprocess, 270.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQKgAJzDipGopVs5kASCxA_90.JPG: 480x640 (no detections), 273.6ms
Speed: 1.0ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQKgAJzDipGopVs5kASCxA_180.JPG: 480x640 (no detections), 270.2ms
Speed: 1.0ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQKgAJzDipGopVs5kASCxA_270.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQMIIc9IuwjnRGud8dUebA_0.JPG: 480x640 (no detections), 274.4ms
Speed: 1.2ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQMIIc9IuwjnRGud8dUebA_90.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQMIIc9IuwjnRGud8dUebA_180.JPG: 480x640 (no detections), 271.4ms

Speed: 1.0ms preprocess, 271.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQMIIc9IuwjnRGud8dUebA_270.JPG: 480x640 (no detections), 272.2ms
Speed: 1.0ms preprocess, 272.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQRkNxY3MkV1IcXmujqKuA_0.JPG: 480x640 (no detections), 269.6ms
Speed: 1.0ms preprocess, 269.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQRkNxY3MkV1IcXmujqKuA_90.JPG: 480x640 (no detections), 270.8ms
Speed: 1.0ms preprocess, 270.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQRkNxY3MkV1IcXmujqKuA_180.JPG: 480x640 (no detections), 267.3ms
Speed: 1.1ms preprocess, 267.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQRkNxY3MkV1IcXmujqKuA_270.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQTyMPvMSS19ct4PCFrfSQ_0.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQTyMPvMSS19ct4PCFrfSQ_90.JPG: 480x640 (no detections), 270.6ms
Speed: 1.4ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQTyMPvMSS19ct4PCFrfSQ_180.JPG: 480x640 (no detections), 273.4ms
Speed: 1.2ms preprocess, 273.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQTyMPvMSS19ct4PCFrfSQ_270.JPG: 480x640 (no detections), 271.0ms
Speed: 1.1ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQZ0U512iu8lSSpv2cWh1w_0.JPG: 480x640 (no detections), 271.2ms
Speed: 1.2ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQZ0U512iu8lSSpv2cWh1w_90.JPG: 480x640 (no detections), 269.8ms
Speed: 1.1ms preprocess, 269.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQZ0U512iu8lSSpv2cWh1w_180.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQZ0U512iu8lSSpv2cWh1w_270.JPG: 480x640 (no detections), 267.9ms
Speed: 1.0ms preprocess, 267.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQ_6qi8m3OVPnhEtYMPuOQ_0.JPG: 480x640 (no detections), 271.4ms
Speed: 1.0ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQ_6qi8m3OVPnhEtYMPuOQ_90.JPG: 480x640 (no detections), 271.8ms
Speed: 1.3ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQ_6qi8m3OVPnhEtYMPuOQ_180.JPG: 480x640 (no detections), 267.8ms
Speed: 1.1ms preprocess, 267.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQ_6qi8m3OVPnhEtYMPuOQ_270.JPG: 480x640 (no detections), 270.8ms
Speed: 1.2ms preprocess, 270.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQ_GJq8Z5M-L7gsaRvNl1Q_0.JPG: 480x640 2 Wastes, 263.5ms
Speed: 1.1ms preprocess, 263.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQ_GJq8Z5M-L7gsaRvNl1Q_90.JPG: 480x640 1 Waste, 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQ_GJq8Z5M-L7gsaRvNl1Q_180.JPG: 480x640 (no detections), 272.1ms
Speed: 1.1ms preprocess, 272.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQ_GJq8Z5M-L7gsaRvNl1Q_270.JPG: 480x640 (no detections), 269.3ms
Speed: 1.0ms preprocess, 269.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQ_L3KjqBfplGNCU0EahVw_0.JPG: 480x640 (no detections), 269.6ms
Speed: 1.1ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQ_L3KjqBfplGNCU0EahVw_90.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQ_L3KjqBfplGNCU0EahVw_180.JPG: 480x640 (no detections), 272.8ms
Speed: 1.0ms preprocess, 272.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQ_L3KjqBfplGNCU0EahVw_270.JPG: 480x640 (no detections), 268.8ms
Speed: 1.2ms preprocess, 268.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQ_MB_nc5TM8NSdHfJ0MxA_0.JPG: 480x640 (no detections), 275.2ms
Speed: 1.1ms preprocess, 275.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQ_MB_nc5TM8NSdHfJ0MxA_90.JPG: 480x640 (no detections), 268.5ms
Speed: 1.0ms preprocess, 268.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQ_MB_nc5TM8NSdHfJ0MxA_180.JPG: 480x640 (no detections), 277.1ms
Speed: 1.0ms preprocess, 277.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQ_MB_nc5TM8NSdHfJ0MxA_270.JPG: 480x640 (no detections), 270.5ms
Speed: 1.0ms preprocess, 270.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQgOPsvFQobef8BQHLoa3w_0.JPG: 480x640 (no detections), 270.3ms
Speed: 1.1ms preprocess, 270.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQgOPsvFQobef8BQHLoa3w_90.JPG: 480x640 (no detections), 300.3ms
Speed: 1.1ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQgOPsvFQobef8BQHLoa3w_180.JPG: 480x640 (no detections), 270.9ms
Speed: 1.0ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQgOPsvFQobef8BQHLoa3w_270.JPG: 480x640 (no detections), 268.2ms
Speed: 1.0ms preprocess, 268.2ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQifq3EE-qFpFPPcRmkofg_0.JPG: 480x640 (no detections), 268.5ms
Speed: 1.1ms preprocess, 268.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQifq3EE-qFpFPPcRmkofg_90.JPG: 480x640 (no detections), 270.3ms
Speed: 1.2ms preprocess, 270.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQifq3EE-qFpFPPcRmkofg_180.JPG: 480x640 (no detections), 266.4ms
Speed: 1.1ms preprocess, 266.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQifq3EE-qFpFPPcRmkofg_270.JPG: 480x640 (no detections), 269.6ms
Speed: 1.2ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQj-Z2W2wf8oapOpecJT7w_0.JPG: 480x640 (no detections), 266.7ms
Speed: 1.1ms preprocess, 266.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQj-Z2W2wf8oapOpecJT7w_90.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQj-Z2W2wf8oapOpecJT7w_180.JPG: 480x640 (no detections), 273.1ms
Speed: 1.0ms preprocess, 273.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQj-Z2W2wf8oapOpecJT7w_270.JPG: 480x640 (no detections), 269.0ms
Speed: 1.0ms preprocess, 269.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQj3Fbn2XxuUWoivQOcyKw_0.JPG: 480x640 (no detections), 272.7ms
Speed: 1.2ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQj3Fbn2XxuUWoivQOcyKw_90.JPG: 480x640 (no detections), 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQj3Fbn2XxuUWoivQOcyKw_180.JPG: 480x640 (no detections), 270.4ms
Speed: 1.1ms preprocess, 270.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQj3Fbn2XxuUWoivQOcyKw_270.JPG: 480x640 1 Waste, 267.7ms
Speed: 1.0ms preprocess, 267.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQjaqc4bL6mSB-dR1h05Ug_0.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQjaqc4bL6mSB-dR1h05Ug_90.JPG: 480x640 (no detections), 272.6ms
Speed: 1.0ms preprocess, 272.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQjaqc4bL6mSB-dR1h05Ug_180.JPG: 480x640 (no detections), 266.5ms
Speed: 1.0ms preprocess, 266.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQjaqc4bL6mSB-dR1h05Ug_270.JPG: 480x640 (no detections), 274.2ms
Speed: 1.0ms preprocess, 274.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQkE55P-AHg3lcUcD3fChw_0.JPG: 480x640 (no detections), 265.9ms
Speed: 1.2ms preprocess, 265.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQkE55P-AHg3lcUcD3fChw_90.JPG: 480x640 (no detections), 269.7ms
Speed: 1.0ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQkE55P-AHg3lcUcD3fChw_180.JPG: 480x640 (no detections), 269.0ms
Speed: 1.1ms preprocess, 269.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQkE55P-AHg3lcUcD3fChw_270.JPG: 480x640 (no detections), 267.6ms
Speed: 1.1ms preprocess, 267.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQkVgW5f_Kybdbs8OTBFsQ_0.JPG: 480x640 (no detections), 270.1ms
Speed: 1.0ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQkVgW5f_Kybdbs8OTBFsQ_90.JPG: 480x640 (no detections), 266.3ms
Speed: 1.1ms preprocess, 266.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQkVgW5f_Kybdbs8OTBFsQ_180.JPG: 480x640 (no detections), 269.2ms
Speed: 1.0ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQkVgW5f_Kybdbs8OTBFsQ_270.JPG: 480x640 (no detections), 269.3ms
Speed: 1.0ms preprocess, 269.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQlKRckx4PNauK6Qotg3Ew_0.JPG: 480x640 (no detections), 270.9ms
Speed: 1.0ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQlKRckx4PNauK6Qotg3Ew_90.JPG: 480x640 (no detections), 261.3ms
Speed: 1.0ms preprocess, 261.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQlKRckx4PNauK6Qotg3Ew_180.JPG: 480x640 (no detections), 259.4ms
Speed: 1.1ms preprocess, 259.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQlKRckx4PNauK6Qotg3Ew_270.JPG: 480x640 (no detections), 270.4ms
Speed: 1.1ms preprocess, 270.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQnZowyDY1dg98D5r6rKwQ_0.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQnZowyDY1dg98D5r6rKwQ_90.JPG: 480x640 (no detections), 271.3ms
Speed: 1.0ms preprocess, 271.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQnZowyDY1dg98D5r6rKwQ_180.JPG: 480x640 (no detections), 271.0ms
Speed: 1.0ms preprocess, 271.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQnZowyDY1dg98D5r6rKwQ_270.JPG: 480x640 (no detections), 270.5ms
Speed: 1.1ms preprocess, 270.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQsmlKYLOY8DHQUcEwNPgQ_0.JPG: 480x640 (no detections), 264.1ms
Speed: 1.1ms preprocess, 264.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQsmlKYLOY8DHQUcEwNPgQ_90.JPG: 480x640 (no detections), 261.6ms

Speed: 1.0ms preprocess, 261.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQsmlKYLOY8DHQUcEwNPgQ_180.JPG: 480x640 (no detections), 267.4ms
Speed: 1.0ms preprocess, 267.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQsmlKYLOY8DHQUcEwNPgQ_270.JPG: 480x640 (no detections), 270.0ms
Speed: 1.0ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQtWCaFHl_-yHaESQEx4LA_0.JPG: 480x640 (no detections), 267.9ms
Speed: 1.1ms preprocess, 267.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQtWCaFHl_-yHaESQEx4LA_90.JPG: 480x640 (no detections), 270.6ms
Speed: 1.2ms preprocess, 270.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQtWCaFHl_-yHaESQEx4LA_180.JPG: 480x640 (no detections), 269.3ms
Speed: 1.1ms preprocess, 269.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQtWCaFHl_-yHaESQEx4LA_270.JPG: 480x640 (no detections), 271.4ms
Speed: 1.0ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQvfKIcuuxO_dwyGYbZLJA_0.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQvfKIcuuxO_dwyGYbZLJA_90.JPG: 480x640 (no detections), 275.9ms
Speed: 1.2ms preprocess, 275.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQvfKIcuuxO_dwyGYbZLJA_180.JPG: 480x640 (no detections), 271.0ms
Speed: 1.1ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zQvfKIcuuxO_dwyGYbZLJA_270.JPG: 480x640 (no detections), 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zR1bu-neFGXxH0o6GZCPTQ_0.JPG: 480x640 (no detections), 273.6ms
Speed: 1.2ms preprocess, 273.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zR1bu-neFGXxH0o6GZCPTQ_90.JPG: 480x640 (no detections), 269.2ms
Speed: 1.1ms preprocess, 269.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zR1bu-neFGXxH0o6GZCPTQ_180.JPG: 480x640 (no detections), 268.0ms
Speed: 1.0ms preprocess, 268.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zR1bu-neFGXxH0o6GZCPTQ_270.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zR375Sv4DMZlM_sKxoNFGQ_0.JPG: 480x640 (no detections), 266.6ms
Speed: 1.1ms preprocess, 266.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zR375Sv4DMZlM_sKxoNFGQ_90.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zR375Sv4DMZlM_sKxoNFGQ_180.JPG: 480x640 (no detections), 270.9ms
Speed: 1.0ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zR375Sv4DMZlM_sKxoNFGQ_270.JPG: 480x640 (no detections), 267.3ms
Speed: 1.0ms preprocess, 267.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zR4bCsttiEVYAkDsZqFDxA_0.JPG: 480x640 (no detections), 275.8ms
Speed: 1.2ms preprocess, 275.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zR4bCsttiEVYAkDsZqFDxA_90.JPG: 480x640 (no detections), 269.0ms
Speed: 1.1ms preprocess, 269.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zR4bCsttiEVYAkDsZqFDxA_180.JPG: 480x640 (no detections), 268.9ms
Speed: 1.1ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zR4bCsttiEVYAkDsZqFDxA_270.JPG: 480x640 (no detections), 272.6ms
Speed: 1.0ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zR7QxErLXVQq5RndoFiQnQ_0.JPG: 480x640 (no detections), 273.1ms
Speed: 1.0ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zR7QxErLXVQq5RndoFiQnQ_90.JPG: 480x640 (no detections), 275.7ms
Speed: 1.5ms preprocess, 275.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zR7QxErLXVQq5RndoFiQnQ_180.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zR7QxErLXVQq5RndoFiQnQ_270.JPG: 480x640 (no detections), 273.1ms
Speed: 1.0ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRANG1s6AT8wUhvDaXqApg_0.JPG: 480x640 (no detections), 273.3ms
Speed: 1.0ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRANG1s6AT8wUhvDaXqApg_90.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRANG1s6AT8wUhvDaXqApg_180.JPG: 480x640 (no detections), 276.1ms
Speed: 1.0ms preprocess, 276.1ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRANG1s6AT8wUhvDaXqApg_270.JPG: 480x640 (no detections), 308.0ms
Speed: 1.5ms preprocess, 308.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRBDK_F9GuX1fWA1AJQaoQ_0.JPG: 480x640 (no detections), 295.7ms
Speed: 1.2ms preprocess, 295.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRBDK_F9GuX1fWA1AJQaoQ_90.JPG: 480x640 (no detections), 331.7ms
Speed: 1.1ms preprocess, 331.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRBDK_F9GuX1fWA1AJQaoQ_180.JPG: 480x640 (no detections), 344.9ms
Speed: 1.4ms preprocess, 344.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRBDK_F9GuX1fWA1AJQaoQ_270.JPG: 480x640 (no detections), 430.3ms
Speed: 1.3ms preprocess, 430.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zREAqyNtrcjPgpYjDZCv8A_0.JPG: 480x640 (no detections), 326.2ms
Speed: 1.1ms preprocess, 326.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zREAqyNtrcjPgpYjDZCv8A_90.JPG: 480x640 (no detections), 292.0ms
Speed: 1.2ms preprocess, 292.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zREAqyNtrcjPgpYjDZCv8A_180.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zREAqyNtrcjPgpYjDZCv8A_270.JPG: 480x640 (no detections), 269.0ms
Speed: 1.1ms preprocess, 269.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zREX2uv3_Hm3iAbkYZ4eEg_0.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zREX2uv3_Hm3iAbkYZ4eEg_90.JPG: 480x640 (no detections), 270.6ms
Speed: 1.0ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zREX2uv3_Hm3iAbkYZ4eEg_180.JPG: 480x640 (no detections), 270.5ms
Speed: 1.0ms preprocess, 270.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zREX2uv3_Hm3iAbkYZ4eEg_270.JPG: 480x640 (no detections), 268.7ms
Speed: 1.1ms preprocess, 268.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zREi92Pe_4IEcrkxGj-taQ_0.JPG: 480x640 (no detections), 269.9ms
Speed: 1.0ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zREi92Pe_4IEcrkxGj-taQ_90.JPG: 480x640 (no detections), 262.3ms
Speed: 1.1ms preprocess, 262.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zREi92Pe_4IEcrkxGj-taQ_180.JPG: 480x640 (no detections), 269.5ms
Speed: 1.0ms preprocess, 269.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zREi92Pe_4IEcrkxGj-taQ_270.JPG: 480x640 (no detections), 273.6ms
Speed: 1.2ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRIazjWpViMx6NGrPsnimA_0.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRIazjWpViMx6NGrPsnimA_90.JPG: 480x640 (no detections), 268.5ms
Speed: 1.0ms preprocess, 268.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRIazjWpViMx6NGrPsnimA_180.JPG: 480x640 (no detections), 276.1ms
Speed: 1.2ms preprocess, 276.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRIazjWpViMx6NGrPsnimA_270.JPG: 480x640 (no detections), 271.8ms
Speed: 1.2ms preprocess, 271.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRJ6pxUGYnsES8b0s_lpNg_0.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRJ6pxUGYnsES8b0s_lpNg_90.JPG: 480x640 (no detections), 268.9ms
Speed: 1.0ms preprocess, 268.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRJ6pxUGYnsES8b0s_lpNg_180.JPG: 480x640 (no detections), 268.9ms
Speed: 1.1ms preprocess, 268.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRJ6pxUGYnsES8b0s_lpNg_270.JPG: 480x640 (no detections), 272.0ms
Speed: 1.0ms preprocess, 272.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRKc3AVj3G5sfT_SSG8lXg_0.JPG: 480x640 1 Waste, 271.5ms
Speed: 1.0ms preprocess, 271.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRKc3AVj3G5sfT_SSG8lXg_90.JPG: 480x640 (no detections), 268.8ms
Speed: 1.1ms preprocess, 268.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRKc3AVj3G5sfT_SSG8lXg_180.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRKc3AVj3G5sfT_SSG8lXg_270.JPG: 480x640 (no detections), 279.0ms
Speed: 1.2ms preprocess, 279.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRLD_H8GT3FdSggibCTSmg_0.JPG: 480x640 (no detections), 270.9ms
Speed: 1.0ms preprocess, 270.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRLD_H8GT3FdSggibCTSmg_90.JPG: 480x640 (no detections), 266.8ms
Speed: 1.1ms preprocess, 266.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRLD_H8GT3FdSggibCTSmg_180.JPG: 480x640 (no detections), 268.1ms
Speed: 1.2ms preprocess, 268.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRLD_H8GT3FdSggibCTSmg_270.JPG: 480x640 (no detections), 271.0ms
Speed: 1.0ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRS0Z7Mw0LJsvTfsFOz1uw_0.JPG: 480x640 (no detections), 275.8ms
Speed: 1.1ms preprocess, 275.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRS0Z7Mw0LJsvTfsFOz1uw_90.JPG: 480x640 (no detections), 275.0ms
Speed: 1.1ms preprocess, 275.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRS0Z7Mw0LJsvTfsFOz1uw_180.JPG: 480x640 (no detections), 280.6ms
Speed: 1.0ms preprocess, 280.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRS0Z7Mw0LJsvTfsFOz1uw_270.JPG: 480x640 (no detections), 268.7ms
Speed: 1.1ms preprocess, 268.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRSz-Z94YZSwwAATQDNe1Q_0.JPG: 480x640 (no detections), 268.2ms

Speed: 1.1ms preprocess, 268.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRSz-Z94YZSwwAATQDNe1Q_90.JPG: 480x640 (no detections), 269.3ms
Speed: 1.1ms preprocess, 269.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRSz-Z94YZSwwAATQDNe1Q_180.JPG: 480x640 (no detections), 269.1ms
Speed: 1.0ms preprocess, 269.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRSz-Z94YZSwwAATQDNe1Q_270.JPG: 480x640 (no detections), 270.9ms
Speed: 1.1ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRUfcIqmRelalzL8rewELw_0.JPG: 480x640 (no detections), 267.5ms
Speed: 1.1ms preprocess, 267.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRUfcIqmRelalzL8rewELw_90.JPG: 480x640 (no detections), 269.2ms
Speed: 1.1ms preprocess, 269.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRUfcIqmRelalzL8rewELw_180.JPG: 480x640 (no detections), 269.4ms
Speed: 1.1ms preprocess, 269.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRUfcIqmRelalzL8rewELw_270.JPG: 480x640 (no detections), 272.2ms
Speed: 1.0ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRV6Nwv4ESc3f9klF3LFrQ_0.JPG: 480x640 (no detections), 271.0ms
Speed: 1.2ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRV6Nwv4ESc3f9klF3LFrQ_90.JPG: 480x640 (no detections), 269.1ms
Speed: 1.1ms preprocess, 269.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRV6Nwv4ESc3f9klF3LFrQ_180.JPG: 480x640 (no detections), 268.8ms
Speed: 1.1ms preprocess, 268.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRV6Nwv4ESc3f9klF3LFrQ_270.JPG: 480x640 (no detections), 272.4ms
Speed: 1.1ms preprocess, 272.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRZTRBvLtj5UT6mF6w8eLw_0.JPG: 480x640 (no detections), 274.2ms
Speed: 1.1ms preprocess, 274.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRZTRBvLtj5UT6mF6w8eLw_90.JPG: 480x640 (no detections), 269.5ms
Speed: 1.1ms preprocess, 269.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRZTRBvLtj5UT6mF6w8eLw_180.JPG: 480x640 (no detections), 275.9ms
Speed: 1.1ms preprocess, 275.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRZTRBvLtj5UT6mF6w8eLw_270.JPG: 480x640 (no detections), 268.9ms
Speed: 1.2ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zReIeG95ToYcWp6IgcSF7g_0.JPG: 480x640 (no detections), 272.6ms
Speed: 1.3ms preprocess, 272.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zReIeG95ToYcWp6IgcSF7g_90.JPG: 480x640 (no detections), 269.2ms
Speed: 1.1ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zReIeG95ToYcWp6IgcSF7g_180.JPG: 480x640 (no detections), 270.6ms
Speed: 1.0ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zReIeG95ToYcWp6IgcSF7g_270.JPG: 480x640 (no detections), 272.2ms
Speed: 1.0ms preprocess, 272.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRga9kcobNpnWeu8PrMsqg_0.JPG: 480x640 (no detections), 272.6ms
Speed: 1.0ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRga9kcobNpnWeu8PrMsqg_90.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRga9kcobNpnWeu8PrMsqg_180.JPG: 480x640 1 Waste, 273.4ms
Speed: 1.0ms preprocess, 273.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRga9kcobNpnWeu8PrMsqg_270.JPG: 480x640 1 Waste, 268.4ms
Speed: 1.1ms preprocess, 268.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRgjvLwr5pbNdEn4Tyrb8A_0.JPG: 480x640 (no detections), 275.0ms
Speed: 1.1ms preprocess, 275.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRgjvLwr5pbNdEn4Tyrb8A_90.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRgjvLwr5pbNdEn4Tyrb8A_180.JPG: 480x640 (no detections), 274.5ms
Speed: 1.0ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRgjvLwr5pbNdEn4Tyrb8A_270.JPG: 480x640 (no detections), 272.9ms
Speed: 1.0ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRoSj3K2UcniDzMJw9vNZQ_0.JPG: 480x640 (no detections), 272.4ms
Speed: 1.0ms preprocess, 272.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRoSj3K2UcniDzMJw9vNZQ_90.JPG: 480x640 (no detections), 272.0ms
Speed: 1.0ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRoSj3K2UcniDzMJw9vNZQ_180.JPG: 480x640 (no detections), 270.9ms
Speed: 1.0ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRoSj3K2UcniDzMJw9vNZQ_270.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRq6e4DPbDIHvKtst10DdQ_0.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRq6e4DPbDIHvKtst10DdQ_90.JPG: 480x640 (no detections), 268.8ms
Speed: 1.0ms preprocess, 268.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRq6e4DPbDIHvKtst10DdQ_180.JPG: 480x640 (no detections), 302.2ms
Speed: 1.1ms preprocess, 302.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRq6e4DPbDIHvKtst10DdQ_270.JPG: 480x640 (no detections), 270.4ms
Speed: 1.0ms preprocess, 270.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRvSdfyTaG44SbThK3pSGQ_0.JPG: 480x640 (no detections), 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRvSdfyTaG44SbThK3pSGQ_90.JPG: 480x640 (no detections), 265.2ms
Speed: 1.1ms preprocess, 265.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRvSdfyTaG44SbThK3pSGQ_180.JPG: 480x640 (no detections), 269.1ms
Speed: 1.0ms preprocess, 269.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRvSdfyTaG44SbThK3pSGQ_270.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRvxsvHlfvcRPx53xei-dA_0.JPG: 480x640 (no detections), 276.4ms
Speed: 1.1ms preprocess, 276.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRvxsvHlfvcRPx53xei-dA_90.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRvxsvHlfvcRPx53xei-dA_180.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRvxsvHlfvcRPx53xei-dA_270.JPG: 480x640 (no detections), 272.3ms
Speed: 1.1ms preprocess, 272.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRvzCNUkuS-ZsBcCxk8f-Q_0.JPG: 480x640 (no detections), 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRvzCNUkuS-ZsBcCxk8f-Q_90.JPG: 480x640 (no detections), 272.4ms
Speed: 1.2ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRvzCNUkuS-ZsBcCxk8f-Q_180.JPG: 480x640 (no detections), 271.5ms
Speed: 1.1ms preprocess, 271.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zRvzCNUkuS-ZsBcCxk8f-Q_270.JPG: 480x640 (no detections), 271.9ms
Speed: 1.8ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zS1SchN5pV80SdEXB3qGuA_0.JPG: 480x640 (no detections), 269.9ms
Speed: 1.0ms preprocess, 269.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zS1SchN5pV80SdEXB3qGuA_90.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zS1SchN5pV80SdEXB3qGuA_180.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zS1SchN5pV80SdEXB3qGuA_270.JPG: 480x640 (no detections), 271.0ms
Speed: 1.0ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zS4Eq_JNEAaKYp1yTCi63g_0.JPG: 480x640 1 Waste, 266.0ms
Speed: 1.2ms preprocess, 266.0ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zS4Eq_JNEAaKYp1yTCi63g_90.JPG: 480x640 (no detections), 263.6ms
Speed: 1.1ms preprocess, 263.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zS4Eq_JNEAaKYp1yTCi63g_180.JPG: 480x640 (no detections), 260.6ms
Speed: 1.0ms preprocess, 260.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zS4Eq_JNEAaKYp1yTCi63g_270.JPG: 480x640 1 Waste, 260.3ms
Speed: 1.0ms preprocess, 260.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zS4Y_SLBEX5KwrlSg_uvnA_0.JPG: 480x640 (no detections), 275.4ms
Speed: 1.0ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zS4Y_SLBEX5KwrlSg_uvnA_90.JPG: 480x640 (no detections), 301.8ms
Speed: 1.2ms preprocess, 301.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zS4Y_SLBEX5KwrlSg_uvnA_180.JPG: 480x640 (no detections), 277.7ms
Speed: 1.2ms preprocess, 277.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zS4Y_SLBEX5KwrlSg_uvnA_270.JPG: 480x640 (no detections), 275.8ms
Speed: 1.2ms preprocess, 275.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zS4fZTvm-sFLEWiOlYAwkQ_0.JPG: 480x640 (no detections), 308.7ms
Speed: 1.0ms preprocess, 308.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zS4fZTvm-sFLEWiOlYAwkQ_90.JPG: 480x640 (no detections), 280.2ms
Speed: 1.3ms preprocess, 280.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zS4fZTvm-sFLEWiOlYAwkQ_180.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zS4fZTvm-sFLEWiOlYAwkQ_270.JPG: 480x640 (no detections), 272.1ms
Speed: 1.0ms preprocess, 272.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zS5vph6ixp4cOR1AAf3seQ_0.JPG: 480x640 (no detections), 271.6ms
Speed: 1.2ms preprocess, 271.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zS5vph6ixp4cOR1AAf3seQ_90.JPG: 480x640 (no detections), 275.2ms
Speed: 1.2ms preprocess, 275.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zS5vph6ixp4cOR1AAf3seQ_180.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zS5vph6ixp4cOR1AAf3seQ_270.JPG: 480x640 (no detections), 274.5ms

Speed: 1.1ms preprocess, 274.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zS93XTmKqdOxeOnc4XWDyQ_0.JPG: 480x640 (no detections), 272.8ms
Speed: 1.0ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zS93XTmKqdOxeOnc4XWDyQ_90.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zS93XTmKqdOxeOnc4XWDyQ_180.JPG: 480x640 (no detections), 278.5ms
Speed: 1.1ms preprocess, 278.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zS93XTmKqdOxeOnc4XWDyQ_270.JPG: 480x640 (no detections), 274.2ms
Speed: 1.0ms preprocess, 274.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zS9XziKnM6oy_GUuMCdj7A_0.JPG: 480x640 (no detections), 281.8ms
Speed: 1.1ms preprocess, 281.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zS9XziKnM6oy_GUuMCdj7A_90.JPG: 480x640 (no detections), 272.2ms
Speed: 1.2ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zS9XziKnM6oy_GUuMCdj7A_180.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zS9XziKnM6oy_GUuMCdj7A_270.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSAMSfYwl19CDKgFZ0pdEg_0.JPG: 480x640 (no detections), 277.3ms
Speed: 1.1ms preprocess, 277.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSAMSfYwl19CDKgFZ0pdEg_90.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSAMSfYwl19CDKgFZ0pdEg_180.JPG: 480x640 (no detections), 269.6ms
Speed: 1.0ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSAMSfYwl19CDKgFZ0pdEg_270.JPG: 480x640 (no detections), 276.2ms
Speed: 1.1ms preprocess, 276.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSE9UaCH27B2Pu5lyGVwGg_0.JPG: 480x640 (no detections), 273.4ms
Speed: 1.0ms preprocess, 273.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSE9UaCH27B2Pu5lyGVwGg_90.JPG: 480x640 (no detections), 270.5ms
Speed: 1.1ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSE9UaCH27B2Pu5lyGVwGg_180.JPG: 480x640 (no detections), 276.2ms
Speed: 1.0ms preprocess, 276.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSE9UaCH27B2Pu5lyGVwGg_270.JPG: 480x640 (no detections), 277.3ms
Speed: 1.0ms preprocess, 277.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSJuD3ip3iRR7OEc4B3qBg_0.JPG: 480x640 (no detections), 273.7ms
Speed: 1.2ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSJuD3ip3iRR7OEc4B3qBg_90.JPG: 480x640 (no detections), 271.2ms
Speed: 1.2ms preprocess, 271.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSJuD3ip3iRR7OEc4B3qBg_180.JPG: 480x640 (no detections), 306.3ms
Speed: 1.0ms preprocess, 306.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSJuD3ip3iRR7OEc4B3qBg_270.JPG: 480x640 (no detections), 271.6ms
Speed: 1.3ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSOgFV5-0mkf609pDguH8A_0.JPG: 480x640 (no detections), 270.2ms
Speed: 1.2ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSOgFV5-0mkf609pDguH8A_90.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSOgFV5-0mkf609pDguH8A_180.JPG: 480x640 (no detections), 277.0ms
Speed: 1.1ms preprocess, 277.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSOgFV5-0mkf609pDguH8A_270.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSQTGALb7mn2UN73qTgrng_0.JPG: 480x640 (no detections), 273.6ms
Speed: 1.2ms preprocess, 273.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSQTGALb7mn2UN73qTgrng_90.JPG: 480x640 (no detections), 278.1ms
Speed: 1.1ms preprocess, 278.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSQTGALb7mn2UN73qTgrng_180.JPG: 480x640 (no detections), 276.7ms
Speed: 1.1ms preprocess, 276.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSQTGALb7mn2UN73qTgrng_270.JPG: 480x640 (no detections), 276.4ms
Speed: 1.0ms preprocess, 276.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSStt6N1ElVvR9XrGfootw_0.JPG: 480x640 (no detections), 288.7ms
Speed: 1.1ms preprocess, 288.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSStt6N1ElVvR9XrGfootw_90.JPG: 480x640 (no detections), 273.6ms
Speed: 1.1ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSStt6N1ElVvR9XrGfootw_180.JPG: 480x640 (no detections), 271.4ms
Speed: 1.0ms preprocess, 271.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSStt6N1ElVvR9XrGfootw_270.JPG: 480x640 (no detections), 271.2ms
Speed: 1.0ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSYVLNOW267TLPSrkXJRjQ_0.JPG: 480x640 (no detections), 275.5ms
Speed: 1.1ms preprocess, 275.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSYVLNOW267TLPSrkXJRjQ_90.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSYVLNOW267TLPSrkXJRjQ_180.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSYVLNOW267TLPSrkXJRjQ_270.JPG: 480x640 (no detections), 271.1ms
Speed: 1.2ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSZh6nfEHNb1mZmVaBAzEA_0.JPG: 480x640 (no detections), 269.6ms
Speed: 1.0ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSZh6nfEHNb1mZmVaBAzEA_90.JPG: 480x640 (no detections), 277.0ms
Speed: 1.0ms preprocess, 277.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSZh6nfEHNb1mZmVaBAzEA_180.JPG: 480x640 (no detections), 289.5ms
Speed: 1.3ms preprocess, 289.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSZh6nfEHNb1mZmVaBAzEA_270.JPG: 480x640 (no detections), 276.4ms
Speed: 1.0ms preprocess, 276.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zS__Bma67l7PoZRlrbyf8w_0.JPG: 480x640 (no detections), 282.2ms
Speed: 1.2ms preprocess, 282.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zS__Bma67l7PoZRlrbyf8w_90.JPG: 480x640 (no detections), 274.0ms
Speed: 1.1ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zS__Bma67l7PoZRlrbyf8w_180.JPG: 480x640 (no detections), 267.7ms
Speed: 1.1ms preprocess, 267.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zS__Bma67l7PoZRlrbyf8w_270.JPG: 480x640 (no detections), 269.9ms
Speed: 1.0ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zScfDrmmdj9OETCxLtN-yQ_0.JPG: 480x640 (no detections), 284.4ms
Speed: 1.0ms preprocess, 284.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zScfDrmmdj9OETCxLtN-yQ_90.JPG: 480x640 (no detections), 285.3ms
Speed: 1.2ms preprocess, 285.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zScfDrmmdj9OETCxLtN-yQ_180.JPG: 480x640 (no detections), 275.9ms
Speed: 1.2ms preprocess, 275.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zScfDrmmdj9OETCxLtN-yQ_270.JPG: 480x640 (no detections), 274.2ms
Speed: 1.2ms preprocess, 274.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSdmwCEQEG-fU3B4O8Zung_0.JPG: 480x640 (no detections), 281.9ms
Speed: 1.1ms preprocess, 281.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSdmwCEQEG-fU3B4O8Zung_90.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSdmwCEQEG-fU3B4O8Zung_180.JPG: 480x640 (no detections), 266.7ms
Speed: 1.0ms preprocess, 266.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSdmwCEQEG-fU3B4O8Zung_270.JPG: 480x640 (no detections), 283.6ms
Speed: 1.1ms preprocess, 283.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSdwd9z4hdKli-kM3fsMbw_0.JPG: 480x640 (no detections), 303.0ms
Speed: 1.1ms preprocess, 303.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSdwd9z4hdKli-kM3fsMbw_90.JPG: 480x640 (no detections), 278.5ms
Speed: 1.1ms preprocess, 278.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSdwd9z4hdKli-kM3fsMbw_180.JPG: 480x640 (no detections), 305.1ms
Speed: 1.3ms preprocess, 305.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSdwd9z4hdKli-kM3fsMbw_270.JPG: 480x640 (no detections), 274.6ms
Speed: 1.1ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSj6RVqnPmS1Kk1paiwNuQ_0.JPG: 480x640 (no detections), 269.6ms
Speed: 1.2ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSj6RVqnPmS1Kk1paiwNuQ_90.JPG: 480x640 (no detections), 272.6ms
Speed: 1.0ms preprocess, 272.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSj6RVqnPmS1Kk1paiwNuQ_180.JPG: 480x640 (no detections), 268.5ms
Speed: 1.1ms preprocess, 268.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSj6RVqnPmS1Kk1paiwNuQ_270.JPG: 480x640 (no detections), 269.4ms
Speed: 1.0ms preprocess, 269.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSjxGLayWa6GH3fZFv9hrQ_0.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSjxGLayWa6GH3fZFv9hrQ_90.JPG: 480x640 (no detections), 270.5ms
Speed: 1.1ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSjxGLayWa6GH3fZFv9hrQ_180.JPG: 480x640 (no detections), 274.2ms
Speed: 1.1ms preprocess, 274.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSjxGLayWa6GH3fZFv9hrQ_270.JPG: 480x640 (no detections), 270.5ms
Speed: 1.1ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSlVUOS3o_k3nSfRMC8-fw_0.JPG: 480x640 (no detections), 269.3ms
Speed: 1.0ms preprocess, 269.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSlVUOS3o_k3nSfRMC8-fw_90.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSlVUOS3o_k3nSfRMC8-fw_180.JPG: 480x640 (no detections), 269.5ms

Speed: 1.0ms preprocess, 269.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSlVUOS3o_k3nSfRMC8-fw_270.JPG: 480x640 (no detections), 273.2ms
Speed: 1.2ms preprocess, 273.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSlrkqDs1kNlANz_wQ-Onw_0.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSlrkqDs1kNlANz_wQ-Onw_90.JPG: 480x640 (no detections), 278.7ms
Speed: 1.0ms preprocess, 278.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSlrkqDs1kNlANz_wQ-Onw_180.JPG: 480x640 1 Waste, 272.9ms
Speed: 1.0ms preprocess, 272.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSlrkqDs1kNlANz_wQ-Onw_270.JPG: 480x640 2 Wastes, 271.4ms
Speed: 1.0ms preprocess, 271.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSqWIkzo7oRu9eovobWCyA_0.JPG: 480x640 (no detections), 271.8ms
Speed: 1.3ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSqWIkzo7oRu9eovobWCyA_90.JPG: 480x640 1 Waste, 272.2ms
Speed: 1.3ms preprocess, 272.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSqWIkzo7oRu9eovobWCyA_180.JPG: 480x640 (no detections), 268.9ms
Speed: 1.1ms preprocess, 268.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSqWIkzo7oRu9eovobWCyA_270.JPG: 480x640 (no detections), 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSwZBdAjKoeARl-w98vqAg_0.JPG: 480x640 (no detections), 266.2ms
Speed: 1.0ms preprocess, 266.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSwZBdAjKoeARl-w98vqAg_90.JPG: 480x640 (no detections), 269.3ms
Speed: 1.0ms preprocess, 269.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSwZBdAjKoeARl-w98vqAg_180.JPG: 480x640 (no detections), 266.7ms
Speed: 1.1ms preprocess, 266.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSwZBdAjKoeARl-w98vqAg_270.JPG: 480x640 (no detections), 273.5ms
Speed: 1.0ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSxlu8K6oErZRt_XzTcnjw_0.JPG: 480x640 (no detections), 273.0ms
Speed: 1.0ms preprocess, 273.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSxlu8K6oErZRt_XzTcnjw_90.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSxlu8K6oErZRt_XzTcnjw_180.JPG: 480x640 (no detections), 274.7ms
Speed: 1.0ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zSxlu8K6oErZRt_XzTcnjw_270.JPG: 480x640 (no detections), 271.2ms
Speed: 1.2ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zT13gEgib5V4xB-EqQ76Zg_0.JPG: 480x640 (no detections), 272.0ms
Speed: 1.4ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zT13gEgib5V4xB-EqQ76Zg_90.JPG: 480x640 (no detections), 276.8ms
Speed: 1.1ms preprocess, 276.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zT13gEgib5V4xB-EqQ76Zg_180.JPG: 480x640 (no detections), 267.1ms
Speed: 1.2ms preprocess, 267.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zT13gEgib5V4xB-EqQ76Zg_270.JPG: 480x640 (no detections), 269.2ms
Speed: 1.1ms preprocess, 269.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zT2mXjf1_8pQb4AVYm_rpw_0.JPG: 480x640 (no detections), 270.2ms
Speed: 1.0ms preprocess, 270.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zT2mXjf1_8pQb4AVYm_rpw_90.JPG: 480x640 (no detections), 273.9ms
Speed: 1.2ms preprocess, 273.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zT2mXjf1_8pQb4AVYm_rpw_180.JPG: 480x640 2 Wastes, 284.4ms
Speed: 1.0ms preprocess, 284.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zT2mXjf1_8pQb4AVYm_rpw_270.JPG: 480x640 (no detections), 270.1ms
Speed: 1.2ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zT9APecdlYtEja6exxIvuQ_0.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zT9APecdlYtEja6exxIvuQ_90.JPG: 480x640 (no detections), 271.7ms
Speed: 1.2ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zT9APecdlYtEja6exxIvuQ_180.JPG: 480x640 (no detections), 268.0ms
Speed: 1.1ms preprocess, 268.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zT9APecdlYtEja6exxIvuQ_270.JPG: 480x640 (no detections), 268.2ms
Speed: 1.0ms preprocess, 268.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTCc1OyfHa11TK-8whdFiQ_0.JPG: 480x640 (no detections), 268.6ms
Speed: 1.0ms preprocess, 268.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTCc1OyfHa11TK-8whdFiQ_90.JPG: 480x640 (no detections), 274.4ms
Speed: 1.2ms preprocess, 274.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTCc1OyfHa11TK-8whdFiQ_180.JPG: 480x640 (no detections), 265.0ms
Speed: 1.1ms preprocess, 265.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTCc1OyfHa11TK-8whdFiQ_270.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTLr-03YO4VDUEHYdFwQuQ_0.JPG: 480x640 (no detections), 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTLr-03YO4VDUEHYdFwQuQ_90.JPG: 480x640 (no detections), 276.2ms
Speed: 1.1ms preprocess, 276.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTLr-03YO4VDUEHYdFwQuQ_180.JPG: 480x640 (no detections), 276.4ms
Speed: 1.0ms preprocess, 276.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTLr-03YO4VDUEHYdFwQuQ_270.JPG: 480x640 (no detections), 273.1ms
Speed: 1.1ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTMrsC0ISBfShg2z5K1Xdg_0.JPG: 480x640 (no detections), 297.8ms
Speed: 1.1ms preprocess, 297.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTMrsC0ISBfShg2z5K1Xdg_90.JPG: 480x640 (no detections), 276.5ms
Speed: 1.2ms preprocess, 276.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTMrsC0ISBfShg2z5K1Xdg_180.JPG: 480x640 1 Waste, 274.6ms
Speed: 1.1ms preprocess, 274.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTMrsC0ISBfShg2z5K1Xdg_270.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTQMDYw5b36Tdfcoa3B-QA_0.JPG: 480x640 (no detections), 267.2ms
Speed: 1.1ms preprocess, 267.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTQMDYw5b36Tdfcoa3B-QA_90.JPG: 480x640 (no detections), 279.2ms
Speed: 1.0ms preprocess, 279.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTQMDYw5b36Tdfcoa3B-QA_180.JPG: 480x640 (no detections), 287.4ms
Speed: 1.1ms preprocess, 287.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTQMDYw5b36Tdfcoa3B-QA_270.JPG: 480x640 (no detections), 275.7ms
Speed: 1.0ms preprocess, 275.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTQXUCZOCRe6QQxpP_v55A_0.JPG: 480x640 (no detections), 275.4ms
Speed: 1.1ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTQXUCZOCRe6QQxpP_v55A_90.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTQXUCZOCRe6QQxpP_v55A_180.JPG: 480x640 (no detections), 277.1ms
Speed: 1.1ms preprocess, 277.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTQXUCZOCRe6QQxpP_v55A_270.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTWT6NKDK5wDVy6bCAhvHw_0.JPG: 480x640 (no detections), 274.2ms
Speed: 1.1ms preprocess, 274.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTWT6NKDK5wDVy6bCAhvHw_90.JPG: 480x640 (no detections), 302.3ms
Speed: 1.2ms preprocess, 302.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTWT6NKDK5wDVy6bCAhvHw_180.JPG: 480x640 1 Waste, 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTWT6NKDK5wDVy6bCAhvHw_270.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTWq86KrcM3kadQJLxONxw_0.JPG: 480x640 (no detections), 269.8ms
Speed: 1.0ms preprocess, 269.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTWq86KrcM3kadQJLxONxw_90.JPG: 480x640 (no detections), 271.3ms
Speed: 1.0ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTWq86KrcM3kadQJLxONxw_180.JPG: 480x640 (no detections), 270.4ms
Speed: 1.0ms preprocess, 270.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTWq86KrcM3kadQJLxONxw_270.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTeNrbCcOxi523ET2arTVg_0.JPG: 480x640 (no detections), 270.8ms
Speed: 1.2ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTeNrbCcOxi523ET2arTVg_90.JPG: 480x640 (no detections), 270.2ms
Speed: 1.2ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTeNrbCcOxi523ET2arTVg_180.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTeNrbCcOxi523ET2arTVg_270.JPG: 480x640 (no detections), 270.2ms
Speed: 1.0ms preprocess, 270.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTiSG3lM95_cHi3hW91WAQ_0.JPG: 480x640 (no detections), 271.0ms
Speed: 1.1ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTiSG3lM95_cHi3hW91WAQ_90.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTiSG3lM95_cHi3hW91WAQ_180.JPG: 480x640 (no detections), 270.9ms
Speed: 1.1ms preprocess, 270.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTiSG3lM95_cHi3hW91WAQ_270.JPG: 480x640 (no detections), 271.0ms
Speed: 1.1ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTioBgnRDgdKEQ287rAiTA_0.JPG: 480x640 (no detections), 272.0ms
Speed: 1.1ms preprocess, 272.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTioBgnRDgdKEQ287rAiTA_90.JPG: 480x640 (no detections), 276.0ms

Speed: 1.2ms preprocess, 276.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTioBgnRDgdKEQ287rAiTA_180.JPG: 480x640 (no detections), 271.9ms
Speed: 1.0ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTioBgnRDgdKEQ287rAiTA_270.JPG: 480x640 (no detections), 273.8ms
Speed: 1.0ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTjVD2GPvoRRV_TSnhbCgw_0.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTjVD2GPvoRRV_TSnhbCgw_90.JPG: 480x640 (no detections), 276.7ms
Speed: 1.1ms preprocess, 276.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTjVD2GPvoRRV_TSnhbCgw_180.JPG: 480x640 (no detections), 277.7ms
Speed: 1.1ms preprocess, 277.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTjVD2GPvoRRV_TSnhbCgw_270.JPG: 480x640 (no detections), 272.4ms
Speed: 1.0ms preprocess, 272.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTmsXe2YFv91dJD2PTBeAg_0.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTmsXe2YFv91dJD2PTBeAg_90.JPG: 480x640 (no detections), 267.6ms
Speed: 1.0ms preprocess, 267.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTmsXe2YFv91dJD2PTBeAg_180.JPG: 480x640 (no detections), 267.3ms
Speed: 1.0ms preprocess, 267.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTmsXe2YFv91dJD2PTBeAg_270.JPG: 480x640 (no detections), 272.0ms
Speed: 1.0ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTollp1PbnHJAOfPfIv7TQ_0.JPG: 480x640 1 Waste, 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTollp1PbnHJAOfPfIv7TQ_90.JPG: 480x640 (no detections), 282.8ms
Speed: 1.0ms preprocess, 282.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTollp1PbnHJAOfPfIv7TQ_180.JPG: 480x640 (no detections), 272.5ms
Speed: 1.5ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTollp1PbnHJAOfPfIv7TQ_270.JPG: 480x640 (no detections), 268.6ms
Speed: 1.1ms preprocess, 268.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTqZ8inFczS30NgTe3Ujhw_0.JPG: 480x640 (no detections), 268.3ms
Speed: 1.1ms preprocess, 268.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTqZ8inFczS30NgTe3Ujhw_90.JPG: 480x640 (no detections), 265.3ms
Speed: 1.6ms preprocess, 265.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTqZ8inFczS30NgTe3Ujhw_180.JPG: 480x640 (no detections), 273.2ms
Speed: 1.0ms preprocess, 273.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTqZ8inFczS30NgTe3Ujhw_270.JPG: 480x640 (no detections), 274.8ms
Speed: 1.1ms preprocess, 274.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTrlj_t3NAScak4q61Wogg_0.JPG: 480x640 (no detections), 267.5ms
Speed: 1.1ms preprocess, 267.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTrlj_t3NAScak4q61Wogg_90.JPG: 480x640 (no detections), 271.0ms
Speed: 1.0ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTrlj_t3NAScak4q61Wogg_180.JPG: 480x640 (no detections), 275.0ms
Speed: 1.3ms preprocess, 275.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTrlj_t3NAScak4q61Wogg_270.JPG: 480x640 (no detections), 267.4ms
Speed: 1.0ms preprocess, 267.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTs4JEnAWNbk5zoUrMyY7w_0.JPG: 480x640 (no detections), 269.2ms
Speed: 1.0ms preprocess, 269.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTs4JEnAWNbk5zoUrMyY7w_90.JPG: 480x640 (no detections), 272.5ms
Speed: 1.1ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTs4JEnAWNbk5zoUrMyY7w_180.JPG: 480x640 (no detections), 270.7ms
Speed: 1.0ms preprocess, 270.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTs4JEnAWNbk5zoUrMyY7w_270.JPG: 480x640 (no detections), 269.2ms
Speed: 1.1ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTstCeN_11hSxvWyeCwV-A_0.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTstCeN_11hSxvWyeCwV-A_90.JPG: 480x640 (no detections), 272.6ms
Speed: 1.0ms preprocess, 272.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTstCeN_11hSxvWyeCwV-A_180.JPG: 480x640 (no detections), 274.9ms
Speed: 1.1ms preprocess, 274.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zTstCeN_11hSxvWyeCwV-A_270.JPG: 480x640 (no detections), 268.4ms
Speed: 1.0ms preprocess, 268.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zU-DWM-dU5fvnRei7eaMXg_0.JPG: 480x640 (no detections), 270.4ms
Speed: 1.0ms preprocess, 270.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zU-DWM-dU5fvnRei7eaMXg_90.JPG: 480x640 (no detections), 297.9ms
Speed: 1.1ms preprocess, 297.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zU-DWM-dU5fvnRei7eaMXg_180.JPG: 480x640 (no detections), 273.4ms
Speed: 1.2ms preprocess, 273.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zU-DWM-dU5fvnRei7eaMXg_270.JPG: 480x640 (no detections), 287.5ms
Speed: 1.0ms preprocess, 287.5ms inference, 3.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zU02ut_K9PSLiJ1NtQUtiQ_0.JPG: 480x640 1 Waste, 287.5ms
Speed: 1.8ms preprocess, 287.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zU02ut_K9PSLiJ1NtQUtiQ_90.JPG: 480x640 (no detections), 284.0ms
Speed: 1.2ms preprocess, 284.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zU02ut_K9PSLiJ1NtQUtiQ_180.JPG: 480x640 (no detections), 279.6ms
Speed: 1.2ms preprocess, 279.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zU02ut_K9PSLiJ1NtQUtiQ_270.JPG: 480x640 (no detections), 327.2ms
Speed: 1.1ms preprocess, 327.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zU1ciu2QDxB5V9dvJYMRrQ_0.JPG: 480x640 (no detections), 290.4ms
Speed: 1.4ms preprocess, 290.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zU1ciu2QDxB5V9dvJYMRrQ_90.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zU1ciu2QDxB5V9dvJYMRrQ_180.JPG: 480x640 (no detections), 269.1ms
Speed: 1.1ms preprocess, 269.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zU1ciu2QDxB5V9dvJYMRrQ_270.JPG: 480x640 (no detections), 269.9ms
Speed: 1.0ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zU2Bc63RJeggTmn0YHLRDw_0.JPG: 480x640 (no detections), 290.0ms
Speed: 1.0ms preprocess, 290.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zU2Bc63RJeggTmn0YHLRDw_90.JPG: 480x640 (no detections), 286.2ms
Speed: 1.2ms preprocess, 286.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zU2Bc63RJeggTmn0YHLRDw_180.JPG: 480x640 (no detections), 277.3ms
Speed: 1.1ms preprocess, 277.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zU2Bc63RJeggTmn0YHLRDw_270.JPG: 480x640 (no detections), 279.1ms
Speed: 1.1ms preprocess, 279.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUAlQ-7npu34twtIjjFt6w_0.JPG: 480x640 1 Waste, 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUAlQ-7npu34twtIjjFt6w_90.JPG: 480x640 1 Waste, 318.8ms
Speed: 1.2ms preprocess, 318.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUAlQ-7npu34twtIjjFt6w_180.JPG: 480x640 3 Wastes, 274.0ms
Speed: 1.0ms preprocess, 274.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUAlQ-7npu34twtIjjFt6w_270.JPG: 480x640 1 Waste, 286.4ms
Speed: 1.1ms preprocess, 286.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUBSsKh18tCCnQdlEFNRAg_0.JPG: 480x640 (no detections), 296.4ms
Speed: 1.1ms preprocess, 296.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUBSsKh18tCCnQdlEFNRAg_90.JPG: 480x640 (no detections), 272.3ms
Speed: 1.4ms preprocess, 272.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUBSsKh18tCCnQdlEFNRAg_180.JPG: 480x640 (no detections), 276.8ms
Speed: 1.1ms preprocess, 276.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUBSsKh18tCCnQdlEFNRAg_270.JPG: 480x640 (no detections), 273.2ms
Speed: 1.1ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUBVqrvACoz3okddhMrZ0g_0.JPG: 480x640 (no detections), 273.1ms
Speed: 1.1ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUBVqrvACoz3okddhMrZ0g_90.JPG: 480x640 (no detections), 276.4ms
Speed: 1.1ms preprocess, 276.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUBVqrvACoz3okddhMrZ0g_180.JPG: 480x640 (no detections), 271.1ms
Speed: 1.2ms preprocess, 271.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUBVqrvACoz3okddhMrZ0g_270.JPG: 480x640 (no detections), 274.4ms
Speed: 1.1ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUDiPnqLwmrqVoKE46JUQA_0.JPG: 480x640 (no detections), 269.5ms
Speed: 1.0ms preprocess, 269.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUDiPnqLwmrqVoKE46JUQA_90.JPG: 480x640 (no detections), 274.8ms
Speed: 1.1ms preprocess, 274.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUDiPnqLwmrqVoKE46JUQA_180.JPG: 480x640 1 Waste, 287.8ms
Speed: 1.1ms preprocess, 287.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUDiPnqLwmrqVoKE46JUQA_270.JPG: 480x640 (no detections), 275.2ms
Speed: 1.4ms preprocess, 275.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUFcZrDDydKXtHBiy3rStQ_0.JPG: 480x640 (no detections), 270.5ms
Speed: 1.1ms preprocess, 270.5ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUFcZrDDydKXtHBiy3rStQ_90.JPG: 480x640 (no detections), 265.6ms
Speed: 1.0ms preprocess, 265.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUFcZrDDydKXtHBiy3rStQ_180.JPG: 480x640 (no detections), 272.6ms
Speed: 1.0ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUFcZrDDydKXtHBiy3rStQ_270.JPG: 480x640 (no detections), 275.0ms
Speed: 1.1ms preprocess, 275.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUMLUVq-0w44gUGvDvuIJA_0.JPG: 480x640 (no detections), 272.3ms

Speed: 1.1ms preprocess, 272.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUMLUVq-0w44gUGvDvuIJA_90.JPG: 480x640 (no detections), 275.5ms
Speed: 1.1ms preprocess, 275.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUMLUVq-0w44gUGvDvuIJA_180.JPG: 480x640 (no detections), 277.2ms
Speed: 1.1ms preprocess, 277.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUMLUVq-0w44gUGvDvuIJA_270.JPG: 480x640 (no detections), 289.6ms
Speed: 1.0ms preprocess, 289.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUNi5AfIA-IoG91sQAW0Cg_0.JPG: 480x640 (no detections), 286.8ms
Speed: 1.2ms preprocess, 286.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUNi5AfIA-IoG91sQAW0Cg_90.JPG: 480x640 (no detections), 277.5ms
Speed: 1.3ms preprocess, 277.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUNi5AfIA-IoG91sQAW0Cg_180.JPG: 480x640 (no detections), 272.9ms
Speed: 1.2ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUNi5AfIA-IoG91sQAW0Cg_270.JPG: 480x640 (no detections), 272.1ms
Speed: 1.1ms preprocess, 272.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUR-SsAXG6kFJVXota0l-w_0.JPG: 480x640 (no detections), 271.7ms
Speed: 1.2ms preprocess, 271.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUR-SsAXG6kFJVXota0l-w_90.JPG: 480x640 (no detections), 269.2ms
Speed: 1.1ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUR-SsAXG6kFJVXota0l-w_180.JPG: 480x640 (no detections), 269.0ms
Speed: 1.1ms preprocess, 269.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUR-SsAXG6kFJVXota0l-w_270.JPG: 480x640 (no detections), 270.5ms
Speed: 1.0ms preprocess, 270.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUW2mZlkVqPixt9GIt6DZQ_0.JPG: 480x640 (no detections), 275.2ms
Speed: 1.1ms preprocess, 275.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUW2mZlkVqPixt9GIt6DZQ_90.JPG: 480x640 (no detections), 310.8ms
Speed: 1.2ms preprocess, 310.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUW2mZlkVqPixt9GIt6DZQ_180.JPG: 480x640 (no detections), 265.4ms
Speed: 1.1ms preprocess, 265.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUW2mZlkVqPixt9GIt6DZQ_270.JPG: 480x640 (no detections), 272.6ms
Speed: 1.6ms preprocess, 272.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUXtHNzblPq1ydV3XjSaUQ_0.JPG: 480x640 (no detections), 272.0ms
Speed: 1.0ms preprocess, 272.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUXtHNzblPq1ydV3XjSaUQ_90.JPG: 480x640 (no detections), 312.4ms
Speed: 1.1ms preprocess, 312.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUXtHNzblPq1ydV3XjSaUQ_180.JPG: 480x640 (no detections), 282.8ms
Speed: 1.2ms preprocess, 282.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUXtHNzblPq1ydV3XjSaUQ_270.JPG: 480x640 (no detections), 272.7ms
Speed: 1.2ms preprocess, 272.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUiUeX1kCkVj6U-wxVvv1w_0.JPG: 480x640 (no detections), 274.0ms
Speed: 1.2ms preprocess, 274.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUiUeX1kCkVj6U-wxVvv1w_90.JPG: 480x640 (no detections), 268.8ms
Speed: 1.1ms preprocess, 268.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUiUeX1kCkVj6U-wxVvv1w_180.JPG: 480x640 (no detections), 269.8ms
Speed: 1.0ms preprocess, 269.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUiUeX1kCkVj6U-wxVvv1w_270.JPG: 480x640 (no detections), 273.2ms
Speed: 1.2ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUkK39B00wQ0GnMxyPIDuA_0.JPG: 480x640 (no detections), 305.1ms
Speed: 1.1ms preprocess, 305.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUkK39B00wQ0GnMxyPIDuA_90.JPG: 480x640 (no detections), 275.2ms
Speed: 1.1ms preprocess, 275.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUkK39B00wQ0GnMxyPIDuA_180.JPG: 480x640 (no detections), 271.0ms
Speed: 1.0ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUkK39B00wQ0GnMxyPIDuA_270.JPG: 480x640 (no detections), 271.0ms
Speed: 1.1ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUm3SLVPiQUg-GF0EsmRIg_0.JPG: 480x640 (no detections), 279.8ms
Speed: 1.4ms preprocess, 279.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUm3SLVPiQUg-GF0EsmRIg_90.JPG: 480x640 (no detections), 273.5ms
Speed: 1.0ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUm3SLVPiQUg-GF0EsmRIg_180.JPG: 480x640 (no detections), 277.9ms
Speed: 1.2ms preprocess, 277.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUm3SLVPiQUg-GF0EsmRIg_270.JPG: 480x640 (no detections), 267.0ms
Speed: 1.2ms preprocess, 267.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUpjUARzslFT1_hoWaRBNw_0.JPG: 480x640 (no detections), 273.4ms
Speed: 1.0ms preprocess, 273.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUpjUARzslFT1_hoWaRBNw_90.JPG: 480x640 (no detections), 278.8ms
Speed: 1.3ms preprocess, 278.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUpjUARzslFT1_hoWaRBNw_180.JPG: 480x640 (no detections), 281.7ms
Speed: 1.2ms preprocess, 281.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUpjUARzslFT1_hoWaRBNw_270.JPG: 480x640 (no detections), 277.8ms
Speed: 1.2ms preprocess, 277.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUw5Vn9TLY4RjmBq3BnlCA_0.JPG: 480x640 (no detections), 269.9ms
Speed: 1.4ms preprocess, 269.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUw5Vn9TLY4RjmBq3BnlCA_90.JPG: 480x640 (no detections), 274.1ms
Speed: 1.2ms preprocess, 274.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUw5Vn9TLY4RjmBq3BnlCA_180.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUw5Vn9TLY4RjmBq3BnlCA_270.JPG: 480x640 (no detections), 275.7ms
Speed: 1.3ms preprocess, 275.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUw9CSGzvDkAO3H5LCkLUQ_0.JPG: 480x640 (no detections), 274.9ms
Speed: 1.3ms preprocess, 274.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUw9CSGzvDkAO3H5LCkLUQ_90.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUw9CSGzvDkAO3H5LCkLUQ_180.JPG: 480x640 (no detections), 278.2ms
Speed: 1.3ms preprocess, 278.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zUw9CSGzvDkAO3H5LCkLUQ_270.JPG: 480x640 (no detections), 276.0ms
Speed: 1.2ms preprocess, 276.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zV9ydwiu6BuQayFLGxEKxA_0.JPG: 480x640 (no detections), 270.7ms
Speed: 1.4ms preprocess, 270.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zV9ydwiu6BuQayFLGxEKxA_90.JPG: 480x640 (no detections), 274.7ms
Speed: 1.2ms preprocess, 274.7ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zV9ydwiu6BuQayFLGxEKxA_180.JPG: 480x640 (no detections), 273.7ms
Speed: 1.2ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zV9ydwiu6BuQayFLGxEKxA_270.JPG: 480x640 (no detections), 287.0ms
Speed: 1.7ms preprocess, 287.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVAYDEiNN80R7XJD1UWG8w_0.JPG: 480x640 (no detections), 297.8ms
Speed: 1.2ms preprocess, 297.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVAYDEiNN80R7XJD1UWG8w_90.JPG: 480x640 (no detections), 354.8ms
Speed: 1.4ms preprocess, 354.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVAYDEiNN80R7XJD1UWG8w_180.JPG: 480x640 (no detections), 357.1ms
Speed: 2.1ms preprocess, 357.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVAYDEiNN80R7XJD1UWG8w_270.JPG: 480x640 (no detections), 325.3ms
Speed: 1.3ms preprocess, 325.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVAi2guQrhjjZ1lwgoecoQ_0.JPG: 480x640 1 Waste, 316.1ms
Speed: 1.8ms preprocess, 316.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVAi2guQrhjjZ1lwgoecoQ_90.JPG: 480x640 1 Waste, 281.8ms
Speed: 1.4ms preprocess, 281.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVAi2guQrhjjZ1lwgoecoQ_180.JPG: 480x640 (no detections), 274.1ms
Speed: 1.2ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVAi2guQrhjjZ1lwgoecoQ_270.JPG: 480x640 (no detections), 274.2ms
Speed: 1.1ms preprocess, 274.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVB9T-P-8SCdmDsBEYri8w_0.JPG: 480x640 (no detections), 277.0ms
Speed: 1.0ms preprocess, 277.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVB9T-P-8SCdmDsBEYri8w_90.JPG: 480x640 (no detections), 268.6ms
Speed: 1.0ms preprocess, 268.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVB9T-P-8SCdmDsBEYri8w_180.JPG: 480x640 (no detections), 285.1ms
Speed: 1.0ms preprocess, 285.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVB9T-P-8SCdmDsBEYri8w_270.JPG: 480x640 (no detections), 267.9ms
Speed: 1.2ms preprocess, 267.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVBOQwAjcxK_CY7teEXemA_0.JPG: 480x640 (no detections), 275.9ms
Speed: 1.2ms preprocess, 275.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVBOQwAjcxK_CY7teEXemA_90.JPG: 480x640 (no detections), 270.3ms
Speed: 1.0ms preprocess, 270.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVBOQwAjcxK_CY7teEXemA_180.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVBOQwAjcxK_CY7teEXemA_270.JPG: 480x640 (no detections), 268.5ms
Speed: 1.0ms preprocess, 268.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVBrwSev0Zj7nDNYtDBQAg_0.JPG: 480x640 2 Wastes, 271.4ms
Speed: 1.0ms preprocess, 271.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVBrwSev0Zj7nDNYtDBQAg_90.JPG: 480x640 (no detections), 269.0ms
Speed: 1.1ms preprocess, 269.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVBrwSev0Zj7nDNYtDBQAg_180.JPG: 480x640 (no detections), 274.1ms
Speed: 1.4ms preprocess, 274.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVBrwSev0Zj7nDNYtDBQAg_270.JPG: 480x640 (no detections), 275.8ms

Speed: 1.0ms preprocess, 275.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVDGvaN4BnqPLiQ5F_T1RQ_0.JPG: 480x640 (no detections), 270.7ms
Speed: 1.2ms preprocess, 270.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVDGvaN4BnqPLiQ5F_T1RQ_90.JPG: 480x640 (no detections), 268.1ms
Speed: 1.1ms preprocess, 268.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVDGvaN4BnqPLiQ5F_T1RQ_180.JPG: 480x640 (no detections), 270.0ms
Speed: 1.0ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVDGvaN4BnqPLiQ5F_T1RQ_270.JPG: 480x640 (no detections), 269.4ms
Speed: 1.1ms preprocess, 269.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVDYat_guuNnsZ9DemVKwA_0.JPG: 480x640 (no detections), 269.9ms
Speed: 1.0ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVDYat_guuNnsZ9DemVKwA_90.JPG: 480x640 (no detections), 272.8ms
Speed: 1.0ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVDYat_guuNnsZ9DemVKwA_180.JPG: 480x640 1 Waste, 271.1ms
Speed: 1.0ms preprocess, 271.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVDYat_guuNnsZ9DemVKwA_270.JPG: 480x640 (no detections), 269.3ms
Speed: 1.1ms preprocess, 269.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVEv1xAk0obc26p-N9nYhw_0.JPG: 480x640 (no detections), 271.1ms
Speed: 1.2ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVEv1xAk0obc26p-N9nYhw_90.JPG: 480x640 (no detections), 270.9ms
Speed: 1.0ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVEv1xAk0obc26p-N9nYhw_180.JPG: 480x640 (no detections), 276.7ms
Speed: 1.2ms preprocess, 276.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVEv1xAk0obc26p-N9nYhw_270.JPG: 480x640 (no detections), 275.9ms
Speed: 1.0ms preprocess, 275.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVFMva69rIp6NIRD9opVlQ_0.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVFMva69rIp6NIRD9opVlQ_90.JPG: 480x640 (no detections), 268.1ms
Speed: 1.0ms preprocess, 268.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVFMva69rIp6NIRD9opVlQ_180.JPG: 480x640 (no detections), 267.6ms
Speed: 1.1ms preprocess, 267.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVFMva69rIp6NIRD9opVlQ_270.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVFitcuKysfegdM2lC96LQ_0.JPG: 480x640 (no detections), 268.4ms
Speed: 1.0ms preprocess, 268.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVFitcuKysfegdM2lC96LQ_90.JPG: 480x640 (no detections), 269.4ms
Speed: 1.1ms preprocess, 269.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVFitcuKysfegdM2lC96LQ_180.JPG: 480x640 (no detections), 266.7ms
Speed: 1.2ms preprocess, 266.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVFitcuKysfegdM2lC96LQ_270.JPG: 480x640 (no detections), 271.0ms
Speed: 1.1ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVHVHBwZmla6mVf6ucHCtA_0.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVHVHBwZmla6mVf6ucHCtA_90.JPG: 480x640 (no detections), 292.8ms
Speed: 1.1ms preprocess, 292.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVHVHBwZmla6mVf6ucHCtA_180.JPG: 480x640 (no detections), 278.6ms
Speed: 1.1ms preprocess, 278.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVHVHBwZmla6mVf6ucHCtA_270.JPG: 480x640 (no detections), 271.1ms
Speed: 1.0ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVKGuz0erxT93FPUkK0pag_0.JPG: 480x640 (no detections), 280.0ms
Speed: 1.0ms preprocess, 280.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVKGuz0erxT93FPUkK0pag_90.JPG: 480x640 (no detections), 286.6ms
Speed: 1.0ms preprocess, 286.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVKGuz0erxT93FPUkK0pag_180.JPG: 480x640 (no detections), 335.3ms
Speed: 1.6ms preprocess, 335.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVKGuz0erxT93FPUkK0pag_270.JPG: 480x640 (no detections), 284.8ms
Speed: 1.3ms preprocess, 284.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVLfbxP2kNeU_8ngqtxvZw_0.JPG: 480x640 (no detections), 287.5ms
Speed: 1.0ms preprocess, 287.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVLfbxP2kNeU_8ngqtxvZw_90.JPG: 480x640 (no detections), 277.2ms
Speed: 1.1ms preprocess, 277.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVLfbxP2kNeU_8ngqtxvZw_180.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVLfbxP2kNeU_8ngqtxvZw_270.JPG: 480x640 (no detections), 267.6ms
Speed: 1.1ms preprocess, 267.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVLrkCQ1VbDIOHPnPvpC4w_0.JPG: 480x640 1 Waste, 274.4ms
Speed: 1.2ms preprocess, 274.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVLrkCQ1VbDIOHPnPvpC4w_90.JPG: 480x640 (no detections), 309.0ms
Speed: 1.2ms preprocess, 309.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVLrkCQ1VbDIOHPnPvpC4w_180.JPG: 480x640 (no detections), 328.0ms
Speed: 1.2ms preprocess, 328.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVLrkCQ1VbDIOHPnPvpC4w_270.JPG: 480x640 1 Waste, 284.4ms
Speed: 1.1ms preprocess, 284.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVPw9T1LJgWyQY-nTSRGmg_0.JPG: 480x640 (no detections), 283.2ms
Speed: 1.1ms preprocess, 283.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVPw9T1LJgWyQY-nTSRGmg_90.JPG: 480x640 (no detections), 286.3ms
Speed: 1.3ms preprocess, 286.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVPw9T1LJgWyQY-nTSRGmg_180.JPG: 480x640 (no detections), 275.4ms
Speed: 1.1ms preprocess, 275.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVPw9T1LJgWyQY-nTSRGmg_270.JPG: 480x640 (no detections), 276.5ms
Speed: 1.2ms preprocess, 276.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVRwYPG5tHNEDZzM4M91pg_0.JPG: 480x640 (no detections), 268.1ms
Speed: 1.1ms preprocess, 268.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVRwYPG5tHNEDZzM4M91pg_90.JPG: 480x640 (no detections), 275.4ms
Speed: 1.0ms preprocess, 275.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVRwYPG5tHNEDZzM4M91pg_180.JPG: 480x640 (no detections), 269.5ms
Speed: 1.1ms preprocess, 269.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVRwYPG5tHNEDZzM4M91pg_270.JPG: 480x640 1 Waste, 267.6ms
Speed: 1.1ms preprocess, 267.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVTW1lXVy2a8GoP6uW07Ng_0.JPG: 480x640 (no detections), 276.7ms
Speed: 1.0ms preprocess, 276.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVTW1lXVy2a8GoP6uW07Ng_90.JPG: 480x640 (no detections), 274.4ms
Speed: 1.0ms preprocess, 274.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVTW1lXVy2a8GoP6uW07Ng_180.JPG: 480x640 (no detections), 272.8ms
Speed: 1.2ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVTW1lXVy2a8GoP6uW07Ng_270.JPG: 480x640 (no detections), 266.8ms
Speed: 1.1ms preprocess, 266.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVUAXWT39n5m4Iqz6GB9Dw_0.JPG: 480x640 (no detections), 291.9ms
Speed: 1.1ms preprocess, 291.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVUAXWT39n5m4Iqz6GB9Dw_90.JPG: 480x640 (no detections), 274.1ms
Speed: 1.2ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVUAXWT39n5m4Iqz6GB9Dw_180.JPG: 480x640 (no detections), 294.3ms
Speed: 1.2ms preprocess, 294.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVUAXWT39n5m4Iqz6GB9Dw_270.JPG: 480x640 (no detections), 270.3ms
Speed: 1.0ms preprocess, 270.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVUVIUH_TjaKst1xIdPppw_0.JPG: 480x640 (no detections), 283.8ms
Speed: 1.2ms preprocess, 283.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVUVIUH_TjaKst1xIdPppw_90.JPG: 480x640 (no detections), 276.3ms
Speed: 1.1ms preprocess, 276.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVUVIUH_TjaKst1xIdPppw_180.JPG: 480x640 (no detections), 270.7ms
Speed: 1.0ms preprocess, 270.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVUVIUH_TjaKst1xIdPppw_270.JPG: 480x640 (no detections), 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVZ-vAZWiLxPPc0aO8boPA_0.JPG: 480x640 (no detections), 304.5ms
Speed: 1.1ms preprocess, 304.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVZ-vAZWiLxPPc0aO8boPA_90.JPG: 480x640 (no detections), 280.6ms
Speed: 1.1ms preprocess, 280.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVZ-vAZWiLxPPc0aO8boPA_180.JPG: 480x640 (no detections), 283.8ms
Speed: 1.2ms preprocess, 283.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVZ-vAZWiLxPPc0aO8boPA_270.JPG: 480x640 (no detections), 302.6ms
Speed: 1.1ms preprocess, 302.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVZqWqydGxJiWbNwnmveog_0.JPG: 480x640 (no detections), 310.4ms
Speed: 1.4ms preprocess, 310.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVZqWqydGxJiWbNwnmveog_90.JPG: 480x640 (no detections), 324.8ms
Speed: 1.1ms preprocess, 324.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVZqWqydGxJiWbNwnmveog_180.JPG: 480x640 (no detections), 355.0ms
Speed: 1.3ms preprocess, 355.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVZqWqydGxJiWbNwnmveog_270.JPG: 480x640 (no detections), 273.8ms
Speed: 1.3ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zV_4HSQCb9VAuSR0zKbjXA_0.JPG: 480x640 (no detections), 276.2ms
Speed: 1.1ms preprocess, 276.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zV_4HSQCb9VAuSR0zKbjXA_90.JPG: 480x640 (no detections), 277.0ms
Speed: 1.1ms preprocess, 277.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zV_4HSQCb9VAuSR0zKbjXA_180.JPG: 480x640 (no detections), 268.2ms

Speed: 1.1ms preprocess, 268.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zV_4HSQCb9VAuSR0zKbjXA_270.JPG: 480x640 (no detections), 277.5ms
Speed: 1.2ms preprocess, 277.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVcVGwlN64HxPkOf34X3ZQ_0.JPG: 480x640 (no detections), 270.4ms
Speed: 1.3ms preprocess, 270.4ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVcVGwlN64HxPkOf34X3ZQ_90.JPG: 480x640 (no detections), 270.0ms
Speed: 1.0ms preprocess, 270.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVcVGwlN64HxPkOf34X3ZQ_180.JPG: 480x640 (no detections), 309.6ms
Speed: 1.3ms preprocess, 309.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVcVGwlN64HxPkOf34X3ZQ_270.JPG: 480x640 (no detections), 329.0ms
Speed: 1.1ms preprocess, 329.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVdQUBU4bLmRWiFlorjaTw_0.JPG: 480x640 (no detections), 289.3ms
Speed: 1.2ms preprocess, 289.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVdQUBU4bLmRWiFlorjaTw_90.JPG: 480x640 (no detections), 274.4ms
Speed: 1.1ms preprocess, 274.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVdQUBU4bLmRWiFlorjaTw_180.JPG: 480x640 (no detections), 315.0ms
Speed: 1.1ms preprocess, 315.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVdQUBU4bLmRWiFlorjaTw_270.JPG: 480x640 (no detections), 280.8ms
Speed: 1.2ms preprocess, 280.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVf3YzG2EVgOyBPM3q2H2A_0.JPG: 480x640 (no detections), 302.9ms
Speed: 1.1ms preprocess, 302.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVf3YzG2EVgOyBPM3q2H2A_90.JPG: 480x640 (no detections), 282.7ms
Speed: 1.2ms preprocess, 282.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVf3YzG2EVgOyBPM3q2H2A_180.JPG: 480x640 (no detections), 274.5ms
Speed: 1.2ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVf3YzG2EVgOyBPM3q2H2A_270.JPG: 480x640 (no detections), 281.6ms
Speed: 1.0ms preprocess, 281.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVf3vaenl11QPL1ZXqfcGw_0.JPG: 480x640 (no detections), 273.2ms
Speed: 1.1ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVf3vaenl11QPL1ZXqfcGw_90.JPG: 480x640 (no detections), 267.2ms
Speed: 1.1ms preprocess, 267.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVf3vaenl11QPL1ZXqfcGw_180.JPG: 480x640 (no detections), 332.2ms
Speed: 1.4ms preprocess, 332.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVf3vaenl11QPL1ZXqfcGw_270.JPG: 480x640 (no detections), 379.7ms
Speed: 1.2ms preprocess, 379.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVoOOHY6G8OmaiCfdSvy6Q_0.JPG: 480x640 (no detections), 283.2ms
Speed: 1.2ms preprocess, 283.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVoOOHY6G8OmaiCfdSvy6Q_90.JPG: 480x640 (no detections), 330.2ms
Speed: 1.1ms preprocess, 330.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVoOOHY6G8OmaiCfdSvy6Q_180.JPG: 480x640 (no detections), 294.5ms
Speed: 1.2ms preprocess, 294.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVoOOHY6G8OmaiCfdSvy6Q_270.JPG: 480x640 (no detections), 277.5ms
Speed: 1.1ms preprocess, 277.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVo_IE3TVaLCx5UQTT10uQ_0.JPG: 480x640 (no detections), 278.5ms
Speed: 1.1ms preprocess, 278.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVo_IE3TVaLCx5UQTT10uQ_90.JPG: 480x640 (no detections), 281.1ms
Speed: 1.0ms preprocess, 281.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVo_IE3TVaLCx5UQTT10uQ_180.JPG: 480x640 (no detections), 273.9ms
Speed: 1.2ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVo_IE3TVaLCx5UQTT10uQ_270.JPG: 480x640 (no detections), 266.0ms
Speed: 1.0ms preprocess, 266.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVohp1xohelbOWopGD42zQ_0.JPG: 480x640 (no detections), 276.4ms
Speed: 1.0ms preprocess, 276.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVohp1xohelbOWopGD42zQ_90.JPG: 480x640 (no detections), 284.8ms
Speed: 1.1ms preprocess, 284.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVohp1xohelbOWopGD42zQ_180.JPG: 480x640 (no detections), 277.0ms
Speed: 1.0ms preprocess, 277.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVohp1xohelbOWopGD42zQ_270.JPG: 480x640 (no detections), 276.6ms
Speed: 1.1ms preprocess, 276.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVsCkLIarWs5GQdXjWLLuA_0.JPG: 480x640 (no detections), 267.6ms
Speed: 1.1ms preprocess, 267.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVsCkLIarWs5GQdXjWLLuA_90.JPG: 480x640 (no detections), 274.9ms
Speed: 1.2ms preprocess, 274.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVsCkLIarWs5GQdXjWLLuA_180.JPG: 480x640 1 Waste, 273.8ms
Speed: 1.2ms preprocess, 273.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVsCkLIarWs5GQdXjWLLuA_270.JPG: 480x640 (no detections), 277.2ms
Speed: 1.1ms preprocess, 277.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVsKU__Aju0y7jdZXIrBwQ_0.JPG: 480x640 (no detections), 280.5ms
Speed: 1.0ms preprocess, 280.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVsKU__Aju0y7jdZXIrBwQ_90.JPG: 480x640 (no detections), 274.8ms
Speed: 1.2ms preprocess, 274.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVsKU__Aju0y7jdZXIrBwQ_180.JPG: 480x640 (no detections), 274.1ms
Speed: 1.2ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVsKU__Aju0y7jdZXIrBwQ_270.JPG: 480x640 1 Waste, 272.6ms
Speed: 1.2ms preprocess, 272.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVxhZ1hg7UH6LN3CwaklJQ_0.JPG: 480x640 (no detections), 272.9ms
Speed: 1.0ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVxhZ1hg7UH6LN3CwaklJQ_90.JPG: 480x640 (no detections), 278.2ms
Speed: 1.2ms preprocess, 278.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVxhZ1hg7UH6LN3CwaklJQ_180.JPG: 480x640 (no detections), 278.0ms
Speed: 1.1ms preprocess, 278.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVxhZ1hg7UH6LN3CwaklJQ_270.JPG: 480x640 (no detections), 273.5ms
Speed: 1.0ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVyChs098QaMYAcdYDm1jw_0.JPG: 480x640 (no detections), 282.6ms
Speed: 1.3ms preprocess, 282.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVyChs098QaMYAcdYDm1jw_90.JPG: 480x640 (no detections), 307.6ms
Speed: 1.0ms preprocess, 307.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVyChs098QaMYAcdYDm1jw_180.JPG: 480x640 (no detections), 309.5ms
Speed: 1.1ms preprocess, 309.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zVyChs098QaMYAcdYDm1jw_270.JPG: 480x640 (no detections), 280.9ms
Speed: 1.2ms preprocess, 280.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zW2YCVR-hXuDG9WlVmIfgw_0.JPG: 480x640 (no detections), 279.0ms
Speed: 1.0ms preprocess, 279.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zW2YCVR-hXuDG9WlVmIfgw_90.JPG: 480x640 (no detections), 274.0ms
Speed: 1.1ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zW2YCVR-hXuDG9WlVmIfgw_180.JPG: 480x640 (no detections), 281.4ms
Speed: 1.0ms preprocess, 281.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zW2YCVR-hXuDG9WlVmIfgw_270.JPG: 480x640 (no detections), 274.5ms
Speed: 1.0ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zW85AHlrfQxx-Y5X-jIxBA_0.JPG: 480x640 (no detections), 282.6ms
Speed: 1.0ms preprocess, 282.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zW85AHlrfQxx-Y5X-jIxBA_90.JPG: 480x640 (no detections), 276.8ms
Speed: 1.2ms preprocess, 276.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zW85AHlrfQxx-Y5X-jIxBA_180.JPG: 480x640 (no detections), 277.8ms
Speed: 1.1ms preprocess, 277.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zW85AHlrfQxx-Y5X-jIxBA_270.JPG: 480x640 (no detections), 270.0ms
Speed: 1.0ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWF2UQ2ucURqVSZGh-nkVA_0.JPG: 480x640 (no detections), 288.1ms
Speed: 1.3ms preprocess, 288.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWF2UQ2ucURqVSZGh-nkVA_90.JPG: 480x640 (no detections), 273.7ms
Speed: 1.2ms preprocess, 273.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWF2UQ2ucURqVSZGh-nkVA_180.JPG: 480x640 (no detections), 271.0ms
Speed: 1.1ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWF2UQ2ucURqVSZGh-nkVA_270.JPG: 480x640 (no detections), 269.0ms
Speed: 1.0ms preprocess, 269.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWG-vEM8UMei_gjdiK7Igg_0.JPG: 480x640 (no detections), 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWG-vEM8UMei_gjdiK7Igg_90.JPG: 480x640 (no detections), 273.6ms
Speed: 1.0ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWG-vEM8UMei_gjdiK7Igg_180.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWG-vEM8UMei_gjdiK7Igg_270.JPG: 480x640 (no detections), 282.9ms
Speed: 1.2ms preprocess, 282.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWGiOj1H3LORhYFn6NmVUg_0.JPG: 480x640 (no detections), 276.5ms
Speed: 1.1ms preprocess, 276.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWGiOj1H3LORhYFn6NmVUg_90.JPG: 480x640 (no detections), 275.5ms
Speed: 1.1ms preprocess, 275.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWGiOj1H3LORhYFn6NmVUg_180.JPG: 480x640 (no detections), 276.9ms
Speed: 1.5ms preprocess, 276.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWGiOj1H3LORhYFn6NmVUg_270.JPG: 480x640 (no detections), 274.6ms
Speed: 1.1ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWHsXgIVnHqPCQAson1vfQ_0.JPG: 480x640 (no detections), 281.8ms
Speed: 1.2ms preprocess, 281.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWHsXgIVnHqPCQAson1vfQ_90.JPG: 480x640 (no detections), 275.7ms

Speed: 1.8ms preprocess, 275.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWHsXgIVnHqPCQAson1vfQ_180.JPG: 480x640 (no detections), 268.9ms
Speed: 1.1ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWHsXgIVnHqPCQAson1vfQ_270.JPG: 480x640 (no detections), 281.2ms
Speed: 1.1ms preprocess, 281.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWMirpRMqBnPnQ1JkIs1bw_0.JPG: 480x640 (no detections), 274.2ms
Speed: 1.0ms preprocess, 274.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWMirpRMqBnPnQ1JkIs1bw_90.JPG: 480x640 (no detections), 269.5ms
Speed: 1.1ms preprocess, 269.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWMirpRMqBnPnQ1JkIs1bw_180.JPG: 480x640 (no detections), 282.6ms
Speed: 1.1ms preprocess, 282.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWMirpRMqBnPnQ1JkIs1bw_270.JPG: 480x640 (no detections), 279.6ms
Speed: 1.2ms preprocess, 279.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWNiwGLFd0ylJx7lwrBeHw_0.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWNiwGLFd0ylJx7lwrBeHw_90.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWNiwGLFd0ylJx7lwrBeHw_180.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWNiwGLFd0ylJx7lwrBeHw_270.JPG: 480x640 (no detections), 273.4ms
Speed: 1.0ms preprocess, 273.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWS7Zcs-NGU1tCkJxDt7gQ_0.JPG: 480x640 (no detections), 269.8ms
Speed: 1.0ms preprocess, 269.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWS7Zcs-NGU1tCkJxDt7gQ_90.JPG: 480x640 (no detections), 269.3ms
Speed: 1.0ms preprocess, 269.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWS7Zcs-NGU1tCkJxDt7gQ_180.JPG: 480x640 (no detections), 278.5ms
Speed: 1.0ms preprocess, 278.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWS7Zcs-NGU1tCkJxDt7gQ_270.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWVwBs99NtqRQYKGV1jJtw_0.JPG: 480x640 (no detections), 272.2ms
Speed: 1.0ms preprocess, 272.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWVwBs99NtqRQYKGV1jJtw_90.JPG: 480x640 (no detections), 270.7ms
Speed: 1.3ms preprocess, 270.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWVwBs99NtqRQYKGV1jJtw_180.JPG: 480x640 (no detections), 274.7ms
Speed: 1.1ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWVwBs99NtqRQYKGV1jJtw_270.JPG: 480x640 (no detections), 284.3ms
Speed: 1.2ms preprocess, 284.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWbU0kflriCW4CKLG6O4ow_0.JPG: 480x640 (no detections), 282.4ms
Speed: 1.1ms preprocess, 282.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWbU0kflriCW4CKLG6O4ow_90.JPG: 480x640 (no detections), 275.3ms
Speed: 1.2ms preprocess, 275.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWbU0kflriCW4CKLG6O4ow_180.JPG: 480x640 (no detections), 312.4ms
Speed: 1.0ms preprocess, 312.4ms inference, 1.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWbU0kflriCW4CKLG6O4ow_270.JPG: 480x640 (no detections), 275.7ms
Speed: 1.2ms preprocess, 275.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWc6Lv3GQbOpq6Pj55oEVg_0.JPG: 480x640 (no detections), 277.9ms
Speed: 1.2ms preprocess, 277.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWc6Lv3GQbOpq6Pj55oEVg_90.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWc6Lv3GQbOpq6Pj55oEVg_180.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWc6Lv3GQbOpq6Pj55oEVg_270.JPG: 480x640 (no detections), 275.3ms
Speed: 1.1ms preprocess, 275.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWd4Pzs8UynC97Ov8xhADQ_0.JPG: 480x640 (no detections), 273.9ms
Speed: 1.0ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWd4Pzs8UynC97Ov8xhADQ_90.JPG: 480x640 (no detections), 275.8ms
Speed: 1.3ms preprocess, 275.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWd4Pzs8UynC97Ov8xhADQ_180.JPG: 480x640 (no detections), 273.1ms
Speed: 1.1ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWd4Pzs8UynC97Ov8xhADQ_270.JPG: 480x640 (no detections), 268.2ms
Speed: 1.1ms preprocess, 268.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWh_GtgaEy9x16Jz8QZQiA_0.JPG: 480x640 (no detections), 267.8ms
Speed: 1.1ms preprocess, 267.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWh_GtgaEy9x16Jz8QZQiA_90.JPG: 480x640 (no detections), 272.6ms
Speed: 1.0ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWh_GtgaEy9x16Jz8QZQiA_180.JPG: 480x640 (no detections), 268.7ms
Speed: 1.0ms preprocess, 268.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWh_GtgaEy9x16Jz8QZQiA_270.JPG: 480x640 (no detections), 273.2ms
Speed: 1.2ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWm48ClBO2HZzwgk_g174A_0.JPG: 480x640 (no detections), 274.4ms
Speed: 1.3ms preprocess, 274.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWm48ClBO2HZzwgk_g174A_90.JPG: 480x640 (no detections), 277.3ms
Speed: 1.1ms preprocess, 277.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWm48ClBO2HZzwgk_g174A_180.JPG: 480x640 (no detections), 363.2ms
Speed: 1.1ms preprocess, 363.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWm48ClBO2HZzwgk_g174A_270.JPG: 480x640 (no detections), 298.5ms
Speed: 1.4ms preprocess, 298.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWoyTGwciP5qvpn95NVcPg_0.JPG: 480x640 (no detections), 278.1ms
Speed: 1.5ms preprocess, 278.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWoyTGwciP5qvpn95NVcPg_90.JPG: 480x640 (no detections), 270.3ms
Speed: 1.1ms preprocess, 270.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWoyTGwciP5qvpn95NVcPg_180.JPG: 480x640 (no detections), 284.5ms
Speed: 1.3ms preprocess, 284.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWoyTGwciP5qvpn95NVcPg_270.JPG: 480x640 (no detections), 311.9ms
Speed: 1.3ms preprocess, 311.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWpKMZNPUK_EVNBl6Nj9RA_0.JPG: 480x640 (no detections), 409.3ms
Speed: 1.4ms preprocess, 409.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWpKMZNPUK_EVNBl6Nj9RA_90.JPG: 480x640 (no detections), 280.1ms
Speed: 1.2ms preprocess, 280.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWpKMZNPUK_EVNBl6Nj9RA_180.JPG: 480x640 (no detections), 291.7ms
Speed: 1.1ms preprocess, 291.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWpKMZNPUK_EVNBl6Nj9RA_270.JPG: 480x640 (no detections), 278.8ms
Speed: 1.1ms preprocess, 278.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWrxHKjpCocF2diZNpZfyg_0.JPG: 480x640 (no detections), 268.8ms
Speed: 1.2ms preprocess, 268.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWrxHKjpCocF2diZNpZfyg_90.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWrxHKjpCocF2diZNpZfyg_180.JPG: 480x640 (no detections), 298.3ms
Speed: 1.1ms preprocess, 298.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWrxHKjpCocF2diZNpZfyg_270.JPG: 480x640 (no detections), 321.3ms
Speed: 1.3ms preprocess, 321.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWsqDKgNohnHv-QoRZ0Yyw_0.JPG: 480x640 (no detections), 293.9ms
Speed: 1.3ms preprocess, 293.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWsqDKgNohnHv-QoRZ0Yyw_90.JPG: 480x640 (no detections), 270.3ms
Speed: 1.1ms preprocess, 270.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWsqDKgNohnHv-QoRZ0Yyw_180.JPG: 480x640 (no detections), 270.5ms
Speed: 1.2ms preprocess, 270.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zWsqDKgNohnHv-QoRZ0Yyw_270.JPG: 480x640 (no detections), 297.3ms
Speed: 1.1ms preprocess, 297.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zX0DlWu8tF-GsV1xytyEaQ_0.JPG: 480x640 (no detections), 294.6ms
Speed: 1.2ms preprocess, 294.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zX0DlWu8tF-GsV1xytyEaQ_90.JPG: 480x640 (no detections), 270.8ms
Speed: 1.2ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zX0DlWu8tF-GsV1xytyEaQ_180.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zX0DlWu8tF-GsV1xytyEaQ_270.JPG: 480x640 (no detections), 281.8ms
Speed: 1.0ms preprocess, 281.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zX0EPw3k2Udvyle0Uj3kdA_0.JPG: 480x640 (no detections), 283.5ms
Speed: 1.2ms preprocess, 283.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zX0EPw3k2Udvyle0Uj3kdA_90.JPG: 480x640 (no detections), 281.3ms
Speed: 1.1ms preprocess, 281.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zX0EPw3k2Udvyle0Uj3kdA_180.JPG: 480x640 (no detections), 278.7ms
Speed: 1.1ms preprocess, 278.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zX0EPw3k2Udvyle0Uj3kdA_270.JPG: 480x640 (no detections), 320.0ms
Speed: 1.0ms preprocess, 320.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zX6F-27I3TmSPQ87ZvqryQ_0.JPG: 480x640 1 Waste, 279.5ms
Speed: 1.1ms preprocess, 279.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zX6F-27I3TmSPQ87ZvqryQ_90.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zX6F-27I3TmSPQ87ZvqryQ_180.JPG: 480x640 (no detections), 312.6ms
Speed: 1.1ms preprocess, 312.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zX6F-27I3TmSPQ87ZvqryQ_270.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zX9eK82NHAP0HuoqgpVVow_0.JPG: 480x640 1 Waste, 263.7ms

Speed: 1.0ms preprocess, 263.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zX9eK82NHAP0HuoqgpVVow_90.JPG: 480x640 1 Waste, 286.1ms
Speed: 1.0ms preprocess, 286.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zX9eK82NHAP0HuoqgpVVow_180.JPG: 480x640 (no detections), 274.6ms
Speed: 1.1ms preprocess, 274.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zX9eK82NHAP0HuoqgpVVow_270.JPG: 480x640 (no detections), 271.6ms
Speed: 1.0ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXD5Pv04MFysOrpJ8envEw_0.JPG: 480x640 (no detections), 272.5ms
Speed: 1.1ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXD5Pv04MFysOrpJ8envEw_90.JPG: 480x640 (no detections), 268.5ms
Speed: 1.1ms preprocess, 268.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXD5Pv04MFysOrpJ8envEw_180.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXD5Pv04MFysOrpJ8envEw_270.JPG: 480x640 (no detections), 263.0ms
Speed: 1.1ms preprocess, 263.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXI12y8tez6Op8p8AEVS2Q_0.JPG: 480x640 (no detections), 272.9ms
Speed: 1.0ms preprocess, 272.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXI12y8tez6Op8p8AEVS2Q_90.JPG: 480x640 (no detections), 267.1ms
Speed: 1.0ms preprocess, 267.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXI12y8tez6Op8p8AEVS2Q_180.JPG: 480x640 (no detections), 289.9ms
Speed: 1.1ms preprocess, 289.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXI12y8tez6Op8p8AEVS2Q_270.JPG: 480x640 (no detections), 277.3ms
Speed: 1.1ms preprocess, 277.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXIN9F-GeuATSDYwREoQdg_0.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXIN9F-GeuATSDYwREoQdg_90.JPG: 480x640 (no detections), 292.4ms
Speed: 1.0ms preprocess, 292.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXIN9F-GeuATSDYwREoQdg_180.JPG: 480x640 (no detections), 274.0ms
Speed: 1.1ms preprocess, 274.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXIN9F-GeuATSDYwREoQdg_270.JPG: 480x640 (no detections), 275.8ms
Speed: 1.2ms preprocess, 275.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXKXyW3nUjM0XxsE4oH26g_0.JPG: 480x640 (no detections), 274.2ms
Speed: 1.2ms preprocess, 274.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXKXyW3nUjM0XxsE4oH26g_90.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXKXyW3nUjM0XxsE4oH26g_180.JPG: 480x640 (no detections), 268.4ms
Speed: 1.9ms preprocess, 268.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXKXyW3nUjM0XxsE4oH26g_270.JPG: 480x640 (no detections), 270.8ms
Speed: 1.2ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXKyt8kdsnzhIMbGhqgvcg_0.JPG: 480x640 (no detections), 268.3ms
Speed: 1.1ms preprocess, 268.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXKyt8kdsnzhIMbGhqgvcg_90.JPG: 480x640 (no detections), 271.9ms
Speed: 1.0ms preprocess, 271.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXKyt8kdsnzhIMbGhqgvcg_180.JPG: 480x640 (no detections), 273.5ms
Speed: 1.0ms preprocess, 273.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXKyt8kdsnzhIMbGhqgvcg_270.JPG: 480x640 (no detections), 286.5ms
Speed: 1.1ms preprocess, 286.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXOw6HsTyCJA1KJFcGPp2A_0.JPG: 480x640 (no detections), 283.2ms
Speed: 1.1ms preprocess, 283.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXOw6HsTyCJA1KJFcGPp2A_90.JPG: 480x640 (no detections), 276.3ms
Speed: 1.2ms preprocess, 276.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXOw6HsTyCJA1KJFcGPp2A_180.JPG: 480x640 1 Waste, 270.9ms
Speed: 1.1ms preprocess, 270.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXOw6HsTyCJA1KJFcGPp2A_270.JPG: 480x640 (no detections), 290.6ms
Speed: 1.0ms preprocess, 290.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXU2OZim7CK5kx58IRkpMA_0.JPG: 480x640 (no detections), 276.3ms
Speed: 1.0ms preprocess, 276.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXU2OZim7CK5kx58IRkpMA_90.JPG: 480x640 (no detections), 268.3ms
Speed: 1.1ms preprocess, 268.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXU2OZim7CK5kx58IRkpMA_180.JPG: 480x640 (no detections), 270.4ms
Speed: 1.1ms preprocess, 270.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXU2OZim7CK5kx58IRkpMA_270.JPG: 480x640 (no detections), 274.4ms
Speed: 1.2ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXVkxF3dCpUSr6AFpS_i_g_0.JPG: 480x640 (no detections), 269.3ms
Speed: 1.1ms preprocess, 269.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXVkxF3dCpUSr6AFpS_i_g_90.JPG: 480x640 (no detections), 268.4ms
Speed: 1.1ms preprocess, 268.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXVkxF3dCpUSr6AFpS_i_g_180.JPG: 480x640 (no detections), 272.5ms
Speed: 1.0ms preprocess, 272.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXVkxF3dCpUSr6AFpS_i_g_270.JPG: 480x640 (no detections), 269.2ms
Speed: 1.1ms preprocess, 269.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXZig8S3mTmPD7_tCMaHvA_0.JPG: 480x640 (no detections), 274.8ms
Speed: 1.0ms preprocess, 274.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXZig8S3mTmPD7_tCMaHvA_90.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXZig8S3mTmPD7_tCMaHvA_180.JPG: 480x640 (no detections), 273.9ms
Speed: 1.1ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXZig8S3mTmPD7_tCMaHvA_270.JPG: 480x640 (no detections), 268.4ms
Speed: 1.0ms preprocess, 268.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXb4Vfi9NJXKimDWER6v7g_0.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXb4Vfi9NJXKimDWER6v7g_90.JPG: 480x640 (no detections), 267.8ms
Speed: 1.0ms preprocess, 267.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXb4Vfi9NJXKimDWER6v7g_180.JPG: 480x640 (no detections), 289.8ms
Speed: 1.0ms preprocess, 289.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXb4Vfi9NJXKimDWER6v7g_270.JPG: 480x640 (no detections), 274.2ms
Speed: 1.2ms preprocess, 274.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXc1AfZVycL1X8TlvYzLiw_0.JPG: 480x640 1 Waste, 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXc1AfZVycL1X8TlvYzLiw_90.JPG: 480x640 1 Waste, 274.9ms
Speed: 1.1ms preprocess, 274.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXc1AfZVycL1X8TlvYzLiw_180.JPG: 480x640 (no detections), 281.2ms
Speed: 1.0ms preprocess, 281.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXc1AfZVycL1X8TlvYzLiw_270.JPG: 480x640 (no detections), 273.9ms
Speed: 1.1ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXcKu4DVCznTjvxTiRP74g_0.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXcKu4DVCznTjvxTiRP74g_90.JPG: 480x640 1 Waste, 269.4ms
Speed: 1.1ms preprocess, 269.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXcKu4DVCznTjvxTiRP74g_180.JPG: 480x640 1 Waste, 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXcKu4DVCznTjvxTiRP74g_270.JPG: 480x640 1 Waste, 268.6ms
Speed: 1.1ms preprocess, 268.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXcXrMcmJxFrmF-uV11TnA_0.JPG: 480x640 (no detections), 271.3ms
Speed: 1.0ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXcXrMcmJxFrmF-uV11TnA_90.JPG: 480x640 (no detections), 266.7ms
Speed: 1.0ms preprocess, 266.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXcXrMcmJxFrmF-uV11TnA_180.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXcXrMcmJxFrmF-uV11TnA_270.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXd8-jt-Wb79aD-7I_XSag_0.JPG: 480x640 (no detections), 292.1ms
Speed: 1.2ms preprocess, 292.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXd8-jt-Wb79aD-7I_XSag_90.JPG: 480x640 (no detections), 278.1ms
Speed: 1.2ms preprocess, 278.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXd8-jt-Wb79aD-7I_XSag_180.JPG: 480x640 (no detections), 274.7ms
Speed: 1.1ms preprocess, 274.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXd8-jt-Wb79aD-7I_XSag_270.JPG: 480x640 (no detections), 274.0ms
Speed: 1.0ms preprocess, 274.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXdv_sfVmp_SX14tKzS4Vw_0.JPG: 480x640 (no detections), 274.9ms
Speed: 1.1ms preprocess, 274.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXdv_sfVmp_SX14tKzS4Vw_90.JPG: 480x640 (no detections), 269.9ms
Speed: 1.0ms preprocess, 269.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXdv_sfVmp_SX14tKzS4Vw_180.JPG: 480x640 (no detections), 273.5ms
Speed: 1.0ms preprocess, 273.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXdv_sfVmp_SX14tKzS4Vw_270.JPG: 480x640 (no detections), 275.0ms
Speed: 1.1ms preprocess, 275.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXeJmrvYjSHBLw2xfuhgfQ_0.JPG: 480x640 (no detections), 268.9ms
Speed: 1.0ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXeJmrvYjSHBLw2xfuhgfQ_90.JPG: 480x640 (no detections), 276.9ms
Speed: 1.1ms preprocess, 276.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXeJmrvYjSHBLw2xfuhgfQ_180.JPG: 480x640 (no detections), 273.7ms
Speed: 1.2ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXeJmrvYjSHBLw2xfuhgfQ_270.JPG: 480x640 (no detections), 271.8ms

Speed: 1.1ms preprocess, 271.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXfFOdrid-ai0HG5QbkaSw_0.JPG: 480x640 (no detections), 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXfFOdrid-ai0HG5QbkaSw_90.JPG: 480x640 (no detections), 277.4ms
Speed: 1.1ms preprocess, 277.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXfFOdrid-ai0HG5QbkaSw_180.JPG: 480x640 (no detections), 275.8ms
Speed: 1.4ms preprocess, 275.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXfFOdrid-ai0HG5QbkaSw_270.JPG: 480x640 (no detections), 280.3ms
Speed: 1.1ms preprocess, 280.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXm2Zq7OoIk_6zSm6ASA9w_0.JPG: 480x640 (no detections), 280.1ms
Speed: 1.1ms preprocess, 280.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXm2Zq7OoIk_6zSm6ASA9w_90.JPG: 480x640 (no detections), 278.6ms
Speed: 1.1ms preprocess, 278.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXm2Zq7OoIk_6zSm6ASA9w_180.JPG: 480x640 (no detections), 298.1ms
Speed: 1.3ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXm2Zq7OoIk_6zSm6ASA9w_270.JPG: 480x640 (no detections), 271.0ms
Speed: 1.1ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXnTjJ4Oi7y4aCqXmyZbvw_0.JPG: 480x640 (no detections), 267.3ms
Speed: 1.1ms preprocess, 267.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXnTjJ4Oi7y4aCqXmyZbvw_90.JPG: 480x640 (no detections), 278.3ms
Speed: 1.0ms preprocess, 278.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXnTjJ4Oi7y4aCqXmyZbvw_180.JPG: 480x640 1 Waste, 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXnTjJ4Oi7y4aCqXmyZbvw_270.JPG: 480x640 (no detections), 280.0ms
Speed: 1.1ms preprocess, 280.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXok67LV4OkvoHyO5vmSpQ_0.JPG: 480x640 (no detections), 273.5ms
Speed: 1.2ms preprocess, 273.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXok67LV4OkvoHyO5vmSpQ_90.JPG: 480x640 (no detections), 270.1ms
Speed: 1.2ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXok67LV4OkvoHyO5vmSpQ_180.JPG: 480x640 (no detections), 299.0ms
Speed: 1.1ms preprocess, 299.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXok67LV4OkvoHyO5vmSpQ_270.JPG: 480x640 (no detections), 278.4ms
Speed: 1.1ms preprocess, 278.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXstsxeeuwgJCbucJ-jxLQ_0.JPG: 480x640 (no detections), 279.1ms
Speed: 1.1ms preprocess, 279.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXstsxeeuwgJCbucJ-jxLQ_90.JPG: 480x640 (no detections), 271.1ms
Speed: 1.2ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXstsxeeuwgJCbucJ-jxLQ_180.JPG: 480x640 (no detections), 280.3ms
Speed: 1.1ms preprocess, 280.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXstsxeeuwgJCbucJ-jxLQ_270.JPG: 480x640 (no detections), 273.6ms
Speed: 1.0ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXuEA8l8rs-83TMBN3-Y9A_0.JPG: 480x640 (no detections), 273.7ms
Speed: 1.0ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXuEA8l8rs-83TMBN3-Y9A_90.JPG: 480x640 (no detections), 277.9ms
Speed: 1.0ms preprocess, 277.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXuEA8l8rs-83TMBN3-Y9A_180.JPG: 480x640 1 Waste, 279.5ms
Speed: 1.2ms preprocess, 279.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXuEA8l8rs-83TMBN3-Y9A_270.JPG: 480x640 (no detections), 273.5ms
Speed: 1.0ms preprocess, 273.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXywUbEYpf8gaQRxA2nt7A_0.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXywUbEYpf8gaQRxA2nt7A_90.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXywUbEYpf8gaQRxA2nt7A_180.JPG: 480x640 (no detections), 272.8ms
Speed: 1.0ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zXywUbEYpf8gaQRxA2nt7A_270.JPG: 480x640 (no detections), 279.6ms
Speed: 1.1ms preprocess, 279.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zY--i70cnKIAacrrypiXjg_0.JPG: 480x640 (no detections), 278.2ms
Speed: 1.1ms preprocess, 278.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zY--i70cnKIAacrrypiXjg_90.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zY--i70cnKIAacrrypiXjg_180.JPG: 480x640 (no detections), 283.6ms
Speed: 1.1ms preprocess, 283.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zY--i70cnKIAacrrypiXjg_270.JPG: 480x640 (no detections), 276.8ms
Speed: 1.1ms preprocess, 276.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zY4H8tXAAqC2WJG46k0TPw_0.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zY4H8tXAAqC2WJG46k0TPw_90.JPG: 480x640 (no detections), 281.5ms
Speed: 1.0ms preprocess, 281.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zY4H8tXAAqC2WJG46k0TPw_180.JPG: 480x640 (no detections), 275.0ms
Speed: 1.0ms preprocess, 275.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zY4H8tXAAqC2WJG46k0TPw_270.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zY6LZXt8EQvYA9NktauDLA_0.JPG: 480x640 (no detections), 273.8ms
Speed: 1.0ms preprocess, 273.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zY6LZXt8EQvYA9NktauDLA_90.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zY6LZXt8EQvYA9NktauDLA_180.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zY6LZXt8EQvYA9NktauDLA_270.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zY6ZKM8a4XHJiwZP8IuhRg_0.JPG: 480x640 (no detections), 275.6ms
Speed: 1.1ms preprocess, 275.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zY6ZKM8a4XHJiwZP8IuhRg_90.JPG: 480x640 (no detections), 270.1ms
Speed: 1.2ms preprocess, 270.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zY6ZKM8a4XHJiwZP8IuhRg_180.JPG: 480x640 (no detections), 272.5ms
Speed: 1.1ms preprocess, 272.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zY6ZKM8a4XHJiwZP8IuhRg_270.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zY9LbY3zW4Xmc_JcDaK08g_0.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zY9LbY3zW4Xmc_JcDaK08g_90.JPG: 480x640 1 Waste, 285.5ms
Speed: 1.1ms preprocess, 285.5ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zY9LbY3zW4Xmc_JcDaK08g_180.JPG: 480x640 (no detections), 287.8ms
Speed: 3.3ms preprocess, 287.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zY9LbY3zW4Xmc_JcDaK08g_270.JPG: 480x640 1 Waste, 273.6ms
Speed: 1.1ms preprocess, 273.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYBUjFUQhWkfriwkKWxq0Q_0.JPG: 480x640 1 Waste, 272.2ms
Speed: 1.3ms preprocess, 272.2ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYBUjFUQhWkfriwkKWxq0Q_90.JPG: 480x640 (no detections), 273.2ms
Speed: 1.1ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYBUjFUQhWkfriwkKWxq0Q_180.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYBUjFUQhWkfriwkKWxq0Q_270.JPG: 480x640 (no detections), 276.8ms
Speed: 1.1ms preprocess, 276.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYCXqF4V283W7cTCoRgheQ_0.JPG: 480x640 1 Waste, 276.9ms
Speed: 1.1ms preprocess, 276.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYCXqF4V283W7cTCoRgheQ_90.JPG: 480x640 (no detections), 280.4ms
Speed: 1.1ms preprocess, 280.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYCXqF4V283W7cTCoRgheQ_180.JPG: 480x640 (no detections), 272.1ms
Speed: 1.2ms preprocess, 272.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYCXqF4V283W7cTCoRgheQ_270.JPG: 480x640 (no detections), 269.3ms
Speed: 1.1ms preprocess, 269.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYCw4T42OCrGgDBnJLAHTA_0.JPG: 480x640 (no detections), 271.6ms
Speed: 1.4ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYCw4T42OCrGgDBnJLAHTA_90.JPG: 480x640 (no detections), 268.5ms
Speed: 1.0ms preprocess, 268.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYCw4T42OCrGgDBnJLAHTA_180.JPG: 480x640 (no detections), 267.0ms
Speed: 1.1ms preprocess, 267.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYCw4T42OCrGgDBnJLAHTA_270.JPG: 480x640 (no detections), 272.0ms
Speed: 1.1ms preprocess, 272.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYD6Jx8NVJyd13QJcqYjlg_0.JPG: 480x640 (no detections), 267.7ms
Speed: 1.0ms preprocess, 267.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYD6Jx8NVJyd13QJcqYjlg_90.JPG: 480x640 (no detections), 270.8ms
Speed: 1.0ms preprocess, 270.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYD6Jx8NVJyd13QJcqYjlg_180.JPG: 480x640 (no detections), 266.7ms
Speed: 1.1ms preprocess, 266.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYD6Jx8NVJyd13QJcqYjlg_270.JPG: 480x640 (no detections), 271.7ms
Speed: 1.0ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYEfx7uGI3THq1JFVvh-mw_0.JPG: 480x640 (no detections), 270.7ms
Speed: 1.0ms preprocess, 270.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYEfx7uGI3THq1JFVvh-mw_90.JPG: 480x640 (no detections), 269.1ms
Speed: 1.0ms preprocess, 269.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYEfx7uGI3THq1JFVvh-mw_180.JPG: 480x640 (no detections), 270.8ms

Speed: 1.0ms preprocess, 270.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYEfx7uGI3THq1JFVvh-mw_270.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYGuBuATsNZ5ojOU0KCWdQ_0.JPG: 480x640 (no detections), 267.2ms
Speed: 1.0ms preprocess, 267.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYGuBuATsNZ5ojOU0KCWdQ_90.JPG: 480x640 (no detections), 271.5ms
Speed: 1.1ms preprocess, 271.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYGuBuATsNZ5ojOU0KCWdQ_180.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYGuBuATsNZ5ojOU0KCWdQ_270.JPG: 480x640 (no detections), 272.4ms
Speed: 1.0ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYHZr8Lv1fphjJ-TyQYM9Q_0.JPG: 480x640 (no detections), 269.3ms
Speed: 1.1ms preprocess, 269.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYHZr8Lv1fphjJ-TyQYM9Q_90.JPG: 480x640 (no detections), 269.5ms
Speed: 1.0ms preprocess, 269.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYHZr8Lv1fphjJ-TyQYM9Q_180.JPG: 480x640 (no detections), 274.3ms
Speed: 1.0ms preprocess, 274.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYHZr8Lv1fphjJ-TyQYM9Q_270.JPG: 480x640 (no detections), 269.9ms
Speed: 1.0ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYICN2hz_Yg0eOLHoWZEzQ_0.JPG: 480x640 (no detections), 272.1ms
Speed: 1.2ms preprocess, 272.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYICN2hz_Yg0eOLHoWZEzQ_90.JPG: 480x640 (no detections), 305.4ms
Speed: 1.2ms preprocess, 305.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYICN2hz_Yg0eOLHoWZEzQ_180.JPG: 480x640 (no detections), 279.1ms
Speed: 1.2ms preprocess, 279.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYICN2hz_Yg0eOLHoWZEzQ_270.JPG: 480x640 (no detections), 287.3ms
Speed: 1.7ms preprocess, 287.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYJiUtYDUMjql7w4K6xyew_0.JPG: 480x640 (no detections), 284.0ms
Speed: 1.4ms preprocess, 284.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYJiUtYDUMjql7w4K6xyew_90.JPG: 480x640 (no detections), 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYJiUtYDUMjql7w4K6xyew_180.JPG: 480x640 (no detections), 274.3ms
Speed: 1.1ms preprocess, 274.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYJiUtYDUMjql7w4K6xyew_270.JPG: 480x640 (no detections), 274.7ms
Speed: 1.2ms preprocess, 274.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYJuwYixIt114ODcirP9gA_0.JPG: 480x640 (no detections), 271.8ms
Speed: 1.2ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYJuwYixIt114ODcirP9gA_90.JPG: 480x640 (no detections), 277.5ms
Speed: 1.2ms preprocess, 277.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYJuwYixIt114ODcirP9gA_180.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYJuwYixIt114ODcirP9gA_270.JPG: 480x640 (no detections), 267.9ms
Speed: 1.0ms preprocess, 267.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYMsPsWRiASoEoP-8VRBfQ_0.JPG: 480x640 1 Waste, 270.2ms
Speed: 1.0ms preprocess, 270.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYMsPsWRiASoEoP-8VRBfQ_90.JPG: 480x640 (no detections), 277.3ms
Speed: 1.1ms preprocess, 277.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYMsPsWRiASoEoP-8VRBfQ_180.JPG: 480x640 (no detections), 280.0ms
Speed: 1.1ms preprocess, 280.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYMsPsWRiASoEoP-8VRBfQ_270.JPG: 480x640 (no detections), 276.1ms
Speed: 1.5ms preprocess, 276.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYMyaMpuyi-tMtmaLeo1NQ_0.JPG: 480x640 (no detections), 275.7ms
Speed: 1.2ms preprocess, 275.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYMyaMpuyi-tMtmaLeo1NQ_90.JPG: 480x640 (no detections), 271.5ms
Speed: 1.0ms preprocess, 271.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYMyaMpuyi-tMtmaLeo1NQ_180.JPG: 480x640 (no detections), 275.4ms
Speed: 1.1ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYMyaMpuyi-tMtmaLeo1NQ_270.JPG: 480x640 (no detections), 271.5ms
Speed: 1.1ms preprocess, 271.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYNhE7bkjo5zs-2s3J9kDg_0.JPG: 480x640 (no detections), 306.5ms
Speed: 1.2ms preprocess, 306.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYNhE7bkjo5zs-2s3J9kDg_90.JPG: 480x640 (no detections), 273.7ms
Speed: 1.2ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYNhE7bkjo5zs-2s3J9kDg_180.JPG: 480x640 (no detections), 270.8ms
Speed: 1.2ms preprocess, 270.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYNhE7bkjo5zs-2s3J9kDg_270.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYNvxyia3XETpTre98mkaA_0.JPG: 480x640 (no detections), 273.2ms
Speed: 1.0ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYNvxyia3XETpTre98mkaA_90.JPG: 480x640 (no detections), 266.4ms
Speed: 1.1ms preprocess, 266.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYNvxyia3XETpTre98mkaA_180.JPG: 480x640 (no detections), 269.3ms
Speed: 1.1ms preprocess, 269.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYNvxyia3XETpTre98mkaA_270.JPG: 480x640 (no detections), 272.8ms
Speed: 1.2ms preprocess, 272.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYPdp-judU7XHfGEFCuxBw_0.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYPdp-judU7XHfGEFCuxBw_90.JPG: 480x640 (no detections), 288.9ms
Speed: 1.2ms preprocess, 288.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYPdp-judU7XHfGEFCuxBw_180.JPG: 480x640 (no detections), 280.1ms
Speed: 1.2ms preprocess, 280.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYPdp-judU7XHfGEFCuxBw_270.JPG: 480x640 (no detections), 280.1ms
Speed: 1.2ms preprocess, 280.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYPzczpTZordmKWIPu77nw_0.JPG: 480x640 (no detections), 275.0ms
Speed: 1.1ms preprocess, 275.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYPzczpTZordmKWIPu77nw_90.JPG: 480x640 (no detections), 277.9ms
Speed: 1.3ms preprocess, 277.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYPzczpTZordmKWIPu77nw_180.JPG: 480x640 (no detections), 272.3ms
Speed: 1.1ms preprocess, 272.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYPzczpTZordmKWIPu77nw_270.JPG: 480x640 (no detections), 283.1ms
Speed: 1.0ms preprocess, 283.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYRZLr2DbeGfVwXlwdaEoQ_0.JPG: 480x640 (no detections), 282.6ms
Speed: 1.1ms preprocess, 282.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYRZLr2DbeGfVwXlwdaEoQ_90.JPG: 480x640 1 Waste, 275.7ms
Speed: 1.0ms preprocess, 275.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYRZLr2DbeGfVwXlwdaEoQ_180.JPG: 480x640 (no detections), 276.5ms
Speed: 1.1ms preprocess, 276.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYRZLr2DbeGfVwXlwdaEoQ_270.JPG: 480x640 (no detections), 309.1ms
Speed: 1.0ms preprocess, 309.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYWFhXgzH5l8i_JByAKYhg_0.JPG: 480x640 (no detections), 279.3ms
Speed: 1.1ms preprocess, 279.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYWFhXgzH5l8i_JByAKYhg_90.JPG: 480x640 (no detections), 268.9ms
Speed: 1.0ms preprocess, 268.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYWFhXgzH5l8i_JByAKYhg_180.JPG: 480x640 1 Waste, 271.5ms
Speed: 1.0ms preprocess, 271.5ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYWFhXgzH5l8i_JByAKYhg_270.JPG: 480x640 (no detections), 275.9ms
Speed: 1.2ms preprocess, 275.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYWnEEqECu8_ljzF-F2nMQ_0.JPG: 480x640 (no detections), 280.1ms
Speed: 1.2ms preprocess, 280.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYWnEEqECu8_ljzF-F2nMQ_90.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYWnEEqECu8_ljzF-F2nMQ_180.JPG: 480x640 (no detections), 275.0ms
Speed: 1.0ms preprocess, 275.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYWnEEqECu8_ljzF-F2nMQ_270.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYX21iZw1Qk9wJSGRveXqQ_0.JPG: 480x640 (no detections), 273.1ms
Speed: 1.0ms preprocess, 273.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYX21iZw1Qk9wJSGRveXqQ_90.JPG: 480x640 (no detections), 269.2ms
Speed: 1.0ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYX21iZw1Qk9wJSGRveXqQ_180.JPG: 480x640 (no detections), 272.1ms
Speed: 1.1ms preprocess, 272.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYX21iZw1Qk9wJSGRveXqQ_270.JPG: 480x640 (no detections), 272.3ms
Speed: 1.2ms preprocess, 272.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYXwdx5No1rItvZLX2JXLg_0.JPG: 480x640 (no detections), 273.1ms
Speed: 1.1ms preprocess, 273.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYXwdx5No1rItvZLX2JXLg_90.JPG: 480x640 (no detections), 274.8ms
Speed: 1.0ms preprocess, 274.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYXwdx5No1rItvZLX2JXLg_180.JPG: 480x640 (no detections), 272.5ms
Speed: 1.1ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYXwdx5No1rItvZLX2JXLg_270.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYalMa1zDyiV-vcJPbVMhw_0.JPG: 480x640 (no detections), 270.2ms
Speed: 1.0ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYalMa1zDyiV-vcJPbVMhw_90.JPG: 480x640 (no detections), 276.2ms

Speed: 1.2ms preprocess, 276.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYalMa1zDyiV-vcJPbVMhw_180.JPG: 480x640 (no detections), 274.0ms
Speed: 1.1ms preprocess, 274.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYalMa1zDyiV-vcJPbVMhw_270.JPG: 480x640 (no detections), 275.3ms
Speed: 1.2ms preprocess, 275.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYeL-lhxQbrwg0Q5es7ujw_0.JPG: 480x640 (no detections), 276.3ms
Speed: 1.1ms preprocess, 276.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYeL-lhxQbrwg0Q5es7ujw_90.JPG: 480x640 (no detections), 269.1ms
Speed: 1.1ms preprocess, 269.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYeL-lhxQbrwg0Q5es7ujw_180.JPG: 480x640 (no detections), 293.0ms
Speed: 1.0ms preprocess, 293.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYeL-lhxQbrwg0Q5es7ujw_270.JPG: 480x640 (no detections), 280.1ms
Speed: 1.1ms preprocess, 280.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYeTjRtfg6sWAkV5Xzx3jw_0.JPG: 480x640 (no detections), 286.7ms
Speed: 1.1ms preprocess, 286.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYeTjRtfg6sWAkV5Xzx3jw_90.JPG: 480x640 (no detections), 274.6ms
Speed: 1.2ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYeTjRtfg6sWAkV5Xzx3jw_180.JPG: 480x640 (no detections), 269.4ms
Speed: 1.1ms preprocess, 269.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYeTjRtfg6sWAkV5Xzx3jw_270.JPG: 480x640 (no detections), 277.4ms
Speed: 1.2ms preprocess, 277.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYgvu8h6vVKOkfSvmUR9Eg_0.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYgvu8h6vVKOkfSvmUR9Eg_90.JPG: 480x640 1 Waste, 275.9ms
Speed: 1.0ms preprocess, 275.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYgvu8h6vVKOkfSvmUR9Eg_180.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYgvu8h6vVKOkfSvmUR9Eg_270.JPG: 480x640 (no detections), 270.9ms
Speed: 1.1ms preprocess, 270.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYiZEJ68QiouqgcGh41_4Q_0.JPG: 480x640 (no detections), 283.2ms
Speed: 1.1ms preprocess, 283.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYiZEJ68QiouqgcGh41_4Q_90.JPG: 480x640 (no detections), 277.2ms
Speed: 1.5ms preprocess, 277.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYiZEJ68QiouqgcGh41_4Q_180.JPG: 480x640 (no detections), 273.0ms
Speed: 1.2ms preprocess, 273.0ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYiZEJ68QiouqgcGh41_4Q_270.JPG: 480x640 (no detections), 269.0ms
Speed: 1.1ms preprocess, 269.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYkC39hrxzXaZaGzHklfxQ_0.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYkC39hrxzXaZaGzHklfxQ_90.JPG: 480x640 1 Waste, 272.6ms
Speed: 1.0ms preprocess, 272.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYkC39hrxzXaZaGzHklfxQ_180.JPG: 480x640 (no detections), 275.4ms
Speed: 1.0ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYkC39hrxzXaZaGzHklfxQ_270.JPG: 480x640 (no detections), 270.9ms
Speed: 1.3ms preprocess, 270.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYke1itDTf4vXQ7bmNV7sQ_0.JPG: 480x640 (no detections), 269.1ms
Speed: 1.0ms preprocess, 269.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYke1itDTf4vXQ7bmNV7sQ_90.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYke1itDTf4vXQ7bmNV7sQ_180.JPG: 480x640 1 Waste, 272.0ms
Speed: 1.0ms preprocess, 272.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYke1itDTf4vXQ7bmNV7sQ_270.JPG: 480x640 (no detections), 270.8ms
Speed: 1.2ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYuOPOGaShtvsJXFHSVfOg_0.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYuOPOGaShtvsJXFHSVfOg_90.JPG: 480x640 (no detections), 269.6ms
Speed: 1.1ms preprocess, 269.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYuOPOGaShtvsJXFHSVfOg_180.JPG: 480x640 (no detections), 271.7ms
Speed: 1.2ms preprocess, 271.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYuOPOGaShtvsJXFHSVfOg_270.JPG: 480x640 (no detections), 268.7ms
Speed: 1.1ms preprocess, 268.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYzNcyp7C1WVy0Tlee4eTw_0.JPG: 480x640 (no detections), 276.9ms
Speed: 1.3ms preprocess, 276.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYzNcyp7C1WVy0Tlee4eTw_90.JPG: 480x640 (no detections), 283.2ms
Speed: 1.2ms preprocess, 283.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYzNcyp7C1WVy0Tlee4eTw_180.JPG: 480x640 (no detections), 282.3ms
Speed: 2.0ms preprocess, 282.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zYzNcyp7C1WVy0Tlee4eTw_270.JPG: 480x640 (no detections), 267.6ms
Speed: 1.0ms preprocess, 267.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZ-aAGf4LCD1p_3htS3jEA_0.JPG: 480x640 (no detections), 276.8ms
Speed: 1.1ms preprocess, 276.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZ-aAGf4LCD1p_3htS3jEA_90.JPG: 480x640 (no detections), 272.4ms
Speed: 1.3ms preprocess, 272.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZ-aAGf4LCD1p_3htS3jEA_180.JPG: 480x640 (no detections), 276.9ms
Speed: 1.1ms preprocess, 276.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZ-aAGf4LCD1p_3htS3jEA_270.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZ4P6VY63UCV_rZx2hK7VA_0.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZ4P6VY63UCV_rZx2hK7VA_90.JPG: 480x640 (no detections), 272.0ms
Speed: 1.0ms preprocess, 272.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZ4P6VY63UCV_rZx2hK7VA_180.JPG: 480x640 (no detections), 272.6ms
Speed: 1.2ms preprocess, 272.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZ4P6VY63UCV_rZx2hK7VA_270.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZ8M38GAnUsknjn5jYlh-g_0.JPG: 480x640 (no detections), 267.9ms
Speed: 1.1ms preprocess, 267.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZ8M38GAnUsknjn5jYlh-g_90.JPG: 480x640 (no detections), 271.4ms
Speed: 1.2ms preprocess, 271.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZ8M38GAnUsknjn5jYlh-g_180.JPG: 480x640 (no detections), 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZ8M38GAnUsknjn5jYlh-g_270.JPG: 480x640 (no detections), 270.1ms
Speed: 1.0ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZCei229kf5xlI42wjKEmg_0.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZCei229kf5xlI42wjKEmg_90.JPG: 480x640 (no detections), 287.5ms
Speed: 1.2ms preprocess, 287.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZCei229kf5xlI42wjKEmg_180.JPG: 480x640 (no detections), 303.5ms
Speed: 1.3ms preprocess, 303.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZCei229kf5xlI42wjKEmg_270.JPG: 480x640 (no detections), 322.3ms
Speed: 1.3ms preprocess, 322.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZFGaqs4dH8Nw_YV30BN2w_0.JPG: 480x640 (no detections), 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZFGaqs4dH8Nw_YV30BN2w_90.JPG: 480x640 (no detections), 276.5ms
Speed: 1.1ms preprocess, 276.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZFGaqs4dH8Nw_YV30BN2w_180.JPG: 480x640 (no detections), 269.0ms
Speed: 1.1ms preprocess, 269.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZFGaqs4dH8Nw_YV30BN2w_270.JPG: 480x640 (no detections), 279.0ms
Speed: 1.2ms preprocess, 279.0ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZJ4epqtUlOPxpjkxfOUfw_0.JPG: 480x640 (no detections), 284.0ms
Speed: 1.4ms preprocess, 284.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZJ4epqtUlOPxpjkxfOUfw_90.JPG: 480x640 (no detections), 270.6ms
Speed: 1.2ms preprocess, 270.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZJ4epqtUlOPxpjkxfOUfw_180.JPG: 480x640 (no detections), 283.1ms
Speed: 1.1ms preprocess, 283.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZJ4epqtUlOPxpjkxfOUfw_270.JPG: 480x640 (no detections), 284.8ms
Speed: 1.0ms preprocess, 284.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZJZxUkmDZRf-Zy4fI6nbQ_0.JPG: 480x640 (no detections), 291.3ms
Speed: 1.1ms preprocess, 291.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZJZxUkmDZRf-Zy4fI6nbQ_90.JPG: 480x640 (no detections), 297.8ms
Speed: 1.3ms preprocess, 297.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZJZxUkmDZRf-Zy4fI6nbQ_180.JPG: 480x640 (no detections), 281.8ms
Speed: 1.1ms preprocess, 281.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZJZxUkmDZRf-Zy4fI6nbQ_270.JPG: 480x640 (no detections), 278.5ms
Speed: 1.1ms preprocess, 278.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZKEy81a3e0h6rLrMad1fA_0.JPG: 480x640 (no detections), 270.3ms
Speed: 1.0ms preprocess, 270.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZKEy81a3e0h6rLrMad1fA_90.JPG: 480x640 (no detections), 272.2ms
Speed: 1.0ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZKEy81a3e0h6rLrMad1fA_180.JPG: 480x640 1 Waste, 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZKEy81a3e0h6rLrMad1fA_270.JPG: 480x640 (no detections), 292.5ms
Speed: 1.1ms preprocess, 292.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZMA1o29LmD0O1mC_Hd7tQ_0.JPG: 480x640 (no detections), 271.5ms

Speed: 1.1ms preprocess, 271.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZMA1o29LmD0O1mC_Hd7tQ_90.JPG: 480x640 (no detections), 270.9ms
Speed: 1.0ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZMA1o29LmD0O1mC_Hd7tQ_180.JPG: 480x640 (no detections), 277.4ms
Speed: 1.1ms preprocess, 277.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZMA1o29LmD0O1mC_Hd7tQ_270.JPG: 480x640 (no detections), 288.0ms
Speed: 1.1ms preprocess, 288.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZMFxV6PrIPyfpHJSvPLnQ_0.JPG: 480x640 (no detections), 276.9ms
Speed: 1.1ms preprocess, 276.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZMFxV6PrIPyfpHJSvPLnQ_90.JPG: 480x640 (no detections), 301.7ms
Speed: 1.1ms preprocess, 301.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZMFxV6PrIPyfpHJSvPLnQ_180.JPG: 480x640 (no detections), 282.2ms
Speed: 1.1ms preprocess, 282.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZMFxV6PrIPyfpHJSvPLnQ_270.JPG: 480x640 1 Waste, 278.6ms
Speed: 1.0ms preprocess, 278.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZOAdVcbqG2jBj7p9oSepQ_0.JPG: 480x640 (no detections), 273.3ms
Speed: 1.0ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZOAdVcbqG2jBj7p9oSepQ_90.JPG: 480x640 (no detections), 269.7ms
Speed: 1.0ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZOAdVcbqG2jBj7p9oSepQ_180.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZOAdVcbqG2jBj7p9oSepQ_270.JPG: 480x640 (no detections), 272.0ms
Speed: 1.2ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZObfVYAtOVD8P9saiyKKQ_0.JPG: 480x640 (no detections), 268.2ms
Speed: 1.1ms preprocess, 268.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZObfVYAtOVD8P9saiyKKQ_90.JPG: 480x640 (no detections), 273.6ms
Speed: 1.0ms preprocess, 273.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZObfVYAtOVD8P9saiyKKQ_180.JPG: 480x640 (no detections), 272.0ms
Speed: 1.2ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZObfVYAtOVD8P9saiyKKQ_270.JPG: 480x640 (no detections), 279.1ms
Speed: 1.1ms preprocess, 279.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZOzkrQUxBZDCU0vvqt2uw_0.JPG: 480x640 (no detections), 272.0ms
Speed: 1.1ms preprocess, 272.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZOzkrQUxBZDCU0vvqt2uw_90.JPG: 480x640 (no detections), 275.8ms
Speed: 1.2ms preprocess, 275.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZOzkrQUxBZDCU0vvqt2uw_180.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZOzkrQUxBZDCU0vvqt2uw_270.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZUUh63mG3r-iBZU1-pioQ_0.JPG: 480x640 1 Waste, 274.9ms
Speed: 1.1ms preprocess, 274.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZUUh63mG3r-iBZU1-pioQ_90.JPG: 480x640 2 Wastes, 290.5ms
Speed: 1.2ms preprocess, 290.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZUUh63mG3r-iBZU1-pioQ_180.JPG: 480x640 (no detections), 276.4ms
Speed: 1.2ms preprocess, 276.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZUUh63mG3r-iBZU1-pioQ_270.JPG: 480x640 (no detections), 273.8ms
Speed: 1.0ms preprocess, 273.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZVWNGkBta_VZaW51TBZJw_0.JPG: 480x640 (no detections), 276.1ms
Speed: 1.1ms preprocess, 276.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZVWNGkBta_VZaW51TBZJw_90.JPG: 480x640 (no detections), 293.2ms
Speed: 1.1ms preprocess, 293.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZVWNGkBta_VZaW51TBZJw_180.JPG: 480x640 (no detections), 278.9ms
Speed: 1.4ms preprocess, 278.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZVWNGkBta_VZaW51TBZJw_270.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZV_5clA-ctkLaY_YyOtiw_0.JPG: 480x640 (no detections), 276.1ms
Speed: 1.1ms preprocess, 276.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZV_5clA-ctkLaY_YyOtiw_90.JPG: 480x640 (no detections), 275.9ms
Speed: 1.2ms preprocess, 275.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZV_5clA-ctkLaY_YyOtiw_180.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZV_5clA-ctkLaY_YyOtiw_270.JPG: 480x640 (no detections), 275.5ms
Speed: 1.1ms preprocess, 275.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZXETGNRdrrSR9j1Rs6m_Q_0.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZXETGNRdrrSR9j1Rs6m_Q_90.JPG: 480x640 (no detections), 275.3ms
Speed: 1.1ms preprocess, 275.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZXETGNRdrrSR9j1Rs6m_Q_180.JPG: 480x640 (no detections), 273.1ms
Speed: 1.0ms preprocess, 273.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZXETGNRdrrSR9j1Rs6m_Q_270.JPG: 480x640 (no detections), 276.0ms
Speed: 1.1ms preprocess, 276.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZajbJtKqeGMl3QZyUSjOg_0.JPG: 480x640 (no detections), 276.8ms
Speed: 1.2ms preprocess, 276.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZajbJtKqeGMl3QZyUSjOg_90.JPG: 480x640 (no detections), 278.9ms
Speed: 1.1ms preprocess, 278.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZajbJtKqeGMl3QZyUSjOg_180.JPG: 480x640 (no detections), 275.9ms
Speed: 1.0ms preprocess, 275.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZajbJtKqeGMl3QZyUSjOg_270.JPG: 480x640 (no detections), 276.3ms
Speed: 1.1ms preprocess, 276.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZdC6ZVlXBCaAIhFzSK2lw_0.JPG: 480x640 (no detections), 290.0ms
Speed: 1.1ms preprocess, 290.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZdC6ZVlXBCaAIhFzSK2lw_90.JPG: 480x640 (no detections), 288.7ms
Speed: 1.8ms preprocess, 288.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZdC6ZVlXBCaAIhFzSK2lw_180.JPG: 480x640 (no detections), 274.1ms
Speed: 1.0ms preprocess, 274.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZdC6ZVlXBCaAIhFzSK2lw_270.JPG: 480x640 (no detections), 270.9ms
Speed: 1.1ms preprocess, 270.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZeAmo60MTVUz_4kqvSS8Q_0.JPG: 480x640 (no detections), 272.6ms
Speed: 1.0ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZeAmo60MTVUz_4kqvSS8Q_90.JPG: 480x640 (no detections), 271.4ms
Speed: 1.0ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZeAmo60MTVUz_4kqvSS8Q_180.JPG: 480x640 (no detections), 284.2ms
Speed: 1.2ms preprocess, 284.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZeAmo60MTVUz_4kqvSS8Q_270.JPG: 480x640 1 Waste, 277.2ms
Speed: 1.2ms preprocess, 277.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZfDVJeL62A2LziVgbn61A_0.JPG: 480x640 (no detections), 277.9ms
Speed: 1.0ms preprocess, 277.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZfDVJeL62A2LziVgbn61A_90.JPG: 480x640 (no detections), 275.1ms
Speed: 1.0ms preprocess, 275.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZfDVJeL62A2LziVgbn61A_180.JPG: 480x640 (no detections), 284.6ms
Speed: 1.0ms preprocess, 284.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZfDVJeL62A2LziVgbn61A_270.JPG: 480x640 (no detections), 272.9ms
Speed: 1.2ms preprocess, 272.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZftAfgjTHr4j-nRNZxIkA_0.JPG: 480x640 (no detections), 276.7ms
Speed: 1.2ms preprocess, 276.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZftAfgjTHr4j-nRNZxIkA_90.JPG: 480x640 (no detections), 277.7ms
Speed: 1.0ms preprocess, 277.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZftAfgjTHr4j-nRNZxIkA_180.JPG: 480x640 (no detections), 277.0ms
Speed: 1.2ms preprocess, 277.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZftAfgjTHr4j-nRNZxIkA_270.JPG: 480x640 (no detections), 271.3ms
Speed: 1.0ms preprocess, 271.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZj5kYxSjwJ-JQmMDbnFHA_0.JPG: 480x640 (no detections), 265.9ms
Speed: 1.0ms preprocess, 265.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZj5kYxSjwJ-JQmMDbnFHA_90.JPG: 480x640 (no detections), 321.0ms
Speed: 1.0ms preprocess, 321.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZj5kYxSjwJ-JQmMDbnFHA_180.JPG: 480x640 (no detections), 286.2ms
Speed: 1.3ms preprocess, 286.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZj5kYxSjwJ-JQmMDbnFHA_270.JPG: 480x640 (no detections), 286.4ms
Speed: 1.4ms preprocess, 286.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZkhsV8F_LEd5kvagKEqRA_0.JPG: 480x640 (no detections), 273.4ms
Speed: 1.1ms preprocess, 273.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZkhsV8F_LEd5kvagKEqRA_90.JPG: 480x640 (no detections), 273.2ms
Speed: 1.3ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZkhsV8F_LEd5kvagKEqRA_180.JPG: 480x640 (no detections), 303.3ms
Speed: 1.1ms preprocess, 303.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZkhsV8F_LEd5kvagKEqRA_270.JPG: 480x640 (no detections), 281.7ms
Speed: 1.1ms preprocess, 281.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZlGP7cPUeNZlqy2Cev_qw_0.JPG: 480x640 (no detections), 278.5ms
Speed: 1.1ms preprocess, 278.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZlGP7cPUeNZlqy2Cev_qw_90.JPG: 480x640 (no detections), 273.6ms
Speed: 1.0ms preprocess, 273.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZlGP7cPUeNZlqy2Cev_qw_180.JPG: 480x640 (no detections), 279.7ms
Speed: 1.1ms preprocess, 279.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZlGP7cPUeNZlqy2Cev_qw_270.JPG: 480x640 (no detections), 285.2ms

Speed: 1.3ms preprocess, 285.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZnMjbSPY3HYm1UaxNgnfg_0.JPG: 480x640 (no detections), 276.7ms
Speed: 1.7ms preprocess, 276.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZnMjbSPY3HYm1UaxNgnfg_90.JPG: 480x640 (no detections), 294.8ms
Speed: 1.1ms preprocess, 294.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZnMjbSPY3HYm1UaxNgnfg_180.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZnMjbSPY3HYm1UaxNgnfg_270.JPG: 480x640 (no detections), 349.5ms
Speed: 1.0ms preprocess, 349.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZsni4qsME_3r_uSlauLzQ_0.JPG: 480x640 (no detections), 369.2ms
Speed: 1.5ms preprocess, 369.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZsni4qsME_3r_uSlauLzQ_90.JPG: 480x640 (no detections), 319.7ms
Speed: 1.3ms preprocess, 319.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZsni4qsME_3r_uSlauLzQ_180.JPG: 480x640 (no detections), 284.3ms
Speed: 1.2ms preprocess, 284.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZsni4qsME_3r_uSlauLzQ_270.JPG: 480x640 (no detections), 291.8ms
Speed: 1.2ms preprocess, 291.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZx5R0_ScxDFKE63gOF46w_0.JPG: 480x640 (no detections), 282.1ms
Speed: 1.1ms preprocess, 282.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZx5R0_ScxDFKE63gOF46w_90.JPG: 480x640 (no detections), 275.0ms
Speed: 1.2ms preprocess, 275.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZx5R0_ScxDFKE63gOF46w_180.JPG: 480x640 (no detections), 279.2ms
Speed: 1.2ms preprocess, 279.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zZx5R0_ScxDFKE63gOF46w_270.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_-jDTXITKs0WZk8sNzDtg_0.JPG: 480x640 (no detections), 274.7ms
Speed: 1.1ms preprocess, 274.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_-jDTXITKs0WZk8sNzDtg_90.JPG: 480x640 (no detections), 274.4ms
Speed: 1.1ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_-jDTXITKs0WZk8sNzDtg_180.JPG: 480x640 (no detections), 282.3ms
Speed: 1.1ms preprocess, 282.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_-jDTXITKs0WZk8sNzDtg_270.JPG: 480x640 (no detections), 272.9ms
Speed: 1.2ms preprocess, 272.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_183jtbMq-JEp8W_X2nbQ_0.JPG: 480x640 (no detections), 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_183jtbMq-JEp8W_X2nbQ_90.JPG: 480x640 (no detections), 283.6ms
Speed: 1.1ms preprocess, 283.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_183jtbMq-JEp8W_X2nbQ_180.JPG: 480x640 (no detections), 270.2ms
Speed: 1.0ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_183jtbMq-JEp8W_X2nbQ_270.JPG: 480x640 (no detections), 289.5ms
Speed: 1.2ms preprocess, 289.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_6ONjUOGvWtB7PWE9f5iQ_0.JPG: 480x640 (no detections), 277.2ms
Speed: 1.1ms preprocess, 277.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_6ONjUOGvWtB7PWE9f5iQ_90.JPG: 480x640 (no detections), 272.2ms
Speed: 1.2ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_6ONjUOGvWtB7PWE9f5iQ_180.JPG: 480x640 (no detections), 278.4ms
Speed: 1.1ms preprocess, 278.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_6ONjUOGvWtB7PWE9f5iQ_270.JPG: 480x640 (no detections), 275.0ms
Speed: 1.0ms preprocess, 275.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_7qMMCnalLTmFBxv84YrQ_0.JPG: 480x640 (no detections), 306.6ms
Speed: 1.2ms preprocess, 306.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_7qMMCnalLTmFBxv84YrQ_90.JPG: 480x640 (no detections), 273.4ms
Speed: 1.1ms preprocess, 273.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_7qMMCnalLTmFBxv84YrQ_180.JPG: 480x640 (no detections), 272.3ms
Speed: 1.5ms preprocess, 272.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_7qMMCnalLTmFBxv84YrQ_270.JPG: 480x640 (no detections), 274.8ms
Speed: 1.2ms preprocess, 274.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_88jkmwRuulAnxfSGr39A_0.JPG: 480x640 (no detections), 272.5ms
Speed: 1.0ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_88jkmwRuulAnxfSGr39A_90.JPG: 480x640 (no detections), 276.6ms
Speed: 1.1ms preprocess, 276.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_88jkmwRuulAnxfSGr39A_180.JPG: 480x640 (no detections), 270.5ms
Speed: 1.0ms preprocess, 270.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_88jkmwRuulAnxfSGr39A_270.JPG: 480x640 (no detections), 272.4ms
Speed: 1.1ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_B-AI-vXRazdgXGJ3m9eQ_0.JPG: 480x640 (no detections), 267.2ms
Speed: 1.1ms preprocess, 267.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_B-AI-vXRazdgXGJ3m9eQ_90.JPG: 480x640 (no detections), 269.5ms
Speed: 1.0ms preprocess, 269.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_B-AI-vXRazdgXGJ3m9eQ_180.JPG: 480x640 (no detections), 270.9ms
Speed: 1.0ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_B-AI-vXRazdgXGJ3m9eQ_270.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_DULIaYILNZW62EY0axeQ_0.JPG: 480x640 (no detections), 273.1ms
Speed: 1.0ms preprocess, 273.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_DULIaYILNZW62EY0axeQ_90.JPG: 480x640 (no detections), 273.1ms
Speed: 1.0ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_DULIaYILNZW62EY0axeQ_180.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_DULIaYILNZW62EY0axeQ_270.JPG: 480x640 (no detections), 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_E8PVym0c7uoIi_stnihQ_0.JPG: 480x640 (no detections), 276.9ms
Speed: 1.1ms preprocess, 276.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_E8PVym0c7uoIi_stnihQ_90.JPG: 480x640 (no detections), 276.7ms
Speed: 1.6ms preprocess, 276.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_E8PVym0c7uoIi_stnihQ_180.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_E8PVym0c7uoIi_stnihQ_270.JPG: 480x640 (no detections), 270.8ms
Speed: 1.0ms preprocess, 270.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_EWJz5DumjKAggNvXoJpg_0.JPG: 480x640 (no detections), 272.7ms
Speed: 1.2ms preprocess, 272.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_EWJz5DumjKAggNvXoJpg_90.JPG: 480x640 (no detections), 277.6ms
Speed: 1.1ms preprocess, 277.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_EWJz5DumjKAggNvXoJpg_180.JPG: 480x640 (no detections), 274.3ms
Speed: 1.2ms preprocess, 274.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_EWJz5DumjKAggNvXoJpg_270.JPG: 480x640 (no detections), 273.9ms
Speed: 1.1ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_FTugzlFLnx3bXHj4V-NQ_0.JPG: 480x640 (no detections), 273.3ms
Speed: 1.3ms preprocess, 273.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_FTugzlFLnx3bXHj4V-NQ_90.JPG: 480x640 (no detections), 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_FTugzlFLnx3bXHj4V-NQ_180.JPG: 480x640 1 Waste, 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_FTugzlFLnx3bXHj4V-NQ_270.JPG: 480x640 1 Waste, 275.7ms
Speed: 1.1ms preprocess, 275.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_GbVh1utO10wBW-URfOzQ_0.JPG: 480x640 (no detections), 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_GbVh1utO10wBW-URfOzQ_90.JPG: 480x640 (no detections), 270.9ms
Speed: 1.1ms preprocess, 270.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_GbVh1utO10wBW-URfOzQ_180.JPG: 480x640 (no detections), 283.7ms
Speed: 1.0ms preprocess, 283.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_GbVh1utO10wBW-URfOzQ_270.JPG: 480x640 (no detections), 273.5ms
Speed: 1.2ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_KRRfvDOPsQkI_fB4oD_A_0.JPG: 480x640 (no detections), 270.5ms
Speed: 1.2ms preprocess, 270.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_KRRfvDOPsQkI_fB4oD_A_90.JPG: 480x640 (no detections), 267.3ms
Speed: 1.1ms preprocess, 267.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_KRRfvDOPsQkI_fB4oD_A_180.JPG: 480x640 (no detections), 274.9ms
Speed: 1.2ms preprocess, 274.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_KRRfvDOPsQkI_fB4oD_A_270.JPG: 480x640 (no detections), 291.6ms
Speed: 1.1ms preprocess, 291.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_M_Xwg_7_Q1a8qV2rRaoQ_0.JPG: 480x640 (no detections), 276.6ms
Speed: 1.1ms preprocess, 276.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_M_Xwg_7_Q1a8qV2rRaoQ_90.JPG: 480x640 (no detections), 272.3ms
Speed: 1.0ms preprocess, 272.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_M_Xwg_7_Q1a8qV2rRaoQ_180.JPG: 480x640 (no detections), 267.5ms
Speed: 1.1ms preprocess, 267.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_M_Xwg_7_Q1a8qV2rRaoQ_270.JPG: 480x640 (no detections), 281.0ms
Speed: 1.2ms preprocess, 281.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_TOlzaCN_0H373rUHBtiA_0.JPG: 480x640 (no detections), 275.6ms
Speed: 1.1ms preprocess, 275.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_TOlzaCN_0H373rUHBtiA_90.JPG: 480x640 (no detections), 274.5ms
Speed: 1.1ms preprocess, 274.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_TOlzaCN_0H373rUHBtiA_180.JPG: 480x640 (no detections), 277.4ms

Speed: 1.0ms preprocess, 277.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_TOlzaCN_0H373rUHBtiA_270.JPG: 480x640 (no detections), 279.6ms
Speed: 1.3ms preprocess, 279.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_V_R9LGu9FRFWeaW66Peg_0.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_V_R9LGu9FRFWeaW66Peg_90.JPG: 480x640 (no detections), 271.8ms
Speed: 1.2ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_V_R9LGu9FRFWeaW66Peg_180.JPG: 480x640 (no detections), 274.0ms
Speed: 1.1ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_V_R9LGu9FRFWeaW66Peg_270.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_h8UYIACGoSL0QEmaFH_Q_0.JPG: 480x640 (no detections), 284.7ms
Speed: 1.1ms preprocess, 284.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_h8UYIACGoSL0QEmaFH_Q_90.JPG: 480x640 (no detections), 308.0ms
Speed: 1.5ms preprocess, 308.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_h8UYIACGoSL0QEmaFH_Q_180.JPG: 480x640 (no detections), 304.5ms
Speed: 1.4ms preprocess, 304.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_h8UYIACGoSL0QEmaFH_Q_270.JPG: 480x640 (no detections), 282.1ms
Speed: 1.2ms preprocess, 282.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_iaw-aWQl5StS6J8m6PsA_0.JPG: 480x640 (no detections), 286.6ms
Speed: 1.1ms preprocess, 286.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_iaw-aWQl5StS6J8m6PsA_90.JPG: 480x640 (no detections), 292.0ms
Speed: 1.7ms preprocess, 292.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_iaw-aWQl5StS6J8m6PsA_180.JPG: 480x640 (no detections), 274.4ms
Speed: 1.2ms preprocess, 274.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_iaw-aWQl5StS6J8m6PsA_270.JPG: 480x640 (no detections), 294.7ms
Speed: 1.2ms preprocess, 294.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_lQNqdRDRrwvIkUl_-X8g_0.JPG: 480x640 (no detections), 276.4ms
Speed: 1.1ms preprocess, 276.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_lQNqdRDRrwvIkUl_-X8g_90.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_lQNqdRDRrwvIkUl_-X8g_180.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_lQNqdRDRrwvIkUl_-X8g_270.JPG: 480x640 (no detections), 279.4ms
Speed: 1.0ms preprocess, 279.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_m-zveI2-GFj-YiFJV4RA_0.JPG: 480x640 (no detections), 280.5ms
Speed: 1.1ms preprocess, 280.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_m-zveI2-GFj-YiFJV4RA_90.JPG: 480x640 (no detections), 331.3ms
Speed: 1.1ms preprocess, 331.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_m-zveI2-GFj-YiFJV4RA_180.JPG: 480x640 (no detections), 309.6ms
Speed: 1.4ms preprocess, 309.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_m-zveI2-GFj-YiFJV4RA_270.JPG: 480x640 (no detections), 314.0ms
Speed: 1.1ms preprocess, 314.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_ojZ2sKr6uvURWNDRC3Tg_0.JPG: 480x640 (no detections), 451.4ms
Speed: 1.3ms preprocess, 451.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_ojZ2sKr6uvURWNDRC3Tg_90.JPG: 480x640 (no detections), 342.0ms
Speed: 1.1ms preprocess, 342.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_ojZ2sKr6uvURWNDRC3Tg_180.JPG: 480x640 (no detections), 321.1ms
Speed: 1.1ms preprocess, 321.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/_/z_ojZ2sKr6uvURWNDRC3Tg_270.JPG: 480x640 (no detections), 324.4ms
Speed: 1.0ms preprocess, 324.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/za0CyX08a6RT0PTBbOwpHQ_0.JPG: 480x640 (no detections), 278.7ms
Speed: 1.1ms preprocess, 278.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/za0CyX08a6RT0PTBbOwpHQ_90.JPG: 480x640 (no detections), 279.8ms
Speed: 1.7ms preprocess, 279.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/za0CyX08a6RT0PTBbOwpHQ_180.JPG: 480x640 (no detections), 284.2ms
Speed: 1.1ms preprocess, 284.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/za0CyX08a6RT0PTBbOwpHQ_270.JPG: 480x640 (no detections), 275.9ms
Speed: 1.2ms preprocess, 275.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/za2kM74TQhMgdMCrhv6dBQ_0.JPG: 480x640 (no detections), 272.0ms
Speed: 1.1ms preprocess, 272.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/za2kM74TQhMgdMCrhv6dBQ_90.JPG: 480x640 (no detections), 279.7ms
Speed: 1.1ms preprocess, 279.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/za2kM74TQhMgdMCrhv6dBQ_180.JPG: 480x640 (no detections), 280.2ms
Speed: 1.2ms preprocess, 280.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/za2kM74TQhMgdMCrhv6dBQ_270.JPG: 480x640 (no detections), 277.5ms
Speed: 1.2ms preprocess, 277.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/za4sF8JBt920ERDNAGTsWw_0.JPG: 480x640 (no detections), 279.6ms
Speed: 1.2ms preprocess, 279.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/za4sF8JBt920ERDNAGTsWw_90.JPG: 480x640 (no detections), 267.9ms
Speed: 1.1ms preprocess, 267.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/za4sF8JBt920ERDNAGTsWw_180.JPG: 480x640 (no detections), 272.8ms
Speed: 1.0ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/za4sF8JBt920ERDNAGTsWw_270.JPG: 480x640 (no detections), 274.2ms
Speed: 1.1ms preprocess, 274.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/za63QuSZOQjEMru4C4oYMw_0.JPG: 480x640 (no detections), 305.3ms
Speed: 1.4ms preprocess, 305.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/za63QuSZOQjEMru4C4oYMw_90.JPG: 480x640 (no detections), 282.7ms
Speed: 1.1ms preprocess, 282.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/za63QuSZOQjEMru4C4oYMw_180.JPG: 480x640 (no detections), 276.0ms
Speed: 1.1ms preprocess, 276.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/za63QuSZOQjEMru4C4oYMw_270.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/za7S_zG3F3rKA4uNkx1B_Q_0.JPG: 480x640 (no detections), 298.1ms
Speed: 1.2ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/za7S_zG3F3rKA4uNkx1B_Q_90.JPG: 480x640 (no detections), 270.4ms
Speed: 1.2ms preprocess, 270.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/za7S_zG3F3rKA4uNkx1B_Q_180.JPG: 480x640 (no detections), 279.2ms
Speed: 1.0ms preprocess, 279.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/za7S_zG3F3rKA4uNkx1B_Q_270.JPG: 480x640 1 Waste, 276.6ms
Speed: 1.1ms preprocess, 276.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/za7jzNE2od5_O-v2sBGzQw_0.JPG: 480x640 (no detections), 268.3ms
Speed: 1.2ms preprocess, 268.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/za7jzNE2od5_O-v2sBGzQw_90.JPG: 480x640 (no detections), 275.0ms
Speed: 1.0ms preprocess, 275.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/za7jzNE2od5_O-v2sBGzQw_180.JPG: 480x640 (no detections), 277.2ms
Speed: 1.0ms preprocess, 277.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/za7jzNE2od5_O-v2sBGzQw_270.JPG: 480x640 (no detections), 279.9ms
Speed: 1.1ms preprocess, 279.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/za8-hLMv3MauwUtQeWqgyw_0.JPG: 480x640 (no detections), 277.4ms
Speed: 1.0ms preprocess, 277.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/za8-hLMv3MauwUtQeWqgyw_90.JPG: 480x640 (no detections), 277.3ms
Speed: 1.1ms preprocess, 277.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/za8-hLMv3MauwUtQeWqgyw_180.JPG: 480x640 (no detections), 272.6ms
Speed: 1.0ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/za8-hLMv3MauwUtQeWqgyw_270.JPG: 480x640 (no detections), 272.4ms
Speed: 1.1ms preprocess, 272.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/za9lIHMZHGEQzeqwXz2wXw_0.JPG: 480x640 (no detections), 310.0ms
Speed: 1.1ms preprocess, 310.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/za9lIHMZHGEQzeqwXz2wXw_90.JPG: 480x640 (no detections), 279.3ms
Speed: 1.1ms preprocess, 279.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/za9lIHMZHGEQzeqwXz2wXw_180.JPG: 480x640 (no detections), 271.0ms
Speed: 1.1ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/za9lIHMZHGEQzeqwXz2wXw_270.JPG: 480x640 (no detections), 273.5ms
Speed: 1.2ms preprocess, 273.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/za9qDstMPs6eJ6X-0Lotlw_0.JPG: 480x640 1 Waste, 270.3ms
Speed: 1.1ms preprocess, 270.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/za9qDstMPs6eJ6X-0Lotlw_90.JPG: 480x640 (no detections), 271.7ms
Speed: 1.0ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/za9qDstMPs6eJ6X-0Lotlw_180.JPG: 480x640 (no detections), 280.8ms
Speed: 1.3ms preprocess, 280.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/za9qDstMPs6eJ6X-0Lotlw_270.JPG: 480x640 (no detections), 274.9ms
Speed: 1.0ms preprocess, 274.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaAimKQeqj1tPYqNnF0abw_0.JPG: 480x640 (no detections), 276.9ms
Speed: 1.2ms preprocess, 276.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaAimKQeqj1tPYqNnF0abw_90.JPG: 480x640 (no detections), 268.1ms
Speed: 1.1ms preprocess, 268.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaAimKQeqj1tPYqNnF0abw_180.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaAimKQeqj1tPYqNnF0abw_270.JPG: 480x640 (no detections), 273.4ms
Speed: 1.1ms preprocess, 273.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaAv0mI4vAoFDEne8kGPjg_0.JPG: 480x640 (no detections), 274.0ms
Speed: 1.1ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaAv0mI4vAoFDEne8kGPjg_90.JPG: 480x640 (no detections), 272.1ms

Speed: 1.2ms preprocess, 272.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaAv0mI4vAoFDEne8kGPjg_180.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaAv0mI4vAoFDEne8kGPjg_270.JPG: 480x640 (no detections), 274.2ms
Speed: 1.1ms preprocess, 274.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaCabKPkcccIh5jMiBgc1w_0.JPG: 480x640 (no detections), 278.2ms
Speed: 1.1ms preprocess, 278.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaCabKPkcccIh5jMiBgc1w_90.JPG: 480x640 (no detections), 272.8ms
Speed: 1.0ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaCabKPkcccIh5jMiBgc1w_180.JPG: 480x640 (no detections), 263.2ms
Speed: 1.0ms preprocess, 263.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaCabKPkcccIh5jMiBgc1w_270.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaHxanrUK9B7dvncgHfsCQ_0.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaHxanrUK9B7dvncgHfsCQ_90.JPG: 480x640 (no detections), 277.6ms
Speed: 1.2ms preprocess, 277.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaHxanrUK9B7dvncgHfsCQ_180.JPG: 480x640 (no detections), 271.7ms
Speed: 1.2ms preprocess, 271.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaHxanrUK9B7dvncgHfsCQ_270.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaI7Xjl2fHdJgmdxIIrzUQ_0.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaI7Xjl2fHdJgmdxIIrzUQ_90.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaI7Xjl2fHdJgmdxIIrzUQ_180.JPG: 480x640 (no detections), 272.4ms
Speed: 1.1ms preprocess, 272.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaI7Xjl2fHdJgmdxIIrzUQ_270.JPG: 480x640 (no detections), 273.7ms
Speed: 1.0ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaLCKs-HIZmeBzVP2WTCww_0.JPG: 480x640 (no detections), 276.2ms
Speed: 1.1ms preprocess, 276.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaLCKs-HIZmeBzVP2WTCww_90.JPG: 480x640 (no detections), 274.1ms
Speed: 1.0ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaLCKs-HIZmeBzVP2WTCww_180.JPG: 480x640 (no detections), 276.5ms
Speed: 1.0ms preprocess, 276.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaLCKs-HIZmeBzVP2WTCww_270.JPG: 480x640 (no detections), 270.9ms
Speed: 1.0ms preprocess, 270.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaLWfw9uWpasVI-swFM4yA_0.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaLWfw9uWpasVI-swFM4yA_90.JPG: 480x640 (no detections), 275.6ms
Speed: 1.0ms preprocess, 275.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaLWfw9uWpasVI-swFM4yA_180.JPG: 480x640 (no detections), 284.6ms
Speed: 1.1ms preprocess, 284.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaLWfw9uWpasVI-swFM4yA_270.JPG: 480x640 (no detections), 274.0ms
Speed: 1.0ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaNAnahyOQa3GZMl1IEbQw_0.JPG: 480x640 (no detections), 277.0ms
Speed: 1.2ms preprocess, 277.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaNAnahyOQa3GZMl1IEbQw_90.JPG: 480x640 (no detections), 293.5ms
Speed: 1.1ms preprocess, 293.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaNAnahyOQa3GZMl1IEbQw_180.JPG: 480x640 (no detections), 325.9ms
Speed: 1.1ms preprocess, 325.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaNAnahyOQa3GZMl1IEbQw_270.JPG: 480x640 (no detections), 276.1ms
Speed: 1.5ms preprocess, 276.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaOxb080W-lKIK6e72Medg_0.JPG: 480x640 (no detections), 278.6ms
Speed: 1.3ms preprocess, 278.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaOxb080W-lKIK6e72Medg_90.JPG: 480x640 (no detections), 310.8ms
Speed: 1.2ms preprocess, 310.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaOxb080W-lKIK6e72Medg_180.JPG: 480x640 (no detections), 307.3ms
Speed: 1.8ms preprocess, 307.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaOxb080W-lKIK6e72Medg_270.JPG: 480x640 (no detections), 290.8ms
Speed: 1.3ms preprocess, 290.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaPrzn2Q8Q5VMlc3TceWgQ_0.JPG: 480x640 (no detections), 278.1ms
Speed: 1.1ms preprocess, 278.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaPrzn2Q8Q5VMlc3TceWgQ_90.JPG: 480x640 (no detections), 312.2ms
Speed: 1.7ms preprocess, 312.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaPrzn2Q8Q5VMlc3TceWgQ_180.JPG: 480x640 (no detections), 282.1ms
Speed: 1.1ms preprocess, 282.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaPrzn2Q8Q5VMlc3TceWgQ_270.JPG: 480x640 (no detections), 308.3ms
Speed: 1.2ms preprocess, 308.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaRsCxrBvn9Kr0Yy4MR6Fw_0.JPG: 480x640 (no detections), 292.2ms
Speed: 1.1ms preprocess, 292.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaRsCxrBvn9Kr0Yy4MR6Fw_90.JPG: 480x640 (no detections), 282.9ms
Speed: 1.2ms preprocess, 282.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaRsCxrBvn9Kr0Yy4MR6Fw_180.JPG: 480x640 (no detections), 277.5ms
Speed: 1.1ms preprocess, 277.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaRsCxrBvn9Kr0Yy4MR6Fw_270.JPG: 480x640 (no detections), 308.9ms
Speed: 1.2ms preprocess, 308.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaXFPWV8OanRTHe84vHIfg_0.JPG: 480x640 (no detections), 293.4ms
Speed: 1.1ms preprocess, 293.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaXFPWV8OanRTHe84vHIfg_90.JPG: 480x640 (no detections), 288.2ms
Speed: 1.3ms preprocess, 288.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaXFPWV8OanRTHe84vHIfg_180.JPG: 480x640 (no detections), 299.9ms
Speed: 1.2ms preprocess, 299.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaXFPWV8OanRTHe84vHIfg_270.JPG: 480x640 (no detections), 283.2ms
Speed: 1.2ms preprocess, 283.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaYzTmxzzXAR-EY8WgX-vw_0.JPG: 480x640 (no detections), 279.7ms
Speed: 1.1ms preprocess, 279.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaYzTmxzzXAR-EY8WgX-vw_90.JPG: 480x640 (no detections), 280.2ms
Speed: 1.2ms preprocess, 280.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaYzTmxzzXAR-EY8WgX-vw_180.JPG: 480x640 (no detections), 304.2ms
Speed: 1.2ms preprocess, 304.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaYzTmxzzXAR-EY8WgX-vw_270.JPG: 480x640 (no detections), 274.0ms
Speed: 1.2ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaZvA341jbcNxwsTFhExjg_0.JPG: 480x640 (no detections), 301.1ms
Speed: 1.1ms preprocess, 301.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaZvA341jbcNxwsTFhExjg_90.JPG: 480x640 (no detections), 274.6ms
Speed: 1.1ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaZvA341jbcNxwsTFhExjg_180.JPG: 480x640 (no detections), 275.7ms
Speed: 1.0ms preprocess, 275.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaZvA341jbcNxwsTFhExjg_270.JPG: 480x640 (no detections), 277.3ms
Speed: 1.0ms preprocess, 277.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaathyvyPfxpFaUvzeGNsQ_0.JPG: 480x640 (no detections), 274.7ms
Speed: 1.5ms preprocess, 274.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaathyvyPfxpFaUvzeGNsQ_90.JPG: 480x640 (no detections), 270.4ms
Speed: 1.2ms preprocess, 270.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaathyvyPfxpFaUvzeGNsQ_180.JPG: 480x640 (no detections), 271.1ms
Speed: 1.0ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaathyvyPfxpFaUvzeGNsQ_270.JPG: 480x640 (no detections), 262.7ms
Speed: 1.1ms preprocess, 262.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zajXR4BreFFuXsaCTtIClg_0.JPG: 480x640 1 Waste, 265.9ms
Speed: 1.1ms preprocess, 265.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zajXR4BreFFuXsaCTtIClg_90.JPG: 480x640 (no detections), 276.7ms
Speed: 1.1ms preprocess, 276.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zajXR4BreFFuXsaCTtIClg_180.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zajXR4BreFFuXsaCTtIClg_270.JPG: 480x640 (no detections), 272.8ms
Speed: 1.0ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zakKtAqxw0B3_6iRdOtjtw_0.JPG: 480x640 (no detections), 276.2ms
Speed: 1.1ms preprocess, 276.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zakKtAqxw0B3_6iRdOtjtw_90.JPG: 480x640 (no detections), 272.4ms
Speed: 1.0ms preprocess, 272.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zakKtAqxw0B3_6iRdOtjtw_180.JPG: 480x640 (no detections), 276.7ms
Speed: 1.0ms preprocess, 276.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zakKtAqxw0B3_6iRdOtjtw_270.JPG: 480x640 (no detections), 270.9ms
Speed: 1.0ms preprocess, 270.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaqutWDJtpLUu0vZZCMpAg_0.JPG: 480x640 (no detections), 271.9ms
Speed: 1.2ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaqutWDJtpLUu0vZZCMpAg_90.JPG: 480x640 (no detections), 271.0ms
Speed: 1.1ms preprocess, 271.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaqutWDJtpLUu0vZZCMpAg_180.JPG: 480x640 (no detections), 269.7ms
Speed: 1.0ms preprocess, 269.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaqutWDJtpLUu0vZZCMpAg_270.JPG: 480x640 (no detections), 277.1ms
Speed: 1.2ms preprocess, 277.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zarxSKKs78U5rH_g1aU3bQ_0.JPG: 480x640 (no detections), 276.8ms

Speed: 1.1ms preprocess, 276.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zarxSKKs78U5rH_g1aU3bQ_90.JPG: 480x640 (no detections), 273.1ms
Speed: 1.1ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zarxSKKs78U5rH_g1aU3bQ_180.JPG: 480x640 (no detections), 277.2ms
Speed: 1.2ms preprocess, 277.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zarxSKKs78U5rH_g1aU3bQ_270.JPG: 480x640 (no detections), 272.1ms
Speed: 1.1ms preprocess, 272.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zat7GzlBnZWZymLpLODfbA_0.JPG: 480x640 (no detections), 282.7ms
Speed: 1.0ms preprocess, 282.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zat7GzlBnZWZymLpLODfbA_90.JPG: 480x640 (no detections), 286.7ms
Speed: 1.2ms preprocess, 286.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zat7GzlBnZWZymLpLODfbA_180.JPG: 480x640 (no detections), 278.8ms
Speed: 1.1ms preprocess, 278.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zat7GzlBnZWZymLpLODfbA_270.JPG: 480x640 (no detections), 276.4ms
Speed: 1.2ms preprocess, 276.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaviodUd0Uhh1KZJTshOeg_0.JPG: 480x640 (no detections), 274.7ms
Speed: 1.1ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaviodUd0Uhh1KZJTshOeg_90.JPG: 480x640 (no detections), 273.3ms
Speed: 1.0ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaviodUd0Uhh1KZJTshOeg_180.JPG: 480x640 (no detections), 271.3ms
Speed: 1.0ms preprocess, 271.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zaviodUd0Uhh1KZJTshOeg_270.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zazv2EGHct9UEfHjlLXl8A_0.JPG: 480x640 (no detections), 275.4ms
Speed: 1.1ms preprocess, 275.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zazv2EGHct9UEfHjlLXl8A_90.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zazv2EGHct9UEfHjlLXl8A_180.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/a/zazv2EGHct9UEfHjlLXl8A_270.JPG: 480x640 (no detections), 274.5ms
Speed: 1.1ms preprocess, 274.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zb26WY3dT-5cp0qarhdlaA_0.JPG: 480x640 (no detections), 274.0ms
Speed: 1.1ms preprocess, 274.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zb26WY3dT-5cp0qarhdlaA_90.JPG: 480x640 (no detections), 273.9ms
Speed: 1.2ms preprocess, 273.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zb26WY3dT-5cp0qarhdlaA_180.JPG: 480x640 (no detections), 270.4ms
Speed: 1.1ms preprocess, 270.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zb26WY3dT-5cp0qarhdlaA_270.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zb3AtZctxUiJ9EbT8IAcxg_0.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zb3AtZctxUiJ9EbT8IAcxg_90.JPG: 480x640 (no detections), 277.7ms
Speed: 1.3ms preprocess, 277.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zb3AtZctxUiJ9EbT8IAcxg_180.JPG: 480x640 (no detections), 273.9ms
Speed: 1.2ms preprocess, 273.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zb3AtZctxUiJ9EbT8IAcxg_270.JPG: 480x640 (no detections), 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zb4NEQhAG6xg9PTBnhxY9Q_0.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zb4NEQhAG6xg9PTBnhxY9Q_90.JPG: 480x640 1 Waste, 276.7ms
Speed: 1.2ms preprocess, 276.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zb4NEQhAG6xg9PTBnhxY9Q_180.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zb4NEQhAG6xg9PTBnhxY9Q_270.JPG: 480x640 (no detections), 275.5ms
Speed: 1.2ms preprocess, 275.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zb6SZyCe_Lg-fNCoZSTEFw_0.JPG: 480x640 (no detections), 274.5ms
Speed: 1.2ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zb6SZyCe_Lg-fNCoZSTEFw_90.JPG: 480x640 (no detections), 274.7ms
Speed: 1.0ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zb6SZyCe_Lg-fNCoZSTEFw_180.JPG: 480x640 (no detections), 268.7ms
Speed: 1.1ms preprocess, 268.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zb6SZyCe_Lg-fNCoZSTEFw_270.JPG: 480x640 (no detections), 279.4ms
Speed: 1.0ms preprocess, 279.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zb9S_yho5Mzm1QK0N8YmHg_0.JPG: 480x640 1 Waste, 277.8ms
Speed: 1.2ms preprocess, 277.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zb9S_yho5Mzm1QK0N8YmHg_90.JPG: 480x640 (no detections), 362.8ms
Speed: 1.1ms preprocess, 362.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zb9S_yho5Mzm1QK0N8YmHg_180.JPG: 480x640 (no detections), 387.2ms
Speed: 1.1ms preprocess, 387.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zb9S_yho5Mzm1QK0N8YmHg_270.JPG: 480x640 (no detections), 274.8ms
Speed: 1.1ms preprocess, 274.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zb9b6qsEX5FojaAbEUDpDA_0.JPG: 480x640 (no detections), 274.4ms
Speed: 1.2ms preprocess, 274.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zb9b6qsEX5FojaAbEUDpDA_90.JPG: 480x640 (no detections), 273.0ms
Speed: 1.2ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zb9b6qsEX5FojaAbEUDpDA_180.JPG: 480x640 (no detections), 269.2ms
Speed: 1.2ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zb9b6qsEX5FojaAbEUDpDA_270.JPG: 480x640 (no detections), 276.1ms
Speed: 1.0ms preprocess, 276.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zb9kRO-1Ev-xcX6CA6ZpWg_0.JPG: 480x640 (no detections), 276.0ms
Speed: 1.1ms preprocess, 276.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zb9kRO-1Ev-xcX6CA6ZpWg_90.JPG: 480x640 (no detections), 270.2ms
Speed: 1.0ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zb9kRO-1Ev-xcX6CA6ZpWg_180.JPG: 480x640 (no detections), 271.3ms
Speed: 1.0ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zb9kRO-1Ev-xcX6CA6ZpWg_270.JPG: 480x640 (no detections), 275.0ms
Speed: 1.1ms preprocess, 275.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbBLIVr4ze-FqZHERGdDbg_0.JPG: 480x640 (no detections), 276.7ms
Speed: 1.2ms preprocess, 276.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbBLIVr4ze-FqZHERGdDbg_90.JPG: 480x640 (no detections), 272.1ms
Speed: 1.0ms preprocess, 272.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbBLIVr4ze-FqZHERGdDbg_180.JPG: 480x640 (no detections), 281.1ms
Speed: 1.0ms preprocess, 281.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbBLIVr4ze-FqZHERGdDbg_270.JPG: 480x640 (no detections), 280.3ms
Speed: 1.1ms preprocess, 280.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbDa0V961si4tqXbXAamqA_0.JPG: 480x640 (no detections), 282.0ms
Speed: 1.1ms preprocess, 282.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbDa0V961si4tqXbXAamqA_90.JPG: 480x640 (no detections), 280.3ms
Speed: 1.2ms preprocess, 280.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbDa0V961si4tqXbXAamqA_180.JPG: 480x640 (no detections), 275.1ms
Speed: 1.2ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbDa0V961si4tqXbXAamqA_270.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbDd6IdKKZd7jqBbVT1JHw_0.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbDd6IdKKZd7jqBbVT1JHw_90.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbDd6IdKKZd7jqBbVT1JHw_180.JPG: 480x640 (no detections), 274.7ms
Speed: 1.0ms preprocess, 274.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbDd6IdKKZd7jqBbVT1JHw_270.JPG: 480x640 (no detections), 269.4ms
Speed: 1.0ms preprocess, 269.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbEiQ2xa3ZTdJzDCvmEYvA_0.JPG: 480x640 (no detections), 285.6ms
Speed: 1.0ms preprocess, 285.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbEiQ2xa3ZTdJzDCvmEYvA_90.JPG: 480x640 (no detections), 302.6ms
Speed: 1.3ms preprocess, 302.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbEiQ2xa3ZTdJzDCvmEYvA_180.JPG: 480x640 1 Waste, 296.5ms
Speed: 1.2ms preprocess, 296.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbEiQ2xa3ZTdJzDCvmEYvA_270.JPG: 480x640 (no detections), 311.2ms
Speed: 1.4ms preprocess, 311.2ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbGKD9rpOVpxj8XPtmIeyQ_0.JPG: 480x640 (no detections), 286.1ms
Speed: 1.1ms preprocess, 286.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbGKD9rpOVpxj8XPtmIeyQ_90.JPG: 480x640 (no detections), 290.9ms
Speed: 1.1ms preprocess, 290.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbGKD9rpOVpxj8XPtmIeyQ_180.JPG: 480x640 (no detections), 303.6ms
Speed: 1.4ms preprocess, 303.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbGKD9rpOVpxj8XPtmIeyQ_270.JPG: 480x640 (no detections), 279.3ms
Speed: 1.1ms preprocess, 279.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbH60Ntmmt--YrO2jwZZjg_0.JPG: 480x640 (no detections), 274.5ms
Speed: 1.0ms preprocess, 274.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbH60Ntmmt--YrO2jwZZjg_90.JPG: 480x640 (no detections), 304.0ms
Speed: 1.5ms preprocess, 304.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbH60Ntmmt--YrO2jwZZjg_180.JPG: 480x640 (no detections), 275.7ms
Speed: 1.1ms preprocess, 275.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbH60Ntmmt--YrO2jwZZjg_270.JPG: 480x640 (no detections), 281.8ms

Speed: 1.1ms preprocess, 281.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbK0-OO9cniUvi0obW6buQ_0.JPG: 480x640 (no detections), 277.4ms
Speed: 1.1ms preprocess, 277.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbK0-OO9cniUvi0obW6buQ_90.JPG: 480x640 (no detections), 276.5ms
Speed: 1.0ms preprocess, 276.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbK0-OO9cniUvi0obW6buQ_180.JPG: 480x640 (no detections), 290.5ms
Speed: 1.1ms preprocess, 290.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbK0-OO9cniUvi0obW6buQ_270.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbLMlqJCX_8fimYO8FaDTQ_0.JPG: 480x640 (no detections), 278.5ms
Speed: 1.0ms preprocess, 278.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbLMlqJCX_8fimYO8FaDTQ_90.JPG: 480x640 (no detections), 279.7ms
Speed: 1.2ms preprocess, 279.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbLMlqJCX_8fimYO8FaDTQ_180.JPG: 480x640 (no detections), 291.4ms
Speed: 1.1ms preprocess, 291.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbLMlqJCX_8fimYO8FaDTQ_270.JPG: 480x640 (no detections), 317.2ms
Speed: 1.1ms preprocess, 317.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbQFa_R_v3HW16fwkOvs8w_0.JPG: 480x640 (no detections), 310.8ms
Speed: 1.2ms preprocess, 310.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbQFa_R_v3HW16fwkOvs8w_90.JPG: 480x640 (no detections), 302.8ms
Speed: 1.3ms preprocess, 302.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbQFa_R_v3HW16fwkOvs8w_180.JPG: 480x640 (no detections), 308.1ms
Speed: 1.3ms preprocess, 308.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbQFa_R_v3HW16fwkOvs8w_270.JPG: 480x640 (no detections), 288.1ms
Speed: 1.3ms preprocess, 288.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbQqLJwaRgL748KbGaTgYw_0.JPG: 480x640 (no detections), 306.6ms
Speed: 1.1ms preprocess, 306.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbQqLJwaRgL748KbGaTgYw_90.JPG: 480x640 (no detections), 271.7ms
Speed: 1.6ms preprocess, 271.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbQqLJwaRgL748KbGaTgYw_180.JPG: 480x640 (no detections), 311.2ms
Speed: 2.4ms preprocess, 311.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbQqLJwaRgL748KbGaTgYw_270.JPG: 480x640 (no detections), 287.4ms
Speed: 1.7ms preprocess, 287.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbUvRy1E6YJTSUqTpMOOQQ_0.JPG: 480x640 1 Waste, 281.3ms
Speed: 1.2ms preprocess, 281.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbUvRy1E6YJTSUqTpMOOQQ_90.JPG: 480x640 (no detections), 279.1ms
Speed: 1.1ms preprocess, 279.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbUvRy1E6YJTSUqTpMOOQQ_180.JPG: 480x640 (no detections), 270.0ms
Speed: 1.2ms preprocess, 270.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbUvRy1E6YJTSUqTpMOOQQ_270.JPG: 480x640 (no detections), 301.5ms
Speed: 1.1ms preprocess, 301.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbWwuY70t95iHr-88DYfFQ_0.JPG: 480x640 1 Waste, 309.5ms
Speed: 1.3ms preprocess, 309.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbWwuY70t95iHr-88DYfFQ_90.JPG: 480x640 1 Waste, 294.2ms
Speed: 1.2ms preprocess, 294.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbWwuY70t95iHr-88DYfFQ_180.JPG: 480x640 (no detections), 280.8ms
Speed: 1.0ms preprocess, 280.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbWwuY70t95iHr-88DYfFQ_270.JPG: 480x640 (no detections), 274.6ms
Speed: 1.4ms preprocess, 274.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbYqk3Z4YeaVBDXh2OpvjQ_0.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbYqk3Z4YeaVBDXh2OpvjQ_90.JPG: 480x640 (no detections), 273.7ms
Speed: 1.0ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbYqk3Z4YeaVBDXh2OpvjQ_180.JPG: 480x640 (no detections), 276.8ms
Speed: 1.1ms preprocess, 276.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbYqk3Z4YeaVBDXh2OpvjQ_270.JPG: 480x640 (no detections), 272.3ms
Speed: 1.0ms preprocess, 272.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zb_2JMwbuDJX7CeKy5TAgA_0.JPG: 480x640 (no detections), 271.9ms
Speed: 1.0ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zb_2JMwbuDJX7CeKy5TAgA_90.JPG: 480x640 (no detections), 273.6ms
Speed: 1.0ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zb_2JMwbuDJX7CeKy5TAgA_180.JPG: 480x640 (no detections), 270.4ms
Speed: 1.0ms preprocess, 270.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zb_2JMwbuDJX7CeKy5TAgA_270.JPG: 480x640 (no detections), 274.5ms
Speed: 1.0ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zb_UwXSag4TveOd3VZhdMQ_0.JPG: 480x640 (no detections), 274.9ms
Speed: 1.1ms preprocess, 274.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zb_UwXSag4TveOd3VZhdMQ_90.JPG: 480x640 (no detections), 271.7ms
Speed: 1.0ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zb_UwXSag4TveOd3VZhdMQ_180.JPG: 480x640 (no detections), 267.5ms
Speed: 1.0ms preprocess, 267.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zb_UwXSag4TveOd3VZhdMQ_270.JPG: 480x640 (no detections), 275.2ms
Speed: 1.1ms preprocess, 275.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbf3I37AO3EtzlhYgTnbDw_0.JPG: 480x640 (no detections), 294.5ms
Speed: 1.4ms preprocess, 294.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbf3I37AO3EtzlhYgTnbDw_90.JPG: 480x640 (no detections), 281.9ms
Speed: 1.2ms preprocess, 281.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbf3I37AO3EtzlhYgTnbDw_180.JPG: 480x640 (no detections), 274.4ms
Speed: 1.2ms preprocess, 274.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbf3I37AO3EtzlhYgTnbDw_270.JPG: 480x640 (no detections), 279.5ms
Speed: 1.3ms preprocess, 279.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbfgPe8p4rB2b5N9L7bWVw_0.JPG: 480x640 (no detections), 274.6ms
Speed: 1.1ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbfgPe8p4rB2b5N9L7bWVw_90.JPG: 480x640 (no detections), 269.6ms
Speed: 1.0ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbfgPe8p4rB2b5N9L7bWVw_180.JPG: 480x640 (no detections), 272.3ms
Speed: 1.1ms preprocess, 272.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbfgPe8p4rB2b5N9L7bWVw_270.JPG: 480x640 (no detections), 272.3ms
Speed: 1.1ms preprocess, 272.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbgopn1iHMe3auO2EcJ3qQ_0.JPG: 480x640 (no detections), 276.4ms
Speed: 1.1ms preprocess, 276.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbgopn1iHMe3auO2EcJ3qQ_90.JPG: 480x640 (no detections), 272.9ms
Speed: 1.0ms preprocess, 272.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbgopn1iHMe3auO2EcJ3qQ_180.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbgopn1iHMe3auO2EcJ3qQ_270.JPG: 480x640 (no detections), 288.1ms
Speed: 1.1ms preprocess, 288.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbhLV72Pw-_Jr4nyxuNR3A_0.JPG: 480x640 (no detections), 283.5ms
Speed: 1.2ms preprocess, 283.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbhLV72Pw-_Jr4nyxuNR3A_90.JPG: 480x640 (no detections), 274.5ms
Speed: 1.2ms preprocess, 274.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbhLV72Pw-_Jr4nyxuNR3A_180.JPG: 480x640 (no detections), 275.8ms
Speed: 1.1ms preprocess, 275.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbhLV72Pw-_Jr4nyxuNR3A_270.JPG: 480x640 (no detections), 269.0ms
Speed: 1.1ms preprocess, 269.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbhgYr3c8z2-qCmFOniFLg_0.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbhgYr3c8z2-qCmFOniFLg_90.JPG: 480x640 (no detections), 279.0ms
Speed: 1.0ms preprocess, 279.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbhgYr3c8z2-qCmFOniFLg_180.JPG: 480x640 (no detections), 283.4ms
Speed: 1.5ms preprocess, 283.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbhgYr3c8z2-qCmFOniFLg_270.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbk-qrw6QsFqOpWbfZX2dg_0.JPG: 480x640 (no detections), 285.8ms
Speed: 1.2ms preprocess, 285.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbk-qrw6QsFqOpWbfZX2dg_90.JPG: 480x640 (no detections), 276.8ms
Speed: 1.1ms preprocess, 276.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbk-qrw6QsFqOpWbfZX2dg_180.JPG: 480x640 (no detections), 279.2ms
Speed: 1.5ms preprocess, 279.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbk-qrw6QsFqOpWbfZX2dg_270.JPG: 480x640 (no detections), 277.4ms
Speed: 1.1ms preprocess, 277.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbkJ_DOI26j5KMYRJ4XDfw_0.JPG: 480x640 (no detections), 274.9ms
Speed: 1.0ms preprocess, 274.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbkJ_DOI26j5KMYRJ4XDfw_90.JPG: 480x640 (no detections), 278.7ms
Speed: 1.1ms preprocess, 278.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbkJ_DOI26j5KMYRJ4XDfw_180.JPG: 480x640 (no detections), 272.3ms
Speed: 1.2ms preprocess, 272.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbkJ_DOI26j5KMYRJ4XDfw_270.JPG: 480x640 (no detections), 279.5ms
Speed: 1.1ms preprocess, 279.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbmAf-KupgC-NpMA2Ibb_g_0.JPG: 480x640 (no detections), 277.5ms
Speed: 1.1ms preprocess, 277.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbmAf-KupgC-NpMA2Ibb_g_90.JPG: 480x640 (no detections), 275.3ms
Speed: 1.2ms preprocess, 275.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbmAf-KupgC-NpMA2Ibb_g_180.JPG: 480x640 (no detections), 273.8ms

Speed: 1.0ms preprocess, 273.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbmAf-KupgC-NpMA2Ibb_g_270.JPG: 480x640 (no detections), 274.3ms
Speed: 1.2ms preprocess, 274.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbrHdwR1RGAPNLVLn3CM1g_0.JPG: 480x640 (no detections), 270.7ms
Speed: 1.2ms preprocess, 270.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbrHdwR1RGAPNLVLn3CM1g_90.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbrHdwR1RGAPNLVLn3CM1g_180.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbrHdwR1RGAPNLVLn3CM1g_270.JPG: 480x640 (no detections), 272.3ms
Speed: 1.1ms preprocess, 272.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbvd7hm-k6hjlCqCY_9K6w_0.JPG: 480x640 (no detections), 270.5ms
Speed: 1.7ms preprocess, 270.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbvd7hm-k6hjlCqCY_9K6w_90.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbvd7hm-k6hjlCqCY_9K6w_180.JPG: 480x640 (no detections), 274.2ms
Speed: 1.1ms preprocess, 274.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbvd7hm-k6hjlCqCY_9K6w_270.JPG: 480x640 (no detections), 269.0ms
Speed: 1.2ms preprocess, 269.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbzXOKCzZFEVeylNB71vrA_0.JPG: 480x640 (no detections), 268.7ms
Speed: 1.0ms preprocess, 268.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbzXOKCzZFEVeylNB71vrA_90.JPG: 480x640 (no detections), 281.0ms
Speed: 1.1ms preprocess, 281.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbzXOKCzZFEVeylNB71vrA_180.JPG: 480x640 (no detections), 281.7ms
Speed: 1.1ms preprocess, 281.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/B/zbzXOKCzZFEVeylNB71vrA_270.JPG: 480x640 (no detections), 273.0ms
Speed: 1.2ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zc-gy0yfBFok_ROKqll_qw_0.JPG: 480x640 (no detections), 274.5ms
Speed: 1.3ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zc-gy0yfBFok_ROKqll_qw_90.JPG: 480x640 (no detections), 272.4ms
Speed: 1.2ms preprocess, 272.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zc-gy0yfBFok_ROKqll_qw_180.JPG: 480x640 (no detections), 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zc-gy0yfBFok_ROKqll_qw_270.JPG: 480x640 1 Waste, 273.0ms
Speed: 1.0ms preprocess, 273.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zc0CraNIOJLOXbvdCOTs3g_0.JPG: 480x640 (no detections), 305.8ms
Speed: 1.0ms preprocess, 305.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zc0CraNIOJLOXbvdCOTs3g_90.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zc0CraNIOJLOXbvdCOTs3g_180.JPG: 480x640 (no detections), 279.5ms
Speed: 1.1ms preprocess, 279.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zc0CraNIOJLOXbvdCOTs3g_270.JPG: 480x640 (no detections), 282.4ms
Speed: 1.1ms preprocess, 282.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zc2qkygkOO0p63qLYNS6gQ_0.JPG: 480x640 (no detections), 269.6ms
Speed: 1.1ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zc2qkygkOO0p63qLYNS6gQ_90.JPG: 480x640 (no detections), 271.7ms
Speed: 1.0ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zc2qkygkOO0p63qLYNS6gQ_180.JPG: 480x640 (no detections), 270.3ms
Speed: 1.1ms preprocess, 270.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zc2qkygkOO0p63qLYNS6gQ_270.JPG: 480x640 (no detections), 274.1ms
Speed: 1.0ms preprocess, 274.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zc2vWBWS_af9qux68ZOhHQ_0.JPG: 480x640 (no detections), 281.7ms
Speed: 1.0ms preprocess, 281.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zc2vWBWS_af9qux68ZOhHQ_90.JPG: 480x640 (no detections), 278.7ms
Speed: 1.0ms preprocess, 278.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zc2vWBWS_af9qux68ZOhHQ_180.JPG: 480x640 (no detections), 277.1ms
Speed: 1.1ms preprocess, 277.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zc2vWBWS_af9qux68ZOhHQ_270.JPG: 480x640 (no detections), 273.4ms
Speed: 1.0ms preprocess, 273.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zc7r384OY1xhDfyvdhix4g_0.JPG: 480x640 (no detections), 277.7ms
Speed: 1.1ms preprocess, 277.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zc7r384OY1xhDfyvdhix4g_90.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zc7r384OY1xhDfyvdhix4g_180.JPG: 480x640 (no detections), 277.6ms
Speed: 1.1ms preprocess, 277.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zc7r384OY1xhDfyvdhix4g_270.JPG: 480x640 (no detections), 275.0ms
Speed: 1.1ms preprocess, 275.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zc88ndYKCt_DjipOYCIQ-A_0.JPG: 480x640 (no detections), 281.0ms
Speed: 1.2ms preprocess, 281.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zc88ndYKCt_DjipOYCIQ-A_90.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zc88ndYKCt_DjipOYCIQ-A_180.JPG: 480x640 (no detections), 272.4ms
Speed: 1.0ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zc88ndYKCt_DjipOYCIQ-A_270.JPG: 480x640 (no detections), 274.1ms
Speed: 1.0ms preprocess, 274.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zc8hJt2GGW_1nY3n0lIRdg_0.JPG: 480x640 (no detections), 273.4ms
Speed: 1.0ms preprocess, 273.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zc8hJt2GGW_1nY3n0lIRdg_90.JPG: 480x640 (no detections), 275.5ms
Speed: 1.1ms preprocess, 275.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zc8hJt2GGW_1nY3n0lIRdg_180.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zc8hJt2GGW_1nY3n0lIRdg_270.JPG: 480x640 (no detections), 290.5ms
Speed: 1.1ms preprocess, 290.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcCOuNByQoqrTSszZMBjrA_0.JPG: 480x640 (no detections), 275.3ms
Speed: 1.2ms preprocess, 275.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcCOuNByQoqrTSszZMBjrA_90.JPG: 480x640 (no detections), 268.0ms
Speed: 1.0ms preprocess, 268.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcCOuNByQoqrTSszZMBjrA_180.JPG: 480x640 1 Waste, 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcCOuNByQoqrTSszZMBjrA_270.JPG: 480x640 1 Waste, 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcFwO_AhfDQ8ajnO6jdj4A_0.JPG: 480x640 (no detections), 273.7ms
Speed: 1.0ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcFwO_AhfDQ8ajnO6jdj4A_90.JPG: 480x640 (no detections), 284.3ms
Speed: 1.1ms preprocess, 284.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcFwO_AhfDQ8ajnO6jdj4A_180.JPG: 480x640 (no detections), 273.2ms
Speed: 1.1ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcFwO_AhfDQ8ajnO6jdj4A_270.JPG: 480x640 (no detections), 277.5ms
Speed: 1.0ms preprocess, 277.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcHe84I8Q_7xtojl52xxHw_0.JPG: 480x640 (no detections), 272.0ms
Speed: 1.1ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcHe84I8Q_7xtojl52xxHw_90.JPG: 480x640 (no detections), 277.6ms
Speed: 1.2ms preprocess, 277.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcHe84I8Q_7xtojl52xxHw_180.JPG: 480x640 (no detections), 268.8ms
Speed: 1.1ms preprocess, 268.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcHe84I8Q_7xtojl52xxHw_270.JPG: 480x640 (no detections), 273.9ms
Speed: 1.1ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcNyp-7spDcVLh3NGeqscQ_0.JPG: 480x640 (no detections), 273.2ms
Speed: 1.1ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcNyp-7spDcVLh3NGeqscQ_90.JPG: 480x640 (no detections), 271.4ms
Speed: 1.0ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcNyp-7spDcVLh3NGeqscQ_180.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcNyp-7spDcVLh3NGeqscQ_270.JPG: 480x640 (no detections), 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcO2DC_2JjvYYhYTS4WPkw_0.JPG: 480x640 (no detections), 274.7ms
Speed: 1.0ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcO2DC_2JjvYYhYTS4WPkw_90.JPG: 480x640 (no detections), 282.3ms
Speed: 1.2ms preprocess, 282.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcO2DC_2JjvYYhYTS4WPkw_180.JPG: 480x640 (no detections), 273.7ms
Speed: 1.0ms preprocess, 273.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcO2DC_2JjvYYhYTS4WPkw_270.JPG: 480x640 (no detections), 278.1ms
Speed: 1.1ms preprocess, 278.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcTXxTBH6nlOyWc5AtaKkg_0.JPG: 480x640 (no detections), 275.5ms
Speed: 1.5ms preprocess, 275.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcTXxTBH6nlOyWc5AtaKkg_90.JPG: 480x640 (no detections), 275.8ms
Speed: 1.3ms preprocess, 275.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcTXxTBH6nlOyWc5AtaKkg_180.JPG: 480x640 (no detections), 324.7ms
Speed: 1.0ms preprocess, 324.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcTXxTBH6nlOyWc5AtaKkg_270.JPG: 480x640 (no detections), 289.2ms
Speed: 1.2ms preprocess, 289.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcUeNDwqeYDngxkQOiALpA_0.JPG: 480x640 (no detections), 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcUeNDwqeYDngxkQOiALpA_90.JPG: 480x640 (no detections), 280.2ms

Speed: 1.2ms preprocess, 280.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcUeNDwqeYDngxkQOiALpA_180.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcUeNDwqeYDngxkQOiALpA_270.JPG: 480x640 (no detections), 359.0ms
Speed: 1.1ms preprocess, 359.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcVc41JxC-9NdxiM6ZSxIw_0.JPG: 480x640 (no detections), 370.5ms
Speed: 1.6ms preprocess, 370.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcVc41JxC-9NdxiM6ZSxIw_90.JPG: 480x640 (no detections), 310.9ms
Speed: 1.1ms preprocess, 310.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcVc41JxC-9NdxiM6ZSxIw_180.JPG: 480x640 (no detections), 286.1ms
Speed: 1.2ms preprocess, 286.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcVc41JxC-9NdxiM6ZSxIw_270.JPG: 480x640 (no detections), 286.2ms
Speed: 1.2ms preprocess, 286.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcX-SRU_dz9sU8X0e1qmPg_0.JPG: 480x640 (no detections), 283.5ms
Speed: 1.1ms preprocess, 283.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcX-SRU_dz9sU8X0e1qmPg_90.JPG: 480x640 (no detections), 298.6ms
Speed: 1.1ms preprocess, 298.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcX-SRU_dz9sU8X0e1qmPg_180.JPG: 480x640 (no detections), 272.7ms
Speed: 1.2ms preprocess, 272.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcX-SRU_dz9sU8X0e1qmPg_270.JPG: 480x640 (no detections), 305.9ms
Speed: 1.1ms preprocess, 305.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcZW73-AsJt7dhfDEqT-pw_0.JPG: 480x640 (no detections), 276.5ms
Speed: 1.2ms preprocess, 276.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcZW73-AsJt7dhfDEqT-pw_90.JPG: 480x640 (no detections), 270.2ms
Speed: 1.0ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcZW73-AsJt7dhfDEqT-pw_180.JPG: 480x640 (no detections), 277.5ms
Speed: 1.1ms preprocess, 277.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcZW73-AsJt7dhfDEqT-pw_270.JPG: 480x640 (no detections), 270.9ms
Speed: 1.1ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zce9GeejEfoPct6hCvEKBA_0.JPG: 480x640 (no detections), 276.1ms
Speed: 1.0ms preprocess, 276.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zce9GeejEfoPct6hCvEKBA_90.JPG: 480x640 (no detections), 270.3ms
Speed: 1.1ms preprocess, 270.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zce9GeejEfoPct6hCvEKBA_180.JPG: 480x640 (no detections), 267.8ms
Speed: 1.1ms preprocess, 267.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zce9GeejEfoPct6hCvEKBA_270.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcej3eG71UMvMoP0-F-8FA_0.JPG: 480x640 (no detections), 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcej3eG71UMvMoP0-F-8FA_90.JPG: 480x640 (no detections), 272.4ms
Speed: 1.0ms preprocess, 272.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcej3eG71UMvMoP0-F-8FA_180.JPG: 480x640 (no detections), 291.5ms
Speed: 1.0ms preprocess, 291.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcej3eG71UMvMoP0-F-8FA_270.JPG: 480x640 (no detections), 278.7ms
Speed: 1.1ms preprocess, 278.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcfvk60KEnCc2ag8-TVmnw_0.JPG: 480x640 (no detections), 276.6ms
Speed: 1.1ms preprocess, 276.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcfvk60KEnCc2ag8-TVmnw_90.JPG: 480x640 (no detections), 276.2ms
Speed: 1.1ms preprocess, 276.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcfvk60KEnCc2ag8-TVmnw_180.JPG: 480x640 (no detections), 272.1ms
Speed: 1.1ms preprocess, 272.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcfvk60KEnCc2ag8-TVmnw_270.JPG: 480x640 (no detections), 276.0ms
Speed: 1.1ms preprocess, 276.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcqEYpT2jKBxZ6F3kOFgKg_0.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcqEYpT2jKBxZ6F3kOFgKg_90.JPG: 480x640 (no detections), 270.6ms
Speed: 1.0ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcqEYpT2jKBxZ6F3kOFgKg_180.JPG: 480x640 1 Waste, 276.3ms
Speed: 1.1ms preprocess, 276.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcqEYpT2jKBxZ6F3kOFgKg_270.JPG: 480x640 (no detections), 269.9ms
Speed: 1.0ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcqlN2XdWQpARLSLRrVHIw_0.JPG: 480x640 (no detections), 275.6ms
Speed: 1.0ms preprocess, 275.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcqlN2XdWQpARLSLRrVHIw_90.JPG: 480x640 (no detections), 300.1ms
Speed: 1.1ms preprocess, 300.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcqlN2XdWQpARLSLRrVHIw_180.JPG: 480x640 (no detections), 271.0ms
Speed: 1.0ms preprocess, 271.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcqlN2XdWQpARLSLRrVHIw_270.JPG: 480x640 (no detections), 301.3ms
Speed: 1.0ms preprocess, 301.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcrT326ptRT7UBzAKtH6-w_0.JPG: 480x640 (no detections), 272.0ms
Speed: 1.0ms preprocess, 272.0ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcrT326ptRT7UBzAKtH6-w_90.JPG: 480x640 (no detections), 270.0ms
Speed: 1.0ms preprocess, 270.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcrT326ptRT7UBzAKtH6-w_180.JPG: 480x640 (no detections), 268.3ms
Speed: 1.0ms preprocess, 268.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcrT326ptRT7UBzAKtH6-w_270.JPG: 480x640 (no detections), 277.9ms
Speed: 1.0ms preprocess, 277.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcwaTwpe8wAJTRqzhm30ew_0.JPG: 480x640 (no detections), 278.5ms
Speed: 1.5ms preprocess, 278.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcwaTwpe8wAJTRqzhm30ew_90.JPG: 480x640 (no detections), 270.3ms
Speed: 1.1ms preprocess, 270.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcwaTwpe8wAJTRqzhm30ew_180.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcwaTwpe8wAJTRqzhm30ew_270.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcwuW49KtzYfAZMgnQpcjg_0.JPG: 480x640 (no detections), 271.9ms
Speed: 1.3ms preprocess, 271.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcwuW49KtzYfAZMgnQpcjg_90.JPG: 480x640 (no detections), 277.0ms
Speed: 1.1ms preprocess, 277.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcwuW49KtzYfAZMgnQpcjg_180.JPG: 480x640 (no detections), 266.4ms
Speed: 1.1ms preprocess, 266.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcwuW49KtzYfAZMgnQpcjg_270.JPG: 480x640 (no detections), 270.3ms
Speed: 1.1ms preprocess, 270.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcy3fY0zDf6-aYOpDengRw_0.JPG: 480x640 (no detections), 270.3ms
Speed: 1.0ms preprocess, 270.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcy3fY0zDf6-aYOpDengRw_90.JPG: 480x640 (no detections), 272.4ms
Speed: 1.2ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcy3fY0zDf6-aYOpDengRw_180.JPG: 480x640 (no detections), 274.3ms
Speed: 1.1ms preprocess, 274.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zcy3fY0zDf6-aYOpDengRw_270.JPG: 480x640 (no detections), 274.1ms
Speed: 1.2ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zczazuA-fSNceVo_EHLfXw_0.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zczazuA-fSNceVo_EHLfXw_90.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zczazuA-fSNceVo_EHLfXw_180.JPG: 480x640 (no detections), 277.0ms
Speed: 1.0ms preprocess, 277.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/C/zczazuA-fSNceVo_EHLfXw_270.JPG: 480x640 (no detections), 274.1ms
Speed: 1.0ms preprocess, 274.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zd5iJVThG9jQvhEeBKB5QA_0.JPG: 480x640 (no detections), 274.5ms
Speed: 1.2ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zd5iJVThG9jQvhEeBKB5QA_90.JPG: 480x640 (no detections), 272.0ms
Speed: 1.1ms preprocess, 272.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zd5iJVThG9jQvhEeBKB5QA_180.JPG: 480x640 (no detections), 269.6ms
Speed: 1.1ms preprocess, 269.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zd5iJVThG9jQvhEeBKB5QA_270.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zd86yQL2LjvraRKN9aiIAQ_0.JPG: 480x640 (no detections), 275.6ms
Speed: 1.2ms preprocess, 275.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zd86yQL2LjvraRKN9aiIAQ_90.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zd86yQL2LjvraRKN9aiIAQ_180.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zd86yQL2LjvraRKN9aiIAQ_270.JPG: 480x640 1 Waste, 269.0ms
Speed: 1.1ms preprocess, 269.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zd9alibSgWQYBQjzWKZdmQ_0.JPG: 480x640 (no detections), 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zd9alibSgWQYBQjzWKZdmQ_90.JPG: 480x640 (no detections), 273.4ms
Speed: 1.1ms preprocess, 273.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zd9alibSgWQYBQjzWKZdmQ_180.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zd9alibSgWQYBQjzWKZdmQ_270.JPG: 480x640 (no detections), 277.4ms
Speed: 1.0ms preprocess, 277.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdBgYI7IzdgmAH-c8VQOmw_0.JPG: 480x640 (no detections), 272.7ms

Speed: 1.0ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdBgYI7IzdgmAH-c8VQOmw_90.JPG: 480x640 (no detections), 271.4ms
Speed: 1.2ms preprocess, 271.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdBgYI7IzdgmAH-c8VQOmw_180.JPG: 480x640 (no detections), 277.3ms
Speed: 1.0ms preprocess, 277.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdBgYI7IzdgmAH-c8VQOmw_270.JPG: 480x640 (no detections), 276.1ms
Speed: 1.0ms preprocess, 276.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdEBor-S_JkpOyrIWOXO_g_0.JPG: 480x640 (no detections), 271.8ms
Speed: 1.2ms preprocess, 271.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdEBor-S_JkpOyrIWOXO_g_90.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdEBor-S_JkpOyrIWOXO_g_180.JPG: 480x640 (no detections), 274.9ms
Speed: 1.2ms preprocess, 274.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdEBor-S_JkpOyrIWOXO_g_270.JPG: 480x640 (no detections), 277.7ms
Speed: 1.1ms preprocess, 277.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdFDe6aJXnr26EuDvFtesQ_0.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdFDe6aJXnr26EuDvFtesQ_90.JPG: 480x640 (no detections), 280.1ms
Speed: 1.1ms preprocess, 280.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdFDe6aJXnr26EuDvFtesQ_180.JPG: 480x640 (no detections), 272.4ms
Speed: 1.1ms preprocess, 272.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdFDe6aJXnr26EuDvFtesQ_270.JPG: 480x640 (no detections), 272.2ms
Speed: 1.2ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdHH45NKtREwA2G9tdX4gQ_0.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdHH45NKtREwA2G9tdX4gQ_90.JPG: 480x640 (no detections), 279.5ms
Speed: 1.2ms preprocess, 279.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdHH45NKtREwA2G9tdX4gQ_180.JPG: 480x640 (no detections), 274.7ms
Speed: 1.1ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdHH45NKtREwA2G9tdX4gQ_270.JPG: 480x640 (no detections), 280.1ms
Speed: 1.2ms preprocess, 280.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdI6iCJgw8ibTQCRhHep5g_0.JPG: 480x640 (no detections), 285.5ms
Speed: 1.4ms preprocess, 285.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdI6iCJgw8ibTQCRhHep5g_90.JPG: 480x640 (no detections), 274.3ms
Speed: 1.1ms preprocess, 274.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdI6iCJgw8ibTQCRhHep5g_180.JPG: 480x640 (no detections), 272.0ms
Speed: 1.0ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdI6iCJgw8ibTQCRhHep5g_270.JPG: 480x640 (no detections), 274.4ms
Speed: 1.1ms preprocess, 274.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdISqLJ-qMjjs1NLLwJWNw_0.JPG: 480x640 (no detections), 272.1ms
Speed: 1.1ms preprocess, 272.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdISqLJ-qMjjs1NLLwJWNw_90.JPG: 480x640 (no detections), 273.6ms
Speed: 1.1ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdISqLJ-qMjjs1NLLwJWNw_180.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdISqLJ-qMjjs1NLLwJWNw_270.JPG: 480x640 (no detections), 270.8ms
Speed: 1.0ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdMvjjDV4LJ2alFCWofPig_0.JPG: 480x640 (no detections), 279.0ms
Speed: 1.1ms preprocess, 279.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdMvjjDV4LJ2alFCWofPig_90.JPG: 480x640 (no detections), 276.9ms
Speed: 1.1ms preprocess, 276.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdMvjjDV4LJ2alFCWofPig_180.JPG: 480x640 (no detections), 279.6ms
Speed: 1.1ms preprocess, 279.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdMvjjDV4LJ2alFCWofPig_270.JPG: 480x640 (no detections), 272.3ms
Speed: 1.1ms preprocess, 272.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdNE_1qnXu-gpUfok96hxA_0.JPG: 480x640 (no detections), 276.5ms
Speed: 1.1ms preprocess, 276.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdNE_1qnXu-gpUfok96hxA_90.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdNE_1qnXu-gpUfok96hxA_180.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdNE_1qnXu-gpUfok96hxA_270.JPG: 480x640 (no detections), 277.2ms
Speed: 1.0ms preprocess, 277.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdNugnlvGj81V8rHDL2_mg_0.JPG: 480x640 (no detections), 273.9ms
Speed: 1.1ms preprocess, 273.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdNugnlvGj81V8rHDL2_mg_90.JPG: 480x640 (no detections), 300.1ms
Speed: 1.1ms preprocess, 300.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdNugnlvGj81V8rHDL2_mg_180.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdNugnlvGj81V8rHDL2_mg_270.JPG: 480x640 (no detections), 275.2ms
Speed: 1.2ms preprocess, 275.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdUgn0WkheXA8iU1HHuf1g_0.JPG: 480x640 (no detections), 275.1ms
Speed: 1.0ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdUgn0WkheXA8iU1HHuf1g_90.JPG: 480x640 (no detections), 288.5ms
Speed: 1.2ms preprocess, 288.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdUgn0WkheXA8iU1HHuf1g_180.JPG: 480x640 (no detections), 281.8ms
Speed: 1.1ms preprocess, 281.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdUgn0WkheXA8iU1HHuf1g_270.JPG: 480x640 (no detections), 272.1ms
Speed: 1.1ms preprocess, 272.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdZVhq2PggCNFU30JnweXg_0.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdZVhq2PggCNFU30JnweXg_90.JPG: 480x640 (no detections), 278.3ms
Speed: 1.2ms preprocess, 278.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdZVhq2PggCNFU30JnweXg_180.JPG: 480x640 (no detections), 276.5ms
Speed: 1.1ms preprocess, 276.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdZVhq2PggCNFU30JnweXg_270.JPG: 480x640 (no detections), 272.1ms
Speed: 1.1ms preprocess, 272.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdcFkCa-BzwSs-knefk-qQ_0.JPG: 480x640 (no detections), 281.4ms
Speed: 1.2ms preprocess, 281.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdcFkCa-BzwSs-knefk-qQ_90.JPG: 480x640 (no detections), 277.1ms
Speed: 1.1ms preprocess, 277.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdcFkCa-BzwSs-knefk-qQ_180.JPG: 480x640 (no detections), 271.5ms
Speed: 1.0ms preprocess, 271.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdcFkCa-BzwSs-knefk-qQ_270.JPG: 480x640 (no detections), 274.9ms
Speed: 1.0ms preprocess, 274.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdc_JEm4H_dAmg7vzTYVRA_0.JPG: 480x640 (no detections), 277.9ms
Speed: 1.0ms preprocess, 277.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdc_JEm4H_dAmg7vzTYVRA_90.JPG: 480x640 (no detections), 275.4ms
Speed: 1.1ms preprocess, 275.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdc_JEm4H_dAmg7vzTYVRA_180.JPG: 480x640 (no detections), 269.7ms
Speed: 1.0ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdc_JEm4H_dAmg7vzTYVRA_270.JPG: 480x640 (no detections), 275.3ms
Speed: 1.1ms preprocess, 275.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdflr8DsYfTHybiduSxgoQ_0.JPG: 480x640 (no detections), 305.2ms
Speed: 1.1ms preprocess, 305.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdflr8DsYfTHybiduSxgoQ_90.JPG: 480x640 (no detections), 274.3ms
Speed: 1.0ms preprocess, 274.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdflr8DsYfTHybiduSxgoQ_180.JPG: 480x640 (no detections), 272.0ms
Speed: 1.0ms preprocess, 272.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdflr8DsYfTHybiduSxgoQ_270.JPG: 480x640 (no detections), 284.7ms
Speed: 1.1ms preprocess, 284.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdgK5TzYeMf13ZDX-Wk20w_0.JPG: 480x640 (no detections), 272.2ms
Speed: 1.2ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdgK5TzYeMf13ZDX-Wk20w_90.JPG: 480x640 (no detections), 276.2ms
Speed: 1.1ms preprocess, 276.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdgK5TzYeMf13ZDX-Wk20w_180.JPG: 480x640 (no detections), 275.9ms
Speed: 1.1ms preprocess, 275.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdgK5TzYeMf13ZDX-Wk20w_270.JPG: 480x640 (no detections), 277.7ms
Speed: 1.1ms preprocess, 277.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdmGCK44pLtDYfngZf_hxA_0.JPG: 480x640 (no detections), 275.4ms
Speed: 1.1ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdmGCK44pLtDYfngZf_hxA_90.JPG: 480x640 (no detections), 273.9ms
Speed: 1.3ms preprocess, 273.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdmGCK44pLtDYfngZf_hxA_180.JPG: 480x640 (no detections), 274.0ms
Speed: 1.0ms preprocess, 274.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdmGCK44pLtDYfngZf_hxA_270.JPG: 480x640 (no detections), 274.8ms
Speed: 1.0ms preprocess, 274.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdmN-k6BEfNUVH_-fPm5sA_0.JPG: 480x640 (no detections), 276.3ms
Speed: 1.0ms preprocess, 276.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdmN-k6BEfNUVH_-fPm5sA_90.JPG: 480x640 (no detections), 277.2ms
Speed: 1.0ms preprocess, 277.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdmN-k6BEfNUVH_-fPm5sA_180.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdmN-k6BEfNUVH_-fPm5sA_270.JPG: 480x640 (no detections), 273.6ms

Speed: 1.1ms preprocess, 273.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdns0i3Se2gyxEDAgeVfyA_0.JPG: 480x640 (no detections), 274.2ms
Speed: 1.1ms preprocess, 274.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdns0i3Se2gyxEDAgeVfyA_90.JPG: 480x640 (no detections), 274.6ms
Speed: 1.1ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdns0i3Se2gyxEDAgeVfyA_180.JPG: 480x640 (no detections), 275.9ms
Speed: 1.1ms preprocess, 275.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdns0i3Se2gyxEDAgeVfyA_270.JPG: 480x640 (no detections), 275.2ms
Speed: 1.6ms preprocess, 275.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdpV-UgM2ppnubbdx__4EQ_0.JPG: 480x640 (no detections), 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdpV-UgM2ppnubbdx__4EQ_90.JPG: 480x640 (no detections), 275.5ms
Speed: 1.4ms preprocess, 275.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdpV-UgM2ppnubbdx__4EQ_180.JPG: 480x640 (no detections), 274.4ms
Speed: 1.0ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdpV-UgM2ppnubbdx__4EQ_270.JPG: 480x640 (no detections), 276.8ms
Speed: 1.1ms preprocess, 276.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdsoVgalZccEQsgTcVW8kQ_0.JPG: 480x640 (no detections), 277.8ms
Speed: 1.1ms preprocess, 277.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdsoVgalZccEQsgTcVW8kQ_90.JPG: 480x640 (no detections), 279.8ms
Speed: 1.1ms preprocess, 279.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdsoVgalZccEQsgTcVW8kQ_180.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdsoVgalZccEQsgTcVW8kQ_270.JPG: 480x640 (no detections), 274.0ms
Speed: 1.2ms preprocess, 274.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdvLp80lrCpQQb-pJem8YA_0.JPG: 480x640 (no detections), 272.0ms
Speed: 1.0ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdvLp80lrCpQQb-pJem8YA_90.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdvLp80lrCpQQb-pJem8YA_180.JPG: 480x640 (no detections), 269.6ms
Speed: 1.1ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdvLp80lrCpQQb-pJem8YA_270.JPG: 480x640 (no detections), 269.3ms
Speed: 1.0ms preprocess, 269.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdvlQYEoWdY218UAR2MvIg_0.JPG: 480x640 (no detections), 277.2ms
Speed: 1.1ms preprocess, 277.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdvlQYEoWdY218UAR2MvIg_90.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdvlQYEoWdY218UAR2MvIg_180.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/d/zdvlQYEoWdY218UAR2MvIg_270.JPG: 480x640 (no detections), 275.7ms
Speed: 1.2ms preprocess, 275.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/ze-_HzAUzoUc8Ireq-38Ew_0.JPG: 480x640 (no detections), 275.1ms
Speed: 1.0ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/ze-_HzAUzoUc8Ireq-38Ew_90.JPG: 480x640 (no detections), 271.8ms
Speed: 1.2ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/ze-_HzAUzoUc8Ireq-38Ew_180.JPG: 480x640 (no detections), 270.7ms
Speed: 1.2ms preprocess, 270.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/ze-_HzAUzoUc8Ireq-38Ew_270.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/ze1Bn3f0KQE6Mn1lEdsmOg_0.JPG: 480x640 (no detections), 272.5ms
Speed: 1.0ms preprocess, 272.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/ze1Bn3f0KQE6Mn1lEdsmOg_90.JPG: 480x640 (no detections), 274.4ms
Speed: 1.0ms preprocess, 274.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/ze1Bn3f0KQE6Mn1lEdsmOg_180.JPG: 480x640 (no detections), 275.0ms
Speed: 1.0ms preprocess, 275.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/ze1Bn3f0KQE6Mn1lEdsmOg_270.JPG: 480x640 (no detections), 277.3ms
Speed: 1.6ms preprocess, 277.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/ze9mAJMI8Y8VgFsqg8Yu2g_0.JPG: 480x640 (no detections), 277.4ms
Speed: 1.1ms preprocess, 277.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/ze9mAJMI8Y8VgFsqg8Yu2g_90.JPG: 480x640 (no detections), 292.4ms
Speed: 1.2ms preprocess, 292.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/ze9mAJMI8Y8VgFsqg8Yu2g_180.JPG: 480x640 (no detections), 280.8ms
Speed: 1.3ms preprocess, 280.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/ze9mAJMI8Y8VgFsqg8Yu2g_270.JPG: 480x640 (no detections), 276.7ms
Speed: 1.3ms preprocess, 276.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeAaAzzfTPlevAN1gnPoPQ_0.JPG: 480x640 (no detections), 279.2ms
Speed: 1.1ms preprocess, 279.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeAaAzzfTPlevAN1gnPoPQ_90.JPG: 480x640 (no detections), 283.7ms
Speed: 1.1ms preprocess, 283.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeAaAzzfTPlevAN1gnPoPQ_180.JPG: 480x640 (no detections), 276.7ms
Speed: 1.3ms preprocess, 276.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeAaAzzfTPlevAN1gnPoPQ_270.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeBDFtWrsTbOIzHkRijteA_0.JPG: 480x640 (no detections), 276.6ms
Speed: 1.1ms preprocess, 276.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeBDFtWrsTbOIzHkRijteA_90.JPG: 480x640 (no detections), 272.7ms
Speed: 1.0ms preprocess, 272.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeBDFtWrsTbOIzHkRijteA_180.JPG: 480x640 (no detections), 333.7ms
Speed: 1.1ms preprocess, 333.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeBDFtWrsTbOIzHkRijteA_270.JPG: 480x640 (no detections), 283.3ms
Speed: 1.1ms preprocess, 283.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeCaY2ddLDuHMrvZNcD4tg_0.JPG: 480x640 (no detections), 296.7ms
Speed: 1.3ms preprocess, 296.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeCaY2ddLDuHMrvZNcD4tg_90.JPG: 480x640 (no detections), 351.3ms
Speed: 1.3ms preprocess, 351.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeCaY2ddLDuHMrvZNcD4tg_180.JPG: 480x640 (no detections), 311.6ms
Speed: 1.1ms preprocess, 311.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeCaY2ddLDuHMrvZNcD4tg_270.JPG: 480x640 (no detections), 274.0ms
Speed: 1.2ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeFR_YoYxRJLdVJTPML8PQ_0.JPG: 480x640 (no detections), 284.1ms
Speed: 1.3ms preprocess, 284.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeFR_YoYxRJLdVJTPML8PQ_90.JPG: 480x640 (no detections), 282.4ms
Speed: 1.0ms preprocess, 282.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeFR_YoYxRJLdVJTPML8PQ_180.JPG: 480x640 1 Waste, 280.7ms
Speed: 1.1ms preprocess, 280.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeFR_YoYxRJLdVJTPML8PQ_270.JPG: 480x640 1 Waste, 289.9ms
Speed: 1.2ms preprocess, 289.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeKYfi6QWcUgVmgum6Cf6A_0.JPG: 480x640 (no detections), 271.1ms
Speed: 1.8ms preprocess, 271.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeKYfi6QWcUgVmgum6Cf6A_90.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeKYfi6QWcUgVmgum6Cf6A_180.JPG: 480x640 (no detections), 276.6ms
Speed: 1.2ms preprocess, 276.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeKYfi6QWcUgVmgum6Cf6A_270.JPG: 480x640 (no detections), 275.4ms
Speed: 1.0ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeLkCEVqlWFP1zGNkSrAwQ_0.JPG: 480x640 (no detections), 275.8ms
Speed: 1.2ms preprocess, 275.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeLkCEVqlWFP1zGNkSrAwQ_90.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeLkCEVqlWFP1zGNkSrAwQ_180.JPG: 480x640 (no detections), 269.9ms
Speed: 1.0ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeLkCEVqlWFP1zGNkSrAwQ_270.JPG: 480x640 (no detections), 273.2ms
Speed: 1.0ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeMBljjHuOrWonaKpR7rww_0.JPG: 480x640 (no detections), 307.6ms
Speed: 1.1ms preprocess, 307.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeMBljjHuOrWonaKpR7rww_90.JPG: 480x640 (no detections), 277.4ms
Speed: 1.1ms preprocess, 277.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeMBljjHuOrWonaKpR7rww_180.JPG: 480x640 (no detections), 319.0ms
Speed: 1.1ms preprocess, 319.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeMBljjHuOrWonaKpR7rww_270.JPG: 480x640 (no detections), 303.9ms
Speed: 1.1ms preprocess, 303.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeMKGDtP935jAdlxN6bzjA_0.JPG: 480x640 (no detections), 314.0ms
Speed: 1.1ms preprocess, 314.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeMKGDtP935jAdlxN6bzjA_90.JPG: 480x640 (no detections), 280.9ms
Speed: 1.0ms preprocess, 280.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeMKGDtP935jAdlxN6bzjA_180.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeMKGDtP935jAdlxN6bzjA_270.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeUpCPP1CW8PzEssH2sT5Q_0.JPG: 480x640 (no detections), 270.4ms
Speed: 1.2ms preprocess, 270.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeUpCPP1CW8PzEssH2sT5Q_90.JPG: 480x640 (no detections), 274.5ms
Speed: 1.2ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeUpCPP1CW8PzEssH2sT5Q_180.JPG: 480x640 (no detections), 275.5ms

Speed: 1.2ms preprocess, 275.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeUpCPP1CW8PzEssH2sT5Q_270.JPG: 480x640 (no detections), 267.9ms
Speed: 1.1ms preprocess, 267.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeWkuWCFA8pZ-NI4Q17Lig_0.JPG: 480x640 (no detections), 277.9ms
Speed: 1.0ms preprocess, 277.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeWkuWCFA8pZ-NI4Q17Lig_90.JPG: 480x640 (no detections), 272.6ms
Speed: 1.0ms preprocess, 272.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeWkuWCFA8pZ-NI4Q17Lig_180.JPG: 480x640 (no detections), 273.4ms
Speed: 1.0ms preprocess, 273.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeWkuWCFA8pZ-NI4Q17Lig_270.JPG: 480x640 (no detections), 273.6ms
Speed: 1.3ms preprocess, 273.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeWnmFDAMVJtSDrF3s9kWw_0.JPG: 480x640 2 Wastes, 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeWnmFDAMVJtSDrF3s9kWw_90.JPG: 480x640 (no detections), 271.2ms
Speed: 1.0ms preprocess, 271.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeWnmFDAMVJtSDrF3s9kWw_180.JPG: 480x640 (no detections), 269.5ms
Speed: 1.1ms preprocess, 269.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeWnmFDAMVJtSDrF3s9kWw_270.JPG: 480x640 (no detections), 271.4ms
Speed: 1.0ms preprocess, 271.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeYFuubMm8p-cjvbOVScXQ_0.JPG: 480x640 (no detections), 270.3ms
Speed: 1.3ms preprocess, 270.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeYFuubMm8p-cjvbOVScXQ_90.JPG: 480x640 (no detections), 271.0ms
Speed: 1.1ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeYFuubMm8p-cjvbOVScXQ_180.JPG: 480x640 (no detections), 275.3ms
Speed: 1.1ms preprocess, 275.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeYFuubMm8p-cjvbOVScXQ_270.JPG: 480x640 (no detections), 276.5ms
Speed: 1.5ms preprocess, 276.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/ze_hgeTrQnydzA4HcHqcsA_0.JPG: 480x640 1 Waste, 276.7ms
Speed: 1.0ms preprocess, 276.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/ze_hgeTrQnydzA4HcHqcsA_90.JPG: 480x640 2 Wastes, 274.4ms
Speed: 1.1ms preprocess, 274.4ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/ze_hgeTrQnydzA4HcHqcsA_180.JPG: 480x640 (no detections), 269.4ms
Speed: 1.1ms preprocess, 269.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/ze_hgeTrQnydzA4HcHqcsA_270.JPG: 480x640 (no detections), 268.6ms
Speed: 1.1ms preprocess, 268.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeaHDe-s7ZVOy3td7LGi2w_0.JPG: 480x640 (no detections), 276.5ms
Speed: 1.0ms preprocess, 276.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeaHDe-s7ZVOy3td7LGi2w_90.JPG: 480x640 (no detections), 280.2ms
Speed: 1.2ms preprocess, 280.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeaHDe-s7ZVOy3td7LGi2w_180.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeaHDe-s7ZVOy3td7LGi2w_270.JPG: 480x640 (no detections), 273.2ms
Speed: 1.1ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeaMOPnMPNWYUng1AYuT0g_0.JPG: 480x640 (no detections), 274.2ms
Speed: 1.0ms preprocess, 274.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeaMOPnMPNWYUng1AYuT0g_90.JPG: 480x640 (no detections), 273.3ms
Speed: 1.0ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeaMOPnMPNWYUng1AYuT0g_180.JPG: 480x640 (no detections), 274.3ms
Speed: 1.1ms preprocess, 274.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeaMOPnMPNWYUng1AYuT0g_270.JPG: 480x640 (no detections), 273.1ms
Speed: 1.1ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zean7ExB_M75RaFaSR1-oQ_0.JPG: 480x640 (no detections), 274.3ms
Speed: 1.4ms preprocess, 274.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zean7ExB_M75RaFaSR1-oQ_90.JPG: 480x640 (no detections), 277.2ms
Speed: 1.3ms preprocess, 277.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zean7ExB_M75RaFaSR1-oQ_180.JPG: 480x640 1 Waste, 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zean7ExB_M75RaFaSR1-oQ_270.JPG: 480x640 (no detections), 279.4ms
Speed: 1.0ms preprocess, 279.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zebDNUNquRyA1vigPaYXXg_0.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zebDNUNquRyA1vigPaYXXg_90.JPG: 480x640 (no detections), 285.7ms
Speed: 1.4ms preprocess, 285.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zebDNUNquRyA1vigPaYXXg_180.JPG: 480x640 (no detections), 267.9ms
Speed: 1.1ms preprocess, 267.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zebDNUNquRyA1vigPaYXXg_270.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zebZRI0hj4Th-SmlYjEejg_0.JPG: 480x640 (no detections), 269.2ms
Speed: 1.0ms preprocess, 269.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zebZRI0hj4Th-SmlYjEejg_90.JPG: 480x640 (no detections), 270.9ms
Speed: 1.1ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zebZRI0hj4Th-SmlYjEejg_180.JPG: 480x640 (no detections), 270.3ms
Speed: 1.0ms preprocess, 270.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zebZRI0hj4Th-SmlYjEejg_270.JPG: 480x640 (no detections), 272.0ms
Speed: 1.0ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zec3x2JJBC9cP7IM2fM20Q_0.JPG: 480x640 (no detections), 274.8ms
Speed: 1.1ms preprocess, 274.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zec3x2JJBC9cP7IM2fM20Q_90.JPG: 480x640 (no detections), 268.4ms
Speed: 1.1ms preprocess, 268.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zec3x2JJBC9cP7IM2fM20Q_180.JPG: 480x640 (no detections), 269.3ms
Speed: 1.0ms preprocess, 269.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zec3x2JJBC9cP7IM2fM20Q_270.JPG: 480x640 (no detections), 270.1ms
Speed: 1.2ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zedGWTimZYcE76qgTVZ_DA_0.JPG: 480x640 (no detections), 277.1ms
Speed: 1.1ms preprocess, 277.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zedGWTimZYcE76qgTVZ_DA_90.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zedGWTimZYcE76qgTVZ_DA_180.JPG: 480x640 (no detections), 273.0ms
Speed: 1.0ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zedGWTimZYcE76qgTVZ_DA_270.JPG: 480x640 (no detections), 274.1ms
Speed: 1.2ms preprocess, 274.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zedU1SBU6vqmWbgTgL9MzQ_0.JPG: 480x640 (no detections), 274.2ms
Speed: 1.2ms preprocess, 274.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zedU1SBU6vqmWbgTgL9MzQ_90.JPG: 480x640 (no detections), 273.0ms
Speed: 1.3ms preprocess, 273.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zedU1SBU6vqmWbgTgL9MzQ_180.JPG: 480x640 (no detections), 271.8ms
Speed: 1.0ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zedU1SBU6vqmWbgTgL9MzQ_270.JPG: 480x640 (no detections), 272.2ms
Speed: 1.0ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeetIoY0HTEyGtVELpgOhg_0.JPG: 480x640 (no detections), 273.6ms
Speed: 1.1ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeetIoY0HTEyGtVELpgOhg_90.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeetIoY0HTEyGtVELpgOhg_180.JPG: 480x640 (no detections), 274.3ms
Speed: 1.0ms preprocess, 274.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeetIoY0HTEyGtVELpgOhg_270.JPG: 480x640 (no detections), 274.5ms
Speed: 1.1ms preprocess, 274.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeetuTQvGrG9fuVNBjVlnw_0.JPG: 480x640 (no detections), 273.4ms
Speed: 1.1ms preprocess, 273.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeetuTQvGrG9fuVNBjVlnw_90.JPG: 480x640 (no detections), 276.9ms
Speed: 1.1ms preprocess, 276.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeetuTQvGrG9fuVNBjVlnw_180.JPG: 480x640 (no detections), 274.4ms
Speed: 1.0ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeetuTQvGrG9fuVNBjVlnw_270.JPG: 480x640 (no detections), 276.7ms
Speed: 1.1ms preprocess, 276.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeh5bG5za6AiHBnX-xFfUg_0.JPG: 480x640 (no detections), 277.0ms
Speed: 1.0ms preprocess, 277.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeh5bG5za6AiHBnX-xFfUg_90.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeh5bG5za6AiHBnX-xFfUg_180.JPG: 480x640 (no detections), 271.6ms
Speed: 1.0ms preprocess, 271.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zeh5bG5za6AiHBnX-xFfUg_270.JPG: 480x640 (no detections), 276.4ms
Speed: 1.0ms preprocess, 276.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zehzAEqqJ8o5EFz53ncOEA_0.JPG: 480x640 (no detections), 275.5ms
Speed: 1.3ms preprocess, 275.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zehzAEqqJ8o5EFz53ncOEA_90.JPG: 480x640 (no detections), 276.9ms
Speed: 1.0ms preprocess, 276.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zehzAEqqJ8o5EFz53ncOEA_180.JPG: 480x640 (no detections), 269.8ms
Speed: 1.1ms preprocess, 269.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zehzAEqqJ8o5EFz53ncOEA_270.JPG: 480x640 (no detections), 270.3ms
Speed: 1.1ms preprocess, 270.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zen2VaWSoM_WAfhIkcKefA_0.JPG: 480x640 (no detections), 270.3ms
Speed: 1.0ms preprocess, 270.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zen2VaWSoM_WAfhIkcKefA_90.JPG: 480x640 (no detections), 268.4ms

Speed: 1.1ms preprocess, 268.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zen2VaWSoM_WAfhIkcKefA_180.JPG: 480x640 (no detections), 272.9ms
Speed: 1.0ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zen2VaWSoM_WAfhIkcKefA_270.JPG: 480x640 (no detections), 274.8ms
Speed: 1.1ms preprocess, 274.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zes5EtNOGgqZsQ2cgBosag_0.JPG: 480x640 (no detections), 285.9ms
Speed: 1.1ms preprocess, 285.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zes5EtNOGgqZsQ2cgBosag_90.JPG: 480x640 (no detections), 281.9ms
Speed: 1.1ms preprocess, 281.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zes5EtNOGgqZsQ2cgBosag_180.JPG: 480x640 (no detections), 313.4ms
Speed: 1.1ms preprocess, 313.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zes5EtNOGgqZsQ2cgBosag_270.JPG: 480x640 (no detections), 309.4ms
Speed: 1.3ms preprocess, 309.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zex7WhwQo7M46nQk-Wyrdg_0.JPG: 480x640 (no detections), 294.2ms
Speed: 1.2ms preprocess, 294.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zex7WhwQo7M46nQk-Wyrdg_90.JPG: 480x640 (no detections), 320.3ms
Speed: 1.1ms preprocess, 320.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zex7WhwQo7M46nQk-Wyrdg_180.JPG: 480x640 (no detections), 313.3ms
Speed: 1.2ms preprocess, 313.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/e/zex7WhwQo7M46nQk-Wyrdg_270.JPG: 480x640 (no detections), 536.6ms
Speed: 1.2ms preprocess, 536.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zf1UG82oYW4YdHeiHNWRIQ_0.JPG: 480x640 (no detections), 327.3ms
Speed: 2.6ms preprocess, 327.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zf1UG82oYW4YdHeiHNWRIQ_90.JPG: 480x640 (no detections), 334.3ms
Speed: 1.1ms preprocess, 334.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zf1UG82oYW4YdHeiHNWRIQ_180.JPG: 480x640 (no detections), 333.4ms
Speed: 1.4ms preprocess, 333.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zf1UG82oYW4YdHeiHNWRIQ_270.JPG: 480x640 (no detections), 376.7ms
Speed: 1.4ms preprocess, 376.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zf4LHRVDMAdmQa_NPUb4SA_0.JPG: 480x640 (no detections), 373.5ms
Speed: 1.2ms preprocess, 373.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zf4LHRVDMAdmQa_NPUb4SA_90.JPG: 480x640 (no detections), 365.2ms
Speed: 1.3ms preprocess, 365.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zf4LHRVDMAdmQa_NPUb4SA_180.JPG: 480x640 (no detections), 351.7ms
Speed: 1.2ms preprocess, 351.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zf4LHRVDMAdmQa_NPUb4SA_270.JPG: 480x640 (no detections), 346.4ms
Speed: 1.4ms preprocess, 346.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zf4WDun9txrY31ZTENCIBg_0.JPG: 480x640 (no detections), 315.4ms
Speed: 1.3ms preprocess, 315.4ms inference, 1.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zf4WDun9txrY31ZTENCIBg_90.JPG: 480x640 (no detections), 328.6ms
Speed: 1.2ms preprocess, 328.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zf4WDun9txrY31ZTENCIBg_180.JPG: 480x640 (no detections), 320.3ms
Speed: 1.2ms preprocess, 320.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zf4WDun9txrY31ZTENCIBg_270.JPG: 480x640 (no detections), 339.9ms
Speed: 1.3ms preprocess, 339.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zf5TMJf4DiPlevghct6CRw_0.JPG: 480x640 (no detections), 340.0ms
Speed: 7.6ms preprocess, 340.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zf5TMJf4DiPlevghct6CRw_90.JPG: 480x640 (no detections), 274.5ms
Speed: 1.2ms preprocess, 274.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zf5TMJf4DiPlevghct6CRw_180.JPG: 480x640 (no detections), 266.2ms
Speed: 1.1ms preprocess, 266.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zf5TMJf4DiPlevghct6CRw_270.JPG: 480x640 (no detections), 265.3ms
Speed: 1.1ms preprocess, 265.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zf7cwGWB4EBz2bn-HHkKcQ_0.JPG: 480x640 (no detections), 284.6ms
Speed: 1.1ms preprocess, 284.6ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zf7cwGWB4EBz2bn-HHkKcQ_90.JPG: 480x640 (no detections), 322.1ms
Speed: 1.9ms preprocess, 322.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zf7cwGWB4EBz2bn-HHkKcQ_180.JPG: 480x640 (no detections), 269.6ms
Speed: 1.2ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zf7cwGWB4EBz2bn-HHkKcQ_270.JPG: 480x640 (no detections), 269.1ms
Speed: 1.4ms preprocess, 269.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zf9_zsjz16PAX9cFJ2aU1g_0.JPG: 480x640 (no detections), 270.2ms
Speed: 1.0ms preprocess, 270.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zf9_zsjz16PAX9cFJ2aU1g_90.JPG: 480x640 (no detections), 307.4ms
Speed: 1.1ms preprocess, 307.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zf9_zsjz16PAX9cFJ2aU1g_180.JPG: 480x640 (no detections), 274.8ms
Speed: 1.1ms preprocess, 274.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zf9_zsjz16PAX9cFJ2aU1g_270.JPG: 480x640 (no detections), 374.1ms
Speed: 1.1ms preprocess, 374.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zfEgFwasFflSKl8uGFTcaA_0.JPG: 480x640 (no detections), 301.6ms
Speed: 1.4ms preprocess, 301.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zfEgFwasFflSKl8uGFTcaA_90.JPG: 480x640 (no detections), 284.2ms
Speed: 1.1ms preprocess, 284.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zfEgFwasFflSKl8uGFTcaA_180.JPG: 480x640 (no detections), 298.4ms
Speed: 1.2ms preprocess, 298.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zfEgFwasFflSKl8uGFTcaA_270.JPG: 480x640 (no detections), 368.3ms
Speed: 1.3ms preprocess, 368.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zfHPx7LwFRbl5WROzEHdjw_0.JPG: 480x640 (no detections), 358.1ms
Speed: 1.3ms preprocess, 358.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zfHPx7LwFRbl5WROzEHdjw_90.JPG: 480x640 (no detections), 355.1ms
Speed: 1.3ms preprocess, 355.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zfHPx7LwFRbl5WROzEHdjw_180.JPG: 480x640 (no detections), 361.9ms
Speed: 1.1ms preprocess, 361.9ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zfHPx7LwFRbl5WROzEHdjw_270.JPG: 480x640 (no detections), 355.5ms
Speed: 1.6ms preprocess, 355.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zfJFVV8vb_QxC9esp6Vg1w_0.JPG: 480x640 (no detections), 355.9ms
Speed: 1.1ms preprocess, 355.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zfJFVV8vb_QxC9esp6Vg1w_90.JPG: 480x640 (no detections), 362.9ms
Speed: 1.1ms preprocess, 362.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zfJFVV8vb_QxC9esp6Vg1w_180.JPG: 480x640 (no detections), 320.5ms
Speed: 1.2ms preprocess, 320.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zfJFVV8vb_QxC9esp6Vg1w_270.JPG: 480x640 (no detections), 345.3ms
Speed: 1.2ms preprocess, 345.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zfJJU40OY0SDzP2_IrfnwA_0.JPG: 480x640 (no detections), 378.5ms
Speed: 1.3ms preprocess, 378.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zfJJU40OY0SDzP2_IrfnwA_90.JPG: 480x640 (no detections), 336.3ms
Speed: 1.3ms preprocess, 336.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zfJJU40OY0SDzP2_IrfnwA_180.JPG: 480x640 (no detections), 387.9ms
Speed: 1.1ms preprocess, 387.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zfJJU40OY0SDzP2_IrfnwA_270.JPG: 480x640 (no detections), 372.3ms
Speed: 1.5ms preprocess, 372.3ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zfNBuq2dflweKEV0k8KPXg_0.JPG: 480x640 (no detections), 427.8ms
Speed: 1.4ms preprocess, 427.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zfNBuq2dflweKEV0k8KPXg_90.JPG: 480x640 (no detections), 391.6ms
Speed: 1.2ms preprocess, 391.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zfNBuq2dflweKEV0k8KPXg_180.JPG: 480x640 (no detections), 372.3ms
Speed: 1.1ms preprocess, 372.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zfNBuq2dflweKEV0k8KPXg_270.JPG: 480x640 (no detections), 288.3ms
Speed: 1.1ms preprocess, 288.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zfOOzc0UU4PpMw9Y9rKutg_0.JPG: 480x640 (no detections), 285.7ms
Speed: 1.2ms preprocess, 285.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zfOOzc0UU4PpMw9Y9rKutg_90.JPG: 480x640 (no detections), 279.4ms
Speed: 1.2ms preprocess, 279.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zfOOzc0UU4PpMw9Y9rKutg_180.JPG: 480x640 (no detections), 275.0ms
Speed: 1.1ms preprocess, 275.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zfOOzc0UU4PpMw9Y9rKutg_270.JPG: 480x640 (no detections), 282.2ms
Speed: 1.0ms preprocess, 282.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zf_tGKfLTFIK70I4CYPESQ_0.JPG: 480x640 (no detections), 280.8ms
Speed: 1.1ms preprocess, 280.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zf_tGKfLTFIK70I4CYPESQ_90.JPG: 480x640 (no detections), 285.4ms
Speed: 1.2ms preprocess, 285.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zf_tGKfLTFIK70I4CYPESQ_180.JPG: 480x640 (no detections), 285.1ms
Speed: 1.3ms preprocess, 285.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zf_tGKfLTFIK70I4CYPESQ_270.JPG: 480x640 (no detections), 280.6ms
Speed: 1.1ms preprocess, 280.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zfabZ6urkvxFrXkec5Uhpw_0.JPG: 480x640 (no detections), 336.3ms
Speed: 1.2ms preprocess, 336.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zfabZ6urkvxFrXkec5Uhpw_90.JPG: 480x640 (no detections), 285.3ms
Speed: 1.1ms preprocess, 285.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zfabZ6urkvxFrXkec5Uhpw_180.JPG: 480x640 (no detections), 302.3ms
Speed: 1.2ms preprocess, 302.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zfabZ6urkvxFrXkec5Uhpw_270.JPG: 480x640 (no detections), 275.7ms
Speed: 1.1ms preprocess, 275.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zfhxsMz3o-UZyomxvFqOfA_0.JPG: 480x640 1 Waste, 287.7ms

Speed: 1.0ms preprocess, 287.7ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zfhxsMz3o-UZyomxvFqOfA_90.JPG: 480x640 (no detections), 278.5ms
Speed: 1.1ms preprocess, 278.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zfhxsMz3o-UZyomxvFqOfA_180.JPG: 480x640 (no detections), 281.4ms
Speed: 1.0ms preprocess, 281.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zfhxsMz3o-UZyomxvFqOfA_270.JPG: 480x640 (no detections), 281.3ms
Speed: 1.1ms preprocess, 281.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zfjJrYu2PWQJ5EOn8hwDxg_0.JPG: 480x640 (no detections), 282.0ms
Speed: 1.2ms preprocess, 282.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zfjJrYu2PWQJ5EOn8hwDxg_90.JPG: 480x640 (no detections), 277.1ms
Speed: 1.0ms preprocess, 277.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zfjJrYu2PWQJ5EOn8hwDxg_180.JPG: 480x640 (no detections), 308.3ms
Speed: 1.5ms preprocess, 308.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zfjJrYu2PWQJ5EOn8hwDxg_270.JPG: 480x640 (no detections), 292.9ms
Speed: 1.2ms preprocess, 292.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zflBBymdC5KpsWPvveqBVQ_0.JPG: 480x640 (no detections), 293.2ms
Speed: 1.2ms preprocess, 293.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zflBBymdC5KpsWPvveqBVQ_90.JPG: 480x640 2 Wastes, 276.0ms
Speed: 1.1ms preprocess, 276.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zflBBymdC5KpsWPvveqBVQ_180.JPG: 480x640 (no detections), 285.7ms
Speed: 1.3ms preprocess, 285.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zflBBymdC5KpsWPvveqBVQ_270.JPG: 480x640 (no detections), 278.9ms
Speed: 1.1ms preprocess, 278.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zfp7Lgxqx8tNjOUcSr5g_Q_0.JPG: 480x640 (no detections), 276.9ms
Speed: 1.0ms preprocess, 276.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zfp7Lgxqx8tNjOUcSr5g_Q_90.JPG: 480x640 (no detections), 296.9ms
Speed: 1.2ms preprocess, 296.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zfp7Lgxqx8tNjOUcSr5g_Q_180.JPG: 480x640 (no detections), 300.8ms
Speed: 1.3ms preprocess, 300.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zfp7Lgxqx8tNjOUcSr5g_Q_270.JPG: 480x640 (no detections), 289.2ms
Speed: 1.2ms preprocess, 289.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zfr11nfSp236Xjbyj1oQKg_0.JPG: 480x640 (no detections), 289.9ms
Speed: 1.5ms preprocess, 289.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zfr11nfSp236Xjbyj1oQKg_90.JPG: 480x640 (no detections), 281.7ms
Speed: 1.2ms preprocess, 281.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zfr11nfSp236Xjbyj1oQKg_180.JPG: 480x640 (no detections), 280.1ms
Speed: 1.1ms preprocess, 280.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zfr11nfSp236Xjbyj1oQKg_270.JPG: 480x640 (no detections), 281.4ms
Speed: 1.2ms preprocess, 281.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zfrT__hrHD4KBoReN2UnDA_0.JPG: 480x640 (no detections), 282.1ms
Speed: 1.5ms preprocess, 282.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zfrT__hrHD4KBoReN2UnDA_90.JPG: 480x640 (no detections), 278.6ms
Speed: 1.1ms preprocess, 278.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zfrT__hrHD4KBoReN2UnDA_180.JPG: 480x640 (no detections), 282.3ms
Speed: 1.0ms preprocess, 282.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/f/zfrT__hrHD4KBoReN2UnDA_270.JPG: 480x640 (no detections), 284.1ms
Speed: 1.1ms preprocess, 284.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zg0tOKxLe0tCI7k7SZwzHA_0.JPG: 480x640 (no detections), 280.1ms
Speed: 1.3ms preprocess, 280.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zg0tOKxLe0tCI7k7SZwzHA_90.JPG: 480x640 (no detections), 283.2ms
Speed: 1.3ms preprocess, 283.2ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zg0tOKxLe0tCI7k7SZwzHA_180.JPG: 480x640 (no detections), 284.0ms
Speed: 1.1ms preprocess, 284.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zg0tOKxLe0tCI7k7SZwzHA_270.JPG: 480x640 (no detections), 280.6ms
Speed: 1.0ms preprocess, 280.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zg1M9hjsF2EbJl1mU4P9Pw_0.JPG: 480x640 (no detections), 279.1ms
Speed: 1.2ms preprocess, 279.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zg1M9hjsF2EbJl1mU4P9Pw_90.JPG: 480x640 (no detections), 284.2ms
Speed: 1.1ms preprocess, 284.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zg1M9hjsF2EbJl1mU4P9Pw_180.JPG: 480x640 (no detections), 281.9ms
Speed: 1.1ms preprocess, 281.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zg1M9hjsF2EbJl1mU4P9Pw_270.JPG: 480x640 (no detections), 283.0ms
Speed: 1.1ms preprocess, 283.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zg21RwXNF_G8qaxEzp4mcQ_0.JPG: 480x640 (no detections), 283.2ms
Speed: 1.2ms preprocess, 283.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zg21RwXNF_G8qaxEzp4mcQ_90.JPG: 480x640 (no detections), 277.6ms
Speed: 1.0ms preprocess, 277.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zg21RwXNF_G8qaxEzp4mcQ_180.JPG: 480x640 (no detections), 280.1ms
Speed: 1.0ms preprocess, 280.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zg21RwXNF_G8qaxEzp4mcQ_270.JPG: 480x640 (no detections), 277.2ms
Speed: 1.0ms preprocess, 277.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zg3tTGUCyTXgArroXEUZPg_0.JPG: 480x640 (no detections), 274.2ms
Speed: 1.0ms preprocess, 274.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zg3tTGUCyTXgArroXEUZPg_90.JPG: 480x640 (no detections), 286.0ms
Speed: 1.1ms preprocess, 286.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zg3tTGUCyTXgArroXEUZPg_180.JPG: 480x640 (no detections), 277.4ms
Speed: 1.2ms preprocess, 277.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zg3tTGUCyTXgArroXEUZPg_270.JPG: 480x640 (no detections), 282.1ms
Speed: 1.1ms preprocess, 282.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zg7RkIfXFtOZ0B6UfPdKpg_0.JPG: 480x640 (no detections), 285.8ms
Speed: 1.3ms preprocess, 285.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zg7RkIfXFtOZ0B6UfPdKpg_90.JPG: 480x640 (no detections), 283.4ms
Speed: 1.2ms preprocess, 283.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zg7RkIfXFtOZ0B6UfPdKpg_180.JPG: 480x640 (no detections), 281.1ms
Speed: 1.0ms preprocess, 281.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zg7RkIfXFtOZ0B6UfPdKpg_270.JPG: 480x640 (no detections), 280.0ms
Speed: 1.2ms preprocess, 280.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgABIma4ElsqPPuCbLwKyw_0.JPG: 480x640 (no detections), 280.7ms
Speed: 1.1ms preprocess, 280.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgABIma4ElsqPPuCbLwKyw_90.JPG: 480x640 (no detections), 281.1ms
Speed: 1.2ms preprocess, 281.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgABIma4ElsqPPuCbLwKyw_180.JPG: 480x640 (no detections), 280.7ms
Speed: 1.1ms preprocess, 280.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgABIma4ElsqPPuCbLwKyw_270.JPG: 480x640 (no detections), 277.5ms
Speed: 1.1ms preprocess, 277.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgFh72z17RmX48IT6HJ0WA_0.JPG: 480x640 (no detections), 282.6ms
Speed: 1.1ms preprocess, 282.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgFh72z17RmX48IT6HJ0WA_90.JPG: 480x640 (no detections), 282.7ms
Speed: 1.2ms preprocess, 282.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgFh72z17RmX48IT6HJ0WA_180.JPG: 480x640 (no detections), 277.6ms
Speed: 1.2ms preprocess, 277.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgFh72z17RmX48IT6HJ0WA_270.JPG: 480x640 (no detections), 274.4ms
Speed: 1.0ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgGzPDR6knys0YGD_uQF3w_0.JPG: 480x640 (no detections), 281.8ms
Speed: 1.2ms preprocess, 281.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgGzPDR6knys0YGD_uQF3w_90.JPG: 480x640 (no detections), 280.0ms
Speed: 1.1ms preprocess, 280.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgGzPDR6knys0YGD_uQF3w_180.JPG: 480x640 (no detections), 282.0ms
Speed: 1.2ms preprocess, 282.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgGzPDR6knys0YGD_uQF3w_270.JPG: 480x640 (no detections), 283.0ms
Speed: 1.0ms preprocess, 283.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgN_fTD_kibQS0xRU3zh6g_0.JPG: 480x640 (no detections), 279.6ms
Speed: 1.2ms preprocess, 279.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgN_fTD_kibQS0xRU3zh6g_90.JPG: 480x640 (no detections), 276.2ms
Speed: 1.1ms preprocess, 276.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgN_fTD_kibQS0xRU3zh6g_180.JPG: 480x640 (no detections), 276.7ms
Speed: 1.0ms preprocess, 276.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgN_fTD_kibQS0xRU3zh6g_270.JPG: 480x640 (no detections), 282.8ms
Speed: 1.0ms preprocess, 282.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgQCJtg7ZXiayuckn7I9-g_0.JPG: 480x640 (no detections), 282.0ms
Speed: 1.1ms preprocess, 282.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgQCJtg7ZXiayuckn7I9-g_90.JPG: 480x640 (no detections), 277.1ms
Speed: 1.2ms preprocess, 277.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgQCJtg7ZXiayuckn7I9-g_180.JPG: 480x640 (no detections), 277.0ms
Speed: 1.2ms preprocess, 277.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgQCJtg7ZXiayuckn7I9-g_270.JPG: 480x640 (no detections), 280.7ms
Speed: 1.1ms preprocess, 280.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgR5jC7E7C5zamyH7IkN-g_0.JPG: 480x640 (no detections), 282.4ms
Speed: 1.1ms preprocess, 282.4ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgR5jC7E7C5zamyH7IkN-g_90.JPG: 480x640 1 Waste, 283.9ms
Speed: 1.1ms preprocess, 283.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgR5jC7E7C5zamyH7IkN-g_180.JPG: 480x640 (no detections), 284.8ms
Speed: 1.1ms preprocess, 284.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgR5jC7E7C5zamyH7IkN-g_270.JPG: 480x640 (no detections), 277.7ms

Speed: 1.1ms preprocess, 277.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgWJaFZ_q5TQK92ren6spw_0.JPG: 480x640 (no detections), 276.3ms
Speed: 1.1ms preprocess, 276.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgWJaFZ_q5TQK92ren6spw_90.JPG: 480x640 (no detections), 277.1ms
Speed: 1.0ms preprocess, 277.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgWJaFZ_q5TQK92ren6spw_180.JPG: 480x640 (no detections), 275.9ms
Speed: 1.0ms preprocess, 275.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgWJaFZ_q5TQK92ren6spw_270.JPG: 480x640 (no detections), 277.2ms
Speed: 1.0ms preprocess, 277.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgWM-VmIlHadzr2RmMBM7g_0.JPG: 480x640 (no detections), 276.8ms
Speed: 1.1ms preprocess, 276.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgWM-VmIlHadzr2RmMBM7g_90.JPG: 480x640 (no detections), 281.2ms
Speed: 1.1ms preprocess, 281.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgWM-VmIlHadzr2RmMBM7g_180.JPG: 480x640 (no detections), 279.1ms
Speed: 1.1ms preprocess, 279.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgWM-VmIlHadzr2RmMBM7g_270.JPG: 480x640 (no detections), 278.4ms
Speed: 1.2ms preprocess, 278.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgYhwFhaytpbPfLIFAR2Yg_0.JPG: 480x640 (no detections), 276.3ms
Speed: 1.1ms preprocess, 276.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgYhwFhaytpbPfLIFAR2Yg_90.JPG: 480x640 (no detections), 275.7ms
Speed: 1.1ms preprocess, 275.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgYhwFhaytpbPfLIFAR2Yg_180.JPG: 480x640 (no detections), 280.7ms
Speed: 1.0ms preprocess, 280.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgYhwFhaytpbPfLIFAR2Yg_270.JPG: 480x640 (no detections), 277.4ms
Speed: 1.1ms preprocess, 277.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgZ2RgDlzmTVcr-gZKh2OA_0.JPG: 480x640 (no detections), 276.8ms
Speed: 1.1ms preprocess, 276.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgZ2RgDlzmTVcr-gZKh2OA_90.JPG: 480x640 (no detections), 280.6ms
Speed: 1.0ms preprocess, 280.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgZ2RgDlzmTVcr-gZKh2OA_180.JPG: 480x640 (no detections), 280.4ms
Speed: 1.2ms preprocess, 280.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgZ2RgDlzmTVcr-gZKh2OA_270.JPG: 480x640 (no detections), 334.7ms
Speed: 1.0ms preprocess, 334.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgZMPjbXFvnLJz4ALKpj7w_0.JPG: 480x640 (no detections), 281.0ms
Speed: 1.3ms preprocess, 281.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgZMPjbXFvnLJz4ALKpj7w_90.JPG: 480x640 (no detections), 277.9ms
Speed: 1.1ms preprocess, 277.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgZMPjbXFvnLJz4ALKpj7w_180.JPG: 480x640 (no detections), 280.5ms
Speed: 1.1ms preprocess, 280.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgZMPjbXFvnLJz4ALKpj7w_270.JPG: 480x640 (no detections), 278.7ms
Speed: 1.2ms preprocess, 278.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgZR6CdpwFppEDJe7nWGew_0.JPG: 480x640 1 Waste, 276.4ms
Speed: 1.1ms preprocess, 276.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgZR6CdpwFppEDJe7nWGew_90.JPG: 480x640 (no detections), 275.3ms
Speed: 1.1ms preprocess, 275.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgZR6CdpwFppEDJe7nWGew_180.JPG: 480x640 (no detections), 280.0ms
Speed: 1.1ms preprocess, 280.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgZR6CdpwFppEDJe7nWGew_270.JPG: 480x640 (no detections), 274.9ms
Speed: 1.1ms preprocess, 274.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgeLzmtbYk7qYA6E_95x0g_0.JPG: 480x640 (no detections), 277.1ms
Speed: 1.1ms preprocess, 277.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgeLzmtbYk7qYA6E_95x0g_90.JPG: 480x640 (no detections), 278.5ms
Speed: 1.0ms preprocess, 278.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgeLzmtbYk7qYA6E_95x0g_180.JPG: 480x640 (no detections), 274.4ms
Speed: 1.0ms preprocess, 274.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgeLzmtbYk7qYA6E_95x0g_270.JPG: 480x640 (no detections), 277.3ms
Speed: 1.1ms preprocess, 277.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgeyIu-12Xwh_L9VvuOB5A_0.JPG: 480x640 (no detections), 280.6ms
Speed: 1.2ms preprocess, 280.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgeyIu-12Xwh_L9VvuOB5A_90.JPG: 480x640 (no detections), 281.8ms
Speed: 1.2ms preprocess, 281.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgeyIu-12Xwh_L9VvuOB5A_180.JPG: 480x640 (no detections), 280.7ms
Speed: 1.3ms preprocess, 280.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgeyIu-12Xwh_L9VvuOB5A_270.JPG: 480x640 (no detections), 285.0ms
Speed: 1.1ms preprocess, 285.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zglYGxlOphj1gCYeg4MaJw_0.JPG: 480x640 (no detections), 280.7ms
Speed: 1.4ms preprocess, 280.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zglYGxlOphj1gCYeg4MaJw_90.JPG: 480x640 (no detections), 292.3ms
Speed: 1.1ms preprocess, 292.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zglYGxlOphj1gCYeg4MaJw_180.JPG: 480x640 (no detections), 287.6ms
Speed: 1.6ms preprocess, 287.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zglYGxlOphj1gCYeg4MaJw_270.JPG: 480x640 (no detections), 287.3ms
Speed: 1.3ms preprocess, 287.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgroJF15LzQsOVW-kRkC6A_0.JPG: 480x640 (no detections), 289.7ms
Speed: 1.1ms preprocess, 289.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgroJF15LzQsOVW-kRkC6A_90.JPG: 480x640 (no detections), 277.2ms
Speed: 1.1ms preprocess, 277.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgroJF15LzQsOVW-kRkC6A_180.JPG: 480x640 (no detections), 277.9ms
Speed: 1.2ms preprocess, 277.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgroJF15LzQsOVW-kRkC6A_270.JPG: 480x640 (no detections), 273.2ms
Speed: 1.1ms preprocess, 273.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgrsEyaAZ0Ir5CNKDbOTuA_0.JPG: 480x640 (no detections), 284.9ms
Speed: 1.2ms preprocess, 284.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgrsEyaAZ0Ir5CNKDbOTuA_90.JPG: 480x640 (no detections), 279.2ms
Speed: 1.1ms preprocess, 279.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgrsEyaAZ0Ir5CNKDbOTuA_180.JPG: 480x640 1 Waste, 277.9ms
Speed: 1.1ms preprocess, 277.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/g/zgrsEyaAZ0Ir5CNKDbOTuA_270.JPG: 480x640 1 Waste, 275.1ms
Speed: 1.2ms preprocess, 275.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zh3mOOhS6JjTsNRgf_cypg_0.JPG: 480x640 (no detections), 280.4ms
Speed: 1.0ms preprocess, 280.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zh3mOOhS6JjTsNRgf_cypg_90.JPG: 480x640 (no detections), 286.7ms
Speed: 1.1ms preprocess, 286.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zh3mOOhS6JjTsNRgf_cypg_180.JPG: 480x640 (no detections), 280.5ms
Speed: 1.1ms preprocess, 280.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zh3mOOhS6JjTsNRgf_cypg_270.JPG: 480x640 (no detections), 292.1ms
Speed: 1.0ms preprocess, 292.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zh9NJkx4IH7XQZ1ePgb6aw_0.JPG: 480x640 (no detections), 291.8ms
Speed: 1.5ms preprocess, 291.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zh9NJkx4IH7XQZ1ePgb6aw_90.JPG: 480x640 (no detections), 290.5ms
Speed: 1.3ms preprocess, 290.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zh9NJkx4IH7XQZ1ePgb6aw_180.JPG: 480x640 (no detections), 383.3ms
Speed: 1.2ms preprocess, 383.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zh9NJkx4IH7XQZ1ePgb6aw_270.JPG: 480x640 (no detections), 325.1ms
Speed: 1.3ms preprocess, 325.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhN-7l9Ak-pgNpPgWt0eJg_0.JPG: 480x640 (no detections), 311.1ms
Speed: 1.1ms preprocess, 311.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhN-7l9Ak-pgNpPgWt0eJg_90.JPG: 480x640 (no detections), 284.8ms
Speed: 1.4ms preprocess, 284.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhN-7l9Ak-pgNpPgWt0eJg_180.JPG: 480x640 (no detections), 274.9ms
Speed: 1.0ms preprocess, 274.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhN-7l9Ak-pgNpPgWt0eJg_270.JPG: 480x640 1 Waste, 281.5ms
Speed: 1.2ms preprocess, 281.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhSKi9VGDslH-LVaMtbVFQ_0.JPG: 480x640 (no detections), 281.2ms
Speed: 1.0ms preprocess, 281.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhSKi9VGDslH-LVaMtbVFQ_90.JPG: 480x640 (no detections), 288.7ms
Speed: 1.1ms preprocess, 288.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhSKi9VGDslH-LVaMtbVFQ_180.JPG: 480x640 (no detections), 283.8ms
Speed: 1.4ms preprocess, 283.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhSKi9VGDslH-LVaMtbVFQ_270.JPG: 480x640 (no detections), 279.0ms
Speed: 1.1ms preprocess, 279.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhbPNQNRBxeTplRv9Zt3JA_0.JPG: 480x640 (no detections), 275.1ms
Speed: 1.0ms preprocess, 275.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhbPNQNRBxeTplRv9Zt3JA_90.JPG: 480x640 (no detections), 280.8ms
Speed: 1.2ms preprocess, 280.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhbPNQNRBxeTplRv9Zt3JA_180.JPG: 480x640 (no detections), 287.3ms
Speed: 1.1ms preprocess, 287.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhbPNQNRBxeTplRv9Zt3JA_270.JPG: 480x640 (no detections), 283.0ms
Speed: 1.1ms preprocess, 283.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhfhC4-bWpzvtql80CEVnA_0.JPG: 480x640 (no detections), 283.7ms
Speed: 1.2ms preprocess, 283.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhfhC4-bWpzvtql80CEVnA_90.JPG: 480x640 (no detections), 283.0ms
Speed: 1.1ms preprocess, 283.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhfhC4-bWpzvtql80CEVnA_180.JPG: 480x640 (no detections), 280.4ms

Speed: 1.1ms preprocess, 280.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhfhC4-bWpzvtql80CEVnA_270.JPG: 480x640 (no detections), 279.7ms
Speed: 1.1ms preprocess, 279.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhflyVc5oPzwgIWJuzXsxQ_0.JPG: 480x640 (no detections), 281.1ms
Speed: 1.0ms preprocess, 281.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhflyVc5oPzwgIWJuzXsxQ_90.JPG: 480x640 (no detections), 276.9ms
Speed: 1.0ms preprocess, 276.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhflyVc5oPzwgIWJuzXsxQ_180.JPG: 480x640 (no detections), 295.3ms
Speed: 1.6ms preprocess, 295.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhflyVc5oPzwgIWJuzXsxQ_270.JPG: 480x640 (no detections), 283.4ms
Speed: 1.1ms preprocess, 283.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhjbxH2iOJUom-MJXQmz-w_0.JPG: 480x640 (no detections), 276.9ms
Speed: 1.5ms preprocess, 276.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhjbxH2iOJUom-MJXQmz-w_90.JPG: 480x640 (no detections), 276.5ms
Speed: 1.1ms preprocess, 276.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhjbxH2iOJUom-MJXQmz-w_180.JPG: 480x640 (no detections), 290.8ms
Speed: 1.2ms preprocess, 290.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhjbxH2iOJUom-MJXQmz-w_270.JPG: 480x640 (no detections), 276.2ms
Speed: 1.1ms preprocess, 276.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhp0kP1-3SU9Spsn_iPQQQ_0.JPG: 480x640 (no detections), 289.7ms
Speed: 1.2ms preprocess, 289.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhp0kP1-3SU9Spsn_iPQQQ_90.JPG: 480x640 (no detections), 278.9ms
Speed: 1.3ms preprocess, 278.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhp0kP1-3SU9Spsn_iPQQQ_180.JPG: 480x640 (no detections), 277.2ms
Speed: 1.1ms preprocess, 277.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhp0kP1-3SU9Spsn_iPQQQ_270.JPG: 480x640 (no detections), 275.4ms
Speed: 1.1ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhpnSxtnRi_ypkIY_8q5Lg_0.JPG: 480x640 1 Waste, 274.2ms
Speed: 1.1ms preprocess, 274.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhpnSxtnRi_ypkIY_8q5Lg_90.JPG: 480x640 1 Waste, 278.9ms
Speed: 1.6ms preprocess, 278.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhpnSxtnRi_ypkIY_8q5Lg_180.JPG: 480x640 (no detections), 275.3ms
Speed: 1.1ms preprocess, 275.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhpnSxtnRi_ypkIY_8q5Lg_270.JPG: 480x640 (no detections), 278.3ms
Speed: 1.1ms preprocess, 278.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhrPYDY92XIK_oyQNfi-5g_0.JPG: 480x640 (no detections), 275.3ms
Speed: 1.1ms preprocess, 275.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhrPYDY92XIK_oyQNfi-5g_90.JPG: 480x640 (no detections), 280.6ms
Speed: 1.0ms preprocess, 280.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhrPYDY92XIK_oyQNfi-5g_180.JPG: 480x640 (no detections), 277.4ms
Speed: 1.0ms preprocess, 277.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhrPYDY92XIK_oyQNfi-5g_270.JPG: 480x640 (no detections), 281.3ms
Speed: 1.2ms preprocess, 281.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhu1iEn1pJMIgHqwV6G74A_0.JPG: 480x640 (no detections), 278.4ms
Speed: 1.1ms preprocess, 278.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhu1iEn1pJMIgHqwV6G74A_90.JPG: 480x640 (no detections), 279.0ms
Speed: 1.0ms preprocess, 279.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhu1iEn1pJMIgHqwV6G74A_180.JPG: 480x640 (no detections), 281.2ms
Speed: 1.1ms preprocess, 281.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhu1iEn1pJMIgHqwV6G74A_270.JPG: 480x640 (no detections), 280.5ms
Speed: 1.3ms preprocess, 280.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhuGwr0BkxvO7kzHMoJY4w_0.JPG: 480x640 (no detections), 280.4ms
Speed: 1.1ms preprocess, 280.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhuGwr0BkxvO7kzHMoJY4w_90.JPG: 480x640 (no detections), 281.8ms
Speed: 1.1ms preprocess, 281.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhuGwr0BkxvO7kzHMoJY4w_180.JPG: 480x640 (no detections), 277.2ms
Speed: 1.1ms preprocess, 277.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhuGwr0BkxvO7kzHMoJY4w_270.JPG: 480x640 (no detections), 276.9ms
Speed: 1.1ms preprocess, 276.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhwH9QwFVLViJ2U6irnhRw_0.JPG: 480x640 (no detections), 330.6ms
Speed: 1.1ms preprocess, 330.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhwH9QwFVLViJ2U6irnhRw_90.JPG: 480x640 (no detections), 309.1ms
Speed: 1.1ms preprocess, 309.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhwH9QwFVLViJ2U6irnhRw_180.JPG: 480x640 (no detections), 287.8ms
Speed: 1.2ms preprocess, 287.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhwH9QwFVLViJ2U6irnhRw_270.JPG: 480x640 (no detections), 296.2ms
Speed: 1.3ms preprocess, 296.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhwbfljriBNAn_sgAuQ8CQ_0.JPG: 480x640 (no detections), 279.4ms
Speed: 1.1ms preprocess, 279.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhwbfljriBNAn_sgAuQ8CQ_90.JPG: 480x640 (no detections), 282.2ms
Speed: 1.1ms preprocess, 282.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhwbfljriBNAn_sgAuQ8CQ_180.JPG: 480x640 (no detections), 286.3ms
Speed: 1.4ms preprocess, 286.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhwbfljriBNAn_sgAuQ8CQ_270.JPG: 480x640 (no detections), 287.3ms
Speed: 1.2ms preprocess, 287.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhybTdjyN8VtGVTr5XCzeg_0.JPG: 480x640 (no detections), 281.2ms
Speed: 1.1ms preprocess, 281.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhybTdjyN8VtGVTr5XCzeg_90.JPG: 480x640 (no detections), 285.3ms
Speed: 1.0ms preprocess, 285.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhybTdjyN8VtGVTr5XCzeg_180.JPG: 480x640 (no detections), 282.0ms
Speed: 1.2ms preprocess, 282.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/H/zhybTdjyN8VtGVTr5XCzeg_270.JPG: 480x640 (no detections), 278.2ms
Speed: 1.0ms preprocess, 278.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zi-eLG9kKcuLP09YWTK1Zg_0.JPG: 480x640 (no detections), 277.8ms
Speed: 1.2ms preprocess, 277.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zi-eLG9kKcuLP09YWTK1Zg_90.JPG: 480x640 (no detections), 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zi-eLG9kKcuLP09YWTK1Zg_180.JPG: 480x640 (no detections), 292.3ms
Speed: 1.1ms preprocess, 292.3ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zi-eLG9kKcuLP09YWTK1Zg_270.JPG: 480x640 (no detections), 327.3ms
Speed: 1.3ms preprocess, 327.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zi-eyabWc-20tLYi2B3pHw_0.JPG: 480x640 (no detections), 281.6ms
Speed: 1.1ms preprocess, 281.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zi-eyabWc-20tLYi2B3pHw_90.JPG: 480x640 (no detections), 294.6ms
Speed: 1.0ms preprocess, 294.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zi-eyabWc-20tLYi2B3pHw_180.JPG: 480x640 (no detections), 289.8ms
Speed: 1.2ms preprocess, 289.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zi-eyabWc-20tLYi2B3pHw_270.JPG: 480x640 (no detections), 290.3ms
Speed: 1.5ms preprocess, 290.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zi0eMXdgu8lvMtE8cfS-2A_0.JPG: 480x640 (no detections), 284.6ms
Speed: 1.2ms preprocess, 284.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zi0eMXdgu8lvMtE8cfS-2A_90.JPG: 480x640 (no detections), 275.7ms
Speed: 1.1ms preprocess, 275.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zi0eMXdgu8lvMtE8cfS-2A_180.JPG: 480x640 (no detections), 320.8ms
Speed: 1.0ms preprocess, 320.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zi0eMXdgu8lvMtE8cfS-2A_270.JPG: 480x640 (no detections), 280.4ms
Speed: 1.1ms preprocess, 280.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zi3dsCnP3T_oIAh6xuBkKQ_0.JPG: 480x640 (no detections), 280.1ms
Speed: 1.0ms preprocess, 280.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zi3dsCnP3T_oIAh6xuBkKQ_90.JPG: 480x640 (no detections), 279.5ms
Speed: 1.1ms preprocess, 279.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zi3dsCnP3T_oIAh6xuBkKQ_180.JPG: 480x640 (no detections), 276.0ms
Speed: 1.4ms preprocess, 276.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zi3dsCnP3T_oIAh6xuBkKQ_270.JPG: 480x640 (no detections), 280.3ms
Speed: 1.1ms preprocess, 280.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zi42Uo6yzPYsvQfFLx8sFA_0.JPG: 480x640 (no detections), 281.5ms
Speed: 1.2ms preprocess, 281.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zi42Uo6yzPYsvQfFLx8sFA_90.JPG: 480x640 (no detections), 278.3ms
Speed: 1.1ms preprocess, 278.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zi42Uo6yzPYsvQfFLx8sFA_180.JPG: 480x640 (no detections), 279.5ms
Speed: 1.1ms preprocess, 279.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zi42Uo6yzPYsvQfFLx8sFA_270.JPG: 480x640 (no detections), 277.0ms
Speed: 1.0ms preprocess, 277.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zi4iahDuj2zI68tRJVZytQ_0.JPG: 480x640 (no detections), 273.5ms
Speed: 1.2ms preprocess, 273.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zi4iahDuj2zI68tRJVZytQ_90.JPG: 480x640 (no detections), 277.6ms
Speed: 1.4ms preprocess, 277.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zi4iahDuj2zI68tRJVZytQ_180.JPG: 480x640 (no detections), 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zi4iahDuj2zI68tRJVZytQ_270.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zi4qGB0hbzVvVuno7BY_RQ_0.JPG: 480x640 (no detections), 274.1ms
Speed: 1.0ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zi4qGB0hbzVvVuno7BY_RQ_90.JPG: 480x640 (no detections), 269.1ms

Speed: 1.1ms preprocess, 269.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zi4qGB0hbzVvVuno7BY_RQ_180.JPG: 480x640 1 Waste, 273.1ms
Speed: 1.1ms preprocess, 273.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zi4qGB0hbzVvVuno7BY_RQ_270.JPG: 480x640 (no detections), 326.0ms
Speed: 1.1ms preprocess, 326.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziATIz_XUs2rIS4xLZBxew_0.JPG: 480x640 (no detections), 305.4ms
Speed: 1.1ms preprocess, 305.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziATIz_XUs2rIS4xLZBxew_90.JPG: 480x640 (no detections), 285.7ms
Speed: 1.2ms preprocess, 285.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziATIz_XUs2rIS4xLZBxew_180.JPG: 480x640 1 Waste, 274.3ms
Speed: 1.1ms preprocess, 274.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziATIz_XUs2rIS4xLZBxew_270.JPG: 480x640 1 Waste, 296.0ms
Speed: 1.2ms preprocess, 296.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziAdE3OlEM1jnDvspjlNKw_0.JPG: 480x640 (no detections), 306.8ms
Speed: 1.1ms preprocess, 306.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziAdE3OlEM1jnDvspjlNKw_90.JPG: 480x640 (no detections), 306.9ms
Speed: 1.8ms preprocess, 306.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziAdE3OlEM1jnDvspjlNKw_180.JPG: 480x640 (no detections), 307.3ms
Speed: 1.2ms preprocess, 307.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziAdE3OlEM1jnDvspjlNKw_270.JPG: 480x640 (no detections), 288.7ms
Speed: 1.1ms preprocess, 288.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziB-SS32ywkC51PXbWyEeQ_0.JPG: 480x640 1 Waste, 338.2ms
Speed: 1.1ms preprocess, 338.2ms inference, 3.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziB-SS32ywkC51PXbWyEeQ_90.JPG: 480x640 (no detections), 358.3ms
Speed: 1.2ms preprocess, 358.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziB-SS32ywkC51PXbWyEeQ_180.JPG: 480x640 (no detections), 355.7ms
Speed: 1.4ms preprocess, 355.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziB-SS32ywkC51PXbWyEeQ_270.JPG: 480x640 (no detections), 287.4ms
Speed: 1.3ms preprocess, 287.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziChOlgctFqlZTfdT3qXtg_0.JPG: 480x640 (no detections), 336.6ms
Speed: 1.4ms preprocess, 336.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziChOlgctFqlZTfdT3qXtg_90.JPG: 480x640 (no detections), 300.4ms
Speed: 1.4ms preprocess, 300.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziChOlgctFqlZTfdT3qXtg_180.JPG: 480x640 (no detections), 330.3ms
Speed: 1.4ms preprocess, 330.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziChOlgctFqlZTfdT3qXtg_270.JPG: 480x640 (no detections), 346.4ms
Speed: 1.3ms preprocess, 346.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziCzLV6ZhV90kj4CB106KA_0.JPG: 480x640 (no detections), 309.9ms
Speed: 1.1ms preprocess, 309.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziCzLV6ZhV90kj4CB106KA_90.JPG: 480x640 (no detections), 352.9ms
Speed: 1.1ms preprocess, 352.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziCzLV6ZhV90kj4CB106KA_180.JPG: 480x640 (no detections), 281.8ms
Speed: 1.2ms preprocess, 281.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziCzLV6ZhV90kj4CB106KA_270.JPG: 480x640 (no detections), 277.3ms
Speed: 1.0ms preprocess, 277.3ms inference, 4.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziIvEMEsa18vM0SzdCjYYQ_0.JPG: 480x640 (no detections), 301.4ms
Speed: 1.2ms preprocess, 301.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziIvEMEsa18vM0SzdCjYYQ_90.JPG: 480x640 (no detections), 288.4ms
Speed: 1.3ms preprocess, 288.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziIvEMEsa18vM0SzdCjYYQ_180.JPG: 480x640 (no detections), 311.1ms
Speed: 1.3ms preprocess, 311.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziIvEMEsa18vM0SzdCjYYQ_270.JPG: 480x640 (no detections), 296.1ms
Speed: 1.1ms preprocess, 296.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziJVWnTh3j6ITRayC1OSnA_0.JPG: 480x640 (no detections), 323.9ms
Speed: 1.2ms preprocess, 323.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziJVWnTh3j6ITRayC1OSnA_90.JPG: 480x640 1 Waste, 278.6ms
Speed: 1.3ms preprocess, 278.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziJVWnTh3j6ITRayC1OSnA_180.JPG: 480x640 (no detections), 281.2ms
Speed: 1.0ms preprocess, 281.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziJVWnTh3j6ITRayC1OSnA_270.JPG: 480x640 (no detections), 270.8ms
Speed: 1.0ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziKnBkTxHc7o1-VUDTlCkQ_0.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziKnBkTxHc7o1-VUDTlCkQ_90.JPG: 480x640 (no detections), 296.4ms
Speed: 1.3ms preprocess, 296.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziKnBkTxHc7o1-VUDTlCkQ_180.JPG: 480x640 (no detections), 278.6ms
Speed: 1.4ms preprocess, 278.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziKnBkTxHc7o1-VUDTlCkQ_270.JPG: 480x640 (no detections), 275.5ms
Speed: 1.1ms preprocess, 275.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziMYAfwlPT7CWrm4Scwv3Q_0.JPG: 480x640 (no detections), 269.8ms
Speed: 1.0ms preprocess, 269.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziMYAfwlPT7CWrm4Scwv3Q_90.JPG: 480x640 (no detections), 279.7ms
Speed: 1.2ms preprocess, 279.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziMYAfwlPT7CWrm4Scwv3Q_180.JPG: 480x640 (no detections), 289.9ms
Speed: 1.6ms preprocess, 289.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziMYAfwlPT7CWrm4Scwv3Q_270.JPG: 480x640 (no detections), 276.5ms
Speed: 1.0ms preprocess, 276.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziN_ojPEIScvCkhgjDVDnQ_0.JPG: 480x640 (no detections), 278.3ms
Speed: 1.2ms preprocess, 278.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziN_ojPEIScvCkhgjDVDnQ_90.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziN_ojPEIScvCkhgjDVDnQ_180.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziN_ojPEIScvCkhgjDVDnQ_270.JPG: 480x640 (no detections), 272.5ms
Speed: 1.0ms preprocess, 272.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziPHxjjxe8YtydA_azezgA_0.JPG: 480x640 (no detections), 274.2ms
Speed: 1.0ms preprocess, 274.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziPHxjjxe8YtydA_azezgA_90.JPG: 480x640 (no detections), 270.4ms
Speed: 1.0ms preprocess, 270.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziPHxjjxe8YtydA_azezgA_180.JPG: 480x640 1 Waste, 272.6ms
Speed: 1.0ms preprocess, 272.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziPHxjjxe8YtydA_azezgA_270.JPG: 480x640 (no detections), 292.2ms
Speed: 1.1ms preprocess, 292.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziRzMRa97vpz2cQjJsCOMg_0.JPG: 480x640 2 Wastes, 278.5ms
Speed: 1.0ms preprocess, 278.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziRzMRa97vpz2cQjJsCOMg_90.JPG: 480x640 1 Waste, 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziRzMRa97vpz2cQjJsCOMg_180.JPG: 480x640 (no detections), 278.7ms
Speed: 1.0ms preprocess, 278.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziRzMRa97vpz2cQjJsCOMg_270.JPG: 480x640 1 Waste, 283.7ms
Speed: 1.2ms preprocess, 283.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziUjar-ff-QoyvvsHn8lmQ_0.JPG: 480x640 (no detections), 287.0ms
Speed: 1.1ms preprocess, 287.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziUjar-ff-QoyvvsHn8lmQ_90.JPG: 480x640 (no detections), 301.6ms
Speed: 1.2ms preprocess, 301.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziUjar-ff-QoyvvsHn8lmQ_180.JPG: 480x640 (no detections), 279.7ms
Speed: 1.1ms preprocess, 279.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziUjar-ff-QoyvvsHn8lmQ_270.JPG: 480x640 1 Waste, 270.4ms
Speed: 0.9ms preprocess, 270.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziXq14_78kY4s4ctQz8S7g_0.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziXq14_78kY4s4ctQz8S7g_90.JPG: 480x640 (no detections), 271.8ms
Speed: 1.3ms preprocess, 271.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziXq14_78kY4s4ctQz8S7g_180.JPG: 480x640 (no detections), 271.0ms
Speed: 1.1ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziXq14_78kY4s4ctQz8S7g_270.JPG: 480x640 (no detections), 312.9ms
Speed: 1.0ms preprocess, 312.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziZniSd964BdktN45Bx-Yw_0.JPG: 480x640 (no detections), 320.3ms
Speed: 1.1ms preprocess, 320.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziZniSd964BdktN45Bx-Yw_90.JPG: 480x640 (no detections), 309.0ms
Speed: 1.2ms preprocess, 309.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziZniSd964BdktN45Bx-Yw_180.JPG: 480x640 (no detections), 326.0ms
Speed: 1.2ms preprocess, 326.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziZniSd964BdktN45Bx-Yw_270.JPG: 480x640 (no detections), 286.6ms
Speed: 1.7ms preprocess, 286.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziccdP5vGDpMbxDNPDmJIg_0.JPG: 480x640 (no detections), 283.7ms
Speed: 1.1ms preprocess, 283.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziccdP5vGDpMbxDNPDmJIg_90.JPG: 480x640 (no detections), 276.6ms
Speed: 1.0ms preprocess, 276.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziccdP5vGDpMbxDNPDmJIg_180.JPG: 480x640 (no detections), 277.7ms
Speed: 1.1ms preprocess, 277.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziccdP5vGDpMbxDNPDmJIg_270.JPG: 480x640 (no detections), 277.7ms
Speed: 1.0ms preprocess, 277.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zidWhLQtPW2VrbWcOglTKg_0.JPG: 480x640 (no detections), 276.1ms

Speed: 1.1ms preprocess, 276.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zidWhLQtPW2VrbWcOglTKg_90.JPG: 480x640 (no detections), 278.5ms
Speed: 1.0ms preprocess, 278.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zidWhLQtPW2VrbWcOglTKg_180.JPG: 480x640 (no detections), 274.5ms
Speed: 1.0ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zidWhLQtPW2VrbWcOglTKg_270.JPG: 480x640 (no detections), 274.4ms
Speed: 1.0ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zieKVym2BwWgj8a5kt6LQw_0.JPG: 480x640 (no detections), 275.8ms
Speed: 1.1ms preprocess, 275.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zieKVym2BwWgj8a5kt6LQw_90.JPG: 480x640 (no detections), 278.5ms
Speed: 1.1ms preprocess, 278.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zieKVym2BwWgj8a5kt6LQw_180.JPG: 480x640 (no detections), 277.9ms
Speed: 1.0ms preprocess, 277.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zieKVym2BwWgj8a5kt6LQw_270.JPG: 480x640 (no detections), 291.4ms
Speed: 1.2ms preprocess, 291.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zigaaDah8miVLx9XnNGl1Q_0.JPG: 480x640 (no detections), 275.6ms
Speed: 1.1ms preprocess, 275.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zigaaDah8miVLx9XnNGl1Q_90.JPG: 480x640 (no detections), 272.6ms
Speed: 1.2ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zigaaDah8miVLx9XnNGl1Q_180.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zigaaDah8miVLx9XnNGl1Q_270.JPG: 480x640 (no detections), 279.7ms
Speed: 1.0ms preprocess, 279.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zigv0PBiPoTydkEal3aT5w_0.JPG: 480x640 (no detections), 307.5ms
Speed: 1.4ms preprocess, 307.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zigv0PBiPoTydkEal3aT5w_90.JPG: 480x640 (no detections), 299.0ms
Speed: 1.4ms preprocess, 299.0ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zigv0PBiPoTydkEal3aT5w_180.JPG: 480x640 (no detections), 295.0ms
Speed: 1.3ms preprocess, 295.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zigv0PBiPoTydkEal3aT5w_270.JPG: 480x640 (no detections), 286.4ms
Speed: 1.1ms preprocess, 286.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zihbMFgwROFQWpW5ir5zPg_0.JPG: 480x640 (no detections), 273.6ms
Speed: 1.1ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zihbMFgwROFQWpW5ir5zPg_90.JPG: 480x640 (no detections), 271.1ms
Speed: 1.0ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zihbMFgwROFQWpW5ir5zPg_180.JPG: 480x640 (no detections), 279.0ms
Speed: 1.0ms preprocess, 279.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zihbMFgwROFQWpW5ir5zPg_270.JPG: 480x640 (no detections), 271.1ms
Speed: 1.2ms preprocess, 271.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zimZWAr6rnbbaIZkDaBkRw_0.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zimZWAr6rnbbaIZkDaBkRw_90.JPG: 480x640 (no detections), 272.4ms
Speed: 1.2ms preprocess, 272.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zimZWAr6rnbbaIZkDaBkRw_180.JPG: 480x640 (no detections), 271.4ms
Speed: 1.0ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zimZWAr6rnbbaIZkDaBkRw_270.JPG: 480x640 (no detections), 272.0ms
Speed: 1.2ms preprocess, 272.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zip6j4qaKNl5kAcyBtZ08Q_0.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zip6j4qaKNl5kAcyBtZ08Q_90.JPG: 480x640 (no detections), 272.6ms
Speed: 1.2ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zip6j4qaKNl5kAcyBtZ08Q_180.JPG: 480x640 (no detections), 274.8ms
Speed: 1.2ms preprocess, 274.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/zip6j4qaKNl5kAcyBtZ08Q_270.JPG: 480x640 (no detections), 300.2ms
Speed: 1.0ms preprocess, 300.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziu_nItG_KJuCubA_Ww7jQ_0.JPG: 480x640 (no detections), 280.0ms
Speed: 1.2ms preprocess, 280.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziu_nItG_KJuCubA_Ww7jQ_90.JPG: 480x640 (no detections), 275.1ms
Speed: 1.0ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziu_nItG_KJuCubA_Ww7jQ_180.JPG: 480x640 (no detections), 271.4ms
Speed: 1.0ms preprocess, 271.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziu_nItG_KJuCubA_Ww7jQ_270.JPG: 480x640 (no detections), 273.1ms
Speed: 1.1ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziw0kycedskvRsE16wfaJQ_0.JPG: 480x640 (no detections), 271.5ms
Speed: 1.0ms preprocess, 271.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziw0kycedskvRsE16wfaJQ_90.JPG: 480x640 (no detections), 277.6ms
Speed: 1.0ms preprocess, 277.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziw0kycedskvRsE16wfaJQ_180.JPG: 480x640 (no detections), 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziw0kycedskvRsE16wfaJQ_270.JPG: 480x640 (no detections), 276.0ms
Speed: 1.2ms preprocess, 276.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziysp40JN3SUEgwTlXOsNA_0.JPG: 480x640 (no detections), 273.9ms
Speed: 1.1ms preprocess, 273.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziysp40JN3SUEgwTlXOsNA_90.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziysp40JN3SUEgwTlXOsNA_180.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/i/ziysp40JN3SUEgwTlXOsNA_270.JPG: 480x640 (no detections), 273.7ms
Speed: 1.2ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zj1cSt-y_-KNL_FQDXaANQ_0.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zj1cSt-y_-KNL_FQDXaANQ_90.JPG: 480x640 (no detections), 338.4ms
Speed: 1.7ms preprocess, 338.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zj1cSt-y_-KNL_FQDXaANQ_180.JPG: 480x640 (no detections), 277.9ms
Speed: 1.0ms preprocess, 277.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zj1cSt-y_-KNL_FQDXaANQ_270.JPG: 480x640 (no detections), 285.9ms
Speed: 1.2ms preprocess, 285.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zj3RTazsO2oMmkRWmiY8Mw_0.JPG: 480x640 (no detections), 272.3ms
Speed: 1.1ms preprocess, 272.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zj3RTazsO2oMmkRWmiY8Mw_90.JPG: 480x640 (no detections), 271.6ms
Speed: 1.0ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zj3RTazsO2oMmkRWmiY8Mw_180.JPG: 480x640 (no detections), 274.0ms
Speed: 1.0ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zj3RTazsO2oMmkRWmiY8Mw_270.JPG: 480x640 (no detections), 286.6ms
Speed: 1.1ms preprocess, 286.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zj3awLTtpj9P2QKWcS1koA_0.JPG: 480x640 (no detections), 286.0ms
Speed: 1.8ms preprocess, 286.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zj3awLTtpj9P2QKWcS1koA_90.JPG: 480x640 (no detections), 275.5ms
Speed: 1.7ms preprocess, 275.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zj3awLTtpj9P2QKWcS1koA_180.JPG: 480x640 (no detections), 285.8ms
Speed: 1.7ms preprocess, 285.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zj3awLTtpj9P2QKWcS1koA_270.JPG: 480x640 (no detections), 275.7ms
Speed: 1.4ms preprocess, 275.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zj3iRyC4-Qy1683P46CkxQ_0.JPG: 480x640 (no detections), 298.5ms
Speed: 1.1ms preprocess, 298.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zj3iRyC4-Qy1683P46CkxQ_90.JPG: 480x640 (no detections), 315.9ms
Speed: 2.0ms preprocess, 315.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zj3iRyC4-Qy1683P46CkxQ_180.JPG: 480x640 (no detections), 332.3ms
Speed: 1.7ms preprocess, 332.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zj3iRyC4-Qy1683P46CkxQ_270.JPG: 480x640 (no detections), 324.5ms
Speed: 1.3ms preprocess, 324.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zj670dvXtN1YZ137LPXdCQ_0.JPG: 480x640 (no detections), 297.2ms
Speed: 1.4ms preprocess, 297.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zj670dvXtN1YZ137LPXdCQ_90.JPG: 480x640 (no detections), 314.6ms
Speed: 1.1ms preprocess, 314.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zj670dvXtN1YZ137LPXdCQ_180.JPG: 480x640 (no detections), 285.6ms
Speed: 1.6ms preprocess, 285.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zj670dvXtN1YZ137LPXdCQ_270.JPG: 480x640 (no detections), 274.9ms
Speed: 1.2ms preprocess, 274.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zj9hGC45AQV2v48K90Kqrw_0.JPG: 480x640 (no detections), 268.9ms
Speed: 1.1ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zj9hGC45AQV2v48K90Kqrw_90.JPG: 480x640 (no detections), 273.8ms
Speed: 1.0ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zj9hGC45AQV2v48K90Kqrw_180.JPG: 480x640 (no detections), 273.2ms
Speed: 1.1ms preprocess, 273.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zj9hGC45AQV2v48K90Kqrw_270.JPG: 480x640 (no detections), 270.4ms
Speed: 1.1ms preprocess, 270.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjB_7nk4r0syPKLElyT3Ow_0.JPG: 480x640 (no detections), 288.3ms
Speed: 1.1ms preprocess, 288.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjB_7nk4r0syPKLElyT3Ow_90.JPG: 480x640 (no detections), 293.2ms
Speed: 1.2ms preprocess, 293.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjB_7nk4r0syPKLElyT3Ow_180.JPG: 480x640 (no detections), 276.5ms
Speed: 1.1ms preprocess, 276.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjB_7nk4r0syPKLElyT3Ow_270.JPG: 480x640 (no detections), 298.9ms

Speed: 1.1ms preprocess, 298.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjFH7KX6NnWK59Mu_1m6qw_0.JPG: 480x640 (no detections), 277.3ms
Speed: 1.2ms preprocess, 277.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjFH7KX6NnWK59Mu_1m6qw_90.JPG: 480x640 (no detections), 272.4ms
Speed: 1.0ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjFH7KX6NnWK59Mu_1m6qw_180.JPG: 480x640 (no detections), 285.9ms
Speed: 1.2ms preprocess, 285.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjFH7KX6NnWK59Mu_1m6qw_270.JPG: 480x640 (no detections), 273.4ms
Speed: 1.1ms preprocess, 273.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjGlCN_4SkuQBeu-F-HGBA_0.JPG: 480x640 (no detections), 273.1ms
Speed: 1.1ms preprocess, 273.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjGlCN_4SkuQBeu-F-HGBA_90.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjGlCN_4SkuQBeu-F-HGBA_180.JPG: 480x640 (no detections), 275.3ms
Speed: 1.0ms preprocess, 275.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjGlCN_4SkuQBeu-F-HGBA_270.JPG: 480x640 (no detections), 270.5ms
Speed: 1.1ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjKfg62xKvmXYxTit3Kv-A_0.JPG: 480x640 (no detections), 338.5ms
Speed: 1.1ms preprocess, 338.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjKfg62xKvmXYxTit3Kv-A_90.JPG: 480x640 (no detections), 276.4ms
Speed: 1.1ms preprocess, 276.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjKfg62xKvmXYxTit3Kv-A_180.JPG: 480x640 (no detections), 273.5ms
Speed: 1.0ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjKfg62xKvmXYxTit3Kv-A_270.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjN0iUupxpnBol9E3_o3Fg_0.JPG: 480x640 (no detections), 275.9ms
Speed: 1.0ms preprocess, 275.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjN0iUupxpnBol9E3_o3Fg_90.JPG: 480x640 (no detections), 270.5ms
Speed: 1.0ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjN0iUupxpnBol9E3_o3Fg_180.JPG: 480x640 (no detections), 271.6ms
Speed: 1.0ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjN0iUupxpnBol9E3_o3Fg_270.JPG: 480x640 (no detections), 275.0ms
Speed: 1.1ms preprocess, 275.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjQGaQNBSCPdyZOTeRhiBw_0.JPG: 480x640 (no detections), 273.6ms
Speed: 1.1ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjQGaQNBSCPdyZOTeRhiBw_90.JPG: 480x640 (no detections), 278.7ms
Speed: 1.1ms preprocess, 278.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjQGaQNBSCPdyZOTeRhiBw_180.JPG: 480x640 (no detections), 273.9ms
Speed: 1.0ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjQGaQNBSCPdyZOTeRhiBw_270.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjTkExHQRWllWFSsaxvI_A_0.JPG: 480x640 (no detections), 273.3ms
Speed: 1.0ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjTkExHQRWllWFSsaxvI_A_90.JPG: 480x640 (no detections), 267.5ms
Speed: 1.1ms preprocess, 267.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjTkExHQRWllWFSsaxvI_A_180.JPG: 480x640 (no detections), 270.2ms
Speed: 1.0ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjTkExHQRWllWFSsaxvI_A_270.JPG: 480x640 (no detections), 273.1ms
Speed: 1.0ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjUsC_7EB1IuQ6g74GlzqA_0.JPG: 480x640 (no detections), 271.3ms
Speed: 1.0ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjUsC_7EB1IuQ6g74GlzqA_90.JPG: 480x640 (no detections), 276.5ms
Speed: 1.1ms preprocess, 276.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjUsC_7EB1IuQ6g74GlzqA_180.JPG: 480x640 (no detections), 273.5ms
Speed: 1.2ms preprocess, 273.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjUsC_7EB1IuQ6g74GlzqA_270.JPG: 480x640 (no detections), 271.2ms
Speed: 1.0ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjVYDBKPJXwdzvKvH4eRXQ_0.JPG: 480x640 (no detections), 272.2ms
Speed: 1.6ms preprocess, 272.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjVYDBKPJXwdzvKvH4eRXQ_90.JPG: 480x640 (no detections), 268.1ms
Speed: 1.0ms preprocess, 268.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjVYDBKPJXwdzvKvH4eRXQ_180.JPG: 480x640 (no detections), 275.5ms
Speed: 1.1ms preprocess, 275.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjVYDBKPJXwdzvKvH4eRXQ_270.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjXjr6f5lR1Qh6p3Q75Plg_0.JPG: 480x640 (no detections), 272.1ms
Speed: 1.0ms preprocess, 272.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjXjr6f5lR1Qh6p3Q75Plg_90.JPG: 480x640 (no detections), 274.3ms
Speed: 1.1ms preprocess, 274.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjXjr6f5lR1Qh6p3Q75Plg_180.JPG: 480x640 (no detections), 272.7ms
Speed: 1.2ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjXjr6f5lR1Qh6p3Q75Plg_270.JPG: 480x640 (no detections), 273.6ms
Speed: 1.1ms preprocess, 273.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjaB2Vse31l8hekerqhuTA_0.JPG: 480x640 (no detections), 273.9ms
Speed: 1.1ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjaB2Vse31l8hekerqhuTA_90.JPG: 480x640 (no detections), 275.7ms
Speed: 1.0ms preprocess, 275.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjaB2Vse31l8hekerqhuTA_180.JPG: 480x640 (no detections), 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjaB2Vse31l8hekerqhuTA_270.JPG: 480x640 (no detections), 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjaY6Teuq--f4lT26gWSiw_0.JPG: 480x640 (no detections), 277.4ms
Speed: 1.1ms preprocess, 277.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjaY6Teuq--f4lT26gWSiw_90.JPG: 480x640 (no detections), 272.0ms
Speed: 1.1ms preprocess, 272.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjaY6Teuq--f4lT26gWSiw_180.JPG: 480x640 (no detections), 272.0ms
Speed: 1.0ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjaY6Teuq--f4lT26gWSiw_270.JPG: 480x640 (no detections), 271.1ms
Speed: 1.2ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjdSBZj5NVUKyY7y0DWFHQ_0.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjdSBZj5NVUKyY7y0DWFHQ_90.JPG: 480x640 (no detections), 271.8ms
Speed: 1.2ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjdSBZj5NVUKyY7y0DWFHQ_180.JPG: 480x640 (no detections), 273.4ms
Speed: 1.1ms preprocess, 273.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjdSBZj5NVUKyY7y0DWFHQ_270.JPG: 480x640 (no detections), 274.2ms
Speed: 1.1ms preprocess, 274.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjhCicISxgGnGjUJXfaH2w_0.JPG: 480x640 (no detections), 282.6ms
Speed: 1.0ms preprocess, 282.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjhCicISxgGnGjUJXfaH2w_90.JPG: 480x640 (no detections), 274.5ms
Speed: 1.1ms preprocess, 274.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjhCicISxgGnGjUJXfaH2w_180.JPG: 480x640 (no detections), 273.6ms
Speed: 1.1ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjhCicISxgGnGjUJXfaH2w_270.JPG: 480x640 (no detections), 275.7ms
Speed: 1.1ms preprocess, 275.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjkITfwqK_fswoYQIJB6ag_0.JPG: 480x640 (no detections), 273.6ms
Speed: 1.4ms preprocess, 273.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjkITfwqK_fswoYQIJB6ag_90.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjkITfwqK_fswoYQIJB6ag_180.JPG: 480x640 (no detections), 271.9ms
Speed: 1.0ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjkITfwqK_fswoYQIJB6ag_270.JPG: 480x640 (no detections), 278.8ms
Speed: 1.1ms preprocess, 278.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjl-mDenXtoCPevKtro4Jg_0.JPG: 480x640 (no detections), 270.1ms
Speed: 1.2ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjl-mDenXtoCPevKtro4Jg_90.JPG: 480x640 (no detections), 268.9ms
Speed: 1.1ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjl-mDenXtoCPevKtro4Jg_180.JPG: 480x640 (no detections), 268.8ms
Speed: 1.1ms preprocess, 268.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjl-mDenXtoCPevKtro4Jg_270.JPG: 480x640 (no detections), 271.3ms
Speed: 1.5ms preprocess, 271.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjoAfsyj3tf8qYvQLtClfA_0.JPG: 480x640 (no detections), 277.2ms
Speed: 1.0ms preprocess, 277.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjoAfsyj3tf8qYvQLtClfA_90.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjoAfsyj3tf8qYvQLtClfA_180.JPG: 480x640 (no detections), 271.0ms
Speed: 1.0ms preprocess, 271.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjoAfsyj3tf8qYvQLtClfA_270.JPG: 480x640 (no detections), 274.0ms
Speed: 1.1ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjt6kPeAsab4jLc44AlG_w_0.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjt6kPeAsab4jLc44AlG_w_90.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjt6kPeAsab4jLc44AlG_w_180.JPG: 480x640 (no detections), 271.6ms

Speed: 1.1ms preprocess, 271.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/j/zjt6kPeAsab4jLc44AlG_w_270.JPG: 480x640 (no detections), 280.0ms
Speed: 1.2ms preprocess, 280.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zk-xgsOgZtZywHbLYdfgsw_0.JPG: 480x640 (no detections), 276.0ms
Speed: 1.0ms preprocess, 276.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zk-xgsOgZtZywHbLYdfgsw_90.JPG: 480x640 (no detections), 273.0ms
Speed: 1.5ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zk-xgsOgZtZywHbLYdfgsw_180.JPG: 480x640 (no detections), 276.2ms
Speed: 1.1ms preprocess, 276.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zk-xgsOgZtZywHbLYdfgsw_270.JPG: 480x640 (no detections), 274.2ms
Speed: 1.1ms preprocess, 274.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zk1hQZetVa5vttS1b5up_A_0.JPG: 480x640 1 Waste, 268.6ms
Speed: 1.2ms preprocess, 268.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zk1hQZetVa5vttS1b5up_A_90.JPG: 480x640 (no detections), 274.8ms
Speed: 1.3ms preprocess, 274.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zk1hQZetVa5vttS1b5up_A_180.JPG: 480x640 (no detections), 274.1ms
Speed: 1.6ms preprocess, 274.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zk1hQZetVa5vttS1b5up_A_270.JPG: 480x640 1 Waste, 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zk3k4cjX0SPb0KnJW0ZkYQ_0.JPG: 480x640 (no detections), 272.5ms
Speed: 1.1ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zk3k4cjX0SPb0KnJW0ZkYQ_90.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zk3k4cjX0SPb0KnJW0ZkYQ_180.JPG: 480x640 (no detections), 271.0ms
Speed: 1.1ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zk3k4cjX0SPb0KnJW0ZkYQ_270.JPG: 480x640 (no detections), 276.7ms
Speed: 1.1ms preprocess, 276.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zk4DYsQYV4mYr50dsI0maA_0.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zk4DYsQYV4mYr50dsI0maA_90.JPG: 480x640 (no detections), 268.1ms
Speed: 1.0ms preprocess, 268.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zk4DYsQYV4mYr50dsI0maA_180.JPG: 480x640 (no detections), 274.3ms
Speed: 1.1ms preprocess, 274.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zk4DYsQYV4mYr50dsI0maA_270.JPG: 480x640 (no detections), 269.5ms
Speed: 1.0ms preprocess, 269.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zk4ryopZ8HiCDDGxCq5dLQ_0.JPG: 480x640 (no detections), 274.7ms
Speed: 1.1ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zk4ryopZ8HiCDDGxCq5dLQ_90.JPG: 480x640 (no detections), 275.8ms
Speed: 1.2ms preprocess, 275.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zk4ryopZ8HiCDDGxCq5dLQ_180.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zk4ryopZ8HiCDDGxCq5dLQ_270.JPG: 480x640 (no detections), 273.1ms
Speed: 1.1ms preprocess, 273.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkBRuFLI3n17HWu1pBc5yQ_0.JPG: 480x640 (no detections), 262.4ms
Speed: 1.2ms preprocess, 262.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkBRuFLI3n17HWu1pBc5yQ_90.JPG: 480x640 (no detections), 290.6ms
Speed: 1.1ms preprocess, 290.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkBRuFLI3n17HWu1pBc5yQ_180.JPG: 480x640 (no detections), 272.2ms
Speed: 1.3ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkBRuFLI3n17HWu1pBc5yQ_270.JPG: 480x640 (no detections), 343.5ms
Speed: 1.1ms preprocess, 343.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkCFeQ9SxOw5HAsdCx-SYQ_0.JPG: 480x640 1 Waste, 278.8ms
Speed: 1.1ms preprocess, 278.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkCFeQ9SxOw5HAsdCx-SYQ_90.JPG: 480x640 (no detections), 274.6ms
Speed: 1.0ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkCFeQ9SxOw5HAsdCx-SYQ_180.JPG: 480x640 (no detections), 276.0ms
Speed: 1.1ms preprocess, 276.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkCFeQ9SxOw5HAsdCx-SYQ_270.JPG: 480x640 (no detections), 274.8ms
Speed: 1.0ms preprocess, 274.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkDQon2QWLT7Q0LNHQkdcQ_0.JPG: 480x640 (no detections), 277.3ms
Speed: 1.1ms preprocess, 277.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkDQon2QWLT7Q0LNHQkdcQ_90.JPG: 480x640 1 Waste, 270.6ms
Speed: 1.0ms preprocess, 270.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkDQon2QWLT7Q0LNHQkdcQ_180.JPG: 480x640 (no detections), 275.9ms
Speed: 1.1ms preprocess, 275.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkDQon2QWLT7Q0LNHQkdcQ_270.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkE-ZhCAzEu-idwNsSK-Ig_0.JPG: 480x640 (no detections), 271.4ms
Speed: 1.0ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkE-ZhCAzEu-idwNsSK-Ig_90.JPG: 480x640 (no detections), 275.7ms
Speed: 1.0ms preprocess, 275.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkE-ZhCAzEu-idwNsSK-Ig_180.JPG: 480x640 (no detections), 277.7ms
Speed: 1.1ms preprocess, 277.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkE-ZhCAzEu-idwNsSK-Ig_270.JPG: 480x640 (no detections), 279.3ms
Speed: 1.2ms preprocess, 279.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkIcbnooL7SeV_9NP_Q1hg_0.JPG: 480x640 (no detections), 274.8ms
Speed: 1.1ms preprocess, 274.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkIcbnooL7SeV_9NP_Q1hg_90.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkIcbnooL7SeV_9NP_Q1hg_180.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkIcbnooL7SeV_9NP_Q1hg_270.JPG: 480x640 (no detections), 270.2ms
Speed: 1.2ms preprocess, 270.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkPC9pRb7itX7ZQsYc4SMQ_0.JPG: 480x640 (no detections), 273.0ms
Speed: 1.0ms preprocess, 273.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkPC9pRb7itX7ZQsYc4SMQ_90.JPG: 480x640 (no detections), 280.4ms
Speed: 1.2ms preprocess, 280.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkPC9pRb7itX7ZQsYc4SMQ_180.JPG: 480x640 (no detections), 275.4ms
Speed: 1.1ms preprocess, 275.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkPC9pRb7itX7ZQsYc4SMQ_270.JPG: 480x640 (no detections), 275.2ms
Speed: 1.0ms preprocess, 275.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkTDARKmiJFKPQFxZHiPEw_0.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkTDARKmiJFKPQFxZHiPEw_90.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkTDARKmiJFKPQFxZHiPEw_180.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkTDARKmiJFKPQFxZHiPEw_270.JPG: 480x640 (no detections), 271.5ms
Speed: 1.2ms preprocess, 271.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkXCpn9VVt10t8Uv8Ir4eA_0.JPG: 480x640 (no detections), 286.2ms
Speed: 1.2ms preprocess, 286.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkXCpn9VVt10t8Uv8Ir4eA_90.JPG: 480x640 (no detections), 332.4ms
Speed: 1.1ms preprocess, 332.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkXCpn9VVt10t8Uv8Ir4eA_180.JPG: 480x640 (no detections), 268.7ms
Speed: 1.1ms preprocess, 268.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkXCpn9VVt10t8Uv8Ir4eA_270.JPG: 480x640 (no detections), 274.5ms
Speed: 1.1ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkXKISQYsnrzdReewOk4Rw_0.JPG: 480x640 (no detections), 274.7ms
Speed: 1.1ms preprocess, 274.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkXKISQYsnrzdReewOk4Rw_90.JPG: 480x640 (no detections), 279.1ms
Speed: 1.0ms preprocess, 279.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkXKISQYsnrzdReewOk4Rw_180.JPG: 480x640 (no detections), 271.5ms
Speed: 1.2ms preprocess, 271.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkXKISQYsnrzdReewOk4Rw_270.JPG: 480x640 (no detections), 279.3ms
Speed: 1.1ms preprocess, 279.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zk_HN-4QIuCH_kX9PQqLmQ_0.JPG: 480x640 (no detections), 289.9ms
Speed: 1.2ms preprocess, 289.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zk_HN-4QIuCH_kX9PQqLmQ_90.JPG: 480x640 (no detections), 277.0ms
Speed: 1.0ms preprocess, 277.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zk_HN-4QIuCH_kX9PQqLmQ_180.JPG: 480x640 (no detections), 276.2ms
Speed: 1.1ms preprocess, 276.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zk_HN-4QIuCH_kX9PQqLmQ_270.JPG: 480x640 (no detections), 280.6ms
Speed: 1.0ms preprocess, 280.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkd8Y07hhxmlrVmIbBa8jA_0.JPG: 480x640 (no detections), 277.4ms
Speed: 1.0ms preprocess, 277.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkd8Y07hhxmlrVmIbBa8jA_90.JPG: 480x640 (no detections), 274.2ms
Speed: 1.0ms preprocess, 274.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkd8Y07hhxmlrVmIbBa8jA_180.JPG: 480x640 (no detections), 270.5ms
Speed: 1.1ms preprocess, 270.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkd8Y07hhxmlrVmIbBa8jA_270.JPG: 480x640 (no detections), 292.6ms
Speed: 1.0ms preprocess, 292.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkdSMO48EtuUA6tLcPwYxA_0.JPG: 480x640 (no detections), 278.8ms
Speed: 1.2ms preprocess, 278.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkdSMO48EtuUA6tLcPwYxA_90.JPG: 480x640 (no detections), 280.3ms

Speed: 1.5ms preprocess, 280.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkdSMO48EtuUA6tLcPwYxA_180.JPG: 480x640 (no detections), 275.4ms
Speed: 1.2ms preprocess, 275.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkdSMO48EtuUA6tLcPwYxA_270.JPG: 480x640 (no detections), 282.4ms
Speed: 1.2ms preprocess, 282.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkecg5ZRqlBkORznvhyDfg_0.JPG: 480x640 (no detections), 288.4ms
Speed: 1.6ms preprocess, 288.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkecg5ZRqlBkORznvhyDfg_90.JPG: 480x640 (no detections), 277.4ms
Speed: 1.2ms preprocess, 277.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkecg5ZRqlBkORznvhyDfg_180.JPG: 480x640 (no detections), 278.8ms
Speed: 1.2ms preprocess, 278.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkecg5ZRqlBkORznvhyDfg_270.JPG: 480x640 (no detections), 272.4ms
Speed: 1.2ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkgH7bkUSpqyv4pbve314w_0.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkgH7bkUSpqyv4pbve314w_90.JPG: 480x640 (no detections), 273.3ms
Speed: 1.0ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkgH7bkUSpqyv4pbve314w_180.JPG: 480x640 (no detections), 270.6ms
Speed: 1.0ms preprocess, 270.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkgH7bkUSpqyv4pbve314w_270.JPG: 480x640 (no detections), 276.4ms
Speed: 1.1ms preprocess, 276.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkjwN_LumjA1EP3C7_IOfA_0.JPG: 480x640 (no detections), 301.1ms
Speed: 1.1ms preprocess, 301.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkjwN_LumjA1EP3C7_IOfA_90.JPG: 480x640 (no detections), 280.8ms
Speed: 1.1ms preprocess, 280.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkjwN_LumjA1EP3C7_IOfA_180.JPG: 480x640 (no detections), 311.2ms
Speed: 1.2ms preprocess, 311.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkjwN_LumjA1EP3C7_IOfA_270.JPG: 480x640 (no detections), 279.5ms
Speed: 1.1ms preprocess, 279.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkmG5CuJEQynbt4TReoelg_0.JPG: 480x640 (no detections), 281.7ms
Speed: 1.1ms preprocess, 281.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkmG5CuJEQynbt4TReoelg_90.JPG: 480x640 (no detections), 305.1ms
Speed: 1.3ms preprocess, 305.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkmG5CuJEQynbt4TReoelg_180.JPG: 480x640 (no detections), 290.1ms
Speed: 1.2ms preprocess, 290.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkmG5CuJEQynbt4TReoelg_270.JPG: 480x640 (no detections), 289.6ms
Speed: 1.7ms preprocess, 289.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkn6Q0WIWDBlTxHOEmpZ9Q_0.JPG: 480x640 (no detections), 313.9ms
Speed: 1.2ms preprocess, 313.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkn6Q0WIWDBlTxHOEmpZ9Q_90.JPG: 480x640 (no detections), 299.7ms
Speed: 1.8ms preprocess, 299.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkn6Q0WIWDBlTxHOEmpZ9Q_180.JPG: 480x640 (no detections), 285.4ms
Speed: 1.2ms preprocess, 285.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkn6Q0WIWDBlTxHOEmpZ9Q_270.JPG: 480x640 (no detections), 281.5ms
Speed: 1.2ms preprocess, 281.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zknNvvMRiwy3l9ibqhWUyw_0.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zknNvvMRiwy3l9ibqhWUyw_90.JPG: 480x640 (no detections), 289.3ms
Speed: 1.0ms preprocess, 289.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zknNvvMRiwy3l9ibqhWUyw_180.JPG: 480x640 (no detections), 312.7ms
Speed: 1.2ms preprocess, 312.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zknNvvMRiwy3l9ibqhWUyw_270.JPG: 480x640 (no detections), 308.5ms
Speed: 1.1ms preprocess, 308.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkorf8yvFFeE9FxSFYBhZw_0.JPG: 480x640 (no detections), 300.3ms
Speed: 1.2ms preprocess, 300.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkorf8yvFFeE9FxSFYBhZw_90.JPG: 480x640 (no detections), 286.1ms
Speed: 1.4ms preprocess, 286.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkorf8yvFFeE9FxSFYBhZw_180.JPG: 480x640 (no detections), 279.0ms
Speed: 1.2ms preprocess, 279.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkorf8yvFFeE9FxSFYBhZw_270.JPG: 480x640 (no detections), 273.3ms
Speed: 1.2ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkwohhFh1i1r6aU58KGHAw_0.JPG: 480x640 (no detections), 282.8ms
Speed: 1.1ms preprocess, 282.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkwohhFh1i1r6aU58KGHAw_90.JPG: 480x640 (no detections), 288.6ms
Speed: 1.2ms preprocess, 288.6ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkwohhFh1i1r6aU58KGHAw_180.JPG: 480x640 (no detections), 274.6ms
Speed: 1.1ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkwohhFh1i1r6aU58KGHAw_270.JPG: 480x640 (no detections), 297.8ms
Speed: 1.1ms preprocess, 297.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkyUtYOnia3hk472yLuz1g_0.JPG: 480x640 (no detections), 274.6ms
Speed: 1.2ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkyUtYOnia3hk472yLuz1g_90.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkyUtYOnia3hk472yLuz1g_180.JPG: 480x640 1 Waste, 273.4ms
Speed: 1.1ms preprocess, 273.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkyUtYOnia3hk472yLuz1g_270.JPG: 480x640 (no detections), 274.4ms
Speed: 1.1ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkyoyLCYbJP6XHLKqZGHPQ_0.JPG: 480x640 (no detections), 274.4ms
Speed: 1.0ms preprocess, 274.4ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkyoyLCYbJP6XHLKqZGHPQ_90.JPG: 480x640 (no detections), 273.3ms
Speed: 1.0ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkyoyLCYbJP6XHLKqZGHPQ_180.JPG: 480x640 (no detections), 273.7ms
Speed: 1.0ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/K/zkyoyLCYbJP6XHLKqZGHPQ_270.JPG: 480x640 (no detections), 276.8ms
Speed: 1.1ms preprocess, 276.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zl1yOKnFlsSVLtqE88ROSQ_0.JPG: 480x640 (no detections), 276.1ms
Speed: 1.1ms preprocess, 276.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zl1yOKnFlsSVLtqE88ROSQ_90.JPG: 480x640 (no detections), 273.7ms
Speed: 1.2ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zl1yOKnFlsSVLtqE88ROSQ_180.JPG: 480x640 (no detections), 274.5ms
Speed: 1.0ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zl1yOKnFlsSVLtqE88ROSQ_270.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zl2hK1GjBcWSlQvRJJWcLg_0.JPG: 480x640 (no detections), 273.6ms
Speed: 1.1ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zl2hK1GjBcWSlQvRJJWcLg_90.JPG: 480x640 (no detections), 277.5ms
Speed: 1.0ms preprocess, 277.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zl2hK1GjBcWSlQvRJJWcLg_180.JPG: 480x640 (no detections), 275.0ms
Speed: 1.1ms preprocess, 275.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zl2hK1GjBcWSlQvRJJWcLg_270.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zl5NgApa6Us6_gdgHZOLBw_0.JPG: 480x640 (no detections), 276.1ms
Speed: 1.1ms preprocess, 276.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zl5NgApa6Us6_gdgHZOLBw_90.JPG: 480x640 (no detections), 273.6ms
Speed: 1.2ms preprocess, 273.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zl5NgApa6Us6_gdgHZOLBw_180.JPG: 480x640 (no detections), 271.5ms
Speed: 1.1ms preprocess, 271.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zl5NgApa6Us6_gdgHZOLBw_270.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zl7aXMlpPd5r4-oz4nGWEQ_0.JPG: 480x640 (no detections), 274.7ms
Speed: 1.1ms preprocess, 274.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zl7aXMlpPd5r4-oz4nGWEQ_90.JPG: 480x640 (no detections), 273.1ms
Speed: 1.0ms preprocess, 273.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zl7aXMlpPd5r4-oz4nGWEQ_180.JPG: 480x640 (no detections), 274.6ms
Speed: 1.2ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zl7aXMlpPd5r4-oz4nGWEQ_270.JPG: 480x640 (no detections), 273.6ms
Speed: 1.2ms preprocess, 273.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlBGDzrkXTr7KF9b0uGt4A_0.JPG: 480x640 (no detections), 268.8ms
Speed: 1.0ms preprocess, 268.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlBGDzrkXTr7KF9b0uGt4A_90.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlBGDzrkXTr7KF9b0uGt4A_180.JPG: 480x640 (no detections), 272.4ms
Speed: 1.2ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlBGDzrkXTr7KF9b0uGt4A_270.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlJ9VlOw9HxFBtoHShZk_Q_0.JPG: 480x640 (no detections), 272.8ms
Speed: 1.2ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlJ9VlOw9HxFBtoHShZk_Q_90.JPG: 480x640 (no detections), 270.3ms
Speed: 1.1ms preprocess, 270.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlJ9VlOw9HxFBtoHShZk_Q_180.JPG: 480x640 (no detections), 277.5ms
Speed: 1.1ms preprocess, 277.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlJ9VlOw9HxFBtoHShZk_Q_270.JPG: 480x640 (no detections), 327.7ms
Speed: 1.1ms preprocess, 327.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlNH7yF0yu8idpmlGx7uPQ_0.JPG: 480x640 (no detections), 274.5ms

Speed: 1.2ms preprocess, 274.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlNH7yF0yu8idpmlGx7uPQ_90.JPG: 480x640 (no detections), 300.6ms
Speed: 1.1ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlNH7yF0yu8idpmlGx7uPQ_180.JPG: 480x640 (no detections), 272.8ms
Speed: 1.0ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlNH7yF0yu8idpmlGx7uPQ_270.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlNh84bDhwDvFB0GpRqLPg_0.JPG: 480x640 1 Waste, 278.9ms
Speed: 1.0ms preprocess, 278.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlNh84bDhwDvFB0GpRqLPg_90.JPG: 480x640 (no detections), 281.4ms
Speed: 1.0ms preprocess, 281.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlNh84bDhwDvFB0GpRqLPg_180.JPG: 480x640 (no detections), 273.4ms
Speed: 1.1ms preprocess, 273.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlNh84bDhwDvFB0GpRqLPg_270.JPG: 480x640 (no detections), 269.9ms
Speed: 1.0ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlNrlW62i8O3bsq9fY8-jA_0.JPG: 480x640 (no detections), 274.8ms
Speed: 1.2ms preprocess, 274.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlNrlW62i8O3bsq9fY8-jA_90.JPG: 480x640 (no detections), 277.2ms
Speed: 1.4ms preprocess, 277.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlNrlW62i8O3bsq9fY8-jA_180.JPG: 480x640 (no detections), 279.0ms
Speed: 1.2ms preprocess, 279.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlNrlW62i8O3bsq9fY8-jA_270.JPG: 480x640 (no detections), 269.8ms
Speed: 1.2ms preprocess, 269.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlPi-t0UqGrvEoY8lsDvHg_0.JPG: 480x640 (no detections), 272.3ms
Speed: 1.1ms preprocess, 272.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlPi-t0UqGrvEoY8lsDvHg_90.JPG: 480x640 (no detections), 275.5ms
Speed: 1.2ms preprocess, 275.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlPi-t0UqGrvEoY8lsDvHg_180.JPG: 480x640 (no detections), 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlPi-t0UqGrvEoY8lsDvHg_270.JPG: 480x640 (no detections), 274.0ms
Speed: 1.1ms preprocess, 274.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlT6qK2TlRajJvBaf-CtGg_0.JPG: 480x640 (no detections), 272.0ms
Speed: 1.1ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlT6qK2TlRajJvBaf-CtGg_90.JPG: 480x640 (no detections), 271.5ms
Speed: 1.1ms preprocess, 271.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlT6qK2TlRajJvBaf-CtGg_180.JPG: 480x640 (no detections), 270.6ms
Speed: 1.0ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlT6qK2TlRajJvBaf-CtGg_270.JPG: 480x640 (no detections), 273.8ms
Speed: 1.0ms preprocess, 273.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlVoTp7_vZZjSNW-0S2L0g_0.JPG: 480x640 (no detections), 285.8ms
Speed: 1.1ms preprocess, 285.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlVoTp7_vZZjSNW-0S2L0g_90.JPG: 480x640 (no detections), 279.4ms
Speed: 1.2ms preprocess, 279.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlVoTp7_vZZjSNW-0S2L0g_180.JPG: 480x640 (no detections), 273.2ms
Speed: 1.2ms preprocess, 273.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlVoTp7_vZZjSNW-0S2L0g_270.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlVt3aP_e9V4AMQQZDr5sw_0.JPG: 480x640 (no detections), 274.8ms
Speed: 1.1ms preprocess, 274.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlVt3aP_e9V4AMQQZDr5sw_90.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlVt3aP_e9V4AMQQZDr5sw_180.JPG: 480x640 (no detections), 274.0ms
Speed: 1.0ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlVt3aP_e9V4AMQQZDr5sw_270.JPG: 480x640 (no detections), 272.4ms
Speed: 1.1ms preprocess, 272.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlfqaQyq-xECCNFn1UpRNA_0.JPG: 480x640 (no detections), 276.5ms
Speed: 1.1ms preprocess, 276.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlfqaQyq-xECCNFn1UpRNA_90.JPG: 480x640 (no detections), 278.9ms
Speed: 1.2ms preprocess, 278.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlfqaQyq-xECCNFn1UpRNA_180.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlfqaQyq-xECCNFn1UpRNA_270.JPG: 480x640 (no detections), 272.8ms
Speed: 1.2ms preprocess, 272.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlggh585T2XPB6V4aY8mKQ_0.JPG: 480x640 (no detections), 267.9ms
Speed: 1.1ms preprocess, 267.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlggh585T2XPB6V4aY8mKQ_90.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlggh585T2XPB6V4aY8mKQ_180.JPG: 480x640 (no detections), 268.5ms
Speed: 1.0ms preprocess, 268.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlggh585T2XPB6V4aY8mKQ_270.JPG: 480x640 (no detections), 275.1ms
Speed: 1.0ms preprocess, 275.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zllDa7m0xGN0nxvcI1WUpQ_0.JPG: 480x640 (no detections), 270.8ms
Speed: 1.0ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zllDa7m0xGN0nxvcI1WUpQ_90.JPG: 480x640 (no detections), 271.6ms
Speed: 1.0ms preprocess, 271.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zllDa7m0xGN0nxvcI1WUpQ_180.JPG: 480x640 (no detections), 271.6ms
Speed: 1.0ms preprocess, 271.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zllDa7m0xGN0nxvcI1WUpQ_270.JPG: 480x640 (no detections), 269.8ms
Speed: 1.1ms preprocess, 269.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zllwY5Bz6zTtWtn9yppmMA_0.JPG: 480x640 (no detections), 269.4ms
Speed: 1.1ms preprocess, 269.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zllwY5Bz6zTtWtn9yppmMA_90.JPG: 480x640 (no detections), 271.1ms
Speed: 1.0ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zllwY5Bz6zTtWtn9yppmMA_180.JPG: 480x640 (no detections), 329.5ms
Speed: 1.0ms preprocess, 329.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zllwY5Bz6zTtWtn9yppmMA_270.JPG: 480x640 (no detections), 277.4ms
Speed: 1.1ms preprocess, 277.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlmLpTrkywwhkyFKmLQegA_0.JPG: 480x640 1 Waste, 272.2ms
Speed: 1.0ms preprocess, 272.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlmLpTrkywwhkyFKmLQegA_90.JPG: 480x640 (no detections), 274.7ms
Speed: 1.0ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlmLpTrkywwhkyFKmLQegA_180.JPG: 480x640 (no detections), 271.1ms
Speed: 1.4ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlmLpTrkywwhkyFKmLQegA_270.JPG: 480x640 (no detections), 273.6ms
Speed: 1.1ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlpaT371WIHlRjdb0KP0ig_0.JPG: 480x640 (no detections), 268.8ms
Speed: 1.1ms preprocess, 268.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlpaT371WIHlRjdb0KP0ig_90.JPG: 480x640 (no detections), 270.4ms
Speed: 1.1ms preprocess, 270.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlpaT371WIHlRjdb0KP0ig_180.JPG: 480x640 (no detections), 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlpaT371WIHlRjdb0KP0ig_270.JPG: 480x640 (no detections), 274.5ms
Speed: 1.3ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlxYniTJeQ3Cfdpi5qfzZQ_0.JPG: 480x640 (no detections), 272.1ms
Speed: 1.0ms preprocess, 272.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlxYniTJeQ3Cfdpi5qfzZQ_90.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlxYniTJeQ3Cfdpi5qfzZQ_180.JPG: 480x640 (no detections), 272.5ms
Speed: 1.0ms preprocess, 272.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlxYniTJeQ3Cfdpi5qfzZQ_270.JPG: 480x640 (no detections), 267.7ms
Speed: 1.0ms preprocess, 267.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlyP-GCpW5sxExB9Jzk1sA_0.JPG: 480x640 (no detections), 263.0ms
Speed: 1.2ms preprocess, 263.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlyP-GCpW5sxExB9Jzk1sA_90.JPG: 480x640 (no detections), 277.3ms
Speed: 1.1ms preprocess, 277.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlyP-GCpW5sxExB9Jzk1sA_180.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/L/zlyP-GCpW5sxExB9Jzk1sA_270.JPG: 480x640 (no detections), 277.6ms
Speed: 1.1ms preprocess, 277.6ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zm1tSZgXevGbYaq1swjJzA_0.JPG: 480x640 (no detections), 281.1ms
Speed: 1.2ms preprocess, 281.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zm1tSZgXevGbYaq1swjJzA_90.JPG: 480x640 (no detections), 274.7ms
Speed: 1.0ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zm1tSZgXevGbYaq1swjJzA_180.JPG: 480x640 (no detections), 275.2ms
Speed: 1.1ms preprocess, 275.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zm1tSZgXevGbYaq1swjJzA_270.JPG: 480x640 (no detections), 271.5ms
Speed: 1.0ms preprocess, 271.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zm3Ab3IvzQcvurdn944jAw_0.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zm3Ab3IvzQcvurdn944jAw_90.JPG: 480x640 (no detections), 272.1ms
Speed: 1.1ms preprocess, 272.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zm3Ab3IvzQcvurdn944jAw_180.JPG: 480x640 (no detections), 276.4ms
Speed: 1.0ms preprocess, 276.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zm3Ab3IvzQcvurdn944jAw_270.JPG: 480x640 (no detections), 273.5ms

Speed: 1.2ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zm9A3lkS7Va8nEzwZelAjg_0.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zm9A3lkS7Va8nEzwZelAjg_90.JPG: 480x640 (no detections), 275.6ms
Speed: 1.0ms preprocess, 275.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zm9A3lkS7Va8nEzwZelAjg_180.JPG: 480x640 (no detections), 270.8ms
Speed: 1.0ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zm9A3lkS7Va8nEzwZelAjg_270.JPG: 480x640 (no detections), 272.9ms
Speed: 1.2ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmDG_yYBqpt5BQVledakVQ_0.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmDG_yYBqpt5BQVledakVQ_90.JPG: 480x640 (no detections), 272.4ms
Speed: 1.0ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmDG_yYBqpt5BQVledakVQ_180.JPG: 480x640 (no detections), 273.4ms
Speed: 1.0ms preprocess, 273.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmDG_yYBqpt5BQVledakVQ_270.JPG: 480x640 (no detections), 268.7ms
Speed: 1.1ms preprocess, 268.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmJA3Balvcirj2BiJBgvhQ_0.JPG: 480x640 (no detections), 275.2ms
Speed: 1.1ms preprocess, 275.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmJA3Balvcirj2BiJBgvhQ_90.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmJA3Balvcirj2BiJBgvhQ_180.JPG: 480x640 (no detections), 270.8ms
Speed: 1.0ms preprocess, 270.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmJA3Balvcirj2BiJBgvhQ_270.JPG: 480x640 (no detections), 271.2ms
Speed: 1.0ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmL7JjYEeNcjuyTK9zrbFw_0.JPG: 480x640 (no detections), 269.6ms
Speed: 1.1ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmL7JjYEeNcjuyTK9zrbFw_90.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmL7JjYEeNcjuyTK9zrbFw_180.JPG: 480x640 (no detections), 270.3ms
Speed: 1.0ms preprocess, 270.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmL7JjYEeNcjuyTK9zrbFw_270.JPG: 480x640 (no detections), 274.0ms
Speed: 1.1ms preprocess, 274.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmLDJBNirLhD8zhzMAmn0w_0.JPG: 480x640 (no detections), 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmLDJBNirLhD8zhzMAmn0w_90.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmLDJBNirLhD8zhzMAmn0w_180.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmLDJBNirLhD8zhzMAmn0w_270.JPG: 480x640 (no detections), 274.0ms
Speed: 1.0ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmN_MXrrbalrTv51hQviEQ_0.JPG: 480x640 (no detections), 275.1ms
Speed: 1.2ms preprocess, 275.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmN_MXrrbalrTv51hQviEQ_90.JPG: 480x640 (no detections), 272.3ms
Speed: 1.1ms preprocess, 272.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmN_MXrrbalrTv51hQviEQ_180.JPG: 480x640 (no detections), 273.0ms
Speed: 1.0ms preprocess, 273.0ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmN_MXrrbalrTv51hQviEQ_270.JPG: 480x640 (no detections), 274.4ms
Speed: 1.0ms preprocess, 274.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmUG0zW5yiXOMwVSwBsirw_0.JPG: 480x640 (no detections), 268.1ms
Speed: 1.0ms preprocess, 268.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmUG0zW5yiXOMwVSwBsirw_90.JPG: 480x640 (no detections), 276.1ms
Speed: 1.1ms preprocess, 276.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmUG0zW5yiXOMwVSwBsirw_180.JPG: 480x640 (no detections), 272.3ms
Speed: 1.0ms preprocess, 272.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmUG0zW5yiXOMwVSwBsirw_270.JPG: 480x640 (no detections), 274.0ms
Speed: 1.0ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmW6xzAuTini6LuDDDQmjA_0.JPG: 480x640 (no detections), 276.3ms
Speed: 1.1ms preprocess, 276.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmW6xzAuTini6LuDDDQmjA_90.JPG: 480x640 (no detections), 271.9ms
Speed: 1.0ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmW6xzAuTini6LuDDDQmjA_180.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmW6xzAuTini6LuDDDQmjA_270.JPG: 480x640 (no detections), 270.3ms
Speed: 1.0ms preprocess, 270.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmfQMqzcLoRI_u_CHULpFw_0.JPG: 480x640 (no detections), 272.5ms
Speed: 1.2ms preprocess, 272.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmfQMqzcLoRI_u_CHULpFw_90.JPG: 480x640 (no detections), 273.0ms
Speed: 1.0ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmfQMqzcLoRI_u_CHULpFw_180.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmfQMqzcLoRI_u_CHULpFw_270.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmi5DQ_u7zvY0Fj5mbHhtA_0.JPG: 480x640 (no detections), 268.2ms
Speed: 1.1ms preprocess, 268.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmi5DQ_u7zvY0Fj5mbHhtA_90.JPG: 480x640 (no detections), 276.4ms
Speed: 1.1ms preprocess, 276.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmi5DQ_u7zvY0Fj5mbHhtA_180.JPG: 480x640 (no detections), 272.7ms
Speed: 1.0ms preprocess, 272.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmi5DQ_u7zvY0Fj5mbHhtA_270.JPG: 480x640 (no detections), 272.4ms
Speed: 1.2ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmigic1YmzBarL7XInqw_g_0.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmigic1YmzBarL7XInqw_g_90.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmigic1YmzBarL7XInqw_g_180.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmigic1YmzBarL7XInqw_g_270.JPG: 480x640 (no detections), 277.2ms
Speed: 1.1ms preprocess, 277.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmmGA8T_Pb1Z3czgp543Ng_0.JPG: 480x640 (no detections), 276.4ms
Speed: 1.1ms preprocess, 276.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmmGA8T_Pb1Z3czgp543Ng_90.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmmGA8T_Pb1Z3czgp543Ng_180.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmmGA8T_Pb1Z3czgp543Ng_270.JPG: 480x640 (no detections), 270.3ms
Speed: 1.1ms preprocess, 270.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmmedBO_tvvej13USAe0kw_0.JPG: 480x640 (no detections), 272.4ms
Speed: 1.4ms preprocess, 272.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmmedBO_tvvej13USAe0kw_90.JPG: 480x640 (no detections), 272.1ms
Speed: 1.1ms preprocess, 272.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmmedBO_tvvej13USAe0kw_180.JPG: 480x640 (no detections), 271.3ms
Speed: 1.0ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmmedBO_tvvej13USAe0kw_270.JPG: 480x640 (no detections), 275.9ms
Speed: 1.0ms preprocess, 275.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmmhlV_siuzPxkWUA6UeNA_0.JPG: 480x640 (no detections), 272.2ms
Speed: 1.2ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmmhlV_siuzPxkWUA6UeNA_90.JPG: 480x640 (no detections), 276.9ms
Speed: 1.0ms preprocess, 276.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmmhlV_siuzPxkWUA6UeNA_180.JPG: 480x640 (no detections), 274.9ms
Speed: 1.3ms preprocess, 274.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmmhlV_siuzPxkWUA6UeNA_270.JPG: 480x640 (no detections), 326.5ms
Speed: 1.1ms preprocess, 326.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmnhv8Gb9NFsAAn-TIkgdQ_0.JPG: 480x640 (no detections), 270.7ms
Speed: 1.0ms preprocess, 270.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmnhv8Gb9NFsAAn-TIkgdQ_90.JPG: 480x640 (no detections), 275.1ms
Speed: 1.0ms preprocess, 275.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmnhv8Gb9NFsAAn-TIkgdQ_180.JPG: 480x640 (no detections), 273.8ms
Speed: 1.0ms preprocess, 273.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmnhv8Gb9NFsAAn-TIkgdQ_270.JPG: 480x640 (no detections), 273.4ms
Speed: 1.1ms preprocess, 273.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmo5BlfXalINLjflb8ND-w_0.JPG: 480x640 (no detections), 269.1ms
Speed: 1.1ms preprocess, 269.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmo5BlfXalINLjflb8ND-w_90.JPG: 480x640 (no detections), 270.5ms
Speed: 1.1ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmo5BlfXalINLjflb8ND-w_180.JPG: 480x640 (no detections), 274.0ms
Speed: 1.0ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmo5BlfXalINLjflb8ND-w_270.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmpTmsJerf2XRk2z185ZnA_0.JPG: 480x640 (no detections), 274.1ms
Speed: 1.0ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmpTmsJerf2XRk2z185ZnA_90.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmpTmsJerf2XRk2z185ZnA_180.JPG: 480x640 (no detections), 274.0ms

Speed: 1.1ms preprocess, 274.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmpTmsJerf2XRk2z185ZnA_270.JPG: 480x640 (no detections), 275.5ms
Speed: 1.0ms preprocess, 275.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmrH1fG5QrRtd20Pc_VT7A_0.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmrH1fG5QrRtd20Pc_VT7A_90.JPG: 480x640 1 Waste, 283.7ms
Speed: 1.6ms preprocess, 283.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmrH1fG5QrRtd20Pc_VT7A_180.JPG: 480x640 (no detections), 269.8ms
Speed: 1.1ms preprocess, 269.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmrH1fG5QrRtd20Pc_VT7A_270.JPG: 480x640 1 Waste, 273.9ms
Speed: 1.1ms preprocess, 273.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmtJyNSXP26c0wmALd3xOw_0.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmtJyNSXP26c0wmALd3xOw_90.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmtJyNSXP26c0wmALd3xOw_180.JPG: 480x640 (no detections), 278.6ms
Speed: 1.1ms preprocess, 278.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmtJyNSXP26c0wmALd3xOw_270.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmxKDgejKNNNpIgRq4xWGA_0.JPG: 480x640 (no detections), 275.6ms
Speed: 1.1ms preprocess, 275.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmxKDgejKNNNpIgRq4xWGA_90.JPG: 480x640 (no detections), 274.6ms
Speed: 1.0ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmxKDgejKNNNpIgRq4xWGA_180.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmxKDgejKNNNpIgRq4xWGA_270.JPG: 480x640 (no detections), 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmxtLUCgm4_41yL-S8OjJw_0.JPG: 480x640 (no detections), 270.5ms
Speed: 1.1ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmxtLUCgm4_41yL-S8OjJw_90.JPG: 480x640 (no detections), 274.2ms
Speed: 1.2ms preprocess, 274.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmxtLUCgm4_41yL-S8OjJw_180.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/m/zmxtLUCgm4_41yL-S8OjJw_270.JPG: 480x640 1 Waste, 323.2ms
Speed: 1.1ms preprocess, 323.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zn7Maf3STExkxQTwrlIrLA_0.JPG: 480x640 (no detections), 280.3ms
Speed: 4.9ms preprocess, 280.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zn7Maf3STExkxQTwrlIrLA_90.JPG: 480x640 (no detections), 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zn7Maf3STExkxQTwrlIrLA_180.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zn7Maf3STExkxQTwrlIrLA_270.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zn8RQVOvZt3Bhechps7Gkw_0.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zn8RQVOvZt3Bhechps7Gkw_90.JPG: 480x640 (no detections), 270.2ms
Speed: 1.0ms preprocess, 270.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zn8RQVOvZt3Bhechps7Gkw_180.JPG: 480x640 (no detections), 270.4ms
Speed: 1.1ms preprocess, 270.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zn8RQVOvZt3Bhechps7Gkw_270.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zn9B75wNPM1G3RCpWMJx1w_0.JPG: 480x640 (no detections), 268.7ms
Speed: 1.0ms preprocess, 268.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zn9B75wNPM1G3RCpWMJx1w_90.JPG: 480x640 1 Waste, 276.9ms
Speed: 1.3ms preprocess, 276.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zn9B75wNPM1G3RCpWMJx1w_180.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zn9B75wNPM1G3RCpWMJx1w_270.JPG: 480x640 (no detections), 274.1ms
Speed: 1.3ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zn9LrsSB-J6X7VvdrlZlNw_0.JPG: 480x640 (no detections), 272.5ms
Speed: 1.1ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zn9LrsSB-J6X7VvdrlZlNw_90.JPG: 480x640 (no detections), 273.0ms
Speed: 1.0ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zn9LrsSB-J6X7VvdrlZlNw_180.JPG: 480x640 (no detections), 273.2ms
Speed: 1.0ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zn9LrsSB-J6X7VvdrlZlNw_270.JPG: 480x640 (no detections), 270.7ms
Speed: 1.0ms preprocess, 270.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znBOGPRbDn2697xxYoLcfA_0.JPG: 480x640 (no detections), 274.9ms
Speed: 1.1ms preprocess, 274.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znBOGPRbDn2697xxYoLcfA_90.JPG: 480x640 (no detections), 273.9ms
Speed: 1.0ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znBOGPRbDn2697xxYoLcfA_180.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znBOGPRbDn2697xxYoLcfA_270.JPG: 480x640 (no detections), 277.1ms
Speed: 1.3ms preprocess, 277.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znGJO02rbSTrDMNcx5t8fw_0.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znGJO02rbSTrDMNcx5t8fw_90.JPG: 480x640 (no detections), 268.7ms
Speed: 1.1ms preprocess, 268.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znGJO02rbSTrDMNcx5t8fw_180.JPG: 480x640 (no detections), 267.4ms
Speed: 1.1ms preprocess, 267.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znGJO02rbSTrDMNcx5t8fw_270.JPG: 480x640 (no detections), 274.3ms
Speed: 1.1ms preprocess, 274.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znLaGVkBLHsn8Ho9yw0Iwg_0.JPG: 480x640 (no detections), 275.2ms
Speed: 1.0ms preprocess, 275.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znLaGVkBLHsn8Ho9yw0Iwg_90.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znLaGVkBLHsn8Ho9yw0Iwg_180.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znLaGVkBLHsn8Ho9yw0Iwg_270.JPG: 480x640 (no detections), 271.5ms
Speed: 1.0ms preprocess, 271.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znO75jKz5bkMZJ_lpGJ-dA_0.JPG: 480x640 (no detections), 269.8ms
Speed: 1.0ms preprocess, 269.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znO75jKz5bkMZJ_lpGJ-dA_90.JPG: 480x640 (no detections), 274.5ms
Speed: 1.0ms preprocess, 274.5ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znO75jKz5bkMZJ_lpGJ-dA_180.JPG: 480x640 (no detections), 274.6ms
Speed: 1.0ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znO75jKz5bkMZJ_lpGJ-dA_270.JPG: 480x640 (no detections), 272.6ms
Speed: 1.0ms preprocess, 272.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znUKc_P1fPQGo9pSyWk2Jw_0.JPG: 480x640 (no detections), 273.8ms
Speed: 0.9ms preprocess, 273.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znUKc_P1fPQGo9pSyWk2Jw_90.JPG: 480x640 (no detections), 272.5ms
Speed: 1.0ms preprocess, 272.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znUKc_P1fPQGo9pSyWk2Jw_180.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znUKc_P1fPQGo9pSyWk2Jw_270.JPG: 480x640 (no detections), 272.7ms
Speed: 1.0ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znUsZRTUthLmvSG4M_KEpQ_0.JPG: 480x640 1 Waste, 268.9ms
Speed: 1.1ms preprocess, 268.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znUsZRTUthLmvSG4M_KEpQ_90.JPG: 480x640 (no detections), 270.1ms
Speed: 1.0ms preprocess, 270.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znUsZRTUthLmvSG4M_KEpQ_180.JPG: 480x640 (no detections), 275.5ms
Speed: 1.0ms preprocess, 275.5ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znUsZRTUthLmvSG4M_KEpQ_270.JPG: 480x640 (no detections), 273.2ms
Speed: 1.1ms preprocess, 273.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znVmiZChezFXGgqC1I1QuA_0.JPG: 480x640 (no detections), 272.9ms
Speed: 1.0ms preprocess, 272.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znVmiZChezFXGgqC1I1QuA_90.JPG: 480x640 (no detections), 269.5ms
Speed: 1.1ms preprocess, 269.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znVmiZChezFXGgqC1I1QuA_180.JPG: 480x640 (no detections), 267.2ms
Speed: 1.1ms preprocess, 267.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znVmiZChezFXGgqC1I1QuA_270.JPG: 480x640 (no detections), 267.4ms
Speed: 1.0ms preprocess, 267.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znVmm9icFOa4ZywkNU2WYA_0.JPG: 480x640 (no detections), 272.5ms
Speed: 1.1ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znVmm9icFOa4ZywkNU2WYA_90.JPG: 480x640 (no detections), 272.8ms
Speed: 1.2ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znVmm9icFOa4ZywkNU2WYA_180.JPG: 480x640 (no detections), 278.4ms
Speed: 1.2ms preprocess, 278.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znVmm9icFOa4ZywkNU2WYA_270.JPG: 480x640 1 Waste, 270.3ms
Speed: 1.3ms preprocess, 270.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zn_tuuN9x9rPQhBRpfyF9Q_0.JPG: 480x640 1 Waste, 267.9ms
Speed: 1.1ms preprocess, 267.9ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zn_tuuN9x9rPQhBRpfyF9Q_90.JPG: 480x640 (no detections), 273.7ms

Speed: 1.0ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zn_tuuN9x9rPQhBRpfyF9Q_180.JPG: 480x640 1 Waste, 268.9ms
Speed: 1.1ms preprocess, 268.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zn_tuuN9x9rPQhBRpfyF9Q_270.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znaudzkf9fpOpyP3zCgNrw_0.JPG: 480x640 (no detections), 271.7ms
Speed: 1.0ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znaudzkf9fpOpyP3zCgNrw_90.JPG: 480x640 (no detections), 267.9ms
Speed: 1.1ms preprocess, 267.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znaudzkf9fpOpyP3zCgNrw_180.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znaudzkf9fpOpyP3zCgNrw_270.JPG: 480x640 (no detections), 273.6ms
Speed: 1.0ms preprocess, 273.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znbVj6upqOfzkcassmc9mQ_0.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znbVj6upqOfzkcassmc9mQ_90.JPG: 480x640 (no detections), 271.0ms
Speed: 0.9ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znbVj6upqOfzkcassmc9mQ_180.JPG: 480x640 (no detections), 270.1ms
Speed: 1.0ms preprocess, 270.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znbVj6upqOfzkcassmc9mQ_270.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znd9lrSv9iqwkuuSm96pVw_0.JPG: 480x640 (no detections), 270.4ms
Speed: 1.1ms preprocess, 270.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znd9lrSv9iqwkuuSm96pVw_90.JPG: 480x640 (no detections), 280.2ms
Speed: 1.6ms preprocess, 280.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znd9lrSv9iqwkuuSm96pVw_180.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znd9lrSv9iqwkuuSm96pVw_270.JPG: 480x640 (no detections), 273.0ms
Speed: 1.0ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zndESOIWVBMUA38MCxcG8Q_0.JPG: 480x640 (no detections), 273.6ms
Speed: 1.1ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zndESOIWVBMUA38MCxcG8Q_90.JPG: 480x640 (no detections), 275.2ms
Speed: 1.2ms preprocess, 275.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zndESOIWVBMUA38MCxcG8Q_180.JPG: 480x640 (no detections), 275.6ms
Speed: 1.1ms preprocess, 275.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zndESOIWVBMUA38MCxcG8Q_270.JPG: 480x640 (no detections), 271.5ms
Speed: 1.1ms preprocess, 271.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zngs8gfG8Dys3NOONEMKpg_0.JPG: 480x640 (no detections), 276.4ms
Speed: 1.0ms preprocess, 276.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zngs8gfG8Dys3NOONEMKpg_90.JPG: 480x640 (no detections), 273.4ms
Speed: 1.1ms preprocess, 273.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zngs8gfG8Dys3NOONEMKpg_180.JPG: 480x640 (no detections), 272.1ms
Speed: 1.1ms preprocess, 272.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zngs8gfG8Dys3NOONEMKpg_270.JPG: 480x640 (no detections), 276.0ms
Speed: 1.1ms preprocess, 276.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zniPwL0cIIAnKkkWUD1kgw_0.JPG: 480x640 (no detections), 329.0ms
Speed: 1.0ms preprocess, 329.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zniPwL0cIIAnKkkWUD1kgw_90.JPG: 480x640 (no detections), 273.9ms
Speed: 1.3ms preprocess, 273.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zniPwL0cIIAnKkkWUD1kgw_180.JPG: 480x640 (no detections), 274.5ms
Speed: 1.1ms preprocess, 274.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/zniPwL0cIIAnKkkWUD1kgw_270.JPG: 480x640 (no detections), 276.4ms
Speed: 1.1ms preprocess, 276.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znjImi1meq3MmLk7fTuRvQ_0.JPG: 480x640 (no detections), 277.8ms
Speed: 1.0ms preprocess, 277.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znjImi1meq3MmLk7fTuRvQ_90.JPG: 480x640 (no detections), 280.7ms
Speed: 1.0ms preprocess, 280.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znjImi1meq3MmLk7fTuRvQ_180.JPG: 480x640 (no detections), 269.4ms
Speed: 1.1ms preprocess, 269.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znjImi1meq3MmLk7fTuRvQ_270.JPG: 480x640 (no detections), 274.2ms
Speed: 1.1ms preprocess, 274.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znlG-b3xqdnOLDT0oK-3MA_0.JPG: 480x640 (no detections), 273.4ms
Speed: 1.1ms preprocess, 273.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znlG-b3xqdnOLDT0oK-3MA_90.JPG: 480x640 (no detections), 275.0ms
Speed: 1.1ms preprocess, 275.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znlG-b3xqdnOLDT0oK-3MA_180.JPG: 480x640 (no detections), 277.1ms
Speed: 1.1ms preprocess, 277.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znlG-b3xqdnOLDT0oK-3MA_270.JPG: 480x640 (no detections), 275.4ms
Speed: 1.2ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znlWjx4dHUtJHIJQtF5CMQ_0.JPG: 480x640 1 Waste, 274.0ms
Speed: 1.1ms preprocess, 274.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znlWjx4dHUtJHIJQtF5CMQ_90.JPG: 480x640 (no detections), 273.2ms
Speed: 1.0ms preprocess, 273.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znlWjx4dHUtJHIJQtF5CMQ_180.JPG: 480x640 (no detections), 268.3ms
Speed: 1.1ms preprocess, 268.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znlWjx4dHUtJHIJQtF5CMQ_270.JPG: 480x640 (no detections), 271.5ms
Speed: 1.1ms preprocess, 271.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znm1vx0oNApUkNNJM6o_Dw_0.JPG: 480x640 (no detections), 271.4ms
Speed: 1.0ms preprocess, 271.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znm1vx0oNApUkNNJM6o_Dw_90.JPG: 480x640 (no detections), 270.7ms
Speed: 1.0ms preprocess, 270.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znm1vx0oNApUkNNJM6o_Dw_180.JPG: 480x640 (no detections), 273.4ms
Speed: 1.1ms preprocess, 273.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znm1vx0oNApUkNNJM6o_Dw_270.JPG: 480x640 (no detections), 275.7ms
Speed: 1.3ms preprocess, 275.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znqBCBqPguD1r7DzMCap7A_0.JPG: 480x640 (no detections), 274.3ms
Speed: 1.1ms preprocess, 274.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znqBCBqPguD1r7DzMCap7A_90.JPG: 480x640 (no detections), 272.1ms
Speed: 1.2ms preprocess, 272.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znqBCBqPguD1r7DzMCap7A_180.JPG: 480x640 (no detections), 273.1ms
Speed: 1.2ms preprocess, 273.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znqBCBqPguD1r7DzMCap7A_270.JPG: 480x640 (no detections), 275.9ms
Speed: 1.1ms preprocess, 275.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znqTXXejlwXNBIlxaBlfdw_0.JPG: 480x640 (no detections), 274.3ms
Speed: 1.1ms preprocess, 274.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znqTXXejlwXNBIlxaBlfdw_90.JPG: 480x640 (no detections), 274.2ms
Speed: 1.1ms preprocess, 274.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znqTXXejlwXNBIlxaBlfdw_180.JPG: 480x640 (no detections), 270.3ms
Speed: 1.1ms preprocess, 270.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znqTXXejlwXNBIlxaBlfdw_270.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znvNhMHFR21gR6M3_rbOXQ_0.JPG: 480x640 (no detections), 273.4ms
Speed: 1.1ms preprocess, 273.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znvNhMHFR21gR6M3_rbOXQ_90.JPG: 480x640 1 Waste, 275.0ms
Speed: 1.0ms preprocess, 275.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znvNhMHFR21gR6M3_rbOXQ_180.JPG: 480x640 (no detections), 274.4ms
Speed: 1.0ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znvNhMHFR21gR6M3_rbOXQ_270.JPG: 480x640 (no detections), 277.8ms
Speed: 1.1ms preprocess, 277.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znwYG8KVVoDpQjDTkG5sug_0.JPG: 480x640 (no detections), 268.9ms
Speed: 1.1ms preprocess, 268.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znwYG8KVVoDpQjDTkG5sug_90.JPG: 480x640 (no detections), 271.6ms
Speed: 1.0ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znwYG8KVVoDpQjDTkG5sug_180.JPG: 480x640 (no detections), 276.8ms
Speed: 1.1ms preprocess, 276.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znwYG8KVVoDpQjDTkG5sug_270.JPG: 480x640 (no detections), 273.1ms
Speed: 1.0ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znxFQQuzwwKEOJjceHsQ4Q_0.JPG: 480x640 (no detections), 271.6ms
Speed: 1.0ms preprocess, 271.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znxFQQuzwwKEOJjceHsQ4Q_90.JPG: 480x640 (no detections), 270.0ms
Speed: 1.0ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znxFQQuzwwKEOJjceHsQ4Q_180.JPG: 480x640 (no detections), 273.3ms
Speed: 1.0ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znxFQQuzwwKEOJjceHsQ4Q_270.JPG: 480x640 (no detections), 272.1ms
Speed: 1.1ms preprocess, 272.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znxtY9sequHGB8F111wKYA_0.JPG: 480x640 (no detections), 267.8ms
Speed: 1.1ms preprocess, 267.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znxtY9sequHGB8F111wKYA_90.JPG: 480x640 (no detections), 276.1ms
Speed: 1.0ms preprocess, 276.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znxtY9sequHGB8F111wKYA_180.JPG: 480x640 (no detections), 278.4ms
Speed: 1.2ms preprocess, 278.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/N/znxtY9sequHGB8F111wKYA_270.JPG: 480x640 (no detections), 278.1ms
Speed: 1.1ms preprocess, 278.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zo-w5YOI9ETsA9v-ZPMM-g_0.JPG: 480x640 (no detections), 292.3ms

Speed: 1.2ms preprocess, 292.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zo-w5YOI9ETsA9v-ZPMM-g_90.JPG: 480x640 (no detections), 298.1ms
Speed: 1.1ms preprocess, 298.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zo-w5YOI9ETsA9v-ZPMM-g_180.JPG: 480x640 (no detections), 279.7ms
Speed: 1.2ms preprocess, 279.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zo-w5YOI9ETsA9v-ZPMM-g_270.JPG: 480x640 (no detections), 276.3ms
Speed: 1.1ms preprocess, 276.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zoDEax2aOdQ-VbkRSmXl6Q_0.JPG: 480x640 (no detections), 285.5ms
Speed: 1.2ms preprocess, 285.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zoDEax2aOdQ-VbkRSmXl6Q_90.JPG: 480x640 (no detections), 281.8ms
Speed: 1.2ms preprocess, 281.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zoDEax2aOdQ-VbkRSmXl6Q_180.JPG: 480x640 (no detections), 307.4ms
Speed: 1.0ms preprocess, 307.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zoDEax2aOdQ-VbkRSmXl6Q_270.JPG: 480x640 (no detections), 300.3ms
Speed: 1.9ms preprocess, 300.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zoGWwppEaFtsktOdXW7iNw_0.JPG: 480x640 (no detections), 271.4ms
Speed: 1.5ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zoGWwppEaFtsktOdXW7iNw_90.JPG: 480x640 (no detections), 262.9ms
Speed: 1.1ms preprocess, 262.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zoGWwppEaFtsktOdXW7iNw_180.JPG: 480x640 (no detections), 266.9ms
Speed: 1.0ms preprocess, 266.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zoGWwppEaFtsktOdXW7iNw_270.JPG: 480x640 (no detections), 330.7ms
Speed: 1.1ms preprocess, 330.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zoKFbuEvuml8_j0Na0xIaA_0.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zoKFbuEvuml8_j0Na0xIaA_90.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zoKFbuEvuml8_j0Na0xIaA_180.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zoKFbuEvuml8_j0Na0xIaA_270.JPG: 480x640 (no detections), 297.6ms
Speed: 1.2ms preprocess, 297.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zoP9tk7xM4lGTa_bF3k-fQ_0.JPG: 480x640 (no detections), 288.9ms
Speed: 1.1ms preprocess, 288.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zoP9tk7xM4lGTa_bF3k-fQ_90.JPG: 480x640 (no detections), 279.5ms
Speed: 1.2ms preprocess, 279.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zoP9tk7xM4lGTa_bF3k-fQ_180.JPG: 480x640 (no detections), 263.3ms
Speed: 1.0ms preprocess, 263.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zoP9tk7xM4lGTa_bF3k-fQ_270.JPG: 480x640 (no detections), 269.5ms
Speed: 1.1ms preprocess, 269.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zoPv9inCLfHGT37wc4D_yA_0.JPG: 480x640 (no detections), 270.9ms
Speed: 1.0ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zoPv9inCLfHGT37wc4D_yA_90.JPG: 480x640 1 Waste, 266.8ms
Speed: 1.2ms preprocess, 266.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zoPv9inCLfHGT37wc4D_yA_180.JPG: 480x640 1 Waste, 280.4ms
Speed: 1.2ms preprocess, 280.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zoPv9inCLfHGT37wc4D_yA_270.JPG: 480x640 1 Waste, 288.2ms
Speed: 1.2ms preprocess, 288.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zoSighN0Vhxhb2qCP71-oA_0.JPG: 480x640 (no detections), 282.6ms
Speed: 1.3ms preprocess, 282.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zoSighN0Vhxhb2qCP71-oA_90.JPG: 480x640 (no detections), 277.0ms
Speed: 1.1ms preprocess, 277.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zoSighN0Vhxhb2qCP71-oA_180.JPG: 480x640 (no detections), 285.1ms
Speed: 1.2ms preprocess, 285.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zoSighN0Vhxhb2qCP71-oA_270.JPG: 480x640 (no detections), 286.3ms
Speed: 1.2ms preprocess, 286.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zo_JLPjVarW6fVt6jTHQ1g_0.JPG: 480x640 (no detections), 279.9ms
Speed: 1.1ms preprocess, 279.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zo_JLPjVarW6fVt6jTHQ1g_90.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zo_JLPjVarW6fVt6jTHQ1g_180.JPG: 480x640 (no detections), 276.5ms
Speed: 1.3ms preprocess, 276.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zo_JLPjVarW6fVt6jTHQ1g_270.JPG: 480x640 (no detections), 273.1ms
Speed: 1.0ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zocb3oxop5uy55I2NUuxOw_0.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zocb3oxop5uy55I2NUuxOw_90.JPG: 480x640 (no detections), 277.6ms
Speed: 1.1ms preprocess, 277.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zocb3oxop5uy55I2NUuxOw_180.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zocb3oxop5uy55I2NUuxOw_270.JPG: 480x640 (no detections), 270.7ms
Speed: 1.0ms preprocess, 270.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zod1XoE5Y6mhguKLLzFaNA_0.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zod1XoE5Y6mhguKLLzFaNA_90.JPG: 480x640 (no detections), 270.3ms
Speed: 1.1ms preprocess, 270.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zod1XoE5Y6mhguKLLzFaNA_180.JPG: 480x640 (no detections), 270.9ms
Speed: 1.0ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zod1XoE5Y6mhguKLLzFaNA_270.JPG: 480x640 (no detections), 267.0ms
Speed: 1.0ms preprocess, 267.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zodK2CqzCM3kP0kxNgNlbA_0.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zodK2CqzCM3kP0kxNgNlbA_90.JPG: 480x640 (no detections), 271.8ms
Speed: 1.0ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zodK2CqzCM3kP0kxNgNlbA_180.JPG: 480x640 (no detections), 269.2ms
Speed: 1.0ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zodK2CqzCM3kP0kxNgNlbA_270.JPG: 480x640 (no detections), 272.9ms
Speed: 1.0ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zof-f3_Orcx6s0e7jJ1AIg_0.JPG: 480x640 2 Wastes, 271.6ms
Speed: 1.0ms preprocess, 271.6ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zof-f3_Orcx6s0e7jJ1AIg_90.JPG: 480x640 (no detections), 268.5ms
Speed: 1.1ms preprocess, 268.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zof-f3_Orcx6s0e7jJ1AIg_180.JPG: 480x640 (no detections), 272.2ms
Speed: 1.0ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zof-f3_Orcx6s0e7jJ1AIg_270.JPG: 480x640 (no detections), 276.4ms
Speed: 1.0ms preprocess, 276.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zoi0dzdQF5ncWOWZuhkJsg_0.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zoi0dzdQF5ncWOWZuhkJsg_90.JPG: 480x640 (no detections), 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zoi0dzdQF5ncWOWZuhkJsg_180.JPG: 480x640 (no detections), 271.8ms
Speed: 1.0ms preprocess, 271.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zoi0dzdQF5ncWOWZuhkJsg_270.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zoiE5lnK_DFJN7YmJGrIGw_0.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zoiE5lnK_DFJN7YmJGrIGw_90.JPG: 480x640 (no detections), 266.5ms
Speed: 1.1ms preprocess, 266.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zoiE5lnK_DFJN7YmJGrIGw_180.JPG: 480x640 (no detections), 264.7ms
Speed: 1.1ms preprocess, 264.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zoiE5lnK_DFJN7YmJGrIGw_270.JPG: 480x640 (no detections), 266.3ms
Speed: 1.0ms preprocess, 266.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zojHSlyzbSdjjWoGUgRiHg_0.JPG: 480x640 (no detections), 273.9ms
Speed: 1.0ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zojHSlyzbSdjjWoGUgRiHg_90.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zojHSlyzbSdjjWoGUgRiHg_180.JPG: 480x640 (no detections), 269.8ms
Speed: 1.0ms preprocess, 269.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zojHSlyzbSdjjWoGUgRiHg_270.JPG: 480x640 (no detections), 274.3ms
Speed: 1.1ms preprocess, 274.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zojmEw8XWUJHPfqkw6t0ow_0.JPG: 480x640 (no detections), 272.3ms
Speed: 1.0ms preprocess, 272.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zojmEw8XWUJHPfqkw6t0ow_90.JPG: 480x640 (no detections), 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zojmEw8XWUJHPfqkw6t0ow_180.JPG: 480x640 (no detections), 276.2ms
Speed: 1.0ms preprocess, 276.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/O/zojmEw8XWUJHPfqkw6t0ow_270.JPG: 480x640 (no detections), 272.7ms
Speed: 1.0ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zp4_DShJVcgp35r29ctdlw_0.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zp4_DShJVcgp35r29ctdlw_90.JPG: 480x640 (no detections), 268.5ms
Speed: 1.1ms preprocess, 268.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zp4_DShJVcgp35r29ctdlw_180.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zp4_DShJVcgp35r29ctdlw_270.JPG: 480x640 (no detections), 273.8ms

Speed: 1.0ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zp4tbSEG6gF7qiYYuTl-4A_0.JPG: 480x640 (no detections), 274.0ms
Speed: 1.1ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zp4tbSEG6gF7qiYYuTl-4A_90.JPG: 480x640 (no detections), 275.6ms
Speed: 1.1ms preprocess, 275.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zp4tbSEG6gF7qiYYuTl-4A_180.JPG: 480x640 (no detections), 280.2ms
Speed: 1.1ms preprocess, 280.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zp4tbSEG6gF7qiYYuTl-4A_270.JPG: 480x640 (no detections), 268.5ms
Speed: 1.1ms preprocess, 268.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zp7qTmkD44WDS7dMNUnMgQ_0.JPG: 480x640 (no detections), 268.5ms
Speed: 1.1ms preprocess, 268.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zp7qTmkD44WDS7dMNUnMgQ_90.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zp7qTmkD44WDS7dMNUnMgQ_180.JPG: 480x640 (no detections), 271.6ms
Speed: 1.0ms preprocess, 271.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zp7qTmkD44WDS7dMNUnMgQ_270.JPG: 480x640 (no detections), 304.2ms
Speed: 1.2ms preprocess, 304.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zp8GDFtZvfCGu7PlD7iC5g_0.JPG: 480x640 (no detections), 274.4ms
Speed: 1.2ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zp8GDFtZvfCGu7PlD7iC5g_90.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zp8GDFtZvfCGu7PlD7iC5g_180.JPG: 480x640 (no detections), 274.3ms
Speed: 1.0ms preprocess, 274.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zp8GDFtZvfCGu7PlD7iC5g_270.JPG: 480x640 (no detections), 268.5ms
Speed: 1.1ms preprocess, 268.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpA2wb9mA6RaOFS1TC0w0A_0.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpA2wb9mA6RaOFS1TC0w0A_90.JPG: 480x640 (no detections), 270.2ms
Speed: 1.0ms preprocess, 270.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpA2wb9mA6RaOFS1TC0w0A_180.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpA2wb9mA6RaOFS1TC0w0A_270.JPG: 480x640 (no detections), 334.1ms
Speed: 1.0ms preprocess, 334.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpBcXuit4zV9xp2HqaclTw_0.JPG: 480x640 (no detections), 280.0ms
Speed: 1.1ms preprocess, 280.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpBcXuit4zV9xp2HqaclTw_90.JPG: 480x640 (no detections), 274.2ms
Speed: 1.1ms preprocess, 274.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpBcXuit4zV9xp2HqaclTw_180.JPG: 480x640 (no detections), 312.0ms
Speed: 1.1ms preprocess, 312.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpBcXuit4zV9xp2HqaclTw_270.JPG: 480x640 (no detections), 275.4ms
Speed: 1.3ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpEby2sKzXfkKk6-NXvRcA_0.JPG: 480x640 (no detections), 294.1ms
Speed: 1.1ms preprocess, 294.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpEby2sKzXfkKk6-NXvRcA_90.JPG: 480x640 (no detections), 292.6ms
Speed: 1.0ms preprocess, 292.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpEby2sKzXfkKk6-NXvRcA_180.JPG: 480x640 (no detections), 277.9ms
Speed: 1.3ms preprocess, 277.9ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpEby2sKzXfkKk6-NXvRcA_270.JPG: 480x640 (no detections), 275.6ms
Speed: 1.0ms preprocess, 275.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpFushY6Q2QxK7qifbtlew_0.JPG: 480x640 (no detections), 289.2ms
Speed: 1.0ms preprocess, 289.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpFushY6Q2QxK7qifbtlew_90.JPG: 480x640 (no detections), 287.2ms
Speed: 4.2ms preprocess, 287.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpFushY6Q2QxK7qifbtlew_180.JPG: 480x640 (no detections), 268.4ms
Speed: 1.1ms preprocess, 268.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpFushY6Q2QxK7qifbtlew_270.JPG: 480x640 (no detections), 273.4ms
Speed: 1.0ms preprocess, 273.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpGEtpmP1GrYQ68uXqVfXw_0.JPG: 480x640 (no detections), 273.9ms
Speed: 1.1ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpGEtpmP1GrYQ68uXqVfXw_90.JPG: 480x640 (no detections), 270.1ms
Speed: 1.0ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpGEtpmP1GrYQ68uXqVfXw_180.JPG: 480x640 (no detections), 275.3ms
Speed: 1.0ms preprocess, 275.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpGEtpmP1GrYQ68uXqVfXw_270.JPG: 480x640 (no detections), 272.1ms
Speed: 1.0ms preprocess, 272.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpIUYROkisk20tuvyMdbLQ_0.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpIUYROkisk20tuvyMdbLQ_90.JPG: 480x640 (no detections), 267.9ms
Speed: 1.1ms preprocess, 267.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpIUYROkisk20tuvyMdbLQ_180.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpIUYROkisk20tuvyMdbLQ_270.JPG: 480x640 (no detections), 274.1ms
Speed: 1.2ms preprocess, 274.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpIlY80KsP-XXF19L7kZ3A_0.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpIlY80KsP-XXF19L7kZ3A_90.JPG: 480x640 (no detections), 287.4ms
Speed: 1.1ms preprocess, 287.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpIlY80KsP-XXF19L7kZ3A_180.JPG: 480x640 (no detections), 277.9ms
Speed: 1.1ms preprocess, 277.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpIlY80KsP-XXF19L7kZ3A_270.JPG: 480x640 (no detections), 272.1ms
Speed: 1.1ms preprocess, 272.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpKnP8ggQ1KYdWcpgHFGmg_0.JPG: 480x640 (no detections), 273.7ms
Speed: 1.0ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpKnP8ggQ1KYdWcpgHFGmg_90.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpKnP8ggQ1KYdWcpgHFGmg_180.JPG: 480x640 (no detections), 274.5ms
Speed: 1.1ms preprocess, 274.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpKnP8ggQ1KYdWcpgHFGmg_270.JPG: 480x640 (no detections), 277.6ms
Speed: 1.1ms preprocess, 277.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpMKDnkCmITmrYO1dqiviA_0.JPG: 480x640 (no detections), 302.1ms
Speed: 1.1ms preprocess, 302.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpMKDnkCmITmrYO1dqiviA_90.JPG: 480x640 (no detections), 274.1ms
Speed: 1.2ms preprocess, 274.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpMKDnkCmITmrYO1dqiviA_180.JPG: 480x640 3 Wastes, 269.5ms
Speed: 1.0ms preprocess, 269.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpMKDnkCmITmrYO1dqiviA_270.JPG: 480x640 (no detections), 270.3ms
Speed: 1.2ms preprocess, 270.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpNdKOo2wrcyoCnvYxu8Bw_0.JPG: 480x640 (no detections), 278.4ms
Speed: 1.0ms preprocess, 278.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpNdKOo2wrcyoCnvYxu8Bw_90.JPG: 480x640 (no detections), 271.9ms
Speed: 1.6ms preprocess, 271.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpNdKOo2wrcyoCnvYxu8Bw_180.JPG: 480x640 (no detections), 273.1ms
Speed: 1.1ms preprocess, 273.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpNdKOo2wrcyoCnvYxu8Bw_270.JPG: 480x640 (no detections), 329.4ms
Speed: 1.1ms preprocess, 329.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpOLZcGQDSO-XpfThx4Rkg_0.JPG: 480x640 (no detections), 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpOLZcGQDSO-XpfThx4Rkg_90.JPG: 480x640 1 Waste, 268.8ms
Speed: 1.2ms preprocess, 268.8ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpOLZcGQDSO-XpfThx4Rkg_180.JPG: 480x640 (no detections), 269.4ms
Speed: 1.0ms preprocess, 269.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpOLZcGQDSO-XpfThx4Rkg_270.JPG: 480x640 (no detections), 272.3ms
Speed: 1.1ms preprocess, 272.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpPp1wWdthT0kFncEWbKxQ_0.JPG: 480x640 (no detections), 270.4ms
Speed: 1.3ms preprocess, 270.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpPp1wWdthT0kFncEWbKxQ_90.JPG: 480x640 (no detections), 276.0ms
Speed: 1.2ms preprocess, 276.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpPp1wWdthT0kFncEWbKxQ_180.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpPp1wWdthT0kFncEWbKxQ_270.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpQVDRc2bnNCkPRuRQiniA_0.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpQVDRc2bnNCkPRuRQiniA_90.JPG: 480x640 (no detections), 269.4ms
Speed: 1.2ms preprocess, 269.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpQVDRc2bnNCkPRuRQiniA_180.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpQVDRc2bnNCkPRuRQiniA_270.JPG: 480x640 (no detections), 273.7ms
Speed: 1.3ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpQeLxqGI-UuKQ7XP6zNDw_0.JPG: 480x640 (no detections), 273.9ms
Speed: 1.1ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpQeLxqGI-UuKQ7XP6zNDw_90.JPG: 480x640 1 Waste, 268.8ms
Speed: 1.7ms preprocess, 268.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpQeLxqGI-UuKQ7XP6zNDw_180.JPG: 480x640 (no detections), 275.8ms

Speed: 1.1ms preprocess, 275.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpQeLxqGI-UuKQ7XP6zNDw_270.JPG: 480x640 (no detections), 274.2ms
Speed: 1.0ms preprocess, 274.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpXnbrFhWKxSX9oungkddw_0.JPG: 480x640 (no detections), 275.6ms
Speed: 1.4ms preprocess, 275.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpXnbrFhWKxSX9oungkddw_90.JPG: 480x640 (no detections), 274.0ms
Speed: 1.1ms preprocess, 274.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpXnbrFhWKxSX9oungkddw_180.JPG: 480x640 (no detections), 274.2ms
Speed: 1.2ms preprocess, 274.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpXnbrFhWKxSX9oungkddw_270.JPG: 480x640 (no detections), 276.4ms
Speed: 1.1ms preprocess, 276.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpZ4ENiYF4S3ze7nBx7EFA_0.JPG: 480x640 (no detections), 274.8ms
Speed: 1.2ms preprocess, 274.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpZ4ENiYF4S3ze7nBx7EFA_90.JPG: 480x640 (no detections), 271.7ms
Speed: 1.2ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpZ4ENiYF4S3ze7nBx7EFA_180.JPG: 480x640 (no detections), 274.9ms
Speed: 1.0ms preprocess, 274.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpZ4ENiYF4S3ze7nBx7EFA_270.JPG: 480x640 (no detections), 276.9ms
Speed: 1.1ms preprocess, 276.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpZEdeLNNO5RN-WMSPKZrQ_0.JPG: 480x640 (no detections), 274.3ms
Speed: 1.1ms preprocess, 274.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpZEdeLNNO5RN-WMSPKZrQ_90.JPG: 480x640 (no detections), 275.8ms
Speed: 1.1ms preprocess, 275.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpZEdeLNNO5RN-WMSPKZrQ_180.JPG: 480x640 (no detections), 268.7ms
Speed: 1.1ms preprocess, 268.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpZEdeLNNO5RN-WMSPKZrQ_270.JPG: 480x640 (no detections), 276.3ms
Speed: 1.2ms preprocess, 276.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zp_UQOdYGbON3u02q4yrUg_0.JPG: 480x640 (no detections), 272.3ms
Speed: 1.4ms preprocess, 272.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zp_UQOdYGbON3u02q4yrUg_90.JPG: 480x640 (no detections), 278.1ms
Speed: 1.1ms preprocess, 278.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zp_UQOdYGbON3u02q4yrUg_180.JPG: 480x640 (no detections), 277.8ms
Speed: 1.1ms preprocess, 277.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zp_UQOdYGbON3u02q4yrUg_270.JPG: 480x640 (no detections), 273.1ms
Speed: 1.0ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpa3UIJOj9nlXvY1JtWcQw_0.JPG: 480x640 (no detections), 275.3ms
Speed: 1.1ms preprocess, 275.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpa3UIJOj9nlXvY1JtWcQw_90.JPG: 480x640 (no detections), 276.9ms
Speed: 1.1ms preprocess, 276.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpa3UIJOj9nlXvY1JtWcQw_180.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpa3UIJOj9nlXvY1JtWcQw_270.JPG: 480x640 (no detections), 277.2ms
Speed: 1.1ms preprocess, 277.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zphSM3kWYCSEs9NuAa61-Q_0.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zphSM3kWYCSEs9NuAa61-Q_90.JPG: 480x640 (no detections), 274.8ms
Speed: 1.1ms preprocess, 274.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zphSM3kWYCSEs9NuAa61-Q_180.JPG: 480x640 (no detections), 276.4ms
Speed: 1.1ms preprocess, 276.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zphSM3kWYCSEs9NuAa61-Q_270.JPG: 480x640 (no detections), 273.0ms
Speed: 1.0ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpiPqEWHnvu2sJ2UpKHUgg_0.JPG: 480x640 (no detections), 275.6ms
Speed: 1.1ms preprocess, 275.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpiPqEWHnvu2sJ2UpKHUgg_90.JPG: 480x640 (no detections), 271.4ms
Speed: 1.0ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpiPqEWHnvu2sJ2UpKHUgg_180.JPG: 480x640 (no detections), 274.6ms
Speed: 1.0ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpiPqEWHnvu2sJ2UpKHUgg_270.JPG: 480x640 (no detections), 267.0ms
Speed: 1.2ms preprocess, 267.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpicEc2yZ5uBK8Dz6rrqqg_0.JPG: 480x640 (no detections), 274.8ms
Speed: 1.2ms preprocess, 274.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpicEc2yZ5uBK8Dz6rrqqg_90.JPG: 480x640 (no detections), 274.7ms
Speed: 1.2ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpicEc2yZ5uBK8Dz6rrqqg_180.JPG: 480x640 (no detections), 274.4ms
Speed: 1.1ms preprocess, 274.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpicEc2yZ5uBK8Dz6rrqqg_270.JPG: 480x640 (no detections), 271.8ms
Speed: 1.0ms preprocess, 271.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpjhIOkyy5T1BZw8RgXT0w_0.JPG: 480x640 1 Waste, 273.9ms
Speed: 1.1ms preprocess, 273.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpjhIOkyy5T1BZw8RgXT0w_90.JPG: 480x640 (no detections), 277.5ms
Speed: 1.1ms preprocess, 277.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpjhIOkyy5T1BZw8RgXT0w_180.JPG: 480x640 (no detections), 276.7ms
Speed: 1.1ms preprocess, 276.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpjhIOkyy5T1BZw8RgXT0w_270.JPG: 480x640 (no detections), 268.8ms
Speed: 1.2ms preprocess, 268.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpnzkYz1PfnD5xPrvF5mkA_0.JPG: 480x640 (no detections), 275.4ms
Speed: 1.0ms preprocess, 275.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpnzkYz1PfnD5xPrvF5mkA_90.JPG: 480x640 (no detections), 272.8ms
Speed: 1.3ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpnzkYz1PfnD5xPrvF5mkA_180.JPG: 480x640 (no detections), 277.9ms
Speed: 1.1ms preprocess, 277.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpnzkYz1PfnD5xPrvF5mkA_270.JPG: 480x640 1 Waste, 275.6ms
Speed: 1.2ms preprocess, 275.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zptEAyQEhQeSurZhAGQ1gQ_0.JPG: 480x640 (no detections), 272.9ms
Speed: 1.0ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zptEAyQEhQeSurZhAGQ1gQ_90.JPG: 480x640 1 Waste, 271.1ms
Speed: 1.0ms preprocess, 271.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zptEAyQEhQeSurZhAGQ1gQ_180.JPG: 480x640 (no detections), 271.6ms
Speed: 1.0ms preprocess, 271.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zptEAyQEhQeSurZhAGQ1gQ_270.JPG: 480x640 (no detections), 278.4ms
Speed: 1.1ms preprocess, 278.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpxQXkoVoKXL_X45YIsnZQ_0.JPG: 480x640 (no detections), 272.7ms
Speed: 1.0ms preprocess, 272.7ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpxQXkoVoKXL_X45YIsnZQ_90.JPG: 480x640 (no detections), 291.5ms
Speed: 1.1ms preprocess, 291.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpxQXkoVoKXL_X45YIsnZQ_180.JPG: 480x640 (no detections), 293.9ms
Speed: 1.1ms preprocess, 293.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpxQXkoVoKXL_X45YIsnZQ_270.JPG: 480x640 (no detections), 277.4ms
Speed: 1.3ms preprocess, 277.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpyJu2sCcLilVKZJ3HPc7Q_0.JPG: 480x640 (no detections), 276.9ms
Speed: 1.1ms preprocess, 276.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpyJu2sCcLilVKZJ3HPc7Q_90.JPG: 480x640 (no detections), 277.3ms
Speed: 1.1ms preprocess, 277.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpyJu2sCcLilVKZJ3HPc7Q_180.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpyJu2sCcLilVKZJ3HPc7Q_270.JPG: 480x640 (no detections), 270.5ms
Speed: 1.0ms preprocess, 270.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpyYJm5xFvBKjSuIwE2ImA_0.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpyYJm5xFvBKjSuIwE2ImA_90.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpyYJm5xFvBKjSuIwE2ImA_180.JPG: 480x640 (no detections), 274.2ms
Speed: 1.0ms preprocess, 274.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/P/zpyYJm5xFvBKjSuIwE2ImA_270.JPG: 480x640 (no detections), 336.5ms
Speed: 1.2ms preprocess, 336.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zq2-G-aB_yJOYMkJ2KNkQw_0.JPG: 480x640 (no detections), 273.2ms
Speed: 1.2ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zq2-G-aB_yJOYMkJ2KNkQw_90.JPG: 480x640 (no detections), 279.9ms
Speed: 1.1ms preprocess, 279.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zq2-G-aB_yJOYMkJ2KNkQw_180.JPG: 480x640 (no detections), 278.3ms
Speed: 1.1ms preprocess, 278.3ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zq2-G-aB_yJOYMkJ2KNkQw_270.JPG: 480x640 (no detections), 276.5ms
Speed: 1.0ms preprocess, 276.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zq23WhhVsp8aWpPtWGZW8g_0.JPG: 480x640 (no detections), 272.0ms
Speed: 1.0ms preprocess, 272.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zq23WhhVsp8aWpPtWGZW8g_90.JPG: 480x640 (no detections), 275.4ms
Speed: 1.1ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zq23WhhVsp8aWpPtWGZW8g_180.JPG: 480x640 (no detections), 275.7ms
Speed: 1.1ms preprocess, 275.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zq23WhhVsp8aWpPtWGZW8g_270.JPG: 480x640 (no detections), 283.7ms
Speed: 1.1ms preprocess, 283.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zq3ByeEFZitjkwSXmeJX1Q_0.JPG: 480x640 (no detections), 282.8ms
Speed: 1.2ms preprocess, 282.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zq3ByeEFZitjkwSXmeJX1Q_90.JPG: 480x640 (no detections), 273.0ms

Speed: 1.0ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zq3ByeEFZitjkwSXmeJX1Q_180.JPG: 480x640 (no detections), 276.8ms
Speed: 1.1ms preprocess, 276.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zq3ByeEFZitjkwSXmeJX1Q_270.JPG: 480x640 (no detections), 273.9ms
Speed: 1.2ms preprocess, 273.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zq3Sh2MPNC1dOJu0g9NACw_0.JPG: 480x640 (no detections), 274.7ms
Speed: 1.0ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zq3Sh2MPNC1dOJu0g9NACw_90.JPG: 480x640 (no detections), 263.4ms
Speed: 1.3ms preprocess, 263.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zq3Sh2MPNC1dOJu0g9NACw_180.JPG: 480x640 (no detections), 265.9ms
Speed: 1.1ms preprocess, 265.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zq3Sh2MPNC1dOJu0g9NACw_270.JPG: 480x640 (no detections), 265.8ms
Speed: 1.2ms preprocess, 265.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zq4Rb4c8TxWOS0pkkuv8gg_0.JPG: 480x640 (no detections), 267.7ms
Speed: 1.2ms preprocess, 267.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zq4Rb4c8TxWOS0pkkuv8gg_90.JPG: 480x640 (no detections), 264.1ms
Speed: 1.1ms preprocess, 264.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zq4Rb4c8TxWOS0pkkuv8gg_180.JPG: 480x640 (no detections), 277.2ms
Speed: 1.1ms preprocess, 277.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zq4Rb4c8TxWOS0pkkuv8gg_270.JPG: 480x640 (no detections), 276.9ms
Speed: 1.0ms preprocess, 276.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zq72HQd0-TMhFFdpj1Xbig_0.JPG: 480x640 (no detections), 273.6ms
Speed: 1.2ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zq72HQd0-TMhFFdpj1Xbig_90.JPG: 480x640 (no detections), 268.5ms
Speed: 1.2ms preprocess, 268.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zq72HQd0-TMhFFdpj1Xbig_180.JPG: 480x640 (no detections), 272.6ms
Speed: 1.7ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zq72HQd0-TMhFFdpj1Xbig_270.JPG: 480x640 (no detections), 276.1ms
Speed: 1.2ms preprocess, 276.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zq82-od9OVCxFFPGATI1ZA_0.JPG: 480x640 (no detections), 287.4ms
Speed: 1.4ms preprocess, 287.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zq82-od9OVCxFFPGATI1ZA_90.JPG: 480x640 (no detections), 271.0ms
Speed: 1.1ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zq82-od9OVCxFFPGATI1ZA_180.JPG: 480x640 (no detections), 292.2ms
Speed: 1.0ms preprocess, 292.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zq82-od9OVCxFFPGATI1ZA_270.JPG: 480x640 (no detections), 275.1ms
Speed: 1.8ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqEx7lWanMzAbpB5bnHk6w_0.JPG: 480x640 (no detections), 293.1ms
Speed: 1.1ms preprocess, 293.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqEx7lWanMzAbpB5bnHk6w_90.JPG: 480x640 (no detections), 280.0ms
Speed: 1.2ms preprocess, 280.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqEx7lWanMzAbpB5bnHk6w_180.JPG: 480x640 1 Waste, 275.4ms
Speed: 1.0ms preprocess, 275.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqEx7lWanMzAbpB5bnHk6w_270.JPG: 480x640 (no detections), 275.8ms
Speed: 1.0ms preprocess, 275.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqGEl7C6qOouznOv8p6ZTA_0.JPG: 480x640 (no detections), 291.0ms
Speed: 1.0ms preprocess, 291.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqGEl7C6qOouznOv8p6ZTA_90.JPG: 480x640 1 Waste, 275.5ms
Speed: 1.2ms preprocess, 275.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqGEl7C6qOouznOv8p6ZTA_180.JPG: 480x640 (no detections), 268.8ms
Speed: 1.1ms preprocess, 268.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqGEl7C6qOouznOv8p6ZTA_270.JPG: 480x640 1 Waste, 281.9ms
Speed: 1.1ms preprocess, 281.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqGa2plvEWGAbQUaKeoP2A_0.JPG: 480x640 (no detections), 276.1ms
Speed: 1.0ms preprocess, 276.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqGa2plvEWGAbQUaKeoP2A_90.JPG: 480x640 (no detections), 280.6ms
Speed: 1.2ms preprocess, 280.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqGa2plvEWGAbQUaKeoP2A_180.JPG: 480x640 (no detections), 282.9ms
Speed: 1.1ms preprocess, 282.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqGa2plvEWGAbQUaKeoP2A_270.JPG: 480x640 (no detections), 284.1ms
Speed: 1.1ms preprocess, 284.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqJ1zf5hhEHIw6Pz4JFQqw_0.JPG: 480x640 (no detections), 269.9ms
Speed: 1.4ms preprocess, 269.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqJ1zf5hhEHIw6Pz4JFQqw_90.JPG: 480x640 (no detections), 275.6ms
Speed: 1.0ms preprocess, 275.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqJ1zf5hhEHIw6Pz4JFQqw_180.JPG: 480x640 (no detections), 274.0ms
Speed: 1.1ms preprocess, 274.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqJ1zf5hhEHIw6Pz4JFQqw_270.JPG: 480x640 (no detections), 276.2ms
Speed: 1.0ms preprocess, 276.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqJwdkrN1M2eEe79b5CKIw_0.JPG: 480x640 (no detections), 272.3ms
Speed: 1.0ms preprocess, 272.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqJwdkrN1M2eEe79b5CKIw_90.JPG: 480x640 (no detections), 273.3ms
Speed: 1.0ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqJwdkrN1M2eEe79b5CKIw_180.JPG: 480x640 (no detections), 274.6ms
Speed: 1.1ms preprocess, 274.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqJwdkrN1M2eEe79b5CKIw_270.JPG: 480x640 (no detections), 277.1ms
Speed: 1.1ms preprocess, 277.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqJzAbH1vzVOWe8rneGgyA_0.JPG: 480x640 (no detections), 280.5ms
Speed: 1.0ms preprocess, 280.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqJzAbH1vzVOWe8rneGgyA_90.JPG: 480x640 (no detections), 301.8ms
Speed: 1.3ms preprocess, 301.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqJzAbH1vzVOWe8rneGgyA_180.JPG: 480x640 (no detections), 281.3ms
Speed: 1.2ms preprocess, 281.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqJzAbH1vzVOWe8rneGgyA_270.JPG: 480x640 (no detections), 275.9ms
Speed: 1.2ms preprocess, 275.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqLwcJvRqjCIyXhqTcy63w_0.JPG: 480x640 (no detections), 275.1ms
Speed: 1.0ms preprocess, 275.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqLwcJvRqjCIyXhqTcy63w_90.JPG: 480x640 (no detections), 336.3ms
Speed: 1.1ms preprocess, 336.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqLwcJvRqjCIyXhqTcy63w_180.JPG: 480x640 (no detections), 276.5ms
Speed: 1.1ms preprocess, 276.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqLwcJvRqjCIyXhqTcy63w_270.JPG: 480x640 (no detections), 274.1ms
Speed: 1.0ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqN-cuMYPs1TI2nHFGRWhw_0.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqN-cuMYPs1TI2nHFGRWhw_90.JPG: 480x640 (no detections), 275.7ms
Speed: 1.1ms preprocess, 275.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqN-cuMYPs1TI2nHFGRWhw_180.JPG: 480x640 (no detections), 283.0ms
Speed: 1.3ms preprocess, 283.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqN-cuMYPs1TI2nHFGRWhw_270.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqN6Kgv2NgUVk0Cdz2SoYg_0.JPG: 480x640 (no detections), 271.5ms
Speed: 1.1ms preprocess, 271.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqN6Kgv2NgUVk0Cdz2SoYg_90.JPG: 480x640 (no detections), 274.8ms
Speed: 1.0ms preprocess, 274.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqN6Kgv2NgUVk0Cdz2SoYg_180.JPG: 480x640 (no detections), 277.8ms
Speed: 1.0ms preprocess, 277.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqN6Kgv2NgUVk0Cdz2SoYg_270.JPG: 480x640 (no detections), 274.1ms
Speed: 1.2ms preprocess, 274.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqSeDGkb16CHe7683g4k1g_0.JPG: 480x640 (no detections), 270.7ms
Speed: 1.0ms preprocess, 270.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqSeDGkb16CHe7683g4k1g_90.JPG: 480x640 (no detections), 275.7ms
Speed: 1.0ms preprocess, 275.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqSeDGkb16CHe7683g4k1g_180.JPG: 480x640 (no detections), 276.7ms
Speed: 1.1ms preprocess, 276.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqSeDGkb16CHe7683g4k1g_270.JPG: 480x640 (no detections), 272.8ms
Speed: 1.2ms preprocess, 272.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqU5XavCRh72CS6TLvmqZQ_0.JPG: 480x640 (no detections), 274.6ms
Speed: 1.0ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqU5XavCRh72CS6TLvmqZQ_90.JPG: 480x640 (no detections), 269.1ms
Speed: 1.2ms preprocess, 269.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqU5XavCRh72CS6TLvmqZQ_180.JPG: 480x640 (no detections), 272.3ms
Speed: 1.1ms preprocess, 272.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqU5XavCRh72CS6TLvmqZQ_270.JPG: 480x640 1 Waste, 269.3ms
Speed: 1.0ms preprocess, 269.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqWzS7bddzT56CO7p1vsqg_0.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqWzS7bddzT56CO7p1vsqg_90.JPG: 480x640 (no detections), 273.6ms
Speed: 1.1ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqWzS7bddzT56CO7p1vsqg_180.JPG: 480x640 (no detections), 271.2ms
Speed: 1.1ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqWzS7bddzT56CO7p1vsqg_270.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqbyf4KYUnwJn3G44W8wog_0.JPG: 480x640 (no detections), 268.1ms

Speed: 1.0ms preprocess, 268.1ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqbyf4KYUnwJn3G44W8wog_90.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqbyf4KYUnwJn3G44W8wog_180.JPG: 480x640 (no detections), 268.2ms
Speed: 1.1ms preprocess, 268.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqbyf4KYUnwJn3G44W8wog_270.JPG: 480x640 (no detections), 273.7ms
Speed: 1.0ms preprocess, 273.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqck_0DxEAgLCyKy5WDwjA_0.JPG: 480x640 (no detections), 269.3ms
Speed: 1.1ms preprocess, 269.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqck_0DxEAgLCyKy5WDwjA_90.JPG: 480x640 (no detections), 276.3ms
Speed: 1.0ms preprocess, 276.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqck_0DxEAgLCyKy5WDwjA_180.JPG: 480x640 (no detections), 274.0ms
Speed: 1.0ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqck_0DxEAgLCyKy5WDwjA_270.JPG: 480x640 (no detections), 275.5ms
Speed: 1.0ms preprocess, 275.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqe0BXBa6RDnEEiEkIqpbw_0.JPG: 480x640 (no detections), 272.2ms
Speed: 1.0ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqe0BXBa6RDnEEiEkIqpbw_90.JPG: 480x640 (no detections), 282.8ms
Speed: 1.0ms preprocess, 282.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqe0BXBa6RDnEEiEkIqpbw_180.JPG: 480x640 (no detections), 275.5ms
Speed: 1.1ms preprocess, 275.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqe0BXBa6RDnEEiEkIqpbw_270.JPG: 480x640 (no detections), 271.8ms
Speed: 1.0ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqlWmStTMi9zNoZfzr73eA_0.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqlWmStTMi9zNoZfzr73eA_90.JPG: 480x640 (no detections), 273.9ms
Speed: 1.2ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqlWmStTMi9zNoZfzr73eA_180.JPG: 480x640 (no detections), 272.5ms
Speed: 1.2ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqlWmStTMi9zNoZfzr73eA_270.JPG: 480x640 (no detections), 268.4ms
Speed: 1.1ms preprocess, 268.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqmUFxmHCKy50TGHpXukHw_0.JPG: 480x640 (no detections), 274.9ms
Speed: 1.2ms preprocess, 274.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqmUFxmHCKy50TGHpXukHw_90.JPG: 480x640 (no detections), 270.5ms
Speed: 1.1ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqmUFxmHCKy50TGHpXukHw_180.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqmUFxmHCKy50TGHpXukHw_270.JPG: 480x640 (no detections), 275.6ms
Speed: 1.0ms preprocess, 275.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqpeF3tF50FV5lCf6esy-Q_0.JPG: 480x640 (no detections), 286.4ms
Speed: 1.1ms preprocess, 286.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqpeF3tF50FV5lCf6esy-Q_90.JPG: 480x640 (no detections), 277.1ms
Speed: 1.1ms preprocess, 277.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqpeF3tF50FV5lCf6esy-Q_180.JPG: 480x640 (no detections), 280.2ms
Speed: 1.0ms preprocess, 280.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqpeF3tF50FV5lCf6esy-Q_270.JPG: 480x640 (no detections), 292.2ms
Speed: 4.5ms preprocess, 292.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqsCM8s9yh6Voc5AVFVcFA_0.JPG: 480x640 (no detections), 278.6ms
Speed: 1.1ms preprocess, 278.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqsCM8s9yh6Voc5AVFVcFA_90.JPG: 480x640 (no detections), 287.8ms
Speed: 1.1ms preprocess, 287.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqsCM8s9yh6Voc5AVFVcFA_180.JPG: 480x640 (no detections), 281.8ms
Speed: 1.1ms preprocess, 281.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqsCM8s9yh6Voc5AVFVcFA_270.JPG: 480x640 (no detections), 274.4ms
Speed: 1.1ms preprocess, 274.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqtBm14cCFDgRpz5nLMbLA_0.JPG: 480x640 1 Waste, 273.6ms
Speed: 1.1ms preprocess, 273.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqtBm14cCFDgRpz5nLMbLA_90.JPG: 480x640 (no detections), 272.8ms
Speed: 1.0ms preprocess, 272.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqtBm14cCFDgRpz5nLMbLA_180.JPG: 480x640 (no detections), 270.8ms
Speed: 1.0ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqtBm14cCFDgRpz5nLMbLA_270.JPG: 480x640 (no detections), 295.4ms
Speed: 1.1ms preprocess, 295.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqtx3cwKjajRVeZU3SrEXw_0.JPG: 480x640 (no detections), 280.9ms
Speed: 1.2ms preprocess, 280.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqtx3cwKjajRVeZU3SrEXw_90.JPG: 480x640 (no detections), 269.0ms
Speed: 1.0ms preprocess, 269.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqtx3cwKjajRVeZU3SrEXw_180.JPG: 480x640 (no detections), 275.8ms
Speed: 1.0ms preprocess, 275.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqtx3cwKjajRVeZU3SrEXw_270.JPG: 480x640 (no detections), 300.8ms
Speed: 1.2ms preprocess, 300.8ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqvG2w06Q8GjsMRpf0_fEw_0.JPG: 480x640 (no detections), 287.1ms
Speed: 1.8ms preprocess, 287.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqvG2w06Q8GjsMRpf0_fEw_90.JPG: 480x640 (no detections), 285.9ms
Speed: 1.1ms preprocess, 285.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqvG2w06Q8GjsMRpf0_fEw_180.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqvG2w06Q8GjsMRpf0_fEw_270.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqyKzZGUdr6akGyfpe8Ing_0.JPG: 480x640 (no detections), 267.4ms
Speed: 1.1ms preprocess, 267.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqyKzZGUdr6akGyfpe8Ing_90.JPG: 480x640 (no detections), 268.9ms
Speed: 1.1ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqyKzZGUdr6akGyfpe8Ing_180.JPG: 480x640 (no detections), 272.0ms
Speed: 1.1ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Q/zqyKzZGUdr6akGyfpe8Ing_270.JPG: 480x640 (no detections), 274.6ms
Speed: 1.1ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zr1oYHAQyEuTwEHDxKEudA_0.JPG: 480x640 (no detections), 274.8ms
Speed: 1.1ms preprocess, 274.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zr1oYHAQyEuTwEHDxKEudA_90.JPG: 480x640 (no detections), 269.2ms
Speed: 1.0ms preprocess, 269.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zr1oYHAQyEuTwEHDxKEudA_180.JPG: 480x640 (no detections), 296.2ms
Speed: 1.0ms preprocess, 296.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zr1oYHAQyEuTwEHDxKEudA_270.JPG: 480x640 (no detections), 286.1ms
Speed: 1.1ms preprocess, 286.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zr3Yl2C5lyp9K5ULmaouaQ_0.JPG: 480x640 (no detections), 278.0ms
Speed: 1.1ms preprocess, 278.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zr3Yl2C5lyp9K5ULmaouaQ_90.JPG: 480x640 (no detections), 341.9ms
Speed: 1.4ms preprocess, 341.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zr3Yl2C5lyp9K5ULmaouaQ_180.JPG: 480x640 (no detections), 296.2ms
Speed: 1.3ms preprocess, 296.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zr3Yl2C5lyp9K5ULmaouaQ_270.JPG: 480x640 (no detections), 279.9ms
Speed: 1.6ms preprocess, 279.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zr8IlvFG-C1D3rtuclK2DQ_0.JPG: 480x640 (no detections), 289.6ms
Speed: 1.2ms preprocess, 289.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zr8IlvFG-C1D3rtuclK2DQ_90.JPG: 480x640 (no detections), 304.8ms
Speed: 1.1ms preprocess, 304.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zr8IlvFG-C1D3rtuclK2DQ_180.JPG: 480x640 (no detections), 277.2ms
Speed: 1.3ms preprocess, 277.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zr8IlvFG-C1D3rtuclK2DQ_270.JPG: 480x640 (no detections), 301.1ms
Speed: 1.1ms preprocess, 301.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zr9PcEHmRJg2ltpdqEweQg_0.JPG: 480x640 (no detections), 289.7ms
Speed: 1.1ms preprocess, 289.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zr9PcEHmRJg2ltpdqEweQg_90.JPG: 480x640 (no detections), 307.9ms
Speed: 1.4ms preprocess, 307.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zr9PcEHmRJg2ltpdqEweQg_180.JPG: 480x640 (no detections), 288.4ms
Speed: 1.2ms preprocess, 288.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zr9PcEHmRJg2ltpdqEweQg_270.JPG: 480x640 (no detections), 279.5ms
Speed: 1.0ms preprocess, 279.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zr9PkvTjZmdC6LSeSGPY4Q_0.JPG: 480x640 (no detections), 274.7ms
Speed: 1.1ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zr9PkvTjZmdC6LSeSGPY4Q_90.JPG: 480x640 (no detections), 268.3ms
Speed: 1.1ms preprocess, 268.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zr9PkvTjZmdC6LSeSGPY4Q_180.JPG: 480x640 (no detections), 276.7ms
Speed: 1.4ms preprocess, 276.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zr9PkvTjZmdC6LSeSGPY4Q_270.JPG: 480x640 (no detections), 332.2ms
Speed: 1.0ms preprocess, 332.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrAiac53HrMU_jX2kQuQ-w_0.JPG: 480x640 (no detections), 279.2ms
Speed: 1.2ms preprocess, 279.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrAiac53HrMU_jX2kQuQ-w_90.JPG: 480x640 (no detections), 291.0ms
Speed: 1.1ms preprocess, 291.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrAiac53HrMU_jX2kQuQ-w_180.JPG: 480x640 (no detections), 295.2ms
Speed: 1.2ms preprocess, 295.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrAiac53HrMU_jX2kQuQ-w_270.JPG: 480x640 (no detections), 319.4ms

Speed: 1.6ms preprocess, 319.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrEK_ZaEg-getfzOVXa1JQ_0.JPG: 480x640 (no detections), 288.0ms
Speed: 1.3ms preprocess, 288.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrEK_ZaEg-getfzOVXa1JQ_90.JPG: 480x640 (no detections), 274.2ms
Speed: 1.6ms preprocess, 274.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrEK_ZaEg-getfzOVXa1JQ_180.JPG: 480x640 (no detections), 296.4ms
Speed: 1.2ms preprocess, 296.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrEK_ZaEg-getfzOVXa1JQ_270.JPG: 480x640 (no detections), 284.4ms
Speed: 1.1ms preprocess, 284.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrFJIHRUOLSY9WkauTe6nw_0.JPG: 480x640 (no detections), 274.6ms
Speed: 1.1ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrFJIHRUOLSY9WkauTe6nw_90.JPG: 480x640 (no detections), 304.9ms
Speed: 1.0ms preprocess, 304.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrFJIHRUOLSY9WkauTe6nw_180.JPG: 480x640 (no detections), 279.3ms
Speed: 1.2ms preprocess, 279.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrFJIHRUOLSY9WkauTe6nw_270.JPG: 480x640 (no detections), 274.4ms
Speed: 1.1ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrHX3ck830vc3siB6Bfddw_0.JPG: 480x640 (no detections), 291.0ms
Speed: 1.4ms preprocess, 291.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrHX3ck830vc3siB6Bfddw_90.JPG: 480x640 (no detections), 282.5ms
Speed: 1.0ms preprocess, 282.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrHX3ck830vc3siB6Bfddw_180.JPG: 480x640 (no detections), 273.3ms
Speed: 1.2ms preprocess, 273.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrHX3ck830vc3siB6Bfddw_270.JPG: 480x640 (no detections), 274.7ms
Speed: 1.1ms preprocess, 274.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrIY0N86KGIcZhsTbKc9cg_0.JPG: 480x640 (no detections), 272.1ms
Speed: 1.1ms preprocess, 272.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrIY0N86KGIcZhsTbKc9cg_90.JPG: 480x640 (no detections), 272.1ms
Speed: 1.0ms preprocess, 272.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrIY0N86KGIcZhsTbKc9cg_180.JPG: 480x640 (no detections), 281.6ms
Speed: 1.1ms preprocess, 281.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrIY0N86KGIcZhsTbKc9cg_270.JPG: 480x640 (no detections), 282.0ms
Speed: 1.1ms preprocess, 282.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrLEX8IpgJk2tv9QkdGdag_0.JPG: 480x640 (no detections), 377.0ms
Speed: 1.1ms preprocess, 377.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrLEX8IpgJk2tv9QkdGdag_90.JPG: 480x640 (no detections), 283.5ms
Speed: 1.2ms preprocess, 283.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrLEX8IpgJk2tv9QkdGdag_180.JPG: 480x640 (no detections), 274.1ms
Speed: 1.2ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrLEX8IpgJk2tv9QkdGdag_270.JPG: 480x640 (no detections), 273.6ms
Speed: 1.2ms preprocess, 273.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrNuya3XXnGBNQBrCwwzRw_0.JPG: 480x640 (no detections), 268.2ms
Speed: 1.1ms preprocess, 268.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrNuya3XXnGBNQBrCwwzRw_90.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrNuya3XXnGBNQBrCwwzRw_180.JPG: 480x640 (no detections), 272.4ms
Speed: 1.1ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrNuya3XXnGBNQBrCwwzRw_270.JPG: 480x640 (no detections), 267.7ms
Speed: 1.1ms preprocess, 267.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrQH7W3x90vgpZoa5Sl5jw_0.JPG: 480x640 (no detections), 268.8ms
Speed: 1.1ms preprocess, 268.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrQH7W3x90vgpZoa5Sl5jw_90.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrQH7W3x90vgpZoa5Sl5jw_180.JPG: 480x640 (no detections), 268.2ms
Speed: 1.0ms preprocess, 268.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrQH7W3x90vgpZoa5Sl5jw_270.JPG: 480x640 (no detections), 288.9ms
Speed: 1.2ms preprocess, 288.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrSIMDCne_kxG-eCcq9X7Q_0.JPG: 480x640 (no detections), 273.7ms
Speed: 1.2ms preprocess, 273.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrSIMDCne_kxG-eCcq9X7Q_90.JPG: 480x640 (no detections), 272.0ms
Speed: 1.1ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrSIMDCne_kxG-eCcq9X7Q_180.JPG: 480x640 (no detections), 271.3ms
Speed: 1.0ms preprocess, 271.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrSIMDCne_kxG-eCcq9X7Q_270.JPG: 480x640 1 Waste, 271.3ms
Speed: 1.0ms preprocess, 271.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrZqk9AjUTVKdrEna49YPQ_0.JPG: 480x640 (no detections), 284.2ms
Speed: 1.1ms preprocess, 284.2ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrZqk9AjUTVKdrEna49YPQ_90.JPG: 480x640 (no detections), 283.3ms
Speed: 1.1ms preprocess, 283.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrZqk9AjUTVKdrEna49YPQ_180.JPG: 480x640 (no detections), 273.6ms
Speed: 1.2ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrZqk9AjUTVKdrEna49YPQ_270.JPG: 480x640 (no detections), 274.7ms
Speed: 1.1ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrdCSB189541L4u0ymMbZw_0.JPG: 480x640 (no detections), 272.5ms
Speed: 1.1ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrdCSB189541L4u0ymMbZw_90.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrdCSB189541L4u0ymMbZw_180.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrdCSB189541L4u0ymMbZw_270.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zret4yu2DUOuY2SRw4wcog_0.JPG: 480x640 (no detections), 270.7ms
Speed: 1.0ms preprocess, 270.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zret4yu2DUOuY2SRw4wcog_90.JPG: 480x640 (no detections), 275.8ms
Speed: 1.1ms preprocess, 275.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zret4yu2DUOuY2SRw4wcog_180.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zret4yu2DUOuY2SRw4wcog_270.JPG: 480x640 (no detections), 274.7ms
Speed: 1.2ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrg4_Mlg3DF7WqNp-vBV5g_0.JPG: 480x640 (no detections), 272.0ms
Speed: 1.1ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrg4_Mlg3DF7WqNp-vBV5g_90.JPG: 480x640 (no detections), 277.1ms
Speed: 1.0ms preprocess, 277.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrg4_Mlg3DF7WqNp-vBV5g_180.JPG: 480x640 (no detections), 279.2ms
Speed: 1.2ms preprocess, 279.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrg4_Mlg3DF7WqNp-vBV5g_270.JPG: 480x640 (no detections), 269.1ms
Speed: 1.1ms preprocess, 269.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrjRfUBdZ5tMS5f9jj7f5A_0.JPG: 480x640 (no detections), 270.5ms
Speed: 1.1ms preprocess, 270.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrjRfUBdZ5tMS5f9jj7f5A_90.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrjRfUBdZ5tMS5f9jj7f5A_180.JPG: 480x640 (no detections), 274.0ms
Speed: 1.2ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrjRfUBdZ5tMS5f9jj7f5A_270.JPG: 480x640 (no detections), 269.7ms
Speed: 1.1ms preprocess, 269.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrjqSlF90FjbfEqGqGCoUg_0.JPG: 480x640 (no detections), 274.3ms
Speed: 1.1ms preprocess, 274.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrjqSlF90FjbfEqGqGCoUg_90.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrjqSlF90FjbfEqGqGCoUg_180.JPG: 480x640 (no detections), 269.6ms
Speed: 1.1ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrjqSlF90FjbfEqGqGCoUg_270.JPG: 480x640 (no detections), 274.3ms
Speed: 1.2ms preprocess, 274.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrlY-C4TJdRjDnArdL2qTQ_0.JPG: 480x640 (no detections), 269.5ms
Speed: 1.1ms preprocess, 269.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrlY-C4TJdRjDnArdL2qTQ_90.JPG: 480x640 (no detections), 269.9ms
Speed: 1.2ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrlY-C4TJdRjDnArdL2qTQ_180.JPG: 480x640 (no detections), 267.6ms
Speed: 1.1ms preprocess, 267.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrlY-C4TJdRjDnArdL2qTQ_270.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrpJDjTbL-Uj6lAMoNVMgQ_0.JPG: 480x640 (no detections), 273.6ms
Speed: 1.0ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrpJDjTbL-Uj6lAMoNVMgQ_90.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrpJDjTbL-Uj6lAMoNVMgQ_180.JPG: 480x640 (no detections), 277.1ms
Speed: 1.2ms preprocess, 277.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrpJDjTbL-Uj6lAMoNVMgQ_270.JPG: 480x640 (no detections), 269.3ms
Speed: 1.1ms preprocess, 269.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrpov5T0gLkAEjssbAh0gQ_0.JPG: 480x640 (no detections), 275.8ms
Speed: 1.0ms preprocess, 275.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrpov5T0gLkAEjssbAh0gQ_90.JPG: 480x640 (no detections), 269.6ms
Speed: 1.0ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrpov5T0gLkAEjssbAh0gQ_180.JPG: 480x640 (no detections), 270.9ms

Speed: 1.1ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrpov5T0gLkAEjssbAh0gQ_270.JPG: 480x640 (no detections), 271.7ms
Speed: 1.2ms preprocess, 271.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrqIWwiwvOwKh8a_XotSxw_0.JPG: 480x640 (no detections), 276.8ms
Speed: 1.2ms preprocess, 276.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrqIWwiwvOwKh8a_XotSxw_90.JPG: 480x640 (no detections), 274.4ms
Speed: 1.0ms preprocess, 274.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrqIWwiwvOwKh8a_XotSxw_180.JPG: 480x640 (no detections), 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrqIWwiwvOwKh8a_XotSxw_270.JPG: 480x640 (no detections), 269.4ms
Speed: 1.1ms preprocess, 269.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrqfVWRjwZ549KilkYdNhA_0.JPG: 480x640 (no detections), 273.7ms
Speed: 1.0ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrqfVWRjwZ549KilkYdNhA_90.JPG: 480x640 (no detections), 275.9ms
Speed: 1.1ms preprocess, 275.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrqfVWRjwZ549KilkYdNhA_180.JPG: 480x640 (no detections), 283.3ms
Speed: 1.0ms preprocess, 283.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrqfVWRjwZ549KilkYdNhA_270.JPG: 480x640 (no detections), 277.4ms
Speed: 1.2ms preprocess, 277.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrsOexdejV8iGNBJSTeg7Q_0.JPG: 480x640 (no detections), 275.2ms
Speed: 1.3ms preprocess, 275.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrsOexdejV8iGNBJSTeg7Q_90.JPG: 480x640 (no detections), 272.1ms
Speed: 1.0ms preprocess, 272.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrsOexdejV8iGNBJSTeg7Q_180.JPG: 480x640 (no detections), 275.5ms
Speed: 1.1ms preprocess, 275.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrsOexdejV8iGNBJSTeg7Q_270.JPG: 480x640 (no detections), 275.4ms
Speed: 1.7ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrw5j4kFNvALPtdCz0u5OQ_0.JPG: 480x640 (no detections), 274.7ms
Speed: 1.2ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrw5j4kFNvALPtdCz0u5OQ_90.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrw5j4kFNvALPtdCz0u5OQ_180.JPG: 480x640 (no detections), 270.9ms
Speed: 1.0ms preprocess, 270.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/r/zrw5j4kFNvALPtdCz0u5OQ_270.JPG: 480x640 (no detections), 280.5ms
Speed: 1.1ms preprocess, 280.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zs14Y6quLYrbDjTtrI7rPA_0.JPG: 480x640 (no detections), 273.1ms
Speed: 1.2ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zs14Y6quLYrbDjTtrI7rPA_90.JPG: 480x640 (no detections), 276.8ms
Speed: 1.2ms preprocess, 276.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zs14Y6quLYrbDjTtrI7rPA_180.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zs14Y6quLYrbDjTtrI7rPA_270.JPG: 480x640 (no detections), 273.2ms
Speed: 1.3ms preprocess, 273.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zs27-D3Hz-KHCRqIgbt5vg_0.JPG: 480x640 (no detections), 330.3ms
Speed: 1.1ms preprocess, 330.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zs27-D3Hz-KHCRqIgbt5vg_90.JPG: 480x640 (no detections), 276.8ms
Speed: 1.4ms preprocess, 276.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zs27-D3Hz-KHCRqIgbt5vg_180.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zs27-D3Hz-KHCRqIgbt5vg_270.JPG: 480x640 (no detections), 273.6ms
Speed: 1.0ms preprocess, 273.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zs4pTX7yfgr2Tt5yqmoXqA_0.JPG: 480x640 (no detections), 271.1ms
Speed: 1.2ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zs4pTX7yfgr2Tt5yqmoXqA_90.JPG: 480x640 (no detections), 273.9ms
Speed: 1.0ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zs4pTX7yfgr2Tt5yqmoXqA_180.JPG: 480x640 2 Wastes, 284.9ms
Speed: 1.1ms preprocess, 284.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zs4pTX7yfgr2Tt5yqmoXqA_270.JPG: 480x640 (no detections), 295.9ms
Speed: 1.1ms preprocess, 295.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zs6Qm3xW1kNUThWOU2TL7A_0.JPG: 480x640 (no detections), 312.8ms
Speed: 1.2ms preprocess, 312.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zs6Qm3xW1kNUThWOU2TL7A_90.JPG: 480x640 (no detections), 356.0ms
Speed: 1.2ms preprocess, 356.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zs6Qm3xW1kNUThWOU2TL7A_180.JPG: 480x640 (no detections), 306.7ms
Speed: 1.7ms preprocess, 306.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zs6Qm3xW1kNUThWOU2TL7A_270.JPG: 480x640 (no detections), 312.2ms
Speed: 1.2ms preprocess, 312.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsA2oXZ7eFhe7Oqh0M21ww_0.JPG: 480x640 (no detections), 273.8ms
Speed: 1.2ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsA2oXZ7eFhe7Oqh0M21ww_90.JPG: 480x640 (no detections), 294.6ms
Speed: 1.4ms preprocess, 294.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsA2oXZ7eFhe7Oqh0M21ww_180.JPG: 480x640 (no detections), 274.5ms
Speed: 1.0ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsA2oXZ7eFhe7Oqh0M21ww_270.JPG: 480x640 (no detections), 286.1ms
Speed: 1.2ms preprocess, 286.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsC84_9G4aVP4l5blM0vug_0.JPG: 480x640 (no detections), 278.6ms
Speed: 1.2ms preprocess, 278.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsC84_9G4aVP4l5blM0vug_90.JPG: 480x640 (no detections), 282.5ms
Speed: 1.2ms preprocess, 282.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsC84_9G4aVP4l5blM0vug_180.JPG: 480x640 (no detections), 284.7ms
Speed: 1.4ms preprocess, 284.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsC84_9G4aVP4l5blM0vug_270.JPG: 480x640 (no detections), 291.5ms
Speed: 1.3ms preprocess, 291.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsDA_jeXHmzRSQr3ZeITIA_0.JPG: 480x640 (no detections), 281.6ms
Speed: 1.1ms preprocess, 281.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsDA_jeXHmzRSQr3ZeITIA_90.JPG: 480x640 (no detections), 267.4ms
Speed: 1.1ms preprocess, 267.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsDA_jeXHmzRSQr3ZeITIA_180.JPG: 480x640 (no detections), 262.8ms
Speed: 1.0ms preprocess, 262.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsDA_jeXHmzRSQr3ZeITIA_270.JPG: 480x640 (no detections), 260.9ms
Speed: 1.1ms preprocess, 260.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsHtKq5pcIVeS7buhBC9FA_0.JPG: 480x640 3 Wastes, 266.7ms
Speed: 1.2ms preprocess, 266.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsHtKq5pcIVeS7buhBC9FA_90.JPG: 480x640 (no detections), 278.1ms
Speed: 1.1ms preprocess, 278.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsHtKq5pcIVeS7buhBC9FA_180.JPG: 480x640 (no detections), 296.5ms
Speed: 1.8ms preprocess, 296.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsHtKq5pcIVeS7buhBC9FA_270.JPG: 480x640 (no detections), 267.7ms
Speed: 1.2ms preprocess, 267.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsIA88aTA8KWL-WzG6H1qQ_0.JPG: 480x640 (no detections), 298.0ms
Speed: 1.3ms preprocess, 298.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsIA88aTA8KWL-WzG6H1qQ_90.JPG: 480x640 (no detections), 275.9ms
Speed: 1.2ms preprocess, 275.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsIA88aTA8KWL-WzG6H1qQ_180.JPG: 480x640 (no detections), 281.8ms
Speed: 1.1ms preprocess, 281.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsIA88aTA8KWL-WzG6H1qQ_270.JPG: 480x640 (no detections), 300.6ms
Speed: 1.1ms preprocess, 300.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsIexN7OnJNkCNoPSKF89Q_0.JPG: 480x640 (no detections), 285.0ms
Speed: 1.1ms preprocess, 285.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsIexN7OnJNkCNoPSKF89Q_90.JPG: 480x640 (no detections), 304.0ms
Speed: 1.3ms preprocess, 304.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsIexN7OnJNkCNoPSKF89Q_180.JPG: 480x640 (no detections), 282.9ms
Speed: 1.3ms preprocess, 282.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsIexN7OnJNkCNoPSKF89Q_270.JPG: 480x640 (no detections), 299.7ms
Speed: 1.2ms preprocess, 299.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsOKybqnZdvPZyTxTJazkA_0.JPG: 480x640 (no detections), 286.8ms
Speed: 1.2ms preprocess, 286.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsOKybqnZdvPZyTxTJazkA_90.JPG: 480x640 (no detections), 284.1ms
Speed: 1.3ms preprocess, 284.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsOKybqnZdvPZyTxTJazkA_180.JPG: 480x640 (no detections), 283.0ms
Speed: 1.1ms preprocess, 283.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsOKybqnZdvPZyTxTJazkA_270.JPG: 480x640 (no detections), 279.9ms
Speed: 1.2ms preprocess, 279.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsQAHiJOotpDGI_hQmp-oQ_0.JPG: 480x640 (no detections), 303.4ms
Speed: 1.0ms preprocess, 303.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsQAHiJOotpDGI_hQmp-oQ_90.JPG: 480x640 (no detections), 278.5ms
Speed: 1.6ms preprocess, 278.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsQAHiJOotpDGI_hQmp-oQ_180.JPG: 480x640 (no detections), 273.2ms
Speed: 1.1ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsQAHiJOotpDGI_hQmp-oQ_270.JPG: 480x640 (no detections), 268.9ms
Speed: 1.0ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsRNWQLKiQoy5SCnUKvo5Q_0.JPG: 480x640 (no detections), 271.5ms
Speed: 1.0ms preprocess, 271.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsRNWQLKiQoy5SCnUKvo5Q_90.JPG: 480x640 (no detections), 274.2ms

Speed: 1.0ms preprocess, 274.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsRNWQLKiQoy5SCnUKvo5Q_180.JPG: 480x640 (no detections), 276.0ms
Speed: 1.0ms preprocess, 276.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsRNWQLKiQoy5SCnUKvo5Q_270.JPG: 480x640 (no detections), 273.9ms
Speed: 1.2ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsSTv9248hqQvn7gjUBdBg_0.JPG: 480x640 (no detections), 271.4ms
Speed: 1.2ms preprocess, 271.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsSTv9248hqQvn7gjUBdBg_90.JPG: 480x640 (no detections), 270.4ms
Speed: 1.0ms preprocess, 270.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsSTv9248hqQvn7gjUBdBg_180.JPG: 480x640 (no detections), 273.8ms
Speed: 1.0ms preprocess, 273.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsSTv9248hqQvn7gjUBdBg_270.JPG: 480x640 (no detections), 273.1ms
Speed: 1.0ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsUG5H-vTX0KzEfNnsg9Gg_0.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsUG5H-vTX0KzEfNnsg9Gg_90.JPG: 480x640 (no detections), 333.9ms
Speed: 1.1ms preprocess, 333.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsUG5H-vTX0KzEfNnsg9Gg_180.JPG: 480x640 (no detections), 278.9ms
Speed: 1.0ms preprocess, 278.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsUG5H-vTX0KzEfNnsg9Gg_270.JPG: 480x640 (no detections), 282.5ms
Speed: 1.1ms preprocess, 282.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsUjpvmb_VGXV5tg1i16pw_0.JPG: 480x640 (no detections), 273.4ms
Speed: 1.0ms preprocess, 273.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsUjpvmb_VGXV5tg1i16pw_90.JPG: 480x640 (no detections), 271.9ms
Speed: 1.0ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsUjpvmb_VGXV5tg1i16pw_180.JPG: 480x640 (no detections), 275.1ms
Speed: 1.0ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsUjpvmb_VGXV5tg1i16pw_270.JPG: 480x640 (no detections), 275.9ms
Speed: 1.1ms preprocess, 275.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsW8BqerVAWgUg_qGefTRQ_0.JPG: 480x640 (no detections), 275.5ms
Speed: 1.2ms preprocess, 275.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsW8BqerVAWgUg_qGefTRQ_90.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsW8BqerVAWgUg_qGefTRQ_180.JPG: 480x640 (no detections), 283.7ms
Speed: 1.1ms preprocess, 283.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsW8BqerVAWgUg_qGefTRQ_270.JPG: 480x640 (no detections), 286.2ms
Speed: 1.0ms preprocess, 286.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zscAHizDOSWT9QYIX5TFNw_0.JPG: 480x640 (no detections), 275.5ms
Speed: 1.1ms preprocess, 275.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zscAHizDOSWT9QYIX5TFNw_90.JPG: 480x640 (no detections), 296.3ms
Speed: 1.0ms preprocess, 296.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zscAHizDOSWT9QYIX5TFNw_180.JPG: 480x640 (no detections), 277.2ms
Speed: 1.1ms preprocess, 277.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zscAHizDOSWT9QYIX5TFNw_270.JPG: 480x640 (no detections), 279.5ms
Speed: 1.1ms preprocess, 279.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsciAqQactY2ZrlzJQrjsg_0.JPG: 480x640 (no detections), 275.3ms
Speed: 1.0ms preprocess, 275.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsciAqQactY2ZrlzJQrjsg_90.JPG: 480x640 (no detections), 273.1ms
Speed: 1.2ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsciAqQactY2ZrlzJQrjsg_180.JPG: 480x640 (no detections), 271.4ms
Speed: 1.0ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsciAqQactY2ZrlzJQrjsg_270.JPG: 480x640 (no detections), 274.5ms
Speed: 1.1ms preprocess, 274.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zscjF7hUF3NO-OiAQHE31A_0.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zscjF7hUF3NO-OiAQHE31A_90.JPG: 480x640 (no detections), 274.8ms
Speed: 1.0ms preprocess, 274.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zscjF7hUF3NO-OiAQHE31A_180.JPG: 480x640 (no detections), 272.8ms
Speed: 1.2ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zscjF7hUF3NO-OiAQHE31A_270.JPG: 480x640 (no detections), 268.0ms
Speed: 1.1ms preprocess, 268.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsdm7ipzmkfCiJP_LOZucw_0.JPG: 480x640 (no detections), 277.2ms
Speed: 1.1ms preprocess, 277.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsdm7ipzmkfCiJP_LOZucw_90.JPG: 480x640 (no detections), 282.3ms
Speed: 1.3ms preprocess, 282.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsdm7ipzmkfCiJP_LOZucw_180.JPG: 480x640 (no detections), 274.7ms
Speed: 1.2ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsdm7ipzmkfCiJP_LOZucw_270.JPG: 480x640 (no detections), 281.0ms
Speed: 1.1ms preprocess, 281.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsehphawrJxz4OArFOD9LA_0.JPG: 480x640 (no detections), 286.1ms
Speed: 1.1ms preprocess, 286.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsehphawrJxz4OArFOD9LA_90.JPG: 480x640 (no detections), 281.5ms
Speed: 1.2ms preprocess, 281.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsehphawrJxz4OArFOD9LA_180.JPG: 480x640 (no detections), 285.3ms
Speed: 1.1ms preprocess, 285.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsehphawrJxz4OArFOD9LA_270.JPG: 480x640 (no detections), 293.3ms
Speed: 1.1ms preprocess, 293.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsgtu3TZSxGeLZZcLQRIbA_0.JPG: 480x640 (no detections), 278.9ms
Speed: 1.1ms preprocess, 278.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsgtu3TZSxGeLZZcLQRIbA_90.JPG: 480x640 (no detections), 279.3ms
Speed: 1.2ms preprocess, 279.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsgtu3TZSxGeLZZcLQRIbA_180.JPG: 480x640 1 Waste, 284.5ms
Speed: 1.1ms preprocess, 284.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsgtu3TZSxGeLZZcLQRIbA_270.JPG: 480x640 1 Waste, 278.6ms
Speed: 1.0ms preprocess, 278.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsk3uXA9cjNUx73VWoVEMA_0.JPG: 480x640 (no detections), 278.4ms
Speed: 1.1ms preprocess, 278.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsk3uXA9cjNUx73VWoVEMA_90.JPG: 480x640 (no detections), 276.1ms
Speed: 1.2ms preprocess, 276.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsk3uXA9cjNUx73VWoVEMA_180.JPG: 480x640 (no detections), 277.7ms
Speed: 1.1ms preprocess, 277.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsk3uXA9cjNUx73VWoVEMA_270.JPG: 480x640 (no detections), 279.0ms
Speed: 1.1ms preprocess, 279.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zso-d3dkgl510JW_f975VA_0.JPG: 480x640 (no detections), 273.0ms
Speed: 1.0ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zso-d3dkgl510JW_f975VA_90.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zso-d3dkgl510JW_f975VA_180.JPG: 480x640 (no detections), 272.9ms
Speed: 1.0ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zso-d3dkgl510JW_f975VA_270.JPG: 480x640 (no detections), 268.0ms
Speed: 1.1ms preprocess, 268.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsqpB5E8hsmJGUembHzYDg_0.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsqpB5E8hsmJGUembHzYDg_90.JPG: 480x640 (no detections), 325.8ms
Speed: 1.1ms preprocess, 325.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsqpB5E8hsmJGUembHzYDg_180.JPG: 480x640 (no detections), 281.8ms
Speed: 1.1ms preprocess, 281.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsqpB5E8hsmJGUembHzYDg_270.JPG: 480x640 (no detections), 279.3ms
Speed: 1.1ms preprocess, 279.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsr1D89_kg5-kWDlSEJuqA_0.JPG: 480x640 (no detections), 276.3ms
Speed: 1.1ms preprocess, 276.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsr1D89_kg5-kWDlSEJuqA_90.JPG: 480x640 (no detections), 275.2ms
Speed: 1.2ms preprocess, 275.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsr1D89_kg5-kWDlSEJuqA_180.JPG: 480x640 (no detections), 275.0ms
Speed: 1.1ms preprocess, 275.0ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsr1D89_kg5-kWDlSEJuqA_270.JPG: 480x640 (no detections), 272.5ms
Speed: 1.0ms preprocess, 272.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zstnUW-W8vk_CBdh0m6kBQ_0.JPG: 480x640 (no detections), 280.4ms
Speed: 1.1ms preprocess, 280.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zstnUW-W8vk_CBdh0m6kBQ_90.JPG: 480x640 (no detections), 274.2ms
Speed: 1.2ms preprocess, 274.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zstnUW-W8vk_CBdh0m6kBQ_180.JPG: 480x640 (no detections), 301.3ms
Speed: 1.1ms preprocess, 301.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zstnUW-W8vk_CBdh0m6kBQ_270.JPG: 480x640 (no detections), 283.1ms
Speed: 1.4ms preprocess, 283.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsu4jsD8B9m6HB8HplKmCw_0.JPG: 480x640 (no detections), 270.2ms
Speed: 1.0ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsu4jsD8B9m6HB8HplKmCw_90.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsu4jsD8B9m6HB8HplKmCw_180.JPG: 480x640 (no detections), 272.6ms
Speed: 1.2ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsu4jsD8B9m6HB8HplKmCw_270.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsuq1w129t1oLkLLkjprdQ_0.JPG: 480x640 (no detections), 273.1ms

Speed: 1.0ms preprocess, 273.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsuq1w129t1oLkLLkjprdQ_90.JPG: 480x640 (no detections), 273.7ms
Speed: 1.2ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsuq1w129t1oLkLLkjprdQ_180.JPG: 480x640 (no detections), 273.9ms
Speed: 1.1ms preprocess, 273.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsuq1w129t1oLkLLkjprdQ_270.JPG: 480x640 1 Waste, 268.1ms
Speed: 1.1ms preprocess, 268.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsv1B73Nuj0spRRwcMcONg_0.JPG: 480x640 (no detections), 273.9ms
Speed: 1.1ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsv1B73Nuj0spRRwcMcONg_90.JPG: 480x640 (no detections), 273.3ms
Speed: 1.0ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsv1B73Nuj0spRRwcMcONg_180.JPG: 480x640 (no detections), 275.3ms
Speed: 1.1ms preprocess, 275.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/s/zsv1B73Nuj0spRRwcMcONg_270.JPG: 480x640 (no detections), 276.6ms
Speed: 1.1ms preprocess, 276.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zt-XACMbpZypt-p9zQ39-w_0.JPG: 480x640 (no detections), 277.0ms
Speed: 1.1ms preprocess, 277.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zt-XACMbpZypt-p9zQ39-w_90.JPG: 480x640 (no detections), 275.8ms
Speed: 1.0ms preprocess, 275.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zt-XACMbpZypt-p9zQ39-w_180.JPG: 480x640 (no detections), 279.7ms
Speed: 1.0ms preprocess, 279.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zt-XACMbpZypt-p9zQ39-w_270.JPG: 480x640 (no detections), 267.2ms
Speed: 1.1ms preprocess, 267.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zt0Www11kQ5nkKitbvpnWg_0.JPG: 480x640 (no detections), 272.7ms
Speed: 1.0ms preprocess, 272.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zt0Www11kQ5nkKitbvpnWg_90.JPG: 480x640 (no detections), 278.5ms
Speed: 1.1ms preprocess, 278.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zt0Www11kQ5nkKitbvpnWg_180.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zt0Www11kQ5nkKitbvpnWg_270.JPG: 480x640 (no detections), 273.0ms
Speed: 1.0ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zt3ESKZ_X6DyM42zYHZZsA_0.JPG: 480x640 (no detections), 274.2ms
Speed: 1.1ms preprocess, 274.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zt3ESKZ_X6DyM42zYHZZsA_90.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zt3ESKZ_X6DyM42zYHZZsA_180.JPG: 480x640 (no detections), 272.9ms
Speed: 1.3ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zt3ESKZ_X6DyM42zYHZZsA_270.JPG: 480x640 (no detections), 272.4ms
Speed: 1.2ms preprocess, 272.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zt5sm5dJ0YxFSspCPEXPFQ_0.JPG: 480x640 (no detections), 276.4ms
Speed: 1.1ms preprocess, 276.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zt5sm5dJ0YxFSspCPEXPFQ_90.JPG: 480x640 (no detections), 273.0ms
Speed: 1.2ms preprocess, 273.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zt5sm5dJ0YxFSspCPEXPFQ_180.JPG: 480x640 (no detections), 272.3ms
Speed: 1.1ms preprocess, 272.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zt5sm5dJ0YxFSspCPEXPFQ_270.JPG: 480x640 (no detections), 275.5ms
Speed: 1.1ms preprocess, 275.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zt7mFUBIDTbWg6Gk2lb86w_0.JPG: 480x640 (no detections), 272.2ms
Speed: 1.0ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zt7mFUBIDTbWg6Gk2lb86w_90.JPG: 480x640 (no detections), 276.3ms
Speed: 1.1ms preprocess, 276.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zt7mFUBIDTbWg6Gk2lb86w_180.JPG: 480x640 (no detections), 275.0ms
Speed: 1.0ms preprocess, 275.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zt7mFUBIDTbWg6Gk2lb86w_270.JPG: 480x640 (no detections), 271.8ms
Speed: 1.0ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zt9LNEYpFBVnWm8FKkk3Ew_0.JPG: 480x640 (no detections), 269.1ms
Speed: 1.1ms preprocess, 269.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zt9LNEYpFBVnWm8FKkk3Ew_90.JPG: 480x640 (no detections), 269.9ms
Speed: 1.3ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zt9LNEYpFBVnWm8FKkk3Ew_180.JPG: 480x640 (no detections), 278.3ms
Speed: 1.1ms preprocess, 278.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zt9LNEYpFBVnWm8FKkk3Ew_270.JPG: 480x640 (no detections), 269.2ms
Speed: 1.1ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztEI9dP7N-l0HxMBECkLCQ_0.JPG: 480x640 (no detections), 272.1ms
Speed: 1.2ms preprocess, 272.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztEI9dP7N-l0HxMBECkLCQ_90.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztEI9dP7N-l0HxMBECkLCQ_180.JPG: 480x640 (no detections), 270.3ms
Speed: 1.2ms preprocess, 270.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztEI9dP7N-l0HxMBECkLCQ_270.JPG: 480x640 (no detections), 274.6ms
Speed: 1.1ms preprocess, 274.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztFTBSRTeVq_lMS7dB6FIQ_0.JPG: 480x640 (no detections), 275.4ms
Speed: 1.0ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztFTBSRTeVq_lMS7dB6FIQ_90.JPG: 480x640 (no detections), 277.0ms
Speed: 1.3ms preprocess, 277.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztFTBSRTeVq_lMS7dB6FIQ_180.JPG: 480x640 (no detections), 274.5ms
Speed: 1.5ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztFTBSRTeVq_lMS7dB6FIQ_270.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztHV_l2GoViJEbhWLW4FRA_0.JPG: 480x640 (no detections), 272.1ms
Speed: 1.2ms preprocess, 272.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztHV_l2GoViJEbhWLW4FRA_90.JPG: 480x640 (no detections), 269.8ms
Speed: 1.1ms preprocess, 269.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztHV_l2GoViJEbhWLW4FRA_180.JPG: 480x640 (no detections), 326.0ms
Speed: 1.2ms preprocess, 326.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztHV_l2GoViJEbhWLW4FRA_270.JPG: 480x640 (no detections), 274.6ms
Speed: 1.1ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztJcCLxkzjWHb8hO_hw6mA_0.JPG: 480x640 (no detections), 275.6ms
Speed: 1.1ms preprocess, 275.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztJcCLxkzjWHb8hO_hw6mA_90.JPG: 480x640 (no detections), 279.3ms
Speed: 1.9ms preprocess, 279.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztJcCLxkzjWHb8hO_hw6mA_180.JPG: 480x640 (no detections), 274.2ms
Speed: 1.1ms preprocess, 274.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztJcCLxkzjWHb8hO_hw6mA_270.JPG: 480x640 (no detections), 273.1ms
Speed: 1.2ms preprocess, 273.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztPZXGaojR2HsSCKNJ2WCQ_0.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztPZXGaojR2HsSCKNJ2WCQ_90.JPG: 480x640 (no detections), 337.1ms
Speed: 1.1ms preprocess, 337.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztPZXGaojR2HsSCKNJ2WCQ_180.JPG: 480x640 (no detections), 273.5ms
Speed: 1.2ms preprocess, 273.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztPZXGaojR2HsSCKNJ2WCQ_270.JPG: 480x640 (no detections), 270.0ms
Speed: 1.0ms preprocess, 270.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztRBSsJDKX8ZrepAFKD9HQ_0.JPG: 480x640 (no detections), 269.8ms
Speed: 1.0ms preprocess, 269.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztRBSsJDKX8ZrepAFKD9HQ_90.JPG: 480x640 (no detections), 272.4ms
Speed: 1.0ms preprocess, 272.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztRBSsJDKX8ZrepAFKD9HQ_180.JPG: 480x640 (no detections), 268.6ms
Speed: 1.1ms preprocess, 268.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztRBSsJDKX8ZrepAFKD9HQ_270.JPG: 480x640 (no detections), 269.2ms
Speed: 1.0ms preprocess, 269.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztSBpLaVtvES_PfW-DbKKA_0.JPG: 480x640 (no detections), 271.5ms
Speed: 1.0ms preprocess, 271.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztSBpLaVtvES_PfW-DbKKA_90.JPG: 480x640 (no detections), 280.3ms
Speed: 1.0ms preprocess, 280.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztSBpLaVtvES_PfW-DbKKA_180.JPG: 480x640 (no detections), 275.7ms
Speed: 1.3ms preprocess, 275.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztSBpLaVtvES_PfW-DbKKA_270.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztTDIXGp4oh8T3z3mq6n2Q_0.JPG: 480x640 (no detections), 276.7ms
Speed: 1.0ms preprocess, 276.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztTDIXGp4oh8T3z3mq6n2Q_90.JPG: 480x640 1 Waste, 274.4ms
Speed: 1.1ms preprocess, 274.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztTDIXGp4oh8T3z3mq6n2Q_180.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztTDIXGp4oh8T3z3mq6n2Q_270.JPG: 480x640 (no detections), 272.0ms
Speed: 1.1ms preprocess, 272.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztUPQfZuzGU0OIcdPvWHkQ_0.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztUPQfZuzGU0OIcdPvWHkQ_90.JPG: 480x640 (no detections), 273.2ms
Speed: 1.2ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztUPQfZuzGU0OIcdPvWHkQ_180.JPG: 480x640 (no detections), 278.6ms
Speed: 1.2ms preprocess, 278.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztUPQfZuzGU0OIcdPvWHkQ_270.JPG: 480x640 (no detections), 277.5ms

Speed: 1.0ms preprocess, 277.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztVd4REw9vQh0IvYVcv6Xg_0.JPG: 480x640 (no detections), 273.7ms
Speed: 1.2ms preprocess, 273.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztVd4REw9vQh0IvYVcv6Xg_90.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztVd4REw9vQh0IvYVcv6Xg_180.JPG: 480x640 (no detections), 274.8ms
Speed: 1.1ms preprocess, 274.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztVd4REw9vQh0IvYVcv6Xg_270.JPG: 480x640 (no detections), 272.4ms
Speed: 1.1ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztXQaq4NklAfggJQ0eVcGA_0.JPG: 480x640 (no detections), 277.3ms
Speed: 1.1ms preprocess, 277.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztXQaq4NklAfggJQ0eVcGA_90.JPG: 480x640 (no detections), 281.8ms
Speed: 1.0ms preprocess, 281.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztXQaq4NklAfggJQ0eVcGA_180.JPG: 480x640 (no detections), 274.0ms
Speed: 1.1ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztXQaq4NklAfggJQ0eVcGA_270.JPG: 480x640 (no detections), 272.9ms
Speed: 1.1ms preprocess, 272.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztYJMxYw2gh31evmDhADZA_0.JPG: 480x640 (no detections), 273.2ms
Speed: 1.0ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztYJMxYw2gh31evmDhADZA_90.JPG: 480x640 (no detections), 273.6ms
Speed: 1.0ms preprocess, 273.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztYJMxYw2gh31evmDhADZA_180.JPG: 480x640 (no detections), 268.1ms
Speed: 1.1ms preprocess, 268.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztYJMxYw2gh31evmDhADZA_270.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztZcXMrNtRFM67TCH13Q9A_0.JPG: 480x640 (no detections), 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztZcXMrNtRFM67TCH13Q9A_90.JPG: 480x640 (no detections), 267.7ms
Speed: 1.1ms preprocess, 267.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztZcXMrNtRFM67TCH13Q9A_180.JPG: 480x640 (no detections), 270.6ms
Speed: 1.0ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztZcXMrNtRFM67TCH13Q9A_270.JPG: 480x640 (no detections), 272.4ms
Speed: 1.1ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zteVFLKS5yQyo8utuIL-Vg_0.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zteVFLKS5yQyo8utuIL-Vg_90.JPG: 480x640 (no detections), 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zteVFLKS5yQyo8utuIL-Vg_180.JPG: 480x640 (no detections), 274.2ms
Speed: 1.4ms preprocess, 274.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zteVFLKS5yQyo8utuIL-Vg_270.JPG: 480x640 (no detections), 274.2ms
Speed: 1.0ms preprocess, 274.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zti0R-4WEBt8aRdXAY_jHA_0.JPG: 480x640 (no detections), 275.0ms
Speed: 1.1ms preprocess, 275.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zti0R-4WEBt8aRdXAY_jHA_90.JPG: 480x640 (no detections), 273.2ms
Speed: 1.1ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zti0R-4WEBt8aRdXAY_jHA_180.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/zti0R-4WEBt8aRdXAY_jHA_270.JPG: 480x640 (no detections), 273.4ms
Speed: 1.0ms preprocess, 273.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztl6jPQzop9L6Isrf70jFA_0.JPG: 480x640 (no detections), 274.6ms
Speed: 1.0ms preprocess, 274.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztl6jPQzop9L6Isrf70jFA_90.JPG: 480x640 (no detections), 273.0ms
Speed: 1.0ms preprocess, 273.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztl6jPQzop9L6Isrf70jFA_180.JPG: 480x640 1 Waste, 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztl6jPQzop9L6Isrf70jFA_270.JPG: 480x640 (no detections), 272.5ms
Speed: 1.1ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztlR4mkhcJDBYCjeDSUr_w_0.JPG: 480x640 (no detections), 273.5ms
Speed: 1.0ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztlR4mkhcJDBYCjeDSUr_w_90.JPG: 480x640 (no detections), 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztlR4mkhcJDBYCjeDSUr_w_180.JPG: 480x640 (no detections), 272.1ms
Speed: 1.0ms preprocess, 272.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztlR4mkhcJDBYCjeDSUr_w_270.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztm5fkpfVtaE7zcKOISVYA_0.JPG: 480x640 (no detections), 274.6ms
Speed: 1.0ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztm5fkpfVtaE7zcKOISVYA_90.JPG: 480x640 (no detections), 291.0ms
Speed: 1.1ms preprocess, 291.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztm5fkpfVtaE7zcKOISVYA_180.JPG: 480x640 (no detections), 275.6ms
Speed: 1.5ms preprocess, 275.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztm5fkpfVtaE7zcKOISVYA_270.JPG: 480x640 (no detections), 293.6ms
Speed: 1.1ms preprocess, 293.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztqV2fkxPcpdyaage1zH1g_0.JPG: 480x640 (no detections), 274.8ms
Speed: 1.2ms preprocess, 274.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztqV2fkxPcpdyaage1zH1g_90.JPG: 480x640 (no detections), 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztqV2fkxPcpdyaage1zH1g_180.JPG: 480x640 (no detections), 274.1ms
Speed: 1.0ms preprocess, 274.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztqV2fkxPcpdyaage1zH1g_270.JPG: 480x640 (no detections), 270.0ms
Speed: 1.1ms preprocess, 270.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztrHnp2DPXyWK5WQpyZt2g_0.JPG: 480x640 (no detections), 275.6ms
Speed: 1.1ms preprocess, 275.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztrHnp2DPXyWK5WQpyZt2g_90.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztrHnp2DPXyWK5WQpyZt2g_180.JPG: 480x640 (no detections), 279.0ms
Speed: 1.1ms preprocess, 279.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztrHnp2DPXyWK5WQpyZt2g_270.JPG: 480x640 (no detections), 279.6ms
Speed: 1.3ms preprocess, 279.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztt6patOoDTfupxQ2z1sGA_0.JPG: 480x640 1 Waste, 271.0ms
Speed: 1.0ms preprocess, 271.0ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztt6patOoDTfupxQ2z1sGA_90.JPG: 480x640 (no detections), 270.4ms
Speed: 1.1ms preprocess, 270.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztt6patOoDTfupxQ2z1sGA_180.JPG: 480x640 (no detections), 271.3ms
Speed: 1.1ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztt6patOoDTfupxQ2z1sGA_270.JPG: 480x640 (no detections), 277.4ms
Speed: 1.1ms preprocess, 277.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztzT3pVpY4yHrHvUWPLwBA_0.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztzT3pVpY4yHrHvUWPLwBA_90.JPG: 480x640 (no detections), 273.0ms
Speed: 1.0ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztzT3pVpY4yHrHvUWPLwBA_180.JPG: 480x640 (no detections), 270.6ms
Speed: 1.2ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/t/ztzT3pVpY4yHrHvUWPLwBA_270.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zu-IaBH6zNmk4SphLZm8fw_0.JPG: 480x640 (no detections), 279.4ms
Speed: 1.2ms preprocess, 279.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zu-IaBH6zNmk4SphLZm8fw_90.JPG: 480x640 (no detections), 277.3ms
Speed: 1.1ms preprocess, 277.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zu-IaBH6zNmk4SphLZm8fw_180.JPG: 480x640 1 Waste, 327.1ms
Speed: 1.0ms preprocess, 327.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zu-IaBH6zNmk4SphLZm8fw_270.JPG: 480x640 1 Waste, 274.7ms
Speed: 1.4ms preprocess, 274.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zu1O2cORvDKEUHp-KfdbAA_0.JPG: 480x640 (no detections), 277.1ms
Speed: 1.1ms preprocess, 277.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zu1O2cORvDKEUHp-KfdbAA_90.JPG: 480x640 (no detections), 274.3ms
Speed: 1.0ms preprocess, 274.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zu1O2cORvDKEUHp-KfdbAA_180.JPG: 480x640 (no detections), 267.9ms
Speed: 1.0ms preprocess, 267.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zu1O2cORvDKEUHp-KfdbAA_270.JPG: 480x640 (no detections), 277.1ms
Speed: 1.1ms preprocess, 277.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zu1zAsi8tHVbbsmLuu1bzQ_0.JPG: 480x640 (no detections), 278.8ms
Speed: 1.2ms preprocess, 278.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zu1zAsi8tHVbbsmLuu1bzQ_90.JPG: 480x640 (no detections), 275.3ms
Speed: 1.1ms preprocess, 275.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zu1zAsi8tHVbbsmLuu1bzQ_180.JPG: 480x640 (no detections), 275.5ms
Speed: 1.1ms preprocess, 275.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zu1zAsi8tHVbbsmLuu1bzQ_270.JPG: 480x640 (no detections), 274.4ms
Speed: 1.0ms preprocess, 274.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zu2NMh55MnfBx8Jw60_m2Q_0.JPG: 480x640 (no detections), 276.6ms
Speed: 1.0ms preprocess, 276.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zu2NMh55MnfBx8Jw60_m2Q_90.JPG: 480x640 (no detections), 274.7ms
Speed: 1.2ms preprocess, 274.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zu2NMh55MnfBx8Jw60_m2Q_180.JPG: 480x640 (no detections), 277.8ms

Speed: 1.0ms preprocess, 277.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zu2NMh55MnfBx8Jw60_m2Q_270.JPG: 480x640 (no detections), 273.4ms
Speed: 1.0ms preprocess, 273.4ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zu4SqySbp7hOpCRMqTUYiA_0.JPG: 480x640 (no detections), 273.2ms
Speed: 1.2ms preprocess, 273.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zu4SqySbp7hOpCRMqTUYiA_90.JPG: 480x640 (no detections), 270.4ms
Speed: 1.2ms preprocess, 270.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zu4SqySbp7hOpCRMqTUYiA_180.JPG: 480x640 (no detections), 348.7ms
Speed: 1.1ms preprocess, 348.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zu4SqySbp7hOpCRMqTUYiA_270.JPG: 480x640 (no detections), 302.0ms
Speed: 2.3ms preprocess, 302.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zu777AqFGCKU-Otf29Jg2Q_0.JPG: 480x640 (no detections), 283.8ms
Speed: 1.1ms preprocess, 283.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zu777AqFGCKU-Otf29Jg2Q_90.JPG: 480x640 (no detections), 289.4ms
Speed: 1.1ms preprocess, 289.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zu777AqFGCKU-Otf29Jg2Q_180.JPG: 480x640 1 Waste, 314.1ms
Speed: 1.2ms preprocess, 314.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zu777AqFGCKU-Otf29Jg2Q_270.JPG: 480x640 (no detections), 276.6ms
Speed: 1.3ms preprocess, 276.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuB-rKPjNG7Sx-BJ4w0s8w_0.JPG: 480x640 (no detections), 265.6ms
Speed: 1.1ms preprocess, 265.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuB-rKPjNG7Sx-BJ4w0s8w_90.JPG: 480x640 (no detections), 266.3ms
Speed: 1.0ms preprocess, 266.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuB-rKPjNG7Sx-BJ4w0s8w_180.JPG: 480x640 (no detections), 270.9ms
Speed: 1.0ms preprocess, 270.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuB-rKPjNG7Sx-BJ4w0s8w_270.JPG: 480x640 (no detections), 268.7ms
Speed: 1.0ms preprocess, 268.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuBUXv6Y4gmvH4BcPqPIUQ_0.JPG: 480x640 (no detections), 274.2ms
Speed: 1.1ms preprocess, 274.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuBUXv6Y4gmvH4BcPqPIUQ_90.JPG: 480x640 1 Waste, 280.9ms
Speed: 1.0ms preprocess, 280.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuBUXv6Y4gmvH4BcPqPIUQ_180.JPG: 480x640 (no detections), 276.8ms
Speed: 1.1ms preprocess, 276.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuBUXv6Y4gmvH4BcPqPIUQ_270.JPG: 480x640 (no detections), 270.2ms
Speed: 1.0ms preprocess, 270.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuBnm1BElAfxk3GucmZ5LA_0.JPG: 480x640 (no detections), 294.4ms
Speed: 1.0ms preprocess, 294.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuBnm1BElAfxk3GucmZ5LA_90.JPG: 480x640 (no detections), 270.4ms
Speed: 1.2ms preprocess, 270.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuBnm1BElAfxk3GucmZ5LA_180.JPG: 480x640 (no detections), 272.7ms
Speed: 1.0ms preprocess, 272.7ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuBnm1BElAfxk3GucmZ5LA_270.JPG: 480x640 (no detections), 271.0ms
Speed: 1.1ms preprocess, 271.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuHe2MLoDOX5v38OOonKZw_0.JPG: 480x640 (no detections), 269.3ms
Speed: 1.0ms preprocess, 269.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuHe2MLoDOX5v38OOonKZw_90.JPG: 480x640 (no detections), 272.3ms
Speed: 1.1ms preprocess, 272.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuHe2MLoDOX5v38OOonKZw_180.JPG: 480x640 (no detections), 269.3ms
Speed: 1.0ms preprocess, 269.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuHe2MLoDOX5v38OOonKZw_270.JPG: 480x640 (no detections), 274.9ms
Speed: 1.1ms preprocess, 274.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuJBCmTE6In3Om6G2-dPng_0.JPG: 480x640 (no detections), 271.9ms
Speed: 1.1ms preprocess, 271.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuJBCmTE6In3Om6G2-dPng_90.JPG: 480x640 (no detections), 276.9ms
Speed: 1.0ms preprocess, 276.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuJBCmTE6In3Om6G2-dPng_180.JPG: 480x640 (no detections), 277.8ms
Speed: 1.3ms preprocess, 277.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuJBCmTE6In3Om6G2-dPng_270.JPG: 480x640 (no detections), 275.6ms
Speed: 1.2ms preprocess, 275.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuKIesMiDdJ1qhNGrgrO-g_0.JPG: 480x640 (no detections), 272.3ms
Speed: 1.1ms preprocess, 272.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuKIesMiDdJ1qhNGrgrO-g_90.JPG: 480x640 (no detections), 273.2ms
Speed: 1.1ms preprocess, 273.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuKIesMiDdJ1qhNGrgrO-g_180.JPG: 480x640 (no detections), 271.3ms
Speed: 1.2ms preprocess, 271.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuKIesMiDdJ1qhNGrgrO-g_270.JPG: 480x640 (no detections), 274.4ms
Speed: 1.0ms preprocess, 274.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuKWK8EZ0QpiT5FfcMaxpQ_0.JPG: 480x640 1 Waste, 275.3ms
Speed: 1.1ms preprocess, 275.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuKWK8EZ0QpiT5FfcMaxpQ_90.JPG: 480x640 (no detections), 275.5ms
Speed: 1.0ms preprocess, 275.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuKWK8EZ0QpiT5FfcMaxpQ_180.JPG: 480x640 (no detections), 281.7ms
Speed: 1.0ms preprocess, 281.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuKWK8EZ0QpiT5FfcMaxpQ_270.JPG: 480x640 1 Waste, 274.6ms
Speed: 1.1ms preprocess, 274.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuN5Hxc5pCZMYMtkSEZiNw_0.JPG: 480x640 (no detections), 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuN5Hxc5pCZMYMtkSEZiNw_90.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuN5Hxc5pCZMYMtkSEZiNw_180.JPG: 480x640 (no detections), 274.1ms
Speed: 1.0ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuN5Hxc5pCZMYMtkSEZiNw_270.JPG: 480x640 (no detections), 345.1ms
Speed: 1.0ms preprocess, 345.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuN7wWJkCssifxjmTjpHzw_0.JPG: 480x640 (no detections), 274.8ms
Speed: 1.1ms preprocess, 274.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuN7wWJkCssifxjmTjpHzw_90.JPG: 480x640 (no detections), 271.7ms
Speed: 1.2ms preprocess, 271.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuN7wWJkCssifxjmTjpHzw_180.JPG: 480x640 (no detections), 275.1ms
Speed: 1.1ms preprocess, 275.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuN7wWJkCssifxjmTjpHzw_270.JPG: 480x640 (no detections), 273.6ms
Speed: 1.1ms preprocess, 273.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuNa-8TX0BLr_etuCQDzRw_0.JPG: 480x640 (no detections), 269.3ms
Speed: 1.0ms preprocess, 269.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuNa-8TX0BLr_etuCQDzRw_90.JPG: 480x640 (no detections), 274.1ms
Speed: 1.0ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuNa-8TX0BLr_etuCQDzRw_180.JPG: 480x640 (no detections), 277.9ms
Speed: 1.1ms preprocess, 277.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuNa-8TX0BLr_etuCQDzRw_270.JPG: 480x640 (no detections), 274.6ms
Speed: 1.1ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuNldSdHP0_5Jg3UhcNqTQ_0.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuNldSdHP0_5Jg3UhcNqTQ_90.JPG: 480x640 (no detections), 279.6ms
Speed: 1.0ms preprocess, 279.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuNldSdHP0_5Jg3UhcNqTQ_180.JPG: 480x640 (no detections), 269.8ms
Speed: 1.1ms preprocess, 269.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuNldSdHP0_5Jg3UhcNqTQ_270.JPG: 480x640 (no detections), 272.1ms
Speed: 1.0ms preprocess, 272.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuUeKF28vGnSR00cDLOL4g_0.JPG: 480x640 (no detections), 276.4ms
Speed: 1.0ms preprocess, 276.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuUeKF28vGnSR00cDLOL4g_90.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuUeKF28vGnSR00cDLOL4g_180.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuUeKF28vGnSR00cDLOL4g_270.JPG: 480x640 (no detections), 271.5ms
Speed: 1.0ms preprocess, 271.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zubK56182jEbIDa-7aCvQw_0.JPG: 480x640 (no detections), 280.3ms
Speed: 1.6ms preprocess, 280.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zubK56182jEbIDa-7aCvQw_90.JPG: 480x640 (no detections), 272.0ms
Speed: 1.1ms preprocess, 272.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zubK56182jEbIDa-7aCvQw_180.JPG: 480x640 (no detections), 280.7ms
Speed: 1.1ms preprocess, 280.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zubK56182jEbIDa-7aCvQw_270.JPG: 480x640 (no detections), 301.8ms
Speed: 1.1ms preprocess, 301.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zud6k2qrWCeHdYVmCA0kyw_0.JPG: 480x640 (no detections), 270.2ms
Speed: 1.2ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zud6k2qrWCeHdYVmCA0kyw_90.JPG: 480x640 (no detections), 276.1ms
Speed: 1.1ms preprocess, 276.1ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zud6k2qrWCeHdYVmCA0kyw_180.JPG: 480x640 (no detections), 273.1ms
Speed: 1.1ms preprocess, 273.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zud6k2qrWCeHdYVmCA0kyw_270.JPG: 480x640 (no detections), 278.4ms
Speed: 1.0ms preprocess, 278.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zufpCuhC7mgKCyyvb8uJrg_0.JPG: 480x640 (no detections), 274.2ms
Speed: 1.2ms preprocess, 274.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zufpCuhC7mgKCyyvb8uJrg_90.JPG: 480x640 (no detections), 274.7ms

Speed: 1.2ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zufpCuhC7mgKCyyvb8uJrg_180.JPG: 480x640 (no detections), 272.0ms
Speed: 1.1ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zufpCuhC7mgKCyyvb8uJrg_270.JPG: 480x640 (no detections), 272.1ms
Speed: 1.0ms preprocess, 272.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zugHg0O_1Uf1aYGKuk0PKw_0.JPG: 480x640 (no detections), 273.7ms
Speed: 1.0ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zugHg0O_1Uf1aYGKuk0PKw_90.JPG: 480x640 (no detections), 268.4ms
Speed: 1.1ms preprocess, 268.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zugHg0O_1Uf1aYGKuk0PKw_180.JPG: 480x640 (no detections), 270.5ms
Speed: 1.2ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zugHg0O_1Uf1aYGKuk0PKw_270.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zugY4zTyIUyVKFcaieGbpA_0.JPG: 480x640 (no detections), 274.3ms
Speed: 1.0ms preprocess, 274.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zugY4zTyIUyVKFcaieGbpA_90.JPG: 480x640 (no detections), 275.0ms
Speed: 1.0ms preprocess, 275.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zugY4zTyIUyVKFcaieGbpA_180.JPG: 480x640 (no detections), 269.3ms
Speed: 1.1ms preprocess, 269.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zugY4zTyIUyVKFcaieGbpA_270.JPG: 480x640 1 Waste, 276.4ms
Speed: 1.2ms preprocess, 276.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zugxrhJ7Z8H6XsIUoCmeag_0.JPG: 480x640 (no detections), 272.1ms
Speed: 1.1ms preprocess, 272.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zugxrhJ7Z8H6XsIUoCmeag_90.JPG: 480x640 (no detections), 268.9ms
Speed: 1.1ms preprocess, 268.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zugxrhJ7Z8H6XsIUoCmeag_180.JPG: 480x640 (no detections), 278.1ms
Speed: 1.0ms preprocess, 278.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zugxrhJ7Z8H6XsIUoCmeag_270.JPG: 480x640 (no detections), 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuhbVYuzqZ4wbzefQmMKsw_0.JPG: 480x640 (no detections), 268.7ms
Speed: 1.1ms preprocess, 268.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuhbVYuzqZ4wbzefQmMKsw_90.JPG: 480x640 (no detections), 272.5ms
Speed: 1.1ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuhbVYuzqZ4wbzefQmMKsw_180.JPG: 480x640 (no detections), 299.4ms
Speed: 1.1ms preprocess, 299.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuhbVYuzqZ4wbzefQmMKsw_270.JPG: 480x640 (no detections), 277.9ms
Speed: 1.0ms preprocess, 277.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zupBGlZ6JGxq-P0OiaYeAg_0.JPG: 480x640 (no detections), 273.6ms
Speed: 1.0ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zupBGlZ6JGxq-P0OiaYeAg_90.JPG: 480x640 (no detections), 270.7ms
Speed: 1.0ms preprocess, 270.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zupBGlZ6JGxq-P0OiaYeAg_180.JPG: 480x640 (no detections), 272.0ms
Speed: 1.0ms preprocess, 272.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zupBGlZ6JGxq-P0OiaYeAg_270.JPG: 480x640 (no detections), 277.1ms
Speed: 1.2ms preprocess, 277.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zupNlZ5rsGsexNUV3HHVfQ_0.JPG: 480x640 (no detections), 262.9ms
Speed: 1.1ms preprocess, 262.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zupNlZ5rsGsexNUV3HHVfQ_90.JPG: 480x640 (no detections), 266.3ms
Speed: 1.1ms preprocess, 266.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zupNlZ5rsGsexNUV3HHVfQ_180.JPG: 480x640 (no detections), 270.0ms
Speed: 1.0ms preprocess, 270.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zupNlZ5rsGsexNUV3HHVfQ_270.JPG: 480x640 (no detections), 268.3ms
Speed: 1.1ms preprocess, 268.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuqjg1bIXva544_Ea6UR3Q_0.JPG: 480x640 (no detections), 273.3ms
Speed: 1.2ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuqjg1bIXva544_Ea6UR3Q_90.JPG: 480x640 (no detections), 269.5ms
Speed: 1.0ms preprocess, 269.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuqjg1bIXva544_Ea6UR3Q_180.JPG: 480x640 (no detections), 275.3ms
Speed: 1.1ms preprocess, 275.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuqjg1bIXva544_Ea6UR3Q_270.JPG: 480x640 (no detections), 270.2ms
Speed: 1.1ms preprocess, 270.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuxv4pbzgG6mQg5HrczDCg_0.JPG: 480x640 (no detections), 266.1ms
Speed: 1.1ms preprocess, 266.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuxv4pbzgG6mQg5HrczDCg_90.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuxv4pbzgG6mQg5HrczDCg_180.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuxv4pbzgG6mQg5HrczDCg_270.JPG: 480x640 1 Waste, 284.5ms
Speed: 1.1ms preprocess, 284.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuzcDSjoJg3Le-sA5WXKLQ_0.JPG: 480x640 (no detections), 271.2ms
Speed: 1.0ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuzcDSjoJg3Le-sA5WXKLQ_90.JPG: 480x640 (no detections), 270.5ms
Speed: 1.1ms preprocess, 270.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuzcDSjoJg3Le-sA5WXKLQ_180.JPG: 480x640 1 Waste, 274.8ms
Speed: 1.1ms preprocess, 274.8ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/U/zuzcDSjoJg3Le-sA5WXKLQ_270.JPG: 480x640 1 Waste, 276.5ms
Speed: 1.1ms preprocess, 276.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zv-QgM-3GUQXeBqiPjuoJg_0.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zv-QgM-3GUQXeBqiPjuoJg_90.JPG: 480x640 (no detections), 276.5ms
Speed: 1.0ms preprocess, 276.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zv-QgM-3GUQXeBqiPjuoJg_180.JPG: 480x640 (no detections), 269.0ms
Speed: 1.1ms preprocess, 269.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zv-QgM-3GUQXeBqiPjuoJg_270.JPG: 480x640 (no detections), 277.1ms
Speed: 1.3ms preprocess, 277.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zv04jnG_IIiGzNfoOpu72Q_0.JPG: 480x640 (no detections), 275.2ms
Speed: 1.1ms preprocess, 275.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zv04jnG_IIiGzNfoOpu72Q_90.JPG: 480x640 (no detections), 270.6ms
Speed: 1.0ms preprocess, 270.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zv04jnG_IIiGzNfoOpu72Q_180.JPG: 480x640 (no detections), 274.1ms
Speed: 1.2ms preprocess, 274.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zv04jnG_IIiGzNfoOpu72Q_270.JPG: 480x640 (no detections), 333.3ms
Speed: 1.2ms preprocess, 333.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zv4uFdaVwboYA2mDJrtjRg_0.JPG: 480x640 (no detections), 274.4ms
Speed: 1.0ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zv4uFdaVwboYA2mDJrtjRg_90.JPG: 480x640 (no detections), 276.2ms
Speed: 1.2ms preprocess, 276.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zv4uFdaVwboYA2mDJrtjRg_180.JPG: 480x640 (no detections), 272.4ms
Speed: 1.2ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zv4uFdaVwboYA2mDJrtjRg_270.JPG: 480x640 (no detections), 272.9ms
Speed: 1.3ms preprocess, 272.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zv5wH8jrOr6OGvZmI_JvwA_0.JPG: 480x640 (no detections), 293.4ms
Speed: 1.0ms preprocess, 293.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zv5wH8jrOr6OGvZmI_JvwA_90.JPG: 480x640 (no detections), 271.1ms
Speed: 1.1ms preprocess, 271.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zv5wH8jrOr6OGvZmI_JvwA_180.JPG: 480x640 (no detections), 282.8ms
Speed: 1.1ms preprocess, 282.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zv5wH8jrOr6OGvZmI_JvwA_270.JPG: 480x640 (no detections), 278.0ms
Speed: 1.0ms preprocess, 278.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zv9DhhVvPPJUBc8frwakeg_0.JPG: 480x640 1 Waste, 272.2ms
Speed: 1.0ms preprocess, 272.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zv9DhhVvPPJUBc8frwakeg_90.JPG: 480x640 (no detections), 280.8ms
Speed: 1.1ms preprocess, 280.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zv9DhhVvPPJUBc8frwakeg_180.JPG: 480x640 (no detections), 271.1ms
Speed: 1.0ms preprocess, 271.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zv9DhhVvPPJUBc8frwakeg_270.JPG: 480x640 (no detections), 266.2ms
Speed: 1.1ms preprocess, 266.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvBN6wBJRWpeFbeKHfHOGw_0.JPG: 480x640 (no detections), 328.0ms
Speed: 1.0ms preprocess, 328.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvBN6wBJRWpeFbeKHfHOGw_90.JPG: 480x640 (no detections), 274.9ms
Speed: 1.0ms preprocess, 274.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvBN6wBJRWpeFbeKHfHOGw_180.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvBN6wBJRWpeFbeKHfHOGw_270.JPG: 480x640 (no detections), 315.3ms
Speed: 1.2ms preprocess, 315.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvBrFwQ9UyE7WGoO-zNclg_0.JPG: 480x640 (no detections), 285.8ms
Speed: 1.2ms preprocess, 285.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvBrFwQ9UyE7WGoO-zNclg_90.JPG: 480x640 (no detections), 280.4ms
Speed: 1.2ms preprocess, 280.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvBrFwQ9UyE7WGoO-zNclg_180.JPG: 480x640 (no detections), 274.6ms
Speed: 1.1ms preprocess, 274.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvBrFwQ9UyE7WGoO-zNclg_270.JPG: 480x640 (no detections), 270.5ms
Speed: 1.1ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvBwUbjKcNrvh6_J7xtrQg_0.JPG: 480x640 (no detections), 269.6ms

Speed: 1.0ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvBwUbjKcNrvh6_J7xtrQg_90.JPG: 480x640 (no detections), 270.6ms
Speed: 1.0ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvBwUbjKcNrvh6_J7xtrQg_180.JPG: 480x640 (no detections), 276.2ms
Speed: 1.1ms preprocess, 276.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvBwUbjKcNrvh6_J7xtrQg_270.JPG: 480x640 (no detections), 308.1ms
Speed: 1.2ms preprocess, 308.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvG7icNXueBoFjfz6p9Aew_0.JPG: 480x640 (no detections), 274.2ms
Speed: 1.2ms preprocess, 274.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvG7icNXueBoFjfz6p9Aew_90.JPG: 480x640 (no detections), 277.8ms
Speed: 1.2ms preprocess, 277.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvG7icNXueBoFjfz6p9Aew_180.JPG: 480x640 (no detections), 277.6ms
Speed: 1.2ms preprocess, 277.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvG7icNXueBoFjfz6p9Aew_270.JPG: 480x640 (no detections), 290.2ms
Speed: 1.4ms preprocess, 290.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvLVJbNQ7b2VDNReooBBlA_0.JPG: 480x640 (no detections), 312.0ms
Speed: 1.2ms preprocess, 312.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvLVJbNQ7b2VDNReooBBlA_90.JPG: 480x640 (no detections), 284.6ms
Speed: 1.1ms preprocess, 284.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvLVJbNQ7b2VDNReooBBlA_180.JPG: 480x640 (no detections), 288.9ms
Speed: 1.4ms preprocess, 288.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvLVJbNQ7b2VDNReooBBlA_270.JPG: 480x640 (no detections), 272.7ms
Speed: 1.1ms preprocess, 272.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvLcR497EKlM3smEDE2YCw_0.JPG: 480x640 (no detections), 280.6ms
Speed: 1.6ms preprocess, 280.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvLcR497EKlM3smEDE2YCw_90.JPG: 480x640 (no detections), 281.5ms
Speed: 1.3ms preprocess, 281.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvLcR497EKlM3smEDE2YCw_180.JPG: 480x640 (no detections), 272.0ms
Speed: 1.4ms preprocess, 272.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvLcR497EKlM3smEDE2YCw_270.JPG: 480x640 (no detections), 294.0ms
Speed: 1.1ms preprocess, 294.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvQ5UkHOKWKZLp0JPj7nBA_0.JPG: 480x640 (no detections), 272.0ms
Speed: 1.1ms preprocess, 272.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvQ5UkHOKWKZLp0JPj7nBA_90.JPG: 480x640 (no detections), 271.8ms
Speed: 1.0ms preprocess, 271.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvQ5UkHOKWKZLp0JPj7nBA_180.JPG: 480x640 (no detections), 277.2ms
Speed: 1.0ms preprocess, 277.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvQ5UkHOKWKZLp0JPj7nBA_270.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvSuCsvhMZEsOd2ciZvFRQ_0.JPG: 480x640 (no detections), 274.0ms
Speed: 1.1ms preprocess, 274.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvSuCsvhMZEsOd2ciZvFRQ_90.JPG: 480x640 (no detections), 285.2ms
Speed: 1.1ms preprocess, 285.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvSuCsvhMZEsOd2ciZvFRQ_180.JPG: 480x640 (no detections), 296.7ms
Speed: 1.4ms preprocess, 296.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvSuCsvhMZEsOd2ciZvFRQ_270.JPG: 480x640 (no detections), 275.5ms
Speed: 1.1ms preprocess, 275.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvWRuJqWsd4isJfg_0tTrQ_0.JPG: 480x640 (no detections), 281.1ms
Speed: 1.0ms preprocess, 281.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvWRuJqWsd4isJfg_0tTrQ_90.JPG: 480x640 (no detections), 268.2ms
Speed: 1.1ms preprocess, 268.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvWRuJqWsd4isJfg_0tTrQ_180.JPG: 480x640 (no detections), 278.2ms
Speed: 1.0ms preprocess, 278.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvWRuJqWsd4isJfg_0tTrQ_270.JPG: 480x640 (no detections), 272.4ms
Speed: 1.1ms preprocess, 272.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvYoO9Ybx3ABNZnMIjQVXQ_0.JPG: 480x640 (no detections), 271.2ms
Speed: 1.2ms preprocess, 271.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvYoO9Ybx3ABNZnMIjQVXQ_90.JPG: 480x640 (no detections), 280.8ms
Speed: 1.1ms preprocess, 280.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvYoO9Ybx3ABNZnMIjQVXQ_180.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvYoO9Ybx3ABNZnMIjQVXQ_270.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvZWPKXBd1aMmg1zft9bAg_0.JPG: 480x640 (no detections), 273.6ms
Speed: 1.0ms preprocess, 273.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvZWPKXBd1aMmg1zft9bAg_90.JPG: 480x640 (no detections), 335.4ms
Speed: 1.0ms preprocess, 335.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvZWPKXBd1aMmg1zft9bAg_180.JPG: 480x640 (no detections), 270.4ms
Speed: 1.1ms preprocess, 270.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvZWPKXBd1aMmg1zft9bAg_270.JPG: 480x640 1 Waste, 270.0ms
Speed: 1.0ms preprocess, 270.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvbqsvSUOQ57R0uC_GH2Kw_0.JPG: 480x640 (no detections), 277.7ms
Speed: 1.1ms preprocess, 277.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvbqsvSUOQ57R0uC_GH2Kw_90.JPG: 480x640 (no detections), 296.7ms
Speed: 1.1ms preprocess, 296.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvbqsvSUOQ57R0uC_GH2Kw_180.JPG: 480x640 1 Waste, 272.2ms
Speed: 1.2ms preprocess, 272.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvbqsvSUOQ57R0uC_GH2Kw_270.JPG: 480x640 (no detections), 284.9ms
Speed: 1.0ms preprocess, 284.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvdtafGgUH2VlKUdDID1fg_0.JPG: 480x640 (no detections), 289.3ms
Speed: 1.0ms preprocess, 289.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvdtafGgUH2VlKUdDID1fg_90.JPG: 480x640 (no detections), 306.0ms
Speed: 1.0ms preprocess, 306.0ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvdtafGgUH2VlKUdDID1fg_180.JPG: 480x640 (no detections), 349.1ms
Speed: 1.5ms preprocess, 349.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvdtafGgUH2VlKUdDID1fg_270.JPG: 480x640 (no detections), 299.8ms
Speed: 1.3ms preprocess, 299.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zve70zST6Jw_-B9rjm6nOQ_0.JPG: 480x640 (no detections), 312.3ms
Speed: 1.3ms preprocess, 312.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zve70zST6Jw_-B9rjm6nOQ_90.JPG: 480x640 (no detections), 355.3ms
Speed: 1.5ms preprocess, 355.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zve70zST6Jw_-B9rjm6nOQ_180.JPG: 480x640 (no detections), 298.7ms
Speed: 1.3ms preprocess, 298.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zve70zST6Jw_-B9rjm6nOQ_270.JPG: 480x640 (no detections), 343.6ms
Speed: 1.1ms preprocess, 343.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvhzvATzawJb8EksK9FSuA_0.JPG: 480x640 (no detections), 292.0ms
Speed: 1.1ms preprocess, 292.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvhzvATzawJb8EksK9FSuA_90.JPG: 480x640 (no detections), 277.4ms
Speed: 1.1ms preprocess, 277.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvhzvATzawJb8EksK9FSuA_180.JPG: 480x640 (no detections), 275.6ms
Speed: 1.1ms preprocess, 275.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvhzvATzawJb8EksK9FSuA_270.JPG: 480x640 (no detections), 272.2ms
Speed: 1.0ms preprocess, 272.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvoUaTV1vHYFCGMvPLCOpg_0.JPG: 480x640 (no detections), 271.8ms
Speed: 1.0ms preprocess, 271.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvoUaTV1vHYFCGMvPLCOpg_90.JPG: 480x640 (no detections), 273.2ms
Speed: 1.1ms preprocess, 273.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvoUaTV1vHYFCGMvPLCOpg_180.JPG: 480x640 (no detections), 271.7ms
Speed: 1.0ms preprocess, 271.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvoUaTV1vHYFCGMvPLCOpg_270.JPG: 480x640 (no detections), 294.8ms
Speed: 1.1ms preprocess, 294.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvsUxdxGJPmWHDl69t19PA_0.JPG: 480x640 (no detections), 277.7ms
Speed: 1.1ms preprocess, 277.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvsUxdxGJPmWHDl69t19PA_90.JPG: 480x640 (no detections), 276.8ms
Speed: 1.0ms preprocess, 276.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvsUxdxGJPmWHDl69t19PA_180.JPG: 480x640 (no detections), 309.5ms
Speed: 1.1ms preprocess, 309.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvsUxdxGJPmWHDl69t19PA_270.JPG: 480x640 (no detections), 288.3ms
Speed: 1.2ms preprocess, 288.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvyKc3XUH4sMSQYnp_F49Q_0.JPG: 480x640 (no detections), 284.8ms
Speed: 1.2ms preprocess, 284.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvyKc3XUH4sMSQYnp_F49Q_90.JPG: 480x640 (no detections), 284.9ms
Speed: 1.4ms preprocess, 284.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvyKc3XUH4sMSQYnp_F49Q_180.JPG: 480x640 (no detections), 284.5ms
Speed: 1.2ms preprocess, 284.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvyKc3XUH4sMSQYnp_F49Q_270.JPG: 480x640 (no detections), 278.7ms
Speed: 1.0ms preprocess, 278.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvzFBn4k_517MwWt8vZ1OA_0.JPG: 480x640 (no detections), 308.3ms
Speed: 1.0ms preprocess, 308.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvzFBn4k_517MwWt8vZ1OA_90.JPG: 480x640 1 Waste, 274.2ms
Speed: 1.2ms preprocess, 274.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvzFBn4k_517MwWt8vZ1OA_180.JPG: 480x640 (no detections), 273.3ms
Speed: 1.0ms preprocess, 273.3ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/v/zvzFBn4k_517MwWt8vZ1OA_270.JPG: 480x640 (no detections), 293.7ms

Speed: 1.1ms preprocess, 293.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zw0T7B9kSFC0TXb_PEzIKQ_0.JPG: 480x640 (no detections), 276.8ms
Speed: 1.2ms preprocess, 276.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zw0T7B9kSFC0TXb_PEzIKQ_90.JPG: 480x640 (no detections), 273.8ms
Speed: 1.2ms preprocess, 273.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zw0T7B9kSFC0TXb_PEzIKQ_180.JPG: 480x640 (no detections), 272.8ms
Speed: 1.1ms preprocess, 272.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zw0T7B9kSFC0TXb_PEzIKQ_270.JPG: 480x640 (no detections), 281.8ms
Speed: 1.3ms preprocess, 281.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zw6iOl5uq-5--0maswrUOw_0.JPG: 480x640 (no detections), 287.0ms
Speed: 1.1ms preprocess, 287.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zw6iOl5uq-5--0maswrUOw_90.JPG: 480x640 (no detections), 299.4ms
Speed: 1.1ms preprocess, 299.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zw6iOl5uq-5--0maswrUOw_180.JPG: 480x640 (no detections), 283.6ms
Speed: 1.2ms preprocess, 283.6ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zw6iOl5uq-5--0maswrUOw_270.JPG: 480x640 (no detections), 273.9ms
Speed: 1.3ms preprocess, 273.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zw7CuYTVBWSD4kB-4m_k4Q_0.JPG: 480x640 (no detections), 274.7ms
Speed: 1.1ms preprocess, 274.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zw7CuYTVBWSD4kB-4m_k4Q_90.JPG: 480x640 (no detections), 275.3ms
Speed: 1.0ms preprocess, 275.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zw7CuYTVBWSD4kB-4m_k4Q_180.JPG: 480x640 (no detections), 278.8ms
Speed: 1.1ms preprocess, 278.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zw7CuYTVBWSD4kB-4m_k4Q_270.JPG: 480x640 (no detections), 289.3ms
Speed: 1.2ms preprocess, 289.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zw8Voo5-Q0AApCg_KgThsA_0.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zw8Voo5-Q0AApCg_KgThsA_90.JPG: 480x640 (no detections), 311.1ms
Speed: 1.1ms preprocess, 311.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zw8Voo5-Q0AApCg_KgThsA_180.JPG: 480x640 (no detections), 295.9ms
Speed: 1.2ms preprocess, 295.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zw8Voo5-Q0AApCg_KgThsA_270.JPG: 480x640 (no detections), 281.9ms
Speed: 1.1ms preprocess, 281.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zw94DfsY_uYLfE7uSb5KQg_0.JPG: 480x640 (no detections), 292.2ms
Speed: 1.1ms preprocess, 292.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zw94DfsY_uYLfE7uSb5KQg_90.JPG: 480x640 (no detections), 301.7ms
Speed: 1.1ms preprocess, 301.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zw94DfsY_uYLfE7uSb5KQg_180.JPG: 480x640 (no detections), 318.5ms
Speed: 1.1ms preprocess, 318.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zw94DfsY_uYLfE7uSb5KQg_270.JPG: 480x640 (no detections), 289.1ms
Speed: 1.2ms preprocess, 289.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zw9Q_DQdVNk1Ed8_1mmGXA_0.JPG: 480x640 (no detections), 288.0ms
Speed: 1.3ms preprocess, 288.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zw9Q_DQdVNk1Ed8_1mmGXA_90.JPG: 480x640 (no detections), 306.6ms
Speed: 1.4ms preprocess, 306.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zw9Q_DQdVNk1Ed8_1mmGXA_180.JPG: 480x640 (no detections), 280.6ms
Speed: 1.1ms preprocess, 280.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zw9Q_DQdVNk1Ed8_1mmGXA_270.JPG: 480x640 (no detections), 289.7ms
Speed: 1.3ms preprocess, 289.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zw9gS4G-JIkCsUKwHCNcAA_0.JPG: 480x640 1 Waste, 278.6ms
Speed: 1.0ms preprocess, 278.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zw9gS4G-JIkCsUKwHCNcAA_90.JPG: 480x640 (no detections), 312.4ms
Speed: 1.7ms preprocess, 312.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zw9gS4G-JIkCsUKwHCNcAA_180.JPG: 480x640 (no detections), 274.8ms
Speed: 1.1ms preprocess, 274.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zw9gS4G-JIkCsUKwHCNcAA_270.JPG: 480x640 2 Wastes, 287.1ms
Speed: 1.0ms preprocess, 287.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwAWL099dpzhWYfMxiWmRA_0.JPG: 480x640 (no detections), 278.5ms
Speed: 1.7ms preprocess, 278.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwAWL099dpzhWYfMxiWmRA_90.JPG: 480x640 (no detections), 272.8ms
Speed: 1.0ms preprocess, 272.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwAWL099dpzhWYfMxiWmRA_180.JPG: 480x640 (no detections), 291.6ms
Speed: 1.0ms preprocess, 291.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwAWL099dpzhWYfMxiWmRA_270.JPG: 480x640 (no detections), 276.2ms
Speed: 1.0ms preprocess, 276.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwGO5ukpzVMIpZwYQj7eag_0.JPG: 480x640 (no detections), 277.7ms
Speed: 1.1ms preprocess, 277.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwGO5ukpzVMIpZwYQj7eag_90.JPG: 480x640 (no detections), 274.3ms
Speed: 1.0ms preprocess, 274.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwGO5ukpzVMIpZwYQj7eag_180.JPG: 480x640 (no detections), 273.6ms
Speed: 1.0ms preprocess, 273.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwGO5ukpzVMIpZwYQj7eag_270.JPG: 480x640 (no detections), 274.7ms
Speed: 1.1ms preprocess, 274.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwOh2fM2QKpKtNMu6kXy_A_0.JPG: 480x640 (no detections), 277.1ms
Speed: 1.0ms preprocess, 277.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwOh2fM2QKpKtNMu6kXy_A_90.JPG: 480x640 (no detections), 273.4ms
Speed: 1.0ms preprocess, 273.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwOh2fM2QKpKtNMu6kXy_A_180.JPG: 480x640 (no detections), 272.4ms
Speed: 1.1ms preprocess, 272.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwOh2fM2QKpKtNMu6kXy_A_270.JPG: 480x640 (no detections), 275.3ms
Speed: 1.0ms preprocess, 275.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwRJ_42heQL92VbMY7RvlQ_0.JPG: 480x640 (no detections), 273.0ms
Speed: 1.5ms preprocess, 273.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwRJ_42heQL92VbMY7RvlQ_90.JPG: 480x640 (no detections), 270.8ms
Speed: 1.1ms preprocess, 270.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwRJ_42heQL92VbMY7RvlQ_180.JPG: 480x640 1 Waste, 271.5ms
Speed: 1.1ms preprocess, 271.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwRJ_42heQL92VbMY7RvlQ_270.JPG: 480x640 (no detections), 273.5ms
Speed: 1.0ms preprocess, 273.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwR_HrjlkjsldHb6f3Xd6Q_0.JPG: 480x640 (no detections), 270.1ms
Speed: 1.0ms preprocess, 270.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwR_HrjlkjsldHb6f3Xd6Q_90.JPG: 480x640 (no detections), 275.5ms
Speed: 1.3ms preprocess, 275.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwR_HrjlkjsldHb6f3Xd6Q_180.JPG: 480x640 (no detections), 272.8ms
Speed: 1.0ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwR_HrjlkjsldHb6f3Xd6Q_270.JPG: 480x640 (no detections), 272.5ms
Speed: 1.1ms preprocess, 272.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwSU9z33TV_3Q3WhgjOaAg_0.JPG: 480x640 (no detections), 274.0ms
Speed: 1.0ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwSU9z33TV_3Q3WhgjOaAg_90.JPG: 480x640 (no detections), 271.9ms
Speed: 1.0ms preprocess, 271.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwSU9z33TV_3Q3WhgjOaAg_180.JPG: 480x640 (no detections), 276.5ms
Speed: 1.1ms preprocess, 276.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwSU9z33TV_3Q3WhgjOaAg_270.JPG: 480x640 (no detections), 277.0ms
Speed: 1.1ms preprocess, 277.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwU88_1WKIbKVwRdtbIhfg_0.JPG: 480x640 (no detections), 278.6ms
Speed: 1.0ms preprocess, 278.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwU88_1WKIbKVwRdtbIhfg_90.JPG: 480x640 (no detections), 275.1ms
Speed: 1.2ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwU88_1WKIbKVwRdtbIhfg_180.JPG: 480x640 (no detections), 271.7ms
Speed: 1.1ms preprocess, 271.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwU88_1WKIbKVwRdtbIhfg_270.JPG: 480x640 (no detections), 273.5ms
Speed: 1.0ms preprocess, 273.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwW6E4yEs0cc96AaCa8BPg_0.JPG: 480x640 (no detections), 331.5ms
Speed: 1.1ms preprocess, 331.5ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwW6E4yEs0cc96AaCa8BPg_90.JPG: 480x640 (no detections), 268.9ms
Speed: 1.0ms preprocess, 268.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwW6E4yEs0cc96AaCa8BPg_180.JPG: 480x640 (no detections), 274.0ms
Speed: 1.1ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwW6E4yEs0cc96AaCa8BPg_270.JPG: 480x640 (no detections), 272.1ms
Speed: 1.1ms preprocess, 272.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwYfFLHUoVu1jeAzD8DK0w_0.JPG: 480x640 (no detections), 276.8ms
Speed: 1.1ms preprocess, 276.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwYfFLHUoVu1jeAzD8DK0w_90.JPG: 480x640 1 Waste, 278.2ms
Speed: 1.1ms preprocess, 278.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwYfFLHUoVu1jeAzD8DK0w_180.JPG: 480x640 (no detections), 275.9ms
Speed: 1.1ms preprocess, 275.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwYfFLHUoVu1jeAzD8DK0w_270.JPG: 480x640 (no detections), 272.4ms
Speed: 1.1ms preprocess, 272.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwZhcWMFSvva7I3sgv89FQ_0.JPG: 480x640 (no detections), 279.3ms
Speed: 1.0ms preprocess, 279.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwZhcWMFSvva7I3sgv89FQ_90.JPG: 480x640 (no detections), 276.2ms
Speed: 1.1ms preprocess, 276.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwZhcWMFSvva7I3sgv89FQ_180.JPG: 480x640 (no detections), 271.1ms

Speed: 1.0ms preprocess, 271.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwZhcWMFSvva7I3sgv89FQ_270.JPG: 480x640 (no detections), 272.8ms
Speed: 1.0ms preprocess, 272.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwamGoKYc-SyhYo-4yVYKg_0.JPG: 480x640 (no detections), 280.0ms
Speed: 1.0ms preprocess, 280.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwamGoKYc-SyhYo-4yVYKg_90.JPG: 480x640 (no detections), 311.7ms
Speed: 1.2ms preprocess, 311.7ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwamGoKYc-SyhYo-4yVYKg_180.JPG: 480x640 (no detections), 285.7ms
Speed: 1.1ms preprocess, 285.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwamGoKYc-SyhYo-4yVYKg_270.JPG: 480x640 (no detections), 267.6ms
Speed: 1.1ms preprocess, 267.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwc5I2nuSi8iZ614XPYlGA_0.JPG: 480x640 (no detections), 276.7ms
Speed: 1.0ms preprocess, 276.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwc5I2nuSi8iZ614XPYlGA_90.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwc5I2nuSi8iZ614XPYlGA_180.JPG: 480x640 (no detections), 275.2ms
Speed: 1.1ms preprocess, 275.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwc5I2nuSi8iZ614XPYlGA_270.JPG: 480x640 (no detections), 275.3ms
Speed: 1.1ms preprocess, 275.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zweMlcII8syLOfCoZbESXg_0.JPG: 480x640 (no detections), 300.9ms
Speed: 1.7ms preprocess, 300.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zweMlcII8syLOfCoZbESXg_90.JPG: 480x640 (no detections), 280.8ms
Speed: 1.1ms preprocess, 280.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zweMlcII8syLOfCoZbESXg_180.JPG: 480x640 (no detections), 291.2ms
Speed: 1.1ms preprocess, 291.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zweMlcII8syLOfCoZbESXg_270.JPG: 480x640 (no detections), 287.5ms
Speed: 1.3ms preprocess, 287.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwgkYfkh9X5URDNNGh7p4w_0.JPG: 480x640 (no detections), 289.4ms
Speed: 1.3ms preprocess, 289.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwgkYfkh9X5URDNNGh7p4w_90.JPG: 480x640 (no detections), 286.2ms
Speed: 1.1ms preprocess, 286.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwgkYfkh9X5URDNNGh7p4w_180.JPG: 480x640 (no detections), 287.6ms
Speed: 1.1ms preprocess, 287.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwgkYfkh9X5URDNNGh7p4w_270.JPG: 480x640 (no detections), 280.5ms
Speed: 1.1ms preprocess, 280.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwiJo-7NydKR0y_P4Q51gw_0.JPG: 480x640 (no detections), 269.6ms
Speed: 1.1ms preprocess, 269.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwiJo-7NydKR0y_P4Q51gw_90.JPG: 480x640 (no detections), 281.5ms
Speed: 1.1ms preprocess, 281.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwiJo-7NydKR0y_P4Q51gw_180.JPG: 480x640 (no detections), 275.1ms
Speed: 1.0ms preprocess, 275.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwiJo-7NydKR0y_P4Q51gw_270.JPG: 480x640 1 Waste, 287.2ms
Speed: 1.1ms preprocess, 287.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwkQaOSn_7E_v7F_2Djjww_0.JPG: 480x640 (no detections), 379.7ms
Speed: 1.4ms preprocess, 379.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwkQaOSn_7E_v7F_2Djjww_90.JPG: 480x640 (no detections), 288.0ms
Speed: 1.1ms preprocess, 288.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwkQaOSn_7E_v7F_2Djjww_180.JPG: 480x640 (no detections), 317.0ms
Speed: 1.3ms preprocess, 317.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwkQaOSn_7E_v7F_2Djjww_270.JPG: 480x640 (no detections), 278.6ms
Speed: 1.1ms preprocess, 278.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwlvlKOmM4eZwHWQPwU4BA_0.JPG: 480x640 (no detections), 277.2ms
Speed: 1.1ms preprocess, 277.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwlvlKOmM4eZwHWQPwU4BA_90.JPG: 480x640 (no detections), 297.5ms
Speed: 1.1ms preprocess, 297.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwlvlKOmM4eZwHWQPwU4BA_180.JPG: 480x640 (no detections), 311.4ms
Speed: 1.1ms preprocess, 311.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwlvlKOmM4eZwHWQPwU4BA_270.JPG: 480x640 (no detections), 286.7ms
Speed: 1.0ms preprocess, 286.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwzRBBnaSKiH6ehCsdumEA_0.JPG: 480x640 (no detections), 279.0ms
Speed: 1.1ms preprocess, 279.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwzRBBnaSKiH6ehCsdumEA_90.JPG: 480x640 (no detections), 276.9ms
Speed: 1.1ms preprocess, 276.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwzRBBnaSKiH6ehCsdumEA_180.JPG: 480x640 (no detections), 282.0ms
Speed: 1.0ms preprocess, 282.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/w/zwzRBBnaSKiH6ehCsdumEA_270.JPG: 480x640 (no detections), 279.3ms
Speed: 1.1ms preprocess, 279.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zx-YVO0uWWqkeXFGK9V0wA_0.JPG: 480x640 (no detections), 274.4ms
Speed: 1.2ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zx-YVO0uWWqkeXFGK9V0wA_90.JPG: 480x640 (no detections), 297.7ms
Speed: 1.1ms preprocess, 297.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zx-YVO0uWWqkeXFGK9V0wA_180.JPG: 480x640 (no detections), 276.7ms
Speed: 1.1ms preprocess, 276.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zx-YVO0uWWqkeXFGK9V0wA_270.JPG: 480x640 (no detections), 274.9ms
Speed: 1.1ms preprocess, 274.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zx1ke2uoHyPh9_X3l-zXAw_0.JPG: 480x640 1 Waste, 280.6ms
Speed: 1.0ms preprocess, 280.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zx1ke2uoHyPh9_X3l-zXAw_90.JPG: 480x640 (no detections), 275.4ms
Speed: 1.2ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zx1ke2uoHyPh9_X3l-zXAw_180.JPG: 480x640 (no detections), 279.3ms
Speed: 1.2ms preprocess, 279.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zx1ke2uoHyPh9_X3l-zXAw_270.JPG: 480x640 (no detections), 274.4ms
Speed: 1.1ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zx5nrrwWtYSvglv67sbV9Q_0.JPG: 480x640 (no detections), 276.7ms
Speed: 1.2ms preprocess, 276.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zx5nrrwWtYSvglv67sbV9Q_90.JPG: 480x640 (no detections), 278.4ms
Speed: 1.1ms preprocess, 278.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zx5nrrwWtYSvglv67sbV9Q_180.JPG: 480x640 (no detections), 275.0ms
Speed: 1.1ms preprocess, 275.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zx5nrrwWtYSvglv67sbV9Q_270.JPG: 480x640 (no detections), 274.0ms
Speed: 1.4ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zx6dD4ZGX2xfkok0wx_Osg_0.JPG: 480x640 (no detections), 274.0ms
Speed: 1.0ms preprocess, 274.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zx6dD4ZGX2xfkok0wx_Osg_90.JPG: 480x640 1 Waste, 274.1ms
Speed: 1.1ms preprocess, 274.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zx6dD4ZGX2xfkok0wx_Osg_180.JPG: 480x640 (no detections), 275.8ms
Speed: 1.1ms preprocess, 275.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zx6dD4ZGX2xfkok0wx_Osg_270.JPG: 480x640 (no detections), 277.9ms
Speed: 1.2ms preprocess, 277.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zx7JqewFoDvS7AplLwGKmg_0.JPG: 480x640 (no detections), 277.2ms
Speed: 1.1ms preprocess, 277.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zx7JqewFoDvS7AplLwGKmg_90.JPG: 480x640 (no detections), 278.2ms
Speed: 1.1ms preprocess, 278.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zx7JqewFoDvS7AplLwGKmg_180.JPG: 480x640 (no detections), 276.6ms
Speed: 1.1ms preprocess, 276.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zx7JqewFoDvS7AplLwGKmg_270.JPG: 480x640 (no detections), 275.0ms
Speed: 1.0ms preprocess, 275.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zx7pc8py3WvVr3tOLOTwew_0.JPG: 480x640 (no detections), 276.7ms
Speed: 1.1ms preprocess, 276.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zx7pc8py3WvVr3tOLOTwew_90.JPG: 480x640 (no detections), 274.4ms
Speed: 1.3ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zx7pc8py3WvVr3tOLOTwew_180.JPG: 480x640 (no detections), 270.6ms
Speed: 1.1ms preprocess, 270.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zx7pc8py3WvVr3tOLOTwew_270.JPG: 480x640 (no detections), 272.7ms
Speed: 1.6ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zx8CKRdQ0-f6JUoGl5uo6Q_0.JPG: 480x640 (no detections), 277.5ms
Speed: 1.1ms preprocess, 277.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zx8CKRdQ0-f6JUoGl5uo6Q_90.JPG: 480x640 (no detections), 276.8ms
Speed: 1.0ms preprocess, 276.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zx8CKRdQ0-f6JUoGl5uo6Q_180.JPG: 480x640 (no detections), 277.0ms
Speed: 1.6ms preprocess, 277.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zx8CKRdQ0-f6JUoGl5uo6Q_270.JPG: 480x640 (no detections), 274.3ms
Speed: 1.1ms preprocess, 274.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxDzPgES_bSSnL5UfAgkFg_0.JPG: 480x640 (no detections), 273.4ms
Speed: 1.0ms preprocess, 273.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxDzPgES_bSSnL5UfAgkFg_90.JPG: 480x640 (no detections), 276.3ms
Speed: 1.0ms preprocess, 276.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxDzPgES_bSSnL5UfAgkFg_180.JPG: 480x640 (no detections), 273.7ms
Speed: 1.0ms preprocess, 273.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxDzPgES_bSSnL5UfAgkFg_270.JPG: 480x640 (no detections), 270.0ms
Speed: 1.0ms preprocess, 270.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxEEBwUQFHfqFAWCItU3kQ_0.JPG: 480x640 (no detections), 278.4ms
Speed: 1.0ms preprocess, 278.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxEEBwUQFHfqFAWCItU3kQ_90.JPG: 480x640 (no detections), 276.1ms

Speed: 1.0ms preprocess, 276.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxEEBwUQFHfqFAWCItU3kQ_180.JPG: 480x640 (no detections), 275.8ms
Speed: 1.1ms preprocess, 275.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxEEBwUQFHfqFAWCItU3kQ_270.JPG: 480x640 (no detections), 276.3ms
Speed: 1.1ms preprocess, 276.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxEJ-WJUwOWVWZUIk8sKow_0.JPG: 480x640 (no detections), 273.0ms
Speed: 1.1ms preprocess, 273.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxEJ-WJUwOWVWZUIk8sKow_90.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxEJ-WJUwOWVWZUIk8sKow_180.JPG: 480x640 (no detections), 279.2ms
Speed: 1.3ms preprocess, 279.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxEJ-WJUwOWVWZUIk8sKow_270.JPG: 480x640 (no detections), 276.0ms
Speed: 1.1ms preprocess, 276.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxO00HPoZdCjk_wbdm7PPg_0.JPG: 480x640 (no detections), 272.2ms
Speed: 1.1ms preprocess, 272.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxO00HPoZdCjk_wbdm7PPg_90.JPG: 480x640 (no detections), 274.3ms
Speed: 1.1ms preprocess, 274.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxO00HPoZdCjk_wbdm7PPg_180.JPG: 480x640 (no detections), 273.2ms
Speed: 1.0ms preprocess, 273.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxO00HPoZdCjk_wbdm7PPg_270.JPG: 480x640 1 Waste, 273.8ms
Speed: 1.0ms preprocess, 273.8ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxSVuxbIBuWoCHf_1ejSJg_0.JPG: 480x640 (no detections), 270.1ms
Speed: 1.1ms preprocess, 270.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxSVuxbIBuWoCHf_1ejSJg_90.JPG: 480x640 (no detections), 273.4ms
Speed: 1.2ms preprocess, 273.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxSVuxbIBuWoCHf_1ejSJg_180.JPG: 480x640 (no detections), 278.0ms
Speed: 1.1ms preprocess, 278.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxSVuxbIBuWoCHf_1ejSJg_270.JPG: 480x640 (no detections), 271.2ms
Speed: 1.0ms preprocess, 271.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxShCmPZ6-tlfuZ9VB8ZFw_0.JPG: 480x640 (no detections), 275.9ms
Speed: 1.0ms preprocess, 275.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxShCmPZ6-tlfuZ9VB8ZFw_90.JPG: 480x640 (no detections), 272.2ms
Speed: 1.2ms preprocess, 272.2ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxShCmPZ6-tlfuZ9VB8ZFw_180.JPG: 480x640 (no detections), 270.2ms
Speed: 1.0ms preprocess, 270.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxShCmPZ6-tlfuZ9VB8ZFw_270.JPG: 480x640 (no detections), 272.4ms
Speed: 1.0ms preprocess, 272.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxW1x7hnctrov4qsUSAU5w_0.JPG: 480x640 (no detections), 271.3ms
Speed: 1.0ms preprocess, 271.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxW1x7hnctrov4qsUSAU5w_90.JPG: 480x640 (no detections), 270.5ms
Speed: 1.0ms preprocess, 270.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxW1x7hnctrov4qsUSAU5w_180.JPG: 480x640 (no detections), 275.9ms
Speed: 1.1ms preprocess, 275.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxW1x7hnctrov4qsUSAU5w_270.JPG: 480x640 (no detections), 280.3ms
Speed: 1.0ms preprocess, 280.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxYhHc9vyyOt2Jok3hblOQ_0.JPG: 480x640 (no detections), 274.4ms
Speed: 1.1ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxYhHc9vyyOt2Jok3hblOQ_90.JPG: 480x640 1 Waste, 289.3ms
Speed: 1.0ms preprocess, 289.3ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxYhHc9vyyOt2Jok3hblOQ_180.JPG: 480x640 (no detections), 283.9ms
Speed: 1.1ms preprocess, 283.9ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxYhHc9vyyOt2Jok3hblOQ_270.JPG: 480x640 (no detections), 278.3ms
Speed: 1.0ms preprocess, 278.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxYmdrJ0qU0xIGqCmYcvHw_0.JPG: 480x640 (no detections), 277.6ms
Speed: 1.1ms preprocess, 277.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxYmdrJ0qU0xIGqCmYcvHw_90.JPG: 480x640 (no detections), 303.9ms
Speed: 1.1ms preprocess, 303.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxYmdrJ0qU0xIGqCmYcvHw_180.JPG: 480x640 (no detections), 277.8ms
Speed: 1.1ms preprocess, 277.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxYmdrJ0qU0xIGqCmYcvHw_270.JPG: 480x640 (no detections), 274.5ms
Speed: 1.2ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxZ00WngsroWIaYbVPceZw_0.JPG: 480x640 (no detections), 296.6ms
Speed: 1.0ms preprocess, 296.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxZ00WngsroWIaYbVPceZw_90.JPG: 480x640 (no detections), 310.7ms
Speed: 1.4ms preprocess, 310.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxZ00WngsroWIaYbVPceZw_180.JPG: 480x640 (no detections), 293.8ms
Speed: 1.1ms preprocess, 293.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxZ00WngsroWIaYbVPceZw_270.JPG: 480x640 (no detections), 290.0ms
Speed: 1.3ms preprocess, 290.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxZBLuOqK6CSDViuiDvJ-Q_0.JPG: 480x640 (no detections), 281.8ms
Speed: 1.1ms preprocess, 281.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxZBLuOqK6CSDViuiDvJ-Q_90.JPG: 480x640 (no detections), 274.8ms
Speed: 1.1ms preprocess, 274.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxZBLuOqK6CSDViuiDvJ-Q_180.JPG: 480x640 (no detections), 277.0ms
Speed: 1.0ms preprocess, 277.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxZBLuOqK6CSDViuiDvJ-Q_270.JPG: 480x640 (no detections), 274.6ms
Speed: 1.0ms preprocess, 274.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zx_7WRjg3h1ONtFSCuPBMg_0.JPG: 480x640 (no detections), 275.2ms
Speed: 1.1ms preprocess, 275.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zx_7WRjg3h1ONtFSCuPBMg_90.JPG: 480x640 (no detections), 275.0ms
Speed: 1.2ms preprocess, 275.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zx_7WRjg3h1ONtFSCuPBMg_180.JPG: 480x640 (no detections), 278.9ms
Speed: 1.2ms preprocess, 278.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zx_7WRjg3h1ONtFSCuPBMg_270.JPG: 480x640 (no detections), 277.4ms
Speed: 1.1ms preprocess, 277.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxaaZsJDxYcYasikudQ51g_0.JPG: 480x640 (no detections), 284.6ms
Speed: 1.1ms preprocess, 284.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxaaZsJDxYcYasikudQ51g_90.JPG: 480x640 (no detections), 360.3ms
Speed: 1.1ms preprocess, 360.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxaaZsJDxYcYasikudQ51g_180.JPG: 480x640 (no detections), 275.4ms
Speed: 1.4ms preprocess, 275.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxaaZsJDxYcYasikudQ51g_270.JPG: 480x640 (no detections), 273.2ms
Speed: 1.1ms preprocess, 273.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxaihFIZJeoejpK__c7Dyw_0.JPG: 480x640 (no detections), 274.6ms
Speed: 1.0ms preprocess, 274.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxaihFIZJeoejpK__c7Dyw_90.JPG: 480x640 (no detections), 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxaihFIZJeoejpK__c7Dyw_180.JPG: 480x640 (no detections), 270.4ms
Speed: 1.0ms preprocess, 270.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxaihFIZJeoejpK__c7Dyw_270.JPG: 480x640 (no detections), 288.3ms
Speed: 1.1ms preprocess, 288.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxgBAyhY6Tvw2NZjfEY_yg_0.JPG: 480x640 (no detections), 276.0ms
Speed: 1.1ms preprocess, 276.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxgBAyhY6Tvw2NZjfEY_yg_90.JPG: 480x640 (no detections), 269.9ms
Speed: 1.1ms preprocess, 269.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxgBAyhY6Tvw2NZjfEY_yg_180.JPG: 480x640 1 Waste, 274.0ms
Speed: 1.0ms preprocess, 274.0ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxgBAyhY6Tvw2NZjfEY_yg_270.JPG: 480x640 (no detections), 277.6ms
Speed: 1.1ms preprocess, 277.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxh1tBglZwNcJ1V4Y2gKUA_0.JPG: 480x640 (no detections), 278.2ms
Speed: 1.1ms preprocess, 278.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxh1tBglZwNcJ1V4Y2gKUA_90.JPG: 480x640 (no detections), 276.9ms
Speed: 1.1ms preprocess, 276.9ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxh1tBglZwNcJ1V4Y2gKUA_180.JPG: 480x640 (no detections), 279.7ms
Speed: 1.0ms preprocess, 279.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxh1tBglZwNcJ1V4Y2gKUA_270.JPG: 480x640 (no detections), 275.8ms
Speed: 1.0ms preprocess, 275.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxhNbRP2bfDzEDw7B99c3w_0.JPG: 480x640 (no detections), 274.5ms
Speed: 1.2ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxhNbRP2bfDzEDw7B99c3w_90.JPG: 480x640 (no detections), 272.5ms
Speed: 1.1ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxhNbRP2bfDzEDw7B99c3w_180.JPG: 480x640 (no detections), 268.6ms
Speed: 1.1ms preprocess, 268.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxhNbRP2bfDzEDw7B99c3w_270.JPG: 480x640 (no detections), 333.6ms
Speed: 1.3ms preprocess, 333.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxijQUESQDMO8H0w2hxWYQ_0.JPG: 480x640 (no detections), 274.7ms
Speed: 1.2ms preprocess, 274.7ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxijQUESQDMO8H0w2hxWYQ_90.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxijQUESQDMO8H0w2hxWYQ_180.JPG: 480x640 (no detections), 279.3ms
Speed: 1.1ms preprocess, 279.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxijQUESQDMO8H0w2hxWYQ_270.JPG: 480x640 (no detections), 281.3ms
Speed: 1.1ms preprocess, 281.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxr-8_kzFKPP2wmJzEq_Sg_0.JPG: 480x640 (no detections), 272.7ms

Speed: 1.2ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxr-8_kzFKPP2wmJzEq_Sg_90.JPG: 480x640 (no detections), 277.5ms
Speed: 1.1ms preprocess, 277.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxr-8_kzFKPP2wmJzEq_Sg_180.JPG: 480x640 (no detections), 289.7ms
Speed: 1.1ms preprocess, 289.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxr-8_kzFKPP2wmJzEq_Sg_270.JPG: 480x640 (no detections), 279.4ms
Speed: 1.3ms preprocess, 279.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxrWSidEJBYbMO7sIMKezQ_0.JPG: 480x640 (no detections), 269.5ms
Speed: 1.1ms preprocess, 269.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxrWSidEJBYbMO7sIMKezQ_90.JPG: 480x640 (no detections), 274.5ms
Speed: 1.1ms preprocess, 274.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxrWSidEJBYbMO7sIMKezQ_180.JPG: 480x640 (no detections), 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxrWSidEJBYbMO7sIMKezQ_270.JPG: 480x640 (no detections), 272.5ms
Speed: 1.0ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxrinwknLlmZ3sHI0TMSng_0.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxrinwknLlmZ3sHI0TMSng_90.JPG: 480x640 (no detections), 276.4ms
Speed: 1.0ms preprocess, 276.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxrinwknLlmZ3sHI0TMSng_180.JPG: 480x640 (no detections), 292.2ms
Speed: 1.5ms preprocess, 292.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxrinwknLlmZ3sHI0TMSng_270.JPG: 480x640 (no detections), 273.4ms
Speed: 1.2ms preprocess, 273.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxw4MJYWOWIgZIDn-ojsdg_0.JPG: 480x640 (no detections), 278.5ms
Speed: 1.1ms preprocess, 278.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxw4MJYWOWIgZIDn-ojsdg_90.JPG: 480x640 (no detections), 274.3ms
Speed: 1.2ms preprocess, 274.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxw4MJYWOWIgZIDn-ojsdg_180.JPG: 480x640 (no detections), 278.6ms
Speed: 1.1ms preprocess, 278.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/x/zxw4MJYWOWIgZIDn-ojsdg_270.JPG: 480x640 (no detections), 313.8ms
Speed: 1.3ms preprocess, 313.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zy3TeDlecSYdetriuma-uA_0.JPG: 480x640 (no detections), 274.3ms
Speed: 1.1ms preprocess, 274.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zy3TeDlecSYdetriuma-uA_90.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zy3TeDlecSYdetriuma-uA_180.JPG: 480x640 (no detections), 274.2ms
Speed: 1.2ms preprocess, 274.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zy3TeDlecSYdetriuma-uA_270.JPG: 480x640 (no detections), 290.0ms
Speed: 1.2ms preprocess, 290.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zy3ic2OX3ZKNjCwAdxpERw_0.JPG: 480x640 (no detections), 284.4ms
Speed: 1.3ms preprocess, 284.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zy3ic2OX3ZKNjCwAdxpERw_90.JPG: 480x640 1 Waste, 285.7ms
Speed: 1.2ms preprocess, 285.7ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zy3ic2OX3ZKNjCwAdxpERw_180.JPG: 480x640 (no detections), 279.2ms
Speed: 1.3ms preprocess, 279.2ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zy3ic2OX3ZKNjCwAdxpERw_270.JPG: 480x640 1 Waste, 284.0ms
Speed: 1.1ms preprocess, 284.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zy4LWuBsh4mWJyDc3deXTw_0.JPG: 480x640 (no detections), 276.4ms
Speed: 1.4ms preprocess, 276.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zy4LWuBsh4mWJyDc3deXTw_90.JPG: 480x640 (no detections), 279.2ms
Speed: 1.0ms preprocess, 279.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zy4LWuBsh4mWJyDc3deXTw_180.JPG: 480x640 (no detections), 277.0ms
Speed: 1.2ms preprocess, 277.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zy4LWuBsh4mWJyDc3deXTw_270.JPG: 480x640 (no detections), 282.8ms
Speed: 1.1ms preprocess, 282.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zy50DSAHmj15j9ql636naA_0.JPG: 480x640 (no detections), 297.1ms
Speed: 1.1ms preprocess, 297.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zy50DSAHmj15j9ql636naA_90.JPG: 480x640 (no detections), 287.5ms
Speed: 1.4ms preprocess, 287.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zy50DSAHmj15j9ql636naA_180.JPG: 480x640 (no detections), 286.1ms
Speed: 1.2ms preprocess, 286.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zy50DSAHmj15j9ql636naA_270.JPG: 480x640 (no detections), 277.2ms
Speed: 1.1ms preprocess, 277.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zy6x_mH3zhR8o5i5t_-mqQ_0.JPG: 480x640 (no detections), 315.8ms
Speed: 1.1ms preprocess, 315.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zy6x_mH3zhR8o5i5t_-mqQ_90.JPG: 480x640 (no detections), 276.1ms
Speed: 1.2ms preprocess, 276.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zy6x_mH3zhR8o5i5t_-mqQ_180.JPG: 480x640 (no detections), 275.6ms
Speed: 1.0ms preprocess, 275.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zy6x_mH3zhR8o5i5t_-mqQ_270.JPG: 480x640 (no detections), 283.6ms
Speed: 1.1ms preprocess, 283.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zy79Ei2IV0T7TSHUA02hJw_0.JPG: 480x640 (no detections), 281.0ms
Speed: 1.2ms preprocess, 281.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zy79Ei2IV0T7TSHUA02hJw_90.JPG: 480x640 (no detections), 278.2ms
Speed: 1.1ms preprocess, 278.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zy79Ei2IV0T7TSHUA02hJw_180.JPG: 480x640 (no detections), 312.8ms
Speed: 1.2ms preprocess, 312.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zy79Ei2IV0T7TSHUA02hJw_270.JPG: 480x640 (no detections), 282.8ms
Speed: 1.2ms preprocess, 282.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zy7XzSGPfMeecFpiabM1Ag_0.JPG: 480x640 (no detections), 279.8ms
Speed: 1.1ms preprocess, 279.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zy7XzSGPfMeecFpiabM1Ag_90.JPG: 480x640 (no detections), 277.6ms
Speed: 1.0ms preprocess, 277.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zy7XzSGPfMeecFpiabM1Ag_180.JPG: 480x640 (no detections), 273.1ms
Speed: 1.2ms preprocess, 273.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zy7XzSGPfMeecFpiabM1Ag_270.JPG: 480x640 (no detections), 273.6ms
Speed: 1.1ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zy8XtU1DFxV14coaA6DiEg_0.JPG: 480x640 (no detections), 281.1ms
Speed: 1.1ms preprocess, 281.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zy8XtU1DFxV14coaA6DiEg_90.JPG: 480x640 (no detections), 273.5ms
Speed: 1.0ms preprocess, 273.5ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zy8XtU1DFxV14coaA6DiEg_180.JPG: 480x640 (no detections), 274.2ms
Speed: 1.2ms preprocess, 274.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zy8XtU1DFxV14coaA6DiEg_270.JPG: 480x640 (no detections), 269.1ms
Speed: 1.1ms preprocess, 269.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zy9-R3ov74MUzmR6gAs_1A_0.JPG: 480x640 (no detections), 275.7ms
Speed: 1.1ms preprocess, 275.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zy9-R3ov74MUzmR6gAs_1A_90.JPG: 480x640 (no detections), 272.1ms
Speed: 1.0ms preprocess, 272.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zy9-R3ov74MUzmR6gAs_1A_180.JPG: 480x640 (no detections), 320.8ms
Speed: 1.1ms preprocess, 320.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zy9-R3ov74MUzmR6gAs_1A_270.JPG: 480x640 (no detections), 295.4ms
Speed: 1.3ms preprocess, 295.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zy9VjGfr4TtogrhLlnyrOg_0.JPG: 480x640 (no detections), 278.4ms
Speed: 1.7ms preprocess, 278.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zy9VjGfr4TtogrhLlnyrOg_90.JPG: 480x640 (no detections), 275.0ms
Speed: 1.5ms preprocess, 275.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zy9VjGfr4TtogrhLlnyrOg_180.JPG: 480x640 (no detections), 272.1ms
Speed: 1.1ms preprocess, 272.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zy9VjGfr4TtogrhLlnyrOg_270.JPG: 480x640 (no detections), 283.3ms
Speed: 1.3ms preprocess, 283.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyIzW65Sh6GlE2jyc1N2Zg_0.JPG: 480x640 (no detections), 288.0ms
Speed: 1.1ms preprocess, 288.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyIzW65Sh6GlE2jyc1N2Zg_90.JPG: 480x640 (no detections), 288.7ms
Speed: 1.2ms preprocess, 288.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyIzW65Sh6GlE2jyc1N2Zg_180.JPG: 480x640 (no detections), 297.8ms
Speed: 1.2ms preprocess, 297.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyIzW65Sh6GlE2jyc1N2Zg_270.JPG: 480x640 (no detections), 297.5ms
Speed: 1.1ms preprocess, 297.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyK7v2O9dMQdpq9Bh_Uteg_0.JPG: 480x640 (no detections), 308.9ms
Speed: 1.3ms preprocess, 308.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyK7v2O9dMQdpq9Bh_Uteg_90.JPG: 480x640 (no detections), 304.0ms
Speed: 1.1ms preprocess, 304.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyK7v2O9dMQdpq9Bh_Uteg_180.JPG: 480x640 2 Wastes, 302.3ms
Speed: 1.5ms preprocess, 302.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyK7v2O9dMQdpq9Bh_Uteg_270.JPG: 480x640 1 Waste, 324.3ms
Speed: 1.6ms preprocess, 324.3ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyOETxFmmHpBe6dgOB_BzA_0.JPG: 480x640 (no detections), 326.1ms
Speed: 1.3ms preprocess, 326.1ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyOETxFmmHpBe6dgOB_BzA_90.JPG: 480x640 (no detections), 355.7ms
Speed: 1.8ms preprocess, 355.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyOETxFmmHpBe6dgOB_BzA_180.JPG: 480x640 (no detections), 293.3ms
Speed: 1.1ms preprocess, 293.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyOETxFmmHpBe6dgOB_BzA_270.JPG: 480x640 (no detections), 296.9ms

Speed: 1.6ms preprocess, 296.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyUIqb_jEfrEnNRj88UntA_0.JPG: 480x640 (no detections), 298.4ms
Speed: 1.5ms preprocess, 298.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyUIqb_jEfrEnNRj88UntA_90.JPG: 480x640 (no detections), 281.0ms
Speed: 1.2ms preprocess, 281.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyUIqb_jEfrEnNRj88UntA_180.JPG: 480x640 (no detections), 333.8ms
Speed: 1.1ms preprocess, 333.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyUIqb_jEfrEnNRj88UntA_270.JPG: 480x640 (no detections), 288.0ms
Speed: 1.0ms preprocess, 288.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyVMtKy1vJiVJVKsY4tMuQ_0.JPG: 480x640 (no detections), 285.0ms
Speed: 1.4ms preprocess, 285.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyVMtKy1vJiVJVKsY4tMuQ_90.JPG: 480x640 (no detections), 278.4ms
Speed: 1.1ms preprocess, 278.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyVMtKy1vJiVJVKsY4tMuQ_180.JPG: 480x640 (no detections), 313.2ms
Speed: 1.2ms preprocess, 313.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyVMtKy1vJiVJVKsY4tMuQ_270.JPG: 480x640 (no detections), 285.3ms
Speed: 1.4ms preprocess, 285.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyVojU5zQ1SGbAYCaUTHmQ_0.JPG: 480x640 (no detections), 269.6ms
Speed: 1.1ms preprocess, 269.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyVojU5zQ1SGbAYCaUTHmQ_90.JPG: 480x640 (no detections), 271.2ms
Speed: 1.2ms preprocess, 271.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyVojU5zQ1SGbAYCaUTHmQ_180.JPG: 480x640 (no detections), 303.8ms
Speed: 1.0ms preprocess, 303.8ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyVojU5zQ1SGbAYCaUTHmQ_270.JPG: 480x640 (no detections), 276.3ms
Speed: 1.3ms preprocess, 276.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyXuzIq1TjzQB50fkMzAYw_0.JPG: 480x640 (no detections), 274.8ms
Speed: 1.2ms preprocess, 274.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyXuzIq1TjzQB50fkMzAYw_90.JPG: 480x640 (no detections), 272.3ms
Speed: 1.1ms preprocess, 272.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyXuzIq1TjzQB50fkMzAYw_180.JPG: 480x640 (no detections), 271.9ms
Speed: 1.0ms preprocess, 271.9ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyXuzIq1TjzQB50fkMzAYw_270.JPG: 480x640 (no detections), 269.9ms
Speed: 1.0ms preprocess, 269.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyZ2Hgpn0Qo9e6A1cgbcbA_0.JPG: 480x640 (no detections), 278.7ms
Speed: 1.0ms preprocess, 278.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyZ2Hgpn0Qo9e6A1cgbcbA_90.JPG: 480x640 (no detections), 272.5ms
Speed: 1.1ms preprocess, 272.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyZ2Hgpn0Qo9e6A1cgbcbA_180.JPG: 480x640 (no detections), 274.0ms
Speed: 1.0ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyZ2Hgpn0Qo9e6A1cgbcbA_270.JPG: 480x640 (no detections), 277.2ms
Speed: 1.2ms preprocess, 277.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zy_tATuGVmhGU8ZrYQntdA_0.JPG: 480x640 (no detections), 273.1ms
Speed: 1.1ms preprocess, 273.1ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zy_tATuGVmhGU8ZrYQntdA_90.JPG: 480x640 (no detections), 277.7ms
Speed: 1.0ms preprocess, 277.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zy_tATuGVmhGU8ZrYQntdA_180.JPG: 480x640 (no detections), 277.5ms
Speed: 1.0ms preprocess, 277.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zy_tATuGVmhGU8ZrYQntdA_270.JPG: 480x640 (no detections), 278.0ms
Speed: 1.1ms preprocess, 278.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zybzYM_N4j8nYtr6mkTLyA_0.JPG: 480x640 (no detections), 282.9ms
Speed: 1.7ms preprocess, 282.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zybzYM_N4j8nYtr6mkTLyA_90.JPG: 480x640 (no detections), 275.2ms
Speed: 1.2ms preprocess, 275.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zybzYM_N4j8nYtr6mkTLyA_180.JPG: 480x640 (no detections), 272.3ms
Speed: 1.0ms preprocess, 272.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zybzYM_N4j8nYtr6mkTLyA_270.JPG: 480x640 (no detections), 288.6ms
Speed: 1.0ms preprocess, 288.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zybzcr8XmlGZWXoIXZLjfw_0.JPG: 480x640 (no detections), 316.3ms
Speed: 1.1ms preprocess, 316.3ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zybzcr8XmlGZWXoIXZLjfw_90.JPG: 480x640 (no detections), 295.2ms
Speed: 1.4ms preprocess, 295.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zybzcr8XmlGZWXoIXZLjfw_180.JPG: 480x640 (no detections), 350.6ms
Speed: 1.1ms preprocess, 350.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zybzcr8XmlGZWXoIXZLjfw_270.JPG: 480x640 (no detections), 327.0ms
Speed: 1.4ms preprocess, 327.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zydqX9jsln8qaZ0MAjMhjg_0.JPG: 480x640 (no detections), 287.6ms
Speed: 2.0ms preprocess, 287.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zydqX9jsln8qaZ0MAjMhjg_90.JPG: 480x640 (no detections), 280.2ms
Speed: 1.2ms preprocess, 280.2ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zydqX9jsln8qaZ0MAjMhjg_180.JPG: 480x640 (no detections), 283.5ms
Speed: 1.1ms preprocess, 283.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zydqX9jsln8qaZ0MAjMhjg_270.JPG: 480x640 (no detections), 277.3ms
Speed: 1.1ms preprocess, 277.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyghDIJxPDtceOG5U30LTA_0.JPG: 480x640 (no detections), 284.0ms
Speed: 1.1ms preprocess, 284.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyghDIJxPDtceOG5U30LTA_90.JPG: 480x640 (no detections), 302.1ms
Speed: 1.2ms preprocess, 302.1ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyghDIJxPDtceOG5U30LTA_180.JPG: 480x640 (no detections), 315.5ms
Speed: 1.1ms preprocess, 315.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyghDIJxPDtceOG5U30LTA_270.JPG: 480x640 (no detections), 265.7ms
Speed: 1.2ms preprocess, 265.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zygt0YQBu8UILFqVEqR7HA_0.JPG: 480x640 (no detections), 306.4ms
Speed: 1.3ms preprocess, 306.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zygt0YQBu8UILFqVEqR7HA_90.JPG: 480x640 (no detections), 301.4ms
Speed: 1.1ms preprocess, 301.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zygt0YQBu8UILFqVEqR7HA_180.JPG: 480x640 (no detections), 281.8ms
Speed: 1.2ms preprocess, 281.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zygt0YQBu8UILFqVEqR7HA_270.JPG: 480x640 (no detections), 305.6ms
Speed: 1.1ms preprocess, 305.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyl0n49NbvaQk2buSCtpZQ_0.JPG: 480x640 (no detections), 296.5ms
Speed: 1.4ms preprocess, 296.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyl0n49NbvaQk2buSCtpZQ_90.JPG: 480x640 (no detections), 321.2ms
Speed: 1.1ms preprocess, 321.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyl0n49NbvaQk2buSCtpZQ_180.JPG: 480x640 (no detections), 333.6ms
Speed: 1.2ms preprocess, 333.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyl0n49NbvaQk2buSCtpZQ_270.JPG: 480x640 (no detections), 289.6ms
Speed: 1.2ms preprocess, 289.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyoiHlMDXGyTaXQ3nWHfZA_0.JPG: 480x640 (no detections), 349.2ms
Speed: 1.1ms preprocess, 349.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyoiHlMDXGyTaXQ3nWHfZA_90.JPG: 480x640 (no detections), 279.4ms
Speed: 1.2ms preprocess, 279.4ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyoiHlMDXGyTaXQ3nWHfZA_180.JPG: 480x640 (no detections), 296.1ms
Speed: 1.1ms preprocess, 296.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyoiHlMDXGyTaXQ3nWHfZA_270.JPG: 480x640 (no detections), 283.2ms
Speed: 1.0ms preprocess, 283.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zypF91iaqzDilZnrw75yeQ_0.JPG: 480x640 (no detections), 281.6ms
Speed: 1.0ms preprocess, 281.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zypF91iaqzDilZnrw75yeQ_90.JPG: 480x640 (no detections), 308.8ms
Speed: 1.2ms preprocess, 308.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zypF91iaqzDilZnrw75yeQ_180.JPG: 480x640 (no detections), 296.9ms
Speed: 1.2ms preprocess, 296.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zypF91iaqzDilZnrw75yeQ_270.JPG: 480x640 (no detections), 284.6ms
Speed: 1.2ms preprocess, 284.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyqF85D5YyXHGJYYKeYPEA_0.JPG: 480x640 (no detections), 283.4ms
Speed: 1.1ms preprocess, 283.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyqF85D5YyXHGJYYKeYPEA_90.JPG: 480x640 (no detections), 335.7ms
Speed: 1.1ms preprocess, 335.7ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyqF85D5YyXHGJYYKeYPEA_180.JPG: 480x640 (no detections), 301.8ms
Speed: 3.1ms preprocess, 301.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyqF85D5YyXHGJYYKeYPEA_270.JPG: 480x640 (no detections), 299.3ms
Speed: 1.1ms preprocess, 299.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyr4CnmlTOcw1rZfUhH0LQ_0.JPG: 480x640 (no detections), 279.8ms
Speed: 1.1ms preprocess, 279.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyr4CnmlTOcw1rZfUhH0LQ_90.JPG: 480x640 (no detections), 274.5ms
Speed: 1.0ms preprocess, 274.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyr4CnmlTOcw1rZfUhH0LQ_180.JPG: 480x640 (no detections), 270.5ms
Speed: 1.1ms preprocess, 270.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyr4CnmlTOcw1rZfUhH0LQ_270.JPG: 480x640 (no detections), 275.8ms
Speed: 1.0ms preprocess, 275.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zysfXcnPd6joY_gIa0SITA_0.JPG: 480x640 (no detections), 297.0ms
Speed: 1.5ms preprocess, 297.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zysfXcnPd6joY_gIa0SITA_90.JPG: 480x640 (no detections), 298.8ms
Speed: 1.5ms preprocess, 298.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zysfXcnPd6joY_gIa0SITA_180.JPG: 480x640 (no detections), 276.2ms

Speed: 1.0ms preprocess, 276.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zysfXcnPd6joY_gIa0SITA_270.JPG: 480x640 1 Waste, 270.3ms
Speed: 1.2ms preprocess, 270.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyuKiiuV5EBlAEXxhmS0BQ_0.JPG: 480x640 (no detections), 276.0ms
Speed: 1.0ms preprocess, 276.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyuKiiuV5EBlAEXxhmS0BQ_90.JPG: 480x640 (no detections), 274.3ms
Speed: 1.2ms preprocess, 274.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyuKiiuV5EBlAEXxhmS0BQ_180.JPG: 480x640 (no detections), 271.3ms
Speed: 1.2ms preprocess, 271.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyuKiiuV5EBlAEXxhmS0BQ_270.JPG: 480x640 (no detections), 281.9ms
Speed: 1.5ms preprocess, 281.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyx-sUBqHW1FZ8NnoQNKMw_0.JPG: 480x640 (no detections), 285.2ms
Speed: 1.1ms preprocess, 285.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyx-sUBqHW1FZ8NnoQNKMw_90.JPG: 480x640 (no detections), 317.0ms
Speed: 1.4ms preprocess, 317.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyx-sUBqHW1FZ8NnoQNKMw_180.JPG: 480x640 (no detections), 313.6ms
Speed: 1.1ms preprocess, 313.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/y/zyx-sUBqHW1FZ8NnoQNKMw_270.JPG: 480x640 (no detections), 302.3ms
Speed: 2.2ms preprocess, 302.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zz0rvpqb958shOSxoBHtLg_0.JPG: 480x640 (no detections), 274.4ms
Speed: 1.3ms preprocess, 274.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zz0rvpqb958shOSxoBHtLg_90.JPG: 480x640 (no detections), 274.3ms
Speed: 1.3ms preprocess, 274.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zz0rvpqb958shOSxoBHtLg_180.JPG: 480x640 (no detections), 314.3ms
Speed: 1.1ms preprocess, 314.3ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zz0rvpqb958shOSxoBHtLg_270.JPG: 480x640 (no detections), 273.7ms
Speed: 1.1ms preprocess, 273.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zz1QXv6MvWI1CaU4YY8nYQ_0.JPG: 480x640 (no detections), 272.6ms
Speed: 1.0ms preprocess, 272.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zz1QXv6MvWI1CaU4YY8nYQ_90.JPG: 480x640 (no detections), 270.4ms
Speed: 1.1ms preprocess, 270.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zz1QXv6MvWI1CaU4YY8nYQ_180.JPG: 480x640 (no detections), 270.5ms
Speed: 1.1ms preprocess, 270.5ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zz1QXv6MvWI1CaU4YY8nYQ_270.JPG: 480x640 (no detections), 273.9ms
Speed: 1.0ms preprocess, 273.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zz3X3pt3_ZXcMc77D0ocpg_0.JPG: 480x640 (no detections), 278.4ms
Speed: 1.0ms preprocess, 278.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zz3X3pt3_ZXcMc77D0ocpg_90.JPG: 480x640 (no detections), 279.9ms
Speed: 1.0ms preprocess, 279.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zz3X3pt3_ZXcMc77D0ocpg_180.JPG: 480x640 (no detections), 270.4ms
Speed: 1.1ms preprocess, 270.4ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zz3X3pt3_ZXcMc77D0ocpg_270.JPG: 480x640 (no detections), 282.4ms
Speed: 1.2ms preprocess, 282.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zz3xs3dQSgb6xxrnsS9H8g_0.JPG: 480x640 (no detections), 281.2ms
Speed: 1.2ms preprocess, 281.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zz3xs3dQSgb6xxrnsS9H8g_90.JPG: 480x640 (no detections), 278.0ms
Speed: 1.0ms preprocess, 278.0ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zz3xs3dQSgb6xxrnsS9H8g_180.JPG: 480x640 (no detections), 281.5ms
Speed: 1.1ms preprocess, 281.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zz3xs3dQSgb6xxrnsS9H8g_270.JPG: 480x640 (no detections), 297.6ms
Speed: 1.2ms preprocess, 297.6ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zz4jPwobDa6GZzvsi8vhqg_0.JPG: 480x640 (no detections), 290.1ms
Speed: 1.5ms preprocess, 290.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zz4jPwobDa6GZzvsi8vhqg_90.JPG: 480x640 (no detections), 268.4ms
Speed: 1.2ms preprocess, 268.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zz4jPwobDa6GZzvsi8vhqg_180.JPG: 480x640 (no detections), 268.6ms
Speed: 1.0ms preprocess, 268.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zz4jPwobDa6GZzvsi8vhqg_270.JPG: 480x640 (no detections), 273.5ms
Speed: 1.1ms preprocess, 273.5ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zz7amAopP8StFZyuBqBBWg_0.JPG: 480x640 (no detections), 273.6ms
Speed: 1.0ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zz7amAopP8StFZyuBqBBWg_90.JPG: 480x640 (no detections), 303.0ms
Speed: 1.2ms preprocess, 303.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zz7amAopP8StFZyuBqBBWg_180.JPG: 480x640 (no detections), 273.1ms
Speed: 1.2ms preprocess, 273.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zz7amAopP8StFZyuBqBBWg_270.JPG: 480x640 (no detections), 267.7ms
Speed: 1.0ms preprocess, 267.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzA2xSAkV54tZvCKd4svSw_0.JPG: 480x640 (no detections), 277.3ms
Speed: 1.0ms preprocess, 277.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzA2xSAkV54tZvCKd4svSw_90.JPG: 480x640 (no detections), 277.9ms
Speed: 1.0ms preprocess, 277.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzA2xSAkV54tZvCKd4svSw_180.JPG: 480x640 (no detections), 272.6ms
Speed: 1.1ms preprocess, 272.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzA2xSAkV54tZvCKd4svSw_270.JPG: 480x640 (no detections), 279.2ms
Speed: 1.1ms preprocess, 279.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzAw6PN5c-AdPGkW4MaYBQ_0.JPG: 480x640 (no detections), 314.8ms
Speed: 1.3ms preprocess, 314.8ms inference, 1.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzAw6PN5c-AdPGkW4MaYBQ_90.JPG: 480x640 (no detections), 284.0ms
Speed: 1.4ms preprocess, 284.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzAw6PN5c-AdPGkW4MaYBQ_180.JPG: 480x640 (no detections), 344.8ms
Speed: 1.2ms preprocess, 344.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzAw6PN5c-AdPGkW4MaYBQ_270.JPG: 480x640 (no detections), 284.7ms
Speed: 1.7ms preprocess, 284.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzBQFIGrSqXzJE60d_HHUw_0.JPG: 480x640 (no detections), 270.4ms
Speed: 1.1ms preprocess, 270.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzBQFIGrSqXzJE60d_HHUw_90.JPG: 480x640 (no detections), 274.2ms
Speed: 1.0ms preprocess, 274.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzBQFIGrSqXzJE60d_HHUw_180.JPG: 480x640 (no detections), 283.4ms
Speed: 1.1ms preprocess, 283.4ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzBQFIGrSqXzJE60d_HHUw_270.JPG: 480x640 (no detections), 290.8ms
Speed: 1.6ms preprocess, 290.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzCFs-dryORLJU5998jlbg_0.JPG: 480x640 (no detections), 268.7ms
Speed: 1.2ms preprocess, 268.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzCFs-dryORLJU5998jlbg_90.JPG: 480x640 (no detections), 272.5ms
Speed: 1.2ms preprocess, 272.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzCFs-dryORLJU5998jlbg_180.JPG: 480x640 (no detections), 278.2ms
Speed: 1.2ms preprocess, 278.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzCFs-dryORLJU5998jlbg_270.JPG: 480x640 (no detections), 269.8ms
Speed: 1.1ms preprocess, 269.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzFOmKZ54twpB0x4-SQtEQ_0.JPG: 480x640 (no detections), 264.7ms
Speed: 1.0ms preprocess, 264.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzFOmKZ54twpB0x4-SQtEQ_90.JPG: 480x640 (no detections), 261.9ms
Speed: 1.1ms preprocess, 261.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzFOmKZ54twpB0x4-SQtEQ_180.JPG: 480x640 (no detections), 266.6ms
Speed: 1.3ms preprocess, 266.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzFOmKZ54twpB0x4-SQtEQ_270.JPG: 480x640 (no detections), 261.6ms
Speed: 1.6ms preprocess, 261.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzLb-4f9lJC19dauM4IaJQ_0.JPG: 480x640 (no detections), 261.4ms
Speed: 1.1ms preprocess, 261.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzLb-4f9lJC19dauM4IaJQ_90.JPG: 480x640 (no detections), 276.6ms
Speed: 1.2ms preprocess, 276.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzLb-4f9lJC19dauM4IaJQ_180.JPG: 480x640 (no detections), 279.0ms
Speed: 1.1ms preprocess, 279.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzLb-4f9lJC19dauM4IaJQ_270.JPG: 480x640 2 Wastes, 272.2ms
Speed: 1.4ms preprocess, 272.2ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzLjypQH5rSDxFtFrstPEw_0.JPG: 480x640 (no detections), 279.2ms
Speed: 1.2ms preprocess, 279.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzLjypQH5rSDxFtFrstPEw_90.JPG: 480x640 (no detections), 270.9ms
Speed: 1.1ms preprocess, 270.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzLjypQH5rSDxFtFrstPEw_180.JPG: 480x640 (no detections), 273.3ms
Speed: 1.1ms preprocess, 273.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzLjypQH5rSDxFtFrstPEw_270.JPG: 480x640 (no detections), 277.2ms
Speed: 1.0ms preprocess, 277.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzNQGTa7GD-vkbxLL2CK7g_0.JPG: 480x640 (no detections), 291.0ms
Speed: 1.0ms preprocess, 291.0ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzNQGTa7GD-vkbxLL2CK7g_90.JPG: 480x640 (no detections), 294.3ms
Speed: 1.2ms preprocess, 294.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzNQGTa7GD-vkbxLL2CK7g_180.JPG: 480x640 (no detections), 286.2ms
Speed: 1.2ms preprocess, 286.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzNQGTa7GD-vkbxLL2CK7g_270.JPG: 480x640 (no detections), 293.6ms
Speed: 1.4ms preprocess, 293.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzTzrnkdxx5ODkBL9iZulg_0.JPG: 480x640 (no detections), 307.1ms
Speed: 1.2ms preprocess, 307.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzTzrnkdxx5ODkBL9iZulg_90.JPG: 480x640 (no detections), 357.2ms

Speed: 2.0ms preprocess, 357.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzTzrnkdxx5ODkBL9iZulg_180.JPG: 480x640 (no detections), 277.2ms
Speed: 1.0ms preprocess, 277.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzTzrnkdxx5ODkBL9iZulg_270.JPG: 480x640 (no detections), 290.5ms
Speed: 1.1ms preprocess, 290.5ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzaOk8HQCWZLEDAWNg8nnQ_0.JPG: 480x640 (no detections), 278.1ms
Speed: 1.3ms preprocess, 278.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzaOk8HQCWZLEDAWNg8nnQ_90.JPG: 480x640 (no detections), 269.8ms
Speed: 1.0ms preprocess, 269.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzaOk8HQCWZLEDAWNg8nnQ_180.JPG: 480x640 (no detections), 271.8ms
Speed: 1.1ms preprocess, 271.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzaOk8HQCWZLEDAWNg8nnQ_270.JPG: 480x640 (no detections), 295.4ms
Speed: 1.1ms preprocess, 295.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzaYuT2w5RWrOxFbHjMnfg_0.JPG: 480x640 (no detections), 307.9ms
Speed: 1.3ms preprocess, 307.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzaYuT2w5RWrOxFbHjMnfg_90.JPG: 480x640 (no detections), 289.0ms
Speed: 1.3ms preprocess, 289.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzaYuT2w5RWrOxFbHjMnfg_180.JPG: 480x640 (no detections), 293.6ms
Speed: 1.3ms preprocess, 293.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzaYuT2w5RWrOxFbHjMnfg_270.JPG: 480x640 (no detections), 273.6ms
Speed: 1.1ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzfBdmcjmvwnAYTpORyWRA_0.JPG: 480x640 (no detections), 278.8ms
Speed: 1.1ms preprocess, 278.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzfBdmcjmvwnAYTpORyWRA_90.JPG: 480x640 (no detections), 276.3ms
Speed: 1.0ms preprocess, 276.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzfBdmcjmvwnAYTpORyWRA_180.JPG: 480x640 (no detections), 287.5ms
Speed: 1.1ms preprocess, 287.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzfBdmcjmvwnAYTpORyWRA_270.JPG: 480x640 (no detections), 281.2ms
Speed: 1.1ms preprocess, 281.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzg0e65qrP0uV3wIUFcQ0A_0.JPG: 480x640 (no detections), 283.2ms
Speed: 1.0ms preprocess, 283.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzg0e65qrP0uV3wIUFcQ0A_90.JPG: 480x640 (no detections), 277.7ms
Speed: 1.0ms preprocess, 277.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzg0e65qrP0uV3wIUFcQ0A_180.JPG: 480x640 (no detections), 282.4ms
Speed: 1.3ms preprocess, 282.4ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzg0e65qrP0uV3wIUFcQ0A_270.JPG: 480x640 (no detections), 275.2ms
Speed: 1.0ms preprocess, 275.2ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzi6AYAmWDTk74yL3Syu8Q_0.JPG: 480x640 (no detections), 272.3ms
Speed: 1.1ms preprocess, 272.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzi6AYAmWDTk74yL3Syu8Q_90.JPG: 480x640 (no detections), 295.5ms
Speed: 1.1ms preprocess, 295.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzi6AYAmWDTk74yL3Syu8Q_180.JPG: 480x640 (no detections), 351.7ms
Speed: 1.3ms preprocess, 351.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzi6AYAmWDTk74yL3Syu8Q_270.JPG: 480x640 (no detections), 285.2ms
Speed: 1.4ms preprocess, 285.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzitoTXrNRjWYhH-j3rRtg_0.JPG: 480x640 (no detections), 276.1ms
Speed: 1.1ms preprocess, 276.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzitoTXrNRjWYhH-j3rRtg_90.JPG: 480x640 (no detections), 273.8ms
Speed: 1.1ms preprocess, 273.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzitoTXrNRjWYhH-j3rRtg_180.JPG: 480x640 (no detections), 280.2ms
Speed: 1.1ms preprocess, 280.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzitoTXrNRjWYhH-j3rRtg_270.JPG: 480x640 (no detections), 274.0ms
Speed: 1.0ms preprocess, 274.0ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzjqMUOLzqw7GmKULdvd3g_0.JPG: 480x640 (no detections), 276.6ms
Speed: 1.2ms preprocess, 276.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzjqMUOLzqw7GmKULdvd3g_90.JPG: 480x640 (no detections), 280.3ms
Speed: 1.1ms preprocess, 280.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzjqMUOLzqw7GmKULdvd3g_180.JPG: 480x640 (no detections), 277.4ms
Speed: 1.1ms preprocess, 277.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzjqMUOLzqw7GmKULdvd3g_270.JPG: 480x640 (no detections), 276.1ms
Speed: 1.1ms preprocess, 276.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzl-TyzhnrAKedJ3_eU6Sw_0.JPG: 480x640 (no detections), 274.9ms
Speed: 1.1ms preprocess, 274.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzl-TyzhnrAKedJ3_eU6Sw_90.JPG: 480x640 (no detections), 274.2ms
Speed: 1.0ms preprocess, 274.2ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzl-TyzhnrAKedJ3_eU6Sw_180.JPG: 480x640 (no detections), 271.4ms
Speed: 1.1ms preprocess, 271.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzl-TyzhnrAKedJ3_eU6Sw_270.JPG: 480x640 (no detections), 268.8ms
Speed: 1.1ms preprocess, 268.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzm3E-_qWqEfdEaXR4lErQ_0.JPG: 480x640 (no detections), 278.4ms
Speed: 1.0ms preprocess, 278.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzm3E-_qWqEfdEaXR4lErQ_90.JPG: 480x640 (no detections), 273.6ms
Speed: 1.0ms preprocess, 273.6ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzm3E-_qWqEfdEaXR4lErQ_180.JPG: 480x640 (no detections), 272.7ms
Speed: 1.0ms preprocess, 272.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzm3E-_qWqEfdEaXR4lErQ_270.JPG: 480x640 (no detections), 284.7ms
Speed: 1.1ms preprocess, 284.7ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zznI94xIf_unaBoFf0Lkjw_0.JPG: 480x640 (no detections), 296.9ms
Speed: 1.6ms preprocess, 296.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zznI94xIf_unaBoFf0Lkjw_90.JPG: 480x640 (no detections), 298.9ms
Speed: 1.2ms preprocess, 298.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zznI94xIf_unaBoFf0Lkjw_180.JPG: 480x640 (no detections), 273.8ms
Speed: 1.4ms preprocess, 273.8ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zznI94xIf_unaBoFf0Lkjw_270.JPG: 480x640 (no detections), 293.4ms
Speed: 1.1ms preprocess, 293.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zznms82BsooDPqwBi2l-EQ_0.JPG: 480x640 (no detections), 276.8ms
Speed: 1.1ms preprocess, 276.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zznms82BsooDPqwBi2l-EQ_90.JPG: 480x640 (no detections), 281.8ms
Speed: 1.6ms preprocess, 281.8ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zznms82BsooDPqwBi2l-EQ_180.JPG: 480x640 (no detections), 271.6ms
Speed: 1.1ms preprocess, 271.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zznms82BsooDPqwBi2l-EQ_270.JPG: 480x640 (no detections), 283.9ms
Speed: 1.0ms preprocess, 283.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzrmNIvcii0OH_7N6f7LBQ_0.JPG: 480x640 (no detections), 278.8ms
Speed: 1.0ms preprocess, 278.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzrmNIvcii0OH_7N6f7LBQ_90.JPG: 480x640 (no detections), 278.8ms
Speed: 1.1ms preprocess, 278.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzrmNIvcii0OH_7N6f7LBQ_180.JPG: 480x640 (no detections), 280.1ms
Speed: 1.1ms preprocess, 280.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzrmNIvcii0OH_7N6f7LBQ_270.JPG: 480x640 (no detections), 285.8ms
Speed: 1.2ms preprocess, 285.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzrzdFoKgnslIzYCwY5m4g_0.JPG: 480x640 (no detections), 289.8ms
Speed: 1.2ms preprocess, 289.8ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzrzdFoKgnslIzYCwY5m4g_90.JPG: 480x640 (no detections), 285.4ms
Speed: 1.2ms preprocess, 285.4ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzrzdFoKgnslIzYCwY5m4g_180.JPG: 480x640 (no detections), 302.1ms
Speed: 1.2ms preprocess, 302.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzrzdFoKgnslIzYCwY5m4g_270.JPG: 480x640 (no detections), 290.9ms
Speed: 1.2ms preprocess, 290.9ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zztCBOzgD9C20vgKCJp5NQ_0.JPG: 480x640 (no detections), 290.5ms
Speed: 1.1ms preprocess, 290.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zztCBOzgD9C20vgKCJp5NQ_90.JPG: 480x640 (no detections), 278.1ms
Speed: 1.1ms preprocess, 278.1ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zztCBOzgD9C20vgKCJp5NQ_180.JPG: 480x640 (no detections), 289.1ms
Speed: 1.1ms preprocess, 289.1ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zztCBOzgD9C20vgKCJp5NQ_270.JPG: 480x640 (no detections), 282.3ms
Speed: 1.2ms preprocess, 282.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zztaiUg3Hep3UXWu5SGKmg_0.JPG: 480x640 (no detections), 288.7ms
Speed: 1.2ms preprocess, 288.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zztaiUg3Hep3UXWu5SGKmg_90.JPG: 480x640 (no detections), 299.5ms
Speed: 1.2ms preprocess, 299.5ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zztaiUg3Hep3UXWu5SGKmg_180.JPG: 480x640 1 Waste, 284.6ms
Speed: 1.7ms preprocess, 284.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zztaiUg3Hep3UXWu5SGKmg_270.JPG: 480x640 (no detections), 282.6ms
Speed: 1.1ms preprocess, 282.6ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzu34WXJTnW2r35OBzwGVA_0.JPG: 480x640 (no detections), 282.9ms
Speed: 1.0ms preprocess, 282.9ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzu34WXJTnW2r35OBzwGVA_90.JPG: 480x640 (no detections), 288.8ms
Speed: 1.2ms preprocess, 288.8ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzu34WXJTnW2r35OBzwGVA_180.JPG: 480x640 (no detections), 270.7ms
Speed: 1.1ms preprocess, 270.7ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzu34WXJTnW2r35OBzwGVA_270.JPG: 480x640 (no detections), 276.6ms
Speed: 1.1ms preprocess, 276.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzu_OfR5p0sFK6uT6rTL4w_0.JPG: 480x640 (no detections), 274.0ms

Speed: 1.1ms preprocess, 274.0ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzu_OfR5p0sFK6uT6rTL4w_90.JPG: 480x640 (no detections), 273.1ms
Speed: 1.4ms preprocess, 273.1ms inference, 0.7ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzu_OfR5p0sFK6uT6rTL4w_180.JPG: 480x640 (no detections), 293.2ms
Speed: 1.1ms preprocess, 293.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzu_OfR5p0sFK6uT6rTL4w_270.JPG: 480x640 (no detections), 273.6ms
Speed: 1.2ms preprocess, 273.6ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzvWdmTO_4oxT63l1GeS7w_0.JPG: 480x640 1 Waste, 275.6ms
Speed: 1.1ms preprocess, 275.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzvWdmTO_4oxT63l1GeS7w_90.JPG: 480x640 (no detections), 291.3ms
Speed: 1.2ms preprocess, 291.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzvWdmTO_4oxT63l1GeS7w_180.JPG: 480x640 (no detections), 283.3ms
Speed: 1.5ms preprocess, 283.3ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzvWdmTO_4oxT63l1GeS7w_270.JPG: 480x640 (no detections), 274.3ms
Speed: 1.3ms preprocess, 274.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzxSjzuQ7B44-cL2EPhyMg_0.JPG: 480x640 1 Waste, 288.9ms
Speed: 1.1ms preprocess, 288.9ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzxSjzuQ7B44-cL2EPhyMg_90.JPG: 480x640 (no detections), 304.2ms
Speed: 1.2ms preprocess, 304.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzxSjzuQ7B44-cL2EPhyMg_180.JPG: 480x640 (no detections), 283.5ms
Speed: 1.2ms preprocess, 283.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzxSjzuQ7B44-cL2EPhyMg_270.JPG: 480x640 1 Waste, 297.3ms
Speed: 1.2ms preprocess, 297.3ms inference, 0.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzz5Wt_DGV8LAzRSfKZWiQ_0.JPG: 480x640 (no detections), 288.2ms
Speed: 1.3ms preprocess, 288.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzz5Wt_DGV8LAzRSfKZWiQ_90.JPG: 480x640 (no detections), 278.3ms
Speed: 1.1ms preprocess, 278.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzz5Wt_DGV8LAzRSfKZWiQ_180.JPG: 480x640 (no detections), 295.7ms
Speed: 1.0ms preprocess, 295.7ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzz5Wt_DGV8LAzRSfKZWiQ_270.JPG: 480x640 (no detections), 288.5ms
Speed: 1.9ms preprocess, 288.5ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzzaSItdTD9Tirtzu6aDnA_0.JPG: 480x640 (no detections), 302.3ms
Speed: 1.1ms preprocess, 302.3ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzzaSItdTD9Tirtzu6aDnA_90.JPG: 480x640 (no detections), 324.4ms
Speed: 1.3ms preprocess, 324.4ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzzaSItdTD9Tirtzu6aDnA_180.JPG: 480x640 (no detections), 345.2ms
Speed: 1.5ms preprocess, 345.2ms inference, 0.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/Z/Z/zzzaSItdTD9Tirtzu6aDnA_270.JPG: 480x640 (no detections), 300.4ms
Speed: 1.3ms preprocess, 300.4ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

,panoid,lat,lon,year,month,img_path,angle,type,img_name,conf,bbox
0,---kW5kLNFT2eKu77K0BSg,-1.337135,36.735751,2021,7,-/-/,0,GSVI,---kW5kLNFT2eKu77K0BSg_0,[],[]
427651,wKlN_0tazFZq3y4MyMOlAQ,-1.287796,36.859518,2018,2,w/K/,270,GSVI,wKlN_0tazFZq3y4MyMOlAQ_270,[],[]
427652,wKmT7fZA7_wzInsXTekmlg,-1.271826,36.972277,2018,2,w/K/,0,GSVI,wKmT7fZA7_wzInsXTekmlg_0,[0.8386391401290894],"[[3.6632728576660156, 207.21533203125, 134.437..."
427653,wKmT7fZA7_wzInsXTekmlg,-1.271826,36.972277,2018,2,w/K/,90,GSVI,wKmT7fZA7_wzInsXTekmlg_90,[],[]
427654,wKmT7fZA7_wzInsXTekmlg,-1.271826,36.972277,2018,2,w/K/,180,GSVI,wKmT7fZA7_wzInsXTekmlg_180,[],[]
...,...,...,...,...,...,...,...,...,...,...,...
453359,zzz5Wt_DGV8LAzRSfKZWiQ,-1.287985,37.044124,2021,10,Z/Z/,270,GSVI,zzz5Wt_DGV8LAzRSfKZWiQ_270,[],[]
453360,zzzaSItdTD9Tirtzu6aDnA,-1.274018,37.035957,2021,10,Z/Z/,0,GSVI,zzzaSItdTD9Tirtzu6aDnA_0,[],[]
453361,zzzaSItdTD9Tirtzu6aDnA,-1.274018,37.035957,2021,10,Z/Z/,90,GSVI,zzzaSItdTD9Tirtzu6aDnA_90,[],[]
453362,zzzaSItdTD9Tirtzu6aDnA,-1.274018,37.035957,2021,10,Z/Z/,180,GSVI,zzzaSItdTD9Tirtzu6aDnA_180,[],[]
453363,zzzaSItdTD9Tirtzu6aDnA,-1.274018,37.035957,2021,10,Z/Z/,270,GSVI,zzzaSItdTD9Tirtzu6aDnA_270,[],[]

In [23]:
df_test

,panoid,lat,lon,year,month,img_path,angle,type,img_name,conf,bbox
0,---kW5kLNFT2eKu77K0BSg,-1.337135,36.735751,2021,7,-/-/,0,GSVI,---kW5kLNFT2eKu77K0BSg_0,[],[]
427651,wKlN_0tazFZq3y4MyMOlAQ,-1.287796,36.859518,2018,2,w/K/,270,GSVI,wKlN_0tazFZq3y4MyMOlAQ_270,[],[]
427652,wKmT7fZA7_wzInsXTekmlg,-1.271826,36.972277,2018,2,w/K/,0,GSVI,wKmT7fZA7_wzInsXTekmlg_0,[0.8386391401290894],"[[3.6632728576660156, 207.21533203125, 134.437..."
427653,wKmT7fZA7_wzInsXTekmlg,-1.271826,36.972277,2018,2,w/K/,90,GSVI,wKmT7fZA7_wzInsXTekmlg_90,[],[]
427654,wKmT7fZA7_wzInsXTekmlg,-1.271826,36.972277,2018,2,w/K/,180,GSVI,wKmT7fZA7_wzInsXTekmlg_180,[],[]
...,...,...,...,...,...,...,...,...,...,...,...
453359,zzz5Wt_DGV8LAzRSfKZWiQ,-1.287985,37.044124,2021,10,Z/Z/,270,GSVI,zzz5Wt_DGV8LAzRSfKZWiQ_270,[],[]
453360,zzzaSItdTD9Tirtzu6aDnA,-1.274018,37.035957,2021,10,Z/Z/,0,GSVI,zzzaSItdTD9Tirtzu6aDnA_0,[],[]
453361,zzzaSItdTD9Tirtzu6aDnA,-1.274018,37.035957,2021,10,Z/Z/,90,GSVI,zzzaSItdTD9Tirtzu6aDnA_90,[],[]
453362,zzzaSItdTD9Tirtzu6aDnA,-1.274018,37.035957,2021,10,Z/Z/,180,GSVI,zzzaSItdTD9Tirtzu6aDnA_180,[],[]
453363,zzzaSItdTD9Tirtzu6aDnA,-1.274018,37.035957,2021,10,Z/Z/,270,GSVI,zzzaSItdTD9Tirtzu6aDnA_270,[],[]

In [24]:
df_combined = pd.concat([rows_done_conf, df_test], ignore_index=True)
df_combined

,panoid,lat,lon,year,month,img_path,angle,type,img_name,conf,bbox
0,---kW5kLNFT2eKu77K0BSg,-1.337135,36.735751,2021,7,-/-/,90,GSVI,---kW5kLNFT2eKu77K0BSg_90,[],[]
1,---kW5kLNFT2eKu77K0BSg,-1.337135,36.735751,2021,7,-/-/,180,GSVI,---kW5kLNFT2eKu77K0BSg_180,[],[]
2,---kW5kLNFT2eKu77K0BSg,-1.337135,36.735751,2021,7,-/-/,270,GSVI,---kW5kLNFT2eKu77K0BSg_270,[],[]
3,--3w2NTa6dWsDSlB7lQqiA,-1.304348,36.742095,2018,1,-/-/,0,GSVI,--3w2NTa6dWsDSlB7lQqiA_0,[],[]
4,--3w2NTa6dWsDSlB7lQqiA,-1.304348,36.742095,2018,1,-/-/,90,GSVI,--3w2NTa6dWsDSlB7lQqiA_90,[],[]
...,...,...,...,...,...,...,...,...,...,...,...
453359,zzz5Wt_DGV8LAzRSfKZWiQ,-1.287985,37.044124,2021,10,Z/Z/,270,GSVI,zzz5Wt_DGV8LAzRSfKZWiQ_270,[],[]
453360,zzzaSItdTD9Tirtzu6aDnA,-1.274018,37.035957,2021,10,Z/Z/,0,GSVI,zzzaSItdTD9Tirtzu6aDnA_0,[],[]
453361,zzzaSItdTD9Tirtzu6aDnA,-1.274018,37.035957,2021,10,Z/Z/,90,GSVI,zzzaSItdTD9Tirtzu6aDnA_90,[],[]
453362,zzzaSItdTD9Tirtzu6aDnA,-1.274018,37.035957,2021,10,Z/Z/,180,GSVI,zzzaSItdTD9Tirtzu6aDnA_180,[],[]
453363,zzzaSItdTD9Tirtzu6aDnA,-1.274018,37.035957,2021,10,Z/Z/,270,GSVI,zzzaSItdTD9Tirtzu6aDnA_270,[],[]

In [26]:
df_combined

In [ ]:
df_combined