SVI have been through Yolo 11 and LLM from autoDL, and file name are:  
cpm_NAME

This code select identified waste images to 'Selected'

In [2]:
import os
import shutil
import pandas as pd

In [40]:
# Define the source name, change this to 'Google', 'Faith', or 'ZWL' as needed
source_name = 'Faith'  # Change this value as needed

# Define base path
base_path = '/Users/wenlanzhang/Downloads/PhD_UCL/Data/Waste/img/'

# Define selected paths dynamically
yolo_selected_path = os.path.join(base_path, 'Yolo2_Selected', source_name)
cpm_selected_path = os.path.join(base_path, 'cpm2_Selected', source_name)
dif_path = os.path.join(base_path, 'yolo2_cpm_dif', source_name)

# Create directories dynamically
os.makedirs(yolo_selected_path, exist_ok=True)
os.makedirs(cpm_selected_path, exist_ok=True)
os.makedirs(dif_path, exist_ok=True)

# Load the CSV file dynamically
csv_file_path = os.path.join(base_path, f'cpm2_{source_name}.csv')
df = pd.read_csv(csv_file_path)
df

,img_name,year,month,day,hour,lat,lon,panoid,img_dir,exist,yolo_conf,yolo_bbox,yolo_num,prediction,CPM2
0,014652c8e7e36740a0fe390870e19052b70a2e9a40,2015,8,22,9,-1.268261,36.821169,NaN,Faith/,True,[],[],0,pending,No.
1,20161115_133906,2016,11,15,13,-1.317033,36.791557,NaN,Faith/,True,"[0.4858177900314331, 0.3025636374950409]","[[28.5167236328125, 1253.941650390625, 776.544...",2,yes,Yes.
2,IMG_1450,2016,11,14,13,-1.289936,36.769103,NaN,Faith/,True,[],[],0,pending,Yes.
3,IMG_1336,2016,11,14,11,-1.303164,36.855931,NaN,Faith/,True,[],[],0,pending,No.
4,20161115_134714,2016,11,15,13,-1.315711,36.790286,NaN,Faith/,True,[],[],0,pending,No.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
812,IMG_1111,2016,11,14,10,-1.264403,36.802028,NaN,Faith/,True,[],[],0,pending,No.
813,IMG_1449,2016,11,14,13,-1.289819,36.766542,NaN,Faith/,True,[],[],0,pending,No.
814,IMG_1461,2016,11,14,13,-1.292219,36.786992,NaN,Faith/,True,[],[],0,pending,No.
815,IMG_1307,2016,11,14,11,-1.277408,36.885069,NaN,Faith/,True,[],[],0,pending,Yes.
816,IMG_1313,2016,11,14,11,-1.285467,36.883256,NaN,Faith/,True,[],[],0,pending,Yes.

# Copy yolo and cpm output to folder

In [41]:
# Function to copy images based on conditions
def copy_images(row):
    img_name = row['img_name']
    img_dir = row['img_dir'] 
    
    # Construct the full image path without extension
    img_path_without_ext = os.path.join(base_path, img_dir, img_name)
    
    # Check for common image extensions (e.g., .jpg, .JPG, .png, etc.)
    extensions = ['.jpg', '.JPG', '.jpeg', '.png', '.PNG']  # Add more if needed
    img_path = None
    
    for ext in extensions:
        candidate_path = img_path_without_ext + ext
        if os.path.exists(candidate_path):
            img_path = candidate_path
            break
    
    # If no image is found, print a warning and skip
    if img_path is None:
        print(f"Image {img_name} not found in {os.path.join(base_path, img_dir)} with any supported extension.")
        return
    
    # Copy images where yolo_conf is not empty
    if row['yolo_conf'] != '[]':  # Check if yolo_conf is not empty
        shutil.copy(img_path, os.path.join(yolo_selected_path, os.path.basename(img_path)))
    
    # Copy images where prediction is 'yes'
    if row['prediction'] == 'yes':
        shutil.copy(img_path, os.path.join(cpm_selected_path, os.path.basename(img_path)))

# Apply the function to each row in the DataFrame
df.apply(copy_images, axis=1)

print("Copying completed!")

Copying completed!

# Copy yolo and cpm diff output to folder

In [37]:
# Function to copy images where prediction == 'no'
def copy_images_prediction_no(row):
    img_name = row['img_name']
    img_dir = row['img_dir'] 
    
    # Construct the full image path without extension
    img_path_without_ext = os.path.join(base_path, img_dir, img_name)
    
    # Check for common image extensions (e.g., .jpg, .JPG, .png, etc.)
    extensions = ['.jpg', '.JPG', '.jpeg', '.png', '.PNG']  # Add more if needed
    img_path = None
    
    for ext in extensions:
        candidate_path = img_path_without_ext + ext
        if os.path.exists(candidate_path):
            img_path = candidate_path
            break
    
    # If no image is found, print a warning and skip
    if img_path is None:
        print(f"Image {img_name} not found in {os.path.join(base_path, img_dir)} with any supported extension.")
        return
    
    # Copy images where prediction == 'no' to path3
    if row['prediction'] == 'no':
        shutil.copy(img_path, os.path.join(dif_path, os.path.basename(img_path)))

# Apply the function to each row in the DataFrame
df.apply(copy_images_prediction_no, axis=1)

print("Copying images where prediction == 'no' completed!")

Copying images where prediction == 'no' completed!

# Number check

In [38]:
df['prediction'].value_counts()
# Google

pending    486401
yes          9756
no           9499
Name: prediction, dtype: int64

In [34]:
df['prediction'].value_counts()
# Faith

pending    721
yes         79
no          17
Name: prediction, dtype: int64

In [32]:
df['prediction'].value_counts()
# ZWL

pending    2505
no          236
yes         189
Name: prediction, dtype: int64

# Copy QWen output to folder

In [1]:
import os
import shutil
import pandas as pd

In [7]:
# Load the CSV file dynamically
source_name = 'Google' 
# source_name = 'ZWL' 
# source_name = 'Faith' 


# Define base path
base_path = '/Users/wenlanzhang/Downloads/PhD_UCL/Data/Waste/img/'
QWen_Y = base_path + "Qwen_selected/" + source_name + '/'
QWen_N = base_path + "Qwen_Cpm_diff/" + source_name + '/'

csv_file_path = os.path.join(base_path, f'vl_{source_name}.csv')
df = pd.read_csv(csv_file_path)
df = df.fillna('')

df

/var/folders/2_/nk9j6sb901n_fk5dz_9vtqj80000gn/T/ipykernel_56720/3084293118.py:13: DtypeWarning: Columns (14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv_file_path)

,panoid,lat,lon,year,month,img_name,img_dir,exist,day,hour,yolo_conf,yolo_bbox,yolo_num,prediction,Domestic,Construction
0,KdbXvhlAf5Sqjw-hwBb_Ww,-1.240368,36.928039,2022,2,KdbXvhlAf5Sqjw-hwBb_Ww_0,Google/K/d/,True,,,[0.4317765235900879],"[[288.10223388671875, 157.34405517578125, 365....",1,yes,N,Y
1,1Xyfr0j4E3Gx6_Coadexow,-1.282457,36.751317,2018,2,1Xyfr0j4E3Gx6_Coadexow_180,Google/1/X/,True,,,[0.4008658230304718],"[[298.3153076171875, 184.95751953125, 400.0, 2...",1,yes,Y,Y
2,AgROMWzI6TjbZRpV6iKJDg,-1.284253,36.902957,2021,7,AgROMWzI6TjbZRpV6iKJDg_270,Google/A/g/,True,,,[0.2816741466522217],"[[264.65301513671875, 209.8660125732422, 399.6...",1,yes,N,Y
3,AgROMWzI6TjbZRpV6iKJDg,-1.284253,36.902957,2021,7,AgROMWzI6TjbZRpV6iKJDg_180,Google/A/g/,True,,,[0.288665235042572],"[[0.0, 205.2751922607422, 72.42560577392578, 2...",1,yes,N,Y
4,nTRlyH7aG8CmTfOI1_akgw,-1.279155,36.719541,2018,3,nTRlyH7aG8CmTfOI1_akgw_0,Google/n/T/,True,,,"[0.5433366894721985, 0.3535045087337494]","[[50.18629455566406, 221.9884033203125, 188.91...",2,yes,Y,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
453359,P8R4aL4MRoJ3I1BAqd9log,-1.243328,36.658198,2021,8,P8R4aL4MRoJ3I1BAqd9log_180,Google/P/8/,True,,,[],[],0,pending,,
453360,P8R4aL4MRoJ3I1BAqd9log,-1.243328,36.658198,2021,8,P8R4aL4MRoJ3I1BAqd9log_270,Google/P/8/,True,,,[],[],0,pending,,
453361,Cj_q1UE8aOoi93oRvPOrKA,-1.223843,36.779281,2018,2,Cj_q1UE8aOoi93oRvPOrKA_0,Google/C/j/,True,,,[],[],0,pending,,
453362,Cj_q1UE8aOoi93oRvPOrKA,-1.223843,36.779281,2018,2,Cj_q1UE8aOoi93oRvPOrKA_90,Google/C/j/,True,,,[],[],0,pending,,
453363,TWPhlJpEwnG-oUaWnGSVeg,-1.296458,36.815322,2018,2,TWPhlJpEwnG-oUaWnGSVeg_0,Google/T/W/,True,,,[0.701630711555481],"[[164.29873657226562, 164.19412231445312, 387....",1,no,,

In [8]:
# Ensure both destination folders exist
os.makedirs(QWen_Y, exist_ok=True)
os.makedirs(QWen_N, exist_ok=True)

# Load the DataFrame (assuming it's already loaded as df)
# Define common image extensions
extensions = ['.jpg', '.JPG', '.jpeg', '.png', '.PNG']  # Add more if needed

for _, row in df.iterrows():
    img_name = row['img_name']
    img_dir = row['img_dir']
    domestic_value = row['Domestic']

    # Construct the full image path without extension
    img_path_without_ext = os.path.join(base_path, img_dir, img_name)
    
    # Try different extensions to find the actual image file
    img_path = None
    for ext in extensions:
        candidate_path = img_path_without_ext + ext
        if os.path.exists(candidate_path):
            img_path = candidate_path
            break
    
    # Determine the correct folder based on 'Domestic' value
    if domestic_value == 'Y':
        target_folder = QWen_Y
    elif domestic_value == 'N':
        target_folder = QWen_N
    else:
        continue  # Skip rows with missing or unexpected values

    # If image is found, copy it to the corresponding folder
    if img_path:
        shutil.copy(img_path, os.path.join(target_folder, os.path.basename(img_path)))
        print(f"Copied: {img_name}")
        # print(f"Copied: {img_path} -> {target_folder}")

    else:
        print(f"Image {img_name} not found in {os.path.join(base_path, img_dir)} with any supported extension.")

Copied: KdbXvhlAf5Sqjw-hwBb_Ww_0
Copied: 1Xyfr0j4E3Gx6_Coadexow_180
Copied: AgROMWzI6TjbZRpV6iKJDg_270
Copied: AgROMWzI6TjbZRpV6iKJDg_180
Copied: nTRlyH7aG8CmTfOI1_akgw_0
Copied: WVS-g25nq0v8CeDWBqs2_g_270
Copied: RlFkV2zvI84UnGwCQ1MrvQ_270
Copied: uc2yRcVOf6bCSyBKfnm0Sw_90
Copied: y_-_BCz3RPfZPFkLoqlA7Q_0
Copied: scBZezKqE14ZQCheaHENog_180
Copied: y_-_BCz3RPfZPFkLoqlA7Q_90
Copied: ETGEi1HYjeVs55aQw0OtIQ_270
Copied: K_0aMv8R7RK8pA_RKJexfQ_270
Copied: tqPu0oYd35DXkkPq8GfJWA_0
Copied: Z1JDnY7sfwjA8iMVWXzn8g_90
Copied: TKqRKphgX9p0MgDv0w6oTg_180
Copied: scBZezKqE14ZQCheaHENog_270
Copied: scBZezKqE14ZQCheaHENog_90
Copied: Qtvp1T3a5Z3GJT6N3LmCww_0
Copied: MWB0GSkoxSS3eZZodWfiQA_0
Copied: sFoAk_5MGAlfz0VYQ516Aw_0
Copied: bBB0YMsDICyXMCRBS1Y1rg_270
Copied: Yw-kgR14SvqHI7y1J6xoUQ_0
Copied: b-wqnAwpCyt9SSRS04niLw_270
Copied: -Kejwouwvd70at49dYJVgg_0
Copied: -Kejwouwvd70at49dYJVgg_90
Copied: 3fmP5Rw49RZmbGE7I5wEYw_90
Copied: YN84KiqclAp_pIuqkj-Hew_270
Copied: Gq9CMBmo82LBWT72e3kDnQ_0
Copied: Qtvp1T3a5Z3GJT6N3LmCww_270
Copied: LmVb8zpIQRRdd6X00KgFIg_180
Copied: wA0OQftkCz7KuU2r9GLf8Q_90
Copied: 2GKKUh2pv8E6ftVTSRteDg_270
Copied: 788iXRGeu9wJH9d35301nw_0
Copied: E6q-gjbjol2y_-B5YB7_jg_0
Copied: Qtvp1T3a5Z3GJT6N3LmCww_90
Copied: _nbXeFyPIvSTQuM5v6_prg_0
Copied: IcE4CdDTtRzuyhlNNEO8vg_90
Copied: aDbPZ_jT3lfp6eL63hpL5A_90
Copied: aDbPZ_jT3lfp6eL63hpL5A_0
Copied: 02BHTl26efmI6qr41fikEg_0
Copied: 02BHTl26efmI6qr41fikEg_90
Copied: IcE4CdDTtRzuyhlNNEO8vg_0
Copied: 8OWPQ_dsqWsMNWWe_qrp8Q_0
Copied: IcE4CdDTtRzuyhlNNEO8vg_180
Copied: vpxnrcPf3vt3wuNoDf7BmQ_90
Copied: XdIUtk2Qzq-td9fnKpjG_Q_180
Copied: HOdfQTIi2k0_Mpx_M0IBrQ_180
Copied: ttE3wiNNTnWiQDOkTCob2g_270
Copied: j9qhN-CQHHt90H_bUnfCog_90
Copied: 2Q3a-zDUEyodd2Bnmpd7TA_90
Copied: RQ6G-4sTcEZNORH_BDX2XQ_0
Copied: kmQmrvQD_s7hN6F4qGewAQ_180
Copied: V2oVzcvBlDyc32NVsyXgmg_0
Copied: BXvvVeumADIAa4Y-TYqVKg_180
Copied: pLVLT75AJ3IRcECvh2bdvg_0
Copied: BXvvVeumADIAa4Y-TYqVKg_90
Copied: eVTCjihE3pL_1e1pJzTX-A_90
Copied: eVTCjihE3pL_1e1pJzTX-A_0
Copied: 21EjmeABHVZi8_JtzNoUOg_180
Copied: 21EjmeABHVZi8_JtzNoUOg_270
Copied: VlDkAw1MFa7GKbYKKF1JYA_180
Copied: Onmg9a1R1jB633PifDMgPQ_180
Copied: xDjqaSRbQiYpHLAtEo3xRQ_180
Copied: Onmg9a1R1jB633PifDMgPQ_90
Copied: UZ5-ZavR6yoskdDg1WBDdQ_90
Copied: Ub8cWVEsITTG_DMrkvKLgQ_0
Copied: Ti32KmFug0_AVAw_UjCgMQ_180
Copied: MobIOxBmexgeJzYKmS71Ig_180
Copied: xDjqaSRbQiYpHLAtEo3xRQ_270
Copied: IGL0_-NzEhFk7UMvBIvr_A_270
Copied: l15m5Q8Vvl4gRj3mMHVliw_0
Copied: bvbzgE1_nEKh1G0mDj5geA_0
Copied: nksUracGS2nEkSb3cLu1mw_180
Copied: 4MwzOo-kZl-snu8XJh-eOQ_180
Copied: Mp864Lyi-bUcXqRyTbSf4Q_270
Copied: -BWKa6hMafJAziI5HAxYgA_180
Copied: sYXuGDqhPBTNwom2r6nc3A_90
Copied: MrxiZikCBPS0nOajsX5L5Q_0
Copied: IeK3l9J2D4kXo6WOrvx-iw_0
Copied: Jr2L-vTPQcw2fgOoP2nN7Q_0
Copied: z6v8Jw2aK4HPjivCh73-vA_270
Copied: CL0gi2g6hFPeAR5L8allkA_0
Copied: qpwF5g-1TRshTe5rPD8Mtw_180
Copied: 0WJK4lT8MYUBh14hhRduOQ_90
Copied: HX62a9A_oN_1p1i5CrY6Tg_90
Copied: dOsLdmpdoO4REzu36SbZbg_0
Copied: nt-NDJb3_IB3VIzaCNIvDw_180
Copied: Mp864Lyi-bUcXqRyTbSf4Q_180
Copied: TMCHNWwdAGHptIPDIx3AGw_90
Copied: 6khkwAcNT6VYtLUL3zTMGg_180
Copied: sinjGnnGJfr3zZ7MUASjbA_90
Copied: NZUxIsNZlsP7xY1spUKMiw_270
Copied: u8El6k4uDEFAXFaOxx6oiQ_180
Copied: u8El6k4uDEFAXFaOxx6oiQ_270
Copied: DClBZhZjMIPWnlc4T9GeuA_0
Copied: DClBZhZjMIPWnlc4T9GeuA_90
Copied: T6sXiP0YQaSqmJUOaLiYnQ_270
Copied: xFhkYqEzVrv9qEWCQQg1lw_270
Copied: rvAPT7mUGoikaDqIvgs53Q_270
Copied: sinjGnnGJfr3zZ7MUASjbA_180
Copied: ByIKPcY9yZV9tD84kXsZ4g_90
Copied: vy4ZGyKSWh_msIrBf4TwYQ_90
Copied: KxZBw4s_scZxVZPfUey55w_180
Copied: TJDxEx6he7A3ML6bBdIPWw_0
Copied: M4h0HIWyTCNERlOiKpm55g_0
Copied: gueBLnAIAdYqVkSFA03oyg_90
Copied: NkRwY78tYZ-T2Rs6-X7SUw_180
Copied: EvOJPO69Hy5vgY6gXFTdMg_0
Copied: rnbx1FHKRxCjQTwVaOOipg_270
Copied: jpqER3W528uqy_hHcu21LQ_180
Copied: jpqER3W528uqy_hHcu21LQ_0
Copied: XdyfTUFOkl6AIFTUMA_edg_90
Copied: n3dJa42e9sZyYunYdM4uLw_270
Copied: jarfwgBIbHNzYBK_1qDjCA_180
Copied: rnbx1FHKRxCjQTwVaOOipg_90
Copied: XwG8Y0OcZTC1-F9NUl05hg_90
Copied: EvOJPO69Hy5vgY6gXFTdMg_270
Copied: X5TrWn2AuFvvvO6kst1xLw_270
Copied: hy_JT05nPaYuTkuohyQD7A_270
Copied: w1mOhXlCl-lSiw9a8BDDzQ_0
Copied: KsOUnxCSg-KKJl81prwKeg_270
Copied: 9uEff4dbKzKVejBwlueF_w_180
Copied: w5AokcY_VFEM1CqoZ-wq1g_180
Copied: 0R1CTQfhOGKm0H-We6DZhQ_270
Copied: jpO9VIyAYETf2_wWfaNHfg_90
Copied: MWB0GSkoxSS3eZZodWfiQA_90
Copied: 3fmP5Rw49RZmbGE7I5wEYw_180
Copied: Hm6ywMRA7nZLFNQY55wEjA_0
Copied: La_7ztckWNGS9JvNC_ei5A_180
Copied: pQkNUE4zuTyt6mCZIw0OGw_270
Copied: HhuhHS-RAyb6oY_prRu57g_270
Copied: HhuhHS-RAyb6oY_prRu57g_90
Copied: S4xTnzV3WB0TenxL36fWfg_0
Copied: wOpG7rIiQMr4hkkQGKC8Wg_90
Copied: wOpG7rIiQMr4hkkQGKC8Wg_180
Copied: wOpG7rIiQMr4hkkQGKC8Wg_270
Copied: Dobv9S3NMXxBcI5kK5HZdg_90
Copied: hguaOTVWP-8M26jeEDHJKg_90
Copied: hguaOTVWP-8M26jeEDHJKg_180
Copied: FtrmQ99F5qI_V1uByiaDtw_180
Copied: Vxa5lifnwv50x_WfUsImxg_0
Copied: Ta7_MP8WaT52-HUzfESztA_270
Copied: Ta7_MP8WaT52-HUzfESztA_180
Copied: 0-isBTI3ATbzATsqVA_0aQ_270
Copied: PwDgqWHmjcM9fBncaK9IbA_90
Copied: 34DnJbNwS_h7pZ_ggu6Ngg_90
Copied: PGaLUuaIGHSf8FgzACKhaQ_180
Copied: PGaLUuaIGHSf8FgzACKhaQ_270
Copied: YNK1Ustkx6AwEagb-nr1kA_180
Copied: K68L-jSmns6d9EqdEueWvA_180
Copied: 6VOKVr3MkR14UoshZZ7tJg_0
Copied: Tiu22dZCcJPXAJ2P4krP0w_270
Copied: dovenY_wl5owRaZqeOPhIg_180
Copied: CysG5uXX-NIM1MjBv9fPUA_270
Copied: UTGgISv541cdNgHO-41_Qw_90
Copied: SIznFSXKOP4VMG8I1PBYGw_0
Copied: 1CL9zssHVMzyysxbXw7RwA_270
Copied: 1CL9zssHVMzyysxbXw7RwA_0
Copied: -1ACbgGCoLMU_yiILUN5UA_180
Copied: hwWuXciiKA9XEhISp6hbsQ_90
Copied: v1HzZEiDBA6xzTPzTiLs-g_180
Copied: xUl9AqdQpkbIm9BEMe96EQ_180
Copied: KQqt-j2iDREGChLobmRc6Q_270
Copied: 0DXxIiUSUwC6WMazS_Xs3A_0
Copied: H-nrQY-RdP-yAAOxzqS31Q_270
Copied: 2R2yc2b6dZO_LMKWsbeQ7w_270
Copied: P55tqPTT0_G0shGptJ_ZsA_0
Copied: xmHkiDFC-ChaoRcOHEknvA_270
Copied: PnDq8bPiZh7GjRtuaU8YCg_270
Copied: AE10klssamiSV-Yu9LhQ3A_270
Copied: GTy1o6TyBoNxbYfUBAAy1w_0
Copied: 95nuNM5J-lvblDKFiGL7tw_90
Copied: i-8vdXx92Cx8LNmUpkXhsg_180
Copied: VB_9PLRtAkIJ1p6OeznsDQ_180
Copied: TucVyt2oGsnT9VcWeopHqQ_0
Copied: fA_3fYmhL0VCAcl0skSZng_180
Copied: ZBWGzaPBR5UI9E0L0eOb2Q_180
Copied: yUb3hEdqMnA_TCAetMX_9g_90
Copied: zqEx7lWanMzAbpB5bnHk6w_180
Copied: vRPawAOZFn8b7f06zul4xw_270
Copied: GggWfriThN95kyU3yzd3Kg_270
Copied: 5LutHKqA_X8m6jpkgPRhSg_90
Copied: yIneaY2QS6W2sQNKT5yw9A_270
Copied: y4MCtiItnSrOUVOD7OdOcg_90
Copied: Sn-5dUvGPrxx2m0bun4HRQ_90
Copied: pKQYaorXZr0iR-f93N-82Q_0
Copied: 7bervMqX960zqvAHvnVtSA_270
Copied: a2EgwEvW7g3_A8kPLyI8eA_270
Copied: sO32zxAvspW1WSwFoXIm1A_0
Copied: r7qhxZ-TO5x6qTGE2oD12w_0
Copied: KfqUYOJ-RNWyasAvWioiUA_270
Copied: KfqUYOJ-RNWyasAvWioiUA_0
Copied: pCNheclqlG0c4wdAtDAPxg_0
Copied: pCNheclqlG0c4wdAtDAPxg_90
Copied: WxPol7muWpAceg8bZ0v4Nw_180
Copied: uinBEro1mWNItYv6Tx55eg_180
Copied: P9y75hne3j7dEmdafX8hyw_0
Copied: 3MFqeEHfB-RWTGt3e9CqpQ_0
Copied: wE7J1v4wdI5zXBpAQmju9g_180
Copied: xpoByDtmn--ArniHX2ho6Q_180
Copied: i-Gg13AljteZUsEUBP_6cQ_180
Copied: Efvqk55ylhVdw3HF1o_5Xg_90
Copied: loZvpS2XQvl7p-edklt0Gw_270
Copied: LntUXGi-D0sI89UFkBsm9g_180
Copied: yFE3KKodf27RpZZmYtCoZQ_0
Copied: qpuN6Co50zN2Q0tAGh1iuA_180
Copied: EjvmaxGN7hWotyCxiUIcSw_270
Copied: EjvmaxGN7hWotyCxiUIcSw_0
Copied: WDierXSSAF5pBk6404Dsfg_0
Copied: Ar__HdEzsCCZfgydEgOCHg_0
Copied: 7O4vEEW1VxzOtjEEKZloTg_180
Copied: g6PiCJLLfQTIRsxvRXSH7Q_90
Copied: GmZGfuGV9MEmJ9R9PyoA7Q_180
Copied: oFTSccuPaqnXr0jCfHH5zg_180
Copied: PgoHTDXHkwEnmvqepMmLPw_0
Copied: L9WKsSXoEORHkw34CbQsMg_0
Copied: ZhWTNTi3lSvRug-fEqxS_A_270
Copied: KmJICTeHPb0lhYa6UqtzIw_0
Copied: sHH-8qLh9Wr8msuWkPGLpg_180
Copied: sHH-8qLh9Wr8msuWkPGLpg_90
Copied: 3_eIjs4wVWmK_5gpCNhXXQ_90
Copied: DfjpawmIi4utFGHAMJr-wg_90
Copied: QE_iWL1KB-_OtFZZ8NnnHw_90
Copied: th2bOoQH99C9JW6s0tSxNQ_180
Copied: g3STpO7IZnf1heZF3zR2bQ_270
Copied: KmpM3DAv4-PQI4nJlm0WMw_90
Copied: uZak6Wxp1tvB-yWURdEyGQ_180
Copied: J-ITC_Sf6Q134sgKvokCuQ_180
Copied: AiJV6rTP4dPfayWyFKwkXQ_270
Copied: L9WKsSXoEORHkw34CbQsMg_270
Copied: ZbOhBVhpqdzME4lHQBJXyg_0
Copied: XruQLIVvo7C_Uq2owtoLfw_180
Copied: 5crr3wS7ojCT8P3kfh4dhA_270
Copied: Ta7_MP8WaT52-HUzfESztA_0
Copied: XG_tFrAy4oPDNj_L6P4E0A_90
Copied: j9qhN-CQHHt90H_bUnfCog_270
Copied: pdCGSiOp6mQ4bXfGh2BNEQ_180
Copied: 5crr3wS7ojCT8P3kfh4dhA_90
Copied: 5crr3wS7ojCT8P3kfh4dhA_180
Copied: HDO7Mj_32xS7r4w4AjE4xw_0
Copied: J5daZ6Oc-Z9FtqWy_oyIEQ_0
Copied: m8NY9ErhGab8Kb6YxUXDWg_270
Copied: IzFkrkaLjXhBS2KZqYS40A_0
Copied: jvCo9LGayH3TJfM8OhBVMA_270
Copied: OBa9DymSaMOvrVhs0IWhsw_180
Copied: nfGBP1wO1iqh6yRNHPBixA_0
Copied: J5daZ6Oc-Z9FtqWy_oyIEQ_270
Copied: ChGzqYiHby1JKiyfW71-QQ_90
Copied: ChGzqYiHby1JKiyfW71-QQ_0
Copied: QsKQP4-sw1dKa5U4XYr8VA_90
Copied: _a_qW1cdmQ71IOqVT489-w_0
Copied: rLRpM9_r58mBD4IHQApDzQ_0
Copied: btcOP4pnG2VE1mi07QLRwQ_90
Copied: btcOP4pnG2VE1mi07QLRwQ_0
Copied: hWCVky6HKRCltfjlQIbZKQ_270
Copied: _9QY8MGpRsskr1TdYdx5Ug_180
Copied: M2_WceDIBu9lxN9Z0thaPw_0
Copied: _a_qW1cdmQ71IOqVT489-w_270
Copied: TMjz04x6YcqbD5tiYaDm5Q_0
Copied: _Zkuq_aPZ-HUL4s3jKPnDA_270
Copied: -y5qL_P07u3ZZEfYmyoUvA_90
Copied: -y5qL_P07u3ZZEfYmyoUvA_180
Copied: H2f6V7_f8s6G_d01shqsDQ_90
Copied: sGBudNT6w4M9yb25MwcaiQ_90
Copied: _8ZK84hy8ACLnppcs1haHQ_0
Copied: lhBNvnnMDyXIkVHQX63J1g_270
Copied: HftpqnG8JrJHKaAAzGphWQ_0
Copied: HftpqnG8JrJHKaAAzGphWQ_270
Copied: ENFE-F6AZOript8FaSuSfQ_90
Copied: jB6xMbxUCkzbeBRLzzT2mQ_270
Copied: ElSojHC3vAiOf2Rhi6UQ7g_90
Copied: qeD0pajsb61o90qN8VntUQ_270
Copied: 2R2yc2b6dZO_LMKWsbeQ7w_0
Copied: ZbOhBVhpqdzME4lHQBJXyg_270
Copied: qeD0pajsb61o90qN8VntUQ_0
Copied: 9E4SpQO86xWR1-e5_EKNzA_270
Copied: 9E4SpQO86xWR1-e5_EKNzA_90
Copied: qj_Lp8fHiR5h2P16r_itSg_90
Copied: 8tH3T3EEtlon-MTMk-Z94Q_90
Copied: OnNxt4WTW-fS4kWnl1BWQw_90
Copied: Pqa5V5jLoMyeFvEBnxMohA_90
Copied: Pqa5V5jLoMyeFvEBnxMohA_180
Copied: vtzQ2DuY_H_ZDGQgPEkjcA_90
Copied: _nbXeFyPIvSTQuM5v6_prg_90
Copied: lLvORIoDh0ZKXLyN6RvSqQ_180
Copied: 49OfKWgjj1_oWVeQ-jDEwg_90
Copied: mHlyw4ahsnRGWC7PIO8Xpw_90
Copied: Jezo0SuWP5QzhpXK4cbxlQ_90
Copied: q_lhzz4e7TNg0KjsReukSQ_0
Copied: R3LbeutpQ3lGiT234arHlA_270
Copied: aInE4nAwViwq_dS35EswZg_0
Copied: 2syDuVTLyZGna2SCE1h7Cg_270
Copied: QTpHTWccPZ8QVFZlwLr92w_0
Copied: qZoneo4ny3CBYJezLhGVRg_0
Copied: HFUuZUn9AMqul1k9tj4vpA_0
Copied: R6ESUHLSTfcN2en1NMh1Jw_90
Copied: l1j1A1Wmtc_mQMy4JeF4kQ_0
Copied: qTLvxNmxKACMZxcDvx34Ow_90
Copied: 4ohRiNzUbuJOFq8tGqEnpw_0
Copied: 4ohRiNzUbuJOFq8tGqEnpw_270
Copied: 3OXZVUluRBEI1X-esVfmsA_0
Copied: DmNNKBf0e0picPY9sl5nLQ_270
Copied: vynFy1HIAM5rA11xVKKpcA_90
Copied: RSZXnP723Pjbie08vEDtqA_90
Copied: Tlg4RbCvDfPDEA_T2w0bQQ_180
Copied: ccVy8TctqSUHPAKJh4WM_Q_0
Copied: EJjKYV-CPQOvNzb_jbduBg_0
Copied: w2NIMP2PP6VBdaB5EMITkA_180
Copied: yEXaUt5VCMfsSyJwqacAyw_90
Copied: KJ0InvPXEcHxllkLLPMsug_180
Copied: TfA7WrS_vA2F-oeIjLbY2w_90
Copied: DmNNKBf0e0picPY9sl5nLQ_180
Copied: OXEsmgZ2XhUbxO_xu-wK6w_90
Copied: ojGdJp6kmafqHwzDiw3Zyw_270
Copied: OgTO5HyHG9KVrhr15-9vAg_270
Copied: ApjfZS55Pv39Q-lC_79s4Q_90
Copied: _go_hU95Z_KJKKHICUThtA_90
Copied: KjEQtL8Kvoqi0cFH_p_k7w_90
Copied: NBZDmwjkyiZcTigxuX9r-w_0
Copied: vynFy1HIAM5rA11xVKKpcA_0
Copied: _DQQ0Ddyn7GoUt119nGtPg_270
Copied: _VnfXKPLcnmo15jgZCJI0g_270
Copied: 7JuGgXmvmspce1Vz1efqLg_270
Copied: 7JuGgXmvmspce1Vz1efqLg_0
Copied: lz68p0u0eKWL4C5dFBsaTw_180
Copied: M_A7970iiHac5ozqwV41yw_270
Copied: M_A7970iiHac5ozqwV41yw_0
Copied: yFfcOPeGTkQOtm9zxjpMUw_0
Copied: AdhjlTMHEPRKY3g0myosqQ_270
Copied: coQXn4pM9K0oDDx4NSrxrg_180
Copied: e2T5cLBfCwwIpfMidqENPw_270
Copied: e2T5cLBfCwwIpfMidqENPw_180
Copied: IM-NhV_4-WrmmMy1jnx_TQ_0
Copied: V8o93D42Y34qt8pIN0QnGQ_90
Copied: 7Drj13FwSUPq7tRmza40tQ_270
Copied: 7Drj13FwSUPq7tRmza40tQ_0
Copied: VOCfKfTM2-2P-ZQ-zvrGEg_0
Copied: tP9q9T6LhPttMxXFmLx-OQ_0
Copied: 9sqatGXKtWfCCJhAX49CAA_90
Copied: h9gnskvjTBf6xw91FdAPMg_270
Copied: jH99oDKE2_SWWNQP0ZJKWA_180
Copied: 1bbANlNYzkrVMCeuo3cb6w_0
Copied: yWILI8b5LLVKZDXrejfREA_90
Copied: 0nHhj8kzfAMSL_W7DJd4Og_270
Copied: 0nHhj8kzfAMSL_W7DJd4Og_180
Copied: WrshmZwOSCaPuxahezifWg_270
Copied: VWXeg4wzFxJJY7VUaLLT4w_180
Copied: e5WAi8YUx09hmMt-v068qA_180
Copied: VWXeg4wzFxJJY7VUaLLT4w_90
Copied: fgmSTA23_KwFgNOWvhrYkA_180
Copied: o7nUXLs25ORkdrQiXZkG1Q_270
Copied: 182kaS6oZEEb_9GCscgQIg_90
Copied: 2Btzo3XHkzHynJGfrxg2wA_90
Copied: aInE4nAwViwq_dS35EswZg_270
Copied: Tlg4RbCvDfPDEA_T2w0bQQ_270
Copied: F6Nl_ZZbvru8Sb2YmzcMbQ_270
Copied: 61ew2mZAlnGpMhBsZfWplA_0
Copied: eKJb-xH1wENniXA19pRvHA_90
Copied: ZFATMVBOoVhAdHFwH4SbPQ_270
Copied: lZeDo4SmtY0dKGyWSxWvuQ_270
Copied: lZeDo4SmtY0dKGyWSxWvuQ_180
Copied: 0qo9wT9kF3jUEt7t18V8tg_180
Copied: 0qo9wT9kF3jUEt7t18V8tg_90
Copied: DL2uzQwtDplL57SSpkE_4w_180
Copied: wCzGFSAUyPciEN7i_SYTfQ_90
Copied: 3QxbXTOdpYVU8e6RDjkUHw_0
Copied: wCzGFSAUyPciEN7i_SYTfQ_180
Copied: wCzGFSAUyPciEN7i_SYTfQ_270
Copied: Etobgd8YyXxeB-KYTJyqVg_90
Copied: Mnaf26klge9s71HTmNOYGA_180
Copied: _iqxs_cd43K1q6sb5sowdw_0
Copied: VyopnSAHYNDPHhCujlOMbg_180
Copied: eErz3WWxcfRJs3cqqEkuVQ_270
Copied: QAhsdGlmzM61scM0FXZeNw_270
Copied: Y8CwvzLytVoVxF1YAKLz8g_270
Copied: J5qMYYCWo4DbAF3M-KUs2A_180
Copied: sm6rrlatgzWjYhoY0HtIMA_180
Copied: 37MOK2PCPIwNAcf4S1FWMQ_90
Copied: 37MOK2PCPIwNAcf4S1FWMQ_180
Copied: hwTEWV14Hd7hHqDRnumohA_90
Copied: hwTEWV14Hd7hHqDRnumohA_180
Copied: OB5ZsCgNkRx3Ax81-fjxsw_90
Copied: 3NsmLwZDIVsMUKhqXCFUbg_0
Copied: QAhsdGlmzM61scM0FXZeNw_0
Copied: mO5Df0PCBZ3Wn2Zh9dNCvA_0
Copied: 8SuASXtX7vRYkgVm0BuRTw_270
Copied: EkKI2RUCDsPsLfgZP0gNeA_180
Copied: dOjwsuOggses4kg91Yt_4w_270
Copied: LkDKU6O7CtIbwoLLAzMwMw_270
Copied: VDKQIT4vni9Gljeh7758fA_270
Copied: VyopnSAHYNDPHhCujlOMbg_90
Copied: XR-XCQL4HJif8wdfIcbWZw_270
Copied: esl4QSwwnoRU76NhH06XZw_270
Copied: g50XGfQWXV2MVMDkQBJHUQ_0
Copied: Xh3MBIsV2iY99-Ha91q5cQ_90
Copied: Wd02xu6fT3cwgOQQSst5bw_0
Copied: uh-O3xpaI81teWdAhTXrDA_180
Copied: hwSys95QbvYOkJSZtU3DTQ_0
Copied: g-tbHE2Kx5I-GkawFzL8KA_180
Copied: tJJIzBnpxzBvJZBaVNR8_w_180
Copied: xjJKQAhJMdJmyYbZFpIUQw_0
Copied: esl4QSwwnoRU76NhH06XZw_0
Copied: wKmT7fZA7_wzInsXTekmlg_0
Copied: YK-upDz0qSrmoap9IcQzog_90
Copied: 3p8HZTpsYYQ1O8MTozLyaw_180
Copied: 2LMqW0NQfkVyHCUQZA4Tfg_90
Copied: IA0wqTW0i1j13i6c4_HcHA_90
Copied: sQhBUC5c_WwFAFDjFf-58Q_270
Copied: LBDK4xzwJrBizglO1v1WSA_90
Copied: e-2fzXkZjvV2PzxK4UqNWQ_180
Copied: -D50Bz222TXvuc5-cKSkNA_270
Copied: JCfzq5ermI4-X1XgGc2oQQ_270
Copied: K9rJxQGSZ7MIwCZ6KUC1bA_90
Copied: GPlerh5HwWYjBi86zIOOdA_180
Copied: GudZ9ap7UL_UHYNqd26OPw_0
Copied: o_c24L5HtC4XD-f5qfOrIg_90
Copied: 8Pb85IRT-zKxKucLcNu0-Q_180
Copied: VJ8T6vmOXHP1VM8_Us4QmQ_0
Copied: mveidxFkjbohhkDAO08-WA_270
Copied: rNk96pi0MX78EeYnmxGDWg_0
Copied: bqYtjp_dH41_Iyp9gio36g_0
Copied: AzGEGPO4XsA5plKkgtM2HA_180
Copied: xjJKQAhJMdJmyYbZFpIUQw_270
Copied: dz7cjnTaR8qxOHlh8g1WDQ_0
Copied: f03wvl7JCE2S1Ijrf3ucHA_270
Copied: AqSC7JDSgpg1u4J2BT8ghQ_180
Copied: t3HWyXf8tN8-TM1yjx0MLw_270
Copied: Fq_jhN88jnJ5vj7MeBkCSA_180
Copied: N_5DiaOCb6RV1F4LNLI_-w_90
Copied: hdQnDq4HdLjvTRifdafANw_180
Copied: hdQnDq4HdLjvTRifdafANw_90
Copied: AMrM244R8JodM776pngQmA_90
Copied: lv0cQbniyi0-Tdq8dc822A_0
Copied: AYjMdqJHOkzL9dDZUcQxtQ_270
Copied: AYjMdqJHOkzL9dDZUcQxtQ_180
Copied: iRoKlJjaNYwJ703tkXqhPw_0
Copied: l4WotJ1cHGPQfeE9mIZE9g_0
Copied: _1ht7FnpasCCgtaVx6QgOQ_180
Copied: pjfHzYSviVkaf_dJuNEBUQ_90
Copied: bC8gL1ebk0Sf9vwQDhLNeQ_0
Copied: aq1fOb5GwMFkBKi5jq9BOA_270
Copied: bC8gL1ebk0Sf9vwQDhLNeQ_270
Copied: La_7ztckWNGS9JvNC_ei5A_0
Copied: JBUpItvi4oi2SArD98zxDQ_180
Copied: b7HgUhLTFo8YLcT-lA5LIQ_180
Copied: sn8i8bcGVc2lbyQYknUgOg_0
Copied: PQCdjVGz192IZYM4f2mhFQ_180
Copied: NwWN45SaR825R_HPbUkxIw_0
Copied: pjfHzYSviVkaf_dJuNEBUQ_0
Copied: n7b0lBRFt9Gp1Q0Lcf7Mhg_90
Copied: B-76fcTFG5zjUocBQmQbYA_180
Copied: MDIPTVXc0SJ2jhoJuWmnLQ_90
Copied: Ctv7aAF72Z74NnYXrnwnYg_90
Copied: PlREHMe3VMl759tLlq2-Mw_270
Copied: b7HgUhLTFo8YLcT-lA5LIQ_90
Copied: PlREHMe3VMl759tLlq2-Mw_180
Copied: T4-VFGHjoXOtnMLOAByo0Q_0
Copied: jgq_wuaWIR1eRFYWj1w1KQ_270
Copied: k_acZHy5t3HWljsghtg0qA_270
Copied: nXEsYNSKdOojYJvAFPhp3A_0
Copied: HRe28FKwSoo85PztCdlsqA_90
Copied: ZqJY-JsHD8CFlhjfYYfAUg_180
Copied: v4aWIjICX8H_X-yifVP-6A_90
Copied: pdx1JGcJ_3Vigi94ktcDZQ_0
Copied: LHONXI_nekpbnl24V_erOg_270
Copied: 1x-QlgsmCnlUFWZI5IN_iQ_90
Copied: 1x-QlgsmCnlUFWZI5IN_iQ_270
Copied: dxi3IdcTPDwaHw1Vnizpeg_180
Copied: NCe2X6_jDO4xPy57n6erOw_90
Copied: QPVYOPeIBWDPeQs3MbBbog_270
Copied: 6KdZVpw1Aqz9Lnm_ciieSg_270
Copied: OYkv2j0pCLl-6iHGEu3hEg_0
Copied: kFO3Xt46SDFaAUDW9IThCA_270
Copied: OYkv2j0pCLl-6iHGEu3hEg_90
Copied: hwYPsrQU55kTapJEHM5DLQ_0
Copied: bx_LoWoCCmaogzFK06wt-w_270
Copied: i7edESUhzw3BkLQL0P7C4A_0
Copied: yDbKUcSanp5tEPek6M0-yg_0
Copied: _DQQ0Ddyn7GoUt119nGtPg_0
Copied: AqF5mo-QV36ChDvBAckpUg_0
Copied: nffrZhq5qGXnz9_hm7L37g_180
Copied: wV61ulnf4Md5tDTlWonD7w_90
Copied: 7pSVWzlPIC_H1vkR3_1szQ_270
Copied: OOBW6DWNALPNdrcNjryUvw_0
Copied: bGTMrXUHnP-l9athbEVlCQ_90
Copied: xY0cY1LkMnaG-4pJrFD5ZQ_270
Copied: YxiFwLIFhbN3k0x29-4m8w_270
Copied: YxiFwLIFhbN3k0x29-4m8w_0
Copied: lZI335Nh3_RBM3h0NRFfyQ_0
Copied: 5Q0Bj06qDO2a9vVf_vIXCg_180
Copied: HOvLER6NrRffnzWZrcctTQ_0
Copied: oU90uGVmsLkbdVP11QI0qw_270
Copied: EIIrWrfKv6P1mmMibL0VOA_0
Copied: xNxe-zw7ZoheUA2YzRYQHg_0
Copied: cX6u3ZBKhmrAzcLUFbB46g_90
Copied: cRQf85OsFaDka-HOBjZF5Q_270
Copied: rvAPT7mUGoikaDqIvgs53Q_180
Copied: 5fy-JW8pfWJd5FUpMy_7VQ_270
Copied: ocEIeBNYUotC3WV3naq2Dg_180
Copied: Rtwz-xNN0Y6G2OVh0Af_zA_0
Copied: i4YSwMOHz8DO9xqqKMBcEQ_90
Copied: drBoz8Nga-MKQ3MVUq05gA_270
Copied: drBoz8Nga-MKQ3MVUq05gA_180
Copied: drBoz8Nga-MKQ3MVUq05gA_90
Copied: kOfL3rQZh6f4UNmnlzKELA_180
Copied: BTulBPGf8A10Y9SZWktpgg_0
Copied: pZaaOtHnZ_6371kwL9K_Qw_90
Copied: Xac2jKUpjhxhf17LZAAJAg_90
Copied: zMGOEXkZsRlM16i-76qS0w_270
Copied: e52V_XnEZXMNnKZojrqZdg_0
Copied: k0v7AW7Eu7zwm_fpIcurmA_0
Copied: e52V_XnEZXMNnKZojrqZdg_270
Copied: qX1v-xGBoBeGfMlIw5yCjg_270
Copied: eZ4DeK-nE_RBT4FlzTQqOQ_270
Copied: Xac2jKUpjhxhf17LZAAJAg_180
Copied: T4Pi78BDcNECsiiDNTKS_g_270
Copied: -7N9UT7bV0KnU1rnw4Zqog_180
Copied: 0atBlBbYZO1810XnRwKjjA_180
Copied: ua-1qPkieyBNoMvjka5FGg_270
Copied: s-P3Xk08XSm54w5DNrnkWQ_90
Copied: dT3DxqN9MlZ_0beKlO5zAQ_90
Copied: mRvkbuKpSEjDH9tONpPNkA_180
Copied: Zly6xgeJLf3IsH2P_cF0sg_180
Copied: TEZDWHsP3bSE36HoPoR_gg_90
Copied: 06Z5eN_hz_3_31DDj6AqeQ_180
Copied: wX1VKS0v7tvOEGrowJH5dg_0
Copied: lT6hC_UTX5h7Q8a9sOv3HQ_180
Copied: 88E8iSuS6GK6iXwN-bePLQ_180
Copied: nmHQtA_5ZFoVaWtBPH36yw_270
Copied: GvhSamIcHQUVEFIMMqwJ7g_0
Copied: TG2m5vk5KD7ezgyFatfTZQ_270
Copied: mjgJGawiMUEkdCF1Pgg3IA_90
Copied: 9rtTswMbsHeMgrUCaOXvfg_180
Copied: LCZth_xpHvhpzPu4cGAngg_180
Copied: LCZth_xpHvhpzPu4cGAngg_0
Copied: RGrRO2SSoelYxmikSNhf-A_90
Copied: 2st9GEHH5PgnZmNhtDU09g_270
Copied: -xT-rAv0zheI41q4N-NiHA_0
Copied: cG8CTfRKtZvgq6Ak-fAhVw_270
Copied: FFftACew2pE1xTU5nAGqRQ_90
Copied: FFftACew2pE1xTU5nAGqRQ_180
Copied: 0cPxqEqoSRbFY2wde2lRTQ_270
Copied: 4aNCYFSLbvHu5oFfAx2V_w_180
Copied: LUud_7WjOEiiCFUZBs3P9g_0
Copied: 4aNCYFSLbvHu5oFfAx2V_w_90
Copied: tyOk4bOiptPujTnNWGeyLQ_90
Copied: tyOk4bOiptPujTnNWGeyLQ_0
Copied: U2EykMo6UQxwyVdCWewbrQ_270
Copied: b2x_1RtqwsuCPVaX3JAdSQ_180
Copied: 5-71-vD-c_K2uJB0ttxj3g_270
Copied: nnTHzBM209QtIpJPiwS67A_0
Copied: ahbbaadcOe8GwrzDBXeyMQ_180
Copied: uJje-uKLnmmAYvtPW4ZXow_180
Copied: yE8R6o41RcoG6La_YvjCVA_270
Copied: aPs-KfKUOvTeoKsD-fLqvw_270
Copied: u3QhidNhKx_NbORjAJdH2g_90
Copied: _7t4KqXXQIE9CIHnMVsDIg_0
Copied: ZOjsbR4jQisymLJ_k7OhLQ_0
Copied: q1FBFYVDO5aJM8FDRRP0Cw_270
Copied: 9jfIez4KwejHE2hc6GHN0Q_180
Copied: e4WennEil-di4c7gEmZmaA_270
Copied: fZYhQ4cnhC4c1Lsegfx8lw_180
Copied: vHejWr_750-sUD2AkyHTEQ_180
Copied: Mw3NOktRyQHVRPbohEU7zA_180
Copied: KJKW_FvX5umZe0SvUnrwQw_180
Copied: xdkQk9Yq8606esgkfe8v2A_270
Copied: LUud_7WjOEiiCFUZBs3P9g_270
Copied: 6IjnXX4ahEjmZ9uk2efw7A_90
Copied: sRq0N8DyqEWKODSqnRsQig_0
Copied: y9N5W6tiaI66Z2litmZPlA_180
Copied: ofPuTBgXBeXcsTIIJbtMeA_180
Copied: rNg6atINNMIp-WQWh7Vwqg_0
Copied: Fu2l4cQcLQZD5w8eM4Lj8A_0
Copied: 60zIDFhv_EPYvm9Z2TnGvA_270
Copied: WBhwhKZr_Nn2XkkbZZmUjg_0
Copied: VVVa4jUbVGCqsj8IQDTtCg_270
Copied: ofPuTBgXBeXcsTIIJbtMeA_90
Copied: yTjLiLa754umyw4-qW-Z5g_270
Copied: ZsgPssjis-XzDOp9AQKWJw_180
Copied: INtw9koWuXHd7kCzLTujwA_90
Copied: 2VitjmnhTZ77sPlgQwtc7g_180
Copied: kaRRHxGYDzfOgcr3BPAYEQ_90
Copied: CewkpjI3Qg3W_cDe_tHF9g_270

# Check test set image

In [23]:
file = '/Users/wenlanzhang/Downloads/PhD_UCL/Data/Waste/img/vl_Faith.csv'
df = pd.read_csv(file)
df

,img_name,year,month,day,hour,lat,lon,panoid,img_dir,exist,yolo_conf,yolo_bbox,yolo_num,prediction,Domestic,Construction
0,014652c8e7e36740a0fe390870e19052b70a2e9a40,2015,8,22,9,-1.268261,36.821169,NaN,Faith/,True,[],[],0,pending,NaN,NaN
1,20161115_133906,2016,11,15,13,-1.317033,36.791557,NaN,Faith/,True,"[0.4858177900314331, 0.3025636374950409]","[[28.5167236328125, 1253.941650390625, 776.544...",2,yes,Y,N
2,IMG_1450,2016,11,14,13,-1.289936,36.769103,NaN,Faith/,True,[],[],0,pending,NaN,NaN
3,IMG_1336,2016,11,14,11,-1.303164,36.855931,NaN,Faith/,True,[],[],0,pending,NaN,NaN
4,20161115_134714,2016,11,15,13,-1.315711,36.790286,NaN,Faith/,True,[],[],0,pending,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
812,IMG_1111,2016,11,14,10,-1.264403,36.802028,NaN,Faith/,True,[],[],0,pending,NaN,NaN
813,IMG_1449,2016,11,14,13,-1.289819,36.766542,NaN,Faith/,True,[],[],0,pending,NaN,NaN
814,IMG_1461,2016,11,14,13,-1.292219,36.786992,NaN,Faith/,True,[],[],0,pending,NaN,NaN
815,IMG_1307,2016,11,14,11,-1.277408,36.885069,NaN,Faith/,True,[],[],0,pending,NaN,NaN
816,IMG_1313,2016,11,14,11,-1.285467,36.883256,NaN,Faith/,True,[],[],0,pending,NaN,NaN

In [26]:
df[df['yolo_num'] != 0 ]

,img_name,year,month,day,hour,lat,lon,panoid,img_dir,exist,yolo_conf,yolo_bbox,yolo_num,prediction,Domestic,Construction
1,20161115_133906,2016,11,15,13,-1.317033,36.791557,NaN,Faith/,True,"[0.4858177900314331, 0.3025636374950409]","[[28.5167236328125, 1253.941650390625, 776.544...",2,yes,Y,N
22,20161115_131903,2016,11,15,13,-1.319186,36.793816,NaN,Faith/,True,"[0.39657795429229736, 0.26016801595687866]","[[0.0, 1408.639892578125, 1536.0, 2483.7131347...",2,yes,Y,Y
23,01d56d3da7a7276ef16b2c8e2196246655518296d0,2015,8,22,13,-1.312889,36.867031,NaN,Faith/,True,"[0.34240347146987915, 0.3375213146209717]","[[337.49151611328125, 889.6815185546875, 2056....",2,yes,Y,N
27,20161115_131056,2016,11,15,13,-1.319284,36.794905,NaN,Faith/,True,[0.29595947265625],"[[1217.840576171875, 2147.228515625, 1536.0, 2...",1,yes,Y,N
47,DSC_0192,2015,8,22,14,-1.318680,36.829600,NaN,Faith/,True,[0.30729740858078003],"[[495.8659362792969, 0.0, 2068.837158203125, 5...",1,no,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
728,20161115_130555,2016,11,15,13,NaN,NaN,NaN,Faith/,True,[0.3984083831310272],"[[4.5418701171875, 1186.5528564453125, 632.190...",1,yes,Y,N
734,DSC_0163,2015,8,22,13,-1.311824,36.866794,NaN,Faith/,True,"[0.39874503016471863, 0.367857426404953, 0.332...","[[1206.91259765625, 1061.9073486328125, 2787.4...",7,yes,Y,N
761,20161115_124643,2016,11,15,12,-1.316081,36.799083,NaN,Faith/,True,[0.3415820002555847],"[[88.9415283203125, 996.94091796875, 1536.0, 2...",1,yes,Y,Y
784,01e077d752bc22c8f22f8e5e006354d18186d51dce,2015,8,22,12,-1.310419,36.868431,NaN,Faith/,True,"[0.397571861743927, 0.3488955795764923]","[[9.140625, 1417.7430419921875, 1536.0, 1690.7...",2,no,NaN,NaN
796,20161115_124457,2016,11,15,12,-1.320061,36.797812,NaN,Faith/,True,"[0.5386744737625122, 0.3723387122154236]","[[0.0, 2201.3876953125, 621.82763671875, 2560....",2,yes,Y,Y

In [24]:
df[df['prediction'] == 'yes' ]

,img_name,year,month,day,hour,lat,lon,panoid,img_dir,exist,yolo_conf,yolo_bbox,yolo_num,prediction,Domestic,Construction
1,20161115_133906,2016,11,15,13,-1.317033,36.791557,NaN,Faith/,True,"[0.4858177900314331, 0.3025636374950409]","[[28.5167236328125, 1253.941650390625, 776.544...",2,yes,Y,N
22,20161115_131903,2016,11,15,13,-1.319186,36.793816,NaN,Faith/,True,"[0.39657795429229736, 0.26016801595687866]","[[0.0, 1408.639892578125, 1536.0, 2483.7131347...",2,yes,Y,Y
23,01d56d3da7a7276ef16b2c8e2196246655518296d0,2015,8,22,13,-1.312889,36.867031,NaN,Faith/,True,"[0.34240347146987915, 0.3375213146209717]","[[337.49151611328125, 889.6815185546875, 2056....",2,yes,Y,N
27,20161115_131056,2016,11,15,13,-1.319284,36.794905,NaN,Faith/,True,[0.29595947265625],"[[1217.840576171875, 2147.228515625, 1536.0, 2...",1,yes,Y,N
53,20161115_140900,2016,11,15,14,-1.316989,36.789524,NaN,Faith/,True,[0.5429480075836182],"[[497.2809753417969, 863.2463989257812, 1345.1...",1,yes,Y,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
724,01ab60a11770f64151fecdcfc8e38e1ef0da0cb574,2015,8,22,9,-1.270211,36.803525,NaN,Faith/,True,[0.3336052894592285],"[[0.0, 1251.2996826171875, 904.1473999023438, ...",1,yes,N,Y
728,20161115_130555,2016,11,15,13,NaN,NaN,NaN,Faith/,True,[0.3984083831310272],"[[4.5418701171875, 1186.5528564453125, 632.190...",1,yes,Y,N
734,DSC_0163,2015,8,22,13,-1.311824,36.866794,NaN,Faith/,True,"[0.39874503016471863, 0.367857426404953, 0.332...","[[1206.91259765625, 1061.9073486328125, 2787.4...",7,yes,Y,N
761,20161115_124643,2016,11,15,12,-1.316081,36.799083,NaN,Faith/,True,[0.3415820002555847],"[[88.9415283203125, 996.94091796875, 1536.0, 2...",1,yes,Y,Y
796,20161115_124457,2016,11,15,12,-1.320061,36.797812,NaN,Faith/,True,"[0.5386744737625122, 0.3723387122154236]","[[0.0, 2201.3876953125, 621.82763671875, 2560....",2,yes,Y,Y

In [25]:
df[df['Domestic'] == 'Y' ]

,img_name,year,month,day,hour,lat,lon,panoid,img_dir,exist,yolo_conf,yolo_bbox,yolo_num,prediction,Domestic,Construction
1,20161115_133906,2016,11,15,13,-1.317033,36.791557,NaN,Faith/,True,"[0.4858177900314331, 0.3025636374950409]","[[28.5167236328125, 1253.941650390625, 776.544...",2,yes,Y,N
22,20161115_131903,2016,11,15,13,-1.319186,36.793816,NaN,Faith/,True,"[0.39657795429229736, 0.26016801595687866]","[[0.0, 1408.639892578125, 1536.0, 2483.7131347...",2,yes,Y,Y
23,01d56d3da7a7276ef16b2c8e2196246655518296d0,2015,8,22,13,-1.312889,36.867031,NaN,Faith/,True,"[0.34240347146987915, 0.3375213146209717]","[[337.49151611328125, 889.6815185546875, 2056....",2,yes,Y,N
27,20161115_131056,2016,11,15,13,-1.319284,36.794905,NaN,Faith/,True,[0.29595947265625],"[[1217.840576171875, 2147.228515625, 1536.0, 2...",1,yes,Y,N
53,20161115_140900,2016,11,15,14,-1.316989,36.789524,NaN,Faith/,True,[0.5429480075836182],"[[497.2809753417969, 863.2463989257812, 1345.1...",1,yes,Y,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
722,20161115_123511,2016,11,15,12,-1.313416,36.799491,NaN,Faith/,True,[0.3125104308128357],"[[179.71334838867188, 902.5142822265625, 390.0...",1,yes,Y,Y
728,20161115_130555,2016,11,15,13,NaN,NaN,NaN,Faith/,True,[0.3984083831310272],"[[4.5418701171875, 1186.5528564453125, 632.190...",1,yes,Y,N
734,DSC_0163,2015,8,22,13,-1.311824,36.866794,NaN,Faith/,True,"[0.39874503016471863, 0.367857426404953, 0.332...","[[1206.91259765625, 1061.9073486328125, 2787.4...",7,yes,Y,N
761,20161115_124643,2016,11,15,12,-1.316081,36.799083,NaN,Faith/,True,[0.3415820002555847],"[[88.9415283203125, 996.94091796875, 1536.0, 2...",1,yes,Y,Y
796,20161115_124457,2016,11,15,12,-1.320061,36.797812,NaN,Faith/,True,"[0.5386744737625122, 0.3723387122154236]","[[0.0, 2201.3876953125, 621.82763671875, 2560....",2,yes,Y,Y

# Google has duplicates

In [9]:
# df = pd.read_csv('/Users/wenlanzhang/Downloads/PhD_UCL/Data/Waste/img/Del_Google_dup/vl_Google.csv')
# df = pd.read_csv('/Users/wenlanzhang/Downloads/PhD_UCL/Data/Waste/img/Del_Google_dup/pano_nairobi.csv')
df = pd.read_csv('/Users/wenlanzhang/Downloads/PhD_UCL/Data/Waste/img/vl_Google.csv')

df

/var/folders/2_/nk9j6sb901n_fk5dz_9vtqj80000gn/T/ipykernel_56401/3591232776.py:3: DtypeWarning: Columns (14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/Users/wenlanzhang/Downloads/PhD_UCL/Data/Waste/img/vl_Google.csv')

,panoid,lat,lon,year,month,img_name,img_dir,exist,day,hour,yolo_conf,yolo_bbox,yolo_num,prediction,Domestic,Construction
0,KdbXvhlAf5Sqjw-hwBb_Ww,-1.240368,36.928039,2022,2,KdbXvhlAf5Sqjw-hwBb_Ww_0,Google/K/d/,True,NaN,NaN,[0.4317765235900879],"[[288.10223388671875, 157.34405517578125, 365....",1,yes,N,Y
1,1Xyfr0j4E3Gx6_Coadexow,-1.282457,36.751317,2018,2,1Xyfr0j4E3Gx6_Coadexow_180,Google/1/X/,True,NaN,NaN,[0.4008658230304718],"[[298.3153076171875, 184.95751953125, 400.0, 2...",1,yes,Y,Y
2,AgROMWzI6TjbZRpV6iKJDg,-1.284253,36.902957,2021,7,AgROMWzI6TjbZRpV6iKJDg_270,Google/A/g/,True,NaN,NaN,[0.2816741466522217],"[[264.65301513671875, 209.8660125732422, 399.6...",1,yes,N,Y
3,AgROMWzI6TjbZRpV6iKJDg,-1.284253,36.902957,2021,7,AgROMWzI6TjbZRpV6iKJDg_180,Google/A/g/,True,NaN,NaN,[0.288665235042572],"[[0.0, 205.2751922607422, 72.42560577392578, 2...",1,yes,N,Y
4,nTRlyH7aG8CmTfOI1_akgw,-1.279155,36.719541,2018,3,nTRlyH7aG8CmTfOI1_akgw_0,Google/n/T/,True,NaN,NaN,"[0.5433366894721985, 0.3535045087337494]","[[50.18629455566406, 221.9884033203125, 188.91...",2,yes,Y,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
453359,P8R4aL4MRoJ3I1BAqd9log,-1.243328,36.658198,2021,8,P8R4aL4MRoJ3I1BAqd9log_180,Google/P/8/,True,NaN,NaN,[],[],0,pending,NaN,NaN
453360,P8R4aL4MRoJ3I1BAqd9log,-1.243328,36.658198,2021,8,P8R4aL4MRoJ3I1BAqd9log_270,Google/P/8/,True,NaN,NaN,[],[],0,pending,NaN,NaN
453361,Cj_q1UE8aOoi93oRvPOrKA,-1.223843,36.779281,2018,2,Cj_q1UE8aOoi93oRvPOrKA_0,Google/C/j/,True,NaN,NaN,[],[],0,pending,NaN,NaN
453362,Cj_q1UE8aOoi93oRvPOrKA,-1.223843,36.779281,2018,2,Cj_q1UE8aOoi93oRvPOrKA_90,Google/C/j/,True,NaN,NaN,[],[],0,pending,NaN,NaN
453363,TWPhlJpEwnG-oUaWnGSVeg,-1.296458,36.815322,2018,2,TWPhlJpEwnG-oUaWnGSVeg_0,Google/T/W/,True,NaN,NaN,[0.701630711555481],"[[164.29873657226562, 164.19412231445312, 387....",1,no,NaN,NaN

In [10]:
# df['img_name'].duplicated().sum()
df[df['img_name'].duplicated()]
# df[df['panoid'].duplicated()]

Empty DataFrame
Columns: [panoid, lat, lon, year, month, img_name, img_dir, exist, day, hour, yolo_conf, yolo_bbox, yolo_num, prediction, Domestic, Construction]
Index: []

In [89]:
126414 - 13073
# pan

113341

In [65]:
505656-52292
# img

453364

In [90]:
# # Pan 
# df_filtered = df.drop_duplicates(subset=['panoid'])
# df_filtered

,Unnamed: 0,id,panoid,lat,lon,year,month,marker
0,0,21,khlXWXsuIX7rodKwi1fDAw,-1.347984,36.904885,2021.0,10.0,True
1,1,22,E2SmMwWyLCmPNFOl5-XhxA,-1.286567,36.804547,2021.0,9.0,True
2,2,23,_YVC8LQsymlhhIFp0go_7g,-1.286704,36.804986,2021.0,9.0,True
3,3,24,BOFAYq7l0PF7Lg2_Kn258w,-1.286835,36.805475,2021.0,9.0,True
4,4,25,K3_Pj41onnAOLziZiZeGIw,-1.286968,36.805993,2021.0,9.0,True
...,...,...,...,...,...,...,...,...
126404,126409,213592,4tAQn57-4Vq_YmxbaJwNMA,-1.227151,36.883277,2021.0,12.0,True
126407,126412,213596,0UjoZN0DN80D_cBRAHcvmw,-1.313533,36.854902,2021.0,8.0,True
126409,126414,213600,f1wVXeQLsTbfDdX1IgZvSg,-1.318228,36.854663,2018.0,1.0,True
126411,126416,213604,xxfDzMmO__DBRl9my1XA1g,-1.289720,36.812128,2018.0,2.0,True
126412,126417,213605,joG2cf6Yga4GW1DA2UdVcw,-1.289322,36.811855,2021.0,7.0,True

In [81]:
# # Basic / yolo
# df_filtered = df.drop_duplicates()
# df_filtered

,Unnamed: 0,id,panoid,lat,lon,year,month,marker
0,0,21,khlXWXsuIX7rodKwi1fDAw,-1.347984,36.904885,2021.0,10.0,True
1,1,22,E2SmMwWyLCmPNFOl5-XhxA,-1.286567,36.804547,2021.0,9.0,True
2,2,23,_YVC8LQsymlhhIFp0go_7g,-1.286704,36.804986,2021.0,9.0,True
3,3,24,BOFAYq7l0PF7Lg2_Kn258w,-1.286835,36.805475,2021.0,9.0,True
4,4,25,K3_Pj41onnAOLziZiZeGIw,-1.286968,36.805993,2021.0,9.0,True
...,...,...,...,...,...,...,...,...
126409,126414,213600,f1wVXeQLsTbfDdX1IgZvSg,-1.318228,36.854663,2018.0,1.0,True
126410,126415,213603,U3VouvYaIateSuoSEz6I9Q,-1.318704,36.853164,2021.0,7.0,True
126411,126416,213604,xxfDzMmO__DBRl9my1XA1g,-1.289720,36.812128,2018.0,2.0,True
126412,126417,213605,joG2cf6Yga4GW1DA2UdVcw,-1.289322,36.811855,2021.0,7.0,True
126413,126418,213607,gXJyEdt-aPTaxcnaDPf9DA,-1.277536,36.899947,2022.0,5.0,True

In [76]:
# # cpm__Google

# # Identify duplicated 'img_name' entries where 'prediction' values differ
# df_filtered = df.sort_values(by='prediction', ascending=False).drop_duplicates(subset=['img_name'], keep='first')

# # Reset index if needed
# df_filtered = df_filtered.reset_index(drop=True)
# df_filtered

,panoid,lat,lon,year,month,img_name,img_dir,exist,day,hour,yolo_conf,yolo_bbox,yolo_num,prediction,Domestic,Construction
0,KdbXvhlAf5Sqjw-hwBb_Ww,-1.240368,36.928039,2022,2,KdbXvhlAf5Sqjw-hwBb_Ww_0,Google/K/d/,True,NaN,NaN,[0.4317765235900879],"[[288.10223388671875, 157.34405517578125, 365....",1,yes,N,Y
1,P77AIHCsD7UVPPH1G4ON2A,-1.482376,36.967405,2022,3,P77AIHCsD7UVPPH1G4ON2A_0,Google/P/7/,True,NaN,NaN,[0.41588473320007324],"[[49.862060546875, 0.0, 393.982177734375, 64.1...",1,yes,N,N
2,ZRhya_zJaFh7hPzh48ZeMA,-1.290648,36.841625,2021,8,ZRhya_zJaFh7hPzh48ZeMA_180,Google/Z/R/,True,NaN,NaN,"[0.4105248749256134, 0.36375853419303894]","[[0.0, 247.82907104492188, 159.00010681152344,...",2,yes,Y,N
3,Acb5lAT2RQaJ6RlV-XWhyQ,-1.342766,36.872262,2018,10,Acb5lAT2RQaJ6RlV-XWhyQ_270,Google/A/c/,True,NaN,NaN,[0.3776053190231323],"[[1.4140129089355469, 195.28640747070312, 244....",1,yes,N,N
4,ZWz0Ej5AcnDC7CNFiXc1AQ,-1.160560,36.751363,2022,2,ZWz0Ej5AcnDC7CNFiXc1AQ_270,Google/Z/W/,True,NaN,NaN,[0.2515825033187866],"[[0.0, 155.95094299316406, 120.75576782226562,...",1,yes,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
453359,aoiNj8oNuV_dNtUhYW7J2w,-1.262548,37.004526,2018,2,aoiNj8oNuV_dNtUhYW7J2w_0,Google/a/o/,True,NaN,NaN,[0.2690472900867462],"[[277.66583251953125, 248.51535034179688, 400....",1,no,NaN,NaN
453360,zOFziINxfLUNS75ER0CagQ,-1.190100,36.738571,2022,2,zOFziINxfLUNS75ER0CagQ_0,Google/z/O/,True,NaN,NaN,[0.26840847730636597],"[[306.6356201171875, 0.0, 400.0, 44.8169708251...",1,no,NaN,NaN
453361,2z_KXgdIFwNpI15jax1T2A,-1.281143,36.740477,2018,3,2z_KXgdIFwNpI15jax1T2A_90,Google/2/z/,True,NaN,NaN,[0.6036550402641296],"[[188.88262939453125, 191.865234375, 399.45080...",1,no,NaN,NaN
453362,036M9--S93eXfevopckA3g,-1.301988,36.753402,2021,8,036M9--S93eXfevopckA3g_270,Google/0/3/,True,NaN,NaN,[0.27903100848197937],"[[3.163738250732422, 117.01132202148438, 318.1...",1,no,NaN,NaN
453363,TWPhlJpEwnG-oUaWnGSVeg,-1.296458,36.815322,2018,2,TWPhlJpEwnG-oUaWnGSVeg_0,Google/T/W/,True,NaN,NaN,[0.701630711555481],"[[164.29873657226562, 164.19412231445312, 387....",1,no,NaN,NaN

In [4]:
# update_Google

# Identify duplicated 'img_name' entries where 'Domestic' values differ
df_filtered = df.sort_values(by="Domestic", key=lambda x: x.notna(), ascending=False).drop_duplicates(subset="img_name", keep="first")

df_filtered

,panoid,lat,lon,year,month,img_name,img_dir,exist,day,hour,yolo_conf,yolo_bbox,yolo_num,prediction,Domestic,Construction
0,KdbXvhlAf5Sqjw-hwBb_Ww,-1.240368,36.928039,2022,2,KdbXvhlAf5Sqjw-hwBb_Ww_0,Google/K/d/,True,NaN,NaN,[0.4317765235900879],"[[288.10223388671875, 157.34405517578125, 365....",1,yes,N,Y
6182,1Xyfr0j4E3Gx6_Coadexow,-1.282457,36.751317,2018,2,1Xyfr0j4E3Gx6_Coadexow_180,Google/1/X/,True,NaN,NaN,[0.4008658230304718],"[[298.3153076171875, 184.95751953125, 400.0, 2...",1,yes,Y,Y
6176,AgROMWzI6TjbZRpV6iKJDg,-1.284253,36.902957,2021,7,AgROMWzI6TjbZRpV6iKJDg_270,Google/A/g/,True,NaN,NaN,[0.2816741466522217],"[[264.65301513671875, 209.8660125732422, 399.6...",1,yes,N,Y
6177,AgROMWzI6TjbZRpV6iKJDg,-1.284253,36.902957,2021,7,AgROMWzI6TjbZRpV6iKJDg_180,Google/A/g/,True,NaN,NaN,[0.288665235042572],"[[0.0, 205.2751922607422, 72.42560577392578, 2...",1,yes,N,Y
6178,nTRlyH7aG8CmTfOI1_akgw,-1.279155,36.719541,2018,3,nTRlyH7aG8CmTfOI1_akgw_0,Google/n/T/,True,NaN,NaN,"[0.5433366894721985, 0.3535045087337494]","[[50.18629455566406, 221.9884033203125, 188.91...",2,yes,Y,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157201,P8R4aL4MRoJ3I1BAqd9log,-1.243328,36.658198,2021,8,P8R4aL4MRoJ3I1BAqd9log_180,Google/P/8/,True,NaN,NaN,[],[],0,pending,NaN,NaN
157200,P8R4aL4MRoJ3I1BAqd9log,-1.243328,36.658198,2021,8,P8R4aL4MRoJ3I1BAqd9log_270,Google/P/8/,True,NaN,NaN,[],[],0,pending,NaN,NaN
157199,Cj_q1UE8aOoi93oRvPOrKA,-1.223843,36.779281,2018,2,Cj_q1UE8aOoi93oRvPOrKA_0,Google/C/j/,True,NaN,NaN,[],[],0,pending,NaN,NaN
157198,Cj_q1UE8aOoi93oRvPOrKA,-1.223843,36.779281,2018,2,Cj_q1UE8aOoi93oRvPOrKA_90,Google/C/j/,True,NaN,NaN,[],[],0,pending,NaN,NaN
453958,TWPhlJpEwnG-oUaWnGSVeg,-1.296458,36.815322,2018,2,TWPhlJpEwnG-oUaWnGSVeg_0,Google/T/W/,True,NaN,NaN,[0.701630711555481],"[[164.29873657226562, 164.19412231445312, 387....",1,no,NaN,NaN

In [6]:
df_filtered.to_csv("/Users/wenlanzhang/Downloads/PhD_UCL/Data/Waste/img/vl_Google.csv", index=False)

In [5]:
# Check duplicate

# df_g[df_g['img_name'].duplicated()]
df_filtered[df_filtered['img_name'] == '-NXOSr3x7LzGKlvTcWqnHw_270']

,panoid,lat,lon,year,month,img_name,img_dir,exist,day,hour,yolo_conf,yolo_bbox,yolo_num,prediction,Domestic,Construction
25,-NXOSr3x7LzGKlvTcWqnHw,-1.382642,36.676872,2018,5,-NXOSr3x7LzGKlvTcWqnHw_270,Google/-/N/,True,NaN,NaN,[0.6295191049575806],"[[222.34576416015625, 213.51779174804688, 398....",1,yes,N,Y

# Combine 3 to 1

In [3]:
Base = '/Users/wenlanzhang/Downloads/PhD_UCL/Data/Waste/img/'
df_F = pd.read_csv(Base + 'vl_Faith.csv')
df_G = pd.read_csv(Base + 'vl_Google.csv')
df_Z = pd.read_csv(Base + 'vl_ZWL.csv')

df_G

/var/folders/2_/nk9j6sb901n_fk5dz_9vtqj80000gn/T/ipykernel_94340/2138352437.py:3: DtypeWarning: Columns (14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df_G = pd.read_csv(Base + 'vl_Google.csv')

,panoid,lat,lon,year,month,img_name,img_dir,exist,day,hour,yolo_conf,yolo_bbox,yolo_num,prediction,Domestic,Construction
0,KdbXvhlAf5Sqjw-hwBb_Ww,-1.240368,36.928039,2022,2,KdbXvhlAf5Sqjw-hwBb_Ww_0,Google/K/d/,True,NaN,NaN,[0.4317765235900879],"[[288.10223388671875, 157.34405517578125, 365....",1,yes,N,Y
1,1Xyfr0j4E3Gx6_Coadexow,-1.282457,36.751317,2018,2,1Xyfr0j4E3Gx6_Coadexow_180,Google/1/X/,True,NaN,NaN,[0.4008658230304718],"[[298.3153076171875, 184.95751953125, 400.0, 2...",1,yes,Y,Y
2,AgROMWzI6TjbZRpV6iKJDg,-1.284253,36.902957,2021,7,AgROMWzI6TjbZRpV6iKJDg_270,Google/A/g/,True,NaN,NaN,[0.2816741466522217],"[[264.65301513671875, 209.8660125732422, 399.6...",1,yes,N,Y
3,AgROMWzI6TjbZRpV6iKJDg,-1.284253,36.902957,2021,7,AgROMWzI6TjbZRpV6iKJDg_180,Google/A/g/,True,NaN,NaN,[0.288665235042572],"[[0.0, 205.2751922607422, 72.42560577392578, 2...",1,yes,N,Y
4,nTRlyH7aG8CmTfOI1_akgw,-1.279155,36.719541,2018,3,nTRlyH7aG8CmTfOI1_akgw_0,Google/n/T/,True,NaN,NaN,"[0.5433366894721985, 0.3535045087337494]","[[50.18629455566406, 221.9884033203125, 188.91...",2,yes,Y,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
453359,P8R4aL4MRoJ3I1BAqd9log,-1.243328,36.658198,2021,8,P8R4aL4MRoJ3I1BAqd9log_180,Google/P/8/,True,NaN,NaN,[],[],0,pending,NaN,NaN
453360,P8R4aL4MRoJ3I1BAqd9log,-1.243328,36.658198,2021,8,P8R4aL4MRoJ3I1BAqd9log_270,Google/P/8/,True,NaN,NaN,[],[],0,pending,NaN,NaN
453361,Cj_q1UE8aOoi93oRvPOrKA,-1.223843,36.779281,2018,2,Cj_q1UE8aOoi93oRvPOrKA_0,Google/C/j/,True,NaN,NaN,[],[],0,pending,NaN,NaN
453362,Cj_q1UE8aOoi93oRvPOrKA,-1.223843,36.779281,2018,2,Cj_q1UE8aOoi93oRvPOrKA_90,Google/C/j/,True,NaN,NaN,[],[],0,pending,NaN,NaN
453363,TWPhlJpEwnG-oUaWnGSVeg,-1.296458,36.815322,2018,2,TWPhlJpEwnG-oUaWnGSVeg_0,Google/T/W/,True,NaN,NaN,[0.701630711555481],"[[164.29873657226562, 164.19412231445312, 387....",1,no,NaN,NaN

In [5]:
# Check if all DataFrames have the same columns
def check_same_columns(*dfs):
    columns_set = [set(df.columns) for df in dfs]
    return all(columns_set[0] == cols for cols in columns_set)

# Usage
if check_same_columns(df_F, df_G, df_Z):
    print("All DataFrames have the same columns.")
else:
    print("DataFrames have different columns.")

All DataFrames have the same columns.

In [7]:
merged_df = pd.concat([df_F, df_G, df_Z], ignore_index=True)
merged_df

,img_name,year,month,day,hour,lat,lon,panoid,img_dir,exist,yolo_conf,yolo_bbox,yolo_num,prediction,Domestic,Construction
0,014652c8e7e36740a0fe390870e19052b70a2e9a40,2015,8,22.0,9.0,-1.268261,36.821169,NaN,Faith/,True,[],[],0,pending,NaN,NaN
1,20161115_133906,2016,11,15.0,13.0,-1.317033,36.791557,NaN,Faith/,True,"[0.4858177900314331, 0.3025636374950409]","[[28.5167236328125, 1253.941650390625, 776.544...",2,yes,Y,N
2,IMG_1450,2016,11,14.0,13.0,-1.289936,36.769103,NaN,Faith/,True,[],[],0,pending,NaN,NaN
3,IMG_1336,2016,11,14.0,11.0,-1.303164,36.855931,NaN,Faith/,True,[],[],0,pending,NaN,NaN
4,20161115_134714,2016,11,15.0,13.0,-1.315711,36.790286,NaN,Faith/,True,[],[],0,pending,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
457106,IMG_0794,2023,2,20.0,11.0,-1.361619,36.763569,NaN,ZWL/,True,[],[],0,pending,NaN,NaN
457107,IMG_20230211_130003,2023,2,11.0,13.0,NaN,NaN,NaN,ZWL/,True,[],[],0,pending,NaN,NaN
457108,IMG_8486,2023,2,11.0,11.0,-1.278647,37.038514,NaN,ZWL/,True,[],[],0,pending,NaN,NaN
457109,IMG_8492,2023,2,11.0,11.0,-1.278183,37.033633,NaN,ZWL/,True,[],[],0,pending,NaN,NaN
457110,IMG_20230211_124704,2023,2,11.0,12.0,NaN,NaN,NaN,ZWL/,True,[],[],0,pending,NaN,NaN

In [12]:
merged_df.to_csv(Base + "Combined_SVI.csv", index=False)

In [14]:
filter_df = merged_df[merged_df['Domestic'] == 'Y' ]
filter_df

,img_name,year,month,day,hour,lat,lon,panoid,img_dir,exist,yolo_conf,yolo_bbox,yolo_num,prediction,Domestic,Construction
1,20161115_133906,2016,11,15.0,13.0,-1.317033,36.791557,NaN,Faith/,True,"[0.4858177900314331, 0.3025636374950409]","[[28.5167236328125, 1253.941650390625, 776.544...",2,yes,Y,N
22,20161115_131903,2016,11,15.0,13.0,-1.319186,36.793816,NaN,Faith/,True,"[0.39657795429229736, 0.26016801595687866]","[[0.0, 1408.639892578125, 1536.0, 2483.7131347...",2,yes,Y,Y
23,01d56d3da7a7276ef16b2c8e2196246655518296d0,2015,8,22.0,13.0,-1.312889,36.867031,NaN,Faith/,True,"[0.34240347146987915, 0.3375213146209717]","[[337.49151611328125, 889.6815185546875, 2056....",2,yes,Y,N
27,20161115_131056,2016,11,15.0,13.0,-1.319284,36.794905,NaN,Faith/,True,[0.29595947265625],"[[1217.840576171875, 2147.228515625, 1536.0, 2...",1,yes,Y,N
53,20161115_140900,2016,11,15.0,14.0,-1.316989,36.789524,NaN,Faith/,True,[0.5429480075836182],"[[497.2809753417969, 863.2463989257812, 1345.1...",1,yes,Y,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
457050,IMG_7819,2023,2,9.0,12.0,-1.312181,36.870267,NaN,ZWL/,True,"[0.7798725366592407, 0.3829556405544281]","[[2542.110595703125, 1953.2369384765625, 4013....",2,yes,Y,N
457082,IMG_20230211_122605,2023,2,11.0,12.0,NaN,NaN,NaN,ZWL/,True,[0.46833276748657227],"[[1749.275634765625, 1453.630859375, 3514.6911...",1,yes,Y,Y
457088,IMG_6440,2023,2,3.0,12.0,-1.315433,36.790297,NaN,ZWL/,True,[0.4961458146572113],"[[2177.84375, 844.6050415039062, 3318.18994140...",1,yes,Y,N
457095,IMG_6468,2023,2,3.0,13.0,-1.306761,36.783131,NaN,ZWL/,True,"[0.41568389534950256, 0.2513587474822998]","[[2769.41552734375, 2133.168701171875, 4032.0,...",2,yes,Y,N
457104,IMG_6483,2023,2,3.0,13.0,-1.305792,36.785050,NaN,ZWL/,True,"[0.6916729807853699, 0.5377081036567688]","[[13.214465141296387, 1253.88720703125, 2881.9...",2,yes,Y,N

In [15]:
filter_df.to_csv(Base + "Correct_SVI.csv", index=False)