This is to copy part images to a path for check / label

# Check location

In [2]:
import pandas as pd

In [3]:
df_20240113 = pd.read_csv('/Users/wenlanzhang/PycharmProjects/SVI_Waste/Data/output_20240113.csv')
df_20240113.drop(columns=['pk', 'id', 'marker'], inplace=True)
df_20240113_sorted = df_20240113.sort_values(by='panoid')
df_20240113_sorted = df_20240113_sorted.reset_index()
df_20240113_sorted

,index,panoid,lat,lon,year,month,ang_0,ang_90,ang_180,ang_270
0,16186,---kW5kLNFT2eKu77K0BSg,-1.337135,36.735751,2021.0,7.0,0.000000,0.000000,0.000000,0.000000
1,16185,---kW5kLNFT2eKu77K0BSg,-1.337135,36.735751,2021.0,7.0,0.000000,0.000000,0.000000,0.000000
2,28639,--3w2NTa6dWsDSlB7lQqiA,-1.304348,36.742095,2018.0,1.0,0.000000,0.000000,0.000000,0.000000
3,28541,--5kqrbr7DiSKTlMm6mmZw,-1.279489,36.716701,2018.0,2.0,0.000000,0.657491,0.000000,0.000000
4,93757,--6rir7WBjJoKcL5UgHzFw,-1.284360,36.972830,2018.0,2.0,0.000000,0.000000,0.000000,0.683942
...,...,...,...,...,...,...,...,...,...,...
126409,107337,zzvWdmTO_4oxT63l1GeS7w,-1.300941,36.811408,2018.0,3.0,0.643877,0.000000,0.000000,0.000000
126410,98735,zzvWdmTO_4oxT63l1GeS7w,-1.300941,36.811408,2018.0,3.0,0.643877,0.000000,0.000000,0.000000
126411,5218,zzxSjzuQ7B44-cL2EPhyMg,-1.268607,36.845904,2021.0,9.0,0.745615,0.000000,0.636643,0.000000
126412,37994,zzz5Wt_DGV8LAzRSfKZWiQ,-1.287985,37.044124,2021.0,10.0,0.000000,0.000000,0.000000,0.000000
126413,100451,zzzaSItdTD9Tirtzu6aDnA,-1.274018,37.035957,2021.0,10.0,0.000000,0.000000,0.000000,0.000000

In [6]:
df_sorted = pd.read_csv('/Users/wenlanzhang/PycharmProjects/SVI_Waste/Data/img_path.csv')
# df.drop(columns=['_0', '_90', '_180', '_270'], inplace=True)
# df_sorted = df.sort_values(by='panoid')
# df_sorted = df_sorted.reset_index()
df_sorted

,index,panoid,lat,lon,year,month,img_path,ang_0,ang_90,ang_180,ang_270
0,16186,---kW5kLNFT2eKu77K0BSg,-1.337135,36.735751,2021.0,7.0,-/-/,0.000000,0.000000,0.000000,0.000000
1,16185,---kW5kLNFT2eKu77K0BSg,-1.337135,36.735751,2021.0,7.0,-/-/,0.000000,0.000000,0.000000,0.000000
2,28639,--3w2NTa6dWsDSlB7lQqiA,-1.304348,36.742095,2018.0,1.0,-/-/,0.000000,0.000000,0.000000,0.000000
3,28541,--5kqrbr7DiSKTlMm6mmZw,-1.279489,36.716701,2018.0,2.0,-/-/,0.000000,0.657491,0.000000,0.000000
4,93757,--6rir7WBjJoKcL5UgHzFw,-1.284360,36.972830,2018.0,2.0,-/-/,0.000000,0.000000,0.000000,0.683942
...,...,...,...,...,...,...,...,...,...,...,...
126409,107337,zzvWdmTO_4oxT63l1GeS7w,-1.300941,36.811408,2018.0,3.0,Z/Z/,0.643877,0.000000,0.000000,0.000000
126410,98735,zzvWdmTO_4oxT63l1GeS7w,-1.300941,36.811408,2018.0,3.0,Z/Z/,0.643877,0.000000,0.000000,0.000000
126411,5218,zzxSjzuQ7B44-cL2EPhyMg,-1.268607,36.845904,2021.0,9.0,Z/Z/,0.745615,0.000000,0.636643,0.000000
126412,37994,zzz5Wt_DGV8LAzRSfKZWiQ,-1.287985,37.044124,2021.0,10.0,Z/Z/,0.000000,0.000000,0.000000,0.000000
126413,100451,zzzaSItdTD9Tirtzu6aDnA,-1.274018,37.035957,2021.0,10.0,Z/Z/,0.000000,0.000000,0.000000,0.000000

In [39]:
df_sorted['ang_0'] = df_20240113_sorted['ang_0']
df_sorted['ang_90'] = df_20240113_sorted['ang_90']
df_sorted['ang_180'] = df_20240113_sorted['ang_180']
df_sorted['ang_270'] = df_20240113_sorted['ang_270']
df_sorted

,index,panoid,lat,lon,year,month,img_path,ang_0,ang_90,ang_180,ang_270
0,16186,---kW5kLNFT2eKu77K0BSg,-1.337135,36.735751,2021.0,7.0,-/-/,0.000000,0.000000,0.000000,0.000000
1,16185,---kW5kLNFT2eKu77K0BSg,-1.337135,36.735751,2021.0,7.0,-/-/,0.000000,0.000000,0.000000,0.000000
2,28639,--3w2NTa6dWsDSlB7lQqiA,-1.304348,36.742095,2018.0,1.0,-/-/,0.000000,0.000000,0.000000,0.000000
3,28541,--5kqrbr7DiSKTlMm6mmZw,-1.279489,36.716701,2018.0,2.0,-/-/,0.000000,0.657491,0.000000,0.000000
4,93757,--6rir7WBjJoKcL5UgHzFw,-1.284360,36.972830,2018.0,2.0,-/-/,0.000000,0.000000,0.000000,0.683942
...,...,...,...,...,...,...,...,...,...,...,...
126409,107337,zzvWdmTO_4oxT63l1GeS7w,-1.300941,36.811408,2018.0,3.0,Z/Z/,0.643877,0.000000,0.000000,0.000000
126410,98735,zzvWdmTO_4oxT63l1GeS7w,-1.300941,36.811408,2018.0,3.0,Z/Z/,0.643877,0.000000,0.000000,0.000000
126411,5218,zzxSjzuQ7B44-cL2EPhyMg,-1.268607,36.845904,2021.0,9.0,Z/Z/,0.745615,0.000000,0.636643,0.000000
126412,37994,zzz5Wt_DGV8LAzRSfKZWiQ,-1.287985,37.044124,2021.0,10.0,Z/Z/,0.000000,0.000000,0.000000,0.000000
126413,100451,zzzaSItdTD9Tirtzu6aDnA,-1.274018,37.035957,2021.0,10.0,Z/Z/,0.000000,0.000000,0.000000,0.000000

In [24]:
df_sorted.to_csv('/Users/wenlanzhang/PycharmProjects/SVI_Waste/Data/img_path_20240113.csv', index=False)

# convert to long

In [44]:
# Reshape the DataFrame from wide to long format
df_long = pd.melt(df_sorted, id_vars=['index', 'panoid', 'lat', 'lon', 'year', 'month', 'img_path'],
                   var_name='angle', value_name='value')

# Extract the angle values from the column names
df_long['angle'] = df_long['angle'].str.replace('ang_', '').astype(int)

# Print the resulting long-format DataFrame
df_long

,index,panoid,lat,lon,year,month,img_path,angle,value
0,16186,---kW5kLNFT2eKu77K0BSg,-1.337135,36.735751,2021.0,7.0,-/-/,0,0.0
1,16185,---kW5kLNFT2eKu77K0BSg,-1.337135,36.735751,2021.0,7.0,-/-/,0,0.0
2,28639,--3w2NTa6dWsDSlB7lQqiA,-1.304348,36.742095,2018.0,1.0,-/-/,0,0.0
3,28541,--5kqrbr7DiSKTlMm6mmZw,-1.279489,36.716701,2018.0,2.0,-/-/,0,0.0
4,93757,--6rir7WBjJoKcL5UgHzFw,-1.284360,36.972830,2018.0,2.0,-/-/,0,0.0
...,...,...,...,...,...,...,...,...,...
505651,107337,zzvWdmTO_4oxT63l1GeS7w,-1.300941,36.811408,2018.0,3.0,Z/Z/,270,0.0
505652,98735,zzvWdmTO_4oxT63l1GeS7w,-1.300941,36.811408,2018.0,3.0,Z/Z/,270,0.0
505653,5218,zzxSjzuQ7B44-cL2EPhyMg,-1.268607,36.845904,2021.0,9.0,Z/Z/,270,0.0
505654,37994,zzz5Wt_DGV8LAzRSfKZWiQ,-1.287985,37.044124,2021.0,10.0,Z/Z/,270,0.0
505655,100451,zzzaSItdTD9Tirtzu6aDnA,-1.274018,37.035957,2021.0,10.0,Z/Z/,270,0.0

In [45]:
df_long['img_name'] = df_long['panoid'] + '_' + df_long['angle'].astype(str)
df_long

,index,panoid,lat,lon,year,month,img_path,angle,value,img_name
0,16186,---kW5kLNFT2eKu77K0BSg,-1.337135,36.735751,2021.0,7.0,-/-/,0,0.0,---kW5kLNFT2eKu77K0BSg_0
1,16185,---kW5kLNFT2eKu77K0BSg,-1.337135,36.735751,2021.0,7.0,-/-/,0,0.0,---kW5kLNFT2eKu77K0BSg_0
2,28639,--3w2NTa6dWsDSlB7lQqiA,-1.304348,36.742095,2018.0,1.0,-/-/,0,0.0,--3w2NTa6dWsDSlB7lQqiA_0
3,28541,--5kqrbr7DiSKTlMm6mmZw,-1.279489,36.716701,2018.0,2.0,-/-/,0,0.0,--5kqrbr7DiSKTlMm6mmZw_0
4,93757,--6rir7WBjJoKcL5UgHzFw,-1.284360,36.972830,2018.0,2.0,-/-/,0,0.0,--6rir7WBjJoKcL5UgHzFw_0
...,...,...,...,...,...,...,...,...,...,...
505651,107337,zzvWdmTO_4oxT63l1GeS7w,-1.300941,36.811408,2018.0,3.0,Z/Z/,270,0.0,zzvWdmTO_4oxT63l1GeS7w_270
505652,98735,zzvWdmTO_4oxT63l1GeS7w,-1.300941,36.811408,2018.0,3.0,Z/Z/,270,0.0,zzvWdmTO_4oxT63l1GeS7w_270
505653,5218,zzxSjzuQ7B44-cL2EPhyMg,-1.268607,36.845904,2021.0,9.0,Z/Z/,270,0.0,zzxSjzuQ7B44-cL2EPhyMg_270
505654,37994,zzz5Wt_DGV8LAzRSfKZWiQ,-1.287985,37.044124,2021.0,10.0,Z/Z/,270,0.0,zzz5Wt_DGV8LAzRSfKZWiQ_270
505655,100451,zzzaSItdTD9Tirtzu6aDnA,-1.274018,37.035957,2021.0,10.0,Z/Z/,270,0.0,zzzaSItdTD9Tirtzu6aDnA_270

In [46]:
df_long.to_csv('/Users/wenlanzhang/PycharmProjects/SVI_Waste/Data/data_long.csv', index=False)

# Select non 0 cells

In [47]:
df_long_n0 = df_long[df_long['value'] !=0]
df_long_n0

,index,panoid,lat,lon,year,month,img_path,angle,value,img_name
14,62980,--RL-phHNlZlg9bGS-7UKQ,-1.276972,36.963164,2018.0,2.0,-/-/,0,0.669043,--RL-phHNlZlg9bGS-7UKQ_0
22,60444,--agTAuB3_qSd3Ml61UQBA,-1.269893,36.920001,2018.0,1.0,-/-/,0,0.626960,--agTAuB3_qSd3Ml61UQBA_0
23,36245,--bF52zepYkkmotd5TYhDw,-1.251215,37.023054,2018.0,2.0,-/-/,0,0.677081,--bF52zepYkkmotd5TYhDw_0
24,76138,--e5EXQUQ4DpdjyZSmZ0PQ,-1.362253,36.924072,2018.0,4.0,-/-/,0,0.785355,--e5EXQUQ4DpdjyZSmZ0PQ_0
26,40846,--gztpPxVlgQtgUzGsxh7w,-1.219777,36.899377,2018.0,2.0,-/-/,0,0.665088,--gztpPxVlgQtgUzGsxh7w_0
...,...,...,...,...,...,...,...,...,...,...
505587,37150,zy8XtU1DFxV14coaA6DiEg,-1.255197,36.671482,2017.0,12.0,Z/y/,270,0.777539,zy8XtU1DFxV14coaA6DiEg_270
505593,98399,zyUIqb_jEfrEnNRj88UntA,-1.255349,36.919906,2018.0,2.0,Z/y/,270,0.895170,zyUIqb_jEfrEnNRj88UntA_270
505594,103153,zyVMtKy1vJiVJVKsY4tMuQ,-1.208400,36.949851,2021.0,9.0,Z/y/,270,0.746431,zyVMtKy1vJiVJVKsY4tMuQ_270
505595,17491,zyVojU5zQ1SGbAYCaUTHmQ,-1.154208,36.952961,2021.0,12.0,Z/y/,270,0.699477,zyVojU5zQ1SGbAYCaUTHmQ_270
505611,71561,zyuKiiuV5EBlAEXxhmS0BQ,-1.283829,37.052720,2018.0,2.0,Z/y/,270,0.821616,zyuKiiuV5EBlAEXxhmS0BQ_270

In [48]:
df_long_n0.to_csv('/Users/wenlanzhang/PycharmProjects/SVI_Waste/Data/df_long_n0.csv', index=False)

# Move file for manuel check and label

In [7]:
import os
import shutil
import pandas as pd

In [8]:
# Reading the CSV file
df_filtered = pd.read_csv('/Users/wenlanzhang/PycharmProjects/SVI_Waste/Data/df_long_n0.csv')
df_filtered

,index,panoid,lat,lon,year,month,img_path,angle,value,img_name
0,62980,--RL-phHNlZlg9bGS-7UKQ,-1.276972,36.963164,2018.0,2.0,-/-/,0,0.669043,--RL-phHNlZlg9bGS-7UKQ_0
1,60444,--agTAuB3_qSd3Ml61UQBA,-1.269893,36.920001,2018.0,1.0,-/-/,0,0.626960,--agTAuB3_qSd3Ml61UQBA_0
2,36245,--bF52zepYkkmotd5TYhDw,-1.251215,37.023054,2018.0,2.0,-/-/,0,0.677081,--bF52zepYkkmotd5TYhDw_0
3,76138,--e5EXQUQ4DpdjyZSmZ0PQ,-1.362253,36.924072,2018.0,4.0,-/-/,0,0.785355,--e5EXQUQ4DpdjyZSmZ0PQ_0
4,40846,--gztpPxVlgQtgUzGsxh7w,-1.219777,36.899377,2018.0,2.0,-/-/,0,0.665088,--gztpPxVlgQtgUzGsxh7w_0
...,...,...,...,...,...,...,...,...,...,...
68330,37150,zy8XtU1DFxV14coaA6DiEg,-1.255197,36.671482,2017.0,12.0,Z/y/,270,0.777539,zy8XtU1DFxV14coaA6DiEg_270
68331,98399,zyUIqb_jEfrEnNRj88UntA,-1.255349,36.919906,2018.0,2.0,Z/y/,270,0.895170,zyUIqb_jEfrEnNRj88UntA_270
68332,103153,zyVMtKy1vJiVJVKsY4tMuQ,-1.208400,36.949851,2021.0,9.0,Z/y/,270,0.746431,zyVMtKy1vJiVJVKsY4tMuQ_270
68333,17491,zyVojU5zQ1SGbAYCaUTHmQ,-1.154208,36.952961,2021.0,12.0,Z/y/,270,0.699477,zyVojU5zQ1SGbAYCaUTHmQ_270
68334,71561,zyuKiiuV5EBlAEXxhmS0BQ,-1.283829,37.052720,2018.0,2.0,Z/y/,270,0.821616,zyuKiiuV5EBlAEXxhmS0BQ_270

In [9]:
# Set your base path for the source images
basepath = '/Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/'  # Replace with your base path

# Set your destination path
destination_path = '/Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/PreScreen/'  # Replace with your destination path

# Set to keep track of copied images
copied_images = set()

In [18]:
df_subset = df_filtered.iloc[10000:13000]

# df_subset = df_filtered.iloc[500:1000]
# df_subset = df_filtered.iloc[1500:4000]

In [19]:
# Iterate over the DataFrame rows
for index, row in df_subset.iterrows():
    # Construct the source file path
    img_folder = row['img_path']  # This should be something like 'Q/g/'
    modified_img_name = row['img_name'] + '.jpg'  # Assuming the file extension is .jpg
    source_path = os.path.join(basepath, img_folder, modified_img_name)

    # Construct the destination file path
    dest_file_path = os.path.join(destination_path, modified_img_name)

    # Check if the image has already been copied
    if modified_img_name not in copied_images:
        # Copy the file
        if os.path.exists(source_path):
            shutil.copy2(source_path, dest_file_path)
            copied_images.add(modified_img_name)
        else:
            print(f"File not found: {source_path}")
    else:
        print(f"Already copied: {modified_img_name}")

Already copied: _5JELZgn2AQpxfodyTyU8g_0.jpg
Already copied: _5JELZgn2AQpxfodyTyU8g_0.jpg
Already copied: _5pRURqf7khEekjuIx8QhA_0.jpg
Already copied: _AwKIvRA8Ghz9evHaMig9w_0.jpg
Already copied: _CEnpJWKsm2CzT3jsI8-4w_0.jpg
Already copied: _Chu3PFa2ZO1O4PunMoljA_0.jpg
Already copied: _Dhts17qXKxOSGJ9qU6LSQ_0.jpg
Already copied: _GQx79FnfmeGp3h_HMZsQw_0.jpg
Already copied: _Hv8fFOPAPEHA6aOi9tnhw_0.jpg
Already copied: _LUMQA-PteAe-jam-ilSBQ_0.jpg
Already copied: _LjUFYYzEANGW8Vfk8MeDA_0.jpg
Already copied: _TJ8D2XXn1fxBagzl07GBw_0.jpg
Already copied: _UsKSQWkLkWqMkca-X5ZVA_0.jpg
Already copied: _hrggPM3VxXqb3V8MLx2oQ_0.jpg
Already copied: _jng0-3pcSWbp8BumH250g_0.jpg
Already copied: _jng0-3pcSWbp8BumH250g_0.jpg
Already copied: _lTHxPTb9DLPjF70scrxzw_0.jpg
Already copied: _my_BVW_WxNyQmJ7PCvafw_0.jpg
Already copied: _oQl1EGSpTWXWNUsixcSng_0.jpg
Already copied: _uzXNS9G4Sq8NsHbX3hvsg_0.jpg
Already copied: a4-VV-3Hbhr8OmRB5m0RfA_0.jpg
Already copied: a44mzT9gtS6TltdOVy9pdw_0.jpg
Already copied: a56JU8oTFppFujqS8e2EAg_0.jpg
Already copied: a5glfGJ0Q2q2oP9CSbxcyQ_0.jpg
Already copied: a62jqycWEX5TJJWuAgSp0g_0.jpg
Already copied: a6kkpDyLHXbs5xLvjJo-Cg_0.jpg
Already copied: aCLPC6Z9hVvKXQ8hJs6r2g_0.jpg
Already copied: aDCIgMrjdLhGuf-vIGc43A_0.jpg
Already copied: aG9RtWuCksO08LETvBfXVw_0.jpg
Already copied: aJdAamANJcB6Q8cDUvKaxg_0.jpg
Already copied: aL-Q_f38M8Le_XRZUFQYmQ_0.jpg
Already copied: aN2xejJQ2SjXjXnqPartXw_0.jpg
Already copied: aOf_5q5Cv8eyiIEdW-qeeg_0.jpg
Already copied: aSNVj_Wsu2IUqWoO0Sgwqg_0.jpg
Already copied: aTl4Rb-Mp7SNn8mYaYQRPQ_0.jpg
Already copied: aTqKSnCQmjijVIh2pXOn-g_0.jpg
Already copied: aUEFGcpg3-PiO_M0rmNh8A_0.jpg
Already copied: aWvQnOeL8i08RCi6xmor2w_0.jpg
Already copied: aWvQnOeL8i08RCi6xmor2w_0.jpg
Already copied: aWvQnOeL8i08RCi6xmor2w_0.jpg
Already copied: aWvQnOeL8i08RCi6xmor2w_0.jpg
Already copied: aWvQnOeL8i08RCi6xmor2w_0.jpg
Already copied: aWvQnOeL8i08RCi6xmor2w_0.jpg
Already copied: aXg8QlzDbLoCB5-cuGViow_0.jpg
Already copied: aXi3am6s4PJZMITMltDrYQ_0.jpg
Already copied: aY9MmR0ebUZZrCJqICz7Dw_0.jpg
Already copied: a_-nJPPzwqSD_2qQmqnbuQ_0.jpg
Already copied: a_-nJPPzwqSD_2qQmqnbuQ_0.jpg
Already copied: abQlFqVMekccCJUKv0qc3w_0.jpg
Already copied: abQlFqVMekccCJUKv0qc3w_0.jpg
Already copied: acU6nJeBoeWZZxQexFwoPw_0.jpg
Already copied: ajHfaynB4RB_bWdXFo504Q_0.jpg
Already copied: ajHfaynB4RB_bWdXFo504Q_0.jpg
Already copied: alLlI6nOmjl9oDQ2JbTTKQ_0.jpg
Already copied: alWDWr8YYixBQI1GdrFbpA_0.jpg
Already copied: alWDWr8YYixBQI1GdrFbpA_0.jpg
Already copied: alWDWr8YYixBQI1GdrFbpA_0.jpg
Already copied: am0K8xK-WSXnFDvytIAdoA_0.jpg
Already copied: aowXJuJ4_TdV2Q3SRggquQ_0.jpg
Already copied: apiABU6gkjEqCM77e0zr8Q_0.jpg
Already copied: arhmQE1snUx4FZD_gY5bRw_0.jpg
Already copied: as0C4Mz32hg7S9e8hMuaUQ_0.jpg
Already copied: asSA31xzAhT5XdYx8xtisg_0.jpg
Already copied: atry33HW4SSvLnP5VTPUag_0.jpg
Already copied: awWls0E1GFcKBvqqxMbuTg_0.jpg
Already copied: ayylWFusIY38KzYueQktwQ_0.jpg
Already copied: b-Mgi0DkOOd4gfjihb_QSA_0.jpg
Already copied: b0ew1lMtBAc5skIxidnIag_0.jpg
Already copied: b4zPbT4zBy99ryHX9mgScQ_0.jpg
Already copied: b8EImuKX7JyB3axVqSy0Fw_0.jpg
Already copied: bAvyTwamVf89mjikgYbzSQ_0.jpg
Already copied: bCeiO0wlwN4WeBgF2gVTdQ_0.jpg
Already copied: bCsLzw6uPD_Qf92m7OFsBQ_0.jpg
Already copied: bCsLzw6uPD_Qf92m7OFsBQ_0.jpg
Already copied: bEpOFZqI94RgnUJiBdjy9Q_0.jpg
Already copied: bEpOFZqI94RgnUJiBdjy9Q_0.jpg
Already copied: bFdnHPPyOkzgeP4hs9wn8g_0.jpg
Already copied: bHHA4wA4Zkf4qVGxguTouw_0.jpg
Already copied: bMz8FGNaWoDO56o0Pcdx3g_0.jpg
Already copied: bR2pD_OaqGmVL193n0692A_0.jpg
Already copied: bR49sedd7exjbnGbD1ftBg_0.jpg
Already copied: bSYO9fmSW4UW0wJ-tcgFcA_0.jpg
Already copied: bScRLF8EB0yMiyV1XXCF-g_0.jpg
Already copied: bSqeY9qDq5iPwQa9ac1Fhg_0.jpg
Already copied: bTTYRGt9HpGDq1JYdt_yXg_0.jpg
Already copied: bUnfu7n1SV0XRuKNOGwjOA_0.jpg
Already copied: bUnfu7n1SV0XRuKNOGwjOA_0.jpg
Already copied: bVxycOhESMPhCXsgwLVY-w_0.jpg
Already copied: bWgL83pziTaDuQuyy-PwUg_0.jpg
Already copied: bXrvCC6FkpgAhrrvHuEc1A_0.jpg
Already copied: bdmUcxTjcC5Df0paVBOdpQ_0.jpg
Already copied: bmohKXaW7xE1bLrrCc7RVw_0.jpg
Already copied: boRP2fYo7wLJ7_1kpxbiqQ_0.jpg
Already copied: brBq-nMVRkcLewjYAtaaEQ_0.jpg
Already copied: bwKmaNrKKvGmggzs6qlNOg_0.jpg
Already copied: byY94DRYj_fdvE_oHoDhrg_0.jpg
Already copied: bzT_5_G2bGHYf35s89SjlQ_0.jpg
Already copied: bzT_5_G2bGHYf35s89SjlQ_0.jpg
Already copied: c1duC9JUBBbF3QmoR0bIvQ_0.jpg
Already copied: c6MNUF6MVvSHP-uQKkN2_w_0.jpg
Already copied: c6PcUeVfwYkzJ8BsADl2TA_0.jpg
Already copied: c6PcUeVfwYkzJ8BsADl2TA_0.jpg
Already copied: c8DDIRxjqWfNozW7IamqgA_0.jpg
Already copied: c8FvRE5GN-jDCKptYYgNMg_0.jpg
Already copied: c8XmC4edXedjY-KNWHXv0w_0.jpg
Already copied: cBwdQKgsxglH0V4NM6eAjg_0.jpg
Already copied: cC9sSULBmD9Hxp-YpdA9cg_0.jpg
Already copied: cDVBLPz7Sb4K0h06Czwm1g_0.jpg
Already copied: cGoFgaSbbCX0lYIOtYdeVA_0.jpg
Already copied: cH-_5oihphMIfKBJ-H9fAQ_0.jpg
Already copied: cH7vLTJP1j6pRq0JJ_aX9w_0.jpg
Already copied: cIx6CZMty77Ps74W7SxQ-w_0.jpg
Already copied: cJZEPkz4W2naDw2GLxyhfw_0.jpg
Already copied: cL8b7cTLjntBG_BFQDWJog_0.jpg
Already copied: cTiG76Q4EoeHUSgsLqvQoA_0.jpg
Already copied: cWgOCRqL0s3Otg8AjWPBMA_0.jpg
Already copied: cYZ2mUiMKAhkSb6p_XKpsg_0.jpg
Already copied: caapZoI-YeoeMzZH861zQA_0.jpg
Already copied: ccVy8TctqSUHPAKJh4WM_Q_0.jpg
Already copied: chkpuc84MMVdwuhGHe6rUQ_0.jpg
Already copied: cjNFFFTMDE_SkWGxgy4zDg_0.jpg
Already copied: cjmKbEoEYEzKrghRxHcJfw_0.jpg
Already copied: cl30hEjCI0ob4ABlqYOdgQ_0.jpg
Already copied: claoM6FrGbGL9gzqAxBuSA_0.jpg
Already copied: conR0SZ7ELy16ZrFpS4EsQ_0.jpg
Already copied: cppbBDHja6S7Gkl3jMX_QA_0.jpg
Already copied: cq0bIaubwiggWx-4DHFy5A_0.jpg
Already copied: cr0wlAPbvwIuvVw6Rvg6xQ_0.jpg
Already copied: cr0wlAPbvwIuvVw6Rvg6xQ_0.jpg
Already copied: ct-4r6Uc59jNKMMHpvlqzg_0.jpg
Already copied: d2LE6dupqMipFcSggzw62Q_0.jpg
Already copied: d2LE6dupqMipFcSggzw62Q_0.jpg
Already copied: d2LE6dupqMipFcSggzw62Q_0.jpg
Already copied: d2w5udBkvxTVjEcM0CiIbQ_0.jpg
Already copied: d3PZtqUP_kPp-XQ6TVe5JQ_0.jpg
Already copied: d3PZtqUP_kPp-XQ6TVe5JQ_0.jpg
Already copied: d6_v9SpxSBGhq-WO_EUHHA_0.jpg
Already copied: d7bA1tP3MRHz-OmByxpEGQ_0.jpg
Already copied: d9W9WG8iwOeaExWFGrs24g_0.jpg
Already copied: d9o74qYyn-G43GPG6rk9_A_0.jpg
Already copied: dCNPjyStClds-rB_m5dVzw_0.jpg
Already copied: dHXpFtR-OrHDuurlcP5Zpw_0.jpg
Already copied: dIUGhmbQj0XtNWPeTESC7g_0.jpg
Already copied: dJxF0qhVRruR157iS-qf3Q_0.jpg
Already copied: dKqWZzCRCSSlx0ifOj7vKA_0.jpg
Already copied: dLF2s1kFYlTh3JOXUOOI5Q_0.jpg
Already copied: dUQkMMjUwT8iY1JOiy1e7Q_0.jpg
Already copied: dWST4rKXCdk1oQdOtqmV3Q_0.jpg
Already copied: d_1Tqr0A9Gx21WZ9TG3a-w_0.jpg
Already copied: dbYKfVhxpQ9LvAkq6NwJDQ_0.jpg
Already copied: djY5GWQgv7iJosjivmmn7Q_0.jpg
Already copied: djfcXrG4_r0kjtYkCUSrhg_0.jpg
Already copied: dldAvauhJ3CR-hLMfnco2Q_0.jpg
Already copied: dldAvauhJ3CR-hLMfnco2Q_0.jpg
Already copied: dsUBF4kujXsKka19Bkja6g_0.jpg
Already copied: dse4SaHCYW9R3dGsKdBbVw_0.jpg
Already copied: dtreJNCdNthZGOfTslI0EQ_0.jpg
Already copied: dtreJNCdNthZGOfTslI0EQ_0.jpg
Already copied: duCHcdaeekj3jVYK0WUV_g_0.jpg
Already copied: duCHcdaeekj3jVYK0WUV_g_0.jpg
Already copied: duCHcdaeekj3jVYK0WUV_g_0.jpg
Already copied: dxUCkektF8V2f97gQ9aIcA_0.jpg
Already copied: dxUCkektF8V2f97gQ9aIcA_0.jpg
Already copied: dyJwSBsW8Gk34zXXxAgQTw_0.jpg
Already copied: dyTi2lNmjPtAcGDtKgLkjg_0.jpg
Already copied: e10EL27Cnc1rzd1ijg5Y6w_0.jpg
Already copied: e12VXVTeWsHjex5L1ekZFw_0.jpg
Already copied: e38C0CiOc_fOQGIO-DkTXA_0.jpg
Already copied: e38C0CiOc_fOQGIO-DkTXA_0.jpg
Already copied: e38C0CiOc_fOQGIO-DkTXA_0.jpg
Already copied: e4zpDdexhcUZLDHA2DOpcg_0.jpg
Already copied: e79Xajy_UQWfLZKBfPu-1A_0.jpg
Already copied: e79Xajy_UQWfLZKBfPu-1A_0.jpg
Already copied: eDxjF-iD6J_qJkx0xuEZKQ_0.jpg
Already copied: eH0utySOSUEPn6qqeCEIAA_0.jpg
Already copied: eHF48TSH4uoimwf_mRIXBg_0.jpg
Already copied: eHYMLJ4nHeBJLL7TnH_RZA_0.jpg
Already copied: eHYMLJ4nHeBJLL7TnH_RZA_0.jpg
Already copied: eJm7EyTttUCKw0F-6Gtllw_0.jpg
Already copied: eMmSuQwwc1N2ZIBnBnPGJA_0.jpg
Already copied: eMmSuQwwc1N2ZIBnBnPGJA_0.jpg
Already copied: ePd0KlKyCJKBtfeN6ISwoA_0.jpg
Already copied: eRqezQwmqxUZWdqXpnCCnA_0.jpg
Already copied: eUuHUOBHbJ3y5SstHHbzmQ_0.jpg
Already copied: eUuHUOBHbJ3y5SstHHbzmQ_0.jpg
Already copied: eUuHUOBHbJ3y5SstHHbzmQ_0.jpg
Already copied: eWRfOgVvhRQ_gU3kFb2HWw_0.jpg
Already copied: eZndzxPw04NwkyJtxoqU5g_0.jpg
Already copied: e_z8QcW8fjE02JzPKRTWBw_0.jpg
Already copied: ea9O8bXDXLkkpOuE6KHkDA_0.jpg
Already copied: eaq98QRMcEVssUwBMwrycg_0.jpg
Already copied: edgRutQu1yE3t3DLlP92iA_0.jpg
Already copied: edvJkwJ3xTW7O6bUmrtv7Q_0.jpg
Already copied: ehsEumbbAsi0v7nvYPhGVw_0.jpg
Already copied: eriIO2w2Mxc2tfSzXN1dnQ_0.jpg
Already copied: etqMsDxlzirSswCmWnWo9g_0.jpg
Already copied: ev3eilp7dfT_bXq9fyxP1w_0.jpg
Already copied: evveojxyPWxTh86VbKQSYw_0.jpg
Already copied: ewYdy1bLwCBIvm9m6n4PQQ_0.jpg
Already copied: ezBZYEM8Qy7ahKma5HzU9w_0.jpg
Already copied: ezBZYEM8Qy7ahKma5HzU9w_0.jpg
Already copied: ezBZYEM8Qy7ahKma5HzU9w_0.jpg
Already copied: ezBZYEM8Qy7ahKma5HzU9w_0.jpg
Already copied: ezBZYEM8Qy7ahKma5HzU9w_0.jpg

Already copied: f5Fyrbm0ok3stYsLhsFMdA_0.jpg
Already copied: f5Fyrbm0ok3stYsLhsFMdA_0.jpg
Already copied: f5Fyrbm0ok3stYsLhsFMdA_0.jpg
Already copied: f7-C9CHRY2r3DL5a4_QN6A_0.jpg
Already copied: f95Vd_KW2EXWMi4R0aczJA_0.jpg
Already copied: f95Vd_KW2EXWMi4R0aczJA_0.jpg
Already copied: f9gxAQmHTnP8_4IacmXZAg_0.jpg
Already copied: fAprm-PPosWuj2Yp43SEVw_0.jpg
Already copied: fAprm-PPosWuj2Yp43SEVw_0.jpg
Already copied: fClyP6r7t_l0oMqAl6kkoQ_0.jpg
Already copied: fJKyqEne5H06J4PIautpbw_0.jpg
Already copied: fJKyqEne5H06J4PIautpbw_0.jpg
Already copied: fJlbmDT0QUjZRz8FjAXxgw_0.jpg
Already copied: fKHsEOebJbcP_IxPKzSwvQ_0.jpg
Already copied: fN6NBXsWd9_6SHAlQEjqUA_0.jpg
Already copied: fQRtjwFXT88v993TvhME_g_0.jpg
Already copied: fQVDPJXDvAIFUyoIldJDTg_0.jpg
Already copied: fT55yQOIaZB_oQX8kzKDnw_0.jpg
Already copied: fUGbTr8zeRCHGzMPrDdsEQ_0.jpg
Already copied: fVbrA6f1WJF6dpBcJ9qLgQ_0.jpg
Already copied: fZRmPvtBJFpOI2EyVrFdxQ_0.jpg
Already copied: faFWDc70y2LpGU8cy1gpWw_0.jpg
Already copied: fd_x7r1MBp20cYpcIIJ5_g_0.jpg
Already copied: fg2HPiIHxC30YIKZpx83Iw_0.jpg
Already copied: fhy48aZtJJTMKHb_EP1P-A_0.jpg
Already copied: fmCUnxJY_zwarcw0JGl6IQ_0.jpg
Already copied: fpBa2G8PP-SJZE5LLyJX6Q_0.jpg
Already copied: ftMKiv72jWaOtlLwSabbmg_0.jpg
Already copied: fuXKPrnObQsbHf02gkI8Zw_0.jpg
Already copied: g-b8ppxHGpyXGJNawtoMUw_0.jpg
Already copied: g0QLsQPyYFmO3i2VCprHng_0.jpg
Already copied: g2hyY_W7PHxMw4smiw9tIg_0.jpg
Already copied: g7bCbMhu0d0g7UI8_fTGow_0.jpg
Already copied: gCgOQBYtqt0HaqEo6KDfTA_0.jpg
Already copied: gD_AnTKLpPVTwl2y_7EfBg_0.jpg
Already copied: gFlRN5D_LmNHjm8NDCyQ8A_0.jpg
Already copied: gG7fYpaIw6WPP5RqYsOBGg_0.jpg
Already copied: gGaB-eVLey8_oznnqd2FRw_0.jpg
Already copied: gGjZByxE9JOrH9Q3SeGM4g_0.jpg
Already copied: gM7XfGZy6gvi30kkVOA0mA_0.jpg
Already copied: gQL-qBUO7acPdT-US31JGQ_0.jpg
Already copied: gSLd4M9mT4_7S0exG6r5MQ_0.jpg
Already copied: gSzZKNU5RNx1BSRtcnxSBA_0.jpg
Already copied: gW1bw7bpGC_3kJAADaneKw_0.jpg
Already copied: gW3VDgJdbSYDe2opQ72W_w_0.jpg
Already copied: gWZ49ROJRNiU1Cd6s1uiQg_0.jpg
Already copied: gYowNwVRzGu6F01nVShiag_0.jpg
Already copied: g_-0zPKjKI1hM_B7ldzCpg_0.jpg
Already copied: g_VMzWZQJdNwI-RKpls4TA_0.jpg
Already copied: gijiIe9so7UI8ucWPJA2dQ_0.jpg
Already copied: griiNLvWEIE69c-3IBB0yg_0.jpg
Already copied: gsncVQYWPb71NGoSiWwTEw_0.jpg
Already copied: gt5hUAV_UwjB6Xh_c55W-g_0.jpg
Already copied: gtL-M_ypXfM7FicaZ08qNw_0.jpg
Already copied: gvseHFfr-zX6Ay8SBKeiwQ_0.jpg
Already copied: gxTppjWLN3GpIokLtGlxtw_0.jpg
Already copied: gydaJGcp3-LwugX9T4WdCg_0.jpg
Already copied: h2yQAF7RAsp01I9wlhIm0Q_0.jpg
Already copied: h4krPLpcrFmIdufwo3C2Wg_0.jpg
Already copied: h5QYKIF8tKFd8PZpQVfw4w_0.jpg
Already copied: h9bsfoLjiS_tt22-kFT_eA_0.jpg
Already copied: h9yIJOuhMpIwRvkD7ainPA_0.jpg
Already copied: h9yIJOuhMpIwRvkD7ainPA_0.jpg
Already copied: hA-cGFWmcwV8N7u59KRNUw_0.jpg
Already copied: hAbB0K7zmW8dMYEpsCKSyA_0.jpg
Already copied: hAbB0K7zmW8dMYEpsCKSyA_0.jpg
Already copied: hDFQw2i1BV_qTzcQeD59CA_0.jpg
Already copied: hDFQw2i1BV_qTzcQeD59CA_0.jpg
Already copied: hDJf8PhTklczxdTFjX5_kA_0.jpg
Already copied: hEiNdiWdRmfUWWz3zD358g_0.jpg
Already copied: hFjlPR5kdXVXmDHF0Pfv5w_0.jpg
Already copied: hGkCBtlU4xHmGydIVB47pg_0.jpg
Already copied: hGw6iX8ogGBoXSDQYA1I2Q_0.jpg
Already copied: hGw6iX8ogGBoXSDQYA1I2Q_0.jpg
Already copied: hJLB0gZpFldgiLJN8BsY7Q_0.jpg
Already copied: hJStE2T1ZGaXQ7uLL-JQ4w_0.jpg
Already copied: hMmdoBFtd4bFAzF6yqWABA_0.jpg
Already copied: hOcEaHVMLjiFLWydACAcfg_0.jpg
Already copied: hPltqHfZhEslZ1pfLKR9PA_0.jpg
Already copied: hQxGyzzCG0wXvi6kS6Ey-g_0.jpg
Already copied: hRV5KqIwthv9ikROUK7B8Q_0.jpg
Already copied: hRV5KqIwthv9ikROUK7B8Q_0.jpg
Already copied: hT4lZfWxu4uBmuzpvy8ThA_0.jpg
Already copied: hTcgbvQLWrhoMZqtQhIy7A_0.jpg
Already copied: hYMS9Jp_WETpJpe_KJoO2A_0.jpg
Already copied: hjKKn6PYZorcrua7YbYWJg_0.jpg
Already copied: hqO9K2lwWzBRrTfm5W5ppA_0.jpg
Already copied: hqkq8zA4K-hikr2ko7rgWQ_0.jpg
Already copied: huG1gH3c2M-R0dROvxSkxg_0.jpg
Already copied: hwrs_okCBl_r5j4VNeWIGQ_0.jpg
Already copied: i0yg_5FHGfBTnwQDv-CKzw_0.jpg
Already copied: i0yg_5FHGfBTnwQDv-CKzw_0.jpg
Already copied: i2QsQb-y3MUL-itZqz0mRA_0.jpg
Already copied: i2l1GyK_wKbdltfXi1hfkw_0.jpg
Already copied: i2l1GyK_wKbdltfXi1hfkw_0.jpg
Already copied: i3WHrt6icxOthJqCCsherw_0.jpg
Already copied: iAuj519IQ1ZuKRy0s8xQEg_0.jpg
Already copied: iEf_xjtNNO6mgRPaWXIahA_0.jpg
Already copied: iFALJURi2xJaTB03B4Bt8Q_0.jpg
Already copied: iFd8gtPwzdrGpRCI0v7wUg_0.jpg
Already copied: iNZjDQ7Sff1NXJy4SSZ6tw_0.jpg
Already copied: iNhZ8FgpfjrvRm-mHG-7KQ_0.jpg
Already copied: iPDFyyySJ7CCNWyBmi55fA_0.jpg
Already copied: iR0EOfPCFcf0cOuFbLRMtg_0.jpg
Already copied: iUAduHBxlnq3zcoJxY1Y9w_0.jpg
Already copied: iVL8NyXZ2AApg_MUSNgG2g_0.jpg
Already copied: ibOYRI6uU2L8DaCkiUq4dw_0.jpg
Already copied: ibOYRI6uU2L8DaCkiUq4dw_0.jpg
Already copied: ifnQJc0jUALYXBNJgxOKsg_0.jpg
Already copied: ifnQJc0jUALYXBNJgxOKsg_0.jpg
Already copied: ig7bkGUBPsP6n7s7hOwWzg_0.jpg
Already copied: ihMx1CZG7xDDlzZdvemyHw_0.jpg
Already copied: iir9C1lGXINcVHQtmN2Qjw_0.jpg
Already copied: iisl_43WjgmJtRjOmjARCA_0.jpg
Already copied: isHdJn0mf05RrCQw11OrJw_0.jpg
Already copied: isM7OLtPTVxVpU9dL11zeA_0.jpg
Already copied: ixaVKb09BVfiVU8-0TR09Q_0.jpg
Already copied: iyZHovYmC1XQRqdb49uAjQ_0.jpg
Already copied: iyZHovYmC1XQRqdb49uAjQ_0.jpg
Already copied: izvlZD4GVjuSV1kytz6Hig_0.jpg
Already copied: j1ZDdr-sAsgPqKCO-j89zQ_0.jpg
Already copied: j1rg0_IZ4eO-dbg-YvQ-rQ_0.jpg
Already copied: j3wnSy9rlTkcN7B637RcBg_0.jpg
Already copied: j6oO36tjja37NxcZueN1kA_0.jpg
Already copied: jANI8eEq9yRzR0qe1ZT3gQ_0.jpg
Already copied: jANI8eEq9yRzR0qe1ZT3gQ_0.jpg
Already copied: jCTaSCTl7AZQrXydBiEhYw_0.jpg
Already copied: jJcukiMzMAvxDpkTycUQfg_0.jpg
Already copied: jJcukiMzMAvxDpkTycUQfg_0.jpg
Already copied: jKnQG6h3V6rtik-4keX-fg_0.jpg
Already copied: jN5vw8LxxLyFZ5KFHGHj4g_0.jpg
Already copied: jND3eAwFDQSxp0Qq-bxv5w_0.jpg
Already copied: jNe7esRBGYMCCGQE0fsKLg_0.jpg
Already copied: jOXPeomaKk0mpPP18nvsYQ_0.jpg
Already copied: jOXPeomaKk0mpPP18nvsYQ_0.jpg
Already copied: jPLzch-FlPtmfCLc--3naw_0.jpg
Already copied: jUYBaOTJBL7KPnuOnKsKsw_0.jpg
Already copied: jWoQOqzMrzn9IUgmMRIoTg_0.jpg
Already copied: jWoQOqzMrzn9IUgmMRIoTg_0.jpg
Already copied: jWoQOqzMrzn9IUgmMRIoTg_0.jpg
Already copied: jWoQOqzMrzn9IUgmMRIoTg_0.jpg
Already copied: jWoQOqzMrzn9IUgmMRIoTg_0.jpg
Already copied: jX-68f8Ltx0IuPhYKKVCBA_0.jpg
Already copied: jYaKBtw1iOFGLo9bvPMuhw_0.jpg
Already copied: jYaKBtw1iOFGLo9bvPMuhw_0.jpg
Already copied: jaRe6eqHlEVzESSQQc0KNA_0.jpg
Already copied: jaRe6eqHlEVzESSQQc0KNA_0.jpg
Already copied: jdYZvfGnN-snKhNQiRTB2A_0.jpg
Already copied: je60UVgoVuVF2PiCriRr_A_0.jpg
Already copied: jeVQ6jGOIm5T3tcQbWftyg_0.jpg
Already copied: jfjoceeCUBJ1Ce8oI-bR2w_0.jpg
Already copied: jk7tNmQWP6fZ_xuq_ueV8Q_0.jpg
Already copied: jlKex8upoJlF6adhDM1yqw_0.jpg
Already copied: jm2_fADVjZqvrmXUbt8y3A_0.jpg
Already copied: jm2_fADVjZqvrmXUbt8y3A_0.jpg
Already copied: jsDoLpEsBdXqcNZ5y51ApQ_0.jpg
Already copied: jwqd8zr0gQ_MVU5U9atfmQ_0.jpg

In [15]:
# Reading the CSV file
df_mapi = pd.read_csv('/Users/wenlanzhang/Downloads/PhD_UCL/Data/Mapillary/combined_MS/All_Img.csv')
df_mapi

,Source,id,time,Map_compass_angle,Map_sequence_id,geometry
0,mapillary,555315025832458.jpg,2017-08-17 11:48:14.000,71.876938,H6fRjtsMmuHb3I06YYpgQQ,POINT (36.95400059223175 -1.258149947252519)
1,mapillary,315127656718481.jpg,2017-08-17 10:17:48.000,166.631247,70accd7gmkd8nrl6vj5tmy,POINT (36.951404213905334 -1.26739595788537)
2,mapillary,341403537326675.jpg,2017-08-17 09:53:47.000,159.407698,c4nvikpmgpskhdlgcotmr6,POINT (36.93908751010895 -1.270715718162919)
3,mapillary,732275437451275.jpg,2017-08-17 11:46:23.000,74.162760,H6fRjtsMmuHb3I06YYpgQQ,POINT (36.951640248298645 -1.257710170986513)
4,mapillary,3720780351381434.jpg,2017-08-17 10:05:04.000,356.175966,3mssf5lja164n60b5bt18i,POINT (36.93676471710205 -1.270919515908602)
...,...,...,...,...,...,...
89620,self,IMG_20230212_081016.jpg,2023-02-12 08:10:16,0.000000,0,POINT (36.73464965805556 -1.307546973055556)
89621,self,IMG_20230212_081003.jpg,2023-02-12 08:10:03,0.000000,0,POINT (36.73464965805556 -1.307618975555556)
89622,self,IMG_20230212_081017.jpg,2023-02-12 08:10:17,0.000000,0,POINT (36.73464965805556 -1.307546973055556)
89623,self,IMG_20230212_082052.jpg,2023-02-12 08:20:52,0.000000,0,POINT (36.66281890861111 -1.256016611944444)
89624,self,IMG_20230212_080902.jpg,2023-02-12 08:09:02,0.000000,0,POINT (36.74350357055555 -1.305370211388889)

In [14]:
df_mapi_w = df_mapi[df_mapi['waste']>0.7]
df_mapi_w

,Source,id,time,Map_compass_angle,Map_sequence_id,geometry,waste
111,mapillary,847210296148795.jpg,2017-12-12 08:25:19.493,113.970795,HhZ1DBhnKWjj_izvV56z9g,POINT (36.82235240936279 -1.250561114725187),0.752451
124,mapillary,129227925815156.jpg,2017-12-12 08:18:18.091,116.005249,CpkmlTFUESrNRrDPh_CYcg,POINT (36.80493414402008 -1.235431652516695),0.738521
173,mapillary,1015499855648110.jpg,2017-12-12 08:19:14.182,121.945618,CpkmlTFUESrNRrDPh_CYcg,POINT (36.81022882461548 -1.238150778834097),0.739024
209,mapillary,2927137017614149.jpg,2017-12-12 08:13:45.795,297.588959,CpkmlTFUESrNRrDPh_CYcg,POINT (36.80814743041992 -1.237104961349445),0.830736
227,mapillary,1390677638023694.jpg,2017-12-11 17:02:16.064,80.432098,uQxi0Q7l-_eszUqEkTC3xQ,POINT (36.86384618282318 -1.308589641333427),0.708321
...,...,...,...,...,...,...,...
89601,self,IMG_20230212_080910.jpg,2023-02-12 08:09:10,0.000000,0,POINT (36.73926162694445 -1.306132793333333),0.882440
89610,self,IMG_20230212_080652.jpg,2023-02-12 08:06:52,0.000000,0,POINT (36.76295471166667 -1.299250364166667),0.784192
89614,self,IMG_20230212_082119.jpg,2023-02-12 08:21:19,0.000000,0,POINT (36.66455841055556 -1.250457048333333),0.768776
89619,self,IMG_20230212_080650.jpg,2023-02-12 08:06:51,0.000000,0,POINT (36.76295471166667 -1.299250364166667),0.784707
89624,self,IMG_20230212_080902.jpg,2023-02-12 08:09:02,0.000000,0,POINT (36.74350357055555 -1.305370211388889),0.909098