This is to copy part images to a path for check / label

# Check location

In [29]:
df_20240113 = pd.read_csv('/Users/wenlanzhang/PycharmProjects/SVI_Waste/Data/output_20240113.csv')
df_20240113.drop(columns=['pk', 'id', 'marker'], inplace=True)
df_20240113_sorted = df_20240113.sort_values(by='panoid')
df_20240113_sorted = df_20240113_sorted.reset_index()
df_20240113_sorted

,index,panoid,lat,lon,year,month,ang_0,ang_90,ang_180,ang_270
0,16186,---kW5kLNFT2eKu77K0BSg,-1.337135,36.735751,2021.0,7.0,0.000000,0.000000,0.000000,0.000000
1,16185,---kW5kLNFT2eKu77K0BSg,-1.337135,36.735751,2021.0,7.0,0.000000,0.000000,0.000000,0.000000
2,28639,--3w2NTa6dWsDSlB7lQqiA,-1.304348,36.742095,2018.0,1.0,0.000000,0.000000,0.000000,0.000000
3,28541,--5kqrbr7DiSKTlMm6mmZw,-1.279489,36.716701,2018.0,2.0,0.000000,0.657491,0.000000,0.000000
4,93757,--6rir7WBjJoKcL5UgHzFw,-1.284360,36.972830,2018.0,2.0,0.000000,0.000000,0.000000,0.683942
...,...,...,...,...,...,...,...,...,...,...
126409,107337,zzvWdmTO_4oxT63l1GeS7w,-1.300941,36.811408,2018.0,3.0,0.643877,0.000000,0.000000,0.000000
126410,98735,zzvWdmTO_4oxT63l1GeS7w,-1.300941,36.811408,2018.0,3.0,0.643877,0.000000,0.000000,0.000000
126411,5218,zzxSjzuQ7B44-cL2EPhyMg,-1.268607,36.845904,2021.0,9.0,0.745615,0.000000,0.636643,0.000000
126412,37994,zzz5Wt_DGV8LAzRSfKZWiQ,-1.287985,37.044124,2021.0,10.0,0.000000,0.000000,0.000000,0.000000
126413,100451,zzzaSItdTD9Tirtzu6aDnA,-1.274018,37.035957,2021.0,10.0,0.000000,0.000000,0.000000,0.000000

In [32]:
df = pd.read_csv('/Users/wenlanzhang/PycharmProjects/SVI_Waste/Data/img_path.csv')
# df.drop(columns=['_0', '_90', '_180', '_270'], inplace=True)
# df_sorted = df.sort_values(by='panoid')
# df_sorted = df_sorted.reset_index()
df_sorted

,index,panoid,lat,lon,year,month,img_path,ang_0,ang_90,ang_180,ang_270
0,16186,---kW5kLNFT2eKu77K0BSg,-1.337135,36.735751,2021.0,7.0,-/-/,0.000000,0.000000,0.000000,0.000000
1,16185,---kW5kLNFT2eKu77K0BSg,-1.337135,36.735751,2021.0,7.0,-/-/,0.000000,0.000000,0.000000,0.000000
2,28639,--3w2NTa6dWsDSlB7lQqiA,-1.304348,36.742095,2018.0,1.0,-/-/,0.000000,0.000000,0.000000,0.000000
3,28541,--5kqrbr7DiSKTlMm6mmZw,-1.279489,36.716701,2018.0,2.0,-/-/,0.000000,0.657491,0.000000,0.000000
4,93757,--6rir7WBjJoKcL5UgHzFw,-1.284360,36.972830,2018.0,2.0,-/-/,0.000000,0.000000,0.000000,0.683942
...,...,...,...,...,...,...,...,...,...,...,...
126409,107337,zzvWdmTO_4oxT63l1GeS7w,-1.300941,36.811408,2018.0,3.0,Z/Z/,0.643877,0.000000,0.000000,0.000000
126410,98735,zzvWdmTO_4oxT63l1GeS7w,-1.300941,36.811408,2018.0,3.0,Z/Z/,0.643877,0.000000,0.000000,0.000000
126411,5218,zzxSjzuQ7B44-cL2EPhyMg,-1.268607,36.845904,2021.0,9.0,Z/Z/,0.745615,0.000000,0.636643,0.000000
126412,37994,zzz5Wt_DGV8LAzRSfKZWiQ,-1.287985,37.044124,2021.0,10.0,Z/Z/,0.000000,0.000000,0.000000,0.000000
126413,100451,zzzaSItdTD9Tirtzu6aDnA,-1.274018,37.035957,2021.0,10.0,Z/Z/,0.000000,0.000000,0.000000,0.000000

In [39]:
df_sorted['ang_0'] = df_20240113_sorted['ang_0']
df_sorted['ang_90'] = df_20240113_sorted['ang_90']
df_sorted['ang_180'] = df_20240113_sorted['ang_180']
df_sorted['ang_270'] = df_20240113_sorted['ang_270']
df_sorted

,index,panoid,lat,lon,year,month,img_path,ang_0,ang_90,ang_180,ang_270
0,16186,---kW5kLNFT2eKu77K0BSg,-1.337135,36.735751,2021.0,7.0,-/-/,0.000000,0.000000,0.000000,0.000000
1,16185,---kW5kLNFT2eKu77K0BSg,-1.337135,36.735751,2021.0,7.0,-/-/,0.000000,0.000000,0.000000,0.000000
2,28639,--3w2NTa6dWsDSlB7lQqiA,-1.304348,36.742095,2018.0,1.0,-/-/,0.000000,0.000000,0.000000,0.000000
3,28541,--5kqrbr7DiSKTlMm6mmZw,-1.279489,36.716701,2018.0,2.0,-/-/,0.000000,0.657491,0.000000,0.000000
4,93757,--6rir7WBjJoKcL5UgHzFw,-1.284360,36.972830,2018.0,2.0,-/-/,0.000000,0.000000,0.000000,0.683942
...,...,...,...,...,...,...,...,...,...,...,...
126409,107337,zzvWdmTO_4oxT63l1GeS7w,-1.300941,36.811408,2018.0,3.0,Z/Z/,0.643877,0.000000,0.000000,0.000000
126410,98735,zzvWdmTO_4oxT63l1GeS7w,-1.300941,36.811408,2018.0,3.0,Z/Z/,0.643877,0.000000,0.000000,0.000000
126411,5218,zzxSjzuQ7B44-cL2EPhyMg,-1.268607,36.845904,2021.0,9.0,Z/Z/,0.745615,0.000000,0.636643,0.000000
126412,37994,zzz5Wt_DGV8LAzRSfKZWiQ,-1.287985,37.044124,2021.0,10.0,Z/Z/,0.000000,0.000000,0.000000,0.000000
126413,100451,zzzaSItdTD9Tirtzu6aDnA,-1.274018,37.035957,2021.0,10.0,Z/Z/,0.000000,0.000000,0.000000,0.000000

In [24]:
df_sorted.to_csv('/Users/wenlanzhang/PycharmProjects/SVI_Waste/Data/img_path_20240113.csv', index=False)

# convert to long

In [44]:
# Reshape the DataFrame from wide to long format
df_long = pd.melt(df_sorted, id_vars=['index', 'panoid', 'lat', 'lon', 'year', 'month', 'img_path'],
                   var_name='angle', value_name='value')

# Extract the angle values from the column names
df_long['angle'] = df_long['angle'].str.replace('ang_', '').astype(int)

# Print the resulting long-format DataFrame
df_long

,index,panoid,lat,lon,year,month,img_path,angle,value
0,16186,---kW5kLNFT2eKu77K0BSg,-1.337135,36.735751,2021.0,7.0,-/-/,0,0.0
1,16185,---kW5kLNFT2eKu77K0BSg,-1.337135,36.735751,2021.0,7.0,-/-/,0,0.0
2,28639,--3w2NTa6dWsDSlB7lQqiA,-1.304348,36.742095,2018.0,1.0,-/-/,0,0.0
3,28541,--5kqrbr7DiSKTlMm6mmZw,-1.279489,36.716701,2018.0,2.0,-/-/,0,0.0
4,93757,--6rir7WBjJoKcL5UgHzFw,-1.284360,36.972830,2018.0,2.0,-/-/,0,0.0
...,...,...,...,...,...,...,...,...,...
505651,107337,zzvWdmTO_4oxT63l1GeS7w,-1.300941,36.811408,2018.0,3.0,Z/Z/,270,0.0
505652,98735,zzvWdmTO_4oxT63l1GeS7w,-1.300941,36.811408,2018.0,3.0,Z/Z/,270,0.0
505653,5218,zzxSjzuQ7B44-cL2EPhyMg,-1.268607,36.845904,2021.0,9.0,Z/Z/,270,0.0
505654,37994,zzz5Wt_DGV8LAzRSfKZWiQ,-1.287985,37.044124,2021.0,10.0,Z/Z/,270,0.0
505655,100451,zzzaSItdTD9Tirtzu6aDnA,-1.274018,37.035957,2021.0,10.0,Z/Z/,270,0.0

In [45]:
df_long['img_name'] = df_long['panoid'] + '_' + df_long['angle'].astype(str)
df_long

,index,panoid,lat,lon,year,month,img_path,angle,value,img_name
0,16186,---kW5kLNFT2eKu77K0BSg,-1.337135,36.735751,2021.0,7.0,-/-/,0,0.0,---kW5kLNFT2eKu77K0BSg_0
1,16185,---kW5kLNFT2eKu77K0BSg,-1.337135,36.735751,2021.0,7.0,-/-/,0,0.0,---kW5kLNFT2eKu77K0BSg_0
2,28639,--3w2NTa6dWsDSlB7lQqiA,-1.304348,36.742095,2018.0,1.0,-/-/,0,0.0,--3w2NTa6dWsDSlB7lQqiA_0
3,28541,--5kqrbr7DiSKTlMm6mmZw,-1.279489,36.716701,2018.0,2.0,-/-/,0,0.0,--5kqrbr7DiSKTlMm6mmZw_0
4,93757,--6rir7WBjJoKcL5UgHzFw,-1.284360,36.972830,2018.0,2.0,-/-/,0,0.0,--6rir7WBjJoKcL5UgHzFw_0
...,...,...,...,...,...,...,...,...,...,...
505651,107337,zzvWdmTO_4oxT63l1GeS7w,-1.300941,36.811408,2018.0,3.0,Z/Z/,270,0.0,zzvWdmTO_4oxT63l1GeS7w_270
505652,98735,zzvWdmTO_4oxT63l1GeS7w,-1.300941,36.811408,2018.0,3.0,Z/Z/,270,0.0,zzvWdmTO_4oxT63l1GeS7w_270
505653,5218,zzxSjzuQ7B44-cL2EPhyMg,-1.268607,36.845904,2021.0,9.0,Z/Z/,270,0.0,zzxSjzuQ7B44-cL2EPhyMg_270
505654,37994,zzz5Wt_DGV8LAzRSfKZWiQ,-1.287985,37.044124,2021.0,10.0,Z/Z/,270,0.0,zzz5Wt_DGV8LAzRSfKZWiQ_270
505655,100451,zzzaSItdTD9Tirtzu6aDnA,-1.274018,37.035957,2021.0,10.0,Z/Z/,270,0.0,zzzaSItdTD9Tirtzu6aDnA_270

In [46]:
df_long.to_csv('/Users/wenlanzhang/PycharmProjects/SVI_Waste/Data/data_long.csv', index=False)

# Select non 0 cells

In [47]:
df_long_n0 = df_long[df_long['value'] !=0]
df_long_n0

,index,panoid,lat,lon,year,month,img_path,angle,value,img_name
14,62980,--RL-phHNlZlg9bGS-7UKQ,-1.276972,36.963164,2018.0,2.0,-/-/,0,0.669043,--RL-phHNlZlg9bGS-7UKQ_0
22,60444,--agTAuB3_qSd3Ml61UQBA,-1.269893,36.920001,2018.0,1.0,-/-/,0,0.626960,--agTAuB3_qSd3Ml61UQBA_0
23,36245,--bF52zepYkkmotd5TYhDw,-1.251215,37.023054,2018.0,2.0,-/-/,0,0.677081,--bF52zepYkkmotd5TYhDw_0
24,76138,--e5EXQUQ4DpdjyZSmZ0PQ,-1.362253,36.924072,2018.0,4.0,-/-/,0,0.785355,--e5EXQUQ4DpdjyZSmZ0PQ_0
26,40846,--gztpPxVlgQtgUzGsxh7w,-1.219777,36.899377,2018.0,2.0,-/-/,0,0.665088,--gztpPxVlgQtgUzGsxh7w_0
...,...,...,...,...,...,...,...,...,...,...
505587,37150,zy8XtU1DFxV14coaA6DiEg,-1.255197,36.671482,2017.0,12.0,Z/y/,270,0.777539,zy8XtU1DFxV14coaA6DiEg_270
505593,98399,zyUIqb_jEfrEnNRj88UntA,-1.255349,36.919906,2018.0,2.0,Z/y/,270,0.895170,zyUIqb_jEfrEnNRj88UntA_270
505594,103153,zyVMtKy1vJiVJVKsY4tMuQ,-1.208400,36.949851,2021.0,9.0,Z/y/,270,0.746431,zyVMtKy1vJiVJVKsY4tMuQ_270
505595,17491,zyVojU5zQ1SGbAYCaUTHmQ,-1.154208,36.952961,2021.0,12.0,Z/y/,270,0.699477,zyVojU5zQ1SGbAYCaUTHmQ_270
505611,71561,zyuKiiuV5EBlAEXxhmS0BQ,-1.283829,37.052720,2018.0,2.0,Z/y/,270,0.821616,zyuKiiuV5EBlAEXxhmS0BQ_270

In [48]:
df_long_n0.to_csv('/Users/wenlanzhang/PycharmProjects/SVI_Waste/Data/df_long_n0.csv', index=False)

# Move file for manuel check and label

In [49]:
import os
import shutil
import pandas as pd

In [50]:
# Reading the CSV file
df_filtered = pd.read_csv('/Users/wenlanzhang/PycharmProjects/SVI_Waste/Data/df_long_n0.csv')
df_filtered

,index,panoid,lat,lon,year,month,img_path,angle,value,img_name
0,62980,--RL-phHNlZlg9bGS-7UKQ,-1.276972,36.963164,2018.0,2.0,-/-/,0,0.669043,--RL-phHNlZlg9bGS-7UKQ_0
1,60444,--agTAuB3_qSd3Ml61UQBA,-1.269893,36.920001,2018.0,1.0,-/-/,0,0.626960,--agTAuB3_qSd3Ml61UQBA_0
2,36245,--bF52zepYkkmotd5TYhDw,-1.251215,37.023054,2018.0,2.0,-/-/,0,0.677081,--bF52zepYkkmotd5TYhDw_0
3,76138,--e5EXQUQ4DpdjyZSmZ0PQ,-1.362253,36.924072,2018.0,4.0,-/-/,0,0.785355,--e5EXQUQ4DpdjyZSmZ0PQ_0
4,40846,--gztpPxVlgQtgUzGsxh7w,-1.219777,36.899377,2018.0,2.0,-/-/,0,0.665088,--gztpPxVlgQtgUzGsxh7w_0
...,...,...,...,...,...,...,...,...,...,...
68330,37150,zy8XtU1DFxV14coaA6DiEg,-1.255197,36.671482,2017.0,12.0,Z/y/,270,0.777539,zy8XtU1DFxV14coaA6DiEg_270
68331,98399,zyUIqb_jEfrEnNRj88UntA,-1.255349,36.919906,2018.0,2.0,Z/y/,270,0.895170,zyUIqb_jEfrEnNRj88UntA_270
68332,103153,zyVMtKy1vJiVJVKsY4tMuQ,-1.208400,36.949851,2021.0,9.0,Z/y/,270,0.746431,zyVMtKy1vJiVJVKsY4tMuQ_270
68333,17491,zyVojU5zQ1SGbAYCaUTHmQ,-1.154208,36.952961,2021.0,12.0,Z/y/,270,0.699477,zyVojU5zQ1SGbAYCaUTHmQ_270
68334,71561,zyuKiiuV5EBlAEXxhmS0BQ,-1.283829,37.052720,2018.0,2.0,Z/y/,270,0.821616,zyuKiiuV5EBlAEXxhmS0BQ_270

In [51]:
# Set your base path for the source images
basepath = '/Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/'  # Replace with your base path

# Set your destination path
destination_path = '/Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/PreScreen/'  # Replace with your destination path

# Set to keep track of copied images
copied_images = set()

In [52]:
df_subset = df_filtered.iloc[4000:6000]

# df_subset = df_filtered.iloc[500:1000]
# df_subset = df_filtered.iloc[1500:4000]

In [53]:
# Iterate over the DataFrame rows
for index, row in df_subset.iterrows():
    # Construct the source file path
    img_folder = row['img_path']  # This should be something like 'Q/g/'
    modified_img_name = row['img_name'] + '.jpg'  # Assuming the file extension is .jpg
    source_path = os.path.join(basepath, img_folder, modified_img_name)

    # Construct the destination file path
    dest_file_path = os.path.join(destination_path, modified_img_name)

    # Check if the image has already been copied
    if modified_img_name not in copied_images:
        # Copy the file
        if os.path.exists(source_path):
            shutil.copy2(source_path, dest_file_path)
            copied_images.add(modified_img_name)
        else:
            print(f"File not found: {source_path}")
    else:
        print(f"Already copied: {modified_img_name}")

Already copied: Dsn3dvCNvL_06BYEZ_E3YQ_0.jpg
Already copied: Du6EuztGH_IJXSywM_nA1g_0.jpg
Already copied: DxMt6sfLIZO1zAxATrTtuA_0.jpg
Already copied: DxMt6sfLIZO1zAxATrTtuA_0.jpg
Already copied: E1-gEZEKbEdUzaEmM1fCbw_0.jpg
Already copied: E266ooyE8DnQ76kr839YPg_0.jpg
Already copied: E4S8eFoNwALbVoX3_1fmWA_0.jpg
Already copied: E4ZGGuVdL7V7Er8nYVr4GA_0.jpg
Already copied: E8kgwKp76CSiTgePOfMZvg_0.jpg
Already copied: E9xgVby7BSqF4SQDD4fexQ_0.jpg
Already copied: EAv2ql-HB0_XW97zDYIfmg_0.jpg
Already copied: EAv2ql-HB0_XW97zDYIfmg_0.jpg
Already copied: ECCcgl2anGB0aFqMW88BYg_0.jpg
Already copied: ECO6b_XtSgkzBPH6mglSeA_0.jpg
Already copied: EDN6w_yvA4KSapBL_NgAQg_0.jpg
Already copied: EMBrBkgERSDW4GnugRhiXQ_0.jpg
Already copied: EMBrBkgERSDW4GnugRhiXQ_0.jpg
Already copied: EMBrBkgERSDW4GnugRhiXQ_0.jpg
Already copied: EMcku9J78euNIFcSBwf2UA_0.jpg
Already copied: ENghuV-zYJGVomUSm-uqhg_0.jpg
Already copied: ENghuV-zYJGVomUSm-uqhg_0.jpg
Already copied: EPB2TaYnd2pHB0NAfIzd4w_0.jpg
Already copied: ER4aY_nsw1MIGf5ahmRe9g_0.jpg
Already copied: EXqm4InjR_d6nb736yhgLg_0.jpg
Already copied: EcpNRoG8-9sYFegvFvwIbQ_0.jpg
Already copied: Edx_HF2owuzWdLNgyIwLsg_0.jpg
Already copied: EnjQgnNzSVUffbeRgphVlw_0.jpg
Already copied: EoPH3317ISFmQzuzMELvaQ_0.jpg
Already copied: EpS-nyMKL474Ux9tHU_PBA_0.jpg
Already copied: EpS-nyMKL474Ux9tHU_PBA_0.jpg
Already copied: ErYw_4floPcZia_XdPVjzA_0.jpg
Already copied: EsGi4VmAv6bZqIKnfKIZ1g_0.jpg
Already copied: EsGi4VmAv6bZqIKnfKIZ1g_0.jpg
Already copied: Es_KCKP9TfkIf--mneAG0g_0.jpg
Already copied: EslnS1sui6wIkc23le_gSA_0.jpg
Already copied: Ez43aobFdnio97B03P0cRg_0.jpg
Already copied: F-jhrJwDZlQMNb7SWUwcbQ_0.jpg
Already copied: F234unqU_79zrJLW_FkxTw_0.jpg
Already copied: F2K2TSrY6dXKbiJO2PZguQ_0.jpg
Already copied: F2V0srlD7dM6z_BXfBSo1w_0.jpg
Already copied: F6dYScTYk6halyZVySDGbg_0.jpg
Already copied: FC2lKGCjZd5owI9Dvr_Dzg_0.jpg
Already copied: FC3Ixppqi-Ss2X0DSgbaWg_0.jpg
Already copied: FC3Ixppqi-Ss2X0DSgbaWg_0.jpg
Already copied: FDCMGbIGPVirAuOZUKWnaA_0.jpg
Already copied: FI-2qVzJtK4x9EKmD481hg_0.jpg
Already copied: FNtANopP2dNIrXTvWxEZ0A_0.jpg
Already copied: FSzkZgAqewy1Uydv8pEKeg_0.jpg
Already copied: FW2ft8Y5oPntvkVUakHQCw_0.jpg
Already copied: FW2ft8Y5oPntvkVUakHQCw_0.jpg
Already copied: FWmL8T5BNls-26qXo4MfRw_0.jpg
Already copied: FhoL7tTedh2Xp5Hh7Fd03g_0.jpg
Already copied: FkHvHFmm-SrAVKRH6A-svQ_0.jpg
Already copied: FqyogBDkj7ZB1UVT0boTiw_0.jpg
Already copied: FrgHh9VWLOrrPbluw7wIZQ_0.jpg
Already copied: Ftauv-NfIQTRwIbD45IqCQ_0.jpg
Already copied: FvRsXV-kY-GGjq1il5sDQg_0.jpg
Already copied: FxQDxuXzqK528NBrkIpn9g_0.jpg
Already copied: FzagVC5rXDtqfTlpnGMPrg_0.jpg
Already copied: FzqsuDYtaeQyY0mTX5xiMw_0.jpg
Already copied: G-Zb6mb80E-G3d-KiXyt7g_0.jpg
Already copied: G-dAG1QrXI4U-VWLC7xu1g_0.jpg
Already copied: G3bHxB16pqA2o2YdtK0CXw_0.jpg
Already copied: GATJv0zNx_LrwO67eywa4A_0.jpg
Already copied: GGKaa3jivzLJ0EwhYhlQxw_0.jpg
Already copied: GGxlnUSxwYcRXWTvTeaS1g_0.jpg
Already copied: GKX-9-E32Wtbyfw_ekTcGA_0.jpg
Already copied: GMrV1yBCTHUNvPbWG7N5nA_0.jpg
Already copied: GMrV1yBCTHUNvPbWG7N5nA_0.jpg
Already copied: GQQ-Dy8_5kX2oXFo-gWZig_0.jpg
Already copied: GQm3mKj6iLZi1LWwnLRwEA_0.jpg
Already copied: GQm3mKj6iLZi1LWwnLRwEA_0.jpg
Already copied: GQm3mKj6iLZi1LWwnLRwEA_0.jpg
Already copied: GQm3mKj6iLZi1LWwnLRwEA_0.jpg
Already copied: GSwrQUHUcD3FP-0hN3byWg_0.jpg
Already copied: GZTZMFkvIWgIWXFeenZEtw_0.jpg
Already copied: G_2QW4uPTErZyPYn5bTBog_0.jpg
Already copied: GcyVzS1yvyvP6r-ifHVCgQ_0.jpg
Already copied: GhzWWSIQvdSRyO2v5ySpqQ_0.jpg
Already copied: GiAwXo466dpYo25GEEK_0g_0.jpg
Already copied: GiyEJDM8pEljdeeCl1BCBg_0.jpg
Already copied: GlByG11vVD08qLsVJRKsyw_0.jpg
Already copied: GnKPWHlNgtb1UpKZKajFUw_0.jpg
Already copied: GohXNJLaXN0JaI4BFpX_EQ_0.jpg
Already copied: Gs6iOS_CA697ctoH9u48DQ_0.jpg
Already copied: Gt3oTwVUZO0KN1c-vmYiQQ_0.jpg
Already copied: GwJ9ciM0gCU49B9M-q_ORQ_0.jpg
Already copied: H-Yx6bcDhhSnMRm9wmyQLg_0.jpg
Already copied: H-_gPKgTBGbo2HzJMs5QQg_0.jpg
Already copied: H0MAslSsJ0F28RiTHHnpHQ_0.jpg
Already copied: H2AHNacFOeR39pCiUOtk6g_0.jpg
Already copied: H2AHNacFOeR39pCiUOtk6g_0.jpg
Already copied: H2AHNacFOeR39pCiUOtk6g_0.jpg
Already copied: H50hG7PUhKzxv3EG3KWj2w_0.jpg
Already copied: H50hG7PUhKzxv3EG3KWj2w_0.jpg
Already copied: H7GdZn926EhIhTLHDVewhg_0.jpg
Already copied: H7vNndbEw5OnYbGXHDP8Bg_0.jpg
Already copied: HCAcW2lvk9mG7YgJTaMFKg_0.jpg
Already copied: HFtlUgxnU03LdbZzmXLkXw_0.jpg
Already copied: HJP0c-XYWxOVhpCBTP-U3A_0.jpg
Already copied: HRyDT_YFzaFdLgH8YHXA3Q_0.jpg
Already copied: HXGA2-swuuvUuMhLDTTB9A_0.jpg
Already copied: HXPP7uKfPetN-LdksAyoQQ_0.jpg
Already copied: HYAdnMVmzEVIWSei4qG7CA_0.jpg
Already copied: HYAdnMVmzEVIWSei4qG7CA_0.jpg
Already copied: HbPivJzaZcXa2AlnLd_sVA_0.jpg
Already copied: Hfxgw3JNYuoQqCqgP8USRg_0.jpg
Already copied: HgSlOqxz2D_XK_QUajYYOA_0.jpg
Already copied: HhfQujQQtoanEqFgKiMEpQ_0.jpg
Already copied: HhfQujQQtoanEqFgKiMEpQ_0.jpg
Already copied: Hl3Fu8ljaz1NsWPnx8t4BQ_0.jpg
Already copied: Ho0ppgrCxC3kY3i00odezw_0.jpg
Already copied: HuJ3p9u1hz2qW7KCFyfJkg_0.jpg
Already copied: HxHJMwjwXUeCNrjC20Kiug_0.jpg
Already copied: HxHJMwjwXUeCNrjC20Kiug_0.jpg
Already copied: I-K4Ru7ks6WCR_dlX4jLZg_0.jpg
Already copied: I1J9swUxn5ucIDejyP7tKQ_0.jpg
Already copied: I1JLkv1cc_8D57_7PmzfAw_0.jpg
Already copied: I24BzAD5LSXBVYxkc8g0iw_0.jpg
Already copied: I3Jsbycdy7HHtFXd1NckAA_0.jpg
Already copied: I6Ckm2xrzOi-JUAKTaMXrA_0.jpg
Already copied: I9DCFn4xNjv9QpI5qXpB2Q_0.jpg
Already copied: I9DCFn4xNjv9QpI5qXpB2Q_0.jpg
Already copied: IEhYNLOYDZMOi9CjKhkvaw_0.jpg
Already copied: IFF-GY07WJH8gQpi4xuRjg_0.jpg
Already copied: IGHwCprfY5SXhr_PGb4pEg_0.jpg
Already copied: IJtrFuK19TP6S09ro6tXxQ_0.jpg
Already copied: IJtrFuK19TP6S09ro6tXxQ_0.jpg
Already copied: IJtrFuK19TP6S09ro6tXxQ_0.jpg
Already copied: IQYCO8yK47Oxem3YuaezoQ_0.jpg
Already copied: IRqCEFN91pXQrCy0Ru9vmw_0.jpg
Already copied: IRuo7NHse8kmpCz5KVWGGQ_0.jpg
Already copied: ITmST8OojCMluI1zfN0VAQ_0.jpg
Already copied: IZr4ugLJD_gbWvWnE0pwZg_0.jpg
Already copied: Ia7SvFDmuYXjcdQ6olIsQA_0.jpg
Already copied: Ia7SvFDmuYXjcdQ6olIsQA_0.jpg
Already copied: Ia7SvFDmuYXjcdQ6olIsQA_0.jpg
Already copied: IaISgRKekvL6WoaUosHATA_0.jpg
Already copied: IcViol92oLE9TXbNnemflg_0.jpg
Already copied: IdA1LZrO1cUFFlfoErYsBw_0.jpg
Already copied: Ifmtx0j4lNyJzF5a-qgC5A_0.jpg
Already copied: IiZ1SM-gPXI6pnH6zgdy1g_0.jpg
Already copied: IidV_M6ImDdKa1VIDMkO7w_0.jpg
Already copied: IidotkmP8uEr5ck1py2PpQ_0.jpg
Already copied: IkyPcsnSnxwUb-iKKf_M1w_0.jpg
Already copied: IkyPcsnSnxwUb-iKKf_M1w_0.jpg
Already copied: IkyPcsnSnxwUb-iKKf_M1w_0.jpg
Already copied: In9tBoUIX5GO4OYes9_Ftg_0.jpg
Already copied: InlSMcHJACCwoRvtWbdmnQ_0.jpg
Already copied: InlSMcHJACCwoRvtWbdmnQ_0.jpg
Already copied: Inxvi4Jqil7mOiZ-OpHcSg_0.jpg
Already copied: Inxvi4Jqil7mOiZ-OpHcSg_0.jpg
Already copied: IsPe3axT1pfOzYU8-483sA_0.jpg
Already copied: IsPe3axT1pfOzYU8-483sA_0.jpg
Already copied: IszA4Mbgaq7aVqqdVg46dg_0.jpg
Already copied: Iy5CIyDNR4rdAyfMfwDDYA_0.jpg
Already copied: IzO_ZzPQbbchVKIsEnn75Q_0.jpg
Already copied: J0gg6eGHL_xgIgtXxnlxJg_0.jpg
Already copied: J0gg6eGHL_xgIgtXxnlxJg_0.jpg
Already copied: J0oKwSICUFmp_lmj_5-ncw_0.jpg
Already copied: J5LJvLfU63SY-fijp3EkOQ_0.jpg
Already copied: J5NJR1Ln80D9n8jcBkYPqA_0.jpg
Already copied: J6umIv-6ZdSxdvhvohfUrw_0.jpg
Already copied: J6umIv-6ZdSxdvhvohfUrw_0.jpg
Already copied: J6umIv-6ZdSxdvhvohfUrw_0.jpg
Already copied: JCM0ZLl9YhuLOAZkVYV2Wg_0.jpg
Already copied: JG9xVCP6fzIhbEs7oauitg_0.jpg
Already copied: JG9xVCP6fzIhbEs7oauitg_0.jpg
Already copied: JGycwMmaXiglW01_eFfmvw_0.jpg
Already copied: JGycwMmaXiglW01_eFfmvw_0.jpg
Already copied: JJM7H6pL6iFmdh5Pvai3sg_0.jpg
Already copied: JJM7H6pL6iFmdh5Pvai3sg_0.jpg
Already copied: JJMjmTEDpbOaz5ENSPwXJw_0.jpg
Already copied: JJMjmTEDpbOaz5ENSPwXJw_0.jpg
Already copied: JKFnH2o0hCE1eBnn3kxB_g_0.jpg
Already copied: JLRVeJhL39hgd46t8bRx9Q_0.jpg
Already copied: JPu4w2sM10UyF8Z84DFrag_0.jpg
Already copied: JPuGhpFnqFWQ7-rDzmedQg_0.jpg
Already copied: JQoLcBzLAPnNChg_Rpfvqg_0.jpg
Already copied: JQoLcBzLAPnNChg_Rpfvqg_0.jpg
Already copied: JQoLcBzLAPnNChg_Rpfvqg_0.jpg
Already copied: JQoLcBzLAPnNChg_Rpfvqg_0.jpg
Already copied: JQoLcBzLAPnNChg_Rpfvqg_0.jpg
Already copied: JWTNT8ijfNmtEEkXY2cNmg_0.jpg
Already copied: JYyVSQBSRvCCQxR9taS_Zg_0.jpg
Already copied: JZqFDwau6VH95Vd_rAZEPg_0.jpg
Already copied: J_XKJJfEpf9XNDzocbcsrw_0.jpg
Already copied: JbYtgkem-8yqAg8Q6MXiOw_0.jpg
Already copied: Jbc0jKUia7OQxU1rwUu1Aw_0.jpg
Already copied: JbuFFrm4NORcu_WiijnEhA_0.jpg
Already copied: JcCiT6QIfEfBtGdnu4FYKQ_0.jpg
Already copied: Jg7_mutDTM3u3Y-5Py8qCw_0.jpg
Already copied: Jg7_mutDTM3u3Y-5Py8qCw_0.jpg
Already copied: Jl1rGk_us2nezowaTYaxsA_0.jpg
Already copied: Jn99tEHS_VSPioA_Irmfdg_0.jpg
Already copied: Jqv50-bC-wUsQ_9XBlLvVQ_0.jpg
Already copied: JvSCkH5SjVQGb4EMY6GSAA_0.jpg

Already copied: Jyhy2ROxqxt-Rqzgw6Q4jQ_0.jpg
Already copied: Jyk0RqHaIcw4lJC7Qenexw_0.jpg
Already copied: KA1yN7jAMwm_B9jKxr0HtA_0.jpg
Already copied: KB8qxNUK32Pm-TJ8ocZPbA_0.jpg
Already copied: KCMHsbZRHYQ3NtmWYMD86Q_0.jpg
Already copied: KCn3tfuBWrLaiW5CuhNxiA_0.jpg
Already copied: KGMChCnT_CxZTdVzeZ1LGA_0.jpg
Already copied: KOOCV_9af2sHHUhh48cJKA_0.jpg
Already copied: KQ8bl9keJCU3AB4_16X0Zg_0.jpg
Already copied: KUEKNLmVLsh2BXkCB1BmUw_0.jpg
Already copied: KUhfiGtlhZjLkOpeCC3r_A_0.jpg
Already copied: KV1_KrYJSwDfOAA2tcaVkQ_0.jpg
Already copied: KX6-h1qjM4xIDXRpeCmUWw_0.jpg
Already copied: KeB6ai6D08kMdQGcMNgt2g_0.jpg
Already copied: Kh1_jkZdD06CM1Wmg6Pn4w_0.jpg
Already copied: KhvRHSUz87ASfIWAsZQ9zQ_0.jpg
Already copied: KleLuw9ZsFNl_Ehrhi7FZA_0.jpg
Already copied: KpuIXodMxMCVps4NIAqdyg_0.jpg
Already copied: KrBOhtzo48gMJLLTVSfnAg_0.jpg
Already copied: L0E5FRSY5Px1GwZ0nmsBlw_0.jpg
Already copied: L0E5FRSY5Px1GwZ0nmsBlw_0.jpg
Already copied: L1Oc7iy3v-99B3xzC0JEpA_0.jpg
Already copied: L1jTmWHb3h4V7fWefrxCgg_0.jpg