The data has duplicates.   
original 126,414, but actual 113,341  
ORIGINAL 505656, but actual 453,364

In [3]:
import pandas as pd

In [ ]:
Base = ''
Date = ''

In [16]:
# incomplete column name
column_names = ["pk", "id", "panoid", 'lat', 'lon', 'year', 'month', 'marker', 
                'Yo_0', 'Yo_90','Yo_180', 'Yo_270', 'LLM_0', 'LLM_90', 'LLM_180', 'LLM_270']
df_GSVI = pd.read_csv('/Users/wenlanzhang/PycharmProjects/SVI_Waste/output_LLM_20240122.csv',
                     header=None, skiprows=1, names=column_names)
unique_df_GSVI = df_GSVI.drop_duplicates(subset='panoid', keep='first')
unique_df_GSVI.drop(columns=['pk', 'id', 'marker'], inplace=True)
df_GSVI_sorted = unique_df_GSVI.sort_values(by='panoid')
df_GSVI_sorted = df_GSVI_sorted.reset_index()
df_GSVI_sorted

/var/folders/2_/nk9j6sb901n_fk5dz_9vtqj80000gn/T/ipykernel_77728/3459855960.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  unique_df_GSVI.drop(columns=['pk', 'id', 'marker'], inplace=True)

,index,panoid,lat,lon,year,month,Yo_0,Yo_90,Yo_180,Yo_270,LLM_0,LLM_90,LLM_180,LLM_270
0,16185,---kW5kLNFT2eKu77K0BSg,-1.337135,36.735751,2021.0,7.0,0.00000,0.0,0.0,0.0,0,0,0,0
1,28639,--3w2NTa6dWsDSlB7lQqiA,-1.304348,36.742095,2018.0,1.0,0.48414,0.0,0.0,0.0,0,0,0,0
2,28541,--5kqrbr7DiSKTlMm6mmZw,-1.279489,36.716701,2018.0,2.0,0.00000,0.0,0.0,0.0,0,0,0,0
3,93757,--6rir7WBjJoKcL5UgHzFw,-1.284360,36.972830,2018.0,2.0,0.00000,0.0,0.0,0.0,0,0,0,0
4,73927,--6yC0DbJTF8nxE2iXrbvQ,-1.490452,36.958099,2022.0,3.0,0.00000,0.0,0.0,0.0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113336,43673,zzu_OfR5p0sFK6uT6rTL4w,-1.252012,37.001303,2018.0,2.0,0.00000,0.0,0.0,0.0,0,0,0,0
113337,98733,zzvWdmTO_4oxT63l1GeS7w,-1.300941,36.811408,2018.0,3.0,0.00000,0.0,0.0,0.0,0,0,0,0
113338,5218,zzxSjzuQ7B44-cL2EPhyMg,-1.268607,36.845904,2021.0,9.0,0.00000,0.0,0.0,0.0,0,0,0,0
113339,37994,zzz5Wt_DGV8LAzRSfKZWiQ,-1.287985,37.044124,2021.0,10.0,0.00000,0.0,0.0,0.0,0,0,0,0
113340,100451,zzzaSItdTD9Tirtzu6aDnA,-1.274018,37.035957,2021.0,10.0,0.00000,0.0,0.0,0.0,0,0,0,0

In [6]:
df_img_path = pd.read_csv('/Users/wenlanzhang/PycharmProjects/SVI_Waste/Data/Output/GSVI/img_path.csv')
# df_img_path.drop(columns=['ang_0', 'ang_90', 'ang_180', 'ang_270'], inplace=True)
# df_img_path_sort = df_img_path.sort_values(by='panoid')
# df_img_path_sort = df_img_path_sort.reset_index()
# df_img_path_sort
df_img_path

                        panoid       lat        lon    year  month img_path
0       ---kW5kLNFT2eKu77K0BSg -1.337135  36.735751  2021.0    7.0     -/-/
1       --3w2NTa6dWsDSlB7lQqiA -1.304348  36.742095  2018.0    1.0     -/-/
2       --5kqrbr7DiSKTlMm6mmZw -1.279489  36.716701  2018.0    2.0     -/-/
3       --6rir7WBjJoKcL5UgHzFw -1.284360  36.972830  2018.0    2.0     -/-/
4       --6yC0DbJTF8nxE2iXrbvQ -1.490452  36.958099  2022.0    3.0     -/-/
...                        ...       ...        ...     ...    ...      ...
113336  zzu_OfR5p0sFK6uT6rTL4w -1.252012  37.001303  2018.0    2.0     Z/Z/
113337  zzvWdmTO_4oxT63l1GeS7w -1.300941  36.811408  2018.0    3.0     Z/Z/
113338  zzxSjzuQ7B44-cL2EPhyMg -1.268607  36.845904  2021.0    9.0     Z/Z/
113339  zzz5Wt_DGV8LAzRSfKZWiQ -1.287985  37.044124  2021.0   10.0     Z/Z/
113340  zzzaSItdTD9Tirtzu6aDnA -1.274018  37.035957  2021.0   10.0     Z/Z/

[113341 rows x 6 columns]

In [17]:
df_GSVI_sorted['img_path'] = df_img_path['img_path']

df_GSVI_sorted

,index,panoid,lat,lon,year,month,Yo_0,Yo_90,Yo_180,Yo_270,LLM_0,LLM_90,LLM_180,LLM_270,img_path
0,16185,---kW5kLNFT2eKu77K0BSg,-1.337135,36.735751,2021.0,7.0,0.00000,0.0,0.0,0.0,0,0,0,0,-/-/
1,28639,--3w2NTa6dWsDSlB7lQqiA,-1.304348,36.742095,2018.0,1.0,0.48414,0.0,0.0,0.0,0,0,0,0,-/-/
2,28541,--5kqrbr7DiSKTlMm6mmZw,-1.279489,36.716701,2018.0,2.0,0.00000,0.0,0.0,0.0,0,0,0,0,-/-/
3,93757,--6rir7WBjJoKcL5UgHzFw,-1.284360,36.972830,2018.0,2.0,0.00000,0.0,0.0,0.0,0,0,0,0,-/-/
4,73927,--6yC0DbJTF8nxE2iXrbvQ,-1.490452,36.958099,2022.0,3.0,0.00000,0.0,0.0,0.0,0,0,0,0,-/-/
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113336,43673,zzu_OfR5p0sFK6uT6rTL4w,-1.252012,37.001303,2018.0,2.0,0.00000,0.0,0.0,0.0,0,0,0,0,Z/Z/
113337,98733,zzvWdmTO_4oxT63l1GeS7w,-1.300941,36.811408,2018.0,3.0,0.00000,0.0,0.0,0.0,0,0,0,0,Z/Z/
113338,5218,zzxSjzuQ7B44-cL2EPhyMg,-1.268607,36.845904,2021.0,9.0,0.00000,0.0,0.0,0.0,0,0,0,0,Z/Z/
113339,37994,zzz5Wt_DGV8LAzRSfKZWiQ,-1.287985,37.044124,2021.0,10.0,0.00000,0.0,0.0,0.0,0,0,0,0,Z/Z/
113340,100451,zzzaSItdTD9Tirtzu6aDnA,-1.274018,37.035957,2021.0,10.0,0.00000,0.0,0.0,0.0,0,0,0,0,Z/Z/

In [28]:
# Yolo8 Only
# Reshape the DataFrame from wide to long format
df_long = pd.melt(df_GSVI_sorted, id_vars=['index', 'panoid', 'lat', 'lon', 'year', 'month', 'img_path'],
                   var_name='angle', value_name='value')

# Extract the angle values from the column names
df_long['angle'] = df_long['angle'].str.replace('ang_', '').astype(int)

# Print the resulting long-format DataFrame
df_long

,index,panoid,lat,lon,year,month,img_path,angle,value
0,16186,---kW5kLNFT2eKu77K0BSg,-1.337135,36.735751,2021.0,7.0,-/-/,0,0.00000
1,16185,---kW5kLNFT2eKu77K0BSg,-1.337135,36.735751,2021.0,7.0,-/-/,0,0.00000
2,28639,--3w2NTa6dWsDSlB7lQqiA,-1.304348,36.742095,2018.0,1.0,-/-/,0,0.48414
3,28541,--5kqrbr7DiSKTlMm6mmZw,-1.279489,36.716701,2018.0,2.0,-/-/,0,0.00000
4,93757,--6rir7WBjJoKcL5UgHzFw,-1.284360,36.972830,2018.0,2.0,-/-/,0,0.00000
...,...,...,...,...,...,...,...,...,...
505651,107337,zzvWdmTO_4oxT63l1GeS7w,-1.300941,36.811408,2018.0,3.0,Z/Z/,270,0.00000
505652,98735,zzvWdmTO_4oxT63l1GeS7w,-1.300941,36.811408,2018.0,3.0,Z/Z/,270,0.00000
505653,5218,zzxSjzuQ7B44-cL2EPhyMg,-1.268607,36.845904,2021.0,9.0,Z/Z/,270,0.00000
505654,37994,zzz5Wt_DGV8LAzRSfKZWiQ,-1.287985,37.044124,2021.0,10.0,Z/Z/,270,0.00000
505655,100451,zzzaSItdTD9Tirtzu6aDnA,-1.274018,37.035957,2021.0,10.0,Z/Z/,270,0.00000

In [21]:
# Yolov8 and LLM 

# Step 1: Melt for Yo columns
yo_long = pd.melt(df_GSVI_sorted, id_vars=['index', 'panoid', 'lat', 'lon', 'year', 'month', 'img_path'],
                  value_vars=['Yo_0', 'Yo_90', 'Yo_180', 'Yo_270'],
                  var_name='yo_angle', value_name='Yo')

# Extract angle for Yo
yo_long['ang'] = yo_long['yo_angle'].str.extract('(\d+)$').astype(int)
yo_long.drop('yo_angle', axis=1, inplace=True)

# Step 2: Melt for LLM columns
llm_long = pd.melt(df_GSVI_sorted, id_vars=['index', 'panoid', 'lat', 'lon', 'year', 'month', 'img_path'],
                   value_vars=['LLM_0', 'LLM_90', 'LLM_180', 'LLM_270'],
                   var_name='llm_angle', value_name='LLM')

# Extract angle for LLM
llm_long['ang'] = llm_long['llm_angle'].str.extract('(\d+)$').astype(int)
llm_long.drop('llm_angle', axis=1, inplace=True)

# Step 3: Merge the Yo and LLM long DataFrames
df_long = pd.merge(yo_long, llm_long, on=['index', 'panoid', 'lat', 'lon', 'year', 'month', 'img_path', 'ang'], how='inner')

# The resulting df_long DataFrame now has separate Yo and LLM columns, with a common 'ang' column for the angle
df_long

,index,panoid,lat,lon,year,month,img_path,Yo,ang,LLM
0,16185,---kW5kLNFT2eKu77K0BSg,-1.337135,36.735751,2021.0,7.0,-/-/,0.00000,0,0
1,28639,--3w2NTa6dWsDSlB7lQqiA,-1.304348,36.742095,2018.0,1.0,-/-/,0.48414,0,0
2,28541,--5kqrbr7DiSKTlMm6mmZw,-1.279489,36.716701,2018.0,2.0,-/-/,0.00000,0,0
3,93757,--6rir7WBjJoKcL5UgHzFw,-1.284360,36.972830,2018.0,2.0,-/-/,0.00000,0,0
4,73927,--6yC0DbJTF8nxE2iXrbvQ,-1.490452,36.958099,2022.0,3.0,-/-/,0.00000,0,0
...,...,...,...,...,...,...,...,...,...,...
453359,43673,zzu_OfR5p0sFK6uT6rTL4w,-1.252012,37.001303,2018.0,2.0,Z/Z/,0.00000,270,0
453360,98733,zzvWdmTO_4oxT63l1GeS7w,-1.300941,36.811408,2018.0,3.0,Z/Z/,0.00000,270,0
453361,5218,zzxSjzuQ7B44-cL2EPhyMg,-1.268607,36.845904,2021.0,9.0,Z/Z/,0.00000,270,0
453362,37994,zzz5Wt_DGV8LAzRSfKZWiQ,-1.287985,37.044124,2021.0,10.0,Z/Z/,0.00000,270,0
453363,100451,zzzaSItdTD9Tirtzu6aDnA,-1.274018,37.035957,2021.0,10.0,Z/Z/,0.00000,270,0

In [22]:
df_long.drop(columns=['index'], inplace=True)

# df_long = df_long.drop_duplicates() # duplicates should have been considered at the beginning.
df_long

,panoid,lat,lon,year,month,img_path,Yo,ang,LLM
0,---kW5kLNFT2eKu77K0BSg,-1.337135,36.735751,2021.0,7.0,-/-/,0.00000,0,0
1,--3w2NTa6dWsDSlB7lQqiA,-1.304348,36.742095,2018.0,1.0,-/-/,0.48414,0,0
2,--5kqrbr7DiSKTlMm6mmZw,-1.279489,36.716701,2018.0,2.0,-/-/,0.00000,0,0
3,--6rir7WBjJoKcL5UgHzFw,-1.284360,36.972830,2018.0,2.0,-/-/,0.00000,0,0
4,--6yC0DbJTF8nxE2iXrbvQ,-1.490452,36.958099,2022.0,3.0,-/-/,0.00000,0,0
...,...,...,...,...,...,...,...,...,...
453359,zzu_OfR5p0sFK6uT6rTL4w,-1.252012,37.001303,2018.0,2.0,Z/Z/,0.00000,270,0
453360,zzvWdmTO_4oxT63l1GeS7w,-1.300941,36.811408,2018.0,3.0,Z/Z/,0.00000,270,0
453361,zzxSjzuQ7B44-cL2EPhyMg,-1.268607,36.845904,2021.0,9.0,Z/Z/,0.00000,270,0
453362,zzz5Wt_DGV8LAzRSfKZWiQ,-1.287985,37.044124,2021.0,10.0,Z/Z/,0.00000,270,0
453363,zzzaSItdTD9Tirtzu6aDnA,-1.274018,37.035957,2021.0,10.0,Z/Z/,0.00000,270,0

In [24]:
df_long.to_csv('/Users/wenlanzhang/PycharmProjects/SVI_Waste/Data/Output/GSVI/0122/GSVI_long_20240204.csv', index=False)

# select rows

In [25]:
df_long

,panoid,lat,lon,year,month,img_path,Yo,ang,LLM
0,---kW5kLNFT2eKu77K0BSg,-1.337135,36.735751,2021.0,7.0,-/-/,0.00000,0,0
1,--3w2NTa6dWsDSlB7lQqiA,-1.304348,36.742095,2018.0,1.0,-/-/,0.48414,0,0
2,--5kqrbr7DiSKTlMm6mmZw,-1.279489,36.716701,2018.0,2.0,-/-/,0.00000,0,0
3,--6rir7WBjJoKcL5UgHzFw,-1.284360,36.972830,2018.0,2.0,-/-/,0.00000,0,0
4,--6yC0DbJTF8nxE2iXrbvQ,-1.490452,36.958099,2022.0,3.0,-/-/,0.00000,0,0
...,...,...,...,...,...,...,...,...,...
453359,zzu_OfR5p0sFK6uT6rTL4w,-1.252012,37.001303,2018.0,2.0,Z/Z/,0.00000,270,0
453360,zzvWdmTO_4oxT63l1GeS7w,-1.300941,36.811408,2018.0,3.0,Z/Z/,0.00000,270,0
453361,zzxSjzuQ7B44-cL2EPhyMg,-1.268607,36.845904,2021.0,9.0,Z/Z/,0.00000,270,0
453362,zzz5Wt_DGV8LAzRSfKZWiQ,-1.287985,37.044124,2021.0,10.0,Z/Z/,0.00000,270,0
453363,zzzaSItdTD9Tirtzu6aDnA,-1.274018,37.035957,2021.0,10.0,Z/Z/,0.00000,270,0

In [26]:
# df_long_se = df_long[df_long['value']>0]
df_long_se = df_long[df_long['LLM']==1]

df_long_se

,panoid,lat,lon,year,month,img_path,Yo,ang,LLM
98,-2QdlzZCwJEM1tO0AU9b4g,-1.274346,36.884966,2018.0,2.0,-/2/,0.374915,0,1
154,-4Rci70cakpla7qHAQ6RtA,-1.310624,36.791561,2021.0,7.0,-/4/,0.327264,0,1
206,-6SOXQcTZXuAv52dmWWkSw,-1.325439,36.835939,2021.0,7.0,-/6/,0.456282,0,1
509,-HCPm9uGbTfUuFYP7S7WqA,-1.210993,36.961580,2021.0,9.0,-/H/,0.259395,0,1
511,-HEB_u_ZPk9mELxyAcCGNw,-1.286155,36.895681,2021.0,8.0,-/H/,0.488870,0,1
...,...,...,...,...,...,...,...,...,...
451795,z64v4mjNGxNei83XFzekuw,-1.301790,36.901959,2021.0,7.0,Z/6/,0.490415,270,1
452304,zNdPGBdJVv2ErYUICdUhVg,-1.263239,36.863245,2018.0,2.0,Z/N/,0.600943,270,1
452483,zUAlQ-7npu34twtIjjFt6w,-1.271890,36.852577,2018.0,1.0,Z/U/,0.385207,270,1
452785,zeKYfi6QWcUgVmgum6Cf6A,-1.268957,36.849096,2018.0,1.0,Z/e/,0.457194,270,1
453200,zuKWK8EZ0QpiT5FfcMaxpQ,-1.255446,36.883093,2018.0,2.0,Z/U/,0.323091,270,1

In [35]:
df_long_se.to_csv('/Users/wenlanzhang/PycharmProjects/SVI_Waste/Data/Output/GSVI/0122/GSVI_True_0204.csv', index=False)

In [45]:
df_long_se2 = df_long[df_long['value']>0.6]
df_long_se2

,panoid,lat,lon,year,month,img_path,angle,value
63,-0wIGghq_wnmlSxQjvfs6Q,-1.260868,36.734328,2018.0,2.0,-/0/,0,0.634289
157,-3l0SHoc2SjGiBF8t3kaaQ,-1.263649,36.687267,2021.0,8.0,-/3/,0,0.712311
1201,-_Zxs2WP-X8m7qj-REHpnQ,-1.288800,36.792943,2021.0,7.0,-/_/,0,0.652671
1339,-dnEqpLrlgYAsG3FVFQ7Aw,-1.312481,36.684438,2021.0,8.0,-/d/,0,0.625009
1414,-gJRF24oKdAlQF_HCZp-Ww,-1.310656,36.760987,2021.0,7.0,-/g/,0,0.654180
...,...,...,...,...,...,...,...,...
504352,zJ3m1RcGYOkHkfxtMblPlw,-1.243302,36.677246,2021.0,8.0,Z/j/,270,0.608835
504489,zNdPGBdJVv2ErYUICdUhVg,-1.263239,36.863245,2018.0,2.0,Z/N/,270,0.600943
504562,zPig30_IDc_32vuwasPbCg,-1.247181,36.872716,2021.0,7.0,Z/P/,270,0.716719
504805,zYNhE7bkjo5zs-2s3J9kDg,-1.271822,36.943358,2021.0,8.0,Z/y/,270,0.712785
505491,zuzcDSjoJg3Le-sA5WXKLQ,-1.244422,36.681994,2021.0,10.0,Z/U/,270,0.725639

In [43]:
df_long_se2.to_csv('/Users/wenlanzhang/PycharmProjects/SVI_Waste/Data/Output/GSVI/0119/GSVI_6_0119.csv', index=False)

In [67]:
df_long_se2 = df_long[(df_long['value']<0.6) & (df_long['value']>0.35)]
df_long_se2

,panoid,lat,lon,year,month,img_path,angle,value
2,--3w2NTa6dWsDSlB7lQqiA,-1.304348,36.742095,2018.0,1.0,-/-/,0,0.484140
26,--gztpPxVlgQtgUzGsxh7w,-1.219777,36.899377,2018.0,2.0,-/-/,0,0.411131
67,-17BE49M9f-tbbDIFUgjiQ,-1.222289,36.923940,2021.0,9.0,-/1/,0,0.382412
74,-1GWYdUrPFiTs4FqbW_Ipw,-1.285079,36.770267,2017.0,12.0,-/1/,0,0.477549
85,-1YaBE-oCIwSInXk4l-cKw,-1.260926,36.792141,2017.0,12.0,-/1/,0,0.481371
...,...,...,...,...,...,...,...,...
505525,zw9gS4G-JIkCsUKwHCNcAA,-1.380512,36.940275,2021.0,8.0,Z/w/,270,0.417355
505555,zxO00HPoZdCjk_wbdm7PPg,-1.319706,36.903292,2021.0,7.0,Z/x/,270,0.489399
505589,zy9VjGfr4TtogrhLlnyrOg,-1.283836,36.694678,2018.0,3.0,Z/y/,270,0.365252
505591,zyK7v2O9dMQdpq9Bh_Uteg,-1.200157,36.760387,2022.0,2.0,Z/y/,270,0.401542
505616,zz3X3pt3_ZXcMc77D0ocpg,-1.202533,36.898650,2018.0,2.0,Z/Z/,270,0.377378

# copy image

In [33]:
import os
import shutil
import pandas as pd

In [30]:
df_long_se['img_name'] = df_long_se['panoid'] + '_' + df_long_se['ang'].astype(str)
df_long_se

/var/folders/2_/nk9j6sb901n_fk5dz_9vtqj80000gn/T/ipykernel_77728/4265509946.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_long_se['img_name'] = df_long_se['panoid'] + '_' + df_long_se['ang'].astype(str)

,panoid,lat,lon,year,month,img_path,Yo,ang,LLM,img_name
98,-2QdlzZCwJEM1tO0AU9b4g,-1.274346,36.884966,2018.0,2.0,-/2/,0.374915,0,1,-2QdlzZCwJEM1tO0AU9b4g_0
154,-4Rci70cakpla7qHAQ6RtA,-1.310624,36.791561,2021.0,7.0,-/4/,0.327264,0,1,-4Rci70cakpla7qHAQ6RtA_0
206,-6SOXQcTZXuAv52dmWWkSw,-1.325439,36.835939,2021.0,7.0,-/6/,0.456282,0,1,-6SOXQcTZXuAv52dmWWkSw_0
509,-HCPm9uGbTfUuFYP7S7WqA,-1.210993,36.961580,2021.0,9.0,-/H/,0.259395,0,1,-HCPm9uGbTfUuFYP7S7WqA_0
511,-HEB_u_ZPk9mELxyAcCGNw,-1.286155,36.895681,2021.0,8.0,-/H/,0.488870,0,1,-HEB_u_ZPk9mELxyAcCGNw_0
...,...,...,...,...,...,...,...,...,...,...
451795,z64v4mjNGxNei83XFzekuw,-1.301790,36.901959,2021.0,7.0,Z/6/,0.490415,270,1,z64v4mjNGxNei83XFzekuw_270
452304,zNdPGBdJVv2ErYUICdUhVg,-1.263239,36.863245,2018.0,2.0,Z/N/,0.600943,270,1,zNdPGBdJVv2ErYUICdUhVg_270
452483,zUAlQ-7npu34twtIjjFt6w,-1.271890,36.852577,2018.0,1.0,Z/U/,0.385207,270,1,zUAlQ-7npu34twtIjjFt6w_270
452785,zeKYfi6QWcUgVmgum6Cf6A,-1.268957,36.849096,2018.0,1.0,Z/e/,0.457194,270,1,zeKYfi6QWcUgVmgum6Cf6A_270
453200,zuKWK8EZ0QpiT5FfcMaxpQ,-1.255446,36.883093,2018.0,2.0,Z/U/,0.323091,270,1,zuKWK8EZ0QpiT5FfcMaxpQ_270

In [31]:
# Set your base path for the source images
basepath = '/Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/'  # Replace with your base path

# Set your destination path
destination_path = '/Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/PreScreen/'  # Replace with your destination path

# Set to keep track of copied images
copied_images = set()

In [70]:
df_long_se2 = df_long_se2.iloc[0:5000]
df_long_se2

,panoid,lat,lon,year,month,img_path,angle,value,img_name
2,--3w2NTa6dWsDSlB7lQqiA,-1.304348,36.742095,2018.0,1.0,-/-/,0,0.484140,--3w2NTa6dWsDSlB7lQqiA_0
26,--gztpPxVlgQtgUzGsxh7w,-1.219777,36.899377,2018.0,2.0,-/-/,0,0.411131,--gztpPxVlgQtgUzGsxh7w_0
67,-17BE49M9f-tbbDIFUgjiQ,-1.222289,36.923940,2021.0,9.0,-/1/,0,0.382412,-17BE49M9f-tbbDIFUgjiQ_0
74,-1GWYdUrPFiTs4FqbW_Ipw,-1.285079,36.770267,2017.0,12.0,-/1/,0,0.477549,-1GWYdUrPFiTs4FqbW_Ipw_0
85,-1YaBE-oCIwSInXk4l-cKw,-1.260926,36.792141,2017.0,12.0,-/1/,0,0.481371,-1YaBE-oCIwSInXk4l-cKw_0
...,...,...,...,...,...,...,...,...,...
90947,hypJTFYhDK4glw_JnYFa5g,-1.325039,36.881184,2018.0,4.0,H/y/,0,0.576613,hypJTFYhDK4glw_JnYFa5g_0
90952,hytgCC1rfg9XxDm8h6fvgg,-1.468403,36.953472,2022.0,3.0,H/y/,0,0.358721,hytgCC1rfg9XxDm8h6fvgg_0
90962,hzEkH1ZS4jQSAjfasvspCQ,-1.233453,36.930619,2018.0,2.0,H/Z/,0,0.456062,hzEkH1ZS4jQSAjfasvspCQ_0
90964,hzQGn39gO-X1SQAVYAcrow,-1.236475,36.689672,2021.0,8.0,H/Z/,0,0.526618,hzQGn39gO-X1SQAVYAcrow_0
90973,hze38NgqlMSBBaYpGgdT7g,-1.319171,36.897080,2021.0,10.0,H/Z/,0,0.404165,hze38NgqlMSBBaYpGgdT7g_0

In [34]:
# Iterate over the DataFrame rows
for index, row in df_long_se.iterrows():
    # Construct the source file path
    img_folder = row['img_path']  # This should be something like 'Q/g/'
    modified_img_name = row['img_name'] + '.jpg'  # Assuming the file extension is .jpg
    source_path = os.path.join(basepath, img_folder, modified_img_name)

    # Construct the destination file path
    dest_file_path = os.path.join(destination_path, modified_img_name)

    # Check if the image has already been copied
    if modified_img_name not in copied_images:
        # Copy the file
        if os.path.exists(source_path):
            shutil.copy2(source_path, dest_file_path)
            copied_images.add(modified_img_name)
        else:
            print(f"File not found: {source_path}")
    else:
        print(f"Already copied: {modified_img_name}")