The data has duplicates.   
original 126,414, but actual 113,341  
ORIGINAL 505656, but actual 453,364

In [1]:
import pandas as pd

In [2]:
Base = ''
Date = ''

In [5]:
# incomplete column name
column_names = ["pk", "id", "panoid", 'lat', 'lon', 'year', 'month', 'marker', 
                'Yo_0', 'Yo_90','Yo_180', 'Yo_270', 'LLM_0', 'LLM_90', 'LLM_180', 'LLM_270']
df_GSVI = pd.read_csv('/Users/wenlanzhang/PycharmProjects/SVI_Waste/Data/Output/GSVI/0122/output_LLM_20240122.csv',
                     header=None, skiprows=1, names=column_names)
unique_df_GSVI = df_GSVI.drop_duplicates(subset='panoid', keep='first')
unique_df_GSVI.drop(columns=['pk', 'id', 'marker'], inplace=True)
df_GSVI_sorted = unique_df_GSVI.sort_values(by='panoid')
df_GSVI_sorted = df_GSVI_sorted.reset_index()
df_GSVI_sorted

/var/folders/2_/nk9j6sb901n_fk5dz_9vtqj80000gn/T/ipykernel_50936/3666778117.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  unique_df_GSVI.drop(columns=['pk', 'id', 'marker'], inplace=True)

,index,panoid,lat,lon,year,month,Yo_0,Yo_90,Yo_180,Yo_270,LLM_0,LLM_90,LLM_180,LLM_270
0,16185,---kW5kLNFT2eKu77K0BSg,-1.337135,36.735751,2021.0,7.0,0.00000,0.0,0.0,0.0,0,0,0,0
1,28639,--3w2NTa6dWsDSlB7lQqiA,-1.304348,36.742095,2018.0,1.0,0.48414,0.0,0.0,0.0,0,0,0,0
2,28541,--5kqrbr7DiSKTlMm6mmZw,-1.279489,36.716701,2018.0,2.0,0.00000,0.0,0.0,0.0,0,0,0,0
3,93757,--6rir7WBjJoKcL5UgHzFw,-1.284360,36.972830,2018.0,2.0,0.00000,0.0,0.0,0.0,0,0,0,0
4,73927,--6yC0DbJTF8nxE2iXrbvQ,-1.490452,36.958099,2022.0,3.0,0.00000,0.0,0.0,0.0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113336,43673,zzu_OfR5p0sFK6uT6rTL4w,-1.252012,37.001303,2018.0,2.0,0.00000,0.0,0.0,0.0,0,0,0,0
113337,98733,zzvWdmTO_4oxT63l1GeS7w,-1.300941,36.811408,2018.0,3.0,0.00000,0.0,0.0,0.0,0,0,0,0
113338,5218,zzxSjzuQ7B44-cL2EPhyMg,-1.268607,36.845904,2021.0,9.0,0.00000,0.0,0.0,0.0,0,0,0,0
113339,37994,zzz5Wt_DGV8LAzRSfKZWiQ,-1.287985,37.044124,2021.0,10.0,0.00000,0.0,0.0,0.0,0,0,0,0
113340,100451,zzzaSItdTD9Tirtzu6aDnA,-1.274018,37.035957,2021.0,10.0,0.00000,0.0,0.0,0.0,0,0,0,0

In [6]:
df_img_path = pd.read_csv('/Users/wenlanzhang/PycharmProjects/SVI_Waste/Data/Output/GSVI/img_path.csv')
# df_img_path.drop(columns=['ang_0', 'ang_90', 'ang_180', 'ang_270'], inplace=True)
# df_img_path_sort = df_img_path.sort_values(by='panoid')
# df_img_path_sort = df_img_path_sort.reset_index()
# df_img_path_sort
df_img_path

                        panoid       lat        lon    year  month img_path
0       ---kW5kLNFT2eKu77K0BSg -1.337135  36.735751  2021.0    7.0     -/-/
1       --3w2NTa6dWsDSlB7lQqiA -1.304348  36.742095  2018.0    1.0     -/-/
2       --5kqrbr7DiSKTlMm6mmZw -1.279489  36.716701  2018.0    2.0     -/-/
3       --6rir7WBjJoKcL5UgHzFw -1.284360  36.972830  2018.0    2.0     -/-/
4       --6yC0DbJTF8nxE2iXrbvQ -1.490452  36.958099  2022.0    3.0     -/-/
...                        ...       ...        ...     ...    ...      ...
113336  zzu_OfR5p0sFK6uT6rTL4w -1.252012  37.001303  2018.0    2.0     Z/Z/
113337  zzvWdmTO_4oxT63l1GeS7w -1.300941  36.811408  2018.0    3.0     Z/Z/
113338  zzxSjzuQ7B44-cL2EPhyMg -1.268607  36.845904  2021.0    9.0     Z/Z/
113339  zzz5Wt_DGV8LAzRSfKZWiQ -1.287985  37.044124  2021.0   10.0     Z/Z/
113340  zzzaSItdTD9Tirtzu6aDnA -1.274018  37.035957  2021.0   10.0     Z/Z/

[113341 rows x 6 columns]

In [7]:
df_GSVI_sorted['img_path'] = df_img_path['img_path']

df_GSVI_sorted

,index,panoid,lat,lon,year,month,Yo_0,Yo_90,Yo_180,Yo_270,LLM_0,LLM_90,LLM_180,LLM_270,img_path
0,16185,---kW5kLNFT2eKu77K0BSg,-1.337135,36.735751,2021.0,7.0,0.00000,0.0,0.0,0.0,0,0,0,0,-/-/
1,28639,--3w2NTa6dWsDSlB7lQqiA,-1.304348,36.742095,2018.0,1.0,0.48414,0.0,0.0,0.0,0,0,0,0,-/-/
2,28541,--5kqrbr7DiSKTlMm6mmZw,-1.279489,36.716701,2018.0,2.0,0.00000,0.0,0.0,0.0,0,0,0,0,-/-/
3,93757,--6rir7WBjJoKcL5UgHzFw,-1.284360,36.972830,2018.0,2.0,0.00000,0.0,0.0,0.0,0,0,0,0,-/-/
4,73927,--6yC0DbJTF8nxE2iXrbvQ,-1.490452,36.958099,2022.0,3.0,0.00000,0.0,0.0,0.0,0,0,0,0,-/-/
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113336,43673,zzu_OfR5p0sFK6uT6rTL4w,-1.252012,37.001303,2018.0,2.0,0.00000,0.0,0.0,0.0,0,0,0,0,Z/Z/
113337,98733,zzvWdmTO_4oxT63l1GeS7w,-1.300941,36.811408,2018.0,3.0,0.00000,0.0,0.0,0.0,0,0,0,0,Z/Z/
113338,5218,zzxSjzuQ7B44-cL2EPhyMg,-1.268607,36.845904,2021.0,9.0,0.00000,0.0,0.0,0.0,0,0,0,0,Z/Z/
113339,37994,zzz5Wt_DGV8LAzRSfKZWiQ,-1.287985,37.044124,2021.0,10.0,0.00000,0.0,0.0,0.0,0,0,0,0,Z/Z/
113340,100451,zzzaSItdTD9Tirtzu6aDnA,-1.274018,37.035957,2021.0,10.0,0.00000,0.0,0.0,0.0,0,0,0,0,Z/Z/

In [28]:
# Yolo8 Only
# Reshape the DataFrame from wide to long format
df_long = pd.melt(df_GSVI_sorted, id_vars=['index', 'panoid', 'lat', 'lon', 'year', 'month', 'img_path'],
                   var_name='angle', value_name='value')

# Extract the angle values from the column names
df_long['angle'] = df_long['angle'].str.replace('ang_', '').astype(int)

# Print the resulting long-format DataFrame
df_long

,index,panoid,lat,lon,year,month,img_path,angle,value
0,16186,---kW5kLNFT2eKu77K0BSg,-1.337135,36.735751,2021.0,7.0,-/-/,0,0.00000
1,16185,---kW5kLNFT2eKu77K0BSg,-1.337135,36.735751,2021.0,7.0,-/-/,0,0.00000
2,28639,--3w2NTa6dWsDSlB7lQqiA,-1.304348,36.742095,2018.0,1.0,-/-/,0,0.48414
3,28541,--5kqrbr7DiSKTlMm6mmZw,-1.279489,36.716701,2018.0,2.0,-/-/,0,0.00000
4,93757,--6rir7WBjJoKcL5UgHzFw,-1.284360,36.972830,2018.0,2.0,-/-/,0,0.00000
...,...,...,...,...,...,...,...,...,...
505651,107337,zzvWdmTO_4oxT63l1GeS7w,-1.300941,36.811408,2018.0,3.0,Z/Z/,270,0.00000
505652,98735,zzvWdmTO_4oxT63l1GeS7w,-1.300941,36.811408,2018.0,3.0,Z/Z/,270,0.00000
505653,5218,zzxSjzuQ7B44-cL2EPhyMg,-1.268607,36.845904,2021.0,9.0,Z/Z/,270,0.00000
505654,37994,zzz5Wt_DGV8LAzRSfKZWiQ,-1.287985,37.044124,2021.0,10.0,Z/Z/,270,0.00000
505655,100451,zzzaSItdTD9Tirtzu6aDnA,-1.274018,37.035957,2021.0,10.0,Z/Z/,270,0.00000

In [8]:
# Yolov8 and LLM 

# Step 1: Melt for Yo columns
yo_long = pd.melt(df_GSVI_sorted, id_vars=['index', 'panoid', 'lat', 'lon', 'year', 'month', 'img_path'],
                  value_vars=['Yo_0', 'Yo_90', 'Yo_180', 'Yo_270'],
                  var_name='yo_angle', value_name='Yo')

# Extract angle for Yo
yo_long['ang'] = yo_long['yo_angle'].str.extract('(\d+)$').astype(int)
yo_long.drop('yo_angle', axis=1, inplace=True)

# Step 2: Melt for LLM columns
llm_long = pd.melt(df_GSVI_sorted, id_vars=['index', 'panoid', 'lat', 'lon', 'year', 'month', 'img_path'],
                   value_vars=['LLM_0', 'LLM_90', 'LLM_180', 'LLM_270'],
                   var_name='llm_angle', value_name='LLM')

# Extract angle for LLM
llm_long['ang'] = llm_long['llm_angle'].str.extract('(\d+)$').astype(int)
llm_long.drop('llm_angle', axis=1, inplace=True)

# Step 3: Merge the Yo and LLM long DataFrames
df_long = pd.merge(yo_long, llm_long, on=['index', 'panoid', 'lat', 'lon', 'year', 'month', 'img_path', 'ang'], how='inner')

# The resulting df_long DataFrame now has separate Yo and LLM columns, with a common 'ang' column for the angle
df_long

,index,panoid,lat,lon,year,month,img_path,Yo,ang,LLM
0,16185,---kW5kLNFT2eKu77K0BSg,-1.337135,36.735751,2021.0,7.0,-/-/,0.00000,0,0
1,28639,--3w2NTa6dWsDSlB7lQqiA,-1.304348,36.742095,2018.0,1.0,-/-/,0.48414,0,0
2,28541,--5kqrbr7DiSKTlMm6mmZw,-1.279489,36.716701,2018.0,2.0,-/-/,0.00000,0,0
3,93757,--6rir7WBjJoKcL5UgHzFw,-1.284360,36.972830,2018.0,2.0,-/-/,0.00000,0,0
4,73927,--6yC0DbJTF8nxE2iXrbvQ,-1.490452,36.958099,2022.0,3.0,-/-/,0.00000,0,0
...,...,...,...,...,...,...,...,...,...,...
453359,43673,zzu_OfR5p0sFK6uT6rTL4w,-1.252012,37.001303,2018.0,2.0,Z/Z/,0.00000,270,0
453360,98733,zzvWdmTO_4oxT63l1GeS7w,-1.300941,36.811408,2018.0,3.0,Z/Z/,0.00000,270,0
453361,5218,zzxSjzuQ7B44-cL2EPhyMg,-1.268607,36.845904,2021.0,9.0,Z/Z/,0.00000,270,0
453362,37994,zzz5Wt_DGV8LAzRSfKZWiQ,-1.287985,37.044124,2021.0,10.0,Z/Z/,0.00000,270,0
453363,100451,zzzaSItdTD9Tirtzu6aDnA,-1.274018,37.035957,2021.0,10.0,Z/Z/,0.00000,270,0

In [9]:
df_long.drop(columns=['index'], inplace=True)

# df_long = df_long.drop_duplicates() # duplicates should have been considered at the beginning.
df_long

,panoid,lat,lon,year,month,img_path,Yo,ang,LLM
0,---kW5kLNFT2eKu77K0BSg,-1.337135,36.735751,2021.0,7.0,-/-/,0.00000,0,0
1,--3w2NTa6dWsDSlB7lQqiA,-1.304348,36.742095,2018.0,1.0,-/-/,0.48414,0,0
2,--5kqrbr7DiSKTlMm6mmZw,-1.279489,36.716701,2018.0,2.0,-/-/,0.00000,0,0
3,--6rir7WBjJoKcL5UgHzFw,-1.284360,36.972830,2018.0,2.0,-/-/,0.00000,0,0
4,--6yC0DbJTF8nxE2iXrbvQ,-1.490452,36.958099,2022.0,3.0,-/-/,0.00000,0,0
...,...,...,...,...,...,...,...,...,...
453359,zzu_OfR5p0sFK6uT6rTL4w,-1.252012,37.001303,2018.0,2.0,Z/Z/,0.00000,270,0
453360,zzvWdmTO_4oxT63l1GeS7w,-1.300941,36.811408,2018.0,3.0,Z/Z/,0.00000,270,0
453361,zzxSjzuQ7B44-cL2EPhyMg,-1.268607,36.845904,2021.0,9.0,Z/Z/,0.00000,270,0
453362,zzz5Wt_DGV8LAzRSfKZWiQ,-1.287985,37.044124,2021.0,10.0,Z/Z/,0.00000,270,0
453363,zzzaSItdTD9Tirtzu6aDnA,-1.274018,37.035957,2021.0,10.0,Z/Z/,0.00000,270,0

In [24]:
df_long.to_csv('/Users/wenlanzhang/PycharmProjects/SVI_Waste/Data/Output/GSVI/0122/GSVI_long_20240204.csv', index=False)

# select rows

In [33]:
df_long = pd.read_csv('/Users/wenlanzhang/PycharmProjects/SVI_Waste/Data/Output/GSVI/0122/GSVI_long_20240204.csv')
df_long

,panoid,lat,lon,year,month,img_path,Yo,ang,LLM
0,---kW5kLNFT2eKu77K0BSg,-1.337135,36.735751,2021.0,7.0,-/-/,0.00000,0,0
1,--3w2NTa6dWsDSlB7lQqiA,-1.304348,36.742095,2018.0,1.0,-/-/,0.48414,0,0
2,--5kqrbr7DiSKTlMm6mmZw,-1.279489,36.716701,2018.0,2.0,-/-/,0.00000,0,0
3,--6rir7WBjJoKcL5UgHzFw,-1.284360,36.972830,2018.0,2.0,-/-/,0.00000,0,0
4,--6yC0DbJTF8nxE2iXrbvQ,-1.490452,36.958099,2022.0,3.0,-/-/,0.00000,0,0
...,...,...,...,...,...,...,...,...,...
453359,zzu_OfR5p0sFK6uT6rTL4w,-1.252012,37.001303,2018.0,2.0,Z/Z/,0.00000,270,0
453360,zzvWdmTO_4oxT63l1GeS7w,-1.300941,36.811408,2018.0,3.0,Z/Z/,0.00000,270,0
453361,zzxSjzuQ7B44-cL2EPhyMg,-1.268607,36.845904,2021.0,9.0,Z/Z/,0.00000,270,0
453362,zzz5Wt_DGV8LAzRSfKZWiQ,-1.287985,37.044124,2021.0,10.0,Z/Z/,0.00000,270,0
453363,zzzaSItdTD9Tirtzu6aDnA,-1.274018,37.035957,2021.0,10.0,Z/Z/,0.00000,270,0

## Old one

In [11]:
# df_long_se = df_long[df_long['value']>0]
df_long_se = df_long[df_long['LLM']==1]

df_long_se

,panoid,lat,lon,year,month,img_path,Yo,ang,LLM
98,-2QdlzZCwJEM1tO0AU9b4g,-1.274346,36.884966,2018.0,2.0,-/2/,0.374915,0,1
154,-4Rci70cakpla7qHAQ6RtA,-1.310624,36.791561,2021.0,7.0,-/4/,0.327264,0,1
206,-6SOXQcTZXuAv52dmWWkSw,-1.325439,36.835939,2021.0,7.0,-/6/,0.456282,0,1
509,-HCPm9uGbTfUuFYP7S7WqA,-1.210993,36.961580,2021.0,9.0,-/H/,0.259395,0,1
511,-HEB_u_ZPk9mELxyAcCGNw,-1.286155,36.895681,2021.0,8.0,-/H/,0.488870,0,1
...,...,...,...,...,...,...,...,...,...
451795,z64v4mjNGxNei83XFzekuw,-1.301790,36.901959,2021.0,7.0,Z/6/,0.490415,270,1
452304,zNdPGBdJVv2ErYUICdUhVg,-1.263239,36.863245,2018.0,2.0,Z/N/,0.600943,270,1
452483,zUAlQ-7npu34twtIjjFt6w,-1.271890,36.852577,2018.0,1.0,Z/U/,0.385207,270,1
452785,zeKYfi6QWcUgVmgum6Cf6A,-1.268957,36.849096,2018.0,1.0,Z/e/,0.457194,270,1
453200,zuKWK8EZ0QpiT5FfcMaxpQ,-1.255446,36.883093,2018.0,2.0,Z/U/,0.323091,270,1

In [35]:
df_long_se.to_csv('/Users/wenlanzhang/PycharmProjects/SVI_Waste/Data/Output/GSVI/0122/GSVI_True_0204.csv', index=False)

In [38]:
df_long_se = df_long[df_long['Yo']>0.5]
df_long_se

,panoid,lat,lon,year,month,img_path,Yo,ang,LLM
58,-0wIGghq_wnmlSxQjvfs6Q,-1.260868,36.734328,2018.0,2.0,-/0/,0.634289,0,0
139,-3l0SHoc2SjGiBF8t3kaaQ,-1.263649,36.687267,2021.0,8.0,-/3/,0.712311,0,0
178,-5HilXXyL-qKt1wv8n1zRg,-1.307061,36.809633,2021.0,7.0,-/5/,0.586642,0,0
270,-8hBsb_UsQnDtjS1V6mYvA,-1.281427,36.899802,2018.0,1.0,-/8/,0.517315,0,0
285,-997EmNYPzvePfvUwFaWEw,-1.277183,36.912439,2018.0,1.0,-/9/,0.514777,0,0
...,...,...,...,...,...,...,...,...,...
453161,zt0Www11kQ5nkKitbvpnWg,-1.370930,36.918294,2021.0,10.0,Z/t/,0.588108,270,0
453188,zu-IaBH6zNmk4SphLZm8fw,-1.264423,36.852286,2018.0,2.0,Z/U/,0.542113,270,0
453207,zud6k2qrWCeHdYVmCA0kyw,-1.192578,36.948039,2021.0,9.0,Z/U/,0.536183,270,0
453217,zuzcDSjoJg3Le-sA5WXKLQ,-1.244422,36.681994,2021.0,10.0,Z/U/,0.725639,270,0
453245,zw8Voo5-Q0AApCg_KgThsA,-1.281923,36.946519,2021.0,7.0,Z/w/,0.502096,270,0

In [43]:
df_long_se2.to_csv('/Users/wenlanzhang/PycharmProjects/SVI_Waste/Data/Output/GSVI/0119/GSVI_6_0119.csv', index=False)

In [19]:
df_long_se2 = df_long[(df_long['Yo']<0.6) & (df_long['Yo']>0.35)]
df_long_se2

,panoid,lat,lon,year,month,img_path,Yo,ang,LLM
1,--3w2NTa6dWsDSlB7lQqiA,-1.304348,36.742095,2018.0,1.0,-/-/,0.484140,0,0
23,--gztpPxVlgQtgUzGsxh7w,-1.219777,36.899377,2018.0,2.0,-/-/,0.411131,0,0
61,-17BE49M9f-tbbDIFUgjiQ,-1.222289,36.923940,2021.0,9.0,-/1/,0.382412,0,0
68,-1GWYdUrPFiTs4FqbW_Ipw,-1.285079,36.770267,2017.0,12.0,-/1/,0.477549,0,0
78,-1YaBE-oCIwSInXk4l-cKw,-1.260926,36.792141,2017.0,12.0,-/1/,0.481371,0,0
...,...,...,...,...,...,...,...,...,...
453248,zw9gS4G-JIkCsUKwHCNcAA,-1.380512,36.940275,2021.0,8.0,Z/w/,0.417355,270,0
453277,zxO00HPoZdCjk_wbdm7PPg,-1.319706,36.903292,2021.0,7.0,Z/x/,0.489399,270,0
453305,zy9VjGfr4TtogrhLlnyrOg,-1.283836,36.694678,2018.0,3.0,Z/y/,0.365252,270,0
453307,zyK7v2O9dMQdpq9Bh_Uteg,-1.200157,36.760387,2022.0,2.0,Z/y/,0.401542,270,0
453330,zz3X3pt3_ZXcMc77D0ocpg,-1.202533,36.898650,2018.0,2.0,Z/Z/,0.377378,270,0

In [6]:
df_long_se = df_long[(df_long['Yo'] > 0.6) & (df_long['LLM']==1)]
                 
df_long_se

,panoid,lat,lon,year,month,img_path,Yo,ang,LLM
5846,2FvCvEji2ye6Yjv04EusTg,-1.208751,36.872991,2018.0,2.0,2/f/,0.693921,0,1
7662,3HOwQFKmy1Ll4h3mq5n4aA,-1.370534,36.937574,2021.0,8.0,3/H/,0.602226,0,1
12715,65i3h8IqhWzNh00zrPSq9w,-1.265181,36.917180,2021.0,8.0,6/5/,0.680557,0,1
14091,6qfAoaAnLsUoUTcYOo8c_Q,-1.275638,36.886093,2018.0,2.0,6/Q/,0.726954,0,1
16571,8E6xaiQ70NxLJNh4lDS3IQ,-1.283245,36.950313,2021.0,8.0,8/e/,0.662972,0,1
...,...,...,...,...,...,...,...,...,...
445699,vd1nYYLTDh_QPTZI0ZcbqQ,-1.237329,36.763191,2021.0,7.0,v/d/,0.630944,270,1
445761,vfCIOxBBuIbqL7oEu5ZNGA,-1.305996,36.832632,2018.0,1.0,v/f/,0.699731,270,1
446318,w-AOJoEBYiAgM7vkcg5CpQ,-1.329398,36.857748,2021.0,8.0,w/-/,0.601536,270,1
446860,wHv6VZHowJfFlhDmK1tKWA,-1.201182,36.888541,2018.0,2.0,w/H/,0.631986,270,1
452304,zNdPGBdJVv2ErYUICdUhVg,-1.263239,36.863245,2018.0,2.0,Z/N/,0.600943,270,1

In [7]:
df_long_se.to_csv('/Users/wenlanzhang/PycharmProjects/SVI_Waste/Data/Output/GSVI/0122/GSVI_Test_0311.csv', index=False)

## Select non empty ['conf'] list
Applicable to output after M 0311

In [16]:
Self_output = pd.read_csv('/Users/wenlanzhang/PycharmProjects/SVI_Waste/Data/Output/Self/0314/self_M0311.csv')
Self_output = Self_output.drop(columns=['Unnamed: 0.1', 'Unnamed: 0'])
Self_output

,panoid,lat,lon,year,month,img_path,angle,type,img_name,conf,bbox
0,IMG_0799,-1.366022,36.766883,2023,2,Used/,NaN,Self,IMG_0799,[],[]
1,IMG_6303,-1.251897,36.825386,2023,2,Used/,NaN,Self,IMG_6303,"[0.298915296792984, 0.28837060928344727]","[[1282.42822265625, 1148.2774658203125, 2331.3..."
2,IMG_0772,-1.346758,36.765344,2023,2,Used/,NaN,Self,IMG_0772,[],[]
3,IMG_8448,-1.279731,37.049336,2023,2,Used/,NaN,Self,IMG_8448,[],[]
4,IMG_6465,-1.306939,36.783822,2023,2,Used/,NaN,Self,IMG_6465,[],[]
...,...,...,...,...,...,...,...,...,...,...,...
2323,IMG_20230212_081016,-1.307547,36.734650,2023,2,Used/,NaN,Self,IMG_20230212_081016,[],[]
2324,IMG_20230212_081003,-1.307619,36.734650,2023,2,Used/,NaN,Self,IMG_20230212_081003,[],[]
2325,IMG_20230212_081017,-1.307547,36.734650,2023,2,Used/,NaN,Self,IMG_20230212_081017,"[0.5341472029685974, 0.3198191821575165]","[[3174.6650390625, 0.0, 3964.56640625, 1101.47..."
2326,IMG_20230212_082052,-1.256017,36.662819,2023,2,Used/,NaN,Self,IMG_20230212_082052,[],[]
2327,IMG_20230212_080902,-1.305370,36.743504,2023,2,Used/,NaN,Self,IMG_20230212_080902,[],[]

In [17]:
# Check Error in the df
Error_df = Self_output.loc[Self_output['conf'] == '-1']
Error_df

# if run below cell first, then it will not appear

,panoid,lat,lon,year,month,img_path,angle,type,img_name,conf,bbox
2138,IMG_0903,-1.293522,36.793267,2023,2,Used/,NaN,Self,IMG_0903,-1,-1

In [18]:
import ast

Self_output['conf'] = Self_output['conf'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)

# Filter rows where the list is not empty
filtered_Self_output = Self_output[Self_output['conf'].apply(lambda x: len(x) > 0 if isinstance(x, list) else False)]

filtered_Self_output

,panoid,lat,lon,year,month,img_path,angle,type,img_name,conf,bbox
1,IMG_6303,-1.251897,36.825386,2023,2,Used/,NaN,Self,IMG_6303,"[0.298915296792984, 0.28837060928344727]","[[1282.42822265625, 1148.2774658203125, 2331.3..."
5,IMG_6471,-1.306494,36.783508,2023,2,Used/,NaN,Self,IMG_6471,[0.37936580181121826],"[[2.3037643432617188, 1978.424072265625, 914.4..."
12,IMG_8474,-1.279736,37.048789,2023,2,Used/,NaN,Self,IMG_8474,[0.6222440004348755],"[[115.94763946533203, 2437.7333984375, 3058.74..."
14,IMG_8460,-1.281864,37.060086,2023,2,Used/,NaN,Self,IMG_8460,[0.38784974813461304],"[[260.67938232421875, 2468.101318359375, 813.5..."
23,IMG_7237,-1.278725,36.803636,2023,2,Used/,NaN,Self,IMG_7237,"[0.5394059419631958, 0.47663816809654236]","[[0.0, 107.2811050415039, 1002.3628540039062, ..."
...,...,...,...,...,...,...,...,...,...,...,...
2307,IMG_20230212_081217,-1.305153,36.715748,2023,2,Used/,NaN,Self,IMG_20230212_081217,[0.5293723344802856],"[[2041.890380859375, 623.721923828125, 3955.17..."
2315,IMG_20230212_080929,-1.306133,36.739262,2023,2,Used/,NaN,Self,IMG_20230212_080929,[0.3957529664039612],"[[1071.80029296875, 611.7474975585938, 2432.35..."
2319,IMG_20230212_080917,-1.306133,36.739262,2023,2,Used/,NaN,Self,IMG_20230212_080917,[0.3308432102203369],"[[2943.7041015625, 845.1068725585938, 3486.244..."
2320,IMG_20230212_081214,-1.305153,36.715748,2023,2,Used/,NaN,Self,IMG_20230212_081214,[0.668906569480896],"[[1473.8294677734375, 1136.3701171875, 2583.34..."
2325,IMG_20230212_081017,-1.307547,36.734650,2023,2,Used/,NaN,Self,IMG_20230212_081017,"[0.5341472029685974, 0.3198191821575165]","[[3174.6650390625, 0.0, 3964.56640625, 1101.47..."

# copy image

In [29]:
import os
import shutil
import pandas as pd

In [39]:
# 应该挪到上面去？ 并且删掉因为已经准备好了
df_long_se['img_name'] = df_long_se['panoid'] + '_' + df_long_se['ang'].astype(str)
df_long_se

/var/folders/2_/nk9j6sb901n_fk5dz_9vtqj80000gn/T/ipykernel_3009/2447535515.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_long_se['img_name'] = df_long_se['panoid'] + '_' + df_long_se['ang'].astype(str)

,panoid,lat,lon,year,month,img_path,Yo,ang,LLM,img_name
58,-0wIGghq_wnmlSxQjvfs6Q,-1.260868,36.734328,2018.0,2.0,-/0/,0.634289,0,0,-0wIGghq_wnmlSxQjvfs6Q_0
139,-3l0SHoc2SjGiBF8t3kaaQ,-1.263649,36.687267,2021.0,8.0,-/3/,0.712311,0,0,-3l0SHoc2SjGiBF8t3kaaQ_0
178,-5HilXXyL-qKt1wv8n1zRg,-1.307061,36.809633,2021.0,7.0,-/5/,0.586642,0,0,-5HilXXyL-qKt1wv8n1zRg_0
270,-8hBsb_UsQnDtjS1V6mYvA,-1.281427,36.899802,2018.0,1.0,-/8/,0.517315,0,0,-8hBsb_UsQnDtjS1V6mYvA_0
285,-997EmNYPzvePfvUwFaWEw,-1.277183,36.912439,2018.0,1.0,-/9/,0.514777,0,0,-997EmNYPzvePfvUwFaWEw_0
...,...,...,...,...,...,...,...,...,...,...
453161,zt0Www11kQ5nkKitbvpnWg,-1.370930,36.918294,2021.0,10.0,Z/t/,0.588108,270,0,zt0Www11kQ5nkKitbvpnWg_270
453188,zu-IaBH6zNmk4SphLZm8fw,-1.264423,36.852286,2018.0,2.0,Z/U/,0.542113,270,0,zu-IaBH6zNmk4SphLZm8fw_270
453207,zud6k2qrWCeHdYVmCA0kyw,-1.192578,36.948039,2021.0,9.0,Z/U/,0.536183,270,0,zud6k2qrWCeHdYVmCA0kyw_270
453217,zuzcDSjoJg3Le-sA5WXKLQ,-1.244422,36.681994,2021.0,10.0,Z/U/,0.725639,270,0,zuzcDSjoJg3Le-sA5WXKLQ_270
453245,zw8Voo5-Q0AApCg_KgThsA,-1.281923,36.946519,2021.0,7.0,Z/w/,0.502096,270,0,zw8Voo5-Q0AApCg_KgThsA_270

In [41]:
# Set your base path for the source images
basepath = '/Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Maoran/img/' 

# Set your destination path
destination_path = '/Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/ad/' 

# Set to keep track of copied images
copied_images = set()

In [42]:
# df_move = df_long_se2.iloc[0:5000]
df_move = df_long_se
# df_move = filtered_Self_output
df_move

,panoid,lat,lon,year,month,img_path,Yo,ang,LLM,img_name
58,-0wIGghq_wnmlSxQjvfs6Q,-1.260868,36.734328,2018.0,2.0,-/0/,0.634289,0,0,-0wIGghq_wnmlSxQjvfs6Q_0
139,-3l0SHoc2SjGiBF8t3kaaQ,-1.263649,36.687267,2021.0,8.0,-/3/,0.712311,0,0,-3l0SHoc2SjGiBF8t3kaaQ_0
178,-5HilXXyL-qKt1wv8n1zRg,-1.307061,36.809633,2021.0,7.0,-/5/,0.586642,0,0,-5HilXXyL-qKt1wv8n1zRg_0
270,-8hBsb_UsQnDtjS1V6mYvA,-1.281427,36.899802,2018.0,1.0,-/8/,0.517315,0,0,-8hBsb_UsQnDtjS1V6mYvA_0
285,-997EmNYPzvePfvUwFaWEw,-1.277183,36.912439,2018.0,1.0,-/9/,0.514777,0,0,-997EmNYPzvePfvUwFaWEw_0
...,...,...,...,...,...,...,...,...,...,...
453161,zt0Www11kQ5nkKitbvpnWg,-1.370930,36.918294,2021.0,10.0,Z/t/,0.588108,270,0,zt0Www11kQ5nkKitbvpnWg_270
453188,zu-IaBH6zNmk4SphLZm8fw,-1.264423,36.852286,2018.0,2.0,Z/U/,0.542113,270,0,zu-IaBH6zNmk4SphLZm8fw_270
453207,zud6k2qrWCeHdYVmCA0kyw,-1.192578,36.948039,2021.0,9.0,Z/U/,0.536183,270,0,zud6k2qrWCeHdYVmCA0kyw_270
453217,zuzcDSjoJg3Le-sA5WXKLQ,-1.244422,36.681994,2021.0,10.0,Z/U/,0.725639,270,0,zuzcDSjoJg3Le-sA5WXKLQ_270
453245,zw8Voo5-Q0AApCg_KgThsA,-1.281923,36.946519,2021.0,7.0,Z/w/,0.502096,270,0,zw8Voo5-Q0AApCg_KgThsA_270

In [44]:
#  删删删删删删删删删删删删删删删删删删删删删删删删删删删删删删删
# 下面版本incorproate了extension

# Iterate over the DataFrame rows
for index, row in df_move.iterrows():
    # Construct the source file path
    img_folder = row['img_path']  # This should be something like 'Q/g/'
    modified_img_name = row['img_name'] + '.jpg'  # Assuming the file extension is .jpg
    source_path = os.path.join(basepath, img_folder, modified_img_name)

    # Construct the destination file path
    dest_file_path = os.path.join(destination_path, modified_img_name)

    # Check if the image has already been copied
    if modified_img_name not in copied_images:
        # Copy the file
        if os.path.exists(source_path):
            shutil.copy2(source_path, dest_file_path)
            copied_images.add(modified_img_name)
        else:
            print(f"File not found: {source_path}")
    else:
        print(f"Already copied: {modified_img_name}")

Already copied: -0wIGghq_wnmlSxQjvfs6Q_0.jpg
Already copied: -3l0SHoc2SjGiBF8t3kaaQ_0.jpg
Already copied: -5HilXXyL-qKt1wv8n1zRg_0.jpg
Already copied: -8hBsb_UsQnDtjS1V6mYvA_0.jpg
Already copied: -997EmNYPzvePfvUwFaWEw_0.jpg
Already copied: -B28FqYgw7ft1_iGNP-xzg_0.jpg
Already copied: -CQQqjzgoLawx3LN307U4g_0.jpg
Already copied: -HPeP6rd8-vM3Li8sSdvkA_0.jpg
Already copied: -IMlKszChg08pW8GMgiLQg_0.jpg
Already copied: -IWRLSUH5z4_XZNFVKof6g_0.jpg
Already copied: -Rusmn9hI2gV7UroHd80Cg_0.jpg
Already copied: -Tm9BB__cL87GjVbDos4mQ_0.jpg
Already copied: -WYuHXoRfzrraYWMscvLNw_0.jpg
Already copied: -_Zxs2WP-X8m7qj-REHpnQ_0.jpg
Already copied: -dE81PTqRvl-czwNVPc17w_0.jpg
Already copied: -dnEqpLrlgYAsG3FVFQ7Aw_0.jpg
Already copied: -gJRF24oKdAlQF_HCZp-Ww_0.jpg
Already copied: -gpavYadFqehhwXprGSR9g_0.jpg
Already copied: -hJxaBJdlGNQu2ID-I1Sng_0.jpg
Already copied: -i-eH0et7_OzpUTIVMXEVg_0.jpg
Already copied: -iUberVTsT9M1KW-T5JZAg_0.jpg
Already copied: -j91DihhMo7HVZsmP6uNWA_0.jpg
Already copied: -qGhfW3xdAZ6wvVBumBdgg_0.jpg
Already copied: -qU8YANg-YEdkD89sRfcTA_0.jpg
Already copied: -qWeZ9Tt6xWTzeGv0L1Z-A_0.jpg
Already copied: -x-2K6q7sNpZqLVEUHcr6Q_0.jpg
Already copied: -xxW4ylzG299vowxeKpvYQ_0.jpg
Already copied: 04uNACQIGwVFI7wl7MZVqQ_0.jpg
Already copied: 05GgGnPe4cos7dwwFNFztA_0.jpg
Already copied: 08nTynEuBPEKOWecC6ePgQ_0.jpg
Already copied: 09e0bWl6FL2iCqL1ymGmyg_0.jpg
Already copied: 0Cl1ty8xnBUhc66lj6NArQ_0.jpg
Already copied: 0DBezUvFKTl7daWl1GvOow_0.jpg
Already copied: 0DYpIajZfrM6dmTZYC7g4g_0.jpg
Already copied: 0Esn5VdDgrnwLq5QLT98Uw_0.jpg
Already copied: 0GoJFQmz_XOXY8VEftFPGg_0.jpg
Already copied: 0HI2Jr5jeLap42lkDOPOdg_0.jpg
Already copied: 0IYvopVjl848MSO5aonogQ_0.jpg
Already copied: 0NT6B4r_Q1d3pUZAGzOjlw_0.jpg
Already copied: 0Rdo1RqvAXXa7REMIMQehg_0.jpg
Already copied: 0ZGYi-iouyIO0ppJSSpAsQ_0.jpg
Already copied: 0ZtmcsPfg2TirRBP-BzmiA_0.jpg
Already copied: 0_dW7k9mzQx4cXTJV9U_Og_0.jpg
Already copied: 0l-EPufk1j_bloz7FEbBMQ_0.jpg
Already copied: 0lt_NEu3YlTCAJEK7TdU3A_0.jpg
Already copied: 0nHhj8kzfAMSL_W7DJd4Og_0.jpg
Already copied: 0oOMUqQzzas9h0sBVqnACw_0.jpg
Already copied: 0pcBfRcYxZzhRCReU9NocQ_0.jpg
Already copied: 0q03zTEQW0KjT2fEYXpGTA_0.jpg
Already copied: 0qVsBzHoLyC3wAJRCL9o-Q_0.jpg
Already copied: 0uJOq262cA-P1hhicTy4qQ_0.jpg
Already copied: 0uj3iwZL4xvtgUXbCgqTrA_0.jpg
Already copied: 0vx6RscL5WxBA9Csp9XOIw_0.jpg
Already copied: 0wdClD5m81WZMb4QuOdY6Q_0.jpg
Already copied: 0xHA7WbQVUC5KqZakwIj9Q_0.jpg
Already copied: 0z6z6wSCUA6KxtQbR2JSFg_0.jpg
Already copied: 11xXQ9TCvV8oNFMcLPoxng_0.jpg
Already copied: 13jpvmgwj1ozcN5LJsSnyQ_0.jpg
Already copied: 15_5OuoLGTQTWdRTAb6tZA_0.jpg
Already copied: 17SudvciJGXTU1PPXzB5Hw_0.jpg
Already copied: 19AwR73Jvr6AyfcP7ebY1w_0.jpg
Already copied: 1EIdg83IpchDoCM5hD2RrA_0.jpg
Already copied: 1G3gi3JBj0WQpMyNc5NNug_0.jpg
Already copied: 1H5dr8MxGHAGuFKpgHrSAA_0.jpg
Already copied: 1Kk83im3uw4IPQ8lM6ckTg_0.jpg
Already copied: 1L-wW4QNVdW0Naufj2Dp_Q_0.jpg
Already copied: 1LrgYHZkmNRAUvYeSHANwA_0.jpg
Already copied: 1P8wKN5QuiF5nNTd2nynFQ_0.jpg
Already copied: 1PA-1gbY2kJq7mp-TjF2bg_0.jpg
Already copied: 1RgBfjxbLz6ffLIqVZyhhg_0.jpg
Already copied: 1TH5ro9nAgWHi_QN6ausLQ_0.jpg
Already copied: 1U84muGD84hCS9AjwRBO4Q_0.jpg
Already copied: 1UlGKxBT4cLDMFB2Ge-VUg_0.jpg
Already copied: 1Zvo_3961hLXseSfzxowHg_0.jpg
Already copied: 1_reB3GHf5wzIRzkS9Uafg_0.jpg
Already copied: 1cuJ7rH2GwJNgsZYMXcqBQ_0.jpg
Already copied: 1kB862rPRviWi_xhIs9aJg_0.jpg
Already copied: 1l8GFvHKJ7xIIjzjkFFK0w_0.jpg
Already copied: 1mjT6U1te-GrtrKgxHMsBg_0.jpg
Already copied: 1peBYD7ZyY7iYLB6ORXuOQ_0.jpg
Already copied: 1qVggII2UdAz7eCAKsYiEA_0.jpg
Already copied: 1rVnrQKI3-HcStA5UWaLew_0.jpg
Already copied: 1sSfOwGf83ZHbL5Lf5vFhg_0.jpg
Already copied: 1s_6dgghD_zqcDuiCIz3Yg_0.jpg
Already copied: 1t-_bAZcLO1dj4GKlwYLjg_0.jpg
Already copied: 1tbZ_Yem9hqvCND8zkjoWA_0.jpg
Already copied: 1xVuBBUGeNYAnkfcVb1EOg_0.jpg
Already copied: 1yinqmMc-Y4MDN6MWeN18g_0.jpg
Already copied: 2-_dSTnQ-1Bdcz9BsRTEaA_0.jpg
Already copied: 219u5bTTQ5gGCDzfNfpGAw_0.jpg
Already copied: 2208hiIGD-Pm481_ijRwyA_0.jpg
Already copied: 24TA_CpF1E144M1CgUBRSg_0.jpg
Already copied: 24ZMIJuzqWQro_gyDCajtw_0.jpg
Already copied: 26HO9j-97GJMV5VqKh0O4g_0.jpg
Already copied: 27dumCPowqGbLHsh-AHr9A_0.jpg
Already copied: 27m_VUcehE5-dWjwiPKqeA_0.jpg
Already copied: 29-kJyCX_nuV59ekNcsySQ_0.jpg
Already copied: 29PHbQ9y46eMmkjCYe2LKA_0.jpg
Already copied: 29jMLYr2bBWfPr5IVCB_Dg_0.jpg
Already copied: 2ByZCvmwkpzq_dKAL8QBZA_0.jpg
Already copied: 2D5YNb5IGWrYSQHzzCvDww_0.jpg
Already copied: 2DkUNwO3R0M2UNrgoG2SBg_0.jpg
Already copied: 2E7rkVqPfzqzDBkd71iUcw_0.jpg
Already copied: 2FvCvEji2ye6Yjv04EusTg_0.jpg
Already copied: 2HNhG6Yms7ryTF2NvjkEsg_0.jpg
Already copied: 2IMGOzJV-h7vzz59EB_V9w_0.jpg
Already copied: 2Jm4mo_FCwRjym4rPhqKKQ_0.jpg
Already copied: 2JvmCJQdYo4Dn3YehUz89w_0.jpg
Already copied: 2N4W9Kc-KpFulkm0tM1eaQ_0.jpg
Already copied: 2NmL9HGCtkLVqu6LFTh6Sw_0.jpg
Already copied: 2PcFvt-hhG5MjbKZHEJ_TQ_0.jpg
Already copied: 2QBHD5fgd3th9_29FR7bSg_0.jpg
Already copied: 2R2yc2b6dZO_LMKWsbeQ7w_0.jpg
Already copied: 2RQ9Ngy6ke9hMeDqrvJGGw_0.jpg
Already copied: 2Tk5SpXMCcAVKJExloEnxA_0.jpg
Already copied: 2Xecqh3T7BGvMXQNEoS5gQ_0.jpg
Already copied: 2c5CZSYVG05J8Gd3aJhYEg_0.jpg
Already copied: 2coHonJh9LfEKFGNoJsIiA_0.jpg
Already copied: 2flPAZSv3-u6A0t2tTIR7Q_0.jpg
Already copied: 2gSWizDN_lT5kqAKfQqD-w_0.jpg
Already copied: 2ipwaqfNk33inDycojhf3Q_0.jpg
Already copied: 2j4GENckjN5cXmoSKdxBwQ_0.jpg
Already copied: 2kOqpVI8y-xAqDBWegEF3A_0.jpg
Already copied: 2oHTIqQ5jvRVxOQvCTSuJw_0.jpg
Already copied: 2oPtX9XdoHmNsAIc1V2uVw_0.jpg
Already copied: 2pCloJ2LeAv-YG9TQfpCog_0.jpg
Already copied: 2tFYffcelKGiXqOp5AMkaA_0.jpg
Already copied: 3-ObqNqRQXZgxnCYY7cTfQ_0.jpg
Already copied: 30PYBlqGUId1Rq5l2Vq1Xw_0.jpg
Already copied: 30qkI7Gmx546Y1ZnPFHm9A_0.jpg
Already copied: 37AaA_yLvcCmgZLucd5r_g_0.jpg
Already copied: 384qpSuuPwSnhtnfg36nKA_0.jpg
Already copied: 3Ahpnot23EAaHqog6kUXng_0.jpg
Already copied: 3BaDkeQH1mspeGV_CWUHow_0.jpg
Already copied: 3ED_odsx6-d234d9C3UGKA_0.jpg
Already copied: 3EdrEGR2_1hS6jgiBh5Mjw_0.jpg
Already copied: 3GBLKFiCIgyqBEEBpelUhw_0.jpg
Already copied: 3HOwQFKmy1Ll4h3mq5n4aA_0.jpg
Already copied: 3KiFMwdLVu9I4SyhQXPnLQ_0.jpg
Already copied: 3NKKFP3sdj6MrQAzvYM9cw_0.jpg
Already copied: 3RcbPvslDYre10WCmDCn4Q_0.jpg
Already copied: 3SYrhgQjLiZGvEJOZHuAZw_0.jpg
Already copied: 3TIose-5WESLTPZh-sO4RQ_0.jpg
Already copied: 3TNK3EJzJcHQh-z1HUC0fA_0.jpg
Already copied: 3WA2kZTpu8YlDUq5Mx_uhg_0.jpg
Already copied: 3WsNev4dkzLVykTX2Q6Dsg_0.jpg
Already copied: 3X3AeBFzETxmJyvZShol9g_0.jpg
Already copied: 3er4xOQfXy4oQsXEXG2Hcg_0.jpg
Already copied: 3g-AGQUWJeHGDXEwrDqbbw_0.jpg
Already copied: 3hw1ZfN3hQeyi2-f2Py5xw_0.jpg
Already copied: 3onUD1JS2qcnUh2vlOFNQQ_0.jpg
Already copied: 3p78JrDaZvddI3yj3F3DdQ_0.jpg
Already copied: 3pHMDJmn5rp634Y-Qv26mw_0.jpg
Already copied: 3pMvb6Dq0aB9tKT6GHuytA_0.jpg
Already copied: 3qn6Sy9d3-FIw2QtU16Ysg_0.jpg
Already copied: 3tAhvdFDPDf8eeS_PdaImA_0.jpg
Already copied: 3tGZJmvkxLaMm4e24gnD_w_0.jpg
Already copied: 3u3nX51LtYfVhLnTM5_HOw_0.jpg
Already copied: 3uevBiKq8UAI_bfAo0MbRw_0.jpg
Already copied: 3v9W6pGMzrpX2-lNJoHNsQ_0.jpg
Already copied: 3x9RUTqAGB4OPe0mcaOdPA_0.jpg
Already copied: 4-4HcS9OPrXWVzdtevUKxA_0.jpg
Already copied: 404mvmJEEQFvzutPcKIa8Q_0.jpg
Already copied: 49uie8TNQRwTfDlmVB25nA_0.jpg
Already copied: 4AnhsPOdz1B6JULYVAqKZw_0.jpg
Already copied: 4B2-64P0hpS_6J4NLLYuPQ_0.jpg
Already copied: 4FJ2Cr67MI6OGnWSIsZO2A_0.jpg
Already copied: 4FNrT6s2VGq88mM8MW7ujg_0.jpg
Already copied: 4G6PfNm6iYUoVrlBQj2Mmg_0.jpg
Already copied: 4HSEKrlj1CSHC3PPpz8WFg_0.jpg
Already copied: 4OXzgv8Jt4JBnyKYdNZXfg_0.jpg
Already copied: 4Q3qiDn_2iv9Lq3xJvPZCA_0.jpg
Already copied: 4S4BlK7z-dmQRFCAdthhJg_0.jpg
Already copied: 4U-2pToJSX7ze2d-PdMjPg_0.jpg
Already copied: 4V11xBdm9pWN4uogYwH0ew_0.jpg
Already copied: 4XHdqGgEV7p1jWaGSUA2Kg_0.jpg
Already copied: 4jEK1Bh8Ct9ksBrQn4PZjw_0.jpg
Already copied: 4ltx8Zv5BRhc44ILQN6tYw_0.jpg
Already copied: 4m552k6D_jJbaVe2tze4EA_0.jpg
Already copied: 4nEwO6Cqb43bIcmSbPfAnw_0.jpg
Already copied: 4n_HVDMace5T-qpCNUNSqw_0.jpg
Already copied: 4qmALWxaQSKBUUlUXiqFtg_0.jpg
Already copied: 4tCnlaxSOSSifKc-VSA7cw_0.jpg
Already copied: 4tSjoWXX6buzvdHkjs2uMw_0.jpg
Already copied: 4ub1DvFLwyDscFyTn_lJtw_0.jpg
Already copied: 4yr4YoBSugZ3KI7oG5FaAQ_0.jpg
Already copied: 4zHd-DpN9pKR11q0u6DmYg_0.jpg
Already copied: 4zJdikkLB1U1rRXq4B8I3w_0.jpg
Already copied: 5-85ehUpXaLvfXO_0dRZ-Q_0.jpg
Already copied: 53w5Zw7JJWRmfpYPUN8Wpg_0.jpg
Already copied: 58kDbfSr4kXAeEYwIejE-A_0.jpg
Already copied: 5976BWwiMupuMqaA2P20bA_0.jpg
Already copied: 59VrNH63HpuTZcnCSKCbQw_0.jpg
Already copied: 5AbVoRCsUKb-WF_mcHtKzQ_0.jpg
Already copied: 5EMa_rqslexfFxAXlfcQcw_0.jpg
Already copied: 5G8MO86T8FjGnzSOifrbdA_0.jpg
Already copied: 5N83s1f_1rWd8x49DVu0XA_0.jpg
Already copied: 5U3shWjrDMrrTgQGVPKhSA_0.jpg
Already copied: 5UaePHVgcYlo4lXfSWeF5g_0.jpg
Already copied: 5XmoPrAKSKeFzKrDytGtVg_0.jpg
Already copied: 5_OmBnkti1nErJz1qs9YyA_0.jpg
Already copied: 5beHKfbgcaPuqzgiicJ8PA_0.jpg
Already copied: 5bk_tSToXsy1QiNYYcWkKw_0.jpg
Already copied: 5bxGz6m5h-WgBU3v96qHlQ_0.jpg
Already copied: 5cqBIezI9MWYZFFJGGONsA_0.jpg
Already copied: 5gbfWW_YCqvRm-d-S7SBlA_0.jpg
Already copied: 5hKEJ40-t0mZQcEm6aKIag_0.jpg
Already copied: 5jfxoMOv5gJ2vo0BPObkPw_0.jpg
Already copied: 5kABLnvqToHCfBAQobNmNQ_0.jpg
Already copied: 5lSmoJ7HLvzSrIIDI1obsA_0.jpg
Already copied: 5mN6yXeBupkXzQnjwryd0A_0.jpg
Already copied: 5mnF7wV3ziSo4X-1qeI35w_0.jpg
Already copied: 5nCO5ejvUEGQ7hjIXUd3vw_0.jpg
Already copied: 5okz0Mf8kzCPhdnny-kdjA_0.jpg
Already copied: 5slYpCeBWMipQqAuutxDMg_0.jpg
Already copied: 5tvfKK1cJUxiTkKWgaxjyw_0.jpg
Already copied: 5uCDu5NgdC8rf0GbCzANAA_0.jpg
Already copied: 5yvKjtfdX402t5UqYEzW1w_0.jpg
Already copied: 61A-_nBmB8SOlKznN1f0lg_0.jpg
Already copied: 65i3h8IqhWzNh00zrPSq9w_0.jpg
Already copied: 65n42ReRwCOTMIVhkaAREw_0.jpg
Already copied: 65xEhzS-dYTel3DiPgkVGQ_0.jpg
Already copied: 6685N0lDkLyw0U6IC9MDUQ_0.jpg
Already copied: 67auQS4l0e5azMLYONWyRQ_0.jpg
Already copied: 680YrTG0QRhDGXGMRbuiLg_0.jpg
Already copied: 6B8CtoR7nzrogQxsdwza_Q_0.jpg
Already copied: 6CDyRP8H18YU89OvZIqi_g_0.jpg
Already copied: 6FJX8-EqlW3P5Fd3VyCGGw_0.jpg
Already copied: 6IJFbTAne1KX6wFlq9Kz4g_0.jpg
Already copied: 6LIXpNc8khZVaqpcBSzECA_0.jpg
Already copied: 6MVWMZr9n-bLlFxnfmiFbg_0.jpg
Already copied: 6Omue3whsWXb7J-8W0eL7Q_0.jpg
Already copied: 6S-yXtYflqDVNMv-c5aBOA_0.jpg
Already copied: 6X-IxqTZAVXUl-wNeIw_nA_0.jpg
Already copied: 6YZuKVBkXZfdI6_zMbP1Pw_0.jpg
Already copied: 6Z8hodK9L-4Dp8plBZAHdQ_0.jpg
Already copied: 6ZWTs4ceTB2TwboLEpqeXA_0.jpg
Already copied: 6ZlWAJL7A-IH60qVizlCIA_0.jpg
Already copied: 6dHsnkNo3L3GFVtEeTRWgA_0.jpg
Already copied: 6e4e99LX0A4FdU_dCgQztQ_0.jpg
Already copied: 6eKFI8XQyEiz-SBEVm-CXg_0.jpg
Already copied: 6gRXTYThEetfJ13OFkL8rA_0.jpg
Already copied: 6kBYr2ofuNm_ddNCOQEndg_0.jpg
Already copied: 6mEk1ydbpvrY9avPp5_DOQ_0.jpg
Already copied: 6oh2RJqrJSdhrJyZGRk90A_0.jpg
Already copied: 6pq5jaV9SWJQEgORUvn8Yw_0.jpg
Already copied: 6qfAoaAnLsUoUTcYOo8c_Q_0.jpg
Already copied: 6rczfZuBeerYX0kaxmH8yA_0.jpg
Already copied: 6s-HE_E949owqUrHWVwDaQ_0.jpg
Already copied: 6tNIs-odBMrBYWiujj3dOQ_0.jpg
Already copied: 6tPhgcmHgxZRLJscNXHA9w_0.jpg
Already copied: 7-oxxoHWnp7KQX9Kd5dIqg_0.jpg
Already copied: 7-sC-RnyIlKX5nEDLmPD3w_0.jpg
Already copied: 76PKtuNzGYHk5wesQdR8ig_0.jpg
Already copied: 76itEaO87j_W3sdvFbDg9g_0.jpg
Already copied: 79mxyM1CW89-oGgbR1HF_w_0.jpg
Already copied: 7Beamy3VF3zqLJ5BwtCRng_0.jpg
Already copied: 7CDwxo-Yfaq1H9KczoZKpw_0.jpg
Already copied: 7E0BJefF5PUcpyA0YDT1VQ_0.jpg
Already copied: 7EdTc4xmYFPnl_BT9jqcwA_0.jpg
Already copied: 7Eh00LNg5OgMEy5x7mcrDg_0.jpg
Already copied: 7GSMDFtqaTHwh2Ie3wAePw_0.jpg
Already copied: 7MCcGTspuDGzXSaxxN8zLg_0.jpg
Already copied: 7MNKu_yxILMYiTtQQFBKTA_0.jpg
Already copied: 7OP_2fH_vOJAXL8r13cRKA_0.jpg
Already copied: 7OedOYbI8S7xobtq_v6Qng_0.jpg
Already copied: 7Q1HA4VkZ0B4veutvueJ5Q_0.jpg
Already copied: 7Ub_C2DOp74-VnQEubSvuw_0.jpg
Already copied: 7W4d0KSjFKKVXbf5yCGmNA_0.jpg
Already copied: 7bLQ_qcqHvo5G9Sl22_CyQ_0.jpg
Already copied: 7bXTKFW1nPSL7_sXmqlhYw_0.jpg
Already copied: 7h5J_xzMEGMXoPQrHezjWA_0.jpg
Already copied: 7iQgKcmZS2bFWTXbbbqWBQ_0.jpg
Already copied: 7jAofLtftu9DRBsrqToUKg_0.jpg
Already copied: 7qIKYxGn6qUr5ufXoN0_eg_0.jpg
Already copied: 7t8-4NPEK2SCxFkP54XitA_0.jpg
Already copied: 7wMC8vekK_yE856SlaaFGA_0.jpg
Already copied: 7xWpNcUTdC36L-DjCYMWWQ_0.jpg
Already copied: 7ymwNkWFXO0lKrH94-oTpA_0.jpg
Already copied: 7zWq5-r5hhLPWOPj_-XlLg_0.jpg
Already copied: 81NhLUh0K_wmEOQQlHuRAQ_0.jpg
Already copied: 84L6tsg9BedDRDjo0JSy_A_0.jpg
Already copied: 86QXYmLsib9406BEhor68A_0.jpg
Already copied: 8Anrf9xIafxz9XArbL2ozg_0.jpg
Already copied: 8BifOcDlC-3z32sXKDENFQ_0.jpg
Already copied: 8CyQMqDBHsc4KN_-qW7lfA_0.jpg
Already copied: 8E6xaiQ70NxLJNh4lDS3IQ_0.jpg
Already copied: 8EAkxMeTudJlOT5rluSnkA_0.jpg
Already copied: 8F9Nmj1C08teg3qN3aZnlQ_0.jpg
Already copied: 8FdGAAjBhifo_dHitHE8yw_0.jpg
Already copied: 8GuDamNbCLjrW8Wag3CBmw_0.jpg
Already copied: 8HLiuspyDo0xx2YL5qsmWw_0.jpg
Already copied: 8HOe5rN8ajjOFGE_BRggcw_0.jpg
Already copied: 8KttScd1EZCPKgLBBCWB3w_0.jpg
Already copied: 8Lmdf6Bjp_0uECb0WxzV6Q_0.jpg
Already copied: 8MXnqOpJi_NpaVtIEdw9Ew_0.jpg
Already copied: 8PIiZYA-ipEt8Sm3AeZGQw_0.jpg
Already copied: 8XoVIoMdOU7jIilg_dnBFg_0.jpg
Already copied: 8aPaAvFfyLb1D9hVmg_2YQ_0.jpg
Already copied: 8aiQ0vKuDzkKuN57JCpB4w_0.jpg
Already copied: 8bSzol1fsXDHPlXy0nlusg_0.jpg
Already copied: 8caY4FeIrC89H8y4Xg-d6Q_0.jpg
Already copied: 8cjlYIy_qjs546zxkudoPA_0.jpg
Already copied: 8gSgAE_yV_VIo5L2VWvfnQ_0.jpg
Already copied: 8iI2JoClhgHD8lW80h_5Bg_0.jpg
Already copied: 8j4thnVqlA1UR0A2Zg4SDQ_0.jpg
Already copied: 8lxSc2MsSIsCmQ7SoltG2A_0.jpg
Already copied: 8oUoIHx10pqRwcqu7i_cvQ_0.jpg
Already copied: 8oVESyl-HGEUYKRXZw4sAw_0.jpg
Already copied: 8qGLsKgYr0LbXaVOrR8EZw_0.jpg
Already copied: 8r4Z3KKRSre6VLJxcjvHjg_0.jpg
Already copied: 8rF68V_nKp-Vihl8MVCPnw_0.jpg
Already copied: 8tH3T3EEtlon-MTMk-Z94Q_0.jpg
Already copied: 8tIqoj0gvzgbyLbxeAKmJQ_0.jpg
Already copied: 8up6y5LtQJCUVjVR5EwekQ_0.jpg
Already copied: 8uuu9xwWJcuExZIKUVvQOw_0.jpg
Already copied: 8vBuWqe7yKjASdBpwkx_xg_0.jpg
Already copied: 8vKRKbHBvwCTc2ALAufqsA_0.jpg
Already copied: 8xsU0EjWrPGXjXhq9CAguw_0.jpg
Already copied: 91diUL0Vc20F2QkwiustPw_0.jpg
Already copied: 93nXjZZPGLC31vY7pl8USw_0.jpg
Already copied: 93uSOGGgNAZJK4CNHMvruA_0.jpg
Already copied: 95_WP27gB_kT6RKzo6bXqw_0.jpg
Already copied: 98sNfxGScX0n6oyhioxiUw_0.jpg
Already copied: 99kEU1F68kd2lIDZYjhvow_0.jpg
Already copied: 9D4cWea2WfYjSZCWhJJD6A_0.jpg
Already copied: 9Du2HVj4CrjYp0KDyQr4DA_0.jpg
Already copied: 9Gs5hWnntPkBukLxKF6HyQ_0.jpg
Already copied: 9KGDHz9oOeRq7e6EshEC0w_0.jpg
Already copied: 9LYKTFxuwIfwGm_cGH8QCw_0.jpg
Already copied: 9M04SGO6WMFAAs2LtOMRYw_0.jpg
Already copied: 9MJ8uJ8Zv4VPGECZcnVoig_0.jpg
Already copied: 9OYKSRIhSLHAaj3dkgUOJw_0.jpg
Already copied: 9QpLijtT9WwmSW9lWgDnsA_0.jpg
Already copied: 9QzFH9U6FxRPj-1c3f5ADA_0.jpg
Already copied: 9Tst71gS7U8SiJhVVu4ekA_0.jpg
Already copied: 9UZsn9OYnEkIGJv5y9m1sQ_0.jpg
Already copied: 9UhV4YlaKjsrkjC_kMmfqQ_0.jpg
Already copied: 9VjwmbcRat_GnMJQVU1bxw_0.jpg
Already copied: 9aa1Ycot6OWUDig_aPOc1Q_0.jpg
Already copied: 9ein1gARPSR6vCQO2t9XUA_0.jpg
Already copied: 9elBzuCZ6ADZ7M1FyYh6Ow_0.jpg
Already copied: 9esSpTWSpuQhsov4gExI0w_0.jpg
Already copied: 9jE2rL4F3fDAK4wZF92zVg_0.jpg
Already copied: 9mOC5bZZngNc8wnYUn-Lvw_0.jpg
Already copied: 9osscyT5XgrzKkfPn-tjoQ_0.jpg
Already copied: 9qwuRijJwxFtfejZPoRFsw_0.jpg
Already copied: 9sMmTwz6srFpeCXRHBrfHw_0.jpg
Already copied: 9vnTx9mNTkCdX7xQkz4-bQ_0.jpg
Already copied: 9vuMWThNL_Jm4o81MaB7oA_0.jpg
Already copied: 9ydwJPddR4pusycPzfvNFg_0.jpg
Already copied: A0-Z6ObAMrrjM6q5Va0c1Q_0.jpg
Already copied: A05K1p4Nc2OZz_KsnzTi0A_0.jpg
Already copied: A5Ndp2YLQMLQy9qdLGKrUg_0.jpg
Already copied: A8osyuAUYz-KuMKF32_opg_0.jpg
Already copied: AAb1CAgD1kMscxgxRUnVRg_0.jpg
Already copied: AEUCI7jlyWtUchxhcVszLw_0.jpg
Already copied: AFDTWfeF01Aa3TKyuwANSQ_0.jpg
Already copied: AHyfHNK_aSyI-bW9SCJHZg_0.jpg
Already copied: ALGi17PRoJ0u3TA9nGYkOw_0.jpg
Already copied: AN0USTM-a2RWsN5P7QkuCw_0.jpg
Already copied: AO4CWTiLLQwVB7bQYkobug_0.jpg
Already copied: AOY0tZ2ny8v9lhOr0sFAGg_0.jpg
Already copied: AQU-z-LGbYe8Azb0ToBeNQ_0.jpg
Already copied: ARrKhCYe7LhltaqQOzotvA_0.jpg
Already copied: ASfd-V8IXyNr-DtE-0UD0A_0.jpg
Already copied: AW7uSiNLKDVsw165uqrASg_0.jpg
Already copied: AYnu6FK0KZ62QUVNztP9aA_0.jpg
Already copied: A_85O6e9cLlyMGmFtEuOdg_0.jpg
Already copied: Aj-2JvxFzptXn8mrPG_oWw_0.jpg
Already copied: AmV44sy5X6RW_2ydottHHQ_0.jpg
Already copied: Ar8Ufvfa0IForls5XqFJTQ_0.jpg
Already copied: Ar__HdEzsCCZfgydEgOCHg_0.jpg
Already copied: AudviuEF_fs5isGpJGCEdQ_0.jpg
Already copied: AvPQt0fgoMNqA0UzG2lCgQ_0.jpg
Already copied: B06ShJEuz2mJG1yOf_d_wQ_0.jpg
Already copied: B51uLYrCbRbIuiu64shKYQ_0.jpg
Already copied: B5DxBb2UGri53bh54wro-w_0.jpg
Already copied: B8nbYhm-BauHZNFN2oNquA_0.jpg
Already copied: BDToYlN8sZ5oAOXNEUCezw_0.jpg
Already copied: BH9iAB3CxcUMeDnzN4czOw_0.jpg
Already copied: BHKPO3TchKILCeg7w0snsQ_0.jpg
Already copied: BHzcZx_6OsQBZwLfLLZpxA_0.jpg
Already copied: BI_wLb1MutdTF9yGyagdLA_0.jpg
Already copied: BKwgACpHhkZQzHSvmXYGiw_0.jpg
Already copied: BKyUYJw50xoHJUzUVgDNnA_0.jpg
Already copied: BMNVaNkZ0Qj6PgTJCdSujA_0.jpg
Already copied: BMVNG98M0AT3mZeRO_TCZQ_0.jpg
Already copied: BOFAYq7l0PF7Lg2_Kn258w_0.jpg
Already copied: BPZCWz5u_ugyNL4E2BhXBw_0.jpg
Already copied: BT6qjdhXMOkU9mXeqmgEPA_0.jpg
Already copied: BVaUHZotSOGnhuV4zsj96w_0.jpg
Already copied: BWyB-MIYy1sj4Y-ZMeD4QA_0.jpg
Already copied: B_uhCJZeNSEgUdJJNbR3KA_0.jpg
Already copied: Ba8VqYMLy1Vqo90jDp8SKw_0.jpg
Already copied: BcyG1FHka5fnxS2bJZ2RFg_0.jpg
Already copied: BgxirwR3CE-c8Ln7EL7C-g_0.jpg
Already copied: BjPuotDxMHwsAJ8RoXzD-Q_0.jpg
Already copied: Blbuxun859llO235pdix0w_0.jpg
Already copied: BnQCZ_LrlHiWODqW4JydQg_0.jpg
Already copied: Bp82990WcDH8fd6W0GiqdA_0.jpg
Already copied: BqRJGkNGZD79P-4D595SPQ_0.jpg
Already copied: Bqc-MMPqDJJmYnzdVzd8Aw_0.jpg
Already copied: BzOwdUBdYQXSHeXecSPQAw_0.jpg
Already copied: BzvYdIo_u10fl_A2vTAjKg_0.jpg
Already copied: C-oQv2YqY2BbiNZZUCGm0w_0.jpg
Already copied: C2eaxizZw3t_gRPd5R7ePQ_0.jpg
Already copied: C8VVIsefoBiRXSI8sS2Aag_0.jpg
Already copied: CCViv5o3Ilgg4mQQauI-2Q_0.jpg
Already copied: CCvSkq9IsFJLx0Z82MoJdw_0.jpg
Already copied: CJKLsu7eCpagDcWpsz5OvA_0.jpg
Already copied: CKPqh5qJjNhb32f0L0i7qg_0.jpg
Already copied: CLw9b2PX9HlmVLtpCnu15A_0.jpg
Already copied: CQhP0Ksgn83-WTFDX1sx9w_0.jpg
Already copied: CU_ZKFZBV_iJuWxvjvMMLA_0.jpg
Already copied: CUgeDh2TC03xrHhqXylbdg_0.jpg
Already copied: CYpvPpF3TNn3mebfMuK2LQ_0.jpg
Already copied: CZN_-VncQJ9dvstaWucAJw_0.jpg
Already copied: C_Nz2ves6oE3RFLYmcj3_Q_0.jpg
Already copied: C_frdSvSHWcYFv0TorCyig_0.jpg
Already copied: CaAQ_sqeLu71eNXbBOvkvg_0.jpg
Already copied: CbjtQ_mA1fPHF9BtiTkOjw_0.jpg
Already copied: CcckwgBwJ54QvFPYDT6URg_0.jpg
Already copied: Cck2cYtr-MxWfzp_MRMigQ_0.jpg
Already copied: CekUqPxA6DFC5jgQChmEwQ_0.jpg
Already copied: Ch9nn6stFCFpoqvDQwiZzQ_0.jpg
Already copied: ChIVe403HR8eJ07MHNKCgQ_0.jpg
Already copied: CjHEp5WlLZuKIhsjsSNxOQ_0.jpg
Already copied: CjaixqhH0BFAWAr-NqAYuA_0.jpg
Already copied: ClV15EyHw8gDptH_P9nCdQ_0.jpg
Already copied: CnmECN5jiVT4_d63Irx5XA_0.jpg
Already copied: Cq9JEl88M2RNZ9q3j87UTg_0.jpg
Already copied: CxhcTijxE8JQASAcWl0xqg_0.jpg
Already copied: CxmJXX4B0NpRGTcMNH56-A_0.jpg
Already copied: CyHRafAbn35YG7qmQb3NIw_0.jpg
Already copied: D1ZQcY1Rj5MqW5obtidpHw_0.jpg
Already copied: D2YYGpsBBK0nRkNXXshZIQ_0.jpg
Already copied: D3EM_rD7XwD8rjtLT3VsCA_0.jpg
Already copied: D42T31nbQILpC9z-I2x8nw_0.jpg
Already copied: DB8ACLdZxwR8TJkzRBicPA_0.jpg
Already copied: DDrNmyfwOXneoTIp5V69oA_0.jpg
Already copied: DNG5jpipikLkvhllARf7Sg_0.jpg
Already copied: DNdnpmfxtMkQEArYgiHNQw_0.jpg
Already copied: DT5_yIFrCJuXbKBOlGiQEA_0.jpg

In [46]:
import os
import shutil

# Define possible extensions
extensions = ['.jpg', '.JPG', '.png']

# Iterate over the DataFrame rows
for index, row in df_move.iterrows():
    img_folder = row['img_path'] 
    file_found = False

    for ext in extensions:
        modified_img_name = row['img_name'] + ext  # Append extension
        source_path = os.path.join(basepath, img_folder, modified_img_name)

        # Construct the destination file path
        dest_file_path = os.path.join(destination_path, modified_img_name)

        # Check if the image has already been copied
        if modified_img_name not in copied_images:
            # Try copying the file with the current extension
            if os.path.exists(source_path):
                shutil.copy2(source_path, dest_file_path)
                copied_images.add(modified_img_name)
                file_found = True
                break  # Stop trying other extensions
            else:
                continue  # Try the next extension
        else:
            print(f"Already copied: {modified_img_name}")
            file_found = True
            break  # File already copied, no need to try other extensions

    if not file_found:
        print(f"File not found for any extensions: {row['img_name']}")

Already copied: -0wIGghq_wnmlSxQjvfs6Q_0.jpg
Already copied: -3l0SHoc2SjGiBF8t3kaaQ_0.jpg
Already copied: -5HilXXyL-qKt1wv8n1zRg_0.jpg
Already copied: -8hBsb_UsQnDtjS1V6mYvA_0.jpg
Already copied: -997EmNYPzvePfvUwFaWEw_0.jpg
Already copied: -B28FqYgw7ft1_iGNP-xzg_0.jpg
Already copied: -CQQqjzgoLawx3LN307U4g_0.jpg
Already copied: -HPeP6rd8-vM3Li8sSdvkA_0.jpg
Already copied: -IMlKszChg08pW8GMgiLQg_0.jpg
Already copied: -IWRLSUH5z4_XZNFVKof6g_0.jpg
Already copied: -Rusmn9hI2gV7UroHd80Cg_0.jpg
Already copied: -Tm9BB__cL87GjVbDos4mQ_0.jpg
Already copied: -WYuHXoRfzrraYWMscvLNw_0.jpg
Already copied: -_Zxs2WP-X8m7qj-REHpnQ_0.jpg
Already copied: -dE81PTqRvl-czwNVPc17w_0.jpg
Already copied: -dnEqpLrlgYAsG3FVFQ7Aw_0.jpg
Already copied: -gJRF24oKdAlQF_HCZp-Ww_0.jpg
Already copied: -gpavYadFqehhwXprGSR9g_0.jpg
Already copied: -hJxaBJdlGNQu2ID-I1Sng_0.jpg
Already copied: -i-eH0et7_OzpUTIVMXEVg_0.jpg
Already copied: -iUberVTsT9M1KW-T5JZAg_0.jpg
Already copied: -j91DihhMo7HVZsmP6uNWA_0.jpg
Already copied: -qGhfW3xdAZ6wvVBumBdgg_0.jpg
Already copied: -qU8YANg-YEdkD89sRfcTA_0.jpg
Already copied: -qWeZ9Tt6xWTzeGv0L1Z-A_0.jpg
Already copied: -x-2K6q7sNpZqLVEUHcr6Q_0.jpg
Already copied: -xxW4ylzG299vowxeKpvYQ_0.jpg
Already copied: 04uNACQIGwVFI7wl7MZVqQ_0.jpg
Already copied: 05GgGnPe4cos7dwwFNFztA_0.jpg
Already copied: 08nTynEuBPEKOWecC6ePgQ_0.jpg
Already copied: 09e0bWl6FL2iCqL1ymGmyg_0.jpg
Already copied: 0Cl1ty8xnBUhc66lj6NArQ_0.jpg
Already copied: 0DBezUvFKTl7daWl1GvOow_0.jpg
Already copied: 0DYpIajZfrM6dmTZYC7g4g_0.jpg
Already copied: 0Esn5VdDgrnwLq5QLT98Uw_0.jpg
Already copied: 0GoJFQmz_XOXY8VEftFPGg_0.jpg
Already copied: 0HI2Jr5jeLap42lkDOPOdg_0.jpg
Already copied: 0IYvopVjl848MSO5aonogQ_0.jpg
Already copied: 0NT6B4r_Q1d3pUZAGzOjlw_0.jpg
Already copied: 0Rdo1RqvAXXa7REMIMQehg_0.jpg
Already copied: 0ZGYi-iouyIO0ppJSSpAsQ_0.jpg
Already copied: 0ZtmcsPfg2TirRBP-BzmiA_0.jpg
Already copied: 0_dW7k9mzQx4cXTJV9U_Og_0.jpg
Already copied: 0l-EPufk1j_bloz7FEbBMQ_0.jpg
Already copied: 0lt_NEu3YlTCAJEK7TdU3A_0.jpg
Already copied: 0nHhj8kzfAMSL_W7DJd4Og_0.jpg
Already copied: 0oOMUqQzzas9h0sBVqnACw_0.jpg
Already copied: 0pcBfRcYxZzhRCReU9NocQ_0.jpg
Already copied: 0q03zTEQW0KjT2fEYXpGTA_0.jpg
Already copied: 0qVsBzHoLyC3wAJRCL9o-Q_0.jpg
Already copied: 0uJOq262cA-P1hhicTy4qQ_0.jpg
Already copied: 0uj3iwZL4xvtgUXbCgqTrA_0.jpg
Already copied: 0vx6RscL5WxBA9Csp9XOIw_0.jpg
Already copied: 0wdClD5m81WZMb4QuOdY6Q_0.jpg
Already copied: 0xHA7WbQVUC5KqZakwIj9Q_0.jpg
Already copied: 0z6z6wSCUA6KxtQbR2JSFg_0.jpg
Already copied: 11xXQ9TCvV8oNFMcLPoxng_0.jpg
Already copied: 13jpvmgwj1ozcN5LJsSnyQ_0.jpg
Already copied: 15_5OuoLGTQTWdRTAb6tZA_0.jpg
Already copied: 17SudvciJGXTU1PPXzB5Hw_0.jpg
Already copied: 19AwR73Jvr6AyfcP7ebY1w_0.jpg
Already copied: 1EIdg83IpchDoCM5hD2RrA_0.jpg
Already copied: 1G3gi3JBj0WQpMyNc5NNug_0.jpg
Already copied: 1H5dr8MxGHAGuFKpgHrSAA_0.jpg
Already copied: 1Kk83im3uw4IPQ8lM6ckTg_0.jpg
Already copied: 1L-wW4QNVdW0Naufj2Dp_Q_0.jpg
Already copied: 1LrgYHZkmNRAUvYeSHANwA_0.jpg
Already copied: 1P8wKN5QuiF5nNTd2nynFQ_0.jpg
Already copied: 1PA-1gbY2kJq7mp-TjF2bg_0.jpg
Already copied: 1RgBfjxbLz6ffLIqVZyhhg_0.jpg
Already copied: 1TH5ro9nAgWHi_QN6ausLQ_0.jpg
Already copied: 1U84muGD84hCS9AjwRBO4Q_0.jpg
Already copied: 1UlGKxBT4cLDMFB2Ge-VUg_0.jpg
Already copied: 1Zvo_3961hLXseSfzxowHg_0.jpg
Already copied: 1_reB3GHf5wzIRzkS9Uafg_0.jpg
Already copied: 1cuJ7rH2GwJNgsZYMXcqBQ_0.jpg
Already copied: 1kB862rPRviWi_xhIs9aJg_0.jpg
Already copied: 1l8GFvHKJ7xIIjzjkFFK0w_0.jpg
Already copied: 1mjT6U1te-GrtrKgxHMsBg_0.jpg
Already copied: 1peBYD7ZyY7iYLB6ORXuOQ_0.jpg
Already copied: 1qVggII2UdAz7eCAKsYiEA_0.jpg
Already copied: 1rVnrQKI3-HcStA5UWaLew_0.jpg
Already copied: 1sSfOwGf83ZHbL5Lf5vFhg_0.jpg
Already copied: 1s_6dgghD_zqcDuiCIz3Yg_0.jpg
Already copied: 1t-_bAZcLO1dj4GKlwYLjg_0.jpg
Already copied: 1tbZ_Yem9hqvCND8zkjoWA_0.jpg
Already copied: 1xVuBBUGeNYAnkfcVb1EOg_0.jpg
Already copied: 1yinqmMc-Y4MDN6MWeN18g_0.jpg
Already copied: 2-_dSTnQ-1Bdcz9BsRTEaA_0.jpg
Already copied: 219u5bTTQ5gGCDzfNfpGAw_0.jpg
Already copied: 2208hiIGD-Pm481_ijRwyA_0.jpg
Already copied: 24TA_CpF1E144M1CgUBRSg_0.jpg
Already copied: 24ZMIJuzqWQro_gyDCajtw_0.jpg
Already copied: 26HO9j-97GJMV5VqKh0O4g_0.jpg
Already copied: 27dumCPowqGbLHsh-AHr9A_0.jpg
Already copied: 27m_VUcehE5-dWjwiPKqeA_0.jpg
Already copied: 29-kJyCX_nuV59ekNcsySQ_0.jpg
Already copied: 29PHbQ9y46eMmkjCYe2LKA_0.jpg
Already copied: 29jMLYr2bBWfPr5IVCB_Dg_0.jpg
Already copied: 2ByZCvmwkpzq_dKAL8QBZA_0.jpg
Already copied: 2D5YNb5IGWrYSQHzzCvDww_0.jpg
Already copied: 2DkUNwO3R0M2UNrgoG2SBg_0.jpg
Already copied: 2E7rkVqPfzqzDBkd71iUcw_0.jpg
Already copied: 2FvCvEji2ye6Yjv04EusTg_0.jpg
Already copied: 2HNhG6Yms7ryTF2NvjkEsg_0.jpg
Already copied: 2IMGOzJV-h7vzz59EB_V9w_0.jpg
Already copied: 2Jm4mo_FCwRjym4rPhqKKQ_0.jpg
Already copied: 2JvmCJQdYo4Dn3YehUz89w_0.jpg
Already copied: 2N4W9Kc-KpFulkm0tM1eaQ_0.jpg
Already copied: 2NmL9HGCtkLVqu6LFTh6Sw_0.jpg
Already copied: 2PcFvt-hhG5MjbKZHEJ_TQ_0.jpg
Already copied: 2QBHD5fgd3th9_29FR7bSg_0.jpg
Already copied: 2R2yc2b6dZO_LMKWsbeQ7w_0.jpg
Already copied: 2RQ9Ngy6ke9hMeDqrvJGGw_0.jpg
Already copied: 2Tk5SpXMCcAVKJExloEnxA_0.jpg
Already copied: 2Xecqh3T7BGvMXQNEoS5gQ_0.jpg
Already copied: 2c5CZSYVG05J8Gd3aJhYEg_0.jpg
Already copied: 2coHonJh9LfEKFGNoJsIiA_0.jpg
Already copied: 2flPAZSv3-u6A0t2tTIR7Q_0.jpg
Already copied: 2gSWizDN_lT5kqAKfQqD-w_0.jpg
Already copied: 2ipwaqfNk33inDycojhf3Q_0.jpg
Already copied: 2j4GENckjN5cXmoSKdxBwQ_0.jpg
Already copied: 2kOqpVI8y-xAqDBWegEF3A_0.jpg
Already copied: 2oHTIqQ5jvRVxOQvCTSuJw_0.jpg
Already copied: 2oPtX9XdoHmNsAIc1V2uVw_0.jpg
Already copied: 2pCloJ2LeAv-YG9TQfpCog_0.jpg
Already copied: 2tFYffcelKGiXqOp5AMkaA_0.jpg
Already copied: 3-ObqNqRQXZgxnCYY7cTfQ_0.jpg
Already copied: 30PYBlqGUId1Rq5l2Vq1Xw_0.jpg
Already copied: 30qkI7Gmx546Y1ZnPFHm9A_0.jpg
Already copied: 37AaA_yLvcCmgZLucd5r_g_0.jpg
Already copied: 384qpSuuPwSnhtnfg36nKA_0.jpg
Already copied: 3Ahpnot23EAaHqog6kUXng_0.jpg
Already copied: 3BaDkeQH1mspeGV_CWUHow_0.jpg
Already copied: 3ED_odsx6-d234d9C3UGKA_0.jpg
Already copied: 3EdrEGR2_1hS6jgiBh5Mjw_0.jpg
Already copied: 3GBLKFiCIgyqBEEBpelUhw_0.jpg
Already copied: 3HOwQFKmy1Ll4h3mq5n4aA_0.jpg
Already copied: 3KiFMwdLVu9I4SyhQXPnLQ_0.jpg
Already copied: 3NKKFP3sdj6MrQAzvYM9cw_0.jpg
Already copied: 3RcbPvslDYre10WCmDCn4Q_0.jpg
Already copied: 3SYrhgQjLiZGvEJOZHuAZw_0.jpg
Already copied: 3TIose-5WESLTPZh-sO4RQ_0.jpg
Already copied: 3TNK3EJzJcHQh-z1HUC0fA_0.jpg
Already copied: 3WA2kZTpu8YlDUq5Mx_uhg_0.jpg
Already copied: 3WsNev4dkzLVykTX2Q6Dsg_0.jpg
Already copied: 3X3AeBFzETxmJyvZShol9g_0.jpg
Already copied: 3er4xOQfXy4oQsXEXG2Hcg_0.jpg
Already copied: 3g-AGQUWJeHGDXEwrDqbbw_0.jpg
Already copied: 3hw1ZfN3hQeyi2-f2Py5xw_0.jpg
Already copied: 3onUD1JS2qcnUh2vlOFNQQ_0.jpg
Already copied: 3p78JrDaZvddI3yj3F3DdQ_0.jpg
Already copied: 3pHMDJmn5rp634Y-Qv26mw_0.jpg
Already copied: 3pMvb6Dq0aB9tKT6GHuytA_0.jpg
Already copied: 3qn6Sy9d3-FIw2QtU16Ysg_0.jpg
Already copied: 3tAhvdFDPDf8eeS_PdaImA_0.jpg
Already copied: 3tGZJmvkxLaMm4e24gnD_w_0.jpg
Already copied: 3u3nX51LtYfVhLnTM5_HOw_0.jpg
Already copied: 3uevBiKq8UAI_bfAo0MbRw_0.jpg
Already copied: 3v9W6pGMzrpX2-lNJoHNsQ_0.jpg
Already copied: 3x9RUTqAGB4OPe0mcaOdPA_0.jpg
Already copied: 4-4HcS9OPrXWVzdtevUKxA_0.jpg
Already copied: 404mvmJEEQFvzutPcKIa8Q_0.jpg
Already copied: 49uie8TNQRwTfDlmVB25nA_0.jpg
Already copied: 4AnhsPOdz1B6JULYVAqKZw_0.jpg
Already copied: 4B2-64P0hpS_6J4NLLYuPQ_0.jpg
Already copied: 4FJ2Cr67MI6OGnWSIsZO2A_0.jpg
Already copied: 4FNrT6s2VGq88mM8MW7ujg_0.jpg
Already copied: 4G6PfNm6iYUoVrlBQj2Mmg_0.jpg
Already copied: 4HSEKrlj1CSHC3PPpz8WFg_0.jpg
Already copied: 4OXzgv8Jt4JBnyKYdNZXfg_0.jpg
Already copied: 4Q3qiDn_2iv9Lq3xJvPZCA_0.jpg
Already copied: 4S4BlK7z-dmQRFCAdthhJg_0.jpg
Already copied: 4U-2pToJSX7ze2d-PdMjPg_0.jpg
Already copied: 4V11xBdm9pWN4uogYwH0ew_0.jpg
Already copied: 4XHdqGgEV7p1jWaGSUA2Kg_0.jpg
Already copied: 4jEK1Bh8Ct9ksBrQn4PZjw_0.jpg
Already copied: 4ltx8Zv5BRhc44ILQN6tYw_0.jpg
Already copied: 4m552k6D_jJbaVe2tze4EA_0.jpg
Already copied: 4nEwO6Cqb43bIcmSbPfAnw_0.jpg
Already copied: 4n_HVDMace5T-qpCNUNSqw_0.jpg
Already copied: 4qmALWxaQSKBUUlUXiqFtg_0.jpg
Already copied: 4tCnlaxSOSSifKc-VSA7cw_0.jpg
Already copied: 4tSjoWXX6buzvdHkjs2uMw_0.jpg
Already copied: 4ub1DvFLwyDscFyTn_lJtw_0.jpg
Already copied: 4yr4YoBSugZ3KI7oG5FaAQ_0.jpg
Already copied: 4zHd-DpN9pKR11q0u6DmYg_0.jpg
Already copied: 4zJdikkLB1U1rRXq4B8I3w_0.jpg
Already copied: 5-85ehUpXaLvfXO_0dRZ-Q_0.jpg
Already copied: 53w5Zw7JJWRmfpYPUN8Wpg_0.jpg
Already copied: 58kDbfSr4kXAeEYwIejE-A_0.jpg
Already copied: 5976BWwiMupuMqaA2P20bA_0.jpg
Already copied: 59VrNH63HpuTZcnCSKCbQw_0.jpg
Already copied: 5AbVoRCsUKb-WF_mcHtKzQ_0.jpg
Already copied: 5EMa_rqslexfFxAXlfcQcw_0.jpg
Already copied: 5G8MO86T8FjGnzSOifrbdA_0.jpg
Already copied: 5N83s1f_1rWd8x49DVu0XA_0.jpg
Already copied: 5U3shWjrDMrrTgQGVPKhSA_0.jpg
Already copied: 5UaePHVgcYlo4lXfSWeF5g_0.jpg
Already copied: 5XmoPrAKSKeFzKrDytGtVg_0.jpg
Already copied: 5_OmBnkti1nErJz1qs9YyA_0.jpg
Already copied: 5beHKfbgcaPuqzgiicJ8PA_0.jpg
Already copied: 5bk_tSToXsy1QiNYYcWkKw_0.jpg
Already copied: 5bxGz6m5h-WgBU3v96qHlQ_0.jpg
Already copied: 5cqBIezI9MWYZFFJGGONsA_0.jpg
Already copied: 5gbfWW_YCqvRm-d-S7SBlA_0.jpg
Already copied: 5hKEJ40-t0mZQcEm6aKIag_0.jpg
Already copied: 5jfxoMOv5gJ2vo0BPObkPw_0.jpg
Already copied: 5kABLnvqToHCfBAQobNmNQ_0.jpg
Already copied: 5lSmoJ7HLvzSrIIDI1obsA_0.jpg
Already copied: 5mN6yXeBupkXzQnjwryd0A_0.jpg
Already copied: 5mnF7wV3ziSo4X-1qeI35w_0.jpg
Already copied: 5nCO5ejvUEGQ7hjIXUd3vw_0.jpg
Already copied: 5okz0Mf8kzCPhdnny-kdjA_0.jpg
Already copied: 5slYpCeBWMipQqAuutxDMg_0.jpg
Already copied: 5tvfKK1cJUxiTkKWgaxjyw_0.jpg
Already copied: 5uCDu5NgdC8rf0GbCzANAA_0.jpg
Already copied: 5yvKjtfdX402t5UqYEzW1w_0.jpg
Already copied: 61A-_nBmB8SOlKznN1f0lg_0.jpg
Already copied: 65i3h8IqhWzNh00zrPSq9w_0.jpg
Already copied: 65n42ReRwCOTMIVhkaAREw_0.jpg
Already copied: 65xEhzS-dYTel3DiPgkVGQ_0.jpg
Already copied: 6685N0lDkLyw0U6IC9MDUQ_0.jpg
Already copied: 67auQS4l0e5azMLYONWyRQ_0.jpg
Already copied: 680YrTG0QRhDGXGMRbuiLg_0.jpg
Already copied: 6B8CtoR7nzrogQxsdwza_Q_0.jpg
Already copied: 6CDyRP8H18YU89OvZIqi_g_0.jpg
Already copied: 6FJX8-EqlW3P5Fd3VyCGGw_0.jpg
Already copied: 6IJFbTAne1KX6wFlq9Kz4g_0.jpg
Already copied: 6LIXpNc8khZVaqpcBSzECA_0.jpg
Already copied: 6MVWMZr9n-bLlFxnfmiFbg_0.jpg
Already copied: 6Omue3whsWXb7J-8W0eL7Q_0.jpg
Already copied: 6S-yXtYflqDVNMv-c5aBOA_0.jpg
Already copied: 6X-IxqTZAVXUl-wNeIw_nA_0.jpg
Already copied: 6YZuKVBkXZfdI6_zMbP1Pw_0.jpg
Already copied: 6Z8hodK9L-4Dp8plBZAHdQ_0.jpg
Already copied: 6ZWTs4ceTB2TwboLEpqeXA_0.jpg
Already copied: 6ZlWAJL7A-IH60qVizlCIA_0.jpg
Already copied: 6dHsnkNo3L3GFVtEeTRWgA_0.jpg
Already copied: 6e4e99LX0A4FdU_dCgQztQ_0.jpg
Already copied: 6eKFI8XQyEiz-SBEVm-CXg_0.jpg
Already copied: 6gRXTYThEetfJ13OFkL8rA_0.jpg
Already copied: 6kBYr2ofuNm_ddNCOQEndg_0.jpg
Already copied: 6mEk1ydbpvrY9avPp5_DOQ_0.jpg
Already copied: 6oh2RJqrJSdhrJyZGRk90A_0.jpg
Already copied: 6pq5jaV9SWJQEgORUvn8Yw_0.jpg
Already copied: 6qfAoaAnLsUoUTcYOo8c_Q_0.jpg
Already copied: 6rczfZuBeerYX0kaxmH8yA_0.jpg
Already copied: 6s-HE_E949owqUrHWVwDaQ_0.jpg
Already copied: 6tNIs-odBMrBYWiujj3dOQ_0.jpg
Already copied: 6tPhgcmHgxZRLJscNXHA9w_0.jpg
Already copied: 7-oxxoHWnp7KQX9Kd5dIqg_0.jpg
Already copied: 7-sC-RnyIlKX5nEDLmPD3w_0.jpg
Already copied: 76PKtuNzGYHk5wesQdR8ig_0.jpg
Already copied: 76itEaO87j_W3sdvFbDg9g_0.jpg
Already copied: 79mxyM1CW89-oGgbR1HF_w_0.jpg
Already copied: 7Beamy3VF3zqLJ5BwtCRng_0.jpg
Already copied: 7CDwxo-Yfaq1H9KczoZKpw_0.jpg
Already copied: 7E0BJefF5PUcpyA0YDT1VQ_0.jpg
Already copied: 7EdTc4xmYFPnl_BT9jqcwA_0.jpg
Already copied: 7Eh00LNg5OgMEy5x7mcrDg_0.jpg
Already copied: 7GSMDFtqaTHwh2Ie3wAePw_0.jpg
Already copied: 7MCcGTspuDGzXSaxxN8zLg_0.jpg
Already copied: 7MNKu_yxILMYiTtQQFBKTA_0.jpg
Already copied: 7OP_2fH_vOJAXL8r13cRKA_0.jpg
Already copied: 7OedOYbI8S7xobtq_v6Qng_0.jpg
Already copied: 7Q1HA4VkZ0B4veutvueJ5Q_0.jpg
Already copied: 7Ub_C2DOp74-VnQEubSvuw_0.jpg
Already copied: 7W4d0KSjFKKVXbf5yCGmNA_0.jpg
Already copied: 7bLQ_qcqHvo5G9Sl22_CyQ_0.jpg
Already copied: 7bXTKFW1nPSL7_sXmqlhYw_0.jpg
Already copied: 7h5J_xzMEGMXoPQrHezjWA_0.jpg
Already copied: 7iQgKcmZS2bFWTXbbbqWBQ_0.jpg
Already copied: 7jAofLtftu9DRBsrqToUKg_0.jpg
Already copied: 7qIKYxGn6qUr5ufXoN0_eg_0.jpg
Already copied: 7t8-4NPEK2SCxFkP54XitA_0.jpg
Already copied: 7wMC8vekK_yE856SlaaFGA_0.jpg
Already copied: 7xWpNcUTdC36L-DjCYMWWQ_0.jpg
Already copied: 7ymwNkWFXO0lKrH94-oTpA_0.jpg
Already copied: 7zWq5-r5hhLPWOPj_-XlLg_0.jpg
Already copied: 81NhLUh0K_wmEOQQlHuRAQ_0.jpg
Already copied: 84L6tsg9BedDRDjo0JSy_A_0.jpg
Already copied: 86QXYmLsib9406BEhor68A_0.jpg
Already copied: 8Anrf9xIafxz9XArbL2ozg_0.jpg
Already copied: 8BifOcDlC-3z32sXKDENFQ_0.jpg
Already copied: 8CyQMqDBHsc4KN_-qW7lfA_0.jpg
Already copied: 8E6xaiQ70NxLJNh4lDS3IQ_0.jpg
Already copied: 8EAkxMeTudJlOT5rluSnkA_0.jpg
Already copied: 8F9Nmj1C08teg3qN3aZnlQ_0.jpg
Already copied: 8FdGAAjBhifo_dHitHE8yw_0.jpg
Already copied: 8GuDamNbCLjrW8Wag3CBmw_0.jpg
Already copied: 8HLiuspyDo0xx2YL5qsmWw_0.jpg
Already copied: 8HOe5rN8ajjOFGE_BRggcw_0.jpg
Already copied: 8KttScd1EZCPKgLBBCWB3w_0.jpg
Already copied: 8Lmdf6Bjp_0uECb0WxzV6Q_0.jpg
Already copied: 8MXnqOpJi_NpaVtIEdw9Ew_0.jpg
Already copied: 8PIiZYA-ipEt8Sm3AeZGQw_0.jpg
Already copied: 8XoVIoMdOU7jIilg_dnBFg_0.jpg
Already copied: 8aPaAvFfyLb1D9hVmg_2YQ_0.jpg
Already copied: 8aiQ0vKuDzkKuN57JCpB4w_0.jpg
Already copied: 8bSzol1fsXDHPlXy0nlusg_0.jpg
Already copied: 8caY4FeIrC89H8y4Xg-d6Q_0.jpg
Already copied: 8cjlYIy_qjs546zxkudoPA_0.jpg
Already copied: 8gSgAE_yV_VIo5L2VWvfnQ_0.jpg
Already copied: 8iI2JoClhgHD8lW80h_5Bg_0.jpg
Already copied: 8j4thnVqlA1UR0A2Zg4SDQ_0.jpg
Already copied: 8lxSc2MsSIsCmQ7SoltG2A_0.jpg
Already copied: 8oUoIHx10pqRwcqu7i_cvQ_0.jpg
Already copied: 8oVESyl-HGEUYKRXZw4sAw_0.jpg
Already copied: 8qGLsKgYr0LbXaVOrR8EZw_0.jpg
Already copied: 8r4Z3KKRSre6VLJxcjvHjg_0.jpg
Already copied: 8rF68V_nKp-Vihl8MVCPnw_0.jpg
Already copied: 8tH3T3EEtlon-MTMk-Z94Q_0.jpg
Already copied: 8tIqoj0gvzgbyLbxeAKmJQ_0.jpg
Already copied: 8up6y5LtQJCUVjVR5EwekQ_0.jpg
Already copied: 8uuu9xwWJcuExZIKUVvQOw_0.jpg
Already copied: 8vBuWqe7yKjASdBpwkx_xg_0.jpg
Already copied: 8vKRKbHBvwCTc2ALAufqsA_0.jpg
Already copied: 8xsU0EjWrPGXjXhq9CAguw_0.jpg
Already copied: 91diUL0Vc20F2QkwiustPw_0.jpg
Already copied: 93nXjZZPGLC31vY7pl8USw_0.jpg
Already copied: 93uSOGGgNAZJK4CNHMvruA_0.jpg
Already copied: 95_WP27gB_kT6RKzo6bXqw_0.jpg
Already copied: 98sNfxGScX0n6oyhioxiUw_0.jpg
Already copied: 99kEU1F68kd2lIDZYjhvow_0.jpg
Already copied: 9D4cWea2WfYjSZCWhJJD6A_0.jpg
Already copied: 9Du2HVj4CrjYp0KDyQr4DA_0.jpg
Already copied: 9Gs5hWnntPkBukLxKF6HyQ_0.jpg
Already copied: 9KGDHz9oOeRq7e6EshEC0w_0.jpg
Already copied: 9LYKTFxuwIfwGm_cGH8QCw_0.jpg
Already copied: 9M04SGO6WMFAAs2LtOMRYw_0.jpg
Already copied: 9MJ8uJ8Zv4VPGECZcnVoig_0.jpg
Already copied: 9OYKSRIhSLHAaj3dkgUOJw_0.jpg
Already copied: 9QpLijtT9WwmSW9lWgDnsA_0.jpg
Already copied: 9QzFH9U6FxRPj-1c3f5ADA_0.jpg
Already copied: 9Tst71gS7U8SiJhVVu4ekA_0.jpg
Already copied: 9UZsn9OYnEkIGJv5y9m1sQ_0.jpg
Already copied: 9UhV4YlaKjsrkjC_kMmfqQ_0.jpg
Already copied: 9VjwmbcRat_GnMJQVU1bxw_0.jpg
Already copied: 9aa1Ycot6OWUDig_aPOc1Q_0.jpg
Already copied: 9ein1gARPSR6vCQO2t9XUA_0.jpg
Already copied: 9elBzuCZ6ADZ7M1FyYh6Ow_0.jpg
Already copied: 9esSpTWSpuQhsov4gExI0w_0.jpg
Already copied: 9jE2rL4F3fDAK4wZF92zVg_0.jpg
Already copied: 9mOC5bZZngNc8wnYUn-Lvw_0.jpg
Already copied: 9osscyT5XgrzKkfPn-tjoQ_0.jpg
Already copied: 9qwuRijJwxFtfejZPoRFsw_0.jpg
Already copied: 9sMmTwz6srFpeCXRHBrfHw_0.jpg
Already copied: 9vnTx9mNTkCdX7xQkz4-bQ_0.jpg
Already copied: 9vuMWThNL_Jm4o81MaB7oA_0.jpg
Already copied: 9ydwJPddR4pusycPzfvNFg_0.jpg
Already copied: A0-Z6ObAMrrjM6q5Va0c1Q_0.jpg
Already copied: A05K1p4Nc2OZz_KsnzTi0A_0.jpg
Already copied: A5Ndp2YLQMLQy9qdLGKrUg_0.jpg
Already copied: A8osyuAUYz-KuMKF32_opg_0.jpg
Already copied: AAb1CAgD1kMscxgxRUnVRg_0.jpg
Already copied: AEUCI7jlyWtUchxhcVszLw_0.jpg
Already copied: AFDTWfeF01Aa3TKyuwANSQ_0.jpg
Already copied: AHyfHNK_aSyI-bW9SCJHZg_0.jpg
Already copied: ALGi17PRoJ0u3TA9nGYkOw_0.jpg
Already copied: AN0USTM-a2RWsN5P7QkuCw_0.jpg
Already copied: AO4CWTiLLQwVB7bQYkobug_0.jpg
Already copied: AOY0tZ2ny8v9lhOr0sFAGg_0.jpg
Already copied: AQU-z-LGbYe8Azb0ToBeNQ_0.jpg
Already copied: ARrKhCYe7LhltaqQOzotvA_0.jpg
Already copied: ASfd-V8IXyNr-DtE-0UD0A_0.jpg
Already copied: AW7uSiNLKDVsw165uqrASg_0.jpg
Already copied: AYnu6FK0KZ62QUVNztP9aA_0.jpg
Already copied: A_85O6e9cLlyMGmFtEuOdg_0.jpg
Already copied: Aj-2JvxFzptXn8mrPG_oWw_0.jpg
Already copied: AmV44sy5X6RW_2ydottHHQ_0.jpg
Already copied: Ar8Ufvfa0IForls5XqFJTQ_0.jpg
Already copied: Ar__HdEzsCCZfgydEgOCHg_0.jpg
Already copied: AudviuEF_fs5isGpJGCEdQ_0.jpg
Already copied: AvPQt0fgoMNqA0UzG2lCgQ_0.jpg
Already copied: B06ShJEuz2mJG1yOf_d_wQ_0.jpg
Already copied: B51uLYrCbRbIuiu64shKYQ_0.jpg
Already copied: B5DxBb2UGri53bh54wro-w_0.jpg
Already copied: B8nbYhm-BauHZNFN2oNquA_0.jpg
Already copied: BDToYlN8sZ5oAOXNEUCezw_0.jpg
Already copied: BH9iAB3CxcUMeDnzN4czOw_0.jpg
Already copied: BHKPO3TchKILCeg7w0snsQ_0.jpg
Already copied: BHzcZx_6OsQBZwLfLLZpxA_0.jpg
Already copied: BI_wLb1MutdTF9yGyagdLA_0.jpg
Already copied: BKwgACpHhkZQzHSvmXYGiw_0.jpg
Already copied: BKyUYJw50xoHJUzUVgDNnA_0.jpg
Already copied: BMNVaNkZ0Qj6PgTJCdSujA_0.jpg
Already copied: BMVNG98M0AT3mZeRO_TCZQ_0.jpg
Already copied: BOFAYq7l0PF7Lg2_Kn258w_0.jpg
Already copied: BPZCWz5u_ugyNL4E2BhXBw_0.jpg
Already copied: BT6qjdhXMOkU9mXeqmgEPA_0.jpg
Already copied: BVaUHZotSOGnhuV4zsj96w_0.jpg
Already copied: BWyB-MIYy1sj4Y-ZMeD4QA_0.jpg
Already copied: B_uhCJZeNSEgUdJJNbR3KA_0.jpg
Already copied: Ba8VqYMLy1Vqo90jDp8SKw_0.jpg
Already copied: BcyG1FHka5fnxS2bJZ2RFg_0.jpg
Already copied: BgxirwR3CE-c8Ln7EL7C-g_0.jpg
Already copied: BjPuotDxMHwsAJ8RoXzD-Q_0.jpg
Already copied: Blbuxun859llO235pdix0w_0.jpg
Already copied: BnQCZ_LrlHiWODqW4JydQg_0.jpg
Already copied: Bp82990WcDH8fd6W0GiqdA_0.jpg
Already copied: BqRJGkNGZD79P-4D595SPQ_0.jpg
Already copied: Bqc-MMPqDJJmYnzdVzd8Aw_0.jpg
Already copied: BzOwdUBdYQXSHeXecSPQAw_0.jpg
Already copied: BzvYdIo_u10fl_A2vTAjKg_0.jpg
Already copied: C-oQv2YqY2BbiNZZUCGm0w_0.jpg
Already copied: C2eaxizZw3t_gRPd5R7ePQ_0.jpg
Already copied: C8VVIsefoBiRXSI8sS2Aag_0.jpg
Already copied: CCViv5o3Ilgg4mQQauI-2Q_0.jpg
Already copied: CCvSkq9IsFJLx0Z82MoJdw_0.jpg
Already copied: CJKLsu7eCpagDcWpsz5OvA_0.jpg
Already copied: CKPqh5qJjNhb32f0L0i7qg_0.jpg
Already copied: CLw9b2PX9HlmVLtpCnu15A_0.jpg
Already copied: CQhP0Ksgn83-WTFDX1sx9w_0.jpg
Already copied: CU_ZKFZBV_iJuWxvjvMMLA_0.jpg
Already copied: CUgeDh2TC03xrHhqXylbdg_0.jpg
Already copied: CYpvPpF3TNn3mebfMuK2LQ_0.jpg
Already copied: CZN_-VncQJ9dvstaWucAJw_0.jpg
Already copied: C_Nz2ves6oE3RFLYmcj3_Q_0.jpg
Already copied: C_frdSvSHWcYFv0TorCyig_0.jpg
Already copied: CaAQ_sqeLu71eNXbBOvkvg_0.jpg
Already copied: CbjtQ_mA1fPHF9BtiTkOjw_0.jpg
Already copied: CcckwgBwJ54QvFPYDT6URg_0.jpg
Already copied: Cck2cYtr-MxWfzp_MRMigQ_0.jpg
Already copied: CekUqPxA6DFC5jgQChmEwQ_0.jpg
Already copied: Ch9nn6stFCFpoqvDQwiZzQ_0.jpg
Already copied: ChIVe403HR8eJ07MHNKCgQ_0.jpg
Already copied: CjHEp5WlLZuKIhsjsSNxOQ_0.jpg
Already copied: CjaixqhH0BFAWAr-NqAYuA_0.jpg
Already copied: ClV15EyHw8gDptH_P9nCdQ_0.jpg
Already copied: CnmECN5jiVT4_d63Irx5XA_0.jpg
Already copied: Cq9JEl88M2RNZ9q3j87UTg_0.jpg
Already copied: CxhcTijxE8JQASAcWl0xqg_0.jpg
Already copied: CxmJXX4B0NpRGTcMNH56-A_0.jpg
Already copied: CyHRafAbn35YG7qmQb3NIw_0.jpg
Already copied: D1ZQcY1Rj5MqW5obtidpHw_0.jpg
Already copied: D2YYGpsBBK0nRkNXXshZIQ_0.jpg
Already copied: D3EM_rD7XwD8rjtLT3VsCA_0.jpg
Already copied: D42T31nbQILpC9z-I2x8nw_0.jpg
Already copied: DB8ACLdZxwR8TJkzRBicPA_0.jpg
Already copied: DDrNmyfwOXneoTIp5V69oA_0.jpg
Already copied: DNG5jpipikLkvhllARf7Sg_0.jpg
Already copied: DNdnpmfxtMkQEArYgiHNQw_0.jpg
Already copied: DT5_yIFrCJuXbKBOlGiQEA_0.jpg

# Remove duplicates from LabelImage output

In [10]:
# 好像是remove from 某一个folder，if file exists in a list?
# 我不记得了

import os
import shutil

def get_modified_jpg_filenames_in_directory(directory, remove_first_n=0):
    jpg_files = []
    for filename in os.listdir(directory):
        if filename.lower().endswith(('.jpg', '.jpeg')):
            modified_filename = filename[remove_first_n:]  # Remove first n characters
            jpg_files.append(modified_filename)
    return jpg_files

def compare_and_copy_images(LI_filenames, Yolo_filenames, source_dir_LI, source_dir_Yolo, destination_dir):
    # Create a set of filenames for efficient comparison
    LI_set = set(LI_filenames)
    Yolo_set = set(Yolo_filenames)

    # Find images that only exist in Yolo_filenames
    unique_to_yolo = Yolo_set - LI_set

    # Copy images unique to Yolo_filenames to destination directory
    for filename in unique_to_yolo:
        source_path = os.path.join(source_dir_Yolo, filename)
        destination_path = os.path.join(destination_dir, filename)
        shutil.copyfile(source_path, destination_path)

    # Find images that only exist in LI_filenames
    unique_to_li = LI_set - Yolo_set

    # Save images unique to LI_filenames to a list
    unique_to_li_list = list(unique_to_li)

    # Print images unique to LI_filenames
    print("Images unique to LI_filenames:")
    for filename in unique_to_li_list:
        print(filename)
    
    return unique_to_li_list

# Usage:
source_dir_LI = '/Users/wenlanzhang/Downloads/images/'
source_dir_Yolo = '/Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Yolo_Train_Waste_Major/'
destination_dir = '/Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/tobelabel/'

LI_filenames = get_modified_jpg_filenames_in_directory(source_dir_LI, remove_first_n=9)
Yolo_filenames = get_modified_jpg_filenames_in_directory(source_dir_Yolo)

unique_to_li_list = compare_and_copy_images(LI_filenames, Yolo_filenames, source_dir_LI, source_dir_Yolo, destination_dir)

Images unique to LI_filenames:

In [48]:
# Remove file from folder 2, if exists folder 1

import os

# Set the path to your folders
folder1 = '/Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/Train0211/images/'
folder2 = '/Users/wenlanzhang/Downloads/PhD_UCL/Data/GoogleStreetView/ad/'

# Get a list of files in each folder
files_in_folder1 = set(os.listdir(folder1))
files_in_folder2 = set(os.listdir(folder2))

# Find duplicate files in folder 2
duplicates = files_in_folder1.intersection(files_in_folder2)

# Remove duplicates from folder 2
for file in duplicates:
    path_to_file = os.path.join(folder2, file)
    os.remove(path_to_file)
    print(f"Removed '{file}' from {folder2}")

print("Done removing duplicates.")

Done removing duplicates.

# check data upload to server

Self: 2328 in total - Uploaded finished.    

Variable:   
file_list:have been uploaed to myraid, copied from ls in myraid/Data (by 02.22: 2081)

In [1]:
import os
import shutil

# Original string with files separated by spaces
file_string = '''Animal.JPG               IMG_20230212_082113.jpg  IMG_6488.JPG  IMG_7142.JPG  IMG_7498.JPG  IMG_8072.JPG  IMG_8387.JPG
IMG_0624.JPG             IMG_20230212_082117.jpg  IMG_6489.JPG  IMG_7143.JPG  IMG_7499.JPG  IMG_8073.JPG  IMG_8388.JPG
IMG_0625.JPG             IMG_20230212_082119.jpg  IMG_6490.JPG  IMG_7144.JPG  IMG_7500.JPG  IMG_8074.JPG  IMG_8389.JPG
IMG_0626.JPG             IMG_20230212_082124.jpg  IMG_6491.JPG  IMG_7145.JPG  IMG_7501.JPG  IMG_8075.JPG  IMG_8390.JPG
IMG_0627.JPG             IMG_20230212_082128.jpg  IMG_6492.JPG  IMG_7146.JPG  IMG_7502.JPG  IMG_8076.JPG  IMG_8391.JPG
IMG_0628.JPG             IMG_20230212_082138.jpg  IMG_6493.JPG  IMG_7147.JPG  IMG_7503.JPG  IMG_8077.JPG  IMG_8392.JPG
IMG_0629.JPG             IMG_20230212_082143.jpg  IMG_6494.JPG  IMG_7148.JPG  IMG_7504.JPG  IMG_8078.JPG  IMG_8393.JPG
IMG_20230212_082035.jpg  IMG_6483.JPG             IMG_7136.JPG  IMG_7493.JPG  IMG_8067.JPG  IMG_8382.JPG
IMG_20230212_082037.jpg  IMG_6484.JPG             IMG_7137.JPG  IMG_7494.JPG  IMG_8068.JPG  IMG_8383.JPG
IMG_20230212_082052.jpg  IMG_6485.JPG             IMG_7139.JPG  IMG_7495.JPG  IMG_8069.JPG  IMG_8384.JPG
IMG_20230212_082103.jpg  IMG_6486.JPG             IMG_7140.JPG  IMG_7496.JPG  IMG_8070.JPG  IMG_8385.JPG
IMG_20230212_082108.jpg  IMG_6487.JPG             IMG_7141.JPG  IMG_7497.JPG  IMG_8071.JPG  IMG_8386.JPG'''

# Convert the string to a list by splitting it by spaces
file_list = file_string.split()

# Folder path
source_folder_path = '/Users/wenlanzhang/Self/'
destination_folder_path = '/Users/wenlanzhang/Selftodo/'

# Get the list of files in the folder
folder_files = os.listdir(source_folder_path)

# Check which files from the folder are missing in the file list 
# missing_files = [file.strip() for file in file_list if file.strip() not in folder_files]
missing_files = [file.strip() for file in folder_files if file.strip() not in file_list]




# Print the missing files
print("Files missing in the folder:")
for file in missing_files:
    print(file)
    
    # Copy missing files to destination folder
    source_file = os.path.join(source_folder_path, file)
    destination_file = os.path.join(destination_folder_path, file)
    shutil.copy(source_file, destination_file)
    print("Missing files copied to destination folder.")

Files missing in the folder:
IMG_0799.JPG
Missing files copied to destination folder.
IMG_0772.JPG
Missing files copied to destination folder.
IMG_0766.JPG
Missing files copied to destination folder.
IMG_0809.JPG
Missing files copied to destination folder.
IMG_0808.JPG
Missing files copied to destination folder.
IMG_0767.JPG
Missing files copied to destination folder.
IMG_0773.JPG
Missing files copied to destination folder.
IMG_0798.JPG
Missing files copied to destination folder.
IMG_0765.JPG
Missing files copied to destination folder.
IMG_0771.JPG
Missing files copied to destination folder.
IMG_0759.JPG
Missing files copied to destination folder.
IMG_0758.JPG
Missing files copied to destination folder.
IMG_0770.JPG
Missing files copied to destination folder.
IMG_0764.JPG
Missing files copied to destination folder.
IMG_0748.JPG
Missing files copied to destination folder.
IMG_0760.JPG
Missing files copied to destination folder.
IMG_0774.JPG
Missing files copied to destination folder.
.DS_Store
Missing files copied to destination folder.
IMG_0775.JPG
Missing files copied to destination folder.
IMG_0761.JPG
Missing files copied to destination folder.
IMG_0749.JPG
Missing files copied to destination folder.
IMG_0788.JPG
Missing files copied to destination folder.
IMG_0777.JPG
Missing files copied to destination folder.
IMG_0763.JPG
Missing files copied to destination folder.
IMG_0762.JPG
Missing files copied to destination folder.
IMG_0776.JPG
Missing files copied to destination folder.
IMG_0789.JPG
Missing files copied to destination folder.
IMG_0856.JPG
Missing files copied to destination folder.
IMG_0895.JPG
Missing files copied to destination folder.
IMG_0894.JPG
Missing files copied to destination folder.
IMG_0880.JPG
Missing files copied to destination folder.
IMG_0857.JPG
Missing files copied to destination folder.
IMG_0909.JPG
Missing files copied to destination folder.
IMG_0869.JPG
Missing files copied to destination folder.
IMG_0855.JPG
Missing files copied to destination folder.
IMG_0896.JPG
Missing files copied to destination folder.
IMG_0897.JPG
Missing files copied to destination folder.
IMG_0854.JPG
Missing files copied to destination folder.
IMG_0868.JPG
Missing files copied to destination folder.
IMG_0908.JPG
Missing files copied to destination folder.
IMG_0850.JPG
Missing files copied to destination folder.
IMG_0878.JPG
Missing files copied to destination folder.
IMG_0893.JPG
Missing files copied to destination folder.
IMG_0892.JPG
Missing files copied to destination folder.
IMG_0879.JPG
Missing files copied to destination folder.
IMG_0851.JPG
Missing files copied to destination folder.
IMG_0847.JPG
Missing files copied to destination folder.
IMG_0853.JPG
Missing files copied to destination folder.
IMG_0891.JPG
Missing files copied to destination folder.
IMG_0852.JPG
Missing files copied to destination folder.
IMG_0846.JPG
Missing files copied to destination folder.
IMG_0903.JPG
Missing files copied to destination folder.
IMG_0863.JPG
Missing files copied to destination folder.
IMG_0876.JPG
Missing files copied to destination folder.
IMG_0862.JPG
Missing files copied to destination folder.
IMG_0902.JPG
Missing files copied to destination folder.
IMG_0900.JPG
Missing files copied to destination folder.
IMG_0848.JPG
Missing files copied to destination folder.
IMG_0874.JPG
Missing files copied to destination folder.
IMG_0860.JPG
Missing files copied to destination folder.
IMG_0861.JPG
Missing files copied to destination folder.
IMG_0875.JPG
Missing files copied to destination folder.
IMG_0849.JPG
Missing files copied to destination folder.
IMG_0901.JPG
Missing files copied to destination folder.
IMG_0905.JPG
Missing files copied to destination folder.
IMG_0871.JPG
Missing files copied to destination folder.
IMG_0859.JPG
Missing files copied to destination folder.
IMG_0858.JPG
Missing files copied to destination folder.
IMG_0864.JPG
Missing files copied to destination folder.
IMG_0870.JPG
Missing files copied to destination folder.
IMG_0910.JPG
Missing files copied to destination folder.
IMG_0904.JPG
Missing files copied to destination folder.
IMG_0906.JPG
Missing files copied to destination folder.
IMG_0866.JPG
Missing files copied to destination folder.
IMG_0872.JPG
Missing files copied to destination folder.
IMG_0899.JPG
Missing files copied to destination folder.
IMG_0898.JPG
Missing files copied to destination folder.
IMG_0873.JPG
Missing files copied to destination folder.
IMG_0867.JPG
Missing files copied to destination folder.
IMG_0907.JPG
Missing files copied to destination folder.
IMG_0790.JPG
Missing files copied to destination folder.
IMG_0784.JPG
Missing files copied to destination folder.
IMG_0753.JPG
Missing files copied to destination folder.
IMG_0747.JPG
Missing files copied to destination folder.
IMG_0800.JPG
Missing files copied to destination folder.
IMG_0814.JPG
Missing files copied to destination folder.
IMG_0815.JPG
Missing files copied to destination folder.
IMG_0801.JPG
Missing files copied to destination folder.
IMG_0746.JPG
Missing files copied to destination folder.
IMG_0752.JPG
Missing files copied to destination folder.
IMG_0785.JPG
Missing files copied to destination folder.
IMG_0791.JPG
Missing files copied to destination folder.
IMG_0787.JPG
Missing files copied to destination folder.
IMG_0793.JPG
Missing files copied to destination folder.
IMG_0744.JPG
Missing files copied to destination folder.
IMG_0750.JPG
Missing files copied to destination folder.
IMG_0778.JPG
Missing files copied to destination folder.
IMG_0803.JPG
Missing files copied to destination folder.
IMG_0802.JPG
Missing files copied to destination folder.
IMG_0816.JPG
Missing files copied to destination folder.
IMG_0779.JPG
Missing files copied to destination folder.
IMG_0751.JPG
Missing files copied to destination folder.
IMG_0745.JPG
Missing files copied to destination folder.
IMG_0792.JPG
Missing files copied to destination folder.
IMG_0786.JPG
Missing files copied to destination folder.
IMG_0782.JPG
Missing files copied to destination folder.
IMG_0796.JPG
Missing files copied to destination folder.
IMG_0769.JPG
Missing files copied to destination folder.
IMG_0741.JPG
Missing files copied to destination folder.
IMG_0755.JPG
Missing files copied to destination folder.
IMG_0812.JPG
Missing files copied to destination folder.
IMG_0806.JPG
Missing files copied to destination folder.
IMG_0807.JPG
Missing files copied to destination folder.
IMG_0813.JPG
Missing files copied to destination folder.
IMG_0754.JPG
Missing files copied to destination folder.
IMG_0768.JPG
Missing files copied to destination folder.
IMG_0797.JPG
Missing files copied to destination folder.
IMG_0783.JPG
Missing files copied to destination folder.
IMG_0795.JPG
Missing files copied to destination folder.
IMG_0781.JPG
Missing files copied to destination folder.
IMG_0756.JPG
Missing files copied to destination folder.
IMG_0742.JPG
Missing files copied to destination folder.
IMG_0805.JPG
Missing files copied to destination folder.
IMG_0811.JPG
Missing files copied to destination folder.
IMG_0810.JPG
Missing files copied to destination folder.
IMG_0804.JPG
Missing files copied to destination folder.
IMG_0743.JPG
Missing files copied to destination folder.
IMG_0757.JPG
Missing files copied to destination folder.
IMG_0780.JPG
Missing files copied to destination folder.
IMG_0794.JPG
Missing files copied to destination folder.

In [2]:
# just to check number

file_string = '''
IMG_20230212_080905.jpg  IMG_6361.JPG             IMG_7065.JPG  IMG_7399.JPG  IMG_8032.JPG  IMG_8365.JPG'''

# Convert the string to a list by splitting it by spaces
file_list = file_string.split()

len(file_list)

2328